### ISSUE TITLE
Chrome is completely broken

### ISSUE THREAD

**Issue by ValentinH** [cypress-io/cypress#1994] opened 2018-06-20 20:08 UTC
### Current behavior:
I'm trying to use Cypress on a new project. I had tried it a few months ago and it was working fine. Today, I installed it via NPM in my app and here's what I get when I try to run a spec in Chrome 67:
![image](https://user-images.githubusercontent.com/2678610/41681699-bc5d0250-74d5-11e8-8084-6f4c2873f703.png)

Here's the Chrome devtools display: ^^
![image](https://user-images.githubusercontent.com/2678610/41681938-7c17dd5e-74d6-11e8-833d-811c4fa32753.png)

I have tried the instructions from https://github.com/cypress-io/cypress/issues/1239#issuecomment-362363993 and also:
`rm -rf  ~/Library/Caches/Cypress`

Electron runs fine though.

What else can I do?
### Versions
Cypress: 3.0.1
OS: macOS 10.13.4 (17E199)

**Comment by brian-mann** [comment] 2018-06-20 22:21
Chrome did something in the later/latest versions that is messing with the GPU.

This is actually a duplicate of a previously opened issue here: https://github.com/cypress-io/cypress/issues/1617#issuecomment-397373555

You can see my comment - it will likely fix your issue. If you wanted to be **SUPER** helpful to us, you might could start removing the default arguments that Cypress adds until you figure out the one that is causing this behavior. I'm 100% sure it is a command line argument.

**Closed by brian-mann** 2018-06-20 22:21 UTC
Labels: type: duplicate

**Comment by ValentinH** [comment] 2018-06-21 04:56
Thanks for the answer and sorry for the duplicate :/

Where can I find the list of default arguments passed by Cypress?

**Comment by brian-mann** [comment] 2018-06-21 15:17
@ValentinH  https://docs.cypress.io/api/plugins/browser-launch-api.html#
