### ISSUE TITLE
Wrong domain in inject.js

### ISSUE THREAD

**Issue by Victroll** [cypress-io/cypress#1537] opened 2018-04-04 07:55 UTC
### Current behavior:
Our app uses a domain like `xxx.yyy.zzz/whatever` but when launching a simple login test, the `document.domain` value is `yyy.zzz`, that is, the firs part of the domain disappears. For that reason, every call to our backend fails because `yyy.zzz` can't be reached.

### Desired behavior:
The var `document.domain` that the injector under the file `node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/util/inject.js` injects should be the right one or not do it at all.

In our case, if we just remove the code `document.domain = '" + domain + "';`, everything works fine. I'm not sure about the reason of this injection and if it could be modified through plugins (not changing the base code itself).

Thanks in advance for any comment about this :smile: 

- Operating System: Ubuntu 17.10
- Cypress Version: 2.1.0
- Browser Version: Chrome 63.0.3239.108

**Comment by jennifer-shehane** [comment] 2018-04-04 16:43
Source file: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/inject.coffee#L5

Where it is used: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/rewriter.coffee#L17

This has to do with how the [proxy](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/controllers/proxy.coffee#L171) is handled in Cypress, which I wish we had a better explanation of, but we are open to work in progress PRs if you are able to fix the cutoff of the domain.

**Comment by brian-mann** [comment] 2018-04-10 16:09
@Victroll based on what you provided I can't really understand what the problem is. There are a huge number of tests around the `document.domain` behavior as that is an essential element to how Cypress works - and if it did not work correctly then nothing at all would work in Cypress.

Can you put together a small reproducible example of what is happening, and provide test code? Things like screenshots would also be helpful.

**Comment by jennifer-shehane** [comment] 2019-04-24 16:09
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-24 16:09 UTC
Labels: stage: needs information
