### ISSUE TITLE
When the feature multiple cy.origin or window tab will be released ?

### ISSUE THREAD

**Issue by adnanerlansyah403** [cypress-io/cypress#28439] opened 2023-12-01 12:01 UTC
### What would you like?

I like this feature because on my project or website it's needed and I still get hard to achieve multiple new tab or window.

### Why is this needed?

Because my project or website need the test case for multiple tab or window I ensure if Cypress has this feature then it will be more powerful.

**Comment by jennifer-shehane** [comment] 2023-12-01 16:58
We recently released a puppeteer plugin which can be used to test multiple tabs. See my comment here: https://github.com/cypress-io/cypress/issues/6251#issuecomment-1836454467

Closing as duplicate of https://github.com/cypress-io/cypress/issues/6251

**Closed as completed by jennifer-shehane** 2023-12-01 16:58 UTC
Labels: type: duplicate
