### ISSUE TITLE
cypress test automation of salesforce application 

### ISSUE THREAD

**Issue by CYPRESSSA** [cypress-io/cypress#26951] opened 2023-06-06 15:19 UTC
### Current behavior

i m trying to automate tests on my ui on salesforce app , i used the cypress recorder to record my steps and generate the script but when i try to execute it , it show me a bug at the step of detecting the app launcher , did anyone tried this before or had the same issue ? 
<img width="943" alt="image" src="https://github.com/cypress-io/cypress/assets/135593723/23a648a1-f412-4bf4-9f80-534eef566212">

### Desired behavior

automate tests using cypress recorder ( test of creating an account for example)

### Test code to reproduce

describe("test1 APP LAUNCH", () => {
  it("tests test1 APP LAUNCH", () => {
    cy.viewport(670, 601);
    //cy.visit("https://usmbaacma-dev-ed.develop.my.salesforce.com/");
    cy.visit("https://login.salesforce.com/");
    cy.get("#username").click();
    cy.get("#username").type("safae.aarab2@usmba.ac.ma");
    cy.get("#password").click();
    cy.get("#password").type("Sasa.123");
    cy.get("#Login").click();
    cy.location("href").should("eq", "https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome&sid=00D67000000RxkX%21AQ4AQJYThQykIfb9NFKtkveBMf40RZ1DHnMVtI3JW0Zh6nbnZfj3yHxIaY0KHFtuo4lVed3m2BLJjO7CnAAxjxQt7Gt4x_Ne&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENjcwMDAwMDBSeGtYIiwia2lkIjoie1widFwiOlwiMDBENjcwMDAwMDBSeGtYXCIsXCJ2XCI6XCIwMkc2NzAwMDAwMEhRckhcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTY3MDAwMDBDRno0S1wifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTY4NjA2NDA5NDU0MywiZXhwIjowfQ%3D%3D..8HgWt1lqQarUkHof.a6KYk7NpLfwRmSqtGcWBZQ%3D%3D.nziOh89Eg5NybYKvqNRR9Q%3D%3D");
    cy.get("div.slds-r5").click();
    cy.get("#input-98").click();
    cy.get("#input-98").type("SALES");
    cy.get("one-app-launcher-menu-item:nth-of-type(3) b").click();
    cy.location("href").should("eq", "undefined");
  });
});

### Cypress Version

v 12.13.0

### Node version

v18.16.0

### Operating System

WINDOW 10

### Debug Logs

```shell
tests test1 APP LAUNCHfailed
TEST BODY
1
viewport670, 601
2
visithttps://login.salesforce.com/
3
get#username
4
click
5
get#username
6
typesafae.aarab2@usmba.ac.ma
(xhr)GET 200 https://a.sfdcstatic.com/digital/one-trust/core/stable/consent/742a15b9-6aa4-4c2f-99c1-ad4ca220cf96/742a15b9-6aa4-4c2f-99c1-ad4ca220cf96.json
(xhr)GET 200 https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location
(xhr)GET 200 https://www.salesforce.com/login-messages/promos/_jcr_content.personalization.pagemetadata.v2.json
7
get#password
8
click
9
get#password
10
typeSasa.123
(xhr)GET 403 https://c.salesforce.com/wbin/www-core/f/g
11
get#Login
12
click
(page load)--page loaded--
(fetch)GET 200 https://a.sfdcstatic.com/digital/one-trust/core/stable/consent/742a15b9-6aa4-4c2f-99c1-ad4ca220cf96/63c0cd1c-5ecb-4f24-8086-ee0ba0e2f894/fr.json
(fetch)GET 200 https://a.sfdcstatic.com/digital/one-trust/core/stable/scripttemplates/202302.1.0/assets/otCenterRounded.json
(fetch)GET 200 https://a.sfdcstatic.com/digital/one-trust/core/stable/scripttemplates/202302.1.0/assets/v2/otPcTab.json
(fetch)GET 200 https://a.sfdcstatic.com/digital/one-trust/core/stable/scripttemplates/202302.1.0/assets/otCommonStyles.css
(fetch)GET 200 https://cdn.cookielaw.org/logos/static/ot_guard_logo.svg
(new url)https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome&sid=00D67000000RxkX%21AQ4AQCfkEqpWZ0.oule0Tl7bMZJAU1nmRZIidjMHAZkGkQtALFV.CbjJmCk_k2EDWpCN3xavTfH5FbfGBDtWRGirXO4BJY_.&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENjcwMDAwMDBSeGtYIiwia2lkIjoie1widFwiOlwiMDBENjcwMDAwMDBSeGtYXCIsXCJ2XCI6XCIwMkc2NzAwMDAwMEhRckhcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTY3MDAwMDBDRno0S1wifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTY4NjA2NDI3NDE3MSwiZXhwIjowfQ%3D%3D..g6NIE2yRP-TTreps.zgrUcR6qR8M5EMCyTXS3FQ%3D%3D.QOBrld3L5v1rEsoglpT_rQ%3D%3D
13
locationhref
14
assertexpected null to equal **https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome&sid=00D67000000RxkX%21AQ4AQJYThQykIfb9NFKtkveBMf40RZ1DHnMVtI3JW0Zh6nbnZfj3yHxIaY0KHFtuo4lVed3m2BLJjO7CnAAxjxQt7Gt4x_Ne&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENjcwMDAwMDBSeGtYIiwia2lkIjoie1widFwiOlwiMDBENjcwMDAwMDBSeGtYXCIsXCJ2XCI6XCIwMkc2NzAwMDAwMEhRckhcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTY3MDAwMDBDRno0S1wifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTY4NjA2NDA5NDU0MywiZXhwIjowfQ%3D%3D..8HgWt1lqQarUkHof.a6KYk7NpLfwRmSqtGcWBZQ%3D%3D.nziOh89Eg5NybYKvqNRR9Q%3D%3D**
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?preloadActions
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=0&ui-force-components-controllers-empApi.EmpApi.getEmpConfig=1&ui-global-components-one-favorites.Favorites.getFavorites=1&ui-global-components-one-header.Header.getSettings=1&ui-global-components-one-systemMessage.SystemMessage.getSystemMessages=1&ui-notifications-components-notifications-controller.Notifications.getInitializationValues=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=1&ui-force-components-controllers-hostConfig.HostConfig.getConfigData=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=2&ui-force-components-controllers-recordGlobalValueProvider.RecordGvp.getRecord=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=3&ui-force-components-controllers-socialPhoto.SocialPhoto.resolvePhotos=1
(new url)https://usmbaacma-dev-ed.develop.lightning.force.com/lightning/setup/SetupOneHome/home
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=4&ui-force-components-controllers-platformStateManager.PlatformStateManager.getSetupTreeNodes=1&ui-setup-components-aura-components-tree.SetupTree.getMenuNodes=1&ui-setup-components-aura-components-tree.SetupTree.getTreeApps=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=5&ui-setup-components-aura-components-createmenu.OneSetupCreateMenu.getMenuItemsToHide=1&ui-setup-components-aura-components-tree.SetupTree.getTreeApps=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=6&ui-setup-components-aura-components-recentitems.RecentItems.getRecentItems=1&ui-setup-components-aura-components-recentitems.RecentItems.hasAccessToViewRecentItems=1&ui-setupassistant-components-aura.SetupAssistantWelcomeMat.getInitialStateTile=1&ui-setupassistant-components-aura.SetupAssistantWelcomeMat.getPercentComplete=1&ui-setupassistant-components-aura.SetupAssistantWelcomeMat.getShouldDisplay=1&ui-setupassistant-components-aura.SetupAssistantWelcomeMat.getState=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=7&ui-instrumentation-components-beacon.InstrumentationBeacon.sendData=1
(xhr)GET 200 https://usmbaacma-dev-ed.develop.lightning.force.com/_nc_external/system/security/session/SessionTimeServlet?buster=1686064278661
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=8&ui-force-components-controllers-defenseHook.DefenseHook.getDefenseHook=1&ui-force-components-controllers-slds.DynamicApp.isWcagEnabled=1&ui-global-components-one-globalCreate.GlobalCreate.getDockableActionsList=1&ui-global-components-one-unsupportedContainer.UnsupportedContainer.getSettings=1&ui-global-components-one-userProfileCard.UserProfileCard.loadProfileCardInfo=1&ui-identity-components-sessiontimeoutwarn.SessionTimeoutWarn.getSessionTimeoutConfig=1&ui-notifications-components-notifications-controller.Notifications.getNotifications=1&ui-search-components-forcesearch-sgdp.PermsAndPrefsCache.getPermsAndPrefs=1&ui-support-components-crossFrameApiManager.CrossFrameApiManager.getIsLightningOpenCtiUser=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=9&ui-search-components-forcesearch-sgdp.ScopesCache.getScopeMaps=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=10&ui-setup-components-aura-components-gear.Gear.getGearSetupApps=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=11&ui-setup-components-aura-components-gear.Gear.getPermissions=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=12&ui-setup-components-aura-components-gear.Gear.getEntitySupport=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=13&ui-global-components-one-onboardingManager.OnboardingManager.getInitData=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=14&ui-force-components-controllers-platformStateManager.PlatformStateManager.getActionOverrides=4&ui-force-components-controllers-platformStateManager.PlatformStateManager.getFlexipageInfo=4&ui-force-components-controllers-platformStateManager.PlatformStateManager.getIsLWCFlexipageEnabled=4&ui-force-components-controllers-platformStateManager.PlatformStateManager.getKeyPrefixesWithRecordTypes=4
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=15&ui-global-components-one-systemMessage.SystemMessage.getSystemMessages=1
(xhr)POST 200 https://usmbaacma-dev-ed.develop.lightning.force.com/aura?r=16&ui-force-components-controllers-fingerprint.Fingerprint.logFingerprint=1
AssertionError
Timed out retrying after 4000ms: expected null to equal 'https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome&sid=00D67000000RxkX%21AQ4AQJYThQykIfb9NFKtkveBMf40RZ1DHnMVtI3JW0Zh6nbnZfj3yHxIaY0KHFtuo4lVed3m2BLJjO7CnAAxjxQt7Gt4x_Ne&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENjcwMDAwMDBSeGtYIiwia2lkIjoie1widFwiOlwiMDBENjcwMDAwMDBSeGtYXCIsXCJ2XCI6XCIwMkc2NzAwMDAwMEhRckhcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTY3MDAwMDBDRno0S1wifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTY4NjA2NDA5NDU0MywiZXhwIjowfQ%3D%3D..8HgWt1lqQarUkHof.a6KYk7NpLfwRmSqtGcWBZQ%3D%3D.nziOh89Eg5NybYKvqNRR9Q%3D%3D'
cypress/e2e/test1 APP LAUNCH.cy.js:11:25
   9 |     cy.get("#password").type("Sasa.123");
  10 |     cy.get("#Login").click();
> 11 |     cy.location("href").should("eq", "https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome&sid=00D67000000RxkX%21AQ4AQJYThQykIfb9NFKtkveBMf40RZ1DHnMVtI3JW0Zh6nbnZfj3yHxIaY0KHFtuo4lVed3m2BLJjO7CnAAxjxQt7Gt4x_Ne&skipRedirect=1&lm=eyJlbmMiOiJBMjU2R0NNIiwiYXVkIjoiMDBENjcwMDAwMDBSeGtYIiwia2lkIjoie1widFwiOlwiMDBENjcwMDAwMDBSeGtYXCIsXCJ2XCI6XCIwMkc2NzAwMDAwMEhRckhcIixcImFcIjpcImNvbnRlbnRkb29ydXNlcnRyYW5zaWVudGtleWVuY3J5cHRcIixcInVcIjpcIjAwNTY3MDAwMDBDRno0S1wifSIsImNyaXQiOlsiaWF0Il0sImlhdCI6MTY4NjA2NDA5NDU0MywiZXhwIjowfQ%3D%3D..8HgWt1lqQarUkHof.a6KYk7NpLfwRmSqtGcWBZQ%3D%3D.nziOh89Eg5NybYKvqNRR9Q%3D%3D");
     |                         ^
  12 |     cy.get("div.slds-r5").click();
  13 |     cy.get("#input-98").click();
  14 |     cy.get("#input-98").type("SALES");
```

**Comment by mschile** [comment] 2023-06-08 23:36
Hi @CYPRESSSA 👋, unfortunately, I wasn't able to reproduce your issue using your test code since I wasn't able to login. My guess is the `href` has a value that changes between runs. You could try changing it to something like:

```js
cy.location("href").should("contain", "https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome");
```

**Comment by CYPRESSSA** [comment] 2023-06-09 07:34
UPPPPPPPPPPPP

**Comment by CYPRESSSA** [comment] 2023-06-19 09:12
> Hi @CYPRESSSA 👋, unfortunately, I wasn't able to reproduce your issue using your test code since I wasn't able to login. My guess is the `href` has a value that changes between runs. You could try changing it to something like:
> 
> ```js
> cy.location("href").should("contain", "https://usmbaacma-dev-ed.develop.file.force.com/secur/contentDoor?startURL=https%3A%2F%2Fusmbaacma-dev-ed.develop.my.salesforce.com%2Flightning%2Fsetup%2FSetupOneHome%2Fhome");
> ```

Thank u for the answer , but i tried this and it doesn't work  ? IT SHOW THIS ERROR 
<img width="839" alt="image" src="https://github.com/cypress-io/cypress/assets/135593723/4e96e2b5-8101-45a4-9895-b9a3bd2c2af5">

**Comment by CYPRESSSA** [comment] 2023-06-21 10:25
did anyone had the same issue ?

**Comment by CYPRESSSA** [comment] 2023-06-21 10:27
@mschile  if u have a moment i ll send u my code to reproduce the same issue

**Comment by mschile** [comment] 2023-06-23 14:13
@CYPRESSSA, it's possible the href location value I provided may not have been correct. You'll just want to update it to a value that corresponds to the location of the salesforce page. If you don't need to verify the href, you could also just remove the `cy.location` command.

Since this issue doesn't appear to be a bug Cypress, I am going to go ahead and close the issue.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress).

**Closed as not planned by mschile** 2023-06-23 14:13 UTC
