### ISSUE TITLE
EEXIST: file already exists, mkdir 'C:\Cypress.Node\node_modules.bin\cypress'

### ISSUE THREAD

**Issue by gogamera** [cypress-io/cypress#5253] opened 2019-09-30 22:06 UTC

**Comment by ZwapKillrath** [comment] 2019-11-02 14:02
I see a \ missing between node_modules and .bin right?
I am having the same issue
@jennifer-shehane ?

**Comment by Krak86** [comment] 2020-01-09 07:41
I have the same issue.

**Comment by EdwinvanDessel** [comment] 2020-04-22 06:27
I have the same issue with a fresh installed 4.4.1 version

**Comment by jennifer-shehane** [comment] 2020-06-22 09:11
Duplicate of #1099

**Closed by jennifer-shehane** 2020-06-22 09:11 UTC
