### ISSUE TITLE
CypressError: Timed out retrying: coordsHistory must be at least 2 sets of coords

### ISSUE THREAD

**Issue by mmsudy** [cypress-io/cypress#3738] opened 2019-03-18 16:24 UTC
@jennifer-shehane @brian-mann @bahmutov #coordsHistory 

### Current behavior:

![image](https://user-images.githubusercontent.com/48072687/54543691-bba12180-4963-11e9-8b1d-93dfe778b513.png)

![image](https://user-images.githubusercontent.com/48072687/54543745-d4a9d280-4963-11e9-8611-e6ca55fb3ba5.png)

### Steps to reproduce: (app code and test code)
```js
cy.get('div._md-container.md-ink-ripple').click({multiple:true})
```

want to select all check boxes once at a time so, used `div` class

### Versions
cypress Version 3.1.5 , OS Windows 10, Chrome 72

**Comment by jennifer-shehane** [comment] 2019-03-19 06:38
Error being thrown: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L200

Yeah, this is not a great error message. Can you provide a reproducible example so that we can recreate this? App code + test code - just make a small repo of the isolated problem, not your entire repo. 

I tried doing `.click({multiple: true})` and couldn't recreate it.

**Comment by mmsudy** [comment] 2019-03-19 14:59
> Error being thrown: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L200
> 
> Yeah, this is not a great error message. Can you provide a reproducible example so that we can recreate this? App code + test code - just make a small repo of the isolated problem, not your entire repo.
> 
> I tried doing `.click({multiple: true})` and couldn't recreate it.

```
<div flex="30" style="margin-top:10px" class="flex-30">
                            <md-checkbox class="blue ng-pristine ng-untouched ng-valid ng-empty" ng-model="entity._profile.ext.minutebook_local" aria-label="minutebook location" ng-disabled="userMinutebook.access === 'read-only' || userMinutebook.access === 'summary-only'" tabindex="0" type="checkbox" role="checkbox" aria-disabled="false" aria-checked="false" aria-invalid="false"><div class="_md-container md-ink-ripple" md-ink-ripple="" md-ink-ripple-checkbox=""><div class="_md-icon"></div></div><div ng-transclude="" class="_md-label"><span class="ng-scope">
                                Minutebook is at our office
                            </span></div></md-checkbox>
                        </div>
<div flex="30" class="flex-30">
                            <md-checkbox class="blue ng-pristine ng-valid ng-empty ng-touched" ng-model="entity._profile.ext.corp_seal" aria-label="corporate seal" ng-disabled="userMinutebook.access === 'read-only' || userMinutebook.access === 'summary-only'" tabindex="0" type="checkbox" role="checkbox" aria-disabled="false" aria-checked="false" aria-invalid="false" style=""><div class="_md-container md-ink-ripple" md-ink-ripple="" md-ink-ripple-checkbox=""><div class="_md-icon"></div><div class="md-ripple-container"></div></div><div ng-transclude="" class="_md-label"><span class="ng-scope">
                                Corporate seal
                            </span></div></md-checkbox>
                        </div>

```
like this 13 elements only **ng-model** was different everything else is same 
instead of writing code for every model I have written 
cy.get('div._md-container.md-ink-ripple').click({multiple:true}) to select multiple check box

**Comment by jennifer-shehane** [comment] 2019-03-19 16:19
@mmsudy I think the styles would need to be provided as well. The provided html alone does not seem to produce the required effect needed for testing - the checkboxes are not visible. 

<img width="407" alt="Screen Shot 2019-03-19 at 10 48 25 PM" src="https://user-images.githubusercontent.com/1271364/54623068-315ad980-4a99-11e9-8b3b-6aa4a1dc4a6a.png">

**Comment by mmsudy** [comment] 2019-03-19 16:46
> @mmsudy I think the styles would need to be provided as well. The provided html alone does not seem to produce the required effect needed for testing - the checkboxes are not visible.
> 
> <img alt="Screen Shot 2019-03-19 at 10 48 25 PM" width="407" src="https://user-images.githubusercontent.com/1271364/54623068-315ad980-4a99-11e9-8b3b-6aa4a1dc4a6a.png">

![image](https://user-images.githubusercontent.com/48072687/54625109-40f40700-4a34-11e9-99af-d086e4b7f271.png)
[](url)

**Comment by jennifer-shehane** [comment] 2019-03-20 02:46
@mmsudy Can you provide the css from your stylesheet that affects these DOM elements where I can copy and paste them into my own stylesheet? Thanks!

**Comment by mmsudy** [comment] 2019-03-20 14:32
> @mmsudy Can you provide the css from your stylesheet that affects these DOM elements where I can copy and paste them into my own stylesheet? Thanks!

`
element.style {
}
._md-container.md-ink-ripple {
}
._md-container.md-ink-ripple {
}
._md-container.md-ink-ripple {
}
<style>…</style>
md-checkbox ._md-container {
    position: absolute;
    top: 50%;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    box-sizing: border-box;
    display: inline-block;
    width: 20px;
    height: 20px;
    left: 0;
    right: auto;
}
<style>…</style>
md-checkbox ._md-container {
    position: absolute;
    top: 50%;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    box-sizing: border-box;
    display: inline-block;
    width: 20px;
    height: 20px;
    left: 0;
    right: auto;
}
<style>…</style>
md-checkbox.md-default-theme .md-ink-ripple, md-checkbox .md-ink-ripple {
    color: rgba(0,0,0,0.54);
}
<style>…</style>
* {
    box-sizing: border-box;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    box-sizing: border-box;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
user agent stylesheet
div {
    display: block;
}
<style>…</style>
md-checkbox {
    box-sizing: border-box;
    display: inline-block;
    white-space: nowrap;
    cursor: pointer;
    outline: 0;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    position: relative;
    min-width: 20px;
    min-height: 20px;
    margin-left: 0;
    margin-right: 16px;
}
<style>…</style>
md-checkbox {
    box-sizing: border-box;
    display: inline-block;
    white-space: nowrap;
    cursor: pointer;
    outline: 0;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    position: relative;
    min-width: 20px;
    min-height: 20px;
    margin-left: 0;
    margin-right: 16px;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
.layout-row {
    -ms-flex-direction: row;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    flex-direction: row;
}
<style>…</style>
.layout-row {
    -ms-flex-direction: row;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    flex-direction: row;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
body, html {
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
    min-height: 100%;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
<style>…</style>
body {
    margin: 0;
    padding: 0;
    min-height: 100%;
    background: #fff;
    direction: ltr;
    font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 1.25em;
    color: #6a6c6f;
    overflow: visible !important;
}
<style>…</style>
body, html {
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
    min-height: 100%;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
<style>…</style>
body {
    margin: 0;
    padding: 0;
    min-height: 100%;
    background: #fff;
    direction: ltr;
    font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 1.25em;
    color: #6a6c6f;
    overflow: visible !important;
}
<style>…</style>
html.md-default-theme, html, body.md-default-theme, body {
    color: rgba(0,0,0,0.87);
    background-color: rgb(250,250,250);
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
body, html {
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
    min-height: 100%;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
<style>…</style>
html {
    margin: 0;
    padding: 0;
    min-height: 100%;
    background: #fff;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    overflow: visible !important;
    font-size: 10px;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
<style>…</style>
body, html {
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
    min-height: 100%;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
<style>…</style>
html {
    margin: 0;
    padding: 0;
    min-height: 100%;
    background: #fff;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    overflow: visible !important;
    font-size: 10px;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
<style>…</style>
html.md-default-theme, html, body.md-default-theme, body {
    color: rgba(0,0,0,0.87);
    background-color: rgb(250,250,250);
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
* {
    -webkit-font-smoothing: antialiased !important;
}
<style>…</style>
md-checkbox ._md-container:before {
    box-sizing: border-box;
    background-color: transparent;
    border-radius: 50%;
    content: '';
    position: absolute;
    display: block;
    height: auto;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    -webkit-transition: all .5s;
    transition: all .5s;
    width: auto;
}
<style>…</style>
md-checkbox ._md-container:before {
    box-sizing: border-box;
    background-color: transparent;
    border-radius: 50%;
    content: '';
    position: absolute;
    display: block;
    height: auto;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    -webkit-transition: all .5s;
    transition: all .5s;
    width: auto;
}
<style>…</style>
*:before, *:after {
    box-sizing: border-box;
}
<style>…</style>
*:before, *:after {
    box-sizing: border-box;
}
<style>…</style>
md-checkbox ._md-container:after {
    box-sizing: border-box;
    content: '';
    position: absolute;
    top: -10px;
    right: -10px;
    bottom: -10px;
    left: -10px;
}
<style>…</style>
md-checkbox ._md-container:after {
    box-sizing: border-box;
    content: '';
    position: absolute;
    top: -10px;
    right: -10px;
    bottom: -10px;
    left: -10px;
}
<style>…</style>
*:before, *:after {
    box-sizing: border-box;
}
<style>…</style>
*:before, *:after {
    box-sizing: border-box;
}
box-sizing:
border-box
;
color:
rgba(0, 0, 0, 0.54)
;
cursor:
pointer
;
direction:
ltr
;
display:
block
;
font-family:
"Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif
;
font-size:
12.5px
;
height:
20px
;
left:
0px
;
position:
absolute
;
right:
138.988px
;
text-size-adjust:
100%
;
top:
10px
;
transform:
matrix(1, 0, 0, 1, 0, -10)
;
user-select:
none
;
white-space:
nowrap
;
width:
20px
;
-webkit-box-direction:
normal
;
-webkit-font-smoothing:
antialiased
;
-webkit-tap-highlight-color:
rgba(0, 0, 0, 0)
`

**Comment by mmsudy** [comment] 2019-03-20 14:44
> @mmsudy Can you provide the css from your stylesheet that affects these DOM elements where I can copy and paste them into my own stylesheet? Thanks!
[css.docx](https://github.com/cypress-io/cypress/files/2988715/css.docx)

**Comment by jennifer-shehane** [comment] 2019-03-21 03:30
Hey @mmsudy, why did you close the issue? Did you resolve the problem?

**Comment by mmsudy** [comment] 2019-03-21 14:25
No it was accidental sorry for that

**Comment by jennifer-shehane** [comment] 2019-07-11 08:06
I've still been unable to reproduce this exactly with the html, css, and test code provided. 
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by themightychris** [comment] 2020-03-30 20:59
I'm running into this too, I suspect that the missing ingredient was CSS that pushes some of the to-be clicked elements out of the viewport

**Comment by jennifer-shehane** [comment] 2020-04-23 07:12
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run.

**Comment by mauricius** [comment] 2020-11-24 15:09
I have experienced this problem too. Apparently Cypress cannot get all the elements if a subset of them are outside the viewport. I temporarily solved it using a cycle, selecting only a small number of elements in each iteration
`cy.get('.tags > .tag:lt(20)').click({multiple:true})`

**Comment by beenushrestha** [comment] 2021-02-19 05:26
I am also searching the solution for this.
Scenario: All the elements should be selected.

DOM: (Couldn't post all the dom elements since there is character limit. All the elements have class names "isChecked")

<tbody><tr class="">
    <td>
        <input class="isChecked" id="ListOfSalesProducts_0__IsChecked" name="ListOfSalesProducts[0].IsChecked" type="checkbox" value="true"><input name="ListOfSalesProducts[0].IsChecked" type="hidden" value="false">
    </td>
    <td>
        4165
    </td>
    <td>
        <input class="noMarkAsreq" data-val="true" data-val-number="The field ID must be a number." id="ListOfSalesProducts_0__ID" name="ListOfSalesProducts[0].ID" type="hidden" value="4165">
        <label for="ListOfSalesProducts_0__IsChecked">Asendia_EPAQ_PLS_MBD_EL150</label>
    </td>
    <td>
        <div class="is-preferred-wrap details_hide">
            <input class="isPreferred" id="ListOfSalesProducts_0__IsPreferred" name="ListOfSalesProducts[0].IsPreferred" type="checkbox" value="true"><input name="ListOfSalesProducts[0].IsPreferred" type="hidden" value="false">
            <div class="is-preferred-icon"><i class="fa fa-star" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Preferred"></i><i class="fa fa-star-o" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Click to make Preferred"></i></div>
        </div>
    </td>
    <td>
        COURIER
    </td>
    <td>
        Denmark
        <div class="details_hide">
            <span class="field-validation-valid" data-valmsg-for="ListOfSalesProducts[0].IsChecked" data-valmsg-replace="true"></span>
            <span class="field-validation-valid" data-valmsg-for="ListOfSalesProducts[0].Name" data-valmsg-replace="true"></span>
        </div>
    </td>
</tr>
<tr class="">
    <td>
        <input class="isChecked" id="ListOfSalesProducts_1__IsChecked" name="ListOfSalesProducts[1].IsChecked" type="checkbox" value="true"><input name="ListOfSalesProducts[1].IsChecked" type="hidden" value="false">
    </td>
    <td>
        4166
    </td>
    <td>
        <input class="noMarkAsreq" data-val="true" data-val-number="The field ID must be a number." id="ListOfSalesProducts_1__ID" name="ListOfSalesProducts[1].ID" type="hidden" value="4166">
        <label for="ListOfSalesProducts_1__IsChecked">Asendia_EPAQ_PLS_MBD_EL45</label>
    </td>
    <td>
        <div class="is-preferred-wrap details_hide">
            <input class="isPreferred" id="ListOfSalesProducts_1__IsPreferred" name="ListOfSalesProducts[1].IsPreferred" type="checkbox" value="true"><input name="ListOfSalesProducts[1].IsPreferred" type="hidden" value="false">
            <div class="is-preferred-icon"><i class="fa fa-star" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Preferred"></i><i class="fa fa-star-o" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Click to make Preferred"></i></div>
        </div>
    </td>
    <td>
        COURIER
    </td>
    <td>
        Denmark
        <div class="details_hide">
            <span class="field-validation-valid" data-valmsg-for="ListOfSalesProducts[1].IsChecked" data-valmsg-replace="true"></span>
            <span class="field-validation-valid" data-valmsg-for="ListOfSalesProducts[1].Name" data-valmsg-replace="true"></span>
        </div>
    </td>
</tr>

Cypress test script:

it('Select all displayed items',()=>{

        cy.get('.isChecked').click({ multiple: true })
      

    })
I used the above code and 32 elements out of 109 were checked. But I need all the elements checked. I am getting the following error on the test runner while running the above code:

Timed out retrying after 4050ms: coordsHistory must be at least 2 sets of coords cypress/integration/StdSysTests/selectproduct_acc.spec.js:28:30

26 |     it('Select all products',()=>{
  27 |
> 28 |         cy.get('.isChecked').click({ multiple: true })
     |                              ^
  29 |       
  30 | 
  31 |     })

**Comment by beenushrestha** [comment] 2021-02-19 07:24
@mmsudy I was also searching solution for this particular problem nd the below ode worke for me:

cy.get('div._md-container.md-ink-ripple').click({multiple:true force: true})

Also add force: true. This worked for me hope works for you as well.

**Comment by jennifer-shehane** [comment] 2021-03-15 16:33
This is happening occasionally in our Windows Appveyor tests https://ci.appveyor.com/project/cypress-io/cypress/builds/38219970/job/2pjd3fi6s1kwe30c It's very flaky though - so it's hard to reproduce reliably. 

<img width="880" alt="Screen Shot 2021-03-15 at 12 32 35 PM" src="https://user-images.githubusercontent.com/1271364/111187645-919e8c00-858a-11eb-9fe1-061d2c1c7690.png">

**Comment by chrisbreiding** [comment] 2021-03-22 14:38
I found the key to reproducing this is slowing the browser down using Chrome's Performance tab options:

- Run the kitchensink's [`actions.spec.js` click spec](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/integration/examples/actions.spec.js#L67). You can put an `.only` on the test.
- Open Chrome DevTools, go to Performance tab
- Click the gear (⚙) icon on the top right
- Set CPU throttling to '6x slowdown'
- Enable advanced paint instrumentation (slow)
 
![Screen Shot 2021-03-22 at 10 05 03 AM](https://user-images.githubusercontent.com/1157043/112002588-6ec62780-8af6-11eb-9bb0-f7bb7b563fc5.png)

- Hit record and rerun the spec

![Screen Shot 2021-03-22 at 10 07 42 AM](https://user-images.githubusercontent.com/1157043/112002663-830a2480-8af6-11eb-84b8-ec1a1ad0b119.png)

The reason this happens is that we only increase the default timeout (4000ms) by 50ms per click when there are multiple clicks, so if the system is resource-constrained and the execution is slow, it's not enough time to perform each click, especially if there are decent number of clicks.

The error message is definitely misleading. It should say something like 'Timed out attempting to click multiple elements'. The coordsHistory bit is a red herring and just happens to be the error that gets picked up when the command times out. The timeout duration in the error message is also wrong. It says it timed out after 4050ms, but it should be 4300ms or so. We settle on the timeout too early, but it's dynamic based on the number of clicks.

We should fix the error message, but that still leaves a question to be answered.

Should we *only* fix the error message because it's the expected behavior that clicking multiple elements should happen within the required time frame? Then the user would be expected to increase the timeout for that click command, since it's going to take too long to click every element with the default timeout. 

Or is the timeout we add per click too short and we should increase it so this is less likely to happen? With a slow enough system, even increasing it to 150ms, for example, might not be enough and still require setting a custom, higher timeout for the click, but maybe there's a more reasonable amount than 50ms.

**Comment by jennifer-shehane** [comment] 2021-03-22 17:09
@chrisbreiding I didn't understand there being a specific click increased timeout of 50ms. This isn't documented anywhere. I would kind of assume with multiple clicks that each click would have default timeout of 4000ms. So clicking 3 elements would be 12000ms. I dunno, this secret timeout is weird to me.

I would like a solution that is the most common sense solution and for it to be well documented. Let's not just blindly increase it to 150ms. But think how the solution can work for most use cases without the timeout to begin with. Anything that can reduce flake with network variation will be a win.

**Comment by chrisbreiding** [comment] 2021-03-23 13:02
It was news to me too. I talked to Brian about it, and he said it's an oversight and each click should get the full 4000ms timeout. I'm working on fixing that, the error message, and I'll update the click doc too.

**Closed** 2021-03-24 19:30 UTC
Labels: internal-priority, stage: work in progress
