### ISSUE TITLE
cy.request with failOnStatusCode: false not working on headless 

### ISSUE THREAD

**Issue by ale-sanchez-g** [cypress-io/cypress#20461] opened 2022-03-03 12:29 UTC
### Current behavior

I am unable to validate a 400 status code running cypress 9.5.1 in headless mode

my test is 
```
    cy.request({
      method: "POST",
      url: "http://localhost:8080/api/registeruser",
      body: incorrectBody,
      failOnStatusCode: false,
    }).then((response) => {
      expect(response.status).to.eq(400);
    });
```

But the runner fails with no error message

![API Testing with Cypress -- Register User (failed)](https://user-images.githubusercontent.com/8701973/156564848-5662c525-60c5-43f0-8445-5838ff791d33.png)

### Desired behavior

This should work on both runner and headless

### Test code to reproduce

```
    cy.request({
      method: "POST",
      url: "http://localhost:8080/api/registeruser",
      body: incorrectBody,
      failOnStatusCode: false,
    }).then((response) => {
      expect(response.status).to.eq(400);
    });
```

### Cypress Version

9.5.1

### Other

Cypress:        9.5.1
Browser:        Chrome 98 (headless)
Node Version:   v17.5.0

**Comment by romankhomitskyi** [comment] 2022-03-07 18:42
Major bug

**Comment by gagan-sharma-sv** [comment] 2022-04-26 04:24
+1

**Comment by akshat55narang** [comment] 2022-06-01 20:38
+1 - Also observed this issue on Cypress 10.0.0

**Comment by kzahozhy** [comment] 2022-06-24 08:20
Have faced the same problem

**Comment by Ariadw** [comment] 2022-07-07 07:28
Have faced the same problem

**Comment by Ariadw** [comment] 2022-07-07 07:30
Have faced the same problem
 cy.request({
                            url:innerUrl+'/'+$e2.attr('href'),
                            failOnStatusCode: false

                        })
                        .then((response) => {
                            expect(response.status).to.eq(200)

![image](https://user-images.githubusercontent.com/86450809/177717078-8701427e-a3c3-43d1-9b9c-f38fdf7ba9dd.png)

**Comment by Valerii-88** [comment] 2022-12-17 23:51
+1 same problem

**Comment by coy123** [comment] 2023-05-25 09:43
I faced this problem but was able to solve it.

In my case, I was sending two requests in one `it` block and they weren't connected with a `then`. First was a _success_ case and second was a _failure_ case. 

Separating the two requests into two `it` blocks solved the issue for me.

**Comment by nagash77** [comment] 2023-05-26 13:17
@Valerii-88  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by nagash77** [comment] 2023-06-02 12:55
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2023-06-02 12:55 UTC
Labels: topic: cy.request, Needs Reproduction
