### ISSUE TITLE
Cypress cannot start with allowJs and target "es5"

### ISSUE THREAD

**Issue by Hypercubed** [cypress-io/cypress#8369] opened 2020-08-20 17:34 UTC
### Current behavior:

Similar to https://github.com/cypress-io/cypress/issues/7503, cannot start cypress in a projecxt were `allowJs` is true and `target` is `es5` in `tsconfig.json`

```
Cannot find module 'tslib' Require stack:

/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/reporter/lib/resolve-dist.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/reporter.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/routes.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/server.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/events.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/interactive.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/index.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/index.js
/Users/user/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/index.js
```

### Desired behavior:

Cypress should start

### Test code to reproduce

Start a new angular cli app, install cypress, change allowJs and target in root tsconfig.

```
ng new
```

follow the promts and cd to new directory

```
npm i cypress@latest
```

Add the following to the root config:

```
    "allowJs": true,
    "target": "es5",
```

then start cypress:

```
npx open cypress
```

### Versions

Cypress: 5.0.0
Angular CLI: 9.1.12
Node: 12.13.1
OS: darwin x64

**Comment by jennifer-shehane** [comment] 2020-08-21 05:37
I believe this is a duplicate of https://github.com/cypress-io/cypress/issues/8162 since this also occurs in versions previous to 5.0.0. Thanks for providing a reproducible example. I will add the steps to reproduce to that issue. 

Duplicate of #8162

**Closed by jennifer-shehane** 2020-08-21 05:37 UTC
