### ISSUE TITLE
cy.contains after a .each() is only looking inside wrapped elements

### ISSUE THREAD

**Issue by rdmorel** [cypress-io/cypress#5163] opened 2019-09-18 21:00 UTC
### Current behavior:

```js
describe('Each + Contains Bug', () => {
  it('test', () => {
      cy.visit('https://www.google.com/');
      cy.contains('About').should('be.visible');
      cy.get('input[type="submit"]').each(($input) => {
          cy.wrap($input).should('exist')
      });
      cy.contains('About').click();
  });
});
```
For some reason the `cy.contains()` line after the `.each()` is only searching within the array yielded by `cy.get('input[type="submit"]')`.

![image](https://user-images.githubusercontent.com/16787674/65185261-08051100-da1c-11e9-9cb8-a689a88f1e72.png)

The first time I call `cy.contains('About')` it finds the element fine, but then when I do it after the `.each()` block it can't find it.

### Desired behavior:

Trying to validate some attribute for each `input` element and then click the "About" button.

### Steps to reproduce: (app code and test code)

Clone [this repository](https://github.com/rdmorel/CypressEachContains/).

Run the `spec.js` integration test.

### Versions

Cypress: 3.4.1
Browser: Chrome v76.0
Operating System: Windows 10 Pro version 1809

**Comment by jennifer-shehane** [comment] 2019-09-19 14:53
As a side not, you should never need to write `.should('exist')` See [this section of our docs](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions).

Thanks for the reproducible example! Closing as duplicate of https://github.com/cypress-io/cypress/issues/4921 I will put your repro example there though. 👍

**Closed by jennifer-shehane** 2019-09-19 14:53 UTC
