### ISSUE TITLE
Cypress keeps old session logged in even after clearLocalStorage() and clearCookies() and window.SessionsStorage().clear()

### ISSUE THREAD

**Issue by rkefi** [cypress-io/cypress#14590] opened 2021-01-15 12:13 UTC
Hi Team,

### Current behavior
I have 3 spec files and in each one I have a before hook to clear localstorage, session and cookies then login to the app

```js
before(function () {
		cy.clearCookies()
		cy.clearLocalStorage()
		cy.visit('/people/users', {
			onBeforeLoad: (win) => {
				win.sessionStorage.clear()
			},
		})
	})
```
	
When I run the tests Cypress keeps the old session logged in and redirects to the users page as it finds the token somewhere in cache every time and login to the old session.

So what happens :

1 - First attempt : run all specs, all fails as when cypress launches the app, it's already signed in

2 - Clear App Data manually from Cypress then restart Cypress

3 - Second attempt : run all specs, first spec and the login in the before hook pass, but second and third specs fails on the login step as cypress kept the session of the first spec executed 

Closing and starting cypress did not help too

The only thing it helped is clearing the app data manually in Cypress (deleting the production folder under cy).

the tested App is running locally
It uses SSO for login (an outh url redirection to enter the username and password and then it sets the oauth token in the localstorage...)

### Desired behavior
Cypress should clear the app data between specs execution.

### Versions

Machine : Mac with Catalina 10.15.7
Cypress latest version
happens in all browsers, Chrome, Firefox for devs, Edge and Electron

Thanks!

**Comment by bahmutov** [comment] 2021-01-15 13:51
Can you provide a reproducible example that shows the cookies remaining?

**Comment by rkefi** [comment] 2021-01-16 00:21
Hi Gleb, Thanks for your answer
So I was able to reproduce here and created you a test account to try it, you will find the details in this repo
I sent you an invite https://github.com/rkefi/cypress-playground

**Comment by bahmutov** [comment] 2021-01-19 17:02
@rkefi please update your repo to be runnable. With instructions and description of what I am seeing. I do not want to move your files and set up the project, because it won't be what you are seeing if I have to do it myself.

I have noticed you are using `before` and `after` to clear the state. Try using `beforeEach` and `afterEach` for consistency.

**Comment by jennifer-shehane** [comment] 2021-02-27 14:17
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-27 14:17 UTC
Labels: stage: needs information
