### ISSUE TITLE
cy.get("body").type("{meta}l") isn't bringing up dialog in circleCI

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#2897] opened 2018-12-04 22:31 UTC
Hey there, for some reason the following code is failing when running 

```js
it("can open the new part window via hotkey and add a new part", function() {
    cy.get("body").type("{meta}l");
    cy.contains("New Part");
// ..more test here ..
  });
```

Strangely this test passes when being run locally using `cypress open` and when running the test locally on a headless browser via `cypress run`. 

Here is a screenshot of the test passing locally. The dialog pops up as expected:
![image](https://user-images.githubusercontent.com/2730609/49477252-338e7600-f7d1-11e8-8ef2-afa4b3f94624.png)

and here is a screenshot of the test failing in circleCI

![image](https://user-images.githubusercontent.com/2730609/49476754-b3b3dc00-f7cf-11e8-8c1f-64af41dffec2.png)

Any ideas as to why this might be happening?

Thanks!

**Comment by egucciar** [comment] 2018-12-04 23:56
I myself ran into this once, it was due to the use of `keyCode` or `key`, i forgot which specifically, in my app code. Because one of those events is not supported in electron. as you can see from ur screenshot, its failing because your modal did not ultimately appear. 

try running this locally in electron. it should be done like so

![image](https://user-images.githubusercontent.com/2848185/49480820-2afc6680-f7f6-11e8-97b5-669858be5c8d.png)

![image](https://user-images.githubusercontent.com/2848185/49480830-32237480-f7f6-11e8-97c6-d2e172f2abbc.png)


sorry i do not remember all the details of my electron / key issue. try this first to see if ur CI issue is reproducible in local electron.

**Comment by tnrich** [comment] 2018-12-05 01:21
It is not reproducible when I try running the tool in local electron. Hmmm I wonder how I can reproduce this and figure out what is going wrong..

**Comment by egucciar** [comment] 2018-12-05 01:49
Ah, ok, sorry. One other explaination I've had for failures in CI is due to environment differences. Sorry the electron tip wasn't helpful. 

Another guess I have is possibly to add some logging or triggering explicitly the key event you need. for logging you can output to let's say a floating div on the body or something. I hope you find out more information.

**Comment by tnrich** [comment] 2018-12-05 02:56
@egucciar I was thinking maybe because in CI it is in a linux environment so the {meta} key would be different?

**Comment by egucciar** [comment] 2018-12-05 03:00
I have no idea, but it sounds plausible!

**Comment by jennifer-shehane** [comment] 2019-01-28 09:09
Hey @tnrich, I think this blog may be useful for this situation. In your situation it is typing, but in the blog the situation is clicking - but the problem may be the same, that the event listeners are not ready yet. https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

**Comment by tnrich** [comment] 2019-01-28 17:33
Hmm thanks Jennifer, makes sense, I'll try that out!

**Comment by mehdikazi** [comment] 2019-03-15 03:35
Hey @jennifer-shehane do you have any other ideas to try? I am having a similar issue where my tests pass locally but not in my CI environment (drone). I'm testing my sites editor which allows special formatting through hotkeys. For example pressing meta+alt+3 should make a header-three. But in the CI environment a "3" is typed into the editor instead of the key combination being pressed. 

I tried adding a delay as suggested by the blog but that did not work. Since a "3" is typed into the editor it seems like the meta key is not working in the CI environment or maybe theres a race condition with the meta key?

**Comment by jennifer-shehane** [comment] 2019-07-11 08:45
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-11 08:45 UTC
Labels: stage: awaiting response

**Comment by msenejoa** [comment] 2019-09-30 20:09
If anyone is still running into the {meta} key problem on CircleCI, it seems that Linux does not support a metaKey. I got around this by adding a handler to check if the browser is in a linux environment

`const IS_LINUX =
  window.navigator.platform.toLowerCase().search('linux') > -1`

you will need to find a way to substitute another key for the `meta` key when you are in a Linux environment. I was working with hotKeys and used this: 

`const metaKey = IS_LINUX ? 'alt' : 'mod'`

and when assigning my hotkey:

`bold: metaKey +  '+b'`

CircleCI will apply `alt+b` instead of `command+b` (mac) and i managed to pass my tests.

**Comment by tnrich** [comment] 2023-03-10 19:08
After looping back to this after several years, I can confirm that the hack from @msenejoa fixes it for me. So it seems @jennifer-shehane that the issue is with Linux not supporting the meta key. Maybe the cypress team could investigate a way to fix that so we don't have to do these kind of odd work arounds
