### ISSUE TITLE
No sample test works!

### ISSUE THREAD

**Issue by ronaldohoch** [cypress-io/cypress#4903] opened 2019-08-01 17:44 UTC
Hello!
I really enjoyed the project, congratulations!

I installed little now on windows 10 and no test works, neither the simple nor the sample tests that already see installed.

The error: 
```
BrowserslistError: [BABEL] C:\Users\ronal\Documents\projetos\agencie-me-js\admin\node_modules\.bin\cypress\integration\admin\faz-login.spec.js: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query. (While processing: "C:\\Users\\ronal\\AppData\\Local\\Cypress\\Cache\\3.4.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\@babel\\preset-env\\lib\\index.js") while parsing file: C:\Users\ronal\Documents\projetos\agencie-me-js\admin\node_modules\.bin\cypress\integration\admin\faz-login.spec.js
```

![image](https://user-images.githubusercontent.com/2287371/62315009-ce2b7b80-b46a-11e9-87d3-2285638588c6.png)

Thank you!

**Comment by liekeninon** [comment] 2019-08-30 11:14
I have the same issue.. Is there any news?

**Comment by jennifer-shehane** [comment] 2020-01-07 08:38
Closing as duplicate of https://github.com/cypress-io/cypress/issues/2983

**Closed by jennifer-shehane** 2020-01-07 08:38 UTC
