### ISSUE TITLE
Cypress Runner goes to infinite loading on saving the code in 13.6.0

### ISSUE THREAD

**Issue by ANSHUL786** [cypress-io/cypress#28422] opened 2023-11-29 08:28 UTC
### Current behavior

When we save our spec file code in vs then auto executing runner goes in infinite loading and timer is running until we need to refresh the runner then it start executing the spec file.
![image](https://github.com/cypress-io/cypress/assets/20628265/6a8b19da-50c2-4721-b6bd-057c287fa861)

### Test code to reproduce

Open the runner and start executing any spec file
Now make any changes in that spec file and save.

Runner will goes in infinite mode most of the time

### Cypress Version

13.6.0

### Node version

18.17.1

### Operating System

Windows 11

**Comment by chrisbreiding** [comment] 2023-11-29 13:19
This looks like a duplicate of #28392.

**Closed as completed by chrisbreiding** 2023-11-29 13:19 UTC
Labels: type: duplicate
