### ISSUE TITLE
Cypress 12.3: Test retries don't work with run mode

### ISSUE THREAD

**Issue by anhtata** [cypress-io/cypress#25409] opened 2023-01-10 08:40 UTC
### Current behavior

Cypress 12.3: Test retries don't work with run mode

### Desired behavior

Cypress 12.3: Test retries can work with run mode

### Test code to reproduce

Setup a test with config: 
![image](https://user-images.githubusercontent.com/3645789/211501901-ede6a96d-f794-45e8-881d-97e15a54742c.png)

### Cypress Version

12.3.0

### Node version

16.13.0

### Operating System

Windows 10 Pro  21H2 19044.2364 (120.2212.4190.0)

**Comment by nagash77** [comment] 2023-01-10 19:14
Hi @anhtata , I'm sorry to hear you are having issues using Cypress.  Unfortunately right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2023-01-17 21:40
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-01-17 21:40 UTC
