### ISSUE TITLE
Waiting for query OFTEN throw a "No response ever occured" in one specific test

### ISSUE THREAD

**Issue by HolyNoodle** [cypress-io/cypress#6290] opened 2020-01-31 16:26 UTC
### Current behavior:
I have encountered this issue.

I have 35+ tests. Every test are built on the same pattern of waiting requests. One of all the tests does not work.

The routes defined before everything.
![image](https://user-images.githubusercontent.com/6311768/73555633-468cec80-444e-11ea-9054-c03b454bf693.png)

The test
![image](https://user-images.githubusercontent.com/6311768/73553966-260f6300-444b-11ea-8937-6f9d1b58020b.png)

Here you can see that the route fetchUsers has been answered (200 with a response).
![image](https://user-images.githubusercontent.com/6311768/73554086-5f47d300-444b-11ea-90b7-99244dc41972.png)

In this particular case, the route should already be matched since it's waited 2 times and has been queried 3 times.

If I wait two times the fetchUsers query at at first, the second wait will throw for the same reason...

The most stunning things is that if I restart the test many times, sometimes it passes...

There is no case ever where the cy.wait() would say there is no response in my test.
I insist, i got many tests doing the same kind of things and this is the only one doing this error.

### Desired behavior:

cy.wait() should not throw a "no response ever occured" when there is a response that occured

### Test code to reproduce

I can't create a reproductible error since I don't understand why it's happening but it's happening. Nevertheless, I can affirm that cy.server() is the first line to be called, the routes are being defined just after the cy.server() line. cy.visit() occurs after the route definition. This order is the same for all my tests : I define a cypress command for configuring the routes which is called in the beforeEach of the tests.

### Versions

Cypress : 3.8.2 and 3.8.3
Browser : Chrome 79.0.3945.130 (Official Build) (64-bit)
OS : Ubuntu 18.04.03 LTS

**Comment by jennifer-shehane** [comment] 2020-02-04 05:59
This looks like a Duplicate of #5999 although #3427 is a similar issue (yet maybe not as specific as your case of waiting for multiple route calls).

**Closed by jennifer-shehane** 2020-02-04 05:59 UTC
