### ISSUE TITLE
Unexpected error when configuring cypress component from the UI

### ISSUE THREAD

**Issue by matiasgarcia** [cypress-io/cypress#24119] opened 2022-10-04 17:38 UTC
### Current behavior

![Screenshot from 2022-10-04 14-36-03](https://user-images.githubusercontent.com/2261869/193888008-60479981-3739-4c8a-be63-1b421b06df93.png)

### Desired behavior

Should not raise this error

### Test code to reproduce

cypress.config.ts 

```
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:3000",
    video: false,
    chromeWebSecurity: false,
    experimentalSourceRewriting: true,
  },

  component: {
    devServer: {
      framework: "create-react-app",
      bundler: "webpack",
    },
  },
});

```

Project directory structure:
- cypress/ -> all cypress files
- src/ -> react code
- package.json

Relevant package.json
```
    "cypress:open": "cypress open --config-file cypress/cypress.config.ts",
    "cypress:run": "cypress run --config-file cypress/cypress.config.ts"
```

### Cypress Version

10.9.0

### Node version

v16.13.1

### Operating System

Linux 18

### Other

I suspect the fix might be reading the package.json from the root folder, but is there any way to tell cypress to do so? Or do I have to create a separate package.json?

**Comment by astone123** [comment] 2022-10-06 00:40
@matiasgarcia could you provide the full stack trace? It looks like it's cut off in the screenshot. Also, could you confirm where your Cypress configuration file is in your project structure? Thanks

**Comment by matiasgarcia** [comment] 2022-10-07 21:12
Hi @astone123 its in the cypress/ folder.

**Comment by warrensplayer** [comment] 2022-10-11 21:19
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-10-21 16:35
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-10-21 16:35 UTC
