### ISSUE TITLE
Scroll behavior "smooth" not working

### ISSUE THREAD

**Issue by markmssd** [cypress-io/cypress#4640] opened 2019-07-03 05:11 UTC
### Current behavior:

In our web app, we have a button that when clicked, executes:
```js
document.getElementById('anchor_top').scrollIntoView({ behavior: 'smooth', block: 'start' })
```

It works properly when clicking the button manually. Only when running in Cypress (Electron or Chrome browser), it doesn't scroll to top. 

To make it reproducible, try this:
```js
cy.window()
  .then(window => window.scrollTo({ top: 0, left: 0, behavior: 'smooth' }))
  .wait(1000)
  .then(() => getWindowTop().should('eq', 0))

```

**Note that it works perfectly if we remove the option `behavior: 'smooth'`**

### Desired behavior:

It should smoothly scroll to top.
I've seen related issues #805 and #3200 , but they were not quite the same.

### Steps to reproduce: (app code and test code)

To make it reproducible, try this:

```js
const getWindowTop = () => 
  cy.document()
    .then(doc => 
      cy.wrap(
        { 
          scrollTop: (doc.scrollingElement || doc.documentElement)
        .scrollTop 
        }
      ).its('scrollTop'))

cy.window()
  .then(window => window.scrollTo({ top: 0, left: 0, behavior: 'smooth' }))
  .wait(1000)
  .then(() => getWindowTop().should('eq', 0))
```

Remove `behavior: 'smooth'` from above and it will pass.

### Versions

Cypress v3.3.2
MacOS v10.14.3
Chrome v75.03

**Comment by jennifer-shehane** [comment] 2019-07-03 07:03
This portion of the code provided seems to be incorrect

```js
cy.wrap({ scrollTop: (doc.scrollingElement || doc.documentElement).scrollTop }).its('scrollTop'))
```

Are you missing a comma or parenthesis here?

**Comment by markmssd** [comment] 2019-07-03 12:31
> This portion of the code provided seems to be incorrect
> 
> ```js
> cy.wrap({ scrollTop: (doc.scrollingElement || doc.documentElement).scrollTop }).its('scrollTop'))
> ```
> 
> Are you missing a comma or parenthesis here?

Hey @jennifer-shehane , indeed in that snippet there is an extra parenthesis, good catch! There it is fixed:

`cy.wrap({ scrollTop: (doc.scrollingElement || doc.documentElement).scrollTop }).its('scrollTop')`

**Comment by jennifer-shehane** [comment] 2019-07-16 07:50
Can you provide the HTML to run this test against? I'm not able to reproduce it.

**Comment by AnnaAKuznetsova** [comment] 2019-11-06 07:33
Hi guys, have you found any solution? We are experiencing the same problem with testing 'smooth' scrolling behavior.

**Comment by VladLegkowski** [comment] 2019-11-08 11:07
Looking for a solution as well.

**Comment by jennifer-shehane** [comment] 2019-12-05 10:46
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

This is likely related to this issue involving scroll-behavior 'smooth' though. https://github.com/cypress-io/cypress/issues/3200

**Closed by jennifer-shehane** 2019-12-05 10:46 UTC
Labels: stage: needs information
