### ISSUE TITLE
Cypress CT & Next: getting webpack errors during component mounting after using Cypress' setup wizard

### ISSUE THREAD

**Issue by liambutler** [cypress-io/cypress#23516] opened 2022-08-23 14:48 UTC
### Current behavior

I’m currently working on getting Cypress Component Testing up and running in my team’s repo. It’s a monorepo managed by NX. Components are React.

I had hoped to save myself from some config headaches by running Cypress in global mode at the root of the repo, and then using the configuration wizard to set up component testing in the desired app folders.

I can see that this wizard is currently in alpha, but I gave it a go (using 10.6.0):

![Screenshot 2022-08-22 at 11 35 17](https://user-images.githubusercontent.com/24389501/186185766-87e132a5-bbc5-446c-985b-1e28fdfc8275.png)

The wizard didn't flag any issues:

<img width="817" alt="Screenshot 2022-08-23 at 16 44 45" src="https://user-images.githubusercontent.com/24389501/186189072-2607513d-05e9-4faf-a392-b914713cdee0.png">
<img width="1004" alt="Screenshot 2022-08-23 at 16 44 55" src="https://user-images.githubusercontent.com/24389501/186189082-82bd0335-8c6a-4662-a523-797c9bfb56a2.png">

Unfortunately I am getting webpack errors when I attempt to mount a component:

![Screenshot 2022-08-24 at 13 29 09](https://user-images.githubusercontent.com/24389501/186407553-ca9ff5d8-24ac-4c33-a288-b59dea53dbf4.png)

And the browser window simply says `Cannot GET /__cypress/src/index.html`

![Screenshot 2022-08-24 at 13 31 59](https://user-images.githubusercontent.com/24389501/186407998-6dcb57ca-e527-4f16-9800-5eb0d45c8d5a.png)

Side note: the wizard didn’t add a `component-test` action to my `project.json`, which the devs tell me is crucial for NX setups.

### Desired behavior

As well as detecting that my repo is running on Next, it is able to detect additional configurations and include them in `cypress.config.ts` or wherever they need to go

### Test code to reproduce

I don't have a public repo to highlight this issue. However I'm talking this through with Jonathan C at Cypress, and am happy to join a call to give further context

### Cypress Version

10.6.0

### Node version

16.15.0

### Operating System

macOS 12.5.1

**Comment by liambutler** [comment] 2022-08-24 14:03
Additional context, requested by @lmiller1990.

NextJS version: 14.15.1
Webpack config is being handled in a `next.config.js` file. Here is the webpack portion:

```js
  webpack: (config, { webpack, isServer }) => {
    config.module.rules.push({
      test: /\.(graphql|gql)$/,
      exclude: /node_modules/,
      loader: 'graphql-tag/loader',
    });
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.CONFIG_BUILD_ID': JSON.stringify(getVersion().name),
        'process.env.ENVIRONMENT': JSON.stringify(getVersion().environment),
      })
    );
    if (!isServer) {
      config.plugins.push(
        new webpack.IgnorePlugin({ resourceRegExp: /authentication/ }),
        new webpack.IgnorePlugin({ resourceRegExp: /server/ })
      );
    }
    return config;
  },

...

module.exports = () => {
  const plugins = [
    withNx,
    withBundleAnalyzer({
      enabled: process.env.ANALYZE === 'true',
    }),
  ];
  const config = plugins.reduce((acc, next) => next(acc), {
    ...nextConfig,
  });
  return config;
};
```
(there's more than this, but I've included what I believe to be the relevant parts)

And then there's a fairly generic `cypress.config.ts`

```js
import { defineConfig } from "cypress";

export default defineConfig({
  component: {
    devServer: {
      framework: "next",
      bundler: "webpack",
    },
  },
});
```

**Comment by ZachJW34** [comment] 2022-08-24 14:35
I believe we need to add support for respecting the webpack modifications made within the `next.config.js` file.

We do offer a `webpackConfig` property in `cypress.config.ts`, can you try utilizing the option to push the additional rules in? Something like:

```js
const webpackConfig = {
  module: {
    rules: [
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: "graphql-tag/loader",
      },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.CONFIG_BUILD_ID': JSON.stringify(getVersion().name),
      'process.env.ENVIRONMENT': JSON.stringify(getVersion().environment),
    }),
    new webpack.IgnorePlugin({ resourceRegExp: /authentication/ }),
    new webpack.IgnorePlugin({ resourceRegExp: /server/ })
  ]
}

export default defineConfig({
  component: {
    devServer: {
      framework: "next",
      bundler: "webpack",
	  webpackConfig,
    },
  },
});
```

As for the project setup, scaffolding the proper setup for Nx projects is not something we will be implementing (at least, not anytime soon). I'd expect an Nx schematic to handle the setup for Nx users.

Lastly, if you could share a minimal reproduction that would help alot!

**Comment by liambutler** [comment] 2022-08-29 14:57
Haven't forgotten about this. Working on putting a minimal reproduction together

**Comment by liambutler** [comment] 2022-08-30 14:42
Minimal reproduction below. Currently getting this error when trying to mount the component:

<img width="1099" alt="Screenshot 2022-08-30 at 16 41 05" src="https://user-images.githubusercontent.com/24389501/187466886-9e689556-c8d7-411a-ae04-9d99a1e48d2c.png">

From what I've been seeing, I believe the loader doesn't like type exports, nor SVGs that are loaded by svgr

https://github.com/liambutler/cypress-ct-issue-repro-cy-wizard

**Comment by rockindahizzy** [comment] 2022-09-01 19:54
Hey @liambutler I noticed that in your reproduction you are using `"executor": "@nrwl/web:webpack",` & `"webpackConfig": "@nrwl/react/plugins/webpack"` for the builder. Was this a mistake? Curious if you are actually running a React or Next application.

**Comment by rockindahizzy** [comment] 2022-09-02 14:13
Hey @liambutler, unfortunately this issue will require some work from the NX team in order to support next.js and cypress. We had a discussion with them and it seems like something they are planning to do.

In the interim, I made some tweaks to your next.config.js and cypress test [here](https://github.com/rockindahizzy/cypress-ct-issue-repro-cy-wizard/commit/65a9ea44dc2086962a17358503107e31196b25b1). It seems to have resolved the issues in your reproduction; curious if it will have the same result in your actual application.

**Comment by liambutler** [comment] 2022-09-02 14:24
Hey @rockindahizzy , thank you for looking into this. I've had to fly back to the UK to attend a family funeral, and my laptop is in Denmark. I'll be able to take a look at the actual repo on Tuesday, and I'll get back to you

**Comment by rockindahizzy** [comment] 2022-09-02 14:26
Sorry to hear that, @liambutler. All the best to you and your family!

**Comment by liambutler** [comment] 2022-09-06 12:53
@rockindahizzy, I've been able to successfully mount a component after the changes you made. Thanks!

In answer to the some of the points that have been raised above:

_I noticed that in your reproduction you are using "executor": "@nrwl/web:webpack", & "webpackConfig": "@nrwl/react/plugins/webpack" for the builder. Was this a mistake? Curious if you are actually running a React or Next application._
It's definitely a Next project. I've checked the `project.json` in the actual app. The build executor is set as  `"executor": "@nrwl/next:build",`. This must have been something I missed while trying to build the minimal repro. Sorry for the confusion; I'm not too familiar with Next yet.

_As for the project setup, scaffolding the proper setup for Nx projects is not something we will be implementing (at least, not anytime soon). I'd expect an Nx schematic to handle the setup for Nx users. @ZachJW34 _

There's currently a lot of overlap between the NX-provided way of setting up Cypress Component Testing (`cypress-component-configuration`) and the wizard provided by Cypress. Both produce many of the same configuration files within the Cypress folder. For those getting set up, it's going to be confusing (it was for me!). Will one of these routes be deprecated?

**Comment by lmiller1990** [comment] 2022-09-07 03:34
@liambutler we have to ship our wizard since many people are not using NX - NX also have a "we provide configuration for all the things" like approach.

NX provide integrations for lots of tools (which is quite cool) but in this case, there are two sources of truth - both Cypress and NX want to control the setup. Ideally, in my opinion, users would use Cypress to configure Cypress - I think this makes the most sense, at least, for frameworks we support out of the box (React, Next.js, etc). 

One alternative might be for Cypress to expose some CLI hooks for NX to integrate with, as not to duplicate work - I'm not sure on the logistics or priority for this, though.

**Comment by ZachJW34** [comment] 2022-09-15 15:20
I'm going to close this issue out. Similar to https://github.com/nrwl/nx/pull/11790, there will need to be some work on Nx's side to add first class support for Next.js + Nx + Cypress CT. Creating an issue in Nx would be good to push this along. We had to make some change on our side to accommodate for Angular + Nx + Cypress CT, so I imagine another issue might be opened down the line if/when the Nx team decides to add support.

**Closed by ZachJW34** 2022-09-15 15:20 UTC
Labels: type: bug, existing workaround, CT, stage: blocked

**Comment by liambutler** [comment] 2022-09-16 08:48
Thanks Zach

There's already an issue raised with NX here: https://github.com/nrwl/nx/issues/11785. It's been closed, but they've committed to working on it

@lmiller1990 sorry I missed your question. The configuration provided to me by @rockindahizzy was enough to get me up and running. Thanks for the help, everyone!
