### ISSUE TITLE
Aliases created in before hook are not shared between all tests

### ISSUE THREAD

**Issue by malantb** [cypress-io/cypress#6801] opened 2020-03-21 19:36 UTC
### Current behavior:

Aliases created in before hook are available only in first test.

### Desired behavior:

Aliases created in before hook should be available in all tests or doc (https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Aliases) should be updated to clarify this.

### Test code to reproduce

```
cd ~ && 
mkdir cypress-issue-verification &&
cd cypress-issue-verification &&
npm install --save-dev cypress &&
./node_modules/cypress/bin/cypress open
```
Create file issue_ver.spec.js in ~/cypress-issue-verification/cypress/integration/examples/ and place there code below:
```javascript
beforeEach(function () {
    cy.fixture('example.json').as('be_example')
})

before(function () {
    cy.fixture('example.json').as('b_example')
})

it('first test', function () {
    cy.wrap(this.be_example.name)
        .should('eq', this.be_example.name, 'Using fixtures to represent data')

    cy.wrap(this.b_example.name)
        .should('eq', this.b_example.name, 'Using fixtures to represent data')
})

it('second test', function () {
    cy.wrap(this.be_example.name)
        .should('eq', this.be_example.name, 'Using fixtures to represent data')

    // Comment on lines below to make this test green.
    cy.wrap(this.b_example.name)
        .should('eq', this.b_example.name, 'Using fixtures to represent data')
})
```

### Versions

Cypress 4.2.0
Chrome 80

**Comment by jennifer-shehane** [comment] 2020-03-23 10:39
Duplicate of #665

**Closed by jennifer-shehane** 2020-03-23 10:39 UTC
