### ISSUE TITLE
When I add tags to scenario in feature file and execute from test runner getting parse error.

### ISSUE THREAD

**Issue by balajikrishnannewsuk** [cypress-io/cypress#7258] opened 2020-05-07 11:04 UTC
When I add tags to scenario in feature file and execute from test runner getting parse error.
<img width="880" alt="Screen Shot 2020-05-05 at 11 17 23 AM" src="https://user-images.githubusercontent.com/62639915/81287582-a49a2300-9080-11ea-993d-ae7eadf00746.png">

**Comment by zac11** [comment] 2020-05-07 11:36
What are the contents of your `/plugins/index.js` file?

**Comment by balajikrishnannewsuk** [comment] 2020-05-07 12:14
const cucumber = require("cypress-cucumber-preprocessor").default;
const fs = require("fs-extra");
const path = require("path");

module.exports = (on, config) => {
	require("cypress-plugin-retries/lib/plugin")(on);
};

module.exports = (on, config) => {
	on("file:preprocessor", cucumber());
	const enviroment = config.env.configFile;
	const configForEnviroment = getConfigurationByFile(enviroment);
	return configForEnviroment ? configForEnviroment : config;
};

function getConfigurationByFile(file) {
	const pathToConfigFile = `config/${file}.json`;
	return fs.readJson(path.join(__dirname, "../../", pathToConfigFile));
}

**Comment by zac11** [comment] 2020-05-07 22:51
Also please add the feature file. This is not a Cypress exception. Looks like originating from Cucumber. Please check if

**Comment by jennifer-shehane** [comment] 2020-05-12 04:39
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

**Closed by jennifer-shehane** 2020-05-12 04:39 UTC
