### ISSUE TITLE
Exceptions in global 'after' are not shown correctly in UI

### ISSUE THREAD

**Issue by danielschwartz85** [cypress-io/cypress#3904] opened 2019-04-07 08:30 UTC
Hi 
When throwing exceptions in a global scoped 'after'  the error is not shown correctly in the UI.
Couldn't find any issue describing this so sorry if it's a duplicate.

(could be related to https://github.com/cypress-io/cypress/issues/2296 or
/ and https://github.com/cypress-io/cypress/issues/3348)

![then](https://user-images.githubusercontent.com/4113198/55680851-00e3be00-5928-11e9-9633-5af1ace7f390.png)
![timeout](https://user-images.githubusercontent.com/4113198/55680850-00e3be00-5928-11e9-8a20-30e6b2d1d9de.png)

### Desired behavior:

Show the correct error messages (For us Applitools - as a plugin is to show users their failed visual tests info)

### Steps to reproduce: (app code and test code)

1. Just throwing in after() call is shown in UI as ```THEN  function(){}```
2. Throwing in a Promise in a cy.then() in an after() call is shown in UI as ```THEN {timeout: 0} function(){}```

* see this repo: https://github.com/danielschwartz85/cypress-ui-invalid-exceptions

### Versions

Cypress 3.1.5
Ubuntu 18.04.1

Tnx.

**Comment by jennifer-shehane** [comment] 2019-04-10 06:12
Thank you for providing a reproducible example! We're currently working on revamping many of the error messages, so this may be something we can work into that issue. https://github.com/cypress-io/cypress/issues/3762

**Comment by Bkucera** [comment] 2020-05-04 18:21
duplicate of #2296

**Closed by Bkucera** 2020-05-04 18:21 UTC
Labels: pkg/driver, stage: needs investigating, type: bug, type: error message
