### ISSUE TITLE
Auto Scrolling no longer works after some time

### ISSUE THREAD

**Issue by edvitor13** [cypress-io/cypress#22199] opened 2022-06-08 18:00 UTC
### Current behavior

In run mode and with the browser hidden.

After upgrading to Cypress >= 10, in large tests, Auto Scrolling stops working at some point.

Before:

https://user-images.githubusercontent.com/11736724/172683673-a7ed4f52-701e-424e-a7ff-64c06851aec6.mp4

After:

https://user-images.githubusercontent.com/11736724/172682939-a244a67f-5d7a-4da2-84df-f946641f7438.mp4

### Test code to reproduce

npx cypress run

### Cypress Version

10.0.3

**Comment by AtofStryker** [comment] 2022-06-10 17:16
Hey @edvitor13. Thank you for filing an issue! I was also able to reproduce the issue by running one of the `@package/driver` tests within the `develop` (SHA 72e6b882bd) branch, specifically [click.cy.js](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/actions/click.cy.js). I am going to document the steps I took below for whoever ultimately works on this bug.

#### Steps to Reproduce

* after cloning the `cypress` repository, running `yarn` to install monorepo dependencies
* in root directory of repository, run `yarn workspace @packages/driver cypress:open`
* Select E2E Testing
* Start E2E Testing in Chrome (my version installed is v102)
* search and select `click.cy.js`
* watch test run. eventually auto scrolling stops
* window dimensions did not seem to matter, but for reproduction:
    * `Cypress.$(window).width()` yielded `1920` 
    * `Cypress.$(window).height()` yielded `857`


![auto-scroll-reprod](https://user-images.githubusercontent.com/3980464/173117877-927da4db-a141-4ae2-ab8c-f39ade6456f5.gif)

It almost looks like a snapshot is being pinned before the test ends. Not sure if that is related 🤔

**Comment by marktnoonan** [comment] 2022-06-10 21:17
Possibly related: https://github.com/cypress-io/cypress/issues/16098

Hopefully helpful: I was thinking we might want to not do this scroll listener in run mode? I commented in the other issue but I don't recall if I actually tested that

```
    scroller.setContainer(this.refs.container as Element, action('user:scroll:detected', () => {
      if (appState && appState.isRunning) {
        appState.temporarilySetAutoScrolling(false)
      }
    }))
 ```

**Comment by retroace** [comment] 2022-07-15 13:08
Any update on this? I am also encountering the same error. I am running in run mode. 

What's the usefulness of enabling the scroll listeners in cli mode? Can user even scroll in headless/cli mode?

**Comment by marktnoonan** [comment] 2022-08-04 13:55
@retroace in the comments of [this draft PR](https://github.com/cypress-io/cypress/pull/23053) you can find instructions in the comments from `cypress-bot` on how to install a pre-release version of Cypress that includes the fix I suggested [here](https://github.com/cypress-io/cypress/issues/22199#issuecomment-1152744654).

I actually completely forgot that @AtofStryker had a reproduction in this issue. We probably should have marked these as duplicates of each other.

In any case, since I have trouble reproducing this problem on my computer, feel free to install the appropriate pre-release binary of Cypress and let me know if it works for you. The pre-release turns off the ability for the user to disable autoscroll in `run` mode, so you will need to either watch back a video, or use `cypress run --headed` to see your tests running in a way that would be fixed by this draft.

**Comment by laerteneto** [comment] 2022-08-11 09:40
Sometimes it happens to me because Cypress turns off the Auto-scrolling option automatically. So, I need to turn it on again, but once again at some point it is turned back to off.

Cypress: 10.4.1
OS: Windows 10
Browser: Chrome 104

![image](https://user-images.githubusercontent.com/9399511/184105784-a498c1b8-558d-43b5-b5dc-7b558997decd.png)

**Closed** 2022-09-13 13:17 UTC
Labels: type: regression, reproducible, E2E-core, stage: fire watch, routed-to-e2e
