### ISSUE TITLE
Scrollbar stuck in test steps area in Cy10

### ISSUE THREAD

**Issue by Darksymphony75** [cypress-io/cypress#22772] opened 2022-07-13 18:41 UTC
### Current behavior

In Cypress 10 when I run any longer tests, the scrollbar with the steps on the left column is very often stuck, so it is not scrolling automatically to the bottom as the steps are executed, then I can't see the current steps, I need to manually scroll down during running test or after it is finished.

This happens very often, almost everytime. It starts to work normally, it scrolls automatically from the beginning, but then suddenly after a while it doesn't scroll automatically. 

It happens also if you expand the Specs column and close it during running test.

![obrázok](https://user-images.githubusercontent.com/73718902/178806795-567f6720-108e-4b75-a82a-c2a8dd5e02ba.png)

### Desired behavior

The area with test steps in Cypress 10 test runner should always scroll to bottom automatically when executing the tests.

### Test code to reproduce

no code needed, it happens for any test

### Cypress Version

10.3.0

**Comment by astone123** [comment] 2022-07-14 14:17
@Darksymphony75 Thanks for filing an issue. Which browser are you testing in?

**Comment by Darksymphony75** [comment] 2022-07-14 14:33
tested in Electron

**Comment by astone123** [comment] 2022-07-14 14:57
Huh - I'm not able to reproduce this in Electron. My test has about 1200 lines of output and I expanded and collapsed the spec list multiple times while the test was running but it continued to auto-scroll correctly.

Which OS are you running Cypress on?

**Comment by astone123** [comment] 2022-07-14 20:44
I tried reproing this on Windows as well but I was unsuccessful. It looks like we do have an open issue for this so I'm going to reference this issue there and close this out as a duplicate.

**Closed by astone123** 2022-07-14 20:44 UTC
Labels: stage: investigating
