### ISSUE TITLE
Cannot log into Cypress Cloud in the app (free user) and cannot delete user account to re-register due to INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by javiktoria** [cypress-io/cypress#25756] opened 2023-02-09 13:43 UTC
### Current behavior

1) I was using Cypress during the course of a udemy course and I could not log in to the app. I clicked on the log in button, it redirected me to the browser and the website where I logged in without an issue, however, the app just kept saying logging in indefinitely. I have tried to get community support on this but we could not solve the issue so I planned on deleting my Cypress account and re-registering, hopefully solving the problem.

2) When I went to the website to delete my account, I got the following message:
You may not delete your Cypress account for the following reasons:
INTERNAL_SERVER_ERROR

### Desired behavior

1) After logging in on the website, the app is logged in, as well.

2) When clicking on "Delete account", account can be deleted.

### Test code to reproduce

N/A

### Cypress Version

12.5.0

### Node version

18.12.1

### Operating System

Windows 10.0.19045

**Comment by warrensplayer** [comment] 2023-02-10 16:22
@javiktoria Can you share a screen recording of you logging into the app or just some screenshots of the error messages you are seeing so we can look into this further?

**Comment by marktnoonan** [comment] 2023-02-15 17:20
Linking a related Discord thread: https://discordapp.com/channels/755913899261296641/1069631475445674044/1069631475445674044

**Comment by marktnoonan** [comment] 2023-02-22 23:54
Confirmed that this is an issue when Brave is used to Log In to the Cloud because it blocks ads and trackers by default. This intuitively makes some sense, Cypress need to connect to localhost to communicate to the app that you have logged in. Turns out that Brave disables all such communication through its adblocking behavior. This setting must be disabled for the log in page to work properly:

![Image](https://user-images.githubusercontent.com/8340719/220790398-1cfca5cc-5079-469d-aa7a-7a9e6508b098.png)

Anybody affected by this, please try turning off adblocking on the login page for the cloud.

In terms of a solution, we have a few ways forward - from UX improvements like info about this side effect of adblockers in the app to changing the way log in is detected to some other method.

**Comment by marktnoonan** [comment] 2023-03-01 20:42
Looks like this is a known issue in Brave and would be fixed by https://github.com/brave/brave-browser/issues/27346

**Comment by marktnoonan** [comment] 2023-06-28 23:19
Confirmed that Brave works great for Cypress in newer versions so I'm going to go ahead and close this issue. Thank you @javiktoria for the report 🙌

**Closed as completed by marktnoonan** 2023-06-28 23:19 UTC
Labels: type: bug, stage: awaiting external fix, Cypress Cloud
