### ISSUE TITLE
Recorded video only shows a static image

### ISSUE THREAD

**Issue by randing89** [cypress-io/cypress#9267] opened 2020-11-20 22:29 UTC
I was on 3.8.0 the video recording suddenly stopped working. After I upgraded to 5.6.0 it is still not working.
The recorded video only shows a static image or sometimes completely blank.

![image](https://user-images.githubusercontent.com/640557/99856117-21807c00-2b3d-11eb-8ddb-190c068ee7b0.png)

Examples:
[Archive.zip](https://github.com/cypress-io/cypress/files/5576385/Archive.zip)
 
Logs:
[cypress-log.txt](https://github.com/cypress-io/cypress/files/5576389/cypress-log.txt)

**Comment by csvan** [comment] 2020-11-22 13:10
I am seeing the same thing, not sure when it started but We had no issues in Cypress 4.x or 5.1-5.4

**Comment by you1anna** [comment] 2020-11-23 14:52
Also getting this issue on Cypress 5.6

**Comment by jennifer-shehane** [comment] 2020-11-25 03:36
Duplicate of https://github.com/cypress-io/cypress/issues/9265

**Closed by jennifer-shehane** 2020-11-25 03:36 UTC
