### ISSUE TITLE
cy.intercept can leak from one test to another

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9406] opened 2020-12-02 02:39 UTC
Cypress v6.0.1 branch `issue-8999`

While testing the solution to https://github.com/cypress-io/cypress/issues/8934 I stumbled on a weird situation that seems to occur pretty often.

The page only has an image resource

```html
<img src="images/tiger.jpg">
```

There are two tests, but they both create an intercept with the same alias `image`

https://github.com/cypress-io/cypress-example-recipes/blob/6.1.0/examples/stubbing-spying__intercept/cypress/integration/image-spec.js#L4-L18

```js
it.only('spies on loading a static image', () => {
  cy.intercept('/images').as('image')
  cy.visit('/pics.html')
  cy.wait('@image')

  // reload the page, it should send another request
  cy.reload()
  cy.wait('@image')
})

it.only('spies on loading a static image (2nd test)', () => {
  cy.intercept('/images').as('image')
  cy.visit('/pics.html')
  cy.wait('@image')
})
```

I noticed that sometimes the second test shows 2 intercepts for `image`, see the gif below

![leaking-intercept](https://user-images.githubusercontent.com/2212006/100821014-7e254600-341d-11eb-89c7-8ba93557daaa.gif)

If I rename the alias so that every test has its own, then I do not see anything suspicious. Might be that an alias can leak from test to test if the names match?

**Comment by jennifer-shehane** [comment] 2021-01-20 04:54
This issue seems to be resolved in our latest 6.3.0 Cypress version. I reran many times and was not able to reproduce the issue. 

Closing as resolved.

**Closed by jennifer-shehane** 2021-01-20 04:54 UTC
Labels: internal-priority, pkg/net-stubbing, stage: needs investigating, type: bug
