### ISSUE TITLE
Setting component properties in .then() callback persists through tests (Angular)

### ISSUE THREAD

**Issue by dvkuenssberg** [cypress-io/cypress#25760] opened 2023-02-09 15:47 UTC
### Current behavior

Setting a component property in the `.then()` callback of the `cy.mount` command seems to persist through some of the later tests in the same `describe` block.

### Desired behavior

Setting attributes of a component this way in a single test should not affect any of the other tests. Of course, it is possible to define a separate configuration to achieve changing the value of the variable, but it is an unexpected behavior nonetheless.

### Test code to reproduce

This is a slightly altered version of my code which causes this problem. The `structure` field is set via `@Input()` in `MyComponent`.

```typescript
let myConfig = {
  componentProperties: {
     structure: {
        isCorrect: true,
     }
  }
}
it('test 1', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is still true
});
it('test 2', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is still true
});
it('test 3', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is still true
});
it('test 4', () => {
   cy.mount(MyComponent, myConfig).then(wrapper => {
      wrapper.component.structure.isCorrect = false;
   });
   // some tests, isCorrect is false as expected
});
it('test 5', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is still true
});
it('test 6', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is still true
});
it('test 7', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is now false!
});
it('test 8', () => {
   cy.mount(MyComponent, myConfig);
   // some tests, isCorrect is now false!
});
```
After changing `isCorrect` in the 4th test to `false`, somehow tests 7 and 8 also show `isCorrect` as `false`, despite being mounted  with a configuration where `isCorrect` is true.

### Cypress Version

12.4.0

### Node version

16.15.1

### Operating System

Windows 10.0.19044 Build 19044

**Comment by mike-plummer** [comment] 2023-02-09 18:05
Hi @dvkuenssberg , thanks for opening an issue! We pass the provided `componentProperties` reference through when mounting, so you are correct in that mutating the object in one test and reusing the same object reference in a second will leak state (by reusing the same object). I would recommend a minor refactor to ensure you aren't sharing state between tests - using a `beforeEach` like this will build a fresh `myConfig` object for each test so that each test is fully isolated:

```
let myConfig;

beforeEach(() => {
  myConfig = {
    componentProperties: {
      structure: {
        isCorrect: true,
      }
    }
  }
});

it('test 1', () => {
   // customize `myConfig` ...here
   cy.mount(MyComponent, myConfig)
      .then(wrapper => {
        // or here...
      });
  // either way, it won't leak into other tests
});

it('test 2', () => {
   cy.mount(MyComponent, myConfig);
});
```

**Comment by dvkuenssberg** [comment] 2023-02-13 07:43
Hi @mike-plummer, thanks for your reply, I will change the properties like this then!

**Comment by mike-plummer** [comment] 2023-02-13 14:16
@dvkuenssberg Hope this fixes your issue; if it does I would appreciate it if you could close this issue out. Thanks!

**Comment by dvkuenssberg** [comment] 2023-06-23 11:24
Hi @mike-plummer,

this problem reoccured today, even with the `beforeEach` config you proposed. This is the simplified setup:

Component:
```typescript
interface Item {
    name: string;
    isExpanded: boolean;
}
@Component({
    selector: 'app-my-component',
    templateUrl: './my-component.html'
})
export class MyComponent {
    items: Item[] = []:
    @Output() itemClicked: EventEmitter<Item> = new EventEmitter<Item>();
}
```
HTML: 
```html
<div *ngFor="let item of items">
	<mat-icon id="toggle-item-{{ i }}" (click)="item.isExpanded = !item.isExpanded">build</mat-icon>
	<button id="button-{{ i }}" (click)="openMenu()" *ngIf="item.isExpanded">Click me</button>
</div>
```
And this the test:
```typescript
  let config: MountConfig<MyComponent> | undefined;

  beforeEach(() => {
    config = {
      componentProperties: {
      	items: [{ name: 'Item1', isExpanded: true }, { name: 'Item2', isExpanded: true }]
      },
    };
  });

  it.only('test 1: should toggle button for row', () => {
    cy.mount(MyComponent, config);
    cy.get('#toggle-item-0').click();
    cy.get('#button-0').should('not.exist');
  });

  it.only('test 2: should click button for row', () => {
    cy.mount(MyComponent, config).then(wrapper => {
      cy.spy(wrapper.component.itemClicked, 'emit').as('clickedSpy');
      cy.log(wrapper.component.items[0].isExpanded); // => false!
    });
    cy.get('#button-0').click(); // => cannot find button!
    cy.get('@clickedSpy').should('have.been.calledOnceWith', { name: 'Item1', isExpanded: true });
  });
```

After I toggle the item in test 1 and thus hide `button-0`, the `isExpanded` attribute of `items[0]` is still unchanged in test 2, failing the test. I'm using Cypress v12.15.0. Do you have an idea why this could happen?

**Comment by mike-plummer** [comment] 2023-06-23 14:51
@dvkuenssberg I had to adjust your example to get it to run - it was referencing Material UI stuff and using spies that didn't seem relevant. I stripped it down to a pure HTML example and I think I maintained the spirit of the issue you're describing.

This simpler example works as I would expect in Cypress 12.15.0. First test hides two elements by updating state values. Second test mounts fresh and everything looks the way it should. Is it possible you have external state being maintained? Maybe my rework changed the behavior you intended; is there a reproduction I can clone and see the issue?

`my-component.component.ts`
```ts
import { Component, Output, EventEmitter } from "@angular/core";

interface Item {
    name: string;
    isExpanded: boolean;
}
@Component({
    selector: 'app-my-component',
    templateUrl: './my-component.html'
})
export class MyComponent {
    items: Item[] = [];
    @Output() itemClicked: EventEmitter<Item> = new EventEmitter<Item>();
}
```

`my-component.html`
```html
<div *ngFor="let item of items; let i = index">
	<button id="toggle-item-{{ i }}" (click)="item.isExpanded = !item.isExpanded">Toggle</button>
	<div id="element-{{ i }}" *ngIf="item.isExpanded">Expanded!</div>
</div>
```

`my-component.cy.ts`
```ts
import { MountConfig } from "cypress/angular";
import { MyComponent } from "./my-component.component";

let config: MountConfig<MyComponent> | undefined;

beforeEach(() => {
  config = {
    componentProperties: {
        items: [{ name: 'Item1', isExpanded: true }, { name: 'Item2', isExpanded: true }]
    },
  };
});

it('test 1: should toggle button for row', () => {
  cy.mount(MyComponent, config);
  cy.get('#element-0').should('be.visible');
  cy.get('#toggle-item-0').click();
  cy.get('#element-0').should('not.exist');

  cy.get('#element-1').should('be.visible');
  cy.get('#toggle-item-1').click();
  cy.get('#element-1').should('not.exist');
  
  // Both items are now hidden, hopefully this state doesn't leak into the next test!!
});

it('test 2: items should be visible again despite being hidden in previous test', () => {
  cy.mount(MyComponent, config).then(wrapper => {
	// Logging `true` for me
    cy.log(`Element visible? ${wrapper.component.items[0].isExpanded}`);
  });
  // Yay, everything is visible like it should be!
  cy.get('#toggle-item-0').should('be.visible');
  cy.get('#toggle-item-1').should('be.visible');
});
```

**Comment by dvkuenssberg** [comment] 2023-06-26 09:57
Hi @mike-plummer ,

thank you for the quick reply!

Firstly, your second test should check the elements to be visible since the toggle buttons are always visible, but the `cy.log` indicates that it behaves as it should:

```typescript
it('test 2: items should be visible again despite being hidden in previous test', () => {
  cy.mount(MyComponent, config).then(wrapper => {
	// Logging `true` for me
    cy.log(`Element visible? ${wrapper.component.items[0].isExpanded}`);
  });
  // Yay, everything is visible like it should be!
  cy.get('#element-0').should('be.visible');
  cy.get('#element-1').should('be.visible');
});
```
More importantly: your example worked for me too, but after making some changes, I ran into the same problem.

When declaring the items as variables first instead of directly declaring them in the `items` array, the second test fails and the state carries over, both elements are not visible:

```typescript
  let item1 = {
    name: 'name1',
    isExpanded: true,
  };

  let item2 = {
    name: 'name2',
    isExpanded: true,
  };

  beforeEach(() => {
    config = {
      componentProperties: {
        items: [item1, item2],
      },
    };
  });

  it('test 1: should toggle button for row', () => {
    cy.mount(MyComponent, config);
    cy.get('#element-0').should('be.visible');
    cy.get('#toggle-item-0').click();
    cy.get('#element-0').should('not.exist');

    cy.get('#element-1').should('be.visible');
    cy.get('#toggle-item-1').click();
    cy.get('#element-1').should('not.exist');

    // Both items are now hidden, hopefully this state doesn't leak into the next test!!
  });

  it('test 2: items should be visible again despite being hidden in previous test', () => {
    cy.mount(MyComponent, config).then(wrapper => {
      // With this setup, logging false!
      cy.log(`Element visible? ${wrapper.component.items[0].isExpanded}`);
    });
    // Fails!
    cy.get('#element-0').should('be.visible');
    cy.get('#element-1').should('be.visible');
  });
```

This is also what I am using in my real component since we declare some test data in another file and import it. Are you able to reproduce this?

**Comment by mike-plummer** [comment] 2023-06-26 13:22
@dvkuenssberg You've come full circle back to your original problem 😆 . In your new example `item1` and `item2` are defined once but used in multiple tests which introduces cross-test state. Even though you're rebuilding `config` in the `beforeEach` it is using the _reference_ to `item1` and `item2` rather than rebuilding new objects. You should move their initialization into your `beforeEach` at which point everything will work as expected.

```js
beforeEach(() => {
  let item1 = {
    name: 'name1',
    isExpanded: true,
  };
  let item2 = {
    name: 'name2',
    isExpanded: true,
  };
  config = {
    componentProperties: {
      items: [item1, item2],
    },
  };
});
```

**Closed as not planned by mike-plummer** 2023-06-26 13:22 UTC

**Comment by dvkuenssberg** [comment] 2023-06-26 13:44
@mike-plummer You're right...thanks for your patience, I got it now 🤦‍♂️ . I cloned the test items from the other file and it works as expected :).

**Comment by mike-plummer** [comment] 2023-06-26 13:45
@dvkuenssberg No problem, happens to all of us from time to time 😆 😭 . Thanks for using Cypress!
