### ISSUE TITLE
Component test hangs when upgrading to next 12.1.6

### ISSUE THREAD

**Issue by gvocale** [cypress-io/cypress#21514] opened 2022-05-16 16:29 UTC
### Current behavior

After upgrading from Next.js 12.1.5 to 12.1.6, component tests hang indefinitely both on localhost or on CI.

### Test code to reproduce

1. upgrade from Next.js 12.1.5 to 12.1.6
2. run `yarn cypress open-ct`
3. test hangs
4. downgrade from Next.js 12.1.6 to 12.1.5
5. run `yarn cypress open-ct`
6. tests run without issues

### Cypress Version

9.6.0

<img width="2122" alt="Screen Shot 2022-05-16 at 12 30 05 PM" src="https://user-images.githubusercontent.com/1319291/168640232-180b63ad-456c-44ed-a09a-ecc2d93a06aa.png">

**Comment by ZachJW34** [comment] 2022-05-16 16:59
Duplicate of #19382, have an open PR fixing this.

**Closed by ZachJW34** 2022-05-16 16:59 UTC
