### ISSUE TITLE
the chrome browser loops without stop when launching with cypress 

### ISSUE THREAD

**Issue by Eyatester** [cypress-io/cypress#28251] opened 2023-11-06 10:43 UTC
### Current behavior

chrome version 119 cypress version 12.8.1
when launching chrome the page crashes and the test does not run

### Desired behavior

it should be launched correctly.
please can anyone help to resolve the problem .

### Test code to reproduce

gfgf

### Cypress Version

12.8.1 /13.3.1/13.4.0

### Node version

V18.16.1

### Operating System

windows 64

**Comment by alexsch01** [comment] 2023-11-06 12:47
This happened to me on pages such as http://httpforever.com in the past

**Comment by Eyatester** [comment] 2023-11-07 15:36
how you did fix it please. Any solutions?

**Comment by kr106** [comment] 2023-11-08 14:22
I think I am seeing this problem too.

Chrome loops when I attempt to run my test suite against an HTTP site. The tests run headlessly for Chrome, but not in Chrome with the UI. I can run the tests in Electron OK.

This is reproducible with a simple template spec:
describe('template spec', () => {
    it('passes', () => {
      cy.visit('http://example.com/')
    });
  });

I posted about it in the Discord here, but no update yet:
https://discord.com/channels/755913899261296641/1169453901498548274/1169453901498548274

I have a project that uses an HTTP environment for test runs, so I hope that this is something that can be fixed in Cypress.

Cypress 12.7.0
Chrome 119
NodeJS 20.9.0

**Comment by Nahkag** [comment] 2023-11-09 08:33
Hello,
same issue for me

**Comment by mpoetzsch** [comment] 2023-11-21 13:12
seems to be the same problem like here: https://github.com/cypress-io/cypress/issues/25891

Summarization of the ticket:

the issue arises only with newer versions of Chrome (it worked for me with an older version). The problem likely started with the introduction of https://blog.chromium.org/2023/08/towards-https-by-default.html.

Workaround:
change the URL from https to http in the address bar of chrome and reload the web specs runner. After that, the tests run smoothly.

or a more permanent workaround is here:
https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome/881431
(the solution with the most upvotes)

**Comment by Eyatester** [comment] 2023-11-21 13:37
the problem is resolved . Thank's a lot

**Comment by jennifer-shehane** [comment] 2023-11-29 16:45
Duplicate of https://github.com/cypress-io/cypress/issues/25891

**Closed as completed by jennifer-shehane** 2023-11-29 16:45 UTC
Labels: type: duplicate
