### ISSUE TITLE
Running cypress in headless mode should not use xvfb

### ISSUE THREAD

**Issue by mrmeku** [cypress-io/cypress#16505] opened 2021-05-13 17:28 UTC
### Current behavior
Currently, when I use cypress in headless mode via `cypress run`, xvfb is still invoked. Consequently, sometimes this can make my cypress tests error out due to an error.

For example:
`Cypress: Fatal IO error 11 (Resource temporarily unavailable) on X server :105.`

### Desired behavior
When running in headless mode, there is no need to spawn xvfb at all. This should only be done when using `cypress run` to run a browser in headed mode.

### Versions
All versions of cypress up to 7.3.0

**Comment by mrmeku** [comment] 2021-05-13 17:33
I believe the fix for this bug can be done within https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/cli/lib/exec/xvfb.js#L60

If the `isNeeded` function where to accept an argument of whether or not the browser is running in headless mode then we could have it return false immediately. There might be a better place to make the fix though.

I would love to make a PR to fix this bug, but I'd like a little input from the maintainers as to the shape of the fix they are most comfortable with.

**Comment by flotwig** [comment] 2021-05-13 17:44
@mrmeku that sounds like the right path. Does Electron still require X to run though?

**Comment by mrmeku** [comment] 2021-05-14 02:44
That's debatable. Chrome and chromium no longer need XVFB to run any more (see https://developers.google.com/web/updates/2017/04/headless-chrome)

Electron's docs, on the other hand, makes the opposite claim (https://www.electronjs.org/docs/tutorial/testing-on-headless-ci)

I suspect that the electron docs are merely out of date.

Electron would need to be launched using the `--headless` flag to avoid the need for xvfb, but I think if that requirement is met there's no reason I know of that it would need a display server at all

**Comment by mrmeku** [comment] 2021-05-14 02:50
Running electron with the `ELECTRON_RUN_AS_NODE` environment variable might also be part of the magic here: https://www.electronjs.org/docs/api/environment-variables#electron_run_as_node

**Comment by mrmeku** [comment] 2021-05-14 03:38
I did some experimenting with `ELECTRON_RUN_AS_NODE ` and it seems like that strategy could pan out. The only other requirement is that when using `ELECTRON_RUN_AS_NODE ` you can no longer require the electron package. So within packages/server, logic will need to be added to deal with that reality.

You could interact with electron via a helper file `packages/server/electron` which tries to require electron and if it fails, provides a mocked out version of the APIs the server tries to interact with.

Anyway, the change is definitely slightly more involved that I had hoped since electron itself doesn't expose the same display server less headless mode that chromium does.

**Comment by wrslatz** [comment] 2021-06-03 20:57
We've run into this all of a sudden over the past couple of days (combo of this, https://github.com/cypress-io/xvfb/issues/98, and https://github.com/cypress-io/cypress-docker-images/issues/54).

**Comment by CritsAndCode** [comment] 2021-06-03 20:59
Same here. Would love to see a fix for this.

**Comment by mrmeku** [comment] 2021-06-03 21:36
I'll keep hacking on my PR, I just got side tracked

**Comment by wrslatz** [comment] 2021-06-03 22:05
Happy to help test any changes if I can

**Comment by wrslatz** [comment] 2021-06-04 16:12
For now it _seems_ like the `xvfb-run -a` workaround described in https://github.com/cypress-io/cypress-docker-images/issues/54 is holding 🤞🏻 The issue is intermittent so it's hard to tell.

**Comment by sec0ndhand** [comment] 2021-06-15 21:05
Would also love to resolve this, I haven't contributed much, but this would also help support people trying to utilise cypress on heroku ci [here.](https://github.com/cypress-io/cypress-example-kitchensink/issues/324)

**Closed** 2021-07-09 14:38 UTC
Labels: stage: needs review

**Comment by mrmeku** [comment] 2021-07-09 16:10
@jennifer-shehane @flotwig Would it be possible for someone to build a cypress binary for linux now that this change has been merged so I can test out the changes in my own projects to better exercise edge cases?

**Comment by bahmutov** [comment] 2021-07-09 16:18
@mrmeku see https://github.com/cypress-io/cypress/commit/cf689dd6093b92cd950e9ec77edd84977f90260f#commitcomment-53273920
