### ISSUE TITLE
"require is not defined" error throws with cypress 5.2.0

### ISSUE THREAD

**Issue by taitranvungle** [cypress-io/cypress#8656] opened 2020-09-24 08:54 UTC
We've just upgraded from Cypress 4.x to 5.2.0, then updated the .babelrc, webpack.config.js files already. When running the test, the error "require is not defined" throws

### Current behavior
Error log:
``` 
ReferenceError: The following error originated from your test code, not from Cypress.

  > require is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
    at Object.path (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:112651:1)
    at __webpack_require__ (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:20:30)
    at Object../node_modules/cypress-file-upload/dist/bundle.js (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:432:9)
    at __webpack_require__ (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:20:30)
    at Module../cypress/support/index.js (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:289:77)
    at __webpack_require__ (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:20:30)
    at Object.0 (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:112639:18)
    at __webpack_require__ (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:20:30)
    at eval (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:84:18)
    at eval (https://react-marketplace-integ.bstock.io/__cypress/tests?p=cypress/support/index.js:87:10)
From previous event:
    at Object.runScripts (https://react-marketplace-integ.bstock.io/__cypress/runner/cypress_runner.js:176807:28)
    at $Cypress.onSpecWindow (https://react-marketplace-integ.bstock.io/__cypress/runner/cypress_runner.js:166278:20)
```

### Desired behavior
The test should run successfully as they did in Cypress 4.x

### Test code to reproduce

1. package.json
```json
{
  "name": "cypress-tests",
  "version": "1.0.0",
  "description": "Cypress test",
  "scripts": {
    "cy": "node_modules/.bin/cypress open",
    "cy:run": "node_modules/.bin/cypress run --browser chrome",
  },
  "dependencies": {
    "cypress": "^5.2.0",
    "cypress-file-upload": "^4.1.1",
    "cypress-wait-until": "^1.7.1",
    "cypress-xpath": "^1.6.0",
    "faker": "^5.1.0",
    "googleapis": "^39.2.0",
    "moment": "^2.27.0",
    "typescript": "^3.9.5"
  },
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^5.4.5",
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "babel-loader": "^8.1.0",
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12",
    "cross-env": "^7.0.2"
  },
  "eslintIgnore": [
    "node_modules/"
  ]
}

```

2. webpack.config.js
```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    target: 'node',
    mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
    plugins: [
        new webpack.IgnorePlugin(/^pg-native$/),
        new webpack.DefinePlugin({
            'process.env.BROWSER': false,
            __DEV__: process.env.NODE_ENV !== 'production',
        }),
    ],
    module: {
        rules: [
            {
                test: /\.(mjs|js|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader',


                options: {
                    presets: [
                        '@babel/preset-env',
                        {
                            plugins: [
                                '@babel/plugin-proposal-class-properties'
                            ]
                        }
                    ]
                },


            }
        ],
    }
};
```

3. index.js
```js
const webpackPreprocessor = require('@cypress/webpack-preprocessor')

module.exports = (on) => {
    const options = {
        webpackOptions: require('../../webpack.config'),
        watchOptions: {},
    }
    on('file:preprocessor', webpackPreprocessor(options))
}
```

4. .babelrc
```yml
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.10"
        }
      }
    ]
  ],


  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

Error screen-shot:
![image](https://user-images.githubusercontent.com/39422419/94123530-1a5f2980-fe7e-11ea-80d9-ab665e56639e.png)

### Versions
MacOS 10.15.6
Chrome 85
Cypress 5.2.0

**Comment by aelmekeev** [comment] 2020-10-16 12:58
@taitranvungle any luck with this? Having the same issue now 🤔

**Comment by taitranvungle** [comment] 2020-10-19 02:46
> @taitranvungle any luck with this? Having the same issue now 🤔

Try removing "target: 'node'" from your webpack.config.js

**Comment by jennifer-shehane** [comment] 2020-10-19 10:00
I can't recreate the error as described. It looks like it's originally throwing from the support/index.js file, which you didn't include. Can you provide a fully reproducible example? A repo is ideal. Thanks.

**Comment by taitranvungle** [comment] 2020-10-19 10:15
Hi @jennifer-shehane , please find my support/index.js file below
```
import './commands';
import 'cypress-file-upload';
import 'cypress-wait-until';
import 'cypress-xpath';
```
After removing "target: 'node'" from webpack.config.js, the error goes

**Comment by jennifer-shehane** [comment] 2021-02-22 14:38
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-22 14:38 UTC
Labels: stage: needs information

**Comment by raunakthakkar** [comment] 2021-02-27 08:52
I can see a similar kind of error 
![image](https://user-images.githubusercontent.com/39436952/109382543-0fb23000-7907-11eb-83df-2173b17b6ecc.png)
where cypress tells, "React is not defined".

**Comment by jennifer-shehane** [comment] 2021-02-27 14:44
@raunakthakkar Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by reidswanson** [comment] 2022-05-12 23:50
I know it's been a long time since the last comment, but I seem to have just run into a similar issue. I'm pretty new to Node, React, Next etc. so I've been sort of fumbling around various tutorials trying to get things working. Strangely, I had almost everything working 2 days ago except global and module css files were not being applied to the component tests. 

I had previously installed some other testing frameworks and additional cruft that I tried to clean up, but wound up not being able to launch cypress at all. Eventually, I was able to reinstall the necessary dependencies and launch the cypress component test browser again, but then ran into the "require is not defined" error.

Since then I have created several new projects from scratch following various different tutorials:

- https://medium.com/geekculture/component-testing-next-js-application-with-cypress-28fa311adda6
- https://docs.cypress.io/guides/component-testing/introduction#Writing-Component-Tests
- https://github.com/cypress-io/cypress/tree/master/npm/react

Most of the tutorials I've listed, and elsewhere, more or less have the same steps except the last, which should in theory automatically configure things for you. However, no matter what I do, I get the "require is not defined" error. The full stack trace is below, because it is slightly different than the original. I committed one of my attempts [here](https://github.com/reidswanson/nextjs-cypress-ct) as a MWE. 

```
cypress_runner.js:218376 ReferenceError: The following error originated from your test code, not from Cypress.

  > require is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at Object.__webpack_require__.f.require (http://localhost:8080/__cypress/src/main.js:194:15)
    at http://localhost:8080/__cypress/src/main.js:133:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (http://localhost:8080/__cypress/src/main.js:132:67)
    at loadSupportFile (webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js:2:51)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:203384:86
From previous event:
    at Object.runScripts (http://localhost:8080/__cypress/runner/cypress_runner.js:203384:62)
    at $Cypress.onSpecWindow (http://localhost:8080/__cypress/runner/cypress_runner.js:191795:76)
    at init (webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/aut-runner.js:10:13)
    at eval (webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js:19:3)
    at Object../node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js (http://localhost:8080/__cypress/src/main.js:40:1)
    at __webpack_require__ (http://localhost:8080/__cypress/src/main.js:88:42)
    at render (webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/browser.js:3:5)
    at eval (webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/browser.js:5:1)
    at Object../node_modules/@cypress/webpack-dev-server/dist/browser.js (http://localhost:8080/__cypress/src/main.js:30:1)
    at __webpack_require__ (http://localhost:8080/__cypress/src/main.js:88:42)
    at http://localhost:8080/__cypress/src/main.js:211:37
    at http://localhost:8080/__cypress/src/main.js:214:12
```

I have a bad feeling it will work fine for others and there is something strange about my environment. In any case I would appreciate any help.

**Comment by AliceMSapient** [comment] 2022-05-13 03:50
I am also facing this problem, I have followed different setups my most current example has been when following: 
https://github.com/cypress-io/cypress-component-testing-examples/tree/main/create-next-app-webpack-5

`The following error originated from your test code, not from Cypress.

  > require is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

at Object.__webpack_require__.f.require (http://localhost:57356/__cypress/src/main.js:205:16)
    at <unknown> (http://localhost:57356/__cypress/src/main.js:144:41)
        at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (http://localhost:57356/__cypress/src/main.js:143:68)
    at loadSupportFile ([webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js:2:52](http://localhost:57356/__/#))
    at <unknown> (http://localhost:57356/__cypress/runner/cypress_runner.js:203384:87)
From previous event:
    at Object.runScripts (http://localhost:57356/__cypress/runner/cypress_runner.js:203384:63)
    at $Cypress.onSpecWindow (http://localhost:57356/__cypress/runner/cypress_runner.js:191795:77)
    at init ([webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/aut-runner.js:10:14](http://localhost:57356/__/#))
    at eval ([webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js:19:4](http://localhost:57356/__/#))
    at Object../node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js (http://localhost:57356/__cypress/src/main.js:40:2)
    at __webpack_require__ (http://localhost:57356/__cypress/src/main.js:99:43)
    at render ([webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/browser.js:3:6](http://localhost:57356/__/#))
    at eval ([webpack-internal:///./node_modules/@cypress/webpack-dev-server/dist/browser.js:5:2](http://localhost:57356/__/#))
    at Object../node_modules/@cypress/webpack-dev-server/dist/browser.js (http://localhost:57356/__cypress/src/main.js:30:2)
    at __webpack_require__ (http://localhost:57356/__cypress/src/main.js:99:43)
    at <unknown> (http://localhost:57356/__cypress/src/main.js:222:38)
    at <unknown> (http://localhost:57356/__cypress/src/main.js:225:13)


`

next.config.js
`module.exports = {
  future: {
    webpack5: true,
  },
};`

package.json
`{
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "cypress:open": "cypress open"
  },
  "dependencies": {
    "next": "latest",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "webpack": "5"
  },
  "devDependencies": {
    "@cypress/react": "^5.12.4",
    "@cypress/webpack-dev-server": "^1.8.4",
    "cypress": "^9.6.1",
    "html-webpack-plugin": "5",
    "webpack-dev-server": "3"
  }
}`

cypress/plugins/index.js
`const injectDevServer = require("@cypress/react/plugins/next");

module.exports = (on, config) => {
  injectDevServer(on, config);
  return config;
};`

**Comment by reidswanson** [comment] 2022-05-14 21:29
@AliceMSapient reverting to Next.js v11.1.3 fixed the error for me. I haven't done much beyond seeing the component rendered, so I can't say what else is or isn't working, but thought this info might get you (and anyone else who stumbles on this error) going.
