### ISSUE TITLE
Clicking URL's with target=_parent makes Cypress break out of its environment

### ISSUE THREAD

**Issue by JDansercoer** [cypress-io/cypress#3282] opened 2019-02-01 14:30 UTC
### Current behavior:

Clicking an `a` tag that has the `target=_parent` property, causes Cypress to fail and displays that there are no tests found.

### Desired behavior:

Don't break the Cypress process.

### Steps to reproduce: (app code and test code)

```js
cy.visit(INITAL URL);
cy.get('.BUTTON CLASS').click();
cy.url().should('include', '/klantendienst/klacht');
```

After the button click, the window displays that there are no tests found, so unable to continue.

### Versions

Cypress 3.1.5

**Comment by jennifer-shehane** [comment] 2019-02-05 08:15
Duplicate of https://github.com/cypress-io/cypress/issues/3121

**Closed by jennifer-shehane** 2019-02-05 08:15 UTC
