### ISSUE TITLE
failed assert doesn't trigger failed test

### ISSUE THREAD

**Issue by utiq** [cypress-io/cypress#19211] opened 2021-12-02 21:01 UTC
### Current behavior

If I use async/await to handle a promise and there is a failed assertion after, the test is not considered as failed
```
it.only('should start', async () => {
   // I have my await code here
   .
   .
   .
    cy.contains('some content').should('exist')
})
```
![image](https://user-images.githubusercontent.com/1144196/144501703-a0f14369-b88d-445c-a4d4-9cda73c6e9b2.png)

### Desired behavior

The test should fail

### Test code to reproduce

```
var helloResult = () => {
  return new Promise(resolve => {
    setTimeout(() => resolve('world'), 1000);
  });
};

it.only('should start', async () => {
    const response = await helloResult();
    console.log(response)
    cy.contains('some content').should('exist')
})
```

### Cypress Version

9.1.0

**Comment by sainthkh** [comment] 2022-04-04 07:47
Sorry for the late reply.

Confirmed that it doesn't work.

**Comment by emilyrohrbough** [comment] 2022-11-17 15:05
Duplicate of: https://github.com/cypress-io/cypress/issues/4742. Closing in favor of https://github.com/cypress-io/cypress/issues/4742.

**Closed by emilyrohrbough** 2022-11-17 15:05 UTC
Labels: type: bug, stage: backlog
