### ISSUE TITLE
Cypress not opening  libnode.so

### ISSUE THREAD

**Issue by chris2kus31** [cypress-io/cypress#3936] opened 2019-04-10 20:03 UTC
### Current behavior:

After running `./node_modules/.bin/cypress open`
I get the below error

```
/home/chris2kus/.cache/Cypress/3.2.0/Cypress/Cypress: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory
```

### Desired behavior:

Trying to install cypress to start testing a symfony appliaction. 

### Versions

linux mint

**Comment by flotwig** [comment] 2019-04-10 21:13
Hey @chris2kus31, another user was having a similar issue with `libnode.so` not existing. Can you try the workarounds in the linked comment and let me know if it resolves the issue for you?

https://github.com/cypress-io/cypress/issues/3878#issuecomment-479911001

**Comment by chris2kus31** [comment] 2019-04-10 22:07
It seems to run when you install the prior version of cypress.   Could that have anything to do with that?

**Comment by flotwig** [comment] 2019-04-10 22:39
Maybe. When you update, Cypress downloads a .zip containing all the files it needs to run. Sometimes those .zip files have trouble unzipping which can cause issues like this. There are some open issues about improving how we verify/install the Cypress updates because this does happen from time to time.

Did re-installing Cypress 3.2.0 using the steps in my comment in the other thread fix the issue? If so, this is what you're running in to.

**Comment by chris2kus31** [comment] 2019-04-10 22:46
No, it installed after I reverted back to 3.1.5

**Comment by flotwig** [comment] 2019-04-11 14:20
@chris2kus31 Great! Let me know if deleting and re-installing Cypress 3.2.0 as described in the linked comment does not fix your issue, and then we'll know if this is a new issue or just a duplicate of #3878.

**Comment by jennifer-shehane** [comment] 2019-04-18 07:11
@chris2kus31 Any updates? Please close this issue if resolved.

**Comment by jennifer-shehane** [comment] 2019-04-30 06:05
Closing. No recent activity.

**Closed by jennifer-shehane** 2019-04-30 06:05 UTC
