### ISSUE TITLE
Error Whoops, there is no test to run.

### ISSUE THREAD

**Issue by cypress1980** [cypress-io/cypress#15126] opened 2021-02-17 14:13 UTC
@bahmutov ,

I am getting the error "Whoops, there is no test to run

After clicking on Login  getting the error "Whoops, there is no test to run

Here is my script 
```js
/// <reference types="cypress" />

describe("Test login funcationlity ", () => {
  it("Open URL", () => {
    cy.visit("test-3b.my.salesforce.com");
  });
  it("Login Into Application", () => {
    cy.get("#username").type("kailash.pathak-kttk@force.com");
    cy.get("#password").type("Kp@12345");
    cy.get("#Login").click();
  });
});
```
![image](https://user-images.githubusercontent.com/76464201/108216355-60cc6200-7158-11eb-8913-e9fe8e929a56.png)

**Comment by jennifer-shehane** [comment] 2021-02-18 13:35
Duplicate of https://github.com/cypress-io/cypress/issues/2367 See the thread for any current workarounds.

**Closed by jennifer-shehane** 2021-02-18 13:35 UTC
Labels: topic:  😳 whoops there is no test to run
