### ISSUE TITLE
Requests to basic auth urls with the chrome browser time out

### ISSUE THREAD

**Issue by itsthatguy** [cypress-io/cypress#573] opened 2017-07-25 14:56 UTC
- Operating System: macOS 10.12.5
- Cypress Version: 0.19.4
- Browser Version: chrome 59.0.3071.115

### Is this a Feature or Bug?

Bug?

### Current behavior:

Running tests in the desktop app, using the chrome browser, against a URL with a basic auth url (ie; `https://username:password@my-site.com`) times out

### Desired behavior:

Running tests in the desktop app, using the chrome browser, against a URL with a basic auth url works

### How to reproduce:

Run a test in the desktop app, using the chrome browser, against a URL with a basic auth url

#### Test code:

```js
describe('My Site', function() {
  it('Go to My Site', function() {
    cy.visit('https://username:password@my-site.com')
  })
});
```

### Additional Info (images, stack traces, etc)

https://www.chromestatus.com/feature/5669008342777856

**Comment by rarichard** [comment] 2017-08-07 13:48
I have the same problem, is there a way to interactively supply basic auth? Or via configuration? 

This shows up in js console when providing basic auth via url:
[Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.

**Comment by brian-mann** [comment] 2017-08-07 14:59
After doing some preliminary research there appears to be a couple solutions we could implement

- Expose Chrome flags to enable the user to disable this feature
- Expand `cy.visit` to accept an `auth` object and then inject credentials to every request going to that domain at the network proxy level
- Come up with an entirely different workaround after some more experimentation

**Comment by rarichard** [comment] 2017-08-07 15:01
I think the #2 option may be best - we have basic auth in every environment, and it would be nice to have the credentials swapped in with a local config or env variable, especially in environments where devs aren't allowed to access creds, we would need it.

**Comment by brian-mann** [comment] 2017-08-07 16:02
I agree. I need to do some research on how the browser decides to attach credentials to resources - whether it applies the typical `same origin policy` logic or something else entirely.

For instance are credentials applied on the superdomain level and automatically get sent for each subdomain? Or do those require their own credentials?

**Comment by brian-mann** [comment] 2017-09-25 14:55
Update: the chrome flag for disabling this security restriction and enabling the current method to work is: `--disable-blink-features=BlockCredentialedSubresources`

**Comment by brian-mann** [comment] 2017-09-28 00:32
The code for this is merged, but it has not been released yet.

**Closed by brian-mann** 2017-09-28 00:32 UTC
Labels: type: bug

**Comment by brian-mann** [comment] 2017-10-06 16:41
Fixed in [`0.20.2`](https://docs.cypress.io/guides/references/changelog.html#0-20-2).

**Comment by bm-stschneider** [comment] 2017-10-16 06:37
So this still needs documentation I guess? Since I couldn't find anything on how basic auth is now implemented.

**Comment by brian-mann** [comment] 2017-10-16 13:41
There's nothing special about basic auth - you just use it the way the spec defines it in the URL.

http://username:password@example.com

`cy.request('http://username:password@example.com')`

**Comment by bm-stschneider** [comment] 2017-10-16 15:04
Does this work now without changing web security setting of the browser?

**Comment by brian-mann** [comment] 2017-10-16 16:02
The web security setting never affected basic auth in any way that I know of.

**Comment by pbastowski** [comment] 2017-10-16 18:47
`cy.visit('http://username:password@example.com')` works for me.

Thanks.

**Comment by rafath-mfind** [comment] 2018-01-17 22:07
I've found solution for this... in cypress.json add baseUrl option:
`"baseUrl": "http://username:password@localhost:3000"`
and in tests suite use `cy.visit('/')`

**Comment by tomardern** [comment] 2019-07-29 15:14
This no longer works when using electron :(

**Comment by JBustin** [comment] 2020-05-22 12:54
I don't know if it is the same problem, but when I use this syntax `cy.visit('${Cypress.config('baseUrl')}/other/stuff')` with `https://login:pwd@myurl.com` as baseUrl, cypress cannot launch test in browser.
It tries to reach `https://myurl.com/__/#/tests/integration/myfirstspec.js` and chrome display the error "website unreachable"

**Comment by jennifer-shehane** [comment] 2020-07-14 08:55
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
