### ISSUE TITLE
Cypress 'expect' with 'regex' fails to validate on second occurrence.

### ISSUE THREAD

**Issue by praveentata** [cypress-io/cypress#19044] opened 2021-11-22 18:44 UTC
### Current behavior

Steps to reproduce:
1) Read a text from any web page.
2) Use `expect` to `match` a `regex`.
3) Now, read the same data from the web page again.
4) Use `expect` to `match` a `regex`.

Actual result: Validation passes the first time but the same validation fails the second time.

![Cypress Expect Failure](https://user-images.githubusercontent.com/26746723/142917573-759c383e-b841-47b9-b3e8-9904eaf4bf3f.JPG)

### Desired behavior

The validation should pass each time if the condition is satisfied or report the appropriate failure if the condition fails.

### Test code to reproduce

```
/* eslint-disable cypress/no-unnecessary-waiting */
/* eslint-disable no-unused-vars */
/// <reference types="Cypress" />

it("Testing Table Validation", () => {
    let regex = /Germany|UK/gm;
    cy.visit("https://www.w3schools.com/html/html_tables.asp");
    cy.get("table[id='customers'] tbody tr:nth-child(2) td:nth-child(3)")
      .then(element => {
          cy.log(element.text());
          expect(element.text()).to.match(regex); // This validation works fine.
      });

    cy.wait(2000);
    cy.get("table[id='customers'] tbody tr:nth-child(2) td:nth-child(3)")
      .then(element => {
          cy.log(element.text());
          expect(element.text()).to.match(regex); // This validation fails.
      });
});
```

### Cypress Version

8.5.0

### Other

Am I doing something wrong here?
The same scenario works if I use `should` instead of `expect`.

**Comment by chrisbreiding** [comment] 2021-11-29 15:29
I was able to reproduce it with the following:

index.html

```html
<div>Word</div>
```

spec.js

```js
const regex = /Word/g;

it('demonstrates regex match issue', () => {
  cy.get('div').then(($el) => {
    expect($el.text()).to.match(regex)
  })
  cy.get('div').then(($el) => {
    expect($el.text()).to.match(regex)
  })
})
```
 
This is because of using the global regex flag and using the same regex again. Remove the global flag or use a different regex reference and it passes. The [lastIndex property of a regex is updated when using the global flag](answer-9873228), influencing any subsequent uses of it.

Cypress could potentially reset the lastIndex to 0 anytime a regex is passed in, but I'm not sure if that's the best solution. Would need further discussion on whether there are any downsides to doing that.

For now, removing the global flag is the simplest fix. Otherwise, use different regex references like so:

```js
it('demonstrates regex match issue', () => {
  cy.get('div').then(($el) => {
    expect($el.text()).to.match(/Word/g)
  })
  cy.get('div').then(($el) => {
    expect($el.text()).to.match(/Word/g)
  })
})
```

**Comment by praveentata** [comment] 2021-11-29 15:32
Thanks for the update @chrisbreiding 
I will try using the solution you provided for now.

**Comment by praveentata** [comment] 2021-12-01 03:20
@chrisbreiding Do you know why the same code works with `should` and not with `expect`?
I can reuse the `const regex` multiple times with `should` without any problem.

**Comment by chrisbreiding** [comment] 2021-12-01 04:39
> Do you know why the same code works with should and not with expect?

It's because of these two things:

- `should` will retry the assertion until it passes or times out. 
- The [`lastIndex` property resets to 0 after failing to find a match](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex#description).

So what happens using `should` is this:

- First `should` passes. `lastIndex` is set to `9` after match.
- Second `should` fails. `lastIndex` is reset to `0` after failure to match.
- Cypress retries second `should` and it passes.

**Comment by praveentata** [comment] 2021-12-01 13:35
> 

Thanks Chris. That makes it clear.

**Comment by chrisbreiding** [comment] 2021-12-01 14:34
I'm going to close this as there's a solution and I don't think we should interfere in the behavior of regular expressions for this case. It's really more of an issue with JavaScript itself and not Cypress, similar to needing to do a deep comparison for two object references (e.g. `expect({}).to.equal({})` vs `expect({}).to.deep.equal({})`).

**Closed by chrisbreiding** 2021-12-01 14:34 UTC
