### ISSUE TITLE
Endurance testing with Cypress

### ISSUE THREAD

**Issue by matt-psaltis** [cypress-io/cypress#1435] opened 2018-03-08 10:55 UTC
### Current behavior:
A small note about performance testing being one of the things you don't do with Cypress.
https://docs.cypress.io/guides/references/trade-offs.html#Automation-restrictions

### Desired behavior:
So we've written a heap of Cypress tests for different end user workflows through our product and now we're looking for ways to simulate a user using the platform over the course of several hours (our goal is 8h+)

* Ability to maintain a single browser session across multiple tests.

* Chain existing tests together. At the conclusion of a test, specify the next test to run in the test sequence. This allows for different user workflows to be created dynamically at run-time. The tests should still execute as separate tests to facilitate separate reporting on the different user workflows instead of just capturing success / failure of the whole workflow.

* Memory snapshots and statistics capture from snapshots to help with memory leak detection.

* Different (configurable) compensation strategies:
   - On application error, terminate the current browser session and establish a new one.
   - On application error, log the error and continue within the current browser session.
   - On application error, stop the test (pretty much what happens now).

* Capture statistics to identify executions that took longer / shorter (standard deviation metrics).

* Errors are captured and aggregated together for statistical reporting (I.E. spec 1 failed 88 times out of 100)

* All of the above captured into the Dashboard service

* Stretch goal: Run multiple instances across different browsers concurrently to do stress testing. Failure rate and other metrics captured on per browser basis. (This one seems less likely to happen given the comments on the link above)

So there's a starting point for our feature wish list (I realize these aren't small things). This might get quickly closed as falling under the banner of performance testing but I hope it can spark some further discussion because there actually aren't that many tools out there that can consistently mimic an end user to the simplicity and extend of Cypress. I know a good chunk of this functionality can be delivered with the existing framework components (Plugins, Cypress Events, Uncaught exception handling) but my hope is that Cypress may consider, or are planning in the future to go into this space as a first-class solution offering long running testing within the Cypress framework and Dashboard service.

**Comment by brian-mann** [comment] 2018-03-08 19:13
Many of the things listed are what we are already doing in our dashboard - some of which is being released in `3.0.0` - namely to collect runtime data of tests in order to show historical run times / outliers, etc. 

This will help you understand where fast vs slow tests are, or performance of them given a period of time - and to also help highlight commits that made all tests run slower.

The workflows you're suggesting can just be composed of functions that you chain together. The tests themselves are agnostic - you'd just roll up behavior and call functions to create more actions - and then reuse those same actions in smaller tests. Nothing specific Cypress here, just basic programming.

Memory snapshots are a whole other animal because Cypress itself will influence what's happening in your application. I'm not sure if you can isolate memory snapshots to a single window to avoid getting Cypress-bits mixed up in your own reports.

At Cypress we **really** want to solve the management of test suites over the long term. We are most interested in identifying performance regressions around the timings of things. And to further be able to give precise data around the actual "thing" that may have changed which caused this.

**Comment by SaltyDH** [comment] 2018-03-08 20:13
Hi Brian, definitely excited to see what 3.0 has in store! The historical runtimes sounds like a huge help.

In terms of the workflows, by composing them together under a single test run, I start to lose the granularity over the statistics we are hoping to capture and as you describe, the actual "thing" that caused the change / regression.

What I'd love to be able to do is to append tests in the afterEach hook and have Cypress pick that up in the test runner. Each dynamically generated test would be executing an existing workflow in our test suite. This way, tests can be looked at in isolation, or grouped together even with some simple naming conventions like:

`"Create user test #1"`
`"Create user test #2"`

Then, in the dashboard these test runs can be aggregated and show

`"Create user test"
  - Attempts: 2
  - Passes: 2
  - Average time taken: 100ms
  - Outlier data etc.
`

I had a go using the underlying Mocha addTest functionality but that causes inconsistencies about which test is actually running in the suite and the UI runner doesn't look like it will pick up new tests added to a suite over time.

I'll see what I can find on the memory snapshot front.

Thanks for taking the time to reply - greatly appreciate it.

**Comment by jennifer-shehane** [comment] 2021-03-31 19:00
We are doing a lot more of these things today in the Dashboard. 

The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thanks!

**Closed by jennifer-shehane** 2021-03-31 19:00 UTC
Labels: stage: proposal 💡, type: feature
