### ISSUE TITLE
cy.request - Content-type header can't be set for POST and PUT requests

### ISSUE THREAD

**Issue by Olgagr** [cypress-io/cypress#7816] opened 2020-06-25 14:08 UTC
### Current behaviour:

I'm passing to the `cy.request` command the options object that contains the header `Content-type`:

```js
cy.request({
  method: 'POST',
  url: `${Cypress.env('RAILS_APP_URL')}/admin/api/clients`,
  headers: {
    'Content-Type': 'application/json; charset=utf-8',
  },
  body: {}
})
```

For some reason, the header is not sent to the server. In the console, I can verify that the request doesn't have `Content-Type` :

![screenshot_6](https://user-images.githubusercontent.com/1297219/85735428-eef16500-b6fd-11ea-8c6e-d6f9715cac5e.png)

The same is true for PUT verb:

```js
cy.request({
  method: 'PUT',
  url: `${Cypress.env('RAILS_APP_URL')}/admin/api/employees/54967`,
  body: {},
  headers: {
    'Content-Type': 'application/json; charset=utf-8',
  }
})
```

![screenshot_7](https://user-images.githubusercontent.com/1297219/85734602-7094c300-b6fd-11ea-997b-caa233a5f114.png)

The only way I can force to set the `content-type` header is to add to each URL `.json` postfix eg.  `${Cypress.env('RAILS_APP_URL')}/admin/api/clients.json`

I can't find any information in the docs that `Content-Type` is ignored and won't be set for POST/PUT request. When I set it for GET a request it is set correctly.

### Desired behaviour:

When I set `Content-Type` header in the `cy.request` command, it is sent with the request. 

### Versions

cypress 4.7.0
operating system: Linux Ubuntu 18 LTS
browser: Chrome 83

**Comment by jennifer-shehane** [comment] 2020-06-26 11:12
I'm not able to reproduce this with the example below. I do see some extra request headers on your request. Can you share any other accompanying code required to reproduce this?

```js
it('example', () => {
  cy.request({
    method: 'POST', 
    url: 'https://jsonplaceholder.cypress.io/posts', 
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
    },
    body: null
  })
})
```

<img width="772" alt="Screen Shot 2020-06-26 at 5 40 50 PM" src="https://user-images.githubusercontent.com/1271364/85851168-364a2500-b7d4-11ea-9ee1-282e1f8936b6.png">

**Comment by Olgagr** [comment] 2020-06-29 14:14
@jennifer-shehane Thanks for a check. I will try to reproduce that and I will return with more info.

**Comment by Olgagr** [comment] 2020-06-30 09:07
@jennifer-shehane I only noticed one difference that I can reproduce. In case of your request, there is no `referer` header sent. In case of request to our API, the `referer` is always sent. It seems connected. When the request headers contains `referer` header, the `Content-Type` is not sent when set as an option.

**Comment by gitsaquib** [comment] 2020-07-30 12:50
Can we override referer? I dont want Referer like localhost:port/_cypress.... I want to set this to say https://jira.myjira.com

**Comment by jennifer-shehane** [comment] 2020-12-15 08:26
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-12-15 08:26 UTC
Labels: stage: needs information

**Comment by LegendaryRaph** [comment] 2021-08-09 12:22
I have the same problem now, how did you fix it? 
```
cy.request({
                method: 'POST',
                url: '/api/mobile/order/save',
                body: {
                    date: '2021-08-05 15:52:29.290000',
                    customerNumber: '0129482034',
                    customerId: '251',
                    recipientId: '252',
                    scanUserId: '42194',
                    orderPositions: [{
                        scanId: 'qag2UYJyB1IG',
                        quantity: '1'
                    }]
                },
                headers: {
                    'XSRF-TOKEN': token
                }
            })
```

I am passing the token, but it does not get sent:
![image](https://user-images.githubusercontent.com/74573437/128705214-9a698af4-1789-42e2-b064-0a606ca1333d.png)

**Comment by listana** [comment] 2022-02-11 13:04
Its floating error. 
Custom Request header was ignored in my GET cy.request()
I changed the method type from GET to POST - it failed with 422 error, but in request Headers there was my header.
Then I restored method type to GET - and wow - header appeared. No wonder its hard to reproduce.

**Comment by surfjedi** [comment] 2024-12-05 18:11
This is still an issue in cypress 13 can we reopen?
I'm trying to do a POST with a header: 'Content-Type': 'application/x-amz-json-1.1' and cypress ignores that

**Comment by jennifer-shehane** [comment] 2024-12-09 18:27
@surfjedi Can you provide information for us to reproduce this on our side in a new issue?
