### ISSUE TITLE
cy.intercept('url', {forceNetworkError:true}) not working in Cypress 10.7

### ISSUE THREAD

**Issue by abruskin** [cypress-io/cypress#23674] opened 2022-09-02 16:46 UTC
### Current behavior

Through Cypress 10.6, I could force a network error using the static response:

cy.intercept('url', {forceNetworkError:true})

After updating to Cypress 10.7, the test ignores the intercept.  

### Desired behavior

cy.intercept('url', {forceNetworkError:true}) should force an error state so that the error state itself can be tested. 

### Test code to reproduce

cy.intercept('url', {forceNetworkError:true})

### Cypress Version

10.7

### Node version

16.2.0

### Operating System

Windows 10

**Comment by emilyrohrbough** [comment] 2022-09-06 15:02
@abruskin I was unable to reproduce the issue you have described on Cypress 10.7. Using the following example, I was able to force a network error. 
```js
it("forces network error", () => {
  cy.intercept('/commands/querying', {forceNetworkError:true})
  cy.visit("https://example.cypress.io")
  cy.contains('a', 'get').click()
});
```

Can you share the error/behavior you are encountering and a reproducible example demonstrating this behavior?

**Comment by abruskin** [comment] 2022-09-06 19:53
I use {forceNetworkError:true} in several tests, all of them work in 10.6 but fail in 10.7. The version of cypress that is running is the only difference. Are there any config changes I should be making?

**Comment by emilyrohrbough** [comment] 2022-09-06 21:06
@abruskin There shouldn't be any configuration changes. Is this the error you are seeing? Looking at my repo, looks like I did have `experiementalSessionAndOrigion=true` in my configuration. When removing I am seeing this.
<img width="683" alt="Screen Shot 2022-09-06 at 4 05 38 PM" src="https://user-images.githubusercontent.com/14099737/188738016-36da88c1-f988-4d2f-93f3-228871bf68d8.png">

**Comment by abruskin** [comment] 2022-09-07 02:07
No, the cy.get command that is looking for the error modal is failing, 'timed out retrying after 4000ms: Expected to find element: .modal-content , but never found it.' In the test preview, the error modal does not display and the appointment was created successfully, but forceNetworkError:true should have blocked appointment creation and prompted the error modal.

**Comment by abruskin** [comment] 2022-09-07 02:09
![Screenshot 2022-09-06 210505](https://user-images.githubusercontent.com/90646708/188772888-0e0faeed-694e-4dda-a528-5a61a1da1cc2.png)

**Comment by abruskin** [comment] 2022-09-07 19:16
I rewrote my intercepts to use {statusCode:500} instead of {forceNetworkError:true} and now they're all working.

**Comment by chrisbreiding** [comment] 2022-09-15 17:32
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by chrisbreiding** [comment] 2022-09-22 14:13
Going to close this issue as there isn't currently a way for us to reproduce this issue. Please post a comment with a reproducible example and we'll re-open this issue.

**Closed by chrisbreiding** 2022-09-22 14:13 UTC
Labels: stage: awaiting response, Needs Reproduction

**Comment by arthurakay** [comment] 2024-10-03 14:14
In `"cypress": "^13.15.0",` I have a similar test:

```
  it('should force a network error', () => {
    // force a network error!
    cy.intercept({ url: '/api/prompt/', times: 1 }, { forceNetworkError: true })

    cy.visit(PORTAL_URL);
    cy.wait(3000);

    // prompt/submit
    cy.get('textarea').type('Book me a flight from ORD to AUS on January 1, 1970 returning on January 1, 1969');
    cy.get(`span[title="Let's go!"]`).click();

    // Click causes API call to /api/prompt...

    // let API respond...
    cy.wait(3000);
    cy.get('.notice-text').contains('Unsupported Request').should('exist');
  });
```

The idea behind this test is that the UI displays some text when the network call fails -- a different scenario than "the server threw a 500". 

As written, Cypress does not cause that network call to fail.

Changing `forceNetworkError: true` to `statusCode: 500` does result in the API throwing a 500 error... but as noted that's not the same test as "server can't be reached".

**Comment by arthurakay** [comment] 2024-10-03 14:33
I also did notice that changing to simply `cy.intercept({ url: '/api/prompt/' }, { forceNetworkError: true });` works... so maybe the `times: 1` bit was throwing it off somehow.

Sorry to resurrect an old thread, hoping this helps someone else in the future.

https://xkcd.com/979/
