### ISSUE TITLE
Cypress 9.1.1 + Node 17.2 (Win 11) Crashes 

### ISSUE THREAD

**Issue by NguyenEngine** [cypress-io/cypress#19320] opened 2021-12-09 12:37 UTC
### Current behavior

Same as issue which is fixed for Cypress v9.1.1. and Node 17.1 seems to have returned for Cypressv9.1.1. and Node 17.2 : https://github.com/cypress-io/cypress/issues/18914

### Test code to reproduce

no test code required

### Cypress Version

9.1.1.

### Other

Adding `"nodeVersion": "bundled"` in the `cypress.json` works around the issue.

**Comment by fazo96** [comment] 2021-12-13 14:16
Same issue on Linux. Using `"nodeVersion": "bundled"` is necessary if the system's nodejs version is >=17

**Comment by amuttsch** [comment] 2021-12-14 14:26
Seems to be related to https://github.com/cypress-io/cypress/issues/18914

This issue also occurs on linux and mac m1.

**Comment by ivandjorgon** [comment] 2021-12-14 21:43
I am experiencing the same issue on MacOS (11.2.1, Big Sur). I upgraded from cypress 9.1.0 to version 9.1.1 and this immediately started happening; no issues whatsoever beforehand while on version 9.1.0.

I've been on node version 17.0.1 & npm version 8.1.0 for a while.

Steps to reproduce:
Upgrade cypress from 9.1.0 to 9.1.1 via command `npm install --save-dev cypress@9.1.1`

--> Unable to launch cypress test runner or run in headless mode
--> Received the following message output in the terminal .../17.0.1/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

Workaround: 
As was mentioned, adding "nodeVersion": "bundled" in the cypress.json temporarily fixes the issue

**Comment by marcandre** [comment] 2021-12-16 17:31
Thanks for the work around ❤️

**Comment by emilyrohrbough** [comment] 2021-12-17 15:23
Additional information / debug logs can found in the duplicate issue of https://github.com/cypress-io/cypress/issues/19409.

**Comment by rdar-lab** [comment] 2021-12-19 13:13
The workaround works, but, you get this message:

Deprecation Warning: `nodeVersion` is currently set to `bundled` in the `cypress.json` configuration file. As of Cypress version `9.0.0` the default behavior of `nodeVersion` has changed to always use the version of Node used to start cypress via the cli. When `nodeVersion` is set to `bundled`, Cypress will use the version of Node bundled with electron. This can cause problems running certain plugins or integrations.
As the `nodeVersion` configuration option will be removed in a future release, it is recommended to remove the `nodeVersion` configuration option from `cypress.json`.

**Comment by emilyrohrbough** [comment] 2021-12-22 17:31
@ivandjorgon In your steps to reproduce,

> Upgrade cypress from 9.1.0 to 9.1.1 via command npm install --save-dev cypress@9.1.1

--> Unable to launch cypress test runner or run in headless mode
--> Received the following message output in the terminal .../17.0.1/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

Are you upgrading in an existing project ?

**Comment by ivandjorgon** [comment] 2021-12-22 17:57
@emilyrohrbough Yes, I upgraded in an existing project.

**Comment by emilyrohrbough** [comment] 2021-12-22 18:10
@ivandjorgon Can you provide minimum example of the project you tried to upgrade? Were any plugins in use? Support files?

**Comment by rdar-lab** [comment] 2021-12-23 11:43
@emilyrohrbough I got the same result when I created a project from scratch (no plugins, just the sample test from the quick starter guide)

**Comment by eagleflo** [comment] 2021-12-27 10:59
This issue is still there with Cypress 9.2.0 and Node 17.3. It is caused by #19094, which attempted to work around a previous problem caused by Node 17 upgrading to OpenSSL 3. It looks like Electron doesn't allow setting `--openssl-legacy-provider` in `NODE_OPTIONS` and will immediately bail out. (FWIW, I encounter this issue no matter which `--browser` I tell Cypress to use.)

The workaround of setting `nodeVersion: "bundled"` sidesteps the issue.

**Comment by akx** [comment] 2022-01-03 07:38
Same here – macOS 10.15, Node 17.3.0, Cypress 9.2.0. The `nodeVersion: "bundled"` workaround works.

**Comment by emilyrohrbough** [comment] 2022-01-03 16:14
We are working on resolving this issue. I am still having issues reproducing this consistently with Node 17.2 and 9.2.0. I had produced this locally at one point, however, I am no longer able to create the issue. To ensure we've handled all cases, it'd be best to determine the issue here on why this is inconsistent.

Can you provide the terminal(s) and the the list of ENVs set on your process when Cypress is launched?

**Comment by eagleflo** [comment] 2022-01-03 17:12
As this is a work application, I'm not at liberty to show the whole debug log with lots of identifying information. Most notably `NODE_OPTIONS` is unset when I try to run `cypress run`.

The last lines of my debug logs are:

```
  cypress:server:plugins launching using custom node version { resolvedNodePath: '/usr/bin/node', resolvedNodeVersion: '17.3.0' } +0ms
  cypress:server:plugins forking to run /home/aku/.cache/Cypress/9.2.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js +1ms
/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

I'll reiterate that this issue was introduced by #19094, which attempted to fix a problem explained in https://github.com/cypress-io/cypress/issues/18914#issuecomment-977123293. By commenting out line https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/index.js#L65, the `/usr/bin/node` invocation succeeds and the test suite starts to run as expected.

It looks like Node.js 17.3 doesn't support that option at all:

```
~ $ node -v
v17.3.0
~ $ NODE_OPTIONS=--openssl-legacy-provider node
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by emilyrohrbough** [comment] 2022-01-03 17:55
Thanks for the info. No disagreement this was introduced by #19094.

**Comment by eagleflo** [comment] 2022-01-03 18:01
Realized that Node.js as packaged by Arch Linux and Homebrew is actually still built against OpenSSL version 1 and improved the heuristic a little bit.

Here is another very similar issue: https://github.com/cloudflare/wrangler/pull/2116.

**Closed** 2022-01-06 20:42 UTC
Labels: stage: needs review
