### ISSUE TITLE
Cypress Test Runner > rerun failed tests

### ISSUE THREAD

**Issue by jakub-bao** [cypress-io/cypress#7179] opened 2020-04-29 17:06 UTC
I mostly use the test runner to run my tests. 
One feature I'd really love to have.
### Current behavior:
User story:

It takes me ~5min to run all my tests in test runner.
After that I have 3-4 failed specs.
I fix my app's code and want to check everything is OK.

I have two was to go:

- write down on a piece of paper which specs failed and re-run them manually (cumbersome)
- re-run all tests (slow, because I know 90% tests will pass but I only need to know the result of 3-4 failed tests from above)

### Desired behavior:

It would be really awesome to have a button in test runner `re-run failed tests only`

![image](https://user-images.githubusercontent.com/47790868/80624800-30290980-8a1a-11ea-9a8b-9a2a67fd7260.png)

### Versions
4.4.0, 4.5.0

**Comment by jennifer-shehane** [comment] 2020-04-30 10:17
Duplicate of #4886

**Closed by jennifer-shehane** 2020-04-30 10:17 UTC
