### ISSUE TITLE
Intercepted API gets aborted in 4 minutes even though the wait configured for it is for 8 minutes

### ISSUE THREAD

**Issue by BuckyB-test** [cypress-io/cypress#15213] opened 2021-02-25 05:47 UTC
### Current behavior
I am spying a POST api request via intercept command. I am waiting for 8 minutes to hear back from the api.
But the api request gets aborted or cancelled within 4 minutes.
```js
cy.intercept('POST', '/abc').as('generateReport')
cy.wait('@generateReport', {timeout:480000})
  .its('response.statusCode').should('eq', 200)
```

![image](https://user-images.githubusercontent.com/79623216/109109094-b5746c00-775a-11eb-861a-6b60d3fe3476.png)

![image](https://user-images.githubusercontent.com/79623216/109109187-ddfc6600-775a-11eb-9ebe-b05ed7e104ea.png)

### Desired behavior
The api call should wait for 8 minutes to get a response from server

### Versions

Latest version

**Comment by pmammadli** [comment] 2021-02-27 18:54
Have the same issue, here : #15260

**Comment by jennifer-shehane** [comment] 2021-02-28 19:30
Can you provide a reproducible example? We'll try to look at it but that always speeds up investigating.

**Comment by BuckyB-test** [comment] 2021-03-01 08:34
cant add the html here. Its sensitive data.

**Comment by BuckyB-test** [comment] 2021-03-01 08:36
> Can you provide a reproducible example? We'll try to look at it but that always speeds up investigating.

cant add the html here. Its sensitive data.

**Comment by BuckyB-test** [comment] 2021-04-05 06:57
@pmammadli did you find solution to your issue. @jennifer-shehane I am still facing the issue but cannot share source code. Let me know if you have any workaround.

**Comment by BuckyB-test** [comment] 2021-04-08 08:34
@jennifer-shehane the issue is resolved in 7.0.0. The API hits back with a response in cypress Test Runner but the code still fails at cy.wait(), saying the request never occurred.

**Comment by flotwig** [comment] 2021-04-08 18:30
@BuckyB-test to clarify, are you saying the issue is not present in 7.0.0?

**Comment by jennifer-shehane** [comment] 2021-05-05 19:43
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-05-05 19:43 UTC
Labels: pkg/net-stubbing
