### ISSUE TITLE
Cross origin error with same url

### ISSUE THREAD

**Issue by phlorie** [cypress-io/cypress#3521] opened 2019-02-19 03:45 UTC
I'm getting a cross origin error even though it's the same url.

```
CypressError: Cypress detected a cross origin error happened on page load:

  > Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.

Before the page load, you were bound to the origin policy:
  > http://localhost:3000

A cross origin error happens when your application navigates to a new superdomain which does not match the origin policy above.
```

It happens on submit of a form which then redirects to a page within the same domain.
The strange part is that it works fine when the form does a `POST`, I'm only getting this error on a `PUT`. The callback function doing the redirect (with a `window.location` because it's a separate library) is the same in both cases. The form behaves perfectly fine in Chrome, outside of Cypress.

### Versions

Cypress 3.1.5
MacOS 10.13.6

**Comment by jennifer-shehane** [comment] 2019-02-19 06:28
Duplicate of https://github.com/cypress-io/cypress/issues/2448

**Closed by jennifer-shehane** 2019-02-19 06:28 UTC
