### ISSUE TITLE
Chinese characters are not displayed

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#7526] opened 2020-05-29 08:08 UTC
Chinese characters are not displayed
![image](https://user-images.githubusercontent.com/31835543/83236009-64cce400-a1c5-11ea-8d03-c38364f4223d.png)

### Versions

cypress: 4.7.0
chrome: 83

**Comment by jennifer-shehane** [comment] 2020-05-29 11:55
Duplicate of #7507

**Closed by jennifer-shehane** 2020-05-29 11:55 UTC
