### ISSUE TITLE
Cypress instantly closes developer tools in chromium

### ISSUE THREAD

**Issue by Jazzepi** [cypress-io/cypress#5663] opened 2019-11-12 00:05 UTC
### Current behavior:
After opening the dev tools with ctrl-shift-i or F12 they close immediately.

Note the behavior does NOT occur using electron 73

### Desired behavior:
The dev tools should stay open :P

### Steps to reproduce: (app code and test code)
1. Run `cypress open`
2. launch with chromium 78
3. try to open dev tools at any point in the run

### Versions
Ubuntu 16.04
chromium 78
cypress 3.6.1

**Comment by jennifer-shehane** [comment] 2020-01-03 08:10
@Jazzepi I haven't been able to reproduce this. I frequently use these keyboard shortcuts myself in Cypress Chromium and they stay open during the duration of a run after opening.

I would make sure you don't have something in your application calling or overriding the keyboard shortcut at some point. Or something on your system.

Closing since this seems like an isolated case. No one else has reported.

![](http://g.recordit.co/w16wL0iOhe.gif)

**Closed by jennifer-shehane** 2020-01-03 08:10 UTC
