### ISSUE TITLE
Cannot read properties of undefined (reading 'undefined') in historyNavigationTriggeredHashChange

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#20539] opened 2022-03-09 01:01 UTC
### Current behavior

We have a Cypress test which tests UI navigation by clicking links, then using the browser's back button to pop the history stack. When running this test in Cypress 9.5.0, we get a stack trace from Cypress code:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'undefined')
    at historyNavigationTriggeredHashChange (cypress_runner.js:166581:101)
    at HTMLIFrameElement.<anonymous> (cypress_runner.js:173017:111)
    at HTMLIFrameElement.dispatch (cypress_runner.js:113217:27)
    at HTMLIFrameElement.elemData.handle (cypress_runner.js:113025:28)
```

### Desired behavior

No stack trace.

### Test code to reproduce

N/A

### Cypress Version

9.5.0

**Comment by davidmunechika** [comment] 2022-03-10 14:13
Can you include a reproducible example or example repo so we can reproduce your issue? Unfortunately we will have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue. Thanks!

**Closed by davidmunechika** 2022-03-10 14:13 UTC
Labels: stage: needs information

**Comment by DiegoMcDipster** [comment] 2022-03-11 09:52
I had this same issue yesterday and I now have it working.  For me it was because of one of two things: 

1. because of cookies being deleted at the start of each test.
I had: 
```
it('first test', () => { runs and loads cookies})
it('second test', () => { reads from cookies and does stuff})
```

I have it working now by merging the two tests, like so:
```
it('first + second test', () => { 
runs and loads cookies
reads from cookies and does stuff
})
```

Or... 2. Cypress is sometimes flakey when moving between pages, spread across tests.  A bit of background: I'm using NextJs and between the tests I'm moving from one NextJs page to another and back. Putting these transitions into one test solves the problem. (I had read something about it.  But I can no longer find it. Sorry.)

Anyway, I hope this helps you get closer to a solution! Happy hacking!

**Comment by kaiyoma** [comment] 2022-03-11 18:47
Yes, this is similar to what I encountered too. My test suite also moves across a lot of pages via several tests, and then pops the entire browser stack by using the browser's back button (in a separate test).

The test passes just fine in our CI, which is running Chrome 95 on Linux, but the test fails for me locally on my laptop, which is running Chrome 99 on Windows 10. Cypress 9.5.0 is being used in both cases. It's unclear if the OS version or Chrome version is causing a difference in behavior.

I suppose if I start running into this issue in our CI in the future, I'll try combining all the test logic into a single test and see if that helps. Thanks @DiegoMcDipster!

**Comment by kaiyoma** [comment] 2022-04-01 19:50
I'm seeing this a lot more in Chrome 100, both in Windows 10 and Linux. My test can actually repro this 100% of the time in Cypress 9.5.0. I think this should be reopened.

**Comment by kaiyoma** [comment] 2022-04-01 21:24
@DiegoMcDipster I implemented your suggestion (combining all tests into one) and it fixed the problem! Hopefully this helps others who stumble upon this. There's a workaround available but the root issue should still be fixed in Cypress.

**Comment by tstark2** [comment] 2022-04-01 21:32
I'm having this issue too, but it's not only in cypress 9.5.x, I'm seeing it all the way back to version 9.2. 9.1.1 works as expected. That said, I think this may be related to Chrome 100. In 9.5.3 I can run the same tests in FIrefox and they all pass. Hopefully that helps.

**Comment by pnjihia** [comment] 2022-04-04 20:22
Experiencing a similar issue with tests that involve page transitions. This was with both 9.5.3 and 9.5.2. The previous version (9.1.0) worked. The workaround was to suppress the exception, but this could hide other valid issues, so not a good solution. I hope we get a fix for this.

```
Cypress.on('uncaught:exception', (err, runnable) => {
  return false;
});
```

**Comment by mr-short** [comment] 2022-04-06 20:40
This is still happening in Cypress `9.5.3`. It is a result of trying to do `cy.url()` during a url/page change. 

After digging into the `cypress_runner.js` and `historyNavigationTriggeredHashChange` function, I found this to be the cause:
```js
  const urls = state('urls');
  const urlPosition = state('urlPosition');
  const currentUrl = _cypress_location__WEBPACK_IMPORTED_MODULE_0__[/* $Location */ "a"].create(urls[urlPosition]);
```

Both `urls` and `urlPosition` is `undefined`, which explains the error message and proves this a Cypress bug and not within the application.

**Comment by emilyrohrbough** [comment] 2022-04-06 20:48
@mr-short / @tstark2  / @pnjihia / @kaiyoma / @DiegoMcDipster 

This issue appears to be a duplicate of https://github.com/cypress-io/cypress/issues/19749.
