### ISSUE TITLE
Intercepted calls are queued before cy.wait

### ISSUE THREAD

**Issue by vojta-k** [cypress-io/cypress#14703] opened 2021-01-22 16:16 UTC
### Current behavior

After calling an intercept for method and path and assigning it an alias, all calls intercepted in this manner are stored in a queue form rather than stacked as I would expect. Meaning if 2 such calls are intercepted but the first one isn't interacted with via `.wait(<alias>)`, then interacting with the second call in this way will return information from the first one instead.

In larger, more complex app and testing code base, it is easy to unintentionally intercept a different, unwanted call prior to interacting with the desired one. So this behaviour is not ideal for that.

### Desired behavior

Intercepted call should be rather stacked or possible those that aren't being interacted with forgotten. Maybe ideally there should be an option parameter to define which of these approaches will be used.

### Test code to reproduce

```js
const baseUrl = 'https://swapi.dev';

const enterRequest = (path: string) => cy.get('[type="text"]').clear().type(path);

const sendRequest = () => cy.contains('button', 'request').click();

it('processes the intercepted requests in a queue', () => {
  cy.visit(baseUrl);

  cy.intercept({method: 'GET', path: '/api/people/*'}).as('getPeople')

  enterRequest('people/4/');
  sendRequest();
  // intercepted but not waiting for the getPeople here, let's assume I am not interested in this one

  enterRequest('people/6/');
  sendRequest();
  // same situation here

  enterRequest('people/10/');
  sendRequest()
  // this is a call I want to interact with
    .wait('@getPeople').then((req) => {
      const returnedUrl = String(req.response.body.url);
      expect(returnedUrl).to.contain('people/4/'); // this will pass
      expect(returnedUrl).to.contain('people/6/'); // this will fail
      expect(returnedUrl).to.contain('people/10/'); // this should be the one to pass but if fails
    });
});
```

### Versions

Cypress version 6.2.1
Browser Chrome 88

**Comment by jennifer-shehane** [comment] 2021-01-25 06:57
I believe this feature request might satisfy what you're asking for? https://github.com/cypress-io/cypress/issues/7663 If so, please add your comments and 👍 on that issue since we use interest in the feature to evaluate priority of development.

Couldn't you also be more specific with the intercept you want to listen for? Defining the path you want to listen for to be `/api/people/10`?

```js
it('processes the intercepted requests in a queue', () => {
  cy.visit(baseUrl);

  // path: people/10
  cy.intercept({method: 'GET', path: '/api/people/10'}).as('getPeople')

  //...
  // this is a call I want to interact with
    .wait('@getPeople').then((req) => {
      const returnedUrl = String(req.response.body.url);
      expect(returnedUrl).to.contain('people/10/'); // we only intercepted people/10 route
    });
});
```

**Comment by vojta-k** [comment] 2021-01-25 11:30
Hi! Thank you for your response. The https://github.com/cypress-io/cypress/issues/7663 would solve the issue partially - ideally we would like to not depend on the number of times the interception matched prior to the call that the code is waiting for (possibly if passing -1 as n would always select the last interception, then it would solve it entirely).

As for increasing path specificity, that can also work, but sometimes the full path might be difficult to obtain ("randomly" created new ID) or there might even be the same path called repeatedly but with different responses.

**Comment by flotwig** [comment] 2021-03-24 23:03
Hey @vojta-k, this is the expected behavior of `cy.wait()`. For tests to be deterministic, it's important to not arbitrarily condense requests based on timing.

> As for increasing path specificity, that can also work, but sometimes the full path might be difficult to obtain ("randomly" created new ID) or there might even be the same path called repeatedly but with different responses.

Does per-request aliasing solve this for you? You can dynamically set an alias from a request handler, so you could test for your randomly created ID/whatever: https://docs.cypress.io/api/commands/intercept#Aliasing-individual-requests

**Comment by flotwig** [comment] 2021-04-08 18:50
Closing since all appears to be working as expected. Please open an issue if you have a new bug report or feature request.

**Closed by flotwig** 2021-04-08 18:50 UTC
Labels: pkg/net-stubbing, stage: awaiting response

**Comment by mohamedatef2020** [comment] 2022-02-24 16:26
@flotwig @jennifer-shehane I believe this issue should be open again as it is a bug and doesn't work as expected according to cypress official documentation here: [Network Requests - waiting](https://docs.cypress.io/guides/guides/network-requests#Waiting)
I'm experiencing the same behavior as @vojta-k that `cy.wait()` always yields  the first sent request while according to the documentation it should yield the latest request.
Here is my use case where I want to verify the content of the displayed test after performing some actions while cypress always return the first default list.
```
cy.intercept("**list/).as("list")
getListRequest()
cy.wait(@list).then(assertDefaultData())
sortListAction()
cy.wait(@list).then(AssertSortedData()) // this is failing as it yields the first call
filterListAction()
cy.wait(@list).then(assertFilteredData()) // this is failing as it yields the first call again
```
