### ISSUE TITLE
to be able to avoid "page load when clicked a link to download file

### ISSUE THREAD

**Issue by kumarisonika** [cypress-io/cypress#19356] opened 2021-12-14 09:45 UTC
### What would you like?

In my Cypress test, I need to test a link which downloads a .txt, .xlsx and a .zip file when clicked, but when I use "click()" to click the hyperlink, it starts "page load" and expects for a new action to happen as a result of clicking a link.

Here is a screenshot of the issue described [https://i.stack.imgur.com/2j1Sy.png]
As an alternative to this I tried using the cy.downloadFile() to download the files directly through the link but the link I am using is dynamically generated hence I am unable to use that as well. Hence I want to store the newly generated link in the variable and then use it in cy.downloadFile() every time I run the test .

Requirement:
If there are any other ways to test a hyperlink or how to store the dynamically generated link every time the test is run?

### Why is this needed?

To be able to download a file with out running into page load

**Comment by marcandre** [comment] 2021-12-22 23:00
Duplicate of #14857

**Comment by mjhenkes** [comment] 2022-01-03 21:34
Closing as duplicate

**Closed by mjhenkes** 2022-01-03 21:34 UTC
