### ISSUE TITLE
Fixtures stored as aliases do not persist throughout the test spec

### ISSUE THREAD

**Issue by dRoskar** [cypress-io/cypress#6209] opened 2020-01-21 15:41 UTC
### Current behavior:
When saving a fixture as an alias (as demonstrated in the documentation) the fixture can no longer be retrieved in subsequent tests. More specifically:
 - If a fixture is saved in a 'before' clause, it can be retrieved in the first test after that but is gone in subsequent tests.

 - If a fixture is saved as an alias in an 'it' clause it's never accessible in subsequent tests.

 - When saving a fixture to an alias is the only command in a test, the cypress command log reports "No commands were issued in this test."

Here is a screenshot of the cypress command log, in which a fixture and a regular string are both stored as aliases in the 'before' clause, an then later recalled in subsequent 'it' clauses:
![chrome_ZGeYdxEtt7](https://user-images.githubusercontent.com/4742527/72813331-6f013380-3c63-11ea-832c-ef6f64d81221.png)

Notice that for saving a simple string as an alias, we get a display in the command log (greeting), but saving a fixture is treated as  if no command was executed.

### Desired behavior:

An aliased fixture should be accessible throughout the test spec within the same context or 'describe' clause
### Test code to reproduce
1. Prepare a simple fixture with content:
```
{
   "foo":"bar"
}
```
2. run code:
```
describe('test fixtures', function() {

    before(function() {
        cy.fixture('fixture_test').as('fixtest')
        cy.wrap('hello').as('greeting')
    })

    it('print fixture', function() {
        cy.log(JSON.stringify(this.fixtest))
        cy.log(this.greeting)
    })

    it('print fixture', function() {
        cy.log(JSON.stringify(this.fixtest))
        cy.log(this.greeting)
    })

    it('print fixture', function() {
        cy.log(JSON.stringify(this.fixtest))
        cy.log(this.greeting)
    })
})
```

### Versions

Cypress: 3.7.0
OS: Windows 10
Browser: Chrome 79

**Comment by jennifer-shehane** [comment] 2020-01-22 06:27
Aliases are not reusable when defined in a `before`. Closing as duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2020-01-22 06:27 UTC

**Comment by dRoskar** [comment] 2020-01-22 08:42
So okay, in the duplicate issue @brian-mann writes "between the tests Cypress removes all of the aliases". But this is clearly not true for the greeting alias, as demonstrated. And how could it be true? Isn't the whole point of aliases to be able to share data between tests?

**Comment by jennifer-shehane** [comment] 2020-01-22 12:12
@dRoskar This is simply how it works today. Many people dislike it and that is why there is an open issue, please comment there: https://github.com/cypress-io/cypress/issues/665
