### ISSUE TITLE
Cypress breaks on Deprecate Unload flag

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#29553] opened 2024-05-21 23:13 UTC
### Current behavior

With the chrome flag for deprecating the `unload` event, cypress breaks when going to a website that has a `unload` event and reloading the page.

### Test code to reproduce

cy.visit("https://www.google.com")
cy.reload()

### Cypress Version

13.10.0

### Node version

v18.17.0

### Operating System

Windows 10.0.19045

**Comment by jennifer-shehane** [comment] 2024-05-22 00:17
We have a PR open to address the depreciation and eventual removal of the unload event here: https://github.com/cypress-io/cypress/pull/29525

I would expect this to be in the next release a couple weeks from now.

**Comment by jennifer-shehane** [comment] 2024-05-22 00:17
Duplicate of https://github.com/cypress-io/cypress/issues/29241

**Closed as not planned by jennifer-shehane** 2024-05-22 00:17 UTC
