### ISSUE TITLE
Cypress 7.1.0 does not run component specs if you set a tsconfig baseUrl.  Error [TypeError]: validateOptions is not a function

### ISSUE THREAD

**Issue by anark** [cypress-io/cypress#16188] opened 2021-04-24 18:40 UTC
### Current behavior

Using a very basic webpack 5 configuration with typescript specs and a tsconfig.json that contains baseUrl value will lead to cypress not being able to run specs correctly.

When using webpack 5 and trying to run a component test via `cypress open-ct` and selecting a component spec you will get the following error
```
Error [TypeError]: validateOptions is not a function
```

If you remove the baseUrl value from tsconfig.json the component specs will run successfully.

I ran into different, but similar issues when trying using webpack 4 as well.  Can create another issue/repo if needed.

### Desired behavior

The component specs should run regardless of if you have a baseUrl set in your tsconfig.json file.

### Test code to reproduce

https://github.com/anark/cypress-tsconfig-baseurl-issue-example

### Versions

Cypress: 7.1.0
Webpack: 5.35.1
@cypress/react: 5.3.4

**Comment by agg23** [comment] 2021-05-06 14:38
Could you provide more information for why the `tsconfig` is written as in your example? In my mind, the "correct" way to write this config is:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "src",
    "paths": {
      "*": ["node_modules/*"]
    },
    "jsx": "react"
  }
}
```

which does work on your repro. I'm not sure what purpose an essentially empty `baseUrl` provides. If you must access code outside of `src`, can't you simply omit `baseUrl` entirely?

Regardless of my questions on the `tsconfig`, I'm not sure whether or not this is an issue with Cypress itself. Does this config generally work in other scenarios?

**Comment by anark** [comment] 2021-05-06 16:11
I believe it is quite common to specify a baseUrl of "." in order to allow for absolute imports based on the paths configured in your typescript project.  It is documented quite a bit in the typescript documentation https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url.

In our example if you remove the `baseUrl: "."` typescript will complain about trying to structure imports relative to the `src` directory
` import Test from 'components/test'`

If you keep `baseUrl: '.'` this is fine and supported.

I may be wrong here and there may be another way to do this but I do see `baseUrl: '.'` documented in their docs for this purpose.

**Comment by agg23** [comment] 2021-05-11 16:53
Fair enough.

The root cause of this issue is the rewriting of standard `node_module` imports:
```json
"paths": {
  "*": ["src/*", "node_modules/*"]
},
```

I'm not sure why `node_modules` being present would change anything at all, but once it's removed, the import in `webpack-dev-server` properly resolves. I believe moving to the following `paths` config will solve your issues:

```json
"paths": {
  "*": ["src/*"]
},
```

**Closed** 2021-05-11 17:43 UTC
Labels: component testing
