### ISSUE TITLE
Visiting a url with subdomains, supplying with basic auth crashes

### ISSUE THREAD

**Issue by geekyme** [cypress-io/cypress#3972] opened 2019-04-16 07:07 UTC
### Current behavior:

Got a blank page with console errors below

```
Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'com.sg' is a top-level domain.
    at $Cypress.setConfig

Uncaught TypeError: Cannot read property 'getSizeContainer' of undefined
    at App._handleScreenshots (cypress_runner.js:168193)
    at App.componentDidMount

The above error occurred in the <Iframes> component:
    in Iframes (created by App)
    in div (created by App)
    in div (created by App)
    in App (created 
```

<img width="1205" alt="Screen Shot 2019-04-16 at 3 06 19 PM" src="https://user-images.githubusercontent.com/977460/56188927-3c604580-6016-11e9-9a22-919f9a15728c.png">

### Desired behavior:

Cypress should correctly visit the page, enter the credentials and render the page. The last version that was working was 3.1.5

### Steps to reproduce: (app code and test code)

```
describe("test", () => {
  it("works", () => {
    cy.visit("https://basic-auth-app.geekyme.now.sh", {
      auth: {
        username: "john",
        password: "secret"
      }
    });
  });
});
```

### Versions

Cypress: 3.2.0

**Comment by flotwig** [comment] 2019-04-16 13:56
This is a known issue in 3.2.0 and will be fixed in the 3.3.0 release. Issue: #3717

For the time being, you can downgrade to 3.1.5 to avoid this bug.

Closing as duplicate of #3717.

**Closed by flotwig** 2019-04-16 13:56 UTC
