### ISSUE TITLE
cy.intercept() with Uncaught CypressError stops the test but doesn't mark test as failed

### ISSUE THREAD

**Issue by jimmy882** [cypress-io/cypress#14553] opened 2021-01-14 10:52 UTC
### Current behavior
When `cy.intercept()` is used to modify a real response
And a response callback passed to `req.reply()` throw an error while intercepting a response
Then the test is stopped, request is cancelled, error is in the console
But the test is marked as passed.

### Desired behavior
When there is Uncaught CypressError while intercepting
Then the test should fail.

Maybe it is not a good practice and we should prevent such errors, but it happened to me and I was wondering why is the test skipping the last steps until I noticed that there is an error 🤷‍♂️ 
I think when we have some errors in other places, then the test is failed so it's clear immediately

### Test code to reproduce
just for a demonstrating purpose
```js
describe('Test` with error in intercept', () => {
    it('should fail', () => {
        cy.intercept('GET', 'https://httpbin.org/get', req => {
            req.reply(res => {
                //do something nasty with response, but in this case just throw an error
                throw new Error('Intercept fails');
            });
        });
        cy.visit('https://resttesttest.com/');
        cy.get('#submitajax').click();
        cy.wait(5000);
        cy.get('#outputpre').should('be.visible');
    });
});
```
notice that the last `cy.get('#outputpre').should('be.visible');` is not executed, there is an error in console, but test has passed
![image](https://user-images.githubusercontent.com/53435536/104580975-3ae60600-565e-11eb-8dd2-5592aad6a6f9.png)

### Versions

Cypress 6.2.1

**Comment by jennifer-shehane** [comment] 2021-01-20 05:15
@jimmy882 I'm not able to reproduce the behavior you've described with the code provided.

<img width="1111" alt="Screen Shot 2021-01-20 at 11 44 50 AM" src="https://user-images.githubusercontent.com/1271364/105130187-f0103680-5b14-11eb-95d1-777a2061c94a.png">


Do you have the code below anywhere in your spec files? Because this will prevent all uncaught error from being thrown - showing as passed as you've described. You'll want to remove this code, or make the handler more specific on when not to fail. 

```js
Cypress.on('uncaught:exception', () => {
  return false
})
```

**Comment by jimmy882** [comment] 2021-01-20 13:07
oh, sorry, my bad. We had this
```
Cypress.on('uncaught:exception', () => {
  return false
})
```
at some unexpected place
When I removed it, all works fine.

**Comment by bahmutov** [comment] 2021-01-20 15:41
Super @jimmy882 if it works as expected, failing the test, could you close this issue?

**Closed** 2021-01-20 16:45 UTC
Labels: pkg/net-stubbing, stage: awaiting response
