### ISSUE TITLE
Git keeps asking me to install cypress

### ISSUE THREAD

**Issue by sakidx** [cypress-io/cypress#21336] opened 2022-05-04 16:07 UTC
### Current behavior

I was trying to run some headless tests via NPM Command.
But I keep getting error. It asks me to install cypress even thought it is already installed in the correct directory.

 npm-run-all pretest chrome-local posttest --continue-on-error

> test@1.0.0 pretest
> npm run clean:reports-w

> test@1.0.0 clean:reports-w
> rmdir /S /Q cypress\reports && mkdir cypress\reports && mkdir cypress\reports\mochareports

> test@1.0.0 chrome-local
> cypress run --config-file local-config.json --headless --browser chrome

No version of Cypress is installed in: C:\Users\sbari\AppData\Local\Cypress\Cache\9.6.0\Cypress

Please reinstall Cypress by running: cypress install

----------

Cannot read binary version from: C:\Users\sbari\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\package.json

----------

Platform: win32-x64 (10.0.19044)
Cypress Version: 9.6.0

> test@1.0.0 posttest
> npm run combine-reports && npm run generate-report

> test@1.0.0 combine-reports
> mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/mochareports/report.json

ERROR: Failed to merge reports

Error: Pattern cypress/reports/mocha/*.json matched no report files
    at C:\git\mnp-web-lr7\src\MyNavyPortal\test\automation\e2e\node_modules\mochawesome-merge\lib\index.js:14:11
    at Array.map (<anonymous>)
    at C:\git\mnp-web-lr7\src\MyNavyPortal\test\automation\e2e\node_modules\mochawesome-merge\lib\utils.js:3:46
    at merge (C:\git\mnp-web-lr7\src\MyNavyPortal\test\automation\e2e\node_modules\mochawesome-merge\lib\index.js:82:17)
    at Object.<anonymous> (C:\git\mnp-web-lr7\src\MyNavyPortal\test\automation\e2e\node_modules\mochawesome-merge\bin\mochawesome-merge.js:32:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
ERROR: "posttest" exited with 1.

### Desired behavior

It should have ran the tests

### Test code to reproduce

npm run test-chrome-local

### Cypress Version

npm -v 8.3.1

**Comment by mjhenkes** [comment] 2022-05-04 22:05
Is cypress installed at `C:\Users\sbari\AppData\Local\Cypress\Cache\9.6.0\Cypress`?

If not try running `cypress install`.

**Comment by sakidx** [comment] 2022-05-05 13:05
> Is cypress installed at `C:\Users\sbari\AppData\Local\Cypress\Cache\9.6.0\Cypress`?
> 
> If not try running `cypress install`.

It is already installed, and I tried installing it again.

**Comment by mjhenkes** [comment] 2022-05-05 14:52
To narrow down the problem what happens if you just run `cypress run --config-file local-config.json --headless --browser chrome` without the other custom commands?

Also if you could provide a project and steps to recreate, that would be very helpful to debug the problem.

**Comment by mjhenkes** [comment] 2022-05-12 20:09
@sakidx, I'm going to go ahead and close this issue. I've been unable to reproduce it myself. If you're able to provide steps to reproduce in the future we'd be happy to take another look.

**Closed by mjhenkes** 2022-05-12 20:09 UTC
Labels: stage: awaiting response
