### ISSUE TITLE
Cypress Crashes

### ISSUE THREAD

**Issue by Palman6** [cypress-io/cypress#22579] opened 2022-06-29 07:36 UTC
### Current behavior

After upgrading to cypress 10 some of my tests run fine and I have a quite huge test case when I run those tests it hangs in the middle and I have to forcefully close. I have provided some errors I got in the console. 

![Screenshot from 2022-06-29 13-17-00](https://user-images.githubusercontent.com/57383559/176377513-dbc38073-d74e-42c9-b0fb-f711213f988b.png)
 
![Screenshot from 2022-06-29 13-13-39](https://user-images.githubusercontent.com/57383559/176377584-1f8f3bb0-af5a-4578-9791-e5539c9d4ef9.png)

### Desired behavior

In the previous version in cypress 9 and below all same code works fine.

### Test code to reproduce

It hangs on the same step. I have to add an address and have to do a footprint check.

 last code that makes hang:
 cy.btnName('checkFootprint').wait(2000); 

due to loading time, I just gave static waits but after this code, it hangs the cypress and gets crashed.

### Cypress Version

10.3.0

**Comment by lmiller1990** [comment] 2022-06-29 23:25
So this fails locally and CI? Or both? 

What do `cy.btnName('checkFootprint').wait(2000)` do? Eg - what is supposed to happen at that point?

You could try running `DEBUG=cypress:* npx cypress run ...`. The `DEBUG` variable will split out lots more logs, which you could share here to help with debugging. Thanks!

**Comment by lmiller1990** [comment] 2022-07-11 02:57
What does `cy.dataCy` do?

It's hard to say without having a project, or at least, your source code. For now I don't see a bug, so I'll close this. If you can share your code, or at least, `dataCy` and the relating elements, I can make some suggestions.

**Closed by lmiller1990** 2022-07-11 02:57 UTC
Labels: stage: awaiting response

**Comment by Palman6** [comment] 2022-07-11 07:39
@lmiller1990 
Thank you for response.

cy.dataCy is a custom command 
Cypress.Commands.add('dataCy', (value) => {
  cy.get(`[data-cy='${value}']`);
});

My failing code:
productConfiguration(variant: SiteDetails): void {
    cy.get('[data-cy="addressDetail"]').then(elements => {
      while (Cypress.$(elements).length > 0) {
        cy.dataCy('addressDetail').find('span').first().contains('Not Configured').parent().parent().first()
          .find('i.pi-cog').click().wait(1000);
        if (variant.quote_type !== 'Renewal') {
          variant.variant.band ? configureProduct(variant.variant.band, false) : cy.inputData('fiberCount','4');
        }
        variant.variant.year && configureProduct(variant.variant.year, true);
        variant.variant.sla && cy.dataCy('sla').find('label').contains(variant.variant.sla).click().wait(500);
        addOnsConfiguration(variant);
        variant.variant.both && cy.dataCy('availBothService').find('label').contains('Yes').click();
        variant.variant.nni && cy.dataCy('nniAddress').last().find('mat-select').type(variant.variant.nni);
        variant.variant.note && cy.dataCy('productNote').find('textarea').clear().type(variant.variant.note);
        variant.variant.lineId && cy.dataCy('customerLineId').find('input').type(variant.variant.lineId);
        cy.dataCy('Complete').click().wait(4000);
        Cypress.$(elements).length--;
      }
    });
  }

Resolved code: 
 productConfiguration(variant: SiteDetails): void {
    cy.get('[data-cy="addressDetail"]').then($elements => {
      while ($elements.length > 0) {

       //same code from above

        $elements.length--;
      }
    });
  }
 
Just changed Cypress.$(element).length to $element.length.

What I found is the issue is from while loop part.
In the while loop when I use Cypress.$(element).length its getting into infinite loop but when I use $elements.length its working as expected. I am not able configure the actual issue.

Thank you.

**Comment by lmiller1990** [comment] 2022-07-11 23:13
Seems the problem is you have multiple elements. I think you should write a more specific selector, eg:

```js
 cy.dataCy('addressDetail').contains('Not Configured').get('.pi-cog').click()
```

Your logic is quite complex. If your DOM changes, it might break. Ideally, I'd add a data selector somewhere closer to where you want to be, like on the `<i>` element that contains more info:

```js
cy.get('[data-cy="addressDetail--non-configured]'`)
```

The more simple you can make your assertion and the less you need to interactive with DOM elements with `parent`, `find` etc, the easier life will be!

**Comment by Palman6** [comment] 2022-07-12 06:24
Thanks for the response. I modified the code as you suggested but still the same. But it's fine it's working when I use $element.length.
