### ISSUE TITLE
cypress caches the host file in the config itself

### ISSUE THREAD

**Issue by LaurynasCiapas** [cypress-io/cypress#24375] opened 2022-10-25 05:46 UTC
### Current behavior

When in the config file you add the object - "hosts" provide desired IP address and start the cypress it doesn't open the expected URL. You must run command cypress clear cache and it then works as expected.

Steps to reproduce:
1. launch cypress and run some tests with the basic your url
2. turn off cypress
3. change config (add hosts object, provide DNS, desired ip)
4. launch again cypress and run some tests.

Current result:
Tests runs in your basic URL.

Actual result:
Tests runs in your desired ip

### Desired behavior

After config save it should work properly without running command "cypress clear cache"

### Test code to reproduce

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    baseUrl:"https://mydns.com",
    viewportHeight: 1080,
    viewportWidth: 1920,
    setupNodeEvents(on, config) {
      
    },
    env: {
        http_proxy: "http://mycompany.proxy.com"
    },
  },
  hosts:{ 
      "mydns.com": "myDesiredIpAddress"
    } 
});
```

### Cypress Version

10.10.0

### Node version

v16.17.1

### Operating System

macOs 12.6

**Comment by amehta265** [comment] 2022-11-01 19:59
@LaurynasCiapas Thank you for opening an issue.
After further investigation, I am unable to replicate your issue. This is what my config file looks like:
```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  fixturesFolder: false,
  e2e: {
    setupNodeEvents(on, config) {},
    supportFile: false,
    baseUrl: 'https://localhost:3000',
  },
})

```
I followed the steps you listed in the issue.
1. I launched cypress and ran some tests with the basic config (as shown above) without a host object just loading the localhost.
![Image](https://user-images.githubusercontent.com/65267668/199325586-3a4359de-c4e2-4c31-ae56-14187fdb42e4.png)
2. I turned off cypress
3. I changed the `cypress.config` file as shown below:
```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  fixturesFolder: false,
  hosts: {
    'my-secure-site': '127.0.0.1',
  },
  e2e: {
    setupNodeEvents(on, config) {},
    supportFile: false,
    baseUrl: 'https://my-secure-site:3000',
  },
})
```
4. I launched cypress again and ran the tests:
![Image](https://user-images.githubusercontent.com/65267668/199326022-cff02bb2-bae4-4745-89c8-b5c79f7fae0a.png)

In my case I did not have to run the `cypress clear cache`.
I may be missing something here but if you can provide more context or a reproducible example in the form of a [Short, Self Contained, Correct, Example](http://sscce.org/) repository, that would be very helpful. 
In regards to the `http-proxy` setting, it would be more useful if you can provide more information about the proxy you are using so that I can better replicate the test. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

**Comment by amehta265** [comment] 2022-11-08 14:13
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by amehta265** 2022-11-08 14:13 UTC
