### ISSUE TITLE
Passing tests marked with red x, looks like a failure

### ISSUE THREAD

**Issue by dotwork** [cypress-io/cypress#15001] opened 2021-02-09 16:32 UTC
Hello,

Recently, perhaps after upgrading, some tests have started to look like failures when they are actually passing. 
I have attached a screenshot of how it looks in the GUI. I assume it is the aborted requests that are causing it to fail (though they have no impact on the function of the page or the tests written. Is there a way Cypress can ignore these?

![cypress-test-failure](https://user-images.githubusercontent.com/10385611/107394904-f49b8f80-6ac1-11eb-9300-5f990a3cd5ec.png)

**Comment by bahmutov** [comment] 2021-02-09 16:57
Yeah, we have noticed this, thanks for reporting, closing as a duplicate of #14978

**Closed by bahmutov** 2021-02-09 16:57 UTC
