### ISSUE TITLE
when request different subdomain, the request can not be caught by  the cypress

### ISSUE THREAD

**Issue by GongJS** [cypress-io/cypress#7472] opened 2020-05-25 08:35 UTC
when i run the test, i find the dashboard can't catch the last request, this is my code:
```js
const getIframeDocument = () => {
    return cy
        .get('iframe[id="login-iframe"]')
        .its('0.contentDocument').should('exist')
}

const getIframeBody = () => {
    // get the document
    return getIframeDocument()
        // automatically retries until body is loaded
        .its('body').should('not.be.undefined')
        // wraps "body" DOM element to allow
        // chaining more Cypress commands, like ".find(...)"
        .then(cy.wrap)
}

const username = Cypress.env('username')
const password = Cypress.env('password')
context('Misc', () => {
    beforeEach('test', () => {
        cy.visit('.........GOUT=&loginChannel=PC')
    })
    it('test', () => {
        getIframeBody().find('.domain-body-input-control-username').should('exist').type('gong.gjs')
        getIframeBody().find('.domain-body-input-control-userpass').should('exist').type(password)
        getIframeBody().find('.domain-body-submit-control-submit').should('exist').click()
        cy.wait(5000)
        cy.visit('https://kbservcenter.alipay.com/sale/index.htm#/shop?_k=efixxr')
        cy.get('.anticon-qrcode').should('exist')
    })
})
```
![06D50A84-9CA5-4FAB-8F58-D38BCC1D48CD](https://user-images.githubusercontent.com/25744301/81935008-81441a80-9622-11ea-88c9-336087d15ea2.png)

because this request url is 'https://kbsales.alipay.com/shop/koubei/commonShopSearch.json',  it is not same with my web app url 'https://kbservcenter.alipay.com/' and different from other request, so when made this request, the domain is seted to  'alipay.net' in the proxy.html ,  as you can see:

![image](https://user-images.githubusercontent.com/25744301/82784861-fcfc5d80-9e93-11ea-9c36-b181b28fe54f.png)

![image](https://user-images.githubusercontent.com/25744301/82744338-b3cfdf00-9da9-11ea-9c31-83b9a28ed5e1.png)

![image](https://user-images.githubusercontent.com/25744301/82784991-4ba9f780-9e94-11ea-89e3-1888728e57a8.png)

in my web app the request is succeed, but the cypress can't catch this request, so i can't stub this request....

### Versions
4.5.0

**Comment by flotwig** [comment] 2022-02-03 21:16
Hi @GongJS, I would recommend trying [`cy.intercept()`](https://on.cypress.io/intercept) for this task, it can stub anything. The issue is that the old `cy.route()` API does not support requests issued by iframes.

Closing since the `cy.intercept()` API fixes this.

**Closed by flotwig** 2022-02-03 21:16 UTC
