### ISSUE TITLE
Terminate / Skip / Stop all tests from all spec files if any one test fails

### ISSUE THREAD

**Issue by rajneeshm49** [cypress-io/cypress#7857] opened 2020-06-30 03:36 UTC
Iam trying to skip all other tests from all spec files if one test fails and found a working solution over here https://github.com/cypress-io/cypress/issues/518#issuecomment-552382781. However this looks to be working only if test fails in`it` assertions. How can we skip the tests if somethings fails in beforeach()

For eg: 

    `before(() => {

          cy.get('[data-name="email-input"]').type(email);
          cy.get('[data-name="password-input"]').type(email);
          cy.get('[data-name="account-save-btn"]').click();
    });`
And if something goes wrong (for eg: CypressError: Timed out retrying: Expected to find element: '[data-name="email-input"]', but never found it.) in above code then stop/ skip all tests in all spec files.

**Comment by jennifer-shehane** [comment] 2020-06-30 08:29
I've added a comment with additional workaround for aborting on failure. I think the other workarounds (not `.skip`) would work in your situation. https://github.com/cypress-io/cypress/issues/518#issuecomment-651633484

Also I would suggest asking in that thread. 

Closing as duplicate of #518

**Closed by jennifer-shehane** 2020-06-30 08:29 UTC
