### ISSUE TITLE
Cy.get('a[href="something"]' returns Syntax error, unrecognized expression

### ISSUE THREAD

**Issue by rkefi** [cypress-io/cypress#14603] opened 2021-01-17 05:16 UTC
### Current behavior

Command :

```js
cy.get('a[href="/app/test-slide/195673893657013642/doc/misc"]')
```

Test fails with this error :

```
Syntax error, unrecognized expression: 'a[href="/app/test-slide/195673893657013642/doc/misc"]'
```

Element in the DOM :

```html
<a class="slide-admin-live-MuiChip-root slide-admin-live-makeStyles-root-736 slide-admin-live-MuiChip-clickable" role="button" tabindex="0" href="/app/test-slide/195673893657013642/doc/misc">
  <span class="slide-admin-live-MuiChip-label">Slides live</span>
</a>
```

### Desired behavior
According to the documentation the expression should work 
https://docs.cypress.io/api/commands/get.html#Selector
```js
cy.get('a[href*="questions"]').click() // Tried also the contains as in the example but didn't help
```

### Test code to reproduce
```js
cy.get('a[href="/app/test-slide/195673893657013642/doc/misc"]')
```

Test fails with this error :
```
Syntax error, unrecognized expression: 'a[href="/app/test-slide/195673893657013642/doc/misc"]'
```
### Versions
Cypress : Latest version

**Comment by jennifer-shehane** [comment] 2021-01-20 09:22
I'm not getting this error with the test code you provided. 

- Are you sure that you don't have any `Cypress.Command.overwrite` defined for the `get` command? 
- Do you have any other code not included that's required to reproduce. If you can provide that I can look further into it. 

`index.html`

```html
<html>
  <body>
    <a href="/app/test-slide/195673893657013642/doc/misc">
      <span>Slides live</span>
    </a>
  </body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('a[href="/app/test-slide/195673893657013642/doc/misc"]')
})
```

<img width="711" alt="Screen Shot 2021-01-20 at 3 50 49 PM" src="https://user-images.githubusercontent.com/1271364/105153845-4aba8a00-5b37-11eb-80ff-f07309c23b5a.png">

**Comment by jennifer-shehane** [comment] 2021-02-27 00:18
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-27 00:18 UTC
Labels: stage: needs information
