### ISSUE TITLE
Whoops, there is no test

### ISSUE THREAD

**Issue by PavelRomashuk** [cypress-io/cypress#5050] opened 2019-08-28 16:26 UTC
I`m using kendo grid. 

Unxpected message - Whoops, there is no test to run. appear when I try to execute click on kendo grid row.

Current behavior: should nevigate to target page

Desired behavior: Whoops, there is no test to run. appear. Address bar shows www.localhost/__/ trailing underscores.

Steps to reproduce: 
part of my code 

    it('Search CN000000000123',()=>{
        cy.get('#find').type('CN000000000123');
        cy.get('#grid').invoke('getKendoGrid').invoke("select", 'tr:eq(2)');
    });

OR 

    it('Search CN000000000123',()=>{
        cy.get('#find').type('CN000000000123');
        cy.contains('CN000000000123', { timeout: 25000}).click();
    })

It doesn`t matter which code I use, each of them gives the behaviour described in Current behaviour.
The strange thing is that if I even click manually on the grid row it also gives the same error.

Please help me, figure out what I`m doing wrong?
If any other information needed please let me know.
Thanks.

**Comment by PavelRomashuk** [comment] 2019-08-28 16:37
I`m using kendo grid. 

Unxpected message - Whoops, there is no test to run. appear when I try to execute click on kendo grid row.

Current behavior: should nevigate to target page

Desired behavior: Whoops, there is no test to run. appear. Address bar shows www.localhost/__/ trailing underscores.

Steps to reproduce: 
part of my code 
    it('Search CN000000000123',()=>{
        cy.get('#find').type('CN000000000123');
        cy.get('#grid').invoke('getKendoGrid').invoke("select", 'tr:eq(2)');
        //cy.contains('CN000000000123', { timeout: 25000}).click();
    });

OR 

    it('Search CN000000000123',()=>{
        cy.get('#find').type('CN000000000123');
        cy.contains('CN000000000123', { timeout: 25000}).click();
    })

It doesn`t matter which code I use, each of them gives the behaviour described in Current behaviour.
The strange thing is that if I even click manually on the grid row it also gives the same error.

Please help me, figure out what I`m doing wrong?
If any other information needed please let me know.
Thanks.

**Comment by mpahuja** [comment] 2019-08-28 23:36
Can you please provide more details, project structure, test files and other files locations? Possibly put it in a public repository and share it with the issue?
Possible problems:
1) No baseUrl defined
2) No visit command provided
3) Incorrect test file location

**Comment by PavelRomashuk** [comment] 2019-08-30 05:39
![project_structure](https://user-images.githubusercontent.com/14273766/63995530-821f3580-cb01-11e9-8ced-8cdd8a629ecd.jpg)
The code that makes issue is underlined.

LoadUrl method if needed.

function LoadUrl(url: string, urlPart: string) {
    cy.visit(url);
    cy.url().should('include', urlPart) // make sure page loaded
}


export {LoadUrl};

**Comment by mpahuja** [comment] 2019-08-30 07:33
if you comment out just that line `.invoke(getKendoGrid)` does it work?

**Comment by PavelRomashuk** [comment] 2019-08-30 15:18
Why it should?

**Comment by mpahuja** [comment] 2019-08-30 15:23
to isolate the problem

**Comment by PavelRomashuk** [comment] 2019-08-30 15:25
You want me to run code like this

cy.get('#grid').invoke("select", 'tr:eq(2)');

?

**Comment by mpahuja** [comment] 2019-08-30 15:28
no comment / remove entire line

**Comment by PavelRomashuk** [comment] 2019-08-30 15:35
If I remove the line I wouldn't get a click on the row, but a click is necessary to navigate further.

**Comment by mpahuja** [comment] 2019-08-30 15:40
Yes I understand that you want to add a test to verify that functionality but without isolating for the error `Whoops, there is no test to run.` to the specific plugin its difficult to fix it

**Comment by PavelRomashuk** [comment] 2019-08-30 16:30
If I entirely remove/comment out this line, everything works just fine, with the line it doesn't

**Comment by PavelRomashuk** [comment] 2019-09-01 18:29
Does anybody else have some ideas, why it doesn't work?

**Comment by bahmutov** [comment] 2019-09-01 18:39
Open devtools and see if there are any error messages shown there

**Comment by PavelRomashuk** [comment] 2019-09-02 08:52
before click on a row

![beforeClick](https://user-images.githubusercontent.com/14273766/64102159-037ffd80-cd78-11e9-8d35-b29f699c384f.png)

after click

![afterClick](https://user-images.githubusercontent.com/14273766/64102170-0bd83880-cd78-11e9-8895-d2bba4e069fe.png)


`{
  "projectId": "4firij",
  "chromeWebSecurity": false,
  "ignoreTestFiles":"**/examples/*.js",
  "blacklistHosts" : [
    "www.googletagmanager.com",
    "cdn.sstatic.net",
    "www.google-analytics.com",
    "fonts.gstatic.com",
    "fonts.googleapis.com"
  ]
}`

**Comment by PavelRomashuk** [comment] 2019-09-02 15:07
I tried to put the direct URL where I want navigate to. It navigates whithout any issues. So looks like the problem directly in click action. 

Not sure what to do next with it.

**Comment by PavelRomashuk** [comment] 2019-09-03 07:10
Is there a way to log what cypress doesn't like?

**Comment by bahmutov** [comment] 2019-09-03 13:42
So something is going terribly wrong there. Try debugging the code following https://on.cypress.io/debugging or give us a reproducible example we can run ourselves to find the problem @PavelRomashuk

**Comment by PavelRomashuk** [comment] 2019-09-17 13:50
I`ve found that we open an edit page with the following code

`window.open(url, target, windowOptions);`

with the following parameters 

`
url - /Item/Edit/29146
target - _parent
windowOptions - undefined
`

Are there any possible issues?

**Comment by jennifer-shehane** [comment] 2019-12-13 11:29
Closing this as a duplicate of https://github.com/cypress-io/cypress/issues/3121

If you have control over the code, you can rewrite `target="_parent"` to `target="_self"` as explained here: https://github.com/cypress-io/cypress/issues/3121#issuecomment-453634949

**Closed by jennifer-shehane** 2019-12-13 11:29 UTC

**Comment by amitdhanke** [comment] 2020-02-20 07:27
> Closing this as a duplicate of #3121
> 
> If you have control over the code, you can rewrite `target="_parent"` to `target="_self"` as explained here: [#3121 (comment)](https://github.com/cypress-io/cypress/issues/3121#issuecomment-453634949)

without proper solution provided then why your closing the issue all issues are not same

**Comment by jennifer-shehane** [comment] 2020-02-20 09:00
@amitdhanke The original issue was caused by having `target="parent"` mentioned here: https://github.com/cypress-io/cypress/issues/5050#issuecomment-532229673, which is the exact issue linked to as duplicate. We consolidate issues that are the same to focus discussion and find a proper solution in one place. 

Please comment in https://github.com/cypress-io/cypress/issues/3121 if you are experiencing this issue.
