### ISSUE TITLE
Feature: Stop Cypress when there are too many failed tests

### ISSUE THREAD

**Issue by dcastil** [cypress-io/cypress#1599] opened 2018-04-16 15:19 UTC
### Current behavior: 
Sometimes a feature I work on breaks a lot of tests in the CI build. I have to wait until all tests are finished until I can figure out what happened, which can take very long due to long timeouts.

### Desired behavior:
Being able to set a variable in cypress.json to stop the Cypress test execution and fast-forward to uploading the data to the Cypress dashboard when a specific number of test failures is exceeded.

For example in cypress.json:

```json
{
  "maxFailedTests": 10
}
```

**Comment by dcastil** [comment] 2018-04-18 08:03
Here is an example of what I mean.
<img width="526" alt="screen shot 2018-04-18 at 09 58 29" src="https://user-images.githubusercontent.com/31006608/38918911-5d08b316-42ef-11e8-959e-1ef484f7f1d5.png">
I know that it would be better to put this just into one `it()` block, but then it would get hard to figure out at which point the test failed.

**Comment by brian-mann** [comment] 2018-04-18 14:35
Yah, you are sort of "going against the grain" here where you are splitting up things across multiple tests but it's really just a single test, which is an anti pattern.

https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests

I can understand what you're doing - and regardless I think the `maxFailedTests` is a good option, but if you were say writing a single test or using a `beforeEach` you naturally would not have this problem.

You say that it's hard to tell at which point the test failed, but I'm not seeing why. Cypress records screenshots and videos, and you can use `cy.log()` in your tests to add context to where the test is. With these it should be immediately obvious where something did or didn't fail. We also have the Dashboard server which records everything making this process even easier.

Can you go into detail as to your process or why you're finding this challenging?

**Comment by dcastil** [comment] 2018-04-18 15:00
Yes, you're right. I should try `cy.log()` instead, I didn't consider that.

My test in the screenshot is going through a registration process with several form pages. The test often fails because newly added form fields are not yet handled in Cypress and the website doesn't let Cypress press the "next"-button. In the error message Cypress provides information about the button element, but not the context of the element (e.g. the URL or previous commands), so I can't easily figure out which of the many "next"-buttons I click in the registration process caused the error.

I know that I can look it up in the screenshots within the dashboard, but I would like to keep the dashboard for more detailed investigation and make such basic things like checking _where_ the test failed visible within the CI logs. And because Cypress only logs whether an `it()` block passed, I separated the test into several such blocks.

**Comment by dcastil** [comment] 2018-04-18 15:12
@brian-mann I just tested it but Cypress doesn't log `cy.log()`s to the console. Is there a way to print a status from within a test? So I have something like this in the console:

```
logs in 'proposal-submitted-2' without UI
navigates through recap
selects joint account
…
✓ registration joint account happy path (26867ms)
```

**Comment by beaugunderson** [comment] 2018-10-25 22:36
@dcastil the docs for `cy.task` include an example for logging to the console 👍

**Comment by beaugunderson** [comment] 2018-10-25 22:41
and just to link the issues; this is very similar to the feature requested in #518

**Comment by jennifer-shehane** [comment] 2020-06-30 06:55
Closing as duplicate of https://github.com/cypress-io/cypress/issues/518

**Closed by jennifer-shehane** 2020-06-30 06:55 UTC
Labels: stage: proposal 💡, type: feature
