### ISSUE TITLE
disabling modifyObstructiveCode breaking cypress

### ISSUE THREAD

**Issue by marcsanchez1** [cypress-io/cypress#5158] opened 2019-09-17 20:46 UTC
### Current behavior: 
When I turn off 'modifyObstructiveCode', I'm getting the following message, "Whoops, there is no test to run." When I turn it back on, it'll work fine. I have a scenario where my test is opening up to its own window and from what I've read, this is because of 'Window.top' and the only way to get around it is to disable modifyObstructiveCode since we can't remove 'window.top'. Are there any other solutions?

![Screen Shot 2019-09-17 at 4 02 01 PM](https://user-images.githubusercontent.com/13281106/65078079-44783480-d96a-11e9-9d7e-1cd38c6df5db.png)

### Desired behavior: 
I'd like for the test to not open in a new non-test runner window.

I want my webpage to open up in test runner as it should.

### Versions
Version 3.3.2 (3.3.2)

Running on Electron or Chrome on a Mac

**Comment by jennifer-shehane** [comment] 2019-09-19 20:44
`modifyObstructiveCode` is removing code that your application is using to prevent framejacking. Since Cypress runs in an iframe, we have to remove that code. Likely your website has some framejacking code that is making it not work in Cypress, so the `modifyObstructiveCode` is necessary. 

>I have a scenario where my test is opening up to its own window and from what I've read, this is because of 'Window.top' and the only way to get around it is to disable modifyObstructiveCode since we can't remove 'window.top'.

I don't know what you're referring to here or what your actual issue is exactly.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-09-19 20:44 UTC
