### ISSUE TITLE
Cypress route2 does not work between tests

### ISSUE THREAD

**Issue by Cesaario** [cypress-io/cypress#8686] opened 2020-09-28 19:54 UTC
I've read some issues that reported this same bug that I'm experiencing, but in some of them it was said that it is expected, and the routes should indeed be reset between tests. The recent pull request #4176 was supposed to close the issue #1183 , but the issue remains.

### Current behavior
Routes are being reset between tests.
Test 1:
![image](https://user-images.githubusercontent.com/17167472/94478354-8c4eb000-01a9-11eb-833d-2f15e5255e71.png)

Test 2:
![image](https://user-images.githubusercontent.com/17167472/94478411-9e305300-01a9-11eb-9edd-c4bb4cc63201.png)

Result:
![image](https://user-images.githubusercontent.com/17167472/94479010-82797c80-01aa-11eb-9de2-ecbe846a7827.png)

### Desired behavior
The route for the endpoint "/todos/1" should not be reset between Test 1 and Test 2

### Test code to reproduce
```
/// <reference types="cypress"/>

describe('Test', () => {
  before(() => {
    cy.visit('https://jsonplaceholder.typicode.com/')
    cy.route2('**/todos/1', 'stub').as('Test');
  })
  it('Test 1', () => {
    cy.get('#run-button').click();

    cy.wait('@Test').then(req => {
      const responseBody = req.response.body;
      expect(responseBody).to.be.equal('stub');
    })
  })
  it('Test 2', () => {
    cy.get('#run-button').click();
    
    cy.wait('@Test').then(req => {
      const responseBody = req.response.body;
      expect(responseBody).to.be.equal('stub');
    })
  })
})
```

### Versions
Windows 10
Chrome 85
Cypress 5.2.0*

*Cypress 5.2.0 has a bug that we can't match routes with external url's. So I used the branch from PR #8662

**Comment by jennifer-shehane** [comment] 2020-09-29 00:09
The closing of #1183 allows you to not have to redefine cy.server() in between tests, so it will only need to be defined once.

That fix has no effect on the defined aliases. Defined aliases (like your @Test) will still be reset between each test and cannot be defined in a before hook. Duplicate of #665

**Closed by jennifer-shehane** 2020-09-29 00:09 UTC
