### ISSUE TITLE
cy.then() should retry upcoming assertions and block until they pass

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#627] opened 2017-09-10 20:58 UTC
Currently this fails:

```coffeescript
it "cy.then does not verify upcoming assertions", ->
  obj = {foo: "bar"}

  cy.wrap(obj).then ->
    setTimeout ->
      obj.foo = "baz"
    , 1000

    return obj
  .should("deep.eq", {foo: "baz"})
```

The reason is because `cy.then` does not verify upcoming assertions. Even though its callback function needs to only be called once (and be idempotent) it could still verify upcoming assertions on the return value from the callback function.

That would enable the above example to pass.

**Comment by brian-mann** [comment] 2017-09-12 22:24
It should only block and retry on mutate objects else do not retry

**Comment by Bkucera** [comment] 2019-01-28 22:24
the code mentioned in the original comment is failing due to this bug #3230

**Comment by jennifer-shehane** [comment] 2019-02-28 16:47
Closing as duplicate of https://github.com/cypress-io/cypress/issues/3230

**Closed by jennifer-shehane** 2019-02-28 16:47 UTC
Labels: pkg/driver, type: duplicate
