### ISSUE TITLE
`.each(..)` wrongfully propagates subject to a parent-style invoked dual-command

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#6550] opened 2020-02-25 11:44 UTC
### Current behavior:

Given a [dual-command](https://docs.cypress.io/api/cypress-api/custom-commands.html#Dual-Commands) like shown below.

```js
Cypress.Commands.add("myCommand", { prevSubject: "optional" }, (subject) => {
  // ...
});
```

When this is invoked parent-style after a chain ending in `.then(..)`, then the command is correctly invoked without a subject. However, when invoked parent-style after a chain ending in `.each(..)`, then it is wrongfully invoked with the yielded subject from `.each(..)`.

With "parent-style" invoked, I mean chained on the `cy` object.

### Desired behavior:

For a parent-style invoked dual-command to never receive a subject.

### Test code to reproduce

I've created an example [here](https://github.com/badeball/cypress-reproducible-issues/tree/master/erroneous-subject-propagation) that illustrates the issue. You can replace `.each` with `.then` and watch it pass.

### Versions

Cypress v4.0.2, Arch Linux, Chrome 80.

**Comment by jennifer-shehane** [comment] 2020-02-26 09:20
Duplicate of #4921

**Closed by jennifer-shehane** 2020-02-26 09:20 UTC
