### ISSUE TITLE
Submitting form through an iframe crashes Cypress since 3.8.0

### ISSUE THREAD

**Issue by jcheo1** [cypress-io/cypress#6076] opened 2020-01-02 00:15 UTC
### Current behavior: When submitting a form in an iframe, the Cypress test crashes and displays "Whoops, there is no test to run". This issue began at 3.8.0

![image](https://user-images.githubusercontent.com/4027861/71647842-d6ecea00-2d47-11ea-8f82-be0c548f57a2.png)
![image](https://user-images.githubusercontent.com/4027861/71647851-ea985080-2d47-11ea-865b-fc9f772af7d3.png)

### Steps to reproduce: (app code and test code)
- Run a cypress test through a <form> element in an <iframe> and submit it. 
- Test will crash immediately. 

### Versions
3.8.0, Linux mint, Chrome

**Comment by jennifer-shehane** [comment] 2020-01-02 04:23
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide the test code and html to run the test code against? Thanks.

**Comment by palmarcell** [comment] 2020-06-29 13:29
I'm also facing this issue with version 4.9.0 of Cypress and the [cypress-iframe](https://www.npmjs.com/package/cypress-iframe) plugin.

After filling out the form in the iframe and clicking on the submit (Pay) button the redirection changes the entire screen of the browser. This causes the crash of the entire test scenario.

Here is a GIF of the event:
![cypress-crash](https://user-images.githubusercontent.com/33153278/86010118-4142c680-ba1b-11ea-9974-7ccf4b83d804.gif)

I believe Cypress should never crash in case of a simple redirection.

**Comment by jennifer-shehane** [comment] 2020-08-21 08:33
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-21 08:33 UTC
Labels: stage: needs information, topic:  😳 whoops there is no test to run

**Comment by salvag-ntt** [comment] 2021-03-13 14:32
I am using this with Cypress 6.6.0 and this type of issue still appears 
A number of similar issues have been closed because of lack of reproducible case, which makes sense because you need an example to reproduce the problem, but also doesn't because such an example with credit card payment either needs to be provided with a live website or on a code base that most of the time can't be shared because of confidentiality.
The fact that this issue is quite common should lead you guys at Cypress to come up with an example similar to what's described in all those issues and try to debug it.
I know it's not easy but at least shows some effort other than closing all the bugs, acknowledging there is an issue but won't be resolved doesn't help anyone.
Who is working with cypress and faces this issue is only left with 2 alternatives: 
1 - ignore the problem not having that area of the website tested 
2 - completely replace Cypress with another tool (which is what we are planning to do and it's a shame because we really though that it was a powerful and flexible tool, until we hit this issue).

**Comment by jennifer-shehane** [comment] 2021-04-29 16:30
@salvag-ntt We are working on iframe support currently, with an understanding that a large majority of our users have iframes for payments, specifically Stripe payments, so this will be something we focus on. https://github.com/cypress-io/cypress/issues/136

Recreating every person's issue and finding a specific workaround for one issue is not the best use of our team's time. Instead we are trying to spend our time building the feature so it will work for mostly everyone.

**Comment by mdmathewdc** [comment] 2021-11-30 20:46
Any update on this issue?

**Comment by SimonGiraudMVMS** [comment] 2023-07-05 08:53
I still have the issue, any one help please ?
