### ISSUE TITLE
deprecation warning when using cy.screenshot()

### ISSUE THREAD

**Issue by joelsjostrom** [cypress-io/cypress#9366] opened 2020-11-27 16:32 UTC
### Current behavior
A deprecation warning is displayed for cy.screenshot()

<img width="716" alt="Skärmavbild 2020-11-27 kl  17 26 53" src="https://user-images.githubusercontent.com/73530499/100469444-85271e00-30d6-11eb-82b1-87b451a557f9.png">

### Desired behavior
The warning should probably only be displayed for cy.server() and cy.route()

### Test code to reproduce
Run Cypress 6.0.0 in vscode

### Versions
6.0.0

**Comment by jennifer-shehane** [comment] 2020-11-30 02:13
Duplicate of https://github.com/cypress-io/cypress/issues/9303 

This will be fixed in our next release

**Closed by jennifer-shehane** 2020-11-30 02:13 UTC
