### ISSUE TITLE
Clear() works on same input text field but type() method does not works on same field.

### ISSUE THREAD

**Issue by PriyaGurde** [cypress-io/cypress#15257] opened 2021-02-27 12:03 UTC
Clear() works on same input text field but type() method does not works on same field.

<input class="override-lds-font-color-medium-grey override-lds-body-03 override-lds-text-box w-100 figma-form-control mt-2 mt-3 undefined" type="text" id="txt-phone-number" data-placeholder="" placeholder="" name="phone_number.line_number" autocomplete="on" value="102545">

My line of code is - cy.findByLabelText('Phone number').clear().type("102546");

<img width="689" alt="Screenshot 2021-02-27 at 14 02 18" src="https://user-images.githubusercontent.com/77773210/109386632-9b768d00-7904-11eb-854f-508464e758de.png">

**Comment by jennifer-shehane** [comment] 2021-02-27 14:42
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. We'll have to close the issue without this because there's no way for us to investigate.

**Comment by PriyaGurde** [comment] 2021-02-28 10:13
what do you mean by reproducible example? can you elaborate more. 

cy.findByLabelText('Phone number').clear().type("102546");    ... is it some issue with this line of code? 

<input class="override-lds-font-color-medium-grey override-lds-body-03 override-lds-text-box w-100 figma-form-control mt-2 mt-3 undefined" type="text" id="txt-phone-number" data-placeholder="" placeholder="" name="phone_number.line_number" autocomplete="on" value="147852369">

**Comment by jennifer-shehane** [comment] 2021-02-28 13:39
We need the HTML to run this code against. Also, `findByLabelText` is not a Cypress command, so please include the version of the plugin you're using for this command. We need to be able to run the example completely - app code and test code.

**Comment by jennifer-shehane** [comment] 2021-04-29 18:04
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-04-29 18:04 UTC
Labels: stage: needs information
