### ISSUE TITLE
Response is modified by cypress

### ISSUE THREAD

**Issue by yuki-93** [cypress-io/cypress#2599] opened 2018-10-12 14:23 UTC
Sometimes cypress seems to modify the responses from my server. This happens if I use a (virtual) host to simulate an other server than localhost. After the html output is the expected output from my request (the json part at the end).
```html
<head> 
  <script type='text/javascript'> 
    document.domain = 'localhost'; 
    var Cypress = window.Cypress = parent.Cypress; 
    if (!Cypress){ 
      throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); 
    }; 
    Cypress.action('app:window:before:load', window); 
  </script> 
</head>
{"success":true,"msg":"my response string"}
```

**Comment by jennifer-shehane** [comment] 2018-10-12 16:06
@florianm93 Could you be more specific about what modifications are done to responses that is causing issues?

**Comment by florianm93** [comment] 2018-10-12 18:36
> @florianm93 Could you be more specific about what modifications are done to responses that is causing issues?

The pasted code above is the response I got from a GET in my application. So the cypress runner somehow wraps the html-document into that response.

**Comment by jennifer-shehane** [comment] 2018-10-12 23:46
Could you paste your test code (omitting sensitive urls if needed)? Also, the request headers / response headers of the request that's doing this?

**Comment by florianm93** [comment] 2018-10-15 06:51
The failing code (there is a comment, where my applicaiton crashes)
```
describe('Test Fail', () => {
    before(() => {
        cy.visit('#dashboard').then(() => {
            cy.get('.x-window', {timeout: 25000}).contains('Login').should('be.visible');
            cy.get('.x-panel').within(() => {
                cy.get('input:first').type('e_test');
                cy.get('input:last').type('1234567');
                cy.get('.x-btn').click();
            });

            // after login, the first request (login successful) from my main application fails
            cy.get('.main-header-logo', {timeout: 25000}).should('be.visible');
        });
    });
    
    it.only('should upload the test data', () => {
        cy.title().should('be', 'Page Title');
    });
});
```

Request Headers: 
```
POST http://localhost/myapp/login.php HTTP/1.1

Host: localhost

Proxy-Connection: keep-alive

Content-Length: 43

Origin: http://localhost

X-Requested-With: XMLHttpRequest

User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36

Content-Type: application/x-www-form-urlencoded; charset=UTF-8

Accept: */*

Referer: http://localhost/myapp

Accept-Encoding: gzip, deflate, br

Accept-Language: en-US,en;q=0.9

Cookie: __cypress.initial=true
```

Response Headers: 
```
HTTP/1.1 200 OK

date: Mon, 15 Oct 2018 06:44:47 GMT

server: Apache/2.4.18 (Ubuntu)

expires: Thu, 19 Nov 1981 08:52:00 GMT

cache-control: no-cache, no-store, must-revalidate

pragma: no-cache

connection: close

content-type: text/html; charset=UTF-8

Set-Cookie: PHPSESSID=foobar; path=/

Set-Cookie: __cypress.initial=; Domain=localhost; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT

Vary: Accept-Encoding

Content-Encoding: gzip

Transfer-Encoding: chunked
```

**Comment by jennifer-shehane** [comment] 2018-10-15 22:53
I see you posted the request headers for a `POST` endpoint, but your original issue outlined a problem with the response returned from a `GET` endpoint. Am I missing something?

I wish something were standing out more in the information you provided as the obvious problem, but we'll likely need a reproducible repo to get debugging started on this. 

As a side note, you should not need the `.then` chained off of `cy.visit()`, the next command will not run until the `load` event is fired from visiting the page.

**Comment by florianm93** [comment] 2018-10-16 06:37
Ah right, it's a POST not a GET request. 

Thanks for the note with the visit and then.

**Comment by florianm93** [comment] 2018-10-16 06:39
Sadly I have no public repo to publish for you :( 

Maybe I can try to build an example later

**Comment by florianm93** [comment] 2018-10-16 09:16
I figured out that it looks like a timing issue. My app only crashed for a producation build, which has minified JS. When I use a non minified build, then cypress runs normally. 

So it looks like my app loads 'to fast' so that cypress is not correctly setted up?

**Comment by florianm93** [comment] 2018-10-17 12:01
Hello again...

Ok this issue seems to be partially a cypress (injecting the cypress code into received request data) and partially an application issue (using appcache and setting content-type text/html on json).

Cypress doesn't properly work with web applications that use an appcache. Cypress fails to insert the __cypress.initial=true cookie due to the index page being cached in the appcache.

If you run the app with a cleared appcache, the index.html is correctly loaded and the cypress-loader properly injected. On the second run the index.html is used from the cache, where cypress fails to add the __cypress.initial cookie and thus delaying it to the first response with content-type text/html to a request with the __cypress.initial cookie (in our example it was the returned json).

Now if there's some XHR response with content-type text/html and the  __cypress.initial, cypress injects it's loader code, regardless of it being a dynamically loaded HTML-snippet. This might probably result in event/action 'app:window:before:load' triggering multiple times.

One would expect cypress to inject itself always into the visited application's index file and not into subsequent XHR-responses, potentially altering behavior.

Attached there's an example app and test spec to exhibit the behavior, described here. 
[dist.tar.gz](https://github.com/cypress-io/cypress/files/2487234/dist.tar.gz)

**Comment by bahmutov** [comment] 2018-10-17 12:18
That’s really interesting information, good debugging

**Comment by yuki-93** [comment] 2018-10-24 06:54
@bahmutov @jennifer-shehane do you have any progress or time here, when this might get fixed? :)

**Comment by devsh4** [comment] 2018-11-02 15:55
Facing the same issue. Would be great if it gets fixed soon. This bug doesn't necessarily stop me from testing my app further, but still should be fixed.

**Comment by jennifer-shehane** [comment] 2018-11-02 19:39
Thanks for narrowing this issue down for us.

Would it be correct to say that things would work well for your use case if Cypress were to clear `appcache` before each `it` test instead of persisting across tests?

**Comment by yuki-93** [comment] 2018-11-02 20:36
Not fully. The problem is, for the second (and all other) run of the tests, the index.html is cached by browser. So cypress doesn’t plug in there but into the next “file” which here is an XHR response.

**Comment by chincheeheng** [comment] 2021-02-03 08:48
Testing with the 6.4.0 version, when download CSV with click, the file injected with header.

<head> <script type='text/javascript'> document.domain = 'XXXXXXXXXX'; var Cypress = window.Cypress = parent.Cypress; if (!Cypress) { throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); }; Cypress.action('app:window:before:load', window); </script> </head>

**Comment by jennifer-shehane** [comment] 2021-02-04 06:21
@chincheeheng This is expected behavior. We have to inject this to run Cypress.

Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-04 06:21 UTC
Labels: stage: needs investigating, type: bug

**Comment by chincheeheng** [comment] 2021-02-04 06:23
> @chincheeheng This is expected behavior. We have to inject this to run Cypress.
> 
> Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

This will be a problem when we try to run download, when the thing injected to csv file, then the validation will not work.
May you advise? this related to the download file test.

**Comment by jennifer-shehane** [comment] 2021-02-04 09:10
@chincheeheng Can you provide a basic example in a newly opened issue? HTML + cypress code where your validation is failing? Thanks!

**Comment by marcospoliceno** [comment] 2022-10-10 12:52
cypress ainda tem esse problema 

retorna o download CSV com o HTML <head> <script type='text/javascript'> document.domain = .....
e não com a integridade do arquivo CSV
impossibilitando a validação do arquivo
