### ISSUE TITLE
Cypress - Next js undefined while server side rendering 

### ISSUE THREAD

**Issue by andru-roshan** [cypress-io/cypress#27017] opened 2023-06-13 14:24 UTC
### Current behavior

![MicrosoftTeams-image (8)](https://github.com/cypress-io/cypress/assets/101979651/fe865268-58af-4199-9ca8-cbd773984b99)
while running the Component test in next js , the above error where occur 

### Test code to reproduce

Import next in 'next' in component need to tested in cypress.

### Cypress Version

12.14.0

### Node version

16.18.1

### Operating System

windows 10

**Comment by nagash77** [comment] 2023-06-14 12:38
Hi @andruroshan Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by mike-plummer** [comment] 2023-06-26 14:10
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by mike-plummer** 2023-06-26 14:10 UTC
