### ISSUE TITLE
ctrl+shift+u combination not working

### ISSUE THREAD

**Issue by Brestachan** [cypress-io/cypress#6514] opened 2020-02-20 08:30 UTC
I'm having a problem with calling a certain key combination. I need to test if some input field accepts any and all special characters form List of Unicode Characters, https://en.wikipedia.org/wiki/List_of_Unicode_characters.

To be able to make an input, the key combination is CTRL+SHIFT+U, and then the rest, ie. for Null Character I would have to start with CTRL+SHIFT+U, and then type 0000.
The thing is, I can't get it to work, no matter what.

Currently, my code looks like this:

```js
cy.get('#iiotAuthCredentialsDockerUsername').click().type('{ctrl}{shift}u',{release:false})
cy.get('#iiotAuthCredentialsDockerUsername').type("0000")
```

but I tried with this one also:

```js
cy.get('#iiotAuthCredentialsDockerUsername').click().type('{ctrl}{shift}',{release:false}).trigger('keydown', { keyCode: 85, which: 85 })
cy.get('#iiotAuthCredentialsDockerUsername').type("0000")
```

and none of it works.

**### Desired behavior:**

CTRL+SHIFT+U combination should make the same input as if it's typed in manually.

**Comment by jennifer-shehane** [comment] 2020-02-20 08:34
Please provide sample HTML code to run these tests within to demonstrate the issue. A simple `index.html` and then `cy.visit('index.html')` would work fine - showing the behavior of what it not happening when typing `CTRL+SHIFT+U` exactly.

**Comment by Brestachan** [comment] 2020-02-20 08:49
It's supposed to trigger special character input, you can try typing anywhere in you browser if you're using Ubuntu. For example, pressing ctrl+shift+u and then typing 0024 will show up as dollar sign ($).
I need to make that exact input through Cypress test, for now it doesn't matter where, in any input field.

**Comment by jennifer-shehane** [comment] 2020-02-20 10:12
Keyboard shortcuts built into the operating system will not work in this way in Cypress. Cypress is not issuing a native keyboard event, but simulating events within the application under test that would normally trigger within a browser. 

Duplicate of #311 

You may want to comment in that issue explaining what you want to test, although I'm not sure why you would need to test the actual functionality of the operating systems keyboard shortcuts. 

I would suggest just typing the special characters into the input you want to test, since testing the OS system functionality is unnecessary. 

```js
cy.get('input').type('$')
```

**Closed by jennifer-shehane** 2020-02-20 10:12 UTC
Labels: stage: awaiting response
