### ISSUE TITLE
Logging Issue: Cannot set property '2' of undefined

### ISSUE THREAD

**Issue by mcblum** [cypress-io/cypress#7843] opened 2020-06-29 13:17 UTC
### Current behavior:

This is very, very strange. Something in our test suite is throwing an error, but I cannot tell what it is. Visually, the test looks fine, but there's an internal Cypress method that's throwing.

### Desired behavior:

Either a more detailed stack trace or a bugfix.

### Test code to reproduce

I can't provide this because all of the code is private. Even still, I have the code that's failing within Cypress:

```js
 Cypress.on('log:changed', options => {
    if (logsChainId[options.id] && options.state === 'failed') {
      logs[logsChainId[options.id]][2] = CONSTANTS.SEVERITY.ERROR;
    }
  });
```

This line `logs[logsChainId[options.id]][2]` throws the error, because `logs[logsChainId[options.id]]` is actually undefined. I know you say you need a runnable example, but I've been at this for three days and I've tried everything under the sun.

### Versions

"cypress": "^3.8.1",
MacOS + Linux (Jenkins)
Chrome Latest

Thank you for taking a look, I love Cypress!

**Comment by jennifer-shehane** [comment] 2020-06-30 08:37
@mcblum Where is `logs` and `logsChainId` initially defined in your code? I can't begin to look at this without understanding how you've built up these objects beforehand. Please provide a fuller code example of how you're building up these objects outside of this listener.

**Comment by mcblum** [comment] 2020-06-30 12:53
@jennifer-shehane interesting -- I thought this was your code :) Let me investigate this and see what's happening. Will update shortly.

**Comment by thejdeep** [comment] 2020-07-15 03:21
@mcblum Are you using `cypress-terminal-report` ? This is an error on that is caused by that package https://github.com/archfz/cypress-terminal-report/issues/31

**Comment by jennifer-shehane** [comment] 2020-07-15 06:23
Closing as an external issue with cypress-terminal-report. Please update that dependency.

**Closed by jennifer-shehane** 2020-07-15 06:23 UTC
Labels: stage: needs information
