### ISSUE TITLE
cy.visit(Cypress.env('baseUrl')) not able to read url from docker-compose.yml environment variable.

### ISSUE THREAD

**Issue by ajays01061991** [cypress-io/cypress#24326] opened 2022-10-20 15:15 UTC
### Current behavior

**I am trying to read url passed in docker compose environment** 
version: '3'
services:
    dev:
        image: cypress2
        build: 
           context: .
           dockerfile: ./Dockerfile
        environment:
            - CYPRESS_baseUrl=https://test.com/
        volumes:
            - /reports/cucumber-htmlreport.html:/app/reports/cucumber-htmlreports.html
        stdin_open: true
        tty: true

**and pass it to cy.visit(Cypress.env('baseUrl')) which is giving error:**

CypressError: `cy.visit()` must be called with a `url` or an `options` object containing a `url` as its 1st argument
#0 18.32
#0 18.32 https://on.cypress.io/visit
#0 18.32       at Context.visit (http://localhost:38291/__cypress/runner/cypress_runner.js:163182:78)
#0 18.32   From Your Spec Code:
#0 18.32       at loginPageAction.openCenteropURLFromConfig (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:1110:10)
#0 18.32       at Context.eval (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:89:13)
#0 18.32       at Context.resolveAndRunStepDefinition (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:13272:9)
#0 18.32       at Context.eval (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:12590:35)

i tried using .env file and docker-compose.dev.yml from which docker-compose is able to read url but same is not getting passed to cy.visit which is essential to run rest of code.
I have used Cypress.env.json file to store url and directly running npx command is working but when comes to using same json to pass from compose it fails with same above error.

### Desired behavior

url passed from environment variable in compose should get passed to cy.visit().

### Test code to reproduce

Attached in above comment.

Test file code:
openCenteropURLFromConfig() {
    //cy.request('baseUrl');
   // Cypress.env('dev_env');
    cy.visit(Cypress.env('baseUrl'))
  }

Compose file content:

version: '3'
services:
    dev:
        image: cypress2
        build: 
           context: .
           dockerfile: ./Dockerfile
        environment:
            - CYPRESS_baseUrl=https://test.com/
        volumes:
            - /reports/cucumber-htmlreport.html:/app/reports/cucumber-htmlreports.html
        stdin_open: true
        tty: true 

### Cypress Version

9.7.0

### Node version

16.17.1

### Operating System

Windows, docker linux

### Debug Logs

```shell
CypressError: `cy.visit()` must be called with a `url` or an `options` object containing a `url` as its 1st argument
#0 18.32
#0 18.32 https://on.cypress.io/visit
#0 18.32       at Context.visit (http://localhost:38291/__cypress/runner/cypress_runner.js:163182:78)
#0 18.32   From Your Spec Code:
#0 18.32       at loginPageAction.openCenteropURLFromConfig (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:1110:10)
#0 18.32       at Context.eval (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:89:13)
#0 18.32       at Context.resolveAndRunStepDefinition (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:13272:9)
#0 18.32       at Context.eval (http://localhost:38291/__cypress/tests?p=cypress/integration/Login.feature:12590:35)
```

**Comment by nagash77** [comment] 2022-10-20 18:22
Hi @ajays01061991 Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

We also will need to see your docker file in order to help investigate.  Please share that with us as well.

**Comment by nagash77** [comment] 2022-10-27 18:00
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-10-27 18:00 UTC
