### ISSUE TITLE
Cypress is referencing to the wrong aliased element

### ISSUE THREAD

**Issue by wlsf82** [cypress-io/cypress#17470] opened 2021-07-24 00:18 UTC
### Current behavior

I have a test that has three aliases for three different elements. They are:

```js
cy.contains('button', 'Start')
  .as('startBtn')

cy.get('input[type="text"]')
  .as('textField')

cy.contains('button', 'Reset')
  .as('resetBtn')
```

As you can see, every alias refers to a different element.

The last assertion of my test is:

```js
cy.get('@resetBtn')
  .should('not.exist')
```

And this exact step fails with the following error:

```
AssertionError: Timed out retrying after 4000ms: Expected to find element: `input[type="text"]`, but never found it.
```

### Desired behavior

Cypress should refer to the correct element through its alias, and the tests should pass.

### Test code to reproduce

Here's a draft PR that changes a sample app and updates its test, which fails with a failure that seems to be a Cypress issue: https://github.com/wlsf82/live-tat-code-cov/pull/3.
And here's the failing test result from GitHub Actions https://github.com/wlsf82/live-tat-code-cov/pull/3/checks?check_run_id=3148179864.

### Cypress Version

I tried on versions 8.0.0 and 7.7.0, and the issue happens on both of them.

### Other

I'm using a macOS Big Sur Version 11.5

**Comment by wlsf82** [comment] 2021-07-24 00:30
Analyzing the failure closer, Cypress is somehow running an assertion that has already run (see screenshots.)

<img width="443" alt="Screenshot 2021-07-24 at 02 29 26" src="https://user-images.githubusercontent.com/2768415/126852231-1cbb9bed-21d1-4c32-89ec-4099043fec1c.png">

<img width="442" alt="Screenshot 2021-07-24 at 02 29 35" src="https://user-images.githubusercontent.com/2768415/126852235-2144737c-8445-4993-89ba-bf9244ba7463.png">

**Comment by wlsf82** [comment] 2021-07-24 00:31
@jennifer-shehane, would you mind looking into it, please?

**Comment by jennifer-shehane** [comment] 2021-07-29 13:53
I believe this may be a duplicate of https://github.com/cypress-io/cypress/issues/7413 where there's a situation where the `cy.contains` is not correctly viewed as a parent command. 

Can you try writing `cy.root().contains()` to replace the `cy.contains()` in your case and verify whether this fixes the issue?

**Comment by wlsf82** [comment] 2021-07-29 19:58
> I believe this may be a duplicate of #7413 where there's a situation where the `cy.contains` is not correctly viewed as a parent command.
> 
> Can you try writing `cy.root().contains()` to replace the `cy.contains()` in your case and verify whether this fixes the issue?

Yup, I've used `cy.root().contains('button', 'Reset')` and this fixes the issue.

And it does seem to be a duplicate of the issue you mentioned. Feel free to close this one.

Thanks!

**Comment by wlsf82** [comment] 2021-07-29 20:03
By the way, I'll read about `cy.root()`. I didn't know about it. :bow:

**Closed** 2021-12-05 01:30 UTC
Labels: stage: awaiting response
