### ISSUE TITLE
Unable to run a spec using chrome browser in test runner and shows Error: EPERM: operation not permitted, unlink '

### ISSUE THREAD

**Issue by allysonmorenolee** [cypress-io/cypress#18969] opened 2021-11-18 02:04 UTC
### Current behavior

Unable to run a spec using chrome browser in test runner and shows Error: EPERM: operation not permitted, unlink '

### Desired behavior

Able to run spec on chrome browser without the error 

### Test code to reproduce

we dont have a public repo

### Cypress Version

9.0.0

**Comment by BlueWinds** [comment] 2021-11-18 19:17
It's possible this is a duplicate of https://github.com/cypress-io/cypress/issues/18893, but without a reproducible example, there's not much we can do to help. I'm going to close this since there's not enough information to reproduce.

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by BlueWinds** 2021-11-18 19:17 UTC
