### ISSUE TITLE
Fail to intercept same URL requests in different testing function

### ISSUE THREAD

**Issue by Kenny-Snub-Nose-Monk** [cypress-io/cypress#26298] opened 2023-03-30 03:47 UTC
### Current behavior

I would like to use the API call with the URL '/api/apps*'.

There are three tests within a single describe function.

Each test will use cy.intercept to intercept the same API, but perform different actions.

When I run all three tests together, only the first interception passes.

However, if I test the second interception individually, it works.

### Desired behavior

should be passed in three testing if intercept the same url.

### Test code to reproduce

```
describe('Apps', () => {
   const apiURL = '/api/apps*';

  it('First testing', () => {

    cy.intercept('GET', apiURL, (req) => { ... }).as('getFirst');
    // success
    cy.wait('@getFirst');
  })

  it('Second testing', () => {
        cy.intercept('GET', apiURL, (req) => { ... }).as('getSecond');
        //fail: timeout
        cy.wait('@getSecond');
  })

  it('Third testing', () => {
        cy.intercept('GET', apiURL, (req) => { ... }).as('getThird');
        //fail: timeout
        cy.wait('@getThird');
  })
})
````

### Cypress Version

12.8.1

### Node version

v18.14.1

### Operating System

macOS 13.2.1（22D68）

**Comment by astone123** [comment] 2023-03-31 17:22
Hey @Kenny-Snub-Nose-Monkeys, are you able to provide a repository so that we can easily reproduce this issue? Thanks

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-04-02 04:40
Sorry, I can't provide that since it's my company product.
But what I did just like below, try to mock data and also to test 404 response to render in my app.

```
describe('testing', () => {

    const api  =  '/data/app/*';

    it("first", () => {
        cy.intercept('GET', api, (req) => { ... // }).as('firstMock');
        cy.wait('@firstMock');
    })

    it("second", () => {
        cy.intercept('GET', api, { body: mockAPIViral }).as('getMockData');
       //fail
        cy.wait('@getMockData');
    })

    it("third", () => {
        cy.intercept('GET', api, { statusCode: 404 }).as('getApi404');
       //fail
        cy.wait('@getApi404');
    })
})```

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-04-10 03:14
Please let me know if you're not clear for my requirement. 
Thx

**Comment by jordanpowell88** [comment] 2023-04-19 20:22
@Kenny-Snub-Nose-Monk Are you trying to do API testing? ie: test the API and various responses or are you just showing these API examples as a way to replicate the issue your experiencing in E2E?

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-04-20 03:38
> @Kenny-Snub-Nose-Monk Are you trying to do API testing? ie: test the API and various responses or are you just showing these API examples as a way to replicate the issue your experiencing in E2E?

Hi Jordan,  I think  I am doing E2E testing, try to simulate different scenarios (404 Error or no match API schema ...) and expect APP can render right content or route to correct page.

**Comment by jordanpowell88** [comment] 2023-04-20 17:32
@Kenny-Snub-Nose-Monk I am unable to reproduce the error you are experiencing. When I create an example just like the you have above I get 3 passing tests and all 3 intercepts are registered and called once

```ts
describe("demo", () => {
  const api = 'http://localhost:3000/api/'
  
  it("should display welcome message", () => {
    cy.intercept(api).as('greeting');
    cy.visit('/')
    cy.wait('@greeting')
    getGreeting().contains("Hello API");
  });

  it("should display welcome message", () => {
    cy.intercept(api).as('greeting2');
    cy.visit('/')
    cy.wait('@greeting2')
    getGreeting().contains("Hello API");
  });

  it("should display welcome message", () => {
    cy.intercept(api).as('greeting3');
    cy.visit('/')
    cy.wait('@greeting3')
    getGreeting().contains("Hello API");
  });
});
```

![Screenshot 2023-04-20 at 1 31 58 PM](https://user-images.githubusercontent.com/3605268/233443605-3f1a21c5-8068-4974-a290-583fdfb74431.png)



Can you provide a reproducing example so we can further investigate the exact issue you are experiencing

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-04-22 08:59
ok , I mocked some private information. Hope code below can help you more understand my question.
Thanks your help.

```
/// <reference types="Cypress" />

describe('Apps', () => {
    const apiURL = '/api/apps*';

    beforeEach(() => {
        cy.visit(Cypress.env('BASE_URL') + '/#/main');
    });

    it('Test Filter function', () => {
        cy.intercept(
            'GET',
            apiURL,
            (req) => {
                const url = new URL(req.url);
                const countryParam = url.searchParams.get('country');
                if (countryParam === 'HK') {
                    expect(countryParam).to.equal('HK');
                }
            }).as('getHKData');

        cy.get('.menu-xx-dashboard').scrollIntoView().click();

        cy.get('.dropdownlist-optionGroup').then(() => {
            cy.get('.dropdownlist-single-option').should('have.length', 2); 
            cy.get('.dropdownlist-single-option').eq(1).click();
            cy.wait('@getHKData');
            cy.get('.field-text').contains('Hong');      
        });
    });

    it('Expect text and attributes based on the response payload.', () => {
        cy.fixture('response.json').then((mockAPI) => {
            cy.intercept('GET', apiURL, { body: mockAPI }).as('getMockData');
            cy.get('.menu-xx-dashboard').scrollIntoView().click();
            cy.wait('@getMockData', { timeout: 4000 }).its('response.statusCode').should('eq', 200);  
            cy.get('.chart-percentCompareBar-label').contains('Games').should('have.text', 'Games');
        }); 

    });


    it('API 404 response validation', () => {
        cy.intercept('GET', apiURL, { statusCode: 404 }).as('getApi404');
        cy.get('.menu-xx-dashboard').scrollIntoView().click();
        cy.wait('@getApi404');
        cy.url().should('not.include', '/top-apps');
    });

});


```

**Comment by jordanpowell88** [comment] 2023-04-24 17:27
@Kenny-Snub-Nose-Monk I'm still unable to reproduce the issue you are describing. What you are describing should be working (and I'm able to get it to work locally). Can you send a screenshot of the Route Matcher output?


![Screenshot 2023-04-24 at 1 26 37 PM](https://user-images.githubusercontent.com/3605268/234071522-02233cc0-ddb8-49fe-b057-269e5b4977ad.png)

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-04-27 10:20
@jordanpowell88 here...

First one is fine, but second can't work.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/27717979/234834376-dea81919-b9e0-4a57-a3ef-2225371763ba.png">

**Comment by redjonzaci** [comment] 2023-05-10 09:10
We are having the same problem, but only in Electron. 
Also, we have the intercept in `beforeEach`.
In our case too, the request doesn't occur so the route matcher doesn't have what to match.
When I use Chrome, it works fine.

We are using Amplify and we need to run the Cypress tests during Amplify build,
so we really need the tests to run on Electron.

Similar issue (closed): #26120

**Comment by marktnoonan** [comment] 2023-05-11 14:22
@Kenny-Snub-Nose-Monk could you confirm do you also only experience this in electron?

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-05-12 07:49
No, I used Chrome.
My temporally solution is to split them into different testing file, and it works for now.

**Comment by marktnoonan** [comment] 2023-05-12 12:11
Got it. @Kenny-Snub-Nose-Monk I am curious if you are able to reproduce this experience using https://github.com/cypress-io/cypress-test-tiny. Since we have not been able to reproduce on our side, it's likely there is some extra piece of information needed which might be in your project's config or dependencies.

@redjonzaci when you say that other Electron issue is similar, what do you mean - are you doing something similar with Remote Debugger Protocol, which was the underlying cause there? Or is something else similar?

**Comment by marktnoonan** [comment] 2023-05-19 00:50
This one is about to close due to inactivity so I want to bump it one more time. @Kenny-Snub-Nose-Monk or @redjonzaci if either of you have the ability to provide us with all the context needed to reproduce we can look into this.

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-05-20 02:55
Sorry, I will do it today and let you know

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-05-22 03:44
Is possible the reason is from cache?

![image](https://github.com/cypress-io/cypress/assets/27717979/15576c68-1461-4adb-9ab5-221967daedfd)

**Comment by Kenny-Snub-Nose-Monk** [comment] 2023-05-22 03:51
> Got it. @Kenny-Snub-Nose-Monk I am curious if you are able to reproduce this experience using https://github.com/cypress-io/cypress-test-tiny. Since we have not been able to reproduce on our side, it's likely there is some extra piece of information needed which might be in your project's config or dependencies.
> 
> @redjonzaci when you say that other Electron issue is similar, what do you mean - are you doing something similar with Remote Debugger Protocol, which was the underlying cause there? Or is something else similar?

I can't use npx cypress open  in cypres-test-tiny. 

Anyway, could you try below testing in your site.

```
/// <reference types="cypress" />
describe('page', () => {

    const url = 'https://pomofocus.io/env-constant*'
    const user = 'https://pomofocus.io/api/use'


    it('Test1', () => {
        cy.intercept('GET', url).as('getApi1');
        cy.intercept('GET', user).as('getApi_user1');
        cy.visit('https://pomofocus.io/');
        cy.wait('@getApi1').its('response.statusCode').should('eq', 200);
        cy.wait('@getApi_user1').its('response.statusCode').should('eq', 403);
    })

    it('Test2', () => {
        cy.intercept('GET', url, { statusCode: 403 }).as('getApi2');
        cy.intercept('GET', user).as('getApi_user2');
        cy.visit('https://pomofocus.io/');
        cy.wait('@getApi2').its('response.statusCode').should('eq', 403);
        cy.wait('@getApi_user2').its('response.statusCode').should('eq', 403);
    });

    it('Test3', () => {
        cy.intercept('GET', url).as('getApi3');
        cy.intercept('GET', user).as('getApi_user3');
        cy.visit('https://pomofocus.io/');
        cy.wait('@getApi3').its('response.statusCode').should('eq', 200);
        cy.wait('@getApi_user3').its('response.statusCode').should('eq', 403);
    });
})

```

**Comment by mike-plummer** [comment] 2023-06-28 18:00
@Kenny-Snub-Nose-Monk Unfortunately I'm not able to reproduce any error with the example code you provided (after fixing the typo in the `user` URL (missing the last 'r'). All tests pass in every browser I've tried using the latest version of Cypress.

At this time I'm going to close this issue - that doesn't mean we don't believe you, but until we receive a full reproducible example we aren't going to be able to diagnose or fix whatever might be causing this behavior. If an example can be provided we would be delighted to reopen and investigate this issue.

**Closed as not planned by mike-plummer** 2023-06-28 18:00 UTC

**Comment by Magnific7** [comment] 2024-10-16 16:06
> @Kenny-Snub-Nose-Monk Unfortunately I'm not able to reproduce any error with the example code you provided (after fixing the typo in the `user` URL (missing the last 'r'). All tests pass in every browser I've tried using the latest version of Cypress.
> 
> At this time I'm going to close this issue - that doesn't mean we don't believe you, but until we receive a full reproducible example we aren't going to be able to diagnose or fix whatever might be causing this behavior. If an example can be provided we would be delighted to reopen and investigate this issue.

I am facing the same issue,
