### ISSUE TITLE
Cookies are disabled

### ISSUE THREAD

**Issue by ImBIOS** [cypress-io/cypress#26929] opened 2023-06-05 03:08 UTC
### Current behavior

![Screenshot 2023-06-05 at 10 08 40](https://github.com/cypress-io/cypress/assets/41441643/6f049b39-54a9-454f-8bdd-5df3204f4082)

I'm following [official docs](https://docs.cypress.io/guides/end-to-end-testing/social-authentication)

### Test code to reproduce

I didn't have time to make reproducable repository yet.

### Cypress Version

12.13.0

### Node version

v18.15.0

### Operating System

macOS 13.4

### Other

```

  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 61.72 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/29565_1685934730167/bin/node
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/29565_1685934730167/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Languages:
    Bash: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.5
  npmPackages:
    cypress: ^12.13.0 => 12.13.0 
    husky: ^8.0.3 => 8.0.3 
    is-ci-cli: ^2.2.0 => 2.2.0 
    jest: ^29.5.0 => 29.5.0 
    jest-environment-jsdom: ^29.5.0 => 29.5.0 
    next: 13.4.3 => 13.4.3 
    next-auth: ^4.22.1 => 4.22.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.1.3 => 5.1.3 


```

Seems similar to #17166

**Comment by nagash77** [comment] 2023-06-05 13:17
Hi @ImBIOS Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

Also check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nagash77** [comment] 2023-06-12 12:46
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-06-12 12:46 UTC
