### ISSUE TITLE
Cypress doesn't provide options to connect to the Informix database

### ISSUE THREAD

**Issue by premkh9** [cypress-io/cypress#20484] opened 2022-03-04 16:40 UTC
### What would you like?

I require plugin to connect to informix DB to run queries 

### Why is this needed?

I see plugins for MySQL, Oracle and SQL server. Any help on this would be much appreciated. For Informix, I need to provide host, port, server and DB details along with username and password

**Comment by davidmunechika** [comment] 2022-03-30 12:40
Closing because duplicate of https://github.com/cypress-io/cypress/issues/20838

**Closed by davidmunechika** 2022-03-30 12:41 UTC
Labels: topic: plugins ⚙️
