### ISSUE TITLE
Support websocket connection through proxy

### ISSUE THREAD

**Issue by dberecz** [cypress-io/cypress#7872] opened 2020-07-02 14:54 UTC
### Current behavior
In corporate environments it's common that certain sites are available via proxies.
Reaching a website through Cypress via proxy is possible right now.

However, if the site (reachable via proxy) is using WebSockets, then loading the website will error out when loading with Cypress: `Error during WebSocket handshake`.

This behaviour is not reproducible when loading site outside of Cypress.

### Desired behavior

WebSocket connections succeed when webpage is loaded with Cypress if proxy is used.

### Reasoning

In corporate environments many applications to be tested are only available through proxies.
If the application under test is using WebSockets, this makes testing those applications virtually impossible.

### Versions

Cypress 4.9.0, all browsers on all operating systems

**Comment by sainthkh** [comment] 2021-01-15 06:18
Sorry for the late reply. Closing because it's duplicate of #7664.

**Closed by sainthkh** 2021-01-15 06:18 UTC
