### ISSUE TITLE
Failed to set the 'domain' property on 'Document'. Is not a suffix of. Remote.DomainName contains different domain

### ISSUE THREAD

**Issue by chielos24** [cypress-io/cypress#1278] opened 2018-02-08 08:54 UTC
- Operating System: Windows 8.1
- Cypress Version: 1.4.2.
- Browser Version: 64.0.3282.140 (latest)

### Is this a Feature or Bug?
Bug

### Current behavior:
error:
Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'localen.local' is not a suffix of 'www.local<sitename>.nl'.
    at $Cypress.setConfig (http://www.local<sitename>.nl/__cypress/runner/cypress_runner.js:60706:23)
    at new $Cypress (http://www.local<sitename>.nl/__cypress/runner/cypress_runner.js:60697:10)
    at Function.$Cypress.create (http://www.local<sitename>.nl/__cypress/runner/cypress_runner.js:61030:12)
    at Object.setup (http://www.locale<sitename>.nl/__cypress/runner/cypress_runner.js:138273:32)
    at Iframes._this._run (http://www.local<sitename>.nl/__cypress/runner/cypress_runner.js:137269:30)

### Desired behavior:
Working solution

### How to reproduce:
Run a test. 

#### Test code:
Tried in 1.4.1. and 1.4.2.

1.4.1 is still working 

This line of code in the runner:
    if (d = (ref = config.remote) != null ? ref.domainName : void 0) {
      document.domain = d;
    }

Apparently remote contains this 'localen.local

Config:
{
  "baseUrl": "http://www.local<sitename>.nl/",
  "viewportHeight": 968,
  "viewportWidth": 1366,
  "chromeWebSecurity": false,
  "env": {
    "local": "http://www.local<sitename>.nl/"
  },
  "projectId": "132465"
}

**Comment by brian-mann** [comment] 2018-02-08 14:28
This is a duplicate of this https://github.com/cypress-io/cypress/issues/1265

It's the same issue - having `local` in the URL is causing Cypress to think that's the TLD. It's a regression in `1.4.2`

**Closed by brian-mann** 2018-02-08 14:28 UTC

**Comment by brian-mann** [comment] 2018-02-11 18:28
Opened issue here: https://github.com/cypress-io/cypress/issues/1292

**Comment by brian-mann** [comment] 2018-02-16 06:16
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
