### ISSUE TITLE
cy.request() does not send cookies when app has underscore in it's URL

### ISSUE THREAD

**Issue by vovkvlad** [cypress-io/cypress#3134] opened 2019-01-15 11:51 UTC
### Description
Hi!
locally our project runs on domain `local.domain.com`. When we run tests, for authentication purposes we set 2 fake auth cookies

Recently we changed our app's URL for local testing to `local_test.domain.com`
All tests are passing successfully, except those that are using `cy.request()` to create some data on the back-end via API. The problem is that `cy.request()` just don't include cookies at all, and thus, we are receiving `HTTP 401` status code.

It seems pretty strange, but the exact same code includes cookies when app is running on `local.domain.com` and even `localtest.domain.com` but once underscore is present in URL, cookies are not included in `cy.request()`

### Current behavior:

* `cy.request()` does not include cookies when app is running on `local_test.doamin.com`

### Desired behavior:

* all cookies should be included in the same way it does for `local.doamin.com` and `localtest.doamin.com`

### Steps to reproduce: (app code and test code)

* get simple server hosting dumb html page
* server should check for cookies for authentication
* run web page on URL with underscore in domain name
* set cookies to env via `cy.setCookie`
* observe `cy.request` no including any cookies

### Versions
Started to be overviewed starting from version `3.1.1` and later

**Comment by flotwig** [comment] 2019-11-07 21:47
I confirmed that this issue is present up to Cypress 3.4.1, it has been fixed since Cypress 3.5.0. Closing this issue as it works properly in the most recent version.

--

Btw, you should be aware that while `local_test` is a valid DNS hostname, it's not a valid hostname in the context of a URL: https://stackoverflow.com/a/2183140/3474615

So while `http://local_test.domain.com` may work in some browsers, it will probably cause problems with tools that expect your URL to strictly follow standards (including Cypress).

**Closed by flotwig** 2019-11-07 21:47 UTC
Labels: topic: cookies :cookie:
