### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by Ramanwalia0216** [cypress-io/cypress#6429] opened 2020-02-12 12:12 UTC
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').
```

### Current behavior:

On the login page, I am entering a valid username and password and then clicking on the Login button, but instead of logging into the application, the application keeps on loading with the following message.

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').
aptrinsic.js?a=AP-HQ8F6KENF3NB-2:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://applicationname-web.domain.com') does not match the recipient window's origin ('https://applicationname.domain.com').
```

### Desired behavior:
I should be able to log in.

### Versions
Version: 3.8.1

MacOS, Chrome browser

**Comment by kaushal90** [comment] 2020-02-13 06:10
@brian-mann @jennifer-shehane : We need your assistance here, Could you please help us to figure it out. It is critical for us.
Thank you in Advance!

**Comment by jennifer-shehane** [comment] 2020-02-13 09:56
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-13 09:56 UTC

**Comment by Ramanwalia0216** [comment] 2020-02-13 11:29
@jennifer-shehane, here is the complete scenario. 
I am logging into the application using the link say 'https://applicationname.domain.com' but when I am clicking on the login button an iframe is getting created within our application, which internally redirects to another URL say: 'https://applicationname-web.domain.com' and keeps on creating the iframes. Hence we are getting the error message which I mentioned above. Our base URL dos not change. Please let me know if further steps are required.

**Comment by kaushal90** [comment] 2020-02-13 17:32
@brian-mann  @jennifer-shehane : It is blocker for us, Could you please take a look into this and do let us know in case you need more details from our end.
:(

**Comment by bahmutov** [comment] 2020-02-13 17:42
Please, if this is a blocker, give us a fully-reproducible example we can run to see the failure.

**Comment by kaushal90** [comment] 2020-02-17 16:20
Hi all, Thank you for your prompt responses. We have found the solution for this. We were facing this issue due to same-origin policy.
We have added the following code in cypress.json and it worked for us:-
"chromeWebSecurity": false,
"modifyObstructiveCode": false
Thanks!

**Comment by swatidhanu1985** [comment] 2021-08-06 10:08
Hi

I am facing similar issue while trying to sign in into Nordea bankID (last step after clicking OK )which is loaded as IFrame in our application.

Console error: 
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('**https**://tunnistus-pp.telia.fi') does not match the recipient window's origin ('**https**://test.company.com').

Current config: 
"chromeWebSecurity": false

![image](https://user-images.githubusercontent.com/45289147/128494332-067da926-c970-4d97-93db-79b812dc121e.png)

@jennifer-shehane @bahmutov Would you please let me know if there is any config needs to do in Cypress?
A lot of issues specific to event triggering in iframe using Cypress.

**Comment by frbl** [comment] 2021-09-15 08:21
Same issue here, we're trying to set up an e2e test with Fitbit and strava, and both don't seem to be able to login. For strava there's no feedback (might actually be reCAPTCHA kicking in), for fitbit we get this error

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.fitbit.com') does not match the recipient window's origin (<OUR_URL>).
```

**Comment by frbl** [comment] 2021-09-15 08:21
Same issue here, we're trying to set up an e2e test with Fitbit and strava, and both don't seem to be able to login. For strava there's no feedback (might actually be reCAPTCHA kicking in), for fitbit we get this error

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.fitbit.com') does not match the recipient window's origin (<OUR_URL>).
```

**Comment by chess-octane** [comment] 2022-03-25 16:32
I was able to overcome this using:

```js
cy.window().then(($window) => {
  const messageEvent = new MessageEvent('message', {
    data: { name: 'name' },
    origin: 'http://example.com',
  });
  $window.dispatchEvent(messageEvent);
});
```

No need to change `cypress.json` at all.
