### ISSUE TITLE
cy.intercept() seemingly causing unpredictable behaviour when used in multiple tests

### ISSUE THREAD

**Issue by GCHQDeveloper911** [cypress-io/cypress#8815] opened 2020-10-12 13:13 UTC
### Current behavior
Cypress 5.3 saw route2 fixed to support intercepting multi origin domain requests. 

However, I have found that when running suites with multiple tests that invoke route2 across multiple different URLs, the behaviour of cypress becomes.... unpredictable. 

See 'Test code to reproduce' below - in that code, if I disable (using `xit`) either test1 or test2, the other test will run and pass fine. However, if I have both tests enabled, then the `cy.click` in test2 fails, with 'my first button' not found (`cy.click failed because it requires a DOM element, subject received was undefined`).

If I reverse the tests, so the test that intercepts localhost is run AFTER any / all non-local intercepts, it seems to be fine. I cannot determine if it's the (non)localhost target, or the fact that it is HTTP vs HTTPS requests.

### Desired behavior
route2 should not 'interfere' with the correct behaviour of other cypress functionality.

### Test code to reproduce
```js
describe('Some tests', => {
  let url1 = 'http://localhost/path'
  let url2 = https://another.domain/and/path'

  beforeEach(() => {
    cy.visit('mytesturl');
  })

  it('test1', => {
    cy.route2(url1, { statusCode: 500, body: { some: 'response' } });
    cy.click('my first button');
    cy.get('some element').should('exist');
  })

  it('test2', => {
    cy.route2(url2, { statusCode: 500, body: { some: 'response' } });
    cy.click('my first button');
    cy.get('some other element').should('exist');    
  })
})
```

### Versions
Cypress 5.3, Chrome 83.

**Comment by jennifer-shehane** [comment] 2020-10-15 00:08
We’ll need a reproducible example provided that we can run to see the passing/failing situation. As there seems to be some logic around the display of the button that is not given here, we’d need that to investigate. 

Please provide an example or we’ll have to close the issue.

**Comment by GCHQDeveloper911** [comment] 2020-10-16 15:09
Ok, so I'm unable to provide the code we are currently testing - give me a few days, and I'll try and come up with an alternative example! Thanks!

**Comment by GCHQDeveloper911** [comment] 2020-10-19 12:24
So... While not quite the same as described in the original ticket, I believe the following displays a fault in route2 which I suspect is probably either the root cause of, or strongly linked to the issues described above. 

The code below (based on my understanding of route2!) should intercept all POST requests to the 'blockurl' and return a 500 response instead. You'll also see a cy.wait in the beforeEach. A bit odd maybe, but done to allow you a few seconds to open DevTools on launch, and open the network tab, and apply a filter of 'collector'. 

In my experience with this code - on launching the test from the cypress runner, the POST requests do not get intercepted and return a 200 response instead - 2 other requests (that do not show a request type in DevTools) DO get intercepted, but not every time. 

Furthermore, I find that if you clear the DevTools results, and click to re-run the test (ie, within the browser window, not dropping back to the runner window) - NONE of the requests get intercepted. Re-run again, and (possibly at least!) you'll see some interceptions again.... 

I can't state 100% that the "sequence" of retrying the test is 100% accurate, but I am certain that the behaviour is not consistent, or correct. I've tried much the same with the 'POST' parameter removed to intercept ALL requests to the stated URL, and that makes little or no difference.

FWIW - Still on Chrome 83, but now on Cypress 5.4.0

```
describe('A problem with route2', function () {
  let blockurl = 'https://http-inputs-itv.splunkcloud.com/services/collector'

  beforeEach(() => {
    cy.wait(5000)
    cy.visit('https://www.itv.com')
  })

  it('blocks a url', function () {
    cy.route2('POST', blockurl, { statusCode: 503, body: { some: 'response' } });
    cy.get('li').contains('Yes Agreed!').click();
    cy.get('button.cp_button.cp_mobile-icon.cp_header-icon').click();
    cy.get('a').contains('Shows').click({force: true});
  })
})
```

**Comment by flotwig** [comment] 2020-10-19 14:26
@GCHQDeveloper911 `cy.route2` needs to be set up before your requests are made. I can see that 2 requests to `services/collector` are made before the page finishes loading. `cy.visit` waits until the page finishes loading, so your `cy.route2` will not have executed by this point.

If you want to intercept resource loads from your `cy.visit`, you need to define your `cy.route2` first:

```js
describe('A problem with route2', function () {
  let blockurl = 'https://http-inputs-itv.splunkcloud.com/services/collector'

  beforeEach(() => {
    cy.route2('POST', blockurl, { statusCode: 503, body: { some: 'response' } });
    cy.wait(5000)
    cy.visit('https://www.itv.com')
  })

  it('blocks a url', function () {
    cy.get('li').contains('Yes Agreed!').click();
    cy.get('button.cp_button.cp_mobile-icon.cp_header-icon').click();
    cy.get('a').contains('Shows').click({force: true});
  })
})
```

**Comment by GCHQDeveloper911** [comment] 2020-10-20 10:30
Thanks @flotwig - that makes sense, and helped. However.... I have a situation where I have a suite of tests, where each test 'disables' a different URL, and then checks app behaviour as appropriate. Obviously this means I can't use beforeEach, as I need to use a different URL in the call to route2 on a per test basis. No problem (at least, I think not a problem!) - just use a function instead of beforeEach, and call that function at the top of the test. This works fine.... if I only have one test. In the example below, I can disable either of the 2 tests, and just run the other fine - and I see the blocked calls in DevTools. As soon as I enable both tests, the 2nd one fails to intercept.

I was wondering if it's using a cached response, however I've tried clicking 'Disable cache' in devtools as soon as the test launches, AND added cy.clearLocalStorage() to my beforeEach.

Am I missing something, or IS there a bug in route2 here?

**Comment by flotwig** [comment] 2020-10-20 14:27
@GCHQDeveloper911 ah, yes, it is very possible that you're running into a bug with route2 that will be fixed in this PR: https://github.com/cypress-io/cypress/pull/8827

The bug is caused by HTTP keep-alive, and by the fact that (before #8827) Cypress did not intercept all HTTPS traffic (for performance). There is a bug where, if you have an existing HTTPS Keep-Alive connection to an origin, Cypress will not be able to intercept traffic to that origin until the Keep-Alive connection is no longer in use.

In the meantime, you should be able to work around the issue by pre-emptively intercepting the origins:

```js
describe('A problem with route2', function () {
  let blockurl1 = 'https://http-inputs-itv.splunkcloud.com/services/collector'
  let blockurl2 = 'https://in.hotjar.com/**'  

  beforeEach(() => {
    // workaround for https://github.com/cypress-io/cypress/issues/8815
    cy.route2('https://http-inputs-itv.spunkcloud.com')
    cy.route2('https://in.hotjar.com')
  })

  function disableRouteAndLaunch(url) {
    cy.route2(url, { statusCode: 500, body: { some: 'response' } })
    cy.wait(5000)
    cy.visit('https://www.itv.com', {
      onBeforeLoad(win) {
        cy.spy(win.console, 'warn').as('console.log')
      }
    });
  }

  it('blocks url1', function () {
    disableRouteAndLaunch(blockurl1)
    cy.get('li').contains('Yes Agreed!').click();
    cy.get('button.cp_button.cp_mobile-icon.cp_header-icon').click();
    cy.get('a').contains('Shows').click({ force: true });
  })

  it('blocks url2', function () {
    disableRouteAndLaunch(blockurl2)
    cy.get('li').contains('Yes Agreed!').click();
    cy.get('button.cp_button.cp_mobile-icon.cp_header-icon').click();
    cy.get('a').contains('Shows').click({ force: true });
  })
})
```

Let me know if this works for you @GCHQDeveloper911, if so, we can link this issue to #8827

**Comment by GCHQDeveloper911** [comment] 2020-10-23 11:17
Thanks @flotwig - That does indeed largely help. However, I'm still seeing times when stated routes aren't getting intercepted... It's taken a while to create steps that I think highlight this - but hopefully you'll find something similar... If you this this needs a separate ticket, let me know!

Using the code below, if you launch the test, and open DevTools, you'll see the 'collector' requests getting intercepted. Leaving the cypress test window open to re-run automatically, if you then change the 'block' parameter in the first test call to disableRouteAndLaunch to false, and the automatically re-running test runs with the appropriate calls not getting intercepted. All good so far. However, if you then set it back to true, and return to the re-running test, some, or all of the calls don't get intercepted. If you close the browser, and re-launch the test from the cypress runner, then once again all the calls seem to get intercepted? It's worth noting that at the end of each test, SOME requests are left in a pending state - is there a possibility of some delayed responses from a previous run interfering with the current run?

FWIW - Another thing I've noted based on the code below - in DevTools, the intercepted calls have a status of '(failed)' - which becomes '(failed) net::ERR_FAILED' when you click on one, rather than the desired 500 response - also the response view of DevTools shows 'Failed to load response data'.... 

In Summary - I *am* managing to intercept the calls, but any time I change my test code I need to completely re-launch the test to ensure a 'clean' run... but even then the stubbing isn't happening as I would expect?

Code:

```
describe('A problem with route2', function () {
  let blockurl1 = 'https://http-inputs-itv.splunkcloud.com/services/collector'
  let blockurl2 = 'https://in.hotjar.com/**'

  function disableRouteAndLaunch(url, block) {
    if (block) {
      cy.log ('INTERCEPTING ' + url)
      cy.route2(url, { statusCode: 500, body: { some: 'response' } })
    }
    cy.visit('https://www.itv.com', {
      onBeforeLoad(win) {
        cy.spy(win.console, 'warn').as('console.log')
      }
    });
  }

  beforeEach(() => {
    cy.route2('https://http-inputs-itv.spunkcloud.com')
    cy.route2('https://in.hotjar.com')
  })

  it('blocks url1', function () {
    disableRouteAndLaunch(blockurl1, true)
    cy.visit('https://www.itv.com');
    cy.get('button.cp_button').contains('Yes Agreed!').should((btn) => {if (btn) btn.click()});
    cy.get('button.cp_button.cp_mobile-icon.cp_header-icon').click();
    cy.get('a').contains('Shows').click({ force: true });
  })

  it('blocks url2', function () {
    disableRouteAndLaunch(blockurl2, true)
    cy.get('button.cp_button').contains('Yes Agreed!').should((btn) => {if (btn) btn.click()});
    cy.get('a').contains('Shows').click({ force: true });
  })
})
```
Many thanks again!

**Comment by GCHQDeveloper911** [comment] 2020-11-02 13:59
Hi @flotwig - I've just tried the above with Cypress 5.5, and I *think* the consistency of behaviour is now there, and much improved (no longer need the beforeEach block as above)... but still the output in DevTools is not showing the specified response code / message, just '(failed)'.

Would it be more appropriate to close this ticket, and raise this as a separate issue?

**Comment by jennifer-shehane** [comment] 2021-01-15 15:59
@GCHQDeveloper911 Yes please open a new issue with what you'd like to see for cy.intercept() 🙏 

Closing as resolved.

**Closed by jennifer-shehane** 2021-01-15 15:59 UTC
Labels: pkg/net-stubbing, stage: needs information
