### ISSUE TITLE
In Angular, it's very easy for dom elements to get de-attached

### ISSUE THREAD

**Issue by SDAdham** [cypress-io/cypress#17471] opened 2021-07-24 09:33 UTC
### What would you like?

Hi team

Is there  configuration variable that I can set to slow actions in cypress? Or at least the interval between:
```
cy.contains('hello').click();
// here it would auto-wait 1 second or something
cy.contains('Name').next().type('hello');
```

### Why is this needed?

In Angular, it's very easy for DOM elements to get de-attached, and that makes tests inconsistent and subject to fail
I'd have to set force: true to fix tests every once in a while and randomly, almost feels like I should just make everything forceable by default

**Comment by jennifer-shehane** [comment] 2021-07-26 13:49
You can add `cy.wait(60000)`. There's an issue for adding a pause between all commands: https://github.com/cypress-io/cypress/issues/249

Closing as duplicate of https://github.com/cypress-io/cypress/issues/7306

**Closed by jennifer-shehane** 2021-07-26 13:49 UTC

**Comment by webia1** [comment] 2021-12-18 19:31
https://github.com/cypress-io/cypress/issues/7306#issuecomment-997271455
