### ISSUE TITLE
Cypress on Authentication with microsoft login wil bipass the authentication with the ignore-frame-headerextention only on cypress open mode not on CI

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#8209] opened 2020-08-06 18:13 UTC
### Current behavior:

On authentication will only bipass the xframe header extention using below code works with `yarn run cypress open`/`npx cypress open` but never worked with `node_modules/.bin/cypress run --browser chrome` or any other commands
```js
module.exports = (on, config) => {
on("before:browser:launch", (browser, launchOptions) => {
  if (browser.name === "chrome") {
    launchOptions.args.push(
      "--disable-features=CrossSiteDocumentBlockingIfIsolating,CrossSiteDocumentBlockingAlways,IsolateOrigins,site-per-process"
    );
    launchOptions.args.push(
      "--load-extension=cypress/extensions/Ignore-X-Frame-headers_v1.1"
    );
    return launchOptions;
  }
})
};
```

### Versions
Cypress 4.12.1

**Comment by jennifer-shehane** [comment] 2020-08-07 09:16
Can this be reproduced locally when running `node_modules/.bin/cypress run --browser chrome` or is this only an issue in your CI environment?

**Comment by sindhukp** [comment] 2020-08-07 13:03
@jennifer-shehane Jennifer,

if I execute `node_modules/.bin/cypress run --browser chrome` it ask for authentication if I give the credentials and 2-factor lands to the homepage of my app and do nothing
If I execute `yarn run cypress open` and click on tests it does not ask for the authentication and bypasses the authentication to the homepage which is correct
![Screen Shot 2020-08-07 at 6 28 38 PM](https://user-images.githubusercontent.com/20899774/89647814-d28b3f80-d8db-11ea-85c1-c6000c090e4f.png)

**Comment by sindhukp** [comment] 2020-08-11 19:07
@here any of you at early response are highly appreciated.

**Comment by jennifer-shehane** [comment] 2020-08-18 06:57
Have you tried loading the extension as laid out here? https://github.com/cypress-io/cypress/issues/4220#issuecomment-649264985

In that example, you push in the local path to the extension into `launchOptions.extension` - I think this is required because if you run `cypress run`, the extension will not be installed to be referenced.

**Comment by jennifer-shehane** [comment] 2020-12-28 05:12
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-12-28 05:12 UTC
Labels: stage: awaiting response
