### ISSUE TITLE
cypress verify fails on GitHub Actions CI

### ISSUE THREAD

**Issue by mganjoo** [cypress-io/cypress#6221] opened 2020-01-22 14:58 UTC
### Current behavior:

My GitHub Actions CI pipeline has started failing at the `cypress verify` step. With `DEBUG=cypress.*` turned on, I get the following output and the `cypress verify` command exits with non-zero code:

```
2020-01-22T14:47:59.210Z cypress:cli:cli cli starts with arguments ["/opt/hostedtoolcache/node/10.18.1/x64/bin/node","/home/runner/work/alisha-and-milind-wedding/alisha-and-milind-wedding/website/node_modules/.bin/cypress","verify"]
2020-01-22T14:47:59.212Z cypress:cli NODE_OPTIONS is not set
2020-01-22T14:47:59.212Z cypress:cli:cli program parsing arguments
2020-01-22T14:47:59.215Z cypress:cli parsed cli options {}
2020-01-22T14:47:59.264Z cypress:cli verifying Cypress app
2020-01-22T14:47:59.264Z cypress:cli checking environment variables
2020-01-22T14:47:59.267Z cypress:cli checking if executable exists /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress
2020-01-22T14:47:59.273Z cypress:cli Binary is executable? : true
2020-01-22T14:47:59.274Z cypress:cli binaryDir is  /home/runner/.cache/Cypress/3.8.2/Cypress
2020-01-22T14:47:59.274Z cypress:cli Reading binary package.json from: /home/runner/.cache/Cypress/3.8.2/Cypress/resources/app/package.json
2020-01-22T14:47:59.276Z cypress:cli Found binary version 3.8.2 installed in: /home/runner/.cache/Cypress/3.8.2/Cypress
2020-01-22T14:47:59.277Z cypress:cli could not read binary_state.json file at "/home/runner/.cache/Cypress/3.8.2/binary_state.json"
2020-01-22T14:47:59.278Z cypress:cli {}
2020-01-22T14:47:59.278Z cypress:cli is Verified ? undefined
2020-01-22T14:47:59.278Z cypress:cli force verify
2020-01-22T14:47:59.278Z cypress:cli running binary verification check 3.8.2
It looks like this is your first time using Cypress: 3.8.2

25l[14:47:59]  Verifying Cypress can run /home/runner/.cache/Cypress/3.8.2/Cypress [started]
2020-01-22T14:47:59.283Z cypress:cli clearing out the verified version
2020-01-22T14:47:59.284Z cypress:cli undefined DISPLAY environment variable
2020-01-22T14:47:59.285Z cypress:cli Cypress will spawn its own Xvfb
2020-01-22T14:47:59.285Z cypress:cli needs Xvfb? true
2020-01-22T14:47:59.285Z cypress:cli Starting Xvfb
2020-01-22T14:47:59.678Z cypress:cli disabling Electron sandbox
2020-01-22T14:47:59.678Z cypress:cli running smoke test
2020-01-22T14:47:59.678Z cypress:cli using Cypress executable /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress
2020-01-22T14:47:59.678Z cypress:cli smoke test command: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=99
2020-01-22T14:47:59.678Z cypress:cli smoke test timeout 30000 ms
2020-01-22T14:47:59.730Z cypress:xvfb _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

2020-01-22T14:48:05.967Z cypress:cli Smoke test failed: { Error: Command failed: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=99


    at makeError (/home/runner/work/alisha-and-milind-wedding/alisha-and-milind-wedding/website/node_modules/cypress/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/runner/work/alisha-and-milind-wedding/alisha-and-milind-wedding/website/node_modules/cypress/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: null,
  stdout: '',
  stderr: '',
  failed: true,
  signal: 'SIGSEGV',
  cmd:
   '/home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=99',
  timedOut: false,
  killed: false }
2020-01-22T14:48:05.968Z cypress:cli error message: Command failed: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=99


2020-01-22T14:48:05.973Z cypress:cli Stopping Xvfb
[14:48:06]  Verifying Cypress can run /home/runner/.cache/Cypress/3.8.2/Cypress [failed]
25hCypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=99

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.2
25h
```

### Desired behavior:

The `cypress verify` command should run successfully.

### Test code to reproduce

Running

```
$(npm bin)/cypress verify
```

within the GitHub Actions CI environment triggers this error.

### Versions

This error does not seem to be tied to a specific Cypress version (the `verify` command was working successfully on Cypress 3.8.2 even before it stopped working)

**Comment by glambert** [comment] 2020-01-22 16:13
FYI @bahmutov just posted the following, which fixes the issue: https://github.com/cypress-io/github-action#important

>We are getting reports that Cypress has suddenly started crashing when running on ubuntu-latest OS. Seems, GH Actions have switched from 16.04 to 18.04 overnight, and are having a xvfb issue. Please wor around this problem by using runs-on: ubuntu-16.04 image.

**Comment by mganjoo** [comment] 2020-01-22 16:32
@glambert That seems to have fixed the issue. Thank you!

**Comment by bahmutov** [comment] 2020-01-22 21:19
Closing as duplicate of https://github.com/cypress-io/cypress/issues/6184 - see work arounds there as well

**Closed by bahmutov** 2020-01-22 21:19 UTC
