### ISSUE TITLE
cy.visit() loads blank page

### ISSUE THREAD

**Issue by MohamedElmowafy** [cypress-io/cypress#16636] opened 2021-05-23 12:08 UTC
Hi

I am experiencing a problem with cypress that it doesn't launch my test env url, it loads the blank page for cy.visit('/').

![cypress_err01](https://user-images.githubusercontent.com/16302726/119259576-f9530200-bbdf-11eb-99c0-c90571f2da64.png)

### Test code to reproduce
```javascript
/// <reference types="cypress"/>
it('should navigate to the TodoMVC App',()=>{
cy.visit('https://www.google.com/')    
})
```

**Version**
I am using the latest version 7.3.0

**Comment by sainthkh** [comment] 2021-07-26 06:00
Duplicate of #7664

**Closed by sainthkh** 2021-07-26 06:00 UTC
