### ISSUE TITLE
Cypress version 4.7.0 Headless Mode File Download Issue with Chrome

### ISSUE THREAD

**Issue by osmnorhn** [cypress-io/cypress#7576] opened 2020-06-03 13:48 UTC
### Current behavior:
When trying to run cypress in headless mode with browser Chrome with the command 
`"cypress run --headless -b chrome"`, in tests which are testing some file download operations, cypress is doing nothing and file cannot be found under the default download location.
 
If the test run is started in headless mode with electron file save popup is shown and if you are clicking the button manually it downloads the file.

I assume download functionality for chrome is not implemented in cypress headless mode.

My cypress test is just calling button click and in the click function it is calling download function defined below which is imported by pdfmake library.
https://pdfmake.github.io/docs/

In Google if the settings in Chrome Settings -> Advanced -> Downloads -> "Ask where to save each file" before downloading as "false" it downloads the file and works correctly in the UI mode of cypress. 

I have tried in Edge chromium too, it was not working. I am running the tests on MacOS.

### Desired behavior:

Can it be worked like UI version when you are downloading a file. 
If "Ask where to save each file" is set as false, instead of doing nothing, it should download a file when I am calling a download function.

### Test code to reproduce

```js
download() {
    pdfmake.createPdf(this.documentDefinition).download(nameOfFile, downloadCompleteCallBack);
}
```

**Comment by jennifer-shehane** [comment] 2020-06-04 08:40
File download is not fully supported in Cypress out of the box. I suggest looking at workarounds described in https://github.com/cypress-io/cypress/issues/949

Duplicate of #949

**Closed by jennifer-shehane** 2020-06-04 08:40 UTC

**Comment by jennifer-shehane** [comment] 2021-01-20 04:34
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
