### ISSUE TITLE
Stop cypress from downloading & unpacking every time

### ISSUE THREAD

**Issue by tschaka1904** [cypress-io/cypress#1363] opened 2018-02-22 20:17 UTC
### Is this a Feature or Bug?
Bug

### Current behavior:
When I run `npm install cypress` everything work nicely 👍 But when I redo the command it is not picking up on the fact that it is already installed and unpacked, which can cost a lot of time.

### Desired behavior:
Cypress not downloading and unpacking itself when there is already a cypress folder.

### How to reproduce:
`npm install cypress` on an existing project where cypress is installed already.

**Comment by Konstruktour** [comment] 2018-02-23 07:41
Recommendation: use yarn - dont have the problem there.

**Comment by brian-mann** [comment] 2018-02-23 17:46
@tschaka1904 I don't think there's anything we can do about this. `npm` nukes the `node_modules/cypress` folder on reinstall which means it lost the binary.

We do have a proposal open for caching the binary outside of the `node_modules` folder which would prevent needing to re-download and unzip it if it's already been cached.

I'm closing this as a duplicate of https://github.com/cypress-io/cypress/issues/1300 and https://github.com/cypress-io/cypress/issues/1233.

**Closed by brian-mann** 2018-02-23 17:46 UTC
Labels: type: duplicate

**Comment by tschaka1904** [comment] 2018-02-26 10:39
I've switched to yarn, which saved that issue. 👍

**Comment by brandonmp** [comment] 2018-04-07 22:24
wanted to chime-in since I landed here trying to figure out why _yarn_ was rebuilding cypress from scratch every time I ran `yarn add x` :/  

though it looks like a fix for that [should be landing in yarn soon](https://github.com/yarnpkg/yarn/issues/932)

**Comment by mathiasrw** [comment] 2019-07-15 01:58
Still having this issue even using yarn. https://github.com/yarnpkg/yarn/issues/932#issuecomment-385510471 says 

> if a package deletes it's own files (why oh why do they do these things 😿) and yarn doesn't track that anywhere (we track what files are created or modified), so it just thinks the package is missing files and rebuilds it.

Could that be the key?
