### ISSUE TITLE
Getting [ERR_INVALID_ARG_TYPE] error with cy.intercept()

### ISSUE THREAD

**Issue by far11ven** [cypress-io/cypress#16145] opened 2021-04-22 16:38 UTC
### Current behavior

I'm using a custom command for file upload:

```/**
 * This Command uploads a file to a given URL endpoint
 * 
 * @param {String} url - full URL of the upload endpoint
 * @param {String} formData - formaData to be passed as body to endpoint
 */
 Cypress.Commands.add("uploadFile", (url, formData) => {
  cy.intercept(url)
    .as("uploadFileRequest");
  cy.window().then(window => {
      var xhr = new window.XMLHttpRequest();
      xhr.open("POST", url);
      xhr.send(formData);
    })
  return cy.wait("@uploadFileRequest");
});
```
When I call this command with proper params, Cypress UI crashes and exits with the following error:

### Test code to reproduce
```
GET /__cypress/tests?p=cypress%5Csupport%5Cindex.js 200 5592.838 ms - -
GET /__cypress/tests?p=cypress%5Cintegration%5Cfeatures%5Cextra.feature 200 6125.957 ms - -
[my-qa-automation] Created URL : /trainer/api/v2/collections/091006ca-6570-422e-af4a-638502597263/documents
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:1496:27)
    at C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:545:23)
    at Immediate._onImmediate (C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:1496:27)
    at C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:545:23)
    at Immediate._onImmediate (C:\Users\Kushal\AppData\Local\Cypress\Cache\7.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:578:7)
    at processImmediate (internal/timers.js:461:21)

```

### Versions

Cypress: 7.0.0

**Comment by jennifer-shehane** [comment] 2021-04-22 18:09
Duplicate of https://github.com/cypress-io/cypress/issues/15901 We have a fix for this that will be included in our next release.

**Closed by jennifer-shehane** 2021-04-22 18:09 UTC
