### ISSUE TITLE
unable to select searched element from autocomplete 

### ISSUE THREAD

**Issue by SornaSundaram** [cypress-io/cypress#6716] opened 2020-03-13 08:34 UTC
### Current behavior:

` cy.get('[data-testid="select-patient"]').click().type(dataObject['patientId']+'{downarrow}{enter}',{force:true});`

**Comment by jennifer-shehane** [comment] 2020-03-13 09:49
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

**Closed by jennifer-shehane** 2020-03-13 09:49 UTC

**Comment by SornaSundaram** [comment] 2020-03-13 11:02
Current behavior
this is the code i use to search a vuetify autocomplete. 
cy.get('[data-testid="select-patient"]').click().focused().type(patientId+'{downarrow}{enter}',{force:true});
cy.get('[data-testid="select-patient"]').should('have.value',patientId);
expected behaviour is that after finding the element it should be selected in the autocomplete.
Current behavior:
after finding the element id is not selected in the autocomplete.
but this code works properly as expected
cy.get('[data-testid="select-patient"]').click().focused().type(patientId+'{downarrow}{enter}',{force:true});
cy.wait(3000); 
cy.get('[data-testid="select-patient"]').should('have.value',patientId);

but adding arbitrary wait is a bad practice mentioned in your guidelines. so how can i overcome this delay issue? 

Test code :
cy.get('[data-testid="select-patient"]').click().focused().type(patientId+'{downarrow}{enter}',{force:true});
cy.get('[data-testid="select-patient"]').should('have.value',patientId);

**Comment by jennifer-shehane** [comment] 2020-03-16 09:36
@SornaSundaram Please provide the HTML or test website to run the Cypress tests you wrote above against. I can't run the tests provided without the HTML or website to see what is happening, then we will consider reopening. Do not open a new issue for this.

**Comment by haroldo-ok** [comment] 2021-06-28 17:22
The problem here seems to be that Vuetify is only rendering the visible items; since the others aren't rendered, the Cypress command will fail.

**Comment by ashika29** [comment] 2021-08-23 03:14
@jennifer-shehane  Hi Jennifer, I'm facing the same having run a cypress test for selecting a value from the material-ui autocomplete after typing some value in the autocomplete field. I did visit all related issues but I couldn't find a way to resolve this. Could you please suggest a workaround?

**Comment by Nikeleos** [comment] 2021-09-08 15:54
Actually, the only workaround I have is using 'force: true' and so disabling warning rule.

**Comment by Roberto-Stanley** [comment] 2024-08-03 18:33
I had the same issue, but I could resolve it, here is the code
`cy.get('form').get('.v-autocomplete .v-field__field').click({ force: true }).type('u{downArrow}{enter}');`
This worked for me.
