### ISSUE TITLE
Cypress loads wrong page after click

### ISSUE THREAD

**Issue by WilliamCham** [cypress-io/cypress#5140] opened 2019-09-13 06:05 UTC
I'm currently using Cypress to test my website to see if switches languages. The test is simply to go into the website, have it click the langauge button to switch language, then click on the contact page to see if the language is still the same. 

The problem is that when I do the test, Cypress shows me that when it clicks on the contact page, it gives me the English instead of my desired language page. If I try to replicate this test by hand, I can never get it to show up the English page. 

This is before I click anything, the page has already switched langauge and I've assert that it has the correct href

![Screenshot (25)](https://user-images.githubusercontent.com/12544626/64840638-6601b500-d626-11e9-81ef-5008998dcc4c.png)

This is what it looks after I've ran the test. It's reverted back to English and the URL no longer has a '/kh' in it

![Screenshot (26)](https://user-images.githubusercontent.com/12544626/64840708-a3664280-d626-11e9-80bf-8493a3f350fe.png)

This is the page that it's suppose to show me. It's the contact page but in the correct language.

![Screenshot (27)](https://user-images.githubusercontent.com/12544626/64840793-e2949380-d626-11e9-8eb8-e1af976d7a32.png)

### Steps to reproduce: (app code and test code)
The code is fairly basic, nothing complicated

```js
describe ('sala enrollment first test', function() {
  it('language switch or nah', function() {

    cy.visit('https://salaenrollment.com/')

    cy.contains('ភាសាខ្មែរ').click()
      .url().should('include', '/kh')

    cy.contains('ទំនាក់ទំនង').should('have.attr', 'href', '/kh/contact')
      .click()
  }) 
})
```

ភាសាខ្មែរ is the language i want
ទំនាក់ទំនង is contact in my language

**Comment by ryan-snyder** [comment] 2019-09-19 17:21
I'm unsure what you're asking here. Or what you are looking for. If I copy your code and run it, it seems to work every time. Out of curiosity, what is the content of your `cypress.json` file?

**Comment by jennifer-shehane** [comment] 2019-09-19 20:22
As @ryan-snyder noted, I cannot create what you are describing from the code provided. Closing as cannot reproduce.

**Closed by jennifer-shehane** 2019-09-19 20:22 UTC
