### ISSUE TITLE
Ads are not loading when launching test with "cypress run" commands.

### ISSUE THREAD

**Issue by samixchoumi** [cypress-io/cypress#26879] opened 2023-05-30 09:19 UTC
### Current behavior

When I open a link, I should see ads.

So for the moment, when I don't use Cypress and I got to the desired link, I see my Ads.
When I launch the test from `cypress open` commands, I see my Ads.
But, When I launch the test from `cypress run` commands, it seem that the Ads doesn't load (not found on the HTML, and proven by the screenshot failure).

I found a similar issues on stackoverflow, but no answer given : https://stackoverflow.com/questions/74758787/ads-are-not-loading-in-cypress-v10-9-0

### Desired behavior

When I launch the test from `cypress run` commands, the Ads should load.

### Test code to reproduce

I can't send a repo because we use a VPN to access our site. When going through the page, we made a callback to gets the wanted ads.
The page is hosted on a server that we can access using FileZilla (don't know if it's important).
Normally the page use http instead of https, but it works with both cases using `cypress open` commands..

### Cypress Version

12.12.0

### Node version

v18.12.1

### Operating System

macOS 13.4

### Debug Logs

```shell
No failing logs, just the ads doesn\'t appear.
I used `debugger`, nothing appeared too.
```

### Other

_It seem to works using `electron`, but it fail using `chrome`. We thought that it was linked to some **ads blocker** but it fail on the **CI too** (and we haven't any ads blocker on our CI)_

**Comment by nagash77** [comment] 2023-05-30 13:21
Hi @samixchoumi Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by samixchoumi** [comment] 2023-05-31 08:09
Hello @nagash77, thanks for your answer, it still happen on `chrome` browser, i tried with `electron` browser and it seem to work. 
Asked one of my superior, not possible to create a test project because of some credential used.

**Comment by nagash77** [comment] 2023-06-01 13:04
Hi @samixchoumi , that is interesting that electron works but chrome does not.  I have a couple of ideas to try to see if we can suss out what is going on.
- Have you tried in firefox to see how that behaves?  
- Can you describe what triggers the ads to display on your site?  
- Does it look for cookies to be set by logging in?  
- Are there CSP directives associated with the ads being displayed?
- Have you tried running with [`testIsolation`](https://docs.cypress.io/guides/references/configuration#e2e) turned off?

**Comment by samixchoumi** [comment] 2023-06-01 13:59
- Have you tried in firefox to see how that behaves? 

> It doesn't work either on Firefox.

- Can you describe what triggers the ads to display on your site? 

> When going to our page to see the ads, an ad-call is made. The script to render the ad look like that : 
> ```
> sas.cmd.push(function () {
>     sas.render('wantedIdNumber');
> });
> ```

- Does it look for cookies to be set by logging in? 

> No, we use `cy.session()` but no cookies.

- Are there CSP directives associated with the ads being displayed?

> It seem that it can have CORS.

- Have you tried running with [testIsolation](https://docs.cypress.io/guides/references/configuration#e2e) turned off?

> Nothing change using this option.

**Comment by nagash77** [comment] 2023-06-07 12:05
Hi @samixchoumi , unfortunately without a reproducible example we wont be able to investigate further.  I am going to close this issue until we can get a reproducible example of this problem.

It might be worth checking out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.  Someone on there might have ideas on ways you can narrow down the cause or provide a reproducible example.

**Closed as not planned by nagash77** 2023-06-07 12:05 UTC
