### ISSUE TITLE
🐛 dev server vite 2.2.3 dynamic import are not using path aliases

### ISSUE THREAD

**Issue by hinogi** [cypress-io/cypress#22390] opened 2022-06-18 13:49 UTC
### Current behavior

`importsToLoad` dynamic import of the spec file fails because it does not replace the path alias given by vite in the dynamic import.

https://github.com/cypress-io/cypress/blob/e5385fe413ae866985c04dfc991f8378673c6159/npm/vite-dev-server/client/initCypressTests.js#L9

This results in a TypeError when it resolves.

### Desired behavior

When vite is used and path aliases are given, check all kinds of imports or references to files with the according path alias.

### Test code to reproduce

`src/components/QuasarButton.vue`
```html
<template>
  <input
    data-cy="button"
    label="test emit"
    @click="$emit('test')"
  />
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'QuasarButton',
  emits: ['test'],
});
```

`src/components/__test__/QuasarButton.spec.ts`
```
// __test__/QuasarButton.spec.ts
```
and a path alias for `src` pointing to src

### Cypress Version

10.1.0

### Other

The content does not really matter because cypress will not reach any of it because vite has found spec files and is providing the paths with knowing the path alias for it but not resolving it but initCypresssTests is blind to it and will fail trying to dynamically import from the path given by vite.

**Comment by lmiller1990** [comment] 2022-06-22 01:32
Hi, thanks for the bug report. Quasar is super nice to work with.

Just to clarify, you want to do something like:

```ts
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': 'src'
    }
  }
})
```

And then type `import QuasarButton from '@components/QuasarButton.vue'`?

**Comment by hinogi** [comment] 2022-06-23 06:14
The path alias yes but the spec files are found by cypress itself, it is about spec files

**Comment by IlCallo** [comment] 2022-06-23 15:45
Adding a bit more context: @hinogi is trying to add support for Cypress 10 into our Cypress App Extension
You can find the draft PR here: https://github.com/quasarframework/quasar-testing/pull/259

**Comment by lmiller1990** [comment] 2022-06-24 01:00
Hello @IlCallo! Long time no talk.

I looked at the draft PR but I think I'm still missing something.

> The path alias yes but the spec files are found by cypress itself, it is about spec files

Can you point me some code that doesn't work (or even make a minimal reproduction)? I looked at the draft PR but I do not see any obvious `@` alias that isn't working. Also, the initial post doesn't include enough:

> src/components/__test__/QuasarButton.spec.ts
> // __test__/QuasarButton.spec.ts
> and a path alias for src pointing to src

What should I do to "and a path alias for src pointing to src"? I think I am missing something,

**Comment by hinogi** [comment] 2022-07-04 17:59
That problem also covers imports in spec files because those paths get used in dynamic imports as is disregarding present path aliases.

**Comment by lmiller1990** [comment] 2022-07-11 02:43
I understand now. A minimal reproduction would be great.

**Comment by lmiller1990** [comment] 2022-07-12 03:36
Seems this is also documented as a Vite problem: https://github.com/vitejs/vite/discussions/7611#discussioncomment-2966823
Maybe fixed: https://github.com/vitejs/vite/pull/7756 so it should be fine here, weird?

**Comment by hinogi** [comment] 2022-07-16 14:00
As far as I can see it, the issue is not fixed in vite 3.

**Comment by IlCallo** [comment] 2022-07-19 16:36
I'm taking a shot with the Cypress 10 migration and I can understand why @hinogi got stuck
I'm pretty sure Vite path aliases actually work and the problem is on our side instead

Quasar did quite some stuff behind the curtains to provide the best DX possible, and this involved using many packages which version has been bumped and are now included into cypress binary (`@cypress/vue`, `@cypress/vite-dev-server`, etc)

He forgot to bump those, so that's probably the problem here, but that's understandable: I saw there are A LOT of things we'll need to change/automate for our users during the migration, I barely lost myself too into all of them

I think I almost got to a working repo, after adapting to the new `devServer.xxxConfig` syntax
Right now I got stuck due to Quasar webpack/vite config being exported as an async function, but Cypress doesn't really seem to like it, so I'm trying to understand if that's the case and I shall revert to export a `devServer` function instead

[quasarframework/quasar-testing@`9dc9c43` (#259)](https://github.com/quasarframework/quasar-testing/pull/259/commits/9dc9c43c5f23ad7df1351b2ffe443f7a82c8b6d0#diff-94f3e3027d935365a72c354e804b5f8d6cea607184bc169b23e2af047953d364R2-R4)

@lmiller1990 any hints?
Some more precise questions:
- do Cypress expect a function into the `webpackConfig` option or the result of that function? Or both?
- do Cypress support async execution of `cypress.config.ts`? 
- do `devServer` function signature support async functions?

If you don't know right away, no problem, I can somehow dig into Cypress code and find it out by myself
I probably won't be able to complete and release the new version before mid-August anyway, since I'm going to be on vacation in a few days 😅

**Comment by lmiller1990** [comment] 2022-07-24 23:58
> do Cypress expect a function into the webpackConfig option or the result of that function? Or both?

Looks like you should pass in an object, so the result: https://github.com/cypress-io/cypress/blob/develop/system-tests/project-fixtures/next/cypress.config.js#L9-L14

> do Cypress support async execution of cypress.config.ts?

Good question, I actually have no idea, but why would you want to declare `cypress.config.ts` to be async? I might be missing something here.

> do devServer function signature support async functions?

I think this should work just fine. Eg:

```js
import { devServer } from '@cypress/webpack-dev-server'

export default defineConfig({
  component: {
    devServer: async (devServerOptions) => devServer({
      ...devServerOptions,
      framework: 'vue',
    }),
  }
})
```

If any of these things don't work how you expect, we can definitely and quickly make non-breaking changes to support frameworks like Quasar. Making it easy to add Cypress to frameworks is important.

**Comment by IlCallo** [comment] 2022-08-08 15:10
> Good question, I actually have no idea, but why would you want to declare cypress.config.ts to be async? I might be missing something here.

We extract the webpack and Vite config from Quasar, but to detect which bundler we're using we need to import the package.json via an async call
We then do another async call to the package itself (`@quasar/app-webpack` or `@quasar/app-vite`) to generate and extract the config
We aren't able to get it in a synchronous way, so the only other option would be to go for the `devServer` route, which is a bit more complex

Would it be too much of an effort to support an async config for cypress, or at least to support a promise for `webpackConfig`/`viteConfig` options?

**Comment by hinogi** [comment] 2022-08-08 18:29
I made some progress with the suggestions of @lmiller1990 This seems to work so far, now @IlCallo has to figure out some stuff for me I guess :D

```ts
import { defineConfig } from 'cypress';
import { quasarWebpackConfig } from '@quasar/quasar-app-extension-testing-e2e-cypress/cct-dev-server';
import { devServer } from '@cypress/webpack-dev-server';


export default defineConfig({
  fixturesFolder: 'test/cypress/fixtures',
  screenshotsFolder: 'test/cypress/screenshots',
  videosFolder: 'test/cypress/videos',
  video: true,
  e2e: {
    baseUrl: 'http://localhost:8080/',
    specPattern: 'test/cypress/integration/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'test/cypress/support/e2e.ts',
  },
  component: {
    supportFile: 'test/cypress/support/component.ts',
    specPattern: 'src/**/*.spec.{js,jsx,ts,tsx}',
    devServer: async (devServerOptions) => {
      return devServer({
        ...devServerOptions,
        framework: 'vue',
        webpackConfig: await quasarWebpackConfig(),
      });
    },
    indexHtmlFile: 'test/cypress/support/component-index.html',
  },
});
```

**Comment by lmiller1990** [comment] 2022-08-09 01:17
Nice, lmk if you need anything on my end.

**Comment by IlCallo** [comment] 2022-08-09 09:18
> Would it be too much of an effort to support an async config for cypress, or at least to support a promise for `webpackConfig`/`viteConfig` options?

This would help us, as we wouldn't need to add `@cypress/webpack-dev-server`/`@cypress/vite-dev-server` dependencies ourselves
Anyway we'll try to move on and release an alpha using `devServer` option instead

**Comment by lmiller1990** [comment] 2022-08-11 03:47
> Would it be too much of an effort to support an async config for cypress, or at least to support a promise for webpackConfig/viteConfig options?

I am not sure about an `async config` for Cypress. We can definitely do an `async` function for `webpackConfig` and `viteConfig`. Maybe we can do:

```ts
defineConfig({
  component: {
    devServer: {
      viteConfig: async (initialConfig) => {
        const overrides = await something()
        return {...initialConfig, ...overrides }
      })
    }
  }
})
```

Let me take a look.

**Comment by hinogi** [comment] 2022-08-11 06:25
> ```js
> viteConfig: async (baseConfig) => {
>   const overrides = await something()
>   return {...baseConfig, ...overrides }
> })
> ```

That was pretty much my first attempt, without async/await, with the then quasar implementation.

**Comment by IlCallo** [comment] 2022-08-11 08:25
Yep, that would be pretty useful as we wouldn't have to manage `@cypress/webpack-dev-server`/`@cypress/vite-dev-server` ourselves 😁 

At that point we would just expose 2 distinct functions returing a promise for webpack/vite config and setting up Cypress would be cleaner and easier for the user :)

**Comment by lmiller1990** [comment] 2022-08-11 23:18
Ok, will look at doing this one. I will track it here: https://github.com/cypress-io/cypress/issues/23302

**Comment by IlCallo** [comment] 2022-08-16 10:05
I just tried the `devServer` route, but apparently that's not viable as well, at least not for TS projects

![image](https://user-images.githubusercontent.com/10036108/184853006-6db309bf-e426-4893-a7f5-4d5b512d69b6.png)
From what I understood, `@cypress/webpack-dev-server` is meant to be bundled with Cypress, but it isn't re-exporting the types

At the same time, if I try to install `@cypress/webpack-dev-server` as a standalone package I get errors about `html-webpack-plugin` not being present. This seems due to the package renaming it to have both a webpack v4 and v5 dependency in the same project to support both, but Quasar then cannot resolve it of course as the name isn't the one it expects

**Comment by lmiller1990** [comment] 2022-08-16 23:22
`@cypress/webpack-dev-server` should be usable in a stand-alone fashion, too, I know some people are using it like this. I am not sure if they just hacked around the types.

Some info on `html-plugin-webpack` situation: https://github.com/cypress-io/cypress/issues/23334

We are trying to resolve this, it's a little messy, if you want to hack into this more than happy to facilitate a fast review and release. Enabling third parties to build stuff with the dev servers is important to me!

**Comment by IlCallo** [comment] 2022-08-17 08:33
I think the problem is that Quasar needs `html-plugin-webpack` to work, but apparently `@cypress/webpack-dev-server` hijacks the dependency and change its name, making Quasar unable to find it at runtime
My supposition is that `@cypress/webpack-dev-server` is surely usable as standalone package, until the project actually requires `html-plugin-webpack` to work, and the problem appears only with some package managers (yarn 1 for sure)

Unluckily we won't be able to make Quasar "yarn 2-friendly" and drop yarn 1 support before Quasar 3 major version, which will probably happen late next year 😅 

Not sure I have the bandwidth to work on it right now, but I'll try as soon as I free up a bit

**Comment by lmiller1990** [comment] 2022-08-19 08:25
Going to carry on discussion in #23334

**Comment by lmiller1990** [comment] 2022-08-30 03:52
I am working on something in this area: https://github.com/cypress-io/cypress/pull/23605

**Comment by lmiller1990** [comment] 2022-09-22 04:11
https://github.com/cypress-io/cypress/pull/23605 landed, it'll be in the next release, I hope this helps!

We can keep working on this, I want to enable third parties as much as possible.

**Comment by IlCallo** [comment] 2022-09-22 12:39
Nice, we'll try this out as soon as new version is released!

**Comment by IlCallo** [comment] 2022-10-11 16:38
I'm back at it 😁 
Seems like the support for async webpack config did the trick, so this issue can be closed
We're now dealing with another problem, but I'll open a dedicated issue about it

**Closed** 2022-10-31 01:45 UTC
Labels: stage: backlog, npm: @cypress/vite-dev-server, CT
