### ISSUE TITLE
Test retries on "run mode" are not available in combination with property "reporter": "mocha-multi-reporters" or "reporter": "cypress-multi-reporters" 

### ISSUE THREAD

**Issue by izydorekjakub** [cypress-io/cypress#8474] opened 2020-09-02 10:18 UTC
### Current behavior:

Test retries in run mode are not available in combination with property "reporter": "mocha-multi-reporters",

### Desired behavior:

Test retries in run mode are  available in combination with property "reporter": "mocha-multi-reporters" and "reporterOptions" property.

### Test code to reproduce

```json
//cypress.json

{
    "retries": {
        "runMode": 1,
        "openMode": 3
      },
     "reporter": "mocha-multi-reporters",
     "reporterOptions": {
         "configFile": "reporter-config.json"
     }
}
```
or

```json
//cypress.json

{
    "retries": {
        "runMode": 1,
        "openMode": 3
      },
     "reporter": "cypress-multi-reporters",
     "reporterOptions": {
         "configFile": "reporter-config.json"
     }
}
```

```json
//reporter-config.json

{
    "reporterEnabled": "mochawesome",
    "reporterOptions": {
        "overwrite": false,
        "reportDir": "./cypress/reports"
    }
}
```

When we remove the property "reporter" retries are working in run mode.
In Open mode everyfing is ok.

### Versions

    "cypress": "^5.1.0",
    "mocha": "^8.0.1",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^6.1.1",
    "mochawesome-merge": "^4.1.0",
    "cypress-multi-reporters": "^1.4.0",

**Comment by gustaferiksson** [comment] 2020-09-02 15:46
Cypress logs retries only with the 'standard' `spec` reporter. Opened an issue about it last week (#8413) and since it won't fix it I came up with this super hacky way to print retries
```js
// support/index.js

Cypress.on('test:before:run:async', (test, runnable) => {
  const indent = '  '.repeat(runnable.titlePath().length)
  const message = `${indent}(Attempt ${test.currentRetry} of ${test.retries + 1}) ${test.title}`
  if (test.currentRetry !== 0 && Cypress.config('reporter') !== 'spec') {
    cy.task('log', message, { log: false })
  }
})
```
```js
// plugins/index.js

module.exports = (on, config) => {

  on('task', {
    log(message) {
      console.log(message)
      return null
    }
  })

}
```

**Comment by you1anna** [comment] 2020-09-03 11:29
Also experiencing this issue.

**Comment by nalmabrcom** [comment] 2020-10-13 08:44
I'm experiencing this issue with the basic `mochawesome` reporter. 
```    "reporter": "mochawesome",
    "reporterOptions": {
      "charts": true,
      "overwrite": false,
      "html": true,
      "json": false,
      "reportDir": "cypress/report/mochawesome-report"
    },```

**Comment by jennifer-shehane** [comment] 2020-10-28 08:00
I'm going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/8413

**Closed by jennifer-shehane** 2020-10-28 08:00 UTC
Labels: topic: test retries ♻️, v5.0.0 :bug:
