### ISSUE TITLE
Cypress scrolls very slow and throws error when attempting to click element that should be scrolled to

### ISSUE THREAD

**Issue by reyisaacm** [cypress-io/cypress#5886] opened 2019-12-05 09:09 UTC
### Current behavior:
Cypress scrolls very slowly on 3.7.0 which result on timeout on most tests. If we press the stop button, cypress will instantly scroll to the desired object.
[version 3.7.0.zip](https://github.com/cypress-io/cypress/files/3925894/version.3.7.0.zip)

### Desired behavior:
Scroll instantly just like on 3.2.0
[version 3.2.0.zip](https://github.com/cypress-io/cypress/files/3925907/version.3.2.0.zip)

### Steps to reproduce: (app code and test code)
```js
it('shows correct data', () => {
    cy.visit('https://developer.thebigbox.id/api')
    cy.get('#all_categorize').children().should('have.length', 8).pause()
    cy.get('.fa-angle-left').parent().parent().should('have.class', 'disabled-page-button')
    cy.get('.fa-angle-right').parent().parent().should('have.not.class', 'disabled-page-button')
    cy.get('.fa-angle-right').parent().click()
    cy.get('#all_categorize').children().should('have.length', 8)
    cy.get('.fa-angle-left').parent().parent().should('have.not.class', 'disabled-page-button')
    cy.get('.fa-angle-right').parent().parent().should('have.not.class', 'disabled-page-button')
    cy.get('.fa-angle-right').parent().click()
    cy.get('#all_categorize').children().should('have.length', 3)
    cy.get('.fa-angle-left').parent().parent().should('have.not.class', 'disabled-page-button')
    cy.get('.fa-angle-right').parent().parent().should('have.class', 'disabled-page-button')
  })
```

### Versions
Cypress 3.7.0
Linux Mint 19.2

**Comment by jennifer-shehane** [comment] 2019-12-05 10:50
@reyisaacm These video files will not play for me. Can you provide another link to a video and gif that is playable? Thanks. 

This is the behavior I am seeing, with no change from 3.2.0 and 3.7.0.

## 3.2.0

![](http://g.recordit.co/kw9oYUK9tG.gif)

## 3.7.0

![](http://g.recordit.co/w4FfND4hA9.gif)

Sometimes there will be a 'scroll' and sometimes when I ran there would not be a scroll, not sure why sometimes it happens and sometimes it doesn't. 

## Scroll behavior (regardless of version of Cypress)

![](http://g.recordit.co/WrNvv1JGlP.gif)

I suspect this is happening due to this issue involving having `scroll-behavior: smooth` in your css somewhere. Can you confirm? https://github.com/cypress-io/cypress/issues/3200

**Comment by reyisaacm** [comment] 2019-12-06 02:06
hi @jennifer-shehane thanks for replying
below is the gif version of the videos

3.7.0
![3 7 0](https://user-images.githubusercontent.com/4222214/70289389-2bfc1580-1807-11ea-9f04-945a72f2b6b7.gif)

3.2.0
![3 2 0](https://user-images.githubusercontent.com/4222214/70289402-33bbba00-1807-11ea-829a-2f866f3031c5.gif)

from the screenshot we can see that on 3.7.0 the page barely scrolls at all or very very slow, and only when i press the stop button the page scrolls to the desired object.
on 3.2.0 it scrolled instantly

and yes we have the scroll-behaviour:smooth in our css code

**Comment by AtofStryker** [comment] 2020-01-04 16:40
> Cypress scrolls very slowly on 3.7.0 which result on timeout on most tests. If we press the stop button, cypress will instantly scroll to the desired object.

I am also noticing this same behavior on Mac OS 10.14. Seems to be problematic on/after version `3.5`. `3.4.1` works fine for me with Electron 61. Issue still persists with Chrome 79.

**Comment by AtofStryker** [comment] 2020-01-10 02:26
I am confirming on my end that this is indeed related to `scroll-behavior: smooth`. https://github.com/cypress-io/cypress/issues/3200 would solve our issues

**Comment by jennifer-shehane** [comment] 2020-07-07 09:31
Duplicate of #3200

**Closed by jennifer-shehane** 2020-07-07 09:31 UTC
Labels: stage: awaiting response
