### ISSUE TITLE
Cypress-5.1.0 : Failed to generate the video

### ISSUE THREAD

**Issue by AkramPasha** [cypress-io/cypress#9390] opened 2020-12-01 09:23 UTC
Hi ,

When a automation suite is executed , for some of the test case getting following error while generating the Video.
Even if the test case is pass.

This error is not consistent, Out of 'n' number of spec file one or the other test case will get this error to generate the video.
```
cypress version - 5.1.0
==========================================================================
Warning: We failed processing this video.

This error will not alter the exit code.

TimeoutError: operation timed out
    at afterTimeout (<path>\Cypress\Cache\5.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (<path>\Cypress\Cache\5.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\timers.js:76:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
![image](https://user-images.githubusercontent.com/17572477/100733524-52da3100-33f4-11eb-89d4-498a58a2fb9d.png)

**Comment by bahmutov** [comment] 2020-12-01 15:37
Please try the later version like 6.0.1

**Comment by jennifer-shehane** [comment] 2020-12-01 15:48
When opening a pull request, please fill out the [pull request template](https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md) next time. 

And yes, also try updating to latest, your issue may already be fixed. 

Which browser is this error occurring on?

**Comment by AkramPasha** [comment] 2020-12-01 17:18
@jennifer-shehane  Thanks for your reply,
I have updated the Cypress for latest version - 6.0.1,Found the same error.
The error occurring in - chrome  86.0.4240.198

**Comment by stick710** [comment] 2020-12-03 09:53
Also you can update your Chrome on 87

**Comment by AkramPasha** [comment] 2020-12-03 12:47
@stick710 , Same issue with chrome - 87.0.4280.88 .

**Comment by jennifer-shehane** [comment] 2020-12-04 08:47
Can you provide a reproducible example? If this is reliably happening every time, it's likely something involving your tests. 

We have in the past seen a similar situation when specfiles have a short runtime. I do see that your spec ran for '0 seconds'. Sometimes on shorter videos the recording would crash because too few video frames were received, but we'd only ever seen that on Firefox: https://github.com/cypress-io/cypress/pull/7192

**Comment by AkramPasha** [comment] 2020-12-04 09:10
@jennifer-shehane 

This issue can be reproduced.
Out of 10 spec file , if I make one spec to be ignored while executing in a suite.
Video recording error is displayed.

1st scenario:

xdescribe('Sample test', () =>{
  before(()=>{
  cy.log('Launching the application)
  cy.visit('hhtps://google.com')
  })
  
  it('first test case',()=>{
  ------
  some work flow
  ---------
  })
  
  it('second test case',()=>{
  ------
  some work flow
  ---------
  })
}) 

When this spec file is executed in a automation suite , the video recording will fail.

2nd scenario:

Assume in any spec file ,if we are not hitting any browser [ex: cy.visit()] is not used , then also we can see this error.

describe('Sample test', () =>{

  it('first test case',()=>{
  ------
  some work flow
  ---------
  })
  
  it('second test case',()=>{
  ------
  some work flow
  ---------
  })
})

**Comment by AkramPasha** [comment] 2020-12-10 20:58
@jennifer-shehane , Thanks for the reply. 
This issue is inconsistent, because in my automation suite if any spec file executed for '0' seconds can expect this error thrown while processing the video. 
For example:

If I have ignored any spec file to be executed during the suite execution. 

xdescribe('update the json file ',() =>{
  // write multiple it blocks. 
}) 

As this spec file takes 0 seconds to execute, after execution found this error.

**Comment by jennifer-shehane** [comment] 2020-12-11 06:41
I ran 50 runs of the code you provided using https://github.com/bahmutov/cypress-repeat in Chrome 87 on my Mac and was not able to see the processing video error. Can you give more detail about the environment you're running this in? What OS? On CI?

**Comment by AkramPasha** [comment] 2020-12-11 06:58
@jennifer-shehane ,
The environment used:
OS : Windows-10 Enterprise.
Chrome : 87.0.4280.88
Executed from VS code

This error is not seen when the spec is executed,
The video error is expected when ever we ignore the spec file to execute, The execution should be in '0' seconds

**Comment by jennifer-shehane** [comment] 2020-12-11 09:06
>The video error is expected when ever we ignore the spec file to execute

Meaning writing `xdescribe` for the suite? That's what I ran my tests with and the video never errorred.

**Comment by jennifer-shehane** [comment] 2021-02-27 00:11
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-27 00:11 UTC
Labels: browser: chrome, stage: needs information, topic: video 📹
