### ISSUE TITLE
@cypress/grep - env grepFilterSpecs: true in cypress.config.js throws a Cypress configuration error

### ISSUE THREAD

**Issue by davidhornmarkINGKA** [cypress-io/cypress#27221] opened 2023-07-06 13:14 UTC
### Current behavior

When using package `@cypress/grep` and setting environment variable `grepFilterSpecs: true` in the `cypress.config.js`.
`configFile` will throw an error while executing `e2e.setupNodeEvents()`.

Setting `grepFilterSpecs: false` allows it to load.

Registered @cypress/grep in the config file according to the guide:
[https://github.com/cypress-io/cypress/tree/develop/npm/grep#config-file](https://github.com/cypress-io/cypress/tree/develop/npm/grep#config-file)

Set environment variable `grepFilterSpecs` according to:
[https://github.com/cypress-io/cypress/tree/v12.11.0/npm/grep#pre-filter-specs-grepfilterspecs](https://github.com/cypress-io/cypress/tree/v12.11.0/npm/grep#pre-filter-specs-grepfilterspecs)

![error-message](https://github.com/cypress-io/cypress/assets/106753170/e93ca94d-3fc2-4486-b60f-bb46d1221c83)

### Test code to reproduce

Created a bare minimum repo with auto generated files by Cypress.

[https://github.com/davidhornmarkINGKA/cypress-grepFilterSpecs-issue](https://github.com/davidhornmarkINGKA/cypress-grepFilterSpecs-issue)

`package.json`:
```
{
  "name": "cypress-grepfilterspecs-issue",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "@cypress/grep": "^3.1.5",
    "cypress": "^12.16.0"
  }
}
```

Example config:
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  env: {
    grepFilterSpecs: true
  },
  e2e: {
    setupNodeEvents(on, config) {
      require('@cypress/grep/src/plugin')(config);
      return config;
    },
  }
});
```

### Cypress Version

12.16.0

### Node version

v18.16.1

### Operating System

Windows 10.0.19045

**Comment by MikeMcC399** [comment] 2023-07-06 14:11
@davidhornmarkINGKA 

- This looks like the same issue as reported a few hours ago in https://github.com/cypress-io/cypress/issues/27216

**Comment by davidhornmarkINGKA** [comment] 2023-07-06 14:17
@MikeMcC399 
Thanks for the link. Searched for grepFilterSpecs but didn't find any issue on it so provided my own information here.

My current workaround is to not have `grepFilterSpecs `set and take the performance loss.

**Comment by ivan-verges** [comment] 2023-07-06 18:14
This issue is caused by the new version of the fast-glob package (3.3.0).
To get a workaround, add manually this dependency to your packages.json file:
"fast-glob": "3.2.12"

**Comment by nagash77** [comment] 2023-07-07 12:02
I am going to close this issue as a duplicate of #27216

**Closed as not planned by nagash77** 2023-07-07 12:02 UTC
