### ISSUE TITLE
Cypress 10 on docker threw "Cannot find module 'cypress'"

### ISSUE THREAD

**Issue by annaFW123** [cypress-io/cypress#22420] opened 2022-06-21 13:15 UTC
### Current behavior

Hello!

My company runs cypress via jenkins and docker. Recently we tried to migrate to v10 and followed the migration guide. Everything works fine on my local machine (windows, no docker). But running it on docker results in an error.

```
Your configFile is invalid: /var/jenkins_home/workspace/fawo_danger_test-cypress12/cypress.config.js


It threw an error when required, check the stack trace below:


Error: Cannot find module 'cypress'

Require stack:

- /var/jenkins_home/workspace/fawo_danger_test-cypress12/cypress.config.js

- /home/node/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js

- /home/node/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js
```

I'm pretty confused, because our setup worked fine before. We used "cypress/base:12" as docker image and also tried "cypress/included:10.1.0" without success.

As far as I understand, cypress is not installed. But why did it work before? And "cypress/included:10.1.0" includes cypress, doesn't it?

(I'm a newbie to docker and npm, maybe I'm missing something obvious)

### Cypress Version

10.1.0

### Package Manager

npm

### Operating system

Linux

**Comment by emilyrohrbough** [comment] 2022-06-23 19:25
@annaFW123 To ensure I am looking into the same issue you are having, can you share your docker setup/command you are running in jenkins that produced this error?

**Comment by annaFW123** [comment] 2022-06-24 06:32
Hi @emilyrohrbough 
Here's the relevant piece of our configuration.

`stage('Loop Deploy and Cypress') {
         agent {
                    docker {
                        image 'pdmlab/jenkins-node-docker-agent:10.21.0'
                        args '-e MAVEN_CONFIG=/tmp/m2 -v /var/run/docker.sock:/var/run/docker.sock -v /etc/passwd:/etc/passwd'
                    }
                }
                steps {
                    script {
                            docker.image('cypress/included:10.1.0').inside { c ->
                                if (buildConfiguration.environments[i].cypressURL != null) {
                                    stage('Cypress') {
                                        echo "start cypress test for ${buildConfiguration.environments[i].cypressURL}"
                                        sh "npx cypress run --config baseUrl=${buildConfiguration.environments[i].cypressURL},responseTimeout=10000"
                                    }
                                }
                            }
                        }
                    }
                }
            }`

**Comment by emilyrohrbough** [comment] 2022-06-28 19:40
@annaFW123 Thank you for the additional information. It was helpful!

The issue you are seeing occurs when Node is looking for.a locally installed (per project-installed) node module and it does not exist. Unfortunately, Node.JS not resolve globally installed node modules by default. This is why the docker image can have Cypress installed globally and you can run into this error. The solution is to configure the `NODE_PATH` environment variable.

This is configured [here](https://github.com/cypress-io/cypress-docker-images/blob/master/included/10.1.0/Dockerfile#L22) in the `cypress/included:10.1.0` docker image. I have confirmed this is working correctly on my mac machine with the `cypress/included:10.1.0` image by running the following in a project without cypress installed in node_modules

```bash
docker run -it -v $PWD:/e2e -w /e2e cypress/included:10.1.0
```
The issue you are seeing is likely due to the fact your Jenkins node is Windows based and this path is incorrect. I suggest logging into your jenkins box and/or running in a script the following command to determine the global path:
```bash
npm ls -g
```
You will see output like:
```bah
# npm ls -g 
/usr/local/lib
+-- corepack@0.10.0
+-- cypress@10.2.0
+-- npm@8.5.0
`-- yarn@1.22.19
```
The above shows the path should be: `/usr/local/lib/node_modules`

The `cypress/base:12` does not have the `NODE_PATH` env variable set. If you'd like to use this image as a base image, you will need to set this env yourself.

**Comment by emilyrohrbough** [comment] 2022-07-11 14:00
@annaFW123 I am going to go ahead and close this. The above comment should provide information for you to solve your issue.

**Closed by emilyrohrbough** 2022-07-11 14:00 UTC
Labels: stage: awaiting response, CI, topic: installation

**Comment by annaFW123** [comment] 2022-07-27 12:28
@emilyrohrbough I apologize for the late answer. This worked, thank you!
