### ISSUE TITLE
Improve Test launcher with custom params

### ISSUE THREAD

**Issue by antonioaltamura** [cypress-io/cypress#21646] opened 2022-05-26 13:01 UTC
### What would you like?

I need env vars in my tests. This is how I launch interactive tests:
`CYPRESS_param1=$param1 CYPRESS_param2=$param2 npx cypress open`

It could be useful to expose received params and allow the user to change them, using a textarea (screenshot) or through a dropdown in the "Tests" tab. The allowed values (for the dropdown) could be defined in the general config `cypress.json`.

![Screenshot from 2022-05-26 13-51-46](https://user-images.githubusercontent.com/6325475/170492169-009a93bf-7424-4ac6-bb38-78212f0363d4.png)

### Why is this needed?

To ease switching between param values without closing the launcher.

**Comment by flotwig** [comment] 2022-05-26 17:18
Hi @antonioaltamura, for your immediate benefit, I would suggest using [`Cypress.env(name, value)`](https://on.cypress.io/env) via the Developer Tools in your browsers if you need to change values on-demand.

I think this has significant overlap with #3640, so I'm going to close it as a duplicate of that issue. Watch that issue for further updates.

**Closed by flotwig** 2022-05-26 17:18 UTC
Labels: stage: investigating
