### ISSUE TITLE
Cypress not finding beta/dev builds of Edge on linux

### ISSUE THREAD

**Issue by CarbonCollins** [cypress-io/cypress#25611] opened 2023-01-27 15:47 UTC
### Current behavior

After installing Edge Beta and Edge Dev on my machine I do not see them listed as an option to run my E2E tests against. The Stable version does appear in the UI with no issues.

### Desired behavior

After installing Edge Beta and Edge Dev on my machine I should see them listed as an option to run my E2E tests against
Test code to reproduce

### Test code to reproduce

There is no test code to run as the bug appears before any tests are run.

### Cypress Version

12.4.1

### Node version

v18.12.1

### Operating System

Manjaro Linux 6.0.15-1-MANJARO

### Other

After looking into how Cypress knows about browsers I noticed two potential issues with the version regex in the packages/launcher/lib/browsers.ts file and the binary names.

For the version regex I'm not sure if this would be the cause of the issue but the regex for Edge Dev is /Microsoft Edge Dev (\S+)/m and for Edge Beta is /Microsoft Edge Beta (\S+)/m but when running /usr/bin/microsoft-edge-dev --version it returns Microsoft Edge 110.0.1587.6 dev which would not match the regex string. This is the same for the beta version where it returns Microsoft Edge 109.0.1518.49 beta

Re-opened issue as the previous one [#25455](https://github.com/cypress-io/cypress/issues/25455) was closed upon release with only 1 of the fixes merged

**Comment by CarbonCollins** [comment] 2023-01-27 15:48
The remaining PR that solves the version matching: #25457

**Comment by emilyrohrbough** [comment] 2023-01-27 16:28
@CarbonCollins oh shoot....this was not expected to have been a 2 part PR. The summary text `partially closes https://github.com/cypress-io/cypress/issues/25455` automatically closed this issue as resolved.

**Comment by CarbonCollins** [comment] 2023-01-27 17:15
It happens :D

Just so the two issues are linked at least ill mention the other on here #25455

**Comment by mschile** [comment] 2023-01-31 23:06
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/25455. The other issue was reopened instead. Both PRs have been merged and were released in Cypress 12.5.0.

**Closed as not planned by mschile** 2023-01-31 23:06 UTC
