### ISSUE TITLE
Can I take a screenshot of my website only?

### ISSUE THREAD

**Issue by Gennadiii** [cypress-io/cypress#1408] opened 2018-03-02 17:49 UTC
I need just content of an iframe with my site without all the cypress stuff.

### Is this a Feature or Bug?
Feature

### Current behavior:
http://i.piccy.info/i9/9f9b93eacf6581b42eb5d005f643f6ce/1520012826/171411/1215371/Home_page_logo_is_correct.png

### Desired behavior:
http://i.piccy.info/i9/d81bb79081bb8d2c315d935ed283c428/1520012884/46923/1215371/Home_page_logo_is_correct_Copy.png

**Comment by brian-mann** [comment] 2018-03-02 19:04
Duplicate of https://github.com/cypress-io/cypress/issues/181

PR's are welcome. Our team is highly aware of this need - and it along with many others will eventually get done.

**Closed by brian-mann** 2018-03-02 19:04 UTC
Labels: type: duplicate
