### ISSUE TITLE
cy.writeFile command keeps on looping if filepath .json file already exists

### ISSUE THREAD

**Issue by poponuts** [cypress-io/cypress#5760] opened 2019-11-21 03:14 UTC
### Current behavior:

When I run the test, the API call keeps looping and writing the response body into the json file until it goes into a "429: Too Many requests" status code.

### Desired behavior:

I only need to do the API call once and save the response body's "access_token" into the json file for my test.

Reason: I only need to generate a token once for my entire suite. I don't want to be calling the API everytime I run a test. Thus, saving it into a file makes it quicker and cleaner.

### Steps to reproduce: (app code and test code)

1. Created a command to call the API then write the response body into a json file under `../support/commands.js`:

```js
Cypress.Commands.add("postToken", () => {
    const options = {
        method: "POST",
        url: "URL Path/API endpoint",
        form: true, 
        body: {
            grant_type: "credentials",
            scope: "scope"
        },
        auth: {
            username: "username",
            password: "password"
        }
    };
    
    cy.request(options).then((response) => {
        cy.writeFile("cypress/fixtures/tokens.json", response.body); 
        cy.log("Token successfully generated and saved at tokens.json");
    });
});
```

3. Call the command "postToken" in either the test file or index.js:
```js
before(() => {
    cy.postToken();    
    }
);
```

Result: The first run is fine as `cy.writeFile` automatically creates the `tokens.json` file. However, when I re-run it (with the `tokens.json` already populated with data), the test run keeps looping until it generates a too many requests error.
Sample `tokens.json` content captured from the API response body:

```json
{
  "access_token": "long token file name",
  "expires_in": 1200,
  "token_type": "Bearer"
}
```

Details:
Cypress version 3.6.1 (latest)
Windows 10, Chrome Version 78.0.3904.108

**Comment by nodi1995** [comment] 2019-11-29 10:46
I had the same problem, and in the end, I realized that this is not a bug. You need to set watchForFileChanges to false because every time you overwrite your JSON file, cypress is listening to changes and restarting the test. I'm wondering now, is there any way to config ignore list related to changes?

**Comment by jennifer-shehane** [comment] 2020-01-03 06:02
This is a duplicate of this issue https://github.com/cypress-io/cypress/issues/3347 which I am still unable to reproduce from the code below. I'm not sure what I'm missing here. 

```js
it('cy.request() - make an XHR request', () => {
  cy.visit('https://example.cypress.io/commands/network-requests')

  cy.request('https://jsonplaceholder.cypress.io/comments')
    .then((response) => {
      cy.writeFile('cypress/fixtures/example.json', response.body)
      
    })
})
```

**Comment by jennifer-shehane** [comment] 2020-03-18 07:23
Duplicate of #3347

**Closed by jennifer-shehane** 2020-03-18 07:23 UTC

**Comment by begli80** [comment] 2020-04-10 00:21
I am facing the same issue , when I create a new user to login I create a new user and want to store it in json file so using cy.writeFIle({key:value}) it keeps looping running the tests

**Comment by hachther** [comment] 2025-01-27 09:00
I faced the same issue but i solved it.

The problem was that my code imported the file written in writeFile (import '/path/of/the/file').

I solved it by using the lazy load so instead of using import instructions I used required('/path/of/the/file') within a function where the file was needed.
