### ISSUE TITLE
Could not type any text on my Iframe

### ISSUE THREAD

**Issue by imaneok** [cypress-io/cypress#2094] opened 2018-07-04 11:16 UTC
I have been trying to create a test where i write a simple text on my ck-editor but could not access it as it is an iframe. i tried many times but could not figure out to solve it and specially that i have a lot of this ck-editors in my project so it is a crucial part of tests.

here is what i tried:
```js 
cy.get("iframe").then(function($iframe){
      // query into the iframe
      var b = $iframe.contents().find("body")

      cy
        .wrap(b)
        .find('.cke_wysiwyg_frame')
        .type('4242424242424242')


      // you can work with this element here but it cannot
      // be returned

      return null
    })```

here is the error :y

```
.find() failed because this element is detached from the DOM.

<body onload="document._l();">...</body>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.wrap()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.
```

Thanks for your help in advance

**Comment by brian-mann** [comment] 2018-07-04 22:02
It's likely erroring with that message because well.. the element is detached rom the DOM.

My guess is that your iframe's body is being rerendered multiple times, and that you're not awaiting until its ready to be consumed by Cypress yet.

Maybe try wrapping the `$iframe.get('contentDocument')` and then `.find()` off of that. The document won't go stale unless the iframe itself navigates.

**Comment by brian-mann** [comment] 2018-07-04 22:02
Also can you create a small reproducible example for us? It would be helpful and we could tell you exactly what to do in that situation.

**Comment by jennifer-shehane** [comment] 2019-04-24 16:14
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-24 16:14 UTC
Labels: stage: needs information

**Comment by bcmcadam** [comment] 2021-06-09 14:59
@brian-mann @jennifer-shehane  
I have an iframe that I am able to work with until it displays a new page (same iframe displaying a different page) how do i refresh my locator. I'm using the example here: https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/

``const getIframeBody = () => {
    return cy.get('#newPaymentIframe').its('0.contentDocument.body').should('not.be.empty').then(cy.wrap)
}

describe('Invoice Scenarios', () => {

    it('can create an AffiniPay CC method', () => {
        
        cy.accessMagicLink('https://mymagiclinkurl.com')

        cy.get('[data-test-id="open-invoices__button-pay"]').trigger('click')
        cy.get('[data-test-id="make-payment__manage"]').as('managePaymentsBtn').click({ force: true})
        cy.get('[data-test-id="make-payment__add-new-pmt"]').as('addNewBtn').click({ force: true})
        getIframeBody().find("input[value='ach']").should('have.value', 'ach').click({force:true})      
        getIframeBody().find("input[value='credit']").should('have.value', 'credit').click({force:true})      

// this is where the iFrame refreshes but when I inspect the failing but when inspect the next line (which fails), its looks to be using the stale iframe that still has the same title from the line above. How can i make sure the below line refreshes the  document content?

        getIframeBody().find("input[name='billing-address-company']", {timeout:60000}).as('companyField').type('Acme')
        getIframeBody().find('input[name="billing-address-address1"]').as('addressField').type('7734 Elm Street')
        getIframeBody().find('input[name="billing-address-city"]').as('cityField').type('Seattle')
        getIframeBody().find('input[name="billing-address-state"]').as('stateField').type('Washington')
        getIframeBody().find('input[name="billing-address-zip"]').as('zipField').type('98199')
        getIframeBody().find('input[name="billing-address-country"]').as('countryField').type('USA')
        getIframeBody().find('input[name="billing-address-email"]').as('emailField').type('acmepay@acme.com')
        getIframeBody().find('input[name="billing-address-zip"]').as('zipField').type('98199')
        getIframeBody().find('input').within('#cc-number').as('ccField').type('4222442432242442')
        getIframeBody().find('#cc-exp-month').as('#ccExpMonth').type('10')
        getIframeBody().find('#cc-exp-year').as('#ccExpYear').type('23')
        getIframeBody().find('input').within('#cc-cvv').as('cvvField').type('123')
        getIframeBody().find('input[name="billing-nickname"]').as('nicknameField').type('Acme CC')
        getIframeBody().find('input[name="submitButton"]').as('saveBtn').click
    })
})

**Comment by jennifer-shehane** [comment] 2021-06-10 18:12
@bcmcadam 
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
