### ISSUE TITLE
Prevent test reload when not setting baseUrl

### ISSUE THREAD

**Issue by rsmets** [cypress-io/cypress#2602] opened 2018-10-12 19:15 UTC
### Current behavior:

Upon first opening a test using the test runner some test are run _then_ the browser reloads and all but the first test is reran which is what the dashboard reads as the result. This behavior is only noticeable when the first test group contains a network request. This stutter step, so to speak, has had averse effects on tests as one can imagine. 

### Desired behavior:

Upon _first_ opening the tests are run once with no reload / restart.

### Steps to reproduce:
Below is example code to reproduce. Upon clicking on the bug example file in the test runner please quickly open the console with preserve log checked to view the characteristic. Note 'randomString2' and 'in request response' is never logged. To reproduce again one must close the browser, stop the test, and restart the test forcing the browser to open for first time.
```js
var randomstring = require("randomstring");

var randomString;
describe('bug highlight', function () {
  before(function () { 
    randomString = randomstring.generate();
    console.log('randomString1', randomString);
  })

  context('bug', function () {
    it('post', () =>{
        console.log('randomString2', randomString);
        return cy.request({
            method: 'POST',
            url: `https://e.deployads.com/e/whatismyip.com`,
            form: false,
            body: {"jsr":{"_count":1,"bdl":"7133","msg":"Okay","u":"https://www.whatismyip.com/what-is-my-public-ip-address/","pv":`${randomString}`,"sid":"jn6d3c0k2juz91","r":"https://www.google.com/","sta":200,"tas":1539368968738,"bld":17252,"s":"whatismyip.com","uid":"jn6d3c0k2juz91","typ":"im","cfdt":"D","rt":115,"_type":"jsr"}}
        }).then((response) => {
            console.log('in request response');
            cy.expect(response.status).to.eq(200);
        })
    })

    it('visit', () =>{
        console.log('randomString3', randomString);
        cy.visit('https://google.com');
    })
  })
})
```

### Versions
cypress v3.1.0
chrome canary 71

**Comment by jennifer-shehane** [comment] 2018-10-12 23:43
You can prevent the reload by setting a `baseUrl`. The explanation for the reload is explained more here: https://on.cypress.io/best-practices#Setting-a-global-baseUrl

**Comment by rsmets** [comment] 2018-10-12 23:56
Hi @jennifer-shehane thanks for the prompt reply. I actually almost posted this at the bottom of https://github.com/cypress-io/cypress/issues/1541 stating that I have to leave the baseUrl config prop blank due to it not following proxy settings on my CI box. Thus using a env variable serving the same purpose(ish).

**Comment by rbayliss** [comment] 2020-07-31 14:08
It looks like this also happens when `baseUrl` is set and you `cy.visit()` any domain that is not the same as the `baseUrl`.

**Comment by flotwig** [comment] 2020-07-31 14:14
@rbayliss this is expected behavior so Cypress can exist within the browser's security model, see explanation here: https://docs.cypress.io/guides/references/best-practices.html#Setting-a-global-baseUrl

---

> Hi @jennifer-shehane thanks for the prompt reply. I actually almost posted this at the bottom of #1541 stating that I have to leave the baseUrl config prop blank due to it not following proxy settings on my CI box. Thus using a env variable serving the same purpose(ish).

@rsmets Cypress has had proxy support for about a year now, might be worth trying `baseUrl` again 

---

Closing this issue as wontfix

**Closed by flotwig** 2020-07-31 14:14 UTC
Labels: stage: proposal 💡, type: unexpected behavior
