### ISSUE TITLE
cy.request() response with Set-Cookie header not setting back on the browser cookies in 3.5.0

### ISSUE THREAD

**Issue by rafawalter** [cypress-io/cypress#5469] opened 2019-10-25 12:20 UTC
### Current behavior:

Using `cy.request` to quickly autenticate before each test. 

Worked in 3.4, setting cookies using `window.localStorage.setItem`,

Not working in 3.5.0

Got a backend response with the `Set-Cookie` header. Looked in `Electron's Developer tools / Application / Cookies`. Seems like cookies are not being setted automatically in the browser after the response. Had to write a workaround to set them manually and get test back running.

### Desired behavior:

https://docs.cypress.io/api/commands/request.html#Cookies

If a response has a `Set-Cookie` header, these are automatically set back on the browser cookies.

### Steps to reproduce:
```js
       cy.request({
            method: 'POST',
            url: 'rest/auth',
            headers: {
                "Pragma": "no-cache",
                "Origin": Cypress.config().baseUrl,
                "Accept-Encoding": "gzip, deflate",
                "Accept-Language": "en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7,fr;q=0.6,es;q=0.5",
                "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.4.1 Chrome/61.0.3163.100 Electron/2.0.18 Safari/537.36",
                "Content-Type": "application/x-www-form-urlencoded",
                "Accept": "application/json, text/plain, */*",
                "Cache-Control": "no-cache",
                "Referer": Cypress.config().baseUrl,
                "Proxy-Connection": 'keep-alive',
            },
            body: {
                username: username,
                password: password
            }
        }).then((resp) => {
            console.debug('autentication response', resp)
            const cookies = resp.headers['set-cookie']
            cookies.forEach(cookie => {
                const firstPart = cookie.split(';')[0]
                const separator = firstPart.indexOf('=')
                const name = firstPart.substring(0, separator)
                const value = firstPart.substring(separator + 1)
                console.debug('cookie', name, value)
                cy.setCookie(name, value)
            })
        })
```

### Versions

Cypress 3.5.0
Electron 73
Windows 7

**Comment by flotwig** [comment] 2019-10-25 13:37
Hey @rafawalter, we changed 3.5.0 so that the final redirect in a `cy.visit()` will set the cookies via a normal `Set-Cookie` header, instead of behind-the-scenes in browser APIs. The intent was to make cookies easier for users to debug. Is this not working for you?

**Comment by flotwig** [comment] 2019-10-25 13:39
Ah, you're saying a cy.request is not setting the correct cookies? Are you making a cy.request to an endpoint that sets cookies on redirects? There is a bug with a fix here: #5432

**Comment by David-Dorr** [comment] 2019-10-25 13:54
I don't know if this is related, but I have upgraded to 3.5.0 from 3.4.2, and my tests have stopped working..

I am getting..
`CypressError: cy.setCookie() must be passed an RFC-6265-compliant cookie name.`

Because this error occurred during a 'before each' hook we are skipping all of the remaining tests.`

Im just doing `cy.visit('/')`

**Comment by rafawalter** [comment] 2019-11-01 14:29
Same behaviour in 3.6.0

**Comment by flotwig** [comment] 2019-11-01 14:42
@rafawalter assuming this is a duplicate of #5432, closing

**Closed by flotwig** 2019-11-01 14:42 UTC
Labels: stage: awaiting response
