### ISSUE TITLE
Timed out retrying: cy.click() failed because this element is not visible...has CSS property: 'display: none'

### ISSUE THREAD

**Issue by krishnapemmaraju** [cypress-io/cypress#4856] opened 2019-07-29 10:44 UTC
Not able to handle the Window pop up , I am not able to click on the button which is available on the pop up window

### Current behavior:

It is throwing below error

![image](https://user-images.githubusercontent.com/53334205/62042441-05ddbd80-b1f6-11e9-9ea9-f644866edafc.png)

### Desired behavior:

it should allow me to click on the button

**Comment by pictuner** [comment] 2019-07-29 13:16
Is it an actual new browser windows or tab? In that case it will not work since Cypress doesn't support multiple browsers windows/tabs.

What Cypress is telling you is that the page it sees has no such element called 'Cancel'.

**Comment by krishnapemmaraju** [comment] 2019-07-29 13:30
Thanks for the reply
It actually a new window pop-up where the buttons are available. But with out clicking on Cancel button we will not be able to proceed further

**Comment by jennifer-shehane** [comment] 2019-07-29 15:18
Users cannot click on elements with a property of `display: none`, this is the browser's behavior. 

If you think this is a bug - ie, the button does not have the `display: none` property, then we'll need a reproducible example to move forward with investigating. Without a reproducible example, we will have to close the issue.

**Comment by BernardoLaing** [comment] 2019-10-17 22:45
I am having a similar error: 
CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<td _ngcontent-pdk-c3="" class="td-actions">...</td>

This element '<td.td-actions>' is not visible because it has an effective width and height of: '0 x 0' pixels.

The actual HTML of that element is:

<td _ngcontent-dks-c3="" class="td-actions"><button _ngcontent-dks-c3="" class=" btn btn-outline-primary btn-icon-only rounded-circle" type="button" tabindex="0" ng-reflect-router-link="/solicitudes,F6McvQ1gdz4TpH5yK"><span _ngcontent-dks-c3="" class=" btn-inner--icon" rel="tooltip" title="Ver solicitud"><i _ngcontent-dks-c3="" class="fa fa-eye"></i></span></button></td>

The element is actually visible in the Chrome window being used by cypress.

**Comment by Neurrone** [comment] 2019-10-18 15:31
We've seen it on our application as well, and suspect that it isn't able to properly deal with display: none styles if its conditionally applied to hide elements on smaller viewports with media queries.

**Comment by melibe23** [comment] 2020-02-05 20:31
Same issue happens to me. My click, refreshes the site and has nothing to do with display:none. Any workaround? Thank you!

**Comment by begli80** [comment] 2020-02-12 19:40
I have had the same issue for a while now. I mousover on an element and then click on another element from the dropdown and that's the place where it fails saying " This element '<a>' is not visible because its parent '<li.sign-in-register.hide-on-mobile>' has CSS property: 'visibility: hidden' "

**Comment by jonauz** [comment] 2020-02-18 11:18
How to stop/limit attempts number. For me it never stops, just keeps on going and makes computer super slow, becomes lagging and almost impossible to debug other steps in the flow. And main run of test is stoped, just this one keeps on retrying into infinity.

**Comment by itinance** [comment] 2020-03-04 22:44
`.click({force: true})` worked for me. It is a checkbox where '.check()' gives the same error messages of this issue.

**Comment by jennifer-shehane** [comment] 2020-07-14 09:46
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-14 09:46 UTC
Labels: stage: needs information

**Comment by swativol** [comment] 2020-09-08 04:21
try to create  different xpath where in all the elements will be covered and user {force:close}.

**Comment by alejandroyunes** [comment] 2022-03-03 20:02
kind of the same error here, even tho it has a display: block, and the form is shown, cypress fails to detect it. 

Timed out retrying after 4050ms: cy.click() failed because the center of this element is hidden from view:

<input type="email" id="email" name="email" value="" data-test-id="topbar-signup-email">

Fix this problem, or use {force: true} to disable error checking

**Comment by kovalforpublic** [comment] 2022-03-31 07:42
Same issue. Seems to be related to combination of conditional `display: none` and `media queries` .

**Comment by Erksters** [comment] 2022-05-04 17:53
I'm hiding a button with css display: 'none' and cypress doesn't like it. Strange how it isn't able to click the hidden button.

```
<Button 
     data-cy="protocols"
     style={{display:'none'}}
>
            adsf
</Button>}
```
```
cy.get('[data-cy=protocols]').click()
```

**Comment by lucho2819** [comment] 2022-10-20 17:51
31
assertexpected <button#0-menu.mat-focus-indicator.mat-menu-trigger.mat-button.mat-button-base.btn-actions> to be visible
AssertionError
Timed out retrying after 30000ms: expected '<button#0-menu.mat-focus-indicator.mat-menu-trigger.mat-button.mat-button-base.btn-actions>' to be 'visible'

This element <button#0-menu.mat-focus-indicator.mat-menu-trigger.mat-button.mat-button-base.btn-actions> is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: hidden, scroll or auto

**Comment by lucho2819** [comment] 2022-10-20 17:52
![image](https://user-images.githubusercontent.com/113719144/197022243-925633f2-e8a3-421a-9d50-f508a59d2faa.png)

**Comment by talhazi** [comment] 2022-11-17 15:32
Hi someone over come the problem? (without force)

**Comment by lucho2819** [comment] 2022-11-17 16:02
what I did was to remove from my script that the element was visible and it worked. 

Example I had
cy.get(.class).should(be.visible).click(); 

I just removed the should and it worked and I got the class.

**Comment by gigamesh** [comment] 2023-02-15 19:21
I've tried `.filter((_, el) => el.style.display !== 'none')` and `.should(be.visible)` but both don't work...why?

**Comment by 55stella** [comment] 2024-10-08 19:38
i'm having this same issue 
Timed out retrying after 30050ms: cy.click() failed because this element is not visible:

<button type="button" class="btn btn-primary" onclick="saveCaseNotes(5,true)">Save</button>

This element <button.btn.btn-primary> is not visible because its parent <div#edit-strategy.w-100.me-3.position-relative> has CSS property: display:

**Comment by eon-waqas** [comment] 2024-12-10 08:27
This element <h5.dropdown-item.cursor-pointer> is not visible because its parent <div.dropdown-border.shadow.dropdown-menu-right.dropdown-menu> has CSS property: display: none

**Comment by DessaugesAntoine** [comment] 2025-04-09 09:31
So for me I got the error `cy.click() failed because this element is not visible`.

`{forced: true}` let me avoid the error but my element was not hidden, behind something or anything strange. It was just not in scroll view and and `.scrollIntoView()` or `.scrollTo(X, Y)` was not changing anything.

It was my first experience with Cypress (fixing tests already done by another person) so by default I choose Electron when I run `cypress open` since it was selected by default and look like Cypress suggestion, even running test with the terminal run with Electron by default for me. Choosing "Chrome" instead of "Electron" fix this error for me.

Don't know if it's only for my project or if this can help anyone.
