### ISSUE TITLE
It looks like a ladybird, it behaves a bit like a ladybird, but it's NOT a ladybird! Why call it a ladybird?

### ISSUE THREAD

**Issue by Izhaki** [cypress-io/cypress#6267] opened 2020-01-28 15:19 UTC
This:
```
  cy.get(`#id`).then(() => {
    doSomething();
  });
```

And this:
```
  await cy.get(`#id`);
  doSomething();
```
Are not the same.

- in the former `doSomething()` will be called once the element is found on the DOM.
- in the latter it will be called WAY before that.

I know and completely understand why this is.

But I think it is worth pointing out that this is MASSIVELY confusing.

If something doesn't implement a promise API, then it should, ideally, not use names from that API. More so if the non-promise API behave like a promise API.

Rename `then`?

**Comment by sainthkh** [comment] 2020-01-30 09:20
Hello,

Thanks for opening the issue. Unfortunately, it is a duplicate of #1417.

Discussion about using `await`/`async` is going on in that thread and you can also find why Cypress is designed in this way.

**Closed by sainthkh** 2020-01-30 09:20 UTC
Labels: type: duplicate
