### ISSUE TITLE
cy.as() command can't share object between tests?

### ISSUE THREAD

**Issue by sqli0189** [cypress-io/cypress#15593] opened 2021-03-20 03:20 UTC
Not sure if this is the correct place to raise this isssue.

In my test code, I would like to share the response body data yielded from the command **cy.createApp()** between tests, however, when I executed this spec file, I noticed in **test 01**, it can print the value that's stored in app_data, in **test 02**, it print nothing, I can not reference any field stored in **app_data** in **test 02**, it seems before the code goes to **test 02**, the alias **app_data** was cleared by cypress runner.

Could you pls let me know if this is a bug or a limitation of Cypress? BTW, the Cypress version I'm using is **6.8.0**

Thanks in advance!  

```js
describe('Foo', function() 
{
    before('Prepare test account', function() {
        cy.log('Generate a new test account')
        cy.task('generateNewAccount', {account_type: 'test'}).then((email)=>{
           cy.login(email, 'account')
           cy.saveLocalStorage()
        })
        cy.log('Create a default iOS app for the account')

        cy.createApp('iOS Test App', 'ios').then(($appdata) => {
            cy.wrap($appdata).as('app_data')
        })

    })

    it('test 01', function () {
        cy.log(this.app_data) //Print the detailed info
    })

    it('test 02', function() {
        cy.log(this.app_data) //Print nothing
    })

}
```

**Comment by jennifer-shehane** [comment] 2021-03-20 13:35
Duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2021-03-20 13:35 UTC
