### ISSUE TITLE
"Webpack Compilation Error - multi" on redirect

### ISSUE THREAD

**Issue by dwineknott** [cypress-io/cypress#8507] opened 2020-09-04 17:03 UTC
@jennifer-shehane Upping this again.  I've upgraded to 5.2.0 and I'm still encountering the below error.

The path in the error: "Users/dknott/Desktop/redacted" is the parent directory for my local Cypress project.  

_Originally posted by @dwineknott in https://github.com/cypress-io/cypress/issues/8407#issuecomment-686768513_

**Comment by dwineknott** [comment] 2020-09-04 17:04
#8407  for reference and code to reproduce.

**Comment by dwineknott** [comment] 2020-09-22 18:10
Adding sample code:

```
describe('Smoke Test', () => {
  Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  });

  beforeEach(() => {
    cy.server()
    cy.route('POST', 'app.songtrust.com/api/v1/lod/').as('lod');

  });

  it('IMRO ', () => {
    // Begin funnel workflow 
    cy.request({
      method: 'POST',
      url: 'app.songtrust.com/api/v1/user/login/',
      body: {
        username: 'demo@songtrust.com',
        password: 'testing',
      }
    });
    cy.visit('app.songtrust.com/songwriters/#add');
    cy.findByTestId('show-lod-pros-button')
      .click();
    cy.findByTestId('lod-pro-selections')
      .select('IMRO', { force: true });
    cy.findByTestId('lod-pro-selections')
      .should('have.value', 'IMRO');
    cy.findByTestId('continue-to-form')
      .click();

    /////LOD Form - IMRO///////
    cy.url()
      .should('contains', '/songwriters/#add/lod-form');  //assert URL

    cy.findByTestId('first-name')
      .should('be.visible')
      .type('Frank');

    cy.findByTestId('middle-name')
      .should('be.visible');

    cy.findByTestId('last-name')
      .should('be.visible')
      .type('Ikiseh');

    cy.findByTestId('id_email')
      .should('be.visible')
      .type('imro@songtrust.com');

    cy.findByTestId('id_writer_id')
      .should('be.visible')
      .type('01047205098');

    cy.findByTestId('lod-us-representation')
      .should('be.visible')
      .select('ASCAP', { force: true });

    cy.findByTestId('pubco_no')
      .should('be.visible');

    cy.findByTestId('pubco_yes')
      .should('be.visible')
      .click();

    cy.findByTestId('id_publishing_company')
      .should('be.visible')
      .type('Alpha Music');

    cy.findByTestId('publishing_company_pro')
      .should('be.visible')
      .select('ASCAP', { force: true });

    cy.findByTestId('id_publisher_id')
      .should('be.visible')
      .type('697403510');

    //Signature Modal
    cy.get('.type-toggle')
      .should('be.visible')
      .click();

    cy.get('.typed-signature-field')
      .should('be.visible')
      .type('Frank Ikiseh');

    //Submit Form - IMRO
    cy.get('.standard')
      .should('be.visible')
      .click();
    cy.wait('@lod').should((xhr) => {
      expect(xhr.status, 'successfull POST').to.equal(201);
    });
    // Thank you modal - NOT WORKING DUE TO CYPRESS BUG
   // Error: Webpack Compilation Error
  });
});
```

**Comment by bahmutov** [comment] 2020-09-23 14:27
Could you please create a public repo with all code reproducing the error?

**Comment by dwineknott** [comment] 2020-09-23 16:52
Hi @bahmutov, and thank you.  This repo should generate the error on 1st try:

https://github.com/dwineknott/cypress-8507

Please run the spec "US_LODapp-smoke.js"

The project baseURL is directing the test to one of our public accessible environments, leveraging dummy data.

**Comment by bahmutov** [comment] 2020-09-23 16:59
@dwineknott if I remove the `integrationFolder` from your `cypress.json` then it bundles the spec and runs (except it cannot get the QA URL specified, I don't think it is reachable)

```
"integrationFolder": "/Users/dknott/Desktop/Songtrust-E2E-master/cypress/integration/Publishing App/Smoke Test/"
```

Try using a relative path there like `cypress/integration/Publishing ...` instead of the absolute path

**Comment by dwineknott** [comment] 2020-09-23 17:17
@bahmutov Sorry about that.  I pushed an update pointing to another environment.

**Comment by bahmutov** [comment] 2020-09-23 17:26
Why do you use `"integrationFolder": "../cypress-8507/cypress/integration/Publishing App/Smoke Test/",`? Goes up the folder then back?

**Comment by bahmutov** [comment] 2020-09-23 17:28
I hit the error, very interesting case

![image](https://user-images.githubusercontent.com/2212006/94047901-b7e42b80-fda0-11ea-85f3-c28ad8066615.png)

**Comment by dwineknott** [comment] 2020-09-23 17:35
Great, I was worried it wouldn't fail!   Also good point RE: integration folder. I updated on my actual project :-) .

**Comment by bahmutov** [comment] 2020-09-24 15:58
@dwineknott do you know how inside the application the redirect to the artist page happens? After you add I believe it goes to `/add/success/<ID>` - but what is the code that actually does the redirect? Is it `window.location = ` or something else? It would give us an idea of where the thing goes sideways.

**Comment by dwineknott** [comment] 2020-09-24 16:25
@bahmutov 


Below is the the block from our codebase.  Note the "else" statement which is where window.location is set:

```
lod_success: function(response) {
        var d = Date();
        this.hideValidating();
        st.track.safeTrack(st.track.events['manage-songwriters-add-9'], {
            name:response.songwriter.full_name,
            PRO:response.songwriter.pro.name,
            Email:response.songwriter.email,
            type:"LOD Application",
            date:d,
            status:"SUCCESS"
        });

        if (ab_test_value == 1 && response.songwriter.managed_by.songwriters_used == 1) {
            this.showOnboardingModal();
        } else {
            this.reset();
            $('.nav-container .song-nav-section').show();
            window.location = '#add/success/' + response.songwriter.id;
        }
    },
```

**Comment by bahmutov** [comment] 2020-09-24 16:31
@flotwig can you see how the `window.location =` redirect is acting weird here?

**Comment by flotwig** [comment] 2020-09-24 16:37
@bahmutov yeah, does `experimentalSourceRewriting` help any?

**Comment by dwineknott** [comment] 2020-09-24 17:12
@flotwig it hasn't helped on my end.

**Comment by github-ronk** [comment] 2020-10-07 08:31
In our company we're looking at migrating from another framework to Cypress.  This issue here started to occur very frequently.   Looks like some race condition?   In any case, this is seriously thwarting our migration.  Most of the time, tests fail because of this.

**Comment by codingontheway** [comment] 2020-10-16 15:58
hello, 
i`m having the same issue. you can find the code below to reproduce it. the problem is that a lot of websites now use this dynamic routing and it needs to be supported. hope you can fix it soon.

here you can find that i went to the registration page directly but it gives the same error even if i went from the main page to the authentication page

```
const inputRegister = 'input[name=email_create]'
const registerBtn = '#SubmitCreate'

context('register new user', () => {
  beforeEach(() => {
    cy.visit(
      'http://automationpractice.com/index.php?controller=authentication&back=my-account'
    )
  })
  it('go to register page', () => {
    cy.get(inputRegister).type('abasdasdasdas@test.com')
    cy.get(registerBtn).click()
  })
})
```

**Comment by Urszulasu** [comment] 2020-10-23 13:26
@bahmutov have You any idea how resolve this problem?

**Comment by bijojoseph99** [comment] 2020-10-26 11:38
> I hit the error, very interesting case
> 
> ![image](https://user-images.githubusercontent.com/2212006/94047901-b7e42b80-fda0-11ea-85f3-c28ad8066615.png)
> 
> It seems the redirect somehow goes to our spec iframe URL, causing another Cypress runner to load.

Hi,
 Is this problem got fixed?
 I get the same error.
 Could you please help me to fix it.
Thanks

**Comment by bowens-zn** [comment] 2020-10-27 17:13
Hitting this error in 5.5.0

**Comment by bowens-zn** [comment] 2020-10-28 19:19
PSA, I'm able to get around this by restructuring my tests. If your are ok splitting whatever test you have into 2, just go into a new test right after the point where this error occurs. For example

- Test case 1: it()
  -  Test step 1
  - Test step 2 -- IF THE TEST BREAKS HERE
  - Test step 3

Split it into 2 test cases:

- Test case 1: it()
  -  Test step 1
  - Test step 2 -- The error will still occur but won't fail the test.
- Test case 2: it()
  - Test step 3

You can then use context() to group these 2 test cases together.

Of course it would be great to fix this but just putting this out there as a hack in the meantime.

**Comment by bijojoseph99** [comment] 2020-10-28 22:39
Hi,

 This is so frustrating to get this error for no reason.

 Just to check this I have made a new test file named "registraionTests.spec.js" and added this simple registration test. The baseUrl "http://automationpractice.com"  is provided under the "cypress.json" file and added the following code in the test file, which is actually going to the baseUrl first, then clicking on the "Sign in" link and then adding a unique emailId and then clicking on the "Create an account" Button. It actually takes the test to the registration page to fill the personal details then immediately redirects and gives the "Webpack compilation error". 

**describe('Registration Feature', () => {    

    it('Register a User', () => {
        cy.visit('/index.php')
        cy.get('.login').contains('Sign in').should('be.visible').click() 

        cy.get('form').within(($form) => {                       
            cy.get('#email_create').type('abcxyz123dkjhkjsdhgkjdshjgd' + '@gmail.com')
            cy.get('#SubmitCreate').click()                           
            })
    })
})**

The above test won't fail as there is no assertions, but takes me to the webpack compilation error page.
Can someone please help me to fix this.

Thanks

**Comment by mysticdevx** [comment] 2020-11-15 15:12
Using  version 5.6.0 and have still the same problem.

**Comment by ooge0** [comment] 2020-11-15 23:01
> Hi,
> 
> This is so frustrating to get this error for no reason.
> 
> Just to check this I have made a new test file named "registraionTests.spec.js" and added this simple registration test. The baseUrl "http://automationpractice.com" is provided under the "cypress.json" file and added the following code in the test file, which is actually going to the baseUrl first, then clicking on the "Sign in" link and then adding a unique emailId and then clicking on the "Create an account" Button. It actually takes the test to the registration page to fill the personal details then immediately redirects and gives the "Webpack compilation error".
> 
> **describe('Registration Feature', () => {
> it('Register a User', () => {
> cy.visit('/index.php')
> cy.get('.login').contains('Sign in').should('be.visible').click()
> 
> ```
>     cy.get('form').within(($form) => {                       
>         cy.get('#email_create').type('abcxyz123dkjhkjsdhgkjdshjgd' + '@gmail.com')
>         cy.get('#SubmitCreate').click()                           
>         })
> })
> ```

I had simple example when Cypres can't reach a requested URL because it can't do this in general. 
Why... ? Because you auth flow is related to redirection to another domain and main problem is 
```
The issue with Cypress is when the browser redirects to another 
domain URI for authentication it breaks. 

Why does Cypress break?
Simply because these redirect URIs have a strict Content-Security-Policy (CSP) directive where the iframe property `ancestors` is set to `none`.
Since Cypress works inside an iframe it breaks because of the CSP directive.
```
[SOURCE](https://medium.com/tenets/cypress-identityserver4-cracking-the-oidc-protocol-6da42289731f)
All answers here or you can build your internal solution based on the implemented authorization logic for your test app.

**Comment by mysticdevx** [comment] 2020-11-16 10:41
SOLUTION: to get rid of the problem, add below values to Cypress.json file
```
        "modifyObstructiveCode": true,
        "experimentalSourceRewriting": true
```
P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

**Comment by bijojoseph99** [comment] 2020-11-16 10:48
Thanks @mysticdevx 
It finally worked adding those couple of values to ```cypress.json``` file as you mentioned.
Thanks a lot once again.

**Comment by bowens-zn** [comment] 2020-11-18 20:20
This only occurs when using `run` including when running in `--headed` mode. I am able to use `open` but this blocks us from running this in CI.

**Comment by sortuno-ws** [comment] 2020-11-21 00:31
I'm having the same issue, some of you know which cypress version can I use in order to avoid this problem?

**Comment by Harshakapila** [comment] 2020-11-25 09:32
> SOLUTION: to get rid of the problem, add below values to Cypress.json file
> 
> ```
>         "modifyObstructiveCode": true,
>         "experimentalSourceRewriting": true
> ```
> 
> P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

Thanks, I had the same issue and this resolved it.

**Comment by jennifer-shehane** [comment] 2020-12-01 03:54
I can recreate this with this repro:

### Reproducible Example

```js
it('go to register page', () => {
  cy.visit('http://automationpractice.com/index.php?controller=authentication&back=my-account')
  cy.get('input[name=email_create]').type('abasdasdasdas@test.com')
  cy.get('#SubmitCreate').click()
})
```

By putting a debugger inside the [`window.unload` listener](https://on.cypress.io/catalog-of-events#App-Events), I can track down what caused the window to navigate to a new page and track it down to this line of code where the `document.location` is being set to a value containing a `#`.

<img width="767" alt="Screen Shot 2020-12-01 at 10 06 21 AM" src="https://user-images.githubusercontent.com/1271364/100694177-e8f26500-33bc-11eb-96b1-e6f9a6554702.png">

Something happens after this that I haven't been able to track down, because I can't reproduce it completely from this alone. But eventually the Cypress `Runner.start` calls on the wrong `document` reference and inserts its own Test Runner within the app iframe.

<img width="1141" alt="Screen Shot 2020-12-01 at 10 22 13 AM" src="https://user-images.githubusercontent.com/1271364/100695189-19d39980-33bf-11eb-8c46-8643b0289bb1.png">


### Workaround

The `experimentalSourceRewriting` configuration is meant to resolve issues related to rerouting to a `__` url, which in some cases shows up as this Webpack Compilation Error. I'm not sure why. 

Add the following to your `cypress.json` or wherever you set your config. 

```js
{
  "experimentalSourceRewriting": true
}
```

I think this workaround may not work in all cases however and there are some other bugs associated with `experimentalSourceRewriting`.

**Comment by jennifer-shehane** [comment] 2020-12-01 03:54
### Workaround

The `experimentalSourceRewriting` configuration is meant to resolve issues related to rerouting to a `__` url, which in some cases shows up as this Webpack Compilation Error. I'm not sure why. 

Add the following to your `cypress.json` or wherever you set your config. 

```js
{
  "experimentalSourceRewriting": true
}
```

I think this workaround may not work in all cases however and there are some other bugs associated with `experimentalSourceRewriting`.

**Comment by dwineknott** [comment] 2020-12-01 16:17
Yes I shared this higher up in this thread.  `experimentalSourceRewriting` is not addressing my specific case/example.

> I think this workaround may not work in all cases however and there are some other bugs associated with `experimentalSourceRewriting`.

**Comment by pebogdan** [comment] 2021-01-09 11:04
This issue is still reproducing. I try on this site https://rahulshettyacademy.com/seleniumPractise/#/ . In this moment I use Cypress 6.2.1. Here is my Code in order to reproduce:

<img width="1305" alt="Screenshot 2021-01-09 at 12 59 59" src="https://user-images.githubusercontent.com/77058130/104089868-f97ae280-527a-11eb-8716-66c0d66a949d.png">




describe('My Second Test Suite ', () => {
    it('My First Test Case', () => {
        cy.log("Go to url")
        cy.visit("https://rahulshettyacademy.com/seleniumPractise/#/")

        cy.log("Enter text")
        cy.get('.search-keyword').type('ca')

        cy.log("Wait for page to load")
        cy.wait(2000)

        //as() is allias command to replace in one variable- declare one to multiple use
        cy.get(".products").as("productLocator")

        //Parent child chaining with assertion
        cy.log("Assert the products list")
        cy.get("@productLocator").find(".product").should("have.length", 4)

        //Iterate from parent to the child and make an if to compare text and add what product we want
        //Iterate over an array of web elements
        cy.get("@productLocator").find(".product").each(($el, index, $list) => { 
            const textReach = $el.find("h4.product-name").text()
            cy.log("Product Name " + textReach)
            if(textReach.includes("Cashews")){
                $el.find("button").trigger("click")
            }
        })

        cy.get(".brand").should("have.text", "GREENKART")  

      //Use then() function in order to save something in a variable and print log in web 
      cy.get(".brand").then(function(logoelement){
        cy.log(logoelement.text())
      })

      cy.log("Click on the bag")
      cy.get('.cart-icon > img').click()

      cy.log("Click Proceed to checkout")
      cy.contains("PROCEED TO CHECKOUT").click()
    
      // cy.contains("Place Order").click()

    })

    it("My second Test case", () =>{
        //Assert if logo text is displayed correctly
      
    })
  })

**Comment by mrpimpita** [comment] 2021-02-01 01:13
> SOLUTION: to get rid of the problem, add below values to Cypress.json file
> 
> ```
> "modifyObstructiveCode": true,
> "experimentalSourceRewriting": true
> ```
> 
> P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

Excelente!! Thank 👍

**Comment by kapelo** [comment] 2021-02-10 14:48
> SOLUTION: to get rid of the problem, add below values to Cypress.json file
> 
> ```
> "modifyObstructiveCode": true,
> "experimentalSourceRewriting": true
> ```
> 
> P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

This worked for me. Thanks @mysticdevx

**Comment by grimjack** [comment] 2021-02-22 19:07
Is there any update to this issue?  I am facing the same error where the cypress runtime is getting confused. in my case, the setting the two flags is not fixing the issue.  As another datapoint, the same tests run successfully with Cypress version 5.5 and just the experimentalSourceRewriting se to true (This is needed as we use a CDN with SRI).

**Comment by dwineknott** [comment] 2021-02-22 19:38
@flotwig  or @jennifer-shehane Any updates on this bug?

**Comment by abhishekpatil173** [comment] 2021-02-25 11:53
Hi guys! I am using Cypress version 6.4.0 .  I am facing the same issue. Setting the experimentalSourceRewriting to true won't allow me to run the tests in headless mode. Is there an update on this issue?
<img width="1781" alt="Screenshot 2021-02-25 at 5 21 34 PM" src="https://user-images.githubusercontent.com/77655321/109149787-0c476900-778e-11eb-972b-90013f17ddb1.png">
@flotwig @jennifer-shehane

**Comment by abhishekpatil173** [comment] 2021-02-25 11:55
Hi guys! I am facing the same issue. I am using Cypress version 6.4.0 and I need to run the tests in headless mode. Are there any updates regarding this? @flotwig @jennifer-shehane

**Comment by RicardoFernandes8** [comment] 2021-02-26 15:17
> Is there any update to this issue? I am facing the same error where the cypress runner is getting confused. in my case, the setting the two flags is not fixing the issue. As another datapoint, the same tests run successfully with Cypress version 5.5 and just the experimentalSourceRewriting set to true (This is needed as we use a CDN with SRI).

Good afternoon, I've got exactly the same defect reported here, and using the two attributes below doesn't solved the defect. 
"modifyObstructiveCode": true,
"experimentalSourceRewriting": true

**Comment by dmitrykazakov** [comment] 2021-02-26 18:09
@RicardoFernandes8 I've got exactly the same issue too, the two attributes don't solve it. Any ideas?

**Comment by vladimircores** [comment] 2021-03-02 10:40
Super annoying problem, it happens from time to time, take a lot of time!

**Comment by rodrigovolkmer** [comment] 2021-03-18 02:13
I am also facing the same problem. 
![image](https://user-images.githubusercontent.com/9524753/111563256-bc3b4f80-87eb-11eb-9638-c0694128a5cb.png)

and using the two flags above makes the home page where I need to go to show up in a completely broken state:
![image](https://user-images.githubusercontent.com/9524753/111563186-931abf00-87eb-11eb-833e-0b9c470a2617.png)

**Comment by MaliYurt7** [comment] 2021-03-19 23:59
@RicardoFernandes8 , actually, for this issue I placed "experimentalSourceRewriting": true and my problem has been solved. 
PS: my chrome version is  89.0.4389.90 , electron 87,firefox86 and "cypress": "^6.8.0".

**Comment by Sajadu1994** [comment] 2021-03-20 00:00
G

**Comment by vishall** [comment] 2021-03-24 20:21
> SOLUTION: to get rid of the problem, add below values to Cypress.json file
> 
> ```
> "modifyObstructiveCode": true,
> "experimentalSourceRewriting": true
> ```
> 
> P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

Thank you s

> SOLUTION: to get rid of the problem, add below values to Cypress.json file
> 
> ```
> "modifyObstructiveCode": true,
> "experimentalSourceRewriting": true
> ```
> 
> P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

Thank you so much for your help

**Comment by vishall** [comment] 2021-03-28 00:28
Very frustrating experience with cypress which is stopping my ci to go green with this issue

**Comment by victorio1** [comment] 2021-04-05 11:19
> SOLUTION: to get rid of the problem, add below values to Cypress.json file
> 
> ```
> "modifyObstructiveCode": true,
> "experimentalSourceRewriting": true
> ```
> 
> P.S: `"experimentalSourceRewriting": true` creates crash problem on some environments while running through `cypress run` command. If you use `cypress open` then it works fine. If anyone finds walkaround for this, I will be happy :)

Thanks!!!!!

**Comment by bowens-zn** [comment] 2021-04-23 20:10
+1 still happening in 7.0.0

only happens when clicking the save button on our site, which leads to the malformed URL issue ( # -> __ ). the suggested workarounds have no effect.

@jennifer-shehane please take another look at this when you get the chance, this is blocking our test strategy.

**Comment by jennifer-shehane** [comment] 2021-05-06 20:58
I'm no longer able to recreate this bug from any of the previous code examples provided. 

I see people are still reporting the issue. I was hoping to see if this upcoming fix would fix the issue https://github.com/cypress-io/cypress/pull/15995 but am unable to confirm since there are no reproducible examples in this thread. 

### Reproducible example

Please provide a reproducible example that we can run to see this issue.

**Comment by jandresboyaca** [comment] 2021-05-07 17:58
@jennifer-shehane Do you know when will be released this fix?

**Comment by dwineknott** [comment] 2021-05-11 17:43
@jennifer-shehane Confirming the release of 7.3.0 fixed this issue for our team.  

Related merge:
https://github.com/cypress-io/cypress/pull/15995

**Closed** 2021-05-11 22:31 UTC
Labels: blocking, existing workaround, stage: needs information, topic: preprocessors :wrench:, type: unexpected behavior

**Comment by Rao-J** [comment] 2021-06-03 18:56
@jennifer-shehane , this issue still persists

Cypress package version: 7.4.0
Cypress binary version: 7.4.0
Electron version: 12.0.0-beta.14
Bundled Node version:
14.15.1

{code}/// <reference types="cypress" />

describe('Login Test', () => {
    it('Visit app server', () => {
        // visit app server 
        cy.visit('https://SomeLink.html')

    })

    it('Enter credential', () => {
      // type user name
      cy.get('#username')
        .type('Value1')
        .should('have.value','Value1')

      // type user name
      cy.get('#password')
        .type('Value1')
        .should('have.value','Value1')
    })

    it('Click login botton', () => {
      // click login button
      cy.get('.btn-submit').click()
      // check if login
      cy.get('#userdisplay-btnInnerEl').should('contain','Value')
    })

  }){code}

![image](https://user-images.githubusercontent.com/85312536/120697333-f67bcb00-c483-11eb-8a39-2366ea1a41ec.png)

**Comment by GuriKristine** [comment] 2022-01-10 11:41
Hi, our team had this exact issue and it turned out to be due to frame busting / frame killing implemented. I.e. our application doesn't accept being run inside a frame (which is what Cypress does). When the application detects the framing, our application forces itself to top location using a window.top.location.replace([...]).

**Comment by rogoit** [comment] 2022-04-22 11:03
"experimentalSourceRewriting": true
 
 Works for me thx for zour passion @jennifer-shehane
