### ISSUE TITLE
Excess ** in Cypress Runner Log

### ISSUE THREAD

**Issue by tit** [cypress-io/cypress#22909] opened 2022-07-24 12:17 UTC
### Current behavior

Cypress Runner Log returns:

```
assert foo: expected foo to equal **foo**
                                  ^^   ^^
```

![image](https://user-images.githubusercontent.com/278604/180646515-0d5ab63a-1778-4297-a39f-73bc12443585.png)

### Desired behavior

Cypress Runner Log should returns:

```
assert foo: expected foo to equal foo
```

![image](https://user-images.githubusercontent.com/278604/180646562-a80c1750-5131-43ab-b416-cbf77d454aae.png)

### Test code to reproduce

```javascript
expect('foo', 'foo').to.equal('foo')
```

### Cypress Version

10.3.1

**Comment by tbiethman** [comment] 2022-07-25 22:27
@tit thanks for the report, this looks like a regression from https://github.com/cypress-io/cypress/pull/22537.

**Comment by GarrisonD** [comment] 2023-09-20 07:10
Any update?

**Comment by jennifer-shehane** [comment] 2023-12-13 19:16
Duplicate of https://github.com/cypress-io/cypress/issues/24960

**Closed by jennifer-shehane** 2023-12-13 19:16 UTC
Labels: type: bug, stage: fire watch, E2E, Triaged
