### ISSUE TITLE
Binary vs NPM .bin 

### ISSUE THREAD

**Issue by guyisra** [cypress-io/cypress#6120] opened 2020-01-08 09:16 UTC
Doing `npm install`/`yarn` on a package.json where cypress exists installs cypress and its binary to the node_modules/.bin folder

But when trying to `yarn cypress run` it says that the binary is not found/installed and need to do `yarn cypress install` which then downloads the binary, unzips it and places it in `~/.cache/3.8.1/Cypress`

But then when running yarn cypress it outputs

```
It looks like you are running the Cypress binary directly.
This is not the recommended approach, and Cypress may not work correctly.
Please install the 'cypress' NPM package and follow the instructions here:
https://on.cypress.io/installing-cypress
```

Can you please clarify why I need both the downloaded binary and the npm binary and when I would use each?

**Comment by jennifer-shehane** [comment] 2020-01-08 10:04
You should only need in include Cypress in your package.json (`yarn add cypress`) and run `yarn` (do not run both `npm` and `yarn` commands mixed together)

You are not meant to run the binary directly as stated in the error message and instead should just need to run `yarn cypress run` after a correct install. 

Also make sure you have not inadvertently downloaded 2 versions of Cypress https://github.com/cypress-io/cypress/issues/4595 Or if the install got interupted, this may result in an incomplete binary install which can cause this issue. So, clean your node_modules and reinstall.

Run `cypress verify` to verify a correct installation.

**Comment by guyisra** [comment] 2020-01-08 10:51
thanks, so when would I need the binary version?

**Comment by pravynandas** [comment] 2020-01-08 17:37
Hi @guyisra, If I may answer from my experiences. The cypress npm package is a wrapper for the actual binary which gets installed in ~/.cache in linux and C:\Users\<user>\AppData\Local\Cypress\Cache in windows.

But all we need to do for a proper install is 'yarn add cypress' OR 'npm install cypress' which will internally take care of installing the actual binaries to the corresponding cache folders and the npm wrapper binaries to the node_modules/cypress (and node_modules/.bin).

Most probably, as @jennifer-shehane pointed, combining npm and yarn in the same project could have corrupted the installation (simply because they work in their own way when it comes to handling packages installation and operation). 

To start fresh, all we need to do is delete node_modules and package-lock.json and do a fresh yarn install (OR) npm install.

**Comment by jennifer-shehane** [comment] 2020-07-07 09:36
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-07 09:36 UTC
Labels: stage: awaiting response
