### ISSUE TITLE
Whoops, we can't run your tests.  This browser was not launched through Cypress. Tests cannot run.

### ISSUE THREAD

**Issue by hubertklusek** [cypress-io/cypress#8061] opened 2020-07-22 06:27 UTC
### Current behavior:
Tests on Chrome won't start. It says:

```
Whoops, we can't run your tests.  This browser was not launched through Cypress. Tests cannot run.
```

### Desired behavior:

Run tests on Chrome 79

### Test code to reproduce

Windows cmd

- `npx cypress open`
- run any test from cypress window on Chrome
- Chrome starts with "Whoops, we can't run your tests.  This browser was not launched through Cypress. Tests cannot run."

Cypress DEBUG logs attached
[cypress log.txt](https://github.com/cypress-io/cypress/files/4958229/cypress.log.txt)

also:
```
C:\Cypress>wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value

Version=79.0.3945.117
```

### Versions

Windows 10
Cypress 4.1
VS Code 1.47.2
Chrome 79.0.3945.117 32bit
behind corpo proxy.

**Comment by jennifer-shehane** [comment] 2020-07-22 07:06
Duplicate of #6889

**Closed by jennifer-shehane** 2020-07-22 07:06 UTC
Labels: topic: 😳 whoops we can't run your tests

**Comment by hubertklusek** [comment] 2020-07-22 07:32
In my case extention is not blocked:

![image](https://user-images.githubusercontent.com/19555685/88147907-26203c80-cbfe-11ea-81fb-3943e7c6fd00.png)

Deleting App Data doesn't help.

**Comment by brandonseydel** [comment] 2020-07-22 15:35
Same here...
![image](https://user-images.githubusercontent.com/5033585/88196692-19ecad00-cc07-11ea-8b7a-18daa047b659.png)

**Comment by jennifer-shehane** [comment] 2020-07-23 09:06
Please comment in the main issue that will be used to track this occurance: https://github.com/cypress-io/cypress/issues/6889
