### ISSUE TITLE
cypress run error: cypress:server:timers can not clear!

### ISSUE THREAD

**Issue by fanshyiis** [cypress-io/cypress#4586] opened 2019-06-27 09:25 UTC
Whenever I run my test case
Cypress always hangs at results, unable to end instruction
When I turn on debug mode
There's always a timer running that hasn't been cleared

![image](https://user-images.githubusercontent.com/15103283/60254398-7f854180-9900-11e9-8e72-773e15a1541c.png)

```
cypress:server:run attempting to close the browser +12s
  cypress:server:browsers killing browser process +13s
  cypress:server:timers clearing timer id 37 from queue { '37': { args: [], ms: 85000, cb: [Function] } } +13s
  cypress:server:timers queuing timer id 38 after 85000 ms +1ms
  cypress:server:timers child received timer id 38 +13s
  cypress:server:timers child sending timer id 3 +4s
  cypress:server:timers child sending timer id 22 +2s
  cypress:server:timers clearing timer id 38 from queue { '38': { args: [], ms: 85000, cb: [Function] } } +25s
  cypress:server:timers queuing timer id 39 after 85000 ms +0ms
  cypress:server:timers child received timer id 39 +19s
  cypress:server:timers clearing timer id 39 from queue { '39': { args: [], ms: 85000, cb: [Function] } } +25s
  cypress:server:timers queuing timer id 40 after 85000 ms +1ms
```
![image](https://user-images.githubusercontent.com/15103283/60254449-95930200-9900-11e9-8513-b1f245459bc6.png)

**Comment by jennifer-shehane** [comment] 2019-06-28 08:47
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4247

**Closed by jennifer-shehane** 2019-06-28 08:47 UTC
