### ISSUE TITLE
Using migration tool from 9.7.0 -> 12.6.0 does not convert `testFiles` to `specPattern` correctly

### ISSUE THREAD

**Issue by monkpit** [cypress-io/cypress#25947] opened 2023-02-24 22:00 UTC
### Current behavior

My original `cypress.json` contained `testFiles: ['array', 'of', 'globs']`.

During the guided migration, this was converted to one big string, but was done incorrectly: `specPattern: 'cypress/e2e/array,of,globs'` - `cypress/e2e` is only added to the first glob, and the rest are tacked on with comma separators.

This causes 2 problems.
1. No specs are found when Cypress starts because it doesn't parse the string as multiple globs, it seems to treat it as 1 big glob.
2. Even if it did work this way, `cypress/e2e/...` path prefix was only added to the first path element, so only 1 out of 3 globs would return spec files.

### Desired behavior

`testFiles: [ 'array', 'of', 'globs' ]` should convert to `specPattern: [ 'cypress/e2e/array', 'cypress/e2e/of', 'cypress/e2e/globs' ]` - which seems to be the only way it works correctly (for me, anyways).

### Test code to reproduce

Convert a project with `cypress.json` that has a `testFiles` value that contains an array of glob patterns.

### Cypress Version

12.6.0

### Node version

16 LTS

### Operating System

MacOS 12.6

**Comment by monkpit** [comment] 2023-02-24 22:02
Another weird thing that happened during the conversion was that none of my specs were renamed `*.cy.js`, they remained `*.spec.js` - I can file another issue if needed, but wasn't sure if it could somehow be related.

Another note - Coming from v9 with the `integrationFolder` config, it seems strange that `cypress/e2e` is required here - I would have expected some configs like `e2eFolder` and `componentFolder` to exist, but it seems like they don't.

**Comment by lmiller1990** [comment] 2023-02-27 06:05
Uh oh, sounds like the logic converting the array to a glob didn't work correctly here. Luckily you were able to fix in manually, but still worth fixing on our end.

>  none of my specs were renamed *.cy.js, they remained *.spec.js

This seems weird - all the repos I tested did this correctly. Can you share a minimal reproduction (maybe add `cypress.json` with your `testFiles` array, any other customizations you've got, and a spec or two so we can reproduce it)?

**Comment by monkpit** [comment] 2023-02-27 16:10
I'll see if I can narrow down the cause with a minimal example and share that.

**Comment by monkpit** [comment] 2023-02-27 16:22
https://github.com/monkpit/testFiles-migration-cypress-error

Note: I'm using `yarn` but I don't think it should have any effect on reproducing the issue here.

Steps to reproduce after cloning the project:
* run `yarn` to install dependencies with Cypress@9.7.0
* run `yarn cypress open` to verify that the `testFiles` array is working - we should only see specs in the `2-advanced-examples` folder, matching `a*.spec.js` and `w*.spec.js`
* run `yarn add cypress@12.6.0` to upgrade cypress
* run `yarn cypress open` again to trigger the migration process
* ⚠️ Notice: the specs do not get renamed as `*.cy.js` here
* 💣 The error occurs on the last step when migrating the config - `specPattern` contains a malformed string even in the Migration tool UI
* Finish the migration and open the e2e suite (in Chrome or whatever)
* 💣 No specs are available to run

@lmiller1990 I hope this will suffice, please let me know if you are not able to reproduce the issue. Thanks!

EDIT: If it matters - I ran this on macOS 12.6 and node 16.19.0

**Comment by lmiller1990** [comment] 2023-02-28 00:46
Right, I reproduced the issue. I think the reason we don't change anything is because if users have a custom `testFiles`, we don't necessarily know what extension they are using - it could be `testFiles: "**/*.test.js"`, or something other than the default.

Either way, we should handle this properly. I'll take a look at this one today.

**Comment by monkpit** [comment] 2023-02-28 00:51
That makes sense for renaming the specs to *.cy.ext.

But, not sure why the glob string is malformed in the resulting specPattern
:(

**Comment by lmiller1990** [comment] 2023-02-28 01:05
I'll build you a pre-release of the fix https://github.com/cypress-io/cypress/pull/25969 that you can test early, give me an hour or two, thanks!

**Comment by lmiller1990** [comment] 2023-02-28 03:07
Hi @monkpit, want to give this pre-release a try with the fix? Linux + MacOS builds: https://github.com/cypress-io/cypress/commit/e02dff7e127d8ff25ff1f85911ef4ffc42c78a42#comments

**Comment by lmiller1990** [comment] 2023-02-28 03:11
Fixed, see https://github.com/cypress-io/cypress/pull/25969 for screenshots.

**Comment by monkpit** [comment] 2023-02-28 03:56
Thanks so much! I’ll check it first thing when I get to work.

**Comment by monkpit** [comment] 2023-02-28 18:36
@lmiller1990 looks great! Thank you for the quick fix. I tested it on the repo with the original issue and it is resolved with the pre-release build.

**Comment by lmiller1990** [comment] 2023-02-28 23:40
Great! This will be in the next Cypress release (that's every 2 weeks). But since you've successfully migrated, you should be good to just go with Cypress 12.7 for now.

If you have any feedback on Cypress 12 vs Cypress 9 in general, please tell me and I will forward it to the right people.

**Closed as completed** 2023-03-01 01:25 UTC
