### ISSUE TITLE
Visibility overflow detection doesn't work as expected when a child element has position:absolute

### ISSUE THREAD

**Issue by bencao** [cypress-io/cypress#755] opened 2017-10-17 17:06 UTC
### Current behavior:

If an child element which has 'position: absolute' is placed in a parent element which contains 'overflow: hidden', the input elements in the child element will be consider not visible by cypress. But from end user perspective, it is visible and interactable.

### Desired behavior:

The visibility detection should consider this case and consider those input elements in a 'position: absolute' child element being visible.

### How to reproduce:

Repo created to demonstrate the issue:

https://github.com/bencao/cypress-visibility-detection-issue

A fiddle page which contains the above parent/child elements:

https://jsfiddle.net/benb88/8j89jbzh/3/

### Test code:

```js
describe('Visibility', function(){
  it('does not work as intended for the widget example', function() {
    cy.
      visit('https://jsfiddle.net/benb88/8j89jbzh/3/show').
      get('input.budget-input').
        // expect this input to be visible and editable
        // but it reports error saying the content is clipped by one of its parent elements
        type('135');
  });
})
```

- Operating System: MacOS 10.12.5
- Cypress Version: 1.0.2
- Browser Version: Electron 53

**Comment by brian-mann** [comment] 2017-10-17 17:13
Will look into this. We actually take this into account when performing the calculations. Will see what needs to be updated.

Here is the visibility code:
https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/visibility.coffee

And the associated tests:
https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/dom/visibility_spec.coffee

**Comment by bencao** [comment] 2017-10-17 17:25
@brian-mann Thanks, I notice there's a related test case, will read the code to find out some clue.

**Comment by jennifer-shehane** [comment] 2017-10-17 17:35
There are quite a few issues tagged as 'topic: visibility', it needs a lot of ❤️ . https://github.com/cypress-io/cypress/labels/topic%3A%20visibility

**Comment by bencao** [comment] 2017-10-17 18:08
@brian-mann I found the logic here a bit confusing:

https://github.com/cypress-io/cypress/blame/develop/packages/driver/src/dom/visibility.coffee#L185

Should the logic be "or" instead of "and"?

**Comment by liuyangcharlie** [comment] 2018-04-26 03:32
Are there any updates on this issue?
We are meeting the similar problems. The element is actually visible and able to interact, but Cypress just log that it is not visible due to being clipped by one of its parent elements. And all parents elements have no style like 'hidden', 'scroll' or 'auto'.
It is a bit annoying to avoid this case by adding `force` option. Is there any better idea?
Thx

**Comment by brian-mann** [comment] 2018-04-26 05:00
@liuyangcharlie do you mind posting a reproducible example - as minimal as possible to show how Cypress incorrectly interprets elements as not visible?

**Comment by benji011** [comment] 2019-04-19 09:14
Hi, I'm working on a project and ran into this issue. From the [docs](https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Visibility), it says that if overflow is hidden AND `position:absolute` is defined then that element being checked is considered hidden.

What I found instead to be the case is, if *either* are true then that element is hidden

**Comment by jennifer-shehane** [comment] 2019-04-24 15:51
Verified, the test case in the original post is still failing in Cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-06-07 16:29
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4395

**Closed by jennifer-shehane** 2019-06-07 16:29 UTC
Labels: stage: ready for work, topic: visibility 👁
