### ISSUE TITLE
intercept()'s minimatch glob-matching against routeMatcher url property no longer works

### ISSUE THREAD

**Issue by knotthere** [cypress-io/cypress#9379] opened 2020-11-30 17:22 UTC
### Current behavior
In Cypress 4.12.1, matching a route (`cy.route()`) with a `url` property that contains a string with minimatch syntax (`*`) works.

In Cypress 6.0.0, using `cy.intercept()` with a `routeMatcher.url` that also contains minimatch syntax fails to match.

The help at https://docs.cypress.io/api/commands/intercept.html#routeMatcher-RouteMatcher says:
> All properties are optional. All properties that are set must match for the route to handle a request. If a string is passed to any property, it will be glob-matched against the request using minimatch.The available routeMatcher properties are listed below:

### Desired behavior
Glob-matching should succeed with string properties passed to `cy.intercept()` in a `routeMatcher`.

**Comment by knotthere** [comment] 2020-11-30 17:25
I saw this, but I'm not sure if dropping minimatch support was intentional:
https://github.com/cypress-io/cypress/issues/9340#issuecomment-733977311

**Comment by flotwig** [comment] 2020-11-30 18:24
@knotthere `url` is matched as a substring or via minimatch. Can you share your test code that is not working please?

**Comment by knotthere** [comment] 2020-11-30 20:35
@flotwig - Thank you for the followup and confirmation minimatch should still be supported. I will circle back on my code and provide a repeatable example (if this was not simply user-error on my part.)

**Comment by bahmutov** [comment] 2020-11-30 20:44
Ok, I added example in https://github.com/bahmutov/cy-intercept-example - it can be tricky if the URL has query parameters.

```js
// to match "https://jsonplaceholder.cypress.io/users?_limit=3"
cy.intercept('**/users?*').as('users')
cy.get('#load-users').click()
cy.wait('@users')
```

Had to do a few tries in the DevTools console like this until found `true`

```js
Cypress.minimatch('https://jsonplaceholder.cypress.io/users?_limit=3', '**/users', {debug: true})
```

**Comment by Pirlouit** [comment] 2020-12-01 13:14
Seems to be a duplicate of #9305

**Comment by CSchulz** [comment] 2020-12-01 13:16
I am struggling with the same issue, the minimatch pattern does not work for intercept:

```
  Cypress.minimatch('http://localhost:4200/product/api/5/vehicles?producer=0005&type=450', '**/product/api/*/vehicles?*', {debug: true})
> true

  cy.intercept({
    method: 'GET',
    url: '**/product/api/*/vehicles?*',
  }).as('search');
> timeout while waiting
```

**Comment by knotthere** [comment] 2020-12-01 15:20
@Pirlouit - Yes, I began converting my `url`'s from minimatch format to RegEx to work around this, but it sounds like minimatch glob-matching should still work with `intercept()`, but it does not.

**Comment by Pirlouit** [comment] 2020-12-01 17:18
Hey @knotthere,
Yes, it definetely should. This is a bug from v6.0. I do not doubt it will be fixed in the next release.
My work around is for the mean time.

**Comment by jarretmoses** [comment] 2020-12-03 16:09
I think this is related to cypress-io/cypress#9340

**Comment by jennifer-shehane** [comment] 2020-12-07 11:44
### Reproducible Example

```js
// ✅ passes
it('cy.route() passes', () => {
  cy.server()
  cy.route('/users/search*').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users/search?=Sarah')
    xhr.send()
  })
  cy.wait('@getUrl')
})

// ❗️ fails
it('cy.intercept() fails', () => {
  cy.intercept('/users/search*').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users/search?=Sarah')
    xhr.send()
  })
  cy.wait('@getUrl')
})

// ✅ passes
it('cy.intercept() with pathname passes', () => {
  cy.intercept({
    method: 'GET',
    pathname: '/users/search*'
  }).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users/search?=Sarah')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

<img width="571" alt="Screen Shot 2020-12-07 at 6 04 43 PM" src="https://user-images.githubusercontent.com/1271364/101346264-b3ff7a00-38b6-11eb-9816-93cbe2e12f47.png">

**Comment by flotwig** [comment] 2020-12-09 19:42
The main issue here seems to be that `cy.intercept`s behavior differs from `cy.route`.

`cy.route` matches full URLs via minimatch, but if that fails, it will test against the pathname as well, as a convenience.

```js
// ✅ matches http://example.com/foo/1
cy.route('http://example.com/foo/*')
// ✅ matches http://example.com/foo/1
cy.route('/foo/*')
```

As of 6.1.0, `cy.intercept` only matches full URLs via minimatch - you must explicitly match against the `pathname` property if you want to match on pathname.

```js
// ❌ does not match http://example.com/foo/1
cy.intercept('/foo/*')
// ✅ matches http://example.com/foo/1
cy.intercept({ pathname: '/foo/*' })
// ✅ matches http://example.com/foo/1
cy.intercept('http://example.com/foo/*')
// ✅ matches http://example.com/foo/1
cy.intercept('**/foo/*')
```

Potentially, `cy.intercept` could be updated to match the old behavior:

```js
// could be updated to match against pathname or full URL, like cy.route
cy.intercept('/foo/*')
// would still only match against full URL
cy.intercept({ url: 'http://example.com/foo/*' })
// would still only match against pathname
cy.intercept({ pathname: '/foo/*' })
```

**Comment by jennifer-shehane** [comment] 2020-12-10 09:23
We have most of the examples in our docs passing the pathname as the main argument for matching in  `cy.intercept()` which is another reason I think no one expected this to be the new behavior. 

<img width="444" alt="Screen Shot 2020-12-10 at 3 49 53 PM" src="https://user-images.githubusercontent.com/1271364/101752223-a6890080-3aff-11eb-8bc7-c89ed0fd5bac.png">

A lot less examples showing the 'correct' way in 6.1.0. 

<img width="403" alt="Screen Shot 2020-12-10 at 3 51 50 PM" src="https://user-images.githubusercontent.com/1271364/101752267-b43e8600-3aff-11eb-8840-5e15ff23ca49.png">

<img width="412" alt="Screen Shot 2020-12-10 at 3 51 57 PM" src="https://user-images.githubusercontent.com/1271364/101752289-b99bd080-3aff-11eb-8382-ff72e940e215.png">

**Comment by jennifer-shehane** [comment] 2020-12-11 10:43
We are planning to update cy.intercept() to match the old behavior like cy.route() matching as Zach showed above.

**Closed** 2020-12-21 17:27 UTC
Labels: internal-priority, pkg/net-stubbing, stage: needs review, type: unexpected behavior

**Comment by knotthere** [comment] 2020-12-21 19:04
Thank you for addressing this. I await a new release so I can complete my port to Cypress 6.x.
