### ISSUE TITLE
run multiple folders

### ISSUE THREAD

**Issue by jetigbayan** [cypress-io/cypress#16319] opened 2021-05-04 06:03 UTC
Is it possible to just select multiple folders (containing tests) to run under cypress/integration?

**Comment by jennifer-shehane** [comment] 2021-05-04 15:37
Not currently. You can run a selected subset of files based on the search filter. Full instructions here: https://on.cypress.io/writing-and-organizing-tests#Run-filtered-specs

Duplicate of https://github.com/cypress-io/cypress/issues/3607

**Closed by jennifer-shehane** 2021-05-04 15:37 UTC
