### ISSUE TITLE
Bug: Response timeout when couple of the same routes are waited at the same time

### ISSUE THREAD

**Issue by dmytro-lymarenko** [cypress-io/cypress#6894] opened 2020-03-31 19:40 UTC
### Current behavior:

When we have two or more the sames requests happening on the page and we need to wait for them cypress sometimes skips the first one and therefore fails with response timeout. This happens in both **open** and **run** modes.

### Desired behavior:

It should wait for all requests correctly

### Test code to reproduce

I have created a [reproducible repository](https://github.com/dmytro-lymarenko/cypress-bug).
This repository contains some images inside /public direcroty like [bug.png](https://github.com/dmytro-lymarenko/cypress-bug/blob/master/public/bug.png) and [run bug.png](https://github.com/dmytro-lymarenko/cypress-bug/blob/master/public/run%20bug.png) to demonstrate the bug.

Hope, it will help.

### Versions
cypress - v4.3.0
os - ubuntu
browsers - chrome, firefox

**Comment by jennifer-shehane** [comment] 2020-04-01 08:57
Yes, I'm able to reproduce (sometimes)

<img width="601" alt="Screen Shot 2020-04-01 at 3 27 05 PM" src="https://user-images.githubusercontent.com/1271364/78118633-477dd280-742d-11ea-85c3-9c82f4f0c055.png">

Duplicate of #5999

**Closed by jennifer-shehane** 2020-04-01 08:57 UTC

**Comment by jennifer-shehane** [comment] 2020-12-03 03:03
This issue is fixed in 6.0.1 by migrating to our new [`cy.intercept()`](https://on.cypress.io/intercept) command (`cy.route()` is deprecated and will be removed in later versions). I ran the tests hundreds of times and never ran into this error using `cy.intercept()`.

### Before

```js
it("should fail sometimes, rerun if not ;)", () => {
	cy.server();
	cy.route("get", "/api/posts").as("getPosts");

	cy.visit("http://localhost:3000");

	cy.wait("@getPosts");
	cy.wait("@getPosts");
	cy.wait("@getPosts");
	cy.wait("@getPosts");
});
```

<img width="520" alt="Screen Shot 2020-12-03 at 9 28 37 AM" src="https://user-images.githubusercontent.com/1271364/100958273-6f887d00-354a-11eb-94a4-d4c688d64aae.png">


### After

```js
describe("Testing", () => {
	Array(200).fill(0).forEach((val, i) => {
		it(`test ${i}`, () => {
			cy.intercept("/api/posts").as("getPosts");

			cy.visit("http://localhost:3000");

			cy.wait("@getPosts");
			cy.wait("@getPosts");
			cy.wait("@getPosts");
			cy.wait("@getPosts");
		})
	})
})
```

<img width="520" alt="Screen Shot 2020-12-03 at 9 32 29 AM" src="https://user-images.githubusercontent.com/1271364/100958374-9646b380-354a-11eb-82eb-c08507c34605.png">

**Comment by dmytro-lymarenko** [comment] 2020-12-03 07:55
Great!

**Comment by jennifer-shehane** [comment] 2020-12-08 06:54
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
