### ISSUE TITLE
Still cannot open Firefox in 4.0.1 on MacOS

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6387] opened 2020-02-10 08:17 UTC
### Current behavior:

I downloaded 4.0.1. Initially I got what looked like the weird new tab issue like [the issue before](https://github.com/cypress-io/cypress/issues/6356#issuecomment-583248699) (without the `on` error) :

<img width="587" alt="Screen Shot 2020-02-10 at 2 40 28 PM" src="https://user-images.githubusercontent.com/1271364/74131687-4d1c2080-4c13-11ea-89a5-fafe03471496.png">

So then I just closed the browser and then I got this error. 

```
Cypress could not connect to Firefox.

An unexpected error was received from Marionette connection:

Error: cannot open socket

To avoid this error, ensure sure that there are no other instances of Firefox launched by Cypress running.
```

<img width="802" alt="Screen Shot 2020-02-10 at 2 35 18 PM" src="https://user-images.githubusercontent.com/1271364/74131711-5ad1a600-4c13-11ea-988c-52c0761cef5b.png">

So I'm like...ok...I hit 'Try Again', it loads the specs back up, but when I click the spec file I get this popup. 

<img width="541" alt="Screen Shot 2020-02-10 at 2 36 20 PM" src="https://user-images.githubusercontent.com/1271364/74131756-7341c080-4c13-11ea-8af3-dbf71ac50417.png">

If I click Quit, basically nothing happens, so then I was like, ok...let's create a new profile I guess. So now it launching Cypress with the 'orange striped bar' and this displaying in the second tab. 

<img width="1281" alt="Screen Shot 2020-02-10 at 2 39 26 PM" src="https://user-images.githubusercontent.com/1271364/74131813-910f2580-4c13-11ea-84f2-f6b96b6efead.png">

### Desired behavior:

Can y'all please verify that Firefox runs on my machine before the next release 😅 I can't debug other people's issues without being able to run Firefox.

### Test code to reproduce

`cypress open` or `cypress run` on MacOS Mojave 10.14.6

Debug logs at time of choosing Firefox browser

```
  cypress:server:open_project launching browser: { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false }, spec: cypress/integration/spec.js +2ms
  cypress:server:browsers getBrowserLauncher { browser: { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false } } +2s
  cypress:server:browsers opening browser { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false } +131ms
  cypress:server:browsers:firefox firefox open { projectRoot: '/Users/jennifer/Dev/cypress-transform-test', onBrowserOpen: [Function: onBrowserOpen], onBrowserClose: [Function], browsers: [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: '80.0.3987.87', path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', majorVersion: 80 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', version: '78.0.3904.0', path: '/Applications/Chromium.app/Contents/MacOS/Chromium', majorVersion: 78 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', version: '82.0.4053.0', path: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary', majorVersion: 82 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '72.0.2', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', majorVersion: 72 }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', version: '73.0', path: '/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', majorVersion: 73 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', version: '80.0.361.48', path: '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge', majorVersion: 80 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', version: '82.0.418.0', path: '/Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary', majorVersion: 82 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', version: '81.0.410.1', path: '/Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev', majorVersion: 81 }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '78.0.3904.130', path: '', majorVersion: 78, info: 'Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses.' } ], proxyUrl: 'http://localhost:65159', userAgent: null, proxyServer: 'http://localhost:65159', socketIoRoute: '/__socket.io', chromeWebSecurity: true, url: 'http://localhost:65159/__/#/tests/integration/spec.js', isTextTerminal: false, browser: { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false } } +0ms
  cypress:server:browsers:firefox available ports: { foxdriverPort: 65162, marionettePort: 65163 } +3ms
  cypress:server:browsers:utils writing extension +2s
  cypress:server:plugins plugin event registered? { event: 'before:browser:launch', isRegistered: true } +2s
  cypress:server:plugins execute plugin event 'before:browser:launch' Node 'v12.8.1' with args: { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false } { extensions: [], preferences: { 'app.normandy.api_url': '', 'app.update.checkInstallTime': false, 'app.update.disabledForTesting': true, 'apz.content_response_timeout': 60000, 'browser.contentblocking.features.standard': '-tp,tpPrivate,cookieBehavior0,-cm,-fp', 'browser.dom.window.dump.enabled': true, 'browser.newtabpage.activity-stream.feeds.section.topstories': false, 'browser.newtabpage.enabled': false, 'browser.pagethumbnails.capturing_disabled': true, 'browser.safebrowsing.blockedURIs.enabled': false, 'browser.safebrowsing.downloads.enabled': false, 'browser.safebrowsing.malware.enabled': false, 'browser.safebrowsing.passwords.enabled': false, 'browser.safebrowsing.phishing.enabled': false, 'browser.search.update': false, 'browser.sessionstore.resume_from_crash': false, 'browser.shell.checkDefaultBrowser': false, 'browser.startup.homepage': 'about:blank', 'browser.startup.homepage_override.mstone': 'ignore', 'browser.startup.page': 0, 'browser.tabs.disableBackgroundZombification': false, 'browser.tabs.warnOnCloseOtherTabs': false, 'browser.tabs.warnOnOpen': false, 'browser.uitour.enabled': false, 'browser.urlbar.suggest.searches': false, 'browser.usedOnWindows10.introURL': '', 'browser.warnOnQuit': false, 'datareporting.healthreport.about.reportUrl': '', 'datareporting.healthreport.documentServerURI': '', 'datareporting.healthreport.logging.consoleEnabled': false, 'datareporting.healthreport.service.enabled': false, 'datareporting.healthreport.service.firstRun': false, 'datareporting.healthreport.uploadEnabled': false, 'datareporting.policy.dataSubmissionEnabled': false, 'datareporting.policy.dataSubmissionPolicyAccepted': false, 'datareporting.policy.dataSubmissionPolicyBypassNotification': true, 'devtools.jsonview.enabled': false, 'dom.disable_open_during_load': false, 'dom.file.createInChild': true, 'dom.ipc.reportProcessHangs': false, 'dom.max_chrome_script_run_time': 0, 'dom.max_script_run_time': 0, 'extensions.autoDisableScopes': 0, 'extensions.enabledScopes': 5, 'extensions.getAddons.cache.enabled': false, 'extensions.installDistroAddons': false, 'extensions.screenshots.disabled': true, 'extensions.update.enabled': false, 'extensions.update.notifyUser': false, 'extensions.webservice.discoverURL': '', 'focusmanager.testmode': true, 'general.useragent.updates.enabled': false, 'geo.provider.testing': true, 'geo.wifi.scan': false, 'hangmonitor.timeout': 0, 'javascript.options.showInConsole': true, 'media.gmp-manager.updateEnabled': false, 'network.cookie.cookieBehavior': 0, 'network.http.prompt-temp-redirect': false, 'network.http.speculative-parallel-limit': 0, 'network.manage-offline-status': false, 'network.sntp.pools': '', 'plugin.state.flash': 0, 'privacy.trackingprotection.enabled': false, 'remote.enabled': true, 'security.certerrors.mitm.priming.enabled': false, 'security.fileuri.strict_origin_policy': false, 'security.notification_enable_delay': 0, 'services.settings.server': '', 'signon.autofillForms': false, 'signon.rememberSignons': false, 'startup.homepage_welcome_url': 'about:blank', 'startup.homepage_welcome_url.additional': '', 'toolkit.cosmeticAnimations.enabled': false, 'toolkit.telemetry.server': "''", 'toolkit.startup.max_resumed_crashes': -1, 'network.proxy.type': 1, 'devtools.debugger.remote-enabled': true, 'devtools.debugger.remote-host': '127.0.0.1', 'devtools.debugger.prompt-connection': false, 'devtools.chrome.enabled': true, 'app.update.auto': false, 'app.update.enabled': false, 'browser.displayedE10SNotice': 4, 'browser.download.manager.showWhenStarting': false, 'browser.EULA.override': true, 'browser.EULA.3.accepted': true, 'browser.link.open_external': 2, 'browser.link.open_newwindow': 2, 'browser.offline': false, 'browser.reader.detectedFirstArticle': true, 'browser.selfsupport.url': '', 'browser.tabs.warnOnClose': false, 'devtools.errorconsole.enabled': true, 'extensions.blocklist.enabled': false, 'extensions.checkCompatibility.nightly': false, 'extensions.logging.enabled': true, 'javascript.enabled': true, 'network.http.phishy-userpass-length': 255, 'offline-apps.allow_by_default': true, 'prompts.tab_modal.enabled': false, 'security.fileuri.origin_policy': 3, 'toolkit.networkmanager.disable': true, 'toolkit.telemetry.prompted': 2, 'toolkit.telemetry.enabled': false, 'toolkit.telemetry.rejected': true, 'xpinstall.signatures.required': false, 'xpinstall.whitelist.required': false, 'browser.laterrun.enabled': false, 'browser.newtab.url': 'about:blank', 'dom.report_all_js_exceptions': true, 'network.captive-portal-service.enabled': false, 'security.csp.enable': false, webdriver_accept_untrusted_certs: true, webdriver_assume_untrusted_issuer: true, 'toolkit.legacyUserProfileCustomizations.stylesheets': true, 'browser.tabs.drawInTitlebar': false, 'media.autoplay.default': 0, 'browser.safebrowsing.enabled': false, 'media.getusermedia.browser.enabled': true, 'media.navigator.permission.disabled': true, 'dom.min_background_timeout_value': 4, 'dom.timeout.enable_budget_timer_throttling': false, 'media.devices.insecure.enabled': true, 'media.getusermedia.insecure.enabled': true, 'network.proxy.allow_hijacking_localhost': true, 'network.proxy.http': 'localhost', 'network.proxy.ssl': 'localhost', 'network.proxy.http_port': 65159, 'network.proxy.ssl_port': 65159, 'network.proxy.no_proxies_on': '', 'devtools.debugger.remote-port': 65162, 'marionette.port': 65163 }, args: [ '-marionette', '-new-instance', '-foreground', '-start-debugger-server' ] } undefined +0ms
  cypress:server:plugins call event before:browser:launch for invocation id inv2 +3ms
  cypress:server:plugins:child execute plugin event: before:browser:launch ({ eventId: 2, invocationId: 'inv2' }) +2s
  cypress:server:plugins promise resolved for id 'inv2' with value undefined +0ms
  cypress:server:browsers:utils copied extension +28ms
  cypress:server:browsers:firefox firefox directories { path: '/Users/jennifer/Library/Application Support/Cypress/cy/production/browsers/firefox/interactive', cacheDir: '/Users/jennifer/Library/Application Support/Cypress/cy/production/browsers/firefox/interactive/CypressCache', extensionDest: '/Users/jennifer/Library/Application Support/Cypress/cy/production/browsers/firefox/interactive/CypressExtension' } +33ms
  cypress:server:browsers:firefox launch in firefox {
  url: 'http://localhost:65159/__/#/tests/integration/spec.js',
  args: [
    '-marionette',
    '-new-instance',
    '-foreground',
    '-start-debugger-server',
    '-profile',
    '/Users/jennifer/Library/Application Support/Cypress/cy/production/browsers/firefox/interactive'
  ]
} +2ms
  cypress:launcher launching browser { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false } to open about:blank +2s
  cypress:launcher spawning browser { channel: 'stable', displayName: 'Firefox', family: 'firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', isChosen: true, majorVersion: 72, name: 'firefox', path: '/Applications/Firefox.app/Contents/MacOS/firefox-bin', version: '72.0.2', isHeaded: true, isHeadless: false } with args about:blank -marionette -new-instance -foreground -start-debugger-server -profile /Users/jennifer/Library/Application Support/Cypress/cy/production/browsers/firefox/interactive +0ms
  cypress:server:browsers:firefox-util firefox: navigating page with webdriver +0ms
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:65162     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 65162 } } +2s
```

### Versions

4.0.1

**Comment by jennifer-shehane** [comment] 2020-02-10 08:28
Also reported in https://github.com/cypress-io/cypress/issues/6381 which is also MacOS Mojave

**Comment by xvyslo05** [comment] 2020-02-10 09:49
Just want to confirm the same behavior in MacOS Catalina 10.15.2. Good luck with investigation!

**Comment by flotwig** [comment] 2020-02-10 14:30
Duplicate of #6380, closing

**Closed by flotwig** 2020-02-10 14:30 UTC
Labels: OS: mac, browser: firefox, stage: needs investigating, type: bug, v4.0.0 :bug:

**Comment by bdimitrovski** [comment] 2020-02-13 08:51
Confirming issue with on macOS Catalina 10.15.1 (19B88) with Firefox 72.
