### ISSUE TITLE
Getting error "Cannot read properties of undefined (reading 'indexOf')" when using ibm_db node module.

### ISSUE THREAD

**Issue by Vsn92** [cypress-io/cypress#21295] opened 2022-05-02 15:54 UTC
### Current behavior

I am working on UI testing using Cypress and wanted to connect to DB2/zOS. I have installed ibm_db and added the below code. I am using latest version of all node, cypress and ibm_db. Same ibm_db module when executed from a simple js is able to connect to DB , but getting this error in cypress

```
describe('Test DB2',()=>{
    it('Test',()=>{
        var ibmdb = require('ibm_db');   
        let connStr= "DATABASE=DSNT;SERVER=<hostname>;UID=<username>;PWD=<password>;PROTOCOL=TCPIP;PORT=446;"
        const conn = mysql.createConnection()
        ibmdb.open(connStr, (err,conn)=>{
            if (err) return console.log(err);
            conn.query('SELECT count(*) FROM STORE', (err,data)=>{
                if (err) console.log(err);
                else console.log(data);

                conn.close(()=> {
                console.log('done');
                });
            })
        })
    })
})
```

When running i am getting the error 

TypeError: Cannot read properties of undefined (reading 'indexOf')
      at Function.getFileName (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:8347:16)
      at bindings (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:8251:48)
      at Object.eval (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:9603:86)
      at Object../node_modules/ibm_db/lib/odbc.js (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:12074:30)
      at __webpack_require__ (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:20:30)
      at Context.eval (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:8145:17)

Below is the stack trace i am getting from cypress
cypress_runner.js:194882 TypeError: Cannot read properties of undefined (reading 'indexOf')
at Function.getFileName (bindings.js:182:1)
at bindings (bindings.js:82:1)
at Object.eval (odbc.js:57:30)
at Object../node_modules/ibm_db/lib/odbc.js (odbc.js:2525:1)
at webpack_require (bootstrap:19:1)
at Context.eval (DbTest.spec.js:3:21)

### Test code to reproduce

Install ibm_db and add 

`var ibmdb = require('ibm_db');`

### Cypress Version

9.5.3

**Comment by mjhenkes** [comment] 2022-05-03 16:22
This seems to be related to this issue, https://github.com/TooTallNate/node-bindings/issues/50

You may need to customize the webpack pre-processor for cypress based on the suggestions from that issue to test the ibm_db module with cypress.

https://docs.cypress.io/api/plugins/preprocessors-api#Defaults

**Comment by mjhenkes** [comment] 2022-05-11 19:42
@Vsn92, because this appears to be an issue with another library we will be closing this issue. If any new information comes up that indicates that this issue is caused by cypress, please feel free to re-open this issue and we can take another look.

**Closed by mjhenkes** 2022-05-11 19:42 UTC
Labels: stage: awaiting response
