### ISSUE TITLE
Refused to display 'https://.......' in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by web-dave** [cypress-io/cypress#7090] opened 2020-04-21 10:12 UTC
### Current behavior:
cypress 4.4.0.
We want to test out login flow.
If the User is not logged in, we redirect to the login page and after successful login we redirect back.

But we never reach the login page, there is a Error: 
```
Refused to display 'https://.......' in a frame because it set 'X-Frame-Options' to 'deny'.
```
my cypress.json:
```json
{
  "supportFile": "cypress/support/index.ts",
  "chromeWebSecurity": false,
  "modifyObstructiveCode": false
}
```
### Desired behavior:

Page should be loaded without any errors

### Test code to reproduce
I try to find a way to share

### Versions

cypress: "4.4.0",
Chrome Version 81.0.4044.113
Node: 10.15.3
OS: win32 x64

**Comment by jennifer-shehane** [comment] 2020-04-22 09:11
Duplicate of #3459

**Closed by jennifer-shehane** 2020-04-22 09:11 UTC
