### ISSUE TITLE
Malformed dynamic iframe request crashes the test run

### ISSUE THREAD

**Issue by probablyup** [cypress-io/cypress#9165] opened 2020-11-11 04:42 UTC
### Current behavior

I'm still not sure exactly what's going on but in certain cases cypress generates a dynamic index.html which apparently requests a malformed url (see the line toward the middle with the empty string as the spec):

```
cypress:server:controllers:spec sending spec { filePath: '/home/runner/.config/Cypress/cy/production/projects/butcherbox-frontend-f90563ed0a20cb5577bcccb20d6f74c0/bundles/cypress/tests/checkoutFlow.spec.ts.js' } +452ms


  Checkout
  cypress:server:controllers:spec request for { spec: 'cypress/support/index.ts' } +3s
  cypress:server:controllers:spec sending spec { filePath: '/home/runner/.config/Cypress/cy/production/projects/butcherbox-frontend-f90563ed0a20cb5577bcccb20d6f74c0/bundles/cypress/support/index.ts.js' } +1ms
  cypress:server:controllers:spec request for { spec: '' } +1ms
  cypress:webpack get /home/runner/work/butcherbox-frontend/butcherbox-frontend +3s
  cypress:webpack load default options +0ms
  cypress:webpack setting devtool to inline-source-map +0ms
  cypress:webpack webpackOptions: { resolve: { extensions: [ '.ts', '.tsx', '.js' ], plugins: [ [TsconfigPathsPlugin] ] }, module: { rules: [ [Object] ] }, plugins: [ CircularDependencyPlugin { options: [Object] } ], watchOptions: {}, mode: 'development', entry: [ '/home/runner/work/butcherbox-frontend/butcherbox-frontend' ], output: { path: '/home/runner/.config/Cypress/cy/production/projects/butcherbox-frontend-f90563ed0a20cb5577bcccb20d6f74c0', filename: 'bundles.js' }, devtool: 'inline-source-map' } +0ms
  cypress:webpack watchOptions: {} +1ms
  cypress:webpack input: /home/runner/work/butcherbox-frontend/butcherbox-frontend +0ms
  cypress:webpack output: /home/runner/.config/Cypress/cy/production/projects/butcherbox-frontend-f90563ed0a20cb5577bcccb20d6f74c0/bundles.js +0ms
  cypress:webpack stats had error(s) +28ms
  cypress:webpack errored bundling /home/runner/.config/Cypress/cy/production/projects/butcherbox-frontend-f90563ed0a20cb5577bcccb20d6f74c0/bundles.js Webpack Compilation Error
multi .
Module not found: Error: Can't resolve '/home/runner/work/butcherbox-frontend/butcherbox-frontend' in '/home/runner/work/butcherbox-frontend/butcherbox-frontend'
Looked for and couldn't find the file at the following paths:
```

The relevant code for iframe handling is here: https://github.com/cypress-io/cypress/blob/5610f4dbe99bce1b1804a3e294d3b13b7df399cc/packages/server/lib/routes.js#L49-L62

Resulting in a run error since there's no spec at the root of the project. Relevant code (called by the iframe handler): https://github.com/cypress-io/cypress/blob/5610f4dbe99bce1b1804a3e294d3b13b7df399cc/packages/server/lib/controllers/files.js#L26-L52

Interestingly this does not happen at all locally under any run conditions. This only occurs via the cypress github action (??)

### Desired behavior

Improper iframe requests should not be generated.

### Test code to reproduce

Private repo so unfortunately I don't have a repro, however I think there might be enough info in this report to be able to get started tracing how a bad iframe request would be generated.

### Versions

Cypress 5.6.0

**Comment by jennifer-shehane** [comment] 2020-11-16 04:48
I don't understand how the error you pasted is related to the code you pointed to. Can you explain more about how you tracked this down?

How do you see an index.html being generated?

>cypress generates a dynamic index.html 

The debug line with the empty spec is coming from here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/controllers/spec.js#L28:L28

And the error being thrown that is causing the run to stop is throwing here: https://github.com/cypress-io/cypress/blob/develop/npm/webpack-preprocessor/index.ts#L276:L276

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment] 2021-02-27 00:14
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-27 00:14 UTC
Labels: stage: needs information
