### ISSUE TITLE
Your system is missing the dependency: Xvfb on linux Alpine

### ISSUE THREAD

**Issue by ruggero95** [cypress-io/cypress#29236] opened 2024-03-31 15:36 UTC
### Current behavior

When i try to run 
```
npx cypress run --headless --browser electron
```
it rejects with:
```
[FAILED] Your system is missing the dependency: Xvfb
```
(See more log in section log)

since in the [prerequisites](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) section there is no mention of linux Alpine i tried to install following lib:
```
apk add xvfb xvfb-run x11vnc fluxbox xdpyinfo st vim 
```

but the error keep raising.

There is any possibility to run cypress on alpine images? In my use case i can't run a cypress docker images since i'm into a gitlab pipeline that is already using docker:dind as base image

### Debug logs

```Text
[STARTED] Task without title.
[FAILED] Your system is missing the dependency: Xvfb
[FAILED] 
[FAILED] Install Xvfb and run Cypress again.
[FAILED] 
[FAILED] Read our documentation on dependencies for more information:
[FAILED] 
[FAILED] https://on.cypress.io/required-dependencies
[FAILED] 
[FAILED] If you are using Docker, we provide containers with all required dependencies installed.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Error: spawn Xvfb ENOENT
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Alpine Linux - 3.19.1)
[FAILED] Cypress Version: 13.7.1
Your system is missing the dependency: Xvfb
Install Xvfb and run Cypress again.
Read our documentation on dependencies for more information:
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
Error: spawn Xvfb ENOENT
----------
Platform: linux-x64 (Alpine Linux - 3.19.1)
Cypress Version: 13.7.1
```

### Cypress Version

^13.7.1

### Node version

20

### Package Manager

npm

### Package Manager Version

10.5.0

### Operating system

Linux

### Operating System Version

Alpine Linux - 3.19.1

**Comment by MikeMcC399** [comment] 2024-04-01 10:31
@ruggero95 

- There is a long history in https://github.com/cypress-io/cypress/issues/419 going back 7 years regarding fundamental issues about Cypress not being able to run on [Alpine Linux](https://www.alpinelinux.org/).
- It was also mentioned in https://github.com/cypress-io/cypress/issues/419#issuecomment-642017901 that trying to launch the binary results in an `ENOENT` error. You would also see this if you ran `npx cypress verify`.

**Comment by MikeMcC399** [comment] 2024-04-03 09:43
- I suggest to close this issue as a duplicate of #419

**Closed as not planned** 2024-04-03 18:25 UTC
Labels: type: duplicate, topic: installation
