### ISSUE TITLE
Error "" happens during the execution with each

### ISSUE THREAD

**Issue by sangmai350** [cypress-io/cypress#4362] opened 2019-06-03 04:31 UTC
### Is this a Feature or Bug?
Bug

### Current behavior:

![image](https://user-images.githubusercontent.com/37669424/58776035-c2e6db80-85f2-11e9-9702-38487d656370.png)

### Desired behavior:
No error should be found

### Steps to reproduce: (app code and test code)

I ran the script which has this line to get a list of li elements
![image](https://user-images.githubusercontent.com/37669424/58776093-05a8b380-85f3-11e9-8d54-a8e3005c1aca.png)
without this, it worked fine for a single li element but when I tried to work with list, it failed

### Versions
3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-03 04:36
This may be duplicate of https://github.com/cypress-io/cypress/issues/4310

Can you click on the yellow error with DevTools opened and take a screenshot of the stack trace printed there?

**Comment by sangmai350** [comment] 2019-06-03 04:44
Here is the stacktrace printed in Console
[image: image.png]

**Comment by sangmai350** [comment] 2019-06-03 04:46
Here is other thing
[image: image.png]

**Comment by jennifer-shehane** [comment] 2019-06-03 05:01
@sangmai350 It doesn't look like the images attach correctly to the GitHub issue when uploaded via email reply. I can't see these images

**Comment by Thanh96** [comment] 2019-06-03 05:13
![Screenshot 2019-06-03 11 46 02](https://user-images.githubusercontent.com/29529118/58777493-be252600-85f8-11e9-9c3c-57125c873cf8.png)
![Screenshot 2019-06-03 11 43 03](https://user-images.githubusercontent.com/29529118/58777507-cda46f00-85f8-11e9-8c46-423936b3acb2.png)

this's  my another account. Please help check this problem. thanks very much

**Comment by jennifer-shehane** [comment] 2019-06-03 05:18
Ah, yeah, this is actually a separate issue from the one described above. I will open a pull request for this.

**Comment by sangmai350** [comment] 2019-06-03 05:22
yeah, please take a look and let me know what the nature of the issue

**Comment by jennifer-shehane** [comment] 2019-12-18 09:20
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by jennifer-shehane** 2019-12-18 09:20 UTC
Labels: pkg/driver, stage: work in progress, type: bug
