### ISSUE TITLE
Test runner refreshes in middle of test when visiting a page whose superdomain is not the same as baseUrl.

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#14538] opened 2021-01-13 16:58 UTC
### Current behavior
When you `cy.visit` a page whose superdomain is different from `baseUrl`, the test runner reloads in the middle of a test and the test starts running again.

### Desired behavior
The test runner does not reload in the middle of a test causing the test to restart.

This is important in the application my organization is testing because the test setup steps (prior to visiting a page) are complex and make up a significant portion of the test time. Having them run twice adds significantly to our overall test runtime.

### Test code to reproduce

Using `cypress-test-tiny` as the starting point, set the `cypress.json` file to be
```
{
  "baseUrl": "https://en.wikipedia.org"
}
```
and create a spec file containing
```
describe('Runner Refresh in Middle of Test', () => {
  it('Issue', () => {
    cy.wait(5000)
    cy.visit('https://www.google.com/')
  })
})
```

Open Cypress, and run the spec file. You'll see the test load, the 5 second wait occur, and then when the `visit` action starts, the page reloads and the test starts running a second time. It does pass on the second run.

[Here's](https://share.vidyard.com/watch/JWMJ4T1aK7KrKjVu6JHjjW?) a video you can watch showing the refresh.

### Versions

I could reproduce this problem using Cypress 6.2.1 in Chrome/Edge/Election 87 and in Firefox 84 on macOS 10.15.7.

**Comment by jennifer-shehane** [comment] 2021-05-05 19:27
Duplicate of https://github.com/cypress-io/cypress/issues/2777

**Closed by jennifer-shehane** 2021-05-05 19:27 UTC
