### ISSUE TITLE
Cannot click item from cypress run navigation menu

### ISSUE THREAD

**Issue by MacGyver27** [cypress-io/cypress#17008] opened 2021-06-18 12:13 UTC
I am not able to enable developer tools.. clicking does not have any effect.. neither cycling via `alt`..
![2021-06-18_14-12-53](https://user-images.githubusercontent.com/6546231/122559173-47bcba80-d03f-11eb-9482-50a658a70dd7.gif)

I upgraded to the latest version 7.5.0
Thanks

**Comment by MacGyver27** [comment] 2021-06-18 14:49
Neither from the main cypress windows this context menu is clickable:
![2021-06-18_16-48-49](https://user-images.githubusercontent.com/6546231/122579353-1cdd6100-d055-11eb-9dd4-f94c3f4bb6e5.gif)

**Comment by jennifer-shehane** [comment] 2021-06-21 13:23
Duplicate of https://github.com/cypress-io/cypress/issues/16323

**Closed by jennifer-shehane** 2021-06-21 13:23 UTC
