### ISSUE TITLE
cy.visit() doesn't load fully page

### ISSUE THREAD

**Issue by zajacrafal** [cypress-io/cypress#2751] opened 2018-11-09 13:33 UTC
### Current behavior:

If im running my single test few times a row, most of them fail because my local host can't load fast enough but first step is finished in cypress and trying to reach elements from next steps.

https://imgur.com/a/nzrX58i

In documentation I can read that cy.visit() will load my css, js and html but as you can see on the screen, page is blank.

### Desired behavior:

If I have in step1 cy.visit() my page is fully loaded then cypress is going to next steps.

### Versions

Cypress 3.1.0, Chrome

**Comment by jennifer-shehane** [comment] 2018-11-09 18:52
@zajacrafal I'd suggest taking a look at this [FAQ question](https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-wait-for-my-application-to-load).

If you still feel it is a problem with Cypress, we will need a reproducible example that we can run ourselves in order to look into the issue.

**Comment by minams2** [comment] 2018-11-19 21:17
For last 2 to 3 days, my test is running very slow, especially when there is cy.visit() it takes 60 seconds to load, also, it is not typing into username and password immediately after login page is loaded, it takes at least 30 to 35 seconds. I saw this issue in 3.1.0, upgraded to 3.1.1, 3.1.2 but still see the same issue. I really appreciate if anyone can help me.

**Comment by jennifer-shehane** [comment] 2018-12-11 17:17
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by Akshaya0309** [comment] 2019-01-04 12:04
Previously it was not occurring but since last week it page is not  loading completely.

Please find below code.
given('recruiter is in profile database', () => {
  cy.visit('/?policy=accepted');
  cy.visit('/werkgever/inloggen');
  Login.typeRecruiterCredentials();
  cy.submit();
  cy.url().should('include', '/werkgever/uw-account');
});

when('recruiter has profile database product', () => {
  cy.get('.clearfix').contains('1× CV-Database Abonnement de Persgroep Employment Solutions 12 maanden');
});

when('recruiter searches in profile database', () => {
  cy.visit('/recruiter/kandidaten/zoeken');
  cy.get('.search-input').type('Manager');
  cy.get('.search-bar-location > .ng-untouched').type('Amsterdam');
  cy.get('.search-submit').click();
});

 cy.visit('/recruiter/kandidaten/zoeken') is not loading full page.

**Comment by jennifer-shehane** [comment] 2019-01-15 08:06
@Akshaya0309 We will need an example that we can run locally to reproduce the error, unfortunately, with the code provided, this is not possible since there is no url provided.

**Closed by jennifer-shehane** 2019-01-15 08:06 UTC
Labels: stage: needs information

**Comment by donaral** [comment] 2020-06-15 13:40
hi  @jennifer-shehane 
i have the same problem of not seeing some elements and things like h3 tags on the page when i visit page from cypress runner. 
page on chrome:
![image](https://user-images.githubusercontent.com/11408945/84663677-27d35200-af26-11ea-8ac9-08454ecc9dce.png)
page on cypress runner:
![elements-with-cypress-runner](https://user-images.githubusercontent.com/11408945/84663737-3a4d8b80-af26-11ea-9307-8c52527920ac.png)

i login via cy.request() and reuse a JWT token for the next step, cy.visit(). 
here is the screenshot of the test runner error:
![invisible-elements-error](https://user-images.githubusercontent.com/11408945/84663804-52bda600-af26-11ea-89a9-abf3cc1d46f9.png)

my test:
```
    it('should go to bounty list', () => {
      cy.visit('/profilebountyhacker.html?bid=5ee2180aa1f9648623751d8b')
      cy.get('#bountyName').contains('Auto Bounty')
    })
```
I am checking the h3 tag text starting with Auto Bounty and because it's not loading it won't find the element.
I hope you can give me an idea about the reason why the runner won't load all elements. 
thanks in advance.

**Comment by donaral** [comment] 2020-06-22 07:37
Hi, anybody to help with the issue above? do you need more detail? thanks

**Comment by nani554** [comment] 2020-06-22 07:54
@donaral  write a recursive function, untill that element and its content are not found, call that function, when its found do nothing, thats how i've managed my cy.visit() problem.
For me: after visiting i need to login so i will search for username field which is not found because the page is not loaded yet, so i have used recursive function.

**Comment by Julyanajs** [comment] 2022-04-24 20:56
@nani554  Could you provide me with an example of this function?
