### ISSUE TITLE
UX - Filter by test status in test runner

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/cypress#15668] opened 2021-03-26 05:05 UTC
### What would you like?

Users should be able to click on the failed tests or passed tests indicators in the local Cypress test runner to filter by that test status (e.g. to only see failed tests or only see passed tests).

![cypress-filters](https://user-images.githubusercontent.com/20798889/112584821-d65dca80-8db5-11eb-8e0f-2580061ce42a.png)

Ex: Clicking on the "7 failed tests" indicator should then only show those 7 failed tests.

### Why is this needed?

When I've made a bunch of probably breaking changes, I'll usually:
1. Run all my tests in Cypress's local test runner.
2. Write down which ones failed.
3. Run each of those failures individually and update the tests until they pass.

This would make it easier to see all of those failing tests in a single list.

**Comment by jennifer-shehane** [comment] 2021-03-29 18:14
Duplicate of https://github.com/cypress-io/cypress/issues/6261

**Closed by jennifer-shehane** 2021-03-29 18:14 UTC
