### ISSUE TITLE
app code that programmatically calls focus() doesn't work if the browser isn't the active window

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3639] opened 2019-03-04 21:08 UTC
### Current behavior:

Try the following test:

```js
      cy.visit('https://typescript-625eku.stackblitz.io');
      cy.get('#box').click();
      cy.wait(3000);
      cy.get('#box').trigger('keydown', {key: 'ArrowDown'});
      cy.get('#myInput').should('have.class', 'bright');
```

During the `cy.wait`, try either giving the browser focus, or giving another application focus. The test will pass/fail depending on this.

### Desired behavior:

I think that focus behavior should not be this flaky. I frequently use `cypress open` and am typing in my editor while tests are running.

### Steps to reproduce: (app code and test code)

https://stackblitz.com/edit/typescript-625eku?file=index.ts

### Versions

3.1.5

**Comment by fr0** [comment] 2019-03-04 21:12
Oddly enough, if you activate the browser window *after* the focus() method has been called, but before the test timeout occurs, it will pass. Looks like something's being queued up for when the browser is activated in that case.

**Comment by jennifer-shehane** [comment] 2019-03-06 08:08
cc @Bkucera - We've worked a lot on this focus behavior already and agree it should not be flaky.

**Comment by Bkucera** [comment] 2019-03-07 20:24
this is a duplicate of https://github.com/cypress-io/cypress/issues/1176 and is fixed in #2982

**Closed by Bkucera** 2019-03-07 20:24 UTC

**Comment by fr0** [comment] 2019-03-07 20:45
Glad to know it's going to be fixed. Can I ask the obligatory "when can I have the fix?" :D

**Comment by Bkucera** [comment] 2019-03-07 22:04
@fr0 pending code review, most likely 3.2.
