### ISSUE TITLE
cy.visit() times out when going to https://www.concursolutions.com

### ISSUE THREAD

**Issue by Maxiiimus** [cypress-io/cypress#1425] opened 2018-03-06 20:05 UTC
### Current behavior:

`cy.visit()` times out when browsing to our test and production sites.

### Desired behavior:

Login page to load.

### How to reproduce:

Use `cy.visit` to go to 'https://www.concursolutions.com/'

#### Test code:

```js
describe('Login Test', function() {
    it('Try login', function() {
        cy.clearCookies()
        cy.visit('https://www.concursolutions.com/')
    })
})
```

### Additional Info (images, stack traces, etc)
```
GET /__/ 200 28.247 ms - -
GET /__cypress/runner/cypress_runner.css 200 38.971 ms - -
GET /__cypress/runner/cypress_runner.js 200 282.340 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 1.712 ms - 77160
GET /__cypress/iframes/integration/prod_login_spec.js 200 7.353 ms - 733
GET /__cypress/tests?p=cypress/integration/prod_login_spec.js-050 200 727.258 ms - 699
GET /__cypress/tests?p=cypress/support/index.js-980 200 745.366 ms - -
GET /__/ 200 3.643 ms - -
GET /__cypress/runner/cypress_runner.css 200 38.160 ms - -
GET /__cypress/runner/cypress_runner.js 200 268.187 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.540 ms - 77160
GET /__cypress/iframes/integration/prod_login_spec.js 200 4.343 ms - 743
GET /__cypress/tests?p=cypress/integration/prod_login_spec.js-367 200 31.735 ms - 699
GET /__cypress/tests?p=cypress/support/index.js-035 200 32.833 ms - -
GET / 200 6.110 ms - -
GET /csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-view/signin.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 241.147 ms - -
GET /i18n/56E764E80A5BCEB91EF263456C0AAD56755136CB_en-us.js?lang=en%2Dus&cat=common%2Cloginjs%2Csmalljs&msk=56E764E80A5BCEB91EF263456C0AAD56755136CB 200 231.880 ms - -
GET /jscache/usermessage.js?cachekilla=DBE19FCA55EF43A05E4433AE942798E8E54A0623B8 200 242.507 ms - -
GET /csscache/minified/e8717107215e8813bfece5f3fc3a0c7584974818_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-javascript/manifest-prototypejs.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 247.877 ms - -
GET /csscache/minified/e8755bdc0b579796587f99be5e97daf4ec91b6ac_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-cnqr.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 320.647 ms - -
GET /csscache/minified/2a95ab027f221a621a23cfe3decc0399aeedeed6_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-bootstrap.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 328.636 ms - -
GET /jscache/minified/DC90B7630B00FA9776263F279313287A43C3D1EE_8D3D6DF72540E662A96CD8ECD18E9D5473FA9E1CB8.js?jslist=/j/functions.js&cachekilla=8D3D6DF72540E662A96CD8ECD18E9D5473FA9E1C 200 251.325 ms - -
GET / 200 352.819 ms - -
GET / 200 397.967 ms - -
GET /csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-view/signin.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 251.421 ms - -
GET /csscache/minified/e8717107215e8813bfece5f3fc3a0c7584974818_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-javascript/manifest-prototypejs.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 251.175 ms - -
GET /csscache/minified/e8755bdc0b579796587f99be5e97daf4ec91b6ac_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-cnqr.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 328.956 ms - -
GET /csscache/minified/2a95ab027f221a621a23cfe3decc0399aeedeed6_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-bootstrap.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 334.828 ms - -
GET / 200 372.767 ms - -
GET / 200 379.141 ms - -
GET /csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-view/signin.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 243.293 ms - -
GET /csscache/minified/e8717107215e8813bfece5f3fc3a0c7584974818_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-javascript/manifest-prototypejs.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 248.362 ms - -
GET /csscache/minified/2a95ab027f221a621a23cfe3decc0399aeedeed6_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-bootstrap.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 312.187 ms - -
GET /csscache/minified/e8755bdc0b579796587f99be5e97daf4ec91b6ac_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-cnqr.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 330.166 ms - -
GET / 200 378.954 ms - -
GET / 200 370.782 ms - -
GET /csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-view/signin.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 248.627 ms - -
GET /csscache/minified/e8717107215e8813bfece5f3fc3a0c7584974818_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-javascript/manifest-prototypejs.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 248.023 ms - -
GET /csscache/minified/e8755bdc0b579796587f99be5e97daf4ec91b6ac_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-cnqr.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 315.314 ms - -
GET /csscache/minified/2a95ab027f221a621a23cfe3decc0399aeedeed6_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-bootstrap.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 337.561 ms - -
GET / 200 376.215 ms - -
GET / 200 367.185 ms - -
GET /csscache/minified/e8717107215e8813bfece5f3fc3a0c7584974818_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-javascript/manifest-prototypejs.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 236.108 ms - -
GET /csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-view/signin.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 251.031 ms - -
GET /csscache/minified/2a95ab027f221a621a23cfe3decc0399aeedeed6_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-bootstrap.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 315.535 ms - -
GET /csscache/minified/e8755bdc0b579796587f99be5e97daf4ec91b6ac_d93fa6670e601df1d6dd19a8c553f71edddb216bb8.css?fn=/static/less/cnqr-global/manifest-cnqr.less&cachekilla=D93FA6670E601DF1D6DD19A8C553F71EDDDB216BB8 200 328.200 ms - -
GET / 200 350.193 ms - -
GET / 200 385.273 ms - -
GET / 200 360.066 ms - -
```

- Operating System: macOS Sierra Version 10.12.6
- Cypress Version: 2.1.0
- Browser Version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment] 2019-01-25 08:54
Hey @Maxiiimus, I am unable to reproduce the behavior you described. I will close as being resolved in a previous issue. Please comment here if you are still experiencing issue - and leave a reproducible example.

**Closed by jennifer-shehane** 2019-01-25 08:54 UTC
