### ISSUE TITLE
Scrolling strategy make element cannot click

### ISSUE THREAD

**Issue by Yuyz0112** [cypress-io/cypress#2302] opened 2018-08-08 03:47 UTC
### Current behavior:

As the guide documented:
> The scrolling algorithm works by scrolling the top, leftmost point of the element we issued the command on to the top, leftmost scrollable point of its scrollable container.

This cause some element cannot be clicked and the "nudge" seems not working.
I've produced a smallest example for the bug on codepen:
https://codepen.io/yuyz0112/pen/jpeZvZ

Cypress code:
`cy.contains('3').click();`

After execute click command, the item contains '3' scrolled to the top and was covered by the mask element.

![image](https://user-images.githubusercontent.com/13651389/43815115-a16bdbc8-9b00-11e8-9314-ecaba5849dba.png)

### Desired behavior:

I'm not sure whether this situation should be covered by the scrolling strategy, but I still expect a method to test this without change my code.

### Versions

v3.0.3

**Comment by Yuyz0112** [comment] 2018-08-08 04:04
I think this is related to #871 , is there any updates on that issue?

**Comment by Yuyz0112** [comment] 2018-08-08 05:12
https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L230
Looks like I can disable the verify process by adding `{ force: true }`?
If I'm right I can close this issue.

**Comment by jennifer-shehane** [comment] 2018-08-08 22:49
Yes, you can disable our checks on whether the element is 'clickable' by just passing `{ force: true}`, but ideally the click here should work without you having to do that.

**Comment by Yuyz0112** [comment] 2018-08-09 01:59
@jennifer-shehane 
Ok, so I'm going to keep this issue open.
But what you mean is that Cypress will not scroll automatically since the target element will be covered by another(The mask element is not the ancestor of target element), or Cypress will scroll but can still click when target element was covered?

**Comment by brian-mann** [comment] 2018-08-09 02:03
Cypress is supposed to automatically scroll the element into view - but due to `Element#scrollIntoView` it is technically possible the browser scrolls the element in a way that is impossible for the user to have done, and it can create situations in which the DOM is completely locked and it is incapable of "scrolling" to get it into view.

This looks like one of these situations. We've internally decided that our algorithms should *always* scroll (to be deterministic) but we've been reconsidering this since scrolling is a mutation and there have been side effects that cause problems like these.

And/or in addition to, we've been considering just allowing you to pass a `{ scroll: false }` or even change the scrolling strategy to be that of "if-necessary", "middle", "bottom", etc.

**Comment by Yuyz0112** [comment] 2018-08-09 02:27
@brian-mann 
Yeah, I think cover all the case of scroll into view is really hard, an configurable scrolling strategy may solve most of the problems.
But now `{ force: true }` already help me in this situation, so maybe we can close this issue and keep tracking the configurable strategy implementation in #871?

**Comment by SLOBYYYY** [comment] 2018-08-09 15:21
I'm having the same issue. The problem is that the "changeable scrolling strategy" feature (#871) was discussed about a year ago and nothing has happened so far.

Please don't close this.

**Comment by Bkucera** [comment] 2018-12-18 20:17
This should be fixed when we change our default scroll strategy to center the element in the viewport, part of 4.0

**Comment by TheBestPessimist** [comment] 2019-08-05 06:18
Also having problems with overscrolling. Check the video: https://github.com/cypress-io/cypress/issues/871#issuecomment-509392310

**Comment by jennifer-shehane** [comment] 2020-10-21 05:41
### Reproducible example:

`spec.js`

```js
it('can click the 3 behind masked el', () => {
  cy.visit('index.html')
  cy.contains('3').click()
})
```

`index.html`

```html
<html>
  <style>
    .item {
      padding: 15px;
      background: lightsteelblue;
    }
  </style>
  <body>
    <div class="container" style="width: 400px;">
      <div class="mask" style="padding: 15px; background: lightpink; z-index: 2; position: relative;">mask</div>
      <div class="long-list" style=" height: 300px; overflow: auto; margin-top: -48px;">
        <div class="item">placeholder</div>
        <div class="item">1</div>
        <div class="item">2</div>
        <div class="item">3</div>
        <div class="item">4</div>
        <div class="item">5</div>
        <div class="item">6</div>
        <div class="item">7</div>
        <div class="item">8</div>
        <div class="item">9</div>
        <div class="item">10</div>
      </div>
    </div>
  </body>
</html>
```
<img width="828" alt="Screen Shot 2020-10-21 at 12 11 14 PM" src="https://user-images.githubusercontent.com/1271364/96677903-945bd300-1396-11eb-86b9-f8bd5cb81ca4.png">

**Comment by itayod** [comment] 2020-11-17 17:28
it seems like the problem is that cypress call "scrollIntoView" which hides the element when the element has a parent element with scroll.
if that's the case then:
```ts 
element.scrollIntoView({block: "end"});
```
should fix that.

**Comment by Bkucera** [comment] 2020-11-23 21:29
closing this as a duplicate of #871, which has an associated PR open

**Closed by Bkucera** 2020-11-23 21:29 UTC
Labels: stage: ready for work, topic: scrolling ↕️, type: bug

**Comment by jennifer-shehane** [comment] 2020-12-08 05:24
In Cypress 6.1.0, there’s a new `scrollBehavior` configuration option that controls the viewport position when an element is scrolled prior to action commands. Possible values are `'top'`, `'bottom'`, `'center'`, `'nearest'`, and `false`, with `'top'` being the default. `scrollBehavior: false` disables scrolling altogether. `scrollBehavior` can be specified in [global configuration](https://on.cypress.io/configuration#Actionability), [test configuration](https://on.cypress.io/writing-and-organizing-tests#Test-Configuration) or individual [action commands](https://on.cypress.io/interacting-with-elements) via options.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
