### ISSUE TITLE
Process Crash During Cypress Test Execution

### ISSUE THREAD

**Issue by Tomoppenheimer** [cypress-io/cypress#30807] opened 2024-12-29 10:09 UTC
### Test code to reproduce

The Chrome Renderer process crashes with the error message "Aw, Snap! Something went wrong while displaying this webpage," along with an error code of STATUS_BREAKPOINT. Attached are screenshots of the issue for your reference:

![image](https://github.com/user-attachments/assets/e067fe01-7544-4b0d-a986-4cb77110aafb)
![image](https://github.com/user-attachments/assets/90664000-7b70-49f5-847c-e94a22b9ff2f)

From the logs, I noticed the following suggestions:
Increase CPU/memory resources on the machine.
Enable experimentalMemoryManagement in the Cypress configuration file.
Lower the numTestsKeptInMemory value during cypress open.

Despite attempting some of these solutions, the issue persists intermittently, particularly during some specific tests.
Here is some additional context about my setup:
Cypress version: 13.16.1 (issue occurs also in version 13.17.0)
Browser: [Chrome version131]
Machine specs: 12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz, 40.0 GB RAM (Issue also occurs in MacBooks)

![image](https://github.com/user-attachments/assets/251068b7-f640-4435-9f4d-9dda61d0c48b)

![image](https://github.com/user-attachments/assets/d05d7e96-e20c-4929-bf92-8a04952d4128)

### Cypress Mode

cypress open

### Cypress Version

13.16.1 and 13.17.0

### Browser Version

131.0.6778.205 (Official Build) (64-bit)

### Node version

 v20.10.0

### Operating System

Windows 10 and 11, and macOS ersion 15.2 (24C101)

### Other

It happens also in Headless mode.

**Comment by jennifer-shehane** [comment] 2024-12-30 14:53
@Tomoppenheimer Could you provide a reproducible example? If so, please add it to this issue, which this is a duplicate of https://github.com/cypress-io/cypress/issues/27415

These are hard to track down honestly because it could be a number of causes including the application under test having a memory leak itself.

**Closed as not planned by jennifer-shehane** 2024-12-30 14:53 UTC
Labels: type: duplicate
