### ISSUE TITLE
Cypress Clearing Cookies During Test Execution

### ISSUE THREAD

**Issue by jtmgio** [cypress-io/cypress#747] opened 2017-10-16 20:42 UTC
- Operating System: OSX
- Cypress Version: 1.0.2 
- Browser Version: CHROME Version 61.0.3163.100 (Official Build) (64-bit)

### Is this a Feature or Bug?
This is a bug

### Current behavior:
When cypress is executing tests, cypress for some reason clears the browser cookies. This is unexpected behavior and is making the Cypress un-useable. 

### Desired behavior:
For cypress not to touch browser cookies during testing. 

### How to reproduce:
See my code

#### Test code:
This is an angular 2 application.

```js
/****** 
INDEX INTEGRATION TEST
- calls all of the test for testing a sub section of our application
- This is run after Jenkins builds the application or run on a local machine
*******/
"use strict";
import { _login } from '../../common/authenticate';
import { _navigate } from "../../common/navigate";
import * as headerTests from "./inc/header.spec";
import * as createFormModalTests from "./inc/create-form-modal.spec";
import * as showArchivedFormsTests from "./inc/show-archived-forms.spec";
import * as searchFormsTests from "./inc/search-forms.spec";
import * as tableSortingTests from "./inc/table-sorting.spec";
import * as tableActionTests from "./inc/table-actions.spec";
let formlist_url = "/administrator/index.php?option=com_mcform&view=ngformlist";
let orgid = "demo2";

context( "Authenticate", () => {
	_login( orgid );	
})
context( "Navigation", () => {
	_navigate( formlist_url );
})
context( "Forms List -> ", () => {
	describe( "Form List Header Toolbar ->", () =>{
		headerTests.executeCyTest();
	})
	describe( "Create Form Modal ->", () => {
		createFormModalTests.executeCyTest();
	})
	describe( "Show Archived Forms ->", () => {
		showArchivedFormsTests.executeCyTest();
	})	
	describe( "Search for Forms ->", () => {
		searchFormsTests.executeCyTest();
	})
        //HERE IS WHERE WE LOSE THE COOKIES
	describe( "Table sorting", () => {
		tableSortingTests.executeCyTest();
	});
})
/******
TABLE-ACTIONS.SPEC
- We use cypress to click a button which in turn calls a modal. 
- This modal executes an HTTP GET request
- By the time we open the modal, the cookies have been cleared, thus  the HTTP call fails due to dependencies on a token in the browser cookie. 
*********/
"use strict";
function cypressTest( path ){
	describe( "Table action should appear on hover", () => {
		it( "should show the action buttons on hover", () => {
			cy.get("table.td-data-table tr.td-data-table-row" ).eq( 1 )
				.find( "td.column6 > div button" ).eq( 1 ).click({ force : true })
		});
	})
}
module.exports = {
	executeCyTest : cypressTest
}
```

### Additional Info (images, stack traces, etc)
A utility to turn off automatic cookie removal.

**Comment by brian-mann** [comment] 2017-10-16 20:50
This isn't a bug, Cypress specifically does this to prevent tests from building up state.

But we agree with you, I've documented in glory here about why we shouldn't be doing that. 

https://github.com/cypress-io/cypress/issues/686

I'll keep this issue open, but this is something we're definitely aware of, and will be giving you API's to control this to exactly how you'd like.

BTW there are API's already there for controlling which cookies don't get removed.

https://docs.cypress.io/api/cypress-api/cookies.html#Preserve-Once

I also agree that this is very unexpected and not documented well enough in high traffic areas.

**Comment by jtmgio** [comment] 2017-10-17 01:47
@brian-mann Thank you for the quick response. I believe the "Preserve-Once" will work for what i need here. I will try this out tomorrow morning and respond back. 

I really like the cypress.io tool. Keep up the good work guys/girls!

**Comment by jtmgio** [comment] 2017-10-17 14:29
@brian-mann Using the "defaults" method worked perfect. I attached my code for reference. Thanks again for the quick response. 

```js
describe( "Memberclicks Tests", () =>{
	
	beforeEach(() => {
		Cypress.Cookies.defaults({
			whitelist: [ "mcid_token", "serviceID" ]
		});
	})

	context( "Authenticate", () => {
	
		_login( orgid );	
	})

	context( "Navigation", () => {
		_navigate( formlist_url );
	})

	context( "Forms List -> ", () => {
		
		describe( "Form List Header Toolbar ->", () =>{
			headerTests.executeCyTest();
		})

		describe( "Create Form Modal ->", () => {
			createFormModalTests.executeCyTest();
		})
		
		describe( "Show Archived Forms ->", () => {
			showArchivedFormsTests.executeCyTest();
		})
		
		describe( "Search for Forms ->", () => {
			searchFormsTests.executeCyTest();
		})
		
		describe( "Table sorting", () => {
			tableSortingTests.executeCyTest();
		})

		describe( "Table Actions", () => {
			tableActionTests.executeCyTest();
		})
		
	})
})

```

**Comment by brian-mann** [comment] 2017-10-17 17:18
Closing because this is not a bug, and is referenced elsewhere.

**Closed by brian-mann** 2017-10-17 17:18 UTC

**Comment by alexkb0009** [comment] 2018-03-29 14:37
@brian-mann thanks for the tip! Is there anything similar to `Cypress.Cookies.preserveOnce()` for localStorage/sessionStorage?

Also +1 for #686 as is my first week with Cypress and inherently assumed tests within the same context would preserve browser state (cookies & localStorage) (as in, that that is primary purpose of 'context'). Re: same issue, think having it in config is a good thing (vs `Cypress.lifecycle(...)` approach) because it simplifies/reduces amount of places where config can live and already have the ability to modify config within test itself.

**Comment by musicformellons** [comment] 2018-04-10 20:04
Any idea why this does not work on headless mode?
