### ISSUE TITLE
how to suppress installation progress when deploying to heroku

### ISSUE THREAD

**Issue by udos** [cypress-io/cypress#2988] opened 2018-12-25 17:05 UTC
I'm using CircleCI and when deploying to Heroku (to a special dev environment in which I need other npm dev dependencies) my console is "flooded" with cypress progress output like the following:

![image](https://user-images.githubusercontent.com/141107/50425406-aab9a600-0875-11e9-9a8a-3d9771f403aa.png)

is there a possibility to reduce this to something shorter or suppress it?

thanks

**Comment by jennifer-shehane** [comment] 2018-12-26 10:34
Duplicate of https://github.com/cypress-io/cypress/issues/1243, see the comments in that issue for possible workarounds.

**Closed by jennifer-shehane** 2018-12-26 10:34 UTC
