### ISSUE TITLE
`window:confirm` does not always reject the confirmation on returning false

### ISSUE THREAD

**Issue by wawhal** [cypress-io/cypress#1851] opened 2018-06-01 12:47 UTC
### Bug

`window:confirm` does not work as expected.

### Current behavior:

Cypress accepts the confirmation in this case (even when returning false):

```js
cy.on('window:confirm', str => {
    expect(str === `Are you sure?`).to.be.true;
    return false;
});
```

Successfully cancels the confirmation in this case:

```js
cy.on('window:confirm', str => {
    return false;
});
```

### Desired behavior:

Both the snippets above should make cypress cancel the confirmation.

### Versions

Cypress: 2.1.0
OS: Linux x86_64 (Ubuntu 16.04)
Browser: Google Chrome 62.0.3202.89

**Comment by jennifer-shehane** [comment] 2019-07-23 11:45
I'm unable to reproduce this in Cypress 3.4.0. Closing as resolved. 

My test code

```js
it('Test', () => {
  cy.on('window:confirm', str => {
    expect(str === `Are you sure?`).to.be.true;
    return false;
  });
  cy.visit('index.html')
  cy.get('#main').contains('NO')
})
```

My app code

```html
<!DOCTYPE html>
<html>
<head>
  <script>
    window.onload = function () {
      if (window.confirm("Are you sure?")) {
        window.document.getElementById('main').innerHTML = 'YES'
      } else {
        window.document.getElementById('main').innerHTML = 'NO'
      }
    }
  </script>
</head>
<body>
  <div id="main"></div>
</body>
</html>
```

**Closed by jennifer-shehane** 2019-07-23 11:45 UTC
Labels: stage: needs investigating
