### ISSUE TITLE
Clicking on a "mailto" link cause cypress 10.10.0 / electron to crash

### ISSUE THREAD

**Issue by diggabyte** [cypress-io/cypress#24371] opened 2022-10-24 21:08 UTC
### Current behavior

Clicking on a mailto link causes cypress / electron to crash. Earlier versions of cypress, this did not occur.

### Desired behavior

Ignore trying to open a mailto link

### test.html
```
<a href="mailto:example@example.com"  target="_blank" rel="noopener noreferrer">
  example@example.com
</a>
```
### test.ts
```
it('should not crash when a mailto: link is clicked', () => {
  cy.visit('/test.html');
  cy.get('a[href="mailto:example@example.com"]').click();
});
```

### Cypress Version

10.10.0

### Node version

16.16.0

### Operating System

macOS 12.4

### Debug Logs

```shell
[object Object]
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)

ERR_FAILED (-2) loading 'mailto:example@example.com'
Error: ERR_FAILED (-2) loading 'mailto:example@example.com'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)

grep: /usr/share/applications//: Is a directory
/usr/bin/xdg-open: 882: x-www-browser: not found
/usr/bin/xdg-open: 882: firefox: not found
/usr/bin/xdg-open: 882: iceweasel: not found
/usr/bin/xdg-open: 882: seamonkey: not found
/usr/bin/xdg-open: 882: mozilla: not found
/usr/bin/xdg-open: 882: epiphany: not found
/usr/bin/xdg-open: 882: konqueror: not found
/usr/bin/xdg-open: 882: chromium: not found
/usr/bin/xdg-open: 882: chromium-browser: not found
/usr/bin/xdg-open: 882: google-chrome: not found
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening 'mailto:example@example.com'
/usr/bin/xdg-email: 786: x-www-browser: not found
/usr/bin/xdg-email: 786: firefox: not found
/usr/bin/xdg-email: 786: iceweasel: not found
/usr/bin/xdg-email: 786: seamonkey: not found
/usr/bin/xdg-email: 786: mozilla: not found
/usr/bin/xdg-email: 786: epiphany: not found
/usr/bin/xdg-email: 786: konqueror: not found
/usr/bin/xdg-email: 786: chromium-browser: not found
/usr/bin/xdg-email: 786: google-chrome: not found
/usr/bin/xdg-email: 786: www-browser: not found
/usr/bin/xdg-email: 786: links2: not found
/usr/bin/xdg-email: 786: elinks: not found
/usr/bin/xdg-email: 786: links: not found
/usr/bin/xdg-email: 786: lynx: not found
/usr/bin/xdg-email: 786: w3m: not found
xdg-email: no method available for opening 'mailto:example@example.com'
ERROR: 1
error Command failed with exit code 1.
```

**Comment by amehta265** [comment] 2022-11-07 15:46
@diggabyte Thank you for opening an issue and providing your tests.
Unfortunately I have been unable to reproduce this issue on my end. After inserting the link in my `index.js` file, I first ran my application on my `localhost`.
While running the application, I started `npx cypress:open` on another terminal and ran my test.
```
it('should not crash when a mailto: link is clicked', () => {
    cy.visit('http://localhost:3000')
    cy.get('a[href="mailto:example@example.com"]').click();
});
```
Because my application was served on `localhost:3000` I have to visit that page.
This is what the test looks like on my end:
<img width="1727" alt="Screenshot 2022-11-07 at 10 44 05 AM" src="https://user-images.githubusercontent.com/65267668/200352602-4aa8e782-6539-4667-8bbd-e915bff98573.png">

The only thing I can think about with a reproducible example is that you may not be serving your application i.e. `test.html` before running Cypress. This could result in the link not working. You should run your application on your local machine and then run cypress (if you are not doing this already)

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marktnoonan** [comment] 2022-11-15 20:52
Confirmed this is an issue in 11.1.0 when using Electron and the markup provided. Confirmed Chrome doesn't crash in the same circumstances.

The error I got is below. This does not replicate if I take away the `target="_blank"`. @diggabyte in the short term, it seems like you could assert the `href` instead of clicking the link in most situations. Or if you have to click it, you could modify the target first.

In the mean time I will route this to team to take a closer look.

```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
ERR_FAILED (-2) loading 'mailto:example@example.com'
Error: ERR_FAILED (-2) loading 'mailto:example@example.com'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-x64 (21.6.0)
Cypress Version: 11.1.0
```

**Comment by jennifer-shehane** [comment] 2023-12-13 16:07
This appears to work fine in 13.6.1 during cypress open and cypress run with Electron. I have no idea why you would be testing this exactly though.

**Closed as completed by jennifer-shehane** 2023-12-13 16:07 UTC
Labels: E2E, Triaged
