### ISSUE TITLE
Cannot run Cypress on Ubuntu 18.04

### ISSUE THREAD

**Issue by tgrander** [cypress-io/cypress#6212] opened 2020-01-21 20:19 UTC
### Current behavior:

![Screen Shot 2020-01-21 at 3 13 59 PM](https://user-images.githubusercontent.com/15262143/72839763-dec1ef00-3c60-11ea-93f2-c0f337329ca7.png)

I run npm install in my git repo, install all Cypress dependencies with `apt-get`, and run `npx cypress run`. The error above is shown. 

### Desired behavior:

Cypress can be opened and ran

### Test code to reproduce

Install Cypress on Ubuntu 18.04 and try to run it

### Versions

Cypress Version : 3.8.2
OS : Ubuntu 18.04.3
Browser : Chrome

**Comment by jennifer-shehane** [comment] 2020-01-22 05:53
There are updated instructions on the required dependencies in our docs here: https://on.cypress.io/guides/guides/continuous-integration#Dependencies

Can you verify you have installed all listed dependencies then run `cypress verify` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by jin60641** [comment] 2020-01-22 07:27
> There are updated instructions on the required dependencies in our docs here: https://on.cypress.io/guides/guides/continuous-integration#Dependencies
> 
> Can you verify you have installed all listed dependencies then run `cypress verify` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

Thanks for reply! But the link you gave is not valid. I think that was https://on.cypress.io/guides/guides/continuous-integration.html#Dependencies

**Comment by tgrander** [comment] 2020-01-22 13:55
I have installed all listed dependencies. My first screenshot [here](https://github.com/cypress-io/cypress/issues/6212#issue-553106524) captures that. 

Running `DEBUG=cypress:* npx cypress verify` prints the following:

![Screen Shot 2020-01-22 at 8 52 11 AM](https://user-images.githubusercontent.com/15262143/72899692-83414100-3cf4-11ea-947c-069f5b4f2b41.png)

The error message from Cypress is not helpful at all. It is just `Command failed: /home/ubuntu/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=26`

If I run the command that failed, `/home/ubuntu/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=26`, then I get the message: `(Cypress:20557): Gtk-WARNING **: 13:54:26.751: cannot open display:`

**Comment by tgrander** [comment] 2020-01-22 18:15
Update: if I do `brew cask install xquartz` on my machine then I am able to successfully do `cypress run` on the Ubuntu machine I am ssh'd into. However this will not work in the CI environment. This seems like a problem with Cypress. Is there a way to run Cypress without the GUI?

**Comment by tgrander** [comment] 2020-01-22 18:59
UPDATE: it works fine on Ubuntu 16, which leads me to believe that Cypress is incompatible with Ubuntu 18

**Comment by flotwig** [comment] 2020-01-22 19:52
Hey @tgrander, I am running & developing Cypress on Ubuntu 19.10, I'd be surprised if it was incompatible with 18.04. It seems like something is wrong with your X setup, do you use Wayland or X normally?

**Comment by flotwig** [comment] 2020-01-22 19:54
Normally, in CI, Cypress uses `xvfb` to set up a virtual framebuffer, so you don't need to do the X situation you're describing. It only does this if the `DISPLAY` environment variable is blank, so does running `DISPLAY= npx cypress run` work for you @tgrander ?

**Comment by tgrander** [comment] 2020-01-22 19:57
@flotwig I'm not using X at all on either the Ubuntu 16.04 or the 18.04 machine and yet it does work on 16.04

I tried running `DISPLAY= npx cypress run` on 18.04 and that does not work either

**Comment by flotwig** [comment] 2020-01-22 20:05
> @flotwig I'm not using X at all on either the Ubuntu 16.04 or the 18.04 machine and yet it does work on 16.04
> 
> I tried running `DISPLAY= npx cypress run` on 18.04 and that does not work either

Yeah bizarre, I was able to reproduce this locally by running Ubuntu 18.04 in Docker. 

Wrapping it in `xvfb` should work as a workaround, try this: `xvfb-run npx cypress run`

**Comment by bahmutov** [comment] 2020-01-22 20:07
This is a duplicate of https://github.com/cypress-io/cypress/issues/6184 see temp workaround https://github.com/cypress-io/cypress/issues/6184#issuecomment-577308973

A fix has been merged in https://github.com/cypress-io/cypress/pull/6199 and will be released in 3.8.3

**Closed by bahmutov** 2020-01-22 20:07 UTC
Labels: stage: awaiting response
