### ISSUE TITLE
Sharing Context with an object is undefined upon 2nd usage

### ISSUE THREAD

**Issue by tiwatson** [cypress-io/cypress#5471] opened 2019-10-25 14:51 UTC
### Current behavior:

Using a before hook to wrap an object and alias it only allows that object to be accessed once. The 2nd time it is accessed it is undefined. A string works as expected. 

### Desired behavior:

When aliasing an object in a before hook I expect to have access to that object in all `it` blocks

### Steps to reproduce: (app code and test code)

```js
describe('Shared Context Bug', () => {
  before(() => {
    cy.wrap('foobar').as('a')
    cy.wrap({ value: 'foobar' }).as('b')
  })

  it('should exist', function () {
    expect(this.a).to.eq('foobar')
    expect(this.b.value).to.eq('foobar')
  })

  it('should exist 2nd time', function () {
    expect(this.a).to.eq('foobar')
    expect(this.b.value).to.eq('foobar') // Cannot read property 'value' of undefined
  })
})
```

### Versions

3.4.1 - Chrome 76 - macOS

**Comment by jennifer-shehane** [comment] 2019-10-25 15:48
`before` code is only run once, and between the tests Cypress removes all of the aliases. So in subsequent tests it is not available.

Moving this code into a `beforeEach` will work.

Closing as duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2019-10-25 15:48 UTC

**Comment by tiwatson** [comment] 2019-10-25 15:54
I don't want a beforeEach though. That is just more overhead. 

I'd suggest updating documents to reflect this removal of all aliases after multiple test. 
And how come the string version of `this.a` does not get removed? 

/shrug

**Comment by jennifer-shehane** [comment] 2020-01-03 08:42
@tiwatson Please comment in the original issue, not to duplicates so that we can focus conversation in one place https://github.com/cypress-io/cypress/issues/665#issuecomment-552961024
