### ISSUE TITLE
Performance Regression in 3.x

### ISSUE THREAD

**Issue by arahansen** [cypress-io/cypress#1915] opened 2018-06-09 16:19 UTC
### Current behavior:

Running 13 spec files in cypress@3.0.1 takes 152 seconds (including test compilation and execution)

### Desired behavior:

Running 13 spec files in cypress@2.1 takes 79 seconds (including test compilation and execution)

### Steps to reproduce:

My guess is that this regression is related to Cypress now running tests in isolation. There appears to be a lot of setup and teardown time between specs running. Is there anyway around this? Cypress taking twice as long to run the same test suite is surprising. 

I'm not sure I can justify upgrading to 3.0 with this issue. It at least will make me think long and hard whether I can justify adding another test when it will be a significant impact to my CI run times.

**UPDATE**: My tests currently do an `afterEach(() => { cy.screenshot() })` removing this cuts down execution time to 110 seconds.

### Versions

cypress@3.0.1

**Comment by brian-mann** [comment] 2018-06-09 20:30
We're aware of the regression. It's a combination of things, some of which we can fix.

There's an open PR fixing the `cy.screenshot` performance issues here: https://github.com/cypress-io/cypress/pull/1864

Opening + closing the browser will add a bit of extra time, but it shouldn't be as drastic as what you're seeing, maybe only 1-3 seconds per additional spec file. 

We noticed the same performance drop in our own internal tests but haven't yet spent the time to identify the root cause other than what I mentioned. Even tests on a single spec are taking longer.

**Comment by arahansen** [comment] 2018-06-10 00:01
Thanks for the update @brian-mann. Happy to provide more diagnostics if it would help!

I'll keep an eye out for other possible offenders too.

**Comment by chrislopresto** [comment] 2018-09-24 15:52
We're seeing a similar performance regression from Cypress 2.1 to Cypress 3.1: 

- 72 spec files
- Representative Cypress 2.1 run: **317 seconds**
- Representative Cypress 3.1 run (no parallelization): **670 seconds**

This would indicate a thoroughly unscientific, approximate ~5 second penalty per spec file. 🙂

With Cypress 3's built-in parallelization (6 workers appears to be our sweet spot), we can improve the time of the overall test suite run to **96 seconds**, so that's fantastic. For better or worse that shifts our conversation to evaluating among a few options:

- Hold steady on Cypress 2
- Combine tests into fewer files. Presumably help unparallelized build time on free plan, hurt parallelized build time on paid plan.
- Upgrade to paid plan to use Cypress 3's built-in parallelization
- Use our own parallelization scheme on Cypress 3 free plan

We're happy to provide diagnostics and help dig in for troubleshooting as well. Cheers!

**Comment by jennifer-shehane** [comment] 2019-07-23 13:01
We fixed many performance issues recently. Please update to our latest version and see if these issues still persist. Comment here if so and we will reopen. 

Also - `cypress run` is expected to be slower than the `Run All Specs` button in `cypress open.

### Explanation of why it is slower (this is expected behavior)

`cypress run` relaunches the browser in between each spec file while 'Run All Tests' button does not. There is an issue to address this discrepancy here: https://github.com/cypress-io/cypress/issues/1586 This would account for the difference in running time. 

If this is the case, then we will close this issue and suggest you add your thoughts and 👍 	to this issue: https://github.com/cypress-io/cypress/issues/2951

**Closed by jennifer-shehane** 2019-07-23 13:01 UTC
Labels: stage: needs investigating, type: performance 🏃‍♀️

**Comment by tomitrescak** [comment] 2020-06-03 11:09
Is it possible to NOT open the browser on each spec file via some flag ?

**Comment by jennifer-shehane** [comment] 2020-06-04 09:52
@tomitrescak No there isn't a flag. The browser relaunches in between each spec file so there is not any discrepancy between how runs run when parallelizaed (which would have each specfile in isolation completely) versus not.
