### ISSUE TITLE
CypressError: Timed out retrying

### ISSUE THREAD

**Issue by Kevdog777** [cypress-io/cypress#5069] opened 2019-08-30 15:15 UTC
### Current behavior:

I am getting the above error in my code, visiting a webpage and checking it contains the correct URL.

This logic works on other links within the webpage.

```javascript
describe('Sectors Tab', function () {
    it('finds Software Development', function () {
        cy.visit('http://www.afd.co.uk/')
        cy.contains('Sectors')
            .click({force: true})
        cy.contains('Software Development')
            .click({force: true})
        cy.url()
            .should('include', '/sectors/software-development/')
    })
```

### Desired behavior:

It should return a valid response back saying it has passed the test. 

Just like it has done for my other tests:

```javascript
    it('finds Banking and Finance', function () {
        cy.visit('http://www.afd.co.uk/')
        cy.contains('Sectors')
            .click({force: true})
        cy.contains('Banking and Finance')
            .click({force: true})
        cy.url()
            .should('include', '/sectors/banks-and-finance/')
    })
```

#### Image for Above Tests

![image](https://user-images.githubusercontent.com/38526279/64031796-0e9d1880-cb41-11e9-9e2d-ce01582768d5.png)

### Steps to reproduce: (app code and test code)

See above for information about test code.

### Versions

Chrome: `76`  
Cypress: `3.4.1`

**Comment by jennifer-shehane** [comment] 2019-08-30 19:41
As the error shows, the url does not contain the `/sectors/banks-and-finance/` portion. 

You can see in the passing test that the page navigated to the `/sectors/banks-and-finance/` url with the `(NEW URL)` being logged - in the failing test case this is not logged - the URL is never changing.

Cypress is displaying the correct error in this case. Why is your website not navigating? Is it not navigating because of a bug in Cypress? I would have no idea of knowing without a fully reproducible example to run.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-08-30 19:41 UTC

**Comment by Kevdog777** [comment] 2019-09-05 09:53
> As the error shows, the url does not contain the `/sectors/banks-and-finance/` portion.

It isn't supposed to contain the `/sectors/banks-and-finance/` URL, as it is a different link. 

The issue I have is that the `/sectors/software-development/` is not working:

```javascript
describe('Sectors Tab', function () {
    it('finds Software Development', function () {
        cy.visit('http://www.afd.co.uk/')
        cy.contains('Sectors')
            .click({force: true})
        cy.contains('Software Development')
            .click({force: true})
        cy.url()
            .should('include', '/sectors/software-development/')
    })
```

I, then, gave an example of a working test that goes to the correct page.

I am sorry I can't give an example as this is a working and easy accessible webpage.

#### This is a step down approach to what I am trying to achieve:
1. Go to: http://www.afd.co.uk
2. Click on Sectors tab
3. Click on Software Development
4. Does the URL (in address bar) match the expected result (http://www.afd.co.uk/sectors/software-development/)?

**Comment by jennifer-shehane** [comment] 2019-09-05 20:27
After running this, when I click on the `.CLICK` command from the Command Log, theelement that was clicked is logged into the Developer Tools console. 

It is printing this element:

```html
<li class="inactive-menu-item horizontal-megamenu-item-parent" style="border-bottom:1px solid #BDBDBD" id="menu-item-sdk" data-toggle="sdk">
  Software Development Kits
  <ul class="menu-level-3">...</ul>
</li>
```

Is this the exact element you wanted to click on? This element is listening and should change the url?

**Comment by Kevdog777** [comment] 2019-09-06 08:40
Thanks @jennifer-shehane, I have asked the developer of the website to help out, as it could be that when you click on the `SECTORS` tab, then `Software Development` is already selected, that it could be selecting the text and not the link?
