### ISSUE TITLE
cy.type on input[type=number] setSelectionRange error is thrown

### ISSUE THREAD

**Issue by tbigueres** [cypress-io/cypress#4488] opened 2019-06-18 08:07 UTC
### Current behavior:

I try to type a number in an input which has the type "number" but I get the following error : 
![image](https://user-images.githubusercontent.com/2139076/59663058-800a3380-91ae-11e9-9485-16180b72885e.png)

### Desired behavior:
When doing : 

   ` cy.get("input[type=number]#meta-edit-contract-select-signature-page").type("2");`

I would expect the input to fill with the number 2
### Steps to reproduce: (app code and test code)

https://github.com/tbigueres/cypress-test-tiny
Branch master : 
npm install 
npm run cypress:open
launch specs.js

### Versions
Cypress 3.3.1
Chromium 57

**Comment by tbigueres** [comment] 2019-06-18 08:21
I've just updated chromium ! it works now. 
Thanks

**Comment by jennifer-shehane** [comment] 2019-06-18 08:40
Yah, we shouldn't be calling setSelectionRange on an input of type number, so I'm not sure where this would be happening. @Bkucera

**Comment by Bkucera** [comment] 2019-06-18 12:45
I'm not sure either, since I couldn't reproduce on electron or any recent version of electron I'm closing this

**Closed by Bkucera** 2019-06-18 12:45 UTC
