### ISSUE TITLE
Unable to read/access the inputbox within iframe in Cypress

### ISSUE THREAD

**Issue by pmrajput** [cypress-io/cypress#15428] opened 2021-03-11 10:55 UTC
Hi I am new to Cypress and facing issue to read/access the inputbox within iframe, as script encounter with "Timed out retrying after 4000ms: cy.its() errored because the property: contentDocument returned a null value." 
Please see the attached screenshot for error, Object structure and Code.
![Error](https://user-images.githubusercontent.com/8936556/110776596-40d71c80-8286-11eb-9740-eb69106f5b3f.jpg)
![iframe](https://user-images.githubusercontent.com/8936556/110776652-53e9ec80-8286-11eb-90f2-12904acd965f.jpg)
![Code](https://user-images.githubusercontent.com/8936556/110776678-59473700-8286-11eb-864f-14b1eeff0290.jpg)

**Comment by jennifer-shehane** [comment] 2021-03-16 19:28
Is this in Firefox? Because this isn't accessible in Firefox for some reason. https://github.com/cypress-io/cypress/issues/14853

In the end, this will fall under iframe support. Duplicate of https://github.com/cypress-io/cypress/issues/136

**Closed by jennifer-shehane** 2021-03-16 19:28 UTC
