### ISSUE TITLE
Got error when I use 'cypress run --record -- xxxx'

### ISSUE THREAD

**Issue by fdiori** [cypress-io/cypress#6062] opened 2019-12-30 07:13 UTC
### Current behavior:

```
cypress run --record --key dec7b846-7baf-4d93-85d7-96caee6d7667
ENOTDIR: not a directory, stat 
'/Users/xingyang.han/Desktop/Item/myc/node_modules/cypress/bin/cypress/plugins/index.js'
Error: ENOTDIR: not a directory, stat '/Users/xingyang.han/Desktop/Item/myc/node_modules/cypress/bin/cypress/plugins/index.js'
```

**Comment by jennifer-shehane** [comment] 2019-12-30 07:59
@fdiori You should not share your record key in a public place. There are reasons why this key should be kept secret as explained here: https://on.cypress.io/projects#Record-key

**We strongly advise that you regenerate a new key since you have exposed your private record key.** Instructions here: https://on.cypress.io/projects#Create-new-record-key


Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example, especially the `cypress/plugins/index.js` file contents since this is where the error is throwing, and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-12-30 07:59 UTC

**Comment by fdiori** [comment] 2019-12-30 09:43
thanks, that key is just for testing the running. nothing in it. 

whatever, I have resolved the issue.
