### ISSUE TITLE
when we close and open the cypress its throwing pluging file error

### ISSUE THREAD

**Issue by akshayqa11** [cypress-io/cypress#20907] opened 2022-04-05 05:04 UTC
### Current behavior

I have received this error many times so i have created multiple project but at the first time its working fine but when we close and reopen the project i got below error but i haven't change anything 

**Message:** Your `pluginsFile` is invalid: `C:\Akshay\AWSSales\SalesDemo\cypress\plugins\index.js`

It threw an error when required, check the stack trace below:

**Details:** Error: Cannot find module './_empty.js'
Require stack:
- C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\lib\builtins.js
- C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\index.js
- C:\Akshay\AWSSales\SalesDemo\node_modules\@cypress\browserify-preprocessor\index.js
- C:\Akshay\AWSSales\SalesDemo\node_modules\cypress-cucumber-preprocessor\lib\index.js
- C:\Akshay\AWSSales\SalesDemo\cypress\plugins\index.js
- C:\Users\Akshay Patil\AppData\Local\Cypress\Cache\9.5.3\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js
- C:\Users\Akshay Patil\AppData\Local\Cypress\Cache\9.5.3\Cypress\resources\app\packages\server\lib\plugins\child\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\lib\builtins.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\@cypress\browserify-preprocessor\index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)

**Stack trace:**
```
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\lib\builtins.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\@cypress\browserify-preprocessor\index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

### Test code to reproduce

**Message:** Your `pluginsFile` is invalid: `C:\Akshay\AWSSales\SalesDemo\cypress\plugins\index.js`

It threw an error when required, check the stack trace below:

**Details:** Error: Cannot find module './_empty.js'
Require stack:
- C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\lib\builtins.js
- C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\index.js
- C:\Akshay\AWSSales\SalesDemo\node_modules\@cypress\browserify-preprocessor\index.js
- C:\Akshay\AWSSales\SalesDemo\node_modules\cypress-cucumber-preprocessor\lib\index.js
- C:\Akshay\AWSSales\SalesDemo\cypress\plugins\index.js
- C:\Users\Akshay Patil\AppData\Local\Cypress\Cache\9.5.3\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js
- C:\Users\Akshay Patil\AppData\Local\Cypress\Cache\9.5.3\Cypress\resources\app\packages\server\lib\plugins\child\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\lib\builtins.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\@cypress\browserify-preprocessor\index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)

**Stack trace:**
```
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\lib\builtins.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\browserify\index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Akshay\AWSSales\SalesDemo\node_modules\@cypress\browserify-preprocessor\index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

### Cypress Version

9.5.3

**Comment by davidmunechika** [comment] 2022-04-05 14:29
Is there any way you could provide a demo repo that we can use to reproduce this issue?

**Comment by akshayqa11** [comment] 2022-04-05 16:44
Actually this issue not coming from repo when i unistall the node_module and install it again then issue gets resolved and i dont why node_module not getting stored in the system

**Comment by jennifer-shehane** [comment] 2022-04-11 18:56
@akshayqa11 Is this issue resolved?

**Comment by akshayqa11** [comment] 2022-04-12 03:06
Yes Jennifer issue is resolved now  actually lqqw is getting added to the some file deu to this issue is coming 

Thanks for help

**Comment by davidmunechika** [comment] 2022-04-12 03:07
Thanks for the response! I will be closing this issue since it has been resolved.

**Closed by davidmunechika** 2022-04-12 03:07 UTC
Labels: stage: awaiting response, topic: plugins ⚙️, unification

**Comment by akshayqa11** [comment] 2022-04-12 06:20
Yes you can close this ticket
