### ISSUE TITLE
window.open causes ERR_FAILED (-2) loading 'url' on electron headless >=10.8.0

### ISSUE THREAD

**Issue by aaron-qa** [cypress-io/cypress#24354] opened 2022-10-22 20:03 UTC
### Current behavior

Updating Cypress from 10.6.0  to 10.10.0 caused some tests to fail which visit a page that executes window.open().

```
ERR_FAILED (-2) loading 'https://cypress.io/'
Error: ERR_FAILED (-2) loading 'https://cypress.io/'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)
```

The page being tested gets a file URL and runs **window.open(url, '_blank');**. The URL is a file location. Cypress does not test the new window but does check for a successes message shown on the page being tested.

This issue does not happen on Cypress interactive mode (so only seen on headless).

I spotted this issue happens on Cypress version 10.8.0 and later. So I will try sticking to 10.7.0 for now.

### Desired behavior

Before I saw a window open and the test passing okay.

### Test code to reproduce

https://github.com/aaron-qa/cy-error-repoduce

### Cypress Version

>= 10.8.0

### Node version

v14.12.0

### Operating System

macOS 12.6

### Debug Logs

```shell
cypress:server:server-base Got CONNECT request from private-company-url.com:443 +21ms
  cypress:https-proxy Writing browserSocket connection headers { url: 'private-company-url.com:443', headLength: 0, headers: { host: 'private-company-url.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Mprivate-companytosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/10.10.0 Chrome/0.0.0.0 Electron/21.0.0 Safari/537.36' } } +20ms
  cypress:https-proxy Got first head bytes { url: 'private-company-url.com:443', head: '\x16\x03\x01\x025\x01\x00\x021\x03\x03�C};\x07x\x174\x7F1;\x06T>��0l��\x07��^��.A�_\x10\x13 �P�\x17w�̖��;n\x11��\x052�`�:' } +0ms
  cypress:https-proxy Making intercepted connection to 52999 +0ms
  cypress:network:connect successfully connected { opts: { port: 52999, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +21ms
  cypress:https-proxy received upstreamSocket callback for request { port: 52999, hostname: 'localhost', err: undefined } +1ms
  cypress:server:util:socket_allowed allowing socket { localPort: 53176 } +21ms
  cypress:server:request received status code & headers on request { requestId: 'request69', statusCode: 200, headers: { 'content-type': 'application/octet-stream' } } +170ms
  cypress:server:request successful response received { requestId: 'request69' } +0ms
  cypress:net-stubbing:server:intercept-response InterceptResponse { req: { url: '/private-path-url' }, request: undefined } +171ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'private-company', tld: 'com' } +25ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://private-company-url.com', strategy: 'http', fileServer: null, domainName: 'private-company.com', props: { port: '443', protocol: 'https:', domain: 'private-company', tld: 'com' } } for: https://private-company-url.com +25ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'file.csvdownloadstorage-url', domain: 'windows', tld: 'net' } +0ms
  cypress:server:remote-states getting primary remote state: { auth: null, origin: 'https://private-company-url.com', strategy: 'http', fileServer: null, domainName: 'private-company.com', props: { port: '443', protocol: 'https:', domain: 'private-company', tld: 'com' } } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'file.csvdownloadstorage-url', domain: 'windows', tld: 'net' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'private-company', tld: 'com' } +0ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://private-company-url.com', strategy: 'http', fileServer: null, domainName: 'private-company.com', props: { port: '443', protocol: 'https:', domain: 'private-company', tld: 'com' } } for: https://private-company-url.com +0ms
ERR_FAILED (-2) loading 'https://file.csvdownloadstorage-url.windows.net/private-path-url'
Error: ERR_FAILED (-2) loading 'https://file.csvdownloadstorage-url.windows.net/private-path-url'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)

  cypress:server:lib:util:suppress_warnings suppressed emitWarning from node: { process: process { version: 'v16.16.0', versions: { node: '16.16.0', v8: '10.6.194.11-electron.0', uv: '1.43.0', zlib: '1.2.12.1-motley', brotli: '1.0.9', ares: '1.18.1', modules: '109', nghttp2: '1.47.0', napi: '8', llhttp: '6.0.7', openssl: '1.1.1', cldr: '41.0', icu: '71.1', tz: '2022b', unicode: '14.0', electron: '21.0.0', chrome: '0.0.0.0' }, arch: 'arm64', platform: 
  
  cypress:server:cloud:api request to url: POST https://api.cypress.io/exceptions with params: {"body":{"err":{"name":"Error","message":"ERR_FAILED (-2) loading 'https:<stripped-path>file.csv'","stack":"Error: ERR_FAILED (-2) loading 'https:<stripped-path>file.csv'\n    at rejectAndCleanup (node:electron<stripped-path>browser_init:165:7500)\n    at EventEmitter.stopLoadingListener (node:electron<stripped-path>browser_init:165:7875)\n    at EventEmitter.emit (node:events:527:28)\n    at EventEmitter.emit (node:domain:475:12)\n"},"version":"10.10.0","osName":"darwin","osVersion":"21.6.0","osCpus":[{"model":"Apple M1 Pro","speed":24,"times":{"user":8209140,"nice":0,"sys":6629150,"idle":29642410,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":8225240,"nice":0,"sys":6279880,"idle":29974400,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":4674160,"nice":0,"sys":1792690,"idle":38012670,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":2770100,"nice":0,"sys":1028430,"idle":40680990,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":1685850,"nice":0,"sys":575830,"idle":42217840,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":1502460,"nice":0,"sys":398420,"idle":42578640,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":776110,"nice":0,"sys":223420,"idle":43479990,"irq":0}},{"model":"Apple M1 Pro","speed":24,"times":{"user":490030,"nice":0,"sys":144520,"idle":43844980,"irq":0}}],"osMemory":{"free":102891520,"total":17179869184}},"headers":{"x-os-name":"darwin","x-cypress-version":"10.10.0"}} and token: undefined +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/exceptions' } +44ms
  cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 } +26ms
  cypress:server:browsers:electron closed event fired +29ms
  cypress:server:windows error removing all extensions { err: TypeError: Object has been destroyed at Object.removeAllExtensions (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/windows.js:39:26) at BrowserWindow.<anonymous> (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:423:21)     at Object.onceWrapper (node:events:642:26)     at BrowserWindow.emit (node:events:539:35)     at BrowserWindow.emit (node:domain:475:12) at /Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/unhandled_exceptions.js:17:21 at tryCatcher (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at _drainQueueStep (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (/Users/private-user/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)     at processImmediate (node:internal/timers:466:21) , extensions: undefined } +0ms
  cypress:server:preprocessor removeFile /Users/private-user/dev/private-company-terminal.aaron.williams/cypress/e2e/data-user/explorer/analysis-report.cy.ts +17s
  cypress:server:preprocessor base emitter plugin close event +0ms
  cypress:server:preprocessor base emitter native close event +0ms
  cypress:server:preprocessor base emitter native close event +0ms
  cypress:server:browsers browsers.kill called with no active instance +17s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 192, proxyRequestsReceived: 66, immediatelyMatchedRequests: 60, unmatchedRequests: 0, unmatchedPreRequests: 121 } +0ms
  cypress:server:browsers:electron debugger detached due to { reason: 'target closed' } +6ms
  cypress:server:browsers:electron debugger detached due to { reason: 'target closed' } +1ms
  cypress:network:connect got addresses { hostname: 'api.cypress.io', port: 443, addresses: [ { address: '0.0.11.239', family: 4 }, { address: '0.0.25.250', family: 4 }, { address: '0.0.10.239', family: 4 }, { address: '0:0:10::6816:aef', family: 6 }, { address: '0:0:10::6816:bef', family: 6 }, { address: '0:4700:10::ac43:19fa', family: 6 } ] } +10ms
  cypress:webpack close /Users/private-user/dev/private-company-terminal.aaron.williams/cypress/e2e/data-user/explorer/report.cy.ts +14s
  cypress:webpack remove temp directory: /var/folders/df/06phgvfs0_ddp2n/T/cypress/webpack-preprocessor/def06d9c1330c +1ms
  cypress:server:socket-base socket-disconnecting transport error +55ms
  cypress:server:socket-base socket-disconnect transport error +0ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 53015 } +41ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 53027 } +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +20s
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +0ms
```

**Comment by aaron-qa** [comment] 2022-10-27 21:29
@mschile sorry the reproduce code was private. It's public now if it helps... https://github.com/aaron-qa/cy-error-repoduce

**Comment by mschile** [comment] 2022-10-27 22:50
@aaron-qa, thanks for the reproduction! I was also able to reproduce the issue and traced it down to being caused by this commit https://github.com/cypress-io/cypress/commit/bcd7548d74fdb5dab4790f10f158bb4f3e9387bc. 

The test did run successfully in other browsers (I tried chrome and edge) if that's an option for you.

I'm going to route your issue onto the appropriate team.

**Comment by flotwig** [comment] 2023-02-27 16:06
This is seemingly a duplicate of #18547, closing. Please follow that issue for updates.

**Closed as completed by flotwig** 2023-02-27 16:06 UTC
Labels: type: bug
