### ISSUE TITLE
How to stop page load issue during script run

### ISSUE THREAD

**Issue by Pradip6622** [cypress-io/cypress#25479] opened 2023-01-17 10:00 UTC
### Current behavior

Due to the page reloading during the script run, unable to see the thank you page. Because of that not successfully complete my script and it is happening fail. Please provide a proper solution to that so I can resolve my problem. I have seen many solutions for that problem but none of them works for me. **Its the Default Magento eCommerce website** 

![image](https://user-images.githubusercontent.com/100840712/212864702-9a4d1674-e69b-4ef5-a4ec-af1bea7bb915.png)
![image](https://user-images.githubusercontent.com/100840712/212864987-ff62f70b-e0f1-4029-b60f-dc1930e47c99.png)

### Desired behavior

I want to see the thank you page with the order number. 
![image](https://user-images.githubusercontent.com/100840712/212866110-23d0dcdf-15e2-44e8-b9cc-5bdc236074d8.png)

### Test code to reproduce
```js
it('can find and order in the customer order history after having placed an order', () => {
        cy.visit(product.simpleProductUrl)
        cy.wait(15000)
        cy.get(selectors.addToCartButton).click({force:true})
        cy.wait(3000)
        Account.login(account.customer.customer.email, account.customer.password)
        cy.visit(checkout.checkoutUrl)
        cy.wait(25000)
        cy.get(selectors.addressSelected).should('exist')
       // cy.get("input[value='freeshipping_freeshipping']").click()
          cy.get("input[value='flatrate_flatrate']").click()
        cy.get(selectors.checkoutBtn).click()
        cy.wait(4000)
        cy.get(selectors.moneyOrderPaymentMethodSelector).check({force: true})
        cy.get(selectors.moneyOrderPaymentMethodSelector).should('be.checked')
        cy.wait(7000)
        //cy.contains('Place Order').should('be.visible').click({force: true})
        //cy.get("button.action.primary.checkout").should('be.visible').click({force: true})
        cy.get('._active > .payment-method-content > .actions-toolbar > div.primary > .action > span').click()
        
        cy.get(selectors.orderConfirmationOrderNumber).then(($orderNr) => {
            const orderNr = $orderNr[0].innerText.trim()
            cy.log(orderNr)
            cy.visit(checkout.orderHistoryUrl)
            cy.wait(3000)
            cy.get(selectors.orderHistoryOrderNumber).then(($orderHistoryOrderNr) => {
                const orderNrHistory = $orderHistoryOrderNr[0].innerText.trim()
                cy.log(orderNrHistory)
                expect(orderNr).to.be.equal(orderNrHistory)
            })
        })
    })
})
```

### Cypress Version

12.3.0

### Node version

16.14.2

### Operating System

Windows 10 Home 21H2 ( 64bit)

**Comment by ZachJW34** [comment] 2023-01-19 16:16
Can you try stubbing the request that is causing the page to reload?

There isn't enough information here for me to reproduce this problem, and the issue seems to be due to the site under test rather than an issue with Cypress. A code snippet is helpful, but the provided code references values that I do not have access to. If you're able, please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by ZachJW34** [comment] 2023-01-27 18:13
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering following the links suggested.

**Closed as completed by ZachJW34** 2023-01-27 18:13 UTC
