### ISSUE TITLE
Add Support For IFrames To cy.clock()

### ISSUE THREAD

**Issue by lots0logs** [cypress-io/cypress#6454] opened 2020-02-13 23:18 UTC
### Current behavior:

`cy.clock()` doesn't support iframes even though the underlying library seems to support it:

>To hijack timers in another context pass it to the install method.
>```
>var FakeTimers = require("@sinonjs/fake-timers");
>var context = {
>    setTimeout: setTimeout // By default context.setTimeout uses the global setTimeout
>}
>var clock = FakeTimers.install({target: context});
>
>context.setTimeout(fn, 15); // Schedules with clock.setTimeout
>
>clock.uninstall();
> // context.setTimeout is restored to the original implementation
>```

### Desired behavior:

Support passing iframe context to `cy.clock()`
 
### Test code to reproduce

N/A

### Versions

4.0.1

**Comment by jennifer-shehane** [comment] 2020-02-14 08:57
Cypress does not offer full iframe support. 

Duplicate of #136 

Please comment in that issue about what you want supported with `cy.clock()` in iframes.

**Closed by jennifer-shehane** 2020-02-14 08:57 UTC

**Comment by lots0logs** [comment] 2020-02-14 17:57
@jennifer-shehane A catch all issue where no one is likely to even notice my request? :disappointed:  How many users have to express the need for proper iframe support before it will be a priority? I'm genuinely curious.

**Comment by jennifer-shehane** [comment] 2020-02-26 10:37
We prioritize issues we work on based on a variety of factors - including the number of users requesting/helped by a feature. While it is still on our Roadmap, other features are a higher priority today as a result of this assessment. Sorry for the delay.
