### ISSUE TITLE
Email type input default behavior removing whitespace?

### ISSUE THREAD

**Issue by puyanwei** [cypress-io/cypress#6988] opened 2020-04-11 10:37 UTC
### Current behaviour:

I've noticed if you type in an input field with the type email all whitespace will be removed automatically by Cypress.
```js
cy.get("#exampleInputEmail1")
  .type("one two three");
```

![image](https://user-images.githubusercontent.com/14803518/79041505-57917100-7be8-11ea-9444-f0c09cde2612.png)

### Desired behavior:

Allow text inputs on email fields to include whitespace because it should imitate what a user is doing

### Test code to reproduce

https://github.com/puyanwei/cypress-test-tiny

### Versions
Cypress 6.13.7
Chrome 80
Mac OS Catalina 10.15.4

**Comment by jennifer-shehane** [comment] 2020-04-13 05:34
Duplicate of #1327

**Closed by jennifer-shehane** 2020-04-13 05:34 UTC
