### ISSUE TITLE
cy.intercept example for stubbing fetch for the same url?

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#15237] opened 2021-02-26 03:07 UTC
I have a list of items on the screen, for some reason after user performed some action it called the same url. I'm doing this, it is able to stubbed for the first time

```cy.intercept('graphql/items', {fixture: items.json});```

then I did

```cy.intercept('graphql/items', {fixture: anoterItems.json});```

it doesn't stub the 'later' fetch.

**Comment by jennifer-shehane** [comment] 2021-02-26 14:52
Duplicate of https://github.com/cypress-io/cypress/issues/9302

**Closed by jennifer-shehane** 2021-02-26 14:52 UTC
