### ISSUE TITLE
cy.go('back') crashes when redirect is present

### ISSUE THREAD

**Issue by aamorozov** [cypress-io/cypress#8082] opened 2020-07-23 21:46 UTC
The issue occurs with both `cy.go('back')` and `cy.go(-1)`

### Current behavior:

`cy.go('back')` causes a crash

### Desired behavior:

`cy.go('back')` navigates back and follows redirect as stated in the documentation

### Test code to reproduce

```js
cy.visit('/page')
cy.get('submit button to go to next page').click()
// global state is updated and `/page` path is supposed to redirect to `/page/user`
cy.go('back') || cy.go(-1)
```

The Cypress debugger window is closed, another empty window opens and stays open without any errors(note the screenshot below).

### Versions

MacOS, Docker(debian). Cypress 4.9.0

### Screenshot for reference
<img width="1792" alt="Screen Shot 2020-07-23 at 2 47 18 PM" src="https://user-images.githubusercontent.com/10227658/88341999-7200dd80-ccf3-11ea-979b-7747be40e71b.png">

**Comment by jennifer-shehane** [comment] 2020-07-24 11:19
The reproduction of this code is dependent on the logic of the application under test - as this can't normally be reproduced with every use of `cy.go('back')`. Working example below.

```js
it('visit example', () => {
  cy.visit('https://example.cypress.io')
  cy.get('.home-list').contains('Querying').click()
  cy.go('back')
})
```

Can you provide a fully reproducible example, including a url to visit or an index.html that reproduces the issue. We'll have to close otherwise as we have no way forward in investigating. Thanks!

**Comment by aamorozov** [comment] 2020-07-27 18:49
@jennifer-shehane Thank you, I'll put together a repo to reproduce later today

**Comment by jennifer-shehane** [comment] 2021-02-22 14:27
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-22 14:27 UTC
Labels: stage: needs information
