### ISSUE TITLE
Cypress 10.0.3 does not find tests when passing specPattern to --config.

### ISSUE THREAD

**Issue by mschaefer-gresham** [cypress-io/cypress#22261] opened 2022-06-11 07:11 UTC
### Current behavior

When running tests without a --config option, Cypress picks up all the tests correctly based on the specPattern in my config file:

```
export default defineConfig({
    video: false,
    reporter: 'junit',
    reporterOptions: {
        mochaFile: 'results/unit/junit-[hash].xml',
    },
    component: {
        setupNodeEvents(on, config) {},
        viewportHeight: 700,
        viewportWidth: 1400,
        specPattern: 'src/**/*.cy.{ts,tsx}',
        devServer: {
            framework: 'react',
            bundler: 'webpack',
            webpackConfig,
        },
    },
});
```

```
    Cypress:        10.0.3                                                                         │
  │ Browser:        Chrome 102 (headless)                                                          │
  │ Node Version:   v16.3.0 (/Users/matthew/.nvm/versions/node/v16.3.0/bin/node)                   │
  │ Specs:          21 found (App.cy.tsx, Breadcrumbs.cy.tsx, BreadcrumbsTreeNodeActions.cy.tsx, P │
  │                 aneSelector.cy.tsx, SmartSearchExtraIntoTabCounts.cy.tsx, SmartSearchGridCanSe │
  │                 lectMultipleRows.cy.tsx, SmartSearchGridExtraInfoTabData.cy.tsx, SmartSearchGr │
  │                 idExtraIntoActiveTab.cy...)                                                    │
  │ Searched:       src/**/*.cy.{ts,tsx}
```

But if I pass the same pattern to --config, it says it can't find the tests. 

```
cypress run --component --browser chrome --config 'specPattern=src/**/*.cy.{ts,tsx}'
```

Even though it was expanded correctly:

```
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /Users/matthew/workspace/electra-web/electracontrolapp/app/src/**/*.cy.{ts,tsx}
```

### Desired behavior

Using --config specPattern='my spec pattern' should find the tests.

### Test code to reproduce

Run component tests based on a specPattern in your cypress config file. Then run using --config and specify the same specPattern. It should claim not to find any tests.

cypress run --component --browser chrome --config 'specPattern=src/**/*.cy.{ts,tsx}'

### Cypress Version

10.0.3

**Comment by lmiller1990** [comment] 2022-06-13 01:46
Hey, thanks for the excellent bug report. I use `--config` all the time as `--config video=false,retries=0`, and it works fine, so I'd have expected this to work fine, too.

The way I normally specify specs in run mode is `--spec`. Here's a command I run all the time:

```
yarn cypress:run:e2e --spec "cypress/e2e/**/*.cy.ts" --browser chrome --headed --config retries=0,video=false
```

For now, I'd recommend using `--spec` for your `specPattern` related needs. In the meantime, we should fine out why `--config specPattern=...` is not respected, though.

**Comment by mschaefer-gresham** [comment] 2022-06-13 07:22
Thank you. --spec is working fine.

**Comment by awaigand** [comment] 2022-06-14 15:04
Just a heads up, we had this
```
  return Object.assign({}, config, {
    fixturesFolder: "tests/integration/fixtures",
    specPattern: "tests/integration/specs/**/*.cy.{js,jsx,ts,tsx}",
    screenshotsFolder: "tests/integration/screenshots",
    videosFolder: "tests/integration/videos",
    supportFile: "tests/integration/support/index.js",
  });
```

in our plugins/index.js. The `specPattern` used to be `integrationFolder`.

The specPattern there now takes precedence over `--config specPattern`, which didn't use to be the case I believe with integrationFolder and `--config testFiles` respectively. That's why our old approach broke. Maybe that's part of the issue?

**Comment by marktnoonan** [comment] 2022-06-15 23:05
@lmiller1990 now that you've investigated with @rachelruderman for https://github.com/cypress-io/cypress/issues/22245, do you think is this is the same underlying issue, regarding the precedence of config loading?

**Comment by lmiller1990** [comment] 2022-06-16 00:43
We didn't look into #22245, we were doing another one (migration issue,#22065). I'm not sure if related, but they do seem similar - it seems like you might be onto something.

**Comment by marktnoonan** [comment] 2022-06-21 15:27
I've flagged this as a dupe of a https://github.com/cypress-io/cypress/issues/22245, we will retest this as part of that ticket and confirm.

**Closed by marktnoonan** 2022-06-21 15:27 UTC
Labels: stage: investigating, existing workaround, v10.0.0 :bug:
