### ISSUE TITLE
Error : certificate has expired

### ISSUE THREAD

**Issue by davpatrik** [cypress-io/cypress#29166] opened 2024-03-18 15:04 UTC
### Current behavior

When we try to download the **cypress.zip** during the build process from this link (https://download.cypress.io/desktop/1.4.2?platform=linux&arch=x64)
we have a **certificate has expired** error.

<img width="516" alt="image" src="https://github.com/cypress-io/cypress/assets/51869286/54a025d0-c423-43e1-b23a-a81690840e56">

<img width="702" alt="image" src="https://github.com/cypress-io/cypress/assets/51869286/c3d6e577-ad9f-4cd2-91c5-c661a114e013">

### Debug logs

```Text
10:02:00  #14 69.66 Installing Cypress (version: 1.4.2)
10:02:00  #14 69.66 
10:02:00  #14 69.66 [14:01:59]  Downloading Cypress     [started]
10:02:00  #14 69.66 [14:01:59]  Downloading Cypress     [failed]
10:02:00  #14 69.66 [14:01:59] → The Cypress App could not be downloaded.
10:02:00  #14 69.66 
10:02:00  #14 69.66 Please check network connectivity and try again:
10:02:00  #14 69.66 ----------
10:02:00  #14 69.66 
10:02:00  #14 69.66 URL: https://download.cypress.io/desktop/1.4.2?platform=linux&arch=x64
10:02:00  #14 69.66 Error: certificate has expired
10:02:00  #14 69.66 ----------
```

### Cypress Version

1.4.2

### Node version

v10.24.1

### Package Manager

npm

### Package Manager Version

6.14.18

### Operating system

other

### Operating System Version

Debian 8.6

**Comment by jennifer-shehane** [comment] 2024-03-18 15:59
@davpatrik Is there a reason you're downloading 1.4.2? This is an extremely old version. What happens when you download 13.7.0?

**Comment by davpatrik** [comment] 2024-03-18 17:58
Hello @jennifer-shehane 
It's because that's used into one of our legacy apps, which uses node v10.

**Comment by lyn5466** [comment] 2024-03-19 17:49
We see the same error for Cypress version 4.12.1

**Comment by jennifer-shehane** [comment] 2024-03-19 20:45
Going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/29110

**Closed as not planned by jennifer-shehane** 2024-03-19 20:45 UTC
Labels: type: duplicate

**Comment by MikeMcC399** [comment] 2024-03-21 07:30
@davpatrik / @lyn5466

There are issues with using older unsupported versions of Node.js to download legacy Cypress versions.

This issue has been logged with Node.js `v10.24.1`  and this version is no longer supported.

Node.js `10` entered end-of-life on Apr 30, 2021. The lowest supported version of Node.js is `18`. (See [Node.js release schedule](https://github.com/nodejs/release#release-schedule) and [Cypress system requirements](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs)).

- See also some discussions in https://github.com/cypress-io/cypress/issues/29110
