### ISSUE TITLE
Automatic reloading of tests does not work correctly when a change is made to the test code

### ISSUE THREAD

**Issue by alejo009** [cypress-io/cypress#28820] opened 2024-01-29 18:00 UTC
### Current behavior

When I make a change to my test files in vsCode, cypress gets stuck when trying to reload the tests to run them again, something happens intermittently

![image](https://github.com/cypress-io/cypress/assets/82913276/10b38e7b-59a2-49b4-823b-8b5db65b7477)

https://app.screencastify.com/v3/watch/wR8jZuwdHFyDT9p2Rxrm

### Desired behavior

Cypress should automatically reload the browser successfully and run the tests.

### Test code to reproduce

1-  create basic cypress project with the following test

describe('template spec', () => {
  it('this is failing', () => {
    cy.visit('http://example.cypress.io')
  })
})

2- change the test name or description

![image](https://github.com/cypress-io/cypress/assets/82913276/95cb453f-4628-45ad-9671-ac5ad48264ec)

### Cypress Version

13.6.3

### Node version

v20.11.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment] 2024-01-29 18:17
Duplicate of https://github.com/cypress-io/cypress/issues/28392 - we're working on a fix. 

In the meantime, follow these steps to enable our extension: https://github.com/cypress-io/cypress/issues/28392#issuecomment-1852735772

**Closed as not planned by jennifer-shehane** 2024-01-29 18:17 UTC
