### ISSUE TITLE
"Run all specs" should run filtered specs

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress#7125] opened 2020-04-23 18:16 UTC
### Current behavior:

In Cypress main window, there is an input field to filter the visible specs. Once only the specs I want are visible, I would like to be able to run them all. Nevertheless, the "Run all specs" button runs even the specs that don't match the filter. 

**Use case:** my test suite has 2 kinds of tests, UI and E2E tests. They are distinguished in their filenames with `_spec.ui.js` or `_spec.e2e.js` suffix. They need a different `baseUrl`, so, when Cypress main window is visible, I can either run the UI tests or the E2E tests, not both. I would like to be able to filter the UI tests (or the E2E tests) and to only run those.

### Desired behavior:

I would expect the button to only run the visible specs or to have a dedicated "Run visible tests" button.

**Comment by jennifer-shehane** [comment] 2020-04-28 08:51
Duplicate of #3607

**Closed by jennifer-shehane** 2020-04-28 08:51 UTC
