### ISSUE TITLE
Flaky test: GitDataSource gets correct status for files on linux

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#25824] opened 2023-02-15 16:24 UTC
### Link to Cypress Cloud or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/49602/workflows/2c9c7753-9b62-4fac-9a64-359a666f03b1/jobs/2060027

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/9e27540f0547163a8ec745da2d66ce455683187c/packages/data-context/test/unit/sources/GitDataSource.spec.ts#L49

### Analysis

This test has `retries(15)` and still fails. Looks like retries don't help, if it fails the first time it will fail every time after. The test tries to create a git repository and must be getting hung up as the test fails due to a promise never returning. Not sure how flaky it is for other platforms so could be a linux issue.

### Cypress Version

12.5.1

### Other

If this test is already covered by and End to End test, [maybe this one](https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/specs_list_no_git_repo.cy.ts), can we just delete (or rewrite) this test?

**Comment by lmiller1990** [comment] 2023-02-22 06:31
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25824?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by flotwig** [comment] 2023-02-22 15:03
This is a duplicate of #23317

**Comment by lmiller1990** [comment] 2023-02-23 02:18
Oops, closing.

We are picking this up @flotwig 

Death to the flake 🔥

**Closed as completed by lmiller1990** 2023-02-23 02:18 UTC
