### ISSUE TITLE
Browser: chrome was not found on your system or is not supported by Cypress

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#24430] opened 2022-10-28 02:17 UTC
### Current behavior

```
17:16:38  Can't run because you've entered an invalid browser name.
17:16:38  
17:16:38 
 Browser: chrome was not found on your system or is not supported by Cypress.
17:16:38  
17:16:38  Cypress supports the following browsers:
17:16:38   - electron
17:16:38   - chrome
17:16:38   - chromium
17:16:38   - chrome:canary
17:16:38   - edge
17:16:38   - firefox
17:16:38  
17:16:38  You can also use a custom browser: [https://on.cypress.io/customize-browsers](https://on.cypress.io/customize-browsers%1B[39m)
17:16:38  
17:16:38  Available browsers found on your system are:
17:16:38   - electron
17:17:17  Can't run because you've entered an invalid browser name.
```

### Desired behavior

Chrome is installed, so Cypress should find it.

### Test code to reproduce

I'm using the `cypress/base:16.17.0` Docker image, with Chrome 107 installed, and Cypress 10.11.0.

### Cypress Version

10.11.0

### Node version

16.17.0

### Operating System

Debian 11

**Comment by nagash77** [comment] 2022-10-28 13:14
@kaiyoma I'm sorry to hear you are having problems.  We have not received any other reports of this problem and I am unable to reproduce this issue myself given the information provided.  Can you provide more detailed steps to recreate the issue please?

I would also recommend questions relating to how to use Cypress be asked in our [Discord server](https://gitter.im/cypress-io/cypress).  This will most likely be the fastest route to an answer.

**Comment by kaiyoma** [comment] 2022-10-28 16:48
It's not reliably reproducible, but simply running Cypress with the above mentioned environment was enough to do it. I've seen this problem infrequently in our CI over the years, but I thought the new version of Cypress was supposed to fix this? After upgrading to 10.11.0, I ran into this almost immediately.

**Comment by nagash77** [comment] 2022-10-31 13:57
@kaiyoma Can you provide more context such as the commands you are using to run Cypress?  Can you include debug logs?  As  this bug currently stands there is not enough information for us to go off of to investigate your particular issue.

**Comment by kaiyoma** [comment] 2022-10-31 16:09
I'm running Cypress like this:

```
cypress run --browser chrome --headless --spec <test file>
```

I don't have debug logs, but if I see this happen again, I'll try to figure out how to get them.

**Comment by kaiyoma** [comment] 2022-11-02 19:33
Just ran into this again:

```
12:17:36  Can't run because you've entered an invalid browser name.
12:17:36  
12:17:36 
 Browser: chrome was not found on your system or is not supported by Cypress.
12:17:36  
12:17:36  Cypress supports the following browsers:
12:17:36   - electron
12:17:36   - chrome
12:17:36   - chromium
12:17:36   - chrome:canary
12:17:36   - edge
12:17:36   - firefox
12:17:36  
12:17:36  You can also use a custom browser: [https://on.cypress.io/customize-browsers](https://on.cypress.io/customize-browsers%1B[39m)
12:17:36  
12:17:36  Available browsers found on your system are:
12:17:36   - firefox
12:17:36   - electron
```

This is definitely still a problem. @nagash77 @amehta265 What kind of logs do you want me to try to get?

**Comment by kaiyoma** [comment] 2022-11-10 16:19
Just ran into a similar problem:

```
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in connectToNewSpec

 Error: Missing browserCriClient in connectToNewSpec
    at Object.connectToNewSpec (/home/jenkins/.cache/Cypress/10.11.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:451:19)
    at Object.connectToNewSpec (/home/jenkins/.cache/Cypress/10.11.0/Cypress/resources/app/packages/server/lib/browsers/index.js:96:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at OpenProject.relaunchBrowser (/home/jenkins/.cache/Cypress/10.11.0/Cypress/resources/app/packages/server/lib/open_project.js:150:24)
```

**Comment by marktnoonan** [comment] 2022-11-18 16:24
Hi @kaiyoma sorry for my slow reply here, the logs can be generated with `DEBUG=cypress:* cypress run`, more details are here: https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs

**Comment by marktnoonan** [comment] 2022-11-18 16:28
I notice that in the two error messages there are different browsers detected. In the issue description Cypress has only found Electron, and in [this comment](https://github.com/cypress-io/cypress/issues/24430#issuecomment-1301117511) Cypress has found both Electron and Firefox. 

Did anything change in the environment between these attempts? It's possible Cypress is inconsistently detecting the installed browsers in general, in this specific situation.

**Comment by kaiyoma** [comment] 2022-11-18 19:13
@marktnoonan Nope, nothing has changed. We're using the same Docker image all the time, which has Chrome and Firefox installed:

```
FROM cypress/base:16.17.0

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install tools and libraries necessary to install the browsers below
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    bzip2=1.0.8-4 \
    ca-certificates=20210119 \
    curl=7.74.0-1.3+deb11u2 \
    git=1:2.30.2-1 \
    gnupg=2.2.27-2+deb11u2 \
    libcurl4=7.74.0-1.3+deb11u2 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Chrome
ARG CHROME_VERSION=107.0.5304.68-1
RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update \
  && apt-get install -y --no-install-recommends google-chrome-stable=$CHROME_VERSION \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Firefox
ARG FIREFOX_VERSION=106.0.2
RUN curl -fsSL -o firefox.tar.bz2 https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2 \
  && echo "4867a211001cc289fbe8ee5eaa04f72691d9a61e44f7c5ddb339ba8a37501bac  firefox.tar.bz2" | sha256sum -c - \
  && tar -C /opt -xjf firefox.tar.bz2 \
  && rm firefox.tar.bz2 \
  && ln -fs /opt/firefox/firefox /usr/bin/firefox

# Upgrade npm
ARG NPM_VERSION=8.19.1
RUN npm install -g npm@$NPM_VERSION
```

**Comment by kaiyoma** [comment] 2022-11-21 16:54
@marktnoonan Do you know if these kinds of messages are related to this issue? We see these sometimes at the start of a test run (again, randomly and non-deterministically):

```
00:55:34  Still waiting to connect to Chrome, retrying in 1 second (attempt 18/62)
00:55:35  Still waiting to connect to Chrome, retrying in 1 second (attempt 19/62)
00:55:36  Still waiting to connect to Chrome, retrying in 1 second (attempt 20/62)
00:55:37  Still waiting to connect to Chrome, retrying in 1 second (attempt 21/62)
00:55:38  Still waiting to connect to Chrome, retrying in 1 second (attempt 22/62)
00:55:39  Still waiting to connect to Chrome, retrying in 1 second (attempt 23/62)
00:55:40  Still waiting to connect to Chrome, retrying in 1 second (attempt 24/62)
00:55:41  Still waiting to connect to Chrome, retrying in 1 second (attempt 25/62)
00:55:42  Still waiting to connect to Chrome, retrying in 1 second (attempt 26/62)
00:55:43  Still waiting to connect to Chrome, retrying in 1 second (attempt 27/62)
00:55:44  Still waiting to connect to Chrome, retrying in 1 second (attempt 28/62)
00:55:45  Still waiting to connect to Chrome, retrying in 1 second (attempt 29/62)
00:55:47  Still waiting to connect to Chrome, retrying in 1 second (attempt 30/62)
00:55:48  Still waiting to connect to Chrome, retrying in 1 second (attempt 31/62)
00:55:49  Still waiting to connect to Chrome, retrying in 1 second (attempt 32/62)
00:55:50  Still waiting to connect to Chrome, retrying in 1 second (attempt 33/62)
00:55:51  Still waiting to connect to Chrome, retrying in 1 second (attempt 34/62)
00:55:53  Still waiting to connect to Chrome, retrying in 1 second (attempt 35/62)
00:55:54  Still waiting to connect to Chrome, retrying in 1 second (attempt 36/62)
00:55:55  Still waiting to connect to Chrome, retrying in 1 second (attempt 37/62)
00:55:56  Still waiting to connect to Chrome, retrying in 1 second (attempt 38/62)
00:55:57  Still waiting to connect to Chrome, retrying in 1 second (attempt 39/62)
00:56:29  
00:56:29  Timed out waiting for the browser to connect. Retrying...
```

Our first test suite after these messages were printed had a bunch of failures today, and it seems too much of a coincidence.

**Comment by kaiyoma** [comment] 2022-11-21 23:33
@marktnoonan Is there some way to send all Cypress debug logs to a file instead of stdout? The amount of output is going to overwhelm our CI system and make the job logs unreadable.

**Comment by kaiyoma** [comment] 2022-11-22 00:21
Lol, never mind, I completely forgot that I went down this path two years ago (https://github.com/cypress-io/cypress/issues/7995). 🤣

**Comment by mike-plummer** [comment] 2022-12-14 18:52
Hi @kaiyoma, were you able to collect any debug logs we could look into? Or has this issue been resolved?

**Comment by kaiyoma** [comment] 2022-12-14 19:34
@mike-plummer I'm still waiting for this to happen again. We're collecting debug logs for all our CI jobs now, so as soon as this happens again, I'll have the logs.

**Comment by lmiller1990** [comment] 2022-12-29 00:18
We need more information to continue debugging. Happy to reopen if more information becomes available. In the meantime, I don't see any actionable work on our end, so I am going to close this.

**Comment by kaiyoma** [comment] 2023-01-25 02:02
@lmiller1990 @nagash77 @rockindahizzy This finally happened again for me and here are the debug logs from Cypress:
[cypress-debug-logs.txt](https://github.com/cypress-io/cypress/files/10495493/cypress-debug-logs.txt)

This ran on the same Docker image we use for all our e2e tests, so Chrome is absolutely installed.

**Comment by ZachJW34** [comment] 2023-01-30 17:21
I wasn't able to reproduce this with the included docker image using the latest `cypress/base` docker image and Chrome/Firefox versions. Have you tried updating to the latest Cypress + docker image?

The logs show strange browser detection results:

```
cypress:server:browsers:utils found browsers {
  browsers: [
    {
      name: 'chrome',
      family: 'chromium',
      channel: 'stable',
      displayName: 'Chrome',
      version: '107.0.5304.68',
      path: 'google-chrome', <--- Incorrect path
      minSupportedVersion: 64,
      majorVersion: '107'
    }, 
    {
      name: 'firefox',
      family: 'firefox',
      channel: 'stable',
      displayName: 'Firefox',
      version: '106.0.2',
      path: 'firefox', <--- Incorrect path
      minSupportedVersion: 86,
      majorVersion: '106'
    }
  ] 
}
```

I can't dig in any further since I can't reproduce this with my local docker setup. Can you also try using the `cypress/included` image and remove the manual browser installation from your docker file?

**Comment by ZachJW34** [comment] 2023-01-30 20:04
We also recently published the [cypress/factory](https://github.com/cypress-io/cypress-docker-images/tree/master/factory) image which can be used to create a custom docker image with specific browsers/node versions.

**Comment by kaiyoma** [comment] 2023-02-03 19:23
@ZachJW34 I tried using one of the `cypress/browsers` Docker images and Cypress no longer runs:

```
xvfb-run: error: xauth command not found
```

Question for you: do I still need to run Cypress through `xvfb-run` if I'm using this image?

**Comment by ZachJW34** [comment] 2023-02-03 19:30
@kaiyoma you should be able to invoke cypress normally via `npx cypress run` (given that you have already `npm i`) if you are using the `cypress/browsers` image.

**Comment by kaiyoma** [comment] 2023-02-04 00:16
Hmm, now I'm getting some kind of cache error:

```
12:27:04  The cypress npm package is installed, but the Cypress binary is missing.
12:27:04  
12:27:04  We expected the binary to be installed here: /root/.cache/Cypress/10.11.0/Cypress/Cypress
12:27:04  
12:27:04  Reasons it may be missing:
12:27:04  
12:27:04  - You're caching 'node_modules' but are not caching this path: /home/jenkins/.cache/Cypress
12:27:04  - You ran 'npm install' at an earlier build step but did not persist: /home/jenkins/.cache/Cypress
```

I'm not quite sure what this is referring to, because even after a fresh install of dependencies, the `.cache` directory doesn't exist:

```
14:08:56  + ls -lR .cache
14:08:56  ls: cannot access '.cache': No such file or directory
```

**Comment by marktnoonan** [comment] 2023-02-20 21:46
@kaiyoma hello again! I'm sorry this has been such a persistent issue. I'm curious if you tried using the [cypress/factory](https://github.com/cypress-io/cypress-docker-images/tree/master/factory) image @ZachJW34 suggested and experienced anything different.

Also, reading back, could you confirm if this is happening every time for you now or is an intermittent issue.

It does seem challenging to address in that we can't reproduce.

**Comment by kaiyoma** [comment] 2023-02-20 22:13
Oh cool! I'll have to give `cypress/factory` a try since `cypress/browsers` doesn't work for us.

**Comment by marktnoonan** [comment] 2023-02-27 15:03
@kaiyoma for now I'll close this as there has been 7 days of inactivity. If that image did not get you unblocked, please comment back here and we can reopen the issue.

**Closed as completed by marktnoonan** 2023-02-27 15:03 UTC

**Comment by Haargeeel** [comment] 2024-05-21 15:33
We came across the same issue. We are using `chromium` and `firefox` and it said that these are not installed, which they are.

We do the cypress tests via systemd and found a difference in the environment in the node process when we started cypress manually.

Via systemd we got:

```
DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/0/bus',
XDG_RUNTIME_DIR: '/run/user/0',
```

Instead of the `0` there should be the uid of our cypress user so we set the correct path in the systemd service file.

**Comment by Lovor01** [comment] 2024-06-18 09:40
A workaround for Chrome Developer version, which is not detected:
create a symlink to Chrome Application folder.
in %programfiles%\Google create Chrome folder besides Chrome Dev.
In powershell terminal, enter that folder and invoke (Replace C:\Program Files with your path):
`New-Item -ItemType SymbolicLink -Path .\Application -Target "C:\Program Files\Google\Chrome Dev\Application"`
