### ISSUE TITLE
Allow selective test to run

### ISSUE THREAD

**Issue by ronenmalka** [cypress-io/cypress#8564] opened 2020-09-13 07:35 UTC
### Desired behavior:

Allow selective test to run using checkboxes.

### Versions

Cypress:5.1.0

It will be very helpful to allow selecting specific tests to run (beside using the filter)

![image](https://user-images.githubusercontent.com/47978855/93012929-dbdb8c00-f5ac-11ea-93d4-442c854efc9b.png)

**Comment by Jacek-fstack** [comment] 2020-09-15 08:59
Just FYI: npx cypress open is supposed to be used only for development. If you want to actually run more than one spec, you should use npx cypress run, and there you can specify specs you want to run.

**Comment by ronenmalka** [comment] 2020-09-15 11:56
Thanks @Jacek-fstack , I'm aware that `npx cypress open` is only for development, but sometimes during development you fix code that impact some tests that you want to keep running while developing. It is not always possible to filter these tests, so it would be very useful to select theses tests and run.

**Comment by jennifer-shehane** [comment] 2020-10-15 02:26
Duplicate of https://github.com/cypress-io/cypress/issues/3607

**Closed by jennifer-shehane** 2020-10-15 02:26 UTC
Labels: topic: spec execution, type: feature
