### ISSUE TITLE
ServiceNow Application Login Page does not load with Cypress 4.11

### ISSUE THREAD

**Issue by TestLeafInc** [cypress-io/cypress#8133] opened 2020-07-30 20:01 UTC
### Current behavior:

The ServiceNow application does not load in Cypress  

### Desired behavior:

It should show Login Page

### Test code to reproduce

```js
///<reference types="cypress" />
describe('ServiceNow - Incidents', () => {
    beforeEach('Login to ServiceNow', () => {
        cy.visit('https://dev81677.service-now.com/',);
    })
    it('Create Incident', () => {

    })
    afterEach('Logout', () => {

    })
    Cypress.on('uncaught:exception', (err, runnable) => {
        debugger
        return false      
    })  
})
```

### Versions

4.11

**Comment by TestLeafInc** [comment] 2020-07-30 20:03
[
![Error](https://user-images.githubusercontent.com/10628620/88968926-b54be500-d2cd-11ea-828b-d6017547341b.PNG)
](url)

Snapshot of the missing login page. Here is the URL for testing: https://dev81677.service-now.com/

**Comment by jennifer-shehane** [comment] 2020-08-03 09:20
There's an error in the console showing when trying to load. 

>Refused to display 'https://developer.servicenow.com/app.do#!/instance?wu=true' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

<img width="1087" alt="Screen Shot 2020-08-03 at 3 48 21 PM" src="https://user-images.githubusercontent.com/1271364/89166961-ced87f80-d5a0-11ea-9afc-9fe1b6b167cd.png">

Duplicate of #3459 There is a potential workaround explained in this comment: https://github.com/cypress-io/cypress/issues/3459#issuecomment-649404233

**Closed by jennifer-shehane** 2020-08-03 09:20 UTC
