### ISSUE TITLE
Remove Nullable type from globals

### ISSUE THREAD

**Issue by dartess** [cypress-io/cypress#23333] opened 2022-08-14 16:37 UTC
### Current behavior

Cypress adds `Nullable` global type in https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/cli/types/cypress-type-helpers.d.ts .

### Desired behavior

Cypress does not add unexpected and unnecessary global types that are not clearly Cypress related.
If it is an internal type, please export and import it explicitly.

### Test code to reproduce

`type A = Nullable<string>`

### Cypress Version

10.4.0

### Node version

any

### Operating System

any

**Comment by nagash77** [comment] 2022-08-15 18:52
@dartess Can you please elaborate on why you think this is a problem?  Can you also provide a reproducible example where we can see the problem you are describing.

**Comment by dartess** [comment] 2022-08-16 18:45
Ok

1. Your type is called `Nullable`. It looks like this type works exactly the opposite of TypeScript's built-in `NonNullable` type. But it is not. `NonNullable` exclude `null` _and_ `undefined`, but your `Nullable` add only `null`. It's not obvious.

2. Cypress is not modular by design (like all other modern software) and I put up with it. But global variables and Cypress types are at least obviously related to it. Guessing from the code that the Nullable type is not a built-in type in the typescript, but a global type from Cypress, can be difficult. This is how you mislead users. They may start relying on undocumented global Cypress types without even knowing it.

3. By the way, where in the documentation does it say that Cypress will add such a global type to your code?

In general, there is no reason why Cypress should add such non-obvious global types to its users' code base. Moreover, Cypress itself uses this type literally in one place. And nothing prevents it from being imported and exported once.

**Comment by nagash77** [comment] 2022-08-18 18:33
@dartess after internal review, the team agrees with your perspective.  I will route it to the appropriate team, however due to current backlog lengths I would not expect a fix for this in the near future from our team.  I have marked it as a 'Good First Issue' to hopefully encourage community contributions to address this issue.  Thanks for your work in reporting it!

**Closed** 2022-08-24 16:15 UTC
Labels: type: bug, good first issue, stage: needs review, E2E-core
