### ISSUE TITLE
Very urgent - I have 8.4.1 and getting an error that Cypress can't open chrome

### ISSUE THREAD

**Issue by stavakolian** [cypress-io/cypress#18209] opened 2021-09-22 21:10 UTC
### Current behavior

```
 Error launching browser

Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 58391.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:58391 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

### Test code to reproduce

And here is the stacktrace:

**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">58391</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:58391
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m58391[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:58391
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

    at get (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1012:15)
    at Object.throwErr [as throw] (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1030:9)
    at /Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:113:21
    at tryCatcher (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/stavakolian/Library/Caches/Cypress/8.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```

### Cypress Version

8.4.1

### Other

please email me the steps on how to fix this issue.
stavakolian@collegeboard.org

**Comment by jennifer-shehane** [comment] 2021-09-23 18:45
Duplicate of https://github.com/cypress-io/cypress/issues/15650 I'm not sure why this happens sometimes for some users.

**Closed by jennifer-shehane** 2021-09-23 18:45 UTC
