### ISSUE TITLE
Node js error after run and pass test on Team City Assertion `(env) != nullptr' failed.

### ISSUE THREAD

**Issue by kamiloski** [cypress-io/cypress#8863] opened 2020-10-16 10:14 UTC
After update to 5.4.0 and run tests on Team City get node error in build log

### Current behavior
``` 
  Node.js[6064]: ../../third_party/electron_node/src/api/callback.cc:226: Assertion (env) != nullptr' failed.`

     1: 00007FF762152E06 node::Buffer::New+45830

     2: 00007FF762152BDB node::Buffer::New+45275

     3: 00007FF762123DAB node::MakeCallback+315

     4: 00007FF762123C3E node::MakeCallback+158

     5: 00007FF762123B6A node::MakeCallback+138

     6: 00007FF75F4A3778 v8::internal::OSROptimizedCodeCache::OSROptimizedCodeCache+206456

     7: 00007FF75F389641 v8::String::Value::length+99665

     8: 00007FF75F38951F v8::String::Value::length+99375

     9: 00007FF75F386FB4 v8::String::Value::length+89796

    10: 00007FF75F386E60 v8::String::Value::length+89456

    11: 00007FF761324820 v8_inspector::V8StackTraceId::ToString+12220704

    12: 00007FF760EEFFFA v8_inspector::V8StackTraceId::ToString+7811322

    13: 00007FF760DFC384 v8_inspector::V8StackTraceId::ToString+6812804

    14: 00007FF75F4174F4 v8_inspector::V8InspectorClient::memoryInfo+28292

    15: 00007FF75F418170 v8_inspector::V8InspectorClient::memoryInfo+31488

    16: 00007FF75F419E70 v8_inspector::V8InspectorClient::memoryInfo+38912

    17: 00007FF75F419C3F v8_inspector::V8InspectorClient::memoryInfo+38351

    18: 00007FF760E0C54D v8_inspector::V8StackTraceId::ToString+6878797

    19: 00007FF760E0DE5B v8_inspector::V8StackTraceId::ToString+6885211

    20: 00007FF760E09A2F v8_inspector::V8StackTraceId::ToString+6867759

    21: 00007FF760CE741F v8_inspector::V8StackTraceId::ToString+5678367

    22: 00007FF760CE6F73 v8_inspector::V8StackTraceId::ToString+5677171

    23: 00007FF761E7A74B IsSandboxedProcess+417899

    24: 00007FF75FF7BA6E v8::Location::GetColumnNumber+784398

    25: 00007FF75F35149F Ordinal0+5279

    26: 00007FF7653ED042 uv_random+16902530

    27: 00007FFFC6C61412 BaseThreadInitThunk+34

    28: 00007FFFC88954F4 RtlUserThreadStart+52
```
### Test code to reproduce
cypress run (on TeamCity)

### Versions
Team City, electron browser

**Comment by jennifer-shehane** [comment] 2020-10-21 11:01
Duplicate of #8865

**Closed by jennifer-shehane** 2020-10-21 11:01 UTC
