### ISSUE TITLE
Test cases are not working with run -- headed

### ISSUE THREAD

**Issue by ssamaji** [cypress-io/cypress#4307] opened 2019-05-24 13:11 UTC
### Current behavior:
Test Cases are working fine when i run it manually but when i do cypress run --headed, i am getting blank screen

### Versions

<img width="1437" alt="couponsRanManually" src="https://user-images.githubusercontent.com/26387897/58330237-1703fa00-7e54-11e9-801a-7d54737575d1.png">
<img width="1439" alt="couponsRanCI" src="https://user-images.githubusercontent.com/26387897/58330240-179c9080-7e54-11e9-9138-efe08753ca4f.png">

**Comment by jennifer-shehane** [comment] 2019-05-28 06:31
@ssamaji It doesn't look like you are calling `cy.visit()` during the "Verify Coupons Details" test. From the command log, I see

```
cy.wait(2000)
cy.get("#coupon_history_tab")
```

If you're trying to visit beforehand, you should know that any `before` hooks are only called *once* before the entire test run. If you want to visit before each test, make sure `cy.visit()` is in a `beforeEach`. 

If you're still having an issue, please paste your test code here for us to look at.

**Comment by ssamaji** [comment] 2019-05-28 08:53
@jennifer-shehane i am getting user beacon call failed Error: Unauthorized error. this is not issue with beforeEach. Can you please help with this error if you have any idea when we get such error.

Thanks,
Swati
<img width="1439" alt="404Error" src="https://user-images.githubusercontent.com/26387897/58464855-17520d00-8154-11e9-8d12-9ee3bd48e5e4.png">

**Comment by jennifer-shehane** [comment] 2019-05-29 08:37
Could you provide the test code you are running please?

Also, it looks like you're still getting 401 responses from your server. I'm not sure how your application qualifies you as authorized, but you'll want to mimic this completely.

**Comment by jennifer-shehane** [comment] 2019-06-06 08:19
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-06-06 08:19 UTC
Labels: stage: needs information
