### ISSUE TITLE
Element 

### ISSUE THREAD

**Issue by CatherineLearmonth** [cypress-io/cypress#2365] opened 2018-08-17 10:47 UTC
Bug 

Current behavior:
This command in a cypress test:
```js
cy.get('#psw-icon-sidebar').click()
```

Results in this error:
```
*******************************************************************************************************
CypressError: Timed out retrying: cy.click() failed because this element is not visible:
<pre>
&lt;button id="psw-icon-sidebar" class="psw-icon" title="Search"&gt;...&lt;/button&gt;
This element '&lt;button#psw-icon-sidebar.psw-icon&gt;
</pre>' is not visible because it has an effective width and height of: '0 x 0' pixels.
Fix this problem, or use {force: true} to disable error checking.
********************************************************************************************************
```
This error is unpredictable - sometimes the element is found and other times it is not found by cypress. We regularly get failed tests due to this issue. 
The element can definitely be found with jQuery in the console. 

Desired behavior:

Using the cy.get command on an element that can be found with an equivalent jQuery command should be able to then click on that element in cypress. 

Steps to reproduce:

1) Create a button element inside some divs:
<pre>
&lt;div id="contentWrapper"&gt;
&lt;div class="psw-container"&gt;
&lt;div id="psw-sidebar&gt;
&lt;button id="psw-icon-sidebar" class="psw-icon ui-button ui-corner-all ui-widget" title="Search"&gt;&lt;span class="mdi mdi-search"&gt;&lt;/span&gt;&lt;/button&gt;
&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;
</pre>

2) Use the `cy.get` command to get `'#psw-icon-sidebar'` and click on this element. 

3) Sometimes the element will not be visible, and cypress can not find it, and sometimes cypress can find it.

Versions

Cypress 2.1.0
Chrome browser Version 68.0.3440.106 (Official Build) (64-bit)
Windows 64

**Comment by jennifer-shehane** [comment] 2018-09-10 09:59
Duplicate of https://github.com/cypress-io/cypress/issues/695

**Closed by jennifer-shehane** 2018-09-10 09:59 UTC
Labels: stage: needs investigating, topic: visibility
