### ISSUE TITLE
Historie view DOM changes

### ISSUE THREAD

**Issue by RonaldVanMaanen** [cypress-io/cypress#2537] opened 2018-09-27 18:54 UTC
### Current behavior:
--Background
We have a web application to manage case cases written in Blueriq (https://www.blueriq.com/en/) which uses a server to process data and perform calculations

--Description
When we run a testcase that fills several drop down lists we observe that in the right-hand browser view pane the ddl's are filled.
When the scripts fails and we click on a earlier step that went OK and where all the ddl's have values selected. We observe in the right-hand browser view pane that the ddl's don't have a selected value.

Due to confidenciality reasons I can't provide images or scripts, I can only provide this description.

### Desired behavior:
The ddl's that have values selected in the earlier selected step should be displayed as they where selected.

### Steps to reproduce:

1) Create a test case that selects value(s) in ddl('s).
2) Run the script
3) When the script fails scroll the right-hand-site-browser view and observe that the ddl's have values selected.
4) Select a step in the test case run history
5) Observe that in all right-hand-site-browser views the ddl's dont have a value any more.

### Versions
Cypress = 3.0.1
OS = Windows 2008 server via remote desktop.
Browser = Chrome / Electron

**Comment by RonaldVanMaanen** [comment] 2018-09-27 18:57
Strange, somehow my message text is not saved. Therefore as a comment.

<!-- 
### Current behavior:
--Background
We have a web application to manage case cases written in Bluerig (https://www.blueriq.com/en/) which uses a server to process data and perform calculations

When we run a testcase that fills several drop down lists we observe that in the right-hand browser view pane the ddl's are filled.
When the scripts fails and we click on a earlier step that went OK and where all the ddl's have values selected. We observe in the right-hand browser view pane that the ddl's don't have a selected value.

Due to confidenciality reasons I can't provide images or scripts, I can only provide this description.

### Desired behavior:
The ddl's that have values selected in the earlier selected step should be displayed as they where selected.

### Steps to reproduce:

1) Create a test case that selects value(s) in ddl('s).
2) Run the script
3) When the script fails scroll the right-hand-site-browser view and observe that the ddl's have values selected.
4) Select a step in the test case run history
5) Observe that in all right-hand-site-browser views the ddl's dont have a value any more.

### Versions
Cypress = 3.0.1
OS = Windows 2008 server via remote desktop.
Browser = Chrome / Electron

**Comment by jennifer-shehane** [comment] 2018-10-02 15:07
Dropdowns are not being re-selected when viewing previous snapshots.

**Comment by jennifer-shehane** [comment] 2019-07-16 08:43
closing as duplicate of https://github.com/cypress-io/cypress/issues/4443

**Closed by jennifer-shehane** 2019-07-16 08:43 UTC
Labels: type: feature
