### ISSUE TITLE
CypressError: Timed out retrying: Not enough elements found. Found '2', expected '2'.

### ISSUE THREAD

**Issue by aldarund** [cypress-io/cypress#2205] opened 2018-07-24 12:34 UTC
### Current behavior:

https://i.imgur.com/S8HQyMc.png

### Desired behavior:

Well, obviously it should pass.

### Steps to reproduce:

"baseUrl": "https://beta.tenantreport.net/",

```js
describe('Signup Affiliate test', () => {
  it('Affiliate signup Test', () => {
    cy.visit('/auth/signup/referral/')

    cy.get('.toolbar-link').should($p => {
      expect($p).to.have.length(2)
      expect($p.first()).to.contain('Signup')
      expect($p.eq(1)).to.contain('Login')
    })
  })
})
```

### Versions

Cypress 3.0.2
Electron

Work fine on chrome, but i cant use chrome because of https://github.com/cypress-io/cypress/issues/2037

**Comment by jennifer-shehane** [comment] 2018-07-24 22:15
I was able to recreate this in Electron 59. 

**reproducible example**
```js
it('Affiliate signup Test', () => {
  cy.visit('https://beta.tenantreport.net/auth/signup/referral/')
  cy.get('.toolbar-link').should('have.length', 2)
})
```

**Comment by zhenyi2697** [comment] 2018-09-18 16:07
I also have the same issue with cypress@3.1.0. When I run the test alone, it passed Ok. It fails only if it runs with other tests, which is very weird.

**Comment by Elshaikh** [comment] 2019-02-19 10:36
i have same issue here , @jennifer-shehane , could u check plz 
`Version 3.1.5 
    describe('Verifying customer can Browse all static pages',  () => {
        it(' Assert tajawal footer 9 page-links contain proper title and visible to traveler and direct on probper Url', function () {
            cy.get('.footer-page-links li').should(($lis) => {
                //expect($lis).to.have.length(28)
                expect($lis.eq(0)).to.contains('Contact us').and('have.attr','href','/en/contact-us').click().wait(1000)// true
                expect($lis.eq(1)).to.contain('FAQ\'s').and('have.attr', 'href', '/en/faq').click().wait(1000)// true`
Error:     CypressError: Timed out retrying: obj.indexOf is not a function

**Comment by jennifer-shehane** [comment] 2019-02-19 11:04
Hey @Elshaikh, this error is due to a typo in your assertion. 

>expect($lis.eq(0)).to.contains('Contact us')

This should be `contain` not `contains` like

```
expect($lis.eq(0)).to.contain('Contact us')
```

**Comment by SOMIASHARMA26** [comment] 2019-09-06 08:41
Hi @jennifer-shehane

I have same issue when I run 

cy
	.get('input[id="searchinput"]')
     .type(this.admin.password);
	cy.get('button[name="Login-btn1"]').click();
	
	
	cy.get('h3').should('contain','Organizations')
		cy.get('div[id="_divorgDiv0"]').click();

**Comment by jennifer-shehane** [comment] 2021-10-15 20:48
The original issue is no longer reproducible, so I can't confirm if this was fixed or not. 

Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-10-15 20:48 UTC
Labels: type: bug, stage: ready for work
