### ISSUE TITLE
Give users an option to ignore --parallel or --record flags when Cypress Dashboard is down

### ISSUE THREAD

**Issue by istateside** [cypress-io/cypress#20356] opened 2022-02-24 17:22 UTC
### What would you like?

A new configuration option to instruct the cypress runner to handle failures from the Cypress Dashboard servers without fully failing the test run. Allow users to configure the runner to continue running the tests without smart orchestration and without recording test results if the Dashboard is down.

### Why is this needed?

When tests are run with `--record` or `--parallel`, the cypress runner attempts to communicate with the Cypress Dashboard servers before proceeding with any tests. If the server returns a 5** status three times in a row, the runner prints an error and exits the process.

It would be helpful if there was an option to fail gracefully here and automatically switch over to running the tests without parallelization, or without any of the dependencies that require the Cypress Dashboard to be available. If the dashboard is not available, it's important to me that my CI builds can continue to run and pass or fail based on the test results.

The servers are generally stable, but we've had two incidents where the servers went down and caused all of our CI builds to fail. Those failures mean we can't merge PRs, since a passing build is a required status check in our Github config. Luckily, the two times where the Dashboard went down were resolved fairly quickly, but it would have slowed down our response time if we needed to merge and deploy an urgent fix to our application.

**Comment by Ponthius** [comment] 2022-02-24 17:24
Stop sending me these OK!

**Comment by jennifer-shehane** [comment] 2022-02-24 17:49
@Ponthius You should check your GitHub subscriptions, you may be watching for notifications on the repo that you can unwatch. 

Duplicate of https://github.com/cypress-io/cypress/issues/2525

**Closed by jennifer-shehane** 2022-02-24 17:49 UTC
