### ISSUE TITLE
Page is not loading properly in chrome using cypress

### ISSUE THREAD

**Issue by ajayprakash83** [cypress-io/cypress#5915] opened 2019-12-09 09:36 UTC

**Comment by ajayprakash83** [comment] 2019-12-09 09:38
Able to open URL on chrome but using cypress page is not loading properly and getting below error.

![error](https://user-images.githubusercontent.com/58553386/70424674-c2456b00-1a95-11ea-9662-b9b9c6b2e47d.png)

**Comment by jennifer-shehane** [comment] 2020-01-02 07:58
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2020-01-02 07:58 UTC

**Comment by ajayprakash83** [comment] 2020-01-07 14:45
You are requested to check this, i have mentioned things in Issue Template.

**Comment by jennifer-shehane** [comment] 2020-01-13 10:14
You have not provided enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue, we cannot visit `182.74.202.219` for example and recreate your issues. Please provide the test code to reproduce also.

**Comment by ajayprakash83** [comment] 2020-01-13 12:56
I am only visiting a website using cy.visit(182.74.202.219) and using cypress open like: ( i have erase some information from screenshot)
![image](https://user-images.githubusercontent.com/58553386/72257636-1e218780-3632-11ea-837f-bc78230e5a8c.png)

**Comment by ajayprakash83** [comment] 2020-01-13 13:01
Hi Jennifer,

Thanks for reply..

I am just visiting the provided URL only and UI is not opening completely using cypress. If i use same URL in chrome directly then it is opening without any issue.

Please have a look....

Thanks
Ajay Prakash

________________________________

**Comment by jennifer-shehane** [comment] 2020-01-14 05:56
@ajayprakash83 We cannot have a look at the issue since there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example *that we can run on our own machines* and we will reopen the issue.
