### ISSUE TITLE
Range Error - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by HafizGhulamAbbas** [cypress-io/cypress#24790] opened 2022-11-23 07:46 UTC
### Current behavior

When I am trying to traverse the DOM using cypress recursively, it is giving Range Error - Maximum call stack size exceeded.

### Desired behavior

When I traverse any website's DOM, it should work fine without any complain. As I am doing it recursively, I've added the base condition to avoid the infinite loops.

### Test code to reproduce

- In a test case, call a function with a parameter: rootElement
- attributesCompliance() function should return the children attributes recursively

**FUNCTION:**

```
function attributesCompliance(baseElement) {
    cy.log("Called for element " + baseElement)
    if(Cypress.$(baseElement).get(0).childNodes.length == 0) {
      cy.log("Found no child, returning...")
      return
    }
    let nodeList = Cypress.$(baseElement).get(0).children
    for(let node of nodeList){
      cy.log("Printing child attributes " + node.getAttributeNames())
      attributesCompliance(node.tagName.toLowerCase())
    }
  }
```

**TEST CASE:**
```
it.only('checks element does not have duplicate attributes', () => {
      attributesCompliance('body')
}
```

### Cypress Version

^11.1.0

### Node version

v16.17.1

### Operating System

macOS 12.6

### Debug Logs

```shell
at <unknown> (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:167303:19)
at arrayMap (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:28250:23)
at Function.map (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:37219:14)
at normalizeStackIndentation (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:167300:78)
at normalizedUserInvocationStack (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:167373:10)
at Object.captureUserInvocationStack (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:167103:25)
at cy.<computed> [as log] (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:157865:96)
at runnable.fn (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:158077:19)
at callFn (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:107989:21)
at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:107976:7)
at <unknown> (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:165418:30)
at PassThroughHandlerContext.finallyHandler (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:7881:23)
at PassThroughHandlerContext.tryCatcher (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:11327:23)
at Promise._settlePromiseFromHandler (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:9262:31)
at Promise._settlePromise (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:9319:18)
at Promise._settlePromise0 (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:9364:10)
at Promise._settlePromises (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:9444:18)
at _drainQueueStep (https://rahulshettyacademy.com/__cypress/runner/cypress_runner.js:6034:12)
```

### Other

<img width="521" alt="Screenshot 2022-11-23 at 12 43 21 PM" src="https://user-images.githubusercontent.com/13692762/203494248-ae604ef4-39d6-4d22-86da-0dd9138d5174.png">

**Comment by nagash77** [comment] 2022-11-23 19:14
@HafizGhulamAbbas Im sorry to hear you are having issues using Cypress.  Can you provide the HTML for the page you are running against?  Or even better a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by HafizGhulamAbbas** [comment] 2022-11-24 05:26
You can try any website but I am using https://www.drupal.org/project/dummyimage

**Comment by BlueWinds** [comment] 2022-12-08 18:45
I'm not able to reproduce myself.

```
describe.only('stuff', () => {
  function attributesCompliance(baseElement) {
    cy.log("Called for element " + baseElement)
    if(cy.$$(baseElement).get(0).childNodes.length == 0) {
      cy.log("Found no child, returning...")
      return
    }
    let nodeList = cy.$$(baseElement).get(0).children
    for(let node of nodeList){
      cy.log("Printing child attributes " + node.getAttributeNames())
      attributesCompliance(node.tagName.toLowerCase())
    }
  }

  it('checks element does not have duplicate attributes', () => {
    cy.visit('https://www.drupal.org/project/dummyimage')

    cy.then(() => {
      attributesCompliance('body')
    })
  })
})
```

passes for me in all browsers, firefox, chrome and electron, in Cypress 11 and Cypress 12.

I moved the attributesCompliance inside a `.then()` block to ensure that it's only executed after cy.visit() completes. Remember that all commands are async - the entire function body is executed before any commands even start!

https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Commands-Are-Asynchronous

**Comment by HafizGhulamAbbas** [comment] 2022-12-20 08:30
Hi @BlueWinds,
I gave it a try as you mentioned but same error. 

```
/// <reference types="cypress" />


describe('Using alt attributes on img elements', () => {
  beforeEach(() => {
    cy.visit(Cypress.env('baseUrl'))
  })

  it('checks that each image element has an alt attribute', () => {
      cy.assertAttrExists('img', 'alt')
  })

  it.only('checks element does not have duplicate attributes', () => {
    cy.then(() => {
      attributesCompliance('body')
    })
  })
})

function attributesCompliance(baseElement) {
  cy.log("Called for element " + baseElement)
  if(cy.$$(baseElement).get(0).childNodes.length == 0) {
    cy.log("Found no child, returning...")
    return
  }
  let nodeList = cy.$$(baseElement).get(0).children
  for(let node of nodeList){
    cy.log("Printing child attributes " + node.getAttributeNames())
    attributesCompliance(node.tagName.toLowerCase())
  }
}
```

**Comment by HafizGhulamAbbas** [comment] 2022-12-20 08:33
However, I achieved my goal by using cy.wrap().within()....
Using this approach, it is traversing the whole DOM recursively. 

```
function attributesCompliance(baseElement) {
  cy.get(baseElement)
  .each((element) => {
    cy.wrap(element).within(() => {
      if(element.children().length == 0) {
        cy.log("Found no child, returning...")
        return
      }
      cy.get(element.children())
      .each((innerElement) => {
        cy.wrap(innerElement).within(ele => {
          let el = Cypress.$(ele[0].tagName.toLowerCase())
          if(el[0].getAttributeNames().length > 1) {
            cy.log("Trying to print attributes: " + el[0].getAttributeNames())
          }
          attributesCompliance(innerElement)
        })
      })
    })
  })
}
```

**Comment by HafizGhulamAbbas** [comment] 2022-12-20 08:33
I am unsure to close this thread or keep it open? @BlueWinds

**Comment by BlueWinds** [comment] 2022-12-20 22:02
Going to close this out. Sorry I wasn't able to help super much, and glad you figured something out! Very strange that we kept getting different results from running the same tests.

**Closed as not planned by BlueWinds** 2022-12-20 22:02 UTC
