### ISSUE TITLE
Cypress hangs on test failure in GitHub actions for hours

### ISSUE THREAD

**Issue by mduft** [cypress-io/cypress#18546] opened 2021-10-19 12:47 UTC
### Current behavior

![Screenshot from 2021-10-19 14-40-20](https://user-images.githubusercontent.com/533793/137912231-05328ffb-345d-49a7-bd41-ed7f365398cf.png)

See screenshot - there is no output by cypress, and it hangs for multiple *hours* on a failing test. We have configured videos only on failure, might be related? Shouldn't there be output in this case?

### Desired behavior

No hour-long hangs.

### Test code to reproduce

Can see full logs here: https://github.com/bdeployteam/bdeploy/runs/3935564140?check_suite_focus=true

### Cypress Version

8.6.0

**Comment by qlimlass** [comment] 2021-10-19 20:38
[Issue #18502](https://github.com/cypress-io/cypress/issues/18502) I posted this recently and it may or may not be related to the problems you guys are having.

**Comment by mduft** [comment] 2021-10-20 05:00
Hm. In our test we do not have any after* hooks and or retries...

**Comment by ilmente** [comment] 2021-10-21 20:49
I removed the retries and it seems better, but it stills hangs on sync requests. 
By removing the retries I just reduce the chance of a hang.
I do not have any AfterEach implemented.

**Comment by sdoasddd0921** [comment] 2021-11-02 01:27
> Seeing the same behavior with failed tests in 8.6, not using cypress-cucumber-preprocessor. Running `cypress run` locally works fine however.

+1, our CI pipeline got stuck for hours because of cypress hanging when tests not pass all, but when tests pass all, it works fine...

**Comment by sdoasddd0921** [comment] 2021-11-02 01:59
I was close video feature in my config, and every thing goes fine on my local machine.
Since I run my test on CI, I got same problem with you, cypress is hanging when tests not passed all, or crash with signal SIGSEGV.
I search and try for nights but find nothing helps.
I found this issue in the morning, and go back to enable video, and my CI works fine.
Cypress version: 8.7.0
Docker Image: cypress/browsers:latest

**Comment by wrotson** [comment] 2021-11-04 07:50
@jennifer-shehane is there any common issue already reported for that? I also have this issue on 8.1, 8.2, 8.6

**Comment by wrotson** [comment] 2021-11-05 07:07
> I was close video feature in my config, and every thing goes fine on my local machine. Since I run my test on CI, I got same problem with you, cypress is hanging when tests not passed all, or crash with signal SIGSEGV. I search and try for nights but find nothing helps. I found this issue in the morning, and go back to enable video, and my CI works fine. Cypress version: 8.7.0 Docker Image: cypress/browsers:latest

Unfortunately it didn't work for me

**Comment by rodilo** [comment] 2021-11-12 09:20
I'm facing the same issue.
Locally all works well, but if error happens while running tests on GithubActions, process hangs.
I've added `DEBUG=cypress:* ` but I don't see anything related to error.
I've tried running a firefox and chrome, same issue.

**Comment by BlueWinds** [comment] 2021-11-16 21:29
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/17627. I'm going to close this issue in favor of that one.

If people don't think it's the same problem, please comment here and I'll look at reopening. Closing isn't meant as a dismissal of the problem - it's definitely a real issue and it's on the list to look at, but keeping things consolidated makes them easier to track.

**Closed by BlueWinds** 2021-11-16 21:29 UTC

**Comment by pmweeks98** [comment] 2021-11-19 12:44
Not sure this is the same issue @BlueWinds, that issue times out when loading a script url and is not reproducible locally (wasn't for me anyway). This seems to be reproducible locally and has a different  (but similar) error

**Comment by chainerprince** [comment] 2022-10-04 21:29
> 

Getting the same error. Any solution yet?

**Comment by JirakJ** [comment] 2023-02-03 11:41
Hi there, I hunted this error as a memory leak, but a memory leak did not cause it. It looks like some promise was never received and is stuck in this infinity load. But it looks like adding just return to beforeEach/afterEach methods at the end helps to prevent these kinds of stuck.

**Comment by MoSattler** [comment] 2023-07-24 14:18
Same problem here - I trued to debug it, but for some reason the whole error wasn't shown:

>   cypress:https-proxy received error on client browserSocket { err: Error: write EPIPE     at afterWriteDispatched (node:internal/stream_base_commons:160:15)     at writeGeneric (node:internal/stream_base_commons:151:3)     at Socket._writeGeneric (node:net:817:11)     at Socket._write (node:net:829:8)     at writeOrBuffer (node:internal/streams/writable:389:12)     at _write (node:internal/streams/writable:330:10)     at Writable.write (node:internal/streams/writable:334:10)     at Socket.ondata (node:internal/streams/readable:754:22)     at Socket.emit (node:events:527:28)     at addChunk (node:internal/streams/readable:315:12)     at readableAddChunk (node:internal/streams/readable:289:9)     at Readable.push (node:internal/streams/readable:228:10)     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) { errno: -32, code: 'EPIPE', sysca...
