### ISSUE TITLE
Cypress Cloud Test Replay Issue with File Uploads

### ISSUE THREAD

**Issue by Yehudami** [cypress-io/cypress#27761] opened 2023-09-07 11:16 UTC
### Current behavior

If the spec contains file upload the run is stuck and that is the output I get:

### Desired behavior

Will complete the run and will have the option to view the test replay

### Test code to reproduce

Private code, Try running a code that contains a file upload with the 'Test Replay' feature

### Cypress Version

V13.1.0

### Node version

V16.14.2

### Operating System

macOS 13.5

### Debug Logs

```shell
` (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.1.0                                                                         │
  │ Browser:        Chrome 116 (headless)                                                          │
  │ Node Version:   v16.14.2 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (patientChat.cy.js)                                                    │
  │ Searched:       cypress/e2e/grinAutomation/grinWebapp/SanityTest/patientActions/patientChat.cy │
  │                 .js, command                                                                   │
  │ Params:         Tag: false, Group: false, Parallel: false                                      │
  │ Run URL:        https://cloud.cypress.io/projects/nk2dp1/runs/138                              │
  │ Experiments:    experimentalRunAllSpecs=true,experimentalMemoryManagement=true,experimentalSt… │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  patientChat.cy.js                                                               (1 of 1)
  Estimated: 2 minutes, 47 seconds


  Patient chat
    send file to a patient
      ✓ should send an image to a patient (42794ms)
      ✓ should send a PDF file to a patient (25258ms)
      ✓ should send a video file to a patient (33430ms)


  3 passing (2m)

`
```

**Comment by nagash77** [comment] 2023-09-07 12:38
Hi @Yehudami I think your error message got cut off or you forgot to add it in. Do you see the run show up in your Cypress Cloud at all?  Can you share the URL to that test replay run if so?

If not, try to create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by Yehudami** [comment] 2023-09-07 12:49
Hey, I did not cut the message and I've seen a couple of people sending the same output that I've got.
I'll try to create a reproduction example, but if it takes me to long, you need to run your test with a file upload test (that is when I experienced the issue, I isolated the tests to see when it is happening)

Thank you,
Yehuda

**Comment by jennifer-shehane** [comment] 2023-10-05 01:50
@Yehudami Our project has tests around file upload. We’d need your specific example since it’s likely isolated to something unique. Closing since there’s no reproduction. If you provide one we can reopen.

**Closed as completed by jennifer-shehane** 2023-10-05 01:50 UTC

**Comment by Yehudami** [comment] 2023-10-05 07:14
It seems to be resolved now,
Thank you,
Yehuda
