### ISSUE TITLE
.wait() behaving inconsistently - does not always see that XHR calls completed

### ISSUE THREAD

**Issue by kyrstenkelly** [cypress-io/cypress#7447] opened 2020-05-21 16:47 UTC
### Current behavior:

When I am running my tests, about half the time Cypress does not see that the XHR requests I have told it to wait for have completed successfully. I can rerun the test many times and it works only about half the time. 

Here is a screenshot of the test timing out because `No response ever occurred`, even though you can see in the Cypress logs that more than 4 `graphl` XHR calls successfully returned w/ a 200:

![Screen Shot 2020-05-21 at 5 06 59 PM](https://user-images.githubusercontent.com/3144408/82611483-3c6e3580-9b86-11ea-9a6d-aa451f8efc60.png)

And I then re-ran the test, and got this.....same XHR calls, all successful, but this time the `wait` finished properly:

![Screen Shot 2020-05-21 at 5 08 09 PM](https://user-images.githubusercontent.com/3144408/82611491-4001bc80-9b86-11ea-962b-8876efe7effc.png)

### Desired behavior:

Consistent test behavior. It seems like maybe `cy.wait(...)` is not seeing that the XHR requests finish if they happen too fast? 

### Test code to reproduce

This can easily be reproduced if you don't mind creating a Udacity account. 

1. See my test code here: https://github.com/kyrstenkelly/cypress-test-tiny
2. Create a [Udacity account](https://auth.udacity.com/sign-up) (it's free!)
3. Find your `_jwt` cookie, and paste that into the test where cypress sets a cookie
4. Run the tests repeatedly. Sometimes they pass, sometimes they don't.

Here is an overview of the code.

I have read through so many issues and as far as I can tell, from a code perspective I am doing things correctly. I am starting the server & setting up routes _before_ using `cypress.visit()`. If I am setting this up incorrectly, please let me know.

```ts
describe('Our website', () => {
  beforeEach(() => {
    cy.setCookie('_jwt', '< add your JWT here >');

    cy.server();
    cy.route({
      url: '**/graphql',
      method: 'POST' 
    }).as('apiRoute');
  });

  it(`Has no accessibility violations`, () => {
    cy.visit('https://classroom.udacity.com/me');

    // Also try waiting for the requests one at a time - but neither seems to work
    // cy.wait('@apiRoute');
    // cy.wait('@apiRoute');
    // cy.wait('@apiRoute');
    // cy.wait('@apiRoute');
    cy.wait(['@apiRoute', '@apiRoute', '@apiRoute', '@apiRoute']);

    expect(true);
  });
});
``` 

### Versions

Cypress: 4.6.0
System: mac OS 10.14
Browser: Electron 80 (when headless) or Chrome 83 in the GUI

**Comment by jennifer-shehane** [comment] 2020-05-22 07:00
This is something we've seen with GraphQL requests before unfortunately. Duplicate of #5999

**Closed by jennifer-shehane** 2020-05-22 07:00 UTC

**Comment by evba1** [comment] 2020-06-16 00:07
I have the same issue with xhr requests
