### ISSUE TITLE
Cypress can only run one test even no .only was specified

### ISSUE THREAD

**Issue by sangmai350** [cypress-io/cypress#4451] opened 2019-06-13 03:14 UTC
### Current behavior:
Currently, my test can run only one test

![image](https://user-images.githubusercontent.com/37669424/59400874-157a8180-8dc3-11e9-8e25-4f0c5ed95fc8.png)
[stacktrace.txt](https://github.com/cypress-io/cypress/files/3284043/stacktrace.txt)

### Desired behavior:
It should run all the expected tests if we dont specified .only param

### Steps to reproduce: (app code and test code)
1. Create a test suite with at least 2 test
2. execute with cypress open
3. Observe the result

### Versions
3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-13 05:53
Can you open the Developer Tools while running tests and post any errors being logged there in the console?

Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the logs here?

Can you provide the test code for `logoutPage` and `loginPage`. 

There is something specific that is making it hang on the 2nd test. We have not seen this issue before and won't be able to look into it without the specifics of your tests.

**Comment by sangmai350** [comment] 2019-06-13 08:09
There are no error on the console.
It happens across places, so not problem in code for logoutPage or loginPage.

**Comment by jennifer-shehane** [comment] 2019-06-17 09:13
Unfortunately we have to close this issue if you cannot provide any of the extra information asked for. We cannot look at issues we cannot reproduce. Sorry.

**Closed by jennifer-shehane** 2019-06-17 09:13 UTC
Labels: stage: needs information
