### ISSUE TITLE
cypress verify times out on WSL2

### ISSUE THREAD

**Issue by icorbrey** [cypress-io/cypress#8119] opened 2020-07-29 17:12 UTC
### Current behavior:

Trying to verify Cypress on WSL2 (Ubuntu 18.04) using VcXsrv times out:

```
$ npx cypress verify

  ✖  Verifying Cypress can run /home/icorbrey/.cache/Cypress/4.11.0/Cypress
    → Cypress Version: 4.11.0
Cypress verification timed out.

This command failed with the following output:

/home/icorbrey/.cache/Cypress/4.11.0/Cypress/Cypress --no-sandbox --smoke-test --ping=303

----------

Command failed: /home/icorbrey/.cache/Cypress/4.11.0/Cypress/Cypress --no-sandbox --smoke-test --ping=303

----------

Platform: linux (Ubuntu - 18.04)
Cypress Version: 4.11.0
```

### Desired behavior:

Cypress should verify as expected.

### Test code to reproduce

Under WSL 2 with dependencies installed:

```
$ npm init
$ npm install cypress
$ npx cypress verify
```

### Versions

* WSL: `2`
* Cypress: `4.11.0`
* VcXsrv: `1.20.8.1`
* Ubuntu: `18.04 LTS`

**Comment by icorbrey** [comment] 2020-07-29 18:01
Fixed by installing `xvfb` and unsetting `DISPLAY`, however unsetting the env variable shouldn't be required

**Comment by jennifer-shehane** [comment] 2020-07-30 06:49
Duplicate of #7065

**Closed by jennifer-shehane** 2020-07-30 06:49 UTC
