### ISSUE TITLE
Early logging (support/index.js and similar)

### ISSUE THREAD

**Issue by Vandivier** [cypress-io/cypress#3541] opened 2019-02-20 16:34 UTC
### Current behavior:

Using `console.log` or `cy.log` within `support/index.js` fails.

`Console.log` is silent.

`cy.log` throws cannot call outside a running test.

### Desired behavior:

I can `console.log` and it will be printed to the command line (or perhaps somewhere else, but in this way I'm envisioning `index.js` is similar to a typical `server.js`) and perhaps even use `debugger` with `chrome://inspect` within `index.js` and similar setup files.

A concrete use case, but by no means exhaustive, is to log `process.env` values to ensure they are populated correctly from CLI, and then if they are unpopulated or mispopulated when a specific test runs we would be able to narrow down the error space and better identify the cause of the late mispopulation.

### Versions

I'm using Chrome 72 on Windows 7 with Cypress: 3.1.5 (although I don't think that matters)

**Comment by jennifer-shehane** [comment] 2019-02-20 17:03
Duplicate of https://github.com/cypress-io/cypress/issues/3541

**Closed by jennifer-shehane** 2019-02-20 17:03 UTC

**Comment by Vandivier** [comment] 2019-02-20 17:12
@jennifer-shehane did you just close this ticket as a duplicate of itself?

**Comment by jennifer-shehane** [comment] 2019-02-20 17:18
Doh, yes 🤦‍♂️ Duplicate of this I mean https://github.com/cypress-io/cypress/issues/3199
