### ISSUE TITLE
Misleading error mesage when redirecting

### ISSUE THREAD

**Issue by Hypenate** [cypress-io/cypress#24287] opened 2022-10-18 07:32 UTC
### Current behavior

We have redirect to Auth0, which has a statuscode of **302** (redirect), and the error cypress shows is:
The response we received from your web server was:
  > **404**: Not Found
  This was considered a failure because the status code was not `2xx`.

 

### Desired behavior

The output should match the actual response of the web server.

### Test code to reproduce

Go to a page
Redirect to another page

404 is shown but 302 was the actual response

### Cypress Version

10.9.0

### Node version

v16

### Operating System

Windows

**Comment by nagash77** [comment] 2022-10-18 13:53
@Hypenate Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-10-25 13:45
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-10-25 13:45 UTC
