### ISSUE TITLE
 Failed test

### ISSUE THREAD

**Issue by andradec** [cypress-io/cypress#4601] opened 2019-06-28 14:31 UTC
### Current behavior:

I am starting my studies in Cypress, I created a basic project and created the following script:
![image](https://user-images.githubusercontent.com/21975206/60349494-151fe000-9998-11e9-80f7-2453d4ba3f3e.png)

However when running the following message appears, can anyone help me?
![image](https://user-images.githubusercontent.com/21975206/60349530-28cb4680-9998-11e9-9416-5c2175e1f33f.png)

**Comment by hvuong-sigma** [comment] 2019-06-28 17:08
You might want to consider adding that `url` as a `baseUrl` in your Cypress config.

**Comment by jennifer-shehane** [comment] 2019-07-01 06:18
This message means there is an uncaught exception being thrown from within your application. Open DevTools and click the yellow message to see the full stack trace where this is originating from. Closing as this is not a bug or feature request.

**Closed by jennifer-shehane** 2019-07-01 06:18 UTC
