### ISSUE TITLE
Cypress Testrunner (Chrome/Mac) randomly stops executing tests

### ISSUE THREAD

**Issue by marc-guenther** [cypress-io/cypress#7432] opened 2020-05-20 14:17 UTC
### Current behavior:

While developing tests, the graphical Testrunner (which runs inside Chrome) just suddenly stops executing anything. This happens at completely random times, but it happens so frequently, that I wanted to report it.

The only thing that still runs is the timer, and it also still recognises changed files, in which case it will restart the timer from 0, but still it won't do anything.

To make it work again, I have to quit Chrome, and in the Cypress Ui, klick on Stop, and then launch the test suite again. It will then sometimes fail again in the middle of the next test run.

### Desired behavior:

Obviously it shouldn't freeze.

### Test code to reproduce

I cannot reproduce this at will, but when using Cypress for 10min, it happens at least 5 times. I don't know if this is a problem with my machine only, or if this happens to other people as well.

### Versions

Cypress Version 4.4.0 (4.4.0.300671)
Chrome Version 83.0.4103.61 (Official Build) (64-bit)
macOS Version 10.12.6 (16G2136)

**Comment by RomanShmandrovskyi** [comment] 2020-05-20 14:29
Have the same issue on this Google Chrome version

**Comment by jennifer-shehane** [comment] 2020-05-20 14:43
Can either of you get a video of this behavior? It's hard to tell exactly what's meant by 'freezing' from the description. 

Also, when this happens are you able to see the Activity Monitor, is it the Chrome Process CPU that's maxed out? Something else?

Does any of the freezing happens in other browsers? Firefox / Electron?

@RomanShmandrovskyi What version of Chrome are you using? Which part of Chrome is a 'white screen'?

**Comment by RomanShmandrovskyi** [comment] 2020-05-20 14:58
Yes, just want to create a video
Give me some minutes

**Comment by RomanShmandrovskyi** [comment] 2020-05-20 15:08
@jennifer-shehane 
take a look on this one:
https://drive.google.com/open?id=1Wp_BiWVIN1gmRXptkHN493BsgJvEANT2

**Comment by marc-guenther** [comment] 2020-05-20 15:27
Hi Roman, this is a completely different behaviour from what I am seeing. Can you open a new issue for this?

I try to record a video later, but basically what happens is:
- I do `cypress open` and launch some tests
- Tests are running just fine in Chrome (in the Testrunner)
- I edit some files, tests automagically run again from that start
- And then at some random point in time, it just stops executing. All output stops, no more events are triggered, ...
- The only thing that still works is the counter
- and when I change a file, it restarts the counter from 0

**Comment by RomanShmandrovskyi** [comment] 2020-05-20 15:31
@marc-guenther 
Can you reproduce the same issue as on my video?
If no, I will create the new one issue

I want firstly try to downgrade cypress or chrome version and test it

**Comment by RomanShmandrovskyi** [comment] 2020-05-20 15:44
@marc-guenther just create the new issue

**Comment by marc-guenther** [comment] 2020-05-21 22:25
This is all very mysterious.

I was finally able to reproduce the issue reliably. It happens on Chrome, Firefox and Electron.

Unfortunately, this is a testcase of our inhouse app, and I wasn't yet able to isolate it.

But I found at least something related, whose presence is required to cause the issue, and that is already puzzling enough:

```
    cy.visit("www.google.de")
    cy.log(cy.get("input"))
```

This very reliably stops the Testrunner. To the user it looks like it is waiting for eg. an element to appear, but it never times out and simply waits forever.

![Huge Counter](https://www.dropbox.com/s/z55mz3in3eop35x/Cypress%20Waiting%20Forever.jpg?raw=1)
_I left this running during lunch_

I would be very interested if you can reproduce this behaviour on your side.  I tested this for Cypress version from 4.6.0 down to 3.4.1 and always got this behaviour.

Now for the mysterious part.

Unfortunately this is NOT the issue I reported earlier, because saving a file in this state still causes Cypress to re-run the tests. And it does this again and again and this works perfectly fine for the mini example above.

But I have a different testcase. This consists of about 80 steps and the last step is exactly the line above. This is the behavior I'm seeing:

- When I run the test, it stops at that line and waits forever, just like in the mini example above.
- When I then change a file (or simply click Stop and Restart), it runs again,
- BUT then it randomly stops at some command (which so far has always been either a `click()` or `type()` command). This command can be a different one every time.
- The Testrunner now is in a state where saving a file (or Stop/Restart button), causes it to reset and restart the timer from zero, and clear the event log, but then it doesn't do anything else anymore.
- The browser window is now completely useless, and I have to click "Stop" in the Cypress UI to kill it and start a new one.

Now THIS is the issue I reported earlier. So far I have not been able to reproduce it outside of this specific testcase.

Here is a [video](https://www.dropbox.com/s/r84g6p6ienv7023/Cypress%20Testrunner%20Hangs.mov?raw=1) of the whole experience. There it hangs at a `type(1)` command, but it could also have been any of the others, or a `click()`.

It gets even more mysterious. I tested the mini-example with several Cypress versions (from 4.6.0 - 3.4.1, I didn't go further down and I skipped some in the middle) and it happened every time. BUT running the longer testcase revealed this:
- 3.6.0 and up: As described above. First run  hangs at the `cy.log(...)` line. Second run stops earlier at some random click or type command. Third run doesn't start anymore.
- 3.5.0:  Almost like above. First run hangs at the `cy.log(...)` line. Second run also always stops there, and NOT at that random earlier command. Third run doesn't start anymore.
- 3.4.1: All runs of the testcase run up to the `cy.log...` line and hang, no matter how often I restart

Ok, that's all for today, it is past midnight by now, and I ran out of wine.

Marc

**Comment by marc-guenther** [comment] 2020-05-30 11:48
Can anyone reproduce the issue with my two liner from above, or does it only happen for me?

**Comment by jennifer-shehane** [comment] 2020-08-21 08:31
You should never be calling Cypress commands *within* other Cypress commands. `cy.log(cy.get('input'))` will not execute correctly due to the asynchronous nature of how commands are run. I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide.

Regardless, the example provided in https://github.com/cypress-io/cypress/issues/7432#issuecomment-632377653 was fixed in Cypress version 4.8.0 and will no longer run forever. 

Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-08-21 08:31 UTC
Labels: stage: needs information
