### ISSUE TITLE
Cypress cannot read baseUrl ending in slash `/`

### ISSUE THREAD

**Issue by dialex** [cypress-io/cypress#5268] opened 2019-10-02 14:42 UTC
### Current behavior:

If you have this url configured

```json
{
  "baseUrl": "http://google.com/"
}
```

When you run `Cypress.config().baseUrl` in a `before` function it returns `undefined`

### Desired behavior:

When you run `Cypress.config().baseUrl` in a `before` function it returns `http://google.com/`

### Steps to reproduce:

The **cause** is the `/` at the end of the URL.

If you remove it, then you get the desired behaviour. This is an issue hard to spot, it took me several hours to pinpoint the problem, as I had diff `baseUrl` per env and only one of them was failing for no apparent reason.

It would be great if Cypress supported `baseUrls` with and without trailing `/`.

### Versions

Cypress 3.4.1
Latest macOS, Chrome

**Comment by dialex** [comment] 2019-10-02 14:48
This might be related with #3540

**Comment by flotwig** [comment] 2019-10-02 16:02
May also be related: #5175

@dialex I was unable to reproduce this issue - setting a cypress.json with that `baseUrl`, this assertion still passes:

```coffee
before ->
  expect(Cypress.config().baseUrl).to.eq("http://google.com/")
```

This happens if I put the `before` before anything else, or if I nest the `before`.

Are you using any other configuration/plugins that may be related? How is your `before` hook setup?

**Comment by dialex** [comment] 2019-10-03 09:40
Thanks for caring about my issue :)

My setup is not very straightforward.

First, it loads some env variables, and based on those values it reads a `config.json` with the baseUrl of the site I'm currently testing. This happens on `plugins/index.js`.

```js
module.exports = async (on, config) => {
  on("file:preprocessor", selectTestsWithGrep(config))

  const targetEnv = validateEnv(process.env["ENV"])
  const targetSite = validateSite(process.env["SITE"])

  config = Object.assign({}, config, await getCypressConfig(targetSite, targetEnv))
  config.env = Object.assign({}, config.env, process.env)
  return config
}

async function getCypressConfig(site, env) {
  const pathToConfigFile = path.resolve(`cypress/config/${site}/${env}`, "config.json")
  return await fs.readJson(pathToConfigFile)
}
```

Then, the flow continues to `support/index.js`, which is where I try to read `baseUrl`:

```js
before(function disableABTesting() {
  const protocolRegex = new RegExp("^(http|https):\\/\\/")
  const domain = Cypress.config().baseUrl.replace(protocolRegex, "") // <== baseUrl was empty
  cy.setCookie("experiments", "false", { domain })
  cy.getCookie("experiments").should("have.property", "value", "false")
})
```

I noticed this because when running the `env=stg` the config.json loaded had a `baseUrl` without a trailing `/` and it worked fine, but `env=dev` had a `/` and it failed that line above.

**Comment by Vitaliy007** [comment] 2020-02-19 11:18
Any updates with this issue?

**Comment by jennifer-shehane** [comment] 2020-02-19 16:54
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-19 16:54 UTC

**Comment by Vitaliy007** [comment] 2020-02-20 08:16
The issue is when you add a base URL 
`{
	"baseUrl": "http://zero.webappsecurity.com/index.html"
}`
And used
 `cy.visit('/')`
I get next error:
![image](https://user-images.githubusercontent.com/9662035/74913710-dd9ff100-53c9-11ea-9f04-5e0225508ce1.png)
Please let me not if you need more info

**Comment by tenjojeremy** [comment] 2020-06-11 01:33
Hi @jennifer-shehane is possible to prevent  the extra '/' from being added at the end of the URL ?

**Comment by jennifer-shehane** [comment] 2020-07-02 09:08
@Vitaliy007 The baseUrl should not include file extensions like `.html`, It is a **base** url, not meant to be a single fully qualified URL. This would mean you can only visit that single `.html` page when the intention is to route to several urls off of a base. 

@tenjojeremy I'm not aware of a way to ignore this.

**Comment by tenjojeremy** [comment] 2020-07-02 10:31
@jennifer-shehane I used an environment variable instead. Thank you.

**Comment by alex700** [comment] 2020-07-07 22:31
I had the same issue when used `@vue/cli-plugin-e2e-cypress` plugin. I removed it to use `cypress` instead. It works well now.
