### ISSUE TITLE
Overwriting as command breaks alias shared context with this.*

### ISSUE THREAD

**Issue by onomatopoetry** [cypress-io/cypress#7666] opened 2020-06-10 18:57 UTC
### Current behavior:

Overwriting the `as` command prevents aliases of basic objects and primitives from being accessed via the shared context (`this.*`).

### Desired behavior:

Aliasing basic objects and primitives with `as` should continue to work if `as` is overwritten.

### Test code to reproduce

I've performed a very simple overwrite of the `as` command so that I can pass alias names in with a leading '@'. This is done so that I can store constants for alias names in external files, and then assign _and_ read aliases using the same constant. Here's the overwrite:
```js
Cypress.Commands.overwrite('as', (originalFn, subject, name) => {
	const alias = `${name}`.replace(/^@/, '');

	subject.alias = alias;

	return originalFn(subject, alias);
});
```
I've realized that after I implemented the overwrite, using `this.*` to reference aliases no longer works. For example, this simple test:
```js
beforeEach(() => {
    cy.wrap({greeting: 'hello world'}).as('helloWorld');
 });
it.only('tests accessing aliases with this.*', function() {
    expect(this.helloWorld.greeting).to.equal('hello world');
 });
```
fails with "Cannot read property 'greeting' of undefined".

### Versions

Cypress v 4.6.0
Windows 10
Chrome 83

**Comment by jennifer-shehane** [comment] 2020-12-09 07:02
Duplicate of https://github.com/cypress-io/cypress/issues/5101

**Closed by jennifer-shehane** 2020-12-09 07:02 UTC
Labels: type: unexpected behavior
