### ISSUE TITLE
AUT navigates to Cypress runner upon page navigation.

### ISSUE THREAD

**Issue by csalazar1** [cypress-io/cypress#7545] opened 2020-05-30 23:05 UTC
**Use Cypress version 4.5.0 to reproduce. Later versions are currently blocked by**(https://github.com/cypress-io/cypress/issues/7518)

This simple tests consists of:
- Logging in
- Visiting specific page with a form
- Filing out required fields and submitting

Upon submission of the form, a page redirect happens and a series of uncaught errors fire. However, when the form is cancelled, the page redirect still happens, but without the errors.

Here's the code for both scenarios. The one where the error happens by submitting the form, and the one where everything is ok when canceling the form

```js
it('Example With Errors',() => {
    cy.request('POST', '/Auth/Login', { username: 'cydemoadmin', password: 'Test1@#$%' })
    cy.visit('/#/Settings/business-units/Add')
    cy.get('[type=submit]').should('be.visible')

    cy.get('[name=Name]').type('TestBU8') //Change value after one use. You can just increase number
    cy.get('[name=OfficialName]').type('TestBU8') //Change value after one use. You can just increase number
    cy.get('[name=Email]').type('asdf2sdfsdf@ggmaill.com')
    cy.get('[name=PhoneNumber]').type('8185556767')
    cy.get('[type=submit]').click()
  })

  it('Example Without Errors',() => {
    cy.request('POST', '/Auth/Login', { username: 'cydemoadmin', password: 'Test1@#$%' })
    cy.visit('/#/Settings/business-units/Add')
    cy.get('[type=submit]').should('be.visible')
    cy.get('.btn-link.muted').click()
  })
```

Here's the stack trace
<img width="1895" alt="exception" src="https://user-images.githubusercontent.com/32462093/83340617-46331f80-a28f-11ea-87ee-fcea62a2b378.png">
<img width="1889" alt="noException" src="https://user-images.githubusercontent.com/32462093/83340620-492e1000-a28f-11ea-9606-9ff116a90377.png">

There seems to be a weird URL mutation happening for the scenario where the exceptions happen

**Comment by jennifer-shehane** [comment] 2020-06-01 11:38
I can't recreate the issue as described. I don't see the uncaught errors or the AUT window traversing into Cypress as shown in the first screenshot. 

Please make sure to include all code required. It looks like you have some `after` code running in your test suite - this may be important to recreate. 

<img width="1619" alt="Screen Shot 2020-06-01 at 6 07 21 PM" src="https://user-images.githubusercontent.com/1271364/83405569-c34aca00-a432-11ea-90a8-7aebeda7181c.png">

Regardless this looks similar to the issue we have a potential fix available for  starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments). Can you try setting this config option in your `cypress.json` or elsewhere as soon as you are able to upgrade:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by csalazar1** [comment] 2020-06-01 14:29
@jennifer-shehane There's no `after` You actually need to run only the it() with the error. If you run both it()'s it'll move on the second test before the first one has finished loading the page and therefore the errors.

Nevertheless, I tried `"experimentalSourceRewriting": true` on `4.7.0` and got a different error
<img width="1899" alt="2" src="https://user-images.githubusercontent.com/32462093/83418962-34f62a00-a3d9-11ea-9c95-4b63f6f265c9.png">
<img width="844" alt="1" src="https://user-images.githubusercontent.com/32462093/83418966-37588400-a3d9-11ea-8d6c-a57dcc656600.png">

Just make sure to it.only() the `Example With Errors` test and change values of `TestBU{##}` to something random that hasn't been used. You should see the URL mutation happen in an `after()` even though there is none specified in the spec file

**Comment by jennifer-shehane** [comment] 2020-06-02 08:51
Ok, I missed the part about the repro requiring you change the `test` selector value. 

Yah, I see the `experimentalSourceRewriting` ends up having the test hang. 

### Repro

```

describe('tests', () => {
  it('test 1', () => {
    cy.request('POST', 'https://qa1-cypress.st.dev/Auth/Login', { username: 'cydemoadmin', password: 'Test1@#$%' })
    cy.visit('https://qa1-cypress.st.dev/#/Settings/business-units/Add')
    cy.get('[type=submit]', {timeout: 15000}).should('be.visible')
  
    cy.get('[name=Name]').type('test43824')
    cy.get('[name=OfficialName]').type('test43824')
    cy.get('[name=Email]').type('asdf2sdfsdf@ggmaill.com')
    cy.get('[name=PhoneNumber]').type('8185556767')
    cy.get('[type=submit]').click()
  })

  it('test 2', () => {
    cy.request('POST', 'https://qa1-cypress.st.dev/Auth/Login', { username: 'cydemoadmin', password: 'Test1@#$%' })
    cy.visit('https://qa1-cypress.st.dev/#/Settings/business-units/Add')
    cy.get('[type=submit]', { timeout: 15000 }).should('be.visible')

    cy.get('[name=Name]').type('test43825') //Changed value
    cy.get('[name=OfficialName]').type('test43825') //Changed value
    cy.get('[name=Email]').type('asdf2sdfsdf@ggmaill.com')
    cy.get('[name=PhoneNumber]').type('8185556767')
    cy.get('[type=submit]').click()
  })
})
```

**Comment by csalazar1** [comment] 2020-06-25 20:38
Update: as of 4.9.0, using 
`{
	"experimentalSourceRewriting": true
}`
Will give the following error
<img width="1905" alt="1" src="https://user-images.githubusercontent.com/32462093/85792826-f3f7e980-b6e8-11ea-9830-6e6b6a0c3cbe.png">

Without 
`{
	"experimentalSourceRewriting": true
}`

There's a new error that happens
<img width="1888" alt="2" src="https://user-images.githubusercontent.com/32462093/85792872-070ab980-b6e9-11ea-9784-04e69875f606.png">

Same steps to repro as above. Just make sure you it.only() the test with the steps leading the errors

**Comment by jennifer-shehane** [comment] 2022-04-08 19:01
This is no longer reproducible from the given repro. 

Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 19:01 UTC
Labels: type: bug, stage: needs investigating
