### ISSUE TITLE
Alias in hooks

### ISSUE THREAD

**Issue by prashantabellad** [cypress-io/cypress#5223] opened 2019-09-27 10:56 UTC
This is an issue

### Current behavior:
Consider below code where I am creating alias users in `before` hook.
```js
before(function () {
  // alias the users fixtures
  cy.fixture('users.json').as('users')
})
I am not able to access it in my test below
it('utilize users in some way', () => {
  // access the users property
  const user = this.users[0]
})

I am able to only access it when I change anonymous "()=> { " to "function()=>{"
it('utilize users in some way', function() => {
  // access the users property
  const user = this.users[0]
})
```

**Comment by ryan-snyder** [comment] 2019-09-27 12:37
This is how it's meant to work. Please read https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Avoiding-the-use-of-this for more info. You can open a feature request for this if you disagree

**Comment by jennifer-shehane** [comment] 2019-10-25 15:47
`before` code is only run once, and between the tests Cypress removes all of the aliases. So in subsequent tests it is not available.

Moving this code into a `beforeEach` will work.

Closing as duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2019-10-25 15:47 UTC
