### ISSUE TITLE
I accidentally closed the Command Log and now I have no idea how to reopen it. Help? 

### ISSUE THREAD

**Issue by Nagimagi** [cypress-io/cypress#4994] opened 2019-08-16 12:43 UTC
I accidentally closed the Command Log and now I have no idea how to reopen it. Help? 
@jennifer-shehane 
![image](https://user-images.githubusercontent.com/33744937/63168329-6c703180-c066-11e9-908e-1be7b4b1485a.png)

**Comment by Nagimagi** [comment] 2019-08-22 09:42
I have found the way by myself and that is >
1. To remove the whole "Cypress" document that you unzipped
2. To remove the whole "cypress" document that was created under the App Data document when you unzipped and initialised the Cypress app from Cypress.zip

I don't have any other clue other than this one, a rather aggressive way. But anyhow it sovled the problem at the time.

**Comment by jennifer-shehane** [comment] 2019-08-23 21:14
Duplicate of https://github.com/cypress-io/cypress/issues/2132 Would love a PR to fix that.

**Closed by jennifer-shehane** 2019-08-23 21:14 UTC

**Comment by brian-mann** [comment] 2019-08-23 22:37
You can also run `cypress cache clear` from the CLI and it'll do this under the hood.

**Comment by Nagimagi** [comment] 2019-08-26 02:08
@brian-mann cypress command doesn't work on me. I can't npm install cypress on a windows Ubuntu subsystem. have tried multiple times....
