### ISSUE TITLE
'CypressError: Timed out retrying: cy.click() failed because this element is not visible:' though it definitely is and works on previous of a sequence of pages

### ISSUE THREAD

**Issue by gerib** [cypress-io/cypress#4897] opened 2019-08-01 12:03 UTC
I'm here since the page linked at the bottom of the error message mentions:
> There have been situations where Cypress does not correctly allow you to interact with an element that should be interactable. If that’s the case, Open an issue.

### Current behavior:

The button that causes the error is to proceed to a multi-page form's next page.

> CypressError: Timed out retrying: cy.click() failed because this element is not visible:
>
> &lt;button onclick="WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;Xml$noel_ehberechnung$Steps$Seitenfolge$ctl00$next$input&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))" data-bind="click: function(data, event){return submitbutton.forceButtonClickBehavior(event);}" name="Xml$noel_ehberechnung$Steps$Seitenfolge$ctl00$next$input" value="Weiter" type="submit" id="Xml_noel_ehberechnung_Steps_Seitenfolge_ctl00_next_input" class="stg-submit btn stg-defaultbutton stg-btn-weiter btn-primary stg-form-type-button">...&lt;/button>
>
> This element &'lt;button#Xml_noel_ehberechnung_Steps_Seitenfolge_ctl00_next_input.stg-submit.btn.stg-defaultbutton.stg-btn-weiter.btn-primary.stg-form-type-button>' is not visible because it has an effective width and height of: '0 x 0' pixels.
>
> Fix this problem, or use {force: true} to disable error checking.
>
> https://on.cypress.io/element-cannot-be-interacted-with

If I use `{force: true}` tests don't fail but do not proceed to the next page either.

### Desired behavior:

Buttons with the same `id` work on previous pages. If I click on them in Cypress manually I can proceed to the next page as desired.

### Steps to reproduce: (app code and test code)

Cannot publish app code. It's an internal ASP.NET form generator including forms with mutiple pages. The only thing I can do is manipulating the DOM created by it in the browser.

The current version of the form (without my pending enhancements) can be tested at: https://wfgtest.noel.gv.at/formularserver/user/formular.aspx?path=(public)&pid=73e1ad84447b4a8783cede5121b4c125&pn=B0e49a0fe2fb541a9addb63108663c3cd

It's proceeding from page 2 to page 3 that doesn't work in the test script. 

#### Test code

(see line comments for where it fails and where it does nothing)
````js
// type definitions for Cypress object "cy"
/// <reference types="cypress" />

describe("EH-Berechnung", function() {
	
	let weiter = '#Xml_noel_ehberechnung_Steps_Seitenfolge_ctl00_next_input'

	// Seite Wohneinheiten
	
	let size1 = '#Xml_noel_ehberechnung_Steps_Seitenfolge_Inner_SeiteWohneinheiten_GruppeWE1_GroesseWE1_input'
	let size2 = '#Xml_noel_ehberechnung_Steps_Seitenfolge_Inner_SeiteWohneinheiten_GruppeWE2_GroesseWE2_input'
	let av = '#Xml_noel_ehberechnung_Steps_Seitenfolge_Inner_SeiteWohneinheiten_GruppeAVVerhaeltnis_AVVerhaeltnis_input'
	
	it("Wohneinheiten - Ohne Eingabe weiter", function() {
		cy.viewport(1000, 1000)
		cy.visit("http://10..../formularserver/user/formular.aspx?path=(entw)&pid=pfad1&pn=B0e49a0fe2fb541a9addb63108663c3cd")
		cy.get(weiter).click()
		cy.get('.stg-error-mark').should('have.length', 4)
		})
	
	function WohneinheitenMitEingabeWeiter() {
		cy.viewport(1000, 1000)
		cy.visit("http://10..../formularserver/user/formular.aspx?path=(entw)&pid=pfad1&pn=B0e49a0fe2fb541a9addb63108663c3cd")
		cy.get(size1).then(e => { e.val("99,99")} )
		cy.get(size2).then(e => { e.val("99,99")} )
		cy.get(av).then(e => { e.val("0,99")} )
		cy.get(weiter).click()
	  }

	it("Wohneinheiten - Mit Eingabe weiter", function() {
		WohneinheitenMitEingabeWeiter()
		})
  
	// Seite Fördermodell
	
	let model = "#Xml_noel_ehberechnung_Steps_Seitenfolge_Inner_SeiteFoerdermodell_GruppeFoerdermodell_Foerdermodell_input"
	
	it("Fördermodell - Ohne Auswahl weiter", function() {
		WohneinheitenMitEingabeWeiter()
		cy.viewport(1000, 2000)
		cy.get(weiter).click()
		cy.get('.stg-error-mark').should('have.length', 2)
		})

	function FoerdermodellPassivWeiter() {
		WohneinheitenMitEingabeWeiter()
		cy.viewport(1000, 2000)
		cy.get(model).select('1')
		// Re {force: true} see https://on.cypress.io/element-cannot-be-interacted-with
		cy.get(weiter).click(/*{force: true}*/)  // Fails here
		}

	it("Fördermodell - Mit 'Passiv' weiter", function() {
		FoerdermodellPassivWeiter()
		})

	function Foerdermode100PunkteWeiter() {
		WohneinheitenMitEingabeWeiter()
		cy.get(model).select('2')
		// Re {force: true} see https://on.cypress.io/element-cannot-be-interacted-with
		cy.get(weiter).click({force: true})  // does not fail but doesn't go to the next page either
		}

	it("Fördermodell - Mit '100-Punkte' weiter", function() {
		Foerdermode100PunkteWeiter()
		})

	function FoerdermodeNiedrigWeiter() {
		WohneinheitenMitEingabeWeiter()
		cy.get(model).select('3')
		// Re {force: true} see https://on.cypress.io/element-cannot-be-interacted-with
		cy.get(weiter).click({force: true})  // does not fail but doesn't go to the next page either
		}

	it("Fördermodell - Mit 'Niedrig' weiter", function() {
		FoerdermodeNiedrigWeiter()
		})

	function FoerdermodeNiedrigstWeiter() {
		WohneinheitenMitEingabeWeiter()
		cy.get(model).select('4')
		// Re {force: true} see https://on.cypress.io/element-cannot-be-interacted-with
		cy.get(weiter).click({force: true})  // does not fail but doesn't go to the next page either
		}

	it("Fördermodell - Mit 'Niedrigst' weiter", function() {
		FoerdermodeNiedrigstWeiter()
		})

	})
````
P.S.: Supplementary question: This is my first Cypress script. There might be a better way to test page sequences apart from `function` chaining. Is there?

### Versions

- Where can I find Cypress' version? There is no _Help_ → _About_. However, I downloaded it yesterday so it must be the latest.
- Windows 10 Enterprise,
- FF 68.0.1

**Comment by Guttz** [comment] 2020-09-30 13:37
I have a similar problem using AWS Amplify UI Components. They use shadow DOM and I've followed the intructions on manipulating Shadow DOM on the Docs but somehow cypress states that the input element is still not visible: 

```
Timed out retrying: cy.type() failed because this element is not visible:

<input id="username" type="text" placeholder="Enter your username" class="input" data-test="sign-in-username-input">

This element <input#username.input> is not visible because it has an effective width and height of: 0 x 0 pixels.

```

**Comment by sainthkh** [comment] 2020-12-29 07:20
Close this issue because it's old and the example provided is not reproducible. If the problem is still happening in the current Cypress version, please open a new issue with a reproducible example.

**Closed by sainthkh** 2020-12-29 07:20 UTC
