### ISSUE TITLE
cy.origin doesn't allow to visit local files

### ISSUE THREAD

**Issue by Jacek-fstack** [cypress-io/cypress#26670] opened 2023-05-04 15:18 UTC
### Current behavior

Currently I can't change origin to a local file, because of the error:
```
cy.origin() failed to create a spec bridge to communicate with the specified origin. This can happen when you attempt to create a spec bridge to an insecure (http) frame from a secure (https) frame.
```

### Desired behavior

it should just let me visit the new origin without complaining about http/https thing.

### Test code to reproduce

```
[my test goes here[
 cy.writeFile(fileUrl, '<h1>Hello</h1>');
    cy.origin('./embeddedFormFile.html', () => {
      cy.visit('/');
    });
```

### Cypress Version

12.11

### Node version

latest

### Operating System

macos

**Comment by nagash77** [comment] 2023-05-04 19:51
Hi @Jacek-fstack , `cy.origin` is meant to assist in interacting with pages and elements that are on a different domain.  What are you trying to accomplish?  If you suspect there is a bug with cy.origin please provide a reproducible example.

Issues in the github repo are reserved for bugs and feature requests.  Question should be posted in [Cypress Discord](https://discord.gg/cypress)

**Comment by Jacek-fstack** [comment] 2023-05-05 06:37
@nagash77  my app under test returns a code, that creates a form; I need to test that form, but I cannot paste it anywhere, because I don't have a repo access to the app under test. The only way is to paste the code to a file locally and see if that opens.
But I cannot do that with cy.origin for whatever reason. Looks like a bug, since cy.origin was made to not care about previous origin, right?

**Comment by Jacek-fstack** [comment] 2023-05-08 08:47
What should I do here?

**Comment by nagash77** [comment] 2023-05-08 18:16
The url argument specifies the secondary origin in which the callback is to be executed. This should at the very least contain a hostname, and may also include the protocol, port number & path.  That does not include local files such as you have listed.  You could try hosting the file in a webserver and navigating to it.

I am going to close this issue since this is not a supported use case as described.  I would again suggest you check out the discord server.

**Closed as not planned by nagash77** 2023-05-08 18:16 UTC
