### ISSUE TITLE
Cypress Test Runner > select multiple tests to run

### ISSUE THREAD

**Issue by jakub-bao** [cypress-io/cypress#7178] opened 2020-04-29 17:01 UTC
Hi I love Cypress,
Using for about 1 year now daily.
This is one thing I've been missing for a while

### Current behavior:

I mostly run my tests using Cypress Test Runner (`cypress open`).
And the test runner offers me two options:

- run all tests
- run single test

### Desired behavior:

It would be awesome if we could also select multiple tests OR at least a directory.

![image](https://user-images.githubusercontent.com/47790868/80624301-76ca3400-8a19-11ea-960c-d236797ce8fb.png)

### Versions
4.4.0, 4.5.0

**Comment by jennifer-shehane** [comment] 2020-04-30 10:16
Duplicate of #3607

**Closed by jennifer-shehane** 2020-04-30 10:16 UTC
