### ISSUE TITLE
CypressError: `cy.task()` must only be invoked from the spec file or support file is still in the latest update 12.16.0

### ISSUE THREAD

**Issue by TarlanZiyadovAdway** [cypress-io/cypress#27218] opened 2023-07-06 09:11 UTC
### Current behavior

CypressError: `cy.task()` must only be invoked from the spec file or support file. Getting this error after updating to 12.16.0 

### Test code to reproduce

cy.task() in e2e.js file from after hook not working due to this error. In previous releases cy.task() worked as expected from e2e.js file

### Cypress Version

12.16.0

### Node version

16.17.0

### Operating System

linux

**Comment by chrisbreiding** [comment] 2023-07-06 13:20
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/27200.

**Closed as not planned** 2023-07-06 13:20 UTC
Labels: type: duplicate
