### ISSUE TITLE
Test execution in Windows results in additional trailing backslash added to the URL

### ISSUE THREAD

**Issue by RobDBob** [cypress-io/cypress#5750] opened 2019-11-20 10:48 UTC
With base url as follows:
"baseUrl": "https://some.tested.webpage.com",

And cy.visit instruction parameter:
'/lower48/production'

### Current behavior:
On Windows 10 OS, URL used by the test is is supplemented with a backslash. 
From log:
VISIT /lower48/production\
![image](https://user-images.githubusercontent.com/6172430/69231864-cca0d300-0b81-11ea-9360-a26c8efd8ae3.png)

This causes webpage not to load i.e. 403 forbidden / access denied.

### Desired behavior:
Accessed webpage is navigated to with use of the actual URL specified.
From log: 
VISIT /lower48/production

![image](https://user-images.githubusercontent.com/6172430/69231810-b2ff8b80-0b81-11ea-8284-a76e55622ff2.png)

### Versions
Issue reproducible on Windows 10 (cypress started with yarn test:open)
Browsers: Chrome 78 and Electron 73
Cypress 3.6.1

**Comment by jennifer-shehane** [comment] 2020-01-02 18:45
This is strange. We haven't seen this issue before or reproduced this, so I am wondering if it has to do with windows because of the backslash.

**Comment by jennifer-shehane** [comment] 2020-10-20 08:30
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-10-20 08:30 UTC
Labels: OS: windows, stage: needs information
