### ISSUE TITLE
Cypress is sometimes blank

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress#5940] opened 2019-12-12 14:49 UTC
### Current behavior:

Sometimes the Chrome 80 that Cypress starts hangs at some point and becomes blank:

![2019-12-12-154230](https://user-images.githubusercontent.com/217543/70721563-151d5d80-1cf6-11ea-8a99-58b10db3f11a.png)

I can *not* reproduce with Chromium 78.

### Desired behavior:

There is always some content in the window.

### Versions

- Cypress : 3.7.0
- System : Fedora 31

**Comment by jennifer-shehane** [comment] 2019-12-13 11:17
Unfortunately we/ll have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Can you please comment in this issue with a reproducible example. 🙏

**Comment by DamienCassou** [comment] 2019-12-13 13:12
Jennifer Shehane <notifications@github.com> writes:
> Unfortunately we/ll have to close this issue as there is not enough
> information to reproduce the problem. This does not mean that your
> issue is not happening - it just means that we do not have a path to
> move forward.  Can you please comment in this issue with a
> reproducible example. 🙏

no I can't and I understand your decision. But now you know that it
happened to at least one user :-).

Thank you so much for Cypress, it's awesome!

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by seyfer** [comment] 2019-12-16 14:13
I have the same issue now.

**Comment by DamienCassou** [comment] 2019-12-23 16:22
I seems that I don't face the same problem when using Electron instead of Chrome/Chromium.

**Comment by lephuongbg** [comment] 2020-01-15 05:11
Same issue with chrome 80. Using chrome 78 for now. (Didn't try chrome 79).

**Comment by jennifer-shehane** [comment] 2020-10-20 08:44
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-10-20 08:44 UTC
Labels: stage: needs information
