### ISSUE TITLE
Cypress 10.0.2 closes itself after 2-3 seconds with errno 2147483651

### ISSUE THREAD

**Issue by Ahmar8228** [cypress-io/cypress#22123] opened 2022-06-06 12:56 UTC
### Current behavior

On running command `npx cypress open`
Cypress runner opens up for 2-3 seconds and then closes itself with following console output

OS: Windows 10 X64
Node.js: 12.13.0
npm: 6.12.0

**console output:**
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2147483651
npm ERR! tcp-qa-70@1.0.0 cy:o: `npx cypress open`
npm ERR! Exit status 2147483651
npm ERR!
npm ERR! Failed at the tcp-qa-70@1.0.0 cy:o script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
### Desired behavior

Runner should not close on its own.

### Test code to reproduce

install cypress 10.0.2
run cypress with command `npx cypress run`

### Cypress Version

10.0.2

### Other

**debug.log file output:**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cy:o'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'precy:o', 'cy:o', 'postcy:o' ]
5 info lifecycle tcp-qa-70@1.0.0~precy:o: tcp-qa-70@1.0.0
6 info lifecycle tcp-qa-70@1.0.0~cy:o: tcp-qa-70@1.0.0
7 verbose lifecycle tcp-qa-70@1.0.0~cy:o: unsafe-perm in lifecycle true
8 verbose lifecycle tcp-qa-70@1.0.0~cy:o: PATH: C:\Users\Owner\AppData\Roaming\nvm\v12.13.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\core-v7-work\tcp-qa-v7\V7.23.1\node_modules\.bin;C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot\bin;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;D:\Work\tcp-we-thirdparty\Nant\0.92\bin;D:\Tools\cygwin\bin;C:\Program Files\Java\jdk1.8.0_311\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\k6\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Users\Owner\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\Owner\AppData\Local\Microsoft\WindowsApps;C:\Users\Owner\.dotnet\tools;C:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\Owner\AppData\Roaming\npm;C:\Users\Owner\AppData\Local\GitHubDesktop\bin;C:\Users\Owner\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle tcp-qa-70@1.0.0~cy:o: CWD: D:\core-v7-work\tcp-qa-v7\V7.23.1
10 silly lifecycle tcp-qa-70@1.0.0~cy:o: Args: [ '/d /s /c', 'npx cypress open' ]
11 silly lifecycle tcp-qa-70@1.0.0~cy:o: Returned: code: 2147483651  signal: null
12 info lifecycle tcp-qa-70@1.0.0~cy:o: Failed to exec cy:o script
13 verbose stack Error: tcp-qa-70@1.0.0 cy:o: `npx cypress open`
13 verbose stack Exit status 2147483651
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Owner\AppData\Roaming\nvm\v12.13.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Owner\AppData\Roaming\nvm\v12.13.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid tcp-qa-70@1.0.0
15 verbose cwd D:\core-v7-work\tcp-qa-v7\V7.23.1
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cy:o"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 2147483651
22 error tcp-qa-70@1.0.0 cy:o: `npx cypress open`
22 error Exit status 2147483651
23 error Failed at the tcp-qa-70@1.0.0 cy:o script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2147483651, true ]
```

**Comment by mkashiftcp** [comment] 2022-06-06 14:16
I'm facing the same issue on Node version 16.15.0

**Comment by teareed88** [comment] 2022-06-06 21:31
I'm facing the same issue on Node version 16.15.1

**Comment by flotwig** [comment] 2022-06-07 15:38
Closing as duplicate of #22064

**Closed by flotwig** 2022-06-07 15:38 UTC
Labels: stage: investigating
