### ISSUE TITLE
browser minimal resolution check failure

### ISSUE THREAD

**Issue by todzheng** [cypress-io/cypress#6049] opened 2019-12-26 14:32 UTC
Browser minimal resolution check failure due to screen resolution of 1280x720, while minimal resolution required is 1024x768

set viewportWidth = 1280, viewportHeight=900

run cypress --run, for a site with browser minimal resolution check, not respecting viewport values

### Versions

MacOS High Serriera, Chrome 78.0, Cypress 3.8.0

**Comment by todzheng** [comment] 2019-12-27 14:09
[](url)

**Comment by todzheng** [comment] 2019-12-27 14:28
the viewport is correctly set to the value specified, however, the error is complaining about screen resolution is 1280x720, which is lower than 1024x768 required. This is not a problem when running interactively, but it is a problem when running headlessly

**Comment by jennifer-shehane** [comment] 2019-12-30 08:51
@todzheng Please provide the exact test code to run recreate this problem. Copy/paste the specfile and any configuration. Thanks.

**Comment by AshMcConnell** [comment] 2020-04-10 14:52
We are noticing this too.  We have some fields with ellipses which display fine at 1920x1080, but are cut off in a smaller resolution.  

The tests pass every time in headed mode, but fail in headless `cypress run` mode.

Our cypress file looks like this: - 

`{
    "viewportWidth": 1920,
    "viewportHeight": 1080,
    "defaultCommandTimeout": 20000,
    "requestTimeout": 40000,
    "numTestsKeptInMemory": 5,
    "ignoreTestFiles": "{**/*.po.js,**/cypress.json,**/test-tools.js}",
    "reporter": "cypress-multi-reporters",
    "reporterOptions": {
        "configFile": "reporterOpts.json"
    }
}`

**Comment by jennifer-shehane** [comment] 2020-04-13 08:26
If you need a larger screensize than the 1280x720 default during headless (because there is no physical screen during headless), you'll need to pass the size specifically like shown in this comment: https://github.com/cypress-io/cypress/issues/6210#issuecomment-583269127

**Comment by AshMcConnell** [comment] 2020-04-21 06:28
Thanks @jennifer-shehane, sorry I missed this as I was off for Easter.  I'll give it a go today!

**Comment by jennifer-shehane** [comment] 2020-08-28 08:59
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-28 08:59 UTC
Labels: stage: needs information
