### ISSUE TITLE
Cypress should fire 'mouseenter' event on .click()

### ISSUE THREAD

**Issue by elmoknit** [cypress-io/cypress#4678] opened 2019-07-09 14:50 UTC
### Current behavior:

I have a custom dropdown with checkboxes. I'm using [vue-on-click-outside lib](https://www.npmjs.com/package/vue-on-click-outside). It's a directive vue.js. When I click outside of my dropdown it's close the dropdown. 

In real life, everything is successful. It's opening when I click on the DOM element and when I click outside, it's closing. 

But with Cypress, when I click the dropdown doesn't show. When I remove the directive, the click works. Obviously, I can't close it when I click outside without the directive.

_My component_

```html
<div class="checkbox-select" v-on-click-outside="closeDropdown">
    <div class="checkbox-select trigger" :class="{ isActive: dropdown }" @click="toggleDropdown" data-testid="displayDropdown">
      <slot v-if="!dropdown" name="label"></slot>
      <span v-show="dropdown" class="checkbox-select title" data-testid="titleOpenedDropdown">TITLE</span>
    </div>
[...]
  </div>
```

I'm using a custom command to get by the data accessor `"data-testid"`. I am using it everywhere, it's not the source of this problem.

```js
export const getByTestId = (id: string) => {
  return cy.get(`[data-testid=${id}]`);
};
```

_My cypress test_

```js
it("should open dropdown",()=>{
  cy.getByTestId("displayDropdown").should('be.visible').click()
    .getByTestId("titleOpenedDropdown").should("be.visible");
});
```

_The result_

<img width="635" alt="Screen Shot 2019-07-09 at 10 12 28" src="https://user-images.githubusercontent.com/43608750/60895130-15d73280-a232-11e9-99ee-937702197221.png">

### Desired behavior:

I want to be able to use the [vue-on-click-outside lib](https://www.npmjs.com/package/vue-on-click-outside) and make my cypress tests work when I click.

### Steps to reproduce: (app code and test code)

On a vue.js project

1- `npm install vue-on-click-outside --save`
2- Add it on something you can toggle open/close

```html
<template>
  <div class="checkbox-select" v-on-click-outside="closeDropdown">
    <div class="checkbox-select trigger" :class="{ isActive: dropdown }" @click="toggleDropdown" data-testid="displayDropdown">
      <slot v-if="!dropdown" name="label"></slot>
      <span v-show="dropdown" class="checkbox-select title" data-testid="titleOpenedDropdown">TITLE</span>
    </div>

    <div id="dropdown" class="checkbox-select dropdown" v-show="dropdown">
      <ul id="customScroll" class="checkbox-select items-wrapp">
        <li v-for="(item, index) in items" :key="index">
          <div class="checkbox-select">
            {{ item }}
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
  import { mixin as onClickOutside } from 'vue-on-click-outside';

  export default {
    name: 'input-dropdownCheckboxes',
    mixins: [onClickOutside],
    props: {
      items: {
        type: Array,
        default: []
      }
    },
    data() {
      return {
        dropdown: false
      };
    },
    methods: {
      toggleDropdown() {
        this.dropdown = !this.dropdown;
      },
      closeDropdown() {
        if(this.dropdown) {
          this.dropdown = false;
        }
      }
    }
  };
</script>
```

3- Try to click on this element with cypress to open it.

```js
it("should open dropdown",()=>{
  cy.getByTestId("displayDropdown").should('be.visible').click()
    .getByTestId("titleOpenedDropdown").should("be.visible");
});
```

### Versions
Cypress 3.3.2
Chrome 75

**Comment by jennifer-shehane** [comment] 2019-07-10 05:15
Okie doke. I went through and create a standard hello-world app using [@vue-cli](https://cli.vuejs.org), installed Cypress 3.4.0 and `vue-on-click-outside`.

I added the template code into my `HelloWorld.vue` file and added an array of items into the default `default: ['foo', 'bar', 'baz']`. 

I don't see the dropdown rendering on my screen at all with the code you provided. I can see that all of it has `display: none` set. Maybe you forgot to include some css you have that is important to reproduce this?

<img width="1186" alt="Screen Shot 2019-07-10 at 11 43 19 AM" src="https://user-images.githubusercontent.com/1271364/60942309-278b0980-a308-11e9-8591-2d961a9d362a.png">


Please provide every piece of code needed so that I can get it running and reproducible. Ideally, provide a hello-world repo that you've completely tested against first to show that it's failing please. If we can't reproduce the issue, we will have to close the issue.

**Comment by elmoknit** [comment] 2019-07-10 12:23
Hello! 

I create a repository on my git hub : 

https://github.com/elmoknit/cypress-bug-vue-click-outside

Thanks and have a nice day!

**Comment by jennifer-shehane** [comment] 2019-07-10 14:39
Hey @elmoknit, I still don't see the checkbox code or test in this repo, is it on a separate branch? Did you commit all the changes?

**Comment by elmoknit** [comment] 2019-07-10 15:00
It was not necessary, so I didn't put it. The problem is only with the display of the dropdown. Content is not important.

**Comment by jennifer-shehane** [comment] 2019-07-11 06:43
Ok. Thanks. I'm able to reproduce this now with the code from this repo https://github.com/elmoknit/cypress-bug-vue-click-outside. 

Luckily `vue-on-click-outside` is nice enough to explain how their package works without me having to dig into code.

>vue-on-click-outside uses `mouseenter` and `mouseleave` events to determine if the user is still inside the element. This should account for content that is dynamically removed on `click` events and is the primary distinction to the existing vue-clickaway library. Once a user clicks on something the `click` event bubbles up the DOM tree until it reaches the `documentElement`. A `click` listener on the `documentElement` then looks for elements that were not targetted by the `click` event and calls the callback you provided via the directive.

vue-on-click-outside is expecting a `mouseenter` event to be called before the click, which is not fired from within Cypress currently. 

### Workaround:

You can get your test to simulate this and pass by writing:

```js
it("should open dropdown",()=>{
  // I removed the should be visible - we already check for visibility before clicking.
  cy.getByTestId("displayDropdown").trigger('mouseenter').click()
    .getByTestId("titleOpenedDropdown").should("be.visible");
});
```

We should fire the `mouseenter` event before some actions, like `.click()`. I will update the title of this issue to reflect this. cc @Bkucera

**Comment by sainthkh** [comment] 2020-08-05 03:54
It's working in 4.12.0. Close this issue.

If the problem still happens for some reason, please leave a comment.

**Closed by sainthkh** 2020-08-05 03:54 UTC
Labels: existing workaround, pkg/driver, stage: ready for work, topic: cy.click 🖱, topic: native events, type: bug
