### ISSUE TITLE
Cypress 13.5.1 Linux ARM64 gives version 'GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Younis-NAB** [cypress-io/cypress#28398] opened 2023-11-24 08:37 UTC
### Current behavior

When running in Cypress in ARM based machine using 13.5.1 fails with 
/lib64/libm.so.6: version 'GLIBC_2.29' not found.

When running the same test on x86 it doesn't present this error

### Test code to reproduce

None applicable

### Cypress Version

13.5.1

### Node version

v18.18.2

### Operating System

Linux RHEL 8 (ARM)

**Comment by jennifer-shehane** [comment] 2023-11-27 15:23
Duplicate of https://github.com/cypress-io/cypress/issues/28374

**Closed as completed by jennifer-shehane** 2023-11-27 15:23 UTC
