### ISSUE TITLE
After upgrading Docker image with chrome 107 tests started crashing

### ISSUE THREAD

**Issue by estrada9166** [cypress-io/cypress#24552] opened 2022-11-04 21:39 UTC
### Current behavior

I was trying to upgrade Node version to v16.18.0 using the docker image `cypress/browsers:node16.18.0-chrome107-ff106-edge` but, the tests started crashing with

```
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
```

After updating the code and removing some `beforeEach` it has improved, but randomly it fails, I have not been able to identify the reason of it.

When I was using chrome 99 it seems to work fine

### Test code to reproduce

- [Dashboard run](https://dashboard.cypress.io/projects/5b79905a-f894-4e91-b60c-fff4d94c218a/runs/68091/overview)

### Cypress Version

10.11.0

### Node version

v16.18.0

### Operating System

CircleCi

**Comment by BenShelton** [comment] 2022-11-16 14:13
We're seeing the same when upgrading from `cypress/browsers:node16.13.0-chrome95-ff94` to `cypress/browsers:node18.12.0-chrome106-ff106`.

Exact same tests as before are now failing with the same error as above. This is in GitLab CI.

**Comment by mschile** [comment] 2022-11-22 20:31
@BenShelton, could you try [`cypress/browsers:node18.12.0-chrome103-ff107`](https://hub.docker.com/layers/cypress/browsers/node18.12.0-chrome103-ff107/images/sha256-bac10e0650032de0b27a52a11cb1a21e7ba071f0b960766673e909cee2c0b377?context=explore) instead? I know there have been some chrome memory issues with v104+.

You could also try this [suggestion](https://github.com/cypress-io/cypress/issues/8525#issue-696149834) to force garbage collection to see if that helps.

**Comment by mschile** [comment] 2022-11-22 20:36
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/23391

**Closed as not planned by mschile** 2022-11-22 20:36 UTC
Labels: browser: chrome, type: performance 🏃‍♀️
