### ISSUE TITLE
click action triggers click event on parent element

### ISSUE THREAD

**Issue by hinfaits** [cypress-io/cypress#5529] opened 2019-10-30 00:07 UTC
### Current behavior:

In my test I do a `cy.contains('button', '<button-text>').click()` the the "click" event is being triggered on the parent of what I've selected. Most of the events are triggered on the element I've grabbed, except for "pointerup", "mouseup" and "click".

![image](https://user-images.githubusercontent.com/4756302/67818385-4572aa80-fa6e-11e9-997f-92b58619c17d.png)

### Desired behavior:

The "click" event should be triggered on the button element

### Versions

Cypress 3.5.0
Windows 10
Chrome 77

This did not occur on Cypress 3.3.2

**Comment by jennifer-shehane** [comment] 2019-10-30 21:27
Hi @hinfaits, we'll need a way to reproduce this ourselves - HTML and test code. We have several tests around this behavior - ensuring the events to sent to the correct element, so there is likely something unique to your situation that we have not considered. Thanks.

**Comment by hinfaits** [comment] 2019-11-01 16:46
Hi @jennifer-shehane,

Just want to check in. The changes in Cypress 3.6.0 did not fix my issue. I will try to get a reproducible example for the team.

**Comment by hinfaits** [comment] 2019-11-04 17:35
Hi @jennifer-shehane, I can't seem to determine what in our webapp is causing this behavior and so I'm unable to produce an example without forking over our entire application.

I quickly investigated this myself and it seems like more of a browser issue. `doc.elementFromPoint(x, y)` appears to be returning different elements for the same coordinate arguments. In `mouse.click()` the calls made to `doc.elementFromPoint(x, y)` from  `mouse.up` is what's returning the parent element.

I'm unsure how to proceed from here and we do have a workaround of using `cy.trigger('click')` instead of using `click()`. Another work around is also sending `cy.click()` twice as the second call executes as expected.

**Comment by tnrich** [comment] 2019-11-15 19:49
Hey @jennifer-shehane we're also seeing the same issue in our app where previously passing tests are now failing when making the jump (from 3.2.0 to 3.6.1 in our case but I believe it is 3.5.0 that introduced the new behavior)  

Here is what that looks like in our app: 

Instead of selecting the row of the datatable like it did pre 3.5.0, now the row no longer gets selected until we fire `.click()` a second time. Pausing before this point and clicking manually works perfectly. 

![image](https://user-images.githubusercontent.com/2730609/68970938-49583980-079d-11ea-8c7d-0395e7afaec7.png)

For some reason it seems like the rt-td, the "Actual Element Clicked" only gets some of the events: 

![image](https://user-images.githubusercontent.com/2730609/68970966-56752880-079d-11ea-9db6-ec5f8662cb69.png)

As you can see, for some reason the datatable container receives the "click" event, not the .rt-td element. 

This is definitely confusing behavior that would be good to get to the bottom of. I'm guessing other people are also seeing this happen as well if @hinfaits is too. 

I'll look into trying to reproduce this.. I'm not sure why this isn't working here.

**Comment by tnrich** [comment] 2019-11-15 19:54
@brian-mann do you see anything in this PR (https://github.com/cypress-io/cypress/pull/3030/files) of yours that you think might be causing the behavior described above? 

Thanks!

**Comment by belev** [comment] 2019-11-20 15:19
In our team we had the same issues with this behaviour. I don't see anything specific in our setup for the failing tests. Previously we were using version `3.4.1`, after updating to `3.6.1` the test started failing and the target element for the click event is not the correct one.

**Comment by coreylight** [comment] 2020-01-04 16:15
I also experienced this, with the current version of https://reacttraining.com/reach-ui/menu-button. For the second item in a MenuList, the click action in Cypress was getting applied to the parent. I suspect this lib does some funky things concerning tabindex and use of react portals, so it is possible it is solely on the lib for the source of issue. However, when I tried using `.click({force: true})` that seemed to work.

**Comment by sarahgaoyan** [comment] 2020-04-10 05:53
I am using cypress 3.8.0 and also experienced this issuer. Only the second click work as expected.
![image](https://user-images.githubusercontent.com/56947386/78966470-9369ff00-7b32-11ea-9d8c-2a1c6b20d653.png)

**Comment by jennifer-shehane** [comment] 2020-08-19 10:02
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-19 10:02 UTC
