### ISSUE TITLE
Unable lo Launch appliication. Getting 500 error code.

### ISSUE THREAD

**Issue by kumarshiva1** [cypress-io/cypress#6746] opened 2020-03-17 01:10 UTC
## Current behavior:

I am getting 500 error code while launching application using `cy.visit()` command. It happen with WebDriver IO as well but when i refresh the page with webdriver IO, it works. When i am refreshing the page using Cypress by using `cy.reload()`, command, it does not work. it gives the same 500 response code.

## Desired behavior:

Cypress should launch app using `cy.visit()` command.

Steps to Reproduce -

`cy.visit('app url')`, I can not share the url as it works within company network.
`cy.reload()`

I am doing `cy.reload()` as with selenium I need to refresh the page to launch the application. When I am doing the same with Cypress, I am still getting 500 error code.

Complete Error Message -

```
CypressError : cy.visit() failed trying to load;
The response received from your web server was:

500:Server Error
This was considered a failure because the status code was not '2XX'.
```

**Comment by jennifer-shehane** [comment] 2020-03-17 05:06
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Can you explain why your webpage initially gets a 500 response? (Is this expected behavior?) and what about your application is 'fixed' due to reloading the webpage exactly? That would probably hint at why this is working/not working.

Please comment in this issue with a reproducible example and answer to questions above and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-03-17 05:06 UTC

**Comment by jennifer-shehane** [comment] 2020-03-17 06:31
Duplicate of #6714 Do not open new issues that are already existing. Comment in the existing issue and we will reopen if necessary.
