### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by dustin-rcg** [cypress-io/cypress#16310] opened 2021-05-03 19:50 UTC
### Current behavior

When using the Okta login method given [in Cypress docs](https://docs.cypress.io/guides/testing-strategies/okta-authentication#Custom-Command-for-Okta-Authentication), I see the following error in the console:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3001') does not match the recipient window's origin ('http://localhost:49528').
onWindowLoadHandler @ authorize?client_id=<hidden>&code_challenge=3KwOJPf4bItZwGMJmDZKmSPPpv2VMgs6XYZP94x7ZWM&code_challenge_method=S256&nonce=L9EuCQI55v5BKTrD8IWrqWupuGd9AYkrdMwvwLoZ5asvZKgHRn8yJSI2hpAO9iRV&prompt=none&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Flogin&response_mode=okta_post_message&response_type=code&sessionToken=<hidden>&state=489BKJ0Aaq3462jkWTOySD8vKtWwtRgIuNAf7e0CIEG04NYZES7UClfKSChYYNRT&scope=openid email:39
```

### Desired behavior

The okta login should complete without errors, and the token data should be saved in localStorage.

### Test code to reproduce

```js
import { OktaAuth } from "@okta/okta-auth-js";

Cypress.Commands.add("loginOkta", () => {
  console.log("Running loginOkta...");
  cy.request({
    method: "POST",
    url: `https://${Cypress.env("okta_domain")}/api/v1/authn`,
    body: {
      username: Cypress.env("username"),
      password: Cypress.env("password"),
    },
  })
  .then(({ body }) => {
    console.log("BODY ->", body);
    const user = body._embedded.user;
    const config = {
      issuer: `https://${Cypress.env("okta_domain")}/oauth2/default`,
      clientId: Cypress.env("client_id"),
      redirectUri: Cypress.env("redirect_uri"),
      scope: ["openid", "email", "profile"],
    };

    const authClient = new OktaAuth(config);
    console.log("Created authClient");

    return authClient.token
      .getWithoutPrompt({ sessionToken: body.sessionToken })
      .then((value) => {
        console.log("VALUE ->", value);
        return value;
      })
      .then(({ tokens }) => {
        const userItem = {
          token: tokens.accessToken.value,
          user: {
            sub: user.id,
            email: user.profile.login,
            given_name: user.profile.firstName,
            family_name: user.profile.lastName,
            preferred_username: user.profile.login,
          },
        };

        window.localStorage.setItem("oktaCypress", JSON.stringify(userItem));

        log.snapshot("after");
        log.end();
      });
  });
});
```

When I run this I see the following output in the browser console:

```
Running loginOkta...
BODY -> Object
Created authClient
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3001') does not match the recipient window's origin ('http://localhost:49528').
```

So it appears to fail in the call to `getWithoutPrompt()`, since `VALUE ->` not printed to the console.

I also tried adding the Cypress config [mentioned here](https://github.com/cypress-io/cypress/issues/6429#issuecomment-587068894), but it made no difference.

### Versions

cypress 7.2.0
@okta/okta-auth-js 4.9.0

**Comment by adambulmer** [comment] 2021-05-25 13:10
Also seeing same issue with same reproduction steps.

**Comment by joydeep100** [comment] 2022-05-16 09:52
Facing the same issue. @jennifer-shehane

**Comment by humancore-olga** [comment] 2022-05-31 16:11
I am facing the same error.
Did someone have found a solution for this??

**Comment by humancore-felipe** [comment] 2022-05-31 16:12
We're facing the same error! We're doing exactly as the [Cypress Documentation](https://docs.cypress.io/guides/testing-strategies/okta-authentication#Setting-Okta-app-credentials-in-Cypress) says, but we're unable to get this working

**Comment by humancore-joe** [comment] 2022-06-21 14:58
hi! Bump! - Is there going to be a response to this?

**Comment by yulev5** [comment] 2022-06-26 12:03
Also here

**Comment by humancore-olga** [comment] 2022-07-28 13:59
Almost 2 months waiting for an answer on this subject and nothing yet... Is it going to be fixed at some point or just ignored?

**Comment by rachelruderman** [comment] 2022-08-19 17:22
Hi @dustin-rcg ! In this case we recommend using [cy.origin](https://docs.cypress.io/api/commands/origin), which was [released in Cypress 9.6.0](https://www.cypress.io/blog/2022/04/25/cypress-9-6-0-easily-test-multi-domain-workflows-with-cy-origin/). However if you're unable to upgrade to 9.6.0, you can use the [Okta hosted sign-in page](https://github.com/okta/okta-signin-widget#okta-hosted-sign-in-page-default) to bypass the cross-origin issue. Or, if you can use the Okta sign in widget, there's a nice blog post on how to get it working with Cypress tests: https://anshuman-bhardwaj.medium.com/perfect-guide-for-testing-login-using-okta-sso-with-cypress-2c82e841179d

**Comment by nagash77** [comment] 2022-08-30 18:23
@humancore-joe @humancore-olga @humancore-felipe Have you all tried the suggestions @rachelruderman listed above?

**Comment by emilyrohrbough** [comment] 2022-09-06 14:44
@humancore-joe @humancore-joe @humancore-felipe

Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide once you've tried out the new `cy.origin` command @rachelruderman suggested.

**Comment by ag-tvs** [comment] 2022-10-14 22:13
@nagash77 Just add `cy.visit(YOUR_WEBSITE);` on the beginning of the command, it will change Cypress url and it will be matched with the origin of your remote application

```
import { OktaAuth } from "@okta/okta-auth-js";

Cypress.Commands.add("loginOkta", () => {
   >>> cy.visit('http://localhost:3000'); <<<
   
   cy.request({
    method: "POST",
    url: `https://${Cypress.env("okta_domain")}/api/v1/authn`,
    body: {
      username: Cypress.env("username"),
      password: Cypress.env("password"),
    },
  })
  ...
```

More about it here
https://docs.cypress.io/guides/guides/web-security#Examples-of-what-Cypress-does-under-the-hood

**Comment by AtofStryker** [comment] 2022-10-21 21:11
@artem-gavrylenko-tvscientific I believe has hit the nail on the head here. 

Likely to avoid any issues with programmatic login, you should set your `baseUrl` to your expected application origin. @dustin-rcg your `cy.request` happens before your `baseUrl` is established via a `cy.visit`. Because of this, `postMessage` looks to fail from the API due to security reasons. Setting your base url to `http://localhost:3001` will set `window.top` for you to the correct domain without having to do a visit and should fix the error. To set `baseUrl` for your needs, please check out our docs on [setting environment variables](https://docs.cypress.io/guides/guides/environment-variables#Setting)!

This same issue came up in #23733, in which a reproduction repository was [provided](https://github.com/chrislacey89/cypressOktaBug). I have a pull request open to show how to fix this issue with `cy.request` I have discussed above, as well as how to log into okta using the `experimentalSessionAndOrigin` commands `cy.origin` and `cy.request`. Both work and can be used to whatever preference you have.

 Cheers and let us know if you have any issues moving forward!

Note: Also documented in https://github.com/cypress-io/cypress/issues/23733#issuecomment-1287438828

**Closed by AtofStryker** 2022-10-21 21:11 UTC
