### ISSUE TITLE
Clock() and tick() not fast forwarding time with async request

### ISSUE THREAD

**Issue by rebeccarothschild** [cypress-io/cypress#24227] opened 2022-10-12 16:53 UTC
### Current behavior

Hi there,

I'm E2E testing some application code that has a setTimeout call that delays a network request which then triggers a component to display. I'm trying to speed up time to skip the timeout but I haven't gotten it to work. I can see by logging in the console that time has been skipped but the async request is not being made until the original setTimout delay has passed.

Below is an example of what I'm trying to do.

spec.js:

```
describe(
  "Delay test",
  function() {
    it("Verify component visible", function() {
      cy.clock();
      cy.visit("/");
      cy.login(userName, password);
      cy.waitToCompleteLoading();
      cy.tick(600000);
      cy.verifyComponentPresent();
    });
  }
);
```

setTimeout call:

```
fetchObject() {
        const component = this;

        setTimeout(() => {
          // Delay fetch
          component.$store.dispatch(`/${GET_OBJECT}`); // async function
        }, 600000);
    }
```

### Desired behavior

I would expect the async call to be made and completed since the setTimout time should be overwritten.

### Test code to reproduce

Will provide if needed

### Cypress Version

10.3.0

### Node version

14.20.1

### Operating System

macOS 12.5

**Comment by warrensplayer** [comment] 2022-10-17 23:45
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by martinneumann** [comment] 2022-10-19 07:58
I have a similar issue and will try to reproduce it tonight. I will update this post and let you know.

**Comment by rebeccarothschild** [comment] 2022-10-20 00:32
I'm working on reproducing it as well.

**Comment by amehta265** [comment] 2022-10-27 17:09
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by amehta265** 2022-10-27 17:09 UTC
