### ISSUE TITLE
Getting unique validation error from cypress version 5.5.0,what ever the number we input the field validation saying number already exists

### ISSUE THREAD

**Issue by venkatkasturi** [cypress-io/cypress#14670] opened 2021-01-21 12:14 UTC
Getting unique validation error from cypress version 5.5.0, what ever the number we input the field validation saying number already exists, however no issues before cypress version 5.4.0, can anyone please help how to resolve the issue?

![image](https://user-images.githubusercontent.com/40849118/105349794-3ac2a900-5c10-11eb-9863-b327917ab1cb.png)

**Comment by bahmutov** [comment] 2021-01-21 12:24
Please provide fully reproducible example we can run. Also could you try the latest Cypress version?

**Comment by venkatkasturi** [comment] 2021-01-21 12:40
I have tried in all the Cypress versions 5.5.0, 5.6.0, 6.0.0, 6.0.1, 6.1.0, 6.2.0, 6.2.1, 6.3.0 - not working
Versions before 5.4.0, working fine

Due to confidentiality agreement of the project could not be able to share the code

Scenario is to check unique validation for Sales Order field 

 const todaysDate = Cypress.moment().format('MMDDYY')
  var x = 100;
  var rand = Math.floor(Math.random() * x) + 1; //Generate Random Number
cy.get("input[id*='input_orderNumber']").clear().type("SO"+todaysDate+rand)


Getting unique validation error message from cypress version 5.5.0, what ever the number we input the field validation saying number already exists, however no issues before cypress version 5.4.0

**Comment by bahmutov** [comment] 2021-01-21 12:58
Thanks for providing the spec code but we need to know your html markup and the code validating the input of any

**Comment by jennifer-shehane** [comment] 2021-01-21 15:52
The only thing in 5.5.0 that I see that could be relevant is this change for Cypress to support `beforeinput` events. https://github.com/cypress-io/cypress/pull/8411 Does the application code rely on `beforeinput` events? 

And as Gleb mentioned, we need the code or psuedo code around how the input verification works in order to track this down.

**Comment by venkatkasturi** [comment] 2021-01-21 18:22
Will take permissions from my Product Owner regarding the "html markup and the code snippet validating the input" and post it shortly..

**Comment by jennifer-shehane** [comment] 2021-06-15 15:43
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-06-15 15:43 UTC
Labels: stage: needs information
