### ISSUE TITLE
Cypress dashboard does not update status/duration of run when killed from CI / terminal

### ISSUE THREAD

**Issue by jjkavalam** [cypress-io/cypress#17098] opened 2021-06-24 09:43 UTC
### Current behavior

Given, a cypress run that got terminated (killed), the duration reported on the dashboard does not reflect the time the test suite was actually in execution. 

### Desired behavior

The dashboard should be aware that the test runner got killed and report the duration / status accordingly.

### Test code to reproduce

- Get hold of any cypress test suite
- Get hold of a cypress dashboard account
- Setup the test to report to the dashboard
- Run the test using `cypress run ...`
- Kill the test while it's in the middle of executing a test
- Check the dashboard for the duration / status of the test

The dashboard shows the test as still in progress; and the duration keeps increasing.

### Versions

Tested on 7.1.0

**Comment by jjkavalam** [comment] 2021-06-24 10:02
From my own experience, when working with a number of developers, this issue has the potential to create some confusion.

---
On a different note,

Is there a web API that can be used to notify dashboard that the test terminated ?

Perhaps a separate "monitor" process could be employed ... eager to hear ideas / solutions.

**Comment by jennifer-shehane** [comment] 2021-06-24 13:49
Currently when a run is cancelled from the CI or the terminal, Cypress does not detect this kill signal and it is not communicated to the Dashboard. So the Dashboard essentially receives no signal as to the progress of the test run. If the Dashboard receives no signal for 1.5 hours, then the run is killed on our side. 

I agree that this is not expected behavior and that the Dashboard should reflect any killed runs, so we'll keep this issue open to track this behavior.

**Comment by hjortskalbagge** [comment] 2021-09-23 15:18
Hi @jennifer-shehane , since this issue is ready for work for a while now, heavily related to https://github.com/cypress-io/cypress/issues/18168, and affecting us as well, could you give us an update on the current status on this topic? ;) 
Greetings!

**Comment by namoscato** [comment] 2023-03-28 19:08
@jennifer-shehane, any update on the prioritization of this behavior change?

**Comment by jennifer-shehane** [comment] 2023-10-11 19:44
Going to close this issue as a duplicate of https://github.com/cypress-io/cypress/issues/21125

**Closed by jennifer-shehane** 2023-10-11 19:44 UTC
Labels: type: unexpected behavior, stage: ready for work, Cypress Cloud
