### ISSUE TITLE
Cypress 9.2.1 + Node 17.1 (Win 11) Fails/Errors When Attempting Any Test

### ISSUE THREAD

**Issue by JamShady** [cypress-io/cypress#19712] opened 2022-01-14 21:33 UTC
### Current behavior

On a brand new, vanilla install, when attempting to run any test (in this case, one of the included spec files), Cypress opens the browser, and then immediately fails as follows:
![image](https://user-images.githubusercontent.com/167395/149586792-757020ac-af2f-463f-a87b-74a6fef305ae.png)

The error is: **Error: error:0308010C:digital envelope routines::unsupported**

Stack Trace:
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`D:\Web\basekit\cypress\plugins\index.js`)
    at Object.get (C:\Users\[user]\AppData\Local\Cypress\Cache\9.2.1\Cypress\resources\app\packages\server\lib\errors.js:1043:15)
    at EventEmitter.handleError (C:\Users\[user]\AppData\Local\Cypress\Cache\9.2.1\Cypress\resources\app\packages\server\lib\plugins\index.js:210:20)
    at EventEmitter.emit (node:events:394:28)
    at ChildProcess.<anonymous> (C:\Users\[user]\AppData\Local\Cypress\Cache\9.2.1\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (node:events:394:28)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

Setting `"nodeVersion": "bundled"` in the config resolves this error, but this wasn't required previously

### Desired behavior

The test should run

### Test code to reproduce

Vanilla fresh install and the bundled test specs

### Cypress Version

9.2.1

### Other

May be related to #18914 - that's where I got the 'fix' from

**Comment by GentlemanHal** [comment] 2022-01-15 20:54
I get the same error on MacOS 12.0.1 and Node 17.2.0. 
Cypress 9.2.0 works fine, so I've just switched back to that for now.

**Comment by emilyrohrbough** [comment] 2022-01-17 03:59
@JamShady / @GentlemanHal What node version are you using & what version of openSSL was the node version built with? Can you please share you OS, terminal and details on how you are running cypress & any logs? Looking for details to reproduce the issue.

This [change was released in 9.2.1](https://github.com/cypress-io/cypress/pull/19522) to try and fix some issue observed with Cypress &  Node 17....

**Comment by Krisell** [comment] 2022-01-17 07:37
I'm facing the same problem with macOS 12.1, Cypress 9.2.1 and OpenSSL `3.0.0+quic`. It can easily be resolved with `NODE_OPTIONS=--openssl-legacy-provider`.

Regarding the fix mentioned above, is that only for new project in some starter code? I have an existing project, updated to Cypress 9.2.1, and I don't see that code anywhere. Searching for `openssl-legacy-provider` in `node_modules/cypress` gives no hits.

**Comment by GentlemanHal** [comment] 2022-01-17 15:12
- macOS 12.0.1
- Node 17.2.0 (installed via `nvm`)
- GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)

> what version of openSSL was the node version built with?

I wasn't sure how to do this, searching I found this command `node -e "console.log(process.versions)" | grep openssl` and that returns:
- 3.0.0+quic

I got the error in an open source project I work so you can see all the files and how it is run at https://github.com/build-canaries/nevergreen

This is the log I get when running Cypress 9.2.1:
```
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`false`)

 Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-loader/dist/index.js:58:5)
    at successLoader (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-loader/dist/index.js:23:5)
    at LOADER_EXECUTION (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/cm/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
```

**Comment by emilyrohrbough** [comment] 2022-01-18 17:42
> Regarding the fix mentioned above, is that only for new project in some starter code? 

This change should be applied when Cypress starts the plugin process. This change won't be found in `node_modules/cypress` because the `cypress` npm module only included the CLI. It will install the Cypress binary onto your machine. Running `cypress verify` will show the install location of the binary.

**Comment by Krisell** [comment] 2022-01-18 17:48
> > Regarding the fix mentioned above, is that only for new project in some starter code?
> 
> This change should be applied when Cypress starts the plugin process. This change won't be found in `node_modules/cypress` because the `cypress` npm module only included the CLI. It will install the Cypress binary onto your machine. Running `cypress verify` will show the install location of the binary.

Thanks for the additional information! I realised that was probably the case, and with your help I could locate the code referenced above. Then my question/problem remains, I still have to add the `NODE_OPTIONS` manually, even though ny node version is `>= 17.0.0` and the OpenSSL version does not begin with `1.`.

**Comment by emilyrohrbough** [comment] 2022-01-18 19:31
@Krisell Are you able to check if the `--openssl-legacy-provider` flag is being applied from with the node options passed to the child process from within the binary? Seems like it should be based on the information you've provided.

**Comment by Krisell** [comment] 2022-01-18 20:04
If I run `npx cypress run` on `9.2.1` i get the familiar error ` Error: error:0308010C:digital envelope routines::unsupported`. However if I manually run it as `NODE_OPTIONS=--openssl-legacy-provider npx cypress run`, it all works.

By adding some logging in the Cypress code I was able to see that `process.versions.openssl` does return `1.1.1` when cypress is running, however the same code in a plain JS file returns `3.0.0+quic`. The node versions are the same in both cases.

<img src="https://user-images.githubusercontent.com/25909128/150009971-59ca68de-228f-4ba7-9f5e-978552c7c08e.png" width="300px">

What could cause this discrepancy? If this is likely to be a setup issue on my device, you don't have to spend more time debugging this.

**Comment by Oaky78** [comment] 2022-01-19 00:20
I had the same problem. You have to install latest stable Node version 16.13.2. Then it works. 
`nvm install --lts`

**Comment by sodatea** [comment] 2022-01-19 08:33
It fails in my GitHub Actions, too: https://github.com/vuejs/create-vue/runs/4864811524?check_suite_focus=true#step:8:73
Node.js 17, Ubuntu latest, Cypress 9.3.1

**Comment by JamShady** [comment] 2022-01-19 20:15
> @JamShady / @GentlemanHal What node version are you using & what version of openSSL was the node version built with? Can you please share you OS, terminal and details on how you are running cypress & any logs? Looking for details to reproduce the issue.

OS: Windows 11
Node 17.1.0
Terminal: PowerShell 7.2.1

Opening Cypress by `npx cypress open` in the project directory

Just upgraded to Cypress 9.3.1 and Node 17.4, the problem remains. I don't know about the OpenSSL version, I downloaded the Windows 64bit portable (.zip) from here: https://nodejs.org/en/download/current/

**Comment by fugazi** [comment] 2022-01-24 22:33
Any news to this issue? It continues broking my tests.

**Closed** 2022-01-31 18:03 UTC
Labels: stage: needs review
