### ISSUE TITLE
Add a way to stub the dependency

### ISSUE THREAD

**Issue by asekularaclf** [cypress-io/cypress#27164] opened 2023-06-29 12:43 UTC
### What would you like?

It's a pain not to be able to mock/stub the dependency/node module when writing Cypress component tests.

### Why is this needed?

Because a test software like Cypress should have a feature like this.

**Comment by mike-plummer** [comment] 2023-06-29 13:17
Hi @asekularaclf - in order to properly respond to your request we need more information. Stubbing and Spying in component tests can be done using the [`cy.stub`](https://docs.cypress.io/api/commands/stub) and [`cy.spy`](https://docs.cypress.io/api/commands/spy) commands, however these have limitations depending on how your application is designed.

If your application is using a legacy module format like CommonJS and you are unable to use `cy.stub`/`cy.spy` then you may have identified a bug in which case we'll need a reproducible example and [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) to help you troubleshoot.

If your project is using [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) then these APIs are unable to work as expected due to by-design limitations in ESM. There has been a lot of conversation in [this ticket](https://github.com/cypress-io/cypress/issues/22355) which provides context and potential workarounds.

If your application is using ESM *and* you're using [Vite](https://vitejs.dev/) for bundling we have an [experimental Vite plugin](https://www.npmjs.com/package/@cypress/vite-plugin-cypress-esm) you can apply to try to work around some of the limitations of ESM. It is still in an alpha stage so it will likely require a few tweaks to get it working in your baseline but has been used successfully on several projects thus far.

Please let me know which of these scenarios is applicable to you so we can handle this ticket accordingly.

**Comment by lmiller1990** [comment] 2023-07-06 01:36
Needs more info - Cypress `stub` and `spy` are only going to work for frontend modules, since our code runs in the browser and does not have access to the Node.js context, except via `cy.task`.

If you've got a specific example you can share, I can help make recommendations. Right now there isn't enough info to action, so I'll close this. Happy to reopen with additional info.

**Closed as completed by lmiller1990** 2023-07-06 01:36 UTC
