### ISSUE TITLE
before() and after() hooks are not executed if the first or the last test is skipped with it.skip()

### ISSUE THREAD

**Issue by alekseyrozh** [cypress-io/cypress#17717] opened 2021-08-12 17:24 UTC
### Current behavior

If I have a test suite with the first test marked with `it.skip()` the `before()` hook is not executed regardless of the number of tests present in a suite.
Similarly, If I have a test suite with the end test marked with `it.skip()` the `after()` hook is not executed regardless of the number of tests present in a suite.

So if I have a test suite with both `before()` and `after()` hooks and with 2 tests only one of which is marked as `it.skip()` I can't get both `before()` and `after()` to execute regardless of how I position the tests inside the suite.

### Desired behavior

`before()` and `after()` hooks are always run if present as long as you have at least one active (not `it.skip()`) test in a suite.

The same logic applies to `describe` blocks instead of suites.

### Test code to reproduce

Example 1:
```
describe('test-suite-with-hooks', (): void => {
    before((): void => {
      cy.log('beforeHook');
    });

    after((): void => {
      cy.log('afterHook');
    });

    it.skip('test1', (): void => {
       cy.log('test1');
       // this test causes before() hook to not execute
    });

    it('test2', (): void => {
       cy.log('test2');
    });
})
```

Example 2:
```
describe('test-suite-with-hooks', (): void => {
    before((): void => {
      cy.log('beforeHook');
    });

    after((): void => {
      cy.log('afterHook');
    });

    it('test1', (): void => {
       cy.log('test1');
    });

    it.skip('test2', (): void => {
       cy.log('test2');
       // this test causes after() hook to not execute
    });
})
```

### Cypress Version

4.12.1

### Other

Please provide the information if this was fixed in any of the versions of Cypress

**Comment by Narretz** [comment] 2021-08-13 15:40
Are you sure the `before` function is not run, or just not logged?

I tested this in 8.2.0, and when the first test is skipped, the log from `before` is not shown, however the before block is definitely executed (just add a console.log('before'))

**Comment by sainthkh** [comment] 2021-08-31 07:01
I tested it with the code below and learned that `after`, `before` are run correctly, but they aren't logged:

```js
describe('test-suite-with-hooks', () => {
  before(() => {
    console.log('before')
  })

  after(() => {
    console.log('after')
  })

  it('test1', () => {
    console.log('test1')
  })

  it.skip('test2', () => {
    console.log('test2')
  })
})
```

Maybe we should show the `after all` `before all` message to resolve confusion.

**Comment by jennifer-shehane** [comment] 2021-09-01 19:40
Duplicate of https://github.com/cypress-io/cypress/issues/1846

**Closed by jennifer-shehane** 2021-09-01 19:40 UTC
Labels: pkg/runner, stage: ready for work
