### ISSUE TITLE
Option to disable video processing on passing tests

### ISSUE THREAD

**Issue by mattvb91** [cypress-io/cypress#2426] opened 2018-09-03 07:22 UTC
### Current behavior:

Currently videos are processed for all tests regardless if they have passed/failed. This consumes quite a bit of our current runners cpu and in our case we create an artifact on gitlab if the pipeline has failed. This ends up being around 200mb videos when we only need the 1 failed which can often be < 5mb.

### Desired behavior:

Add a new config flag such as `processVideoOnPassingTest: false` to possibly discard the whole video therefore preventing the processing stage from happening or delete the video file after the test has passed if there is no way to circumvent the processing stage.

If someone can give a pointer to where the processing happens I would be happy to take a look and issue an associated pull request.

**Comment by jennifer-shehane** [comment] 2018-09-10 09:55
Duplicate of #2217  See comment for existing option: https://github.com/cypress-io/cypress/issues/2217#issuecomment-410386771

**Closed by jennifer-shehane** 2018-09-10 09:55 UTC
Labels: type: duplicate

**Comment by mattvb91** [comment] 2018-09-10 15:58
@jennifer-shehane that doesnt really related to this. Even when using the option you linked it will still process that video and put it into the /videos folder unless im understanding it wrong? 

For example currently what happens is: 5 tests pass 1 test fails. 
Results in 6 videos in the /videos folder.

This issue wants to only have 1 video in the /videos folder. (The fail)

**Comment by jennifer-shehane** [comment] 2018-10-20 20:16
Yes, you're correct, setting the `videoUploadOnPasses: false` WILL skip the processing and uploading stage and save you some time, but the video file would still be available locally. 

You could delete the video within your `videos` folder using the [Module API](https://on.cypress.io/module-api#Example) so that after the spec completes running, you could trash the asset yourself
