### ISSUE TITLE
http2 requests to server fallbacking to http1

### ISSUE THREAD

**Issue by midan888** [cypress-io/cypress#15740] opened 2021-04-01 11:21 UTC
I am using http2 requests in our project!

Trouble is that in cypress when starting chrome all requests two server become http1.
But if I start in regular chrome on host machine its http2.
Because of that we get a lot of stalled requests. Our project uses grpc over http2.
Need help!

**Comment by jennifer-shehane** [comment] 2021-04-01 17:23
Duplicate of https://github.com/cypress-io/cypress/issues/3708

**Closed by jennifer-shehane** 2021-04-01 17:23 UTC

**Comment by loumacdev** [comment] 2021-07-22 07:27
> Duplicate of #3708

why have both these issues been closed as duplicates when the issue has not been resolved - is anyone actively looking at this issue with server reverting to http1? many people are using grpc http2 - which would unfortunately make cypress an unacceptable choice

**Comment by gajus** [comment] 2022-06-14 19:15
This could be solved with https://github.com/cypress-io/cypress/issues/22319

**Comment by MolochKel** [comment] 2022-09-06 13:25
@jennifer-shehane Any update on either of the referenced issues?
