### ISSUE TITLE
Return conditional data based an XHR's request details

### ISSUE THREAD

**Issue by sarahgracesmith** [cypress-io/cypress#180] opened 2016-06-30 17:24 UTC
Often a server will respond conditionally to a request based on information in the POST data. Would be helpful to be able to do this using cy.route() - currently if a function is passed in it is called immediately, not at the point of requesting.

**Comment by bahmutov** [comment] 2018-01-19 20:42
@sarahgracesmith can you give me a little code snippet of what you would like to see ideally here?

**Comment by sarahgracesmith** [comment] 2018-01-22 20:43
for example, the following `commentsResponse` would check the request variables and dynamically return different results. Similar to how a server might behave. This would allow returning different results for the same route in a single test even if there's no logical point to re-`route` in the test. 
```
const commentsResponse = (routeData) => {
  //routeData is a reference to the current route's information
  if ( ... request contains some field ... )
    return {
      data: foo
    }
  } else {
    return {
      data: bar
    }
  }
}

cy.route('POST', '/comments/**', commentsResponse)
```

**Comment by bahmutov** [comment] 2018-01-22 21:27
👍 I have this test passing
```js
it('returns data based on response', () => {
    let req
    cy
      .route({
        url: '/users?_limit=3',
        response: r => {
          req = r
          return [1, 2, 3]
        },
        headers: {
          'access-control-allow-origin': '*'
        }
      })
      .as('users')
    cy.visit('has-fetch.html')
    cy.wait('@users').then(() => {
      expect(req).to.deep.equal({
        method: 'GET',
        url: '/users?_limit=3'
      })
    })
  })
```
which confirms the right logic

**Comment by jennifer-shehane** [comment] 2019-05-30 06:59
Closing as duplicate of https://github.com/cypress-io/cypress/issues/521

**Closed by jennifer-shehane** 2019-05-30 06:59 UTC
Labels: stage: ready for work, type: feature
