### ISSUE TITLE
Stub removed automatically when trying to stub window.open

### ISSUE THREAD

**Issue by ErenPhayte** [cypress-io/cypress#3732] opened 2019-03-18 07:15 UTC
Hi,

So I found a possible bug where stubs seem to disappear(???). I have created the following method:

```js
Cypress.on('window:after:load', (win) => {

    cy.stub(win, 'open')
        .as('openAuthWindow')
        .callsFake(function (url, target, features, replace) {
            // so fake work here ..
        })
})
```
in the description block I have the following:

> I only want to run this once and not after every test since the tests are interlinked

```js
before(() => {
        cy.visit('/')
})
```

The actual tests at this stage are simple as I cant get further:

```js
it('Sign in with Spotify', () => {
            cy.get('#step-one button').contains('Spotify').click()
            cy.get('@openAuthWindow').should('be.calledWith', '/spotify/login')
})

it('Sign in with Soundcloud', () => {
            cy.get('#step-one button').contains('Soundcloud').click()
            cy.get('@openAuthWindow').should('be.calledWith', '/soundcloud/login')
})
```

What happens is the first tests works perfectly. `Window.open` is hijacked and I can do perform fake actions to mimic the flow. However the second one fails as it seems `window.open` has reverted back to the original function.

I have tried implementing this with `beforeEach` and also tried putting it into a `onBeforeLoad` with the `cy.visit` but with no success.

**Comment by ErenPhayte** [comment] 2019-03-19 09:27
I finally found a solution that kinds does what it needs to, would have been better just to set this once and not for each test by using `before` but here is the code snippet anyways:
```
beforeEach(function () {
        cy.window().then(win => {
            cy.stub(window, 'open')
                .as('openAuthWindow')
                .callsFake(function (url, target, features, replace) {
                    //do some magic faking here
                })
        })
    })
```

**Comment by jennifer-shehane** [comment] 2019-03-19 12:32
This appears to be a duplicate of this issue: https://github.com/cypress-io/cypress/issues/583

We clear the stub in between tests. We want to implement better control over this behavior though. Let me know if I've misunderstood.

**Closed by jennifer-shehane** 2019-03-19 12:32 UTC

**Comment by ErenPhayte** [comment] 2019-03-19 13:20
Yeah #583 is spot on what is happening.

**Comment by zaren-s** [comment] 2023-05-11 17:04
On cypress 10, I am having a similar issue, where I open one url, hijack `open` to prevent url from opening in another window, then `cy.go('back')` and click on another link. Even though it is in the same test and not in before, the stub still gets reset and the second link opens up in another tab.

**Comment by nagash77** [comment] 2023-05-12 13:05
@zaren-s please open a new issue with a reproducible example and the Cypress team will be happy to investigate.
