### ISSUE TITLE
The Chromium Renderer process just crashed - 'sad face' Error

### ISSUE THREAD

**Issue by JimLynchCodes** [cypress-io/cypress#7204] opened 2020-05-02 04:36 UTC
Hi, I am running m cypress script in headless mode on a remote ubuntu 18.03 machine. The strange thing is that it works fine on my local macbook, but I'm getting an error that the Chromium renderer is crashing when running on the ubuntu server. Here is the output:

```
We detected that the Chromium Renderer process just crashed.
[1] 
[1] This is the equivalent to seeing the 'sad face' when Chrome dies.
[1] 
[1] This can happen for a number of different reasons:
[1] 
[1] - You wrote an endless loop and you must fix your own code
[1] - There is a memory leak in Cypress (unlikely but possible)
[1] - You are running Docker (there is an easy fix for this: see link below)
[1] - You are running lots of tests on a memory intense application
[1] - You are running in a memory starved VM environment
[1] - There are problems with your GPU / GPU drivers
[1] - There are browser bugs in Chromium
[1] 
[1] You can learn more including how to fix Docker here:
[1] 
[1] https://on.cypress.io/renderer-process-crashed
[1] TypeError: onError is not a function
[1]     at BrowserWindow.onCrashed (/home/ubuntu/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/modes/run.js:538:7)
[1]     at WebContents.<anonymous> (/home/ubuntu/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/gui/windows.js:181:34)
[1]     at WebContents.emit (events.js:215:7)
[1] 
[1] TypeError: onError is not a function
[1]     at BrowserWindow.onCrashed (/home/ubuntu/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/modes/run.js:538:7)
[1]     at WebContents.<anonymous> (/home/ubuntu/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/gui/windows.js:181:34)
[1]     at WebContents.emit (events.js:215:7)
[1] 
[1] The Test Runner unexpectedly exited via a exit event with signal SIGILL
[1] 
[1] Please search Cypress documentation for possible solutions:
[1] 
[1] https://on.cypress.io
[1] 
[1] Check if there is a GitHub issue describing this crash:
[1] 
[1] https://github.com/cypress-io/cypress/issues
[1] 
[1] Consider opening a new issue.
[1] 
[1] ----------
[1] 
[1] Platform: linux (Ubuntu Linux - 18.04)
[1] Cypress Version: 4.4.0
```

Is there any way for me to see why it is crashing? 🤔

**Comment by JimLynchCodes** [comment] 2020-05-02 16:14
hmm it seems that there is some memory leak with Cypress. After running it locally and using Activity Monitor to profile the "Google Chrome Helper (Renderer)" process I can see that it starts at about 400mb memory and slowly climbs up to 4gb as the test runs... 🤔

**Comment by JimLynchCodes** [comment] 2020-05-02 16:23
I added the profiling environment variable `DEBUG=cypress:server:util:process_profiler cypress run`, but I'm still not really sure what's causing the issue.

My output looks like this image below. It seems that with every print the first like, "Electron", is taking more and more memory usage. Everything else seems to be pretty stable. 

![Screen Shot 2020-05-02 at 12 20 19 PM](https://user-images.githubusercontent.com/5354163/80869662-b5f1c280-8c6f-11ea-80b4-ee93e3520ce2.png)

**Comment by zac11** [comment] 2020-05-02 23:35
I am facing the same issue when trying to run Cypress on local Jenkins. See this [Issue-7200](https://github.com/cypress-io/cypress/issues/7200)

**Comment by JimLynchCodes** [comment] 2020-05-03 03:24
hmm... how are you getting the exact memory usage displayed when it crashes? that's pretty cool. haha

I am running it on a 1gb digital ocean linux server, but still I wouldn't expect it to just continually increase in memory. 

@zac11 are you switching pages a lot? I am ,and it seems like every time I switch pages memory goes up like 150mb. I am also creating big objects on each page (but I was hoping they would be freed once the leaving the page).

**Comment by jennifer-shehane** [comment] 2020-05-04 06:10
The CPU usage is based on a number of things. The Cypress app itself is running, Chromium is running and the application under test is running. If you're doing very memory intensive things within testing the app, then yes, this will require more CPU on the machine to handle. If it's maxing out, we recommend increasing the machine resources.

**Comment by JimLynchCodes** [comment] 2020-05-04 15:29
Thanks @jennifer-shehane, but I don't think I am doing very memory-intensive things.

I am going to a few different pages (and on each pages I would think the memory for the previous pages could be freed, which it seems that it is not).

I am building up an object of data, but after every 4 pages I reassign that object to `{}`. I was thinking that would allow the memory it was taking up to be freed, but it seems not. 

The memory never goes down at all-just continually goes up. 🤔

**Comment by zac11** [comment] 2020-05-07 11:23
@JimLynchCodes Did you try the same tests in Chrome headless? 

I disabled the shm usage as per the suggestion from @jennifer-shehane here [#7200 ](https://github.com/cypress-io/cypress/issues/7200#issuecomment-623275364) and even then Electron would crash and the Chromium renderer error would be thrown.

I changed the run command to have `--headless --browser chrome` and now the tests are running fine. Can you check if your tests fail on Chrome too?

**Comment by zac11** [comment] 2020-05-07 11:24
Also how did you do [this](https://github.com/cypress-io/cypress/issues/7204#issuecomment-622978707). I want to have a comparison between Electron and Chrome to see the difference

**Comment by JimLynchCodes** [comment] 2020-05-07 17:10
@zac11 hmm I did not disable shm usage... I will try that. Btw does anyone know what "shm" stands for? lol

In node you can set arbitrary PATH variables before you execute the script / command. It seems like "cypress:server:util:process_profiler" is some special value for the DEBUG variable that cypress looks for.

So if you normally run `cypress run` then you can run it with the extra profiling output like this:
```
DEBUG=cypress:server:util:process_profiler cypress run
```

**Comment by probil** [comment] 2020-07-07 16:37
I have the same issue while running cypress in headless mode in Gitlab CI. We have only 5 tests

Version 4.4.1 - works fine
Version 4.5+ - crashes almost every time 

We are using docker image provided by cypress: `cypress/base:12.18.0` which should be fine but for some reason it started to fail.

For now we stick to version 4.4.1 as it seems to be stable enough. We are considering firefox as it tend to use less memory but we haven't gave it a shot just yet

**Comment by probil** [comment] 2020-07-09 07:26
We setup a custom gitlab runner as described here
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2168#note_190617588
It works fine now

**Comment by jennifer-shehane** [comment] 2020-07-09 09:15
Unfortunately we'll have to close this issue if there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

There's a lot of things that could contribute to the browser crashing, including issues from the underlying application under test that don't have to do with Cypress. Please comment in this issue with a reproducible example so we can assess that this is an issue specific to Cypress.

**Comment by JimLynchCodes** [comment] 2020-10-03 18:17
Sorry I haven't commented on this in a while.

To be fair I was trying to run this on the 1GB cheapest digital ocean server. 😅

Currently I have it running via travisCI which is free since the code is on a public repo (those boxes seem to be ~7gb, and the tests finish successfully after about 4 minutes).

I am doing some relatively intense stuff (like scraping a bunch of text from the page, storing it in a giant object, and running a little backend server on the side which saves the object to a db...)

It would be really interesting though to get some kind of memory profile (over time?) that shows how much mem is being consumed by cypress and by each of these other things. 🤔

**Comment by CoryDanielson** [comment] 2020-10-14 21:02
I had a similar issue to what you're describing, and I was able to resolve it by exposing the garbage collector and running it between tests.

See https://github.com/cypress-io/cypress/issues/8525 and https://github.com/cypress-io/cypress/issues/350#issuecomment-688969443

Garbage collection is an expensive operation. Javascript's automatic garbage collector will try to stay out of your way, and only run when there is downtime in the code. The issue with this is that even very basic Cypress tests are quite intensive programs that do not have much downtime. When one test finishes, another test runs and so on until there are no tests remaining. The garbage collector will sometimes step in to free up memory, but not often enough to prevent out of memory crashes.

When testing a complex page with lots of requests and events, this issue becomes more noticeable. As Electron/Chrome approaches their max MB threshold (2GB by default), the JS runtime does not seem to get more aggressive with garbage collection. In my case, I saw 1.8GB used, and no decrease -- the next test to kick off would put it over 2GB and the app would crash.

**Comment by jennifer-shehane** [comment] 2020-10-20 11:00
@JimLynchCodes You can log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

**Comment by jennifer-shehane** [comment] 2020-10-20 11:05
Closing as resolved. Running Cypress does require some resources, so running it on an underpowered machine can cause Chrome to crash, especially when testing pages with lots of requests and DOM interactions.

@CoryDanielson We'll have to take a look at the window.gc() suggections.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-10-20 11:05 UTC
Labels: stage: needs information

**Comment by trainoasis** [comment] 2021-03-18 11:53
This fixed it for me: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2168#note_190617588

**Comment by garyburgmann** [comment] 2021-03-31 05:29
a combination of:

using image:
```yaml
image: cypress/browsers:node14.16.0-chrome89-ff86
```

adding `--disable-dev-shm-usage``` for chrome:
```javascript
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  // ignore examples/
  config.ignoreTestFiles = "**/examples/*.spec.js";

  // https://github.com/cypress-io/cypress/issues/349
  // add --disable-dev-shm-usage chrome flag
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.family === 'chromium') {
      console.log('Adding Chrome flag: --disable-dev-shm-usage');
      launchOptions.args.push('--disable-dev-shm-usage');
    }
    return launchOptions;
  });

  return config;
}
```

and explicitly running as chrome:
```sh
$ npx cypress run --browser chrome
```

made this work for me
