### ISSUE TITLE
Test fails between query and click.

### ISSUE THREAD

**Issue by aleksey-ilin** [cypress-io/cypress#21506] opened 2022-05-15 14:49 UTC
### Current behavior

Hi.
I have side panel and I want to test that it close by click on cross button. There is a request when side panel open. Between open side panel and getting response side panel contain skeleton. When response have received skeleton changes to text.
I wrote a test for it, but it is a flake test. Sometimes it fails with error "Timed out retrying after 4050ms: cy.click() failed because this element is detached from the DOM."
I found that cypress finds button, then side panel re-renders and then cypress clicks on button, but button is deatached the DOM. This happens on CI and I was able to repeat local only with network throttling.
I use intercept for mock request. I tried to use route, test did not fail.
Why is this happening?

### Desired behavior

I expect intercept will work like a route and wait re-render content.

### Test code to reproduce

describe('side panel ( intercept)', () => {
    it('should close sidepanel by click on close button (intercept)', () => {
        cy.intercept('/proxy/international-multistep-api/transfer/requirements', getTransferRequirements200).as('getTransferRequirements');

        cy.visit('http://localhost:9090/dashboard/');
        cy.window().then((win) => {
            const openSidePanel = cy.spy(win, 'openSidePanel');

            cy.wrap({ openSidePanel }).invoke('openSidePanel', 'SwiftTransferRequirements').then(() => {
                cy.wait('@getTransferRequirements');
                cy.findByTestId('side-panel-header-close-service-button-root').debug().click();
                cy.findByTestId('Slide').should('not.exist');
            });
        });
    });
});

describe('side panel (route)', () => {
    it('should close sidepanel by click on close button (route)', () => {
        cy.server();
        cy.route('/proxy/international-multistep-api/transfer/requirements', getTransferRequirements200).as('getTransferRequirements');

        cy.visit('http://localhost:9090/dashboard/');
        cy.window().then((win) => {
            const openSidePanel = cy.spy(win, 'openSidePanel');

            cy.wrap({ openSidePanel }).invoke('openSidePanel', 'SwiftTransferRequirements').then(() => {
                cy.wait('@getTransferRequirements');
                cy.findByTestId('side-panel-header-close-service-button-root').debug().click();
                cy.findByTestId('Slide').should('not.exist');
            });
        });
    });
});

### Cypress Version

7.5.0

### Other

![newclick-host-ui 2022-05-15 17-48-16](https://user-images.githubusercontent.com/32348899/168478921-c9081f1c-3037-4e52-ad36-b07d853ea8d5.png)
![newclick-host-ui 2022-05-15 17-47-37](https://user-images.githubusercontent.com/32348899/168478874-21fdfe20-85bb-46e9-b7b3-d2ccc25a6adb.png)

Link to video
https://drive.google.com/drive/folders/1y9k8jBH-bdJ80-p3-qoIsXsAwN7tnVxQ?usp=sharing

**Comment by wojciech-sygier** [comment] 2022-05-16 06:09
Welcome to our world. You've just discovered what we've been trying to have fixed for quite some time now. https://github.com/cypress-io/cypress/issues/7306

**Comment by BlueWinds** [comment] 2022-05-16 21:02
@aleksey-ilin - Yeah, unfortunately looks like a duplicate of that issues @wojciech-sygier linked, which is a longstanding Cypress issue with no clear solution. That issue contains some workarounds and other advice you might want to try. I'm going to close this as duplicate of #7306.

I can say that we're (finally) prioritizing that in the coming months - looking into detached DOM issue and figuring out how to fix it (this will probably involve adjusting how Cypress queues and retries commands, not a straightforward thing) is #1 on my priority list of the upcoming quarter.

**Closed by BlueWinds** 2022-05-16 21:02 UTC
Labels: stage: investigating
