### ISSUE TITLE
Infinite runtime with afterEach and retries enabled

### ISSUE THREAD

**Issue by qlimlass** [cypress-io/cypress#18502] opened 2021-10-14 22:48 UTC
### Current behavior

[My ticket on cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/628#issuecomment-943656687)

Semi-reproducible behavior: With retries enabled and anything in afterEach on a test, if that test fails, then the test will run infinitely on the retry attempt whether the second attempt fails or succeeds.

The behavior on my project: I've got timeouts set to 60 seconds and if I have a bad network request hanging longer than that, then it will produce this infinite run on the retry. I'm only able to reproduce it consistently on a handful of websites with `"pageLoadTimeout": 1000`. The behavior is the same though.

<img width="996" alt="Screen Shot 2021-10-14 at 4 26 52 PM" src="https://user-images.githubusercontent.com/81179661/137405366-0be04b8f-23bf-44ae-a127-9a280a86b931.png">

### Desired behavior

I am trying to use `cypress-cucumber-preprocessor` which runs with logic in afterEach. I currently can't put these cucumber tests into CI because of the risk of running jobs infinitely. Desired behavior is that the tests fail or succeed on retry attempts and the test concludes, which is what happens if I remove the afterEach block from the test code below.

Any suggestions for workarounds?

### Test code to reproduce

Infinite.js
```js
describe('Infinite', function () {
    afterEach(() => {
        cy.then(() => {});
    });
    it('Infinite', function () {
        cy.visit('https://www.starwars.com/');
    });
});
```

cypress.json
```json
{
	"retries": 2,
    "pageLoadTimeout": 1000
}
```

### Cypress Version

8.6.0

**Comment by adrienjoly** [comment] 2021-12-11 16:50
I have the same problem with Cypress 8.6.0 and 9.1.1, since I enabled `retries`!

You can find public run logs on https://github.com/openwhyd/openwhyd/runs/4493699111?check_suite_focus=true

Below, you'll see (based on timestamps) that tests should have timed out!

![image](https://user-images.githubusercontent.com/531781/145684780-ba71f524-7749-436d-903f-79274a2df1ec.png)

**Comment by Regaddi** [comment] 2022-05-13 07:41
This issue is currently blocking us from utilizing `retries`. When we hit this issue, our GitHub Action runner keeps running for hours, unless we notice it's hanging, causing unnecessary usage of our Actions quota. Disabling `retries` has the side effect that some tests fail randomly due to overall network or infrastructure flakiness, forcing us to re-run the whole test suite again (which again causes unnecessary usage of our Actions and Cypress Dashboard quota).

**Comment by flotwig** [comment] 2022-08-22 20:12
Agreed that this seems like an issue. Closing this as duplicate of #21619 since that has more information in the thread.

**Closed by flotwig** 2022-08-22 20:12 UTC
Labels: type: bug, topic: test retries ♻️
