### ISSUE TITLE
cypress run hangs when adding .skip() to two or more it blocks in the same spec

### ISSUE THREAD

**Issue by mynormh** [cypress-io/cypress#23244] opened 2022-08-10 15:35 UTC
### Current behavior

If I add `.skip()` to two or more `it()` blocks in the same spec file, cypress run just hangs and never makes it past that spec

![Screen Shot 2022-08-10 at 9 32 12 AM](https://user-images.githubusercontent.com/2418695/183945759-55323ff8-da61-450b-a48b-82fa6211d563.png)
![Screen Shot 2022-08-10 at 9 33 15 AM](https://user-images.githubusercontent.com/2418695/183945764-7715d06e-2ee1-425a-9222-920c75cbbbaa.png)

If I move the second `it.skip()` block to another file it all works, they are both skipped and it moves onto the other spec files.

### Desired behavior

Cypress should be able to finish `cypress run` when adding `.skip()` to two or more `it` blocks in the same spec file

### Test code to reproduce

```
describe('Skip tests', () => {
  it.skip('first test', () => {
    cy.visit('/');
  });

  it.skip('second test', () => {
    cy.visit('/');
  });
});
```

Run `cypress run` and it will hang 

### Cypress Version

9.7.0

**Comment by AtofStryker** [comment] 2022-08-10 21:34
Hey @mynormh. Thank you for opening an issue. I created a quick [reproduction repository](https://github.com/AtofStryker/cypress-issue-23244) with Cypress 10 and wasn't able to recreate the issue. Are you able to clone and verify the results?

**Comment by mynormh** [comment] 2022-08-10 21:59
@AtofStryker thanks for looking into this so quickly, you are correct not able to reproduce on Cypress 10. Guess we need to update from v9.

**Comment by AtofStryker** [comment] 2022-08-11 14:25
> @AtofStryker thanks for looking into this so quickly, you are correct not able to reproduce on Cypress 10. Guess we need to update from v9.

Of course! Glad to help. I am going to close this out as it seems to be resolved, but if it continues to be a problem in v10 let us know!

**Closed by AtofStryker** 2022-08-11 14:25 UTC
Labels: stage: investigating, v9.7.0 :bug:
