### ISSUE TITLE
dashboard setup doesn't write projectId to custom cypress config file

### ISSUE THREAD

**Issue by alvaromartmart** [cypress-io/cypress#8933] opened 2020-10-22 14:20 UTC
### Current behavior

When setting up the dashboard integration from the test runner, the `projectId` is always written to the default `cypress.json`, even if a custom config file was passed using the  `--configuration` CLI argument.

### Desired behavior

Take the used cypress configuration file into account when updating the dashboard integration settings.

### Test code to reproduce

1) Open cypress using a custom configuration file
`cypress open --configuration='cypress-prod.json'`
2) Go to the "runs" tab and connect it to the dashboard
3) The `projectId` key is written to the `cypress.json` file, instead of `cypress-prod.json`

### Versions

5.4.0

**Comment by jennifer-shehane** [comment] 2020-10-23 05:02
Duplicate of https://github.com/cypress-io/cypress/issues/5747

**Closed by jennifer-shehane** 2020-10-23 05:02 UTC
