### ISSUE TITLE
Test fail after "Silent Sign In Failed." is called.

### ISSUE THREAD

**Issue by pavelsmajda** [cypress-io/cypress#4978] opened 2019-08-13 12:40 UTC
After a very long fight I already asked in chat but without success, so I'm trying luck here.

It seems problem is somewhere between Cypress and OIDC library.

### Current behavior:
Hi , did anyone of your team experienced issue with `Silent Sign In Failed.` error ? 

We have 3 Angular applications with oidc authentication. When I sign in, after silent refresh is called, then I get  `Silent Sign In Failed.` error in browser console (Electron 61, Chrome 76) 
I tried all workarounds but nothing worked. Problem is token have no cookie related and throw the error.

- The same failing behavior is with cypress recorder BUT Selenium IDE is passing the test so I think this issue seems to be Cypress related. 
- Items in localStorage are not deleted between the tests (instead of second oidc. item -- see .gif file attached) - seems to be caused by "before" function (second describe below) - This is not causing the issue it seems.
- It seems Cypress is failing while getting silent refresh and proper token information and trying to request it again without success. (first few tokens are ok and works without any problem)
- First token is received and works but after silent refresh is called then token with no cookie is received. 
 
Do you now where is the problem? Is there any workaround?

Test structure looks like this:

describe('Check if app is available', () => {
    it('request url' () {
        cy.a
        })
    })
})
describe('login into app, function() {
    before(function () {
        cy.login()
    })
    it('go to page X and test something() {
        cy.b
        })
    })
    it('go to page Y and test something () {
        cy.c
        })
    })
describe('logout', () => {
    it('Logout from app', function () {
        cy.d
    })
})

![silent_sign_in_failed](https://user-images.githubusercontent.com/24811669/62940148-38311280-bdd3-11e9-87df-33d7738cbc75.png)

![cypress_loc_storage](https://user-images.githubusercontent.com/24811669/62941825-42eda680-bdd7-11e9-99b4-e23f9206883a.gif)

### Desired behavior:

Cypress should keep user sign in all the time during the test.

### Steps to reproduce: (app code and test code)
Unfortunately I can't provide any project information or reproducible steps. 

### Versions
Cypress 3.4.1, Windows 10, Electron 61, Chrome 76

### What I already tried
Everything from: 
https://github.com/cypress-io/cypress/issues/461
https://github.com/cypress-io/cypress/issues/686
https://docs.cypress.io/examples/examples/recipes.html#Logging-In (all variations)

**Comment by sainthkh** [comment] 2020-12-29 07:14
We're closing this issue because it's old and has no reproducible example. If you're having the same problem with the current version of Cypress, please open a new issue.

**Closed by sainthkh** 2020-12-29 07:14 UTC
