### ISSUE TITLE
Zip File download

### ISSUE THREAD

**Issue by Elif5757** [cypress-io/cypress#14168] opened 2020-12-14 09:33 UTC
### Current Issue

when I click on a button on our frontend a zip file is downloaded locally. In this zip file are pdf files.
I can't download and test it.

### What would you like?

I would like to have a feature that downloads a zip file and enables it to be opened that.

### Why is this needed?

we need to know that our documents are downloaded as a zip file and would like to open the zip file to see what is in it

**Comment by jennifer-shehane** [comment] 2020-12-14 09:59
Duplicate of https://github.com/cypress-io/cypress/issues/949

**Closed by jennifer-shehane** 2020-12-14 09:59 UTC

**Comment by jennifer-shehane** [comment] 2021-01-20 04:33
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
