### ISSUE TITLE
Unable to mount / load component having relative path within it

### ISSUE THREAD

**Issue by arunkumar741** [cypress-io/cypress#24335] opened 2022-10-21 11:35 UTC
### Current behavior

I am using CRA, using context api, placed cypress folder within src folder

login.js
`import image1 from "assets/images/image.jpg'`

currently cypress is not detecting relative paths within a  component / js file

error details
`Error: Webpack Compilation Error
./components/image.js
Module not found: Error: Can't resolve "assets/images/image.jpg" `

### Desired behavior

relative paths within component / js file need to be used properly

### Test code to reproduce

login.js
`import image1 from "assets/images/image.jpg'`

### Cypress Version

v10.10.0

### Node version

v14.18.0

### Operating System

windows 10

### Debug Logs

```shell
Error: Webpack Compilation Error
./components/image.js
Module not found: Error: Can't resolve "assets/images/image.jpg"
```

**Comment by amehta265** [comment] 2022-10-26 16:23
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by arunkumar741** [comment] 2022-10-27 09:49
addings logs here

```
1000x660
Error: Webpack Compilation Error
./views/Pages/LoginPage.js
Module not found: Error: Can't resolve 'NewContext.js' in 'C:\Arun\Main\current_apps\src\views\Pages'
resolve 'NewContext.js' in 'C:\Arun\Main\current_apps\src\views\Pages'
  Parsed request is a module
  using description file: C:\Arun\Main\current_apps\package.json (relative path: ./src/views/Pages)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Arun\Main\current_apps\src\views\Pages\node_modules doesn't exist or is not a directory
      C:\Arun\Main\current_apps\src\views\node_modules doesn't exist or is not a directory
      C:\Arun\Main\current_apps\src\node_modules doesn't exist or is not a directory
      C:\Arun\Main\node_modules doesn't exist or is not a directory
      C:\Arun\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Arun\Main\current_apps\node_modules
        using description file: C:\Arun\Main\current_apps\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Arun\Main\current_apps\package.json (relative path: ./node_modules/NewContext.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.json doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.jsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.js.mjs doesn't exist
            .coffee
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.js.coffee doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.js.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Arun\Main\current_apps\node_modules\NewContext.js.tsx doesn't exist
            as directory
              C:\Arun\Main\current_apps\node_modules\NewContext.js doesn't exist
[C:\Arun\Main\current_apps\src\views\Pages\node_modules]
[C:\Arun\Main\current_apps\src\views\node_modules]
[C:\Arun\Main\current_apps\src\node_modules]
[C:\Arun\Main\node_modules]
[C:\Arun\node_modules]
[C:\node_modules]
[C:\Arun\Main\current_apps\node_modules\NewContext.js]
[C:\Arun\Main\current_apps\node_modules\NewContext.js]
[C:\Arun\Main\current_apps\node_modules\NewContext.json]
[C:\Arun\Main\current_apps\node_modules\NewContext.jsx]
[C:\Arun\Main\current_apps\node_modules\NewContext.js.mjs]
[C:\Arun\Main\current_apps\node_modules\NewContext.js.coffee]
[C:\Arun\Main\current_apps\node_modules\NewContext.js.ts]
[C:\Arun\Main\current_apps\node_modules\NewContext.js.tsx]
 @ ./views/Pages/LoginPage.js 106:26-58
 @ ./cypress/e2e/login_spec.cy.js
 
    at Watching.handle [as handler] (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-preprocessor\dist\index.js:230:23)
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Watching._done (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:98:28)
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:73:19
    at Compiler.emitRecords (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Watching.js:54:20
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:482:27
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:464:33
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\Arun\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:179:23)
```

**Comment by arunkumar741** [comment] 2022-10-27 09:55
similar to #20487 , but this is happening in react app (create-react-app)

**Comment by amehta265** [comment] 2022-10-28 15:31
@arunkumar741 Thank you for providing the error logs.
Upon further investigation, looks like `webpack` is complaining about the `browser` field. If you have a client side application, webpack requires the `resolve.aliasFields` argument in your `webpack.config` to contain a browser element as explained [here](https://webpack.js.org/configuration/resolve/). The `browser` helps tell the bundler (in this case webpack) to how to bundle certain arguments: https://github.com/defunctzombie/package-browser-field-spec
A couple suggestions:
- Ensure that all your imports in the `NewContext.js` file specify the directory you are starting from i.e. try to change `import image1 from "assets/images/image.jpg'` to `import image1 from "./assets/images/image.jpg'` Notice the extra `./` in the proposed code. Also check the casing for the paths you mentioned so that they exactly match the casing you used for your files
- Ensure that your the `resolve.extensions` in your `webpack.config` have all the necessary extensions mentioned e.g. 
```
module.exports = {
(...)
  resolve: {
    extensions: ['.ts', '.js'],
  }
}
```
This is because some files used by Cypress are `.js` files so ensure all extensions are covered.

If the suggestions above don't solve the issue I strongly recommend you provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. This would significantly help me reproduce the issue on my end.

**Comment by amehta265** [comment] 2022-11-04 14:16
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by amehta265** 2022-11-04 14:16 UTC
