### ISSUE TITLE
Running Light house with cypress is resulting in error 

### ISSUE THREAD

**Issue by priyagupta06** [cypress-io/cypress#29060] opened 2024-03-05 14:11 UTC
### Current behavior

Have installed all the necessary settings but at lighthouse scan run it's throwing error and coming out of Chrome
Cypress extension has disconnected. Cypress cannot run tests without this extension 'reload the browser'.
```json
"@cypress-audit/lighthouse": "^1.4.2",
"lighthouse": "^11.3.0",
"cypress": "10.11.0",
```

Sharing versions as well for ref

### Desired behavior

It should the run the lighthouse scan and come with accessibility reports

### Test code to reproduce

This has been added in index.js
```js
on('task', {
    lighthouse: lighthouse(),
    pa11y: pa11y(),
  });
```

### Cypress Version

10.11.0

### Node version

21.6.2

### Operating System

McOS Sonoma 14.3.1

**Comment by jennifer-shehane** [comment] 2024-03-05 16:37
@priyagupta06 Could you try on the newest version of Cypress?

**Comment by priyagupta06** [comment] 2024-03-05 23:50
Tried with Cypress 13.6.6 - 

Getting this error now on console and chrome is getting crashed - 
We detected that the Chrome tab running Cypress tests closed unexpectedly.

We have failed the current spec and aborted the run.

**Comment by priyagupta06** [comment] 2024-03-06 00:06
Also tried with 13.5.1 - Same error. it opens up lighhouse analysis in same tab - pausing the cypress automation run and after that the chrome session terminates and crash

**Comment by jennifer-shehane** [comment] 2024-03-06 15:51
@priyagupta06 This is a duplicate of https://github.com/cypress-io/cypress/issues/28511. We've changed the behavior of how cypress works across tabs, so the lighthouse plugin will need to update to accommodate on their side.

**Closed as not planned by jennifer-shehane** 2024-03-06 15:51 UTC
Labels: type: duplicate
