### ISSUE TITLE
Cypress hangs in TFS build

### ISSUE THREAD

**Issue by HiranCser** [cypress-io/cypress#5091] opened 2019-09-05 14:47 UTC
[cypress_logs.txt](https://github.com/cypress-io/cypress/files/3579838/cypress_logs.txt)

### Current behavior:

E2E test written using Cypress hangs in tfs build, passes locally. Test passes, however, the cypress process is not exiting and hence, build fails.

### Desired behavior:

cypress process should exit after test finished (irrespective of test passed/failed)

### Steps to reproduce: (app code and test code)

see the attached logs 

### Version

Cypress: 3.2.0
Electron: 59.*
Angular : 7.2

With solution from : https://github.com/cypress-io/cypress/issues/4182, test hangs even locally. So I feel `onbeforeunload` is not issue with my test.

Any hint on why cypress process hangs, will be helpful.

NOTE: TFS does not have internet access, angular packages are installed using TFS package feed and cypress zip stored in the build system.

**Comment by jennifer-shehane** [comment] 2019-09-05 19:12
Try running the tests locally and selecting 'Electron' to run the tests or pass `--browser` flag of 'chrome' in `cypress run`. Where the tests fail in this situation would narrow down if it's an issue with Electron. 

Regardless,  we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-09-05 19:12 UTC

**Comment by HiranCser** [comment] 2019-09-06 14:13
I've written small reproducible test.

[Cypress_Repo.zip](https://github.com/cypress-io/cypress/files/3584290/Cypress_Repo.zip)

You need .Net core 2.2, Node JS and Yarn

Steps
====
Download the zip
Open solution in Visual Studio
Build the solution (any mode - Debug or release). In case angular compilation fail, perform yarn install manually once. Incase you use npm to install, adapt clientapp project file for the same.
Run below command from ClientApp directory
	gulp systemtest --url=http://localhost:52760 --continue --copyLogs=True

**Please try 3-4 times if issue is not reproducible at once.** 

you should be able to see message as shown below.

[19:24:40] Error: Command failed: node_modules\.bin\cypress run --spec=**/*.e2e-spec.dev.ts -P ./e2e --env baseUrl=http://localhost:52760

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

We have added timeout for cypress task which actually runs test.

**Comment by irfancharania** [comment] 2019-11-28 19:35
I'm seeing this happen now after upgrading to 3.7.0 from 3.4.0. 
(I had skipped upgrading in between due to authentication cookie issues)

There is no Chrome installed on the build server. 

When I run in interactive (Cypress open) mode, the tests pass without issues. 
When I run in headless mode (Cypress run ...), the tests pass most of the time, occasionally hanging.
When I run headless from TFS, the tests always hang. (I let one release go to see when it would end and it hadn't stopped by the next day...)

When I switch back to 3.4.0, all tests pass as expected within reasonable time.

**Comment by jennifer-shehane** [comment] 2020-01-02 07:44
@irfancharania Please provide a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by irfancharania** [comment] 2020-01-07 18:57
@jennifer-shehane I upgraded to 3.8.1 and this issue is resolved. Running headless from TFS in a Windows Server 2016 Standard environment is working again. However, I am seeing the same issue identified in [5595](https://github.com/cypress-io/cypress/issues/5995). I will follow that one.
