### ISSUE TITLE
Items of menu of Cypress Runner are not clickable

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#16687] opened 2021-05-26 11:48 UTC
### Current behavior
1. Open Cypress.exe
2. Click any item in menu of Cypress  Runner (File, Edit, View etc.)
3. Item is not clickable.

### Desired behavior
3. Item is clickable.

### Versions
Cypress 7.4.0, Windows 10 Enterprise

**Comment by jennifer-shehane** [comment] 2021-05-26 15:35
Duplicate of https://github.com/cypress-io/cypress/issues/16323

**Closed by jennifer-shehane** 2021-05-26 15:35 UTC
