### ISSUE TITLE
When no baseUrl is provided in cypress.json , first cy.visit reruns prior commands

### ISSUE THREAD

**Issue by SergeS** [cypress-io/cypress#6525] opened 2020-02-20 19:13 UTC
### Current behavior:

When no baseUrl is provided in cypress.json , first cy.visit reloads test suite causing all prior commands to rerun (I'm using cypress to also test example server startup, therefore baseUrl is not accessible on start).

### Desired behavior:

cy.visit do not reload whole envirnoment in browser

### Test code to reproduce

cypress.json

```json
{}
```

cypress/integration/example.spec.js

```js

describe('Example server', () => {
  before(() => {
    cy.task('startServer', {}).should('be', 'ok'); // this will happen twice
    // Reason to start server here is that we have ~21 examples and I want to have them covered with single test suite, including test if script will launch server as expected
  })

  it('starts', () => {
    // First call to this visit will cause electron content to reload and run before block again
    cy.visit('http://localhost:8080/') // check if it is running

    // do some other tests on output
  })

  // other
});

```

### Versions

cypress 4.0.2
Electron 78
node v10.9.0

**Comment by SergeS** [comment] 2020-02-20 19:16
Addon, happens in all browsers.

As alternative solution, disabling baseUrl test on start would be sufficient

**Comment by jennifer-shehane** [comment] 2020-02-24 07:14
Duplicate of #2602

**Closed by jennifer-shehane** 2020-02-24 07:14 UTC
