### ISSUE TITLE
Browser: 'chrome' was not found on your system.  (windows)

### ISSUE THREAD

**Issue by chli283** [cypress-io/cypress#2989] opened 2018-12-26 11:32 UTC
### Current behavior:
My Evironment:    Win 7 , Chrome71
```
Given I have already install cypress 3.1.3 by npm.
When Run 'cypress run --browser chrome'
Error:
...
 Can't run because you've entered an invalid browser. 
Browser: 'chrome' was not found on your system. 
Available browsers found are: electron
```

### Desired behavior:

Run cypress with chrome71 in OS.

### Versions
Cypress version 3.1.3

**Comment by jennifer-shehane** [comment] 2018-12-26 16:33
Duplicate of https://github.com/cypress-io/cypress/issues/2834

**Closed by jennifer-shehane** 2018-12-26 16:33 UTC

**Comment by chli283** [comment] 2018-12-27 02:08
I had reviewed the #2834.
It did not work in my system.


I would like to run cypress with chrome71 in OS, not default electron chrome59.
When  run `cypress run --browser chrome`
Got error following:

...
 Can't run because you've entered an invalid browser. 
Browser: 'chrome' was not found on your system. 
Available browsers found are: electron

**Comment by jennifer-shehane** [comment] 2018-12-27 05:39
Yes, this is the exact same issue as #2834 as I've previously stated. There has not been enough information provided on that issue to reproduce on our end, so no work has been done on this.

**Comment by Elif5757** [comment] 2020-06-05 05:17
Hi, 
i've been using cypress recently. 
I would like to run my tests in Edge or Canary but i got :
Can't run because you've entered an invalid browser name.  Browser: 'edge' was not found on your system.  

I didn't understand how i can set it and which path should I put in the index.js 
Please help! :(  @jennifer-shehane

**Comment by jennifer-shehane** [comment] 2020-06-05 08:51
@Elif5757 Check out troubleshooting guide on launching browsers: https://on.cypress.io/troubleshooting#Launching-browsers

**Comment by WilliamMega** [comment] 2021-08-03 18:59
I cannot access the option:

Go to File -> View App Data

Also, I can't configure Chrome and Firefox browsers to be displayed on Cypress.

I've already tried using "https://docs.cypress.io/guides/references/troubleshooting#To-clear-App-Data"

Could someone help me please?
