### ISSUE TITLE
`cy.intercept` StaticResponse headers cannot contain multiple `Set-Cookie` header values 

### ISSUE THREAD

**Issue by ARBrooks** [cypress-io/cypress#16441] opened 2021-05-11 11:35 UTC
Hi, I've got a scenario where I'm stubbing an endpoint that sets multiple cookies on success via multiple set-cookie headers using the intercept API.

With a static response object, when you define the headers option it only enables you to define a single header/ set-cookie entry with the typings strictly only allowing strings, so if you have, for example:

```js
headers: {
     set-cookie: ['cookie1=1', 'cookie2=2']
}
```
Cypress throws and exception, but there's no alternative that I've seen to define the set-cookie header, with multiple entries with a static response. I've tried alternatives like hooking into the req/ res using the handler functions but this isn't fulfilling the upfront stub requirement as it appears to still allow the request through to the destination URL before modifying the response headers with our extra set-cookie header values.

### Current behavior
A single set cookie header will be set, or cypress fails to build and logs and error for the interception stating that StaticResponse can only be used with string values for headers.

### Desired behavior
You can define multiple Set-Cookie header values for a StaticResponse object

### Versions
The equivalent behaviour worked in 5.6.0  upgrading to 7+ and intercept we have observed the above.

**Comment by jennifer-shehane** [comment] 2021-05-11 20:00
Is this just a TypeScript error? You can put a ts-ignore comment above the line to ignore it if that's the case.

**Comment by jennifer-shehane** [comment] 2021-05-13 19:55
I see what you mean. Yah, I don't think this is currently supported unfortunately.

**Comment by jennifer-shehane** [comment] 2021-05-13 19:56
Duplicate of https://github.com/cypress-io/cypress/issues/14368

**Closed by jennifer-shehane** 2021-05-13 19:56 UTC
Labels: pkg/net-stubbing, stage: proposal 💡, type: enhancement
