### ISSUE TITLE
Cypress freezes completely when an ajax request is called in the test

### ISSUE THREAD

**Issue by jesusmsr** [cypress-io/cypress#22475] opened 2022-06-23 11:18 UTC
### Current behavior

I have a button which calls a Javascript function, which launches an ajax request with async = false. When I call .click() on this button, the Cypress runner just completely freezes, I can't click anything on it and I have to close it and open it again.
Also, in my tests I have an interceptor which sets a header required in my application.

### Desired behavior

The Ajax call should be resolved normally, or at least fail the test if something goes wrong.

### Test code to reproduce

The button: 
```
<td><a href='javascript:ajaxLoadDriver();' title="Suchen"><img src="<c:url value='../System/images/lupe_icon.gif'/>"></a></td>
```

Ajax request in JS function:
```
var request = $.ajax({ 
		url: "../User/AjaxFindUser", 
		type: "POST", 
		data: "", 
		dataType: "json",
		async: false
}); 
```

### Cypress Version

10.2.0

### Other

When I open my web application in a normal browser and click this button, the Ajax request is called, and the initiator is jquery.
In the test runner, the initiator shows as cypress-runner, and the request stays as 'pending' 
The payload is exactly the same as in a browser so that's not the problem.
![imagen](https://user-images.githubusercontent.com/82810705/175286512-04561ff6-28cc-40ce-afb9-baec512959d8.png)

**Comment by emilyrohrbough** [comment] 2022-06-23 13:36
@jesusmsr Thank you for logging an issue. This appears to be a duplicate of #22394 so I am going to close this issue. Can you please add this information to that ticket so all the info is in one place?

**Closed by emilyrohrbough** 2022-06-23 13:36 UTC
