### ISSUE TITLE
cy.fixture timeout error with large xlsx file (100MB)

### ISSUE THREAD

**Issue by sgomezcnvdev** [cypress-io/cypress#8253] opened 2020-08-11 16:37 UTC
### Current behavior:
Cypress is throwing a timeout error when it tries to execute the command cy.fixture('import280k.xlsx', 'binary', { timeout: 120000} ).as('import')

![image](https://user-images.githubusercontent.com/8384696/89923352-d4544c00-dbd6-11ea-92cc-0161308f7f68.png)

It happens using large files. I tried with a smaller file and it worked ok. Both files are in cypress/fixture folder.

![image](https://user-images.githubusercontent.com/8384696/89923559-272e0380-dbd7-11ea-83b8-51a9ada4f3a9.png)

### Desired behavior:
I want to use fixture command with large files without timeout errors.

### Test code to reproduce
cy.fixture('import280k.xlsx', 'binary', { timeout: 120000} ).as('import')

### Versions
I tried with
Cypress 4.12.0, 4.11.0 and 4.10.0
Window Server 2008 R2

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-248) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment] 2020-08-12 06:31
Duplicate of #8181 - this will be fixed in our next release. You can roll back to 4.11.0 in the meantime to avoid this error.

**Comment by sgomezcnvdev** [comment] 2020-08-12 14:09
@jennifer-shehane I saw the same behavior on 4.11.0 and 4.10.0. Is it really the same error?

**Comment by jennifer-shehane** [comment] 2020-08-14 10:01
Sorry, no, I didn't look closely enough. This is a different issue.

**Comment by xumepadismal** [comment] 2020-08-20 07:02
Hmm seems to be duplicate of #7365 isn't it?

**Comment by jennifer-shehane** [comment] 2020-08-20 07:51
Sorry, yes. There are a few issues with large fixture files that I've gotten confused. 

Duplicate of #7365

**Closed by jennifer-shehane** 2020-08-20 07:51 UTC
Labels: internal-priority, stage: ready for work, type: bug
