### ISSUE TITLE
Impossible to determine what spec line the custom command has failed at

### ISSUE THREAD

**Issue by alexkiro** [cypress-io/cypress#28719] opened 2024-01-15 10:16 UTC
### Current behavior

Current error logs only show the line inside the command where the test failure occurs. When using multiple calls to the same custom command it can create scenarios where it's impossible to detect which call exactly has failed when running headless.

E.g error log:

```  
Running:  foo.cy.js                                                                       (1 of 1)


  testing error messages
    1) this will fail in the middle


  0 passing (5s)
  1 failing

  1) testing error messages
       this will fail in the middle:
     AssertionError: Timed out retrying after 4000ms: expected '<h1>' to be 'visible'

This element `<h1>` is not visible because it has CSS property: `display: none`
      at Context.checkIfVisible (webpack://foo/./cypress/support/commands.js:136:21)
```

### Desired behavior

Instead of only showing the last line of the error stack: 
```
 at Context.checkIfVisible (webpack://foo/./cypress/support/commands.js:136:21)
```

We should ideally show the entire stack; maybe something like:

```
 at Context.eval (webpack://foo/./cypress/e2e/foo.cy.js:6:17)
 at Context.checkIfVisible (webpack://foo/./cypress/support/commands.js:136:21)
```

### Test code to reproduce

A simple page `bar.html`

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
    <h1>TEST</h1>
    <button onclick="document.querySelector('h1').style.display = 'none';">HIDE</button>
  </body>
</html>
```

A simple command example:
```js
Cypress.Commands.addAll({
  checkIfVisible(selector) {
    cy.get(selector).should("be.visible");
  },
});
```

With a spec:

```js
describe("testing error messages", () => {
  it("this will fail in the middle", () => {
    cy.visit("http://localhost:8000/bar.html");
    cy.checkIfVisible("h1");
    cy.get("button").click();
    cy.checkIfVisible("h1");
  });
});
```

In this example it's impossible to determine if the failure was at the first `cy.checkIfVisible("h1");` call or the second. 

### Cypress Version

13.6.2

### Node version

18.15.0

### Operating System

Ubuntu 22.04.3 LTS

**Comment by jennifer-shehane** [comment] 2024-01-23 22:10
Thanks for the feedback

**Comment by jennifer-shehane** [comment] 2024-01-24 01:17
Duplicate of https://github.com/cypress-io/cypress/issues/15581

**Closed as not planned by jennifer-shehane** 2024-01-24 01:17 UTC
Labels: type: duplicate
