### ISSUE TITLE
cy.click() on React Select component doesn't show the drop down

### ISSUE THREAD

**Issue by bencao** [cypress-io/cypress#549] opened 2017-07-06 16:59 UTC
- Operating System: macOS Sierra
- Cypress Version: 0.19.4
- Browser Version: Electron 53

### Is this a Feature or Bug?

Bug

### Current behavior:

cy.click() on an react select component not showing the dropdown options.

### Desired behavior:

cy.click() on an react select component shows the dropdown options.

### How to reproduce:

A demo repo is created to reproduce the issue.

https://github.com/bencao/react-select-cypress

The test file is located at cypress/integration/react_select_spec.js

#### Test code:

```js
describe('Weird behavior when testing React Select', function() {
  it('fails on Electron 53 and Canary 61, but passes on Chrome 59', function() {
    cy
      .visit('http://jedwatson.github.io/react-select/')
      .get('div.Select-control:first')
        .click()
      .get('.Select-option:contains(Victoria)')
        .click();
  });
});
```

### Additional Info (images, stack traces, etc)

```
$ cypress run                                                                                                       [12:55:58]

Started video recording: /Users/zcao/Documents/workspace/react-select-cypress/cypress/videos/79qp6.mp4

  (Tests Starting)


  Weird behavior when testing React Select
    1) fails on Electron 53 and Canary 61, but passes on Chrome 59


  0 passing (6s)
  1 failing

  1) Weird behavior when testing React Select fails on Electron 53 and Canary 61, but passes on Chrome 59:
     CypressError: Timed out retrying: Expected to find element: '.Select-option:contains(Victoria)', but never found it.
      at Object.cypressErr (http://jedwatson.github.io/__cypress/static/js/cypress.js:5729:15)
      at Object.throwErr (http://jedwatson.github.io/__cypress/static/js/cypress.js:5694:22)
      at Object.throwErrByPath (http://jedwatson.github.io/__cypress/static/js/cypress.js:5721:21)
      at $Cy._retry (http://jedwatson.github.io/__cypress/static/js/cypress.js:12954:26)
      at http://jedwatson.github.io/__cypress/static/js/cypress.js:8122:28
      at tryCatcher (http://jedwatson.github.io/__cypress/static/js/vendor.js:46490:31)
      at Promise._settlePromiseFromHandler (http://jedwatson.github.io/__cypress/static/js/vendor.js:44625:31)
      at Promise._settlePromiseAt (http://jedwatson.github.io/__cypress/static/js/vendor.js:44701:18)
      at Promise._settlePromises (http://jedwatson.github.io/__cypress/static/js/vendor.js:44817:14)
      at Async._drainQueue (http://jedwatson.github.io/__cypress/static/js/vendor.js:42184:16)
      at Async._drainQueues (http://jedwatson.github.io/__cypress/static/js/vendor.js:42194:10)
      at MutationObserver.Async.drainQueues (http://jedwatson.github.io/__cypress/static/js/vendor.js:42022:14)




  (Tests Finished)

  - Tests:           1
  - Passes:          0
  - Failures:        1
  - Pending:         0
  - Duration:        5 seconds
  - Screenshots:     1
  - Video Recorded:  true
  - Cypress Version: 0.19.4


  (Screenshots)

  - /Users/zcao/Documents/workspace/react-select-cypress/cypress/screenshots/Weird behavior when testing React Select -- fails on Electron 53 and Canary 61 but passes on Chrome 59.png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/zcao/Documents/workspace/react-select-cypress/cypress/videos/79qp6.mp4 (0 seconds)


  (All Done)

FAIL: 1
```

**Comment by brian-mann** [comment] 2017-07-06 17:08
This doesn't appear to be `cy.click` related at all. The error message is talking about not being able to find the DOM element, which means its failing on `cy.get`. 

Why are you using `cy.get` as opposed to `cy.contains` which finds elements by their contents?

**Comment by brian-mann** [comment] 2017-07-06 17:09
Oh nevermind, I see that you mean the click isn't causing the dropdown's contents to appear in the DOM. Disregard what I said.

**Comment by jennifer-shehane** [comment] 2017-07-06 17:18
This issue only occurs headlessly and does not occur even when invoking the binary directly with the `--show-headless-gui` option. 

This is definitely a bug. We'll have to investigate it further.

**Comment by bencao** [comment] 2017-07-06 18:19
Not only headlessly, sometimes it can be reproduced with Electron 53 in gui.

**Comment by dziamid** [comment] 2017-08-18 10:09
This is what i do to interact with React Select components: 
```
Cypress.addParentCommand('chooseReactSelectOption', (selector, text, option) => {
  cy
    .get(`${selector} .Select-control input`).first().click({ force: true }).type(text, { force: true })
    .get('.Select-menu').contains(option).click();
});
```

**Comment by bencao** [comment] 2017-09-05 08:26
@dziamid The trick does work! The key is to type on 'input' element. A simplified version:

```
it('works when type on the input element', function() {
  cy
    .visit('http://jedwatson.github.io/react-select/')
    // OLD VERSION 
    // .get('div.Select-control:first').click()
    // the key of the trick is to type on the input element
    .get(`div.Select-control input`).first().type('V')
    .get('.Select-option:contains(Victoria)')
    .click();
});
```

**Comment by dziamid** [comment] 2017-09-05 17:05
Hope we can have native events soon, so we don't have to come up with such tricks anymore. I believe it should be as simple as `cy.get('div.Select-control:first').click()`.

**Comment by brian-mann** [comment] 2017-09-05 17:25
There are a ton of bug fixes for `cy.type` in `0.20.0`. We'll introduce native events when chromium adds multiplexing support to the debugger protocol. If we added it now you'd lose Dev Tools access when running tests in Cypress.

**Comment by johann-sonntagbauer** [comment] 2018-01-13 14:00
I face some related problem - the focus events only work, when the electron window has os native focus. So running the electron UI in the background or headless causes failing tests because UI elements are shown because of missing blur event.
Keeping the UI open and manually focus the window runs fine.

**Comment by johann-sonntagbauer** [comment] 2018-01-13 14:03
There is already a bug report https://github.com/cypress-io/cypress/issues/1176 about the blur event problem

**Comment by jennifer-shehane** [comment] 2018-02-08 19:02
Curious to see if this is resolved in #1275

**Comment by johann-sonntagbauer** [comment] 2018-02-15 11:13
@jennifer-shehane tried the current develop branch with Electron 59. Still the same issue.

**Comment by voold** [comment] 2018-04-19 13:57
Did we resolve this problem?

**Comment by nitzansan** [comment] 2018-06-26 10:14
The problem is not resolved yet.
It's actually originating from `react-select` and I wonder if cypress can actually work around the issue there without solving the root cause itself.
The problem is that react-select dropdown won't open when the window is not focused. For example, even when you use the full gui browser but you open devtools and your window focus is on devtools instead of the app window, it still won't open.

The `input` solution that was suggested above indeed works, but obviously only for input enabled react-select. No input still causes problems.
We currently worked around this by running `--browser chrome --headed` (unfortunately, since it's not ideal).

**Comment by jennifer-shehane** [comment] 2018-07-12 22:44
@nitzansan We made some improvements to Electron's focusing and `document.hasFocus()` in version [`3.0.2`](https://docs.cypress.io/changelog#3-0-2) that was causing behavior similar to this - with dropdowns closing/not opening correctly due to focus issues. 

Has anyone tried this on the latest version?

**Comment by bencao** [comment] 2018-07-13 02:02
Just tested the following spec on cypress 3.0.2, currently it works fine for headed mode(Chrome 59), but still fails for headless mode(Chrome 59).

```
describe('Weird behavior when testing React Select', function() {
  it('fails on Electron 53 and Canary 61, but passes on Chrome 59', function() {
    cy
      .visit('http://jedwatson.github.io/react-select/')
      .get('div.Select-control:first')
        .click()
      .get('.Select-option:contains(Victoria)')
        .click();
  });
});
```

**Comment by Bkucera** [comment] 2018-07-13 04:14
@bencao thanks for this. I'll try to reproduce, and I'll update this with any timeline for a fix

**Comment by Lucianova** [comment] 2018-07-18 16:13
It also works if you type a string with an empty space
```
cy
    .get('div.Select input')
    .first()
   // It will show all the options
    .type(' ', { force: true })
    .get('.Select-option')
    .first()
    .click()
```
Works for headed mode (Chrome 67) and headless mode (Chrome 59)
Cypress 3.0.2

**Comment by Bkucera** [comment] 2018-07-20 18:47
@bencao , 
@brian-mann  found the issue that was causing this, its a problem with the browser not firing focus events when the browser isn't the focused window. The fix should be in a PR soon

**Comment by brian-mann** [comment] 2018-07-20 19:30
This fix will go out in the next release. I'll be opening a new issue describing it and linking it here. There were a few edge cases surrounding focus events that we are getting nailed down. It will likely fix other issues two. There were two separate but related problems going on which made it difficult to track down.

**Closed** 2018-07-30 10:50 UTC
Labels: bug - window focus, stage: needs investigating, type: bug

**Comment by yhoiseth** [comment] 2018-09-21 10:56
> This is what i do to interact with React Select components:
> 
> ```js
> Cypress.addParentCommand('chooseReactSelectOption', (selector, text, option) => {
>   cy
>     .get(`${selector} .Select-control input`).first().click({ force: true }).type(text, { force: true })
>     .get('.Select-menu').contains(option).click();
> });
> ```

Thanks a lot for sharing. I found that I needed to make some adjustments – maybe because I'm using React Select v2.0.0, which [was just released](https://github.com/JedWatson/react-select/releases/tag/v2.0.0):

```js
// cypress/support/commands.js

// …

Cypress.Commands.add("chooseReactSelectOption", (selector, text, option) => {
  cy
    .get(`${selector} input`)
    .first()
    .click({ force: true })
    .type(text, { force: true })
    .get(`${selector} .select__menu`)
    .contains(option)
    .click();
});
```

(It seems like some class names have been changed.)

I used the ID I set on the input as a selector:

```js
// cypress/integration/create_questions_spec.js

// …

cy.chooseReactSelectOption('#respondents-input', 'clark@kent.com', 'clark@kent.com');

// …
```

```js
// src/components/EditQuestion.js

// …

<Select
  defaultValue={selectedRespondentOptions}
  isMulti
  name="respondents"
  options={respondentOptions}
  classNamePrefix="select"
  id="respondents-input"
  onChange={this.onRespondentInputChange}
  styles={colourStyles}
/>

// …

```

**Comment by christianjoun** [comment] 2018-10-11 00:51
@yhoiseth I tried your above solution and it looks like it almost works.  In cypress, I pinned the DOM editor but could not find ".select__menu", instead I was able to find ".select__menu-list". I confirmed I am using react select 2.0.0.  After I made the change to select__menu-list, I get a new error stating. 

`CypressError: cy.click() failed because this element is detached from the DOM.

<div tabindex="-1" class="MuiButtonBase-root-69 MuiListItem-root-137 MuiListItem-default-140 MuiListItem-gutters-144 MuiListItem-button-145 MuiMenuItem-root-302 MuiMenuItem-selected-303" role="option" id="react-select-2-option-1" style="font-weight: 400;">...</div>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.click()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom`

**Comment by mitchuski** [comment] 2018-12-04 06:37
> > This is what i do to interact with React Select components:
> > ```js
> > Cypress.addParentCommand('chooseReactSelectOption', (selector, text, option) => {
> >   cy
> >     .get(`${selector} .Select-control input`).first().click({ force: true }).type(text, { force: true })
> >     .get('.Select-menu').contains(option).click();
> > });
> > ```
> 
> Thanks a lot for sharing. I found that I needed to make some adjustments – maybe because I'm using React Select v2.0.0, which [was just released](https://github.com/JedWatson/react-select/releases/tag/v2.0.0):
> 
> ```js
> // cypress/support/commands.js
> 
> // …
> 
> Cypress.Commands.add("chooseReactSelectOption", (selector, text, option) => {
>   cy
>     .get(`${selector} input`)
>     .first()
>     .click({ force: true })
>     .type(text, { force: true })
>     .get(`${selector} .select__menu`)
>     .contains(option)
>     .click();
> });
> ```
> 
> (It seems like some class names have been changed.)
> 
> I used the ID I set on the input as a selector:
> 
> ```js
> // cypress/integration/create_questions_spec.js
> 
> // …
> 
> cy.chooseReactSelectOption('#respondents-input', 'clark@kent.com', 'clark@kent.com');
> 
> // …
> ```
> 
> ```js
> // src/components/EditQuestion.js
> 
> // …
> 
> <Select
>   defaultValue={selectedRespondentOptions}
>   isMulti
>   name="respondents"
>   options={respondentOptions}
>   classNamePrefix="select"
>   id="respondents-input"
>   onChange={this.onRespondentInputChange}
>   styles={colourStyles}
> />
> 
> // …
> ```

I am testing with Cypress and believe " .select__menu " is no longer a class, can't seem to work out what to replace it with or how to select the option.

Help!

**Comment by Bkucera** [comment] 2018-12-27 13:35
@yhoiseth fixes for react-select v2.0 will be in this PR #2982 
The issue associated with v2 is #1486 , so feel free to drop a comment on there

**Comment by yarokon** [comment] 2019-01-04 10:05
**reacr-virtualized-select** also not showing the dropdown options when the window is not focused (because it based on reacr-select@1.3.0). 

But at least everything works fine in headless mode, or if you manually set the focus on the cypress window.

```
Cypress.Commands.add('chooseRVSOption', { prevSubject: true }, (subject, lablel) => {
  cy.wrap(subject)
    .find('.Select')
    .within(() => {
      cy.get('.Select-control').click();

      cy.get('.VirtualizedSelectOption')
        .contains(lablel)
        .click();
    });
});
```

**Comment by yarokon** [comment] 2019-01-04 12:31
```js
Cypress.Commands.add(
  'chooseRVSOption',
  { prevSubject: true },
  (subject, label = '', searchable = false) => {
    cy.wrap(subject)
      .find('.Select')
      .within(() => {
        cy.wrap(Array.isArray(label) ? label : [label]).each(lablel => {
          if (searchable) {
            cy.get('.Select-input input').type(lablel, { force: true });
          } else {
            cy.get('.Select-control').click();
          }

          cy.get('.VirtualizedSelectOption')
            .contains(lablel)
            .click();
        });
      })
      .then(() => subject);
  }
);

Cypress.Commands.add('clearAllRVSOptions', { prevSubject: true }, subject => {
  cy.wrap(subject)
    .find('.Select .Select-clear')
    .click();
});
```

**Comment by jbpallingayan** [comment] 2019-05-30 12:07
hello, how about createselect? cant add data on the list  here is my test.

`cy.get('.css-1hwfws3').click().find('input').focus().type('City', {
    force: true
  }).wait(500)
  cy.contains('City').click({
    force: true
  })`

**Comment by SimonHFrost** [comment] 2019-08-21 10:34
I modified this to find the input by label instead of id, and also added a delay before selecting the option as my input involves an async call. Hopefully someone find's it useful. Using `react-select@3.0.4`

```javascript
Cypress.Commands.add(
  'chooseReactSelectOption',
  (label, text, option, selectDelay = 0) => {
    cy.contains(label)
      .parent()
      .find(`input`)
      .click({ force: true })
      .type(text, { force: true });

    cy.wait(selectDelay);

    cy.get(`[class*="-menu"]`)
      .contains(option)
      .click();
  },
);
```

**Comment by Bkucera** [comment] 2019-08-29 19:12
@yarokon @SimonHFrost If you're still experiencing unexpected behavior, consider opening new issues, and please edit your comments with what versions of cypress you're on since there were changes to focus events added in [`3.3.2`](https://on.cypress.io/changelog#3-3-2).

**Comment by jennifer-shehane** [comment] 2020-01-06 10:32
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
