### ISSUE TITLE
cypress open reloading in infinite loop when calling cy.visit to `http` URL that upgrades to `https`.

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#28285] opened 2023-11-08 22:17 UTC
### Current behavior

Randomly hitting an infinite loop in open mode. This has been observed repeatedly on windows and sporatically on a Mac while running Cypress in development mode. @mschile was able to reproduce this behavior on windows in v13.4.0.

https://github.com/cypress-io/cypress/assets/14099737/deed0866-ccea-4c32-a7ce-4545ff8bac9e

https://github.com/cypress-io/cypress/assets/14099737/c2894340-a687-45bf-9986-5e74f41fecef

https://github.com/cypress-io/cypress/assets/14099737/9218055f-3d4a-466d-b8a8-d5f864856982

### Test code to reproduce

open mode - click between specs and/or whenever cypress is re-loaded on the page.

### Cypress Version

13.4.0

### Node version

18.5.0

### Operating System

MacOS 12.6.2 / Windows VM

**Comment by emilyrohrbough** [comment] 2023-11-09 20:15
Saw this issue again locally. Was able to capture some debug logs. See https://gist.github.com/emilyrohrbough/32fc6b995a52691ce7b87f7bb208242f.

**Comment by pjg** [comment] 2023-11-13 14:02
I'm also experiencing a similar / this issue. Both in Chrome (v119) and Canary (v121). Electron is fine. Only for me, I am always experiencing a death loop. Any spec launch results in Chrome permanently reloading the whole test page.

**Comment by jennifer-shehane** [comment] 2023-11-28 17:11
I can recreate this with the following code below in Chrome versions 117, 119, 120 (beta) and within Cypress versions 13, 12, 11, and 10.

```js
describe('Test', () => {
    it('Testing http visit', () => {
        cy.visit('http://example.com/')
    })
})
```

It seems that when you visit a website that is `http`, Chrome upgrades the visit to `https` to a secure URL. At the same time, we're still trying to resolve to the `http` URL, while Chrome continues to upgrade - resulting in an infinite loop. 

For now, if you're encountering this issue, some people have reported some luck in clearing their [cache](https://docs.cypress.io/guides/references/troubleshooting#Clear-Cypress-cache) and/or clearing their [App data](https://docs.cypress.io/guides/references/troubleshooting#To-clear-App-Data) and reinstalling Cypress. I haven't tried this myself.

**Comment by Mehran-Badami** [comment] 2023-11-29 06:06
Hello,
I am experiencing the same issue. My system information is as follows:
The issue starts when Chrome tries to redirect to HTTPS.
Chrome version: 119
Node version: v20.9.0
Cypress package version: 13.6.0
Cypress binary version: 13.6.0
Electron version: 25.8.4
Bundled Node version: 18.15.0

![cypress](https://github.com/cypress-io/cypress/assets/7279974/c070be90-baa2-46e2-b3d1-c68de3662c9b)

**Comment by jennifer-shehane** [comment] 2023-11-29 16:42
Closing as duplicate of https://github.com/cypress-io/cypress/issues/25891

**Closed as completed by jennifer-shehane** 2023-11-29 16:42 UTC
Labels: type: bug, type: duplicate
