### ISSUE TITLE
Dashboard: tests passing in seconds, but keeps running for +1 hour.

### ISSUE THREAD

**Issue by MarkLyck** [cypress-io/cypress#14929] opened 2021-02-05 00:32 UTC
### Current behavior

Whenever a run is started on the cypress dashboard, the tests pass quickly. But it keeps being stuck in "Running" for multiple hours.

This seems to have started happening today.

The exact same tests that is now taking 2 hours & counting. Were passing in 10 seconds this morning.

It seems to have gradually gotten worse (even though I have made no changes to the tests, or the pages related to the tests).

Tests running this morning:
<img width="1342" alt="Screen Shot 2021-02-04 at 19 24 44" src="https://user-images.githubusercontent.com/6841110/106972335-a7fd3080-671e-11eb-87ef-1955e062421c.png">

The same tests running now:
<img width="1340" alt="Screen Shot 2021-02-04 at 19 25 12" src="https://user-images.githubusercontent.com/6841110/106972365-b8151000-671e-11eb-9d14-ceb2a4c0d54c.png">

The output of the tests showing it's passing in 1 second
<img width="1568" alt="Screen Shot 2021-02-04 at 19 25 59" src="https://user-images.githubusercontent.com/6841110/106972421-d4b14800-671e-11eb-9a30-20961fec0e0c.png">

When running cypress locally in open mode, it finishes in 5 seconds.
When running cypress in CI mode with record key. It finishes in ~4 seconds (and exits out correctly).

When running it in GitHub, it finishes in ~4 minutes (mostly installing node_modules & building), but the run in the dashboard never ends...

in console:
<img width="1345" alt="Screen Shot 2021-02-04 at 19 27 54" src="https://user-images.githubusercontent.com/6841110/106972565-193ce380-671f-11eb-90e9-7c77e59a627d.png">

The status looks like this for about an hour or so.
<img width="1362" alt="Screen Shot 2021-02-04 at 19 29 12" src="https://user-images.githubusercontent.com/6841110/106972651-47babe80-671f-11eb-9188-78c46b4aae2e.png">

Then it does change to reflect saying my 2 tests have passed. but it's STILL running... :(

<img width="1359" alt="Screen Shot 2021-02-04 at 19 30 02" src="https://user-images.githubusercontent.com/6841110/106972719-64ef8d00-671f-11eb-8906-1e386d6b0ccc.png">

This is blocking our CI/CD pipeline as the Cypress status takes hours to pass.

### Desired behavior

The tests should be marked as passed after all assertions have passed & cypress should stop running.
Status checks should pass if tests all tests have passed.

### Test code to reproduce

integration test:

```
import {
  SPEC_MOCK
} from '../../src/test/mocks'

declare var cy: any

describe('Page load', () => {
  it('Should visit the page', () => {
    cy.intercept(
      { method: 'GET', url: 'https://api.colonynetworks.com/v3/timescale' },
      SPEC_MOCK
    )

    cy.visit('localhost:5000')
    cy.contains('Dashboard')
  })
})

```

Github workflow:
```
name: Integration tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
          wait-on: http://localhost:5000
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Versions:

"cypress": "6.4.0", (latest as of today)

Any idea why this is happening O.o?

**Comment by milan-easykad** [comment] 2021-02-05 00:39
I have just experience the same issue with the Cypress Dashboard using Cypress versions 6.4.0 and 6.3.0, and running tests locally and from AWS CodeBuild Pipeline.

**Comment by matthemsteger** [comment] 2021-02-05 00:50
Unfortunately, if you have github integration turned on with status checks, this will block your build pipeline.

**Comment by jennifer-shehane** [comment] 2021-02-05 05:06
I'm looking into this with our engineering. Is this issue still occuring?

**Comment by jenwei** [comment] 2021-02-05 06:02
@jennifer-shehane - I'm not seeing the issue anymore and am seeing tests complete

**Comment by jennifer-shehane** [comment] 2021-02-05 06:18
We are investigating a possible incident during the time this was reported. I'll update the issue when I have more detail.

**Comment by bodinsamuel** [comment] 2021-02-07 20:09
I confirm the same behavior, right now (Sunday 07/02/2020 21:00 Paris) 
In circle ci that means consuming credit for 5hours until timeout :/

**Comment by jennifer-shehane** [comment] 2021-02-09 02:53
@bodinsamuel Can you email support@cypress.io with the details of the specific run this is occurring on? I think this is likely a new issue.

**Comment by jennifer-shehane** [comment] 2021-02-09 03:37
Closing as resolved as it seems to have been an incident that is no longer occuring.

**Closed by jennifer-shehane** 2021-02-09 03:37 UTC
Labels: external: dashboard, stage: investigating, type: bug

**Comment by KrupalVaghasiya** [comment] 2022-04-19 06:56
@jennifer-shehane I am facing same issue. in my case in the cypress dashboard test will not stop until i cancel it manually.

**Comment by swati-goyal** [comment] 2022-05-02 06:00
@jennifer-shehane Facing the same issue on circleci, and getting `Too long with no output (exceeded 20m0s): context deadline exceeded` error (Version 9.6.0). I have tried everything suggested on different platforms. Now downgraded cypress version and trying again.

**Comment by alineborak** [comment] 2022-06-14 20:09
I'm facing the same issue, this just started happening.
All my tests passed, but it keeps running.

**Comment by kostekd** [comment] 2022-12-30 20:28
Same here. Still looking for a solution

**Comment by MelikeTopcu** [comment] 2023-01-06 09:25
We are having the same problem,  @jennifer-shehane we sent an e-mail and we are waiting for a reply.

**Comment by muranea** [comment] 2023-10-04 19:49
@jennifer-shehane  I am seeing it as well

**Comment by onlypfachi** [comment] 2023-12-15 05:45
I'm having this same issue. What is the solution @jennifer-shehane ?

**Comment by onlypfachi** [comment] 2023-12-15 05:58
Oh, this seems to be caused by the ```cy.origin()```.  If you put any line after it somehow it keeps loading even though the test passes. Removed all my everything after ```cy.origin()``` and it's fixed
