### ISSUE TITLE
Running Edge reports 'failed to connect to Chrome'

### ISSUE THREAD

**Issue by PetMou** [cypress-io/cypress#9024] opened 2020-10-29 10:57 UTC
Weird situation.
I run a test (in an Azure pipeline) with browser Edge.
At some point Cypress reports 'failed to connect to chrome' 
I know this issue looks like #7450, which can be tackled with 'disable-gpu'

Is this an error in reporting or is cypress secretly running Chrome instead of Edge?
The issue appears infrequently.
Windows 10, Azure, OpenShift

```
+ cypress@5.5.0
2020-10-29T10:09:49.8958440Z added 2462 packages from 2003 contributors in 92.685s
2020-10-29T10:09:50.9050267Z 
2020-10-29T10:09:50.9053683Z > dwd-fe@0.405.0 e2e-cicd-tst D:\releaseagents\agent1\_work\r54\a\_dwd
2020-10-29T10:09:50.9055175Z > cypress run --config-file cypress/configs/test.json --headless --browser edge
2020-10-29T10:09:50.9055888Z 
2020-10-29T10:09:51.6705731Z Note: You have set the environment variable:
2020-10-29T10:09:51.6707219Z 
2020-10-29T10:09:51.6709450Z CYPRESS_RUN_BINARY=D:/Tools/Cypress/5.5.0/Cypress/Cypress.exe
2020-10-29T10:09:51.6711244Z 
2020-10-29T10:09:51.6713028Z This overrides the default Cypress binary path used.
2020-10-29T10:09:51.6714661Z 
2020-10-29T10:09:51.8429923Z 
2020-10-29T10:10:03.6271780Z 
2020-10-29T10:10:03.6859917Z ====================================================================================================
2020-10-29T10:10:03.6862107Z 
2020-10-29T10:10:03.6863767Z   (Run Starting)
2020-10-29T10:10:03.6865365Z 
2020-10-29T10:10:03.6946478Z   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
2020-10-29T10:10:03.6947850Z   │ Cypress:    5.5.0                                                                              │
2020-10-29T10:10:03.6949415Z   │ Browser:    Edge 84 (headless)                                                                │
2020-10-29T10:10:03.6950799Z   │ Specs:      32 found (01authorisatie\01inloggen.spec.js, 02zaak\01zaken-tab.spec.js, 02zaak\02 │
2020-10-29T10:10:03.6952151Z   │             zaak-partijnamen.spec.js, 02zaak\03printen-voorhouden.spec.js, 03stapels\01losse-s │
2020-10-29T10:10:03.6953482Z   │             tapel.spec.js, 03stapels\02enkele-stapel.spec.js, 03stapels\03meerdere-stapels.spe │
2020-10-29T10:10:03.6954785Z   │             c.js, 03sta...)                                                                    │
2020-10-29T10:10:03.6956184Z   └────────────────────────────────────────────────────────────────────────────────────────────────┘
2020-10-29T10:10:03.6957339Z 
2020-10-29T10:10:03.6958813Z 
2020-10-29T10:10:03.6960600Z ────────────────────────────────────────────────────────────────────────────────────────────────────
2020-10-29T10:10:03.6962059Z                                                                                                     
2020-10-29T10:10:03.6963289Z   Running:  01authorisatie\01inloggen.spec.js                                              (1 of 32)
2020-10-29T10:10:09.3763718Z 
2020-10-29T10:10:09.3777838Z 
2020-10-29T10:10:09.4781592Z   Authorisatie - Inloggen
2020-10-29T10:10:14.9501593Z     √ Log in, open zaak met enter, log uit (5541ms)
2020-10-29T10:10:16.7673028Z     √ Geeft geen zoekresultaat bij openen zaak door verkeerde gebruiker (1797ms)
2020-10-29T10:10:17.7431229Z     √ Geeft foutmelding bij onbekende gebruiker (967ms)
2020-10-29T10:10:19.8787181Z     √ Tonen onbekende zaak (2117ms)
...
...
2020-10-29T10:12:05.5091209Z 
2020-10-29T10:12:05.5210544Z 
2020-10-29T10:12:05.5219794Z ────────────────────────────────────────────────────────────────────────────────────────────────────
2020-10-29T10:12:05.5221473Z                                                                                                     
2020-10-29T10:12:05.5223322Z   Running:  02zaak\03printen-voorhouden.spec.js                                            (4 of 32)
2020-10-29T10:12:11.1592557Z Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
...
2020-10-29T10:12:53.7978026Z Failed to connect to Chrome, retrying in 1 second (attempt 60/62)
2020-10-29T10:12:54.8132199Z Failed to connect to Chrome, retrying in 1 second (attempt 61/62)
2020-10-29T10:12:55.8284205Z Failed to connect to Chrome, retrying in 1 second (attempt 62/62)
2020-10-29T10:12:56.8551022Z Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.
2020-10-29T10:12:56.8556564Z 
2020-10-29T10:12:56.8571091Z This usually indicates there was a problem opening the Chrome browser.
2020-10-29T10:12:56.8576624Z 
2020-10-29T10:12:56.8578768Z The CDP port requested was 50038.
2020-10-29T10:12:56.8580545Z 
2020-10-29T10:12:56.8582687Z Error details:
2020-10-29T10:12:56.8584753Z 
2020-10-29T10:12:56.8585894Z Error: could not find CRI target
2020-10-29T10:12:56.8588811Z     at lazyAssLogic (D:\Tools\Cypress\5.5.0\Cypress\resources\app\packages\server\node_modules\lazy-ass\index.js:110:14)
2020-10-29T10:12:56.8590352Z     at Object.lazyAss (D:\Tools\Cypress\5.5.0\Cypress\resources\app\packages\server\node_modules\lazy-ass\index.js:115:28)
2020-10-29T10:12:56.8591725Z     at findStartPage (D:\Tools\Cypress\5.5.0\Cypress\resources\app\packages\server\lib\browsers\protocol.js:56:23)
2020-10-29T10:12:56.8593003Z     at runMicrotasks (<anonymous>:null:null)
2020-10-29T10:12:56.8594346Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-10-29T10:12:56.8595625Z 
```

**Comment by jennifer-shehane** [comment] 2020-10-30 11:40
Thanks for opening an issue. 

[Microsoft Edge is based on Chromium.](https://support.microsoft.com/en-us/microsoft-edge/download-the-new-microsoft-edge-based-on-chromium-0f4a3dd7-55df-60f5-739f-00010dba52cf), so Cypress performs the same actions to connect to Edge as it would Chrome, like using the Chrome DevTools Protocol, which is why you would see the same messaging when there is an error. 

Closing as duplicate of #7450

**Closed by jennifer-shehane** 2020-10-30 11:40 UTC
