### ISSUE TITLE
Cypress devtool sometimes loses "developer tools" menu bar item 

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#3559] opened 2019-02-21 19:08 UTC
### Current behavior:

I'm not sure when this happens but fairly often I'll go to press a shortcut to reload cypress or open the inspector and find that it isn't working. Then I'll see that those options have disappeared from the menubar:

![image](https://user-images.githubusercontent.com/2730609/53194356-08454700-35c8-11e9-9c9f-1a756e0b3835.png)

### Desired behavior:

![image](https://user-images.githubusercontent.com/2730609/53194493-50fd0000-35c8-11e9-8dc2-eb94a989df82.png)

### Steps to reproduce: (app code and test code)
I'm not sure when this happens, but maybe someone else who has experienced this issue knows?

### Versions
Latest chrome v72
Cypress 3.1.5
Mac OSX

**Comment by jennifer-shehane** [comment] 2019-02-22 06:19
This menu is only available when running Cypress tests on Electron for me. When running through Chrome, the Chrome menubar appears. Are you opening the tests in Electron here?

**Comment by tnrich** [comment] 2019-02-22 16:57
Yep running in electron

**Comment by hinfaits** [comment] 2019-02-22 23:17
I observe this occasionally when running tests in Electron from the Test Runner. I believe when this occurs, the Devtools are also inaccessible through Ctrl+Shift+I (which normally opens the devtools).

Windows 10 / Cypress 3.1.5

**Comment by alexlee-dev** [comment] 2019-04-05 15:26
This happens to me using Electron / Cypress 3.1.5.

**Comment by jennifer-shehane** [comment] 2019-04-24 06:59
I think this may be fixed by this PR: https://github.com/cypress-io/cypress/pull/4003

**Comment by tnrich** [comment] 2019-04-24 17:09
Whoo! Can you let me know when that lands in a cypress release!?

**Comment by lrtanner** [comment] 2019-05-01 21:31
This bug is present on both Windows and Linux for me on 3.1.5

**Comment by jennifer-shehane** [comment] 2019-05-30 08:59
3.3.0 was released. Has this been fixed you y'all?

**Comment by alexlee-dev** [comment] 2019-06-02 06:28
Seems to be fixed for me. Using 3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-03 08:15
Released in [changelog](https://on.cypress.io/changelog#3-3-0).

**Comment by lukeapage** [comment] 2019-07-17 14:25
@jennifer-shehane can you re-open this?

![image](https://user-images.githubusercontent.com/309321/61383722-84119a00-a8af-11e9-9c4a-1e39dec882eb.png)


Its intermittent for me, it happens particularly when my system is slowed down e.g. if I run one spec over and over for 20 mins, until its very slow due to memory leaks, then I close the spec and re-open it.

I notice that you seem to be globally adding and removing the menu for developer tools depending on if a spec window is open, so I suspect that as some of this is async, if you process removing the menu after adding a menu, it ends up disappearing.

work around - close the spec window. wait 10 seconds. open it again.

**Comment by jennifer-shehane** [comment] 2019-07-18 10:01
Honestly, it's much simpler than this because I just found it looking at your screenshot. The Develop Tools menu disappears in Electron browser after focusing on the "Integration Tests" window, then switching back to the Electron browser window. 

Oh great, my screen recording doesn't record my Menu bar. 😝 	

![](http://g.recordit.co/eAULdmiEXr.gif)

**Comment by lukeapage** [comment] 2019-07-18 11:59
Thanks for the simpler reproduction!

**Comment by fr0** [comment] 2020-02-04 17:17
This is still happening for me on Cypress 3.8.3, using Mac OS + Electron 78. Activating the Integration Tests window and switching back to the Electron browser window does not help.

**Comment by jennifer-shehane** [comment] 2020-06-29 06:29
This will be fixed in the Electron 9 upgrade https://github.com/cypress-io/cypress/pull/7791

**Closed** 2020-07-07 09:01 UTC
Labels: browser: electron, pkg/server, stage: pending release, type: bug

**Comment by jennifer-shehane** [comment] 2020-08-20 07:26
Released in [5.0.0](https://on.cypress.io/changelog#5-0-0).

This comment thread has been locked. If you are still experiencing this issue after upgrading to Cypress v5.0.0, please open a new issue.
