### ISSUE TITLE
Cypress run output prints "undefined" in various locations

### ISSUE THREAD

**Issue by zztessema** [cypress-io/cypress#6223] opened 2020-01-22 17:06 UTC
### Current behavior:
When using "cypress run", the output to the command window will print "undefined" in various locations. I was wondering where I could get more information as to what error is occurring to cause this. Is there a way to suppress this?

![image](https://user-images.githubusercontent.com/57146040/72909649-5ba6a480-3d05-11ea-8402-57cf20b5d1c1.png)

This issue was first seen using the default "spec" Mocha reporter but I have used other reporters and all of them will print "undefined".

### Versions
Cypress 3.8.2
Windows 10
Resolution 1920x1200
node 12.13.1
npm 6.12.1

**Comment by jennifer-shehane** [comment] 2020-01-23 10:52
Duplicate of #5995

**Closed by jennifer-shehane** 2020-01-23 10:52 UTC
