### ISSUE TITLE
Error accessing website >>> Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by VladmirOcampo** [cypress-io/cypress#14751] opened 2021-01-26 16:14 UTC
- I'm trying to access a somewhat simple website, which shouldn't be that complicated

- The code is simple
```js
describe('My First Test', () => {
          it('Visits the Avianca', () => {
                   cy . visit ( 'https://www.avianca.com/co/es/' )
             })
  })
```
- This happens in all 3 browsers
-
![image](https://user-images.githubusercontent.com/48364802/105871598-77ebba00-5fc7-11eb-9ca4-d3085ded7535.png)

![image](https://user-images.githubusercontent.com/48364802/105871042-e5e3b180-5fc6-11eb-8370-6eea696f6414.png)

![image](https://user-images.githubusercontent.com/48364802/105870685-81285700-5fc6-11eb-9482-237023dc5f28.png)

**Comment by TapashiRoy** [comment] 2021-06-10 14:17
I am getting the same issue. Do we have any update on this. The timeout has been increased in json file.

![Cypress](https://user-images.githubusercontent.com/47500643/121541043-91e0e300-ca24-11eb-9251-d22fc80d047d.png)
![Capturegit](https://user-images.githubusercontent.com/47500643/121541177-b046de80-ca24-11eb-938b-9e95695affed.PNG)

**Comment by jennifer-shehane** [comment] 2021-06-10 14:57
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/7062. I can recreate the issue as described. 

Someone found a workaround in this comment https://github.com/cypress-io/cypress/issues/7062#issuecomment-749788362 which works in your case. I'm not sure why - please follow the other issue for any followup.

```js
it('Visits the Avianca', () => {
  cy.visit({
    url: 'https://www.avianca.com/co/es/',
    headers: {
      "User-Agent": "axios/0.18.0"
    }
  })
})
```

**Closed by jennifer-shehane** 2021-06-10 14:57 UTC
Labels: blocking, type: bug
