### ISSUE TITLE
cy.type() randomly failing to set text, when length of text > 5.

### ISSUE THREAD

**Issue by hardikdiyora92** [cypress-io/cypress#5626] opened 2019-11-07 12:13 UTC
### Current behavior: 
cy.type('Los Angeles, CA, USA').should('have.value', 'Los Angeles, CA, USA'); is failing randomly in google map's search field. Its like randomly happening. I ran 10 times and it passed 3 times only.

**Screen shot**:
<img width="1280" alt="Exec Screenshot" src="https://user-images.githubusercontent.com/54315475/68387877-a6ca0600-015f-11ea-99f8-2094d6f2d340.png">

### Desired behavior:

It should set text as we expected all times.

### Steps to reproduce: (app code and test code)
**Code**:
<img width="619" alt="code" src="https://user-images.githubusercontent.com/54315475/68388169-4daea200-0160-11ea-9aff-8f051c8eb087.png">

```
describe('Location related tests', function() {
    it('should search the respective location', function() {
        cy.visit('https://maps.google.com/');

        cy.get('#searchboxinput')
            .type('Los Angeles, CA, USA')
            .should('have.value', 'Los Angeles, CA, USA');
    })
});
```

### Versions
"cypress": "^3.6.0"

**Comment by gthompson-extensis** [comment] 2019-11-07 17:05
I'm also seeing a problem. I upgraded from 3.4.1 and am now seeing a problem where .type() is failing to enter in the text.  My text is longer than 5 characters.  I'll see if the problem persists when using less than 5.

**Comment by Bkucera** [comment] 2019-11-07 19:51
@hardikdiyora92 trying out the google maps example, type is working fine but the page is still loading while the text is being typed, which causes the input to briefly be blurred. You can manually verifying this by commenting out all steps but the cy.visit() and manually typing as soon as the page starts to load. If you add a `.wait()` before the type, the problem goes away

**Comment by Bkucera** [comment] 2019-11-07 19:52
@gthompson-extensis could you give a reproducible example as @hardikdiyora92 has above?

**Comment by skoblenick** [comment] 2019-11-12 22:51
@Bkucera I could reproduce this issue exactly as @hardikdiyora92 describes in the test case but...

I created a PR at https://github.com/cypress-io/cypress-test-tiny/pull/53 to demonstrate potentially similar, if not the same issue around the `type()` command. It seems to be related to `3.6.x`. The AngularJS material input I am using receives partial events from `type()` but doesn't react as expected.

The first test example shows it failing. The second shows that I can work around the issue in certain cases by using a `click()` on the component before I type. It looks like the type event isn't setting, possibly keeping focus, when the type command starts to send events; reverting to the last clicked element and starts sending the events to that other component.

**Comment by sainthkh** [comment] 2021-01-04 08:54
@skoblenick It was impossible to reproduce your problem with 6.2.0. Cypress says the fields are hidden by other elements. It can be bypassed by passing `{ force: true }` for now. 

Closing this issue because it seems that the original issue is solved and the issue in the comment has a workaround. If it's still happening, please open a new issue with a reproducible example.

**Closed by sainthkh** 2021-01-04 08:54 UTC
