### ISSUE TITLE
Cannot load iFrame from different domain

### ISSUE THREAD

**Issue by g00fy-** [cypress-io/cypress#954] opened 2017-11-23 11:42 UTC
### Current behavior:
Iframe, or websocket won't load

### Desired behavior:
Iframe loads normally

### How to reproduce:
```javascript
describe('Iframe test', function(){
  it('load iframe', function(){
    cy.visit('https://danskebank.dk/privat/find-hjaelp?n-login=pbnetbank');
    // iframe https://applet.danid.dk/launcher/std/1511437117631 won't load
  })
});
```

### Additional Info (images, stack traces, etc)
![image](https://user-images.githubusercontent.com/843807/33171322-e558637c-d04b-11e7-9522-03f96a804626.png)

**Comment by jennifer-shehane** [comment] 2017-11-27 17:40
Make sure to look through this issue, I believe there may be a workaround for this: https://github.com/cypress-io/cypress/issues/136#issuecomment-342391119

**Comment by brian-mann** [comment] 2017-11-27 17:47
Also you might want to turn off `Chrome Web Security` if you want to access cross origin iframes.

https://docs.cypress.io/guides/guides/web-security.html

**Comment by g00fy-** [comment] 2017-11-30 09:05
@brian-mann 
I tried disabling `Chrome Web Security` but I don't think that is the issue, The request times out (proxy fault?)

![image](https://user-images.githubusercontent.com/843807/33422423-f6619ba6-d5b5-11e7-8be7-8ddc4c0b7f8a.png)

**Comment by jcpeden** [comment] 2018-04-10 14:37
Same issue for me

**Comment by jennifer-shehane** [comment] 2019-01-25 07:42
I am unable to reproduce this issue from the test code provided above on version 3.1.4 of Cypress. 

We'll have to close this issue as resolved if no reproducible example is provided. Can anyone provide a way to reproduce this in >3.1.4?

**Comment by jennifer-shehane** [comment] 2019-04-25 06:22
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 06:22 UTC
Labels: stage: needs information
