### ISSUE TITLE
Performance degradation after multiple runs

### ISSUE THREAD

**Issue by karevn** [cypress-io/cypress#3922] opened 2019-04-09 12:51 UTC
### Current behavior:

I've got a pretty large SPA built in dev Webpack mode with hot reloads (build size is about 8Mb). It has about 20 test cases built with Cypress. When I run one test in a freshly start Cypress - it runs pretty quickly (initial page load takes about 2 sec which is fine).  But when I run the whole test suite - the performance decreases dramatically, and the same test can take up to 20-25 seconds being launched after other 15 cases. As far as I see, it takes about 10-15 seconds to just load the page with JS and start the code. After loading it - the rest of the testcase goes more or less fine.

### Desired behavior:

Performance does not depend on the test run history.

### Versions
Cypress 3.2, MacOS, Chromium/Electron (no difference in behaviour).

**Comment by karevn** [comment] 2019-04-30 07:37
I've realized that it only reproduces in Chromium / Chrome. All is fine when using Electron.

**Comment by jennifer-shehane** [comment] 2019-06-06 05:55
Closing as duplicate of https://github.com/cypress-io/cypress/issues/3829

**Closed by jennifer-shehane** 2019-06-06 05:55 UTC
Labels: browser: chrome, type: performance 🏃‍♀️
