### ISSUE TITLE
.selectFile command when used in Firefox does not send files to the server

### ISSUE THREAD

**Issue by jitenev** [cypress-io/cypress#21991] opened 2022-06-01 10:26 UTC
### Current behavior

You need to add files and send a verification request to the server. There is no response from the server when using Firefox. But the request passes correctly and the result is saved when using Chrome

### Test code to reproduce
```js
 it('Upload_file', () => {
       
        cy.get('input[type="file"]')
            .selectFile([Cypress.env('PathFile') + '6.pdf', Cypress.env('PathFile') + '7.pdf'], { force: true })
        cy.get('input[id="qa-role"]').eq(0).parent().click()
        cy.get('.menuable__content__active div[id^="list-item"]').eq(0).click().wait(500)
        cy.get('input[id="qa-role"]').eq(1).parent().click()
        cy.get('.menuable__content__active div[id^="list-item"]').eq(1).click()
        cy.get('input[id="qa-parent"]').eq(1).parent().click().wait(500)
        cy.get('.menuable__content__active div[id^="list-item"]').eq(0).click().wait(500)
        cy.contains('button', 'Проверить приложенные файлы').click().wait(1500)
        cy.contains('button', 'Далее').click({ force: true }).wait(500)
        cy.contains('button', 'Сохранить').click({ force: true }).wait(500)
    })
```
### Cypress Version

6.14.4

**Comment by flotwig** [comment] 2022-06-02 19:24
Hi @jitenev, we have fixed issues with selectFile since it was released and 6.x is very old, can you please try upgrading to the latest Cypress and letting me know if you still have an issue in Cypress 10.0.1?

**Comment by jitenev** [comment] 2022-06-03 08:11
> 

Updated the version, but the problem remains

**Comment by flotwig** [comment] 2022-06-03 15:40
@jitenev Can you please fork https://github.com/cypress-io/cypress-test-tiny and use it to create a reproducible example which I can  run to see this issue? I haven't been able to reproduce based on the code you shared since it is missing the `cy.visit`.

**Comment by mjhenkes** [comment] 2022-06-10 20:46
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-06-10 20:46 UTC
Labels: stage: awaiting response
