### ISSUE TITLE
cy.intercept cannot properly wait for request against endpoint with multiple aliases

### ISSUE THREAD

**Issue by kevinold** [cypress-io/cypress#9262] opened 2020-11-20 17:07 UTC
### Current behavior 
Migrating from `cy.route` to `cy.intercept` for the upcoming 6.0.0 release reveals a bug when and endpoint has multiple aliases defined for it.

Failing screenshot shows that the `mockedPublicTransactions` request is being intercepted and responded to successfully (notice the Chrome DevTools console where the response shows `"limit": 9000000,` which is only present in the fixture returned (`public-transactions.json`)
![Screen Shot 2020-11-19 at 3 48 41 PM](https://user-images.githubusercontent.com/21967/99827207-f9822000-2b1e-11eb-95e9-c5fc92ab9087.png)

```js
beforeEach(function () {
   // ...
   cy.http("GET", "http://localhost:3001/transactions/public*").as(feedViews.public.routeAlias); //publicTransactions

})

// ...

describe("renders and paginates all transaction feeds", function () {
    it("renders transactions item variations in feed", function () {
      cy.intercept("GET", "http://localhost:3001/transactions/public*", {
        headers: {
          "access-control-allow-origin": window.location.origin,
          "Access-Control-Allow-Credentials": "true",
        },
        fixture: "public-transactions.json",
      }).as("mockedPublicTransactions");

      // Visit page again to trigger call to /transactions/public
      cy.visit("/");

      //cy.wait("@notifications");
      cy.wait("@mockedPublicTransactions")
        .its("response.body.results")
        .then(JSON.parse)
        .then((transactions) => {
// ...
```

Here is what the run looks like

![transaction-feeds spec ts](https://user-images.githubusercontent.com/21967/99827761-a9f02400-2b1f-11eb-9585-65c6df9a078b.gif)

### Desired behavior
Results from `mockedPublicTransactions` are available as they were using `cy.route` to the remainder of the test.

### Test code to reproduce
A reproduction is available [in a branch in the RWA](https://github.com/cypress-io/cypress-realworld-app/pull/649/files#diff-a861fe4d6d78d89525e438b23fbf224ff723dfe2651e05dc608ea3bc82fe9b25)

### Versions
6.0.0

**Comment by kevinold** [comment] 2020-12-02 15:01
Adjusted pathname matching and see the stubbed route matched in "Routes", but the fixture does not seem to be returned.

https://github.com/cypress-io/cypress-realworld-app/pull/676/commits/d18ef3e0b90bb4794a27b3b360870ac7cdc2b404

![Screen Shot 2020-12-02 at 8 56 25 AM](https://user-images.githubusercontent.com/21967/100889486-cd4e9380-347c-11eb-8506-d5974de522fa.png)

**Comment by nickpalmer** [comment] 2020-12-03 21:12
Based on the screenshot it would seem you have two intercepts that match the same endpoint? I believe that intercept picks the FIRST match registered, so you probably need to either not declare the intercept for publicTransactions or declare the mock one first.

I have had to order the registrations of our endpoints so the matching goes in the order appropriate for our wildcards as I have migrated to 6.0.0. So for instance `/Objects/*` route has to be registered AFTER `/Objects` or the `/Objects` match will never be matched.

**Comment by kevinold** [comment] 2020-12-07 15:53
@CypressJosh This seems to be resolved as of latest `develop` branch.

**Comment by jennifer-shehane** [comment] 2021-01-19 07:56
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-01-19 07:56 UTC
Labels: internal-priority, pkg/net-stubbing, type: bug

**Comment by hehoo** [comment] 2021-02-12 06:55
No the problem wasn't fixed.

**Comment by jennifer-shehane** [comment] 2021-02-19 20:04
@hehoo Please open a new issue with a complete reproducible example so we can investigate. Thanks!

**Comment by kevinold** [comment] 2021-03-12 16:02
This appears to be a duplicate of https://github.com/cypress-io/cypress/issues/9302 and I can confirm that https://github.com/cypress-io/cypress/pull/14543 resolves the issue 

cc @flotwig
