### ISSUE TITLE
Cypress run command skips cy.requests

### ISSUE THREAD

**Issue by Nwizardd** [cypress-io/cypress#6439] opened 2020-02-13 10:14 UTC
It looks like that Cypress has a bug that some steps with `cy.request` are ignored when a user runs all tests via the `cypress run` command. But when we run the same test from the Cypress UI (`cypress open`) everything works fine...

So in my code, the second and third POST requests are ignored (nothing happens on the `cypress run` command (`yarn cypress run --browser chrome --config-file=./cypress.json`)

### Test code to reproduce

```js
Promise.all([
    assertFile(`./cypress/fixtures/questionnaire/${val}_submission.json`),
    assertFile(`./cypress/fixtures/questionnaire/${val}_finalize.json`),
  ])
    .then(([submissionBody, finalizeBody]) => {
      expect(submissionBody).not.null;
      expect(finalizeBody).not.null;

      cy.request({
        method: 'POST',
        url: buildApiUrl(Cypress.env('questionnaireConfigurationPath')),
        headers: {
          PHPSESSID: sessionId,
          'X-Requested-With': 'XMLHttpRequest',
          'Content-Type': 'application/json;charset=UTF-8',
          Accept: 'application/json, text/plain, */*',
        },
        body: {},
      }).then(configurationResponse => {
        expect(configurationResponse.status).to.eq(200);
        configurationBody = configurationResponse.body;

        const { questionnaireId } = configurationBody.submission;
        const uniqueSubmissionBody = Object.assign({}, submissionBody, {
          questionnaireId,
        });
        const uniqueFinalizeBody = Object.assign({}, finalizeBody, {
          questionnaireId,
        });

        cy.request({
          method: 'POST',  //this is ignored (nothing on ui test log)
          url: buildApiUrl(Cypress.env('questionnaireSubmissionPath')),
          headers: {
            PHPSESSID: sessionId,
            'cache-control': 'no-cache',
            'Content-Type': 'application/json;charset=UTF-8',
            Accept: 'application/json, text/plain, */*',
          },
          body: uniqueSubmissionBody,
        }).then(submissionResponse => {
          expect(submissionResponse.status).to.eq(200);
          cy.request({
            method: 'POST',  //this is ignored (nothing on ui test log)
            url: buildApiUrl(Cypress.env('questionnaireFinalizePath')),
            headers: {
              PHPSESSID: sessionId,
              'Content-Type': 'application/json;charset=UTF-8',
              Accept: 'application/json, text/plain, */*',
            },
            body: uniqueFinalizeBody,
          }).then(finalizeResponse => {
            expect(finalizeResponse.status).to.eq(200);
            expect(finalizeResponse.body.fundingSearchId).greaterThan(0);
            cy.writeFile('./testDataApi.json', {
              profileId: finalizeResponse.body.fundingSearchId,
            });
          });
        });
      });
    })
    .catch(err => cy.log(err));
});
```

### Versions

Latest Chrome, Cypress

![Open](https://user-images.githubusercontent.com/61007803/74424222-361b3f80-4e5a-11ea-9fcb-c9ea52094834.png)

![Run](https://user-images.githubusercontent.com/61007803/74424224-387d9980-4e5a-11ea-8d7e-ce1b853306b4.png)

**Comment by jennifer-shehane** [comment] 2020-02-13 11:03
Can you write a test that fails during `cypress run` but passes during `cypress open` to demonstrate where the unexpected behavior is? Since I'm not familiar with your app, I can't instantly tell what it expected or not from the screenshot.

Also, we can't run the code provided. We need a reproducible example provided that we can run on our machines to demonstrate the issue or else we will have to close the issue.

**Comment by jennifer-shehane** [comment] 2020-02-14 09:42
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-14 09:42 UTC
Labels: stage: needs information
