### ISSUE TITLE
Jasmine types conflict with Cypress

### ISSUE THREAD

**Issue by yurakhomitsky** [cypress-io/cypress#25349] opened 2023-01-03 21:01 UTC
### Current behavior

I was following along with the installation instructions from [cypress/schematic](https://www.npmjs.com/package/@cypress/schematic) for "ng new" project

However, when I navigated to the `app.component.spec.ts` file I noticed an error you can see in the screenshot below.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/54478076/210440082-ac8b943f-4c47-47bf-bb06-b9fd97b634f1.png">

### Desired behavior

Please add changes required to fix these types of conflicts, or create documentation on what needs to be done to fix this annoying issue.

Expected behavior: Jasmine types should not conflict with Cypres ones, the error should not showing up

### Test code to reproduce

https://github.com/yurakhomitsky/cypress-angular-schematic-issue

### Cypress Version

12.2.0

### Node version

16.15.0

### Operating System

macOS 13.0.1

**Comment by romankhomitskyi** [comment] 2023-01-04 14:00
+1

**Comment by chrisbreiding** [comment] 2023-01-10 20:42
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/7552.

**Closed as not planned by chrisbreiding** 2023-01-10 20:42 UTC
