### ISSUE TITLE
TypeError: test.slow is not a function

### ISSUE THREAD

**Issue by avaldelvira** [cypress-io/cypress#7516] opened 2020-05-28 17:04 UTC
### Current behavior:
Inconsistently (but often) showing this error when running test related to mocha: 
```
TypeError: test.slow is not a function
    at Runner.<anonymous> (Library/Caches/Cypress/4.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/mocha/lib/reporters/base.js:265:30)
```

## Cypress Config (cypress.json):
```json
{
	"viewportWidth": 1920,
	"viewportHeight": 1080,
	"screenshotTimeout": 2000,
	"screenshotsFolder": "cypress/screenshots/regression/test",
	"integrationFolder": "cypress/functional",
	"testFiles": [
		"**/*.spec.js"
	],
	"retries": 0,
	"video": false,
	"chromeWebSecurity": false,
	"screenshotOnRunFailure": false,
	"trashAssetsBeforeRuns": true
}
```

## Command used: 
```
./node_modules/.bin/cypress run --config-file cypress.json
```

### Desired behavior:

Not getting those errors and have a consistency running test

### Test code to reproduce
Sorry, It doesn't happen in any specific test, it's inconsistent and I can't provide any specific example.

### Versions
Platform: linux (Debian - 9.12)
Cypress Version: 4.4.0

**Comment by avaldelvira** [comment] 2020-05-29 14:15
I've reopened this issue because the problem persist in version 4.7.0

**Comment by jennifer-shehane** [comment] 2020-06-01 10:50
Can you provide test code to run to reproduce this? We've never seen this error and it likely will require the exact test code and configuration for us to run. 

Also do you have any reporters/options set up? 

We'll have to close this issue without a fully reproducible example provided.

**Comment by avaldelvira** [comment] 2020-06-01 11:10
Hi @jennifer-shehane I can't provide any specific test to run but our test look like this example:

`
  import { BUTTON } from './constants'

  describe('Show button if cookie is set to true', () => {
  beforeEach(() => {
    Cypress.config('baseUrl', 'http://localhost.nowtv.bskyb.com:8092');
    setLoginCookies(); (set some necessary cookies to mock user login)
    loadFixtures(); (load necessary mocks for headers and footers)
    cy.setCookie('cookie', 'true');
  });

  it('should  display the button', () => {
    cy.route({
      method: 'GET',
      url: '**/',
      status: 200,
      response: {}
    });
    cy.visit('/url');
    cy.get(BUTTON).should('exist');
  });
});
`
They are fairly simple test, nothing special, but we are getting this error: 
`
 Running:  button.spec.js                                                              (6 of 12)
  ✓ should  display the button (2570ms)
TypeError: test.slow is not a function
    at Runner.<anonymous> (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/lib/reporters/base.js:308:30)
    at Runner.emit (events.js:215:7)
    at Reporter.emit (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/lib/reporter.js:230:55)
    at Object.onMocha (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/lib/project.js:381:18)
    at Socket.<anonymous> (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/lib/socket.js:313:32)
    at Socket.emit (events.js:210:5)
    at /root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

TypeError: test.slow is not a function
    at Runner.<anonymous> (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/lib/reporters/base.js:308:30)
    at Runner.emit (events.js:215:7)
    at Reporter.emit (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/lib/reporter.js:230:55)
    at Object.onMocha (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/lib/project.js:381:18)
    at Socket.<anonymous> (/root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/server/lib/socket.js:313:32)
    at Socket.emit (events.js:210:5)
    at /root/.cache/Cypress/4.7.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
`

**Comment by jennifer-shehane** [comment] 2020-06-02 09:17
Do you have any reporters/options set up?

Unfortunately we'll have to close this issue without a fully reproducible example. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by lejban** [comment] 2020-06-26 08:23
Same error with the following code (I'm a noob at cypress, bear with me ;) )

```
function testXXX() {
  return dynamoClient.get({
    TableName: XXX,
    Key: {
      StoreId: XXX,
      Type: 'XXX
    }
  }).promise().then((data) => {
    for (const item of data.Item.Data) {
      describe('XXX ' + item.name, () => {
        it('successfully loads', () => {
          cy.visit('http://localhost:3000/XXX/ + item.id')
        })
      })
    }
  });
}
testXXX()
```

**Comment by lucastagliani** [comment] 2020-06-30 15:11
We have the same error and we tried several things. Then we realized that the error started to happen when we did a rebase in our code and that rebase let our code withou a closing "})" in cypress test file. 

It was like this:

```js
it("test", () => {
      cy.window().then((win) => {
        
      })
// --> missing a closing "})"

it("test B", () => {
     
})
```

Weirdly this throws the "test.slow is not a function" error. 

Hope it helps someone =)

**Comment by jennifer-shehane** [comment] 2020-07-02 08:25
@lejban Unfortunately, I can't run the code provided. Can you provide an example that is runnable from another machine as is?

@lucastagliani I'm not able to reproduce this from the code - this throws a syntax error in both `cypress open` and `cypress run`. Can you provide any other code in the project necessary? plugins/support/reporters/etc?

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-02 08:25 UTC
Labels: stage: needs information

**Comment by moxventura** [comment] 2020-08-10 12:50
I've ran into this using cypress 4.12.1
I had some code with a custom function and fixtures in a before() statement. When I changed the `before()` into `describe("before", () => { ... } )` the problem went away. Not ideal, but it works now. Hope this helps some.

**Comment by pietmichal** [comment] 2021-04-21 12:19
Also came across it in Cypress 6.3.0

**Comment by akmur** [comment] 2021-12-31 14:43
Also came across this with latest Cypress 9.2.0.

This happened to me while running component tests with the `run-ct` command.

This seems to happen if there is some content in `.nyc_output/out.json`

If I clean up out.json and just put a some empty brackets `{}` tests complete properly.

**Comment by micahlt** [comment] 2022-07-25 15:06
The same issue appears in Cypress 7.7.0 (Mocha 7.0.1).  It's not intermittent - occurs every time a test is run.  Unfortunately, I also can't provide a codebase to work with since I'm working on a proprietary project.  Attached is the error stack if anyone is interested.

<details>
<summary>error stack</summary>

```
TypeError: test.slow is not a function
    at Runner.<anonymous> (C:\Users\Micah Lindley\AppData\Local\Cypress\Cache\7.7.0\Cypress\resources\app\packages\server\node_modules\mocha-7.0.1\lib\reporters\base.js:308:30)
    at Runner.emit (events.js:327:22)
    at Reporter.emit (C:\Users\Micah Lindley\AppData\Local\Cypress\Cache\7.7.0\Cypress\resources\app\packages\server\lib\reporter.js:333:46)
    at Object.onMocha (C:\Users\Micah Lindley\AppData\Local\Cypress\Cache\7.7.0\Cypress\resources\app\packages\server\lib\project-base.js:471:26)
    at Socket.<anonymous> (C:\Users\Micah Lindley\AppData\Local\Cypress\Cache\7.7.0\Cypress\resources\app\packages\server\lib\socket-base.js:208:40)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (C:\Users\Micah Lindley\AppData\Local\Cypress\Cache\7.7.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Micah Lindley\AppData\Local\Cypress\Cache\7.7.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

</details>

**Comment by malachit-sekady** [comment] 2022-11-21 20:50
Not that this will help most people who comes across it, but in case it does - we were running into this error. During `npx cypress run --component` it would give this error. But during `npx cypress open` on the same tests, it would pass and do the tests, but the command log would stop working and display "No Tests Found"

Our specific problem was that PDFTron's Webviewer wasn't set up to work. We were ignoring it because the test was supposed to pass without it. But something about it trying to spin up and failing was causing the two esoteric errors/bugs mentioned

**Comment by PetitGens** [comment] 2024-05-16 12:09
In case it can help someone, I encountered similar issues as those mentionned above.

My issue was that one of my test was submitting a form (with default action) without preventing its default behavior (`event.preventDefault()`).

I think it caused my spec file to stop executing, ending with a "0 passed, 0 failed" result and sometimes crashing with a "`e.slow is not a function`" message.
