### ISSUE TITLE
Tests do not fail on cypress internal errors

### ISSUE THREAD

**Issue by Alphy11** [cypress-io/cypress#4236] opened 2019-05-17 18:20 UTC
### Current behavior:

When cypress itself has an error, the test passes.

### Desired behavior:

If cypress has an internal error the test cannot be trusted, and therefore should fail.

### Repro steps
Add uncaught exception handler
```js
  Cypress.on('uncaught:exception', () => {
    return true;
  });
```

throw an error in your code that is not an error object:
`throw "error"`

Cypress tests pass, even though an unhandled exception is thrown.  this is because in the `appendErrMsg` function, it assumes error is an object, and throws before calling the handler.

### Versions

cypress 3.2 
Chrome 72

**Comment by jennifer-shehane** [comment] 2019-05-20 08:15
Can you provide the test code + app code to reproduce this? I'm a little confused how this is represented as a cypress 'internal error' when you say you are throwing the 'error', can you provide the code where you are throwing this? Something we can pull and run locally. 

Also, can you reference where this 'appendErrMsg' call is in our code that you believe the problem is?

**Comment by jennifer-shehane** [comment] 2019-07-11 08:20
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-11 08:20 UTC
Labels: stage: needs information
