### ISSUE TITLE
cy.wait yields string instead of object as intercepted request body

### ISSUE THREAD

**Issue by tlpbu** [cypress-io/cypress#14273] opened 2020-12-22 10:51 UTC
`cy.wait()` yields object containing string instead of object as intercepted request/response body if `cy.intercept()` is used preventing deep equal assertions.

### Current behavior
If request is stubbed with `cy.route()`, then `cy.wait()` yields object in request and response body as expected (if json is used).

### Desired behavior
Yield object to simplify assertions

### Test code to reproduce
I cannot provide full test due to info security but generic code involved is as: 
```js
      cy.route('POST', '/api/data, {}).as('storeDataRequest'); // passes with cy.route stubbing
      cy.intercept('POST', '/api/data', {}).as('storeDataRequest'); // fails with cy.intercept stubbing

      cy.contains('button', 'PUBLISH').click()
        .wait('@storeDataRequest')
        .should(interception => {
          expect(interception.request.body).to.deep.eq(
            { name: 'XYZ',
              date: `${dayjs().format('YYYY-MM-DD')}`,
              collectNew: false,
              productName: 'example.com',
              content: [{ locale: 'en', text: '<p>Text html</p>' }] }
          );
        });
```

### Versions
Cypress 6.20

**Comment by jarretmoses** [comment] 2020-12-22 17:24
Im having this issue myself. It seems the actual api response is just missing and the `body` field is an empty string. The setup above is essentially identical to mine without adding adding the 3rd arg as an empty object. It does not actually happen 100% of the time. I've noticed when the response code is `304 Not Modified` the body will not show my data but when it is `200` the data appears as expected.

**Comment by jarretmoses** [comment] 2020-12-22 17:51
This may actually be a different issue...I've opened a new one

**Comment by tlpbu** [comment] 2020-12-24 11:42
@jarretmoses you issue is something else. from description sounds like the one described here https://glebbahmutov.com/blog/cypress-intercept-problems/#cached-response with solution.

I have response and request body content it is just that it is string if stubbing done with `cy.intercept()` but was always an object with `cy.route()` previously and IMO it was more convenient for assertions.

**Comment by jennifer-shehane** [comment] 2020-12-29 02:42
@tlpbu This is actually only an issue with the request.body, not the response.body. 

### Reproducible example

```js
it('test cy.route()', () => {
  cy.server()
  cy.route('POST', '/users', { foo: 'bar' }).as('postUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/users')
    xhr.send({ name: 'XYZ' })
  })
  cy.wait('@postUrl')
    .should(xhr => {
      expect(xhr.request.body).to.deep.eq({ name: 'XYZ' })
      expect(xhr.response.body).to.deep.eq({ foo: 'bar'  })
    })
})

it('test cy.intercept()', () => {
  cy.intercept('POST', '/users', { foo: 'bar' }).as('postUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/users')
    xhr.send({ name: 'XYZ' })
  })
  cy.wait('@postUrl')
  .should(interception => {
    expect(interception.response.body).to.deep.eq({ foo: 'bar' })
    // ❗️ fails because request.body is a string
    expect(interception.request.body).to.deep.eq({ name: 'XYZ' }
    )
  })
})
```

<img width="524" alt="Screen Shot 2020-12-29 at 9 10 52 AM" src="https://user-images.githubusercontent.com/1271364/103254928-c51f4080-49b5-11eb-94a2-5aaea4c8957d.png">

**Comment by flotwig** [comment] 2021-01-22 19:07
@jennifer-shehane this still fails in 6.3.0, but I think the repro is wrong, the body of the XHR is not being stringified as you expect: 
![image](https://user-images.githubusercontent.com/1151760/105533748-762ea780-5ce4-11eb-985c-3ed4bbb63ce3.png)

If I update the repro to properly send a JSON request body, it passes in 6.3.0:

```js
    it('test cy.intercept()', () => {
      cy.intercept('POST', '/users', { foo: 'bar' }).as('postUrl')
      cy.visit('https://example.com')
      cy.then((win) => {
        Cypress.$.ajax({
          url: '/users',
          method: 'POST',
          contentType: 'application/json',
          data: JSON.stringify({ name: 'XYZ' }),
        })
      })

      cy.wait('@postUrl')
      .should((interception) => {
        expect(interception.response.body).to.deep.eq({ foo: 'bar' })
        // ❗️ fails because request.body is a string
        expect(interception.request.body).to.deep.eq({ name: 'XYZ' })
      })
    })
```

@tlpbu are you POSTing `application/json` type data or some other type of body? Only JSON bodies are automatically parsed in req.body and res.body, currently, but more could be added.

**Comment by tlpbu** [comment] 2021-01-23 12:55
@flotwig Yes, it is JSON in request body.

**Comment by aethr** [comment] 2021-01-27 01:11
We're seeing a similar issue when we use `cy.intercept` and want to make changes to the intercepted response and then deliver it using `res.send`:

```js
  cy.intercept('POST', '/users', (req) => {
    // ... a bunch of logic here
    req.reply((res) => {
      // send an object
      res.send({ name: 'XYZ' });
    });
  }).as('postUrl')

  cy.wait('@postUrl')
    .should((interception) => {
      // ❗️ fails because response.body is a string
      expect(interception.response.body).to.deep.eq({ name: 'XYZ' })
    })
```

**Comment by sybrendotinga** [comment] 2021-02-09 11:01
I have the same issue with the `response.body`.  This works with `.route`: 

```
cy.route('GET', '**/projects/*/calculation').as('projectCalculation')
cy.wait('@projectCalculation').its('response.body').should('contain.keys', ['xyz'])
```

But this fails with `.intercept`:

```
cy.intercept('GET', '**/projects/*/calculation').as('projectCalculation')
cy.wait('@projectCalculation').its('response.body').should('contain.keys', ['projectId', 'name']) // etc.

cy.wait('@projectCalculation').then(request => {
  console.log(typeof request.response.body) // Yields String, the whole body is not JSON, but a String
})
```

![image](https://user-images.githubusercontent.com/14016492/107354371-5cf06e00-6ace-11eb-804a-2c0de0fa8510.png)

**Comment by flotwig** [comment] 2021-02-09 15:04
> @flotwig Yes, it is JSON in request body.

Are you sending content-type `application/json`? That is what matters.

If you are using another content-type, see https://github.com/cypress-io/cypress/issues/14763

**Comment by flotwig** [comment] 2021-02-09 15:04
@sybrendotinga The response type from your server is incorrect. It is text/html, but should be application/json.

**Comment by sybrendotinga** [comment] 2021-02-09 15:54
> @sybrendotinga The response type from your server is incorrect. It is text/html, but should be application/json.

Life safer! This was my problem.

**Comment by flotwig** [comment] 2021-03-24 23:09
Closing since there should not be any issues with this with the current release of Cypress as long as Content-Type is correct - see: https://github.com/cypress-io/cypress/issues/14273#issuecomment-776005868

If you're still experiencing this issue with a JSON content-type in the latest version of Cypress, please open a new issue.

**Closed by flotwig** 2021-03-24 23:09 UTC
Labels: pkg/net-stubbing, stage: ready for work, type: unexpected behavior
