### ISSUE TITLE
cy.type sometimes fails to type without causing test failure

### ISSUE THREAD

**Issue by juan-espinet-adpearance** [cypress-io/cypress#8381] opened 2020-08-22 01:39 UTC
In some cases when interacting with an element which has recently become interactable, `cy.type()` will fail to type into an element, or only partially type, even after the element has been found. No error is shown in the cypress log. 

This behavior was observed specifically on a form modal which was hidden and revealed with a fade-in effect. If `cy.wait()` is called to give the modal longer to fade in or `{force:true}` is added to the `cy.type` options, this error does not occur. 

Looking at the logs and the console output cypress provides, it appears that the target of the keydown events is changing to the previously targeted element for some reason:
![image](https://user-images.githubusercontent.com/55517627/90945826-303f8180-e3dc-11ea-8755-760570fb7a1c.png)

Unfortunately this does not occur with every page load (I tried but wasn't able to isolate the specific event that is causing the element to lose focus), but I was able to observe it fairly frequently when the test is rerun enough times (it seemed to occur more often when the window fully reloaded so the cache was emptied as well).

Test code:
```js
cy.visit('https://www.previewsite.adpearance.com/inventory/437')

cy.get('[aria-controls="RequestQuoteForm"]')
    .first()
    .click()
	   
cy.get('#RequestQuoteForm')
    .should('be.visible') 
    .within(($contactModal) => {
         cy.get('input[name="person.firstName"]').type('Test') 
         cy.get('input[name="person.lastName"]').type('Test') 
    }
```

Desired behavior: If this is an issue with the type command, it should be updated so it does not lose focus. If the type command is working as intended and something in the site code is causing the type command to lose focus, ideally this should result in some kind of error from the type command.

### Versions

Cypress 5.0.0
Windows 10
Chrome 84.0.4147.135 (bundled)

Modal is powered by Foundation 6 Reveal : https://get.foundation/sites/docs/reveal.html`

**Comment by jennifer-shehane** [comment] 2020-08-24 07:30
Cypress will follow the focus that the application follows - and type on the current element with focus. So, there's something that is pulling the focus of the mouse to the modal in between typing in the first input and second input. 

Duplicate of #5480

**Closed by jennifer-shehane** 2020-08-24 07:30 UTC
