### ISSUE TITLE
Cypress 10+Vite3 fails to read REACT_APP_SC_ATTR

### ISSUE THREAD

**Issue by alyaothman14** [cypress-io/cypress#23090] opened 2022-08-03 15:56 UTC
### Current behavior

Trying to run component testing using react+vite3+styled-component
 The component will not mount with an error
Cannot read properties of undefined (reading 'REACT_APP_SC_ATTR')
 at <unknown> (http://localhost:3000/__cypress/src/node_modules/.vite/deps/styled-components.js?v=c5916fe2:597:56)
From previous event:
    at Object.runScripts (http://localhost:3000/__cypress/runner/cypress_runner.js:179934:63)
    at $Cypress.onSpecWindow (http://localhost:3000/__cypress/runner/cypress_runner.js:168145:77)
    at <unknown> (http://localhost:3000/__cypress/iframes//Users/alya/Documents/contra/contra-github-2/contra-web-app/src/components/TextField/TextField.cy.tsx:59:18)

### Test code to reproduce

Setup a React app with styled component
Setup component configuration as per Cypress documentation. 
Use Vite3
Try to mount the component

### Cypress Version

10.4

### Other

Node v18.2
Vite 3

**Comment by rockindahizzy** [comment] 2022-08-04 16:15
Hey @alyaothman14! I'm closing this as it seems to be a duplicate of #22678

**Closed by rockindahizzy** 2022-08-04 16:15 UTC
Labels: stage: investigating
