### ISSUE TITLE
Assertion inside test fails, but test doesn't fail

### ISSUE THREAD

**Issue by MarekJavurek** [cypress-io/cypress#3664] opened 2019-03-07 10:15 UTC
### Current behavior:

test success

### Desired behavior:

test will fail

### Steps to reproduce: (app code and test code)

```js
describe("a", () => {
  it("b", () => {
    cy.get("#c").contains("d");
  });
});
```

![image](https://user-images.githubusercontent.com/405034/53949347-23d14700-40ca-11e9-8552-93b1f76c1509.png)

### Versions

Cypress: "cypress": "^3.1.5" (latest npm, latest nodejs)
operating system: 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
browser: both, chrome 74, electron 59

**Comment by jennifer-shehane** [comment] 2019-03-07 10:51
I've been chasing this one for a while: https://github.com/cypress-io/cypress/issues/2720 https://github.com/cypress-io/cypress/issues/3497

Unfortunately, running the code provided (on Mac) does not produce this situation for me. 

<img width="1563" alt="screen shot 2019-03-07 at 5 17 36 pm" src="https://user-images.githubusercontent.com/1271364/53951611-3dd84d00-40fd-11e9-88d9-58f75e8a5ba9.png">

Closing as duplicate of https://github.com/cypress-io/cypress/issues/3497 - please provide more information in there if you do narrow it down some more. For example, do you have anything in support files? plugin files? cypress.json??

**Closed by jennifer-shehane** 2019-03-07 10:51 UTC
