### ISSUE TITLE
Simulated copy and paste failure

### ISSUE THREAD

**Issue by 614222611** [cypress-io/cypress#4381] opened 2019-06-04 07:44 UTC
![企业微信截图_15596342298763](https://user-images.githubusercontent.com/50280980/58860865-ab395100-86df-11e9-8972-9cd802d33489.png)

**Comment by 614222611** [comment] 2019-06-04 07:46
I can't execute Ctrl + C and Ctrl + V. What's the problem?

**Comment by jennifer-shehane** [comment] 2019-06-04 10:44
Duplicate of https://github.com/cypress-io/cypress/issues/2386

**Closed by jennifer-shehane** 2019-06-04 10:44 UTC

**Comment by 614222611** [comment] 2019-06-05 01:17
But my cypress test browser failed to achieve its function. What's the matter, please?

**Comment by jennifer-shehane** [comment] 2019-06-10 05:25
Copy and paste is not supported yet - how you are doing it. Please follow this issue: https://github.com/cypress-io/cypress/issues/2386
