### ISSUE TITLE
Cy.visit got redirected

### ISSUE THREAD

**Issue by vitoo** [cypress-io/cypress#2384] opened 2018-08-22 15:28 UTC
Hi

### Current behavior:

I have in my test 
```js
  cy.visit('https://www.google.fr')
```
When i run the test, the runner 

http://localhost:56325/__/#/tests/integration\examples\google.js

 is redirected to  : 

https://www.google.fr/__/#/tests/integration\examples\google.js

So the runner page is lost.

Is this issue known ?

### Versions

Windows 7
Cypress 3.1.0 (i've tried the windows 64 exe package and the npm version with gitbash)

**Comment by jennifer-shehane** [comment] 2018-08-22 17:16
Cypress does redirect the main url to the window under test - this in intended behavior. 

What do you mean by "the runner page is lost"? Can you provide a screenshot?

**Comment by vitoo** [comment] 2018-08-22 19:35
So i've tried on linux, it works 

https://image.ibb.co/cuR4yK/linux.png

but on windows, the browser really visit the url, so i'm out of cypress

https://image.ibb.co/munBdK/windows.png

**Comment by jennifer-shehane** [comment] 2018-08-22 21:51
Yeah I do see that the `/` is being converted to `%5c` within the url on windows, but not on linux.

**Comment by bitstrider** [comment] 2019-03-07 01:52
hey I'm also having the same issue, any updates?

for me things worked as expected with `cy.visit` a remote url, like: https://mydomain.com

but when i tried it on a locally hosted page, like http://localhost:8080, i get the same problem as @vitoo 

Win10
Cypress 3.1.3

**Comment by jennifer-shehane** [comment] 2019-03-08 09:16
@bitstrider Have you tried a later version of Cypress? Does this still happen on 3.1.5?

**Comment by bitstrider** [comment] 2019-03-11 04:29
@jennifer-shehane thanks for the tip, its working fine with 3.1.5 🙌

**Comment by RicardoVaranda** [comment] 2019-03-21 10:28
I'm still facing this issue in 5.2.0 on windows @jennifer-shehane has there been any development on this?

**Comment by AlbertWhite** [comment] 2019-06-26 10:47
It is not working on win10 with the same problem

**Comment by flotwig** [comment] 2019-06-26 13:20
I think that the issue in this thread looks like a duplicate of #1253 - where Chrome fails if there are proxy settings set by the administrator.

Anyone experiencing this issue: can you please visit `chrome://policy` in the browser launched by Cypress and share the contents? If there are any `Proxy` or `Extension` policies set, it can cause bad behavior on the part of Cypress.

For now, the workaround is to use Electron or [try the workarounds in this issue comment](https://github.com/cypress-io/cypress/issues/1253#issuecomment-465782037).

#4405 will add a clear warning in the GUI when this problem is encountered.

**Comment by knagarajan1984** [comment] 2019-10-25 12:11
my issue is related to this.
After cy.visit() to my home page url, I am being asked to authenticate against Azure AD during which redirection to login.microsoftonline.com happens. During this time, i am being kicked out of cypress as commented above by @vitoo and the test abrupty stops

snapshot of policies on browser launched by cypress. 
![image](https://user-images.githubusercontent.com/15121799/67570255-31a70b80-f731-11e9-9b83-2ce26651bc69.png)

OS: Windows 10
cypress: 3.5

**Comment by jennifer-shehane** [comment] 2020-02-04 07:40
Anyone experiencing this issue: please visit `chrome://policy` in the browser launched by Cypress and share the contents? If there are any `Proxy` or `Extension` policies set, it can cause bad behavior on the part of Cypress.

For now, the workaround is to use Electron or [try the workarounds in this issue comment](https://github.com/cypress-io/cypress/issues/1253#issuecomment-465782037).

You should also clear warning in the GUI when this problem is encountered.

**Closed by jennifer-shehane** 2020-02-04 07:40 UTC
Labels: OS: windows, stage: awaiting response
