### ISSUE TITLE
Drag and drop is not working.

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#25061] opened 2022-12-08 11:23 UTC
### Current behavior

I'm using my drag and drop functions for 2 years.
It's working on 11.2.0 version, but it's not working at 12.0.1 version

### Test code to reproduce
```js
const checkDragAndDrop = (nameDrag, nameDrop, tableName) => {
  cy.get(tableName)
    .find('tr')
    .contains(nameDrag)
    .parent()
    .find('svg')
    .eq(0)
    .trigger('mousedown', { which: 1, button: 0 })
    .trigger('dragstart', { dataTransfer: dataTransfer })

  cy.get(tableName)
    .find('tr')
    .contains(nameDrop)
    .parent()
    .find('svg')
    .eq(0)
    .trigger('dragover', { dataTransfer: dataTransfer, position: 'bottomLeft' })
    .trigger('drop', { dataTransfer: dataTransfer, force: true, position: 'bottomLeft' })
    .trigger('mouseup', { which: 1, button: 0, position: 'bottomLeft' });
}
```
### Cypress Version

12.0.1

### Node version

14.15.1

### Operating System

Windows 11

**Comment by emilyrohrbough** [comment] 2022-12-21 00:18
@zbigniewkalinowski I am sorry to hear you are having troubles. Can you provide a quick example page I can test this against to verify the behavior you are seeing? Without it and your error logs, it's difficult to determine the root cause of your issues. Thanks!

**Comment by emilyrohrbough** [comment] 2023-01-03 14:54
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by emilyrohrbough** 2023-01-03 14:54 UTC
