### ISSUE TITLE
Cypress does not work on Windows - Chrome

### ISSUE THREAD

**Issue by yogeshgadge** [cypress-io/cypress#21299] opened 2022-05-02 21:37 UTC
### Current behavior

This is happening to me todat angular 13 and cypress/schematics 1.6.0 , cypress 9.6.0.

Step1: Create a brand new angular project with routing - call this my-cypress-app

Step 2: ng add @cypress/schematic

Step 3: ng serve

Step 4: ng run my-cypress-app:cypress-open - click on the spec file, F12 in the another chrome window and this exact error

### Desired behavior

Angular 13 and cypress/schematics 1.6.0 , cypress 9.6.0.

Step 1: `ng new my-cypress-app --routing=true && cd my-cypress-app` Create a brand new angular project with routing - call this my-cypress-app

Step 2: `ng add @cypress/schematic`

Step 3: `ng serve`

Step 4: `ng run my-cypress-app:cypress-open` - click on the spec file, F12 in the another chrome window and this error

```
core.mjs:6461 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '__'
Error: Cannot match any routes. URL Segment: '__'
    at ApplyRedirects.noMatchError (router.mjs:2938:16)
    at router.mjs:2920:28
    at catchError.js:10:38
    at OperatorSubscriber._error (OperatorSubscriber.js:19:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at OperatorSubscriber.error (Subscriber.js:40:1)
    at OperatorSubscriber._error (Subscriber.js:64:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25444:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
```

fyi - same steps on macOS worked fine

### Test code to reproduce

No code needed just follow steps

### Cypress Version

9.6.0

### Other

* Works fine in MacOS chrome
* Does not work on WIndows Chrome 100
* Works fine on Windows Edge 
_No response_

**Comment by yogeshgadge** [comment] 2022-05-02 22:13
Works fine on macOS not windows

**Comment by yogeshgadge** [comment] 2022-05-03 15:06
Problems may be due to GPO policies

**Comment by mjhenkes** [comment] 2022-05-05 14:47
@yogeshgadge, I followed your reproduction steps but was unable to recreate the issue.

The test ran correctly in chrome 101, edge 101, and firefox 95.

**Comment by mjhenkes** [comment] 2022-05-12 20:07
@yogeshgadge, I'm going to go ahead and close this issue. I'm unable to reproduce it in my windows vm. If you're able to provide steps to reproduce we'd be happy to reopen this issue in the future.

**Closed by mjhenkes** 2022-05-12 20:07 UTC
Labels: stage: awaiting response
