### ISSUE TITLE
Retry on all retry-compatible commands, not just the last one

### ISSUE THREAD

**Issue by miklosme** [cypress-io/cypress#4320] opened 2019-05-28 14:06 UTC
### Current behavior:

```js
    const getFoo = state => state.foo;
    it('compose retrying commands', () => {
        cy.window().then(window => {
            setTimeout(() => {
                window.foo = { bar: true };
            }, 2000);
        });
        cy.window()
            .pipe(getFoo)
            .its('bar')
            .should('be.true'); // fails because `its` will retry on `undefined`
    });
```

### Desired behavior:

I have some selector functions (think of Redux selectors) to use with `cypress-pipe`, and I'd like to be able to use `.its` with them. Because I'm depending on pipe's retrying nature, right now it's not possible to use these two commands together.

I know about the "only the last command will retry" restriction, but maybe some simple commands like `its` should be an exception.

### Versions

`v3.3.1`

**Comment by fr0** [comment] 2019-05-28 14:35
Possible duplicate of #3561

**Comment by miklosme** [comment] 2019-05-28 15:44
> Possible duplicate of #3561

I agree, seems duplicate.

**Comment by jennifer-shehane** [comment] 2019-05-28 16:09
Closing as duplicate. 

There's also been some recent work done specifically around `.its()` retry behavior. I'd suggest checking those issues out:

- https://github.com/cypress-io/cypress/pull/3226
- https://github.com/cypress-io/cypress/issues/1531

**Closed by jennifer-shehane** 2019-05-28 16:09 UTC
