### ISSUE TITLE
Firefox68 Beta cannot load page

### ISSUE THREAD

**Issue by JoyCJay** [cypress-io/cypress#7826] opened 2020-06-26 07:50 UTC
### Current behavior:
![image](https://user-images.githubusercontent.com/32035698/85833352-e3e81480-b791-11ea-81a2-e9731adfc5c9.png)
Firefox68 Beta cannot load page but works well in chrome, edge and electron

### Desired behavior:

![image](https://user-images.githubusercontent.com/32035698/85833700-725c9600-b792-11ea-8aad-671ac6ef13eb.png)

### Versions

Cypress: 4.8.0
OS: win10
Browser: Firefox68 Beta

**Comment by jennifer-shehane** [comment] 2020-06-26 11:55
You're sure this is Firefox 68 beta? What does it say in the About info? Because 68 beta is over a year old. We don't generally guarantee browser support for versions that are not current.

**Comment by JoyCJay** [comment] 2020-06-26 14:33
![image](https://user-images.githubusercontent.com/32035698/85868424-8a500c00-b7ca-11ea-9968-916ca3a4f361.png)

l've updated firefox version to 77 beta, but still in the same case.

**Comment by jennifer-shehane** [comment] 2020-07-02 08:31
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-02 08:31 UTC
Labels: stage: awaiting response
