### ISSUE TITLE
"Whoops, there is no test to run" when an specific URL is loaded.

### ISSUE THREAD

**Issue by Santiagodh88** [cypress-io/cypress#7122] opened 2020-04-23 15:25 UTC
### Current behavior:

When I try to open "https://givingassistant.org/', cypress crashes indicating "Whoops, there is no test to run". It happens only with this URL. Any other works correctly. I'm just trying to do a simple cy.visit of the URL
Also, every site I try to access using Cypress is marked as Not Secured. 

Spec with the bug: `givva.spec.js`
Important files:

- https://github.com/Santiagodh88/givva/blob/master/cypress.json
- https://github.com/Santiagodh88/givva/blob/master/cypress/integration/example_mine/givva.spec.js
- All my code: https://github.com/Santiagodh88/givva
- URL that causes the error: https://givingassistant.org/
- Video of the error: https://share.getcloudapp.com/geuWWel5

Note: I added a lot of Blacklisted URLs to see if any of this was causing the error but it did not fix the problem

### Versions
Latest Cypress, Windows 10, Chrome Version 81.0.4044.122 (Official Build) (64-bit)>

**Comment by jennifer-shehane** [comment] 2020-04-28 08:49
Duplicate of #3077 Understanding a workaround for this, we'd need to understand the mechanism behind the website that prevents itself from running within the Cypress iframe.

**Closed by jennifer-shehane** 2020-04-28 08:49 UTC
Labels: topic:  😳whoops there is no test to run
