### ISSUE TITLE
Stub assertion fails, despite stub being called, plus stub fake is called many other times

### ISSUE THREAD

**Issue by tuzmusic** [cypress-io/cypress#8545] opened 2020-09-10 17:26 UTC
### Current behavior:

Stubbing a function, providing a logging fake for confirmation, fails an assertion that it's been called.
The console logs confirm that it has indeed been called, although the real function is also called. Unexpectedly, the fake function is called 4 times

### Desired behavior:

The real function is not called, stub is called once, and passes the assertion as such.

### Test code to reproduce

`foo.ts`
```ts
export function callingFunction() {
  calledFunction()
}

export function calledFunction() {
  console.log('hello from real')
}'
```

`some.spec.ts`
```ts
/// <reference types="cypress"/>

import * as functions from './foo';

describe('should work', () => {
  it('should stub it', () => {
    cy.stub(functions, 'calledFunction', () => console.log('hello from fake'));
    console.log('calling function:')
    functions.callingFunction();
    console.log('asserting:')
    expect(functions.calledFunction).to.have.been.called;
  });
});
```
Result:
![image](https://user-images.githubusercontent.com/22814728/92771632-0b9a5200-f369-11ea-83c5-fc6a30a35234.png)

### Versions

macOS 10.15.6
Cypress 5.1
Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by flotwig** [comment] 2022-02-03 21:20
Cannot reproduce this 5x behavior in latest Cy:
![image](https://user-images.githubusercontent.com/1151760/152430543-33840dc1-eca9-4dd4-b568-d2be86f1dc48.png)

Since this has to do with exports, I'm guessing this is most likely an issue with not stubbing the same object reference. See Sinon's "How to stub a dependency" for a discussion on this subject: https://sinonjs.org/how-to/stub-dependency/

Closing since cannot reproduce, and how to use stubs is out of scope for this repo.

**Closed by flotwig** 2022-02-03 21:20 UTC
