### ISSUE TITLE
[cy.origin] The command was expected to run against origin (3th) but the application is at origin (2nd).

### ISSUE THREAD

**Issue by tomaskytommy** [cypress-io/cypress#25255] opened 2022-12-22 16:57 UTC
### Current behavior

Test (from given code) works only in Firefox browser. On Electron (and other chromium browsers) it stucks at origin2 page, which results in error: 'The command was expected to run against origin _(3th)_ but the application is at origin _(2nd)_.'
Last time it worked in electron was in 10.8.0 version.

Recreated problem using website found on the internet with multiple redirects to different domains: 
Repro: [https://github.com/tomaskytommy/cy-issue](url)

### Desired behavior

The same code should work in all supported browsers.

### Test code to reproduce

```js
it('login', () => {
  const credentials = {
    name: 'abc',
    pwd: 'abc123'
  }
  cy.visit('/');
  cy.origin(origin1, () => {
    // code here, click element etc
  });
  cy.origin(origin2, () => {
    // code here, click element etc
  });
  cy.origin(origin3, { args: credentials }, ({ name, pwd }) => {
    // code here, fill form etc
  });
});
```

### Cypress Version

12.2.0

### Node version

18.12.0

### Operating System

windows 10

**Comment by emilyrohrbough** [comment] 2022-12-23 20:52
@tomaskytommy When I try to clone [https://github.com/tomaskytommy/cy-issue](https://github.com/orgs/cypress-io/projects/9/views/url),  I'm getting this repo no longer exists 😓 . Is it private by chance?

**Comment by tomaskytommy** [comment] 2022-12-23 21:00
> @tomaskytommy When I try to clone [https://github.com/tomaskytommy/cy-issue](https://github.com/orgs/cypress-io/projects/9/views/url), I'm getting this repo no longer exists 😓 . Is it private by chance?

@emilyrohrbough  Yes, it is. I forgot to mention that, sry. Please, check your mail for invitation.

**Comment by emilyrohrbough** [comment] 2022-12-27 13:39
@tomaskytommy I ran the spec you provided and I actually am not seeing successful runs on any browsers, including Firefox. It looks like he second origin block is clicking the first profile card which navigates to the third origin. I am seeing the cypress commands passing for `get().click()`, however the navigation is not occurring. If I manually interview during the test by clicking on the card, the tests pass in all browsers.

I am noticing you are ignoring `(uncaught exception) ReferenceError: redirectUrl is not defined` which is logged immediately after `.click()` and isn't logged when manually clicking. It seems this might be something to dig into on the application side.

**Comment by chrisbreiding** [comment] 2023-01-10 14:23
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by chrisbreiding** 2023-01-10 14:23 UTC
Labels: stage: awaiting response

**Comment by tomaskytommy** [comment] 2023-01-15 13:54
@chrisbreiding @emilyrohrbough Sorry for the delay. I quess cypress is just too fast and redirect url loads too slow on element with onclick event. Adding `cy.wait()` before clicking that element, solves the problem. Probably, between chromium browsers v102 and v108 (all firefox versions works without problems), was a slight change, cuz the same apllication code "works" different in different versions. I havent seen anything suspicious in cypress logs.
Im not sure where exactly the problem is. Waiting for page to fully load all JS solves the problem for me.
Thx, for assistance!
