### ISSUE TITLE
NPM install error: `string` and `indent` should be strings

### ISSUE THREAD

**Issue by joeskeen** [cypress-io/cypress#1898] opened 2018-06-07 16:16 UTC
### Current behavior:

```
$ npm i --save-dev cypress

> cypress@3.0.1 postinstall ~/project/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 3.0.1)

~/project/node_modules/indent-string/index.js:6
                throw new TypeError('`string` and `indent` should be strings');
                ^

TypeError: `string` and `indent` should be strings
    at module.exports (~/project/node_modules/indent-string/index.js:6:9)
    at renderHelper (~/project/node_modules/listr-update-renderer/index.js:19:16)
    at render (~/project/node_modules/listr-update-renderer/index.js:48:12)
    at Timeout._id.setInterval [as _onTimeout] (~/project/node_modules/listr-update-renderer/index.js:68:4)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.0.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-06-07T16_08_09_677Z-debug.log
```

### Desired behavior:

Successful install

### Steps to reproduce:

`npm i --save-dev cypress`

### Versions

```
$ npm -v
6.1.0

$ node -v
v8.9.3
```

Environtment: both WSL and Windows Command prompt produced the same error for me (Windows 10 latest update)

**Comment by its-eric** [comment] 2018-10-15 11:38
same happening while installing inside a Docker container with

```
$ npm -v  
5.6.0
```

**Comment by austinfox** [comment] 2018-11-21 22:07
I'm experiencing this same issue on Mac OS

Cypress version: 3.1.2
NPM version: 5.10.0
Node version: v8.2.1

The arguments being passed to the "indent-string" module are:

str:  ⠙  Verifying Cypress can run /Users/hiddenforprivacy/Workspace/hiddenforprivacy/src/hiddenforprivacy/node_modules/cypress/dist/3.1.2/mac/Cypress.app

indent: 0

The indent-string module is complaining because the value passed as indent is 0 when it is expecting a string.

**Comment by jennifer-shehane** [comment] 2018-12-03 03:33
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by jennifer-shehane** [comment] 2019-04-24 16:22
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-24 16:22 UTC
Labels: OS: windows, stage: needs information
