### ISSUE TITLE
When I use cypress run --spec cypress/integration/test1/**, become error

### ISSUE THREAD

**Issue by Peggy1012** [cypress-io/cypress#1834] opened 2018-05-31 07:26 UTC
### Is this a Feature or Bug?

Bug

### Current behavior:

When I use `cypress run --spec cypress/integration/test1/**`, become error

### Steps to reproduce:

I have a folder `test1` with three tests a I use `cypress run --spec cypress/integration/test1/**`
I become error 
```
  Running: test1\faxes_spec.js...                                                          (3 of 3)

Oops...we found an error preparing this test file:

  cypress\integration\test1\faxes_spec.js

The error was:

Error: EEXIST: file already exists, mkdir 'C:\Users\Markéta Hloušková\AppData\Roaming\Cypress\cy\production\projects\B2B-649200f1d98906be5059cc457d5b4ef3\bundles\cypress\integration\test1'


This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

### Versions

Cypress: 3.0.1, Win 10

**Comment by jennifer-shehane** [comment] 2018-05-31 16:46
Is this the correct directory where you tests were supposed to run? 
```
C:\Users\Markéta Hloušková\AppData\Roaming\Cypress\cy\production\projects\B2B-649200f1d98906be5059cc457d5b4ef3\bundles\cypress\integration\test1
```

**Comment by brian-mann** [comment] 2018-05-31 16:50
@Peggy1012 can you paste the entire output? It looks like this is `3 of 3` and we'd need to see the entire output...

Also can you set an environment variable that will output all the debugging information for us? It will output a huge stream of data...

```js
set DEBUG=cypress:*
cypress run
```

**Comment by maximilianschmid** [comment] 2018-05-31 21:02
I have two subfolders in my integration folder:
cypress/integration/APP/
cypress/integration/API/

When I run 
> cypress run --spec cypress/integration/APP/**/*

ALL tests run, but I expected that only tests in the APP subfolder would run. 
Is this a bug or intended behaviour? Doesn't the --spec flag support globs?

The --spec feature would be really useful if I could run all tests in different subfolders so I could manually distribute tests across machines. 

cypress 3.0.1 on Mac OS 10.13.4

**Comment by Peggy1012** [comment] 2018-06-04 10:06
@brian-mann 
  Running: test1\faxes_spec.js...                                                          (1 of 3)

Oops...we found an error preparing this test file:

  cypress\integration\test1\faxes_spec.js

The error was:

Error: EEXIST: file already exists, mkdir 'C:\Users\Markéta Hloušková\AppData\Roaming\Cypress\cy\production\projects\B2B-649200f1d98906be5059cc457d5b4ef3\bundles\cypress\integration\test1'



This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Results)

  ┌───────────────────────────────────┐
  │ Tests:        0                   │
  │ Passing:      0                   │
  │ Failing:      1                   │
  │ Pending:      0                   │
  │ Skipped:      0                   │
  │ Screenshots:  0                   │
  │ Video:        true                │
  │ Duration:     0 seconds           │
  │ Spec Ran:     test1\faxes_spec.js │
  └───────────────────────────────────┘


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  C:\Repos\B2B\cypress\videos\test1\faxes_spec.js.mp4 (1 second)

**Comment by jennifer-shehane** [comment] 2018-06-04 14:07
@Peggy1012 Hey, it looks like the `DEBUG` environment variable may not have run with the output, it should print some extra info from `cypress:cli`, etc that looks something like this after running `cypress run`:

```bash
cypress:cli cli starts with arguments ["/Users/jennifer/.nvm/versions/node/v6.5.0/bin/node","/Users/jennifer/Dev/Projects/cypress-example-kitchensink/node_modules/.bin/cypress","run","--spec","cypress/integration/examples/**/*"] +0ms
cypress:cli NODE_OPTIONS is not set +0ms
cypress:cli program parsing arguments +2ms
cypress:cli running Cypress +1ms
cypress:cli parsed cli options { spec: 'cypress/integration/examples/**/*' } +261ms
```

Look into how to set environment variables in Windows [here](http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/) to set  `DEBUG=cypress:*` env var.

**Comment by Peggy1012** [comment] 2018-06-07 13:12
@brian-mann @jennifer-shehane 
cypress:driver emitted: 'config' - with args: {baseUrl: "....", defaultCommandTimeout: 12000, chromeWebSecurity: false, projectId: "gmfqdk", pageLoadTimeout: 80000, …}animationDistanceThreshold: 5arch: "x64"autoOpen: falsebaseUrl: "..."blacklistHosts: nullbrowserUrl: ".../__/"browsers: (2) [{…}, {…}]chromeWebSecurity: falseclientRoute: "/__/"cypressEnv: "production"defaultCommandTimeout: 12000execTimeout: 60000fileServerFolder: "C:\Repos\B2B"fixturesFolder: "C:\Repos\B2B\cypress\fixtures"hosts: nullignoreTestFiles: "*.hot-update.js"integrationExampleName: "examples"integrationExamplePath: "C:\Repos\B2B\cypress\integration\examples"integrationFolder: "C:\Repos\B2B\cypress\integration"isInteractive: trueisNewProject: falseisTextTerminal: falsemodifyObstructiveCode: truemorgan: truenamespace: "__cypress"numTestsKeptInMemory: 50pageLoadTimeout: 80000parentTestsFolder: "C:\Repos\B2B\cypress"parentTestsFolderDisplay: "B2B\cypress"platform: "win32"pluginsFile: "C:\Repos\B2B\cypress\plugins\index.js"port: 55798projectId: "gmfqdk"projectName: "B2B"projectRoot: "C:\Repos\B2B"proxyUrl: "http://localhost:55798"report: falsereporter: "spec"reporterOptions: nullreporterRoute: "/__cypress/reporter"reporterUrl: "...__cypress/reporter"requestTimeout: 5000responseTimeout: 30000screenshotsFolder: "C:\Repos\B2B\cypress\screenshots"socketId: nullsocketIoCookie: "__socket.io"socketIoRoute: "/__socket.io"supportFile: "C:\Repos\B2B\cypress\support\index.js"supportFolder: "C:\Repos\B2B\cypress\support"taskTimeout: 60000testFiles: "**/*.*"trashAssetsBeforeRuns: trueuserAgent: nullversion: "3.0.1"video: truevideoCompression: 32videoUploadOnPasses: truevideosFolder: "C:\Repos\B2B\cypress\videos"viewportHeight: 660viewportWidth: 1000waitForAnimations: truewatchForFileChanges: truexhrRoute: "/xhrs/"xhrUrl: "__cypress/xhrs/"__proto__: Object +0ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "message" +11ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "backend:request" +3ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "automation:request" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "mocha" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "collect:run:state" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "log:added" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "log:changed" +3ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "before:screenshot" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "after:screenshot" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "paused" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run:async" +3ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:after:run" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "run:start" +3ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "run:end" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "viewport:changed" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "config" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "stop" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "url:changed" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "page:loading" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "visit:failed" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "script:error" +10ms
cypress_runner.js:144595 [Violation] 'message' handler took 233ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +198ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +7ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "window:before:load" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run:async" +8ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "resume:next" +6ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "resume:all" +5ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "clear:fixtures:cache" +14ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +0ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "window:alert" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "window:confirmed" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +3ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "stability:changed" +0ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "navigation:changed" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "form:submitted" +10ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "window:before:load" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +7ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "stop" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "runnable:after:run:async" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run:async" +7ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "window:unload" +2ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "test:before:run" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'newListener' - with args: "window:before:load" +1ms
cypress_runner.js:13674 cypress:driver emitted: 'stop' +25ms
cypress_runner.js:13674 cypress:driver emitted: 'script:error' - with args: {type: "BUNDLE_ERROR", error: "Error: EEXIST: file already exists, mkdir 'C:\User…dles\cypress\integration\test1'{newline}{newline}"} +4ms
cypress_runner.js:13674 cypress:driver emitted: 'run:start' +96ms
cypress_runner.js:13674 cypress:driver emitted: 'run:end' +16ms

**Comment by jennifer-shehane** [comment] 2018-06-07 15:19
Err from logs
```
cypress:driver emitted: 'script:error' - with args: {
  type: "BUNDLE_ERROR", 
  error: "Error: EEXIST: file already exists, 
  mkdir 'C:\User…dles\cypress\integration\test1'{newline}{newline}"
}
```

**Comment by jennifer-shehane** [comment] 2018-06-07 15:23
@Peggy1012 Do you have any code within your [`plugins`](https://on.cypress.io/plugins-guide) files?

**Comment by Peggy1012** [comment] 2018-06-13 08:04
@jennifer-shehane  No, I don't have plugins.

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}

**Comment by brian-mann** [comment] 2018-06-20 18:08
@Peggy1012 I believe this is a Windows problem with you not quoting the spec arguments...

Try to do what my comment here says: https://github.com/cypress-io/cypress/issues/1845#issuecomment-394534129

**Comment by brian-mann** [comment] 2018-07-01 00:48
Closing this as I believe quoting the argument fixes everything. Please reopen if that's not the case.

**Closed by brian-mann** 2018-07-01 00:48 UTC
Labels: stage: awaiting response

**Comment by avgalon** [comment] 2022-10-03 16:26
I also get this error for all my tests when running it on docker using jenkins pipeline.
(Run Starting)

[2022-10-03T16:21:49.923Z] 

[2022-10-03T16:21:49.924Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐

[2022-10-03T16:21:49.924Z]   │ Cypress:        9.5.2                                                                          │

[2022-10-03T16:21:49.924Z]   │ Browser:        Chrome 90 (headless)                                                           │

[2022-10-03T16:21:49.924Z]   │ Node Version:   v14.16.0 (/usr/local/bin/node)                                                 │

[2022-10-03T16:21:49.924Z]   │ Specs:          19 found (install/ecommerceplatforms/ecommerce_platforms_filter_ds.spec.js, in │

[2022-10-03T16:21:49.924Z]   │                 stall/marketingplatforms/marketing_platforms_empty_state.spec.js, install/mark │

[2022-10-03T16:21:49.924Z]   │                 etingplatforms/marketing_platforms_filter_ds.spec.js, install/marketingplatfor │

[2022-10-03T16:21:49.924Z]   │                 ms/marketing_platforms_...)                                                    │

[2022-10-03T16:21:49.924Z]   └────────────────────────────────────────────────────────────────────────────────────────────────┘

[2022-10-03T16:21:49.924Z] 

[2022-10-03T16:21:49.924Z] 

[2022-10-03T16:21:49.924Z] ────────────────────────────────────────────────────────────────────────────────────────────────────

[2022-10-03T16:21:49.924Z]                                                                                                     

[2022-10-03T16:21:49.924Z]   Running:  install/ecommerceplatforms/ecommerce_platforms_filter_ds.spec.js               (1 of 19)

[2022-10-03T16:22:11.967Z] 

[2022-10-03T16:22:11.968Z] Oops...we found an error preparing this test file:

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z]   > cypress/integration/install/ecommerceplatforms/ecommerce_platforms_filter_ds.spec.js

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] The error was:

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

[2022-10-03T16:22:11.968Z] 

[2022-10-03T16:22:11.968Z] [object Object]

I use an image with both chrome and cypress preinstalled

**Comment by pbmallapre** [comment] 2022-12-27 05:03
Hi!

I got this error when using github actions. But not when running the test locally. It seems that my page objects are not being read when using GitHub actions
