### ISSUE TITLE
Angular Component Tests: Load assets from component tests

### ISSUE THREAD

**Issue by lydemann** [cypress-io/cypress#24361] opened 2022-10-24 07:26 UTC
### Current behavior

Currently, it is only supported to load assets from HTML but not through HTTP requests eg. when registering icons from Angular Material.

### Desired behavior

We should be able to load assets from an URL like "assets/**" using HTTP requests.

### Test code to reproduce

Create an Angular project with Angular material and have it registering some custom icons using the URL (assets/...) and see it fail with 404.

### Cypress Version

10.10.0

### Node version

v16.14.2

### Operating System

MACOS 12.3.1

**Comment by amehta265** [comment] 2022-10-27 16:23
@lydemann Thank you for posting this issue.
Upon further investigation, I am able to mount `svg` icons located within my `assets/**` directory in my `angular project`.

This is what my test looks like:
![Image](https://user-images.githubusercontent.com/65267668/198344105-8e197030-e51c-4a13-b9a4-937c94979dcd.png)

This is what Cypress looks like when I run the test:
![Image](https://user-images.githubusercontent.com/65267668/198344195-987682ac-e985-4139-a614-7da9b0b23406.png)

Potential things you might want to look into:
- Do you have the correct [loaders](https://webpack.js.org/loaders/) in your `cypress.config` file. Depending on the dev-server you use in the case of `webpack` you need to install specific loaders so that you can preprocess certain types of files. For svg icons you may want to use the [svg-inline-loader](https://v4.webpack.js.org/loaders/svg-inline-loader/) and for other icon extensions you can use [file-loaders](https://v4.webpack.js.org/loaders/file-loader/)
- In certain cases depending on the library you are using, you may need to add a path to your `angular.json` or `angular-cli` file. For more information on that you can look at this: https://github.com/angular/angular-cli/issues/2662#issuecomment-253448448

If these possible solutions do not address your issue it would be very helpful if you could provide a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
Right now there doesn't seem to be enough information to reproduce the problem mentioned specifically on our end.

**Comment by lydemann** [comment] 2022-10-30 08:23
Hi @amehta265 

Thank you, can you share your repo on Github?

**Comment by lydemann** [comment] 2022-10-30 08:25
And I'm talking about using "addSvgIcon" from Angular Material, which is triggering an HTTP request.

**Comment by amehta265** [comment] 2022-10-31 16:22
@lydemann It would be very helpful if you provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. 

Currently, I don't have enough information to go off of. My best guess is that in your `angular.json` file, you should include your other folders that can contain the svg icons, in the `projects.<your-project-name>.architect.build.options.assets` array. This should help you solve your issue.

Providing a reproducible repo on Github would definitely aid in my troubleshooting.
Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

**Comment by lydemann** [comment] 2022-11-03 08:58
@amehta265 

You are right, seems to work.

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/9210691/199681165-8104595c-9237-4feb-bf99-961554b0bd22.png">

**Comment by amehta265** [comment] 2022-11-03 14:11
I am glad it is working!
Closing as resolved.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed as completed by amehta265** 2022-11-03 14:11 UTC

**Comment by lydemann** [comment] 2022-11-04 10:31
So realised it the problem is coming from Nx and it's Cypress runner + component test configuration:

Repo:
https://github.com/lydemann/cypress-assets-bug/tree/nx

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/9210691/199951805-493f86f5-8a5f-4b74-af69-dafd3c3d79a9.png">

Will create an Issue on Nx instead

**Comment by alexandrzavalii** [comment] 2023-01-03 12:25
@lydemann have you been able to identify the issue?

**Comment by lydemann** [comment] 2023-01-18 07:42
It's still a problem when trying to load assets from HTTPClient.
