### ISSUE TITLE
Cypress Hang on launch when chromium is installed on ubuntu

### ISSUE THREAD

**Issue by jbpallingayan** [cypress-io/cypress#7028] opened 2020-04-16 08:35 UTC
### Current behavior:

Cypress hangs CLI and GUI when chromium latest/stable 81.0.4044.92 is installed on your system

### Desired behavior:

should run smoothly even there is chromium installed

### Test code to reproduce

cypress open
cypress run

### Versions

ubuntu 18.04
chromium latest/stable 81.0.4044.92
cypress 4.3 and 4.4
![Screenshot from 2020-04-16 14-15-46](https://user-images.githubusercontent.com/13012053/79433842-32de3480-8000-11ea-8c48-8e12d1ff97c0.png)

**Comment by mightyiam** [comment] 2020-04-16 10:40
Likely duplicate of #7020 .

**Comment by jennifer-shehane** [comment] 2020-04-17 09:34
Duplicate of #7020

**Closed by jennifer-shehane** 2020-04-17 09:34 UTC
