### ISSUE TITLE
Cypress.minimatch returns true, but timeout still happens

### ISSUE THREAD

**Issue by Nasicus** [cypress-io/cypress#9647] opened 2020-12-11 14:29 UTC
### Current behavior

It looks like there's still a bug with intercept or I don't understand what could be wrong ;)
I basically migrated all `cy.route` in our project to `cy.intercept`.
Some tests always fail now, I don't understand why. For me it seems like a bug, but maybe I'm also doing something wrong?

---------------------

First example:

Code
```js
cy.intercept(  'GET',  `**/editor/**?owner=hans@automatix.onmicrosoft.com&state=draft*`).as('getItemsToFinish');
getTaskViewButton('finish', 3).click();
cy.wait('@getItemsToFinish');
```

Minimatch on the console:

```js
Cypress.minimatch(
  '/api/v1/editor/news?owner=hans@automatix.onmicrosoft.com&state=draft',
  '**/editor/**?owner=hans@automatix.onmicrosoft.com&state=draft*'
)

=> true
```

In the test:
![image](https://user-images.githubusercontent.com/1086065/101914967-478dbf00-3bc5-11eb-96b1-50e62ee6e606.png)

![image](https://user-images.githubusercontent.com/1086065/101914935-3e9ced80-3bc5-11eb-821f-410ba3b7a6f3.png)

-----

Second example:

Code
```js
cy.intercept('PUT', `/api/v1/editor/news/42*`).as('update');
getBody().type('{enter}');
cy.wait('@update');
```

Minimatch on the console:

```js
Cypress.minimatch(
  '/api/v1/editor/news/42?createLease=true',
  '/api/v1/editor/news/42*'
)

=> true
```

In the test:

![image](https://user-images.githubusercontent.com/1086065/101916726-a05e5700-3bc7-11eb-8e17-aa22af0cd0a1.png)

![image](https://user-images.githubusercontent.com/1086065/101916692-93d9fe80-3bc7-11eb-906e-347d8189c959.png)

### Versions

Version: `6.1.0`

**Comment by jennifer-shehane** [comment] 2020-12-14 08:17
Thanks for opening an issue. Duplicate of https://github.com/cypress-io/cypress/issues/9379 

There is an explanation of how the current implementation works here: https://github.com/cypress-io/cypress/issues/9379#issuecomment-742004697 but we do intend to update this to work how it previously did in cy.route().

**Closed by jennifer-shehane** 2020-12-14 08:17 UTC
