### ISSUE TITLE
Assertion keeps spinning after passing

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3144] opened 2019-01-16 15:48 UTC
Quite an esoteric test case, but shows some edge case in assertion state management

Cypress 3.1.4 on Mac

Source code in https://github.com/bahmutov/retry-task-demo just clone, install and run

I am retrying a function that calls either a simple async promise-returning function or a function that calls `cy.task`. In both cases little utility function `retry` checks the upcoming assertion to stop.

```js
const getRandomNumber = () => {
  return new Cypress.Promise((resolve, reject) => {
    setTimeout(() => {
      const x = Cypress._.random(0, 50)
      console.log('resolving with %d', x)
      resolve(x)
    }, 10)
  })
}

const retry = fn => () => {
  return fn().then(value => {
    return cy.verifyUpcomingAssertions(
      value,
      {},
      {
        onRetry: retry(fn)
      }
    )
  })
}

it('retries task', () => {
  let counter = 0
  const limit = 100
  const printToTerminal = () => cy.task('print', (counter += 1), { log: false })

  // cypress-pipe does not retry Cypress chains
  // cy.document()
  //   // .pipe(printToTerminal)
  //   .should('equal', limit)

  cy.log('retrying task')
  cy.then(retry(printToTerminal)).should('equal', limit)

  cy.log('retrying async random number')
  cy.then({ timeout: 10000 }, retry(getRandomNumber)).should('equal', 10)
})
```

The `getRandomNumber` retries itself fine and stops, and the assertion is green.

The `printToTerminal` that calls `cy.task` runs, retries, passes - but the assertion is still spinning in the UI

![retry-task](https://user-images.githubusercontent.com/2212006/51260425-41144f80-197c-11e9-96b7-f6117265390e.gif)

**Comment by Saibamen** [comment] 2019-01-16 18:59
Confirmed in Cypress 3.1.4 running on Win 10 both Chrome 71 and Electron 59

**Comment by jennifer-shehane** [comment] 2019-07-12 07:19
Closing as duplicate of https://github.com/cypress-io/cypress/issues/2380

**Closed by jennifer-shehane** 2019-07-12 07:19 UTC
Labels: stage: needs investigating
