### ISSUE TITLE
Pseudo query parameters are being removed from the hash fragment

### ISSUE THREAD

**Issue by mknookppw** [cypress-io/cypress#8822] opened 2020-10-13 08:16 UTC
### Current behavior
When using the HashLocationStrategy in Angular, Angular uses pseudo query parameters. The query parameters are appended to the hash fragment. However, for some reason Cypress removes everything following the question mark inside the hash.

The output of the test with the expected result:
![image](https://user-images.githubusercontent.com/33869125/95833728-55959f80-0d3c-11eb-9200-8f94c66c07be.png)

When referring to the URI standards (https://tools.ietf.org/html/rfc3986#section-3.5), we can see that it's allowed to use such patterns.

>The characters slash ("/") and question mark ("?") are allowed to
>represent data within the fragment identifier.  Beware that some
>older, erroneous implementations may not handle this data correctly
>when it is used as the base URI for relative references (Section
>5.1).

### Desired behavior
Keep the hash fragment as is.

### Versions
Cypress: 5.3.0
OS: Windows 10
Browser: Chrome Canary 88.0.4290.0

**Comment by jandppw** [comment] 2020-10-13 08:27
BTW, given url `http://localhost:4200/index.html#/license?cloud=1&clientId=135`

- `cy.location('hash')` also returns the fragment with the `?…` part stripped (`'#/license'`)
- `cy.location('search')` is empty

Furthermore, after the click on `#add-button`, the URL shown in the test output visualization has the `?…` part stripped too (`http://localhost:4200/index.html#/license`). When using the SPA outside cypress, the URL is as expected.

**Comment by jennifer-shehane** [comment] 2020-10-14 05:44
This `cy.location('hash')` returns the correct URL when directly visiting a `http://localhost:4200/index.html#/license?cloud=1&clientId=135` page for me. 

```js
// Create a blank index.html page to visit.
it('passes', () => {
  cy.visit('index.html#/license?cloud=1&clientId=135')
  cy.location('hash').should('eq', '#/license?cloud=1&clientId=135') // passes
})
```

<img width="1037" alt="Screen Shot 2020-10-14 at 12 10 38 PM" src="https://user-images.githubusercontent.com/1271364/95948436-8cd87f00-0e16-11eb-8166-f83959dfdbde.png">

It seems that within Cypress, the url is navigating to a page without the query params for some reason after clicking the 'add-button'. 

We'll need more information and a reproducible example to narrow down why that may be happening. Make sure to check your console log for any errors that may be thrown.

**Comment by jandppw** [comment] 2020-10-14 11:05
After some more experimenting, trying to find the core issue, here are some more observations and context.

We use "pseudo-query parameters" to communicate parameters that have to be filled in in create mode of an entity detail card, coming from the "+" button of a list that represents a parent-child relationship. Usually, this the id of the parent, which must be filled in in the new child entity.

These are "pseudo-query parameters", because they are formally part of the URL fragment (aka, the hash), because we use hash routing (for reasons). Angular supports this, and there is no formal issue with this, since the RFC says "?" is allowed in URL fragments ([RFC 3986, "Uniform Resource Identifier (URI): Generic Syntax", "3. Syntax Components", "3.5 Fragment"](https://tools.ietf.org/html/rfc3986#section-3.5)):

> The characters slash ("/") and question mark ("?") are allowed to represent data within the fragment identifier. […]

Obviously, we checked that this works as expected when we use the app "manually".

The verification code below works "most of the time" on macOS and Bitbucket Pipelines, with Chrome Canary, and Electron, resp., but fails "always" on Windows with Chrome Canary. We currently have 5 situations where we test this, and some occasionally fail on macOS, one or another almost always fails on Bitbucket Pipelines (no run has passed completely until now), and we have never seen any instance pass on Windows.

```
/**
 * Creates pairs, with the property name in odd positions, and the values in even positions after the property name
 * @type {RegExp}
 */
const queryParametersPattern = /^(?:(.+?)=(.+?))(?:&(?:(.+?)=(.+?)))*$/;

function pseudoQueryParams(pseudoQuery) {
  const matches = queryParametersPattern.exec(pseudoQuery);
  return matches
    ? matches.reduce((acc, v, i, arr) => {
        if (i > 0 && i % 2 === 0 && !!arr[i - 1]) {
          acc[arr[i - 1]] = v;
        }
        return acc;
      }, {})
    : {};
}

[…]

    it('navigates to detail creation when the "+" is clicked', function () {
      cy.get('[data-cy=toManyList]')
        .should('be.visible')
        .within(() => {
          cy.get('#add-button').click();
          cy.hash()
            // we need to wait here for the route, it seems; without this, the test becomes flaky (**)
            .should('contain', Object.keys(createParams).length > 0 ? `${detailRoutePrefix}?` : detailRoutePrefix) 
            .then((hash) => {
              const parts = hash.split('?');
              expect(parts[0]).to.equal(detailRoutePrefix);
              const params = pseudoQueryParams(parts[1]);
              expect(params).to.deep.equal(createParams);
            });
        });
```

A typical execution would have, e.g.,

```
detailRoutePrefix = '#/client/2'
createParams = { parentId: '' + parentPersistenceId }
```

The `.should` line (**) was added to make the test work "most of the time" on macOS, but might have little or no impact.

This "feels" like a race condition. Maybe Angular adds the pseudo-query parameters to the location async, one by one? We checked this by waiting in the test above explicitly for 5s, but it was not a solution on Windows. Furthermore we scanned Angular code, and as far as we can see the query parameters are _not_ added to the location async, one by one. Stronger, we see that the "route" (i.e., the fragment) is prepared well beforehand, when the card on which the "+" button is shown is               rendered. On click, the location is changed from that prepared "route" in one go.

The problem has never happened when `cy.visit('http://localhost:4200/index.html#/client/2?parentId=135')` is done to get the app to show the create mode of an entity detail card.

To us it seems that Cypress has parsing issues with a change of the location to a location that contains a fragment with pseudo-query parameters, intermittently on macOS and Linux, and always on Windows.

**Comment by pschaub** [comment] 2020-10-14 17:57
In one of our closed projects we have seen race conditions. The website is modifying the URL hash through Javascript.
To bypass this issue in our Cypress tests we are currently using [cypress-wait-until](https://www.npmjs.com/package/cypress-wait-until) to wait until the URL is like expected:
```
cy.waitUntil(() => cy.location().then(location => {
  return location.pathname === '/example-path/' && location.hash === '#exampleHash'
}), {
  errorMsg: 'example error message',
  interval: 1000
});
```

**Comment by jandppw** [comment] 2020-10-15 10:13
Wait, isn't `should` supposed to do that, wait for the situation to appear
(with a timeout)?

Or is what you suggest to do the fragment parsing ourselves, and wait for
that, to work around a parsing issue in Cypress?

Met vriendelijke groeten,

Jan Dockx
CTO
PeopleWare
Duwijckstraat 17, 2500 Lier, Belgium
<https://www.google.com/maps/place/Duwijckstraat+17,+2500+Lier/@51.1521552,4.5342603,17z/data=!3m1!4b1!4m5!3m4!1s0x47c3fb94fdf61a6d:0xbe16a452d3dee30!8m2!3d51.1521552!4d4.536449>
+32 3 448 33 38 <003234483338>
www.peopleware.be
<https://www.linkedin.com/company/peopleware/>
<https://www.facebook.com/PeopleWare.be/> <https://twitter.com/peoplewarebe>
<https://www.instagram.com/peopleware_be/>


Op wo 14 okt. 2020 om 19:57 schreef Patrick Schaub <notifications@github.com

**Comment by jennifer-shehane** [comment] 2020-10-16 09:23
@jandppw Thanks for the investigation. It could be any number of the contributing factors you're mentioning. Can you provide a reproducible example so we can see the failing situation and investigate?

**Comment by jennifer-shehane** [comment] 2021-02-22 14:37
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-22 14:37 UTC
Labels: stage: needs information
