### ISSUE TITLE
Cypress not running tests in Chrome when using --disable-extensions arg

### ISSUE THREAD

**Issue by abias1122** [cypress-io/cypress#8521] opened 2020-09-08 15:34 UTC
### Current behavior:
In order to get around an issue where a Chrome extension was preventing my test from navigating to another page, I tried to run a test with extensions disabled. This caused Cypress to open a new Chrome window (not a test window) and display the following output in the console:
<img width="387" alt="cypress error" src="https://user-images.githubusercontent.com/28871516/92496478-2aacae80-f1c6-11ea-8a66-3cb06c4b2e68.PNG">
Additionally, the following error showed up on the test runner:
<img width="606" alt="cypress error 2" src="https://user-images.githubusercontent.com/28871516/92496661-6ba4c300-f1c6-11ea-96cf-442a930e3e37.PNG">

### Desired behavior:
When I try to run Cypress tests with extensions disabled in Chrome, tests should open up a test window and run.

### Test code to reproduce
In cypress/integrations/*.spec.js
```js
cy.visit(url)
```
In cypress/plugins/index.js
```js
on('before:browser:launch', (browser = {}, options) => {
		if (browser.family === 'chromium' && browser.name !== 'electron') {
			options.args.push('--disable-extensions');}}
```

### Versions
Cypress: 5.1.0
OS: Windows 10 Enterprise
Chrome: 85

**Comment by jennifer-shehane** [comment] 2020-11-03 08:07
I'm not able to reproduce this issue as described. Does this happen every single time you include this plugins code? And the issue stops occurring when you remove the code?

Yeah, we'd recommend not having any extensions installed on the Cypress Chrome browser - this browser is separate from your local Chrome browser. 

Maybe this is specific to Windows?

**Comment by bpskishore** [comment] 2020-12-03 02:59
I faced similar experience, I can share my fix may be you can try

check /etc/hosts file if you are in linux systems or c:\Windows\System32\Drivers\etc\hosts in windows, if entries are blank then you need to add localhost and 127.0.0.1 please check configuration. cypress works using reverse proxy behind scenes

**Comment by jennifer-shehane** [comment] 2021-02-26 23:51
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-26 23:51 UTC
Labels: stage: needs information
