### ISSUE TITLE
Warning: Failed prop type

### ISSUE THREAD

**Issue by JoeEarly** [cypress-io/cypress#6463] opened 2020-02-14 11:58 UTC
### Current behavior:

Getting a new error in the console when running cypress testes. 

> VM3374 index.js:1437 Warning: Failed prop type: Invalid prop `imagesPerPage` of type `string` supplied to `AdminPanel`, expected `number`.
    in AdminPanel (created by Connect(AdminPanel))
    in Connect(AdminPanel) (at Admin.js:21)
    in Provider (at Admin.js:20)
    in Admin (at App.js:33)
    in Route (at App.js:30)
    in Switch (at App.js:11)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:10)
    in App (at src/index.jsx:12)
    in ScreenCloudReactApp (at src/index.jsx:11)

### Desired behavior

No errors in console. (App under test does not display the error outside of Cypress Runner. )

### Test code to reproduce

```js
it("renders the admin panel on screen", () => {
    window.localStorage.setItem("opened", "true");

    cy.visit("/admin").withConfig(config.one);

    cy.get("[data-testid=header-logo]")
      .should("be.visible")
      .and("have.prop", "src")
      .and("contain", "/assets/images/mobile-icon.svg");

    cy.get("[data-testid=header-titles]")
      .should("be.visible")
      .and("have.length", "1");
  });

```
![Screenshot 2020-02-14 at 11 58 27](https://user-images.githubusercontent.com/5208459/74530155-5235e400-4f21-11ea-9fe4-0fc63867fc76.png)

### Versions
**Cypress:**  3.8.3
**OS:** Mac 10.15.2
**Node:** 11.4.0

**Comment by jennifer-shehane** [comment] 2020-02-18 05:12
If your test is dependent on this localStorage being set, you'll need to set it on the window of your application. As this is written, this is writing to the Cypress window's localStorage.

```js
it("renders the admin panel on screen", () => {
  cy.window().then((win) => {
    win.localStorage.setItem("opened", "true");
  })   
});
```

Outside of that, I can't say why your application is throwing this error since I can't run the code provided. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-18 05:12 UTC
