### ISSUE TITLE
Cypress 1.4.0 - Dashboard do not update when run is aborted locally

### ISSUE THREAD

**Issue by chit786** [cypress-io/cypress#1102] opened 2017-12-20 14:04 UTC
- Operating System: Mac OS High Sierra
- Cypress Version: 1.4.0
- Browser Version:

### Is this a Feature or Bug?
Bug

### Current behavior:
![image](https://user-images.githubusercontent.com/18376182/34210578-9fbeb536-e596-11e7-902b-66190a4440c9.png)

### Desired behavior:
If tests are aborted/ stopped locally , dashboard runs should get stopped and provide appropriate result.

### How to reproduce:
- install cypress 1.4.0
- Run a test with misconfigured baseurl (with passing correct remote key to upload the result)
- Cypress prompts that URl is misconfigured and stops execution
- Check the runs in Dashboard, i's same as above screenshot

**Comment by brian-mann** [comment] 2017-12-20 15:12
It should already do this. Whenever a run exits early due to an error that prevents the tests from starting we check that.

Possibly a regression here.

**Comment by chit786** [comment] 2017-12-23 11:03
Currently it do not. Although it timeouts after nearly 2 hours.

**Comment by maxTadmor** [comment] 2018-09-06 20:16
Is there any update on this? I am experiencing the same, local run aborted long time ago, but dashboard one continues to show as running

**Comment by jennifer-shehane** [comment] 2018-10-20 20:01
This should be fixed (going past 90 minutes), but there is an issue to have this be more responsive here: https://github.com/cypress-io/cypress/issues/2630

**Closed by jennifer-shehane** 2018-10-20 20:01 UTC
Labels: stage: needs investigating

**Comment by jorgeautomation** [comment] 2019-04-25 17:15
@maxTadmor how do you abort a cypress run locally? Please let me know, thanks!

**Comment by jennifer-shehane** [comment] 2019-04-26 06:37
@jorgeautomation Any cancelled runs are cleaned up and closed every 90 minutes.

More thorough issue for cancelled runs is here: https://github.com/cypress-io/cypress/issues/1691
