### ISSUE TITLE
Asserts with asterisks or understrokes becomes bold/italic in the Command Log

### ISSUE THREAD

**Issue by Regnander** [cypress-io/cypress#7419] opened 2020-05-19 15:55 UTC
### Current behavior:

Any pair of asterisks or understrokes inside asserts will not show up in the Command Log, but will instead cause the containing text to be italic or bold, respectively.

![image](https://user-images.githubusercontent.com/17113053/82333474-1199ab00-99e7-11ea-84a9-87c2afef311d.png)

### Desired behavior:

I want to be able to see the asterisks and understrokes in my asserts.

### Test code to reproduce

````js
context('aaa', () => {
    it('bbb', () => {
        expect('abcdef__').to.match(/.*abcdef__/) // Not affected
        expect('*abcdef*').to.equal('*abcdef*') // Will be italic
        expect('abcdef').to.match(/.*abcdef.*/) // Will also be italic
        expect('__*abcdef*__').to.match(/__.*abcdef.*__/) // Will be bold and italic
    })
})
````

### Versions

Cypress 4.5.0
Windows 10
Electron 80

**Comment by jennifer-shehane** [comment] 2020-05-20 08:01
Duplicate of #5679

**Closed by jennifer-shehane** 2020-05-20 08:01 UTC
