### ISSUE TITLE
cy.then() passing zetpo object to callback function if the SUT uses zepto library

### ISSUE THREAD

**Issue by Ayase-252** [cypress-io/cypress#7917] opened 2020-07-08 08:36 UTC
### Current behavior:

When website uses Zepto library, the `cy.then()` will convert a jQuery object into a Zepto object, if it is chained with a command which should resolved as a jQuery object.

For example, we have a html as following:

```html
 <body>
    hello world
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js"></script>
 </body>
```

and a test case try to make a screenshot of `body` element:

```javascript

cy.get("body").then(($el) => {
   // `$el` is a zepto object now, the following will fail because $el is not a valid jQuery object
   cy.wrap($el).screenshot();
});

```

Run the test case, it shows

![截屏2020-07-08下午4 21 10](https://user-images.githubusercontent.com/6264033/86895480-1bae6f00-c137-11ea-884a-e7c548cb1b65.png)

### Desired behavior:

The above case should run without issue

### Test code to reproduce

https://github.com/Ayase-252/cypress-zepto-issue

### Versions

Cypress 4.10
OS: macOS 10.15.3
Chrome 83

### Note

I think this issue is similiar to issue #6529. And, some plugins use the coding pattern as above, therefore, they are broken in a very confusing way.

After digging into the code, I find that the problem may arise in [there](https://github.com/cypress-io/cypress/blob/993302757cc9871c8a1a7da9e54bcf191e93d0e1/packages/driver/src/cy/jquery.js#L17). The `remoteJQuery` is actually a `Zepto`. therefore, the `remoteSubject` is a zepto object with a jquery passing in.

But I am not familiar with the context of code, could you please look into this issue?

**Comment by jennifer-shehane** [comment] 2020-07-09 04:26
Yah, this looks to be a duplicate of https://github.com/cypress-io/cypress/issues/6529 I'll comment in that issue regarding thoughts on why this is happening. 

Duplicate of #6529

**Closed by jennifer-shehane** 2020-07-09 04:26 UTC
