### ISSUE TITLE
Position: fixed, partially superposed divs, determined as not visible

### ISSUE THREAD

**Issue by nerfologist** [cypress-io/cypress#3369] opened 2019-02-07 11:00 UTC
Hello, I'm developing a simple mobile layout based on a side menu and a backdrop.

Backdrop has:
```
position: fixed;
width: 100%;
height: 100%;
top: 0;
left: 0;
```

Drawer has:
```
position: fixed;
width: 70%;
height: 100%;
top: 0;
right: 0;
```

Here's the test
```js
describe('Backdrop and side drawer layout', () => {
  it('recognizes both elements as visible', () => {
    cy.visit('https://507owq3644.codesandbox.io/');
    cy.get('[data-testid="side-drawer"]').should('be.visible');
    cy.get('[data-testid="backdrop"]').should('be.visible');
  });
});
```

### Current behavior:

The test fails with the following error:
```
CypressError: Timed out retrying: expected '<div#backdrop>' to be 'visible'

This element '<div#backdrop>' is not visible because it has CSS property: 'position: fixed' and its being covered by another element:

<div id="side-drawer" data-testid="side-drawer">side dr...</div>
```
### Desired behavior:

The test should recognize both elements as visible, as the drawer **is only partially covering the backdrop**.

### Steps to reproduce: (app code and test code)

The described layout can be found here: https://codesandbox.io/s/507owq3644

The test code is included in the description.

### Versions

Cypress: 3.1.5
Operating system: macOS High Sierra 10.13.6
Browser: Version 72.0.3626.96 (Official Build) (64-bit)

Thanks for your work! 👍

**Comment by jennifer-shehane** [comment] 2019-04-25 08:24
Thank you for providing a reproducible example!

**Comment by jennifer-shehane** [comment] 2019-04-26 08:16
Hey @nerfologist Any reason for closing this issue? The error is still reproducible as of yesterday.

**Comment by nerfologist** [comment] 2019-04-26 08:30
@jennifer-shehane sorry I probably closed by mistake while checking your answer on my mobile device (I'm clumsy) and obviously failed to notice it. Reopening!

**Comment by jennifer-shehane** [comment] 2019-06-10 09:01
So, I've taken a look at this issue on visibility of the lefthand sidebar. 

This one is a bit tricky. Asserting that the entire #backdrop element is visible is.....kind of untrue. Since the element expands the entire width of the page, truly 70% of that element *is* being covered by another element. So, should Cypress determine that element as visible truly?

What will be a more accurate test will be testing the elements within the #backdrop sidebar. For example, you can see below, I have a `<span>VISIBLE</span>` and `<span>NOT VISIBLE</span>` within the #backdrop where the spans are visible and not visible respectively. If you do use Cypress to assert the visibility of these elements *within* the #backdrop, Cypress returns the correct results. 

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <div id="backdrop" style="width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.3); position: fixed; top: 0; left: 0;">
    <span>VISIBLE</span>
    <span style="position: absolute; left: 500px;">NOT VISIBLE</span>
  </div>
  <div id="side-drawer" style="width: 70%; height: 100%; background-color: palevioletred; position: fixed; top: 0; right: 0;">side drawer</div>
</body>
</html>
```

```js
it('recognizes elements within backdrop as visible or not', () => {
  cy.visit('index.html');
  cy.get('#backdrop>span').first().should('be.visible');
  cy.get('#backdrop>span').last().should('be.visible');
});
```

While I do not consider this a *bug* in Cypress, I would qualify this as unexpected behavior. I think this can be improved upon within the issue where we will print reasons why we qualify something as not visible: https://github.com/cypress-io/cypress/issues/677

I will be closing this issue and adding a note in the above linked issue to handle messaging around elements that are partially visible.

**Closed by jennifer-shehane** 2019-06-10 09:01 UTC
Labels: pkg/driver, stage: ready for work, topic: visibility 👁

**Comment by nerfologist** [comment] 2019-06-10 09:41
Hello and thanks for your detailed analysis @jennifer-shehane, it makes sense and I agree with your observations.
