### ISSUE TITLE
cypress 3.1.1 open fails

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2797] opened 2018-11-18 20:10 UTC
Hi,
I'm running under windows 10 pro
with node 11.2 installed
with C++ Redistributable for Visual Studio 2015 installed
with C++ Redistributable for Visual Studio 2017 installed

On cypress 3.1.1 open command I have the following error :
```
C:\nodejs\node_modules\project>npx cypress open
  cypress:cli cli starts with arguments ["C:\\nodejs\\node.exe","C:\\nodejs\\node_modules\\cypress\\bin\\cypress","open"] +0ms
  cypress:cli NODE_OPTIONS=--trace-warnings +0ms
  cypress:cli program parsing arguments +16ms
  cypress:cli opening Cypress +0ms
  cypress:cli parsed cli options {} +115ms
  cypress:cli opening from options {"project":"C:\\nodejs\\node_modules\\project"} +0ms
  cypress:cli command line arguments ["--project","C:\\nodejs\\node_modules\\project"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress\Cypress.exe +0ms
  cypress:cli Binary is executable? : true +0ms
  cypress:cli binaryDir is  C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress +0ms
  cypress:cli Reading binary package.json from: C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 3.1.1 installed in: C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress +16ms
  cypress:cli could not read binary_state.json file +16ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +0ms
  cypress:cli running binary verification check 3.1.1 +0ms
It looks like this is your first time using Cypress: 3.1.1

  cypress:cli clearing out the verified version +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress\Cypress.exe +0ms
  cypress:cli needs XVFB? false +0ms
  cypress:cli smoke test command: C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress\Cypress.exe --smoke-test --ping=934 +0ms
 \  Verifying Cypress can run C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress
  cypress:cli Smoke test failed: { Error: Command failed: C:\Users\glour\AppData\Local\Cypress\Cache\3.1.1\Cypress\Cypress.exe --smoke-test --ping=934



    at makeError (C:\nodejs\node_modules\execa\index.js:172:9)
    at Promise.all.then.arr (C:\nodejs\node_modules\execa\index.js:277:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  code: 3221225477,
  stdout: '\r\n',
  stderr: '',
  failed: true,
  signal: null,
  cmd:
   'C:\\Users\\glour\\AppData\\Local\\Cypress\\Cache\\3.1.1\\Cypress\\Cypress.exe --smoke-test --ping=934',
  timedOut: false,
```
Can I have some help please ?

**Comment by jennifer-shehane** [comment] 2018-11-19 19:17
duplicate of https://github.com/cypress-io/cypress/issues/1866

**Closed by jennifer-shehane** 2018-11-19 19:17 UTC

**Comment by jennifer-shehane** [comment] 2019-07-01 08:50
In order to direct better focus on the overall problem that is being described in several issues - we opened one issue to track this behavior https://github.com/cypress-io/cypress/issues/4624 Please add any information about how we can reproduce this bug there. 🙏
