### ISSUE TITLE
How to delete cookies from all domain after running tests of a single Feature File

### ISSUE THREAD

**Issue by eGoudi** [cypress-io/cypress#6676] opened 2020-03-08 20:57 UTC
Hi,
I'm working on a web project. I use cypress to do my tests.

    Cypress version 3.8.2
    Cypress preprocessor : 2.0.1 (j'utilise Gherkin cucumber)
    J'utilise Mac book (OS) : 8 Go
    _ Node version: 10.7.0

I have the following features:

<img width="433" alt="Capture d’écran 2020-03-08 à 16 22 27" src="https://user-images.githubusercontent.com/58534476/76171046-ae3e0200-6187-11ea-8b28-b17c09b5c654.png">

So I am able to run the tests in a file (.feature).

For example: when I run the tests which is in 01TestCaseprofileAdminRightAccess.feature
The scenarios are executed without problem.

And then if I want to launch the tests which are in 02TestCaseprofileAdminRightAccess.feature the browser is displayed and crashes (no test scenario is executed).

So I have to delete cookies by hand so that cypress can run the tests.

List of cookies:

<img width="656" alt="Capture d’écran 2020-03-08 à 16 34 09" src="https://user-images.githubusercontent.com/58534476/76171058-c1e96880-6187-11ea-8943-d4e4b511279b.png">

So my question is: Is there a way to tell Cypress to delete all cookies from the domains auth0, SSO, .com?

I have seen clearCookies () and even clearCookies ({domain: null}) and I added them each at the end of the scenario believing that it would solve the problem but nothing.

**Comment by eGoudi** [comment] 2020-03-08 21:25
I add information here is a screenshot when I add Cypress.debug in my login command.

<img width="1427" alt="Capture d’écran 2020-03-08 à 22 12 37" src="https://user-images.githubusercontent.com/58534476/76171365-ae8bcc80-618a-11ea-9d71-6ece14e51e6d.png">


dans ma command login j'ai ajouté le debug et le clearcookies . J'ai paramétré tout ce qui est authentifiacation auth0:
cypress/support/command.js: 

<img width="603" alt="Capture d’écran 2020-03-08 à 22 20 00" src="https://user-images.githubusercontent.com/58534476/76171420-8781ca80-618b-11ea-89ca-6f03ab1ee7ec.png">


How to delete that cookies using cypress ?

**Comment by jennifer-shehane** [comment] 2020-03-10 06:55
Passing `{domain: null}` should work for clearing cookies across domain. 

Duplicate of #408 - see that thread for any existing workarounds.

**Closed by jennifer-shehane** 2020-03-10 06:55 UTC

**Comment by eGoudi** [comment] 2020-03-10 10:35
Sorry, it doesn't work for me when I pass {domain: null} as argument (see fourth line in my command.js code). I finally activate this : 

<img width="707" alt="Capture d’écran 2020-03-10 à 11 32 05" src="https://user-images.githubusercontent.com/58534476/76303963-d54d1e80-62c2-11ea-81a2-3a19b47d397d.png">

To allow the browser to clean all cookies. 

Right I can't run all specs:
I get the following warning : 

GET /__cypress/tests?p=cypress/support/index.js-453 200 11.577 ms - -
HEAD / - - ms - -
HEAD / - - ms - -
HEAD / - - ms - -
GET /__cypress/tests?p=cypress/integration/01AdministrationTask/administrationtask.feature-981 200 17011.749 ms - -
GET /__cypress/tests?p=cypress/integration/02AccessManagement/02TestCaseprofileIssuerRightAccess.feature-995 200 16994.752 ms - -
GET /__cypress/tests?p=cypress/integration/02AccessManagement/00TestCaseForVisitor.feature-741 200 17010.527 ms - -
GET /__cypress/tests?p=cypress/integration/02AccessManagement/01TestCaseprofileAdminRightAccess.feature-412 200 17001.914 ms - -
GET /__cypress/tests?p=cypress/integration/02AccessManagement/03TestCaseprofileOriginatorRIghtAccess.feature-016 200 16999.539 ms - -
GET /__cypress/tests?p=cypress/integration/02AccessManagement/04TestCaseprofileDealerRightAccess.feature-258 200 17004.824 ms - -
(node:1393) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:1393) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:1423) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:1423) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit.
And the following crash:


<img width="1138" alt="Capture d’écran 2020-03-10 à 11 35 05" src="https://user-images.githubusercontent.com/58534476/76304183-370d8880-62c3-11ea-8454-6833c9d445dc.png">

**Comment by jennifer-shehane** [comment] 2020-03-11 11:11
@eGoudi The `MaxListenersExceededWarning` is just a warning and should not be affecting your test run. It can be ignored. https://github.com/cypress-io/cypress/issues/1305

The plugins error does not look related to the originally opened cookies issue. If you're still experiencing this error - open a new issue with the contents of your `plugins/index.js` file.
