### ISSUE TITLE
Reach Router test failing consistently in Chrome when window loses focus and visibility

### ISSUE THREAD

**Issue by danieltott** [cypress-io/cypress#8085] opened 2020-07-24 15:12 UTC
### Current behavior:

In headed mode with Chrome 84 and MacOS, using React and [Reach Router](https://github.com/reach/router), having cypress `click()` on a `<Link>` when the browser window is not visible results in cypress not being able to find content on the resulting route. The browser window must be completely hidden (either by another tab, another app, minimizing, or switching to a new Space). The test fails with `Timed out retrying: Expected to find element: .dashboard, but never found it.`

In the test runner, when you go back to the window, the route has updated and the content seems visible, but cypress timed out finding it. Hovering over the snapshots shows the new url in the expected place in the url bar, but not the new content.

Post run:
![image](https://user-images.githubusercontent.com/360261/88406220-5e5e8100-cd9e-11ea-941d-3c44fc132618.png)

Snapshot after click:
![image](https://user-images.githubusercontent.com/360261/88406281-759d6e80-cd9e-11ea-8848-34d12760501c.png)

This is probably related to #5023 but in this case I was able to isolate an exact repeatable scenario.

Interestingly, this does _not_ happen if I switch to React Router (5 or 6), only in Reach Router.

This does _not_ happen in electron or headless electron

In Firefox (dev and regular flavor) it just waits to run anything until it's back in focus/visible.

Perhaps this is a bug with Reach Router - I'm not really sure. I know they're doing some focus management, but then again so is Cypress. Feel free to close if this is too close to #5023 or is in fact a reach router bug.

### Desired behavior:

Cypress tests pass without having to have the window in focus

### Test code to reproduce

https://github.com/danieltott/cypress-reach-router-example

I've created a very simple CRA app with reach router and cypress and no customization. The test is simply:

```js
describe('The Home Page', () => {
  it('successfully loads', () => {
    cy.visit('http://localhost:3000');
    cy.get('.dashlink').click();
    cy.get('.dashboard').should('be.visible');
  });
});
```

https://github.com/danieltott/cypress-reach-router-example

Steps:
- run `yarn`
- run `yarn start`
- run `yarn cy:open`
- in the test runner, select Chrome and click "run all specs" or "router-link.spec.js"
- let it run once to verify that is passes
- run it a few more times if you want
- click the run button and quickly switch to another space/app or minimize (using a keyboard shortcut is probably best for this)
- make sure to wait 5 seconds (allow the timeout to pass)
- come back to Chrome and behold your failed test

There are also branches in there for React Router 5 and 6 to verify this behavior does not occur in either of those packages.

### Versions

```json
{
  "dependencies": {
    "@reach/router": "^1.3.4",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "devDependencies": {
    "cypress": "^4.11.0",
    "eslint-plugin-cypress": "^2.11.1"
  }
}
```

MacOS Catalina 10.15.5
Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment] 2020-07-27 04:46
Yeah, it seems as if the DOM doesn't render in Reach Router until the browser window is in focus, which is pretty strange. The URL navigates to the new url, but the content is not rendered. I'm not sure what would be causing this, but I do think this would fall under #5023 

Duplicate of #5023.

**Closed by jennifer-shehane** 2020-07-27 04:46 UTC

**Comment by danieltott** [comment] 2020-07-27 11:58
The funniest part of this is that it _will_ pass if the window is visible but not in focus - even it it's only a little visible. So there may be some OS-level funkiness going on here too. Would be curious to see if this happens on Windows. Either way, it does seem to be of a piece with #5023. Just wanted to provide some specifics and context. Thanks!

**Comment by juanvillegas** [comment] 2020-07-30 21:05
We are having the same issue in our test suite, we are using the Vuejs virtual DOM though, not React's. I will try to provide a reproducible test case.
