### ISSUE TITLE
cy.click() failed because it requires a DOM element in aftereach block

### ISSUE THREAD

**Issue by khaledjawhar** [cypress-io/cypress#8274] opened 2020-08-13 20:53 UTC
### Current behavior:

I am running a bunch of tests in a fixture and from time to time and I am having the failure:
```
cy.click() failed because it requires a DOM element.
``` 

It occured in this line: 

```js
cy.get(Cypress.env('page.commandButton')).click();
```
   

### Desired behavior:

I expect the fixture to always pass without having this flaky result

### Test code to reproduce

```js
context('SomeFixture', () => {
  before(() => {
    cy.visit('')
  })

  beforeEach(() => {
    cy.login(Cypress.env('mUser'), Cypress.env('mPassword'))
    cy.clickButton(Cypress.env('page.memorytab'))
  })

  afterEach(() => {
    cy.reload()
    cy.logout()
  })
  Cypress.Commands.add("logout", () => {
    cy.get(Cypress.env('page.commandButton')).click();
    cy.get(Cypress.env('page.signoutButton')).click();
  })
  //some tests exist here but regardless of what tests exist, the failure is happening always in the after each  block. The failure is not happening in a specific test, it occurs in the after each for various tests. The code above will help reproducing the problem
})
```

**Comment by jennifer-shehane** [comment] 2020-08-14 09:22
`cy.get()` is not returning a DOM element in the case of your test. I can't determine why because I can't run the code provided - there is no app code to run it against.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-14 09:22 UTC

**Comment by khaledjawhar** [comment] 2020-08-14 13:31
I am writing the code against a UI application and not sure how I can post the whole code there. I mean you can't run the cypress test if you don't have the UI running. I am not sure what to classify the problem above and whether it is an issue or a question
