### ISSUE TITLE
No command runs after implementing drag and drop

### ISSUE THREAD

**Issue by Jerry1811** [cypress-io/cypress#24242] opened 2022-10-13 16:16 UTC
### Current behavior

After implementing drag and drop in cypress, any other command that runs afterwards throws the error in the screenshot below

![drag-drop-error](https://user-images.githubusercontent.com/58642285/195650341-67f28a23-7fe5-4de3-b380-c2e53605e63c.png)

### Test code to reproduce

```
cy.get('#tpl-container')
      .trigger('mousedown', { which: 1, pageX: 600, pageY: 100 })
      .trigger('mousemove', { which: 1, pageX: 600, pageY: 600 })
      .trigger('mouseup')

cy.get('[tester-id=perform-Provision]').click()
```

### Cypress Version

10.9.0

### Node version

v16.17.0

### Operating System

Windows 11

**Comment by Ralkage** [comment] 2022-10-13 16:27
To add to @Jerry1811's issue, this also happens when we double-click on an element, and it moves to the left side of our application, rather than performing a drag and drop.

**Comment by AtofStryker** [comment] 2022-10-13 21:19
Hi @Jerry1811 & @Ralkage . Would either of you be able to provide a reproduction repository I can clone/run to reproduce the issue?

**Comment by Ralkage** [comment] 2022-10-18 18:28
@AtofStryker 

Our application is built into an OVA, so it's mostly on-prem.

Do you need access to just the Cypress project we built to run e2e against our application?

**Comment by AtofStryker** [comment] 2022-10-18 19:34
@Ralkage it doesn't have to be your application. Just an example of the commands failing to run from dragging and dropping . Would you be able to do that with [cypress-tiny-test](https://github.com/cypress-io/cypress-test-tiny) repo for a reproduction?

**Comment by mschile** [comment] 2022-10-26 17:39
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Ralkage** [comment] 2022-10-28 01:19
Sorry about that @mschile, notifications were turned off for me for this issue for whatever reason.

@AtofStryker I tried using http://demo.guru99.com/test/drag_drop.html with drag and drop and it works.

The error occurs after double-clicking as well and I've included the stacktrace below if that helps. I don't really understand the error as it only shows up after moving an item from the right pane of our app to a drop zone to the left. Our app lets us drag the item or simply double-click it and it'll move it to the left pane.

```sh
index.656179c6.js:99335 
        
       TypeError: Cannot read properties of null (reading 'scrollY')
    at Object.getElementPositioning (https://192.168.124.75/__cypress/runner/cypress_runner.js:167751:49)
    at elIsOutOfBoundsOfAncestorsOverflow (https://192.168.124.75/__cypress/runner/cypress_runner.js:171082:80)
    at isHiddenByAncestors (https://192.168.124.75/__cypress/runner/cypress_runner.js:170898:10)
    at isHidden (https://192.168.124.75/__cypress/runner/cypress_runner.js:170810:10)
    at Object.isVisible (https://192.168.124.75/__cypress/runner/cypress_runner.js:170792:11)
    at ../driver/src/config/jquery.ts.$.expr.filters.visible (https://192.168.124.75/__cypress/runner/cypress_runner.js:132607:85)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:92629:22)
    at superMatcher (https://192.168.124.75/__cypress/runner/cypress_runner.js:92850:12)
    at Sizzle.select (https://192.168.124.75/__cypress/runner/cypress_runner.js:93029:44)
    at Sizzle (https://192.168.124.75/__cypress/runner/cypress_runner.js:91197:9)
    at Sizzle.matchesSelector (https://192.168.124.75/__cypress/runner/cypress_runner.js:91856:9)
    at tryFn (https://192.168.124.75/__cypress/runner/cypress_runner.js:132574:30)
    at tryCatchFinally (https://192.168.124.75/__cypress/runner/cypress_runner.js:132545:12)
    at ../driver/src/config/jquery.ts.$.find.matchesSelector (https://192.168.124.75/__cypress/runner/cypress_runner.js:132572:10)
    at jQuery.filter (https://192.168.124.75/__cypress/runner/cypress_runner.js:93201:22)
    at winnow (https://192.168.124.75/__cypress/runner/cypress_runner.js:93183:17)
    at jQuery.fn.init.filter (https://192.168.124.75/__cypress/runner/cypress_runner.js:93234:26)
    at Log.setElAttrs (https://192.168.124.75/__cypress/runner/cypress_runner.js:162108:116)
    at Log.set (https://192.168.124.75/__cypress/runner/cypress_runner.js:161976:12)
    at setEl (https://192.168.124.75/__cypress/runner/cypress_runner.js:143346:22)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:143371:11)
From previous event:
    at resolveElements (https://192.168.124.75/__cypress/runner/cypress_runner.js:143366:52)
From previous event:
    at Context.contains (https://192.168.124.75/__cypress/runner/cypress_runner.js:143400:65)
    at wrapped (https://192.168.124.75/__cypress/runner/cypress_runner.js:157382:19)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:156105:15)
From previous event:
    at CommandQueue.runCommand (https://192.168.124.75/__cypress/runner/cypress_runner.js:156083:8)
    at next (https://192.168.124.75/__cypress/runner/cypress_runner.js:156230:19)
From previous event:
    at next (https://192.168.124.75/__cypress/runner/cypress_runner.js:156230:39)
From previous event:
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:171669:77)
From previous event:
    at CommandQueue.run (https://192.168.124.75/__cypress/runner/cypress_runner.js:171664:21)
    at CommandQueue.run (https://192.168.124.75/__cypress/runner/cypress_runner.js:156298:15)
    at $Cy.runQueue (https://192.168.124.75/__cypress/runner/cypress_runner.js:157348:14)
    at cy.<computed> [as contains] (https://192.168.124.75/__cypress/runner/cypress_runner.js:157457:12)
    at runnable.fn (https://192.168.124.75/__cypress/runner/cypress_runner.js:157640:19)
    at callFn (https://192.168.124.75/__cypress/runner/cypress_runner.js:107910:21)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://192.168.124.75/__cypress/runner/cypress_runner.js:107897:7)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:164958:30)
From previous event:
    at Object.onRunnableRun (https://192.168.124.75/__cypress/runner/cypress_runner.js:164943:53)
    at $Cypress.action (https://192.168.124.75/__cypress/runner/cypress_runner.js:153717:28)
    at Runnable.run (https://192.168.124.75/__cypress/runner/cypress_runner.js:162595:13)
    at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://192.168.124.75/__cypress/runner/cypress_runner.js:108569:10)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:108695:12)
    at next (https://192.168.124.75/__cypress/runner/cypress_runner.js:108478:14)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:108488:7)
    at next (https://192.168.124.75/__cypress/runner/cypress_runner.js:108390:14)
    at Hook.<anonymous> (https://192.168.124.75/__cypress/runner/cypress_runner.js:108451:7)
    at next (https://192.168.124.75/__cypress/runner/cypress_runner.js:164849:24)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:164878:13)
From previous event:
    at onNext (https://192.168.124.75/__cypress/runner/cypress_runner.js:164875:59)
    at done (https://192.168.124.75/__cypress/runner/cypress_runner.js:107850:5)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:107915:11)
From previous event:
    at callFn (https://192.168.124.75/__cypress/runner/cypress_runner.js:107913:14)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://192.168.124.75/__cypress/runner/cypress_runner.js:107897:7)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:164958:30)
From previous event:
    at Object.onRunnableRun (https://192.168.124.75/__cypress/runner/cypress_runner.js:164943:53)
    at $Cypress.action (https://192.168.124.75/__cypress/runner/cypress_runner.js:153717:28)
    at Runnable.run (https://192.168.124.75/__cypress/runner/cypress_runner.js:162595:13)
    at next (https://192.168.124.75/__cypress/runner/cypress_runner.js:108412:10)
    at <unknown> (https://192.168.124.75/__cypress/runner/cypress_runner.js:108456:5)
    at timeslice (https://192.168.124.75/__cypress/runner/cypress_runner.js:102382:27)
logError @ index.656179c6.js:99335
```

**Comment by mschile** [comment] 2022-10-31 16:55
@Ralkage, thanks for the stack trace. The error appears to be coming from this line when `win` is null:

https://github.com/cypress-io/cypress/blob/8547f61029108c005901f9b04a0a41a1e514f245/packages/driver/src/dom/coordinates.ts#L171

Unfortunately, I haven't been able to reproduce the issue. Would you be able to try and setup a reproduction with the [cypress-tiny-test](https://github.com/cypress-io/cypress-test-tiny) repo?

**Comment by Ralkage** [comment] 2022-11-02 00:52
@mschile I think we are good here, looks to be a change we made in our product when introducing a new feature; you can go ahead and close this issue :)

Thank you for your time and patience!

**Closed as completed** 2022-11-02 03:25 UTC
