### ISSUE TITLE
Different behavior in normal tab and test tab

### ISSUE THREAD

**Issue by julianmendonca** [cypress-io/cypress#7155] opened 2020-04-27 18:10 UTC
### Current behavior:

Test browser tab not behaving the same way as a normal tab.
My company inject stuff to already developed sites and i use cypress to check if the content loaded.
The problem is when i do cy.visit("https://www.sodimac.com.ar/sodimac-ar/") the carousel that we inject doesent appear, but when i open another tab in the same browser the carousel appear...

I used the same exact code in 4 computers with windows, it worked in my desktop one and the one we use from aws, but didnt work in the other 2 windows notebooks we used

I dont know why it appear in others tab but no in the running test tab.

This is the carousel that should appear

![image](https://user-images.githubusercontent.com/31936866/80404890-3db68600-8898-11ea-90be-658b567b6cae.png)

There should be cookies from s.braindw.com that dont appear, maybe that is a hint?

### Desired behavior:

Apper the same carousel in test tab

### Test code to reproduce

Cypress.json

`{
    "chromeWebSecurity": false,
    "viewportWidth": 1300,
    "viewportHeight": 660
}`

index.js

`Cypress.Cookies.defaults({
    whitelist: ['cd_user_id',
        '__utmb',
        '__cfduid',
        'keepalive',
        '_fbp',
        '_sdsat_login_clienteID',
        '__utmt',
        'guid',
        '_hjIncludedInSample',
        'DYNAMIC_DATA_COOKIE',
        'kampyleUserPercentile',
        'kampyleUserSessionsCount',
        'kampyleUserSession',
        'kampyle_userid',
        'TS016f6d42',
        'JSESSIONID',
        'kampyleSessionPageCounter',
        '_pk_ses.655.44e8',
        'TS01660a12',
        'ADRUM',
        '_sdsat_hash-id',
        '_pk_id.655.44e8',
        '_pk_ref.655.44e8',
        'AWSALB',
        'BVBRANDSID',
        'TS01c00e35',
        '__utmz',
        'BVBRANDID',
        'AWSALBCORS',
        '__utmc',
        '__utma',
        '_hjid',
        'mbox',
        'guid',
        'DYNAMIC_DATA_COOKIE',
        '_hjIncludedInSample',
        'keepalive',
        '_fbp',
        '__cfduid',
        '_sdsat_login_clienteID',
        '__utmt',
        '__utmb',
        'cd_user_id'
    ]
})

beforeEach(() => {
    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
    })
})`

commands.js

`Cypress.Commands.add('getIframeDocument', (id) => {
    return cy
        .get('#' + id)
        .its('0.contentDocument').should('exist')
})
Cypress.Commands.add('getIframeBody', (id) => {
    return cy.getIframeDocument(id)
        .its('body').should('not.be.undefined')
        .then(cy.wrap)
})

let LOCAL_STORAGE_MEMORY = {};

Cypress.Commands.add("saveLocalStorageCache", () => {
    if (Object.keys(localStorage)) {
        Object.keys(localStorage).forEach(key => {
            LOCAL_STORAGE_MEMORY[key] = localStorage[key];
        });
    }

});

Cypress.Commands.add("restoreLocalStorageCache", () => {
    if (Object.keys(LOCAL_STORAGE_MEMORY)) {
        Object.keys(LOCAL_STORAGE_MEMORY).forEach(key => {
            localStorage.setItem(key, LOCAL_STORAGE_MEMORY[key]);
        });
    }

});

Cypress.Commands.add('clearLocalAndCookies', () => {
    Cypress.Cookies.defaults({
        whitelist: []
    });

    //Clear localStrage
    cy.clearLocalStorage()

    //Clear Cookies
    cy.clearCookies()

    // Set defaults
    Cypress.Cookies.defaults({
        whitelist: /cd_user_id.*|kampyleSessionPageCounter.*|guid.*/
    })
})`

theTest.js

`
beforeEach(() => {
    cy.restoreLocalStorageCache();
});

afterEach(() => {
    cy.saveLocalStorageCache();
});
describe("Sodimac Gondola Los Mas Vendidos", () => {

    it('Cargo la gondola "Los Mas Vendidos"', function () {
        cy.visit("https://www.sodimac.com.ar/sodimac-ar/");
        cy.wait(10000);
        cy.getIframeBody('Braindw6').find('.owl-item:not(.cloned)').should('exist')
    })

})`
### Versions

There actualy is more code, but since the carousel doesent appear in any part of the site i only put the home page only.

Thank you in advance :)

Latest Chrome

**Comment by jennifer-shehane** [comment] 2020-04-29 06:15
Do not open a new issue for an existing issue. Post a comment in the original issue and we will reopen the issue if necessary.

Duplicate of #7141

**Closed by jennifer-shehane** 2020-04-29 06:15 UTC
