### ISSUE TITLE
Updating to 4.8.0 version from 4.7.0 version delete Cypress folder

### ISSUE THREAD

**Issue by Hiyeos** [cypress-io/cypress#7749] opened 2020-06-17 23:32 UTC
### Current behavior:

When I try to update the version, the cypress folder has been deleted from node_modules folder

Before
![After](https://user-images.githubusercontent.com/65571958/84960100-6273f080-b0c6-11ea-8d18-353d50f3c2af.jpeg)

Updating process:
![Updating process](https://user-images.githubusercontent.com/65571958/84960084-5ab44c00-b0c6-11ea-8a58-a51eb98c3d24.jpeg)

After:
![Before](https://user-images.githubusercontent.com/65571958/84960057-4e2ff380-b0c6-11ea-991a-3166c992989f.jpeg)

Then:
![Then](https://user-images.githubusercontent.com/65571958/84960985-c697b400-b0c8-11ea-82d9-2ef3aa1dbe43.jpeg)

Log:
[log.txt](https://github.com/cypress-io/cypress/files/4795489/log.txt)

### Desired behavior:

The update process should end without affecting any important component of cypress, now cypress does not work and the only way to solve this is copy and paste the cypress folder that I have on my back up 

### Versions

Current cypress version: 4.7.0
Desired cypress versioin: 4.8.0
Windows 10 Enterprise
Node js V12.18.1

**Comment by jennifer-shehane** [comment] 2020-06-18 10:04
It looks like something failed during the postinstall of the Cypress package, so it never fully installed the npm module as shown in the warnings. If the install fails, then the module will not be present to run. 

I'm not sure why the postinstall is failing in this case however. Looks to be a duplicate of https://github.com/cypress-io/cypress/issues/6807

**Closed by jennifer-shehane** 2020-06-18 10:04 UTC
