### ISSUE TITLE
Creating cy.route(s) for an iframe

### ISSUE THREAD

**Issue by james-demaine** [cypress-io/cypress#2014] opened 2018-06-22 15:31 UTC
Hi all, I want to setup a cy.route which listens for a request on a button press within an iframe but haven't had any luck. I think this might be down to the cy.server being setup on the parent window so its not catching the request as it's sent from the iframe - can anyone help? - I think this might be related to the ever present cypress iframe bugs but I think it should be possible to launch the server on the iframe and listen for the request there instead of the parent window.

Is this a known bug or can anyone help me out?

**Comment by chrisbreiding** [comment] 2018-06-25 14:13
We've started work on [re-writing network stubbing](https://github.com/cypress-io/cypress/issues/687), which should fix this issue once it is complete.

**Comment by egucciar** [comment] 2018-06-25 17:39
@chrisbreiding I would ask this to be a feature request or bug rather than a Q.

I too am interested in the feature.

**Comment by misantronic** [comment] 2018-12-20 21:52
any progress on this issue?

**Comment by hhudson** [comment] 2018-12-26 02:09
I have this same need.

**Comment by aldocd4** [comment] 2019-02-15 09:46
Hello, 

any progress here ?

**Comment by jennifer-shehane** [comment] 2019-02-15 17:54
No work has been done on this specific issue at this time.

**Comment by kmahata** [comment] 2019-09-23 20:43
Any updates ?

**Comment by dudewad** [comment] 2020-02-11 19:41
@jennifer-shehane Hey there! It's been a while since any update on this, is this scoped on the roadmap at all? Just curious when we might be able to expect this feature, would be a huge boost. Presently we can't test based off iframe network activity which is a bit tough for apps that are designed to be used via iframe.

**Comment by bahmutov** [comment] 2020-02-11 19:45
@dudewad I have added a recipe showing working with iframes here https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__iframes and there will be a new post to go with it tomorrow at https://www.cypress.io/blog/

**Comment by dudewad** [comment] 2020-02-11 19:46
@bahmutov thanks!! I will check this out. Appreciate it!

**Comment by dudewad** [comment] 2020-02-11 21:17
@bahmutov the examples there actually break for me -- the `.get()` iframe call chained to an `.its()` call causes `TS2345: Argument of type '"0.contentWindow"' is not assignable to parameter of type 'number'.`
I'm not positive but it looks like the override added in 3.7 seems to only allow numbers. Weirdly enough this appears to only be the case after `get` calls because we have other usages of `its` that work fine with string values. For some reason it thinks that the `0.contentWindow` is a _type_.
Not to fill a feature request with support but did you run these examples? Not working for me :/

**Comment by bahmutov** [comment] 2020-02-11 21:20
Yes, all our recipes are tested constantly https://circleci.com/gh/cypress-io/cypress-example-recipes/62084

**Comment by dudewad** [comment] 2020-02-11 21:20
Ok. Maybe its a configuration issue but I've confirmed against the api docs as well as copy/pasted your example and am getting that error in both intellisense as well as at cypress runtime. Will keep looking../

**Comment by dudewad** [comment] 2020-02-11 21:53
For anyone else with this issue, the following works for me where the above snippet (copy/pasted from the recipes doc) does not:
(to get iframe window)
```
cy
    .get('iframe')
    .its(0)
    .its('contentWindow')
    .should('exist');
```

**Comment by flotwig** [comment] 2021-05-06 14:55
`cy.intercept` supports requests in iframe, and is planning to eventually obsolete `cy.route`. Closing this issue since it's possible today with `cy.intercept`.

**Closed by flotwig** 2021-05-06 14:55 UTC
Labels: stage: proposal 💡, topic: iframes, topic: network, type: feature
