### ISSUE TITLE
cypress should live reload when changes made to `fixturesFolder`

### ISSUE THREAD

**Issue by brettz9** [cypress-io/cypress#6606] opened 2020-03-02 03:38 UTC
### Current behavior:

When changing `plugins` or `fixtures`, the tests opened by `cypress open` are not auto-reloaded as they are when changes are made to `cypress/integration` or `cypress/support` files.

### Desired behavior:

Unless there is some good reason for it, I would expect the pages would reload. While I can see that `plugins` might be more consequential in having unintended side-effects, so too can `support` files (which can use plugins by way of commands), I would at least think that changes to`fixtures` would trigger reloads, and I'd personally like to see changes to `plugins` be able to do so.

### Test code to reproduce

1. Run `cypress open` on some repository.
2. Open a test file
3. Modify a file in `/plugins`
4. See that the test file does not reload (nor does the command line show changes)

### Versions

Cypress: 4.1.0
OS: Mac 10.15.2
Browser: Firefox or Chrome

**Comment by jennifer-shehane** [comment] 2020-03-02 09:07
Updating on changes to `plugins` is duplicate of https://github.com/cypress-io/cypress/issues/2869 - we can't actually watch and just rerun it because it could crash Cypress essentially, so the proposal is to display a message to warn that there have been changes. There is an open PR - but it is stale atm. 

Change to `fixtures` *does* take effect when reloading the page, but yes - live reload does not reload the test when fixtures are changed. 

I will update the scope of this issue as a request to live reload when changes are made to `fixturesFolder`.

**Comment by jennifer-shehane** [comment] 2023-12-16 03:32
Since this request has not gotten a lot of interest over the years, we’ll close this issue.

**Closed by jennifer-shehane** 2023-12-16 03:32 UTC
Labels: type: enhancement, stage: ready for work, topic: file watching :eyes:, topic: fixtures
