### ISSUE TITLE
Ionic app isn't fully supported 

### ISSUE THREAD

**Issue by Yohandah** [cypress-io/cypress#6288] opened 2020-01-31 09:48 UTC
### Current behavior:
When looking at dom snapshots on a ionic app the app isn't in full screen and in a weird state. 
It also cause weird behavior like Cypress is clicking on a menu item after it scrolled but it doesn't navigate.

![dom bugged 2](https://user-images.githubusercontent.com/15921402/73524410-5d5f1f00-440d-11ea-9c1c-074709b8ba96.png)
![dom bugged](https://user-images.githubusercontent.com/15921402/73524411-5d5f1f00-440d-11ea-87c5-1e269d732d4a.png)

### Desired behavior:

When tests are over and my app is displayed in Cypress, it's in a "normal" state with full of the screen taken, clicking on menu is working, etc.
![dom ok](https://user-images.githubusercontent.com/15921402/73524485-82ec2880-440d-11ea-87a7-92bb1645254b.png)

### Test code to reproduce
Clone this repo (it's just a Ionic starter app with cypress added) : https://github.com/Yohandah/cypress_ionic_bug

Install dependencies : `yarn` 
Run the Ionic app : `ionic serve` 
Open cypress : `yarn cypress open ` 

Open bug.spec.js in Cypress, then navigate to the snapshots, you'll see the app in a weird state with half of the screen taken.

The written test doesn't pass, the click on the menu didn't work.

### Versions

Cypress 3.8.3
Windows 10
Chrome 79
Ionic 4

**Comment by jennifer-shehane** [comment] 2020-02-04 06:08
I believe this is due to [Ionic using Shadow DOM](https://ionicframework.com/blog/shadow-dom-in-ionic-and-why-its-awesome/), which is not fully supported in Cypress. Which would be a duplicate of https://github.com/cypress-io/cypress/issues/144

But I can't get the repo to run. I get this error running `yarn`:

```
error An unexpected error occurred: "https://si-devops-zhb-nexus.edf.fr/repository/npmjs/@angular/forms/-/forms-8.1.3.tgz: getaddrinfo ENOTFOUND si-devops-zhb-nexus.edf.fr si-devops-zhb-nexus.edf.fr:443".
```

**Comment by Yohandah** [comment] 2020-02-04 07:25
@jennifer-shehane oops yes ! Delete the yarn.lock and relaunch yarn install! I’ll update the repo asap

**Comment by Yohandah** [comment] 2020-02-04 14:15
@jennifer-shehane I've updated the repo please let me know if you can reproduce. I tried to use a cypress plugin that supports Shadow Dom but couldn't get it to work either.

If you do not support Ionic maybe you should put it out of your FAQ (https://docs.cypress.io/faq/questions/general-questions-faq.html)

![Capture](https://user-images.githubusercontent.com/15921402/73752351-1cdf0880-4761-11ea-95a9-293783cdaecb.PNG)

**Comment by oneumyvakin** [comment] 2020-02-22 17:47
@Yohandah  May this package help you https://www.npmjs.com/package/cypress-shadow-dom ?

**Comment by Yohandah** [comment] 2020-02-24 16:18
@oneumyvakin No it doesn't I've already looked into that, but maybe I did not take enough time to understand it all. 

In the end I've decided to use Selenide to e2e my Ionic project as Cypress it doesn't feel really reliable for a Ionic project, and I can't use the snapshot functionality as the dom is not okay and not rendered properly :/.

**Comment by mvandebunt** [comment] 2020-04-14 12:05
I'm able to test my ionic app using https://www.npmjs.com/package/cypress-shadow-dom

But I still have this issue: #5776 DOM Snapshots are blank
Snapshot of last test is displaying, but snapshots of other tests are blank

**Comment by jennifer-shehane** [comment] 2020-06-09 04:27
We've added experimental shadow DOM support through the `experimentalShadowDomSupport` configuration option.

To use it, update to Cypress 4.8.0 and pass the following to your configuration file or however you pass in configuration. 

```json
{
  "experimentalShadowDomSupport": true
}
```

See the [Experiments](https://on.cypress.io/experiments#Cross-boundary-selectors) for more information including how to use the new `.shadow()` command and `includeShadowDom` option.

This is still experimental, so we'd like your help working through any bugs or unexpected behavior before releasing into the main product. If you encounter any issues using the new experimental shadow DOM feature, please **[open a new issue](https://github.com/cypress-io/cypress/issues/new)**, filling in the issue template and providing a reproducible example.

**Closed by jennifer-shehane** 2020-06-09 04:27 UTC
Labels: stage: awaiting response
