### ISSUE TITLE
Clicking on anchor elements expects a page load events

### ISSUE THREAD

**Issue by mohsenny** [cypress-io/cypress#15220] opened 2021-02-25 14:14 UTC
### Current behavior

In our web application, we have buttons in form of anchor elements, with links inside of them of course. These links points to S3 bucket files and clicking on those button triggers a download.

However, from Cypress' perspective, clicking on any `anchor` element that contains `href` inside of them, would expect a **new page** to load. For example here:

<img width="1440" alt="Screenshot_2021-02-25_at_15_01_43" src="https://user-images.githubusercontent.com/1129811/109169049-b66bc480-777f-11eb-843e-fe44c0125cce.png">

at line `#11` we're clicking on the button and the file starts getting downloaded, but immediately Cypress starts to wait for a new page to load which in this case there would be no new page to open, and therefore the tests fail

### Desired behavior

Either Cypress should detect if redirection to a new page is happening when clicking on an anchor (maybe looking for the `download` attribute not to exist) to start waiting for a new page to load, or, another approach could be passing an option to click element that stops such event from being triggered:

```
cy.get(selector).click({newPageTrigger: false})
```

### Test code to reproduce
This is the HTML element for the Download button:

```html
<a data-wide="true" download="Event in the past.xls" theme="[object Object]" class="ant-btn sc-pjTIO fJuPmM ant-btn-primary ant-btn-lg" href="https://s3.eu-central-1.amazonaws.com/blahblah">
   <span role="img" aria-label="download" class="anticon anticon-download">
      <svg viewBox="64 64 896 896" focusable="false" class="" data-icon="download" width="1em" height="1em" fill="currentColor" aria-hidden="true">
         <path d="M505.7 661a8 8 0 0012.6 0l112-141.7c4.1-5.2.4-12.9-6.3-12.9h-74.1V168c0-4.4-3.6-8-8-8h-60c-4.4 0-8 3.6-8 8v338.3H400c-6.7 0-10.4 7.7-6.3 12.9l112 141.8zM878 626h-60c-4.4 0-8 3.6-8 8v154H214V634c0-4.4-3.6-8-8-8h-60c-4.4 0-8 3.6-8 8v198c0 17.7 14.3 32 32 32h684c17.7 0 32-14.3 32-32V634c0-4.4-3.6-8-8-8z"></path>
      </svg>
   </span>
   <span>Download</span>
</a>
```

### Versions

Cypress version: `6.5.0` 
Node version: `15.3.0`

**Comment by jennifer-shehane** [comment] 2021-02-26 00:35
@mohsenny We have several examples of anchor links with download attributes being tested in our recipes: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/cypress/integration/remote-download-spec.js None of them show this behavior. 

There must be something more unique about the application you're testing. Is there an onclick handler? Maybe it's setting the location?

Ideally a reproducible example - like a repo - that shows the issue would be best so we can investigate.

**Comment by mohsenny** [comment] 2021-02-26 09:05
Hey @jennifer-shehane thank you for the links. You're probably right. Let me communicate this to our dev team and I'll get back to this ticket with more information 🙏

**Comment by jennifer-shehane** [comment] 2021-02-26 13:55
I have an example of this error actually already here: https://github.com/cypress-io/cypress/issues/14857

Duplicate of https://github.com/cypress-io/cypress/issues/14857

**Closed by jennifer-shehane** 2021-02-26 13:55 UTC
Labels: stage: needs information

**Comment by jennifer-shehane** [comment] 2021-02-26 13:56
Actually, I'm not sure if it is a duplicate of https://github.com/cypress-io/cypress/issues/14857 exactly without a repro. So, comment here if it's different - or comment in the other issue if it is.

**Comment by mohsenny** [comment] 2021-02-26 14:27
@jennifer-shehane Yep, it's an exact duplicate. 
I'll be following the discussion in https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/public/index.html for any further updates.
