### ISSUE TITLE
Cypress videos recorded from Firefox are rendered at 10x the normal speed

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#17149] opened 2021-06-30 01:03 UTC
### Current behavior
When playing back a video that was recorded during a Firefox test run, the rendering is 10x what it should be when comparing the playback position in the video content vs. the offset of the video file. This does not happen with Chrome.

For instance, if I seek to 29 seconds into the video file, the test's timer says that 280 seconds have elapsed since the start of the test.

### Desired behavior
Video playback should be correct.

### Test code to reproduce
Record a video from Firefox 88.

### Versions
Cypress 7.5.0
Firefox 88
Debian 9

**Comment by kaiyoma** [comment] 2021-06-30 01:05
![image](https://user-images.githubusercontent.com/10719780/123886522-82a6d400-d904-11eb-87e4-beb0a566ca11.png)

**Comment by jennifer-shehane** [comment] 2021-06-30 13:48
Duplicate of https://github.com/cypress-io/cypress/issues/6337 This is a bug from Mozilla that we've filed with them.

**Closed by jennifer-shehane** 2021-06-30 13:48 UTC
