### ISSUE TITLE
"Cannot read property 'lastIndexOf' of undefined" when using import in typescript plugins file

### ISSUE THREAD

**Issue by sceee** [cypress-io/cypress#7570] opened 2020-06-02 16:14 UTC
### Current behavior:

It seems as soon as I am trying to use an `import { ... } from '...'` (import a separate .ts Typescript file from the project to be tested) in a `plugins/index.ts`, cypress fails directly when executing `cypress open` with the following error and stack trace:
![image](https://user-images.githubusercontent.com/11340487/83543213-6287c400-a4fc-11ea-835a-b8247397bf2f.png)

**Message:** Cannot read property 'lastIndexOf' of undefined

**Stack trace:**
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:2060:20)
    at mangleScopedPackageName (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30540:16)
    at mangleScopedPackageNameWithTrace (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30527:23)
    at loadModuleFromImmediateNodeModulesDirectory (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30458:83)
    at C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30435:39
    at Object.forEachAncestorDirectory (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:6784:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30429:19)
    at loadModuleFromNearestNodeModulesDirectoryTypesScope (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30425:16)
    at tryResolve (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30604:28)
    at classicNameResolver (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:30580:24)
    at Object.resolveModuleName (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\typescript\lib\typescript.js:29897:30)
    at tsLookup (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\filing-cabinet\index.js:221:26)
    at cabinet (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\filing-cabinet\index.js:75:18)
    at Function.module.exports._getDependencies (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:104:20)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:149:37)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at traverse (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:171:24)
    at Module.module.exports (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:35:19)
    at Function.module.exports.toList (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\node_modules\dependency-tree\index.js:72:17)
    at Watchers.watchTree (C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\lib\watchers.js:60:30)
    at C:\Users\me\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\server\lib\project.js:272:28
```

### Desired behavior:

`import {...} from '...'` can be used in `plugins/index.ts`.

### Test code to reproduce

1. Add `import {...} from '../../myproject/any/file.ts' to the top of your `plugins/index.ts`
Note: The import must not be used at all, it seems having it is enough to break displaying the tests list.
2. tsconfig in cypress directory is
```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"]
  },
  "include": [
    "**/*.ts"
  ]
}
```

### Versions

Cypress 4.7.0

**Comment by jennifer-shehane** [comment] 2020-06-03 07:22
I'm not able to reproduce the issue from the instructions provided. Please provide a full example that we can run to reproduce the issue, otherwise we will have to close the issue. 

Likely it has something to do with the contents of your export. What I tried is below. Cypress launches fine.

`cypress/plugins/index.ts`

```ts
import { getString } from '../../export'

module.exports = (on) => {};
```

`export.ts`

```ts
export function getString (s) {
  return s
}
```

`cypress/tsconfig.json`

```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": [
      "es5",
      "dom"
    ],
    "types": [
      "cypress"
    ]
  },
  "include": [
    "**/*.ts"
  ]
}
```


`package.json`

```json
{
  "name": "my-application",
  "version": "1.2.3",
  "devDependencies": {
    "cypress": "4.7.0",
    "typescript": "^3.9.3"
  }
}
```

**Comment by sceee** [comment] 2020-06-03 11:03
@jennifer-shehane you are correct, it seems to have something to do with this specific project or the imports in `export.ts`.

Unfortunately, it seems I am unable to create a reproducible example without the full code from this project. I tried but I could not reproduce it with an easy example.

And I cannot drag any helpful trace information from the cypress call stack. Do you know if there is any log or something where I could further trace down what's causing cypress to fail loading this import (and to see which class/file actually creates this error)?

**Comment by jennifer-shehane** [comment] 2020-06-05 09:27
We have [debug](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) logs but I honestly don't think they'd help much in this situation. 

I would suggest commenting out chunks of code in the project until you can reduce down exactly which line is causing the issue.

**Comment by sceee** [comment] 2020-06-06 17:01
Thanks @jennifer-shehane . Unfortunately commenting out chunks is pretty hard as an initial test revealed that it seems to be caused by some imports in `export.ts` (which of course have a lot of other imports again).

I will try if I can reduce it down to see what's causing this but it'd definitely be better if cypress would provide any hint on the failing file as I guess others could also run into this and the project itself of course compiles regularly with TS.
Just as an improvement idea.

**Comment by jennifer-shehane** [comment] 2020-07-14 10:17
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-14 10:17 UTC
Labels: stage: needs information

**Comment by capaj** [comment] 2021-04-02 11:45
@jennifer-shehane I got this error on my machine with cypress 6.8.0 when I had this line in my code:
```ts
 const { messages } = await import(`../locale/${kebabCaseLocale}/messages`)
```

as soon as I removed it, cypress worked fine. 
I worked around this by replacing it with require for now, but require sucks, bucause they are not type safe in TS. Dynamic imports are.

Do you have any spec with a dynamic import in place here in the repository?

**Comment by capaj** [comment] 2021-04-02 11:46
Also should I open a new bug for this dynamic import issue?

**Comment by jennifer-shehane** [comment] 2021-05-05 18:09
@capaj Yes please open a new bug with a fully reproducible example.
