### ISSUE TITLE
React (jsx) fragments without import cause issue for Component Testing

### ISSUE THREAD

**Issue by coreylight** [cypress-io/cypress#16172] opened 2021-04-23 17:56 UTC
### Current behavior
Running `npx cypress open-ct`
Using the Create React App setup, trying to execute a simple test that uses unnamed fragments seems to fail:
```ts
describe.only('Hello', () => {
  it('works', () => {
    mount(
      <div>
        <>ok</>
      </div>
    );
  });
});
```
If I use the `Fragment` import from React, this works fine though.
React 17 is supposed to work without import of React module in most cases.

### Desired behavior
Ability to use unnamed jsx fragment syntax.
With storybook I've added global code that helps this issue like so:
```ts
import { Fragment } from 'react';
window.React = {
  Fragment,
};
```
Note: this is not only an issue for the fragments inside of the test file, source components that are imported for testing will fail.

### Versions
- Cypress 7.1.0
- @cypress/react 5.3.4

**Comment by lmiller1990** [comment] 2021-04-30 05:27
Hi! I might need a minimal repo to reproduce this issue. I added your example to [my own basic project](https://github.com/lmiller1990/cypress-react-template/blob/master/src/NewJsxTransform.spec.tsx) which is using `react-scripts@4.0.3` and the new JSX transform, but it seems to be working fine.

**Comment by lmiller1990** [comment] 2021-05-19 03:25
Going to close this one for now, happy to reopen if we have more information and can reproduce the problem.

**Closed by lmiller1990** 2021-05-19 03:25 UTC
Labels: component testing, npm: @cypress/react, stage: needs more info
