### ISSUE TITLE
window.Cypress is undefined when running CLI with Electron

### ISSUE THREAD

**Issue by paulmoliva** [cypress-io/cypress#2383] opened 2018-08-22 14:36 UTC
### Current behavior:

`window.Cypress` is `undefined` when running in Electron via CLI

### Desired behavior:

`window.Cypress` should be defined

### Steps to reproduce:

Open any project and add a conditional to the view that will add a tag if `window.Cypress` is defined.

i.e. for react 

```jsx
{window.Cypress && <p data-cy="windowTest">window.Cypress is defined</p>}
```

add a cypress test to your spec file checking for the presence of the tag

```js
cy.get('[data-cy=windowTest]')
```

Run via the cli `cypress run my_spec.js` this runs in Electron by default. Tag is not present.

Run via cli `cypress run my_spec.js --browser chrome` this runs it in Chrome. It works.

Run `cypress open` and click the spec file. It works.

This issue is a pain point because video recording isn't supported in Chrome, so it'll be difficult to debug issues when it runs in our CI. We have to use `window.Cypress` in order to authenticate our automation user properly.

### Versions

Observed in both v2 and v3.

**Comment by bbuckland** [comment] 2018-08-22 20:35
Note: this is a sporatic issue — It will generally work in electron with the first spec, but subsequent specs that are dependent on window.Cypress being present, will generally fail.

**Comment by chrisbreiding** [comment] 2018-08-28 16:49
I'm afraid those steps to reproduce don't really prove that `window.Cypress` is undefined. They just prove that the element has not been rendered, which could be caused by something else within your app. 

Can you try the following test to verify that `window.Cypress` is indeed undefined:

```javascript
cy.window().its('Cypress').should('be.an', 'object')
```

**Comment by paulmoliva** [comment] 2018-09-04 20:30
@chrisbreiding Still undefined with that test instead.  Noticed it's only happening when we run it against our QA site. Works fine locally.

**Comment by jennifer-shehane** [comment] 2018-10-20 19:07
Hey @paulmoliva, is it possible to provide a public url that we could visit in Cypress to see this behavior? Or you could provide a reproducible repo? We'll need to be able to reproduce this to address the issue. Thanks!

**Comment by s00500** [comment] 2019-03-29 12:22
Also just ran into this issue... is there a better way to detect testing environment?

**Comment by s00500** [comment] 2019-03-29 14:16
Nevermind, it was a pageload issue

**Comment by jennifer-shehane** [comment] 2019-04-18 08:02
Unfortunately we'll have to close this issue since no reproducible example is provided. Please comment with a reproducible example to consider reopening.

**Closed by jennifer-shehane** 2019-04-18 08:02 UTC
Labels: stage: needs information

**Comment by tonilopezmr** [comment] 2019-10-17 14:06
`window.Cypress` on Electron browser is undefined.

I'm running this test

```javascript
cy.window().its('Cypress').should('be.an', 'object')
```

<img width="554" alt="Screenshot 2019-10-17 at 16 02 36" src="https://user-images.githubusercontent.com/5845622/67015903-95a94e80-f0f7-11e9-9562-561e39a12845.png">

**Comment by jennifer-shehane** [comment] 2020-01-03 09:20
Please ensure you are visiting a valid url first before running this assertion, otherwise there is no window that Cypress could be attached to. The test below passes for me in Electron and chrome.

```js

it('has Cypress defined', () => {
  cy.visit('index.html')
  cy.window().its('Cypress').should('be.an', 'object')
})
```

**Comment by Gurubg1** [comment] 2020-02-24 13:20
I have written 5 tests using cypress. When I do 'cypress run', Only the first test passes and all other tests fail at the line cy.window().its('Cypress').should('be.an', 'object'). Here is a screenshot
![image](https://user-images.githubusercontent.com/58414764/75155673-8b96fc80-5736-11ea-986a-fffd7227bc48.png)

**Comment by jennifer-shehane** [comment] 2020-03-25 11:39
@Gurubg1 I'm not able to recreate this. From the screenshot, it looks like you're calling `cy.window()` then `cy.visit()` and chaining 'its' off of this.

My test code:

```js
it('test', () => {
  cy.window()
  cy.visit('index.html').its('Cypress').should('be.an', 'object')
})
```

I see you're using the Cypress cucumber plugin - try removing cucumber and run again, it may be an issue isolated to that plugin.

**Comment by tauil** [comment] 2021-03-31 11:10
I had the same issue. `window.Cypress` is undefied when running in CircleCI. Probably due to CI=true but also I have the same result when running locally in headless mode with the `cypress run` command. My workaround was to use a custom environment variable in a Cypress-specific build of my application. It's not as clean as `window.Cypress` check but it works.

**Comment by ggascoigne** [comment] 2021-11-18 18:18
My issue is slightly different since I have some conditional code in my application that I want gated on whether code is being run by Cypress (i.e. I want to expose my redux store to Cypress).  Anyway, for me, `window.Cypress` was always undefined, but `window.parent.Cypress` wasn't.  Maybe this'll help someone else.

**Comment by ludwighogstrom** [comment] 2021-12-09 20:24
I also experience a flakiness of `window.Cypress`. Works most of the time but every once in the while it's `undefined`. Running Cypress via Cypress dashboard and GitHub action.

Right now I'm trying a solution where I set a cookie from Cypress that can be checked in the application. Seems to work so far...


In `commands.js`
```
Cypress.Commands.overwrite("visit", (visit, url, options) => {
  cy.setCookie("Cypress", "true");
  visit(url, options);
  // Custom MSW object that should be set if application detects the cookie.
  cy.window().should("have.property", "msw");
});
```

In the application
```
/Cypress=true/.test(document.cookie)
```
