### ISSUE TITLE
cy.visit() failed because you are attempting to visit a second unique domain.

### ISSUE THREAD

**Issue by bhargavi101** [cypress-io/cypress#5759] opened 2019-11-21 00:32 UTC
Hi 

I am trying to switch the domain based on the API response, so to no the status 
First I need to visit http://xyz.domain.com
After I receive API response now I need to visit https://abc.domain.com

When I am trying to hit this I am getting **"cy.visit() failed because you are attempting to visit a second unique domain."**

I have looked into some other scenarios and also tried implementing
"chromeWebSecurity": false in cypress.json file

and using cy.request(url, option)

both of them did not work. Is there a way to tweak this scenario

**Comment by moonformeli** [comment] 2019-11-21 14:30
To be very honest, I have no idea why they don’t care about this issue for years, it’s a big matter for a lot of people.

Who would just want to test 1 page and how many pages are there that do not have any redirect functionality in it

**Comment by flotwig** [comment] 2019-11-21 14:32
@moonformeli We do care about this issue. But if you read #944, you will understand it's not exactly simple to implement with Cypress's existing architecture.

You are able to test multiple pages with redirect functionality. You just can't `cy.visit()` multiple superdomains.

Duplicate of #944, closing

**Closed by flotwig** 2019-11-21 14:32 UTC
