### ISSUE TITLE
get(aliased network request).should(callbackFn) doesn't retry, but fails

### ISSUE THREAD

**Issue by balnagy** [cypress-io/cypress#5231] opened 2019-09-28 00:00 UTC
### Current behavior:

```js
cy.get('@request').should(xhr => {
  expect(xhr.requestBody.field).to.equal("data");
});
```

It fails the test when the first `@request` comes through, which doesn't have the required field.

### Desired behavior:

Continue and assert the next request as the documentation for `get()` and `should()` claims.

> cy.get() will automatically retry until assertions you've chained all pass.

> should() Create an assertion. Assertions are automatically retried until they pass or time out.

### Steps to reproduce: (app code and test code)

```js
cy.server();
cy.route("POST","/path", "response").as("request");
cy.get('@request').should(xhr => {
  expect(xhr.requestBody.field).to.equal("data");
});
```

### Versions

^3.4.1

**Comment by sainthkh** [comment] 2021-01-04 08:05
Confirmed that it doesn't work as expected.

```js
it('t', () => {
  cy.server()
  cy.route('POST', '/path', 'response').as('request')
  cy.get('@request').should((xhr) => {
    expect(2).to.equal(3)
  })
})
```

**Comment by flotwig** [comment] 2022-12-15 19:40
This is working as intended, if you don't want to assert on the first matched request, then either the matcher needs to be more strict or you should assert on the second request explicitly. Tests shouldn't be conditional.

Also, `cy.route()` was removed in [Cypress 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0), please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept) instead. Closing this issue since the relevant API has been deprecated and removed.

**Closed by flotwig** 2022-12-15 19:40 UTC
Labels: type: unexpected behavior, pkg/driver, stage: ready for work
