### ISSUE TITLE
Cypress can't find Chrome after update to 3.3.0

### ISSUE THREAD

**Issue by jameseg** [cypress-io/cypress#4260] opened 2019-05-20 18:50 UTC
### Current behavior:
After upgrading to 3.3.0, Cypress is unable to use the existing Chrome installation it used prior.  In addition, now even after uninstalling/reinstalling several times both Cypress and Chrome, I can't get Chrome to be available anymore.

![image](https://user-images.githubusercontent.com/38703245/58044494-df244c00-7b0d-11e9-8bf9-81bf2d0c9e7c.png)

When trying to clear the app data from the GUI:
```
{ Error: spawn cmd ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/wait',
     'C:\\Users\\James\\AppData\\Roaming\\Cypress\\cy\\production' ] }
Error: spawn cmd ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

DEBUG logs:
https://pastebin.com/u6kLMHZ0
^this is the piece that worries me, since the logs seem to indicate that Cypress found Chrome, but doesn't have it available for execution.

additional info:
https://stackoverflow.com/questions/56224598/how-do-i-get-cypress-to-detect-my-existing-chrome-browser-after-upgrade
### Desired behavior:

Cypress is able to use the existing Chrome application for execution, and is available in the dropdown menu in the GUI
### Steps to reproduce: (app code and test code)
Windows 10
Cypress 3.2.0
Chrome installed in the correct location

1. Upgrade using npm i cypress --save-dev
2. Open cypress
3. Look for Chrome to be now missing in the dropdown

### Versions

Cypress 3.2.0
Cypress 3.3.0
Windows 10
Chrome 74

**Comment by flotwig** [comment] 2019-05-20 20:21
Thanks for the bug report. Does this work for you in 3.2.0?

**Comment by jameseg** [comment] 2019-05-20 20:28
I actually am blocked now.  I can't get it to find Chrome at all.  I will try with a fresh 3.2 install though tomorrow

**Comment by flotwig** [comment] 2019-05-20 20:38
Alright, cool.

Also, try running this command too in Command Prompt, Cypress runs this internally to find your browser:

```
wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
```

It should output something like `Version=74.x.x.x`.

If it doesn't output that, then this looks a duplicate of #3645, and you should be able to fix it by resetting your WMIC store by following the [instructions from #3645](https://github.com/cypress-io/cypress/issues/3645#issuecomment-470991075).

**Comment by jennifer-shehane** [comment] 2019-05-21 05:58
Some troubleshooting tips as well: https://on.cypress.io/debugging#Launching-browsers

**Comment by jameseg** [comment] 2019-05-21 13:21
![image](https://user-images.githubusercontent.com/38703245/58099537-d7b28080-7ba9-11e9-980f-12105ccacb90.png)

like this?^

**Comment by jameseg** [comment] 2019-05-21 13:55
UPDATE:  After installing 3.2.0:

![image](https://user-images.githubusercontent.com/38703245/58101828-485b9c00-7bae-11e9-89af-efbeb6c442a0.png)

I'm also able to click "View App Data" without that crazy ENOENT error message above.
I'm going to use this version for now, thanks for the advice @flotwig

**Comment by petermouton** [comment] 2019-05-22 07:50
Same here. 
After installing 3.3.0 I get the 'Oops' window, trying to run Chrome 74. Electron 61 runs fine.
Back to Cypress 3.2.0 and Chrome 74 runs without problems

**Comment by petermouton** [comment] 2019-06-04 06:26
Error remains in 3.3.1

**Comment by PetMou** [comment] 2019-06-06 13:14
![Cypress_Chrome_error](https://user-images.githubusercontent.com/48205462/59035449-9db1d180-886d-11e9-84ea-34e6fec8b2fb.PNG)

Cypress 3.3.1

**Comment by flotwig** [comment] 2019-06-07 13:17
Hey @petermouton @PetMou, this looks like a different issue than the original post in this thread, so I've created a new issue to track this: #4410 Let's move discussion there.

**Comment by jameseg** [comment] 2019-06-17 14:30
UPDATE 6-14-19:  Another dev on my team implemented some new Cypress tests around a Vue component.  We have multiple projects in the same solution using different "cypress test projects".  The Cypress instances for my project (there are 2) still can't find Chrome after updating even to 3.3.1. Chrome is available in his project but neither of mine.  Is there a setting per project (like maybe ```cypress.json```) that might be affecting this?

**Comment by flotwig** [comment] 2019-06-17 15:04
@jameseg Can you re-share your debug logs? The pastebin in the OP has expired.

There aren't any per-project settings for browsers. Cypress attempts to find your browser on each run.

Does it work if you manually specify the path to your browser? ex: `cypress open --browser "C:\path\to\chrome.exe"`

Also, how are you launching Cypress? ex. via command prompt, powershell, powershell inside of VS code...?

**Comment by jameseg** [comment] 2019-07-02 16:52
I'm unable to get the logs to work now for some reason.  Am I doing this correctly?

<img width="321" alt="2019-07-02 12_50_45-login_spec js - automation - Visual Studio Code" src="https://user-images.githubusercontent.com/38703245/60531089-32bab580-9cc8-11e9-9fe5-b26fe187e981.png">

**Comment by jameseg** [comment] 2019-07-02 16:55
Running with the path...
![image](https://user-images.githubusercontent.com/38703245/60531274-9a710080-9cc8-11e9-9df4-9fc0bde28f18.png)

**Comment by jameseg** [comment] 2019-07-02 17:02
And to answer your question I'm running cypress in VS Code

**Comment by flotwig** [comment] 2019-07-02 17:14
Hmm, looks similar to #3891.

Cypress uses WMIC.exe to look up info about a potential browser. If it can't be launched, browser detection is broken.

It looks like `WMIC.exe` isn't in your `PATH`. If you do `echo $env:PATH`, do you see `C:\Windows\System32\Wbem`? If not, add it:

```
setx PATH "$env:PATH;C:\Windows\System32\Wbem"
```

...and then restart VS code to pick up the new system-wide PATH. Check that `echo $env:PATH` shows the `Wbem` directory at the end, and then re-launch Cypress. Browser detection should work.

---

Environment variables on Windows are weird, you can obtain debug logs by using the `cross-env` package:

```
npm i -g cross-env
cross-env DEBUG=cypress:* npx cypress open
```

**Comment by jameseg** [comment] 2019-07-02 17:24
Fixed it.  Thanks!

**Comment by flotwig** [comment] 2019-07-02 17:25
Ok, great. #3672 is also open to change the way we do browser detection to not use WMIC for reasons like this. Glad it's working!

**Closed by flotwig** 2019-07-02 17:25 UTC
Labels: OS: windows, browser: chrome, stage: needs information

**Comment by colinbr96** [comment] 2022-08-23 17:15
> ```
> setx PATH "$env:PATH;C:\Windows\System32\Wbem"
> ```
Warning to all: I ran this command and it deleted everything else in my PATH. Now I have to rewrite it from scratch.

**Comment by naraphim** [comment] 2023-08-28 22:16
Aug 2023 - I installed Cypress and it wouldn't show Chrome as a selectable browser.
If I ran 
wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
it wouldn't find any version.
It turns out I had actually installed Chrome in 
"C:\Program Files\Google\Chrome\Application\chrome.exe"

I solved this issue based on https://github.com/cypress-io/cypress/issues/2834

I created a Directory Junction using mklink
mklink /J "C:\Program Files (x86)\Google\Chrome\Application" "C:\Program Files\Google\Chrome\Application"

Now when I run 
wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
it indicates the current version
Version=116.0.5845.111

Now when I run Cypress it shows the Chrome Browser.
![Chrome in Cypress](https://github.com/cypress-io/cypress/assets/3886512/78ff15bf-aac5-43e4-b342-2d7552bfc930)
