### ISSUE TITLE
More control over checking for spec updates

### ISSUE THREAD

**Issue by marcins** [cypress-io/cypress#2404] opened 2018-08-28 06:32 UTC
### Current behavior:

This line of code: https://github.com/cypress-io/cypress/blob/9d581fdbf1e9a3220d614197bcd0fbaa4a670749/packages/server/lib/open_project.coffee#L150

means that the `testFiles` glob is re-evaluated every 2,500ms. In our project, with over 18,000 files evaluating a glob like `**/*cy-integration.js` takes just over 2,000ms on my machine. This means that Cypress effectively uses 100% CPU as it's constantly re-evaluating this glob. 

We worked around this by creating a plugin that will evaluate the glob once on startup, and create a "fake" glob that's an explicit list of specs, and override the `testFiles` config with this value.

### Desired behavior:

Two changes that could improve the behaviour here are:

* make the interval configurable
* switch from `node-glob` to [`fast-glob`](https://github.com/mrmlnc/fast-glob) - with fast-glob, evaluating the glob above takes approximately 500ms on my machine.

I'm sure there are others as well. I haven't investigated fully, but it seems that `checkForSpecUpdates` runs regardless of the `watchForFileChanges` config option - the config option only applies when actually sending the change notification in `server/lib/socket.coffee`. 

Possibly another fix would be to not re-run `checkForSpecUpdates` if `waitForFileChanges` is disabled, but I'm not sure because I haven't fully comprehended the code yet.

### Versions

Cypress 3.1.0 on macOS 10.13.6

**Comment by chrisbreiding** [comment] 2018-08-30 13:17
`watchForFileChanges` relates to watching the spec file contents and re-running the tests. It doesn't currently affect watching the file list for changes. I think we've talked in the past about changing it to something like `rerunSpecsOnChange` because that's more accurate. Even when it's `false`, we still technically watch spec files because otherwise they wouldn't be updated when you manually re-run your tests.

Honestly, I don't think this will be a high priority since the majority of users have their tests in `cypress/integration` and won't face this issue since it's not globbing through thousands of files.

But we'd be open to a pull request for any of the proposed changes if you'd like to submit one.

**Comment by jennifer-shehane** [comment] 2020-12-17 09:26
>In our project, with over 18,000 files evaluating a glob like **/*cy-integration.js takes just over 2,000ms on my machine. This means that Cypress effectively uses 100% CPU as it's constantly re-evaluating this glob.

I rolled back to 3.1.0 and was indeed able to reproduce this. My Mac would lock up at 100%+ CPU every 2 secs.

I haven't been able to reproduce this 'constant evaluation of glob' that takes up 100% CPU in our most recent version (6.1.0), so I'm going to close this as resolved. 

For posterity, how I recreated this was basically setting my `integrationFolder` to my `node_modules` which is the largest folder I know :D

`cypress.json`

```js
{
  "integrationFolder": "./node_modules/",
  "testFiles": "**/cache-browser-local-storage.cjs.js" // just pick a random file in node_modules
}
```

**Closed by jennifer-shehane** 2020-12-17 09:26 UTC
Labels: stage: proposal 💡, topic: file watching :eyes:, type: performance 🏃‍♀️
