### ISSUE TITLE
Snapshots not picking up select choices visually

### ISSUE THREAD

**Issue by jameseg** [cypress-io/cypress#4928] opened 2019-08-05 15:57 UTC
### Current behavior:
When using ```cy.select()```, the selections are being made correctly, but the snapshots look like nothing has changed in the app.  If you review your ```select``` commands in Cypress, you'll see default selections and prior values in dropdown menus, etc.

### Desired behavior:

I'd like the snapshots for the selections to accurately represent the choices being made by Cypress.

### Steps to reproduce: (app code and test code)
Use the ```cy.select()``` method on a dropdown menu, select by value or text.  When the test is finished hover over the snapshots Cypress created for any ```select``` you implemented.

https://github.com/jameseg/cypress-test-tiny 
branch: issues/905

### Versions

Cypress:
3.4.0
3.4.1

Windows 10
Chrome 75

**Comment by jennifer-shehane** [comment] 2019-08-07 05:13
Duplicate of https://github.com/cypress-io/cypress/issues/4443

**Closed by jennifer-shehane** 2019-08-07 05:13 UTC
