### ISSUE TITLE
.type() should allow to enter all values that can be typed manually to an input field (valid/invalid)

### ISSUE THREAD

**Issue by rammohankini** [cypress-io/cypress#21267] opened 2022-04-29 13:29 UTC
### What would you like?

I would like .**type()** to support entering invalid values if invalid values can be entered manually to an input field (because of some issue with the field/application)
Using the **cypress real events** plugin (**.realType()**) we can replicate the manual behavior of typing invalid values, but it won't fetch the typed invalid values. 

### Why is this needed?

I want this because as a tester we want to replicate/test from an end-user perspective. Cypress should support entering all values that a user can enter manually.
In our application, there was an issue where an input field of type number was accepting invalid values ex 'e','24--', '--' etc. Using **.type(),** I was not able to enter these values into an input field, even though the field was accepting these values and I was able to enter it manually as well.
In the screenshot below, the input field with the label **TestIntegerYear** is of type **"number"**, and it was accepting invalid values like 'e'. I used the .**type** method and tried entering 'e' to that field to replicate manual behavior. But the .**type()** was not able to enter 'e'. So I used **.realType()** from real events plugin. Using **realType()** I was able to enter the invalid value 'e' but while fetching I was getting an empty string ''. Cypress was not able to fetch that entered invalid value. resulting in assertion getting passed.

**cy.get('locator').clear().focus().realType('e');
cy.get('locator').should('have.value', '');**

![cypress  type()](https://user-images.githubusercontent.com/72487913/165949924-eacb53a1-23f1-4617-97c1-3db820be8d51.png)

### Other

cy.get('locator').clear().focus().realType('e');
cy.get('locator').should('have.value', '');

This assertion was getting passed since the value typed using realType() - 'e' was not returned.
![cypress  type()](https://user-images.githubusercontent.com/72487913/165952702-9ed6f48c-dc2e-48ab-9838-0e37e5ae7630.png)

**Comment by mjhenkes** [comment] 2022-05-02 17:37
@rammohankini, thanks for logging this issue. This seems like a good enhancement to add. We'll be closing this issue as a duplicate of #6150, and any progress can be track there.
Thanks!

**Closed by mjhenkes** 2022-05-02 17:37 UTC
Labels: type: duplicate, topic: cy.type ⌨️, reproducible, stage: new issues
