### ISSUE TITLE
Assertion have.length.above is not working as expected

### ISSUE THREAD

**Issue by emahuni** [cypress-io/cypress#18678] opened 2021-10-28 08:40 UTC
### Current behavior

I have a bunch of elements with `data-test="comment-bubble"`. Getting them is working as intended, but checking their length is the issue when using above.
I can however use `have.length.at.least` as a workaround, but `above` isn't working.

```js
cy.get('[data-test=comment-bubble]').should('have.length.above', 1);
```

 Here are screenshots:

![image](https://user-images.githubusercontent.com/7290508/139218707-4a532ccc-104b-492b-ab74-ac73fb576987.png)

![image](https://user-images.githubusercontent.com/7290508/139218774-c2cadbd2-172a-4677-9a01-f954dec13413.png)

It seems as if it's doing something else other than just checking what it was given.

### Desired behavior

It should pass the test, see above screenshots, since length of get is above 1.

### Test code to reproduce

cy.get('[data-test=comment-bubble]').should('have.length.above', 1);

### Cypress Version

8.6.0

**Comment by kubk** [comment] 2021-10-31 12:39
I am unable to reproduce it on my project. Both these lines pass correctly:

```js
cy.get('[data-cy="tab"]').should('have.length.above', 1);
cy.get('[data-cy="tab"]').should('have.length', 2);
```

If I change value `above` to `2` it fails (which is correct behavior) 
```js
cy.get('[data-cy="tab"]').should('have.length.above', 2);
```

It seems like it's working. Please try to create a minimal runnable reproduction repository.

**Comment by BlueWinds** [comment] 2023-02-23 21:35
Since this issue hasn't had activity in several months, I'm going to close it. Please feel free to file a new one with reproducible steps if you're still seeing problems.

**Closed by BlueWinds** 2023-02-23 21:35 UTC
