### ISSUE TITLE
Server is running but 404s on visit to application during cypress run

### ISSUE THREAD

**Issue by TanvirAlam** [cypress-io/cypress#3245] opened 2019-01-29 17:47 UTC
### Current behavior:

Circle config.yml:

```yml
frontend-test:
    <<: *defaults
    docker:
      - image: cypress/base:8
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:cypress
```

Package.json:

```json
{
    "cypress:run": "cypress run",
    "start": "webpack-dev-server --config ./webpack.config.js --mode development",
    "test:cypress": "start-server-and-test start http://localhost:8080 cypress",
    "cypress": "cypress run",
}
```

cypress:json:

```json
{
    "baseUrl": "http://localhost:8080/",
    "fixturesFolder": "cypress/fixtures",
    "integrationFolder": "cypress/integration",
    "pluginsFile": "cypress/plugins",
    "screenshotsFolder": "cypress/screenshots",
    "supportFile": "cypress/support",
    "videosFolder": "cypress/videos"
}
```

webpack.config.js:

```js
module.exports = {
    entry: "./public/js/app.js"
}
```

### GETTING ERROR:

![circlecieror](https://user-images.githubusercontent.com/3250040/51928387-1c958a00-23f6-11e9-80f8-2ed8f2a6c760.gif)

### Desired behavior:

it says:

```
CypressError: cy.visit() failed trying to load:

http://localhost:8080/login

The response we received from your web server was:

  > 404: Not Found

```

I have been trying this past 4 days, I don't know what is wrong, please help

The front-end is vuejs, hence the login page is `login.vue` which is loading `vue-router`

**Comment by DylanVann** [comment] 2019-01-30 03:47
I'm also having an issue similar to this. 

<img width="265" alt="screen shot 2019-01-29 at 10 46 37 pm" src="https://user-images.githubusercontent.com/1537615/51956988-c9ccca00-2417-11e9-893e-80e4b45a548f.png">

**Comment by jennifer-shehane** [comment] 2019-01-30 05:05
Hey @TanvirAlam, have you been able to look at the screenshots or video of the test failure? 

@DylanVann Be sure you are not experiencing this issue which has a fix pending release. https://github.com/cypress-io/cypress/issues/3045

**Comment by DylanVann** [comment] 2019-01-30 05:12
@jennifer-shehane Yes that was actually my issue, thanks for the help 🙏 .

**Comment by TanvirAlam** [comment] 2019-01-30 08:52
@jennifer-shehane Kindly look at the following screenshots:
![login page -- see the login page -- before each hook failed](https://user-images.githubusercontent.com/3250040/51969463-c3b90680-2474-11e9-8cc7-0c845c3860f1.png)

**Comment by jennifer-shehane** [comment] 2019-01-30 08:55
@TanvirAlam Hmm, do you have a video of this test run? It doesn't look like this captured before `cy.visit()` resolved.

**Comment by TanvirAlam** [comment] 2019-01-30 09:00
@jennifer-shehane yes I got the video but its `mp4` git doesn't support to upload

**Comment by TanvirAlam** [comment] 2019-01-30 09:02
@jennifer-shehane 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3250040/51969996-15ae5c00-2476-11e9-81a7-573e5a4dcf1b.gif)

**Comment by embiem** [comment] 2019-01-30 10:10
We're experiencing a similar issue right now. It looks like cypress reloads the whole page with the baseUrl of the site we want to test instead of cypress's baseUrl. In more detail:

When no baseUrl is set, we see the test page (where the tests are listed on the left side) at the url `http://localhost:56113/__/#/tests/integration\myTestFolder\myTest.spec.js` and once we go into the first test and call cy.visit(), the whole page reloads with the `http://localhost:3000/__/#/tests/integration\myTestFolder\myTest.spec.js` URL, which of course is a 404 on our website. The whole test run is then stuck. It pretty much looks like in the gif @TanvirAlam posted above, where the blank at the end is loading our website which then shows the 404 page.

When we have the baseURL set, the test window immediately loads the 404 page. The actual test window is not shown.

This only happens when running the tests in Chrome, but works when running in Electron. We have a dependency on Chrome because of our CI setup.

**Comment by OussamaBaybay** [comment] 2019-01-30 10:49
@embiem  

https://github.com/cypress-io/cypress/issues/1872#issuecomment-450807452

**Comment by embiem** [comment] 2019-01-30 11:05
@OussamaBaybay thanks, that fixes our issue!

**Comment by TanvirAlam** [comment] 2019-01-30 11:06
@embiem should I remove the `baseURL` from cypress.json?

**Comment by beagleknight** [comment] 2019-01-30 11:07
I am experiencing the same issue @embiem today but yesterday was working fine. I tried @OussamaBaybay suggestion but now it doesn't work during the first run because the full page reload is killing the cookies (I think). If I reload the Cypress chrome instance when using `cypress open` it works thought.

**Comment by embiem** [comment] 2019-01-30 11:07
@TanvirAlam no, it works for us now with baseUrl in cypress.json

**Comment by embiem** [comment] 2019-01-30 11:59
>  I don't understand why this was working yesterday without the patch 😞

As far as I understood #1872 it has to do with a chromium update. So if your Chrome browser was updated between yesterday and today, this might be the reason.

**Comment by jennifer-shehane** [comment] 2019-04-25 08:14
I noticed some of the other commenters problems were related to a bug that was fixed in Cypress version 3.1.5. 

@TanvirAlam Can you verify this error is still occurring in version 3.1.5+

**Comment by TanvirAlam** [comment] 2019-04-26 10:14
@jennifer-shehane Yes, I will check and let you know as soon as i can

**Comment by jennifer-shehane** [comment] 2019-06-03 08:48
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Closed by jennifer-shehane** 2019-06-03 08:48 UTC
Labels: stage: awaiting response

**Comment by spiray** [comment] 2019-10-25 14:37
@jennifer-shehane I am having this issue on 3.4.1. I am using GitHub Actions and it works for me perfectly locally.

**Comment by colbyallenc** [comment] 2019-11-08 03:51
set a `baseUR`  in your `cypress.json` file

**Comment by jennifer-shehane** [comment] 2020-01-03 07:48
@spiray Please open a new issue and provide a fully reproducible example.
