### ISSUE TITLE
Can we disable baseUrl from the command line

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7800] opened 2020-06-24 18:40 UTC
Cypress v4.8.0

Imagine we have `cypress.json` with `baseUrl` (and lots of other settings)

```json
{
  "baseUrl": "http://localhost:5005"
}
```

We want to run component tests, they don't require `baseUrl`, but attempting to run them hits the base URL check

```
Cypress could not verify that this server is running:

  > http://localhost:5005

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
```

I can try blanking `baseUrl` using CLI but

```
$ yarn cypress:run --spec 'src/**/*_spec.jsx' --config baseUrl=
yarn run v1.22.4
$ cross-env TZ=America/New_York node ../../scripts/cypress run --project . --spec 'src/**/*_spec.jsx' --config baseUrl=
We found an invalid configuration value:

Expected `baseUrl` to be a fully qualified URL (starting with `http://` or `https://`). Instead the value was: `""`
```

I tried disabling it using `false` like some other settings allow, but no success

```
$ yarn cypress:run --spec 'src/**/*_spec.jsx' --config baseUrl=false
yarn run v1.22.4
$ cross-env TZ=America/New_York node ../../scripts/cypress run --project . --spec 'src/**/*_spec.jsx' --config baseUrl=false
We found an invalid configuration value:

Expected `baseUrl` to be a fully qualified URL (starting with `http://` or `https://`). Instead the value was: `false`
```

## Proposal

Allow ignoring `baseUrl` by using `--config baseUrl=false` to override `cypress.json` value

**Comment by jennifer-shehane** [comment] 2020-06-25 04:23
Very similar issue to https://github.com/cypress-io/cypress/issues/2918 where users want to reset `baseUrl` back to default of `null` as various stages of testing.

**Comment by timharsch** [comment] 2020-07-01 21:18
I ran into this issue today.   I also note that removing the setting for `baseUrl` in the cypress.json doesn't help because it will default to `http://localhost:3000` and perform the check anyway.

This issue is of interest to me because I'm attempting to move our component tests out of our integration build and into our component build so they can get run by our PR builds (which don't run the app, just some React Testing Library (RTL) tests that I want to replace with Cypress component tests using cypress-react-unit-test).

**Comment by ConfiDeveloper** [comment] 2020-12-30 13:50
Try to unset the Cypress variable : 
$ unset CYPRESS_baseUrl 
you will no longer have this test done : 
Cypress could not verify that this server is running
Then you can use baseUrl at cypress.json or even add some more variables to prefix your cy.visit()

**Comment by timharsch** [comment] 2021-04-24 17:53
> Try to unset the Cypress variable :
> $ unset CYPRESS_baseUrl
> you will no longer have this test done :
> Cypress could not verify that this server is running
> Then you can use baseUrl at cypress.json or even add some more variables to prefix your cy.visit()

That doesn't seem to be a valid work around, see my workflow below.   As of cypress 6.5.0 this problem still exists.  @jennifer-shehane is it possible to run the new Component Test Runner headless?   I still have yet to find a way to run component tests without having the application up & running (again this makes doing cypress component testing in a CI environment for unit test or PR tests difficult because it requires the application stack to be available)

```shell
NOTE: My cypress.env.json contains `"baseUrl": "http://localhost:3000"`

> CYPRESS_BASE_URL=http://localhost:3000 ./node_modules/cypress/bin/cypress  run --spec "**/GenericDialog.cy-spec.jsx"
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
> ./node_modules/cypress/bin/cypress --version
Cypress package version: 6.5.0
Cypress binary version: 6.5.0
Electron version: 11.2.3
Bundled Node version: 12.18.3
> CYPRESS_BASE_URL= ./node_modules/cypress/bin/cypress  run --spec "**/GenericDialog.cy-spec.jsx" 
We found an invalid configuration value:

Expected `baseUrl` to be a fully qualified URL (starting with `http://` or `https://`). Instead the value was: `""`
> unset CYPRESS_BASE_URL
> ./node_modules/cypress/bin/cypress  run --spec "**/GenericDialog.cy-spec.jsx" 
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
```

**Comment by jennifer-shehane** [comment] 2021-04-26 18:23
@timharsch Have you tried the new Component Testing in Cypress 7.0? There's a separate run command now for component tests, `cypress run-ct`, that should address confusion between e2e and component tests.

**Comment by timharsch** [comment] 2021-05-27 17:09
Sure enough, we migrated to Cypress 7 recently and I can confirm running via `cypress run-ct` can run the component tests without the application stack.  We'll just need to tweak our CI jobs to do it that way now,  but I think we are no longer blocked here.  Thanks for the follow up on this.  @bahmutov Does it make sense to close this enhancement request in light of the new component test runner?

**Comment by jennifer-shehane** [comment] 2023-12-16 03:27
Closing as this is no longer a concern with e2e and ct config being split out in Cypress 10.

**Closed by jennifer-shehane** 2023-12-16 03:27 UTC
Labels: type: enhancement, stage: proposal 💡
