### ISSUE TITLE
Cypress fails to connect to chrome using the GUI

### ISSUE THREAD

**Issue by nickpm21** [cypress-io/cypress#20011] opened 2022-02-02 07:47 UTC
### Current behavior

When running scripts in cypress using the gui, the error message 
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
will appear as Cypress doesn't run the test and insteads open a blank chrome browser instead.
When using Electron or Edge as the browser the tests run fine, additionally when running the 
test suite in headless mode the tests run fine using Chrome as the browser. 
![Screen Shot 2022-02-02 at 1 46 21 AM](https://user-images.githubusercontent.com/70174414/152113566-f5b1366f-e8b3-4114-aa41-4f01e42b7442.png)

### Desired behavior

Connect to the Chrome Browser when using the Cypress GUI

### Test code to reproduce

I've tried this with a blank cypress template repo and have the same results.

### Cypress Version

9.4.0

**Comment by flotwig** [comment] 2022-02-02 15:11
Duplicate of #15650

@nickpm21 in that thread, can you also share what OS you are on?

**Closed by flotwig** 2022-02-02 15:11 UTC
