### ISSUE TITLE
Failed to find body in content Document

### ISSUE THREAD

**Issue by wehnerjp** [cypress-io/cypress#23856] opened 2022-09-16 20:02 UTC
### Current behavior

its .0.contentDocument.body - assert expected <body> not to be empty

### Desired behavior

correctly find the body on the webpage

### Test code to reproduce

its occurring in the beforeEach not relation to any individual test

### Cypress Version

10.8.0

### Node version

v16.16

### Operating System

MacOS current

### Debug Logs

```shell
Timed out retrying after 6000ms: cy.its() errored because the property: contentDocument returned a null value. The property: body does not exist on a null value.

cy.its() waited for the specified property body to become accessible, but it never did.

If you do not expect the property body to exist, then add an assertion such as:

cy.wrap({ foo: null }).its('foo.baz').should('not.exist')

Because this error occurred during a before each hook we are skipping the remaining tests in the current suite:
```

**Comment by nagash77** [comment] 2022-09-19 18:09
@wehnerjp Can you please provide code that reproduces this issue.  There is very little information in this ticket that would give our engineers a place to begin to reproduce this issue.

**Comment by vpkhachane** [comment] 2022-09-27 10:43
I am facing same issue . Any update on it

Code:

```
const iframe = cy
          .get("#atlwdg-frame", { timeout: 7000 })
          .its("0.contentDocument.body")
          .should("be.visible")
          .then(cy.wrap);

        iframe.find(help.submitButton).click();
```

**Comment by mjhenkes** [comment] 2022-09-29 16:15
@vpkhachane is the iframe in the same origin as the document? If not you'll have to wait for our iframe support feature.

Could you provide a repo that recreates the issue. It's difficult to determine why contentDocument may return null for body when we don't have access to the running sight. Typically when I put together sample repos I start with https://github.com/cypress-io/cypress-test-tiny

**Comment by mjhenkes** [comment] 2022-10-06 14:24
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by mjhenkes** 2022-10-06 14:24 UTC

**Comment by davidkiama** [comment] 2023-02-01 16:01
> @vpkhachane is the iframe in the same origin as the document? If not you'll have to wait for our iframe support feature.
> 
> Could you provide a repo that recreates the issue. It's difficult to determine why contentDocument may return null for body when we don't have access to the running sight. Typically when I put together sample repos I start with https://github.com/cypress-io/cypress-test-tiny

Is the iframe feature now available? I am facing a similar issue and the iframe is from a different origin

**Comment by mud1387** [comment] 2023-04-20 19:16
Hi Team, I am also facing the same issue with the iframe not being of the same origin. Please advise, on the iframe feature availability?

**Comment by nagash77** [comment] 2023-04-21 12:32
@mud1387 check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by mud1387** [comment] 2023-04-21 13:31
> @mud1387 check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

@nagash77 I posted the question on the community and went through all the previous posts and approaches but nothing seems to be working. Any advise on how to identify the elements within the iframe if it's of a different origin than the document itself?

**Comment by nagash77** [comment] 2023-04-21 13:54
@mud1387 have you read up on [`cy.origin`](https://docs.cypress.io/api/commands/origin)?  That should be what you need to deal with cross origin requests.

**Comment by mud1387** [comment] 2023-04-21 14:20
@nagash77 Yup, I am currently utilizing cy.origin for handling it. The problem is that the scenario is for a payment page, so from the main domain, it redirects to another domain and then the card details are residing inside a frame routing to another domain. So I was able to use cy.origin successfully to redirect the control to the payment page. But within it the iframe elements are not being visible to the testrunner leading to failure. 
I was able to find the below discussion on the issue wherein the user was also having the same problem but no solution in-sight:
https://discord.com/channels/755913899261296641/1088143961115332728

**Comment by nagash77** [comment] 2023-04-21 18:12
@mud1387 please open a new issue with your example and details on how to reproduce what you are seeing.  We will be happy to take a look and see if we can help.

**Comment by RichardODonoghue** [comment] 2023-08-09 04:07
is the iframe rendering something from a different domain? If so you will need to set `chromeWebSecurity: false` in your `cypress.config.json` to get it working. I had the same issue and this is what resolved it.

**Comment by mud1387** [comment] 2023-08-09 20:39
@RichardODonoghue i tried by setting up the chromewebsecurity as false but to no avail. I am still getting the same issue.

**Comment by NathanC** [comment] 2023-09-08 20:59
We're also getting this same issue, and chrome web security is false. Perhaps there was a regression since [this blog post](https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/)?

**Comment by adriann-dg** [comment] 2023-10-02 10:03
Hiya guys, did some digging and this was the solution that I found.

1. Disable `chromeWebSecurity` (set to false)
2. Inside your test code add this function as you see fit:

```
const getElemInsideIFrame = (iFrameselector: string, elementSelector: string) =>
  cy
    .get(iFrameselector)
    .find('iframe')
    .then(($el) => {
      if (!$el || $el.length === 0) {
        return cy.wrap(null);
      }
      return cy.wrap($el[0].contentWindow?.document.body.querySelector(elementSelector));
    });
```

Notice how I've used `contentWindow` instead of `contentDocument`. I found it on a tutorial [here](https://learn.microsoft.com/en-us/previous-versions/troubleshoot/winautomation/process-development-tips/web-automation/get-an-element-from-within-an-iframe-with-javascript). An oldie but a goodie.

Essentially, imagine you were in the javascript console in your browser and you were searching for an element inside an iframe there. Whatever is returned I wrap up and send back to cypress for more chaining and testing code.

NOTE. Make sure the iframe is fully loaded before calling this. Lest the content of the iframe will return null and make your tests flaky. I personally used `cy.intercept` and `cy.wait` to check when certain network requests were complete and then run my iframe automation testing code
