### ISSUE TITLE
Allow to reset session on demand

### ISSUE THREAD

**Issue by stychu** [cypress-io/cypress#26091] opened 2023-03-13 23:12 UTC
### What would you like?

I found working with the `session` to be a really bad user experience. Whenever I was testing validate function I got multiple times into the state that my session was already cached and I can't do anything about it other than restart the whole Cypress open process to get rid of the session.

```
This session already exists. You may not create a new session with a previously used identifier. If you want to create a new session with a different validate function, please call cy.session() with a unique identifier other than... 
```

Whenever this error occurs allow user to see current sessions and  click `Clear all session`. Can't understand why it's hidden at this point.

### Why is this needed?

To allow easy manual session prune in order to develop flawlessly. Currently you have to kill the cypress and run again in order to run the test when the error occurs

**Comment by emilyrohrbough** [comment] 2023-03-14 18:50
@stychu Thank you for details! This is a duplicate of this feature requests to add a `cy.clearSession()` command - see https://github.com/cypress-io/cypress/issues/17991.

Mind adding adding a thumbs up to the existing issue?

Going to close this in favor of https://github.com/cypress-io/cypress/issues/17991.

**Closed as not planned by emilyrohrbough** 2023-03-14 18:50 UTC
