### ISSUE TITLE
Chromium Renderer process just crashed

### ISSUE THREAD

**Issue by dummulokesh2105** [cypress-io/cypress#28690] opened 2024-01-11 14:01 UTC
### Test code to reproduce

unable to share my repisitory

### Cypress Mode

cypress run

### Cypress Version

12.17.4

### Browser Version

Electron 106(headless)

### Node version

16.20.1

### Operating System

12.7.1

### Other

![image](https://github.com/cypress-io/cypress/assets/150820743/8616aa1e-0921-43b3-8813-f2c8ae16d568)

**Comment by akshaygupta5233** [comment] 2024-01-11 14:54
Even I am also stuck in this from last many days.
The moment I increase the load of tests, it throws this error.
I tried the experimental feature and other provided fix from Cypress docs, but its  not helping!

**Comment by jennifer-shehane** [comment] 2024-01-11 15:38
Could you try updating to the latest Cypress version? 

Unfortunately we'll need a reproducible example to be able to track down and address the issue. Without that we'll need to close the issue.

**Comment by kateengstrom** [comment] 2024-01-18 16:18
Same issue, but can't share my code either... Only since upgrading to Cypress 13 from 12, which went smoothly otherwise...

**Comment by bensouth** [comment] 2024-02-09 16:05
Same issue for me. I am running 7 tests inside one spec and this happens, and now I am blocked and so is our company.

**Comment by jennifer-shehane** [comment] 2024-02-27 15:25
Duplicate of https://github.com/cypress-io/cypress/issues/27415. I offered some recommendations in this comment: https://github.com/cypress-io/cypress/issues/27415#issuecomment-1966723515

**Closed as not planned by jennifer-shehane** 2024-02-27 15:25 UTC
