### ISSUE TITLE
eq(1) fails to find component if there is a delay (100ms or so) in it appearing

### ISSUE THREAD

**Issue by mike-hogan** [cypress-io/cypress#8430] opened 2020-08-27 09:47 UTC
### Current behavior:

This test fails on the last line:

```js
it("does not wait for eq(1)", () => {
    cy.visit('http://localhost:5000')
    cy.get('button').click()
    cy.get('p').eq(0).contains('Paragraph 0')
    cy.get('button').click()
    cy.get('p').eq(1).contains('Paragraph 1')
})
```
### Desired behavior:

Cypress should wait to find the second paragraph, then continue with the assertion

### Test code to reproduce

https://github.com/mike-hogan/cypress-sync-issue

### Versions

Cypress: 5.0.0
Browser: Chrome 84 and Electron 83
OS X: 10.15.5

**Comment by jennifer-shehane** [comment] 2020-08-27 09:59
Yah, the docs do seem to indicate that the `.eq()` command retries until the element exists, but there is a bit of a flaw in this in that the `cy.get()` will not retry. See [only the last command is retries](https://on.cypress.io/retry-ability#Only-the-last-command-is-retried).

So, the `cy.get()` will always return the single paragraph - then it will retry this array of a single element to look for the 2nd element within it. Definitely a bit weird.

This is a workaround however, below the `cy.get('p')` will retry until there are 2 paragraphs before moving on since there's an assertion chained to it:

```js
it("does not wait for eq(1)", () => {
    cy.visit('http://localhost:5000')
    cy.get('button').click()
    cy.get('p').eq(0).contains('Paragraph 0')
    cy.get('button').click()
    cy.get('p').should('have.length', 2)
      .eq(1).contains('Paragraph 1')
})
```

Another workaround using psuedo selector `:eq(1)`:

```js
it("does not wait for eq(1)", () => {
    cy.visit('http://localhost:5000')
    cy.get('button').click()
    cy.get('p').eq(0).contains('Paragraph 0')
    cy.get('button').click()
    cy.get('p:eq(1)').contains('Paragraph 1')
})
```

**Comment by jennifer-shehane** [comment] 2020-08-27 10:00
This is essentially a duplicate of #3561

**Closed by jennifer-shehane** 2020-08-27 10:00 UTC
