### ISSUE TITLE
Cypress getting into an infinite XHR request loop

### ISSUE THREAD

**Issue by jackfranklin** [cypress-io/cypress#1068] opened 2017-12-14 10:36 UTC
### Current behavior:
When visiting a page on our site through Cypress we're seeing it never complete loading because something causes the XHR requests being made to be made infinitely.

If we look at the Cypress CLI output when running the test we see:

```
GET /xhr/item/alternate-colours/1606925 200 236.222 ms - -
GET /xhr/item/alternate-colours/1606925 200 456.960 ms - -
GET /xhr/item/alternate-colours/1606925 200 288.704 ms - -
GET /xhr/item/alternate-colours/1606925 200 260.936 ms - -
```

This request is only made by our application once; if I got to the page in a browser and watch the network tab I can see that the request is made once. Watching the test through the Cypress UI, I can see that the browser just hangs and becomes unresponsive as all these requests are firing.

I'm not sure what, but something is causing these requests to run again and again and again.

Interestingly, this only happens via `cypress open` and then running the test through the UI. If I do `cypress run` and watch the video, the test does complete and the XHR requests complete as expected.

I'm not sure what extra info is useful here but let me know what I can provide to help with this.

* Operating System: Mac OS X Sierra 
* Cypress Version: 1.1.4
* Browser Version: Chrome 63

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-63) by [Unito](https://www.unito.io/learn-more)

**Comment by bahmutov** [comment] 2017-12-14 14:13
That's a very interesting bug! 
- great that this happens while in the GUI mode, will be simpler to debug
- is there a small reproducible example? We have never seen this behavior and there are a lot of tests around XHR

**Comment by jackfranklin** [comment] 2017-12-14 14:40
I've yet to figure out exactly what the cause here is. The particular XHR code is a `$.getJSON` (from jQuery call) in a React `componentWillMount` lifecycle hook. I don't see why those characteristics would lead to it behaving like this but I'm going to try using a plain `fetch` call and see if that helps.

Is there a way from the Cypress GUI to get to the developer console for the page I'm testing to see if there's any useful information in the console / network tab?

**Comment by jennifer-shehane** [comment] 2017-12-14 15:35
Are you using React 16? I have seen this happen in my React app when running in Cypress when there was an error that was not being handled properly by an ErrorBoundary component. I kind of assumed this was reflective of the behavior of my application though and didn't look at the live application in the circumstance. I fixed my ErrorBoundary problem and it hasn't happened since. I could recreate that circumstance if you think there's any chance this sounds related. :thinking:

**Comment by brian-mann** [comment] 2017-12-14 15:42
@jackfranklin just open your Dev Tools. Everything is in there the same as when you use your application outside of Cypress.

**Comment by jackfranklin** [comment] 2017-12-18 13:44
@brian-mann that's what I thought; but when I open the dev tools they don't work. I'm assuming this is because the browser is locked in an infinite loop of some sorts.

@jennifer-shehane that sounds relevant, I'll do some digging into that. I'll see if I can fix it by using an error boundary to catch any problems.

**Comment by wulfovitch** [comment] 2018-01-09 14:49
We are currently using React 15 and also have this problem. Will an update to React 16 solve this problem as @jennifer-shehane indicates?

**Comment by brian-mann** [comment] 2018-01-09 14:53
This is not possible to track down without a reproducible repo. Cypress works with XHR mocking on a large number of projects including many many react 15 and react 16 projects.

**Comment by paulpruteanu** [comment] 2018-02-22 14:26
I'm facing the same issue, hope the screenshot helps further. One thing that I'm noticing is that recurrence happens when the resource is required via text/plain.
![cypress-failing](https://user-images.githubusercontent.com/8288389/36543587-0f2f80d6-17dc-11e8-8d97-cc8bae71dcdf.png)
The test remains stuck.

**Comment by lsplogi** [comment] 2018-03-01 17:58
We are also facing the same issue while running in the browser, whereas in headless mode its working fine.

![2018-03-01_18-52-37](https://user-images.githubusercontent.com/20560652/36860756-78bb7554-1d82-11e8-83ba-eeeee73dc773.png)

**Comment by jennifer-shehane** [comment] 2018-03-06 19:24
We really need a small reproducible example to begin work on this issue.

**Comment by balmar** [comment] 2018-04-19 14:52
I have just installed cypress via npm. With just the default settings I get into an infinite loop of GET requests after redirecting to the url below. The requests in browser are just like on @lsplogi screenshot. 

**My code:**
```
describe('Cypress infinite loop', function() {
	it('hangs', function(){
		cy.visit('https://evryplace.com/panel');
	})
})
```

**Output:**
```
...
GET /panel/i18n/59858b7/app-webvr_en.json 200 190.868 ms - -
GET /panel/i18n/59858b7/app-webvr_en.json 200 187.331 ms - -
GET /panel/i18n/59858b7/app-webvr_en.json 200 195.618 ms - -
GET /panel/i18n/59858b7/app-webvr_en.json 200 150.965 ms - -
GET /panel/i18n/59858b7/app-webvr_en.json 200 191.312 ms - -
```

**Comment by jennifer-shehane** [comment] 2018-04-20 00:27
Yep, this code does cause this never loading behavior. Thanks @balmar. The behavior looks oddly similar to this other issue's test code I just ran here: https://github.com/cypress-io/cypress/issues/1235#issuecomment-382912229

```js
it('hangs', function () {
  cy.visit('https://evryplace.com/panel/')
})
```

<img width="1357" alt="screen shot 2018-04-19 at 8 22 46 pm" src="https://user-images.githubusercontent.com/1271364/39024556-b4504a14-440f-11e8-9d5a-a26bf71725f9.png">

**Comment by LawJolla** [comment] 2018-04-20 22:11
This was my "welcome to Cypress" bug.  

I went through the tutorial on my project, and then it got stuck in this XHR loop.  I can choose any route too and I get the same response.  In this video recording, I chose a bad route.  It didn't matter -- XHR loop.

https://cl.ly/1z2a1h3a170u

**Comment by nickspiel** [comment] 2018-05-26 22:08
I have also come across this. Anyone come across a fix?

**Comment by matt212** [comment] 2018-10-30 07:37
@jennifer-shehane  , i am also facing same xhr waiting scenario any update or alternative code snippets to place in config files like (commands file  or cypress.json) wherein we would put timeout for xhr to complete and cancel the request and continue with test cases for time being to resolve this bug

**Comment by ayandebbarman** [comment] 2019-11-08 08:11
I am facing this same issue with infinite xhr loop when using wait.. any workaround would be appreciated

**Comment by Jananidevi** [comment] 2019-12-09 09:14
@jennifer-shehane Please help to resolve #5898. It is critical and please let us know if any work around too.

**Comment by SmitharyZach** [comment] 2020-02-04 16:11
I also have this issue. The xhr request will get stuck in an infinite loop when I run Cypress through the GUI. When I run cypress headless it works perfectly fine. The GUI will freeze and I will have to force close it through the activity monitor. It is a web component using React.

**Comment by kriegster108** [comment] 2020-03-03 22:54
@SmitharyZach @jennifer-shehane found a fix for this in terms of a workaround. Simply add a `.as('whateverAliasYouWant')` to the end of the `cy.route()`

**Comment by kriegster108** [comment] 2020-03-03 23:06
@SmitharyZach @jennifer-shehane @ayandebbarman #5898  it appears that if you do a `.then()` after you call route it will prevent the looping. example: `cy.route('messages/*', 'fixture:messages').as('getMessages').then(() => {})`

**Comment by queen-of-code** [comment] 2020-03-11 17:25
I'm experiencing the same - it doesn't always reproduce, but is much more likely to do so when hitting a slower environment.

**Comment by tanyutu** [comment] 2020-04-20 09:49
I also have this issue. The XHR request will get stuck in an endless loop. Any progress for fixing this?

**Comment by ha404** [comment] 2020-05-15 21:55
I just ran into this issue after trying to fix `fetch`: https://dev.to/mjsarfatti/how-to-test-your-fetch-requests-with-cypress-bh5

The culprit was the addition of:
```javascript
Cypress.on('window:before:load', win => {
  delete win.fetch;
});
```

Removing the above fixed my issues.

**Comment by deshiknaves** [comment] 2020-06-18 06:32
I don't know if this is the case for anyone else, but this was happening for me because of a NewRelic script in `index.html`. I'm now conditionally including it by environment.

**Comment by jennifer-shehane** [comment] 2020-07-07 08:41
I can't be sure that this is the actual issue that anyone else in this thread is experiencing since no one else provided a reproducible example. If you're facing this issue and need a fix, we suggest providing a reproducible example - as your issue may be different from the one we have.

---

This issue is still occurring in 4.9.0 with the example below. 

```js
it('hangs', () => {
  cy.visit('https://evryplace.com/panel/');
})
```

#### In Cypress during `cypress open`

The `cy.visit()` does not resolve and the browser locks up in all browsers (Chrome, Electron) during `cypress open`. There are infinite requests that go out every second to `GET /panel/i18n/7fa71d4/app-webvr_en.json`.

<img width="1357" alt="screen shot 2018-04-19 at 8 22 46 pm" src="https://user-images.githubusercontent.com/1271364/39024556-b4504a14-440f-11e8-9d5a-a26bf71725f9.png">

#### In Cypress during `cypress run`

The behavior is actually different during `cypress run`. The `cy.visit()` resolves and the test passes (although it looks like the page doesn't load exactly right still). 

![ezgif-6-76c96ca00058](https://user-images.githubusercontent.com/1271364/86750197-cce3d500-c063-11ea-969f-9c7ff9ad3b1a.gif)


#### Outside of Cypress

Should fully load UI like shown below.

![Screen Shot 2020-07-07 at 2 59 41 PM](https://user-images.githubusercontent.com/1271364/86748499-8477e780-c062-11ea-9c3d-3cfde10c5b0e.png)

**Comment by swiecaJS** [comment] 2020-07-07 09:08
@jennifer-shehane 

Another quick way to reproduce it is trying to visit MS Office login:

```js
  it('can open office online', () => {
    cy.visit('https://www.office.com/launch/excel?ms.officeurl=webapps&auth=2');

    cy.contains('Sign in').should('be', 'visible');
  });
```

Cypress output:
![image](https://user-images.githubusercontent.com/12431424/86755452-f1c75080-c041-11ea-9aba-aa22f29500a8.png)

Expected page:
![image](https://user-images.githubusercontent.com/12431424/86755528-00156c80-c042-11ea-871f-b53c674107cf.png)


I know that there is a redirect, to another page (`https://login.microsoftonline.com/`). I am just trying to login to MS Office online to be able to test Office Add-ins

**Comment by deshiknaves** [comment] 2020-07-09 00:01
For reproducible steps. You can create an any application and use the JavaScript snippet from NewRelic, you'll see these infinite redirects.

**Comment by jennifer-shehane** [comment] 2020-07-09 05:06
@swiecaJS Thanks for providing another repro. This does indeed cause infinite XHR loops where the `cy.visit()` eventually times out.

**Comment by arsfeld** [comment] 2020-07-13 17:17
I've had the same issue described here, but it's only consistently failing when running `cypress run`, with `cypress open` it's inconsistent. 

But I noticed it doesn't happen when using Firefox, so I've switched CI to use Firefox and so far it's ok. 

I really was hoping to test the frontend on Chrome though, so I'm looking forward for a solution.

**Comment by panzarino** [comment] 2020-07-23 20:46
@swiecaJS That's actually a separate issue here. The Office login page has some code that detects if it's running in an iframe, and if so reload itself / make some requests. Cypress works by running everything within an iframe, so that's where this becomes a problem. However, our new system of source rewriting is designed to fix some issues like this, which you can enable by setting `experimentalSourceRewriting` to `true` in your config. This fixes some of the issues that page was having with Cypress, but it still doesn't load yet. That's mainly because we're only rewriting sources from the same domain as the main document, but the page is pulling in some scripts from different domains that (also) contains problematic code for iframes. We'll have to reconsider the way that we handle source rewriting in order to make this page work, cc: @flotwig 

As far as the original issue goes, I've been able to narrow down the issue and am trying to figure out a viable fix.

**Comment by panzarino** [comment] 2020-07-27 01:23
As for the original reported bug, it looks like the underlying issue was actually #7187, which has to do with how our snapshot functionality would accidentally interact with documents using custom elements. A PR #8080 has been created to address this, and fixes the issue initially reported [here](https://github.com/cypress-io/cypress/issues/1068#issuecomment-382766098) with `https://evryplace.com/panel`.

**Closed** 2020-07-28 16:43 UTC
Labels: blocking, internal-priority, stage: needs review, type: bug
