### ISSUE TITLE
Support vite v5 for component testing

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28347] opened 2023-11-16 11:25 UTC
### What would you like?

Cypress component testing should support vite v5 (React, Vue and Svelte) - see announcement [Vite 5.0 is out!](https://vitejs.dev/blog/announcing-vite5) Nov 16, 2023.

### Why is this needed?

According to https://docs.cypress.io/guides/component-testing/overview "Vite 2+" is supported, however in practice only up to Vite `v4` is supported by Cypress `13.x` at this time.

https://github.com/cypress-io/cypress/blob/ab60af86332a2a1c3c65e965dd539f081a28807a/packages/scaffold-config/src/dependencies.ts#L73-L80

### Other

See [Migration from (vite) v4](https://vitejs.dev/guide/migration.html) and note that [the CJS Node API has been deprecated](https://vitejs.dev/guide/migration#deprecate-cjs-node-api).

**Comment by MikeMcC399** [comment] 2023-12-09 12:53
- Following the steps to reproduce on https://github.com/cypress-io/cypress/issues/26849, which installs the latest version of vite, results in the warning:

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

- This is also noted in the issue https://github.com/cypress-io/cypress/issues/28373

**Comment by MikeMcC399** [comment] 2023-12-11 16:43
@jordanpowell88 

The examples in [cypress-io/component-testing-quickstart-apps](https://github.com/cypress-io/component-testing-quickstart-apps) are left using [vite@4.5.1](https://github.com/vitejs/vite/releases/tag/v4.5.1) until this enhancement request is addressed.

**Comment by rstoneIDBS** [comment] 2023-12-11 18:01
I'm currently experiencing issues with component testing when trying Vite 5.0.7 with Cypress 13.6.1. It looks like 'public' folder mapping is broken which (for me anyway) breaks the use of mock service worker amongst other things. Is this likely to be fixed by the work mentioned in this ticket or would you like a new issue raised?

**Comment by juliandreas** [comment] 2023-12-19 12:18
> I'm currently experiencing issues with component testing when trying Vite 5.0.7 with Cypress 13.6.1. It looks like 'public' folder mapping is broken which (for me anyway) breaks the use of mock service worker amongst other things. Is this likely to be fixed by the work mentioned in this ticket or would you like a new issue raised?

Same.

**Comment by MikeMcC399** [comment] 2023-12-19 12:26
@rstoneIDBS / @juliandreas 

Did you try using the latest Vite version [v5.0.10](https://github.com/vitejs/vite/releases/tag/v5.0.10)?

**Comment by juliandreas** [comment] 2023-12-19 12:49
> Did you try using the latest Vite version [v5.0.10](https://github.com/vitejs/vite/releases/tag/v5.0.10)?

Yep.

**Comment by MikeMcC399** [comment] 2023-12-19 12:55
- For comparison PR https://github.com/cypress-io/cypress/pull/25365 from @marktnoonan which updated the support to Vite `v4`. Perhaps somebody has an idea what needs to be done to update to Vite `v5` support?

**Comment by rstoneIDBS** [comment] 2024-01-02 10:42
Just tried again with the latest versions of Cypress (13.6.2) and Vite (5.0.10) and I'm still seeing the same issue.

**Comment by steveworkman** [comment] 2024-01-03 11:30
> > I'm currently experiencing issues with component testing when trying Vite 5.0.7 with Cypress 13.6.1. It looks like 'public' folder mapping is broken which (for me anyway) breaks the use of mock service worker amongst other things. Is this likely to be fixed by the work mentioned in this ticket or would you like a new issue raised?
> 
> Same.

public folder mapping has had a small change in vite 5. In [aligning dev and preview behaviour](https://vitejs.dev/guide/migration.html#align-dev-and-preview-html-serving-behaviour) vite 5 now returns the `index.html` file in more cases, so if you're trying to access `/locales/en.json` which is inside `public` then you need to get `./locales/en.json` instead

**Comment by rstoneIDBS** [comment] 2024-01-03 11:38
> > > I'm currently experiencing issues with component testing when trying Vite 5.0.7 with Cypress 13.6.1. It looks like 'public' folder mapping is broken which (for me anyway) breaks the use of mock service worker amongst other things. Is this likely to be fixed by the work mentioned in this ticket or would you like a new issue raised?
> > 
> > 
> > Same.
> 
> public folder mapping has had a small change in vite 5. In [aligning dev and preview behaviour](https://vitejs.dev/guide/migration.html#align-dev-and-preview-html-serving-behaviour) vite 5 now returns the `index.html` file in more cases, so if you're trying to access `/locales/en.json` which is inside `public` then you need to get `./locales/en.json` instead

Yes, I noticed that in the release notes. I *think* the code that needs to change is part of the Cypress Vite dev server integration - I couldn't see any way of doing this from the consumer side. My app works fine in Vite dev mode (with Vite 5), it only fails when running Cypress component tests.

**Comment by SamGeodynamics** [comment] 2024-01-03 13:49
> Just tried again with the latest versions of Cypress (13.6.2) and Vite (5.0.10) and I'm still seeing the same issue.

as said; it's not working. (cypress v13.6.2 & vite 5.0.10), you **can** press skip, then you are greeted with a huge version mismatch notification.

![image](https://github.com/cypress-io/cypress/assets/62433899/a1362327-ee7c-4c64-9715-4abcf887bd41)

**Comment by juliandreas** [comment] 2024-01-03 14:46
> I _think_ the code that needs to change is part of the Cypress Vite dev server integration - I couldn't see any way of doing this from the consumer side. My app works fine in Vite dev mode (with Vite 5), it only fails when running Cypress component tests.

Same. Imports works fine in the app with Vite 5, but it fails when running Cypress. Changing a path from `/locales/en.json` to `./locales/en.json`, for example, is not helping in that scenario. The Cypress team needs to update their package to support Vite 5.

**Comment by jennifer-shehane** [comment] 2024-02-19 15:07
We'd be open to a PR to help support Vite 5.

**Comment by MikeMcC399** [comment] 2024-02-26 14:51
@jennifer-shehane 

> We'd be open to a PR to help support Vite 5.

Just for the sake of clarity, since I'm the author of this issue, I'm not able to provide a PR to update Cypress for Vite 5 compatibility. I don't have the skills to do this.

**Comment by essenmitsosse** [comment] 2024-02-29 12:13
Giving the hefty sums Cypress charges for their service, asking the community to implement support for the latest version of industry-standard tooling, while ignoring the issue for over four month, seems like pretty bad optics. I understand Cypress itself is free and open source, but the lack of Vite 5 support is a road block for Cypress-only users as well as Cypress cloud customers.

**Comment by waldemarennsaed** [comment] 2024-03-25 11:01
> Giving the hefty sums Cypress charges for their service, asking the community to implement support for the latest version of industry-standard tooling, while ignoring the issue for over four month, seems like pretty bad optics. I understand Cypress itself is free and open source, but the lack of Vite 5 support is a road block for Cypress-only users as well as Cypress cloud customers.

I agree on what @essenmitsosse says. Vite 5 is released for a while now. We are currently migrating our whole stack to Vue 3, including Vuetify 3 and the latest Vite version. I do not understand why the Cypress org does not see their responsibility in keeping their tooling up-to-date.

**Comment by MikeMcC399** [comment] 2024-04-05 11:03
Vite's blog announced [release of 5.1](https://vitejs.dev/blog/announcing-vite5-1.html) in February 2024.

[Vite's GitHub releases](https://github.com/vitejs/vite/releases) currently show `5.2.8` as latest and there is a first appearance of a `6.0.0` alpha version.

**Comment by waldemarennsaed** [comment] 2024-04-05 12:32
> Vite's blog announced [release of 5.1](https://vitejs.dev/blog/announcing-vite5-1.html) in February 2024.
> 
> Vite's [GitHub releases](https://github.com/vitejs/vite/releases) currently show `5.2.8` as latest and there is a first appearance of a `6.0.0` alpha version.

Well, a new major release within two months is really quick. However, Vite 5 is out a while now. IMHO cypress should have supported it already.

**Comment by jennifer-shehane** [comment] 2024-04-11 15:18
We do plan to evaluate the effort to support Vite 5.

**Comment by AtofStryker** [comment] 2024-04-25 16:32
I had some time to build binaries for `vite@5` support if anyone wants to give it a try https://github.com/cypress-io/cypress/commit/d129a641afd33b187ed720d561a573d37b24694d. This is still a work in progress so hoping for feedback to see if there is anything we missed here!

**Comment by rstoneIDBS** [comment] 2024-04-25 16:47
I've just tried this and I still see exactly the same problem. Looking at the code in this fix I can't see anything that addresses how Vite 5 changed how 'public' folders are handled - see comment here https://github.com/cypress-io/cypress/issues/28347#issuecomment-1875223144.
This appears to be what is causing the issue for me as Cypress no longer loads Mock Service Worker correctly which causes my tests to fail.

**Comment by rstoneIDBS** [comment] 2024-04-26 08:59
I've found a fix for the MSW issue :)

I already had a section in my component.js that was configuring the MSW service worker, this also allows you to specify the URL of the worker so I changed it to this:
```
const { worker, graphql } = await import('../../src/mocks/browser');

Cypress.on('test:before:run:async', () => {
  if (worker.context.isMockingEnabled) {
    return;
  }
  return worker.start({
    serviceWorker: {
      url: '../src/public/mockServiceWorker.js',
    },
    // Disable logging of matched requests as this can occasionally result in test failures
    quiet: true,
  });
});

window.msw = {
  worker,
  graphql,
};
```

The key bit is the ``url`` setting as this ensures that MSW loads its code from the correct location.

This fixes MSW, but it won't fix anything else being served from the 'public' directory so it would be good if Cypress could figure out how to handle this in a more generic fashion.

**Comment by whitespacecode** [comment] 2024-04-29 08:07
The issue is still present inCypress  V13.8.1
![image](https://github.com/cypress-io/cypress/assets/37139936/a5ed1101-5490-486e-918b-07130b37ba9c)

**Comment by rstoneIDBS** [comment] 2024-04-29 08:10
> The issue is still present inCypress V13.8.1 ![image](https://private-user-images.githubusercontent.com/37139936/326366535-a5ed1101-5490-486e-918b-07130b37ba9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzg0MDYsIm5iZiI6MTcxNDM3ODEwNiwicGF0aCI6Ii8zNzEzOTkzNi8zMjYzNjY1MzUtYTVlZDExMDEtNTQ5MC00ODZlLTkxOGItMDcxMzBiMzdiYTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA4MDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZWMxZWIyZGJkZDgzZjBlOTdkOTA2ZmM2Y2M5Nzk0MjdiNzQyM2Q2NDVhNGUyYWQ5ODE5ZDkxNTZlNTU2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ibmZKNl22V_day-NJbJaqOidm9Vr-_ibZNm4vjmcuGM)

See https://github.com/cypress-io/cypress/issues/28347#issuecomment-2077703297 - it looks like 13.9.0 might fix this

**Comment by AtofStryker** [comment] 2024-05-08 13:53
> > The issue is still present inCypress V13.8.1 ![image](https://private-user-images.githubusercontent.com/37139936/326366535-a5ed1101-5490-486e-918b-07130b37ba9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzg0MDYsIm5iZiI6MTcxNDM3ODEwNiwicGF0aCI6Ii8zNzEzOTkzNi8zMjYzNjY1MzUtYTVlZDExMDEtNTQ5MC00ODZlLTkxOGItMDcxMzBiMzdiYTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA4MDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZWMxZWIyZGJkZDgzZjBlOTdkOTA2ZmM2Y2M5Nzk0MjdiNzQyM2Q2NDVhNGUyYWQ5ODE5ZDkxNTZlNTU2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ibmZKNl22V_day-NJbJaqOidm9Vr-_ibZNm4vjmcuGM)
> 
> See [#28347 (comment)](https://github.com/cypress-io/cypress/issues/28347#issuecomment-2077703297) - it looks like 13.9.0 might fix this

This did not make it into `13.9.0` since more work needs to be done, but the plan is for me to look back at this in next few days to make sure https://github.com/cypress-io/cypress/issues/28347#issuecomment-2077731063 is addressed as well as other possible breaking changes.

**Comment by AtofStryker** [comment] 2024-05-13 15:03
> I've found a fix for the MSW issue :)
> 
> I already had a section in my component.js that was configuring the MSW service worker, this also allows you to specify the URL of the worker so I changed it to this:
> 
> ```
> const { worker, graphql } = await import('../../src/mocks/browser');
> 
> Cypress.on('test:before:run:async', () => {
>   if (worker.context.isMockingEnabled) {
>     return;
>   }
>   return worker.start({
>     serviceWorker: {
>       url: '../src/public/mockServiceWorker.js',
>     },
>     // Disable logging of matched requests as this can occasionally result in test failures
>     quiet: true,
>   });
> });
> 
> window.msw = {
>   worker,
>   graphql,
> };
> ```
> 
> The key bit is the `url` setting as this ensures that MSW loads its code from the correct location.
> 
> This fixes MSW, but it won't fix anything else being served from the 'public' directory so it would be good if Cypress could figure out how to handle this in a more generic fashion.

Glad you found a work around for this @rstoneIDBS .

I'm currently trying to look into the public path issues but I am a bit stuck. The thread above mentions the [fallback behavior to index.html ](https://vitejs.dev/guide/migration.html#allow-path-containing-to-fallback-to-index-html) and [aligning html preview behavior](https://vitejs.dev/guide/migration.html#align-dev-and-preview-html-serving-behaviour), but the later only applies to html files. I'm struggling to recreate the public path issues at a very basic level since I can see assets still being served from the cypress public path 
![image](https://github.com/cypress-io/cypress/assets/3980464/1c363ca3-1fac-4ca1-8ed2-abe5e419aa7e). 

Pardon my ignorance, but what is it that I am missing? Would either you, @juliandreas , or anyone really, be able to help me reproduce the public path issues so I can work on getting this supported?

**Comment by rstoneIDBS** [comment] 2024-05-14 07:56
In you example above, change line 13 of App.jsx from:
`<img src={viteLogo} className="logo" alt="Vite logo" />`
to
`<img src="/vite.svg" className="logo" alt="Vite logo" />`
This will pull the logo directly from the `public` folder, now if you re-run your Cypress test you will see a broken image where the Vite logo should be. This is simulating the issue I'm seeing with MSW

**Comment by AtofStryker** [comment] 2024-05-14 13:25
> In you example above, change line 13 of App.jsx from: `<img src={viteLogo} className="logo" alt="Vite logo" />` to `<img src="/vite.svg" className="logo" alt="Vite logo" />` This will pull the logo directly from the `public` folder, now if you re-run your Cypress test you will see a broken image where the Vite logo should be. This is simulating the issue I'm seeing with MSW

I appreciate the help! I was able to reproduce the problem on my end. Replacing the `src` with `/vite.svg` yields the asset can't be found and we need to somehow prefix this with the public path (default `/__cypress/src/vite.svg`).

**Comment by rstoneIDBS** [comment] 2024-05-14 16:27
> > In you example above, change line 13 of App.jsx from: `<img src={viteLogo} className="logo" alt="Vite logo" />` to `<img src="/vite.svg" className="logo" alt="Vite logo" />` This will pull the logo directly from the `public` folder, now if you re-run your Cypress test you will see a broken image where the Vite logo should be. This is simulating the issue I'm seeing with MSW
> 
> I appreciate the help! I was able to reproduce the problem on my end. Replacing the `src` with `/vite.svg` yields the asset can't be found and we need to somehow prefix this with the public path (default `/__cypress/src/vite.svg`).

I *think* there might be a way of letting Vite know about additional public directories which I think is what you want to do here - i.e. tell Vite that '/__cypress/src/' is also a public folder. This was where I got to when looking at it before but I couldn't figure out how to configure that part of Vite from the Cypress code that starts the Vite dev server.

Edit: You might need to look at this https://github.com/vitejs/vite/discussions/5129

**Comment by AtofStryker** [comment] 2024-05-14 18:53
> > > In you example above, change line 13 of App.jsx from: `<img src={viteLogo} className="logo" alt="Vite logo" />` to `<img src="/vite.svg" className="logo" alt="Vite logo" />` This will pull the logo directly from the `public` folder, now if you re-run your Cypress test you will see a broken image where the Vite logo should be. This is simulating the issue I'm seeing with MSW
> > 
> > 
> > I appreciate the help! I was able to reproduce the problem on my end. Replacing the `src` with `/vite.svg` yields the asset can't be found and we need to somehow prefix this with the public path (default `/__cypress/src/vite.svg`).
> 
> I _think_ there might be a way of letting Vite know about additional public directories which I think is what you want to do here - i.e. tell Vite that '/__cypress/src/' is also a public folder. This was where I got to when looking at it before but I couldn't figure out how to configure that part of Vite from the Cypress code that starts the Vite dev server.
> 
> Edit: You might need to look at this [vitejs/vite#5129](https://github.com/vitejs/vite/discussions/5129)

I think this actually requires the assets in the specified directories to be on disk. I am wondering if we can accomplish the same thing with a simple proxy?

```
        proxy: {
          '/': {
            target: `${devServerPublicPathRoute}/`,
            bypass: (
              req,
            ) => {
              // If the request comes from the root folder (i.e. the alias public path in Vite v5)
              // then proxy the assets to the public path for them to resolve correctly as they should.
              if (!req.url?.includes(devServerPublicPathRoute)) {
                const proxyPath = `${devServerPublicPathRoute}${req.url}`

                debug(`Proxying request ${req.url} to public path ${proxyPath}`)

                return `${devServerPublicPathRoute}${req.url}`
              }

              return req.url
            },
          },
        },
```

Though I would think you might want the ability to turn this off, especially if your server has more complex middleware and is spoofing an api server, so I don't think this is an ideal/perfect solution by any means. We might be able to narrow it down to just assets

**Comment by AtofStryker** [comment] 2024-05-14 20:08
> > > > In you example above, change line 13 of App.jsx from: `<img src={viteLogo} className="logo" alt="Vite logo" />` to `<img src="/vite.svg" className="logo" alt="Vite logo" />` This will pull the logo directly from the `public` folder, now if you re-run your Cypress test you will see a broken image where the Vite logo should be. This is simulating the issue I'm seeing with MSW
> > > 
> > > 
> > > I appreciate the help! I was able to reproduce the problem on my end. Replacing the `src` with `/vite.svg` yields the asset can't be found and we need to somehow prefix this with the public path (default `/__cypress/src/vite.svg`).
> > 
> > 
> > I _think_ there might be a way of letting Vite know about additional public directories which I think is what you want to do here - i.e. tell Vite that '/__cypress/src/' is also a public folder. This was where I got to when looking at it before but I couldn't figure out how to configure that part of Vite from the Cypress code that starts the Vite dev server.
> > Edit: You might need to look at this [vitejs/vite#5129](https://github.com/vitejs/vite/discussions/5129)
> 
> I think this actually requires the assets in the specified directories to be on disk. I am wondering if we can accomplish the same thing with a simple proxy?
> 
> ```
>         proxy: {
>           '/': {
>             target: `${devServerPublicPathRoute}/`,
>             bypass: (
>               req,
>             ) => {
>               // If the request comes from the root folder (i.e. the alias public path in Vite v5)
>               // then proxy the assets to the public path for them to resolve correctly as they should.
>               if (!req.url?.includes(devServerPublicPathRoute)) {
>                 const proxyPath = `${devServerPublicPathRoute}${req.url}`
> 
>                 debug(`Proxying request ${req.url} to public path ${proxyPath}`)
> 
>                 return `${devServerPublicPathRoute}${req.url}`
>               }
> 
>               return req.url
>             },
>           },
>         },
> ```
> 
> Though I would think you might want the ability to turn this off, especially if your server has more complex middleware and is spoofing an api server, so I don't think this is an ideal/perfect solution by any means. We might be able to narrow it down to just assets

This is a bit of a smell to me. @rstoneIDBS out of curiousity have you tried setting the `devServerPublicPathRoute` to root to fix asset resolution, like this:


#### cypress.config.js
```js
export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },

  component: {
    devServer: {
      framework: "react",
      bundler: "vite",
    },
    devServerPublicPathRoute: '',
  },
});
```

**Comment by rstoneIDBS** [comment] 2024-05-15 08:23
@AtofStryker setting `devServerPublicPathRoute` breaks the test with the following error:
```
> Failed to resolve module specifier '\cypress\support\component.js'
```

**Comment by AtofStryker** [comment] 2024-05-15 11:46
> @AtofStryker setting `devServerPublicPathRoute` breaks the test with the following error:
> 
> ```
> > Failed to resolve module specifier '\cypress\support\component.js'
> ```

@rstoneIDBS I'm struggling to reproduce this error. Are you able to share a reproduction? Also, are you on Windows or running an ESM project?

**Comment by rstoneIDBS** [comment] 2024-05-15 12:40
@AtofStryker all I did was:

1. create a new Vite project (``npm create vite@latest``)
2. selected React & JavaScript
3. install and run Cypress
4. select React + Vite + Component testing.

Modified the ``App.jsx`` file as described above and then changed ``cypress.config`` to include the ``devServerPublicPathRoute`` setting described above - this gave me the described error when running the created Cypress test.

I'm using Windows and the default Vite project is ESM

**Comment by AtofStryker** [comment] 2024-05-15 12:49
> ```js
> devServerPublicPathRoute: '',
> ```

Interesting I did the identical steps and everything works fine. The main difference is that I am not on Windows and am on MacOS 14.3. I bet this is some type of pathing issue specific to Windows. Will try the same steps as well but on Windows.

**Comment by AtofStryker** [comment] 2024-05-15 14:02
> > ```js
> > devServerPublicPathRoute: '',
> > ```
> 
> Interesting I did the identical steps and everything works fine. The main difference is that I am not on Windows and am on MacOS 14.3. I bet this is some type of pathing issue specific to Windows. Will try the same steps as well but on Windows.

@rstoneIDBS After investigating it does look like a pathing issue. Hardcoding some values inside `@cypress/vite-dev-server` gets its going inside windows https://github.com/cypress-io/cypress/commit/37c01ca44f2b69bb86a7dd6fe10b39f7b08d15e3. Exploring solutions and will keep the thread updated.

**Comment by AtofStryker** [comment] 2024-05-15 20:59
@rstoneIDBS are you able to try the binary for windows on this commit https://github.com/cypress-io/cypress/commit/ac6e96d5f1d2d448a225df286347666b77e89e9d?

**Comment by rstoneIDBS** [comment] 2024-05-16 07:50
> @rstoneIDBS are you able to try the binary for windows on this commit [ac6e96d](https://github.com/cypress-io/cypress/commit/ac6e96d5f1d2d448a225df286347666b77e89e9d)?

Just tried it with my test case (mentioned above) and with my real code (using MSW) and it appears to be working fine :) Thanks @AtofStryker 

I guess the Cypress documentation will be updated to mention this - I can imagine others running into it and the solution (devServerPublicPathRoute) isn't obvious so making this discoverable is going to be a challenge.

**Comment by AtofStryker** [comment] 2024-05-16 12:02
> > @rstoneIDBS are you able to try the binary for windows on this commit [ac6e96d](https://github.com/cypress-io/cypress/commit/ac6e96d5f1d2d448a225df286347666b77e89e9d)?
> 
> Just tried it with my test case (mentioned above) and with my real code (using MSW) and it appears to be working fine :) Thanks @AtofStryker

@rstoneIDBS glad it works! 

> 
> I guess the Cypress documentation will be updated to mention this - I can imagine others running into it and the solution (devServerPublicPathRoute) isn't obvious so making this discoverable is going to be a challenge.

This is the tricky part. We don't have a lot of documentation on our bundler dev-servers, but I did add a snippet into the package readme https://github.com/cypress-io/cypress/pull/29518/files#diff-07cdfa8a3a7320f94daa82c1155a2c8de98dc257e0749be5a72dd6789fdfed06R59. Discoverability here is difficult, but it at least gives us something to reference.

**Closed as completed** 2024-05-21 16:49 UTC
Labels: type: enhancement, CT
