### ISSUE TITLE
Potential bug: cy.get(selector).contains(text) inferior to cy.contains(selector, text)

### ISSUE THREAD

**Issue by yanneves** [cypress-io/cypress#6868] opened 2020-03-27 13:18 UTC
Follows #3745

From https://docs.cypress.io/guides/core-concepts/retry-ability.html#Commands-vs-assertions
> If the assertion that follows the cy.get() command fails, then the cy.get() command will requery the application’s DOM again. Then Cypress will try the assertion against the elements yielded from cy.get(). If the assertion still fails, cy.get() will try requerying the DOM again, and so on until the cy.get() command timeout is reached.

### Current behavior:

When using `cy.get(selector).contains(text)`, tests may fail if new matching elements are later added to the DOM.

When using `cy.contains(selector, text)`, tests pass even if new matching elements are later added to the DOM.

### Desired behavior:

Both `cy.get(selector).contains(text)` and `cy.contains(selector, text)` should behave identically.

### Test code to reproduce

Fails:
```js
cy.visit('/wizard')

cy.get('a, button').contains('Next').click() // transitions to next screen
cy.get('a, button').contains('Done').click() // Done button exists on new screen
```

Succeeds:
```js
cy.visit('/wizard')

cy.contains('a, button', 'Next').click() // transitions to next screen
cy.contains('a, button', 'Done').click() // Done button exists on new screen
```

### Versions

Cypress v4.2.0, Linux, Electron

**Comment by jennifer-shehane** [comment] 2020-03-30 09:12
Duplicate of #2640

**Closed by jennifer-shehane** 2020-03-30 09:12 UTC
