### ISSUE TITLE
Test Runner UI Needs Multi-Select Option

### ISSUE THREAD

**Issue by SDESkowronski** [cypress-io/cypress#3589] opened 2019-02-26 00:06 UTC
### Current behavior:
In the test Runner UI I only find the ability to select a single test spec file to run.

### Desired behavior:
I would like to be able to select multiple test specs to run. 

I would also like to be able to select individual tests from a spec file to run as opposed to running the entire spec file. Yes, I know there is a .only() and .skip() function to tack onto the code, but that is not as simple a multi-select in the UI.

I actually came up with what I thought was a cool way to do this, and it works, but my manager has a tough time accepting it since it is "non-standard"...sigh.

**What it would look like:** Just like Windows File Explorer, double click launches whatever you have selected, single click selects, CTRL+single click adds or removes selection, shift+single click selects a range...check boxes could also be used.

### Versions
Cypress v3.0.3 is what I am currently using.
Chrome v72.0.3626.109

**Comment by royalrex** [comment] 2019-04-01 11:46
+1
I'd love to see this feature as well.

Recently been doing a lot of API changes in our product, and then running all specs to find problem areas. After fixing issues in one test, it would be nice to rerun just that, or as @SDESkowronski proposes a way to select what it() statements to run eg. a UI for .skip() and .only()

**Comment by jennifer-shehane** [comment] 2019-04-01 14:30
There is this issue for running a subset of *files*: https://github.com/cypress-io/cypress/issues/3607

Also there is this issue for running a single test (which I think is what this issue is mostly a duplicate of) https://github.com/cypress-io/cypress/issues/925

Closing as duplicate.

**Closed by jennifer-shehane** 2019-04-01 14:30 UTC
Labels: pkg/desktop-gui, pkg/runner, stage: proposal 💡
