### ISSUE TITLE
No output in dashboard report

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#977] opened 2017-11-29 08:59 UTC
- Operating System: Win10
- Cypress Version: 1.1.2
- Browser Version: Firefox, Chrome

### Is this a Feature or Bug?
Bug

### Current behavior:
I run 'example_spec.js' suite and i can't see output in dashboard.

### Desired behavior:
Output should be visible as in demo movie on cypress.io site

### How to reproduce:
1. Run 'example_spec.js' script using for example: 'cypress run --record --key  command

#### Test code:

```js

```

### Additional Info (images, stack traces, etc)
![obraz](https://user-images.githubusercontent.com/34089686/33366577-f1f0271a-d4eb-11e7-92ed-44f32a0b03cd.png)

**Comment by jennifer-shehane** [comment] 2017-11-29 16:26
Could you tell me exactly what browser and OS you were viewing this page in the Dashboard on?

I've attempted to look at the Dashboard's output with some of our projects in Windows 10 in both Chrome 62 and Firefox 57, but do not see any issues. 

It looks as though you are not running the `example_spec` fresh as there is 1 failure in your screenshot. Could you provide the exact tests you ran?

Also, you exposed your record-key in the issue you opened above. This key should remain private. I've removed it from your issue, but you should probably generate a new key to avoid any concerns with it being publicized. https://on.cypress.io/dashboard-service#Identification

**Comment by jennifer-shehane** [comment] 2017-11-29 21:53
Hi @zbigniewkalinowski I was able to track down and fix a css issue that was causing the output screen to scroll independently from the window (which I had a feeling may be your issue just looking from the screenshots). 

If you could, take another look and see if this is fixed. :crossed_fingers:

**Comment by zbigniewkalinowski** [comment] 2017-11-30 09:19
I can't see the difference. I used a example_spec file that is installing with cypress pack when i'm creating new project.

**Comment by zbigniewkalinowski** [comment] 2017-11-30 09:42
and now my account zbigniewkalinowski is corrupted...
I can't see left panel in dashboard and i can't configure projects.
I logged from a different account and performed this test, but still i can't see proper output in my run details... I tried to install cypress in different folder and run it. Still the same.

**Comment by jennifer-shehane** [comment] 2017-11-30 14:45
I'm not sure what you mean by "and now my account zbigniewkalinowski is corrupted", is this related to Cypress?

Could you possibly give more detail on what you are doing to get here? Your OS? Browser? How you installed Cypress? Where you installed Cypress? Where you executed the cypress record? 

There's not much we can do if we cannot reproduce your problem - which we've been unable to do so far from our setup. Thanks.

**Comment by zbigniewkalinowski** [comment] 2017-11-30 15:11
You're asking about things that i wrote. I wrote that this is Windows 10, no matter Chrome or Firefox browser.

1. I installed cypress by 'npm install cypress --save-dev'
2. I got two accounts in github that i'm using to login to Cypress dashboard now. 
3. From account 'zbigniewkalinowski' i can't see left panel in this dashboard (that's why i told you that this account is corrupted and that's why i created new account)
3. I logged on new github account: 'zbylon80'
4. When i'm login to dashbord on 'zbylon80' account i can see left panel - account looks good 
5. When i'm running and recording test using 'cypress run --record --key' command (using test_spec.js file that is installed with Cypress by default) i can't see Output in dashbord. 
6. I can see my runs there, but there is no Output in run's details like on screenshot that i pasted before.

**Comment by jennifer-shehane** [comment] 2017-11-30 15:31
Thanks! This helped and we're currently tracking down the issue.

**Comment by bahmutov** [comment] 2017-11-30 16:30
Confirmed by running `cypress-example-kitchensink` on Windows https://dashboard.cypress.io/#/projects/4b7344/runs/d439db3f-852c-4a67-a670-6bc152be48f2/output

**Comment by brian-mann** [comment] 2017-11-30 16:38
It seems its just a windows problem with the desktop app not collecting `stdout`. Not surprising since Windows is a unique snowflake.

**Comment by zbylon80** [comment] 2017-12-07 13:25
Hello. In new version still no output...

**Comment by bahmutov** [comment] 2017-12-07 14:19
Yes, there was no Windows work in this release.

**Comment by zbylon80** [comment] 2017-12-07 14:39
When can we except some fix for this issue?

**Comment by bahmutov** [comment] 2017-12-07 14:58
We are quite deep in other issues, but please see if you can fix it yourself - https://github.com/cypress-io/cypress/blob/develop/cli/lib/exec/spawn.js

**Comment by brian-mann** [comment] 2017-12-24 23:56
I found the culprit. Electron is doing something special for windows. Instead of calling `process.stdout.write` they are calling their own specially added method `process.log`.

Here's the associated issues and PRs:

- https://github.com/electron/electron/issues/5715
- https://github.com/electron/electron/pull/7578
- https://github.com/electron/node/pull/19/files

The fix here is simple - if `process.log` is defined (or we're on Windows) then use that instead of `process.stdout.write`

**Comment by bahmutov** [comment] 2017-12-25 01:16
Nice find 👍

**Closed** 2017-12-25 02:49 UTC
Labels: OS: windows, stage: investigating

**Comment by brian-mann** [comment] 2017-12-26 22:08
Released in [`1.4.1`](https://docs.cypress.io/guides/references/changelog.html#1-4-1).
