### ISSUE TITLE
cy.route2() doesn't catch req, req is aborted

### ISSUE THREAD

**Issue by ghostika** [cypress-io/cypress#9008] opened 2020-10-28 17:50 UTC
### Current behavior
I have a login page in react and it's calling an API endpoint `POST /api/login`. I had a setup with `cy.route()` what worked, the route was matched and stubbed, but with `cy.route2()` it doesn't work.

### Test code to reproduce
This works:

```js
cy.server();
cy.route({
  method: 'POST', url: '/api/login', status: 401, response: {
    code: 401,
    message: "Invalid credentials"
  }
}).as('login_xhr');
```

![](https://user-images.githubusercontent.com/2512578/97476248-7b32c380-194e-11eb-9093-8440731ea8ba.png)

but this doesn't 

```js
cy.route2('/api/login', {
  statusCode: 401,
  body: {
    code: 401,
    message: "Invalid credentials"
  }
}).as('login_xhr');
```

![](https://user-images.githubusercontent.com/2512578/97476466-b7662400-194e-11eb-981f-30239f893c38.png)

in both cases, the rest of the test looks like this:

```js
cy.get('.tab-pane.active input[name="email"]').type('test@exmaple.com');
cy.get('.tab-pane.active input[name="password"]').type('wrong_pw');

cy.contains('button', 'Login').click();
cy.wait('@login_xhr');
```

### Versions

5.5.0

**Comment by jennifer-shehane** [comment] 2020-10-29 11:28
I'm not 100% sure this is the same issue, but it looks similar. I was able to get this abort reported when I changed the url to `.dev` from `.com`

```js
describe('tests', () => {
  beforeEach(() => {
    cy.route2('api/login', {
      statusCode: 401,
      body: {
        code: 401,
        message: "Invalid credentials"
      }
    }).as('request')
  })

  it('aborted cy.route2()', () => {
    cy.window().then((win) => {
      const xhr = new win.XMLHttpRequest()
      // shows as aborted
      xhr.open('POST', 'https://example.dev/api/login')
      xhr.send()
    })
    cy.wait('@request')
  })

  it('completed cy.route2()', () => {
    cy.window().then((win) => {
      const xhr = new win.XMLHttpRequest()
      // looks fine
      xhr.open('POST', 'https://example.com/api/login')
      xhr.send()
    })
    cy.wait('@request')
  })
})
```

<img width="553" alt="Screen Shot 2020-10-29 at 5 57 46 PM" src="https://user-images.githubusercontent.com/1271364/97562634-5868e380-1a10-11eb-9a0e-83b416f23105.png">

**Comment by ghostika** [comment] 2020-10-29 12:54
@jennifer-shehane aborted is one of the questions but in any case, it's not stubbed with your 2 solutions either.

**Comment by ghostika** [comment] 2020-11-08 12:22
@jennifer-shehane I was able to fix the aborted problem, it was a cors error, I had to specifically add to my stub response, `{ 'access-control-allow-origin': '*' }` even though this was not required with `cy.route()`.

**Comment by jennifer-shehane** [comment] 2020-11-24 08:30
Duplicate of #9264

**Closed by jennifer-shehane** 2020-11-24 08:30 UTC
Labels: internal-priority, pkg/net-stubbing, type: bug
