### ISSUE TITLE
Incorrect screenshots when scroll-behavior is set to smooth

### ISSUE THREAD

**Issue by stevenimhof** [cypress-io/cypress#19032] opened 2021-11-22 11:32 UTC
### Current behavior

I was trying to get a screenshot of an element. The screenshot was only 1 px high. 
When I was using some delay for testing purposes the screenshots were higher but the element was not fully captured. It seemed like there was a wrong scroll offset when the picture was taken.

We have the following css rule:
`:root {
  scroll-behavior: smooth;
}
`

After disabling this css rule , the screenshots were working as desired.

I assume that Cypress should be able to cover that case by itself and not that I have to manually disable the css rule for the tests.

### Desired behavior

The screenshots should always capture the element, regardless of `scroll-behavior`. 

### Test code to reproduce

I created a page with some paragraphs and in the middle was a red box.

Spec-file:

```describe('Test', () => {
  beforeEach(() => {
    cy.viewport(1560, 1440);
  });

  it('should take screenshot', () => {
    cy.visit('/');
    cy.get('#box').screenshot('screenshot-box');
  });
});
```

To reproduce the issue, you can add the following css:

`:root {
  scroll-behavior: smooth;
}
`

I was testing it with Electron 94 and Chrome 96.

### Cypress Version

9.0.0, but the same with 8.7.x

**Comment by chrisbreiding** [comment] 2021-11-22 19:50
Duplicate of #6018

**Closed by chrisbreiding** 2021-11-22 19:50 UTC
