### ISSUE TITLE
move chai from window to Cypress

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3520] opened 2019-02-18 20:53 UTC
it would make more sense to allow the cypress `chai` instance to be accessed via `Cypress.chai` instead of being a global.

I think we should move `chai` onto `Cypress` and deprecate `window.chai`

**Comment by bahmutov** [comment] 2019-02-18 21:01
Yes and also at the same time we should move expect to cy.expect

**Comment by jennifer-shehane** [comment] 2019-02-19 11:11
Duplicate of https://github.com/cypress-io/cypress/issues/280

**Closed by jennifer-shehane** 2019-02-19 11:11 UTC
Labels: stage: proposal 💡, type: breaking change
