### ISSUE TITLE
Application is not rendering the data in drop-down while executing test case from cypress

### ISSUE THREAD

**Issue by Ankitp001** [cypress-io/cypress#29081] opened 2024-03-07 11:26 UTC
### Current behavior

I am testing a UI application developed in Angular version 12. The UI page causing issue have several search fields and several drop downs getting added dynamically based on input values in search fields. As per of testing, first I enter search criteria and search results. basis on that one dropdown gets enabled. In the dropdown, I provide input data and it search like typeahead. On correct selection from first drop-down, I try to search from second drop-down using same pattern. There I am struggling to get any input. The same application (Same codebase and environment) works fine when I try running the scenario manually. However at times, cypress is causing issue in second drop down as described earlier

### Desired behavior

The scenario should work fine irrespective of its within cypress or outside of cypress. In all dropdown, with valid input data should be visible

### Test code to reproduce
```js
cy.intercept(ProviderFacilityDetailsApi).as('facilityDetailsAPI')
cy.xpath(locators.visitReason_cmb).scrollIntoView();
cy.xpath(locators.visitReason_cmb).should('be.visible')
cy.xpath(locators.visitReason_cmb).type(data.visitReason);
cy.xpath(locators.firstVisitReason_opt).click();
cy.xpath(locators.serviceNeeded_cmb).should('be.visible')
cy.xpath(locators.serviceNeeded_cmb).type(data.serviceNeeded);
cy.xpath(locators.firstServiceNeeded_opt).click();
cy.wait('@facilityDetailsAPI').then((res)=>{
cy.xpath(locators.facilitySearch_btn).type(data.facilityName);
cy.xpath(locators.firstFacility_opt).click();
cy.xpath(locators.resourcesSearch_btn).click()
cy.xpath(locators.resourcesSearchbox_txt).type(data.facilityName);
cy.xpath(locators.resourcesSearchbox_txt).click()
})
```

###Application
Refer below Image Here when I select visit reason , Service needed , Facility flow work fine .But when I Search Provider Data not appearing in Drop Down .This flow works fine Manually only in cypress I am facing this issue . 
<img width="400" alt="image" src="https://github.com/cypress-io/cypress/assets/162570799/865d3888-e30d-44fb-a639-2267032f99cf">

I am not providing actual locators since the environment is internal facing and you cant run actual script. However this is something which should help you to understand the page.

### Cypress Version

12.14

### Node version

21.4.0

### Operating System

Amazon Linux 2

**Comment by jennifer-shehane** [comment] 2024-03-07 15:34
@Ankitp001 We'll need a reproducible example in order to investigate, otherwise we'll have to close this issue since we can't find the root cause with this information.

**Comment by Ankitp001** [comment] 2024-03-08 06:49
Hi @jennifer-shehane  Thanks For the response I added steps to reproduce please check it . I can not find any matching code to reproduce and My code contain sensitive data so can not post here . But I added what is exact issue I am facing in steps to reproduce .
Thank You

**Comment by jennifer-shehane** [comment] 2024-03-11 16:50
@Ankitp001 Unfortunately we'll have to close this issue without the ability for us to recreate it ourselves. There are a lot of factors involved and no way for us to investigate with the information given.

**Closed as not planned by jennifer-shehane** 2024-03-11 16:50 UTC
Labels: stage: needs information

**Comment by GraceWangare** [comment] 2025-10-08 13:40
I am experiencing same problem , when I type on search box manullay, the list apppears on drop down ,but not in cypress test. We are also using Angular framework
