### ISSUE TITLE
css nth-child is selecting but cy.eq isn't

### ISSUE THREAD

**Issue by patrickbussmann** [cypress-io/cypress#9634] opened 2020-12-10 22:53 UTC
### Current behavior

    cy.get('tr').eq(2).should('contain', 'Canada')  // should be true but its NOT FOUND

**Error:**

    Timed out retrying: Expected to find element: 1, but never found it. Queried from element: <tr>

And this is working:

    cy.get('tr:nth-child(3)').should('contain', 'Canada')

### Desired behavior

Should find the element because the documentation says it.

### Test code to reproduce

https://docs.cypress.io/api/commands/eq.html#Index

```html
<table>
  <tr>
    <th>Breed</th>
    <th>Origin</th>
  </tr>
  <tr>
    <td>Siamese</td>
    <td>Thailand</td>
  </tr>
  <tr>
    <td>Sphynx</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Persian</td>
    <td>Iran</td>
</table>
```

### Versions

**Cypress version:** 6.1.0
**Google Chrome:** 87.0.4280.88 (64-Bit)

**Comment by bahmutov** [comment] 2020-12-10 22:57
Please click on each command in the command log on the left to see what TR elements the cy.get command finds, then click on the eq command gets.

**Comment by patrickbussmann** [comment] 2020-12-10 23:03
@bahmutov I already tried to debug it.
But it absolutly makes no sense:
It shows the first tr and the `.eq(2)` fails.

```
<tr>
    <th>Breed</th>
    <th>Origin</th>
</tr>
```

So it selects the first one instead of all the `tr` elements...

What could it be?

**Comment by jennifer-shehane** [comment] 2020-12-11 05:00
@patrickbussmann With the code given, I can't reproduce the situation you're describing. 

As Gleb mentioned above, you may need to investigate more on what the `cy.get('tr')` is returning at the time the command runs. Perhaps your application isn't fully loaded for some reason. 

You could click on the GET command in the command log to see what `tr`'s it is returning, or add a `.pause()` to pause the commands to see what is rendered in the application at that time. 

Or perhaps there's another issue, we'd be happy to look at if you provide a reproducible example for us to run. For now, we will be closing, but will reopen if a reproducible example is provided that indicates a bug. 

```js
// pause and see what's rendered in our app
cy.get('tr').pause() 
.eq(2).should('contain', 'Canada')  
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('tr').eq(2).should('contain', 'Canada')        // passes
  cy.get('tr:nth-child(3)').should('contain', 'Canada') // passes
})
```

`index.html`

```html
<html>
  <body>
    <table>
      <tr>
        <th>Breed</th>
        <th>Origin</th>
      </tr>
      <tr>
        <td>Siamese</td>
        <td>Thailand</td>
      </tr>
      <tr>
        <td>Sphynx</td>
        <td>Canada</td>
      </tr>
      <tr>
        <td>Persian</td>
        <td>Iran</td>
    </table>
  </body>
</html>
```

<img width="752" alt="Screen Shot 2020-12-11 at 11 29 01 AM" src="https://user-images.githubusercontent.com/1271364/101865226-194bb780-3ba4-11eb-8e5e-a4b0198c28a4.png">

**Closed by jennifer-shehane** 2020-12-11 05:00 UTC

**Comment by brahimkraiem** [comment] 2022-08-12 12:43
@jennifer-shehane  Hi, i can 't type a date  i have an error "invalide time date"
this is my line of code  cy.get('#date-rendez-vous').type('16/08/2022');

**Comment by emilyrohrbough** [comment] 2022-08-12 14:14
@brahimkraiem Your comment is unrelated to this issue. Please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) and provide the details asked in the issue templated.

**Comment by dhakalsamundra** [comment] 2022-09-12 07:06
@bahmutov  and @jennifer-shehane , which one is the best approach to use it. Using the `eq` or using directly `tr:nth-child(3)` via the help of the cypress selector?
