### ISSUE TITLE
Top header gets hide in when running test in Cypress. Why is that happening. Kindly see the screenshots attached.

### ISSUE THREAD

**Issue by bilal-bin-zafar** [cypress-io/cypress#7423] opened 2020-05-19 19:37 UTC
![cypress_more filters](https://user-images.githubusercontent.com/33050731/82370391-eab49680-9a31-11ea-9044-fc30d65697f2.png)
![Airbnb_more_filters](https://user-images.githubusercontent.com/33050731/82370414-eee0b400-9a31-11ea-9027-f2bf1e0eee42.png)

**Comment by jennifer-shehane** [comment] 2020-05-20 08:18
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

**Closed by jennifer-shehane** 2020-05-20 08:18 UTC

**Comment by bilal-bin-zafar** [comment] 2020-05-20 09:11
Current behavior:
Top header as in screenshots gets hide.

Desired behavior:
Top header should be visible in cypress

Test code to reproduce
describe('Unlayer Automation', function ()
{

    it('Airbnb', function()
    {

        cy.visit('https://www.airbnb.com/');
        cy.get('._1spzot3').type('italy').click({force:true})
        cy.wait(2000)
        cy.get('#Koan-query__option-0 > ._1825a1k > ._91tt0g').click({force:true})
        cy.get('body > div:nth-child(7) > div > div > div > div._16grqhk > div._siy8gh > div > div._3hmsj > div > div > div > div > form > div > div._1wqpgwk > div:nth-child(3)').click({force:true})
        cy.get('body > div:nth-child(7) > div > div > div > div._16grqhk > div._siy8gh > div > div._3hmsj > div > div > div > div > form > div > div._1wqpgwk > div:nth-child(3) > div > div > div > div > div > div > div._14676s3 > div._1foj6yps > div > div:nth-child(2) > div > table > tbody > tr:nth-child(4) > td:nth-child(4)').click({force:true})
        cy.get('body > div:nth-child(7) > div > div > div > div._16grqhk > div._siy8gh > div > div._3hmsj > div > div > div > div > form > div > div._1wqpgwk > div:nth-child(3) > div > div._1w7uj89a > div > div > div > div > div._14676s3 > div._1foj6yps > div > div:nth-child(2) > div > table > tbody > tr:nth-child(5) > td:nth-child(6)').click({force:true});
        cy.wait(5000)//.end();
        cy.get('._4poulv').click({force:true})
        cy.get('#stepper-adults > button:nth-child(3)').click({force:true})
        cy.get('#stepper-adults > button:nth-child(3)').click({force:true}) // Selecting 2 adults
        cy.get('#stepper-children > button:nth-child(3)').click({force:true}) // selecting 1 child
        cy.get('._m9v25n').click({force:true}) // searching related result
        cy.wait(5000)
      //  cy.get('_14i3z6h').contains("Stays in Italy")
        // cy.log();
        cy.get('#menuItemButton-dynamicMoreFilters > ._1wc4ltr').click({force:true})
       
       
     cy.get(':nth-child(6) > ._9fvlwj0').scrollIntoView()
     cy.wait(5000)

Versions
Chrome web latest with Cypress latest version.

**Comment by bilal-bin-zafar** [comment] 2020-05-21 14:59
@jennifer-shehane Kindly reopen this issue. Thanks

**Comment by jennifer-shehane** [comment] 2020-07-14 09:02
I'm unable to reproduce this from the code provided. Likely because the selectors are now out of date with airbrbs site. I would suggest targeting elements with a more unique identifier instead of a deeply nested identifier in general, as they tend to be very brittle - subject to any change on the website. 

Please provide a reproducible example and we can reopen.

<img width="820" alt="Screen Shot 2020-07-14 at 3 32 15 PM" src="https://user-images.githubusercontent.com/1271364/87406772-370df400-c5e7-11ea-812c-1031b07b1439.png">
