### ISSUE TITLE
Corrupted cache files created on Win 10 64bit, resulting with "Can't start server" permanent state

### ISSUE THREAD

**Issue by mr-gb** [cypress-io/cypress#4192] opened 2019-05-14 12:48 UTC
### Current behavior:

When running test spec, after few initial successful launches, Cypress got stuck in a state that does not allow to run the test spec. Upon trying to launch a suite "Opening Chrome" status is displayed and after several seconds the following error message is displayed:

![image](https://user-images.githubusercontent.com/44611955/57696395-f4eaca80-7650-11e9-82e0-3902780f993c.png)

I've turned debugging on using 

`set DEBUG=cypress:* `

but logs don't provide any more data:

```  
cypress:server:events send error: { 
  Error: EPERM: operation not permitted, lstat 'C:\Users\amg016\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_0'   
  cause: { 
    Error: EPERM: operation not permitted, lstat 'C:\Users\amg016\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_0'   
  errno: -4048, 
  code: 'EPERM', 
  syscall: 'lstat', 
  path: 'C:\\Users\\amg016\\AppData\\Roaming\\Cypress\\cy\\production\\browsers\\chrome\\interactive\\CypressCache\\Default\\Cache\\data_0' }, 
  isOperational: true, 
  errno: -4048, 
  code: 'EPERM', 
  syscall: 'lstat', 
  path: 'C:\\Users\\amg016\\AppData\\Roaming\\Cypress\\cy\\production\\browsers\\chrome\\interactive\\CypressCache\\Default\\Cache\\data_0' } +2ms`

Trying to manually delete the cache file referred fails - Windows provides strange message **Access is denied**, even thought I'm logged in account with local admin privileges. Further digging shows up that indeed the file is strange, as Windows doesn't provide **Owner** attribute of the file at all!
![image](https://user-images.githubusercontent.com/44611955/57697462-8eb37700-7653-11e9-8ab0-c8db116d424b.png)

(didn't know that it's possible to create a file without an owner on NTFS ???).

After digging on M$ pages I've found out that such behavior (messages like **Access Denied** even though I'm an admin) is a result of corrupted file - in order to delete the file, first chkdsk  operation has to be scheduled for the next boot up:
`chkdsk /r` 
the computer then has to be restarted, disk checking operation completed, and then I was able to manually remove the file. After removal of the file, Cypress allowed me to run the spec several times (like 5), then got stuck again.

### Desired behavior:

Cypress shall allow for arbitrary number of subsequent runs of a test spec.

### Steps to reproduce: (app code and test code)

As Current behaviour. I don't think this is related to specific test spec - it is a plain test consiting of opening a page, providing credentials, clicking of submit button, and checking if login was successful.

### Versions
Cypress:
`$ cypress --version
Cypress package version: 3.2.0
Cypress binary version: 3.2.0`

OS = Win 10 64bit

Browser = Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by mr-gb** [comment] 2019-05-14 14:31
Hi @flotwig , the path to the file is the same, i.e. in my case `C:\Users\amg016\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache`. The filename itself falls into `data_{x}` pattern, where `x` is random, single digit number.

**Comment by flotwig** [comment] 2019-05-14 14:53
@mr-gb We do support Windows 64-bit - that documentation is out of date, opened a PR to fix it: cypress-io/cypress-documentation#1680

I'm sorry to hear that you had issues. The unfortunate fact of the matter is that when it comes to development, Windows is not a great OS, and it really shows when you start trying to run something like Cypress, which is a large and complex Node.js application.

The Windows support is definitely not "by accident", and we'll try to get to the bottom of this issue (and the issue you linked). We're also happy to accept PRs that fix any of the Windows-specific bugs, especially since none of our development team uses Windows so it's difficult to track these kinds of bugs down.

**Comment by jennifer-shehane** [comment] 2019-05-22 08:43
Can this issue be closed?

**Comment by kandres2341** [comment] 2019-05-23 21:01
Just coming here to report I have been experiencing this same exact issue.  Same exact file as @mr-gb mentioned, which is `C:\Users\USER\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_0`.

I have noticed on first boot up (when things work) there's a bunch of stuff in the cache.  When the browser window closes, that cache gets cleaned out but that particular file stays.  The whole thing kind of smells like the file handle isn't being freed to me, but I don't know the inner workings of the application to make this kind of claim.

For the record, **_the only way_** I have found to "fix" this issue is by restarting my PC.  It's extremely frustrating.

**Comment by deedee96** [comment] 2019-12-05 22:36
Same issue here. I solved my problem using Electron instead of Chrome. I hope that helps

**Comment by jennifer-shehane** [comment] 2020-05-05 09:18
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-05-05 09:18 UTC

**Comment by shirshendu30** [comment] 2021-01-12 07:16
> Closing as resolved.
> 
> If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
