### ISSUE TITLE
 window env variables are not not accessible while running component test

### ISSUE THREAD

**Issue by rohit-squirrel** [cypress-io/cypress#25752] opened 2023-02-09 09:35 UTC
### Current behavior

While running component test it is giving me an error of undefined for window.env.VAR_NAME, i have all the api endpoints in a single file with env variable.

    cypress version : "^11.2.0"
    "react" : "18.0.0"
    DOM Environment:

### Desired behavior

We can access the app env variable inside cypress components tests.

### Test code to reproduce

When we test for a component which have api endpoints declared as windows.env, it is giving error as undefined for that variable

### Cypress Version

^11.2.0

### Node version

18.12.1

### Operating System

Windows

**Comment by rohit-squirrel** [comment] 2023-02-10 03:24
I have updated the variable from window.env to process.env, but now when i run component tests it is returning me process.env as undefined.
Earlier for E2E testing window.env was working fine without any issues, what is wrong that i am doing which is getting me this error?
My app env and cypress are creating a conflict how can i use the env variable that is defined in my app without any conflict?
Thanks

**Comment by warrensplayer** [comment] 2023-02-10 17:19
@Rk1131 Providing a reproducible example of the issue you're encountering would be the most helpful. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

If I am following your scenario, the reason you are not seeing the same information in your component tests that you can see in your E2E tests is because the component tests do not run your application.  A "best practice" would be for your components to not access global state on `window` and instead have that passed in as a dependency.  If you do want to keep that type of functionality, you would have to bootstrap those values on the window for your component tests.

I may not have totally understood your use case, so a reproduction would be the best way to help.

**Comment by marktnoonan** [comment] 2023-02-17 19:52
I think @warrensplayer hit on the right idea, that global variables not set by the component under test need to be set some other way in component testing. I would suggest doing this from the `support/component.js` file, possibly in a `before` hook like.

This seems more like a question than a Cypress issue, so if you have an example to share or want feedback on specific code, I would suggest moving this conversation to our [Discord server](https://on.cypress.io/chat). Feel free to tag me there, though I suspect other people will answer this before I would get a chance.

I'll close this issue for now.

**Closed as completed by marktnoonan** 2023-02-17 19:52 UTC
