### ISSUE TITLE
"npm run test:e2e" exits to command prompt

### ISSUE THREAD

**Issue by ZwapKillrath** [cypress-io/cypress#5710] opened 2019-11-15 09:43 UTC
### Current behavior:

Brand new Vue project (vue create), install Vuetify (vue add Vuetify)

```
npm install cypress --save-dev
```

package.json:
```json
{
  "name": "democypress",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:e2e": "vue-cli-service test:e2e"
  },
  "dependencies": {
    "@mdi/font": "^4.5.95",
    "core-js": "^3.3.2",
    "material-design-icons-iconfont": "^5.0.1",
    "register-service-worker": "^1.6.2",
    "roboto-fontface": "^0.10.0",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-property-decorator": "^8.3.0",
    "vue-router": "^3.1.3",
    "vuetify": "^2.1.0"
  },
  "devDependencies": {
    "@types/node": "^12.12.7",
    "@typescript-eslint/eslint-plugin": "^2.7.0",
    "@typescript-eslint/parser": "^2.7.0",
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-e2e-cypress": "^4.0.0",
    "@vue/cli-plugin-pwa": "^4.0.0",
    "@vue/cli-plugin-typescript": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "cypress": "^3.6.1",
    "eslint": "^6.6.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-vue": "^6.0.1",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "typescript": "^3.7.2",
    "vue-cli-plugin-vuetify": "^2.0.2",
    "vue-template-compiler": "^2.6.10",
    "vuetify-loader": "^1.3.0"
  }
}
```

"npm run test:e2e" just exits to the command line with no test runner shown.

### Desired behavior:

Want Cypress to show the test runner and ready to manually run tests.

### Steps to reproduce: (app code and test code)

New vue project, add Vuetify and Cypress
npm run test:e2e
(all executed from the project folder)

PS: The test runner opens with "npx cypress open" but not able to hit the pages with cy.visit() - results in "404 page not found" when test scripts are executed.

### Versions
Cypress 3.6.1
Windows 10 64 bit
Chrome etc.

**Comment by trajano** [comment] 2019-11-16 14:04
I am hitting the same issue though I didn't have Chrome installed.  However, installing Chrome didn't help either.

**Comment by trajano** [comment] 2019-11-16 14:08
Also running in `--headless` mode fails

**Comment by trajano** [comment] 2019-11-16 14:16
I got it working by downgrading Cypress.  The last known version that worked for my project was 3.4.1.  

https://github.com/trajano/vue-cordova/blob/v0.1.2/package-lock.json#L3443

So I downgraded `npm install --save-dev cypress@3.4.1`

Upgrading to cypress 3.5 causes it to fail so it appears to be introduced in 3.5

**Comment by ZwapKillrath** [comment] 2019-11-19 08:00
> I got it working by downgrading Cypress. The last known version that worked for my project was 3.4.1.
> 
> https://github.com/trajano/vue-cordova/blob/v0.1.2/package-lock.json#L3443
> 
> So I downgraded `npm install --save-dev cypress@3.4.1`
> 
> Upgrading to cypress 3.5 causes it to fail so it appears to be introduced in 3.5

Yup. Exactly the same here. We are running 3.4.1 at the moment but would like to upgrade to 3.6.
@jennifer-shehane Do you have a resolution for this?

**Comment by trajano** [comment] 2019-11-19 16:02
Not only that I have to downgrade to 3.4.1 of Cypress, but I can't upgrade to Node 12.13 which is LTS.  I think it may work with 12.11

**Comment by ZwapKillrath** [comment] 2019-12-02 11:29
Same problem in 3.7.0

**Comment by jennifer-shehane** [comment] 2019-12-03 07:35
From https://github.com/cypress-io/cypress/issues/5843

![image](https://user-images.githubusercontent.com/49122691/69948089-4c6a5e00-14ef-11ea-84c1-2579e9e89a87.png)

Cypress test runner never starts - just exits to cmd prompt when doing "npm run test:e2e".
(set DEBUG=cypress:* used here)

**Comment by jennifer-shehane** [comment] 2019-12-03 07:40
This is a bit tricky to detect, but this is a duplicate of https://github.com/cypress-io/cypress/issues/5466 - this is isolated to Windows when passing an argument containing a url (such as `baseUrl=https://localhost:3000`, which is what the vue cli does by default. 

We're working on deciding how to move forward with fixing.

**Closed by jennifer-shehane** 2019-12-03 07:40 UTC
