### ISSUE TITLE
Support for Webpack 5

### ISSUE THREAD

**Issue by JulianIsrael** [cypress-io/cypress#15718] opened 2021-03-31 07:06 UTC
### What would you like?
Update cypress to support Webpack 5.

### Why is this needed?
Webpack 5 is the last Webpack release and is becoming more adopted by the community. For repositories where Webpack 5 is already being used, is not possible to use cypress with a file preprocessor.

**Comment by jennifer-shehane** [comment] 2021-03-31 14:41
Duplicate of https://github.com/cypress-io/cypress/issues/8900

**Closed by jennifer-shehane** 2021-03-31 14:41 UTC
