### ISSUE TITLE
Unable to use cypress to automate use cases

### ISSUE THREAD

**Issue by Simran1221** [cypress-io/cypress#7234] opened 2020-05-06 09:29 UTC
### Current behavior:

Certificate Issue 

### Desired behavior:

Should be able to login it using cypress

```js
describe('Openning Sprinklr App', () => {
  it('should load correct url', () => {
    cy.visit('https://space-qa4.sprinklr.com/', { timeout: 10000 })
    cy.url().should('include', 'space-qa4')
    cy.log('before reload')
    cy.reload()
    cy.log('After reload')
  })

  it('wait for 3 secoonds', () => {
    cy.wait(3000)
  })

  it('click on user name field', () => {
    cy.get('input[name=uid]').clear()
    cy.get('input[name=uid]').type('username')
  })

  it('click on the next button', () => {
    cy.get('button').contains('Next').click()
  })

  it('click on password text field', () => {
    cy.get('input[name=pass').clear()
    cy.get('input[name=pass').type('password')
  })

  it('click on submit button', () => {
    cy.get('button').contains('Log in').click()
  })

  it('should wait for 3 seconds'), () => {
    cy.wait(3000)
  }
})
```

### Versions

Chorme, Firefox
[](url)

**Comment by jennifer-shehane** [comment] 2020-05-06 10:50
Hey @Simran1221, I'm unable to run the code as provided. I encounter the error below.

We also **strongly advise you to not share sensitive email and password information** in GitHub issues since this is completely public and could be used by anyone to access your account.

I have deleted the sensititive information from your original comment and also deleted the revision history of the GitHub comment, but still advise you to change any exposed passwords. 

<img width="1467" alt="Screen Shot 2020-05-06 at 5 13 20 PM copy" src="https://user-images.githubusercontent.com/1271364/81168616-56701b80-8fbd-11ea-98de-ac835be19a2b.png">

Please provide a screenshot of the error you are encountering and any way to reproduce the error. If there is sensitive information, you can email us the reproducible example at support@cypress.io. 

Without seeing the error or a way to reproduce we will have to close the issue.

**Comment by id-dan** [comment] 2020-05-06 11:54
Hi, @Simran1221 ! Are you sure that you use correct selector? ;) 

> input[name=pass

```
it('click on password text field', () => {
    cy.get('input[name=pass').clear()
    cy.get('input[name=pass').type('password')
})
```

I think that is correct selector:
- input[name="pass"]

**Comment by jennifer-shehane** [comment] 2020-08-28 09:11
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by jennifer-shehane** 2020-08-28 09:11 UTC
Labels: stage: needs information
