### ISSUE TITLE
Error when using Cypress.log from cy.on uncaught:exception handler

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3513] opened 2019-02-17 03:34 UTC
Cypress 3.1.5

I have an application that throws an error on purpose

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
  <script>
  setTimeout(() => {
    throw new Error('Random problem')
  }, 50)
  </script>
</body>
</html>
```

Before `cy.visit` I set up an exception handler to catch this error. I would like to print the error. If I do `cy.log` from the handler, it affects the current command chain and fails the test

```js
  cy.on('uncaught:exception', (e, runnable) => {
    console.log('error', e)
    console.log('runnable', runnable)
    cy.log('caught error', e)
    return false
  })
  cy.visit('index.html')
  cy.get('foo')
```

<img width="1095" alt="cy-log-from-fail" src="https://user-images.githubusercontent.com/2212006/52907995-ab016c80-323a-11e9-9d35-a450b549f04c.png">

If I use `Cypress.log` then Cypress throws _another_ error

```js
  cy.on('uncaught:exception', (e, runnable) => {
    console.log('error', e)
    console.log('runnable', runnable)
    Cypress.log('caught error', e)
    return false
  })
  cy.visit('index.html')
  cy.get('foo')
```
Error screenshot
<img width="1090" alt="screen shot 2019-02-16 at 10 31 21 pm" src="https://user-images.githubusercontent.com/2212006/52907990-9ae98d00-323a-11e9-9f41-42fdabdca1a9.png">

Seems the code is trying to use current test right away without checking if it is defined

<img width="955" alt="screen shot 2019-02-16 at 10 32 46 pm" src="https://user-images.githubusercontent.com/2212006/52908009-ddab6500-323a-11e9-9b63-303a36b42558.png">

Really the only way to print the error was to use `cy.now`

```js
cy.on('uncaught:exception', (e, runnable) => {
  console.log('error', e)
  console.log('runnable', runnable)
  cy.now('log', 'caught error', e)
  // return true if you WANT test to fail
  return false
})
cy.visit('index.html')
cy.get('foo')
```

**Comment by alaboudi** [comment] 2021-02-25 17:27
You are using Cypress.log incorrectly. trying using `Cypress.log({ message: 'some message'' })`

**Comment by jennifer-shehane** [comment] 2021-02-25 20:18
Cypress commands don't work within event listeners.

Duplicate of https://github.com/cypress-io/cypress/issues/6316

**Closed by jennifer-shehane** 2021-02-25 20:18 UTC
Labels: stage: ready for work, topic: unhandled exceptions ⚠️
