### ISSUE TITLE
videoCompression Option isn't worked

### ISSUE THREAD

**Issue by rockthis13** [cypress-io/cypress#9380] opened 2020-11-30 17:45 UTC
### Current behavior

videoCompression has no effect while changing value or set it to false
![image](https://user-images.githubusercontent.com/59865468/100644695-54e4b700-3344-11eb-895e-cfd4f33c5ca1.png)
so video quality is far from perfect, and this screen is with "videoCompression" false option(which seems no has effect)
the main goal is to make video quality nice in dashboard because now it like pixels 
![image](https://user-images.githubusercontent.com/59865468/100644882-92494480-3344-11eb-8154-b197c52b15b9.png)

### Desired behavior
As in docs
https://docs.cypress.io/guides/references/configuration.html#Videos

Cypress.json
"videoCompression": false,

### Versions

Cypress 6.0

**Comment by jennifer-shehane** [comment] 2020-12-01 04:45
`videoCompression: false` does prevent compression. You can see this in the time that it takes to compress the video after the video is done recording. 

Likely you want to increase the screen size of the machine you are recording in. If you download the video, you'll likely see that the resolution of the video is 12980x720, which is the default. This is just a small size resolution for the video. 

To increase the screen size of the machine when recording, I'd suggest trying these workarounds depending on the browser you're recording in: https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless

**Comment by rockthis13** [comment] 2020-12-02 14:07
@jennifer-shehane Hello! thank you for your reply
Sadly I have no luck with solution you provided, seems it just has no effect
my index.js file:
![image](https://user-images.githubusercontent.com/59865468/100882655-1bcd5380-34b8-11eb-8a19-69c3352665b8.png)
can it be done on cypress side as a fix?
cause we have a paid dashboard plan, and it seems nobody can use video recording for debugging or review purposes, becase it just pixalised
so maybe you can turn this resolution to 1920 1080 wich is standart nowadays HD for most screens
and if some people need bad quality of their videos they can mess up with configs?

**Comment by jennifer-shehane** [comment] 2020-12-22 08:14
Yes, I agree the workarounds are not ideal. I'll close this as a duplicate of https://github.com/cypress-io/cypress/issues/587

**Closed by jennifer-shehane** 2020-12-22 08:14 UTC
Labels: topic: video 📹
