### ISSUE TITLE
Intercept same URL do different thing, but not working

### ISSUE THREAD

**Issue by Kenny-Snub-Nose-Monk** [cypress-io/cypress#26386] opened 2023-03-31 17:14 UTC
### Current behavior

I do three testing in one describe, and intercept URL call '/data/app/', 
I found a bug if I intercept '/data/app/' API   in three different test function. It only will successfully intercept first test function.

### Test code to reproduce

```
describe('testing', () => {

    const api  =  '/data/app/*';

    it("first", () => {
        cy.intercept('GET', api, (req) => { ... // }).as('firstMock');
        cy.wait('@firstMock');
    })

    it("second", () => {
        cy.intercept('GET', api, { body: mockAPIViral }).as('getMockData');
       //fail
        cy.wait('@getMockData');
    })

    it("third", () => {
        cy.intercept('GET', api, { statusCode: 404 }).as('getApi404');
       //fail
        cy.wait('@getApi404');
    })
})
```

### Cypress Version

12.8.1

### Node version

18.14.1

### Operating System

macOS 13.2.1(22D68)

**Comment by astone123** [comment] 2023-04-03 14:14
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/26298

**Closed as not planned by astone123** 2023-04-03 14:14 UTC
