### ISSUE TITLE
Calling .blur() on elements inside iframes throws an error

### ISSUE THREAD

**Issue by alexandernanberg** [cypress-io/cypress#2124] opened 2018-07-11 07:34 UTC
### Current behavior:
When using Cypress together with Storybook there is an issue when calling `.blur()` on an element. Storybook render inside an iframe so my guess is that there is a bug in the `document.activeElement` check inside the `.blur()` function. We should probably loop through all iframes and find the correct `activeElement`. Using the `force` option solves the issue but I feel that this should work without that.

Note that this worked before 3.0.2. 

Error message
```
CypressError: cy.blur() can only be called on the focused element. Currently the focused element is a: <iframe id="storybook-preview-iframe" title="preview" src="iframe.html?" allowfullscreen="" style="width: 100%; height: 100%; border: 0px; margin: 0px; padding: 0px;"></iframe>
```

### Desired behavior:
To not throw an error.

### Steps to reproduce:

https://github.com/alexandernanberg/cypress-test-tiny

Install dependencies and start storybook + cypress
`npm install && npm start`

Run the basic test and the `blur` will throw an error.

### Versions

Cypress: 3.0.2

**Comment by alexandernanberg** [comment] 2018-07-11 08:10
Did some more digging and I think I found the root cause of the problem. In the [`getFocused`](https://github.com/cypress-io/cypress/blob/7c6c8a2838a63f5c49c6837dee1d02d0687a07a9/packages/driver/src/cy/focused.coffee#L5-L25) function we don't check for focus inside iframes at all, which is something I strongly believe we should do and is essential for tools like Storybook to work.

**Comment by jennifer-shehane** [comment] 2021-03-31 18:05
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-03-31 18:05 UTC
Labels: pkg/driver, stage: ready for work, type: bug

**Comment by reintroducing** [comment] 2021-07-28 18:21
@alexandernanberg I realized this is two years old, but I'm stuck on this very same thing (accessing an iframe in storybook and calling a blur from an element that is focused in it) and i can't figure out how to get it working. Did you get this resolved at some point?

I'm having a secondary issue where .focus() inside of an iframe only works if i actually have the browser runner focused as well (if I switch focus to VSCode while the test is running, it'll fail, otherwise itll pass), but thats another issue altogether.

**Comment by AlexanderSesslerPorabo** [comment] 2021-08-06 10:50
+1 on this still being an issue.

**Comment by alexandernanberg** [comment] 2021-08-16 09:25
@reintroducing Was some time ago and sadly I don't remember if I got it to work or not

**Comment by benjpac** [comment] 2022-12-17 00:24
Still happening

**Comment by wylieconlon** [comment] 2023-03-23 20:31
As a workaround I'm using `cy.focused().invoke("blur")`, which seems to work by bypassing the Cypress checks.

**Comment by lashidalgo** [comment] 2023-06-27 23:09
I can confirm that this is still broken and that @wylieconlon's solution above works!

**Comment by mike-plummer** [comment] 2023-06-28 13:38
@lashidalgo If you are able to provide a reproducible example in the latest version of Cypress we'd be happy to take a look. I would recommend opening a new issue since this one is quite old and providing all requested information so we can properly review & prioritize.

**Comment by erango** [comment] 2023-08-30 15:09
We are experiencing the same issue. Our setup is complex, but it can be boiled down to an iframe containing an input field.

**Comment by maria-sanchez-gs** [comment] 2024-05-27 12:02
Still happening here
`cy.get('[testid="mytestid"]').type('name2').blur();`
It types fine on the input filed but randomly fails on blur.

In our case the page is not contained in an iframe.

**Comment by jennifer-shehane** [comment] 2024-06-03 16:32
Please open a new issue with a reproducible example of this issue as this is an older issue that's been closed.
