### ISSUE TITLE
Crash of cypress-io/github-action@v1 after cache restore

### ISSUE THREAD

**Issue by qmphan** [cypress-io/cypress#6219] opened 2020-01-22 08:56 UTC
### Current behavior:

Cypress runner crashed with SIGSEGV when running in Github workflow (cypress-io/github-action@v1 )

```
restoring cache /home/runner/.cache/yarn
primary key yarn-linux-x64-9222cac261f9e33e5589be37df571194a31634791b0dc7f3d8e830ff66c6cbc7a1ee7d17d2ca3a8ac2fc8074c47419012b4462a2291ce932f831891f5810d52c
restoring cache /home/runner/.cache/Cypress
primary key cypress-linux-x64-9222cac261f9e33e5589be37df571194a31634791b0dc7f3d8e830ff66c6cbc7a1ee7d17d2ca3a8ac2fc8074c47419012b4462a2291ce932f831891f5810d52c
/bin/tar -xz -f /home/runner/work/_temp/e8420a58-1763-4056-9800-7e7323a3e047/cache.tgz -C /home/runner/.cache/Cypress
/bin/tar -xz -f /home/runner/work/_temp/c62a5276-0684-4a93-8d37-85a02e34b749/cache.tgz -C /home/runner/.cache/yarn
Cache restored from key: cypress-linux-x64-9222cac261f9e33e5589be37df571194a31634791b0dc7f3d8e830ff66c6cbc7a1ee7d17d2ca3a8ac2fc8074c47419012b4462a2291ce932f831891f5810d52c
Cache restored from key: yarn-linux-x64-9222cac261f9e33e5589be37df571194a31634791b0dc7f3d8e830ff66c6cbc7a1ee7d17d2ca3a8ac2fc8074c47419012b4462a2291ce932f831891f5810d52c
/usr/bin/yarn --frozen-lockfile
yarn install v1.21.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.22s.
Cypress test command: npx cypress run --record --config-file cypress.json --browser chrome --env false
/opt/hostedtoolcache/node/12.14.1/x64/bin/npx cypress run --record --config-file cypress.json --browser chrome --env false
The Test Runner unexpectedly exited via a close event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.0
Error: The process '/opt/hostedtoolcache/node/12.14.1/x64/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:894:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:877:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:777:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/opt/hostedtoolcache/node/12.14.1/x64/bin/npx' failed with exit code 1
##[error]Node run failed with exit code 1
```

### Versions

Cypress 3.8.0

**Comment by msmart** [comment] 2020-01-22 10:57
I've got the same behavior with Cypress Version: 3.8.2

**Comment by Sebastian-Haehnlein** [comment] 2020-01-22 11:46
same here

**Comment by qmphan** [comment] 2020-01-22 12:16
I have changed the cache-key parameter as follows
```
cache-key: node-v12-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
```

And Cypress still couldn't start. You will find the log bellow. Everything worked smoothly until this morning. Was the Github action updated today?

```
using custom cache key "node-v12-on-Linux-hash-4a459757fbeedfa865681a600b217924ac99df8a28768716609e7300648956ff"
restoring cache /home/runner/.cache/yarn
primary key node-v12-on-Linux-hash-4a459757fbeedfa865681a600b217924ac99df8a28768716609e7300648956ff
restoring cache /home/runner/.cache/Cypress
primary key cypress-linux-x64-9222cac261f9e33e5589be37df571194a31634791b0dc7f3d8e830ff66c6cbc7a1ee7d17d2ca3a8ac2fc8074c47419012b4462a2291ce932f831891f5810d52c
Cache not found for input keys: node-v12-on-Linux-hash-4a459757fbeedfa865681a600b217924ac99df8a28768716609e7300648956ff, node-v12-on-Linux-hash-4a459757fbeedfa865681a600b217924ac99df8a28768716609e7300648956ff.
/bin/tar -xz -f /home/runner/work/_temp/e82fc120-a807-474d-b1b4-f7939a039d66/cache.tgz -C /home/runner/.cache/Cypress
Cache restored from key: cypress-linux-x64-9222cac261f9e33e5589be37df571194a31634791b0dc7f3d8e830ff66c6cbc7a1ee7d17d2ca3a8ac2fc8074c47419012b4462a2291ce932f831891f5810d52c
/usr/bin/yarn --frozen-lockfile
yarn install v1.21.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.26s.
/opt/hostedtoolcache/node/12.14.1/x64/bin/npx cypress verify
It looks like this is your first time using Cypress: 3.8.0

```
25l[09:34:10]  Verifying Cypress can run /home/runner/.cache/Cypress/3.8.0/Cypress [started]
[09:34:11]  Verifying Cypress can run /home/runner/.cache/Cypress/3.8.0/Cypress [failed]
25hCypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed: /home/runner/.cache/Cypress/3.8.0/Cypress/Cypress --no-sandbox --smoke-test --ping=816

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.0
25hError: The process '/opt/hostedtoolcache/node/12.14.1/x64/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:894:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:877:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:777:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/opt/hostedtoolcache/node/12.14.1/x64/bin/npx' failed with exit code 1
##[error]Node run failed with exit code 1
```

**Comment by glambert** [comment] 2020-01-22 16:14
Does this fix the issue? https://github.com/cypress-io/cypress/issues/6221#issuecomment-577262510

**Comment by qmphan** [comment] 2020-01-22 20:45
Yes it does! Thank you @glambert!

**Comment by bahmutov** [comment] 2020-01-22 22:13
duplicate of https://github.com/cypress-io/cypress/issues/6184 see workarounds there

**Closed by bahmutov** 2020-01-22 22:13 UTC
Labels: CI: github actions
