### ISSUE TITLE
event is undefined in XHR onload handlers using cypress open

### ISSUE THREAD

**Issue by meastes** [cypress-io/cypress#2859] opened 2018-11-29 16:11 UTC
### Current behavior:

Currently, Cypress will fail if the page uses an onload event handler and relies on data from the event. It appears that the event is undefined when the onload handler is executed. This issue only appears in Cypress 3.1.1 and 3.1.2; it is not present in Cypress 3.1.0 and earlier. Here is the code that fails for me:

```javascript
var request = new XMLHttpRequest();
request.open('GET', 'http://127.0.0.1:8088/', true);
request.onload = function (evt) {
  if (evt.target.status >= 200 && evt.target.status < 400) { // This will fail since evt will be undefined
    console.log('success!');
  }
}
request.send();
```

It also appears that the test will execute fine with `cypress run`. Only `cypress open` has the issue.

### Desired behavior:

Cypress should execute onload event handlers with the correct onload event.

### Steps to reproduce:

An example of the issue is available at https://github.com/meastes/cypress-test-tiny
1. Clone https://github.com/meastes/cypress-test-tiny
1. Run `npm install`
1. Run `npm start` to start the web server
1. Run `npm run cypress:open`
1. Execute the spec.js test
1. Notice that it will fail because the event in the XHR request is undefined

### Versions

Cypress 3.1.2, MacOS 10.13.6, Chrome 70

**Comment by jennifer-shehane** [comment] 2018-11-30 04:33
Thanks so much for providing a repo to reproduce the issue. I can indeed reproduce this running the code provided.

Test code:

```js
it('works', () => {
  cy.visit('http://127.0.0.1:8088');
})
```

Command Log on very 1st run:

<img width="844" alt="screen shot 2018-11-30 at 11 02 04 am" src="https://user-images.githubusercontent.com/1271364/49268717-7bd72c80-f48f-11e8-93ec-e44e1866ec06.png">

Command Log on every run after 1st:

<img width="557" alt="screen shot 2018-11-30 at 10 57 29 am" src="https://user-images.githubusercontent.com/1271364/49268605-c86e3800-f48e-11e8-8535-0ad028ecd7ad.png">

**Comment by lilaconlee** [comment] 2018-12-13 15:56
This was fixed with #2924 and will be part of the next release.

**Closed by lilaconlee** 2018-12-13 15:56 UTC
Labels: priority: high❗️, stage: ready for work, type: regression

**Comment by jennifer-shehane** [comment] 2019-03-13 06:56
This was released in [3.1.5](https://on.cypress.io/changelog#3-1-5).

**Comment by robinrizvi** [comment] 2019-11-26 09:08
Able to reproduce this in 3.6.1 as well

**Comment by jennifer-shehane** [comment] 2019-11-27 08:33
@robinrizvi Please open a new issue detailing a reproducible example since this issue has been resolved. There's likely an edge case we're not handling that we will need to address separately.
