### ISSUE TITLE
Not able to install cypress on windows 7 32 bit

### ISSUE THREAD

**Issue by qasachin** [cypress-io/cypress#2095] opened 2018-07-04 13:10 UTC
Not able to install cypress on my windows 7 32 bit.

1.I have download cypress from https://www.cypress.io/ (By clicking download now option)
2.Zip file get downloaded successfully.
3. I create folder and save that file on my C drive.
4.When I unzip and try to install application I am getting this message.
![image](https://user-images.githubusercontent.com/12164155/42278807-890e38bc-7fb9-11e8-8a40-13daaff524be.png)

**Comment by brian-mann** [comment] 2018-07-04 22:07
We release `ia32` binaries for Cypress. Not seeing why this is incompatible. Can you try downloading from `npm` and see if it makes any difference?

Have you ever been able to install Cypress before?

**Comment by qasachin** [comment] 2018-07-05 05:32
@brian-mann No I am installing it first time.

When I try to install using npm I am seeing this message  & not able to install it.
Please see the screen shots and let me know what I am doing wrong here.
![image](https://user-images.githubusercontent.com/12164155/42304221-c362759e-8042-11e8-8f97-fc3baf24db98.png)
![image](https://user-images.githubusercontent.com/12164155/42304247-e4128888-8042-11e8-869c-1e65e4735b4e.png)

**Comment by qasachin** [comment] 2018-07-09 08:56
@brian-mann Hello Any updates on my problem. It is very urgent for me.

**Comment by brian-mann** [comment] 2018-07-09 16:22
@qasachin unfortunately this appears to be an issue on your end with your terminal. I'm not sure if you don't have node installed or if your command line is messed up, but this isn't a problem with Cypress itself.

I would recommend you go over to the `node` docs and learn how to setup a node project and install dependencies since that appears to be what the problem is.

We release `32bit` binaries for Windows so I'm not sure why you can't use the binary from the direct download. More information is needed on your system.

**Comment by ShreeshailG** [comment] 2019-02-23 18:31
I successfully installed cypress on Windows 7 32 bit through npm

**Comment by ShreeshailG** [comment] 2019-02-23 18:54
Hello brian,
the npm installed the latest cypress (3.1.5) on my windows 7 32 bit system. However, if I run the "cypress open" command from the .bin folder, I get the following error:
It looks like this is your first time using Cypress: 3.1.5
 x  Verifying Cypress can run C:\Users\lenovo\AppData\Local\Cypress\Cache\3.1.5\
Cypress
   → Cypress Version: 3.1.5
Cypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies in
stalled.
----------
spawn UNKNOWN
----------
Platform: win32 (6.1.7600)
Cypress Version: 3.1.5

So, I tried installing the dependency mentioned in "required-dependencies" section, but in vain. Please see below:

D:\Automation\node_modules\.bin>apt-get install xvfb libgtk2.0-0 libnot
ify-dev libgconf-2-4 libnss3 libxss1 libasound2
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

D:\Automation\node_modules\.bin>npm install xvfb libgtk2.0-0 libnotify-
dev libgconf-2-4 libnss3 libxss1 libasound2
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/xvfb failed, reason: geta
ddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-02-23T18_42_30
_727Z-debug.log

**Comment by jennifer-shehane** [comment] 2019-03-06 17:10
Hey @ShreeshailG, where are you running the `cypress open` command from? Is it in a plain terminal (cmd) window or from a terminal within your IDE program? I've read that running from the IDE terminal may cause this issue.

**Comment by jennifer-shehane** [comment] 2019-03-06 17:43
Closing this issue as duplicate of https://github.com/cypress-io/cypress/issues/1554

**Closed by jennifer-shehane** 2019-03-06 17:43 UTC
Labels: type: question

**Comment by flotwig** [comment] 2019-04-08 21:32
We have fixed this by also building for Windows 32-bit.

The code for this is done in [cypress-io/cypress#3877](https://github.com/cypress-io/cypress/pull/3877), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
