### ISSUE TITLE
XHRs Not Logged/Handled (due to Service Workers)

### ISSUE THREAD

**Issue by OmriAharon** [cypress-io/cypress#1716] opened 2018-05-14 08:09 UTC
### Current behavior: 

When running build in webpack 4's `production` mode (but probably not the root cause of this bug), Cypress is not logging XHR requests and not noticing them, hence `cy.route()/cy.wait()` mechanism fails. (These are _not_ fetch requests)
This is probably not the culprit, but haven't thought of anything else that's different yet.

As per [the documentation](https://docs.cypress.io/guides/guides/network-requests.html#Failures): 

> Now we know exactly why our test failed. It had nothing to do with the DOM. Instead we can see that either our request never went out or a request went out to the wrong URL.

But in my case I can see the requests have been made and when running locally (`development` mode) everything works perfectly, no change to the URL.

** Update - seems that when I comment out a test that signs in on a different site (no option to programmatically login) the rest of the tests run fine and *the XHRs are logged*. Somehow, having the first test sign up and then redirect to my own app breaks XHR logging. (Still weird that local setup doesn't suffer from this)

### Desired behavior:
XHR requests are noticed and can be waited upon.

### Steps to reproduce:
Not sure how you can reproduce it yourself.
Local setup with webpack - everything works fine.
Building in production mode (webpack 4) and serving with `http-server` (in order to mock how it runs in the CI which is where I initially spotted the problem) - Cypress is blind to XHRs - they don't appear in the log as well as you can see in the screenshots below. I can see the XHRs request in the network pane and my site loads up as normal. There is no difference in the URL and you can see no XHRs are even logged.
Initially I thought it might be happening because I serve under port 80, but then I changed to a random port and it still didn't work so I ruled it out.

#### Local scenario (everything's fine):

![image](https://user-images.githubusercontent.com/12033595/39985194-77ac6826-5766-11e8-97a2-feab42f734f5.png)

#### Served scenario (XHRs not logged):

![image](https://user-images.githubusercontent.com/12033595/39985097-0664eea4-5766-11e8-8fa0-bc104254ba47.png)
![image](https://user-images.githubusercontent.com/12033595/39985102-0a727a84-5766-11e8-8aa4-8a9382376f73.png)

Anything else I can provide that will help?

### Versions  
MacOS High Sierra 10.13.3
Chrome 66.0.3359.170 (Official Build) (64-bit)
Cypress 2.1.0

**Comment by OmriAharon** [comment] 2018-05-15 06:49
Is it possible that's because I have a `cy.visit(siteA)` and on the subsequent test I have `cy.visit(mySite)`?

And if so, why does it work on a local run?

**Comment by OmriAharon** [comment] 2018-05-18 13:20
To anyone who encounters this situation or similar (external login: initially visiting a different domain then redirecting to own website):
I've managed to workaround by doing a `cy.reload()` afterwards:
```
cy.server({ matchBase: false });
cy.route('/someRequest').as('someRequest');
cy.visit('/');
cy.reload(); // <-- This fixes it
```

Though it would have been nice to get some kind of response from the library devs and not rely on workarounds.

**Comment by jennifer-shehane** [comment] 2018-05-18 14:09
Yeah - it's difficult to address issues without a reproducible example. I wasn't able to detect anything unusual from the information provided, but we'd need an example to run ourselves to give any more insight as to why this didn't work + why the workaround works.

**Comment by OmriAharon** [comment] 2018-05-18 15:49
Thanks @jennifer-shehane for the response.
I understand this is difficult, and unfortunately, this is also a complex scenario to provide reproducible steps for.
I assume as this is not an uncommon scenario, and as Cypress' popularity rises, you will probably face similar issues like this again in the near future. I'm sure there are at least logs that I can provide, and if more information is needed I'd be more than happy to help offline this issue in order to help you guys figure this out.

**Comment by maxime1992** [comment] 2018-05-21 15:34
Hi,

I'm facing the exact same issue.

- A call to AWS cognito happens
- I'm waiting for it
- **The call is logged**
- The `wait` does not see that the call has been done
- **The global counter does not increment for that count**

The relevant piece of code:

```
  cy.server();
  cy.route('POST', `https://sts.amazonaws.com`).as('getToken');
  cy.route('POST', `https://cognito-idp.eu-west-1.amazonaws.com`).as('cognitoRootPost');

  cy
    .get(`cnc-credential-challenge button`)
    .contains('Login')
    .click();

  cy.wait('@cognitoRootPost');
```

As I cannot provide a repro, I've tried to provide a detailed and absolutely beautiful screenshot :+1: 

![e2e-cypress-bug](https://user-images.githubusercontent.com/4950209/40315697-03519826-5d14-11e8-89d0-6ee4235dc407.png)

Notice that the call right after the `wait` is the one I'm expecting.

Clicking on it display what's on the right side. It's the good URL, there's no error.

The wait fail unexpectedly, the global counter is not incremented.

**Context**
I'm currently upgrading to Angular 6.
And as @OmriAharon pointed out, it might be related to Webpack 4 maybe? As they've switched from v3 to 4 between Angular (& Angular-Cli) v5 to 6.

**Comment by OmriAharon** [comment] 2018-05-22 08:36
@maxime1992 Looks like your URLs are mismatched, maybe that's the problem?
You're trying to capture `cognito-idp` but the XHR that got out is `cognito-identity`

**Comment by maxime1992** [comment] 2018-05-22 09:15
@OmriAharon you're right.

BUT, taking a closer look to my network panel, I can see the calls being done to cognito-idp as expected:

![image](https://user-images.githubusercontent.com/4950209/40353022-53b4b250-5da8-11e8-9ff9-ab5ae7ada1b3.png)


A coworker just noticed that too:
![image](https://user-images.githubusercontent.com/4950209/40353127-9faf395a-5da8-11e8-9284-d7b7d48f6562.png)

For some reason it seems that the fetch are not caught by Cypress. Probably related to https://github.com/cypress-io/cypress/issues/95

**Comment by mgalindo** [comment] 2018-05-31 19:17
Since I updated to Cypress 3.0.1, I am seeing something similar but only when I run my tests in Electron 59, the tests run fine in Chrome 66.

**Comment by phellipeandrade** [comment] 2018-06-01 03:33
Maybe related: https://github.com/cypress-io/cypress/issues/1201

**Comment by egucciar** [comment] 2018-06-12 20:06
This is happening to me too...how are we supposed to debug Electron issues?

**Comment by bsmithEG** [comment] 2018-06-13 14:54
I had made a comment in #1201, however, looking at when that ticket was started and my problems now, I felt it's more relevant to comment on this issue instead, because at least for us it looks like this might be a regression with > 3.0.0.

My use case:  I just recently moved to using CircleCI (2.0) with this docker image:
https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/chrome65-ff57, but did this around the same time we bumped our cypress version to 3.0.  Getting the behavior listed above, where none of our tests waitForXHRs seem to be picking up on cy.wait (but verified traffic on the server side).

Moving back to 2.1.0 and the tests work as intended with the same docker image above and same circleci config (minus the change in cypress versions) .

Unfortunately I'll need to go through a little effort to get a reproducible example I can share, because we are doing a few strange things like using blacklisting to intercept certain requests and rewrite them (a work around for hijacking js fetch/imports), but I'll try to isolate that's not a part of the issue and attach a reproducible cypress-tiny-test by the end of the week.

Thanks,

**Comment by bsmithEG** [comment] 2018-06-14 20:54
It seems like it's also the Electron problem for me after all.

I figured out that if you pass invalid command line opts to cypress, it will just run default (which runs defaulted to Electron 59 headless).  I was trying to glob options with the --spec flag like so:

```
cypress run --browser chrome --spec **/*.spec.ts

```

This causes cypress to actually just run as if it were:

```
cypress run
```

Dropping the spec flag runs chrome, which now works correctly for me in terms of the XHR waiting, and I'm back to the original issue involving Electron.

Sorry for the confusion.

**Comment by egucciar** [comment] 2018-06-14 21:06
@bsmithEG i had a similar issue with my tests but i discovered that i had an uncaught exception *only in electron* which prevented my xhr.

**Comment by brian-mann** [comment] 2018-06-14 22:03
@bsmithEG https://github.com/cypress-io/cypress/issues/1953#issuecomment-397446885

**Comment by ShaneMckenna23** [comment] 2018-10-26 21:00
Hey @trydionel @lilaconlee, 
I have just encountered this issue on Circle CI/Electron browser. Has the source of this issue been found? I can see that it has recently been added to sprint 8. If you need help replicating, I can make an example of the issues I'm seeing. Cheers!

**Comment by lilaconlee** [comment] 2018-10-30 16:01
@ShaneMckenna23 We haven't found the source yet and an example reproducing your issues would be helpful!

**Comment by ShaneMckenna23** [comment] 2018-11-08 22:08
Below are some snippets of the behaviour I'm seeing. I can make a working example over a longer timeframe if you are still having trouble solving this.

**Setup:**
React Application built using create-react-app
Cypress:  3.1.0
Circle Ci image:  cypress/base:8


## Circle CI
````
-  run:
	name:  Build the browser app
	command:  cd browser-app && npm run build
-  run:
	name:  Serve the browser app
	command:  cd browser-app && serve -l 3000 -s build
	background:  true
- run:
	name:  Running Cypress tests
	command:  cd browser-app && npm run cy:run
````

## Cypress Test 
````
describe('Find Player',  ()  =>  {
	beforeEach(()  =>  {
		cy.server();
		cy.route('POST',  routes.api.queryForLoginPlayer).as('queryForLoginPlayer');
		cy.visit('http://localhost:3000/');
	});
	
	it('Finds Player sucessfully',  ()  =>  {
		cy.get('[data-cy=email-input]')
		.type(testEmail)
		.should('have.value',  testEmail);
		
		cy.get('[data-cy=email-input-button]').click();
  
		// Only resolves locally
		cy.wait('@queryForLoginPlayer');
});
````

## Cypress local
![local](https://duaw26jehqd4r.cloudfront.net/items/2g3U303H3p3P2A343h2K/%5Bf637f179f850f35e960981a1246f2436%5D_Image%25202018-11-08%2520at%25201.48.25%2520PM.png?v=f9189db3)

## Cypress Circle Ci
![circle ci](https://duaw26jehqd4r.cloudfront.net/items/0U061c0w1H1U0f3W3R1K/Image%202018-11-08%20at%201.57.54%20PM.png?v=8ab64239)

**Comment by vijayadurga259** [comment] 2018-11-27 09:43
Hello

Any one found a workaround to this issue?
Am blocked as waiting for xhr's to finish is very much required in my tests.

**Comment by ShaneMckenna23** [comment] 2018-11-27 16:15
@vijayadurga259 
We have resorted to using `cy.wait(1000)` after API calls until this is resolved.

**Comment by Olgagr** [comment] 2018-11-27 20:14
@vijayadurga259 My problem was that these cancelled XHR requests fail tests. To avoid it I ignore such cancelled XHR requests.

In the support/index.js file:
```
Cypress.on('uncaught:exception', hackToNotFailOnCancelledXHR);
Cypress.on('fail', hackToNotFailOnCancelledXHR);

function hackToNotFailOnCancelledXHR(err) {
  const realError =
    err.message.indexOf("Cannot set property 'aborted' of undefined") === -1;
  if (realError) {
    throw err;
  } else {
    console.log(err);
  }
}
```

The solution was described in the other issue.

**Comment by HinnHabib** [comment] 2019-01-08 08:17
Hi 
I am facing the same issue. But in my case sometimes XHR requests are logged and sometimes not.
So I did this workaround. 
`Cypress.Commands.overwrite('wait', (originalFn, url, options) => {
    if (typeof options === 'string') {
        let aliasName = options.replace('@', '')
        let aliases = Cypress.state().aliases;
        if (!aliases[aliasName]) {
            options = 5000;
        }
    }
    return originalFn(url, options)
});`

**Comment by cintrzyk** [comment] 2019-01-14 21:07
Are you using service workers in production? If so, then try to unregister them before each spec:
```js 
Cypress.Commands.add('unregisterServiceWorkers', () => {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.getRegistrations()
      .then(registrations => registrations.forEach(reg => reg.unregister()));
  }
});
```

```js
beforeEach(() => {
    cy.unregisterServiceWorkers();
});

```

works for me 💃

**Comment by jennifer-shehane** [comment] 2019-04-25 08:38
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by drachum** [comment] 2019-05-02 12:41
> Are you using service workers in production? If so, then try to unregister them before each spec:
> 
> ```js
> Cypress.Commands.add('unregisterServiceWorkers', () => {
>   if ('serviceWorker' in navigator) {
>     navigator.serviceWorker.getRegistrations()
>       .then(registrations => registrations.forEach(reg => reg.unregister()));
>   }
> });
> ```
> 
> ```js
> beforeEach(() => {
>     cy.unregisterServiceWorkers();
> });
> ```
> 
> works for me

@cintrzyk just to tell that of more than 20 Cypress issues with the same team, your solution is the one who works for me.

@jennifer-shehane it definitely seems like service workers are of the main causes for Cypress not logging XHR requests. That explains why on related issues people tell things work on development and not on production, or not on CI, because normally SWs are disabled on localhost ;)

Hope to help and thank you again @cintrzyk

**Comment by jennifer-shehane** [comment] 2019-06-03 09:12
@cintrzyk Thanks for providing this workaround - it does seem to be the reason some people's XHRs are not logging. 

It's been tough narrowing down which cases are actual issues in Cypress because an XHR not being logged covers a very broad category. We'll look into the ServiceWorker cases.

**Comment by jennifer-shehane** [comment] 2019-06-04 04:50
We want to include this work as part of the Lifecycle Events feature documented here: https://github.com/cypress-io/cypress/issues/686

We don't want to add more magical things in the background without it being explicitly stated that we are handling ServiceWorkers (as defined in the LifeCycle Events issue), so please go thumbsup / show your support in that issue if you want this addressed.

## Workaround

For now, we suggest using the workaround given by @cintrzyk in this comment: https://github.com/cypress-io/cypress/issues/1716#issuecomment-454161526

**Closed** 2019-06-04 04:52 UTC
Labels: existing workaround, priority: high❗️, stage: needs investigating, type: unexpected behavior

**Comment by ddesna** [comment] 2019-10-23 09:47
Could someone explain me why this test does not log XHR POST requests to `https://www.academia.edu/v0/server_notifications?subdomain_param=api`?

```js
it(should log xhr', () => {
 cy.visit('https://www.academia.edu/12297791/Open_Access_Meets_Discoverability_Citations_to_Articles_Posted_to_Academia.edu')
})
```

I have tried some workarounds commented in this thread but had not luck.
