### ISSUE TITLE
[7.0.1] Component testing not working with Next.js and future.webpack5 configuration

### ISSUE THREAD

**Issue by edusig** [cypress-io/cypress#15864] opened 2021-04-07 21:21 UTC
### Current behavior

Cypress `open-ct` and `run-ct` both get stuck while using:
Nextjs: 10.1.3
React: 17.0.2
Cypress: 7.0.1
Webpack: 5.30.0

my next.config.js file:
```js
module.exports = {
  future: {
    webpack5: true,
  },
};
```

cypress/plugins/index.js file:
```js
module.exports = (on, config) => {
  require("@cypress/react/plugins/next")(on, config);
  return config;
};
```

![Screenshot_2021-04-07_16-36-33](https://user-images.githubusercontent.com/810728/113924446-37c36780-97c0-11eb-94b1-c63ee973a5d3.png)
![Screenshot_2021-04-07_16-37-59](https://user-images.githubusercontent.com/810728/113924454-38f49480-97c0-11eb-9496-58e2e012ac35.png)

### Desired behavior
It should run normally

### Test code to reproduce

I have forked [this repo](https://github.com/bahmutov/next-and-cypress-example) and updated the packages and configurations here -> https://github.com/edusig/next-and-cypress-example

### Versions

Cypress: 7.0.1
Last working Cypress version: 6.5.0
OS: Manjaro Linux

### More information

- The integration tests are working properly.
- I have read and followed [this cypress blog post](https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/) and the [documentation migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing)

**Comment by djsilcock** [comment] 2021-04-08 06:33
I had this same issue - initially fails as can't find webpack. If webpack is added as dependency then it fails as you describe but with debugging on shows a 'compilation must be an instance of Compilation' error.
Essentially the problem is that next bundles its own version of webpack so there are two versions in play at once. However it adds a require hook so it is possible to use the next censored webpack as long as the next config is run before the webpack devserver is set up.
Will put in a PR to fix later when I get to my PC.

**Comment by JessicaSachs** [comment] 2021-04-12 19:38
Updating this issue to reflect that it's specific to nextjs with the `future.webpack5` flag set.

**Comment by edusig** [comment] 2021-04-13 12:17
@JessicaSachs Even with the future.webpack5 set as false it still won't work. You can't try it in the repo I created to reproduce the problem.

@djsilcock Thanks for the quick reply.

**Comment by hwhitworth10** [comment] 2021-04-13 18:04
Working through this exact same issue. Thanks for the quick responses.

**Comment by djsilcock** [comment] 2021-04-14 06:54
It occurred to me earlier that a better approach might be instead of trying to extract the nextjs config and the monkeypatched webpack, that it might be easier to use the actual next devserver instead. Will share some code later

**Comment by lmiller1990** [comment] 2021-04-16 05:43
Anything merged into master inside of the `npm` directory (so `npm/react`) is released automatically via semantic release. So if you install the latest version of `@cypress/react`, you will have the latest code.

I just installed it and can confirm the code is there: `yarn add @cypress/react && cat node_modules/@cypress/react/plugins/next/index.js`

```js
const findNextWebpackConfig = require('./findNextWebpackConfig')

module.exports = (on, config) => {
  on('dev-server:start', async (options) => {
    const webpackConfig = await findNextWebpackConfig(config)

    // require('webpack') now points to nextjs bundled version
    const { startDevServer } = require('@cypress/webpack-dev-server')

    return startDevServer({ options, webpackConfig })
  })

  config.env.reactDevtools = true

  return config
}
```

Please install it and give it a try! Let us know if there is still any problems.

**Comment by edusig** [comment] 2021-04-16 13:11
@lmiller1990 I updated the packages on my example repo (https://github.com/edusig/next-and-cypress-example) to the latest and now I'm getting another error:
```
Error [TypeError]: Cannot read property 'version' of undefined
    at Object.<anonymous> (/home/edusig/workspace/edusig/next-and-cypress-example/node_modules/@cypress/webpack-dev-server/node_modules/html-webpack-plugin/lib/file-watcher-api.js:7:67)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/edusig/workspace/edusig/next-and-cypress-example/node_modules/@cypress/webpack-dev-server/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:41:24)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/edusig/workspace/edusig/next-and-cypress-example/node_modules/@cypress/webpack-dev-server/node_modules/html-webpack-plugin/index.js:19:36)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
TypeError: Cannot read property 'version' of undefined
    at Object.<anonymous> (/home/edusig/workspace/edusig/next-and-cypress-example/node_modules/@cypress/webpack-dev-server/node_modules/html-webpack-plugin/lib/file-watcher-api.js:7:67)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/edusig/workspace/edusig/next-and-cypress-example/node_modules/@cypress/webpack-dev-server/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:41:24)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/edusig/workspace/edusig/next-and-cypress-example/node_modules/@cypress/webpack-dev-server/node_modules/html-webpack-plugin/index.js:19:36)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
```

Packages versions:
cypress: 7.1.0
@cypress/react: 5.3.3
@cypress/webpack-dev-server: 1.1.3

I also tested downgrading the @cypress/webpack-dev-server to version 1.1.2 and re-installing html-webpack-plugin and it finally opened, but it stuck loading the first component test file.

**Comment by itstheandre** [comment] 2021-04-18 18:47
I tried cloning @edusig code and moving around dependencies, making webpack 4, removing flags and i still cant get it to work :(

**Comment by lmiller1990** [comment] 2021-04-20 02:40
I reproduced the problem: https://github.com/cypress-io/cypress/pull/16078

The stack trace comes from in `html-webpack-plugin`:

```
const webpackMajorVersion = Number(require('webpack/package.json').version.split('.')[0]);
```

I will dig deeper.

**Comment by lmiller1990** [comment] 2021-04-20 05:03
Ok, I think the problem is we have `html-webpack-plugin@4` as a [direct dependency](https://github.com/cypress-io/cypress/blob/738193f4505be801c35f4a5b4feb452f3f974a64/npm/webpack-dev-server/package.json#L14). It's look inside `node_modules/@cypress/webpack-dev-server/node_modules...` for `html-webpack-plugin` and the associated `webpack` version, which is not there. I think we need to remove this hard dependency and just have webpack and html-webpack-plugin as peer dependencies.

This is proving more complex than expected but I'm working through it and should have something soon.

**Comment by lmiller1990** [comment] 2021-04-20 05:28
Ok changing the `package.json` [like this](https://github.com/cypress-io/cypress/pull/16078/files#diff-e385749d8138fa9c2e7c04a2ad111a9ebb9e547525f6bb10f1e4fd5f1a8c8934) seems to work, at least locally. I will set up some CI tests.

The user will need run something like this:

```
yarn add cypress @cypress/webpack-dev-server html-webpack-plugin@5 webpack@5`
```

As well as specifying `webpack5: true` in their `next.config.js`. The reason we need to webpack and friends separately is nextjs does not seem to install them in `node_modules` like other templates do (such as Create React App, Vue CLI etc...)

I am still not entirely sure how the next.js toolchain works; I don't see `webpack` installed in `node_modules` when I create a new nextjs project - where is the toolchain installed? I'll do more research, but if someone who knows nextjs really well can point me in the right direction, that'd be nice. I guess it's buried somwhere deep inside `node_modules/next`?

**Comment by djsilcock** [comment] 2021-04-20 10:57
Happy to be corrected by an actual nextjs developer, but my understanding from peeking around in the source code is that both webpack4 and webpack5 are vendored into the next source and it selects the one required at runtime. It then hooks into the require mechanism so `requre('webpack')` points to the bundled nextjs version. If you add webpack as your own dependency, then you seem to end up with two instances of webpack in play at the same time which causes some unpredictable behaviour.
The special sauce is [here](https://github.com/vercel/next.js/tree/canary/packages/next/build/webpack)
As far as I can tell the two options are
1 - start with a base webpack config, modify it if necessary using the webpack() function from the users `next.config.js` file and start the webpack devserver from that:

    const baseConfig=require('./baseWebPackConfig')
    const webpack=require('webpack')
    const nextConfig=require(path.join(projectRoot,'next.config'))

    const nextWebPackConfig=nextConfig.webpack(baseConfig,{webpack})
    const webpackCompiler=webpack(nextWebPackConfig)
    if (nextConfig.future?.webpack5 && webpack.version().startsWith('4.')) throw 'you need to use the same version of webpack as specified in your next.config.js file'
    ...

2 - use the actual next devserver and run the cypress component testing framework as a next app. This requires a bit of hackery as you need to bypass any __app component that the next app might have but is doable. I see there is a PR which should fix this issue already but will submit my server-as-a-next-app version as a PR anyway (because I might as well)

**Comment by lmiller1990** [comment] 2021-04-20 12:27
Holy crap nice job figuring out how this all works! I'll definitely reference this as I work through the issue. I think I am pretty close to getting this to "just work". The only downside is we'll need to ask the user to install a specific webpack version based on their next version - so we are kind of "doubling up" on the webpack installation (one bundled, one not). 

I think if we can keep everything as non-framework-specific as possible it will pay itself off down the track, but good to know there is an alternative if things get too messy. Thanks

**Comment by djsilcock** [comment] 2021-04-20 12:59
How about a 'bring your own webpack' option to webpack-devserver (which would fall back to a `require("webpack")` ) to cover the situation where you have a configured webpack instance/module you have obtained in some kind of nonstandard way (such as extracting from next)

**Comment by lmiller1990** [comment] 2021-04-21 06:33
Bring your own webpack is exactly what I'm going for. Nextjs seems kind of unique in that they bundle and ship their own webpack implementation.

I made this PR: https://github.com/cypress-io/cypress/pull/16108

Basically users need to have either `webpack@4` or `webpack@5` installed (and the relevant `html-webpack-plugin`). Those are listed as [`peerDependencies`](https://github.com/cypress-io/cypress/pull/16108/files#diff-e385749d8138fa9c2e7c04a2ad111a9ebb9e547525f6bb10f1e4fd5f1a8c8934R30-R31), with a range of 4-5. The other main change is to remove [`html-webpack-plugin`](https://github.com/cypress-io/cypress/pull/16108/files#diff-e385749d8138fa9c2e7c04a2ad111a9ebb9e547525f6bb10f1e4fd5f1a8c8934L14) from `dependencies`, so `@cypress/webpack-dev-server` won't try to install and use it's own one.

The only real downside here is we require quite a lot of `peerDependencies`. This is not generally a problem, since most templates will specify their `webpack` and `html-webpack-plugin`, which are installed to `node_modules`. Nextjs is the exception, with its inline webpack.

I think this solution is a little better in terms of long term maintainability. We are also working on a `yarn create cypress-tests` scaffolder - this would be the place to check for the existence of `next.config.js` and install the relevant `webpack` and `html-webpack-plugin` versions.

**Comment by djsilcock** [comment] 2021-04-21 17:53
I actually meant that you could supply webpack to webpack-devserver rather than have it `require` webpack itself. The webpack module is exposed to the webpack method in next.config.js such that you can use something like:

    let webpackModule
    nextConfig={
        future:{webpack5:true},
        webpack (config,{webpack}) {
            webpackModule=webpack
            return config
            }
        }
    const nextWebpackConfig = await getNextJsBaseWebpackConfig(
    config.projectRoot,
    {
      buildId: `@cypress/react-${Math.random().toString()}`,
      config: nextConfig,
      dev: true,
      isServer: false,
      pagesDir: config.projectRoot,
      entrypoints: {},
      rewrites: { fallback: [], afterFiles: [], beforeFiles: [] },
    },
    )
    //now webpackModule == require('webpack')

**Comment by Norfeldt** [comment] 2021-04-22 11:57
Hope I'm not side-tracking this issue - but how do you get it to work with just the webpack version that NextJS is using in your application? 

I have tried the `cypress/plugins/index.js` file you wrote (but with .ts) and it's not really working out for me https://github.com/cypress-io/cypress/discussions/16136

**Comment by lmiller1990** [comment] 2021-04-23 03:50
I managed to remove the hard requirement of html-webpack-plugin v4 here. https://github.com/cypress-io/cypress/pull/16108

This should fix the problem - all you'll need to do now is install webpack 5 and html-webpack-plugin 5 and it should work. This should minimize the framework specific concerns from leaking too deeply into Cypress.

The above code will go out in the next release. Thanks everyone so far - it's entirely possible that some edge cases are not covered still (nextjs ecosystem is huge), but keep the bug reports coming 👍 

I started to use nextjs a little from this - it's really neat, and the DX experience is great!

**Comment by nottyo** [comment] 2021-05-02 03:28
Next.js just released the new version 10.2 https://nextjs.org/blog/next-10-2 which enables webpack5 by default. Has anyone tried this version with Cypress component testing ?

**Comment by edusig** [comment] 2021-05-03 15:42
@lmiller1990 and @nottyo I have just updated my example repo (https://github.com/edusig/next-and-cypress-example) and it is working perfectly. I also updated Next.js to v10.2.0 and there was no problem running the tests.

On other projects, which have a more complex Next.js/Babel/Cypress/Yarn workspaces configuration it seems to be working perfectly as well.

Thanks again for all the help and quick resolution :)

**Comment by nottyo** [comment] 2021-05-04 05:57
@edusig Thanks I also write a blog post for this https://nottyo.medium.com/component-testing-next-js-application-with-cypress-28fa311adda6

**Comment by lmiller1990** [comment] 2021-05-05 02:55
There is a PR for detailed docs with information on how to use Cypress with  both next.js + webpack 4 and 5 here: https://github.com/cypress-io/cypress-documentation/pull/3883

Incredibly good blog post @nottyo!

Seems this is working fine now - I'm sure we will find some edge cases for more complex configurations, if so, please open a discussion.

**Closed** 2021-05-05 02:59 UTC
Labels: component testing, npm: @cypress/react, stage: done
