### ISSUE TITLE
<Tests (View all tests) button doesn't work

### ISSUE THREAD

**Issue by emijmker** [cypress-io/cypress#7392] opened 2020-05-18 09:41 UTC
### Current behavior:
In the testrunner when I click <Tests (View all tests) it doesn't return to the overview of my spec files, the button doesn't do anything. Worked in 3.7.0 and older. doesn't work anymore since upgrading to 4.0x or even the current latest 4.5.0. I found this feature to be very useful, but now I have to go to the Dock and there click the Cypress app again in order to go back to the overview.

### Desired behavior:
When I'm in the testrunner and I click <Tests I expect to go back to (a.k.a. open) the overview page where it shows the integration tests.
![afbeelding](https://user-images.githubusercontent.com/35372494/82198267-57c61000-98fc-11ea-8e4c-8c3805c5df0c.png)

### Test code to reproduce
Not test related, it's the GUI.

### Versions
Cypress 4.5.0
MacOs 10.14.6
Chrome 81.0.4044.138

**Comment by jennifer-shehane** [comment] 2020-05-18 09:59
Duplicate of #5948

**Closed by jennifer-shehane** 2020-05-18 09:59 UTC
