### ISSUE TITLE
When I change the focus from cypress tests browser "chrome" to other window except the IDE than the browser stops executing the code commands and freezes.

### ISSUE THREAD

**Issue by manishclevero** [cypress-io/cypress#28542] opened 2023-12-18 06:03 UTC
### Current behavior

I have a login test. 
When I run the test and the cursor focus is in the test running browser than everything works and executes properly.
In case I navigate to other window or change the focus by moving the browser to something else or other window than the test freezes and I have to refresh or restart the test every time. 

### Desired behavior

Once I run the test and change the focus to other windows than also everything should work as expected. 

### Test code to reproduce

e2e.ts
```
// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')


Cypress.on('uncaught:exception', (err) => {
    // returning false here prevents Cypress from
    // failing the test
    console.log('Cypress detected uncaught exceptions: ', err);
    return false;
});

// for attachFile
import 'cypress-file-upload';
```

cypress.config.js
```const {defineConfig} = require("cypress");

module.exports = defineConfig({
    viewportWidth: 1280,
    viewportHeight: 1024,
    chromeWebSecurity: false,
    numTestsKeptInMemory: 0,
    experimentalMemoryManagement: true,

    //development mode
    // defaultCommandTimeout: 3200,
    // execTimeout: 3200,
    // pageLoadTimeout: 10000,
    // requestTimeout: 2200,
    // responseTimeout: 2200,

    // git mode

    defaultCommandTimeout: 90000,
    execTimeout: 500000,
    pageLoadTimeout: 250000,
    requestTimeout: 15000,
    responseTimeout: 15000,

    video: false,
    e2e: {
        setupNodeEvents(on, config) {
            return require("./cypress/plugins")(on, config);
        }, specPattern: "cypress/e2e/**/*.{ts,tsx}",
    },
});
```

package.json
`{
  "devDependencies": {
    "cypress": "^13.6.1",
    "cypress-file-upload": "^5.0.8"
  },
  "main": "index.js",
  "author": "Manish Shah",
  "license": "ISC",
  "description": "Test",
  "scripts": {
    "cypress": "cypress open",
    "start": "npx cypress run",
    "headless": "npx cypress run --browser chrome --headless --spec cypress/e2e/crudTests/create/1createTest.ts"
  },
  "dependencies": {
    "dotenv": "^16.0.1",
    "mocha": "^10.2.0",
    "node": "^19.2.0",
    "socket.io": "^4.5.4",
    "tsc": "^2.0.4",
    "typescript": "^4.9.3"
  }
}
`

tsconfig.json
`{
  "compilerOptions": {
    "types": ["cypress", "cypress-file-upload"],
    "target": "es2016",
    "lib": [
      "es2016",
      "es2019",
      "DOM",
      "es5"
    ],
    "module": "commonjs",
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "skipLibCheck": true
  }
}
`

### Cypress Version

13.6.1

### Node version

19.2.0

### Operating System

14.1.2 (23B92)

**Comment by ztarsoly** [comment] 2023-12-18 10:16
I am experiencing this issue too. Also, if I switch focus to another window at the beginning of the execution (or the test is re-executed due to I saved modifications), then I get 'no commands were issued in this test' message.

**Comment by jennifer-shehane** [comment] 2023-12-18 16:06
Duplicate of https://github.com/cypress-io/cypress/issues/28392 We're looking into it.

**Closed as not planned by jennifer-shehane** 2023-12-18 16:06 UTC
Labels: type: duplicate
