### ISSUE TITLE
Cypress 7.3.0 - RangeError: Maximum call stack size exceeded at isBinary

### ISSUE THREAD

**Issue by nikhkrish555** [cypress-io/cypress#16578] opened 2021-05-19 02:31 UTC
Observed the following error when running Cypress Tests on Azure Devops pipeline.

> RangeError: Maximum call stack size exceeded
>     at isBinary (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:23:18)
>     at hasBinary (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:46:9)
>   at hasBinary (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
>     at hasBinary (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
>     at hasBinary (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
>     at hasBinary (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)

   
Tests works fine when running on Windows locally.

I am assuming this is different to issue fixed as part https://github.com/cypress-io/cypress/issues/15101

**Comment by jennifer-shehane** [comment] 2021-05-19 19:55
Duplicate of https://github.com/cypress-io/cypress/issues/16476

**Closed by jennifer-shehane** 2021-05-19 19:55 UTC
