### ISSUE TITLE
Cypress 3.8 can't open Chrome 79 during test run

### ISSUE THREAD

**Issue by amir1011** [cypress-io/cypress#6026] opened 2019-12-22 13:10 UTC
### Current behavior:

After clicking run in Cypress window with Chrome 79, a chrome launches with blank\home window and nothing else happens (the same test works properly with Electron 78). After 20 seconds this error massage appears:
![cypress](https://user-images.githubusercontent.com/48730309/71322068-a7c6b500-24cb-11ea-88e7-720e80501583.png)

![cypress_policy](https://user-images.githubusercontent.com/48730309/71322152-2112d780-24cd-11ea-862a-1a716deb5ffe.png)

### Desired behavior:

Click on run button in the Cypress window (while Chrome 79 is selected)--> Chrome 79 launches and test run in it.
### Steps to reproduce: (app code and test code)

Open cypress by deskstop icon or using npx cypress open;
Chrome 79 selected as test browser;
Chose test to run and click run;
ISSUE: A blank chrome tab opens up outside of the test runner and nothing happens.

### Versions

Windows 10
Chrome Version 79 (64 bit)
Cypress 3.8.0

**Comment by jennifer-shehane** [comment] 2019-12-23 03:06
Closing as duplicate of https://github.com/cypress-io/cypress/issues/5912 which is pending release.

**Closed by jennifer-shehane** 2019-12-23 03:06 UTC

**Comment by amir1011** [comment] 2019-12-26 11:26
Hi, @jennifer-shehane 
I'm familiar with #5912 case and it isn't solves my problem...

**Comment by jennifer-shehane** [comment] 2019-12-30 09:58
@amir1011 The fix for that issue was released in 3.8.1, did you try on version 3.8.1 of Cypress?

If it is still happening in 3.8.1, we'll need more information to reproduce it.  you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by hieuTranEnouvo** [comment] 2020-02-18 03:04
The cypress is 4.0.2 version which still occurs chrome 80

**Comment by jennifer-shehane** [comment] 2020-02-18 07:12
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
