### ISSUE TITLE
Getting error after using this command on windows 7 32 bit : "npm run cypress:open"

### ISSUE THREAD

**Issue by PiyushTalwalkar** [cypress-io/cypress#3706] opened 2019-03-14 06:12 UTC

**Comment by PiyushTalwalkar** [comment] 2019-03-14 06:16
Cypress V: 3.1.5
If you navigate to to root folder, try to execute Cypress.exe it gives error as check the version may not be compatible with windows 7 32 bit

**Comment by jennifer-shehane** [comment] 2019-03-14 08:12
@PiyushTalwalkar Can you provide a screenshot of the error or the exact text of the error please? Thanks!

**Comment by PiyushTalwalkar** [comment] 2019-03-14 08:28
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\Cypress_Automation>.\node_modules\.bin\cypress open
It looks like this is your first time using Cypress: 3.1.5

 ×  Verifying Cypress can run C:\Users\PT\AppData\Local\Cypress\Cache\3.1.5\Cypress
   → Cypress Version: 3.1.5
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

spawn UNKNOWN
----------

Platform: win32 (6.1.7600)
Cypress Version: 3.1.5

**Comment by PiyushTalwalkar** [comment] 2019-03-14 08:30
also check this screenshot
![image](https://user-images.githubusercontent.com/48544309/54342041-7928cd80-4661-11e9-8416-17ba17a12375.png)

**Comment by jennifer-shehane** [comment] 2019-03-14 09:23
This issue is a duplicate of https://github.com/cypress-io/cypress/issues/787

**Closed by jennifer-shehane** 2019-03-14 09:23 UTC
Labels: stage: needs information

**Comment by flotwig** [comment] 2019-04-08 21:33
We have fixed this by also building for Windows 32-bit.

The code for this is done in [cypress-io/cypress#3877](https://github.com/cypress-io/cypress/pull/3877), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
