### ISSUE TITLE
Command line options, CYPRESS_CONFIG_FILE or CYPRESS_configFile are not creating/updating the environment variable

### ISSUE THREAD

**Issue by mdwaseem157** [cypress-io/cypress#6737] opened 2020-03-16 13:12 UTC
### Steps to reproduce:

1. Run the command:
`"cypress:run:nix": "CYPRESS_configFile=qa npx cypress open",`
		or
`"cypress:run:nix": "CYPRESS_CONFIG_FILE=dev npx cypress open"`,

2. Checked the cypress environment if the `configFile` variable has been set with the passed value

### Observed behavior:

New values of `configFile` is not available in the cypress environment.

### Desired behavior:

The use of `CYPRESS_CONFIG_FILE=qa` or `CYPRESS_configFile=qa` should set the `configFile` in cypress environment with the desired value passed(i.e qa or dev).

I could not find any documentation for setting `configFile` variable using `CYPRESS_<config file> `

### Versions
Cypress: 4.1.0
Ubuntu v18.04

**Comment by jennifer-shehane** [comment] 2020-03-17 05:29
Duplicate of #5706

**Closed by jennifer-shehane** 2020-03-17 05:29 UTC
