### ISSUE TITLE
Set the console color set

### ISSUE THREAD

**Issue by dramosv90** [cypress-io/cypress#3709] opened 2019-03-14 19:11 UTC
I would like to be able to configure the colors with which the data of the tests are shown in the console, to at least modify the ones that represent the duration of each spec. Since the color **red** gives the wrong idea and many times alarms jump unintentionally

### Versions
Cypress: 3.1.4
OS: WIndows 10 Home 64bits, Ubuntu 18.04.1 LTS
NodeJS: 10.15.1
npm: 6.4.1

**Comment by FredTreg** [comment] 2019-03-26 17:05
I have the same request. Seeing all this red is misleading.

Changing the default color used to display duration from red to a more neutral color would also do the trick for me (with much less development I presume).

**Comment by jennifer-shehane** [comment] 2019-03-27 07:13
Duplicate of https://github.com/cypress-io/cypress/issues/447

**Closed by jennifer-shehane** 2019-03-27 07:13 UTC

**Comment by valkedev** [comment] 2022-09-01 07:05
colors are pretty confusing for me too
![Снимок экрана от 2022-09-01 10-04-42](https://user-images.githubusercontent.com/1539181/187852791-133d72e3-5d30-47b8-b2f8-e270e95e5575.png)
