### ISSUE TITLE
Global before all hook disappears in OPEN mode when first test in spec is skipped

### ISSUE THREAD

**Issue by jprealini** [cypress-io/cypress#29383] opened 2024-04-23 02:28 UTC
### Current behavior

I have a global before hook (in my support file). I noticed that even though when I run Cypress in open mode I can see it being executed, if the first test in my spec is being skipped by using a tag or it.skip, then once the suite has finished running I can't see the "before all" hook anymore. 

I was supposing that this happens because the first test is being skipped, and then I found this issue which seems to be similar or related https://github.com/cypress-io/cypress/issues/1846. It was originally about the hook not being shown in the runner (exact same scenario I describe), and then morphed to "the hook not even being executed". That last behavior was supposedly fixed, but what I am seeing now is, as I mentioned, that the hook is executed, but then not displayed in the command log when the test run completes (making it difficult to debug anything that happened while it was executed)

### Desired behavior

The "before ALL" hook should be kept in command log once the execution has been finished, regardless if the first test in the spec has been skipped or not

### Test code to reproduce

https://github.com/jprealini/cypress-before-hook

### Cypress Version

13.8

### Node version

v18.17.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment] 2024-04-23 14:09
Duplicate of https://github.com/cypress-io/cypress/issues/1846

**Closed as not planned by jennifer-shehane** 2024-04-23 14:09 UTC
Labels: type: duplicate
