### ISSUE TITLE
"Cypress Quit Unexpectedly" when closing Cypress using X button in window corner

### ISSUE THREAD

**Issue by arnoldsmithson** [cypress-io/cypress#22257] opened 2022-06-10 22:02 UTC
### Current behavior

When quitting cypress via the X button in the corner of a window, instead of silently quitting, macOS reports that "Cypress Quit Unexpectedly."

### Desired behavior

Cypress should be able to close without triggering macOS's "Unexpected Quit" alert.

### Test code to reproduce

Simply run `npx cypress run` with the necessary stuff installed, then close the window.

### Cypress Version

10.0.3

### Other

It's more of a quality of life thing, so if it's not priority that's fine.

**Comment by lmiller1990** [comment] 2022-06-13 01:49
Nice catch... agreed, we should cleanly kill the process in this situation - there's nothing unexpected about an application closing when you click the X button.

**Comment by mjhenkes** [comment] 2022-06-13 20:54
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/22132

**Closed by mjhenkes** 2022-06-13 20:54 UTC
