### ISSUE TITLE
edit code with single element，but run test had 2 elements with cypress 3.8.0

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#5992] opened 2019-12-18 06:19 UTC
### Current behavior:

cy.get('div:nth-child(1) > div > div > span:nth-child(1)').click()

CypressError: cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.

**Comment by jennifer-shehane** [comment] 2019-12-18 06:41
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example - html + test code and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-12-18 06:41 UTC

**Comment by marystoikaaa** [comment] 2020-11-12 11:16
Hello , @jennifer-shehane There is one similar issue

**I have such html code. :** 
```
<div class="action-multicheck-wrap" data-bind="css: {_disabled: !totalRecords()}, collapsible">
        <input class="admin__control-checkbox" type="checkbox" data-bind="
                checked: allSelected(),
                attr: {id: ++ko.uid},
                event: { change: togglePage },
                css: { '_indeterminate': indetermine },
                enable: totalRecords" id="68">
        <label data-bind="attr: {for: ko.uid}" for="68"></label>
        <button class="action-multicheck-toggle" data-toggle="dropdown" data-bind="css: { '_active': $collapsible.opened },
                       enable: totalRecords,
                       toggleCollapsible">
            <span data-bind="i18n: 'Options'">Options</span>
        </button>
        <ul class="action-menu" data-bind="foreach: actions, closeCollapsible">
            <li data-bind="click: $parent[value].bind($parent),
                           visible: $parent.isActionRelevant(value)" style="">
                <span class="action-menu-item" data-bind="text: label">Select All</span>
            </li>
        
            <li data-bind="click: $parent[value].bind($parent),
                           visible: $parent.isActionRelevant(value)" style="display: none;">
                <span class="action-menu-item" data-bind="text: label">Deselect All</span>
            </li>
        
            <li data-bind="click: $parent[value].bind($parent),
                           visible: $parent.isActionRelevant(value)" style="display: none;">
                <span class="action-menu-item" data-bind="text: label">Select All on This Page</span>
            </li>
        
            <li data-bind="click: $parent[value].bind($parent),
                           visible: $parent.isActionRelevant(value)" style="display: none;">
                <span class="action-menu-item" data-bind="text: label">Deselect All on This Page</span>
            </li>
        </ul>
    </div>
```
**And my cypress code :** 
cy.get('.data-grid-multicheck-cell').find('button').click({**force:true**})

When I run my cypress code I get such error : cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.

I changed my code to cy.get('.data-grid-multicheck-cell').find('button').click({**multiple: true**})
When I run the modified code I get such error : 
_Timed out retrying: cy.click() failed because this element is not visible:

<button class="action-multicheck-toggle" data-toggle="dropdown" data-bind="css: { '_active': $collapsible.opened },                        enable: totalRecords,                        toggleCollapsible">...</button>

This element <button.action-multicheck-toggle> is not visible because its parent <div.sticky-header> has CSS property: display: none

Fix this problem, or use {force: true} to disable error checking._

Actually, I just don't understand why  it shows that a subject contained 2 elements in the first case with {force: true} .
You can see only one <button> tag in my html code .
Also, this test was passed with one of the old cypress versions . I currently have Version 5.1.0. Can you help me?

**Comment by panvalkar1994** [comment] 2021-04-18 07:48
cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.
<b>
In the selected list i have many element. So cy.click() cannot be used. Also i cannot allow {multiple:true} as i want to select only one item of all. 
</b>

<b>How to reproduce issue?</b>
call cy.get() with css class selector which is applied to multiple buttons . 
Now  apply cy.click().

Any suggestion will be helpful.

**Comment by jennifer-shehane** [comment] 2021-04-29 17:31
@panvalkar1994 You'll need to write a more specific selector. `cy.get('el').first().click()`
