### ISSUE TITLE
TypeScript 5 support for sourceMap option

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#26203] opened 2023-03-23 20:19 UTC
### Current behavior

If I want to use TypeScript 5 and use sourceMap in my tsconfig.json, cypress errors with the following error.

```log
Error: Webpack Compilation Error
/Users/bart/Dev/cypress-with-ts5/tsconfig.json
[tsl] ERROR
      TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
```

### Test code to reproduce

https://github.com/elevatebart/cypress-with-ts5/

### Cypress Version

12.8.1

### Node version

v18.7.0

### Operating System

macOS 13.2.1

**Comment by elevatebart** [comment] 2023-03-23 20:20
I found this old issue that throws the same error. Maybe that helps
https://github.com/cypress-io/cypress/issues/8477

**Comment by koooge** [comment] 2023-03-25 17:13
Hi, I encountered the same error with typescript@5, and `"sourceMap": false,`  worked. However, cypress now reports the wrong line when a test error occurs.

**Comment by lmiller1990** [comment] 2023-03-27 03:01
Related: https://github.com/cypress-io/cypress/issues/26148

Might be fixed in https://github.com/cypress-io/cypress/pull/26173

**Comment by peniqliotuv** [comment] 2023-04-03 15:11
Encountering the same issue with Typescript 5.0.3 - solution was just to pin our cypress tests to 4.9.5 while aforementioned GH issues get resolved.

**Comment by lmiller1990** [comment] 2023-04-03 23:58
Yep please give us a few, there are some TS 5 incompatibilities - some of them are upstream, in `ts-node`, eg #26148, leading to a PR in TS itself. We will get through these soon. Thanks!

**Comment by lmiller1990** [comment] 2023-04-20 21:03
The issue is we hard code inlineSourceMap: https://github.com/cypress-io/cypress/blob/4963893ac5738d8a0e447c0a624639a21ae7a072/npm/webpack-batteries-included-preprocessor/index.js#L41

One work around would be to provide your own preprocessor and webpack config that does not set this option, eg: https://github.com/elevatebart/cypress-with-ts5/compare/main...lmiller1990:cypress-with-ts5:example-fix?expand=1

Alternatively, you should be able to modify our defaults and remove the `inlineSourceMap` options, something like described here: https://github.com/cypress-io/cypress/tree/4963893ac5738d8a0e447c0a624639a21ae7a072/npm/webpack-preprocessor#modifying-default-options

I don’t know if we can just remove the `inlineSourceMap` option in our default preprocessor, that might be a breaking change. We could detect if they are using sourceMap and if they are, conditionally remove it. I'd say providing your own `webpack-preprocessor` with the defaults you'd like to use is probably a good work around for now - more control, and you can also use webpack 5 (default is 4).

**Comment by CheIIau** [comment] 2023-05-30 21:03
Facing the same error

**Comment by flavianh** [comment] 2023-05-31 15:27
> Alternatively, you should be able to modify our defaults and remove the `inlineSourceMap` options, something like described here: https://github.com/cypress-io/cypress/tree/4963893ac5738d8a0e447c0a624639a21ae7a072/npm/webpack-preprocessor#modifying-default-options
> 

@lmiller1990 in `cypress.config.ts`, I tried:

```typescript
export default defineConfig({
...
  e2e: {
    setupNodeEvents(on) {
      const options = { ...webpackPreprocessor.defaultOptions };
      console.log(JSON.stringify(options));
    },
  },
})
```

However, the rule you mention does not appear in the result. `options` gives out:

```json
{"webpackOptions":{"mode":"development","module":{"rules":[{"test":{},"exclude":[{}],"use":[{"loader":"babel-loader","options":{"presets":["@babel/preset-env"]}}]}]}},"watchOptions":{}}
```

Strangely, I can't find `cypress/npm/webpack-batteries-included-preprocessor/index.js` in my `node_modules`. Any idea why?

> One work around would be to provide your own preprocessor and webpack config that does not set this option, eg: https://github.com/elevatebart/cypress-with-ts5/compare/main...lmiller1990:cypress-with-ts5:example-fix?expand=1
> 

Sadly this fails for me too as I'm having trouble finding the right webpack.config to use and the cypress compilation returns an import error for my own module.

<img width="613" alt="image" src="https://github.com/cypress-io/cypress/assets/5397842/2c921aae-4ed2-487d-8f9b-40a90d452778">

I've tried `"sourceMap": false,` which fixes the compilation issue, but we'll misreport the lines as a previous user said.

**Comment by vlad-ivanov-d** [comment] 2023-06-01 11:18
My workaround for now is just to overwrite original `sourceMap` inside `tsconfig.json` in `cypress` folder:

<img width="935" alt="image" src="https://github.com/cypress-io/cypress/assets/21308971/41967f1c-0194-4d20-9f1f-8f55d648e4b8">

**Comment by lmiller1990** [comment] 2023-06-05 05:16
@flavianh does ^ work for you?

Re: 

> Strangely, I can't find cypress/npm/webpack-batteries-included-preprocessor/index.js in my node_modules. Any idea why?

Yeah - it's part of the actual Cypress app, which has it's own `node_modules` (that are not installed into your local project. The actual app and it's dependencies are located in different places depending on your OS, [something like these](https://docs.cypress.io/guides/references/advanced-installation#Binary-cache) directories.

When you tried making your own webpack config, you got an error - what is that? Maybe we can work through it.

**Comment by liuliu-dev** [comment] 2023-07-05 17:52
have the same issue with `typescript@5.1.6`, `cypress@11.2.0` and `"sourceMap": true,`, overwrite `sourceMap` in  `tsconfig.json` in `cypress` folder does not work for me.

**Comment by nitzcard** [comment] 2023-07-12 07:49
Are there update on this?

**Comment by nitzcard** [comment] 2023-07-12 07:50
I also have this problem

**Comment by lmiller1990** [comment] 2023-07-12 23:55
Did either of you try https://github.com/cypress-io/cypress/issues/26203#issuecomment-1571861397? It seems to be the best work around for now.

**Comment by guilhermesimoes** [comment] 2023-07-24 16:14
Do note that Cypress also appears to be loading the wrong `tsconfig.json` file. [Cypress's documentation](https://docs.cypress.io/guides/tooling/typescript-support) states:

> We recommend creating a [tsconfig.json](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) inside your [cypress folder](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-Structure)

But even though I have that file, Cypress still loads the `tsconfig.json` in the project root.

**Comment by scottohara** [comment] 2023-07-25 01:02
I have successfully used the [workaround above](https://github.com/cypress-io/cypress/issues/26203#issuecomment-1571861397) (for now - I remain hopeful that the workaround is only temporarily necessary).

I already had a `cypress/tsconfig.json` file in my project (in addition to my main `tsconfig.json` in the project root), so adding `"sourceMap": false` to the former (to override `"sourceMap": true` in the latter) was straightforward.

What I don't understand though is why this error only appears after upgrading to TypeScript 5.x?

I have always had `"sourceMap": true` in my main `tsconfig.json`; and as far as I can tell Cypress has always defaulted to `"inlineSourceMap": true` unless overridden by the `sourceMap` setting in a user-supplied `tsconfig.json` file.

So with TypeScript 4.x, this was fine:
```jsonc
/* tsconfig.json */
{
  "compilerOptions": {
    // ...
    "sourceMap": true,
    // ...
  }
}

/* cypress/tsconfig.json */
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    // Nothing here about source maps
  }
}
```

But with TypeScript 5.x we need this:
```jsonc
/* tsconfig.json */
{
  "compilerOptions": {
    // ...
    "sourceMap": true,   // same as always
    // ...
  }
}

/* cypress/tsconfig.json */
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    // ...
    "sourceMap": false   // <-- workaround
    // ...
  }
}
```

Not that it really matters, but I would be curious to know what actually changed with TypeScript 5.x that triggered the need for the workaround?

**Comment by guilhermesimoes** [comment] 2023-07-25 08:50
@scottohara TypeScript 5.x did make changes related to tsconfig.json: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends

**Comment by scottohara** [comment] 2023-07-25 09:12
Yeah, that was my first thought too, but that change seems to relate to extending from multiple configs.

I suppose it is _possible_ that in making those changes they have somehow altered how certain config values in a single base `tsconfig.json` file (e.g. `sourceMap`) are resolved into the final config; but on the surface it doesn't sound like this should behave any differently to earlier TS versions when just extending from a single `tsconfig.json` file.

**Comment by Mexx77** [comment] 2023-08-03 11:42
face the same issue and would like to remove the workaround again

**Comment by attila** [comment] 2023-09-05 21:21
I've tried the workaround at https://github.com/cypress-io/cypress/issues/26203#issuecomment-1571861397 but my problem is that `cypress/tsconfig.json` is ignored.

If I set sourceMap to false in the tsconfig.json of the workspace, it works fine.
The folder structure in this npm monorepo is as follows:

```
/packages/
   tsconfig/
      base.json        // <-- setting "sourceMap": false works in here
   project/
      cypress/
         tsconfig.json // <-- This file is never picked up as tsconfig for cypress
      tsconfig.json    // <-- extends from "/packages/tsconfig/base.json" – setting "sourceMap": false works here
```

**Comment by IlCallo** [comment] 2023-09-13 17:00
This feels painfully similar to https://github.com/cypress-io/cypress/issues/8477 🥲

**Comment by Sinled** [comment] 2023-10-06 14:45
Any updates on this?
for me `"sourceMap": false` works for some specs, but fails for others.

**Comment by pjanik** [comment] 2024-01-09 12:32
The provided workaround won't work if you attempt to import files from outside the Cypress directory. Whether this is a good or bad idea is a separate discussion, but it can pose real issues for many projects. In such cases, the main tsconfig.json will be picked up.

Are there any plans to address this issue on the Cypress side?

**Comment by fbandrei** [comment] 2024-01-18 11:51
Having the same issue, setting "sourceMap: false" does not work as a workaround.

**Comment by NealArw** [comment] 2024-03-13 07:31
Having the same issue, setting "sourceMap: false" does not work as a workaround.

**Comment by asalgado87** [comment] 2024-04-26 16:23
> Encountering the same issue with Typescript 5.0.3 - solution was just to pin our cypress tests to 4.9.5 while aforementioned GH issues get resolved.

@peniqliotuv can you point me to any resources on how to run cypress with an older version of typescript?

**Comment by peniqliotuv** [comment] 2024-04-26 16:42
> 
> 
> 
> 
> 
> 
> > Encountering the same issue with Typescript 5.0.3 - solution was just to pin our cypress tests to 4.9.5 while aforementioned GH issues get resolved.
> 
> 
> 
> @peniqliotuv can you point me to any resources on how to run cypress with an older version of typescript?

You can use the ' resolutions' field in the package file

**Comment by asalgado87** [comment] 2024-04-26 16:59
@peniqliotuv Can you be more specific? Sorry I'm relatively new to this kind of thing. Much appreciated

**Comment by scottohara** [comment] 2024-05-03 00:22
Permit me to ask a potentially silly question.

If I understand correctly, this issue arises when:
* `sourceMap: true` (as specified by the *user* in `cypress/tsconfig.json`)

... conflicts with
* `inlineSourceMap: true` (as specified by *Cypress* in the webpack preprocessor)

... as these two tsconfig options (`sourceMap` / `inlineSourceMap`) are [mutually exclusive](https://www.typescriptlang.org/tsconfig/#inlineSourceMap).

The workaround that many of us here have successfully used to avoid this error is to explicitly set `sourceMap: false` in the user-supplied `cypress/tsconfig.json` file (noting that there were some concerns mentioned above about whether it would be safe for Cypress to remove the `inlineSourceMap: true` setting).

Given the mutual exclusivity of these two config options and the fact that Cypress hardcodes the value of one of the options; shouldn't it also hardcode the value of the other?

That is, instead of asking every end-user that encounters this error to apply the same workaround, would it be possible for Cypress to force `sourceMap: false` at the same time as setting `inlineSourceMap: true`?

```diff
webpackOptions.module.rules.push({
    test: /\.tsx?$/,
    exclude: [/node_modules/],
    use: [
      {
        loader: require.resolve('ts-loader'),
        options: {
          compiler: options.typescript,
          compilerOptions: {
            inlineSourceMap: true,      // if this is true...
            inlineSources: true,
            downlevelIteration: true,
+           sourceMap: false,           // ...then this MUST be false
          },
          logLevel: 'error',
          silent: true,
          transpileOnly: true,
        },
      },
    ],
  })
```

Or would that not fix the issue because anything in the user-supplied `cypress/tsconfig.json` takes precedence over the defaults in the webpack processor?
(so a user-supplied `sourceMap: true` would overwrite the Cypress supplied `sourceMap: false`?)

**Comment by WellingtonBraga** [comment] 2024-05-06 13:35
Hi,

After upgrading Typescript to version `5.x` we started to have the same issue. We've set `sourceMap` to false in the `e2e/tsconfig.json` as a workaround, but I appreciate a final solution in this case.

As @scottohara said, that shouldn't (in theory) be that complicated as we can evaluate both `sourceMap` and `inlineSourceMap` values before building the final config to be used.

Anyways, the workaround is applied and hopefully we can move forward until we have nailed-down solution.

**Closed as completed** 2024-06-04 23:17 UTC
Labels: type: feature, topic: typescript, Triaged

**Comment by CedricHg** [comment] 2024-06-06 13:29
This is still broken for me with Cypress version 13.11.0. I have the sourceMap: false in cypress/tsconfig.json, but it looks like as others have said in this thread, this file is not being picked up. 

My folder structure that leads to the Cypress tsconfig.json file is as follows:
mygitrepo\src\front\cypress\tsconfig.json

My node_modules are located here:
mygitrepo\src\front\node_modules

So it looks like it should be the correct location to me..

**Comment by AtofStryker** [comment] 2024-06-06 13:43
> This is still broken for me with Cypress version 13.11.0. I have the sourceMap: false in cypress/tsconfig.json, but it looks like as others have said in this thread, this file is not being picked up.
> 
> My folder structure that leads to the Cypress tsconfig.json file is as follows: mygitrepo\src\front\cypress\tsconfig.json
> 
> My node_modules are located here: mygitrepo\src\front\node_modules
> 
> So it looks like it should be the correct location to me..

@CedricHg the fix for this should make its way into the next release of Cypress, which is targeted for around June 18th, 2024
