### ISSUE TITLE
setInterval not working in IE 11

### ISSUE THREAD

**Issue by shabreennishath** [cypress-io/cypress#6479] opened 2020-02-17 05:55 UTC
### Current behavior:
setInterval becoming undefined after 1st step of execution, not able to play the video

### Desired behavior:
When a video button which is a svg image is played should work as it is working in Chrome, FF, Edge

### Test code to reproduce
```js
this.timelineInterval = setInterval(() => {
      this.setStep(this.timelineStep + 1);

      if (this.timelineStep >= this.timeline.stepCount + 1) {
        this.stopTimeline();
      }
}, 200);
```

### Versions
IE 11

**Comment by jennifer-shehane** [comment] 2020-02-18 06:15
@shabreennishath Cypress does not fully support IE11, so does not guarantee anything within Cypress will work when run in IE11. 

Duplicate of #6423

**Closed by jennifer-shehane** 2020-02-18 06:15 UTC
