### ISSUE TITLE
Upgrade Electron to 3.x.x, including related dependencies to match those in 3.x.x

### ISSUE THREAD

**Issue by Jaemu** [cypress-io/cypress#2559] opened 2018-10-03 15:28 UTC
### Current behavior:

Latest Cypress is still on Electron 1.8.2, which is two major versions behind latest stable release of [3.0.2](https://electronjs.org/releases#3.0.2). 

### Desired behavior:

Upgrading to Electron 3.0.2 will also bring in:
- Node 10
- Chromium 67 
as related dependencies.

**Comment by Jaemu** [comment] 2018-10-03 15:35
This issue replaces https://github.com/cypress-io/cypress/issues/2253 as upgrading Node will be required as part of this work.

Not sure if https://github.com/cypress-io/cypress/pull/1659 would be entirely replaced by this change, might be worthwhile having a compatible version of Cypress for each of the electron major versions.

**Comment by Ricky-rick** [comment] 2018-11-08 07:08
This would posible solve the issues with alpine Linux
https://github.com/cypress-io/cypress/issues/419
https://github.com/electron/electron/issues/2727#issuecomment-409044881

**Comment by Gillespie59** [comment] 2018-12-09 21:30
On which version of cypress this change will be available ?

**Comment by jennifer-shehane** [comment] 2018-12-10 15:50
This is planned to be released in version 4.0

**Comment by jraoult** [comment] 2019-01-04 23:05
Might be worth considering Electron 4.0 now: https://electronjs.org/blog/electron-4-0

**Comment by kommen** [comment] 2019-01-24 16:08
This is a real blocker for us since we're using RegExp lookbehind assertions, which were implemented in Chrome 62: https://www.chromestatus.com/feature/5668726032564224

Via Electron 1.8.2 cypress uses Chromium 59, where those regexes are just resulting in a syntax error.

**Comment by jpike88** [comment] 2019-02-16 07:07
I have recently started running into this issue

https://github.com/cypress-io/cypress/issues/349

I found that cypress/browsers:chrome69 image instead of the cypress/base:10 made the issue go away. This means that there are latent issues with an aging version of electron that are probably the cause of other bugs with how the browser is firing up etc... but now I don't get any video recordings.

**Comment by chrisbreiding** [comment] 2019-02-22 19:34
Closing in favor of [upgrading to Electron 4.x](https://github.com/cypress-io/cypress/issues/3568).

**Closed by chrisbreiding** 2019-02-22 19:34 UTC
Labels: difficulty: 2️⃣, stage: work in progress, type: chore
