### ISSUE TITLE
The failure screenshot doesn't display failed assertion (it's still in progress)

### ISSUE THREAD

**Issue by ovenal** [cypress-io/cypress#5290] opened 2019-10-04 12:33 UTC
### Current behavior:
Cypress takes a screenshot in case of a failure and the Command Log on the screenshot isn't updated, there is still an assertion in blue with spinner icon in front. So currently the screenshot doesn't show what assertion has been failed.

![screenshot -- screenshot (failed)](https://user-images.githubusercontent.com/3194707/66207355-3db42600-e6bb-11e9-9874-f6c56ace94bd.png)

This problem was mentioned in https://github.com/cypress-io/cypress/issues/394#issuecomment-336047840, but it is still actual.

### Desired behavior:

The screenshot should display "synchronized" Command Log (with information about failed assertion).

### Steps to reproduce: (app code and test code)
```javascript
describe.only("screenshot", () => {
  it("screenshot", () => {
    cy.visit("https://docs.cypress.io/api/commands/screenshot.html#Arguments", {url: ""});
    cy.get("table").contains('tr', "never existed row").should('exist');
  });
});
```

### Versions

Cypress 3.4.1, Chrome 77

**Comment by danatemple** [comment] 2019-12-07 10:29
Also seeing this same issue. The text log shows the error ('...was never found').

**Comment by jennifer-shehane** [comment] 2019-12-17 07:31
I was able to recreate this in 3.4.1, but was not able to recreate in 3.8.0. This has likely been fixed since the Electron upgrade. Please rerun the code in the [most recent version of Cypress](https://docs.cypress.io/guides/references/changelog.html#3-8-0).

I will be closing this exact issue as resolved. If you can provide a reproducible example of this happening in another test case, [open a new issue](https://github.com/cypress-io/cypress/issues/new). 

## 3.4.1 

![screenshot -- screenshot (failed)](https://user-images.githubusercontent.com/1271364/70974180-8f265b80-20d5-11ea-9bc5-4cb52338a47b.png)


## 3.8.0

![screenshot -- screenshot (failed)](https://user-images.githubusercontent.com/1271364/70974097-60a88080-20d5-11ea-825c-9953226667ab.png)

**Closed by jennifer-shehane** 2019-12-17 07:31 UTC
