### ISSUE TITLE
Wrong last updated time Cypress runner UI

### ISSUE THREAD

**Issue by HafizGhulamAbbas** [cypress-io/cypress#28985] opened 2024-02-21 12:42 UTC
### Current behavior

I added a new file in my spec folder few minutes ago but **Last updated** time in the Cypress runner window is showing 40 years ago.

<img width="1512" alt="Screenshot 2024-02-21 at 5 29 38 PM" src="https://github.com/cypress-io/cypress/assets/13692762/6145be64-f832-4191-8cdb-bed7fb50bdf2">

### Desired behavior

When I add new file in my spec folder, correct time should show in **Last updated** column

### Test code to reproduce

1. Add a new file
2. Execute command: npx cypress open
3. Select the option: E2E tesing
4. Choose a browser: chrome in my case
5. Click "Start E2E Testing in Chrome"
6. Locate the latest added file

### Cypress Version

12.10.0

### Node version

v18.16.0

### Operating System

macOS 12.5.1

**Comment by jennifer-shehane** [comment] 2024-02-21 15:24
Duplicate of https://github.com/cypress-io/cypress/issues/22188 Thanks for reporting.

**Closed as not planned by jennifer-shehane** 2024-02-21 15:24 UTC
Labels: type: duplicate
