### ISSUE TITLE
`after` hook ignored if last test is skipped via `xit`

### ISSUE THREAD

**Issue by francoismassart** [cypress-io/cypress#6438] opened 2020-02-13 07:46 UTC
### Current behavior:

I'm using the `before`, `beforeEach`, `afterEach` & `after` hooks inside `describe` and `context` blocks of my spec file... 

BUT if the last `it` statement is disabled (replaced by a `xit`)

Then the `after` hook is never called...

![image](https://user-images.githubusercontent.com/704026/74411625-0a895c80-4e3c-11ea-80c6-0db805d19a3e.png)

### Desired behavior:

I expect the `after` hook to be executed even if the last `it` test is disabled via `xit`...

![image](https://user-images.githubusercontent.com/704026/74411748-4c1a0780-4e3c-11ea-82bf-fba392fcdd7c.png)

Notice the `⏹ after (context)` log...

### Test code to reproduce

https://github.com/francoismassart/cypress-test-tiny/tree/demo-after-hook-vs-xit

### Versions

Cypress 4.0.1
macOS Mojave 10.14.6
Chrome 79

**Comment by jennifer-shehane** [comment] 2020-02-13 08:10
I'm not seeing this behavior. You need to use `console.log()` instead of `cy.log()` because Cypress will not log any hooks or commands from a skipped test (even thought they may have ran).  Duplicate of #1846

If you console.log the messages, you'll see the `after` hook is indeed running. This is just visually not showing it in the Cypress Command Log. 

`spec.js`

```js
context('In a certain context', () => {
  before(() => {
    console.log('▶️ before (context)')
  })
  beforeEach(() => {
    console.log('beforeEach (context)')
  })

  describe('Some describe', () => {
    before(() => {
      console.log('before (describe)')
    })
    beforeEach(() => {
      console.log('beforeEach (describe)')
    })

    it('tests something', () => {
      console.log('test (it)')
    })

    after(() => {
      console.log('after (describe)')
    })
    afterEach(() => {
      console.log('afterEach (describe)')
    })
  })

  describe('Another describe', () => {
    before(() => {
      console.log('before (describe)')
    })
    beforeEach(() => {
      console.log('beforeEach (describe)')
    })

    xit('does last test', () => {
      console.log('test (it)')
    })

    after(() => {
      console.log('after (describe)')
    })
    afterEach(() => {
      console.log('afterEach (describe)')
    })
  })

  after(() => {
    console.log('⏹ after (context)')
  })
})
```

<img width="485" alt="Screen Shot 2020-02-13 at 2 36 12 PM" src="https://user-images.githubusercontent.com/1271364/74413730-5e149e00-4e6e-11ea-802f-7be8eed3082c.png">

**Closed by jennifer-shehane** 2020-02-13 08:10 UTC
