### ISSUE TITLE
Problem with cy.task()  Cypress version 13.3.0  

### ISSUE THREAD

**Issue by Troyc-boop** [cypress-io/cypress#28018] opened 2023-10-10 14:52 UTC
### Current behavior

Using cy.task() as in the [example](https://docs.cypress.io/api/commands/task), but am getting the error message:
"CypressError: `cy.task()` must only be invoked from the spec file or support file."
Am having the same issue as reported [here](https://github.com/cypress-io/cypress/issues/27099). 
![image](https://github.com/cypress-io/cypress/assets/58141884/d6dd06ba-bb61-4a05-97d0-1a20d605a40b)

### Desired behavior

It should work as it is described in the documentation

### Test code to reproduce

In cypress.config I have added:
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message);

          return null;
        },
      });
    }
}
![image](https://github.com/cypress-io/cypress/assets/58141884/080882a5-6f79-4c54-94a6-0d492bca26fc)
and in the test just call the cy.task()
![image](https://github.com/cypress-io/cypress/assets/58141884/811dbd8d-7a61-4ab8-a6d5-83e95f31c9c0)

### Cypress Version

13.3.0 

### Node version

18.13.0

### Operating System

Ubuntu 23.04

**Comment by jennifer-shehane** [comment] 2023-10-10 16:16
Duplicate of https://github.com/cypress-io/cypress/issues/27784 Thanks for reporting so much detail. We'll let you know if we need more info. We are prioritizing investigating this now.

**Closed as completed by jennifer-shehane** 2023-10-10 16:16 UTC

**Comment by meganaroserakuten** [comment] 2025-03-20 17:49
Facing this issue, any solutions please?

02:43:06    1) POST API Test - Data Discovery Aggregate
02:43:06         "before all" hook for "CS DD - Verify the Last 24 hours of Data":
02:43:06       CypressError: `cy.task('cypress-plugin-snapshot:getFile')` failed with the following error:
02:43:06  
02:43:06  The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()
02:43:06  
02:43:06  Fix this in your setupNodeEvents method here:
02:43:06  /home/jenkins/agent/workspace/Tenant/Continuous Integration/cypress-e2e/cypress.config.ts
02:43:06  
02:43:06  https://on.cypress.io/api/task
02:43:06  
02:43:06  Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
02:43:06        at <unknown>

**Comment by meganaroserakuten** [comment] 2025-03-20 17:49
Facing this problem, any solutions please?

02:43:06    1) POST API Test - Data Discovery Aggregate
02:43:06         "before all" hook for "CS DD - Verify the Last 24 hours of Data":
02:43:06       CypressError: `cy.task('cypress-plugin-snapshot:getFile')` failed with the following error:
02:43:06  
02:43:06  The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()
02:43:06  
02:43:06  Fix this in your setupNodeEvents method here:
02:43:06  /home/jenkins/agent/workspace/Tenant/Continuous Integration/cypress-e2e/cypress.config.ts
02:43:06  
02:43:06  https://on.cypress.io/api/task
02:43:06  
02:43:06  Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
02:43:06        at <unknown> 

cypress package version: 13.6.6
