### ISSUE TITLE
Change event is not fired on number input

### ISSUE THREAD

**Issue by szerintedmi** [cypress-io/cypress#1171] opened 2018-01-09 12:03 UTC
- Operating System: MacOs
- Cypress Version: 1.4.1
- Browser Version: Chrome 63 & Electron 53
- React: 16.2.0

### Is this a Feature or Bug?
Bug

### Current behavior:
Change event is not fired on "number" type inputs after .type() nor .click() or .focus() to other element.
It works fine with "text" input types

### Desired behavior:
Change event should fire with number input just like with text input type

### How to reproduce:
https://stackblitz.com/edit/react-byhe3e?file=index.js

#### App code:

```js
import React, { Component } from 'react';
import { render } from 'react-dom';

class App extends Component {
  state = {
    inputTextValue: '',
    inputNumberValue: ''
  };

  handleTextChange = (event) => {
    this.setState({ 
      inputTextValue: event.currentTarget.value,
    });
  }

 handleNumberChange = (event) => {
    this.setState({ 
      inputNumberValue: event.currentTarget.value,
    });
  }

  render() {
    return (
      <div>
        <div>
          Input text: {this.state.inputTextValue} <br/>
          <input id="textInput" onChange={this.handleTextChange } value={this.state.inputTextValue} type="text" /> <br/><br/>
        </div>
        <div>
          Input number: {this.state.inputNumberValue} <br/>
          <input id="numberInput" onChange={this.handleNumberChange } value={this.state.inputNumberValue} type="number" />
        </div>
      </div>
    );
  }
}

render(<App />, document.getElementById('root'));
```
**Test code:**
```js
describe("Change event bug repro", function() {
    it("Should fire change on textInput", function() {
        cy.visit("https://react-byhe3e.stackblitz.io");

        cy
            .get("#textInput")
            .type("hello")
            .should("have.value", "hello");
        cy.get("#inputTextValue").contains("hello");
    });

    it("Should fire change on numberInput entering integers", function() {
        cy
            .get("#numberInput")
            .type("1234.56")
            .should("have.value", "1234");
        cy.get("#inputNumberValue").contains("1234.56");
    });

    it("Should fire change on numberInput entering decimals", function() {
        cy
            .get("#numberInput")
            .type("1234.56")
            .should("have.value", "1234.56");
        cy.get("#inputNumberValue").contains("1234.56");
    });
});
```
### Additional Info (images, stack traces, etc):
related issue: https://github.com/cypress-io/cypress/issues/816
test results:
![image](https://user-images.githubusercontent.com/7456451/34719865-59e1f28c-f534-11e7-9b81-f7ab31fae790.png)

**Comment by brian-mann** [comment] 2018-01-09 14:49
Appreciate you putting together a detailed bug report. We'll look at this.

**Comment by szerintedmi** [comment] 2018-01-12 17:08
I accidentally found what's going on. 
The event isn't triggered when  I pass string to type(), if I pass number then events are firing.
Although the behaviour is weird and works different than browser when passing string even if it contains only numbers

**Comment by GavinThompson** [comment] 2018-01-12 23:05
Just to piggyback on this really detailed bug, I'm actually encountering the same bug with number fields and change events not firing. Specifically however I believe it's only happening when the input contains a decimal (at least in our case).

If I use the following command cy.get('#price').type('9122') and log the changes I can watch the following logs scroll by in Cypress:

Price change output on number field: 9
Price change output on number field: 91
Price change output on number field: 912
Price change output on number field: 9122

When I change the command to include a decimal -- cy.get('#price').type('9122.99') I get the following:

Price change output on number field: undefined
Price change output on number field: undefined
Price change output on number field: ....etc

this works with or without single quotes around the number in question.

**Comment by mjfaga** [comment] 2018-01-26 16:02
I'd like to add that we are having this same issue, but for `<input type="date" />` fields, even when typing the date with the [Date Input format](https://docs.cypress.io/api/commands/type.html#Date-Inputs) noted in the cypress docs: "YYYY-MM-DD".

**Comment by jbmusso** [comment] 2018-02-07 18:40
@mjfaga I think I'm experimenting the same issue with `<input type="date" />`. Have you been able to find a workaround by chance?
Date input value is being cleared in the DOM despite a `should('have.value')` assertion is successful. I can only reproduce this issue when filling form in cypress - I'm still trying to figure out if this is a cypress bug, or somewhere down in my app. Will reply if I find a workaround/fix.

**Comment by mjfaga** [comment] 2018-02-07 20:50
@jbmusso I can reproduce this by running the following in my console...
```
const datePicker = document.querySelector('input[type="date"]');
datePicker.value = "2015-01-01";
```
...and then clicking the submit button on my form manually.

From the research I've done, it comes down to that fact that doing what I note above doesn't trigger the react life cycle events, so the react change event is never fired, and therefore, the field doesn't technically have a value as a result.

I can get things working when using `ReactTestUtils.Simulate.change(datePicker);` in a debug session, but I haven't found a way to hook that up properly in cypress to get things to execute properly. 

That is as far as I've gotten thus far. No work around yet.

**Comment by jbmusso** [comment] 2018-02-08 09:53
Thanks for sharing. Our app is a single page app (React).
As a quick-n-dirty workaround, I fixed my Cypress test suite by casting the input to a `type="text"`:

```javascript
cy
    .get('input[name="birthDate"]')
    .type('1970-06-15')
    .should('have.value', '1970-06-15') // Successful assertion

// Workaround, cast to "type"
cy
    .get('input[name="birthDate"]')
    .invoke('attr', 'type', 'text')
    .should('have.value', '1970-06-15') // Successful assertion
```
It looks like that the change event now fires, which triggers form validation (use case: form validation using `mobx-react-form`).

**Comment by vagusX** [comment] 2018-06-23 11:19
In my situaion, 
```js
cy.get('input').type('10.0001').trigger('blur');
```
I set something for input#onBlur, but seems input#onChange didn't work when with decimals

**Comment by Bkucera** [comment] 2018-07-16 21:07
This issue will be fixed in PR #2016!

**Closed** 2018-07-23 08:43 UTC
Labels: pkg/driver, type: bug

**Comment by ervicsangel** [comment] 2019-01-07 11:33
It seems that the issue still occurs on the current version

type: "number"
pattern: "^([0-9]{6})$"

Removing both accepts the values.

**Comment by Bkucera** [comment] 2019-01-07 15:23
@ervicsangel are you saying using the `pattern` attribute will not lead to desired behavior? or any `number` input?

**Comment by Bkucera** [comment] 2019-01-08 15:38
@ervicsangel can you provide a reproducible example using the `mat-form-field` element? What library is that component from? Possible just link us to the demo of the component if it's in documentation somewhere

**Comment by ervicsangel** [comment] 2019-01-09 05:14
I think it was because the maxLength was not explicitly set. As I did so, it worked not just using Cypress but also in IE. I think that's enough for now, thanks.

Cheers

**Comment by maccurt** [comment] 2019-01-21 19:18
Thank you. I was getting frustrated with my decimals not typing in and just by upgrading I got past it..

**Comment by SergeiTsarikTR** [comment] 2019-09-13 13:16
> I'd like to add that we are having this same issue, but for `<input type="date" />` fields, even when typing the date with the [Date Input format](https://docs.cypress.io/api/commands/type.html#Date-Inputs) noted in the cypress docs: "YYYY-MM-DD".

I have the issue that in browser the input field is 
<input type="date">
but when Cypress is running browser the input field is
<input type="text">
Why is it?

**Comment by sgronblo** [comment] 2019-11-01 08:16
I'm using Cypress with the following versions (installed yesterday):

Cypress package version: 3.5.0
Cypress binary version: 3.5.0

Using `.type('yyyy-mm-dd')` on an input type=date does not fire React's onChange event.

**Comment by sgronblo** [comment] 2019-11-01 09:02
Worked around by manually triggering by calling `.trigger('change')`

**Comment by jennifer-shehane** [comment] 2019-12-24 09:00
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
