### ISSUE TITLE
Browser not launched through Cypress

### ISSUE THREAD

**Issue by Spookyguy** [cypress-io/cypress#7947] opened 2020-07-10 11:03 UTC
### Current behavior:

When I try to run tests under Chrome, Chrome opens with the message 'Whoops, we can't run your tests. This browser was not launched through Cypress. Tests cannot run.'. The icon of the cypress add-on is shown. The browser also says, that it's controlled by automated test software, but the test is not running.
![chrome](https://user-images.githubusercontent.com/17175729/87147304-b11f3f80-c2ac-11ea-8242-edbd9cfd00a8.JPG)

With Electron 80 the tests run as expected.

### Desired behavior:

Tests should run in Chrome.

### Test code to reproduce

1. Open cypress: `cypress open`
2. Select Chrome as browser
3. Run test

Testcode is not relevant, because it doesn't work with any test.

### Versions
OS: Windows 10 Enterprise, Version 1903, Build 18362.904
Cypress: 4.10.0
Browser: Chrome Version 83.0.4103.106 (Official Build) (64-Bit)

I already uninstalled Cypress and reinstalled it with no effect.

**Comment by jennifer-shehane** [comment] 2020-07-13 05:47
Could you try following [these instructions](https://on.cypress.io/debugging#Clear-App-Data) to Clear App Data?

**Comment by Spookyguy** [comment] 2020-07-13 17:17
Hello Jennifer, I couldn't find any instructions for clearing app data at the link you provided, but if you are referring to clicking File/View App Data in the menu of the ui and deleting all files in the shown folder, yes I did that several times.

**Comment by jennifer-shehane** [comment] 2020-07-14 06:43
Sorry about that, I linked the wrong doc: https://on.cypress.io/troubleshooting#Clear-App-Data

**Comment by Spookyguy** [comment] 2020-07-14 06:45
Did that several times, but Chrome still shows the mentioned behaviour :(

**Comment by jennifer-shehane** [comment] 2020-07-14 06:45
Are you able to reproduce this when running the standard kitchensink tests? Narrowing down if this is something specific to your project would be helpful. https://github.com/cypress-io/cypress-example-kitchensink

**Comment by Spookyguy** [comment] 2020-07-14 08:10
Cloned the kitchensink repo and installed tried to run the example tests, but the result is the same as above.

**Comment by jennifer-shehane** [comment] 2020-07-14 08:30
@Spookyguy Can you run `cypress info` and print the information here? 

You're sure that your company is not blocking specific Chrome extensions? https://on.cypress.io/troubleshooting#Allow-the-Cypress-Chrome-extension

**Comment by Spookyguy** [comment] 2020-07-14 08:38
Might be the solution. Is there a way to test it?

**Comment by Spookyguy** [comment] 2020-07-14 12:57
@jennifer-shehane Would Chrome install the extension in the first place, if the company policies blocked it? As you can see in  the screenshot I posted, the extension is installed (icon is visible in the upper right corner).

**Comment by jennifer-shehane** [comment] 2020-07-22 07:06
Duplicate of #6889

**Closed by jennifer-shehane** 2020-07-22 07:06 UTC
Labels: stage: needs information, topic: 😳 whoops we can't run your tests
