### ISSUE TITLE
performance issues running on azure build servers from v4.4.1 to v5

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#8311] opened 2020-08-18 19:02 UTC
### Current behavior:

We've had huge performance problems with cypress since 3.4.1. After 3.4.1 cypress went unusably slow. Then in 4.2.0 suddenly it was fast again.. but after 4.4.1 it went a little slower, on the latest release its double the time and on v5 it just times out. In all cases the performance problems could not be reproduced locally, only on our azure windows builds.

I've been trying to identify the problem and trying different solutions ;- it seems that windows, low hardware build servers aggrevate the performance. e.g.

v4.4.1 - 2 v cpu's, 8gb ram - 24min
v4.4.1 - 4 v cpu's, 8gb ram - 19min
v5 - 2 v cpu's 8gb ram - times out after 50mins
v5 - 4 v cpu's, 8gb ram - 23min

Note that 2 virtual cpu's, 8gb ram is the normal build machine for public azure devops.

So on a faster machine its only 20% slower. On a slow machine we just get lots of problems.

The cpu logs indicate that the "cypress" process is using by far the most amount of cpu and it seems from the logs like network requests are the main cause of slowness.

I tried a few hacks:
* I tried disabling the cache clear - but I couldn't get it to work, even commenting out the cache clear in the electron file and disabling the profile cleaner util
* I had an idea to disable the proxy only for certain requests by specifying a pac script instead of a proxy in electron.js - then sending the main page and __ cypress request to the proxy and everything else direct - If something like this could be made to work I think it would offer a significant performance boost. However I couldn't get electron to use the pac script correctly, either encoded as a data uri or a web request.

My theory is that the proxy uses request and pipe and that something about it isn;t optimal on slower machines. I read a bit about setting highWatermark settings etc. to optimize piping a request to a response - but I'm a bit out of my debt. I see a number of other issues about network performance and there might be improvements here.

btw modifyObstructiveCode is false.

I'll upload two debug logs of the same spec and the same version of cypress on 2cpu's and 4 cpu's showing it being very slow.

### Desired behavior:

No performance degradation.

### Test code to reproduce

I think I should be able to put together a repo of our project - will this be valuable? I guess I can see if I can reproduce problems on app vejor? If all I can reproduce on public servers is a 20% degradation is that expected? Its going to be alot of effort to put it together so I'd like to hear if its helpful first.

**Comment by lukeapage** [comment] 2020-08-18 19:11
[v5-slow.txt](https://github.com/cypress-io/cypress/files/5092346/v5-slow.txt)
[v5-fast.txt](https://github.com/cypress-io/cypress/files/5092347/v5-fast.txt)

**Comment by lukeapage** [comment] 2020-08-18 19:23
An example from the logs - the first javascript file entry.js is 2mb big. First the proxy gets the request:

```
2020-08-16T18:30:49.7071459Z 2020-08-16T18:30:49.618Z cypress:proxy:http:request-middleware proxying request { req: { method: 'GET', proxiedUrl: 'http://localhost:3001/static/integrationTests-pro/entry.js', headers: { host: 'localhost:3001', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/5.0.0 Chrome/83.0.4103.122 Electron/9.2.0 Safari/537.36', accept: '*/*', 'sec-fetch-site': 'same-origin', 'sec-fetch-mode': 'no-cors', 'sec-fetch-dest': 'script', referer: 'http://localhost:3001/integrationTests/pro?theme=black&lang=en', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-US' } } }
```
The request gets a response (its being served also from localhost so its fast):
```
2020-08-16T18:30:50.2357751Z 2020-08-16T18:30:49.988Z cypress:proxy:http:response-middleware received response { req: { method: 'GET', proxiedUrl: 'http://localhost:3001/static/integrationTests-pro/entry.js', headers: { host: 'localhost:3001', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/5.0.0 Chrome/83.0.4103.122 Electron/9.2.0 Safari/537.36', accept: '*/*', 'sec-fetch-site': 'same-origin', 'sec-fetch-mode': 'no-cors', 'sec-fetch-dest': 'script', referer: 'http://localhost:3001/integrationTests/pro?theme=black&lang=en', 'accept-encoding': 'gzip', 'accept-language': 'en-US' } }, incomingRes: { headers: { 'content-encoding': 'gzip', 'content-length': '2040213', 'last-modified': 'Sun, 16 Aug 2020 18:29:17 GMT', 'cache-control': 'max-age=0', 'content-type': 'application/javascript; charset=utf-8', date: 'Sun, 16 Aug 2020 18:30:49 GMT', connection: 'keep-alive' }, statusCode: 200 } }
```
Then the proxy pipes the response back:
```
2020-08-16T18:30:50.2381893Z 2020-08-16T18:30:49.993Z cypress:proxy:http Running middleware { stage: 'IncomingResponse', middlewareName: 'SendResponseBodyToClient' }
2020-08-16T18:30:53.9146900Z 2020-08-16T18:30:53.836Z cypress:proxy:http Entering stage { stage: 'IncomingRequest' }
```

The log after sending the response is the next request coming in - its done on the first line of the entry.js. So it takes 4seconds. On the faster machine it takes 400ms.

**Comment by jennifer-shehane** [comment] 2020-08-19 06:02
Could you possibly narrow down the scope of the versions? A fairer comparison would be the timings between 4.12.1 and 5.0.0, that would help us completely verify if this was solely introduced in 5.0.

**Comment by lukeapage** [comment] 2020-08-19 06:46
@jennifer-shehane I will do. In fact I can try and run a bisect to find the commit where it gets slow, because my current investigation isn't getting me anyway.

**Comment by lukeapage** [comment] 2020-08-19 06:47
[v5-slow-no-retry-passing.txt](https://github.com/cypress-io/cypress/files/5094485/v5-slow-no-retry-passing.txt)

better log - this is with retries off - it passes, but takes 1m16s, where as it should take about 9s.

**Comment by lukeapage** [comment] 2020-08-19 08:34
It seems this is only a 4.5.0 regression. I've comma seperated the values because I get different results. Maybe what I said earlier isn't true its just that the time taken varies.

4.4.1         always ~9 seconds
4.5.0         4m51s, 54s
4.8.0         hangs, 4m40s
4.12.1       1m13s
5.0.0         1m16s, hangs

I tried removing the compression module: e.g. this line https://github.com/cypress-io/cypress/blob/aa6470d349237234e551f83cb3abbac5bb0eda98/packages/server/lib/server.js#L159 
and I do get better performance (50s on 5.0.0)

**Comment by lukeapage** [comment] 2020-08-19 08:39
It seems like this might be the same issue as #7930

**Comment by jennifer-shehane** [comment] 2020-08-19 08:53
Yah, I think this is the 4.5.0 performance regression. Providing a use case there to reproduce would be helpful.

Duplicate of #8311

**Closed by jennifer-shehane** 2020-08-19 08:53 UTC
Labels: OS: windows, stage: needs investigating, type: performance 🏃‍♀️

**Comment by lukeapage** [comment] 2020-08-19 08:57
@jennifer-shehane I would like to bisect this to a commit, but the artifacts are no longer available: https://github.com/cypress-io/cypress/commit/9d8992a4459eb77ef41ec1f32a15b3e9cbb996f2#commitcomment-38623419

Do you know of a way I can run a build against a particular commit of cypress?

If you saved artifacts on PR's I was thinking to make a draft PR and use that, but it doesn't look like you do.

**Comment by jennifer-shehane** [comment] 2020-08-19 09:03
@lukeapage You'd have to pull down the repo itself and run your project in there, doing `git bisect` or however other way you want to run at the specific commit where you want to run from. 

In general, it's: 

- pull down repo
- run `yarn`
- run `yarn start` for `cypress open`
- run `yarn cypress:run --project 'path/to/project'` for `cypress run`

There's more specific instructions here though: https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements
