### ISSUE TITLE
Missing webresource files while running Cypress which then throws an error (uncaught exception)ReferenceError: Page_ClientValidate is not defined after a click action

### ISSUE THREAD

**Issue by Walczynska** [cypress-io/cypress#26878] opened 2023-05-30 09:19 UTC
### Current behavior

Many Webresource files are missing when I try to run my Cypress test. The error (uncaught exception)ReferenceError: Page_ClientValidate is not defined appears when my test tries to click a button. I have tried the following solution
Cypress.on('uncaught:exception', (err, runnable) => {
return false});
but the button still doesn't click. After a review I noticed that the Websource files where the Page_ClientValidate is defined are missing when I run the test in Cypress comparing to when I perform the action manually on the page. (See attached screenshots)
Files on the page when manually clicking on the Save Address button

The files in Cypress:
![image](https://github.com/cypress-io/cypress/assets/56719178/dcb6d6fa-0dde-4788-990f-40a341acc816)

![image](https://github.com/cypress-io/cypress/assets/56719178/52a62854-a41c-413d-a094-41ca74db9aa8)

![image](https://github.com/cypress-io/cypress/assets/56719178/c98115d3-e11e-448c-aa15-41c6934bb1d3)

Even if I pause the test and manually click the button the same error appears.

### Desired behavior

![image](https://github.com/cypress-io/cypress/assets/56719178/e9cd92b6-bd3e-46b7-9fe7-4325ed9f6658)

The button is clicked and the error does not appear and the test continues to run.

### Test code to reproduce

   cy.get('#ctl00_cphPage_CreateCitationCon1_AddressDialog_txtSearchPostCode').type(PostCode)
   Cypress.on('uncaught:exception', (err, runnable) => {
    return false});
    cy.wait(200)      
    
  cy.get('[class="button TypeAddressField ui-button ui-corner-all ui-widget"]').should('have.value', 'Save Address').click(),

### Cypress Version

12.11.0

### Node version

v16.17.0

### Operating System

Edition	Windows 10 Enterprise Version	22H2 Installed on	‎31/‎08/‎2022 OS build	19045.2846 Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by nagash77** [comment] 2023-05-30 13:20
@Walczynska Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by Walczynska** [comment] 2023-06-01 11:51
Apologies I wasn't sure if I should raise it as a disccusion or an issue. – I have poseted in the discussion

I work in law enforcement and the application under test is restricted so I would never be able to give you a reproducible example.

We are Tester’s moving into automation and don’t have access to the source code. What we have been told by the developer is that “I can debug and step into the Page_ClientValidate function successfully, with no errors in the console on the button click events. Page_ClientValidate is an asp.net supplied function, and not a function we have control over, so it’s strange it’s complaining about that.” Its only when we launch via Cypress that the WebResource.axd containing the Page_ClientValidate function is not loaded.

The application is protected by Kerberos authentication, we therefore have to use ‘Fiddler’ to allow us access to the application when using Cypress – please see last post in here which is our set-up. https://github.com/cypress-io/cypress/issues/1255

Can anyone offer any solution or work around to this issue?

**Comment by nagash77** [comment] 2023-06-01 12:58
Hi @Walczynska , I have assigned this ticket out to one of our engineers to investigate but I do not have high hopes of being able to properly debug with such limited access to the exact scenario you are encountering.  They may be able to offer some insights and pose some questions you might be able to forward onto your developer contact to get closer to the cause.

**Comment by AtofStryker** [comment] 2023-06-01 21:51
Hi @Walczynska. Out of curiosity, have you tried setting any of the following in your config, in particular [experimentalModifyObstructiveThirdPartyCode]() or [experimentalSkipDomainInjection](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection)?
```js
{
experimentalModifyObstructiveThirdPartyCode: true,
experimentalSkipDomainInjection: true
}
```

**Comment by Walczynska** [comment] 2023-06-06 12:24
Hi @AtofStryker, Thanks for your response. We have managed to solve the issue by starting a new project from scratch. Our developers also added
{ experimentalStudio: true,}
but I am not sureif that was what fixed it. 
Thanks for your help. We can move this issue to closed or resolved

**Closed as completed** 2023-06-06 12:24 UTC

**Comment by gabrielsams-pnnl** [comment] 2025-02-19 18:49
My personal issue was using ntlm-cypress-auth, when  running my Cypress tests no webresource.axd files would load. I was using SSO auth to access the site, but I was not including the host that was being called to access those files. When I switched to using a wildcard i.e. cy.ntlmSso(["*"]); for my authentication it started properly loading my webresource.axd files.
