### ISSUE TITLE
Can't switch to the new Window 

### ISSUE THREAD

**Issue by Muhammadehsan2019** [cypress-io/cypress#14231] opened 2020-12-18 14:31 UTC
I am currently working on the page at my company, lets say I am working on "https://mycompany.com" when adding a contact it opens a new window after clicking on submit button.  Each time I create a new contact the new window opens with a URL from same domain but dynamic extension such as

 "https://mycompany.com/ contacID=098fda7876378"
"https://mycompany.com/ contacID=dkg786543322"
"https://mycompany.com/ contacID=xuy675432jhj7"

when clicking the button no "target attr" or "href" is available that I can remove the attribute or  capture "href" to navigate to the new window.
is there any way that I can navigate to the contactID page using some regular expressions? or capture the URLS for all open windows?
I can automate is in selenium through window handles  but not through cypress.

**Comment by bahmutov** [comment] 2020-12-18 15:18
How is the new window created or opened?

**Comment by Muhammadehsan2019** [comment] 2020-12-18 16:35
on the homepage when I fill out the form for add contact and then click on submit contact button, a new contact details window  opens after clicking a submit contact button which has a dynamic contact ID in the URL such as:
"https://mycompany.com/ DetailsContact?=098fda7876378"
This contact ID generates after clicking the submit contact button, and can't be captured on the homepage. So in order to continue with the test I have to navigate or switch to the new window, so how do we switch or navigate to the new window without manually adding the unique contact ID to the URL.

**Comment by bahmutov** [comment] 2020-12-18 20:08
Can you provide an example HTML with the form? Does it submit and the endpoint return 302 redirect with new location? In that case you can use `cy.intercept` to listen to the POST request, grab the target page URL, extract and verify the ID, but then change the redirect to point back at the original page. See example recipe here https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept

But I am not sure why it opens the new window, we would need to know how you open the new window.

**Comment by Muhammadehsan2019** [comment] 2020-12-21 18:46
I was able to use the below method and extract the unique ID and concatenate it with the URL and navigate to the new window, this method worked for almost all of the new windows. this would work if anyone else has the same problem
cy.visit(Cypress.env('homePage'))
cy.server()

        cy.route("POST","myCompany.com/contactID=*").as("getUrl")       
       
        // Method to click on the Add Contact button
        //after clicking this button the new window opens with a partial dynamic url contactID=897ght56475c9988, for example :"mycompany.com/contactID=897ght56475c9988
        contactPageObj.SubmitContactBtn().click()

        cy.wait("@getUrl")
            
        cy.get("@getUrl").then((xhr)=>{
        expect(xhr.status).to.eq(200)
        expect(xhr.response.body.contact.email).to.eq('Jane@mycompany.com')
        let contactID =(xhr.response.body.contact.email)
        cy.log(contactID)

        let contactDetailsPage=Cypress.env('contactDetailsPageUrl')+contactID

       // cy.writeFile('cypress\\integration\\Other\\XHR Testing\\xhrcaptData.json',xhr.response.body.contact.email)
       cy.visit(contactDetailsPage)

**Comment by jennifer-shehane** [comment] 2020-12-22 04:05
Great. I'll be closing this issue as resolved.

**Closed by jennifer-shehane** 2020-12-22 04:05 UTC
Labels: stage: needs information

**Comment by Abduxukur** [comment] 2022-08-11 06:40
@bahmutov my issue is about switch window scenario is below
my application there is have the button upload ,when i click this button there opened a now window ,and then first window window.name ='',new window name is have defined by dev like pre-screen ,the url is the same url just window name is diffreret ,i want to go the new window and get element or some opreation ,but now i can't enter the new window that you provied solution,could you please give me other solution fix this ?

**Comment by bahmutov** [comment] 2022-08-11 07:37
Please provide a repo that shows the app and the test your are writing. Without an app I  do not have time to show any possible solutions

**Comment by Abduxukur** [comment] 2022-08-11 09:02
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 4:43:49 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gleb Bahmutov ***@***.***>
发送时间: Thursday, August 11, 2022 3:37:31 PM
收件人: cypress-io/cypress ***@***.***>
抄送: Abduxukur ***@***.***>; Comment ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


Please provide a repo that shows the app and the test your are writing. Without an app I do not have time to show any possible solutions

**Comment by Abduxukur** [comment] 2022-08-11 09:02
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:07 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 4:43:49 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gleb Bahmutov ***@***.***>
发送时间: Thursday, August 11, 2022 3:37:31 PM
收件人: cypress-io/cypress ***@***.***>
抄送: Abduxukur ***@***.***>; Comment ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


Please provide a repo that shows the app and the test your are writing. Without an app I do not have time to show any possible solutions

**Comment by Abduxukur** [comment] 2022-08-11 09:03
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:41 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:07 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 4:43:49 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gleb Bahmutov ***@***.***>
发送时间: Thursday, August 11, 2022 3:37:31 PM
收件人: cypress-io/cypress ***@***.***>
抄送: Abduxukur ***@***.***>; Comment ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


Please provide a repo that shows the app and the test your are writing. Without an app I do not have time to show any possible solutions

**Comment by Abduxukur** [comment] 2022-08-11 09:04
Dev code
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:59 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:41 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:07 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 4:43:49 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gleb Bahmutov ***@***.***>
发送时间: Thursday, August 11, 2022 3:37:31 PM
收件人: cypress-io/cypress ***@***.***>
抄送: Abduxukur ***@***.***>; Comment ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


Please provide a repo that shows the app and the test your are writing. Without an app I do not have time to show any possible solutions

**Comment by Abduxukur** [comment] 2022-08-11 09:04
My code
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:04:17 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)

Dev code
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:59 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:41 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 5:02:07 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 居麦 热米提拉 ***@***.***>
发送时间: Thursday, August 11, 2022 4:43:49 PM
收件人: cypress-io/cypress ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gleb Bahmutov ***@***.***>
发送时间: Thursday, August 11, 2022 3:37:31 PM
收件人: cypress-io/cypress ***@***.***>
抄送: Abduxukur ***@***.***>; Comment ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


Please provide a repo that shows the app and the test your are writing. Without an app I do not have time to show any possible solutions

**Comment by Abduxukur** [comment] 2022-08-11 09:06
@bahmutov send you by my phone just photo

**Comment by Abduxukur** [comment] 2022-08-11 10:55
@bahmutov i am waiting for you  solution, may i explained the issue good?have you understand my issue?

**Comment by bahmutov** [comment] 2022-08-11 10:58
No. A photo of the code is not enough. Make a public repo with instructions how to install and run it. Maybe then someone can help.

**Comment by Abduxukur** [comment] 2022-08-11 11:07
i can't public repo with istruction ,because of  company policy,may be this is not possible

**Comment by bahmutov** [comment] 2022-08-11 11:57
I don’t need your app. I need similar minimal app reproduction

**Comment by Abduxukur** [comment] 2022-08-11 12:02
sorry i wrong understand you means


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gleb Bahmutov ***@***.***>
发送时间: Thursday, August 11, 2022 7:57:28 PM
收件人: cypress-io/cypress ***@***.***>
抄送: Abduxukur ***@***.***>; Comment ***@***.***>
主题: Re: [cypress-io/cypress] Can't switch to the new Window (#14231)


I don’t need your app. I need similar minimal app reproduction
