### ISSUE TITLE
Cannot login to dashboard from Test Runner using 'Log in with Email' option

### ISSUE THREAD

**Issue by blackgrouse** [cypress-io/cypress#9441] opened 2020-12-03 11:19 UTC
### Current behavior

Logging in to dashboard via test runner and selecting 'Log in with Email' results in blank screen in Chrome.

### Desired behavior
Should be able to enter credentials and login

### Test code to reproduce

1. Start Test Runner
2. Select 'Log in'
3. When browser opens select 'Log in with email' option
4. Get blank screen

F5 results in 404 screen for the URL https://dashboard.cypress.io/test-runner-login/email

### Versions
Cypress 6.0.1, Chrome 86

**Comment by jennifer-shehane** [comment] 2020-12-04 03:59
Hello, yes, I can confirm that logging in via email from the Test Runner is a dead end. 

I've notified our Dashboard engineering team so they are investigating. I'll update this issue with any updates.

**Comment by jennifer-shehane** [comment] 2020-12-05 00:26
A fix for this issue has been deployed by our Dashboard team and is now available. This fix is immediately live and does not require an update of the Cypress Test Runner.

**Comment by blackgrouse** [comment] 2020-12-07 09:30
I no longer get the 404 error, but using valid credentials I can't log in via this route.  I can login if I browse to dashboard.cypress.io.

![image](https://user-images.githubusercontent.com/37184954/101333767-e5ecee00-386e-11eb-8a54-970bf86406cd.png)

**Comment by jennifer-shehane** [comment] 2020-12-07 11:21
Thanks for the update. I've informed the Dashboard team to look into this.

**Comment by jennifer-shehane** [comment] 2020-12-08 15:23
@blackgrouse Our team believes this may be a cache issue since we can’t replicate the issue. Could you clear your browser cache and try again?

**Comment by blackgrouse** [comment] 2020-12-09 08:09
@jennifer-shehane I can confirm I can login after clear the browser cache.  Thanks.

**Closed** 2020-12-09 09:03 UTC
Labels: external: dashboard, type: bug
