### ISSUE TITLE
Implement .tab() for checking keyboard accessibility

### ISSUE THREAD

**Issue by Graham42** [cypress-io/cypress#852] opened 2017-10-30 17:21 UTC
- Operating System: Ubuntu 16.04
- Cypress Version: 1.0.3
- Browser Version: Google Chrome 62.0.3202.75

### Is this a Feature or Bug?
Feature

### Current behavior:
`cy.focused().type('{tab}');` fails with error
>  CypressError: {tab} isn't a supported character sequence. You'll want to use the command cy.tab(), which is not ready yet, but when it is done that's what you'll use.

### Desired behavior:
To navigate elements using `.tab()`

#### Test code:

1. Clone https://github.com/Graham42/test-case-cypress-tabbing
2. In one terminal run `npm run start`
3. In a second terminal run `npm run test` to open cypress
4. Choose the `tabbing_spec.js` suite

### Additional Info (images, stack traces, etc)

This feature is important in order to test forms for keyboard accessibility.

**Comment by jennifer-shehane** [comment] 2017-10-30 17:30
Thanks for providing a reproducible example! I am closing this and referencing it as duplicate of #299. 

Luckily the issue described in the initial issue should no longer be the case with Chrome, so this is now more possible than before.

> There is an open issue in Chromium to add multiplexing support so we've been waiting for that to go live.

**Comment by Graham42** [comment] 2017-10-30 17:31
ah sorry, did a search and didn't find that one.

**Closed by jennifer-shehane** 2017-10-30 17:30 UTC
