### ISSUE TITLE
"autofocus" not working with Chrome since Chrome 79

### ISSUE THREAD

**Issue by AlexGrek** [cypress-io/cypress#6207] opened 2020-01-21 14:24 UTC
### Current behavior:

"autofocus" attribute works with Electron and with older Chrome versions, but it does not work in Chrome 79. 
When testing a page with "autofocus" attribute, `cy.focused()` returns no elements, and nothing is in focus. 

Chrome console log:

```log
Autofocus processing was blocked because a document's URL has a fragment '#/tests/__all'.
```

### Desired behavior:

Autofocus attribute is working in tests as expected in any supported browser, including Chrome 79.
No warnings in JS console log.

### Test code to reproduce

Simple HTML page:
```html
<!DOCTYPE html>
<html>
<body>
<form>
  First name:<br>
  <input type="text" name="firstname" autofocus>
  <br>
  Last name:<br>
  <input type="text" name="lastname">
</form>
</body>
</html>
```

Code of the integration test:
```js
describe('Focus', function() {
    it.only('autofocus', function() {
        cy.visit('./af.html');
        cy.focused().should('have.attr', 'name','firstname');
    });
});
```

### Versions

Cypress 3.8.2
Chrome 79.0.3945.117
Ubuntu 16.04 and 18.04

**Comment by jennifer-shehane** [comment] 2020-01-21 16:30
Welp, that is very weird. Confirmed this happens in Chrome 79. Did not narrow down to what specific release. 

<img width="750" alt="Screen Shot 2020-01-21 at 10 59 08 PM" src="https://user-images.githubusercontent.com/1271364/72823214-b9a1a080-3ca1-11ea-81d3-aa522725feef.png">

**Comment by jackyl** [comment] 2020-02-03 20:40
Hi,

I think it's broken when there's hashtag in the url, in my case there were 4, and the console message was:

`Autofocus processing was blocked because a document's URL has a fragment '####'.`

If you open the simple html page in chrome without any testing integrated, autofocus works fine.

**Comment by raryson** [comment] 2020-02-28 13:43
Same here

**Comment by staspk** [comment] 2020-02-29 03:32
Same issue. Developing an angular app and Chrome won't autofocus. Gives "_Autofocus processing was blocked because a document's URL has a fragment '#/login'._" error. Does work on Firefox.

**Comment by Darkle** [comment] 2020-03-23 08:43
Here's the tracking bug for chromium: https://crbug.com/1046357

**Comment by dcrystalj** [comment] 2020-03-30 07:12
I wouldnt say this is chrome related because I have same issue using firefox 72 beta. Element does not get auto-focused while running tests. After opening page in new tab I can see autofocus is working (same browser)

**Comment by rrfaria** [comment] 2020-05-05 14:57
I noticed on  cypress when open interface run tests and I start work with another screen and leave tests running ... 
if there is no focus on chrome ... it don't pass tests with focus on fields.

I must to keep the focus on chrome window running

**Comment by KennyEng12** [comment] 2020-07-23 10:47
> I wouldnt say this is chrome related because I have same issue using firefox 72 beta. Element does not get auto-focused while running tests. After opening page in new tab I can see autofocus is working (same browser)

@dcrystalj Safari doesn't has this issue.

Thanks,
Kenny.

**Comment by sainthkh** [comment] 2020-09-16 06:15
This is related with the [html spec](https://html.spec.whatwg.org/multipage/interaction.html#flush-autofocus-candidates). 

To fix this problem, spec should be changed (the discussion is going on [here](https://github.com/whatwg/html/issues/5252)), or cypress should change the test url structure.

**Comment by boyet007** [comment] 2021-01-30 01:38
any solve this problem?

**Comment by bahmutov** [comment] 2021-04-05 20:38
I have created simple reproduction in https://github.com/cypress-io/cypress-test-tiny/tree/focused-bug

- fails in Electron 87
- fails in Chrome 89
- works in Chrome Canary 91

See https://bugs.chromium.org/p/chromium/issues/detail?id=1046357#c15 for Chrome fix progress

**Comment by jennifer-shehane** [comment] 2021-10-15 19:55
This has been fixed in newer versions of Chrome. Closing as resolved.

**Closed by jennifer-shehane** 2021-10-15 19:55 UTC
Labels: type: bug, browser: chrome, stage: awaiting external fix

**Comment by YaelDillies** [comment] 2022-10-04 09:41
I get this error again on Chrome 105.
