### ISSUE TITLE
Cypress 13.6.0+ Hanging During Run

### ISSUE THREAD

**Issue by hrapulya** [cypress-io/cypress#28459] opened 2023-12-05 12:57 UTC
### Current behavior

While running test through Cypress App
`npx cypress open`
the specs execution is hanging without any error and need to stop it and re-run it again, spinner is rolling:
![Screenshot 2023-12-05 at 13 51 12](https://github.com/cypress-io/cypress/assets/3442105/b1f3d9b0-fa50-4d81-b877-95b7d45910f6)

Note: there was no changes in this spec and it was running ok with Cypress 12

Chrome:
Version 119.0.6045.199

### Test code to reproduce

no response

### Cypress Version

13.6.0

### Node version

v18.17.0

### Operating System

macOS 14.1.2 Sonoma, Apple M2

**Comment by hrapulya** [comment] 2023-12-05 13:06
Seems the issue happens in Chrome Browser, as Electron works as expected

**Comment by ItsWasteD** [comment] 2023-12-05 13:43
I think I had almost the same issue. It worked with cypress `13.5.1` and when I upgraded to `13.6.0` some specs stopped working on Edge. With Chrome the still work as expected. For me it was within `cy.stub()` that it startet "hanging" not sure what the issue is tho.

It showed me that the test was still running and the spinning wheel as in the screenshot could be seen. But in the cypress runner there was no "active step" still executing.

**Comment by jennifer-shehane** [comment] 2023-12-05 15:19
@hrapulya @ItsWasteD There's an issue open with 13.6.0 hanging when you pull focus away from the window. Let me know if this is what is happening in your case... We haven't been able to reproduce it though, so it would be really really helpful to provide a way to reproduce it. https://github.com/cypress-io/cypress/issues/28392

**Comment by ItsWasteD** [comment] 2023-12-06 13:25
Hmm for me it doesnt seem to have to do with the window focus. Or let me be more specific I could reproduce the same behaviour with pulling away the focus but for me the problem also occurs even with window focus. I'm trying to `stub` a `confirm()` inside an `iframe`. That also seems to work but after all the steps inside the test are finished it still shows that the test is running a step. And I only have this problem with Edge, in Chrome everything works as expected.
![Pasted image 20231206135538](https://github.com/cypress-io/cypress/assets/18613337/73919b0b-f02c-41ba-bdae-5a02e9f6b5e9)
Sadly I cant provide a reproducible example. I tried to create a page with an `iframe` that has a button with a `confirm()` inside but there the tests worked normally.

**Comment by JarekSuchocki** [comment] 2023-12-06 19:09
> @hrapulya @ItsWasteD There's an issue open with 13.6.0 hanging when you pull focus away from the window. Let me know if this is what is happening in your case... We haven't been able to reproduce it though, so it would be really really helpful to provide a way to reproduce it. #28392

@jennifer-shehane  We have exact same thing. Only in Chrome browser, when you get out of cypress runner window it hangs without any errors.

**Comment by Ollisteka** [comment] 2023-12-08 08:23
Cypress `10.10.0` and `13.6.0` `cypress run` also hang on Chrome 120. It was working fine on Chrome 119

![image](https://github.com/cypress-io/cypress/assets/27495566/fb8c7214-400d-4b3c-889d-003f3b054a6c)
![image](https://github.com/cypress-io/cypress/assets/27495566/a4fc9433-a8b2-4173-9ec2-7d2cbd444169)

**Comment by kdp88** [comment] 2023-12-08 16:00
I am seeing the same behavior in jenkins 
```
| Cypress:  13.5.1
│Browser: Chrome 120 (headless)
│Node Version:   v18.19.0 (/usr/bin/node)
```  
i am running `DEBUG=cypress* npx cypress run` and seeing a lot of 

```
CreatePlatformSocket() failed: Address family not supported by protocol (97)
```

would this indicate chrome crashing ?

**Comment by psibean** [comment] 2023-12-13 10:53
I've been able to reproduce this locally 99% of the time on 13.6.0 and 13.6.1, it isn't the same as the focus issue, as I also experienced that problem separately from this one.

Happens on both MacOS 14.1.2 and 14.2. M1

Cypress 13.6.0 and 13.6.1 both presented this issue for me.

I tried all of the following and various combinations there of:

```
cypress cache clear
cypress install
/Users/abignell/Library/Caches/Cypress/13.6.0/Cypress.app --smoke-test --ping=101
rm -rf node_modules
yarn install
cypress cache path # and clearing
```

**As well as clearing the App Data** under Developer Tools > View App Data.

Nothing works. There's an extremely small chance doing all of the above will allow me to run one test, but then the focus bug happens and prevents the test from running, and then re-running the test puts it back where it doesn't run at all.

The smoke test didn't show any errors or warnings, while starting Cypress and Chrome, no warnings or errors, even with `ELECTRON_ENABLE_LOGGING` set to true, everything was fine, but Cypress would hang indefinitely and not even start the spec execution.

I reverted back to the last known working version we had, 13.3.3 and it worked right away.

I then updated to 13.5.1 and it also worked immediately.

Updating back to 13.6.0, the issue presented itself straight away, going back to 13.5.1 works.

So something in 13.6.0 has caused this problem.

Edit: So far 13.5.1 has been one of the better experiences I've had had since migrating from v10 to  v12 and then v13

Edit: I should also note I am running in an arm64 context. When running Chrome via cypress and checking the version, it shows it is definitely the arm64 version of the browser.

**Comment by droca** [comment] 2023-12-15 10:21
My team and me are experiencing the same issues mentioned above on cypress 13.6.X, MacOS ventura 13.6.3.
Downgrading to 13.5.1 did the trick for now.

**Comment by jennifer-shehane** [comment] 2024-01-04 22:33
We're still looking for a way to reproduce this hanging, seperate from the focus hang issue if anyone can provide a reproducible example.

**Comment by psibean** [comment] 2024-01-12 09:40
> We're still looking for a way to reproduce this hanging, seperate from the focus hang issue if anyone can provide a reproducible example.

I think "reproducible" will be difficult, however I am able to reproduce this 100% of the time on my work mac and project. Is there anything I can do or provide that would be helpful? Is there a way I can run Cypress itself in debug mode from within `node_modules`, I suppose I could hook into it via the vscode debugger. Would there be any areas in particular that I should put breakpoints? In the terminal output, it seems to make some spec specific requests (like to the cypress server, not as part of my test), and then just hangs.

If you point me to the code that starts a spec run when the "re-run" button is pressed from the command pane, I can debug this and provide more insight. I'm just not familiar with the Cypress codebase itself.

**Comment by ItsWasteD** [comment] 2024-01-12 10:23
For me its the same thing as @psibean I can't really provide a reproducible example because we are testing applications that we develop inside another very big webapplication (a document management system) that is developed by a third party. I couldn't find a way to reproduce it outside of this application. If there is another way I can help I will try.

**Comment by waterkamp** [comment] 2024-01-18 21:40
Hi all,

I just started with Cypress Component Testing v13.6.3.

1. I have a simple HelloWorld Component Test. (only cy.mount(HelloWorldComponent); )
2. I start Cypress Component Testing in Watch (Headed) mode with Chrome v120
3. It hangs at cy.mount(HelloWorldComponent) -> no errors anywhere!
4. I stop the tests manually
5. Run it again and - it works!
6. When I do a change within the Component and the watcher kicks in I have the same hanger at cy.mount() again.

I have no problems to run the HelloWorldComponent test with:
- Edge v120
- Electron v114

Hope this helps a little bit.

Would be nice to find a solution to fix it to be able to run the test with Chrome.

**Comment by ariep** [comment] 2024-02-08 16:21
Our project seems to experience this problem as well: we run cypress tests in a docker container as part of our CI pipeline. With 13.5, our tests succeed. Any attempt to upgrade cypress to 13.6 results in one particular test hanging (page load timeout).

This is an open source project, but the pipeline outputs are not publicly visible. The project structure is complex so it would not be particularly easy to extract an independent reproducing example, but if this would help a cypress maintainer to pinpoint this bug I can attempt to do so.

**Comment by psibean** [comment] 2024-02-08 22:24
> Our project seems to experience this problem as well: we run cypress tests in a docker container as part of our CI pipeline. With 13.5, our tests succeed. Any attempt to upgrade cypress to 13.6 results in one particular test hanging (page load timeout).

Just to check here, your spec actually runs, and then the page load hits a timeout, or?

This issue pertains to a spec not even starting, it hangs on the "Your tests are loading..." and never progresses. Screenshot attached.

![image](https://github.com/cypress-io/cypress/assets/20571408/f237db77-9c65-45f7-a33b-6a1ae5c1a6ac)

Lets say I have a spec file named "example.tests.ts", the last output in the Cypress terminal is this:

```
GET /__cypress/tests?p=cypress/integration/path/to/spec/file/example.tests.ts 200 3794.367 ms - -
```
@jennifer-shehane where is this request made in the Cypress code? With this information I could debug the problem and provide more insight.

**Comment by ItsWasteD** [comment] 2024-02-08 22:40
> > Our project seems to experience this problem as well: we run cypress tests in a docker container as part of our CI pipeline. With 13.5, our tests succeed. Any attempt to upgrade cypress to 13.6 results in one particular test hanging (page load timeout).
> 
> Just to check here, your spec actually runs, and then the page load hits a timeout, or?
> 
> This issue pertains to a spec not even starting, it hangs on the "Your tests are loading..." and never progresses. Screenshot attached.
> 
> ![image](https://private-user-images.githubusercontent.com/20571408/303499906-f237db77-9c65-45f7-a33b-6a1ae5c1a6ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzE2MjIsIm5iZiI6MTcwNzQzMTMyMiwicGF0aCI6Ii8yMDU3MTQwOC8zMDM0OTk5MDYtZjIzN2RiNzctOWM2NS00NWY3LWEzM2ItNmExYWU1YzFhNmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDIyMjg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmM4MjI4N2YyODJlODIwNzU4ODBjNTcwMGIxOWRjZDhhNzE3NWY0NTA3YjljNTg5Y2NlOWIzOWRjZjRlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.77cQ6MLO6EKMq0C6wczcVHQJwaU1WKIZ2-5VcbAbVa4)
> 
> Lets say I have a spec file named "example.tests.ts", the last output in the Cypress terminal is this:
> 
> ```
> GET /__cypress/tests?p=cypress/integration/path/to/spec/file/example.tests.ts 200 3794.367 ms - -
> ```

Thats not what happens for me. My first comment in this Issue resembles what happens to me. Suddenly the test doesn't continue even tho there wasn't an error or anything. Also it doesn't show the currently running command inside the test.

**Comment by psibean** [comment] 2024-02-08 22:46
> Thats not what happens for me. My first comment in this Issue resembles what happens to me. Suddenly the test doesn't continue even tho there wasn't an error or anything. Also it doesn't show the currently running command inside the test.

And ah yeah, my bad. It's hard to tell from the OP as their screenshot doesn't show whether or not the test was running. But the title does say "during run", so maybe I've got the wrong issue. 👍🏻

**Comment by jennifer-shehane** [comment] 2024-02-26 20:08
Could you all try to update to 13.6.6 and let us know if you're still experiencing this issue? We fixed an issue in 13.6.5 with some hanging situations that were introduced in 13.6.0 and we want to understand if this has also resolved this issue. Thank you!

**Comment by ItsWasteD** [comment] 2024-02-27 10:51
@jennifer-shehane I updated to 13.6.6 and all the tests I tried worked fine. I will update you if there are any problems but for now at least for me that issue seems solved.

**Comment by droca** [comment] 2024-02-27 11:07
I got a laptop upgrade from an `intel` processor one to an `apple silicon m2` one and I cannot reproduce the issue that I was experiencing before.
In this new m2 macbook, running Sonoma 1.4.3.1, running cypress 13.6.4 and 13.6.6 worked perfectly and I couldn't reproduce the issue.

Could it be that the issue is focused on older, intel processor macbooks?

**Comment by jennifer-shehane** [comment] 2024-02-27 15:40
Going to close this as resolved and monitor any more comments left here.

**Closed as completed by jennifer-shehane** 2024-02-27 15:40 UTC
Labels: v13.6.0 🐛

**Comment by psibean** [comment] 2024-05-21 00:49
I've since bumped up to 13.9.0, and so far things seem fine in regards to the hanging / freezing experience I was having with 13.6.2. I can see all kinds of various fixes since then that might have been the cause (for example, the extension being disabled / unavailable).
