### ISSUE TITLE
npm install fails to find minimist package

### ISSUE THREAD

**Issue by tylerthehaas** [cypress-io/cypress#16399] opened 2021-05-07 17:51 UTC
### Current behavior
when I run `npm i -D cypress` I get the following error

![image](https://user-images.githubusercontent.com/11150235/117489050-5ab17a80-af2a-11eb-8d11-7dc3070f306e.png)

### Download method
 

- [x] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [x] Mac
- [ ] Windows

### Other

- [x] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by JohnIrle** [comment] 2021-05-21 21:18
I am also getting this error in one of my project. I am on MacOS big sur, using npm version `7.14.0` and node version `15.8.0` The command works in a fresh project created with `npm init`. The project it is failing on is a create-react-app project with typescript. 
```json
{
  "name": "markdown",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "5.11.6",
    "@testing-library/react": "11.1.2",
    "@testing-library/user-event": "12.2.2",
    "@types/jest": "26.0.14",
    "@types/marked": "1.1.0",
    "@types/node": "14.11.2",
    "@types/react": "16.9.50",
    "@types/react-dom": "16.9.8",
    "bootstrap": "4.3.1",
    "marked": "0.7.0",
    "react": "^16.11.0",
    "react-bootstrap": "1.0.0-beta.14",
    "react-dom": "^16.11.0",
    "react-scripts": "4.0.0",
    "typescript": "^4.0.3"
  },
  "homepage": "https://johnirle.com/markdown",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by JohnIrle** [comment] 2021-05-21 21:33
As a follow up, cypress installs correctly in a fresh application created with `npx create-react-app --template typescript`.

**Comment by lmiller1990** [comment] 2021-05-24 04:46
> I am also getting this error in one of my projects. I am on MacOS Big Sur, using npm version `7.14.0` and node version `15.8.0` The command works in a fresh project created with `npm init`. The project is failing on a create-react-app project with typescript.
> 
> ```json
> {
>   "name": "markdown",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@testing-library/jest-dom": "5.11.6",
>     "@testing-library/react": "11.1.2",
>     "@testing-library/user-event": "12.2.2",
>     "@types/jest": "26.0.14",
>     "@types/marked": "1.1.0",
>     "@types/node": "14.11.2",
>     "@types/react": "16.9.50",
>     "@types/react-dom": "16.9.8",
>     "bootstrap": "4.3.1",
>     "marked": "0.7.0",
>     "react": "^16.11.0",
>     "react-bootstrap": "1.0.0-beta.14",
>     "react-dom": "^16.11.0",
>     "react-scripts": "4.0.0",
>     "typescript": "^4.0.3"
>   },
>   "homepage": "https://johnirle.com/markdown",
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> }
> ```

I tried copy pasting this into a `package.json` file then running `npm install` and it failed. This `package.json` does not contain `cypress`.

**Comment by JohnIrle** [comment] 2021-05-24 05:19
Interesting. I also get that if I try to install from the package json. It was working in the project but I may have run `npm audit` and messed somethings up. I ended up just creating a new project with CRA and moving the files. Sorry if that was a waste of time.

**Comment by lmiller1990** [comment] 2021-05-24 05:28
No problem - happy to investigate any problem related to Cypress, even if it turns out not to be directly related.

I'll close this for now since there's no way to reproduce the original issue, or any clear action to be taken. Happy to re-open if someone finds a problem.

**Closed by lmiller1990** 2021-05-24 05:28 UTC
Labels: stage: needs information, topic: installation
