### ISSUE TITLE
trigger("keydown", ...) or type() seems to have a different behaviour compared to browsers?

### ISSUE THREAD

**Issue by paxcodes** [cypress-io/cypress#4650] opened 2019-07-04 13:41 UTC
### Current behavior:

The tests "should have an empty value" pass.
![the tests](https://user-images.githubusercontent.com/13646646/60670650-0fa61800-9e26-11e9-8e16-1d97f4edff4b.gif)

### Desired behavior:

The tests "should have an empty value" should fail. 

Given how the code is now, the shortcut key (;) is entered in the textfield everytime I use the shortcut.
![value_becomes_semicolon](https://user-images.githubusercontent.com/13646646/60670675-192f8000-9e26-11e9-838a-b519254c2259.gif)

### Steps to reproduce: 
A [repository](https://github.com/akosipax/cypress-test) to the app code + test code is available.

Just serve it with `npx serve` and you can change the  `baseURL` in cypress.json in case the port changes.

(I didn't realize that there was a cypress-test-tiny repo that I could fork so I made my own repo)

### Versions

Cypress 3.3.2

Mac OS 10.14.5

Chrome 75

**Comment by jennifer-shehane** [comment] 2019-07-11 07:30
Right, I got a little confused with the description. Basically - there are no global shortcuts coded within the application, so when you are not focused on anything and you click the `;` button, it should type into the input. - this behavior is not being simulated in Cypress - it's not typing into the input when you do `cy.get('body').type(';')`

I'm able to reproduce this difference in behavior from this repo https://github.com/akosipax/cypress-test

cc @ben

**Comment by akosipax** [comment] 2019-07-12 13:34
Yes. Basically, the app code I have for shortcuts (in this case, focusing on the text field when pressing ";") is still incorrect but Cypress was giving me a false positive telling me that my tests pass when it actually should fail.

The tests in the repo I gave here are not my app's actual tests but tests to simply reproduce the inconsistent behaviour between type()/trigger('keydown') and the browser.

**Comment by Bkucera** [comment] 2019-10-22 22:55
tested with changes from #4870 , and the test correctly fails: 
![Uploading image.png…]()

**Comment by Bkucera** [comment] 2019-10-22 22:56
closing as duplicate of #2240

**Closed by Bkucera** 2019-10-22 22:56 UTC
Labels: pkg/driver, stage: ready for work, topic: cy.type ⌨️, type: bug
