### ISSUE TITLE
[BUG] Cypress unable to load the changes on file save autorun

### ISSUE THREAD

**Issue by vrknetha** [cypress-io/cypress#7751] opened 2020-06-18 10:07 UTC
<Test runner won't execute before all and before each on autorun when a file is saved in cypress 4.8.0>

### Current behavior:

![image](https://user-images.githubusercontent.com/20596261/85007227-db338500-b178-11ea-8ea4-4f7c8e4881bb.png)
![image](https://user-images.githubusercontent.com/20596261/85007248-e4bced00-b178-11ea-8f94-30a30f807942.png)

Once I refresh it works fine.

Also, execution won't stop when an assertion failed it has to be stopped manually.

![image](https://user-images.githubusercontent.com/20596261/85007497-3d8c8580-b179-11ea-9da5-f59043caac92.png)

**Comment by jennifer-shehane** [comment] 2020-06-22 08:51
Can you provide the code you're running - how you have the `before` set up in your tests? A repo would be ideal. Thanks!

**Comment by vrknetha** [comment] 2020-06-24 15:06
I figured out the issue, It is due to a node module @testing-library/cypress. I am filing a bug there. Closing this for now.

**Comment by vrknetha** [comment] 2020-07-01 19:15
@jennifer-shehane Any update on this?

**Comment by jennifer-shehane** [comment] 2020-07-02 07:46
Yeah, I can recreate this. Do you use service workers on your application? May be duplicate of #702 - where the file watching doesn't update when testing a site with Service Workers. 

As a side note, you can't have 2 `module.exports` defined in your `plugins` file, you should only export one thing. You want to do:

```js
module.exports = (on, config) => {
	on('file:preprocessor', cypressTypeScriptPreprocessor);
	// `on` is used to hook into various events Cypress emits
	// `config` is the resolved Cypress config
	on('task', {
		async loginUsingFacebook({user, pass}) {
			const cookies = await FacebookLogin(user, pass);
			return cookies;
		}
	});
};
```

**Comment by vrknetha** [comment] 2020-07-02 08:08
Thank you for the update, We use service worker in our application.

**Comment by jennifer-shehane** [comment] 2020-07-02 08:20
Closing as duplicate of #702

**Closed by jennifer-shehane** 2020-07-02 08:20 UTC
Labels: stage: awaiting response

**Comment by vrknetha** [comment] 2020-07-08 09:33
@jennifer-shehane  I have disabled the service worker all together but still, I am facing this issue.

![image](https://user-images.githubusercontent.com/20596261/86902752-01bb5f00-c12c-11ea-9994-0c72812ae1ac.png)
![image](https://user-images.githubusercontent.com/20596261/86902795-10a21180-c12c-11ea-9d2a-9da00a2c91f1.png)
 You can use the same code and test by unregistering the service worker. You would still get the issue.
