### ISSUE TITLE
Cypress 7.0 - Vue - Component testing - devServer undefined on cypress open-ct and lazy-compile-webpack-plugin bug

### ISSUE THREAD

**Issue by JasonFairchild** [cypress-io/cypress#15838] opened 2021-04-07 02:53 UTC
### Current behavior
I have confirmed that when I run "npx cypress open" everything works fine with 7.0, but when I run "npx cypress open-ct" I get the following error log:
```
(node:18324) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
Error [TypeError]: Cannot read property 'devServer' of undefined
    at Object.<anonymous> (C:\Users\jfairchild\Projects\VitalSmarts FE\node_modules\@cypress\webpack-dev-server\dist\startServer.js:54:90)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jfairchild\Projects\VitalSmarts FE\node_modules\@cypress\webpack-dev-server\dist\startServer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: Cannot read property 'devServer' of undefined
    at Object.<anonymous> (C:\Users\jfairchild\Projects\VitalSmarts FE\node_modules\@cypress\webpack-dev-server\dist\startServer.js:54:90)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jfairchild\Projects\VitalSmarts FE\node_modules\@cypress\webpack-dev-server\dist\startServer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I am trying to migrate component testing for a Vue2 app. I have triple checked that I followed all the recommended guide steps. 
Cypress.json:
```
{
  "pluginsFile": "cypress/plugins/index.js",
  "supportFile": "cypress/support/index.js",
  "fixturesFolder": "cypress/fixtures",
  "integrationFolder": "cypress/e2e",
  "testFiles": "**/*.spec.@(js|ts)",
  "componentFolder": "src",
  "baseUrl": "http://localhost:8080"
}
```

package.json (I tried removing @cypress/webpack-preprocessor but that made no difference):
```
{
  "name": "cumulus-vapor",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "storybook": "start-storybook -s -p 6006",
    "build-storybook": "build-storybook",
    "storybook:serve": "vue-cli-service storybook:serve -p 6006 -c .storybook",
    "test:e2e": "vue-cli-service test:e2e",
    "test:components": "vue-cli-service test:components"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "devextreme": "20.2.5",
    "devextreme-vue": "20.2.5",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-cli-plugin-storybook": "^2.0.0",
    "vue-clickaway": "^2.2.2",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "^3.5.1",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.13.8",
    "@cypress/vue": "2",
    "@cypress/webpack-dev-server": "^1.1.2",
    "@prettier/plugin-pug": "^1.13.5",
    "@storybook/addon-actions": "^6.1.21",
    "@storybook/addon-essentials": "^6.1.21",
    "@storybook/addon-links": "^6.1.21",
    "@storybook/vue": "^6.1.21",
    "@testing-library/cypress": "^7.0.4",
    "@types/node": "^14.14.36",
    "@types/vue-clickaway": "^2.2.0",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-e2e-cypress": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "babel-loader": "^8.2.2",
    "cypress": "^7.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^2.2.1",
    "pug-plain-loader": "^1.1.0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3",
    "vue-cli-plugin-cypress-experimental": "~1.2.0",
    "vue-template-compiler": "^2.6.11"
  }
}
```

Plugins index.js:
```
/* eslint-disable @typescript-eslint/no-var-requires */
const { startDevServer } = require("@cypress/webpack-dev-server");
const custom = require("@vue/cli-service/webpack.config");
module.exports = (on, config) => {
  //require("@cypress/code-coverage/task")(on, config);
  on("dev-server:start", (options) => {
    return startDevServer({ options, custom });
  });
  return config;
};
```
I'm not sure what else I should/could provide. If webpack or Vue config details need to be known, that'd take a bit more explanation or doing for me. I didn't set that up and I'm far from an expert on it.
### Desired behavior
open-ct works and devServer is defined or handled properly.

### Test code to reproduce
I'm not sure if this is realistic to provide. I don't know if any Vue CLI project would exhibit this behavior or if it is more specific to my project's setup. If others can confirm that their Vue apps work with cypress 7.0 component testing, that would help. But let me know if code is really necessary or any other info and I will see what I can do.

### Versions

I just updated to Cypress 7.0. Component testing was working quite well for our project on 6.8, previous to this update and attempted migration.

I'm on windows 10.
Node version 14.15.3
Never get to the browser, so I doubt it will matter, but I usually use Chrome 89.0.4389.114

**Comment by lmiller1990** [comment] 2021-04-07 04:20
Hey, I did not try to reproduce your error (yet) but first thing I noticed:

```
/* eslint-disable @typescript-eslint/no-var-requires */
const { startDevServer } = require("@cypress/webpack-dev-server");
const custom = require("@vue/cli-service/webpack.config");
module.exports = (on, config) => {
  //require("@cypress/code-coverage/task")(on, config);
  on("dev-server:start", (options) => {
    return startDevServer({ options, custom });
  });
  return config;
};
```

**Comment by JasonFairchild** [comment] 2021-04-07 17:04
Thanks for the advice. I fixed the webpackConfig name. It does get farther, but there are other problems now it seems. The component runner comes up, but there are no spec files listed and there are errors from the console:
```
$ "C:\Users\jfairchild\Projects\VitalSmarts FE\node_modules\.bin\cypress" open-ct

(node:24232) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
i ∩╜ówds∩╜ú: Project is running at http://localhost:61269/webpack-dev-server/
i ∩╜ówds∩╜ú: webpack output is served from /__cypress/src
i ∩╜ówds∩╜ú: Content not from webpack is served from C:\Users\jfairchild\Projects\VitalSmarts FE
Starting type checking service...
Using 1 worker with 2048MB memory limit
 ERROR  Failed to compile with 1 error10:31:56 AM

This dependency was not found:

* !!C:UsersjfairchildProjectsVitalSmarts FE
ode_moduleslazy-compile-webpack-pluginlibloadersapi.js in ./node_modules/@cypress/webpack-dev-server/dist/browser.js

To install it, you can run: npm install --save !!C:UsersjfairchildProjectsVitalSmarts FE
ode_moduleslazy-compile-webpack-pluginlibloadersapi.js
Type checking in progress...
├ù ∩╜ówdm∩╜ú: Hash: 38bb65571d235841af2e
Version: webpack 4.46.0
Time: 896ms
Built at: 04/07/2021 10:31:56 AM
                                         Asset       Size  Chunks             Chunk Names
               ../../../../../dist/favicon.ico   4.19 KiB          [emitted]
   ../../../../../dist/locales/en/en.base.json   3.63 KiB          [emitted]
../../../../../dist/locales/en/en.courses.json  410 bytes          [emitted]
 ../../../../../dist/locales/en/en.events.json   1.44 KiB          [emitted]
   ../../../../../dist/locales/gr/gr.base.json   3.83 KiB          [emitted]
../../../../../dist/locales/gr/gr.courses.json  410 bytes          [emitted]
 ../../../../../dist/locales/gr/gr.events.json   1.48 KiB          [emitted]
                                    index.html  363 bytes          [emitted]
                                       main.js   4.75 KiB    main  [emitted]  main
Entrypoint main = main.js
[./node_modules/@cypress/webpack-dev-server/dist/browser.js] 559 bytes {main} [built]

ERROR in ./node_modules/@cypress/webpack-dev-server/dist/browser.js
Module not found: Error: Can't resolve 'C:UsersjfairchildProjectsVitalSmarts FE
ode_moduleslazy-compile-webpack-pluginlibloadersapi.js' in 'C:\Users\jfairchild\Projects\VitalSmarts FE\node_modules\@cypress\webpack-dev-server\dist'
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:10-126
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  556 KiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@cypress/webpack-dev-server/index-template.html] 489 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 531 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  557 KiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html] 1.38 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 531 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
i ∩╜ówdm∩╜ú: Failed to compile.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
No type errors found
Version: typescript 3.9.9
Time: 6908ms
(node:24232) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
GET /__/ 200 14.290 ms - -
```
I don't know that I understand the error about 'moduleslazy-compile-webpack-pluginlibloadersapi.js' but does it mean that it is originating from the webpack-dev-server package? I've done 'yarn install' and it tells me I'm all up-to-date. If it could help, we use PUG and SCSS, but those work when we serve our project locally already, so I wouldn't understand why the webpack config didn't handle it already.

This is what the component runner looks like for me:
![image](https://user-images.githubusercontent.com/56280950/113904437-51988680-978f-11eb-9175-a3891204853a.png)

I'm not sure if the errors from the console are necessarily related to why no spec files are listed. Is it still correct to define the component test folder inside the cypress.json as we have it?

**Comment by JasonFairchild** [comment] 2021-04-07 22:59
@lmiller1990 
```
Can't resolve 'C:UsersjfairchildProjectsVitalSmarts FE
ode_moduleslazy-compile-webpack-pluginlibloadersapi.js
``` 
I just realized in this, there appears to be a line break (\n) right where the missing 'n' for node_modules is. Is this some weird quirk of this log, or is it a potential hint at the problem?

**Comment by lmiller1990** [comment] 2021-04-07 23:57
Yep, it's a windows only issue. Seem this is not only known but [also has been patched](https://github.com/liximomo/lazy-compile-webpack-plugin/pull/10), only problem is the repo seems not to be actively maintained.

We will fork and fix the problem, please wait a little!

**Comment by JasonFairchild** [comment] 2021-04-08 02:00
Sounds great. Thanks a ton for looking into all this!

**Comment by lmiller1990** [comment] 2021-04-12 01:31
Fixed in https://github.com/cypress-io/cypress/pull/15889, will leave this open until that is released, should be a few days, tops.

**Comment by lmiller1990** [comment] 2021-04-16 05:51
The latest version of `@cypress/webpack-dev-server` is out and no longer uses the lazy compile plugin. This fixes the problem this issue relates to.

That said, there is another known bug in windows (same problem... backslashes). That is been [tracked in this issue](https://github.com/cypress-io/cypress/issues/15976) which also has an open PR. Let's use that one to track windows progress. I'll close this one off for now, since the problem is addresses has been fixed.

The fix for windows will be part of the next release cycle (every two weeks usually, might be earlier though). Please keep an eye on that issue for updates.

**Closed by lmiller1990** 2021-04-16 05:51 UTC
Labels: component testing, stage: review/qa
