### ISSUE TITLE
cy.route to match on request body for POST

### ISSUE THREAD

**Issue by cookiescrumbs** [cypress-io/cypress#3755] opened 2019-03-20 12:25 UTC
### Current behavior:
```js
cy.fixture('teacher/my-library/skills').then((data) => {
    cy.server();
    cy.route({
        url: '/tag/search',
        method: 'POST',
        response: data
});

cy.fixture('teacher/my-library/level').then((data) => {
    cy.server();
    cy.route({
        url: '/tag/search',
        method: 'POST',
        response: data
});
```
Currently `cy.route` doesn't match the POST request body which means you can't stub requests that have the same url but a different request body.

### Desired behavior:

```js
cy.fixture('teacher/my-library/skills').then((data) => {
    cy.server();
    cy.route({
        url: '/tag/search',
        method: 'POST',
        response: data,
        body: {"filter":{"family":["skills"]}}
});

cy.fixture('teacher/my-library/level').then((data) => {
    cy.server();
    cy.route({
        url: '/tag/search',
        method: 'POST',
        response: data,
        body: {"filter":{"family":["Lesson Type"]}}
});
```

**Comment by SamShiSS** [comment] 2019-03-25 12:59
Same issue here

**Comment by jennifer-shehane** [comment] 2019-03-26 05:58
Duplicate of https://github.com/cypress-io/cypress/issues/3333

**Closed by jennifer-shehane** 2019-03-26 05:58 UTC

**Comment by cookiescrumbs** [comment] 2019-03-26 12:38
@jennifer-shehane I'm not sure that those are the same as what I'm asking

**Comment by jennifer-shehane** [comment] 2019-03-26 14:53
@cookiescrumbs 	Right, sorry, this is different than I was thinking. 

Some of this is slightly discussed in this issue https://github.com/cypress-io/cypress/issues/521 but ultimately the functionality that you want is covered in this issue: https://github.com/cypress-io/cypress/issues/387

There are likely some hacky workarounds, especially if you search our issues for graphql, but no way to officially do this through Cypress.

**Comment by jlgaustin** [comment] 2020-02-28 23:07
I don't see this in 4.1?   Am I missing something or when will this be available?

**Comment by cookiescrumbs** [comment] 2020-03-11 09:06
Is there an update on this issue?

**Comment by jennifer-shehane** [comment] 2020-03-11 11:03
This functionality has not been released. This is a duplicate issue. Please see https://github.com/cypress-io/cypress/issues/521 or https://github.com/cypress-io/cypress/issues/387 depending on your request.
