### ISSUE TITLE
Unable to retry tests while using the Cypress run mode

### ISSUE THREAD

**Issue by Reece98** [cypress-io/cypress#8434] opened 2020-08-27 15:36 UTC
### Current behavior:

Unable to get the Cypress run mode start to attempt to retry the failed tests and it stay on pending for a very long time. It work perfectly fine in Cypress open mode. And I have followed the implementation guide provided for the 5.0 update. I am unsure on how 

One thing to note is that I have upgraded from 4.0 to 5.0.

### Desired behavior:
To be able to have the Cypress run mode retry the failed tests to amount expressed in the config file.

### Test code to reproduce
```js
{
  "supportFile": "cypress/support/index.ts",
  "baseUrl": "https://XYZ",
  "viewportWidth": 1440,
  "viewportHeight": 900,
  "defaultCommandTimeout": 5000,
  "videoUploadOnPasses": false,
  "env": {
    "ELECTRON_ENABLE_LOGGING": 1
  },
  "retries": {
    "runMode": 2,
    "openMode": 3
  }
}
```

This is the only implementation I made in my suite with `cypress.json` file.

### Versions
**Cypress:** 5.0.0
**Node:** 12.15.0

**OS:** Win 10 Pro Version 2004

**Comment by jennifer-shehane** [comment] 2020-08-28 05:40
This is likely a duplicate of #8363 but it's impossible to tell without a reproducible example. Please provide a repro in that issue (or in a comment here if you are sure it's a different issue). 

Duplicate of #8363

**Closed by jennifer-shehane** 2020-08-28 05:40 UTC
