### ISSUE TITLE
Recording video on Dashboard : The run started, but never completed

### ISSUE THREAD

**Issue by okabache** [cypress-io/cypress#1282] opened 2018-02-08 17:44 UTC
After recording our tests, i will see them in the Dashboard, but strangely I have following error message!

"The run started, but never completed. This can happen when the run is cancelled from CI or when Cypress crashes during running tests.
Check your [object Object] logs for more information."

Do you have an explanation related to this issue please?
### Screenshot
![2018-02-08_18-24-39](https://user-images.githubusercontent.com/34486465/35987981-93b96554-0cfd-11e8-9973-169591d026bd.png)

![2018-02-08_18-16-38](https://user-images.githubusercontent.com/34486465/35987571-5640931a-0cfc-11e8-97e4-4fd950bfc7eb.png)

**Comment by brian-mann** [comment] 2018-02-08 17:59
This happens when you started a run but it never completed or notified the Dashboard what happened.

In your case you say:

> I see them in our Dashboard...

But I don't see anything in your Dashboard. Per your test logs, no tests log out to `stdout` so it appears nothing ever happened - no tests started.

It appears the problem is that the tests aren't running.

**Comment by jennifer-shehane** [comment] 2018-02-08 18:23
> Check your [object Object] logs for more information.

This should say "Check your Hudson logs for more information" - I'll open an issue for this in our Dashboard.

**Comment by okabache** [comment] 2018-02-08 19:49
@jennifer-shehane 
I already check logs but strangely the test does not run !

[jenkins.log](https://github.com/cypress-io/cypress/files/1708553/jenkins.log)

I think it's related to the parallelism of the tasks
![2018-02-08_20-48-19](https://user-images.githubusercontent.com/34486465/35994670-73b1159a-0d11-11e8-9f2b-24a63b1649a3.png)

**Comment by jennifer-shehane** [comment] 2019-03-01 20:33
The message in the Dashboard was fixed https://github.com/cypress-io/cypress-dashboard/issues/494

Closing the CI not running as not an issue with Cypress

**Closed by jennifer-shehane** 2019-03-01 20:33 UTC
Labels: external: dashboard
