### ISSUE TITLE
Problem with multiple requests and route / wait

### ISSUE THREAD

**Issue by ArmandoAmmar** [cypress-io/cypress#3308] opened 2019-02-03 14:56 UTC
### Current behavior:

I am using the alias of `cy.route()` and on the page there are 2 requests for the same alias. For some reason when I use the following code, it uses the data from the first request, not the second.

### Desired behavior:

I would like it to use the data of the last request and not the first one.

### Steps to reproduce: (app code and test code)

```js
it("testara a selecao de precos", () => {
  let priceValue: any = 1000000;
  let maxValue: any = 1500000;

  cy.route('POST','/v1/realestate/properties/search?token=altopedroso')
    .as('postProperties')

  cy.get(`input[ng-model="vm.filters['price_gte']"]`).type(priceValue)
  cy.get(`input[ng-model="vm.filters['price_lte']"]`).click();

  cy.wait("@postProperties")
    .then((xhr) => {
      let request: any = xhr.request.body;
      let response: any = xhr.response.body;

      response = response.body;

      testClass.propTests(response.results, request.filters, response.count);
    });

  cy.get(`input[ng-model="vm.filters['price_lte']"]`).type(maxValue);
  cy.get(`input[ng-model="vm.filters['price_gte']"]`).click();

  cy.wait("@postProperties")
    .then((xhr) => {
      let request: any = xhr.request.body;
      let response: any = xhr.response.body;

      response = response.body;
      
      console.log('response', response)
      console.log('request', request)
    });
});
```

### Versions
Cypress: 3.1.4
Chrome: 71

**Comment by paulosborne** [comment] 2019-04-08 14:21
+1

**Comment by bryantebeek** [comment] 2019-05-23 08:49
I'm having the same issues when using GraphQL as it only has one endpoint, if you've figured out a solution please let me know :)

**Comment by prashantabellad** [comment] 2019-05-27 10:35
Any update on this?

**Comment by vladferix** [comment] 2019-05-31 11:36
I am having the same trouble. Any update on this?

**Comment by rhday74** [comment] 2019-05-31 13:26
yep same here with v3.3.1.  Noticed it with the same structure described by the original poster of this issue and also with something like:

`cy.wait(@someApiCall).then(() => {
     // do some stuff

     cy.wait(@someApiCall.then(....

});`

really strange side note: If I have Chrome Dev Tools open on the Chromium instance launched by Cypress it will behave as expected.  The two calls act independently.  If dev tools is closed, I 100% consistently get the behavior described in this issue

**Comment by devniel** [comment] 2019-06-09 05:25
Same issue, with graphql, in my case some queries are running successfully (response 200 on network tab) before `wait` is even created. The network tab shows 10 successfully request, but `wait` is hanging on for the 4th one as if the request's never been invoked when it's already done behind.

**Comment by RoryH** [comment] 2019-08-08 10:25
@rhday74 Regarding your comment:

> really strange side note: If I have Chrome Dev Tools open on the Chromium instance launched by Cypress it will behave as expected. The two calls act independently. If dev tools is closed, I 100% consistently get the behavior described in this issue

Is it possible you have "disable cache" checked in the network tab? This might be the difference.

**Comment by DanielStoica85** [comment] 2019-11-13 13:42
I just encountered the same issue.

**Comment by prashantabellad** [comment] 2019-11-13 14:08
I found a solution where in you create multiple aliases for the same route

eg - cy.route('GET', '/request').as('req1')
  cy.wait('@req1)
cy.route('GET', '/request').as('req2')
  cy.wait('@req1)
cy.route('GET', '/request').as('req3')
  cy.wait('@req1)

**Comment by DanielStoica85** [comment] 2020-01-13 11:11
The above solution does not work for me. Any chance of getting this fixed? Or maybe there is another workaround?

**Comment by Undistraction** [comment] 2020-01-14 13:34
This is a pretty nasty bug. 

The workaround is to redefine the same route with a different alias and use that to wait: 
```
cy.route('GET', '/route').as('r1')
cy.wait('@req1)
cy.route('GET', '/route').as('r2')
cy.wait('@req2)
```

**Comment by darrendahl** [comment] 2020-03-17 14:02
Above doesn't seem to work for glob routes:

`cy.route('GET', '/route/**').as('r1')
cy.wait('@r1)
cy.route('GET', '/route/**').as('r2')
cy.wait('@r2)`

**Comment by felquis** [comment] 2020-04-09 17:55
I ran into a similar situation today, but all I did was...

```js
cy.wait('@loadingRequest', { requestTimeout: 60000 }).its('status').should('eq', 200)
cy.wait('@loadingRequest', { requestTimeout: 60000 }).its('status').should('eq', 200)
```

This is the closest doc I could find about it https://docs.cypress.io/api/commands/wait.html#Nesting

------

I guess, in the original issue description, I would make this line return a promise.

```js
testClass.propTests(response.results, request.filters, response.count);
```

**Comment by chdeliens** [comment] 2020-04-09 20:21
I think you can now use `cy.wait('@postProperties.2').then((xhr) => { ... })` to wait and access data of the second call to that alias. It's an undocumented feature.

Also, cf. [opened ticket on this topic](https://github.com/cypress-io/cypress-documentation/issues/1573)

Hope this helps!!!

**Comment by ck-primitybio** [comment] 2020-05-05 23:25
This works for me

cy.wait("@Request1");
cy.wait("@Request2");
cy.wait(0);
cy.wait("@Request2");

**Comment by naimkhalifa** [comment] 2020-06-04 09:42
@chdeliens What you are referencing doesn't seem to work as expected. From what I've tried, I could use cy.wait('@postProperties.50').then(() => { ... }) . I would land on then(...) directly. No matter if there's really 50 calls or if that number of responses is reached for given alias.

**Comment by rybkowskigrzegorz** [comment] 2020-10-28 14:42
any chance on update here? I'm approaching the same issue in which it's impossible to rename alias, all post are running at the same time so for `*2` it fails.

```
    cy.wait('@generatedImages1').then(handler)
    cy.route('POST', '**/images/offer/generated').as('generatedImages2')
    cy.wait('@generatedImages2').then(handler)
    cy.route('POST', '**/images/offer/generated').as('generatedImages3')
    cy.wait('@generatedImages3').then(handler)
    cy.route('POST', '**/images/offer/generated').as('generatedImages4')
    cy.wait('@generatedImages4').then(handler)
    cy.route('POST', '**/images/offer/generated').as('generatedImages5')
    cy.wait('@generatedImages5').then(handler)
```

+ it just feels bad, looks like ugly workaround

**Comment by Stianhn** [comment] 2021-02-15 17:00
Still no update?

**Comment by bahmutov** [comment] 2021-02-15 19:00
I would love to see a reproducible example, but would also suggest trying using the new command [cy.intercept](https://on.cypress.io/intercept)

- if the example is simple to set up, you can use https://github.com/cypress-io/cypress-test-tiny repo
- alternatively, you can fork https://github.com/cypress-io/cypress-example-recipes There is the full folder with servers in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept that you could use as the basis

Having a reproducible example is the key to resolving this issue

**Comment by jennifer-shehane** [comment] 2021-04-29 17:55
`cy.route()` is deprecated and will no longer be maintained. 

Please try the examples that were failing using our new `cy.intercept()` command. 

If you're encountering a bug using `cy.intercept()`, please open a new issue with a reproducible example. Thanks.

**Closed by jennifer-shehane** 2021-04-29 17:55 UTC
Labels: stage: needs information
