### ISSUE TITLE
Sometimes, cy.route is not working in headless mode. 

### ISSUE THREAD

**Issue by predictiveXu** [cypress-io/cypress#2535] opened 2018-09-27 15:13 UTC
### Current behavior:

![capture1](https://user-images.githubusercontent.com/41205627/46155976-7ae30e00-c246-11e8-91ce-fa38cb342298.PNG)
![capture](https://user-images.githubusercontent.com/41205627/46155977-7ae30e00-c246-11e8-9b1f-f509a95594d1.PNG)

### Desired behavior:

When the test was running in headless mode, `cy.route` was not working sometimes. 

I put `cy.route` functions in `before()` and `beforeEach()`, but it's not working.

The first picture is screen-shot from video. 

By the way, XHR stub did work in headless but not always. 

### Versions

windows.
cypress 3.1.0

**Comment by jennifer-shehane** [comment] 2018-10-24 14:03
Hey @predictiveXu, we would really need a reproducible example to determine this as a bug. 

Most often in cases of flaky tests, we see that there is not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next assertion. So if there is any variation in the speed of the XHR requests response in interactive mode versus run mode, then there will start to be failures in one over the other - or flaky tests. 

So, for example if you had a test to check that when you click a 'Save' button that the users page refreshes with the correct content, you may write a test like so:

```js
cy.get('.name-input').type('Jennifer')
cy.get('form').contains('Save').click()
cy.get('#user- name).should('contain', 'Jennifer')
```

Each command by default will wait 4 seconds to meet it's requirements, but if the POST for the form request *sometimes* takes longer to respond than it takes for the `cy.get('#user- name).should('contain', 'Jennifer')` to run, then it will fail sometimes. Because of this, we recommend asserting on as many required steps as possible - this also helps later to isolate where the exact failure is when debugging on an actual bug. 

So, the example above would be less flaky written like this:

```js
cy.server()
cy.route('POST', 'users/*').as('updateUser')
cy.route('GET', 'users').as('getUsers')

cy.get('.name-input').type('Jennifer')
cy.get('form').contains('Save').click()
cy.wait('@updateUser').then((xhr) => {
expect(xhr.requestBody).to.have.property('name', 'Jennifer')
}
cy.url('contains', 'users/123')
cy.wait('@getUsers')
cy.get('#user- name).should('contain', 'Jennifer') 
```

Now when the last line runs, we don't have to worry about the POST or that the POST sent the right information, that the url changed and the GET's or whatever requests needed to respond - we know it's in the right state to find the content here.

**Comment by neekey** [comment] 2019-02-26 06:47
@jennifer-shehane it happens to me as well, the stub does not work when running in Electron regardless headless or not (chrome version 59), it works perfectly with `cypress open` or use `cypress run --broswer chrome` to run on my local chrome (version 71)

It seems like a chrome version issue ?

**Comment by jennifer-shehane** [comment] 2019-04-25 08:46
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 08:46 UTC
Labels: browser: electron, stage: needs information
