### ISSUE TITLE
[bug] route2 doesn't recognise request before redirect(route change)

### ISSUE THREAD

**Issue by Hulkmaster** [cypress-io/cypress#9168] opened 2020-11-11 14:35 UTC
### Description

We have login test, where after submit we wait for `post` request to go through, before going further, and with route2 there is a problem.

does not work
```js
cy.route2('POST', `.../login`).as('login');
```

works
```js
cy.server().route('POST', `.../login`).as('login');
```

```js
cy
  // fill form
  .submit()
  .wait('@login')
  // after that we check if user was pushed to correct page
```

<img width="507" alt="Screenshot 2020-11-11 at 15 27 31" src="https://user-images.githubusercontent.com/2781622/98823625-a5967d80-2432-11eb-8c02-65290a30ce31.png">

As you can see on screenshot - cypress recognises url, but does not recognise that url was completed.
Right after "submit" we do routing with vue route `route.push()` (basically browser history api `push`)

so its
- user fills form
- user submits
- we wait for 204 response from server
- user is `pushed` to user-specific page

### Versions

5.6.0

**Comment by jennifer-shehane** [comment] 2020-11-16 04:35
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by flotwig** [comment] 2020-11-16 18:21
There is currently a bug with waiting on `204` responses with route2: #8999 

This looks like a duplicate, closing

**Closed by flotwig** 2020-11-16 18:21 UTC
Labels: pkg/net-stubbing, stage: needs information
