### ISSUE TITLE
Cypress keeps crashing after opening any browser to run the Sample Test - Mac M1 PRo, Ventura 13.6.3

### ISSUE THREAD

**Issue by pabloca88** [cypress-io/cypress#28631] opened 2024-01-03 18:40 UTC
### Current behavior

When i open the spec sample test of cypress on any of the selected browsers it keeps crashing and "not responding" infinitely..
![CypressBUg](https://github.com/cypress-io/cypress/assets/12400637/09469396-375f-4dbf-9737-c8f50694148b)

### Desired behavior

Use cypress as it should

### Test code to reproduce

I dont have any code beside the sample spec test you provide

### Cypress Version

13.6.2

### Node version

21.5.0

### Operating System

13.6.3

### Debug Logs

```shell
I dont have any logs since the apps keeps crashing and ending on a "not responding" state
```

**Comment by jennifer-shehane** [comment] 2024-01-04 22:22
@pabloca88 I've never seen this. Is this your first time using Cypress? Have you been able to open Cypress before? 

You could try [clearing the cache of Cypress](https://docs.cypress.io/guides/guides/command-line#cypress-cache-clear) or the [App data](https://docs.cypress.io/guides/references/troubleshooting#Clear-App-Data). 

Our team had some weird freezing behavior recently with Chrome in general after updating, but it was always working in Cypress actually.

**Comment by jennifer-shehane** [comment] 2024-03-07 20:07
Closing since no reproducible example was provided to investigate.

**Closed as not planned by jennifer-shehane** 2024-03-07 20:07 UTC
Labels: stage: needs information
