### ISSUE TITLE
Cypress is not working with Firefox

### ISSUE THREAD

**Issue by melibe23** [cypress-io/cypress#15187] opened 2021-02-23 11:39 UTC
It is considered a 404
![image](https://user-images.githubusercontent.com/32499737/108838703-479e3800-75d4-11eb-8c1a-90a9c9c460d0.png)

it doesn't work with the GUI nor with `npm run cypress:run -- --browser firefox`

![image](https://user-images.githubusercontent.com/32499737/108838502-01e16f80-75d4-11eb-901b-5c512b94142d.png)

Firefox 85
Mac Catalina 10.15.7 (19H2)

**Comment by jennifer-shehane** [comment] 2021-02-24 01:18
Can you provide a reproducible example? Likely the issue is specific to the tests you've written and/or the application it is testing. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment] 2021-04-29 17:57
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-04-29 17:57 UTC
Labels: stage: needs information
