### ISSUE TITLE
XHR requests get aborted when running headless, in cypress based image container

### ISSUE THREAD

**Issue by DeanCivlin** [cypress-io/cypress#19482] opened 2021-12-26 16:28 UTC
### Current behavior

Cypress XHR requests get aborted when running headless, in a cypress-based image container. 

Browser: Both Electron and Chrome

After Signing in some XHR requests are sent from my app but weirdly being aborted.
I tried `cy.intercept` and `cy.sleep(miliseconds/aliases)` and nothing works.
This happens only on headless mode. locally it happens only on Chrome but when running on the container it happens both on Electron and Chrome.

Since those requests are aborted, the next step of my test is not doable and therefore the test will always fail on the container.

![image](https://user-images.githubusercontent.com/45535340/147414214-af23da9f-9715-4e49-925a-078fda91ac1f.png)

### Desired behavior

The Xhr Requests should not be aborted but finish successfully, and so is the test.

### Test code to reproduce

```describe('Test Sign-In', () => {
  before(() => {
    cy.clearLocalStorageSnapshot();
  });
  beforeEach(() => {
    cy.restoreLocalStorage();
  });
  afterEach(() => {
    cy.saveLocalStorage();
  });
  it('Test Sign In Process', () => {
    cy.visit(Cypress.config().baseUrl);
    cy.get('[data-test="signInHeader"]', { timeout: 10000 }).should(
      'be.visible'
    );
    cy.get('[data-test="emailInput"]').type(Cypress.env('USER_EMAIL'));
    cy.get('[data-test="passwordInput"]').type(Cypress.env('USER_PASSWORD'));
    cy.get('[data-test="signInBtn"]').click(); // Preform Sign-in
    cy.get('[data-test="newAnalysisHeader"]', { timeout: 25000 }).should(
      'be.visible'
    );
  });


**The Xhr requests are fired right after the // Preform Sign-in row**

### Cypress Version

9.1.1

### Other

_No response_

**Comment by sainthkh** [comment] 2021-12-28 23:48
Duplicate of #19481.

**Closed by sainthkh** 2021-12-28 23:48 UTC
