### ISSUE TITLE
Websocket ERROR with HEAD 500

### ISSUE THREAD

**Issue by Mipme** [cypress-io/cypress#1455] opened 2018-03-13 17:35 UTC
- Operating System: Mac OS X High Sierra
- Cypress Version: 2.1.0
- Browser Version: Chrome 64 / Electron 59

### Is this a Feature or Bug?
Bug

### Current behavior:
Cypress installed via npm
Cypress starting
Starting `example_spec.js`
Browser starting display blank grey page

```
Console Error: Head / 500
Browser Console Error: WebSocket connection to 'ws://localhost:50816/__socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.
```

### Desired behavior:
Work as advertised :-)

### How to reproduce:
See ### Current behavior

### Additional Info (images, stack traces, etc)
Maybe related to https://github.com/cypress-io/cypress/issues/556

**Comment by ValerieThoma** [comment] 2018-03-20 16:15
duplicate of #680 
resolved by mapping ip address to localhost

**Closed by ValerieThoma** 2018-03-20 16:15 UTC
Labels: type: duplicate

**Comment by saas2813** [comment] 2019-06-28 19:49
I got logs similar to this. The problem was that my

    /etc/hosts

file did not include a line:

    127.0.0.1 localhost
