### ISSUE TITLE
I cannot run "npx cypress open" on ubuntu

### ISSUE THREAD

**Issue by serge-eric-kalaga** [cypress-io/cypress#30169] opened 2024-09-02 15:04 UTC
### Current behavior

I'm on Ubuntu, I can't launch Cypress. 
I get this error after running the `npx cypress open` command 👇🏿👇🏿👇🏿
![Capture d’écran du 2024-09-02 15-00-29](https://github.com/user-attachments/assets/938f537d-2bd0-49f4-9dd3-62b48033e6dd)
 :

### Test code to reproduce

```
$ npx cypress open

(Cypress:22510): GLib-GIO-ERROR **: 14:51:42.210: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 24.04)
Cypress Version: 13.14.1
```

### Cypress Version

13.14.1

### Node version

v22.7.0

### Operating System

Ubuntu 24.04.1 LTS

**Comment by MikeMcC399** [comment] 2024-09-02 16:38
- This is a duplicate of https://github.com/cypress-io/cypress/issues/30160

**Comment by serge-eric-kalaga** [comment] 2024-09-03 09:41
> * This is a duplicate of [Cannot start cypress on Ubuntu #30160](https://github.com/cypress-io/cypress/issues/30160)

I had to revert to an earlier version of Cypress for it to work. Version 7.6.0

**Comment by MikeMcC399** [comment] 2024-09-03 09:46
@serge-eric-kalaga 

> I had to revert to an earlier version of Cypress for it to work. Version 7.6.0

Cypress `7.6.0` is a very old and legacy version. Have you considered trying Cypress `13.13.3` instead?

**Comment by serge-eric-kalaga** [comment] 2024-09-03 09:50
> @serge-eric-kalaga
> 
> > I had to revert to an earlier version of Cypress for it to work. Version 7.6.0
> 
> Cypress `7.6.0` is a very old and legacy version. Have you considered trying Cypress `13.13.3` instead?

No. Maybe I'll try with this version and I'll get back to you

**Comment by serge-eric-kalaga** [comment] 2024-09-03 10:18
> > @serge-eric-kalaga
> > > I had to revert to an earlier version of Cypress for it to work. Version 7.6.0
> > 
> > 
> > Cypress `7.6.0` is a very old and legacy version. Have you considered trying Cypress `13.13.3` instead?
> 
> No. Maybe I'll try with this version and I'll get back to you

 13.13.3 Version works great.

**Comment by serge-eric-kalaga** [comment] 2024-09-03 10:18
> @serge-eric-kalaga
> 
> > I had to revert to an earlier version of Cypress for it to work. Version 7.6.0
> 
> Cypress `7.6.0` is a very old and legacy version. Have you considered trying Cypress `13.13.3` instead?

13.13.3 Version works great.

**Closed as completed** 2024-09-03 10:37 UTC
