### ISSUE TITLE
Screenshot different betweem CI and Local

### ISSUE THREAD

**Issue by mmonteiroc** [cypress-io/cypress#22804] opened 2022-07-15 09:26 UTC
### Current behavior

Trying to do some visual testing, we take screenshots of the UI with "cy.screenshot".
The screenshots taken by the tests are different in the CI than in Local.

Our code that take the screenshots is similar to the following one:

```
cy.get('#card-selector').matchImage('card-image');
```
Where  `matchImage` is a custom comand which does the following:
```
Cypress.Commands.add('matchImage', { prevSubject: true }, (subject, fileName: string) => {
 cy.wrap(subject)
      .first()
      .screenshot(fileName, {
        capture: 'viewport',
        overwrite: true
      })
      .then(() => {
        // Whatever logic we do aftwewards
      });
});
```

If you see the code above, and following official documentation, we are taking the screenshot from a single element, the "card-selector" element.

In local (headless / non headless) works well, and generates the image as expected.
When we run in the CI, the screenshot shifts to the top for a bit, and includes / excludes parts non expected.

I can share the expected / actual image if needed, but for that I would need an email of any person in cypress (email@cypress) so that is not available for everyone.

ENV in local:
![image](https://user-images.githubusercontent.com/28816737/179195103-3b690587-d5bc-49a7-8e68-6a4a8c4c7b15.png)

Env in CI
![image](https://user-images.githubusercontent.com/28816737/179195174-c334f124-1e54-49b2-ab9b-93816ed32f7c.png)

### Desired behavior

That the screenshots are the same in local than in CI 

### Test code to reproduce

Test code mentioned above in the description

### Cypress Version

10.2.0

**Comment by mmonteiroc** [comment] 2022-07-15 09:34
in the "setupNodeEvents" we have the following code which you guys provided us long time ago to fix the window size, so that always the screenshots are in the same "env" 


```
on('before:browser:launch', (browser, options) => {
  return useFixedBrowserLaunchSize(browser, options);
});
....
.....
function useFixedBrowserLaunchSize(browser, options) {
  if (browser.family === 'firefox') {
    // (height must account for firefox url bar, which we can only shrink to 1px)
    options.args.push('-width', '1280', '-height', '720');
  } else if (browser.name === 'electron') {
    options.preferences.width = 1280;
    options.preferences.height = 720;
  } else if (browser.family === 'chromium') {
    options.args.push('--window-size=1280,720');
  }
  return options;
}

```

**Comment by chrisbreiding** [comment] 2022-07-19 14:09
I'm not able to reproduce the issue with the code provided. 

Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed** 2022-07-26 18:10 UTC
Labels: stage: awaiting response
