### ISSUE TITLE
Secure coding is not enabled for restorable state (Sonoma)

### ISSUE THREAD

**Issue by pavinduLakshan** [cypress-io/cypress#28158] opened 2023-10-27 10:26 UTC
### Current behavior

Seeing the following warning when running the Cypress in headed mode in Chrome 118.

```
2023-10-27 15:49:35.592 Cypress[5949:37879] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

### Desired behavior

Cypress should not print these kind of warnings

### Test code to reproduce

Running any Cypress project on Mac OS 14 shows this warning

### Cypress Version

12.5.1

### Node version

v16.17.0

### Operating System

MacOS 14.1

**Comment by PabloGarcia10** [comment] 2023-10-31 15:09
Did you have any success? I'm with the same problem here..

**Comment by jennifer-shehane** [comment] 2023-10-31 16:36
@pavinduLakshan @PabloGarciaQATesting Is this causing any changes to how your tests or run or impacting the run at all?

**Comment by PabloGarcia10** [comment] 2023-10-31 16:44
@jennifer-shehane Yes it is, I cannot run the tests or open even open cypress interface

**Comment by pavinduLakshan** [comment] 2023-11-01 03:08
In my case, it had no effect on the issue I was facing. My issue was related to a misconfigured host mapping.

**Comment by jennifer-shehane** [comment] 2023-11-02 20:09
Can anyone provide a repo to run where this warning is showing? It's likely specific to something involved in the repo since this isn't occuring for everyone.

**Comment by glyph** [comment] 2023-11-03 05:29
@jennifer-shehane I ran across this while looking at a completely different issue https://github.com/beeware/toga/issues/2188 so I thought it might be useful to note here that this is probably at least Sonoma-specific

**Comment by matt384** [comment] 2023-11-03 18:07
Facing this issues as well, cypress was working great and now completely blocks. I tried clearing Library/Caches/Cypress... but it didn't work.

MacOS 14.0 @glyph  I do believe this is sonoma specific. An unrelated app with the same issue [here](https://discussions.apple.com/thread/255171260)

**Comment by ericreinheart** [comment] 2023-11-05 23:47
Ran into this error as well on M2 Pro / MacOS 14.1 after moving Cypress into its own (sub-)working directory. Turns out I forgot to move the `cypress.config.ts` with it. After doing so everything worked fine.

I am aware that in some of the above cases, this error seemed to come up without changing anything about their codebase prior. But maybe this information helps other Mac users who've made the same mistake as me, as the error message is identical... :)

**Comment by mrlonis** [comment] 2023-11-14 04:21
Here's an app that reproduces this: https://github.com/mrlonis/example-angular-app.

I am on Intel Mac-OS 14.1.1

**Comment by czuniga9** [comment] 2023-11-16 21:04
I get this warning but it doesn't stop cypress from working. [Here's a thread](https://stackoverflow.com/a/77320845) with details about the warning.

**Comment by obecker-csdisco** [comment] 2023-11-20 23:59
Have the same problem, 'Cypress open' doesn't connect to Chrome anymore.

Sonoma 14.1

`Cypress run` still works  and so does `Cypess run --headed` (using electron)

but 

`Cypess run --headed --no-exit --browser chrome`

does not (same issue as `Cypress open`)

**Comment by obecker-csdisco** [comment] 2023-11-21 00:07
Running with debug enabled attached output (https://github.com/cypress-io/cypress/files/13420424/debug.log))

**Comment by jennifer-shehane** [comment] 2023-11-28 20:07
@obecker-csdisco I'm not seeing the "Secure coding is not enabled for restorable state" message anywhere in your debug logs. Are you describing this same issue?

**Comment by nbouvrette** [comment] 2023-12-02 18:12
I'm having the same issue on Cypress `13.6.0` and Node `v18.18.2`. I'm also on Sonoma - to reproduce: 

1) clone https://github.com/Avansai/next-multilingual
2) `npm install`
3) `npm run test`

**Comment by obecker-csdisco** [comment] 2023-12-04 16:34
> @obecker-csdisco I'm not seeing the "Secure coding is not enabled for restorable state" message anywhere in your debug logs. Are you describing this same issue?

Sorry, doesn't show up in the logs but in terminal.

```
$ cypress open
2023-12-04 08:33:25.124 Cypress[11676:59495] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

**Comment by obecker-csdisco** [comment] 2023-12-20 16:18
Any update on this Issue ?

**Comment by jennifer-shehane** [comment] 2023-12-28 22:16
I imagine this is coming from Electron, they implemented a fix for this, but it doesn't look like they're backporting it to older versions for some reason: https://github.com/electron/electron/pull/40296

We're working on an Electron update, but were not going to get up to Electron 29 quite yet.

**Comment by jennifer-shehane** [comment] 2024-01-02 15:09
I just want to note more clearly, as did the [engineer at Electron](https://github.com/electron/electron/pull/40296#issuecomment-1871565673), that this log message is a **warning** and can be ignored.

If you are encountering an error, early exit, hanging or unusual failures after this warning is displayed - that is not indicating that this warning message is the **cause** of the abnormal behavior in cypress. If you're encountering these situations, please open a new issue with full debug logs, a description of the problem, and a way to reproduce it and we can investigate if there is a bug causing the test run to act abnormally

**Comment by obecker-csdisco** [comment] 2024-01-03 23:48
Not using Electron, but Chrome. Unfortunately I have no simple way to reproduce this.

My best "guess" at this point is that it is env related, as I have engineers using the same repo and being able to run cypress open successfully with chrome. Same version of MacOS, Chrome and Node

**Comment by nnaydenow** [comment] 2024-06-12 11:02
Same here:
macOS:  Sonoma - version 14.5
Node: v20.11.0
Cypress: 13.6.4

I've noticed that the issue appears only in Chrome and Edge but it's a problem because we need to run our tests on Chrome browser.

**Closed as completed** 2024-11-21 17:58 UTC
Labels: type: bug, OS: mac, stage: needs information
