### ISSUE TITLE
cy.writeFile timesout but also runs writeFile beyond the timeout.

### ISSUE THREAD

**Issue by SDESkowronski** [cypress-io/cypress#3350] opened 2019-02-06 20:23 UTC
### Current behavior:
The documentation says it is technically possible for `cy.writeFile` to timeout but it shouldn't, however, it did for me today. I know it was the `cy.writeFile` that timedout because it is the only cy.Command in my `aftereach` hook.

#### The Error Output:
```
  20) EditAndBranching
       "after each" hook for "Tag And Frog":
     Error: Cypress command timeout of '4000ms' exceeded.

Because this error occurred during a 'after each' hook we are skipping all of the remaining tests.
      at http://localhost:5050/__cypress/runner/cypress_runner.js:66264:25
```

### Desired behavior:
I think Cypress should provide a way to override the timeout or fix it so it can't timeout.

I also think Cypress should not stop running the remaining tests when one fails in the `aftereach` hook. That is a harsh punishment for an intermittent failure. In fact that also is a good case for not failing all tests in the `aftereach` since one failure does not necessarily mean they all will fail. Perhaps this needs a rethink as well. 

### Steps to reproduce: (app code and test code)

`"Issues without reproducible steps will get closed."` -- How am I supposed to give you code to reproduce this? Do I have to write some OS hook to intercept the writeFile command and make it take longer than 4 seconds?

Sorry but I don't have the time to work up some sort of repro steps...this requirement on obvious flaws is an impedance to filing a bug. I've reported the bug, if you all want to just close and do nothing then so be it.

### Versions

Cypress package version: 3.0.3
Cypress binary version: 3.0.3
OS Name:	Microsoft Windows 10 Enterprise
OS Version:	10.0.17763 Build 17763
Browser: Electron 59 (headless)

**Comment by jennifer-shehane** [comment] 2019-02-07 10:46
Was able to reproduce from code below:

```js
it('writes until timeout', () => {
  cy.writeFile('./fixtures/my-long-file.txt', Cypress._.times(900000, '😈'))
})
```

<img width="561" alt="screen shot 2019-02-07 at 5 16 04 pm" src="https://user-images.githubusercontent.com/1271364/52406434-155c3380-2afc-11e9-8423-3cdfac260d84.png">


This `write:file` event actually seems to run forever:
<img width="1411" alt="screen shot 2019-02-07 at 5 11 20 pm" src="https://user-images.githubusercontent.com/1271364/52406301-c3b3a900-2afb-11e9-9767-faa7cae8cbf9.png">

The `writeFile` code can be found here: 

https://github.com/cypress-io/cypress/blob/renovate/develop/packages/driver/src/cy/commands/files.coffee#L66

**Comment by SDESkowronski** [comment] 2019-02-07 16:57
Thanks Jennifer, I'm glad you were able to come up with repro steps.

**Comment by JoshMcAloone** [comment] 2020-03-16 21:36
Hi @jennifer-shehane do you know if this issue was ever fixed or is planned to be fixed? We are facing a lot of random timeouts with cy.writeFile when running tests on Azure build agents. The timeout occurs in the before all or after all hook and the remaining tests all fail.

**Comment by lisophorm** [comment] 2020-04-15 15:41
Hi,
I am having the same issue and this is becoming a major blocker. Is this going to be solved?

**Comment by JoshMcAloone** [comment] 2020-04-15 15:56
> Hi,
> I am having the same issue and this is becoming a major blocker. Is this going to be solved? @jennifer-shehane

@lisophorm I found a workaround for this issue which I thought I would share in case it helps.

I stopped using cy.writeFile and instead used fs.writeFileSync.

Firstly I added a task in index.js like:
```
const fs = require('fs');

module.exports = (on, config) => {
        on('task', {
                writeFile ({ filename, data }) {
                    fs.writeFileSync(filename, data);
                    return null;
                }
            })
}
```

Then in my before/after all hooks in the cypress tests I now just use the following to write to the files:

`cy.task('writeFile', { filename: <some filename>, data: <some data> });`

This works well and the cypress tests are stable and run very consistently on Azure build agents. Hope this helps whilst we wait for this issue to be fixed.

**Comment by amitguptagwl** [comment] 2020-09-25 07:27
Any update on this?

**Comment by amitguptagwl** [comment] 2020-09-25 09:19
I tried like this and it worked for me
```js
it('writes until timeout', () => {
  cy.then( () => cy.writeFile('./fixtures/my-long-file.txt', Cypress._.times(900000, '😈')) );
})
```

**Comment by jennifer-shehane** [comment] 2020-12-15 08:28
This issue is still open, so no work has been done on it. We are welcome to PRs to fix the issue.

**Comment by mjhenkes** [comment] 2021-10-21 21:39
A couple of notes here: 

To recreate this issue I added an extra zero to @jennifer-shehane 's test to recreate the issue.

```javascript
it('writes until timeout', () => {
  cy.writeFile('./fixtures/my-long-file.txt', Cypress._.times(9000000, '😈'))
})
```

The websocket request the server to write files[^1] times out after 4000 MS, but the actual fs writeFile operation that is kicked off in the server is never canceled[^2]. This actually seems to lead to some unresponsiveness in the cypress app ui. 

Fix Proposal: 
* Update `cy.writeFile` to have a configurable timeout option that would apply to both the websocket and the write operation in the server.
* Update the server to read and honor the timeout. There is an option[^3] to do with with the abortController but it's only available experimentally in node 14, so there is some digging to do there.

[^1]: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/files.ts#L127
[^2]: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/files.js#L29
[^3]: https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_writefile_file_data_options_callback

**Comment by tbiethman** [comment] 2021-11-23 21:34
Summarizing the plan of action here:

1. We will be introducing a timeout option to readFile/writeFile commands and setting a sensible default (larger than the default timeout of 4 seconds).
2. We will introduce better error handling for scenarios where large reads/writes were silently failing and causing the reporter to hang (as shown in the investigations above). We will also investigate increasing our internal transmission limits to mitigate this further.
3. Failures within afterEach and other hooks are expected to fail the tests within that context; if the setup/teardown has failed in some way, it is hard to ensure the validity of subsequent test executions. We will not be making changes to this behavior with this work. However, as far as writeFile is concerned, the changes we are making should significantly reduce the amount of failures occurring due to large file sizes.

**Closed** 2021-12-06 21:31 UTC
Labels: type: bug, type: enhancement, pkg/driver, pkg/server, first-timers-only, stage: needs review
