### ISSUE TITLE
Tests randomly finish early and passes

### ISSUE THREAD

**Issue by iainxt** [cypress-io/cypress#9102] opened 2020-11-05 04:13 UTC
### Current behavior
From time to time I noticed that my test finishes early and still passes. This means it doesn't run half the test.

Example of it exiting early after 63 commands
![image](https://user-images.githubusercontent.com/146976/98196918-8652a880-1f79-11eb-8364-75d7a8906a2b.png)

Example of it continuing beyond 63 commands
![image](https://user-images.githubusercontent.com/146976/98196521-6ff81d00-1f78-11eb-9f32-ab20c445edbb.png)

The relevant bit of code is:
```js
cy.get('[data-cy="GraphAutoSave"]').click();
cy.get('[data-cy=GraphAutoSave]').contains(0, {timeout:10000});
const reg = new RegExp("^"+0+"$");
cy.contains('[data-cy="pendingStoreDbNodeCount"]', reg);
// Eletron appears to lose data
cy.wait(200);
```

I do not see any errors, and there is nothing on the console. This occurs once in every 20-50 runs.

### Desired behavior
The test to run all commands, or to fail if it does not.

### Test code to reproduce
I'll keep an eye on when this occurs to see if it is always during a contains command passing an int.

```js
cy.get('[data-cy=GraphAutoSave]').contains(0, {timeout:10000});
```

### Versions

Windows, Chrome, Cypress 5.5, when running with `cypress open`

I feel this has started in the last few months. I recently upgraded to 5.5 and its still occuring.

**Comment by jennifer-shehane** [comment] 2020-11-05 10:56
`.contains()` doesn't accept a number as its first argument. This should be a valid selector. What are you trying to test for using this signature? `.contains(0, 1000)`. It could be doing something unexpected because this is an incorrect use of the API.

When I try to run this `.contains()` signature, Cypress encounters an error. Maybe in your run this error is not being displayed properly and instead freezing?

A fully reproducible example would be most helpful in us tracking down why this isn't failing for you.

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('div').contains(0, 10000)
})
```

<img width="563" alt="Screen Shot 2020-11-05 at 4 58 49 PM" src="https://user-images.githubusercontent.com/1271364/98229411-421ad480-1f88-11eb-86f7-45caf6c3c42a.png">

**Comment by iainxt** [comment] 2020-11-05 22:49
While inlining the code I made a mistake so the example above should read:

```js
        it('test', () => {
            cy.visit('/');
            const TIMEOUT_LONG = {timeout: 30000};
            cy.get('div').contains(0, TIMEOUT_LONG);
            cy.log('Finished');
        })
```

The above code is working, I'll keep on eye on it and when it occurs again see if its the same place. Being intermittent its hard to reproduce reliably. I was partly hoping there may be a known issue or this has been seen before.

**Comment by iainxt** [comment] 2020-11-05 23:08
It just happened again, different code but a stacktrace!!

```
cypress_runner.js:6449 
Unhandled rejection TypeError: Cannot read property 'get' of null
  at validateType (http://localhost:3000/__cypress/runner/cypress_runner.js:160993:22)  
  at Object.ensureSubjectByType (http://localhost:3000/__cypress/runner/cypress_runner.js:161040:9)   
  at pushSubjectAndValidate (http://localhost:3000/__cypress/runner/cypress_runner.js:169553:15)   
  at Context.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:169890:18)   
at http://localhost:3000/__cypress/runner/cypress_runner.js:169315:15From previous event:
   at runCommand (http://localhost:3000/__cypress/runner/cypress_runner.js:169294:8)
   at next (http://localhost:3000/__cypress/runner/cypress_runner.js:169440:14)From previous event:
   at Promise.catch.err.name (http://localhost:3000/__cypress/runner/cypress_runner.js:169481:37)From previous event:
   at run (http://localhost:3000/__cypress/runner/cypress_runner.js:169474:21)
   at $Cy.cy.<computed> [as log] (http://localhost:3000/__cypress/runner/cypress_runner.js:169931:11)
   at Context.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:169891:21)
   at http://localhost:3000/__cypress/runner/cypress_runner.js:169315:15From previous event:
   at runCommand (http://localhost:3000/__cypress/runner/cypress_runner.js:169294:8)
   at next (http://localhost:3000/__cypress/runner/cypress_runner.js:169440:14)
   at http://localhost:3000/__cypress/runner/cypress_runner.js:169468:16From previous event:
   at next (http://localhost:3000/__cypress/runner/cypress_runner.js:169440:34)From previous event:
   at Promise.catch.err.name (http://localhost:3000/__cypress/runner/cypress_runner.js:169481:37)From previous event:
   at run (http://localhost:3000/__cypress/runner/cypress_runner.js:169474:21)
   at $Cy.cy.<computed> [as get] (http://localhost:3000/__cypress/runner/cypress_runner.js:169931:11)
   at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:170155:21)
   at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:104227:21)
   at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:104214:7)
   at http://localhost:3000/__cypress/runner/cypress_runner.js:175754:28From previous event:
   at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:175742:17)
   at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:166291:28)
   at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:174128:13)
   at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:104886:10)
   at http://localhost:3000/__cypress/runner/cypress_runner.js:105012:12
   at next (http://localhost:3000/__cypress/runner/cypress_runner.js:104795:14)
   at http://localhost:3000/__cypress/runner/cypress_runner.js:104805:7
   at next (http://localhost:3000/__cypress/runner/cypress_runner.js:104707:14)
   at http://localhost:3000/__cypress/runner/cypress_runner.js:104773:5
   at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:98699:27)
```

And the code:
```
cy.get('[data-cy-label=Name]').clear().type("Original Title");
<--- STOPPED HERE --->
cy.get('[role="main"]').XXX
```

XXX is a custom command. This was occuring before I wrote the custom command so my guess is its something about the app under test.

**Comment by individual-it** [comment] 2021-01-05 09:53
we also have this issue, currently working on cypress 5.1 and updating to 6.1 but the issue seem not have gone away

**Comment by jennifer-shehane** [comment] 2021-01-07 10:13
@iainxt The code is throwing here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/ensures.js#L25:L25

We'll really need a reproducible example in order to investigate further.

**Comment by iainxt** [comment] 2021-01-08 03:53
If it becomes more of an issue I'll invest the time. 

For the moment my gut says its due to using react with asynch code that causes the DOM to re-render randomly.

Regardless it would nice if you could include an assert that the test hasn't died, perhaps the stacktrace I posted will assist in reproducing a dieing test that passes.

**Comment by jennifer-shehane** [comment] 2021-02-27 14:21
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-27 14:21 UTC
Labels: stage: needs information

**Comment by brandon-mork** [comment] 2021-05-07 17:20
This has occurred for me if my `it` callback method is marked `async`.

Symptoms in my use case:
* Running a full `.spec.js` file often resulted in tests finish early and pass (first 1-4 `cy.get` type statements execute, rest of test never executed.)
* Running a single test using `it.only` my `async` tests would fully execute.

Fix:
* Removing `async` from my tests fixed my issue.

Code before:
`it.('test name`, async () => { ... })`
Code after:
`it.('test name`, () => { ... })`

**Comment by anatolygusakovsky1** [comment] 2021-08-17 11:51
@brandon-mork exactly the same happens with me. If there are any way to use async and avoid early tests finish and pass ?
Would be really helpful!

**Comment by AlexDaniel** [comment] 2021-10-19 10:09
This happens all the time to me even without async. Hmmm.

**Comment by Nervniyak** [comment] 2021-11-22 10:51
Have the same issue of test randomly finishing early. But it doesn't seem to occur when I select test to run in Cypress UI. But it occurs randomly when I Ctrl+S my changes and Cypress automatically restarts test in Chrome test window. (not sure if Run All Tests [R] behaves the same, didn't see it occur with it yet)

**Comment by AlexDaniel** [comment] 2021-11-22 10:54
@Nervniyak perhaps you're right! I also don't remember the tests not running on the first run, only after hot reloading.

**Comment by np104098** [comment] 2021-11-22 21:58
I was facing the same issue when trying to get a value string from Slack within a function and wrap that number into String and use it later on. Today, I have faced it a few times but not as frequent. Its a hit and miss really. Anyone else have any recommendations?

**Comment by annisokaay** [comment] 2021-12-02 12:22
Can relate to that, usually happens when i work with specs that have cy.request. Only occurs with `cypress open`.

**Comment by JuanMaciel** [comment] 2022-02-02 21:37
> 

It also seems like it's happening to me with tests that use cy.request. Any recommendations?

**Comment by ritika13singh** [comment] 2022-03-13 16:27
Is there any clarity on this issue? I am facing this issue randomly after 'n' number of executions, no pattern is observed when execution just stops in the middle of tests, without any error. It has been random but this is occurring more frequently now. Some support from cypress would be appreciated.

**Comment by austinbradshaw** [comment] 2022-09-02 17:22
Same here! We're using cy.request everywhere to log in/generate a session at the beginning of each test. Gonna keep researching - I'll report back here if I find anything

**Comment by rrokkam** [comment] 2022-09-08 17:20
I'm running into the same issue for the same reason as @austinbradshaw. 

It's been mentioned that this issue occurs when `cy.request` is used. Has anyone found a workaround to replace `cy.request` with other APIs? What did you use instead of `cy.request`?

**Comment by gigamesh** [comment] 2022-10-25 21:50
I was experiencing this in a test that needs to make an async call to a local service at the start of the test. This solution worked for me:

```
cy.wrap(null).then(() => myAsyncFunction());
```

https://stackoverflow.com/a/68178922/9202501
