### ISSUE TITLE
cy.visit() on a specific URL ends the test prematurely

### ISSUE THREAD

**Issue by nadvolod** [cypress-io/cypress#23839] opened 2022-09-15 12:33 UTC
### Current behavior

cy.visit('https://who--spmstage.sandbox.lightning.force.com/lightning/page/home') with a `baseUrl` is ending the test execution prematurely without any feedback. The spec starts to run, then stops, and comes back to the Specs screen with no extra information.
I tried the same thing with `google.com` and it works just fine. Seems as though something about this URL is causing a weird behavior.

### Desired behavior

In this situation, Cypress should finish execution and provide some helpful logs to let me know what to do and why this URL isn't opening.

### Test code to reproduce

[cypress.zip](https://github.com/cypress-io/cypress/files/9575211/cypress.zip)
Attaching a repo to reproduce this issue.

### Cypress Version

10.8.0

### Node version

16.15.1

### Operating System

macOS 12.5

**Comment by nagash77** [comment] 2022-09-15 18:44
@nadvolod Due to security concerns we cannot open zip files locally.  Can you please link to a git repo where the problem is reproducible or include the test code inline?

**Comment by nadvolod** [comment] 2022-09-15 18:51
@nagash77 see if this is helpful? Lemme know if you need more files included
https://gist.github.com/nadvolod/324540bbbaa0aa3336351207edde0232

**Comment by nadvolod** [comment] 2022-09-16 11:18
Hello, any thoughts/updates?

**Comment by nagash77** [comment] 2022-09-16 18:11
This is great.  We will have a developer take a look.  Thanks for the quick response!

**Comment by chrisbreiding** [comment] 2022-09-19 12:30
I was able to reproduce the issue with the given code. That will help a lot with debugging this, so thanks for that!

I'm going to route this to a team to look at.

**Comment by nadvolod** [comment] 2022-09-29 12:04
@chrisbreiding, any updates on this? We're blocked

**Comment by chrisbreiding** [comment] 2022-09-29 13:49
I think there's frame-busting causing the redirect back to the specs list. Can you try setting `experimentalModifyObstructiveThirdPartyCode: true` in your cypress config? It goes a bit further than the standard `modifyObstructiveCode` option to prevent frame-busting. I tried it in the reproduction you provided and it stopped the redirect from happening.

**Comment by nadvolod** [comment] 2022-10-07 19:13
that works, thanks os much

**Comment by chrisbreiding** [comment] 2022-10-07 19:18
Great! Thanks for following up. I'm going to close this as resolved, since using `experimentalModifyObstructiveThirdPartyCode` is our recommended way to avoid such frame-busting issues.

**Closed as completed by chrisbreiding** 2022-10-07 19:18 UTC
Labels: type: bug, topic: visit
