### ISSUE TITLE
Position the search bar at the top in Cypress Test Runner

### ISSUE THREAD

**Issue by gmkumar08** [cypress-io/cypress#5369] opened 2019-10-15 13:10 UTC
#### Search bar in Cypress Test Runner scrolls up when I scroll down the tests making it mandatory to scroll to the top again if I have to search for any tests once I'm at the bottom or somewhere in between. The same applies to the "Run all specs" option too.

![image](https://user-images.githubusercontent.com/46545923/66833833-265a2000-ef7a-11e9-9add-8d0fe4daed71.png)

#### Position the Search bar at the top even when I scroll down the tests.
![image](https://user-images.githubusercontent.com/46545923/66834128-b730fb80-ef7a-11e9-81a2-e10a36998a68.png)

**Comment by jennifer-shehane** [comment] 2019-10-15 14:53
@gmkumar08 You're in luck because this has already made it's way into the next pre-release version of Cypress (3.5.0). Closing as duplicate of https://github.com/cypress-io/cypress/issues/4904

**Closed by jennifer-shehane** 2019-10-15 14:53 UTC

**Comment by gmkumar08** [comment] 2019-10-15 15:07
@jennifer-shehane that's great news. I couldn't find the original issue and hence have created a new one. Sorry for the trouble. I can't wait to try out the next release. Keep up the good work :)
