### ISSUE TITLE
In CI, cypress install should clear old cached versions

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1840] opened 2018-05-31 16:40 UTC
**Proposal:** Prevents large buildup of `~/.cache` with obsolete versions. Should only happen in CI because locally users could have multiple versions installed on the system in other projects.

**complications:**
- different cypress versions across branches, can't clear out other versions...

**Comment by zeptonaut** [comment] 2020-07-17 13:19
We're also running into this on my team's CircleCI builds. I noticed that our frontend dependency cache had gotten up to almost ~1GB (zipped) recently and was confused about why. I opened up our /Cypress folder and found:

![image](https://user-images.githubusercontent.com/1407397/87789676-6bfb9000-c80d-11ea-8374-25b3d9331e6f.png)

I see the `cypress cache clear` command linked above, but I don't think it's directly useful for addressing this problem. Ideally, we want to remove all versions of Cypress _except_ the one currently in use, whereas `cypress cache clear` deletes _all_ versions of Cypress. I think a `cypress cache clear unused` command is probably more useful.

**Comment by jennifer-shehane** [comment] 2020-07-17 13:41
Yeah, I've also wanted a way to clear specific versions in the cache instead of **all** cached versions.

**Comment by zeptonaut** [comment] 2020-07-17 13:43
Yep, I could definitely see that being useful too!

Given that `cypress version` already knows the version ([it looks like through `util.pkgVersion()`](https://github.com/cypress-io/cypress/blob/3b6514399dec4cd53c5e1500f3aa49c7f5608519/cli/lib/tasks/state.js#L53)), creating a loop to iterate through all other versions in the cache directory and delete them doesn't seem too farfetched.

**Comment by zeptonaut** [comment] 2020-07-17 15:06
For anyone else encountering this: my hacky solution is to run a bash script in between the time that we load our node modules (and Cypress cache) from our CircleCI cache and the time that we save the new cache. The bash script wipes the cache if multiple versions of Cypress are detected and reinstalls Cypress, which takes about ~30s or so.

```sh
#!/usr/bin/env bash
set -e

# If left unchecked, old versions of Cypress will accumulate in the Cypress
# cache and cause our frontend cache load times in CI to become too long.
# This script clears out old versions of that cache.

CWD=$(realpath $(dirname "$0"))
FRONTEND_ROOT=$(realpath "$CWD/..")

# Cypress uses semver versioning, so all versions take the form of x.y.z
# yarn --silent is needed here, or else yarn prints its own semver version
# number also.
NUM_CYPRESS_VERSIONS=`yarn --silent cypress cache list | grep -Ec '\d+\.\d+\.\d+'`

if [[ "$NUM_CYPRESS_VERSIONS" == "1" ]]; then
  echo "Multiple versions of Cypress detected!"
  echo "Clearing the cache and reinstalling only the latest version."
  yarn cypress cache clear
  yarn cypress install
fi
```

**Comment by jennifer-shehane** [comment] 2020-10-29 08:42
This is now possible with `cypress cache prune`. Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-10-29 08:42 UTC
Labels: stage: proposal 💡, topic: installation, type: feature

**Comment by zeptonaut** [comment] 2020-10-29 15:03
Thanks for getting this prioritized @jennifer-shehane! Excited to delete that script that I wrote 😄
