### ISSUE TITLE
cy.request gets a 200 but doesn't call `then`

### ISSUE THREAD

**Issue by bwiklund** [cypress-io/cypress#8194] opened 2020-08-06 01:54 UTC
here's our code (with some details stripped out). we do a series of `cy.request` calls in order to create a test account.

```js
let TEST_USER_CREDENTIALS;
function getUserCreds() {
  if (TEST_USER_CREDENTIALS) return cy.wrap(TEST_USER_CREDENTIALS);
  return cy
    .request({
      ...
    })
    .then(() => {
      return cy.request({
        ...
      });
    })
    .then(() => {
      return cy.request({
        ....
      });
    })
    .then(resp => {
      TEST_USER_CREDENTIALS = resp.body;
      return cy.wrap(TEST_USER_CREDENTIALS);
    });
}
```

90% of the time this runs correctly, and gets the user creds back for our tests. But sometimes it runs all but the final `then` callback, despite always getting a 200 status code (as we can see in the console logs). This breaks our tests because other tests expect the cached `TEST_USER_CREDENTIALS` to be returned, but the whole request chain happens again and errors out because this user has already been created.

are we misunderstanding how this is supposed to work, or is this a bug in `cy.request`?

**Comment by anton-bulyenov** [comment] 2020-08-06 21:29
I'm having exactly the same issue as well

**Comment by jennifer-shehane** [comment] 2020-08-07 09:34
I'm not able to reproduce the issue as given. 

Working example below - test runs 50 times and never failed.

```js
let TEST_USER_CREDENTIALS;

function getUserCreds() {
  return cy.request('https://jsonplaceholder.cypress.io/users')
    .then(() => {
      return cy.request('https://jsonplaceholder.cypress.io/users')
    })
    .then(() => {
      return cy.request('https://jsonplaceholder.cypress.io/users')
    })
    .then(resp => {
      TEST_USER_CREDENTIALS = resp.body;
      return cy.wrap(TEST_USER_CREDENTIALS);
    });
}


describe("Testing", () => {
  Array(50).fill(0).forEach((val, i) => {
    it(`test ${i}`, () => {
      expect(getUserCreds()).to.not.be.empty
    })
  })
})
```

<img width="493" alt="Screen Shot 2020-08-07 at 4 04 33 PM" src="https://user-images.githubusercontent.com/1271364/89632120-b5e50c80-d8c7-11ea-8cd9-df8c0ba220af.png">


Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide a full failing example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-07 09:34 UTC
