### ISSUE TITLE
Cypress says script error thrown in cross origin script - do not know why

### ISSUE THREAD

**Issue by mxrguspxrt** [cypress-io/cypress#2554] opened 2018-10-02 14:57 UTC
Hello!

Everything works ok. 0 errors in Chrome or in tests console. But I get this error. And all pipeline is broken.

If there is a error, why it is hidden from me?

```
Uncaught Error: Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the 'crossorigin' attribute and setting a CORS header.

https://on.cypress.io/cross-origin-script-error

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

**Comment by jennifer-shehane** [comment] 2018-11-19 17:39
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

You may also try to update to version [3.1.2](https://on.cypress.io/changelog#3-1-2) as we just fixed some cross origin error issues.

**Comment by hiren0007** [comment] 2018-11-28 06:12
The Uncaught Error: Script error issue happens every time for https://harper-morpho-luna.myshopify.com, while I have used cy.visit('https://harper-morpho-luna.myshopify.com')

**Comment by hiren0007** [comment] 2018-11-29 10:44
> @hiren0007 I'm not totally sure why this is displaying as a 'cross origin error'. It looks like there is an error in Harpers own code trying to console.log() an undefined variable when the window loads. Perhaps I'm wrong about it not being from a cross origin script though 
> 
> <img alt="screen shot 2018-11-28 at 12 53 40 pm" width="431" src="https://user-images.githubusercontent.com/1271364/49132985-d1370080-f30c-11e8-875d-1e01a6035bd2.png">
> 
> If this is not your website and you cannot fix the error, I suggest adding a check to ignore uncaught errors in Cypress like below:
> 
> ```js
> Cypress.on('uncaught:exception', (err, runnable) => {
>   // returning false here prevents Cypress from
>   // failing the test
>   return false
> })
> 
> it('fails to visit website 1', function () {
>   cy.visit('https://harper-morpho-luna.myshopify.com')
> })
> ```

Thanks Jennifer.
It really worked. (bypassed uncaught exception).

**Closed** 2018-12-04 08:17 UTC
Labels: stage: needs information

**Comment by JohnnyFun** [comment] 2019-04-13 05:23
fwiw, in my case the error was that I used `Promise.prototype.finally`, which is supported in chrome 73, but not in electron 59.

**Comment by felipenmoura** [comment] 2019-07-24 18:35
Hello.
Interestingly, this workaround (bypassing uncaught errors) work in the `open` ui, but still fail in terminal/cli!
Any reason for that?!

**Comment by jmargolisvt** [comment] 2020-01-27 20:33
My issue is that I've added a new `script` tag that points to a different subdomain.  I have a `link` tag that also points to a different subdomain, but Cypress is fine with that.  Seems the problem is with Cypress.  I can't think of a reason that Cypress should fail when it finds a COR.  If it's ok for one tag, it should be ok for the other.  Adding `"chromeWebSecuirty": false` to my cypress.json did not fix the problem.  I think this issue should be re-opened and fixed to allow the resource.

**Comment by jennifer-shehane** [comment] 2020-05-05 09:15
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by darrylsepeda** [comment] 2023-07-24 02:39
> @hiren0007 I'm not totally sure why this is displaying as a 'cross origin error'. It looks like there is an error in Harpers own code trying to console.log() an undefined variable when the window loads. Perhaps I'm wrong about it not being from a cross origin script though 🤔
> 
> <img alt="screen shot 2018-11-28 at 12 53 40 pm" width="431" src="https://user-images.githubusercontent.com/1271364/49132985-d1370080-f30c-11e8-875d-1e01a6035bd2.png">
> 
> If this is not your website and you cannot fix the error, I suggest adding a check to ignore uncaught errors in Cypress like below:
> 
> ```js
> Cypress.on('uncaught:exception', (err, runnable) => {
>   // returning false here prevents Cypress from
>   // failing the test
>   return false
> })
> 
> it('fails to visit website 1', function () {
>   cy.visit('https://harper-morpho-luna.myshopify.com')
> })
> ```

Sorry to comment on this thread, I thought no point of creating new issue when the same thread is already exist.
I found bypassing uncaught error doesn't return the API response to the component, therefore causing another issue in my component. Is there another way to get API response without getting this cors issue?

Tried to use cy.intercept, but the component still calling the real API and got the same cors error.

**Comment by nagash77** [comment] 2023-07-27 13:25
@darrylsepeda Are you running component tests or E2E tests? Currently cy.origin (which is needed for cross origin testing) only works in E2E tests.

**Comment by darrylsepeda** [comment] 2023-07-31 02:21
I'm running component tests, but cors issue always appear when my component calling an endpoint for its data.
However, I found fixture is able to mock the API response while bypassing uncaught error solves the cors issue.
