### ISSUE TITLE
Cypress occasionally fails to fetch existing module in CI when building with Vite

### ISSUE THREAD

**Issue by hansfuchs-optimate** [cypress-io/cypress#21450] opened 2022-05-12 12:40 UTC
### Current behavior

One particular test case in our e2e tests fails occasionally when run in the GitLab CI (about every 10-15 runs), after building with Vite and starting a dev server with [start-server-and-test](https://github.com/bahmutov/start-server-and-test).
This happens even though all other test cases use the module (in this case: `landingpage.2abc81c5.js`) without any problems.
This does not occur when running the test suite locally.

Basically the procedure looks as such:
```
> vite build --mode e2e-ci
> vite preview --port 3000
> cypress run
```

Relevant vite build output:
```
vite v2.9.5 building for e2e-ci...
transforming...
✓ 2557 modules transformed.
rendering chunks...
[...]
dist/assets/landingpage.2abc81c5.js                       17.84 KiB / gzip: 5.38 KiB
[...]
```

Relevant Cypress output:
```
Running:  general/general.spec.ts                                                         (3 of 9)
In general
  ✓ the default browser language should be detected (4924ms)
  1) users can switch their language
1 passing (7s)
1 failing
1) In general
       users can switch their language:
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > Failed to fetch dynamically imported module: http://localhost:3000/assets/landingpage.2abc81c5.js
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
https://on.cypress.io/uncaught-exception-from-application
```
In the above test scenario, both tests access the landingpage, however only the second fails.

Test Code:
```ts
describe('In general', () => {
  it('the default browser language should be detected', () => {
    initAppFor(freeUser)
    inGeneral().shouldDetectBrowserLanguage()
  })

  it('users can switch their language', () => {
    initAppFor(freeUser)
    inGeneral().shouldAllowLanguageSwitching()
  })
})
```

I know it says the error was not caused by Cypress, but was it really not?
We have never encountered this "`fails to fetch existing module`" problem before when testing locally or when deploying to production, so I think it's unlikely this is an issue with Vite.
Especially when the module itself IS being built and used by all other tests successfully.
As I understand it, the code for the second test isn't even run anyways, since Cypress cannot find the module.

### Desired behavior

Both tests should pass, as they do most of the time.

### Test code to reproduce

Sadly I have not yet been able to reproduce this in a minimal example.

### Cypress Version

9.6.0

### Other

Perhaps this issue occurs due to an issue with GitLab's CI...

Any suggestions or leads are greatly appreciated. 
Thanks in advance!

**Comment by BlueWinds** [comment] 2022-05-12 21:47
So I'm not really sure what's going on - from your description, it sounds like the browser isn't able to load that file, but there isn't enough info here for me to figure out why.

Our [Troubleshooting Guide](https://docs.cypress.io/guides/references/troubleshooting#Isolate-the-Problem) has advice on a variety of things to try which might help narrow down the problem, but unless you can provide a reproducible example, there's not much I can do to help narrow it down.

**Comment by artemjackson** [comment] 2022-05-17 09:14
@hansfuchs-optimate , check out [the comment](https://github.com/cypress-io/cypress/issues/18124#issuecomment-994598568), it may help you

**Comment by hansfuchs-optimate** [comment] 2022-05-17 10:05
> @hansfuchs-optimate , check out [the comment](https://github.com/cypress-io/cypress/issues/18124#issuecomment-994598568), it may help you

Thanks a lot! This could be the same or at least a similar issue. I'll definitely be watching this issue.

**Comment by hansfuchs-optimate** [comment] 2022-05-17 10:10
@BlueWinds 
The guide didn't really help, sadly.
I'll try to create a reproducible example soon.

**Comment by BlueWinds** [comment] 2022-05-17 15:34
It does sound extremely similar to #18124, thanks @artemjackson. I'm going to close this as a duplicate; If you do get a reproducible example, please do post it over there, it would be very helpful.

**Closed by BlueWinds** 2022-05-17 15:34 UTC
Labels: stage: awaiting response

**Comment by straurob** [comment] 2022-11-18 12:51
@hansfuchs-optimate Have you found the root cause or any viable solution to this problem?
