### ISSUE TITLE
Typing uses different Events to actual human typing

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress#7653] opened 2020-06-10 12:48 UTC
### Current behavior:

Typing in cypress seems to issue different events to a human doing the same key sequences, see below:

![image](https://user-images.githubusercontent.com/677167/84268535-b52a3700-ab1f-11ea-9233-b6afc6b9a3b1.png)

On the left is Chrome automated, on the right Chrome manual.

I'm trying to replicate, in cypress, a bug a customer hit. Where they type and our web app (Angular) looses characters due to a binding mistake.

The cypress spec always passes but when a human does manual testing the bug becomes very obvious.

In the screenshot cypress typed `el` and got `el` in the field but if the human types `el` they end up with `e`.

I've tried various options on type such as:

* Making sure to do `.focus()` before `.type()`
* Typing fast, medium, slow, mixed.
* Multiple `cy.type()`, chained `.type()` for individual characters.
* Forced

The events Angular says happened for the keyup are different...

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/677167/84269191-c758a500-ab20-11ea-82f4-aed2f7802424.png">

`Event` in Cypress versus `KeyboardEvent` in the human interaction.

The only other difference I can see if the `composed` field being `false` for cypress.

### Desired behavior:

Should match how a human types.

### Test code to reproduce

Commercial application unfortunatly.

```js
  it.only('should work', () => {
    cy.get('#search')
      .focus()
      .clear()
      .type('e', { delay: 350 }).should('have.value', 'e')
      .type('l', { delay: 550 }).should('have.value', 'el')
      .type('l', { delay: 150 }).should('have.value', 'ell')
      .type('a', { delay: 450 }).should('have.value', 'ella')
      .type('.', { delay: 350 }).should('have.value', 'ella.');
  })
```

### Versions

Cypress 4.8.0
MacOS
Chrome 83
Node 12 LTS
Angular 9.1.x

**Comment by jennifer-shehane** [comment] 2020-06-11 06:55
@philjones88 Yes, basically as you found, this is related to our not issuing Native Events, but rather simulating events.

Closing as duplicate of #311

**Closed by jennifer-shehane** 2020-06-11 06:55 UTC
