### ISSUE TITLE
Digits Scrambled when using type on tel input field with input mask

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#940] opened 2017-11-20 23:08 UTC
- Operating System: Windows 10
- Cypress Version: 1.1.0
- Browser Version: Chrome

### Is this a Feature or Bug? 
Bug

### Current behavior: 
When using .type() on tel inputs with masks, the numbers are entered out of order.  That is, digits are added to the end of the field when they meet a special character.

### Desired behavior:
The digits are entered into the field in order.

### How to reproduce:
Call .type() on a tel input field with an input mask that provides hyphens, parentheses, or other formatting

#### Test code:

```js
cy.get("#PrimaryPhone").type("1234567890").should('have.value', "(123) 456-7890")
//The above expected output is based on the input mask used by my application.  
//Your mileage may vary.
```

### Additional Info (images, stack traces, etc)

**Comment by jennifer-shehane** [comment] 2017-11-21 14:19
Can confirm, fails in v1.1.1. To replicate:

**Test code**
```js
it('Type in tel input with input mask', function(){
  cy.visit('http://robinherbots.github.io/Inputmask/')
  cy.contains('Demo').click()
  cy.get('input[data-inputmask-alias]').first()
    .type('11/21/2017')
    .should('have.value', '11/21/2017')
})
```

**Failed message**
<img width="1327" alt="screen shot 2017-11-21 at 9 17 47 am" src="https://user-images.githubusercontent.com/1271364/33077165-09e53fe0-ce9d-11e7-8432-be5ddc58e174.png">

**Comment by lardissone** [comment] 2017-11-24 18:36
Also doesn't works with [text-mask](https://github.com/text-mask/text-mask).

**Comment by lardissone** [comment] 2017-11-24 19:11
Typing the complete value works with text-mask.

For example I have a mask for times like: `10:30 am` and if I type it literally `.type('10:30 am')` it works.

**Comment by JPHamlett1993** [comment] 2017-11-27 17:55
I have something similar

Steps to reproduce

Run this on localhost:8000
```
<html>

<head>
</head>

<body>
    <input id="billingZip" name="zip" type="tel" value="55344" placeholder="" maxlength="5" data-track-id="" class="sessioncamhidetext form-control   ">
</body>

</html>
```

Run the following tests

#### Test code:

```js
it('Not Working Example', () => {
    cy.visit('localhost:8000')
    cy.get('#billingZip').clear().type('54321')
});

it('Workaround Example', () => {
    cy.visit('localhost:8000')
    cy.get('#billingZip').invoke('attr', 'maxlength', '10').clear().type('54321')
});

```

**Comment by brian-mann** [comment] 2017-11-27 21:12
@JPHamlett1993 actually after looking at your code I think you're referring to a bug in `1.1.1` that we've fixed and released in `1.1.2`. 

Update to that and it should work.

**Comment by JPHamlett1993** [comment] 2017-11-27 21:15
@brian-mann  I am on 1.1.2

**Comment by brian-mann** [comment] 2017-11-27 22:42
@JPHamlett1993 I confirmed your issue. I think it's a separate one from this. It's another edge case around the `maxlength`. Basically what's happening is that your input is already at maxlength, and then cypress is not applying the special character because it thinks it's been exceeded.

**Comment by JPHamlett1993** [comment] 2017-11-28 12:56
@brian-mann Why does Cypress look at max-length, why shouldn't the application handle that?

**Comment by brian-mann** [comment] 2017-11-28 17:37
Because `maxlength` is irrelevent when setting the value property directly

**Comment by davidszepernick** [comment] 2018-01-05 23:01
I have an element as follows:
<input type="text" name="auth_column" id="auth_column" value="AB" maxlength="2" minlength="2" class="av-touched av-pristine av-valid form-control">
cy.get('#auth_column').clear() does not work for this field
( I dont think any of the special character sequences are working either.)

**Comment by davidszepernick** [comment] 2018-01-05 23:03
sorry, as follows:
input type="text" name="auth_column" id="auth_column" value="AB" maxlength="2" minlength="2" class="av-touched av-pristine av-valid form-control"

**Comment by paulbao** [comment] 2018-05-02 02:06
There's workaround that might be helpful to people who have the same issue.
`cy.get("#PrimaryPhone").then($input => $input.val('123) 456-7890')).should('have.value', "(123) 456-7890")`

**Comment by LeightonDarkins** [comment] 2018-05-28 12:05
@paulbao Extending on your workaround, I found that overriding the value worked great, but I still needed to call .type() to trigger an onChange event.

So I chose to simulate clear() by emptying the input value, then typing in the new value I wanted:

```javascript
    cy.get('#UserInfoDialog input')
      .then($input => $input.val(''))
      .type('123')
      .should('have.value', '123')
```

**Closed** 2018-07-23 08:43 UTC
Labels: pkg/driver, type: bug
