### ISSUE TITLE
Response body is not added to console props for successfull XHR logs

### ISSUE THREAD

**Issue by archfz** [cypress-io/cypress#25924] opened 2023-02-22 20:37 UTC
### Current behavior

Response body is not added to console props for successfull XHR logs. On the other hand atleast for certain failing XHR it is added.

![image](https://user-images.githubusercontent.com/13706730/220752096-f418ecb4-a4fe-404b-b264-14cb78c0883e.png)

### Desired behavior

Response body should always appear in console props. This is also requested by users of cypress-terminal-report plugin. On pipeline this is very useful since there you **cannot** go to network tab of the browser alternatively to check. See https://github.com/archfz/cypress-terminal-report/issues/176

### Test code to reproduce

On the example setup of cypress, the following should enough to trigger one such kind of XHR log.

cy.visit('/commands/network-requests');
cy.get('.network-btn').click();

### Cypress Version

12.4.1

### Node version

12.22.6

### Operating System

Ubuntu 22.04

**Comment by marktnoonan** [comment] 2023-02-27 16:40
Thanks @archfz, this matches the way logging seems to be intended to work (based on our [tests here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cypress/proxy-logging.cy.ts#L96)), but I can see the usefulness of including the response body always.

I'm going to route this to the e2e team, who can update this issue if there's a specific reason to avoid doing this.

**Comment by jennifer-shehane** [comment] 2023-08-10 19:35
Duplicate of https://github.com/cypress-io/cypress/issues/21421

**Closed as completed by jennifer-shehane** 2023-08-10 19:35 UTC
Labels: E2E, Triaged
