### ISSUE TITLE
Cypress Test Runner crashes every time when closing

### ISSUE THREAD

**Issue by zac11** [cypress-io/cypress#17854] opened 2021-08-23 14:55 UTC
### Current behavior

When ever I try to close the Cypress test runner, it crashes on clicking the [x] icon, with a crash report being generated and then the crash being reported on the terminal.

Terminal Output once the crash happens -

```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (20.6.0)
Cypress Version: 8.3.0

```

Here is the complete crash report - [Pastebin](https://pastebin.com/DSuxN9mq)

### Desired behavior

Test runner should exit without any crash.

### Test code to reproduce

```
const { expect } = require("chai");
const { it } = require("mocha")

describe("Launch the movie URL",()=>{

    beforeEach(()=>{
        cy.visit('/')
    });

    it('verifies the title',()=>{
        expect(cy.title().to.eql('TBP'))
    })

    it("launches the first test",()=>{
       cy.get("a[href='/login']").click()
    });

})
```

### Cypress Version

8.3.0

### Other

OS - Mac OS Big Sur 11.5.2
VS Code - 1.52
Node - 16.7.0

**Comment by jennifer-shehane** [comment] 2021-08-23 15:06
Duplicate of https://github.com/cypress-io/cypress/issues/17766 - this will be fixed in our next release.

**Closed by jennifer-shehane** 2021-08-23 15:06 UTC
