### ISSUE TITLE
Screenshots taken in 1000px viewport are 800px wide in Docker + Chrome + Headless

### ISSUE THREAD

**Issue by steveharrison** [cypress-io/cypress#6246] opened 2020-01-27 04:45 UTC
### Current behavior:
When I set the viewport to 1000x600px and then take a screenshot, the resulting screenshot is 800x600px wide. This only happens when running inside Docker.

### Desired behavior:
I expect the screenshot to be 1000px wide.

I've read @brian-mann's [post about issues with taking screenshots larger than 1280x720px](https://github.com/cypress-io/cypress/issues/2102#issuecomment-402901382), but 1000x600px is within these dimensions.

### Test code to reproduce
1. Checkout this repository: https://github.com/steveharrison/cypress-viewport-test/.
2. Install dependencies with `npm i`.
3. Start the test server with `npm start`, which will fire up a server at `http://localhost:9000`.
4. Ensure Docker for Mac is running and then run `npm run test-d` (which runs `docker run -it -v $PWD:/cypress -w /cypress --entrypoint=cypress cypress/included:3.8.2 run --config baseUrl=http://host.docker.internal:9000 --headless --browser chrome`).
5. Check the resolution of `screenshots/main.spec.js/Cypress Viewport Test -- works.png`.

### Versions
- Cypress 3.8.2 (running in Docker using cypress/included:3.8.2)
- Docker for Mac 2.2.0.0
- macOS 10.12.6
- Node 13.6.0 (running in `nvm` and used for the project, not in Docker)

**Comment by jennifer-shehane** [comment] 2020-01-28 08:52
Duplicate of https://github.com/cypress-io/cypress/issues/6210

**Closed by jennifer-shehane** 2020-01-28 08:52 UTC
