### ISSUE TITLE
Add configuration option to throw error when `it.only()` is used

### ISSUE THREAD

**Issue by martinsik** [cypress-io/cypress#6536] opened 2020-02-22 14:30 UTC
### Current behavior:

Using `it.only()` will execute only a single or multiple `only.it()` tests in a file when running Cypress with `cypress run`.

### Desired behavior:

I'm using `it.only()` a lot when writing tests but sometimes by mistake a forget to remove it before commiting changes. Then on our CI/CD we run the entire test suite and we don't realise that some tests were ignored because we forgot `it.only()` somewhere.

I think it would be great if there was a configuration option to abort tests and return error status code when Cypress finds any `.it()` usage. This would include all `describe.only()` and `context.only()` usage.

### Test code to reproduce

https://github.com/martinsik/cypress-it-only-failing-test

After cloning the repo and running `npm run cypress:run` it will pass with two passing tests even when there's one test that should fail https://github.com/martinsik/cypress-it-only-failing-test/blob/master/cypress/integration/other.spec.js#L6

It passed because it forgot to remove `it.only()`.

```
      Spec                                              Tests  Passing  Failing  Pending  Skipped    
 ┌────────────────────────────────────────────────────────────────────────────────────────────────┐  
 │ √  other.spec.js                             86ms        1        1        -        -        - │  
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤  
 │ √  spec.js                                  00:03        1        1        -        -        - │  
 └────────────────────────────────────────────────────────────────────────────────────────────────┘  
   √  All specs passed!                        00:03        2        2        -        -        -    
                                                                                                     
```

### Versions

Cypress 4.0.2

**Comment by Narretz** [comment] 2020-02-23 20:28
This has been requested before: https://github.com/cypress-io/cypress/issues/239 I suggest we focus on this issue.

**Comment by jennifer-shehane** [comment] 2020-02-24 06:36
Duplicate of #239 

Although there are several other ways to prevent this currently outside of Cypress and I'm leaning to just closing the other issue outright because of this. 

We personally prevent commiting to our own project by setting up a `husky` precommit hook to prevent commit `.only` using the `stop-only` npm package: https://github.com/bahmutov/stop-only#readme

**Closed by jennifer-shehane** 2020-02-24 06:36 UTC

**Comment by martinsik** [comment] 2020-02-24 08:57
Thanks, I didn't know about https://github.com/bahmutov/stop-only.

**Comment by jrr** [comment] 2020-10-30 03:03
If you're using ESLint, check out this plugin: https://github.com/levibuzolic/eslint-plugin-no-only-tests
