### ISSUE TITLE
Files uploaded via input[type="file"] only have names for the first test in a spec file

### ISSUE THREAD

**Issue by textbook** [cypress-io/cypress#28492] opened 2023-12-11 10:44 UTC
### Current behavior

When end-to-end testing an app that allows the user to upload a file using `file[type="input"]`, we noticed some inconsistent behaviour - for the first test in a given file, a test that relies on the `name` property of the `File` object received by the event handler (as part of the target's `files` property) will pass. The core part of the test is:

```javascript
cy.fixture(filename /* in cypress/fixtures */).as('file')  // get fixture
cy.get('input[type="file"]').selectFile('@file')  // select fixture in file input
cy.get('#filename').should('contain.text', filename)  // assert on name property
```

However, any _subsequent_ test in the same file will receive an empty string for the name of the file (the file _content_ seems to be fine).

Note that:

- Another `describe` block in the same test file will also fail; but
- The first test in a separate test file will succeed.

I'd initially wondered if this was something to do with Vite, React or even Cypress Testing Library, but we've trimmed all of that away and still see the error.

### Desired behavior

I am expecting the behaviour to be consistent between the suites and tests - the `File` object received by the event handler should _always_ have an appropriate `name`.

### Test code to reproduce

MRE: https://github.com/textbook/cypress-test-file-name

### Cypress Version

13.6.1

### Node version

20.10.1 (also 18.19.0)

### Operating System

macOS 14.1.2 (also Windows 11 Enterprise 22H2, Ubuntu 22.04)

### Debug Logs

This was too long for GitHub Issues, but it's running in GitHub Actions with the debug flag set: https://github.com/textbook/cypress-test-file-name/actions/runs/7166270414/job/19509914235

**Comment by jennifer-shehane** [comment] 2023-12-11 15:26
Duplicate of https://github.com/cypress-io/cypress/issues/21936

**Closed as completed by jennifer-shehane** 2023-12-11 15:26 UTC
Labels: type: duplicate

**Comment by textbook** [comment] 2023-12-11 15:27
You're right, thank you @jennifer-shehane - evidently I hadn't searched back far enough.
