### ISSUE TITLE
Cypress changes layout position for element on the page when i try to select element

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [cypress-io/cypress#5410] opened 2019-10-22 05:50 UTC
### Current behavior:  

when i try to select element cypress changes layout position for element on the page (as shown on the screen) 

---- before selecting element - everything is ok ----
![image](https://user-images.githubusercontent.com/50987561/67260818-5431ee00-f4bf-11e9-8465-18378324a9bc.png)
---- when cypress tries to select my element-------------
![image](https://user-images.githubusercontent.com/50987561/67260840-762b7080-f4bf-11e9-9e83-a32f38d30f86.png)

### Desired behavior: Layout shouldn't be changed on selecting elements

I tryed this test case on testcafe also, everything works fine, so I suppose it's not a problem of my code 

### Steps to reproduce: (app code and test code) 

Step 1: go to https://powr-staging.io/plugins/form-builder/standalone (sign in first)
Step 2: Select 'Payment' or 'Design' tab and try to select and click to first element (it'll be failed)

### Versions

OS: MacOS
Browser: Chrome 77
Cypress: 3.4.1
Extra: our page wrapped into iframe block (may be cuz it) and we are using React.js on front-end side.

**Comment by jennifer-shehane** [comment] 2019-10-22 22:26
When you hover over a command in the Command Log within Cypress, we show a preview of the application at the time the test ran - as well as highlight the element that was found in Cypress at the time. 

Since this element *may* have been outside of the viewport at the time we found the element, Cypress scrolls the containers of the element in an attempt to show you the element preview. **Cypress is not scrolling the containers at the time the test ran**

There's an explanation here: https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Debugging

Closing this issue as a duplicate of https://github.com/cypress-io/cypress/issues/483

**Closed by jennifer-shehane** 2019-10-22 22:26 UTC

**Comment by jennifer-shehane** [comment] 2019-12-24 09:18
Please comment in the original issue for any followup https://github.com/cypress-io/cypress/issues/483
