### ISSUE TITLE
When running Cypress interactive application it fails with SIGTRAP error

### ISSUE THREAD

**Issue by croraf** [cypress-io/cypress#7943] opened 2020-07-10 08:35 UTC
### Current behavior:

![image](https://user-images.githubusercontent.com/19698636/87134042-6b587c00-c298-11ea-8393-5d39ef1ab6b5.png)

### Desired behavior:

Tests should complete.

### Test code to reproduce

The error happens when I run a larger testsuite in the Cypress interactive application `cypress open`. Rarely the suite passes, but in majority of cases it fails. I haven't notice it happen when I run it with `cypress run` (and headless), although I might not have run it enough times.

### Versions

Cypress: 4.9.0
OS:   Ubuntu 19.10,    `5.3.0-62-generic #56-Ubuntu`   and   Ubuntu 20.04, `5.4.0-40-generic #44-Ubuntu`
Browser: Chrome, Version 83.0.4103.116 (Official Build) (64-bit) and Chromium, Version 83.0.4103.116 (Official Build) snap (64-bit)

**Comment by jennifer-shehane** [comment] 2020-07-13 05:41
@croraf Can you provide the exact error text that is thrown from stdout?

This may be related to the application you are testing. Can you provide the test code to reproduce this? Thanks!

**Comment by croraf** [comment] 2020-07-13 08:23
The stdout does not show any interesting, I just see the HTTP requests which just stop at one instant:

```
...
...
GET /rest/v1/comments?entityType=CASE&entityId=30000001 200 4.029 ms - -
```

Also as I said, I haven't found the exact code that does this. All of my test suites produce this randomly. I think it could be more related to the OS.


-----------
The test code is proprietary, I don't have rights to post it. Would I have to provide the application code that does this or only the test code?

**Comment by jennifer-shehane** [comment] 2020-07-14 06:48
@croraf We would need enough information to run this exactly on our system to see the SIGTRAP error, otherwise there's no really anything we can look at here without that.

**Comment by croraf** [comment] 2020-07-14 10:15
I've cloned https://github.com/cypress-io/cypress-example-kitchensink, and I cannot reproduce the error with that project (on the same machine)!

What I can say (again) is that the error happens with my test suite on almost every run, but not consistently on the same point in the suite.

Perhaps if you have some ideas on why it might happen, and if we can keep the issue open so maybe someone else might experience this same issue and add the code which reproduces it.

**Comment by jennifer-shehane** [comment] 2020-07-27 11:18
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-27 11:18 UTC
Labels: stage: needs information

**Comment by dennis-benzinger-hybris** [comment] 2020-10-14 12:49
It's not much but when this happened to me I found the following in `/var/log/kern.log`:
```
Oct 14 14:26:38 dennis-virtual-machine kernel: [16403.834046] traps: chrome[26354] trap int3 ip:5640a2c8cfad sp:7ffd3b28d8d0 error:0 in chrome[5640a0966000+73fd000]
```

**Comment by croraf** [comment] 2021-05-13 14:52
This still persists in
Cypress: 7.3.0
Chrome: Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by cjcrandall** [comment] 2022-04-21 17:33
@jennifer-shehane here's a MRE:

``` javascript
describe('hog memory', () => {
  for (let i = 0; i < 100; i++) {
    it('takes pictures', () => {
      cy.visit('https://www.cypress.io/');
      cy.screenshot();
    });
  }
});
```

My environment:
* Ubuntu 20.04
* Cypress 9.5.4 (our real tests are on 8.7.0)
* Chrome 100
* Node 16.14.0

The above fails partway through when executed using `cypress open` with an "Aw, snap!" SIGTRAP error, but passes when using `cypress run --browser chrome`.

Setting `numTestsKeptInMemory` to something really low like 5 seems to allow it to pass using `cypress open`, but I'd much rather see Cypress fail the tests with a reasonable error _before_ Chrome actually runs out of memory, since when this happens you get no details on how far the tests got or what the results prior to the SIGTRAP were.

**Comment by ivelin** [comment] 2022-08-24 13:55
Here is another example of a test that leads to core dump and SIGTRAP error in the browser. [This is the line](https://github.com/ivelin/sweat-token/blob/055e72aec984ea6caed05659987b71c63ff10c1c/e2e-tests/tests/e2e/specs/projects.js#L99) that triggers it.

```
    it(`Should proceed to contract write via wallet`, () => {
       cy.get('input[name="goalTitle"]').type('Complete Milestone 10')
       cy.get('input[name="deadline"]').type('2222-12-31')
       cy.get('[data-cy="submit-button"]').click()          <<<<<<<< causes synpress/cypress to hang up
```

**Comment by JohnSmithyy** [comment] 2022-08-29 12:59
@jennifer-shehane I'm also experiencing the same issue.

**Comment by henricook** [comment] 2022-09-14 11:18
This is affecting me, also on an Ubuntu system with Cypress `10.8.0`. I can't run any of the extended tests in our test suites. Anecdotally mac users on the team don't have this issue.

Now that this has a hard repro case from @cjcrandall can we reopen this issue @jennifer-shehane ?

Update: specifying `NODE_ENV=production` in front of `cypress run` didn't appear to make any difference for me

Update 2: This looks to be caused by: https://github.com/cypress-io/cypress/issues/23391

I did not get this behaviour when I downgraded Edge to version 102
