### ISSUE TITLE
TypeError: Cannot convert undefined or null to object failing the test

### ISSUE THREAD

**Issue by arnojong** [cypress-io/cypress#4181] opened 2019-05-13 08:19 UTC
### Current behavior:
My tests are failing because of the `TypeError: Cannot convert undefined or null to object` failing the test

### Steps to reproduce

I wrote the following test, yet it fails, I followed the documentation but don't see what I did wrong.

```js
context('Checkout', () => {
  
  before(() => {
    cy.visit('https://www.geluk.com/feest-en-themadagen')
  })

  it('clicks the first product', () => {
    cy.get('.product-item__title').contains('Amerigo').click()
  })

  it('clicks the custom product options', () => {
    cy.get('select.product-custom-option').eq(0).select('Geen')
    cy.get('select.product-custom-option').eq(3).select('Geen')
  })

  it('clicks the checkout button', () => {
    cy.contains('Direct bestellen').click()
  })

  it('checks if we are on the right location', () => {
    cy.url().should('include', '/onestepcheckout')
  })

})
```

### Versions

Cypress version 3.2.0, using `npx cypress open` to show the runner, no changes made to that.
Mac OSX Mojave 10.14

**Comment by jennifer-shehane** [comment] 2019-05-14 06:19
Hey @arnojong, thanks for providing the test code to reproduce the issue. Unfortunately, when I run the code above, I get some different errors. 

<img width="609" alt="Screen Shot 2019-05-14 at 12 48 58 PM" src="https://user-images.githubusercontent.com/1271364/57674973-adf7d780-7646-11e9-9e7a-3827c20e0b7f.png">


Do you have anything in your `cypress.json` configuration file that I should also have set up?

Can you send a screenshot of the TypeError you are seeing in the Test Runner? I'd like to see where this is being thrown.

You should also be able to click the error in the Command Log with devtools open and see the stack trace of the error printed within the console - this may help you track down where the error is throwing. 

Let me know!

**Comment by arnojong** [comment] 2019-05-27 07:31
Hey Jennifer,

There's nothing in my cypress.json file.
Below I attached a screenshot of the test runner. 

![image](https://user-images.githubusercontent.com/15924505/58402382-75052d00-8060-11e9-824e-62bb261400c9.png)

I thought it may have something to do with clearing cookies, as it's a Magento based website, because of that I whitelisted all cookies, but the test still fails with the same error.

**Comment by jennifer-shehane** [comment] 2019-05-28 04:51
@arnojong 	Can you open the DevTools and click on the yellow error? This should print the stack trace in the console. Can you send a screenshot or what is printed there please? Thanks!

**Comment by arnojong** [comment] 2019-05-28 07:08
@jennifer-shehane Here you go!
![image](https://user-images.githubusercontent.com/15924505/58457882-130ffa80-8128-11e9-8691-4ec196bcabc8.png)

**Comment by jennifer-shehane** [comment] 2019-05-30 05:15
@arnojong This error is coming from your application's code at `https://geluk.com/static/frontend/Elephant/jumbo/nl_NL/jquery/jquery.storageapi.min.js:2:1921` as indicated in the stacktrace. Normally Cypress has a better error message - mentioning that the error is coming from your application. 

I would suggest looking into why that is happening at that line of code. 

I can't give much more insight since I haven't been able to run this locally and get the same error. We'd need a reproducible example.

**Comment by jennifer-shehane** [comment] 2019-07-11 07:19
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-11 07:19 UTC
Labels: stage: needs information

**Comment by WinstonN** [comment] 2019-11-03 01:45
Hi @arnojong just dropping a comment here, to let you know that I saw the same error. I see you're also running a Magento site. This error happens sporadically and I am not able to accurately reproduce is - no action is needed here, I just thought I'd let you know that there is someone else in the world that saw this :)

**Comment by paul-cc** [comment] 2019-11-06 13:46
Also seeing this error with Magento, but only in the graphic test runner. Tests work fine in the CLI.

**Comment by WinstonN** [comment] 2019-11-15 21:28
Hi, 

I have had some time to look into this error

It appears for me when selecting product options, address autocomplete drop down options, and it prevented my checkout from completing

I first started by going over the versions of https://github.com/julien-maurel/jQuery-Storage-API
, to see if I can upgrade, but that did not solve my issue
 
Early on in my tests, I saw that my local storage (which Magento 2 depends on) are being cleared. This is a philosophy of Cypress and I agree with it, but Magento depends on that storage data being set - I found the same for cookies btw

What I ended up doing was to set the below at the top of my test
```
Cypress.LocalStorage.clear = function(keys, ls, rs) {};
```

That has prevented the error from firing, and my tests, no function as they should

Hope it helps!
