### ISSUE TITLE
Installing Cypress failed at the cypress@3.8.2 postinstall script 

### ISSUE THREAD

**Issue by UmranDogan** [cypress-io/cypress#6208] opened 2020-01-21 14:30 UTC
Im new in automated testing and want to use cypress.
I installed node js and npm. Now i want to install cypress and followed the instruction on [www.cypress.io ](www.cypress.io). 

when i run `npm install cypress --save-dev` on my powershell i'm getting the following error message: 

```
The command "node" is either misspelled or
could not be found.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.8.2 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.8.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\U\AppData\Roaming\npm-cache\_logs\2020-01-21T11_05_01_566Z-debug.log
```

I want cypress to run so I can test our project. But thats not possible now.

i tried out `npm -v` and `node -v` and get the current versions: npm(6.13.6) and node (v13.6.0)
I added the path to my environment variables. 
what else can i do?

im using windows 10

**Comment by codecog** [comment] 2020-01-21 15:34
I would put this down to your powershell version not having access to node rather than it being an issue with the postinstall script. 

I've tried installing cypress on a fresh project (on a pretty fresh install of the OS as well) and didn't run into the same problem.

**Comment by UmranDogan** [comment] 2020-01-21 15:39
> I would put this down to your powershell version not having access to node rather than it being an issue with the postinstall script.
> 
> I've tried installing cypress on a fresh project (on a pretty fresh install of the OS as well) and didn't run into the same problem.

i can run `node-v ` and get the version back. how can i check this else ?

**Comment by codecog** [comment] 2020-01-21 15:44
Try running a javascript file with node from the same powershell window.

**Comment by UmranDogan** [comment] 2020-01-21 16:00
i get this error back. 

```
ReferenceError: context is not defined 
[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:811:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m

what does ist mean?
```

**Comment by codecog** [comment] 2020-01-21 16:06
that doesn't provide too much information. What is context and where is it trying to be called from?

**Comment by UmranDogan** [comment] 2020-01-21 16:08
`C:\Users\Username\source\repos\......\examples\actions.spec.js:3
context('Actions', () => {
^

ReferenceError: context is not defined
    at Object.<anonymous> (C:\Users\Username\source\repos\.....\examples\actions.spec.js:3:1)
[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:811:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m`

**Comment by UmranDogan** [comment] 2020-01-21 16:10
> that doesn't provide too much information. What is context and where is it trying to be called from?

im really thankfull for your support. hope im not ennoying you

**Comment by codecog** [comment] 2020-01-21 16:14
context does not exist in your `actions.spec.js` file. I think this is not a cypress issue and it down to an issue in your source code.

**Comment by UmranDogan** [comment] 2020-01-22 14:27
hi i run a js file on my powershell. thats okay. but now im getting this error message again when installing cypress. on my mac i have no problems installing cypress but on my windows (where i actually need cypress) i m getting this error messages. 

` node index.js --exec install

The command "node" is misspelled or can not be found.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.8.2 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.8.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\u\AppData\Roaming\npm-cache\_logs\2020-01-22T14_21_27_724Z-debug.log`

**Comment by codecog** [comment] 2020-01-22 14:28
It is more or less saying, it cannot find the command `node` which would come back to your node install on the windows machine.

**Comment by UmranDogan** [comment] 2020-01-22 14:38
hmm how can i fix this?

**Comment by codecog** [comment] 2020-01-22 14:39
you would need to look at how you installed node on your machine. I don't think the issue is cypress related.

**Comment by jennifer-shehane** [comment] 2020-01-23 10:53
Closing as this does not appear to be a Cypress issue.

**Closed by jennifer-shehane** 2020-01-23 10:53 UTC

**Comment by yoonjong-park** [comment] 2021-11-25 02:18
i met same issue again
