### ISSUE TITLE
Debug filter DEBUG=cypress:server:browsers:electron not working

### ISSUE THREAD

**Issue by roggerfe** [cypress-io/cypress#6160] opened 2020-01-14 14:06 UTC
### Current behavior:

I am not being able to filter debugs message using cypress run command

### Desired behavior:

I should be able to filter debug messages as explained here in the docs: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

### Test code to reproduce

To reproduce this issue, you can simply start a new cypress project:

`npm i --save cypress`
`./node_modules/.bin/cypress open`

If you run
`DEBUG=cypress* node_modules/.bin/cypress run`
all debugs are printed in the console

if you run
`DEBUG=cypress:server:browsers:electron node_modules/.bin/cypress run`
No debug message is printed

### Versions

Cypress version: 3.8.1
Operating System: Linux Mint

**Comment by jennifer-shehane** [comment] 2020-01-15 07:41
Closing as duplicate of https://github.com/cypress-io/cypress/issues/5051 which I will reopen. I'm not able to reproduce this though so it must be something specific to the environment.

**Closed by jennifer-shehane** 2020-01-15 07:41 UTC
