### ISSUE TITLE
Locale storage and cache is not cleared during two test 

### ISSUE THREAD

**Issue by atemor** [cypress-io/cypress#5411] opened 2019-10-22 13:41 UTC
### Current behavior:
During my test, i am visiting 2 differents URL in that order : 
1 - **URL A** **(Where I have to log in)**
2 - **URL B** **(Where I have to log in)**
I visit those URL in Two separate scenario using cucumber plugin.

When I rerun the test, I log as usual in the **URL A** BUT when I go to the **URL B** I am already logged. This is not normal. I have to logout manually in the cypress to can re run without being logged.

More strange : When i open the console to track the local storage, the **URL B** is not present when I am on the **URL A** BUT when I arrive on **URL B** (already log) the cache appears and the **URL A** cache is clear

### Desired behavior:

Changing URL should empty the cache

### Steps to reproduce: (app code and test code)

To fix it, i utilise this work around : 
```js
  cy.visit(urlMistertempApp, {
    onBeforeLoad: window => {
      window.localStorage.clear();
    }
  });
```

### Versions
3.4.1

**Comment by jennifer-shehane** [comment] 2019-10-22 22:20
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/2573

**Closed by jennifer-shehane** 2019-10-22 22:20 UTC
