### ISSUE TITLE
ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Requested setting not found

### ISSUE THREAD

**Issue by THILAGAWATHIATDNASKEW** [cypress-io/cypress#28907] opened 2024-02-09 14:14 UTC
### Current behavior

System config: 8CPU,16GB RAM,512GB.
Cypress version: 13.6.4
**When I am starting the cypress it is showing the below error:**
DevTools listening on ws://127.0.0.1:37589/devtools/browser/177ff725-e9a0-48d4-8d0e-3d3a8e328ad8
[209755:0209/192634.744702:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Requested setting not found

Note: My system gets hanged.

### Desired behavior

Error should not be present.

### Test code to reproduce

Installing Node.js
$ sudo apt update		
$ sudo apt install nodejs
$ node -v
Install npm
$ sudo apt install npm
Upgrade step for npm
$ npm install -g npm@<version>
Ex: npm install -g npm@10.4.0
Installing nvm to change the desired version of nvm to support nodejs
Go to the nvm repository
https://github.com/nvm-sh/nvm 
Copy the git clone link
$ git clone <nvm_repository_link>
$ ./install.sh
To use particular version
$ nvm install v21.1.0
$ nvm alias default v21.1.0

### Cypress Version

13.6.1

### Node version

10.4.0

### Operating System

20.04.6

### Debug Logs

```shell
DevTools listening on ws://127.0.0.1:37589/devtools/browser/177ff725-e9a0-48d4-8d0e-3d3a8e328ad8
[209755:0209/192634.744702:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Requested setting not found
```

### Other

Fix ASAP

**Comment by jennifer-shehane** [comment] 2024-02-09 16:09
Duplicate of https://github.com/cypress-io/cypress/issues/28061 This is a warning message and can safely be ignored

**Closed as not planned by jennifer-shehane** 2024-02-09 16:09 UTC
Labels: type: duplicate
