### ISSUE TITLE
Cypress 12.10.0 is failing with assertion errors or API call is returning undefined when run it on Gitlab schedule

### ISSUE THREAD

**Issue by GauriMestry** [cypress-io/cypress#26910] opened 2023-06-01 17:45 UTC
### Current behavior

I migrated from cypress 7.3.0 to 12.10.0. All my test cases are running fine on local but while running it from gitlab schedule it is failing by asstertion errors or returning undefined from API calls.

### Cypress Version

12.10.0

### Node version

18.16.0

### Package Manager

npm

### Package Manager Version

8

### Operating system

Linux

### Operating System Version

NA

**Comment by nagash77** [comment] 2023-06-02 12:25
Hi @GauriMestry Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

Also check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nagash77** [comment] 2023-06-09 12:40
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-06-09 12:40 UTC
Labels: topic: installation

**Comment by GauriMestry** [comment] 2023-06-09 14:00
Hi,
You can close this issue as my issue is resolved now.
Thanks for your response
