### ISSUE TITLE
Allow one to store location as alias and visit it later

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#2854] opened 2018-11-29 01:38 UTC
### Desired behavior:

I would love if something like this would work:

```js
cy.location('pathname').should('match', /\/document\/(.*)/).as('document');

// ... much later ...

cy.visit('@document');
```

**Comment by jennifer-shehane** [comment] 2018-11-29 11:01
What happens when you run this test code currently?

**Comment by mitar** [comment] 2018-11-29 15:33
It tries to open '@document` as a location and gets 404.

**Comment by jennifer-shehane** [comment] 2018-12-03 03:19
**Reproducible Example**

```js
describe('location test', function () {
  beforeEach(() => {
    cy.visit('https://example.cypress.io/commands/querying')
  })

  it('alias location', function () {
    cy.location('pathname').as('querying').should('match', /querying/)
    cy.visit('@querying')
  })
})
```

**Error on `cy.visit()`**

```
Error:     CypressError: cy.visit() failed trying to load:

@querying

We failed looking for this file at the path:

/Users/jennifer/Dev/cypress-example-kitchensink/@querying

The internal Cypress web server responded with:

  > 404: Not Found
```

**Comment by joshpzero** [comment] 2019-04-22 23:15
This seems like some pretty useful behaviour that fits the use case for the alias nicely. Can this be prioritised or a proposed solution for a custom command?

**Comment by jennifer-shehane** [comment] 2019-04-24 15:45
Honestly this is pretty low priority in terms of things we are working on. 

You're welcome to open a PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by michael1visser** [comment] 2022-06-07 16:45
A little late to the game but for anyone who might hit this thread later:

I was able to get the url string by chaining a promise off the alias and using the alias value as an argument.

```
cy.get('@mySavedUrl').then($mySavedUrl => {
      cy.visit($mySavedUrl);
    });
```

**Comment by mshavliuk** [comment] 2022-10-18 11:42
A shorter version of `michael1visser`'s code:
```ts
cy.get<string>('@url').then(cy.visit);
```

**Comment by jennifer-shehane** [comment] 2024-01-24 01:52
Since this has not had a lot of interest over the years, we’ll close this as not planned.

**Closed by jennifer-shehane** 2024-01-24 01:52 UTC
Labels: type: feature, stage: ready for work

**Comment by mitar** [comment] 2024-01-24 09:27
6 upvotes and 5 different people commenting is not a lot of interest. :-(
