### ISSUE TITLE
[7.0.0] FormData requests cause cypress to crash

### ISSUE THREAD

**Issue by Threnos** [cypress-io/cypress#15851] opened 2021-04-07 14:26 UTC
### Current behavior
Sending XMLHttpRequest **with .png image file** crashes cypress. When code reaches xhr.send() method, it's instantly over. Sending usual object with string key-value pairs works as usual.

Console output:
```
(node:7892) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
(node:7892) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
GET /__/ 200 48.858 ms - -
GET /chrome-variations/seed?osname=linux&channel=stable&milestone=89 200 290.749 ms - -
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 254.251 ms - -
GET /__cypress/runner/cypress_runner.css 200 17.430 ms - -
GET /__cypress/runner/cypress_runner.js 200 17.439 ms - -
GET /__cypress/runner/popper.js.map 404 1.422 ms - 136
GET /__cypress/iframes/integration/API/AP/admin/customer/deleteLogo.ts 200 10.735 ms - -
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 1.087 ms - 76120
GET /v1/pages/ChRDaHJvbWUvODkuMC40Mzg5LjExNBIQCcmLdcaTM2VsEgUNkWGVThIXCQPNs0E5ZBKtEgUNL4g-ghIFDZFhlU4=?alt=proto 200 244.889 ms - -
GET /__cypress/tests?p=cypress/integration/API/AP/admin/customer/deleteLogo.ts 200 1851.977 ms - -
GET /__cypress/tests?p=cypress/support/index.ts 200 3583.412 ms - -
GET /__cypress/runner/fonts/fa-regular-400.woff2 200 7.244 ms - 13600
HEAD / - - ms - -
HEAD / - - ms - -
HEAD / - - ms - -
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)

TypeError [ERR_UNKNOWN_SIGNAL] [ERR_UNKNOWN_SIGNAL]: Unknown signal: true
    at convertToValidSignal (internal/util.js:251:9)
    at ChildProcess.kill (internal/child_process.js:472:5)
    at Object.<anonymous> (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:428:43)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 {
  code: 'ERR_UNKNOWN_SIGNAL'
}
TypeError [ERR_UNKNOWN_SIGNAL] [ERR_UNKNOWN_SIGNAL]: Unknown signal: true
    at convertToValidSignal (internal/util.js:251:9)
    at ChildProcess.kill (internal/child_process.js:472:5)
    at Object.<anonymous> (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:428:43)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/home/threnode/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


Process finished with exit code 0
```

### Desired behavior
Completed xhr request.

### Test code to reproduce
Method convertObjectToFormData() just creates new FormData object, and appends key-value pairs to it.

Fairly simple workaround for sending formdata:
```
Cypress.Commands.add('requestFormData', function (method: string, url: string, obj: Record<string, any>, exp = 200) {
  cy.intercept(method, '/v1/' + url)
    .as(url)
    .then(() => {
      const xhr = new XMLHttpRequest()
      xhr.open(method, '/v1/' + url)
      xhr.send(convertObjectToFormData(obj)) **<----------- Crash happens on this line**
    })
    .wait('@' + url)
    .then(xhr => {
      if (xhr.response) {
        if (xhr.response.statusCode !== exp) {
          throw new Error(`Unexpected server response status: expected ${exp}, but got ${xhr.response.statusCode}`)
        } else {
          return xhr.response.body
        }
      } else {
        console.error(`Response for request ${url} is missing.`)
      }
    })
})
```

And a command I call:
```
Cypress.Commands.add('uploadLogo', function (id: string, fixturePath: string, fileName: string, url: string) {
  cy.fixture(fixturePath, 'binary').then(binary => {
    const file = new File([binary], fileName, {type: 'image/png'})

    cy.requestFormData('POST', url, { id, file })
  })
})
```

There is correct .png image in fixtures folder, and it is returned by cy.fixture, correctly converted into file object and appended to formdata.

### Versions
Last working on version 6.9.1, 6.8.0
Broken on 7.0.0, 7.0.1

Linux Mint 19.3 Cinnamon, kernel 5.4.0-70-generic

**Comment by Threnos** [comment] 2021-04-07 14:39
Still investigatinvg. Not all files cause this to crash. I have other similar requests that upload csv file, and they are fire. So far it shows up only with .png images.

**Comment by Threnos** [comment] 2021-04-07 14:44
I narrowed issue down to line:
```
cy.fixture(fixturePath, 'binary').then(binary => {
```

Removing 'binary' fixes the issue.

**Comment by ukjinjang** [comment] 2021-04-09 06:51
Oh, I have same issue.

When I upload jpeg file with `FormData` and `XMLHttpRequest`, it causes crash.
It worked until Cypress version 6.8.0.
 
```js
Cypress.Commands.add('uploadProfile', () => {
  // ...

  const fd = new FormData();
  fd.append('profile_file', new File([binary], 'profile.jpeg', { type: 'image/jpeg' }));

  return cy
    .wrap(
      new Cypress.Promise<string>((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open('POST', url);
        xhr.onload = () => resolve(JSON.parse(xhr.response));
        xhr.onerror = () => reject(xhr.response);
        xhr.send(fd);
      })
    )
    .then(/** codes... */)
    // ...
});
```

and...

```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/Users/ukjinjang/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)


INFO: Gracefully shutting down. Please wait...
✨  Done in 94.93s.
```

**Comment by Threnos** [comment] 2021-04-09 10:49
> I narrowed issue down to line:
> 
> ```
> cy.fixture(fixturePath, 'binary').then(binary => {
> ```
> 
> Removing 'binary' fixes the issue.

Although, removing 'binary' helped with .png files, problem still persists with .pdf.
Even more worth noting, that I have another test that sends .csv file, which goes fine **with** 'binary'.

**Comment by bahmutov** [comment] 2021-04-09 19:50
Probably the same bug as https://github.com/cypress-io/cypress/issues/15901 (where there is easily reproducible example)

**Comment by johnnyperkins** [comment] 2021-04-21 21:09
Same issue but happens when using `cy.fixture(file.name, 'base64')`

**Comment by jennifer-shehane** [comment] 2021-04-26 19:22
Duplicate of https://github.com/cypress-io/cypress/issues/15901, if this issue is not resolved when the fix for that is released, please open a new issue with a reproducible example.

**Closed by jennifer-shehane** 2021-04-26 19:22 UTC
Labels: pkg/net-stubbing

**Comment by donalmurtagh** [comment] 2021-04-27 13:17
This issue still exists in Cypress 7.2.X. In my case the file I'm attempting to uploads is an Excel file. I create the `File` object from a fixture like so
```javascript
    cy.fixture('testing.xlsx', 'binary').then((file) => {

      const fileBlob = Cypress.Blob.binaryStringToBlob(file, fileType)
      const fileToUpload = new File([fileBlob], 'testing.xlsx', { type: fileType })
      
      const requestBody = new FormData()
      requestBody.append('file', fileToUpload)

      const options = {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      }

      await http.post('/api/endpoint', requestBody, options)
    })
```

**Comment by jennifer-shehane** [comment] 2021-04-27 13:39
7.2.0 was released. Please try to update and see if the issue is resolved.

**Comment by donalmurtagh** [comment] 2021-04-27 13:45
@jennifer-shehane I've tested with 7.2.0 and the issue still exists. See [this comment](https://github.com/cypress-io/cypress/issues/15898#issuecomment-827617631) for further details

**Comment by jennifer-shehane** [comment] 2021-04-29 17:28
@donalmurtagh Yes, we're looking into it in that issue.
