### ISSUE TITLE
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

### ISSUE THREAD

**Issue by davilo61** [cypress-io/cypress#16571] opened 2021-05-18 18:46 UTC
**Current behavior:**
Cypress run fails with the following error on Chrome:
**Stack trace**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 54716.
```

**Error details:**
```
Error: connect ECONNREFUSED 127.0.0.1:54716
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Windows 10 OS build 19042.928. Chrome is up to date
Version 90.0.4430.212 (Official Build) (64-bit)
Stack trace attached.
```

**Summary**:  Same error occurs with the test runner and in headless mode. I tried a few suggested solutions found online including adding browser options to the `index.js` file, clearing the cache, closing all chrome browser windows but the issue persists. We're trying to isolate whether the issue is a dev tools setting or an organization-related block. *I noted that a new issue  was recommended if this behavior was seen in a version above 6.4
[cypress_7_3_stacktrace.txt](https://github.com/cypress-io/cypress/files/6503547/cypress_7_3_stacktrace.txt)

**Comment by jennifer-shehane** [comment] 2021-05-18 19:33
- Does this fail at the beginning of starting your run? Or are there some tests that run and then you see this error on a new specfile?
- Does this happen during `cypress open` and/or `cypress run`?
- Any information on the environment your running? This is locally on your Windows 10? Does this occur on multiple machines in your org?
- Do you have anything else connecting to CDP port?

The only situation I know this can happen is currently is if there are multiple Cypress instances open. I've also seen this happen on a first run on Windows, where there was a prompt from Windows defender or Chrome or something, asking for permissions to open Cypress/chrome which prevented it from opening, but I could visibly see this on the machine.

**Comment by davilo61** [comment] 2021-05-19 13:44
Hey thanks for the feedback: 
1. Occurs immediately after starting the run. The chrome window displays followed by a timeout error after 50 seconds. 
2. Occurs on both cypress open and cypress run. 
3. This behavior occurs on multiple windows laptops.  
4. I will check with my org. support regarding any potential restrictions due to the CDP protocol.

**Comment by anthony-sarkis** [comment] 2021-06-05 00:50
I am seeing this issue too

```
cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │    pids    │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │   '598'    │     0      │       0        │  120.82  │    120.82    │   120.82    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '610, 611' │     0      │       0        │  102.57  │    102.57    │   102.57    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '759, 760' │     0      │       0        │   3.39   │     3.39     │    3.39     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │    '-'     │     0      │       0        │  226.79  │    226.79    │   226.79    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    7.4.0                                                                              │
  │ Browser:    Chrome 90                                                                          │
  │ Specs:      14 found (diffgram/annotate_files/annotate_files_attributes_spec.js, diffgram/anno │
  │             tate_files/annotate_files_context_menu_spec.js, diffgram/annotate_files/annotate_f │
  │             iles_file_information_spec.js, diffgram/annotate_files/annotate_files_instance_dra │
  │             wing_spec.j...)                                                                    │
  │ Params:     Tag: false, Group: false, Parallel: false                                          │
  │ Run URL:    https://dashboard.cypress.io/projects/***/runs/1094                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  diffgram/annotate_files/annotate_files_attributes_spec.js                      (1 of 14)
  Estimated: 3 minutes, 35 seconds
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
Failed to connect to Chrome, retrying in 1 second (attempt 20/62)
Failed to connect to Chrome, retrying in 1 second (attempt 21/62)
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                      pids                       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'electron-shared' │      8       │ '610, 792, 611, 886, 948, 968 ... 2 more items' │     0      │       0        │  457.97  │    280.27    │   457.97    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                      '598'                      │    3.55    │      1.78      │  257.92  │    189.37    │   257.92    │
  cypress:server:util:process_profiler │    2    │      'other'      │      6       │         '940, 945, 946, 950, 988, 989'          │     0      │       0        │  121.26  │    62.32     │   121.26    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │                      '909'                      │     0      │       0        │  106.35  │    106.35    │   106.35    │
  cypress:server:util:process_profiler │    4    │     'ffmpeg'      │      1       │                      '939'                      │     0      │       0        │  13.12   │    13.12     │    13.12    │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      17      │                       '-'                       │    3.55    │      1.78      │  956.62  │    591.71    │   956.62    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
Failed to connect to Chrome, retrying in 1 second (attempt 22/62)
Failed to connect to Chrome, retrying in 1 second (attempt 23/62)
Failed to connect to Chrome, retrying in 1 second (attempt 49/62)
Failed to connect to Chrome, retrying in 1 second (attempt 50/62)
Failed to connect to Chrome, retrying in 1 second (attempt 51/62)
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                      pids                       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'electron-shared' │      8       │ '610, 792, 611, 886, 948, 968 ... 2 more items' │     0      │       0        │  461.96  │    387.69    │   461.96    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                      '598'                      │    0.12    │      0.92      │  226.29  │    211.2     │   257.92    │
  cypress:server:util:process_profiler │    2    │      'other'      │      6       │        '940, 945, 946, 950, 1111, 1112'         │    0.01    │       0        │  122.01  │     97.8     │   122.01    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │                      '909'                      │     0      │      0.02      │  104.46  │    104.93    │   106.35    │
  cypress:server:util:process_profiler │    4    │     'ffmpeg'      │      1       │                      '939'                      │     0      │       0        │  13.12   │    13.12     │    13.12    │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      17      │                       '-'                       │    0.14    │      0.94      │  927.84  │    791.13    │   956.62    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
Failed to connect to Chrome, retrying in 1 second (attempt 52/62)
Failed to connect to Chrome, retrying in 1 second (attempt 53/62)
Failed to connect to Chrome, retrying in 1 second (attempt 54/62)
Failed to connect to Chrome, retrying in 1 second (attempt 55/62)
Failed to connect to Chrome, retrying in 1 second (attempt 56/62)
Failed to connect to Chrome, retrying in 1 second (attempt 57/62)
Failed to connect to Chrome, retrying in 1 second (attempt 58/62)
Failed to connect to Chrome, retrying in 1 second (attempt 59/62)
Failed to connect to Chrome, retrying in 1 second (attempt 60/62)
[2021-06-05 00:36:38,786] INFO regular_methods.py Line 184: [SyncActions Queue heartbeat]49
Failed to connect to Chrome, retrying in 1 second (attempt 61/62)
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                      pids                       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'electron-shared' │      8       │ '610, 792, 611, 886, 948, 968 ... 2 more items' │     0      │       0        │  461.96  │    400.07    │   461.96    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                      '598'                      │    0.12    │      0.79      │  226.43  │    213.73    │   257.92    │
  cypress:server:util:process_profiler │    2    │      'other'      │      6       │        '940, 945, 946, 950, 1152, 1153'         │     0      │       0        │  121.84  │    101.81    │   122.01    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │                      '909'                      │     0      │      0.01      │  104.46  │    104.84    │   106.35    │
  cypress:server:util:process_profiler │    4    │     'ffmpeg'      │      1       │                      '939'                      │     0      │       0        │  13.12   │    13.12     │    13.12    │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      17      │                       '-'                       │    0.12    │      0.8       │  927.81  │    813.91    │   956.62    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
Failed to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 38607.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:38607
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
From previous event:
    at _connectAsync (/github/home/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:31:31)
    at Object.getWsTargetFor (/github/home/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:86:12)
    at Object._connectToChromeRemoteInterface (/github/home/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:234:21)
    at Object.<anonymous> (/github/home/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:425:42)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/github/home/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:24:58)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by jennifer-shehane** [comment] 2021-06-11 16:47
Going to close as duplicate of https://github.com/cypress-io/cypress/issues/15650

**Closed by jennifer-shehane** 2021-06-11 16:47 UTC
Labels: stage: needs information
