### ISSUE TITLE
Cypress Version: 3.1.1 fails to start on windows

### ISSUE THREAD

**Issue by freemaths** [cypress-io/cypress#2743] opened 2018-11-08 17:01 UTC
"npx cypress open" gives the following error after upgrading to version 3.1.1 (3.1.0 suggests to update)
When I unistall and re-install cypress@3.1.0 all is fine again.

```
Cypress Version: 3.1.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: C:\Users\Ed\AppData\Local\Cypress\Cache\3.1.1\Cypress\Cypress.exe --smoke-test --ping=922
----------
```

Platform: win32 (10.0.17134)
Cypress Version: 3.1.1

**Comment by jennifer-shehane** [comment] 2018-11-08 18:31
Duplicate of https://github.com/cypress-io/cypress/issues/1866

**Closed by jennifer-shehane** 2018-11-08 18:31 UTC

**Comment by freemaths** [comment] 2018-11-10 20:01
I suspect this is not a duplicate. Same symptom but this is a problem with the very latest release.
I tried re-installing 3.1.1 twice. 3.1.1 breaks. 3.1.0 is fine.

**Comment by dirtyredz** [comment] 2018-12-15 01:58
im having this issue on version 3.1.3
![capture](https://user-images.githubusercontent.com/7119499/50037797-9c989980-ffda-11e8-9bde-eb591a9abfb9.PNG)
