### ISSUE TITLE
Cypress 9.5.2 runner is crashing in MacOS 12.2.1 when closing runner. 

### ISSUE THREAD

**Issue by pokaalinkanssayohon** [cypress-io/cypress#20679] opened 2022-03-18 07:35 UTC
### Current behavior

Crash is appearing:
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

### Desired behavior

No crashes

### Test code to reproduce

open cypress runner and close it.

The Test Runner unexpectedly exited via a exit event with signal SIGABRT

----------

Platform: darwin-x64 (21.3.0)
Cypress Version: 9.5.2

### Cypress Version

9.5.2

**Comment by emilyrohrbough** [comment] 2022-03-18 13:36
@pokaalinkanssayohon thank you for logging this issue. It appears to be a duplicate of #https://github.com/cypress-io/cypress/issues/17849. I'm going to close this in favor of the existing information to keep details in one place. Please add your OS information in a comment.

**Closed by emilyrohrbough** 2022-03-18 13:36 UTC
