### ISSUE TITLE
Cypress error while running Sample Test. Cypress crashed and shows error ECONNRESET

### ISSUE THREAD

**Issue by Pratyushwildnet** [cypress-io/cypress#14908] opened 2021-02-04 00:52 UTC
Please help if anyone knows how to resolve this error.

When I tried to run the cypress Sample Test it crashed and showing the error below :
```
Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27) { 
  errno: 'ECONNRESET', 
  code: 'ECONNRESET', 
  syscall: 'read' 
} 
Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
```

I am using cypress the first time. so please If anyone knows please help.

When I run the same in Macbook then it's working fine but not for windows.

Nodejs: 12.14.0 windows: 10

**Comment by Pratyushwildnet** [comment] 2021-02-04 00:54
@jennifer-shehane  Please help me with this issue as I am trying to resolve it but till now no result.

**Comment by jennifer-shehane** [comment] 2021-02-04 04:50
Duplicate of https://github.com/cypress-io/cypress/issues/14175

**Closed by jennifer-shehane** 2021-02-04 04:50 UTC
Labels: topic: installation

**Comment by jbarrios2623** [comment] 2022-03-15 18:20
@jennifer-shehane  You have given us no solution. Just have been redirecting us to another Ticket with no solution. Can you please help us figure it out or hopefully direct us to someone who can help? @cypress-github-team-services-sa
