### ISSUE TITLE
Re-run only failed tests

### ISSUE THREAD

**Issue by renanleandrof** [cypress-io/cypress#6614] opened 2020-03-02 17:09 UTC
Sometimes, when we change some code, some tests will break, and we need to run only the failed tests, one by one, to check if it's fixed, before running everything again.

On big projects with lots of tests, running all tests multiple times it's impossible... Re-run failed tests should be a feature!

**Comment by jennifer-shehane** [comment] 2020-03-03 09:00
Duplicate of #4886

**Closed by jennifer-shehane** 2020-03-03 09:00 UTC
