### ISSUE TITLE
Screenshot support capture full screen.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#8643] opened 2020-09-23 03:38 UTC
### Current behavior
When test case fail, cypress will capture screenshot only visible region.

### Desired behavior
Support capture full screen (app preview).  In some case, error happened in invisible region, capture full screen maybe will get it.

<img width="989" alt="截屏2020-09-23 上午11 35 34" src="https://user-images.githubusercontent.com/22906174/93963909-ec4feb80-fd90-11ea-951a-477018f256ef.png">

Set an environment variable in cypress.json, like: screenshotsFullScreen, default is false, capture full screen when it is true.

### Versions
Cypress4.10.0

**Comment by bahmutov** [comment] 2020-09-23 14:25
I would mark it as a feature but would think this is a low priority since we would expect the error to more likely manifest itself in the command log.

**Comment by jennifer-shehane** [comment] 2020-10-15 00:40
Duplicate of https://github.com/cypress-io/cypress/issues/5920

**Closed by jennifer-shehane** 2020-10-15 00:40 UTC
Labels: topic: screenshots 📸, type: enhancement
