### ISSUE TITLE
Fixtures do not seem to be avaiable to all it() when loaded in before(). Required  to load them in beforeEach()

### ISSUE THREAD

**Issue by janusqa** [cypress-io/cypress#3839] opened 2019-03-28 00:32 UTC
### Current behavior:
fixtures loaded in `before()` seem only available to the first `it()`. In order to access a fixture in any other `it()` it seems that you are required to load it in `beforeEach`

### Desired behavior:

fixture loaded in `before` should be available to any `it()`

### Steps to reproduce: (app code and test code)

https://github.com/janusqa/fixturesinbefore 

```cypress run``` to see error, then you can move loading fixture to ```beforeEach``` to see no error.

### Versions

Linux: Ubuntu 18.04
Cypress package version: 3.1.5
Cypress binary version: 3.1.5

**Comment by jennifer-shehane** [comment] 2019-03-28 05:30
Duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2019-03-28 05:30 UTC
