### ISSUE TITLE
cannot override default yield of .within() in cypress 5.4.0

### ISSUE THREAD

**Issue by gustaferiksson** [cypress-io/cypress#8888] opened 2020-10-19 17:04 UTC
### Current behavior

Putting a `return` inside a `.within()` doesn't have any effect. `.within()` yields what the previous command returned no matter what.

### Desired behavior

The `.within()` should return whatever you tell it to return

### Test code to reproduce

In cypress `5.4.0` (current behavior)
```js
cy.get('body').within(() => {
    return cy.wrap(1)
}).then((res) => {
    console.log(res)        // jQuery.fn.init [body, prevObject: jQuery.fn.init(1), selector: "body"]
})
```

In cypress `5.3.0` (desired behavior)
```js
cy.get('body').within(() => {
    return cy.wrap(1)
}).then((res) => {
    console.log(res)        // 1
})
```

### Versions

Cypress 5.4.0

**Comment by jennifer-shehane** [comment] 2020-10-20 11:28
`.within()` is documented and intended to always yield the subject that was given to it originally, so the return value currently would have no effect on the next chained command. See https://on.cypress.io/within#Yields

In 5.4.0 we fixed an issue where the original subject would not be returned, so now consider this to be working as intended. See the PR: https://github.com/cypress-io/cypress/pull/8699

Closing as this is working as designed.

**Closed by jennifer-shehane** 2020-10-20 11:28 UTC
