### ISSUE TITLE
Cypress tells Input is disabled, but it isn't, while typing

### ISSUE THREAD

**Issue by mszkudelski** [cypress-io/cypress#5827] opened 2019-11-29 10:40 UTC
### Current behavior:

I'd like to test login page on Ionic (v3) website. But when I invoke method `.type` there appears error:

```
CypressError: cy.type() failed because it targeted a disabled element.
```

Error does not occurs always. Test fails is about 20-25% runs. Analysing Cypress' source code I realized that it can behave that way because Input is not focused. I was looking at file: https://github.com/cypress-io/cypress/blob/70ef58bede981567732697c8b79fe7642ab164cf/packages/driver/src/cy/commands/actions/type.js from 407 line. 

So I added method `.focus` before `.type`. But then I am given another error: 

```
CypressError: Timed out retrying: expected '<input.text-input.text-input-md>' to have value 'asdasddd', but the value was 'adasddd'
```

which means that not every character was typed into input (propably every, but not second)

### Desired behavior:

I assume that I have done everything right, and there is no problem with my website, so expected result would be not to got any error using method `.type`. Otherwise, please tell if I'm doing anything incorrect

### Steps to reproduce: (app code and test code)

Here is reproduction project that test my application:

https://github.com/mszkudelski/cypress-bug-repro

You can use npm script or use my bash `script.sh` that runs spec 20 times and log result in `log.txt` file.

### Versions

Cypress: 3.6.1, 
operating system: MacOs 10.15.1 
browser: Electron headless and Chrome

**Comment by jennifer-shehane** [comment] 2019-12-03 09:31
Hey @mszkudelski, I eventually got this to fail on a run within Chrome in Cypress 3.6.1 during `cypress open`

![Screen Shot 2019-12-03 at 3 45 08 PM](https://user-images.githubusercontent.com/1271364/70036833-e7446480-15e3-11ea-9349-8fc7c53f6017.png)

I was not able to replicate this in 3.7.0 (but it's difficult since it's intermittent and I have to reun many times), can you confirm if you have seen this error in 3.7.0?

**Comment by Gerros** [comment] 2019-12-03 10:21
I have the same problem with an input field in version 3.7.0 when running tests with cypress run, with cypress open it works

**Comment by mszkudelski** [comment] 2019-12-05 10:47
Hi @jennifer-shehane, I'm sorry for mistake, but in reproduction project I use 3.7.0 version of Cypress. So bug appears in version 3.6.1 (in my real project) and 3.7.0 (in repro project).

**Comment by jure** [comment] 2019-12-05 16:48
Looks similar to #5830, #5743 and maybe a few others. For what it's worth, we're also seeing this intermittently. Tiptoeing around it with `click().wait().focus().wait()` does not help, and the element is clearly visible and not disabled.

**Comment by kevinpainchaud** [comment] 2019-12-12 09:22
Hi,
I confirm that I have the same problem from 3.5.0 to 3.7.0.
It also appears randomly.
I hope a solution can be found.

**Comment by raphaelyancey** [comment] 2019-12-30 15:54
Same with 3.8.1, seems to be random.

**Comment by Saharshdeep** [comment] 2020-01-27 10:38
I was also getting the same issue and tried all the above possible workarounds. The solution that worked for me was using click with force: true option, before every type operation.
![image](https://user-images.githubusercontent.com/60344478/73168103-2d6aff80-411f-11ea-8be9-bb7a9f0557d1.png)

**Comment by kevinpainchaud** [comment] 2020-02-21 15:34
After investigation, I think I have found the reason that causes this error.

When Cypress wishes to type into an input, it scrolls first to it.
However, in my case, the page header becomes sticky at scroll.
And it covers part of the input, which causes this error.

To be sure, I tried to delete this sticky header and then restart my tests.
Everything was ok, no more errors related to the input ...

**Comment by scridget** [comment] 2020-03-31 03:27
Just tacking onto this if anybody experiences this from the cypress ui - I found that, for whatever reason, if I disable/enable the auto scrolling toggle, it will successfully run. I have to do this each time I re-run a test :/ but it's getting me through!

**Comment by petermartin2002** [comment] 2020-04-02 11:56
@jennifer-shehane I am seeing this frustratingly frequently when working with long iframes. 

Is there a potential targeted release for this defect?

**Comment by petermartin2002** [comment] 2020-04-03 11:37
> After investigation, I think I have found the reason that causes this error.
> 
> When Cypress wishes to type into an input, it scrolls first to it.
> However, in my case, the page header becomes sticky at scroll.
> And it covers part of the input, which causes this error.
> 
> To be sure, I tried to delete this sticky header and then restart my tests.
> Everything was ok, no more errors related to the input ...

Can you please share the code you used to delete the header?

**Comment by kevinpainchaud** [comment] 2020-04-03 12:23
It looks like this:

```
it("My page", () => {
  cy.on("window:load", () => Cypress.$("header").remove());

  // My tests...
});
```

**Comment by petermartin2002** [comment] 2020-04-03 12:45
Thank you very much however this is not resolving the issue for me.

I shall await Cypress releasing a fix version for this issue

**Comment by brunodbo** [comment] 2020-04-16 01:06
The workaround mentioned by @scridget in https://github.com/cypress-io/cypress/issues/5827#issuecomment-606377029 worked for me too.

**Comment by proIT324** [comment] 2020-05-11 13:10
I have the same issue now. Cypress v4.5.0 is installed in my project and the same error with input typing test case occurs. I'm looking forward to the fixed version. 😄

**Comment by mjlucca** [comment] 2020-05-28 14:21
I got it solved on Cypress V4.5.0 by adding a .focus() before typing.
Actually added focus().should('be.enabled').type('Something')

**Comment by MaximeCheramy** [comment] 2020-06-01 12:06
I have the same issue with cypress 4.7.0. The `focus().should('be.enabled')` didn't work for me unfortunately.

**Comment by nicolasraviolo** [comment] 2020-07-28 14:37
{ force: true } worked for me, thanks!

**Comment by petermartin2002** [comment] 2020-07-28 14:56
I have bypassed type and I am instead using invoke("text") with args to set the text of the text box as opposed to type.  It is a workaround on text boxes that I find to be continually problematic

**Comment by samRC** [comment] 2020-08-08 11:57
Encountered this same issue with Cypress 4.11.0. 
The other workarounds didn't seem to work for me. 
But adding a small wait `cy.wait(500)` before issuing the _type_ command, **fixed it for me**.

**Comment by samRC** [comment] 2020-08-08 12:02
Encountered this same issue with Cypress 4.11.0. 
The other workarounds didn't seem to work for me. 
But **adding a small wait** `cy.wait(500)` before issuing the _type_ command, **fixed it for me**.

**Comment by sainthkh** [comment] 2020-08-19 08:06
The cause of the problem is that the app is not fully loaded. 

One of the workaround is to use `cy.wait(500)` like @samRC mentioned.

**Comment by siphiwe** [comment] 2020-09-15 06:06
Just experienced this in  5.1.0 :(

**Comment by jyotsana-khaparde** [comment] 2020-09-29 12:46
Hey, i was having same issue for me this worked -> 
**cy.xpath("<YOUR_XPATH>").click({ force: true})
cy.xpath("<YOUR_XPATH>").type("<YOUR_TEXT>");**

**Comment by Nxtra** [comment] 2020-10-14 09:19
If this is a Cypress issue, I think it's quite bothersome. The issue stays alive over multiple cypress versions already.
What is the definite solution that works for version 5.3.0? I try all of the above and they still fail from time to time.

**Comment by Arturace** [comment] 2020-10-22 14:08
I encouter this issue frequently in inputs inside of an open shadow dom. `focus()` does not solve the issue, but focing it does.

**Comment by DharaniY** [comment] 2020-10-26 17:15
I am using the 5.4.0 version, I had the same issue when I tried to emulate the device iPhone x etc, the workaround mentioned by @Saharshdeep is worked for me.
ex:
    cy.get("#sku-search-txt").click({ force: true });
    cy.get("#sku-search-txt").clear({ force: true });

**Comment by aamiriqubal** [comment] 2020-11-16 16:33
I made a work around for this problem, this problem mostly seems to happen when you try to type into an input box right after typing in an input box
```
cy.get("firstInputSelector").type("My First Input text");
cy.get("someHeaderSelector").clear({ force: true }); // A force click somewhere outside the form
cy.wait(200);
cy.get("secondInputSelector").type("My Second Input text");
```
This solution works smoothly for me and the tests don't break intermittently.

**Comment by 1ratnesh1** [comment] 2020-11-27 10:10
I was facing this exact issue. What I did is here -
```
cy.get('input[name="password"]').click()
cy.get('input[name="password"]').type(password)

```
This works totally fine.

**Comment by Reshma155** [comment] 2020-12-25 05:07
Email TextBox is hidden ,also it parent is hidden 
cy.get(":nth-child(2) > :nth-child(1) > :nth-child(1) > .cognito-asf > :nth-child(3) > #signInFormUsername").should('be.visible').click({force:true});
        cy.get(":nth-child(2) > :nth-child(1) > :nth-child(1) > .cognito-asf > :nth-child(3) > #signInFormUsername").type(this.data.Email);

**Comment by jennifer-shehane** [comment] 2020-12-29 08:35
There has been one reproducible example given in this issue: https://github.com/mszkudelski/cypress-bug-repro. That issue is due to the timing when loading the page. When the input is attempted to be typed into - the element is disabled. If you throw a debugger right were we check the disabled attribute - you can see the element is not finished rendering to the page.

This is not an issue with Cypress that we can solve on our side. Cypress has no way of knowing whether the page is fully loaded - intended for a user to type or not.

**If you have an issue that you think falls outside of this example, please provide a reproducible example so that we can evaluate and see whether there is a bug with Cypress falsely attributing an input as disabled at the time of the action.**

At the moment, this will be closed as 'wontfix' from the example provided.

<img width="1425" alt="Screen Shot 2020-12-29 at 2 53 50 PM" src="https://user-images.githubusercontent.com/1271364/103270336-07607600-49e6-11eb-86cc-e07be81a7092.png">


```js
it('test ', function () {
    cy.visit('https://app.bas24.pl/');
    cy.location('href').should('contain', 'app.bas24.pl');
    cy.get('input[name="username"]')
    .type('a').should('have.value', 'a')
});
```

### Recommendation

 So, some ways to test this are to:

- Ensure that the element is not disabled at the time you intend to type into the field by asserting that it is not disabled.

```js
cy.get('input[name="username"]')
  .should('not.be.disabled')
  .type('asdasddd')
```

- Force type into the element (not recommended over the approach above)

```js
cy.get('input[name="username"]')
  .should('not.be.disabled')
  .type('asdasddd', { force: true })
```

- Add some other assertion that would ensure page is loaded before continuing.

**Closed by jennifer-shehane** 2020-12-29 08:35 UTC
Labels: existing workaround, stage: ready for work, topic: cy.type ⌨️, type: bug

**Comment by phpworker** [comment] 2021-01-07 12:07
> Just tacking onto this if anybody experiences this from the cypress ui - I found that, for whatever reason, if I disable/enable the auto scrolling toggle, it will successfully run. I have to do this each time I re-run a test :/ but it's getting me through!

worked for me! Thanks!

**Comment by snake-py** [comment] 2022-02-11 09:34
Okay, I think I might have something where this falls out of line 
![image](https://user-images.githubusercontent.com/59285387/153568105-521702f1-3860-4a09-95b6-673f0a3e21d1.png)

**Comment by ashblox** [comment] 2022-03-18 18:05
Seeing this also:

![image](https://user-images.githubusercontent.com/47283036/159058918-ab4a6ac2-344f-4bb5-baa7-67780dce8eb8.png)

**Comment by ABDERRAHMANE-OUALI** [comment] 2023-07-06 18:51
I Solved the issue with adding `{force: true}` in `type()`

`cy.get('[aria-label="emailInput"]').type(`email@gmail.com`, {force: true})`

**Comment by TestIsTest001** [comment] 2024-05-09 13:10
This issue is still present in 13.7.3..The element is clearly not disabled but when typing on it it says the element is disabled.

**Comment by gnsoria** [comment] 2024-07-18 01:43
I am also running into this in Cypress 13.9.0. Tl;dr: The solution for me was to add waits before the type call, since my React app was still re-rendering and Cypress wasn't waiting for it.

Ironically, I tried calling `should("not.be.disabled")` first, which passes, but when I get to `type()` I get this failure:
```
cy.type() failed because it targeted a disabled element.

The element typed into was:

> <input name="runtime" data-value="" test-id="runtime" min="0" step="1" inputmode="decimal" type="number" id="runtime" class="form-control" value="">

Ensure the element does not have an attribute named disabled before typing into it.[Learn more](https://on.cypress.io/type)
```

This error is even more frustrating because Cypress is showing me that the element does not have the `disabled` attr but failing because it says it does.

In my case, it appears to be because my React app is re-rendering and Cypress gets lost in the mix somewhere. At no point during my render is that input disabled, but if I include hard waits to ensure that the page is done rendering, it passes. Given Cypress's emphasis on not needing to explicitly wait for things, this is not what I expected to have to do.

**Comment by vincezipparro** [comment] 2024-12-13 21:17
Having the same issue here as well. I make an assertion to check if its enabled, and it passes but still thinks the element is disabled 
![image](https://github.com/user-attachments/assets/36d84948-6d2a-4127-920e-a54780fa3c3a)
