### ISSUE TITLE
Not able to import an Excel file when using Cypress

### ISSUE THREAD

**Issue by gpenafib** [cypress-io/cypress#1594] opened 2018-04-15 17:35 UTC
Hi, I am trying to automate with Cypress the step where the user imports an Excel file, but I am not able to see how to do it with Cypress. 

What is the syntax of the command to import an Excel file that is on my desktop?

Anyone can support?
Many thanks.

**Comment by gpenafib** [comment] 2018-04-18 07:12
anyone knows? any comment? I need to know this asap please!

**Comment by jennifer-shehane** [comment] 2018-04-18 19:02
Could you provide some of the test code you already tried to get this file upload working for you application? 

There are a few examples on file uploads here also: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/file-upload-react

We are a small team and have many considerations on what issues we work on and when. We can prioritize bug fixes, do screensharing, and code reviews under our premium support. If you’re interested in this kind of premium support, please let us know by emailing support@cypress.io.

**Comment by jennifer-shehane** [comment] 2019-02-25 15:07
Duplicate of https://github.com/cypress-io/cypress/issues/1594

**Closed by jennifer-shehane** 2019-02-25 15:07 UTC
Labels: type: question

**Comment by khine-shwezin** [comment] 2019-12-17 10:19
Hi Cypress team, 
In step 1, trying to upload the excel file into the web application, using Cypress, which will then parse the content of excel file in further process, I face the issue that the content of the excel file seems being corrupted, although **_the file upload is successful_**. Without encoding value added in the code, it does not work. 
xlsx is its original format, but i also tried with csv formatted file in uploading, but still content seems being corrupted too. My excel file has some html content, but it should not be the case I guess. 

Error is
 'You\'re trying to decode an invalid JSON String: \n\nThis error originated from your application code, not from Cypress.'

In step 2, after uploading that excel file through Cypress, I download it manually and open it with Excel program, but Excel prompts that the file is corrupted.

Code is here. Hoping to get the suggestion. 
Thanks.

import 'cypress-file-upload';
..
     cy.get('#upload-btn).click();
     cy.fixture(fileName)
     .then(fileContent => {
       cy.get(selector)
         .upload({ fileContent, fileName, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', encoding: 'utf-8'}, { subjectType: 'input' })
       }).then(v => {
         cy.get("#button-1073-btnInnerEl").should('be.visible').click();
       });

Note:
mimeType:'application/vnd.ms-excel' also causes the same issue.

**Comment by mohitsingla1** [comment] 2019-12-19 08:55
@khine-shwezin 

Try with this code for Excel :-
Cypress.Commands.add('upload_file', (fileName, fileType, selector) => {
	 fileName = 'OrgAndCampusUserLoad.xls';
	 selector='#file_0';
	 fileType='application/vnd.ms-excel'

    cy.get(selector).then(subject => {
        cy.fixture(fileName, 'hex').then((fileHex) => {

            const fileBytes = hexStringToByte(fileHex);
            const testFile = new File([fileBytes], fileName, {
                type: fileType
            });
            const dataTransfer = new DataTransfer()
            const el = subject[0]

            dataTransfer.items.add(testFile)
            el.files = dataTransfer.files
        })
    })
})

// UTILS
function hexStringToByte(str) {
    if (!str) {
        return new Uint8Array();
    }

    var a = [];
    for (var i = 0, len = str.length; i < len; i += 2) {
        a.push(parseInt(str.substr(i, 2), 16));
    }

    return new Uint8Array(a);
}

**Comment by SornaSundaram** [comment] 2020-02-16 20:50
hi cypress team even after using the suggested above code still issue exist . it is not uploading the file. previously it uploads the file but it was corrupted . please suggest a hint what i am missing . thank you.

**Comment by saschahofmann** [comment] 2020-02-19 10:46
I am observing a similar behaviour as @SornaSundaram . With the code from @mohitsingla1 the input field is never updated to reflect that the file has been uploaded. 

We are using *cypress-file-upload* and it works perfectly for CSVs. As @khine-shwezin mentions for excel you need to specify the encoding for the file to be uploaded. The upload only finished with an 'utf8' encoding but the resulting file is corrupted. If I try something else e.g. 'binary'  I get an ```InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded contains characters outside of the Latin1 range.```

**Comment by saschahofmann** [comment] 2020-02-19 11:35
Ok. So it seems like the issue with the alternative code was a result from our implementation of the input field. We were using the input field with `display: 'none'`. I assume this prevented the change event to be triggered. I now do this manually by adding `cy.wrap(subject).trigger('change', { force: true })` to the new cypress command. 

*Note:* It's important to add it outside the fixture clause otherwise you are running into a sync/async mixture error.

**Updated code example**

```Cypress.Commands.add('upload_file', (fileName, selector) => {
  const fileType = 'application/vnd.ms-excel'

  cy.get(selector).then(subject => {
    cy.fixture(fileName, 'hex').then(fileHex => {
      const fileBytes = hexStringToByte(fileHex)
      const testFile = new File([fileBytes], fileName, {
        type: fileType
      })
      const dataTransfer = new DataTransfer()
      const el = subject[0]
      dataTransfer.items.add(testFile)
      el.files = dataTransfer.files
      return subject
    })
    cy.wrap(subject).trigger('change', { force: true })
  })
})```

**Comment by saschahofmann** [comment] 2020-02-19 11:45
Ok I also just stumbled over this issue abramenal/cypress-file-upload#102. In short: adding the `binary` flag and a `.then(Cypress.Blob.binaryStringToBlob)` to my fixture command was enough to make it work with cypress-file-upload.

**Comment by SornaSundaram** [comment] 2020-02-20 11:22
Thank you so much for the response and clarifying @saschahofmann . i have a doubt regarding implementation . can you explain in simple terms why we are using this approach and about the code snippet above . its advanced for a beginner like me .thanks for your time.

**Comment by saschahofmann** [comment] 2020-02-20 13:46
Uff. I am not sure whether I am well equipped to give an into depth explanation but let's see. 
If you want to use `cypress-file-upload`, you can do it like that:
```javascript
    cy.fixture('test.xlsx', 'binary')
      .then(Cypress.Blob.binaryStringToBlob)
      .then(fileContent => {
        cy.get('input[type=file]').upload({
          fileContent,
          fileName: 'test.xlsx',
          mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          encoding: 'utf8'
        })
      })```

Your test file needs to be in the *cypress/fixtures/* directory. We specify to read it as binary encoded in the fixture command and then convert that binary string to a blob which seems to help `cypress-file-upload` to the file. Then we only need to specify the mimeType (Note: you might need to change it if you are reading an *xls*) and encoding for `cypress-file-upload` and voila it works (for me). 

Also check out the linked github issue.

**Comment by soniahms** [comment] 2020-02-26 12:57
Why it doesnt support .xlsm ? any way to upload .xslm ?
