### ISSUE TITLE
3.3.2 Environmnent variable via ENVIRONMENT_* is not read

### ISSUE THREAD

**Issue by wulfovitch** [cypress-io/cypress#4634] opened 2019-07-02 15:15 UTC
### Current behavior:

I have set a environment variable via `CYPRESS_variable_name`. I've setup the same variable name in the cypress.json via `variable_name`.
In 3.3.2 the value from cypress.json is chosen. In previous releases the environment variable has had a higher preference.

### Desired behavior:

Environment variables with the same name should have the higher preference than the setting in cypress.json.

**Comment by jennifer-shehane** [comment] 2019-07-03 04:53
Hey @wulfovitch, can you look at the [resolved configuration](https://on.cypress.io/configuration#Resolved-Configuration) to verify which is taking precedence? 

Also, can you provide the name of the `variable_name` you are setting? It may be relevant since we have tests around this and haven't seen this behavior. 

![](https://docs.cypress.io/img/guides/configuration/see-resolved-configuration.d6407c4c.jpg)

We added a new env variable in 3.3.2 which I know touched some of this code. It's the only thing I can think that may have caused a bug to be introduced. https://github.com/cypress-io/cypress/pull/4431

**Comment by jennifer-shehane** [comment] 2019-12-10 07:44
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-12-10 07:44 UTC
