### ISSUE TITLE
Component testing with Vite is failing due to the outdated bundled `graceful-fs` version

### ISSUE THREAD

**Issue by sodatea** [cypress-io/cypress#19610] opened 2022-01-07 06:32 UTC
### Current behavior

Component testing with Vite in new projects doesn't work.
There will be errors like:
```
[vite] Internal server error: Cannot read properties of undefined (reading 'uid') Failed to fetch dynamically imported module: http://localhost:3001/src/components/__tests__/HelloWorld.spec.js?import
```

The direct cause is the latest version of `resolve`. It exposes a bug in older versions of `graceful-fs`.
Because Cypress bundles `graceful-fs` by itself, there seems no way for users to fix it by themselves.

More technical details is explained at https://github.com/browserify/resolve/issues/264#issuecomment-1006948040

### Desired behavior

Update the bundled `graceful-fs` version to >= 4.2.9

### Test code to reproduce

https://github.com/robyedlin/vue3-starter

### Cypress Version

9.2.0

**Comment by sainthkh** [comment] 2022-01-10 01:08
Confirmed that it doesn't work. Thanks for the reproducible example.

**Comment by ljharb** [comment] 2022-01-10 06:53
A better solution than just updating the bundled version is to not bundle dependencies at all :-)

**Comment by NitinMalave20** [comment] 2022-01-10 12:12
Using **Cypress 8.7.0 in Angular 12.2.0** application & I have been facing the similar issue since last 3 days. Please let me know in case any fix exist for the issue. 

I think it is due to incompatibility caused by upgradation of internal packages i.e. of `**graceful-fs**` & `**resolve**` , Any help would be appreciated on the issue, Thanks.

Attaching the detail log of the issue

`
The function exported by the plugins file threw an error.

We invoked the function exported by `C:\\\\\e2e\cypress\plugins\index.js`, but it threw an error.

 TypeError: Cannot read properties of undefined (reading 'uid')
    at Object.statSync (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:303:17)
    at isDirectory (C:\\Development\rs-iot-client-ng-latest\rs-iot-client-ng\node_modules\resolve\lib\sync.js:22:23)        
    at loadNodeModulesSync (C:\\Development\rs-iot-client-ng-latest\rs-iot-client-ng\node_modules\resolve\lib\sync.js:191:17)
    at Function.resolveSync [as sync] (C:\\node_modules\resolve\lib\sync.js:98:17)
    at module.exports (C:\\\\e2e\cypress\plugins\index.js:8:25)
    at C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:90:12
    at tryCatcher (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)       
    at Function.Promise.attempt.Promise.try (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at load (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:87:7)
    at EventEmitter.<anonymous> (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:198:5) 
    at EventEmitter.emit (events.js:376:20)
    at process.<anonymous> (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at process.emit (events.js:376:20)
    at process.emit (C:\\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\source-map-support\source-map-support.js:495:21)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
`

**Comment by bhvngt** [comment] 2022-01-11 13:37
Any update on this issue? This is breaking even the older version of cypress possibly due to buggy [dependency](https://github.com/isaacs/node-graceful-fs/pull/220). In the long term, it might help to remove this dependency as the author [suggest](https://github.com/isaacs/node-graceful-fs/pull/220#issuecomment-1005302925)

**Comment by yeongsheng-tan** [comment] 2022-01-11 13:59
You may force the transitive dependency of resolve to version 1.20.0 in your package.json.
E.g.:

```
  "devDependencies": {
    "@testing-library/cypress": "8.0.2",
    "@types/node": "^17.0.2",
    "browserify": "^17.0.0",
    "cy-verify-downloads": "^0.0.5",
    "cypress": "9.2.1",
    "cypress-cucumber-preprocessor": "4.3.1",
    "cypress-file-upload": "5.0.8",
    "file-saver": "^2.0.5",
    "got": "^12.0.1",
    "npm-run-all": "4.1.5",
    "prettier": "^2.5.0",
    "tsify": "5.0.4",
    "typescript": "^3.9"
  },
  "resolutions": {
    "resolve": "1.20.0"
  }
```

**Comment by ljharb** [comment] 2022-01-11 15:06
That’s not a helpful suggestion.

You can use next@12.0.8-canary, 19 or higher, and it should be fixed.

**Comment by bhvngt** [comment] 2022-01-11 15:40
Since this the dependencies are bundled up with cypress app, the overrides in local `package.json` will not work in this case.

@ljharb I am using svelte. In any case it does not matter because of the above reason.

**Comment by ljharb** [comment] 2022-01-11 15:42
@bhvngt ah, and does svelte bundle graceful-fs also? If so, can you link me to the issue filed on it? (or does svelte depend on cypress which bundles it, and that’s the problem)

**Comment by bhvngt** [comment] 2022-01-11 17:00
@ljharb  the issue has nothing to do with svelte. 

In my case it is getting thrown from the Cypress app bundle. Cypress app bundles graceful-fs from where this error is thrown...

**Comment by ljharb** [comment] 2022-01-11 17:02
then in that case, i hope cypress fixes it soon.

**Comment by erikrahm** [comment] 2022-01-11 21:20
Any update on this? Happening for me as well using cypress w/ react

**Comment by bhvngt** [comment] 2022-01-12 10:40
Code digging suggests that [graceful-fs](https://github.com/cypress-io/cypress/blob/0382768981bd68695ca498cfb52107c4748c9489/packages/server/package.json#L68) package installed under [server](https://github.com/cypress-io/cypress/tree/develop/packages/server) throws this error. It needs to be upgraded to `4.2.9`.

**Comment by Assael1** [comment] 2022-01-12 12:17
Is there something i can do for now? someone found a work around until it's fixed?

**Comment by mjhenkes** [comment] 2022-01-12 16:19
PR to update graceful-fs version: #19676

**Comment by chrisbreiding** [comment] 2022-01-18 16:49
The code for this is done, but has yet to be released. We'll update this issue and reference the [changelog](https://docs.cypress.io/guides/references/changelog) when it's released.

**Closed by chrisbreiding** 2022-01-18 16:49 UTC
Labels: stage: ready for work
