### ISSUE TITLE
Reporter: Cypress crashes with any reporter that uses sync-request library

### ISSUE THREAD

**Issue by xlenz** [cypress-io/cypress#2567] opened 2018-10-05 14:49 UTC
### Current behavior:

Cypress crashes with any reporter that uses sync-request library.

There are no problems with webdriverio + mocha (or any other combination) and reporter that uses sync-request

### Desired behavior:

support reporters that uses sync-request

### Steps to reproduce:

1. Use any reporter that uses sync-request, example: https://github.com/xlenz/cypress-bugs/blob/sync-request-bug/custom-reporter.js
2. run at least one test

```
Error: Invalid port number string returned:
    at findPort (/Users/mygr/sources/cypress-bugs/node_modules/sync-rpc/lib/index.js:65:11)
```

- https://github.com/xlenz/cypress-bugs/tree/sync-request-bug
- cypress run
- and see logs

### Versions

Cypress 3.1.0

**Comment by jennifer-shehane** [comment] 2018-10-09 19:46
Hi @xlenz, I'm unable to reproduce the error you are seeing. 

I ran the tests within the repo after running `npm i` using both `cypress run` and `cypress open`. The tests results reported and exited properly and generated a report in the mochaawesome folder. 

Where is it that you were seeing the Error print? In the terminal? What OS are you using?

<img width="1319" alt="screen shot 2018-10-09 at 3 42 50 pm" src="https://user-images.githubusercontent.com/1271364/46694305-66096180-cbda-11e8-939b-682d4d590444.png">

<img width="838" alt="screen shot 2018-10-09 at 3 46 08 pm" src="https://user-images.githubusercontent.com/1271364/46694332-79b4c800-cbda-11e8-96eb-cddcd5b3df44.png">

**Comment by mgrybyk** [comment] 2018-10-09 21:20
@jannifer-shehane what you have sent is not a proper mochawesome report.

Can you ask help of someone who understands how it should work?

You should see report for all the tests not one of them.
I dont know how to explain it better if you don't want to read the ticket.

**Comment by xlenz** [comment] 2018-10-09 21:28
You are using wrong reporter or wrong branch. There should be no mochawesome report. Custom reporter is used there.

Please check if you have switched to branch

**Comment by jennifer-shehane** [comment] 2018-10-12 16:31
@xlenz Which branch is the bug on? master?

**Comment by mgrybyk** [comment] 2018-10-12 20:18
The one mentioned in the ticket.
sync-request-bug

**Comment by jennifer-shehane** [comment] 2018-11-19 21:31
Yes, I was able to replicate this

```
 cypress run
Could not load reporter by name: custom-reporter

We searched for the reporter in these paths:

- /Users/jennifer/Dev/cypress-bugs/custom-reporter
- /Users/jennifer/Dev/cypress-bugs/node_modules/custom-reporter

The error we received was:

Error: Invalid port number string returned:
    at findPort (/Users/jennifer/Dev/cypress-bugs/node_modules/sync-rpc/lib/index.js:65:11)
    at start (/Users/jennifer/Dev/cypress-bugs/node_modules/sync-rpc/lib/index.js:32:16)
    at sendMessage (/Users/jennifer/Dev/cypress-bugs/node_modules/sync-rpc/lib/index.js:117:17)
    at createClient (/Users/jennifer/Dev/cypress-bugs/node_modules/sync-rpc/lib/index.js:157:27)
    at Object.<anonymous> (/Users/jennifer/Dev/cypress-bugs/node_modules/sync-request/lib/index.js:16:14)
    at Object.<anonymous> (/Users/jennifer/Dev/cypress-bugs/node_modules/sync-request/lib/index.js:36:3)
```

This also causes 2 Cypress apps to run for me - and they end up in global mode. It's very strange.

<img width="828" alt="screen shot 2018-11-19 at 4 29 10 pm" src="https://user-images.githubusercontent.com/1271364/48736165-846e6e00-ec18-11e8-92eb-f1c229bbac7f.png">

**Comment by mourasman** [comment] 2019-02-21 13:44
I'm having the exact same problem here (same sync-request module, same symptoms). Are there any updates regarding this issue?

**Comment by jennifer-shehane** [comment] 2019-07-24 05:30
This is still an issue in Cypress 3.4.0

**Comment by Ahilmurugesan** [comment] 2020-11-19 01:58
Any updates on this issue?

**Comment by gaarutyunov** [comment] 2021-07-07 14:40
Any updates on this issue?

**Comment by jennifer-shehane** [comment] 2021-07-07 15:18
I'm not able to recreate this issue in Cypress latest version, 7.7.0, from the provided example.

Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-07-07 15:18 UTC
Labels: stage: needs investigating, topic: reporters 📄
