### ISSUE TITLE
Can't invoke "nested" when making expectations 

### ISSUE THREAD

**Issue by lorenzozanotto** [cypress-io/cypress#5350] opened 2019-10-11 13:04 UTC
### Current behavior:

When executing these two lines, from the [Cypress Documentation](https://docs.cypress.io/guides/references/assertions.html#BDD-Assertions), the console says that it's not possible to read the property `property` or `include` of `undefined`.

```js
expect({a: {b: ['x', 'y']}}).to.have.nested.property('a.b[1]')
expect({a: {b: ['x', 'y']}}).to.nested.include({'a.b[1]': 'y'})
```

### Desired behavior:

These assertions should work. 

Starting from a [Chai example project](https://github.com/yusufshakeel/mocha-chai-project) the lines written above run as expected.

### Steps to reproduce:

Running a Cypress test that make the two assertions above.

### Versions

**Cypress**: 3.4.1
**MacOS**: 10.14.5
**Electron**: 61

**Comment by jennifer-shehane** [comment] 2019-10-11 20:02
Thanks for reporting, closing as a duplicate of https://github.com/cypress-io/cypress/issues/5004 which I will look into shortly.

**Closed by jennifer-shehane** 2019-10-11 20:02 UTC
