### ISSUE TITLE
Loading and Crashing issues with Cypress v3.0.1

### ISSUE THREAD

**Issue by Stormdoodle** [cypress-io/cypress#1866] opened 2018-06-04 12:01 UTC
### Current behavior:
When I try to run Cypress via npm I get the following:
```
C:\Users\aallford\Documents\elprd-risk-assessment-app>C:\Users\aallford\Documents\elprd-risk-assessment-app\node_modules\.bin\cypress run

It looks like this is your first time using Cypress: 3.0.1

 ×  Verifying Cypress can run C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress
   → Cypress Version: 3.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------
----------

Platform: win32 (6.3.9600)
Cypress Version: 3.0.1
```

ALSO
If I try to run Cypress from the local install of 3.0.1, it crashes when I try to run an integration test.

### Desired behavior:
Cypress will open from npm, and not crash and close if run from local install
### Steps to reproduce:

As Current behaviour

### Versions
Cypress = v3.0.1
OS = Win 8
Browser = Chrome

**Comment by Stormdoodle** [comment] 2018-06-04 13:49
I completely deleted my version of Cypress and installed it again and it is now working.

Still got an issue through npm though

**Comment by Stormdoodle** [comment] 2018-06-04 14:12
@Bkucera   I mean I uninstalled Cypress that was locally installed.  Reinstalled it from the most recent (3.0.1) release and my local version is now working and allowing me to run integration tests.

My other issue (or the original issue) is when I try to launch Cypress from Visual Studio Code using `node_modules.bin\cypress run` is still giving me an error:
![capture](https://user-images.githubusercontent.com/19931722/40922246-a3241a68-6809-11e8-9d9f-7b6f0857477d.PNG)

**Comment by Bkucera** [comment] 2018-06-04 15:07
@Stormdoodle ok, strage that Cypress failed with a dependency error but didn't tell you which one. Can you run the following? 
```
set DEBUG=cypress*
node_modules\.bin\cypress run
```
?

**Comment by Stormdoodle** [comment] 2018-06-04 15:10
@Bkucera 
I ran what you suggested and got the following:

`C:\Users\aallford\Documents\elprd-risk-assessment-app>set DEBUG=cypress*

C:\Users\aallford\Documents\elprd-risk-assessment-app>node_modules\.bin\cypress run

  cypress:cli cli starts with arguments ["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\aallford\\Documents\\elprd-risk-assessment-app\\node_modules\\cypress\\bin\\cypress","run"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +2ms
  cypress:cli running Cypress +1ms
  cypress:cli parsed cli options {} +328ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe +2ms
  cypress:cli binaryDir is  C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress +1ms
  cypress:cli Found binary version 3.0.1 installed in: C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress +3ms
  cypress:cli could not read binary_state.json file +0ms
  cypress:cli {} +1ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli running binary verification check 3.0.1 +1ms
It looks like this is your first time using Cypress: 3.0.1

  cypress:cli clearing out the verified version +2ms
  cypress:cli running smoke test +3ms
  cypress:cli using Cypress executable C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe +0ms
  cypress:cli needs XVFB? false +1ms
  cypress:cli smoke test command: C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe --smoke-test --ping=567 +0ms
 ×  Verifying Cypress can run C:\Users\aallford\AppData\Local\Cypress\Cache\3.0.1\Cypress
   → Cypress Version: 3.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------
----------

Platform: win32 (6.3.9600)
Cypress Version: 3.0.1`

**Comment by Bkucera** [comment] 2018-06-04 16:13
@Stormdoodle thanks! How are you getting Cypress to work currently? You said you got it working, how are you running it, from where? How is that different than this failure?

**Comment by Stormdoodle** [comment] 2018-06-05 15:11
@Bkucera I have a local install of Cypress (Direct Download install) and open my project solution from within the application.  My project has 3.0.1 saved as a Dev dependency.  My problem/issue is that I can't open Cypress from within Visual Studio Code using the npm/npx methods/

**Comment by filipenevola** [comment] 2018-06-11 01:30
Same here

`DEBUG=cypress* node_modules/.bin/cypress run`
```
  cypress:cli cli starts with arguments ["/usr/local/Cellar/node/9.11.1/bin/node","/Users/filipenevola/Documents/quave/ws/bemarke/node_modules/.bin/cypress","run"] +0ms
  cypress:cli NODE_OPTIONS=--max-old-space-size=4096 +0ms
  cypress:cli program parsing arguments +3ms
  cypress:cli running Cypress +1ms
  cypress:cli parsed cli options {} +88ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/MacOS/Cypress +12ms
  cypress:cli binaryDir is  /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app +2ms
  cypress:cli Found binary version 3.0.1 installed in: /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app +2ms
  cypress:cli could not read binary_state.json file +0ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli running binary verification check 3.0.1 +0ms
It looks like this is your first time using Cypress: 3.0.1

  cypress:cli clearing out the verified version +2ms
  cypress:cli running smoke test +1ms
  cypress:cli using Cypress executable /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/MacOS/Cypress +0ms
  cypress:cli needs XVFB? false +0ms
  cypress:cli smoke test command: /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/MacOS/Cypress --smoke-test --ping=282 +1ms
 ✖  Verifying Cypress can run /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app
   → Cypress Version: 3.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------
----------

Platform: darwin (17.6.0)
Cypress Version: 3.0.1
```

**Comment by Bkucera** [comment] 2018-06-15 17:13
@Stormdoodle @filipenevola what are your node versions?

**Comment by SeriousM** [comment] 2018-06-18 11:45
The problem in #1959 is isolated by running this commands in docker windows container mode:

```cmd
C:\> docker run -it --rm stefanscherer/node-windows:8-nanoserver cmd
# switches into container
C:\> mkdir work
C:\> cd work
C:\work> npm i -y
C:\work> npm i --save-dev cypress@3.0.1
# till now everything works well
C:\work> set DEBUG=*
C:\work> node_modules\.bin\cypress verify
```

The node version is in this case node v8 but also fails with node v10.

**Comment by filipenevola** [comment] 2018-06-18 12:48
@Bkucera 
```
node --version
v9.11.1
```

I really want to try cypress out but the installation problems are real and I'm not able to get it running.

**Comment by Bkucera** [comment] 2018-06-18 14:46
@filipenevola @SeriousM 
There is a very good chance this is a permissions issue. We've got enhanced error logs coming out in the next release that should tell you the exact error.
I suspect you are downloading the Cypress binary as one user, and attempting to launch Cypress as another. This goes for Administrator privileges as well: in a Dockerfile you execute commands as root by default, and when you run the Cypress, you may not have root.

**Comment by SeriousM** [comment] 2018-06-18 15:21
> I suspect you are downloading the Cypress binary as one user, and attempting to launch Cypress as another. This goes for Administrator privileges as well: in a Dockerfile you execute commands as root by default, and when you run the Cypress, you may not have root.

I checked every single step and I'm always the same user (administrator).

**Comment by Bkucera** [comment] 2018-06-18 16:14
@SeriousM can you try lauching the Cypress binary directly via `.cache/Cypress/3.0.1/Cypress/Cypress.exe` ? This might give you the reason Cypress failed to launch

**Comment by SeriousM** [comment] 2018-06-18 19:22
> can you try lauching the Cypress binary directly

I did, but sadly none of my tries exposed *any* result..

```
C:\work>C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe --smoke-test

C:\work>C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe --smoke-test --ping=573

C:\work>C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe --help

C:\work>C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe verify

C:\work>C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe

C:\work>dir C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe
 Volume in drive C has no label.
 Volume Serial Number is 74B0-DF79

 Directory of C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress

06/19/2018  06:16 AM        85,785,600 Cypress.exe
               1 File(s)     85,785,600 bytes
               0 Dir(s)  20,442,939,392 bytes free
```

**Comment by brian-mann** [comment] 2018-06-18 19:39
Can any of you link us to the windows docker container you're using or maybe your docker script so we can reproduce on our end?

**Comment by SeriousM** [comment] 2018-06-18 20:37
https://github.com/cypress-io/cypress/issues/1866#issuecomment-398027576

It's there, just a few posts before.

**Comment by filipenevola** [comment] 2018-06-19 21:39
@Bkucera I'm running with nvm now:
```
cypress-validation nvm which current
/Users/filipenevola/.nvm/versions/node/v8.11.3/bin/node
```
and I got this error
```
➜  cypress-validation npm run cypress:open

> cypress-validation@1.0.0 cypress:open /Users/filipenevola/Documents/quave/ws/cypress-validation
> cypress open


It looks like this is your first time using Cypress: 3.0.1

 ✖  Verifying Cypress can run /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app
   → Cypress Version: 3.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------
----------

Platform: darwin (17.6.0)
Cypress Version: 3.0.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-validation@1.0.0 cypress:open: `cypress open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-validation@1.0.0 cypress:open script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filipenevola/.npm/_logs/2018-06-19T21_31_28_131Z-debug.log
```

just to be clear, I run a lot of node projects in this machine without any problem, the only one that is not working is cypress and I see a lot of people complain about it. Looks like there is something wrong on your end.

cypress promises to be the easiest solution that will make my life a lot easier with end-to-end testing but I'm not able to install it 😞, I really want to try this out because I already implemented end-to-end tests with a lot of different tools but I already spent a lot of time trying to make cypress works and that is frustrating.

I don't know what else to do, I already read everything that I could find online and I already tried in my Ubuntu machine too, I also got problems there. I really don't believe the problem is on my end when everything except cypress is working fine.

If you have more alternatives for me to try I will be happy to do it.

**Comment by lazytesting** [comment] 2018-06-20 15:45
Same issue here after I installed Cypress as a dependency of my nodejs project. Finally found a workaround.
1. clear C:\Users\[username]\AppData\Local\Cypress\Cache
2. start a command prompt as administrator
3. run ```npm i cypress -g```
4. run ```cypress open``` (not sure if this is needed)
5. close command prompt
6. return back to your node.js project and run the tests

**Comment by Bkucera** [comment] 2018-06-22 21:23
@filipenevola wow, I'm surprised that didn't work :disappointed: 
Can you try executing the binary directly from `/Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/MacOS/Cypress` ?

**Comment by Bkucera** [comment] 2018-06-22 21:37
@lazytesting what node version are you on?

**Comment by filipenevola** [comment] 2018-06-25 12:34
@Bkucera I got 
```
➜  ~ /Users/filipenevola/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/MacOS/Cypress ; exit;
[1]    49987 segmentation fault 
```

**Comment by lazytesting** [comment] 2018-06-25 14:39
@Bkucera I'm running node v8.11.1 and npm 5.8.0 via NVM for Windows.

**Comment by Bkucera** [comment] 2018-06-25 14:58
@filipenevola one more thing, Trying to see if we can get more info about the seg fault, can you execute the binary directly with ` DEBUG=cypress:*` set?

**Comment by SeriousM** [comment] 2018-07-02 09:10
Hi, here's an update with 3.0.2, done with the docker setup described above:

```
C:\>set DEBUG=cypress:*

C:\>cypress verify
  cypress:cli cli starts with arguments ["C:\\nodejs\\node.exe","C:\\nodejs\\node_modules\\cypress\\bin\\cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +0ms
  cypress:cli parsed cli options {} +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe +0ms
  cypress:cli Binary is executable? : true +0ms
  cypress:cli binaryDir is  C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress +0ms
  cypress:cli Reading binary package.json from: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 3.0.2 installed in: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress +0ms
  cypress:cli could not read binary_state.json file +15ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +15ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 3.0.2 +0ms
It looks like this is your first time using Cypress: 3.0.2

  cypress:cli clearing out the verified version +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe +0ms
  cypress:cli needs XVFB? false +0ms
  cypress:cli smoke test command: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=259 +0ms
 \  Verifying Cypress can run C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress
  cypress:cli Smoke test failed: { Error: Command failed: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=259


    at makeError (C:\nodejs\node_modules\cypress\node_modules\execa\index.js:172:9)
    at Promise.all.then.arr (C:\nodejs\node_modules\cypress\node_modules\execa\index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 3221225781,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Cypress\\Cache\\3.0.2\\Cypress\\Cypress.exe --smoke-test --ping=259',
  timedOut: false,
 ?  Verifying Cypress can run C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress
   ? Cypress Version: 3.0.2
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=259
----------

Platform: win32 (10.0.17134)
Cypress Version: 3.0.2
```

**Comment by brian-mann** [comment] 2018-07-02 16:56
Okay cool. We're making progress. Now we can at least see the exit code.

It appears there is more information from Electron regarding this here: https://github.com/electron/electron/issues/3570

Will investigate to see what can be done.

**Comment by brian-mann** [comment] 2018-07-02 17:00
@SeriousM or @petertsu are either of your offline when running Cypress?

**Comment by brian-mann** [comment] 2018-07-02 17:03
@SeriousM or @peterhry or @filipenevola are any of you trying to run Cypress from VSCode integrated terminal?

**Comment by petertsu** [comment] 2018-07-02 17:13
@brian-mann 
I am trying to run from cmd terminal

C:\Users\Administrator>node --version
v10.4.1

C:\Users\Administrator>npm --version
6.1.0

C:\Users\Administrator>

**Comment by brian-mann** [comment] 2018-07-02 17:18
So you're all experiencing the same problem which is good: Electron is exiting with exit code `3221225781`

There are a bunch of issues over at Electron's github indicating this. I scanned through them but didn't really see any actionable steps. We really need to be able to reproduce this on our own machines so we can iterate on the problem.

A quick google pulls up a bunch of results here: https://www.google.com/search?q=electron+3221225781&oq=electron+3221225781&aqs=chrome..69i57j69i60l2.1334j0j4&sourceid=chrome&ie=UTF-8

I would suggest any/all of you read through those and try out some of the workarounds there. If any work, please report them back here and we'll see what changes we need to make.

**Comment by SeriousM** [comment] 2018-07-03 07:22
> @SeriousM or @petertsu are either of your offline when running Cypress?

No, I'm online and the docker container is online as well

> @SeriousM or @peterhry or @filipenevola are any of you trying to run Cypress from VSCode integrated terminal?

Nope, just in cmd or powershell. same result.

**Comment by petertsu** [comment] 2018-07-03 09:13
Hi 
Good news  :) I have installed  Microsoft Visual C++ Redistributable for Visual Studio 2017 .
and after that uninstall  cypress + delete all local cache and install cypress again .

C:\Users\Administrator>cypress verify
It looks like this is your first time using Cypress: 3.0.2
 Verified Cypress! C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress

**Comment by SeriousM** [comment] 2018-07-03 13:51
I guess I found the docker solution!

As described above there is a docker windows-image for node 8 called `stefanscherer/node-windows:8-nanoserver`. This image is not able to verify cypress.
There is another tagged image called `stefanscherer/node-windows:8-build-tools` which is basically the same with the difference of `RUN npm install --global windows-build-tools`.
The image `stefanscherer/node-windows:8-build-tools` *IS* able to verify cypress!

The downside of this: the windows-build-tools adds 3.77GB of additional data to the image, but who cares :)

**Comment by filipenevola** [comment] 2018-07-07 15:10
@Bkucera follow below but I don't think that had any effect.

```
DEBUG=cypress:* /Users/filipenevola/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/MacOS/Cypress
[1]    936 segmentation fault  DEBUG=cypress:* 
```

**Comment by brian-mann** [comment] 2018-07-07 18:10
@filipenevola don't invoke the binary directly. Just set `DEBUG=cypress:* npm install` and then paste the output.

Make sure you're on `3.0.2`

**Comment by v-mwalk** [comment] 2018-07-08 22:34
I've also followed the install instructions (on https://docs.cypress.io/guides/getting-started/installing-cypress.html#npm-install) using npm and yarn on Windows.

Both resulted in the "Cypress failed to start" error as discussed above and the closed duplicate thread.  I see a lot of talk about Docker and saying that all required dependencies' are installed in the containers provided.  Do I need to have docker installed to play Cypress?

**Comment by v-mwalk** [comment] 2018-07-08 23:32
Cleared the cache and re-installed seems to have fix it.    Dunno if stuff did previously was the actual fix, but a new cache was also needed, or if just clearing the cache was the actual fix.

Tried installing using npm, then using yarn.  Both failed.  Couldn't run the direct download as a path-length issue was thrown up (even tho I'm enabled for long paths); an unzipping issue rather than Cypress,

Installed VS C++ 2017 Redist and restarted.  Still no joy.

Cleared cache and did a reinstall (when Cypress whinges after clearing cache).  Cypress Opened fine....

**Comment by jennifer-shehane** [comment] 2018-07-12 19:09
I was able to recreate this on our internal Cypress' EC2 instance running Windows 10. I created a new directory and ran `npm init`, `npm i --save-dev cypress` then `cypress open` and this same error occurred.

**Comment by autobrain-stanley** [comment] 2018-08-03 16:07
I'm having the same issue with circleci-cli. Everything works locally and inside our Docker+Docker-Compose instance. I'm at a loss as to what the problem and why its restricted to circleci. What exactly does the smoke test do?

**Comment by brian-mann** [comment] 2018-08-03 16:37
It doesn't do anything other than launch itself and exit with the same value you passed in which verifies that it's able to launch and run in the environment and that there are no missing dependencies

**Comment by autobrain-stanley** [comment] 2018-08-03 21:53
I finally figured it out. Looks like it was a rogue ENV variable setting `DISPLAY` to `10`.

**Comment by vladzhigulsky** [comment] 2018-08-10 13:06
I'm having the same issue on macOS after running initial `cypress open`.

**Comment by rsenna** [comment] 2018-10-08 09:04
To me, the issue was only fixed after i) I cleared cypress cache, and then ii) I was forced to run `cypress install`. Nothing else seems to have fixed the issue, at least in my case.

**Comment by filipenevola** [comment] 2018-10-08 13:37
I'm still not able to run cypress.

I already tried everything above many times.

My current error is:
```
npx cypress open            
It looks like this is your first time using Cypress: 3.1.0

 ✖  Verifying Cypress can run /Users/filipenevola/Library/Caches/Cypress/3.1.0/Cypress.app
   → Cypress Version: 3.1.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: /Users/filipenevola/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/MacOS/Cypress --smoke-test --ping=898
----------

Platform: darwin (17.7.0)
Cypress Version: 3.1.0

```

**Comment by skumar7** [comment] 2018-10-23 06:14
It worked after doing this for me.
Step1: Delete the cache folder 'Library/Caches/Cypress/'
Step2: Run Cypress install npm command locally.

This will download and install cypress as a fresh copy.

**Comment by D-Alexis** [comment] 2018-10-26 10:58
I had the exact same problem, and installing " Microsoft Visual C++ Redistributable for Visual Studio 2017" resolved it. I had to also delete ..\AppData\Local\Cypress\Cache .

The problem didn't occur on a computer with the same setup which already had the 2017 Redistributable.

**Comment by Saibamen** [comment] 2019-02-22 20:32
Add this to `package.json`:
```
"scripts": {
    "cypress": "cypress"
}
```

And run it with `npm run cypress open` (GUI) or `npm run cypress run`

**Comment by jkoop** [comment] 2019-03-07 07:57
[This solution](https://github.com/cypress-io/cypress/issues/2657) fixed the issue for me.

**Comment by Bkucera** [comment] 2019-03-07 22:40
@filipenevola you should try settings `NODE_OPTIONS=`, as @jkoop mentioned, since your logs indicate you have it set

**Comment by Saibamen** [comment] 2019-03-08 11:28
https://github.com/cypress-io/cypress/issues/1607#issuecomment-470802128

**Comment by filipenevola** [comment] 2019-03-11 13:02
Wow. Thank you @Bkucera, now it worked. It seems like that was the issue since always. Now I can finally run cypress and really start to use it. Thank you again!

As I'm always using NODE_OPTIONS for other projects I'll have to always disable it for Cypress but better than nothing ;) at least now I can use Cypress.

**Comment by linhsonit** [comment] 2019-05-07 09:06
Congrats @filipenevola . I do the same as you but it's still get the same error. Could you please show the final configuration? 

This is what i am doing:
set NODE_OPTIONS=
cache clean --force
npm install
set DEBUG=cypress:*
cypress:run

**Comment by filipenevola** [comment] 2019-05-07 10:17
Hi @linhsonit , I'm always running cypress like this
`unset NODE_OPTIONS && cypress open`

you can add this to your package.json
`"cypress:open": "unset NODE_OPTIONS && cypress open"`
and run with
`yarn cypress:open`

**Comment by linhsonit** [comment] 2019-05-07 14:44
Awesome! Thank you @filipenevola . It's worked. 
I am very happy now.

**Comment by derpmarine168** [comment] 2019-05-18 18:23
For me, what fixed it was intalling the Visual C++ redistributable :
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by jennifer-shehane** [comment] 2019-05-30 07:40
We did make a few updates recently to `cypress verify`, so please update to the latest version and retry - also post any [DEBUG logs](https://on.cypress.io/debugging#Debug-the-Command-Line) if it is still erroring.

**Comment by marcenacp** [comment] 2019-06-27 19:50
I still have the problem on the latest release. It occurs randomly on Gitlab CI when running tests on an Ubuntu (16.04 in Docker) without using cache. Is it possible to bypass this `verify` check?

I cannot post any more log, as Cypress does not even start.

```
+ npm run cypress:run

It looks like this is your first time using Cypress: 3.3.1

[19:28:50]  Verifying Cypress can run /root/.cache/Cypress/3.3.1/Cypress [started]
[19:29:01]  Verifying Cypress can run /root/.cache/Cypress/3.3.1/Cypress [failed]
Cypress verification timed out.

This command failed with the following output:

/root/.cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=563

----------

Command failed: /root/.cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=563

----------

Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 3.3.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui@0.0.1 cypress:run: `cypress run --key fae232b4-8625-419d-8df2-6dac9efb07c3 --browser chrome`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ui@0.0.1 cypress:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-27T19_29_01_361Z-debug.log
```

**Comment by Bkucera** [comment] 2019-06-30 05:51
@marcenacp please enable debug logs as mentioned above when posting error logs

**Comment by jennifer-shehane** [comment] 2019-07-01 08:45
We will be closing this issue in favor of https://github.com/cypress-io/cypress/issues/4624 in order to direct better focus on the overall problem that is being described in several issues - please add any information about how we can reproduce this bug there. 🙏

**Closed by jennifer-shehane** 2019-07-01 08:45 UTC
Labels: OS: windows, stage: needs investigating

**Comment by sydneybarlow** [comment] 2019-08-07 15:08
@jennifer-shehane I don't know if this would be helpful at this point. But a fix that happened for us for my co-worker that ran into the **exact same error, using Docker on Macs** is that we needed to **bump up the memory in the Docker settings**.
If you go to Docker preferences and click on Advanced, you can adjust the memory there.
My co-worker bumped it up to **5.0 GiB**, and that solved his `[cypress-test] Error 22`.
<img width="502" alt="Screen Shot 2019-08-07 at 11 05 36 AM" src="https://user-images.githubusercontent.com/37448056/62634269-9a85a100-b903-11e9-9189-c1927a0a72bb.png">

**Comment by jennifer-shehane** [comment] 2020-01-07 08:59
@sydneybarlow Please comment in the main issue in order to have all conversation in one place https://github.com/cypress-io/cypress/issues/4625
