### ISSUE TITLE
Cypress fails when mocha@6 is installed

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3756] opened 2019-03-20 14:14 UTC
### Current behavior:

Using `mochawesome`. According to your [docs](https://docs.cypress.io/guides/tooling/reporters.html#Local-Reporters):

```
You need to install any peer dependencies the reporter requires, even if they’re bundled with Cypress.
For example, mochawesome requires mocha as a peer dependency. You will need to install mocha
as a dev dependency of your own project for it to work.
```

So, then I run `yarn add --dev mocha`

However, this leads to the following problem:

https://stackoverflow.com/questions/55138378/got-typeerror-cannot-read-property-passes-of-undefined-using-cypress-when-gen

### Desired behavior:

Either cypress should work with mocha 6.0, or the docs should very clearly state that it doesn't and mocha@5.2.0 needs to be installed.

### Versions

Cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-03-21 03:48
Duplicate of https://github.com/cypress-io/cypress/issues/3537

**Closed by jennifer-shehane** 2019-03-21 03:48 UTC
