### ISSUE TITLE
Cypress crashes with whoops error

### ISSUE THREAD

**Issue by acurrieebix** [cypress-io/cypress#7298] opened 2020-05-11 19:31 UTC
I am generating tests from data much like the sample recipe provided.  On second run, a whoops error is appearing.  Debug log file attached.

### Test code to reproduce
```js
var RandExp = require('randexp');

describe('Create quote', () => {

    beforeEach(() => {
        cy.getUserByType('broker', 0, 'manager', 'broker', 0).as('user')
        
        cy.get('@user').then((user) => {
            //console.log('log in')
            cy.login(user.pplUsername, user.pplPassword)
        }).debug()
        
        cy.visit('/UI/BrokerPlacing/PlacementSummary.aspx?ascx=All&docType=quotation&doc=0').then(() => console.log('PlacementSummary visited'))
    })

    // load the data to populated the form
    const data = require('../../../fixtures/UI/DraftQuoteFormData')

    let i = 0;
    // This will generate one test per item  in the array data
    data.forEach(dataRow => {
        i++
        it(`Create quote with unique quote reference row ${i}`, () => {
```

### Versions

Cypress 4.4.1

**Comment by acurrieebix** [comment] 2020-05-11 19:32
[Cypress.log](https://github.com/cypress-io/cypress/files/4611679/Cypress.log)

**Comment by jennifer-shehane** [comment] 2020-05-12 07:11
The most common usecase of seeing a 'Whoops, there is no test to run' error is due to rerouting with target="_parent" https://github.com/cypress-io/cypress/issues/3121

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example, full test code that we can execute and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-05-12 07:11 UTC
