### ISSUE TITLE
When Intercepted, aborted XHR requests do not resolve the cy.wait command.

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#24492] opened 2022-11-01 20:36 UTC
### Current behavior

cy.wait will timeout when waiting on an intercepted aborted xhr call. (See test code)

### Desired behavior

The wait should resolve when the xhr request is aborted by the browser.

### Test code to reproduce

```js
it('aborts', () => {
  cy.visit('/xhr.html')
  cy.intercept(/users/, [{}, {}]).as('getUsers')
  cy.window()
  .then((win) => {
   cy.intercept('POST', /users/, {
     body: { name: 'b' },
     delay: 2000,
    }).as('createUser')

    cy.get('#create').click().then(() => {
      return win.location.href = '/index.html'
    })

    cy.wait('@createUser').its('canceled').should('be.true')
  })
})
```

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

MacOs

**Comment by flotwig** [comment] 2022-11-17 22:23
Dupe of #18544

**Closed as not planned by flotwig** 2022-11-17 22:23 UTC
Labels: type: bug, stage: needs review
