### ISSUE TITLE
Cypress cy.visit not updating url and dom after first visit in the spec. 

### ISSUE THREAD

**Issue by a2109k** [cypress-io/cypress#29628] opened 2024-06-07 09:34 UTC
### Current behavior

A cypress spec file with more than one visit `cy.visit()` doesn't work after the first visit. 
 
Let's say the first test has `cy.visit('/product/1')` which loads the product details of the item with id 1. It changes the URL to `localhost:4200/product/1` in the Cypress browser and loads the required page as expected. 

Now, if there is another visit say visit to the second product, `cy,visit('/product/2')`. It doesn't change the URL and the page remains at the same URL while the rest of the cypress code keeps executing. However, since the assertions don't match the expected values it fails due to this issue.

To resolve this, putting `cy.reload` just after `cy.visit` reloads the loads the URL and page fine. However, this is a hack which doesn't seem right. Cypress visit should continue to work fine. 

Please note if this could be related to the issue, we have `testIsolation` set as `false`. 

### Desired behavior

Cypress visit `cy.visit()` should continue to work update the URL irrespective of the number of times called without any need to reload the page.

### Test code to reproduce
```js
describe(('should display product details)=> {
 it('it should load product details of 1st item', ()=> {
    cy.visit('/product/1');
   cy.get('product-id').should('be.equal',1)
 })
 
it('it should load product details of 2nd item', ()=> {
   cy.visit('/product/2'');   
   cy.get('product-id').should('be.equal',2)})
})
```
### Cypress Version

13.10.0

### Node version

18.13.0

### Operating System

windows

**Comment by jennifer-shehane** [comment] 2024-06-10 15:34
I haven't seen this behavior. And this doesn't happen in any of our example or internal apps. I imagine this is something specific to running your application within Cypress. Is is possible to provide a way to reproduce this on our side?

**Comment by omerg** [comment] 2024-08-03 11:22
I have the exact same issue. To reproduce, I have to close the browser and click "Start E2E Testing in Edge". From that point, the the URL visible on the browser area of the on the right hand side of Cypress' test viewer keeps displaying the initial URL, even though the content obviously belongs to another url.

Browser: Microsoft Edge For Business
Browser Version: Version 126.0.2592.68 (Official build) (64-bit)
Cypress Version: 13.12.0

**Comment by jennifer-shehane** [comment] 2024-08-26 18:46
Closing since there is not enough information provided for us to investigate. We need a way to reproduce this behavior. Open an issue if you see similar behavior with a way to reproduce.

**Closed as not planned by jennifer-shehane** 2024-08-26 18:46 UTC

**Comment by erestor** [comment] 2025-03-07 09:15
Same issue here. There's a visit() in beforeEach and another visit() in test body. See screenshot and the url change at the end, not initiated by any command from the test.

![Image](https://github.com/user-attachments/assets/36abb874-0b4c-478b-a501-ca6ba184bb3d)
