### ISSUE TITLE
Cypress does not detect dependencies with Yarn 3 PNP

### ISSUE THREAD

**Issue by wopian** [cypress-io/cypress#25733] opened 2023-02-07 12:13 UTC
### Current behavior

Shows a warning that `vite@4`, `react@18` and `react-dom@18` (or `vue@3` in Vue repositories) dependencies are not found when running component tests interactively with Yarn 3 PNP

<img width="626" alt="Screenshot 2023-02-07 at 10 49 10" src="https://user-images.githubusercontent.com/3440094/217224724-d9c6f637-b7ea-43c5-867e-391cc6b6bf87.png">

### Desired behavior

No warnings when `vite@4`, `react@18` and `react-dom@18` are all installed and listed as dependencies in package.json

### Test code to reproduce

Barebones React 18 and Vite 4 reproduction with Yarn 3: https://github.com/wopian/cypress-test-tiny

CircleCI has been changed to use Yarn commands.

### Cypress Version

12.5.0

### Node version

19.6.0

### Operating System

macOS 13.0

### Other

Yarn 3 with Plug 'n' Play.

`.yarnrc.yml`
```yaml
cloneConcurrency: 8
defaultSemverRangePrefix: '~'
enableScripts: false
enableTelemetry: false
httpRetry: 3
httpTimeout: 60000
nmMode: hardlinks-global
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.3.1.cjs
```

**Comment by wopian** [comment] 2023-02-07 12:14
This may be a duplicate of https://github.com/cypress-io/cypress/issues/22747 but I am not sure, as I do not get any errors when using Cypress with Yarn 3 PNP or ES Modules - only this warning box before selecting which browser to open tests with on Vue and React apps. Though both issues would likely be fixed with the same module resolution fix.

**Comment by warrensplayer** [comment] 2023-02-08 19:27
@wopian This is not a duplicate of #22747 even though they both involve yarn 3.  The similarity is that both involve the way the Cypress app relies on looking into the `node_modules` folder for things, which yarn 3 does not use.

Are you having any issues running your tests?  Or are you simply reporting that warning message in your screenshot?

**Comment by wopian** [comment] 2023-02-09 09:23
@warrensplayer reporting the warning message. Tests run without issues

**Comment by bensullivan-ag** [comment] 2023-02-24 02:33
Hi - just checking that cypress 12 is compatible with yarn 3?  I noticed that the cypress factory docker images don't support versions of yarn later than 1.22.19.  ..

**Comment by bensullivan-ag** [comment] 2023-02-24 03:01
Hi - just wondering if cypress 12 is compatible with yarn 3?  I noticed that the cypress factory docker images don't support yarn 3....

**Comment by wopian** [comment] 2023-02-24 03:38
Cypress 12 works fine with Yarn 3 for me after using both for >1 month - it just doesn't detect the package versions of frameworks you target in cypress config when using PnP package linking

**Comment by lmiller1990** [comment] 2023-03-08 05:20
Cypress 12 works fine with Yarn 3, except the component testing dependency detection screen isn't working as expected. That's what this ticket is about. It's misleading and confusing, we will fix it by end of March.

I made a new issue https://github.com/cypress-io/cypress/issues/25733 which I'm using to track -- I didn't realize this one already existed when I made that one. Closing this one is favor of the newer one.

**Closed as completed by lmiller1990** 2023-03-08 05:20 UTC

**Comment by wopian** [comment] 2023-03-08 10:49
@lmiller1990 you may have linked back to this issue instead of the new issue created 😅 

I assume you mean #25960?

**Comment by lmiller1990** [comment] 2023-03-08 21:45
Yep, sorry... we will work on #25960 in the next 2 weeks.

**Comment by thewordisbird** [comment] 2023-08-30 18:05
@lmiller1990 thanks for resolving this issue! do you have a timeline on when this is expected to be available in the production build?

**Comment by wopian** [comment] 2023-08-31 08:17
> @lmiller1990 thanks for resolving this issue! do you have a timeline on when this is expected to be available in the production build?

5 months ago :)

https://github.com/cypress-io/cypress/issues/25960#issuecomment-1511907459

**Comment by MikeMcC399** [comment] 2023-08-31 11:27
@thewordisbird  / @wopian 

- There is an active open issue for this https://github.com/cypress-io/cypress/issues/26859
