### ISSUE TITLE
Cypress Recording not complete

### ISSUE THREAD

**Issue by katosdev** [cypress-io/cypress#9394] opened 2020-12-01 16:22 UTC
Hello there! 
Apologies if this is a simple mis-configuration, or something I have missed, but after having looked around I can't seem to see what might be causing this, and so slightly hoping one of you lovely peeps can assist! 

### Current behavior
When recording (either locally, or to the dashboard), the video cuts off and does not show the test(s) in progress. An example of this can be seen here: https://dashboard.cypress.io/projects/ngzhq1/runs/9/test-results/19ab84be-a666-461a-80dd-3c950cbbd56a/video?utm_source=Dashboard&utm_medium=Share+URL&utm_campaign=Video 

As you can see, this starts to record, but then after "Your tests are loading" it just cuts out. 

### Desired behavior
Full recording of the running test to be created, and uploaded to the dashboard on completion or failure for QA Team review. 

### Test code to reproduce
We are seeing this over both of our current tests, but this can be seen on our latest run for example : https://dashboard.cypress.io/projects/ngzhq1/runs/9/overview

(Disclaimer) : I am entirely new to Cypress (and by extension, automation testing) so if this is something silly that I have missed, I apologise and would appreciate any pointers 👍 

### Versions

Cypress V6.0.0 (about to update to v6.0.1 and re-test) 
Windows 10.0.19042
Electron 87

### Test output

 Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 6 seconds                                                              │
  │ Estimated:    1 minute, 10 seconds

**Comment by bahmutov** [comment] 2020-12-01 16:24
Yes, this is a duplicate of #9265 and should be solved by 6.0.1 https://on.cypress.io/changelog#6-0-1

**Closed by bahmutov** 2020-12-01 16:24 UTC

**Comment by katosdev** [comment] 2020-12-01 16:27
> Yes, this is a duplicate of #9265 and should be solved by 6.0.1 https://on.cypress.io/changelog#6-0-1

Well that's embarrassing. Apologies for clearly not looking well enough...!
