### ISSUE TITLE
Application not working with Chrome-64.  Failing to get URL "/__/#/tests/"

### ISSUE THREAD

**Issue by p4pramod** [cypress-io/cypress#1497] opened 2018-03-25 11:37 UTC
- Operating System: Window 7
- Cypress Version: Cypress package version: 2.1.0
  Cypress binary version: 2.1.0
- Browser Version: Chrome 64

### Current behavior: 
I am trying to test website with Chrome 64 browser. As soon as i run the test chrome browser opens up and it shows that it is requesting the page. But soon after it opens a page that says..

```
404. That’s an error.

The requested URL /__/ was not found on this server. That’s all we know.
```

### Desired behavior:
Ideally it should open the login page.

### How to reproduce:
It is very simple and it breaking at the start of the test.

#### Test code:
```js
cy.visit('https://www.google.co.in')
```

**Comment by p4pramod** [comment] 2018-03-27 11:35
I can not upload image as i am behind corporate proxy. My problem is as soon as test starts running in Chrome 64 it opens a page having __  e.g. " https://app.corp.com/__/#/tests/integration\example_spec.js" and it crashes saying 404 not found.

But when I run the save test in Electron 59 it works.

**Comment by ValerieThoma** [comment] 2018-03-27 12:52
It really sounds like you might be experiencing a roadblock caused by your corporate proxy. A number of users are experiencing similar pains that are presenting in multiple ways and Cypress is currently looking into solutions or work arounds for these pain points. 
Please take a look at this proposal #1469 and its related issues, there are some verified work arounds to try in the interim.

**Comment by p4pramod** [comment] 2018-03-27 14:31
I want to know why it works with Electron 59 but not with Chrome 64?

**Comment by cameronc56** [comment] 2018-03-29 17:26
I've been hitting this when the site implements framebusting techniques that cypress has no workaround for. (frame-ancestors:none)

**Comment by cameronc56** [comment] 2018-03-29 19:45
Yeah we were discussing it yesterday.

https://chaseonline.chase.com/Logon.aspx?LOB=RBGLogon

I'm not sure if there is a workaround to frame-ancestors: none. But I think cypress should skip/autofail the test if it encounters this, otherwise it just hangs there.

**Comment by cameronc56** [comment] 2018-03-29 22:05
^ this is wrong. 

There was another difference between when I ran it with and without the extension.

There was some code in the comments of  https://github.com/cypress-io/cypress/issues/992
to work around the framebusting that I had in my utils/index.js file that was causing it to do this.

**Comment by cameronc56** [comment] 2018-03-29 22:13
Try it with this site: https://secure2.store.apple.com/shop/account/setup

**Comment by jennifer-shehane** [comment] 2018-03-29 22:26
@cameronc56 Yeah, you shouldn't need any of the code that was previously recommended to get around framebusting applications since ^2.0.0. We automatically strip code from applications that attempt to prevent being run within an iframe, but there could definitely be some edge cases that we've missed.

This apple one is a *really* good usecase, and also not typical of what I've seen with framebusting behavior. It usually will show a blank grey screen, the message "Whoops, there is no test to run" is interesting. Looking into this one. 👍

**Comment by jennifer-shehane** [comment] 2018-03-29 23:02
@cameronc56 Opened an issue for the store.apple url here: https://github.com/cypress-io/cypress/issues/1517

**Comment by rsudarson** [comment] 2018-03-30 13:21
With cypress 2.1.0 &  chromium 64+, url visit is not redirecting properly. It adds __ in the url and the page simply waits.

**Comment by cameronc56** [comment] 2018-03-30 19:13
Cypress gets stuck and doesn't move on when from the test when visiting this url: https://login.yahoo.com/config/login?.src=flickrsignin&.pc=8190&.scrumb=0&.pd=c%3DH6T9XcS72e4mRnW3NpTAiU8ZkA--&.intl=in&.lang=en&.done=https%3A%2F%2Flogin.yahoo.com%2Fconfig%2Fvalidate%3F.src%3Dflickrsignin%26.pc%3D8190%26.scrumb%3D0%26.pd%3Dc%253DJvVF95K62e6PzdPu7MBv2V8-%26.intl%3Din%26.done%3Dhttp%253A%252F%252Fwww.flickr.com%252Fsignin%252Fyahoo%252F%253Fredir%253Dhttp%25253A%25252F%25252Fwww.flickr.com%25252F

**Comment by cameronc56** [comment] 2018-03-30 19:39
https://stackoverflow.com/users/login also hijacks the page

**Comment by jennifer-shehane** [comment] 2018-04-02 20:25
Opened issue for yahoo login here: https://github.com/cypress-io/cypress/issues/1524
Stackoverflow needs some more investigation, but is definitely hijacked.

**Comment by khuezy** [comment] 2018-04-03 14:42
I was also experiencing this issue:
`cy.visit('anysite.com')` and it would redirect to cypress chrome window to `anysite.com/__/test/integration/testfile.js` 404

It turned out I had an extension that was redirecting traffic. Culprit was SwitchyOmega.

**Comment by jennifer-shehane** [comment] 2018-04-03 18:50
@khuezy Did you install `SwitchyOmega` specifically within the Cypress browser? Launching within the Cypress browser profile should not have brought over 3rd party extensions installed in your regular browser - exactly for this reason - to ensure they do not interfere with your testing environment. https://on.cypress.io/launching-browsers#Cypress-Profile

**Comment by khuezy** [comment] 2018-04-04 14:42
@jennifer-shehane yes, I installed the plugin within the Cypress browser. I was trying to proxy via socks5 to the office network from home.

**Comment by rizzza** [comment] 2018-04-04 21:28
> With cypress 2.1.0 & chromium 64+, url visit is not redirecting properly. It adds __ in the url and the page simply waits.

Seeing this as well after login with multiple re-directs

**Comment by ben-poon** [comment] 2018-04-24 18:04
I'm able to reproduce this issue on the example spec with cypress 2.1.0 and chromium 65 running just the default with no add-ons or mods in windows OS. I've also reproduced this with a simple cy.visit statement.

**Comment by Bkucera** [comment] 2018-10-09 20:59
@bsmithEG we have tests covering that scenario, so that shouldn't be able to framebust

**Comment by matt212** [comment] 2018-11-07 19:00
any updates or alternative strategy in order to resolve this issue . since the problem is the issue is reproducing it being of  inconsistent nature . is there any way in which we can wait for inner window to load and then execute commands / spec file

**Comment by jpatel13** [comment] 2018-11-12 03:16
Hi, 
  I'm using Cypress 3.1.1  on MacOS Sierra. When i run a simple test(below)  against chrome 70 I get  'The requested URL /__/ was not found on this server. That’s all we know.' error. 

`cy.visit('https://www.google.com')`

Is there a work around for this? There doesn't seems to be a cypress extension as indicated in one of the solutions?

**Comment by jennifer-shehane** [comment] 2018-11-28 10:01
Unfortunately we'll have to close this issue if no reproducible example is provided. All of the examples given have not been reproducible on our side. 

Can anyone provide a way to reproduce this?

**Closed** 2019-01-08 06:04 UTC
Labels: stage: needs information

**Comment by SOMIASHARMA26** [comment] 2019-09-04 09:40
@ Jennifer-shehane

I am running simple CY.visit('https://192.168.7.2')

Getting error  is  "err_ssl_version_or_cipher_mismatch"

Cypress version: 3.4.1 and chrome version 76

**Comment by memee** [comment] 2019-12-10 14:16
Are there any workarounds for this issue?

**Comment by sdjnaik** [comment] 2019-12-27 06:10
Hi,

Facing same issue with Chrome whereas my page works fine on Electron browser

Platform : Windows
Chrome version:  79.0.3945.88

**Comment by jennifer-shehane** [comment] 2019-12-30 10:48
Please open a new issue detailing exact test code with application code we can test against so that we can work towards a fix for this issue.
