### ISSUE TITLE
Configurable framebuffer resolution and browser width

### ISSUE THREAD

**Issue by KrzysztofKarol** [cypress-io/cypress#804] opened 2017-10-24 23:54 UTC
### Current behavior:
Browser width is fixed.

### Desired behavior:
Browser width is configurable.

I'm running cypress in Docker and framebuffer resolution is fixed and browser size is fixed.

My ugly, temporary workaround

**Dockerfile**
```dockerfile
FROM cypress/base

ENV XRES 1920
ENV YRES 1200

RUN npm install --save-dev cypress
COPY ./node_modules/cypress/lib/exec/xvfb.js node_modules/cypress/lib/exec/xvfb.js
COPY ./node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/modes/headless.js node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/modes/headless.js
RUN $(npm bin)/cypress verify

CMD ["node_modules/.bin/cypress", "run", "--project", "/frontend"]
```

**node_modules/cypress/lib/exec/xvfb.js:13**
```javascript
var xvfb = process.env.XRES && process.env.YRES
  ? Promise.promisifyAll(new Xvfb({ silent: true, xvfb_args: ['-screen', '0', process.env.XRES + 'x' + process.env.YRES + 'x24'] }))
  : Promise.promisifyAll(new Xvfb({ silent: true }))
```

**node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/modes/headless.js:118**
```javascript
width: process.env.XRES && +process.env.XRES - 6 || 1280, // 1914 is max for 1920
height: process.env.YRES && +process.env.YRES - 6 || 720, // 1194 is max for 1200
```

**Comment by brian-mann** [comment] 2017-10-25 00:08
Yeah this is do-able. It'll need to be a CLI argument since as you figured out we have to spawn xvfb at the CLI level prior to invoking the binary.

Then we just pass that around and set the width/height of the renderer to that. There is one additional piece of complexity which is `ffmpeg`. It is very sensitive about the resolutions it can record it. For instance the width/height must not be an odd number, and it cannot exceed what the display is actually set to. 

I think @bahmutov mentioned at one point it actually has to be divisible by 4, so I'm not sure if that's still the case.

**Comment by brian-mann** [comment] 2017-10-25 00:12
Also I'm not sure what we'll need to do for Windows to make this work... or even OSX. The problem is that it's possible to set something that exceeds what the display is capable of. We could error then or maybe there is a way to work around it.

**Comment by jennifer-shehane** [comment] 2022-04-08 13:47
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 13:47 UTC
Labels: type: enhancement, cli, pkg/server, stage: needs investigating
