### ISSUE TITLE
Execução com o Chrome apresentando problema

### ISSUE THREAD

**Issue by arborges12** [cypress-io/cypress#15713] opened 2021-03-30 19:14 UTC
Ao tentar executar os testes usando o Chrome o Cypress não consegue processar e apresenta esse erro.

**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">57622</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:57622
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m57622[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:57622
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

    at get (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\errors.js:986:15)
    at Object.throwErr [as throw] (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\errors.js:1004:9)
    at C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\browsers\protocol.js:105:21
    at tryCatcher (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\adriano.borges\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

![image](https://user-images.githubusercontent.com/63407915/113043538-f5bc7500-9172-11eb-81a4-d7c7b43941d8.png)

```

**Comment by jennifer-shehane** [comment] 2021-03-30 19:39
Duplicate of https://github.com/cypress-io/cypress/issues/15650

**Closed as completed by jennifer-shehane** 2021-03-30 19:39 UTC
