### ISSUE TITLE
Passing "cypress open --browser electron" with browser flag alone shouldn't prompt to open browser and open automatically

### ISSUE THREAD

**Issue by far11ven** [cypress-io/cypress#22003] opened 2022-06-01 17:26 UTC
### Current behavior

On launching cypress test with **npx cypress open --browser chrome** command still asks user to choose a browser

Also, 
on this screen, when the user chose a browser
![image](https://user-images.githubusercontent.com/26922130/171465549-24cf3995-f0be-4315-afc6-36064be6cb9d.png)

user should directly lead to Test Runner
instead of clicking on  GREEN button
IMO its an extra click for user

### Desired behavior

Cypress should not ask user to again choose a browser if it was passed --browser flag
and clicking on the GREEN button shouldn't be required

### Test code to reproduce

NA

### Cypress Version

10.0.0

**Comment by jennifer-shehane** [comment] 2022-06-01 18:19
@far11ven When you run this, does it prompt you in the UI to choose e2e or ct tests first? Does this work if you pass `npx cypress open --e2e --browser chrome`? Because that combination of flags should work, but I don't think we coded passing the browser flag alone and for that to skip the browser screen. 

It's a good idea though, we'll keep this open as a suggestion to skip this screen regardless of the testing type flag passed.

**Comment by far11ven** [comment] 2022-06-01 19:08
@jennifer-shehane yes it works fine with npx cypress open --e2e --browser chrome, just not without --e2e flag

**Comment by flotwig** [comment] 2022-06-01 22:47
The reason the `--e2e` or `--component` flag is required is because otherwise we don't know what mode you intend to launch in.

Maybe it would improve the experience if we auto-launched the browser if there's only 1 testing type configured in the project and the user passes `--browser`? Select the configured testing type by default in the Launchpad

**Comment by KuroiRaven** [comment] 2022-06-02 11:18
Hey guys, I'm facing the same issue.
I switched my command from : `"cy:open": "cypress open"` to `"cy:open": "cypress open --e2e --browser electron"`
And the e2e/component & browser's launcher still launches every time I use the `yarn cy:open` command.

Did I misunderstand something ?
Is this the new expected behaviour from this command ?
I kinda feel like it is useless to have a separate windows to handle these 2 parameters and they could be merged in the standard test-runner window.

**Comment by jennifer-shehane** [comment] 2023-07-07 19:36
When passing the --browser flag alone, without the testing type, during `cypress open`, the screen to select a testing type should display. After selecting a testing type, the browser should automatically open to the browser passed, skipping the browser selection screen. 

If someone wants to open a PR to fix this behavior, we would accept it.

**Comment by effihol** [comment] 2023-07-10 13:19
@jennifer-shehane Hey there!

I'm exicted to jump in and help solve this issue, but I'm a newbie to the project. Any guidanceon where I should start digging? Which files should I check first?

I appreciate your support :)

**Comment by raygdev** [comment] 2023-08-29 17:13
Hi @jennifer-shehane! I would like to start working on this launchpad feature. I do have some questions though!

1. Do we want to launch from the testing type selection view and not render the browser selection view?
2. Do we want to render the browser selection view and display all the state that would normally be displayed had a browser been selected from that view?
3. If number 2, do we want to highlight the chosen browser as if it had been selected on the browser select view?
4. I'm still trying to figure out how to start in dev to be able to pass cli options. Would this be the same as `yarn cypress:open --browser chrome`? Or is there some other way I should be aware of?

Please bare with me as I am completely new to this stack in general! But have a pretty good idea as to where it should take place and the queries to use and logic to reuse. Once that is out of the way, I will make a draft pull request and start working! Thank you!

**Comment by jennifer-shehane** [comment] 2023-12-13 15:59
> Do we want to launch from the testing type selection view and not render the browser selection view?

It should perform as if you clicked the browser automatically, so the end state would be the browser selection view, showing the button to close. 

>Do we want to render the browser selection view and display all the state that would normally be displayed had a browser been selected from that view?

Yes 

>If number 2, do we want to highlight the chosen browser as if it had been selected on the browser select view?

Yes 

>I'm still trying to figure out how to start in dev to be able to pass cli options. Would this be the same as yarn cypress:open --browser chrome? Or is there some other way I should be aware of?

You would likely verify this behavior via the tests.

**Comment by raygdev** [comment] 2023-12-13 17:40
@jennifer-shehane Thank you for the response! I took a few days to read through the code to try and understand where the changes need to be made. I started with the cli repo and worked my way through the data context and found that the data is available in a GQL query for the browser that was passed as the option to the cli. 

Ultimately I know that the change will happen in a vue component. All of the logic for the views are already in place without having to make any additional changes to that (I believe). I have had a "working" change for some time now, but it is not a clean solution. Please allow me a little bit of time to make a draft PR with that change. I understand you all are busy, but I may need help with a cleaner option. I want to maintain code consistency and keep it as minimal as possible. I am not at all familiar with vue or GraphQL, but did manage to connect some dots. Please bare with me on this!

**Closed as completed** 2024-08-27 14:22 UTC
Labels: type: enhancement, type: feature, v10.0.0 :bug:, E2E
