### ISSUE TITLE
cy.get() returns undefined when using global options object

### ISSUE THREAD

**Issue by WilliamWaterworth** [cypress-io/cypress#5221] opened 2019-09-26 22:51 UTC
### Current behavior:
I used a global object for cy.get commands, which usually works for Cypress testing. It works here if all tests run in the same `specify` function. Otherwise, all tests except the first fail with a vague "Undefined does not have class \<classname\>" error.

### Desired behavior:

Ideally, I shouldn't have to redefine my `cy.get` options parameter for each `specify`. At minimum, Cypress should provide a useful error message.

### Steps to reproduce: (app code and test code)
This works only when inlining the options object, i.e. `{timeout: 120000}` instead of `options`
```
const options = { timeout: 120000 };
describe("Onboard Files", function() {
    beforeEach(function() {
        Cypress.Cookies.preserveOnce(".cookiename");
        const files = Cypress.env("fileSpecifications");
        createCypressFile(files.fileA).then(blob => createMockDrag(blob, files.fileA)).as("fileA");
        createCypressFile(files.fileB).then(blob => createMockDrag(blob, files.fileB)).as("fileB");
    });

    specify("A", function() {
        dragAndDropFile(this.fileA);
        cy.get("c-container-drag-drop", options).should("have.class", "success");
    });
    
    specify("B", function() {
        dragAndDropFile(this.fileB);
        cy.get("c-container-drag-drop", options).should("have.class", "success");
    });
});

const createCypressFile = function(fileObject) {
    return cy
        .fixture(fileObject.path, 'base64')
        .then(Cypress.Blob.base64StringToBlob);
};

const createMockDrag = function(blob, fileObject) {
    const file = new File([blob], fileObject.name, { type: fileObject.type });
    return {
        dataTransfer: {
            files: [file],
        },
        preventDefault: function() { },
    };
};

const dragAndDropFile = function(e) {
    cy.get("c-container-drag-drop").as("host");

    cy.get("c-container-drag-drop:not(.onboard):not(.dragging)", options)
        .then(function(host) {
            getShadow(host).querySelector("#content").ondragenter(e);
        });

    cy.get("c-container-drag-drop.dragging", options)
        .then(function(host) {
            getShadow(host).querySelector("#drop-indicator").ondrop(e);
        });

    cy.get("c-container-drag-drop", options)
        .should("not.have.class", "onboard");
};

const getShadow = host => host[0] === undefined
    ? host.shadowRoot
    : host[0].shadowRoot;
```

### Versions

Cypress 3.4.1 running Chrome 77

**Comment by Bkucera** [comment] 2019-09-26 23:02
@WilliamWaterworth thanks for the bug report! I'm closing this as a duplicate of #3171

**Closed by Bkucera** 2019-09-26 23:02 UTC
