### ISSUE TITLE
Firefox v105 not working for runner/headless

### ISSUE THREAD

**Issue by brentsharon** [cypress-io/cypress#24195] opened 2022-10-10 23:50 UTC
### Current behavior

Currently FFv105 will not open and times out when attempting to run specs in the runner and also running specs in headless.

### Desired behavior

FF browser should not timeout and user should be able to run specs in the FF browser

### Test code to reproduce

no test code needed just try to open FFv105 and run spec or use the cli to run a headless test

### Cypress Version

10.9.0

### Node version

v14.16.1

### Operating System

mac 12.4 Monterey

### Debug Logs

```shell
cypress:server:cypress exiting with err Error: connect ECONNREFUSED 127.0.0.1:55248
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
 {
  isCypressErr: true,
  type: 'FIREFOX_COULD_NOT_CONNECT',
  details: 'Error: connect ECONNREFUSED 127.0.0.1:55248\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)\n',
  messageMarkdown: 'Cypress failed to make a connection to Firefox.\n' +
    '\n' +
    'This usually indicates there was a problem opening the Firefox browser.',
  originalError: Error: connect ECONNREFUSED 127.0.0.1:55248
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
   {
    isCypressErr: true,
    type: 'CDP_COULD_NOT_CONNECT',
    details: 'Error: connect ECONNREFUSED 127.0.0.1:55248\n' +
      '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)\n',
    messageMarkdown: 'Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.\n' +
      '\n' +
      'This usually indicates there was a problem opening the Firefox browser.\n' +
      '\n' +
      'The CDP port requested was `55248`.',
    originalError: OperationalError: connect ECONNREFUSED 127.0.0.1:55248
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
     {
      cause: [Error],
      isOperational: true,
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 55248
    },
    stackWithoutMessage: '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)\n'
  },
  stackWithoutMessage: '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)\n'
} +53s
Cypress failed to make a connection to Firefox.

This usually indicates there was a problem opening the Firefox browser.

Error: connect ECONNREFUSED 127.0.0.1:55248
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
```

**Comment by nagash77** [comment] 2022-10-11 14:10
Hello @brentsharon , We have a fix for a problem that appeared after firefox made a change to how they resolve localhost.  https://github.com/cypress-io/cypress/issues/23897 will be releasing today in `Cypress 10.10.0`. Can you please try upgrading to that version of Cypress and seeing if that resolves the issue?

**Comment by brentsharon** [comment] 2022-10-11 19:01
Thanks!

**Comment by audriusnavickasDB** [comment] 2022-10-12 08:44
@nagash77 Still reproducible with v10.10.0. I have added what I am seeing with cypress open on https://github.com/cypress-io/cypress/issues/23897 it's a step forward, but the problem still remains :(

**Comment by radekBednarik** [comment] 2022-10-12 16:43
hi, can confirm, even after update to v10.10.0, in our CI/CD pipeline, Cypress cannot connect to Firefox.

**Comment by radekBednarik** [comment] 2022-10-13 05:49
let me pls add some logs: 
Cypress can find Firefox:
```shell
07:35:18  2022-10-13T05:35:18.679Z cypress:server:browsers:utils found browsers { browsers: [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: '106.0.5249.119', path: 'google-chrome', minSupportedVersion: 64, majorVersion: '106' }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '105.0.3', path: 'firefox', minSupportedVersion: 86, majorVersion: '105' }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', version: '106.0.1370.42', path: 'microsoft-edge', minSupportedVersion: 79, majorVersion: '106' } ] }
```
firefox is then started, but once Cypress tries go to the page with the first test, it will start to get problems:

```shell
07:35:21  2022-10-13T05:35:21.279Z cypress:server:browsers:firefox launch in firefox {
07:35:21    url: 'http://XXX/__/#/specs/runner?file=cypress/e2e/client/XXX.cy.ts',
07:35:21    args: [
07:35:21      '-marionette',
07:35:21      '-new-instance',
07:35:21      '-foreground',
07:35:21      '-start-debugger-server',
07:35:21      '-no-remote',
07:35:21      '--remote-debugging-port=41613',
07:35:21      '-headless',
07:35:21      '--width=1536',
07:35:21      '--height=754',
07:35:21      '-profile',
07:35:21      '/root/.config/Cypress/cy/production/browsers/firefox-stable/run-1326'
07:35:21    ]
07:35:21  }
07:35:21  2022-10-13T05:35:21.604Z cypress:server:browsers:firefox-util firefox: navigating page with webdriver
07:35:22  2022-10-13T05:35:22.013Z cypress:server:browsers:browser-cri-client cancelling any additional retries { host: '127.0.0.1', port: 41613 }
07:35:22  2022-10-13T05:35:22.077Z cypress:server:server-base Got CONNECT request from location.services.mozilla.com:443
07:35:22  2022-10-13T05:35:22.317Z cypress:server:browsers:browser-cri-client error finding browser target, maybe retrying { delay: 100, err: Error: <html>                    <head><title>404 Not Found</title></head>                    <body>                      <h1>404 Not Found</h1>                      <p>                        <span style='font-family: monospace;'>&#47;&#106;&#115;&#111;&#110;&#47;&#118;&#101;&#114;&#115;&#105;&#111;&#110;</span> was not found.                      </p>                    </body>                  </html> at IncomingMessage.<anonymous> (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/lib/external-request.js:33:26) at IncomingMessage.emit (node:events:539:35) at IncomingMessage.emit (node:domain:475:12) at endReadableNT (node:internal/streams/readable:1345:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)  }
07:35:22  2022-10-13T05:35:22.376Z cypress:server:util:socket_allowed allowing socket { localPort: 55628 }
```
and after that is is just these retries until timeout:

```shell
07:35:24  2022-10-13T05:35:24.275Z cypress:server:browsers:browser-cri-client error finding browser target, maybe retrying { delay: 100, err: ProtocolError: this.browsingContext.currentWindowGlobal is null (get title@chrome://remote/content/cdp/targets/TabTarget.jsm:117:5 _getTargetInfo@chrome://remote/content/cdp/domains/parent/Target.jsm:186:7 getTargets@chrome://remote/content/cdp/domains/parent/Target.jsm:69:29 execute@chrome://remote/content/cdp/domains/DomainCache.jsm:103:25 execute@chrome://remote/content/cdp/sessions/Session.jsm:66:25 onPacket@chrome://remote/content/cdp/CDPConnection.jsm:275:36 onMessage@chrome://remote/content/server/WebSocketTransport.jsm:91:18 handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:73:14 ) at /root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/lib/chrome.js:94:35 at Chrome._handleMessage (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/lib/chrome.js:257:17) at WebSocket.<anonymous> (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/lib/chrome.js:235:22) at WebSocket.emit (node:events:527:28) at WebSocket.emit (node:domain:475:12) at Receiver.receiverOnMessage (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:1047:20) at Receiver.emit (node:events:527:28) at Receiver.emit (node:domain:475:12) at Receiver.dataMessage (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:517:14) at Receiver.getData (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:435:17) at Receiver.startLoop (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:143:22) at Receiver._write (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:78:10) at writeOrBuffer (node:internal/streams/writable:389:12) at _write (node:internal/streams/writable:330:10) at Receiver.Writable.write (node:internal/streams/writable:334:10) at Socket.socketOnData (/root/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:1141:35) at Socket.emit (node:events:527:28) at Socket.emit (node:domain:475:12) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23) { request: { method: 'Target.getTargets', params: undefined, sessionId: undefined }, response: { message: 'this.browsingContext.currentWindowGlobal is null', data: 'get title@chrome://remote/content/cdp/targets/TabTarget.jsm:117:5\n' + '_getTargetInfo@chrome://remote/content/cdp/domains/parent/Target.jsm:186:7\n' + 'getTargets@chrome://remote/content/cdp/domains/parent/Target.jsm:69:29\n' + 'execute@chrome://remote/content/cdp/domains/DomainCache.jsm:103:25\n' + 'execute@chrome://remote/content/cdp/sessions/Session.jsm:66:25\n' + 'onPacket@chrome://remote/content/cdp/CDPConnection.jsm:275:36\n' + 'onMessage@chrome://remote/content/server/WebSocketTransport.jsm:91:18\n' + 'handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:73:14\n' } } }
```
any idea, what this may be caused by?

**Comment by warrensplayer** [comment] 2022-10-18 00:07
@brentsharon @audriusnavickasDB @radekBednarik Are any of you able to provide a reproduction project to help recreate the issue?  I am not able to reproduce the problem.  Can you also confirm if you are on Firefox v105.0.3?

If you could also provide the debug logs using `DEBUG=cypress:network:connect,cypress:server:browsers:firefox-util,cypress:server:browsers:browser-cri-client`, then that would be very helpful as well.

**Comment by audriusnavickasDB** [comment] 2022-10-18 05:56
@warrensplayer Well the case I'm experiencing is reproducible here in separate ticket: https://github.com/cypress-io/cypress/issues/24236

**Comment by mikewolfd** [comment] 2022-10-19 16:08
I also see this issue on 105.0.3 in headless mode in our CICD and locally using 10.10.0. Wiped everything locally including the Application Support data for both applications.

**Comment by whimboo** [comment] 2022-10-24 09:44
Could anyone seeing this issue please check the last comment from @warrensplayer and provide detailed logs? Thanks.

**Comment by amehta265** [comment] 2022-10-31 14:00
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by amehta265** 2022-10-31 14:00 UTC
