### ISSUE TITLE
Timed out waiting for the browser to connect. Retrying...

### ISSUE THREAD

**Issue by alexandruiftime** [cypress-io/cypress#14816] opened 2021-01-29 07:52 UTC
Hi,

I am facing an issue with all my CI jobs running through jenkins, I already have this issue for about 2-3 months, so it happens on different version of cypress.
 I am getting this error:
```
Timed out waiting for the browser to connect. Retrying...
EPERM: operation not permitted, unlink 'C:\Users\WebAutomation\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-7940\CypressCache\Default\Cache\data_2'
Error: EPERM: operation not permitted, unlink 'C:\Users\WebAutomation\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-7940\CypressCache\Default\Cache\data_2'
```

The command using for running tests is : `npx cypress run --browser chrome --spec`

So all works perfect if I run the tests directly from the command line, the executions goes till the end without any error. I encounter this issue only when test are running through Jenkins. I already tried to reinstall completely the machine where jenkins is installed (windows, jenkins, npm, cypress).
My test runs have between 30-60 test cases. The error above can appear at the beginning of the test run, just before even executing any test, or somewhere in the middle (after 3 tesst, or after 20, all the time is different). I also have runs which goes till the end from time to time.

But most important to specify as I said above its happening only when triggered from Jenkins, running manually from cmd works fine.

**Comment by jennifer-shehane** [comment] 2021-02-02 04:41
EPERM is a permissions error. You'll need to verify the correct permissions are set for whatever is involving the the CypressCache. The 'Timed our retrying' is a separate warning and unrelated.

**Comment by jennifer-shehane** [comment] 2021-02-02 04:41
Also update to 6.4.0 as the retry warnings do not display anymore and will more accurate highlight your issue.

**Comment by jennifer-shehane** [comment] 2021-02-02 07:47
Actually this is a duplicate of https://github.com/cypress-io/cypress/issues/14644 but do try to update and see if it's fixed

**Closed by jennifer-shehane** 2021-02-02 07:47 UTC
Labels: stage: awaiting response
