### ISSUE TITLE
route2 stub not matched for cross origin request

### ISSUE THREAD

**Issue by ncjones** [cypress-io/cypress#8920] opened 2020-10-22 00:33 UTC
### Current behavior

Route2 stubbed response is not matched for cross origin call. Seems like a regression of #8487. Might be the same as #8815 and might be fixed by #8827.

The workaround is to replace the cross origin request with a same origin request (localhost, non-tls works for me) or downgrade from 5.4 to 5.3.

### Desired behavior

Route2 stubbed response should match cross origin call.

### Test code to reproduce

```js
/* app.js */
fetch('https://cognito-idp.us-east-1.amazonaws.com/', {
  method: 'POST',
  headers: {
    'X-Amz-Target': 'AWSCognitoIdentityProviderService.InitiateAuth',
    'Content-Type': 'application/x-amz-json-1.1',
  },
  body: JSON.stringify({
    AuthFlow: 'CUSTOM_AUTH',
    ClientId: clientId,
    AuthParameters: {
      USERNAME: username,
    },
  }),
});
```

```js
/* spec.js */
cy.route2({ method: 'POST', url: 'https://cognito-idp.us-east-1.amazonaws.com/' }, { body: 'ok' });
cy.visit('/');
```

### Versions

5.4

**Comment by jennifer-shehane** [comment] 2020-10-22 06:59
Can you provide a failing test to show the behavior you're describing? Or a screenshot of the failing test? 

Was trying to reproduce with the test code below:

```js
it('works', () => {
  cy.route2({ 
    method: 'POST', 
    url: 'https://cognito-idp.us-east-1.amazonaws.com/' 
  }, { body: 'ok' })
  .as('post')

  cy.visit('https://example.com')

  cy.window().then((win) => {
    win.fetch('https://cognito-idp.us-east-1.amazonaws.com/', {
      method: 'POST',
      headers: {
        'X-Amz-Target': 'AWSCognitoIdentityProviderService.InitiateAuth',
        'Content-Type': 'application/x-amz-json-1.1',
      },
      body: JSON.stringify({
        AuthFlow: 'CUSTOM_AUTH',
        ClientId: 'foo',
        AuthParameters: {
          USERNAME: 'bar',
        },
      }),
    })
  })

  cy.wait('@post').its('response.body').should('eq', 'ok')
})
```

<img width="449" alt="Screen Shot 2020-10-22 at 1 29 15 PM" src="https://user-images.githubusercontent.com/1271364/96836172-9abb7f00-146a-11eb-992c-a198638d114d.png">

**Comment by ncjones** [comment] 2020-10-22 10:09
Hmm, your test works for me. I wonder if we have a fetch polyfill which is causing an issue. I just switched from axios to fetch in order to take advantage of route2. Do you know if there is a way to make route2 work with axios/xhr so I don't need to use fetch?

**Comment by flotwig** [comment] 2020-10-22 13:53
It should work the same for fetch and XHR, route2 handles requests at the network layer so there is no difference.

@ncjones there is an existing issue with route2 where, if you stub an HTTPS origin while you already have an open HTTP Keep-Alive connection to that HTTPS origin, subsequent requests to that HTTPS origin will not be intercepted. It will be fixed in 5.5.0. That might be the source of the problem you are experiencing, if you have already sent a request to that origin before setting up the route2 interceptor.

**Comment by ncjones** [comment] 2020-10-23 01:37
I forgot to mention I'm using Firefox. I've tried many combinations of XHR vs Fetch, Firefox vs Chrome, same origin vs CORS, and Docker vs local. The only combination that works for me is fetch on firefox with same origin on localhost. Very frustrating.

**Comment by ncjones** [comment] 2020-10-23 18:05
I have made some progress:

 * Removing `cy.server({ force404: true })` call at the start of my test fixed XHR with route2 stubs.
 * Adding `{ 'access-control-allow-origin', '*' }` response header on my route2 stubs (mostly) fixed cross-origin requests.
 * Deduplicating headers sent via window.fetch that my route2 was matching on fixed my issue with Chrome (Firefox automatically deduped the header).

One stubbed cross-origin API call is still failing for me in Docker using both XHR and Fetch. The error I see in the browser console is "TypeError: Failed to fetch" on Chrome and "TypeError: NetworkError when attempting to fetch resource" on Firefox. The test is working fine in the Cypress GUI on Mac but failing in Docker.

**Comment by bhgsbatista** [comment] 2020-11-13 22:37
I'm having the same problem on 5.6. Any updates?

**Comment by flotwig** [comment] 2020-11-16 18:25
> One stubbed cross-origin API call is still failing for me in Docker using both XHR and Fetch. The error I see in the browser console is "TypeError: Failed to fetch" on Chrome and "TypeError: NetworkError when attempting to fetch resource" on Firefox. The test is working fine in the Cypress GUI on Mac but failing in Docker.

@ncjones Since the OP has been resolved, can you open a new issue for this if you are still encountering it? Will make it easier to track. I think I have seen another user running in to something similar.

@bhgsbatista for the same reason, can you open a new issue describing what you're experiencing please?

**Closed by flotwig** 2020-11-16 18:25 UTC
Labels: pkg/net-stubbing, stage: needs information

**Comment by bhgsbatista** [comment] 2020-11-16 20:24
@flotwig I solved my problem by forcing the URL into lower case. It had mixed upper and lower case letters which interfered with the pattern matching it seems.
