### ISSUE TITLE
Upgrade to 8.5.0 The Test Runner unexpectedly exited via a exit event with signal SIGABRT

### ISSUE THREAD

**Issue by OlwenCX** [cypress-io/cypress#18291] opened 2021-09-29 11:30 UTC
### Current behavior

`The Test Runner unexpectedly exited via a exit event with signal SIGABRT`

Platform: darwin (20.6.0)
Cypress Version: 8.5.0

I am restricted to node version 14. 

Is 8.5.0 compatible with node 14? 

Thanks

See stack trace below:

```
yarn cy
yarn run v1.22.11
$ cypress open-ct
[@cypress/webpack-dev-server]: removing HtmlWebpackPlugin from configuration.
ℹ ｢wds｣: Project is running at http://localhost:53339/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /__cypress/src
ℹ ｢wds｣: Content not from webpack is served from /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp
GET /__/ 200 8.974 ms - -
GET /__cypress/runner/cypress_runner.css 200 44.524 ms - -
GET /__cypress/runner/cypress_runner.js 200 29.684 ms - -
GET /chrome-variations/seed?osname=mac&channel=stable&milestone=94 304 599.341 ms - -
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 610.280 ms - -
GET /__cypress/runner/favicon.ico 200 5.270 ms - -
GET /__/ctChunk-reactdevtools.css 200 3.345 ms - 304
GET /__/ctChunk-reactdevtools.b277574baaba7359e3a3.js 200 5.650 ms - -
GET /__/vendors~ctChunk-reactdevtools.71f4c4a828a7b7522abe.js 200 9.318 ms - -
GET /__cypress/runner/fonts/open-sans-latin-400-normal.woff2 200 20.700 ms - 14380
GET /__cypress/runner/fonts/mulish-latin-400-normal.woff2 200 28.601 ms - 31176
GET /__cypress/runner/fonts/mulish-latin-500-normal.woff2 200 23.859 ms - 31176
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 28.283 ms - 76120
GET /v1/pages/ChNDaHJvbWUvOTQuMC40NjA2LjYxEh4Jx9hhzm5qLs8SBQ227b-SEgUNL4g-ghIFDZFhlU4=?alt=proto 200 586.208 ms - -
## There is an issue with `node-fibers` ##
`/Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/fibers/bin/darwin-x64-89/fibers.node` is missing.

Try running this to fix the issue: /Users/Olwen.Davies/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Frameworks/Cypress Helper.app/Contents/MacOS/Cypress Helper /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/fibers/build
Error: Cannot find module '/Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/fibers/bin/darwin-x64-89/fibers'
Require stack:
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/fibers/fibers.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/sass-loader/dist/utils.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/sass-loader/dist/index.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/sass-loader/dist/cjs.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/loader-runner/lib/loadLoader.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/webpack/lib/NormalModule.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/webpack/lib/Compiler.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/webpack/lib/webpack.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/@cypress/webpack-dev-server/dist/startServer.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/@cypress/webpack-dev-server/dist/index.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/@cypress/react/plugins/react-scripts/index.js
- /Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/cypress/plugins/index.js
- /Users/Olwen.Davies/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/Olwen.Davies/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.Module._resolveFilename (/Users/Olwen.Davies/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Object.require.extensions.<computed> [as .js] (/Users/Olwen.Davies/Library/Caches/Cypress/8.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:529:44)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getSassOptions (/Users/Olwen.Davies/CX-p012/cx-p012-agent-ccp/src/webapp/node_modules/sass-loader/dist/utils.js:140:25)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT
```

### Desired behavior

Prior to upgrade to 8.5.0 `"cypress open-ct",` opened the Cypress UI and was working to run tests via Storybook. 

### Test code to reproduce

yarn cy

### Cypress Version

8.5.0

**Comment by emilyrohrbough** [comment] 2022-01-25 21:11
@OlwenCX if you read the stack trace, the error is related to a fiber's issue. I'd remove your node_modules and try re-installing the project to see if this resolves your issue.

**Comment by emilyrohrbough** [comment] 2022-03-18 13:37
@OlwenCX I am going to close this as duplicate of #https://github.com/cypress-io/cypress/issues/17849 to keep information in one place.

**Closed by emilyrohrbough** 2022-03-18 13:37 UTC
Labels: stage: awaiting response
