### ISSUE TITLE
Using .should('contain', 'text') Cypress returns timedout on cy.srceenshot when visit a new url

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#6962] opened 2020-04-08 03:53 UTC
### Current behavior:
Assertion .should('contian', 'text') when visit a new url element, but error cy.screenshot timeout
can click this text ,but not add assert.
      cy.xpath('//a[text()="text"]').should('contain', 'text')
      cy.xpath('//span[text()="text"]').click()

### Versions

Cypress: 4.2.0
Chrome: 80.0.3987.149 and 80.0.3987.163
OS: MacOS Catalina 10.15.4

**Comment by jennifer-shehane** [comment] 2020-04-08 04:45
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

The test code I ran:

```html
<!DOCTYPE html>
<html>
<body>
  <a>text</a>
</body>
</html>
```

```js
require('cypress-xpath')

it('testing', () => {
  cy.visit('index.html')
  cy.xpath('//a[text()="text"]').should('contain', 'text')
})
```

<img width="463" alt="Screen Shot 2020-04-08 at 11 15 38 AM" src="https://user-images.githubusercontent.com/1271364/78745482-4b0fdd00-798a-11ea-9b74-d90fdfc84284.png">


Please comment in this issue with a reproducible example (HTML and test code to reproduce completely) and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-04-08 04:45 UTC

**Comment by mingyixu** [comment] 2020-04-08 05:58
@jennifer-shehane ： the issue is visit another url,  open a new tab for jumping .
 require('cypress-xpath')

it('testing', () => {
  cy.visit('index.html')
  cy.xpath('//a[text()="text"]').should('contain', 'text')  //success

  cy.visit('index1.html')
  cy.xpath('//a[text()="text"]').should('contain', 'text')  //failure
})

**Comment by jennifer-shehane** [comment] 2020-04-08 08:55
Assuming both the `index.html` and `index1.html` are both containing the anchor with 'text', this test passes. **Please provide a full example that you have run completely before commenting to ensure it fails.**

`index.html` and `index1.html` contain same HTML.

```html
<!DOCTYPE html>
<html>
<body>
  <a>text</a>
</body>
</html>
```

```js
require('cypress-xpath')

it('testing', () => {
  cy.visit('index.html')
  cy.xpath('//a[text()="text"]').should('contain', 'text')  //success

  cy.visit('index1.html')
  cy.xpath('//a[text()="text"]').should('contain', 'text')  //failure
})
```

**Comment by mingyixu** [comment] 2020-04-08 09:31
@jennifer-shehane ： this is my testcase,  fail on the second visit， can repeat.

require('cypress-xpath')

describe('test_name', function() {

 it('what_it_does', function() {

    cy.viewport(1536, 763)
 
    cy.visit('https://ons.console.aliyun.com/?spm=5176.234368.1278132.btn1.3177db25Crltkg#/?regionId=cn-hangzhou&instanceId=MQ_INST_1542970758516810_BbyASPOo')
 
    cy.wait(1000)
    cy.xpath('//div[text()="概览"]').click()
 
    cy.wait(4000)
    cy.xpath('//button[text()="新建实例"]').click()
 
    cy.visit('https://common-buy.aliyun.com/?commodityCode=onsMqtt#/buy')
 
    cy.wait(1000)
    cy.xpath('//div[text()="text"]').should('contain', 'text')
 
 })
})

1) test_name
       what_it_does:
     CypressError: cy.screenshot() timed out waiting '30000ms' to complete.
      at Object.cypressErr (https://passport.aliyun.com/__cypress/runner/cypress_runner.js:104968:11)
      at Object.throwErr (https://passport.aliyun.com/__cypress/runner/cypress_runner.js:104923:18)
      at Object.throwErrByPath (https://passport.aliyun.com/__cypress/runner/cypress_runner.js:104955:17)

**Comment by jennifer-shehane** [comment] 2020-04-14 08:37
I'm not able to run the tests beyond the 4th command during `cypress open` (which seems to be a bug in itself). Do you have any settings in your `cypress.json` or `support` / `plugins` files that are necessary to run these tests?

<img width="532" alt="Screen Shot 2020-04-14 at 2 58 33 PM" src="https://user-images.githubusercontent.com/1271364/79203442-0e982180-7e61-11ea-93c8-b9e0b38e30e6.png">
