### ISSUE TITLE
Warn on making DOM assertions on non-DOM subjects

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#130] opened 2016-05-06 16:26 UTC
When making DOM assertions on non-DOM subjects, the command log prints:
`CypressError: Timed out retrying: r(...)[e] is not a function`. This should instead throw an error saying something to the effect of:

```
CypressError: Cannot make assertion 'have.attr' on a non-DOM subject!
```

**Example Code**

``` javascript
cy
  .get("input")
     .should('have.attr', 'style', 'color: orange;') // changes subject to string
     .and('have.attr', 'type', 'password')           // can't use 'have.attr' on string subject
```

**Example Error**
![screen shot 2016-05-06 at 12 21 07 pm](https://cloud.githubusercontent.com/assets/1271364/15079241/62f52e6c-1385-11e6-88d4-21fb8b77f648.png)

**Comment by brian-mann** [comment] 2017-09-13 14:41
Duplicate of https://github.com/cypress-io/cypress/issues/604

This has been fixed.

**Closed by brian-mann** 2017-09-13 14:41 UTC
Labels: bug, enhancement
