### ISSUE TITLE
Cypress unexpectedly hangs when running tests on Codeship CI

### ISSUE THREAD

**Issue by rufushonour** [cypress-io/cypress#1890] opened 2018-06-06 19:44 UTC
### Current behavior:
We have parallel tests running a suite of specs on Codeship Pro, completely dockerised setup. One container running our app, one the database and one cypress for each parallel run.

In the last month or so, we've been seeing our CI hang randomly on different specs. They can fail on one build and pass after being restarted. 

I have no errors in the logs. 

The behaviour is very weird. It will run an random number of specs and then stop dead. On each run, its a different spec file that decides to hang. I have set DEBUG to cypress:* but when it hangs, I just get messages about waiting for an event. 

Everything works fine running on my dev machine. 

Any ideas to what could be causing it?

### Desired behavior:
All tests run and output correctly, fail/pass

### Steps to reproduce:
Not sure how to reproduce as completely random.

### Versions

Cypress 3.0.1
Docker on Codeship

**Comment by brandonb927** [comment] 2018-06-06 20:09
I normally don't do this, but +1 here.

Since upgrading to Cypress v3.0.1 we've also been seeing random hangs on Jenkins builds that run our Cypress tests in headless mode. It is intermittent and we're not sure how to reproduce as it will hang the build on different specs while running.

**Comment by jennifer-shehane** [comment] 2018-06-06 20:18
Could you paste the error message/exit message from one of these previously failing runs?

**Comment by brandonb927** [comment] 2018-06-06 21:43
This is the exact issue with our situation as well: there is no exist code and there is no error, and the last message in `STDOUT` is the spec name.

**Comment by rufushonour** [comment] 2018-06-07 08:50
I've just noticed that my issue seems to be related to CORS. However, I'm not really sure exactly whats going on or whats actually causing this. There seems to be a bug where cypress doesn't report that it failed and just gets stuck.

`Thu, 07 Jun 2018 08:19:36 GMT cypress:server:reporter got mocha event 'fail' with args: [ { id: 'r3', title: 'completed project display a closed banner', err: { message: 'Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt\'s possible to enable debugging these scripts by adding the \'crossorigin\' attribute and setting a CORS header.\n\nhttps://on.cypress.io/cross-origin-script-error\n\nThis error originated from your application code, not from Cypress.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the \'uncaught:exception\' event.\n\nhttps://on.cypress.io/uncaught-exception-from-application', name: 'Uncaught Error', stack: 'Uncaught Error: Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt\'s possible to enable debugging these scripts by adding the \'crossorigin\' attribute and setting a CORS header.\n\nhttps://on.cypress.io/cross-origin-script-error\n\nThis error originated from your application code, not from Cypress.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the \'uncaught:exception\' event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at createErrFromMsg (http://gaudi:3000/__cypress/runner/cypress_runner.js:61362:14)\n    at Object.createUncaughtException (http://gaudi:3000/__cypress/runner/cypress_runner.js:61369:13)\n    at Object.onUncaughtException (http://gaudi:3000/__cypress/runner/cypress_runner.js:63919:20)\n    at onError (http://gaudi:3000/__cypress/runner/cypress_runner.js:63393:39)' }, state: 'failed', body: 'function (done) {\n    production.newDesignFeedbackScenario(projects.COMPLETED_DESIGN_FEEDBACK_PROJECT).then(function (scenario) {\n      var anon = scenario.newAnonymousUser();\n\n      anon.seesProjectIsClosed().then(function () {\n        return done();\n      });\n    });\n  }', type: 'test', duration: 940, wallClockStartedAt: '2018-06-07T08:19:35.281Z', timings: { lifecycle: 65, 'before all': [Array], test: [Object] } } ]`

**Comment by SanderMeester** [comment] 2018-06-11 09:46
+1; same issue on TFS. It just hangs without any feedback about why. So the tests work fine on my local-machine, but since upgrading to 3.0.1 the cli hangs randomly on my build-server.

**Comment by neutcomp** [comment] 2018-06-11 13:40
+1 totally agree with SanderMeester and rufushonour. Hope there will be an quick fix for this.

**Comment by gugahoi** [comment] 2018-06-12 01:42
We used to see the same thing in `v2` but it seems like upgrading to `v3` made it so that it hangs more often. Also running in CI with docker, cypress is actually running in the same container talking over `localhost` and yet it hangs every now and then. When things are good the steps take a little over 2 minutes so it should be pretty quick.

**Closed** 2018-06-25 20:09 UTC
Labels: stage: needs information

**Comment by brian-mann** [comment] 2018-06-29 09:12
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
