### ISSUE TITLE
Error when running command ->>> npm install cypress --save-dev Failed at the cypress@4.12.1 postinstall script.

### ISSUE THREAD

**Issue by rohit-24** [cypress-io/cypress#8218] opened 2020-08-07 12:34 UTC
### Current behavior:

Error when running command ->>> `npm install cypress --save-dev` 
```
npm ERR! path C:\Windows\system32\cmd.exe;BrowserServers\\chromedriver.exe
npm ERR! errno ENOENT
npm ERR! cypress@4.12.1 postinstall: `node index.js --exec install`
npm ERR! spawn C:\Windows\system32\cmd.exe;BrowserServers\\chromedriver.exe ENOENT
npm ERR!
npm ERR! Failed at the cypress@4.12.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-07T12_33_09_219Z-debug.log
```

### Desired behavior:

Cypress should be installed 

### Versions

Windows 7 - 64 bit

**Comment by jennifer-shehane** [comment] 2020-08-11 06:37
Can you post the DEBUG logs at `C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-07T12_33_09_219Z-debug.log`?

Could you run the install in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by rohit-24** [comment] 2020-08-11 06:55
> Can you post the DEBUG logs at `C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-07T12_33_09_219Z-debug.log`?
> 
> Could you run the install in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

[2020-08-11T06_45_13_632Z-debug.log](https://github.com/cypress-io/cypress/files/5055247/2020-08-11T06_45_13_632Z-debug.log)

**Comment by rohit-24** [comment] 2020-08-11 06:55
> > Can you post the DEBUG logs at `C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-07T12_33_09_219Z-debug.log`?
> > Could you run the install in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
> 
> [2020-08-11T06_45_13_632Z-debug.log](https://github.com/cypress-io/cypress/files/5055247/2020-08-11T06_45_13_632Z-debug.log)

I have attached the file , could not upload in comments , beceause of huge size of logs

**Comment by jennifer-shehane** [comment] 2020-08-18 06:46
Duplicate of #6807 

```
5321 verbose stack Error: cypress@4.12.1 postinstall: `node index.js --exec install`
5321 verbose stack spawn C:\Windows\system32\cmd.exe;BrowserServers\\chromedriver.exe ENOENT
5321 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
5321 verbose stack     at onErrorNT (internal/child_process.js:469:16)
5321 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Closed by jennifer-shehane** 2020-08-18 06:46 UTC
Labels: stage: needs information
