### ISSUE TITLE
File going through event triggers are losing their properties

### ISSUE THREAD

**Issue by lsenta** [cypress-io/cypress#3613] opened 2019-02-28 11:02 UTC
Hi there, thanks for maintaining and supporting Cypress.

### Current behavior:

When I load a file from my tests and pass it through a `trigger()` function, `file instanceof File` goes to false. Which breaks the rest of my code (firebase storage upload).

```js
// In my test:
const type = 'application/pdf';

return cy.readFile(p, 'base64')
      .then((x) => Cypress.Blob.base64StringToBlob(x, type))
      .then((content) => {
        const testfile = new w.File([content], 'my-script.pdf', { type });

        console.error('testfile instanceof Blob', testfile instanceof Blob); // true
        console.error('testfile instanceof File', testfile instanceof File); // true
        console.error('testfile instanceof w.File', testfile instanceof window.File); // true

        const dataTransfer = new DataTransfer();
        dataTransfer.items.add(testfile);

        return cy.get('file-upload section').trigger('drop', {
          dataTransfer: {
            files: {
              0: testfile,
              item: () => testfile,
              length: 1
            }
          }
        });
      });
```

```js
// in the event:
    console.error('file instanceof Blob', file instanceof Blob); // false
    console.error('file instanceof File', file instanceof File); // false
```

### Desired behavior:

The file passed through the event should preserve all its characteristics.

### Steps to reproduce: (app code and test code)

Clone https://github.com/lsenta/cypress-test-tiny

```sh
python -m SimpleHTTPServer 3007 # serves the index.html
```
```sh
npm run cypress:open --base-url=https://localhost:3007 # opens cypress
```

Run the test, and check the log output, it'll show that testfile is and instanceof File then the file in the event is not.
Screenshot of the output:
https://github.com/lsenta/cypress-test-tiny/blob/master/Screenshot%202019-02-28%20at%2011.59.27.png

### Versions

MacOS, cypress 3.1.5, default Chrome.

Thanks in advance for taking a look,

**Comment by jennifer-shehane** [comment] 2019-02-28 16:28
Duplicate of https://github.com/cypress-io/cypress/issues/3420

**Closed by jennifer-shehane** 2019-02-28 16:28 UTC
