### ISSUE TITLE
Calling mochawesome addContext throws error in TypeScript spec files.

### ISSUE THREAD

**Issue by rsi21** [cypress-io/cypress#8374] opened 2020-08-21 10:22 UTC
### Current behavior:

Hi,

I started to use Cypress recently, so i started with v4.12.1, i integrate also `mochawesome` to generate reports and everything works fine. But when i tested the 5.0, my test hangs when an assertion is thrown.

I tough first it was caused by `.should()` as seen in other issues. (#8363)

But it seems related to `mochawesome` integration, i added a script to add context on failures with an after run event.

Without the `addContext` from `mochawesome`, everything works fine.

Retries doesn't change anything, it hangs on first attempt, so no matter its value.

I wish the use case is clear :)

Thanks

### Desired behavior:

The run must continue or make new attempts after an assertion.

### Test code to reproduce

The last retry test was only for test, otherwise if hangs on first attempt directly instead of last one.

- support/index.ts:
```ts
import addContext from 'mochawesome/addContext';

Cypress.on('test:after:run', (test, runnable) => {
    // Adding context only on last retry
    if (test.state === 'failed' && test.currentRetry === test.retries) {
        addContext({ test }, 'boomm');
    }
});
```

I get the same test code form #8363 to reproduce :

- index.html
```html
<html>
  <body>
    <div>bar</div>
  </body>
</html>
```

- spec.js:
```js
it('test', () => {
  cy.visit('index.html')
  cy.get('div').should('contain', 'foo')
})
```

- cypress.json:
```json
{
    "baseUrl": "http://localhost:4200/",
    "reporter": "mochawesome",
    "retries": {
        "runMode": 3,
        "openMode": 3
    }
}
```

### Versions

5.0.0

**Comment by jennifer-shehane** [comment] 2020-08-24 06:45
I can't reproduce the issue using the code provided. 

There is an issue where tests will hang if there is an error thrown from within a `test:after:run` handler, because Cypress silently captures them and doesn't throw them. There's a possibility that is this issue - where there's an error being thrown in the addContext somewhere. https://github.com/cypress-io/cypress/issues/2271

Please provide a fully reproducible example and we will consider reopening.

**Code I ran**

```spec.js
import addContext from 'mochawesome/addContext';

Cypress.on('test:after:run', (test, runnable) => {
  // Adding context only on last retry
  if (test.state === 'failed' && test.currentRetry === test.retries) {
    addContext({ test }, 'boomm');
  }
})

it('test', () => {
  cy.visit('index.html')
  cy.get('div').should('contain', 'foo')
})

it('test', () => {
  expect(true).to.be.false
})

it('test', () => {
  expect(true).to.be.true
})
```

`index.html`

```html
<html>
<body>
  <div></div>
</body>
</html>
```

`package.json`

```json
{
  "devDependencies": {
    "cypress": "5.0.0",
    "mochawesome": "^6.1.1"
  }
}
```

`cypress.json`

```json
{
  "retries": {
    "runMode": 3,
    "openMode": 3
  }
}
```

<img width="530" alt="Screen Shot 2020-08-24 at 1 14 49 PM" src="https://user-images.githubusercontent.com/1271364/91012264-d02f2200-e60b-11ea-8487-91c7d6559a67.png">

**Comment by rsi21** [comment] 2020-08-24 08:25
> Does it still hang if you remove ` && test.currentRetry === test.retries`? I am running mochawesome with Cypres 5.0 without any issues. Are you sure you have the latest version of mochawesome and related dependencies?

Hi, yes the test doesn't change anything, i added it because i tought first taht it could be a problem with several attempts so i limited to last one only. And for the dependencies, i have the latest ones too.

**Comment by rsi21** [comment] 2020-08-24 08:30
> I can't reproduce the issue using the code provided.
> 
> There is an issue where tests will hang if there is an error thrown from within a `test:after:run` handler, because Cypress silently captures them and doesn't throw them. There's a possibility that is this issue - where there's an error being thrown in the addContext somewhere. #2271
> 
> Please provide a fully reproducible example and we will consider reopening.
> 
> **Code I ran**
> 
> ```js
> import addContext from 'mochawesome/addContext';
> 
> Cypress.on('test:after:run', (test, runnable) => {
>   // Adding context only on last retry
>   if (test.state === 'failed' && test.currentRetry === test.retries) {
>     addContext({ test }, 'boomm');
>   }
> })
> 
> it('test', () => {
>   cy.visit('index.html')
>   cy.get('div').should('contain', 'foo')
> })
> 
> it('test', () => {
>   expect(true).to.be.false
> })
> 
> it('test', () => {
>   expect(true).to.be.true
> })
> ```
> 
> `index.html`
> 
> ```
> <html>
> <body>
>   <div></div>
> </body>
> </html>
> ```
> 
> `package.json`
> 
> ```json
> {
>   "devDependencies": {
>     "cypress": "5.0.0",
>     "mochawesome": "^6.1.1"
>   }
> }
> ```
> 
> `cypress.json`
> 
> ```json
> {
>   "retries": {
>     "runMode": 3,
>     "openMode": 3
>   }
> }
> ```
> 
> <img alt="Screen Shot 2020-08-24 at 1 14 49 PM" width="530" src="https://user-images.githubusercontent.com/1271364/91012264-d02f2200-e60b-11ea-8487-91c7d6559a67.png">

Hi,
Thanks for the linked issue, i will have a look and make again a test with a new project, without uneeded dependencies. Otherwise it was the same code than you and same dependencies versions for cypress and mochawesome.

**Comment by rsi21** [comment] 2020-08-24 10:28
Hi,

I think i finally found out the reason, 
When we installed Cypress we wanted to use Typescript to write tests and commands, and also get advantage of our lint configuration + completion.
So we applied this:
https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Reference-type-declarations-via-tsconfig
And I renamed all the js files to ts files, including support/index.js
So may be it was a mistake here. Renaming again index.ts to js solves the problem when migrating to 5.0.0

So not related to mochawesome but typescript version i suppose.

I added my sample project in case of.
[cypress5-mochawesome.zip](https://github.com/cypress-io/cypress/files/5117221/cypress5-mochawesome.zip)

Thanks

**Comment by jennifer-shehane** [comment] 2020-08-24 10:45
Yeah, the reason this is hanging is due to #2271. This `addContext` call is throwing an exception when run in TypeScript that we are swallowing. 

Although the reason that this error should be throwing now in 5.0.0 and not in 4.12.1 is a regression.

<img width="1206" alt="Screen Shot 2020-08-24 at 5 04 15 PM" src="https://user-images.githubusercontent.com/1271364/91035052-fb296e00-e62b-11ea-9eb1-841851108cc4.png">

### Repro

`spec.ts`

```ts
import addContext from 'mochawesome/addContext';

it('test', () => {
  addContext({ foo: 'bar' }, 'boomm');
})
```

`package.json`

```json
{
  "devDependencies": {
    "cypress": "5.0.0",
    "mochawesome": "^6.1.1",
    "typescript": "^4.0.2"
  }
}
```

### 4.12.1 with JavaScript or TypeScript spec file

<img width="529" alt="Screen Shot 2020-08-24 at 5 15 08 PM" src="https://user-images.githubusercontent.com/1271364/91036460-61fb5700-e62d-11ea-8472-13922737d709.png">


### 5.0.0 with JavaScript spec file

<img width="527" alt="Screen Shot 2020-08-24 at 5 11 52 PM" src="https://user-images.githubusercontent.com/1271364/91036257-0630ce00-e62d-11ea-89d9-4449045fc5db.png">


### 5.0.0 with TypeScript spec file

<img width="527" alt="Screen Shot 2020-08-24 at 5 13 14 PM" src="https://user-images.githubusercontent.com/1271364/91036315-1d6fbb80-e62d-11ea-94ab-79ff6dcb3890.png">

**Comment by chrisbreiding** [comment] 2020-08-25 13:37
I wonder if this is related to the `esModuleInterop` change. Does setting `"esModuleInterop": true` in the `tsconfig.json` fix the "5.0.0 with TypeScript spec file" case @jennifer-shehane?

**Comment by jennifer-shehane** [comment] 2020-08-27 10:52
@chrisbreiding No, adding `"esModuleInterop": true` to the base or `cypress/integration` `tsconfig.json` does not get rid of this error.

**Comment by chrisbreiding** [comment] 2020-08-27 14:32
That's odd. I just tried it out and found turning `esModuleInterop` to `true` fixed the error. I had to close and open the file for the tsconfig change to take effect.

**Comment by chrisbreiding** [comment] 2020-08-27 15:01
The reason it worked before is because pre 5.0, we automatically set `esModuleInterop` to `true`. Now we don't and leave it up to what's in your tsconfig. The default for `esModuleInterop` is `false`, so that's why you now need to set it to `true`.

In regards to the version of TypeScript, we load the typescript you have installed in your project, so there shouldn't be any compatibility issues in that regard.

I'm going to close this as it's not a regression, it's just a consequence of the breaking change regarding `esModuleInterop` in 5.0.0.

**Closed by chrisbreiding** 2020-08-27 15:01 UTC
Labels: stage: needs investigating, topic: typescript, type: regression, v5.0.0 :bug:
