### ISSUE TITLE
cy.route onRequest block alters request

### ISSUE THREAD

**Issue by mwren-mshanken** [cypress-io/cypress#6035] opened 2019-12-23 18:38 UTC
### Current behavior: 

I am currently attempting to mock up a client server response pattern using Cypress.

I would like to:

- Use `cy.route` to catch a call to set data when I click a "save" button
- Write the response to a file using the `onResponse` parameter of my `cy.route`
- Use the contents of the file as my response for the same `cy.route` call

Currently, if I include either a `cy.writeFile`, or even a `console.log(cy.readFile(testFile))` command, I get an error when I call the route with a `cy.wait`.

Error:

```
application_actions.js:84 Uncaught (in promise) TypeError: Cannot read property 'statusText' of undefined
```

If I remove the `cy.writeFile` or `readFile` from my `onResponse` block the code executes fine.

It seems like `cy.route` is completely synchronous, so maybe this isn't possible, or maybe I am doing something wrong.

### Desired behavior:

I would like to be able to change data in a `cy.route`'s `onRequest` block, then return that data as the request of the same route

### Steps to reproduce: (app code and test code)

```javascript
beforeEach(() => {
      //call fixture file 
      cy.fixture('newApplication.json').as('newApplication')
      cy.server()
      //This first route is used when I load a page that contains application data. 
      //This works fine
      cy.route('GET', 'applications/*', '@newApplication').as('getNewApplication')
      //This route is hit when I click a Save Button to save updates to my application data
      cy.route({
        method: 'PATCH', 
        url: 'applications/update/*',
        onRequest: (xhr) => {
          cy.writeFile('cypress/fixtures/newApplication.json', xhr.request.body.application)
          },
        response: '@newApplication'
      })
      .as('updatedApplication')
      cy.visit('/admin/review_application/1')
      cy.wait('@getNewApplication')
      .its('response.headers')
      .its('content-type')
      .should('contain','application/json')
    });

it.only('Saving Restaurant Name changes page header text', () => {
      //Alter some application data
      cy.get('#Restaurant\\ Name')
        .clear()
        .type('Header Update Test');
      cy.get('#name-buttons\\ Accept').click();
      //Click save button to save data change
      clickSaveButton();
      //hit updatedApplication route when data is saved
      cy.wait('@updatedApplication').should('have.property','status',200)
      //Test fails on above wait every time
      cy.reload();
      cy.wait('@getNewApplication')
      cy.get('#Restaurant\\ Name').then($newText => {
          //compare text values to ensure the data change was saved
          cy.get('.MuiTypography-h2').then($headerText => {
          expect($headerText).to.have.text($newText.prop('value'));
        });
      });
```

If I change this code to use variables, rather than writing to file, instead of timing out on the wait, my response contains the value "chainer123" in the body, rather than the altered code.

Example:

```javascript
beforeEach(() => {
      //call fixture file 
      cy.fixture('newApplication.json').as('newApplication')
      cy.server()
      //This first route is used when I load a page that contains application data. 
      //This works fine
      cy.route('GET', 'applications/*', '@newApplication').as('getNewApplication')
      //This route is hit when I click a Save Button to save updates to my application data
     let jsonData = cy.readFile('/cypress/fixtures/newApplication.json') 
     cy.route({
        method: 'PATCH', 
        url: 'applications/update/*',
        onRequest: (xhr) => {
          jsonData = xhr.request.body.application)
          },
        response: jsonData
      })
      .as('updatedApplication')
      cy.visit('/admin/review_application/1')
      cy.wait('@getNewApplication')
      .its('response.headers')
      .its('content-type')
      .should('contain','application/json')
    });

it.only('Saving Restaurant Name changes page header text', () => {
      //Alter some application data
      cy.get('#Restaurant\\ Name')
        .clear()
        .type('Header Update Test');
      cy.get('#name-buttons\\ Accept').click();
      //Click save button to save data change
      clickSaveButton();
      //hit updatedApplication route when data is saved
      cy.wait('@updatedApplication').should('have.property','status',200)
      //Response is "chainer123" rather than the actual contents of jsonData
      ...
        });
      });
```

### Versions

Cypress 3.5.0, Chrome Version 79.0.3945.88

**Comment by sainthkh** [comment] 2021-01-06 05:57
[`cy.readFile()`](https://docs.cypress.io/api/commands/readfile.html#Syntax) doesn't return the content of the file. To get access to it, you need to chain `then()` after it. 

In your case, using `fs.readFileSync` might be the better solution. 

Closing this issue because it's old and the API is used in the wrong way. If the problem is still happening, please open a new issue with a reproducible example.

**Closed by sainthkh** 2021-01-06 05:57 UTC
