### ISSUE TITLE
cy.origin redirects inside embedded browser window but url of embedded browser does not change (Chrome and Electron)

### ISSUE THREAD

**Issue by sebamomann** [cypress-io/cypress#21988] opened 2022-05-31 20:18 UTC
### Current behavior

Upon clicking a "Login" button, the user gets redirected to the `/account/login` page (still localhost) and is then redirected to the  (Keycloak) IDP where the user should log in.

After the successful login, the content of the embedded browser changes, since after a successful login my IDP (Keycloak) redirects back to the AUT. But in some cases (more often than not) the URL does not change appropriately. The URL still shows the IDP URL (https://account.sebamomann.de/auth) . The runner also shows an error message saying it is still waiting for the page to load. 

![image](https://user-images.githubusercontent.com/46058597/171275107-1516e560-b227-49fe-a74c-ae9a1236ee43.png)
Image shows faulty URL (still IDP URL) but correct content (localhost) while "waiting for new page to load"

![Screenshot 2022-05-31 220552](https://user-images.githubusercontent.com/46058597/171275690-363005c3-d252-464c-bd84-e5646107450c.png)

After timeout the following error gets shown.

![Screenshot 2022-05-31 220639](https://user-images.githubusercontent.com/46058597/171275755-4a9a493a-6edb-4db4-8877-561d2c05072e.png)

Behaviour is observable in Chrome 101 and Electron 100.
Working fine in Firefox 100.

### Desired behavior

After a successful login on the IDP website the user shold be redirected back to the AUT (http://localhost:4200). The URL of the embedded Browser should also change, so further actions and URL comparisons can be made.

### Test code to reproduce

```js          
beforeEach(() => {
  cy.login_button().click();
  cy.fixture('user/user-1.json').then(function (user) {
      cy.keycloack_login_via_ui_isolated(user);
    });
});
``` 

Custom command looks as follows

```js
Cypress.Commands.add('keycloack_login_via_ui_isolated', (user) => {
  cy.origin(Cypress.env('KEYCLOAK_URL'), { args: { user } }, function ({ user }) {
    cy.get("#username")
      .type(user.username);
    cy.get("#password")
      .type(user.password);
    cy.get("[type=submit]")
      .click();
  });

  cy.origin("localhost:4200", () => {  
  });
});
``` 

### Cypress Version

9.6.0, 9.6.1, 9.7.0

### Other

behaviour is identical when not having 
```js
cy.origin("localhost:4200", () => {

});
```
after the testcase. This was just for debug purposes but has no effect. 
Error is now just shown at the first `cy.origin` instead of the second `cy.origin`

![image](https://user-images.githubusercontent.com/46058597/171276728-8a547d4b-2516-4aa6-a216-dcd26f449e43.png)

Possibly related to #21363

**Comment by mschile** [comment] 2022-06-02 21:06
@sebamomann, thanks for reporting this issue. Based on the login working correctly in Firefox I am inclined to believe that you are being impacted by our cookie handling. We are currently working on https://github.com/cypress-io/cypress/issues/20685 to improve our cookie handling.

I am going to close this issue as a duplicate of https://github.com/cypress-io/cypress/issues/20685. If you are still experiencing this issue after https://github.com/cypress-io/cypress/issues/20685 is resolved, please comment on this issue and we can reopen.

**Closed by mschile** 2022-06-02 21:06 UTC
Labels: stage: investigating

**Comment by idanElitzur** [comment] 2022-09-13 13:23
Still happens to me on cypress 10.7.0.
can you please post a reference how to handle this use case?
thanks

**Comment by sebamomann** [comment] 2022-09-14 11:33
I just revalidated it with 10.3.0, 10.7.0 and 10.8.0. All versions work fine in my case. 
Could not reproduce the error.

**Comment by idanElitzur** [comment] 2022-09-14 13:12
Actually this happens to me only when I'm using Chrome browser v105x
when using electron the `load` errors are not returning and the origin it works but the cookies of the session are not passing inside and the flow can't be done :/

**Comment by sebamomann** [comment] 2022-09-14 13:45
Said runs were on Chrome 104.
Tested Cypress 10.7.0 and 10.8.0 on Chrome 105. Works fine on my side.
