### ISSUE TITLE
Cypress Rendering PDF File

### ISSUE THREAD

**Issue by arkage88** [cypress-io/cypress#26871] opened 2023-05-29 07:49 UTC
### What would you like?

<img width="453" alt="Screenshot at May 29 14-46-46" src="https://github.com/cypress-io/cypress/assets/26951343/f6c6dea4-204a-450e-9d5e-9f4758c30bc9">

Can someone help me to fix this I already use 
Cypress.on("uncaught:exception", (err, runnable) => {
      console.log(err);
      return false;
    });

but can't handle this uncaught errors

**Comment by nagash77** [comment] 2023-05-30 13:15
@arkage88 , Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by arkage88** [comment] 2023-05-31 05:36
![photo_2023-05-30 09 34 55](https://github.com/cypress-io/cypress/assets/26951343/cd2f6607-e04b-4095-8ca2-ee606d370ae4)

@nagash77 (uncaught exception)
n: Renders
canceled, page 1 appears when a pop-up PDF file with three pages that may be zoomed in is displayed by a web application, as demonstrated in the screenshot above.

**Comment by nagash77** [comment] 2023-05-31 12:51
Hi @arkage88 unfortunately a screenshot is not enough information for our developers to reproduce and thus track down the cause of this problem.  Please refer back to my previous comment on providing a reproducible example.

**Comment by nagash77** [comment] 2023-06-07 13:44
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-06-07 13:44 UTC
