### ISSUE TITLE
Closing the Cypress runner using CTRL+C in the terminal causes an unexpected error

### ISSUE THREAD

**Issue by fricci-bread** [cypress-io/cypress#29463] opened 2024-05-02 14:23 UTC
### Current behavior

When the Cypress runner is open (run command is `npx cypress open`), I usually close the runner by entering CTRL+C in the terminal. This is now causing a "Cypress quit unexpectedly" error to appear, as well as the following terminal message:

"We detected that the Chrome browser process closed unexpectedly.

We have failed the current spec and aborted the run."

### Desired behavior

The Cypress runner should close without an error.

### Test code to reproduce

N/A

### Cypress Version

13.8.1

### Node version

20.11.1

### Operating System

macOS 14.3

**Comment by jennifer-shehane** [comment] 2024-05-02 15:28
Duplicate of https://github.com/cypress-io/cypress/issues/29232

**Closed as completed by jennifer-shehane** 2024-05-02 15:28 UTC
Labels: type: duplicate
