### ISSUE TITLE
Getting Timed out retrying after 4000ms: The command was expected to run against origin https://pfedcert.xxxxx.com but the application is at origin https://ims.stage.advertising.xxxxx.com.

### ISSUE THREAD

**Issue by yashpandey** [cypress-io/cypress#27143] opened 2023-06-27 05:27 UTC
### Current behavior

-  i have set my baseUrl as : "https://ims.stage.advertising.xxxxxxx.com/" which is the app url. 

- But there is a SSO login which validates through AD (active directory) whose url is  https://pfedcert.xxxxx.com 
- After completing the login functionality at the  https://pfedcert.xxxxx.com my app again gets redirected to the https://ims.stage.advertising.xxxxxxx.com/
- But cypress is considering origin to be  "https://pfedcert.xxxxx.com" rather than "https://ims.stage.advertising.xxxxxxx.com/"
- So when i am trying to access any web element at my app i.e."https://ims.stage.advertising.xxxxxxx.com/". I am getting below error 
- Timed out retrying after 4000ms: The command was expected to run against origin https://pfedcert.xxxxx.com but the application is at origin https://ims.stage.advertising.xxxxx.com.

### Desired behavior

I should not get any error while accessing any element of my app "https://ims.stage.advertising.xxxxxxx.com/"

### Test code to reproduce

`import {loginPage} from "../page_object/login.page";
import { imsLandingPage } from "../page_object/imsLanding.page";

const login = new loginPage()
const landingPage = new imsLandingPage()

describe('template spec', () => {
  it('passes', () => {
    
    login.login()
    cy.wait(15000)
 
      cy.get('[data-automation-id="date-range-container"]').click()
})})`

`
export class loginPage {
 login() {
 cy.visit('https://ims.stage.advertising.xxxxxxx.com/', {failOnStatusCode: false})
  } 
}     
`
### Cypress Version

v12.16.0

### Node version

v19.8.1

### Operating System

macOS ventura 13.4

**Comment by mike-plummer** [comment] 2023-06-27 13:06
Hi @yashpandey , thanks for reaching out. It appears that you're attempting to visit two different domains within a single Cypress test - you may want to review our guide on [Cross-Origin Testing](https://docs.cypress.io/guides/guides/cross-origin-testing) which explains some of the limitations of what you're trying to do. I suspect what you need is the [`cy.origin`](https://docs.cypress.io/api/commands/origin) API which allows you to operate part of your test against a different domain than another part of your test.

Since this appears to be a question around proper use rather than a bug in Cypress I'm going to close this issue - questions around how to use Cypress are best directed to our [Discord](https://on.cypress.io/discord) community. If you disagree and think you've found a bug after reviewing the documentation please comment here and I'll be happy to reopen. We would ask that you provide a reproducible example (ideally a `git` repo we can clone and run locally) and [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) to help diagnose your issue.

**Closed as not planned by mike-plummer** 2023-06-27 13:06 UTC
