### ISSUE TITLE
Rendering differences in 3.4.1 causing failures

### ISSUE THREAD

**Issue by drumbeg** [cypress-io/cypress#4885] opened 2019-07-31 10:34 UTC
### Current behavior:

We have dialogs that are not rendering properly since upgrading to 3.4.1 and elements are not scrolled into view when attempting interactions.

3.4.0

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1645007/62205297-0eb1c900-b387-11e9-9a8a-6b3fe4ce3086.png">

3.4.1

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1645007/62205137-acf15f00-b386-11e9-8fd6-bac33dd48b1d.png">

### Desired behavior:

Dialog should open full size so that elements can be clicked without {force: true}

### Steps to reproduce: (app code and test code)

Open a dialog with contents loaded via iFrame. Dialog is not sized properly.

### Versions

Cypress 3.4.1 Electron, MacOS 10.14.5

**Comment by jennifer-shehane** [comment] 2019-07-31 12:10
Do these elements you are trying to click happen to be `readonly`?

The rendering of the dialog should not have changed in Cypress at all - the scroll behavior, however could possibly changed. 

Can you provide the HTML and CSS of this dialog? We'll need all of this to recreate what's happening as it's likely very specific to the DOM structure. 

I also just want to clarify - you are running it in 3.4.1, downgrading and running in 3.4.0 and seeing this change? Same browser, everything?

**Comment by drumbeg** [comment] 2019-07-31 12:22
The elements are not readonly.

I will try to provide a generic test case for you. The application in question uses the Oracle APEX framework, which is very much declarative and offers up pre-canned HTML/CSS for these dialogs/modals.

My testing is as you describe. I am installing 3.4.1, testing, then installing 3.4.0 and repeating my test. No other changes made.

**Comment by sainthkh** [comment] 2020-11-13 06:35
Closing because there is no reproducible test. If it's still happening in 5.6.0+, please open a new issue with a reproducible example.

**Closed by sainthkh** 2020-11-13 06:35 UTC
