### ISSUE TITLE
Cypress suddenly stopped working on Ubuntu systems

### ISSUE THREAD

**Issue by rfftrifork** [cypress-io/cypress#7054] opened 2020-04-17 10:28 UTC
### Current behavior:

It get's stuck on the loading spinner of Cypress, as seen her:

https://stackoverflow.com/questions/61262881/cypress-never-get-past-loading-screen-on-ubuntu-19-10

### Desired behavior:

That it loads the test and allows running the tests

### Test code to reproduce

Seems to be any Cypress test, it's confirmed for multiple users and multiple projects, using a variety of frameworks

### Versions
Ubuntu 19.10
Kubuntu 19.10
Ubuntu 18.04

Cypress, 4.4.0, 4.3.0 and 4.1.?

Chrome 80.0.3987.163-1, 81.0.4044.92-1 and 81.0.4044.113-1
Chromium 77.0.3865.120-0ubuntu1~snap1 and 79.0.3945.79-0ubuntu0.19.10.2
Firefox 69.0.3+build1-0ubuntu1 and 75.0+build3-0ubuntu0.19.10.1

**Comment by hindsc52** [comment] 2020-04-17 11:00
Also seeing an issue when running on CI

`The Test Runner unexpectedly exited via a exit event with signal SIGTRAP`

Cypress Version 4.4.0

**Comment by hindsc52** [comment] 2020-04-17 11:02
Not yet sure if these two issues are related

**Comment by jennifer-shehane** [comment] 2020-04-17 11:26
Duplicate of #7020

**Closed by jennifer-shehane** 2020-04-17 11:26 UTC
