### ISSUE TITLE
Slow execution when repeating same step in scenario

### ISSUE THREAD

**Issue by Chili82** [cypress-io/cypress#27801] opened 2023-09-13 14:25 UTC
### Test code to reproduce

I'm using Cypress V12.16.0
numTestsKeptInMemory: 0,
experimentalMemoryManagement: true,
video: false.

When I run Scenario, first few step working ok. I have step for insert data on form and after that I have step for checking data on same form and this working ok. Step execution for insert data is extremly fast.

Then the same step is repeated to fill in the same form only with other data and the execution is much slower. It is the same step and the same implementation. Memory is not a problem and it does not go over 400MB because I perform the tests in the Chrome browser. Has anyone had a similar experience and in what direction should I research?
The form is a little longer and filling it out takes about 2 minutes. Does Cypress have a problem with some local cache if the execution of one step takes longer or something similar?

### Cypress Mode

both modes

### Cypress Version

12.16.0

### Browser Version

Chrome 116

### Node version

v18

### Operating System

windows and linux docker

**Comment by MikeMcC399** [comment] 2023-09-13 16:50
@Chili82 

If you are asking for feedback from the Cypress community of experienced users, then a better place for your question is on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button) 

The issue list here is for bugs, so you would need to provide a reproducible example with debug logs, if you think that you have hit a bug. Usually you would also be asked as well to make sure that your issue is reproducible on the latest version of Cypress (currently `13.2.0`).

**Comment by jennifer-shehane** [comment] 2023-12-17 19:22
Closing since no reproducible example was provided for us to investigate.

**Closed as not planned by jennifer-shehane** 2023-12-17 19:22 UTC
