### ISSUE TITLE
How to click and draw with openlayers. Possible or Not?

### ISSUE THREAD

**Issue by tascioglu** [cypress-io/cypress#1624] opened 2018-04-20 08:18 UTC
I asked this a lot of time on forms and chats.. But never get an answer back. So this time I'm writing it here as an issue.

I'm searching for weeks how to create some tests with openlayers. I can't find anything on the internet, but it should be possible right? So who can help me with this?

**Situation:**

There's created a map (sort of google maps) with angular / openlayers. What I need is to click on this map (coordinates) and draw on it (for example a polygon). 

For example go to the website https://openlayers.org/en/latest/examples/draw-features.html. Select here by Geometry type for point to click on the map or polygon to draw a polygon on the map. It has to be possible to get this in my test right?

**So the tests what I want to do is like:**

**Test 01:**
1. Go to https://openlayers.org/en/latest/examples/draw-features.html
2. Choose Geometry type "point"
3. Click on map

**Test 02:**
1. Go to https://openlayers.org/en/latest/examples/draw-features.html
2. Choose Geometry type "polygon"
3. Draw a polygon on the map

ps: I always updated my cypress version, so got the last one now. Trying to test this on a mac and windows.

**Comment by jennifer-shehane** [comment] 2018-04-20 18:15
Hey @tascioglu, could you provide some of the test code you already tried? 

Drawing on the canvas likely requires [triggering](https://on.cypress.io/trigger) the events that the map is specifically listening for, so may take some trial and error.

**Comment by tascioglu** [comment] 2018-04-25 13:25
hi @jennifer-shehane At this moment I don't have many code.. because after it didn't worked, I was frustated and deleted it.. :smiley: 

but it's nothing else then:
1. Go to the site : cy.visit('http://openlayers.org/en/latest/examples/draw-features.html');
2. Click on map: cy.get('ol-viewport').click();

I tried different things like trigger etc.. but nothing helped..

**Comment by Renaud009** [comment] 2018-05-10 13:59
What you also can do is intercept ol3 global object and your map instance to capture informations, calculate things like layers features or trigger some other events

```
cy.window().then((window) => {
      cy.simulateOpenLayersEvent (window.ol, window.map, 'pointerdown', 50, 50)
      cy.simulateOpenLayersEvent (window.ol, window.map, 'pointerup', 50, 50)
})
```

My command file:
```
Cypress.Commands.add('simulateOpenLayersEvent', (ol, map, type, x, y, opt_shiftKey = undefined) => {
    var viewport = map.getViewport();
    let position = viewport.getBoundingClientRect();
    cy.log(`left: ${position.left}, top: ${position.top}, width: ${position.width}, height: ${position.height}`)
    cy.get('canvas').trigger(type, {
        clientX: position.left + x + (position.width / 2),
        clientY: position.top + y + (position.height / 2),
    })
})
```

Example code that makes me able to count how many polygons (selected regions) are loaded in a layer (won't work on draw-feature.htm tho...l)
```
cy.window().then((window) => {
      cy.hasOpenLayersSelectedRegion(window.ol, window.cyCurrentMap, 1) // 1 selected region attended
})

Cypress.Commands.add('hasOpenLayersSelectedRegion', (ol, map, count) => {
    console.log("Current ol3 global object: %o", ol)
    console.log("Current OLComponent.map instance: %o", map)
  
    let layers = map.getLayers().getArray()
    cy.wrap(layers).each ((layer)=> {
        if (layer instanceof ol.layer.Vector && layer.get('nameId') && layer.get('nameId') === LAYER_SELECTED_REGIONS_NAME) {
          cy.log('Found Vector Layer LAYER_SELECTED_REGIONS')
          cy.wrap(layer.getSource().getFeatures().length).should('eq', count)
        } 
    });
  })
```

**Comment by domlyons** [comment] 2019-03-21 17:06
Just to add to this. If you want to simulate a drag event in openlayers using cypress we found that you need to specify `isPrimary` in the `pointerdown` trigger i.e     
```js
cy.get('canvas.ol-unselectable')
      .trigger('pointerdown', {
        x: 450, 
        y: 300,
        isPrimary: true,
      })
      .trigger('pointermove', { x: 380, y: 240 })
      .trigger('pointerup', { x: 380, y: 240 });
```

**Comment by jennifer-shehane** [comment] 2019-04-02 07:07
Closing this issue as resolved as others have noted they have been able to draw on openlayers.

**Closed by jennifer-shehane** 2019-04-02 07:07 UTC
Labels: stage: awaiting response, type: question

**Comment by nikonov91-dev** [comment] 2020-02-07 13:18
> Just to add to this. If you want to simulate a drag event in openlayers using cypress we found that you need to specify `isPrimary` in the `pointerdown` trigger i.e
> 
> ```js
> cy.get('canvas.ol-unselectable')
>       .trigger('pointerdown', {
>         x: 450, 
>         y: 300,
>         isPrimary: true,
>       })
>       .trigger('pointermove', { x: 380, y: 240 })
>       .trigger('pointerup', { x: 380, y: 240 });
> ```

weird but that didnt work for me, but i tried cy.get('canvas.ol-unselectable').click(100, 100) and it made a point on canvas

**Comment by bryanSME** [comment] 2020-02-07 15:04
> What you also can do is intercept ol3 global object and your map instance to capture informations, calculate things like layers features or trigger some other events
> 
> ```js
> cy.window().then((window) => {
>       cy.simulateOpenLayersEvent (window.ol, window.map, 'pointerdown', 50, 50)
>       cy.simulateOpenLayersEvent (window.ol, window.map, 'pointerup', 50, 50)
> })
> ```
> 
> My command file:
> 
> ```js
> Cypress.Commands.add('simulateOpenLayersEvent', (ol, map, type, x, y, opt_shiftKey = undefined) => {
>     var viewport = map.getViewport();
>     let position = viewport.getBoundingClientRect();
>     cy.log(`left: ${position.left}, top: ${position.top}, width: ${position.width}, height: ${position.height}`)
>     cy.get('canvas').trigger(type, {
>         clientX: position.left + x + (position.width / 2),
>         clientY: position.top + y + (position.height / 2),
>     })
> })
> ```
> 
> Example code that makes me able to count how many polygons (selected regions) are loaded in a layer (won't work on draw-feature.htm tho...l)
> 
> ```js
> cy.window().then((window) => {
>       cy.hasOpenLayersSelectedRegion(window.ol, window.cyCurrentMap, 1) // 1 selected region attended
> })
> 
> Cypress.Commands.add('hasOpenLayersSelectedRegion', (ol, map, count) => {
>     console.log("Current ol3 global object: %o", ol)
>     console.log("Current OLComponent.map instance: %o", map)
>   
>     let layers = map.getLayers().getArray()
>     cy.wrap(layers).each ((layer)=> {
>         if (layer instanceof ol.layer.Vector && layer.get('nameId') && layer.get('nameId') === LAYER_SELECTED_REGIONS_NAME) {
>           cy.log('Found Vector Layer LAYER_SELECTED_REGIONS')
>           cy.wrap(layer.getSource().getFeatures().length).should('eq', count)
>         } 
>     });
>   })
> ```

`window.ol` and `window.map` do not exist.  I'm on OL version 5.x.  

As for the other method, listed above, I have not been able to get any of them to work.

**Comment by mustafahamid** [comment] 2021-02-05 09:52
the problem is always exist, i can not understand why cypress team not able to solve this type of problems.

**Comment by mustafahamid** [comment] 2021-02-05 16:35
closed but not solved.

**Comment by mhjadav** [comment] 2021-05-13 06:13
Trigger mouse event using trigger method, event name is same as jQuery mouse event name, i am using these events to draw, i hope this will help

`cy.get('.main-canvas').trigger('mousedown', 500, 100, { force: true }).trigger('mousemove', 500, 200, { force: true }).trigger('mouseup', { force: true });`

**Comment by nboisteault** [comment] 2021-07-28 09:33
> Trigger mouse event using trigger method, event name is same as jQuery mouse event name, i am using these events to draw, i hope this will help
> 
> `cy.get('.main-canvas').trigger('mousedown', 500, 100, { force: true }).trigger('mousemove', 500, 200, { force: true }).trigger('mouseup', { force: true });`

This worked with which OpenLayers version?

**Comment by jaure96** [comment] 2023-01-11 10:24
Hi all.
Did someone manage to pan the map using cypress??
I'm trying with this code... but nothing. I'm usin OpenLayers 6.10.0

```
cy.fixture('maritimeObjects').then((maritimeObjects) => {
    cy.wait(1000)

    cy.get(maritimeObjects.mapCanvas)
      .trigger('pointerdown', {
        x: 50,
        y: 370,
        pointerType: 'touch',
        pointerId: 1,
      })
      .trigger('pointermove', {
        x: 300,
        y: 200,
        pointerType: 'touch',
        pointerId: 1,
      })
      .trigger('pointerup', {
        x: 300,
        y: 200,
        pointerType: 'touch',
        pointerId: 1,
      })
  }) 
```
The fixture mapCanvas is this selector:
`"mapCanvas": "div.ol-map-container div.ol-viewport div.ol-unselectable.ol-layers div.ol-layer canvas"`
