### ISSUE TITLE
Failed to deserialize the V8 snapshot blob error during 'run' and 'open in Windows - 3.5.0

### ISSUE THREAD

**Issue by dugajean** [cypress-io/cypress#5440] opened 2019-10-24 12:37 UTC
### Current behavior:
`cypress run` and `cypress open`, yield the following error after upgrading to 3.5.0:

```
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------
cypress open
It looks like this is your first time using Cypress: 3.5.0

#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the 
snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 0000003A7AAFEB88

----------

Platform: win32 (10.0.19002)
Cypress Version: 3.5.0
error Command failed with exit code 1.
```

![image](https://user-images.githubusercontent.com/2448254/67486030-7cf6e680-f66b-11e9-83e5-26ea635b8305.png)

### Desired behavior:
Regain the ability to run tests and open the Cypress window.

### Steps to reproduce: (app code and test code)
Run `cypress run` or `cypress open` on Windows 10 after upgrading to 3.5.0 via `yarn upgrade cypress`.

### Versions

- Cypress 3.5.0
- Node 12.13.0
- Windows 10 Version 1903, Build 19002.1002

**Comment by jennifer-shehane** [comment] 2019-10-24 12:56
Hey @dugajean, thanks for opening this issue. This is likely isolated to something about your environment specifically. 

In order to address you issue as quickly as possible, could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here? Thanks!

**Comment by dugajean** [comment] 2019-10-24 13:02
@jennifer-shehane I'm running this on my local machine. I'll run Cypress in debug mode and provide the output here.

**Comment by dugajean** [comment] 2019-10-24 13:10
@jennifer-shehane 

```
yarn cypress
yarn run v1.19.1
$ cross-env DEBUG=cypress:* cypress open
  cypress:cli cli starts with arguments ["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\lol\\Code\\myproject\\myproject-frontend\\node_modules\\cypress\\bin\\cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms  
  cypress:cli program parsing arguments +2ms
  cypress:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +174ms
  cypress:cli opening from options {"project":"C:\\Users\\lol\\Code\\myproject\\myproject-frontend"} +0ms
  cypress:cli command line arguments ["--project","C:\\Users\\lol\\Code\\myproject\\myproject-frontend"] +1ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +2ms
  cypress:cli checking if executable exists C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe +4ms
  cypress:cli Binary is executable? : true +25ms
  cypress:cli binaryDir is  C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress +1ms
  cypress:cli Reading binary package.json from: C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\package.json +0ms   
  cypress:cli Found binary version 3.5.0 installed in: C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress +6ms
  cypress:cli could not read binary_state.json file +8ms
  cypress:cli {} +21ms
  cypress:cli is Verified ? undefined +25ms
  cypress:cli running binary verification check 3.5.0 +1ms
It looks like this is your first time using Cypress: 3.5.0

  cypress:cli clearing out the verified version +8ms
  cypress:cli needs Xvfb? false +3ms
  cypress:cli spawning, should retry on display problem? false +20ms 
  cypress:cli running smoke test +1ms
  cypress:cli using Cypress executable C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe +1ms
  cypress:cli smoke test command: C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe --smoke-test --ping=465 +2ms        
  cypress:cli smoke test timeout 30000 ms +1ms
 \  Verifying Cypress can run C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress
  cypress:cli Smoke test failed: Error: Command failed: C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe --smoke-test --ping=465


#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the 
snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 0000006AF4EFED78


    at makeError (C:\Users\lol\Code\myproject\myproject-frontend\node_modules\cypress\node_modules\execa\index.js:172:9)
    at C:\Users\lol\Code\myproject\myproject-frontend\node_modules\cypress\node_modules\execa\index.js:277:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 3,
  stdout: '\r\n',
  stderr: '\r\n' +
    '\r\n' +
    '#\r\n' +
    '# Fatal error in , line 0\r\n' +
    '# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.\r\n' +
    '#\r\n' +
    '#\r\n' +
    '#\r\n' +
    '#FailureMessage Object: 0000006AF4EFED78',
  failed: true,
  signal: null,
  cmd: 'C:\\Users\\lol\\AppData\\Local\\Cypress\\Cache\\3.5.0\\Cypress\\Cypress.exe --smoke-test --ping=465',
  timedOut: false,
  killed: false
} +82ms
  cypress:cli error message: 

#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the 
snapshot blob file is corrupted or missing.
#
#
#
 ×  Verifying Cypress can run C:\Users\lol\AppData\Local\Cypress\Cache\3.5.0\Cypress
   → Cypress Version: 3.5.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.


Platform: win32 (10.0.19002)
Cypress Version: 3.5.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by karlcp** [comment] 2019-10-24 14:30
similar problem, after updating too.   similar error messages in debugmode
installed via npm rather than yarn.


C:\Users\KarlGladwin>npx cypress run
  cypress:cli cli starts with arguments ["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\KarlGladwin\\node_modules\\cypress\\bin\\cypress","run"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +4ms
  cypress:cli running Cypress +1ms
  cypress:cli parsed cli options {} +97ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe +4ms
  cypress:cli Binary is executable? : true +2ms
  cypress:cli binaryDir is  C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress +0ms
  cypress:cli Reading binary package.json from: C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 3.5.0 installed in: C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress +4ms
  cypress:cli could not read binary_state.json file +4ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli running binary verification check 3.5.0 +0ms
It looks like this is your first time using Cypress: 3.5.0

  cypress:cli clearing out the verified version +4ms
  cypress:cli needs Xvfb? false +2ms
  cypress:cli spawning, should retry on display problem? false +1ms
  cypress:cli running smoke test +5ms
  cypress:cli using Cypress executable C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe +0ms
  cypress:cli smoke test command: C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe --smoke-test --ping=557 +1ms
  cypress:cli smoke test timeout 30000 ms +1ms
  cypress:cli Smoke test failed: { Error: Command failed: C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress\Cypress.exe --smoke-test --ping=557


#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 00000019900FED68


    at makeError (C:\Users\KarlGladwin\node_modules\execa\index.js:172:9)
    at Promise.all.then.arr (C:\Users\KarlGladwin\node_modules\execa\index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 3,
  stdout: '\r\n',
  stderr:
   '\r\n\r\n#\r\n# Fatal error in , line 0\r\n# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.\r\n#\r\n#\r\n#\r\n#FailureMessage Object: 00000019900FED68',
  failed: true,
  signal: null,
  cmd:
   'C:\\Users\\KarlGladwin\\AppData\\Local\\Cypress\\Cache\\3.5.0\\Cypress\\Cypress.exe --smoke-test --ping=557',
  timedOut: false,
  killed: false } +60ms
  cypress:cli error message:

#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 00000019900FED68 +5ms
 ×  Verifying Cypress can run C:\Users\KarlGladwin\AppData\Local\Cypress\Cache\3.5.0\Cypress
   → Cypress Version: 3.5.0

**Comment by AsthirWP** [comment] 2019-10-25 08:14
I also got the "Failed to deserialize the V8 snapshot blob". Renaming the Cyrpress cache folder and reinstalling with npx cypress install resolved the problem though. Previously I upgrade the Vue CLI and had multiple errors here and interrupts. In my case, I think Cypress simply wasn't install correctly. Just for information for your troubleshooting.

**Comment by dugajean** [comment] 2019-10-25 13:48
@AsthirWP where's that cache folder located?

**Comment by AsthirWP** [comment] 2019-10-25 14:28
On Windows, its in <user>\AppData\Local\Cypress\Cache\<version>

**Comment by rdmorel** [comment] 2019-10-25 16:42
> I also got the "Failed to deserialize the V8 snapshot blob". Renaming the Cyrpress cache folder and reinstalling with npx cypress install resolved the problem though. Previously I upgrade the Vue CLI and had multiple errors here and interrupts. In my case, I think Cypress simply wasn't install correctly. Just for information for your troubleshooting.

This fix worked for me!

**Comment by dugajean** [comment] 2019-10-26 11:39
This fix worked for me too!

**Comment by karlcp** [comment] 2019-10-28 14:54
yup,  clearing the cache (renaming the above cache folder) and reinstalling cypress fixed this issue.

**Comment by AndreasHaaversen** [comment] 2019-10-29 19:06
Worked for me too! Didn't have to clear the cache though, only force reinstall.

**Comment by kristianfjelde** [comment] 2019-10-30 11:12
`npx cypress install --force`

Fixed it completely.

**Comment by danilocasassa** [comment] 2019-11-05 14:10
> `npx cypress install --force`
> 
> Fixed it completely.

I did this too. Fixed for me.

**Comment by basvanlaarhoven** [comment] 2019-11-06 14:16
npx cypress install --force also fixed it for me!
Thanks kristianfjelde

**Comment by JGurganus12** [comment] 2019-11-07 17:05
I just had this happen to me because I accidentally closed out before installation had completed.

**Comment by TuomasKoivisto** [comment] 2019-11-13 08:13
with yarn:

1. remove cypress from node_modules
2. yarn install --check-files

**Comment by AaronRohrbacher** [comment] 2019-11-14 23:12
Joining the `npx cypress install --force` bandwagon, problem solved for me.

**Comment by jennifer-shehane** [comment] 2019-12-10 07:41
We'll be closing this issue as resolved. Please follow the workaround above for clearing cache during install if you see this error.

**Closed by jennifer-shehane** 2019-12-10 07:41 UTC
Labels: OS: windows

**Comment by adielsh** [comment] 2020-01-06 11:00
> che f

Worked for me! Thanks!

**Comment by adielsh** [comment] 2020-01-06 11:01
> I also got the "Failed to deserialize the V8 snapshot blob". Renaming the Cyrpress cache folder and reinstalling with npx cypress install resolved the problem though. Previously I upgrade the Vue CLI and had multiple errors here and interrupts. In my case, I think Cypress simply wasn't install correctly. Just for information for your troubleshooting.

Worked for me! Thanks!

**Comment by wolffc** [comment] 2020-01-16 16:06
for me ` yarn run cypress install --force` has worked well. to force the installation.

**Comment by orochizu** [comment] 2020-04-15 15:50
Joining `npx cypress install --force` gang! Fixed it.

**Comment by y0n1** [comment] 2020-05-05 11:39
`cypress cache clear && cypress install` fixed this issue in my case while upgrading from v4.1.0  to v4.5.0

**Comment by gianlucabaldin** [comment] 2020-05-07 07:25
> 
> 
> `npx cypress install --force`
> 
> Fixed it completely.

it works for me too! 
@kristianfjelde you saved my day (and my sanity), thanks a lot!

**Comment by kees0** [comment] 2020-06-09 05:22
For some reason I seem to be needing to do this a lot lately: npx cypress install --force Not sure why.

**Comment by lukeapage** [comment] 2020-10-01 18:04
At our company it seems to happen to one or two / 100 employees every time we upgrade.

**Comment by trevithj** [comment] 2020-10-06 20:36
Also happened to me today on a new install.
FYI: on local machine, Windows 10, Cypress 4.4.0, using yarn. The above fix worked: `yarn run cypress install --force `

**Comment by SourceCode** [comment] 2020-10-28 05:06
npx force works but this must be the longest route possible to reinstall cypress.

**Comment by DanielRamos84** [comment] 2021-03-16 02:10
Tried `npx cypress install --force` this was taking forever, not sure if it was doing anything.  As others have pointed out the fix for me was navigating C:\Users\*****\AppData\Local\Cypress renaming the Cache folder followed by running `npx cypress install`.

**Comment by markhughes** [comment] 2021-03-30 05:05
> Also happened to me today on a new install.
> FYI: on local machine, Windows 10, Cypress 4.4.0, using yarn. The above fix worked: `yarn run cypress install --force `

Fixed it! Wasted an hour!

**Comment by kayraberktuncer** [comment] 2021-04-14 20:45
> Also happened to me today on a new install.
> FYI: on local machine, Windows 10, Cypress 4.4.0, using yarn. The above fix worked: `yarn run cypress install --force `

Fixed it! thank you.

**Comment by ethdmill** [comment] 2021-04-19 21:37
> npx cypress install --force

Worked for me too! Thank you so much!

**Comment by leopucci** [comment] 2021-07-02 13:13
`Done in 132.95s.`
The problem is the slowliness while installing. 
Hitting CTRL+C is what caused the problem in the first place. 
NPM is not so verbose, yarn did it better.

**Comment by barbalex** [comment] 2021-07-21 13:29
Happened to me when updating from 7.3.0 to 8.0.0.

Deleting the cache took a loooooooong time as it contained > 20GB and > 1.5 million files! (and windows recycled it all 🙄).

But then after additionally running `yarn run cypress install --force` it worked 😄

**Comment by lorainegarutti** [comment] 2021-08-14 14:21
Also happened to me installing 8.2.0 and only solved with `yarn run cypress install --force` 
Tks @trevithj
