### ISSUE TITLE
Cypress click is not closing menu when it clicks on a button from menu.

### ISSUE THREAD

**Issue by M-H-Riad** [cypress-io/cypress#9055] opened 2020-11-02 05:43 UTC
Here I am testing a Vue application using cypress. I have a menu on my app screen. Normally when I click a button on the menu it closes the menu and performs the functionality. But when I do it using cypress, it performs the functionality but it can't close the menu. 

**Note:**  I am using  **"cypress": "^4.10.0",**
1.  I have also tried  .click({force:true} );
2. and  [#3135](https://github.com/cypress-io/cypress/issues/3135) this issue, but still it is not working for me.
![Menu snip](https://user-images.githubusercontent.com/43503357/97834175-5a2cf280-1d01-11eb-9908-edb9a74c11f6.PNG)

Here is my test code.
```js
    it('Open menu, Click on sort button(A -> Z): Check ascending order of data', function () {
      cy.server();
      cy.route("GET", getTableListAPI).as('getTableList');
      cy.route("GET", getFirstPageTableData).as("getTableDetails");
      //Asc sort Api
      cy.route("GET", ascendingSortApi).as("getAscData");
      cy.visit(testTargetURL);
      //Wait to load data
      cy.wait('@getTableList');
      //Select the target tablefrom the left pane
      cy.get(selectors.navigationDrawer).find('a').contains(testTableWithData).click();
      //Wait to load data
     cy.wait('@getTableDetails');
    //Open menu
    cy.get('th').eq(1).find('button').click();
    //Click on first button.
    cy.get(selectors.filterMenu).within(($menu) => {
        cy.get('.v-item-group').find('button').eq(0).click();
    })
    //Wait to load data
    cy.wait('@getAscData');

    //Check visibility
    cy.get(selectors.filterMenu).should('not.be.visible');
    //Check ascending order data
    cy.get('table').within(($table) => {
        cy.get('tr').find('td').should('contain','');
        cy.get('tr').find('td').should('contain','-9223372036854776000');
    })
 })
```

**My production code is:**

```html
<v-btn-toggle>
                    <v-btn 
                      class="ml-2"
                      small
                      color="success"
                      @click="sortColumnData(head.value,false)"
                    >
                      A</br>Z
                      <v-icon>mdi-arrow-up</v-icon>
                    </v-btn>
                    <v-btn 
                      small 
                      color="success" 
                      @click="sortColumnData(head.value,true)"
                    >
                      Z</br>A
                      <v-icon>mdi-arrow-down</v-icon>
                    </v-btn>
                </v-btn-toggle>
```
**And** 

```js
sortColumnData(sortBy, sortDesc) {
      //Colse the filtering menu
      this.CloseMenu = true;
      //Set api parameter for sorting
      this.$set(this.options, 'sortBy', [sortBy]);
      this.$set(this.options, 'sortDesc', [sortDesc]);
      this.getTableData();
    },
```

**Comment by jennifer-shehane** [comment] 2020-11-02 09:03
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

There are several selectors with no definition in the test files, so that these tests cannot be run to see the failing situation. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-11-02 09:03 UTC

**Comment by M-H-Riad** [comment] 2020-11-02 09:58
Sorry for being unclear. Now I am sharing the full test specification with selectors and const.
**If still, it is not enough, please let me know.**

```
const testTargetURL = '/tabledata';
const getTableListAPI = '/api/v1/tables';
const getFirstPageTableData = '/api/v1/table-data/1?page=1&itemsPerPage=100&sortBy[]=created_at&sortDesc[]=true';
const ascendingSortApi = '/api/v1/table-data/1?page=1&itemsPerPage=100&sortBy[]=test_column_bigint&sortDesc[]=false';

const testTableWithData = ' テスト用_全カラムタイプ(E2Eテスト用)';

const selectors = {
    drawerButton: '#drawerButton',
    navigationDrawer: '#navidationDrawer',
    filterMenu: '.v-menu__content',
}


 describe('Check functionality of sort button', function () {
    it('Open menu, Click on sort button(A -> Z): Check ascending order of data', function () {
        cy.server();
        cy.route("get", getTableListAPI).as('getTableList');
        cy.route("GET", getFirstPageTableData).as("getTableDetails");
        //Asc sort Api
        cy.route("GET", ascendingSortApi).as("getAscData");
        cy.visit(testTargetURL);
        //Wait to load data
        cy.wait('@getTableList');
        //Select the target tablefrom the left pane
        cy.get(selectors.navigationDrawer).find('a').contains(testTableWithData).click();
        //Wait to load data
        cy.wait('@getTableDetails');

        //Open menu
        cy.get('th').eq(1).find('button').click();
        //Click on first button.
        cy.get(selectors.filterMenu).within(($menu) => {
            cy.get('.v-item-group').find('button').eq(0).click();
        })
        
        //Wait to load data
        cy.wait('@getAscData');

        //Check visibility
        cy.get(selectors.filterMenu).should('not.be.visible');
        //Check ascending order data
        cy.get('table').within(($table) => {
            cy.get('tr').find('td').should('contain','');
            cy.get('tr').find('td').should('contain','-9223372036854776000');
        })
     })

    });
```

Here is my production code:
```
<template
        v-for="head in headers"
        v-slot:[`header.${head.value}`]="{ header }"
      >
        <span :key="head.text">{{ header.text }}</span>

        <v-menu :close-on-content-click="CloseMenu">
          <template v-slot:activator="{ attrs, on }">
            <v-icon
              v-on="on"
              v-bind="attrs"
              :disabled="loadingStatus"
              :color="filterIcon.color"
              small
              right
              class="ml-12"
            >
              {{filterIcon.icon}}
            </v-icon>
          </template>

          <v-list>
            <v-row>
              <v-col>
                <v-btn-toggle>
                    <v-btn 
                      class="ml-2"
                      small
                      color="success"
                      @click="sortColumnData(head.value,false)"
                    >
                      A</br>Z
                      <v-icon>mdi-arrow-up</v-icon>
                    </v-btn>
                    <v-btn 
                      small 
                      color="success" 
                      @click="sortColumnData(head.value,true)"
                    >
                      Z</br>A
                      <v-icon>mdi-arrow-down</v-icon>
                    </v-btn>
                </v-btn-toggle>
              </v-col>
            </v-row>

            <v-card-actions>
              <v-spacer></v-spacer>
              <v-btn color="success darken-1" text >OK</v-btn>
              <v-btn color="success darken-1" text @click="close">Cancel</v-btn>
            </v-card-actions>
          </v-list>
        </v-menu>
      </template>


export default {
  data: () => ({
CloseMenu: false,
}),

methods: {

sortColumnData(sortBy, sortDesc) {
      //Colse the filtering menu
      this.CloseMenu = true;
      //Set api parameter for sorting
      this.$set(this.options, 'sortBy', [sortBy]);
      this.$set(this.options, 'sortDesc', [sortDesc]);
      this.getTableData();
    },
}
```

**Comment by jennifer-shehane** [comment] 2020-11-02 10:04
The test code provided cannot be run as given, since there's no URL given and many of the routes do not exist. Trying to remove those and visit the given HTML at `index.html` still results in a failed test.

<img width="551" alt="Screen Shot 2020-11-02 at 4 32 33 PM" src="https://user-images.githubusercontent.com/1271364/97855481-31b8ee80-1d29-11eb-8d47-96089ff09cc6.png">

<img width="987" alt="Screen Shot 2020-11-02 at 4 33 54 PM" src="https://user-images.githubusercontent.com/1271364/97855502-38dffc80-1d29-11eb-88db-b115ad6105ad.png">

**Comment by M-H-Riad** [comment] 2020-11-02 10:18
I don't know how should I share the full environment including the database with you. Those URLs and API data are for my local environment. So how should it come to your end? My production code is in  **someComponent.vue** file, I am not sure the behavior of " .html " and  ".vue" file are the same or not.

**Comment by jennifer-shehane** [comment] 2020-11-02 10:50
Generally creating an `index.html` outside of your environment that recreates the issue is best. We just need some way to see the problem in order to fix it and right now I can't run any of the tests provided.

**Comment by M-H-Riad** [comment] 2020-11-11 06:08
@jennifer-shehane 
Yes, I understand your point. I have made a simple environment in an index.html file and test case for that. This HTML and test are the same as my application environment. Can you please consider reopen this issue or suggest something better for me?
Thanks.

Here is the index.html file.
```

<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  <div id="app">
    <v-app>
      <v-main>
        <v-container>Hello world</v-container>
        <v-menu
        buttom
        :close-on-content-click="closeOnContentClick"
      >
        <template v-slot:activator="{ on, attrs }">
          <v-btn
            color="primary"
            dark
            v-bind="attrs"
            v-on="on"
            right
            class="ml-15"
          >
            Dropdown
          </v-btn>
        </template>
  
        <v-list>
          <v-row>
              <v-col>
                <v-btn-toggle>
                    <v-btn 
                      class="ml-2"
                      small
                      color="success"
                      @click="closeMenu()"
                    >
                      A</br>Z
                      <v-icon>mdi-arrow-up</v-icon>
                    </v-btn>
                    <v-btn 
                      small 
                      color="success" 
                    >
                      Z</br>A
                      <v-icon>mdi-arrow-down</v-icon>
                    </v-btn>
                </v-btn-toggle>
              </v-col>
            </v-row>
            <v-card-actions>
              <v-spacer></v-spacer>
              <v-btn color="success darken-1" text >OK</v-btn>
              <v-btn color="success darken-1" text >Cancel</v-btn>
            </v-card-actions>
        </v-list>
      </v-menu>
      </v-main>
    </v-app>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
  <script>
    new Vue({
      el: '#app',
      vuetify: new Vuetify(),
      data: () => ({
        items: [
          { title: 'Click Me' },
          { title: 'Click Me' },
          { title: 'Click Me' },
          { title: 'Click Me 2' },
        ],
        closeOnContentClick: false,
      }),
      methods:{
        closeMenu() {
          this.closeOnContentClick = true;
        },
      }
    })
  </script>
</body>

</html>

```
And here is the test case:
// .click({ force: true }) also doesn't work for me.
```
describe('Check functionality of sort button', function () {
    it('Open menu, Click on sort button(A -> Z): Check menu is closed', function () {
        cy.visit('./pages/index.html');
        //Open menu
        cy.get('.v-main__wrap').find('button').click();
        //Click first button
        cy.get('.v-menu__content').find('.v-item-group').find('button').eq(0).click();
        //Check visibility
        cy.get('.v-menu__content').should('not.be.visible');
     })
 });
```
