### ISSUE TITLE
 V8 process OOM

### ISSUE THREAD

**Issue by cw0423** [cypress-io/cypress#24049] opened 2022-09-30 06:20 UTC
### Current behavior

Browser crashes after 10 tests after upgrading to 10.8.0
chrome version 106

### Desired behavior

should not report an error

### Test code to reproduce

Browser crashes after 10 tests after upgrading to 10.8.0

### Cypress Version

10.8.0

### Node version

v14

### Operating System

macOS12

**Comment by cw0423** [comment] 2022-09-30 06:21
![image](https://user-images.githubusercontent.com/3793852/193203736-1e5eb0f1-44cd-407b-a966-43082d21e849.png)

**Comment by cw0423** [comment] 2022-09-30 07:11
after testing
There are problems with chrome V106, V104, V101 versions
With more and more tests, after the chrome memory exceeds 3G, there is a high probability of crashing

**Comment by cw0423** [comment] 2022-09-30 07:12
be OOM by cypress 10+

**Comment by nagash77** [comment] 2022-10-03 13:40
@tcw010 Can you please include the tests you are running or a link to a repo that reproduces the issue?  We have heard of reports of Chromium browsers having memory issues (as seen [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1352649)).  As a temporary workaround I would suggest downgrading your chrome to a version <v100 which seems to be when these issues arose in Chromium.

**Comment by nagash77** [comment] 2022-10-11 13:42
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by rajat007kamra** [comment] 2023-07-14 10:43
@nagash77 :  I am still seeing this same issue with Chrome - Version 114.0.5735.198

<img width="1338" alt="image" src="https://github.com/cypress-io/cypress/assets/32223546/cc0631bc-8938-47d3-a05a-9b592947d9b8">


You can refer my repo :: https://github.com/rajat007kamra/CypressAssignment

**Comment by cacieprins** [comment] 2023-07-14 18:51
Hi @rajat007kamra , thank you for the reproduction repository. Have you tried enabling [experimental memory management](https://docs.cypress.io/guides/references/experiments#Configuration)? In order to fully reproduce and triage, can you let me know how much memory the machine these tests are running on has available?

Thanks!

**Comment by rajat007kamra** [comment] 2023-07-15 01:07
@cacieprins :  Below is my PC configurations ::
<img width="570" alt="image" src="https://github.com/cypress-io/cypress/assets/32223546/b34e68ff-fbf5-483d-8366-d4a719154a7a">

I have around 400 GB of space available.

**Comment by cacieprins** [comment] 2023-07-17 17:14
Thank you, @rajat007kamra ! Unfortunately, I'm unable to reproduce with your example repository - could you try enabling experimental memory management to see if that resolves your issue? Thanks!

**Comment by rajat007kamra** [comment] 2023-07-18 04:12
@cacieprins :   By enabling experimentalMemoryManagement:true , I am not able to reproduce this issue.
Thanks- @cacieprins

**Comment by cacieprins** [comment] 2023-07-18 20:11
Glad to hear it - I'll go ahead and close this issue.

**Closed as completed by cacieprins** 2023-07-18 20:11 UTC
Labels: existing workaround
