### ISSUE TITLE
cy.log in Cypress.on(..) swallows the subject

### ISSUE THREAD

**Issue by psech** [cypress-io/cypress#14270] opened 2020-12-22 04:14 UTC
It looks very similar to https://github.com/cypress-io/cypress/issues/8084

### Current behaviour

/support/index.js
```js
Cypress.on('uncaught:exception', (err, runnable) => {
  cy.log('Uncaught Exception', err);
  return false;
});
```

Spec
```js
cy.get(selectors.archive.archiveNameInput)
  .clear()
  .type(archiveName);
```

Somewhere around `clear()` we face an `uncaught:exception`
> Args:     TypeError: The following error originated from your application code, not from Cypress.
>  \> Cannot set property 'status' of undefined

In Cypress, we experience the following
```
cy.type() failed because it requires a DOM element.

The subject received was:

  > null

The previous command that ran was:

  > cy.log()
```

<img width="746" alt="cypress" src="https://user-images.githubusercontent.com/4928981/102847914-a0801180-4467-11eb-97f6-c20555851f69.png">

When I comment out the `cy.log('Uncaught Exception', err);` it works fine.

### Desired behaviour
The `cy.log` should not swallow the subject.

### Versions

Cypress: 6.20
Chrome: 87
macOS Big Sur: 11.1

**Comment by jennifer-shehane** [comment] 2020-12-22 07:27
Duplicate of https://github.com/cypress-io/cypress/issues/6316

Calling Cypress commands does not work outside of the context of a test - so does not work when called within a Cypress event listener.

**Closed by jennifer-shehane** 2020-12-22 07:27 UTC
