### ISSUE TITLE
Change how we show options in the Command Log

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1045] opened 2017-12-08 18:52 UTC
## Current behavior

When use pass options to `cy.visit()` or `cy.trigger()` we get weird `Object{N}` serialization in the Command Log. For example

```js
cy.get().trigger('keydown', { which: 'Arrows.down' })
```
shows up like this

<img width="1276" alt="screen shot 2017-12-08 at 12 17 01 pm" src="https://user-images.githubusercontent.com/2212006/33780444-c90ca33e-dc1e-11e7-827f-e8055a40e4cd.png">

## Desired behavior

We should be smarter about options object and

- print only non-default options
- serialize the object to print `TRIGGER keydown, {which: 40}` for example in this case

**Comment by jennifer-shehane** [comment] 2019-07-12 04:14
This is a duplicate of a previous issue you opened 🤣 https://github.com/cypress-io/cypress/issues/678 Closing as duplicate.

**Closed by jennifer-shehane** 2019-07-12 04:14 UTC
Labels: pkg/reporter, stage: ready for work, type: enhancement, type: user experience
