### ISSUE TITLE
Cannot find element in JSON body

### ISSUE THREAD

**Issue by FransPeterson** [cypress-io/cypress#6626] opened 2020-03-03 16:15 UTC
I noticed that a certain assertion was failing when upgrading from version 3.8.3 towards 4.1.0. I downgraded the version back towards 3.8.3 and it's passing again.

### Current behavior:

![image](https://user-images.githubusercontent.com/58031612/75795066-0af98100-5d72-11ea-9e26-f8fa669b62e3.png)

### Desired behavior:

Assertion should pass. 

### Test code to reproduce

```js
describe('API Testing with Cypress', () => {

  var baseURL = "https://pokeapi.co/api/v2/pokemon"

  beforeEach(() => {
      cy.request(baseURL+"/25").as('pikachu');
  });

  it('Print response body',() => {
    cy.get('@pikachu')
    .its('body')
    .then((apivalue) => {
          cy.log(apivalue)
        })
  });

  it('Validate the header', () => {
      cy.get('@pikachu')
          .its('headers')
          .its('content-type')
          .should('include', 'application/json; charset=utf-8');
  });

  it('Validate the status code', () => {
      cy.get('@pikachu')
          .its('status')
          .should('equal', 200);
  });

  it("Validate the pokemon's name", () => {
    cy.get("@pikachu") 
      .its('body')
      .its('forms')
      .should('include', { 
        name: 'pikachu', 
        url: 'https://pokeapi.co/api/v2/pokemon-form/25/' 
      })
      .should('not.include', {
        name: 'johndoe'
      });
  })
```
### Versions

Working in 3.8.3
Not working in 4.1.0

**Comment by jennifer-shehane** [comment] 2020-03-04 09:01
I can confirm this change in behavior starting in 4.0.0.

This expected behavior and is due to our upgrade of Chai from 3.5.0 to 4.2.0 which included breaking changes. Specifically:

>Previously, `.include` was using strict equality (`===`) for non-negated property inclusion, but deep equality for negated property inclusion and array inclusion.

This upgrade causes `include` to always use strict equality unless the `deep` property is set.

There's a bit of a deeper explanation [here](https://github.com/chaijs/chai/issues/743#issuecomment-229755825
), but essentially in 3.x, a different equality check was being applied for `not.include` versus `include`, which is now fixed 

## 3.8.3

<img width="496" alt="Screen Shot 2020-03-04 at 3 09 37 PM" src="https://user-images.githubusercontent.com/1271364/75860427-3475e380-5e2a-11ea-80bc-2576e4712cf9.png">

## 4.0.0

<img width="495" alt="Screen Shot 2020-03-04 at 3 21 34 PM" src="https://user-images.githubusercontent.com/1271364/75861505-e530b280-5e2b-11ea-8d7e-152e97a798dc.png">

## To fix:

Update your assertion to use `deep.include` for deep equality and `include` for strict equality. The below code passes in 4.0.0, for example.

```js
it("Validate the pokemon's name", () => {
  cy.request('https://pokeapi.co/api/v2/pokemon/25').as('pikachu');
  cy.get("@pikachu")
    .its('body')
    .its('forms')
    .should('deep.include', {
      name: 'pikachu',
      url: 'https://pokeapi.co/api/v2/pokemon-form/25/'
    })
})
```

**Closed by jennifer-shehane** 2020-03-04 09:01 UTC

**Comment by jennifer-shehane** [comment] 2020-03-04 09:12
I've opened a PR in our docs to more specifically note this in our Migration Guide https://github.com/cypress-io/cypress-documentation/pull/2574

**Comment by FransPeterson** [comment] 2020-03-04 12:58
Thanks for the information.
