### ISSUE TITLE
"Cypress open" with `baseUrl` opens **to** `baseUrl` rather than Cypress itself.

### ISSUE THREAD

**Issue by ckpearson** [cypress-io/cypress#5797] opened 2019-11-26 11:20 UTC
# Current behavior:

Running `npx cypress open` with the following configuration:

```
{
  "pluginsFile": "tests/e2e/plugins/index.js",
  "baseUrl": "http://localhost:8080",
  "port": 8082,
  "chromeWebSecurity": false
}
```

Running the test in the cypress app opens the browser **to** the baseUrl rather than the Cypress interactive environment on the configured port:

![current-cypress-behaviour](https://user-images.githubusercontent.com/5690115/69625092-cad18680-103d-11ea-8a10-71bd4a9f5358.png)

### Desired behavior:

Cypress should launch to the interactive experience, and should render the application specified by the `baseUrl` within the interactive UI

### Steps to reproduce: (app code and test code)

Doesn't appear to be an issue with the specs or tests themselves, as they do run (as proven by video and screenshots) via `npx cypress run`, instead it appears to be an issue with how cypress handles the config.

### Versions

- Cypress 3.6.1 (via `@vue/cli-plugin-e2e-cypress ^4.0.5`)
- Windows 10 Enterprise (10.0.17763 N/A Build 17763)
- Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by ckpearson** [comment] 2019-11-26 11:50
It appears this is probably related to: #1253 as switching the browser to electron does in fact work.

**Comment by jennifer-shehane** [comment] 2019-11-27 08:02
@ckpearson Please close this issue if it is a duplicate of #1253 and the provided workaround from that issue has solved your issue.

**Closed** 2019-11-27 08:54 UTC
Labels: stage: awaiting response
