### ISSUE TITLE
[Multi-origin][Spike]: Various driver tests fail in more recent versions of Firefox

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#20968] opened 2022-04-07 19:08 UTC
### Current behavior

Various driver tests fail when run in the latest version of Firefox (98 as of writing this) that don't fail in older versions. Tests pass in Firefox 93, which is what we run in CI.

For example, [`e2e/multi-domain/multi_domain_spec.ts`](https://github.com/cypress-io/cypress/blob/8a78b5c127a937df58d96e4b1d1f689416ce387d/packages/driver/cypress/integration/e2e/multi-domain/multi_domain_spec.ts) results in the 2nd test failing with no commands run:

![Screen Shot 2022-04-07 at 3 06 25 PM](https://user-images.githubusercontent.com/1157043/162278141-20aef748-4359-414b-b286-387cfb2d25e1.png)

This also causes subsequent tests not to run.

### Desired behavior

All tests should pass in the latest Firefox.

### Test code to reproduce

Run [`e2e/multi-domain/multi_domain_spec.ts`](https://github.com/cypress-io/cypress/blob/8a78b5c127a937df58d96e4b1d1f689416ce387d/packages/driver/cypress/integration/e2e/multi-domain/multi_domain_spec.ts) in a recent version of Firefox.

### Cypress Version

feature-multidomain branch

**Comment by mjhenkes** [comment] 2022-05-16 21:34
duplicate of #21300

**Closed by mjhenkes** 2022-05-16 21:34 UTC
Labels: stage: backlog, cy.origin, E2E-auth
