### ISSUE TITLE
Please add support for the http verb QUERY

### ISSUE THREAD

**Issue by epchelina** [cypress-io/cypress#29076] opened 2024-03-06 22:16 UTC
### What would you like?

I am testing an application that uses http verb QUERY. For example, we have this endpoint`/api/v3/Location` and an http verb QUERY. 

When I run a UI Cypress test, Cypress Test Runner returns 400 Bad request for the `/api/v3/Location` endpoint.

Example of the request payload that is being sent with QUERY `/api/v3/Location`:

(accountid: “1234”) {
      id
      name
      latitude
      longitude
      address1
      address2
      city
  }

### Other

Please let me know if there are any available work arounds? Thanks!

**Comment by jennifer-shehane** [comment] 2024-03-07 03:36
Duplicate of https://github.com/cypress-io/cypress/issues/28282

**Closed as not planned by jennifer-shehane** 2024-03-07 03:36 UTC
Labels: type: duplicate
