### ISSUE TITLE
FR: Add UI to denote context function

### ISSUE THREAD

**Issue by sitefinitysteve** [cypress-io/cypress#2557] opened 2018-10-02 17:55 UTC
### Current behavior:

![image](https://user-images.githubusercontent.com/1542376/46366810-0ba45a00-c64a-11e8-908d-bacdc82ba77f.png)

The tests in the image above are wrapped in 

```js
context("Profile", function(){

});

context("Favourites", function(){

});

...etc
```

But none of that shows up in the UI anywhere.

### Desired behavior:

I'm using the "Log" because I want the UI to break me out some detail, but it would be great if somehow "context" was nested into the UI somewhere instead.

Ideally just more `it()` methods would work too, then I'd get the nice checkmarks by them, but every `it()` is a new page request and the site is protected so I need to load a custom route and log the user in to run the test... so it's very time consuming to visit a new page on every contextual test just for UI embellishments.

**Comment by egucciar** [comment] 2018-10-24 13:51
I guess we would like a way to group assertions and commands with pretty collapsible messages and check marks if anything

**Comment by sitefinitysteve** [comment] 2018-10-24 13:59
@jennifer-shehane I DO have it() methods, the context() wrappers are inside that, which I guess per your screenshot is wrong.

Here's my problem, every it() is a new browser instance\request to the page. The problem is that it's a secure site so I'm hitting a custom route to log me in every time.

So I want to have one test to lets say validate core functionality, like menus, floating interactive stuff, clickable profile... stuff thats on every page.

If I wrap all of those into separate it() statements I massively increase my test run time, when I only ever want to hit the 1 page, then do multiple tests on it.

![image](https://user-images.githubusercontent.com/1542376/47435776-3e3a0200-d773-11e8-8211-e1b6067fb52f.png)

**Comment by sitefinitysteve** [comment] 2018-10-29 13:57
@jennifer-shehane Please if you could respond or re-open...

**Comment by sitefinitysteve** [comment] 2018-11-06 19:35
@jennifer-shehane I'm begging you to re-open I don't want to have to make a new issue 

Here's a real world example of how messy it is currently.  This is testing an angular wizard-style app.  I have no way to "Group" the test items so the UI isn't just a massive garbled mess.

![image](https://user-images.githubusercontent.com/1542376/48088901-2e89d700-e1d1-11e8-8f8d-861161dbcfbd.png)

**Comment by bahmutov** [comment] 2019-07-08 18:04
Hey @sitefinitysteve to me your test seems a little bit ... unfocused. I would replace all assertions in the above comment with a single visual test. The code would be simply something like this

```js
it('looks correct', () => {
  cy.get('...').click()
  cy.visualScreenshotTest()
})
```

and the `cy.visualScreenshotTest` would be a command from either a DIY image comparison plugin or 3rd party commercial image diffing service plugin. Read https://on.cypress.io/visual-testing guide to see what I mean.

But a little grouping of commands in the log would be a nice thing I believe, which maybe @NicholasBoll would find useful as well

PS: even if you log in once to the site, you can still organize your tests in separate `it()` blocks, see examples in our "Logging in recipes" https://github.com/cypress-io/cypress-example-recipes#logging-in-recipes For example, see this recipe: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__jwt/cypress/integration/spec.js

**Comment by sitefinitysteve** [comment] 2019-07-08 18:20
@bahmutov So I don't feel like visual diffing is what needs to happen here (can happen?). It's a private site, and the data is constantly changing for the test.  It's an angular component to page through steps, so once the test runs once, the data is now different, so a visual test would fail if it runs a second time.  I know in a perfect world test finishes, data gets reset, or the data is just mocked, but this test I need to run though the system live.

So the problem with a new it() block is (because the site is 100% locked) I need to hit a custom CILogin page to then redirect me in for the test to execute, and the more times I have to do that the slower it all runs, where just hitting the ci\page the once I can then just ram through everything... but then I'm in the output mess you see in the screenshot.

**Comment by NicholasBoll** [comment] 2019-07-08 19:10
I opened up an issue a while ago similar to what you want. I think there is a bit of confusion in this issue though: `context` is actually an alias for `describe`. What you want is some grouping: #1260

I think log grouping is necessary to understand "macros"/custom commands/helper functions. Otherwise, you're right: we have a list to describe a tree.

**Comment by jennifer-shehane** [comment] 2019-07-23 10:29
@NicholasBoll I think so too. Going to close as duplicate of https://github.com/cypress-io/cypress/issues/1260

**Closed by jennifer-shehane** 2019-07-23 10:29 UTC
Labels: pkg/reporter, pkg/server, stage: proposal 💡, type: feature
