### ISSUE TITLE
Cypress is not able to clean /screenshots

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#4655] opened 2019-07-05 12:57 UTC
### Current behavior:

On every run, cypress will clean it's screenshots folder (as mentioned in the documentation). Unfortunately on Windows it is likely that the filenames are too long and thus can not be deleted. When cypress tries to do this, it ignores those files. 
We take all screenshots after the test runs and publish them as build artifacts. So this is a problem as we always see old screenshots.

### Desired behavior:

Cypress should be able to delete them anyway.

I will use a own build step that uses "rimraf" to do this. maybe cypress should include rimraf or similar for this task?

### Steps to reproduce: (app code and test code)

https://github.com/gabbersepp/cypress-test-tiny

Execute cypress from this repo on a Windows 2016 Server.

Please note: It seems that Windows 10 has increased it's max path length. So when using this repo on a Win10 machine, you will have no issues. 

### Versions

cypress 3.3.2
Windows 10
Chrome: Version 75.0.3770.100 (Offizieller Build) (64-Bit)

**Comment by jennifer-shehane** [comment] 2019-07-08 10:17
Thanks for providing a reproducible example. We shouldn't be creating screenshot files with a filename that is too long - so that we don't run into a problem deleting them. 

There is some code to ensure filename length here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L326

As well as tests here: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshots_spec.coffee#L243

**Comment by gabbersepp** [comment] 2019-07-08 12:15
Thanks to make that clear.
Unfortunatelly, this code ensures a max filename length but ignores the directory structure.
In Windows we have 260 chars including the directory structure.

But I am not sure if this needs to be fixed as stated in **https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names** the new Win10 versions do not have this limitation anymore and also new windows server versions doesn't restrict the length.

By using rimraf I have fixed this for our purpose.

**Comment by gabbersepp** [comment] 2019-10-14 11:20
@jennifer-shehane maybe I can fix this. Is it acceptable to include rimraf dependency only for this task?

**Comment by jennifer-shehane** [comment] 2021-02-03 07:27
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-03 07:27 UTC
Labels: OS: windows, first-timers-only, pkg/server, stage: ready for work, type: bug
