### ISSUE TITLE
Uncaught error in plugins file not displayed in Desktop GUI

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2723] opened 2018-11-06 00:08 UTC
### Expected: 
If there's an EACCES error in the plugins file, Cypress should show `Error EACCES` or similar message in the desktop gui

### Actual: 
Spinner spins forever
![cens](https://user-images.githubusercontent.com/14625260/48034564-ec5b8980-e12d-11e8-84ac-c1dbd2e36bad.png)

### To reproduce:

```
npm i --save-dev express
```

in `plugins/index.js`:
```
const express = require('express')

const PORT = 443

const app = express()
app.listen(PORT, () => console.log(`Test Server running on port ${PORT}`))
```

now launch cypress without `sudo` and you should get the permissions error since you've set the port to 443

**Comment by chrisbreiding** [comment] 2018-11-06 14:04
Steps to reproduce?

**Comment by jennifer-shehane** [comment] 2019-07-13 02:36
This is still happening in Cypress version 3.4.0.

**Comment by chrisbreiding** [comment] 2019-07-16 14:26
I'm unable to reproduce this. It runs the server without any error. 

Were you able to reproduce this on MacOS, @jennifer-shehane? Wondering if this is OS-specific.

**Comment by jennifer-shehane** [comment] 2020-11-06 06:05
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-11-06 06:05 UTC
Labels: stage: ready for work, topic: plugins ⚙️, type: bug
