### ISSUE TITLE
Cypress 3.4.0 can't start

### ISSUE THREAD

**Issue by inovramadani** [cypress-io/cypress#4770] opened 2019-07-20 23:49 UTC
### Current behavior:
Always got this error when installing 3.4.0 and then run cypress open
![image](https://user-images.githubusercontent.com/27492820/61585414-59606380-ab85-11e9-8d9c-847c12e3a7b3.png)

I tried installing 3.3.2, it can run smoothly.

### Desired behavior:
Should be able to start.

### Steps to reproduce: (app code and test code)
1. npm i cypress
2. set cypress:open script "cypress open" in package.json
3. npm run cypress:open

### Versions
3.4.0
Windows 10

**Comment by jennifer-shehane** [comment] 2019-07-23 07:26
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4624

**Closed by jennifer-shehane** 2019-07-23 07:26 UTC
