### ISSUE TITLE
Cypress verification is still timing out in Docker CI environments

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#7879] opened 2020-07-03 14:29 UTC
### Current behavior:

We run our Cypress tests inside Docker containers (with Kubernetes) as part of our CI. Sometimes our k8s cluster hardware is slow (being overburdened with other tasks) and verification takes longer than 30 seconds, which causes Cypress to fail, and therefore the entire build to fail. This ends up wasting a lot of our time.

I had added a comment here (https://github.com/cypress-io/cypress/issues/4624#issuecomment-563675146) with some details and received no response. As noted in that comment, we've already tried enabling debug logs, but they don't offer any additional information.

### Desired behavior:

As has been requested by others, we would like a user-facing knob to address this. Either:

1. A way to disable verification completely, or
2. A way to increase the 30-second timeout to a value of our choosing

### Test code to reproduce

As has been noted elsewhere, there is no software repro for this. In my experience, the repro is to run Cypress tests on some slow or overburdened hardware such that verification takes longer than 30 seconds.

### Versions

Cypress 4.8.0, Linux, Chrome 83

**Comment by jennifer-shehane** [comment] 2020-07-06 06:25
Duplicate of #6082

**Closed by jennifer-shehane** 2020-07-06 06:25 UTC

**Comment by kaiyoma** [comment] 2020-07-06 17:12
Oh whoops! I forgot I had already added an open issue. Sorry about that. 😳
