### ISSUE TITLE
net-stubbing.ts breaks some TS tooling, should be .d.ts

### ISSUE THREAD

**Issue by vpanta** [cypress-io/cypress#15644] opened 2021-03-24 16:48 UTC
### Current behavior
We use Bazel, and `bazelbuild/rules_nodejs` generates helper targets to allow arbitrary installed NPMs visibility within Bazel's build dependency tree. When we use this with `cypress` and need to import `cypress/types/net-stubbing`, we get the following `strictDeps` error from Bazel's wrapped `tsc`:
```
error TS2307: [strictDeps] transitive dependency on external/npm/node_modules/cypress/types/net-stubbing.ts not allowed. Please add the BUILD target to your rule's deps.
```

This is due to `net-stubbing.ts` being seen as a full TS file instead of a type-declaration file (`.d.ts`), even though (AFAICT) it only contains TS typings.

### Desired behavior
It should be visible upstream, even when using Bazel

### Test code to reproduce
Not provided, due to the bazel setup this isn't very straightforward

### Versions
Cypress 6.3.0
Bazel 3.1.0
rules_nodejs 3.2.1

### Suggested Fix
Generate `net-stubbing.d.ts` instead of `net-stubbing.ts`, should be generally compatible with other users (assuming they import as `cypress/types/net-stubbing`).
PR with this suggestion is forthcoming.

**Comment by karfau** [comment] 2021-05-20 23:08
This is also a problem when adding custom command and the related types that need to have any types from that file as arguments, e.g. for wrapping `cy.intercept` (`HttpRequestInterceptor`, `RouteMatcher` in my case).

Due to the issue perfectly described above, the types can not be referenced in a `*.d.ts` file using 
```typescript
/// <reference types="cypress/types/net-stubbing" />
```
it complains with `TS2688: Cannot find type definition file for 'cypress/types/net-stubbing'.`

I think it would be quite straight forward to provide a "Test code to reproduce" for my case (if it's not already "obvious" from the details I gave).

**Comment by jordanpowell88** [comment] 2022-06-02 14:56
I am also running into this issue when trying to add Angular CT support. AFAIK this change should be pretty straitforward a just requires a name change of that file and that reference to it in the `index.d.ts` file
![Screen Shot 2022-06-02 at 10 19 08 AM](https://user-images.githubusercontent.com/3605268/171658445-e8928377-c198-4327-a650-191a2623ef3d.png)

**Comment by ZachJW34** [comment] 2022-11-15 18:40
This was fixed in #22858 and is available since v10.5.0 of Cypress

**Closed by ZachJW34** 2022-11-15 18:40 UTC
Labels: stage: backlog, type: typings

**Comment by karfau** [comment] 2022-11-15 20:23
No chance for a backport to the 9.x branch

**Comment by ZachJW34** [comment] 2022-11-15 20:51
@karfau no, we do not backport fixes to older versions.
