### ISSUE TITLE
Browser: 'chrome' was not found on your system or is not supported by Cypress.

### ISSUE THREAD

**Issue by Arcturus5404** [cypress-io/cypress#15390] opened 2021-03-10 08:21 UTC
### Current behavior

Cypress won't run because chrome is not installed?
Can't run because you've entered an invalid browser name.
```
e2e_2                  | 
e2e_2                  | Browser: 'chrome' was not found on your system or is not supported by Cypress.
e2e_2                  | 
e2e_2                  | Cypress supports the following browsers:
e2e_2                  | - chrome
e2e_2                  | - chromium
e2e_2                  | - edge
e2e_2                  | - electron
e2e_2                  | - firefox
e2e_2                  | 
e2e_2                  | You can also use a custom browser: https://on.cypress.io/customize-browsers
e2e_2                  | 
e2e_2                  | Available browsers found on your system are:
e2e_2                  | - firefox
e2e_2                  | - electron
```
### Desired behavior

Cypress should run, just like the other 3 docker containers based on the same image which do run. e2e_1, 3 and 4 all run fine!

### Versions
6.6.0

**Comment by jennifer-shehane** [comment] 2021-03-16 20:39
Please see our [troubleshooting guide on Launching Browsers](https://on.cypress.io/troubleshooting#Launching-browsers)

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) specifically logging `cypress:launcher` logs and run `cypress info` and print the entire set of logs here?

**Comment by jennifer-shehane** [comment] 2021-04-28 13:57
Duplicate of https://github.com/cypress-io/cypress/issues/8611

**Closed by jennifer-shehane** 2021-04-28 13:57 UTC
Labels: stage: needs information
