### ISSUE TITLE
Cypress 3.8.1 - visible element is not recognised as visible

### ISSUE THREAD

**Issue by nekolnyt** [cypress-io/cypress#6095] opened 2020-01-06 10:37 UTC
### Current behavior:
After upgrade to Cypress `3.8.1` I am getting failures on visibility check for some elements which are actually visible.

`cy.get('._2y_1QBqUOhnVj7K4NfZN').should('be.visible');`

<img width="1914" alt="visibility check" src="https://user-images.githubusercontent.com/54807371/71810315-64934700-3072-11ea-9083-b65a820ac16e.png">

### Desired behavior:
The element is visible, the check should pass.

### Versions
Cypress 3.8.1
Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
OS: MacOS 10.15.1 (19B88)

**Comment by jennifer-shehane** [comment] 2020-01-07 07:42
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

I tried with the given css styles and am unable to reproduce. We need test code and HTML to run against to reproduce the exact issue.

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
<div style="box-sizing: 
border-box; 
display: block; 
flex-basis: auto; 
flex-grow: 1; 
flex-shrink: 1;
font-size: 20px; 
font-weight: 300; 
line-height: 32px; 
min-width: 0; 
position: relative; 
text-size-adjust: 100%; 
user-select: none;">Objectives</div>
</body>
</html>
```

`spec.js`

```js
it('visibility', () => {
  cy.visit('index.html')
  cy.get('div').should('be.visible')
})
```

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-01-07 07:42 UTC
