### ISSUE TITLE
`.click()` doesn't fire `mouseout` event if element is obscured

### ISSUE THREAD

**Issue by Hypercubed** [cypress-io/cypress#5500] opened 2019-10-28 19:49 UTC
### Current behavior:

In v3.5 a `click()` action also triggers the `mouseover` and `mouseout` events.  However, if the element becomes obscured (for example hidden behind a dialog) due to the `.click()` action the `mouseout` event is never fired.  In some cases, this can leave the UI in a state that will cause later tests to fail.

Note: A workaround is to use `.click().trigger('mouseout', { 'force': true })`.

### Desired behavior:

The `mouseout` event should trigger if the element becomes obscured... in other words the user can no longer hover.  This is the behavior I see in the native browser.

### Steps to reproduce: (app code and test code)

* A button contains a tooltip that obscures another button
* Clicking on the first button causes a dialog to be shown for 1s.

See: https://github.com/Hypercubed/cypress-test-tiny/blob/5080e0943eb91a5da7c57b34e91f19a7ae8fab07/cypress/integration/spec.js

You will see that in v3.5 (but not v3.4 or native chrome) the tooltip remains even after the dialog opens and obscures the button.

![image](https://user-images.githubusercontent.com/509946/67712511-bdb37000-f989-11e9-8e7f-f4b168aea818.png)

### Versions

v3.5

**Comment by jennifer-shehane** [comment] 2019-10-28 20:20
@Hypercubed Thanks for providing a reproducible example. This is quite clever. https://github.com/Hypercubed/cypress-test-tiny/commit/5080e0943eb91a5da7c57b34e91f19a7ae8fab07

I'm able to reproduce this and verify this behavior if not what happens manually when you click - the failure was introduced in 3.5.0.

**Comment by Bkucera** [comment] 2019-10-28 23:03
@Hypercubed since 3.5.0 added mouseover/mouseout events, we now send those and behave similar to touch devices, where we won't send `mouseout` until a new element has been clicked. 

For this reason we have the same result as a mobile user would on your app, see here in Mobile Emulation Mode:
![19-10-28_17:36::36](https://user-images.githubusercontent.com/14625260/67724369-34b22e00-f9b5-11e9-9742-55ecb078fe1a.gif)

If you want to just trigger the click and avoid the popover, you can either use `.trigger('click')` or use `.trigger('mouseout')` after the `click`

I'm going to close this as expected behavior

**Comment by Hypercubed** [comment] 2019-10-28 23:18
Hmmm... I'm not certain.  Why should cypress behave like a touch device?  Has cypress chosen to behave like a touch device in all cases?  Any way to control that?

**Comment by Bkucera** [comment] 2019-10-29 02:32
@Hypercubed the element should receive mouseout upon the next cy.click or cy.type command, since those are the only two commands that "move" the cursor. 

We could allow an option to emit sending hover events during a click, which would solve your issue.

You can overrite the cypress click command in support/index.js and add a `.trigger('mouseout').trigger('mouseleave')` if you'd like the tooltips to immediately go away.

**Comment by Hypercubed** [comment] 2019-10-29 14:53
Hi @Bkucera, respectfully, I find it odd that cypress is following mobile behavior in this case.  Would it make sense to have separate a `click` and `touch` actions?

I don't think it's possible to implement correct behavior using a command.  It's not that 'mouseout' and 'mouseleave' fire after every click... only when (AFAIK) the target element becomes covered by another element as a result of a click.

**Comment by marjan-georgiev** [comment] 2019-10-29 15:09
@Bkucera any reason you chose to emulate the touch behaviuor? 
This is not the default behaviour of the browser when not using a touch device, so there's a concerning inconsistency now.

Is there a way to turn this behaviour off without having to revert to <3.5.0?

**Comment by Bkucera** [comment] 2019-10-29 15:14
@marjan-georgiev it's not that we chose to emulate touch behavior, we did not. We chose to begin sending `mouseover` and `mouseenter` as your mouse would when clicking on an element. Since we don't know when some other element comes in and obstructs your mouse, we can't know exactly when to send `mouseout` and `mouseleave`, until you issue another click, or type command

As I mentioned earlier, we could allow an option to omit sending hover events during a click, which would prevent any hover events (mouseover, mouseout) from being sent, which is pre-3.5.0 behavior.

**Comment by marjan-georgiev** [comment] 2019-10-29 15:27
I understand, thanks for the clarification.

> As I mentioned earlier, we could allow an option to omit sending hover events during a click, which would prevent any hover events (mouseover, mouseout) from being sent, which is pre-3.5.0 behavior.

I guess this would work. Do you imagine this being a global config, or something to pass as an argument to `click`?

**Comment by Bkucera** [comment] 2019-10-29 18:30
@Hypercubed in your case, your app does actually synchronously cover the element, so we _can_ sent the mouseout. I'll have a PR to fix, but know if you have your modal pop up in a `setTimeout` for example (or using async framework like react), we wouldn't be able to send those events

**Comment by Hypercubed** [comment] 2019-10-29 20:19
The bootstrap/jquery demo attached was just an example.  I'm seeing this issue in an angular application where dialogs may, in fact, be animating in async.

**Comment by Bkucera** [comment] 2019-10-29 20:21
alright, leaving closed then. let me know if the `.trigger('mouseout')` fixes the issue

**Closed by Bkucera** 2019-10-29 20:21 UTC

**Comment by Hypercubed** [comment] 2019-10-29 20:23
I'm using `.trigger('mouseout', { 'force': true })` in a few places.  I still think it would be useful to add an option to not send the additional mouse events.

**Comment by gabbersepp** [comment] 2020-08-25 07:41
Hi,
i also have random tooltips that do not disappear. `.trigger('mouseout', { 'force': true })` won't help because if the tooltip is not there, an error is thrown:

```
CypressError: `cy.trigger()` failed because this element is detached from the DOM.

`...`

Cypress requires elements be attached in the DOM to interact with them.
```

Our usecase: We have buttons that show a tooltip which sometimes does not disappear. In some cases, the button is removed from the page, thus `trigger(mouseout)` does not work because the button is not there anymore. Is there another fix for this?

**Comment by jennifer-shehane** [comment] 2020-08-25 08:00
@gabbersepp Probably the detached fix would be helpful https://github.com/cypress-io/cypress/issues/7306

**Comment by gabbersepp** [comment] 2020-08-25 08:26
@jennifer-shehane  I don't think that this is the same problem. In my case the element who got clicked and showed the tooltip was completely removed from the GUI. re-querying would not help here, or do I miss something?

The solution would be to inspect every usage of button clicks all over the tests and add the "trigger(mouseout)" only to those cases were the button does not disappear from the UI. But in my opinion this seems not to be a good test pattern.

**Comment by gabbersepp** [comment] 2020-08-25 08:33
To explain it a little bit better:

Let's say I have 2 buttons on two different pages. As the buttons are always built the same way, there is one generic `ButtonProvider` in the test project that can click the button based on a button name. Both buttons show a custom tooltip that appears on `mouseover` and disappear on `mouseout` or when the button is removed from the UI component (e.g. if the component is closed).
The first component will not be closed after the button was clicked. Here the tooltip does not disappear because after the click, no `mouseout` is triggered. Unfortunatelly I need to click exactly where the tooltip is which does not work. So the test fails.
This can be fixed by triggering `mouseout` 👍 
Component 2 is closed after the button was clicked. The tooltip is removed by the application fast enough so that the trigger of `mouseout` is too late. 
The only solution would be to find all cases where the components are closed and skip the `mouseout`.

**Comment by gabbersepp** [comment] 2020-08-25 08:41
I will try this hack to avoid an error in cypress. Jquery won't report an error if no element was found so maybe this will help us here:

```
.get(locator).click({force: true}).then($e => $e.mouseout()))
```
