### ISSUE TITLE
Cypress only records first 2 minutes of video

### ISSUE THREAD

**Issue by jmtimko5** [cypress-io/cypress#16630] opened 2021-05-21 21:48 UTC
I am not sure how to condense this into a reproducible bug, but very on every test run where a test fails the recorded video is only the first 2 minutes of our test run. You can tell from the failure screenshot at a completely different point from where the video ends below. The video doesn't get beyond the `before()` method completion, while the screenshot shows what is actually happening in the test. I have no idea why this happens so any guidance would be much appreciated.

Cypress Version: 7.2.0

https://user-images.githubusercontent.com/6867087/119201216-4a79bf00-ba43-11eb-9254-dbd5c142901e.mp4
![Test Rule CRUD -- Rule CRUD Testing (failed)](https://user-images.githubusercontent.com/6867087/119201270-65e4ca00-ba43-11eb-9dab-28b764e27f94.png)

**Comment by jennifer-shehane** [comment] 2021-05-24 18:36
Can you provide the version and browser that you're running in? We're trying to identify some video issues that may have been recently introduced https://github.com/cypress-io/cypress/issues/16498 

Does downgrading to 6.8.0 resolve the issue?

**Comment by jmtimko5** [comment] 2021-05-25 04:43
Hi @jennifer-shehane thanks for responding! We are using the following configuration:
Browser: Electron 89 (that is headless right?)
OS: Linux Debian 10.5
Cypress: 7.2.0

Downgrading to Cypress 6.8 does appear to have resolved the issue.

**Comment by jennifer-shehane** [comment] 2021-06-04 16:57
@jmtimko5 We've been running a lot of experiments on videos lately, in different environments, etc - and haven't quite seen this issue. 

What was a length of the actual video compared to the length of the test? Is the video freezing? Or is there only 2 mins of video length?

Can you provide a way to reproduce this? Or provide the video? Feel free to email to support@cypress.io if necessary. Thanks!

**Comment by jennifer-shehane** [comment] 2021-07-08 16:32
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-07-08 16:32 UTC
Labels: stage: needs information, topic: video 📹
