### ISSUE TITLE
preserveOnce does not work if you do not run all tests in a file

### ISSUE THREAD

**Issue by HuachuanD** [cypress-io/cypress#5409] opened 2019-10-22 00:14 UTC
If you have any "xit" in the file cookie get clean up even you have `preserveOnce` in `beforeEach`

### Current behavior:

If you have any "xit" in the file cookie get clean up even you have `preserveOnce` in `beforeEach`

### Desired behavior:

any test with xit should not run and `preserveOnce` should still work for other tests

### Steps to reproduce: (app code and test code)
```js
describe('test describe', () => {
    context('test context', () => {
       before(() => {
          cy.setCookie('locserv', 'locservcookie');
       })
        beforeEach(() => {
            Cypress.Cookies.preserveOnce('locserv');
        });

        xit('One', () => {
            cy.visit('www.google.com');
        });

        it('Two', () => {
            cy.visit('www.google.com');
            cy.getCookies();
            cy.wait(10000);
        });
    });
});
```

`cy.getCookies();` in the second it gets nothing

### Versions

OS Windows 10
Browser: Chrome 77
Cypress 3.4.1

**Comment by jennifer-shehane** [comment] 2019-10-28 16:49
Code within a `xit` is never run. `xit` is shorthand for `skip` of the test - the `cy.setCookie()` code is *never ran*, so there is absolutely never any cookie set - aka nothing for `preserveOnce` to ever preserve. Closing as this is the intended behavior of `xit`.

**Comment by HuachuanD** [comment] 2019-10-28 17:23
But if it skip xit why does it still clean up the cookie after skipping xit shouldn't it just ignore xit and run the next it so .preserveOnce should be ran and cookie set in before should be kept

**Comment by jennifer-shehane** [comment] 2019-10-28 19:59
Ok, I can recreate this behavior - ran this in Cypress 3.4.1. The cookie is set if the `skip` is removed or if the `skip` is moved to another test other than non-first test.

```js
context('test context', () => {
  before(() => {
    cy.visit('example.cypress.io')
    cy.setCookie('locserv', 'locservcookie')
  })
  beforeEach(() => {
    Cypress.Cookies.preserveOnce('locserv')
  })

  it.skip('One', () => {
    cy.getCookies().should('not.be.empty')
  })

  it('Two', () => {
    // only fails when .skip is on first test
    cy.getCookies().should('not.be.empty') 
  })
})
```

<img width="515" alt="Screen Shot 2019-10-28 at 3 56 28 PM" src="https://user-images.githubusercontent.com/1271364/67713076-85b52880-f99b-11e9-859e-4d1a3f4f6840.png">

**Comment by Auchindoun** [comment] 2019-11-26 15:32
@jennifer-shehane I'm also running into this issue intermittently in CI, on `3.4.1` (sorry for the necro). It appears that the cookie isn't being preserved for one specific test file, but not the rest.

We have:

```
export function testScreen(
  label: string,
  fn: (screen: ScreenFormat) => void,
  skipLogin = false,
  adminLogin = false,
) {
  describe(label, () => {
    // reset db
    before(() => resetQuery().then(query => cy.sql(query)))

    if (!skipLogin) {
      before(() => cy.resetConfig()[adminLogin ? 'adminLogin' : 'login']())
      beforeEach(() => Cypress.Cookies.preserveOnce('goalert_session.2'))
    }
    describe(screenName(), () => fn(screen()))
  })
}
```
and here is the file where the test fails, I'm only including up into the first test since it fails on the first one:
```
testScreen('Schedules', testSchedules)

function testSchedules(screen: ScreenFormat) {
  describe('Creation', () => {
    it('should create a schedule', () => {
      const name = c.word({ length: 8 })
      const description = c.sentence({ words: 5 })

      cy.visit('/schedules')

      cy.pageFab()
      cy.get('div[role=dialog]').should('contain', 'Create New Schedule')

      cy.get('input[name=name]')
        .type(name)
        .should('have.value', name)
      cy.get('textarea[name=description]')
        .type(description)
        .should('have.value', description)

      cy.get('button')
        .contains('Submit')
        .click()

      // verify on details by content headers
      cy.get('[data-cy=details-heading]').should('contain', name)
      cy.get('[data-cy=details]').should('contain', description)
    })
  })
```
---
Screenshots:
![image](https://user-images.githubusercontent.com/11381794/69647636-758e7880-102f-11ea-8d58-e3113dadd0f8.png)


![image](https://user-images.githubusercontent.com/11381794/69647615-6c9da700-102f-11ea-82b6-78798c49ad29.png)

**Comment by loliver1234** [comment] 2020-09-30 12:33
I face the same issue for cypress in version `5.2.0`

If in my spec file there is any test skipped before the one that is being executed - every 2nd rerun in cypress console the cookies are being cleared. If the skipped test is after the given test, then the cookies are always present.

Reference spec file:
```javascript
describe('Cookies test', function () {
  before(function () {
    Cypress.Cookies.debug(true);
    cy.setCookie('test-cookie', 'test cookie');
  });

  beforeEach(function () {
    console.log('beforeEach: before preserveOnce');
    Cypress.Cookies.preserveOnce('test-cookie');
    console.log('beforeEach: after preserveOnce');
    cy
      .getCookie('test-cookie', {log: true})
      .then((cookie) => console.log('Cookie: ' + JSON.stringify(cookie)))
  });

  it.skip('Skipped before', function() {});

  it('Test cookies', function() {
    console.log('it: Test cookies start');
    cy
      .getCookie('test-cookie', {log: true})
      .then((cookie) => {
          console.log('Cookie: ' + JSON.stringify(cookie))
          expect(cookie).not.to.be.null
      });
  });

  it.skip('Skipped after', function() {});

});
```

Console logs of a successful run:
```
Cookie Set: 'test-cookie' 
domain: ".my.domain"
expiry: 2232621090
hostOnly: false
httpOnly: false
name: "test-cookie"
path: "/"
sameSite: "unspecified"
secure: false
value: "test cookie"
__proto__: Object
----------------------------------------------------------------
beforeEach: before preserveOnce
----------------------------------------------------------------
beforeEach: after preserveOnce
----------------------------------------------------------------
Cookie: {"name":"test-cookie","value":"test cookie","path":"/","domain":".my.domain","secure":false,"httpOnly":false,"expiry":2232621090}
----------------------------------------------------------------
it: Test cookies start
----------------------------------------------------------------
Cookie: {"name":"test-cookie","value":"test cookie","path":"/","domain":".my.domain","secure":false,"httpOnly":false,"expiry":2232621090}
```

Console logs of a failed run (every next rerun after the successful one of spec file):
```
Cookie Set: 'test-cookie' 
domain: ".my.domain"
expiry: 2232621010
hostOnly: false
httpOnly: false
name: "test-cookie"
path: "/"
sameSite: "unspecified"
secure: false
value: "test cookie"
__proto__: Object
----------------------------------------------------------------
beforeEach: before preserveOnce
----------------------------------------------------------------
beforeEach: after preserveOnce
-----------------------------------------------------------------
Cookie Removed: 'test-cookie' 
domain: ".my.domain"
expiry: 2232621010
hostOnly: false
httpOnly: false
name: "test-cookie"
path: "/"
sameSite: "unspecified"
secure: false
value: "test cookie"
__proto__: Object
----------------------------------------------------------------
Cookie: null
----------------------------------------------------------------
it: Test cookies start
----------------------------------------------------------------
Cookie: null
```

**Comment by emilyrohrbough** [comment] 2022-11-16 22:55
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been replaced with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.

**Closed by emilyrohrbough** 2022-11-16 22:55 UTC
Labels: type: bug, stage: needs investigating, topic: cookies :cookie:
