### ISSUE TITLE
Failed to connect to Chrome, retrying in 1 second / Error launching browser

### ISSUE THREAD

**Issue by NoahGrayLee** [cypress-io/cypress#14304] opened 2020-12-24 03:29 UTC
### Current behavior
![image](https://user-images.githubusercontent.com/38752819/103057217-42c40480-45e2-11eb-8c92-836751974d96.png)

Cannot run an individual test case on Cypress.
Able to open the test list, but when I click an item, Cypress fail to open the Chrome browser.
It says "Failed to connect to Chrome, retrying in 1 second and finally failed with this message." on the terminal.

I tried on my previous branches but also failed.

> Error launching browser
> Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.
> This usually indicates there was a problem opening the Chrome browser.
> The CDP port requested was 64768.
> Error details: Error: connect ECONNREFUSED 127.0.0.1:64768 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
-----

### Desired behavior

Able to run the testings on Cypress

### Test code to reproduce
I tried multiple test cases but failed to open

### Versions
In my memory, I updated to version 6.1.0 several days or 1 week? ago, and at that time all cases are working fine. 
Today I got this error and updated to version 6.2.0 but it didn't solve the problem.
So did downgrade to 6.0.0 and try again, but also failed. 

I updated Chrome also to solve this issue. 
Now the Chrome Version is 87.0.4280.88 (Official Build) (x86_64)
And I'm on macOS Mojave (version 10.14.6)

(added at 2020-12-27)
I cloned the code from Git to another laptop and installed Cypress as 6.0.0.
It's working now but hope to do this on my main machine also.. 
Current machine is macOS High Sierra (10.13.6), Chrome 86.0.4240.80 

Thanks

**Comment by jennifer-shehane** [comment] 2020-12-29 03:43
Duplicate of https://github.com/cypress-io/cypress/issues/8986

**Closed by jennifer-shehane** 2020-12-29 03:43 UTC
