### ISSUE TITLE
when text contains whitespace, incorrect/confusing error message in web console

### ISSUE THREAD

**Issue by alexch** [cypress-io/cypress#2003] opened 2018-06-21 13:03 UTC
### Current behavior:

![image](https://user-images.githubusercontent.com/8524/41720366-d56fcc90-7530-11e8-9b27-fc6fabd0e0fb.png)

When the actual text contains trailing whitepace, instead of displaying the actual text in boldface, it displays double asterisks around the text, unbolded, with no clear indication that the distinction between actual and expected is a single space character. 

When the expected text does *not* contain trailing whitespace, it displays a space between the final character and the comma.

Underneath the log message is an error box that does include trailing whitespace in the actual string, but that message is harder to read and contradicts its neighbor. 

### Desired behavior:

Whitespace in strings should be clearly indicated -- especially since whitespace mismatch is a very common source of test failures.

My advice is to ditch the faux-markdown double-star bold trick, and instead output correct HTML, including a "no-wrap" style so relevant space characters do not turn into misleading newlines, and including correct string-escaped versions of tab, newline, etc.

### Steps to reproduce:

See https://github.com/BurlingtonCodeAcademy/markdown_preview (branch solution). Inside the top H1 put a trailing space:

``` 
<h1>Markdown Preview </h1>
```

then run the specs with `cypress open`.

### Versions

Cypress 3.0.1

**Comment by chrisbreiding** [comment] 2018-06-21 15:01
Duplicate of https://github.com/cypress-io/cypress/issues/1360

**Closed by chrisbreiding** 2018-06-21 15:01 UTC
