### ISSUE TITLE
Dynamic test doesn't work properly

### ISSUE THREAD

**Issue by chirita-alex** [cypress-io/cypress#5378] opened 2019-10-16 12:45 UTC
### Current behavior:
   Dyanmic test it is skipped

```js
context('Check Videos', () => {
 **// This map it's skipped during the test run**
    Cypress._.map(videoList, (videoDetails) => {
      it(`${videoDetails.title}`, () => {
        cy.visit(`${videoDetails.path}`, {timeout: 120000});
        cy.wait(10000);

        cy.get('.rc-slider-handle', {timeout: 120000}).then((el) => {
          const styleLeft = Cypress._.trimEnd(Cypress._.get(Cypress._.find(el, 'style'), 'style.left'), '%');

          if (styleLeft > 0) {
            cy.get('#episodePlayerContainer-the-jwPlayer').should('have.class', 'jw-state-playing');
            cy.log(`**OK!! ${videoDetails.path}**`);
          } else {
            brokenVideos.push({title:videoDetails.title, path:videoDetails.path});
            cy.log(`**THIS MOVIE DOESN'T WORK!!, MOVIE TITLE -->> ${videoDetails.title} <<--**`);
          }
        });
      })
    })
  });
```  
### Versions
cypress: "3.4.1"
macOS Mojave Version: 10.14.6
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
node: v8.11.2

### FULL CODE
```js
const videoList = [];
const brokenVideos = [];

describe('Videos', () => {
  before(() => {
    cy.fixture('../fixtures/videoList.json').each((el) => {
      videoList.push(el);
    });
  });

  context('Check Videos', () => {
 **// This map it's skipped during the test run**
    Cypress._.map(videoList, (videoDetails) => {
      it(`${videoDetails.title}`, () => {
        cy.visit(`${videoDetails.path}`, {timeout: 120000});
        cy.wait(10000);

        cy.get('.rc-slider-handle', {timeout: 120000}).then((el) => {
          const styleLeft = Cypress._.trimEnd(Cypress._.get(Cypress._.find(el, 'style'), 'style.left'), '%');

          if (styleLeft > 0) {
            cy.get('#episodePlayerContainer-the-jwPlayer').should('have.class', 'jw-state-playing');
            cy.log(`**OK!! ${videoDetails.path}**`);
          } else {
            brokenVideos.push({title:videoDetails.title, path:videoDetails.path});
            cy.log(`**THIS MOVIE DOESN'T WORK!!, MOVIE TITLE -->> ${videoDetails.title} <<--**`);
          }
        });
      })
    })
  });

  context('Broken Videos', () => {
    it('BrokenVideos', () => {
      if(brokenVideos.length > 0) {
        Cypress._.map(brokenVideos, (value) => {
          cy.log(`**BROKEN MOVIE TITLE -->> ${value.title} <<--**`);
        });

        Cypress._.map(brokenVideos, (value) => {
          cy.visit(`${value.path}`, {timeout: 120000});
          cy.wait(10000);
          cy.get('.rc-slider-handle').should('have.css', 'left').and('gt', '0px');
          cy.get('#episodePlayerContainer-the-jwPlayer').should('have.class', 'jw-state-playing');
        });
      } else {
        cy.log('**NO BROKEN VIDEOS**');
      }
    });
  });
});
```
**Note: If I use hardcoded videoList array it work's very fine**

**Comment by jennifer-shehane** [comment] 2019-10-16 18:59
Unfortunately we have to close this issue as there is not enough information to reproduce the problem.

Please narrow down this issue to a small reproducible example to highlight the exact failure. The below example works, for example. Can you provide an example pulling out what about your example doesn't work versus mine? We need a full example we can run on our machines and see the error. 

```js
context('Check Videos', () => {
  Cypress._.map(['1', '2'], (videoDetails) => {
    it(`${videoDetails}`, () => {
      cy.log(videoDetails)
    })
  })
})
```

**Closed by jennifer-shehane** 2019-10-16 18:59 UTC

**Comment by chirita-alex** [comment] 2019-10-17 07:56
The problem appears when I use the data from fixture in dynamic test. 
This code doesn't work 
```
const videoDetails = [];
const brokenVideos =[];

  before(() => {
    cy.fixture('../fixtures/videoList.json').each((el) => {
      videoDetails.push(el);
    });
  });

  context('Check Videos', () => {
    Cypress._.map(videoList, (videoDetails) => {
      it(`${videoDetails.title}`, () => {
        cy.visit(`${videoDetails.path}`, {timeout: 120000});
        cy.wait(10000);

        cy.get('.rc-slider-handle', {timeout: 120000}).then((el) => {
          const styleLeft = Cypress._.trimEnd(Cypress._.get(Cypress._.find(el, 'style'), 'style.left'), '%');

          if (styleLeft > 0) {
            cy.get('#episodePlayerContainer-the-jwPlayer').should('have.class', 'jw-state-playing');
            cy.log(`**OK!! ${videoDetails.path}**`);
          } else {
            brokenVideos.push({title:videoDetails.title, path:videoDetails.path});
            cy.log(`**THIS MOVIE DOESN'T WORK!!, MOVIE TITLE -->> ${videoDetails.title} <<--**`);
          }
        });
      })
    });
  });
```
### Next code works but integration test it's no more dynamic

```
const brokenVideos =[];
  before(() => {
    cy.fixture('../fixtures/videoList.json').each((el) => {
      brokenVideos.push(el);
    });
  });

  context('Broken Videos', () => {
    it('BrokenVideos', () => {
      console.log('BrokenVideos ====>>>>', videoList);
      if(brokenVideos.length > 0) {
        Cypress._.map(brokenVideos, (value) => {
          cy.log(`**BROKEN MOVIE TITLE -->> ${value.title} <<--**`);
        });

        Cypress._.map(brokenVideos, (value) => {
          cy.visit(`${value.path}`, {timeout: 120000});
          cy.wait(10000);
          cy.get('.rc-slider-handle').should('have.css', 'left').and('gt', '0px');
          cy.get('#episodePlayerContainer-the-jwPlayer').should('have.class', 'jw-state-playing');
        });
      } else {
        cy.log('**NO BROKEN VIDEOS**');
      }
    });
  });
```

**Comment by chirita-alex** [comment] 2019-10-17 09:13
Problem solved with const videoList = require('../fixtures/videoList.json');

**Comment by jennifer-shehane** [comment] 2020-01-03 09:28
@chirita-alex I believe this is due to this issue https://github.com/cypress-io/cypress/issues/4716
