### ISSUE TITLE
Cypress crashes when a site uses a secure cookie but served in http

### ISSUE THREAD

**Issue by randing89** [cypress-io/cypress#3720] opened 2019-03-15 18:25 UTC
This issue was a follow up for https://github.com/cypress-io/cypress/issues/1321#issuecomment-462647518

### Current behavior:

It is very common to run a dev server locally with HTTP. However in this case the server still puts `secure` keyword in `set-cookie` because in production environment it will be served with HTTPS.

Cypress 3.1.5 crashes with following error message:
`Error: Failed to parse or set cookie named "JSESSIONID".`

### Desired behavior:

Not crash

### Steps to reproduce: (app code and test code)

Return following in response header with HTTP
`set-cookie: JSESSIONID=4C30AC94E795759EC164FF34D2FD5AB6; Path=/wiki; Secure; HttpOnly`

### Workaround

- Remove the `Secure` keyword.
- Make local dev server to work with HTTPS
- Downgrade to 3.1.0

### Versions

3.1.5

**Comment by jennifer-shehane** [comment] 2019-03-15 19:04
Duplicate of https://github.com/cypress-io/cypress/issues/3525

**Closed by jennifer-shehane** 2019-03-15 19:04 UTC

**Comment by vidhyaSoundararajan** [comment] 2019-11-18 19:51
Hi all, 
Im trying to bypass the multifactor authentication in my code and getting the error " Failed to parse or set cookie  when run my code in Chrome browser. Below is my code:
cy.request('POST', 'https://XXX.com/api/v1/sessions', {
        "sessionToken": sessionToken
      })
      .then((response) => {
        console.log(response.body);
        var options = {};
        options.domain = '.xxx.com';
       options.log = 'true';
        options.secure= true;
      //cy.clearCookies()
    //  cy.clearCookie('sid')
        cy.setCookie('sid', response.body.id,options);
      })
    })
    cy.visit(applicationURL)


Any ideas?

**Comment by flotwig** [comment] 2019-11-18 19:52
@vidhyaSoundararajan Please open a new issue, this issue is closed and is a duplicate of another issue.
