### ISSUE TITLE
Uncaught syntax error in selector expression.

### ISSUE THREAD

**Issue by tzolnai** [cypress-io/cypress#9073] opened 2020-11-03 13:27 UTC
I experienced an issue with syntax error detection. I managed to use a wrong selector accidentally in one of my tests which were not recognized as a syntax error. It just passed and then sometimes it just failed randomly.

### Current behavior
A syntax error is not caught in a specific selector string and the test goes on.

### Desired behavior
The syntax error should be caught and the test should fail.

### Test code to reproduce
```js
describe('Syntax error.', function() {

	it('Uncaught syntax error.', function() {
		cy.visit('https://googlechrome.github.io/samples/picture-in-picture/');
		
		cy.get('#holy-grail[style=\'visibility: visible;')
			.should('not.be.visible');
	});
});
```

The closing `\']` characters are missing from the selector, but this test case just passes without a problem.

### Versions

cypress version: 5.3.0
browser: chromium 78.0.3904.108
OS: openSUSE Leap 15.0

**Comment by jennifer-shehane** [comment] 2020-11-04 04:18
This is essentially highlighting this issue: https://github.com/cypress-io/cypress/issues/205

When `cy.get()` finds no element (as it did in this case because the selector was written incorrectly), an assertion about it not being being visible passes (because technically it isn't visible). But you really want the assertion to fail first when not finding the element exist in the DOM at all.

Duplicate of https://github.com/cypress-io/cypress/issues/205

**Closed by jennifer-shehane** 2020-11-04 04:18 UTC

**Comment by tzolnai** [comment] 2020-11-04 10:36
I'm not happy with your decision here. It's not about the should('not.be.visible') part, but the ignored syntax error. I'll create a different issue then where I'll use should('be.visible') in the test cases.

**Comment by tzolnai** [comment] 2020-11-04 10:48
https://github.com/cypress-io/cypress/issues/9089
