### ISSUE TITLE
Migration Helper loads endlessly

### ISSUE THREAD

**Issue by Maleckidd** [cypress-io/cypress#22461] opened 2022-06-22 21:06 UTC
### Current behavior

Hi! After update to latest version 10.2.0 (from 9.1.0) and run 'cypress open', I have clicked button 'Continue to Cypress 10', Migration Helper have been shown, but it's loading endlessly (screenshot).  There is no errors in terminal or cypress window
Here is my repo: https://github.com/Maleckidd/CypressExample-OWASPJuiceShop
![image](https://user-images.githubusercontent.com/38877513/175133370-c350ef71-7b1a-48c0-915e-2669a17e7f7f.png)

### Cypress Version

10.2.0

### Package Manager

npm

### Operating system

Mac

**Comment by lmiller1990** [comment] 2022-06-24 03:09
Thanks for the reproduction - I confirmed it's happening on linux, too. I will find out the problem and fix it.

**Comment by lmiller1990** [comment] 2022-06-24 06:12
I found the problem. The migration tool is not respecting when `pluginsFile` and `supportFile` point to directories containing `index.js`. I think `pluginsFile` and `supportFile` are supposed to point to files (thus the name) but it looks like, by Node.js default module resolution, directories with `index.js` also worked in Cypress 9.

I'm fixing the migration helper now. You can wait until the patch is merged and try again, or you can just change your `cypress.json` to point to the files directly, like this:

```json
{
   "baseUrl": "http://localhost:3000/",
   "integrationFolder": "JuiceShopTests",
   "fixturesFolder": "fixtures",
   "pluginsFile": "plugins/index.js",
   "screenshotsFolder": "screenshots",
   "supportFile": "support/index.js"
}
```

I made these changes and it works.

**Closed** 2022-06-24 14:48 UTC
Labels: stage: needs review, existing workaround, topic: installation

**Comment by Maleckidd** [comment] 2022-06-24 17:55
thx, workaround works!
