### ISSUE TITLE
Property 'get' does not exist

### ISSUE THREAD

**Issue by JulSeb42** [cypress-io/cypress#25387] opened 2023-01-06 22:56 UTC
### Current behavior

I'm trying to set up tests with Cypress inside my React / TS app. I installed the package, and when I try to set up a test it shows an error when using the `get` function:

```
Property 'get' does not exist on type 'typeof import("path/to/package")'.
```

Why does this happen? Did I install something wrong?

### Desired behavior

Being able to use the `get` function

### Test code to reproduce

```
it("displays Text component", () => {
    cy.mount(<Text tag="h1" data-testid="Hello">Hello World</Text>)
    cy.get("[data-testid='Hello']").should("contain.text", "Hello")
})
```

### Cypress Version

12.3.0

### Node version

18.12.1

### Operating System

macOS 13.0

**Comment by astone123** [comment] 2023-01-10 18:59
@JulSeb42 just to clarify, `cy.mount` _is_ working correctly, but `cy.get` is not? Are you running your tests through the Cypress UI (cypress open) or in the terminal? How is Cypress installed? Thanks

**Comment by ZachJW34** [comment] 2023-01-17 21:56
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by JulSeb42** [comment] 2023-01-17 22:03
@astone123 yes exactly, `cy.mount` but not `cypress.get`. I'm running tests through Cypress UI via Electron browser, and cypress is installed only on the project and not my computer

**Comment by nagash77** [comment] 2023-01-18 16:57
@JulSeb42 Are you able to follow the links in @ZachJW34 comment and provide a reproducible example?  Unfortunately what's in the ticket will not be enough for our internal devs to accurately and effectively diagnose the issue.

**Comment by JulSeb42** [comment] 2023-01-19 12:45
@nagash77 I created a basic repo here https://github.com/JulSeb42/cypress-demo, from what I see if I don't have the page `cypress/support/component.ts` open in my editor I get the error `Cannot find name 'cy'.`
If I import `cy` inside the test page I get `Property 'mount' does not exist on type 'CypressNpmApi'.`.
And if I import `mount` the `get` function does not exist

**Comment by ZachJW34** [comment] 2023-01-19 18:43
Looks like you are fighting some typescript types which can be frustrating, especially inside a project preconfigured with Jest. We have some documentation ([1](https://docs.cypress.io/guides/component-testing/faq#Why-isnt-TypeScript-recognizing-the-global-Cypress-objects-or-custom-cypress-commands-eg-cymount) and [2](https://docs.cypress.io/guides/component-testing/faq#How-do-I-get-TypeScript-to-recognize-Cypress-types-and-not-Jest-types)) to help get your IDE happy across both your Cypress and Jest tests.

Another option not listed in the docs but has worked for me is to create a `types.d.ts` file inside your `cypress directory` and then linking this file in your Cypress tests at the top via `/// <reference types="../cypress/types" />`. The contents of this file would look like:

```ts
/// <reference types="cypress" />

declare global {
  namespace Cypress {
    interface Chainable {
      mount: typeof import('cypress/react').mount;
    }
  }
}

export {}
```

There are many solutions since there are many different IDE setups. If a user isn't using Jest, adding `"include": ["cypress"]` to your tsconfig is normally the simplest way to get your IDE to recognize your types.

Hope this helps!

**Comment by JulSeb42** [comment] 2023-01-20 23:22
Ok I tried adding the `types.d.ts` file, still same problem. If I add a `/// <reference types="cypress" />` on the top of a test file I get `Property 'mount' does not exist on type 'cy & CyEventEmitter'.`, but the `get` one works (HOW?). I also added `cypress` in the include array in `tsconfig.json` but still the same

**Comment by ZachJW34** [comment] 2023-01-23 15:15
@JulSeb42 Try referencing `/// <reference types="../cypress/types" />`, or whatever the relative path to the newly created types file. Adding `cypress` to the `tsconfig.includes` array will give you TS intellisense for the default cypress commands but won't include the declared mount command unless you include the `./cypress` directory as well (but doing so might cause conflict with your jest tests). If you aren't utilizing jest, then this is fine.

If it would help I can fork your repo and put together a config that demonstrates a proper TS setup.

**Comment by ZachJW34** [comment] 2023-01-30 15:20
Going to close, the information and the docs should be sufficient to get the types happy on your system but please post back if you're still struggling.

**Closed as completed by ZachJW34** 2023-01-30 15:20 UTC
