### ISSUE TITLE
Unable to find and view tests in the side bar. It is quite urgent from our side. Treat this ticket as priority

### ISSUE THREAD

**Issue by priya314** [cypress-io/cypress#16356] opened 2021-05-05 22:01 UTC
<img width="1440" alt="Screenshot 2021-05-06 at 3 30 06 AM" src="https://user-images.githubusercontent.com/42987780/117215209-8abe2800-ae1b-11eb-8594-bcd9611469b7.png">

**Comment by lmiller1990** [comment] 2021-05-06 14:29
Can you please provide some more information? Are you using the component testing runner? e2e? What's your project configuration?

**Comment by jennifer-shehane** [comment] 2021-05-06 14:48
@priya314 Likely you've shrunk the lefthand sidebar to a size that is no longer visible. 

You *can* grab the left side and drag it, it's just very very tricky.

But, this will be fixed if you clear out the app data that has this saved state:

- Goto `File` -> `View App Data`
- Delete everything in here
- Close cypress and open it up again

Duplicate of https://github.com/cypress-io/cypress/issues/2132

**Closed by jennifer-shehane** 2021-05-06 14:48 UTC
Labels: stage: needs information
