### ISSUE TITLE
Getting navigated back to previous url instead of remaining on new one.

### ISSUE THREAD

**Issue by ShivaniBali** [cypress-io/cypress#1713] opened 2018-05-12 23:31 UTC
Hi All,
I am having trouble in understanding, what can I use to stay on the same page.
Instead, I am navigated back to the previous URL, rather than remaining on a new one.

below are both URL's console specifications.

```
Event:           new url
 New Url:         https://app.staging.blockport.tech/settings
 Url Updated By:  pushState
 Args:            (3) [null, "", "/settings"]

 New Url:         https://app.staging.blockport.tech/
 Url Updated By:  replaceState
 Args:            (3) [null, "", "/"]
```

```js
selectSettings: () => {
  cy.viewport(viewportSize).then(() => {
  cy.get(settingsButton).click({force: true });
  
  })
},
verifySettingsPage: () => {
  cy.viewport(viewportSize).then(() => {
  cy.get(settingsPageVerification).should('be.visible');
  //cy.url().should('eq', `${Cypress.env('host')}/settings`); ---> doesn't work 
})
},
```

Please have a look and suggest me what can be done here.

**Comment by brian-mann** [comment] 2018-05-12 23:39
Sorry, unfortunately those URL's are not accessible to us. Please provide a reproducible repo or public URL's we can look at.

**Comment by ShivaniBali** [comment] 2018-05-13 00:26
ok, meanwhile, could you please suggest me is there any command I can use to keep my focus on the new page, not on the previous one?

**Comment by Nate-Watts** [comment] 2018-05-24 18:16
I am having this problem as well. I use cy.visit() to go to a specific page, I then use cy.url().should('contain', '/#/exampleEndpoint'). The assertion passes, but then I am rerouted to a previous endpoint. It's frustrating because it does not happen all the time. It creates flaky tests. There is an event emitted called (New URL) which is fired. You can see in the screenshot that the (new url) event is emitted after the assertions are made. Why am I being redirected to this new url? Would there be code on our app's end that causes this or is it from cypress?
![image](https://user-images.githubusercontent.com/38437438/40503632-fac4a98e-5f4b-11e8-8473-0cd3ade01267.png).

**Comment by itaykotler-fundbox** [comment] 2018-06-18 07:42
@Nate-Watts, did you find a solution?

**Comment by jennifer-shehane** [comment] 2018-07-13 21:40
@Nate-Watts It's possible that it could be some logic that is not perfectly replicated in your tests from your app. I had a situation today where my routing worked correctly after logging in on my dev app, but not within my test environment I had not properly simulated the authentication well enough for the app within my tests to see me as 'authenticated', so it would reroute back to 'login'. It involved some third party integration. 

But, we would really need a reproducible example to determine the cause exactly.

**Comment by Nate-Watts** [comment] 2018-07-13 21:51
@jennifer-shehane I have actually discovered the solution to this issue. The problem is that I wasn't waiting for all of the XHR requests to finish. Not sure why, but I'm always taken to the app's landing page. Once I wait for all the requests to be made then I am able to visit other endpoints without being rerouted.

**Comment by jennifer-shehane** [comment] 2018-07-17 15:51
@Nate-Watts Awesome!

@ShivaniBali Were you able to resolve your issue?

**Comment by d0n0tdisturb** [comment] 2018-10-24 08:12
I have exactly the same issue described by Nate-Watts in the picture. After the login there are xhr requests running, and some of them will redirect to main page. My test wants to go to another page, click some navigation link, but in the mean time the new url event is fired from xhr requests that are not finished yet, and the page will redirect to landing page. My test will search for something from that another page, and it will not find because the page has been redirected.

I saw that Nate said that he discovered the solution by waiting for all xhr requests to finish, then moving to other endpoint. 

Temporarily I did that by hardcoding a cy.wait of 5 seconds after login, in order for all xhr requests to finish.
But this solution is not acceptable.

Do you have a method to wait for all xhr to finish?
I also did cy.server.route and wait for route but it didn't work.

**Comment by jennifer-shehane** [comment] 2018-11-19 22:08
@d0n0tdisturb We do not have a method to wait for 'all' requests to finish - as it is difficult to define what 'all' would be. 

The best way to do this would be to define the routes that have to respond using `cy.route()` then using `cy.wait()` to wait for each defined route. 

I am closing this issue as this seems to not be a Cypress bug.

**Closed by jennifer-shehane** 2018-11-19 22:08 UTC
Labels: stage: needs information

**Comment by jenchek** [comment] 2019-05-06 16:07
Здравствуйте, извините, что на русском, английским не сильно владею.
Так же я новичок и в Cypress!)
Проблема, как я понял выше, одна и та же, но простым ожиданием завершения всех xhr все не заканчивается.
После того как я добавляю юзера в нашу базу POST запросом, меня вместо того, чтоб перекинуть на страницу всех пользователей, кидает на страницу авторизации, и я не знаю, что с этим делать. 
![image](https://user-images.githubusercontent.com/42541466/57238058-2f40e000-7031-11e9-915e-3bed4939f922.png)
такое же повторяется и на cy.reload() и cy.go(back)
Но самое интересное, что сейчас у меня этот тест большой размещен внутри context() и разделен на много it() , и если все тесты it() объединить, т.е. чтобы они не разделялись, то в конечном результате у меня не появляется этого злосчастного  (NEW URL). 
Заранее спасибо!)

**Comment by bahmutov** [comment] 2019-05-07 13:34
@jenchek скорее всего вы неправильно сделали session cookie или jwt который апп использует для авторизации. Есть разные примеры на https://github.com/cypress-io/cypress-example-recipes#logging-in-recipes но мне интересно другое - если не использовать cy.route stub этот запрос работает как надо? Не перебрасывает на страницу /login ?

**Comment by jenchek** [comment] 2019-05-07 13:48
@bahmutov Здравствуйте, все равно перебрасывает.
Пока что я решил проблему, переместив весь тест в один it(), но все таки было бы удобнее, разделять на каждом более или менее значимом шаге.

сейчас у меня авторизация на сервисе через
`cy.request().then((resp) => {
                window.localStorage.setItem('access-token', resp.body.access_token)
                window.localStorage.setItem('refresh-token', resp.body.refresh_token)
            })`

**Comment by bahmutov** [comment] 2019-05-07 14:18
@jenchek ага супер - только надо авторизацию делать _перед каждым тестом_. Cypress чистить все перед тестом и авторизация в первом тесте уже не существует во втором! Используйте beforeEach https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__html-web-forms/cypress/integration/logging-in-html-web-form-spec.js#L140

**Comment by jenchek** [comment] 2019-05-07 14:23
@bahmutov спасибо, помогло, не знаю почему не вспомнил раньше.

**Comment by testerez** [comment] 2019-05-31 02:40
Hello @jennifer-shehane ,
We have a very similar issue that happens only on our CI. I've never been able to reproduce locally.

The scenario is very similar:
1. Navigate to a page
2. Log the user in
3. Some XHR are triggered by our app
4. We get redirected to `/` with a `(NEW URL)` log entry

Here is a screenshot took on a CI failed build:
<img width="396" alt="Screen Shot 2019-05-30 at 10 31 46 PM" src="https://user-images.githubusercontent.com/815236/58677753-36ef5e00-832b-11e9-9875-a51b1fdc608f.png">

As far as I can tell this redirect is not caused by our app. Maybe waiting for some XHR to finish would solve our issue like it did for @Nate-Watts but I don't really understand why this would be required. From what I can see it looks more like a bug in Cypress.

**Comment by jennifer-shehane** [comment] 2019-06-03 08:17
@testerez 	We'd really need a reproducible example to determine whether this is or is not a bug. There's not much we can do from the screenshot unfortunately.

**Comment by Frozenfire92** [comment] 2019-11-14 21:59
I recently ran into this as well, for context its an ember app (SPA, which modifys the history)

It seemed the fix was to wait for all the network requests to resolve before asserting the url with `cy.url().should('equal'` This has fixed the issue of not being able to carry on with your test (such as getting an element for a click) however I still see the `new url` event caused by `pushState` inconsistently.

I suspect part of the issue is `cy.url()` doesn't seem to be waiting for these events in a way that most people would expect for a SPA? And some combination of the network requests being watched is breaking that? the issue being it then reroutes to the index (and hopefully your app logic takes you to where you were / wanted to go)

Note that the pushState url event is the exact same one that is being asserted above it

![image](https://user-images.githubusercontent.com/5893112/68899367-e072b200-0707-11ea-8b89-72a4bc56730b.png)

![image](https://user-images.githubusercontent.com/5893112/68899561-537c2880-0708-11ea-974e-100166c1493e.png)

![image](https://user-images.githubusercontent.com/5893112/68899268-ad302300-0707-11ea-9ac2-3d88cb973150.png)



- If I mouse over the assertion of url the app is in the state I expect it to be
- If I mouse over the new url its from push state and I see the app in the intial state (before SPA has done any auth logic to reroute, but has proper url it should be at)
- If I mouse over the get or the click the app is in the state I expect it to be (right url / redirect from login logic)


I'll see if I can come up with a small example that reproduces this, would be good to figure it out as it is quite frustrating (as it seems to happen inconsistently, I have some runs where that new url event isn't there at all)

But it does seem to "fix" if you wait for all network requests

**Comment by natural411** [comment] 2021-01-13 23:23
Same issue, waiting about 6-8 seconds seems to work for me.  not ideal, but idk what else i could do.  If we could completely destroy the browser between each test, that would solve it for me.

**Comment by verheyenkoen** [comment] 2022-01-21 13:11
@brian-mann @jennifer-shehane I may have had the same problem as @salty-blue-mango [above](#issuecomment-391810942) and found the issue at hand. I used the alias method `.as()` chained to a `cy.contains()` and expected it to work just like with `cy.get()`, however that caused the `cy.visit()` from the top of the test to weirdly be re-executed totally out of order after fetching the alias with `cy.get('@...')`. 

So the test being:

![image](https://user-images.githubusercontent.com/599538/150531810-d450ba3b-4dfa-4e7b-8dd1-94951aa2046e.png)

Gave this result in command log:

![image](https://user-images.githubusercontent.com/599538/150531861-5795c090-d57e-4df6-93ef-47dcf0e1148e.png)

... where the visit in log line 13 should not be there.

So there is probably no fixable issue here as I checked and at no point in the docs it is stated that you can alias the result of a `cy.contains(...)` construct (probably very different from `cy.get` under the hood), however I would suggest adding this to the docs in the "Incorrect usage" section of `cy.as()`.

Published a reproducible repo here: https://github.com/verheyenkoen/cypress-issue-1713
