### ISSUE TITLE
Cypress doesn't open chrome 

### ISSUE THREAD

**Issue by bilalSaidi** [cypress-io/cypress#25688] opened 2023-02-02 17:05 UTC
### Current behavior

after opening the window choosing chrome v109 
![image](https://user-images.githubusercontent.com/42448053/216392362-a2e72502-c354-4882-a2c8-dfd5291ae449.png)
and open broswer page like this 
![image](https://user-images.githubusercontent.com/42448053/216392550-dcfaf9ff-805d-4408-993b-c12c46c81c0d.png)

### Test code to reproduce

no code 

### Cypress Version

12.5.0

### Node version

16.15.0

### Operating System

windows 10

**Comment by nagash77** [comment] 2023-02-03 19:13
Hi @bilalSaidi , it appears from your screenshot that the browser is opened but it is not connecting.  Unfortunately, right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2023-02-10 19:00
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-02-10 19:00 UTC
