### ISSUE TITLE
Add option to remove browser cookies from cy.request

### ISSUE THREAD

**Issue by ashblox** [cypress-io/cypress#9013] opened 2020-10-28 21:11 UTC
### What would you like?

All requests in Cypress are currently sent "as if through the browser," meaning that all your browser cookies get copied into your request. This makes sense for the default behavior, but if I think you should be able to specify if you don't want them included. Perhaps `cy.request` could take an option `"includeCookies": "false"` . 

(I tried passing `Authorization: { cookie: "" }` and `Authorization: { cookie: null }` but neither had any effect.)

### Why is this needed?

Consider an application that supports both "read-only" users and "can make edits" users. Ours relies on message queueing and websockets, so that the view will update in realtime. What I'd like to do is test the "read-only" user functionality by POST-ing using a user token that has both permissions. I am currently getting an unauthorized error on my HTTP call because the session cookie associated with my logged in user is being passed in the request. The service accepts both Bearer auth and cookie auth, but in this case I'd like to send *only* the Bearer token.

My current workaround is to pull back my cookie values, clear them, make the request, and then set them again 😕

**Comment by cameron-martin** [comment] 2021-02-15 11:54
Duplicate of https://github.com/cypress-io/cypress/issues/8909

**Comment by jennifer-shehane** [comment] 2021-05-05 20:11
Duplicate of https://github.com/cypress-io/cypress/issues/8909

**Closed by jennifer-shehane** 2021-05-05 20:11 UTC
Labels: topic: cookies :cookie:, type: enhancement
