### ISSUE TITLE
Cypress rarely doesn't type a space in a string

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress#4811] opened 2019-07-25 07:36 UTC
### Current behavior:

Random flake which is frustrating. Out of 10+ runs this happens once.

It is meant to type `Foo Bar` (space) but Cypress types `FooBar`.

![image](https://user-images.githubusercontent.com/677167/61854680-8464f300-aeb6-11e9-8e84-d63cd7138ec8.png)

You can see it above.

And it then fails when the test can't find `Foo Bar` because Cypress typed `FooBar`.

![image](https://user-images.githubusercontent.com/677167/61854741-9e9ed100-aeb6-11e9-98e1-f1406ac1b8cb.png)

We also see instances where it misses letters. I.e. `ew Test Endpoint` instead of `New Test Endpoint` in different areas of the test suite. See:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/677167/61854959-179e2880-aeb7-11e9-88ee-56dd25a1938a.png">

### Desired behavior:

It to type consistently.

### Steps to reproduce: (app code and test code)

The spec:

```js
  it('should persist a report name change', () => {
    analyticsEdit.name().clear().type('Foo Bar');

    analyticsEdit.done().click().waitForAPI('analytics-report');

    layout.clearToasts();

    analytics.reportDropdownOptions().contains('Foo Bar');
  });
```

### Versions

Cypress 3.4.0
Cypress Dockerfile with Electron.

**Comment by jennifer-shehane** [comment] 2019-07-25 08:10
Unfortunately we'll have to close this issue since the example provided is not reproducible on our end. I don't doubt that this is happening, but we need a way to produce the bug on our end to move forward.

This issue may be unique to the way your input listens to events, so any insights in the html or javascript around your search input may be helpful. 

Can you also try playing with the [`delay` option](https://on.cypress.io/type#Arguments) - which controls the time in between each keypress. See if this changes anything.

**Comment by philjones88** [comment] 2019-07-25 08:38
We use Angular 8 and Bootstrap 3.

Very helpful considering the tag line `Fast, easy and reliable testing for anything that runs in a browser.`

I could spend ages writing a sample but this is a private commercial project where we've paid for the dashboard.

**Comment by jennifer-shehane** [comment] 2019-07-25 09:19
Sorry, we have to close the issue then, as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-25 09:19 UTC
Labels: stage: needs information

**Comment by robinelvin** [comment] 2022-05-13 08:56
I have the missing space issue which is consistently happening with the app I am testing. I have tried adding waits and delays to the `type` call and it still doesn't work. I have added a delay of 1000 to the type and I can see the input ignoring the just spaces and type the rest of the input perfectly. I have even added multiple spaces and this ignores them all. Alphanumeric characters work fine. Typing manually works so this isn't an issue with the app.

I have tried 9.6.0 and 9.6.1 and both versions have the same issue.

![image](https://user-images.githubusercontent.com/1187032/168247914-45ea601f-7e58-47b3-91ef-06d82563b89e.png)

![image](https://user-images.githubusercontent.com/1187032/168248021-4bc27831-b3a6-4bf2-ac5d-7dd9b01d351a.png)

I understand you would like a reproducible example in order to debug this but I suspect that any contrived code won't exhibit this problem and the project I am working on is confidential. Since this issue seems to crop up for many users I would expect more effort into tracking this down rather than closing issues because you don't have a test case. I can check things at my end if required.
