### ISSUE TITLE
Cypress dashboard showing duplicate tags

### ISSUE THREAD

**Issue by luciusyeah** [cypress-io/cypress#18019] opened 2021-09-08 12:12 UTC
### Current behavior

Problem:
As of yesterday, the Cypress Dashboard started showing multiple tags (one per job in Azure). See screenshot:
![image](https://user-images.githubusercontent.com/7584917/132505284-936d2a4f-7513-4a47-9f63-85c2cec51989.png)

Context:
We run our e2e's from a build-pipeline in Azure DevOps on a Ubuntu machine, using a docker image. And no code changes were done to the build-pipeline for over a week now. 

This is how we execute our tests in Azure DevOps:

```
docker run -e "env var1" \
-e env var2,etc. \
-v $(Build.ArtifactStagingDirectory)/${{ job.name }}:/cypress/reports/ 
--entrypoint "cypress" 
--ipc=host dockerembrace.azurecr.io/client-web-e2e:latest run 
--browser chrome 
--headless 
--ci-build-id $(Build.BuildId) 
--group ${{ job.displayName }} 
**--tag "daily-e2e-regression,nightly"** 
--record 
--key $(CYPRESS_DASHBOARD_KEY) 
--spec '$(DefaultTestLocation)/${{ job.name }}/*.feature' 
```
(In order to rule out issues with encoding in YAML, I hardcoded the tags and placed quotes around them)

### Desired behavior

In this situation the Cypress Dashboard should only show 2 tags instead of adding tags per YAML-job.

### Test code to reproduce

This section isn't relevant as the test itself isn't failing, its just that the Cypress Dashboard shows additional tags, since yesterday. 

Ofc I could create a separate repos, but then i would also need to give you guys access to the Cypress Dashboard and Azure DevOps. 

We did not change anything on our end regarding the YAML. As of yesterday it just started showing additional tags => each run adds additional tags. 

So i'm just curious:
Did you guys/gals change some logic regarding tagging around yesterday on your end? 

### Cypress Version

6.4.0

**Comment by jennifer-shehane** [comment] 2021-09-08 13:31
Duplicate of https://github.com/cypress-io/cypress/issues/18016

**Closed by jennifer-shehane** 2021-09-08 13:31 UTC
