### ISSUE TITLE
Low quality screenshots in headless mode

### ISSUE THREAD

**Issue by avivshafir** [cypress-io/cypress#1445] opened 2018-03-12 16:25 UTC
### Is this a Feature or Bug?
Feature

### Current behavior:
Low resolution screenshots in headless mode

### Desired behavior:
Ability to control screenshot quality

### How to reproduce:
cypress run
cypress run --browser chrome

### Additional Info (images, stack traces, etc)
when running using headless electron or chrome
![image](https://user-images.githubusercontent.com/6135443/37295960-3b437f0c-2622-11e8-8763-989973d7cd36.png)

VS when opening cypress with chrome
![image](https://user-images.githubusercontent.com/6135443/37295933-29687576-2622-11e8-8c2d-003ce989e423.png)

Is there an option to make the image qualities the similar in all modes of running?
The current behaviour causes image screenshot diffing tools to fail.

- Operating System: 
Linux
- Cypress Version:
2.1.0
- Browser Version:

Thanks

**Comment by brian-mann** [comment] 2018-03-12 16:41
Is the root cause of this problem this issue: https://github.com/cypress-io/cypress/issues/1309

There's definitely no reason that the screenshot quality would be low - other than if your app is scaled and tiny.

My guess is that you've reduced the size of the app and then are running Cypress headlessly. If you expand the size (as per that issue) then it won't be so fuzzy.

**Comment by avivshafir** [comment] 2018-03-12 18:59
@brian-mann it looks like the issue described in #1309 is the similar.
But I still do not understand is this that i also get low quality images when running cypress in headless mode inside a docker container I created from the base _cypress/browsers:chrome64_ image.
And also when each developer will get different image diffing results depending on the reporter width option is sort of a problem for me.
Is there a way to solve this in a consistent way? (configurable or fixed reporter width perhaps?)

**Comment by jennifer-shehane** [comment] 2019-09-25 19:22
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-09-25 19:22 UTC
Labels: stage: proposal 💡, topic: screenshots 📸, type: unexpected behavior

**Comment by magjac** [comment] 2020-02-04 18:33
I have the same issue. You can see it [here](https://dashboard.cypress.io/projects/8wm34o/runs/111/failures/1c73563a-58be-414b-8afb-bc242ed877fe). The video is just as bad.

Presumably it's because it is scaled down to 35%. How can I avoid that?

**Comment by Pirozek** [comment] 2020-02-06 09:09
I am having exactly the same problem. Viewport is OK, but the screenshost are 800x600 and the scaling of UI makes screenshots unusable. Can be reproduced by opening any page in cypress and screenshoting it, while using headles chrome.

**Comment by jennifer-shehane** [comment] 2020-03-17 14:59
@Pirozek you were likely facing this issue which has been resolved. https://github.com/cypress-io/cypress/issues/6210
