### ISSUE TITLE
'.should' assertion is not working properly in currency cases

### ISSUE THREAD

**Issue by khashaba** [cypress-io/cypress#9530] opened 2020-12-04 12:59 UTC
I am trying to assert that a span has the value "0,00 €" but it seems like it doesn't work properly
`    cy.get(".shipping_amount").should("have.text","0,00 €");`

![image](https://user-images.githubusercontent.com/12282832/101166465-ff105780-3640-11eb-8e76-8e72cb256c79.png)

**Comment by bahmutov** [comment] 2020-12-04 13:05
Could you add a screenshot of the elements panel from the devtools around this element? There might be some white space there that is not showing in the assertion message

**Comment by khashaba** [comment] 2020-12-06 19:33
nope @bahmutov  there is only one space between the 0,00 and euro sign as you see in the assertion! 

![image](https://user-images.githubusercontent.com/12282832/101290119-fec2b880-3808-11eb-8411-8b051bf09ec7.png)

also I tried to replace the space with 0,00&nbsp€
![image](https://user-images.githubusercontent.com/12282832/101290399-a8ef1000-380a-11eb-8232-598d175e98ed.png)

**Comment by jennifer-shehane** [comment] 2020-12-07 08:09
Duplicate of https://github.com/cypress-io/cypress/issues/9531

**Closed by jennifer-shehane** 2020-12-07 08:09 UTC

**Comment by jennifer-shehane** [comment] 2020-12-07 08:20
Wrote in the other issue, but here's how you could write this:

```js
it('text', () => {
  cy.get('.shipping_amount').contains('0,00 €')

  cy.get('.shipping_amount').invoke('text').then((text) => {
    // remove the space char
    expect(text.replace(/\u00a0/g, ' ')).equal('0,00 €')
  })

  cy.get('.shipping_amount').invoke('text')
  // remove the space char
  .invoke('replace', /\u00a0/g, ' ')
  .should('eq', '0,00 €')
})
```

**Comment by bahmutov** [comment] 2020-12-07 12:29
We could probably document this edge case in our docs to make finding it easier
