### ISSUE TITLE
Unexpected Error: Your configFile threw an error from: cypress.config.js

### ISSUE THREAD

**Issue by bruno333** [cypress-io/cypress#23935] opened 2022-09-22 10:21 UTC
### Current behavior

I was installing the latest cypress in my angular apps (mono repo using nx).
E2e test are working but component testing is throwing me this error and I can't find where to specify the path for the tsConfig file

### Test code to reproduce

Error
Your configFile threw an error from: cypress.config.ts

We stopped running your tests because your config file crashed.

..\..\..\node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:51:15
  49 |     const configResult = readConfiguration(tsConfigFullPath);
  50 |     if (configResult.errors && configResult.errors.length) {
> 51 |         throw new Error(formatDiagnostics(configResult.errors));
     |               ^
  52 |     }
  53 |     return configResult;
  54 | }
  55 | exports.readTsconfig = readTsconfig;
[Stack trace](http://localhost:56001/__launchpad/index.html#)
Error: error TS5012: Cannot read file 'pathto.../tsconfig.app.json': ENOENT: no such file or directory, open 'pathto.../tsconfig.app.json'.

    at readTsconfig (node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:51:15)
    at async generateWebpackConfig (node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:48:22)
    at async generateBrowserWebpackConfigFromContext (node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:125:20)
    at async getAngularCliWebpackConfig (AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:137:24)
    at async angularHandler (AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:142:27)
    at async getPreset (AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:76:20)
    at async Function.devServer.create (AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:93:61)
    at async AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.

### Cypress Version

10.8.0

### Node version

v16.13.1

### Operating System

Windows 10 Pro

### Other

Angular version: 14.2.0
Nrwl version: 14.7.8

**Comment by lmiller1990** [comment] 2022-09-22 10:31
Potentially related (NX and Angular) https://github.com/cypress-io/cypress/issues/23673

**Comment by ZachJW34** [comment] 2022-09-26 16:46
I generated and ran an nx-angular repo with:
- `npx create-nx-workspace@latest nx-angular --preset angular --appName my-app --nxCloud false --style css`
- `cd ./nx-angular`
- `nx g @nrwl/angular:cypress-component-configuration --project my-app --generateTests`
- `nx component-test my-app --watch`

Everything worked fine on my end. Are you up to date with the latest NX? If that is not the issue, could you provide a minimal reproduction of the issue?

**Comment by bruno333** [comment] 2022-09-28 07:05
Hi Zach,
I do have the latest version of NX installed.
What info would you need for further investigation ? 
But Maybe I only missed where to specify the path of the tsConfig file for component testing?

**Comment by lmiller1990** [comment] 2022-09-29 22:17
Can you provide a minimal reproduction @bruno333? That would be the easiest way to get some momentum on this issue.

**Comment by astone123** [comment] 2022-10-06 14:07
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as completed by astone123** 2022-10-06 14:07 UTC

**Comment by Josh68** [comment] 2023-01-30 18:49
@astone123, I am **_intermittently_** getting this type of error on a newly-upgraded repo, migrating from v9 to v12 (latest).

This is a CRA project (no Angular) and we develop on Mac OS (may have something to do with it?). The error may appear on both headed and headless runs, and it's simply a Node EACCES error (nvm-installed Node versions from 16 up to 18 LTS):

```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Error: spawn /Users/joshuaadamschneider/.nvm/versions/node/v18.12.1/bin/node EACCES
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

One thing that's catching my attention is that my config is a TS file (`cypress.config.ts`), and the error shows an issue with `cypress.config.js`.  Almost makes me think the TS compiler has a lock on the file at the time, or something like that.

I will open another issue if that's best, but wonder if you or anyone else has thoughts about what's going on'?

**Comment by lmiller1990** [comment] 2023-01-31 00:24
Hm interesting re:

> config is a TS file (cypress.config.ts), and the error shows an issue with cypress.config.js

Are you able to repro this in a minimal repository? The main blocker with fixing this is creating a minimal reproduction for debugging.

You can also run with `DEBUG=cypress:* npx cypress open...`  and it'll print lots of logs, which you can share here.

**Comment by Josh68** [comment] 2023-01-31 00:40
Thank, @lmiller1990. Let me see what i get with debugging. It's true that ours is a large, containerized application, so I'm not whether a minimal repo would reproduce similar results. I might try cloning one of the example projects and converting the config to TS (none of them I've looked at, including TS-specific ones, have a `cypress.config.ts`. At the same time, docs clearly show this is an option. The thing that really gets me is the inconsistency. Often works, sometimes crashes.

**Comment by lmiller1990** [comment] 2023-01-31 03:57
How about some logs with `DEBUG=cypress:* npx cypress open...`? That should be easier (not sure how useful it'll be, but worth trying).

**Comment by Josh68** [comment] 2023-01-31 17:43
Thanks, @lmiller1990. So far I haven't deciphered what may be up here. The stack trace is still the same, but there's a lot of context around it. [cypress_debug.txt.zip](https://github.com/cypress-io/cypress/files/10549312/cypress_debug.txt.zip)

**Comment by Josh68** [comment] 2023-01-31 17:49
Here's what it looks like when I click "Try again" in the runner UI, and it succeeds (this is after the failure I collected above)

```cypress:lifecycle:child:run_require_async_child:46182 loaded config file /Users/joshuaadamschneider/Repos/coverage-tools-frontend/cypress.config.ts +2s
  cypress:lifecycle:ProjectConfigIpc loadConfig:reply +3s
  cypress:lifecycle:ProjectConfigManager config is loaded for file /Users/joshuaadamschneider/Repos/coverage-tools-frontend/cypress.config.ts null +11m
  cypress:config:browser validating configuration {
  chromeWebSecurity: false,
  defaultCommandTimeout: 6000,
  pageLoadTimeout: 8000,
  screenshotsFolder: './cypress/snapshots/actual',
  env: {
    apiUrl: '',
    failSilently: false,
    SNAPSHOT_BASE_DIRECTORY: './cypress/snapshots/base',
    SNAPSHOT_DIFF_DIRECTORY: './cypress/snapshots/diff',
    INTEGRATION_FOLDER: 'cypress/integration/',
    ALWAYS_GENERATE_DIFF: false,
    ALLOW_VISUAL_REGRESSION_TO_FAIL: true,
    trashAssetsBeforeRuns: true,
    video: false
  },
  e2e: {
    baseUrl: 'https://localhost/#',
    specPattern: './cypress/integration/**/*.spec.{js,jsx,ts,tsx}',
    supportFile: './cypress/support/e2e.ts',
    setupNodeEvents: '[Function setupNodeEvents]'
  }
} +3s
```

**Comment by Josh68** [comment] 2023-01-31 17:59
Could this be relevant?

```
cypress:lifecycle:ProjectConfigIpc found typescript in /Users/joshuaadamschneider/Repos/coverage-tools-frontend +3ms
  cypress:lifecycle:ProjectConfigIpc using cjs with --require /Users/joshuaadamschneider/Library/Caches/Cypress/12.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/register_ts_node.js +0ms
```
My `cypress.config.ts` is not written in CJS. It's ESM. But again, it loads more than half the time. I could be interpreting this wrong, though.

**Comment by Josh68** [comment] 2023-01-31 19:16
Turns out there is at least [one official recipe](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__add-custom-command-ts/cypress.config.ts) with a `cypress.config.ts` and it's ESM, too.

However, I just realized why I may have avoided trying this earlier in my upgrade process. In my main `tsconfig`, `rootDir` is `/src`, the `include` is set to `./src/**/*`, and the config is above that directory. I can't `include` the config as a single file to be compiled because of where it is. I wonder if I need to turn it back into a plain JS file unless I can figure out another structure. I've seen a few examples in the wild where the config is inside the `/cypress` folder, but it seems that's not the recommended place to have it (don't even know if it would work).

**Comment by Josh68** [comment] 2023-01-31 23:12
OK, interesting. When I change my config to JS, I get this error on the beginning of a headless run.

```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: spawn /Users/joshuaadamschneider/Library/Caches/Cypress/12.4.1/Cypress.app/Contents/Resources/app/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg EACCES
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
spawn /Users/joshuaadamschneider/Library/Caches/Cypress/12.4.1/Cypress.app/Contents/Resources/app/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg EACCES
Error: spawn /Users/joshuaadamschneider/Library/Caches/Cypress/12.4.1/Cypress.app/Contents/Resources/app/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg EACCES
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
```

**Comment by lmiller1990** [comment] 2023-02-01 23:34
That looks like a permissions error - EACCES. I think there have been a few of these on Mac OS Ventura - did it just happen after you upgraded? You may need to give your terminal extra permissions?

There's a few issues around related to Mac OS Ventura - I did a basic filter https://github.com/cypress-io/cypress/issues?q=is%3Aissue++ventura++macos might be useful.

(Could be unrelated, stab in the dark).

**Comment by Josh68** [comment] 2023-02-02 05:45
Thanks, @lmiller1990. Yes, I do think this may be a Mac OS thing, but still not quite sure. I've also tried running both zsh and bash, and even running tests as sudo. I had to back that out, because it ended up creating snapshot assets as root that I then had to go change permissions on in order to run again non-root.

The thing that still gets me is how it's inconsistent. Obviously, if it always happened, it would be a deal breaker, and I have yet to see it happen in CI, which is Linux. That tells me you may be right about it being an OS thing. I'll look at the issues you site and possible workarounds. Appreciate the help.
