### ISSUE TITLE
Couldn't determine Mocha version

### ISSUE THREAD

**Issue by wojtek1150** [cypress-io/cypress#9439] opened 2020-12-03 09:52 UTC
### Current behavior

```
Couldn't determine Mocha version
```
According to documentation: https://docs.cypress.io/guides/references/bundled-tools.html#Mocha mocha should be bundled. There was a similar issue before: https://github.com/cypress-io/cypress/issues/4602

### More details
Here is my dependency list
```
    "@types/lodash": "4.14.165",
    "@types/mongodb": "3.5.34",
    "@types/numeral": "0.0.28",
    "cypress": "6.0.1",
    "cypress-file-upload": "4.1.1",
    "cypress-multi-reporters": "1.4.0",
    "lodash": "4.17.20",
    "mocha-junit-reporter": "2.0.0",
    "moment": "2.29.1",
    "moment-business-days-diff": "1.0.2",
    "mongodb": "3.6.1",
    "numeral": "2.0.6",
    "tslint": "6.1.3",
    "tslint-consistent-codestyle": "^1.16.0",
    "tslint-plugin-cypress": "^1.0.4",
    "typescript": "4.1.2"
```

To fix this issue I just installed mocha `"mocha": "8.2.1"` but if it's bundled it should be required.
In lock file I don't see mocha, see below:
```
"cypress": {
      "version": "6.0.1",
      "resolved": "https://registry.npmjs.org/cypress/-/cypress-6.0.1.tgz",
      "integrity": "sha512-3xtQZ0YM65soLgKQUgn2wg2IbWsM6A2yBg6L4RF31mZHr5LNKdO2/9sgiwxEVMKu2C2m6+IQ75zHP41kZP5rPg==",
      "dev": true,
      "requires": {
        "@cypress/listr-verbose-renderer": "^0.4.1",
        "@cypress/request": "^2.88.5",
        "@cypress/xvfb": "^1.2.4",
        "@types/sinonjs__fake-timers": "^6.0.1",
        "@types/sizzle": "^2.3.2",
        "arch": "^2.1.2",
        "blob-util": "2.0.2",
        "bluebird": "^3.7.2",
        "cachedir": "^2.3.0",
        "chalk": "^4.1.0",
        "check-more-types": "^2.24.0",
        "cli-table3": "~0.6.0",
        "commander": "^5.1.0",
        "common-tags": "^1.8.0",
        "debug": "^4.1.1",
        "eventemitter2": "^6.4.2",
        "execa": "^4.0.2",
        "executable": "^4.1.1",
        "extract-zip": "^1.7.0",
        "fs-extra": "^9.0.1",
        "getos": "^3.2.1",
        "is-ci": "^2.0.0",
        "is-installed-globally": "^0.3.2",
        "lazy-ass": "^1.6.0",
        "listr": "^0.14.3",
        "lodash": "^4.17.19",
        "log-symbols": "^4.0.0",
        "minimist": "^1.2.5",
        "moment": "^2.27.0",
        "ospath": "^1.2.2",
        "pretty-bytes": "^5.4.1",
        "ramda": "~0.26.1",
        "request-progress": "^3.0.0",
        "supports-color": "^7.2.0",
        "tmp": "~0.2.1",
        "untildify": "^4.0.0",
        "url": "^0.11.0",
        "yauzl": "^2.10.0"
      }
    },
``` 

### Versions
6.0.0, 6.0.1

**Comment by jennifer-shehane** [comment] 2020-12-04 08:33
You should never need to download `mocha` with Cypress. Previously this was an issue with mocha-junit-reporter. I'm not able reproduce this solely by having the dependencies installed and running cypress.

- What are you doing when this error is printed? `cypress run`? `cypress open`?
- Can you include your plugins file and support file also?

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by wojtek1150** [comment] 2020-12-04 11:08
During the `cypress run` command. You have to setup mocha reporter, 
```
{
  "reporterEnabled": "spec, mocha-junit-reporter",
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "./report/junit/xml-result-[hash].xml",
    "outputs": true,
    "attachments": true,
    "toConsole": false
  }
}
```
I don't have anything in plugins and support file, just reset database task and simple command for login/logout. But without anything still same so just omitted them. To reproduce just prepared clean cypress install with reporter set. Here is my cypress file
```
{
  "chromeWebSecurity": false,
  "video": false,
  "baseUrl": "http://localhost:4200",
  "env": {
    "programName": "",
    "mongoUrl": "mongodb://localhost:27017"
  },
  "screenshotsFolder" : "./report/screenshots",
  "videosFolder": "./report/videos",
  "viewportWidth": 1920,
  "viewportHeight": 1080,
  "defaultCommandTimeout": 10000,
  "projectId": "xxxxx",
  "requestTimeout": 10000,
  "reporter": "./node_modules/cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporter-config.json"
  }
}
```

**Comment by sandra-ouadghiri** [comment] 2021-02-19 11:21
Also producing in 6.3 + "mocha-junit-reporter": "^2.0.0" (via cypress-multi-reporters in my case, but not sure it matter)
Appeared when I added the custom reporter. It looks very very similar to https://github.com/cypress-io/cypress/issues/4602. At that time, @gcirone produced [a fix in the reporter](https://github.com/michaelleeallen/mocha-junit-reporter/pull/88). To see if that's the same root cause/same fix situation or a different bug just leading to the same behaviour.

**Comment by justinmorrow** [comment] 2021-02-22 04:19
@wojtek1150 Are you working in a monorepo maybe? I only ask cause I am (with yarn workspaces), and I'm running into the same issue. My current theory is that it's something to do with...
1. running cypress within a subfolder instead of the project-root. For me, this subfolder has its own `package.json` and `node_modules`, in addition to the project root's at `../node_modules` and `../package.json`,
2. and `cypress` (and deps) being hoisted to the project-root `../node_modules`.

I haven't looked at the patched code @sandra-ouadghiri shared, but if the `mocha-junit-reporter` is using npm/npx to resolve the mocha version then I'm guessing that the reporter can't find mocha at all: it's looking in the wrong places with tools that don't know how to find hoisted workspace packages. 

I'll post a followup with my environment+project details when I've got time, probably tomorrow. Or a solution, if I find one for myself. Going to work on this a little tonight.

**Comment by sandra-ouadghiri** [comment] 2021-02-22 17:58
@justinmorrow > Indeed, it's a monorepo, with cypress being under a dedicated folder. So (root/)micro-service-A/package.json and (root/)test-folder/package.json (including the cypress dependencies and the rest).

**Comment by wojtek1150** [comment] 2021-02-23 07:40
@justinmorrow yea, monorepo. But I have only root package.json

**Comment by jluttrell** [comment] 2021-05-12 17:33
@justinmorrow same issue here, also with monorepo with nested `package.json` for cypress. Has anyone figured out a solution/workaround? It's failing my CI although locally the tests continue to run despite the `Couldn't determine Mocha version`

"cypress": "7.3.0"
"mocha-junit-reporter": "2.0.0"
"cypress-multi-reporters": "1.5.0"

**Comment by jluttrell** [comment] 2021-05-12 18:58
Couple things to add:
* `Couldn't determine Mocha version` first gets printed from [cypress-multi-reporters](https://github.com/YOU54F/cypress-multi-reporters/blob/643d899d209ebbd70968b3003f8ae78057e99c4b/lib/MultiReporters.js#L36) and then [mocha-junit-reporter](https://github.com/michaelleeallen/mocha-junit-reporter/blob/88388ee4f8a63eb51e76b9122fc5c00fa1282aa7/index.js#L32). Both use `require.resolve('mocha')` which fails.
* I don't see `mocha` in `root/node_modules` nor the `nested/node_modules`
* Verified explicitly adding `mocha` to the `nested/package.json` resolves the warning (as stated in the original issue description), adding to `root/package.json` does not
* My relevant contents of cypress.json
```json
{
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "reporterEnabled": "spec, mocha-junit-reporter",
    "mochaJunitReporterReporterOptions": {
      "mochaFile": "cypress/results/results-[hash].xml"
    }
  }
}
```

**Comment by jluttrell** [comment] 2021-05-12 21:36
@jennifer-shehane 
> Can you provide a reproducible example?

Here is a repo with a reproducible example:
https://github.com/jluttrell/cypress-mocha-version-warning-repro

**Comment by san-ouadghiri** [comment] 2021-08-05 11:17
@jennifer-shehane so maybe, with all the info we added, including @jluttrell last post, the 'needs information' label can be remove? I fear this prevent this ticket from being treated 😢.

**Comment by stychu** [comment] 2021-08-30 11:52
+++

I'm also getting this warning with this setup

```
"dependencies": {
    "cypress": "8.3.1",
    "cypress-fail-fast": "3.1.1",
    "cypress-multi-reporters": "1.5.0",
    "del": "6.0.0",
    "lodash.some": "4.6.0",
    "mocha-junit-reporter": "2.0.0",
    "mochawesome": "6.2.2",
    "mochawesome-merge": "4.2.0",
    "mochawesome-report-generator": "5.2.0",
    "typescript": "4.3.5"
  }
  ```
  ```
  {
  "baseUrl": "xxxx",
  "chromeWebSecurity": false,
  "screenshotOnRunFailure": false,
  "videoUploadOnPasses": false,
  "defaultCommandTimeout": 10000,
  "fixturesFolder": false,
  "integrationFolder": "cypress/tests",
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "reporterEnabled": "mochawesome, mocha-junit-reporter",
    "mochawesomeReporterOptions": {
      "reportDir": "cypress/reports/mocha",
      "overwrite": false,
      "html": false,
      "json": true
    },
    "mochaJunitReporterReporterOptions": {
      "mochaFile": "cypress/reports/results-[hash].xml"
    }
  }
}

```

**Comment by MaaikeFox** [comment] 2021-09-27 16:35
I also have this issue
A mono repo with Cypress on a sub folder, but one package.json under the root

```
"devDependencies": {
    "cypress": "^8.3.1",
    "junit-report-merger": "^3.0.2",
    "mocha-junit-reporter": "^2.0.0",
    "typescript": "^4.4.2"
  },
```

cypress.json:
```
{
    "reporter": "mocha-junit-reporter",
    "reporterOptions": {
        "configFile" : "reporter-config.json"
        },
}
```

reporter-config.json:
```
{
    "reporterEnabled": "mocha-junit-reporter",
    "reporterOptions": {
      "testsuitesTitle": true,
      "includePending": true,
      "mochaFile" : "./reports/test-results.[hash].xml"
    }
  }
```

**Comment by Katona** [comment] 2021-10-14 14:33
I have the same issue, I don't have monorepo, yet the error appears. The root cause is `require("mocha")` in the reporter fails because `mocha` can not be found in the `node_modules`. Using `"cypress": "^8.3.0"`.

**Comment by DebraBurnett** [comment] 2021-10-20 22:03
I'm also getting the issue:

package.json file:

`  "devDependencies": {
    "cypress": "^8.5.0",
    "cypress-audit": "^1.1.0",
    "cypress-multi-reporters": "^1.5.0",
    "del": "^6.0.0",
    "junit-report-merger": "^3.0.2",
    "mocha-junit-reporter": "^2.0.2",
    "mochawesome": "^6.3.1",
    "mochawesome-merge": "^4.2.0",
    "rimraf": "^3.0.2",
    "typescript": "^4.4.3"
  },
  "dependencies": {
    "mkdirp": "^1.0.4"
  }`
  
  Portion of Cypress.json file:
  
  `    "defaultCommandTimeout": 20000,
    "pageLoadTimeout": 90000,
    "reporter": "cypress-multi-reporters",
    "reporterOptions": {
      "reporterEnabled": "mochawesome, mocha-junit-reporter",
      "mochawesomeReporterOptions": {
        "reportDir": "cypress/reports/mochawesome",
        "quite": true,
        "overwrite": false,
        "html": false,
        "json": true
      },
      "mochaJunitReporterReporterOptions": {
        "mochaFile": "cypress/test-results/results-[hash].xml",
        "toConsole": true,
        "attachments": true
      }
    },
    "videoUploadOnPasses": false,
    "viewportWidth": 1200,
    "viewportHeight": 800,
    "retries": {
        "runMode": 3,
        "openMode": 3
    }`

**Comment by lmiller1990** [comment] 2023-03-15 05:44
The problem is we ship `mocha` as part of the Cypress App binary, which is not installed in `node_modules`. That only contains the CLI tool, which launches the Cypress app (which includes all the required modules for Cypress, like `mocha`).

The `mocha-junit-reporter` tries to do `require('mocha')` - which looks at your project's `node_modules` - which does not contain `mocha`. It logs a warning - that is here: https://github.com/michaelleeallen/mocha-junit-reporter/blob/4b17772f8da33d580fafa4d124e5c11142a70c1f/index.js#L32.

There isn't anything we can reasonable do about this warning in the Cypress code base - other than add specific code to silence a specific warning from a third party module, which I don't think makes much sense.

The warning shouldn't prevent the reporter from working. The only way to silence this warning when using this reporter would be a PR to the `mocha-junit-reporter` repository either removing the warning, or adding an option to silence it. 

I am going to close this, since there isn't any actionable work for us to do in Cypress regarding this warning.

**Closed by lmiller1990** 2023-03-15 05:44 UTC
Labels: stage: needs information

**Comment by vladkasianenko** [comment] 2024-11-15 08:48
Still have the same issue, Cypress version: 13.15.0
![image](https://github.com/user-attachments/assets/533f0039-7896-4ee8-ab6d-8f6ffb3dbd98)
