### ISSUE TITLE
Cypress open works, but cypress run throws ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by mm-dsibinski** [cypress-io/cypress#21654] opened 2022-05-27 10:40 UTC
### Current behavior

I'm using Cypress 9.7.0 and trying to run my tests.
If I use `npx cypress open` and run them in Electron or Chrome, everything works great.

However, if I run exactly the same tests with `npx cypress run` (using defaults, so Electron 100 headless, no other configuration, params etc.), it gives the following error for the first test:

```
CypressError: `cy.visit()` failed trying to load:

 http://127.0.0.1:56635/

 We attempted to make an http request to this URL but the request failed without a response.

 We received this error at the network level:

   > Error: ESOCKETTIMEDOUT

 Common situations why this would fail:
   - you don't have internet access
   - you forgot to run / boot your web server
   - your web server isn't accessible
   - you have weird network configuration settings on your computer
       at http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:159325:82
       at visitFailedByErr (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:158675:12)
       at http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:159324:11
       at tryCatcher (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:13022:23)
       at Promise._settlePromiseFromHandler (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:10957:31)
       at Promise._settlePromise (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:11014:18)
       at Promise._settlePromise0 (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:11059:10)
       at Promise._settlePromises (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:11135:18)
       at _drainQueueStep (http://127.0.0.1:56635/__cypress/runner/cypress_runner.js:7729:12)
```

Opening the url of course works in web browsers directly without using cypress.

### Desired behavior

`cypress run` and `cypress open` behaves the same way.

What could be the reason for that? What should I check?

### Test code to reproduce

Just use `cy.visit()`, separetely in `cypress open` (manually) and `cypress run`.

### Cypress Version

9.7.0

### Other

The issue occurs on a CI machine only (Windows machine).
Some params when I execute `npx cypress run`:

```
(Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.7.0                                                                          │
  │ Browser:        Electron 100 (headless)                                                        │
  │ Node Version:   v16.13.0 (C:\Dev\nodejs\node.exe)

```

**Comment by mschile** [comment] 2022-05-27 20:56
@mm-dsibinski, you may try turning on Cypress debug logs to see if that provides any useful information:
`DEBUG=cypress-verbose:proxy:http,cypress:* npx cypress run`

**Comment by mm-dsibinski** [comment] 2022-05-28 16:09
hi @mschile ,
so I tried again with the debug logs. For this test, my `baseUrl` was `http://127.0.0.1:50857/`. Everything works fine with `npx cypress open`. However, `npx cypress run` gives the same errors.

I've uploaded the interesting parts from the debug log here: https://gist.github.com/mm-dsibinski/22aef730d0fbcfbffeec3ff188a017b9

I don't clearly see anything very useful there... but I noticed few things:

- first requests to the URL seem to work fine, they have success state
- there are some requests related to ASP.NET authentication, but they seem to go fine
- at one place in the log, I found this: `proxyServer: 'http://localhost:51136'`. At the same time, in the Gist log above, you can find parts with `samesite=strict`. It makes me thinking, that maybe because `cypress run` runs behind a proxy, and the server has `samesite` policy set to `strict`, it somehow doesn't let these requests made by `cypress run` go through? But if that's the case, why would it work with `cypress open`?

I don't really know where to look here, any help is appreciated 😉

**Comment by mm-dsibinski** [comment] 2022-05-28 18:44
It seems that the issue is not present using Chrome:
```
npx cypress run --browser chrome
```

But it still exists with default configuration (Electron).

**Comment by mschile** [comment] 2022-05-31 18:18
@mm-dsibinski, we did update the Electron version in Cypress 9.7.0. Can you try using Cypress 9.6.1 to see if that fixes the issue?

**Comment by mjhenkes** [comment] 2022-06-07 17:32
@mm-dsibinski, Could you try using cypress 9.6.1 to see if the issue is still reproducible?

**Comment by mjhenkes** [comment] 2022-06-14 17:48
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-06-14 17:48 UTC
Labels: stage: awaiting response

**Comment by mm-dsibinski** [comment] 2022-06-28 04:55
Hi again, sorry for my late response. So far, I haven't reproduced this issue with Electron anymore. However, I also permanently switched to using Chrome, so not paying attention to Electron in this scenario on daily basis anymore.
