### ISSUE TITLE
Firefox videos run faster than they should

### ISSUE THREAD

**Issue by kjifs** [cypress-io/cypress#9566] opened 2020-12-08 15:16 UTC
### Current behavior

When running a test in Firefox, the video that is reproduced runs much faster than it should, at approximately 10x speed. This can be seen by comparing the runtime of the video with the timer above the cypress log. I've attached a zip file containing a video demonstrating this behaviour.
[actions.spec.js.mp4.zip](https://github.com/cypress-io/cypress/files/5660042/actions.spec.js.mp4.zip)

### Desired behavior

The video runs in real time.

### Test code to reproduce

Can reproduce using the cypress kitchen sink repo (https://github.com/cypress-io/cypress-example-kitchensink), even after updating cypress to the latest version (6.1.0).

### Versions

Happens as far back as 5.4.0, have not tested earlier versions.
Occurs on windows 10 using firefox 83. Also occurs during bitbucket pipeline using `cypress/included` docker image.

**Comment by jennifer-shehane** [comment] 2020-12-09 07:41
This looks to be a duplicate of #6337

**Closed by jennifer-shehane** 2020-12-09 07:41 UTC
Labels: browser: firefox, topic: video 📹
