### ISSUE TITLE
Can't open windows file upload dialog

### ISSUE THREAD

**Issue by ZhouQQQ** [cypress-io/cypress#4524] opened 2019-06-19 18:38 UTC
### Is this a Feature or Bug?

Bug?Maybe

### Current behavior:

![image](https://user-images.githubusercontent.com/20562245/59790795-50207480-9303-11e9-82bd-e48c5728468e.png)
after click upload element ,nothing happened

### Desired behavior:

open this
![image](https://user-images.githubusercontent.com/20562245/59790889-83fb9a00-9303-11e9-9ee2-557f7ad564ba.png)

### Steps to reproduce: (app code and test code)
```
describe('test', function () {
  it('open baidu img upload', function () {
      cy.visit('https://www.baidu.com/')
      cy.get(".soutu-btn").click()
      cy.get(".upload-pic").click()    
      
  })
})
```
### Versions

win10
chrome
Cypress.version=3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-21 09:28
Duplicate of https://github.com/cypress-io/cypress/issues/170

**Closed by jennifer-shehane** 2019-06-21 09:28 UTC

**Comment by ZhouQQQ** [comment] 2019-06-21 09:34
Thank you, but all I have to do is open the windows file upload dialog.
Instead of actually uploading files

**Comment by keshavpdl1** [comment] 2022-09-14 06:00
How to close this upload dialogue box??
