### ISSUE TITLE
::before element

### ISSUE THREAD

**Issue by rloukil** [cypress-io/cypress#5860] opened 2019-12-03 13:08 UTC
I am getting a button visible with the ::before selector.
I tied to trigger mouseover in order to make it visible but didn't succeed on that.
Can anyone suggest a workaround?
### Current behavior:
![Capture du 2019-12-03 14-06-18](https://user-images.githubusercontent.com/57907029/70053618-1e137e00-15d6-11ea-866f-72239081e15a.png)

### Desired behavior:

Be able to test the button visibility when hovering over the div

**Comment by gabbersepp** [comment] 2019-12-20 13:35
Hey, you can try the chrome remote debugger protocol. That would require you to run your tests in chrome and not in electron. I think by using the protocol you should be able to trigger `:before`.

See this example:
https://github.com/cypress-io/cypress-example-recipes/pull/384

**Comment by jennifer-shehane** [comment] 2019-12-23 07:35
@rloukil We do not currently support testing pseudo css selectors as explained in this comment: https://github.com/cypress-io/cypress/issues/10#issuecomment-118114716 Closing as duplicate of cy.hover() support. https://github.com/cypress-io/cypress/issues/10

**Closed by jennifer-shehane** 2019-12-23 07:35 UTC
