### ISSUE TITLE
Not able to download version 6.9.0 with download link

### ISSUE THREAD

**Issue by michalscreen** [cypress-io/cypress#16616] opened 2021-05-21 07:16 UTC
Not able to download v6.9.0, I would like to try it out to test which version has the best possible performance for my tests.

### Current behavior
<img width="799" alt="Screen Shot 2021-05-21 at 2 13 58 PM" src="https://user-images.githubusercontent.com/56572713/119097343-ce7d7800-ba3e-11eb-9491-63d11de46d90.png">

### Debug logs
Request returns 404

### Download method
https://download.cypress.io/desktop/6.9.0?platform=darwin&arch=x64

- [x] npm
- [ ] yarn
- [x] Direct download
- [ ] other 

### Operating System
- [x] Linux
- [x] Mac
- [x] Windows

**Comment by jennifer-shehane** [comment] 2021-05-21 14:21
Yeah, we messed up publishing 6.9.0 and had to unpublish it. You can try 6.8.1 or 6.9.1 which are the exact same binary. See https://github.com/cypress-io/cypress/issues/15797

Duplicate of https://github.com/cypress-io/cypress/issues/15797

**Closed by jennifer-shehane** 2021-05-21 14:21 UTC
Labels: topic: installation
