### ISSUE TITLE
Socket connection error when app is hosted in a sub domain

### ISSUE THREAD

**Issue by masterpreenz** [cypress-io/cypress#5329] opened 2019-10-10 02:06 UTC
### Current behavior:
The app is hosted in a sub domain but in this error it connects to the domain instead

![1xEqqnJ](https://user-images.githubusercontent.com/1271364/71719893-26b5d900-2e4e-11ea-9312-7fea36868d04.png)

![cyNrMK8](https://user-images.githubusercontent.com/1271364/71719904-31706e00-2e4e-11ea-9c03-3ca375979346.png)

### Desired behavior:
Socket should connect to where it's hosted like a normal browser does

### Steps to reproduce: (app code and test code)

Since the api is hosted in the same place as our front end
```
io.connect("/ui")
```

Also had this but no avail doesn't work
```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  on("before:browser:launch", (browser = {}, args) => {
    console.log(browser, args); // see what all is in here!

    // browser will look something like this
    // {
    //   name: 'chrome',
    //   displayName: 'Chrome',
    //   version: '63.0.3239.108',
    //   path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    //   majorVersion: '63'
    // }

    // args are different based on the browser
    // sometimes an array, sometimes an object

    if (browser.name === "chrome") {
      args.push("--disable-site-isolation-trials");
      args.push("--disable-web-security");
      args.push("--user-data-dir=\"~/www/user-data\"");
      args.push("--config baseUrl=http://app.tenscores.com");
      // whatever you return here becomes the new args



      return args;
    }
  });
}
```

### Versions

Cypress 3.4.1
Ubuntu 18.04.3 LTS

**Comment by sainthkh** [comment] 2021-01-04 08:37
Closing this issue because it's old and doesn't have a reproducible example. I hope this is solved with the latest Cypress. If the problem is still happening, please open a new issue with a reproducible example.

**Closed by sainthkh** 2021-01-04 08:37 UTC
