### ISSUE TITLE
Blank page opened in browser after Cypress installation

### ISSUE THREAD

**Issue by Bannikova77** [cypress-io/cypress#24422] opened 2022-10-27 18:01 UTC
### Current behavior

That was the first installation of the Cypress, the following commands were executed:

1. npm init
2. npm install cypress --save-dev
3. npx cypress open
4. Cypress windows opened > clicked on E2E testing > Configuration files windows opened > clicked on Continue > Chrome browser v107 was chosen > Start E2E testing in Chrome : 
Actual result : The blank screen is presented, nothing happened

<img width="1200" alt="Screen Shot 2022-10-27 at 12 42 17" src="https://user-images.githubusercontent.com/57111119/198361623-34563887-900c-4742-b58e-cd368fbf7dc3.png">

in terminal:
<img width="1228" alt="Screen Shot 2022-10-27 at 12 46 20" src="https://user-images.githubusercontent.com/57111119/198361875-fe294fe1-c913-4c5f-8735-c09c20f5b876.png">

### Desired behavior

On the Chrome, I expect to see something like that:
<img width="699" alt="Screen Shot 2022-10-27 at 12 48 12" src="https://user-images.githubusercontent.com/57111119/198362372-af705528-1bd2-42e1-9475-f01aa6fed29a.png">

### Test code to reproduce

That was the first installation:
1. npm init
2. npm install cypress --save-dev
3. npx cypress open

### Cypress Version

v 10.11.0

### Node version

v16.17.0

### Operating System

macOS Big Sur Version 11.7.1 (20G918)

### Debug Logs

```shell
DevTools failed to load source map: Could not load content for http://localhost:51849/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.7f41798a.js:32840 WebSocket connection to 'ws://localhost:51849/__socket/?EIO=4&transport=websocket' failed: 
doOpen @ index.7f41798a.js:32840
open @ index.7f41798a.js:32238
open @ index.7f41798a.js:33088
Socket$2 @ index.7f41798a.js:33042
lib$3.exports @ index.7f41798a.js:33395
open @ index.7f41798a.js:34289
(anonymous) @ index.7f41798a.js:34433
```

### Other

Chrome Version 107.0.5304.62 (Official Build) (x86_64)

**Comment by amehta265** [comment] 2022-10-31 14:26
@Bannikova77 Thank you for opening this issue. As you have mentioned, this should not be the intended behavior.
I have tried to replicate this issue on my end, however, I have been unable to do so. Cypress works as intended after I install it for the first time in the repository.

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by amehta265** [comment] 2022-11-07 14:40
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by amehta265** 2022-11-07 14:40 UTC
