### ISSUE TITLE
Cypress is not opening

### ISSUE THREAD

**Issue by sdusolle** [cypress-io/cypress#15491] opened 2021-03-15 16:22 UTC
Hello,

I am trying to run Cypress on my local (on Windows) but the Cypress window is loading forever...
Here the commands I use inside my project:
    `yarn install`
    `yarn e2e:debug` --> which triggers `cypress open`

**Result:** the Cypress window is opening but the test is not displayed and I get a never ending loader (attached).

Please note that I try to run my test on a branch of my project, if I use the same command ( `yarn e2e:debug`) on master, cypress is opening and I can launch the test.

With : 
Yarn v1.22.10 / Cypress v6.6.0 /  Node v14.16.0

![cypress](https://user-images.githubusercontent.com/42536778/111185958-d2aa9680-85b2-11eb-91c7-4a00f67a1488.JPG)

**Comment by jennifer-shehane** [comment] 2021-03-15 18:30
Duplicate of https://github.com/cypress-io/cypress/issues/9572

**Closed by jennifer-shehane** 2021-03-15 18:30 UTC
