### ISSUE TITLE
error while loading shared libraries: libffmpeg.so — gitlab, cypress/base:10

### ISSUE THREAD

**Issue by a-x-** [cypress-io/cypress#3473] opened 2019-02-14 20:06 UTC
### Current behavior:

`error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory`

### Steps to reproduce: (app code and test code)

```yml
...

cache:
  paths:
    - ~/.npm
    - ~/.cache

...

e2e-tests:
  image: cypress/base:10
  scripts:
    - npm run ci:mocks # faked backend background process
    - npm run ci:start # dev static server background process
    - npm ci && cypress verify && cypress run
```
### Versions

- "cypress": "3.1.0",
- latest enterprise gitlab
- cypress/base:10

**Comment by a-x-** [comment] 2019-02-14 20:07
add ffmpeg to docker image, ok?

**Comment by a-x-** [comment] 2019-02-14 20:15
> add ffmpeg to docker image, ok?

I tried though, it has not helped :-(

**Comment by jennifer-shehane** [comment] 2019-02-15 06:27
Duplicate of https://github.com/cypress-io/cypress/issues/1556 See some workarounds here: https://github.com/cypress-io/cypress/issues/1556#issuecomment-418069209

**Closed by jennifer-shehane** 2019-02-15 06:27 UTC

**Comment by glpibr** [comment] 2019-10-16 12:38
Hello,
I hope what I post will help.
I'm starting at Electronjs and right from the start I had a very hard problem finding solution which is exactly this error that are reported from the ffmpeg shared library.
I use Debian 10 and have installed it in a number of ways and sometimes thinking it might be some package management error.

Finally, I solved my problem by manually installing NodeJS (same official website tutorial) and running the commands below to resolve the shared library error.

```
npm audit fix
npm audit fix --force
```

After that, start working normally.

Big hug to all!

#
# PORTUGUESE ORIGINAL

olá,
espero que o que vou postar ajude.
Estou iniciando no Electronjs e logo de início tive um problema muito difícil de encontrar solução que é exatamente este erro que estão relatando da biblioteca compartilhada ffmpeg.
Uso Debian 10 e fiz a instalção de diversas formas e vezes pensando que pudesse ser algum erro de gerenciamento de pacotes.

Por fim, resolvi meu problema com a instalação manual do NodeJS (tutorial do site oficial mesmo) e rodando os comandos abaixo para resolver o erro de biblioteca compartilhada.

```
npm audit fix
npm audit fix --force
```

Depois disso, o start passou a funcionar normalmente.

Grande abraço a todos!
