### ISSUE TITLE
Attributes getting removed while running tests 

### ISSUE THREAD

**Issue by soumyappillai** [cypress-io/cypress#23176] opened 2022-08-07 13:04 UTC
### Current behavior

When I run my test using cypress, a particular test, keeps failing because hidden element is not showing up but when I run the same test manually, I can see the element with the hidden element showing up as soon as I enter value.

There is a field in our UI where if I pass invalid characters, then it should immediately show the hidden error element using aria, but this is not happening when running through cypress
Eg : attached
![image](https://user-images.githubusercontent.com/110770875/183290851-ac3315bd-9299-4d32-8e7b-67325db5f3d5.png)
![image](https://user-images.githubusercontent.com/110770875/183290856-6c0bb98d-d88b-473f-b57c-4a758a8b9b22.png)
![image](https://user-images.githubusercontent.com/110770875/183290859-12c6b29d-351e-40e4-ba45-acd3e9961427.png)
![image](https://user-images.githubusercontent.com/110770875/183290914-a56965a0-5f12-41df-93ef-6b1ba6b495b4.png)
![image](https://user-images.githubusercontent.com/110770875/183290924-5de0c1a8-937b-4452-9e93-41b6d99cba2b.png)

### Desired behavior

When I run the same above test manually on the same field the result I am getting is this.
![image](https://user-images.githubusercontent.com/110770875/183290883-ff241229-b5ff-4734-a902-a788a3e0d4d4.png)
![image](https://user-images.githubusercontent.com/110770875/183290887-89970d07-2dc5-4428-95df-10a4527e3ac8.png)

### Test code to reproduce

cy.get('#address-cityName').type("$^");

        cy.contains('Next').click();

        cy.get('#address-cityNameError').should('have.attr', 'message').should('contain', 'City contains invalid characters.');

### Cypress Version

10.4

**Comment by rockindahizzy** [comment] 2022-08-09 14:53
Hey @soumyappillai,

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-16 18:18
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-16 18:18 UTC
Labels: stage: awaiting response, Needs Reproduction
