### ISSUE TITLE
Continually getting "element detached from the DOM" even after employing Cypress's suggestions

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#17043] opened 2021-06-21 22:06 UTC
### Current behavior
My test gets the dreaded "element detached from the DOM" error even after following the recommendations from Cypress.

### Test code to reproduce
```
    cy.get('.data-table tbody tr:nth-of-type(1) .device-link')
      .should('have.length', 1)
      .click();
```

As you can see, I've combined all my selectors into a single `get` command, I'm running an assertion afterwards, and I'm not saving the reference, so it should be valid. Still, this test fails in CI all the time with messages like this:

```
Timed out retrying after 4050ms:  cy.click() failed because this element is detached from the DOM.

<a class="link device-link" href="..." ...>

The previous command that ran was:

  > cy.should()
```

How is the element getting detached between the `should` and the `click`?

### Versions
OS: Linux
Cypress: 7.5.0

**Comment by 08screasey** [comment] 2021-06-22 12:22
I am encountering the exact same issue on Cypress 7.1.0:
```
Timed out retrying after 4050ms: cy.click() failed because this element is detached from the DOM.
<button data-cy="expand-panel" type="button" class="expand-button px-2 py-1  btn btn-link">...</button>
Cypress requires elements be attached in the DOM to interact with them.
The previous command that ran was:
  > cy.get()
```
for command:
cy.getByData("expand-panel").click();

@kaiyoma which mode are you running in, open or run? 
I am finding this to be a consistent issue every time I re-open a spec from the GUI, and if I refresh the tests from within the spec the issue disappears. I can't figure out a solution

**Comment by kaiyoma** [comment] 2021-06-22 17:35
I'm getting this with `cypress run` in our CI.

**Comment by jennifer-shehane** [comment] 2021-06-22 18:06
Duplicate of https://github.com/cypress-io/cypress/issues/7306 

There's a long thread of suggestions in there - it'd be helpful to keep conversation focused in that issue. I understand not all workarounds work and we need a broader solution.

**Closed by jennifer-shehane** 2021-06-22 18:06 UTC
