### ISSUE TITLE
Can I have cy.task retry until assertion passes?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1936] opened 2018-06-12 21:42 UTC
[`cy.task`](https://on.cypress.io/task) is great but does not retry its action, even if it is idempotent code. In situations like "checking if the database has been updated" (see https://github.com/cypress-io/cypress-example-recipes/commit/e6f3b4c2cc7731c1ec9936426bb71b5ecb9af9ae#diff-11f8d1f12b6eb04ff4abd710d5e9d786) it would be perfect NOT to implement "retry until my assertion passes" logic in Node, but instead have `cy.task` behave like a regular Cypress command.

Something like this

```js
cy.taks('find item in the database').should('deep.equal', {id: 1, text: 'something'})
```

**Comment by Bkucera** [comment] 2018-06-13 11:40
Is this one action, then the assertion will retry until it passes, or multiple actions? Cypress commands don't retry actions right?

**Comment by bahmutov** [comment] 2018-06-13 15:07
it should rerun the single action until the assertion passes or times out

**Comment by Bkucera** [comment] 2018-06-13 16:37
So it will potentially seed my db multiple times? We don't `click` multiple times for example when retrying a `cy.get(...').click().should(...)`

**Comment by bahmutov** [comment] 2018-06-13 17:01
Sure, it depends on the callback function

**Comment by bahmutov** [comment] 2018-06-13 17:35
better formatting

```js
cy.task('reset:db').then(...)
// "reset:db" runs once
cy.task('db:select', title, {timeout: 5000, idempotent: true}).should('deep.equal', ...)
// "db:select" is retried until the assertion passes or 5 seconds timeout reached
```

**Comment by jennifer-shehane** [comment] 2019-07-12 07:35
I don't think this is a great suggestion either. We have [an existing open issue](https://github.com/cypress-io/cypress/issues/4692) where we *do* accidentally run tasks multiple times which causes issues - I can see this being even more confusing. Do you have a real world use case for wanting this?

**Comment by hdavidzhu** [comment] 2019-07-12 17:33
@bahmutov I have a lot of success with wrapping `cy.task` with `cy.verifyUpcomingAssertions`. Although it's not well documented, there are enough code samples for us to have what we need for "checking if the database has been updated"

```coffee
# Look for data with a query. If chained with an assertion, retry until assertion passes (or timeout)
#
# @param collection [String]
# @param expression [Object] Mongo-like query
# @param options [Object]
#
# @return [Promise]
#   @resolve [Array<Object>] Array of docs
#
# @log [Object]
#   @property collection [String]
#   @property docs [Array<Object>] Resulting query fetch docs
#   @property expression [Object]
Cypress.Commands.add 'queryGet', (collection, expression, options = {}) ->
  # We want to reference the same console output to update the same log
  # @see https://github.com/cypress-io/cypress/blob/55b352a11d0a664517ae054c67432d98abc2389e/packages/driver/src/cy/commands/task.coffee#L14
  consoleOutput = {
    collection
    expression
  }

  options._log = Cypress.log({
    consoleProps: -> consoleOutput
    message: "#{collection} -> #{JSON.stringify(expression)}"
    name: 'queryGet'
  })

  tryQueryGet = ->
    cy.task('queryGet', {collection, expression}, {
      log: false
      timeout: options.timeout || Cypress.config('defaultCommandTimeout')
    }).then (docs) ->
      consoleOutput.docs = docs
      # TODO 2019-04-12: How does all this logging work? Without 'snapshot'ing, we can't get docs
      #   in the console logs. If we don't mutate 'consoleOutput' directly, we get duplicate Cypress
      #   messages
      #   @see https://github.com/cypress-io/cypress/blob/6a53b4bed1950d7112e59a195f760c38bb2ad519/packages/driver/src/cypress/log.coffee#L262
      #   @see https://github.com/cypress-io/cypress/search?q=_log.snapshot&unscoped_q=_log.snapshot
      options._log.snapshot().end()
      cy.verifyUpcomingAssertions(docs, options, {
        onFail: options._log
        onPass: options._log
        onRetry: tryQueryGet
      })

  return tryQueryGet()
```

**Comment by leolin0704** [comment] 2019-09-30 06:36
`Cypress.Commands.add(
    'until',
    ({ it, become, delay = 5000, timeout = Cypress.config('defaultCommandTimeout') }) => {
        cy.log('Until start:');

        let lastestResult;
        setTimeout(() => {
            if (typeof become === 'function') {
                expect(become(lastestResult), `${become}`).to.be.true;
            } else {
                expect(lastestResult).to.be.equal(become);
            }
        }, timeout);

        const retry = () => {
            let originalResult = it();

            if (!Cypress.isCy(originalResult)) {
                originalResult = cy.wrap(originalResult, { log: false });
            }

            originalResult.then(result => {
                lastestResult = result;
                let checkResult = false;
                if (typeof become === 'function') {
                    checkResult = become(result);
                } else {
                    checkResult = isEqual(result, become);
                }

                if (checkResult) {
                    cy.log(`Until end: "${result}" is expected`);
                    return cy.wrap(result, { log: false });
                } else {
                    cy.log(`Until retry: "${result}" is not expected`);
                    cy.wait(delay);
                    return retry();
                }
            });
        };

        return retry();
    }
);`

**Comment by leolin0704** [comment] 2019-09-30 06:41
Add a custom command to do this:
```javascript
Cypress.Commands.add(
    'until',
    ({ it, become, delay = 5000, timeout = Cypress.config('defaultCommandTimeout') }) => {
        cy.log('Until start:');
        let lastestResult;
        setTimeout(() => {
            if (typeof become === 'function') {
                expect(become(lastestResult), `${become}`).to.be.true;
            } else {
                expect(lastestResult).to.be.equal(become);
            }
        }, timeout);

        const retry = () => {
            let originalResult = it();

            if (!Cypress.isCy(originalResult)) {
                originalResult = cy.wrap(originalResult, { log: false });
            }

            originalResult.then(result => {
                lastestResult = result;
                let checkResult = false;
                if (typeof become === 'function') {
                    checkResult = become(result);
                } else {
                    checkResult = isEqual(result, become);
                }

                if (checkResult) {
                    cy.log(`Until end: "${result}" is expected`);
                    return cy.wrap(result, { log: false });
                } else {
                    cy.log(`Until retry: "${result}" is not expected`);
                    cy.wait(delay);
                    return retry();
                }
            });
        };

        return retry();
    }
);
```

Usage:
```javascript
it('should retry task', function() {
        let result = 0;
        cy.until({
            it: () => ++result,
            become: 3,
            timeout: 5000,
            delay: 500,
        });
    });
```

**Comment by jennifer-shehane** [comment] 2020-11-09 06:13
Closing as resolved since there is a workaround outline. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-11-09 06:13 UTC
Labels: pkg/driver, stage: proposal 💡

**Comment by veryspry** [comment] 2024-08-20 20:10
Taking inspiration from @leolin0704 🎉  I wrote a custom command that allows you to retry a `Cypress.Chainable` command and then yield it's result. This allows you to chain on the custom command to do further assertions.


Command:
```ts
declare global {
	namespace Cypress {
		retryUntil: (opts: {
			cmd: () => Cypress.Chainable;
			validator: any;
			delay?: number;
			timeout?: number;
		}) => Chainable;
	}
}

Cypress.Commands.add(
	'retryUntil',
	({
		cmd,
		validator,
		delay = 500,
		timeout = Cypress.config('defaultCommandTimeout'),
	}) => {
		const startTime = new Date().getTime();

		const checkCondition = () => {
			const currentTime = new Date().getTime();
			if (currentTime - startTime >= timeout) {
				throw new Error('retryUntil: Timeout reached');
			}

			cmd().then((result) => {
				if (validator(result)) {
					cy.wrap(result);
				} else {
					cy.wait(delay).then(checkCondition);
				}
			});
		};

		checkCondition();
	}
);
``` 

Example:

(Example use case: external API can take between 2-8 seconds to finish processing a POST request on a new entity.)

```ts
cy.retryUntil({
	cmd: () => cy.customAPIRequestCmd(),
	validator: (response) => response.status === 200,
	timeout: 10000,
}).then((response) => response.data.should('not.be.empty'));
```
