### ISSUE TITLE
cy.origin() failed to create a spec bridge to communicate with the specified origin. This can happen when you attempt to create a spec bridge to an insecure (http) frame from a secure (https) frame.

### ISSUE THREAD

**Issue by abdul-saboor-datics** [cypress-io/cypress#30398] opened 2024-10-11 10:25 UTC
### Current behavior

i am facing this issue while autherticating cypress with auth0 as per provided documentation.

**issue**
cy.origin() failed to create a spec bridge to communicate with the specified origin. This can happen when you attempt to create a spec bridge to an insecure (http) frame from a secure (https) frame.

### Desired behavior

it should be logged in into my web app.

### Test code to reproduce

function loginViaAuth0Ui(username, password) {
    
    cy.visit('/');

    cy.origin(
        Cypress.env('AUTH0_DOMAIN'),
        { args: { username, password } },
        ({ username, password }) => {
            cy.get('input#username').type(username);
            cy.get('input#password').type(password, { log: false });
            cy.contains('button[value=default]', 'Continue').click();
        }
    );

    cy.url().should('include', Cypress.config('baseUrl'));
}

Cypress.Commands.add('loginToAuth0', (username, password) => {
    const log = Cypress.log({
        displayName: 'AUTH0 LOGIN',
        message: [`🔐 Authenticating | ${username}`],
        autoEnd: false,
    });
    log.snapshot('before');

    cy.session(
        `auth0-${username}`,
        () => {
            loginViaAuth0Ui(username, password);
        },
        {
            validate: () => {
                cy.wrap(localStorage)
                  .invoke('getItem', 'authToken')
                  .should('exist');
            },
        }
    );

    log.snapshot('after');
    log.end();
});

### Cypress Version

13.11.0

### Node version

v16.20.2

### Operating System

Windows Feature Experience Pack 1000.22700.1034.0

**Comment by jennifer-shehane** [comment] 2024-10-11 18:14
Duplicate of https://github.com/cypress-io/cypress/issues/28284

**Closed as not planned by jennifer-shehane** 2024-10-11 18:14 UTC
Labels: type: duplicate
