### ISSUE TITLE
Cypress test runner / dev tools are blanked out

### ISSUE THREAD

**Issue by jean-smaug** [cypress-io/cypress#1617] opened 2018-04-19 15:10 UTC
### Current behavior:
<img width="1440" alt="capture d ecran 2018-04-19 a 17 04 05" src="https://user-images.githubusercontent.com/22884251/39000221-bf91ad12-43f3-11e8-85cd-b2bda4f650b3.png">

### Desired behavior:
See the cypress app ^^ 

### Steps to reproduce:

Just run a test

### Versions  
On Cypress 2.1.0, MacOS High Sierra with Chrome Canary  68.0.3400.0. 
Maybe it's on canary's side but if the next version of Chrome introduce some breaking changes, it's something to be aware of

**Comment by jennifer-shehane** [comment] 2018-04-20 00:11
I'm not experiencing this in Canary 68.0.3400.0.

<img width="1792" alt="screen shot 2018-04-19 at 8 09 08 pm" src="https://user-images.githubusercontent.com/1271364/39024240-977e3132-440d-11e8-9be4-144c42f99eb6.png">

It looks like you have some other extensions installed in your Canary browser. Could you disable all of those first to further isolate the issue to Cypress? Let me know if the issue still occurs after that. Thanks.

**Comment by lobor** [comment] 2018-06-11 10:44
I have same issue

Chrome 67.0.3396.79 on Mac
<img width="1914" alt="capture d ecran 2018-06-11 a 12 42 56" src="https://user-images.githubusercontent.com/3316940/41227451-1a3da00e-6d75-11e8-8fe9-992d260e97ed.png">

**Comment by jennifer-shehane** [comment] 2018-06-11 21:37
We'll need a reproducible example that we can run to get this to happen for us. I do not think this issue is likely relevant to the specific Chrome version, but some other reason that we'd love to track down. Thanks!

**Comment by jennifer-shehane** [comment] 2018-06-11 21:38
@lobor Also, as stated above, if you could you disable all of those first to further isolate the issue to Cypress? Let me know if the issue still occurs after that. Thanks.

**Comment by simsim2006** [comment] 2018-06-14 14:38
so i had the same issue. I just remember i deleted my project's node_module/ folder a few minutes before facing that issue, and then i did a yarn install/npm install. I don't know if it can help you to reproduce the issue. 

In my case, i use Electron instead of Chrome as a workaround of this issue

**Comment by brian-mann** [comment] 2018-06-14 15:07
Text is overrated, why do you even need it rendered? Nothing to see here folks...

**Comment by jennifer-shehane** [comment] 2018-06-14 15:13
Yeah, deleting the node_module folder did not affect the runner. Did you happen to touch the App Data folder? Like `File > App Data` in menu bar? 

I'm pretty confused on this one. :(

**Comment by simsim2006** [comment] 2018-06-14 15:18
No i never touched that folder no. Can i try to empty it without any risk ?

**Comment by jennifer-shehane** [comment] 2018-06-14 15:21
Yes, I suppose it is worth a try:

- Goto `File -> View App Data`
- Delete everything in here
- Close cypress and open it up again

**Comment by simsim2006** [comment] 2018-06-14 15:23
just tested but doesn't help

**Comment by simsim2006** [comment] 2018-06-14 15:28
and when i open a new tab on the browser window opened by cypress, it show the same... so seems like an issue with the "piloted browser" (i don't know how to call that)

![google_with_chrome](https://user-images.githubusercontent.com/9596971/41422010-500ab9c6-6ff8-11e8-9b4d-5660fd90c8a1.png)

**Comment by Antontelesh** [comment] 2018-06-14 17:14
I have the same issue.

I tried to remove cypress cache folder and reinstall it again.
But that did not help.

**Comment by brian-mann** [comment] 2018-06-14 17:22
You all might want to pass in arguments to chrome to start disabling things like the GPU

[`--disable-gpu`](https://peter.sh/experiments/chromium-command-line-switches/#disable-gpu)

You can do that in your `pluginsFile` as documented here: https://docs.cypress.io/api/plugins/browser-launch-api.html

For a full list of command line arguments use this:

https://peter.sh/experiments/chromium-command-line-switches/

Alternatively you could also **remove** the ones we pass in by default to see if those trigger it. Either something we're adding or something you need to add will fix this. But without a reproducible machine we won't be able to figure it out on our own.


You might want to start adding a bunch of the `--disable-*` flags

**Comment by ankri** [comment] 2018-06-15 15:37
I am on 
- Mac `Sierra 10.12.6` 
- Cypress `3.0.1`
- Chrome `67.0.3396.87`

`--disable-gpu` did the trick for me, thanks!

**Comment by ValentinH** [comment] 2018-06-24 16:27
I can confirm that adding `--disable-gpu` fixes the issue.

I've also tried to remove all the default flags and it didn't fix it.

Then I have tried each `--disable-gpu-***` flags and 2 of them also fixed the issue (separately):
- `--disable-gpu-compositing`
- `--disable-gpu-rasterization`

**Comment by dcastil** [comment] 2018-07-14 11:39
I have the same issue after updating to Chrome v67. The window looks like this:
<img width="1312" alt="bildschirmfoto 2018-07-14 um 13 21 23" src="https://user-images.githubusercontent.com/31006608/42724016-c187fe5e-876a-11e8-9079-8fd7a81dcdd2.png">

I can also confirm that adding one of
`--disable-gpu`
`--disable-gpu-compositing`
`--disable-gpu-rasterization`
solves the problem for me.

**Comment by jennifer-shehane** [comment] 2019-01-25 09:14
Closing since there is a suggested workaround available.

**Closed by jennifer-shehane** 2019-01-25 09:14 UTC
