### ISSUE TITLE
first() p element is detached from DOM after cy.get() in ProseMirror contenteditable

### ISSUE THREAD

**Issue by Narretz** [cypress-io/cypress#9523] opened 2020-12-03 21:09 UTC
### Current behavior

Cypress can't get an element with first() inside a [ProseMirror](https://prosemirror.net/) contenteditable. It always fails with a detached error.

### Desired behavior
Cypress should get the currently attached element, not the detached one.

### Test code to reproduce
The ProseMirror test app is here: 
https://cypress-prosemirror-bug.glitch.me/

The test is as simple as:
```js
describe('get elements', function () {
    it('should get element', function () {
        cy.visit('https://cypress-prosemirror-bug.glitch.me/');
        cy.get('.ProseMirror p').first().should('exist')
        // Working
        // cy.get('.ProseMirror p:first-of-type').as('firstP');
        // cy.get('.ProseMirror p:first').as('firstP');        
     })
 });
```

### More info
You can see in the example in the console that querying for the element triggers dom changes in the contenteditable. I assume this happens in the first place because cypress is doing some checks for visibility etc? If I want to look into the implementation a bit more, where should I start?
You can also see that `cy.get('.ProseMirror p:first-of-type').as('firstP')` is triggering a different set of dom changes, that don't let the query fail.
This is my problem with this - I know that Cypress needs stability, but in this example it seems arbitrary that Cypress can pick up the attached element in one case, but not in another.
What makes it even more tricky is that the Cypress query itself is causing the dom change.

### Versions
I've tested with 5.6.0 and 6.0.1, but I think that doesn't matter.
The problem appeared after I updated prosemirror-view to 1.9.0+
But since Cypress causes a dom change in all versions of ProseMirror I tested, but only same make it fail, I consider it a Cypress bug / problem.

**Comment by jennifer-shehane** [comment] 2020-12-04 05:33
Yeah, there is something between the `.get()` and the `.first()` that is causing the page to rerender so that the element is no longer there with the `.first()` command runs. This is kind of a duplicate of https://github.com/cypress-io/cypress/issues/7306

I do see the logs in the console of the app rerendering when the `cy.get()` runs. Can you provide the repo code for the https://cypress-prosemirror-bug.glitch.me/ app? I'd be interested in understanding why the `cy.get()` query itself is causing the page to rerender as this is not intended behavior. 

<img width="601" alt="Screen Shot 2020-12-04 at 11 55 25 AM" src="https://user-images.githubusercontent.com/1271364/101125437-a1234600-3627-11eb-9b2e-2559b752dd71.png">

**Comment by jolkkola** [comment] 2020-12-04 10:39
I am having the same sort of trouble when trying to test our ProseMirror-based editor component. Our setup is a bit more complex, but I noticed that a similar error happens with this test app as well.

Using @Narretz's test app and one of the functioning selectors, Cypress fails when trying to click:

```js
describe('get elements', function () {
  it('should get element and click', function () {
    cy.visit('https://cypress-prosemirror-bug.glitch.me/');
    cy.get('.ProseMirror p:first').should('exist').click();
  });
});
```

This results in the `cy.click() failed because this element is detached from the DOM.` error being shown.

**Comment by Narretz** [comment] 2020-12-04 15:52
Hi @jennifer-shehane the code is at https://glitch.com/edit/#!/cypress-prosemirror-bug?path=index.js

Unfortunately, the prosemirror setup is a bit awkward here, because it pulls in a special bundled file. I can set up a repo with a classic webpack config if that helps.

I've also tried to find out why exactly get() triggers a re-render, but no luck so far. The re-render also happens when you do a simple `cy.get('.ProseMirror p').should('have.length', 2)` but in this case, Cypress doesn't complain about detached elements.

**Comment by Narretz** [comment] 2021-03-05 09:32
Hi @jennifer-shehane  I recently came back to this issue, and can unfortunately confirm that this is  still happening in Cypres 6.6.0.

I have created a repo with a few simple test cases that should hopefully help to track down why the "detached" error happens with some commands / selectors but not others.

https://github.com/Narretz/cypress-prosemirror-get

**Comment by phikes** [comment] 2021-04-09 14:28
I am fairly sure this happens because prosemirror re-renders the editor content when the DOM gets changed inside from somwhere else. Cypress does add some attributes to the content, so I strongly suspect this is the issue. I am currently investigating if this behaviour can be changed.

**Comment by phikes** [comment] 2021-04-09 14:38
One way to confirm this, is to trigger events outside of cypress:

```
cy.document().then((document) => Cypress.dom.wrap(document.querySelector('.ProseMirror p:first')).click())
```

This works.

**Comment by phikes** [comment] 2021-04-09 15:03
I couldn't find a way to disable the attributes, but the above sufficiently worked in my case!

**Comment by Narretz** [comment] 2021-08-05 12:27
It appears this problem was "fixed" somewhere in prosemirror-view 1.18.1 - 1.18.8, i.e. prosemirror doesn't re-render anymore when cypress tries to get the element.

**Comment by Narretz** [comment] 2021-08-10 09:31
Actually, this still happens depending on the complexity of the ProseMirror instance. But I don't have a basic example yet.

**Comment by Narretz** [comment] 2022-01-18 19:27
fyi, this problem came back with a vengeance for me in prosemirror-view 1.23.6

**Comment by tpjg** [comment] 2022-02-17 10:18
I confirm the problem is there with prose mirror 1.23.6, interestingly (at least on my setup) this problem exists when using `Chrome 98` as a browser but does **not** exist when running exactly the same spec with the builtin `Electron 94`.

**Comment by jennifer-shehane** [comment] 2022-04-13 14:18
Duplicate of https://github.com/cypress-io/cypress/issues/7306

**Closed by jennifer-shehane** 2022-04-13 14:18 UTC
Labels: stage: needs information
