### ISSUE TITLE
spawn get ENOENT

### ISSUE THREAD

**Issue by errohitrana2013** [cypress-io/cypress#6852] opened 2020-03-26 09:58 UTC

**Comment by errohitrana2013** [comment] 2020-03-26 10:01
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cypress',
1 verbose cli   '--save-dev'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session abfb9d5db25de986
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/cypress 461ms (from cache)
8 silly pacote tag manifest for cypress@latest fetched in 532ms
9 timing stage:loadCurrentTree Completed in 658ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule cypress@4.2.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@cypress%2flistr-verbose-renderer 261ms (from cache)
18 silly pacote version manifest for @cypress/listr-verbose-renderer@0.4.1 fetched in 273ms
19 silly resolveWithNewModule @cypress/listr-verbose-renderer@0.4.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/common-tags 196ms (from cache)
21 silly pacote version manifest for common-tags@1.8.0 fetched in 236ms
22 silly resolveWithNewModule common-tags@1.8.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/@types%2fsizzle 591ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/arch 592ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/@cypress%2fxvfb 605ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/chalk 582ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/cli-table3 562ms (from cache)
28 silly pacote version manifest for @types/sizzle@2.3.2 fetched in 619ms
29 silly resolveWithNewModule @types/sizzle@2.3.2 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/bluebird 612ms (from cache)
31 silly pacote version manifest for arch@2.1.1 fetched in 638ms
32 silly resolveWithNewModule arch@2.1.1 checking installable status
33 silly pacote version manifest for @cypress/xvfb@1.2.4 fetched in 648ms
34 silly resolveWithNewModule @cypress/xvfb@1.2.4 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/cachedir 630ms (from cache)
36 silly pacote version manifest for chalk@2.4.2 fetched in 627ms
37 silly resolveWithNewModule chalk@2.4.2 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/commander 605ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/check-more-types 624ms (from cache)
40 silly pacote version manifest for cli-table3@0.5.1 fetched in 621ms
41 silly resolveWithNewModule cli-table3@0.5.1 checking installable status
42 silly pacote version manifest for bluebird@3.7.2 fetched in 675ms
43 silly resolveWithNewModule bluebird@3.7.2 checking installable status
44 silly pacote version manifest for cachedir@2.3.0 fetched in 696ms
45 silly resolveWithNewModule cachedir@2.3.0 checking installable status
46 silly pacote version manifest for commander@4.1.0 fetched in 678ms
47 silly resolveWithNewModule commander@4.1.0 checking installable status
48 silly pacote version manifest for check-more-types@2.24.0 fetched in 726ms
49 silly resolveWithNewModule check-more-types@2.24.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/debug 441ms (from cache)
51 silly pacote version manifest for debug@4.1.1 fetched in 486ms
52 silly resolveWithNewModule debug@4.1.1 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/eventemitter2 384ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/execa 374ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/executable 375ms (from cache)
56 http fetch GET 304 https://registry.npmjs.org/extract-zip 387ms (from cache)
57 silly pacote version manifest for eventemitter2@4.1.2 fetched in 414ms
58 silly resolveWithNewModule eventemitter2@4.1.2 checking installable status
59 silly pacote version manifest for executable@4.1.1 fetched in 399ms
60 silly resolveWithNewModule executable@4.1.1 checking installable status
61 silly pacote version manifest for execa@1.0.0 fetched in 404ms
62 silly resolveWithNewModule execa@1.0.0 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/is-ci 347ms (from cache)
64 http fetch GET 304 https://registry.npmjs.org/getos 377ms (from cache)
65 http fetch GET 304 https://registry.npmjs.org/fs-extra 391ms (from cache)
66 silly pacote version manifest for extract-zip@1.6.7 fetched in 423ms
67 silly resolveWithNewModule extract-zip@1.6.7 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/is-installed-globally 343ms (from cache)
69 silly pacote version manifest for is-ci@2.0.0 fetched in 402ms
70 silly resolveWithNewModule is-ci@2.0.0 checking installable status
71 silly pacote version manifest for getos@3.1.4 fetched in 433ms
72 silly resolveWithNewModule getos@3.1.4 checking installable status
73 silly pacote version manifest for fs-extra@8.1.0 fetched in 471ms
74 silly resolveWithNewModule fs-extra@8.1.0 checking installable status
75 http fetch GET 304 https://registry.npmjs.org/lazy-ass 394ms (from cache)
76 silly pacote version manifest for is-installed-globally@0.1.0 fetched in 435ms
77 silly resolveWithNewModule is-installed-globally@0.1.0 checking installable status
78 silly pacote version manifest for lazy-ass@1.6.0 fetched in 632ms
79 silly resolveWithNewModule lazy-ass@1.6.0 checking installable status
80 silly fetchPackageMetaData error for request@github:cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16 Error while executing:
80 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
80 silly fetchPackageMetaData
80 silly fetchPackageMetaData
80 silly fetchPackageMetaData spawn git ENOENT
81 http fetch GET 304 https://registry.npmjs.org/listr 538ms (from cache)
82 silly pacote version manifest for listr@0.14.3 fetched in 562ms
83 silly resolveWithNewModule listr@0.14.3 checking installable status
84 http fetch GET 304 https://registry.npmjs.org/lodash 532ms (from cache)
85 http fetch GET 304 https://registry.npmjs.org/log-symbols 527ms (from cache)
86 http fetch GET 304 https://registry.npmjs.org/minimist 537ms (from cache)
87 http fetch GET 304 https://registry.npmjs.org/moment 531ms (from cache)
88 silly pacote version manifest for lodash@4.17.15 fetched in 569ms
89 silly resolveWithNewModule lodash@4.17.15 checking installable status
90 silly pacote version manifest for log-symbols@3.0.0 fetched in 579ms
91 silly resolveWithNewModule log-symbols@3.0.0 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/ospath 515ms (from cache)
93 silly pacote version manifest for minimist@1.2.2 fetched in 600ms
94 silly resolveWithNewModule minimist@1.2.2 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/pretty-bytes 530ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/ramda 519ms (from cache)
97 silly pacote version manifest for moment@2.24.0 fetched in 602ms
98 silly resolveWithNewModule moment@2.24.0 checking installable status
99 silly pacote version manifest for ospath@1.2.2 fetched in 561ms
100 silly resolveWithNewModule ospath@1.2.2 checking installable status
101 silly pacote version manifest for pretty-bytes@5.3.0 fetched in 579ms
102 silly resolveWithNewModule pretty-bytes@5.3.0 checking installable status
103 silly pacote version manifest for ramda@0.26.1 fetched in 557ms
104 silly resolveWithNewModule ramda@0.26.1 checking installable status
105 http fetch GET 304 https://registry.npmjs.org/request-progress 317ms (from cache)
106 silly pacote version manifest for request-progress@3.0.0 fetched in 325ms
107 silly resolveWithNewModule request-progress@3.0.0 checking installable status
108 http fetch GET 304 https://registry.npmjs.org/supports-color 283ms (from cache)
109 silly pacote version manifest for supports-color@7.1.0 fetched in 301ms
110 silly resolveWithNewModule supports-color@7.1.0 checking installable status
111 http fetch GET 304 https://registry.npmjs.org/tmp 214ms (from cache)
112 silly pacote version manifest for tmp@0.1.0 fetched in 220ms
113 silly resolveWithNewModule tmp@0.1.0 checking installable status
114 http fetch GET 304 https://registry.npmjs.org/untildify 164ms (from cache)
115 silly pacote version manifest for untildify@4.0.0 fetched in 167ms
116 silly resolveWithNewModule untildify@4.0.0 checking installable status
117 http fetch GET 304 https://registry.npmjs.org/url 159ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/yauzl 159ms (from cache)
119 silly pacote version manifest for url@0.11.0 fetched in 181ms
120 silly resolveWithNewModule url@0.11.0 checking installable status
121 silly pacote version manifest for yauzl@2.10.0 fetched in 169ms
122 silly resolveWithNewModule yauzl@2.10.0 checking installable status
123 timing stage:rollbackFailedOptional Completed in 4ms
124 timing stage:runTopLevelLifecycles Completed in 2593ms
125 silly saveTree hello@1.0.0
125 silly saveTree `-- cypress@4.2.0
125 silly saveTree   +-- @cypress/listr-verbose-renderer@0.4.1
125 silly saveTree   +-- @cypress/xvfb@1.2.4
125 silly saveTree   +-- @types/sizzle@2.3.2
125 silly saveTree   +-- arch@2.1.1
125 silly saveTree   +-- bluebird@3.7.2
125 silly saveTree   +-- cachedir@2.3.0
125 silly saveTree   +-- chalk@2.4.2
125 silly saveTree   +-- check-more-types@2.24.0
125 silly saveTree   +-- cli-table3@0.5.1
125 silly saveTree   +-- commander@4.1.0
125 silly saveTree   +-- common-tags@1.8.0
125 silly saveTree   +-- debug@4.1.1
125 silly saveTree   +-- eventemitter2@4.1.2
125 silly saveTree   +-- execa@1.0.0
125 silly saveTree   +-- executable@4.1.1
125 silly saveTree   +-- extract-zip@1.6.7
125 silly saveTree   +-- fs-extra@8.1.0
125 silly saveTree   +-- getos@3.1.4
125 silly saveTree   +-- is-ci@2.0.0
125 silly saveTree   +-- is-installed-globally@0.1.0
125 silly saveTree   +-- lazy-ass@1.6.0
125 silly saveTree   +-- listr@0.14.3
125 silly saveTree   +-- lodash@4.17.15
125 silly saveTree   +-- log-symbols@3.0.0
125 silly saveTree   +-- minimist@1.2.2
125 silly saveTree   +-- moment@2.24.0
125 silly saveTree   +-- ospath@1.2.2
125 silly saveTree   +-- pretty-bytes@5.3.0
125 silly saveTree   +-- ramda@0.26.1
125 silly saveTree   +-- request-progress@3.0.0
125 silly saveTree   +-- supports-color@7.1.0
125 silly saveTree   +-- tmp@0.1.0
125 silly saveTree   +-- untildify@4.0.0
125 silly saveTree   +-- url@0.11.0
125 silly saveTree   `-- yauzl@2.10.0
126 verbose stack Error: spawn git ENOENT
126 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
126 verbose stack     at onErrorNT (internal/child_process.js:456:16)
126 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
127 verbose cwd F:\CypressAutomation
128 verbose Windows_NT 6.3.9600
129 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cypress" "--save-dev"
130 verbose node v12.13.1
131 verbose npm  v6.12.1
132 error code ENOENT
133 error syscall spawn git
134 error path git
135 error errno ENOENT
136 error enoent Error while executing:
136 error enoent undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
136 error enoent
136 error enoent
136 error enoent spawn git ENOENT
137 error enoent This is related to npm not being able to find a file.
138 verbose exit [ 1, true ]

**Comment by errohitrana2013** [comment] 2020-03-26 10:04
not able to install the cypress 
i used this command.
after creating the package  by > npm init
i used > npm install cypress --save-dev
getting above issue.

**Comment by jennifer-shehane** [comment] 2020-03-26 10:43
Likely duplicate of #6807

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

**Closed by jennifer-shehane** 2020-03-26 10:43 UTC
