### ISSUE TITLE
3.5.0 Error: write EPROTO 3343909432:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569:

### ISSUE THREAD

**Issue by natkrish** [cypress-io/cypress#5446] opened 2019-10-24 14:01 UTC
# Current behavior:

I upgraded my cypress version from 3.4.1 to 3.5.0. All my tests were working fine on 3.4.1 but when running on 3.5.0 - I get errors see attached screenshot. 

### Desired behavior:

I should be able to run my tests without any problems. 

### Steps to reproduce: (app code and test code)

Unfortunately, I dont have the time to create a dummy project just for this issue. I am sure its to do with version 3.5.0. Please fix it ASAP 

### Versions
Cypress : 3.5.0
OS: Windows 10
Browser: Chrome 77
Node: 11.7.0
![image](https://user-images.githubusercontent.com/12541984/67492546-7e75de00-f66e-11e9-9420-2758118a559a.png)
![image](https://user-images.githubusercontent.com/12541984/67492962-1e336c00-f66f-11e9-8852-117e89a56400.png)

**Comment by jennifer-shehane** [comment] 2019-10-24 14:30
@natkrish Thanks for opening an issue. Without a reproducible example, this issue will take longer to fix without this because we have to find the exact circumstances this fails.

Could you provide any more details surrounding your project and this test. 

- Are you behind a proxy?
- You are writing `cy.request()` - are you passing any options?
- Do you have any options sent to `cy.server()` that overwrite defaults?
- What is the expected result of your `cy.request()`? 200, 300?? 
- Does the url usually do any redirects?
- Is the url `http` or `https`
- Do you have any special SSL configuration?

**Comment by natkrish** [comment] 2019-10-24 14:56
@jennifer-shehane  thanks for your response. I understand that its not possible to reproduce without a working example - may be when i get sometime I will try and do a simple example. 
Are you behind a proxy?
Yes

You are writing cy.request() - are you passing any options?
Yes I use it but with no options. But i wasn't executing that test. 

Do you have any options sent to cy.server() that overwrite defaults?
Yes I use it but with no options. But i wasn't executing that test. 

What is the expected result of your cy.request()? 200, 300??
I am not sending cy.request();

Does the url usually do any redirects?
Nope

Is the url http or https
https:

Do you have any special SSL configuration?
not really

**Comment by natkrish** [comment] 2019-10-24 14:57
I was able to run the same tests in 3.4.1 with success. But with 3.5.0 its not even trying to open the url.

**Comment by jennifer-shehane** [comment] 2019-10-24 15:12
Sorry @natkrish, I assumed this was an error from a `cy.request()` just from the messaging of the error. This is happening during a `cy.visit()`?

**Comment by natkrish** [comment] 2019-10-24 15:15
Yes it is happening when i start my tests with cy.visit('/') - and I have set up the base url in cypress.json

**Comment by itsnathandaily** [comment] 2019-10-25 09:56
I upgraded to 3.4.1 and I'm having the same issue

**Comment by flotwig** [comment] 2019-10-25 16:45
`boringssl` is the custom OpenSSL-alike implementation Electron uses (also bundled with Chromium): electron/electron#20204

We had a similar issue with certain certs that was a result of a bug in the version of OpenSSL bundled with Node in 3.4.1. Updating Node should've fixed that. We also updated Electron from 2 to 5 in 3.5.0, and in Electron 4, they switched from OpenSSL in Node to `boringssl`.

You can see issues with `boringssl` in Electron here: https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+boringssl

@natkrish @itsnathandaily Can one of you share a URL that shows this behavior when `cy.visit()`ed? It would be a big help to track this down.

**Comment by natkrish** [comment] 2019-10-29 10:36
@flotwig - unfortunately, its not possible for me to share the url reason being I was using our internal test environments which works fine with 3.4.1. That site pretty much looks similar to this one - so may be you can use it to test cy.visit(). https://onlinedoctor.lloydspharmacy.com/

**Comment by flotwig** [comment] 2019-10-29 21:37
@natkrish I tried running this test, and it works:

```js
it('', () => {
  cy.visit('https://onlinedoctor.lloydspharmacy.com/')
})
```

Is there a difference in how you generate certs for production and development? It could be some weird cipher suite or option you're using in your development certificate conflicting with Electron.

**Comment by GarthyCheang** [comment] 2019-10-31 10:32
I have this problem. this case maybe CA is old. Chrome can show “Your connection is not private“ Warning in new version. 

  "chromeWebSecurity": false  in cypress.json

this setting is not work, how to miss this warning?? @jennifer-shehane

**Comment by flotwig** [comment] 2019-10-31 14:24
@GarthyCheang Are you talking about this?

![image](https://user-images.githubusercontent.com/1151760/67955210-9dbdbf80-fbc8-11e9-88e0-18129fed9f1d.png)

^ That's normal, that's just there because Cypress uses it's own CA to intercept HTTPS traffic for tests.

**Comment by GarthyCheang** [comment] 2019-11-01 01:26
@flotwig yes! Cypress show network issue, and then can't testing the app

**Comment by natkrish** [comment] 2019-11-05 11:34
@flotwig @jennifer-shehane  After updating cypress to 3.6.0 version i no longer get this issue anymore. Hence closing this ticket for now.

**Comment by Mkots** [comment] 2019-11-05 11:37
I still have this issue even on "cypress": "3.6.0", and Chrome 78

**Comment by yanashapkatest** [comment] 2019-11-06 10:14
I am having the same issue. (3.6.0) 
{code}
Error: write EPROTO 3839146440:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16)
{code}

**Comment by jennifer-shehane** [comment] 2019-11-06 13:44
Reopening since people seem to still be having this issue.

**Comment by Sigalsha** [comment] 2019-11-07 09:11
Same thing for me:
I upgraded my cypress version from 3.4.1 to 3.6.0. All my tests were working fine on 3.4.1 but once I upgraded to 3.6.0 - I get errors when using cy.request() and even cy.visit():

**cy.visit()** :
![image](https://user-images.githubusercontent.com/28334441/68375191-0ec42080-014f-11ea-9666-1daf6a5d7f1f.png)
![image](https://user-images.githubusercontent.com/28334441/68375211-1be10f80-014f-11ea-985c-bb213ea39c0b.png)

**cy.request()** :
![image](https://user-images.githubusercontent.com/28334441/68375254-31eed000-014f-11ea-9af9-04a52fd3a2a9.png)
![image](https://user-images.githubusercontent.com/28334441/68375276-3adfa180-014f-11ea-943b-1dd4a91657b4.png)
![image](https://user-images.githubusercontent.com/28334441/68375289-429f4600-014f-11ea-8264-615f89015571.png)

**Comment by flotwig** [comment] 2019-11-07 20:03
@Mkots I tried to use mkcert to generate a cert that would reproduce this issue, but couldn't get Electron to throw the unsupported_protocol error even with a mkcert cert.

Can you please check out my repo and let me know what the difference is between my `gen-cert.sh` and the command *you* use to generate testing certificates?

https://github.com/flotwig/electron-boringssl-repro

**Comment by flotwig** [comment] 2019-11-07 20:10
For anyone experiencing this issue - if you can try running your tests with [debug logs enabled][debug], and share those logs here, it will show some more information which we can use to get to the root of the issue.

* On Linux/macOS: `DEBUG=cypress:* cypress ...`
* On Windows: `npx cross-env DEBUG=cypress:* cypress ...`

Make sure to scrub any private data from the logs before sharing here.

[debug]: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

**Comment by mutongwu** [comment] 2019-11-13 12:21
+1

it happens when visit self-signed certificate website.

**Comment by vrodnyanskiy** [comment] 2019-11-21 23:19
Same here in 3.6.1
Was working in 3.4.1

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

RequestError: Error: write EPROTO 140723175747320:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569:

    at new RequestError (/Users/vrodnyanskiy/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/vrodnyanskiy/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/vrodnyanskiy/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/vrodnyanskiy/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)
    at Request.emit (events.js:194:13)
    at Request.onRequestError (/Users/vrodnyanskiy/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:199:15)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:194:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at internal/streams/destroy.js:49:7
    at TLSSocket.Socket._destroy (net.js:600:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:12)

**Comment by natkrish** [comment] 2019-12-05 10:46
@jennifer-shehane I think this is still an issue on my side too with version 3.7.0. The good thing is it doesnt throw this error when running local but happens when running it on jenkins. 
![image](https://user-images.githubusercontent.com/12541984/70228561-72d90500-174c-11ea-8631-c1829eece5d6.png)

**Comment by Mkots** [comment] 2019-12-05 10:54
@flotwig Sorry for the late reply, now I can't reproduce this behaviour, I think this error was connected with my environment, unfortunately, I don't know any concrete causes

**Comment by nkrishna79** [comment] 2019-12-13 11:41
@jennifer-shehane @flotwig  I think this issue is still happening on 3.8.0 unfortunately.

**Comment by natkrish** [comment] 2019-12-13 14:51
can someone help me with a solution for this issue please? At the moment, i had to downgrade it to 3.4.1 due to this error and i am losing a lot of good features as a result of this.

**Comment by flotwig** [comment] 2019-12-13 15:32
Still looking for DEBUG logs from anyone experiencing this issue:

> For anyone experiencing this issue - if you can try running your tests with [debug logs enabled](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs), and share those logs here, it will show some more information which we can use to get to the root of the issue.
> 
>     * On Linux/macOS: `DEBUG=cypress:* cypress ...`
> 
>     * On Windows: `npx cross-env DEBUG=cypress:* cypress ...`
> 
> 
> Make sure to scrub any private data from the logs before sharing here.

It is probably a result of incompatibility between Electron and certain SSL configurations.

**Comment by nkrishna79** [comment] 2019-12-16 16:32
@flotwig here is the debug output. I havent formatted it to be honest and according to me there is no sensitive information on it. You can use the full to investigate. Let me know if you need more info. 
[ConEmu-2019-12-16-p3516.log](https://github.com/cypress-io/cypress/files/3969109/ConEmu-2019-12-16-p3516.log)

**Comment by nkrishna79** [comment] 2019-12-17 11:33
@flotwig any luck with the investigation?

**Comment by fourthmeal70** [comment] 2019-12-18 16:22
I'm also experiencing this issue. It runs fine locally on an unsecure domain (i.e.  http://) however as soon as I run it in my testing environment which has a self-signed SSL cert, all tests fail with the error in this issues title.

**Comment by natkrish** [comment] 2019-12-19 11:19
@fourthmeal70 thats right. I am kind of stuck with 3.4.1 and not be able to use the latest and best features in version 3.8.0. I am hoping that the cypress team investigates this sooner than later. @jennifer-shehane @flotwig

**Comment by itsnathandaily** [comment] 2019-12-19 19:14
This is still a problem with version 3.8.0

**Comment by flotwig** [comment] 2019-12-19 22:32
Do any of you have a public website that I can use to reproduce this issue? I think it's related to specific SSL configurations.

**Comment by nkrishna79** [comment] 2019-12-20 10:46
@flotwig unfortunately, it doesnt happen on any site thats available to public. it happens on our internal test environments. So if you can find any self signed certificate site, then you should be able to reproduce.

**Comment by fourthmeal70** [comment] 2019-12-20 13:35
@flotwig My tests run just fine when pointed to my public site as it's using a public certificate. As @natkrish has said, it seems to only happen on environments that use self signed certificates which is what all of our internal environments use.

**Comment by flotwig** [comment] 2019-12-20 14:51
@nkrishna79 @fourthmeal70 Gotcha. Could you please share how you generated your self signed certs? All commands used, parameters given, etc.

**Comment by nkrishna79** [comment] 2019-12-20 15:01
@flotwig this is going to be tricky because I dont have access to do this on our servers. Its normally done by the Dev ops team. May be @fourthmeal70  does?

**Comment by fourthmeal70** [comment] 2019-12-31 18:02
@flotwig I apologize for taking so long to reply. I am not on the team that generally creates our certs so I don't know the steps taken to generate our self signed certs however, I've asked the team that does for the information and am waiting for their reply. 

I also came across this issue: https://github.com/cypress-io/cypress/issues/771  I wonder if the changes to fix that somehow caused the error we're facing now.

**Comment by fourthmeal70** [comment] 2020-01-03 16:14
@flotwig All I know so far is our certs are generated with Microsoft's Active Directory Cert services. I don't know any details beyond that.

**Comment by cjones2-sandia** [comment] 2020-01-06 15:20
My team has encountered this error in an internal-only project, and I have noticed a potentially useful data point. We have two environments, one "old" with out-of-date infrastructure and one "current" with up-to-date infrastructure. This error only appears when running against the "old" environment, which happens to have TLS 1.0 running. The "current" environment (which works great) has TLS 1.2.

I am suspicious that the error is tied to the TLS version in some way.

**Comment by nkrishna79** [comment] 2020-01-07 16:39
@bahmutov - it will be great if you can take this issue on board and see what you can do about it. At the moment, it’s been difficult to set up a demo project to showcase this issue however on the negative side I am not able to use the latest version of cypress due to this bug. Can you please investigate it?

**Comment by bahmutov** [comment] 2020-01-07 17:03
We really cannot solve this problem without a reproduction

**Comment by nkrishna79** [comment] 2020-01-07 18:05
@bahmutov well it’s a bit tricky to reproduce because it happens only on internal test environment. I am not sure how other cypress users are overcoming this problem at their end. If you can schedule someone to come on a video call may be we can solve this issue?

**Comment by flotwig** [comment] 2020-01-07 18:59
@nkrishna79 (or @fourthmeal70, or @cjones2-sandia, or anyone else with this issue) - here is a command which will give a bunch of information about the SSL configuration in place, which we can use to establish a pattern of what causes this issue.

Please run it against the site that fails to load in Cypress and share the output here.

It will require having the `openssl` command line tool installed.

```
openssl s_client -showcerts -connect your-site-here.com:443
```

**Comment by nkrishna79** [comment] 2020-01-07 19:19
@flotwig thanks for much. I will definitely run it tomorrow as soon as I get into work and will pass you the information.

**Comment by natkrish** [comment] 2020-01-08 10:39
@flotwig I have sent you an email with the output from running the above command. Please do let me know upon receipt.

**Comment by fourthmeal70** [comment] 2020-01-08 15:47
[opensslOutput.txt](https://github.com/cypress-io/cypress/files/4036072/opensslOutput.txt)

Attached is the output when I run the command against our internal site.

**Comment by fourthmeal70** [comment] 2020-01-08 21:31
After reading what @cjones2-sandia said about TLS versions, I pointed our cypress to test to another internal site that uses TLS 1.2 and the tests worked fine. Pointing them back to our normal development server which only supports TLS 1.0 and the tests fail with the error here. I also believe that the issue has something to do with the TLS version.  I've asked our devOps team to upgrade our development servers and will report back if things start working when they do.

**Comment by flotwig** [comment] 2020-01-08 22:53
The openssl output I received from @natkrish also used TLSv1, I also suspect that using TLSv1 could be what triggers this bug.

**Comment by fourthmeal70** [comment] 2020-01-09 01:16
@flotwig What you had was real close! I was able to reproduce the error with this node server: 

`const https = require('https')
const cert = require('https-pem')

const port = process.env.PORT || 12345

const server = https.createServer({
   //secureProtocol: 'TLSv1_2_server_method',
   secureProtocol: 'TLSv1_server_method',
  ...cert
}, (req, res) => {
  res.setHeader('content-type', 'text/html') // required by Cypress cy.visit
  res.end('foo')
})

server.listen(port, () => {
  console.log(`listening at https://127.0.0.1:${port}`)
})`

Run it as is and then hit with cy.visit(), you'll see the error.  Then swap the secureProtocol setting to use TLSV1.2 and run the same cy.visit() and page loads successfully.

**Comment by natkrish** [comment] 2020-01-09 09:57
@flotwig do you think a fix is possible or should this be reported upstream? Will be good to know who is responsible for fixing this so that I can make some decisions regarding staying put with 3.4.1 (this is the only cypress version which works with TLS1)

**Comment by flotwig** [comment] 2020-01-09 15:57
> Run it as is and then hit with cy.visit(), you'll see the error. Then swap the secureProtocol setting to use TLSV1.2 and run the same cy.visit() and page loads successfully.

@fourthmeal70 Nice, got it working. I notice that I get this error:

```
Error: write EPROTO 1942426598472:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 70
```

Which is different from the error in the OP, which was:

```
Error: write EPROTO 3343909432:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569: 
```

So I wonder if this is actually an accurate representation of the real issue.

Still, we can fix this in Cypress by updating the network code to pass a `minVersion` of `TLSv1` (the default is `TLSv1.2`). I'll open a PR.

---

> do you think a fix is possible or should this be reported upstream?

@natkrish See above - we can fix the `TLSV1_ALERT_PROTOCOL_VERSION`, but without a reproducible example for the `UNSUPPORTED_PROTOCOL` error, it's uncertain if this will also fix the `UNSUPPORTED_PROTOCOL` error.

**Comment by nkrishna79** [comment] 2020-01-09 16:31
@flotwig definitely I will it pull it down and report back either tonight or tomorrow AM. Thanks so much for this investigative and fixing work. Much appreciated. Hopefully it will work. Fingers crossed!

**Comment by fourthmeal70** [comment] 2020-01-09 17:41
@flotwig Good catch! I was just excited that an error appeared.. obviously I didn't look closely enough at it haha. 

Anyway, I pulled down your PR and tested on my end and everything appears to work! 🎉 
So it looks like the change may have fixed both errors we've now seen. I'm interested to see if @natkrish gets the same results.

**Comment by nkrishna79** [comment] 2020-01-09 17:51
@fourthmeal70 if you don’t mind can you let me me know the steps that you took to do a pull down? Sorry this is my first time with PR stuff hence asking.

**Comment by flotwig** [comment] 2020-01-09 18:31
> @fourthmeal70 if you don’t mind can you let me me know the steps that you took to do a pull down? Sorry this is my first time with PR stuff hence asking.

You should just be able to clone the repo, checkout my branch, `npm i`, and start it. Like this:

```shell
git clone https://github.com/cypress-io/cypress.git
cd cypress
git checkout issue-5446-tlsv1-fix
npm i
npm run cypress:open  # same as `cypress open`, use `cypress:run` if you want to test `cypress run`
```

**Comment by natkrish** [comment] 2020-01-09 18:36
@flotwig thanks. Working on it. Will let you know shorly.

**Comment by natkrish** [comment] 2020-01-09 21:43
@flotwig Yessssssssssssssssssssssssssss I can confirm that it is now working with your fix in place. 👍

**Comment by flotwig** [comment] 2020-01-09 21:46
Awesome, thanks for checking! Will work on getting this merged and released.

**Comment by natkrish** [comment] 2020-01-09 23:01
@flotwig Thanks so much. Looking forward to it.

**Comment by natkrish** [comment] 2020-01-15 10:11
@flotwig how long will it take for cypress to release the next version with this bug fix?

**Comment by flotwig** [comment] 2020-01-16 17:12
@natkrish it should be in 3.8.3 which is scheduled for next Friday

**Closed** 2020-01-16 17:15 UTC
Labels: stage: needs review, type: bug
