### ISSUE TITLE
Add additional flags when running Chrome

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#3633] opened 2019-03-03 22:01 UTC
### Current behavior:

Currently, Cypress is regularly failing inside Docker. This is a known problem, even described in documentation. 

In documentation the workaround is to add `--ipc=host` and there is a link to this issue: #350 

Another solution mentioned is increasing `/dev/shm` size for the container. 

But none of this is a solution one can use on public CI systems where you do not control how Docker container is run.

### Desired behavior:

When rendering large pages using Cypress inside Docker-based CI systems, Cypress should not crash.

### Solution:

Adopt switches used by Google Chrome official puppeteer project. They have various list of switches to fix these and similar problems. See the [list here](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L37):

```
  '--disable-background-networking',
  '--enable-features=NetworkService,NetworkServiceInProcess',
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-breakpad',
  '--disable-client-side-phishing-detection',
  '--disable-default-apps',
  '--disable-dev-shm-usage',
  '--disable-extensions',
  '--disable-features=site-per-process,TranslateUI',
  '--disable-hang-monitor',
  '--disable-ipc-flooding-protection',
  '--disable-popup-blocking',
  '--disable-prompt-on-repost',
  '--disable-renderer-backgrounding',
  '--disable-sync',
  '--force-color-profile=srgb',
  '--metrics-recording-only',
  '--no-first-run',
  '--safebrowsing-disable-auto-update',
  '--enable-automation',
  '--password-store=basic',
  '--use-mock-keychain',
```

Not all are relevant here, but some are. I think it would be great if most of those would be added to Chrome and Electron runners for Cypress, especially when they run inside CI.

The one which seems it will fix the problem with Chrome failing inside Docker-based CI is `--disable-dev-shm-usage`, so at least that one should be added. This is available since Chrome 65.

You could even detect if running inside Docker and set this flag automatically (if you do not want to simply set it always). Or if your run Cypress from command line instead of GUI.

For more information see [tips section here](https://developers.google.com/web/tools/puppeteer/troubleshooting#tips).

**Comment by brian-mann** [comment] 2019-03-04 06:01
We'll take a look at these. You can control which additional command line args get passed to chrome as per documented here: 

https://docs.cypress.io/api/plugins/browser-launch-api.html#Usage

**Comment by mitar** [comment] 2019-03-04 06:16
Interesting. I didn't know that you can already set them. Will have to use installed Chrome browser instead of Electron to be able to use new flags though.

**Comment by Joelasaur** [comment] 2019-03-04 16:28
@brian-mann Those are for arguments to the browser. --ipc=host has to be passed to docker itself, not the browser.

**Comment by Joelasaur** [comment] 2019-03-04 16:33
Yeah I'm only seeing this issue in Electron. I'd like to get this working in our pipeline reliably because the videos produced are invaluable to troubleshooting issues with our application.

**Comment by Joelasaur** [comment] 2019-03-04 16:42
It looks like Chromium found the root cause back in 2016 and has labeled it as "Won't fix"

https://github.com/electron/electron/issues/4491 

So that isn't fun...

**Comment by jennifer-shehane** [comment] 2019-03-06 06:23
Chrome flags can be updated here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.coffee#L21

Adding Electron flags [may or may not be necessary/supported](https://electronjs.org/docs/api/chrome-command-line-switches), but would be added here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/environment.coffee#L26

**Comment by flotwig** [comment] 2019-10-10 14:00
Opened a PR to add all of the args in the above comment (except `--disable-dev-shm-usage`) to Chrome: #5310

It doesn't seem like Electron supports passing any of these: https://electronjs.org/docs/api/chrome-command-line-switches

Adding `--disable-dev-shm-usage` in this commit seems to make the browser sporadically not open: 7247dcfa78ad3e1d0ad032474e724a083007edda Opened a new issue (with workaround) for that flag specifically: #5336

**Closed** 2019-10-10 14:02 UTC
Labels: stage: needs review, stage: work in progress
