### ISSUE TITLE
Wrong formatting of ~ during APIcall with Cypress

### ISSUE THREAD

**Issue by trondag** [cypress-io/cypress#19170] opened 2021-12-01 13:24 UTC
### Current behavior

It looks like the first ~ (tilde) is formatted into %5Cx7e. It should not change it into anything. The next tilde is not touched, which is correct.

I just tested with 8.7.0 and 9.1.0, and this bug is present in 9.1.0

### Desired behavior

Not convert the first tilde to this %5Cx7e

### Test code to reproduce

    cy.request({
        url: 'randomwebpage.com',
        method: "POST",
        body: {
            test: "~~~",
        },
    })

### Cypress Version

9.1.0

### Other

The test code outputs `Body: {"test":"\x7e~~"}`, should output `Body: {"test":"~~~"}`

**Comment by janhesters** [comment] 2021-12-01 22:11
We have the same, our Cypress tests are failing after the upgrade because of authentication schemes that are no longer working. (Our [cookie serialization has a version number](https://github.com/vvo/iron-session/issues/436) `~2`.)

**Comment by chrisbreiding** [comment] 2021-12-02 14:48
Duplicate of #19115

**Closed by chrisbreiding** 2021-12-02 14:48 UTC
