### ISSUE TITLE
Append custom headers to all requests

### ISSUE THREAD

**Issue by TUNER88** [cypress-io/cypress#8165] opened 2020-08-03 20:43 UTC
### Current behavior:

Right now I can add custom headers only to the main `cy.visit()` requests and subsequent XHR requests.

### Desired behavior:

I would like to add custom headers to all subsequent requests like images and other assets

### Versions

Cypress `4.11.0`, any browser and any OS

Is there anyway how I can override the default behaviour?

**Comment by jennifer-shehane** [comment] 2020-08-18 12:04
This will be part of the work in #687. Closing as duplicate of #687

**Closed by jennifer-shehane** 2020-08-18 12:04 UTC
Labels: stage: proposal 💡, topic: network
