### ISSUE TITLE
connectToNewSpec is still happening

### ISSUE THREAD

**Issue by matanbanin** [cypress-io/cypress#27241] opened 2023-07-09 08:06 UTC
### Current behavior

Still reproducing https://github.com/cypress-io/cypress/issues/24650 in 12.17.0

### Test code to reproduce

Really difficult to do, sorry. It's intermittent, and it's a fairly large, sensitive, code-base.

### Cypress Version

12.17.0

### Node version

18.16.1

### Operating System

 Ubuntu   22.04.2

### Debug Logs

```shell
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in connectToNewSpec
Error: Missing browserCriClient in connectToNewSpec
    at Object.connectToNewSpec (<embedded>:4580:47339)
    at Object.connectToNewSpec (<embedded>:4580:25729)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async v.relaunchBrowser (<embedded>:4646:397035)
```

**Comment by nagash77** [comment] 2023-07-10 13:33
Hi @matanbanin Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Or check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Closed as not planned by nagash77** 2023-07-10 13:33 UTC

**Comment by matanbanin** [comment] 2023-07-10 14:04
But why not reopening the old issue? it's clearly not fixed. I know there is not a lot information to reproduce but at least can we go to the previous step?

**Comment by nagash77** [comment] 2023-07-10 16:31
@matanbanin if you have an example that would help us reproduce this behavior please share.  But at this point we don't have any new information to go off of to reopen this investigation.

**Comment by jazpearson** [comment] 2023-07-12 11:48
We are also still seeing this one, unfortunately. I came to write up a new issue and found one already created.

A user from the old issue mentioned that they would be willing to help out with their code-base: https://github.com/cypress-io/cypress/issues/24650#issuecomment-1495553736

**Comment by jazpearson** [comment] 2023-07-12 11:50
@AtofStryker also mentioned to open a new issue if this was still happening.

**Comment by AtofStryker** [comment] 2023-07-12 14:59
@jazpearson I was hoping that the fixes in `12.17.0` would fix this. This still sounds like an issue, but I'm wondering on ways to reproduce it. Any ideas?

**Comment by jazpearson** [comment] 2023-07-13 09:26
@AtofStryker unfortunately, i don't have an idea why this happens. There was a user from this comment who said they would be able to help out though: https://github.com/cypress-io/cypress/issues/24650#issuecomment-1495553736

**Comment by matanbanin** [comment] 2023-07-26 09:51
I have tried decreasing the RAM consumption of my machine, and it happends a lot less right now.
Maybe it is possible to reproduce with tons of RAM usage (i have dozens of containers running in the same runner)

**Comment by jazpearson** [comment] 2023-07-26 10:06
How did you do that?

**Comment by jazpearson** [comment] 2023-07-26 10:07
> I have tried decreasing the RAM consumption of my machine, and it happends a lot less right now. Maybe it is possible to reproduce with tons of RAM usage (i have dozens of containers running in the same runner)

How did you do that?

**Comment by jazpearson** [comment] 2023-07-27 08:06
@AtofStryker is it possible the issues could be caused by multiple instances of cypress running on the same machine? I think our Jenkins machines allow 2 builds at a time, so in theory, we could have 2 sets of cypress tests running on the same machine at the same time........ just a thought?

**Comment by jazpearson** [comment] 2023-07-27 08:27
I just checked failures from just now and only one instance of cypress was running on each machine, so that debunks that theory.

**Comment by jazpearson** [comment] 2023-07-27 09:38
Not sure if this helps, but i added `DEBUG=cypress:server:util:process_profiler` to the run
![image](https://github.com/cypress-io/cypress/assets/7648154/88977c5a-cfa3-47a5-b190-29f541b626ad)

**Comment by jazpearson** [comment] 2023-08-03 13:04
I've tried using Edge as the browser and this seems A LOT more reliable than chrome. I'd prefer to keep using chrome because that's what most people are using, but at least this gets us moving again.

As we've been adding more and more tests, cypres has become more and more unreliable. I've actually parallelised the tests and running tests across multiple machines in the hope to avoid getting this crash, but it's not made much difference. 

We have got to the point where we are getting a crash in 80% of our pipeline builds, which is unsustainable. So switching to Edge seems like the only option. 

We can't switch to Firefox either. because we can't disable web security like we can in chromium based browsers.
