### ISSUE TITLE
.should(callbackFn) changes parameter of callback value on assertion retry

### ISSUE THREAD

**Issue by lionwolfdev** [cypress-io/cypress#22883] opened 2022-07-21 12:47 UTC
### Current behavior

Given the attached simplified application and the Cypress test specification, the second test case fails due to a timeout when Cypress' automatic retries for `.should()` fails the first assertion of `$elements` to have a length of two with the following message:

![grafik](https://user-images.githubusercontent.com/80899291/180212579-7bdebfdd-ae5f-438d-a72f-50f055a1c2db.png)

`console.log($elements)` yields that `$elements` indeed changed from being an array of elements to an individual `<input>`, therefore not having a `.length` property, resulting in the `undefined` value.

![grafik](https://user-images.githubusercontent.com/80899291/180214169-2cd02c9a-17e9-405e-ac66-1a5da757ce20.png)

### Desired behavior

Cypress should not change the value of the callback function's parameter between the automatic retries or clarify this behaviour in the documentation.

### Test code to reproduce

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<div>
  <input data-cy="my-input" placeholder="My input 1">
  <input data-cy="my-input" placeholder="My input 2">
</div>
</body>
</html>
```

```js
describe('Replicate issue', () => {
  it('passes', () => {
    cy.visit('test.html')
    cy.get('[data-cy="my-input"]').should(($elements) => {
      console.log('Test case 1', $elements) // is as expected, prints an array of two jQuery elements
      expect($elements).to.have.length(2)
    })
  })

  it('fails', () => {
    cy.visit('test.html')
    cy.get('[data-cy="my-input"]').should(($elements) => {
      console.log('Test case 2', $elements) // <-- will print an array once at the beginning only, then prints a single <input>
      expect($elements).to.have.length(2) // <-- assertion fails because $elements becomes an individual (single) <input>
      $elements.each((i, $e) => {
        cy.wrap($e).should('be.visible').type('hello')
      })
    })
  })
})
```

### Cypress Version

10.3.1

**Comment by tbiethman** [comment] 2022-07-22 16:14
@lionwolfdev thank you for the ticket, this is interesting. The nested cy commands within the `should` callback seem to confuse the outer scope and override the subject. But based on how Cypress commands are enqueued and retried, this is behaving like I'd expect.

Our docs around [`should`'s callback function](https://docs.cypress.io/api/commands/should#Function) do warn about executing side-effects inside the callback. While the `.type('hello')` command is definitely a side effect, I don't necessarily think `.wrap()` or `.should()`  are perceived that way. We'll have to discuss more to determine a resolution.

In general, for this example test case, using `then` for the outer scope would be more appropriate:

```js
  it('passes', () => {
    cy.get('[data-cy="my-input"]').then(($elements) => {
      $elements.each((i, $input) => {
        cy.wrap(Cypress.$($input)).should('be.visible').type('hello') // all good
      })
    })
  })
```

**Comment by nagash77** [comment] 2022-10-24 20:02
@lionwolfdev Upon further internal discussion we have decided to close this issue as intended behavior.  We agree we can update our docs to better clarify why you should follow @tbiethman pattern.  Thank you for bringing this subtly up for discussion!

**Closed by nagash77** 2022-10-24 20:02 UTC
Labels: type: bug, E2E-core, stage: fire watch, routed-to-e2e
