### ISSUE TITLE
AssertionError: Timed out retrying: expected 'chrome-error://chromewebdata/'

### ISSUE THREAD

**Issue by LMPrashkbk** [cypress-io/cypress#8457] opened 2020-09-01 02:37 UTC
### Current behavior:

Login to website 
1.Run login page
2.Run another page with login
 

### Desired behavior:

Both pages should run but I'm getting this error

Already added chromewebsecurity:false still getting this error

**Comment by jennifer-shehane** [comment] 2020-12-18 02:41
Duplicate of https://github.com/cypress-io/cypress/issues/4220

**Closed by jennifer-shehane** 2020-12-18 02:41 UTC
