### ISSUE TITLE
I can´t start dashboard

### ISSUE THREAD

**Issue by narayana108** [cypress-io/cypress#2852] opened 2018-11-28 21:04 UTC
Operating System: win10 x64
cypress version 3.1.2

### Current behavior:
I am starting cypress with npm run test command because using cypress open or run is giving me errors that the file already exists...  like it is here:   https://github.com/cypress-io/cypress/issues/1125
I have overcomed this with using script in package.json

now if I use the command  cypress run --record --key <key> 

I got the same error....
![cypress](https://user-images.githubusercontent.com/33807475/49182193-dd957a80-f359-11e8-98bd-c2534749bcb0.png)

### Desired behavior:

It should start recording your test

### Steps to reproduce:

run cypress, copy the command from Test runner under Runs, and run the command cypress run --record --key <'key'>

### Versions

I am using cypress 3.1.2 . Windows 10 x 64 and latest chrome browser

**Comment by jennifer-shehane** [comment] 2018-11-29 11:03
Duplicate of https://github.com/cypress-io/cypress/issues/1099

**Closed by jennifer-shehane** 2018-11-29 11:03 UTC

**Comment by narayana108** [comment] 2018-11-29 11:10
> Duplicate of #1099

The issue zou have sent is an issue with starting the server, not with the dashboard.

**Comment by jennifer-shehane** [comment] 2018-11-29 11:34
The error in the other issue also occurs during `cypress run`. Does this issue only happen when passing the `--record` and `--key` flags?

**Comment by narayana108** [comment] 2018-11-29 12:38
also durring cypress run

**Comment by narayana108** [comment] 2018-11-29 12:39
> The error in the other issue also occurs during `cypress run`. Does this issue only happen when passing the `--record` and `--key` flags?

also durring cypress run
