### ISSUE TITLE
Videos not recording complete test in cypress version 6.0.0

### ISSUE THREAD

**Issue by alokverma75** [cypress-io/cypress#9342] opened 2020-11-26 04:17 UTC
Hi,

I upgraded cypress version to 6.0.0 and tried running my test to upload videos but somehow video duration before compression is 14 seconds and after compression is 0 seconds. it shows video having screen : Your tests are loading. Before this it was working fine. I tried setting videoCompression: false but uploaded video is just for 1 sec showing your tests are loading though tests run for around 14 seconds but not complete video is getting completed. 

![image](https://user-images.githubusercontent.com/54471085/100307949-2aee6600-2fcd-11eb-9f69-040ad93b80e6.png)

 (Results)
![image](https://user-images.githubusercontent.com/54471085/100308916-80c40d80-2fcf-11eb-84fd-1a339f9f6cf0.png)

We tested the same from two diff dashboard accounts and different machines but result was same.

And after reverting to 5.6 and setting videoCompression to false it started working again. So there is some problem in compression for 6 version

**Comment by mfittko** [comment] 2020-11-26 08:21
I can confirm this, all videos recorded with the chrome or electron browsers look like this. When I open them in chrome they even show like a couple of seconds but they are in fact only a fraction of a second long with that default blank page. Interestingly it works with the firefox browser option. CI and me are on linux debian/ubuntu. If you need more debugging info, tag me.

**Comment by pmcochrane** [comment] 2020-11-26 12:11
Same for me. Videos work in 5.6.0 but not in 6.0.0

**Comment by jennifer-shehane** [comment] 2020-11-26 14:27
Duplicate of https://github.com/cypress-io/cypress/issues/9265

**Closed by jennifer-shehane** 2020-11-26 14:27 UTC
