### ISSUE TITLE
WebSocket unclean close due and "Chrome didn't shut down correctly." when running tests using cypress run

### ISSUE THREAD

**Issue by speedwellsoftware** [cypress-io/cypress#8285] opened 2020-08-14 18:45 UTC
### Current behavior:

When running tests using `cypress open` there are no issues.
When running tests using `cypress run --browser chrome` we have issues with WebSocket forcibly closed and chrome didn't shut down correctly dialog appears on the next spec:

![image](https://user-images.githubusercontent.com/14232761/90282306-07f8d580-de66-11ea-9f7b-e0adb1fe17da.png)

### Desired behavior:

Even if running each spec on a separate browser session, this session should gracefully close without breaking Chrome functionality like closing websockets and not flagging a clean shutdown.

### Test code to reproduce

`cypress run --browser chrome --config numTestsKeptInMemory=2`

### Versions

Cypress 4.12.1
Chrome 84.0.4147.125

**Comment by t00** [comment] 2020-08-16 11:10
I tried above with chrome --headless and the result is the same. The problem is bigger than I previously thought, I am unsure about cypress internals but it seems requests are somehow proxied to the browser and after a few tests they are stuck and stopping tests using Ctrl+C generates a bunch of previously waiting requests. We open a websocket connection after user signs in for notifications, can it cause tests to fail and chrome not being able to shut down correctly?

I tried electron and firefox - no similar issues with cypress run, both headless and not, but we cannot switch to electron, even temporarily, as it does not allow setting browser's language ( --lang) to a value and we depend on non - en_US locale for tests.

We cannot disable websockets for testing as it is an integral part of our app. May I ask about few ideas I want to try but I am unsure how?

1. How to execute cypress run on chrome without running specs in separate browser sessions? This should prevent (re) opening of websocket and cypress proxy (is there such a thing?) might better cope with ws open/force close for each test.
2. How to reset cypress connection after each spec? This should prevent it holding connections between tests (or is it a bug itself?)
3. How to reliably set electron lang=en_GB in a way other than faking navigator properties as it is not enough for full intl compatibility?

**Comment by jennifer-shehane** [comment] 2020-08-17 07:00
@t00 

1. Running several specs within a single browser session is not possible during `cypress run`. And yes, Cypress proxying requests is a huge part of the internals.
2. This would appear to be a bug if any state from a previous run spec is causing failures in the newly opened spec. Can you provide a reproducible example of a repo using websockets where this is occuring?
3. I'm not sure this is possible in Electron, there was some discussion here on the topic of language: https://github.com/cypress-io/cypress/issues/7890

**Comment by jennifer-shehane** [comment] 2021-02-26 23:53
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-26 23:53 UTC
Labels: stage: needs information
