### ISSUE TITLE
Failing spec requests

### ISSUE THREAD

**Issue by hangvar** [cypress-io/cypress#2624] opened 2018-10-17 12:01 UTC
### Current behavior:

When initializing Cypress makes requests to the spec files that fails intermittenly which usually consumes between 1-5 seconds before the actual tests start. When rerunning the tests without closing the electron window the requests are quick and do not fail.

![image](https://user-images.githubusercontent.com/1937005/47084432-c66c5480-d213-11e8-8e2e-fe428d7cf911.png)

### Desired behavior:

There should be no failing spec requests when running Cypress tests.

### Steps to reproduce:

Checkout https://github.com/hangvar/cypress-reproduce-error and do: 

yarn install
ng serve
yarn cy:open

### Versions
Cypress 3.1.0, Windows 10, Electron 59.

**Comment by jennifer-shehane** [comment] 2018-10-17 21:04
I'm unable to reproduce this locally on my Mac. 

Are you reloading the entire browser? Or are you clicking the 'refresh' button within the Cypress command log?

May I also ask what this if statement is for within your `navigateTo` custom command? https://github.com/hangvar/cypress-reproduce-error/blob/master/cypress/support/commands.ts#L5

**Comment by hangvar** [comment] 2018-10-18 06:31
Funny that you can't reproduce it, I can on my machine and my colleague could also reproduce it from the same code on his computer. 

The navigateTo was written by a developer who has quit and I thought it was a convenience method for shortening the urls we enter, but as we use it it seems to be syntactic sugar for cy.visit. But the problem I'm refering to is happening before the navigateTo and I get the same behaviour when doing cy.visit in the example code, so it seems as not significant to the problem.

I will check and see if I can reproduce it locally on my Mac tonight at home. Do you have any virtualization environment to see if you can reproduce it in Windows?

**Comment by hangvar** [comment] 2018-10-18 06:55
After some experimenting I can see that navigateTo is a hack to save some lead time between different tests. I think the Angular application is reloaded in a thorough way if we would use cy.visit, but due to the manipulation of the window.location.hash property that doesn't happen. Anyway, it should not be part of the problem following my argumentation above.

**Comment by hangvar** [comment] 2018-10-18 19:20
I'm afraid it's reproducible on my Macbook as well (OSX 10.13.6):

![image](https://user-images.githubusercontent.com/1937005/47178465-9c9e5500-d31b-11e8-93fb-335d9c26d67f.png)

**Comment by jennifer-shehane** [comment] 2019-07-23 15:24
I see that you are using an older version of Cypress. Could you update to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? Your issue may have already been fixed. Thanks!

**Comment by jennifer-shehane** [comment] 2022-04-08 13:49
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 13:49 UTC
Labels: stage: needs investigating
