### ISSUE TITLE
plugins/index CoffeeScript file support

### ISSUE THREAD

**Issue by laurentpayot** [cypress-io/cypress#2046] opened 2018-06-27 11:18 UTC
### Current behavior:

If I use a CoffeeScript file as plugins/index.coffee the file is not transpiled as I get an hash-prefixed-comment syntax error, even if the error message says "_The pluginsFile must be a .js or .coffee file._".

```
 Can't start server
The plugins file is missing or invalid.

Your pluginsFile is set to '/home/laurent/projects/myproject/cypress/plugins/index.coffee', but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.

Please fix this, or set 'pluginsFile' to 'false' if a plugins file is not necessary for your project.

The following error was thrown:

/home/laurent/projects/myproject/cypress/plugins/index.coffee:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { # ***********************************************************
^

SyntaxError: Invalid or unexpected token
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10)
at Module._compile (module.js:533:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at module.exports (/home/laurent/.cache/Cypress/3.0.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:104:15)
at Object. (/home/laurent/.cache/Cypress/3.0.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:14:25)
at Object. (/home/laurent/.cache/Cypress/3.0.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:16:3)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
```

I could manually compile my index.coffee file into index.js file, but I had to use the solution described in https://github.com/jashkenas/coffeescript/issues/4769#issuecomment-341492901 to import big CS modules with CS2 import syntax in my tasks definitions.

### Desired behavior:

It would be nice to be able to use a native CS file without manual compilation, and to be able to run it with CS2 `--transpile` Babel options (why not set in cypress.json) to avoid the register transpilation trick described in https://github.com/jashkenas/coffeescript/issues/4769#issuecomment-341492901

### Steps to reproduce:

- use a CoffeeScript file plugins/index.coffee
- add `"pluginsFile": "cypress/plugins/index.coffee"` in cypress.json
- run `cypress open`

### Versions

Cypress 3.0.1
Ubuntu 18.04 LTS
Chromium 66
CoffeeScript 2.3.1
Node 10.0.0

**Comment by chrisbreiding** [comment] 2018-06-27 13:08
Thanks for the bug report. 

I thought this might be an issue with CoffeeScript 2 syntax, but I reproduced it with a pluginsFile as simple as `module.exports = ->`. So CoffeeScript support is indeed busted, regardless of CS version.

**Comment by andreiucm** [comment] 2018-06-27 16:55
It happens to me too. I have the index.js but then I need import a stages.coffe file to set an environment variable `config.env.STAGE = ...`
So I do
`stages = require("..../stages.coffee")`
then 
imported file is simple
```
//stages.coffee 
stages = ["123"]
modules.export = 
    stages: stages
```
But cypress always throw errors saying I have a sintax error in *stages.coffee*
```
//cypress client
                          The following error was thrown:
                                .................
SyntaxError: Unexpected token :
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10) ..............
```

**Comment by brian-mann** [comment] 2018-06-27 17:01
At the moment, all you have to do to fix this is do the same things you'd do in your own node code.

Namely you need to have a regular `index.js` entrypoint, but in that file just require the `coffeescript/register` module and then require your coffee files.

That way, those subsequent requires will go through your own transpiler.

We could build in default support for this - but the problem is now there are two versions of coffeescript. The more built in choices we make for you, the harder it is for us to keep up with all of it or to enable customization.

It's much easier if you control this yourself using your own `node_modules` the same way you do it for your own projects.

Try that and see what you think

**Comment by andreiucm** [comment] 2018-06-27 18:32
Deal! Thank you very much for your help, and of course for Cypress! 
(Hope Firefox support will come soon :) )

**Comment by jennifer-shehane** [comment] 2019-07-23 12:20
Closing since there is a working solution for this.

**Closed by jennifer-shehane** 2019-07-23 12:20 UTC
Labels: existing workaround, pkg/server, type: bug
