### ISSUE TITLE
Redirect Test is Failing

### ISSUE THREAD

**Issue by DarthOpto** [cypress-io/cypress#3627] opened 2019-03-01 20:25 UTC
### Current behavior:

I am trying to port over my protractor tests to Cypress. One of the suites is a test where I navigate directly to certain areas of our application directly from the URL. 

For example, I would put `cy.visit('auth/login?next=page_I_Want')` it goes to the login page, logs in, then I get this newUrl message with the following `https://qa.app.com/__/page_I_want`, and then it immediately stops and gives me another newUrl and it is our home page. 

I tried the suggestions for #992 and it does not work. 

our login app redirect stuff is below:

```js
this.security.login(this.user.username, this.user.password, impersonate, next).then(response => {
    if (response.status === 200) {
        if (response.data.error) {
            this.user.isLoggingIn = false // don't hide spinner on success, we're loading a different app

            // Bad credentials
            // FIXME: show reasons for failure instead of assuming credential failure
            if (response.data.error === 'Account disabled') {
                this.showError(this.ACCOUNT_DISABLED_MESSAGE)
            } else {
                this.showError(this.BAD_CREDENTIAL_MESSAGE)
            }
        } else {
            // success
            // save user as non SSO
            window.localStorage.setItem(
                this.PRECHECK_USER_COOKIE,
                JSON.stringify({ email: this.user.username, isSSO: false }),
            )

            const pdfDownloadFileRegex = /[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}\/.+\.(pdf|zip)$/

            if (pdfDownloadFileRegex.test(response.data.redirect)) {
                this.$window.location.replace(response.data.redirect)

                setTimeout(() => {
                    this.$window.location.replace('/')
                }, 5000)
            } else {
                // redirect user to main app, terminating this app
                this.$window.location.replace(response.data.redirect)
            }
        }
    } else {
        // server issue
        this.showError(this.REQUEST_ERROR_MESSAGE)
        this.user.isLoggingIn = false
    }
})
}
```

![image](https://user-images.githubusercontent.com/7504395/53666601-c6517c00-3c2b-11e9-991d-ee9e612c7c06.png)

Not sure what I can do to make Cypress work for these tests. 

### Desired behavior:

Handle redirects like protractor / webdriver does

### Steps to reproduce: (app code and test code)

Running the following test:

```js
describe('Login: Navigate Directly to Apps', () => {
    _.forEach(AppParams.apps, page => {
        it(`should navigate to ${page.url} after logging in`, () => {
            if (page.navLink !== 'mgmt-console') {
                cy.visit(`auth/login?next=${page.url}`)
                normalLogin(userName, password)
                waitForPermon()
                cy.url().should('include', page.url)
            } else {
                console.log('Customer Users Would Not have permission to access the Mgmt Console')
            }
        })
    })
})
```

### Versions

Cypress 3.1.5
Chrome 72

**Comment by flotwig** [comment] 2019-11-07 22:10
This is a duplicate of #3994, closing

**Closed by flotwig** 2019-11-07 22:10 UTC
