### ISSUE TITLE
Video recording issue in Cypress Cloud. Frame gets stuck when view them

### ISSUE THREAD

**Issue by ahmed-ramzi** [cypress-io/cypress#26124] opened 2023-03-15 16:03 UTC
### Current behavior

Hi there,

The videos that are recorded in our account via the Gitlab integration are not reliable. The frame get stuck after 5 to 10 seconds and nothing gets updated, therefore I can not see what is going on with the tests 

### Test code to reproduce

Unfortunately I can not provide the repo due to NDA. However, you can watch this video to see what I mean

https://user-images.githubusercontent.com/82296979/225368692-d6f42b8a-64ec-4417-93c5-97199e23fb3d.mp4

### Cypress Version

10.11.10

### Node version

16.13.2

### Operating System

Linux Debian - 11.5

**Comment by lmiller1990** [comment] 2023-03-16 03:36
This looks frustrating, sorry you are running into this issue. I'd definitely recommend updating to the latest version of Cypress (v12), but I suspect the issue might be related to the runner. Can you share the specs? I wonder if it's just a lack of resources.

Hard to say without access to the code - if possible, does GL let you bump up to a machine with more resources? That'd be a good way to debug and isolate the issue. What if you just run a single spec?

If this doesn't help, I'll spend some time making a GL project and see if I can reproduce. Does this happen with any other projects (maybe a more simple one) or is it just this project?

**Comment by lmiller1990** [comment] 2023-03-28 04:28
Happy to reopen once we've got more information to continue debugging. Until then, I'll close this, since I don't see any actionable work in Cypress relating to this issue.

**Closed as completed by lmiller1990** 2023-03-28 04:28 UTC
