### ISSUE TITLE
Cypress desktop app on windows 10  crashes when trying to open a project

### ISSUE THREAD

**Issue by Nagimagi** [cypress-io/cypress#5031] opened 2019-08-23 09:32 UTC
\### Current behavior:

When I was trying to open my project to run the files under the `/integration`, the cypress desktop app just kept crashing from time to time. Most recently it quite frequents and I couldn't proceed to my work. I wonder if any of you ever have this problem or even better the solution.   

Below is the log I copied from the all.log under route:  `\AppData\Roaming\Cypress\cy\production`

```
{"level":"info","message":"getting user","timestamp":"2019-08-23T09:09:43.826Z"}
{"level":"info","message":"getting user","timestamp":"2019-08-23T09:10:29.282Z"}
{"level":"info","message":"getting user","timestamp":"2019-08-23T09:10:29.457Z"}
{"level":"info","message":"getting user","timestamp":"2019-08-23T09:16:17.338Z"}
{"error":"Expected pattern to be a non-empty string",
  "stack":"TypeError: Expected pattern to be a non-empty string\n    
at picomatch (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\picomatch\\lib\\picomatch.js:43:11)\n    
at createPattern (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\node_modules\\anymatch\\index.js:25:18)\n    at Array.map (<anonymous>:null:null)\n    
at anymatch (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\node_modules\\anymatch\\index.js:77:28)\n    
at FSWatcher._isIgnored (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:720:25)\n    
at NodeFsHandler._addToNodeFs (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\lib\\nodefs-handler.js:515:16)\n    
at Promise.all.paths.map (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:405:47)\n    
at Array.map (<anonymous>:null:null)\n    
at FSWatcher.add (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:404:13)\n    
at Object.watch (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:897:11)\n    
at createSpecsWatcher (D:\\Cypress\\resources\\app\\packages\\server\\lib\\open_project.js:149:35)\n    
at D:\\Cypress\\resources\\app\\packages\\server\\lib\\open_project.js:159:13\n    
at tryCatcher (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    
at Promise._settlePromiseFromHandler (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromiseCtx (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\promise.js:604:10)\n    at Async._drainQueue (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\async.js:138:12)\n    at Async._drainQueues (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)\n","type":"server","level":"info","message":"caught error","timestamp":"2019-08-23T09:16:17.342Z"}
{"level":"info","message":"getting user","timestamp":"2019-08-23T09:16:17.343Z"}
```

### Desired behavior:

opening the project and showing all the js files.

### Steps to reproduce: (app code and test code)

It seems the crashes often happened when I created a new file on vscode under the project.
Then I opened the `cypress.exe` and selected the project I intended.
Then it crashed.

### Versions
Cypress: v2.0.18
OS: Windows10
Browser: Chrome  76.0.3809.100

**Comment by Nagimagi** [comment] 2019-08-26 08:26
now it's back to normal without me doing anything. no idea why this happened.

**Comment by bahmutov** [comment] 2019-08-26 12:50
@Nagimagi can you post your `cypress.json` file please? Because it is suspicious that it crashed trying to watch spec files. Maybe you have a custom pattern of spec files there?

```
{"error":"Expected pattern to be a non-empty string","stack":"TypeError: Expected pattern to be a non-empty string\n at picomatch (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\picomatch\\lib\\picomatch.js:43:11)\n at createPattern (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\node_modules\\anymatch\\index.js:25:18)\n at Array.map (<anonymous>:null:null)\n at anymatch (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\node_modules\\anymatch\\index.js:77:28)\n at FSWatcher._isIgnored (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:720:25)\n at NodeFsHandler._addToNodeFs (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\lib\\nodefs-handler.js:515:16)\n at Promise.all.paths.map (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:405:47)\n at Array.map (<anonymous>:null:null)\n at FSWatcher.add (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:404:13)\n at Object.watch (D:\\Cypress\\resources\\app\\packages\\server\\node_modules\\chokidar\\index.js:897:11)\n at createSpecsWatcher (D:\\Cypress\\resources\\app\\packages\\server\\lib\\open_project.js:149:35)\n at 
```

**Comment by Nagimagi** [comment] 2019-08-26 13:23
@bahmutov sure, it looks like this. I appended 'txt' so that I can upload this file.


[cypress.json.txt](https://github.com/cypress-io/cypress/files/3541279/cypress.json.txt)

**Comment by bahmutov** [comment] 2019-08-26 13:35
@Bkucera can you check if we handle the file mask correctly on Windows in this case - I have extracted just the two props that matter

```json
{
  "ignoreTestFiles": "",
  "testFiles": "**/*.*",
  "watchForFileChanges": true,
  "fileServerFolder": "/playground",
  "fixturesFolder": "cypress/fixtures",
  "integrationFolder": "cypress/integration"
}
```

from the user-supplied full `cypress.json` file below

```json
{
  "baseUrl": "abc.xyz",
  "env": {
    "user": "abc",
    "pass": "abc"
  },
  "ignoreTestFiles": "",
  "numTestsKeptInMemory": 50,
  "port": null,
  "reporter": "spec",
  "reporterOptions": null,
  "testFiles": "**/*.*",
  "watchForFileChanges": true,
  "defaultCommandTimeout": 10000,
  "exexTimeout": null,
  "taskTimeout": null,
  "pageLoadTimeout": 10000,
  "requestTimeout": null,
  "responesTimeout": null,
  "fileServerFolder": "/playground",
  "fixturesFolder": "cypress/fixtures",
  "integrationFolder": "cypress/integration",
  "pluginsFile": false,
  "screenshotsFolder": "cypress/screenshots",
  "supportFile": "cypress/support/index.js",
  "trashAssetsBeforeRuns": true,
  "videoCompression": 32,
  "videosFolder": "cypress/videos",
  "video": true,
  "videoUploadOnPasses": true,
  "chromeWebSecurity": false,
  "userAgent": null,
  "blacklistHosts": null,
  "modifyObstructiveCode": true,
  "viewportHeight": 760,
  "viewportWidth": 1440,
  "animationDistanceThreshold": 20,
  "waitForAnimations": true,
  "projectId": "y3481s"
}
```

**Comment by KarneyenkaDzmitry** [comment] 2019-08-27 08:43
I have faced with the same problem after update to 3.4.1 version
![Cypress_issue](https://user-images.githubusercontent.com/33957610/63755709-ce7b3300-c8bf-11e9-9781-22ca9fd41b15.png)

**Comment by KarneyenkaDzmitry** [comment] 2019-08-27 08:50
I faced with the same problem after update to 3.4.1 version.

1. When I try to open cypress ui by using comman `cypress open`:
`TypeError: Expected pattern to be a non-empty string
    at picomatch (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\picomatch\lib\picomatch.js:43:11)
    at createPattern (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\node_modules\anymatch\index.js:25:18)
    at Array.map (<anonymous>:null:null)
    at anymatch (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\node_modules\anymatch\index.js:77:28)
    at FSWatcher._isIgnored (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:720:25)
    at NodeFsHandler._addToNodeFs (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:515:16)
    at Promise.all.paths.map (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:405:47)
    at Array.map (<anonymous>:null:null)
    at FSWatcher.add (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:404:13)
    at Object.watch (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:897:11)
    at createSpecsWatcher (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\open_project.js:149:35)
    at C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\open_project.js:159:13
    at tryCatcher (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromiseCtx (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:10)
    at Async._drainQueue (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Dzmitry\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)`

2. Despite, `cypres run works correctly`

Windows 10 
Cypress version 3.4.1
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by KarneyenkaDzmitry** [comment] 2019-08-27 09:37
I have no Idea why, but after instalation to new project `cypress open` did not thow the Error. Moreover, after that it works correct in current project. It may be connected with cypress.json parser.

**Comment by KarneyenkaDzmitry** [comment] 2019-08-28 14:37
I found the problem for the Error for my situation. It was connected with flag `"ignoreTestFiles": ""` in cypress.json file. It was empty string. Before update to version 3.4.1 everything works fine with the flag. But in the latest version `cypress open` throws an Error. My solution of this is: delete the field or set empty array. Now everything works fine.

**Comment by Nagimagi** [comment] 2019-08-29 02:19
@KarneyenkaDzmitry In desperate I tried with your solution and it **WORKS** !!!  THANKS A MILLION!!

**Comment by KarneyenkaDzmitry** [comment] 2019-08-29 07:02
@Nagimagi. My pleasure. I am glad to help.

**Comment by Bkucera** [comment] 2019-08-30 16:05
@bahmutov do we know what caused this regression? (if this bug didn't exist prior to `3.4.1`

**Comment by bahmutov** [comment] 2019-08-30 16:16
@Bkucera not sure, and I am not sure this is a regression - not handling empty `ignoreTestFiles` string

**Comment by hannahmolloy** [comment] 2019-11-25 23:25
I ran into this problem too and found out that it is a bug in the version of chokidar that cypress uses ( https://github.com/paulmillr/chokidar/issues/871 ) - chokidar have fixed this issue in version 3.1.1 - it would be great if cypress could upgrade the chokidar version to fix this

**Comment by bahmutov** [comment] 2019-11-26 13:36
Hmm, I see `packages/server/package.json:56:    "chokidar": "3.2.2"`

**Comment by jennifer-shehane** [comment] 2021-02-03 07:27
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-03 07:27 UTC
Labels: OS: windows, stage: needs information, topic: file watching :eyes:
