### ISSUE TITLE
uncaught:exception is not working for different subdomain

### ISSUE THREAD

**Issue by mxrguspxrt** [cypress-io/cypress#3750] opened 2019-03-19 14:15 UTC
Hello!

I hope you are having a good day and you can help us with our problems with Cypress:

It seems that subdomains implementation is badly tested - unable to get it to work in 3 days.

Problems:
1. Catching errors does not work. If 3rd party JS has error, test fails. 

	`Cypress.on('uncaught:exception', (err, runnable) => {
  		return false;
	});`

	has no effect, if different subdomain is visited. (Appears with Electron, with Chrome works ok.)

2. Why would the framework even would force only one domain or subdomain? I need to run a local proxy to by-pass this limitation.

3. Any 3rd party JS can fail. Why does the framework default presume, that i want to fail all my test and deployment flow in that scenario?

4. If test fails on second subdomain, test is timed out and marked to be finished successfully.

Thank you for the great testing framework and hopefully these things get also fixed. :)

Best regards!

**Comment by jennifer-shehane** [comment] 2019-03-19 16:12
Hey @mxrguspxrt, thanks for the feedback. We know this has been challenging for some of our users. There has been some discussion on why this decision was made initially in this issue, which I believe you've seen. https://github.com/cypress-io/cypress/issues/944

If you can provide an example of where `Cypress.on('uncaught:exception'...` is not catching an Uncaught Exception or where else you are unable to move forward with your test code, we'd be happy to look at it here or at support@cypress.io Thanks!

**Comment by mxrguspxrt** [comment] 2019-03-20 08:21
Hello, @jennifer-shehane!

Precondition:
1. Browser: Electron
2. `Cypress.on('uncaught:exception', ...) `
3. cypress.json includes baseUrl = mydomain1.domain.com

Steps:
1. cy.visit('/url/on/first/subdomain')
2. cy.loginOnMyDomain1()
3. cy.visit('mydomain1.domain.com/some-url-that-throws-exception-in-code-but-in-reality-does-work')

**Comment by mxrguspxrt** [comment] 2019-03-20 08:48
Additionally, if subdomain is switched:

cy.get('#element-that-does-exist-and-tests-fails').click()

Then test passes as green.

**Comment by mxrguspxrt** [comment] 2019-03-25 11:05
As a quick fix changed Electron to Chrome and got tests running. If possible, please fix Electron also. :)

**Comment by jennifer-shehane** [comment] 2019-07-23 09:36
going to close as duplicate of https://github.com/cypress-io/cypress/issues/987

**Closed by jennifer-shehane** 2019-07-23 09:36 UTC
Labels: stage: needs investigating
