### ISSUE TITLE
Cypress crashes on quit after running test in Electron

### ISSUE THREAD

**Issue by johnchurchill** [cypress-io/cypress#15378] opened 2021-03-09 22:15 UTC
### Current behavior
Start Cypress (my exact command is: `$(npm bin)/cypress open`), run one test using Electron, then quit (menu or Cmd-Q). In the terminal is this error, and exit code is 1:

```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (19.6.0)
Cypress Version: 6.5.0
```

10 seconds later, MacOS shows the "Cypress quit unexpectedly" dialog.
The crash does _not_ happen in these circumstances:
- no test is run
- use Chrome or Firefox
- click "stop" (closing the browser window) before quitting

### Desired behavior
Just quit.

### Versions
Cypress 6.5.0
MacOS 10.15.7

**Comment by johnchurchill** [comment] 2021-03-09 22:19
I just noticed there is a near identical issue for this.
Duplicate of #9164

**Comment by jennifer-shehane** [comment] 2021-03-16 22:35
Duplicate of https://github.com/cypress-io/cypress/issues/9164

**Closed by jennifer-shehane** 2021-03-16 22:35 UTC
