### ISSUE TITLE
focus is not working when we have scenario outline in the feature file

### ISSUE THREAD

**Issue by mohanbabu-zumen** [cypress-io/cypress#25781] opened 2023-02-13 05:47 UTC
### Current behavior

focus is not working when we have scenario outline in the feature file

### Desired behavior

focus should work even If we have Scenario outline

### Test code to reproduce

- Integrate cypress with cucumber framework
- Write the scenario outline in the feature file
- focus the any other scenario
- But, It's running from first scenario

### Cypress Version

11.2.0

### Node version

16.17.0

### Operating System

Windows 11

**Comment by marktnoonan** [comment] 2023-02-16 16:48
Hi @mohanbabu-zumen, thanks for opening an issue. Can you create an example of this problem? The description provided is not enough to understand the issue. For example, are you using https://github.com/badeball/cypress-cucumber-preprocessor - and could this be an issue with that library, not Cypress? It's hard to tell without seeing the full code, dependencies etc.

Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marktnoonan** [comment] 2023-02-22 23:55
I'm going to close this for now due to inactivity, please comment with new information and we can consider reopening the issue.

**Closed as completed** 2023-02-22 23:55 UTC
