### ISSUE TITLE
Fix type definition for component prop in cypress/vue

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24341] opened 2022-10-21 15:51 UTC
The current type for the mount prop `component` is not easily understandable in cypess/vue
<img width="954" alt="image" src="https://user-images.githubusercontent.com/25568640/197237582-93e3f44c-d983-4282-839f-e147e7aa7f1f.png">

**Comment by baus** [comment] 2022-10-24 15:31
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24341?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by astone123** [comment] 2022-10-24 19:04
Do we have any ideas for how to better type this prop?

**Comment by ZachJW34** [comment] 2022-10-25 15:24
Could be a duplicate of https://github.com/cypress-io/cypress/issues/24330

Current:
<img width="685" alt="Screen Shot 2022-10-25 at 10 21 55 AM" src="https://user-images.githubusercontent.com/25158820/197814960-c747e84a-4b8d-41e1-a411-a7edd276537b.png">

After converting `@cypress/mount-utils` to `cypress/mount-utils` in `node_modules/cypress/vue/index.d.ts`:
<img width="622" alt="Screen Shot 2022-10-25 at 10 24 05 AM" src="https://user-images.githubusercontent.com/25158820/197815281-751aa2e2-156d-4181-a420-969fa9e89607.png">

Is the issue to investigate how to improve the type? What are the current problems (assuming the above issues is resolved)?

**Comment by lmiller1990** [comment] 2022-10-31 02:46
I agree it's hard to understand - but this is the unfortunate reality of Vue components, there is a lot of ways to define them, so this type is accurate (albeit confusing).

The only way to make it easier would be something like

```js
import { DefineComponent } from 'vue'

function mount(component: DefineComponent) {
  // ...
}
```

I don't think you get type safety when doing

```js
mount(Blah)
```

Anyway... I wonder if we should make this `any` (or `DefineComponent`)? If you want type safety, you need to use TSX anyway (which we do). It'd still be *less* type safe though, which isn't ideal... I'm not sure there's any actionable fix here.

For reference, the actual definitions for `DefineComponent` are here: https://github.com/vuejs/core/blob/32b51249bff70d1e03a3f9193f5a42461974daa6/packages/runtime-core/src/apiDefineComponent.ts#L33

**Comment by lmiller1990** [comment] 2023-02-24 04:12
I don't see how we can really improve this - it's an upstream dependency for TS and Volar.

I'd love to improve this if anyone has any ideas - I don't see any way to fix this, and I don't think we will be doing any work on this in the future, so I'm going to close it for now.

**Closed as not planned** 2023-02-24 04:12 UTC
Labels: CT
