### ISSUE TITLE
Google Chrome on special version not respond and freeze with white screen

### ISSUE THREAD

**Issue by RomanShmandrovskyi** [cypress-io/cypress#7433] opened 2020-05-20 15:43 UTC
### Current behavior:
When run Cypress tests on 83.0.4103.61 Google Chrome version, browser stuck just after Crhrome was opened.

It works on Electron!

Also I try downgrade Cypress version. It not help.

Think problem inside Google Chrome

### Test code to reproduce

Take a look on this video:
https://drive.google.com/open?id=1Wp_BiWVIN1gmRXptkHN493BsgJvEANT2

can be related to #7432 

### Versions

Google Chrome Version: Version 83.0.4103.61 (Official Build) (64-bit)
Cypress version: 4.5.0
OS: Ubuntu 18.04.4 TLS

**Comment by RomanShmandrovskyi** [comment] 2020-05-20 18:11
Downgrade Chrome version to 81.0.4044.92.
Now it works good

**Comment by bgk17** [comment] 2020-05-20 21:03
same here

**Comment by jennifer-shehane** [comment] 2020-05-21 07:08
Thanks for providing the video. This is helpful to see the problem. 

I can't recreate this on macOS with Chrome 83.0.4103.61

@RomanShmandrovskyi Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

@bgk17 Could you verify what operating system you're using?

### Current Behavior

Upon `cypress open` and clicking into a specfile, Chrome shows the following message instantly. 

<img width="440" alt="Screen Shot 2020-05-21 at 1 22 00 PM" src="https://user-images.githubusercontent.com/1271364/82532053-86472380-9b66-11ea-8718-cecff17526c6.png">

Exiting Chrome shows this error in the Cypress Desktop-GUI

<img width="424" alt="Screen Shot 2020-05-21 at 1 22 14 PM" src="https://user-images.githubusercontent.com/1271364/82532072-919a4f00-9b66-11ea-9fe3-21e1bbd8d89c.png">

With this error printed to the console:

<img width="1460" alt="Screen Shot 2020-05-21 at 1 23 35 PM" src="https://user-images.githubusercontent.com/1271364/82532104-9e1ea780-9b66-11ea-885b-8c859cb49b38.png">

```
ERROR.bus.css(393) Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

**Comment by RomanShmandrovskyi** [comment] 2020-05-21 08:49
@jennifer-shehane 
just run it in DEBUG mode: https://drive.google.com/file/d/1qjcoE3UKl18tSUfGdbbwC62ctLrXm53H/view?usp=sharing

and logs from terminal are here:
https://drive.google.com/open?id=1XZgerRpXl-BWWtSxfCH_bDPK0lEm5kG4

Seems like it can't connect to browser:
![Screenshot from 2020-05-21 11-48-08](https://user-images.githubusercontent.com/32175470/82541400-15e5d580-9b59-11ea-9c09-aee2c1edf257.png)

**Comment by marc-guenther** [comment] 2020-05-21 12:40
Just for the record, I cannot reproduce this on MacOS either. Firefox and Electron work fine as well.

Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by flotwig** [comment] 2020-05-21 13:08
Chrome 83.0.4103.61 works fine for me with Cypress on Linux (Pop OS 20.04)

> This Chrome commit seemed maybe related (related to running xvfb with RGB color masks breaking in Linux) https://chromium.googlesource.com/chromium/src.git/+/f5b9b624ed2cb9b85215b62b5d1c7a7a36a89400

Tried running 83 inside of the Xvfb spawned by Cypress and still no issues, but this does sound related since we do some kind of colorspace setup for Xvfb...

**Comment by fornellas** [comment] 2020-05-22 15:23
Chrome 83.0.4103.61-1 seems to be a bad build. I bumped into this issue by chance, as I'm having frequent freezes with this build, in things completely unrelated, in 2 different machines (LinuxMint + Nvidia). [81.0.4044.138-1](http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_81.0.4044.138-1_amd64.deb) works fine.

Here's what the kernel complains when it freezes:

```
[  440.937828] NVRM: GPU at PCI:0000:01:00: GPU-63d4c5cf-2520-d9e0-1554-a8d7d42ace11
[  440.937833] NVRM: GPU Board Serial Number: 
[  440.937837] NVRM: Xid (PCI:0000:01:00): 31, pid=1688, Ch 00000016, intr 10000000. MMU Fault: ENGINE HOST0 HUBCLIENT_HOST_CPU faulted @ 0x1_01361000. Fault is of type FAULT_PTE ACCESS_TYPE_WRITE
[ 1061.672936] NVRM: Xid (PCI:0000:01:00): 31, pid=10091, Ch 00000016, intr 10000000. MMU Fault: ENGINE HOST0 HUBCLIENT_HOST_CPU faulted @ 0x1_025f2000. Fault is of type FAULT_PTE ACCESS_TYPE_READ
```

**Comment by clarmso** [comment] 2020-06-05 20:44
@fornellas Are you still good with 81.0.4044.138-1 or above? I hope that 83.0.4103.61-1 happened to be a bad build.

**Comment by fornellas** [comment] 2020-06-08 18:04
@clarmso I haven't update Chrome ever since... not sure TBH. But I'm not a cypress user, I just shared here for awareness.

**Comment by jennifer-shehane** [comment] 2020-07-02 09:18
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-02 09:18 UTC
Labels: OS: linux, browser: chrome

**Comment by arifhussain353** [comment] 2020-08-04 07:45
OS Ubuntu **Ubuntu 18.04.4 LTS**
