### ISSUE TITLE
ERR_CONNECTION_ABORTED when running tests

### ISSUE THREAD

**Issue by jlem** [cypress-io/cypress#6268] opened 2020-01-28 17:17 UTC
### Current behavior:

When trying out the simple introduction example and running tests, I get an `ERR_CONNECTION_ABORTED` response from the browser. Have tried Chrome 79 headed and headless, and electron. Same issue. Appears to be a network problem.

### Desired behavior:

The tests should run in the browser without an issue.

### Test code to reproduce

No special test setup required. Just follow the introduction example in the documentation. 

Some additional information about my environment:

1. Not running as admin
2. Machine is a corporate machine provisioned by the IT department and it appears to be blocking connections being made from Cypress. 

I could use some advice on how to debug this and how Cypress is using the network under the hood. 

I have allowed Cypress through the Windows Firewall for all networks.

### Versions

Cypress 3.8.3, Windows 10, Chrome 79.

**Comment by Sumedh-k** [comment] 2020-02-01 01:56
Did you have chat with your IT department on why they are blocking connections?

Do you use a proxy to connect the internet?

Follow this doc for more info on how to debug

https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

**Comment by jennifer-shehane** [comment] 2020-02-04 07:14
I cannot reproduce on my network, so this is likely due to something regarding your network. 

@jlem Please check proxy setup and check with your IT for any network blocking as explained above. https://on.cypress.io/proxy-configuration

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-04 07:14 UTC
