### ISSUE TITLE
Screenshot on failure should take screenshot before running "afterEach" commands

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#394] opened 2017-01-26 18:30 UTC
If there are lot of commands (or a meaningful change) in `afterEach` callback, the screenshot on failure produces an image that does not show the failure. For example
```js
describe('something', () => {
  afterEach(() => {
    cy.visit('/else')
    cy.wait(100)
    cy.wait(100)
    cy.wait(100)
    cy.wait(100)
    // more calls like this
  })
  it('works', () => {
    cy.visit('/something')
    cy.contains('does not exist')
  })
})
```

In the above test I would like to see page "/something" during the failure `cy.contains`
but instead I see screenshot of `/else` and the command log might be scrolled way down
due to lots of `cy.wait` calls; hiding the red failure log.

It would be nice to have the screenshot taken right on failure, not at the end, despite #194 (which still applies)

**Comment by brian-mann** [comment] 2017-01-26 19:57
The screenshot is actually taken at the moment of failure.

The problem is that we are using React on the front-end, and there is no guarantee that the commands have been updated when the screenshot is taken - so it appears the screenshot is "lagging" but in reality its not.

We haven't really figured out a good solution for this, because while we could theoretically wait and synchronize with the command log - your application may actually be in a different state and therefore the screenshot would reflect "not the truth".

Taking a screenshot is async in the first place so there is no guarantees at the moment of failure your app looked the way it does.

So another option we've been considering is taking a synchronous snapshot, and then rebuilding it at a later time to take the screenshot. That would mostly work but would not take into account CSS transitions.

It's a complicated thing to get right...

**Comment by bahmutov** [comment] 2017-01-26 20:20
hmm, not sure I understand, but thanks for looking into this

**Comment by bahmutov** [comment] 2017-01-30 04:48
Ok, I did this in user space as part of my log utility https://github.com/bahmutov/cypress-failed-log
Compare the screenshots generated "normally" after all user `afterEach` callbacks finished and 

![immediate-screenshot](https://cloud.githubusercontent.com/assets/2212006/22412527/3173beb4-e67d-11e6-83d6-5ccac24dac59.png)
![full-test-finishes](https://cloud.githubusercontent.com/assets/2212006/22412528/3175a76a-e67d-11e6-8c73-d0909b47f943.png)

The spec is here: https://github.com/bahmutov/cypress-failed-log/blob/master/cypress/integration/failing-spec.js 
Note the `afterEach` even goes to another page, destroying what I really want to see in the failing page.

I could post dashboard link :)

So I am fine with this screenshot - all rendering and DOM updates aside.

**Comment by brian-mann** [comment] 2017-09-13 14:52
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)

**Closed by brian-mann** 2017-09-13 14:52 UTC

**Comment by verheyenkoen** [comment] 2017-10-12 07:43
Shouldn't the command log already reflect the failure in the screenshot? I'm always getting screenshots of failures where it seems that the test is still ongoing (assertion in blue with spinner icon in front / no red marker in the left margin).

**Comment by brian-mann** [comment] 2017-10-12 21:17
Because the Command Log uses React under the hood (which render async) it's actually not trivial to get it to "sync up" with the screenshot taking process, because that is also async. We did a bunch of work in 0.20.0 to make it closer, but I also noticed it's not perfect and we'll need to synchronize multiple components together to do more than what we're doing now.

This work can be done at any time and should be pretty easy to find in the code.
