### ISSUE TITLE
 After clicking the button the cypress window turns completely blank page. Although there are no URL changes on click of this button.

### ISSUE THREAD

**Issue by Ganesh3438** [cypress-io/cypress#25895] opened 2023-02-21 14:14 UTC
### Current behavior

All Screen Turns White when a button on the DOM is clicked.

### Desired behavior

it shouldn't turn white, Instead the display should be normal

### Test code to reproduce
```js
userSaveButton(){
        cy.xpath('//button[@data-cy="submit"]').scrollIntoView().should('be.visible')
        cy.wait(2000)
        // cy.xpath('//button[@data-cy="submit"]').click({force:true})
        cy.contains('Save').click({force:true})
       
        
    }
```
### Cypress Version

9.7.0 and latest versions as well

### Node version

16.13.2

### Operating System

Windows 10

**Comment by gvaatstra** [comment] 2023-02-21 15:18
There isn't much to go on without any code for reproduction or a video or anything.
Maybe if you remove the force, it could help if something might not have been loaded properly.

**Comment by nagash77** [comment] 2023-02-21 15:49
Hi @Ganesh3438 , I'm sorry to hear you are having problems using Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2023-02-27 17:48
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-02-27 17:48 UTC
