### ISSUE TITLE
custom commands are failing with Webkit 

### ISSUE THREAD

**Issue by kashifali00** [cypress-io/cypress#24136] opened 2022-10-05 18:21 UTC
### Current behavior

I have few customs command to get  Oauth token and I'm using them in beforeEach hook but the custom command doesn't work in beforeEach hook when running test through webkit. Whereas, same test is passing with electron browser

![Screenshot_232](https://user-images.githubusercontent.com/18286977/194132795-92ec9f51-09ad-4f02-93bd-0c34d2eddfc3.png)
![Screenshot_233](https://user-images.githubusercontent.com/18286977/194132808-8cbeffb2-1743-4a46-86be-8fdfb93ae17e.png)
![Screenshot_234](https://user-images.githubusercontent.com/18286977/194132818-71926136-6601-42e6-b000-f5869f925c76.png)

cypress.config.json
```javascript
 e2e: {
    specPattern: "**/*.feature",
    supportFile: "cypress/support/e2e.js",
    setupNodeEvents,
    baseUrl: "https://np-ppcm.hdsupply.com",
    projectId: "8rwz2r",
    watchForFileChanges: false,
    experimentalSessionAndOrigin: true,
    experimentalWebKitSupport: true
}
```

package.json
```json
"devDependencies": {
    "@babel/core": "7.19.0",
    "@babel/preset-env": "7.19.0",
    "allure-commandline": "^2.18.1",
    "babel-loader": "8.2.5",
    "cypress": "^10.9.0",
    "cypress-mochawesome-reporter": "^3.2.2",
    "playwright-webkit": "^1.26.1",
    "saucectl": "^0.107.2",
    "webpack": "5.74.0"
  }
```

### Desired behavior

User should be able to get the token from custom command in beforeEach hook as same behavior is working absolutely fine with other browsers/ cypress test runner

### Test code to reproduce

beforeEach("Get login to ppcm portal through programtically", () => {

    // login to ppcm portal
    cy.getAzzureToken().then(token => {
            cy.login(token)

    })   
    
})

### Cypress Version

10.9.0

### Node version

v16.17.0

### Operating System

window10

**Comment by astone123** [comment] 2022-10-05 23:04
Closing as duplicate of #23832

**Closed as completed by astone123** 2022-10-05 23:04 UTC
