### ISSUE TITLE
Cypress does not open color input on click

### ISSUE THREAD

**Issue by tayateo** [cypress-io/cypress#7812] opened 2020-06-25 10:13 UTC
### Current behavior:

Color palette does not appear when click `input type="color"` in Cypress test.
However it appears when click manually in browser launched by Cypress.

### Desired behavior:

Color palette appears when click at `input type="color"`

### Test code to reproduce

https://github.com/mayenok/cypress-test-tiny

### Versions

Cypress: 4.9.0
Ubuntu 18.04.4 64-bit
Chromium 83.0.4103.61

**Comment by jennifer-shehane** [comment] 2020-06-26 11:00
I imagine this is due to our not issuing a native click event, and instead simulating events within Cypress. https://github.com/cypress-io/cypress/issues/311 

@mayenok What is it that this is blocking your test from testing?

### Reproducible example

`index.html`

```html
<html>
<body>
  <input type='color'>
</body>
</html>
```

`spec.js`

```js
it('opens color palette', () => {
  cy.visit('index.html')
    .get('input').click()
})
```

**Comment by bahmutov** [comment] 2020-06-26 11:10
Yeah it is a native browser dialog similar to file opener dialog. Your test can simply set the desired color value as shown in 

https://www.cypress.io/blog/2020/03/17/how-to-test-an-application-that-changes-css-variable/

**Comment by mayenok** [comment] 2020-06-26 11:24
Thanks for help! This works:
```
cy.get('input[type=color]')
    .invoke('val', '#ff0000')
    .trigger('change')
```

P.S. and thanks for the great framework :heart:

**Comment by JohnDDuncanIII** [comment] 2020-10-22 01:36
Thank you all for the examples! I'm running into a similar issue where I want to simulate a real browser click that would set the value of the `input[type=color]`, trigger the event, and update its field in the `redux-form` store.

I was unable to get my controlled `input[type=color]` to update the `redux-form` store with just:

```javascript
cy.get('input[type=color]')
    .invoke('val', '#ff0000')
    .trigger('change')
```

Adding `.blur()` after the `.trigger("change")` seems to fix it for whatever reason (I guess the `redux-form` value is only committed to the store when the input loses blur/focus?).

`.invoke("val", "#ff007f").trigger("change")`

vs

`.invoke("val", "#ff007f").trigger("change").blur()`

---

The `input[type=color]` component I'm using looks like

```jsx
export const ColorInputField = styled.input`
    ...
`
```

```jsx
<S.ColorInputField
    data-cy={props.dataCy}
    error={props.meta.error}
    type="color"
    {...props.input}
/>
```

**Comment by EtienneBruines** [comment] 2021-01-28 09:07
This workaround does not work for Vue, where the value gets overwritten as soon as Vue updates the view.

```js
cy.get('input[type=color]')
    .invoke('val', '#ff0000')
    .trigger('change')
```

The addition of `blur` did not help in this case.

```js
cy.get('input[type=color]')
    .click()
    .invoke('val', '#ff0000')
    .trigger('change')
    .blur()
```

The color is updated (visually), but gets overwritten as soon as Vue updates. This happens for example when someone clicks a (submit) button.

------------------------

```html
<input v-model="primaryColor"
       type="color">
```

**Comment by nitsan** [comment] 2021-01-31 16:59
Also work for Angular!

```js
cy.get('input[type=color]')
    .invoke('val', '#ff0000')
    .trigger('input')
```

**Comment by waelhasan** [comment] 2021-11-09 18:07
Only this one worked for Nextjs, thanks @EtienneBruines 

```js
cy.get('input[type=color]')
    .invoke('val', '#ff0000')
    .trigger('input')
```

**Comment by sayefeddine** [comment] 2022-03-08 10:07
For whom may need it, the trigger('input') works on Angular.

> waelhasan

**Comment by wtachau** [comment] 2023-04-21 18:33
Has anyone gotten this to work in Svelte?

**Comment by jordanpowell88** [comment] 2023-04-24 17:28
> Has anyone gotten this to work in Svelte?

Can you provide an example of this @wtachau ?

**Comment by wtachau** [comment] 2023-04-24 17:31
If I have an input element in Svelte like
```jsx
<input
  bind:value={displayColor}
  type="color"
/>
```
the tricks shown above to fill the input don't work. Are you asking for a project repo that reproduces it?

**Comment by jordanpowell88** [comment] 2023-04-24 17:38
@wtachau If you can that would be appreciated

**Comment by warrensplayer** [comment] 2023-05-09 16:59
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by warrensplayer** 2023-05-09 16:59 UTC
Labels: type: unexpected behavior, pkg/driver, topic: native events, stage: backlog

**Comment by wtachau** [comment] 2023-05-09 17:01
Why is this closed? It is still an issue

**Comment by nagash77** [comment] 2023-05-09 18:13
@wtachau Sorry for the misunderstanding.  @jordanpowell88 asked for a reproduction repo and we didn't hear back for over 7 days so this was closed.  Are you able to provide us with a repo that reproduces this issue?  We have made https://github.com/cypress-io/cypress-test-tiny available in order to keep the examples small and self contained.

**Comment by wtachau** [comment] 2023-05-09 18:15
I will try to find time to reproduce, I understand that it makes the issue easier to triage. It just seems odd that adding _more_ information to a ticket that's been open for three years would lead it to be closed.

**Comment by nagash77** [comment] 2023-05-11 13:46
@wtachau Cypress evolves quickly and we are trying to keep our backlog more current and more relevant to modern versions of Cypress.  

We are also trying to spend more time investigating issues (even extremely old issues) and so getting reproducible examples on current versions of Cypress is critical to us being able to support the community as best as we can.  Often on older tickets the original author becomes unresponsive and the examples no longer work.  So older tickets without an updated reproducible example become stale and unworkable from our end.  This is why on extremely old issues we move towards closing the stale issue when we cannot get an updated reproducible example and it is often easier to triage and understand a problem that is narrow and specific and does not have multiple slightly different examples of the problem.  That is the long way of saying that more information does not always make it easier for our engineers to understand and debug a problem they may be seeing for the first time (especially for tickets that have been open for years).  

All that said, we always welcome a new issue if you are having problems running Cypress which we will add to our triage queue.
