### ISSUE TITLE
"cypress cache list --size" command doesn't work

### ISSUE THREAD

**Issue by AleksandrBorovkov** [cypress-io/cypress#8860] opened 2020-10-15 20:28 UTC
### Current behavior
![image](https://user-images.githubusercontent.com/22237897/96182321-ff904a00-0f3d-11eb-8cb5-6ab1dab3cb48.png)

### Desired behavior
No error

### Test code to reproduce
run "cypress cache list --size"

### Versions
Cypress 5.4, mac os 10.14.6

**Comment by jennifer-shehane** [comment] 2020-10-16 03:53
Duplicate of https://github.com/cypress-io/cypress/issues/8856

**Closed by jennifer-shehane** 2020-10-16 03:53 UTC
