### ISSUE TITLE
Cypress Dashboard not showing complete information which is available in output -- Fixing ASAP will Help paid users

### ISSUE THREAD

**Issue by KakaniSantosh** [cypress-io/cypress#27942] opened 2023-09-29 17:36 UTC
### Current behavior

We are seeing Cypress Dashboard is not showing complete information that is available in the output 

when we are using nested describe and iterations the result is wired and it shows the information in the unreadable manner instead you can show how it is displaying in  **view Output window**

I think its minor css change to dashboard but still its not getting repaired though i gave official email to support since few months iam sending this issue with a hope to get more value to people who see results 

![image](https://github.com/cypress-io/cypress/assets/146359184/d28a5d84-8694-41d9-885a-ab90177a5112)

### Desired behavior

To show output the same way as that of View Output window 
even in case user have multiple nested describe and nested iterations 

### Test code to reproduce

You can use large text in describe saying 
a statement like 
Describe("Describe 1 contains the main section to test the resgistration of the page and also login functionality" 

Nested Describe as 
Describe("Nested Describe  contains the main section to test the MFA of the page and also OTP functionality" 
    It ("Testing user with MFA login screen to check the valid credentials via OTP")

if you use this kind of realistic statements then you will be able to reproduce it 

because our client want to read statements which gives meaningful ness to non technical people to evaluate what went wrong by seeing into the results 

### Cypress Version

All versions

### Node version

All versions

### Operating System

Windows

### Other

CSS ISSUE

**Comment by jennifer-shehane** [comment] 2023-09-29 20:11
Closing as duplicate of https://github.com/cypress-io/cypress/issues/27904, our Cloud team has this issue they're tracking.

I know this is not an ideal solution - you can currently see the full test title by clicking on the test to open the righthand panel to see the full text. 

![image (3)](https://github.com/cypress-io/cypress/assets/1271364/3cb8d7e6-9a70-4756-a5b9-932cccdaf76e)

**Closed as completed by jennifer-shehane** 2023-09-29 20:11 UTC
