### ISSUE TITLE
Infinite page load on clicking a button that downloads a file via script

### ISSUE THREAD

**Issue by sllshrm** [cypress-io/cypress#6166] opened 2020-01-15 15:15 UTC
### Current behavior:

I have a button that allows me to download a some file on clicking it. However, it is not a button with an href link, it runs a script that changes the window.location to a blank page that downloads that file.

On running this with Cypress, this causes a page load event to fire which doesn't resolve even after download is started or completed.

For now as a workaround I'm creating a cy.request() with the API and checking it's response, but my aim is to do _end-to-end_ testing so it's just a workaround

### Desired behavior:

Page Load shouldn't fire or it should resolve after download gets started

### Test code to reproduce

Relevant screenshots:
How the page looks (I'm clicking the export button with class .get-new):
![1](https://user-images.githubusercontent.com/41990985/72445106-35e64080-37d7-11ea-9e12-54bc0ee43148.PNG)

The script that fires on click:
![2](https://user-images.githubusercontent.com/41990985/72445107-35e64080-37d7-11ea-8442-a8489ec00d88.PNG)

Page load timing out (file has already completed downloading and the response returned is 200):
![3](https://user-images.githubusercontent.com/41990985/72445105-354daa00-37d7-11ea-994b-2994941aa5e8.PNG)

### Versions

Cypress: 3.8.2
OS: Windows 10
Browser: Chrome 79.0.3945.117 (64-bit)

**Comment by jennifer-shehane** [comment] 2020-01-16 07:52
Cypress does not fully support in-browser file download support. Duplicate of https://github.com/cypress-io/cypress/issues/949

Cypress also does not support visiting urls that are non `text/html` content (aka what may be visited after downloading a file. Duplicate of https://github.com/cypress-io/cypress/issues/1551

Please follow the issues above for full support of your issue.

**Closed by jennifer-shehane** 2020-01-16 07:52 UTC

**Comment by jennifer-shehane** [comment] 2021-01-20 04:35
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).

**Comment by hafiz-usman-cowlar** [comment] 2022-09-12 16:15
@jennifer-shehane 
pageLoadTimeOut while downloading a xlsx file on click #23784
When I click on downloads button, it downloads a xlsx file. It visits this [url](https://idt.dev.viaphoton.dev/data/files/viaPhoton_Panel-Labeling-HDCE-12-UA-FMEXT-RD.xlsx) to download file. After downloading cypress Error occurs. pageLoadTimeOut.

If this issue is fixed, then plz help me to solve this issue. I searched about this issue, but not found any solution

**Comment by AlanBreck** [comment] 2023-06-07 00:37
I'm getting the same behavior as @hafiz-usman-cowlar.
