### ISSUE TITLE
Server sent events don't work and seem to be buffered by the Cypress proxy.

### ISSUE THREAD

**Issue by hally9k** [cypress-io/cypress#1440] opened 2018-03-11 23:34 UTC
This is following up after tagging onto [this issue](https://github.com/cypress-io/cypress/issues/1111) with my versions, specs and further info:

- Operating System: macOS 10.13.3
- Cypress Version: 2.1.0
- Browser Version: Google Chrome 65

### Is this a Feature or Bug?
Bug

### Current behavior:
No server sent events are received by the application running in the Cypress browser. If I kill the server then all events are flushed and appear in the browser at once. It seems that the events are getting buffered in Cypress' proxy layer until the connection terminates. This is how nginx works (or more accurately - doesn't work) with buffering turned on.

### Desired behavior:
Server sent events are passed through to the application.

### How to reproduce:
Run the repro below.

#### Test code:
https://github.com/hally9k/cypress-sse

**Comment by hally9k** [comment] 2018-03-13 00:29
@brian-mann If you'd like to take a moment to give me a pointer or two I might have a go at a PR?

**Comment by hally9k** [comment] 2018-03-22 22:43
@brian-mann is there an update on this issue? Or progress on version 3.0 release?

**Comment by brian-mann** [comment] 2018-03-25 15:20
I apologize I have not yet had a chance to resolve this, and the rest of our team are busy on other features outside of this repo. We're in the middle of raising our 3rd round of funding and with that will be able to add 2-3 more engineers which should help maintain the velocity since we have experience a lot of user growth.

I'm looking at this today and will let you know how it goes. I intended to release this fix with 3.0, but it seems we're still a bit aways on that, and will instead release a `2.x.x` fix instead.

**Comment by brian-mann** [comment] 2018-03-26 04:28
I have spent the last few hours on this. I can reproduce and am working on a fix. It's not simple, but it's not the worst thing either.

**Comment by hally9k** [comment] 2018-03-26 05:05
Awesome! Good luck with it. We are really looking forward to resolving this one.

**Comment by hally9k** [comment] 2018-03-28 01:14
@brian-mann Are you continuing to work on this? It would be awesome to get an alpha build to tide us over?

**Comment by brian-mann** [comment] 2018-03-31 16:38
I am doing what I can when I have time to work on it. I will try to have a release this weekend. As I mentioned, now is a transition point for Cypress. Our team is busy at work albeit on other things, and we are in the middle of raising (hopefully) a significant round of financing that I am primarily spearheading. When this is over we will add significantly more developers to keep up with the pace of issues. At the moment we're primarily focused on releasing 3.0.

I have your fix in place, but it requires some proxy changes which are really delicate and specifically error handling needs to be updated to better facilitate it. It's probably another 4-6 hours of work for me to do.

**Comment by hally9k** [comment] 2018-04-16 01:26
@brian-mann How's it all going over there? Any further news regarding the SSE support?

**Comment by hally9k** [comment] 2018-05-03 20:49
@brian-mann Any chance of that `2.x.x` patch release you mentioned?

**Comment by hally9k** [comment] 2018-05-28 02:08
@jennifer-shehane @brian-mann Any chance of an update on this front?

**Comment by hally9k** [comment] 2018-05-31 00:26
Aaaah you missed us out of 3.0!!! Noooooo! Okay, eagerly awaiting 3.0.1 then I suppose...

**Comment by brian-mann** [comment] 2018-06-02 22:19
I am working on this and we should see this get released in `3.0.2` before Monday. Apologize this took so long. With 3.0 out we are back to smaller iterations.

**Comment by hally9k** [comment] 2018-06-28 03:28
@brian-mann - The team here are super excited to see this land in `3.0.2` !!

**Closed** 2018-06-28 10:22 UTC
Labels: stage: in progress, type: feature

**Comment by brian-mann** [comment] 2018-06-29 09:11
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
