### ISSUE TITLE
Cypress throws Uncaught Error when trying to uncheck radio box

### ISSUE THREAD

**Issue by aeendale** [cypress-io/cypress#4974] opened 2019-08-12 17:54 UTC
### Current behavior:

Cypress throws the following uncaught error. It does NOT uncheck the checked boxes.
![image](https://user-images.githubusercontent.com/23197906/62886008-36e6e380-bd08-11e9-92ca-e877ff42dc63.png)

### Desired behavior:

Cypress should uncheck all checkboxes that are currently checked (Example screenshot below)
![image](https://user-images.githubusercontent.com/23197906/62885935-0dc65300-bd08-11e9-967f-d965a68c068b.png)

Note this was working ok with no issues before. The issue started occurring today.

### Steps to reproduce: (app code and test code)

1. Run the below cypress script

```js
cy.visit("http://pie-website-next.surge.sh/examples/pie-multiple-choice.html");

cy.get('input[class^="MuiPrivateSwitchBase"][type="checkbox"],{ timeout: 30000 }').should('be.visible').uncheck()
```

### Versions

**Browser**: Electron, Chrome (v69)
**OS**: Mac Mojave 10.14.3 
**Cypress**: 3.3.0

**Comment by mpahuja** [comment] 2019-08-30 09:07
there are two possible things that you can do:
1) Handle the app error specifically using https://docs.cypress.io/faq/questions/using-cypress-faq.html#Can-I-prevent-Cypress-from-failing-my-test-when-my-application-throws-an-uncaught-exception-error
2) Force each checkbox to be unchecked irrespective if the state by passing in `{force: true}` argument to `.uncheck()` call

**Comment by jennifer-shehane** [comment] 2020-01-07 08:44
I can't run the tests provided anymore. They just sit on the loading page. Closing since we cannot reproduce. 

<img width="1135" alt="Screen Shot 2020-01-07 at 3 13 59 PM" src="https://user-images.githubusercontent.com/1271364/71881247-591e4980-3160-11ea-8e1e-9bf4eba43c5c.png">


Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-01-07 08:44 UTC
