### ISSUE TITLE
Newer versions of Cypress have an ugly fixed-width font in the sidebar

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#24608] opened 2022-11-09 03:50 UTC
### Current behavior

Sometime in the last few months, there was a change to the fonts and now there's an ugly (and wide) fixed-width font in the sidebar:

![image](https://user-images.githubusercontent.com/10719780/200733945-f530cea9-46bb-4486-b2e5-d3ecf9ee2597.png)

### Desired behavior

Cypress should use a nicer-looking font.

### Test code to reproduce

Run any test in a browser.

### Cypress Version

10.11.0

### Node version

16.17.0

### Operating System

Windows 10

**Comment by lmiller1990** [comment] 2022-11-09 06:18
Do you see any failed network requests in the network tab? I wonder if the font is not getting loaded or is blocked for some reason. I am on windows, too, but it doesn't look like that for me.

**Comment by kaiyoma** [comment] 2022-11-09 17:22
No failed network requests. When I inspect the styles, I can see that `ui-monospace` is actually the first font-family being specified, so this seems like a legitimate issue with the Cypress styles:

![image](https://user-images.githubusercontent.com/10719780/200898207-06bb0460-a026-4b9f-9e9c-e91753876548.png)

**Comment by marktnoonan** [comment] 2022-11-18 20:00
Hi @kaiyoma what browser are you in in Windows when you see this? Agree it looks weird but I also don't see this behavior. Can you confirm what is showing up as the "rendered font"? For example in Chrome this is under the computed styles tab, right at the bottom: 

![Screen Shot 2022-11-18 at 2 57 54 PM](https://user-images.githubusercontent.com/8340719/202791946-d9821760-72d1-4862-82eb-079734b108a4.png)

In Safari it is under the "fonts" tab.

![Screen Shot 2022-11-18 at 2 59 05 PM](https://user-images.githubusercontent.com/8340719/202792107-4e65c628-f70a-4a0b-a818-e5622807e53b.png)

Then we can target exactly what to remove from this list.

**Comment by kaiyoma** [comment] 2022-11-18 23:58
@marktnoonan I'm running the latest version of Chrome. This is what I see in devtools:

![image](https://user-images.githubusercontent.com/10719780/202822257-0abe4e3b-dc0b-463b-850b-4678ca4061d9.png)

**Comment by marktnoonan** [comment] 2022-11-21 14:44
Thanks. Looks like the rendered font is Courier New in this case. I'll forward this feedback to design team to get a recommendation.

**Comment by kaiyoma** [comment] 2023-02-03 19:16
Interesting data point: I recently upgraded to a Windows 11 laptop and I no longer see this, so I guess the problem is with the system fonts in Windows 10.

**Comment by lmiller1990** [comment] 2023-02-05 23:55
Seems like this is limited to a subset of users, and isn't easily reproduced (so difficult to fix - I could not reproduce on Windows 10, either).

Going to close this one off - we can reopen if we've got some reliable way to reproduce.

**Closed as completed by lmiller1990** 2023-02-05 23:55 UTC
