### ISSUE TITLE
Shadow Content (User Agent) How to get pseudo element

### ISSUE THREAD

**Issue by ehsaan-shah** [cypress-io/cypress#19626] opened 2022-01-10 09:38 UTC
### Current behavior

- Please see the attached screenshot attached herewith.
- I want to click the wheel psuedo button or up-arrow and down-arrow to update the quantity:
** <div pseudo="-webkit-inner-spin-button"></div>

it is under the shadow element and I am not able to get it with the shadow() command. Cypress gives the error that element. Please see the error screenshot attached herewith.

Can you please help me with a solid working command that I can use?

Regards,

### Test code to reproduce

cy.get('div[class="j2store-add-to-cart"]').within(() => {

		//cy.get('div[class="product-qty"]').get('input[class="input-mini form-control"]').clear().type(3)
		//.shadow()
			cy.get('div[class="product-qty"]').get('input[class="input-mini form-control"]')
			.clear()
			.shadow() //.shadow('Shadow Content (User Agent)')
			.get('div[pseudo="-webkit-textfield-decoration-container"]')
			.get('div[pseudo="-webkit-inner-spin-button"]')
			.click()
		//	.find('div[pseudo="-webkit-inner-spin-button"]').click()
		cy.get('button[title="Add to cart"]').click()
	})

### Cypress Version

9.2.0

### Other

![Screenshot 2022-01-10 at 10 22 17 AM](https://user-images.githubusercontent.com/29987465/148744087-cdf2f33d-51ab-428d-8357-4b532913757c.png)
![Screenshot 2022-01-10 at 10 34 32 AM](https://user-images.githubusercontent.com/29987465/148744367-e441853c-e237-4203-a147-a774472b75fe.png)

**Comment by sainthkh** [comment] 2022-04-04 07:33
Sorry for the late reply. 

As we all know, the debugging start with reproducing the problem on the developer's environment. Could you provide a reproducible code example (in this case, the website HTML and JavaScript)?

**Comment by sainthkh** [comment] 2022-04-25 06:04
Closing because of the inacitivity.

**Closed by sainthkh** 2022-04-25 06:04 UTC
Labels: stage: awaiting response

**Comment by 787681277** [comment] 2023-01-17 09:18
I also have this issue that cannot to get element in **user-agent** shadow root
