### ISSUE TITLE
Failed to connect to firefox retrying in 1 second

### ISSUE THREAD

**Issue by nitro2112** [cypress-io/cypress#18919] opened 2021-11-15 14:14 UTC
### Current behavior

After upgrading OS to Cypress has problem with Firefox driver initialization. Sometimes tests runs after 4 retries, sometimes after 50 retries, but and usually it fails after 62 retries.

Issue appear after upgrade OS to Microsoft Windows Server 2019 (10.0.17763). Issue also appear on Microsoft Windows Server 2022 (10.0.20348)

### Desired behavior

In this situation Cypress should run test scenarios like in older OS versions or like for Chrome or Edge browsers on current OS.

### Test code to reproduce

Tests are executed by package.json script: "e2e_firefox_cli": "tsc && cypress run --browser firefox --headless"

### Cypress Version

9.0.0

### Other

I saw this problem appeared after upgrading the OS from Microsoft Windows Server 2017 to Microsoft Windows Server 2019. 
Cypress was version: 8.6.0, 
Firefox was version: 93 (headless)

**Comment by merrua** [comment] 2022-02-13 14:40
I noticed this issue with 
package.json
    "cypress:run:firefox": "node_modules\\.bin\\cypress run --browser firefox",

I opened Firefox on the machine and let it updated and it then ran correctly. It may be related to Firefox needing to update?

**Comment by BlueWinds** [comment] 2022-02-16 22:12
We did have another user report an issue with Windows Server 2019 a couple weeks back - https://github.com/cypress-io/cypress/issues/19756 - but it wasn't entirely clear what was going on there, and they were having trouble with electron rather than Firefox.

I don't have ready access to a windows server box, so it's fairly hard for me to help directly - best I can do is offer some links to our troubleshooting guides and some suggestions to try.
1. You might be able to learn more from the [DEBUG logs](https://docs.cypress.io/guides/references/troubleshooting#To-clear-App-Data).
2. Can you open firefox headlessly outside the context of Cypress? It's worth trying to figure out if this is an issue with cypress or with firefox on your system.

**Comment by Rich-Farmbrough** [comment] 2022-03-23 09:03
I'm seeing a similar issue , running the sample tests on Firefox under Debian:

Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
...
Still waiting to connect to Firefox, retrying in 1 second (attempt 26/62)

After this the test runs.  It seems very consistent.  I'm wondering if the timeout is just a little too fast.

**Comment by DomyNithanth** [comment] 2022-04-04 11:24
Any update on this issue?
Facing the issue with running via VM, but locally it's working fine.

Cypress Version : 9.5.2
Firefox version : Firefox 98 
Node Version:  v10.15.3

![image](https://user-images.githubusercontent.com/95854242/161533967-b5072655-6d7e-46b2-ade1-94a67e076472.png)

**Comment by JohnLukeBentley** [comment] 2022-06-02 04:11
I'm getting this sort of error after an upgrade to Cypress 10.0.1 (which distinguishes, for the first time, End to End V Component testing).

I've successfully migrated my project and can run End to End (e2e) tests in Chrome. But I can't run these in firefox ...

```powershell
> npm test

> testers@1.0.1 test
> npx cypress open


Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 19/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 20/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 21/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 22/62)
[etc ...]
```

To get that failed result I:

* (In effect) from the command line run ` npx cypress open`. That is, `npm test` references `scripts: { ..."test": "test": "npx cypress open"}} ...` in package.json.
* The Cypress test environment opens and I choose [E2E Testing]
* Firefox is selected. I choose [Start E2E Testing in Firefox]
* The Cypress test runner (browser) opens, with the browser body being blank and the "Still waiting to connect to Firefox, retrying in 1 second" messages being output to the command line (as above).

Windows 10 64bit Pro 21H1 (19043.1706)
Firefox 101.0 (64-bit).

**Comment by TatyCat** [comment] 2022-06-13 22:46
> I'm getting this sort of error after an upgrade to Cypress 10.0.1 (which distinguishes, for the first time, End to End V Component testing).
> 
> I've successfully migrated my project and can run End to End (e2e) tests in Chrome. But I can't run these in firefox ...
> 
> ```powershell
> > npm test
> 
> > testers@1.0.1 test
> > npx cypress open
> 
> 
> Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
> Still waiting to connect to Firefox, retrying in 1 second (attempt 19/62)
> Still waiting to connect to Firefox, retrying in 1 second (attempt 20/62)
> Still waiting to connect to Firefox, retrying in 1 second (attempt 21/62)
> Still waiting to connect to Firefox, retrying in 1 second (attempt 22/62)
> [etc ...]
> ```
> 
> To get that failed result I:
> 
> * (In effect) from the command line run ` npx cypress open`. That is, `npm test` references `scripts: { ..."test": "test": "npx cypress open"}} ...` in package.json.
> * The Cypress test environment opens and I choose [E2E Testing]
> * Firefox is selected. I choose [Start E2E Testing in Firefox]
> * The Cypress test runner (browser) opens, with the browser body being blank and the "Still waiting to connect to Firefox, retrying in 1 second" messages being output to the command line (as above).
> 
> Windows 10 64bit Pro 21H1 (19043.1706) Firefox 101.0 (64-bit).

I had the same issue with Cypress trying to connect to Firefox repeatedly. I was able to finally connect to Firefox after closing Cypress and updating npm and npx.

**Comment by JohnLukeBentley** [comment] 2022-06-14 09:24
@TatyCat, thanks for your comment. There's no need to quote the whole post, if you are responding to it, just below.

(I've since discovered) #18919 is the main issue for this. Updating to cypress 10.1.0 did change this for me (and I'm on the latest Node.js LTS, 16.15.1).

**Comment by TatyCat** [comment] 2022-06-23 15:11
@JohnLukeBentley You're welcome.

**Comment by mjhenkes** [comment] 2022-06-23 21:26
Closing as a duplicate of #22086

**Closed by mjhenkes** 2022-06-23 21:26 UTC
Labels: stage: investigating

**Comment by JohnLukeBentley** [comment] 2022-06-28 04:17
@emilyrohrbough the comment you point to is part of the thread, #18919, that I'd previously pointed to (as the more relevant thread). But good of you to tag me in any case. And indeed the current thread is now rightly close (at least there was no need to keep it open on my account).
