### ISSUE TITLE
modifyObstructiveCode is not recognized by vsc

### ISSUE THREAD

**Issue by BambiMC** [cypress-io/cypress#23501] opened 2022-08-22 20:06 UTC
### Current behavior

File: cypress.config.ts
Everything works great, but vsc doesnt recognize the modifyObstructiveCode-option.
Any other parameter like chromeWebSecurity is recognized without issues.

### Desired behavior

In this situation, Cypress should recognize the parameter just like any other one.

### Test code to reproduce

import { defineConfig } from "cypress";

export default defineConfig({
  chromeWebSecurity: false,
  modifyObstructiveCode: false,
  defaultCommandTimeout: 40000,
  pageLoadTimeout: 200000,
  viewportWidth: 1280,
  viewportHeight: 1024,
});

### Cypress Version

10.6.0

### Node version

16.16.0

### Operating System

Windows 10 x64

### Debug Logs

```shell
Error:
Argument of type '{ chromeWebSecurity: false; modifyObstructiveCode: boolean; defaultCommandTimeout: number; pageLoadTimeout: number; viewportWidth: number; viewportHeight: number; }' is not assignable to parameter of type 'ConfigOptions<any>'.
  Object literal may only specify known properties, and 'modifyObstructiveCode' does not exist in type 'ConfigOptions<any>'.ts(2345)
```

### Other

My guess is that something is missing in \node_modules\cypress\types\cypress.d.ts

_No response_

**Comment by flotwig** [comment] 2022-08-22 20:43
Duplicate of #22146

**Closed by flotwig** 2022-08-22 20:43 UTC
