### ISSUE TITLE
Cypress don't support while(true), just beacause it's async?

### ISSUE THREAD

**Issue by yangislet** [cypress-io/cypress#25929] opened 2023-02-23 06:07 UTC
### What would you like?

We often use a test mode, which includes a server and client, so that we can easily control the steps of each test case. Usually the client is only responsible for generating test cases and sending test cases, and the server is responsible for the real test case execution. implement. For example, Python builds a client, which is only responsible for sending JSON test cases. As a server, cypress is responsible for receiving JSON test cases, translating them into test cases for execution, and returning the direct results of the current test cases to the client. If Cypress doesn't support While(TRUE) mode, how can I dynamically add test cases to Cypress execution thread? In the Python Asyncio library, they provide the **asyncio.run_coroutine_threadsafe** function, which allows users to dynamically add tasks to the loop thread, but why doesn't Cypress provide the corresponding function?

### Why is this needed?

**We need Api that allow user dynamiclly append case to Cypress**

```js
const socket = io("http://localhost:5000");
var ui_case = null;
describe("template spec", () => {
  before(() => {
    cy.log("set up socket client"); 
    socket.on("connect", () => { 
      console.log("socket connect");
    });
    socket.on("disconnect", () => {
      console.log("socket disconnect");
    });
    socket.on("connect_error", (e) => {
      console.log("socket connect error", e.message);
    });

    socket.on("uicase", (data) => {
      console.log("get ui case data");
      ui_case = data;
    });

  });
  
  it("wait new ui case data", () => {
    cy.log("wait for new case"); 
    while (true) { 
      //test ui case
      if(ui_case != null){
        // translate json data to cypress api and excute case
        
        ui_case = null;
      } 
    }
  });
});
```

**Comment by marktnoonan** [comment] 2023-04-05 19:53
Thanks for reporting this and showing the example, I'm going to close this as a duplicate of some related issues that are already on our radar:

https://github.com/cypress-io/cypress/issues/3757
https://github.com/cypress-io/cypress/issues/3114

**Closed as completed by marktnoonan** 2023-04-05 19:53 UTC
Labels: type: feature, E2E
