### ISSUE TITLE
How to use Cypress Component Testing in Amplify Console

### ISSUE THREAD

**Issue by bob-lee** [cypress-io/cypress#17046] opened 2021-06-22 01:04 UTC
My project is hosted on AWS `amplify console` and I wrote some component tests using `@cypress/vue` and wonder if I can run `run-ct` command in there.

In `amplify.yml`, I tried to add `yarn cy:run-ct`:
```
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
        - yarn test
        - yarn cy:run-ct
```
which gives me an error `The cypress npm package is installed, but the Cypress binary is missing`.

Anyone managed to run-ct on Amplify console? Or is it not supported yet?

**Comment by lmiller1990** [comment] 2021-06-23 07:09
Have you run regular E2E Cypress on Amplify? To clarify; are you having trouble with Component Testing specifically, or just running Cypress on Amplify in general?

**Comment by bob-lee** [comment] 2021-06-23 07:55
@lmiller1990 having trouble with component testing. Already running e2e tests without a problem.

**Comment by lmiller1990** [comment] 2021-06-24 03:15
Interesting. I cannot see any obvious problem. I have some more questions about your environment. 

```
        - npm install
        - npm install wait-on
        - npm install pm2
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        #- yarn cy:run-ct # Dev-server compilation failed. We can not run tests if dev-server can not compile and emit assets, please make sure that all syntax errors resolved before running cypress.
        - npx pm2 start npm -- start
```

This seems a little odd to me. I wonder why the dev-server compilation is failing? I assume this is not the case locally?

That's also a very old version of mocha - Cypress bundles 7.x or 8.x I believe.

Not sure if this helps much - I might need to try out Amplify and see if I can repro the error. Have you tried running with a minimal project (eg, just one simple spec)?

**Comment by bob-lee** [comment] 2021-06-24 03:37
@lmiller1990 I'm using cypress@7.5.0 and `test` section in current `amplify.yml` above is the result of gathering informations from here and there, at least e2e tests running ok.
For component tests, to make `run-ct` work locally, I recall I had problems with devDependencies like `@cypress/webpack-dev-server` and `webpack-dev-server`.
Not sure about Amplify console environment..

**Comment by bob-lee** [comment] 2021-06-26 00:17
@lmiller1990 minimal project here, https://github.com/bob-lee/nuxt-cy-amplify, seems to have the same problem.
```
                                 # Starting phase: preBuild
                                 # Executing command: yarn install
2021-06-26T00:09:29.259Z [INFO]: yarn install v1.22.0
2021-06-26T00:09:29.334Z [INFO]: [1/4] Resolving packages...
2021-06-26T00:09:29.738Z [INFO]: success Already up-to-date.
2021-06-26T00:09:29.741Z [INFO]: Done in 0.49s.
2021-06-26T00:09:29.750Z [INFO]: # Executing command: yarn cy:run-ct
2021-06-26T00:09:29.873Z [INFO]: yarn run v1.22.0
2021-06-26T00:09:29.896Z [INFO]: $ cypress run-ct
2021-06-26T00:09:30.235Z [INFO]: The cypress npm package is installed, but the Cypress binary is missing.
                                 We expected the binary to be installed here: /root/.cache/Cypress/7.6.0/Cypress/Cypress
                                 Reasons it may be missing:
                                 - You're caching 'node_modules' but are not caching this path: /root/.cache/Cypress
                                 - You ran 'npm install' at an earlier build step but did not persist: /root/.cache/Cypress
                                 Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
                                 Alternatively, you can run 'cypress install' to download the binary again.
                                 https://on.cypress.io/not-installed-ci-error
                                 ----------
                                 Platform: linux (Amazon Linux - 2 (Karoo))
                                 Cypress Version: 7.6.0
2021-06-26T00:09:30.247Z [WARNING]: error Command failed with exit code 1.
2021-06-26T00:09:30.247Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-06-26T00:09:30.254Z [ERROR]: !!! Build failed
2021-06-26T00:09:30.255Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-26T00:09:30.255Z [INFO]: # Starting environment caching...
2021-06-26T00:09:30.267Z [INFO]: # Uploading environment cache artifact...
2021-06-26T00:09:30.401Z [INFO]: # Environment caching completed
```

**Comment by bob-lee** [comment] 2021-06-26 05:58
Got it working, cypress component tests (`yarn cy:run-ct`) could be run in test.phases.test.commands section in `amplify.yml` as below:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm install
        - npm install wait-on
        - npm install pm2
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:3000'
    test:
      commands:
        - 'yarn cy:run-ct'
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill
```

**Comment by lmiller1990** [comment] 2021-06-28 01:03
Great, good to know! Running E2E and CT should be almost identical - I wonder why the phases need to be different 🤔 

I'll close this one off since it looks like it's solved, and not a bug in Cypress.

**Closed by lmiller1990** 2021-06-28 01:03 UTC
Labels: component testing
