### ISSUE TITLE
An uncaught error was detected outside of a test

### ISSUE THREAD

**Issue by plweil** [cypress-io/cypress#27397] opened 2023-07-26 15:44 UTC
### Current behavior

I try to run any simple E2E test and I get this error:

```
TypeError
The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > h2 is null

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

I'm using debug, and found that the line that creates the error is in /__cypress/tests?p=cypress/support/e2e.js, also listed in the console as cypress_runner.js.

```
Uncaught (in promise) TypeError: h2 is null
    j$1 http://wisconsin-idea.test/__cypress/tests?p=cypress/support/e2e.js:24764
    <anonymous> http://wisconsin-idea.test/__cypress/tests?p=cypress/support/e2e.js:25528
    <anonymous> http://wisconsin-idea.test/__cypress/tests?p=cypress/support/e2e.js:2
    <anonymous> http://wisconsin-idea.test/__cypress/tests?p=cypress/support/e2e.js:3
    evalScripts http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:168482
    tryCatcher http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:18744
    gotValue http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:17886
    gotAccum http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:17875
    tryCatcher http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:18744
    _settlePromiseFromHandler http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16679
    _settlePromise http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16736
    _settlePromiseCtx http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16773
    _drainQueueStep http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13455
    _drainQueue http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13444
    _drainQueues http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13460
    drainQueues http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13330
```

I don't understand what exactly this file is, where it comes from, and what it contains. But the flagged line is the reference to `h2:dataset.page` in this function on line 24763:

```javascript
async function j$1({ id: e2 = "app", resolve: o2, setup: n2, title: p2, progress: t2 = {}, page: a2, render: l2 }) {
    let f2 = typeof window > "u", h2 = f2 ? null : document.getElementById(e2), y2 = a2 || JSON.parse(h2.dataset.page), r2 = (c2) => Promise.resolve(o2(c2)).then((b2) => b2.default || b2), s2 = [], i2 = await r2(y2.component).then((c2) => n2({ el: h2, App: I$1, props: { initialPage: y2, initialComponent: c2, resolveComponent: r2, titleCallback: p2, onHeadUpdate: f2 ? (b2) => s2 = b2 : null }, plugin: $$1 }));
    if (!f2 && t2 && Z$1(t2), f2) {
      let c2 = await l2(createSSRApp({ render: () => h$1("div", { id: e2, "data-page": JSON.stringify(y2), innerHTML: i2 ? l2(i2) : "" }) }));
      return { head: s2, body: c2 };
    }
  }
```

### Desired behavior

This test should run without any errors. It has Laravel seed some fake data and has the use click the Register button, which should take them to the registration form page. That's it.

### Test code to reproduce

Here is the test spec I am working with:

```javascript
describe('Login flow for Unregistered user with NetID', function () {
  beforeEach(function () {
    Cypress.config('baseUrl', 'http://widea-unregistered.test/')
    cy.exec('php artisan db:seed --env=testing')
  })

  it.only('Redirects user to registration form', function () {
    cy.visit('/')

    cy.get('[data-cy=login]').click()

    cy.url().should('include', '/register')
  })

})
```

### Cypress Version

12.17.2

### Node version

v16.19.1

### Operating System

Mac OS 12.7

### Debug Logs

```shell
Console was cleared. index-67d905f1.js:112171:50
TypeError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.

  > h2 is null

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
at j$1 (http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/login-unregistered.cy.js:24764:86)
at <unknown> (http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/login-unregistered.cy.js:25528:6)
at <unknown> (http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/login-unregistered.cy.js:2:66)
at <unknown> (http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/login-unregistered.cy.js:3:3)
at ../driver/src/cypress/script_utils.ts/evalScripts (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:168482:23)
at tryCatcher (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:18744:23)
at gotValue (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:17886:18)
at gotAccum (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:17875:25)
at tryCatcher (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:18744:23)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16679:31)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16736:18)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16781:10)
at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16861:18)
at _drainQueueStep (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13451:12)
at _drainQueue (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13444:24)
at ../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13460:16)
at ../../node_modules/bluebird/js/release/async.js/</Async/this.drainQueues (http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13330:14) index-67d905f1.js:112167:13
    logError http://wisconsin-idea.test/__/assets/index-67d905f1.js:112167
    addGlobalListeners http://wisconsin-idea.test/__/assets/index-67d905f1.js:124401
    emit2 http://wisconsin-idea.test/__/assets/index-67d905f1.js:117863
    listen http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:188745
    emit http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:28198
    emit http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:188808
    onPrint http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:187623
    _onPrintClick http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:187627
    initializer http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:188929
    executeAction http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:54695
    n http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:54695
    ca http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65341
    ja http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65342
    ka http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65342
    wa http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65344
    Aa http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65345
    ya http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65345
    Da http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65348
    Ad http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65411
    Gi http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65577
    Kb http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65366
    Dd http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65413
    Ii http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65578
    unstable_runWithPriority http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:69104
    Ii http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65578
    Cd http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:65412

​
```

**Comment by mike-plummer** [comment] 2023-07-26 19:09
Hi @plweil , sorry to hear you're having trouble. The error message you reference indicates there is an error being generated by your project's [Support File](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file) (located at `cypress/support/e2e.js`), which is the reason for the "...originated from your test code, not from Cypress" portion of the error message. Can you review this file (or post it here) to see what custom logic is in there that may be failing?

**Comment by plweil** [comment] 2023-07-26 19:51
hi @mike-plummer. Thanks for responding.! Initially, I'd prefer to do without a Support File, just to keep things as simple as possible until I was sure basic E2E tests were running ok. The old file had everything commented out; originally it pulled in a `commands.js` file.

`// Import commands.js using ES2015 syntax:
//import './commands'`

So since my initial post, I did a clean install of Cypress (removed the Cypress folder, all specs, the application support folder in the Library...), and entered `supportFile: false` in the `cypress.config.ts` file.

```javascript
import { defineConfig } from "cypress";
import vitePreprocessor from 'cypress-vite'

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      on('file:preprocessor', vitePreprocessor())
    },
    baseUrl: 'http://wisconsin-idea.test/',
    supportFile: false,
  },
});
```


After launching Cypress and getting the default config files installed (and then edited as above), I tried running the example spec, and got the same error. 

```javascript
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})
```

If this is not coming from the support file (which doesn't exist), where is it coming from? And how can one tell? I wish I had more of a hint. Is it coming from one of my application files? A node module? I'd love to be able to clean it out if I could only find out where it is.


From the console:

```
Uncaught (in promise) TypeError: h2 is null
    j$1 http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/spec.cy.ts:24764
    <anonymous> http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/spec.cy.ts:25528
    <anonymous> http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/spec.cy.ts:2
    <anonymous> http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/spec.cy.ts:3
    evalScripts http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:168482
    tryCatcher http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:18744
    gotValue http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:17886
    gotAccum http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:17875
    tryCatcher http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:18744
    _settlePromiseFromHandler http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16679
    _settlePromise http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16736
    _settlePromiseCtx http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:16773
    _drainQueueStep http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13455
    _drainQueue http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13444
    _drainQueues http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13460
    drainQueues http://wisconsin-idea.test/__cypress/runner/cypress_runner.js:13330

```

**Comment by mike-plummer** [comment] 2023-07-26 20:08
@plweil Hmm, is it possible this error is being thrown by the page under test (bad JS included when `wisconsin-idea.test` is loaded that throws an uncaught exception)? The browser's devtools might give you a hint. Could you try removing your `baseUrl` value from the config before running the very simple spec from your previous comment to see if you get different behavior?

I set up a project that attempts to reproduce your basic setup (`cypress`, `cypress-vite`, `typescript`, used config from above, scaffold new e2e project + run simple example spec) and the test runs successfully, but I can't access the `baseUrl` so I can't tell whether that page might be generating errors. If you're able to reproduce this behavior on a public URL (something I would be able to access) let me know as well as if there are any other dependencies/customizations to your project setup. Best case would be a fork of [`cypress-test-tiny`](https://github.com/cypress-io/cypress-test-tiny) that I could run locally to debug the issue.

As additional info, Cypress does have built-in support for triaging/addressing uncaught errors that are generated by application code - there is a [recipe here](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__errors) to show ways to analyze and suppress errors as appropriate. This may be useful if it does turn out to be the page-under-test generating the uncaught errors.

**Comment by plweil** [comment] 2023-07-26 20:34
@mike-plummer Removing the `baseUrl` value from the config did not change anything. Rats; same error. As to your first question, I'm not seeing any js errors when I load http://wisconsin-idea.test/. I'll work on the other two options you mentioned and will get back to you -- although I don't think I can put this on a public URL. FWIW, this is a Laravel/Vue3/Inertia application. Are you aware of any issues between Cypress and Inertia.js? Thanks again!

**Comment by plweil** [comment] 2023-07-27 02:10
@mike-plummer how would I utilize `cypress-test-tiny` to get you something (i.e., a copy of my app) that you could run locally? I did take a look at it, but am not sure what to do with it. I'm taking it that there's got to be **something** in my application js that is causing this error.

**Comment by mike-plummer** [comment] 2023-07-27 12:56
@plweil Creating a fork of `cypress-test-tiny` is what we ask for when attempting to resolve a bug within Cypress. If you're able to reproduce the behavior you're seeing against a different website (one that we would be able to access) then it may be a bug and we can look into it if you can put together a reproducible example. If it's only occurring on your private website then it likely is not a bug. In that situation you can diagnose using an Uncaught Exception handler (see linked recipe above), or with [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs).

Have you tried using the browser's DevTools to enable its uncaught exception breakpoint to see if you can determine what piece of code is actually throwing? Here's what that looks like in Chrome; turning this on when re-running your tests may at least tell you what area of code is throwing the error and whether it can be fixed or just needs to be squashed using the Cypress Uncaught Exception handler.
![Screenshot 2023-07-27 at 7 52 46 AM](https://github.com/cypress-io/cypress/assets/11482842/47bca2c3-e596-413b-9c1d-ef302d32aa67)

**Comment by plweil** [comment] 2023-07-27 16:08
@mike-plummer Well, I can't seem to get anywhere. The uncaught exception handler finds nothing. The doc section on Debug Logs says to enter `DEBUG=cypress:* cypress run` in the Terminal, but that just gives me "command not found: cypress". I tried using the Cypress Uncaught Exception handler, but n my case it does nothing. It's as if the text doesn't even begin to run. I don't know what Cypress actually does when you start a test, but it generates that runner file... I don't know if it's gathering and testing code from my application first or what. But it won't even run a test that logs a message to the console. Is it checking my application code first? Is it checking all of the node modules in the project, or the ones I am importing? I don't think it ever even gets to the tests. I'm used to doing a lot of troubleshooting, and sorry if I sound kind of whiny and helpless, but I'm feeling pretty lost with this one.

**Comment by mike-plummer** [comment] 2023-07-27 16:25
**Debug Logs**
You would need to adapt the command to launch Cypress depending on how it's configured in your project. If you're using `npx` it would be `DEBUG=cypress:* npx cypress run`, or if you have a Node script defined it might be `DEBUG=cypress:* npm run test:cypress`, for `yarn` it might be `DEBUG=cypress:* yarn cypress run`

**Browser devtools**
Did you try using the browser devtools to "see" the uncaught exception? You should be able to link back to the exact line of code throwing that error which would tell you whether it's a third-party library, something in your test code, etc. Depending on how things are packaged it might be minified which would make it trickier, but it may give you some hints. Is there anything being reported in the devtools console?

In your stacktrace above, the line throwing the error is being reported `j$1 http://wisconsin-idea.test/__cypress/tests?p=cypress/e2e/spec.cy.ts:24764` - you should be able to click that to take you there in the devtools (it will likely change between runs). In this case, `spec.cy.ts` is a bundled version of your test which includes all the code for that test (including anything imported/referenced by that test)

**Bare minimal reproduction**
Have you tried putting together a completely minimal Cypress project to see if the same issue exhibits? Just want to make sure there isn't a third-party dependency, weird proxy injection, or some other build config that's interfering specific to your current project or machine

`mkdir cypress-minimal-test && cd cypress-minimal-test`
`npm init -y`
`npm i -D cypress`
`npx cypress open`
Open e2e mode & open browser
Create new spec
Run spec

**Comment by plweil** [comment] 2023-07-27 16:52
@mike-plummer Ok, I've finally(!) tracked it down to a line in the [Inertia.js adapter for Vue 3](https://github.com/inertiajs/inertia/tree/master/packages/vue3). I kind of suspected that it had something to do with Inertia. I guess that I should open an issue over there, unless there's a newer release that resolves it (I didn't see any Cypress issues there). In the meantime, I gather that there is no way to tell Cypress to ignore it? And, to be complete, are we sure that this is not a bug in Cypress? Has there been any testing with Inertia apps?

**Comment by mike-plummer** [comment] 2023-07-27 17:05
@plweil Just to confirm, are you attempting to import anything from IntertiaJS into your spec file? I'm not sure how your test is failing in this way without triggering the uncaught exception handler - definitely strange unless something is ending up in your spec file *before* that handler gets set up. 🤔 

I'm not aware of any issues with InertiaJS + Cypress, but I'm definitely not an InertiaJS expert.

I created a quick test suite against the [IntertiaJS demo site](http://demo.inertiajs.com/) and didn't see any problems, so the issue is either unique to the Vue adapter (maybe the demo app is a different framework), or your test project is doing something unique that I haven't reproduced. If you're able to reproduce the issue against the InertiaJS demo site I'd be happy to dig in deeper.

**Comment by plweil** [comment] 2023-07-27 17:19
@mike-plummer I am not explicitly importing Inertia or anything else into the spec file:

```typescript
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})

```

How would it even know that I'm using Inertia someplace, except for the baseURL in the config file? Maybe I should try that demo site with the Vue 3 adapter, if that's possible. If that can help narrow it down.... In the meantime, I'm logging an issue with Inertia.

**Comment by plweil** [comment] 2023-07-27 19:58
@mike-plummer I got the Inertia demo set up, updated the composer and node packages, and it ran a simple Cypress E2E spec with no errors.

So it must be something about my application, or in my application directory, anyway. Question: do I need to install the [cypress-vite plugin](https://github.com/mammadataei/cypress-vite) to run E2E specs if I'm using Vite instead of webpack? Or does Cypress support this out of the box now?

**Comment by plweil** [comment] 2023-07-27 20:23
@mike-plummer After installing a Mac OS update, rebooting, and doing a clean install with npm, I re-ran the same and another spec with the same content (same as earlier). I still see the same error in the console.

In the (Electron) browser, it says: "No tests found. Cypress could not detect tests in this file."

In Firefox, it's the same as before.

If I start to get desperate (maybe in the next five minutes), I may create a clean, brand new application and start from scratch, copying files in bit by bit. Maybe there's some phantom corruption in there someplace.

**Comment by mike-plummer** [comment] 2023-07-27 20:33
@plweil `cypress-vite` is a third-party plugin that changes how your *tests* are bundled. By default Cypress uses Webpack to bundle the JS used by the test runner, but this has no dependency on how your *application* is bundled. From Cypress' perspective your application is just a webpage, and the bundler it uses is irrelevant. Since `cypress-vite` is not a part of core Cypress (it's a community-maintained plugin) I can't say for certain whether it's causing your issue - you might want to try stripping out any customizations from your `cypress.config.*` file just to reduce the surface area of potential issues.

**Comment by plweil** [comment] 2023-07-27 21:03
@mike-plummer Thanks. Just so I'm clear, are you saying that I don't necessarily need an extra plugin or to bundle my tests with Vite, and can run E2E tests of my application with Cypress out of the box, regardless of which bundler I use in my application? I do have the `cypress.config` file stripped down to a minimum.

**Comment by plweil** [comment] 2023-07-27 21:18
@mike-plummer Sorry to shower you with messages. I removed the plugin, got a message that I needed a  `tsconfig.json` file, which I added. Ran the same spec and it passed with no errors. Spec-wise, not much of a test. But just maybe I found the cause of this torturous experience -- I hope I'm not jumping the gun. For some reason I misread the description of that plugin and thought I needed it. I wish somewhere in the Cypress docs it would say straight out: "Works fine with Vite!" Thanks for your efforts to help and for putting up with me.

**Comment by mike-plummer** [comment] 2023-07-27 21:39
@plweil No problem, glad you've narrowed down a suspect! You are correct - Cypress e2e tests do not care how your website is bundled. It's just a website, loaded by the browser. There is zero dependency; Cypress is happy to test pages made with any bundler or no bundler at all. Things are a bit more complicated when you're using [Component Testing](https://docs.cypress.io/guides/component-testing/overview) since that *does* care about your bundler, but that's a separate discussion.

We make no mention of it in the docs because the defaults should work fine for 99.999% of our users. The `cypress-vite` plugin is meant for power-users who have thousands of tests that are extremely complex and want a potential performance bump. Sorry you were led astray, glad you stuck with it 💯

**Comment by 0xshubhs** [comment] 2023-08-07 14:13
The error you're encountering seems to originate from your Cypress test code, specifically within the test file `/cypress/e2e/login-unregistered.cy.js`. The error message suggests that there's an issue with the variable `h2` being null. This variable is being used within a function named `j$1`.

From the provided debug logs and code snippets, it's a bit challenging to pinpoint the exact source of the issue without the full context of your application's code and structure. However, I can offer some general guidance on how to approach this issue:

1. **Variable `h2` is null:** The error message indicates that `h2` is null at the line where the error is occurring. The issue might be related to how `h2` is supposed to be populated or used. You should look into where `h2` is supposed to be initialized or assigned a value before this function is called.

2. **Async Function `j$1`:** The async function `j$1` seems to handle various asynchronous operations, and it appears to be interacting with the page's DOM elements and data. It's important to understand how this function is being called and what data is being passed to it.

3. **Element Retrieval and Dataset Usage:** It seems like `h2` is an HTML element that's being retrieved using `document.getElementById(e2)` where `e2` might be the value "app". The error suggests that this element is not found, which might indicate a problem with the HTML structure or the element's id attribute.

4. **Debugging Steps:**
   - Check if the element with id "app" is present in the DOM when the test runs.
   - Confirm that the dataset attribute "data-page" is correctly set on the element.
   - Double-check that the expected data structure is assigned to `y2` before it's being used.
   - Verify that the rest of the code within the function `j$1` is working as intended.

5. **Async/Promise Handling:** The error message also mentions an unhandled promise rejection. Make sure that all promises within your code are properly handled using `async/await` or `.then()` syntax to prevent unhandled promise rejections.

6. **Laravel and Backend Setup:** Since your test involves interaction with a Laravel application and seeding fake data, ensure that your backend setup and database seeding are working correctly. Any issues with data initialization could potentially impact the behavior of your tests.

7. **Cypress Configuration:** Make sure that your Cypress configuration (`cypress.json` or other configuration files) is correctly set up, including the `baseUrl` configuration.

If you continue to face issues after going through these steps, consider providing more context about the code around the `j$1` function, the HTML structure of your page, and any additional relevant information. This will help in providing more specific guidance on resolving the issue.

**Closed as completed** 2023-08-07 14:27 UTC
