### ISSUE TITLE
Uncertain Assertion errors

### ISSUE THREAD

**Issue by yashjain560** [cypress-io/cypress#25413] opened 2023-01-10 14:01 UTC
### Current behavior

The tests have abnormal behavior, as they are working fine on local development but showing assertion errors at the cloud.cypress.io, The portal sometimes gets stuck and cannot find the root cause of the issue.

https://user-images.githubusercontent.com/117162355/211545676-5f827545-4dff-4cf6-bdfe-119b3b29b9e7.mp4

I have Attached the screenshots of my local testing and on the cloud
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/117162355/211563779-48795e88-b45c-4365-bac9-f30b0e074816.png">
![image](https://user-images.githubusercontent.com/117162355/211563865-99d9ff6a-d06b-40ce-be59-1d4f643b354c.png)

### Test code to reproduce
```js
describe('Whydonate Login Page (account)', { tags: ['@accountTag'] }, () => {
  beforeEach(() => {
    cy.visit('https://whydonate.in');
  });
  it('The User exists', () => {
    cy.wait(2000);
    cy.get('.cc-dismiss').click();
    cy.get('#loginButton > span.mat-button-wrapper').click();
    cy.get('#loginEmail').type('abdur@whydonate.nl');
    cy.get('#loginPassword').type('Rehman95');
    cy.get('#userLogin').click();
    cy.request('POST', 'https://account-staging.whydonate.workers.dev/account/user/login/', { email: 'abdur@whydonate.nl', password: 'Rehman95' })
  });

  it('The User does not exists', () => {
    cy.wait(2000);
    cy.get('.cc-dismiss').click();
    cy.get('#loginButton > span.mat-button-wrapper').click();
    cy.get('#loginEmail').type('aur@whydonate.nl');
    cy.get('#loginPassword').type('rhman95');
    cy.get('#userLogin').click();
    cy.wait(4000);
  });

  it('The empty login try', () => {
    cy.wait(2000);
    cy.get('.cc-dismiss').click();
    cy.get('#loginButton > span.mat-button-wrapper').click();
    cy.get('#userLogin').click();
    cy.wait(4000);
  });

});
```

### Cypress Version

11.1.0

### Node version

16

### Operating System

mac Os ventura 13.0.1

**Comment by astone123** [comment] 2023-01-12 17:17
@yashjain560 it looks like there are two separate issues here

- The video recording freezing
- The test flaking in CI

For diagnosing the flake, you could try enabling [test retries](https://docs.cypress.io/guides/guides/test-retries) in CI to see if running your test case multiple times after it fails makes it succeed. 

I would also recommend running the suite again to get a video where we can clearly see the failure happen. This will give us a better idea of how to improve our assertion. If an element isn't being found within the timeout (like in this case), it usually means that the element wasn't loaded on screen fast enough. Maybe there is another element or network request we can wait for before asserting to make our test less flaky.

Also see our docs section on [debugging flake](https://docs.cypress.io/guides/guides/debugging#Debugging-flake). Please let us know if this helps. Thanks

**Comment by ZachJW34** [comment] 2023-01-23 15:56
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as completed by ZachJW34** 2023-01-23 15:56 UTC
