### ISSUE TITLE
Huge Memory Usages

### ISSUE THREAD

**Issue by ANSHUL786** [cypress-io/cypress#28184] opened 2023-10-31 08:33 UTC
### Test code to reproduce

In my code after the execution for 10 min it goes to 4.2 GB memory. after some time it goes into "Out of memory" state

Is there a way to either increase memory in cypress or decrease the quality

![image](https://github.com/cypress-io/cypress/assets/20628265/14db4c79-39e5-4535-b9cb-7144d48560f4)

### Cypress Mode

cypress run

### Cypress Version

13.3.3

### Browser Version

Chrome 118

### Node version

18.17.1

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment] 2023-10-31 13:03
Assuming this is during cypress open, you could try setting numTestsKeptInMemory to a lower number or 0, you would then lose the time travel snapshots, but this uses a bit of memory.

Closing as duplicate of https://github.com/cypress-io/cypress/issues/4164

**Closed as completed by jennifer-shehane** 2023-10-31 13:03 UTC
Labels: type: duplicate
