### ISSUE TITLE
how to resolve heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by elamathym** [cypress-io/cypress#21124] opened 2022-04-19 05:20 UTC
### What would you like?

Created Cypress project for api automation. Getting heap limit allocation error when we executed 600+ scenario at a time.

### Why is this needed?

Please find the error below
<--- Last few GCs --->

[7444:0000023889DDFCE0] 7869450 ms: Mark-sweep 4060.4 (4120.5) -> 4044.2 (4120.8) MB, 3707.9 / 0.0 ms (average mu = 0.137, current mu = 0.010) allocation failure scavenge might not succeed
[7444:0000023889DDFCE0] 7872965 ms: Mark-sweep 4062.4 (4122.3) -> 4043.7 (4119.4) MB, 3463.8 / 0.0 ms (average mu = 0.080, current mu = 0.014) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

--package.json file

{
"name": "core_apiautomation",
"version": "1.0.0",
"description": "Core API Automation by PSCS",
"main": "index.js",
"scripts": {
"scripts": "cypress run",
"test": "npm run scripts"
},
"author": "Nandakumar & Elamathy",
"license": "ISC",
"devDependencies": {
"@types/cypress-cucumber-preprocessor": "^4.0.1",
"cypress": "^9.5.1",
"cypress-cucumber-preprocessor": "^4.3.0",
"cypress-multi-reporters": "^1.2.4",
"mocha-junit-reporter": "^2.0.2",
"start-server-and-test": "^1.14.0"
},
"dependencies": {
"ajv": "^8.8.2",
"cypress-xpath": "^1.6.2",
"moment": "^2.29.1",
"mysql": "^2.18.1"
},
"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": false,
"step_definitions": "cypress/support/step_definitions/",
"cucumberJson": {
"generate": true,
"outputFolder": "cypress/cucumber-json",
"filePrefix": "",
"fileSuffix": ".cucumber"
}
},
"keywords": []
}

**Comment by davidmunechika** [comment] 2022-04-19 13:13
Duplicate of: https://github.com/cypress-io/cypress/issues/20846

**Comment by davidmunechika** [comment] 2022-04-19 13:19
@elamathym Is there any way you could provide a reproducible example (ideally a demo repo) that we could use to recreate this issue?

**Comment by elamathym** [comment] 2022-04-19 16:34
@davidmunechika  we are doing api automation. We have around 200+ api's and we created framework with cucumber. When we execute all 200+ api's at a time we are facing memory leak exception

**Comment by BlueWinds** [comment] 2022-06-23 16:33
Going to close as duplicate of https://github.com/cypress-io/cypress/issues/17853. We should hopefully have a patch release out to address it today or tomorrow.

**Closed by BlueWinds** 2022-06-23 16:33 UTC
Labels: type: duplicate, stage: backlog
