### ISSUE TITLE
cy.intercept not behaving the same between GET and PUT HTTP requests

### ISSUE THREAD

**Issue by lvkron7809** [cypress-io/cypress#9341] opened 2020-11-25 23:19 UTC
### Current behavior
When migrating from `cy.route` to `cy.intercept` I observed the following behavior in `cy.intercept` between GET and PUT calls.  It appears that even though the Cypress runner is not saying the call is being stubbed that it actually is.  I also observed that calls are not being labeled as stubbed when the calls are made in the body of the test as seen with `cy.route`.

![image](https://user-images.githubusercontent.com/45778490/100290320-ae15aa80-2f40-11eb-9e3c-7c9aeda90ebf.png)

![image](https://user-images.githubusercontent.com/45778490/100290332-b4a42200-2f40-11eb-8721-1a227b520161.png)

### Desired behavior
The test runner should indicate a stub as it did with `cy.route`

### Test code to reproduce
When passing an empty string for the response the command seems to be working as expected.
I verified this by not entering anything for the response but found that a database entry had been created. 
I did NOT get a new database entry when sending an empty string as the response as expected.

PUT CALLS
![image](https://user-images.githubusercontent.com/45778490/100289863-8a9e3000-2f3f-11eb-81b7-99438d94852a.png)

GET CALLS
![image](https://user-images.githubusercontent.com/45778490/100290175-50815e00-2f40-11eb-96b7-39343518ed40.png)

### Versions

Cypress v6.0.0

**Comment by jennifer-shehane** [comment] 2021-01-20 06:06
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Please also make sure to update to our latest Cypress version as a lot of intercept bugs have been fixed since this release.

**Closed by jennifer-shehane** 2021-01-20 06:06 UTC
Labels: pkg/net-stubbing
