### ISSUE TITLE
Currently there exists no way to run a suite of spec files in Cypress

### ISSUE THREAD

**Issue by adokania** [cypress-io/cypress#263] opened 2016-10-12 20:39 UTC
Mocha has a --grep option that takes in a pattern and runs all spec files that match it. I would like cypress to support this feature as there are times where i want to group together a few spec files in my CI build but not run all the spec files at once.

The --spec option allows you to run a single spec file but not a combination.

**Comment by adokania** [comment] 2016-10-21 20:23
Is there any update/ETA  on this feature?

**Comment by brian-mann** [comment] 2016-10-26 13:23
No updates yet - although mocha supports this out of the box (for node processes), Cypress runs in the browser, and we'll have to specifically code an integration for this to work well.

For instance, this flag makes sense when running all of the tests once, but it doesn't work so well when working in the GUI mode.  

If you were to `cypress open --grep foobar`, we could initially run the GUI tests with that grep, but then how do you "remove" this grep option? Internally when you use `.only` that will actually obliterate any passed in `--grep` flag.

What if both an `.only` and `--grep` flag was passed?

**Comment by adokania** [comment] 2016-11-01 04:12
I understand that it can get tricky to support this in the browser but maybe that use-case is not as important.

I think the use case of this flag is mostly when used to run the tests through the command line (atleast in my scenario) where I want to batch together specific test files when running on CI or locally using the `cypress run --grep foobar` command. Maybe this command like the '--reporter' flag can be supported only when running through command line?

**Comment by brian-mann** [comment] 2016-11-01 18:55
Okay thats a good point, adding this specifically for the CLI would be much easier.

**Comment by adokania** [comment] 2016-11-16 20:08
Any updates, if this is easy can we pls have it in the next release. Will help us quite a bit.

**Comment by adokania** [comment] 2016-12-14 21:34
Hello, is this feature now available to use?

**Comment by brian-mann** [comment] 2016-12-17 04:32
Nope. When its ready this issue will be closed and you'll see it in the changelog. Unfortunately there are higher priority features / bugs we're working on. You can look at our projects roadmap for `0.18.x` work too and see the issues we're dealing with.

In January we'll have more bandwidth as some of the bigger projects we're working on will be done.

We are working towards an open source release which will make it possible to accept community contributions.

**Comment by jennifer-shehane** [comment] 2018-04-11 15:59
Closing as duplicate of #681 - this should be released soon.

**Closed by jennifer-shehane** 2018-04-11 15:59 UTC
Labels: cli, type: feature

**Comment by bmanuel** [comment] 2018-04-15 16:50
@brian-mann is there any documentation on how to go about running individual suites?

**Comment by jessejoe** [comment] 2018-05-08 03:40
@brian-mann I think @bmanuel was asking for documentation on how to run multiple spec files, since you commented that this issue was fixed in #1583, but the PR doesn't have much detail.

**Comment by bmanuel** [comment] 2018-05-08 22:14
@brian-mann, @jessejoe nailed it. Sorry, I forgot to respond right away with that.
