### ISSUE TITLE
Cypress runner DOM snapshots differ from viewport

### ISSUE THREAD

**Issue by Spelllman** [cypress-io/cypress#9630] opened 2020-12-10 22:19 UTC
When running a test which goes into my app and selects a value from the dropdown using select(), the viewport of the Cypress Runner shows my value being selected, however, if I click on the individual steps, the DOM snapshots show the dropdown in its default state.  I've added waits and other speed bumps to make sure there was plenty of time between steps for the page to load completely, but no luck. I'm running Cypress 6.0.1.

![Screen Shot 2020-12-10 at 5 11 40 PM](https://user-images.githubusercontent.com/38104718/101836196-f02b1880-3b0a-11eb-9e5b-cc5d5739a86d.png)
![Screen Shot 2020-12-10 at 5 12 36 PM](https://user-images.githubusercontent.com/38104718/101836198-f0c3af00-3b0a-11eb-8229-f21f6d50d99b.png)

**Comment by jennifer-shehane** [comment] 2020-12-11 06:48
Duplicate of https://github.com/cypress-io/cypress/issues/4443

**Closed by jennifer-shehane** 2020-12-11 06:48 UTC
