### ISSUE TITLE
Origin url set up wrongly when landing page redirects to new login domain

### ISSUE THREAD

**Issue by mwalesa89** [cypress-io/cypress#27464] opened 2023-08-04 08:39 UTC
### Current behavior

Situation: 
Application under address https://ABC.run  does not contain any public page (even 404 is not public). The application landing page if no session is available redirects into  https://XYZ/login.

I would like to use cy.origin to be able to set up the login properly. 
When I'm trying to set up cy.origin to XYZ it's showing error, that I can not set origin to same that top. 

In this case the origin is set up after cy.visit() is called, redirected (http 302) and the login page (XYZ) is loadded (http 200).
In this situation when creating page objects I would need to wrap every method with cy.origin() wchich is not the best solution.

### Desired behavior

I've got several propositions how it should work:
1. Set origin before test start (before cy.visit is called)
2. Set the main origin after login
3. Define main origin and "login" origin. 

### Test code to reproduce

I can not provide any test scripts - the app that is under test is not available for public. 

### Cypress Version

12.17.3

### Node version

14.16.0

### Operating System

Windows 10

### Debug Logs

```shell
-
```

**Comment by nagash77** [comment] 2023-08-04 12:21
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. 

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by irbrad** [comment] 2023-08-07 22:31
We're seeing the same thing happen.  I have a test starting with `cy.visit('https://www.google.com')` and then I use `cy.origin` to change to our app domain.  Finally I log in via our web page and I never actually get logged in.  The session cookies seem to set for the appropriate domains but the browser just stays on logged out.  If I remove the initial visit to Google, the browser logs in just fine.  I imagine the Cypress Cloud login page would do the same thing as our app.

**Comment by nagash77** [comment] 2023-08-16 18:38
Unfortunately we have to close this issue due to inactivity.

**Closed as not planned by nagash77** 2023-08-16 18:38 UTC
