### ISSUE TITLE
'Warning: We failed capturing this video' sometimes on cypress 13; comes and goes without any changes

### ISSUE THREAD

**Issue by joshkaplan** [cypress-io/cypress#28466] opened 2023-12-06 03:49 UTC
### Current behavior

Cypress fails to capture video on 13.16.0 and 13.16.1. Previously, we were on 12.x without issues.

All tests are passing (none are skipped), so this appears to be a distinct issue from https://github.com/cypress-io/cypress/issues/27898

Interestingly, disabling Cypress Cloud (`record`) resolves the issue. However, we are going to be using cypess cloud soon, so this is not a long-term solution.

```
Warning: We failed capturing this video.

This error will not affect or change the exit code.

TimeoutError: operation timed out
     at afterTimeout (/pokey/tests/.cache/cypress/13.6.0/Cypress/resources/app/node_modules/bluebird/js/release/timers.js:46:19)
     at Timeout.timeoutTimeout [as _onTimeout] (/pokey/tests/.cache/cypress/13.6.0/Cypress/resources/app/node_modules/bluebird/js/release/timers.js:76:13)
     at listOnTimeout (node:internal/timers:569:17)
     at process.processTimers (node:internal/timers:512:7)
```

### Test code to reproduce

Mainly tested on 2 very short, near instant, passing tests

### Cypress Version

13.6.0, 13.6.1

### Node version

18.16.1

### Operating System

Linux (docker), mac OS 14.1

**Comment by jennifer-shehane** [comment] 2023-12-06 14:23
@joshkaplan If there’s any way to provide a way to reproduce that would be helpful. 

In Cypress 13 versions, we have Test Replay captured. If you haven’t looked at those results instead of video already, I would suggest trying that. https://docs.cypress.io/guides/cloud/test-replay#What-Is-Test-Replay

**Comment by joshkaplan** [comment] 2023-12-07 20:34
@jennifer-shehane update: this has gone away on our end, without changing _**anything**_. the exact same code/dependencies/environment/tests that consistently reproduced this 2 days ago no longer does. i have checked out the exact commit linked to those^ logs and run on the same machine to verify.

the most likely thing i can think of that would cause this behavior is that there was some kind of issue in the network calls to cypress cloud

a few more details that can maybe help you all figure out what was going on:
* the exact timestamp we got the last of the warnings: `[2023-12-06T03:33:19Z]`
  * it may have persisted past this time, we just turned off cypress cloud at that point
  * i can try to look through our logs to find the earliest timestamp, if that would be helpful)
* we are also getting this warning (it's not a problem, but perhaps that's related to the failure mode)
```
You've exceeded the limit of test results under your free billing plan this month.

To continue getting the full benefits of your current plan, please visit your billing to upgrade.

https://on.cypress.io/set-up-billing
```

**Comment by jennifer-shehane** [comment] 2023-12-07 22:16
Yah, I’ve seen this behavior in another test at least, that was only occurring in v13, not v12, on the Cloud. Does this happen to be a very short test? Like it has a short duration? 2 secs or something?

**Comment by joshkaplan** [comment] 2023-12-07 22:40
> Does this happen to be a very short test? Like it has a short duration? 2 secs or something?

Yes! The main project it was running on was 2 _extremely_ short tests (near-instant no-ops). Updated issue description to reflect that

**Comment by jennifer-shehane** [comment] 2023-12-08 16:06
Ok, I'm going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/27898 and add some more context there. Essentially when the test is so short, it doesn't capture the video properly. This is only happening when you record to the Cloud because we hide the runner ui (`--no-runner-ui`) when recording to the Cloud, so the test is actually running faster when recording to the Cloud than without.

**Closed as completed by jennifer-shehane** 2023-12-08 16:06 UTC
Labels: type: duplicate
