### ISSUE TITLE
Option to override single unique domain per test limitation

### ISSUE THREAD

**Issue by peterklijn** [cypress-io/cypress#1267] opened 2018-02-07 09:34 UTC
### Is this a Feature or Bug?
Feature

### Current behavior:
Tests are limited to a single domain per test

### Desired behavior:
An override in the `visit()` command to allow this for a specific visit.

### Additional Info (images, stack traces, etc)

In the WebSecurity documentation (https://on.cypress.io/web-security#Disabling-Web-Security) there's a mention that the Cypress limitation is artificial and if one wants it overwritten, an issue should be opened. So here we go :).

One of the integration tests that I'm trying to write is testing the reset password flow of our application. We use Auth0 as an authentication provider, which hosts it's own reset page, on its own domain. I would like this functionality to be under integration test as it's an important flow which is should not be broken.

This means that there's a test that starts on `https://login.ourdomain.com/reset`, jumps to `https://our-company.eu.auth0.com/lo/reset?ticket=123456789` and eventually back at `https://login.ourdomain.com/`. 

I understand the limitation in Cypress as it's often a indication of bad tests, and maybe this is an example of it. I would however still like to be able to override it.

**Comment by jennifer-shehane** [comment] 2019-01-25 08:06
Duplicate of https://github.com/cypress-io/cypress/issues/944

**Closed by jennifer-shehane** 2019-01-25 08:06 UTC
