### ISSUE TITLE
Interceptor subject not passed to alias flakiness in Cypress 12

### ISSUE THREAD

**Issue by apexskier** [cypress-io/cypress#25966] opened 2023-02-27 21:31 UTC
### Current behavior

It appears Cypress isn't seeing the interceptor passed from the `cy.intercept` chainable sometimes. I'm getting the error:

> You wrote code that looks like this:
>
> `cy.as("randomizeIP")
>
> A child command must be chained after a parent because it operates on a previous subject.
>
...

But my code is `cy.intercept("...", ...).as("randomizeIP")`.

(In my screenshot I have type as set to "static", but I've seen it with and without that, the docs say it has no effect on interceptors)

<img width="542" alt="e2e - Cypress - 2023-02-27 at 14 07 05@2x" src="https://user-images.githubusercontent.com/329222/221689457-5de327f2-b113-4830-9c9e-2c9d920a843e.png">

### Desired behavior

Interceptor subject should always be passed to `.as` and this should be stable as it was in V10

### Test code to reproduce

```
cy.intercept("/orchestrator/v1/logout").as("postLogout");
```

I've seen reproductions <75% of the time.

### Cypress Version

12.7.0

### Node version

v18.12.1

### Operating System

macOS 12.3.1

**Comment by mjhenkes** [comment] 2023-03-01 22:06
@apexskier, i threw together a repo to reproduce this and ran the intercept command 1000, but was unable to recreate. What am I missing?

https://github.com/mjhenkes/issue-25966-repro

**Comment by mjhenkes** [comment] 2023-03-13 14:55
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open comment on this issue with a reproducible example, and we can look into it further. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as completed by mjhenkes** 2023-03-13 14:55 UTC

**Comment by apexskier** [comment] 2023-03-16 22:31
I don't seem to reproduce this in cypress 12.8 (or at least now)

**Comment by Sanzhanov** [comment] 2023-06-23 01:09
@apexskier did you manage to overcome this issue? I get the same when using multiple cy.intercept()

**Comment by apexskier** [comment] 2023-06-23 17:00
It stopped happening for me without any known cause.

**Comment by craigmiller160** [comment] 2024-01-27 22:33
Having this same issue on 13.6.3. Not sure what the cause could be. I also use a lot of intercept calls with aliases.

**Comment by inder128** [comment] 2024-05-22 08:22
Having the same issue.

**Comment by jennifer-shehane** [comment] 2024-05-22 16:55
@craigmiller160 @inder128 Please create a new issue with a reproducible example

**Comment by craigmiller160** [comment] 2024-06-22 14:22
Hello. I have just experienced this as I am trying to setup a gitlab pipeline. It is definitely a real issue. The best I can do is provide my mochawesome report from my tests.
[cache.zip](https://github.com/user-attachments/files/15937081/cache.zip)
