### ISSUE TITLE
Redirects are not working and throwing error message

### ISSUE THREAD

**Issue by prathadsan** [cypress-io/cypress#2452] opened 2018-09-10 15:51 UTC
### Is this a Feature or Bug?

Its a bug. I am evaluating Cypress for some web applications that we are building. The web application is currently hosted internally and it does have redirects here and there. For every single redirect it takes about 12 - 15 seconds, until the actual page that i expect is loaded and redirected.

### Current behavior:

When finally the page i am expecting is loaded, then it will be a blank screen and if i open the dev tool in chrome, then the following error is displayed in the console:

```
_Uncaught Error: Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!   at silent-renew.html:3_
```

### Desired behavior:

Whats the issue with redirects and why does it take sooo long ? its not the actual tests which is causing it. because, when the browser is opened by cypress, i open a new tab and try and access the website and there its the same issue. it takes more than 10 seconds until redirects are loaded properly.

### Versions

Using latest version of cypress with Chrome 69 on latest MacBook Pro!

**Comment by prathadsan** [comment] 2018-09-10 15:52
@brian-mann I would really appreciate, if you could give me some feedback to this, as this has been blocking me since start of evaluation.

**Comment by prathadsan** [comment] 2018-09-10 15:55
Okay, I see that the error message stated above is appearing, because i opened a new tab. nevertheless, when the page is loaded it takes ages to redirect AND after having loaded fully, i get a blanc page. with nightwatch we are not experiencing this issue for the same web application.

**Comment by jordandlaman** [comment] 2018-09-19 19:46
I can't be sure from the description but one thing cypress doesn't do - it does not handle new tabs.

**Comment by jennifer-shehane** [comment] 2018-11-02 22:43
@prathadsan We'll need a reproducible example of this bug to begin looking into it. There are a lot of variables involved and unless we can run and see the error ourselves, we'll have to close this issue. Sorry.

**Comment by jennifer-shehane** [comment] 2019-01-28 07:38
Closing this issue since no reproducible example was provided. Please comment with an example that we can reproduce locally - test code + app code in order to reopen.

**Closed by jennifer-shehane** 2019-01-28 07:38 UTC
