### ISSUE TITLE
Whoops, there is no test to run after running the 3rd test.

### ISSUE THREAD

**Issue by gretherMG** [cypress-io/cypress#14901] opened 2021-02-03 20:15 UTC
Hi good afternoon, I too something similar happens, I start my test the functions login correctly, then step test select from the menu and the other test filling information of the person I am referring, income type identification and the identity card (number), then I click on the button to consult and there in the 3rd test case is that it sends the message to me, however I'm not going to another url, just what you do when you click on the button is loading a component under the button with information from the person consulted. attached images, thank you in advance for your help.

![error](https://user-images.githubusercontent.com/78503594/106802458-ffbd6e00-6630-11eb-8d11-7e5ce4529f37.jpg)

![error2](https://user-images.githubusercontent.com/78503594/106802460-00560480-6631-11eb-9e0d-5b236c40586a.jpg)

![cyjson](https://user-images.githubusercontent.com/78503594/106802751-617dd800-6631-11eb-9e1d-64e89888c26f.jpg)

```js
  it('P1LB-3-CA2:Escoger Menu Solicitud Reclamos y Requerimientos',function(){
      cy.get(MenuRR.NuevoCaso).click();
      cy.get(MenuRR.Categoria).click();
      cy.screenshot('MenuSolicRR',{capture:'runner',});
    });
//in the 3rd test it is where it falls:
    it('P1LB-1-CA3:Ingresar Cedula y escoger servicio copias mov',function(){
      cy.xpath(InputCedServ.ComboTipoCI).click();
      cy.contains('Cédula').click();
      cy.xpath(InputCedServ.Cedula).type(Datos.Cedula3,{delay:100});
      cy.wait(1000);
      cy.screenshot('logIngresocedula',{capture:'runner',});
      cy.get(InputCedServ.Botonconsultar).click();
     
      cy.wait(12000)
      cy.get(InputCedServ.RadioSiCorreo).click({force:true});
      cy.xpath(InputCedServ.InputCorreoAlt).type(Datos.email,{delay:100});
      cy.screenshot('correoalterno',{capture:'runner',});
```

versión cypress 6.4.0
windows 10
chrome 87

attentive to your prompt response. Greetings

**Comment by jennifer-shehane** [comment] 2021-02-04 04:58
I would suggest checking the other opened issues involving this error: [here](https://github.com/cypress-io/cypress/labels/topic%3A%20%20%F0%9F%98%B3%20whoops%20there%20is%20no%20test%20to%20run). Typically it is because the application under test is setting window.location.top or target=_parent - something changing the main parent window.

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-04 04:58 UTC
Labels: topic:  😳 whoops there is no test to run
