### ISSUE TITLE
blockHosts ignores arrays

### ISSUE THREAD

**Issue by GBirch** [cypress-io/cypress#4470] opened 2019-06-15 20:07 UTC
### Current behavior:

If cypress.json contains
```json
blacklistHosts: [
    "www.google-analytics.com",
    "www.googletagmanager.com"
]
```
Then the resulting configuration, as reported by the GUI, is blacklistHosts: null, and neither domain is blacklisted.

By contrast, if cypress.json contains
```
blacklistHosts: "www.google-analytics.com"
```
Then the resulting configuration, as reported by the GUI, is blacklistHosts: www.google-analytics.com  And the single domain is properly blacklisted.

### Desired behavior:

I would like blacklistHosts to support arrays of domain strings, as the documentation says it should.

### Steps to reproduce: (app code and test code)

See above for steps to reproduce.

### Versions

Cypress: 3.3.1
Chrome: 75
Operating system: Ubuntu 18.04

**Comment by jennifer-shehane** [comment] 2019-06-17 05:07
Hey @GBirch, I'm not able to reproduce what you are describing. 

My `cypress.json` file:

```json
{
  "blacklistHosts": [
    "www.google-analytics.com",
    "www.googletagmanager.com"
  ]
}
```

The resolved configuration within the "Settings" tab on `cypress open`



Where are you accessing the `blacklistsHosts` - where it is showing as `null`? Can you provide the screenshot of your "Settings" tab showing the resolved configuration?

**Comment by GBirch** [comment] 2019-06-17 12:11
Aha!  I poked around a bit, turning things on and off, and discovered that
the bug (if bug it is), is more subtle than reported.

I'm using a custom  plugin to read config from another file, like (but not
identical to) the example here:
https://docs.cypress.io/api/plugins/configuration-api.html#Promises  (I
don't use a Promise, and I add some other config dynamically)

It works great for everything else I've tried (env variables, baseUrl).

But when I read blacklistHosts from the alternate config file, I get null,
per the attached screenshot.

When I turn the plugin off, and add blacklistHosts to the main cypress.json
file, it works fine.

It also works fine with the plugin turned on, as long as blacklistHosts is
in the main configuration file, and is not a value added by the plugin.

So presumably it's an artifact of
"Whenever you return an object from your pluginFile, Cypress will take this
and “diff” it against the original configuration, and automatically set the
resolved values to point to what you returned."

Best, Giles

Giles Birch
Tech-Tamer, LLC
gbirch@tech-tamer.com
617-202-3718

**Comment by jennifer-shehane** [comment] 2019-06-18 04:56
Ok, thanks for clearing this up - there definitely may be an issue with some of this getting sorted out. Will look into recreating today.

**Comment by GBirch** [comment] 2019-06-18 14:04
package.json is in docroot.  cypress.json is present in docroot, and contains an empty object:
```
{
}
```

Contents of ./cypress/plugins/index.js
```
const fileConf = require('./file_config.js')

module.exports = (on, config) => {
  return fileConf.altConfig(config)
}
```
Contents of ./cypress/plugins/file_config.js
```
const fs = require('fs')
const path = require('path')
const n_ = require('lodash')

function altConfig(config) {
  const file = config.env.configFile || 'cypress'
  const pathToConfigFile = path.resolve('cypress', `${file}.json`)
  let rawData = fs.readFileSync(pathToConfigFile);
  let loaded_config = JSON.parse(rawData);
  // Add env variables from the original.
  n_.merge(loaded_config.env, config.env)
  return loaded_config
}

module.exports = {
  altConfig,
}
```

Sample contents of ./cypress/cypress.json
```
{
  "pageLoadTimeout": 10000,
  "blacklistHosts": [
    "www.google-analytics.com",
    "www.googletagmanager.com"
  ]
}
```
On my box, using the GUI to inspect Configuration, this results in pageLoadTimeout: 10000 (and highlighted as coming from plugin) and blacklistHosts: null

**Comment by jennifer-shehane** [comment] 2022-04-08 13:39
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 13:39 UTC
Labels: type: unexpected behavior, stage: ready for work, topic: plugins ⚙️

**Comment by GBirch** [comment] 2022-04-08 15:38
No new information.  I did provide the code as requested, and thought the ball was in your court.  But I haven't returned to this issue in a very long time, obviously, so it may be moot.
