### ISSUE TITLE
Cypress test runner freezes during long running spec ('NOT_LOGGED_IN' error)

### ISSUE THREAD

**Issue by alexcampbell86** [cypress-io/cypress#6312] opened 2020-02-04 06:05 UTC
### Current behavior:

During the running of long running (approx 5 mins) e2e spec, Cypress will freeze at the same step. I cannot interact with the test runner except to forcibly close the window. 

When running Cypress in Debug mode, the following logs are printed at the time the test runner hangs:

```
  cypress:server:events got request for event: get:project:status, { id: '7yap3o', path: '/Users/acampbell/projects/console-connect-e2e' } +10s
  cypress:server:project get project status for client id 7yap3o at path /Users/acampbell/projects/console-connect-e2e +10s
  cypress:server:file get values from /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +10s
  cypress:server:file attempt to get lock on /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:file gettin lock succeeded or failed for /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +4ms
  cypress:server:file read /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:file read succeeded or failed for /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +7ms
  cypress:server:file attempt to unlock /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:file unlock succeeded or failed for /Users/acampbell/Library/Application Support/Cypress/cy/production/cache +1ms


 cypress:server:events send error: Error: You're not logged in. Run `cypress open` to open the Desktop App and log in. at Object.get (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:328:11) at /Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/user.js:63:26 at tryCatcher (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at _drainQueueStep (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)     at processImmediate (internal/timers.js:439:21) { isCypressErr: true, type: 'NOT_LOGGED_IN', details: undefined, isApiError: true } +108ms
  
  cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.009630644786421838, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' + '    at Object.get (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:328:11)\n' + '    at /Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/user.js:63:26\n' + '    at tryCatcher (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n' + '    at Promise._settlePromiseFromHandler (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)\n' + '    at Promise._settlePromise (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)\n' + '    at Promise._settlePromise0 (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)\n' + '    at Promise._settlePromises (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)\n' + '    at _drainQueueStep (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)\n' + '    at _drainQueue (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)\n' + '    at Async._drainQueues (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)\n' + '    at Immediate.Async.drainQueues [as _onImmediate] (/Users/acampbell/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)\n' + '    at processImmediate (internal/timers.js:439:21)\n', message: "You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } } } +1ms
```

### Desired behavior:

Expect test runner to proceed without hanging.

### Test code to reproduce

Please contact me privately about this as I will need to adhere to my company's security guidelines. 

### Versions

**Cypress version**: 3.8.3

**OS**: Have reproduced on Windows 10.0.17763 and Mac 19.2.0 (local development), and Linux Debian - 9.11 (Jenkins CI)

**Browser**:  Electron 78.0.3904.130 & Chrome 79.

**Comment by jennifer-shehane** [comment] 2020-02-04 07:12
@alexcampbell86 We don't recommend having spec files that are this long running. There is a lot of rendering going on with the Cypress UI and a lot in the application as well, so either one of these could be a problem when performing that many quick actions over 5 minutes. For example, the application under test could have a memory leak that would cause the browser to freeze, we wouldn't be able to determine what the issue is without a reproducible example though.

### General Advice:

- Split up your tests into shorter specfiles (less than 1 min each)
- Play with the `numTestsKeptInMemory` value, lowering this may help. https://on.cypress.io/configuration

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-04 07:12 UTC
