### ISSUE TITLE
Can not wait() the registered alias in multiple it() function body 

### ISSUE THREAD

**Issue by Daily-Prophet** [cypress-io/cypress#15391] opened 2021-03-10 09:18 UTC
### Current behavior

I defined an alias in before(), it couldn't find the registered alias for @send in the second it() body.

### Desired behavior

It could always find the registered alias in multiple it() body.

### Test code to reproduce

```typescript
before(() => {
// Spy on the post request
cy.server();
cy.route("POST", /postInfo/).as("send");
cy.visit( "examplePage");
});

describe("wait the same multiple it() body", () => {
  it("the first it()", () => {
    // Can successfully wait in this it() body
    cy.wait("@send").then(xhr => {
      doSomething();
    });
  });

  it("the second it()", () => {
    // Error message: cy.wait() could not find a registered alias for: @send.
    cy.wait("@send").then(xhr => {
      doSomething();
    });
  });
});
```

### Versions

"cypress": "4.4.1",
"@cypress/code-coverage": "^2.0.0",
"@cypress/snapshot": "https://github.com/rkanjani/snapshot.git"

**Comment by woodi3** [comment] 2021-03-10 16:25
Aliases are destroyed after each test, if you have a reoccurring alias, you should put it in the beforeEach hook.

**Comment by Daily-Prophet** [comment] 2021-03-11 05:56
Thanks @woodi3 for the quick response! Some of my issue is discussed more in this issue - [#665](https://github.com/cypress-io/cypress/issues/665) , but this issue discussion thread seems a bit outdated.
So, do you know if there is any work around to use the reoccurring alias without using beforeEach()? Or waht is the best practice about my scenario, any suggestion?

**Comment by woodi3** [comment] 2021-03-11 11:08
@Daily-Prophet I don’t know of any workarounds, I just learned recently that the “Cypress way” was to recreate the aliases in the beforeEach hook if the alias is reused across tests.

**Comment by jennifer-shehane** [comment] 2021-03-16 20:37
https://github.com/cypress-io/cypress/issues/665 is the correct issue for this. You'll need to move the definition into a beforeEach. Aliases are destroyed in between each test. Duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2021-03-16 20:37 UTC

**Comment by Daily-Prophet** [comment] 2021-03-17 02:07
Got it, @woodi3 @jennifer-shehane , I appreciate your help.
