### ISSUE TITLE
cy.intercept() do not intercept one type of URL that has wildcard "*"

### ISSUE THREAD

**Issue by Postavshik** [cypress-io/cypress#23046] opened 2022-08-01 18:31 UTC
### Current behavior

Cypress does not intercept just one specific URL in my application that I try to use with a wildcard. It can intercept a full URL. It can intercept other similar URLs with a wildcard. But just one specific URL with wildcard - don't

### Desired behavior

Cypress should match the wildcard when it used in URL

### Test code to reproduce

**Example.**
Here are the original URLs that I wanted to intercept
1. `/api/Provider/VerifyProvider?providerId=31726&includeRecruiterDetails=true`
2. `/api/providers?IncludeLicensedStatesModes=0&PageSize=100&PageNumber=1&includeRecruiterDetails=true&OrderDirection=0&OrderBy=0`
3. `/api/Capacity?providerId=31726&startDate=07/01/2022&endDate=01/28/2023`

All these URLs wanted to intercept using a global matching pattern with wildcard, so
1. `cy.intercept('/api/Provider/VerifyProvider?providerId=*')`
2. `cy.intercept('/api/providers?IncludeLicensedStatesModes=*')`
3. `cy.intercept('/api/Capacity?providerId=*')`

**The Problem:**
Intercepts 1 and 2 - worked just fine. Intercept 3 - does not work. If I provide full URL in example 3 - it works. So for some reason, for URL 3, cypress does not like the wildcard and do not recognize pattern to match URL.

### Cypress Version

10.3.1

**Comment by rockindahizzy** [comment] 2022-08-04 16:16
Hey @Postavshik,

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-11 18:12
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-11 18:12 UTC
Labels: stage: awaiting response
