### ISSUE TITLE
CYPRESS_INSTALL_BINARY on Windows Concats to Download URL

### ISSUE THREAD

**Issue by fhilton** [cypress-io/cypress#4296] opened 2019-05-23 19:32 UTC
#### On windows 10, setting `CYPRESS_INSTALL_BINARY` with the following:

```
setx CYPRESS_INSTALL_BINARY C:/cypressBinary.3.3.1/cypress.zip /M
```

#### Then run npm install

```
npm install cypress@3.3.1
```

#### Produces this in the install log:

> 
> ‼ Warning: Forcing a binary version different than the default.
> 
>   The CLI expected to install version: 3.3.1
> 
>   Instead we will install version: C:/cypressBinary.3.3.1/cypress.zip
> 
>   These versions may not work properly together.
> 
> Installing Cypress (version: C:/cypressBinary.3.3.1/cypress.zip)
> 
>  ×  Downloading Cypress
>    → Cypress Version: 3.3.1
>     Unzipping Cypress
>     Finishing Installation
> The Cypress App could not be downloaded.
> 
> Please check network connectivity and try again:
> 
> ----------
> 
> URL: https://download.cypress.io/desktop/C:/cypressBinary.3.3.1/cypress.zip?platform=win32&arch=x64
> Error: Failed downloading the Cypress binary.
> Response code: 404
> Response message: Not Found

Notice how the URL contains the path to the zip file.

Some more details here: https://github.com/cypress-io/cypress-documentation/issues/761#issuecomment-428059070

and a proposed solution here: https://github.com/cypress-io/cypress-documentation/issues/761#issuecomment-446140101

### Desired behavior:

Setting `CYPRESS_INSTALL_BINARY` on windows should install using the file located in the env variable.

### Steps to reproduce: (app code and test code)

- Download the cypress zip file to  `C:/cypressBinary.3.3.1/cypress.zip`
- Run `setx CYPRESS_INSTALL_BINARY C:/cypressBinary.3.3.1/cypress.zip /M`
- Reload command window to refresh `env` variable
- Run `npm install cypress@3.3.1`

**Comment by jasmine-zhang-nz** [comment] 2019-05-24 03:27
I have a similar issue, after set up the http_proxy and https_proxy, I still not able to install Cypress 3.3.1
The error message is: The Cypress App could not be downloaded. Please check network connectivity and try again.

I have already setup the proxy, so if 3.3.1 has resolved the issue, this should not happen again.

**Comment by jennifer-shehane** [comment] 2019-05-24 05:04
@jasmine-zhang-nz Are you also setting the `CYPRESS_INSTALL_BINARY`? If not, I believe you are having a separate issue and should open a new issue.

**Comment by tomasbjerre** [comment] 2019-08-29 19:14
Could it be that the file does not exist? That should be made clerar with the fix in #5060

**Comment by ari-meetai** [comment] 2019-11-08 19:04
Used "\" instead of "/" and it worked.

i.e.: "c:\cypressBinary\cypress.zip"

**Comment by kaiyoma** [comment] 2020-04-10 00:36
I've run into this problem as well. If I set `CYPRESS_INSTALL_BINARY` in the Cygwin/Unix style (e.g. `/c/Users/Kyle Getz/AppData/Local/Cypress/Cache`) I see this in the output of `yarn install`:

```
Exit code: 1
Command: node index.js --exec install
Arguments:
Output:
‼ Warning: Forcing a binary version different than the default.
  The CLI expected to install version: 4.1.0
  Instead we will install version: /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip
  These versions may not work properly together.
Installing Cypress (version: /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip)
[16:48:05]  Downloading Cypress     [started]
[16:48:07]  Downloading Cypress     [failed]
[16:48:07] → The Cypress App could not be downloaded.
Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environm
ent variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
Otherwise, please check network connectivity and try again:
----------
URL: https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip?pl
atform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
```

You can see that the URL is very badly malformed:

```
https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip?platform=win32&arch=x64
```

**Comment by jennifer-shehane** [comment] 2020-04-14 09:23
Could you run `cypress install` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

There should be a debug log that will print the `CYPRESS_INSTALL_BINARY` we are reading in, perhaps this will highlight some problem.

**Comment by kaiyoma** [comment] 2020-04-17 01:27
```
$ CYPRESS_INSTALL_BINARY=~/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip DEBUG=cypress:* yarn cypress install
yarn run v1.22.4
$ "C:\Users\Kyle Getz\Work\event-viewer\node_modules\.bin\cypress" install
  cypress:cli:cli cli starts with arguments ["C:\\Program Files\\Node.js\\node.exe","C:\\Users\\Kyle Getz\\Work\\event-viewer\\node_modules\\cypress\\bin\\cypress","install"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +4ms
  cypress:cli parsed cli options {} +495ms
  cypress:cli installing with options {} +0ms
  cypress:cli version in package.json is 4.1.0 +1ms
  cypress:cli Using CYPRESS_INSTALL_BINARY from environment variable +5ms
  cypress:cli Using CYPRESS_INSTALL_BINARY from environment variable +1ms
  cypress:cli using environment variable CYPRESS_INSTALL_BINARY "/c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip" +1ms
  cypress:cli Reading binary package.json from: C:\Users\Kyle Getz\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\package.json +0ms
  cypress:cli no binary installed under cli version +14ms
‼ Warning: Forcing a binary version different than the default.

  The CLI expected to install version: 4.1.0

  Instead we will install version: /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip

  These versions may not work properly together.

  cypress:cli checking local file /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip cwd C:\Users\Kyle Getz\Work\event-viewer +4ms
  cypress:cli preparing to download and unzip version  /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip to path C:\Users\Kyle Getz\AppData\Local\Cypress\Cache\4.1.
0 +26ms
Installing Cypress (version: /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip)

  cypress:cli needed Cypress version: /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip +0ms
  cypress:cli source url https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip?platform=win32&arch=x64 +1ms
  cypress:cli downloading cypress.zip to "C:\Users\KYLEGE~1\AppData\Local\Temp\cypress.zip" +4ms
  cypress:cli Downloading package {
  url: 'https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip?platform=win32&arch=x64',
  proxy: null,
  downloadDestination: 'C:\\Users\\KYLEGE~1\\AppData\\Local\\Temp\\cypress.zip'
} +24ms
  /  Downloading Cypress
     Unzipping Cypress
     Finishing Installation
  cypress:cli response code 404 +351ms
  cypress:cli URL: https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip?platform=win32&arch=x64
  ×  Downloading Cypress
    → Cypress Version: 4.1.0
     Unzipping Cypress
     Finishing Installation
  cypress:cli downloading finished +8ms
  cypress:cli downloaded file lacks checksum or size to verify +0ms
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypres
s.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip?platform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: win32 (10.0.18363)
Cypress Version: 4.1.0
```

**Comment by kaiyoma** [comment] 2020-04-17 16:20
Just ran into a related issue. I have version 4.1.0 specified in my package.json, but when I `yarn install`, Cypress downloads the wrong version, then complains that the checksum doesn't match:

```
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/11] ⠄ waiting...
[-/11] ⡀ waiting...
[-/11] ⡀ waiting...
[4/11] ⡀ cypress
error C:\Users\Kyle Getz\Work\event-viewer\node_modules\@types\testing-library__cypress\node_modules\cypress: Command fa
iled.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: C:\Users\Kyle Getz\Work\event-viewer\node_modules\@types\testing-library__cypress\node_modules\cypress
Output:
Installing Cypress (version: 4.2.0)

[09:10:44]  Downloading Cypress     [started]
[09:10:45]  Downloading Cypress      0% 0s [title changed]
[09:10:46]  Downloading Cypress      1% 80s [title changed]
[09:10:46]  Downloading Cypress      1% 90s [title changed]
[09:10:46]  Downloading Cypress      1% 100s [title changed]
...
[09:13:36]  Downloading Cypress      98% 4s [title changed]
[09:13:37]  Downloading Cypress      99% 2s [title changed]
[09:13:38]  Downloading Cypress      100% 0s [title changed]
[09:13:41]  Downloading Cypress      100% 0s [failed]
[09:13:41] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environm
ent variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.2.0?platform=win32&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 45e16e4dd692ff89ddd8155bd80caaddbf11ba6ee12e57a3fbcbe12e5245418196840a324b9e0
22699b295f6364c0500c7df41baf0611f89f3316066b1c39c7e
Computed checksum: f17e5e344fbd17de1b7b9ec2d8756161f6f55ab36300e75b1b53107af8183fe1c77b7e95448590c26cdb48209663d07cb251e
3774e2d51381960043c41b6ad38

Expected downloaded file to have size: 168629214
Computed size: 168629214

----------

Platform: win32 (10.0.18363)
Cypress Version: 4.2.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environm
ent variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.2.0?platform=win32&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 45e16e4dd692ff89ddd8155bd80caaddbf11ba6ee12e57a3fbcbe12e5245418196840a324b9e0
22699b295f6364c0500c7df41baf0611f89f3316066b1c39c7e
Computed checksum: f17e5e344fbd17de1b7b9ec2d8756161f6f55ab36300e75b1b53107af8183fe1c77b7e95448590c26cdb48209663d07cb251e
3774e2d51381960043c41b6ad38

Expected downloaded file to have size: 168629214
Computed size: 168629214

----------
```

No one told it to download version 4.2.0. Why is it doing that?

**Comment by jennifer-shehane** [comment] 2020-08-28 09:03
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by kaiyoma** [comment] 2020-08-28 15:23
This is still an issue.

**Comment by jennifer-shehane** [comment] 2020-10-19 10:31
@kaiyoma Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by kaiyoma** [comment] 2020-10-19 15:03
I believe I already did this here: https://github.com/cypress-io/cypress/issues/4296#issuecomment-614984451

**Comment by jennifer-shehane** [comment] 2021-01-22 07:16
@kaiyoma The checksum issue is a duplicate of #4595

**Closed by jennifer-shehane** 2021-01-22 07:16 UTC
Labels: OS: windows, topic: installation

**Comment by kaiyoma** [comment] 2021-01-22 16:53
@jennifer-shehane I don't think this is the same issue. It's not an issue of the checksum being wrong. The actual URL is being constructed incorrectly and the download fails entirely. I still run into this issue, so please leave this open.

**Comment by kaiyoma** [comment] 2021-01-28 19:11
@jennifer-shehane Can you please reopen this issue? Otherwise I'm just going to have to file a new one with all the same info again, because I still run into this issue regularly. Note the URL below:

```
----------

Platform: win32 (10.0.19042)
Cypress Version: 6.2.1
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environm
ent variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop//c/Users/Kyle%20Getz/AppData/Local/Cypress/Cache/cypress-6.2.1-win32-x64.zip?pl
atform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------
```

**Comment by bahmutov** [comment] 2021-01-28 19:53
@kaiyoma The suspicious log line in your DEBUG logs is this one
```
cypress:cli checking local file /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip cwd C:\Users\Kyle Getz\Work\event-viewer
```

For some reason, it see a mixture of unix-like paths and window current working directory. Because you said it was Cygwin - what happens when you pass the traditional Windows path to the binary? Because that would break the `path.relative` check under Nodejs.

**Comment by kaiyoma** [comment] 2021-01-28 22:00
> @kaiyoma The suspicious log line in your DEBUG logs is this one
> 
> ```
> cypress:cli checking local file /c/Users/Kyle Getz/AppData/Local/Cypress/Cache/cypress-4.1.0-win32-x64.zip cwd C:\Users\Kyle Getz\Work\event-viewer
> ```
> 
> For some reason, it see a mixture of unix-like paths and window current working directory. Because you said it was Cygwin - what happens when you pass the traditional Windows path to the binary? Because that would break the `path.relative` check under Nodejs.

I can try this out, but I will note that Cypress's own docs use the forward-slash, Unix style for directories, even for Windows:

https://docs.cypress.io/guides/getting-started/installing-cypress.html

**Comment by kaiyoma** [comment] 2021-01-28 22:31
> I can try this out, but I will note that Cypress's own docs use the forward-slash, Unix style for directories, even for Windows:
> 
> https://docs.cypress.io/guides/getting-started/installing-cypress.html

I believe using Windows-style paths does actually work here, thanks for the suggestion! I guess that means the docs are wrong?

(I also didn't realize that `CYPRESS_INSTALL_BINARY` can take a URL, which actually works better for me anyway, so I'll be switching to that notation.)

**Comment by bahmutov** [comment] 2021-01-28 23:31
In our examples we see Unix-style path, do you find it somewhere else?

<img width="833" alt="Screen Shot 2021-01-28 at 6 31 09 PM" src="https://user-images.githubusercontent.com/2212006/106211636-18440900-6197-11eb-82a7-9ad078053df7.png">

**Comment by kaiyoma** [comment] 2021-01-29 00:09
I see Unix-style for Windows here:

![image](https://user-images.githubusercontent.com/10719780/106214148-0eb0a600-6183-11eb-9fba-6aadc883f074.png)

And also here:

![image](https://user-images.githubusercontent.com/10719780/106214186-1ff9b280-6183-11eb-93c0-370f07586aef.png)

Also, that path in the first screenshot is wrong. It's missing a `~` in front.

**Comment by geyuqiu** [comment] 2022-09-14 09:15
Same issue here, looks like a backslash problem in windows, use \ instead of /. Windows sucks really at web development

**Comment by DustinOgan** [comment] 2023-06-06 22:08
Know this is an older issue, but as I was helping a friend troubleshoot something this is still with the advanced install options.
Steps to reproduce:
1. Windows Desktop cmd.exe prompt
2. Create a new folder using 'mkdir CypressProject'
3. cd CypressProject
4. use 'npm init' 
5. use the above examples to 'set CYPRESS_INSTALL_BINARY=~/Downloads/cypress.zip'
6. run 'npm install cypress

`npm install cypress
npm ERR! code 1
npm ERR! path S:\CypressProject\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! ‼ Warning: Forcing a binary version different than the default.
npm ERR!
npm ERR!   The CLI expected to install version: 12.13.0
npm ERR!
npm ERR!   Instead we will install version: ~/Downloads/cypress.zip
npm ERR!
npm ERR!   These versions may not work properly together.
npm ERR!
npm ERR! Installing Cypress (version: ~/Downloads/cypress.zip)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be downloaded.
npm ERR!
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR!
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! URL: https://download.cypress.io/desktop/~/Downloads/cypress.zip?platform=win32&arch=x64
npm ERR! Error: Failed downloading the Cypress binary.
npm ERR! Response code: 404
npm ERR! Response message: Not Found`

Note the install fails (bigger problem despite the file being at this location), and instead of replacing the location it inserts it onto the end of the original url between "desktop" and the query parameters.   Will open a new issue but putting this here as breadcrumb for those with similar issue.
