### ISSUE TITLE
Cypress GUI stays on infinite loading

### ISSUE THREAD

**Issue by aryanmajeed** [cypress-io/cypress#19409] opened 2021-12-17 13:21 UTC
### Current behavior

After running `cypress open` on vscode terminal, the cypress GUI stays on infinite loading, and I get these logs:

```
[5407:1217/043419.721073:WARNING:vaapi_wrapper.cc(586)] VAAPI video acceleration not available for swiftshader
[5407:1217/043419.721278:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

### Desired behavior

It should open cypress GUI.

### Test code to reproduce

Here are the specs where I run cypress:
Node: v17.1.0
Yarn: 1.22.17
![Screenshot_20211217_161204](https://user-images.githubusercontent.com/58115075/146550768-baf6fff2-d653-4799-9071-45719420a3ef.png)

### Cypress Version

9.1.1

**Comment by atasak** [comment] 2021-12-17 13:49
I have this problem as well. However, I run the command `npx cypress open` from a normal terminal emulator. Using Manjaro linux and i3. I included a copy of npx cypress info below. 

```
$ npx cypress info
Displaying Cypress info...

Detected 2 browsers installed:

1. Chromium
  - Name: chromium
  - Channel: stable
  - Version: 96.0.4664.93
  - Executable: chromium

2. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 95.0
  - Executable: firefox

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox
- cypress run --browser chromium

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /home/<user>/.config/cypress/cy/development
Browser Profiles: /home/<user>/.config/cypress/cy/development/browsers
Binary Caches: /home/<user>/.cache/Cypress

Cypress Version: 9.1.1
System Platform: linux (Manjaro Linux - 21.2rc)
System Memory: 16.6 GB free 1.67 GB
```

**Comment by atasak** [comment] 2021-12-17 14:37
Some more info:

I followed [this](https://docs.cypress.io/guides/references/troubleshooting#Edit-the-installed-Cypress-code) guide to obtain some more information. I found the following:

  - `npx cypress run` hangs as well
  - A file is attatched containing the output of `DEBUG=cypress:* npx cypress open` here: [cypress_debug_log.txt](https://github.com/cypress-io/cypress/files/7735776/cypress_debug_log.txt)
  - Running the binary directly using `ELECTRON_ENABLE_LOGGING=true`, using `ldd`, or using the `--smoke-test` flag did not generated any interesting output
  - Running /home/<user>/.cache/Cypress/9.1.1/Cypress/Cypress directly works fine, including opening the project, executing the tests, ...

**Comment by emilyrohrbough** [comment] 2021-12-17 15:22
This appears to be a duplicate of https://github.com/cypress-io/cypress/issues/19320. I'm going to close this in favor of the existing issue. I appreciate you taking the time to open and issue & provide useful information. Please add your find there!

**Closed by emilyrohrbough** 2021-12-17 15:22 UTC
