### ISSUE TITLE
Cypress test runner running tests in Infinite Loop

### ISSUE THREAD

**Issue by shivkaps** [cypress-io/cypress#7470] opened 2020-05-24 20:28 UTC
Cypress runs the tests in infinite loop in test runner if a different url is used in one of the tests. However, when we run the same test via CLI then it runs just once. 

### Desired behavior:

The test should run just once.

### Test code to reproduce

1. Clone this repo [https://github.com/shivkaps/cypress-mastery/tree/cypress-issue](url)
2. Open this project in Visual Studio.
3. Run the command `npx cypress open`
4. Click on "Run All Specs"
5. The test will run in infinite loop in the test runner

### Root Cause

A different url for testing in this file. "http://example.com" as compared to other tests which are running test against a different url "http://zero.webappsecurity.com".
https://github.com/shivkaps/cypress-mastery/blob/cypress-issue/cypress/integration/visual-tests/full-page.spec.js

It seems it just restarts

### Versions

Cypress 4.6.0, 4.5.0, 
Operating system - MacOs 
Browser - Chrome

**Comment by jennifer-shehane** [comment] 2020-05-26 08:36
I'm able to recreate this with the code below. 

This is a duplicate of #1987. You can workaround this issue by moving the visits outside of the `before` hooks for now, but this will be fixed in #7154. 

`spec.js`

```js
before(() => {
  cy.visit('http://zero.webappsecurity.com/index.html')
})

it('test 1', () => {
})

it('test 2', () => {
  cy.visit('http://example.com/')
})
```

As a side note, you may want to consider excluding `node_modules` using `.gitignore` for your projects because the size of your repo is enormous to download with all the included `node_modules`.

**Closed by jennifer-shehane** 2020-05-26 08:36 UTC
