### ISSUE TITLE
RangeError with isBinary call for socket.io-parser

### ISSUE THREAD

**Issue by impleri** [cypress-io/cypress#16801] opened 2021-06-03 14:48 UTC
### Current behavior
Working on upgrading my app from using Cypress 5.x to 7.4. It's working fine running locally on Chromium, but it's getting the following error at the end of the first test run:

```
RangeError: Maximum call stack size exceeded
    at isBinary (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:23:18)
    at hasBinary (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:46:9)
    at hasBinary (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
```

It's running on CircleCI using the `cypress/browsers:node14.16.0-chrome90-ff88` Docker image and uses Chrome instead of Chromium.

### Desired behavior

Test run should continue on to the next test.

I suspect the error relates to continued API calls being caught by `cy.intercept` and the app under test not being in a "done" state despite reaching the end of the assertions in the test.

### Versions

Was working on Cypress 5.6 with Chrome and Chromium on both Mac and Linux. Works on 7.4 on Mac with Chromium. Failing on 7.4 with Chrome browser on Mac and Linux.

**Comment by onimougwo** [comment] 2021-06-03 19:07
I got a similar issue but on 7.3.0 in my CI environment (ADO). I ran the build again and the second time it was fine. Not sure what's triggering this.

**RangeError: Maximum call stack size exceeded
    at isBinary (C:\Users\tfsbuild\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:23:18)**

**Comment by carlpeaslee** [comment] 2021-06-03 21:24
I am experiencing this as well

**Comment by jennifer-shehane** [comment] 2021-06-04 13:23
Duplicate of https://github.com/cypress-io/cypress/issues/16476

This has been fixed and is scheduled to be released on Monday. 

You may have to downgrade to 6.4.0 to avoid the Maximum call stack errors altogether.

**Closed by jennifer-shehane** 2021-06-04 13:23 UTC
