### ISSUE TITLE
Cypress can not type (cy.get(el).type) space char (' ') into input[type=email] !

### ISSUE THREAD

**Issue by MohammadS3dd** [cypress-io/cypress#29472] opened 2024-05-06 11:45 UTC
### Current behavior

Cypress does not type space char into any email input. 

### Desired behavior

in case this is desired behavior: 
Cypress should be able to type any character into any field. if users can do it with their physical keyboard, Cypress should too. 

### Test code to reproduce

reproduction: https://github.com/MohammadS3dd/cypress-bug-reproduction

### Cypress Version

13.7.0

### Node version

v18.17.1

### Operating System

windows 11

**Comment by jennifer-shehane** [comment] 2024-05-06 14:42
Duplicate of https://github.com/cypress-io/cypress/issues/1327

**Closed as not planned by jennifer-shehane** 2024-05-06 14:42 UTC
Labels: type: duplicate
