### ISSUE TITLE
Add option to allow LocalStorage entries to persist between tests

### ISSUE THREAD

**Issue by carlos-granados** [cypress-io/cypress#461] opened 2017-03-15 18:47 UTC
Similar to the mechanism available to whitelist cookies so that these entries will not be cleared between test

**Comment by tjhillard** [comment] 2017-04-26 18:11
👍 Would a be nice feature!

**Comment by ashercoren** [comment] 2017-05-12 06:55
Yes, please!

**Comment by ZwaarContrast** [comment] 2017-08-21 14:54
Yes, that would really help us with our application which uses cognito by AWS as a authentication provider (which under the hood uses localstorage)

**Comment by brian-mann** [comment] 2017-08-28 16:23
You can achieve this manually right now because the method that clear local storage are publicly exposed as `Cypress.LocalStorage.clear`.

You can backup this method and override it based on the keys sent in.

```js
const clear = Cypress.LocalStorage.clear

Cypress.Location.clear = (keys, ls, rs) => {
  // do something with the keys here
  if (keys) {
    return clear.apply(this, arguments)
  }

}

**Comment by jurom** [comment] 2017-09-20 12:39
@brian-mann We had similar problem and this worked, thanks ! However, I assume that there's a typo and it should've been
```
Cypress.LocalStorage.clear = function (....
```

**Comment by jennifer-shehane** [comment] 2017-12-04 16:42
@jurom Thanks, this has been fixed in brian's example.

**Comment by lacroixdavid1** [comment] 2018-01-11 15:56
I've tried your example @brian-mann but i get empty keys array on every call. Any ideas why ?

**Comment by brian-mann** [comment] 2018-01-11 15:57
@lacroixdavid1 then it sounds like you don't have anything in localStorage. Are you sure you're not storing it in SessionStorage? You don't have to guess - just use Dev Tools Application Tab and it'll show you everything that's being stored.

**Comment by lacroixdavid1** [comment] 2018-01-11 16:02
@brian-mann it is really stored in localstorage with key `jStorage`

**Comment by lacroixdavid1** [comment] 2018-01-11 16:03
```typescript
const clear = Cypress.LocalStorage.clear;
Cypress.LocalStorage.clear = function (keys, ls, rs) {
  // do something with the keys here
  if (keys) {
    debugger;
    // return clear.apply(this, arguments)
  }
}
```

This doesnt clear my localStorage, but i need to filter keys

**Comment by lacroixdavid1** [comment] 2018-01-11 16:23
In `/packages/driver/src/cypress/local_storage.coffee` in method `clear: (keys, local, remote)` : 

```javascript
      .each (item) =>
        if keys.length
          @_ifItemMatchesAnyKey item, keys, (key) =>
            @_removeItem(storage, key)
        else
          @_removeItem(storage, item)
```

My localStorage gets fully cleared as `key.length` is 0 on every call.
So, as I can see, because no keys are sent to the methods, it clears whole storage.

Also, in `packages/driver/src/cy/commands/local_storage.coffee` in method `clearLocalStorage = (state, keys)`, `keys` is always empty, but `local` and `remote` have values.

Why this ? because of the following : 

```typescript
  Cypress.prependListener "test:before:run", ->
    try
      ## this may fail if the current
      ## window is bound to another origin
      clearLocalStorage(state, [])
    catch
      null
```

you can clearly see that method `clearLocalStorage` called before each test doesn't get passed any keys.

**Comment by lacroixdavid1** [comment] 2018-01-15 20:34
@brian-mann any suggestions ?

**Comment by lacroixdavid1** [comment] 2018-01-26 20:00
Those wrong answers and that dead silence leave me disappointed about cypress.io.

**Comment by bahmutov** [comment] 2018-01-26 20:30
Sorry to hear @lacroixdavid1 - but notice that this goes against our philosophy of making each test independent from others. Suggestion - maybe in `afterEach` grab all values from `localStorage` and then inside into `localStorage` in `beforeEach` callback? Remember, this is JUST JavaScript, so you can copy / clone / modify everything, just like you can from DevTools console.

**Comment by lacroixdavid1** [comment] 2018-01-26 20:33
@bahmutov I know it can be done this way, but I feel like `Cypress.LocalStorage.clear` should get localstorage keys like suggested in previous answers. Did code change since the first answer?

**Comment by michalcafe** [comment] 2018-05-25 14:12
I hope that in the future cypress will allow us to define the behaviour.

My current workaround is creating two helper commands which save and restore the local storage between tests.

```
```

**Comment by Aaronius** [comment] 2018-09-06 19:52
Regarding [@unrealprogrammer's approach](https://github.com/cypress-io/cypress/issues/461#issuecomment-392070888), I have something like this:

```
describe()
  it()
  it()

describe()
 before()
   it()
```

Inside the `before()`, I'm calling `cy.visit()`. The problem is that the call to `cy.visit()` comes after the global `afterEach()` that stores off the local storage item, but before the global `beforeEach()` that restores the local storage item. Therefore, when Cypress tries to visit the URL, our app says it can't find the thing that's supposed to be in local storage and fails (in our case, we're storing an auth token).

The only solution I have for now is that I move the `cy.visit()` call into a `beforeEach()` or into each `it()`, both of which require that the browser do more work than is necessary. I would love to hear if there's a better way of handling this. I've tried @brian-mann's approach, but can't get it to work for the same reasons @lacroixdavid1 has stated.

**Comment by lacroixdavid1** [comment] 2018-09-06 20:27
@Aaronius the best recommendation I can give you is to get rid of Cypress and switch to Protractor. There are multiple reasons.

**Comment by carlos-granados** [comment] 2018-09-06 20:31
@lacroixdavid1 I had the opposite experience. Protractor was a nightmare and switching to Cypress solved all our problems with random failures and tests which were impossible to debug

**Comment by EvHaus** [comment] 2019-01-09 20:00
I would honestly just offer an option to "Don't reset localStorage between test" as well. I would say, in the majority of cases (for us) we want to preserve it, and clearing it manually is literally a one liner we can add in `after()` where appropriate.

**Comment by AbdealiJK** [comment] 2019-04-30 14:54
For the earlier issues on the `keys` always being empty `[]`.
As per the code i debugged today, it looks like the `[]` means - delete all keys.

Reference: https://github.com/cypress-io/cypress/blob/00920b1f9f93d0830003ac9198c3ad14e558489e/packages/driver/src/cypress/local_storage.coffee#L33

So, the code which should work for whitelist would be as:
```
const clear = Cypress.LocalStorage.clear

Cypress.LocalStorage.clear = function (keys, ls, rs) {
  if (keys && keys.length == 0) {
    keys = Object.keys(localStorage);
  }
  whitelistKeys = [];
  keys = keys.filter(function(i) {return whitelistKeys.indexOf(i) < 0;});
  return clear.apply(this, arguments)
}
```

**Comment by jennifer-shehane** [comment] 2019-07-01 03:53
It's on our roadmap to make handling localStorage and other things that are automatically cleared between tests more customizable, including turning off clearing altogether. You can follow that larger issue here: https://github.com/cypress-io/cypress/issues/686

**Comment by pavelsmajda** [comment] 2019-08-09 14:34
Hi everyone, 
our new web application is using Silent sign in method (oidc authentication) and after all tutorials, and hints I'm still unable to keep localStorage and Cookies saved for whole bunch of tests. My goal is to keep user logged in all the time during the tests but I always finish on "/not-authorized" page and with completely cleared session. I'm out of ideas.
Test structure looks like this:

`describe('testA', () => {
    it('request url if available' () {
        cy.a
        })
    })
})

describe('login, function() {
    before(function () {
        cy.login()
    })
        
    it('go to page A and test something() {
        cy.a
        })
    })

    it('go to page B and test something () {
        cy.a
        })
    })
    
describe('logout', () => {
    it('Logout', function () {
        cy.a
    })
})`

Can you help me with this issue please? Thanks a lot! :-)

**Comment by danatemple** [comment] 2019-08-10 09:08
I have a similar model to you, with each spec having a describe() containing a sequence of tests, with a single login at the start. Each test is in an it(), and we want to preserve both DOM and localStorage between the it()s as we use JWT login.

The solution that works robustly for us is to initially prevent any localStorage clearing happening:
```
Cypress.LocalStorage.clear = function (keys, ls, rs) {
    return;
}

```
We did try to implement the "whitelist" solution above by replacing this with a function to process the list of keys, but this did not work reliably.

Then, at the start of each describe() i.e. before the login:
`localStorage.clear();
`

Control of cookie clearing **is** supported by Cypress: https://docs.cypress.io/api/cypress-api/cookies.html

**Comment by pavelsmajda** [comment] 2019-08-19 07:04
@danatemple thanks for help, but your solution works for me only partially. I still receive "not-authorized" page after some time tests are running. Thank you anyway. 

I'm also trying workaround from @pietmichal but I got the same result. 

Silent sign on is called in Cypress very often and requests are often returned without token. I'm in dead end and it seems I need to wait to this issue fix. In Selenium is this working without any problem. "authority" is called once and returned with token which keep user signed into application.

**Comment by Tenmak** [comment] 2020-02-20 14:48
> You can achieve this manually right now because the method thats clear local storage is publicly exposed as `Cypress.LocalStorage.clear`.
> 
> You can backup this method and override it based on the keys sent in.
> 
> ```js
> const clear = Cypress.LocalStorage.clear
> 
> Cypress.LocalStorage.clear = function (keys, ls, rs) {
>   // do something with the keys here
>   if (keys) {
>     return clear.apply(this, arguments)
>   }
> }
> ```

I've been inspiring myself from this example to create my own in TypeScript. I'm setting the list of keys to ignore in my Local Storage but still manually clear it once at when Cypress start to ensure at least one authentication case.

Works great for my needs.

```
import { isArray } from 'util';

// Manually clear the localStorage before each session to ensure authentication at least once
window.localStorage.clear();

Cypress.LocalStorage.clear = (keys?: string[]) => {
  const KEYS_IGNORED = [
    ...
  ];

  // Specific clear
  if (keys !== undefined && isArray(keys) && keys.length > 0) {
    keys.forEach(key => window.localStorage.removeItem(key));
  } else {
    // Full clear
    if (window.localStorage.length > 0) {
      Object.keys(window.localStorage)
        .filter(key => !KEYS_IGNORED.includes(key))
        .forEach(key => window.localStorage.removeItem(key));
    }
  }
};
```

I've set this code in a custom .ts file that I import un the support folder of Cypress.

**Comment by kriegster108** [comment] 2020-03-06 17:36
This needs to get implemented soon as possible. super frustrating issue

**Comment by MikhailForte** [comment] 2020-03-20 19:15
also faced with this problem

**Comment by Cubo25** [comment] 2020-04-09 09:44
Same problem for my 😞  strange think is that it was working like charm for 3 weeks but somehow this issue popped up like 3 days ago for me ...

**Comment by evba1** [comment] 2020-05-07 16:49
> For the earlier issues on the `keys` always being empty `[]`.
> As per the code i debugged today, it looks like the `[]` means - delete all keys.
> 
> Reference:
> 
> https://github.com/cypress-io/cypress/blob/00920b1f9f93d0830003ac9198c3ad14e558489e/packages/driver/src/cypress/local_storage.coffee#L33
> 
> So, the code which should work for whitelist would be as:
> 
> ```js
> const clear = Cypress.LocalStorage.clear
> 
> Cypress.LocalStorage.clear = function (keys, ls, rs) {
>   if (keys && keys.length == 0) {
>     keys = Object.keys(localStorage);
>   }
>   whitelistKeys = [];
>   keys = keys.filter(function(i) {return whitelistKeys.indexOf(i) < 0;});
>   return clear.apply(this, arguments)
> }
> ```

This isn't working as expected! In fact it doesn't remove any local storage item at all.
I did a test like this. Set new item in local storage with name 'test'. Then in the whitelistKeys add 'test2'. It will not remove the 'test' item and any other item that exists in local storage.

**Comment by jennifer-shehane** [comment] 2020-08-18 09:46
Hey everyone, we've outlined some work to be done to address some of the concerns of 'local storage' in this issue: https://github.com/cypress-io/cypress/issues/8301

It outlines a proposal for a 'session' API, to quickly summarize:

>With cy.session, you'll be able to perform UI interactions before taking a "snapshot" of all the session related data and "restore" it before each test.

This session related data would include localStorage.

I recommend reading the entire proposal in https://github.com/cypress-io/cypress/issues/8301 and following there for any updates. Please feel free to express any concerns or questions in that issue concerning the API and add a 👍 for general support.

**Comment by whenmoon** [comment] 2020-09-16 14:52
I cannot believe there isn't a proper solution for this yet. There I was trying out Cypress and thinking how easy it was to use and then realising I couldn't actually use it because it logs me out of the app I'm trying to tests every time. maybe they think authentication isn't a thing.

**Comment by grinsteindavid** [comment] 2021-04-06 05:01
this should be an option in the cypress.json :/

**Comment by javierbrea** [comment] 2021-05-24 06:02
Until this is natively supported, the [`cypress-localstorage-commands` plugin](https://github.com/javierbrea/cypress-localstorage-commands) allows persisting localStorage between tests.

**Comment by davifsroberto** [comment] 2021-07-09 12:18
`Cypress.LocalStorage.clear = () => {};`

Works for me 😉
I using cypress 7 version.

**Comment by TheDutchCoder** [comment] 2021-07-30 17:03
> Until this is natively supported, the [`cypress-localstorage-commands` plugin](https://github.com/javierbrea/cypress-localstorage-commands) allows persisting localStorage between tests.

What a beautiful little plugin! Thanks!

I ran into this problem today and was desperate for a solution. I don't understand the reasoning for why Cypress wipes localStorage between tests, it only makes sense to do that on a per-spec basis. It doesn't align at all with e2e testing either.

**Comment by adi518** [comment] 2021-10-03 13:05
> > For the earlier issues on the `keys` always being empty `[]`.
> > As per the code i debugged today, it looks like the `[]` means - delete all keys.
> > Reference:
> > https://github.com/cypress-io/cypress/blob/00920b1f9f93d0830003ac9198c3ad14e558489e/packages/driver/src/cypress/local_storage.coffee#L33
> > 
> > So, the code which should work for whitelist would be as:
> > ```js
> > const clear = Cypress.LocalStorage.clear
> > 
> > Cypress.LocalStorage.clear = function (keys, ls, rs) {
> >   if (keys && keys.length == 0) {
> >     keys = Object.keys(localStorage);
> >   }
> >   whitelistKeys = [];
> >   keys = keys.filter(function(i) {return whitelistKeys.indexOf(i) < 0;});
> >   return clear.apply(this, arguments)
> > }
> > ```
> 
> This isn't working as expected! In fact it doesn't remove any local storage item at all. I did a test like this. Set new item in local storage with name 'test'. Then in the whitelistKeys add 'test2'. It will not remove the 'test' item and any other item that exists in local storage.

Of course that won't work, it does:
```js
return clear.apply(this, arguments)
```

Instead of
```js
return clear.apply(this, keys)
```

Btw, not sure what `ls` and `rs` arguments are, but `localStorage.clear()` only accepts one argument and that's `keys`. I guess those are Cypress specific or something.

**Comment by NAMU1105** [comment] 2021-12-22 06:31
> const clear = Cypress.LocalStorage.clear;
> 
> Cypress.LocalStorage.clear = function (keys) {
>   if (keys && keys.length == 0) {
>     return;
>   }
>   whitelistKeys = [];
>   keys = keys.filter(function(i) {return whitelistKeys.indexOf(i) < 0;});
>   return clear.apply(this, keys);
> }

Thank you this saved my day!

**Comment by yescine** [comment] 2022-02-16 18:22
@abugleev thanks it worked with the whitelistkeys .

**Comment by emilyrohrbough** [comment] 2022-10-21 20:28
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation). There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests.

To persist DOM and browser state between a set of tests, i.e. local storage, you will be able to turn test isolation off for the run or at the suite level.

Closing this issue as done and tagging for the v12.0.0 release.

**Closed** 2022-11-16 21:46 UTC
Labels: type: feature, stage: ready for work, v12.0 Release
