### ISSUE TITLE
cy.intercept() does not work with brackets in URL

### ISSUE THREAD

**Issue by MayGo** [cypress-io/cypress#16361] opened 2021-05-06 09:36 UTC
### Current behavior
There is no way to make intercept work with URL that has brackets in them (for example `[i]`). It will work if those brackets are encoded in the actual URL and in the intercepted URL. But it is not an option to encode the actual URL.

### Desired behavior
```js
cy.intercept("https://test.something.com/api/v1/users?sort=email[i]", "something")
```
or at least with "*" 
```js
cy.intercept("https://test.something.com/api/v1/users?sort=email[i]*", "something")
```
to intercept request "https://test.something.com/api/v1/users?sort=email[i]"

For my case, the best fix would be to intercept if the request URL equals intercept URL exactly.
Currently, you can't even intercept plain exact URL
```js
cy.intercept("https://test.something.com/api/v1/users", "something")
```
and make a request to https://test.something.com/api/v1/users.
you have to append "*" to intercept URL

### Test code to reproduce

https://github.com/MayGo/cypress-test-tiny

### Versions

Cypress version 7.2.0

**Comment by jennifer-shehane** [comment] 2021-05-06 18:40
In the example you provided, the failing specs do show a failed request. So it's not intercepting the requests because they didn't go out. 

<img width="1044" alt="Screen Shot 2021-05-06 at 1 38 09 PM" src="https://user-images.githubusercontent.com/1271364/117348972-7a846800-ae70-11eb-8173-9a1da647619b.png">

Regardless, currently `cy.intercept()` does require the URL argument to be encoded. We're open to PRs to change this behavior. 

Duplicate of https://github.com/cypress-io/cypress/issues/15956

**Closed by jennifer-shehane** 2021-05-06 18:40 UTC
