### ISSUE TITLE
Blur event is not fired reliably in some situations

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1176] opened 2018-01-09 20:23 UTC
# bug

Mac, Cypress 1.4.1, Electron and Chrome 63

I have investigated source of failures in Todomvc app some more and found interesting thing. Take a look at https://github.com/cypress-io/cypress-test-tiny/tree/blur-test (I put entire Ampersand TodoMVC there in the branch `blur-test`, you can just open ampersand/index.html to see and test).

The test adds 3 todos, edits second, then checks if the local storage has been updated with new title text.

```js
it('edits todo', () => {
  createDefaultTodos()
  // let everything settle
  cy.wait(1000)

  visibleTodos()
    .eq(1)
    .find('label')
    .dblclick()

  // clear out the inputs current value
  // and type a new value
  visibleTodos()
    .eq(1)
    .find('.edit')
    .should('have.value', 'bar')
    .clear()
    .type('buy some sausages{enter}')
  cy.wait(1000)

  // confirm that new value is in localStorage
  cy
    .window()
    .its('localStorage')
    .its('todos-ampersand')
    .then(JSON.parse)
    .should('have.length', 3)
    .its('1')
    .its('title')
    .should('equal', 'buy some sausages')
})
```

When running in Electron or Chrome browser with Devtools closed, the test passes. I can open DevTools AFTER the test and see the "enter" + "blur" events triggered and propagating into the app.

<img width="1273" alt="screen shot 2018-01-09 at 3 10 24 pm" src="https://user-images.githubusercontent.com/2212006/34741376-76fdeb16-f550-11e7-84b2-a7bdedc306b8.png">

<img width="1049" alt="screen shot 2018-01-09 at 3 10 35 pm" src="https://user-images.githubusercontent.com/2212006/34741384-7cddfd46-f550-11e7-8bb1-f8e1137628e5.png">

If I open DevTools but keep the FOCUS on the app iframe or on the command log and reload the tests, they still work. But if I click on the devtools, for example into the console tab and reload the tests, the "blur" event is not fired anymore and the test fails

<img width="1085" alt="screen shot 2018-01-09 at 3 11 22 pm" src="https://user-images.githubusercontent.com/2212006/34741462-b8b19a08-f550-11e7-8c0b-b3765915c951.png">

Probably related to blur event is the run mode. It just fails 100%

<img width="898" alt="screen shot 2018-01-09 at 3 12 15 pm" src="https://user-images.githubusercontent.com/2212006/34741483-c664c300-f550-11e7-96c5-016143ac4834.png">

If I could see console.log messages during this run (https://github.com/cypress-io/cypress/issues/448) it could shed some light

**Comment by DanielMSchmidt** [comment] 2018-01-18 14:21
Hey there, I think I have a similar issue with focussing a field. I created a [small demo](https://github.com/DanielMSchmidt/cypress-autofocus-bug) if you check this repo out, run `npm install` and then `cypress open` the test works, if you run `cypress run` it fails. Maybe this helps to reproduce the issue 👍

**Comment by Bkucera** [comment] 2018-07-12 12:17
This might be fixed by #1939 , can anyone confirm?

**Comment by Bkucera** [comment] 2018-07-16 17:51
@DanielMSchmidt there is actually a problem with using the jquery `*:focus` selectors. Instead you should use `cy.focused().should(...` as that uses `document.activeElement` under the hood, and is more consistent and has better performance than searching the DOM for `:focus`. 

The change event not firing will be fixed alongside other issues in #2016

**Comment by warpdesign** [comment] 2018-12-12 16:22
I am having the same problem: the blur event isn't sent, I'm using Cypress `3.1.3` on macOS (mojave).

Here is what I noticed:

If the Chrome window where the Cypress test gets executed is active, the event is correctly sent/received by my app, but if the window isn't the active one, the blur event isn't received.

Here is the test:

```js
        cy.get('#view_0 [data-cy-path]')
            .type('/{esc}')
            .should('have.value', '');
```

My app is a React app that does this:

```js
    private onKeyUp = (event: React.KeyboardEvent<HTMLElement>) => {
        console.log('path keyup', event.keyCode);
        if (event.keyCode === KEYS.Escape) {
            event.nativeEvent.stopImmediatePropagation();
            // lose focus
            this.input.blur();
        } else if (event.keyCode === KEYS.Enter) {
            this.onSubmit();
        }
    }
```

My input element also has a onBlur event which is never trigger if the Chrome window is not active while the tests are being run.

Note that this doesn't happen in real life since the Chrome window must be active for the user to type something.

Hope this helps.

**Comment by Bkucera** [comment] 2018-12-27 14:02
This should fixed by PR #2982 
We now polyfill focus/blur events that would otherwise be queued by the browser until it regains focus.

**Closed** 2019-06-11 15:06 UTC
Labels: pkg/driver, stage: needs review

**Comment by hereiscasio** [comment] 2019-06-27 12:42
Hi, i also face the same issue, that's, 

```
cy.get(...).type(...)
```

when Cypress's browser is not the active browser

then seems like ` type() ` will fire blur event,
but if Cypress's browser is under focusing, ` type() ` works great

at now, how can we user solve this issue . . . 😔 ?
i test this wired behavior 10x times

**Comment by drumslave-git** [comment] 2019-10-23 11:33
> Hi, i also face the same issue, that's,
> 
> ```
> cy.get(...).type(...)
> ```
> 
> when Cypress's browser is not the active browser
> 
> then seems like `type()` will fire blur event,
> but if Cypress's browser is under focusing, `type()` works great
> 
> at now, how can we user solve this issue . . . 😔 ?
> i test this wired behavior 10x times

can someone answer this please? I have a lot of logic based on blur event, and it is hard to work with tests because of that.

**Comment by jennifer-shehane** [comment] 2019-10-23 17:13
@drumslave-git This issue is closed and has been resolved. If you are seeing a bug in Cypress, open a new issue with a reproducible example. If this is a question, we recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).
