### ISSUE TITLE
`contains()` targets element with `pointer-events: none` and fails to click instead of targeting element higher up the tree

### ISSUE THREAD

**Issue by hon2a** [cypress-io/cypress#1887] opened 2018-06-06 10:44 UTC
### Is this a Feature or Bug?

~Bug.~ A feature, I guess. Thought it was a bug, but it turns out `contains` does something else than what I originally assumed.

### Current behavior:

I use UI components from Ant Design (React) and the [button](https://ant.design/components/button/) has the following mark-up:

```html
<button type="button" class="ant-btn">
  <span>Some Label</span>
</button>
```

and the following style applied:

```css
.ant-btn > span {
  pointer-events: none;
}
```

When I try to interact with the button using:

```javascript
cy.get('button').contains('Some Label').click()
```

I get the following error message:

> CypressError: Timed out retrying: cy.click() failed because this element:
> 
> <span>Create</span>
> 
> is being covered by another element:
> 
> <button type="button" class="ant-btn">...</button>
> 
> Fix this problem, or use {force: true} to disable error checking.
> 
> https://on.cypress.io/element-cannot-be-interacted-with

When I programmatically set `pointer-events` to `auto`, the issue disappears. Apparently the `contains` operator finds the `<span>` containing the text and then fails, because it has `pointer-events: none`.

### Desired behavior:

The `contains()` should ideally react to the expected interaction request by selecting elements without `pointer-events: none` when possible. In this case, it should select the `button` and the `click` should be triggered on it.

### Steps to reproduce:

https://github.com/hon2a/cypress-test-tiny/tree/hon2a/pointer-events-bug

### Versions

Cypress: 3.0.1
OS: macOS 10.13.5
browser: Chrome 66.0

**Comment by jennifer-shehane** [comment] 2018-06-06 20:06
This is actually not how `.contains()` was designed to work. It was specifically designed to prefer elements like `button` over `span` as documented [here](https://docs.cypress.io/api/commands/contains.html#Preferences). 

Can you try specifying a selector in `.contains()` like in the code below? This should definitely prefer the button. Let me know what the result is of this.  
```js
cy.contains('button', 'Some Label').click()
```

**Comment by brian-mann** [comment] 2018-06-06 20:39
It's because setting `pointer-events: none` changes how the browser yields elements via `document.elementFromPoint`. 

In that case the element is "falling through" which triggers Cypress into thinking its being covered up. There's a note / documentation somewhere that talks about `pointer-events: none` not being handled correctly.

I would open a new issue about this specifically.

**Comment by jennifer-shehane** [comment] 2020-06-22 05:54
Closing as resolved. This now prints an error correctly indicating that the element has pointer-events: none.

<img width="544" alt="Screen Shot 2020-06-22 at 12 23 28 PM" src="https://user-images.githubusercontent.com/1271364/85253021-4041f000-b483-11ea-975c-ba0a57a2ac54.png">
 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed** 2020-07-14 07:31 UTC
Labels: type: error message, type: unexpected behavior

**Comment by asmirnov-style** [comment] 2022-09-23 14:39
This is kind of sucks. If it works manually, then it should work with Cypress. ({force: true} not always a solution)
SOLUTION: add `.scrollIntoView().wait(1000).click({ force: true });` especially wait will help you, if force click doesn't help

**Comment by kprisAutomation** [comment] 2022-10-24 20:33
> This is kind of sucks. If it works manually, then it should work with Cypress. ({force: true} not always a solution)
> SOLUTION: add `.scrollIntoView().wait(1000).click({ force: true });` especially wait will help you, if force click doesn't help

Thank you!  doing this worked for me! the menu item had the pointer-event:none so neither .trigger('click') nor force:true would work.
