### ISSUE TITLE
Testing offline behaviour causes tests to become unresponsive

### ISSUE THREAD

**Issue by Mythie** [cypress-io/cypress#23889] opened 2022-09-20 03:23 UTC
### Current behavior

Previously we were able to test our applications ability to go offline and handle network instability using the methods outlined in the following article:

https://www.cypress.io/blog/2020/11/12/testing-application-in-offline-network-mode/

This had the caveat that we had to ensure we restored network connectivity ASAP otherwise Cypress would disconnect from the browser and tests would hang indefinitely.

Upon upgrading to Cypress 10+ these tests have broken and it appears as though Cypress isn't able to reconnect to the testing session, ideally this would not occur and the old behaviour would remain. 

### Desired behavior

In this situation we are expecting Cypress to retain it's prior behaviour where it would reconnect to the testing session and continue the test suite.

### Test code to reproduce

Please see the test code within the article.

### Cypress Version

^10.0.0

### Node version

v14.18

### Operating System

MacOS, Ubuntu

**Comment by ZachJW34** [comment] 2022-09-20 19:08
Closing as duplicate of https://github.com/cypress-io/cypress/issues/17723. Giving that issue a thumbs up will help push the issue along!

**Closed as completed by ZachJW34** 2022-09-20 19:08 UTC
