### ISSUE TITLE
Cannot read property isAttached of undefined - with firefox

### ISSUE THREAD

**Issue by sai-tej** [cypress-io/cypress#7899] opened 2020-07-07 04:58 UTC
### Current behavior:
Cypress is not working with firefox 78.0.1

```
TypeError: Cannot read property 'isAttached' of undefined

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Job Failure`
      at /home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/firefox-util.js:117:20
      at tryCatcher (/home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
      at /home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:15:34
      at /home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/firefox-util.js:235:40
      at tryCatcher (/home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/jenkins/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises 
```
### Desired behavior:

It should run without any errors

### Test code to reproduce
Any test that runs on firefox 78.0.1 in linux fails with this error during before each. 

```
/// <reference types="cypress" />
describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
  })
  it('still works', () => {
    cy.visit('https://example.cypress.io')
  })
})
```

### Versions
- Cypress 4.8.0
- Ubuntu 18.04
- Firefox 78.0.1

**Comment by sai-tej** [comment] 2020-07-07 05:01
**Work Around**
The work around is to disable firefox gc interval `"firefoxGcInterval": null`

But now we are trusting firefox to do the right thing and not crash during the tests. This, for some reason appears to be a ticking time bomb and that concerns us. Please let me know if that's not the case.

**Comment by sai-tej** [comment] 2020-07-07 05:04
This is same [issue on ff 75](https://github.com/cypress-io/cypress/issues/6813)

**Comment by jennifer-shehane** [comment] 2020-07-07 07:08
Duplicate of #6813

**Closed by jennifer-shehane** 2020-07-07 07:08 UTC
