### ISSUE TITLE
Smaller screenshot window when running under Chrome Headless

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#6351] opened 2020-02-06 21:27 UTC
### Current behavior:

When running under Chrome Headless, my screenshot is *800x600*, which is mostly taken up by the cypress log on the left side. My UI is scaled down to be very tiny.
When running under Electron, my screenshot is *1280x720*, which does help make things easier to read.

In both cases I'm using
```
  "viewportWidth": 1400,
  "viewportHeight": 1000
```

### Desired behavior:

I'd like the screenshots to be bigger under Chrome. My UI is scaled down to the point where it is illegible.

### Versions

Cypress 3.8.3
Ubuntu

**Comment by jennifer-shehane** [comment] 2020-02-07 01:45
Duplicate of #6210

**Closed by jennifer-shehane** 2020-02-07 01:45 UTC
