### ISSUE TITLE
clicking on links in application sending a invalid get request URL resulting in failure (404 error)

### ISSUE THREAD

**Issue by murthy-n** [cypress-io/cypress#4472] opened 2019-06-17 10:48 UTC
## Current behavior: 

clicking on any link even manually in cypress chrome browser throwing error (invalid get request URL has been sent to server) 
when i click on link getting below error
" /__/"landingpage.htm was not found on this server.
at the place of "/__/" domain name should be sent.

my base URL is ex: https://testapp.com/testing"
after login when i try to perform some actions
get request sent: "https://testapp.com/__/landingpage.htm" but it should have been "https://testapp.com/testing/landingpage.htm"

same script works fine in electron browser. have issues with chrome browser only.

**Comment by jennifer-shehane** [comment] 2019-06-21 09:16
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this? Any screenshots? [Debug logs](https://on.cypress.io/debugging#Debug-the-Command-Line)?

**Comment by murthy-n** [comment] 2019-06-23 12:38
Hi Jennifer-shehane please find the attached screenshot. after clicking on some link it will throw
the requested URL /__/landingpage.htm was not found on this server. 
![CypressError](https://user-images.githubusercontent.com/50316749/59976418-c2ce7000-95e1-11e9-9e39-72eda0a5dcc5.png)

**Comment by jennifer-shehane** [comment] 2019-06-24 07:11
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/3975 - I see your tests are also 'logging in' and I wonder if this is a result of a redirect also. Could you provide any more information in that issue? It will be hard to address without us being able to reproduce it ourselves.

**Closed by jennifer-shehane** 2019-06-24 07:11 UTC
Labels: stage: needs information

**Comment by jennifer-shehane** [comment] 2020-05-21 07:38
This fix is available starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments) which you can access by setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

The fix is experimental, so there may be some situations where the this is not fixed. 

If you're still this issue while setting the `experimentalSourceRewriting` to true in 4.6.0 - [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a reproducible example + screenshots, etc - filling out our issue template.
