### ISSUE TITLE
unable to cancel download

### ISSUE THREAD

**Issue by mudit94** [cypress-io/cypress#20071] opened 2022-02-07 12:47 UTC
### What would you like?

Hi Team,
I have a use case in which I begin download. The download starts happening at the default location. Now I want to click on the download and cancel it. How do I interact with native chrome browser option in cypress

### Why is this needed?

cancel download feature

**Comment by flotwig** [comment] 2022-02-08 21:53
Duplicate of #19969

**Closed by flotwig** 2022-02-08 21:53 UTC
