### ISSUE TITLE
Cypress.spec returns "All Integration Specs" via cypress open

### ISSUE THREAD

**Issue by AussieFlem** [cypress-io/cypress#18835] opened 2021-11-09 03:50 UTC
### Current behavior

When using _cypress open_ and the "Run # integration specs" Cypress.spec.name returns "All Integration Specs" rather than the name of the spec file executing at the time.

### Desired behavior

Cypress should return the name of the spec file being executed, rather than the summary string which is unrelated to any filenames used by the specs being executed

### Test code to reproduce

Create:
/cypress/integration/SpecFileA.spec.js
/cypress/integration/SpecFileB.spec.js

Open cypress using "cypress open"
Click an individual integration test file --> works as expected (returns "SpecFileA.spec.js" and "SpecFileB.spec.js")
Click the "Run 2 integration specs" option on the right hand side --> returns "All Integration Specs" for both Spec files

Note that it _does_ seem to work via _cypress run_ - it's the interactive version which seems broken.

### Cypress Version

8.7.0

**Comment by AussieFlem** [comment] 2021-11-09 03:55
Return value of Cypress.spec via _cypress open_
{
    "name": "All Integration Specs",
    "absolute": "__all",
    "relative": "__all",
    "specType": "integration",
    "specFilter": null
}

When executing a single spec file (Application.int.test.js):
{
    "name": "Application.int.test.js",
    "absolute": "/Users/myaccount/Projects/testing-cy-spec/cypress/integration/Application.int.test.js",
    "relative": "cypress/integration/Application.int.test.js",
    "specType": "integration",
    "specFilter": null
}

**Comment by jennifer-shehane** [comment] 2021-11-10 22:07
Duplicate of https://github.com/cypress-io/cypress/issues/3090

**Closed by jennifer-shehane** 2021-11-10 22:07 UTC
