### ISSUE TITLE
Freezing on Test runner screen when import aws amplify lib

### ISSUE THREAD

**Issue by dsjin** [cypress-io/cypress#7453] opened 2020-05-22 10:33 UTC
### Current behavior:

I executed test spec files and got freeze on Test runner screen.
![Screenshot](https://user-images.githubusercontent.com/8769240/82657326-2339b780-9c60-11ea-8dfe-ee891f0d0926.png)
But after i removed aws-amplify lib on support file then it can run normally.

### Desired behavior:

I would like to run aws-amplify lib on cypress 4.6.0 (The same code can run on 4.5.0 and 4.4.1)

### Test code to reproduce

support/command.js
`import Amplify, { Auth } from 'aws-amplify'`

### Versions

Cypress : 4.6.0
Preprocessor : Cypress-webpack
Browser : Chrome 83

**Comment by jennifer-shehane** [comment] 2020-05-26 06:08
This takes a full 10+ seconds to load the first test during `cypress run` or `cypress open` in Cypress regardless of version (not 4.6.0 related). I'm not using any preprocessor with my example. The increased time occurs when importing the `aws-amplify` modules. 

Including the `@cypress/webpack-preprocessor` v5.4.1 causes the Test Runner to never load and runs up my CPU over 100% with the Cypress process. Again, the Test Runner runs completely fine when I remove the `aws-amplify` import statement from the support file.

I'm going to close this as a duplicate of #7464, but we'll reopen this if that turns out to be a different issue. 

`support/index.js`

```js
import { Auth } from 'aws-amplify'
```

`spec.js`

```js
it('Loads the homepage', function () {
  cy.visit('index.html')
});
```

`index.html`

```html
<html>
<body>
</body>
</html>
```

Seems to stall at this DEBUG log:

```
  cypress:server:run browser launched +1s
  cypress:browserify finished bundling: /Users/jennifer/Library/Application Support/Cypress/cy/production/projects/cypress-transform-test-74d5161f4a1005f86b0d85a657ddcf07/bundles/cypress/integration/spec.js +510ms
  cypress:server:controllers:spec sending spec { filePath: '/Users/jennifer/Library/Application Support/Cypress/cy/production/projects/cypress-transform-test-74d5161f4a1005f86b0d85a657ddcf07/bundles/cypress/integration/spec.js' } +558ms
```

**Comment by chrisbreiding** [comment] 2020-05-26 18:40
@jennifer-shehane As far as I can tell, this isn't related to #7464. In [this comment](https://github.com/cypress-io/cypress/pull/7485), you said this isn't related to the Cypress version, but #7464 will only happen in `4.6.0`. I'm going to re-open this, since it's a different issue.

**Comment by jennifer-shehane** [comment] 2020-05-29 10:39
@chrisbreiding Sorry if my comment was unclear. What I meant was that 

- there is an increased loading time when importing the aws-amplify in *every* version - around 10 secs. 
- in 4.6.0 the UI no longer loads at all (although maybe it takes more than 30+ seconds and I didn't wait).

**Comment by jennifer-shehane** [comment] 2020-06-02 09:34
Closing as duplicate of #7464

**Closed by jennifer-shehane** 2020-06-02 09:34 UTC
Labels: stage: needs investigating, type: regression, v4.6.0 :bug:
