### ISSUE TITLE
CRA/react-scripts v5, Mac Monterey: Cypress component test crashes with error RangeError: Invalid WebSocket frame: RSV1 must be clear

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/cypress#22762] opened 2022-07-13 11:37 UTC
### Current behavior

[This repo](https://github.com/muratkeremozcan/cra5-cy10-test) is using CRA & react-scripts v5 with a minimal Cypress 10 install. There is a simple component test that mounts the app.

On running the test, we get a crash on MacBook Pro, Mac Monterey 12.4, Intel Core i9.

To reproduce:

```bash
git clone https://github.com/muratkeremozcan/cra5-cy10-test.git
cd cra5-cy10-test
nvm use
yarn install
yarn cy:open-ct
```

[Works in CI](https://github.com/muratkeremozcan/cra5-cy10-test/runs/7319634870?check_suite_focus=true). Works if we downgrade react-scripts to v4, however that is a blocker for component test code coverage. More data [here](https://github.com/muratkeremozcan/react-hooks-in-action-with-cypress/pull/168). TL, DR; with react-scripts 5, we cannot configure webpack ([as in this commit](https://github.com/muratkeremozcan/react-hooks-in-action-with-cypress/pull/168/commits/1515ee27357ba3f67962a3aaed622bf90a99a065)) so that we can get coverage from component tests.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/34237651/178725916-5978fb9f-95ec-4f54-b8f9-d33285b1377d.png">

### Desired behavior

Component test do not crash on Mac Montery, with a repo using react-scripts v5.

More desired behavior is code coverage being included with component testing, as it used to be long time ago in the past.

### Test code to reproduce

https://github.com/muratkeremozcan/cra5-cy10-test

```bash
git clone https://github.com/muratkeremozcan/cra5-cy10-test.git
cd cra5-cy10-test
nvm use
yarn install
yarn cy:open-ct
```

### Cypress Version

10.3.0

**Comment by muratkeremozcan** [comment] 2022-07-13 14:30
I had 4 people try it , 2 internal to the company, and this only happens on my setup. First time. 

I appreciate any ideas.

**Comment by jamiescript** [comment] 2022-07-15 12:40
I am able to reproduce your example @muratkeremozcan on MacBook Air, Mac Monterey 12.4, Intel Core i5

I get the same `RSV1 must be clear` error on my project, when running in browser or CLI

**Comment by ZachJW34** [comment] 2022-07-15 15:54
I couldn't find any issues relating to webpack (and couldn't reproduce this issue myself), but it has to be related since you said downgrading to cra4 fixed this. I did find a [similar issue with Snowpack](https://www.snowpack.dev/reference/common-error-details#rangeerror-invalid-websocket-frame-rsv1-must-be-clear). Can you try overwriting your port to use something other than port 8080 (which is the default)? The config would look something like this:

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  component: {
    devServer: {
      framework: "create-react-app",
      bundler: "webpack",
      webpackConfig: {
        devServer: {
          port: 3000,
        },
      },
    },
  },
});
```

**Comment by marktnoonan** [comment] 2022-07-21 12:13
@muratkeremozcan I gave this a shot and couldn't reproduce either on my machine, how did you get on with @ZachJW34's suggestion?

**Comment by marktnoonan** [comment] 2022-07-28 12:58
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by marktnoonan** 2022-07-28 12:58 UTC
Labels: stage: awaiting response

**Comment by muratkeremozcan** [comment] 2022-07-28 13:06
> I couldn't find any issues relating to webpack (and couldn't reproduce this issue myself), but it has to be related since you said downgrading to cra4 fixed this. I did find a [similar issue with Snowpack](https://www.snowpack.dev/reference/common-error-details#rangeerror-invalid-websocket-frame-rsv1-must-be-clear). Can you try overwriting your port to use something other than port 8080 (which is the default)? The config would look something like this:
> 
> ```js
> const { defineConfig } = require("cypress");
> 
> module.exports = defineConfig({
>   component: {
>     devServer: {
>       framework: "create-react-app",
>       bundler: "webpack",
>       webpackConfig: {
>         devServer: {
>           port: 3000,
>         },
>       },
>     },
>   },
> });
> ```

Thank you very much, this worked.
