### ISSUE TITLE
is being covered by another element

### ISSUE THREAD

**Issue by xiaoxinhis** [cypress-io/cypress#7084] opened 2020-04-21 03:01 UTC

**Comment by jennifer-shehane** [comment] 2020-04-21 07:22
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

**Closed by jennifer-shehane** 2020-04-21 07:22 UTC

**Comment by hangho89** [comment] 2020-08-27 09:55
Hi @jennifer-shehane 
I have the same issue

- Browser :  85.0.4183.83
- Cypress: 5.0

**Current behavior**
1. Test run the first time is pass
![image](https://user-images.githubusercontent.com/49506960/91425532-72a60a00-e885-11ea-96dc-44e495ef8fe3.png)

2. Test run the second time is failing

![image](https://user-images.githubusercontent.com/49506960/91425685-aaad4d00-e885-11ea-8b46-67d2f97ad87f.png)


Cypress is telling me: 
CypressError
Timed out retrying: cy.click() failed because this element:

<span class="v-btn__content">...</span>

is being covered by another element:

<div class="layout fill-height justify-center align-center">...</div>

Fix this problem, or use {force: true} to disable error checking.

**Desired behavior:**
No error Can click on element.

**Comment by jennifer-shehane** [comment] 2020-08-27 10:12
@hangho89 Please provide a reproducible example - we can't look at the issue without that.

**Comment by hangho89** [comment] 2020-08-28 03:32
Hi @jennifer-shehane 
 
EX: 
**Funtion :**
SelectDate_GeneralSegmentTab(value) {
    var currentDate = new Date();
    var day = currentDate.getDate();
    cy.get(`[placeholder="${value}"]`).should("be.visible").click().wait(1000);
    cy.get(".v-menu__content.theme--dark.menuable__content__active")
      .should("be.visible")
      .find(".v-picker.v-card.v-picker--date.theme--dark")
      .should("be.visible")
      .find(".v-date-picker-table.v-date-picker-table--date.theme--dark")
      .should("be.visible")
      .find("table tbody tr td")
      .contains(day)
      .should("include.text", day)
      .click({ timeout: 2000 });
  }

**Test**
it("After Saving valid data that data after save,  will have status =  Stored", function () {
    //DateOfRegistratio
    CreateManifest.SelectDate_GeneralSegmentTab(
      fields.dateOfRegistration
    );
    CreateManifest.ScrollTo("center");
    //Date Of Departure
    CreateManifest.SelectDate_GeneralSegmentTab(
      fields.dateOfDeparture
    );
    //Date Of Arrival
    CreateManifest.SelectDate_GeneralSegmentTab(
      fields.dateOfArrival
    );
});
****Error:**
-  when I test run the first time is pass
- Test run the second time: this case can pass or failing
=>  I think if I many times test run. It will fail and display error is being covered by another element: class="layout fill-height justify-center align-center"


Thank you so much because you support me

**Comment by jennifer-shehane** [comment] 2020-08-28 08:15
@hangho89 I can't run the code as provided - there is no application to run this test code against.
