### ISSUE TITLE
Webpack Preprocessor publicPath `auto` not supported

### ISSUE THREAD

**Issue by brianorwhatever** [cypress-io/cypress#18748] opened 2021-11-02 16:25 UTC
### Current behavior

When running cypress with webpack preprocessor it fails (in chrome & cypress gui) with a "publicPath `auto` not supported by the browser. It's impossible to change this configuration because it is being overwritten here: https://github.com/cypress-io/cypress/blob/4d9fb6c507e0720bfb804f31232ffa208bc12299/npm/webpack-preprocessor/index.ts#L204

### Desired behavior

Be able to configure the `output.publicPath` in the webpack config

### Test code to reproduce

This issue is for the same issue https://github.com/cypress-io/cypress/issues/8900

### Cypress Version

8.4.0 / 8.7.0

**Comment by RickyC0626** [comment] 2021-12-24 10:12
Can confirm even in `v9.2.0`. I still get the automatic publicPath error even when `webpack.config.js` is properly configured to explicitly define `publicPath`.

**Comment by emilyrohrbough** [comment] 2022-01-25 23:25
@brianorwhatever thank you for logging this issue. It appear to be a duplicate of https://github.com/cypress-io/cypress/issues/18748. I'm going to close this to keep track of this in one place.

**Closed by emilyrohrbough** 2022-01-25 23:25 UTC
