### ISSUE TITLE
No text is selected when using shift + arrow keys

### ISSUE THREAD

**Issue by kolpav** [cypress-io/cypress#14797] opened 2021-01-28 12:29 UTC
### Current behavior
No text is selected
### Desired behavior
`D` letter should be selected
### Test code to reproduce

```jsx
const App = () => <div contentEditable />
```

```javascript
  it('shift+left arrow selects text', () => {
    cy.get('div[contentEditable="true"]')
      .type('ABCD')
      .type('{shift}{leftarrow}')
      // I omitted text select assertion please test by hand in browser
  })
```

(I also tested it with plain `<input />` with same results.)
### Versions
`6.3.0`

**Comment by jennifer-shehane** [comment] 2021-02-02 04:02
We don't support text selection natively in Cypress yet, but there are some workarounds detailed in this thread: https://github.com/cypress-io/cypress/issues/2839 

Duplicate of #2839

**Closed by jennifer-shehane** 2021-02-02 04:02 UTC
