### ISSUE TITLE
Cypress size?

### ISSUE THREAD

**Issue by maxime1992** [cypress-io/cypress#2168] opened 2018-07-18 14:46 UTC
### Current behavior:

I was surprised to see that my node_modules is now 1.3 GB.

It used to be ~700mb and don't remember adding a lot of libs during the past few months.

I've been digging into the issue and found the following:

![image](https://user-images.githubusercontent.com/4950209/42888693-ae0d7780-8aa0-11e8-92d3-06a78eb3ef89.png)

Cypress is huge (394 mb) and, I might get it.

But, why do we have a node modules inside cypress folder? Shouldn't be flattened at the top of the `node_modules` of my project?

Also, is there anyway of cleaning what's not necessary before publishing to npm?

### Versions
`"cypress": "2.1.0",`

Ubuntu 18.04

**Comment by jennifer-shehane** [comment] 2018-07-18 15:03
Duplicate of https://github.com/cypress-io/cypress/issues/1806

**Closed by jennifer-shehane** 2018-07-18 15:03 UTC
Labels: type: duplicate
