### ISSUE TITLE
Testing vuex store with vue 3 script setup sugar fails

### ISSUE THREAD

**Issue by ThiloHettmer** [cypress-io/cypress#22524] opened 2022-06-26 10:21 UTC
### Current behavior

When running a vuex test with vue 3 script setup sugar, the test will fail with the following message:

`Timed out retrying after 4000ms: cy.its() errored because the property: $store does not exist on your subject.

cy.its() waited for the specified property $store to exist, but it never did.

If you do not expect the property $store to exist, then add an assertion such as:

cy.wrap({ foo: 'bar' }).its('quux').should('not.exist')`

As soon as the setup sugar is removed from App.vue the test will run successfully.

Test is located under cypress/e2e/vuex.cy.js

### Desired behavior

Should not fail with script setup sugar

### Test code to reproduce

https://gitlab.com/ThiloHettmer/vite-vuex-cypress-bug-demonstration

### Cypress Version

10.2.0

**Comment by lmiller1990** [comment] 2022-06-27 08:08
Hi! Thanks for the reproduction.

You are using E2E testing. We've also got [Component Testing](https://docs.cypress.io/guides/component-testing/writing-your-first-component-test) which might be of interest!

As for your actual observation: I think this is actually the intended behavior of `script setup`. It's "closed by default" and this means you cannot access component properties like this. [See here in the RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#exposing-components-public-interface). I tried doing `defineExpose({ $store })` but it did not work. It might be possible to hack it in, but think the idea of `<script setup>` is to discourage this.

I came up with an alternative: if you change your `main.ts` slightly, you can access it:

```js
const app = createApp(App)

//@ts-ignore
if (window.Cypress) {
  //@ts-ignore
  window.$store = store
  //@ts-ignore
  window.app = app
}

app.use(store)
app.mount('#app')
```

And the test:

```js
describe('Test vuex store', () => {
  const getStore = () => cy.window().its('$store')

  it('should have vuex stores', () => {
    cy.visit('/')
    getStore().its('state').should('exist')
  })
})
```

It works!!

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/19196536/175891228-dadb4d8d-6c46-4b09-bb05-61e574db02a6.png">

I think this is probably the intended behavior, and it's in the Vue library, not Cypress, so I don't think we can access `$store` like this anymore.

**Comment by ThiloHettmer** [comment] 2022-06-27 08:16
Hi, 

thanks alot for your explanation and solution! I didn't know that, so I hope I didn't waste too much of your time ;)

**Closed** 2022-06-27 19:08 UTC
Labels: stage: wontfix, stage: awaiting response, existing workaround, CT, stage: routed to ct

**Comment by binaryfunt** [comment] 2023-03-09 15:45
Another possibility is, in `main.js`:
```js
const app = createApp(App)
// ...

if (window.Cypress) {
  window.app = app.config.globalProperties
}
```

This allows accessing Vue plugins etc. too using `cy.window().its('app.$myPlugin')`
