### ISSUE TITLE
Cypress assertion throws an error even when the requirements are correct

### ISSUE THREAD

**Issue by muellercornelius** [cypress-io/cypress#6176] opened 2020-01-16 08:16 UTC
Cypress Assertion throws error even when the requirements are correct

### Current behavior:

![image](https://user-images.githubusercontent.com/26606825/72505250-da03d200-383f-11ea-8490-196f1b459cad.png)

**AssertionError: expected '<input.dx-texteditor-input>' to have value '5.001,00 €', but the value was '5.001,00 €'**

I compare two values with each other. They look identical but Cypress is not satisfied

### Desired behavior:

The Assertion should not fail.

### Test code to reproduce

We are using Devexpress for our UI Components. The Dom Element of this textbox looks like this:

```html
<div data-v-7893b764="" id="durchschnittlicherPreisTextbox" class="dx-show-invalid-badge dx-numberbox dx-texteditor dx-show-clear-button dx-editor-underlined dx-widget">
    <input type="hidden" value="0">
    <div class="dx-texteditor-container">
        <div class="dx-texteditor-input-container">
            <input inputmode="decimal" autocomplete="off" class="dx-texteditor-input" type="text" spellcheck="false" min="undefined" max="undefined" step="1" aria-valuemin="" aria-valuemax="" tabindex="0" aria-valuenow="0" role="spinbutton">
            <div data-dx_placeholder="" class="dx-placeholder dx-state-invisible"></div>
        </div>
        <div class="dx-texteditor-buttons-container"><span class="dx-clear-button-area"><span class="dx-icon dx-icon-clear"></span></span>
            <div></div>
        </div>
    </div>
</div>
```

**The Code I am using for the Assertion:** 
```js
cy.get('#durchschnittlicherPreisTextbox')
  .find('.dx-texteditor-input')
  .should('have.value', '5.001,00 €');
```

### Versions

Chrome: 79
Cypress: 3.8.2
Windows 10

**Comment by jennifer-shehane** [comment] 2020-01-16 18:05
There could be some variation in the spacing that is causing the strings to not match. Maybe the 'space' is not really a space character but another whitespace character?

I tried to reproduce what you're describing, but unfortunately I can't since I wasn't provided a fully reproducible example. There's no explanation on how the value is set for example. 

The below examples work

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <input class="dx-texteditor-input" value="5.001,00 €">
</body>
</html>
```

```js
it('works', () => {
  cy.visit('index.html')
    .get('.dx-texteditor-input')
    .should('have.value', '5.001,00 €')
})
```

<img width="635" alt="Screen Shot 2020-01-17 at 12 34 49 AM" src="https://user-images.githubusercontent.com/1271364/72550466-2e9b6180-38c1-11ea-9fa5-ed9b7634eebc.png">


Also typing the value into the field and then checking the value works also. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-01-16 18:05 UTC
