### ISSUE TITLE
Dashboard disappear

### ISSUE THREAD

**Issue by Horfon** [cypress-io/cypress#2216] opened 2018-07-26 15:00 UTC
### Is this a Feature or Bug?

A Bug i guess

### Current behavior:

The dashboard is not displayed when i launch my tests

### Desired behavior:

The Dashboard should('be.visible')

### Steps to reproduce:
Cypress was working fine but my last change was to click on a onclick field

I don't know how to reproduce this...

I already uninstall and re-install Cypress but it doesn't change anything

### Versions

Version : v1.8.2
On Electron & Chrome
and i'm on Windows 7

Thanks for your help.

Horfon

**Comment by jennifer-shehane** [comment] 2018-07-26 15:07
Hi @Horfon, what is not displaying exactly? 

- Could you show a screenshot of what you are seeing? 
- Could you share your test code?

**Comment by jennifer-shehane** [comment] 2019-01-28 05:49
Closing due to not enough information provided. Please comment if you have test code + application code that can reproduce your issue.

**Closed by jennifer-shehane** 2019-01-28 05:49 UTC
