### ISSUE TITLE
Memory leak after upgrading v6.5.0 to v7.1.0

### ISSUE THREAD

**Issue by kpittman-securus** [cypress-io/cypress#16021] opened 2021-04-15 21:59 UTC
We are running Cypress v7.1.0 on Jenkins using the Electron browser setting. Videos and screenshots are enabled. `numTestsKeptInMemory: 1` and viewport is set to `1440x900`.

After upgrading from v6.5.0 to v7.1.0, we have gotten a lot more stable tests, which is awesome.

However, we have also been seeing test runs get stalled out / frozen. We noticed today that some builds were still running after 19 hours (overnight) and seemed to be doing nothing.

When we examined the logs, the last line we see is about the start of specfile # 49 of 64. We have had it stall on spec # 49 at 3 separate times today, across several different Jenkins workers.

When I dumped the resource utilization, it says that 1 instance of Cypress on the Jenkins worker is using 49gb of ram (we allow 2 simultaneous PR builds on each Jenkins worker).

This has not been an issue before, and while I realize there are a lot of moving parts, it seems to coincide with the Cypress upgrade.

Is there anything I can do to try and further narrow down the cause? Anything I can do to rule out Cypress itself as the issue?

**Comment by maga-polito** [comment] 2021-04-16 07:12
after upgrading I'm experiencing same problem, previous version working was 6.6. I'm running tests on docker with base image cypress/browsers:node14.16.0-chrome89-ff86

**Comment by agg23** [comment] 2021-04-16 12:34
Would you happen to be using Windows on your Jenkins machines? We have #15973, though at the moment we've only had it reported on Windows.

**Comment by kpittman-securus** [comment] 2021-04-16 15:31
> Would you happen to be using Windows on your Jenkins machines? We have #15973, though at the moment we've only had it reported on Windows.

No, it's a linux AMI.

**Comment by agg23** [comment] 2021-04-16 15:36
Any repro you could provide would be appreciated.

I suggest trying Cypress v6.8 and seeing if the memory leak occurs there. We have some significant performance regressions with 7.x that are currently under investigation (see #15853).

**Comment by kpittman-securus** [comment] 2021-04-16 16:03
@agg23 ok, the trouble is it's pretty intermittent. We haven't been able to determine what causes this to happen, so if there's anything you could suggest to troubleshoot it would be very helpful. As a workaround we just put a hard timeout on all builds to terminate after 3 hours.

**Comment by kpittman-securus** [comment] 2021-04-16 18:46
@agg23 we have reverted back to v6.5.0 since that was the last known-good version for us (we had not used 6.8 at all).

It's unfortunate because v7.1 seemed to have eliminated a lot of flakiness we had seen on v6 builds.

Again, if there's anything I could do to try and help isolate the cause, please let me know. We would like to be back on v7 as soon as we can!

**Comment by csvan** [comment] 2021-04-17 06:11
@kpittman-securus have you tried 6.9.1? We are seeing roughly the same performance as 6.5

**Comment by kpittman-securus** [comment] 2021-04-19 17:04
@csvan we did not bother, since 6.5 was known-good for us and this was basically blocking builds for us, we didn't want to have to guess-and-check to see if a certain version would work. We are going to be pinned at 6.5 until there's updates from the Cypress team. ( @jennifer-shehane 😅  ? )

**Comment by michalscreen** [comment] 2021-04-22 08:40
It may be relevant: I have noticed (it would be difficult not to ^^") a major downgrade in terms of cypress performance after bumping version from 6.8.0 to 7.1.0.

Runs that used to take around 20 min were significantly delayed (between 3 and 4 hours longer!), and time between executing a test file and another one did extend to 30 - 40 minutes. Plus recorded videos were choppy and frozen.

After reverting to cypress 6.8.0 everything seems to be fine.

Details:
browser: electron
ci/cd: github actions (so probably it's not only a jenkins related issue)

**Comment by jennifer-shehane** [comment] 2021-04-22 12:51
@michaelhays We are aware of performance issues with the newer version and are actively working on fixing them.

**Comment by michaelhays** [comment] 2021-04-22 15:58
Good to know, I'll let @michalscreen know as well :stuck_out_tongue_winking_eye:

You can follow #15853 for progress on that, Michal.

**Comment by jennifer-shehane** [comment] 2021-04-26 18:19
There are some performance issues introduced in recent versions of Cypress, please see those issues for relevant updates. We're working on them.

- https://github.com/cypress-io/cypress/issues/15853
- https://github.com/cypress-io/cypress/issues/15779
- https://github.com/cypress-io/cypress/issues/16152
- https://github.com/cypress-io/cypress/issues/15973
- https://github.com/cypress-io/cypress/issues/15990

If you are running Cypress in a headless browser, please try reducing the screen size to the default size prior to 7.0 (1280x720) to see if the new issues are related to the increase in screen size. [Instructions here.](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless) 

If that doesn't resolve the issue, I suggest downgrading to the last known version of Cypress that worked well.

We'll be closing this issue as there are no reproducible actions. For now we need to focus on the performance issues where we're given clear reproducible examples.

**Closed by jennifer-shehane** 2021-04-26 18:19 UTC
Labels: CI: jenkins, type: performance 🏃‍♀️
