### ISSUE TITLE
Feature request: Run subset of single spec file from CLI 

### ISSUE THREAD

**Issue by gone** [cypress-io/cypress#7220] opened 2020-05-04 18:49 UTC
### Current behavior:

Currently when running a single spec file all tests within the spec file are run. I'm scripting the test run within a larger app and I'm trying to do a flow of set up -> run cypress -> check data -> tear down around the test and currently I can't isolate each test to check the results.

### Desired behavior:

I'd like to be able to run a subset (one) similar to how mocha's -g flag works https://mochajs.org/#-grep-regexp-g-regexp

something like
`yarn run cypress run --spec "src/__tests__/cypress/integration/signup.js" -g "it works" `
`yarn run cypress run --spec "src/__tests__/cypress/integration/signup.js" -g "this one fails" `

**Comment by jennifer-shehane** [comment] 2020-05-05 06:51
Duplicate of #1865

**Closed by jennifer-shehane** 2020-05-05 06:51 UTC
