### ISSUE TITLE
ECONNRESET issue

### ISSUE THREAD

**Issue by VinothCoder** [cypress-io/cypress#19451] opened 2021-12-22 07:52 UTC
### Current behavior

Facing below issue while running cypress.
Browser opens for two seconds and closes automatically.
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
 {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
```
### Desired behavior

Cypress should run the defined test cases

### Test code to reproduce

Test

### Cypress Version

8.7.0

**Comment by emilyrohrbough** [comment] 2021-12-22 13:52
Duplicate of https://github.com/cypress-io/cypress/issues/14175 & https://github.com/cypress-io/cypress/issues/19451. 

Closing to keep this info in one issue.

**Closed by emilyrohrbough** 2021-12-22 13:52 UTC
