### ISSUE TITLE
Fail a test when errors occur in the Vue JS pipeline 

### ISSUE THREAD

**Issue by WayneHiller** [cypress-io/cypress#5385] opened 2019-10-16 19:54 UTC
I would like to fail a test if any errors occur within the Vue JS pipeline like within event handlers etc. Vue has it's own built in error handling so errors are handled, thus a Cypress test will never see them.

I have found a way to call into Cypress from the `Vue.config.errorHandler` in my app:

```js
        Vue.config.errorHandler = (err, vm, info) => {
            const er = "Error in " + info + ": \"" + (err.toString()) + "\"";
            const cy = (window as any).Cypress;
            if (cy && cy.onVueError) {
                cy.onVueError(er);
            }
        };
```

In the Cypress commands.js file I have:
```js
Cypress.onVueError = function(err) {
    assert.isNotOk(err, err.message);
}
```

Now the trick is how can I fail the currently running test from `Cypress.onVueError` without trying to access the DOM to force a failure? 

Why is there no `cy.fail("reason")` method in Cypress for special cases like this? I could not find anything like this in the docs.

It seems like Cypress should handle this on it's own or at least have a plugin or something.

**Comment by jennifer-shehane** [comment] 2019-10-29 20:10
@WayneHiller Have you tried throwing the error from within your application? Cypress automatically fails tests on uncaught exceptions, so if you can throw an error I think it may naturally fail the test. 

You could set up a listener in Cypress to listen for uncaught exceptions if you want to play around with that: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by WayneHiller** [comment] 2019-10-29 21:41
@jennifer-shehane  That will not work for Vue JS because they have a built in Exception Handler. You can override the Vue.errorHandler but if you throw an exception from there it is caught as well.

Maybe the best would be if Cypress had a method that could be called to simulate what happens when an unhandled Exception is thrown.  That way if a framework like Vue JS has a global error handler you could use the global "errorHandler" event and then just call Cypress.exception( .. ) or whatever it is called.

**Comment by bahmutov** [comment] 2020-02-20 18:50
@WayneHiller give us a tiny reproduction repo and we can figure out. On the first glance, it seems to be an async error that is similar to https://cypress-io.ghost.io/blog/2020/01/16/when-can-the-test-stop/

**Comment by WayneHiller** [comment] 2020-02-20 19:11
@bahmutov You might have misunderstood my issue. There is no issue with cypress (bug). The problem is Vue JS handles all exceptions itself. This means that cypress will never see any JS errors thrown by a Vue app. The only way I can find around the issue is to setup an error handler in Vue to call a method in cypress like:

```
Vue.config.errorHandler = (err, vm, info) => {
            const er = "Error in " + info + ": \"" + (err.toString()) + "\"";
            const cy = (window as any).Cypress;
            if (cy && cy.onVueError) {
                cy.onVueError(er);
            }
        };
```

In my tests I have a method like:
```
Cypress.onVueError = function(err) {
    ????? Cypress.fail(err.message);
}
```

I need a method in cypress to "Fail" the test and display any error without accessing the DOM at all.

**Comment by bahmutov** [comment] 2020-02-20 19:19
Ok still please create a tiny Vue repo so we can take a look

**Comment by johnpeb** [comment] 2020-02-20 21:36
I was able to use the following to get cypress to fail the test when there's a Vue error
```
if (window.Cypress) {
	// Expose Vue errors to Cypress as uncaught exceptions
	Vue.config.errorHandler = function(err/*, vm, info*/) {
		setTimeout(() => {throw err})
	}
}
```

**Comment by WayneHiller** [comment] 2020-02-20 23:15
@johnpeb Ah yes that will work because of the setTimeout, cool will try that

**Comment by jennifer-shehane** [comment] 2020-07-14 09:29
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-14 09:29 UTC
Labels: stage: proposal 💡, type: feature
