### ISSUE TITLE
No way to unselect all options in <select multiple />

### ISSUE THREAD

**Issue by Sawtaytoes** [cypress-io/cypress#17462] opened 2021-07-23 06:00 UTC
### Current behavior

In an HTML `<select />`, when the `multiple` property is set, there's no way to unselect all items. I can select `''`, but it will complain that option doesn't exist.

I was hoping for `.unselect()`, `.select()` or `.select(null)` to do it.

### Desired behavior

Unselect all items regardless of which options exist to select.

### Test code to reproduce

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <select
    id="color"
    multiple
    name="color"
    size="4"
  >
    <option value="red">
      Red
    </option>

    <option value="yellow">
      Yellow
    </option>

    <option value="green">
      Green
    </option>

    <option value="blue">
      Blue
    </option>
  </select>
</body>
</html>
```

```js
describe(
  'Multi Select',
  () => {
    it(
      'Unselect selected values.',
      () => {
        cy
        .visit(
          'multi-select'
        )

        cy
        .findByLabelText( // I'm using @testing-library/cypress.
          'Select zero to many colors.'
        )
        .select('')
        .should(
          'not.be.selected'
        )
      },
    )
  },
)
```

### Cypress Version

8.0.0

**Comment by Sawtaytoes** [comment] 2021-07-23 06:01
I think this to verify my form library is working correctly. If no options are selected, it shouldn't have any selected.

**Comment by jennifer-shehane** [comment] 2021-07-23 14:09
Duplicate of https://github.com/cypress-io/cypress/issues/4318

**Closed by jennifer-shehane** 2021-07-23 14:09 UTC
