### ISSUE TITLE
Memory leak still in long running single test

### ISSUE THREAD

**Issue by Konstruktour** [cypress-io/cypress#6330] opened 2020-02-05 11:36 UTC
As already described [here](https://github.com/cypress-io/cypress/issues/4164) the memory leak is still present (also in the new version 3.8.3) - the supposed [fix](https://github.com/cypress-io/cypress/issues/4164#issuecomment-502668433) did maybe solve another issue, but not the one i described in the original issue.
So i would ask you kindly if you could either reopen the original issue or keep this one.

**Comment by jennifer-shehane** [comment] 2020-02-05 15:16
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4164, we'll comment in that issue with our findings on this issue still occurring. Please feel free to comment in there as the comments have been unlocked.

**Closed by jennifer-shehane** 2020-02-05 15:16 UTC
