### ISSUE TITLE
Can't resolve typescript when using Yarn v2 with PlugNPlay

### ISSUE THREAD

**Issue by johnwiseheart** [cypress-io/cypress#15241] opened 2021-02-26 08:00 UTC
### Current behavior
When upgrading to Yarn v2 with plug n play, Cypress tests and configuration which were previously working no longer work. Specifically, when running with debug mode, I see
```
  cypress:server:plugins resolving typescript with options { basedir: '/Users/john/<repo>' } +0ms
  cypress:server:plugins could not resolve typescript, error: Cannot find module 'typescript' from '/Users/john/<repo>' +9ms
```
even though `typescript` is present in the project.

I imagine this is probably because the `node_modules` directory no longer exists with `pnp`. However, I found https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ts-node.js, and tried using `resolve.sync("typescript")` myself, which seemed to work. 

### Desired behavior
It should continue working with no issues.

### Versions

Broken on 6.5.0, 6.6.0.

**Comment by jennifer-shehane** [comment] 2021-02-26 15:13
Duplicate of https://github.com/cypress-io/cypress/issues/8008

**Closed by jennifer-shehane** 2021-02-26 15:13 UTC
