### ISSUE TITLE
Giving access to users is buggy and not transparent

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#557] opened 2017-07-12 08:03 UTC
I received an "A user request needs your attention" e-mail, where my coworker requested access to the organization. Beside the fact that he already was in the user's list, he now is added to the list twice (same name, same e-mail address).

I think you should remove duplicate users or, even better, do not allow to add people that already have access. In this case I think that he did not have access in the first place, despite that he was in the list, resulting in this request e-mail.

As side effect, I did not see any "accept" or "reject" button. After clicking the "Manage users" button in the e-mail, the user was automatically added without confirmation.

**Comment by jennifer-shehane** [comment] 2019-02-01 11:44
Hey @trydionel, can you look into this (embarrassingly) old issue and open an issue on the Services board?

I can confirm that at least part of this issue still exists, as I'm able to invite an existing user to my organization. 

<img width="1015" alt="screen shot 2019-02-01 at 6 12 32 pm" src="https://user-images.githubusercontent.com/1271364/52121187-1e0cbf80-264d-11e9-9199-86053d8cc2cc.png">

**Comment by jennifer-shehane** [comment] 2021-02-04 06:05
The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thanks!

**Closed by jennifer-shehane** 2021-02-04 06:05 UTC
Labels: external: dashboard, stage: ready for work, type: unexpected behavior
