### ISSUE TITLE
Cypress crashes when a site uses secure cookies

### ISSUE THREAD

**Issue by timcosta** [cypress-io/cypress#1264] opened 2018-02-06 20:04 UTC
- Operating System: macOS 10.12
- Cypress Version: 1.4.2
- Browser Version: Chrome 64.0.3282.140

### Is this a Feature or Bug?
Bug

### Current behavior:
Subsequent get/sets for a cookie that has `secure: true` set by the server fail with the message `Failed to parse or set cookie named "<name>"`

### Desired behavior:
Requests made to/from servers utilizing secure cookies should work.

### How to reproduce:
1. Use a cookie on your domain that is https/secure restricted
2. Make a request to a route that will set this cookie
3. Verify cookie is set successfully
4. Make another request to same domain for cookie
5. Request fails with error about parsing cookie

### Additional Info (images, stack traces, etc)
I believe this is due to the invalid SSL cert used by Cypress. Setting `"chromeWebSecurity": false` allowed the subsequent requests to begin working. Possible solution would be to force `secure: false` on cookie set operations.

**Comment by brian-mann** [comment] 2018-07-12 21:45
I believe this is a duplicate of: https://github.com/cypress-io/cypress/issues/1321

**Closed** 2018-10-31 17:09 UTC
Labels: type: duplicate
