### ISSUE TITLE
Cypress exits unexpectedly while execution

### ISSUE THREAD

**Issue by anas-qa** [cypress-io/cypress#2585] opened 2018-10-10 10:15 UTC
### Current behavior:
I have a basic login module consist of a username, password, and a Btn

Filling details and then click on the Btn will terminate execution and show this 

👇
 
![screen shot 2018-10-10 at 1 41 28 pm](https://user-images.githubusercontent.com/16471809/46728810-b04f1900-cc94-11e8-8c7a-d82551dc0096.png)

Besides, no logs on terminal (please advice if i can help you with some logs)

Terminal is not even showing a failure status, the execution displays as it's still initiating the test

👇 

![screen shot 2018-10-10 at 2 06 02 pm](https://user-images.githubusercontent.com/16471809/46729205-b72a5b80-cc95-11e8-8c61-ff05ed14349c.png)

And that's it! it's stuck now and no timeout or any other event until i terminate the command.

I tried `.debug()` but nothing as the execution is not terminated with some logs, it's stuck.

Btn selector

👇 

<img width="1196" alt="screen shot 2018-10-10 at 2 08 23 pm" src="https://user-images.githubusercontent.com/16471809/46729318-0c666d00-cc96-11e8-8848-ea60f120d847.png">

Code snippent

```javascript
describe('anything', function () {

    before(function () {

        // Navigate =>  Home Page
        cy.visit('/requestedPage')
    });


    it('should do anything', function () {

        cy.get('#IdSelector')
          .type('example');

        cy.get('#IdSelector')
          .type('example');

        cy.get('#IdSelector').click();
    });
```

### Versions
Capabilities as per the attached i-term screenshot

**Comment by bahmutov** [comment] 2018-10-10 13:12
Is it the same in Cypress 3.1.0?

**Comment by anas-qa** [comment] 2018-10-10 14:08
Just upgrade `npm install --save-dev cypress@3.1.0`

Same behavior in Cypress 3.1.0

**Comment by jennifer-shehane** [comment] 2018-10-10 21:54
I've seen some of these situations when there was some framebusting code on the url that was being visited at the time the page went to the "Whoops, there is no test to run." page. 

Are you able to track down if there is any code in the app you visited that is attempting to prevent the app from being run within an iframe? Because Cypress places the application under test within an iframe.

**Comment by anas-qa** [comment] 2018-10-11 05:18
Actually, this website that i am doing a test for is a third party in which i need to do a login on during my primary test, so, i am not sure about the code or if they are preventing running within iframe

However, i tried to do this flow using another automation framework and it went positivly.

**Comment by jennifer-shehane** [comment] 2018-11-19 21:05
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?

**Closed** 2019-01-03 11:34 UTC
