### ISSUE TITLE
Improved ability to run more than one test

### ISSUE THREAD

**Issue by craig-dae** [cypress-io/cypress#16326] opened 2021-05-04 17:43 UTC
### What would you like?

I have too many tests to run them all before pushing. I typically want to run a bunch of tests, either in a folder, or close to each other alphabetically within a folder, after making a change. 

Imagine I updated the User Profile page. Maybe I want to run all the /User Profile tests, but I don't want to waste my time running other tests locally. I'll let CI handle it. Or maybe I worked on User Profile/Settings, and I just want to run a few Profile/Settings related tests. 

I would like to either: 
- Run all tests in a specified folder
- Highlight/run a bunch of selected tests
- Be able to queue up additional tests after the one I'm running (like a music app)

### Why is this needed?

Makes it easier to run a selected set of tests, before doing a push and relying on CI to run them. 

This is not super urgent. It's a nice-to-have. But I will be more likely to run the correct tests locally, before pushing and discovering that I missed something.

**Comment by jennifer-shehane** [comment] 2021-05-04 18:22
You can run a selected subset of files based on the search filter. Full instructions here: https://on.cypress.io/writing-and-organizing-tests#Run-filtered-specs

Duplicate of https://github.com/cypress-io/cypress/issues/3607

**Comment by jennifer-shehane** [comment] 2021-05-04 18:23
Or if you don't need the UI, run `cypress run --specs` with the list of specs to run locally.

**Closed by jennifer-shehane** 2021-05-04 18:22 UTC
