### ISSUE TITLE
Test passes when loading a page which returns 500

### ISSUE THREAD

**Issue by trygveaa** [cypress-io/cypress#2825] opened 2018-11-22 13:58 UTC
### Current behavior:

If a page which is navigated to during a test returns HTTP status 500, the test still passes.

Note that the test does fail when visiting the page directly with `.visit`, it only passes when loaded by normal navigation, e.g. by clicking a link or submitting a form.

### Desired behavior:

I think the test should fail when a HTTP error is encountered on page load.

### Steps to reproduce:

This test reproduces the issue:

```js
describe('500 test', () => {
    it('should fail', () => {
        cy.visit('/');
        cy.get('[href="/500"]').click();
    });
});
```

With this config:

```js
{
    "baseUrl": "https://httpstat.us/",
    "chromeWebSecurity": false
}
```

Note that I had to disable web security for this particular page, otherwise I get a cross origin error. Since it is a relative link, that shouldn't be necessary. But if I test with a my own page, I don't get a cross origin error, so this seems to be a separate issue.

### Versions

Cypress 3.1.2 using the embedded Electron 59 on Arch Linux.

**Comment by bahmutov** [comment] 2018-11-25 01:04
yeah, I tried the above code, does, in fact, redirect to the page that has content, but status is 500

<img width="1278" alt="screen shot 2018-11-25 at 1 02 07 am" src="https://user-images.githubusercontent.com/2212006/48974358-e599a580-f04d-11e8-88cf-32e87bcf7f90.png">

when clicking on the underlined 500 in the stack trace goes to a blank source page, which is also weird by itself

<img width="1280" alt="screen shot 2018-11-25 at 1 02 21 am" src="https://user-images.githubusercontent.com/2212006/48974362-019d4700-f04e-11e8-88f3-7306c1ac3e21.png">

**Comment by jennifer-shehane** [comment] 2018-11-26 08:55
Duplicate of https://github.com/cypress-io/cypress/issues/2825

The issue already opened proposes an API to allow defined statuses that should fail any test where they occur.

**Closed by jennifer-shehane** 2018-11-26 08:55 UTC

**Comment by trygveaa** [comment] 2018-11-26 15:02
@jennifer-shehane: Which issue? You referenced this issue.

The visit command already fails for some statuses, so I think it would be natural that any page load with the same statuses makes the test fail, not just loads from the visit command. So I don't think you necessarily need an API to define statuses to solve this.

**Comment by brian-mann** [comment] 2018-11-26 15:09
A `500` is a valid status code. When you're acting like a user clicking links and stuff, then you're effectively in the e2e layer which is all about the user experience and is whatever the server serves. In this way, you're limited to testing things like the URL and the DOM directly.

However if you want to test the route programmatically, I suggest using `cy.request()` since you don't care about the actual HTML results.

```js
cy.get('href="/500"').invoke('prop', 'href').then((href) => {
  cy.request(href) // now makes a programmatic request to this HREF and will fail if it returns 500
})
```

**Comment by trygveaa** [comment] 2018-11-26 15:29
> A 500 is a valid status code. When you're acting like a user clicking links and stuff, then you're effectively in the e2e layer which is all about the user experience and is whatever the server serves. In this way, you're limited to testing things like the URL and the DOM directly.

Well, 500 is used when the server encountered an unexpected error, which I don't think can/should be any valid scenario. But I see your point for 4xx codes, which might be a valid scenario that you might want to test without failure.

> What I mean is - I don't think there's any guarantee that when you're testing that the test should necessarily fail when any request comes back 500.

Yeah, I agree that it might not be practical for all requests. What I was thinking about was just failing for page loads, to make them consistent with the visit command. But regarding the above, maybe consistency with visit isn't a good idea after all.

> However today, if you want to test the route programmatically, I suggest using cy.request() since you don't care about the actual HTML results.

I don't want to test the route programmatically. My use case for this request is that the test fails if the backend encounters an uncaught exception.

**Comment by trygveaa** [comment] 2018-12-04 09:05
That's for XHR's though. I'm talking about page loads.
