### ISSUE TITLE
toast-container component is not displayed in Cypress Version => 10.10.0

### ISSUE THREAD

**Issue by jaime1702** [cypress-io/cypress#24617] opened 2022-11-09 15:07 UTC
### Current behavior

since version 10.10.0 the toast-container component is not displayed in Cypress controlled browser (Chrome, Electron,Firefox, Edge).
![image](https://user-images.githubusercontent.com/61567212/200859578-1a3a0f47-2cb7-44fd-8a2c-572a82fc1d81.png)
![image](https://user-images.githubusercontent.com/61567212/200859754-4bc19c3e-0bba-47e6-a26b-189440216d47.png)
![image](https://user-images.githubusercontent.com/61567212/200859846-e48bb8ee-ff30-4522-8b7e-907eace9493d.png)

In version 10.9.0 it is working perfectly.

![image](https://user-images.githubusercontent.com/61567212/200860373-98b5a58e-de33-4a21-aa5d-72b2a11584c3.png)

### Desired behavior

demonstrate the same behavior as shown until cypress version 10.9.0

![image](https://user-images.githubusercontent.com/61567212/200860804-b846c684-e977-4914-9198-925ac1f0d8f7.png)

### Test code to reproduce

cy.findByText(searchData.msg).should('be.visible');

cy.contains(searchData.msg).should('be.visible');

searchData.msg = Pesquisa criado(a) com sucesso.

### Cypress Version

10.11.0

### Node version

v18.12.1

### Operating System

Ubuntu 22.04.1 LTS

### Debug Logs

```shell
cypress:server:browsers:electron console message: { column: 20, level: 'warning', line: 167230, source: 'console-api', text: "Cypress Warning: `cy.state('subject')` has been deprecated and will be removed in a future release. Consider migrating to `cy.currentSubject()` instead.", url: 'https://homol.system.solides.com/__cypress/runner/cypress_runner.js' } +0ms
  cypress:server:browsers:electron console message: { column: 26495, level: 'warning', line: 2, source: 'console-api', text: 'jQuery.Deferred exception: Wiselinks is not defined ReferenceError: Wiselinks is not defined\n' + '    at HTMLDocument.<anonymous> (https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js:131:19321)\n' + '    at u (https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js:2:24913)\n' + '    at m (https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js:2:25217)\n' + '    at i (https://homol.system.solides.com/pt-BR/crud/pesquisa:3:1403)\n' + '    at https://homol.system.solides.com/pt-BR/crud/pesquisa:3:1776 undefined', url: 'https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js' } +0ms
  cypress:server:browsers:electron console message: { column: 26495, level: 'warning', line: 2, source: 'console-api', text: "jQuery.Deferred exception: Cannot read properties of undefined (reading 'porcentagem') TypeError: Cannot read properties of undefined (reading 'porcentagem')\n" + '    at HTMLDocument.<anonymous> (https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js:148:28357)\n' + '    at u (https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js:2:24913)\n' + '    at m (https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js:2:25217)\n' + '    at i (https://homol.system.solides.com/pt-BR/crud/pesquisa:3:1403)\n' + '    at https://homol.system.solides.com/pt-BR/crud/pesquisa:3:1776 undefined', url: 'https://homol.system.solides.com/assets/application-248fc9609868fb919c0e57f033341bba986d8e0a71ccb197427f524986a0cb94.js' } +0ms
```

**Comment by ryanthemanuel** [comment] 2022-11-16 21:49
Hi @jaime1702. Thanks for logging this issue. When this problem occurs, do you see any errors in the developer tools console? Can you try using `cy.pause()` to pause your test when the toast should be displaying and see if the state of the DOM looks like you would expect?

**Comment by jaime1702** [comment] 2022-11-16 23:34
Good evening, I tried to get the element by debugging, but it doesn't show up, it's a very strange behavior, it doesn't show any kind of error, and visualizing the execution really doesn't show up, but when I dowgrade the version, the otast appears normally

**Comment by ryanthemanuel** [comment] 2022-11-22 03:03
Thanks @jaime1702. Is there a minimal test case that can reproduce this? Is the toast component something open source that can be utilized in a reproduction? Do the WiseLinks errors in your debug logs show up when things are working in 10.10.0?

**Comment by mjhenkes** [comment] 2022-11-30 22:02
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by mjhenkes** 2022-11-30 22:02 UTC

**Comment by vandrieiev-godaddy** [comment] 2023-07-24 14:10
have exactly the same issue in version 12.17.2

**Comment by nagash77** [comment] 2023-07-24 15:50
@vandrieiev-godaddy  In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.
