### ISSUE TITLE
Unable to delete videos before upload for test replay in Cypress 13

### ISSUE THREAD

**Issue by beccaonx** [cypress-io/cypress#27743] opened 2023-09-04 21:53 UTC
### Current behavior

On Cypress 13.1, with TestReplay on, our suite takes about 5:02. With replay off, it takes about 4:16. I would like to record some times without video getting uploaded to the cloud, as suggested in this section of the [cypress 13 announcement](https://www.cypress.io/blog/2023/08/29/announcing-cypress-13-test-replay/#what-test-replay-means-for-video-capture).
However, the recommended workaround (adding an after:spec action) did not prevent the videos from being uploaded to the cloud. Workaround: https://docs.cypress.io/guides/guides/screenshots-and-videos#Delete-videos-for-specs-without-failing-or-retried-tests.

### Desired behavior

There are a couple of possible desired behaviors here
Good- provide working sample code to prevent video upload
Better- very little performance difference between having Test Replay on and off

### Test code to reproduce
```js
setupNodeEvents(on, config) {
  on(
    'after:spec',
    (spec: Cypress.Spec, results: CypressCommandLine.RunResult) => {
      if (results && results.video) {
        // Do we have failures for any retry attempts?
        const failures = results.tests.some((test) =>
          test.attempts.some((attempt) => attempt.state === 'failed')
        )
        if (!failures) {
          // delete the video if the spec passed and no tests retried
          fs.unlinkSync(results.video)
        }
      }
    }
  )
}
```
### Cypress Version

13.1

### Node version

18.16.0

### Operating System

CircleCI

**Comment by jennifer-shehane** [comment] 2023-09-05 10:10
@beccagsc Can you provide the contents of your full config file? What is the output you are seeing in your terminal when this code is run?

The example provided should work. You can only have one ‘after:spec’ event handler in your config file.

**Comment by richardmward** [comment] 2023-09-11 09:26
> You can only have one ‘after:spec’ event handler in your config file.

Does this mean if a plugin uses that even handler, I can't use it myself?

**Comment by jennifer-shehane** [comment] 2023-10-05 01:53
Closing since no reproducible example is provided.

**Closed as completed by jennifer-shehane** 2023-10-05 01:53 UTC
Labels: Test Replay
