### ISSUE TITLE
Event based calendar is not rendered on Electron browser

### ISSUE THREAD

**Issue by prashantabellad** [cypress-io/cypress#3921] opened 2019-04-09 11:03 UTC
### Current behavior:
I am using event based calendar eg Full Calendar product. Based on non business days the calendar days render different colours. This is not  displayed or rendered on Electron browser. The same works on Chrome in non headless option.

Below is sample div element generated by the Full Calendar product which is rendered on chrome but not on electron
```html
<div class="fc-bgevent-skeleton"><table><tbody><tr><td colspan="5"></td><td class="fc-nonbusiness fc-bgevent" colspan="2"></td></tr></tbody></table></div>
```

### Desired behavior:

Since I am interested in headless execution I want event based Calendar's background color to work on electron. eg the sample div of Full Calendar product

### Steps to reproduce: (app code and test code)

Below is sample div element generated by the Full Calendar product which is rendered on chrome but not on electron
```html
<div class="fc-bgevent-skeleton"><table><tbody><tr><td colspan="5"></td><td class="fc-nonbusiness fc-bgevent" colspan="2"></td></tr></tbody></table></div>
```

### Versions

Cypress version - 3.2.0

**Comment by jennifer-shehane** [comment] 2019-04-24 06:17
This may be due to Electron running Chrome version 59, which will be upgraded in v4 of Cypress. 

Since I'm unfamiliar with the logic behind rendering this html and/or the colors, I can't say or reproduce without a fully reproducible example. Unfortunately we have to close this issue.
Please comment in this issue with a fully reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-24 06:17 UTC
