### ISSUE TITLE
`res.send(..)` without `statusCode` does not default to status: 200 in Electron

### ISSUE THREAD

**Issue by tgelu** [cypress-io/cypress#9325] opened 2020-11-25 08:40 UTC
### Current behavior
```
res.send({ body: someOtherData })
```
The above does what it is expected if I run it in Chrome or Firefox, but in Electron 87 the response which I get from `res.send({ body: someData })` contains the data but the status code is 404 instead of 200.

Everything works fine in all browsers if I explicitly specify the status code `res.send({ statusCode: 200, body: someData })`.

### Desired behavior
`res.send(...)` without `statusCode` specified should behave the same in all browsers.

### Test code to reproduce
```js
      cy.intercept('GET', '**/some/endpoint/*', (req) => {
        req.reply(res => {
          res.send({ body: someData })
        })
```

### Versions
6.0.0

**Comment by jennifer-shehane** [comment] 2020-11-25 09:29
I can recreate this issue with the following code. 

@tgelu What versions of Chrome/Firefox are you using? Because this failed reliably in all browsers for me. 

### Reproducible example

```js
it('test cy.intercept()', () => {
  cy.intercept('GET', 'url', (req) => {
    req.reply(res => {
      res.send({ body: { data: 'foo' } })
    })
  }).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/url')
    xhr.send()
  })
  cy.wait('@getUrl').its('response.statusCode').should('eq', 200)
})
```

The statusCode is 404

<img width="624" alt="Screen Shot 2020-11-25 at 3 52 09 PM" src="https://user-images.githubusercontent.com/1271364/100207633-32166500-2f36-11eb-8c18-9700ae7979b3.png">

### Workaround

Specifying the `statusCode` resolves the issue.

```js
it('test cy.intercept()', () => {
  cy.intercept('GET', 'url', (req) => {
    req.reply(res => {
      res.send({ statusCode: 200, body: { data: 'foo' } })
    })
  }).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/url')
    xhr.send()
  })
  cy.wait('@getUrl').its('response.statusCode').should('eq', 200)
})
```

<img width="645" alt="Screen Shot 2020-11-25 at 3 58 49 PM" src="https://user-images.githubusercontent.com/1271364/100208449-20818d00-2f37-11eb-8129-9fcaa1345d1c.png">

**Comment by flotwig** [comment] 2020-11-25 15:41
When you do `req.reply(res => { /* ... */ })`, the request is sent to the real server. Then, in the `res` callback, the real response is available and can be overwritten. But if you do not overwrite a property, then it will be unmodified.

So if the real response has a `404`, then `res.send` will send a `404`, unless you overwrite it by specifying a new `statusCode`.

This is mentioned in the docs:

> Continue the HTTP response, merging the supplied values with the real response.
> https://docs.cypress.io/api/commands/intercept.html#Modifying-an-incoming-response

So if you want to change the real response's status code from `404` to `200`, you'll need to specify it.

If you don't need the real response at all, you can just specify a StaticResponse:

```js
      // will send the default statusCode, 200
      cy.intercept('GET', '**/some/endpoint/*', { body: someData })
```

Closing since working as expected.

**Closed by flotwig** 2020-11-25 15:41 UTC
Labels: pkg/net-stubbing, stage: needs investigating, type: unexpected behavior, v6.0.0 :bug:

**Comment by tgelu** [comment] 2020-11-25 23:37
@flotwig I think you misunderstood my report. I was demonstrating how simply changing the browser from Firefox/Chrome to Electron resulted in a different behavior though of my tests or server remained the same. The only way to normalize that behavior was to overwrite the statusCode.

My server always responded with 404, but in Firefox/Chrome this turned magically into 200 when I overwrite the *only* body. This was not the case in Electron where the status remained 404.

It's not obvious to me why this is closed.

**Comment by jennifer-shehane** [comment] 2021-01-11 07:49
@tgelu Can you provide a fully reproducible example of the behavior being different in Electron versus Chrome/Firefox? Let me know what I need to modify in my example to see this behavior and we can reopen.

**Comment by tgelu** [comment] 2021-01-11 10:33
I retested this in my old code which caused the issue and I now notice that the problem I had was different than what I thought when I wrote this ticket. Your code also proves that.
I will try to find out if it is an actual bug, and if so submit a new issue.

Thank you for having looked at this :)
