### ISSUE TITLE
Cypress hangs on Google Maps JavaScript API v3.52

### ISSUE THREAD

**Issue by jsakas** [cypress-io/cypress#26615] opened 2023-04-28 04:38 UTC
### Current behavior

Our Cypress tests in three apps randomly began failing today. As soon as a call was made using the Google Maps JavaScript API, the runner would freeze up until it would fail the test on the next `cy` call that relied on the maps response being successful. 

We tracked it down to Google's latest Maps SDK release 3.53. Pinning the version to 3.52 resolves the issue.

That is really all the information I have at this point. I am not even sure if this is a Cypress issue or if it falls on Google, but this does not happen outside of Cypress. 

More info on versions: https://developers.google.com/maps/documentation/javascript/versions

Although I can't provide a reproduction right now, I figured I would open the issue and hopefully save others from the hours of debugging I just had to do.

```diff
  import { Loader } from "@googlemaps/js-api-loader"

  const loader = new Loader({
    apiKey: "YOUR_API_KEY",
-    version: "weekly",
+    version: "3.52",
  });
  
  loader.load()
```

Or more commonly:

```diff
- <script src="https://maps.googleapis.com/maps/api/js?v=weekly&key=%VITE_PLACES_API_KEY%&libraries=places"></script>
+ <script src="https://maps.googleapis.com/maps/api/js?v=3.52&key=%VITE_PLACES_API_KEY%&libraries=places"></script>
```

### Test code to reproduce

```
<script src="https://maps.googleapis.com/maps/api/js?v=weekly&key=%VITE_PLACES_API_KEY%&libraries=places"></script>
```

### Cypress Version

12.11.0

### Node version

18.16

### Operating System

macOS

**Comment by higginsddh** [comment] 2023-04-28 15:59
@jsakas Thank you so much for finding this! I spent most of yesterday debugging our tests and I came up empty.

**Comment by jfarris587** [comment] 2023-04-28 20:09
@jsakas experiencing the same too. 

spent too much time trying to figure this out 😮‍💨 so thank you for saving us from debugging endlessly

**Comment by mschile** [comment] 2023-04-28 21:12
Hi @jsakas 👋, thanks for logging this issue. Does anyone have a reproduction I can use to investigate? Would someone be able to recreate the issue by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by other means?

**Comment by jsakas** [comment] 2023-04-28 22:03
@mschile I tried to create the reproduction but it's not happening in the small app: https://github.com/jsakas/cypress-issue-26615 (you will need your own places API key inside of a `.env` file. )

`echo VITE_PLACES_API_KEY=xxxxxx_your_key > .env`

Not entirely sure what is going on with our production application and the others who are posting. Perhaps it's even unrelated to Cypress and the result of another dependency we all share. It's hard to make the distinction due to the size of our dependency list.

If you decide to close the issue, at least the historical record is here and maybe another person will have more clarity into the exact cause of the freezing of Cypress.

**Comment by mschile** [comment] 2023-04-28 23:11
Thanks for trying @jsakas. I'm going to leave the issue open for now in case someone is able to provide a reproduction.

You could try printing the [DEBUG logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) to see if that provides anything useful.

**Comment by andrewbeckman** [comment] 2023-05-03 02:02
We ran into this as well! Thank you so much @jsakas!

**Comment by higginsddh** [comment] 2023-05-08 15:00
@mschile After running the tests with DEBUG logs, I noticed the following entries that happen when using the latest version of Google Maps but not when reverting back to 3.5.2. This happens at the same time the tests seem to hang. I can post the full DEBUG logs as well if that's helpful.

Thank you for your help!

```
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61552 } +3s
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61551 } +46ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61568 } +1s
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61581 } +220ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61582 } +29ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61591 } +454ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61596 } +203ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 61619 } +2s
```

**Comment by chrisbreiding** [comment] 2023-05-15 13:01
> I tried to create the reproduction but it's not happening in the small app

@jsakas I wonder if the issue only occurs if there are multiple tests in a spec or multiple different spec files. For your project where this issue is happening, how many spec files are in your project and how many tests are in the spec file where this issue occurs? Also, does this happen in every browser or only a particular browser?

**Comment by higginsddh** [comment] 2023-05-19 15:36
@chrisbreiding  - For my scenario, this is happening with spec files mostly containing a single test per file. There are a total of 13 spec files in the project.  Were the log entries from https://github.com/cypress-io/cypress/issues/26615#issuecomment-1538504189 helpful? I can also send you the entire log files for both with the new version of Google Maps were the tests hang and the same tests run with the old version of Google Maps where they run correctly.

**Comment by chrisbreiding** [comment] 2023-05-22 13:53
@higginsddh Thanks for the information! Having the entirety of the log files would be helpful. Of course the most useful thing would be a minimal reproduction that we can run ourselves to debug this.

**Comment by higginsddh** [comment] 2023-05-22 17:04
@chrisbreiding - I'll keep work on getting a minimal repo going but in the meantime will send you logs. Is there a way to email them to you? I think I removed anything sensitive but just in case, would prefer to not post them in a public spot.

**Comment by chrisbreiding** [comment] 2023-05-22 17:34
@higginsddh You can send them to `chris [at] cypress [dot] io`. Thanks!

**Comment by higginsddh** [comment] 2023-05-22 18:13
@chrisbreiding  Email sent!

**Comment by AtofStryker** [comment] 2023-05-23 19:11
@higginsddh I'm taking a look at the debug logs but there is nothing that stands out as a possible issue. Once the small repro is ready I can take a look. My guess is the problem lives in the browser and isn't surfaced by the debug logs.

**Comment by higginsddh** [comment] 2023-05-23 19:22
@AtofStryker Were the log lines posted in https://github.com/cypress-io/cypress/issues/26615#issuecomment-1538504189 not looking relevant? Those happened at the same time the tests hung and the delays are pretty significant (+3s, +1s, +2s) all on "socket_allowed allowed socket closed, removing { localPart: ... }". They don't seem to appear in the log file for the successful test run.

**Comment by AtofStryker** [comment] 2023-05-23 20:02
> @AtofStryker Were the log lines posted in [#26615 (comment)](https://github.com/cypress-io/cypress/issues/26615#issuecomment-1538504189) not looking relevant? Those happened at the same time the tests hung and the delays are pretty significant (+3s, +1s, +2s) all on "socket_allowed allowed socket closed, removing { localPart: ... }". They don't seem to appear in the log file for the successful test run.

It could be related or a side effect, but I don't think its the cause. When tests fail / finish we need to clean up those upstream sockets in the server state to prevent hanging onto stale state. Something might be forcing the socket to close prematurely, but it's hard to infer.

**Comment by higginsddh** [comment] 2023-05-27 16:24
@AtofStryker I'm still trying to get a small repro available but it's been a challenge. One thing I did notice is when profiling using Chrome, the call stack is full of @testing-library calls (specifically printer, printCOmplexValue and printObjectProperties) and if I remove the @testing-library findBy* methods, it seems to resolve the problem. I'm going to keep investigating and possibly file an issue with them if that seems to be the cause.

**Comment by higginsddh** [comment] 2023-05-27 16:36
Appears it's already filed with @testing-library [here](https://github.com/testing-library/cypress-testing-library/issues/241#issuecomment-1532450790). I used the posted workaround of updating getElementError in testing-library and it resolved the problem.

**Comment by AtofStryker** [comment] 2023-05-30 14:36
@higginsddh it sounds like this is indeed an issue with [cypress-testing-library](https://github.com/testing-library/cypress-testing-library/issues/241). I think we can go ahead and close this issue as the fix would need to occur in cypress-testing-library. Further conversation on this issue should also happen there.

**Closed as completed by AtofStryker** 2023-05-30 14:36 UTC
Labels: existing workaround
