### ISSUE TITLE
Negative Blacklist (ie a whitelist)

### ISSUE THREAD

**Issue by tomardern** [cypress-io/cypress#4344] opened 2019-05-30 12:30 UTC
### Current behavior:
Currently, you can provide a "blacklist" of hosts.

### Desired behavior:
it would be nice to only have a "whitelist" (or a negative blacklist), for example, we would want to block everything except `*.example.com` or `*.foo.com`

**Comment by flotwig** [comment] 2019-05-30 12:37
Duplicate of #1443

**Closed by flotwig** 2019-05-30 12:37 UTC
