### ISSUE TITLE
GitHub Actions ( Cypress Runs) || Getting "Run finished" immediately when "Run Starts"

### ISSUE THREAD

**Issue by RemaKoul** [cypress-io/cypress#25494] opened 2023-01-18 07:55 UTC
### Current behavior

As soon as the  Run starts through pipeline   , it finishes without actually initiating the test execution
![image](https://user-images.githubusercontent.com/21169655/213118751-d9581df9-e349-40ff-826b-5f8d76b313ef.png)

### Desired behavior

GitHub action should initiate test execution and run it completely without any deviations

### Test code to reproduce

Workflow ;

jobs:
  cypress-CrossBrowser-testing:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run tests
        uses: cypress-io/github-action@v5
        timeout-minutes: 50
        with:
          # Run on all Chrome browser
          browser: chrome
          parallel: true
          record: true
          

### Cypress Version

12.3.0

### Node version

 v16.13.0 

### Operating System

Windows 10

### Other

Found an existing bug With Cypress : https://github.com/cypress-io/github-action/issues/147
This seems to have been fixed in v2.2 
I am already using v5

**Comment by RemaKoul** [comment] 2023-01-19 10:27
Any updates ?

**Comment by nagash77** [comment] 2023-01-19 15:42
Hi @RemaKoul , Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marktnoonan** [comment] 2023-02-20 21:26
I'm going to close this due to inactivity, please comment with more details if this is still a problem for you.

**Closed as completed by marktnoonan** 2023-02-20 21:26 UTC
