### ISSUE TITLE
Configuration to change the speed of test

### ISSUE THREAD

**Issue by andrew-vandenbrink** [cypress-io/cypress#2090] opened 2018-07-03 09:26 UTC
### Current behavior:

Test run very fast, if we want to have a delay between test steps, we need to put cy.wait manually in the code

### Desired behavior:

There must be configuration to change the speed of test

**Comment by Bkucera** [comment] 2018-07-03 11:05
Hi @andrew-vandenbrink, this seems to be a duplicate of #249

**Closed** 2018-07-03 11:05 UTC
