### ISSUE TITLE
Timed out waiting for the browser to connect.

### ISSUE THREAD

**Issue by ctorresDespegar** [cypress-io/cypress#7040] opened 2020-04-16 16:14 UTC
**Cypress:    4.4.0                                                                              │
Browser:    Electron 80 
Node: v11.6.0
npm: 6.14.4
SO: macOS Catalina v 10.15.2**

 When use cypress run the first spec is running well, the all others spec are showing 
**Timed out waiting for the browser to connect. Retrying...
Timed out waiting for the browser to connect. Retrying again...**

![image](https://user-images.githubusercontent.com/29870571/79479738-9ad25200-7fe3-11ea-91a4-6d217137f0c6.png)

**Comment by jennifer-shehane** [comment] 2020-04-17 10:48
Duplicate of #3310

**Closed by jennifer-shehane** 2020-04-17 10:48 UTC
