### ISSUE TITLE
Got the TypeError: Illegal invocation when getting the locator 

### ISSUE THREAD

**Issue by sangmai** [cypress-io/cypress#5774] opened 2019-11-22 09:00 UTC
### Current behavior:

Cypress got the issue when getting the normal locator. It throws the exception TypeError: Illegal invocation in version 3.6.1

### Desired behavior:

Can get the locator properly 

### Versions

3.6.1

**Comment by gabbersepp** [comment] 2019-11-25 15:10
Unfortunately my glass sphere is broken currently. I will try to buy a new one.

**Comment by jennifer-shehane** [comment] 2020-02-12 09:06
Closing as there is not reproducible example provided. Duplicate of #6412 though likely.

**Closed by jennifer-shehane** 2020-02-12 09:06 UTC
