### ISSUE TITLE
Cypressio passing tests in browser with green tick, but tests are not actually finishing

### ISSUE THREAD

**Issue by lucidity-joe** [cypress-io/cypress#8640] opened 2020-09-22 09:52 UTC
### Current behaviour:

Despite the green tick and seeming 'pass' state:
<img width="549" alt="Screenshot 2020-09-22 at 10 43 41" src="https://user-images.githubusercontent.com/68896248/93867379-dffc5d80-fcc0-11ea-86e3-54f40ea58594.png">

Test stops very early without completing all steps and does not surface any error or traceback:
<img width="595" alt="Screenshot 2020-09-22 at 10 43 53" src="https://user-images.githubusercontent.com/68896248/93867386-e1c62100-fcc0-11ea-8876-22d414f9632a.png">

### Desired behaviour:

If my tests fails I would like to be informed of that and the frontend of cypress should give it a red X

### Test code to reproduce

My code involves logging in to a private website, and I cannot provide it. Genuinely curious as to what I am supposed to do here? I need support/advice but there seems to be no reasonable way to gain it without compromising my code.

### Versions

macOS Mojave. Chrome, latest; Cypress, latest

**Comment by Bkucera** [comment] 2020-09-22 15:00
> My code involves logging in to a private website, and I cannot provide it. Genuinely curious as to what I am supposed to do here? I need support/advice but there seems to be no reasonable way to gain it without compromising my code

Good question. What we recommend is trying to reproduce the problem in a different context that you can then supply to us as a reproducible. Either a code snippet that visits a public website that demonstrates the problem, or better a repository with a demo server. 

Otherwise we are even further from the source of the problem than you are, and we don't have much to work off of. We will have to close this issue unless a repro is supplied. Thanks

**Comment by bahmutov** [comment] 2020-09-22 19:06
@lucidity-joe I suggest you also start commenting test code and support code to see where the problem is coming from. Maybe it is a custom command? Or an error handler? Or some async assertions? Read this blog post that describes a similar situation for example https://www.cypress.io/blog/2020/01/16/when-can-the-test-stop/

**Comment by jennifer-shehane** [comment] 2020-09-29 05:38
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-09-29 05:38 UTC
Labels: stage: needs information

**Comment by lucidity-joe** [comment] 2020-09-30 10:21
This is happening almost 50% of the time with no traceback or anything, which is pretty much the entire problem in a nutshell.  I don't have a reproducible example because there is no discernible reason why this does or doesn't happen, but it is happening so regularly I'm wondering if you can at least point me towards examples you must have of other people with this issue please?

**Comment by lucidity-joe** [comment] 2020-09-30 10:23
Here's a recent test not even getting past type a username in on my login page: 
<img width="492" alt="Screenshot 2020-09-30 at 11 22 28" src="https://user-images.githubusercontent.com/68896248/94673919-5aeff480-030f-11eb-99b1-c0e4410608f9.png">

It's incredibly frustrating that there is not an affective way to describe this problem, but it is very pervasive

**Comment by Bkucera** [comment] 2020-10-06 15:58
@lucidity-joe most likely it's a dangling promise or some race condition in your spec code. However if you can't show us the spec code there is nothing we can do. The command log screenshots you are posting are not enough to even speculate what your problem may be.
