### ISSUE TITLE
Intercept still making a request to the server

### ISSUE THREAD

**Issue by Evaske** [cypress-io/cypress#27325] opened 2023-07-18 15:05 UTC
### Current behavior

When using `cy.intercept()` a request is still being made to the live server instead of it actually being intercepted and sending a response. 

### Desired behavior

Not make a call to the live server and just simulate the call and return the provided data

### Test code to reproduce

```
beforeEach(() => {
      cy.visit("/couple/onboarding");
      cy.get('input[name="firstName"]').type("FirstName");

      cy.get('input[name="partnerFirstName"]').type("partnerFirstName");

      cy.contains("button", "Next", { matchCase: false }).click();
    });

it("should allow an account to be created", () => {
      cy.intercept(
        {
          method: "POST",
          url: "https://domain.com/auth/signup",
        },
        ({
          body: {
            data: {
              member: {
                id: "member_id",
              },
              tokens: {
                accessToken: "access-token",
              },
            },
          },
        })
      ).as("createAccount");
```

I can still see in the Chrome developer tools a server call being made to /auth/signup and also a user being created in the database. 

### Cypress Version

12.11.0

### Node version

20.4.0

### Operating System

macOS and Linux

**Comment by mike-plummer** [comment] 2023-07-18 17:10
@Evaske Two observations here:
1. Seeing the request in the browser's devtools is expected behavior. From the [`cy.intercept` docs](https://docs.cypress.io/api/commands/intercept):

> The request modification cannot be verified by inspecting the browser's network traffic (for example, in Chrome DevTools), since the browser logs network traffic before Cypress can intercept it.

All requests are proxied from the frontend thru Cypress then on to their destination, so they will appear to be "made" when looking at the browser's devtools

2. The request proceeding on to your backend is most likely caused by a `routeMatcher` mismatch (most often a URL mismatch) - the url and method must match *exactly* unless you're using wildcards. A good first troubleshooting step would be to use one or more wildcards in place of the domain/query params portions of the URL. You can also use the `routeHandler` argument pattern to verify whether your interceptor is actually firing by adding some logging statements.

There is a [good resource](https://glebbahmutov.com/blog/cypress-intercept-problems/) linked from [our docs](https://docs.cypress.io/api/commands/intercept#See-also) with lots of troubleshooting steps to take with `cy.intercept` - you may want to review this. If you aren't able to resolve your usage with that resource then a good followon would be to reach out to the [Cypress Community](https://on.cypress.io/discord) for help.

At this time your issue appears to be a problem with usage rather than a true bug in Cypress, so I am going to close this. If you are able to verify this is a true bug in Cypress and can provide a *full, reproducible example* please link it here and we'd be happy to reopen and investigate.

**Closed as not planned by mike-plummer** 2023-07-18 17:10 UTC
