### ISSUE TITLE
AfterEach() -> Logout() is not running after each test

### ISSUE THREAD

**Issue by swaroopa-mooda** [cypress-io/cypress#17745] opened 2021-08-16 13:15 UTC
### Current behavior

Hello,

I have added my logout functionality in afterEach(). I want this code to run even the test fails, but this is not currently executing. Can you please help? 

Many thanks
Swaroopa

### Desired behavior

After each test run my application should logout and the next test should start from login screen

### Test code to reproduce
```js
afterEach(() => {
  cy.visit("/")
  try {
    cy.get("body").then(body => {
      if (body.find("[data-test-id=log-out-button]").length > 0) {
        cy.get("[data-test-id=log-out-button]").then(logoutButton => {
          if (logoutButton.is(":visible")) {
            cy.get("[data-test-id=log-out-button]").click()
          }
        })
      }
    })
  } catch (e) {
    // do nothing - no testSubject was created
  }
})
```
### Cypress Version

8.0.0

**Comment by jennifer-shehane** [comment] 2021-08-16 17:12
I imagine this is a duplicate of this issue - https://github.com/cypress-io/cypress/issues/2831 Click commands don't work in `afterEach` commands if the test failed. This is a bug.

**Closed by jennifer-shehane** 2021-08-16 17:12 UTC
