### ISSUE TITLE
Watch mode doens't continue when window looses focus

### ISSUE THREAD

**Issue by Chrischaaan** [cypress-io/cypress#28928] opened 2024-02-13 06:37 UTC
### Current behavior

Since Update to Cypress 13:

- Run Tests in watch mode
- Select Test file
- Tests start running
- click to VsCode or anywhere else (cypress test window looses focus)
- Tests stop running

### Desired behavior

Tests should continue running, like they did in Version 12

### Test code to reproduce

[All Tests are failing with this, this is not specified for one test!](https://github.com/cypress-io/cypress-test-tiny)

### Cypress Version

13.6.4

### Node version

20.11.0

### Operating System

Windows 10 Enterprise 22H2, Windows Feature Experience Pack 1000.19053.1000.0

**Comment by jennifer-shehane** [comment] 2024-02-13 17:01
Duplicate of https://github.com/cypress-io/cypress/issues/28392 We're working on fixing this currently. 

You can follow instructions here to get around this issue: https://github.com/cypress-io/cypress/issues/28392#issuecomment-1852735772

**Closed as not planned by jennifer-shehane** 2024-02-13 17:01 UTC
