### ISSUE TITLE
cy.route2: body is not in the yielded request object

### ISSUE THREAD

**Issue by warpdesign** [cypress-io/cypress#8914] opened 2020-10-21 17:02 UTC
### Current behavior

When inspecting the `request` prop of a route with cy.route2, the `body` is not in the request object.

### Desired behavior

The body should be there (so that what's mentioned in the cy.route2's [documentation](https://docs.cypress.io/api/commands/route2.html#Waiting-on-a-request) is possible).

### Test code to reproduce

I have created a small example here: https://github.com/warpdesign/cypress-route2-repro

1. run `npm install`
2. run `npm run cypress:open`
3. click on the spec file
4. open the console so that the debugger stops the js execution
5. check the request parameter and notice that there is no `body` property

![image](https://user-images.githubusercontent.com/199648/96754025-fd603c80-13d0-11eb-80e9-996f3a7c5435.png)

### Versions

Cypress 5.3.0
macOS 10.15.6
Chrome 86

**Comment by jennifer-shehane** [comment] 2020-10-22 06:51
Yes, I can also see that the `request.body` doesn't seem to exist in the example provided.

```js
it('works', () => {
  cy.route2({
    method: 'POST',
    url: 'https://warpdesign.fr/tests/cypress/index.html'
  }).as('postWarp')

  cy.visit('https://www.wikipedia.org/')

  cy.window().then((win) => {
    win.fetch('https://warpdesign.fr/tests/cypress/index.html', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        message: 'hey!'
      })
    })
  })

  cy.wait('@postWarp').then((req) => {
    expect(req.request.body).to.exist // fails
  })
})
```

<img width="954" alt="Screen Shot 2020-10-22 at 1 19 31 PM" src="https://user-images.githubusercontent.com/1271364/96835216-4c59b080-1469-11eb-9858-5d7a75ac8a2b.png">

**Comment by flotwig** [comment] 2020-10-22 13:54
This is a duplicate of https://github.com/cypress-io/cypress/issues/8695, it will be fixed in the next release.

**Closed by flotwig** 2020-10-22 13:54 UTC
Labels: experiment: network stubbing, pkg/net-stubbing, stage: needs investigating, type: unexpected behavior
