### ISSUE TITLE
Crashing on test start with TypeError: Cannot read property 'objectMode' of undefined

### ISSUE THREAD

**Issue by RomainGoncalves** [cypress-io/cypress#5786] opened 2019-11-25 11:15 UTC
### Current behavior:
Since updating to 3.6.1, when launching a test file (or all), Cypress stops the execution and shows me the following message:

<img width="752" alt="Screenshot 2019-11-25 at 12 12 09" src="https://user-images.githubusercontent.com/1366477/69535826-035d5b80-0f7d-11ea-9642-d506c68de190.png">

Upong clicking Try Again, the list of test file appears again. Click any file launches the browser window, then closes it, and the message above appears again.

### Desired behavior:
The tests to run :D

### Steps to reproduce: (app code and test code)
As it mentions the plugins, here's my `plugins/index.js` file content:

```javascript
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
};

const browserify = require('@cypress/browserify-preprocessor');

module.exports = (on) => {
  const options = browserify.defaultOptions;
  const envPreset = options.browserifyOptions.transform[1][1].presets[0];
  options.browserifyOptions.transform[1][1].presets[0] = [envPreset, { ignoreBrowserslistConfig: true }];

  on('file:preprocessor', browserify(options));
};

```

### Versions
3.6.1

Thanks for any help.

**Comment by swapnasundarbiswal** [comment] 2019-11-27 11:47
Any help on this ?

**Comment by xeger** [comment] 2019-12-06 18:29
This is happening to me, too across a wide range of projects and Cypress configurations.

**Comment by poponuts** [comment] 2020-01-09 03:36
I have same problem. It seems like the child nodes in the JSON are not being accepted.
**This works:**
```
{
"parent": "hello"
} 
```

**This does not work:**
```
{
"parent": "hello",
"parent2": {
 "child": "hello child"
} 
```

**Comment by TomCaserta** [comment] 2020-03-04 22:55
Took a while but managed to figure out how to fix it but not exactly certain what is wrong - all attempts to debug this issue failed for me, I could never find the real source of the error...

That being said I recently updated my projects 'fs-extra' package to > `8.0.0`. I noticed the `@cypress/browserify-preprocessor` package uses `fs-extra` to create a writable stream. I downgraded the 'fs-extra' package and everything now works without problems.

**Comment by xeger** [comment] 2020-03-05 03:40
Interesting! My problem went away too, once I fixed a yarn issue that was causing multiple versions of cypress to be concurrently installed in `node_modules` (I hate yarn for this behavior, but that's another story.) I'd noticed that the multiple cypresses was causing multiple `fs-extra` versions to enter node_modules, and hypothesized it was an interface incompatibility between versions of `fs-extra` or something called `stream-writable`.

Your experience indicates the issue is simpler than that, and there is a major-version issue between `fs-extra` and `stream-writable` and/or `cypress` and `fs-extra`. Hopefully this info will lead the Cypress team to find a more robust semver constraint to guard us hapless souls from npm version hell, which it seems is still a thing after all these years.

**Comment by jennifer-shehane** [comment] 2020-07-14 09:58
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-14 09:58 UTC
