### ISSUE TITLE
Cypress ESOCKET time out in Bitbuket CI 

### ISSUE THREAD

**Issue by MehranShafqat** [cypress-io/cypress#6547] opened 2020-02-25 06:49 UTC
### Current behavior:

Well Im facing huge issue in bitbucket CI almost every run `cy.visit` time out well there is no issue with Internet or our server everything up and running but some how cypress always falling in CI run not able to do `cy.visit`.  If I execute and run the tests locally all working fine.

```
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: ESOCKETTIMEDOUT
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
The stack trace for this error is:
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/root/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:680:40)
    at Object.onceWrapper (events.js:291:20)
    at TLSSocket.emit (events.js:203:13)
    at TLSSocket.Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**My pipeline is very simple**
```yml
- step:
  name: Build and test
  image: cypress / base: 10
  script:
  - npm install
    - npx cypress run
  artifacts:
  - cypress / videos/**
```

### Versions

v 4.0.2

**Comment by MehranShafqat** [comment] 2020-02-25 07:38
Now more problem getting  same error even im executing the tests on local machine after 4 to 5 tests 6th test through the same error on cy.visit

**Comment by otalandim** [comment] 2020-04-17 20:42
@MehranShafqat any news?

**Comment by iamdaniyalz** [comment] 2020-07-03 11:17
Any update on this would be helpful for users like me who encountered the same issue.

**Comment by jennifer-shehane** [comment] 2020-07-27 11:52
Duplicate of #7062

**Closed by jennifer-shehane** 2020-07-27 11:52 UTC
