### ISSUE TITLE
Running Cypress through TeamCity fails the test in the Before hook

### ISSUE THREAD

**Issue by nimmala89** [cypress-io/cypress#8294] opened 2020-08-17 01:29 UTC
### Current behavior:

I'm trying to run cypress tests on Teamcity CI/CD. I have a Before() hook which does the login into the application and stores the cookies of the session for each subsequent test to use. For some reason when i run locally, this works pretty much fine. But when I try to run it on Teamcity , the tests fail abruptly. From what I investigated, they fail at the step of logging in (i.e in the Before() hook). Has anyone else faced the same issue ?

```
 AssertionError: Timed out retrying: Expected to find element: `.btn.btn.btn-primary> span`, but never found it.
[20:24:49][Step 2/2]       
  at Context.eval (https://dev5.finalphasesystems.com/__cypress/tests?p=cypress\support\index.js:94:6)
```

This particularly happens when the test has not logged in and is failing to find the above button.
### Desired behavior:

The tests should run without failing.

### Test code to reproduce

Code in the script of `package.json` file
```
cypress run --parallel --config baseUrl=https://abcd.com --record --key xxxxxxxxxxxxxxxxxx --reporter mocha-teamcity-reporter --ci-build-id ${BUILD_NUMBER}
```

### Versions

OS version Windows 10
Cypress Version 4.12.1

**Comment by nimmala89** [comment] 2020-08-17 04:26
https://github.com/cypress-io/cypress/issues/7424 - This seems to be the issue.

**Comment by jennifer-shehane** [comment] 2020-08-17 05:15
Duplicate of #7424

**Closed by jennifer-shehane** 2020-08-17 05:15 UTC
