### ISSUE TITLE
.type with form submission using {enter} behaves incorrectly

### ISSUE THREAD

**Issue by basslagter** [cypress-io/cypress#2326] opened 2018-08-13 08:40 UTC
Just updated to 3.0.3
I have a test that looks like:

```
cy
      .find('input[type="search"]')
      .type('water{enter}')
```

In the form containing the input I also have a clear button and a submit button. This looks like:

```
<form>
   <input type="search"/>
   <button type="button">Empty</button>
   <button type="submit">Search</button>
</form>
```

Before, the form was submitted because of the {enter}. Since 3.0.3 the empty button is 'clicked' instead.

**Comment by basslagter** [comment] 2018-08-13 08:59
Investigated somewhat further and not sure if my statement is correct.

**Comment by brian-mann** [comment] 2018-08-13 11:04
Duplicate of https://github.com/cypress-io/cypress/issues/2261. This has been fixed and merged via PR https://github.com/cypress-io/cypress/pull/2278 and its about to be released.

**Closed by brian-mann** 2018-08-13 11:04 UTC
