### ISSUE TITLE
Cypress dashboard not receiving results from Azure or local machine on Cypress v9.1.0

### ISSUE THREAD

**Issue by Fairbuj987** [cypress-io/cypress#19093] opened 2021-11-24 16:57 UTC
### Current behavior

Since upgrading to Cypress v9.1.0 my integration between Azure and Cypress dashboard has not been working correctly.
The tests show as started but never receive any indication that the test has completed and just hang.

I've tested this directly from Azure pipeline and received the issue

I also ran the same set of tests locally against the same environment with cypress versions
8.6.0 tests passed and results displayed correctly in dashboard
9.0.0 tests passed and results displayed correctly in dashboard
9.1.0 tests passed and results not displayed correctly in dashboard - results show as pending and then time out

### Desired behavior

Results to be uploaded into the cypress dashboard for the most recent version of cypress

### Test code to reproduce

npx  cypress run --browser chrome --spec "cypress/integration/path/to/folderWithMultipleSpecFiles/*.js" --record --key [my-key-to-cypress-dashboard]

### Cypress Version

9.1.0

### Other

Other people are claiming to be experiencing the same issue in https://gitter.im/cypress-io/cypress#

**Comment by emilyrohrbough** [comment] 2021-11-24 18:59
Duplicate of https://github.com/cypress-io/cypress/issues/19087. Going to close this issue in favor of 19087. Please add any relevant information there.

**Closed by emilyrohrbough** 2021-11-24 18:59 UTC
