### ISSUE TITLE
open command has doesn't display anything in Windows 10

### ISSUE THREAD

**Issue by farzadmf** [cypress-io/cypress#2760] opened 2018-11-12 04:53 UTC
Hi, I recently learned about Cypress, and I wanted to play with it, but unfortunately, I'm stuck at the very beginning step: I cannot start it!

I'm using Windows, and I've tried running it using the locally installed package in my project or as a global Node module.

### Current behavior:

When I run `cypress open` in my terminal, nothing happens, it seems that something is happening in the background, but I don't see any window appear. If I directly find `Cypress.exe` and click on it, a window appears, but not using the `open` command.

I've tried `cache clear` and then `cypress install`, but the behavior is still the same!

### Desired behavior:

I should be able to see something. Am I missing something here?

### Steps to reproduce:

1. Install globally: `yarn global add cypress`
2. Run the `install` command: `cypress install`
3. Run the `open` command: `cypress open`

### Versions

Windows 10 1809 64bit
Cypress 3.1.1
Chrome 70

**Comment by lchenay** [comment] 2018-11-12 09:50
Regression on node 11, related to https://github.com/nodejs/node/pull/21316
Duplicate of https://github.com/cypress-io/cypress/issues/2667

**Closed** 2018-11-13 16:54 UTC
Labels: type: duplicate
