### ISSUE TITLE
Video recording of tests is not functioning when running on Jenkins Nodes

### ISSUE THREAD

**Issue by edaldridge** [cypress-io/cypress#15876] opened 2021-04-08 13:59 UTC
Hi

I'm finding with the videos recorded of test runs from our two Jenkins nodes that they are freezing part way through the recording so aren't able to be used to debug.  Not sure if this is related to the upgrade to 7.0 but older videos are working ok.   When running the same tests locally the video is recorded fine.

Jenkins nodes are running Ubuntu server

Has any other instance like this been reported at all?

Sample video attached

Thanks
Ed

https://user-images.githubusercontent.com/67149573/114039946-11163700-987b-11eb-9d53-1f0bbcab1749.mp4

**Comment by GeoFro** [comment] 2021-04-08 15:06
Experiencing same as above.^
Video shows loading screen up until the last seconds of the test.

**Comment by bukharov** [comment] 2021-04-08 16:04
we have the same issue, however test suddenly appears in the last second:

https://user-images.githubusercontent.com/49371/114059484-698d0a80-9862-11eb-99cc-4f3e27b94787.mp4

**Comment by edaldridge** [comment] 2021-04-12 15:16
> we have the same issue, however the test suddenly appears in the last second:
> 
>  cypress-video18c4f84c-e126-47f0-99c8-5a64ebc4cfa7.mp4 
> we're running on AWS CodeBuild, so possibly it's not related to Jenkins
> another thing to mention is that i suspect it's related to the `parallel` flag, because videos for the same set of tests looked fine when run on one machine
> 
> Cypress version: `7.0.1`

I'm currently not running using the 'parallel' flag so, for me at least, it's not related.  

I suspect the resources available on the nodes aren't enough to support the generation of the videos but it would be nice to get some confirmation from other people who are experiencing the same thing

**Comment by FilipSwiatczak** [comment] 2021-04-14 12:01
We are running v7.0.1 from Jenkins as well and uploaded videos start with 5 sec of correct video then have about 1 frame per minute. 
OS: Linux Debian 10.8
CI: Jenkins, aws ecs instances
Cypress v: 7.0.1
worker spec: 4 Parallel workers with 2048 CPU Units / 6144 Mb RAM each

Further, video compression is throwing :
![image](https://user-images.githubusercontent.com/30108240/114706267-a81e3b80-9d20-11eb-9a8c-320d65ada720.png)
 OR:
![image](https://user-images.githubusercontent.com/30108240/114706360-c2f0b000-9d20-11eb-9408-d849d0093710.png)

When that happens it disconnects the cloud runner which is stuck "in progress"
Disabling video compression fixed the hanging but uploaded video still has just a few frames. 

This works correctly on previous v6.5.0

**Comment by bukharov** [comment] 2021-04-16 15:50
> > we have the same issue, however the test suddenly appears in the last second:
> > cypress-video18c4f84c-e126-47f0-99c8-5a64ebc4cfa7.mp4
> > we're running on AWS CodeBuild, so possibly it's not related to Jenkins
> > another thing to mention is that i suspect it's related to the `parallel` flag, because videos for the same set of tests looked fine when run on one machine
> > Cypress version: `7.0.1`
> 
> I'm currently not running using the 'parallel' flag so, for me at least, it's not related.
> 
> I suspect the resources available on the nodes aren't enough to support the generation of the videos but it would be nice to get some confirmation from other people who are experiencing the same thing

I can confirm that it has nothing to do with the `parallel` flag. It also seems to be randomly affecting some videos as some are fine. Checked with `7.1.0` - the issue is still there.

**Comment by jennifer-shehane** [comment] 2021-04-26 20:26
There are some performance issues introduced in recent versions of Cypress, please see those issues for relevant updates. We're working on them.

- https://github.com/cypress-io/cypress/issues/15853
- https://github.com/cypress-io/cypress/issues/15779
- https://github.com/cypress-io/cypress/issues/16152
- https://github.com/cypress-io/cypress/issues/15973
- https://github.com/cypress-io/cypress/issues/15990

If you are running Cypress in a headless browser, please try reducing the screen size to the default size prior to 7.0 (1280x720) to see if the new issues are related to the increase in screen size. [Instructions here.](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless) 

If that doesn't resolve the issue, I suggest downgrading to the last known version of Cypress that worked well.

We'll be closing this issue as there are no reproducible actions. For now we need to focus on the performance issues where we're given clear reproducible examples.

**Closed by jennifer-shehane** 2021-04-26 20:26 UTC
Labels: CI: jenkins
