### ISSUE TITLE
GitHub Actions ( Cypress Runs) || Getting "Run finished" immediately when "Run Starts"

### ISSUE THREAD

**Issue by janavi-p** [cypress-io/cypress#29811] opened 2024-07-08 13:38 UTC
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/132589418/adf3655e-1ecc-40f6-9ced-439015d4095e)

### Desired behavior

GitHub action should initiate test execution and run it completely without any deviations

### Test code to reproduce
```yml
jobs:
  cypress-run:
    name: 'Cypress Test on Ubuntu'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1] # Uses 1 parallel instance
        
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: 'git branch info'
        run: | 
          git branch

      - name: 'Building web application to be tested'
        run: yarn
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          config-file: cypress.config.js
          spec: "cypress/e2e/specs/regression-specs/staging/**/*.cy.js"
          group: 'UI-Electron'
          record: true
          parallel: true
        
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
### Cypress Version

13.13.0

### Node version

v20.13.1

### Operating System

macOS 14.5

### Other

Found an existing bug With Cypress : https://github.com/cypress-io/github-action/issues/147
This seems to have been fixed in v2.2
I am already using v6

**Comment by janavi-p** [comment] 2024-07-08 14:13
Note: The spec files run seamlessly when I re-run the same job. It fails via manual run, scheduled job and via automatically.

**Comment by MikeMcC399** [comment] 2024-07-08 14:17
- This is a duplicate of https://github.com/cypress-io/cypress/issues/29722

**Comment by jennifer-shehane** [comment] 2024-07-08 15:31
Typically there will be output of the 'Run finished' prematurely without running the tests if Cypress detects a ciBuildId that has already completed running - this means it's associated with another older run. 

Ensure that the ciBuildId is unique for the run in order to trigger a new run in Cypress. https://docs.cypress.io/guides/cloud/smart-orchestration/parallelization#Linking-CI-machines-for-parallelization-or-grouping

**Comment by MikeMcC399** [comment] 2024-07-23 06:51
- According to the duplicate issue https://github.com/cypress-io/cypress/issues/29722 the workflow is now running, so this issue should be closed.

**Closed as completed** 2024-08-09 15:05 UTC
Labels: stage: awaiting response
