### ISSUE TITLE
Using .should('not.be.checked') Cypress doesn't wait for the input element and returns undefined - gives false positive result

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress#6958] opened 2020-04-07 14:54 UTC
### Current behavior:

Assertion `.should('not.be.checked')` does not wait for the input element to be visible/actionable and returns `undefined`.
![undefined checkbox](https://user-images.githubusercontent.com/58426925/78683662-dd16d780-78ef-11ea-9614-f23467964202.png)

### Desired behavior:

When using `.should('not.be.checked')` on a checkbox input, Cypress should wait for the element to exist and be actionable just like it does when using assertion `.should('be.checked')`
![expected like](https://user-images.githubusercontent.com/58426925/78683675-e142f500-78ef-11ea-8962-ea9677d8fd3a.png)

### Test steps to reproduce

Visit web app that has loading screen, use mentioned assertion like
`cy.get('input[data-testid="checkbox-thing"]').should('not.be.checked');`

compare result to 
`cy.get('input[data-testid="checkbox-thing"]').should('be.checked');`

### Versions
Cypress: 4.2.0 and 4.3.0
Chrome: 80.0.3987.149 and 80.0.3987.163
OS: MacOS Catalina 10.15.4

**Comment by shwarcu** [comment] 2020-04-07 15:10
Temporary workaround:
`cy.get(checkboxTagReminderSelector).should('be.visible').and('not.be.checked');`

`be.visible` will force Cypress to wait for the element, and then `not.be.checked` assertion will be executed and will give correct result.

**Comment by jennifer-shehane** [comment] 2020-04-08 04:41
Duplicate of #205

**Closed by jennifer-shehane** 2020-04-08 04:41 UTC
