### ISSUE TITLE
Application under test is not interactive

### ISSUE THREAD

**Issue by bukharov** [cypress-io/cypress#25228] opened 2022-12-20 15:21 UTC
### Current behavior

Cypress displays "Default blank page" after test completes and there is no way to get to interactive version of the app. 

### Desired behavior

In previous versions applications stayed interactive, so it's possible to continue development.

### Test code to reproduce

Test code doesnt matter. Run any test to reproduce.

### Cypress Version

12.0.2

### Node version

14.19.3

### Operating System

macOS 12.5.1

**Comment by mike-plummer** [comment] 2022-12-20 18:27
Hi @bukharov , thanks for reaching out. I'm afraid I'll need a bit more information to assist with this. It's not clear from your writeup whether you're referring to E2E or Component Testing, but in both modes I'm able to create a new project, scaffold out basic tests, and the final rendered result is still visible and interactive in the runner once the tests are complete with Cypress v12.0.2.

A reproducible example would help me diagnose the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by emilyrohrbough** [comment] 2022-12-20 18:48
@bukharov The behavior you are describe is [`Test Isolation`](https://docs.cypress.io/guides/core-concepts/test-isolation). Please take a look at the documentation on what Test Isolation is a the aspects it provided you when enabled. It is configurable, so you can disabled this to persist the DOM state between tests, however, you'll be responsible to clearing cookies. local and session storage when desired.

**Comment by emilyrohrbough** [comment] 2022-12-20 18:49
I'm going to go ahead and close this issue since this is intended behavior in Cypress. If you have an issues after reading the documentation. Please feel add more information like @mike-plummer asked.

**Closed as not planned by emilyrohrbough** 2022-12-20 18:49 UTC
