### ISSUE TITLE
Firefox || Cross origin error thrown while running scripts on FF browser

### ISSUE THREAD

**Issue by RemaKoul** [cypress-io/cypress#25275] opened 2022-12-27 12:47 UTC
### Current behavior

Problem Statement  : While accessng the application, user has an option to make payment via a 3rd party tool. For other browsers, we are able to  make payment . However for FF , seeing cross origin error .
Cypress version in use : "cypress": "^12.2.0"

![image](https://user-images.githubusercontent.com/21169655/209668602-c0a2b51b-fc73-4bca-ac86-513b566ef43f.png)

### Desired behavior

Like chrome and Edge  , User should be able to make payment

### Test code to reproduce

Log on to application ( React JS based) on Firefox Browser 
Try to make payment 

### Cypress Version

12.2.0

### Node version

v16.17.0

### Operating System

Windows 10

**Comment by emilyrohrbough** [comment] 2022-12-27 14:37
@RemaKoul Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by RemaKoul** [comment] 2022-12-28 10:54
please give me some time. will add relevant details,

**Comment by RemaKoul** [comment] 2022-12-28 12:33
[
[FFPayment.zip](https://github.com/cypress-io/cypress/files/10314223/FFPayment.zip)
](url)

Hi @emilyrohrbough , please see attached ffpayment.spec.js which has steps to b executed . All called files are added in the zip,in case you find any particular file missing please refer from :  https://github.com/raintreeinc/qa-automation

Note : Issue exists only for FF browser

**Comment by emilyrohrbough** [comment] 2022-12-28 13:36
@RemaKoul thanks for the spec information! Is this setup to run against a deployed url or is there a local server I can use to run these specs? Also can you share your cypress configuration? As of know, the specs gives more insights but I'm not able to run them without access to your site or a small reduce-example you can share.

Maybe the github repo has this information. It appears to be private though and I don't have access to view.

**Comment by RemaKoul** [comment] 2022-12-29 06:24
[cypressConfig.txt](https://github.com/cypress-io/cypress/files/10317916/cypressConfig.txt)
url : https://org1-kiosk.sqa.raintreeinc.com/?location=ZZPOC

PS
; wasnt able to add .js file. So have added cypress config as txt file. Please save correctly before using

**Comment by RemaKoul** [comment] 2023-01-02 08:51
Hi @emilyrohrbough  , Any updates please?

**Comment by RemaKoul** [comment] 2023-01-09 11:16
@chrisbreiding  can we have an udpate on this please?

**Comment by RemaKoul** [comment] 2023-01-10 09:14
Hi Team,

It has been quite some time since I raised this issue and haven’t heard back . Looking forward for an update and early response please.

REMA KOUL
Sr. QA Analyst
[Logo  Description automatically generated]<https://www.cybage.com/>
[Receiver]
91-20-66041700
Ext : 6841
[World]
www.cybage.com<http://www.cybage.com>
[A close up of a sign  Description automatically generated]<https://www.facebook.com/cybage>
[A picture containing drawing  Description automatically generated]<https://www.linkedin.com/company/cybage/>
[A picture containing computer  Description automatically generated]<https://twitter.com/cybage>

**Comment by chrisbreiding** [comment] 2023-01-11 15:37
It looks like the error you're encountering is being thrown from a 3rd party plugin, [cypress-iframe](https://gitlab.com/kgroat/cypress-iframe). I would suggest submitting an issue there. 

Cypress does not currently support [cross-origin iframe testing](https://github.com/cypress-io/cypress/issues/136), though we do plan to add support for it in the future. I recommend keeping an eye on that issue for progress on built-in support for iframe testing.

**Closed as not planned by chrisbreiding** 2023-01-11 15:37 UTC
