### ISSUE TITLE
[Cypress4.3.0] Cannot execute multiple Cypress.promise() in after() (in support/index.js)

### ISSUE THREAD

**Issue by frankind** [cypress-io/cypress#6922] opened 2020-04-02 14:23 UTC
### Current behavior: Cannot execute multiple Cypress.promise() in after() (in support/index.js)
Found error in console

```Error:     Uncaught TypeError: Cannot read property 'textContent' of null

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
    at HTMLLIElement.<anonymous> (https://docs.cypress.io/__cypress/tests?p=cypress/support/index.js-927:52171:44)
    at findParentTitles (https://docs.cypress.io/__cypress/tests?p=cypress/support/index.js-927:52168:25)
```
![image](https://user-images.githubusercontent.com/16382131/78259828-63fe3580-7527-11ea-950a-0a4a62d38dd3.png)
Note: You cannot execute second Cypress.Promise() // show red error text

### Desired behavior:
Able to call multiple Cypress.Promise() in support/index.js
![image](https://user-images.githubusercontent.com/16382131/78260318-061e1d80-7528-11ea-8ff3-ab839045173b.png)

Note: It works fine in Cypress.4.1.0 and 4.2.0
Note2: It works fine if 'after()' method is execute in the same test file.
```js
/// <reference types="Cypress" />
describe('Cannot execute after() method', () => {
  after(() => {
    callWithPromise()
    callWithPromise()
  })

  function callWithPromise() {
    cy.server()
    return cy
      .request({
        method: 'POST',
        url: 'https://play.google.com/log?format=json&hasfast=true',
        failOnStatusCode: false
      })
      .then((xhr) => {
        return new Cypress.Promise((resolve, reject) => {
          resolve(xhr.body)
        })
      })
  }
  it('Test cannot execute after() in support/index.js', () => {
    cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html')
    cy.get('xxx').should('not.be.visible')
  })
})
```

### Test code to reproduce
Put this code in support/index.js
```js
after(() => {
  callWithPromise()
  callWithPromise()
})

function callWithPromise() {
  cy.server()
  return cy
    .request({
      method: 'POST',
      url: 'https://play.google.com/log?format=json&hasfast=true',
      failOnStatusCode: false
    })
    .then((xhr) => {
      return new Cypress.Promise((resolve, reject) => {
        resolve(xhr.body)
      })
    })
}
```

Put this code for running
```js
it('Test cannot execute after() in support/index.js', () => {
    cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html')
    cy.get('xxx').should('not.be.visible')
  })
```
### Versions
Cypress: 4.3.0
Chrome: 81 (or latest)

Effect: It will not execute multiple promises.

**Comment by jennifer-shehane** [comment] 2020-04-06 07:32
Thanks for providing an example. 

I am not able to reliably reproduce this in 4.3.0 - using Cypress 80. Are you sure you're using Chrome 81? Because that's not a stable release candidate. 

It did seem to fail on one rerun I made out of *many*, but not reliably where I could ever see it again. 

<img width="681" alt="Screen Shot 2020-04-06 at 1 35 13 PM" src="https://user-images.githubusercontent.com/1271364/78531565-ad8e9f00-780b-11ea-926e-5ab495b7680c.png">

Is this happening every run? Am I missing something else? I see the original error was failing at `findParentTitles`.

**Comment by frankind** [comment] 2020-04-07 06:49
> Thanks for providing an example.
> 
> I am not able to reliably reproduce this in 4.3.0 - using Cypress 80. Are you sure you're using Chrome 81? Because that's not a stable release candidate.
> 
> It did seem to fail on one rerun I made out of _many_, but not reliably where I could ever see it again.
> 
> <img alt="Screen Shot 2020-04-06 at 1 35 13 PM" width="681" src="https://user-images.githubusercontent.com/1271364/78531565-ad8e9f00-780b-11ea-926e-5ab495b7680c.png">
> 
> Is this happening every run? Am I missing something else? I see the original error was failing at `findParentTitles`.

Thank Jennifer

I try to reproduce this and finally found the problem.
I use this plugin "cypress-skip-and-only-ui"
After install this.
Add this **import 'cypress-skip-and-only-ui/support'** at support/index.js

So it will fail as I describe.
https://github.com/frankind/CypressSamples/blob/master/cypress/support/index.js

**Comment by jennifer-shehane** [comment] 2020-04-10 09:05
I am able to reproduce after pulling down the provided repository.

This error is being thrown from within the [`cypress-skip-and-only-ui`](https://github.com/bahmutov/cypress-skip-and-only-ui) plugin at this line: https://github.com/bahmutov/cypress-skip-and-only-ui/blob/dc1cb224d090019d7e170f112bb20e7771fa4b37/src/support.tsx#L76

You can see the stack trace by clicking on the failed POST request in the Command Log of the Test Runner.

<img width="873" alt="Screen Shot 2020-04-10 at 3 33 30 PM" src="https://user-images.githubusercontent.com/1271364/78978886-b3a0ba80-7b40-11ea-9dbf-3e724d531ed9.png">

<img width="504" alt="Screen Shot 2020-04-10 at 3 33 20 PM" src="https://user-images.githubusercontent.com/1271364/78978912-c1564000-7b40-11ea-8491-b7c7fc465428.png">

Please open an issue with the [`cypress-skip-and-only-ui`](https://github.com/bahmutov/cypress-skip-and-only-ui) plugin.

Closing as this is not an issue with the Cypress product.

**Closed by jennifer-shehane** 2020-04-10 09:05 UTC
Labels: stage: needs information
