### ISSUE TITLE
Cypress Tests are failing after the updating the Browser to Latest Version

### ISSUE THREAD

**Issue by svadivel0006** [cypress-io/cypress#23240] opened 2022-08-10 14:05 UTC
### Current behavior

_**Issue:**_ 

When the installed local Browser version is updated to the latest version and when I run the Cypress Test script, the test scripts are failing and the message “No Commands were issued in the test” was displayed.

**_After clicking the update in the Cypress Test runner too, the test scripts were failing._**

If I Close the Cypress Test Runner and after re-opening it, the tests are passing.

_**After local browser is updated, every new opening of Cypress Test Runner is causing error and tests are failing.**_

**_Screenshots:_**

![image](https://user-images.githubusercontent.com/85741928/183921371-a38e1c63-86db-4cf5-842b-944175b48a64.png)

![image](https://user-images.githubusercontent.com/85741928/183921399-4f5a78f8-b431-46c8-a443-26cfdef1c67c.png)

_After Re-Opening the Cypress Test Runner, the test scripts are passing:_

![image](https://user-images.githubusercontent.com/85741928/183921482-3055b350-5fa6-4c43-b521-e3d02f65d3df.png)

### Test code to reproduce

Any test will reproduce the behavious

### Cypress Version

v10.4.0

**Comment by rockindahizzy** [comment] 2022-08-11 17:45
Hey @svadivel0006, thanks for opening an issue!

I have a couple clarifying questions:
- Are you referring to the the update button in the browser that is highlighted in the screenshots above? 
- You stated that 
  > After Re-Opening the Cypress Test Runner, the test scripts are passing
  
  
  1\. Updating the browser
  2\. Closing and reopening cypress 

  After those steps, do things work as expected from that point forward (even after subsequent reopenings)?

**Comment by svadivel0006** [comment] 2022-08-11 18:26
Hey @rockindahizzy, kindly find my comments bellow

•	Are you referring to the update button in the browser that is highlighted in the screenshots above?

My Comments:
No, I have updated the local browser and to the latest version and when I run the Cypress Test script, the test scripts are failing and the message “No Commands were issued in the test” was displayed.

After clicking the update in the Cypress Test runner too, the test scripts were failing.
	
•	You stated that
After Re-Opening the Cypress Test Runner, the test scripts are passing
1. Updating the browser
2. Closing and reopening cypress

**_My Comments:_**
**_Yes, but the next time if re-open the Test Runner, issue still persist
When the test runner is re-opened after the 1st time it is working, the issue is happening all the next re-opening_**

**Comment by rockindahizzy** [comment] 2022-08-12 16:12
Hi @svadivel0006, thanks for responding!  Can you provide me with the OS and local Browser version?

**Comment by svadivel0006** [comment] 2022-08-12 19:52
Hi @rockindahizzy, kindly find the requested details

OS: Windows 10
Browser: Latest Chrome

**Comment by mike-plummer** [comment] 2022-08-17 20:26
@svadivel0006 It would be expected for Cypress to lose its connection to the browser if it is relaunched by an external process (such as the relaunch that happens on browser update). It would likely improve your experience if you make a habit of updating your browser while running it manually, rather than when it is launched from Cypress. We're simply opening the browser as-installed on your computer, so the version management process can be handled outside of the test runner.

If you're having to repeatedly update the browser (for example, it shows as out of date every time you launch your computer) that sounds like an issue with a VM or managed desktop image and would be external to Cypress. In this case it sounds like there is a viable workaround by ensuring Cypress is opened only after the browser has been updated.

If what I've stated here is incorrect please let me know and provide an example that reproduces the issue.

**Comment by nagash77** [comment] 2022-08-24 18:11
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-24 18:11 UTC
Labels: stage: awaiting response, Needs Reproduction
