### ISSUE TITLE
Cypress 3.4.0 hangs in CI with Chrome 75

### ISSUE THREAD

**Issue by rpd10** [cypress-io/cypress#4731] opened 2019-07-16 13:42 UTC
### Current behavior:
A test suite that runs correctly in CI using Chrome 73 is now hanging after using Chrome 75.

We have a suite of tests that has been working in CI builds using Chrome 73, and works locally using Chrome 75 and `cypress open`.  When we upgrade to use the `cypress/browsers:node10.11.0-chrome75` Docker image, the test runs started to hang after a couple of minutes.  There's no distinct pattern, sometimes it gets through 5 specs, sometimes 7, 10, etc (i.e. I don't believe it's a problem with a specific test).  

### Desired behavior:

Run through the whole suite of tests.

### Steps to reproduce: (app code and test code)

This is testing an Angular application.  In CI, we are using a Docker image based on cypress/browsers: `FROM cypress/browsers:node10.11.0-chrome75`, with browser set to chrome and headless mode turned on.

We are using `cypress-failed-log` and `
`cypress-skip-and-only-ui` plugins.  We use the standard spec reporter.

I turned DEBUG logs on and captured the logs from the failing run here: https://gist.github.com/rpd10/5f5522a3b76f79b1e952b81b36411e06

If it helps, I can attach partial DEBUG logs from a successful Chrome 73 run.

### Versions
Cypress 3.4.0 and 3.3.2.  Chrome 75 (FROM cypress/browsers:node10.11.0-chrome75).  GitLab 11.11.5.

**Comment by frankind** [comment] 2019-07-17 09:40
I face this problem too. Now I can run both chrome 73 and 74 in docker but all chrome 75 (all node versions) it is hang.

**Comment by Residentkoopa** [comment] 2019-07-17 14:50
i'm having the same issue since 3.3.2

**Comment by Q-back** [comment] 2019-08-28 12:10
as @frankind said. https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node10.2.1-chrome74 it's the latest version which works

**Comment by jbensson8790** [comment] 2019-09-18 11:33
I'm also hitting hangs and abnormal behavior in Chrome 77.0.3865.75.
I'm need to build my own CI containers and tried to use the following excerpt from Cypress's [Chrome Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node10.2.1-chrome74/Dockerfile) in my own custom Dockerfiles.
```dockerfile
RUN \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y dbus-x11 google-chrome-stable && \
  rm -rf /var/lib/apt/lists/*
```

Since the Chrome distributions have all been upgraded the excerpt now installs Chrome 77 instead of Chrome 74.

It would be helpful if Cypress could host the versions Chrome it supports, available for developers to download.

**Comment by Bkucera** [comment] 2019-10-01 21:27
@jbensson8790 have you seen https://chromium.cypress.io/ ?

**Comment by jbensson8790** [comment] 2019-10-02 00:52
Awesome, thanks  @Bkucera!

**Comment by alexanderchan** [comment] 2019-10-03 22:29
Seeing this as well on chrome Google Chrome 77.0.3865.90

**Comment by frankind** [comment] 2019-10-10 03:17
I still found this problem on Docker Chrome 77 with all node versions

**Comment by ptoshniw** [comment] 2019-10-20 11:28
I still found this issue in chrome 77 version and took two weeks time to figure out that it is not Network/Script/Proxy issue but chrome issue.

**Comment by dthomason** [comment] 2019-10-29 11:44
I'm experiencing this issue as well.  Hopefully it gets fixed soon.

**Comment by Rodyb** [comment] 2019-10-29 14:06
I have the same problem. 

However when adding: 
npx cypress run --browser chrome --spec cypress\integration\examples\POS\Login\002.Login.js

--browser chrome will work, so probably it's an electron issue.

**Comment by dthomason** [comment] 2019-10-29 14:57
cypress run --browser chrome works for most of my tests but intermittently it will stall.  One way of avoiding this was to break out my docker run in multiple tasks per spec folder.  This is not ideal though when needing to parralize.

**Comment by frankind** [comment] 2019-11-04 07:46
Finally, I get a workaround from my friend to be able to run on chrome docker version > 74 with this
https://github.com/cypress-io/cypress/issues/350#issuecomment-503231128
I have tried with node10.16.0-chrome77, and it works properly. (With Cypress 3.4.1)
No more hang anymore.

**Comment by brian-mann** [comment] 2019-11-04 21:17
With `3.5.0` out we now record videos in Chrome. 

@frankind we've looked into adding this option permanently, but we've seen it also be a **source** of crashes as well - which is why we've hesitated to add it.

**Comment by alexanderchan** [comment] 2019-12-05 00:03
We implemented the shm as recommended in https://github.com/cypress-io/cypress/issues/350#issuecomment-503231128 but still had the crashes.  In addition to the disabling shm, two things helped that so far 🤞have solved the issue with the cypress 3.7.0 and chrome 78:

- we found we had one file that was hanging more often so we split the tests into two files
- increased the [container size on CircleCI ](https://circleci.com/docs/2.0/configuration-reference/#resource_class) from `medium` to `medium+` which is a 4gb -> 6gb ram size difference

We didn't see any dreaded CircleCI 137 out of memory issues so it might just be a coincidence that the split and memory size fixed the problem.  When I get some more time I may try to reduce the container size to see if it was one or the other root cause.  Hope this helps someone.

**Comment by Shelex** [comment] 2020-01-01 21:44
>`so we split the tests into two files`

Yes, it helps us as well. When test suite execution time is more than 5 minutes - usually it hangs. 
(Your "critical execution time" may be above 5 min as we have a lot of additional logging in background in our case)
The problem is that as cypress return no errors in case browser crashes or hangs - pipeline (Concourse CI) with container keep running and should be terminated manually.

**Comment by LienLotus** [comment] 2020-02-13 04:54
I face this problem too on Chrome 80.0.3987.100-1, node10.16.0-chrome77, and cypress 4.0.1.
But it's working fine on Cypress 3.8.3
@jennifer-shehane : is it a regression bug?

**Comment by jennifer-shehane** [comment] 2021-09-08 18:41
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-09-08 18:41 UTC
Labels: external: docker, browser: chrome
