### ISSUE TITLE
Nuxt 3 Integration with Cypress Component Testing

### ISSUE THREAD

**Issue by bchandel77** [cypress-io/cypress#28780] opened 2024-01-23 10:28 UTC
### What would you like?

Can you please provide integration of cypress component testing with Nuxt 3 applications.

### Why is this needed?

This is needed to add cypress component testing in our Nuxt 3 application.

**Comment by jennifer-shehane** [comment] 2024-01-23 16:12
Duplicate of https://github.com/cypress-io/cypress/issues/23619

**Closed as completed by jennifer-shehane** 2024-01-23 16:12 UTC
Labels: type: duplicate
