### ISSUE TITLE
Delete old Cypress versions

### ISSUE THREAD

**Issue by lugosium** [cypress-io/cypress#28563] opened 2023-12-20 21:03 UTC
### What would you like?

Cypress should not keep all the old versions in ~/Library/Caches/Cypress.

### Why is this needed?

I have a 256G disk as many others.

Cypress currently take **54G**, this could be optimized.

### Other

Thanks!

**Comment by jennifer-shehane** [comment] 2023-12-21 04:44
Yah that’s…a lot… You can run `cypress cache prune` to uninstall all versions except for current. I suppose you could add this in a prebuild script or something if you use a particular project with Cypress. 

Duplicate of https://github.com/cypress-io/cypress/issues/19278

**Closed as not planned by jennifer-shehane** 2023-12-21 04:44 UTC
