### ISSUE TITLE
CLI - Browser doesn't close and hangs forever

### ISSUE THREAD

**Issue by venu** [cypress-io/cypress#4182] opened 2019-05-13 08:21 UTC
### Current behavior:

``` 
DEBUG=cypress:* ./node_modules/.bin/cypress run  --spec "cypress/integration/test_spec.js" --headed
```

When test is finished, browser is supposed to close and move to next testsuite. But it hangs forever.

```
cypress:server:project onMocha suite end +0ms
  cypress:server:reporter got mocha event 'suite end' with args: [ { id: 'r1', title: '', root: true, type: 'suite' } ] +0ms
  cypress:server:timers clearing timer id 82 from queue { '82': { args: [], ms: 85000, cb: [Function] } } +17ms
  cypress:server:timers queuing timer id 83 after 85000 ms +0ms
  cypress:server:timers child received timer id 83 +18ms
  cypress:server:project onMocha end +1ms
  cypress:server:reporter got mocha event 'end' with args: [ { end: '2019-05-13T08:03:29.340Z' } ] +0ms

  1 passing (10s)


  (Results)

  ┌──────────────────────────────────────────────────────┐
  │ Tests:        1                                      │
  │ Passing:      1                                      │
  │ Failing:      0                                      │
  │ Pending:      0                                      │
  │ Skipped:      0                                      │
  │ Screenshots:  0                                      │
  │ Video:        false                                  │
  │ Duration:     9 seconds                              │
  │ Spec Ran:     test_spec.js │
  └──────────────────────────────────────────────────────┘

  cypress:server:run attempting to close the browser +11ms
  cypress:server:browsers killing browser process +0ms
  cypress:server:timers clearing timer id 83 from queue { '83': { args: [], ms: 85000, cb: [Function] } } +13s
  cypress:server:timers queuing timer id 84 after 85000 ms +4ms
  cypress:server:timers child received timer id 84 +13s
  cypress:server:timers child sending timer id 3 +3s
```
![image](https://user-images.githubusercontent.com/130384/57605935-6f4e1880-7585-11e9-9683-1555c42de65d.png)

### Desired behavior:

When test is finished, browser is supposed to close and move to next testsuite. But it hangs forever.

### Steps to reproduce: (app code and test code)

App Code
-------------

```js
function onButtonClick() {
   window.location.hash = '/test/new'
}
```

Test Code
-------------

```js
cy.visit("/#/test");
cy.get('.test-btn').click()
cy.hash().should('eq', '#/test/new')
```

### Versions

Cypress - 3.2.0
OS - Ubuntu 18.04

**Comment by venu** [comment] 2019-05-13 08:46
It looks like, its related to `onbeforeunload` event.

**Comment by venu** [comment] 2019-05-13 15:29
For now, I have fixed this by disabling `onbeforeunload` after test finished, so browser can close.
```
afterEach(function() {
  cy.window().then(win => win.onbeforeunload = undefined);
})
```

**Comment by jennifer-shehane** [comment] 2019-05-14 07:12
Yes, this is a duplicate of https://github.com/cypress-io/cypress/issues/2118

**Closed by jennifer-shehane** 2019-05-14 07:12 UTC
