### ISSUE TITLE
Uncaught (in promise) TypeError doesn't cause test to fail

### ISSUE THREAD

**Issue by westhomas** [cypress-io/cypress#4998] opened 2019-08-16 19:22 UTC
### Steps to reproduce: 

```js
describe('how to fail', function () {
    it.only('should fail', function () {
        cy.visit("http://google.com")

        const doTheThing = () => {
            return new Promise((resolve) => {
                resolve({done: true})
            })
        }

        doTheThing().then((obj) => {
            const test = obj.badAttribute.reallyBad
            console.log(test)
            cy.log(test)
        })
    })  
})
```

This will throw this exception:

```
Uncaught (in promise) TypeError: Cannot read property 'reallyBad' of undefined
```

The problem is this is considered a pass in cypress:

![Screenshot 2019-08-16 14 19 18](https://user-images.githubusercontent.com/953369/63192527-e980b400-c030-11e9-93cf-28062e58f4e1.png)

### Current behavior:

Cypress tests don't fail when there's an exception within Promise

### Desired behavior:

Cypress test should fail if there's an unhandled exception in my test code. Right? 

### Versions

cypress==3.4.1

Note: I've added these in my support file and the debugger never breaks at these events for the above test:

```js
Cypress.on('uncaught:exception', (err, runnable) => {
    debugger
    console.log('uncaught:exception', err)
    // returning false here prevents Cypress from
    // failing the test
    return true
})

Cypress.on('fail', (err) => {
    debugger
})
```

**Comment by uweku** [comment] 2019-08-19 09:30
I confirm that behaviour.
My fail routine looks similar to the one above. But it still won't fail. This seems to have changed since the most current release, as the Tests broke reliably in the past:

`
Cypress.on('fail', (error, runnable) => {
	skipAllTests = true;
	throw error;
})
`

`
function deleteElements(name, deleteFunc) {
  isContain(name).then(el => {
    for (let i = 0; i < el.length; i++) {
      isContain(name)
        .eq(0)
        .click({ force: true });
      deleteFunc();
      cy.wait(1000);
    }
  });
}
...
	cy.route({
		method: 'DELETE', url: '/master/locations/*',
		onResponse: (xhr) => {
			expect(xhr.status).to.eq(expectedHttpStatus);
		}
	}).as('deleteLocations');
…
	deleteElements('TestBla', () => {
		cy.wait('@getLocationsDetails');
		cy.wait(500);
		cy.getElementByDataCypress('btnDeleteLocation').click({ force: true });
		cy.get("button:contains('Ja'),button:contains('Yes')").click({ force: true });
		cy.wait('@deleteLocations');
	})
`
I'll give it some more Tests with <....its('status').should('be', 201)…> Notation, and will observe that behaviour in non-visual test runner mode

**Comment by westhomas** [comment] 2019-08-19 16:21
I went all the way back to cypress@2.1.0 and observed the same behavior: test still passes and events do not get triggered.

**Comment by westhomas** [comment] 2019-08-20 11:37
@jennifer-shehane Could you confirm this behavior as intended or a defect? It makes for some scary false positives and I need to figure out how to mitigate that.

**Comment by westhomas** [comment] 2019-08-23 16:27
@brian-mann Any thoughts on this? I basically can't use the promise pattern in my own support code currently because if there are exceptions in the support code, they don't fail the test. Is that desired? What am I doing wrong?

**Comment by mpahuja** [comment] 2019-08-30 08:56
might wanna try using the Cypress promise which wraps bluebird promises but should be chained off cy.
https://docs.cypress.io/api/utilities/promise.html#Syntax

**Comment by trejjam** [comment] 2020-01-16 13:14
The correct way how to write this is:

```
describe('how to fail', function () {

    it.only('should fail', function () {

        cy.visit("http://google.com")

        const doTheThing = () => {
            return new Promise((resolve) => {
                resolve({done: true})
            })
        }

// see the cy.wrap here
        cy.wrap(doTheThing()).then((obj) => {

            const test = obj.badAttribute.reallyBad
            console.log(test)
            cy.log(test)
        })

    })
    
})
```

Otherwise, your test ends before `Cannot read property 'reallyBad' of undefined`

**Comment by JohnnyFun** [comment] 2020-04-09 21:13
Is this a duplicate of https://github.com/cypress-io/cypress/issues/2487?

**Comment by jennifer-shehane** [comment] 2020-05-18 05:24
Cypress only waits for it's own enqueued commands to finish before passing the tests. So after the visit succeeds, there are no more Cypress commands enqueued - so it passes. As mentioned by @trejjam, you'll want to put your promise in a `cy.wrap()` so we know to wait for the Promise code.

**Closed by jennifer-shehane** 2020-05-18 05:24 UTC
