### ISSUE TITLE
Application built on iframes requires window.top to be the actual application and not the cypress window

### ISSUE THREAD

**Issue by Raghav-Ramanathan** [cypress-io/cypress#15367] opened 2021-03-09 07:44 UTC
The problem I am facing here is that my application has been built entirely on iframes.
So when I click on sign in, there is a code which accesses the window.top and makes changes to it. This causes a lot of issues for me as it stops the cypress execution of the tests and displays "no tests to execute" message as the original cypress window gets redirected.
The work around I have implemented here for now is to open my application into a new child window and this works as the window.top is now equal to window.self. 
However, opening the application in a child window restricts the use of cypress to take screenshots or videos as expected , as the screenshot captures the cypress iframe instead of my application window.
Please suggest a approach which would help and I would be glad to try it out.

**Comment by jennifer-shehane** [comment] 2021-03-16 22:44
Duplicate of https://github.com/cypress-io/cypress/issues/8063

The only way to workaround would be to call `window` when running within Cypress isntead of `window.top`. 
```
if (window.Cypress) {
  // we are running in Cypress
  // so do something different here
  window.env = 'test'
} else {
  // we are running in a regular ol' browser
}
```

**Closed by jennifer-shehane** 2021-03-16 22:44 UTC
