### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by vasal635** [cypress-io/cypress#21643] opened 2022-05-26 10:34 UTC
### Current behavior

I checked cypress performance on version 9.7.0 and this is slower then 8.1.0 

MacOs Monterey 12.4 (21F79)
MacBook Pro (16-inch, 2019)
Processor 2,6 GHz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4

I used the same test for 2 versions. 

In version 9.7.0 it's taking average 130 seconds per my test.

![Screenshot 2022-05-24 at 11 22 52](https://user-images.githubusercontent.com/71557713/170470216-10684fb7-e061-4c64-af03-dbfc910cd4f1.png)

In version 8.1.0 it's taking average 70 seconds per my test.

![Screenshot 2022-05-24 at 11 19 02](https://user-images.githubusercontent.com/71557713/170470180-69722f4e-b186-4a14-befa-c67a3463604b.png)

### Desired behavior

I'm waiting, that new version will have better performance, then old one.

Also I tried to install new versions for several times -> but performance was bad.

### Test code to reproduce

1. Install version 8.1.0
npm install --save-dev cypress@8.1.0

2. Run test and make screenshot of time

3. Install version 9.7.0
npm install --save-dev cypress@9.7.0

4. Run test and make screenshot of time

5. Notice, that new version is slower, then old one

### Cypress Version

9.7.0

**Comment by bbartizek** [comment] 2022-05-26 18:00
I noticed similar results.  We have a test suite in one of our CI pipelines that averages 12m 10s over the last 30 days on 8.1.0.  I recently upgraded to 9.7.0 in order to take advantage of the new experimental session() feature, and the same suite with only minor changes for the session handling went to ~25 minutes.  I thought it was due to the new session behavior compared to inheriting existing sessions between tests, but that seemed like a huge hit for just fetching browser state from cache.  I think my results might be impacted in the same way as vasal365.

**Comment by romankhomitskyi** [comment] 2022-05-27 16:07
Same here, tests are really slow on 9.5.0
It would be great if this issue got fixed before 10 release

**Comment by darrinmn9** [comment] 2022-05-27 21:36
possibly related to https://github.com/cypress-io/cypress/issues/18564 ?

**Comment by vasal635** [comment] 2022-06-02 09:54
Hi @ZachJW34 

Yes, this is duplicate of [#18564](https://github.com/cypress-io/cypress/issues/18564)

I have a lot of cy.visit() in this tests.

I also tried 10.0.1 
![Screenshot 2022-06-02 at 11 47 43](https://user-images.githubusercontent.com/71557713/171604614-06387344-9f97-44a0-bcb5-ed27fa504e39.png)

But 8.1.0 still has better performance 
![Screenshot 2022-06-02 at 11 35 28](https://user-images.githubusercontent.com/71557713/171604740-9b8ecd02-93c8-4641-bab0-f15efe5c9966.png)

Hope, that you will fix it.

**Comment by mjhenkes** [comment] 2022-06-02 17:42
Closing as duplicate of https://github.com/cypress-io/cypress/issues/18564

**Closed by mjhenkes** 2022-06-02 17:42 UTC
Labels: stage: investigating
