### ISSUE TITLE
Cypress headless run doesn't exit after the error log "The automation client disconnected"

### ISSUE THREAD

**Issue by broom9** [cypress-io/cypress#4434] opened 2019-06-11 18:38 UTC
### Current behavior:

When running Cypress in Docker, after a line of error log "The automation client disconnected. Cannot continue running tests." Cypress doesn't exit but keeps running with logs like below:

```
Tue, 11 Jun 2019 15:28:06 GMT cypress:server:timers child sending timer id 1454
Tue, 11 Jun 2019 15:28:06 GMT cypress:server:timers child sending timer id 1013
Tue, 11 Jun 2019 15:28:06 GMT cypress:server:timers child sending timer id 1457
Tue, 11 Jun 2019 15:28:08 GMT cypress:server:timers child sending timer id 1014
```

### Desired behavior:

Headless run exits if the automation client has disconnected.

### Steps to reproduce: (app code and test code)

This doesn't happen very often or steadily, so I don't have steps to reproduce. 

### Versions

Cypress 3.2.0
Docker
Amazon Linux 2

**Comment by luckybai** [comment] 2019-06-18 09:41
+1. 

At the same time, Cypress can't work in Local Docker Container, but it's ok on Gitlab CI. 

![image](https://user-images.githubusercontent.com/31891883/59671233-e95e6680-91ef-11e9-861c-1f335b2cfd3a.png)

**Comment by jennifer-shehane** [comment] 2019-06-21 09:26
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

We have many passing tests against our own Docker Containers - so we would need information on what is specific to your setup that is failing. It likely has something to do with a combination of your tests + docker.

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by mark-veenstra** [comment] 2019-06-21 09:47
@jennifer-shehane I run into the same issue on GitLab CI running a Cypress image with the docker in docker executor.

What I have done:

# Create own Cypress image based on images from Cypress
```
FROM cypress/browsers:node11.13.0-chrome73 AS build
MAINTAINER markdark81 [at] gmail [dot] com

# ------------------------------------------ #
#              Production stage              #
# ------------------------------------------ #
FROM build AS prod

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./cypress.json ./cypress.json

RUN echo "Europe/Amsterdam" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
RUN npm i

ENV PATH="${PATH}:/usr/src/app/node_modules/.bin"
```
Above `Dockerfile` is build using GitLab CI and pushed to the registry in private GitLab. This works as expected.

# Running test with `docker-dind`
Following job is used in `.gitlab-ci.yml`
```yaml
e2e:videocall:
  stage: e2e
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - |
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      BASE_DIR="cypress/integration/videocall/"
      for DIRPATH in ${BASE_DIR}/* ; do
        if [ -d "${DIRPATH}" ]; then
          DIR=$(basename ${DIRPATH})
          ./bin/e2e-run.sh videocall ${DIR}
        fi
      done
  dependencies:
    - build:dev:browser
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/log
      - cypress/screenshots
      - cypress/videos
```
And the script (`e2e-run.sh`) that get's executed has the following content:
```
#!/usr/bin/env sh
DOCKER_IMAGE="<PREVIOUS-BUILDED-IMAGE>"
CYPRESS_DIR="cypress/"
TEST_FUNC="${1}"
BASE_DIR="${CYPRESS_DIR}integration/${TEST_FUNC}/"
SETTINGS_FILE="Settings.js"

USAGE="${0} <test folder> <skip file>\n\nCheck for the <test folder> the directories listed in '${BASE_DIR}', which can be used as argument\n\nFor example: ${0} videocall one-to-one"

TESTFLOW="${2}"
SKIPFILE="${3}"

if [ ! -d "cypress" ] && [ ! -f "package.json" ]; then
  echo "Execute this command from your project root!" >&2
  echo -e ${USAGE} >&2
  exit 1
fi

if [ ! -d "${BASE_DIR}${TESTFLOW}" ] || [ -z "${TESTFLOW}" ] || [ -z "${TEST_FUNC}" ]; then
  echo "Argument '${TESTFLOW}' not found as a directory of '${BASE_DIR}'" >&2
  echo -e ${USAGE} >&2
  exit 1
fi

if [ ! -f "${BASE_DIR}${TESTFLOW}/${SKIPFILE}" ] && [ ! -z "${SKIPFILE}" ]; then
  echo "Argument '${SKIPFILE}' not found as a spec file in directory '${BASE_DIR}${TESTFLOW}'" >&2
  echo -e ${USAGE} >&2
  exit 1
fi

if [ ! -d "${CYPRESS_DIR}log" ]; then
  mkdir "${CYPRESS_DIR}log"
fi

echo "Pulling ${DOCKER_IMAGE}"
docker pull ${DOCKER_IMAGE}

if [ ${CI} ]; then
  CICMD="--volume /var/run/docker.sock:/var/run/docker.sock"
fi

if [ ! -z "${CYPRESS_RECORD_KEY}" ]; then
  RECORDCMD="--record --key ${CYPRESS_RECORD_KEY}"
fi

START=`date +%s`
if [ -f "${BASE_DIR}${TESTFLOW}/${SETTINGS_FILE}" ]; then
  echo "Executing settings for test: '${TESTFLOW}'"
  docker run --rm --name=e2e_${TEST_FUNC}_${TESTFLOW}_${SETTINGS_FILE} --ipc=host -i ${CICMD} -v $(pwd)/config:/usr/src/app/config -v $(pwd)/cypress:/usr/src/app/cypress ${DOCKER_IMAGE} sh -c "cypress run ${RECORDCMD} --spec=${BASE_DIR}${TESTFLOW}/${SETTINGS_FILE} > ${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_${SETTINGS_FILE}.log 2>&1 && rm ${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_${SETTINGS_FILE}.log"

  if [ -f "${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_${SETTINGS_FILE}.log" ]; then
    echo "Something went wrong while executing '${BASE_DIR}${TESTFLOW}/${SETTINGS_FILE}', check the log!" >&2
    exit 1
  fi
fi

for SPECFILEPATH in ${BASE_DIR}${TESTFLOW}/*-spec.js; do
  SPECFILE=$(basename ${SPECFILEPATH})
  if [ "${BASE_DIR}${TESTFLOW}/${SPECFILE}" != "${BASE_DIR}${TESTFLOW}/${SKIPFILE}" ]; then
      echo "Starting '${SPECFILE}' for test '${TESTFLOW}'"
      docker run --detach --rm --name=e2e_${TEST_FUNC}_${TESTFLOW}_${SPECFILE} --ipc=host -i ${CICMD} -v $(pwd)/config:/usr/src/app/config -v $(pwd)/cypress:/usr/src/app/cypress ${DOCKER_IMAGE} sh -c "cypress run ${RECORDCMD} --spec=${SPECFILEPATH} --browser=chrome > ${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_${SPECFILE}.log 2>&1 && rm ${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_${SPECFILE}.log" > /dev/null
  fi
done

while [ `docker container ls --filter name=e2e_${TEST_FUNC}_${TESTFLOW} --format {{.Names}} | wc -l` -gt 0 ]; do
  NOW=`date +%s`
  CCONT=`docker container ls --filter name=e2e_${TEST_FUNC}_${TESTFLOW} --format {{.Names}} | wc -l`

  COUNTER=0
  TOTAL=$(($CCONT + 1))
  while [ $COUNTER -lt ${TOTAL} ]; do
    tput cuu1 2> /dev/null; tput el 2> /dev/null
    COUNTER=$(($COUNTER + 1))
  done

  docker container ls --filter name=e2e_${TEST_FUNC}_${TESTFLOW} --format "{{.Names}} - {{.Status}}"

  DURATION=$((NOW-START))
  echo "Running '${TESTFLOW}' for ${DURATION} seconds."
  sleep 1

  if [ $DURATION -gt 600 ]; then
    for log in `docker container ls --filter name=e2e_${TEST_FUNC}_${TESTFLOW} --format "{{.Names}}"`; do
      echo "---- BEGIN ${log} ----"
      docker logs "${log}"
      echo "---- END ${log} ----"
    done
    for log in ${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_*; do
      echo "---- BEGIN ${log} ----"
      cat "${log}"
      echo "---- END ${log} ----"
    done
    break
  fi
done
echo ""

COUNT_LOGFILES=$(ls -l ${CYPRESS_DIR}log/e2e_${TEST_FUNC}_${TESTFLOW}_* 2> /dev/null | wc -l)
echo "${COUNT_LOGFILES} spec files with errors"
if [ ${COUNT_LOGFILES} -gt 0 ]; then
  exit 1
fi
exit 0
```
I am using the above script because I want to fire-up multiple containers. These containers do E2E tests with videocall capabilities. For example one container is the `Caller` and the other `Callee`. Locally all works fine and all tests pass.

But when I run it in the GitLab CI it fails with the error `The automation client disconnected. Cannot continue running tests.`, but the container do not exit.

So I have 2 issues:
1. Why does this error occur?
2. Why do the containers keep running?

As you can see in the `e2e-run.sh` script I run a `Settings.js` spec first. This fires up a container and logs into our application for different users used in the test and will set the settings needed for the test. I do this because there is no other way at the moment to do this in our application. This settings spec is running correctly. But after it finishes and the Caller and Callee specs are started some of the test succeed but then the error occurs as mentioned in GitLab CI.

Maybe it has something to do with the gitlab shared runners and memory?

**Comment by mark-veenstra** [comment] 2019-06-24 12:32
Well I just did some fixes as described [in this comment](https://github.com/cypress-io/cypress/issues/350#issuecomment-503231128). So what I did:
* Everyting described as above, but
* Upgraded the image to install Cypress `3.3.0`
* Using the base image `cypress/browsers:node10.2.1-chrome74` instead of `cypress/browsers:node11.13.0-chrome73`
* Use the `--browser chrome` flag and make sure to add the chrome flag `--disable-dev-shm-usage` is used

Now the tests will run and pass like locally.

**Comment by bahmutov** [comment] 2019-06-24 17:44
yeah, it seems it was just crashing due to shm space

**Comment by pozimkie** [comment] 2019-11-18 21:52
We are running cypress 3.4.1 with chrome 74 headless inside custom docker image, "The automation client disconnected" appeared after adding few additional tests. By default docker is granting 64MB of shared memory to container, after tweaking it to 256MB mentioned issue is resolved.

**Comment by jennifer-shehane** [comment] 2021-07-06 20:35
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-07-06 20:35 UTC
Labels: type: error message
