### ISSUE TITLE
unable to signup using keycloak through cypress

### ISSUE THREAD

**Issue by wajeeha09** [cypress-io/cypress#3119] opened 2019-01-10 19:41 UTC
### Current behavior:

In my application, user management is done through Keycloak. Manual signup works fine but while testing my application end to end through cypress, I come across an issue. When I sign up user through it, it gives the following error:

**We're sorry. An error has occurred, please login again through your application.**

I have noticed that in test case cypress is appending `session_code` to the request url after I click on submit button. While doing manual test I don't get session code. This can be cause of this issue. Please share your views if you think of any other reason for this issue. Below is the url generated through cypress

```
.../login-actions/registration?session_code=LsZbmsVVLwEH9s-xwFJ2JdDtaCu1_xzqAGOQCpjxGJI&execution=06fac3bb-fb19-474b-8659-2572586ae371&client_id=web_app&tab_id=PSlmfgdv0ls
```

Where as manually generated url is like following 
```
.../login-actions/registration?client_id=web_app&tab_id=PSlmfgdv0ls
```

My application backend is Spring boot and front-end is in React and next.js

It would be really helpful if anyone from your team could guide us for this issue. Please let me know if you need more information about our application.

### Desired behavior:

Desired behavior is to able to signup through cypress tests 

### Steps to reproduce: (app code and test code)

You can use this test case 

```json
{
  "baseUrl": "",
  "pageLoadTimeout": 180000,
  "defaultCommandTimeout": 50000,
  "env":{
    "ENVIROMENT":"mock"
  },
  "reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "reports",
    "reportFilename": "test-report",
    "reportTitle": "Carbook Test Run",
    "overWrite": true,
    "saveHtml": true
  }
}
```

```js
describe("Carbook Registration Page", () => {
  before(() => {
    cy.visit("/")
  })

  it("Verify that user is access registration page", () => {
    cy.get("#nav-sign-in").should('be.visible')
    cy.get("#nav-sign-in").click()
    cy.wait(5000)
    cy.get("a").contains("Register").should('be.visible')
    cy.get("a").contains("Register").click()
  })

  it("Verify that user able to go back to login page", () => {
    cy.get("#kc-form-options").should('be.visible')
    cy.get("#kc-form-options").click()
    cy.get("#kc-page-title").should('be.visible')
  })

  it("Verify that user is able to register for carbook", () => {
    cy.get("#firstName").type("Test")
    cy.get("#lastName").type("Test")
    cy.get("#email").type("wajeeha@test.com")
    cy.get("#password").type("test@123")
    cy.get("#password-confirm").type("test@123")
    cy.get('input[name="user.attributes.phone"]').type("12341234567")
    cy.get('input[name="user.attributes.cnic"]').type("1234512345678")
    cy.get('input[value="Register"]').click()
    cy.wait(10000)
  })
})
```

**Comment by jennifer-shehane** [comment] 2019-01-14 07:11
Hey @wajeeha09, we are unable to run the tests provided without the application code or a url to visit in the tests. From the provided test code and settings - everything looks set up properly. 

Could you provide screenshots, application code to visit replicating the error, anything else? 
Unfortunately we'll have to close this issue if no reproducible example is provided.

If you're interested in dedicated email support, which gives you one-on-one help from our team, you can sign up for one of our [paid plans](https://www.cypress.io/pricing/) then email us at support@cypress.io.

**Comment by wajeeha09** [comment] 2019-01-15 10:01
@jennifer-shehane Thank you for responding.  Application is deployed  its base url is:  "https://carbook-client-public.carbook-mock.gocarbook.com". Using this url you should be able to run the test.  Let me know if any other information is required.

**Comment by wajeeha09** [comment] 2019-01-15 10:18
@jennifer-shehane This zip file contains output video of this test. You can use this as you reference 
[register.e2e-spec.ts.mp4.zip](https://github.com/cypress-io/cypress/files/2759128/register.e2e-spec.ts.mp4.zip)

**Comment by wajeeha09** [comment] 2019-01-15 10:36
@jennifer-shehane Thank you for responding. Application is deployed. Base url is: https://carbook-client-public.carbook-mock.gocarbook.com. Using this url you should be able to reproduce this issue. Let me know if any other information is required.

**Comment by kashifali00** [comment] 2019-01-23 10:03
Hi @jennifer-shehane is there any update on that issue?

**Comment by jennifer-shehane** [comment] 2019-04-16 12:17
@wajeeha09 Any update on this? Were you able to resolve this issue? I'd like to close it if so.

**Comment by ZijlkerVR** [comment] 2019-05-17 14:08
@wajeeha09 Have the same problem in my application using keycloak tested by cypress, but I do not recall seeing any extra parameters in my URL. 

Do you have the issue when you login right away as first step of your first test? I'm only getting it whenever I try to login in test after some other actions/tests. 

Workaround for now is changing "before" to "beforeEach" so it revisits the login page every test. I'm going straight to login page. Only doing this in a specific login.spec which has only 3 tests so impact is minimal. 

Now trying to create a cy.request to skip the UI login altogether for all other tests as recommended by Cypress team. Having a hard time with that though. Not familiar with the API. Might be easier to just stub the authentications.

**Comment by ZijlkerVR** [comment] 2019-05-23 08:16
I've succeeded in automating our (proxied) Keycloak login without UI using a chain of 5 requests. 

1. GET request to retrieve actionUrl plus query string parameters from login page:
`/auth/realms/{realm}/protocol/openid-connect/auth?scope=name%2Cemail&response_type=code&approval_prompt=auto&redirect_uri={site}%2Fuserauth&client_id=account`
Used this regex to retrieve the url from the HTMLstring object and fix it (using &):
`resp.body.match(/action\=\"(.*)\" /)[1].replace(/&amp;/g, '&');`
2. POST form request to the actionUrl with user/pass in body:
`/auth/realms/{realm}/login-actions/authenticate?session_code={x}&execution={x}&client_id=account&tab_id={x}`
Keycloak cookies are now set. 
3. Redirect back to our login page (which will redirect now because of keycloak cookies)
4. Redirected to the same "auth" of step 1 but with state:
`/auth/realms/{realm}/protocol/openid-connect/auth?state={x}&scope=name%2Cemail&response_type=code&approval_prompt=auto&redirect_uri={site}%2Fuserauth&client_id=account`
5. Redirected to "userauth" eventually leading to our application setting our final login cookies:
`/userauth?state={x}&session_state={x}&code={x}`

I've disabled followRedirect on all calls and handled them myself instead. Main reason is it didn't result in an authentication cookies for some reason. Second reason is we use Keycloak server on 1 environment for several other test environments. Catching the redirect enables us to go to particular environment. 

Normally I would expect it to be possible to handle this in 2 - 3 steps when the redirecting is followed properly by both Cypress and website. Not sure where it failed. We have a custom keycloak proxy layer so just followed that one. Going through UI entirely will result in even more requests/redirects (8-10). 

I realize this is not the most ideal way, but it was the quickest one and still decent result. Login in 2.5s instead of 6-10s through UI. Call 1 and 2 are done in 0.4 seconds. Step 3 is slowing it down caused by lazy acceptance server.

**Comment by pouriaMaleki** [comment] 2019-05-28 08:34
@ZijlkerVR I have followed steps 1 to 3 using this [Blog Post of @vrockai](https://vrockai.github.io/blog/2017/10/28/cypress-keycloak-intregration/), still can't figure out why it won't work. 

It might be because of step 4 and 5 of your guide, can you provide more detailed information about that?

```
context('Logged in user', () => {
  beforeEach(() => {
    cy.kcLogin('testuser', 'testuserpass');
  });

  afterEach(() => {
    cy.kcLogout();
  });

  it('Should render logged user name somewhere on the page', () => {
    cy.visit('http://SAMPLE.com'); // still not logged in, although beforeEach is successful.
    cy.get('#username').should('contain', 'testuser');
  });
});
```

**Comment by jennifer-shehane** [comment] 2019-07-30 07:12
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Closed by jennifer-shehane** 2019-07-30 07:12 UTC
Labels: stage: needs information

**Comment by KhizerRehan** [comment] 2022-03-15 16:33
Hi @jennifer-shehane 
I will highly appreciate if you could help

Tried following packages to login with cypress:
- https://openbase.com/js/cypress-keycloak-commands/documentation
- https://vrockai.github.io/blog/2017/10/28/cypress-keycloak-intregration/

I am able to login in the sense that Local-storage does show state and token but cypress fails to redirect back to `/home` page



https://user-images.githubusercontent.com/17727069/158426431-860f74ef-3da9-496f-94bb-23680ab9b577.mp4

**Comment by Medmj** [comment] 2022-11-08 10:46
Hello I had the same issue,
Cypress is able to see the cookies, I even tried getting them and force setting them just after the login and before every test but still acts as if there are no cookies.

The actual message I am getting from the app I'm testing is "Cookie not found. Please make sure cookies are enabled in your browser."

Weirdly enough, I changed the Cypress browser to use for from Chrome 107 to Electron 93 and the problem is gone. (using cypress 8.7.0)

Aren't the browsers supposed tp work in "similar ways" regarding the basic stuff like cookies and login to a certain degree ?

**Comment by Swiech-Jan** [comment] 2023-09-28 11:34
@KhizerRehan
Did you solve your problem? 
I have the same issue since we upgraded KeyCloak from version 11 to 21.1.
All works in browser as user interacts with the page but Cypress have problem with last redirect to home page after getting all auth cookies from KeyCloak.

I'm Starting the test on the KeyCloak login page then after submitting the login form that last redirect to App home page ends up with timeout - even If all cookies are set properly. Strange that this was working on old version of KeyCloak... Perhaps newest version of KeyCloak are more restrict?
