### ISSUE TITLE
@cypress/react version is behind cypress-react-unit-test

### ISSUE THREAD

**Issue by kestas-devbridge** [cypress-io/cypress#15030] opened 2021-02-10 23:32 UTC
### Current behavior
`cypress-react-unit-test` is deprecated and renamed to `@cypress/react`, however `cypress-react-unit-test` latest version is `4.17.2` and `@cypress/react` is `4.16.4`. Looks like issues that were resolved in latest version of `cypress-react-unit-test` still exists in `@cypress/react`. i.e.: https://github.com/cypress-io/cypress-react-unit-test/pull/519

### Desired behavior
Fixes from `cypress-react-unit-test` should exist in `@cypress/react`

**Comment by glomotion** [comment] 2021-02-11 04:53
Could we plz get some attension on this issue?

FWIW i'm also seeing some bad type errors when using @cypress/react@4.16.4: 
```
node_modules/@cypress/react/dist/mount.d.ts:22:65 - error TS2304: Cannot find name 'MountOptions'.

22 export declare const mount: (jsx: React.ReactElement, options?: MountOptions) => Cypress.Chainable<JQuery<any>>;
                                                                   ~~~~~~~~~~~~

node_modules/@cypress/react/dist/mount.d.ts:59:52 - error TS2304: Cannot find name 'MountOptions'.

59 export declare const createMount: (defaultOptions: MountOptions) => (element: React.ReactElement, options?: Partial<StyleOptions & MountReactComponentOptions> | undefined) => Cypress.Chainable<JQuery<any>>;
                                                      ~~~~~~~~~~~~

node_modules/@cypress/react/dist/mount.d.ts:59:117 - error TS2304: Cannot find name 'StyleOptions'.

59 export declare const createMount: (defaultOptions: MountOptions) => (element: React.ReactElement, options?: Partial<StyleOptions & MountReactComponentOptions> | undefined) => Cypress.Chainable<JQuery<any>>;
                                                                                                                       ~~~~~~~~~~~~

node_modules/@cypress/react/dist/mount.d.ts:59:132 - error TS2304: Cannot find name 'MountReactComponentOptions'.

59 export declare const createMount: (defaultOptions: MountOptions) => (element: React.ReactElement, options?: Partial<StyleOptions & MountReactComponentOptions> | undefined) => Cypress.Chainable<JQuery<any>>;
                                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cassus** [comment] 2021-03-13 20:59
Upgrading to `@cypress/react@5.0.1` solved the problem for me

**Comment by sainthkh** [comment] 2021-05-03 00:50
Closing because the problem is solved with the latest version.

**Closed by sainthkh** 2021-05-03 00:50 UTC
