### ISSUE TITLE
Test report in Cypress dashboard does not work (Azure DevOps)

### ISSUE THREAD

**Issue by Oaky78** [cypress-io/cypress#8249] opened 2020-08-11 10:56 UTC
Since yesterday, my tests no longer run in the dashboard. All tests are shown as new (screenshot).

After 40 minutes the run in Azure is finished, in Cypress dashboard it stops after 90 minutes without result.
The job configuration was not changed.

<img width="1134" alt="dash" src="https://user-images.githubusercontent.com/20914123/89889581-2646a300-dbd2-11ea-928c-22a0d33de38e.png">

### Versions
CI: Azure
Cypress: v4.12.1
Browser: Electron 80.0.3987.165
OS: Windows 10.0.14393

**Comment by jennifer-shehane** [comment] 2020-08-12 06:59
This means that the `cypress run` inside of Azure never reported an exit code through Cypress. So Cypress has no record of the results of the run. You'll need to refer to your CI Provider's logs to see any errors or reasons that the exit code did not issue. 

If we don't receive an exit code then the run will automatically time out after about 90 minutes. 

Running Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode may also give some insight into what is happening during the cypress run.

**Comment by Oaky78** [comment] 2020-08-12 07:59
`
2020-08-12T07:43:37.308Z cypress:server:cypress about to exit with code 11
2020-08-12T07:43:37.321Z cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 54138 }
2020-08-12T07:43:37.519Z cypress:cli child event fired { event: 'exit', code: 11, signal: null }
2020-08-12T07:43:37.519Z cypress:cli child event fired { event: 'close', code: 11, signal: null }
##[error]Cmd.exe exited with code '11'.
`

**Comment by Oaky78** [comment] 2020-08-12 08:02
2020-08-12T07:27:27.361Z cypress:server:api request to url: POST https://api.cypress.io/exceptions with params: {"body":{"err":{"name":"StatusCodeError","message":"400\n\n{\n  \"message\": \"Cannot find unclaimed instance for spec: cypress<stripped-path>favorite-folder-description.spec.ts\"\n}","stack":"StatusCodeError: 400 - {\"message\":\"Cannot find unclaimed instance for spec: cypress<stripped-path>favorite-folder-description.spec.ts\"}\n    at new StatusCodeError (<stripped-path>errors.js:32:15)\n    at Request.plumbing.callback (<stripped-path>plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (<stripped-path>plumbing.js:46:31)\n    at Request.self.callback (<stripped-path>request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.<anonymous> (<stripped-path>request.js:1156:10)\n    at Request.emit (events.js:210:5)\n    at IncomingMessage.<anonymous> (<stripped-path>request.js:1078:12)\n    at Object.onceWrapper (events.js:299:28)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1183:12)\n    at processTicksAndRejections (internal<stripped-path>task_queues.js:80:21)"},"version":"4.12.1","osName":"win32","osVersion":"10.0.14393","osCpus":[{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":14044109,"nice":0,"sys":6941984,"idle":472526296,"irq":119109}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":13292671,"nice":0,"sys":6444484,"idle":473774859,"irq":103250}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":12463046,"nice":0,"sys":6226765,"idle":474822203,"irq":155937}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":14831593,"nice":0,"sys":6764343,"idle":471916062,"irq":160000}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":14396343,"nice":0,"sys":6028171,"idle":473087468,"irq":120265}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":13305125,"nice":0,"sys":6063031,"idle":474143828,"irq":125468}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":13140828,"nice":0,"sys":6267140,"idle":474104015,"irq":105937}},{"model":"Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz","speed":2098,"times":{"user":13158484,"nice":0,"sys":8042703,"idle":472310781,"irq":111312}}],"osMemory":{"free":11642863616,"total":17179332608}},"headers":{"x-os-name":"win32","x-cypress-version":"4.12.1"}} and token: undefined

**Comment by jennifer-shehane** [comment] 2020-08-12 08:02
@Oaky78 Can you clarify what may have changed 'since yesterday'? Did you update Cypress or any other application/test code? Or make any changes to your Azure setup?

**Comment by jennifer-shehane** [comment] 2020-08-12 08:03
Yup, there is is - this looks to be a duplicate of #8251, which our API team is investigating.

closing as duplicate.

**Closed by jennifer-shehane** 2020-08-12 08:03 UTC
Labels: stage: awaiting response

**Comment by jennifer-shehane** [comment] 2020-08-12 17:40
Our engineering team has released a fix for this issue - of seeing the `Cannot find unclaimed instance for spec  ` error when running in Windows OS's. 

Please comment here or open a new issue if you continue to see this issue on new runs that are recorded to the Dashboard started after this comment.
