### ISSUE TITLE
Not able to run my tests on cypress on Windows.

### ISSUE THREAD

**Issue by LorenzoCervi** [cypress-io/cypress#14482] opened 2021-01-11 11:04 UTC
Hi!
I'm trying using cypress on Windows. I downloaded the software from official websites, it starts correctly with double click on app.
Once I opened Cypress, I drag my project folder, that has a different path from Cypress folder, into cypress test runner.
Then I try to run a test file that cypress finds correctly from my project folder, but it shows me this :  

> Error: Webpack Compilation Error
./cypress/integration/edit_spec.js
Module build failed (from C:/Users/asus/Downloads/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Using `babel-preset-razzle` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.

But in my package.json I have : 
`"scripts": {
"cypress:open": "NODE_ENV=production CYPRESS_API=plone CYPRESS_NO_COMMAND=0 cypress open"}`
but it still not working. 

Does anyone have any idea?

**Comment by jennifer-shehane** [comment] 2021-01-12 00:13
Duplicate of https://github.com/cypress-io/cypress/issues/6755

**Closed by jennifer-shehane** 2021-01-12 00:13 UTC
