### ISSUE TITLE
Enable Video only on Retry

### ISSUE THREAD

**Issue by eaustin** [cypress-io/cypress#16672] opened 2021-05-25 14:20 UTC
### What would you like?
Currently, we can disable video processing/compression to only occur on test failures.  Instead, or in addition, I propose a new configuration that would enable video recording only on retry of test.
```
"video": false
 "retries": {
    "runMode": 2,
    "openMode": 0,
    "video": true
  }
```
In the above configuration, all passing tests will not record a video, but if test is a valid failure, it would record the video on both re-tries. Additionally, if the first retry passes, there would still be a video recorded.

### Why is this needed?
Disabling video dramatically improves the performance of test runs. However, the video is extremely useful when trying to determine the cause of a failure. If a test fails and retries are configured it would be very nice if that is the only time a video is even recorded.

**Comment by jennifer-shehane** [comment] 2021-05-25 18:06
Duplicate of https://github.com/cypress-io/cypress/issues/16377

There's a workaround detailed in that issue: https://github.com/cypress-io/cypress/issues/16377#issuecomment-833679799

**Closed by jennifer-shehane** 2021-05-25 18:06 UTC

**Comment by eaustin** [comment] 2021-05-26 00:41
@jennifer-shehane - I looked at the workaround even before submitting this feature. However, I don't think it solves the problem. I'm disabling videos altogether and noticed a significant performance improvement. It would be nice though to capture the video if a test is retried only.

The workaround you propose is to delete the videos if the test passes and only process the videos. Currently, storing a lot of videos is not an issue for me.

Even for my case, this feature would not be high priority but I do think it would be useful for many use cases.

**Comment by jasonk** [comment] 2021-11-05 20:21
@jennifer-shehane The point this request was trying to make is that having Cypress record video of every test and then throw it away consumes an awful lot of resources, turning off the video recording make Cypress significantly faster, so being able to only record videos on retries would mean the tests would be much faster in most cases and only take the performance hit of video recording for tests that actually failed and had to be retried.

For anyone else who ends up here from Google and finding themselves disappointed, [Playwright support this](https://playwright.dev/docs/test-configuration/#record-video)

**Comment by AlexDaniel** [comment] 2022-04-20 19:32
While this ticket is closed, there is another one that is still open: https://github.com/cypress-io/cypress/issues/16681 (somehow I always find this ticket but not the other, so I'm leaving a link for others too)
