### ISSUE TITLE
Getting 404 page when logging in to application

### ISSUE THREAD

**Issue by eoin-roll-out** [cypress-io/cypress#21202] opened 2022-04-26 12:28 UTC
### Current behavior

I am currently facing an issue where I try to sign in to my application on cypress and receive a 404 error page response. I can log in fine when I do it manually within my own browser.
![Screenshot 2022-04-26 at 13 20 02](https://user-images.githubusercontent.com/60970259/165299236-fd7073e5-8cdb-44ee-8125-22de2312e891.png)
![Screenshot 2022-04-26 at 13 19 17](https://user-images.githubusercontent.com/60970259/165299240-9140cfb5-5e2a-4643-8dff-8b47ff656e29.png)

### Desired behavior

Allow me to login, the initial domain I navigate to in the test is different to the one that I am redirected to. I wonder if cypress is struggling to handle the domain change in the sign in process? It works okay in local as I believe localhost is present the whole time.

### Test code to reproduce
```js
describe('Login', () => {
  it('Login', () => {
    cy.visit('<applicatuinUrl>');
    cy.get('.login-submit').eq(1).should('be.visible').click();
    cy.contains('Add task or event');
  });
});
```

### Cypress Version

9.4.1

**Comment by mschile** [comment] 2022-04-26 23:13
In order to support multiple domains, you'll want to look into using [cy.origin](https://docs.cypress.io/api/commands/origin) in Cypress version 9.6.0.

**Comment by eoin-roll-out** [comment] 2022-04-27 08:01
@mschile do you have an example of how this could work for oidc as I am not explicitly navigating to another domain Instead I am being redirected through different domains. Maybe if I use cy.origin for the initial url?

**Comment by eoin-roll-out** [comment] 2022-04-27 08:17
My current attempt looks like this which is not working:
` it('Login', () => {
    cy.origin('https://idam.rest/', () => {
      cy.visit('https://domain2.rest/');
      cy.get('.login-submit').eq(1).should('be.visible').click();
    })
    cy.contains('Add task or event');
  });
});`

**Comment by eoin-roll-out** [comment] 2022-04-27 12:12
Okay so because of the way my application generates the first url I have moved to the code below:
`    cy.visit('https://domain.restOfUrl/');
      cy.get('form').first().invoke('attr', 'action').then((action) => {
      cy.origin(`https://idam.restOfDomain/${action}`, () => {
        cy.get('.login-submit').eq(1).should('be.visible').click();
      });
    });
    cy.contains('Add task or event');
  });`

This is giving me an error because it cannot find the .login-submit button, any ideas? Doesn't look like cy.origin will work for oidc to me

**Comment by mjhenkes** [comment] 2022-04-28 14:18
@eoin-roll-out, how does your application generate the first url?

Does visiting 'https://domain.restOfUrl/' automatically redirect you to 'https://idam.restOfDomain' if you are not logged in?

The action doesn't need to be part of the cy.origin call, we just need the origin, so conceivably you could do this:

```javascript
it('tests login', () => {
  cy.visit('https://domain.restOfUrl/');
  cy.get('form').first().invoke('attr', 'action'); // Redirects you log the 'https://idam.restOfDomain' origin
  cy.origin('https://idam.restOfDomain', () => {
    cy.get('.login-submit').eq(1).should('be.visible').click(); // Redirects you back to the 'https://domain.restOfUrl/' origin
  });
  cy.contains('Add task or event'); // this cy command is run agains the 'https://domain.restOfUrl/' origin.
})
```

**Comment by eoin-roll-out** [comment] 2022-05-04 08:48
@mjhenkes thanks for looking into this. Yes you are redirected to the idam url if you are not logged in. The 'action' value I am getting is the endpoint of the url and hence why I am getting it then using a .then to put the action in the url within origin. The issue I am having is that the button .login-submit is not found and can't be clicked within the cy.origin.

**Comment by mjhenkes** [comment] 2022-05-04 18:29
Based on the error it looks like you have successfully navigated to the expected origin, but we can't find the selector for some reason, have you verified that the page has loaded on that origin as expected?

If we hadn't navigated to the idam.xx origin i would have expected the timed out error to inform you that the origin the command was run on did not match the origin that the AUT was at.

**Comment by eoin-roll-out** [comment] 2022-05-09 17:06
The page loads fine in the initial instance, unsure how to verify the origin url I am using though?

**Comment by mjhenkes** [comment] 2022-05-09 21:08
Inside of the cy.origin block you can log out the current url using `cy.url()`
eg: 
```javascript
cy.origin('https://idam.xx', () => {
  cy.url().should('eq', 'https://idam.xx')
})
```

**Comment by mjhenkes** [comment] 2022-05-12 19:25
That indicates that the page was not navigated to.

take for example the following tests
```javascript
describe('tests', () => {
  it('navigates', () => {
    cy.origin('https://www.spacejam.com/', () => {
      // This isn't the only way to visit, clicking outside as you are doing in your tests is also valid,
      // This method is just more succinct for examples. 
      cy.visit('https://www.spacejam.com/1996/') 
      cy.url().should('eq', 'https://www.spacejam.com/1996/')
    })
  })

  it('does not navigates', () => {
    cy.origin('https://www.spacejam.com/', () => {
      cy.url().should('eq', 'https://www.spacejam.com/1996/')
    })
  })

  it('cannot find a selector', () => {
    cy.origin('https://www.spacejam.com/', () => {
      cy.get('selector')
    })
  })
})
```

The first test executes successfully. The second fails with `Timed out retrying after 4000ms: expected '' to equal 'https://www.spacejam.com/1996/'` which is kind of a terrible message that we should change.


<img width="882" alt="Screen Shot 2022-05-12 at 2 08 23 PM" src="https://user-images.githubusercontent.com/1588747/168152370-cfbdae35-407c-49c4-b029-c2c6f7bfc832.png">

And the third failure is what you'll see if you try to run commands when the AUT origin doesn't match the cy.origin commands origin. Note that it tells you that the command was run against an unexpected origin.

<img width="883" alt="Screen Shot 2022-05-12 at 2 08 30 PM" src="https://user-images.githubusercontent.com/1588747/168152041-fe776a1e-5038-4673-850f-f3f3fa59cc30.png"> 

I'm not sure what is happening in. your case, it seem we're getting conflicting error messages. it doesn't seem like you're in the correct origin, due to the url error, but you're also not seeing the cross origin part of the error message.

Do you have `chromWebSecurity` enabled? if so, try disabling it.

**Comment by mjhenkes** [comment] 2022-05-23 21:10
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-05-23 21:10 UTC
Labels: stage: awaiting response, experiment: origin
