### ISSUE TITLE
Cypress is not loading files from cache what leads to memory issues

### ISSUE THREAD

**Issue by achelonmm** [cypress-io/cypress#4195] opened 2019-05-15 11:38 UTC
### Current behavior:

![patron 502](https://user-images.githubusercontent.com/41155189/57772612-21b4e580-7716-11e9-8883-e5391a941ea5.png)
I am working on a test suite and I am facing a serious problem.

On this website, there is a 1.4Mb file that is downloaded and stored in cache and from then onwards, whenever you refresh the page or visit again, if that file is in cache, the website reads it from there.

This happens when I work with Electron and Chrome manually, however, whenever I execute the tests on Cypress, it keeps downloading the file every time eventually reaching an out-of-memory crash and pausing the execution.

![image](https://user-images.githubusercontent.com/41155189/57772720-7a847e00-7716-11e9-828d-13e0cb92b8d5.png)

### Desired behavior:

Cypress is not reading files from cache and keeps downloading files for every test.

### Versions

Electro 59
Windows 10
Cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-05-22 08:47
Changing the cacheing strategy is part of our larger 'LifeCycle Events' epic: https://github.com/cypress-io/cypress/issues/686

**Comment by jashkenas** [comment] 2019-08-22 21:52
Hi folks,

We have the same problem (Cypress 3.4.1, on Mac OS X), which became much more noticeable after we started using code-splitting in our application, causing every test to re-download all of the JavaScript chunks for our app, over and over again: 

![image](https://user-images.githubusercontent.com/4732/63552288-2692ed80-c4ec-11e9-8748-79632ee4f205.png)

Is there any way to get Cypress not to clear the browser disk cache for JS in 3.4.1? Or do we need to wait for the (almost 2 year old) Lifecycle Events epic to be completed in a future release?

**Comment by jennifer-shehane** [comment] 2020-05-12 06:14
Duplicate of #686

**Closed by jennifer-shehane** 2020-05-12 06:14 UTC
