### ISSUE TITLE
Cypress performance issues

### ISSUE THREAD

**Issue by Jacek-fstack** [cypress-io/cypress#8297] opened 2020-08-17 11:52 UTC
Since about version 4.11 our cypress has become insanely slow.
It hogs network like crazy [any page I'm trying to load, like this github post is taking forever when tests are running]
Failed video compression takes AGES
it logs progress every few seconds, and all I'm seeing are 1-5% increments in that time
``` 
Started processing:  Compressing to 32 CRF
    Compression progress:  8%
    Compression progress:  16%
    Compression progress:  22%
    Compression progress:  27%
    Compression progress:  32%
    Compression progress:  37%
    Compression progress:  40%
    Compression progress:  44%
    Compression progress:  48%
    Compression progress:  52%
    Compression progress:  56%
    Compression progress:  60%
    Compression progress:  63%
    Compression progress:  67%
    Compression progress:  70%
    Compression progress:  72%
    Compression progress:  74%
    Compression progress:  77%
    Compression progress:  79%
```
Typing has been insanely slow as well.
Tests in general got exponentially longer.
Is it only our instance or did anyone else experience it?
I'm not really sure where to look for a fix for this.
Anything you guys can point me to would help! thanks!
Also: headless seems to be WAY SLOWER then the non-headless, which is already really slow.
All in CHROME - electron doesn't seem to be affected by this.
### Versions

4.11, 4.12

**Comment by jennifer-shehane** [comment] 2020-08-18 05:59
There have not been any reports of performance issues starting in 4.11. 

- Can you downgrade to 4.10? Does this resolve the slowness issue? Tracking down why the performance suddenly changed will be most helpful.
- There may be a lack of resources on the system running the tests - [You can log memory and cpu usage](https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage) to see if the processes are maxed. If so, you'll want to increase the resources on the machine.
- You could also collect all cypress logs in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode - not sure if that will be helpful here or not.

**Comment by PawelWesolowski** [comment] 2020-08-18 08:42
I have also experienced the "slowness". It is related to Chrome update and not Cypress update.
I am currently updating our Cypress from 4.1 to 4.12.1 and my colleague is having same issues on his "4.1" branch. I am on Mac and he is on Windows.
What we see is that memory usage in the Cypress' Chrome instance increases with every test (e.g. up to 10gb). It makes the tests run slower since the whole machine is running out of memory.

**Comment by Jacek-fstack** [comment] 2020-08-18 09:51
I agree that it most likely is a chrome issue - when I downgrade to even 4.8, everything is just as bad. But there's just no easy way to downgrade chrome.

**Comment by jennifer-shehane** [comment] 2020-08-18 12:08
We have a tool to help track down previous versions of Chromium to download so you can run Cypress within them and track down any newer bugs: https://chromium.cypress.io/

I wouldn't really be able to track down a Chrome bug without being given a reproducible example to run against to see this specific performance issue.

**Comment by Jacek-fstack** [comment] 2020-08-18 12:52
I was able downgrade for a few tests [stupid chrome updates itself even with auto updates turned off]. and 100% it was waaaay snappier, faster and more reliable.... until it updated to 84 again.

**Comment by Jacek-fstack** [comment] 2020-08-20 10:02
FYI 5.0 is experiencing the same slowness
a) in typing, the more consecutive tests I run (doesn't have to be run in a single run, I can just fire them manually one by one)
b) headless chrome is about 1.5 times slower, sometimes more

**Comment by alexmonteirocastro** [comment] 2020-08-20 13:47
I haven't been able to upgrade to higher versions since 4.8.0 because of slow typing which causes my tests to fail. 

I tried the 4.12.1 and it seems that the slow typing still persists, however, it only happens on the first time the tying command is executed. On subsequent typing commands, the typing occurs at the normal speed (fast). I have witnessed this in both **headed** and **headless** test runs. 

Regarding the issues with CPU usage:

Here is CPU usage for **4.12.1**

![image](https://user-images.githubusercontent.com/35965983/90777271-783aa780-e2fb-11ea-8241-75b169a8b8c7.png)

CPU usage for **4.8.0**

![image](https://user-images.githubusercontent.com/35965983/90777307-85579680-e2fb-11ea-97d8-d88d47f8eeda.png)

As we can see in both cases the CPU usage is quite high for chrome browser.

**Comment by Jacek-fstack** [comment] 2020-08-20 14:01
@alexmonteirocastro hmm so it doesn't slow down in 4.8 for you? That's odd, because the only thing that SEEMED to help was when I downgraded my chrome for a few seconds. 4.8 with newest chrome is behaving just like on 4.12.
And my CPU usage is ramping up to even 1000 in some cases.

**Comment by Jacek-fstack** [comment] 2020-08-24 08:02
@csvan nope, I'm on mac and running from my host

**Comment by srdjanprole** [comment] 2020-08-25 10:18
This is a huge problem... with cypress 5.0.0 we have like 2k requests and with 4.8.0 we have like 100k requests...

**Comment by nicolajv** [comment] 2020-08-27 14:20
After some research it looks like this issue started in 4.9 and is related to asset requests being cancelled and retried a bunch of times. We see it in the dev console on both electron and chrome. Downgrading to 4.8 or using Firefox we do not see this issue.
![image](https://user-images.githubusercontent.com/30402684/91454401-31abf680-e881-11ea-8cf4-a49e40c3b05a.png)
I replicated the issue in a test in this repo:
https://github.com/nicolajv/cypress-chromium-issue

**Comment by srdjanprole** [comment] 2020-08-28 08:35
> After some research it looks like this issue started in 4.9 and is related to asset requests being cancelled and retried a bunch of times. We see it in the dev console on both electron and chrome. Downgrading to 4.8 or using Firefox we do not see this issue.
> ![image](https://user-images.githubusercontent.com/30402684/91454401-31abf680-e881-11ea-8cf4-a49e40c3b05a.png)
> I replicated the issue in a test in this repo:
> https://github.com/nicolajv/cypress-chromium-issue

@jennifer-shehane can you maybe have a look into it?

**Comment by mike-tdsy** [comment] 2020-09-01 18:23
I am experiencing the same issue. We are having to rollback our upgrade.

**Comment by nicolajv** [comment] 2020-09-03 08:12
Also affects 5.1

**Comment by sshaar08** [comment] 2020-09-03 19:10
👍  ill follow this thread for a resolution I'm seeing the same issue re: clicks etc

**Comment by flotwig** [comment] 2020-09-08 20:55
Hi everyone, I have been reading through this thread, and it sounds like the main issue is that CPU is being maxed out to 100% for the duration of the test run. This can lead to other strange behavior, including requests being canceled, Cypress commands taking too long and timing out, and video compression being throttled to take a really long time.

There was a CPU performance regression introduced in version 4.9.0 of Cypress that has been identified in #8012 and will be fixed in the *next* release of Cypress. That is probably the reason behind the issues described in these comments.

Since this issue is effectively a duplicate of #8012, I'm going to close this thread. If, after upgrading to a version of Cypress newer than 5.1.0, your issue is not fixed, please open a new issue describing the problem and we can investigate further.

**Closed by flotwig** 2020-09-08 20:55 UTC
Labels: stage: awaiting response, type: performance 🏃‍♀️
