### ISSUE TITLE
Persist previous "Search Specs" when navigating to specs and back

### ISSUE THREAD

**Issue by jidma** [cypress-io/cypress#22962] opened 2022-07-27 22:04 UTC
### What would you like?

We have a lot of specs in our project, and when testing a particular file I use the filter to get straight to the spec or folder I'm testing:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/2295247/181379678-6a939347-9bae-4aa3-82bc-dec2aff1f726.png">

Once I'm done with the selected spec, I go back to the previous list by clicking the "specs" button on the left side:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/2295247/181380073-4d9f5d76-83c0-4aad-a26c-d5d9b24af966.png">

When I'm back to the Specs list, the prevously entered filter is cleared:

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/2295247/181380188-5718b526-a3e6-4f8f-b201-74f4efa4e8f8.png">

It would be easier if the filter is still there so we don't have to type it again.

**Comment by marktnoonan** [comment] 2022-07-28 21:35
Thanks @jidma, I'm going to close this as a dupe of #21837 - the work for that issue and a few related items should merge over the next few weeks.

In the mean time I'd call your attention to the new (as of Cy 10) inline specs list in the spec runner, which lets you navigate between specs without losing any state. If you haven't seen that yet it might be useful for the time being until the other work lands:

![](https://user-images.githubusercontent.com/8340719/174787529-97226120-bcf5-4142-933d-f5ddd6c5de2a.png)

**Closed** 2022-07-28 21:36 UTC
Labels: stage: investigating

**Comment by jidma** [comment] 2022-07-28 21:43
@marktnoonan Awesome thanks! I haven't seen that and it's indeed helpful in my situation
