### ISSUE TITLE
cy.wait('@route') isn't waiting for the route

### ISSUE THREAD

**Issue by KatieMFritz** [cypress-io/cypress#9233] opened 2020-11-18 00:22 UTC
### Current behavior
A new test has an `afterEach` hook that calls a custom command. Test code below.

I have a `cy.wait('@countElements`) waiting for a POST request (`countElements`) to resolve. The following step fails if it's executed before resolution.

I can see that the XHR happens a bit later, but the test doesn't wait.

<img width="821" alt="Screen Shot 2020-11-17 at 7 16 22 PM" src="https://user-images.githubusercontent.com/7085184/99465987-7b006500-2909-11eb-8d6e-6df6eb6625b7.png">

I tested by changing the awaited route in step 5 to something that doesn't even load on that page, and I got the same false positive behavior. No timeout, no failure, just went right past it. 🙃

### Desired behavior
I expect Step 5, `@countElements`, to resolve before step 6 begins.

### Test code to reproduce

```js
Cypress.Commands.add('deleteMembership', (email) => {
  // Save routes
  cy.server()
  cy.route('POST', '/index.php?p=admin/actions/element-indexes/count-elements&v=**').as('countElements')

  // Select all memberships for this user
  cy.visit('/admin/commerce/orders')
  cy.wait('@countElements')
  cy.findByPlaceholderText(/Search/).type(email + '{enter}')
  cy.wait('@countElements')
  cy.findAllByText('Membership').parent().within(() => {
    cy.get('.checkbox').click({multiple:true})
  })
  // do other stuff...
})
```

From the actual spec file:
```js
    afterEach(() => {
      cy.deleteMembership(email)
    })
```

### Versions
- Cypress 5.6.0
- Browser: Chrome 86
- Operating System: MacOS Catalina

**Comment by jennifer-shehane** [comment] 2020-11-18 04:07
Are you sure there is not a previously matching request for `@countElements` above this screenshot? 

Can you provide a reproducible example? We won't be able to look into what's causing this without that. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by KatieMFritz** [comment] 2020-11-18 15:36
Yes, I'm sure there's not an earlier matching request.

> I tested by changing the awaited route in step 5 to something that doesn't even load on that page, and I got the same false positive behavior. No timeout, no failure, just went right past it. 🙃

I'll try to isolate it into a reproducible example.

**Comment by paddotk** [comment] 2021-12-16 11:34
This is still an issue. The only workaround for this that works for me is putting all subsequent code in the `.then(() => {` of a request, but that doesn't make for logical, readable code. As its name suggests, `cy.wait()` should wait for the request to be resolved.

**Comment by emilyrohrbough** [comment] 2021-12-16 14:14
@paddotk Are you able to provide a reproducible example?

**Comment by paddotk** [comment] 2021-12-23 12:17
@emilyrohrbough Sure. Assume we have an interception for an API call called `@getEvents`, and somewhere in the Cypress needs to check something in the response of the API call, or the frontend uses the response to trigger an update.

With the following attempts:
```
// Attempt 1
const response = cy.wait('@getEvents');
expect(response.body).to.contain('hello');
```

```
Attempt 2
let response;
cy.wait('@getEvents').then((res) => {
  response = res;
});
expect(response.body).to.contain('hello');
```
```
// Attempt 3 (workaround)
cy.wait('@getEvents').then((res) => {
  // The rest of the test
});
```

Only the third one works, as everything next happens in the callback, But since we have multiple of such situations, we have to do a lot of callback nesting which is not really 'neat'

**Comment by flotwig** [comment] 2022-12-15 19:34
`cy.route()` was removed in [Cypress 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0), please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept) instead. Closing this issue since the relevant API has been deprecated and removed.

**Closed by flotwig** 2022-12-15 19:34 UTC
Labels: stage: backlog
