### ISSUE TITLE
Assertion fails if scrollLeft property has 0 value

### ISSUE THREAD

**Issue by Mykhail-Lukashevych** [cypress-io/cypress#1491] opened 2018-03-22 22:24 UTC
- Operating System: macOS High Sierra 10.13.3
- Cypress Version: 2.1.0
- Browser Version: Chrome 65

### Current behavior:
Assertion fails if scrollLeft property has 0 value.

### Desired behavior:
Assertion should passed correctly

### How to reproduce:
```js
cy.get('.view').should('have.prop', 'scrollLeft', 0) 
```
<img width="389" alt="screen shot 2018-03-22 at 11 20 57 pm" src="https://user-images.githubusercontent.com/6429407/37801699-da20760e-2e27-11e8-8d54-89f50d3313b9.png">

### Additional Info (images, stack traces, etc)
**Command**:   assert
**Actual**:    0
**Expected**:  0
**Subject**:   jQuery.fn.init(1)
&nbsp;&nbsp;&nbsp; 0: div.view.ng-scope.release-flow: document
&nbsp;&nbsp;&nbsp; length: 1
&nbsp;&nbsp;&nbsp; selector: ".view"
**Message**:   expected <div.view.ng-scope.release-flow> to have property scrollLeft with the value **0**, but the value was **0**
**Error**:     AssertionError: expected '<div.view.ng-scope.release-flow>' to have property 'scrollLeft' with the value **0**, but the value was **0**

Looks like the problem with 0 value itself, because after changing the scroll position assertion works fine:
```js
cy.get('.view').scrollTo('right');
cy.get('.view').should('have.prop', 'scrollLeft', 2507)
```
<img width="390" alt="screen shot 2018-03-22 at 11 17 36 pm" src="https://user-images.githubusercontent.com/6429407/37801614-864cc65e-2e27-11e8-9284-39571e1b49f1.png">

**Comment by jennifer-shehane** [comment] 2018-03-23 15:41
Yes, I think there is something strange going on with the 3rd argument. I will have to dive deeper into why this is happening.

A workaround is to split the assertions up:
```
cy.get('.view').should('have.prop', 'scrollLeft').and('eq', 0)
```

<img width="597" alt="screen shot 2018-03-23 at 11 38 47 am" src="https://user-images.githubusercontent.com/1271364/37838656-e751ce10-2e8e-11e8-8ee8-20f97fa3422a.png">

**Comment by jennifer-shehane** [comment] 2018-03-23 15:47
I suspect the culprit is likely in our chai-jquery overrides here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/chai_jquery.coffee#L1

You could likely easily write a failing test and then fix it. Tests here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/commands/assertions_spec.coffee#L1

**Comment by brian-mann** [comment] 2018-03-25 15:00
I believe this is a duplicate of this issue https://github.com/cypress-io/cypress/issues/831 which was fixed by this PR: https://github.com/cypress-io/cypress/pull/1480

**Comment by brian-mann** [comment] 2018-03-25 15:01
The problem is `0` is falsy, just like `""` in the other issue. It's been fixed.

**Closed** 2018-03-25 15:02 UTC
Labels: first-timers-only, stage: investigating, type: bug

**Comment by jennifer-shehane** [comment] 2018-03-26 15:03
@brian-mann Did you add a test for this `0` case?
