### ISSUE TITLE
Getting table cells returns the whole row

### ISSUE THREAD

**Issue by dthomason** [cypress-io/cypress#9064] opened 2020-11-03 00:07 UTC
Found in version 5.5.

Issue: When `getting` a table's cell assertions or actions return the whole row.

Details:

The code I used in version `4.0.2` that worked before upgrading to `5.5`
```js
export function getTableCell(
  tableId: string,
  column: string,
  row: number,
): Cypress.Chainable {
  return cy
    .getByTestId(tableId)
    .find('tbody>tr')
    .eq(row)
    .within(() => {
      cy.getByTestId(column);
    });
}
```
This would enable me to do things like the following
```js
getTableCell(tableId, column, row).should('have.text', 'only the cell's text')
```
Now I receive failures because it smashes the whole row's text together.  Does this for things like `click()` so it's unable to actually click the proper item.

**Comment by jennifer-shehane** [comment] 2020-11-03 05:10
This change of behavior was introduced in 5.4.0. Likely with this PR: https://github.com/cypress-io/cypress/pull/8699

This is a duplicate of https://github.com/cypress-io/cypress/issues/8873, where it is unexpected that the `.within()` is returned from a custom function/command as opposed to the inner value within within.

### 5.3.0

<img width="616" alt="Screen Shot 2020-11-03 at 11 31 27 AM" src="https://user-images.githubusercontent.com/1271364/97951322-2f59a180-1dc8-11eb-96ab-edb53bb5ba51.png">

### 5.4.0

<img width="551" alt="Screen Shot 2020-11-03 at 11 33 48 AM" src="https://user-images.githubusercontent.com/1271364/97951409-79428780-1dc8-11eb-9052-37f5de34e7d9.png">

**Closed by jennifer-shehane** 2020-11-03 05:10 UTC
