### ISSUE TITLE
mocha type definitions conflict with @types/jest (AGAIN)

### ISSUE THREAD

**Issue by covertbert** [cypress-io/cypress#7520] opened 2020-05-28 21:02 UTC
### Current behavior:

Type conflicts with mocha and jest - mocha types from cypress are polluting my jest test files

<img width="1258" alt="Screenshot 2020-05-28 at 21 56 43" src="https://user-images.githubusercontent.com/8471383/83193054-58e21300-a12e-11ea-86c9-75e10e724008.png">

### Desired behavior:

I hope one day that Cypress and Jest can actually work together in a TS project without hacky workarounds (or even with the hacky workarounds that used to work but don't seem to anymore)

### Test code to reproduce

Steps:
- `git clone git@github.com:covertbert/bertie-blackman.git`
- `git checkout broken-types-example`
- `yarn`
- `yarn test` or `yarn tsc:repo`

### Versions

`"cypress": "4.7.0",` MacOS

**Comment by jennifer-shehane** [comment] 2020-05-29 12:00
Duplicate of #7435

**Closed by jennifer-shehane** 2020-05-29 12:00 UTC
