### ISSUE TITLE
I am integrating cypress tests with Jenkins pipeline. I have used cypress/included:8.5.0 docker image

### ISSUE THREAD

**Issue by DeepakB01** [cypress-io/cypress#23753] opened 2022-09-09 14:48 UTC
I am integrating cypress tests with Jenkins pipeline. I have used cypress/included:8.5.0 docker image
We are running  jenkins as non-root as we dont have access for root.

But we are getting following exception on Jenkins Console - 

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, mkdir '/root/.config/Cypress/cy/production'
    at Object.mkdirSync (fs.js:987:3)
    at Object.mkdirsSync (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
at createFile (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/logger.js:23:6)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/logger.js:42:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/server-base.js:20:42)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/server-ct.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/project-base.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/open_project.js:11:24)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/lib/cypress.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/index.js:39:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/.cache/Cypress/8.5.0/Cypress/resources/app/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
    at Module._load (internal/modules/cjs/loader.js:747:15)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Please help me resolve this issue.

_Originally posted by @DeepakB01 in https://github.com/cypress-io/cypress/discussions/23752_

**Comment by nagash77** [comment] 2022-09-09 19:52
Hello @DeepakB01 .  It looks like you created an issue from a discussion.  We ask that people use the issue creation template when entering an issue to ensure you are including all the information we will need to best troubleshoot this issue.  I am going to close this issue and ask that you you submit this problem via our issue template.  Keep in mind we will need a reproducible example of code in order to investigate this fully.

**Closed by nagash77** 2022-09-09 19:52 UTC
