### ISSUE TITLE
 Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by redpiggypaul** [cypress-io/cypress#2156] opened 2018-07-16 06:46 UTC
### Is this a Feature or Bug?
Bug

### Current behavior:
Cypress Helper[4350:75408] Couldn't set selectedTextBackgroundColor from default ()
With Chomre Version 67.0.3396.99 (Official Build) (64-bit) in MAC.
 This work well in last week, I don't know what happened, maybe the Chrome auto update in the weekend.
CYPRESS Version, Version 3.0.2 (3.0.2)
I install the CYPRESS with : cnpm install cypress --save-dev in the project path, it works well in last week.

**Comment by jennifer-shehane** [comment] 2018-07-16 15:21
Duplicate of https://github.com/cypress-io/cypress/issues/1996

**Closed by jennifer-shehane** 2018-07-16 15:21 UTC
