### ISSUE TITLE
Developer tools opens in 0x0 window

### ISSUE THREAD

**Issue by kolyaventuri** [cypress-io/cypress#3835] opened 2019-03-27 16:48 UTC
### Current behavior:
When the Chrome DevTools window is set to "Undock in separate window" mode, rather than pinned to one side of the browser window, it opens in a 0x0 (or practically 0x0) window at the top right of the leftmost monitor. It can be expanded however, but the developer has to notice it's there in the first place.

![image](https://user-images.githubusercontent.com/972446/55094984-a10e2d00-5074-11e9-82ba-b5b857bf9f72.png)

### Desired behavior:
The DevTools window should open with a defined width / height, to make it easy to access. It is extremely useful to have the dev tools be on a separate monitor than where the tests are running, so you can still easily see the test run visually.

### Steps to reproduce: (app code and test code)
- Start running a test
- Open the DevTools (either through View > Developer > Developer Tools, Right Click > Inspect Element, or other method)
- Use the top right menu to change the "Dock side" to "Undocked into separate window"
- See (or don't see) DevTools window at effectively 0x0 in top left corner.

### Versions
- Cypress 3.2.0
- Chrome 73
- macOS 10.14

**Comment by jennifer-shehane** [comment] 2019-03-28 05:39
Duplicate of https://github.com/cypress-io/cypress/issues/2497 Any help to track this down would be appreciated.

**Closed by jennifer-shehane** 2019-03-28 05:39 UTC
