### ISSUE TITLE
Cypress Will not load anything within Chrome

### ISSUE THREAD

**Issue by JPHamlett1993** [cypress-io/cypress#3832] opened 2019-03-27 15:01 UTC
### Current behavior:

When I run a test in Cypress it loads the Chrome Frame but nothing within it

![image](https://user-images.githubusercontent.com/11742812/55086898-2bf02700-5077-11e9-946c-3f38a34b5315.png)

### Desired behavior:
The tests run

They run if I go down to 3.1.5

### Versions
3.2.0, Mac OS, Installed, Chrome

**Comment by Niceplace** [comment] 2019-03-27 19:08
Same behavior for me, I have to stick with 3.1.5 because 3.2.0 never works.

I didn't dig into the issue too much but I tried using different browsers (chrome, chromium, electron) and the behavior is always the same. I see that in the logs when trying to start a simple test (visiting one URL only):

```
GET /__/ 200 27.290 ms - -
GET /__cypress/runner/cypress_runner.css 200 5.645 ms - -
GET /__cypress/runner/cypress_runner.js 200 6.738 ms - -
GET /__cypress/static/favicon.ico 200 1.384 ms - -
HEAD / 500 566.713 ms - -
HEAD / 500 573.216 ms - -
HEAD / 500 582.971 ms - -
GET /__/ 200 26.772 ms - -
GET /__cypress/runner/cypress_runner.css 200 1.769 ms - -
GET /__cypress/runner/cypress_runner.js 200 1.334 ms - -
```

**Comment by jennifer-shehane** [comment] 2019-03-28 05:37
We'll need a reproducible example of this in order to look into it. Is this only happening on a specific url you are visiting? Does it also happen when trying to test against `https://example.cypress.io` for example?

**Comment by mekhami** [comment] 2019-03-28 15:54
@jennifer-shehane you were given the answer to this problem in the previous issue about it here:

https://github.com/cypress-io/cypress/issues/1872#issuecomment-445581050

I don't understand why it was ignored.

**Comment by JPHamlett1993** [comment] 2019-03-28 16:09
I fixed mine, I had localhost commented out in host file

**Comment by jennifer-shehane** [comment] 2019-03-29 05:30
@mekhami The proxy-server issue documented was already fixed in our 3.1.5 release as explained here: https://github.com/cypress-io/cypress/issues/1872#issuecomment-450807452 

We suspect this is a different issue. Can you confirm the issue outlined in the comment is still happening in 3.2.0?

**Comment by mekhami** [comment] 2019-03-29 05:31
It is still happening in 3.2.0, yes.

**Comment by jennifer-shehane** [comment] 2019-03-29 05:39
@mekhami Can you give me the exact steps to replicate this behavior? I am running `cypress open` with Cypress version 3.2.0 and do not see this behavior. I would love to track the issue down

Chrome versions tried and not seeing behavior:
- 72.0.3605.0
- 73.0.3658.0
- 73.0.3683.86
- 75.0.3747.0

**Comment by Niceplace** [comment] 2019-04-18 20:12
I solved my issue ! I was not able to reset to the error behavior however so that's a bit strange, it was something on my computer I assume.

- Opened my `/etc/hosts` file and made sure that only these lines were present / uncommented

```
# Static table lookup for hostnames.
# See hosts(5) for details.
255.255.255.255    broadcasthost
127.0.0.1             localhost
```

After changing the file the tests started working right away, reverting to its initial state didn't bring back the error.

I tried making a npm script with `cypress clean && cypress install` to make sure nothing was stuck in the cache, it didn't change anything for me but maybe it can help others.

I can successfully run tests with any browser using cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-04-24 15:53
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Closed by jennifer-shehane** 2019-04-24 15:53 UTC
Labels: type: regression
