### ISSUE TITLE
Gitlab CI parallel run hangs sometimes

### ISSUE THREAD

**Issue by nanoflat** [cypress-io/cypress#3567] opened 2019-02-22 17:16 UTC
### Current behavior:
We are running 20 parallel jobs on GitlabCI. A week ago we started noticing that 3 out of 20 jobs hangs.
We are running tests on Chrome 72. Looks like this issue is not happening when using bundled Electron browser

### Desired behavior:

debug logs from runs: 
run 1 https://gist.github.com/nanoflat/2594f6a76a1ad725a039795b169dacc5
run 2 https://gist.github.com/nanoflat/fad95bf3096abbdc8ce48f16e81cc168

### Versions
OS:
 Linux Debian - 8.11
Browser:
 Chrome 72.0.3626.109
Cypress:
v3.1.5

**Comment by jbpallingayan** [comment] 2019-02-26 06:20
[related to this](https://github.com/cypress-io/cypress/issues/2265)

it happens also from us. there's no answer came from them sad.

**Comment by jennifer-shehane** [comment] 2019-02-27 19:21
Hey @nanoflat, this may be related to the other issue as mentioned. We will need a reproducible example to look into this, since the logs are not revealing anything helpful. 

Can you provide an example of test code + app code we can run to see this bug?

**Comment by jennifer-shehane** [comment] 2019-04-25 08:39
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 08:39 UTC
Labels: stage: needs information
