### ISSUE TITLE
Cannot fire hover event by CSS

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress#6198] opened 2020-01-20 22:33 UTC
### Current behavior:

The current documentation points out that `show("trigger", "mouseover")` or `trigger("mouseover")` are used for hovering over certain DOM elements:

https://docs.cypress.io/api/commands/hover.html
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__hover-hidden-elements

When the hover event in the CSS, Cypress does not fire the event.  Please see the test code below.  I have not found a workaround to fire the hover event.

### Desired behavior:

Either `show("trigger", "mouseover")` or `trigger("mouseover")` works on all sorts of hovering or mouseover activities.

### Test code to reproduce

git clone https://github.com/clarmso/force-element-state-cypress
npm i
npm run start
npm run open

### Versions

Cypress 3.8.2
Ubuntu 16.04 LTS
Chrome 79 (79.0.3945.130)

**Comment by jennifer-shehane** [comment] 2020-01-21 04:35
Using `.trigger()` will only trigger the actual events in JavaScript and has zero effect on the CSS effects. This is a duplicate of https://github.com/cypress-io/cypress/issues/10 which outlines the challenges and work necessary to support simulating hover effects in CSS. 

Although I don't think this is made very clear in the .hover doc, so I've opened an issue to add clarification directly there https://github.com/cypress-io/cypress-documentation/issues/2412

**Closed by jennifer-shehane** 2020-01-21 04:35 UTC
