### ISSUE TITLE
Seems `cypress ci` does not respect or handle integrationFolder parameter

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#164] opened 2016-06-13 18:06 UTC
When passing custom path to the integration folder (to allow running just some tests), cypress just initializes the Kitchen Sink example and runs its own tests, not mine.

**Comment by brian-mann** [comment] 2016-06-13 18:24
What's happening here is that when cypress does not detect any cypress tests it's seeding the example kitchen sink and running those tests.

We need to do two things better:

1. Never seed tests when running `cypress ci`
2. If Cypress cannot detect any tests it should error and indicate the exact path it searched where there were no tests.

However this was likely caused by running `cypress ci` in the wrong `cwd` and if you hypothetically update this (or pass `--config` options) it will work correctly.

**Comment by jennifer-shehane** [comment] 2019-02-01 11:02
Closing - added suggestion about never seeding when running `cypress ci` to https://github.com/cypress-io/cypress/issues/619

**Closed by jennifer-shehane** 2019-02-01 11:02 UTC
Labels: cli, type: enhancement
