### ISSUE TITLE
Feature Request: Enhance Stack traces to display the caller of a custom command

### ISSUE THREAD

**Issue by vivekKodira** [cypress-io/cypress#19506] opened 2021-12-31 15:42 UTC
### What would you like?

We use custom commands to wrap common steps and to encapsulate test logic related to 3rd party libraries. 

When a custom command fails, the stack trace only displays it and nothing else. Please consider improving the logic to also display the caller.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/719368/147830904-8b497283-1b9e-4a44-92eb-20c9937acf2c.png">

### Why is this needed?

Knowing the line in the test spec will allow me to find the cause of the issue sooner. Since custom commands are tried and tested, seeing only them in the stack trace is useless.

**Comment by jennifer-shehane** [comment] 2024-01-24 01:41
Duplicate of https://github.com/cypress-io/cypress/issues/15581

**Closed by jennifer-shehane** 2024-01-24 01:40 UTC
Labels: type: enhancement
