### ISSUE TITLE
Command Log auto-disables auto-scrolling during test run (Cypress 5.0 + issue)

### ISSUE THREAD

**Issue by symon-skelly** [cypress-io/cypress#8646] opened 2020-09-23 09:10 UTC
### Current behavior
On some occasions the autoscroll of the Command Log will automatically disable itself, this causes the screenshots / videos of failed tests to become less useful as I am unable to see where the test actually failed using this information.

### Desired behavior
Never automatically disable the autoscrolling of the Command Log, only ever disable autoscrolling if the user has actually clicked the button to disable the autoscroll.

### Versions

Cypress 5.0+ (never had issues pre 5.0). Windows 10 (local) with Chrome 85 , Linux (CI) with Chrome 84

**Comment by jennifer-shehane** [comment] 2020-09-29 05:35
This is happening only when you run via `cypress run`? 

Do you tests have a lot of tests / commands? Like does it look like in the video that the UI may be freezing?

Can you provide a video of this behavior?

**Comment by jennifer-shehane** [comment] 2020-10-15 00:36
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-10-15 00:36 UTC
Labels: stage: needs information

**Comment by dlabrecque-uzinakod** [comment] 2022-02-04 01:54
Hi,
This behavior also happens in our environment. We are using cypress 9.3.1 with cypress-cucumber-preprocessor. 
It happens with cypress open and cypress run. 
It also happens on our CI/CD pipeline which is a problem because we can't rely on the screenshot or the video to troubleshoot because it doesn't show the error which is at the end of the scroll.
I tried to make a video of it. I have it available if you want. It is weird because it appears to happen at the same place in a test, but it does not happen on every run.
In the video I recorded, it seems to happen right after a page load when there are a lot of backend requests.
I ran it with a spec file where only one test runs and it happens approx 2 times out of 3.
I don't understand the used case where one would like the cypress command log to not auto-scroll. Maybe this toggle should be removed along with the feature.
