### ISSUE TITLE
Going offLine and onLine not working in cypress 

### ISSUE THREAD

**Issue by senthkum** [cypress-io/cypress#23849] opened 2022-09-16 03:59 UTC
### Current behavior

This was working fine with the 6.5.0 version and I upgraded to 8.5.0, 9.7.0, and 10.7.0 with all these versions toggling network is not working.
I was using the same code earlier and was working perfectly. but know we can change the network to offLine but cannot toggle back to onLine and this is impacting a few test cases. Is there a work around or a fix for this
https://www.cypress.io/blog/2020/11/12/testing-application-in-offline-network-mode/

### Cypress Version

10.7.0

### Node version

16.14.0

### Package Manager

yarn

### Package Manager Version

12.16.2

### Operating system

Mac

### Operating System Version

mac

**Comment by nagash77** [comment] 2022-09-16 18:17
@senthkum Can you provide us with the tests you are using and seeing this problem?  We will need that to be able to help you further.

**Comment by senthkum** [comment] 2022-09-19 06:19
I am attaching the SS and piece of code, I have tried it in both chrome and Electron browsers.
Step 1: I login to the application and wait for the page to load.
Step 2: I set the network to offline and added a assertion to it
Step 3: now I select an item from the link and it will display an error page
Step 4:I set the network to onLine and added an assertion to it
Step 5: I click on Try again button and it should load the page successfully
Step 6: The above steps repeat for multiple links and verify the error page is displaying the correct link chosen.

Even though in the Electron browser if the assertion is passed, when it clicked on the Try again button the page fails to load.
All these were working in the earlier version (6.5.0)

![code](https://user-images.githubusercontent.com/46837197/190958501-661e1918-b508-4eea-b026-131e015c1bb5.JPG)

Electron browser:
![Electron-1](https://user-images.githubusercontent.com/46837197/190959153-095febc7-0111-41c8-a215-1c33a1ef54cc.jpg)
![Electron-2](https://user-images.githubusercontent.com/46837197/190959156-ce37d937-3144-4d4a-b345-42fb93ff7d3d.jpg)

Chrome browser:
![Chrome-1](https://user-images.githubusercontent.com/46837197/190959196-61e953b6-bcc6-4074-8b44-c17fd456a8ca.jpg)
![Chrome-2](https://user-images.githubusercontent.com/46837197/190959197-3d97b81c-aace-424d-bedc-2b9213270cf3.JPG)

**Comment by ZachJW34** [comment] 2022-09-20 15:37
Closing as duplicate of #17723. Throwing a thumbs up on that issue will let us know that more users are interested in this feature and help push it along.

Tinkering a bit, you can stub the `navigator.onLine` which might be able to suit your use case (also some intercepts/force404). Here is a code snippet that might help (document is listening to `window.addEventListener("offline", ...)`:

```js
let originalOnLine;

const goOffline = () => {
  cy.log("offline");
  return cy.window({ log: false }).then((win) => {
    if (!originalOnLine) {
      originalOnLine = win.navigator.onLine;
    }

    Object.defineProperty(win.navigator.constructor.prototype, "onLine", {
      get: () => {
        return originalOnLine;
      },
    });

    const isOnline = originalOnLine;
    originalOnLine = false;

    if (isOnline) {
      win.dispatchEvent(new win.Event("offline"));
    }
  });
};

const goOnline = () => {
  cy.log("online");
  return cy.window({ log: false }).then((win) => {
    if (!originalOnLine) {
      originalOnLine = win.navigator.onLine;
    }

    Object.defineProperty(win.navigator.constructor.prototype, "onLine", {
      get: () => {
        return originalOnLine;
      },
    });

    const isOnline = originalOnLine;
    originalOnLine = true;

    if (!isOnline) {
      win.dispatchEvent(new win.Event("online"));
    }
  });
};

describe("page", () => {
  it("works", () => {
    cy.visit("./index.html");

    goOffline();
    cy.get("#network-status").should("contain", "offline");

    goOnline();
    cy.get("#network-status").should("contain", "online");
  });
});

```

**Closed as completed by ZachJW34** 2022-09-20 15:37 UTC
Labels: type: duplicate, topic: installation

**Comment by senthkum** [comment] 2022-09-23 02:09
Hi Zach, The code given is not working.. do you have any other workaround to fix the issue ?. also the issue is still open. without having a solution we can not close the issue. I know it might be a duplicate. But it's difficult to track the issues.

**Comment by senthkum** [comment] 2022-09-26 23:25
> Hi Zach, The code given is not working.. do you have any other workaround to fix the issue ?. also the issue is still open. without having a solution we can not close the issue. I know it might be a duplicate. But it's difficult to track the issues.



> Closing as duplicate of #17723. Throwing a thumbs up on that issue will let us know that more users are interested in this feature and help push it along.
> 
> Tinkering a bit, you can stub the `navigator.onLine` which might be able to suit your use case (also some intercepts/force404). Here is a code snippet that might help (document is listening to `window.addEventListener("offline", ...)`:
> 
> ```js
> let originalOnLine;
> 
> const goOffline = () => {
>   cy.log("offline");
>   return cy.window({ log: false }).then((win) => {
>     if (!originalOnLine) {
>       originalOnLine = win.navigator.onLine;
>     }
> 
>     Object.defineProperty(win.navigator.constructor.prototype, "onLine", {
>       get: () => {
>         return originalOnLine;
>       },
>     });
> 
>     const isOnline = originalOnLine;
>     originalOnLine = false;
> 
>     if (isOnline) {
>       win.dispatchEvent(new win.Event("offline"));
>     }
>   });
> };
> 
> const goOnline = () => {
>   cy.log("online");
>   return cy.window({ log: false }).then((win) => {
>     if (!originalOnLine) {
>       originalOnLine = win.navigator.onLine;
>     }
> 
>     Object.defineProperty(win.navigator.constructor.prototype, "onLine", {
>       get: () => {
>         return originalOnLine;
>       },
>     });
> 
>     const isOnline = originalOnLine;
>     originalOnLine = true;
> 
>     if (!isOnline) {
>       win.dispatchEvent(new win.Event("online"));
>     }
>   });
> };
> 
> describe("page", () => {
>   it("works", () => {
>     cy.visit("./index.html");
> 
>     goOffline();
>     cy.get("#network-status").should("contain", "offline");
> 
>     goOnline();
>     cy.get("#network-status").should("contain", "online");
>   });
> });
> ```



> Hi Zach, The code given is not working.. do you have any other workaround to fix the issue ?. also the issue is still open. without having a solution we can not close the issue. I know it might be a duplicate. But it's difficult to track the issues.

**Comment by ZachJW34** [comment] 2022-09-27 15:04
Unfortunately I do not have another workaround, you can try posting in the thread I linked to see if there are any workarounds. As for closing the issue, that is our policy for duplicates. You can subscribe to the linked issue if you would like to track it.

**Comment by WorkAroundAndFindOut** [comment] 2023-03-09 09:26
I also couldn't make offline mode to work. Is there a solution?
