### ISSUE TITLE
Cannot find module in file inside "node_modules". E.g. Uncaught Error: Cannot find module './../../config/dev.json'

### ISSUE THREAD

**Issue by XIWEI-house** [cypress-io/cypress#2977] opened 2018-12-20 20:31 UTC
Current i am working on using cypress to create AT but i am getting issue when I import internal library which is to create users. The error is thrown from this file 

```
'use strict';

const lodash = require('lodash');
const environment = require('./environment');

let configDir = '../../config';

let env = environment.getEnv() || 'dev';
let envConfig = require(`${configDir}/${env}.json`);
let defaultConfig = require(`${configDir}/default.json`);

function loadConfig() {
  return lodash.merge(defaultConfig, envConfig);
}

module.exports = {
  loadConfig
};

```
where it is complaining `Cannot find module '../../config/dev.json'` at line 9. The file is located in the internal module `shutterstock-test-user`. I confirm the path is right and config folder is on the right directory but still cannot find the module. Is there something wrong with cypress to run with external packages? Thank you!

**Comment by brian-mann** [comment] 2018-12-21 04:13
You didn't post where or how you're using this file, or what your cypress options are or what it is you're trying to do, and we'll need more information such as a reproducible repo in order to investigate this.

It sounds and looks like you're trying to load default configuration which you could/would use our Configuration API which is part of the plugins system.

I'm going to close this issue because there's not enough information provided. If you can provide more and demonstrate how this is happening, we'll open it again.

https://docs.cypress.io/api/plugins/configuration-api.html#Usage

**Closed by brian-mann** 2018-12-21 04:13 UTC

**Comment by XIWEI-house** [comment] 2018-12-21 22:13
@brian-mann Sorry if it is unclear, i am trying to post as much as i can. This is the an internal modularized library so I cannot share repo. The code is from an internal library in `node_modules` where is using `config` in npm library. You are right it is not using cypress config but i just want to see if cypress runner can run code in library in node_modules

**Comment by bahmutov** [comment] 2018-12-21 22:17
Yes it can - but to jump from the test running inside the browser to code running on node you need to use cy.task for example.
