### ISSUE TITLE
 Unzipping cypress preblem

### ISSUE THREAD

**Issue by luxin59** [cypress-io/cypress#2165] opened 2018-07-18 03:31 UTC
```
The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at


----------

Error: end of central directory record signature not found
----------
```

Platform: darwin (16.7.0)
Cypress Version: 3.0.2

**Comment by gustawdaniel** [comment] 2018-09-19 18:20
I had this problem but only one time. Without corporate proxy. I installed package in other project and now package is treated as installed globally. I can't reproduce this problem now. Probably you can close this issue because it describe rare and accidentally occurring bug.

**Closed** 2018-09-20 07:46 UTC

**Comment by limzhang** [comment] 2019-05-28 07:17
I tried to excute the command of "npm install cypress" two times.
The first time, I encountered this problem,too.The error log says "Error: end of central directory record signature not found",and there is a npm warning says "no such file or directory, open 'C:\Users\zhanglimin\package.json'".
Then I tried the second time.During the installation,there is no errors,but the waring still exists.The warning contents is described as below:
 `npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\zhanglimin\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zhanglimin\package.json'
npm WARN zhanglimin No description
npm WARN zhanglimin No repository field.
npm WARN zhanglimin No README data
npm WARN zhanglimin No license field.`
Can I omit this warning and continue to use cypress?And if I need to modify the file name "package-lock.json" to "package.json"?

**Comment by jennifer-shehane** [comment] 2019-05-30 05:10
@limzhang The second warnings comes directly from npm and does not have to do with Cypress. They are just telling you that some fields should be added to your package.json file - you can ignore them though.

If the `end of central directory record signature not found` error occurs again, I would suggest posting in this issue as it is tracking this more closely: https://github.com/cypress-io/cypress/issues/3515
