### ISSUE TITLE
Cypress not working correctly with version 68 of Chrome

### ISSUE THREAD

**Issue by janusvl** [cypress-io/cypress#2215] opened 2018-07-26 13:55 UTC
After we have updated our machines to the latest versions of Chome we encounter some issues. 

Till this morning everything worked fine. However, since we have update chrome from version 67 to 68. It seems that cypress suddenly thinks there is a layer on top of our page. We are getting the following error 
```

CypressError: Timed out retrying: cy.click() failed because this element:

<td id="eri.npcs.external.bezoekschip.shipoperator" onclick="javascript:window.location='http://npcs.portbase.test/vesselcall';">Vessel ...</td>

is being covered by another element:

<td id="eri.npcs.external.notificationshipsupplies.declarant" onclick="javascript:window.location='http://npcs.portbase.test/notificationshipsupplies';">Notific...</td>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with

```

We get this error on multiple pages, and we can see that we that mouse hover is wrong as well. This If I hover the menu the focus seems to lay a lot lower then it's supposed to be.

We don't encounter the problem if we open our website normally. Adding {force: true} works for some occasions but unfortunately not for all.

**Comment by brian-mann** [comment] 2018-07-26 14:36
We are working on a patch release today to fix this.

There is a workaround now per this comment you can do right now which fixes this problem: https://github.com/cypress-io/cypress/issues/2037#issuecomment-407898194

I'm closing this and marking it as duplicate in the mean time.

The problem is that we added this flag to **fix** a different bug that Chrome introduced in 67. This flag is now causing a new bug in the latest stable release of Chrome 68 - however Chrome has already fixed this upstream, so using Canary or the built in Electron would also fix it.

**Closed by brian-mann** 2018-07-26 14:36 UTC
