### ISSUE TITLE
No commands found on test

### ISSUE THREAD

**Issue by mmonteiroc** [cypress-io/cypress#28686] opened 2024-01-11 10:46 UTC
### Current behavior

When I run in the UI, cypress tells me the file has no commands issued.
![image](https://github.com/cypress-io/cypress/assets/28816737/90074980-5960-4f0f-b188-8ecd5c2ba226)

After I refresh several times, finally it decides to understand that there is tests.
![image](https://github.com/cypress-io/cypress/assets/28816737/984e9dae-750f-4315-a432-85929a69050b)

When running headless, seems to work fine

### Test code to reproduce

Not much to provide, its random and sometimes decides to find tests and sometimes doesnt.

### Cypress Version

v13.6.2

### Node version

v18.13.0

### Operating System

Windows 10

**Comment by harveysanders** [comment] 2024-01-18 19:30
I'm also seeing this behavior in GUI mode. In headless mode, all the tests are found and executed.
Desired behavior
All tests with valid commands/assertions should be found an executed

Test code to reproduce
I agree it seems to be random. I will say that so far this has only happened with Chrome (`v121`) and Canary Chrome (`v122`). With the Electron browser (`v114`), all the tests run.

### Cypress Version
v13.6.2 && 13.6.3

### Node version
v20.8.0

Operating System
MacOS 14.2.1 (Intel)

### Debug Logs
No response

Other
No response

**Comment by HenrikJoreteg** [comment] 2024-01-21 14:57
I'm seeing this as well.

It doesn't happen on first run, but happens very consistently when i refresh cypress-controlled Chrome browser to re-run a test after a change. 

I can usually also get it to run by clicking on another spec then back.

It still runs fine in CI, but this is happening very consistenly locally. 



**Cypress Version**
v13.6.2 && 13.6.3

**Node version**
v16.17.0

**Operating System**
MacOS 14.2.1 (Apple M2)

<img width="396" alt="Screenshot 2024-01-21 at 6 54 34 AM" src="https://github.com/cypress-io/cypress/assets/67925/12929df9-8dc3-4d3d-81a0-decdaffb069b">

**Comment by MattySheikh** [comment] 2024-02-07 23:25
Consistently seeing this on v13.6.4, node v18.19.0 - first test will run but the rest won't

**Comment by deniseruck** [comment] 2024-02-26 06:55
Seeing this 1 out of 5 times when I run in the UI. this has only started happening in the last couple of versions 13.6.4. I need to stop and re-run

**Comment by jennifer-shehane** [comment] 2024-02-26 20:14
Could you all try to update to 13.6.6 and let us know if you're still experiencing this issue? We fixed an issue in 13.6.5 that was introduced in 13.6.0 and we want to understand if this has also resolved this issue. Thank you!

**Comment by manuelmiksche** [comment] 2024-02-27 14:51
@jennifer-shehane Thanks for the update on this topic! I tested 13.6.6 on latest MacOS with latest Chrome and didn't face any issues.

Before, any 13.6.x version ran only the first test and then stopped. 13.5.1 was the last one with a working GUI.

**Comment by jennifer-shehane** [comment] 2024-02-27 15:37
@manuelmiksche Very nice. I thought it may be related. Going to close this issue and monitor any more comments.

**Closed as completed by jennifer-shehane** 2024-02-27 15:37 UTC
Labels: v13.6.0 🐛

**Comment by ParisseNicolas** [comment] 2024-03-14 14:59
Hello @jennifer-shehane 

I was experiencing the same issue. Even upgrading the version did not work (and I actually can't really because I am using nx mono repo, but that is another story).

I am using cypress for component testing.

Just to be clear about the issue: the tests run perfectly once but running them again lead to the message "no commands were issued on this test". By running them again I mean anything like "modifying a test then saving it on VS code" or clicking on the run all tests button:
![image](https://github.com/cypress-io/cypress/assets/58308727/c4f894aa-d1d1-43d0-add6-1fbb23475489)

Pressing F5 to refresh the page let the tests to run once again but would fail if running them again.
Changing browser (tested for chrome and electron) did not change the issue.

I actually found out the issue was caused by clicking on a hyperlink which would open a new tab. So I applied the workaround which consist in removing the target attribute. It is this behaviour which led to that same issue.
Would there be a fix available? 

The test to reproduce the issue:
```js
/// <reference types="cypress" />

import { RouterTestingModule } from '@angular/router/testing';
import { Component } from "@angular/core";

@Component({template: '<div>hello</div>'})
class DummyComponent {}

const IdValue = '12'
const propertyAValue = 'stringPropertyAValue'
const propertyBValue = 'test'

describe('component test', () => {

    it('should go to url', () => {
        cy.mount(`<a class="property-value" [routerLink]="['route/to/somewhere', properties.Id]" target="_blank">
        {{ properties.propertyA }}
        {{ properties.propertyB }}
    </a>`, {
        imports:[ RouterTestingModule.withRoutes([ {path:'route/to/somewhere/:Id', component: DummyComponent} ]) ],
        componentProperties: {
            properties: {
                propertyA: propertyAValue,
                propertyB: propertyBValue,
                Id: IdValue
            }
        }
    });
    cy.get('.property-value').invoke("removeAttr", "target").click(); // remove .invoke("removeAttr", "target") to stop the issue with cypress rerunning test
    cy.url().should('include', `route/to/somewhere/${IdValue}`);
    }) 

    it('should translate', () => {
        cy.log('should translate');
   
    })
})
```

I reproduced this issue on cypress c13.7.0 as well.

Thanks,

**Comment by jennifer-shehane** [comment] 2024-03-14 16:18
@Ystalard Can you open a new issue for tracking?
