### ISSUE TITLE
Incorrect domain when setting cookie

### ISSUE THREAD

**Issue by jaroslav-kubicek** [cypress-io/cypress#9158] opened 2020-11-10 13:37 UTC
### Current behavior

When setting a cookie with `cy.setCookie("foo", "bar")`, domain is not set according to doc:

Given the current URL is `https://another-level.subdomain.example.com`, a cookie is saved with the domain set to `.example.com`. Also, when setting the domain explicitly, it's prefixed with `.`

### Desired behavior

Domain should be set to `another-level.subdomain.example.com` as stated in docs: https://docs.cypress.io/api/commands/setcookie.html#Arguments => default is `window.location.hostname`

### Versions

tested on 5.4.0 & 5.6.0

**Comment by chenfan-fchen** [comment] 2020-12-22 08:36
Per my knowledge, it's not cypress issue, cause the server agent(I used chrome) add a dot before the domain, cypress just pass this value to it's cookie, the result is what we can see there's a dot prefix the value.
Do you resolved this issue, I got the same issue, pending to resolve

**Comment by eriatall** [comment] 2021-03-31 18:50
This issue still exists in v6.3.0, related issue [8809](https://github.com/cypress-io/cypress/issues/8809).

**Comment by jennifer-shehane** [comment] 2021-03-31 19:13
Duplicate of https://github.com/cypress-io/cypress/issues/1896

**Closed by jennifer-shehane** 2021-03-31 19:13 UTC
Labels: stage: needs investigating, topic: cookies :cookie:

**Comment by eriatall** [comment] 2021-03-31 19:28
I believe there are two issues here.  The main issue, which is not a duplicate of [#1896](https://github.com/cypress-io/cypress/issues/1896), is that cy.setCookie() does not set the full domain correctly by default.  [The docs](https://docs.cypress.io/api/commands/setcookie#Arguments) state it is set to `window.location.hostname` by default.  This isn't the actual behavior, as can be seen from repro test in [#8809](https://github.com/cypress-io/cypress/issues/8809).

**Comment by jshields-squarespace** [comment] 2021-06-30 22:28
@jennifer-shehane Please see @eriatall's comment above: https://github.com/cypress-io/cypress/issues/9158#issuecomment-811376411

The documentation for the default value of `cy.setCookie`'s `domain` option is demonstrably incorrect. Can you please consider reopening this issue to address that fact? It's separate from the `.` prefix behavior.

**Comment by drinchev** [comment] 2021-10-13 08:56
We ended up using `sameSite: "no_restriction"` when using `cy.setCookie`.
