### ISSUE TITLE
Popup is not getting stop on Screen. 

### ISSUE THREAD

**Issue by waqas9462** [cypress-io/cypress#28064] opened 2023-10-16 11:36 UTC
### Current behavior

As click on Action icon, It validate some of the content on the popup and popup doesn't appear. Script is getting failed. 
But when try to check time travel to see the popup behaviour popup doesn't show on the screen. 
<img width="1787" alt="image" src="https://github.com/cypress-io/cypress/assets/145959340/49626f8f-d978-429e-9b24-59efdeb165d1">

### Desired behavior

Popup should be hold on the screen. 
<img width="1711" alt="image" src="https://github.com/cypress-io/cypress/assets/145959340/6bd285f4-a066-496d-9507-7e1168735cc8">

### Test code to reproduce

Login Page Elements:
```js
{
    "LoginPageLocators": {
        "login_button": "a[href='https://master.chargeautomation.com/login']",
        "username_text": "input[name='email']",
        "Password_text": "input[name='password']",
        "login_user": "#loginbtn",
        "profile_icon": "#nav_prof_u-name"
    }
}
```

Login Page Actions:
```js
const loginElementLocators = require('../PageElements/LoginPageElements.json')

export class loginPageElements{
    
    happyLogin(userName, password){
        sessionStorage.clear()
        cy.clearAllCookies({ log: true })
        cy.clearAllLocalStorage('your item', { log: true })
        cy.clearAllSessionStorage()
        this.exceptionError()
        cy.get(loginElementLocators.LoginPageLocators.login_button)
            .click()
        cy.get('.signup-upper > p').should('have.text', 'Welcome back to ChargeAutomation')
        cy.get(loginElementLocators.LoginPageLocators.username_text)
            .type(userName)
        cy.get(loginElementLocators.LoginPageLocators.Password_text)
        .type(password, { force: true })
        cy.get(loginElementLocators.LoginPageLocators.login_user).click({force: true })
        cy.get('.page-title')
            .should('have.text', 'Welcome Waqas')
        cy.url().should('include', '/dashboard-new')
        return
    }
    exceptionError(){
        Cypress.on('uncaught:exception', (err, runnable) => {
            // returning false here prevents Cypress from
            // failing the test
            return false
          })
    }
```
Spec file:
```js
/// <reference types ="Cypress" />

import { loginPageElements } from "../../../PageObjects/PageActions/LoginPageActions"

  const Login_Elements = new loginPageElements


describe('Pre Check-In Process', () => {
  
  beforeEach(() => {
    cy.visit('/')
    Login_Elements.happyLogin('automationca2@yopmail.com', 'Boring321')
  })
  
 it('Validate when Collect Basic Information From Guest(s) toggle is disable', () => {
    cy.xpath("(//a[@id='navbarDropdown'])[4]").click()
    cy.get(':nth-child(4) > .main-item').click({force: true})
    cy.scrollTo('top')
    cy.get('#edit-guest-exp2').click({force: true})
    cy.xpath("//h5[@class='modal-title'][normalize-space()='Collect Basic Information From Guest(s)']")
      .should('contain', 'Collect Basic Information From Guest(s)')
    cy.xpath("//span[normalize-space()='Full Name']").should('contain', 'Full Name')
    cy.get("li:nth-child(1) label:nth-child(1) input:nth-child(1)").click().wait(2000)
    cy.xpath("//span[normalize-space()='Phone Number']").should('contain', 'Phone Number')
    cy.get("li:nth-child(2) label:nth-child(1) input:nth-child(1)").click().wait(2000)
    
  }) 
}) 
```
### Cypress Version

13.3.1

### Node version

v18.18.0

### Operating System

mac version: 12.2.1 (21D62)

### Debug Logs

```shell
Please check this recording. 
https://screenpal.com/watch/c06DXzVEn27
```

**Comment by waqas9462** [comment] 2023-10-17 07:12
@cypress-github-team-services-sa 
Any update regarding this?

**Comment by jennifer-shehane** [comment] 2023-11-28 19:20
@waqas9462 It seems from the error msg that it's indicating that the element you're clicking has a parent that's hiding it. Could you try clicking on another element further up that opens the modal? It's hard to tell without seeing the App completely.

**Comment by jennifer-shehane** [comment] 2024-04-23 03:00
Unfortunately we’ll have to close this issue since we don’t have enough information to reproduce it and assist.

**Closed as not planned by jennifer-shehane** 2024-04-23 03:00 UTC
Labels: topic: cy.click 🖱
