### ISSUE TITLE
Recaptcha error on version 5.5.0

### ISSUE THREAD

**Issue by JChrist** [cypress-io/cypress#9104] opened 2020-11-05 08:57 UTC
### Current behavior
Recaptcha script is blocked with an error similar to:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://www.gstatic.com/recaptcha/releases/<reducted>/recaptcha__en.js' with computed SHA-256 integrity '<reducted>'. The resource has been blocked.
```

### Desired behavior
The script should not be blocked, and the submit function should be able to run, receiving a recaptcha token.

### Test code to reproduce
https://github.com/JChrist/cypress-test-tiny

### Versions
The error occurs on Cypress 5.5.0
Switching back to 5.4.0 works as expected.

**Comment by jennifer-shehane** [comment] 2020-11-05 10:58
Duplicate of https://github.com/cypress-io/cypress/issues/8983

There's a PR out to fix this.

**Closed by jennifer-shehane** 2020-11-05 10:58 UTC
