### ISSUE TITLE
Record videos only for failing tests

### ISSUE THREAD

**Issue by t0lkman** [cypress-io/cypress#7802] opened 2020-06-24 19:16 UTC
### Current behavior:
Currently, the video files take a lot of local storage because the video is being recorded for each test regardless if a test passes or fails.

### Desired behavior:
Introduce a config option that will limit video recording only for tests which are failed

**Comment by jennifer-shehane** [comment] 2020-06-25 04:28
Duplicate of #2522

**Closed by jennifer-shehane** 2020-06-25 04:28 UTC
