### ISSUE TITLE
How to test site which loads in bing map callback?

### ISSUE THREAD

**Issue by ShahriatHossain** [cypress-io/cypress#3964] opened 2019-04-15 01:27 UTC
I have an app which has been developed using angularJs. But the app is loading under the bing map callback as a result when I use cypress to find any html element it fails all the time because of the callback process. Test is executing before the app is loaded.

How to sort out this problem?

**Comment by Lakitna** [comment] 2019-04-15 11:36
This would probably be the best solution based on what I can make out from your description. https://docs.cypress.io/api/commands/wait.html#Wait-for-a-specific-XHR-to-respond

Please note that we prefer you ask these kinds of questions in the Gitter chat instead. https://gitter.im/cypress-io/cypress That keeps the issue log clean and often results in faster responses.

**Comment by jennifer-shehane** [comment] 2019-04-18 06:35
Closing since issues in our GitHub repo are reserved for potential bugs or feature requests. If you think this is a bug with Cypress, feel free to comment with a fully reproducible example.

**Closed by jennifer-shehane** 2019-04-18 06:35 UTC
