### ISSUE TITLE
I dont see url during cypress test execution

### ISSUE THREAD

**Issue by niceGuyOneTwo** [cypress-io/cypress#25817] opened 2023-02-15 08:32 UTC
### Current behavior

![image](https://user-images.githubusercontent.com/125444158/218973850-3fb60ec4-9682-4025-b917-8b377906818b.png)
and this causes cy visit error, looks like the cypress doesn't know where to start actually 

### Desired behaviour

url working as always
### Test code to reproduce

I don't have any test code related,

### Cypress Version

12.5.1

### Node version

16.14

### Operating System

Ventura 13.1

**Comment by niceGuyOneTwo** [comment] 2023-02-15 08:36
looks like cy.visit is not seeing the url

**Comment by nagash77** [comment] 2023-02-15 18:48
Hi @niceGuyOneTwo , I am sorry to hear you are having issues using Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2023-02-23 18:58
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-02-23 18:58 UTC
