### ISSUE TITLE
cypress runner ignoring charset=“windows-1252” html tag

### ISSUE THREAD

**Issue by opensas** [cypress-io/cypress#3725] opened 2019-03-17 04:14 UTC
### Current behavior:

I'm testing a page encoded with windows-1252 like this:

```html
<html>
<head>
  <title>Meta-SSC</title>
  <meta http-equiv="Content-Type" content="text/html">
  <meta charset="windows-1252">
  [...]
```

But cypress runner seems not to be taking it into account:

![cypress runner ignores windows-1252 encoding](https://i.stack.imgur.com/YKnCN.png)

My test are failing because of this.

On the other hand, when testing it on chrome (Version 72.0.3626.121 Official Build 32-bit running on windows 10) or firefox (65.0.2 64bits) it works ok:

![windows-1252 encoding runs ok in chrome](https://i.stack.imgur.com/SX6Ga.png)

### Desired behavior:

Cypress runner should correctly handle windows-1252 encoding like chrome and firefox do.

### Steps to reproduce: (app code and test code)

This is a minimal example I built: 

```html
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html">
  <meta charset="windows-1252">
</head>
<body>
  <h1>Character encoding failing test: á é í ó ú ñ</h1>
</body>
```

![imagen](https://user-images.githubusercontent.com/481687/54485082-6b399f00-4851-11e9-978c-0b197d5613f3.png)

While on chrome:

![imagen](https://user-images.githubusercontent.com/481687/54485087-81dff600-4851-11e9-82f4-d4de27a93c7b.png)

### Versions

cypress version:

```
  "devDependencies": {
    "cypress": "^3.2.0"
  }
```
os: Microsoft Windows 10 Home, Version 10.0.17134 Build 17134

works ok on:
chrome (Version 72.0.3626.121 Official Build 32-bit running on windows 10)
firefox (65.0.2 64bits)

---

Also asked at [SO](https://stackoverflow.com/questions/55203672/cypress-runner-ignoring-charset-windows-1252-html-tag)

**Comment by opensas** [comment] 2019-03-17 06:26
update: this is the best workaound I could find so far, if anybody has a better alternative I'd be grateful

```js
describe('playing with regular expressions', () => {
  it.only('should match by regular expression', () => {
    cy.visit('http://localhost/metaSSC/cypress/regexp.html')
    cy.get('div.flash_warning span')
      .should('have.text', 'El registro no ha podido ser dado de alta.')
    cy.get('div.flash_error span')
      .contains(/^El c.digo de la aplicacion no puede estar vac.o\.$/) // match span text by regexp
  })
})

**Comment by jennifer-shehane** [comment] 2019-03-18 04:05
Duplicate of https://github.com/cypress-io/cypress/issues/1543

**Closed by jennifer-shehane** 2019-03-18 04:05 UTC
