### ISSUE TITLE
can't fetch session from previous testcase

### ISSUE THREAD

**Issue by rijkysallaffudin** [cypress-io/cypress#25190] opened 2022-12-16 03:19 UTC
### Current behavior

when running a different test-case  the session position was still logged in version 10, whereas in version 12 we need to log-in again to run a different test case

![image](https://user-images.githubusercontent.com/120697627/208014935-aa243b66-0711-4dd9-91da-7a78e8546a2a.png)

### Test code to reproduce

when running a different test-case  the session position was still logged in version 10, whereas in version 12 we need to log-in again to run a different test case

### Cypress Version

v.12.0.2

### Node version

-

### Operating System

windows 10

**Comment by nagash77** [comment] 2022-12-16 16:03
Hi @rijkysallaffudin , Have you read through the changes around [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation#Test-Isolation-in-End-to-End-Testing)?  Without seeing a specific example from your tests this would be my best guess.  I am going to close this issue until a reproducible example is shared since we have nothing to go off of.  If you can share a reproducible example I will reopen this issue.

**Closed as not planned by nagash77** 2022-12-16 16:03 UTC
