### ISSUE TITLE
New file download feature: need a method to get the filename of the download

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#15232] opened 2021-02-25 22:03 UTC
This feature seems to assume that we know the name of the file being downloaded. The UI that I work on generates a new filename on every download (because it includes the timestamp). How do we get the filename of each download from Cypress?

**Comment by jennifer-shehane** [comment] 2021-02-26 13:52
Actually this issue is already opened here, I forgot. 

Duplicate of https://github.com/cypress-io/cypress/issues/14863

**Closed by jennifer-shehane** 2021-02-26 13:52 UTC
Labels: stage: proposal 💡, topic: downloads ⬇️, type: enhancement
