### ISSUE TITLE
Feature request for ignoring page loading

### ISSUE THREAD

**Issue by vitaliy4us** [cypress-io/cypress#7785] opened 2020-06-23 09:13 UTC
### Current behavior:

1. Press a button on the page to confirm certain action (e.q. save some changes)
2. The page starts reloading. Cypress is paused and is waiting for reloading is finished.
3. Notification about successfully confirmed action appears, but the page is still reloading.
4. Notification is gone, but the page is still reloading.
5. The page has been reloaded, Cypress starts working and tries to assert the notification.
6. Test fails as the notification does not exist any more.
![notification issue 1](https://user-images.githubusercontent.com/12917391/85385371-e7d62580-b54a-11ea-817a-072e24aa7e8d.png)
![notification issue 2](https://user-images.githubusercontent.com/12917391/85385383-ee649d00-b54a-11ea-95e6-ce770facd761.png)

### Desired behavior:

1. Press a button on the page to confirm certain action (e.q. save some changes)
2. The page starts reloading. Cypress is NOT paused and continue working.
3. Notification about successfully confirmed action appears, but the page is still reloading.
4. Cypress is able to detect the notification.

### Versions

Cypress 4.8.3, Windows 10, Chrome

**Comment by jennifer-shehane** [comment] 2020-07-14 08:36
Duplicate of #788

**Closed by jennifer-shehane** 2020-07-14 08:36 UTC
