### ISSUE TITLE
Cypress doesn't take correct snapshots in 'fullPage' mode in Electron and Chrome browsers

### ISSUE THREAD

**Issue by ElderMorgun** [cypress-io/cypress#5876] opened 2019-12-04 13:54 UTC
### Current behavior:

When I use `cy.screenshot()` in the test code for visual regression, I wanna take a picture of all DOM element, not only its visible part.
 
But cypress cannot capture the whole element. The screenshots have the correct size but with only recurring visible part.

![screenshot example](https://user-images.githubusercontent.com/51074781/70147853-c21c2880-16ad-11ea-9f9a-9332d1fe11d5.png)

### Desired behavior:

To take full element as screenshot independently of the DOM element size or viewport settings

### Steps to reproduce: 

**Test code:**
```js
it('Take a long snapshot', () => {
  cy.visit('https://twitter.com/Irine_Meier/status/1172003419458088960');
  cy.wait(2000);
  cy.get('#stream-items-id').screenshot({ capture: 'fullPage', scale: true });
});
```

I took twitter long read for example of **App code**

https://twitter.com/Irine_Meier/status/1172003419458088960

As u can see the getter `#stream-items-id` is the twitter tread, the DOM element has a specific length and width

### Versions

Windows: win 10 x64
Cypress: 3.7.0
Browsers: Electron 73, Chrome 78

**Comment by jennifer-shehane** [comment] 2019-12-05 11:41
@ElderMorgun As an aside the `capture: 'fullPage'` option will also be ignored here, since you chained `.screenshot()` off of an element as noted in the description for the `capture` option in our docs. https://on.cypress.io/screenshot#Arguments

When I run the provided code the `#stream-items-id` shows as not visible when running the test, not sure why that is. 

The twitter feed also dynamically loads as your scroll, which may have something to do with the strange screenshot behavior in Cypress.

<img width="982" alt="Screen Shot 2019-12-05 at 6 04 28 PM" src="https://user-images.githubusercontent.com/1271364/70231956-c289f180-1789-11ea-8df8-a8584929aa1e.png">

## Screenshot in Cypress

The screenshot is notably wrong. I pasted a screenshot of what mine returned - the checkered part being a transparent bg. 

![Screen Shot 2019-12-05 at 6 07 01 PM](https://user-images.githubusercontent.com/1271364/70232176-3a581c00-178a-11ea-825d-edfbb98d6105.png)

## Screenshot how it should look

![twitter com_Irine_Meier_status_1172003419458088960 copy](https://user-images.githubusercontent.com/1271364/70232331-9327b480-178a-11ea-8b51-335090d7cef1.png)

**Comment by danjor38** [comment] 2020-03-13 13:16
I had a similar issue with fullPage screenshot without element, it did not scroll and did not screenshot the fullPage
I had style height: 100% on the body element, and removing it allow cypress to take fullPage screenshot

**Comment by Poitrin** [comment] 2020-05-08 09:13
> I had style height: 100% on the body element, and removing it allow cypress to take fullPage screenshot

Can confirm, had the same CSS code. After removing it, it works.

**Comment by azaeng04** [comment] 2020-05-12 15:12
@jennifer-shehane any proposed solution for this?

**Comment by jennifer-shehane** [comment] 2020-07-14 05:20
I believe this is a duplicate of #2681 - I can't completely recreate the original issue since Twitter's interface has changed, but it sounds similar from the screenshots and comments.

**Closed by jennifer-shehane** 2020-07-14 05:20 UTC
Labels: stage: needs investigating, topic: screenshots 📸, type: bug

**Comment by srinu-kodi** [comment] 2021-03-11 13:19
Hi @ElderMorgun 
Could you please tell me how did you solve this issue. I have been facing this issue and there is no way to visually test the application if I have to test at fullPage level... Please respond.

**Comment by srinu-kodi** [comment] 2021-03-11 13:24
@jennifer-shehane  Any thoughts on this. No library is helping out in the visual regression front with Cypress. It would be really great if someone from Cypress fixes the cy.screenshot() which is not taking fullPage screenshot.. Could you please throw some light on this.

**Comment by jennifer-shehane** [comment] 2021-06-16 19:51
@srinu-kodi There's not a current workaround, this is still an issue documented in https://github.com/cypress-io/cypress/issues/2681
