### ISSUE TITLE
Server sent events not showing up in the Cypress browser

### ISSUE THREAD

**Issue by simonatorw** [cypress-io/cypress#1111] opened 2017-12-21 00:41 UTC
- Operating System: Windows 7
- Cypress Version: 1.4
- Browser Version: Chrome 55

### Is this a Feature or Bug?
Bug

### Current behavior:
I have an app that uses SSE and it works fine on  browser running localhost but the browser that Cypress opens does not show this data coming through

### Desired behavior:
It should show the SSE data just like in the regular browser

### How to reproduce:
`cypress open` and then visit the app at localhost

**Comment by bahmutov** [comment] 2017-12-21 00:42
Can we have the server setup for this? Includ ing SSE events sending?

**Comment by brian-mann** [comment] 2017-12-21 00:43
Yah we've had other users use SSE without any problems. Must be an edge case here. Can you provide more details?

**Comment by simonatorw** [comment] 2017-12-21 01:03
Hello, the node code is attached as jsx file

On 12/20/17, Gleb Bahmutov <notifications@github.com> wrote:
> Can we have the server setup for this? Includ ing SSE events sending?
>
> Sent from my iPhone
>
>> On Dec 20, 2017, at 19:41, Raph <notifications@github.com> wrote:
>>
>> Operating System: Windows 7
>> Cypress Version: 1.4
>> Browser Version: Chrome 55
>> Is this a Feature or Bug?
>>
>> Bug
>>
>> Current behavior:
>>
>> I have an app that uses SSE and it works fine on browser running localhost
>> but the browser that Cypress opens does not show this data coming through
>>
>> Desired behavior:
>>
>> It should show the SSE data just like in the regular browser
>>
>> How to reproduce:
>>
>> cypress open and then visit the app at localhost
>>
>> Test code:
>>
>> Additional Info (images, stack traces, etc)
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cypress-io/cypress/issues/1111#issuecomment-353224635


-- 
Can fat ppl fly on the halfpipe?  I replied, "How high?"

**Comment by simonatorw** [comment] 2017-12-21 01:09
Once you run it:
node server.jsx

You can see it in the browser we these urls:
http://127.0.0.1:8124/dailyperformancert
http://127.0.0.1:8124/equitypositionsrt
http://127.0.0.1:8124/marketheadlinesrt

On 12/20/17, Simon <simon@bigredtiger.com> wrote:
> Hello, the node code is attached as jsx file
>
> On 12/20/17, Gleb Bahmutov <notifications@github.com> wrote:
>> Can we have the server setup for this? Includ ing SSE events sending?
>>
>> Sent from my iPhone
>>
>>> On Dec 20, 2017, at 19:41, Raph <notifications@github.com> wrote:
>>>
>>> Operating System: Windows 7
>>> Cypress Version: 1.4
>>> Browser Version: Chrome 55
>>> Is this a Feature or Bug?
>>>
>>> Bug
>>>
>>> Current behavior:
>>>
>>> I have an app that uses SSE and it works fine on browser running
>>> localhost
>>> but the browser that Cypress opens does not show this data coming
>>> through
>>>
>>> Desired behavior:
>>>
>>> It should show the SSE data just like in the regular browser
>>>
>>> How to reproduce:
>>>
>>> cypress open and then visit the app at localhost
>>>
>>> Test code:
>>>
>>> Additional Info (images, stack traces, etc)
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub, or mute the thread.
>>>
>>
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/cypress-io/cypress/issues/1111#issuecomment-353224635
>
>
> --
> Can fat ppl fly on the halfpipe?  I replied, "How high?"
>


-- 
Can fat ppl fly on the halfpipe?  I replied, "How high?"

**Comment by simonatorw** [comment] 2017-12-21 01:14
It's funny, because when i stopped this server, the sse data shows up
in the cypress browser

On 12/20/17, Simon <simon@bigredtiger.com> wrote:
> Once you run it:
> node server.jsx
>
> You can see it in the browser we these urls:
> http://127.0.0.1:8124/dailyperformancert
> http://127.0.0.1:8124/equitypositionsrt
> http://127.0.0.1:8124/marketheadlinesrt
>
> On 12/20/17, Simon <simon@bigredtiger.com> wrote:
>> Hello, the node code is attached as jsx file
>>
>> On 12/20/17, Gleb Bahmutov <notifications@github.com> wrote:
>>> Can we have the server setup for this? Includ ing SSE events sending?
>>>
>>> Sent from my iPhone
>>>
>>>> On Dec 20, 2017, at 19:41, Raph <notifications@github.com> wrote:
>>>>
>>>> Operating System: Windows 7
>>>> Cypress Version: 1.4
>>>> Browser Version: Chrome 55
>>>> Is this a Feature or Bug?
>>>>
>>>> Bug
>>>>
>>>> Current behavior:
>>>>
>>>> I have an app that uses SSE and it works fine on browser running
>>>> localhost
>>>> but the browser that Cypress opens does not show this data coming
>>>> through
>>>>
>>>> Desired behavior:
>>>>
>>>> It should show the SSE data just like in the regular browser
>>>>
>>>> How to reproduce:
>>>>
>>>> cypress open and then visit the app at localhost
>>>>
>>>> Test code:
>>>>
>>>> Additional Info (images, stack traces, etc)
>>>>
>>>> —
>>>> You are receiving this because you are subscribed to this thread.
>>>> Reply to this email directly, view it on GitHub, or mute the thread.
>>>>
>>>
>>>
>>> --
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/cypress-io/cypress/issues/1111#issuecomment-353224635
>>
>>
>> --
>> Can fat ppl fly on the halfpipe?  I replied, "How high?"
>>
>
>
> --
> Can fat ppl fly on the halfpipe?  I replied, "How high?"
>


-- 
Can fat ppl fly on the halfpipe?  I replied, "How high?"

**Comment by simonatorw** [comment] 2017-12-24 01:59
The node server is here:
https://github.com/simonatorw/server

**Comment by nLight** [comment] 2018-02-23 18:04
I bet it's the same issue as with missing `progress` events. Since cypress never propagates `progress` events SSE data never shows up until you stop the server which closes the connection so cypress finally dumps all the data. Should be fixed with https://github.com/cypress-io/cypress/issues/687 also related to https://github.com/cypress-io/cypress/issues/1185

**Comment by hally9k** [comment] 2018-03-07 04:46
I have just run into this and it's kind of a show stopper for what we are doing. Are there any known work arounds?

**Comment by brian-mann** [comment] 2018-03-07 04:57
We need a simplified reproducible repo to look into this.

**Comment by hally9k** [comment] 2018-03-07 05:13
@brian-mann Thanks for your response; first thing tomorrow as it's 6pm already 😅

**Comment by hally9k** [comment] 2018-03-07 21:58
@brian-mann Here is a simple repro: https://github.com/hally9k/cypress-sse

**Comment by hally9k** [comment] 2018-03-07 22:03
There ay be a clue in that it behaves as @simonatorw described above. If you run cypress and the repro app separately and watch the event stream in dev tools in the cypress browser nothing comes through. Then go and stop the repro app and watch all the buffered events come through at once in the dev tools event stream. This is behaving like a buffering proxy.

**Comment by hally9k** [comment] 2018-03-11 23:20
@brian-mann Did you have a chance to look at this yet? What's the state of play?

**Comment by brian-mann** [comment] 2018-03-12 18:35
I have not looked at this yet. We are super busy trying to get out our `3.0` release - we're raising money, and we just had a new full time developer start today. 

I'll try to get to this soon (or someone else) will but can't give you a timeline. If 3.0 gets delayed any long we'll issue a patch release to fix some bugs like this one.

**Closed** 2018-06-28 10:22 UTC
Labels: stage: needs investigating

**Comment by brian-mann** [comment] 2018-06-29 09:12
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
