### ISSUE TITLE
Cypress Heap Issue

### ISSUE THREAD

**Issue by basicallysteve** [cypress-io/cypress#20846] opened 2022-03-30 13:50 UTC
### Current behavior

Was running tests on staging last night and the cypress process was killed halfway through tests with a heap limit allocation failure.  I've added a stack trace from when the tests failed last night, I'm not really sure what else I should add here, but if more info is needed, I can try and get you more.

![image](https://user-images.githubusercontent.com/22861039/160848397-3e312b53-efed-43fc-a8a2-d7aefd0b000a.png)

### Test code to reproduce

- Run `npx cypress run --record --key SOMEKEY --reporter mochawesome`

### Cypress Version

9.5.3

**Comment by jimberley** [comment] 2022-03-31 18:45
FWIW, this is happening to our instance a lot as well. Seems to happen right about 5 minutes into our suite.

**Comment by esonhey** [comment] 2023-02-21 18:03
I'm getting a similar Heap error on CI using Cypress v12.3.0 and cypress-io/github-action@v5.0.4. any updates on how to resolve it?
```
<--- Last few GCs --->

[2673:0x578f210]   661978 ms: Scavenge (reduce) 2043.2 (2080.8) -> 2043.0 (2081.3) MB, 4.7 / 0.0 ms  (average mu = 0.353, current mu = 0.305) allocation failure 
[2673:0x578f210]   663964 ms: Mark-sweep (reduce) 2043.9 (2081.6) -> 2043.2 (2082.1) MB, 1985.1 / 8.2 ms  (average mu = 0.212, current mu = 0.045) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb0a860 node::Abort() [Cypress: Config Manager]
 2: 0xa1c193 node::FatalError(char const*, char const*) [Cypress: Config Manager]
 3: 0xcf9a6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
 4: 0xcf9de7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
 5: 0xeb1685  [Cypress: Config Manager]
 6: 0xec134d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [Cypress: Config Manager]
 7: 0xec404e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [Cypress: Config Manager]
 8: 0xe8558a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [Cypress: Config Manager]
 9: 0x11fe2d6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [Cypress: Config Manager]
10: 0x15f2d39  [Cypress: Config Manager]
```

**Comment by ryanwelch-degreed** [comment] 2023-03-08 21:14
Same issue in Cypress 12.6 running in ADO. Happens right around the 6 or 7 minute mark.

**Comment by nemonemi** [comment] 2023-03-24 09:38
And I can confirm it with the v12.8.0.

**Comment by metalix2** [comment] 2023-04-04 11:13
> I'm getting a similar Heap error on CI using Cypress v12.3.0 and cypress-io/github-action@v5.0.4. any updates on how to resolve it?
> 
> ```
> <--- Last few GCs --->
> 
> [2673:0x578f210]   661978 ms: Scavenge (reduce) 2043.2 (2080.8) -> 2043.0 (2081.3) MB, 4.7 / 0.0 ms  (average mu = 0.353, current mu = 0.305) allocation failure 
> [2673:0x578f210]   663964 ms: Mark-sweep (reduce) 2043.9 (2081.6) -> 2043.2 (2082.1) MB, 1985.1 / 8.2 ms  (average mu = 0.212, current mu = 0.045) allocation failure scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
>  1: 0xb0a860 node::Abort() [Cypress: Config Manager]
>  2: 0xa1c193 node::FatalError(char const*, char const*) [Cypress: Config Manager]
>  3: 0xcf9a6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
>  4: 0xcf9de7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
>  5: 0xeb1685  [Cypress: Config Manager]
>  6: 0xec134d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [Cypress: Config Manager]
>  7: 0xec404e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [Cypress: Config Manager]
>  8: 0xe8558a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [Cypress: Config Manager]
>  9: 0x11fe2d6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [Cypress: Config Manager]
> 10: 0x15f2d39  [Cypress: Config Manager]
> ```


I started recieving something similar to this when I added a custom plugin which returns a promise. I've tested it on DroneCI and there are no issues but when on Github Actions. I constantly get Memory heap errors and the Github Actions run forever.. this is on Cypress 12.7.0 :/

![Screenshot 2023-04-04 at 12 00 25](https://user-images.githubusercontent.com/2506718/229774517-cc692b61-2f7a-4b9f-b5bc-1921856b9e39.png)
```
 <--- Last few GCs --->
[2939:0x6794da0]   134045 ms: Mark-sweep 4053.6 (4141.2) -> 4039.7 (4143.5) MB, 2150.4 / 0.0 ms  (average mu = 0.277, current mu = 0.013) allocation failure; scavenge might not succeed
[2939:0x6794da0]   137266 ms: Mark-sweep 4055.2 (4144.0) -> 4042.5 (4146.2) MB, 2941.0 / 0.0 ms  (average mu = 0.176, current mu = 0.087) allocation failure; GC in old space requested
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7b3e0 node::Abort() [Cypress: Config Manager]
 2: 0xa8c8aa  [Cypress: Config Manager]
 3: 0xd69100 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
 4: 0xd694a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
 5: 0xf46ba5  [Cypress: Config Manager]
 6: 0xf5908d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [Cypress: Config Manager]
 7: 0xf3378e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [Cypress: Config Manager]
 8: 0xf34b57 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [Cypress: Config Manager]
 9: 0xf15d2a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [Cypress: Config Manager]
10: 0x12dae9d v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [Cypress: Config Manager]
11: 0x1707b79  [Cypress: Config Manager]
```

**Comment by nemonemi** [comment] 2023-04-04 11:18
For me, it went away after I increased the `--max-old-space-size` to 4k. 
```
NODE_OPTIONS="--max-old-space-size=4096 nx ..."
```

This, however, should not be the first thing one reaches up for. We should understand why this is needed. If the Cypress starts consuming more resources, or similar, it should be documented, or at least warned about.

**Comment by nagash77** [comment] 2023-04-04 13:43
I would suggest folks in this thread upgrade to the latest version of Cypress and try running with the flag `experimentalMemoryManagement` set to true and see if this helps relieve memory pressure on the runner.

**Comment by nemonemi** [comment] 2023-04-04 13:45
I have to say I've tried it and it hasn't worked for me.

**Comment by nagash77** [comment] 2023-04-06 17:33
@nemonemi Can you please open a new issue with a reproducible example of your problem?  We will be happy to investigate.

I am going to close this issue as we do not have a reproducible example to go off of.  If anyone that is following this ticket has a similar problem please do open a new ticket with a reproducible example and mention this ticket in the description.

**Closed by nagash77** 2023-04-06 17:33 UTC

**Comment by nemonemi** [comment] 2023-04-11 08:40
@nagash77, although I understand the need for reproduction, it is often difficult to produce one because of time constraints and understanding of the problem.

I would hope that if enough people report the same problem with a description here, the Cypress team go about creating a reproduction based on said provided information and potentially share it when they couldn't reproduce it.
