### ISSUE TITLE
When browser refresh, Cypress becomes undefined

### ISSUE THREAD

**Issue by justin73** [cypress-io/cypress#8155] opened 2020-08-01 15:27 UTC
### Current behavior:
Tests run successfully for only once after Cypress is up and running. When tests are changed and re-run or simply click the refresh button on the browser, Cypress becomes undefined. 

![](https://files.gitter.im/5516368c15522ed4b3ddf3eb/iYfT/first-time-loading-fine.png)

![](https://files.gitter.im/5516368c15522ed4b3ddf3eb/eaDt/refresh-fail.png)

![2020-08-01 11_08_24-DevTools - playground horizon ubisoft org____](https://user-images.githubusercontent.com/3356603/89104482-ab1e0980-d3e7-11ea-9b13-5f432d666d34.png)

it works again once I manually clear the browser cache

### Desired behavior:

Be able to repeatedly running the tests when refreshing the browser or when changing files

### Test code to reproduce
I have a 3rd party single sign-on popup to get the credentials  in my app, so I need to stub the pop up when opening the page
```js
before(function () {
  cy.visit("/", {
    onBeforeLoad(win) {
      cy.stub(win, "open");
    },
    onLoad(win) {
      cy.stub(win.AdminConnect, "OpenLoginPopup", () => {
        console.log("open OpenLoginPopup");
      }).as("OpenLoginPopup");
      cy.stub(win.AdminConnect, "RequestSessionAsync", () => {
        console.log("open RequestSessionAsync");
      }).as("RequestSessionAsync");
    },
  })
    .then(() => {
      const str = `${Cypress.env("username")}:${Cypress.env("password")}`;
      const authorization = btoa(str);
      return cy.loginByAdminConnect({ authorization });
    })
    .then((res) => {
      const { sessionId, ticket } = res.body;
      Cypress.env("ticket", ticket);
      Cypress.env("sessionId", sessionId);
});
```

Authentication.spec.js
```js
  context("preparing for prerequisite state", () => {
    it("should fetch relevant data", () => {
      cy.window().its("Cypress").should("be.an", "object");
      cy.window()
        .its("store")
        .invoke("dispatch", {
          type: "SESSION_REFRESHED",
          session: {
            sessionId: Cypress.env("sessionId"),
            ticket: Cypress.env("ticket"),
            authenticated: true,
            isAuthenticating: false,
          },
        });
    })
  });
```

### Versions
**Cypress** : 4.11.0
**Chrome**: 84
**OS**: Win10

**Comment by jennifer-shehane** [comment] 2020-08-03 10:06
I'm not able to reproduce this with the code below. Can you run the code below and reproduce the issue? If not, there may be something else involved that is causing the issue that's particular to the project under test or the env you're running within.

```js
it('test', () => {
  cy.visit('https://example.cypress.io')
  cy.window().its('Cypress').should('be.an', 'object')
})
```

**Comment by jennifer-shehane** [comment] 2020-08-18 07:57
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-18 07:57 UTC
Labels: stage: needs information
