### ISSUE TITLE
cy.writeFiles runs into errors

### ISSUE THREAD

**Issue by JanUrb** [cypress-io/cypress#27097] opened 2023-06-21 08:30 UTC
### Current behavior

Hello, 
while integrating Cypress version 12.15.0 some of our tests failed with `PayloadTooLargeError: request entity too large`. The problematic test cases write files around 200 - 300 kb. Cypress UI shows the error message `cy.writeFile() must only be invoked from the spec or support file`

### Desired behavior

On Cypress 12.14.0 the same tests ran fine. 

### Test code to reproduce

https://github.com/JanUrb/cypress-test-writefiles-error

### Cypress Version

12.15.0

### Node version

v20.3.0

### Operating System

macOS 13.3.1

**Comment by dubzzz** [comment] 2023-06-21 10:03
I encounter exactly the same issue when bumping to 12.15.0 on Node 18.

**Comment by ddnexus** [comment] 2023-06-21 10:39
Same error with version 12.15.0 (working fine with 12.14.0) but a different origin, probably related to the size of the snapshot file:

```
"after all" hook: saveSnapshots for "Test ...":
     CypressError: `cy.writeFile()` must only be invoked from the spec file or support file.
```

**Comment by gabor-szallas** [comment] 2023-06-21 11:11
Same error, but with cy.readFile() after updating to 12.15.0

`cy.readFile() must only be invoked from the spec file or support file.`

**Comment by mike-plummer** [comment] 2023-06-21 21:03
We're aware of the "must only be invoked from the spec file or support file" issue and are looking into it now. Until a fix is identified, tested, and released you can temporarily downgrade to Cypress v12.14.0 which does not exhibit this issue.

**Comment by mike-plummer** [comment] 2023-06-21 21:05
This is a duplicate of #27099 which has a slightly more targeted description of the issue so I will close this in favor of that one

**Comment by JomyGeo** [comment] 2023-06-22 07:12
I am getting the same issue for the 12.4.0 version 

Issue 1 :
PayloadTooLargeError: request entity too large
    at p (<embedded>:2319:1358)
    at s.exports (<embedded>:2319:799)
    at s.exports (<embedded>:2338:1577)
    at <embedded>:2358:2007
    at a.handle_request (<embedded>:2640:1038)
    at d (<embedded>:2655:1285)

Issue 2 : CypressError: `cy.task()` must only be invoked from the spec file or support file.

Issue 3 : CypressError: `cy.writeFile()` must only be invoked from the spec file or support file.

**Comment by arundavid1987** [comment] 2023-06-22 08:42
![image](https://github.com/cypress-io/cypress/assets/6092834/bbc873af-417f-43e1-8f51-e3ada640ddda)

**Comment by mike-plummer** [comment] 2023-06-26 16:32
[Cypress v12.16.0](https://docs.cypress.io/guides/references/changelog#12-16-0) has just been released with a fix for the issue with cy.task, apologies for the oversight on that bug.

Thanks for using Cypress, everyone!

**Comment by bdimitrovski** [comment] 2023-06-27 13:17
This is still not resolved, as we are also getting the same error:

![ss](https://github.com/cypress-io/cypress/assets/4244896/d4262410-218c-428e-a64f-35492c95efcf)


The bespoke code resides in a custom class, which implements the `cy.writeFile()` function like so:

`cy.writeFile('cypress/support/data/paymentOrders/groupOrders.json', data);`

Is there a workaround for this, or is downgrading to 12.14.0 the only option?

**Comment by mike-plummer** [comment] 2023-06-27 13:50
Hi @bdimitrovski , sorry you're still having issues. We addressed an issue that was causing this error in 12.16.0 but it appears you've identified one or more edge cases we missed. Are you able to share a reproduction case we can use to troubleshoot?

**Comment by bdimitrovski** [comment] 2023-06-27 14:30
Hi @mike-plummer ,

Thanks for the quick reply.

Here's the repro code https://github.com/bdimitrovski/writefile-cy-issue, however, when I used the exact same function as in my real project, I could not get it to fail, it normally populates the file using `cy.writeFile`.

Is there anything else I could be missing?

**Comment by elGatoMantocko** [comment] 2023-06-27 18:22
Still able to reproduce https://github.com/cypress-io/cypress/issues/27099 via `cypress-localstorage-commands`.

https://github.com/cypress-io/cypress/issues/27099#issuecomment-1601573400

**Comment by chrisbreiding** [comment] 2023-06-28 13:13
@elGatoMantocko Thanks for the report. That will be helpful for debugging.

**Comment by chrisbreiding** [comment] 2023-06-28 13:32
> Here's the repro code [bdimitrovski/writefile-cy-issue](https://github.com/bdimitrovski/writefile-cy-issue), however, when I used the exact same function as in my real project, I could not get it to fail, it normally populates the file using cy.writeFile.
> 
> Is there anything else I could be missing?

@bdimitrovski It's tricky to say, since that's the information we'd be trying to use the reproduction to suss out. It could be something different with how the project is structured, as in which file the function that calls `cy.writeFile` is defined. It could a difference in how the spec code is calling it. It could be useful if you posted your `cypress.config.js` or as much of it as you can.

There's two known issues that cause this error right now (and are in the process of being fixed), so I would first check to see if your project code is encountering it because of one of these:

- The command is called with an extra argument that isn't part of its API, as in `cy.writeFile('file.txt', 'contents', 'utf-8', { log: false }, { flag: 'w' })`. In that case, the `{ flag: 'w' }` object should be part of the `{ log: false }` object.
- The command is called with a trailing `undefined` argument. This usually happens when one of the arguments is a variable, like:

```js
function writeFile (options) {
  cy.writeFile('file.txt', 'contents', options)
}

writeFile()
```

**Comment by Jacek-fstack** [comment] 2023-06-30 06:32
I have the same issue - only showing up in headless mode
example:
```
  cy.writeFile('cypress/fixtures/10Users.csv', data, (err) => {
      if (err) { cy.log(err); } else {
        cy.log('File written successfully\n');
      }
    });
```
inside of the spec file

**Comment by bdimitrovski** [comment] 2023-06-30 08:17
> > Here's the repro code [bdimitrovski/writefile-cy-issue](https://github.com/bdimitrovski/writefile-cy-issue), however, when I used the exact same function as in my real project, I could not get it to fail, it normally populates the file using cy.writeFile.
> > Is there anything else I could be missing?
> 
> @bdimitrovski It's tricky to say, since that's the information we'd be trying to use the reproduction to suss out. It could be something different with how the project is structured, as in which file the function that calls `cy.writeFile` is defined. It could a difference in how the spec code is calling it. It could be useful if you posted your `cypress.config.js` or as much of it as you can.
> 
> There's two known issues that cause this error right now (and are in the process of being fixed), so I would first check to see if your project code is encountering it because of one of these:
> 
> * The command is called with an extra argument that isn't part of its API, as in `cy.writeFile('file.txt', 'contents', 'utf-8', { log: false }, { flag: 'w' })`. In that case, the `{ flag: 'w' }` object should be part of the `{ log: false }` object.
> * The command is called with a trailing `undefined` argument. This usually happens when one of the arguments is a variable, like:
> 
> ```js
> function writeFile (options) {
>   cy.writeFile('file.txt', 'contents', options)
> }
> 
> writeFile()
> ```

@chrisbreiding thanks for looking into this -  here' a part of my `cypress.config.js` file:

```ts
const { defineConfig } = require('cypress');
const fs = require('fs-extra');
const path = require('path');

function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve('..', 'cypress/cypress/config', `${file}.config.json`);

  return fs.readJson(pathToConfigFile);
}

module.exports = defineConfig({
  reporter: 'cypress-multi-reporters',
  reporterOptions: {
    configFile: 'reporter-config.json'
  },
  e2e: {
    responseTimeout: 30000,
    requestTimeout: 30000,
    viewportWidth: 1440,
    viewportHeight: 900,
    baseUrl: "http://localhost:8080/",
    supportFile: "cypress/support/e2e.js",
    video: false,
    trashAssetsBeforeRuns: true,
    env: {
      username: "**********",
      password: "**********",
      apiBaseUrl: "**********",
      docsUrl: "**********"
    },
    specPattern: "cypress/e2e/**/*.spec.ts",
    setupNodeEvents(on, config) {
      const loggerOptions = {
        outputRoot: `${config.projectRoot}/cypress/reports/logs`,
        outputTarget: {
          'verbose.log': 'txt',
          'verbose.json': 'json'
        }
      }

      require('cypress-mochawesome-reporter/plugin')(on);
      require('cypress-terminal-report/src/installLogsPrinter')(on, loggerOptions);

      on('task', {
        getDownload: () => {
          const downloadsFolder = config['downloadsFolder'];

          if (!fs.existsSync(downloadsFolder)) {
            fs.mkdirSync(downloadsFolder);
          }

          return new Promise((resolve, reject) => {
            const watcher = fs.watch(downloadsFolder, (eventType, filename) => {
              if (eventType === 'rename' && !filename.endsWith('.crdownload') && !filename.endsWith('.part')) {
                resolve(filename);
                watcher.close();
              }
            });

            setTimeout(reject, config.taskTimeout);
          });
        }
      });

      const file = config.env.configFile || 'dev';

      return getConfigurationByFile(file);
    },
  },
});
```

I do not see anything outstanding here that could cause issues with `cy.writeFile()` inside some custom class though.

**Comment by rashmiranjanbhoi** [comment] 2023-07-03 14:26
I have the same issue - only showing up in headless mode in Cypress version 12.16.0

![image](https://github.com/cypress-io/cypress/assets/57247500/2b7c224c-c7d1-486b-9b81-bc89f5bc1740)


Note :- This is inconsistent; occasionally it succeeds, occasionally it fails.

**Comment by bimanpathirage** [comment] 2023-07-05 11:02
> We're aware of the "must only be invoked from the spec file or support file" issue and are looking into it now. Until a fix is identified, tested, and released you can temporarily downgrade to Cypress v12.14.0 which does not exhibit this issue.

Can I please know the way to downgrade the version? TIA

**Comment by MikeMcC399** [comment] 2023-07-05 13:06
@bimanpathirage 

> Can I please know the way to downgrade the version? TIA

If you are using npm, then simply

```bash
npm install cypress@12.14.0 --save-dev --exact
```

For Yarn

```bash
yarn add cypress@12.14.0 --dev --exact
```

**Comment by bahmutov** [comment] 2023-07-06 19:55
Reproducible example (still fails with 12.17.0) in https://github.com/bahmutov/cypress-examples/pull/174
Can be seen in branch `12.16`
```
npx cypress run --spec ./docs/commands/files.md,./docs/recipes/collect-headings.md

  Running:  commands/files.md                                                               (1 of 2)


  Files
    ✓ cy.fixture() - load a fixture (767ms)
    - cy.fixture() or require - load a fixture
    ✓ cy.readFile() - read file contents (75ms)
    1) cy.writeFile() - write to a file
    2) cy.writeFile() - write combined JSON object
    3) cy.writeFile() - write combined JSON array


  2 passing (3s)
  1 pending
  3 failing

  1) Files
       cy.writeFile() - write to a file:
     CypressError: `cy.writeFile()` must only be invoked from the spec file or support file.
      at <unknown> (http://localhost:65471/__cypress/runner/cypress_runner.js:146497:87)
      at tryCatcher (http://localhost:65471/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:65471/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:65471/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:65471/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:65471/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:65471/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:65471/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:65471/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:65471/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:65471/__cypress/tests?p=docs/commands/files.md)
```

**Comment by chrisbreiding** [comment] 2023-07-07 15:20
Thanks for the repro, @bahmutov! That's a new edge case and being able to reproduce it will help a lot in debugging it.

**Closed as completed** 2023-07-12 17:09 UTC
