### ISSUE TITLE
TypeScript 5.x and Node 18.18, cypress can't build

### ISSUE THREAD

**Issue by gplusdotgr** [cypress-io/cypress#28052] opened 2023-10-13 08:45 UTC
### Current behavior
```js
// cypress.config.js
import { defineConfig } from "cypress"

export default defineConfig({
  projectId: "dbzk5w",
  video: false,
  viewportWidth: 1440,
  viewportHeight: 768,
  scrollBehavior: "center",
  screenshotOnRunFailure: false,
  fixturesFolder: false,
  e2e: {
    specPattern: "cypress/integration/**/*",
    baseUrl: "http://localhost:3000",
    setupNodeEvents() {
      // implement node event listeners here
    },
  },
})

```

 pnpm cypress

> request-frontend@0.0.1 cypress /Users/gkatsanos/repos/visable/requests-frontend
> cypress run

```
DevTools listening on ws://127.0.0.1:61881/devtools/browser/47282436-ad31-4f94-9789-b5cbb52eaf2e
/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:311
        return new TSError(diagnosticText, diagnosticCodes, diagnostics);
               ^
TSError: ⨯ Unable to compile TypeScript:
error TS5095: Option 'bundler' can only be used when 'module' is set to 'es2015' or later.

    at createTSError (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:311:16)
    at reportTSError (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:314:23)
    at /Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:686:17
    at Object.compile (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:743:35)
    at Module.m._compile (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:856:36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.require.extensions.<computed> [as .js] (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 5095 ]
}
```

### Test code to reproduce
```json
// package.json

{
  "name": "request-frontend",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "start": "NODE_OPTIONS='-r dd-trace/init' HOST=localhost PORT=3000 node ./dist/server/entry.mjs",
    "astro": "astro",
    "locales:generate": "node src/helpers/generateLocale.cjs",
    "cypress": "cypress run",
    "cypress:open": "cypress open"
  },
  "lint-staged": {
    "**/*.ts": "tsc-files --noEmit",
    "*.{js,css,md,astro,vue}": "prettier --write --config ./.prettierrc.mjs --ignore-path ./.prettierignore --list-different"
  },
  "dependencies": {
    "@astrojs/check": "^0.2.0",
    "@astrojs/node": "^6.0.3",
    "@astrojs/tailwind": "^5.0.2",
    "@astrojs/ts-plugin": "^1.1.1",
    "@astrojs/vue": "^3.0.1",
    "@nanostores/logger": "^0.2.3",
    "@nanostores/vue": "^0.10.0",
    "@visable-dev/design-tokens": "3.1.2",
    "@visable-dev/routing": ">= 10.1.0",
    "@visable-dev/styleguide": "^36.3.0",
    "@visable-dev/tracking": ">= 4.0.1",
    "@visable-dev/ui-components": "^1.10.2",
    "@visable-dev/ui-icons": "0.0.7",
    "@visable-dev/vue": "^21.7.0",
    "@visable-dev/wlw-tailwindcss-config": "^4.0.0",
    "astro": "^3.2.4",
    "await-to-js": "^3.0.0",
    "axios": "^1.3.6",
    "dd-trace": "^4.11.1",
    "ipaddr.js": ">=2.1.0",
    "nanostores": "^0.9.3",
    "sharp": "^0.32.5",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.2.2",
    "vue": "^3.3.4",
    "weighted-random": "^0.1.0"
  },
  "engines": {
    "node": ">=16.16.0",
    "pnpm": ">=8"
  },
  "devDependencies": {
    "@gkatsanos/vite-svg-loader": ">=1.3.0",
    "cypress": "^13.3.1",
    "husky": "^8.0.3",
    "lint-staged": "^14.0.1",
    "prettier": "^3.0.2",
    "prettier-plugin-astro": "^0.12.0",
    "prettier-plugin-tailwindcss": "^0.5.3",
    "sass": "^1.62.0",
    "tsc-files": "^1.1.4"
  }
}
```

### Cypress Version

13.3.1

### Node version

18.18

### Operating System

mac

### Debug Logs

```shell
pnpm cypress

> request-frontend@0.0.1 cypress /Users/gkatsanos/repos/visable/requests-frontend
> cypress run


DevTools listening on ws://127.0.0.1:61881/devtools/browser/47282436-ad31-4f94-9789-b5cbb52eaf2e
/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:311
        return new TSError(diagnosticText, diagnosticCodes, diagnostics);
               ^
TSError: ⨯ Unable to compile TypeScript:
error TS5095: Option 'bundler' can only be used when 'module' is set to 'es2015' or later.

    at createTSError (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:311:16)
    at reportTSError (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:314:23)
    at /Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:686:17
    at Object.compile (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:743:35)
    at Module.m._compile (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:856:36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.require.extensions.<computed> [as .js] (/Users/gkatsanos/Library/Caches/Cypress/13.3.1/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 5095 ]
}
```

### Other

no

**Comment by rikzwarthoff** [comment] 2023-11-01 13:18
Having the same issue here, related to previous issue. 
https://github.com/cypress-io/cypress/issues/26308
https://github.com/cypress-io/cypress/issues/27448

Using temp fix: https://github.com/cypress-io/cypress/issues/26308#issuecomment-1663592648

- node 18.18.2
- cypress 13.4.0
- typescript 5.2.2

**Comment by jennifer-shehane** [comment] 2023-11-27 18:50
Duplicate of https://github.com/cypress-io/cypress/issues/27731

**Closed as completed by jennifer-shehane** 2023-11-27 18:50 UTC
Labels: type: duplicate
