### ISSUE TITLE
cy.intercept delay does nothing if statusCode: 204

### ISSUE THREAD

**Issue by scott-maddox** [cypress-io/cypress#15249] opened 2021-02-26 15:13 UTC
### Current behavior
In the following test snippet, `delay` does nothing.

```js
cy.intercept('POST', '/api/share', { statusCode: 204, delay: 1000 }).as('api-share');
cy.get('@share-button').click();
cy.get('#share-modal').should('exist');
cy.get('@share-button').should('be.disabled');
cy.get('@cancel-button').should('be.disabled');
cy.get('#loading-spinner').should('exist');
cy.wait('@api-share')
  .its('response.statusCode').should('eq', 204);
```

<img width="553" alt="image" src="https://user-images.githubusercontent.com/3509144/109316017-c8497800-7810-11eb-903c-0512256c4e5f.png">

If I change `statusCode: 204` to `statusCode: 200`, though, then the request is correctly delayed:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/3509144/109316073-dbf4de80-7810-11eb-9e69-7af7a7ff3b4f.png">

### Desired behavior

It should be possible to delay requests even with `statusCode: 204`.

### Test code to reproduce

See above. I'm not sure how best to put together a minimum complete reproduction (is there any easy way to have cypress run against a static html file?).

### Versions

```
"cypress": {
      "version": "6.5.0",
      "resolved": "https://registry.npmjs.org/cypress/-/cypress-6.5.0.tgz",
      "integrity": "sha512-ol/yTAqHrQQpYBjxLlRSvZf4DOb9AhaQNVlwdOZgJcBHZOOa52/p/6/p3PPcvzjWGOMG6Yq0z4G+jrbWyk/9Dg==",
```

**Comment by jennifer-shehane** [comment] 2021-02-26 17:38
Duplicate of https://github.com/cypress-io/cypress/issues/15188

**Closed by jennifer-shehane** 2021-02-26 17:38 UTC
