### ISSUE TITLE
file watch is not reliable on linux

### ISSUE THREAD

**Issue by acthp** [cypress-io/cypress#1058] opened 2017-12-12 03:03 UTC
- Operating System: ubuntu 14.04
- Cypress Version: 1.1.4
- Browser Version: chrome 60

### Is this a Feature or Bug?
bug

### Current behavior:
UI stops responding to file updates

### Desired behavior:
UI consistently responds to file updates

### How to reproduce:
Unclear. It happens very regularly, like every 5 minutes or so, during regular use. I sometimes convince myself that it happens after an error, like a syntax error in the spec file, but I've never been able to invoke the bug by introducing errors.

Once this state occurs, it can only be cleared by killing the cypress process and restarting. Hitting 'stop' on the UI, and restarting the spec file doesn't help. Neither does reloading the browser tab. It will never pick up changes to the spec file until the cypress process is killed and restarted.

Also, to be clear, this never happens on OSX.

**Comment by jennifer-shehane** [comment] 2017-12-12 15:18
@acthp This sounds very similar to this issue we found in v1.1.3 and was thought to be fixed in v1.1.4, could you try the steps from this issue and see if this reproduces the 'stop watching' behavior? Maybe there is something we missed in linux specifically with the bug fix. 

**Previous Issue:** https://github.com/cypress-io/cypress/issues/1018

**Comment by Bkucera** [comment] 2018-02-16 19:53
You may want to check out this thread, because linux can run into problems with the inotify limit of the kernel: https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

**Comment by jennifer-shehane** [comment] 2019-01-09 07:41
@acthp Any update on this from your end?

**Comment by jennifer-shehane** [comment] 2019-03-14 09:48
Closing as stale. No response in over a year. Please comment if you are still experiencing this issue.

**Closed by jennifer-shehane** 2019-03-14 09:48 UTC
Labels: OS: linux, stage: needs information
