### ISSUE TITLE
Cypress will convert double space to a single space.

### ISSUE THREAD

**Issue by reuben-rodrigues** [cypress-io/cypress#6397] opened 2020-02-10 16:20 UTC
### Current behavior:
```js
cy.get('.options-panel').contains('option', 'firstname  lastname').click()
```

**There should be two spaces between firstname and lastname.**

When running cypress, the log will show it is looking for "firstname lastname" containing only a single space between the names and therefore not find the value.

### Desired behavior:

Should allow for multiple spaces to be found. Works as intended in 3.8.3.

```js
cy.get('.options-panel').contains('option', 'firstname  lastname').click().
```

I have only tested this with an options panel that contained a name with two spaces separating each.

### Versions

4.0.1

**Comment by c32hedge** [comment] 2020-02-10 23:14
@reuben-rodrigues I encountered this as well and entered #6405 -- I included a link there to the migration documentation that indicates that this was an intentional (though as it turns out, incomplete, IMO) breaking change in 4.0.*.

Also, it looks like GitHub won't preserve spaces even in `code` formatting unless you use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks), so your examples appear to have only one space in the call to `contains`.

**Comment by jennifer-shehane** [comment] 2020-02-11 07:57
Yes, this behavior was an [intentional breaking change of 4.0](https://on.cypress.io/migration-guide#cy-contains-ignores-invisible-whitespaces), so is expected behavior. 

However, we are looking into adding an option to opt out of ignoring the invisible whitespaces in `cy.contains()`. Duplicate of #6405

**Closed by jennifer-shehane** 2020-02-11 07:57 UTC
