### ISSUE TITLE
baseUrl in extended cypress config can't be overwritten by environment variable 

### ISSUE THREAD

**Issue by timnederhoff** [cypress-io/cypress#16373] opened 2021-05-06 14:17 UTC
### Current behavior
In my usecase I use the cypress.json config, and extends it in separate cypress-e2e.json and cypress-smoke.json to have different baseUrls for different environments. But sometimes however I want to run tests on another environment, i.e. on another baseUrl. Preferably I want to run that test from CI with the command argument "CYPRESS_BASE_URL=https://example.com cypress run... etc", but it occurs to me that the baseUrl isn't overwritten by my command line options as long as I have the cypress.json extended in one of my other config files.

### Desired behavior
The environment variables matching configuration properties should always overwrite properties from the config file(s).

### Test code to reproduce
CYPRESS_BASE_URL="https://example.environment3.com" cypress run --config-file smoketest-cypress.json

cypress.json:
```json
"baseUrl": "https://example.environment1.com",
...other properties
```

smoketest-cypress.json:
```json
"extends": "./cypress.json",
"baseUrl": "https://example.environment2.com"
```

### Versions
Cypress version: 7.0.1
OS: MacOS Big Sur
Node: v14.16.0

**Comment by jennifer-shehane** [comment] 2021-05-06 19:01
Duplicate of https://github.com/cypress-io/cypress/issues/15606 

Looks like there's a lot of confusion over how this works. Someone mentioned that setting `--env baseUrl=https://new.url` may work. Gonna try and play around with it.

**Closed by jennifer-shehane** 2021-05-06 19:01 UTC

**Comment by timnederhoff** [comment] 2021-05-14 08:59
I don't agree this is a duplicate of #8680. Maybe the root cause is the same. But in my case the CYPRESS_BASE_URL variable is ignored when using a config file that extends another config file (e.g. cypress.json). To me, it looks like the command line variables like CYPRESS_BASE_URL are overwritten by the extended config file. While I would expect that command line variables overwrite properties in the (extended) config file.

**Comment by jennifer-shehane** [comment] 2021-05-17 19:35
I'm not sure that our config fully supports extends: https://github.com/cypress-io/cypress/issues/5674

But yah, I think the issue in general is a lack of consistent, documented application of how configuration is resolved. It doesn't always resolve as expected, which is what https://github.com/cypress-io/cypress/issues/8680 basically covers.
