### ISSUE TITLE
Feature request: Support `delay: false` in `cy.type`

### ISSUE THREAD

**Issue by Svish** [cypress-io/cypress#6273] opened 2020-01-30 14:08 UTC
Trying to test that a textarea indeed has an enforced max length of 500. To test it, I'm first filling it with 500 characters, and then trying to type some more.

### Current behavior:

Even with `{ delay: 0 }` it takes quite a while to fill up the textarea.

```js
    it('Should allow max 500 characters', () => {
      cy.get('#maxlength').should('have.text', '500');

      cy.fixture('max-length-feedback').then(text => {
        expect(text).to.have.length(500);
        cy.get('#input')
          .type(text, { delay: 0 })
          .should('have.value', text)
          .type('more')
          .should('have.value', text);
      });
    });
```

### Desired behavior:

Would be super handy if I could pass `{ delay: false }`, which would then just dump the whole string at once and then trigger an event afterwards instead, as if the text was pasted.

### Versions

**Cypress:** 3.8.3

**Comment by Svish** [comment] 2020-01-30 14:11
I've already tested various combinations of `.invoke('val', text').trigger('change')`, `.then($input => $input.val(text)).trigger('change')`, etc., but for some reason these just aren't picked up by React. Typing does work fine though, so would be nice if it was just possible to type _really_ fast or just paste a value.

**Comment by jennifer-shehane** [comment] 2020-01-31 08:43
Yeah, this is a bit difficult because it wouldn't really be typing or mimicking any real life user behavior if you just plop the entire text in, so what would this actually be testing? 

Each key that is typed triggers several events and triggering 500 key events at once wouldn't be implementing the behavior of any real user either, so then we've just made this psuedo behavior that is the equivalent of `$input.val(text)` with some additional events that wouldn't naturally be triggered in that amount of time.

Likely whatever your React component is listening for is one of the various events that is triggered when you actually type that is triggered during `.type()`, if you can narrow down exactly which event the component needs for your behavior to be tested, then use `.trigger()` to trigger that event. 

If you want to test copy/paste - there are other issues requesting this feature https://github.com/cypress-io/cypress/issues/2851

I am leaning towards this being a feature we would not implement (outside of the copy/paste issue above). Any additional thoughts @Bkucera

**Comment by Svish** [comment] 2020-02-01 21:52
"so what would this actually be testing", well, nothing of course, but it would be part of setting things up for a test. 

Anyways, being able to paste a chunk of text from a Cypress test would also solve it for me, and would be the way a user like myself would do it. For example if I had written a chunk of text in a text editor, and then pasted it into a text area on a website.

**Comment by jennifer-shehane** [comment] 2020-02-04 06:52
Then I will close this as a duplicate of the issues for copy/paste in Cypress. Related issues:

- Enable access to clipboard in test https://github.com/cypress-io/cypress/issues/2752
- Using document.execCommand("copy") https://github.com/cypress-io/cypress/issues/2851
- copy + paste using modifier keys: https://github.com/cypress-io/cypress/issues/2386

**Closed by jennifer-shehane** 2020-02-04 06:52 UTC

**Comment by jennifer-shehane** [comment] 2020-08-24 05:37
@DanielFerrariR Could you open a pull request to add this plugin to our [documentation](https://on.cypress.io/plugins)? Thanks! [PR Template here.](https://github.com/cypress-io/cypress-documentation/blob/develop/.github/PULL_REQUEST_TEMPLATE/plugin_template.md)

**Comment by alexp1980** [comment] 2020-12-15 11:52
> I created a npm package that is working on React with Material-UI in the lastest version:
> 
> [cypress-fill-command](https://www.npmjs.com/package/cypress-fill-command)
> 
> I used some info collected from all related posts, so, if you feel that you need to be tagged on it to give properly credit, contact me.

Hi @DanielFerrariR,

I've tried using you fill command, but we have a 'Next' button that apparently works off the onChange event, but does not activate when using your command. Manually typing in each field will trigger it though. Have you come across any similar issues?

Thanks

**Comment by DanielFerrariR** [comment] 2020-12-15 12:01
@alexp1980 Hi, please open an issue in fill command repository, telling me the framework used and a way to reproduce the issue. Thanks!

**Comment by ssorallen** [comment] 2024-03-14 14:47
> Yeah, this is a bit difficult because it wouldn't really be typing or mimicking any real life user behavior if you just plop the entire text in, so what would this actually be testing?

This is actually how Apple decided to implement [automatic passcode filling from SMS](https://support.apple.com/guide/iphone/automatically-fill-in-sms-passcodes-iphc89a3a3af/ios) (and from email). There may be a more relevant issue, but I have yet to find relevant documentation in Cypress. This old `fill` command may be what's required to mimic the behavior of iOS's passcode filling.

The event ends up being `{ type: "textInput", data: { "123456" }}` whereas Cypress is designed to type one character at a time like a human would.
