### ISSUE TITLE
Running lighthouse in Cypress stops working after upgrade to v. 13.5.0

### ISSUE THREAD

**Issue by basiaBB** [cypress-io/cypress#28511] opened 2023-12-12 16:16 UTC
### Current behavior

After upgrading Cypress to version 13.5.0 when lighthouse opens new tab there is an issue that Cannot GET /xyz. In console I can see 404 for it. For version 13.4.0 it works properly.

### Desired behavior

Cypress Lighthouse properly open app in the new tab and run performance audit.

### Test code to reproduce

`cy.lighthouse(thresholds, options, config)` using `@cypress-audit/lighthouse/commands` for that.

### Cypress Version

13.5.0

### Node version

18.16.0

### Operating System

macOS 14.1.1

### Other

Reporting again same issue because https://github.com/cypress-io/cypress/issues/28430 has not been resolved and nobody responds to the comments.

**Comment by jennifer-shehane** [comment] 2023-12-12 18:21
Duplicate of https://github.com/cypress-io/cypress/issues/28430

**Closed as completed by jennifer-shehane** 2023-12-12 18:21 UTC
Labels: type: duplicate
