### ISSUE TITLE
Many Cypress tests are hanging at the first Visit command during full runs (Electron only)

### ISSUE THREAD

**Issue by funatronics** [cypress-io/cypress#3662] opened 2019-03-06 23:58 UTC
### Current behavior:

In Electron, about one third of my tests are failing during a full run because it's hanging at the first Visit command (both headless and headed). Usually it's the same tests, but not always. When running alone, I do not experience this issue

Works correctly in Chrome 72.

### Steps to reproduce: (app code and test code)

Running all tests. When it hangs, I get this error:

`Your page did not fire its 'load' event within '60000ms'.`

However, it looks like everything had loaded:

<img width="452" alt="screen shot 2019-03-06 at 2 39 48 pm" src="https://user-images.githubusercontent.com/25094910/53922308-a43f6b80-4028-11e9-8296-06de34067afb.png">

Let me know if there is any other debug information I can provide.

### Versions

3.1.5
Electron 59

**Comment by jennifer-shehane** [comment] 2019-03-07 10:56
Could you provide the test code you are running? Also, are you sure that your application is indeed firing it's load event within this time? 

So, can you see if this is console.logging from your code?
```js
<script>
  window.addEventListener("load", function(event) {
    console.log("load event fired!");
  });
</script>
```

**Comment by funatronics** [comment] 2019-03-07 23:32
@jennifer-shehane : Test looks like this:

```
describe('Blah Blah Blah', function() {
  it('More Blah Blah', function(){
    var user = this.user; //User object
    var pageInformation = this.pages.addressBook; //Page object
    
    cy.visit(this.pages.home.url)
    
   //There are more Cypress commands, but it gets stuck at the Visit above
    })
  })
```

I edited the post above, but it's worth noting that this hanging does **not** occur in when running in Chrome 72.

**Comment by jbpallingayan** [comment] 2019-03-08 03:56
same experience for me. https://github.com/cypress-io/cypress/issues/2265
we experience this even chrome and electron.

**Comment by jennifer-shehane** [comment] 2019-03-08 08:58
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/2938

I'm curious is blacklisting some hosts as laid out in this comment may help the `load` event fire. https://github.com/cypress-io/cypress/issues/1608#issuecomment-384351857

**Closed by jennifer-shehane** 2019-03-08 08:58 UTC

**Comment by funatronics** [comment] 2019-03-09 03:34
FYI: I was able to fix this problem by blacklisting Google ad and tracking services hosts.
