### ISSUE TITLE
Cypress GUI window can open at non-existent coordinates.

### ISSUE THREAD

**Issue by baremaximum** [cypress-io/cypress#16337] opened 2021-05-05 10:59 UTC
### Current behavior
When starting cypress from the command line, no check is performed to make sure that the coordinates the window is opening at actually exist. As a result, the window will be unreachable.

This issue happens if the window is closed while on a second monitor. X and Y coordinates are saved to state, and the next time cypress is started, it will start at those coordinates. If the second monitor is removed after state is saved, but before cypress is started again, cypress will start the window at the coordinates in state, even though they don't exist anymore.

This can be fixed by either manually finding and editing the state object, plugging the second monitor back in and moving the window, or re-installing cypress.

### Desired behavior
The window opens somewhere that can be reached.

### Versions

**Cypress version:** 7.2.0
**OS:** Windows 10 Pro v.2004

**Comment by jennifer-shehane** [comment] 2021-05-05 13:56
Duplicate of https://github.com/cypress-io/cypress/issues/4606

**Comment by jennifer-shehane** [comment] 2021-05-05 13:56
You can fix it by following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data.

**Closed by jennifer-shehane** 2021-05-05 13:56 UTC
