### ISSUE TITLE
Multiple files, multiple beforeEach, not all run

### ISSUE THREAD

**Issue by nWidart** [cypress-io/cypress#1678] opened 2018-05-04 07:30 UTC
Hello,

### Current behavior: 

I have 2 test files, both have their `beforeEach` with some commands that stub xhr requests.
However, only one of the 2 `beforeEach` sections gets run. I do see it in the "Routes" section, but with 0 hits.

When I run both files in isolation, they work as expected.

Example command:

```js
Cypress.Commands.add('mockGetActivationsData', (fixture = 'getActivations.json') => {
  cy.server();
  cy.route('GET', '**/**/business-units/*/activations', `fixture:activations/${fixture}`);
});
```

### Desired behavior:

Each `beforeEach` section should allow commands to be fired to intercept xhr requests.

### Steps to reproduce:

Create 2 test files. Each of them have a `beforeEach` section that call a command, that stubs a XHR request.

**It works fine when I remove my command calls from every `beforeEach` section and duplicate them across every test.**

### Versions  

- cypress `2.1.0`
- chrome `66`

Thanks

**Comment by jennifer-shehane** [comment] 2018-05-04 14:14
When you run your tests with "run all" or using `cypress run` currently, we basically merge all of the test files together into one "big file". This will [change soon](https://github.com/cypress-io/cypress/issues/681). 

I'm not exactly clear as to what is happening since there is no code provided for each spec file. Are you wrapping the `beforeEach` in each file within a `describe` or `context` block? I would suggest doing that so that each file has it's appropriate `beforeEach` defined for the context of the file when they get merged into 1 file.

**spec_file1.js**
```js 
describe('File 1 tests', () => {
  beforeEach(() => {
    // commands here
  })
})
``

**spec_file2.js**
```js 
describe('File 2 tests', () => {
  beforeEach(() => {
    // commands here
  })
})
``

**Comment by nWidart** [comment] 2018-05-04 14:17
I have indeed 1 global before each in each file, *and* before each in describes.

I don't see what code could clarify this as it's straightforward but:

The global one:

```js
beforeEach(() => {
  cy.mockAllUnhandledHttpCalls();
  cy.mockGetAuthenticationData();
  cy.mockGetBusinessUnitData();
  cy.mockGetPermissionsData();
  cy.mockGetNavigationData();

  cy.mockGetActivationPartnersData();
});

```

In describe:

```js
describe('when all activation partners have activations', () => {
  beforeEach(() => {
    cy.visit('/activations?clientId=8021&companyBusinessUnitId=106007');
    cy.mockGetActivationPartnersData();
    cy.mockGetActivationsData();
  });
  it('should display a list of activations', () => {
    cy.get('.activation').should('have.length', 2);
  });
```

**Comment by brian-mann** [comment] 2018-05-04 14:35
I am 100% sure there is not a bug in the way this works - but there is likely a misunderstanding of how it works.

Hooks come from `mocha` and they definitely work as advertised. they are added in the order they appear. Having multiple root level `beforeEach` or `before` hooks will all work together. I would put a `console.log` or `debugger` statement in each and I'm very confident they will indeed work and fire.

For us to look at this you'll need to put together a reproducible repo with two test files and the code that you're describing. Just add something like `console.log(...)` to show that they are indeed hitting.

**Comment by nWidart** [comment] 2018-05-04 14:36
I have only one root level beforeEach _per file_. The issue is apparently when merging multiple files together.

**Comment by jennifer-shehane** [comment] 2018-05-04 16:25
If you want to run a `beforeEach` globally shared and run before every file, I suggest you put it in a `support` file as outline [here](https://on.cypress.io/writing-and-organizing-tests#Support-file).

I'd have to investigate more on whether this is an issue - but this is a suggestion for now.

**Comment by nWidart** [comment] 2018-05-04 16:28
Thank you.
The issue, however, is more than about the global beforeEach in those 2 files. I could indeed extract those out, even though I need custom global before each in each file, which makes this not possible.

Every before each the in the second test didn't get touched, making the test fail. The workaround is to copy the code in the multiple beforeEach blocks in every test, which works but provides a lot of code duplication.

**Comment by jennifer-shehane** [comment] 2018-05-04 16:35
Can you just wrap a larger describe within each file to contain the global `beforeEach` as described in my original comment?

**file1.js**
```js
describe('file 1 something', () => {
  beforeEach(() => {
    cy.mockAllUnhandledHttpCalls();
    cy.mockGetAuthenticationData();
    cy.mockGetBusinessUnitData();
    cy.mockGetPermissionsData();
    cy.mockGetNavigationData();

    cy.mockGetActivationPartnersData();
  });

  describe('something', () => {
    beforeEach(() => {
      cy.visit('/activations');
      cy.mockGetActivationPartnersData();
      cy.mockGetActivationsData();
    });
    it('should display a list of activations', () => {
      cy.get('.activation').should('have.length', 2);
    });
  });
});
```

**file2.js**
```js
describe('file 2 something', () => {
  beforeEach(() => {
    cy.mockAllUnhandledHttpCalls();
    cy.mockGetAuthenticationData();
    cy.mockGetBusinessUnitData();
    cy.mockGetPermissionsData();
    cy.mockGetNavigationData();

    cy.mockGetActivationPartnersData();
  });

  describe('something', () => {
    beforeEach(() => {
      cy.visit('/activations');
      cy.mockGetActivationPartnersData();
      cy.mockGetActivationsData();
    });
    it('should display a list of activations', () => {
      cy.get('.activation').should('have.length', 2);
    });
  });
});
```

**Comment by nWidart** [comment] 2018-05-04 17:04
I have beforeEach sections in multiple `describe` "blocks", which don't get called.

**Comment by jennifer-shehane** [comment] 2018-05-04 18:08
Ok, so, I should have taken a closer look to begin with at what the code was doing . You made the assertion that the `beforeEach` was not working - and I jumped into that assumption, but I believe the issue is how the order of these commands are structured. 

You will *always* want to set up `cy.server()` and `cy.route()` before calling a `cy.visit()`. The route definition is saying - "listen for these xhr requests", so if they are not set up before the visit...the xhr requests could have already gone out by the time you tell them to listen. 

I think the reason these routes are not being mocked is because you are defining them after the `cy.visit()` here:

```
  beforeEach(() => {
    cy.visit('/activations');
    cy.mockGetActivationPartnersData();
    cy.mockGetActivationsData();
  });
```

This should be:

```
  beforeEach(() => {
    cy.mockGetActivationPartnersData();
    cy.mockGetActivationsData();
    cy.visit('/activations');
  });
```

I'm actually a bit confused how your last example could be working reliably on every run.

If this doesn't help, I think we need to take a step back and have you define what exactly about this is "not working" in the runner exactly. They're not being stubbed? What does the screenshot of the test runner show?

**Comment by nWidart** [comment] 2018-05-04 18:10
I was indeed mocking the xhr calls before `cy.visit()` this is what is not working with running multiple files.

**Comment by jennifer-shehane** [comment] 2018-05-04 18:28
phew, I didn't think `beforeEach` could be this busted since we use it extensively every day for our own tests. 😅 

Let us know if you have any other issues - or ask in our community chat https://gitter.im/cypress-io/cypress

**Comment by nWidart** [comment] 2018-05-04 18:29
Hm so no resolution?

**Comment by nWidart** [comment] 2018-05-04 18:34
I'm not sure why this was closed...

Here's a screenshot of the dashboard with the failing tests.

![image](https://user-images.githubusercontent.com/882397/39646049-7db8ce3c-4fda-11e8-8c27-a32a7322fd70.png)

The routes section correctly shows the xhr requests to mock (even if duplicated), but they're just not getting hit.

**Comment by jennifer-shehane** [comment] 2018-05-04 18:50
The `cy.get('.activation-partner')` is only going to wait 4 seconds for that DOM element to be there before failing, so if your requests don't all respond within 4 seconds it will fail. 

You generally want to set up  `cy.wait()` to wait for each route to respond that is required for your application's view. This will not only provide an extra layer of tests for your routes, but also make the tests less brittle (instead of arbitrary 4 seconds, it will wait for all routes specifically) https://on.cypress.io/wait

**Comment by nWidart** [comment] 2018-05-04 18:52
Indeed, but the request never responds because it's not hit, ie the problem. :D  So no matter how long I wait, it'll never hit.

Again, this works fine when running the single test file on its own. It fails when running multiple files.

**Comment by jennifer-shehane** [comment] 2018-05-04 19:01
Yeah, we'll need a reproducible example of this behavior - the `beforeEach` not working as described. 

I'm unable to figure out why an example like below would not work with the information provided.

```js

Cypress.Commands.add('mockGetActivationsData', (fixture = 'getActivations.json') => {
  cy.server();
  cy.route('GET', '**/**/business-units/*/activations', `fixture:activations/${fixture}`).as("getActivations");
});

describe('something', () => {
  beforeEach(() => {
    cy.mockGetActivationsData();
    cy.visit('/activations');
  });

    it('should display a list of activations', () => {
      cy.wait("@getActivations")
      cy.get('.activation').should('have.length', 2);
    });
});
```

**Comment by nWidart** [comment] 2018-05-04 19:08
I tried with `.wait`:

![image](https://user-images.githubusercontent.com/882397/39647338-d889faa8-4fde-11e8-9374-1c5580864c41.png)

Where:

global beforeEach contains `cy.mockGetActivationPartnersData();`, which is:

```js
Cypress.Commands.add('mockGetActivationPartnersData', (fixture = 'getActivationPartners.json') => {
  cy.server();
  cy
    .route('GET', '**/**/activation-partners', `fixture:activations/${fixture}`)
    .as('getActivationPartners');
});
```

And :`cy.mockGetActivationsData();`, is inside a before each of a describe block.

Which is 
```js
Cypress.Commands.add('mockGetActivationsData', (fixture = 'getActivations.json') => {
  cy.server();
  cy
    .route('GET', '**/**/program-manager-service/business-units/*/activations', `fixture:activations/${fixture}`)
    .as("getActivations");
});
```

The error message said it timed out waiting for the request, which I can see in the network tab.

**Comment by jennifer-shehane** [comment] 2018-05-04 20:59
Here's a simplified version of the pieces you are explaining from our example app. This example is passing. Maybe you could have this reflect what you are doing to get this to fail for me? I'm just unable to recreate this as being a `beforeEach` bug and honestly can't look into it any further without a reproducible example.

**spec1.js**
```js
beforeEach(() => {
  cy.server()
  cy.route('GET', 'comments/*', {
    'body': 'laudantium enim quasi est quidem magnam voluptate ipsam eos↵tempora quo necessitatibus↵dolor quam autem quasi↵reiciendis et nam sapiente accusantium',
    'email': 'Eliseo@gardner.biz',
    'id': 1,
    'name': 'id labore ex et quam laborum',
    'postId': 1,
  }).as('getComment')
})

context('Network Requests', () => {
  beforeEach(() => {
    cy.server()
    cy.route('POST', '/comments', 'foo').as('postComment')
    cy.visit('https://example.cypress.io/commands/network-requests')
  })

  it('cy.route() - route responses to matching requests', () => {
    let message = 'whoa, this comment does not exist'

    cy.get('.network-btn').click()
    cy.wait('@getComment').its('status').should('eq', 200)

    cy.get('.network-post').click()
    cy.wait('@postComment')
  })
})
```

**spec2.js**
```js
beforeEach(() => {
  cy.server()
  cy.route('POST', '/comments', 'foo').as('postComment')
})

context('Network Requests', () => {
  beforeEach(() => {
    cy.server()
    cy.route('GET', 'comments/*', {
      'body': 'laudantium enim quasi est quidem magnam voluptate ipsam eos↵tempora quo necessitatibus↵dolor quam autem quasi↵reiciendis et nam sapiente accusantium',
      'email': 'Eliseo@gardner.biz',
      'id': 1,
      'name': 'id labore ex et quam laborum',
      'postId': 1 }).as('getComment')
    cy.visit('https://example.cypress.io/commands/network-requests')
  })

  it('cy.route() - route responses to matching requests', () => {
    let message = 'whoa, this comment does not exist'

    cy.get('.network-btn').click()
    cy.wait('@getComment').its('status').should('eq', 200)

    cy.get('.network-post').click()
    cy.wait('@postComment')
  })
})
```

**Comment by jennifer-shehane** [comment] 2019-01-25 09:17
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Closed** 2019-02-15 17:42 UTC
Labels: stage: needs information, topic: hooks ↪

**Comment by zeralight** [comment] 2020-12-12 23:11
I am having the same issue.
In some test, I delay a network request to test a loading state.
```javascript
describe("...", () => {
  beforeEach(() => somethingA());
  describe("...", () => {
    beforeEach(() => cy.intercept("/foo", { delayMs: 2000 }).as("requestFoo"));

    it("...", () => {
      /* trigger action to request Foo */
      /* run asserts: OK */
      // cy.wait('@requestFoo')
    });
  });

  describe("...", () => {
    it("...", () => {
      /* none of the beforeEach runs here */
    });
  });
});

```

When I uncomment the line  **// cy.wait('@requestFoo'),** the issue disappears.

**Comment by jennifer-shehane** [comment] 2020-12-14 11:42
@zeralight Can you provide an example we can run completely? There's a lot of things not included in your example that may be affecting the way it runs. You can edit our tests against our example.cypress.io website, which has some routing. Repo to fork: https://github.com/cypress-io/cypress-example-kitchensink
