### ISSUE TITLE
Exceptions in after() don't show up in UI

### ISSUE THREAD

**Issue by danielschwartz85** [cypress-io/cypress#3348] opened 2019-02-06 12:11 UTC
### Current behavior
If after() is defined in root level (not in **describe** and not in **it**) and an error is thrown then the UI does not show the Error.
* tests **do** fail from CLI.
* probably related to: https://github.com/cypress-io/cypress/issues/2296

### Desired behavior
UI should show Exceptions thrown in after

### To reproduce 
See (there are 4 specs showing _weird_ behavior): 
https://github.com/danielschwartz85/after-error-not-shown

### Versions

Cypress 3.1.5
Ubuntu 18.04.1

Tnx.

**Comment by jennifer-shehane** [comment] 2019-05-02 09:00
Thanks for providing an example. Closing as duplicate of https://github.com/cypress-io/cypress/issues/2296

**Closed by jennifer-shehane** 2019-05-02 09:00 UTC
Labels: stage: ready for work, topic: unhandled exceptions ⚠️, type: bug
