### ISSUE TITLE
Not able to Run the testcases

### ISSUE THREAD

**Issue by kulkarnikavyashree31** [cypress-io/cypress#24939] opened 2022-12-02 10:32 UTC
### Current behavior

Taking more time to run the testcases and even some time not  even running the testcases 

### Test code to reproduce

not able to run the code 

### Cypress Version

9

### Node version

v18.12.1

### Operating System

windows

**Comment by nagash77** [comment] 2022-12-05 18:46
Hi @kulkarnikavyashree31 , I am sorry to hear you are having difficulties using Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-12-14 14:35
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-12-14 14:35 UTC
