### ISSUE TITLE
cy.visit() hangs when cy.on('url:changed') event listener is added

### ISSUE THREAD

**Issue by scommisso** [cypress-io/cypress#5576] opened 2019-11-01 20:46 UTC
### Current behavior:

If `cy.on('url:changed', _handler)` is called prior to using `cy.visit()`, the call hangs after successfully navigating (note it gets stuck on "Loading...")

<img width="375" alt="Screen Shot 2019-11-01 at 1 44 00 PM" src="https://user-images.githubusercontent.com/1964119/68055405-ccfa2c80-fcad-11e9-889c-f9cf4da89a67.png">

<img width="506" alt="Screen Shot 2019-11-01 at 1 44 09 PM" src="https://user-images.githubusercontent.com/1964119/68055543-1e0a2080-fcae-11e9-800e-4cc182ddae3a.png">

<img width="540" alt="Screen Shot 2019-11-01 at 1 44 13 PM" src="https://user-images.githubusercontent.com/1964119/68055546-1fd3e400-fcae-11e9-8a1b-9141d6a7cf34.png">

### Desired behavior:

- `cy.visit()` should complete successfully

### Steps to reproduce: (app code and test code)

See screenshot:
```js
  cy.on('url:changed', newUrl => {
    console.log('newUrl', newUrl);
  });
  cy.visit('https://httpstat.us/302'); // doesn't have to be a 302, but this links to another issue...
```

### Versions

- Cypress 3.4.1
- Electron 61

**Comment by jennifer-shehane** [comment] 2019-11-01 21:06
I'm not able to recreate this, which seems strange because I copy and pasted what you had exactly. Ran in osMac Mohave in Cypress 3.4.1 (and 3.6.0), tried Chrome and Electron 61. 

Do you have anything in your `cypress.json` or configuration anywhere set? Maybe a `baseUrl`?

My full test code

```js
it('visits', () => {
  cy.on('url:changed', (newUrl) => {
    console.log('newUrl', newUrl)
  })
  cy.visit('https://httpstat.us/302')
})
```

<img width="512" alt="Screen Shot 2019-11-01 at 5 03 20 PM" src="https://user-images.githubusercontent.com/1271364/68056520-bfeb3680-fcc9-11e9-83de-a679788987ba.png">

**Comment by jennifer-shehane** [comment] 2020-10-20 08:27
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-10-20 08:27 UTC
Labels: stage: needs information

**Comment by Temi89** [comment] 2021-07-06 14:12
Hi there this issue still very much exists how do we go about resolving it or do we need to pass in extra parameters ?

**Comment by jennifer-shehane** [comment] 2021-07-12 16:35
Calling Cypress commands such as `cy.log()` within Cypress event listerners does not work and will throw non-specific errors. https://github.com/cypress-io/cypress/issues/6316
