### ISSUE TITLE
Requests to `blockHosts` not being blocked consistently

### ISSUE THREAD

**Issue by aautem** [cypress-io/cypress#2714] opened 2018-11-02 23:01 UTC
### Current behavior:

I'm receiving a network error on a POST request to a URL I've added to the `blacklistedHosts` in my Cypress config. An identical POST request is made and ignored in a test that runs immediately before the test that fails. I can see that the request has the `x-cypress-match-blacklisted-host` response header with the blacklisted URL and a status code of `503 Service Unavailable`. Looking at the network traffic, I can see that there are numerous other requests to this URL that are correctly being blocked.

![test](https://user-images.githubusercontent.com/20647694/47944009-0e070780-dec7-11e8-822b-6a2d84f739a8.PNG)

![network](https://user-images.githubusercontent.com/20647694/47944015-19f2c980-dec7-11e8-8504-8f3f02c15f54.PNG)

### Desired behavior:

I expect the request to be blocked and the tests to continue running.

### Versions

Operating System: Microsoft Windows 10 Pro
Cypress Version: ^3.1.0
Browser Version: Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by dialex** [comment] 2019-07-03 20:21
I have a similar issue. I blacklisted a domain, and the tests that hit that domain have a 10-20% chance of failing. The test fails when the request to the blacklisted domain gets stalled. The expected behaviour would be to not wait for a response from that domain.

![Screenshot 2019-07-03 at 16 25 37](https://user-images.githubusercontent.com/2140450/60622318-ed85a900-9dd7-11e9-9913-d2184e2c6022.png)

This makes our tests flaky, which is a big disappointment.

**Comment by kriegster108** [comment] 2019-09-11 19:46
I am getting the exact issue @aautem is getting. We got a doubleclick.net service call in the backend returning a 503 and I put it into my blacklist file to try to avoid making the call, and it still trys to anyway. This ends up forcing cypress to wait 20+ seconds each time it has to navigate to the site

**Comment by jennifer-shehane** [comment] 2022-04-08 13:54
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 13:54 UTC
Labels: stage: needs investigating

**Comment by Darpanad** [comment] 2023-08-03 21:20
I'm encountering a similar problem with Cypress version 12.x.x. The requests are directed to the hosts specified in `blockHosts`, resulting in `503` errors that fill up the command log with unnecessary clutter, even though these errors are not genuine issues.

<img width="802" alt="Screenshot 2023-08-03 at 3 14 20 PM" src="https://github.com/cypress-io/cypress/assets/14354090/e23e6d22-a22c-4494-b530-60b7a160ce4b">

**Comment by MikeMcC399** [comment] 2023-08-04 07:04
@Darpanad 

Your screenshot matches the documentation [blockHosts](https://docs.cypress.io/guides/references/configuration#blockHosts)

![image](https://github.com/cypress-io/cypress/assets/66998419/396608bc-59f6-4314-b1af-238b6559adc4)

If you feel that there should be an option to blockHosts silently, then you should probably file a separate Feature request under https://github.com/cypress-io/cypress/issues/new/choose.
