### ISSUE TITLE
CYPRESS_NO_COMMAND_LOG=1 doesn't hide command logs in Cypress 10

### ISSUE THREAD

**Issue by olgamicollier** [cypress-io/cypress#22673] opened 2022-07-04 15:35 UTC
### Current behavior

In Cypress 10 passing environment variable  CYPRESS_NO_COMMAND_LOG=1 during 'cypress open' or 'cypress run' doesn't hide the command log

### Desired behavior

According to the documentation https://docs.cypress.io/guides/references/troubleshooting#Disable-the-Command-Log passing environment variable  CYPRESS_NO_COMMAND_LOG=1 during 'cypress open' or 'cypress run' should hide the command log

### Test code to reproduce

CYPRESS_NO_COMMAND_LOG=1 npx cypress run

### Cypress Version

10.3.0

**Comment by chrisbreiding** [comment] 2022-07-11 14:08
This is a duplicate of https://github.com/cypress-io/cypress/issues/21721 and will be fixed when https://github.com/cypress-io/cypress/pull/22641 is released.

**Closed by chrisbreiding** 2022-07-11 14:08 UTC
