### ISSUE TITLE
Cypress 13.6.1 crashes on Windows 11

### ISSUE THREAD

**Issue by PrakratiAgarwal123** [cypress-io/cypress#28567] opened 2023-12-21 13:38 UTC
### Current behavior

I have installed cypress for the first time on this present machine and cypress window opens and closes almost immediately when I run "npx cypress open". Cypress version is 13.6.1.
It opens once in a while and does not crash but most of the time, it does.

### Test code to reproduce

npx cypress open
cypress open

with admin priviledges

### Cypress Version

13.6.1

### Node version

v18.16.0

### Operating System

Windows 11

### Debug Logs

```shell
1. Logs when we use command cypress open from .bin folder-
 cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli parsed cli options {} +2s
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress\Cypress.exe +3ms
  cypress:cli Binary is executable? : true +4ms
  cypress:cli binaryDir is  C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress +1ms
  cypress:cli Reading binary package.json from: C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 13.6.1 installed in: C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress +7ms
  cypress:cli { verified: true } +10ms
  cypress:cli is Verified ? true +4ms
  cypress:cli opening from options {"project":"C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj\\node_modules\\.bin"} +0ms
  cypress:cli command line arguments ["--project","C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj\\node_modules\\.bin"] +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli spawn args [ '--', '--project', 'C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj\\node_modules\\.bin', '--cwd', 'C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj\\node_modules\\.bin', '--userNodePath', 'C:\\Program Files\\nodejs\\node.exe', '--userNodeVersion', '18.16.0' ] { detached: false, stdio: 'pipe', windowsHide: false } +3ms
  cypress:cli spawning Cypress with executable: C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress\Cypress.exe +2ms
  cypress:cli piping process STDIN into child STDIN +2s
  cypress:cli piping child STDOUT to process STDOUT +1ms
  cypress:cli piping child STDERR to process STDERR +0ms


DevTools listening on ws://127.0.0.1:61096/devtools/browser/b1a79fa2-1be7-40c9-b50f-e449ecc18847
AssignProcessToJobObject: (6) The handle is invalid.
[54760:1221/175902.206:ERROR:crashpad_client_win.cc(844)] not connected
  cypress:cli child event fired { event: 'exit', code: 4294930435, signal: null } +4s
  cypress:cli child event fired { event: 'close', code: 4294930435, signal: null } +1ms


2. Logs when we use npx cypress open from project path - 
 cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli parsed cli options {} +2s
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress\Cypress.exe +3ms
  cypress:cli Binary is executable? : true +3ms
  cypress:cli binaryDir is  C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress +1ms
  cypress:cli Reading binary package.json from: C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 13.6.1 installed in: C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress +7ms
  cypress:cli { verified: true } +11ms
  cypress:cli is Verified ? true +5ms
  cypress:cli opening from options {"project":"C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj"} +0ms
  cypress:cli command line arguments ["--project","C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj"] +1ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +1ms
  cypress:cli spawn args [ '--', '--project', 'C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj', '--cwd', 'C:\\LEO\\workspaces\\leo\\leo-workspace\\CypressProj', '--userNodePath', 'C:\\Program Files\\nodejs\\node.exe', '--userNodeVersion', '18.16.0' ] { detached: false, stdio: 'pipe', windowsHide: false } +4ms
  cypress:cli spawning Cypress with executable: C:\Users\e5619013\AppData\Local\Cypress\Cache\13.6.1\Cypress\Cypress.exe +4ms
  cypress:cli piping process STDIN into child STDIN +2s
  cypress:cli piping child STDOUT to process STDOUT +0ms
  cypress:cli piping child STDERR to process STDERR +1ms


DevTools listening on ws://127.0.0.1:61332/devtools/browser/0160c6fe-dff2-4040-af1c-31d5baa6f5d6
[39560:1221/180239.564:ERROR:network_service_instance_impl.cc(558)] Network service crashed, restarting service.
Error: ERR_FAILED (-2) loading 'http://localhost:61340/__launchpad/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:84929)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85316)
    at WebContents.emit (node:events:513:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'http://localhost:61340/__launchpad/index.html'
}
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +33s
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +1ms
```

### Other

RAM - 16 GB

**Comment by jennifer-shehane** [comment] 2023-12-21 15:43
Duplicate of https://github.com/cypress-io/cypress/issues/22663

Someone had a workaround in this comment that worked for them: https://github.com/cypress-io/cypress/issues/22663#issuecomment-1854495823

**Closed as not planned by jennifer-shehane** 2023-12-21 15:43 UTC
