### ISSUE TITLE
Cypress doesn't play the video present on the page.

### ISSUE THREAD

**Issue by nitingupta220** [cypress-io/cypress#2291] opened 2018-08-07 08:42 UTC
I have a video in the HTML's video tag.
And I want to test it by playing it.
`cy.get('.segment-main-container .video-wrapper video').click({force: true});`
In Cypress it's showing the element is clicked but the video is not playing.

Also, I tried to click on the fullscreen button and it's working. Don't know why the video is not playing?
Using Cypress 3.0.3
@jennifer-shehane

**Comment by LankyLou** [comment] 2018-08-09 14:16
I had a similar issue with testing a video player in cypress using chrome due to chrome blocking videos from playing without user interaction. Running the tests in electron fixed it for me.

**Comment by jennifer-shehane** [comment] 2018-08-09 18:46
@nitingupta220 What browser are you running this test in? Does @LankyLou comment help?

**Comment by nitingupta220** [comment] 2018-08-13 09:27
@brian-mann Can you help?

**Comment by jennifer-shehane** [comment] 2018-08-13 20:10
@nitingupta220 We'll need a reproducible example to look into what the issue may be. We're a small team, and being able to quickly reproduce the failing situation helps a lot in getting us started.

**Comment by nitingupta220** [comment] 2018-08-14 07:14
Didn't understand what you are asking for?
Can you please tell more about what you actually expecting from me?

**Comment by jennifer-shehane** [comment] 2018-08-15 16:09
You can provide a cypress test visiting a public url that reproduces the issue or fork https://github.com/cypress-io/cypress-test-tiny repo, set up a test that reproduces the issue, then tell us the repo/branch to try.

**Comment by nitingupta220** [comment] 2018-08-20 10:42
Hey @jennifer-shehane  here is the repo link where I have reproduced the issue.
You just need to clone it and run it on your local server. See it says it is clicked but the video is not played.
Github repo link: - [](https://github.com/nitingupta220/cypress-video-testing)

Please check.

**Comment by frazboyz** [comment] 2018-08-20 14:36
Getting the same issue here.

`cy.get('video#introVideo')
      .then(video => {
        const videoElement = video.get(0);
        return new Promise((resolve) => {
          videoElement.oncanplay = () => {
            cy.log('playing')
            videoElement.play();
          };
          videoElement.onended = () => {
            cy.log('ended!');
            resolve(true)
          }
        });
      })`

**Comment by nitingupta220** [comment] 2018-08-21 10:12
@frazboyz Tried but still not working.
The problem is I'm getting the video tag and when I ran the command to click on it. Cypress says it is clicked but the video didn't play in the cypress browser. 
Will this be possible that when I click via Cypress it actually plays but because of Cypress I won't be able to see it.
@jennifer-shehane @brian-mann

**Comment by frazboyz** [comment] 2018-08-21 10:42
@nitingupta220 Try starting the video bu not clicking it.

```javascript
cy.get('video').then(video => {
    const element = video.get(0);
    element.muted = true;
    element.play();
    return video;
});```

**Comment by nitingupta220** [comment] 2018-08-21 10:58
@frazboyz By using the above code the video is playing. But I have multiple videos on the page and by your code only first video is playing. Is there any way to play all the videos?

**Comment by frazboyz** [comment] 2018-08-21 11:32
@nitingupta220 Ill leave that up to you to figure out, hint: my code only selects the first video element.

**Comment by jennifer-shehane** [comment] 2019-04-24 16:17
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Closed by jennifer-shehane** 2019-04-24 16:17 UTC

**Comment by Yashas0796** [comment] 2019-07-31 09:17
I have script which will sign in to now.dstv.com. But when I select particular movie or any content from recently watched channels the video is not playing.

**Comment by jennifer-shehane** [comment] 2019-07-31 12:28
@Yashas0796 Please provide an example we can run to see this behavior.
