### ISSUE TITLE
Cypress Automation: Domain based Javascript execution issue

### ISSUE THREAD

**Issue by bhushan-udawant** [cypress-io/cypress#6190] opened 2020-01-17 18:52 UTC
### Current behavior:
- The JS file is not getting loaded while testing using Cypress.
- There is a check added to load the JS file when one of the window property is set.
- Cypress opens the requested URL into iframes which has its own window object. So, the actual window object of the site is different and the Cypress window object is different.
- Due to this JS file is not loading in Cypress browser.
- The window property which is required to load the JS file returns value as "undefined" because the Cypress runs the site in its own frame which has its own window object.

Solutions We tried: Which still does not works.
 - We tried setting the property of window object from the test itself.
 - Also, tried adding "chromeWebSecurity": false to the config file.

### Test code to reproduce
```js
describe(‘ExampleTest’, () => {
    it('Verify test’, () => {

    cy.visit(Cypress.config().baseUrl )
    cy.login(email, password)

    parent.window.GLOBAL_VAR = true 
    window.GLOBAL_VAR  = true
    parent.window.frames[0].window.GLOBAL_VAR = true
    parent.window.frames[1].window.GLOBAL_VAR= true

    cy.window().then((window) => {
        window.GLOBAL_VAR  = true
        window.frames[0].window.GLOBAL_VAR = true
    }
}
```

### Versions
**Chrome Browser Version**:
- Version 79.0.3945.117 (Official Build) (64-bit)
- Version 81.0.4030.0 (Official Build) canary (64-bit)

**Comment by jennifer-shehane** [comment] 2020-01-22 06:45
@bhushan-udawant Can you provide a reproducible example of this behavior that we can run? I can't run the provided code as there is not a url provided or the `cy.login()` command. 

Ideally, provide an `index.html` file that when visited will show the problem or a repo that we can clone with the failing Cypress tests.

**Comment by bhushan-udawant** [comment] 2020-01-22 08:24
Hi @jennifer-shehane , I have mailed you the required URL.

Please have a look into it.

**Comment by jennifer-shehane** [comment] 2020-10-20 08:42
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-10-20 08:42 UTC
Labels: stage: needs information
