### ISSUE TITLE
libgconf-2.cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tbell511** [cypress-io/cypress#4807] opened 2019-07-25 00:00 UTC
Started getting this error today in Travis.

`/home/travis/.cache/Cypress/3.4.0/Cypress/Cypress: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

Only happens in Travis, works fine on my own machine.

**Comment by tbell511** [comment] 2019-07-25 00:25
Adding `apt: packages: -libgconf-2-4` to the addons part of my travis.yml file fixed the problem.  Very strange why this is have never been a problem before.

```
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
```

**Comment by jennifer-shehane** [comment] 2019-07-25 06:02
closing as duplicate of https://github.com/cypress-io/cypress/issues/1526

**Closed by jennifer-shehane** 2019-07-25 06:02 UTC
