### ISSUE TITLE
Cypress doesn't work when there is no internet connection, testing to localhost

### ISSUE THREAD

**Issue by jodelasur** [cypress-io/cypress#4763] opened 2019-07-19 08:09 UTC
### Current behavior:
Cypress will not load tests to localhost server **when there is no internet connection**. This happens in both GUI (cypress open) and command line (cypress run).

I'm experiencing something similar to https://github.com/cypress-io/cypress/issues/4235, but the differences are:
- It only doesn't work when there is no internet connection.
- When there's no connection, issue happens with **both** Chrome and Electron

In the console, I see this:

![image](https://user-images.githubusercontent.com/34933233/61518722-d7652300-aa3c-11e9-91c0-9b52725533fb.png)

I'm not in a corporate proxy server.

### Desired behavior:
The tests should still run, since I'm only testing a local server.

### Steps to reproduce:
1. Clone [this repo](https://github.com/jodelasur/cypress-issue-localhost-no-internet), then `npm install`. This repo is just create-react-app with a cypress test that visits the home page.
2. Disconnect internet connection.
3. `npm start` to start server. http://localhost:3000 should display the default page for create-react-app.
4. `npm run cypress:open` to start Cypress. Then run home.spec.js. You'll see that the test doesn't load.

I also included my logs in the repo. See `log.txt`.

### Versions

Cypress 3.4.0, Windows 10, Chrome 75 and Electron 61

**Comment by brian-mann** [comment] 2019-07-19 16:56
Cypress should most definitely work offline, @flotwig 	can you take a look at this?

**Comment by bahmutov** [comment] 2019-07-19 18:22
Justin James @digitaldrummerj has asked about it before https://twitter.com/digitaldrummerj/status/1130898592481316864

**Comment by flotwig** [comment] 2019-07-22 11:16
Couldn't reproduce in Ubuntu 19.04, but in Windows 10 can confirm the issue occurs in Chrome & Electron. Working on the "why" now.

**Comment by flotwig** [comment] 2019-07-22 12:52
The root issue appears to be nodejs/node#11320... Node on Windows cannot resolve `localhost` when there is no active network interface besides 'loopback'.

A fix landed in Node 8.10: nodejs/node#17662, we're on 8.9.3.

An interim fix is to intercept calls to `dns.lookup` and use `os.networkInterfaces()` to detect if this problem is going to occur, and if so, strip the problematic flag from `dns.lookup`. Submitted a PR to fix this (#4774) while we work on upgrading the bundled Node (#3568)

**Comment by bahmutov** [comment] 2019-07-22 13:12
Nice detective work, Zach

**Closed** 2019-07-22 16:57 UTC
Labels: stage: needs review, topic: network, type: bug
