### ISSUE TITLE
Implicit should 'exist' assertion is not being applied on cy.get() when other assertion.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#205] opened 2016-08-30 19:09 UTC
Using `cy.get()` on an element should implicitly assert existence of the element. But in my examples below, you can see that I have no element `foobarbaz`, the Command Log correctly logs `0` elements found, yet my explicitly written assertions (`not.be.visible` and `not.have.class`) chained off of the gotten element pass. 

`cy.get()` should always implicitly assert existence unless there is an explicit assertion down the chain on that element asserting that it should `not.exist`.

**Example Test Code**

```javascript
it("dom element doesn't have attributes", function() {
  cy.get("foobarbaz").should("not.be.visible");
  cy.get("foobarbaz").should("not.have.class", "foo");
});
```

**Example Command Log**
![screen shot 2016-08-30 at 3 04 42 pm](https://cloud.githubusercontent.com/assets/1271364/18103089/2fa45986-6ec3-11e6-9904-f7223c557c58.png)

**Comment by brian-mann** [comment] 2016-09-08 16:22
This is because internally Cypress applies a default assertion `should("exist")` **only if** there are *no other assertions*.

Since you added additional assertions the implicit `should("exist")` was not applied. You're using negated assertions and those pass because cypress did not find the element, and a non existent element is both not visible and does not have the class.

Cypress needs to be updated to always apply the default `should("exist")` assertion even if there are other assertions **so long as** there is not a `should("not.exist")`. If there is it should reverse its behavior and wait for the element not to exist before applying assertions.

**Comment by fvanwijk** [comment] 2017-01-31 21:27
I like to have `cy.get('@someAlias').should('not.exist')` to have the same behavior, because according to the [docs](https://docs.cypress.io/docs/using-aliases#section-when-alias-references-no-longer-exist-in-the-dom) an alias requeries the element.

Currently the given example returns `Timed out retrying: Expected to find element: ’someAlias', but never found it.`, while a regular `should('not.exist')` passes.

**Comment by udisun** [comment] 2017-05-16 17:32
I'm getting some weird behavior with this, when trying this assertion:
```
cy.visit('/')
  .get('#signup').should('not.exist')
```
the assertion fails and prints:
`expected #signup to exist in the DOM`

it look like a bug

**Comment by brian-mann** [comment] 2017-05-16 18:39
@udisun It seems unlikely that is the entirety of your code.  Can you put together a reproducible repo?
 There is likely another problem in play because code that simple **definitely works**.

**Comment by udisun** [comment] 2017-05-17 10:21
@brian-mann i've created a very small repo with the example of `not.exist` failing , the weird thing is that it only fails on the ui (cypress open and run).
`https://github.com/udisun/cypress-first-steps`

**Comment by udisun** [comment] 2017-05-24 10:30
@brian-mann did you check my example project, do you have an explanation why the command isn't working?

thanks

**Comment by brian-mann** [comment] 2017-09-12 22:31
@udisun I looked at your repo and you did not provide a proper query selector to the `cy.get` which is why it was failing.

https://github.com/udisun/cypress-first-steps/blob/master/cypress/integration/app_spec.js#L13

There is no element called `signup-guide`

**Comment by PKSpeleo** [comment] 2018-09-13 06:33
Same problem(

**Comment by dwelle** [comment] 2018-12-15 15:11
I think this is large enough issue to warrant doc changes, particularly in https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions and https://docs.cypress.io/api/commands/should.html#Syntax. Should I open a PR?

**Comment by jennifer-shehane** [comment] 2019-01-03 17:50
Hey @dwelle, yes you can open an issue and/or PR from our documentation repo. https://github.com/cypress-io/cypress-documentation

**Comment by Bkucera** [comment] 2019-01-25 17:52
Hi, this is due to a bug fixed in this PR #3219

**Comment by jennifer-shehane** [comment] 2019-05-01 06:03
Hey @Bkucera, I think you may have linked the wrong PR above in your comment. Did you mean this? https://github.com/cypress-io/cypress/pull/3268

**Comment by jennifer-shehane** [comment] 2020-02-03 16:46
An example on why this current implementation is a problem.

## Example #1

If you have an element that did exist and then sets the elements visibility to `hidden`. Both of these assertions pass, so you essentially cannot test this behavior with the current implementation of Cypress.

```js
cy.get(el).should(not.be.visible)
cy.get(el).should(be.visible)
```

**Comment by Jazzepi** [comment] 2020-02-22 23:13
To add another datapoint I find it confusing that these constructs do not do the same thing. The first one successfully fails if the element is on the page, and the second one does not.

    cy.get('something').should('not.exist');
    cy.get('something').should('not', 'exist');

**Comment by jennifer-shehane** [comment] 2020-04-08 04:42
Another use case from #6958 - notice I'm not even visiting a website and this passes because the checkbox doesn't event exist. 

```js
it('testing', () => {
  cy.get('input').should('not.be.checked')
})
```

**Comment by shwarcu** [comment] 2020-09-09 07:21
@jennifer-shehane hi, is there any progress on that issue?

**Comment by jennifer-shehane** [comment] 2020-11-10 05:38
We're looking into the details of this issue again, to see if we can get this into one of our future breaking releases.

**Closed** 2020-11-20 08:12 UTC
Labels: internal-priority, stage: work in progress, type: breaking change, type: bug, type: unexpected behavior
