### ISSUE TITLE
cy.exec() fails when git bash has been installed in folder with space in its name

### ISSUE THREAD

**Issue by katQA** [cypress-io/cypress#1034] opened 2017-12-07 08:42 UTC
### Current behavior:
 `cy.exec('echo')` fails when Git has been installed in folder with space in its name

### Desired behavior:
`cy.exec()` not to fail when Git has been installed in folder with space in its name

### How to reproduce:
1. Install Git in Program Files or in folder with space in its name
2. Start Cypress from Git Bash 
3. Start test with `cy.exec('echo')` in it

Result: The test will fail with the following error:

"Stderr:
/c/Program: Files\Git\usr\bin\bash.exe: No such file or directory"

#### Test code:

```js
 cy.exec('echo') 
```

### Additional Info (images, stack traces, etc)
![cypress_problem](https://user-images.githubusercontent.com/33421059/33705923-db8a88f8-db3a-11e7-845d-c79918c141b3.png)

`cy.exec()` is working when Cypress has been started from cmd

- Operating System: Windows 10 Pro
- Cypress Version:  0.4.1
- Browser Version:  Chrome 62

**Comment by bahmutov** [comment] 2017-12-07 14:22
Ughh, Windows! 

- I have noticed that you use `del ... || rm ..` commands - we now have [`Cypress.platform`](https://docs.cypress.io/api/cypress-api/platform.html) to help with this
- Seems the problem is coming from our `cy.exec` implementation. I think it would be nice if you could investigate the code responsible https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/exec.coffee here. For example you can run Cypress with `DEBUG=cypress:server ...` environment variable to see the shell path it finds.

**Comment by Saibamen** [comment] 2019-02-22 18:17
Correct error for `cy.exec('echo')`:
```
CypressError: cy.exec('echo') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 127

Stderr:
/c/Program: Files\Git\usr\bin\bash.exe: No such file or directory
```

**Comment by jennifer-shehane** [comment] 2019-02-28 16:33
Closing as duplicate of https://github.com/cypress-io/cypress/issues/789

**Closed by jennifer-shehane** 2019-02-28 16:33 UTC
Labels: OS: windows, pkg/server
