### ISSUE TITLE
(node:745) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by DimaNext** [cypress-io/cypress#5115] opened 2019-09-10 13:37 UTC
![image](https://user-images.githubusercontent.com/46421505/64618621-43cf2380-d3e9-11e9-80a0-677a4ae04d29.png)

How i can fix it ?

**Comment by jennifer-shehane** [comment] 2019-11-06 15:30
Closing as duplicate of https://github.com/cypress-io/cypress/issues/1305

**Closed by jennifer-shehane** 2019-11-06 15:30 UTC
