### ISSUE TITLE
System generated cypress.config.ts issue

### ISSUE THREAD

**Issue by santheep** [cypress-io/cypress#22034] opened 2022-06-02 07:51 UTC
### Current behavior

upgraded successfully to cypress ver 10

after running cypress open

Select e2e Testing (not configured)

It recommends the following changes 

1. cypress.config.ts
3. cypress\support\e2e.ts
4. cypress\support\commands.ts

click continue
Throws Syntax error eventhough the default cypress.config.ts was system generated

--cypress.config.ts--
```ts
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
}); 
```

### Desired behavior

IT should continue successfully

### Test code to reproduce

SyntaxError
```
Your configFile is invalid: C:\GuiAutomation\cypress.config.ts

It threw an error when required, check the stack trace below:

[Stack trace](http://localhost:54487/__launchpad/index.html#)
C:\GuiAutomation\cypress.config.ts:1

import { defineConfig } from "cypress";
^^^^^^
Your configFile is invalid: C:\GuiAutomation\cypress.config.ts

It threw an error when required, check the stack trace below:

[Stack trace](http://localhost:54487/__launchpad/index.html#)
C:\GuiAutomation\cypress.config.ts:1
import { defineConfig } from "cypress";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadFile (C:\Users\santh_lfly\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:103:14)
    at EventEmitter. (C:\Users\santh_lfly\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:146:38)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:467:12)
    at process. (C:\Users\santh_lfly\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:467:12)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
### Cypress Version

v10.0.1

### Other

Cypress package version: 10.0.1
Cypress binary version: 10.0.1
Electron version: 18.0.4
Bundled Node version:
16.13.2

**Comment by lmiller1990** [comment] 2022-06-02 11:01
Seems like a dup of https://github.com/cypress-io/cypress/issues/22038.

**Comment by tgriesser** [comment] 2022-06-02 14:15
@santheep can you confirm whether you have `typescript` installed in your project? Also whether you have a `tsconfig.json` in your project's root directory? The issue may be that we're incorrectly scaffolding TS for projects that aren't using it - we should have a fix out for that issue today.

**Comment by RiZKiT** [comment] 2022-06-02 15:36
We have the same issue and yes we have a tsconfig.json in our project, but just for linting and other reasons, no typescript installed.

**Comment by mjhenkes** [comment] 2022-06-02 18:11
@tgriesser, @lmiller1990 should we close this as a dupe of #22038?

**Closed** 2022-06-02 21:23 UTC
Labels: stage: needs review, v10.0.0 :bug:, PATCH
