### ISSUE TITLE
[7.1.0] Vue Component testing - The test doesn't finish loading

### ISSUE THREAD

**Issue by xanxuz** [cypress-io/cypress#15959] opened 2021-04-13 12:43 UTC
### Current behavior
The test doesn't finish loading

![image](https://user-images.githubusercontent.com/11968584/114553812-09b4ac00-9c34-11eb-83d5-09a965547bb5.png)
![image](https://user-images.githubusercontent.com/11968584/114553655-df62ee80-9c33-11eb-8aa6-c43a2016dfeb.png)
![image](https://user-images.githubusercontent.com/11968584/114553709-edb10a80-9c33-11eb-84bb-e60d8a6593a0.png)
![image](https://user-images.githubusercontent.com/11968584/114553749-f86b9f80-9c33-11eb-8a5b-99442e8f9501.png)

### Desired behavior
To load and run the test

### Test code to reproduce
Here is a repo with vue-cli and cypress ct that was being used to test and make the screenshots
[https://github.com/xanxuz/vue-cypress-ct](https://github.com/xanxuz/vue-cypress-ct)

### Versions
Cypress v7.1.0
Yarn v1.22.5
Node v15.14.0
Windows 10

**Comment by agg23** [comment] 2021-04-13 14:14
Duplicate of #15842

**Closed by agg23** 2021-04-13 14:14 UTC
Labels: component testing
