### ISSUE TITLE
How to click button present inside a context menu and iframe in cypress?

### ISSUE THREAD

**Issue by nikkieta** [cypress-io/cypress#4830] opened 2019-07-26 10:23 UTC
### Current behavior:

Trying to click on a button present in an iframe using below code. 
```js
cy.log("Wait for Iframe to load");
cy.get(getdatasourcelocator.Iframe, { timeout: 30000 }).should('be.visible').then($iframe =>{
const body = $iframe.contents().find('body');
cy.wrap(body).find(getdatasourcelocator.SearchBox).should('be.visible', { timeout: 30000 }).type(datasourceType);
cy.wrap(body).find('.textCsv').click();entityURL
cy.wrap(body).find(getdatasourcelocator.URL).type(entityURL);
cy.wrap(body).find('button').contains('Next').click();
cy.wrap(body).wait(15000);
cy.wrap(body).xpath("//button[@name='Transform table']").should('be.visible').first().click();
```

Menu option is opens but closes immediately.
suggest if i m doing anything wrong. Any help will be appreciated.

### Desired behavior:

after clicking menu option it should remain open till clicked somewhere else.

### Steps to reproduce: (app code and test code)

![image](https://user-images.githubusercontent.com/50622994/61945188-00e1f980-afbd-11e9-886e-f6fe83ad8110.png)

Gif of the above mentioned code. After clicking on Transform Table the Menu option closes immediately.
![tranformtable](https://user-images.githubusercontent.com/50622994/61945266-2bcc4d80-afbd-11e9-8cd7-75316ae383e1.gif)

![image](https://user-images.githubusercontent.com/50622994/61945378-6f26bc00-afbd-11e9-8056-c76f066a265a.png)

### Versions

Chrome, Windows 10, Cypress 3.4.0

**Comment by sainthkh** [comment] 2020-11-13 06:11
Cannot help closing this because there's no reproducible example. If it's still happening in 5.6.0+, please open a new issue with a reproducible example.

**Closed by sainthkh** 2020-11-13 06:11 UTC
