### ISSUE TITLE
Brittle builds - intermittent failures on CircleCI and no way to resolve

### ISSUE THREAD

**Issue by andrewryan1906** [cypress-io/cypress#2994] opened 2018-12-26 22:56 UTC
### Current behavior:

I have an Angular application that runs locally with about 100 tests. The tests run fine. On CircleCI, there are intermittent, unpredictable test failures. When reviewing the recordings on the Cypress dashboards, it registers as missing element timeouts. And... I'm stuck.

### Desired behavior:

When a build fails, I'd like to be able to review the Electron console output to see if Angular outputted an error, to help get a clue of why the build is failing in CI, but not locally. Without this, I have no tools to resolve brittle builds and CI failures, and this tool becomes challenging to use.

### Steps to reproduce: (app code and test code)

Can't repro reliably; depending on when I run, different tests fail. 
### Versions

Windows 10, Chrome (locally), CircleCI/Debian (in the cloud CI/CD process)

**Comment by andrewryan1906** [comment] 2018-12-26 23:19
Also, if anyone has any suggestions/experience with failures like these - it's driving me up the wall. With every Cypress build, 2-4 _different_ tests fail each time. These tests work fine locally, and when I rerun the build, those tests pass and 2-4 other ones fail. And there's no way to see why they fail... it looks like a timeout on an XDR PUT request. 

No idea what's going on, no idea how to stabilize the build.

**Comment by jennifer-shehane** [comment] 2018-12-27 05:48
Most often in cases of flaky tests, we see that there is not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next assertion. So if there is any variation in the speed of the XHR requests response in interactive mode versus run mode, then there will start to be failures in one over the other - or flaky tests. 

So, for example if you had a test to check that when you click a 'Save' button that the users page refreshes with the correct content, you may write a test like so:

```js
cy.get('.name-input').type('Jennifer')
cy.get('form').contains('Save').click()
cy.get('#user- name).should('contain', 'Jennifer')
```

Each command by default will wait 4 seconds to meet it's requirements, but if the POST for the form request *sometimes* takes longer to respond than it takes for the "cy.get('#user- name).should('contain', 'Jennifer')" to run, then it will fail sometimes. Because of this, we recommend asserting on as many required steps as possible - this also helps later to isolate where the exact failure is when debugging on an actual bug. 

So, the example above would be less flaky written like this:

```js
cy.server()
cy.route('POST', 'users/*').as('updateUser')
cy.route('GET', 'users').as('getUsers')

cy.get('.name-input').type('Jennifer')
cy.get('form').contains('Save').click()
cy.wait('@updateUser').then((xhr) => {
expect(xhr.requestBody).to.have.property('name', 'Jennifer')
}
cy.url('contains', 'users/123')
cy.wait('@getUsers')
cy.get('#user- name).should('contain', 'Jennifer') 
```

Now when the last line runs, we don't have to worry about the POST or that the POST sent the right information, that the url changed and the GET's or whatever requests needed to respond - we know it's in the right state to find the content here. 

Unfortunately we'll have to close this issue since no reproducible example was provided, but hopefully this points you in the right direction.

**Closed by jennifer-shehane** 2018-12-27 05:48 UTC

**Comment by andrewryan1906** [comment] 2018-12-27 17:57
Jennifer,

I'm having a hard time presenting a reproducible example since it's so spotty. But I get your point... this was one of the first things I observed. I got around this by increasing the wait timeout to 15 seconds for everything, but to your point, I'd be better off using the wait to deal with cold lamda starts that cause XHR operations to take >5 seconds sometimes.

But given that I've increased the wait timeout, this shouldn't be a problem. There's literally no way a REST operation can ever take more than 10 seconds in my system. So again - I need to be able to get at that browser console info to see whats happening, because what's more likely is that Angular is throwing an exception.

Is that not possible?

**Comment by andrewryan1906** [comment] 2018-12-27 18:49
Also - can I send you the video privately to demonstrate? That might help illustrate. The timeout is 20 seconds and so I know page isn't timing out... it's an Angular error I need to be able to observe.

**Comment by jennifer-shehane** [comment] 2018-12-28 06:10
Hey @andrewryan1906, I'd suggest asking questions about using Cypress in our [community chat](https://gitter.im/cypress-io/cypress). We also have dedicated email support as part of some of our [plans](https://www.cypress.io/pricing/). 

Sorry, we wish we could spend all day answering questions! I hope you understand.

**Comment by andrewryan1906** [comment] 2018-12-28 10:37
```
Sorry, we wish we could spend all day answering questions! I hope you understand.
```

Really?

Respectfully, this has been a very frustrating exchange. Please try to put yourselves in my shoes; I am a paid user of your product, which I am planning to rely on to support automated testing and a continuous delivery model which is a big part of our our R&D plan. I cannot get it to work reliably in my CI/CD pipeline. I submitted a ticket with the best possible information I could - given that the problem was not reproducible and the issues intermittent.

I got a vague answer about assertions and you insta-closed my ticket, telling me I didn't provide sufficient steps to reproduce. You didn't give me a chance to respond, or a chance to provide follow up information. There was no "wait period" for more information before the ticket was closed. It was just closed. I was unable to reopen and wasn't sure whether or not my additional comments were even being read, and so I opened another ticket - for which I was promptly scolded. When I try to respond with additional information, including a request to privately send you the additional context that you insta-closed my ticket for not having, you tell me to go check out a chat room and tell me, a paid user of your product, **you wish you could spend "all day" answering questions.** Really? Condescension aside, this just isn't a good way to treat your customers.

For the record, I did go over to your chat room. I asked my question - twice - and got no response. The chat room model is a tough way to get help - you fire off a question, often in the middle of several other conversations, and hope someone pays attention. Often you get no response, and there appears to be little recourse other than to keep shouting.

Cypress - as far as I can see - is an **awesome** product. I have great plans for it in the company we are launching next year. But I need better support than this. Perhaps you might offer some kind of support offering at an additional cost? Or a consulting offering? 

By the way - I still don't have an answer to my question - how can I access the Chrome console output from runs that happen in CircleCI to debug spotty builds? Because right now, the tool is not fulfilling its promise to me because I can't get stable CircleCI test runs, and I need to get that fixed in order to continue using your product.

Thank you,
Andrew
