### ISSUE TITLE
Getting this error when I run cypress in chrome "This browser was not launched through Cypress. Tests cannot run."

### ISSUE THREAD

**Issue by chakradhari** [cypress-io/cypress#8754] opened 2020-10-06 05:20 UTC
### Current behavior
I having the same issue "This browser was not launched through Cypress. Tests cannot run."

I am working in organisation.
I am behind a proxy.

It's working fine when I select "Electron" as the browser but if I want to execute tests in Chrome they won't work.

I tried following ways:

1) I tried clearing App data and tried fresh cypress open (I am able to see cypress icon in my broswer)
2) I tried adding hosts

None of them seem to work.

Can anyone please help me with this?

I am not sure how to get cypress logs in windows machine.

### Desired behavior

I need tests to be executed on chrome

### Versions
Operating system: Windows 10, 64bit
Browser: Chrome 81
Cypress Version: 5.3.0

**Comment by jennifer-shehane** [comment] 2020-10-07 06:08
Duplicate of https://github.com/cypress-io/cypress/issues/6889

You can run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode to get the logs.

**Closed by jennifer-shehane** 2020-10-07 06:08 UTC
