### ISSUE TITLE
replace ComponentName.cy.ts to ComponentName.cy.tsx in component test

### ISSUE THREAD

**Issue by hidaviddong** [cypress-io/cypress#24880] opened 2022-11-29 17:45 UTC
### What would you like?

Replace the default provided`ComponentName.cy.ts` with `ComponentName.cy.tsx`
<img width="718" alt="image" src="https://user-images.githubusercontent.com/73568310/204601089-01f93f9d-2bfb-4674-bc4a-ab41ece41fff.png">

### Why is this needed?

Using Next.js + TypeScript , component test default provided  spec `ComponentName.cy.ts`

When we import a component, it will report an TS error by default
<img width="482" alt="image" src="https://user-images.githubusercontent.com/73568310/204602721-be4c4525-a9d0-4eec-ae64-033e0439a880.png">
The solution is to change file `ComponentName.cy.ts` to`ComponentName.cy.tsx`
<img width="181" alt="image" src="https://user-images.githubusercontent.com/73568310/204602131-c64cea8f-d8b7-4d88-9fc9-a7234dc2650e.png">

**Comment by mike-plummer** [comment] 2022-12-06 16:30
Hi @DongHY1 , thanks for opening an issue! It sounds like you're proposing that projects that are JSX-friendly include the JSX/TSX extension by default when proposing names for newly-created component spec files, is that correct? I think that would be possible, but we would need to do some brainstorming to ensure we only apply that logic for projects where it makes sense (for example, Angular and Svelte by default don't use JSX).

Our "[Create Spec from Component](https://github.com/cypress-io/cypress/issues/22836)" feature is being expanded to [support React](https://github.com/cypress-io/cypress/issues/24773) in an upcoming release, and that will utilize JSX the way you describe plus automatically add the `import` and `mount` statements to the new spec for you. I wonder if this would meet your needs?

**Comment by hidaviddong** [comment] 2022-12-10 08:18
> Hi @DongHY1 , thanks for opening an issue! It sounds like you're proposing that projects that are JSX-friendly include the JSX/TSX extension by default when proposing names for newly-created component spec files, is that correct? I think that would be possible, but we would need to do some brainstorming to ensure we only apply that logic for projects where it makes sense (for example, Angular and Svelte by default don't use JSX).
> 
> Our "[Create Spec from Component](https://github.com/cypress-io/cypress/issues/22836)" feature is being expanded to [support React](https://github.com/cypress-io/cypress/issues/24773) in an upcoming release, and that will utilize JSX the way you describe plus automatically add the `import` and `mount` statements to the new spec for you. I wonder if this would meet your needs?

I'm looking forward to trying it out when it becomes available. It sounds like it will be a great addition to the tool, and I'm sure it will be very useful for creating specs for React components.

**Comment by mike-plummer** [comment] 2022-12-14 19:50
This work is being tracked under #24773 , closing this issue as a duplicate of the functionality being delivered there

**Closed as not planned by mike-plummer** 2022-12-14 19:50 UTC
