### ISSUE TITLE
How can I change the xhr request before send

### ISSUE THREAD

**Issue by arm-liang** [cypress-io/cypress#7567] opened 2020-06-02 13:42 UTC
### Current behavior:
I find all of the api of cypress about `route` and `server`, but there is no way to change the xhr request `before send`, there is only the `onRequest` callback of route method.
In a situation, my gps location is get from internet, and I know the current location of the target area.
But I can't simulation the location. The only way I find is to change the request body before send to server. I prepare the correct location and change the request to test the different cases;

May it has a callback of `beforeRequest`.

**Comment by bahmutov** [comment] 2020-06-02 13:47
How does your web application get the GPS location? Maybe you could stub that API?

**Comment by arm-liang** [comment] 2020-06-02 13:54
It inspire me.
I can change the location before it gets.
But my web app run inside a native app, and the native app get GPS do not from xhr.(such as Wechat web)

**Comment by sainthkh** [comment] 2021-01-15 05:39
Maybe new [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept.html) can help solve the problem (by returning GPS value).

I'll close this issue because it's not the problem on the Cypress side. If you have any other questions, or the problem is still happening, open [a new discussion here](https://github.com/cypress-io/cypress/discussions).

**Closed by sainthkh** 2021-01-15 05:39 UTC
Labels: type: question
