### ISSUE TITLE
cant get html of https://data.gov.il/organization/

### ISSUE THREAD

**Issue by yoelfr** [cypress-io/cypress#21597] opened 2022-05-23 08:18 UTC
### Current behavior

cy.visit("https://data.gov.il/organization/")
page load but I get empty html

### Desired behavior

cy.visit("https://data.gov.il/organization/")

### Test code to reproduce

cy.visit("https://data.gov.il/organization/")

### Cypress Version

5.3.0

### Other

cy.visit("https://data.gov.il/organization/")
page finish loaded but html is empty

**Comment by mjhenkes** [comment] 2022-05-24 16:56
@yoelfr, could you try updating your version of cypress? We have fixed many issues since the 5.3.0 version of cypress.

**Comment by ZachJW34** [comment] 2022-05-24 22:18
When I tried to visit the site in my browser is stalled out the first time, but I was able to get through eventually.

I can reproduce this with the latest version of Cypress, blank page (even with "chromeWebSecurity": false):
![Screen Shot 2022-05-24 at 5 14 43 PM](https://user-images.githubusercontent.com/25158820/170141133-d1632491-6121-4939-8afe-fe7853d121dd.png)

I can load the page in Electron, with some `page-load` warnings
![Screen Shot 2022-05-24 at 5 16 07 PM](https://user-images.githubusercontent.com/25158820/170141241-a30c0655-a4d8-4e2d-a100-0fd0776e3f66.png)

@yoelfr can you try using the electron browser as a workaround?

**Comment by yoelfr** [comment] 2022-07-25 09:01
I upgrade to cypress 10 and the problem steel happens , 
the work around to visit with electron is good and the site visible there
I would like to know if you manage to fix this issue so we can use chrome
Tanks

**Comment by flotwig** [comment] 2022-08-22 20:09
Closing as duplicate of #4383.

**Closed by flotwig** 2022-08-22 20:09 UTC
Labels: type: bug, browser: chrome, E2E-core, stage: routed to e2e-core, stage: fire watch
