### ISSUE TITLE
Cypress freezes after couple of seconds

### ISSUE THREAD

**Issue by YPD-HG** [cypress-io/cypress#24288] opened 2022-10-18 09:38 UTC
### Current behavior

I type `npx cypress open `, cypress opens, after about 40 seconds, the cypress freezes, stops responding, can't click anything, totally non responsive, had to use force quit to quit.
Have tried clearing the cache and re-installing the cypress and not able to find solution.
Please help.

### Desired behavior

Cypress should not freeze

### Test code to reproduce

---no code--- cypress stops in about a minute

### Cypress Version

10.10.1

### Node version

8.15.0

### Operating System

macOS 12.1

**Comment by zswati** [comment] 2022-10-18 11:21
Same issue with updated Cypress version

**Comment by BrianIto** [comment] 2022-10-18 15:09
Same here, not even a possibility of finding out what is going on.

**Comment by nagash77** [comment] 2022-10-19 18:27
potentially related to #24270

**Comment by warrensplayer** [comment] 2022-10-19 20:21
@YPD-HG You indicated node version 8.15.0, I am guessing that is the version of `npm` you are using. Can you confirm the node version?

@YPD-HG @zswati @BrianIto Can any of you provide a screen recording of what is happening?  Also, can you run with debug logs turned on and supply those as well?  https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs

**Comment by zswati** [comment] 2022-10-19 21:21
https://user-images.githubusercontent.com/20716175/196806811-12d59650-11d4-4d01-9bc1-1e982c7611e6.mov

@warrensplayer attaching video for reference

**Comment by zswati** [comment] 2022-10-19 21:25
https://user-images.githubusercontent.com/20716175/196807628-7298dc43-0e4f-4ba2-a5c0-2e0ec4361b9a.mov

**Comment by YPD-HG** [comment] 2022-10-20 04:27
> @YPD-HG You indicated node version 8.15.0, I am guessing that is the version of `npm` you are using. Can you confirm the node version?
> 
> @YPD-HG @zswati @BrianIto Can any of you provide a screen recording of what is happening? Also, can you run with debug logs turned on and supply those as well? https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs

**Comment by YPD-HG** [comment] 2022-10-20 04:29
> @YPD-HG You indicated node version 8.15.0, I am guessing that is the version of `npm` you are using. Can you confirm the node version?
> 
> @YPD-HG @zswati @BrianIto Can any of you provide a screen recording of what is happening? Also, can you run with debug logs turned on and supply those as well? https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs

@warrensplayer , current version of npm is 8.15.0

**Comment by amehta265** [comment] 2022-10-31 14:30
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by amehta265** [comment] 2022-11-07 14:39
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by amehta265** 2022-11-07 14:39 UTC
