### ISSUE TITLE
Cannot click button download in cypress 6.3.0

### ISSUE THREAD

**Issue by hiatien19** [cypress-io/cypress#14792] opened 2021-01-28 02:58 UTC
i was update Cypress 6.3.0
but i cannot click button download

Evidence: ![error_export](https://user-images.githubusercontent.com/56146091/106083576-50275e00-614f-11eb-9a08-701a69b48a23.jpg)

file csv add message:
```js
<script type='text/javascript'> document.domain = 'tctav.com'; var Cypress = window.Cypress = parent.Cypress; if (!Cypress) { throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); }; Cypress.action('app:window:before:load', window); </script>
```

Evidence: ![error_export_1](https://user-images.githubusercontent.com/56146091/106083596-587f9900-614f-11eb-94d9-98ce79d07da0.jpg)

**Comment by jennifer-shehane** [comment] 2021-01-28 08:58
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-01-28 08:58 UTC

**Comment by hiatien19** [comment] 2021-02-02 01:30
Hi jennifer-shehane,

i was update Cypress 6.4.0
but i cannot click button download.
Please help me.

**Comment by jennifer-shehane** [comment] 2021-02-05 09:41
Duplicate of https://github.com/cypress-io/cypress/issues/14857
