### ISSUE TITLE
requested gles version

### ISSUE THREAD

**Issue by Dante690** [cypress-io/cypress#23394] opened 2022-08-17 07:31 UTC
### Current behavior

Requested gles version is greatest than max supported
![Error](https://user-images.githubusercontent.com/102960711/185060433-161a8703-fefe-49cb-b3b9-e7c10c1f3e51.jpg)

### Test code to reproduce

-

### Cypress Version

10.3.0

### Node version

14.15.1

### Operating System

win7

**Comment by rachelruderman** [comment] 2022-08-17 18:55
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-24 18:15
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-24 18:15 UTC
Labels: stage: awaiting response, Needs Reproduction
