### ISSUE TITLE
Corrupted download in CircleCI for v5.6.0 on Linux x64

### ISSUE THREAD

**Issue by westrem** [cypress-io/cypress#14967] opened 2021-02-08 08:13 UTC
### Current behavior
There seems to be a corrupted package for Cypress 5.6.0 

The checksums don't match. 

**Context: Trying to install Cypress in CircleCI**

### Debug logs

```
error /root/workspace/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /root/workspace/node_modules/cypress
Output:
Installing Cypress (version: 5.6.0)

[07:58:38]  Downloading Cypress     [started]
[07:58:39]  Downloading Cypress     [failed]
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/5.6.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 90012cdfc2823eba1921e9ed72e8e2156f409cbbc63d5918bf062b176f4f5e4467869cac609da02f75a229d402ee9acd52ea7fae8504c73196f2e98cbf002c6f
Computed checksum: 363316dea46c37f732346727197a9418f2257be9985fcc0ce68c581eec3dba5e753d5d62a1fc8b4be9a3ad7457aab7d2a6ec92028f55e4a8cc1fa0d1c01ebd0a

Expected downloaded file to have size: 205241643
Computed size: 205241643

----------

Platform: linux (Debian - 9.13)
Cypress Version: 5.6.0
```

### Download method
 

- [ ] npm
- [x] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [x] Linux
- [ ] Mac
- [ ] Windows

### Other

- [ ] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [x] This only occurs in CI

**Comment by jennifer-shehane** [comment] 2021-02-08 10:26
This is very likely this issue: https://github.com/cypress-io/cypress/issues/4595 which luckily we have a PR open to fix soon. 🤞 

Duplicate of https://github.com/cypress-io/cypress/issues/4595

**Closed by jennifer-shehane** 2021-02-08 10:26 UTC
Labels: topic: installation
