### ISSUE TITLE
Cypress Assertion Error at mobile testing with inside pages

### ISSUE THREAD

**Issue by ftraxler-tgm** [cypress-io/cypress#7649] opened 2020-06-10 07:27 UTC
I am trying to do a mobile integration test. By clicking on a input field our application opens an inside page. There I want to select an element normally it works but sometimes the inside page does not load during the testing but immediately after the test failed it loads

**Comment by jennifer-shehane** [comment] 2020-06-10 09:02
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

**Closed by jennifer-shehane** 2020-06-10 09:02 UTC

**Comment by ftraxler-tgm** [comment] 2020-06-15 13:44
I am trying to do a mobile integration test. By clicking on a input field our application opens an inside page. There I want to select an element normally it works but sometimes the inside page does not load during the testing but immediately after the test failed it loads


## Current behavior:
Clicking on an input fiield opens a blank white inside page with no content therefore I get an Assertion Error because there are no elements

## Desired behavior:
Clicking on an input field should open a inside page with another input that is typeable and setable.

## Test code to reproduce
```typescript
cy.get('span[name=username]').should('be.visible').click();
cy.get('#email')
		.should('be.visible')
		.type(email)
		.should('have.value', email);
cy.get('#button-email').click();
```
`

## Versions
Cypress 4.8.0
Electron 80
Ubuntu 20.04 LTS

**Comment by jennifer-shehane** [comment] 2020-06-16 09:29
@ftraxler-tgm We'll need an example we can run, or the HTML to run the test against to see what the issue is. We can't help debug without knowing the mechanism that is used in the application on click.
