### ISSUE TITLE
The statements after Async/await line are not executing in command line mode in cypress 8.3.0

### ISSUE THREAD

**Issue by senthiltr** [cypress-io/cypress#17857] opened 2021-08-23 17:25 UTC
### Current behavior

![image](https://user-images.githubusercontent.com/36333193/130487720-775c5180-5602-4361-9fe4-eaf3d9bc43b2.png)
Hi Team,
       I have created one sample project for the issue facing in cypress.
I have written general function in lib directory and import that into one of module with class. Exported this class as default export. Imported this module in one test suite and call its function(async/await) using object.
When i executed this test suite in open mode all the lines which is after await statement are executing. But when i execute the test case using run mode till the await and cy.log lines only executing. The other navigation and other clicks statements are not executing and the execution is stopping.

after await line , I have written to navigation statement and some click action statement.
These are not executing in run mode. The same issue is getting in my original project code. I given commitment with this style.
what is the other way to implement this general kind of functions and access and use.

added the whole repo.

Kindly check and let me know if I missed any or it's the behavior or it is the issue?.
Created discussions long time before:
https://github.com/cypress-io/cypress/discussions/17651
[cypress-async-await.zip](https://github.com/cypress-io/cypress/files/7033803/cypress-async-await.zip)

https://github.com/cypress-io/cypress/discussions/17639
Why there is a difference between open and run mode.

Thanks
Senthilkumar TR

### Desired behavior

All the lines of code should be executed in run mode.

### Test code to reproduce

![run-mode-result](https://user-images.githubusercontent.com/36333193/130489721-4ab2fabc-f9a2-4958-8184-aeb445bdb628.JPG)
![with-open-mode](https://user-images.githubusercontent.com/36333193/130489726-fe96c771-9c66-4828-89ac-cc1489a33832.JPG)

### Cypress Version

8.3.0

**Comment by razvanracota98** [comment] 2022-08-05 10:08
In have the same issue.Cypress doesn't want to run the code in headless mode using await calls. If I use the other promises (then) it is working. Do you know any explanation for this?

**Comment by mladshampion** [comment] 2022-09-14 13:45
same issue happening to me

**Comment by mladshampion** [comment] 2023-04-26 13:22
Any update on this? The async/await is working in the cypress open mode, but not in the command line mode.

**Comment by mschile** [comment] 2023-04-26 18:13
I'm going to close this issue as a duplicate of https://github.com/cypress-io/cypress/issues/1417 which includes more details on async/await. That issue is also part of our [Cypress App Priorities](https://github.com/orgs/cypress-io/projects/13) board.

Additional details:
https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Chains-of-Commands
https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-use-the-new-ES7-async--await-syntax
https://github.com/cypress-io/cypress/blob/develop/cypress-prioritization-and-triage.md#the-cypress-app-priorities

**Closed by mschile** 2023-04-26 18:13 UTC
