### ISSUE TITLE
Ability to display a test category/label in 'Runs' view of Cypress dashboard

### ISSUE THREAD

**Issue by davidedwards88** [cypress-io/cypress#4503] opened 2019-06-19 11:50 UTC
### Current behavior:

We are using Cypress for our monitoring tests. These tests run across our Production environment and two Test environments, and all upload their results to a single Cypress monitoring project. 

When viewing that project in the Cypress dashboard, the 'Runs' screen provides no way of seeing at a glance which environment those tests ran against. For now, we have set a group and CI Build ID to expose this information when you click through to view an individual run. However, this does mean you can only see this for a single run at a time.

### Desired behavior:

A way of displaying a custom category/label for a test run in the top-level 'Runs' screen of the Cypress dashboard. 

We had wondered about repurposing the 'CI' property (as this currently comes through as 'Unknown', and would have served as the ideal column for displaying what we want in the dashboard view). However, from what we can see this is inferred by Cypress from CI systems, and not something we can control.

### Versions

Cypress version 3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-21 09:02
Closing as duplicate of https://github.com/cypress-io/cypress/issues/2561

**Closed by jennifer-shehane** 2019-06-21 09:02 UTC
