### ISSUE TITLE
Test execution wont stop on failure or passed and move to the next test. It just stays on

### ISSUE THREAD

**Issue by vrknetha** [cypress-io/cypress#7935] opened 2020-07-09 15:51 UTC
### Current behaviour:

As our application uses service workers, we thought it is due to that. But, I have disabled the service workers altogether. But, the issue still remains.  The test run never completes. I am trying to migrate from selenium to cypress in my organisation. This is like a big roadblock for me to proceed. Where the issue is with the test execution. I have attached a [video ](https://drive.google.com/file/d/16e0ed5EvVzY0NH__w0WBVKmbyTBjjdj8/view?usp=drivesdk)here

@jennifer-shehane  Please check this.I have updated the repo with the workaround given in the issue. That did not solve the problem.

### Test code to reproduce
All the code is given in the issue
https://github.com/cypress-io/cypress/issues/7751

### Versions
Cypress: 4.10.0
Windows 10
Node v12.18.2

**Comment by saki2rules** [comment] 2020-07-09 18:36
I am facing the similar issue, where the tests execution doesn't stop when we encounter an Assert error or any such failure.

I was looking out on google for people who passed similar issue. 

Cypress: 4.9.0
Issue is happening on all environment

**Comment by jennifer-shehane** [comment] 2020-07-10 06:34
The repo is missing some devDependencies https://github.com/vrknetha/cypress-blueprint from master branch. 

```
npm i --save-dev ts-loader typescript
```

I do not see the issue of the runner stalling with the given example spec. The test runs and stops in 11 seconds. 

Please run and link to the **exact repo** that I can run without any global dependencies installed, so that I have exact versions of everything and it is reproducible. 

<img width="1470" alt="Screen Shot 2020-07-10 at 1 03 01 PM" src="https://user-images.githubusercontent.com/1271364/87123922-b3ce6480-c2ad-11ea-9ff2-71cb8aeb0610.png">

**Comment by vrknetha** [comment] 2020-07-10 08:22
@jennifer-shehane  Thank you for looking into it. When I have tried the same repo to run the test. I am able to get this issue. You can watch the issue [here](https://drive.google.com/file/d/1cjBB0Zl5NcCF7Kybv5GZI-TkQKAhKwZ3/view?usp=drivesdk) in the video. 

I have tried reinstalling chrome, cleared cache, deleted all global node modules, and tried to run them again. The issue still exists. I just can't figure out why it is happening. Is there any way I can get the logs so that we can know what exactly running behind.

**Comment by vrknetha** [comment] 2020-07-10 13:11
@jennifer-shehane The issue was resolved. I was missing a return statement in plugins/index.js. for the screenshot method. You can close this now.

**Comment by saki2rules** [comment] 2020-07-10 21:29
Can you please share the changes you made.

I have `  return fs.readJson(configPath); `
still my tests keeps running after failure of assertion

**Comment by saki2rules** [comment] 2020-07-10 21:31
`const fs = require('fs-extra');
const path = require('path')

module.exports = (on, config) => {
  require('cypress-terminal-report/src/installLogsPrinter')(on);
  require('cypress-plugin-retries/lib/plugin')(on);
  
  const configFile = config.env.configFile || 'gamma'
  const testApplication = config.env.testApplication || 'checkout';

  const configPath = path.resolve(`cypress/config/${testApplication}`, `${configFile}.json`)
  return fs.readJson(configPath);

};`

My plugins/index.js file looks like this. Can you help me what I'm missing here

**Comment by jennifer-shehane** [comment] 2020-07-14 06:50
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-14 06:50 UTC
Labels: stage: needs information
