### ISSUE TITLE
Cypress opening cypress window inside its own window

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#5958] opened 2019-12-13 18:57 UTC
### Current behavior:

Since 3.5.0 version. Cypress is opening cypress window inside its own window, which finally throws console.error and hence No other further movement in the Tests execution. If we degrade the version from 3.5.0 to 3.4.1 then it will work fine and it has the same behaviour for next version 
3.6.0, 3.7.0 and now with 3.8.0 too. As attached in the image
![CypressVersionErro](https://user-images.githubusercontent.com/17109022/70825044-8f8ad200-1e09-11ea-98ca-11131cae5818.jpg)

### Desired behavior:

We want that it should work as it works with 3.4.1 version without any error. 

### Steps to reproduce: (app code and test code)

1. Reproducible steps is not generalised. Actually, when the URL gets changed this occurs (this is just the assumption). 
2. Try to change the url by adding #SOMEVALUE=?#uid=

Please DONT close the issue we are facing since 3.5 till 3.8. We need to utilize the new commands but due to this error we end up degrading the version. BUT a solution to this with latest version is appreciated. 

### Versions
3.5.0,3.6.0,3.7.0 and 3.8.0

Windows 10,
Electron, Chrome
(Both - Headless and With head)

**Comment by jennifer-shehane** [comment] 2019-12-16 07:51
@Prashant-Kan This is very likely this issue https://github.com/cypress-io/cypress/issues/3975 but since I cannot see the urls, I cannot verify. Can you verify that it is inserting a `_/` into your url upon navigating?

**Comment by Prashant-Kan** [comment] 2019-12-16 09:57
@jennifer-shehane : It doesn't has any '_' but it has \, -,#,? characters.
Will that cause any problem, if yes then what can the possible solution for it with latest version

**Comment by jennifer-shehane** [comment] 2019-12-17 09:58
@Prashant-Kan We won't be able to investigate without a reproducible example unfortunately. Can you provide a way for us to recreate the error?

**Comment by Prashant-Kan** [comment] 2020-01-10 07:23
I tried, but didn't get success to provide you the environment where you can reproduce.

**Comment by jennifer-shehane** [comment] 2020-01-13 06:25
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-01-13 06:25 UTC
Labels: stage: needs information
