### ISSUE TITLE
AW, Snap! always happens. 

### ISSUE THREAD

**Issue by predictiveXu** [cypress-io/cypress#2459] opened 2018-09-11 19:43 UTC
### Current behavior:

![image](https://user-images.githubusercontent.com/41205627/45383427-323a1c80-b5d9-11e8-8aa7-6de14a31712a.png)

### Desired behavior:

I don't understand why it always happens when I try to run all tests. Plus, It always happen when It passes half tests. As a result of it, I have to run it again. 

Did someone see it before?

### Versions
windows 10. 
chrome.

**Comment by jennifer-shehane** [comment] 2018-09-12 14:37
Cypress keeps many of the tests in memory, so that you can access snapshots and timetravel, unfortunately, this causes this crash when you run a large amount of tests (like in the 'Run All' button), we have some plans laid out to prevent this from happening. 

For now, you may try adding the option below in your `cypress.json` https://on.cypress.io/configuration#Global :

```json
{
  "numTestsKeptInMemory": 0,
}
```

**Comment by Konstruktour** [comment] 2018-09-13 09:56
does `numTestsKeptInMemory` also work for headed mode?  
i also run into this issue - think it is because the test run against an app which has a lot of dom elements.
set `numTestsKeptInMemory` works in my case for headless mode, but not for the headed mode.

**Comment by predictiveXu** [comment] 2018-09-14 14:09
Thanks.

**Comment by Peggy1012** [comment] 2018-10-01 11:15
I have the same problem, but this idea did not help me

**Comment by jennifer-shehane** [comment] 2018-11-10 00:17
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by lukeapage** [comment] 2018-11-27 06:57
We had this too, windows 10, chrome and also after about a minute when running all specs.
Adding the `numTestsKeptInMemory` helped us massively.
We already have this option:
```
"runTestsKeptInMemory": 1,
```
maybe adding both helps?

**Closed** 2019-03-08 04:32 UTC
Labels: topic: aw snap :slightly_frowning_face:
