### ISSUE TITLE
Issue with SSL certificates in Cypress version 5.6.0

### ISSUE THREAD

**Issue by klmlfl** [cypress-io/cypress#9259] opened 2020-11-20 13:50 UTC
I'm having an issue loading the secure version of any website using Cypress 5.6.0.
For example, attempting to navigate to https://www.amazon.com returns the non-https version.

### Current behavior
When I perform cy.visit() on any website, the non-secure version of the page is loaded. I have tried the following websites on Chrome and Electron:
1. www.amazon.com
2. www.facebook.com
3. www.google.com
**Note: Screenshots, logs, or other evidence not currently available as my problem has been resolved by downgrading  to Cypress version 5.3.0.**

### Desired behavior
When visiting a website, the secure version should be loaded when available.

### Test code to reproduce
```
describe ('Secure version of the website should be loaded`, () => {
    it ('should load using https', () => {
    cy.visit('https://www.amazon.com');
    };
})

```
### Versions
Cypress version 5.6.0
Last known working Cypress version: 5.3.0
Browser and version: Chrome 86.0.4240.198 (Official Build) (64-bit)
Operating System: Windows 10 Professional

**Comment by flotwig** [comment] 2022-02-03 21:34
Cannot reproduce in latest Cypress: 
![image](https://user-images.githubusercontent.com/1151760/152432674-73f798b5-e736-439b-9e69-23596a5268a3.png)

Closing since 5.6.0 is very old, please try the latest Cypress and if you are still having problems open a new issue here.

**Closed by flotwig** 2022-02-03 21:34 UTC
