### ISSUE TITLE
[Cypress dashboard] When a user opens a currently running test case, the running test icon and title overlap on the right side popup.

### ISSUE THREAD

**Issue by priyankvadaliya753** [cypress-io/cypress#23497] opened 2022-08-22 16:56 UTC
### Current behavior

**Steps To Reproduce:-**

Pre-Conditions:- Some tests should be running and recorded using Cypress Dashboard 
1) log in to the Cypress Dashboard
2) click on Latest runs
3) Click on First Currently Running raw
4) click on the "Test Results" tab
5) click on any Test case of the spec file
6) observe the icon and title on the popup

**Video:-** 

https://user-images.githubusercontent.com/82139164/185976088-e0417c96-9489-49ce-bd04-9ddaaec75d46.mov

### Desired behavior

The icon should not be overlapping with the title.

### Test code to reproduce

Pre-Conditions:- Some tests should be running and recorded using Cypress Dashboard 
1) log in to the Cypress Dashboard
2) click on [Latest runs](https://dashboard.cypress.io/projects/61d9ff/runs)
3) Click on First Currently Running raw
4) click on the "Test Results" tab
5) click on any Test case of the spec file
6) observe the icon and title on the popup

### Cypress Version

9.6.1

### Node version

v16.13.1

### Operating System

Linux Debian - 10.11 Chrome 100

**Comment by benpatterson** [comment] 2022-08-24 20:32
Thanks for surfacing this.
It's a known bug and we have pulled it into work.

I'm closing this as a duplicate of #20506  but leaving that note here; you can follow the linked GH issue as well.

**Closed by benpatterson** 2022-08-24 20:32 UTC
