### ISSUE TITLE
TypeError: TsconfigPaths.loadConfig is not a function

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#9153] opened 2020-11-10 10:38 UTC
### Current behavior
Unable to run any tests
I'm not experiencing this problem after downgrade to 5.3.0 version
See the screenshot below:
![obraz](https://user-images.githubusercontent.com/34089686/98663301-3002b280-2349-11eb-8f41-92df09376e68.png)

### Versions
5.4.0 to 5.6.0

**Comment by jennifer-shehane** [comment] 2020-11-16 05:24
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example - one with your typescript version and tsconfig.json and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-11-16 05:24 UTC

**Comment by zbigniewkalinowski** [comment] 2020-11-17 08:33
In my opinion this is critical bug. I got the same situation on two computers. Ask me what should I send you but do not close this ticket. Cypress is not working for me on versions 5.4.0 and higher.

**Comment by zbigniewkalinowski** [comment] 2020-11-24 08:33
```
{
  "extends": "./tsconfig-paths.json",
  "compilerOptions": {
    "target": "es2016",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "plugins": [
    {
      "name": "typescript-styled-plugin"
    },
    {
      "name": "typescript-tslint-plugin",
      "alwaysShowRuleFailuresAsWarnings": false,
      "ignoreDefinitionFiles": true,
      "configFile": "./tslint.json",
      "disableNoUnusedVariableRule": true,
      "suppressWhileTypeErrorsPresent": false,
      "mockTypeScriptVersion": false
    }
  ],
  "include": [
    "src"
  ]
}
```
tsconfig.json

typescript version is 3.1.2

**Comment by zbigniewkalinowski** [comment] 2020-11-24 08:37
I upgraded typescript to 4.1.2 version and it's still crashing...

**Comment by jennifer-shehane** [comment] 2020-12-08 07:03
Duplicate of https://github.com/cypress-io/cypress/issues/9326
