### ISSUE TITLE
Cypress runs  hanging when video stream was not able to be generated

### ISSUE THREAD

**Issue by jorgeautomation** [cypress-io/cypress#4033] opened 2019-04-25 17:12 UTC
### Current behavior:

When having a set of specs and there was an error generating the video output for any of them then the specific run is hanging and looping. I had to delete the project to have those runs finished. To make it work had to put `"video":false`

### Desired behavior:

Even if the video failed to generate it should continue with the next test of abort the run as a whole, it is looping forever. 

### Steps to reproduce: (app code and test code)

**this is how the cypress.json looks like inside plugins**
```json
{
    "baseUrl": "http://eaapp.somee.com",
    "video":true,
    "screenshotsFolder":"cypress/videos",
    "env":{
        "username":"admin"
    }
}
```

**this is the folder structure**
![image](https://user-images.githubusercontent.com/40399705/56757456-84d3dd80-6751-11e9-8c71-d751b736f7ef.png)

**this is the error message**

```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (C:\Users\jorge\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

{ Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (C:\Users\jorge\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 recordingVideoFailed: true }
Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (C:\Users\jorge\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Versions

 Cypress:    3.2.0       
 OS: Windows 10                                                                       │
 Browser:    Electron 59 (headless)

**Comment by jennifer-shehane** [comment] 2019-04-26 09:38
Duplicate of https://github.com/cypress-io/cypress/issues/3491

**Closed by jennifer-shehane** 2019-04-26 09:38 UTC
