### ISSUE TITLE
Cypress runner waits indefinitely for a XHR request and freezes 

### ISSUE THREAD

**Issue by qadeepa17** [cypress-io/cypress#23389] opened 2022-08-17 02:59 UTC
### Current behavior

The website that i'm testing makes multiple XHR requests to display the landing page after authentication.
While running via Cypress, Cypress runner freezes and waits indefinitely for the XHR request that was cancelled.
While checking the network trace, no Response headers could be found.
I had to kill Cypress and start again to run my other tests. Tried both with cypress run and cypress open - no luck

### Desired behavior

Cypress runner should not freeze, the moment login button is clicked the redirected landing page of the website should be shown

### Test code to reproduce

This is similar to #1068 and the fix #8080 does not work for my case as I cannot use cy.visit as the request that is stuck is a "network request" triggered by a jquery.

### Cypress Version

10.4.0

### Node version

16.14.2

### Operating System

macOS 12.5

**Comment by mike-plummer** [comment] 2022-08-17 19:41
Hi @qadeepa17 , thanks for opening this issue.

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-24 18:12
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-24 18:12 UTC
Labels: stage: awaiting response
