### ISSUE TITLE
cy.stub doesn't work with next.js 14

### ISSUE THREAD

**Issue by tar-aldev** [cypress-io/cypress#28918] opened 2024-02-11 17:23 UTC
### Current behavior

cy.stub does nothing when using it in next.js v 13+.

### Desired behavior

cy.stub should work properly

### Test code to reproduce

https://github.com/tar-aldev/next-nx-cypress/tree/cypress-stub-nextjs

Use cypress-stub-nextjs branch.
1. run tests with `npx nx component-test test-lib --watch=true`
2. run test called HelloServer

It shows Original impl, which comes from the original function and completely ignores `cy.stub()` in the test.

### Cypress Version

^13.0.0

### Node version

18.18.2

### Operating System

14.0 (23A344)

**Comment by MikeMcC399** [comment] 2024-02-11 20:01
@tar-aldev 

- There is an open enhancement request https://github.com/cypress-io/cypress/issues/28185 for Next.js `14` support in Cypress Component Testing which you can subscribe to.

**Comment by jennifer-shehane** [comment] 2024-02-13 21:40
Duplicate of https://github.com/cypress-io/cypress/issues/28185

**Closed as not planned by jennifer-shehane** 2024-02-13 21:40 UTC
Labels: type: duplicate
