### ISSUE TITLE
Fixture files defined in `cy.route` with `fx` and `fixture` shortcut take longer to load, sometimes timeout.

### ISSUE THREAD

**Issue by SurjithP** [cypress-io/cypress#8181] opened 2020-08-05 06:19 UTC
Current behavior:

```js
cy.route('GET', `**/test/**`, `fixture:test.json`).as('something');
```

 error : 

    Error:    CypressError: `cy.fixture()` timed out waiting `30000ms` to receive a fixture. No fixture was ever sent by the server.Desired behavior: the file is in the fixture folder and it should be taken, this was working in 4.11.0 Versions

 The issue is newer version 4.12.0

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-218) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment] 2020-08-05 06:52
The code around the `fixture` shortcut was updated in 4.12.0, so that it should now throw a descriptive error if the file specified is not found in the location given - this would be unexpected behavior if this other error is being shown. https://github.com/cypress-io/cypress/issues/7818

I'm not able to reproduce this behavior from the information given. Please provide a repo or more code to reproduce the issue. Maybe it is dependent on the content in your json file - or if you have a `cy.wait()` later defined waiting on the alias. We'd love to fix this if there's a regression. 

**My code that does not fail**

`cypress/integration/spec.js`

```js
it('test', () => {
  cy.server()
  cy.route('GET', `**/test/**`, `fixture:test.json`).as('something')
})

it('test2', () => {
  cy.visit('https://example.cypress.io/commands/files')
  cy.server()
  cy.route('GET', 'comments/*', 'fixture:test.json').as('getComment')
  cy.get('.fixture-btn').click()
  cy.wait('@getComment')
})
```

`cypress/fixtures/test.json`

```json
{}
```

<img width="429" alt="Screen Shot 2020-08-05 at 1 22 06 PM" src="https://user-images.githubusercontent.com/1271364/89381130-b1312480-d71e-11ea-94fa-27da7e71f8e4.png">

**Comment by SurjithP** [comment] 2020-08-05 07:08
if this was my code issue, how that worked in 4.11.0 and earlier versions. Json file is the fixture folder and content is same as before. nothing was changed, but after the cypress update it started failing 
![image](https://user-images.githubusercontent.com/32353654/89382431-74622f00-d718-11ea-9081-43b6866ed619.png)
![image](https://user-images.githubusercontent.com/32353654/89382484-9065d080-d718-11ea-87ab-2e202c6ecac4.png)

**Comment by jennifer-shehane** [comment] 2020-08-05 07:23
Yes, I believe that you may be encountering an error in 4.12.0. I need the exact code to run to reproduce it - as shown above, I'm not able to reproduce with the information given alone. 

The `cy.route()` command does not log to the Command Log in the Test Runner, but I see in your screenshot that this is logging. Have you overwritten the `cy.route()` command somewhere in your project using `Cypress.Commands.overwrite`?

Please provide a full example so that we can begin work on fixing the issue. We will have to close this issue without this - since we will not have a path to move forward.

**Comment by SurjithP** [comment] 2020-08-05 07:31
@jennifer-shehane , I can understand, but I can't provide my repo details to you.  we do not overwrite any inbuild cypress commands, only our custom things are doing like that. 
I just tried the same test in version 4.11.o Its green
![image](https://user-images.githubusercontent.com/32353654/89384394-aa54e280-d71b-11ea-89ec-d794b62912e7.png)
![image](https://user-images.githubusercontent.com/32353654/89384423-b50f7780-d71b-11ea-8bec-f2068b38db7f.png)

**Comment by jennifer-shehane** [comment] 2020-08-05 07:37
You'll need to revert to Cypress 4.11.0 for now then. 

Unfortunately we can't work on fixing this possible regression without a clear example given on how to reproduce the issue.

**Comment by SurjithP** [comment] 2020-08-05 07:41
@jennifer-shehane , Ok. One doubt , is there is any file size limit or any json new validation added in version 4.12.0 ?
my file is little lengthy

**Comment by jennifer-shehane** [comment] 2020-08-05 08:00
How large is your file? I tried this with a 1,400kb file and it is not erroring with my example above. 

Are you positive that this fixture file exists? Previously, in 4.11.0, this would silently pass - not warning you that the file does not exist. We fixed this error, but it should show a better error than you're seeing if that is the case.

**Comment by SurjithP** [comment] 2020-08-05 10:01
@jennifer-shehane  it was a file size issue, my file was the size of more than 8MB. Removed some content in the file, now it works. Can you please specify the max file size ?

**Comment by jennifer-shehane** [comment] 2020-08-06 10:22
I am able to recreate this *sometimes* with a JSON file that is 11mb in size. Sometimes it takes longer than 30seconds to load. I can recreate this below - with a lower timeout. 

```js
it('test', () => {
  cy.server()
  Cypress.config('responseTimeout', 5000)
  cy.route('GET', 'test', 'fixture:large_11mb.json')
})
```

You could increase the global [`responseTimeout`](https://on.cypress.io/configuration#Timeouts) to increase the time allowed to fetch this fixture, but since this is increasing the runtime it'd probably be best to just downgrade to 4.11.0.

This issue was introduced in 4.12.0. When downgrading - the file instantly resolves. 

### 4.11.0

Only took 0.02 seconds to run test

<img width="512" alt="Screen Shot 2020-08-06 at 4 48 59 PM" src="https://user-images.githubusercontent.com/1271364/89521031-c5e7e800-d804-11ea-8509-73993221e245.png">


### 4.12.0

Takes longer than 10 seconds, sometimes longer than 30 seconds (which is default timeout).

<img width="507" alt="Screen Shot 2020-08-06 at 4 51 19 PM" src="https://user-images.githubusercontent.com/1271364/89521218-1d865380-d805-11ea-9eb1-3f6afe1c73bf.png">

**Closed** 2020-08-10 18:21 UTC
Labels: internal-priority, stage: needs review, type: regression, v4.12.0 :bug:
