### ISSUE TITLE
Schrödinger's code; works and doesn't work at the same time

### ISSUE THREAD

**Issue by Brestachan** [cypress-io/cypress#6386] opened 2020-02-10 07:48 UTC
I'm having issue with the way code behaves in these two situations.

You'll notice that the code I used is the same in both of these cases, it just happens to be a problem for one of them. The code should reset all of changes to their defaults, regardless of test failing or passing.

First situation is that all tests pass successfully, and in this case, code works like a charm, does everything as it supposed to.

Second situation is that test fails after login, that shouldn't affect `afterEach` command, but it does. In this case, elements, although nothing has changed regarding their ID's or any other element attribute, cannot be found with `cy.get` functions.

**Current behavior:**
Code fails, although there's no apparent reason to it, but only in case of test failing.

**Desired behavior:**
Code works, no matter if test fails or passes.

**Test code to reproduce**
```js
afterEach(function() {
if (this.currentTest.state === 'failed') {
Cypress.runner.stop()
cy.exec(
,cy.get('[id="item-users"]').click({force:true})
,cy.get('[id="iiotUserListEdit0"]').click({force:true})
,cy.get('[ng-model="selectedRoles"]').click()
,cy.get('[selected="selected"]').should('be.visible').click({multiple:true,force:true})
,cy.get('[ng-model="selectedRoles"]').click({ force: true })
,cy.get('[label="Roles"]').contains("User").click()
,cy.get('[id="save"]').click({ force: true })
,cy.get('[id="iiotLogout"]').click()
,cy.get('[id="leftPart"]')
,cy.get('[id="inputIdentity"]').type("somemail@mail.com")
,cy.get('[id="inputPassword"]').type("Passw0rd")
,cy.get('[id="loginButton2"]').click()
)
}
});
after(function() {
if (this.currentTest.state === 'passed') {
Cypress.runner.stop()
cy.exec(
cy.get('[id="item-users"]').click({force:true})
,cy.get('[id="iiotUserListEdit0"]').click()
,cy.get('[ng-model="selectedRoles"]').click()
,cy.get('[selected="selected"]').should('be.visible').click({multiple:true,force:true})
,cy.get('[ng-model="selectedRoles"]').click({ force: true })
,cy.get('[label="Roles"]').contains("User").click()
,cy.get('[id="save"]').click({ force: true })
,cy.get('[id="iiotLogout"]').click({ force: true })
,cy.get('[id="leftPart"]')
,cy.get('[id="inputIdentity"]').type("somemail@mail.com")
,cy.get('[id="inputPassword"]').type("Passw0rd")
,cy.get('[id="loginButton2"]').click()
)
}
});

```
Versions
Cypress 4.0.0, Ubuntu 18.04, Chrome 79

**Comment by jennifer-shehane** [comment] 2020-02-10 08:30
Duplicate of #2831

**Closed by jennifer-shehane** 2020-02-10 08:30 UTC
