### ISSUE TITLE
10.6.0 Breaks tests that use aliased cy.readfile 

### ISSUE THREAD

**Issue by kpturner** [cypress-io/cypress#23466] opened 2022-08-19 14:47 UTC
### Current behavior

```
cy.readFile(‘myfile’, ‘base64’).as(‘myAlias’);

cy.get(‘@myAlias’).then(file => { console.log(file) });
```
This will simply log `null` in 10.6.0

### Desired behavior

It should work as previous versions where this would log out the contents of the file.

### Test code to reproduce

https://github.com/kpturner/cypress-bug-repro

### Cypress Version

10.6.0

### Node version

v16.13.1

### Operating System

Ubuntu 18 and Mac

**Comment by kpturner** [comment] 2022-08-22 10:13
Here is a repoduction repo:  https://github.com/kpturner/cypress-bug-repro

**Comment by mike-plummer** [comment] 2022-08-22 14:34
Hi @kpturner , thanks for opening an issue and providing a reproduction. It does appear that this broke in v10.5.0 (likely related to #23400). I can suggest a couple workarounds:

1. Swap the order of your `as` and `then` blocks so the alias is established immediately using the subject from `readFile`, after which the `then` block will receive the same subject and can execute as-is without breaking downstream commands
2. Leave your code as-is but add an explicit `return cy.wrap(file)` as the return statement in your `then` to re-establish the command subject prior to building the alias (not very pretty, but it works)

**Note for future reference on reproduction**
README on reproduction case does not work as-is: update `cypress.config` file with fixed public baseUrl (google, cypress.io, etc) and just run tests using `npx cypress run`. Tests fail with dependency of cypress@10.6.0, succeed with cypress@10.4.0

**Comment by kpturner** [comment] 2022-08-22 14:59
Thanks Mike

I will give it a try.

I take it that this is a workaround for a bug? Or is the behaviour intentional?

The repro steps should have worked but I’d forgotten to delete a .gitignore reference. I will correct that just to complete the circle.

Kevin

**Comment by mike-plummer** [comment] 2022-08-22 18:30
Closing as a duplicate, will track under #23400 since it seems that is the root cause of the behavior seen here

**Closed by mike-plummer** 2022-08-22 18:30 UTC
