### ISSUE TITLE
Stubbing requests with cy.route() not working as expected when stubbing multiple calls to same url

### ISSUE THREAD

**Issue by emilyb7** [cypress-io/cypress#3333] opened 2019-02-05 15:46 UTC
### Current behavior:

When I attempt to stub a route with two different responses for consecutive requests to an API, the mock server always response with the first response. This happens on circle CI only. On my local environment it works as expected.

Here's a screenshot from circle CI (failing):

![image](https://user-images.githubusercontent.com/17532458/52285255-edcf6480-295d-11e9-8867-260a64a4f967.png)

And locally:

![image](https://user-images.githubusercontent.com/17532458/52283788-0ee28600-295b-11e9-9354-c12e37f36f3a.png)

### Desired behavior:

I would like to be able to make requests to exactly the same endpoint, and to be able to get a different response each time.

This is what I would expect based on the Cypress docs:

> You can test a route multiple times with unique response objects by using aliases and cy.wait(). Each time we use cy.wait() for an alias, Cypress waits for the next nth matching request.

Reference: https://docs.cypress.io/api/commands/route.html#With-Stubbing

### Steps to reproduce: (app code and test code)

Here's my test code. Comments added for explanation:

```js
cy.route({
      url: 'api/cashflow-settings',
      method: 'GET',
      response: 'fixture:cashflow/settings-happy-path.json'
    }).as('getBankAccountsSuccess') // on the first request, return one set of data

    cy.get(SETTINGS_BUTTON).click()

    cy.wait('@getBankAccountsSuccess')

    // stub request to a different endpoint
    cy.route({
      url: 'api/cashflow-settings/**',
      method: 'POST',
      status: 409,
      response: {}
    }).as('excludeAccountConflict')

    cy.get('[data-testid="bank-account-item_id:1"] .switchThumb').click()
    cy.wait('@excludeAccountConflict')

    // second GET request to the same endpoint as the first request. Expect a different response object this time
    cy.route({
      url: 'api/cashflow-settings',
      method: 'GET',
      response: 'fixture:cashflow/settings-happy-path-all-excluded.json'
    }).as('getBankAccountsSuccessExcluded')

    cy.wait('@getBankAccountsSuccessExcluded')
```

### Versions

Cypress: 3.1.5
Chrome: 71.0.3578.98
OS: macOS Mojave

And CI:
- circleci/node:10.14.0-browsers
- cypress/base:10 (I've tried the default too)

**Comment by jennifer-shehane** [comment] 2019-02-14 05:06
Is the `wait` for the unexpected result returning the response from the `cy.route({url: 'api/cashflow-settings/**'}) definition? Or is it returning the response from the first `cy.route({url: 'api/cashflow-settings'})` definition?

**Comment by emilyb7** [comment] 2019-02-17 18:50
@jennifer-shehane as far as I can tell (rewatching the video captured as an artefact by CI), it's returning from the first `cy.route({url: 'api/cashflow-settings' })`

**Comment by jennifer-shehane** [comment] 2019-03-26 06:01
Duplicate of https://github.com/cypress-io/cypress/issues/3248

**Closed by jennifer-shehane** 2019-03-26 06:01 UTC
Labels: stage: needs investigating

**Comment by front-end-developer** [comment] 2020-08-05 16:36
Hi All,

I still see this issue in the latest version of Cypress v4.11.0, 

its now Aug 2020, has this been solved?
