### ISSUE TITLE
Alias is undefined after first test

### ISSUE THREAD

**Issue by lourenci** [cypress-io/cypress#2766] opened 2018-11-12 19:06 UTC
### Current behavior:

When defined inside a `before` hook, the alias becomes `undefined` after first spec.

![image](https://user-images.githubusercontent.com/2339362/48369171-eb31db80-e69c-11e8-9233-b54684b1e151.png)

### Desired behavior:

The alias should be available inside others `it`s in that context.

### Steps to reproduce:

```javascript
describe('test', function () {
  before(function () {
    cy.wrap({ id: 1 }).as('licensee')
  })

  it('first it', function () {
    console.log('first it', this.licensee)
  })

  it('second it', function () {
    // this.licensee is undefined
    console.log('second it', this.licensee)
  })
})
```

### Versions

Cypress 3.1.1
Chrome 70

**Comment by jennifer-shehane** [comment] 2018-11-13 16:24
Duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2018-11-13 16:24 UTC
