### ISSUE TITLE
Not able to fetch value of json variable updated on run time.

### ISSUE THREAD

**Issue by visjag** [cypress-io/cypress#7891] opened 2020-07-06 12:21 UTC
Updating json file with fixture on Runtime.
```js
cy.fixture('file').then((data) => {
var test = obj.text()
data.variableInFile = test
cy.writeFile("cypress/fixtures/file.json", data)
}
```
Fetching variable value in another function in same test,
```js
cy.fixture('file').then((data) => {
cy.get("id").type(data.variableInFile)
}
```

I'm getting last updated value from JSON not currently updated when I fetch.

When I fetch with `cy.readFile` it work as expected.

**Comment by jennifer-shehane** [comment] 2020-07-07 07:00
Duplicate of #4716

**Closed by jennifer-shehane** 2020-07-07 07:00 UTC
