### ISSUE TITLE
Passing a function to .should()

### ISSUE THREAD

**Issue by maisproject** [cypress-io/cypress#7824] opened 2020-06-26 02:13 UTC
### Current behavior:

Passing a function to the should statement results in a `null` parameter.

```
cypress_runner.js:197677 AssertionError: Target cannot be null or undefined.
 ```

The line `cy.get('span').should('have.length',25);` does work.

```js
  describe('Cypress ', () => {
    it(`Works `, () => { 
      cy.get('span').should('have.length',25);
      cy.get('span').should(($span) => {
        expect($span).to.have.length(25);
      });
    });
  })
```

### Desired behavior:

The should function should work as per the documentation. https://docs.cypress.io/api/commands/should.html#Function

### Test code to reproduce

```js
  describe('Cypress ', () => {
    it(`Works `, () => { 
      cy.get('span').should('have.length',25);
      cy.get('span').should(($span) => {
        expect($span).to.have.length(25);
      });
    });
  })
```

### Versions

Cypress 4.9
Windows 10
Chrome

**Comment by maisproject** [comment] 2020-06-26 04:13
After further testing, it works in electron and headless but not with Chrome.

**Comment by jennifer-shehane** [comment] 2020-06-26 11:59
@maisproject Please provide the accompanying HTML to reproduce this error. The test below works for me, and the failure is likely specific to the application you are testing against. Thanks!

`index.html`

```html
<html>
<body>
  <span></span>
  <span></span>
</body>
</html>
```

`spec.js`

```js
  it('Works', () => {
    cy.visit('index.html')
    cy.get('span').should('have.length', 2);
    cy.get('span').should(($span) => {
      expect($span).to.have.length(2);
    });
  });
```
<img width="507" alt="Screen Shot 2020-06-26 at 6 29 35 PM" src="https://user-images.githubusercontent.com/1271364/85854755-018d9c00-b7db-11ea-871e-b358d468ed62.png">

**Comment by jennifer-shehane** [comment] 2021-02-27 00:00
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-27 00:00 UTC
Labels: stage: needs information

**Comment by marymuniz** [comment] 2021-03-15 03:13
Hi! I'm getting the same message in some API tests.
Here are some examples:
```
expect(getTopTwoDeviceStatesResponse.body.value).to.have.lengthOf(2);

const hasExpectProperty = getASinglePropertyResponse.body.valu.every(el => el.Description);
expect(hasExpectProperty).to.be.true
```

**Comment by jennifer-shehane** [comment] 2021-03-19 19:59
@marymuniz We can't run the example provided. Please provide a full example we can run on our machine.
