### ISSUE TITLE
cy.wait for alias registered to non-first matching cy.intercept does not have response property (body & status)

### ISSUE THREAD

**Issue by core01** [cypress-io/cypress#14205] opened 2020-12-16 19:08 UTC
Hi guys, thank you so much for new intercept method, it is a great job!

But I have a problem, I need to have an opportunity to modify body for all requests to `API` to pass `isTestData` flag which will indicate that this data was created by cypress and it can be deleted. To do this I created `beforeEach` for all test cases and add `cy.intercept` for all `POST` requests, but It breaks the ability to receive a response body or status in `cy.wait`.

### Current behavior

response property doesn't exist
![image](https://user-images.githubusercontent.com/2903772/102386492-2faca580-3fe0-11eb-82b9-1898f7c0faf4.png)

### Desired behavior
response property should always exist

### Test code to reproduce

I created a repo with a small test case which show my problem https://github.com/core01/cypress-intercept/blob/main/cypress/integration/spec.js

And below you can see a  code from a project I'm working on:

support/beforeEach.js:
```js
beforeEach(() => {
  cy.intercept('POST', '*', (req) => {
    req.body.isTestData = true;
  });
});

```

support/commands.js:

```js
Cypress.Commands.add('createOrganization', (organizationName) => {
  Cypress.log({
    name: 'createOrganization',
    message: 'Create a superuser and new organization',
  });

  cy.intercept('POST', '**/organizations').as('createOrganization');
  cy.intercept('GET', '**/organizations/*/profiles?pageSize=*').as('getProfileList');

  // visit organization creation page and fill form
  cy.visit('/create-organization');
  cy.get('[data-test=input-organization-name]').type(organizationName);
  cy.get('[data-test=btn-create-organization]').click();

  // check createOrganization request and assign an alias for organizationId
  cy.wait('@createOrganization').then((interception) => {
    console.log('aaaa', interception);
  }).its('response.body.id').as('organizationId');
});
```

support/index.js:

```js
import './commands';
import './beforeEach';
```

### Versions

Cypress 6.1.0
Chrome/Electron. Mac Big Sur

The same problem was described in [this](https://github.com/cypress-io/cypress/issues/4934#issuecomment-738691221) comment, but I think that it deserves a separate issue

Related issue - https://github.com/cypress-io/cypress/issues/8493

**Comment by cbruge** [comment] 2020-12-16 19:45
Hey, the object that intercept yields slightly differs from the one that route yielded. Click on the wait and see the output in the console. From the top of my head it should be something like, e.g. .then((call) => { const responseBody = call.response.body});

**Comment by cbruge** [comment] 2020-12-16 19:48
Also check https://docs.cypress.io/api/commands/intercept.html#Using-the-yielded-object

**Comment by avient** [comment] 2020-12-16 20:10
Having the same issue on some requests with intercept(). But works as expected with route()

**Comment by vrknetha** [comment] 2020-12-22 16:46
Same as this , already filed since the release 5.6.0

https://github.com/cypress-io/cypress/issues/9150

**Comment by jennifer-shehane** [comment] 2020-12-29 09:14
I can reproduce this with the given example. I believe this is because the alias is registered to the second intercept. We don't support overriding intercepts that match exactly, but are working on support: https://github.com/cypress-io/cypress/issues/9302 I'm not completely sure this will be resolved by that solution though, so I'm leaving this open.

I actually think this is this issue, but Kevin said his issue was resolved. https://github.com/cypress-io/cypress/issues/9262 So, I'll leave this issue open as the reproducible example.

### Reproducible example


```js
it('route should work', () => {
  cy.server()
  cy.route('GET', '**/comments/*')
  cy.route('GET', '**/comments/*').as('getComment')

  cy.visit('https://example.cypress.io/commands/waiting')

  cy.get('.network-btn').click()

  // ✅ passes 'status' does exist
  cy.wait('@getComment').its('status').should('be.oneOf', [200, 304])
})

it('intercept should work', () => {
  cy.intercept('GET', '**/comments/*')
  cy.intercept('GET', '**/comments/*').as('getComment')

  cy.visit('https://example.cypress.io/commands/waiting')

  cy.get('.network-btn').click()

  // ❗️ fails 'response' does not exist
  cy.wait('@getComment').its('response.statusCode').should('be.oneOf', [200, 304])
})
```

<img width="456" alt="Screen Shot 2020-12-29 at 3 43 12 PM" src="https://user-images.githubusercontent.com/1271364/103272989-97092300-49ec-11eb-9320-294ee6e3d33f.png">

**Comment by VinitMaheswari** [comment] 2021-02-02 12:06
@jennifer-shehane Any update on this bug fix? When shall we expect fix for this bug.

Thanks.

**Comment by VinitMaheswari** [comment] 2021-02-04 07:13
As a work around, To get response from an intercept(). 

Intercept an API, Take the request from the intercepted method. Then use cy.request() for that intercepted URL and body (if present). And then find the response from cy.request().

**Comment by core01** [comment] 2021-02-04 07:21
@VinitMaheswari could you please provide an example with code?

**Comment by VinitMaheswari** [comment] 2021-02-04 07:33
HI @core01 

Please find the below code and Let me know if you need any help. The same piece of code is working for me.

`cy.intercept('POST', '/API Need to be intercpeted**').as('intercept');
// Click for an event to call API. For example: here clicking on a button
cy.findByRole('button', {
  name: 'Search'
}).should('exist').click();
// Waiting for an alias
cy.wait('@intercept').then((res) => {
  //Storing the request body and URL of an intercepted API
  let body = JSON.stringify(res.request.body);
  let URL = Path of the intercpeted API or find it.As done
  for body.
  console.log('URL ' + URL);
  console.log('Body ' + body);
  //Now calling the same API with request() method.
  cy.request({
    method: 'POST',
    url: URL,
    body: body,
  }).then((response) => {
    // response.body is automatically serialized into JSON
    expect(response.status).to.eq(200);
    console.log('Response Body ' + JSON.stringify(response));
  });
});`

**Closed** 2021-03-16 21:18 UTC
Labels: pkg/net-stubbing, stage: pending release, type: unexpected behavior
