### ISSUE TITLE
Screen freezes in production

### ISSUE THREAD

**Issue by shaklin-box8** [cypress-io/cypress#16203] opened 2021-04-26 12:53 UTC
Hi, 

I have encountered an unreproducible bug, this happens only when i run in our Jenkins server, the problem is that the screen freezes while i run the spec, i tried changing the browser(came across a thread where it stated that it happens in chromium based browsers), check the resource utilisation and the CPU is at 3%. Not sure how to go about it, any help would be great.

**Comment by alexneo2003** [comment] 2021-04-27 11:08
I have the same problem with 7.2.0 but in runner mode with 'cypress open' command and headless mode too (cypress run)
runner gets stuck and no more action, no logs, no exceptions
and i can't get to reproduce than because it's happens randomly

**Comment by jennifer-shehane** [comment] 2021-04-27 19:20
There are some performance issues introduced in recent versions of Cypress, please see those issues for relevant updates. We're working on them.

- https://github.com/cypress-io/cypress/issues/15853
- https://github.com/cypress-io/cypress/issues/15779
- https://github.com/cypress-io/cypress/issues/16152
- https://github.com/cypress-io/cypress/issues/15973
- https://github.com/cypress-io/cypress/issues/15990

If you are running Cypress in a headless browser, please try reducing the screen size to the default size prior to 7.0 (1280x720) to see if the new issues are related to the increase in screen size. [Instructions here.](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless) 

If that doesn't resolve the issue, I suggest downgrading to the last known version of Cypress that worked well.

We'll be closing this issue as there are no reproducible actions. For now we need to focus on the performance issues where we're given clear reproducible examples.  Feel free to open a new issue if there are steps to fully reproduce the issue.

**Closed by jennifer-shehane** 2021-04-27 19:20 UTC
