### ISSUE TITLE
Cypress login fail randomly 

### ISSUE THREAD

**Issue by felixpro** [cypress-io/cypress#24602] opened 2022-11-08 20:23 UTC
### Current behavior

When running Cypress using the cypress open or run command. The first test always passes, but one or two of the next tests randomly fails. And what happens it's that cypress It's logging correctly but In some tests, instead of redirecting to the home page, it stays completely frozen on the login page. 

When I run the tests I waited for it to fail and then I stopped the test after it fail. After that, I opened a new tab in the cypress browser and I went into the home page http://localhost:4000/. And I could access the app without having to log in. It means that I am being logged in correctly, it's just that for some reason the test freezes on the login page.

![Image of the error](https://user-images.githubusercontent.com/42367473/200669262-6c76f28b-ff76-4516-b4f6-0ac444c128eb.png)

Notes: 

- I'm using **@badeball/cypress-cucumber-preprocessor**
- I'm not receiving any logs in the console or in cypress. 
- Even without using the cypress framework the error appears. 

------ ------ ------- -------- ------- -----

Here is my `cypress.config` 
```
const { defineConfig } = require('cypress');
const webpack = require('@cypress/webpack-preprocessor');
const preprocessor = require('@badeball/cypress-cucumber-preprocessor');

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on(
    'file:preprocessor',
    webpack({
      webpackOptions: {
        resolve: {
          extensions: ['.ts', '.js'],
        },
        module: {
          rules: [
            {
              test: /\.feature$/,
              use: [
                {
                  loader: '@badeball/cypress-cucumber-preprocessor/webpack',
                  options: config,
                },
              ],
            },
          ],
        },
      },
    })
  );

  // Useful trick for debugging: cy.task('log', 'soem text')
  on('task', {
    log(...params) {
      console.log(...params);

      return null;
    },
  });

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

module.exports = defineConfig({
  e2e: {
    setupNodeEvents,
    baseUrl: 'http://localhost:4000/',
    specPattern: './cypress/integration/**/*.feature',
    screenshotOnRunFailure: true,
    screenshotsFolder: 'cypress/output/screenshots',
    videosFolder: 'cypress/output/videos',
    experimentalStudio: true,
    numTestsKeptInMemory: 0,
    env: {
      TAGS: 'not @manual and not @MANUAL and not @ignore',
    },
    supportFile: false,
  },
});
```

This is the steps file: 

```
Given('I am an authenticated user to filter milestones', () => {
  cy.visit('/');
  const username = Cypress.env('auth_username');
  const password = Cypress.env('auth_password_valid');
  cy.get('input[data-fx-name="email"]').type(username);
  cy.get('input[data-fx-name="password"]').type(password, { log: false });
  cy.get('button[data-fx-name="submit"]').click();
});

And('There are existing Milestones assigned to different clients', () => {
  cy.location('pathname').should('equal', '/marketingcloudfx/dashboard');
  cy.get('div[data-fx-name="TeamworkFX"').click();
  cy.location('pathname').should('equal', '/dashboard');
  cy.get('a[data-fx-name="QA Testing Project"]').scrollIntoView().click({ force: true });
});

And('I access TeamworkFX Milestones Page to filter milestones', function () {
  cy.location('pathname').should('contain', '/overview');
  cy.get('li[data-fx-name="Milestones"]').click();
  cy.location('pathname').should('contain', '/milestones');
});

When('I click the Assigned To', () => {
  cy.get('[data-fx-name="milestoneAssigneeDropdown"]>div>div>div').first().click({ force: true });
});

Then('A dropdown list is displayed', () => {
  cy.get('[data-fx-name="milestoneAssigneeDropdownOpened"]').should('be.visible');
});

And('It displays all clients for the project', () => {
  cy.get('[data-fx-name="milestoneAssigneeDropdownOpened"]').children().children().should('have.length.at.least', 2);
});

When('I click the Add a New Milestone button', () => {
  cy.get('button[data-fx-name="addANewMilestone"]').click();
});

And('I fill all of the details', () => {
  cy.get('[data-fx-name="addMilestoneTitle"]>div:nth-child(2)>input').type('Mock Milestone');
});

Then('I click the Add Milestone button', () => {
  cy.get('button[data-fx-name="addMilestone"]').click();
});`
```

### Test code to reproduce

```
Given('I am an authenticated user to filter milestones', () => {
  cy.visit('/');
  const username = Cypress.env('auth_username');
  const password = Cypress.env('auth_password_valid');
  cy.get('input[data-fx-name="email"]').type(username);
  cy.get('input[data-fx-name="password"]').type(password, { log: false });
  cy.get('button[data-fx-name="submit"]').click();
});

And('There are existing Milestones assigned to different clients', () => {
  cy.location('pathname').should('equal', '/marketingcloudfx/dashboard');
  cy.get('div[data-fx-name="TeamworkFX"').click();
  cy.location('pathname').should('equal', '/dashboard');
  cy.get('a[data-fx-name="QA Testing Project"]').scrollIntoView().click({ force: true });
});

And('I access TeamworkFX Milestones Page to filter milestones', function () {
  cy.location('pathname').should('contain', '/overview');
  cy.get('li[data-fx-name="Milestones"]').click();
  cy.location('pathname').should('contain', '/milestones');
});

When('I click the Assigned To', () => {
  cy.get('[data-fx-name="milestoneAssigneeDropdown"]>div>div>div').first().click({ force: true });
});

Then('A dropdown list is displayed', () => {
  cy.get('[data-fx-name="milestoneAssigneeDropdownOpened"]').should('be.visible');
});

And('It displays all clients for the project', () => {
  cy.get('[data-fx-name="milestoneAssigneeDropdownOpened"]').children().children().should('have.length.at.least', 2);
});

When('I click the Add a New Milestone button', () => {
  cy.get('button[data-fx-name="addANewMilestone"]').click();
});

And('I fill all of the details', () => {
  cy.get('[data-fx-name="addMilestoneTitle"]>div:nth-child(2)>input').type('Mock Milestone');
});

Then('I click the Add Milestone button', () => {
  cy.get('button[data-fx-name="addMilestone"]').click();
});
```

### Cypress Version

10.7.0

### Node version

16.17.0

### Operating System

Mac M1

### Debug Logs

```shell
No logs
```

**Comment by ryanthemanuel** [comment] 2022-11-16 21:44
Hi @felixpro. Thank you for logging an issue. When this error occurs are you seeing any errors in the developer tools console? Also, your screenshot is helpful. Can you show a screenshot of what one of the successful tests looks like? It could be useful to compare what is happening on success vs. what is happening on failure.

**Comment by ryanthemanuel** [comment] 2022-11-16 21:45
Hi @felixpro. Thank you for logging an issue. When this error occurs are you seeing any errors in the developer tools console? Also, your screenshot is helpful. Can you show a screenshot of what one of the successful tests looks like? It could be useful to compare what is happening on success vs. what is happening on failure.

**Comment by ryanthemanuel** [comment] 2022-11-16 21:46
Hi @felixpro. Thank you for logging an issue. When this error occurs are you seeing any errors in the developer tools console? Also, your screenshot is helpful. Can you show a screenshot of what one of the successful tests looks like? It could be useful to compare what is happening on success vs. what is happening on failure.

**Comment by mjhenkes** [comment] 2022-11-23 14:25
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment or open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as completed by mjhenkes** 2022-11-23 14:25 UTC
