### ISSUE TITLE
Runner crashes while opening a new Electron browser by clicking link in url bar

### ISSUE THREAD

**Issue by ksezen59** [cypress-io/cypress#18888] opened 2021-11-11 18:51 UTC
### Current behavior

While the test is running in running container, I click the link in url bar and application crashes after seconds and nothing displayed in new window.

GET /api/mySegments/5ee3e889-30a2-4c0c-83ae-02c7b01f4ec3 200 117.266 ms - -
POST /api/v1/p 200 241.096 ms - -
Error: ERR_FAILED (-2) loading 'https://miro.com/'
    at rejectAndCleanup (electron/js2c/browser_init.js:161:7486)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:161:7861)
    at Object.emit (events.js:376:20)
 {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'https://miro.com/'
}
Error: ERR_FAILED (-2) loading 'https://miro.com/'
    at rejectAndCleanup (electron/js2c/browser_init.js:161:7486)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:161:7861)
    at Object.emit (events.js:376:20)

### Desired behavior

Cypress should open the link in new window and keep running the test in runner container.

### Test code to reproduce

Visit any website.

### Cypress Version

8.7.0

### Other

Electron 93

**Comment by BlueWinds** [comment] 2021-11-16 19:42
I'm unable to reproduce on Cypress 8.7.0 or 9.0.0. 

```
it('works as expected', () => {
  cy.visit('https://duckduckgo.com/?q=miro')
})
```
Steps attempted:
1. Run in Electron.
2. Manually click on the first search result - electron visits the page as expected, no crash.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

If you can put together a reproducible example we'll consider reopening - crashes are definitely not expected behavior!

**Closed by BlueWinds** 2021-11-16 19:42 UTC
