### ISSUE TITLE
Cypress.config('baseUrl') escapes slash

### ISSUE THREAD

**Issue by Saibamen** [cypress-io/cypress#3540] opened 2019-02-20 14:55 UTC
### Current behavior:

![image](https://user-images.githubusercontent.com/905878/53100266-c238a680-3527-11e9-8511-788ae62f0866.png)

### Desired behavior:

![image](https://user-images.githubusercontent.com/905878/53100313-d381b300-3527-11e9-957a-ff2ff83b411c.png)

### Steps to reproduce: (app code and test code)

cypress.json
```json
{
  "env": {
    "test_url": "http://localhost:3000/"
  },
  "baseUrl": "http://localhost:3000/"
}
```
Example test:
```js
it('test url', function () {
    cy.visit('/')
    var baseUrl = Cypress.config('baseUrl')
    //baseUrl = baseUrl + '/'    // bug in Cypress - add slash
    cy.url().should('eq', Cypress.env('test_url'))
    cy.url().should('eq', baseUrl)
})
```

### Versions

Windows, Cypress 3.1.5

**Comment by jennifer-shehane** [comment] 2019-02-20 16:45
Duplicate of https://github.com/cypress-io/cypress/issues/2101

**Comment by jennifer-shehane** [comment] 2019-02-20 16:47
Sorry, this is not a duplicate at all. I read this assertion incorrectly. The issue here is that the `Cypress.config('baseUrl')` is not evaluating to the correct value. The `baseUrl` value is `http://localhost:3000/`, but is evaluating as `http://localhost:3000` in the test, removing the trailing slash.

**Comment by jennifer-shehane** [comment] 2019-02-20 16:59
I've confirmed this situation.

**cypress.json**
```json
{
  "baseUrl": "http://localhost:8080/"
}
```

**test**
```js
it('test url', function () {
  cy.visit('/')
  cy.url().should('eq', Cypress.config('baseUrl'))
})
```

<img width="439" alt="screen shot 2019-02-20 at 11 23 15 pm" src="https://user-images.githubusercontent.com/1271364/53109066-896bf200-3566-11e9-9996-5138a0c65343.png">

Also, the config in the Desktop GUI displays without the trailing slash as well.

<img width="912" alt="screen shot 2019-02-20 at 11 21 37 pm" src="https://user-images.githubusercontent.com/1271364/53109111-9d175880-3566-11e9-83a9-011835824015.png">

I'm pretty sure a good deal of the baseUrl logic is contained in this file: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/location.coffee

**Comment by Saibamen** [comment] 2019-02-20 19:13
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/config.coffee#L232

**Closed** 2019-02-21 23:50 UTC
Labels: stage: ready for work, type: bug
