### ISSUE TITLE
Unable to open URL using cy.visit() 

### ISSUE THREAD

**Issue by vinaybshetty** [cypress-io/cypress#5928] opened 2019-12-10 18:55 UTC

**Comment by vinaybshetty** [comment] 2019-12-10 18:56
None of the URL even local host url's are opening through cypress

**Comment by nwiatrek** [comment] 2019-12-11 02:56
Can you provide what your spec.js file looks like? are you using a baseUrl in `cypress.json`?

**Comment by jennifer-shehane** [comment] 2019-12-13 11:54
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-12-13 11:54 UTC
