### ISSUE TITLE
Multiple versions of cypress fail install with yarn workspaces on travis-ci

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/cypress#2340] opened 2018-08-14 15:08 UTC
### Current behavior:

Cypress v3.1.0 doesn't unzip:
```
[14:59:00]  Downloading Cypress     [started]
[14:59:02]  Downloading Cypress     [completed]
[14:59:02]  Unzipping Cypress       [started]
[14:59:02]  Unzipping Cypress       [failed]
The Cypress App could not be unzipped.
```

### Desired behavior:

It should unzip

### Steps to reproduce:

Multiple runs on travis with v3.1.0 failed after clearing travis cache, but I was able to clear the travis cache and use v3.0.3

### Versions

Cypress v3.1, travis-ci, ubuntu 14

**Comment by paulfalgout** [comment] 2018-08-14 15:11
I was able to download https://download.cypress.io/desktop?platform=linux64 and unzip it on osx

**Comment by paulfalgout** [comment] 2018-08-14 15:35
Ok figured this out.  We're using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) to install multiple packages for a shared lock file / node_modules directory.  In just testing one of our projects in `v3.1.0` it fails the install on travis, but not locally on OSX.  Updating both to `v3.1.0` fixes the issue.  This might be because we're using a custom cypress cache directory?

In any case, the real issue is different than described, though there's probably something to do here with the error?  I'm not 100% sure what the conflict is that's causing it to fail however.

**Comment by jennifer-shehane** [comment] 2019-07-23 12:23
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4595

**Closed by jennifer-shehane** 2019-07-23 12:23 UTC
Labels: stage: needs investigating
