### ISSUE TITLE
Upload same file more than one time when uploading multiple files

### ISSUE THREAD

**Issue by SonaliQA** [cypress-io/cypress#8371] opened 2020-08-21 02:30 UTC
### Current behavior:
When I upload  multiple files then actually it uploads same file more than one time

**For Instance:**
When i upload A+B+C then it will upload A + B +A +C +B+A

### Desired behavior:
When i upload A+B+C then it should upload A + B +C only (should not repeated)

### Test code to reproduce
[Test code to reproduce.txt](https://github.com/cypress-io/cypress/files/5106423/Test.code.to.reproduce.txt)

**Uploading three files (A+B+C)**
![uploading moreThanOneFile](https://user-images.githubusercontent.com/62263280/90845448-1c404500-e334-11ea-9342-3efccface5bb.PNG)

**Uploaded six files and one file more than three files (A +B+ A+C+ B+ A)**
![uploaded sameFileOnMultipleTimes](https://user-images.githubusercontent.com/62263280/90845339-daaf9a00-e333-11ea-87c9-c2c59f84b135.PNG)

**Debug Log**
[Debug log-MultipleFile.log](https://github.com/cypress-io/cypress/files/5106439/Debug.log-MultipleFile.log)

### Versions

Chrome :  83
Cypress : 4.10.0
OS : Win10

**Comment by jennifer-shehane** [comment] 2020-08-21 05:49
We'll need a fully reproducible example we can run to track down the issue. The test code provided can't be run as there is no url provided to test against. 

I see you're using the [`cypress-upload-file`](https://www.npmjs.com/package/cypress-file-upload) plugin. You may want to check that this is not a bug with that plugin also - does the upload do multiple files when using Cypress alone, for example? 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-21 05:49 UTC
