### ISSUE TITLE
Create React App + Cypress 5.0 - cannot find module 'tslib'

### ISSUE THREAD

**Issue by stevensacks** [cypress-io/cypress#8360] opened 2020-08-20 08:06 UTC
### Current behavior:

```
npm run cy:run

> cypress run

It looks like this is your first time using Cypress: 5.0.0

  ✔  Verified Cypress! /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app

Opening Cypress...
Cannot find module 'tslib'
Require stack:
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/reporter/lib/resolve-dist.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/reporter.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/routes.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/server.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/run.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/index.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/index.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/index.js
-
Error: Cannot find module 'tslib'
Require stack:
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/reporter/lib/resolve-dist.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/reporter.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/routes.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/server.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/run.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/index.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/index.js
- /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/index.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module._load (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:18:25)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/reporter/lib/resolve-dist.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Module.m._compile (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Object.require.extensions.<computed> [as .js] (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module._load (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:18:25)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/reporter.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Module.m._compile (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Object.require.extensions.<computed> [as .js] (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module._load (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:18:25)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/routes.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Module.m._compile (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Object.require.extensions.<computed> [as .js] (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module._load (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:18:25)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Server.createRoutes (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/server.js:174:12)
    at /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/server.js:220:12
    at tryCatcher (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Server.open (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/server.js:195:23)
    at /Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:119:26
    at tryCatcher (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/steven/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.1.0 cy:run: `cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@0.1.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steven/.npm/_logs/2020-08-20T08_00_17_360Z-debug.log
```

### Desired behavior:

Cypress to run successfully.

### Test code to reproduce

Create a new Create React App project with TypeScript, and then install Cypress.

### Versions

MacOS Catalina 10.15.6
Node 10.16.3
Npm 6.14.6
Cypress 5.0
TypeScript 3.9.7

**Comment by stevensacks** [comment] 2020-08-20 08:09
@jennifer-shehane I just noticed that on [this thread](https://github.com/cypress-io/cypress/issues/8162#issuecomment-674730268) you mentioned that this error might be fixed in v5. Unfortunately, looks like it's still happening.

Are there any leads as to what might be causing it and/or how to fix it?

**Comment by jennifer-shehane** [comment] 2020-08-20 08:15
Duplicate of #8162 

No, I'm not sure why this error happens or if this is even an error with Cypress itself - we haven't been able to reproduce.

**Closed by jennifer-shehane** 2020-08-20 08:15 UTC
