### ISSUE TITLE
Cypress: Stubbing not working for static TS methods

### ISSUE THREAD

**Issue by AlanKrygowski** [cypress-io/cypress#7394] opened 2020-05-18 10:05 UTC
### Current behavior:
The full issue was already described in the [so question here](https://stackoverflow.com/questions/61821245/cypress-stubbing-not-working-for-static-ts-methods). I've tried looking for help there, but seeing no response I'm starting to believe the issue is much deeper. 

Here is the content of the so question for easier access:
### Setup:

I'm trying to test out a component using a static method of a redirecting service which uses `window.location.href`.
The idea was to stub the operation and check the url.
While looking around the net I've found [this article](https://medium.com/cypress-io-thailand/understand-stub-spy-apis-that-will-make-your-test-better-than-ever-on-cypress-io-797cb9eb205a) and decided to apply its technique by creating a static method in my TS file:
```ts
static setLocation(href: string) {
  window.location.href = href;
}
```
The stub created for this is rather simple (the test is still in an early phase):
```js
const locationStub = (href) => {
  cy.log("Called for " + href);
};
```

And I've applied it in `beforeLoad`:
```js
onBeforeLoad(win) {
  cy.stub(Service, 'setLocation', locationStub);
},
```

The pipe of dependencies looks like this:
```
buttonClickListener -> static redirecting method -> setLocation -> window.location.href
```
### Current behaviour:

The issue is that this does not work at all. As you can see from my `cy.log` the stub is not picked up at all, as can be see here (the first stub is a `window.open` stub that actually works fine and dandy).
![image](https://user-images.githubusercontent.com/29440326/82200460-521df980-98ff-11ea-8456-3152f756f0f0.png)

### Desired behavior:

The static methods stub should be properly picked up and and its contents replaced.

I have already tried replacing the stub method with 
```js
cy.stub(Service, 'setLocation').callsFake(locationStub);
```

Turning the method into a non-static also doesn't seem to be picked up - most likely due to the differences between instances.

Solving the instance issues in this example does not solve the issues as well. 
```js
cy.stub(Service.prototype, 'setLocation').callsFake(locationStub)
```
After applying, it produces the exact same outcome without any logging of the issues.

### Desired behavior:

The redirect should not happen and the replacing function ought be called.

### Versions

- Cypress: 13.4;
- System: Mac OS
- Browser: Cypress-Chrome

**Comment by jennifer-shehane** [comment] 2020-05-19 10:40
The function to replace your original method in needs to be runnable from your application, so called `cy.log()` in place of the `setLocation` function will never work - since that's only callable within Cypress, not your application. This would never log in the Cypress console.

Can you provide a full example? Where this ts file is? Where it's being called? Something we can completely run to see the issue?

**Comment by AlanKrygowski** [comment] 2020-05-19 11:02
@jennifer-shehane Understood. However - the function I'm replacing does also have a `console.log` which ought then show up in the console and yet, it doesn't. 

Unfortunately I can not provide too much information about the project and give the files out as-is.
I'll try to put together a reproductible example as soon as possible.
The files are properly imported. Cypress actually seems to properly know of the function because if I run it with an intentional mistake, like:
```
cy.stub(Service, 'setLocation2').callsFake(locationStub);
```
The error will be that I'm stubbing an nonexistent method.

**Comment by jennifer-shehane** [comment] 2020-10-20 11:15
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-10-20 11:15 UTC
Labels: stage: needs information
