### ISSUE TITLE
Error: Source and destination must not be the same.

### ISSUE THREAD

**Issue by kemsky** [cypress-io/cypress#4637] opened 2019-07-02 21:34 UTC
### Current behavior:

Random fails on CI server

```
[00:19:14]	[Step 21/21]   (Video)
[00:19:14]	[Step 21/21] 
[00:19:14]	[Step 21/21]   - Started processing:   Compressing to 32 CRF
[00:19:16]	[Step 21/21]   - Finished processing:  C:\TeamCity\buildAgent\work\89524d52ec0f2109\XXXXXXX\cypress\videos\master.affiliate.plan.name.spec.js.mp4 (1 second)
[00:19:16]	[Step 21/21] 
[00:19:16]	[Step 21/21] { Error: Source and destination must not be the same.
[00:19:16]	[Step 21/21]     at getStats (C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\util\stat.js:82:17)
[00:19:16]	[Step 21/21]     at fs.stat (C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\util\stat.js:51:16)
[00:19:16]	[Step 21/21]     at C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:285:20
[00:19:16]	[Step 21/21]     at FSReqWrap.oncomplete (fs.js:153:5)
[00:19:16]	[Step 21/21] 
[00:19:16]	[Step 21/21]   cause: Error: Source and destination must not be the same.
[00:19:16]	[Step 21/21]     at getStats (C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\util\stat.js:82:17)
[00:19:16]	[Step 21/21]     at fs.stat (C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\util\stat.js:51:16)
[00:19:16]	[Step 21/21]     at C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:285:20
[00:19:16]	[Step 21/21]     at FSReqWrap.oncomplete (fs.js:153:5)
[00:19:16]	[Step 21/21] ,
[00:19:16]	[Step 21/21]   isOperational: true }
[00:19:16]	[Step 21/21] Error: Source and destination must not be the same.
[00:19:16]	[Step 21/21]     at getStats (C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\util\stat.js:82:17)
[00:19:16]	[Step 21/21]     at fs.stat (C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\util\stat.js:51:16)
[00:19:16]	[Step 21/21]     at C:\Users\Administrator\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:285:20
[00:19:16]	[Step 21/21]     at FSReqWrap.oncomplete (fs.js:153:5)
```

### Desired behavior:

NO errors.

### Steps to reproduce: (app code and test code)

`cypress run --reporter teamcity`

### Versions

"cypress": "3.3.2"

nodejs 12.*

**Comment by jennifer-shehane** [comment] 2019-07-03 04:13
@kemsky Thank you for opening this issue. This is definitely due to our updating `fs-extra` in version [3.3.2](https://on.cypress.io/changelog#3-3-2). 

I wasn't able to reproduce this by installing [mocha-teamcity-reporter](https://github.com/travisjeffery/mocha-teamcity-reporter) `npm install mocha-teamcity-reporter --save-dev` then running `cypress run --reporter teamcity`. 

I do see that the teamcity reporter was properly found and is logging, but not displaying the error you are seeing.

```
────────────────────────────────────────────────────────────────────────────────────────────────────

  Running: examples/actions.spec.js...                                                     (1 of 1)
##teamcity[testSuiteStarted name='My First Test']
##teamcity[testStarted name='Visits slatejs' captureStandardOutput='true']
##teamcity[testFinished name='Visits slatejs' duration='5036']
##teamcity[testSuiteFinished name='My First Test' duration='NaN']
##teamcity[testSuiteFinished name='mocha.suite' duration='8797']

  (Results)
```

**Can you provide ALL of the configuration around your use of the `teamcity` reporter.** I suspect this is bug is only happening with the configuration you specifically set up. Also anything you specifically set up after the run has completed (if using the Module API).

## Why this is happening

Effectively in the newer versions of [fs-extra](https://www.npmjs.com/package/fs-extra) that we upgraded to using in the Cypress code, fs-extra is more diligent in checking that we are not copying a file from a source to the exact same destination file (even if symlinked). 

## Current Workaround

Downgrade to Cypress version [3.3.1](https://on.cypress.io/changelog#3-3-1) - this will not error in that version.

**Comment by kemsky** [comment] 2019-07-03 09:57
@jennifer-shehane there is nothing special in our setup:

```json
{
  "projectId": "XXXXXX",
  "baseUrl": "http://localhost:5001",
  "testFiles": "**/*.spec.js",
  "integrationFolder": "cypress/tests/integration",
  "chromeWebSecurity": false,
  "modifyObstructiveCode": false,
  "viewportWidth": 1200
}
```

We are using builtin teamcity reporter (docs link https://docs.cypress.io/guides/tooling/reporters.html#Reporter-Options) 
I'm not sure if this error is related to teamcity reporter.

Exception message does not contain actual resource path, but nothing points to mistake on our end.

**Comment by jennifer-shehane** [comment] 2019-07-03 10:11
Oh, interesting. I actually didn't realize that we package teamcity reporter into Cypress. 

We use our own fork of the project here https://github.com/cypress-io/mocha-teamcity-reporter so let me dig into that.

**Comment by jvanoostveen** [comment] 2019-07-24 08:07
I'm seeing these errors as well (not using teamcity reporter). So it might be related to something else. Looks like it is doing some processing with the video?

**Comment by jvanoostveen** [comment] 2019-07-24 08:08
Using Cypress 3.4.0 by the way.

**Comment by jvanoostveen** [comment] 2019-08-05 09:03
Any update on this? It is randomly failing our builds and making Cypress even more flaky than the Selenium we are trying to replace...

**Comment by baptistepattyn** [comment] 2019-08-12 09:00
I have had the same issue as described by @jvanoostveen 
I do believe it has something to do with the video compression as he mentions...
![image](https://user-images.githubusercontent.com/48830942/62854696-5a059900-bcf0-11e9-85e1-28a727efdbf1.png)

I got the error right after the video compression started

**Comment by hadighattas** [comment] 2019-09-23 09:57
Any updates on this issue as https://github.com/cypress-io/cypress/issues/1906 / https://github.com/cypress-io/cypress/issues/4164 were fixed in 3.3.2 and 3.3.2 has this issue

**Comment by jvanoostveen** [comment] 2019-09-23 10:44
The label says: existing workaround, which is not really true, as the workaround is not updating. We'll been stuck on 3.3.1 until this bug is fixed...

**Comment by joshuakeel** [comment] 2019-09-24 17:36
This is happening for us on 3.4.0 as well.

**Comment by AliceShi789654** [comment] 2019-11-05 01:32
This is happening on 4.3.1 as well, but it could not reproduce stably.

**Comment by kemsky** [comment] 2019-11-07 11:06
@jennifer-shehane, can't you simply add some debug information to logs to trace this problem? We can not upgrade since July.

**Comment by joshuakeel** [comment] 2019-12-02 19:10
@jennifer-shehane Will the resolution of this issue involve updating the paths so the source and destination are not the same? I'm not sure exactly what paths those are, but I assume the paths of video files that are being written.

I'm interested in potentially working on this, since this is a blocking issue for my team that prevents us from being able to use the latest Cypress.

**Comment by adil060606** [comment] 2020-02-27 12:22
Any news regarding ? Its still happens to us occasionally and fails our build...

**Comment by kemsky** [comment] 2020-02-27 13:58
@adil060606, version 4.0.1 works for me, but I don't know how stable it will be for you.

**Comment by jennifer-shehane** [comment] 2020-07-09 05:56
I'm not sure this issue is still occurring for anyone in our latest version. We did upgrade `fs-extra` in 4.0.0, which may have resolved the issue. https://github.com/cypress-io/cypress/pull/5632 Maybe this issue? https://github.com/jprichardson/node-fs-extra/issues/657

Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-09 05:56 UTC
Labels: pkg/server, stage: needs information, topic: reporters 📄, type: regression, v3.3.2 :bug:
