### ISSUE TITLE
GUI test auto-reload on trigger.

### ISSUE THREAD

**Issue by jamiuadeleke** [cypress-io/cypress#412] opened 2017-02-06 19:07 UTC
Hi Guys! Love cypress. Using it daily.
simple question: is it possible to have cypress reload a test automatically when I am working on a dependant file? Like I do with rspec and guard?
I use ember, so say i'm working on a particular route hello.js and my tests that are tied to it are in hello_spec.js
when i change the routefile, can it autoreload hello_spec? I can setup a guard file with a particular command / watcher or something if there is a commandline way to do this.
I am not worried about headless, i'm thinking of my development flow. It would help team adoption dramatically

Thanks,

**Comment by brian-mann** [comment] 2017-02-06 19:50
If you were writing a unit test and you were importing or requiring `hello.js` from `hello_spec.js`, then it would automatically reload when the source was changed.

The problem is that you are likely writing `integration` or `e2e` tests, and in that case you are not requiring or importing your source files.

In that case its impossible for Cypress to know when it should rerun your tests when your source changes.

What we can do in this situation is add a new configuration option like: `watchForAdditionalFileChanges`: "src/**/*" and give you the ability to provide a glob pattern which then will automatically wait all of these files and reload whenever any of them change.

It can get a bit tricky though due to system file watching limits, so we might have to do a bit more work to make a good experience around this.

Another option is for us to enable you to tell Cypress when to reload (so you can manually manage file watching on your own end). You'd have to send us a message over `ipc` or use something like a process signal that we bind to.

**Comment by fvanwijk** [comment] 2017-02-10 12:03
Related to #188

**Comment by jennifer-shehane** [comment] 2017-11-01 18:29
Closing in favor of #456 which defines more specific implementation details.

**Closed by jennifer-shehane** 2017-11-01 18:29 UTC
