### ISSUE TITLE
cy.visit keep redirecting to the same page 

### ISSUE THREAD

**Issue by amrayoub** [cypress-io/cypress#3594] opened 2019-02-26 12:49 UTC
### Current behavior:
basically when I try to Microsoft login page
```js
cy.visit('https://login.microsoftonline.com/')
```

For some reason, my login page is redirecting me to the login page, which is in turn redirected to the login page and so on ....

<img width="645" alt="screen shot 2019-02-26 at 13 45 23" src="https://user-images.githubusercontent.com/16503306/53413761-2dbdc080-39cd-11e9-8a66-39384d2e8cdc.png">

<img width="1194" alt="screen shot 2019-02-26 at 13 45 39" src="https://user-images.githubusercontent.com/16503306/53413768-331b0b00-39cd-11e9-8a39-14a5d3180847.png">

terminal .
![screen shot 2019-02-26 at 13 46 26](https://user-images.githubusercontent.com/16503306/53413782-3dd5a000-39cd-11e9-9293-b751fd313650.png)

### Desired behavior:

justs basically visit the following page https://login.microsoftonline.com/'
### Steps to reproduce: (app code and test code)

```js
cy.visit('https://login.microsoftonline.com/')
```

**Comment by jennifer-shehane** [comment] 2019-02-26 16:26
Hey @amrayoub, I'm seeing a couple of other issues referencing issues with testing `https://login.microsoftonline.com/`
 
- https://github.com/cypress-io/cypress/issues/1342
- https://github.com/cypress-io/cypress/issues/908#issuecomment-380889611

I'll try to take a look across all these.

**Comment by rafenden** [comment] 2020-04-01 12:46
Experiencing the same problem when accessing Django login page `/admin/login/` and using `cypress/included:4.3.0`.

Switching browser to Firefox fixed that problem.

**Comment by mkkhedawat** [comment] 2020-04-13 18:48
Has there been any solution to this?

**Comment by jennifer-shehane** [comment] 2020-08-19 10:05
Duplicate of #1342

**Closed by jennifer-shehane** 2020-08-19 10:05 UTC
Labels: stage: needs investigating
