### ISSUE TITLE
Uncaught TypeError: stack.split is not a function in 5.4.0 and not happening in 3.8.4

### ISSUE THREAD

**Issue by MSIH** [cypress-io/cypress#8872] opened 2020-10-16 20:09 UTC
console error:

```
cypress_runner.js:186969 Uncaught TypeError: stack.split is not a function
    at splitStack (cypress_runner.js:186969)
    at getStackLines (cypress_runner.js:186985)
    at Object.getSourceDetailsForFirstLine (cypress_runner.js:178083)
    at getInvocationDetails (cypress_runner.js:174553)
    at Suite.suite.addTest (cypress_runner.js:174599)
    at Object.createRootTest (cypress_runner.js:174934)
    at Object.normalizeAll (cypress_runner.js:176199)
    at Socket.<anonymous> (cypress_runner.js:200113)
    at Socket.../socket/node_modules/socket.io-client/lib/socket.js.Socket.onack (cypress_runner.js:194508)
    at Socket.../socket/node_modules/socket.io-client/lib/socket.js.Socket.onpacket (cypress_runner.js:194433)
    at Manager.<anonymous> (cypress_runner.js:187597)
    at Manager.../socket/node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:187739)
    at Manager.../socket/node_modules/socket.io-client/lib/manager.js.Manager.ondecoded (cypress_runner.js:193923)
    at Decoder.<anonymous> (cypress_runner.js:187597)
    at Decoder.../socket/node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:187739)
    at Decoder.../socket/node_modules/socket.io-circular-parser/index.js.Decoder.add (cypress_runner.js:192571)
```
### Current behavior
The test gets stuck and never finished. 

### Desired behavior
In version cypress 3.8.3 this function _getCallerFile() returned the filename of the integration js file

### Test code to reproduce
```js
function _getCallerFile(){
  // https://stackoverflow.com/a/19788257/2330272
  try {
      var err = new Error();
      var callerfile;
      var currentfile;

      Error.prepareStackTrace = function (err, stack) { return stack; };

      currentfile = err.stack.shift().getFileName();
      it('currentfile: '+ currentfile);
      while (err.stack.length) {
          callerfile = err.stack.shift().getFileName();

          if (currentfile !== callerfile) return callerfile;
      }
  } catch (err) { }
  return null;
}
const scriptName = _getCallerFile();
```
### Versions
Cypress: 5.40, 
operating system: windows 10 and 2016, 
browser: chrome

**Comment by jennifer-shehane** [comment] 2020-10-18 18:00
Where do you have the code above running in your project?

**Comment by MSIH** [comment] 2020-10-18 19:30
I get the same behavior with the code in the integration test .js file or in the index.js

**Comment by jennifer-shehane** [comment] 2020-10-19 16:19
We do some manipulation to the stack trace behind the scenes (since version 4.3.0 I believe). Can you explain what you're actually needing to achieve here?

**Comment by MSIH** [comment] 2020-10-19 16:34
I am trying to get the filename of the integration test js file. We use the filename to get data from the cypress.json file and test reporting.

**Comment by jennifer-shehane** [comment] 2020-10-21 10:28
You can get this by using `Cypress.spec`: https://on.cypress.io/spec 

Will using this meet your needs?

**Comment by MSIH** [comment] 2020-10-21 11:33
Yes. Thank you

**Comment by jennifer-shehane** [comment] 2021-06-11 17:11
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-06-11 17:11 UTC
Labels: stage: awaiting response
