### ISSUE TITLE
Before Block Doesn't Execute When We Skip The First Test in Spec File

### ISSUE THREAD

**Issue by dillibabuj** [cypress-io/cypress#14748] opened 2021-01-26 12:37 UTC
### Current behavior
I have 'before' block & 'before each' block in my spec file. And if I skip the first test (it.skip) in my spec file., 'before' is not executing. if I remove skip for the first test., then it's fine. 

### Desired behavior
Should execute before block

### Test code to reproduce
[Sample Repo for reproducing](https://github.com/dillibabuj/cypress-skip-bug)

### Versions
Cypress package version: 6.3.0
Cypress binary version: 6.3.0
Electron version: 11.2.0
Bundled Node version:
12.18.3

**Comment by jennifer-shehane** [comment] 2021-01-27 07:48
The `before` hook is executing. You can see the `console.log('Before All Tests`)` in the DevTools in your example. The `before` hook is just not logging in the Test Runner's command log. 

Duplicate of https://github.com/cypress-io/cypress/issues/1846

**Closed by jennifer-shehane** 2021-01-27 07:48 UTC
