### ISSUE TITLE
Assertion after Cypress.Promise results in unhandled exception.

### ISSUE THREAD

**Issue by myAlias** [cypress-io/cypress#25860] opened 2023-02-16 22:22 UTC
### Current behavior

Assertion within .then callback chained from resolved Cypress.Promise results in unhandled exception.

![image](https://user-images.githubusercontent.com/46292323/219499751-38326e85-9c25-4b78-864c-cb1931f0cbcb.png)

```
cypress_runner.js:5038 Unhandled rejection AssertionError: assertion    at fn (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:131613:19)From previous event:    at __stackReplacementMarker (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:150656:13)    at runnable.fn (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:151409:19)    at callFn (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:104964:21)    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:104951:7)    at https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:158438:30From previous event:    at Object.onRunnableRun (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:158421:53)    at $Cypress.action (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:147618:28)    at Runnable.run (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:156377:13)    at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:105623:10)    at https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:105749:12    at next (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:105532:14)    at https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:105542:7    at next (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:105444:14)    at https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:105510:5    at timeslice (https://stg.ecostruxure-energy-one.se.app/__cypress/runner/cypress_runner.js:99436:27)
```

### Desired behavior

Assertion results in test failure without unhandled exception

### Test code to reproduce

Test Code
```js
describe("Investigate Cypress treating assertions as unhandled exceptions that are caught in afterAll hook but test passes.", () => {
  //test fails as expected
  xit("asserts without promise", () => {
    chained().then(() => {
      assert(false, "normal chained assertion");
    });
  });

  //test marked as passed. Unhandled promise rejection that could be missed.
  it("asserts with returned promise", () => {
    resolvedPromise().then(() => {
      assert(false, "resolved Cypress.Promise assertion");
    });
  });
});

const chained = () => {
  return cy.wrap(null);
};

const resolvedPromise = () => {
  return new Cypress.Promise((resolve) => {
    resolve();
  });
};
```

### Cypress Version

10.11.0, 12.6.0

### Node version

16.19

### Operating System

Windows 10, Ubuntu 22.04

**Comment by myAlias** [comment] 2023-02-16 23:29
I see in the docs that rejected test promises do not fail tests, so I removed my  "test being marked as passed instead of failed" comment.
https://docs.cypress.io/api/utilities/promise#Rejected-test-promises-do-not-fail-tests

**Comment by nagash77** [comment] 2023-02-17 19:27
Hi @myAlias , I'm sorry to hear you are having issues using Cypress.  We will have this investigated by our triage team and get back to you.  We have some staff out at the moment so response times may be a bit delayed, please bear with us.

**Comment by flotwig** [comment] 2023-02-22 17:27
@myAlias You need to tell Cypress to wait for the Promise to resolve before finishing the test. Since Cypress is built on Mocha, you can just `return` the Promise:

```ts
  it("asserts with returned promise", () => {
    return resolvedPromise().then(() => {
      assert(false, "resolved Cypress.Promise assertion");
    });
  });
```

If you are also using `cy` chainables in your test, you can use `cy.then` to add your Promise to the chain:

```ts
  it("asserts with returned promise", () => {
    // chain a bunch of cy stuff here, then wait for a promise using cy.then:
    cy.then(() => {
      return resolvedPromise().then(() => {
        assert(false, "resolved Cypress.Promise assertion");
      });
    });
  });
```

More examples: https://docs.cypress.io/api/utilities/promise#Examples

Closing since this is expected behavior.

**Closed as completed by flotwig** 2023-02-22 17:27 UTC
