### ISSUE TITLE
Firefox won't start with version 13.15.2

### ISSUE THREAD

**Issue by brunohgo** [cypress-io/cypress#30636] opened 2024-11-18 10:48 UTC
### Current behavior

Currently the firefox does not start when we click, in version 13.15.1 it worked was normally, I updeted the firefox, but nothing happened.
![not start](https://github.com/user-attachments/assets/ea82834a-ba1d-400d-9db2-8c006fab0974)

### Desired behavior

When we click in firefox it should open the browser.

### Test code to reproduce

1. npx cypress open
2. Select firefox
3. Click and wait
4. Not open the browser
5. To open other browser is necessary close all cypress and open again. 

### Cypress Version

13.15.2

### Node version

16.20.2

### Operating System

Windows

### Debug Logs

```shell
In console no show nothing
```

**Comment by mschile** [comment] 2024-11-18 15:20
Hi @brunohgo, could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by brunohgo** [comment] 2024-11-18 15:55
[cypress-debug-log.txt](https://github.com/user-attachments/files/17803052/cypress-debug-log.txt)


Ok, Does it help ?

**Comment by AtofStryker** [comment] 2024-11-18 17:02
> [cypress-debug-log.txt](https://github.com/user-attachments/files/17803052/cypress-debug-log.txt)
> 
> Ok, Does it help ?

@brunohgo could you try `DEBUG=cypress:server:browsers*,cypress-verbose:server:browsers*` and send us those logs? It looks like firefox is trying to start but is getting stuck somehow.

**Comment by brunohgo** [comment] 2024-11-18 17:21
> > [cypress-debug-log.txt](https://github.com/user-attachments/files/17803052/cypress-debug-log.txt)
> > Ok, Does it help ?
> 
> @brunohgo could you try `DEBUG=cypress:server:browsers*,cypress-verbose:server:browsers*` and send us those logs? It looks like firefox is trying to start but is getting stuck somehow.

[cypress-noverbose_log.txt](https://github.com/user-attachments/files/17804046/cypress-noverbose_log.txt)
[cypress-verbose_log.txt](https://github.com/user-attachments/files/17804047/cypress-verbose_log.txt)

**Comment by AtofStryker** [comment] 2024-11-18 19:47
> > > [cypress-debug-log.txt](https://github.com/user-attachments/files/17803052/cypress-debug-log.txt)
> > > Ok, Does it help ?
> > 
> > 
> > @brunohgo could you try `DEBUG=cypress:server:browsers*,cypress-verbose:server:browsers*` and send us those logs? It looks like firefox is trying to start but is getting stuck somehow.
> 
> [cypress-noverbose_log.txt](https://github.com/user-attachments/files/17804046/cypress-noverbose_log.txt) [cypress-verbose_log.txt](https://github.com/user-attachments/files/17804047/cypress-verbose_log.txt)

It looks like the logs are cut off? The verbose logs should have quite a lot of content as it is printing all the commands from geckodriver/webdriver

**Comment by brunohgo** [comment] 2024-11-18 20:34
> > > > [cypress-debug-log.txt](https://github.com/user-attachments/files/17803052/cypress-debug-log.txt)
> 
> > > > Ok, Does it help ?
> 
> > > 
> 
> > > 
> 
> > > @brunohgo could you try `DEBUG=cypress:server:browsers*,cypress-verbose:server:browsers*` and send us those logs? It looks like firefox is trying to start but is getting stuck somehow.
> 
> > 
> 
> > [cypress-noverbose_log.txt](https://github.com/user-attachments/files/17804046/cypress-noverbose_log.txt) [cypress-verbose_log.txt](https://github.com/user-attachments/files/17804047/cypress-verbose_log.txt)
> 
> 
> 
> It looks like the logs are cut off? The verbose logs should have quite a lot of content as it is printing all the commands from geckodriver/webdriver


I didn't look for completely, but, Yes, it's cutting. Sorry

**Comment by AtofStryker** [comment] 2024-11-18 22:11
> > > > > [cypress-debug-log.txt](https://github.com/user-attachments/files/17803052/cypress-debug-log.txt)
> > 
> > 
> > > > > Ok, Does it help ?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @brunohgo could you try `DEBUG=cypress:server:browsers*,cypress-verbose:server:browsers*` and send us those logs? It looks like firefox is trying to start but is getting stuck somehow.
> > 
> > 
> > > 
> > 
> > 
> > > [cypress-noverbose_log.txt](https://github.com/user-attachments/files/17804046/cypress-noverbose_log.txt) [cypress-verbose_log.txt](https://github.com/user-attachments/files/17804047/cypress-verbose_log.txt)
> > 
> > 
> > It looks like the logs are cut off? The verbose logs should have quite a lot of content as it is printing all the commands from geckodriver/webdriver
> 
> I didn't look for completely, but, Yes, it's cutting. Sorry

Are you able to send the full log? It's going to be difficult for me to tell what is happening without it

**Comment by brunohgo** [comment] 2024-11-19 09:16
I think it's complete.
[cypress_log_full.txt](https://github.com/user-attachments/files/17812609/cypress_log_full.txt)

**Comment by AtofStryker** [comment] 2024-11-19 15:22
> I think it's complete. [cypress_log_full.txt](https://github.com/user-attachments/files/17812609/cypress_log_full.txt)

Thank you for sending that over! There isn't anything that is standing out to me, except that your node version in use is very old. A lot of these packages require at least node 18 to work and Cypress only works with node 18. Would you be able to try node 20 and see if it launches?

**Comment by brunohgo** [comment] 2024-11-19 16:32
> > I think it's complete. [cypress_log_full.txt](https://github.com/user-attachments/files/17812609/cypress_log_full.txt)
> 
> Thank you for sending that over! There isn't anything that is standing out to me, except that your node version in use is very old. A lot of these packages require at least node 18 to work and Cypress only works with node 18. Would you be able to try node 20 and see if it launches?

I can't, my company works with angular 14 so the node must be on version 16.

I found it strange, in version 13.15.1 it worked normally

**Comment by alexsch01** [comment] 2024-11-19 16:48
I thought that Cypress 14 would be the first to actually drop NodeJS 16 support

Cypress 13.15.2 includes this now https://github.com/salesforce/tough-cookie/releases/tag/v5.0.0 which I think would break NodeJS 16 support

EDIT: ahh nevermind
```Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress v13, but will not be supported moving forward to closer coincide with [Node 16's end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) schedule. It is recommended that users update to at least Node 18.```

**Comment by AtofStryker** [comment] 2024-11-19 18:54
> Cypress 13.15.2 includes this now https://github.com/salesforce/tough-cookie/releases/tag/v5.0.0 which I think would break NodeJS 16 support

I bet that is the cause, considering Firefox is working for you @brunohgo in `13.15.1`, which contained a lot of the work to use `geckodriver` and `webdriver` to automate Firefox. I don't think there is too much we can do to help since we do not support Node 16. As a heads up, we will also be dropping support for Angular 14 in Cypress 14 and will only be supporting Angular `17.2.0` and up to align with Angular's [LTS schedule](https://angular.dev/reference/releases#support-window). I would highly encourage you to update Angular and Node to stay up to date with support/releases when you are soonest able.

Since you are unable to verify with Node 18+, I am unfortunately going to have to close the issue. But if you do update and the issue persists, please comment or open another issue and we will investigate!

**Closed as completed by AtofStryker** 2024-11-19 18:54 UTC
