### ISSUE TITLE
Env Variable doesn't reflect updated value

### ISSUE THREAD

**Issue by Harleylee96** [cypress-io/cypress#5956] opened 2019-12-13 16:06 UTC
### Current behavior:

Trying to update a global variable by invoking text values from a notification bar. The text values are invoked properly and used to update the env variable within the invoking function. However, outside the function, it prints the previous value.

For e.g. if I had the env variable set to 1 initially,
I update the env value to 2 within the function, and outside the function, it'd still say 1.

### Desired behavior:

Updated values should be synchronized. When I update it to 2, it should print out 2 outside the invoking function.

### Steps to reproduce: (app code and test code)

in cypress.env.json:

```json
{
    "env": {
        "intakeID": ""
    }
}
```

in my testfile.spec.js:
```js
    cy.get('.MuiSnackbar-root > .MuiTypography-root')
        .invoke('text')
        .then((newIntakeID) => {
            const id = String(newIntakeID)
            Cypress.env('intakeID', id.substring(id.length - 5))
            cy.log('intakeID: ' + Cypress.env('intakeID'))
        })

    cy.log('intakeID outisde: ' + Cypress.env('intakeID'))
    })
```

And it shows in the test runner:
![image](https://user-images.githubusercontent.com/51380689/70813568-ad1f5380-1d97-11ea-9796-781b22786f05.png)

### Versions
React.js
"cypress": "3.4.1"

**Comment by jennifer-shehane** [comment] 2019-12-16 03:22
This has something to do with the async running of the commands, although I feel like this result if unexpected to me. The result of the code below:

```js
it('should set ENV var string', () => {
  cy.wrap('3').then((newStringID) => {
    Cypress.env('stringID', newStringID)
    cy.log(`stringID inside: ${Cypress.env('stringID')}`)
  })

  cy.log(`stringID outside: ${Cypress.env('stringID')}`) // is wrong
})

it('should set ENV var num', () => {
  cy.wrap(3).then((newNumID) => {
    Cypress.env('numID', newNumID)
    cy.log(`numID inside: ${Cypress.env('numID')}`)
  }).then(() => {
    cy.log(`numID outside: ${Cypress.env('numID')}`) // is correct
  })
})
```

<img width="449" alt="Screen Shot 2019-12-16 at 9 50 02 AM" src="https://user-images.githubusercontent.com/1271364/70876804-76d91280-1fe9-11ea-84c8-477fe9c0d6e0.png">

Also - if I rerun the tests, the previous assigned value seems to persist through sessions when it shouldn't, so if I simply 'rerun' the test above, now it prints different values.

<img width="446" alt="Screen Shot 2019-12-16 at 9 51 44 AM" src="https://user-images.githubusercontent.com/1271364/70876871-b7389080-1fe9-11ea-9ee5-0726c0cc5989.png">

**Comment by Harleylee96** [comment] 2019-12-16 14:26
Yes for your result, because your number is static, not dynamic, you'd get 3 after rerunning it. If you randomize the number, you'll realize that updating the environment variable is a step behind. 

For example, now you have set up the env variable to 3, if you change it to updating it to 4 this time, and rerun it, you'll see that the env variable's value is 3 - because it reflects one older version of the value. Please randomize the value and retry.

**Comment by Harleylee96** [comment] 2019-12-17 16:28
Hi I tried to converting a string to a number and reran the code - still yielding the unexpected behaviour:

`    cy.get('.MuiSnackbar-root > .MuiTypography-root')
        // .should('contain', 'Process updated successfully.')
        .invoke('text')
        .then((newIntakeID) => {
            const id = String(newIntakeID)
            const num = Number(id.substring(id.length - 5))
            Cypress.env('intakeID', num)
            cy.log('intakeID: ' + Cypress.env('intakeID'))
        })

    cy.log('intakeID outisde: ' + Cypress.env('intakeID'))
    })
`

![image](https://user-images.githubusercontent.com/51380689/71014700-5c259d00-20c0-11ea-8ddf-1f4d79b52c52.png)

**Comment by jennifer-shehane** [comment] 2019-12-19 17:24
As I explained above, this is because of the asynchronous code. the `Cypress.env('intakeId')` is being stringified as soon as `cy.log() is read, which is before the `cy.log() inside of the .then is read. You'll need to nest the second `cy.log()` within a `then()` and evaluate it inside of there to get the correct reading.

Closing as this is expected behavior.

**Closed by jennifer-shehane** 2019-12-19 17:24 UTC
Labels: stage: needs investigating, type: bug, type: unexpected behavior

**Comment by jennifer-shehane** [comment] 2019-12-19 17:30
New issue for resetting state https://github.com/cypress-io/cypress/issues/6010
