### ISSUE TITLE
Texts rendering problems with Chrome

### ISSUE THREAD

**Issue by sergiop** [cypress-io/cypress#2005] opened 2018-06-21 14:24 UTC
### Current behavior:
For a few days I have some problems with Cypress/Chrome. All texts disappears. All work properly, but Chrome has some problem rendering texts, inside developer tools too.
I have no problem with the normal instance of Chrome.
![schermata 2018-06-21 alle 16 14 50](https://user-images.githubusercontent.com/2235134/41725022-20fb045c-756f-11e8-94ac-8203bd733417.png)

Any ideas to solve?

### Versions
Cypress 3.0.1 (but it happened also with previous versions)
macOS 10.13.5
Google Chrome 67.0.3396.87 (64 bit)

**Comment by chrisbreiding** [comment] 2018-06-21 15:02
Duplicate of https://github.com/cypress-io/cypress/issues/1617

**Closed by chrisbreiding** 2018-06-21 15:02 UTC

**Comment by brian-mann** [comment] 2018-06-21 15:18
@sergiop per my comment on the other duplicate issues -

https://github.com/cypress-io/cypress/issues/1994#issuecomment-398916221

Can you do us a favor and remove the flags that we pass to chrome until this no longer breaks? Since it works in normal Chrome but not in Cypress I am 100% sure it's related to a flag we pass. However, none of us can reproduce and we need help reproducing what is causing this problem.

**Comment by sergiop** [comment] 2018-06-21 16:43
Of course, I'll gladly help you with some debugging. I solved adding `--disable-gpu` flag, as you told here https://github.com/cypress-io/cypress/issues/1617#issuecomment-397373555. What can I do more?

**Comment by brian-mann** [comment] 2018-06-21 19:23
@sergiop that's how you solve the problem - but because that flag is not needed when you "normally use Chrome" its just hiding the **real** problem.

The real problem is that some flag that we pass to Chrome is causing it to enter into this rendering mode. I don't know what it is. 

It would be great if you can remove the flags that we pass into chrome one by one until it "works".

You can remove the flags by tapping into the `before:browser:launch` event and then rejecting the `args` from the array until one passes.

**Comment by sergiop** [comment] 2018-06-22 08:47
Hi @brian-mann, as you asked me I removed one by one all the flags but I had no success. :-(
None of that apparently cause the issue.

I used this:
```es6
if (browser.name === 'chrome') {
  const index = args.indexOf('--disable-default-apps');
  if (index > -1) {
    args.splice(index, 1);
  }

  return args
}
```

And this is what I get from args var:
```es6
args = ['--test-type', '--ignore-certificate-errors', '--start-maximized', '--silent-debugger-extension-api', '--no-default-browser-check', '--no-first-run', '--noerrdialogs', '--enable-fixed-layout', '--disable-popup-blocking', '--disable-password-generation', '--disable-save-password-bubble', '--disable-single-click-autofill', '--disable-prompt-on-repos', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-renderer-throttling', '--disable-restore-session-state', '--disable-translate', '--disable-new-profile-management', '--disable-new-avatar-menu', '--allow-insecure-localhost', '--reduce-security-for-testing', '--enable-automation', '--disable-infobars', '--disable-device-discovery-notifications', '--disable-blink-features=RootLayerScrolling', '--metrics-recording-only', '--disable-prompt-on-repost', '--disable-hang-monitor', '--disable-sync', '--disable-web-resources', '--safebrowsing-disable-auto-update', '--safebrowsing-disable-download-protection', '--disable-client-side-phishing-detection', '--disable-component-update', '--disable-default-apps', '--proxy-server=http://localhost:55204']
```

**One final note:** removing all the flags at the same time, still returns me the same error.
```es6
if (browser.name === 'chrome') {
  args = []
  return args
}
```
![schermata 2018-06-22 alle 10 15 09](https://user-images.githubusercontent.com/2235134/41767243-67a42452-7609-11e8-9200-4bd99c443c85.png)

**Comment by antonmyrberg** [comment] 2018-08-07 13:10
Just getting started checking in Cypress, which looks great. Unfortunately, I've run into the same problem as @sergiop. My regular Chrome works as expected, but Cypress just renders color blocks with text in the same color. So the testing works, but the rendering breaks. If I copy the text and pastes it somewhere else I get the correct messages from Cypress.

See image: 
<img width="1201" alt="cypress_screenshot" src="https://user-images.githubusercontent.com/29479737/43776396-054115f2-9a50-11e8-801b-fa4d8e7a9775.png">

Let me know if I can do anything to help.
