### ISSUE TITLE
Rerun selected test

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#17516] opened 2021-07-29 07:19 UTC
### What would you like?

During debugging, when I ran group of tests in Cypress window and some of tests fail, I would like to rerun only failed ones, while keeping results of  ones ended with success. Currently I can only rerun whole group by clicking Run All Tests button.

### Why is this needed?

To safe time of tests execution.

**Comment by jennifer-shehane** [comment] 2021-07-29 13:34
Duplicate of https://github.com/cypress-io/cypress/issues/4886

**Closed by jennifer-shehane** 2021-07-29 13:34 UTC
