### ISSUE TITLE
Unable to Type in "number" input field in Chromium

### ISSUE THREAD

**Issue by pocketcolin** [cypress-io/cypress#4694] opened 2019-07-10 19:09 UTC
### Current behavior:

When running Chromium 57 with Cypress 3.4.0, Cypress is unable to type in an input field with `type="number"` and immediately fails with the error: `InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.`

![Error Screenshot](https://github.com/pocketcolin/cypress-test-tiny/blob/number_input_field_issue/error.png?raw=true)

It is possible to use the `clear()` method on a number field. Typing *does* work in Chrome 75.

### Desired behavior:

Ability to use the `.type()` method on input fields with `type="number"` as mentioned in the `type` docs: https://docs.cypress.io/api/commands/type.html#Supported-Elements

### Steps to reproduce: (app code and test code)

Clone this repo and run the 1 spec (named, "editing number input field") in Chromium 57:
https://github.com/pocketcolin/cypress-test-tiny/tree/number_input_field_issue

Simple Test html file, `test.html`:
```html
<input type="number" value="5" class="number-input" />
```

Cypress test that fails:
```js
describe('page', () => {
  it('editing number input field', () => {
    cy.visit('/test.html')
    cy.get('input').clear().type(5)
  })
})
```

Error:
```
InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.
```

### Versions

Cypress: 3.4.0
Browser: Chromium 57
OS: MacOS 10.14.5

**Comment by anorudes** [comment] 2019-12-09 08:59
Yes, I have the same problem. I tried to find any solution/. This seems to be a bug in cypress/ Updating packages didn't help.

**Comment by jennifer-shehane** [comment] 2020-01-02 08:06
I was unable to recreate this from the example provided. Tried Chrome 78. Chromium 57 is quite old, so that is not something Cypress is supporting.

Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? Your issue may have already been fixed as we did a lot of updates to typing.

**Comment by pocketcolin** [comment] 2020-01-06 21:26
@jennifer-shehane I was only able to create this bug in Chromium 57 back when that was the default version of Chromium packaged with Cypress way back in July of last year. Since that version isn't the default anymore, this issue can probably be closed. I doubt it is the same issue @anorudes is having as the `.type()` method worked fine for me in Chrome 75 as I mentioned in my original post, but I haven't tested with Chrome 78.

**Comment by jennifer-shehane** [comment] 2020-02-04 07:44
Closing as resolved. Please open a new issue with a reproducible example if you are experiencing an issue similar to this thread.

**Closed by jennifer-shehane** 2020-02-04 07:44 UTC
Labels: browser: chromium, stage: awaiting response
