### ISSUE TITLE
Don't retry `its()` command when passed an alias object from `cy.wait()`

### ISSUE THREAD

**Issue by jakub-bao** [cypress-io/cypress#7120] opened 2020-04-23 14:11 UTC
Hi, daily cypress user here again. I noticed this behavior.

### Current behavior:

I started stubbing my server requests to make stuff faster. The following way:

```js
function stubRequest(){
    cy.server();
    cy.route({
        method: 'PUT',
        url: '/api/users/Fvgq5e8jzl8.json',
        response: 'fixture:editUser.response.json'
    }).as('saveUser');
}

function inspectRequest(){
    cy.wait('@saveUser').its('request.body').should('deep.equal', editUserRequest);
}
```

Basically my REACT app edits a user and then I click save and send the result back to the server.

However, cypress interjects and inspects the outgoing request:
`.its('request.body').should('deep.equal', editUserRequest);`

Well I noticed that cypress is `waiting`:

![image](https://user-images.githubusercontent.com/47790868/80108674-8a255d00-854a-11ea-8322-3b3be4245877.png)

### Desired behavior:

Why Is cypress waiting?

The desired request is known. The fired request is known.
They won't change. No need to wait.
It would make my tests faster if cypress would remove wait times by default in this context.
I can do it manually.

### Test code to reproduce

Look for code above.

### Versions
cypress 4.3.0

**Comment by jennifer-shehane** [comment] 2020-04-28 08:19
This is the default behavior of the `its()` command as explained here: https://on.cypress.io/its#Assertions

We don't really intelligently look at what you passed to `its()`, so it's assumed that the state could change (which is the case for objects on the application for example). 

We could be smarter about this when the `its` is being passed an alias from a `cy.wait()` command.

### Workaround

You can get around this by setting a very low `timeout` option within the `its()` when you know the object it's asserting on cannot change after it exists. 

```js
cy.wait('@saveUser').its('request.body', { timeout: 0 }).should('deep.equal', editUserRequest);
```

It doesn't look like this `timeout` option is documented for `its()` so I'll need to update the docs for that. 

### Reproducible Example

```js
it('test', () => {
  cy.visit('http://example.cypress.io/commands/network-requests')
  cy.server()
  cy.route('GET', 'comments/*').as('getComment')
  cy.get('.network-btn').click()
  cy.wait('@getComment').its('status').should('eq', 404)
})
```

![](http://g.recordit.co/YEuDi3vbkd.gif)

**Comment by jennifer-shehane** [comment] 2023-12-15 04:13
Closing since this hasn’t gotten a lot of interest over the years.

**Closed by jennifer-shehane** 2023-12-15 04:13 UTC
Labels: type: enhancement, stage: ready for work
