### ISSUE TITLE
View All Tests button on Cypress Runner Does not work in Cypress 4.1.0

### ISSUE THREAD

**Issue by abhidp** [cypress-io/cypress#6673] opened 2020-03-08 04:40 UTC
### Current behavior:

In the Cypress test runner browser window for `v4.1.0` the  `View All Tests` option does not navigate back to the Cypress runner window 
![AllTests](https://user-images.githubusercontent.com/30851622/76156699-2e497500-6152-11ea-997f-4a424a9a082f.gif)

### Desired behavior:

This is a gif of `v3.6.1`. Clicking on the `View All Tests` option reveals the Cypress runner window.
The same behaviour should also be exhibited in `v4`
![testRunnerWorking](https://user-images.githubusercontent.com/30851622/76156748-e2e39680-6152-11ea-845b-966a78bd6c81.gif)

### Versions

Cypress: 
``` json
"devDependencies": {
    "cypress": "^4.1.0"
 }
```
OS:
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
```
Browser:
```
Google Chrome is up to date
Version 80.0.3987.132 (Official Build) (64-bit)
```

**Comment by jennifer-shehane** [comment] 2020-03-09 15:28
Duplicate of #5948

**Closed by jennifer-shehane** 2020-03-09 15:28 UTC
