### ISSUE TITLE
After logon to sales force using cypress script the runner pane just disappears

### ISSUE THREAD

**Issue by muralinaidud** [cypress-io/cypress#22453] opened 2022-06-22 14:18 UTC
### Current behavior

After logon to sales force the runner pane just disappears

### Desired behavior

Runner pane should not disappear

Should be able to run the complete test

### Test code to reproduce

           it("should sales force page is open", () => {

                            cy.visit("https://***-digital--fpqa.my.salesforce.com/")
                            cy.get('#username').type('murali.naidu@******')
                            cy.get('#password').type('*****')
                            cy.get('#Login').click()
                            cy.wait(1000)
                            cy.url().should('include','sSSA')
                          

                        })

### Cypress Version

10.2.0

**Comment by mjhenkes** [comment] 2022-06-23 13:34
Closing as duplicate of #2367

**Closed by mjhenkes** 2022-06-23 13:34 UTC
Labels: stage: investigating

**Comment by muralinaidud** [comment] 2022-06-23 14:28
Hi @mjhenkes why did you close this defect ?

This is not a duplicate, #2367 is related to logon issue with cypress into Sales Force application

But my issue is, cypress runner pane is disappearing after logging on to sales force using cypress script

**Comment by mjadrianf** [comment] 2022-08-17 21:25
Yes, the issues is not the same. I have the same issue when I try to run the test case, when the origin url is open, the pane of debuggin disapear.
Please can you investigate an reopen the issue!
Is a behavior with cypress 10.X

**Comment by ShashidharSM** [comment] 2022-08-18 04:04
Agree - this is not the same issue as #2367. While I am able to login using the workarounds suggested in #2367, the debugging/testrunner pane on the left closes as soon as the Lightning components of Salesforce load up. This renders Cypress unusable for testing Salesforce applications.

**Comment by ShashidharSM** [comment] 2022-08-18 04:06
@muralinaidud and @mjadrianf Were you able to get this working by some other means?

**Comment by mjadrianf** [comment] 2022-08-18 18:27
No, I can' to resolve this issue..is stuck me!

**Comment by muralinaidud** [comment] 2022-08-22 11:39
no this is still not working @mjhenkes lot of people are struggling with this issue and you keep closing it without giving us roper resolution ?

**Comment by lucascruz9494** [comment] 2022-08-24 22:19
I had the same problem as almost everyone I think...
What I think I discovered is that the problem of the left panel disappearing occurs when you are redirected to this link "https://yourWorkPlaceUrl.lightning.force.com/one/one.app" 
(you have to replace yourWorkPlaceUrl , obviously)

So what I have 2 work arounds : 
1 - If you can login by cy.request() or something like this to bypass the "manual" login, you do that and visit the url I mentioned before
2 - If you can't bypass the login it is going to be a really bad work around but you need to create one test one only for the manual login so the cypress can preserve cookies , localStorage, or anything that needs to keep you logged...
Once you are logged you can close the test, rename it with "it.skip" so it won't try to log you again and then you can visit the url I mentioned before on the other tests...
