### ISSUE TITLE
Support Next.js version 15 for Cypress Component Testing

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#30501] opened 2024-10-30 22:36 UTC
### What would you like?

Next.js 15 released about a week ago. To keep up to date with framework support, Cypress should add support for next.js 15

**Comment by MikeMcC399** [comment] 2024-10-31 11:18
@AtofStryker 

- This is a duplicate of https://github.com/cypress-io/cypress/issues/30445

**Comment by jennifer-shehane** [comment] 2024-10-31 16:48
Closing as duplicate of https://github.com/cypress-io/cypress/issues/30445

**Closed as completed by jennifer-shehane** 2024-10-31 16:48 UTC
Labels: type: duplicate
