### ISSUE TITLE
Markers for tagging tests

### ISSUE THREAD

**Issue by toshikagarwal** [cypress-io/cypress#21581] opened 2022-05-20 07:30 UTC
### What would you like?

Markers to be able to tag tests so that they could be grouped into categories.
This will be useful to be able to categorise tests like "sanity" "regression" etc across various spec files and be able to trigger them based on run time parameters

### Why is this needed?

It is needed for testing when you would like the tests to be categorised and triggered for some short, quick runs

**Comment by flotwig** [comment] 2022-05-24 17:22
Hi @toshikagarwal, this functionality can be accomplished by using the `cypress-grep` plugin: https://github.com/cypress-io/cypress-grep

There is also a feature request to add this in core: #1865

Closing as duplicate of #1865

**Closed by flotwig** 2022-05-24 17:22 UTC
Labels: type: enhancement, stage: investigating
