### ISSUE TITLE
Possibility to intercept API calls without wait for new page to load

### ISSUE THREAD

**Issue by szanelato** [cypress-io/cypress#16062] opened 2021-04-19 12:27 UTC
I think this behavior could be improved in Cypress: 

When an interception is made to obtain the response from a API Cypress is waiting for a new page to load after the `cy.wait()` and the code block of the assertions.

I followed the example at Cypress documentation about how to wait and intercept a response using a Alias: https://docs.cypress.io/api/commands/wait#Alias

So I made this code for my test scenario:

```js
verifyLoginSuccess () {
    cy.intercept('https://api.security.service.com/authenticate').as('postAuthenticate');
    cy.wait ('@ postAuthenticate'). then (interception => {
         expect (interception.response.statusCode) .equal (200);
         expect (interception.response.body.dest) .equal ('https://destinationurl.com');
     })
} 
```

So with this function I was expecting that my tests get passed after validate the statusCode and the specific property called "dest" inside response body. But Cypress is forcing me to wait for new page to load. 
In this case that page isn't work because in login scenarios is common send the user to a logged area and I want to test only until the redirection and ignore the page load.

Do you guys think that could be a feature for Cypress or I haven't found it but is there a way to do it?

**Comment by jennifer-shehane** [comment] 2021-04-21 20:34
It's waiting for a new page load because the page has redirected to a new page?

Looks like a duplicate of https://github.com/cypress-io/cypress/issues/788 which...is mostly concerned with `visit` rather than redirects though. 

May also be more closely related to https://github.com/cypress-io/cypress/issues/7083 which would allow you to 'stop' the page loading. 

Neither of these functionalities exist currently though, so there isn't a workaround atm.

**Closed by jennifer-shehane** 2021-04-21 20:34 UTC

**Comment by szanelato** [comment] 2021-04-22 14:29
@jennifer-shehane thanks for you feedback.

I'm testing a login web page so I start the test visiting my login page and after some actions my tests get a redirection for a new page.

In my case the decision of what page the users have to be redirected is provided by a API service. I was expecting that Cypress will provide me a way to intercept this API response without wait for the new pages be fully loaded. I'm currently do the response interception with success.

So it is a huge block for my test suite inside my CI/CD tools.

I saw your suggestion of a workaround here [#7083 comment](https://github.com/cypress-io/cypress/issues/7083#issuecomment-618921445) but how it's not prevent Cypress to wait for page load so it will not improve my situation here.

What can I do? It isn't a possible feature for Cypress just provide a way for do not wait for page load if you are performing a service interception?

**Comment by tina-zeng** [comment] 2022-12-06 03:13
> @jennifer-shehane thanks for you feedback.
> 
> I'm testing a login web page so I start the test visiting my login page and after some actions my tests get a redirection for a new page (this is commonly known as transition to logged area).
> 
> In my case the decision of what page the users have to be redirected is provided by a API service. I was expecting that Cypress will provide me a way to intercept this API response without wait for the new pages be fully loaded. I'm currently do the response interception with success.
> 
> So it is a huge block for my test suite inside my CI/CD tools.
> 
> So I understanding that the correction can be followed by the issue [#7083](https://github.com/cypress-io/cypress/issues/7083). We have some expectation about when it will be corrected?

Is your problem solved?
