### ISSUE TITLE
Inability to determine reason for invisibility

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#5974] opened 2019-12-16 17:11 UTC
### Current behavior:

[Per v3.8.0](https://github.com/cypress-io/cypress/blob/v3.8.0/packages/driver/src/dom/visibility.js#L524), one might receive a message stating EG. `Cypress could not determine why this element '<button>' is not visible.`

This is non-sensical, as there's obviously some heuristic implemented that has determined the element to be invisible.

I understand that there's a method `getReasonIsHidden` that is somewhat replicating the behavior of `isHidden`, but returning a human-readable string instead of a boolean value. I am however having a very hard time understanding why you would implement it like this.

Since there should be one, and only one, heuristic-implemention, why not make one a function of the other?

```js
const getReasonIsHidden = function ($el) {
  // Implementation ...
}

const isHidden = ($el) => {
  return !!getReasonIsHidden($el);
}
```

### Desired behavior:

Never to see such a non-informative error message.

### Steps to reproduce: (app code and test code)

Doesn't really matter here, but I can see if I can produce a minimal example.

### Versions

Cypress v3.8.0, Arch Linux, Chrome 77.

**Comment by jennifer-shehane** [comment] 2019-12-17 08:58
I agree, this is pretty awful. I wrote this code as a catchall if a specific error message was not written for a hidden check.  https://github.com/cypress-io/cypress/pull/4421

This is complicated by the fact that the `isHidden` function is separate (returning a boolean) from the `getReasonIsHidden` (returning a string) function which is not ideal.

Giving a repro would actually be really helpful because there must be a case we are checking but not printing a message for.

The one thing I do suspect is this check because I can't find a corresponding error message for it. It's 

- https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/visibility.js#L356:L356

**Comment by badeball** [comment] 2019-12-17 11:55
I figured out why. One of the ancestors has a CSS property `transform: translate(0px, 0px)` * and a height of 0. It does not however have `overflow: hidden`, hence its children are visible, but determined by Cypress to be invisible (by `elIsHiddenByAncestors`, which recursively calls `elIsHiddenByTransform`). The method `getReasonIsHidden` invokes `elIsHiddenByTransform`, but not `elIsHiddenByAncestors`, hence the indeterminate error message.

\* I know this is a completely non-sensical attribute for someone to give to an element. This is done by Google Maps.

**Comment by jennifer-shehane** [comment] 2019-12-17 14:59
@badeball K, thanks for looking into this. I'll have to try to set up a test for this situation.

**Comment by jennifer-shehane** [comment] 2019-12-18 07:08
Got a repro and also verified this is a regression introduced in 3.8.0, likely from this PR https://github.com/cypress-io/cypress/issues/723. So this is actually incorrectly failing the visibility check also.

`index.thml`

```html
<!DOCTYPE html>
<html>
<body>
  <div style="transform: translate(0, 0); height: 0;">
    <p>Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
</body>
</html>
```

`spec.js`

```js
it('types', function () {
  cy.visit('index.html')
  cy.get('p').should('be.visible')
})
```

## 3.7.0

<img width="728" alt="Screen Shot 2019-12-18 at 1 37 30 PM" src="https://user-images.githubusercontent.com/1271364/71063663-8f892a00-219b-11ea-831c-45cfdc62f3c0.png">


## 3.8.0

<img width="704" alt="Screen Shot 2019-12-18 at 1 34 44 PM" src="https://user-images.githubusercontent.com/1271364/71063500-2f928380-219b-11ea-8f42-46fbec52ebf7.png">

**Comment by sainthkh** [comment] 2019-12-18 07:26
@jennifer-shehane Ill check it out.

**Comment by badeball** [comment] 2019-12-18 09:14
This is undoubtedly a very interesting case, along with the whole problem of programmatically determining visibility. You obviously made a great deal of effort here, which I am wholeheartedly appreciative of.

However, I'd like to emphasize that what I originally wanted to address was the disconnect between reasoning and actual determination.

As long as the two methods `isHidden` & `getReasonIsHidden` implements their own heuristics, there will *always* be a possibility for the last, indeterminate message to be returned.

This message is non-sensical at the very core. Cypress does determine visibility and I believe it should always be able to tell you why in case it determined something to be invisible.

**Comment by badeball** [comment] 2019-12-18 09:18
Here's an example of what I mean by sharing heuristic, without changing the current interface.

```js
function determineVisibility ($el) {
  if ( /* some condition */ ) {
    return {
      visible: false,
      reason: "foobar"
    };
  }

  return {
    visible: true
  };
}

export function isHidden ($el) {
  return !determineVisibility($el).visible;
}

export function getReasonIsHidden ($el) {
  const visibility = determineVisibility($el);

  if (visibility.visible) {
    throw new Error("Erroneously invoked on a visible element");
  }

  return visibility.reason;
}
```

**Comment by jennifer-shehane** [comment] 2019-12-19 07:55
@sainthkh I also ran this, without a parent, where the `<p>` is still visible and it falsely fails. 

```html
<!DOCTYPE html>
<html>
<body>
  <p style="transform: translate(0, 0); height: 0;">
   Aenean lacinia bibendum nulla sed consectetur.
  </p>
</body>
</html>
```

**Comment by sainthkh** [comment] 2019-12-19 08:38
@jennifer-shehane 

![Screenshot from 2019-12-19 17-16-58](https://user-images.githubusercontent.com/8130013/71156526-807da700-2283-11ea-98fb-7fdf21ccd60c.png)

As you can see in the screenshot, "without-a-parent" problem is not the problem of the #6000. It's the problem of effective width or height. It's not regression. 

It's been fixed by checking the value of effective width/height and transform value together.

**Comment by sainthkh** [comment] 2019-12-27 06:22
@badeball I realized that your idea can be used to fix #677, too.

But I cannot implement your idea now because #5916 and #6000 are not merged yet. After they're done. 

I'll revisit this issue.

**Comment by janakdr** [comment] 2020-01-14 18:28
@sainthkh it looks like the PRs you mentioned are merged now. Is this issue fixed, or is there still more work to do? We're blocked on upgrading Cypress to >= 3.8 due to this issue. Thanks!

**Comment by sainthkh** [comment] 2020-01-15 00:13
@janakdr I've been spending time on #5762. And it is finished my part and waiting for feedback. 

If your problem is the test falsely failing, then it is solved in #6000. Please try 3.8.2. 

But your idea about creating a visibility result object to determine the reason, it is not started yet. 

Currently, I'm trying to make #619 and planning to fix that with #677.

**Comment by janakdr** [comment] 2020-01-15 06:12
Thanks, the failing test was our issue, and 3.8.2 does fix it!

**Comment by jennifer-shehane** [comment] 2020-07-07 07:53
This was fixed in https://github.com/cypress-io/cypress/pull/6000 in 3.8.2 of Cypress. Closing as resolved.

**Closed by jennifer-shehane** 2020-07-07 07:53 UTC
Labels: pkg/driver, stage: ready for work, type: regression, type: user experience, v3.8.0 :bug:

**Comment by badeball** [comment] 2020-08-03 17:47
I hate to be the stickler here, but this issue was equally much about the fact that the reason for determining invisibility was unavailable. As far as I can see, there's still two different methods of determining invisibility and for explaining why an element is invisible. This means that this can still become an issue again and therefore it will.

**Comment by jennifer-shehane** [comment] 2020-08-04 06:38
Yah, there's a larger issue to evaluate our error messages - showing why something is invisible or visible here: https://github.com/cypress-io/cypress/issues/677 

As far as I have seen, there aren't any open issues of a situation where the ambiguous error 'could not determine why' is showing for anyone in the current version.
