### ISSUE TITLE
Basic Auth not working

### ISSUE THREAD

**Issue by alycda** [cypress-io/cypress#232] opened 2016-09-20 19:13 UTC
I have basic auth credentials in my `cypress.json` file, something like:

``` json
{
  "projectId": "ksjdsjfs-dfksjdf-sdjfsll-fdlkf",
  "baseUrl": "http://username:password@host.com"
}
```

But when I run tests, I still get a prompt. If I enter credentials manually, I am only prompted once until the browser is re-opened, so I can run tests with this work-around but it is not ideal.

**Comment by brian-mann** [comment] 2016-10-04 23:23
I cannot reproduce. 

I put together a small example project which uses `basic auth`. This code passes for me.

I cannot even figure out how you are even getting the browser's challenge window, because when sending back a `401` status code on a `cy.visit` the visit will immediately fail.

What version of Cypress are you on? My guess is that you *have* to be on `0.16.x`. I believe this may have been fixed in `0.17.x`.

Here is my example app.

```coffeescript
## server code
auth = require("basic-auth")

app.use (req, res, next) ->
  credentials = auth(req) ? {}

  {name, pass} = credentials

  if name is "foo" and pass is "bar"
    next()
  else
    res
    .status(401)
    .set("WWW-Authenticate", "Basic realm='localhost'")
    .end()

app.get "/", (req, res) ->
  res.send("<html><a href='/page2'>page2</a></html>")

app.get "/page2", (req, res) ->
  res.send("<div id='main'>main</div>")

```

```coffeescript
## test code (this passes for me)

describe "basic auth", ->
  it "can visit without prompting challenge", ->
    cy
      .visit("http://foo:bar@localhost:8181/")
      .get("a").click()
      .location("pathname")
        .should("eq", "/page2")
      .get("#main")
```

**Comment by rarichard** [comment] 2017-08-07 13:43
Just curious, is there an approved/better way to provide basic auth with cypress via config? Or do I need to do it interactively somehow?

**Comment by brian-mann** [comment] 2017-08-07 14:57
I'm closing this issue in favor of this: https://github.com/cypress-io/cypress/issues/573

Back in the day this problem was never reproducible, but Chrome did remove support for embedded credential'd URL's which is clearly reproducible and needs a completely different workaround.

@rarichard for now you can switch to the Electron 53 browser from within Cypress to get things working without making any changes.

We'll either need to research a workaround for the way we handled basic auth in the past, such as injecting it via proxy (or another solution to this effect) or expose browser flags to disable this in chrome.

**Closed by brian-mann** 2017-08-07 14:57 UTC
Labels: needs information
