### ISSUE TITLE
No automatic scrolling in Cypress 13.5.0

### ISSUE THREAD

**Issue by FelixSchwenke** [cypress-io/cypress#28305] opened 2023-11-10 08:45 UTC

**Comment by jennifer-shehane** [comment] 2023-11-10 18:49
@FelixSchwenke Can you please describe your issue and provide a reproducible example of your problem.

**Comment by MelvinBaaijAviva** [comment] 2023-11-13 09:22
I have the same problem. After upgrading to Cypress V13.5.0 , in GUI mode. Running tests with Test preference setting :  Auto-scrolling set to ON. Auto scrolling during running test does not work

**Comment by jennifer-shehane** [comment] 2023-11-13 14:24
I'm not seeing this behavior in Chrome or Electron. 

Can you please provide a reproducible example? Can you also specify which browser you're seeing this behavior? How many tests are you running? Does it never work? Does it stop working at some point in the test run?

We cannot investigate bugs that we cannot recreate. The situations for the scrolling not working are likely specific to what you are running.

**Comment by MelvinBaaijAviva** [comment] 2023-11-14 07:32
Hi,
I am using: 
 - Chrome Version: 119.0.6045.124 
 - Cypress Version: 13.5.0
 - Node version: 16.20.0
 - I am running one test. The issue is not always present. I restarted the GUI and auto scrolling worked upto the 60th logged line in the 'Test status menu' , the next time I restarted it works fine. So it randomly appears. Not sure what's the cause

**Comment by jennifer-shehane** [comment] 2023-11-30 15:20
@MelvinBaaijAviva We'll need an example to reproduce this issue and move this forward. Otherwise we'll need to close the issue.

**Closed as not planned** 2024-04-23 02:02 UTC
