### ISSUE TITLE
getting typeError from `click();`

### ISSUE THREAD

**Issue by eifr-vault** [cypress-io/cypress#25023] opened 2022-12-07 10:18 UTC
### Current behavior

I'm getting `Cannot set property message of [object DOMException] which has only a getter` 

when doing 
```ts
cy.get('a').invoke('removeAttr', 'target').click();
```

### Desired behavior

Cypress should click on the link and open the page in the same frame

### Test code to reproduce

```ts
it('Clicking opens the link', {}, () => {
    cy.mount(<Componenet />);
    cy.get('a').invoke('removeAttr', 'target').click();
  });
```

### Cypress Version

12.0.1

### Node version

v16.15.1

### Operating System

macOS 13.0.1

**Comment by BlueWinds** [comment] 2022-12-08 17:00
I'm having trouble reproducing your issue locally. I used the following code:

```
    it('Clicking opens the link', {}, () => {
      cy.$$('body')[0].innerHTML = `<div><a target="_blank" href="/test">foo</a></div>`
      cy.get('a').invoke('removeAttr', 'target').click();
    });
```

and it seems to work for me, so the issue is likely somewhere in your component or the surrounding code; if you can provide a reproducible example, I'd be happy to take a closer look. Could possibly fork https://github.com/cypress-io/cypress-component-testing-apps and demonstrate the issue in one of the examples.

**Comment by eifr-vault** [comment] 2022-12-12 13:22
> I'm having trouble reproducing your issue locally. I used the following code:
> 
> ```
>     it('Clicking opens the link', {}, () => {
>       cy.$$('body')[0].innerHTML = `<div><a target="_blank" href="/test">foo</a></div>`
>       cy.get('a').invoke('removeAttr', 'target').click();
>     });
> ```
> 
> and it seems to work for me, so the issue is likely somewhere in your component or the surrounding code; if you can provide a reproducible example, I'd be happy to take a closer look. Could possibly fork https://github.com/cypress-io/cypress-component-testing-apps and demonstrate the issue in one of the examples.

I tried your example and it still fails with the same error
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/107053978/207055491-0ed365dc-5ce8-469f-9bb4-91eeaee29abc.png">

**Comment by BlueWinds** [comment] 2022-12-13 18:14
I'm really not sure how to help here - I had one of my coworkers on a mac try this out on 12.0.2, in Chrome 108, and we're just not running into it.

Some things to try:
- Try disabling any Cypress plugins or addons.
- Try disabling your code-coverage `beforeEach` hook.
- Try it with a completely empty support file, and disable any other setup code in your spec file.
- Try it on a different browser.

If any of these let the test pass, that could help narrow down the problem.

**Comment by eifr-vault** [comment] 2022-12-13 18:24
i tried to reset the config and remove all coverage.. now im getting a different error 😢 
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/107053978/207414618-5cdcd7e5-a1a2-434f-b597-dbb6147e83ad.png">

the code: 
```ts
    cy.mount(<FileDownloadTemplate />);

    cy.get('a').invoke('removeAttr', 'target').click();
    cy.url().should('include', '/file/link');

```

**Comment by BlueWinds** [comment] 2022-12-13 18:31
Well, you're making some progress; please continue debugging (or perhaps visit discord for help). Right now there doesn't seem to be enough information to reproduce the problem on our end, though - unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as completed by BlueWinds** 2022-12-13 18:31 UTC
