### ISSUE TITLE
cy.selectFile() fails with Webkit

### ISSUE THREAD

**Issue by sylvain-viole** [cypress-io/cypress#25930] opened 2023-02-23 08:28 UTC
### Current behavior

Using the same `cy.selectFile()` command on a UI doc upload test it is ✅ on chrome but ❌ on webkit

Command is a follows 
```javascript
cy.fixture(`pdf/${document.name}`).as('document');
    this.preparePage
      .getFileDropZone()
      .selectFile('@document', { force: true });
```
I then intercept the API request on `POST /documents`

=> On webkit it resolves in a `400` 
- response Body : 
```
{propertyPath: "file", message: "An empty file is not allowed.", key: null, keyData: {name: "\"documentFrench.pdf\""}}

```
- request Body 
 ```
"------WebKitFormBoundaryRo5h6lsb2JoKFB5V
Content-Disposition: form-data; name=\"file\"; filename=\"documentFrench.pdf\"
Content-Type: application/pdf


------WebKitFormBoundaryRo5h6lsb2JoKFB5V--
"
```

### Desired behavior

=> On Chrome it resolves with a `200` 

- Request Body
![image](https://user-images.githubusercontent.com/71819292/220852407-264331ae-8f14-4e4a-9b9f-ea0eae6ce86f.png)

### Test code to reproduce

As it uses company private codebase, I am not able to provide reproduction code.

### Cypress Version

12.3.0

### Node version

16.17.0

### Operating System

macOS 12.6

### Debug Logs

```shell
cypress:server:browsers:webkit-automation received request { browserPreRequest: { requestId: '475', method: 'POST', url: 'https://testing-kalos-api.yousign.tech/signature_requests/2e399824-1733-4798-a442-214e04a68f6f/documents', headers: { accept: 'application/json, text/plain, */*', 'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary4HxiNnknEM11xL5R', origin: 'https://testing-kalos-app.yousign.tech', referer: 'https://testing-kalos-app.yousign.tech/', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-site', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15' }, resourceType: 'xhr', originalResourceType: 'xhr' } } +59ms
```
```
  cypress:server:browsers:webkit-automation received requestfinished { responseReceived: { requestId: '475', status: 400, headers: { 'content-encoding': 'gzip', 'keep-alive': 'timeout=5', 'cache-control': 'no-cache, private', 'access-control-allow-origin': 'https://testing-kalos-app.yousign.tech', vary: 'Origin, Accept-Encoding', date: 'Thu, 23 Feb 2023 08:25:01 GMT', connection: 'keep-alive', 'access-control-expose-headers': 'Link, Retry-After', 'transfer-encoding': 'Identity', 'content-type': 'application/json', 'access-control-allow-credentials': 'true', server: 'nginx', 'ratelimit-limit': '20000', 'x-correlation-id': '48d77ca5-df13-4289-9fbd-5dda91da5979#76779', allow: 'GET, POST', 'ratelimit-reset': '59', 'x-ratelimit-remaining-hour': '23326', 'ratelimit-remaining': '19987', 'x-ratelimit-limit-minute': '20000', 'x-ratelimit-limit-hour': '24000', 'x-ratelimit-remaining-minute': '19987' } } } +17ms
```
```


### Other

_No response_

**Comment by flotwig** [comment] 2023-02-27 15:59
Hey @sylvain-viole, thanks for opening an issue. This looks like a duplicate of #24815, please follow that issue for updates.

**Closed as completed by flotwig** 2023-02-27 15:59 UTC
Labels: type: bug, browser: webkit, experiment: webkit
