### ISSUE TITLE
Custom array class methods disappear

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/cypress#17603] opened 2021-08-04 16:44 UTC
### Current behavior

Custom array class methods disappear:

```typescript
class MyArray extends Array<number> {
  public toString(): string {
    return 'Custom toString method called!';
  }

  public toDB(): string[] {
    return Array.from(this.map((t) => t.toString()));
  }
  
  public static fromDB(record: string[]): MyArray {
    return new MyArray(...record.map((t) => Number(t)));
  }
}

 // Logs an empty array `[]`
console.log('MyArray:', new MyArray());
// Logs an empty string (calls Array#toString instead of MyArray#toString)
console.log(`MyArray: ${new MyArray().toString()}`); 
// Logs `undefined` (even though I defined a MyArray#toDB method)
console.log('MyArray toDB:', new MyArray().toDB);
// Logs `[Function (anonymous)]` (so static methods are preserved)
console.log('MyArray fromDB:', MyArray.fromDB);
```

### Desired behavior

Cypress should compile that custom `MyArray` class and it's methods properly.

```typescript
// Should log `Custom toString method called!` instead of an empty string
console.log(`MyArray: ${new MyArray().toString()}`); 
// Should log `[Function (anonymous)]` instead of `undefined`
console.log('MyArray toDB:', new MyArray().toDB);
```

### Test code to reproduce

See description above.

### Cypress Version

Cypress package version: 8.1.0
Cypress binary version: 8.1.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1

**Comment by sainthkh** [comment] 2021-08-09 02:19
It's a bit hard to guess why this happened, but it might be because Cypress tests are trying to access application code.

For example, if you write the whole code in a single TS test file like below:

```ts
// test.ts

class MyArray extends Array<number> {
  public toString (): string {
    return 'Custom toString method called!'
  }

  public toDB (): string[] {
    return Array.from(this.map((t) => t.toString()))
  }

  public static fromDB (record: string[]): MyArray {
    return new MyArray(...record.map((t) => Number(t)))
  }
}

it('cy works', () => {
  // Should log `Custom toString method called!` instead of an empty string
  console.log(`MyArray: ${new MyArray().toString()}`)
  // Should log `[Function (anonymous)]` instead of `undefined`
  console.log('MyArray toDB:', new MyArray().toDB)
})
```

The result is like below:

![image](https://user-images.githubusercontent.com/8130013/128653924-296c8a3e-aed8-4c0d-9943-551ed560ba15.png)

The app code and test code are run in the separate frames, so it causes unexpected behavior. 

The solutions might be print out some messages on the app window and test the message with `cy` commands.

**Comment by nicholaschiang** [comment] 2021-08-09 16:30
@sainthkh have you tested that out when it's running in a Cypress task defined in the plugins file? Because I can recreate my repro when it's in a task, but I haven't yet tried to do what you just did (where the custom class is defined and used all in an actual test file that is bundled for the browser).

**Comment by sainthkh** [comment] 2021-08-09 23:48
[`cy.task` runs code in Node environment.](https://docs.cypress.io/api/commands/task#Syntax) It's natural that `MyArray` is not sent to the browser environment.

**Comment by nicholaschiang** [comment] 2021-08-14 21:29
Yeah, I know. But the logs in the terminal Node.js environment also show disappearing array methods.

**Comment by sainthkh** [comment] 2021-08-16 01:14
When I changed the compile target in `tsconfig.json` from `ES5` to `ES6`. It works.

**Comment by sainthkh** [comment] 2021-08-31 06:12
@nicholaschiang Did it solve the problem? If so, we can close the issue.

**Comment by sainthkh** [comment] 2021-09-21 01:28
Closing because of the inactivity.

**Closed by sainthkh** 2021-09-21 01:28 UTC
Labels: stage: awaiting response
