### ISSUE TITLE
Behaviour of node package outside of Cypress different to in Cypress

### ISSUE THREAD

**Issue by sydneyvert** [cypress-io/cypress#7717] opened 2020-06-16 08:32 UTC
### Current behavior:

When I execute my node script outside of Cypress it runs as planned. However, in Cypress it does not error and looks as if it has run but it hasn't executed. I have written my node code in the plugins file to be exported and call it using `cy.task()`.

### Desired behavior:

That the codes executes successfully as it does outside of Cypress.

### Test code to reproduce

Code that runs in node successfully outside of Cypress 

```js
import * as sql from 'mssql';

const cctdPassword = <password>;

const config = {
    user: <user>,
    password: cctdPassword,
    server: <server>,
    database: <database>
}

let sqlQuery = 'EXEC <myStoredProc>';

let returnValues = [];

async function queryDb ({config, sqlQuery}) {
    let pool = await sql.default.connect(config);

    console.log('pool:');
    console.log(pool);

    let data = await pool.request()
        .query(sqlQuery);

    console.log('data:');
    console.log(data.recordsets);

    for (let i=0;i<data.rowsAffected;i++){
        returnValues.push(data.recordset[i]);
    }

    console.log('return values:');
    console.log(returnValues);
    pool.close;
    sql.default.close;

    return returnValues;
}

queryDb({config, sqlQuery}).then( result => {
    result.forEach( item => {
        console.log(item);
    });
}).catch( err => {
    pool.close;
    sql.default.close;
    console.log(err)
})
```

The code in my plugins file looks like:
```js
module.exports = (on, config) => {
    on('task', {
       database: async ({config, sqlQuery}) => {
            let returnValues = [];
            async function queryDb ({config, sqlQuery}) {

                    let pool = await sql.connect(config);
                    console.log('pool');
                    console.log(pool);
                    let data = await pool.request()
                        .query(sqlQuery);
                    console.log('data');
                    console.log(data.recordsets);
                    for (let i = 0; i < data.rowsAffected; i++) {
                        returnValues.push(data.recordset[i]);
                    }
                    console.log('return values:');
                    console.log(returnValues);
                    pool.close;
                    sql.close;
                    return returnValues;
            }

            let result = [];
            queryDb({config, sqlQuery}).then(results => {
                result = results;
            }).catch( err => {
            pool.close;
            sql.close;
            console.log(err)
            })
            return new Promise((resolve) => {
                resolve(result);
            });
        }

    })
}
```

And I call this in my test using 
```js
describe("Query in SQL using plugins file", () => {
    it("Query in SQL using plugins file", () => {
        cy.task('database', {config, query}).then((result) => {
            console.log(result)
        });
    });
});
```

It logs pool to be the same as calling outside of Cypress and then does not get any further. I am not sure why it is executing differently inside Cypress as my understanding was the node plugins file worked the same.

### Versions

Cypress version 4.3.0 
OS: Windows

**Comment by sainthkh** [comment] 2021-01-15 06:00
Sorry for the late reply. It's a bit hard to pinpoint the problem because there's no reproducible example. 

But it seems that something went wrong in the code. 

In the plugin code, there's no `await` in front of `queryDb` call. Without it, `Promise` isn't resolved and the result returns with just the empty array you set as `let result = [];`.

The code below might solve the problem:

```js
const result = await queryDb({config, sqlQuery});
await pool.close();
await sql.close();

return result;
```

Moreover, according to [the mssql doc](https://www.npmjs.com/package/mssql), `close` is a function. But they're used like variables (`sql.close;`). And they're `async` functions and there're no `await` in front of them. 

I hope this change fixes your problem. 

I'll close this issue because it seems that it's not the problem on the Cypress side. If the problem's still happening, please leave a comment in this issue or ask a new question at the [discussion board](https://github.com/cypress-io/cypress/discussions).

**Closed by sainthkh** 2021-01-15 06:00 UTC
