### ISSUE TITLE
Getting -  read ECONNRESET when running Cypress in Chrom & Edge.

### ISSUE THREAD

**Issue by shashankkvs309668** [cypress-io/cypress#23748] opened 2022-09-09 13:30 UTC
### Current behavior

Cypress - v10.6
OS - Windows 10

Started our E2E  UI Automation Testing with Cypress after all approvals from management.
From Past one Month we are Facing the read ECONNRESET when running Cypress in Chrom & Edge for both headless and headed. But working fine only in Electron browser.
When checked with backend IT team, could not able to do the sophos agent global settings at org level.

And we cannot perform any Test execution operations now. How to proceed on this, is there any fix available for this issue. As the Designed Scripts are now totally useless to run.

### Desired behavior

Test Execution should work without any errors

### Test code to reproduce

npx cypress run --spec<spec File.js> --env file=<text>  --browser <edge/chrome>

### Cypress Version

10.6

### Node version

16.14

### Operating System

Windows 10

### Debug Logs

```shell
tried for Edge & Chrom browser, where the issue is comming,

GET /config/v1/Edge/105.0.1343.27?clientId=-6570308033263362323&agents=EdgeConfig%2CEdgeDomainActions%2CEdgeFirstRunConfig&osname=win&client=edge&channel=stable&scpfull=0&scpguard=0&scpfre=0&scpver=&osarch=x86_64&osver=10.0.19044&wu=1&devicefamily=desktop&uma=0&mngd=1&installdate=1631095109&edu=0&bphint=2&soobedate=1610643685 200 807.993 ms - -
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by emilyrohrbough** [comment] 2022-09-09 21:57
@shashankkvs309668 This is related to #14175. It has been reported that users that have installed Sophos with Network Threat Protection enabled are experiencing this issue. Are you by chancing using Sophos?

**Comment by shashankkvs309668** [comment] 2022-09-12 05:09
As mentioned in the description we are using Sophos  (Core Agent Version 2022.2.1.9).

**Comment by emilyrohrbough** [comment] 2022-09-12 14:50
I haven't dug into the full details of the required changes myself because I do not use Sophos. Do you mind share the concerns your IT team have around changing these permissions? It would help us understand the impact better.

**Comment by chrisbreiding** [comment] 2022-09-20 15:44
Closing as a duplicate of #14175

**Closed by chrisbreiding** 2022-09-20 15:44 UTC
Labels: stage: awaiting response
