### ISSUE TITLE
Missing browserCriClient in connectToNewSpec

### ISSUE THREAD

**Issue by karolis-kimtys** [cypress-io/cypress#28909] opened 2024-02-09 14:48 UTC
### Current behavior

SvelteKit project runs tests inside GitLab CICD and in some occasions it fails with "Missing browserCriClient in connectToNewSpec" message after running all Cypress tests.

### Desired behavior

Cypress tests should run and pass inside CICD pipeline without any failures. 

### Test code to reproduce

Possibly setting up a basic SvelteKit project and trying to run Cypress tests inside GitLab CICD.
---- .gitlab-ci.yml
```yml
.tests-setup:
  stage: runtests
  image: cypress/browsers:latest
  script:
    - npm install
    - npm run sync
    - npm run build
    - npm run preview &
    - npx wait-on https://localhost:5173
    - npx cypress run --record --browser chrome
  ```
----

### Cypress Version

v13.5.0

### Node version

18-alpine

### Operating System

GitLab Runner saas-linux-small-amd64 

### Debug Logs

```shell
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in connectToNewSpec
Error: Missing browserCriClient in connectToNewSpec
    at Object.connectToNewSpec (<embedded>:4438:48137)
    at Object.connectToNewSpec (<embedded>:4438:27043)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async v.relaunchBrowser (<embedded>:4504:37530)
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by AtofStryker** [comment] 2024-05-14 15:36
Hi @karolis-kimtys. Is it possible that you have debug logs via `DEBUG=cypress* npx cypress run --record --browser chrome`?

**Comment by karolis-kimtys** [comment] 2024-05-15 12:52
Is there a way to reduce log output size? I have ran in Gitlab pipeline but exceeded the 4mb log limit.

**Comment by AtofStryker** [comment] 2024-05-15 13:54
@karolis-kimtys maybe `DEBUG=cypress:server:browsers* npx cypress run --record --browser chrome` would get us mostly what we are looking for?

**Comment by jennifer-shehane** [comment] 2024-05-20 15:02
Going to close this as duplicate of https://github.com/cypress-io/cypress/issues/27657 if you can followup with debug logs in that issue.

**Closed as not planned by jennifer-shehane** 2024-05-20 15:02 UTC
Labels: type: duplicate
