### ISSUE TITLE
Back button, rerun buttons disappeared

### ISSUE THREAD

**Issue by frattaro** [cypress-io/cypress#615] opened 2017-09-03 14:25 UTC
- Operating System: Ubuntu 16.04
- Cypress Version: 0.19.4
- Browser Version: Chrome 60/Electron 53

### Is this a Feature or Bug?

Bug

### Current behavior:

In the header, the back button (to project window) and rerun buttons have disappeared.

### Desired behavior:

Buttons are available.

### How to reproduce:

I'm not sure why they disappeared. It happened some time shortly after I changed the viewportWidth and viewportHeight. But I decided that couldn't be it because I removed the entries from cypress.json and the buttons did not reappear.

#### Test code:

reporter.css shows an entry:
```js
.reporter header button {... display:none; ...}
```
When I disable the rule property, they show up and are usable. I couldn't find this file on the system. I'm not sure why they would have that rule anyway - can't think of a case where they'd be hidden.

### Additional Info (images, stack traces, etc)

![missing-controls](https://user-images.githubusercontent.com/14955351/30003812-b65688f0-9091-11e7-8130-42bd987dba05.png)

**Comment by frattaro** [comment] 2017-09-03 14:33
Oh, and it seems my cookies have stopped being cleared before running tests.

Restarting machine has no effect.

**Comment by brian-mann** [comment] 2017-09-03 17:38
This is being caused by the reporter on the left being resized to too small. Simply drag the left side to make it bigger and they will appear.

This has already been fixed in the upcoming `0.20.0` re: this issue https://github.com/cypress-io/cypress/issues/544

**Closed by brian-mann** 2017-09-03 17:38 UTC
