### ISSUE TITLE
Cypress 4.6 Update Issue

### ISSUE THREAD

**Issue by axleross09** [cypress-io/cypress#7473] opened 2020-05-25 11:57 UTC
### Current behavior:

After Installing the recent Version update of Cypress, Whenever I run a test in the Cypress Browser, Half of the test screen (Browser) goes up hiding the URL and Playground Selector. 

![Screenshot 2020-05-25 at 3 25 42 PM](https://user-images.githubusercontent.com/65379921/82810711-be7d9780-9ec1-11ea-8c68-e305f91e8eba.png)

### Desired behavior:

I can perform testing regularly

### Test code to reproduce

None

### Versions

Cypress 4.6, Mac OS Catalina, Chrome Version 83.0.4103.61

**Comment by SimonasB88** [comment] 2020-05-25 12:54
Exactly. Thought it is viewport problem in code or something. Seems not only to me.

**Comment by grivard** [comment] 2020-05-25 18:46
I am also experiencing this problem with 4.6.0.  Didn't notice it until I was trying to actually use the selector playground.  This is happening on any test, including those I always ran before.  I asked a colleague who is still on 4.4.1 to confirm that it doesn't disappear for him running the same test, and it doesn't.

**Comment by grivard** [comment] 2020-05-25 19:40
Workaround: For me at least, the selector playground seems to work using Electron, as long as the window is maximized.

**Comment by ragu2807** [comment] 2020-05-25 21:00
https://github.com/cypress-io/cypress/issues/7443

**Comment by jennifer-shehane** [comment] 2020-05-26 08:38
Duplicate of #7443

**Closed by jennifer-shehane** 2020-05-26 08:38 UTC
