### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by markusfalk** [cypress-io/cypress#5875] opened 2019-12-04 13:29 UTC
### Current behavior:

When accessing an external site with a self signed certificate I get the following error (Chrome has Certificate installed to access)

I already tried 

```json
{
  "chromeWebSecurity": false
}
```

and 

```
NODE_TLS_REJECT_UNAUTHORIZED=0 cypress open
```

#### Error 

```
CypressError: cy.visit() failed trying to load:

https://myInternalAngularApp.de/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: write EPROTO 24122634061576:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: write EPROTO 24122634061576:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16)
```

### Desired behavior:

Open https page as normal.

### Steps to reproduce: (app code and test code)

* open cypress
* use cy.visit('https://myInternalAngularApp.de/');
* run test

### Versions

* node@v12.13.0
* cypress@3.7.0
* Chrome Version 78.0.3904.108 (Offizieller Build) (64-Bit)

### Additional Information

* There has been a similar issue here: #4394

**Comment by sainthkh** [comment] 2021-01-06 05:46
Closing this issue because the website is now unavailable. I hope the problem has been solved with the latest Cypress. If the problem is still happening, please open a new issue with a reproducible example.

**Closed by sainthkh** 2021-01-06 05:46 UTC
