### ISSUE TITLE
CSS `scroll-behavior: smooth;` on the `html` el breaks actionability

### ISSUE THREAD

**Issue by nicklemmon** [cypress-io/cypress#3200] opened 2019-01-23 17:54 UTC
### Current behavior:
* Multiple tests when attempting to leverage the `.click()` and `.check()` methods with the following error:

> CypressError: Timed out retrying: cy.click() failed because the center of this element is hidden from view:

### Desired behavior:
* Ideally this CSS would not impact Cypress' ability to view elements appropriately
* Not a showstopper for our project as we can remove the styles and keep on trucking!

### Steps to reproduce: (app code and test code)
1. Add the following CSS:

```css
html {
  scroll-behavior: smooth;
}
```

1. Try running a Cypress test that leverages the `.click()` or `.check()` methods

### Versions
Cypress version 3.1.4, Mac OSX, Chrome

A huge thank you to all of the contributors on this project. It's a great great tool!

**Comment by jennifer-shehane** [comment] 2019-01-24 10:43
Hey @nicklemmon, I've opened a PR for this - writing a failing test for this behavior here: https://github.com/cypress-io/cypress/pull/3213

Now someone will need to look into why this failure occurs and fix Cypress calculations. Just from watching the test run, it looks as if the scroll is happening after the `.click` command has errored.

The error is being thrown at this line of code: https://github.com/cypress-io/cypress/blob/issue-3200-scroll-behavior-smooth/packages/driver/src/cy/ensures.coffee#L224

**Comment by jennifer-shehane** [comment] 2019-02-07 19:00
@Bkucera Brian was hoping you could pick this issue up as well as part of 3.1.6. 🙏 	Thank you!

**Comment by Bkucera** [comment] 2019-02-07 21:04
@jennifer-shehane this issue can't be fixed by simply passing options into `scrollIntoView`, it seems the css property will force all calls to `scrollIntoView` to be smooth.

The solution is to mutate the styles of the element with `scroll-behavior:smooth` just before the call to `scrollIntoView`, and then change it back right after.

I'm not sure why this would be a priority and need to go in the next patch, currently you can just work around this bug by removing that style

**Comment by sergioblancoo** [comment] 2019-03-11 05:17
I start having this issue when updated to Cypress 3.1.4 and I solved it by adding to cy.visit the following:

```
cy.visit('/', {
      onBeforeLoad(win) {
        cy.stub(win, 'scrollTo').as('windowScroll');
      }
    });
```
cc. @jennifer-shehane Hope this helps you.

**Comment by Betree** [comment] 2019-06-26 17:14
Same bug here, ended up disabling the style with the following snippet:

```es6
/**
 * Disable css smooth scroll, that doesn't plays nice with cypress.
 * See https://github.com/cypress-io/cypress/issues/3200
 */
const disableSmoothScroll = () => {
  cy.document().then(document => {
    const node = document.createElement('style');
    node.innerHTML = 'html { scroll-behavior: inherit !important; }';
    document.body.appendChild(node);
  });
};

describe('test', () => {
  it('does stuff', () => {
    cy.visit(...);
    disableSmoothScroll();
    cy.get(...).scrollIntoView();
  })
})
```

**Comment by ArthurClemens** [comment] 2019-07-17 12:14
I've solved this by adding class `e2e` to the html element when running in test mode, and setting

```css
html:not(.e2e) {
  scroll-behavior: smooth;
}
```

**Comment by gimtonic** [comment] 2019-09-25 09:36
Use only window.scrollTo(0,0);

**Comment by gtsop** [comment] 2019-10-29 17:25
Reproduction app:
https://github.com/gtsop/cypress-scroll-behaviour-smooth-bug-app

**Comment by gtsop** [comment] 2019-10-31 15:16
@jennifer-shehane Can I suggest we at least give out a warning when scroll-behaviour: smooth is in use and scrolling happens? I spent an hour trying to figure out why a simple test case didn't work, we can help a lot of people save time. I am willing to issue a PR with a little guidance regarding the appropriate place in the codebase to throw such a warning.

**Comment by jennifer-shehane** [comment] 2019-10-31 16:06
Ideally fixing the issue as @Bkucera described would be the best solution. https://github.com/cypress-io/cypress/issues/3200#issuecomment-461595024 

There is already a PR open with a failing test case if someone would like to make a PR using that test case as a base. https://github.com/cypress-io/cypress/pull/3213

**Comment by asarra** [comment] 2019-12-24 14:48
It is not just because of cypress itself. I have the same issue when I use nothing, but plain JS on Chrome, too. Seems to be a problem with the Chrome browser.

**Comment by jennifer-shehane** [comment] 2020-07-06 08:49
Just wanted to highlight what this issue is more clearly. 

`index.html`

```html
<html style="scroll-behavior: smooth">
<body>
  <div style="height: 4000px; background-color: red;"></div>
  <div style="height: 200px; background-color: green;">TEST</div>
</body>
</html>
```

```js
it('should be able to find and click', () => {
  cy.visit('index.html')
  cy.get('div:last')
    .click()
})
```

![](http://g.recordit.co/0r47zr17Rm.gif)

If you remove the `scroll-behavior: smooth`, it correctly clicks.

<img width="1276" alt="Screen Shot 2020-07-06 at 3 19 19 PM" src="https://user-images.githubusercontent.com/1271364/86574606-17018380-bf9c-11ea-8f5f-91ef6d9691ff.png">

**Comment by hueter** [comment] 2020-08-07 22:49
Hello,

I'm having a very tough time using the workaround. I don't have a single page app, so every time Cypress goes to a different route in my specs I have to re-disable smooth scrolling since the workaround above is dependant on injecting a style tag in the existing DOM.

Any suggestions? I tried putting `disableSmoothScroll` into a `Cypress.on("window:load"` but I got an error about a promise within a promise or something 🤔

**Comment by jennifer-shehane** [comment] 2020-08-12 10:24
If you're using this workaround - you would have to call `disableSmoothScroll` after the `cy.visit()` https://github.com/cypress-io/cypress/issues/3200#issuecomment-505965470, so yes you would need to call this after every `cy.visit()`. 

You could also write a custom command so this is always called after your visit. https://on.cypress.io/custom-commands#Overwrite-Existing-Commands

```js
Cypress.Commands.add('visitApp', (url) => {
  cy.visit(url)
  cy.document().then(document => {
    const node = document.createElement('style');
    node.innerHTML = 'html { scroll-behavior: inherit !important; }';
    document.body.appendChild(node);
  });
})

it('test', () => {
  cy.visitApp('https://...')
})
```

**Comment by hueter** [comment] 2020-08-12 17:46
Thanks @jennifer-shehane 

I think this will work for now. Unfortunately if any of my specs click on links I also have to remember to invoke this 😞 

Hopefully a fix comes out someday 👀

**Comment by Sandy-Garrido** [comment] 2020-09-30 18:45
This work around is great!
I personally adapted it slightly only to allow the site to continue to work as expected. This a "toggle" approach:

Maybe this will help others as it did me until something else comes in :) 

in commands add a new function:

```JavaScript
Cypress.Commands.add("toggleScrollIntoViewHTML", () => {
	cy.document().then((document) => {
		let element = document.getElementById("scroll_into_view_disable");
		if (typeof element != "undefined" && element != null) {
			element.remove();
		} else {
			const node = document.createElement("style");
			node.innerHTML = "html { scroll-behavior: inherit !important; }";
			node.setAttribute("id", "scroll_into_view_disable");
			document.body.appendChild(node);
		}
	});
});
```

Then use this before and after to add and then remove this styling change from the DOM 

```JavaScript
it("A test name", () => {
	cy.toggleScrollIntoViewHTML(); //Adds

	cy.get(".className").scrollIntoView().click();

	cy.toggleScrollIntoViewHTML(); // Removes
});

```

**Comment by todd-m-kemp** [comment] 2020-10-09 18:59
Overwriting the `cy.visit` command so that it automatically handles the workaround above has worked well for me.
```
Cypress.Commands.overwrite('visit', (originalFn, url) => {
  originalFn(url);
  cy.document().then((document) => {
    const node = document.createElement('style');
    node.innerHTML = 'html { scroll-behavior: inherit !important; }';
    document.body.appendChild(node);
  });
});
```
This way you can just use `cy.visit` like you normally would and have the `scroll-behavior` modification taken care of without having to think of it.

That said, you will still run into problems if your test loads a new page not using `cy.visit` (i.e. navigating to a new page by clicking a button or taking some other action). I know that Cypress considers this kind of test structure to be an anti-pattern, but there are times when structuring a test in this way has its benefits, so I would still say that there is value in resolving this issue in the general sense.

**Comment by todd-m-kemp** [comment] 2020-10-15 16:23
Thanks everyone for providing workarounds; they do seem to work.

That said, I do really wish that the original issue were to be resolved. Having to factor this workaround into tests is quite arduous. Yes, you can write your own custom command to use the workaround after a `cy.visit`, but this doesn't account for uses of `cy.reload` or `cy.go` for which you also need to write custom commands. Furthermore, if your application sends you to a new page during a test (as a result of clicking a button or some other user interaction) you also have to deliberately apply the workaround in those instances since the scroll behaviour will have been reset to smooth.

It is not impossible to deal with, but it is much more work than I would expect to have to do in order to be able to write basic tests out of the box on a page that uses smooth scrolling.

Just my two cents.

**Comment by sand4rt** [comment] 2020-11-21 23:13
I decided to override the native scrollIntoView method as a workaround. Add the following code to your `commands.js` and the scrollIntoView() should work as expected: 
 
```javascript 
Cypress.Commands.overwrite("scrollIntoView", (originalFn, url, options) => {
	cy.document().then((document) => {
		document.documentElement.style.scrollBehavior = "auto";
		originalFn(url, options);
		document.documentElement.style.scrollBehavior = "";
	});
});
```

**Comment by paulyoung5** [comment] 2020-12-16 13:20
thanks for the workarounds shared here - I went with something similar that seems to be working regardless of `.visit()` or `.reload()` calls:

```css
html:not(.cypress-tests) {
  scroll-behaviour: smooth;
}
```

```js
// cypress/support/index.js

Cypress.on('window:before:load', win => {
  const htmlNode = win.document.querySelector('html')
  htmlNode.classList.add('cypress-tests')
})
```

**Comment by obedparla** [comment] 2021-01-01 21:35
Is there a chance this issue can be caused by something else? I'm having the exact same issue but I'm not using `scroll-behavior: smooth;` anywhere. I've tried the workarounds as well just in case to no avail. 

Using `.click` works on Firefox but on on Chromiun because of the scrolling issue. I tried forcing it with `.click({force: true})`, or scrolling it manually, nothing has worked. 

My element is inside an Iframe, so I thought that may be the issue, but I created a simple app to test and scrolling on click works as it should even when you're targetting an element inside an iframe (and it even scrolls both the main page and the iframe if it needs to). 

I'm at a loss as to what could be causing this exact same issue that is not `scroll-behavior: smooth;`

**Comment by jennifer-shehane** [comment] 2021-01-04 02:25
@obedparla It's entirely possible there could be another issue. We'd need a reproducible example to narrow it down. You may also want to play with our new `scrollBehavior` option in the `.click()` command, in case you missed that.

**Comment by obedparla** [comment] 2021-01-04 10:35
Thanks @jennifer-shehane . I tried that too but got no results :(. I'd love to provide an example but I have no clue what's causing the issue. For now I'm just forcing the tests to run on Firefox. I'll post here if I ever figure it out 🤞

**Comment by TuureKaunisto** [comment] 2021-01-11 14:41
Based on the suggested workarounds we decided to create a wrapper command that alters the page styles before scrolling
```
Cypress.Commands.add('instantScroll', selector => {
  cy.document().then(document => {
    const htmlElement = document.querySelector('html');
    if (htmlElement) {
      htmlElement.style.scrollBehavior = 'inherit';
    }
  })
  cy.get(selector).scrollIntoView();
  return cy.get(selector);
})
```

**Comment by Flinlock** [comment] 2021-02-05 15:38
@paulyoung5 love your workaround, seems to be the least hassle and headache.

**Closed** 2021-03-15 18:56 UTC
Labels: existing workaround, first-timers-only, internal-priority, pkg/driver, stage: work in progress, topic: actionability, topic: scrolling ↕️, type: bug
