### ISSUE TITLE
Cypress takes 60+ seconds to build each unit test and execute

### ISSUE THREAD

**Issue by silbinarywolf** [cypress-io/cypress#3704] opened 2019-03-13 22:38 UTC
### Current behavior:
When using `cypress run` on CI, it builds each test in isolation. Since we're using Cypress for [unit testing](https://github.com/silbinarywolf/cypress-aurelia-unit-test), this means it takes about 60 seconds to build each test and execute. Each test we add increases the time it takes for Cypress to run on our CI machines, which is less than ideal.

### Desired behavior:
Build all the test code once.

### Steps to reproduce: (app code and test code)
N/A

### Versions
3.1.5

**Comment by jennifer-shehane** [comment] 2019-03-14 05:38
Hey @silbinarywolf, I'm not able to reproduce this 60+ sec build/execution time. 

I ran the tests in the library linked using `cypress run` in my local terminal and they all ran within 1 second. 

<img width="821" alt="Screen Shot 2019-03-14 at 12 07 36 PM" src="https://user-images.githubusercontent.com/1271364/54333682-cf8e1000-4651-11e9-9844-7b4d743c900f.png">

Are you able to recreate this behavior locally? If not, I would look more closely at your CI configuration. Can you share your CI configuration?

**Comment by silbinarywolf** [comment] 2019-03-15 03:46
Sorry if I wasn't clear. I was linking to the library we're using for unit testing our code not linking to a reproducible repo.

This is issue is occurring in our private codebase which is quite bulky and monolithic, so simply importing 1 class/component to test will import a large chunk of the project.

Am I incorrect in my assumption that Cypress will rebuild each test file separately via Webpack?

**What we run in CI**
- `cypress run`

**cypress.json**
```
{
	"viewportWidth": 1280,
	"viewportHeight": 720,
	"videoUploadOnPasses": false,
	"env": {
		"forceAPIRecording": false,
		"stubAPIPatterns": [
			"api"
		]
	}
}
```

**Comment by jennifer-shehane** [comment] 2019-03-19 13:05
Hey @silbinarywolf, can you run cypress specifically with the debug logging for our browserify logic and print those here - hopefully this should show some helpful information. 

```shell
DEBUG=cypress:browserify,cypress:server:preprocesssor cypress open
```

or

```shell
DEBUG=cypress:browserify,cypress:server:preprocesssor cypress run
```

**Comment by silbinarywolf** [comment] 2019-03-20 00:37
The debug commands you suggested didn't seem to work (ie. ran it, no debug lines were printed), but I did discover that `cypress:webpack` worked, so I opted to use that. I got the output below.

Since you can't see what the test is importing, technically it's importing entrypoint for the project, ie. `main.ts`. This goes on to import jQuery, stylesheets and a **lot** of other files.

Looking at the output, it seems like perhaps I could handle this in my `support/index.js` file instead and that might make the most expensive part of the build, only happen once?

`DEBUG=cypress:webpack ./node_modules/.bin/cypress run`
```
2019-03-20T00:28:22.346Z cypress:webpack user options: { webpackOptions:
   { resolve: { alias: [Object], extensions: [Array], modules: [Array] },
     entry: { app: [Array] },
     output:
      { path: 'C:\\{myproject}\\dist\\static',
        publicPath: '/',
        filename: '[name].bundle.js',
        sourceMapFilename: '[name].bundle.map',
        chunkFilename: '[name].chunk.js' },
     devServer:
      { contentBase: 'C:\\{myproject}\\dist\\static',
        clientLogLevel: 'error',
        historyApiFallback: true,
        inline: true,
        port: 9000,
        stats: [Object] },
     module: { strictExportPresence: true, rules: [Array] },
     plugins:
      [ [Object],
        [Object],
        CheckerPlugin {},
        [Object],
        [Object],
        [Object] ],
     mode: 'development',
     devtool: 'cheap-module-eval-source-map' } }

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.5                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      7 found (unit\address.test.ts, unit\autocomplete.test.ts, unit\category-descripti… │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                
  Running: unit\address.test.ts...                                                         (1 of 7)
2019-03-20T00:28:25.354Z cypress:webpack get C:\{myproject}\cypress\integration\unit\address.test.ts
2019-03-20T00:28:25.354Z cypress:webpack input: C:\{myproject}\cypress\integration\unit\address.test.ts
2019-03-20T00:28:25.355Z cypress:webpack output: C:\Users\{my_user_name}\AppData\Roaming\Cypress\cy\production\projects\javascript-11d360c39cbd570a7c764bd7472a01c6\bundles\cypress\integration\unit\address.test.ts
2019-03-20T00:28:25.563Z cypress:webpack get C:\{myproject}\cypress\support\index.js
2019-03-20T00:28:25.564Z cypress:webpack input: C:\{myproject}\cypress\support\index.js
2019-03-20T00:28:25.564Z cypress:webpack output: C:\Users\{my_user_name}\AppData\Roaming\Cypress\cy\production\projects\javascript-11d360c39cbd570a7c764bd7472a01c6\bundles\cypress\support\index.js
i ｢atl｣: Using typescript@3.0.1 from typescript
i ｢atl｣: Using tsconfig.json from C:/{myproject}/tsconfig.json
i ｢atl｣: Using typescript@3.0.1 from typescript
i ｢atl｣: Using tsconfig.json from C:/{myproject}/tsconfig.json
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
(node:16216) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 changed listeners added. Use emitter.setMaxListeners() to increase limit
i ｢atl｣: Checking started in a separate process...
i ｢atl｣: Time: 1075ms
i ｢atl｣: Checking started in a separate process...
i ｢atl｣: Time: 812ms
2019-03-20T00:29:30.325Z cypress:webpack finished bundling C:\Users\{my_user_name}\AppData\Roaming\Cypress\cy\production\projects\javascript-11d360c39cbd570a7c764bd7472a01c6\bundles\cypress\integration\unit\address.test.ts
2019-03-20T00:29:30.457Z cypress:webpack finished bundling C:\Users\{my_user_name}\AppData\Roaming\Cypress\cy\production\projects\javascript-11d360c39cbd570a7c764bd7472a01c6\bundles\cypress\support\index.js


  Address
    √ Select Suburb that auto-populates State, Post Code and Country (993ms)
    √ Change State will clear Suburb and Post Code (1049ms)
    √ Pressing clear button for State will clear Suburb and Post Code (1042ms)


  3 passing (3s)


  (Results)

  ┌────────────────────────────────────┐
  │ Tests:        3                    │
  │ Passing:      3                    │
  │ Failing:      0                    │
  │ Pending:      0                    │
  │ Skipped:      0                    │
  │ Screenshots:  0                    │
  │ Video:        true                 │
  │ Duration:     3 seconds            │
  │ Spec Ran:     unit\address.test.ts │
  └────────────────────────────────────┘

2019-03-20T00:29:36.054Z cypress:webpack close C:\{myproject}\cypress\integration\unit\address.test.ts

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                
  Running: unit\autocomplete.test.ts...                                                    (2 of 7)
2019-03-20T00:29:37.691Z cypress:webpack get C:\{myproject}\cypress\integration\unit\autocomplete.test.ts
2019-03-20T00:29:37.691Z cypress:webpack input: C:\{myproject}\cypress\integration\unit\autocomplete.test.ts
2019-03-20T00:29:37.691Z cypress:webpack output: C:\Users\{my_user_name}\AppData\Roaming\Cypress\cy\production\projects\javascript-11d360c39cbd570a7c764bd7472a01c6\bundles\cypress\integration\unit\autocomplete.test.ts
i ｢atl｣: Using typescript@3.0.1 from typescript
i ｢atl｣: Using tsconfig.json from C:/{myproject}/tsconfig.json
i ｢atl｣: Checking started in a separate process...
i ｢atl｣: Time: 791ms
2019-03-20T00:30:10.276Z cypress:webpack finished bundling C:\Users\{my_user_name}\AppData\Roaming\Cypress\cy\production\projects\javascript-11d360c39cbd570a7c764bd7472a01c6\bundles\cypress\integration\unit\autocomplete.test.ts


  Autocomplete
    √ Type Victor (includes simulated typo, backspacing and fixing it) and select (704ms)
    √ Type S and select New South Wales (327ms)
    √ Type X and get no results (263ms)


  3 passing (1s)


  (Results)

  ┌─────────────────────────────────────────┐
  │ Tests:        3                         │
  │ Passing:      3                         │
  │ Failing:      0                         │
  │ Pending:      0                         │
  │ Skipped:      0                         │
  │ Screenshots:  0                         │
  │ Video:        true                      │
  │ Duration:     1 second                  │
  │ Spec Ran:     unit\autocomplete.test.ts │
  └─────────────────────────────────────────┘

2019-03-20T00:30:13.592Z cypress:webpack close C:\{myproject}\cypress\integration\unit\autocomplete.test.ts
```

**Comment by JakeBIress** [comment] 2019-04-29 23:53
@jennifer-shehane After some investigation, I've discovered that if I provide all test spec files as a seperate "entry" items in the [cypress-webpack-preprocessor](https://github.com/cypress-io/cypress-webpack-preprocessor), I can make all tests + the support.js file build once. This essentially makes running Cypress tests as fast our Webpack production build.

To do this, I had to manually scan the `cypress/integration` folder for the tests as the ["options" parameter](https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/index.js#L44) provided to the preprocessor function callback only provides the current test file being executed.

Ideally, there would be a callback for building all test files at once rather than building each spec individually, however we can just get away with bundling everything on the first test, so even something as simple as providing all test files in the "options" parameter would help reduce complexity on my current unfinished implementation. (ie. I don't need to manually get all test files out of `cypress/integration` myself)

When it's done, I'll add another comment with my forked / customised cypress webpack preprocessor so the Cypress team can observe what I mean. I don't feel like a PR against the original repo is appropriate as it requires manually scanning of the cypress/integration directory and is a bit of a hack.

**Comment by silbinarywolf** [comment] 2019-04-29 23:54
@jennifer-shehane After some investigation, I've discovered that if I provide all test spec files as a seperate "entry" items in the [cypress-webpack-preprocessor](https://github.com/cypress-io/cypress-webpack-preprocessor), I can make all tests + the support.js file build once. This essentially makes running Cypress tests as fast our Webpack production build.

To do this, I had to manually scan the `cypress/integration` folder for the tests as the ["options" parameter](https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/index.js#L44) provided to the preprocessor function callback only provides the current test file being executed.

Ideally, there would be a callback for building all test files at once rather than building each spec individually, however we can just get away with bundling everything on the first test, so even something as simple as providing all test files in the "options" parameter would help reduce complexity on my current unfinished implementation. (ie. I don't need to manually get all test files out of `cypress/integration` myself)

When it's done, I'll add another comment with my forked / customised cypress webpack preprocessor so the Cypress team can observe what I mean. I don't feel like a PR against the original repo is appropriate as it requires manually scanning of the cypress/integration directory and is a bit of a hack.

**Comment by jakebiress** [comment] 2019-05-01 02:49
Here's my customized Cypress Webpack Preprocessor:
https://github.com/silbinarywolf/cypress-webpack-multibundle-preprocessor

**Comment by silbinarywolf** [comment] 2019-05-01 02:54
Here's my customized Cypress Webpack Preprocessor:
https://github.com/silbinarywolf/cypress-webpack-multibundle-preprocessor

**Comment by jennifer-shehane** [comment] 2019-07-24 05:56
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Closed by jennifer-shehane** 2019-07-24 05:56 UTC
Labels: stage: needs investigating
