### ISSUE TITLE
UX - Option to collapse all or expand all tests

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/cypress#15669] opened 2021-03-26 05:07 UTC
### What would you like?

In Cypress's local test runner, there should be a button in the top left (next to the "toggle auto-scroll" button) that collapses or expands all test results.

### Why is this needed?

This would be nice to easily collapse all of the failing tests in order to see just the names of each tests that I then have to inspect by itself (see #15668 for more info on that).

**Comment by jennifer-shehane** [comment] 2021-03-29 18:15
Duplicate of https://github.com/cypress-io/cypress/issues/8563

**Closed by jennifer-shehane** 2021-03-29 18:15 UTC
