### ISSUE TITLE
Clicking on element within Select2 Autogen dropdown causes cypress viewport toolbar to disappear, and viewport to resize / relocate, causing test failures

### ISSUE THREAD

**Issue by symon-skelly** [cypress-io/cypress#7440] opened 2020-05-21 10:08 UTC
### Current behavior:

When accessing a Select2 Autogenerated dropdown menu and clicking on an element within, the cypress viewport will resize, relocate, and the Selector Playground & URL field will disappear.

Before 'Hawaii' item has been clicked:

![image](https://user-images.githubusercontent.com/60613068/82548468-3b6fe080-9b53-11ea-98cd-db491da106aa.png)

After 'Hawaii' item has been clicked:
![image](https://user-images.githubusercontent.com/60613068/82548536-5b9f9f80-9b53-11ea-92c3-578b95ea8038.png)

### Desired behavior:

When clicking on the select2 dropdown item, the item should be selected and the viewport Selector Playground & URL field should still exist, and the viewport should not resize or relocate.

### Test code to reproduce

```js
cy.visit('https://select2.org/appearance', {timeout: 6000}) //visit serlect2 url
cy.get('.js-programmatic-enable').click() //enable the select2 dropdown
cy.get(':nth-child(6) > :nth-child(1) > .select2 > .selection > .select2-selection').click() //click the select2 dropdown
cy.get('#select2-b54g-result-evac-HI').click() //click the Hawaii option from the dropdown menu
```

### Versions

Cypress 4.6.0, Windows 10, Google Chrome 81
Issue does not occur on Cypress 4.5.0, Windows 10, Google Chrome 81

### Notes

If I select the option via typing its name into the search field and pressing enter, the issue does not occur.

`cy.get('.select2-dropdown > .select2-search > .select2-search__field').type('Hawaii{enter}')`

**Comment by jennifer-shehane** [comment] 2020-05-22 07:24
Duplicate of #7443 which will be fixed in our next release.

**Closed by jennifer-shehane** 2020-05-22 07:24 UTC
