### ISSUE TITLE
Error "TypeError: Cannot read property 'body' of null" when trying to use cy.type() in an iframe

### ISSUE THREAD

**Issue by codybarr** [cypress-io/cypress#6142] opened 2020-01-10 19:50 UTC
### Current behavior:

I'm trying to type into a froala editor that uses an iframe to receive input and render rich text. The code below runs successfully in Cypress `3.4.1` but in `3.8.1` it throws an error:

```js
cy.get('section.modal iframe.fr-iframe').then(function($iframe) {
    const $body = $iframe.contents().find('body')
    cy.wrap($body)
        .find('p')
        .type(MESSAGE)
})
```

![image](https://user-images.githubusercontent.com/4359586/72177919-c1af3580-33af-11ea-9410-618dcbb1c536.png)

### Desired behavior:

After reverting Cypress to `3.4.1` the iframe `.type()` code runs successfully

### Test code to reproduce

https://github.com/codybarr/cypress-bug-6142

**Note**: In creating this I discovered that if I first `.clear()` the editor I'm then able to `.type()` into it. So I have something of a workaround but still think this behavior is strange.

**Also Note**: In the test code repo above I'm using TinyMCE but the behavior is the same as Froala.

### Versions

Cypress: `3.8.1`
OS: MacOS 10.14.6 (Mojave)
Browser: Chrome 79 / Electron 78

**Comment by jennifer-shehane** [comment] 2020-01-13 06:03
Closing as duplicate of https://github.com/cypress-io/cypress/issues/5930

**Closed by jennifer-shehane** 2020-01-13 06:03 UTC
