### ISSUE TITLE
headles mode saves screenshots in an extra folder compared to cypress run

### ISSUE THREAD

**Issue by blv-rodrigoerades** [cypress-io/cypress#29057] opened 2024-03-05 07:32 UTC
### Current behavior

For some reason, Cypress does save the screenshots in a different folder  when running in headless mode (cypress run)

It will use the  spec file name to build an extra folder in the path

ie:
**[CORRECT]   cypress open** => .../snapshots/actual/cypress/e2e/alt-sub/foo/**deep.cy.ts**/inside_context.png
**[INCORRECT] cypress run** =>  .../snapshots/actual/**deep.cy.ts**/cypress/e2e/alt-sub/foo/**deep.cy.ts**/inside_context.png

A workaround to remove the extra folder from the path is to look into Cypress.spec object.

When running headless there is an extra attribute named **`relativeToCommonRoot`** 
           
looking at Cypress.spec we can see that the relativeToCommonRoot is set only when running in headless mode
and that is the only time we need to remove the extra folder from the path
 

### Desired behavior

Both `cypress open` and `cypress run` should save the screenshots to the same folder 

### Test code to reproduce

```js
// /cypress/e2e/alt-sub/foo/deep.cy.ts

describe('Inner file within context', () => {
  it('test inside context', () => {
    cy.visit('./web/01.html'). // Could be any web page  
    cy.screenshot('inside context')
    })
});
```

you need to run the 2 commands to see that the files are saved in different folders:
```bash
cypress open
cypress run
```

### Cypress Version

13.6.6

### Node version

18.18.2

### Operating System

macOS 14.3.1

**Comment by jennifer-shehane** [comment] 2024-03-05 16:27
Duplicate of https://github.com/cypress-io/cypress/issues/24052

**Closed as not planned by jennifer-shehane** 2024-03-05 16:27 UTC
Labels: type: duplicate

**Comment by jennifer-shehane** [comment] 2024-03-05 16:29
Actually may be a duplicate of https://github.com/cypress-io/cypress/issues/27992, but it is related to the same behavior of the other issue.
