### ISSUE TITLE
CypressError: Cypress detected a cross origin error happened on page load showing in Chromium browser whereas working for firefox browser

### ISSUE THREAD

**Issue by Suban5** [cypress-io/cypress#6593] opened 2020-02-28 07:15 UTC
### Current behavior:

Chromium browser is always showing `CypressError: Cypress detected a cross origin error happened on page load:` but while running same code it works fine in firefox browser

I am trying to login into the demo server `http://executeautomation.com/demosite/Login.html`

After clicking login button the page will redirect to `http://executeautomation.com/demosite/index.html?UserName=admin&Password=password&Login=Login`

After the error i have added   `"chromeWebSecurity": false` in `cypress.json` file.

After adding `chromeWebSecurity`, the page will navigate to `chrome-error://chromebdata/` instead of `http://executeautomation.com/demosite/index.html?UserName=admin&Password=password&Login=Login`

### Desired behavior:

The test must be pass on all browsers

### Test code to reproduce

```js
describe("My first cypress test", () => {
    it("Navigate to ea site", () => {
        cy.visit('http://executeautomation.com/demosite/Login.html')
    });

    it("Login to application", () => {
        cy.get("input[name=UserName").type("admin");
        cy.get("input[name=Password]").type("password");
        cy.get("input[name=Login]").click()
    });

    it('Enter User Details', () => {
        cy.get("#TitleId").select("Ms.");
        cy.get("#Initial").type("SD");
        cy.get("#FirstName").type("Diamond");
        cy.get("input[name=Hindi]").click();
        cy.get("input[name=Save]").click()
    });
});
```

### Versions
Cypress: 4.0.2
Operating System : Ubuntu 18.04.4 LTS
browser: Chromium 80, electron 78
working fine in Firefox 73(beta) browser

**Comment by jennifer-shehane** [comment] 2020-02-28 07:36
Duplicate of #4220

**Closed by jennifer-shehane** 2020-02-28 07:36 UTC
