### ISSUE TITLE
Vue stubs not working in cypress 12.3.0 + vue 2.7.14 + script setup

### ISSUE THREAD

**Issue by mverdaguer** [cypress-io/cypress#25450] opened 2023-01-13 09:20 UTC
### Current behavior

Cypress fails to stub components when working with Vue 2.7 and using `<script setup>`.
I prepared [this github project](https://github.com/mverdaguer/cypress-vue-2.7-stubs-not-working) with an example which I'll explain next.

Having a component like:
```js
<script setup lang="ts">
import ChildComponent from './ChildComponent.vue'
</script>

<template>
  <div class="hello-world">
    <ChildComponent />
    <ChildComponent />
    <ChildComponent />
  </div>
</template>
```
Where `ChildComponent` can be anything.

Cypress fails to stub `ChildComponent` with the following code:
```js
it("renders properly", () => {
    cy.mount(HelloWorld, { stubs: { ChildComponent: true } })
      .get("childcomponent-stub")
      .should("have.length", "3");  // It is returning 0!
  });
``` 

Whereas, if I set up the parent component like:
```js
<script lang="ts">
import { defineComponent } from "vue";
import ChildComponent from "./ChildComponent.vue"

export default defineComponent({
  components: {
    ChildComponent,
  },
});
</script>

<template>
  <div class="hello-world">
    <ChildComponent />
    <ChildComponent />
    <ChildComponent />
  </div>
</template>
```
It works like a charm.

### Desired behavior

Ideally both components should have the same output. That is, when creating a component with `<script setup>`, Vue stubs should work properly.

### Test code to reproduce

https://github.com/mverdaguer/cypress-vue-2.7-stubs-not-working

### Cypress Version

12.3.0

### Node version

v16.19.0

### Operating System

macOS 13.1

**Comment by lmiller1990** [comment] 2023-01-17 23:49
Thanks for the bug report, I suspect the problem is in the underlying Vue Test Utils library: https://github.com/vuejs/vue-test-utils/issues/2048

We should try fix it there.

**Comment by mverdaguer** [comment] 2023-01-18 07:28
Thanks @lmiller1990!

**Comment by oevasque** [comment] 2023-05-16 18:32
Hey @lmiller1990. What is going on?. What is the current status of this bug? It is totally annoying dont being able to test components when <script setup> is used (the current reommended way to declare the setup) 😭.

**Comment by lmiller1990** [comment] 2023-06-05 04:30
To clarify, this only happens in Vue 2 (not Vue 3)?

I guess we need to fix https://github.com/vuejs/vue-test-utils/issues/2048. The bug is in the actual Test Utils library. I don't have bandwidth to fix that one right now - I have to maintain the Vue 3 Test Utils, Vue Jest, cypress/vue, and many other libs -- if someone wants to fix https://github.com/vuejs/vue-test-utils/issues/2048 I'd be happy to review and release a patch.

In general, I find is less necessary to stub components when I write tests with Cypress anyway - that's one of the things I like about it. Are you attempting to migrate an existing Test Utils suite to Cypress, or writing fresh tests in Cypress? If you'd like to share a specific componen/test you'd like to write, I might be able to make some recommendations. I've found that avoiding stubbing components has helped my tests be more useful and catch regressions.

**Comment by mverdaguer** [comment] 2023-06-05 10:36
Hey @lmiller1990, yes in our case with Vue 3 stubs work as expected. So the problem happens only in Vue 2.

**Comment by jennifer-shehane** [comment] 2024-12-10 17:45
We'll be closing this issue as Vue 2 support will be removed in Cypress 14.

**Closed as completed by jennifer-shehane** 2024-12-10 17:45 UTC
Labels: CT, Triaged
