### ISSUE TITLE
Type error within Cypress itself after upgrading to the latest version

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#25762] opened 2023-02-09 20:18 UTC
### Current behavior

After upgrading to the latest version of all Cypress dependencies, I am getting a type error from deep within Cypress itself:

```
../../common/temp/node_modules/.pnpm/cypress@12.5.1/node_modules/cypress/types/cypress.d.ts:6201:13 - error TS2430: Interface 'cy' incorrectly extends interface 'Chainable<undefined>'.
  The types returned by 'now(...)' are incompatible between these types.
    Type 'void' is not assignable to type 'Promise<any> | ((subject: any) => any)'.

6201   interface cy extends Chainable<undefined> { }
                 ~~


Found 1 error in ../../common/temp/node_modules/.pnpm/cypress@12.5.1/node_modules/cypress/types/cypress.d.ts:6201
```

### Desired behavior

No type errors.

### Test code to reproduce

N/A. The problem is coming from Cypress itself.

### Cypress Version

12.5.1

### Node version

16.19.0

### Operating System

Windows 11

### Debug Logs

```shell
N/A
```

**Comment by warrensplayer** [comment] 2023-02-14 18:15
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marktnoonan** [comment] 2023-02-20 21:35
@kaiyoma I'm going to close this issue due to inactivity, please comment with more details when you are ready. If this is still a problem we can look into it more then.

**Closed as completed by marktnoonan** 2023-02-20 21:35 UTC
