### ISSUE TITLE
Support automated E2E config and example scaffolding

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29619] opened 2024-06-05 11:12 UTC
### What would you like?

Cypress should support an automated way of configuring and setting up E2E examples through the command line, for instance using an environment variable.

The choice of the full set of "Scaffold example specs" or the single test spec from "Create new spec" should be given.

### Why is this needed?

Currently it is necessary to use `cypress open`, then to manually agree to the configuration, followed by selecting spec options.

This means that there is no straightforward way to automate the setup or update of a running Cypress example project. Instead, manual steps have to be described and carried out. An example of this is in the instructions [factory/test-project/README.MD](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/README.MD) in the [cypress-io/cypress-docker-images](https://github.com/cypress-io/cypress-docker-images) repo, where it is necessary to combine shell instructions with manual instructions to achieve setup:

---
```shell
rm -rf cypress cypress.config.js
npm install cypress@latest --no-package-lock
npx cypress open
```

- Select "E2E Testing"
- Select "Electron" browser
- Select "Continue"
- Select "Scaffold example specs"
- Close all Cypress windows

Test that scaffolded specs run:

```shell
npm test
```
---

**Comment by jennifer-shehane** [comment] 2024-06-05 14:55
Duplicate of https://github.com/cypress-io/cypress/issues/619

**Closed as not planned by jennifer-shehane** 2024-06-05 14:55 UTC
Labels: type: duplicate

**Comment by MikeMcC399** [comment] 2024-06-05 15:19
@jennifer-shehane 

> - Duplicate of #619

Sorry I missed that one in my search!
