### ISSUE TITLE
Should have text assertion passed even when the text was different

### ISSUE THREAD

**Issue by Swati-activeops** [cypress-io/cypress#15176] opened 2021-02-22 13:28 UTC
### Current behavior
![image](https://user-images.githubusercontent.com/50127497/108713861-b4e89500-7510-11eb-9197-92b0b0ea03c6.png)
![image](https://user-images.githubusercontent.com/50127497/108713950-d2b5fa00-7510-11eb-8d19-a032746ee094.png)

It does fail if I change the expected text to this :
![image](https://user-images.githubusercontent.com/50127497/108714434-6e476a80-7511-11eb-87de-74009330ea09.png)

### Versions
 6.5.0

**Comment by jennifer-shehane** [comment] 2021-02-23 00:36
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

I tried to reproduce with the simplest example from the info provided and cannot reproduce. 

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('div').should('have.text', '0.0')
})
```

```html
<body>
<div>0.8</div>
</body>
```

<img width="689" alt="Screen Shot 2021-02-22 at 7 35 22 PM" src="https://user-images.githubusercontent.com/1271364/108788146-4ffb6200-7545-11eb-97c8-056614451041.png">

**Comment by jennifer-shehane** [comment] 2021-02-27 00:14
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-27 00:14 UTC
Labels: stage: needs information
