### ISSUE TITLE
Cypress.config('baseUrl', ...) applies to the "cypress browser" and not the actual browser

### ISSUE THREAD

**Issue by terencechow** [cypress-io/cypress#5137] opened 2019-09-12 21:03 UTC
### Current behavior:

Using `Cypress.config('baseUrl', '...')` updates the "cypress" browser as opposed to the real browser. In combination with an application making a redirect with `window.location`, this results in using the browser baseUrl. However the expectation is that the redirect would use the "cypress" browser url.

### Desired behavior:
`Cypress.config('baseUrl', '...')` should set the baseUrl in the browser not the 'cypress browser'.

### Steps to reproduce: (app code and test code)

1. have a config.json that has the following:
```
{
  "baseUrl": "https://first-subdomain.someurl.com"
}
```
2. In a test, update the baseUrl in a before block

```
...
before(() => Cypress.config('baseUrl', 'https://other-subdomain.someurl.com'))
...
```

3. Have an application that visits the `/login` page of your app and types a password and email. It will login and authenticate with `other-subdomain-staging.wealthsimple.com`

4. Have your application then do a `window.location.assign('/some-relative-path')` after signing up. Make your test pass if it gets to that page.

5. Now run the cypress test and the application will redirect to `first-subdomain.someurl.com/some-relative-path`

However because we just authenticated at `other-subdomain` there are no cookies with `first-subdomain`. This causes the redirect to 401, causing the test to fail. However if you try the same test with the baseUrl in step 1 set to `other-subdomain.someurl.com`, everything passes.

### Versions

cypress 3.2

**Comment by jennifer-shehane** [comment] 2019-09-19 21:39
@terencechow Can you provide the Cypress test code and application code to run this - as described?

**Comment by sainthkh** [comment] 2020-12-29 07:37
Close this because it's old and doesn't have a reproducible example. If the problem is still happening, please open a new issue with a reproducible example.

**Closed by sainthkh** 2020-12-29 07:37 UTC
