### ISSUE TITLE
Cypress errors when an undefined exception is raised on another origin

### ISSUE THREAD

**Issue by michaelkay-wrisk** [cypress-io/cypress#29334] opened 2024-04-15 11:25 UTC
### Current behavior

When running automated tests against Stripe, they currently raise an error of `undefined` which does not hit `uncaught:exception` and fails the test instead with message:

```
Cannot read properties of undefined (reading 'message')
```

### Desired behavior

Cypress should cater for when the error being raised is `undefined` (and probably when `message` is not defined as well if it doesn't already)

### Test code to reproduce

Any E2E test running against Stripe

### Cypress Version

13.7.3

### Node version

18.14.2

### Operating System

macOS

### Other

This is definitely a problem with Stripe in doing something it shouldn't so I understand this is not a case that would normally happen but would be great if Cypress handled this edge case without error.

**Comment by michaelkay-wrisk** [comment] 2024-04-15 11:26
Please see https://github.com/cypress-io/cypress/issues/23937#issuecomment-2053613129 for further discussion on a closed Issue

**Comment by jennifer-shehane** [comment] 2024-04-16 13:54
I'll close this as a duplicate of https://github.com/cypress-io/cypress/issues/23937 which has been reopened

**Closed as not planned by jennifer-shehane** 2024-04-16 13:54 UTC
Labels: type: duplicate
