### ISSUE TITLE
"type()" function execute more and more slowly.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#8669] opened 2020-09-25 03:47 UTC
### Current behavior
When run a long time test case, "type()" function execute more and more slowly.

In the being:

![beginning](https://user-images.githubusercontent.com/22906174/94224314-9318c100-ff24-11ea-8846-a34919147826.gif)

In the end:

![ending](https://user-images.githubusercontent.com/22906174/94224103-200f4a80-ff24-11ea-80a2-8deb52bbfbcb.gif)

Completed video:
[TestResolveGroup.ts.mp4.zip](https://github.com/cypress-io/cypress/files/5280477/TestResolveGroup.ts.mp4.zip)

### Desired behavior
Execute speed like beginning.

### Versions
Cypress 5.1.0
MacOS 10.15.4
Chrome  85.0.4183.102

**Comment by bahmutov** [comment] 2020-09-25 13:13
Does it happen with "simple" text field and and running type there for 400 times? Can you measure timings per command like we have done in https://www.cypress.io/blog/2020/05/22/where-does-the-test-spend-its-time/

**Comment by JFRabbit** [comment] 2020-09-27 04:15
@bahmutov 

> Does it happen with "simple" text field and and running type there for 400 times?

With simple text, but running type only 36 times. 

elements like:

```html
<!-- antd input-->
<input data-v-602608bc="" placeholder="请输入Category名称" type="text" class="ant-input">
```

test code with:
``` typescript
export function input(placeholder: string, text: string): void {
  cy.get(`input[placeholder=${placeholder}]`)
    .clear()
    .type(text, { force: true });
}
```

and
```html
<!-- antd form item-->
<div data-v-7e36b91e="" class="ant-row ant-form-item">
  <div class="ant-col ant-form-item-label">
    <label title="名称" class="ant-form-item-required">名称</label>
  </div><div class="ant-col ant-form-item-control-wrapper">
  <div class="ant-form-item-control">
    <span class="ant-form-item-children">
      <input data-v-7e36b91e="" type="text" class="ant-input">
    </span>
  </div>
</div>
```

test code with:
``` typescript
export function formInput(option: Cypress.FormOption) {
  const { label: key, input: target } = option;
  cy.get("label")
    .contains(key)
    .parent()
    .parent()
    .find("input")
    .clear()
    .type(target, { force: true });
}
```

> Can you measure timings per command like we have done in https://www.cypress.io/blog/2020/05/22/where-does-the-test-spend-its-time/

in the beginning of test case, type text like: "Test_7ba81ee0_Category", spend less than 200ms

<img width="1792" alt="截屏2020-09-27 上午11 53 51" src="https://user-images.githubusercontent.com/22906174/94355647-6a293500-00b8-11eb-9a38-e8558018873a.png">

and spend time more and more slowly, even type one letter used 500 ms

in the ending of test case, type text like: "Test_fcdd1f6a_rc", spend more an 2 sec.
<img width="1791" alt="截屏2020-09-27 上午11 53 05" src="https://user-images.githubusercontent.com/22906174/94355665-89c05d80-00b8-11eb-8750-e3b57c5bb258.png">

**Comment by jennifer-shehane** [comment] 2020-12-17 09:45
I'm not able to reproduce this issue with the examples provided. The typing does not slow down over time.

I suspect that there is something else involved in the slowdown that is a larger part of your app/tests. It may be a duplicate of this https://github.com/cypress-io/cypress/issues/6783 where XHRs are performed in between type that cause type to slow down over time.

Examples I tried that showed no slowdown:

`index.html`

```html
<html>
<body>
  <input data-v-602608bc="" placeholder="请输入Category名称" type="text" class="ant-input">
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html');

  for (let i = 0; i < 300; i++) {
    cy.get(`input[placeholder=请输入Category名称]`)
      .clear()
      .type('Test_7ba81ee0_Category', { force: true });
  }

})
```

`index.html`

```html
<html>
<body>
  <div data-v-7e36b91e="" class="ant-row ant-form-item">
    <div class="ant-col ant-form-item-label">
      <label title="名称" class="ant-form-item-required">名称</label>
    </div>
    <div class="ant-col ant-form-item-control-wrapper">
      <div class="ant-form-item-control">
        <span class="ant-form-item-children">
          <input data-v-7e36b91e="" type="text" class="ant-input">
        </span>
      </div>
    </div>
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html');

  for (let i = 0; i < 300; i++) {
    cy.get("label")
      .contains('名称')
      .parent()
      .parent()
      .find("input")
      .clear()
      .type('Test_7ba81ee0_Category', { force: true });
  }
})
```

Right now there isn't to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-12-17 09:45 UTC
Labels: stage: needs information, type: performance 🏃‍♀️
