### ISSUE TITLE
Cypress -Webkit does not support  open browser when {failOnStatusCode: false}

### ISSUE THREAD

**Issue by Anshita-Bhasin** [cypress-io/cypress#23866] opened 2022-09-18 15:25 UTC
### Current behavior

When we try to open the .feature file in WebKit.. It returns a type error while it works fine for .js files.

If you have BDD + Cypress configured, WebKit will not work.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/10338077/190913493-073486b2-3dfc-4ced-b116-bce0e2df3c82.png">

### Desired behavior

Should work fine like other browsers

Below is the screenshot from .js file (WebKit)

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/10338077/190914292-a6af296f-02b0-4f04-8a20-dbeb16abf37e.png">

### Test code to reproduce

1. Create Cucumber + Cypress Framework
2. Run .feature file , select Webkit as browser

Expected : url should open in safari browser

### Cypress Version

10.8.0

### Node version

v16.17.0

### Operating System

12.5.1

**Comment by Anshita-Bhasin** [comment] 2022-09-18 15:34
Webkit

**Comment by nagash77** [comment] 2022-09-19 18:23
@Anshita-Bhasin I see that you closed this issue.  Are you still experiencing this issue?  Can you please provide code that reproduces the the problem?  This should include the .feature file.  The repo might also help - https://github.com/badeball/cypress-cucumber-preprocessor

**Comment by flotwig** [comment] 2022-09-21 14:03
@Anshita-Bhasin I believe this is a duplicate of #23832, closing for now.

**Closed as completed by flotwig** 2022-09-21 14:03 UTC
Labels: browser: webkit, experiment: webkit
