### ISSUE TITLE
Option to auto-minimize/hide launchpad if --e2e and --browser is passed

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#28837] opened 2024-01-31 19:32 UTC
### What would you like?

It would be nice to have an option to hide or minimize the launchpad if `--e2e` or `--component` is passed to the `cypress open` command. 

So instead of both of these windows being opened: 
<img width="1437" alt="image" src="https://github.com/cypress-io/cypress/assets/2730609/8dd383a8-b7d9-4d59-8b0a-a405ffeae07b">

Just the spec runner would show up and the "launchpad" would be minimized.

**Comment by jennifer-shehane** [comment] 2024-01-31 20:59
Duplicate of https://github.com/cypress-io/cypress/issues/28313. I suppose 'minimizing' it is an approach, but then we'd have to also implement the logic to unminimize and bring to focus the launchpad in the situation were there is an error to display, like config or something fundamentally broken. 

We did discuss this idea a lot when we implemented v10 for what its worth because we agree it would be ideal.

**Closed as not planned by jennifer-shehane** 2024-01-31 20:59 UTC
Labels: type: duplicate
