### ISSUE TITLE
On entering a value in a field, the value is automatically cleared when executed from command line

### ISSUE THREAD

**Issue by VSathyamoorthy** [cypress-io/cypress#3059] opened 2019-01-04 03:32 UTC
### Current behavior:

Entering a value in a field in modal, but it automatically changed back to 0

### Desired behavior:

The entered value should remain

### Steps to reproduce: (app code and test code)

- run the test in command line 
- the test should be opening a modal which has field to enter value and save the modal
- the entered value is getting reset to 0 automatically

```js
context('apex', () => {
   beforeEach(() => {
       cy.loginViaApi();
       cy.viewport(1280, 800);
       cy.visit('/');
   });

   afterEach(() => {
       cy.visit('/home/logoff');
   });

   it('stageTotal', () => {
       const inputIR = 9000
       cy.visit('/opportunities/main');
       //cy.wait(5000);
      cy.get('.i-card__menu__ellipsis-btn__header')
           .first()
           .click();
       cy.contains('.i-dropdown__menu__item', 'Edit').click();
       cy.get('.potential-revenue__initial .i-input').clear();
       cy.get('.create-opportunity__footer__create').click();
       cy.reload()
       cy.get('.i-label .i-input')
           .eq(0)
           .invoke('val')
           .as ('totalIR')
       cy.get('.i-card__menu__ellipsis-btn__header')
           .first()
           .click();
       cy.contains('.i-dropdown__menu__item', 'Edit').click();
       cy.get('.potential-revenue__initial .i-input')
           .type(inputIR)
       cy.wait(1000)
       cy.get('.create-opportunity__footer__create').click();
       cy.reload()
       cy.get('@totalIR').then(totalIR => {
           const convertAsNum = Number(totalIR.replace(/[^0-9]+/g,""))
           const totalIRAsNum = convertAsNum +inputIR
           cy.get('.i-label .i-input')
           .eq(0)
           .should('have.value', '$ '+ totalIRAsNum );
       });
   });
});
```

**Look at the attached ZIP files which contains the video recorded (look for around 30-33 secods)**

[hubs_opportunities_stage_total.js.zip](https://github.com/cypress-io/cypress/files/2725964/hubs_opportunities_stage_total.js.zip)

### Versions

OS: Windows 10
Browser: Electron 59.0.3071.115
Cypress:v3.1.3

**Comment by jennifer-shehane** [comment] 2019-01-04 15:46
In your case there are not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next action.

As you can see in this frame of the video, the `.type()` in Cypress happens so quickly that the XHR for the user data has not finished loading, when that XHR finishes - it wipes out the previously typed data with the fresh user data. 

**While it's typing**
<img width="1392" alt="screen shot 2019-01-04 at 9 59 11 pm" src="https://user-images.githubusercontent.com/1271364/50696528-123dd580-106e-11e9-9981-1575fee79e9e.png">

**When the XHR loads after typing**
<img width="1392" alt="screen shot 2019-01-04 at 9 59 21 pm" src="https://user-images.githubusercontent.com/1271364/50696552-21248800-106e-11e9-9eb9-531eb64bb83d.png">

You'll need to be more thoughtful in asserting that the state of the DOM is ready for you to take action. In this case setting up a `cy.route()` and `cy.wait()` before initiating the type.

I'm closing this issue, as this is not a bug within Cypress. If you have any more questions about testing strategies, try asking in our [community chat](https://gitter.im/cypress-io/cypress)

**Closed by jennifer-shehane** 2019-01-04 15:46 UTC
