### ISSUE TITLE
ParseError: Unexpected token for fixture JSON values

### ISSUE THREAD

**Issue by poponuts** [cypress-io/cypress#7003] opened 2020-04-14 06:16 UTC
### Current behavior:
After updating to 4.4.0, when running via CI (TeamCity) or Cypress runner, I get the following error:
```
..\cypress\fixtures\statuses.json:2
    "status";
                  ^
ParseError: Unexpected token

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

A missing file or dependency
A syntax error in the file or one of its dependencies
```

### Desired behavior:
The tests should run as the JSON format of the fixture file is correct. It runs smoothly in version 4.3.0. The fixture JSON file looks like this and no error in the IDE:
```js
{
  "status": {
    "description": "submitted"
 }
} 
```

The compilation must have changed the colon (:) to semi-colon (;)

### Test code to reproduce
**../cypress/fixtures/statuses.json:**
```js
{
  "status": {
    "description": "submitted"
 }
} 
```
**../cypress/tests/CheckStatus.js:**
```js
import {status} from '../fixtures/statuses'
﻿describe('test this', ()=> {
    it('test this', () => {
        cy.log(status.description);
    });
});
```

### Versions
Cypress 4.4.0
Run on Windows 10 in local machine
Run on Linux in TeamCity (CI)

**Comment by jennifer-shehane** [comment] 2020-04-14 06:52
I am not encountering this error when running the fixture + test code provided within 4.3.0 or 4.4.0 of Cypress by itself. 

Are you using any other Cypress plugins in your project or any other code in your plugins/support file that I may need to reproduce the error?

**Comment by poponuts** [comment] 2020-04-14 08:06
Hi @jennifer-shehane  I have the following plugins:
```
import '@bahmutov/cy-api/support'
import 'cypress-file-upload'
import 'cypress-localstorage-commands'
```

Also, my `../support/index.js` includes the following:
```
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from failing the test
    return false
});
```

Lastly, my `package.json` contains the following:
```
{
  "name": "tests-cypress",
  "version": "1.0.0",
  "dependencies": {
    "fs-extra": "^8.1.0",
    "path": "^0.12.7"
  },
  "devDependencies": {
    "@bahmutov/cy-api": "^1.4.2",
    "aws-sdk": "^2.632.0",
    "cypress": "^4.4.0",
    "cypress-file-upload": "^4.0.4",
    "cypress-localstorage-commands": "^1.1.7",
    "cypress-sql-server": "^1.0.0",
    "cypress-teamcity-reporter": "^2.6.1",
    "faker": "^4.1.0",
    "mocha": "^6.2.2",
    "mocha-junit-reporter": "^1.23.1",
    "uuid": "^3.3.3"
  },
  "scripts": {
    "cy:run": "node scripts/cypress.js"
  }
}
```

**Comment by jennifer-shehane** [comment] 2020-04-14 08:12
Yah, I'm not able to reproduce this with the added plugins either. I'm running it on MacOS Catalina in Chrome 80. Have you ran the exact code you provided? The one below exactly?

`statuses.json`

```json
{
  "status": {
    "description": "submitted"
  }
}
```

`spec.js`

```js
import { status } from '../fixtures/statuses'

describe('test this', () => {
  it('test this', () => {
    cy.log(status.description);
  });
});
```

<img width="532" alt="Screen Shot 2020-04-14 at 2 41 49 PM" src="https://user-images.githubusercontent.com/1271364/79201430-173b2880-7e5e-11ea-89e9-6dd1fe4908c6.png">

**Comment by poponuts** [comment] 2020-04-14 11:51
Hi @jennifer-shehane yes, I have run it exactly like that. See below in 4.4.0:

![2020-04-14_21-42-15](https://user-images.githubusercontent.com/36245304/79221620-82562080-7e99-11ea-85b4-f8e7b00488c4.jpg)

I have rolled back to 4.3.0 and it works fine:
![2020-04-14_21-44-54](https://user-images.githubusercontent.com/36245304/79221627-85e9a780-7e99-11ea-8fc5-b54bae05ac45.jpg)

I am using a Windows 10 Enterprise version 1903. However, I run this via Teamcity Linux agent and same issue. 

I am not sure if this will help find the root cause, but the following in `package-lock.json` were automatically changed from upgrading as well:
```
"mkdirp": "0.5.5"
"rxjs": "6.5.5"
```

**Comment by marlenemaiobarroso12** [comment] 2020-05-22 16:43
Hello,

Happens the same with me. Very similar....

But I think that cames from:

```
const {SwaggerValidation} = require('@jc21/cypress-swagger-validation');
module.exports = (on, config) => {
    on('task', SwaggerValidation(config));
    return config;
};

on index.ts plugin file.
```

**Comment by jennifer-shehane** [comment] 2020-08-28 09:25
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-28 09:25 UTC
Labels: stage: needs information
