### ISSUE TITLE
Cypress can't open salesforce login page

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [cypress-io/cypress#692] opened 2017-09-25 15:41 UTC
- Operating System: MacOS
- Cypress Version: 0.19.4
- Browser Version: 

### Is this a Feature or Bug?
Bug

### Current behavior:
The browser get's redirected to a blank page

### Desired behavior:
Should visit the salesforce login page

### How to reproduce:
Run `salesforce_spec.js`

### Repo
https://github.com/GuilhermeMedeiros/cypress-salesforce

**Comment by brian-mann** [comment] 2018-03-09 17:51
This was actually fixed in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).

Logging into Salesforce works now.

**Closed by brian-mann** 2018-03-09 17:51 UTC
Labels: type: bug

**Comment by AlanGDC** [comment] 2018-08-14 12:59
Hi!, sorry to bother you, i was looking for automate a SalesForce page with cypress but i im getting the same issue about the login in sf, i have the last version (3.3.0 i think) i was wondering if you were able to fix the login with salesforce

**Comment by jennifer-shehane** [comment] 2018-08-15 20:56
This issue as described above is working in Cypress version 3.1.0 - with this being the test case:

```js
describe("Salesforce", function() {
    it("opens the login page", function() {
        cy.visit("https://login.salesforce.com/");
    });
});
```

@AlanGDC I would suggest opening a new issue and giving a reproducible example of the issue you are having.

**Comment by simonmagabe** [comment] 2018-12-04 23:57
@jennifer-shehane After entering the login credentials and hit submit the "Whoops, there is no test to run" message is displayed.
Here is my code:

`describe("Salesforce", function() {
    it("opens the login page", function() {
        cy.visit("https://login.salesforce.com/");
    });
    it('Log in to Salesforce', function() {
        cy.get('#username').type('xxxxx@xxxxx.xxx.xxx')
        cy.get('#password').type('xxxxxxxxx')
        cy.get('#Login').click()
    })
});`

What am I doing wrong? I really need help with this. Thanks.

**Comment by jennifer-shehane** [comment] 2018-12-05 06:18
Hey @simonmagabe can you open a [new issue](https://github.com/cypress-io/cypress/issues/new?template=bug_report.md) for this - as this results in a different error message than this issue. I am indeed able to reproduce this issue, so it looks like a bug.

**Comment by samuel012** [comment] 2020-02-10 10:45
To those redirected here, this might be a viable solution:

https://github.com/cypress-io/cypress/issues/2367#issuecomment-584058927
