### ISSUE TITLE
  > Error: write EPROTO 140380046106824:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

### ISSUE THREAD

**Issue by 1412904892** [cypress-io/cypress#9188] opened 2020-11-13 03:03 UTC
Current behavior
A few minutes ago, I can run the demo, and I add some code to it, I can't run the demo, and I get the ERROR like this:

  > Error: write EPROTO 140380046106824:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

I delete my code in the demo which can't run too.

cypress version 5.6.0

**Comment by jennifer-shehane** [comment] 2020-11-16 02:05
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-11-16 02:05 UTC

**Comment by abhishek-singh-21** [comment] 2020-11-24 08:31
I am getting this error upon requesting response from express server.
Error: write EPROTO 47742220895112:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

**Comment by lukazohar** [comment] 2020-12-01 22:01
Had the same thing just now. The problem was that I was trying to access my API with SSL "https://localhost......." instead of "http://localhost:.......".

**Comment by ZnK88** [comment] 2020-12-02 07:27
> J'ai eu la même chose tout à l'heure. Le problème était que j'essayais d'accéder à mon API avec SSL " [https: // localhost](https://localhost) ......." au lieu de " [http: // localhost](http://localhost) : .......".

Thx !

**Comment by mittu80** [comment] 2025-06-28 07:56
Had the same issue now, write PROTO 1009216:error:100000f7:SSL....tls_record.cc:211 as i tried oepning with "http://localhost" but it tries to open with "https.." ( also the same with chromeWebSecurity: false".  additional info what i observed : i tried a single  same test run directly as .spec.cy.js and use a feature file with step file as spec.cy.js. in the first case (no cucumber) i could pass the test using http://localhost but not with feature file. I use the following @bahmutov @badeball packages in my config could we repoen this issue if its related?
