### ISSUE TITLE
Keep getting constant Error: Still waiting to connect to Edge, retrying in 1 second

### ISSUE THREAD

**Issue by CloneOfAlex** [cypress-io/cypress#28103] opened 2023-10-20 18:39 UTC
### Current behavior

When running tests in GitHub Actions 
Keep getting constant Error: Still waiting to connect to Edge, retrying in 1 second

This behavior began around 48 hours ago

![image](https://github.com/cypress-io/cypress/assets/135152564/6ea43fd5-b9a4-48b8-88b3-dfe9f47fef71)

```
19s
DevTools listening on ws://12[7](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:7).0.0.1:33475/devtools/browser/dd527eb[8](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:8)-bf[9](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:9)9-479a-84bb-4ddc20f0d875
[1745:[10](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:10)20/123626.443847:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type: 
Displaying Cypress info...
Detected 4 browsers installed:
1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: [11](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:11)8.0.5993.70
  - Executable: google-chrome
2. Chromium
  - Name: chromium
  - Channel: stable
  - Version: 118.0.5993.0
  - Executable: chromium-browser
3. Edge
  - Name: edge
  - Channel: stable
  - Version: 118.0.2088.46
  - Executable: microsoft-edge
4. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 118.0.2
  - Executable: firefox
Note: to run these browsers, pass <name>:<channel> to the '--browser' field
Examples:
- cypress run --browser firefox
- cypress run --browser chrome
Learn More: https://on.cypress.io/launching-browsers
Proxy Settings: none detected
Environment Variables: none detected
Application Data: /home/runner/.config/cypress/cy/development
Browser Profiles: /home/runner/.config/cypress/cy/development/browsers
Binary Caches: /home/runner/.cache/Cypress
Cypress Version: [13](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:13).3.2 (stable)
System Platform: linux (Ubuntu - [22](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:22).04)
System Memory: 7.[26](https://github.com/Foundant/cypress-tests/actions/runs/6591472100/job/17910117529#step:4:26) GB free 6.06 GB
```

### Desired behavior

We expect for browser to be found and tests to run - same way as it did 48 hour ago ..

### Test code to reproduce

cant share at this time 

### Cypress Version

13.3.2

### Node version

20.5

### Operating System

ubuntu latest

### Debug Logs

```shell
19s
DevTools listening on ws://127.0.0.1:33475/devtools/browser/dd527eb8-bf99-479a-84bb-4ddc20f0d875
[1745:1020/123626.443847:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type: 
Displaying Cypress info...
Detected 4 browsers installed:
1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 118.0.5993.70
  - Executable: google-chrome
2. Chromium
  - Name: chromium
  - Channel: stable
  - Version: 118.0.5993.0
  - Executable: chromium-browser
3. Edge
  - Name: edge
  - Channel: stable
  - Version: 118.0.2088.46
  - Executable: microsoft-edge
4. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 118.0.2
  - Executable: firefox
Note: to run these browsers, pass <name>:<channel> to the '--browser' field
Examples:
- cypress run --browser firefox
- cypress run --browser chrome
Learn More: https://on.cypress.io/launching-browsers
Proxy Settings: none detected
Environment Variables: none detected
Application Data: /home/runner/.config/cypress/cy/development
Browser Profiles: /home/runner/.config/cypress/cy/development/browsers
Binary Caches: /home/runner/.cache/Cypress
Cypress Version: 13.3.2 (stable)
System Platform: linux (Ubuntu - 22.04)
System Memory: 7.26 GB free 6.06 GB
```

**Comment by MikeMcC399** [comment] 2023-10-20 19:32
@CloneOfAlex 

We're seeing delays in CI on https://github.com/cypress-io/github-action/actions/workflows/example-edge.yml using Edge

for example https://github.com/cypress-io/github-action/actions/runs/6589879261/job/17905293268 on 

https://github.com/actions/runner-images/blob/ubuntu22/20231016.1/images/linux/Ubuntu2204-Readme.md which merged 2 days ago and bumped Microsoft Edge  from `117.0.2045.47` to `118.0.2088.46` on `ubuntu-22.04` (aka `ubuntu-latest`)

![image](https://github.com/cypress-io/cypress/assets/66998419/a06ddf06-0fc2-459a-a251-b2fe642c79cf)

![image](https://github.com/cypress-io/cypress/assets/66998419/7b64f4f0-5f60-4096-878e-bf1350f85edf)

I assume this is related. There doesn't seem to be any difference between Cypress `13.3.1` in this run and `13.3.2` which I also tried out (hasn't been merged yet - waiting for PR https://github.com/cypress-io/github-action/pull/1061).

Connection problems to Edge have been going on for a while. In the `github-action` repo they have however generally not led to test failure.

**Comment by MikeMcC399** [comment] 2023-10-23 07:11
@CloneOfAlex 

I'm seeing Edge also slow to start on a local Ubuntu 22.04 machine, although in a second Cypress test in the same session there are no waiting messages shown.

I can't reproduce the issue that the connection from Cypress to Edge fails completely. I only see it slow to connect, which makes me think it may be a performance issue.

I also noticed on GitHub that running in a Cypress container there were no waiting messages. I can't say it that would workaround your issue, but you might like to just try it out, for instance:

```yaml
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.6.1-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
```

**Comment by MikeMcC399** [comment] 2023-10-23 09:34
- This is a duplicate of issue https://github.com/cypress-io/cypress/issues/27830

**Closed as completed** 2023-11-02 18:45 UTC
Labels: type: duplicate

**Comment by CloneOfAlex** [comment] 2023-11-03 15:31
How is this completed - problem with Edge is still real and we dont have issues with Chrome BTW

**Comment by jennifer-shehane** [comment] 2023-11-28 19:24
This was closed as a duplicate.
