### ISSUE TITLE
Flaky test: Timed out retrying after 250ms: Target cannot be null or undefined.

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23437] opened 2022-08-18 17:26 UTC
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/analytics/flaky-tests/56ff5c54-3c68-affc-d950-07a1afacd807-feea373b-9a0f-0ccd-2b49-8863d3c54097?branches=%5B%7B%22label%22%3A%22skip-or-fix-flaky-tests-2%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22skip-or-fix-flaky-tests-2%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222022-08-18%22%2C%22endDate%22%3A%222022-08-18%22%7D&viewBy=TEST_CASE

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts#L51

### Analysis

<img width="439" alt="Screen Shot 2022-08-18 at 10 26 43 AM" src="https://user-images.githubusercontent.com/26726429/185457491-1c84bfbd-42be-4f1d-a075-0e4f07d232f6.png">

Very rare flake
<img width="427" alt="Screen Shot 2022-08-18 at 10 26 02 AM" src="https://user-images.githubusercontent.com/26726429/185457303-ad6d8034-ef42-402d-80cd-cb4e7ea5dbce.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by flotwig** [comment] 2023-02-01 22:32
cy.route was removed in 12, closing

**Comment by flotwig** [comment] 2023-02-01 22:32
oh whoops, this isn't a cy.route issue anyways

**Comment by flotwig** [comment] 2023-02-01 22:41
Since this is no longer a separate mechanism for XHRs and fetches, closing this as a duplicate of #23840

**Closed by flotwig** 2023-02-01 22:41 UTC
Labels: process: flaky test, topic: cross-origin ⤭, topic: flake ❄️, routed-to-e2e
