### ISSUE TITLE
Running .should('have.attr', 'target') and then .invoke('removeAttr', 'target') fails.

### ISSUE THREAD

**Issue by mylastore** [cypress-io/cypress#8552] opened 2020-09-11 01:25 UTC
### Current behavior:
Running `.should('have.attr', 'target)` and right after I run `.invoke('removeAttr', 'target')` will failed.

![cypress-should](https://user-images.githubusercontent.com/8906338/92837140-12898a80-f392-11ea-8763-68a74bd90f09.png)

### Desired behavior:

Should run the check if attribute target exist and I should be able to remove it after. 

### Test code to reproduce
```
it.only('has a link to application author', () => {
  cy
      .get('.my-link')
      .should('have.attr', 'target')
      .invoke('removeAttr', 'target')
});

```
### Versions
Cypress: "cypress": "^5.1.0
OS: Ubuntu 20.04.1 LTS
Browser: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by nicholaschiang** [comment] 2020-09-28 22:13
Fixing this, however, might result in a breaking change.

For example, I'm currently using this bug to check if an image's `src` attribute changes:
```typescript
    cy.get('@account-header').find('img').as('profile-img').should('have.attr', 'src').as('profile-photo');

    cy.contains('Your profile photo')
      .as('photo-input')
      .children('input')
      .should('have.attr', 'type', 'file')
      .attachFile('users/student.jpg');
    cy.get('@photo-input')
      .next()
      .as('photo-input-label')
      .should('have.text', 'Uploading student.jpg...');

    cy.wait('@upload-photo');

    cy.get('@photo-input-label').should('have.text', 'Uploaded student.jpg.');
    cy.get('@profile-img').should('have.attr', 'src').then((src: unknown) => {
      cy.get('@profile-img-src').then((originalSrc: unknown) => {
        expect(src as string).to.not.equal(originalSrc as string);
      });
    });
```

The code above is doing the following:
1. Getting the current `src` for the user's profile photo.
2. Updating the profile photo using a "Your profile photo" input.
3. Checking that the profile photo `src` has also changed.

And it only works because of this bug where `have.attr` assertions return the attribute value instead of the `HTMLElement`.

**Comment by bahmutov** [comment] 2020-09-28 22:39
A few assertions do change the subject (unfortunately it is convenient, but is an exception), see the examples in https://github.com/bahmutov/cypress-examples/commit/5bdc5ac148bed9a15e981d1b49b31ac7c65cf267

**Comment by bahmutov** [comment] 2020-09-29 03:01
A few more tested examples for changing the subject in the few assertions is here https://glebbahmutov.com/cypress-examples/commands/assertions.html#subject

Maybe I should add them to the docs @jennifer-shehane

**Comment by nicholaschiang** [comment] 2020-09-29 17:51
Yeah, add that to the [assertions reference](https://docs.cypress.io/guides/references/assertions.html#) (it seems like you're already mentioning it [here](https://docs.cypress.io/api/commands/should.html#Yields)). Otherwise, this seems like a bug and can be confusing.

Also, you should update the Typescript types to reflect this. Right now, chaining a `.then()` off of a `.should()` expects an `HTMLElement`:

```typescript
cy.get('#hello').should('have.attr', 'id').then((attr: string) => { // This errors because it's typed as an `HTMLElement` not `string`
  // Do something with that `attr`
});
```

**Comment by jennifer-shehane** [comment] 2020-10-15 00:29
This is expected behavior. Some assertions change the subject for future chaining. 

You’re welcome to create a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document this. Our documentation is open source and contributions are welcome. 

Closing here as this is not a bug in the product.

**Closed by jennifer-shehane** 2020-10-15 00:29 UTC

**Comment by jpierson-at-riis** [comment] 2022-08-02 15:58
@bahmutov, @jennifer-shehane I'd agree about updating the docs. I've run into this and in the process of confirm it ran into more StackOverflow questions regarding this behavior as well which points to people who are thrown off about this behavior that has a lack of documentation. To be clear the documentation actually states something somewhat contrary to reality currently.

Ex.
> Note that all chained assertions will use the same reference to the original subject.

This is confusing because in the documentation site I also was able to find the [explanation in should.md](https://github.com/cypress-io/cypress-documentation/blob/770dee0b41fe0427d687418d443f2a4af68a6bb0/content/api/commands/should.md?plain=1#L147-L148) elsewhere but I don't know where this translates too because it doesn't seem to be in the documentation for `should()`.

> **Note:** the `have.attr` assertion changes the subject from the original
element to the attribute's value.

It seems that there are some inconsistencies in these explanations which warrant some adjustment. Personally I'm not familiar enough with the documentation repo or the nuances in these behaviors to confidently propose a change though.

**Comment by jpierson-at-riis** [comment] 2022-08-02 16:00
Neverminded, I found it.
![image](https://user-images.githubusercontent.com/77620925/182419795-fdd5ad2c-f05e-4461-a516-177997f696db.png)

**Comment by jpierson-at-riis** [comment] 2022-08-02 16:06
It may still be worth while adjusting the claim that "all chained assertions will use the same reference to the original subject." It would also be nice to have a short definitive list of the chainers that do or do not return the original subject perhaps in a table if that is a known list.
