### ISSUE TITLE
Cypress: Getting The task 'gmail:get-messages' returned undefined. in Cypress 10 but its working on older version of cypress

### ISSUE THREAD

**Issue by VaghasiyaKrupal** [cypress-io/cypress#23196] opened 2022-08-08 15:58 UTC
### Current behavior

I am using cypress `gmail-tester`. I have updated cypress to `10` or above version and `gmail-tester` return the below error.
```
cy.task('gmail:get-messages') failed with the following error:

The task 'gmail:get-messages' returned undefined. You must return a value, null, or a promise that resolves to a value or null to indicate that the task was handled.

The task handler was:

async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      console.log(messages);
      return messages;
    }

Fix this in your setupNodeEvents method here:
/home/krupal/Desktop/Cypress Automation/RebelBase/cypress.config.js
```
In cypress's older version it's working fine.

Here is my `plugin/index.js` file
```
/// <reference types="Cypress" />
const debug = require("debug");
const path = require("path");

const gmail_tester = require("gmail-tester");

const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
  
  on("task", {
    "gmail:get-messages": async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      console.log(messages);
      return messages;
    }
  });

  on("task", { "setUserId": (val) => { return (userId = val); } });

  on("task", { "getUserId": () => { return userId; } });
};
```
And here is my `cypress.config.js` file
```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config)
    },
    baseUrl: 'https://app.dev.rebelbase.co',
    experimentalSessionAndOrigin: true,
    specPattern: 'cypress/integration/**/*.feature',
  },
})
```
And in my test I have used like...
```
cy.task("gmail:get-messages", {
    options: {
      from: "noreply@rebelbase.co",
      subject: "Join CypressTestProject01 team on RebelBase",
      include_body: true,
      // before: new Date(2021, 9, 24, 12, 31, 13), // Before September 24rd, 2019 12:31:13
      //  after: new Date(2021, 7, 23) // After August 23, 2019
    }
  }).then(emails => {
    assert.isAtLeast(
      emails.length,
      1,
      "Expected to find at least one email, but none were found!"
    );
    const body = emails[0].body.html;
    console.log(body)
    cy.log(body);

    assert.isTrue(
      body.indexOf(
        "/auth/sign-up?type=project_invitation&amp;token="
      ) >= 0,
      "Found link!"
    );

    window.token = extractData(body, startStr, endStr);

    cy.visit(
      `auth/sign-up?type=project_invitation&token=${token}&email=${randomEmail8}`
    );
  })
```

### Test code to reproduce

Clone https://github.com/VaghasiyaKrupal/cucumber-issue.git
cd cucumber-issue
install dependency using `npm install`
Open cypress: `npx cypress open`
Run the `Signup.feature` file

### Cypress Version

10.1.0

**Comment by emilyrohrbough** [comment] 2022-08-08 16:22
@VaghasiyaKrupal Thanks for logging this issue! This appears to be the same issue as #5240. I am going to close this as a duplicate. Please follow the existing issue for updated.

**Closed by emilyrohrbough** 2022-08-08 16:22 UTC

**Comment by VaghasiyaKrupal** [comment] 2022-08-08 16:28
@emilyrohrbough I think this should be different issue

**Comment by DarynaMinko** [comment] 2022-09-14 09:33
@VaghasiyaKrupal Hi. Did you find a way how to fix it? Cause I faced the same issue

**Comment by VaghasiyaKrupal** [comment] 2022-09-14 23:18
@DarynaMinko Unfortunately not found any solution for this.

**Comment by DarynaMinko** [comment] 2022-09-15 07:14
@VaghasiyaKrupal ok, thanks

**Comment by Englishman-in-newYork** [comment] 2022-11-24 14:51
@DarynaMinko 
I faced with same issue and i think it caused by Google API limimits per day, if you look at console you should see something like this
![image](https://user-images.githubusercontent.com/75856971/203810502-4f532ab6-2777-4591-b1d6-adef3dc85a4f.png)

**Comment by VaghasiyaKrupal** [comment] 2022-12-03 07:25
@DarynaMinko I have not found this in my console
