### ISSUE TITLE
Browser: 'edge' was not found on your system or is not supported by Cypress. (Ubuntu)

### ISSUE THREAD

**Issue by estefafdez** [cypress-io/cypress#8952] opened 2020-10-23 12:06 UTC
### Current behavior
Cypress can't find Microsoft Edge when you installed on Ubuntu. 

Steps to reproduce: 

- Install Microsoft Edge for Ubuntu following this tutorial:  https://www.bleepingcomputer.com/news/microsoft/microsoft-edge-for-linux-released-how-to-install/
- Check that Microsoft Edge is installed and get the path:
```
whereis microsoft-edge-dev
microsoft-edge-dev: /usr/bin/microsoft-edge-dev
```

- Check the version of Microsoft Edge installed on the system:
```
microsoft-edge-dev --version
Microsoft Edge 88.0.673.0 dev
```

- Run the tests on Cypress in Edge (working already in Mac and Windows but not in Ubuntu):
```
> cypress run --env configFile=*** --browser edge --headless --spec 'cypress/integration/*/*.js'
--
973 | > Cypress config: {
974 | animationDistanceThreshold: 5,
975 | baseUrl: null,
976 | blockHosts: null,
977 | browsers: [
978 | {
979 | name: 'chrome',
980 | family: 'chromium',
981 | channel: 'stable',
982 | displayName: 'Chrome',
983 | version: '85.0.4183.83',
984 | path: 'google-chrome',
985 | majorVersion: 85
986 | },
987 | {
988 | name: 'firefox',
989 | family: 'firefox',
990 | channel: 'stable',
991 | displayName: 'Firefox',
992 | version: '80.0',
993 | path: 'firefox',
994 | majorVersion: 80,
995 | warning: 'Your project has set the configuration option: `chromeWebSecurity: false`\n' +
996 | '\n' +
997 | 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.'
998 | },
999 | {
1000 | name: 'electron',
1001 | channel: 'stable',
1002 | family: 'chromium',
1003 | displayName: 'Electron',
1004 | version: '85.0.4183.121',
1005 | path: '',
1006 | majorVersion: 85,
1007 | info: 'Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses.'
1008 | }
1009 | ],
1010 | chromeWebSecurity: false,
1011 | componentFolder: '*',
1012 | defaultCommandTimeout: 4000,
1013 | env: {
1014 | name: '***',
1017 | baseURL: 'https://****.com/',
1020 | },
1021 | execTimeout: 60000,
1022 | experimentalSourceRewriting: false,
1023 | experimentalComponentTesting: false,
1024 | experimentalFetchPolyfill: false,
1025 | experimentalNetworkStubbing: false,
1026 | fileServerFolder: '*',
1027 | firefoxGcInterval: { runMode: null, openMode: null },
1028 | fixturesFolder: '*',
1029 | hosts: null,
1030 | ignoreTestFiles: '**/skippedTestFiles/*/*.js',
1031 | includeShadowDom: false,
1032 | integrationFolder: '*',
1033 | modifyObstructiveCode: true,
1034 | nodeVersion: 'default',
1035 | numTestsKeptInMemory: 0,
1036 | pageLoadTimeout: 60000,
1037 | pluginsFile: '*',
1038 | port: null,
1039 | projectId: null,
1040 | reporter: 'cypress-multi-reporters',
1041 | reporterOptions: { configFile: 'cypress/config/reporter-config.json' },
1042 | requestTimeout: 5000,
1043 | resolvedNodeVersion: '12.16.3',
1044 | responseTimeout: 30000,
1045 | retries: { runMode: 1, openMode: 0 },
1046 | screenshotOnRunFailure: true,
1047 | screenshotsFolder: *',
1048 | supportFile: '*',
1049 | supportFolder: '*',
1050 | taskTimeout: 60000,
1051 | testFiles: '**/*.*',
1052 | trashAssetsBeforeRuns: true,
1053 | userAgent: null,
1054 | video: false,
1055 | videoCompression: 32,
1056 | videosFolder: '*',
1057 | videoUploadOnPasses: true,
1058 | viewportHeight: 1080,
1059 | viewportWidth: 1920,
1060 | waitForAnimations: true,
1061 | watchForFileChanges: false,
1062 | projectRoot: '*',
1063 | configFile: '*',
1064 | version: '5.4.0'
1065 | }
1066 | Couldn't determine Mocha version
1067 | Can't run because you've entered an invalid browser name.
1068 |  
1069 | Browser: 'edge' was not found on your system or is not supported by Cypress.
1070 |  
1071 | Cypress supports the following browsers:
1072 | - chrome
1073 | - chromium
1074 | - edge
1075 | - electron
1076 | - firefox
1077 |  
1078 | You can also use a custom browser: https://on.cypress.io/customize-browsers
1079 |  
1080 | Available browsers found on your system are:
1081 | - chrome
1082 | - firefox
1083 | - electron
1084 | npm ERR! code ELIFECYCLE
```

If I add the following code with the correct path info the`plugins/index.js` file (https://docs.cypress.io/guides/guides/launching-browsers.html#Customize-available-browsers), Cypress find Edge but it don't get the configuration file property that I have set. 

### Desired behavior
I'm looking forward to be able to run Cypress on Edge in Ubuntu. 

### Test code to reproduce
Any project with a configuration file already added with custom baseURL depending to the environment. (https://docs.cypress.io/guides/guides/environment-variables.html#Option-1-configuration-file)

### Versions

Cypress: 5.4.0
Edge: Microsoft Edge 88.0.673.0 dev
Ubuntu: 16.04

Thanks!

**Comment by jennifer-shehane** [comment] 2020-10-25 17:26
Yah, since Linux support is finally out, we likely need to update the location we look for Edge on Linux.

**Comment by estefafdez** [comment] 2020-10-26 07:46
Hey @jennifer-shehane, 

if you force the location on the run parameter: 

```
--browser /usr/bin/microsoft-edge-dev 
```

it's working but on the logs it appears the following message: 

```
Browser:    Custom Edge 88 (headless)   
```

instead of the real version of the browser.

**Comment by jennifer-shehane** [comment] 2020-10-26 08:30
Duplicate of #8930

**Closed by jennifer-shehane** 2020-10-26 08:30 UTC
Labels: OS: linux, browser: edge, stage: needs investigating
