### ISSUE TITLE
Different domain exception with different subdomain 

### ISSUE THREAD

**Issue by datpham23** [cypress-io/cypress#1764] opened 2018-05-24 17:20 UTC
### Current behavior: 
I'm getting the following exception where Cypress consider 'https://single-signon.corp.company.com' and 'https://app-host.company.com' as different domains.  
```
You may only visit a single unique domain per test.
Different subdomains are okay, but unique domains are not.

The previous domain you visited was: 'https://single-signon.corp.company.com'
You're attempting to visit this new domain: 'https://app-host.company.com'
```
### Desired behavior:
'https://single-signon.corp.company.com' and 'https://app-host.company.com' should be consider the same domain.

### Steps to reproduce:
Create an app that redirect the users to a single signon if they're not authenticated. Once they're authenticated the single sign on redirect the user back to the app. 

### Versions  
Cypress 2.1.0, MacOS 10.12.6, Chrome

**Comment by jennifer-shehane** [comment] 2019-01-25 08:03
Duplicate of #1265

**Closed by jennifer-shehane** 2019-01-25 08:03 UTC
