### ISSUE TITLE
Add environment variable to pass PR number to Dashboard from Github Action

### ISSUE THREAD

**Issue by sjohnson-sage** [cypress-io/cypress#18046] opened 2021-09-09 15:20 UTC
### What would you like?

Currently it's possible to override some git information via environment variables to be displayed in the Cypress Dashboard: https://docs.cypress.io/guides/continuous-integration/introduction#Git-information. 

It would be good to add an extra environment variable that we can pass a PR number to be displayed.

### Why is this needed?

The following examples are in a test repository.

I'm currently setting the `COMMIT_INFO_BRANCH` env var in a manually triggered (via the Github API) Github Action which runs Cypress: 

![image](https://user-images.githubusercontent.com/14963680/132713541-f27fd1f7-8bc5-4ca4-8c90-edaa9d24fe51.png)

This correctly displays the branch name `blue-button-sam` in the Cypress Dashboard for the corresponding run:

![image](https://user-images.githubusercontent.com/14963680/132712988-8a434750-4d24-4cd1-a809-95a28d29f1ea.png)

As you can see in the above image, the pull request displays as "Not provided" - I would like to pass in the PR number via an environment variable to set that, in the same way we can for the branch name.

Hopefully that made sense, I'm more than happy to provide any extra info or context needed! Thanks

**Comment by jennifer-shehane** [comment] 2021-09-10 16:27
Duplicate of https://github.com/cypress-io/cypress/issues/17913

**Closed by jennifer-shehane** 2021-09-10 16:27 UTC
