### ISSUE TITLE
Cypress crashes when specifying -- --config after upgrading to 3.6.0

### ISSUE THREAD

**Issue by jpierson** [cypress-io/cypress#5608] opened 2019-11-05 13:29 UTC
### Current behavior:

After upgrading to Cypress 3.6.0 from 3.3.1, the cypress test runner crashes when running `open` or running from CLI while also suppling the `baseUrl` configuration through the command line.

```
> cypress-test@1.0.0 cypress C:\projects\myproject\cypress
> cypress run "--config" "baseUrl=https://someurl.nonsense"

npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! cypress-test@1.0.0 cypress: `cypress run "--config" "baseUrl=https://someurl.nonsense"`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the cypress-test@1.0.0 cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2019-11-05T13_23_51_508Z-debug.log
```

[2019-11-05T13_23_51_508Z-debug.log](https://github.com/cypress-io/cypress/files/3809153/debuglog.log)

### Desired behavior:

The tests should run or open the test runner with the specified configuration value as it had in the past.

### Steps to reproduce: (app code and test code)

ex. 

```
npm run cypress -- --config baseUrl=https://someurl.nonsense
```

or

```
npm run cypress:open -- --config baseUrl=https://someurl.nonsense
```

### Versions

Cypress 3.6.0
Node v11.10.0
NPM 6.7.0
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134

**Comment by amrtn** [comment] 2019-11-05 15:51
I'm experiencing the same behavior. I had to downgrade back to 3.4.1

Possible duplicate of https://github.com/cypress-io/cypress/issues/5466

**Comment by jennifer-shehane** [comment] 2019-11-05 21:32
@jpierson In your posted log, I see `Exit status 4294967295` and that you are running on Windows. This is a duplicate of https://github.com/cypress-io/cypress/issues/5466

Downgrade to 3.4.1 as a workaround today.

**Closed by jennifer-shehane** 2019-11-05 21:32 UTC
