### ISSUE TITLE
Add onBeforeLoad and onLoad to cy.reload method

### ISSUE THREAD

**Issue by andreiucm** [cypress-io/cypress#2065] opened 2018-06-29 08:58 UTC
### Current behavior:

`cy.reload` doesn't have powerful options that have `cy.visit`

### Desired behavior:

Add `onBeforeLoad` + `onLoad` option to `cy.reload` method that behaves same as for `cy.visit`

### Versions

Cypress version: 3.0.1

**Comment by jennifer-shehane** [comment] 2018-06-29 16:00
Duplicate of https://github.com/cypress-io/cypress/issues/1895

**Closed by jennifer-shehane** 2018-06-29 16:00 UTC
Labels: type: duplicate
