### ISSUE TITLE
Add {Shift} and {leftarrow} supported.

### ISSUE THREAD

**Issue by disappearedgod** [cypress-io/cypress#6200] opened 2020-01-21 07:11 UTC
### Current behavior:

I get a input and type a string(like 'ava') and want to select the last char with `Shift + leftarraow` from the cursor.

But I sees `leftarraow` would work without Shift. The cursor moves after 'v', like 'av |  a'

### Desired behavior:

I want to select the last char with  typing `Shift + leftarraow`
### Test code to reproduce

```js
cy.get('#ID').find('input[type=text]').eq(0)
.type('ava')
.type('{Shift}{leftarrow}', {release : false})
```
### Versions

cypress :5.0.2
macOS :10.15.2
Chrome

**Comment by disappearedgod** [comment] 2020-01-21 07:12
<img width="424" alt="Screen Shot 2020-01-21 at 2 54 47 PM" src="https://user-images.githubusercontent.com/4340627/72783068-76730d80-3c60-11ea-8906-fcad6b7e9c93.png">

**Comment by jennifer-shehane** [comment] 2020-01-21 08:04
Cypress' API does not fully support text selection at the moment. Closing as duplicate of https://github.com/cypress-io/cypress/issues/2839 which does detail a workaround for simulating test selection here: https://github.com/cypress-io/cypress/issues/2839#issuecomment-447012818

**Closed by jennifer-shehane** 2020-01-21 08:04 UTC
