### ISSUE TITLE
Cypress DOM alias retries to re-run .blur command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#15793] opened 2021-04-05 20:51 UTC
Cypress v6.8.0

https://github.com/cypress-io/cypress-test-tiny/tree/alias-blur

Imagine the spec

```js
/// <reference types="cypress" />
it('uses the alias', () => {
  // cy.visit('/')
  cy.visit('index.html')
  cy.focused().should('have.id', 'fname').blur()

  // completely unrelated field
  cy.contains('Child div').as('child').should('be.visible')

  // re-render the label
  cy.get('button').click()

  cy.get('@child')
  // just querying it again works
  // cy.contains('Child div').as('child').should('be.visible')
})
```

The button click re-draws the relevant DOM node

```js
document.getElementById('work').addEventListener('click', () => {
  document.getElementById('parent').innerHTML = `
    <div id="child">Updated Child div</div>
  `
})
```

Because of the button click, the original DOM alias `@child` is no longer attached to the DOM, thus Cypress tries to re-query the chain of commands. When this runs (use Chrome v91+ to get around https://github.com/cypress-io/cypress/issues/6207) we get an attempt to re-run the `.blur` command

<img width="1150" alt="Screen Shot 2021-04-05 at 4 49 28 PM" src="https://user-images.githubusercontent.com/2212006/113625568-12532400-962f-11eb-85a0-e52a7a144d02.png">

**Comment by bahmutov** [comment] 2021-04-05 21:35
Seems it thinks the original `cy.contains` is a child command, even if it starts

```js
cy.contains('Child div').as('child').should('be.visible')
```

<img width="976" alt="Screen Shot 2021-04-05 at 5 34 34 PM" src="https://user-images.githubusercontent.com/2212006/113630089-5812eb00-9635-11eb-87d5-a89b35f0e775.png">

**Comment by bahmutov** [comment] 2021-04-05 21:50
@Bkucera would/should `cy.contains` be a parent command or a child command this test?

```js
cy.visit('/')
cy.contains('some text')
```

Right now it thinks `cy.contains` is a child command of `cy.visit` but I seriously doubt this is correct

**Comment by jennifer-shehane** [comment] 2021-05-05 16:57
`cy.contains()` reruns queries when there's an alias. It's very very weird behavior.

Duplicate of https://github.com/cypress-io/cypress/issues/7413

**Closed by jennifer-shehane** 2021-05-05 16:57 UTC
Labels: topic: alias, type: bug
