### ISSUE TITLE
Failed to capture tab: image readback failed

### ISSUE THREAD

**Issue by broom9** [cypress-io/cypress#4427] opened 2019-06-11 05:47 UTC
### Current behavior:

When run Cypress (3.2.0 and 3.3.1) in Docker on Linux, it sometimes fails to do screenshot, with error message: `Failed to capture tab: image readback failed`

It happens fairly often on CI, about 1 out of 10 times. It doesn't happen on Mac or local environment.

Initially, I thought full page screenshot was too heavy. Reduced the screenshot to `viewport` but it still happens.

The screenshot call is a straightforward call like `cy.screenshot(filename)` with a `Cypress.Screenshot.defaults({ capture: 'viewport' });` call earlier.

It's interesting that the `after-failure` automatic screenshot still works... just the 

Here are some logs related to the error.

```
  cypress:server:timers queuing timer id 1471 after 30000 ms +2ms
  cypress:server:timers child received timer id 1471 +60ms
  cypress:server:timers clearing timer id 1471 from queue { '1351': { args: [], ms: 85000, cb: [Function] }, '1452': { args: [], ms: 85000, cb: [Function] }, '1471': { args: [], ms: 30000, cb: [Function] } } +25ms
  cypress:server:timers clearing timer id 1351 from queue { '1351': { args: [], ms: 85000, cb: [Function] }, '1452': { args: [], ms: 85000, cb: [Function] } } +75ms
  cypress:server:timers queuing timer id 1472 after 85000 ms +1ms
  cypress:server:timers child received timer id 1472 +101ms
  cypress:server:timers clearing timer id 1452 from queue { '1452': { args: [], ms: 85000, cb: [Function] }, '1472': { args: [], ms: 85000, cb: [Function] } } +2ms
  cypress:server:timers queuing timer id 1473 after 85000 ms +1ms
  cypress:server:timers child received timer id 1473 +8ms
  cypress:server:cookies received get:cookies [] +1ms
  cypress:server:timers queuing timer id 1474 after 30000 ms +3ms
  cypress:server:timers child received timer id 1474 +12ms
  cypress:server:timers clearing timer id 1474 from queue { '1472': { args: [], ms: 85000, cb: [Function] }, '1473': { args: [], ms: 85000, cb: [Function] }, '1474': { args: [], ms: 30000, cb: [Function] } } +5ms
  cypress:server:timers child sending timer id 1227 +102ms
  cypress:server:timers child sending timer id 1228 +10ms
  cypress:server:timers child sending timer id 1229 +8ms
  cypress:server:timers child sending timer id 1230 +12ms
  cypress:server:request setting request jar cookies [] +130ms
  cypress:server:timers child sending timer id 1231 +10ms
  cypress:server:timers child sending timer id 1232 +15ms
  cypress:server:timers child sending timer id 1233 +81ms
  cypress:server:timers child sending timer id 611 +28ms
  cypress:server:timers child sending timer id 1234 +1ms
  cypress:server:timers child sending timer id 612 +3ms
  cypress:server:timers clearing timer id 1472 from queue { '1472': { args: [], ms: 85000, cb: [Function] }, '1473': { args: [], ms: 85000, cb: [Function] } } +136ms
  cypress:server:timers queuing timer id 1475 after 85000 ms +1ms
  cypress:server:timers child received timer id 1475 +4ms
  cypress:server:timers child sending timer id 1235 +1ms
  cypress:server:timers clearing timer id 1473 from queue { '1473': { args: [], ms: 85000, cb: [Function] }, '1475': { args: [], ms: 85000, cb: [Function] } } +3ms
  cypress:server:timers queuing timer id 1476 after 85000 ms +0ms
  cypress:server:timers child received timer id 1476 +1ms
  cypress:server:cookies received get:cookies [] +1ms
  cypress:server:timers child sending timer id 1236 +7ms
  cypress:server:timers queuing timer id 1477 after 30000 ms +11ms
  cypress:server:timers child received timer id 1477 +4ms
  cypress:server:timers clearing timer id 1477 from queue { '1475': { args: [], ms: 85000, cb: [Function] }, '1476': { args: [], ms: 85000, cb: [Function] }, '1477': { args: [], ms: 30000, cb: [Function] } } +56ms
  cypress:server:timers child sending timer id 1237 +77ms
  cypress:server:request setting request jar cookies [] +47ms
  cypress:server:timers child sending timer id 1238 +63ms
  cypress:server:timers child sending timer id 1239 +23ms
  cypress:server:timers child sending timer id 1240 +2ms
  cypress:server:timers child sending timer id 1241 +12ms
  cypress:server:timers child sending timer id 1243 +132ms
  cypress:server:timers child sending timer id 1244 +4ms
  cypress:server:timers child sending timer id 1245 +5ms
  cypress:server:timers child sending timer id 1246 +107ms
  cypress:server:timers child sending timer id 1247 +52ms
  cypress:server:timers child sending timer id 1248 +22ms
  cypress:server:timers child sending timer id 1249 +29ms
  cypress:server:timers child sending timer id 1250 +303ms
  cypress:server:timers child sending timer id 1251 +5ms
  cypress:server:timers queuing timer id 1478 after 30000 ms +3ms
  cypress:server:timers child received timer id 1478 +77ms
  cypress:server:timers clearing timer id 1478 from queue { '1475': { args: [], ms: 85000, cb: [Function] }, '1476': { args: [], ms: 85000, cb: [Function] }, '1478': { args: [], ms: 30000, cb: [Function] } } +146ms
  cypress:server:timers clearing timer id 1475 from queue { '1475': { args: [], ms: 85000, cb: [Function] }, '1476': { args: [], ms: 85000, cb: [Function] } } +54ms
  cypress:server:timers queuing timer id 1479 after 85000 ms +0ms
  cypress:server:socket automation:request take:screenshot { titles: [ 'Test Process', 'Process user 24955' ], testId: 'r8', name: '24955-user-name', capture: 'viewport', clip: { x: 0, y: 0, width: 1050, height: 932 }, viewport: { width: 1050, height: 932 }, scaled: false, blackout: [], startTime: '2019-06-11T04:14:52.274Z' } +0ms
  cypress:server:screenshot (s6) capturing screenshot { titles: [ 'Test User Process', 'Process user 24955' ], testId: 'r8', name: '24955-user-name', capture: 'viewport', clip: { x: 0, y: 0, width: 1050, height: 932 }, viewport: { width: 1050, height: 932 }, scaled: false, blackout: [], startTime: '2019-06-11T04:14:52.274Z', specName: 'test_spec.js' } +1ms
  cypress:server:screenshot (s6) capture and check { tries: 1, totalDuration: 0 } +0ms
  cypress:server:timers child received timer id 1479 +296ms
  cypress:server:timers clearing timer id 1476 from queue { '1476': { args: [], ms: 85000, cb: [Function] }, '1479': { args: [], ms: 85000, cb: [Function] } } +102ms
  cypress:server:timers queuing timer id 1480 after 85000 ms +1ms
  cypress:server:timers child received timer id 1480 +102ms
  cypress:server:screenshot (s6) received screenshot data from automation layer data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABBoAAAOkCAIAAACH2cCDAAAAAXNSR0IArs4c6QAAIABJREFUeJzsnX +3ms
  cypress:server:timers queuing timer id 1481 after 1 ms +76ms
  cypress:server:timers child received timer id 1481 +79ms
  cypress:server:timers child sending timer id 1481 +2ms
  cypress:server:timers clearing timer id 1481 from queue { '1479': { args: [], ms: 85000, cb: [Function] }, '1480': { args: [], ms: 85000, cb: [Function] }, '1481': { args: [], ms: 1, cb: [Function] } } +2ms
  cypress:server:screenshot (s6) read buffer to image 1050 x 932 +1ms
  cypress:server:screenshot (s6) helper pixels
  cypress:server:screenshot  { topLeft: { r: 204, g: 204, b: 204, a: 255, isNotWhite: true },
  cypress:server:screenshot   topLeftRight: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   topLeftDown: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   bottomLeft: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   topRight: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   bottomRight: { r: 0, g: 0, b: 0, a: 255, isBlack: true } } +0ms
  cypress:server:screenshot (s6) pixelConditionFn { pixelRatio: 1, subject: 'app', hasPixels: true, expectedPixels: false } +0ms
  cypress:server:screenshot (s6) capture and check { tries: 2, totalDuration: 185 } +0ms
  cypress:server:timers child sending timer id 615 +42ms
  cypress:server:timers clearing timer id 1480 from queue { '1479': { args: [], ms: 85000, cb: [Function] }, '1480': { args: [], ms: 85000, cb: [Function] } } +46ms
  cypress:server:timers queuing timer id 1482 after 85000 ms +1ms
  cypress:server:timers child received timer id 1482 +6ms
  cypress:server:screenshot (s6) clearing 0 cached multipart images +0ms
  cypress:server:timers child sending timer id 616 +88ms
  cypress:server:timers clearing timer id 1479 from queue { '1479': { args: [], ms: 85000, cb: [Function] }, '1482': { args: [], ms: 85000, cb: [Function] } } +113ms
  cypress:server:timers queuing timer id 1483 after 85000 ms +1ms
  cypress:server:timers child received timer id 1483 +26ms
  cypress:server:socket automation:request take:screenshot { titles: [ 'Test User Process', 'Process user 24955' ], testId: 'r8', simple: false, testFailure: true, capture: 'runner', clip: { x: 0, y: 0, width: 1050, height: 932 }, viewport: { width: 1050, height: 932 }, scaled: true, blackout: [], startTime: '2019-06-11T04:14:52.676Z' } +0ms
  cypress:server:screenshot (s7) capturing screenshot { titles: [ 'Test User Process', 'Process user 24955' ], testId: 'r8', simple: false, testFailure: true, capture: 'runner', clip: { x: 0, y: 0, width: 1050, height: 932 }, viewport: { width: 1050, height: 932 }, scaled: true, blackout: [], startTime: '2019-06-11T04:14:52.676Z', specName: 'test_spec.js' } +0ms
  cypress:server:screenshot (s7) capture and check { tries: 1, totalDuration: 0 } +1ms
  cypress:server:timers clearing timer id 1482 from queue { '1482': { args: [], ms: 85000, cb: [Function] }, '1483': { args: [], ms: 85000, cb: [Function] } } +151ms
  cypress:server:timers queuing timer id 1484 after 85000 ms +0ms
  cypress:server:timers child received timer id 1484 +152ms
  cypress:server:screenshot (s7) received screenshot data from automation layer data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABBoAAAOkCAIAAACH2cCDAAAAAXNSR0IArs4c6QAAIABJREFUeJzsnX +2ms
  cypress:server:timers queuing timer id 1485 after 1 ms +52ms
  cypress:server:timers child received timer id 1485 +54ms
  cypress:server:timers child sending timer id 1485 +1ms
  cypress:server:timers clearing timer id 1485 from queue { '1483': { args: [], ms: 85000, cb: [Function] }, '1484': { args: [], ms: 85000, cb: [Function] }, '1485': { args: [], ms: 1, cb: [Function] } } +2ms
  cypress:server:screenshot (s7) read buffer to image 1050 x 932 +0ms
  cypress:server:screenshot (s7) helper pixels
  cypress:server:screenshot  { topLeft: { r: 204, g: 204, b: 204, a: 255, isNotWhite: true },
  cypress:server:screenshot   topLeftRight: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   topLeftDown: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   bottomLeft: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   topRight: { r: 255, g: 255, b: 255, a: 255, isWhite: true },
  cypress:server:screenshot   bottomRight: { r: 0, g: 0, b: 0, a: 255, isBlack: true } } +1ms
  cypress:server:screenshot (s7) pixelConditionFn { pixelRatio: 1, subject: 'runner', hasPixels: true, expectedPixels: true } +0ms
  cypress:server:screenshot (s7) resolving with image { tries: 1, totalDuration: 0 } +0ms
  cypress:server:screenshot (s7) pixel ratio is 1 +0ms
  cypress:server:screenshot (s7) save /app/cypress/screenshots/test_spec.js/Test User Process -- Process user 24955 (failed).png +2ms
  cypress:server:timers child sending timer id 620 +72ms
  cypress:server:timers child sending timer id 621 +27ms
  cypress:server:plugins plugin event registered? { event: 'after:screenshot', isRegistered: false } +112ms
  cypress:server:timers child sending timer id 622 +27ms
  cypress:server:timers child sending timer id 623 +4ms
  cypress:server:timers child sending timer id 624 +0ms
  cypress:server:timers child sending timer id 625 +1ms
  cypress:server:timers clearing timer id 1483 from queue { '1483': { args: [], ms: 85000, cb: [Function] }, '1484': { args: [], ms: 85000, cb: [Function] } } +42ms
  cypress:server:timers queuing timer id 1486 after 85000 ms +0ms
  cypress:server:project onMocha fail +1ms
  cypress:server:timers child received timer id 1486 +28ms
    1) Process user 24955
  cypress:server:timers clearing timer id 1486 from queue { '1484': { args: [], ms: 85000, cb: [Function] }, '1486': { args: [], ms: 85000, cb: [Function] } } +11ms
  cypress:server:timers queuing timer id 1487 after 85000 ms +0ms
  cypress:server:project onMocha test end +0ms
  cypress:server:reporter got mocha event 'test end' with args: [ { id: 'r8', title: 'Process user 24955', err: { message: 'Failed to capture tab: image readback failed' }, state: 'failed', body: 'function () {\n      retrieveAndProcessUser(userId);\n    }', type: 'test', duration: 20083, wallClockStartedAt: '2019-06-11T04:14:32.957Z', timings: { lifecycle: 26, 'before each': [Array], test: [Object] } } ] +0ms
  cypress:server:timers child received timer id 1487 +13ms
  cypress:server:timers clearing timer id 1487 from queue { '1484': { args: [], ms: 85000, cb: [Function] }, '1487': { args: [], ms: 85000, cb: [Function] } } +9ms
  cypress:server:timers queuing timer id 1488 after 85000 ms +0ms
  cypress:server:project onMocha hook +0ms
  cypress:server:timers child received timer id 1488 +7ms
```

### Desired behavior:

Cypress does not fail during screenshot, or give more specific reason.

### Steps to reproduce: (app code and test code)

Sorry I don't have a way to reproduce it without running it on Amazon ECS.

### Versions

Cypress 3.2.0 and 3.3.1
Docker on Amazon ECS
Amazon Linux 2

**Comment by jennifer-shehane** [comment] 2019-06-11 06:20
Error from logs:

```
cypress:server:reporter got mocha event 'test end' with args: 
[ 
  { 
    id: 'r8', 
    title: 'Process user 24955', 
    err: { 
      message: 'Failed to capture tab: image readback failed' 
    }, 
    state: 'failed', 
    body: 'function () {\n      retrieveAndProcessUser(userId);\n    }', 
    type: 'test', 
    duration: 20083, 
    wallClockStartedAt: '2019-06-11T04:14:32.957Z', 
    timings: { lifecycle: 26, 'before each': [Array], test: [Object] } 
  } 
] +0ms
```

I suspect this error is throwing from here where we call `chrome.tabs.captureVisibleTab` during `takeScreenshot` https://github.com/cypress-io/cypress/blob/renovate/develop/packages/extension/app/background.coffee#L193

This is essentially calling into `chrome.tabs` - which is throwing https://developer.chrome.com/extensions/tabs#method-captureVisibleTab

I have no idea why this is failing though. cc @chrisbreiding

**Comment by Getfree** [comment] 2020-04-11 06:12
`chrome.tabs.captureVisibleTab()` throws this error when the tab's containing window is minimized.

Chrome disables the renderer for minimized windows, so trying to capture a minimized window will result in nothing being drawn, which throws the aforementioned error.

**Comment by jennifer-shehane** [comment] 2020-07-14 05:40
I don't actually get this same error when minimizing the browser. I do however run into another issue here: #7971

I'll be closing this original issue since there is no reproducible example provided.  This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-14 05:40 UTC
Labels: stage: needs investigating, topic: screenshots 📸
