### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGABRT (After 4.2.0 update.)

### ISSUE THREAD

**Issue by nevdelap** [cypress-io/cypress#6782] opened 2020-03-19 05:51 UTC
### Current behavior:

(Line breaks added for readability in here.)

````
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Debian - 10.1)
Cypress Version: 4.2.0
/root/.cache/Cypress/4.2.0/Cypress/Cypress --no-sandbox -- --run-project e2e --browser chrome
--config baseUrl=https://www.xxxxxx.com,video=false,trashAssetsBeforeRuns=false
--headed false --spec e2e/cypress/integration/safe/setForLife.spec.js --cwd /
[18]: ../../third_party/electron_node/src/node_platform.cc:449:std::shared_ptr<PerIsolatePlatformData>
node::NodePlatform::ForIsolate(v8::Isolate *): Assertion `data' failed.
````

### Desired behavior:

No SIGABRT.

### Test code to reproduce

We saw this four times 19th March, since updating from 4.1.0 to 4.2.0 that morning, in different tests in a complex environment in integration tests. Will provide something to repro when we can.

The same test suite was running previous versions for months, updated to 4.2.0 in the morning, issued happened 4 in about 50 runs. Hasn't happened since reverting to 4.1.0 this morning the 20th March, but that is only about 20 runs. Will update.

### Versions

Cypress' docker container (Debian 10), Chrome 80 (headless).

**Comment by framauro** [comment] 2020-03-19 09:01
I see similar failure after upgrading from 4.1.0 to 4.2.0:

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Debian - 9.6)
Cypress Version: 4.2.0
npm ERR! Test failed.  See above for more details.


Exited with code exit status 1
CircleCI received exit code 1

  | Cypress:    4.2.0                                                                              │
  │ Browser:    Electron 80 (headless)                                                             │
  │ Specs:      1 found (performance.spec.js)                                                      │
  │ Searched:   cypress/integration/performance.spec.js                                            │
  │ Params:     Tag: false, Group: false, Parallel: false                                          │
  │ Run URL:    https://dashboard.cypress.io/projects/3bh5kk/runs/88

**Comment by VesterDe** [comment] 2020-03-19 20:33
I suppose this is related to #5965

**Comment by jennifer-shehane** [comment] 2020-03-26 10:49
Duplicate of #5965

**Closed by jennifer-shehane** 2020-03-26 10:49 UTC
