### ISSUE TITLE
Alert is popping while running the scripts in headless mode

### ISSUE THREAD

**Issue by Digvijayautomation** [cypress-io/cypress#23011] opened 2022-07-29 10:24 UTC
### Current behavior

![image](https://user-images.githubusercontent.com/87946611/181739628-1efa2cd4-80c6-462b-9d17-c7d5d5f15273.png)

### Test code to reproduce

Scenario- 

While testing the one of login page in our application if we provide the invalid credentials it will give error message in popup(alert), but while running it in headless mode it stills displaying the popup and until it take any action manually it is stopping the further execution

### Cypress Version

10

**Comment by tbiethman** [comment] 2022-08-01 21:40
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. 

Please also include other details relevant to your issue, like the browser you are testing against, your local version of node, and any previous Cypress version you may have used that did not exhibit this issue.

**Comment by AtofStryker** [comment] 2022-08-09 18:28
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by AtofStryker** 2022-08-09 18:28 UTC
Labels: stage: awaiting response
