### ISSUE TITLE
Retrieving aliased primitive doesn't work on other page when stored as result of a DOM query

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#25411] opened 2023-01-10 11:48 UTC
### Current behavior

If you query the DOM and extract a primitive value, eg. by invoking the `text` method, and want to alias the resulting primitive value (a string in this case), you can only retrieve it again (via `cy.get('@aliasName')`) when you remain on the same page (or return to it). If you move to another page, you get an empty string back.

```js
it('should return the alias on another page', () => {
  cy.visit('https://example.cypress.io/')

  cy.get('a[href="/commands/querying"]:eq(4)').invoke('text').as('linkText')

  // Move to /cypress-api page
  cy.contains('Cypress API').click()

  // This doesn't work
  cy.get('@linkText').should('eq', 'within')
})
```

<img width="385" alt="image" src="https://user-images.githubusercontent.com/599538/211543368-fe86d46f-0e4e-42d9-a7a0-f8d22e877a01.png">

Weirdly, the alias is stored on the `this`-object (accessible via anonymous functions, eg. in `cy.then(...)` constructs).

```js
  // This works
  cy.then(function () {
    return this.linkText
  }).should('eq', 'within')
```

### Desired behavior

As the [`cy.get` docs](https://docs.cypress.io/api/commands/get#Arguments) state:

> You can use cy.get() for aliases of **primitives**, regular objects, or even DOM elements.
>
> When using aliases with DOM elements, Cypress will query the DOM again if the previously aliased DOM element has gone stale.

Even though this primitive has been retrieved from the DOM, I don't expect this to be re-queried upon retrieval. There are use cases where you want to retrieve an ID or slug (that is generated by an application backend) from a page and re-use it in other pages so I guess it should be possible to retrieve this via the `cy.get('@alias')` command.

### Test code to reproduce

I created a repo (against the Kitchen Sink website) with 4 tests here: https://github.com/verheyenkoen/cypress-primitive-alias-bug/blob/main/cypress/e2e/test.cy.js

### Cypress Version

12.3.0

### Node version

v18.12.1

### Operating System

macOS Ventura 13.1

**Comment by nagash77** [comment] 2023-01-10 19:23
Hi @verheyenkoen , this looks to be a duplicate of this existing issue - https://github.com/cypress-io/cypress/issues/25173.  I am going to close this issue as a duplicate but it will be linked in the other issue through this comment.  Please follow the linked issue for updates.

**Closed as not planned by nagash77** 2023-01-10 19:23 UTC
