### ISSUE TITLE
allow custom location for cypress.json

### ISSUE THREAD

**Issue by dwhieb** [cypress-io/cypress#4839] opened 2019-07-26 19:50 UTC
### Current behavior:

A config file (`cypress.json`) may only be provided in the project root.

### Desired behavior:

The user should be able to specify a custom path to a config file as an option to the command line interface (probably `--configFile` or `--configPath`).

**Comment by bahmutov** [comment] 2019-07-26 19:59
duplicate of #1369 which was implemented in https://github.com/cypress-io/cypress/pull/3246

**Closed by bahmutov** 2019-07-26 19:59 UTC
