### ISSUE TITLE
Trying to login with Auth0 seems to get stuck and not redirect back to app

### ISSUE THREAD

**Issue by purejgleason** [cypress-io/cypress#18208] opened 2021-09-22 21:07 UTC
### Current behavior

Gets stuck at `https://<auth0domain>/authorize/resume` when trying to log in using Auth0 OpenID connect with session cypress

### Desired behavior

It should allow me to fully complete the Oauth and end up at the callback url

### Test code to reproduce

I have a working app that uses Auth0 for authentication. In the workflow the user visits `http://site/login` and they are redirected to the auth0 domain for the login popup. Once logged in it should be forwarded back to `http://site/callback`. However, when I have this as my test

```js
const fillLogin = async () => {
  await cy.visit(baseUrl);
  cy.log("Filling login");
  cy.get("#username")
    .should("be.visible")
    .type("...");
  cy.get("#password")
    .should("be.visible")
    .type("...");
  cy.get("button[name=\"action\"]")
    .should("be.visible")
    .click();
  await cy.visit(baseUrl);
  return cy.get(".main-container")
    .should("be.visible");
};
```

It fills out everything and then clicks the button but when it is redirected it gets stuck at `https://<auth0domain>/authorize/resume`. If I try reloading with `await cy.visit(baseUrl);` I get...

>cy.visit() failed because you are attempting to visit a URL that is of a different origin.

### Cypress Version

^8.4.1

**Comment by jennifer-shehane** [comment] 2021-09-23 19:04
You can't currently visit another url that is of a different origin within a single test. We're currently working on supporting this. Duplicate of https://github.com/cypress-io/cypress/issues/17336

There are many guides online showing ways to test with Auth0 through verifying the API calls that you should reference to write this test in a programmatic way until that is delivered.

**Closed by jennifer-shehane** 2021-09-23 19:04 UTC
