### ISSUE TITLE
Cypress running different test file.

### ISSUE THREAD

**Issue by VaghasiyaKrupal** [cypress-io/cypress#22565] opened 2022-06-28 17:50 UTC
### Current behavior

I have one project where I have implemented the `cucumber framework`. but when I run the `HubActivity1.feature` file it will be using `ProjectProfile.spec.js` instead of `HubActivity1.spec.js`. 

Please check out the below image for more reference.

![image](https://user-images.githubusercontent.com/45596703/176248732-5a5185c9-3c4b-42a4-b2ff-d85f7f9a0ffa.png)

### Test code to reproduce

1. Clone `https://github.com/VaghasiyaKrupal/cucumber-issue.git`
2. Switch to cloned directory
3. Install dependacy using `npm install`
4. Run the `HubActivity1.feature` file

### Cypress Version

10.1.0

**Comment by lmiller1990** [comment] 2022-06-29 00:24
Hi! I was able to reproduce the bug. I looked into the preprocessor - you are on v4.3.1. I visited the repo: https://github.com/badeball/cypress-cucumber-preprocessor#readme and it says

> information_source The repositor has recently moved from github.com/TheBrainFamily to github.com/badeball. Read more about the transfer of ownership https://github.com/badeball/cypress-cucumber-preprocessor/issues/689. It looks like the latest version is [v11, which has Cypress 10 support](https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v11.0.0).

I'm thinking you probably need to update to the latest version of the plugin, which has Cypress 10 support. If you are still having problems after migrating, we can dig it more.

**Comment by mjhenkes** [comment] 2022-07-11 20:29
Closing, The fix seems to be updating the plugin version.

**Closed by mjhenkes** 2022-07-11 20:29 UTC
Labels: stage: awaiting response
