### ISSUE TITLE
No tests found, When rename *.ts to *.spec.ts for component testing

### ISSUE THREAD

**Issue by cocoder16** [cypress-io/cypress#19717] opened 2022-01-15 06:38 UTC
### Current behavior

1. Create any `*.tsx` or `*.ts` file in `src`
2. Write any content in that new file and save it
3. Rename that file to `*.spec.tsx` or `*.spec.ts`
4. Write proper test code in that file like below and save it
```
import { mount } from "@cypress/react";

import App from "./App";

describe("App", () => {
  it("test", () => {
    mount(<App />);

    expect(true).to.eq(true);
  });
});
```
5. Run unit test by scripts `cypress open-ct`
6. Then we can see "No tests found" for new file
![failed pic](https://user-images.githubusercontent.com/60813614/149611049-5287007c-828b-4dca-b123-ec52c4e6b386.PNG)
7. Tests cannot be found for all `*.spec.ts` files created afterwards. In order to solve it, I couldn't find any solution except for erasing `node_modules`. This phenomenon does not occur inside the cypress/integration folder. It occurs only for component unit tests.

### Desired behavior

Now that I know this phenomenon, there is no problem if I work carefully.
Though, I report because the difference that this phenomenon does not occur in the cypress/integration folder.

### Test code to reproduce

* cypress.json
```
{
  "testFiles": "**/*.spec.ts",
  "component": {
    "componentFolder": "src",
    "testFiles": ["**/*.spec.tsx", "**/*.spec.ts"]
  }
}
```
* plugins/index.js
```
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  if (config.testingType === "component") {
    require("@cypress/react/plugins/react-scripts")(on, config);
  }

  return config;
};
```
* package.json
```
{
  "dependencies": {
    "@types/node": "^17.0.8",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^5.0.0",
    "typescript": "^4.5.4",
    "web-vitals": "^2.1.3"
  },
  "devDependencies": {
    "@cypress/react": "^5.12.0",
    "@cypress/webpack-dev-server": "^1.8.0",
    "@typescript-eslint/parser": "^5.9.0",
    "cypress": "^9.2.1",
    "postcss-normalize": "^10.0.1"
  }
}
```

I made a repo for you to see code
https://github.com/cocoder16/cypress-issue-report-no-tests-found

### Cypress Version

9.2.1

### Other

Code editor: vscode
OS: windows

I love this framework and thank you for making this 🥰

**Comment by lmiller1990** [comment] 2022-01-18 00:34
Hi!

So just to confirm, the problem only happens when you **rename** a spec file? I guess our dev-server is not correctly watching for renames.

**Comment by cocoder16** [comment] 2022-01-18 09:28
@lmiller1990 Hi! After rename a ts file to a spec file, it happens with all newly created spec files.

**Comment by lmiller1990** [comment] 2022-01-19 04:45
Yep - the problem must be that the dev server doesn't pick up new files (renaming is kind of like making a new file).

This is actually a duplicate of https://github.com/cypress-io/cypress/issues/16664 which has an open fix: https://github.com/cypress-io/cypress/pull/17950

@ZachJW34 are we good to merge that fix you did?

**Comment by ZachJW34** [comment] 2022-01-19 20:20
@lmiller1990 we are good, I'll update the PR today so we can get it merged.

**Comment by emilyrohrbough** [comment] 2022-01-25 22:55
Closing as a duplicate of #16664.

**Closed by emilyrohrbough** 2022-01-25 22:55 UTC
Labels: component testing
