### ISSUE TITLE
TS error after installing 5.5.0

### ISSUE THREAD

**Issue by PetMou** [cypress-io/cypress#8981] opened 2020-10-27 09:16 UTC
After installing Cypress 5.5.0 I get the following error when trying to run a test:
```

Oops...we found an error preparing this test file:

  cypress\intake\intake-kernfuncties.spec.js

The error was:

Error: Webpack Compilation Error
./cypress/intake/intake-kernfuncties.spec.js
Module build failed (from P:/Users/xxxxxx/AppData/Local/Cypress/Cache/5.5.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
TSError: ⨯ Unable to compile TypeScript:
../../browserslist(1,2): error TS1127: Invalid character.
../../browserslist(1,1): error TS18016: Private identifiers are not allowed outside class bodies.
../../browserslist(1,3): error TS1005: ';' expected.
../../browserslist(1,8): error TS1005: ';' expected.
../../browserslist(1,13): error TS1005: ';' expected.
../../browserslist(1,16): error TS1005: ';' expected.
../../browserslist(1,21): error TS1005: ';' expected.
...(etc)...
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

```

Windows 10, Citrix, running headless with browser chrome.
Back to cypress 5.3.0 everything runs fine

**Comment by assimilatedgiraffe** [comment] 2020-10-27 15:29
I'm getting the same thing, Cypress is attempting to compile /browserslist to typescript.

tsconfig.json is in the same folder as cypress, browserslist is in the folder above so shouldn't be included:

`{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "../node_modules",
    "types": [
      "cypress"
    ]
  },
  "include": [
    "**/*.*"
  ]
}`

Windows 10, cypress open or cypress run both give the same error.

Downgraded to 5.3.0 and it works again.

**Comment by assimilatedgiraffe** [comment] 2020-10-27 15:38
possible duplicate of https://github.com/cypress-io/cypress/issues/8864

**Comment by jennifer-shehane** [comment] 2020-10-28 05:36
Duplicate of #8864

**Closed by jennifer-shehane** 2020-10-28 05:36 UTC
