### ISSUE TITLE
trashAssetsBeforeRuns does not clear screenshots folder

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#18410] opened 2021-10-08 07:56 UTC
### Current behavior

`trashAssetsBeforeRuns` does not clear screenshots folder as it is supposed to documentation https://docs.cypress.io/guides/references/configuration#Screenshots

### Desired behavior

clear screenshots folder

### Test code to reproduce

Add `"trashAssetsBeforeRuns": true,` to cypress.json

### Cypress Version

8.5.0

**Comment by kpurikhova** [comment] 2022-03-01 15:12
Same for downloads folder!
Cypress Version 9.5.1

**Comment by emilyrohrbough** [comment] 2022-11-17 15:25
duplicate of https://github.com/cypress-io/cypress/issues/8280. Closing in favor of https://github.com/cypress-io/cypress/issues/8280.

**Closed by emilyrohrbough** 2022-11-17 15:25 UTC
Labels: stage: backlog
