### ISSUE TITLE
'JQuery' is not defined.

### ISSUE THREAD

**Issue by AaronMcCloskey** [cypress-io/cypress#22467] opened 2022-06-23 04:32 UTC
### Current behavior

In `commands.ts` trying to get the type `JQuery` returns an eslint error

```
'JQuery' is not defined.eslint[no-undef](https://eslint.org/docs/rules/no-undef)
```

<img width="1235" alt="Screenshot 2022-06-23 at 05 11 51" src="https://user-images.githubusercontent.com/20436343/175207467-60dcbdde-2e73-4227-8698-f7c6f59c18ea.png">

### Desired behavior

The `JQuery` type gets defined.

It definitely exists as a type as you can see from the screenshot above, but perhaps because there are 2 definitions of the same type there's a conflict?

## command.ts

```
/// <reference types="cypress" />

declare global {
  namespace Cypress {
    interface Chainable {
      getElByAttr(attr: string, val: string): Chainable<JQuery<HTMLElement>>;
      getByTestId(testId: string, length?: number): Chainable<void>;
    }
  }
}

Cypress.Commands.add('getByTestId', (testId, length = 1) => {
  cy.get(`[data-testid="${testId}"]`).should('have.length', length);
});

Cypress.Commands.add('getElByAttr', (attr = 'name', val) => {
  return cy.get(`[${attr}=${val}]`);
});

export {};
```

## root tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "incremental": true,
    "baseUrl": "."
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "babel.config.js", "jest.config.js", "__tests__/**/*.js"]
}
````

I have tried to add a `tsconfig.json` into my `/cypress` folder but that didn't resolve the issue, this is what I tried.

## /cypress/tsonfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.ts"]
}
```

### Cypress Version

10.1.0

### Other

I've tried restarting my TS server in VSCode every time I make any change, but nothing seems to have resolved the issue

It looks like someone else also had this issue [here](https://stackoverflow.com/q/70249876/3113377)

Also tried adding `"types": ["cypress"]` into either `tsconfig.json`

FWIW I've also tried the following; 
- [What is in the docs](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfig-json)
- [This](https://github.com/cypress-io/cypress/issues/1152#issuecomment-355794417)
- [And this](https://github.com/cypress-io/cypress/issues/1152#issuecomment-359837094)
- [And this](https://github.com/cypress-io/cypress/issues/1236#issuecomment-374935739)
- [And this in both tsconfig files](https://github.com/cypress-io/cypress/issues/1152#issuecomment-374854979)

Truthfully, at a loss.

**Comment by lmiller1990** [comment] 2022-06-24 01:56
This seems specific to something in your configuration - it seems okay for me:

![image](https://user-images.githubusercontent.com/19196536/175446783-67a40bb7-d374-4d55-a2d2-6685cab69851.png)

Are you able to provide a minimal reproduction (including your VS Code plugins, potentially)? This looks like an issue with some combination of tooling, types and IDE plugins.

**Comment by AaronMcCloskey** [comment] 2022-06-24 15:16
@lmiller1990 So your response helped me debug this and where the issue is, but I'm unsure on a resolution. 

I had created a new barebones project and was still getting the same issue.

So initially, I tried to reload the window extensions disabled and was still getting the error, but I also got as ts error on `global` stating

```
'module' declarations can only be used in TypeScript files.
```

When I tried the same project in `VSCode Insiders` I wasn't getting the error, so thought it was an issue with my settings

I did have this in my VSCode settings
```
"files.associations": {
  "*.ts": "typescript"
},
``` 

which I updated to 

```
"files.associations": {
  "*.ts": "typescript"
},
``` 

and that fixed the module error, but not the `JQuery` error.

Although when I reloaded again with extensions disabled, the error disappeared. So now I know it's an extension.

Found the culprit to be the [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) VSCode extension.

Once disabled the error goes away, though I do still kind of want this extension enabled.

I tried adding `jquery: true,` into the eslint `env` property, but no joy.

This is my `.eslintrc.js` file for reference

```
module.exports = {
  env: {
    browser: true,
    node: true,
    jest: true,
    jquery: true,
  },
  extends: [
    'airbnb',
    'airbnb/hooks',
    'eslint:recommended',
    'plugin:prettier/recommended',
    'plugin:cypress/recommended',
  ],
  plugins: ['@typescript-eslint'],
  parser: '@typescript-eslint/parser',
  rules: {
    '@typescript-eslint/no-use-before-define': ['error'],
    '@typescript-eslint/no-unused-vars': [
      'error',
      {
        vars: 'all',
        args: 'after-used',
        ignoreRestSiblings: true,
      },
    ],
    'arrow-body-style': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 0,
    'import/extensions': 'off',
    'max-len': [
      'error',
      {
        code: 120,
      },
    ],
    'prefer-destructuring': 'off',
    'no-param-reassign': 'off',
    'no-use-before-define': 'off',
    'no-unused-vars': 'off',
    'react/destructuring-assignment': 'off',
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx', '.tsx'] }],
    'react/prop-types': [0],
    'react/state-in-constructor': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/require-default-props': 'off',
    'react/default-props-match-prop-types': 'off',
    'global-require': 'off',
    'react-hooks/exhaustive-deps': 'off',
    'prettier/prettier': 'error',
    'jsx-a11y/anchor-is-valid': 'off',
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
  },
  globals: {
    __DEV__: true,
    JSX: true,
  },
};
```

So, I'm unsure of a solution other than disabling the ESLint extension

**Comment by AaronMcCloskey** [comment] 2022-06-24 15:40
After a few web searches, I found the solution.

Added 

```
'plugin:@typescript-eslint/eslint-recommended',
'plugin:@typescript-eslint/recommended',
``

in my `extends` property in my `.eslintc.js` file

And had to add a new rule too
```
'@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
```

So my `.eslintrc.js` file now looks like this.

```
module.exports = {
  env: {
    browser: true,
    node: true,
    jest: true,
  },
  extends: [
    'airbnb',
    'airbnb/hooks',
    'eslint:recommended',
    'plugin:prettier/recommended',
    'plugin:cypress/recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  plugins: ['@typescript-eslint'],
  parser: '@typescript-eslint/parser',
  rules: {
    '@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
    '@typescript-eslint/no-use-before-define': ['error'],
    '@typescript-eslint/no-unused-vars': [
      'error',
      {
        vars: 'all',
        args: 'after-used',
        ignoreRestSiblings: true,
      },
    ],
    'arrow-body-style': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 0,
    'import/extensions': 'off',
    'max-len': [
      'error',
      {
        code: 120,
      },
    ],
    'prefer-destructuring': 'off',
    'no-param-reassign': 'off',
    'no-use-before-define': 'off',
    'no-unused-vars': 'off',
    'react/destructuring-assignment': 'off',
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx', '.tsx'] }],
    'react/prop-types': [0],
    'react/state-in-constructor': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/require-default-props': 'off',
    'react/default-props-match-prop-types': 'off',
    'global-require': 'off',
    'react-hooks/exhaustive-deps': 'off',
    'prettier/prettier': 'error',
    'jsx-a11y/anchor-is-valid': 'off',
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
  },
  globals: {
    __DEV__: true,
    JSX: true,
  },
};
```

**Comment by lmiller1990** [comment] 2022-06-27 02:09
Nice job debugging this. I'm going to close this off, since there's no obvious action to be taken in the Cypress repo, but I hope this thread will help someone in the future. It's still not entirely clear what combination of plugins/config actually fixes this, and why it was broken in the first place. :man_shrugging:

**Closed by lmiller1990** 2022-06-27 02:09 UTC
Labels: stage: awaiting response
