### ISSUE TITLE
cy.contains shouldn't use content from script/style tags in the body

### ISSUE THREAD

**Issue by duaneatat** [cypress-io/cypress#15947] opened 2021-04-12 19:41 UTC
https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/packages/driver/src/dom/elements.ts#L1066

Since `elem.textContent` will include strings that are inside non-visible nodes like `<script>` and `<style>` tags, `cy.contains` can result in false-positives and false negatives. I discovered this while writing tests for a SSR app (using Next.js).

```
[Click Delete button]
cy.contains(deletedText).should("not.exist");
```

In this case, the test failed because the value of `deletedText` was found in `body.textContent` since that value was present in a `<script>` tag that was part of the original HTML.

```
cy.contains("Button that doesn't exist").click();
```

In this case, an element may get clicked if it contains a script tag that contains the text `Button that doesn't exist`. This happens pretty easily with our SSR app, where the react component names end up in a script tag, regardless of whether they are visible or not. So the test will pass on that line and proceed after clicking the `body`.

Is it possible to add an option to allow only visible contents to be matched (and internally use `innerText`)?
E.g. `cy.contains("Visible text", {visibleOnly: true});`

**Comment by jennifer-shehane** [comment] 2021-04-30 19:21
@duaneatat Can you provide a full example of this? Because Cypress does filter out `script` and `style` tags when searching for text in contains at this line https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/elements.ts#L1140:L1140

**Comment by duaneatat** [comment] 2021-05-01 13:12
Sure! take a look at: https://codepen.io/markduane/pen/YzNojLQ

The line you reference above will indeed prevent the selector from matching on `script` or `style` tags, but it won't prevent matching an element that _contains_ `script` or `style` tags. E.g. `body.textContent` will still have the script contents, so `body` will still be matched.

**Comment by jennifer-shehane** [comment] 2021-05-04 19:11
@duaneatat Can you provide an example of a failing test against this codepen? It looks like all of the text inside the script tag in this case *is* visible on the screen.

**Comment by duaneatat** [comment] 2021-05-04 19:20
My apologies, it only appears that way because the example was outputting textContent to the innerHtml of a div on the page. If you look here: https://codepen.io/markduane/pen/YzNojLQ you'll see the value that is logged into the Console includes the javascript, but that javascript isn't rendered to the page.

**Comment by jennifer-shehane** [comment] 2021-05-04 20:11
Ok, below is a reproducible example.

```js
it('passes even though in script tag', () => {
  cy.visit('index.html')
  // should not pass, but does
  cy.contains('I am in the script tag in body')  
})

it('fails as expected', () => {
  cy.visit('index.html')
  // fails correctly
  cy.contains('I am in the script tag in head')
})
```

```html
<html>
<script>
  console.log('I am in the script tag in head')
</script>
<body>
  <h1>Look at Console for values</h1>
  <script>
    console.log('I am in the script tag in body')
  </script>
</body>
</html>
```

<img width="895" alt="Screen Shot 2021-05-04 at 3 10 18 PM" src="https://user-images.githubusercontent.com/1271364/117063758-e3da6e80-acea-11eb-86e8-5669f14de198.png">

**Comment by sainthkh** [comment] 2021-07-19 00:56
Duplicate of #14861.

**Closed by sainthkh** 2021-07-19 00:56 UTC
Labels: pkg/driver, stage: ready for work, type: breaking change, type: unexpected behavior
