### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV (Error: This socket has been ended by the other party)

### ISSUE THREAD

**Issue by BiosBoy** [cypress-io/cypress#6478] opened 2020-02-17 05:19 UTC
### Current behavior:
Cypress is crashing on each run even in all browsers listed inside the options to run. 

I can't figure out what it can be, so I hope for your help guys. 

Thanks first of all for such a great tool for testing!

Stacktrace:
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:407:14)
    at IncomingMessage.ondata (_stream_readable.js:720:22)
    at IncomingMessage.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at IncomingMessage.Readable.push (_stream_readable.js:210:10)
    at HTTPParser.parserOnBody (_http_common.js:129:22)
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
 {
  code: 'EPIPE'
}
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:407:14)
    at IncomingMessage.ondata (_stream_readable.js:720:22)
    at IncomingMessage.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at IncomingMessage.Readable.push (_stream_readable.js:210:10)
    at HTTPParser.parserOnBody (_http_common.js:129:22)
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### Desired behavior:

Should work without crashing at least.

### Test code to reproduce
```js
import getToken from '../../modules/getToken'

context('Login', () => {
  beforeEach(() => {
    cy.setCookie('rfc_id', 'test')
    cy.setCookie('rfc_v', 'test')
    cy.visit('https://test:test@test.com/login.php')
  })

  it('should make a 2FA login', () => {
    // making basic 2FA login
    cy.get('#player').type('test@gmail.com')
    cy.get('#password').type('test')
    cy.get('.login').click()

    // should be a redirect to authentication screen for 2FA
    cy.url().should('match', /authenticate.php/)

    cy.get('#verify-code-input').then(() => {
      cy.get('#verify-code-input').type(getToken())
    })
    cy.get('button.c-pointer').click()

    // checking if we're on the Home page
    cy.contains('Home')
  })

  it('should make a basic login', () => {
    // making basic login
    cy.get('#player').type('test@gmail.com')
    cy.get('#password').type('test')
    cy.get('.login').click()

    // checking if we're on the Home page
    cy.contains('You are logged')
  })
})
```

### Versions

Platform: darwin (19.3.0)
Cypress Version: 4.0.2

**Comment by jennifer-shehane** [comment] 2020-02-18 06:18
Duplicate of #6458

**Closed by jennifer-shehane** 2020-02-18 06:18 UTC

**Comment by sharmilajesupaul** [comment] 2023-08-14 18:21
> Duplicate of https://github.com/cypress-io/cypress/issues/6458

@jennifer-shehane I don't think this is a duplicate issue. It looks like the stack traces are different.

https://github.com/cypress-io/cypress/issues/6458 has a path to the Cypress app in the stack trace and this one doesn't. 

```
     at ClientRequest.<anonymous> (/Users/estefania.fernandez/Library/Caches/Cypress/4.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:115:16)
```

We're running into this too, with the stack trace mentioned in this issue:

```
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (node:net:487:14)
    at IncomingMessage.ondata (node:internal/streams/readable:754:22)
    at IncomingMessage.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

on node `v16.20.0` 
Cypress version `v12.17.3`

Any idea what might be causing this?

**Comment by sharmilajesupaul** [comment] 2023-08-14 19:49
More info on this, I was running the test with `DEBUG=*`

I'm seeing the crash happen mid `cypress:net-stubbing:server:util sending event to driver`:

```
 cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'DOM.pseudoElementAdded', params: { parentId: 2596, pseudoElement: { nodeId: 2609, backendNodeId: 2612, nodeType: 1, nodeName: '::before', localName: '::before', nodeValue: '', childNodeCount: 0, attributes: [], pseudoType: 'before' } } } +9ms

cypress:net-stubbing:server:util sending event to driver { eventName: 'response:callback', data: { eventId: 'event9936', subscription: { eventName: 'response:callback', await: false, routeId: '1692037077353-4' }, browserRequestId: '2341.219', requestId: 'interceptedRequest9898', data: { headers: [Object], url: 'https://[redacted]/assets/static/packages/web/en/frontend/routes/TicketsLayout.a8ffded984.js', method: null, httpVersion: '1.1', statusCode: 200, statusMessage: 'OK', body: '__d((function(g,r,i,a,m,e,d){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.appLoaderClassNames=void 0;r(d[0]);function t(){const n=babelHelpers.interopRequireDefault(r(d[1]));return t=function(){return n},n}const{unit:n}=t().default;e.appLoaderClassNames={appLoader:"a1p3tfjg",appLoader_centered:"ak7w5u6",subtitle:"sg0dnxy",errorOrLoader:"e1tlunw3"}}),"007ed6",["ea4b89","374cab"]);\n' + function n(){const t=babelHelpers.interopRequireDefault(r(d[1]));return n=function(){return t},t}function s(){const t=babelHelpers.interopRequireDefault(r(d[2]));return s=function(){return t},t}function l(){const t=babelHelpers.interopRequireDefault(r(d[3]));return l=function(Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (node:net:487:14)
    at IncomingMessage.ondata (node:internal/streams/readable:754:22)
    at IncomingMessage.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
){return t},t}function u(){const t=babelHelpers.interopRequireDefault(r(d[4])); <... truncated...> recipientType:s,ticketID:p,onClose:this.handleCloseModal,onSendMacro:this.handleSendMacro,onUpdate:this.handleUpdate})]})}}H.contextTypes={data:t().default.object.isRequired},H.defaultProps={macroTemplateMapping:{},preferredLanguage:''};var T=H;e.defaul  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +7m
```

The log ending is exactly as reported,  i.e. before the JS string ends, it logs that the CLI receives an exit signal.
`;var T=H;e.defaul  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +7m`
