### ISSUE TITLE
Retries with failures stops processing tests

### ISSUE THREAD

**Issue by Kwozzie** [cypress-io/cypress#8455] opened 2020-09-01 01:05 UTC
### Current behavior:
Hi, having trouble with retries and test failures, getting to a point where the test run stalls. I have replicated this using the site/page: http://the-internet.herokuapp.com/login as using the company site is not an option.

I have written code to replicate and screenshots of memory and cpu usage in repository: https://github.com/Kwozzie/cypress-retry-issue

With retries set to 2 and if failures occur, tests stop progressing.

If I remove retries from the cypress.json file and bump up the number of iterations from 20 to 60 to replicate the same number of times the test would run with retries, it gets through all 60 failed tests.

With retries set, tests will run up until the 11th iteration, then stall, getting gradually slower after the 7th or 8th test. Tested on 2 different Mac Book Pros, first seen in a Gitlab CI pipeline. Am seeing CPU usage over 100%.

Tested with both Chrome and Electron as initially it looked like the 24Gb of virtual memory that Chrome used was the issue but with the same occurring with the Electron browser, this doesn't look like the cause.

### Desired behavior:

Tests to continue until completed without slow down or stopping (without failure). Using less than 100% CPU would also be good.

### Test code to reproduce

https://github.com/Kwozzie/cypress-retry-issue
```
context('demonstrating slow down using retries', () => {
    const totalTests = 20; // with retries for cy:run set to 2 (total of 60 runs), this stalls at test 10/11

    for (let i = 0; i < totalTests; i++) {
        it(`(${i}) should login successfully`, () => {
            const username = 'tomsmith';
            // const password = 'SuperSecretPassword!'; // correct password
            const password = 'badpassword';

            cy.visit('http://the-internet.herokuapp.com/login');
            cy.get('#username').clear().type(username);
            cy.get('#password').clear().type(password);
            cy.get('button').contains('Login').click();

            cy.get('#flash').contains('You logged into a secure area!');
        });
    }
});
```
with cypress.json
```
{
  "chromeWebSecurity": false,
  "defaultCommandTimeout": 5000,
  "execTimeout": 120000,
  "numTestsKeptInMemory": 0,
  "pageLoadTimeout": 5000,
  "requestTimeout": 5000,
  "responseTimeout": 5000,
  "screenshotsFolder": "cypress/reports/screenshots",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 application (version/7.2.0)",
  "video": false,
  "retries": {
    "runMode": 2,
    "openMode": 1
  }
}
```

### Versions
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Cypress package version: 5.0.0
Cypress binary version: 5.0.0
Node.js v12.18.0

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by lukeapage** [comment] 2020-09-03 19:18
Is this the same as this? https://github.com/cypress-io/cypress/issues/8363

**Comment by Kwozzie** [comment] 2020-09-03 22:50
yes it is, thank you @lukeapage

**Comment by Bkucera** [comment] 2020-09-04 14:15
closing as duplicate of #8363

**Closed by Bkucera** 2020-09-04 14:15 UTC
