### ISSUE TITLE
Cypress test runner crashes with "npm run test:e2e"

### ISSUE THREAD

**Issue by ZwapKillrath** [cypress-io/cypress#5843] opened 2019-12-02 08:48 UTC
### Current behavior:
![image](https://user-images.githubusercontent.com/49122691/69948089-4c6a5e00-14ef-11ea-84c1-2579e9e89a87.png)

Cypress test runner never starts - just exits to cmd prompt when doing "npm run test:e2e".
(set DEBUG=cypress:* used here)

### Desired behavior:
Cypress starts test runner when doing "npm run test:e2e"

### Steps to reproduce: (app code and test code)
Clean VUE project, clearing older version with cypress cache clear, add cypress

### Versions
3.5.0, 3.6.0, 3.6.1 and 3.7.0 all has this issue. 3.4.1 works
Windows 10, VSCode, NPM 6.13.1

**Comment by ZwapKillrath** [comment] 2019-12-02 08:49
Question....Any way to get a debug log file from the above?

**Comment by ZwapKillrath** [comment] 2019-12-02 11:34
Repost of #5710

**Comment by jennifer-shehane** [comment] 2019-12-03 07:34
Please do not reopen issues for already existing ones. Closing as duplicate of https://github.com/cypress-io/cypress/issues/5710

**Closed by jennifer-shehane** 2019-12-03 07:34 UTC
