### ISSUE TITLE
Failed assertion doesn't lead to test fail

### ISSUE THREAD

**Issue by ikonvpalto** [cypress-io/cypress#7274] opened 2020-05-08 07:14 UTC
### Current behavior:

I've replaced `window.console.error` function with `expect(true).to.be.false` to fail test if some error have appeared in console during test. And this solution work fine for simple js code. But test won't fail if `console.error` function have used inside promise.

![изображение](https://user-images.githubusercontent.com/14931230/81380389-83364700-9113-11ea-9364-a625f87d7c1c.png)

### Desired behavior:

Failed assertions inside promises should lead to test fail

### Test code to reproduce

https://github.com/ikonvpalto/cypress-example-kitchensink/commit/665d7fc7ca07ee6dd12c84049f3235af74e84354

### Versions

cypress 4.2.0 and 4.4.1
windows 10 1909
chrome 81.0.4044.138

**Comment by jennifer-shehane** [comment] 2020-05-11 10:22
Duplicate of #4742

**Closed by jennifer-shehane** 2020-05-11 10:22 UTC
