### ISSUE TITLE
Using any type of loop in cypress after hooks ( aftereach or after) results in cypress window hanging/crashing

### ISSUE THREAD

**Issue by rakhid** [cypress-io/cypress#5831] opened 2019-11-29 23:06 UTC
This bug is being filed by @rakhid and @leimd.

### Current behavior:

If a current test has a describe block that contains a loop.
the loop can be any type: for, while, do-while, etc the test hangs or cypress window crashes  and never reaches the hook.

### Desired behavior:

loops shouldn't be a problem within a hook
### Steps to reproduce: (app code and test code)
1.) create a spec under integration folder
2.) In your test under describe block add "aftereach" or each hook and add a loop inside it that logs a simple statement
3.) under "it" block, write a simple test to perform a couple of simple actions 
4.) do a cypress open and run the test

The git repo to replicate this failure is as follows:
https://github.com/rakhid/cypress-after-hook-bug
### Versions

3.4 and 3.6
chrome 78

**Comment by avallete** [comment] 2019-11-30 21:23
Hi there,

I didn't actually tried to run your MWE bug reproduction, so I may be wrong, but reading your code I found:

```js
    afterEach(function() {
        for (let step = 0; step < 3; step + 1) {
            cy.log('the loop is not the problem');
        }
```

Which will create an infinite loop since `step` isn't reassigned. You may want to give a shot to this instead:

```js
    afterEach(function() {
        for (let step = 0; step < 3; step += 1) {
            cy.log('the loop is not the problem');
        }
```

**Comment by rakhid** [comment] 2019-11-30 21:56
I will give it a try and update you on it tomorrow.

**Comment by rakhid** [comment] 2019-12-02 01:01
yes, That's correct. 
Closing this as its not a bug :)

**Closed** 2019-12-02 01:02 UTC
