### ISSUE TITLE
cy.visit() unable to visit https:// urls

### ISSUE THREAD

**Issue by krishvv** [cypress-io/cypress#3846] opened 2019-03-29 05:45 UTC
Hi,

Whenever i have `cy,visit()` to `https://` urls , i am getting the below mentioned error . Only through cypress this error happens  . I have also tried setting the `HTTPS_PROXY` , but that also does not help. All `http://` urls are working fine

```
The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not '2xx'.

This http request was redirected '1' time to:
```

**Comment by jennifer-shehane** [comment] 2019-03-29 05:56
Hey @krishvv, can you run the test below and tell me the results? The below test works for me. I would like to narrow down why this error is occuring for you.


```js
it('visit https', () => {
  cy.visit('https://example.cypress.io')
})
```

**Comment by krishvv** [comment] 2019-03-29 06:18
Hey @jennifer-shehane . Thanks for the reply . Yes i am able to access the above mentioned url
It works fine when i set https_proxy . 
However not all https:// urls are getting accessed  . We have some internal https://* urls which i was planning to test . Note: I am using cypress 3.2.0.
These https:// urls have SSO . Will that be a problem?

**Comment by jennifer-shehane** [comment] 2019-03-29 06:22
We'd have to know more about the implementation to say. What is required in your app to not get a 401 response from your web server? You likely will have to do this in cypress.

**Comment by krishvv** [comment] 2019-03-29 06:24
I do not have access to the web server and its code :( unfortunately!
Let me check what i can do .

**Comment by krishvv** [comment] 2019-04-03 09:41
@jennifer-shehane @maff @jbr @lorennorman . This issue is blocking us from using cypress :( 
I would love to use cypress for our automation . Can you please let me know if  i can provide data so that this issue can be debugged?
These https:// urls have SSO .

**Comment by krishvv** [comment] 2019-04-04 04:53
I tried using cy.request as well and here is the detailed error
==============
CypressError: cy.request() failed on:

http://fm6gwww6608.amr.corp.intel.com:8080/KitTool/KT3/KT3KitTool/KT3Home.aspx

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://fm6gwww6608.amr.corp.intel.com:8080/KitTool/KT3/KT3KitTool/KT3Home.aspx
Headers: {
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  "content-type": "text/html",
  "server": "Microsoft-IIS/10.0",
  "www-authenticate": "Negotiate, NTLM",
  "x-ua-compatible": "IE=edge",
  "date": "Thu, 04 Apr 2019 04:50:41 GMT",
  "content-length": "1293",
  "via": "1.1 bgintpr02",
  "cache-control": "proxy-revalidate",
  "connection": "close",
  "proxy-support": "Session-based-authentication"
}
Body: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-...

**Comment by jennifer-shehane** [comment] 2019-04-04 13:25
Hey @krishvv, thanks for providing the information from the `cy.request()`, this helps!

It looks like you are using NTLM authentication. Unfortunately, this is not fully supported at the moment in Cypress - see https://github.com/cypress-io/cypress/issues/850

However, a user has published a plugin claiming that it handles NTLM authentication within cypress here: https://github.com/bjowes/cypress-ntlm-auth This is not associated with the Cypress team, but some people seem to have had success with it. 

I will close this issue as a duplicate of https://github.com/cypress-io/cypress/issues/850

**Closed by jennifer-shehane** 2019-04-04 13:25 UTC

**Comment by krishvv** [comment] 2019-04-05 04:57
@jennifer-shehane Thanks a lot . Will check out the plugin

**Comment by krishvv** [comment] 2019-04-05 10:51
The plugin is working awesome .  Thanks
