### ISSUE TITLE
Cypress cannot load pages without proxy

### ISSUE THREAD

**Issue by catalin7mar** [cypress-io/cypress#5739] opened 2019-11-19 11:39 UTC
Hi!
I work in an organization that uses PAC. From the cypress specifications I have to use:

If your organization uses a PAC file, contact a network administrator to ask what HTTP proxy you should be using to access the general Internet, then use that proxy with Cypress.

However, I can't use a proxy for my project, because "internal" calls should be called just without a proxy. 

This is the response from the support team (from my organization):

Please clarify with cypress team, if no PAC can be used, then tool must be adjusted so that no proxy is used, because "internal" calls should be called just without a proxy. 

My question is: it is possible to adjust so that no proxy is used? Thanks!

![image](https://user-images.githubusercontent.com/28535063/69143103-88053100-0ac8-11ea-8f40-1fb96a09d6ee.png)

**Comment by sainthkh** [comment] 2021-01-05 06:52
Closing this issue because it's old and doesn't have a reproducible example. I hope your question is solved with the latest Cypress. If the problem is still happening, please open a new issue with a reproducible example. Or if you have any questions, please open a question at [discussions](https://github.com/cypress-io/cypress/discussions).

**Closed by sainthkh** 2021-01-05 06:52 UTC
