### ISSUE TITLE
cy.intercept is much slower than cy.route in stubbing 

### ISSUE THREAD

**Issue by hatem-hatamleh** [cypress-io/cypress#16059] opened 2021-04-19 09:29 UTC
### Current behavior

We are testing our UI application in isolation using cypress, we mock almost all the backend, and in the test cases, we override the command to update the fixture file to test a specific scenario. After the 7.0.0 release and with the ability to override cy.intercept we decided to use it, but we have noticed that the performance became lower! using cy.route our suite takes around 13 mins to execute more than 300 TC, and once we changed to cy.intercept the duration was doubled! and now it takes almost 30 mins.

Here is an example of a spec file using cy.route:
<img width="721" alt="Screenshot 2021-04-19 at 10 12 38" src="https://user-images.githubusercontent.com/78985254/115213184-90b8c700-a101-11eb-9fbe-49e37afa7789.png">

And here is the same spec file but using cy.intercept:
<img width="721" alt="Screenshot 2021-04-19 at 10 12 33" src="https://user-images.githubusercontent.com/78985254/115213256-a4642d80-a101-11eb-9b29-ba31a2eabb64.png">

As you can see that the time is doubled!

### Desired behavior

To have the same performance as cy.route

### Test code to reproduce

An example of the code: 
```js
beforeEach(() => {
    cy.mockUser('POSTPAID_USER');
    cy.login('rdummy@test.coml');
  });


  it('Should not show the other subscriptions when the non-eligible is empty ', () => {
    cy.updateNumberOfGroupMembers('fx:postpaid/group-members/non-eligible');
    cy.visit('/my/red-together');
    cy.get('[data-testid="red-together-non-eligible-subscription-list"]').should('be.visible');
  });
```

cy.updateNumberOfGroupMembers is a command that overrides one of the routes in cy.mockUser with a different fixture file.

### Versions

7.1.0

**Comment by GC-Mark** [comment] 2021-04-19 09:54
Probably related to #15853

**Comment by jennifer-shehane** [comment] 2021-04-21 20:55
@hatem-hatamleh Can you isolate if the performance is the Cypress version update or purely a change from cy.route to cy.intercept? So try running it all in the previous 6.8 version. 

Because as stated previously, it may be a 7.0+ performance regression in general which our team is focusing on fixing now. 

Please feel free to close if it a version performance issue.

**Comment by jennifer-shehane** [comment] 2021-06-11 17:32
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-06-11 17:32 UTC
Labels: stage: awaiting response
