### ISSUE TITLE
Postinstall masks error when file specified in CYPRESS_INSTALL_BINARY doesn't exist

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#19645] opened 2022-01-11 10:47 UTC
### Current behavior

If you put a relative or absolute path to a file in `CYPRESS_INSTALL_BINARY` and that file doesn't exist, Cypress doesn't give an error that the file was not found. Instead, it will somehow insert the path into an URL and attempt to download that. This is very confusing.

```
C:\Users\jessef\dev\cypress-test-tiny>set CYPRESS_INSTALL_BINARY="C:\path\to\nonexistent\file.zip"

C:\Users\jessef\dev\cypress-test-tiny>npm i cypress@9.2.1

> cypress@9.2.1 postinstall C:\Users\jessef\dev\cypress-test-tiny\node_modules\cypress
> node index.js --exec install


The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/C:/path/to/nonexistent/file.zip?platform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: win32-x64 (10.0.19042)
Cypress Version: 9.2.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@9.2.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@9.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jessef\AppData\Roaming\npm-cache\_logs\2022-01-11T10_37_49_234Z-debug.log
```

### Debug logs

```
C:\Users\jessef\dev\cypress-test-tiny>set DEBUG=cypress:*

C:\Users\jessef\dev\cypress-test-tiny>npm i cypress@9.2.1

> cypress@9.2.1 postinstall C:\Users\jessef\dev\cypress-test-tiny\node_modules\cypress
> node index.js --exec install

  cypress:cli installing Cypress from NPM +0ms
  cypress:cli installing with options {} +0ms
  cypress:cli version in package.json is 9.2.1 +0ms
  cypress:cli Using CYPRESS_INSTALL_BINARY from environment variable +0ms
  cypress:cli Using CYPRESS_INSTALL_BINARY from environment variable +1ms
  cypress:cli using environment variable CYPRESS_INSTALL_BINARY "C:\path\to\nonexistent\file.zip" +4ms
  cypress:cli Reading binary package.json from: C:\Users\jessef\AppData\Local\Cypress\Cache\9.2.1\Cypress\resources\app\package.json +0ms
  cypress:cli found npm argv json '{"remain":["cypress@9.2.1"],"cooked":["i","cypress@9.2.1"],"original":["i","cypress@9.2.1"]}' +159ms
  cypress:cli looking for versionSpecifier { dir: 'C:\\Users\\jessef\\dev\\cypress-test-tiny\\node_modules\\cypress' } +3ms
  cypress:cli looking for versionSpecifier { dir: 'C:\\Users\\jessef\\dev\\cypress-test-tiny\\node_modules' } +6ms
  cypress:cli looking for versionSpecifier { dir: 'C:\\Users\\jessef\\dev\\cypress-test-tiny' } +1ms
  cypress:cli finished looking for versionSpecifier { versionSpecifier: '^9.2.1' } +2ms
  cypress:cli installed version is null version needed is C:\path\to\nonexistent\file.zip +0ms
  cypress:cli no binary installed under cli version +1ms
  cypress:cli checking local file C:\path\to\nonexistent\file.zip cwd C:\Users\jessef\dev\cypress-test-tiny\node_modules\cypress +1ms
  cypress:cli preparing to download and unzip version  C:\path\to\nonexistent\file.zip to path C:\Users\jessef\AppData\Local\Cypress\Cache\9.2.1 +1ms

  cypress:cli needed Cypress version: C:\path\to\nonexistent\file.zip +0ms
  cypress:cli source url https://download.cypress.io/desktop/C:/path/to/nonexistent/file.zip?platform=win32&arch=x64 +1ms
  cypress:cli downloading cypress.zip to "C:\Users\jessef\AppData\Local\Temp\cypress-3000.zip" +0ms
  cypress:cli Downloading package {
  url: 'https://download.cypress.io/desktop/C:/path/to/nonexistent/file.zip?platform=win32&arch=x64',
  proxy: null,
  downloadDestination: 'C:\\Users\\jessef\\AppData\\Local\\Temp\\cypress-3000.zip'
} +3ms
  cypress:cli response code 404 +133ms
  cypress:cli URL: https://download.cypress.io/desktop/C:/path/to/nonexistent/file.zip?platform=win32&arch=x64
  cypress:cli     Error: Failed downloading the Cypress binary.
  cypress:cli Response code: 404

The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/C:/path/to/nonexistent/file.zip?platform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: win32-x64 (10.0.19042)
Cypress Version: 9.2.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@9.2.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@9.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jessef\AppData\Roaming\npm-cache\_logs\2022-01-11T10_39_03_653Z-debug.log
```

### Cypress Version

9.2.1

### Package Manager

npm

### Operating system

Windows

### Other

The command output above is from a machine that does not use a proxy

**Comment by mjhenkes** [comment] 2022-01-13 21:43
I believe this is intended behaviour. 

The CYPRESS_INSTALL_BINARY has several functions:
* Installing a different cypress version
* Installing a local binary file
* Installing a external binary file
* Disabling Installation 

Perhaps the error log could be cleaned up by inspecting the CYPRESS_INSTALL_BINARY string for the presence of 'http'

https://docs.cypress.io/guides/getting-started/installing-cypress#Install-binary

**Comment by jennifer-shehane** [comment] 2024-01-24 01:40
Since this has not gotten a lot of interest over the years, we’ll close this as not planned.

**Closed by jennifer-shehane** 2024-01-24 01:40 UTC
Labels: type: enhancement, topic: installation
