### ISSUE TITLE
Should callback crashes if there are multiple should callbacks and multiple expect calls

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#5979] opened 2019-12-17 02:32 UTC
Cypress v3.8.0
Reproduction: https://github.com/cypress-io/cypress-test-tiny/tree/two-should-cb

The following test breaks with "Cannot read property 'undefined' of undefined" error

```js
it('two should callbacks (crashes and burns)', () => {
  cy.wrap(null)
    .should(() => {
      console.log('in should()')
      expect(true).to.be.true
      expect(true).to.be.true
    })
    .and(() => {
      console.log('in and ()')
    })
})
```

<img width="543" alt="Screen Shot 2019-12-16 at 9 27 50 PM" src="https://user-images.githubusercontent.com/2212006/70959717-f2b77700-204a-11ea-82be-6b0313e6b5d6.png">

The stack at the failure (notice both `assertions` and `index` values being undefined)

<img width="1281" alt="Screen Shot 2019-12-16 at 9 30 38 PM" src="https://user-images.githubusercontent.com/2212006/70959886-635e9380-204b-11ea-86b3-6e635ae87741.png">

## Weird 1

The test _passes_ if there is no second `.and(cb)`

```js
it('one should callback (works)', () => {
  cy.wrap(null)
    .should(() => {
      console.log('in should()')
      expect(true).to.be.true
      expect(true).to.be.true
    })
})
```

## Weird 2

The test _passes_ if there is only 1 `expect`

```js
it('two should callbacks with 1 expect (works)', () => {
  cy.wrap(null)
    .should(() => {
      console.log('in should()')
      expect(true).to.be.true
    })
    .and(() => {
      console.log('in and ()')
    })
})
```

**Comment by jennifer-shehane** [comment] 2019-12-17 07:16
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4981

**Closed by jennifer-shehane** 2019-12-17 07:16 UTC
Labels: topic: assertions :heavy_check_mark:, type: bug
