### ISSUE TITLE
Allow Tests to Be Run at the Folder Level From the Dashboard

### ISSUE THREAD

**Issue by zkilleb** [cypress-io/cypress#6307] opened 2020-02-03 19:43 UTC
### Current behavior:

When Cypress open is run, the user can select to run all specs or individual spec files.

### Desired behavior:

Allow the user to select a specific folder to run all of the specs inside the selected folder.

**Comment by jennifer-shehane** [comment] 2020-02-04 04:18
Duplicate of #3607

**Closed by jennifer-shehane** 2020-02-04 04:18 UTC
