### ISSUE TITLE
Enormous amount of data getting stored in EC2 under .config/Cypress/cy/production/projects 

### ISSUE THREAD

**Issue by gkrishna08** [cypress-io/cypress#29281] opened 2024-04-08 05:30 UTC
### Test code to reproduce

Not sure if it is the exact same issue, but on our CI machines (Jenkins) we see one issue 

We also have this on our Linux machine

/home/builduser/.config/Cypress/cy/production/projects

I couldn't find any information about this. Are we doing something wrong causing these files to be generated? Tired cypress cache clear command but not useful in clearing the memory. Is this issue with cypress version or anything.
Should Cypress automatically clear this? Do we have to run a certain command to clear them?

### Cypress Mode

cypress run

### Cypress Version

9.7.0

### Browser Version

Chrome 91

### Node version

16.20.0

### Operating System

Linux

**Comment by cacieprins** [comment] 2024-04-08 14:20
Hi @gkrishna08 , does this issue still occur with newer versions of Cypress?

**Comment by gkrishna08** [comment] 2024-04-08 14:47
Hi @cacieprins, yes seeing the same issue on cypress 13.6.6 as well with more memory consumption compared to 9.7.0 as we enabled video recording and some logs..

**Comment by jennifer-shehane** [comment] 2024-04-12 11:35
This is the [Cypress App Data](https://docs.cypress.io/guides/references/troubleshooting#Clear-App-Data) which is used to store things like preferences. It should be safe for you to delete everything in the `cy` folder if you want to add that into your automated process. 

I know a lot of local state for cypress open is stored in there. I’m a little less sure of what the utility would be on a CI machine and whether we need to write data in that case. 

What’s the size of the folder?

**Comment by jennifer-shehane** [comment] 2024-04-12 14:49
I see now this is a duplicate of https://github.com/cypress-io/cypress/issues/20435

I'll comment in there and close this as a duplicate.

**Closed as not planned by jennifer-shehane** 2024-04-12 14:49 UTC
Labels: type: duplicate

**Comment by gkrishna08** [comment] 2024-04-12 14:53
Hi @jennifer-shehane , In EC2 on each node daily it is storing around 2 to 2.5 GB, as we running multiple test cases and regressions daily. Is there any alternative apart from cleaning the folder or directory

**Comment by jennifer-shehane** [comment] 2024-04-12 15:23
@gkrishna08 Ahh, that is a lot. If you're open to sharing what files these are or a screenshot, you can email to jennifer@cypress.io. Looking at my App Data for many many projects, it's nowhere near that size, it's just minimal json and js files.

**Comment by gkrishna08** [comment] 2024-04-12 15:39
Not sure exactly if it is there or not now, recently we enabled to clear that data after each run. Let me check and get back to you if anything is there in EC2. @jennifer-shehane 
When we explored that directory, we found data of each runs feature files, failure screenshot, logs and reports etc.

**Comment by jennifer-shehane** [comment] 2024-04-12 17:22
@gkrishna08 Yah the screenshots, etc should not be in those directories. They would be in a cypress/screenshots directory that you could choose to cache on your machine on your own.
