### ISSUE TITLE
Don't wait for page load when clicking a download link

### ISSUE THREAD

**Issue by haleypearse** [cypress-io/cypress#8089] opened 2020-07-26 20:30 UTC
### Current behavior:

Clicking this download link works fine, but I can't stop cypress from waiting for a nonexistant page to load, which prevents the rest of the test from running.

![image](https://user-images.githubusercontent.com/10296672/88488490-4b84b180-cf42-11ea-900a-2fa790691778.png)

![image](https://user-images.githubusercontent.com/10296672/88488393-ec26a180-cf41-11ea-9c0c-bb3554cf4e37.png)

### Desired behavior:

Some way to disable waiting for a page to load.

**Comment by jennifer-shehane** [comment] 2020-07-27 05:34
What do you mean when saying 'nonexistent page'? What is the normal behavior of the browser, does it navigate to the document in the browser? 

This is likely a duplicate of one of the issues below.

- Issue for not waiting for load event: https://github.com/cypress-io/cypress/issues/788
- Issue for ability to visit non text/html pages https://github.com/cypress-io/cypress/issues/1551

**Comment by haleypearse** [comment] 2020-07-27 16:08
Yes, thank you! I guess it's sort of a duplicate of #1551[https://github.com/cypress-io/cypress/issues/1551](url) which I hadn't been able to find. The normal behavior is simply downloading a file, no page is visited. 

All I need to do is initiate a click without waiting for a page load. I tried .trigger('click'), .trigger('mousedown'.wait(100).trigger('mouseup'), Cypress.$(...click()) and a bunch of other things. Or some way to dispatch a page load event to stop the waiting, or to tell cypress to abort the waiting directly. There must be some workaround, but I haven't found it yet. But ideally there'd be a way to stop cypress from assuming there's a page to load.

**Comment by jennifer-shehane** [comment] 2020-07-28 10:47
There's currently no way to prevent the page load from happening within Cypress itself once the application under test has initiated a page load - so the tests won't continue until that new page fires its load event. 

This thread may be helpful for testing downloading a file - as this is not completely supported in Cypress yet. https://github.com/cypress-io/cypress/issues/949

**Closed by jennifer-shehane** 2020-07-28 10:47 UTC
Labels: stage: awaiting response

**Comment by norvinino** [comment] 2020-09-25 19:51
@haleypearse 
I have the same problem. Do you have an answer to this please

**Comment by norvinino** [comment] 2020-09-25 19:51
@jennifer-shehane 
I have the same problem. Do you have an answer to this please

**Comment by stanislavgeorgiev** [comment] 2020-10-09 17:39
I also have the same issue @jennifer-shehane and I'm looking for a solution. Clicking on a button which triggers a file download is usually just triggering the browser to download the file without changing the actual page thus not emitting a load event.

**Comment by DenStrelnik** [comment] 2020-10-15 08:51
Hello @jennifer-shehane. I also have the same problem. Have you any solution to solve it?

**Comment by magarwal19** [comment] 2020-11-30 05:25
Hi @jennifer-shehane 
I am also facing this issue. Can you please let us know if there is some solution or workaround for this.

**Comment by sofiia-german** [comment] 2020-12-08 06:11
Hi @jennifer-shehane We have the same problem with download(( Is there any update on this matter?

**Comment by jennifer-shehane** [comment] 2020-12-08 07:21
No, there is no workaround or way to prevent this behavior. You will have to avoid clicking the download button or use any of the workarounds in this thread: https://github.com/cypress-io/cypress/issues/949 until the feature for testing file download is released.

**Comment by stanislavgeorgiev** [comment] 2020-12-08 22:44
Is there an ETA on expected release? Something in the span of 1Q 2021 or 2Q, etc.?

**Comment by jennifer-shehane** [comment] 2020-12-09 09:00
It's on our current roadmap. We're hoping to spike into assessing the effort it would take to support soon. https://on.cypress.io/roadmap

**Comment by stanislavgeorgiev** [comment] 2020-12-09 19:08
Great, thanks for the update!

**Comment by jennifer-shehane** [comment] 2021-01-20 04:34
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).

**Comment by jimpriest** [comment] 2021-01-20 19:45
I still have this issue in 6.3.0   I click my download button, file is downloaded to cypress/downloads - but Cypress is expecting a page load which doesn't happen.   I'm not downloading a link but via button I click which dynamically generates a file.

**Comment by maaaariana** [comment] 2021-02-04 10:56
Hi, @jennifer-shehane,
still have the same problem with download file

**Comment by jennifer-shehane** [comment] 2021-02-05 09:55
@maaaariana You may be experiencing this issue: https://github.com/cypress-io/cypress/issues/14857 There seem to still be some cases where this page load timeout occurs clicking to download files, but not all cases so we need to narrow down why. If you can add your example there. Thanks!

**Comment by sarja510** [comment] 2021-02-18 12:03
I am facing the same problem. Clicking on the **Download** button change **window.location.href** to download the file, also triggers the **beforeunload** event. We are downloading the file only, not redirecting towards a page actually, but for the redirection, cypress wait for a **load**  event to be triggered by the application but as no redirection actually is happening it gets page load timeout error. I tried stopPropagation on "window:before:unload" event but didn't work. If we can invoke the load event during the wait or can execute the stopPropagation on the correct state it can be resolved I guess.

**Comment by pseidonims** [comment] 2021-09-24 12:06
@jennifer-shehane Hi, Jennifer! Having the same issue here.

**Comment by suryakumara** [comment] 2021-12-08 07:24
@jennifer-shehane same problem here.

**Comment by vvzge** [comment] 2022-04-05 12:26
Same issue here. In cypress UI this works with all browsers. (after clicking on element, a pdf is open in a new page) In headless electron everything is fine. But in headless chrome and edge i got "waiting for new page to load".

**Comment by andi-dev** [comment] 2022-06-27 15:35
@jennifer-shehane I am facing the same issue, "waiting for new page to load" while the download has been visibly finished.

**Comment by slpngpnthr** [comment] 2022-07-15 11:10
I am having the same issue - Page Load event timeout  - after clicking on a file download link.

**Comment by SiWhite** [comment] 2022-07-20 02:20
+1 for this issue

**Comment by stass-1** [comment] 2022-08-01 18:32
Same for me

**Comment by icedbuffing** [comment] 2022-08-30 10:03
I also still encounter this issue. Expected a page to load, but there is no page switch. Just a file being downloaded.

**Comment by icedbuffing** [comment] 2022-10-04 07:35
Anyone has an idea? My test fails, but it's actually not failing.

**Comment by ajapalak** [comment] 2022-10-25 09:39
same issue here

**Comment by Gjodim** [comment] 2022-11-04 12:14
I have the same or similar issue as well.
I am trying to click an element (regular button), but i am stuck on loading the page on which that button is located.
The button itself is visible and loaded but i get an error that the page is not loaded (i wait 60s which is more than enough)... any solution or workaround for this?

**Comment by ScottAgirs** [comment] 2022-12-28 10:24
Same here, when trying to test for Auth0 login flow - after redirect, the page loads, but the event is not triggered and test fails 🌚

**Comment by kuchkarbayev** [comment] 2023-01-17 10:46
Add this `defaultpageLoadTimeout: 100000` in the **cypress.config.js**

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    watchForFileChanges: false
  },
  defaultCommandTimeout: 10000,
  defaulpageLoadTimeout: 100000
});
```

**Comment by suseendranm** [comment] 2023-01-20 13:00
> 

Same problem. Like after click login button it just showing "waiting for new page to load" in auth page. Can't believe this bug existing more than year in Cypress side.

**Comment by annoyed** [comment] 2023-03-04 15:45
https://stackoverflow.com/questions/70346567/ability-to-prevent-stop-loading-page-load-in-cypress-when-clicked-a-hyperlink

**Comment by tkoop** [comment] 2023-03-09 19:28
I have the same problem.

On my page I have a form that makes a POST request to the server.  The server returns with these headers:
- Content-Type: application/pdf
- Content-Disposition: attachment; filename=form_response.pdf

The I get the 60 second page timeout error, even though the file downloaded correctly and into the correct Cypress downloads folder.

**Comment by anthony-bernardo** [comment] 2023-03-16 14:49
same issue for me, do we have to create a new issue ?

**Comment by ramirezmz** [comment] 2023-03-20 20:59
@anthony-bernardo I solved that problem adding in my `cypress.config.js`:
`chromeWebSecurity: false`

**Comment by KrzGruszcz** [comment] 2023-04-28 05:35
I got the same problem. My workaround was to add following script before clicking the download button:

```
const loadScript = '<script> setTimeout(() => location.reload(), 1000); </script>';
cy.get('body').invoke('append', loadScript);
```

The page is reloaded after 1s and the load event is captured by Cypress.

**Comment by mikolajtutak** [comment] 2023-06-07 11:52
> I got the same problem. My workaround was to add following script before clicking the download button:
> 
> ```
> const loadScript = '<script> setTimeout(() => location.reload(), 1000); </script>';
> cy.get('body').invoke('append', loadScript);
> ```
> 
> The page is reloaded after 1s and the load event is captured by Cypress.

It works for most of the runs, but changes content of the page so extra steps are required to navigate back to initial page state. 

We have button which, when clicked, initiates file download, and this download works fine, file is saved inside "cypress/download" folder. I would be great if finish of this this download will satisfy Cypress "wait for page load"...

I wonder is someone found better workaround for this issue than mentioned above...

**Comment by jmicu** [comment] 2023-06-09 21:45
i don't know _why_ this works but it does work for me

```
<your selector to grab the link>.then(el => { 
  el.attr('download', '')
}).click()
```

i asked ChatGPT and it said this:

> The reason your solution works is because you're dynamically adding the download attribute to the element before clicking it. The download attribute is a HTML5 attribute that, when present on an anchor (<a>) element, specifies that the target resource should be downloaded instead of navigating to it.

> In your code snippet, el.attr('download', '') sets the download attribute of the element el to an empty value. This is sufficient for triggering the download behavior when the element is clicked.

> Even though you may not see the download attribute in the DOM using developer tools, adding it dynamically through JavaScript is still effective in triggering the desired download behavior. This is because the attribute is recognized by the browser and interpreted accordingly when the element is clicked.

> By adding the download attribute to the element before clicking it, you're instructing the browser to download the linked resource instead of navigating to it, thus avoiding any potential waiting for page load behavior in Cypress.

**Comment by mikolajtutak** [comment] 2023-06-12 09:28
> <your selector to grab the link>.then(el => { 
>   el.attr('download', '')
> }).click()

Thanks for this idea! I've tried to add "download" attribute, even "download='somefile.txt'", also I've added it manually to the tested VUE app code. Cypress is still "waiting for page to load"...

However, when I empty href attribute with "el.attr('href', '')", Cypress says it downloads file from _originall_url_ and saves it in "cypress/downloads" folder, and then enters wait intercepted with original url, but in fact file is not downloaded...

I've also tried adding target attribute to the download link but this makes Cypress to disappear....

**Comment by ianbunag** [comment] 2023-10-09 00:57
This doesn't seem to be a bug on Cypress' end, its just how the browsers treat anchor elements. As https://github.com/cypress-io/cypress/issues/8089#issuecomment-1585159023 mentioned, adding a download attribute solves the issue by injecting it during runtime or just adding it as an actual attribute. This worked for me for Firefox but might be treated differently from e.g. chrome. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes.

**Comment by pastorga23** [comment] 2023-10-11 15:02
I found this and it helped me 

` downloadAsPDF(){
        cy.window().document().then(function (doc) {
            doc.addEventListener('click', () => {
              setTimeout(function () { doc.location.reload() }, 5000)
            })
            cy.get('[id="pdf_download"]').click()
          })
    }`

**Comment by DarwinCamahalan** [comment] 2024-04-02 00:53
> > .then(el => {
> > el.attr('download', '')
> > }).click()
> 
> Thanks for this idea! I've tried to add "download" attribute, even "download='somefile.txt'", also I've added it manually to the tested VUE app code. Cypress is still "waiting for page to load"...
> 
> However, when I empty href attribute with "el.attr('href', '')", Cypress says it downloads file from _originall_url_ and saves it in "cypress/downloads" folder, and then enters wait intercepted with original url, but in fact file is not downloaded...
> 
> I've also tried adding target attribute to the download link but this makes Cypress to disappear....

This Works for me! 4/2/2024
