### ISSUE TITLE
Scrollbar take screen space on small viewport

### ISSUE THREAD

**Issue by yut304** [cypress-io/cypress#5076] opened 2019-09-03 09:38 UTC
### Current behavior:

![Screen Shot 2562-09-03 at 16 28 12](https://user-images.githubusercontent.com/8858542/64161878-913b1600-ce68-11e9-8e87-16c698f04aa5.png)

### Desired behavior:

I found if I set viewport to small screen like "iPhone-4" some test had weird screen.
After inspect I found screen space for web content is not 320px but only 308px like in screenshot.

### Versions
3.4.1, macOS Mojave, Chrome 76

**Comment by jennifer-shehane** [comment] 2019-09-09 21:41
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4772

**Closed by jennifer-shehane** 2019-09-09 21:41 UTC
