### ISSUE TITLE
the style update is failing after In the Vue3 component test

### ISSUE THREAD

**Issue by cuixiaorui** [cypress-io/cypress#24874] opened 2022-11-29 13:42 UTC
### Current behavior

I used tailwind CSS for my project

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/12064746/204542979-72374bbf-6483-4af5-a771-639bc0d0cd7a.png">

The first time you enter the cypress component test it's fine

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/12064746/204543047-571badbd-5c59-45a7-ad75-b392157bf234.png">

When I change the class, the cypress component test does not update the view

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/12064746/204543114-9b3d455b-7bb1-4c48-8435-0b2dba16c982.png">

Changed bg-red-500 to bg-blue-500

When you go back to cypress and click the refresh button, you will see that the style is invalid
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/12064746/204543266-45f41ff1-c11e-48c0-ab1d-2e48f6ada8e7.png">

### Desired behavior

The correct behavior should be after updating the component's class
you should see the correct result in the cypress component test, where the background turns blue

### Test code to reproduce

repo: https://github.com/cuixiaorui/cypress-issue-for-vue3-compoment-test-hot-update

### Cypress Version

11.2.0

### Node version

v17.5.0

### Operating System

macOS 13.0.1 (22A400)

**Comment by cuixiaorui** [comment] 2022-11-29 13:51
@lmiller1990 
hi, guy 
One more piece of information
I refreshed the whole cypress window (cmd+r) and it didn't work, the style still doesn't come out
It only takes effect when it is initialized for the first time

**Comment by lmiller1990** [comment] 2022-11-29 22:55
Hmm interesting, I guess this is related to how Tailwind does a JIT compilation and injects the latest stylesheet. I notice:

- `style.css`: https://github.com/cuixiaorui/cypress-issue-for-vue3-compoment-test-hot-update/blob/main/src/style.css
- imported [here](https://github.com/cuixiaorui/cypress-issue-for-vue3-compoment-test-hot-update/blob/main/cypress/support/component.ts#L20) in `component.ts`

My question is - how does the latest styles generated by Tailwind actually get *into* the app in the first place (even in a regular Vite development environment)? 

The only style code I see is

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Does one of these somehow contain all the JIT'd styles based on your CSS classes?

**Comment by lmiller1990** [comment] 2022-11-29 23:03
Right, I see it injects during development like this:

![image](https://user-images.githubusercontent.com/19196536/204667375-394fde3c-5fd1-43c8-adda-49cf92addc24.png)

Let's find out why that isn't working in Cypress. Also, I don't see how this is injected in the regular Vite development environment, either... let's find out.

Ok, so this is the line that does injection:  `@tailwind utilities;`. Let's find out why Cypress is messing up, now. It looks like the Tailwind CSS is not getting regenerated, it's stuck on the old value of `bg-red-500`:

![image](https://user-images.githubusercontent.com/19196536/204668351-1accda52-6c22-4eaf-b8da-bdc97e57a890.png)

**Comment by lmiller1990** [comment] 2022-11-29 23:33
I think the problem is related to importing the style in the `component.ts` file. If I do 

```vue
<style>
@import './style.css';
</style>
```

Inside of `App.vue`, it's fine. It does NOT work in `App.cy.ts`, though. It looks like the bug is related to "importing dynamically generated CSS in JS (or TS) files". I will need to spend some more time to find out exactly how the Tailwind CSS update happens, and why it's getting the stale values here.

I actually just realized I had a similar bug in my own project. I worked around it by kicking off Tailwind manually

https://github.com/lmiller1990/eleutheria/blob/main/packages/frontend/package.json#L14

Then importing that:

https://github.com/lmiller1990/eleutheria/blob/main/packages/frontend/cypress/support/component.ts#L7

I wonder if we have a bug in the Cypress Vite plugin: https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/src/plugins/cypress.ts#L75-L78

**Comment by lmiller1990** [comment] 2022-11-30 00:41
Ah, @marktnoonan offers this work around:

```ts
const styles = import('../../src/style.css?' + Date.now())
```

I think vite (or our integration) has some caching that we need to bust somehow - it's not realizing that the stylesheet has been updated. 

Can you test that out @cuixiaorui ?

**Comment by cuixiaorui** [comment] 2022-11-30 07:31
cool  It's working now

That's an interesting solution

Looking forward to finding the real problem

thx @lmiller1990 @marktnoonan

**Comment by lmiller1990** [comment] 2022-11-30 21:29
We should see if webpack based projects have a similar problem. The solution might be as simple as appending a query string, like this workaround, but somewhere inside our `{webpack|vite}-dev-server` packages.

**Comment by lmiller1990** [comment] 2022-12-05 04:19
I found out this only happens with Vite - webpack works fine. I'll try and patch vite-dev-server.

**Comment by lmiller1990** [comment] 2022-12-05 06:24
I am trying to fix this, I think https://github.com/cypress-io/cypress/pull/24965 should do it. Let's see how it goes. I'll share a pre-release for you try @cuixiaorui, please give me a day or so. I don't think we even care about HMR here - if any module dependency changes (including supportFile) we can just do a full reload... the bundle should be pretty small in general, and Vite does a lot of caching, so I don't think it'll really impact perf. But let's see!

**Comment by lmiller1990** [comment] 2022-12-06 00:37
@cuixiaorui can you try the pre-release (scroll to bottom and grab the install link for your OS) https://github.com/cypress-io/cypress/commit/e1d766ce9fa8ce9d3803f634f91e5104d3e17140#comments

It's working for me. This will be fixed once https://github.com/cypress-io/cypress/pull/24965 is merged.

**Comment by baus** [comment] 2022-12-06 15:34
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24874?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment] 2022-12-06 17:39
Not adding an estimate since @lmiller1990 already has an open PR for this

**Comment by lmiller1990** [comment] 2022-12-08 23:35
@cuixiaorui fixed, it will be in the next release!

**Closed as completed** 2022-12-08 23:34 UTC
Labels: CT
