### ISSUE TITLE
Cookie through cy.request not longer setted in 3.5.0

### ISSUE THREAD

**Issue by lgraziani2712** [cypress-io/cypress#5450] opened 2019-10-24 16:26 UTC
### Current behavior:

It doesn't set the cookie that the server is returning when I try to login with `cy.request`.

### Desired behavior:

To have the cookie setted, as in v3.4.1.

#### Command

![image](https://user-images.githubusercontent.com/15050200/67505446-a6127980-f661-11e9-9794-6716052520cb.png)

#### Test

```js
before(() => {
  cy.loginAs('admin');
});
```

### Versions

Cypress v3.5.1

**Comment by jennifer-shehane** [comment] 2019-10-24 16:58
Hey @lgraziani2712, this appears to be a duplicate of this issue - introduced in 3.5.0. Closing as duplicate. https://github.com/cypress-io/cypress/issues/5432

**Closed by jennifer-shehane** 2019-10-24 16:58 UTC
