### ISSUE TITLE
M1 Mac version of Cypress

### ISSUE THREAD

**Issue by christian-kolb** [cypress-io/cypress#18724] opened 2021-11-01 14:42 UTC
### What would you like?

I'd like to be able to run Cypress on a M1 Mac without any hacks (like the one described on the official blog post back in January).

### Why is this needed?

I want this because the setup and maintenance is pretty cumbersome and error prone in a team of multiple developers.

### Other

As far as I understand the only reason why there hasn't been any progress on this topic is, that there is no native support for those processors on [Circle CI](https://circleci.canny.io/cloud-feature-requests/p/support-new-m1-arm-based-macs). It also looks like it's not top priority there.

I understand that this is quite a blocker for such a complex project like Cypress. On the other hand I'd like to open up a discussion on whether it's feasible to start with the implementation without support from Circle CI. Through the new more powerful machines, I guess there are going to be a higher percentage of users with M1 Macs in the near future.

I have no idea on how much of a burden missing Circle CI support is. I just wanted to ask because there is no way of planning at the moment as Circle CI could add support in a few days/months/years or even never.

**Comment by jennifer-shehane** [comment] 2021-11-01 15:57
Duplicate of https://github.com/cypress-io/cypress/issues/4478 

I think the main issue with missing CircleCI is our lack of being able to test the implementation ourselves. I'll make sure this is added to our product log.

**Closed by jennifer-shehane** 2021-11-01 15:57 UTC

**Comment by christian-kolb** [comment] 2021-11-01 15:59
@jennifer-shehane Ok, I wasn't sure if it's a duplicate as the other issue was tagged as OS:linux. I would be willing to help test it, if that helps 🙂

**Comment by jennifer-shehane** [comment] 2021-11-01 16:07
Yeah, I suppose we'll break out the issue if necessary for Mac/Linux when we look into it.

**Comment by JawaMatter** [comment] 2022-01-26 16:19
I suppose this are the same issues 
https://github.com/cypress-io/cypress/issues/18724
and
https://github.com/cypress-io/cypress/issues/19654

and maybe these:
https://github.com/cypress-io/cypress/issues/19908
https://github.com/cypress-io/cypress/issues/4478

**Comment by thomvaill** [comment] 2022-01-28 14:17
Yep,

I propose to close https://github.com/cypress-io/cypress/issues/19654, and to continue the discussion on these two possible solutions:

- https://github.com/cypress-io/cypress/issues/4478 : to build ARM binaries from ARM CircleCI custom runners
- https://github.com/cypress-io/cypress/issues/19908 : more short term solution to build mac ARM binaries from the current Intel runners
