### ISSUE TITLE
Cypress version 3.5.0 Problems filling Date Input

### ISSUE THREAD

**Issue by caroleco** [cypress-io/cypress#5551] opened 2019-10-31 17:33 UTC
#4332 # Current behavior:
Since I've upgraded to the 3.5.0 version, Cypress doesn't work propertly filling a *required date input*.

Even thought the input is filled , it stays red, as if it wasn't filled, so I'm not able to submit the form.

![image](https://user-images.githubusercontent.com/10404179/67969276-ba1d2480-fbe7-11e9-9adb-1b824ed47610.png)

### Desired behavior:

When I installed the previous version (3.4.1), it worked correctly. 
I was able to fill the input (that is no longer red) and submit the form.

![image](https://user-images.githubusercontent.com/10404179/67970423-b68a9d00-fbe9-11e9-90ea-204f0ddcf178.png)

### Steps to reproduce: (app code and test code)

App code:

*<input _ngcontent-c22="" class="form-control ng-pristine ng-invalid ng-touched" id="idDataNascimento" name="idDataNascimento" *required=""* type="date">*

*cy.contains('Data Nascimento').next().type('2020-10-12')*

I tried to use a tab plugin, to work around the problem, but it didn't work either.
( https://github.com/Bkucera/cypress-plugin-tab )

*cy.contains('Data Nascimento').next().type('2020-10-12').tab()*

### Versions
Chrome version :  77.0.3865.120

**Comment by brian-mann** [comment] 2019-10-31 17:53
This is likely fixed by `3.6.0` which we just released. I'm closing this issue as duplicate - and after upgrading if you still have problems please reopen this issue.

Duplicate of https://github.com/cypress-io/cypress/issues/5476

**Closed by brian-mann** 2019-10-31 17:53 UTC
Labels: type: duplicate

**Comment by barnabynorman** [comment] 2019-11-26 10:34
@brian-mann I don't think this is a duplicate issue as I can see the same problem as @caroleco also in version 3.6.1

```javascript
cy.get('[data-cy="installationDate"]')
  .type('1983-12-23')

cy.get('[data-cy="btn-decline"]')
  .should('be.visible')
  .click()
```

So basically I type in the date, which works, but when I click the checkbox (ie loose focus of the date input), it errors:

![image](https://user-images.githubusercontent.com/1710907/69622041-7d0a4d80-1040-11ea-8452-8dd693e5f9d7.png)

**Comment by bahmutov** [comment] 2019-11-26 13:33
@barnabynorman look at the screenshot - your input has a mask and should be entered as "dd/mm/yyyy" and you are entering "yyyy-mm-dd"

**Comment by barnabynorman** [comment] 2019-11-27 07:12
Thank you @bahmutov, good suggestion but no prize:

![image](https://user-images.githubusercontent.com/1710907/69701561-7ede1a80-10ed-11ea-9355-22225a03acc2.png)

**Comment by jennifer-shehane** [comment] 2019-11-27 07:26
The below example types in a valid date input in version 3.6.1 of Cypress. 

Please provide a fully reproducible example that we can run on our machines to show the error you are encountering and we will consider reopening.

This does not mean that your issue is not happening - it just means that we do not have a path to move forward without this information.

`index.html`

```html
<html>
<body>
  <style>
    input:invalid + span::after {
      content: '✖';
      color: red;
    }
    input:valid+span::after {
      content: '✓';
      color: green;
    }
  </style>
  <input type="date" required>
  <span></span>
</body>
<script>
</script>
</html>
```

`spec.js`

```js
it('works', () => {
  cy.visit('index.html')
  cy.get('input').type('2019-11-27')
})
```

![](http://g.recordit.co/KKpbP2N4Sy.gif)

**Comment by barnabynorman** [comment] 2019-11-28 12:47
@jennifer-shehane , @bahmutov looks like there was an error my end completely nothing to do with the date field that caused it to clear. Yes it works the way you said and thank you for your time!

It was only when I tried to build something to send to you that I spotted it!

**Comment by jennifer-shehane** [comment] 2020-01-02 07:45
@barnabynorman Thank you for your response. And yes, this is a big reason why we ask for reproducible examples upfront.
