### ISSUE TITLE
Provide binary for arm64 architecture (Linux)

### ISSUE THREAD

**Issue by svi3c** [cypress-io/cypress#4478] opened 2019-06-17 13:59 UTC
We need to run e2e tests on a device with ARM 7 architecture. Could you provide binaries for this architecture, please?
I would like to move all the e2e tests in a customer project to cypress, since they are a lot faster than Selenium. Only the missing binary is holding be back.

**Comment by bahmutov** [comment] 2019-06-17 14:26
Electron has builts for arm7 and arm64 https://electronjs.org/docs/tutorial/support#linux the challenge would be to build Cypress on CI. For example CircleCI does not support ARM builds at the moment

**Comment by svi3c** [comment] 2019-06-17 14:46
Thanks for the feedback, @bahmutov.
Is there a way to build the binary myself as a workaround for now?

**Comment by bahmutov** [comment] 2019-06-17 14:57
Yes, you can build the test binary yourself following https://github.com/cypress-io/cypress/blob/develop/DEPLOY.md#building-the-binary - usually, you just need to run a single script to build it.

**Comment by bjclark13** [comment] 2020-03-24 14:47
@svi3c were you able to build Cypress on your ARM machine?

**Comment by svi3c** [comment] 2020-03-24 15:03
@bjclark13 sorry, I did not try it yet. The priority of the task was decreased in my project.

**Comment by dfellis** [comment] 2020-06-09 23:18
I had a need for this, myself, but the original `yarn`/`npm install` in the repo failed to install `node-sass`, as an FYI. An abbreviated portion of the install logs:

```
[web-config:install ] npm ERR! code ELIFECYCLE
[web-config:install ] npm ERR! errno 1
[web-config:install ] npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
[web-config:install ] npm ERR! Exit status 1
[web-config:install ] npm ERR! 
[web-config:install ] npm ERR! Failed at the node-sass@4.11.0 postinstall script.
[web-config:install ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[web-config:install ] 
[web-config:install ] npm ERR! A complete log of this run can be found in:
[web-config:install ] npm ERR!     /home/damocles/.npm/_logs/2020-06-09T23_12_11_377Z-debug.log
[server:install     ] npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1591743866425-0.8260163179815476/node but npm is using /home/damocles/.nvm/versions/node/v10.21.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[server:install     ] prebuild-install WARN install No prebuilt binaries found (target=10.21.0 runtime=node arch=arm64 libc= platform=linux)
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@cypress/browserify-preprocessor/node_modules/chokidar/node_modules/fsevents):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/win32-ia32):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-x64@4.1.0 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/win32-x64):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-x64@4.1.0: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/darwin-x64):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-ia32):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-arm):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.3 (node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-arm64):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.0.6 (node_modules/chokidar/node_modules/fsevents):
[server:install     ] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
[server:install     ] npm WARN mocha-teamcity-reporter@3.0.0 requires a peer of mocha@>=3.5.0 but none is installed. You must install peer dependencies yourself.
[server:install     ] 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.4.1 all: `node ./scripts/run.js "install"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.4.1 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/damocles/.npm/_logs/2020-06-09T23_13_11_494Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I'm also on Node 10, so I rewound the repo to: 1a4ac7d84c01b1232e40a24fd83a2e5e1a181a3c 

I will probably switch to an Intel machine in a few hours to complete my immediate task and then come back to this problem in the future (it may also prompt me to update the backend to use node 12 instead of 10).

**Comment by wichpatricke** [comment] 2020-10-19 09:11
@bahmutov @dfellis @svi3c @jennifer-shehane 

I am also interested in armv8 cypress build. 

If I use the cypress version 4.8.0 via npm....on armv8 machine, I get following error
~~~
It looks like this is your first time using Cypress: 4.8.0

Verifying Cypress can run /home/travis/.cache/Cypress/4.8.0/Cypress [started]
Verifying Cypress can run /home/travis/.cache/Cypress/4.8.0/Cypress [failed]

Cypress failed to start.

This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
/home/travis/.cache/Cypress/4.8.0/Cypress/Cypress: 3: /home/travis/.cache/Cypress/4.8.0/Cypress/Cypress: Syntax error: Unterminated quoted string
----------
~~~

My system is ubuntu Xenial.
For the fix, I have installed these dependencies (libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb) via apt-get, but no help.

I guess cypress can not be installed on ARMv8 via npm???

I took the source code and built it following this <https://github.com/cypress-io/cypress/blob/develop/DEPLOY.md>
Here are the steps
~~~
1. increment the version in package.json
2. yarn build --scope cypress
~~~
But this is failing for a lot of dependencies like postinstall, lerna and many more. Even installing these dependecies is not helping me to build my own cypress on armv8 machine.

Can you please check if I am following the correct steps here?? Or do I need to execute something else??

**Comment by jbarbier-prisma** [comment] 2020-11-14 13:30
> @bahmutov @dfellis @svi3c @jennifer-shehane
> 
> I am also interested in armv8 cypress build.
> 
> If I use the cypress version 4.8.0 via npm....on armv8 machine, I get following error
> 
> ```
> It looks like this is your first time using Cypress: 4.8.0
> 
> Verifying Cypress can run /home/travis/.cache/Cypress/4.8.0/Cypress [started]
> Verifying Cypress can run /home/travis/.cache/Cypress/4.8.0/Cypress [failed]
> 
> Cypress failed to start.
> 
> This is usually caused by a missing library or dependency.
> The error below should indicate which dependency is missing.
> https://on.cypress.io/required-dependencies
> If you are using Docker, we provide containers with all required dependencies installed.
> ----------
> /home/travis/.cache/Cypress/4.8.0/Cypress/Cypress: 3: /home/travis/.cache/Cypress/4.8.0/Cypress/Cypress: Syntax error: Unterminated quoted string
> ----------
> ```
> 
> My system is ubuntu Xenial.
> For the fix, I have installed these dependencies (libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb) via apt-get, but no help.
> 
> I guess cypress can not be installed on ARMv8 via npm???
> 
> I took the source code and built it following this https://github.com/cypress-io/cypress/blob/develop/DEPLOY.md
> Here are the steps
> 
> ```
> 1. increment the version in package.json
> 2. yarn build --scope cypress
> ```
> 
> But this is failing for a lot of dependencies like postinstall, lerna and many more. Even installing these dependecies is not helping me to build my own cypress on armv8 machine.
> 
> Can you please check if I am following the correct steps here?? Or do I need to execute something else??

Have you found a solution?
I'm trying to install Cypress on my Raspberry pi 4B and I have the same problem ...: /

**Comment by shiro** [comment] 2020-11-28 20:08
also failing on postinstall with a raspi 4b:
```
@packages/electron: error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@packages/electron'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
error Command failed with exit code 1.

    at checkExecSyncError (node:child_process:636:11)
    at execSync (node:child_process:672:15)
    at Object.<anonymous> (/home/shiro/tmp/cypress/node_modules/postinstall-postinstall/run.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(5628) [Uint8Array] [
      121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
       50,  50,  46,  49,  48,  10,  36,  32,  46,  47, 115,  99,
      114, 105, 112, 116, 115,  47, 114, 117, 110,  45, 105, 102,
       45, 110, 111, 116,  45,  99, 105,  46, 115, 104,  32, 121, [more uints...]
```

**Comment by jennifer-shehane** [comment] 2021-01-20 05:06
@dfellis node-sass has been removed as a dependency from Cypress in 6.3.0.

**Comment by jennifer-shehane** [comment] 2021-01-21 02:20
There's a blog post explaining how to run Cypress on Apple's latest ARM-based M1 chip here: https://cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/

**Comment by lassesteffen** [comment] 2021-03-02 17:58
Hey I am trying to run on AWS with `m6g` instances (https://aws.amazon.com/ec2/instance-types/m6/). Is there any way to make it work?

**Comment by azaeng04** [comment] 2021-03-18 13:04
@jennifer-shehane will their be native support for Apple Silicon soon?

**Comment by TheDiveO** [comment] 2021-03-20 11:16
Any RPi support? Even if node performance on Raspberry Pi 4B/8G silicon is still ugly, any support planned?

**Comment by DarkC35** [comment] 2021-05-05 12:34
CircleCI provides ARM resources now, see: https://circleci.com/blog/managing-ci-cd-pipelines-with-arm-compute-resource-classes/

Although the blog post writes about a preview, there is no hint about this on the website and in the docs so maybe it's stable now?
https://circleci.com/build-environments/arm/
https://circleci.com/docs/2.0/arm-resources/

Unfortunately they currently only support `arm64` but this would be a good start to provide an arm build that can be tested for example on a Raspberry 3/4 with Raspberry OS 64bit (Beta) or Ubuntu 64bit or AWS instances IMO.

**Comment by TheDiveO** [comment] 2021-05-05 12:52
arm64 looks like a no-brainer to me: the typical user for Raspbian 32bit might not be in the ballpark for having need for Cypress. Those who do most probably have ditched Raspbian for such uses already or never did start there and work with arm64 anyway. In my experience, Raspbian has so many crude things thanks to 32bit and its maker orientation, such as broken kernel and Docker MACVLAN support, etc.

**Comment by jennifer-shehane** [comment] 2021-05-05 14:52
@DarkC35 Yah it is a little confusing. I've filled out the form to request preview access regardless for us.

**Comment by Princemachiavelli** [comment] 2021-05-25 16:36
I was able to build for ARM on a Graviton 2 AWS instance with minimal changes. I changed to Dockerfile to use Ubuntu 20.04 since the repositories for 19.04 are EOL and I also updated the nodejs repo to use 14_x. I followed the build instructions in DEPLOY.md.

As shown in #16530 , there are only two issues building 7.4.0. The current electron-packager version incorrectly detects an incompatible electron version which is fixed in electron-packager 15.2.0. The other issue is a hardcoded path to linux-unpacked which #16530 also fixes.

You can either use the unmerged branch in #16530 or you can manually work around the bugs:
1. When the build fails on the electron-packager issue, you will see a warning like "WARNING: Offical Linux/ARM is only supported in Electron"...
2. Remove the 'continue' statement at node_modules/electron-packager/src/targets.js:51
3. Change directory into the packages/electron directory & run yarn build. This will build without reverting the source code change.
4. Re-run the yarn install / yarn build --scope cypress command.

For the second issue which occurs at the end of the 'yarn binary-build' step , you can just create a symlink from linux-unpacked to linux-arm64-unpacked. I had to create the symlink a second time for 'yarn binary-zip'.

I also noticed if you have DEBUG=* set or some other verbose logging enabled, you will get maxBuffer errors during the 'lerna' commands. The simplest solution it just unset any environment variable or option. Alternatively, you can increase the buffer size by passing lerna an additional parameter.

**Comment by dtinth** [comment] 2021-11-03 09:24
Hello, I know that [Cypress can be run on M1 Macs using Rosetta 2](https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/), but my machine does not have development tools (e.g. Node.js) installed except Docker.

I am developing apps using [Remote - Containers](https://code.visualstudio.com/docs/remote/containers) and [VS Code provides dev images for ARM64 Docker daemons](https://github.com/microsoft/vscode-dev-containers/issues/558). For desktop environment I am using X11vnc running inside Docker. Everything is working fine except Cypress, which fails in this manner:

![image](https://user-images.githubusercontent.com/193136/140035532-44e441e9-1fc8-4ddb-a8a7-75fa7957f7eb.png)

It would be great if binaries for ARM-based Linux can be provided. :pray:

**Comment by baptisteArno** [comment] 2021-11-29 08:35
I'm using Cypress on my Mac to actively develop new features (TDD) and it feels really slow.
I think running an arm64 build of Cypress would speed things up. Is there a way to do this?

**Comment by baversjo** [comment] 2022-01-21 07:57
@jennifer-shehane Running cypress on an ARM-based M1 mac is pretty slow under rosetta 2. Considering apple is no longer seem to selling new intel macs as of q4 2021, I think it's a pretty important feature to add?

Also, it  seems ARM is now fully supported by circleci: https://circleci.com/blog/self-hosted-runners-add-arm-support-to-circleci/

**Comment by stevehodgkiss** [comment] 2022-01-21 10:45
As a workaround, I've managed to build Cypress v9.3.1 for `linux-arm64` on an AWS Graviton instance with the following script:

```bash
#!/bin/bash -ex

yum install -y git vim jq zip unzip gcc-c++
yum install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
git clone https://github.com/cypress-io/cypress.git
git checkout v9.3.1
cd cypress

git clone https://github.com/asdf-vm/asdf.git /usr/local/asdf --branch v0.9.0
echo ". /usr/local/asdf/asdf.sh" >> ~/.bashrc
. /usr/local/asdf/asdf.sh
asdf plugin-add nodejs
asdf install nodejs $(cat .node-version)
asdf global nodejs $(cat .node-version)

npm install -g yarn
yarn install

# needed for Cypress v8 and earlier:
# mkdir -p build
# ln -s linux-arm64-unpacked ./build/linux-unpacked

yarn binary-build --version "$(jq -r .version < package.json)"
yarn binary-zip

mv cypress.zip /home/ec2-user/
ls -lah /home/ec2-user/
```

**Comment by thomvaill** [comment] 2022-01-26 08:56
Hey!
We are also struggling to use Cypress on M1 Macbooks with Rosetta 2.
After doing some research, maybe I found a viable solution, implementable quickly: https://github.com/cypress-io/cypress/issues/19908

**Comment by JawaMatter** [comment] 2022-01-27 13:26
> I found a viable solution, implementable quickly: #19908

This worked for me. Workaround is not the best but fixes the problem:
System Version: macOS 12.1 (21C52)
Kernel Version: Darwin 21.2.0
Cypress: 9.3.1
nvm 0.39.1
npm 6.14.15
node 12.22.9 (specific for Rosetta 2 and workaround)

**Comment by taoeffect** [comment] 2022-02-01 04:20
I got 9.4.1 building on Linux ARM following @stevehodgkiss's instructions above (using node 16, it wouldn't build with node 17 [because of some SSL thing](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)).

However, I can't figure out how to use it with my project... my project installed Cypress into `~/.cache/Cypress/9.4.1`, and `yarn install` didn't override that. It fails to run the Cypress binary in there because that one is still the x86 one.

What to do?

Also - I couldn't build 7.7.0 at all, and that's a huge bummer because in our tests 9.4.1 is like 10x slower on Travis.

**Comment by taoeffect** [comment] 2022-02-01 04:33
> What to do?

Ah ok, so I misread the instructions @stevehodgkiss's instructions, and forgot to do this part:

```
yarn binary-build --version "$(jq -r .version < package.json)"
yarn binary-zip

mv cypress.zip /home/ec2-user/
ls -lah /home/ec2-user/
```

Unzipping the resulting zip file gives me the `Cypress` folder I was looking for. Alternatively you can skip the zip part and grab it from `/tmp/cypress-build/linux/build/Cypress`.

Then replace the folder `~/.cache/Cypress/9.4.1/Cypress` with it and presto everything works!

Now to see if I can figure out how to get 7.7.0 working too...

**Comment by taoeffect** [comment] 2022-02-01 05:03
> Now to see if I can figure out how to get 7.7.0 working too...

While I was able to get 9.4.1 building, I couldn't get 7.7.0 to build. I got as far as running `yarn install --ignore-engines` with node v16, and then ran into:

```
lerna info Executing command in 17 packages: "yarn run build"
cypress: $ yarn postinstall && node ./scripts/start-build.js
@cypress/mount-utils: $ tsc
@cypress/webpack-dev-server: $ tsc
@packages/electron: $ node ./bin/cypress-electron --install
cypress: $ node ./scripts/post-install.js
cypress: set -e
cypress: cp -R /home/dev/Programming/JavaScript/cypress/node_modules/@types/bluebird types
cypress: cp -R /home/dev/Programming/JavaScript/cypress/node_modules/@types/lodash types
@packages/electron: WARNING: Official linux/arm64 support only exists in Electron >= 1.8.0
@packages/electron: moving created file from undefined
@packages/electron: to /home/dev/Programming/JavaScript/cypress/packages/electron/dist/Cypress
@packages/electron: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
@packages/electron:     at Object.stat (node:fs:1458:10)
@packages/electron:     at Object.stat (/home/dev/Programming/JavaScript/cypress/node_modules/graceful-fs/polyfills.js:301:29)
@packages/electron:     at getStats (/home/dev/Programming/JavaScript/cypress/node_modules/fs-extra/lib/util/stat.js:31:8)
@packages/electron:     at Object.checkPaths (/home/dev/Programming/JavaScript/cypress/node_modules/fs-extra/lib/util/stat.js:76:3)
@packages/electron:     at Object.move (/home/dev/Programming/JavaScript/cypress/node_modules/fs-extra/lib/move/move.js:19:8)
@packages/electron:     at Object.move (/home/dev/Programming/JavaScript/cypress/node_modules/universalify/index.js:5:67)
@packages/electron:     at Object.tryCatcher (/home/dev/Programming/JavaScript/cypress/node_modules/bluebird/js/release/util.js:16:23)
@packages/electron:     at Object.ret [as moveAsync] (eval at makeNodePromisifiedEval (/home/dev/Programming/JavaScript/cypress/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
@packages/electron:     at Object.move (/home/dev/Programming/JavaScript/cypress/packages/electron/lib/install.js:56:15)
@packages/electron:     at /home/dev/Programming/JavaScript/cypress/packages/electron/lib/install.js:111:19
@packages/electron: error Command failed with exit code 1.
@packages/electron: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@packages/electron'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by flotwig** [comment] 2022-02-02 14:54
Separate issue to discuss Mac M1 support: https://github.com/cypress-io/cypress/issues/19908

**Comment by sam-mfb** [comment] 2022-02-21 16:05
I created a Dockerfile to build from source based on the script from @stevehodgkiss 

Here it is:
```
FROM node:16-bullseye-slim AS cypress-build
RUN apt-get update
RUN apt-get install -y git vim jq zip unzip gcc
RUN apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
RUN apt-get install -y libgtk-3-dev 
RUN git clone https://github.com/cypress-io/cypress.git
WORKDIR cypress
RUN git checkout tags/v9.3.1 -b build-branch
RUN yarn install
RUN yarn binary-build --version "$(jq -r .version < package.json)" 2>&1 > ./build.docker.log && yarn binary-zip
RUN cp -a /tmp/cypress-build/linux/build/Cypress /Cypress
```

It can be used as part of multi stage build by, for example, including the built file in a subsequent container build, e.g.:
```
COPY --from=cypress-build /Cypress/ /home/some_user/.cache/Cypress/9.3.1/Cypress
```

NB: I had to redirect standard error to standard output in the second to last line above.  This is because some of the tests that run after the build are failing.  The build still seems to work correctly, but if anyone is able to fix those errors, that would be ideal.

NB2: This can be run on an M1 mac (which will build an arm64 docker container), but because this is actually building on linux I posted here rather than on [19908](https://github.com/cypress-io/cypress/issues/19908)

**Comment by sam-mfb** [comment] 2022-02-22 20:10
Also, in terms of the CI/CD testing blocker/problem, even if the pipelines don't have arm64 agents that should, in theory, be able to be overcome using a QEMU image.   See [qemu-user-static](https://github.com/multiarch/qemu-user-static). This is actually the way MSFT recommends doing [multi-arch builds on ADO](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops#how-to-build-linux-container-images-for-architectures-other-than-x64).

If I have some time this week, I'll see if I can put together a POC Dockerfile.

**Comment by AjitKamath** [comment] 2022-03-07 22:30
> As a workaround, I've managed to build Cypress v9.3.1 for `linux-arm64` on an AWS Graviton instance with the following script:
> 
> ```shell
> #!/bin/bash -ex
> 
> yum install -y git vim jq zip unzip gcc-c++
> yum install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
> yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
> git clone https://github.com/cypress-io/cypress.git
> git checkout v9.3.1
> cd cypress
> 
> git clone https://github.com/asdf-vm/asdf.git /usr/local/asdf --branch v0.9.0
> echo ". /usr/local/asdf/asdf.sh" >> ~/.bashrc
> . /usr/local/asdf/asdf.sh
> asdf plugin-add nodejs
> asdf install nodejs $(cat .node-version)
> asdf global nodejs $(cat .node-version)
> 
> npm install -g yarn
> yarn install
> 
> # needed for Cypress v8 and earlier:
> # mkdir -p build
> # ln -s linux-arm64-unpacked ./build/linux-unpacked
> 
> yarn binary-build --version "$(jq -r .version < package.json)"
> yarn binary-zip
> 
> mv cypress.zip /home/ec2-user/
> ls -lah /home/ec2-user/
> ```

@stevehodgkiss I would buy you a coffee if you were nearby. Truly appreciate your answer. I was able to setup Cypress on my RPi4 following your instructions after 3 days !!!.

**Comment by schroedan** [comment] 2022-03-16 09:33
Use this `Dockerfile` to build Cypress v9.3.1 for `linux-arm64` on Apple M1 with `docker build Dockerfile`:
```
FROM node:16.5.0

ENV CYPRESS_VERSION=9.3.1

# Install bild dependencies
RUN set -eux; \
    apt-get update -qq; \
    apt-get install --no-install-recommends -qq \
        # Cypress
        libgtk2.0-0 \
        libgtk-3-0 \
        libgbm-dev \
        libnotify-dev \
        libgconf-2-4 \
        libnss3 \
        libxss1 \
        libasound2 \
        libxtst6 \
        xauth \
        xvfb \
        # utils
        jq \
        zip; \
    rm -rf /var/lib/apt/lists/*

# Install package managers
RUN set -eux; \
    npm install --global --force --silent \
        yarn; \
    rm -rf ~/.npm

# Clone source
RUN set -eux; \
    git clone --depth=1 --branch "v${CYPRESS_VERSION}" https://github.com/cypress-io/cypress.git /cypress

WORKDIR /cypress

# Build Cypress from source
RUN set -eux; \
    yarn install --frozen-lockfile; \
    yarn binary-build --version "${CYPRESS_VERSION}"; \
    yarn binary-zip
```

**Comment by flotwig** [comment] 2022-06-10 21:45
I've started a PR to add 64-bit Linux Arm support (`arm64`, `aarch64`, `armv8`) that will close this issue: https://github.com/cypress-io/cypress/pull/22252

This will still not provide support for 32-bit Arm (`armv7`). So I can get an idea of the demand for this, who here specifically needs 32-bit Arm support in Cypress, not 64-bit Arm?

**Closed** 2022-06-15 16:22 UTC
Labels: type: feature, OS: linux, stage: needs review
