### ISSUE TITLE
Blur active element if cy.type subject is 'body'

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2243] opened 2018-07-30 16:30 UTC
**Currently**, if `cy.type`'s subject is `body`, Cypress will not blur the active element, and instead just send key events to the body while ignoring typing any characters and skipping actionability checks

**Instead**, Cypress should blur the active element. This makes sense because the user can't type into the body if there is an active element that's typeable

**Comment by jennifer-shehane** [comment] 2019-07-13 02:32
Relevant issue where when you type in the keyboard on a browser with nothing focused...it focuses the input and types - so they want this behavior replicated and try to replicate it by typing into 'body' https://github.com/cypress-io/cypress/issues/4650

**Comment by jennifer-shehane** [comment] 2021-01-05 09:24
I don't think this is an issue anymore since 3.5.0. Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-01-05 09:24 UTC
Labels: stage: ready for work, topic: cy.type ⌨️, type: breaking change, type: enhancement
