### ISSUE TITLE
If "We detected that the Chromium Renderer process just crashed." still output report

### ISSUE THREAD

**Issue by tomardern** [cypress-io/cypress#3602] opened 2019-02-27 10:41 UTC
### Current behavior:
If cypress crashes due to "We detected that the Chromium Renderer process just crashed.", it does not produce a mocha report:

```
Checkout Test
 ✓ Can load the site (5958ms)
We detected that the Chromium Renderer process just crashed.
 This is the equivalent to seeing the 'sad face' when Chrome dies.
 This can happen for a number of different reasons:
 - You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium
 You can learn more including how to fix Docker here:
 https://on.cypress.io/renderer-process-crashed
 (Results)
 ┌──────────────────────────────────────┐
 │ Tests: 0 │
 │ Passing: 0 │
 │ Failing: 1 │
 │ Pending: 0 │
 │ Skipped: 0 │
 │ Screenshots: 0 │
 │ Video: true │
 │ Duration: 0 seconds │
 │ Spec Ran: checkout/basic.spec.js │
 └──────────────────────────────────────┘
 (Video)
 - Started processing: Compressing to 32 CRF
 - Finished processing: frontend/tmp/cypress/videos/checkout/basic.spec.js.mp4 (6 seconds)

```
^^ (Note no mocha report is generted)

### Desired behavior:
The mocha report is also outputted/saved, this is so that (for us) the mocha-awesome report can be generated and uploaded via our CI.

### Steps to reproduce: (app code and test code)
Make the chrome renderer crash.

### Versions
Latest cypress, we are running on CI/CD (AWS CodeBuild) - all other tests are fine, it's this one that randomly crashes. (Thats another issue). 

If this is an issue with the reporter - please let me know and I'll raise an issue there.

Thanks :)

**Comment by Nomeasmo** [comment] 2019-07-23 14:50
We also have this issue in a flaky manner, so cannot provide a working example. But it shows the tests run with version 3.2.0 but are failing with 3.3.2 and 3.4.

Maybe this helps. (Internally we think it might be the electron version)

**Comment by darkyndy** [comment] 2019-11-13 05:17
I started to encounter this error with version 3.6.0 and now tested with 3.6.1 and still happens.

With 3.4.1 version I never encountered it.

**Comment by mattrlong** [comment] 2019-11-26 17:04
Also started experiencing this while attempting to upgrade from 3.4.0 -> 3.6.1

**Comment by jasondeng** [comment] 2019-11-30 01:42
Started encountering this after upgrading from 3.4.1 -> 3.7.0

**Comment by mattrlong** [comment] 2019-12-03 16:45
@jasondeng @darkyndy are you using kubernetes by any chance?

**Comment by darkyndy** [comment] 2019-12-03 16:58
@mattrlong yes

**Comment by mattrlong** [comment] 2019-12-03 17:05
> @mattrlong yes

Same, and also experiencing this issue. How many parallel runners are you using? Are you using resource limits on your Pods?

**Comment by mattrlong** [comment] 2019-12-03 17:12
Have you tried to prevent this issue in the past? `ipc=host` solution processed I've been advised against in my k8 pod definition. I'm currently using shared /dev/shm volume mounts. This prevents the issue on 3.4.1 for me, but crashes on every Jenkins build for me on 3.6.1 & 3.7.0. 

Wondering if this is something you're also experiencing?

**Comment by darkyndy** [comment] 2019-12-03 17:29
I do not have access to k8s setup as this is maintained by the Ops team and as I'm the owner of the single project that uses Cypress they will not do any changes specific to my project.

If it is a way to configure cypress or to run some bash script (I have sudo) on the docker image that could be a solution for me.

**Comment by davidzambrana** [comment] 2019-12-10 15:34
We also started seen this after upgrading to 3.7.0

It only breaks in our CI where we use k8s

**Comment by nantoniazzi** [comment] 2019-12-13 13:58
We have tried an upgrade to 3.7.0 and we have the same issue (tests are run from docker, in gitlab-ci)

**Comment by pshynin** [comment] 2020-01-17 19:59
we have circle-ci and also jenkins-kuberneties.. crushing in both. 
kuberneties kills cypress pods due to spikes in CPU usage, but circle-ci crushes with exact same error message... 
spent few days figuring out, gave up for now and downgraded back to 3.4.1

**Comment by domachine** [comment] 2020-01-19 20:34
> we have circle-ci and also jenkins-kuberneties.. crushing in both.
> kuberneties kills cypress pods due to spikes in CPU usage, but circle-ci crushes with exact same error message...
> spent few days figuring out, gave up for now and downgraded back to 3.4.1

Same here. In my case I use cypress to test a ReST API. I do not even load a website. Just sending requests using `cy.request()`. It's really strange. Each time a core dump is created. It happens only when being run on the CI server. Locally everything works like a charm.

**Comment by ameem91** [comment] 2020-02-02 02:00
I'm also seeing this same issue. I stub all requests using mock data, so my tests don't even take that long to run. I'm on 3.8.2.

**Comment by dialex** [comment] 2020-02-18 17:50
I'm having the same issue, with the latest Cypress (`4.0.1`) on self-hosted GitLab.
If I run them locally, they pass without issues (at least so far).

**Comment by khalalw** [comment] 2020-02-22 01:42
Also running into this same issue. We were looking to upgrade to Cypress 4.0.x, but cannot. Works fine on 3.4.1

**Comment by michaelhayman** [comment] 2020-02-25 17:46
Running into a similar issue on 4.0.2.  Wasn't seeing the issue on earlier versions.

**Comment by JoniVR** [comment] 2020-02-26 15:17
We are running into the same issue on Gitlab CI

| Technology | Version |
---|---
| Cypress | 4.0.2 |
| Electron | Electron 78 (headless) |

**Comment by JoniVR** [comment] 2020-02-26 16:58
Here's our fix for Cypress `4.0.2` (we use Gitlab CI):

1. We changed our run command to use `chrome` instead of `electron`
```
"e2e-headless": "ng e2e --headless --browser chrome",
```
(might be a different command for you because we use angular, just append `--browser chrome`)

2. Then inside the `cypress/plugins/index.js` file we added the following to enable the `--disable-dev-shm-usage` chrome flag:
```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  on('before:browser:launch', (browser = {}, launchOptions) => {
    // `args` is an array of all the arguments that will
    // be passed to browsers when it launches

    if (browser.family === 'chromium' && browser.name !== 'electron') {
      // see: https://github.com/cypress-io/cypress/issues/3633
      launchOptions.args.push('--disable-dev-shm-usage');

      // whatever you return here becomes the launchOptions
      return launchOptions;
    }
  });
};
```

Then, in our ci conflig, we changed the image to:
```
image: cypress/browsers:node12.13.0-chrome80-ff73
```
So we could use chrome 80 (not sure if chrome 80 is necessary but doesn't hurt)

After that our CI passed without issues, hope this helps any other poor souls running into this :)

**Comment by ktoley** [comment] 2020-04-03 21:42
This issue seems to be back.  Electron crashes in its first attempt to validate a link. The ipc host setting does not seem to be doing anything on Gitlab Public Runners.
Running in GitLab on public runners.  Job including:

**image: cypress/base:10**
 $(npm bin)/cypress run
_Crash_

**image: docker**
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
 docker run -i -e "CYPRESS_baseUrl=http://<server>:8080" --ipc=host -v $PWD:/e2e -w /e2e cypress/included:4.3.0
_Crash_

**image: docker/compose:latest**
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
docker-compose up --abort-on-container-exit
With compose yml settings including:
    ipc: host
    image: cypress/included:4.3.0
    shm_size: 4096000000
_Crash_

**Comment by leads** [comment] 2020-07-16 15:45
@JoniVR re point 3, you've change the docker image. What do you install cypress with? As the image you use doesn't include the runner itself. (Unless I'm mistaken.) 
Thanks

**Comment by JoniVR** [comment] 2020-07-16 15:55
@leads We run the `npm ci` command first, which installs cypress through npm if not available (we've also cached the cypress cache folder so it doesn't have to download it every time). 

Although I'm pretty sure you'll be able to find base images that have cypress included with chrome 80+ by now, I just said v80+ because I wasn't sure if that specific argument was supported before v80.

**Comment by leads** [comment] 2020-07-16 16:13
Thanks @JoniVR for such a quick response. Ours is all done via a docker file which uses `cypress/included:4.0.2` and that is what installs cypress.

I'll have a play with your solution.

**Comment by mirobo** [comment] 2023-04-11 09:29
With Cypress 10.7.0 I have observed a similar behaviour. I didn't check whether the output report exists. But when a test fails with "Chromium Renderer process just crashed" it will not be reported to sorry-cypress (and probably also not Cypress dashboard). Luckily the build job in GitLab will fail but the test itself in sorry-cypress will remain in the state "Running" and will turn into "timed out" or something else later on.

Also these test failures are not retried (see #349)

Anybody who is using sorry-cypress with cypress-cloud could probably also profit from this feature request  https://github.com/currents-dev/cypress-cloud/issues/121 but ideally it would be solved in Cypress itself.

**Comment by nagash77** [comment] 2023-04-11 19:46
This issue is for a very old version of Cypress.  I am going to close it.  If anyone has a reproducible example on a later version of Cypress please comment back here or open a new issue and we will be happy to investigate.

**Closed by nagash77** 2023-04-11 19:46 UTC
Labels: stage: needs investigating, topic: reporters 📄, Popular Issue
