### ISSUE TITLE
Firefox does not recognise localhost as a secured origin when running through Cypress

### ISSUE THREAD

**Issue by Pixcell** [cypress-io/cypress#16611] opened 2021-05-20 22:39 UTC
### Current behavior

When running through Cypress, Firefox does not consider `http://localhost:3000` to be a secured origin
![image](https://user-images.githubusercontent.com/4005291/119057051-e2fe4800-ba1f-11eb-9cc3-92029b1f9eb9.png)

Although, when running outside of Cypress, it works perfectly fine
![image](https://user-images.githubusercontent.com/4005291/119057143-0f19c900-ba20-11eb-9300-57ab6091894a.png)

### Desired behavior

When running through Cypress runner, with Cypress extension, firefox should still consider localhost as a secured origin

### Test code to reproduce

Any React application with @auth0/auth0-react authentication in place.

Currently this is a private project. I can provide a small repo that reproduce the issue if it helps. Let me know.

### Versions

Cypress 7.3.0
Firefox 88.0.1 (64-bit) (started by Cypress)
Firefox 88.0.1 (64-bit) (started manually)

**Comment by jennifer-shehane** [comment] 2021-05-21 14:19
Yes, if you can provide a small repo that reproduces the issue, that would help.

**Comment by Pixcell** [comment] 2021-05-23 20:45
Hi @jennifer-shehane ,

Please find a public github repo with a minimal setup to reproduce the issue.

https://github.com/Pixcell/cypress-16611

Thanks!

**Comment by Pixcell** [comment] 2021-10-04 02:30
Any update on this?
This is becoming a big problem

**Comment by th1nkgr33n** [comment] 2023-05-25 22:14
@Pixcell I don't know if this helps you, but I had the same issue.
Commented here (https://github.com/cypress-io/cypress/issues/18217#issuecomment-1563568197)

I solved the problem to set the cypess.config.ts e2e.baseUrl from "localhost" to "127.0.0.1"

**Comment by nagash77** [comment] 2023-05-26 13:38
I am going to close this as a duplicate of [18217](https://github.com/cypress-io/cypress/issues/18217#issuecomment-1563568197).  Please follow that issue for updates on any work in this area.

**Closed by nagash77** 2023-05-26 13:38 UTC
Labels: stage: needs information

**Comment by joacopaz** [comment] 2025-05-09 15:17
> [@Pixcell](https://github.com/Pixcell) I don't know if this helps you, but I had the same issue. Commented here ([#18217 (comment)](https://github.com/cypress-io/cypress/issues/18217#issuecomment-1563568197))
> 
> I solved the problem to set the cypess.config.ts e2e.baseUrl from "localhost" to "127.0.0.1"

This was the fix for me, had the same issue testing through browserstack. Accessing localhost thru 127.0.0.1 provided the much needed secure context
