### ISSUE TITLE
cypress builtin retry function causes allocation failure or hanging forever  

### ISSUE THREAD

**Issue by 0xIslamTaha** [cypress-io/cypress#9546] opened 2020-12-07 10:59 UTC
### Current behavior
I'm using the official docker cypress images to run my test cases in our jenkins machines. Since cypress 5, I replaced the **cypress-retry-plugin** with the builtin retry cypress option and since then, sometimes test cases got hanging or throw the following error. 
```
<--- Last few GCs --->

[18:0x38bf00000000]   408300 ms: Mark-sweep 1992.3 (2067.9) -> 1985.9 (2069.4) MB, 1468.7 / 0.0 ms  (average mu = 0.201, current mu = 0.028) allocation failure scavenge might not succeed
[18:0x38bf00000000]   409960 ms: Mark-sweep 1993.8 (2069.4) -> 1987.2 (2070.9) MB, 1626.2 / 0.0 ms  (average mu = 0.114, current mu = 0.021) allocation failure scavenge might not succeed


<--- JS stacktrace --->

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Debian - 10.6)
Cypress Version: 6.0.1

```

### WORKAROUND:
I had to roll-back to Cypress 4.12.0 and use the **cypress-retry-plugin** again.

### Desired behavior
Test cases should be running without hanging nor throwing the previous error.

### Test code to reproduce
Any long spec with many failures will produce the previous scenario. 

### Versions

Platform: linux (Debian - 10.6)
Cypress Version: 6.0.1

**Comment by jennifer-shehane** [comment] 2020-12-07 11:22
Can you provide a reproducible example? We won't be able to look into it without test cases that show the retry errors. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by c32hedge** [comment] 2020-12-15 17:37
@jennifer-shehane I added a reproducible example of the hang behavior to #9040 almost a month ago--could be the same thing?

**Comment by jennifer-shehane** [comment] 2020-12-16 05:33
Closing as duplicate of #9040, although can't be 100% sure since a reproducible was not provided.

**Closed by jennifer-shehane** 2020-12-16 05:33 UTC
Labels: stage: needs information, topic: SIG errors, topic: test retries ♻️
