### ISSUE TITLE
Slow Rendering Performance During Tests

### ISSUE THREAD

**Issue by lots0logs** [cypress-io/cypress#4638] opened 2019-07-02 22:18 UTC
### Current behavior:
There is currently very noticeable lag during certain animations when running tests. This only happens during test runs. I recorded a profile in devtools. You can grab it [here](https://drive.google.com/file/d/1JIKvw6Bi_3UtAdjZIf5lLndqIaAWM1Jv/view?usp=sharing).

### Desired behavior:
Cypress test runner not causing lag during tests.

### Steps to reproduce: (app code and test code)
I'm not sure which exact steps would provide you with a way to reproduce this. I suspect it has something to do with the size of the dom and the amount of CSS styles loaded.

### Versions
Cypress: 3.3.2
Chrome: 75

**Comment by jennifer-shehane** [comment] 2019-07-03 03:57
Hey @lots0logs, can you run these same tests in some previous versions and log the performance? Particularly 3.3.1 and 3.2.0? This way we can narrow down if this has always been happening or if it is a regression from one of our recent releases - where we made many changes for performance.

We can look into it, but the debugging will be must faster if you can provide a reproducible repo for us to run on our side as it's likely some edge-case with your app/css styles/tests that we haven't run into.

**Comment by lots0logs** [comment] 2019-07-03 18:32
I think the profile I included should be helpful considering the amount of details it includes. It shows that every time the runner's callback runs it takes over 400ms. It spends most of that time doing something with CSS styles AFAICT. Because the callback runs so frequently it causes significant animation janking and lag.

**Comment by jennifer-shehane** [comment] 2020-01-14 06:59
@lots0logs Is this performance issue still occurring in version 3.8.2?

**Comment by jennifer-shehane** [comment] 2020-12-17 07:27
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-12-17 07:27 UTC
Labels: stage: needs information, type: performance 🏃‍♀️
