### ISSUE TITLE
Vue2 Component Tests fails to run on Cypress 12.2.0 - 12.3.0

### ISSUE THREAD

**Issue by rowellx68** [cypress-io/cypress#25483] opened 2023-01-17 16:42 UTC
### Current behavior

Vue2 component tests have started breaking since upgrading to 12.3.0 with the following exceptions. Removing the `tsconfig.json` from the `cypress` folder fixes the issue somehow, but doing so causes TypeScript to flag the files in the `cypress/e2e` folder.

### Screenshot

<img width="1312" alt="Cypress UI showing exception" src="https://user-images.githubusercontent.com/10155704/212957446-32f35c24-2e59-4bb9-ba66-f46c298843a1.png">

### Stack Trace

```
at ./node_modules/.pnpm/cypress@12.3.0/node_modules/cypress/vue2/dist/cypress-vue2.cjs.js ([webpack://vue2-vue-cli-component-tests-broken/./node_modules/.pnpm/cypress@12.3.0/node_modules/cypress/vue2/dist/cypress-vue2.cjs.js:19725:27](http://localhost:8080/__/#))
    at __webpack_require__ (http://localhost:8080/__cypress/src/main.js:23:42)
    at ./cypress/support/component.ts ([webpack://vue2-vue-cli-component-tests-broken/./cypress/support/component.ts:21:13](http://localhost:8080/__/#))
    at Function.__webpack_require__ (http://localhost:8080/__cypress/src/main.js:23:42)
From previous event:
    at evalScripts (http://localhost:8080/__cypress/runner/cypress_runner.js:158641:58)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:158650:152)
From previous event:
    at runScriptsFromUrls (http://localhost:8080/__cypress/runner/cypress_runner.js:158650:136)
    at Object.runScripts (http://localhost:8080/__cypress/runner/cypress_runner.js:158664:12)
    at $Cypress.onSpecWindow (http://localhost:8080/__cypress/runner/cypress_runner.js:147384:75)
    at init (http://localhost:8080/__cypress/src/chunk-vendors.js:63:11)
    at ../../../Library/Caches/Cypress/12.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/loader.js!../../../Library/Caches/Cypress/12.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/browser.js (http://localhost:8080/__cypress/src/chunk-vendors.js:38:3)
    at __webpack_require__ (http://localhost:8080/__cypress/src/main.js:23:42)
    at render (http://localhost:8080/__cypress/src/chunk-vendors.js:80:3)
    at ../../../Library/Caches/Cypress/12.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/browser.js (http://localhost:8080/__cypress/src/chunk-vendors.js:82:1)
    at __webpack_require__ (http://localhost:8080/__cypress/src/main.js:23:42)
    at <unknown> (http://localhost:8080/__cypress/src/main.js:294:109)
    at __webpack_require__.O (http://localhost:8080/__cypress/src/main.js:59:23)
    at <unknown> (http://localhost:8080/__cypress/src/main.js:295:53)
    at <unknown> (http://localhost:8080/__cypress/src/main.js:297:12)
```

### Desired behavior

Cypress should run the Vue2 component tests successfully.

### Test code to reproduce

https://github.com/rowellx68/vue2-vue-cli-component-tests-broken

### Cypress Version

12.3.0

### Node version

16.19.0

### Operating System

macOS 13.1

### Other

I have tried versions 12.0.0 - 12.1.0 and can confirm that the component tests run as expected.

**Comment by ZachJW34** [comment] 2023-01-17 18:45
I can reproduce this issue, looks like it was indeed introduced in 12.2.0. The global `Vue` object is defined prior but is now no longer defined. Going to quickly look to see what might have caused this change but will get this routed to the CT Team shortly. Thanks for opening the issue!

Edit: We upgraded to Rollup@3, changing how `cypress/vue2` was bundled. Looks like this is what caused the issue

**Comment by astone123** [comment] 2023-01-24 22:05
@rowellx68 I haven't been able to reproduce this outside of the project that you gave us. After spending some time on this, I think you can work around it by updating `cypress/tsconfig.json` to target `es6`:

```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.ts"]
}
```

This fixes the issue for me. Please try this out and let us know if it works for you. I think we should close this out for now and come back to it if this becomes a more widely reported issue. Thanks

**Closed as completed by astone123** 2023-01-24 22:05 UTC
Labels: CT

**Comment by rowellx68** [comment] 2023-01-30 12:00
@astone123 thanks for taking time to look into this. I've just tried the workaround and it seems to be working as expected.
