### ISSUE TITLE
Unable to upload files using Cypress 6.2.1 and Multer middleware

### ISSUE THREAD

**Issue by arinabarnett** [cypress-io/cypress#14555] opened 2021-01-14 13:02 UTC
### Current behavior
Our team recently decided to upgrade Cypress version to 6.2.1 to utilise `cy.intercept()` in our project and with the new version we're facing an issue: 
In our application we have  two input forms that are used to upload files from user's system. In our project we use [multer](https://www.npmjs.com/package/multer) as a middleware. We have two routes in our app, the first one is used to upload a single file (using multer's `.single()` method), and the second on is to upload multiple files(using multer's `.array()` method). Everything work's fine with with the first route, file is uploaded correctly. 
However, when we use the second route - that should allow to upload multiple files - it doesn't work at all. The POST request is being sent and the file seems to be processing correctly, but in the end it doesn't upload (not only when running a specific test, just in general when we try to do it in Chrome 87 with the cypress running).
fileFilter method of multer is not called with .array() therefore 'files' property is not added to req object

### Desired behavior
The file should be uploaded correctly (the code works with Cypress 5.0)

### Test code to reproduce

Code that works with Cypress 5.0:

routes.js 
```js
router.post('/:caseId', uploadFile.array('files'), controller.upload);
router.post('/:caseId/previous-case/snapshot', uploadFile.single('file'), controller.uploadPreviousCase);
```
input-work.js
```js
function uploadFile(filePath, inputSelector, fixtureAlias = 'caseFile') {
  const fileName = filePath.split('/').slice(-1)[0];
  cy.fixture(filePath, 'base64').as(fixtureAlias);

  return cy.get(inputSelector).then(function (input) {
    const blob = Cypress.Blob.base64StringToBlob(this[fixtureAlias])
    uploadBlobToInput(input, blob, fileName);
  });
}

function uploadBlobToInput(input, blob, fileName) {
  const testFile = new File([blob], fileName);
  const dataTransfer = new DataTransfer();
  dataTransfer.items.add(testFile);
  input[0].files = dataTransfer.files;
  input[0].dispatchEvent(new Event('change', { bubbles: true }));
}
```
api-work.js
```js
function APIListener({route, method = 'POST', onRes = () => {}, alias = 'APIResponse'}) {
  cy.server().route({
    url: `${Cypress.config().beUrl}${route}`,
    method: method,
    onResponse: (res) => {
      onRes(res);
    }
  }).as(alias);
}

function APIAction(routeObject, trigger = () => {}) {
  APIListener(routeObject);
  trigger();
  cy.wait(`@${routeObject.alias}`);
}
```
test-example.js
```js
And(`user uploaded {string} case`, caseName => {
  const CaseFiles = Cases[caseName];
  const TTDFiles = CaseFiles.TTDFiles.map(fileName => {
    return { 
      path: `${CaseFiles.TTDPath}${fileName}`, 
      fileName: `${fileName}`
    };
  });

  TTDFiles.forEach(TTDFile => {
    apiWork.APIAction(casesRoutes.uploadTTD, () => uploadFile(TTDFile.path, '#thisPeriodFileInput'));
    cy.get('#FilesList li').contains(TTDFile.fileName);
  });

  cy.get('.choose-pr-case span').contains('Upload snapshot').click();
  // We have exactly the same code for uploading a single file, just using a different route and input selector
});
```
Code that doesn't work with Cypress 6.1.0:

input-work.js 
```js
function uploadFile(filePath, inputSelector, fixtureAlias = 'caseFile') {
  const fileName = filePath.split('/').slice(-1)[0];
  cy.fixture(filePath, 'base64').as(fixtureAlias);

  return cy.get(inputSelector).then(function (input) {
    const blob = Cypress.Blob.base64StringToBlob(this[fixtureAlias]) 
    uploadBlobToInput(input, blob, fileName);
  });
}

function uploadBlobToInput(input, blob, fileName) {
  const testFile = new File([blob], fileName);
  const dataTransfer = new DataTransfer();
  dataTransfer.items.add(testFile);
  input[0].files = dataTransfer.files;
  input[0].dispatchEvent(new Event('change', { bubbles: true }));
}
```

api-work.js
```js
function APIListener({ route, method = 'POST', onRes = () => { }, alias = 'APIResponse' }) {
  const url = new RegExp(`${Cypress.config().beUrl.replaceAll('/', '\\/')}${route}`);

  cy.intercept({
    url,
    method,
    matchUrlAgainstPath: false
  },
  (req) => {
    req.reply(res => {
      onRes(res);
    });
  }
  ).as(alias);
}
```
Other code is the same

### Versions
Cypress 6.2.1, Chrome 87, MacOS Sierra 10.12.6

**Comment by bahmutov** [comment] 2021-01-14 14:05
Can you add a reproducible example (including server code and spec file) to https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept ? There is code there to spin server, do responses, and there are Cypress spec files. If we can run the code to see the problem, we can work on the issue.

**Comment by sakuranasty** [comment] 2021-01-20 11:05
What's the right way to add the example there? I can't push to your repo and I'm not familiar with how to contribute to projects

**Comment by sakuranasty** [comment] 2021-02-24 14:04
Sorry for the long answer, I have half code working, but I can't upload there, do I need to bacome a contributor?

**Comment by bahmutov** [comment] 2021-02-24 14:11
You should create a new public repo under your GitHub account, push code there and then post a link to it

**Comment by samtsai** [comment] 2021-02-24 16:53
@arinabarnett does it work in `6.2.0` if so, I wonder if it's related to #14527

**Comment by flotwig** [comment] 2021-03-24 23:05
I believe this is a duplicate of #14527, let's move discussion + repros there

**Closed by flotwig** 2021-03-24 23:05 UTC
Labels: pkg/net-stubbing, stage: needs information
