### ISSUE TITLE
Cypress route() random url structure and headers

### ISSUE THREAD

**Issue by kevinch** [cypress-io/cypress#2619] opened 2018-10-16 17:53 UTC
### Current behavior:
Structure of the spec:
```js
describe('Accounts', () => {
  before(() => {
    cy.login()
    cy.visit('/accounts')
  })

  context('Loading stubbed accounts', () => {
    it('should display 10 accounts', () => {
      cy.server()
      cy.route(
        `${apiUrlBase}/accounts?&to=9&sort=lastUpdate&order=asc`,
        accountsMock,
      ).as('getAccounts')

      cy.wait('@getAccounts')

      ...
```

`cy.login()` being a custom command in `commands.js` to do a login process with two `cy.request()` and a `cy.setCookie()`.

The `cy.wait('@getAccounts')` works fine roughly 13 out of 15 times.

I've whitelisted the cookie set in the `login` function so it is kept through the whole process.

#### What i've seen:

When `cy.wait()` works fine, my request has an extra url section set by Cypress: 
```
https://sub.mydomain.com/__cypress/xhrs/
```
like so: 
```
https://sub.mydomain.com/__cypress/xhrs/https://sub.mydomain.com/api/cc/accounts?&to=9&sort=lastUpdate&order=asc
```
as well as specific request headers:
```
X-Cypress-Delay: 0
X-Cypress-Id: xhr309
X-Cypress-Matched: https://sub.mydomain.com/api/cc/accounts?&to=9&sort=lastUpdate&order=asc
X-Cypress-Response: ...
X-Cypress-Status: 200
```

When `cy.wait()` fails, my request does not have the extra url section: 
```
https://sub.mydomain.com/api/cc/accounts?&to=9&sort=lastUpdate&order=asc
```
and none of the headers written above.

The error logged goes as follow:
```
Uncaught TypeError: Cannot set property 'aborted' of undefined
```

#### Note:
All the xhr requests return 200.

### Desired behavior:
Consistent results.

### Versions
Cypress: `3.1.0`
React: 16.x

I know it might be very specific but if anyone has inputs i'd be glad to hear them.
Cheers.

**Comment by jennifer-shehane** [comment] 2018-10-17 20:33
You usually want to define your `cy.server()` and `cy.route()` before a `cy.visit()`. Defining a `cy.route()` is essentially saying "listen for this route", so if the route had happened right after `cy.visit()` and before `cy.route()`, you'd have some issues. Not saying this is the problem you are having, but one observation that may not be helping. 

There is an issue open involving the `Cannot set property 'aborted' of undefined` error here: It would help a lot if you could provide a reproducible example there. https://github.com/cypress-io/cypress/issues/761 Going to close as duplicate of this.

**Closed by jennifer-shehane** 2018-10-17 20:33 UTC
