### ISSUE TITLE
Socket closed before finished writing response.

### ISSUE THREAD

**Issue by asimplify** [cypress-io/cypress#29938] opened 2024-07-30 15:22 UTC
### Current behavior

I am running a cypress e2e test and its just a click and redirect flow of a web app. the web app BE returns streaming response and its being handled in FE and cypress is not intercepting or anything with the apis. However, in one particular api, I get this error:
```
Error:                    Error: Socket closed before finished writing response.
    at ServerResponse.b (<embedded>:2792:46765)
    at ServerResponse.emit (node:events:526:35)
    at emitCloseNT (node:_http_server:996:10)
    at TLSSocket.onServerResponseClose (node:_http_server:278:5)
    at TLSSocket.emit (node:events:526:35)
    at node:net:323:12
    at Socket.done (node:_tls_wrap:588:7)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:323:12)
```
![image](https://github.com/user-attachments/assets/dd37be1d-973a-4401-800e-0c9cef42aa81)

and this api is not getting any response, however all the other apis are getting response as they should and all are of streaming type.

### Desired behavior

It should give response as it is giving for other api.

### Test code to reproduce

This my cypress test:

```js
describe("Normal Flow", () => {

  it("checksLR", () => {
    cy.visit("/");
    cy.get("[placeholder='Enter your email']")
      .type("some@gmail.com")
      .should("have.value", "somegmail.com");
    cy.get("[placeholder='Enter your password']")
      .type("password")
      .should("have.value", "password");
    cy.contains("Continue").click();
    cy.location("pathname", { timeout: 10000 }).should("include", "/chat");
    cy.wait(5000);
    cy.get('[data-id="Litigation"]').click();
    cy.get('[data-id="legalResearchModule"]').click();
    cy.location("pathname", { timeout: 10000 }).should(
      "include",
      "/legalResearchModule"
    );
    cy.get('[data-id="guide-modal-close"]', { timeout: 8000 }).click();
    cy.get('[data-id="pre-selection"]').click({ force: true });
    cy.get('[data-id="menu-selection-0"]').click();
    cy.contains("quick answer").click();
    cy.wait(5000);
    })})
```

### Cypress Version

13.13.1

### Node version

20.15.1

### Operating System

windows 10

**Comment by jennifer-shehane** [comment] 2024-08-09 15:01
Duplicate of https://github.com/cypress-io/cypress/issues/26248

**Closed as not planned by jennifer-shehane** 2024-08-09 15:01 UTC
Labels: type: duplicate

**Comment by RicardoInuits** [comment] 2024-08-20 15:02
Any progress on this bug? Im trying to find a work around but it seems downgrading node & cypress is not helping. therefore im waiting for a bug fix as this is pretty critical.

**Comment by jennifer-shehane** [comment] 2024-08-21 14:25
Comment in the other issue - this is a duplicate. https://github.com/cypress-io/cypress/issues/26248
