### ISSUE TITLE
Component Test cases not running though cmd shows client compiled successfully

### ISSUE THREAD

**Issue by shivani-sonawane-ntt** [cypress-io/cypress#26144] opened 2023-03-17 13:42 UTC
### Current behavior

![image](https://user-images.githubusercontent.com/97085081/225915329-29cd2132-8a69-485c-ac45-4beda24131bd.png)
I run test cases using => 
@1.0.0 test:run
> cypress run-ct 

But I did not get any error anything else but test cases get stuck on the level as shown in screenshot.
We did not changed anything in code or any version and it was working fine before and suddenly stopped working and getting stuck here only.

### Desired behavior

It should run all the spec.tsx files and show coverage like this
![image](https://user-images.githubusercontent.com/97085081/225919422-e6a3fdd3-2b64-4882-8604-9eab2d5267ab.png)

### Test code to reproduce
```js
import { mount } from '@cypress/react';

import { ADFilterButton } from '.';

const getDetailsSpan = (text: string, className: string) => {
    cy.getCy('ad-filter-button')
        .should('be.visible')
        .should('have.class', className)
        .find('span')
        .should('have.class', 'text-10x15 text-grey-500')
        .contains(text);
};

describe('<ADFilterButton with different text than selected button />', () => {
    beforeEach(() => {
        const componentProps = {
            col2AgeFilter: 'All',
            col3AgeFilter: 'All',
            colNumber: 2,
            onClickButton: cy.spy().as('onClickButton'),
            text: 'last month',
        };
        mount(<ADFilterButton {...componentProps} />);
    });

    it('with different text', () => {
        cy.getCy('ad-filter-button').should('be.visible').click();
        cy.get('@onClickButton').should('have.been.calledOnce');
        cy.get('@onClickButton').should('have.been.calledWith', 2, 'last month');
        getDetailsSpan('last month', 'py-[2px] px-[10px] rounded bg-white border-0.5 font-medium');
    });
});

describe('<ADFilterButton with same text as selected button />', () => {
    beforeEach(() => {
        const componentProps = {
            col2AgeFilter: 'All',
            col3AgeFilter: 'last month',
            colNumber: 3,
            onClickButton: cy.spy().as('onClickButton'),
            text: 'last month',
        };
        mount(<ADFilterButton {...componentProps} />);
    });

    it('with same text', () => {
        getDetailsSpan('last month', 'py-[2px] px-[10px] rounded bg-blue-500 font-semibold');
    });
});
```

### Cypress Version

9.1.1

### Node version

v18.13.0

### Operating System

Windows - 10

### Other

We use 
```
"@cypress/code-coverage": "3.9.12",
"@cypress/react": "5.10.3",
"@cypress/webpack-dev-server": "1.7.0",
"next": "^12.1.5",
"react": "17.0.2",
```

My chrome version is - 111.0.5563.65 
![image](https://user-images.githubusercontent.com/97085081/225918500-9a94f8f1-e67b-48c8-ba56-f164f620e77f.png)

**Comment by mike-plummer** [comment] 2023-03-17 14:18
Hi @ShivaniNTT , sorry to hear you're having trouble. We would first ask you to provide [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) - these may provide additional information of what is happening. In addition:
1. Have you tried running your test in "open" mode via `open-ct`? Do you get different behavior or additional logging (either in the terminal or browser console)?
2. Have you tried with an alternate browser? You're using Electron by default per the screenshot, can you try Chrome `--browser chrome`?
3. You're using a fairly old version of Cypress (9.1.1 was released in December 2021) - have you tried upgrading to a newer version? Component Testing was officially released (GA) in version 11, and we're now on 12.8.1

**Comment by lmiller1990** [comment] 2023-03-28 04:29
Happy to reopen once we've got more information to continue debugging. Until then, I'll close this, since I don't see any actionable work in Cypress relating to this issue.

**Comment by shivani-sonawane-ntt** [comment] 2023-03-31 06:28
> Hi @ShivaniNTT , sorry to hear you're having trouble. We would first ask you to provide [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) - these may provide additional information of what is happening. In addition:
> 
> 1. Have you tried running your test in "open" mode via `open-ct`? Do you get different behavior or additional logging (either in the terminal or browser console)?
> 2. Have you tried with an alternate browser? You're using Electron by default per the screenshot, can you try Chrome `--browser chrome`?
> 3. You're using a fairly old version of Cypress (9.1.1 was released in December 2021) - have you tried upgrading to a newer version? Component Testing was officially released (GA) in version 11, and we're now on 12.8.1

I tried to 1st and 2nd point its not working open-ct stuck on same point not running test cases, and even if I change browser still facing same issue and point 3 will take some time

**Comment by mike-plummer** [comment] 2023-03-31 13:15
@ShivaniNTT The best way for us to help you is if you can provide a reproducible reproduction case, ideally a Git repo we can clone and run ourselves. Having a reproduction case makes it much easier to identify and resolve your issue. If you can't create a reproduction case then we would need [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs).

**Comment by shivani-sonawane-ntt** [comment] 2023-04-03 06:40
> @ShivaniNTT The best way for us to help you is if you can provide a reproducible reproduction case, ideally a Git repo we can clone and run ourselves. Having a reproduction case makes it much easier to identify and resolve your issue. If you can't create a reproduction case then we would need [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs).

Hi @mike-plummer, Here is the log. 
[dubuglog.log](https://github.com/cypress-io/cypress/files/11135290/dubuglog.log)
New update on this is now Test cases I can see running but I am not able to see report as html file as shown in screenshot I provided in description 

I updated following lib as -
        "cypress": "12.7.0",
        "@cypress/code-coverage": "^3.10.0",
        "@cypress/react": "7.0.3",
        "@cypress/webpack-dev-server": "3.3.0",
Also I followed things from these documents 
https://www.npmjs.com/package/@cypress/code-coverage 
https://www.npmjs.com/package/@cypress/webpack-dev-server - for next JS

Here is the cypress.config.js file
```
import { defineConfig } from 'cypress';

export default defineConfig({
    video: false,

    component: {
        devServer: {
            framework: 'next',
            bundler: 'webpack',
        },
        specPattern: 'components/**/*.spec.tsx',
        setupNodeEvents(on, config) {
            require('@cypress/code-coverage/task')(on, config);
            on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'));

            return config;
        },
    },
});
```

Here is the .babelrc file- 

```
{
    "presets": [
        "next/babel",
        ["@babel/preset-react", {"runtime": "automatic"}]
    ],
    "plugins": [
        //"transform-class-properties",
        "istanbul",
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }],
        ["@babel/plugin-proposal-private-methods", { "loose": true }],
    ]
}
```
here is .nycrc file -

```
{
    "cache": false,
    "check-coverage": true,
    "lines": 25,
    "statements": 25,
    "functions": 25,
    "branches": 25,
    "reporter": [
        "lcov",
        "text-summary",
        "text", 
        "json"
    ], 
    "report-dir": ".results",
    "temp-directory": ".results/.nyc_output",
    "require": [
        "ts-node/register"
      ],
    "excludeAfterRemap" : false,
    "watermarks": {
        "lines": [
            50,
            80
        ],
        "statements": [
            50,
            80
        ],
        "functions": [
            50,
            80
        ],
        "branches": [
            50,
            80
        ]
    }
}

```
Here is the file cypress/plugins/index.js -

```
const injectDevServer = require('@cypress/react/plugins/next');
import "@cypress/code-coverage/support"


module.exports = (on, config) => {
    require('@cypress/code-coverage/task')(on, config);
    on(
        'file:preprocessor',
        require('@cypress/code-coverage/use-browserify-istanbul')
      )
    if (config.testingType === 'component') {
        injectDevServer(on, config);
    }
    return config;
};

```

**Comment by mike-plummer** [comment] 2023-04-03 13:54
Just to make sure I understand @ShivaniNTT , you are now able to successfully run your component tests but are not seeing code coverage being collected? It's going to be very difficult to help you troubleshoot this without a reproduction case, but I can give you a few pointers:

1. It looks like you upgraded to a newer version of Cypress (yay!). Cypress v10 [dropped support for the "plugins" file](https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed), so your code there will need to be refactored into the new [`setupNodeEvents`](https://docs.cypress.io/guides/references/configuration#setupNodeEvents) API within your Cypress config file. I would recommend reviewing the [migration guides](https://docs.cypress.io/guides/references/migration-guide) to ensure all breaking changes for versions 10, 11, and 12 are addressed.
2. Your attached Debug Log shows you trying to launch Cypress into "e2e" testing mode, but you are using component testing. If using `cypress run` it is assumed you want to run e2e tests unless configured otherwise using a CLI flag: `cypress run --component`
3. It isn't clear what version of Next.js you're using, but by default newer versions use the [SWC compiler](https://nextjs.org/docs/advanced-features/compiler) rather than Babel for compiling Javascript. [Special plugins](https://www.npmjs.com/package/swc-plugin-coverage-instrument) are needed to hook Istanbul into SWC to collect coverage. You may have overridden this config to use babel in your project, but it's something to be aware of.
4. Note that component tests only execute *browser-side* Next.js code, so any server-side logic like `getServerSideProps`, API routes, etc will not be invoked in your tests and will thus not generate any coverage data. Those areas are better suited to e2e tests. There is a fairly comprehensive writeup around this and other unique issues with Next.js in [this blog post](https://www.cypress.io/blog/2023/02/16/component-testing-next-js-with-cypress/).

I have a [fully-working example](https://github.com/mike-plummer/nextjs-cypress-ct-example) of a Next.js application with e2e and component tests that all collect code coverage, you may find it to be a useful reference.

**Comment by mike-plummer** [comment] 2023-04-11 13:24
I will be closing this issue since there is no issue with Cypress and no further information has been provided. If you need further guidance on how to use Cypress I recommend referencing our [documentation](https://docs.cypress.io/) and utilizing our [Discord community](https://on.cypress.io/chat).

**Closed as not planned by mike-plummer** 2023-04-11 13:24 UTC
