### ISSUE TITLE
Test execution paused in chrome when it is not focused

### ISSUE THREAD

**Issue by koenvangeert** [cypress-io/cypress#28887] opened 2024-02-07 11:19 UTC
### Current behavior

When running cypress tests in Chrome, the test execution stops after chrome loses focus.

### Desired behavior

I would like to have the tests remain running while developing.
I believe this is intentionally done for: https://github.com/cypress-io/cypress/pull/28334

If we can't remove this, at least resume the tests after focusing the tab manually again, currently they stay paused.

### Test code to reproduce

How to reproduce.
- Run cypress tests in Chrome (watch mode)
- Switch to another program while the tests are still running

### Cypress Version

13.6.0

### Node version

v18.19.0

### Operating System

macOS 14.3

**Comment by jennifer-shehane** [comment] 2024-02-07 15:20
Duplicate of https://github.com/cypress-io/cypress/issues/28392 We have a fix we are working on that is explained [here](https://github.com/cypress-io/cypress/issues/28392#issuecomment-1924167195). You can downgrade below 13.6.0 to avoid the issue for now.

**Closed as not planned by jennifer-shehane** 2024-02-07 15:20 UTC
Labels: type: duplicate
