### ISSUE TITLE
"cy.type() failed because it targeted a disabled element" in shadow root

### ISSUE THREAD

**Issue by Chrisx0385** [cypress-io/cypress#21433] opened 2022-05-11 08:15 UTC
### Current behavior

Hi, 

I've already mentioned that in the closed Ticket #5830, but since the problem still exists in Version 9.6.1, at least when the elements are located in a shadow root, I opened this new ticket.

We're testing a form in a custom element. Now we moved the component into the shadow dom.
Since that, we are having the issue, that most of our tests fail with the message 
"cy.type() failed because it targeted a disabled element". 

We changed nothing beside that we detect the inputs in .shadow() of the custom element, like mentioned in the docs (https://docs.cypress.io/api/commands/shadow#Usage)

Before that, the tests were stable.

I was able to isolate the problem. It always occurs, when we use "type" and "clear" multiple times on the same element. 

### Desired behavior

Thee "type" and "clear" commands can be used in shadow root without any limitations on order or count.

### Test code to reproduce

I've created a minimal demo where the problem always occurs:

https://gitlab.com/cgz/cypress-type-bug-demo

### Cypress Version

9.6.1

### Other

I've created a workaround for the two commands. Unfortunately I wasn't able to just override the commands which seems to be another bug: https://github.com/cypress-io/cypress/issues/3838#issuecomment-527434058

But with writing two custom commands I could get our tests back working. 
You can find it in a separate branch in the demo project: https://gitlab.com/cgz/cypress-type-bug-demo/-/blob/workaround-commands/cypress/cypress/support/commands.js

They just click in the body before using the original "type" or "clear" command for elements which are located in the shadow root.

**Comment by BlueWinds** [comment] 2022-05-12 20:47
Thank you for the report, and the very clear repro! It fails as you describe on Electron and Chromium (with a different error earlier in the test on Firefox). It's not entirely clear to me what's going on here, but definitely looks like a Cypress bug - I'm sending it over to the e2e team and hopefully someone can do a more careful investigation.

**Comment by tronicboy1** [comment] 2022-07-20 08:56
I also am observing the same bug. 

I am using `LitElement` where my \<input> and \<select> elements are being rendered into the shadow DOM.

The error occurs sporadically with both `.type` and `.select`.

I am using the `{ force: true }` option as a work around however would prefer to not have to.

I wish I could do more to help!

**Comment by pedro00dk** [comment] 2023-02-20 23:18
Hello,
I'm also experiencing this issue.

**Comment by pedro00dk** [comment] 2023-02-21 01:03
Hello,
I'm also experiencing this same issue.
Initially, I thought it was caused by a web-components-based UI library my company uses because I had some other problems with it, so I started debugging the issue before checking for cypress issues.

I don't know if this issue is being tackled already, and I'm very new to cypress, I'm just sharing my findings here in case they are helpful.

First, I was able to reduce the test case a bit more:

index.html
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <div id="root"></div>
        <textarea></textarea> <!--  << does not change anything, just for comparing with now shadow element -->
        <script>
            const shadow = document.querySelector('#root').attachShadow({ mode: 'open' })
            shadow.append(document.createElement('input'))
        </script>
    </body>
</html>
```

cypress.config.js
```javascript
const { defineConfig } = require('cypress')

module.exports = defineConfig({
    includeShadowDom: true,
    e2e: {},
})
```

spec.cy.js
```javascript
describe('template spec', () => {
    beforeEach(() => cy.visit('index.html'))

    it('passes', () => {
        // a single `type` command works fine
        cy.get('input').type('hello')
    })

    it('fails', () => {
        // more than one `type` command fails
        cy.get('input').type('hello')
        cy.get('input').clear()
    })

    it('fails', () => {
        // an odd number of `click`/`focus` commands before a `type` command fails
        cy.get('input').click().type('hello')

        // same result
        // cy.get('input').focus().type('hello')
        // cy.get('input').click().click().click().type('hello')
        // cy.get('input').focus().focus().focus().type('hello')
    })

    it('passes', () => {
        // however, an even number of `click`/`focus` commands before a `type` command passes
        cy.get('input').click().click().type('hello')

        // same result
        // cy.get('input').focus().focus().type('hello')
        // cy.get('input').click().focus().type('hello')
    })

    it('passes', () => {
        // based on previous tests, the first `type` works fine (even (0) clicks before), but it also has a click-like effect
        // hence, following `type` commands will work with an extra `click` command.
        cy.get('input').type('hello')
        cy.get('input').click().type(' world')
        cy.get('input').click().type('!')
    })

    it('focus/blur toggle weird', () => {
        /*
         * I started debugging cypress_runner.js code and found out what was causing the `type` command to fail.
         *
         * The function `getActiveElByDocument` at https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/elements/complexElements.ts#L222
         * returns the `activeElement` of the input's shadow root.
         *
         * And the `type` command requires `activeElement` to be defined at https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/type.ts#L545
         * (I think it probably checks that because of the internal `click` command just before it).
         *
         * The test below triggers `click`s multiple times and prints for the same prop as the `getActiveElByDocument` function returns.
         * Every command to `click` on the input toggles the `activeElement` property, between `null` and the input itself.
         */
        const logActives =
            message =>
            ([el]) =>
                console.log(message, {
                    doc: document,
                    root: el.getRootNode(),
                    docActive: document.activeElement,
                    rootActive: el.getRootNode().activeElement,
                })

        cy.get('input')
            .then(logActives('input before all')) // prints { ..., rootActive: null }
            .click()
            .then(logActives('input after click 1')) // prints { ..., rootActive: input }
            .click()
            .then(logActives('input after click 2')) // prints { ..., rootActive: null }
            .click()
            .then(logActives('input after click 3')) // prints { ..., rootActive: input }
            .click()
            .then(logActives('input after click 4')) // prints { ..., rootActive: null }

        /**
         * The behavior with an element outside the shadow root is different.
         * The `activeElement` prop is not set to null when multiple click commands are issued.
         *
         * (I tested with input as well, textarea is just to simplify the demo)
         */
        cy.get('textarea')
            .then(logActives('textarea before all')) // prints { ..., rootActive: body }
            .click()
            .then(logActives('textarea after click 1')) // prints { ..., rootActive: textarea }
            .click()
            .then(logActives('textarea after click 2')) // prints { ..., rootActive: textarea }
            .click()
            .then(logActives('textarea after click 3')) // prints { ..., rootActive: textarea }
            .click()
            .then(logActives('textarea after click 4')) // prints { ..., rootActive: textarea }
    })
})
```
Test repository: https://github.com/pedro00dk/cypress-shadow-root-type-demo

**Comment by knoefel** [comment] 2023-03-03 12:02
@BlueWinds Are there any plans, when this is going to be resolved? 

Unfortunately it's blocking some important tests in our project right now. Thanks in advance for your feedback!

**Comment by pedro00dk** [comment] 2023-03-03 13:01
Hey @knoefel, I'm currently using this workaround, it might help you.
```typescript
Cypress.Commands.overwrite('type', ((
    originalFn: any,
    element: JQuery<HTMLElement>,
    ...args: Parameters<typeof cy.type>
) => {
    // TODO: { force: true } required because https://github.com/cypress-io/cypress/issues/21433
    const [text, options] = args
    const force = element?.[0].getRootNode() instanceof ShadowRoot || options?.force
    return originalFn(element, text, { ...options, force })
}) as unknown as Cypress.CommandFnWithOriginalFn<'type'>)

```

**Comment by knoefel** [comment] 2023-03-03 17:26
@pedro00dk Thanks a lot for sharing! Unfortunately it still fails sometimes.

**Comment by tibioneh** [comment] 2023-03-16 11:32
We need a fix for this soon, please and thank you.

**Comment by yktoo** [comment] 2023-05-22 08:58
Yes we're impacted by this one, too.

**Comment by pistolpete101** [comment] 2023-06-09 15:35
HI, this too is causing some pain for us. And is affecting our project also.
When will this be fixed?

**Comment by chris-gotenna** [comment] 2023-06-13 14:24
Same. I am having these failures in CI.

**Comment by pistolpete101** [comment] 2023-06-13 14:26
Seems the issue has been sorted, for me at leats in v12.14.0. Might want to update and see if it sorts the out the issue your side.

**Comment by pedro00dk** [comment] 2023-06-13 19:17
The issue seems to be fixed for me as well.

**Comment by jennifer-shehane** [comment] 2024-03-13 15:36
Closing as resolved. If you have an issue similar to this, please open a new issue with a full description and reproducible example.

**Closed by jennifer-shehane** 2024-03-13 15:36 UTC
Labels: type: bug, E2E
