### ISSUE TITLE
open-ct complains about missing browser but open works fine

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress#15808] opened 2021-04-06 08:53 UTC
### Current behavior

`npx cypress open` works just fine but `npx cypress open-ct` crashes with:

```
(node:33115) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
Error: Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- chromium
- firefox
- electron
    at get (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at ~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
 {
  isCypressErr: true,
  type: 'BROWSER_NOT_FOUND_BY_NAME',
  details: undefined
}
Error: Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- chromium
- firefox
- electron
    at get (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at ~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (~/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
```

### Versions

- Cypress 7.0.0
- Fedora GNU/Linux

**Comment by lmiller1990** [comment] 2021-04-06 14:27
Hey, thanks for the quick bug report (~12 hours after launch).

When you do `npx cypress open` and launch to the electron app, is chrome available as one of the browsers from the dropdown where you choose your browser? It looks like your system has:

- chromium
- firefox
- electron

[We default to chrome](https://github.com/cypress-io/cypress/blob/df8cb0345f7b09f393b442ac9b9cbc549eee0f23/packages/server/lib/modes/interactive-ct.js#L6). We should definitely add some intelligent logic to fallback to the next *available* browser, eg chrome -> chromium -> electron -> firefox or something to that tune.

A work around would be to pass `--browser=chromium` to launch the new component testing runner. You could also try electron, which feels great (dedicated window) but there is a bug (in electron, from what I can tell, not in the runner) where the DOM in the devtools is not updated and gets stale, so I'd recommend chromium until we figure out why electron's devtools do that.

**Comment by DamienCassou** [comment] 2021-04-06 14:38
@bahmutov: you added the "experiment: component testing" label even though I had to remove the `experimentalComponentTesting` property from my configuration to make it work. Who is right? :smile:

**Comment by lmiller1990** [comment] 2021-04-06 14:44
Label is now fixed 👍 

A different error? Don't hesitate if you think it's on our end, the Component Testing runner, while no longer experimental, is still pretty new and might have some bugs. It's working fine for me with Chrome, Electron and FF. I did not try chromium but I will give this a try later today and see if I can reproduce the problem.

Let me know if you have any progress with you debugging.

**Comment by DamienCassou** [comment] 2021-04-06 15:04
@lmiller1990 I reported the error separately: https://github.com/cypress-io/cypress/issues/15813

**Comment by lmiller1990** [comment] 2021-04-07 01:47
Cool, #15837 should fix this.

**Comment by DamienCassou** [comment] 2021-04-07 06:42
Thank you @lmiller1990.

**Comment by lmiller1990** [comment] 2021-04-07 13:50
It will be released 2 weeks (next release).

For now please just pass the browser you'd like to use. Thanks for the all the detailed bug reports :100:

**Closed** 2021-04-08 02:04 UTC
Labels: component testing, stage: work in progress

**Comment by jennifer-shehane** [comment] 2021-04-28 13:15
This was released.

This comment thread has been locked. If you are still experiencing this issue after upgrading, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
