### ISSUE TITLE
Waiting for two identical requests in run mode makes cypress freeze

### ISSUE THREAD

**Issue by Kremliovskyi** [cypress-io/cypress#22450] opened 2022-06-22 13:38 UTC
### Current behavior

I have two identical requests issued by an app that I intercept like 
`cy.intercept('GET', '**/user/documents/offering/**').as('getOfferingDocuments')`
Whenever I wait for them like this 
```
      cy.wait(['@getOfferingDocuments', '@getOfferingDocuments']).should('have.length', 2)
        .then((interceptions) => {
          expect(interceptions[0].response.statusCode, 'first request status').eq(200)
          expect(interceptions[1].response.statusCode, 'second request status').eq(200)
        })
```
or even like this
```
      cy.wait(['@getOfferingDocuments', '@getOfferingDocuments'])
      cy.get('@getOfferingDocuments.all').should('have.length', 2)
        .then((interceptions) => {
          expect(interceptions[0].response.statusCode, 'first request status').eq(200)
          expect(interceptions[1].response.statusCode, 'second request status').eq(200)
        })
```

Whenever I run test in cypress open mode the test passes, but in cypress run mode test just freezes indefinetely with no errors in terminal.

### Desired behavior

Same code should be working in run mode as it does in the open mode

### Test code to reproduce

```
     cy.intercept('GET', '**/user/documents/offering/**').as('getOfferingDocuments')

     cy.visit(someUrl)

      cy.wait(['@getOfferingDocuments', '@getOfferingDocuments']).should('have.length', 2)
        .then((interceptions) => {
          expect(interceptions[0].response.statusCode, 'first request status').eq(200)
          expect(interceptions[1].response.statusCode, 'second request status').eq(200)
        })
```

### Cypress Version

10.2.0

**Comment by lmiller1990** [comment] 2022-06-29 06:15
Hi! I was unable to reproduce. You could try running `yarn DEBUG=cypress:* yarn cypress run`. This will print a huge amount of logs in your terminal, which you can paste here to help with debugging.

Here's my code.

## command:

`yarn cypress:run --e2e --spec cypress/e2e/blah.cy.ts`.

I started my server with `python3 -m http.server 9999`.

## cypress/e2e/blah.ts

```ts
// blah.cy.ts
it('', () => {
  const url = 'https://jsonplaceholder.typicode.com/todos/1'
  cy.intercept('GET', url).as('todos')
  cy.visit('http://localhost:9999')
  cy.wait(['@todos', '@todos']).should('have.length', 2)
    .then((interceptions) => {
      expect(interceptions?.[0]?.response?.statusCode, 'first request status').eq(200)
      expect(interceptions?.[1]?.response?.statusCode, 'second request status').eq(200)
    })
})
```

## index.html

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

  <script>
    const url = 'https://jsonplaceholder.typicode.com/todos/1'

    fetch(url)
      .then(response => response.json())
      .then(json => console.log(json))

    fetch(url)
      .then(response => response.json())
      .then(json => console.log(json))

  </script>
</body>

</html>
```

Does anything look different to what you are doing?

I am on 10.3.0 using Ubuntu 22.

**Comment by Kremliovskyi** [comment] 2022-06-29 09:41
@lmiller1990 I am using windows and we do not use yarn. Your command does not work for windows. 
![image](https://user-images.githubusercontent.com/12884831/176405483-2653d23b-bb59-4fa9-8418-8fc2fd672c20.png)
 Could you please give me the same command for windows ?

**Comment by Kremliovskyi** [comment] 2022-06-29 12:55
@lmiller1990 for some reason with debug variable cypress does not freezes. Here you may find the log
[cypress.log](https://github.com/cypress-io/cypress/files/9010659/cypress.log)

**Comment by Kremliovskyi** [comment] 2022-06-29 16:12
@lmiller1990 Unfortunately yes, when I removed DEBUG it still freezes

**Comment by lmiller1990** [comment] 2022-06-30 00:30
I wonder if there's a race condition and `DEBUG` + all the console.logs slows things down enough to avoid it...

1. what OS?
2. can you reproduce this in Cypress 9? Let's see if we can isolate the problem - is it a regression, or a long standing bug

I cannot reproduce this, and the fact adding `DEBUG` (which just does console.log under the hood) fixes it is very weird. How are you making the requests? Can you share a minimal repository I can actually pull down and clone?

**Comment by Kremliovskyi** [comment] 2022-07-08 08:11
In gitlab ci its image: cypress/included:10.3.0
Locally windows 10
I will setup cypress 9 , recheck and tell the result.

**Comment by lmiller1990** [comment] 2022-07-11 03:12
Oh, you reproduced in docker on CI? Can you make the repo open and share it here (ideally with the Dockerfile). This is the reproduction I'm looking for!

**Comment by Kremliovskyi** [comment] 2022-07-18 09:38
@lmiller1990 @astone123 I can not share repo as it is closed sourse. I am able to reproduce it with cypress 9 and cypress 10 everywhere.
Here are the logs with debug mode when the issue reproduces for both cypress 9 and 10
[cypress-9.txt](https://github.com/cypress-io/cypress/files/9130921/cypress-9.txt)
[cypress-10.txt](https://github.com/cypress-io/cypress/files/9130922/cypress-10.txt)

**Comment by Kremliovskyi** [comment] 2022-07-18 09:45
The tables in the end of the logs are just printed non stop

**Comment by marktnoonan** [comment] 2022-07-22 22:04
Hi @Kremliovskyi these logs show the happy situation where the freeze doesn't happen is that right?

I know you can't share the code but would you be able to try the example code @lmiller1990 [provided here](https://github.com/cypress-io/cypress/issues/22450#issuecomment-1169576124) and verify if that causes the same problem. This might help isolate the problem.

**Comment by Kremliovskyi** [comment] 2022-07-25 06:57
@marktnoonan I said the logs show the situation when cypress test execution freezes, in the end of the log you will find tables printed non stop, I just terminated execution because it never ends printing them and test never finishes in this case

**Comment by marktnoonan** [comment] 2022-07-25 16:29
Thanks @Kremliovskyi, will look at the logs more closely now. I must have misunderstood:

> with debug variable cypress does not freeze

When was this the case?

**Comment by Kremliovskyi** [comment] 2022-07-25 16:35
@marktnoonan If open fresh terminal it is not reproduced, when I try executing run command each subsequent time it reproduces. I do not know how it works in CI though and have absolutely no idea how even this might be happening locally but I recreated it several times.

**Comment by Kremliovskyi** [comment] 2022-07-25 16:39
I initially thought it was because of debug but it is not, it just reproduces or not depending on terminal, fresh start or not. In windows I use git bash for the sake of this debug part.

**Comment by mike-plummer** [comment] 2022-08-17 16:44
@Kremliovskyi I also am not able to reproduce an issue with the pattern you described in the issue (Lachlan's example code above being a simple way to check). Based on your more recent comments it appears that your issue only manifests when running your test suite multiple times within the same terminal session, is that correct? Also, when you say the tests hang "indefinitely" it appears (from your attached log) that they are timing out after a several tens of seconds (this is probably much longer than you would expect those calls to complete within) which tells me the assertions may be properly waiting and just not seeing the expected calls within their default timeouts (each [`cy.wait`](https://docs.cypress.io/api/commands/wait#Timeouts) will delay up to 5 seconds to see an outgoing request begin, and 30 seconds for a response to come back). Is there a way to validate within your application logic that the expected XHR requests are firing each time?

At this point my best guess is that there is state being maintained to control when/how those requests are made, and it is being done in a way that leaks between test runs. Is it possible there are environment variables, filesystem-based storage, or other stateful caching/updating being done that would prevent the expected calls from firing? We do attempt to start each test from a clean slate, but there are lots of ways that state can be managed outside the standard cleanup we do.

Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-24 18:12
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-24 18:12 UTC
Labels: stage: awaiting response, Needs Reproduction

**Comment by Jorrex** [comment] 2023-04-04 11:15
Just to post my findings - we experienced something similar with our regression. Can confirm that the issue was within our own web app by using a 'caching mechanism' which prevented multiple API calls within a timeframe. Cypress was expecting requests and ended up freezing in some runs. The fix (or workaround) here was to use some waits to allow our app to pass the timeframe and resend the request.

Can't provide a reproducible example since our code is in a private repo and can't compress this into something that I can share.
