### ISSUE TITLE
Cypress not accepting 'text/html; charset=utf-8'

### ISSUE THREAD

**Issue by codinghorizon** [cypress-io/cypress#9054] opened 2020-10-30 21:59 UTC
I know Cypress is usually working with text/html. We're about to write Cypress tests for [OTRS][1]. I have written some example tests yet for public websites, everything worked well.  
Now I have the problem that OTRS (several dev- and test-systems) seems to return content-type as 'text/html; charset=utf-8' instead of expected 'text/html' when I use cy.visit() - tested in Firefox, Chrome and Electron:  

        cy.visit() failed trying to load:
    
    http://xx.xx.xx.xx/otrs/index.pl
    
    The content-type of the response we received from your web server was:
    
      > text/html; charset=utf-8;
    
    This was considered a failure because responses must have content-type: 'text/html'
    
    However, you can likely use cy.request() instead of cy.visit().
    
    cy.request() will automatically get and set cookies and enable you to parse responses.

Since this content-type is defined in so many parts of OTRS, it is not possible for us to change it - especially because this product is not developed by us, but imho the content-type 'text/html; charset=utf-8' should also be accepted from Cypress since it actually is text/html.

Any feedback on this is very much appreciated!

### Versions
Cypress 5.5.0 (via npm install cypress)
Running on MacOS 10.15.7 (first tests) and later inside docker image cypress/included:5.5.0
Chrome 86/Firefox81/Electron85

  [1]: https://github.com/OTRS/otrs

**Comment by jennifer-shehane** [comment] 2020-11-02 08:42
Duplicate of https://github.com/cypress-io/cypress/issues/8506, we should handle any content-type containing `text/html` - that was the conclusion on the other issue.

**Closed by jennifer-shehane** 2020-11-02 08:42 UTC

**Comment by codinghorizon** [comment] 2020-11-02 08:48
> Duplicate of #8506, we should handle any content-type containing `text/html` - that was the conclusion on the other issue.

Sorry, didn't find that one, even though I was searching a lot for "charset=utf-8". That mentioned issue should fix my problem aswell, thank you!
