### ISSUE TITLE
Cannot type() into input field with invalid type

### ISSUE THREAD

**Issue by maticko** [cypress-io/cypress#1061] opened 2017-12-13 03:54 UTC
- Operating System: any
- Cypress Version: 1.1.4
- Browser Version: Chrome

### Is this a Feature or Bug?
Bug

### Current behavior:
Won't type into input filed with invalid type (like type="invalid"), throws an error.

### Desired behavior:
Cypress should type to input field anyway. Cypress shouldn't be so strict regarding the input field type. It should handle types that it cannot recognise (as default text).

### How to reproduce:

Create HTML input element with an invalid type.
```html
<input type="invalid" />
```
Then use cypress to type into that input field.

#### Test code:

```js
cy.get('input').type('banana')

```

### Additional Info (images, stack traces, etc)
![image](https://user-images.githubusercontent.com/1460731/33920422-bf370130-e022-11e7-85a5-f0ab78febe05.png)

**Comment by jennifer-shehane** [comment] 2017-12-13 15:21
We have chosen to be strict about only allowing [valid input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) to be typed into. We feel that this helps ensure that your application's HTML is valid and is another layer of testing that is more helpful than harmful. If your application uses invalid HTML, there is no assurance that browsers will respect the behavior you expect.

That being said, I'd like to hear the use case for *why* you feel using an invalid input type is necessary for your application - we are always open to hear situations we have not considered.

**Comment by brian-mann** [comment] 2017-12-13 16:54
This is actually a duplicate of https://github.com/cypress-io/cypress/issues/586

We decided to accept a new option to turn off validation. Just needs a PR to get merged in.

**Closed by brian-mann** 2017-12-13 16:54 UTC
Labels: stage: needs information, type: duplicate
