### ISSUE TITLE
--spec argument can only find files in cypress/e2e folder

### ISSUE THREAD

**Issue by aommm** [cypress-io/cypress#22192] opened 2022-06-08 14:58 UTC
### Current behavior

Hi! Thx for providing Cypress, I'm a big fan of your product :)

I'm having trouble moving to Cypress 10.
The `--spec` argument doesn't seem to work properly if I don't keep my tests in the `cypress/e2e` folder.

In my [repro repo](https://github.com/aommm/cypress-spec-bug), these work:
```
> cd cypress-spec-bug
> npx cypress run --spec cypress/e2e/spec.cy.js
> npx cypress run --spec /Users/aom/cypress-spec-bug/cypress/e2e/spec.cy.js
```
These **don't** work, but I expect them to:
```
> cd cypress-spec-bug

> npx cypress run --spec cypress/e2e-fail/spec.cy.js
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
/Users/aom/cypress-spec-bug/cypress/e2e-fail/spec.cy.js

> npx cypress run --spec /Users/aom/cypress-spec-bug/cypress/e2e-fail/spec.cy.js
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
/Users/aom/cypress-spec-bug/cypress/e2e-fail/spec.cy.js
```

### Test code to reproduce

https://github.com/aommm/cypress-spec-bug

### Cypress Version

10.0.3

### Other

[The documentation for --spec](https://docs.cypress.io/guides/guides/command-line#cypress-run-spec-lt-spec-gt) states:
> The spec path should be an absolute path or can relative to the current working directory.

It doesn't seem to work with either relative or absolute path in my case 🤔 

Final note:
This weirdness used to happen for me also on Cypress 9.
Then I fixed it by setting `integrationFolder=cypress/e2e-fail`, but that config option has been removed.

**Comment by JeroenVdb** [comment] 2022-06-09 14:45
I maybe have a related problem.

Some data:
- Cypress version 10.0.3
- I have the problem in my Docker only, base image: node:16.15.1-alpine3.16
- I don't have the problem when I run it on my Macbook

```

> temptation-module@1.8.7 test:e2e:ci
> ls -lsa "./cypress/e2e" && npx cypress run --spec "./cypress/e2e/formulas.cy.ts"

total 28
4 drwxrwxrwx 3 root root 4096 Jun  9 14:40 .
4 drwxrwxrwx 7 root root 4096 Jun  9 14:40 ..
4 drwxrwxrwx 2 root root 4096 Jun  9 14:40 components
4 -rw-rw-rw- 1 root root 1536 Jun  9 14:40 formulas.cy.ts
8 -rw-rw-rw- 1 root root 4786 Jun  9 14:40 purchase.cy.ts
4 -rw-rw-rw- 1 root root  716 Jun  9 14:40 visual-regression.cy.ts

Can't run because no spec files were found.
We searched for specs matching this glob pattern:
  > /opt/atlassian/pipelines/agent/build/cypress/e2e/formulas.cy.ts
```

**Comment by marktnoonan** [comment] 2022-06-09 16:22
@aommm It looks like you are running into an issue with running a spec that is not found with the default `specPattern` ([docs here](https://docs.cypress.io/guides/references/configuration#e2e)). This can be set for `e2e` in `cypress.config.js` and the default value is `cypress/e2e/**/*.cy.{js,jsx,ts,tsx}`.

Thanks for providing the reproduction! The following config is an example of how make the `specPattern` more inclusive, which allows the example to run:

```
module.exports = {
  e2e: {
    specPattern: '**/*.cy.js',
    setupNodeEvents(on, config) {},
  },
}
```

I think our error message could be more informative on in this situation to guide you to the solution, I will follow up on this.

**Comment by aommm** [comment] 2022-06-10 09:16
Thanks a lot for the prompt reply! It works for me now.

### Some random thoughts:

After reading between the lines in your documentation, it seems like two things are happening when users specify `--spec`:
1. Cypress loads specs based on `specPattern`
2. Cypress searches loaded specs based on `--spec`

It does not feel very relevant to have this two-step process when I've already told Cypress which specs to execute with `--spec`. It feels like an implementation detail that doesn't need to be exposed to the user.

But on the other hand I can see that `specPattern` is relevant when `--spec` is not specified, as a sort of default value.

I'm curious if both `specPattern` and `--spec` are needed, or if they could be consolidated to the same option in some future version.

^ Just some random thoughts from someone uninitiated, take it with a grain of salt 🙂 Great that you're updating the documentation as a next step!

**Comment by marktnoonan** [comment] 2022-06-10 11:30
Thanks for the comments! Closing this one now. I noticed your comment @JeroenVdb, please open a new issue if there is still a problem related to this for you with Docker.

**Closed by marktnoonan** 2022-06-10 11:30 UTC
Labels: stage: awaiting response
