### ISSUE TITLE
Random failures over Regexp: Invalid regular expression

### ISSUE THREAD

**Issue by houshuang** [cypress-io/cypress#1746] opened 2018-05-20 12:28 UTC
I get very strange non-deterministic errors when opening my website in Cypress. It complains about a failing Regexp, but the weird thing is that this never causes a problem in a normal browser, and in fact, even within the Cypress browser, if I open a new tab and reload the code, it works perfectly. And I also added on Cypress.on('uncaught.exception') to my code, which does not seem to help.

Here's my test script:
```js
const uuid = require('cuid');
Cypress.on('uncaught:exception', (err, runnable) => {
  return false;
});

describe('My First Test', function() {
  it('finds the content "type"', function() {
    const id = uuid();
    // cy.wait(30000 * Math.random());
    cy.visit(`https://icchilisrv3.epfl.ch:7000/w948?login=${id}`);

    cy.get('video', { timeout: 90000 });
    cy
      // .wait(10000)
      .then(() => cy.wrap(Cypress.$('video')[0].networkState).should('eq', 2));
    cy.wait(180000);
  });
});
```

Here you see two tabs of the same browser, consistently showing completely different behaviour (even when reloading etc). What's very strange is that when I deploy this in 30 different browsers using Kubernetes, I get half of them failing with this error, and the other half working normally! Perhaps this is a timing issue (the reason for the non-determinism) with some interaction between my code and Cypress test code?

<img width="1390" alt="screen shot 2018-05-20 at 14 21 31" src="https://user-images.githubusercontent.com/61575/40278898-b93edd1e-5c39-11e8-880d-f64c55436ed2.png">
<img width="1394" alt="screen shot 2018-05-20 at 14 21 00" src="https://user-images.githubusercontent.com/61575/40278900-b957a394-5c39-11e8-8c97-1aee8ae4f936.png">

Here you see examples of failing and successful Cypress runs - these are exactly the same code in different Kubernetes containers: 

![screen shot 2018-05-20 at 14 27 06](https://user-images.githubusercontent.com/61575/40278907-f4976dfe-5c39-11e8-8ccd-39935a09d163.png)

(in this case, I don't get the error exceptions, because of the uncaught.exception setting, but the behaviour is exactly the same as in interactive mode, making me believe that the problem is identical). 

Reference to [Cypress dashboard run](https://dashboard.cypress.io/#/projects/32bbwc/runs/ba1f5eeb-9b17-4088-a8e7-d6c0c18fd44a/output)

**Comment by jennifer-shehane** [comment] 2018-05-21 14:21
We've seen this `Invalid regular expression` before, so I suspect it is some situation on our part. It needs investigating.

**Comment by rufushonour** [comment] 2018-06-15 09:08
@houshuang Not sure if you fixed this issue or not but I've managed to get around it by adding `"modifyObstructiveCode": false` to my cypress.json

I think this might be related to #1396 ?

**Comment by frazboyz** [comment] 2018-08-29 11:52
I can confirm, adding `"modifyObstructiveCode": false` to your config fixes the issue.

**Comment by arasabbasi** [comment] 2019-06-21 16:50
FakeNews... still getting garbage regex error

**Comment by flotwig** [comment] 2019-07-12 15:29
I believe that #4698 might fix this issue - browsers infer the character encoding of subresources (partially) based on the character encoding of the consuming HTML document, so fixing the character encoding of HTML in Cypress should cascade to this.

I tried using the example in the OP, but that website is not available. If anyone has a reproducible example of this happening, I'll test it against #4698 to see if this fixes the problem.

**Comment by SeanBE** [comment] 2019-07-12 15:57
Ran this example https://github.com/cypress-io/cypress/issues/2112#issuecomment-510899430 with the #4698 build and I still get  invalid regular expression.

**Comment by flotwig** [comment] 2019-07-12 17:47
@SeanBE This doesn't seem like an encoding issue, rather, a browser compatibility error. When I add that RegEx, the app no longer works in Firefox:

![image](https://user-images.githubusercontent.com/1151760/61147616-c0f22100-a4aa-11e9-9d90-33e54599cdf6.png)

It's because you're using negative lookbehind in the RegEx:

* Firefox doesn't support negative lookbehind
* Chrome >=62 does, which is why it works when you use `cypress open` with Chrome 75
* The version of Chrome bundled with Cypress (61) does not support negative lookbehind, which is why it fails in `cypress run`.

[Read more about the development of this feature.](https://stackoverflow.com/q/641407/3474615)

Try using `cypress run` with `--browser=chrome`, you'll find that it does work now because you're using the Chrome bundled with your system.

---

We're working on upgrading the Chrome/Electron version bundled with Cypress: #3568 For now, you'll need to run tests in Chrome to support negative lookbehind, or use some other method of pattern-matching to support your needs.

**Comment by Halt001** [comment] 2019-08-11 09:53
I have a similar issue where unicode characters in vendor.js are not properly encoded. Problem with creating a repo to reproduce this is that even renaming the project path is enough to get it to behave properly.

So I have a repo which can reproduce the problem but only on my machine and only on the exact same path. Creating a new test project on that exact same path also produces the error so it must be caused by something outside the project directory.

Installing a previous version of Cypress (3.2.0) fixes the problem.
Setting "modifyObstructiveCode": false also fixes the problem.

Is it possible that there is something cached somewhere that uses the project path as key?

**Comment by flotwig** [comment] 2019-08-12 13:38
@Halt001 Are you using 3.4.1? That release contained some fixes for character encoding.

Is your Javascript UTF-8-encoded? What headers is it being sent with from your web server?

**Comment by Uzlopak** [comment] 2019-08-12 15:28
I have to correct myself. It did fix our issue. 

Best Regards

**Comment by Halt001** [comment] 2019-08-12 17:04
Yes, I'm using 3.4.1

The Javascript file I'm talking about is the vendor.js file created by Angular, and it contains UTF8 characters.

**Request headers as seen in the Chrome instance started by Cypress:**

```
GET http://localhost:4200/vendor.js HTTP/1.1
Host: localhost:4200
Proxy-Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Sec-Fetch-Mode: no-cors
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Accept: */*
Sec-Fetch-Site: same-origin
Referer: http://localhost:4200/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
```


**Response headers as seen in the Chrome instance started by Cypress:**

```
HTTP/1.1 200 OK
x-powered-by: Express
access-control-allow-origin: *
accept-ranges: bytes
content-type: application/javascript; charset=UTF-8
etag: W/"3d0d98-V90I6hrR5NqasgimxMHD6dWanEk"
date: Mon, 12 Aug 2019 16:44:56 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked
```

After renaming my project directory the problem goes away. For completeness I'll copy the headers below for this working situation.

**Request headers as seen in the Chrome instance started by Cypress when it all works:**
```
GET http://localhost:4200/vendor.js HTTP/1.1
Host: localhost:4200
Proxy-Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Sec-Fetch-Mode: no-cors
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Accept: */*
Sec-Fetch-Site: same-origin
Referer: http://localhost:4200/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
```



**Response headers as seen in the Chrome instance started by Cypress when it all works:**

```
HTTP/1.1 200 OK
x-powered-by: Express
access-control-allow-origin: *
accept-ranges: bytes
content-type: application/javascript; charset=UTF-8
etag: W/"3d12ae-UQQQNJC5AvB8VbY23IHRMFJdox8"
date: Mon, 12 Aug 2019 17:00:07 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked
```

**Comment by flotwig** [comment] 2019-08-12 18:43
What is the name of your project folder when it works, and when it is broken?

**Comment by Halt001** [comment] 2019-08-12 19:06
`/Users/Tim/Dev/bagger/Nx/myorg` is the path where it doesn't work.

Rename any part of the path, (not necessarily the `myorg` part) and everything works fine.

As there is nothing special about this path and throwing the project away and recreating it from scratch in the exact same location causes the same problem again I suspect that Cypress uses something  that is cached beyond the life of the project and also outside the project folder.

The project is the Nx dev tutorial until step 2: [Tutorial](https://nx.dev/angular/tutorial/01-create-application).

This is the repo that contains the tutorial on my machine in the state that it fails. But I'm pretty certain it won't fail anywhere else because as I said, the problem seems to be bound to a specific path. [Repo](https://github.com/morepublic/nx-tutorial) (Run e2e with: `ng e2e todos-e2e --watch` or` npm run e2e -- --watch`)

Also note that when the server is running and Cypress is failing, opening another Chrome browser manually and opening the same url shows that vendor.js is then correctly served without the utf8 problem.

**Comment by Halt001** [comment] 2019-08-13 04:50
**Interesting observation:** It is not the value of the project path that makes the difference but the length. I can rename al I want but as long as it stays the same length it will fail, adding or removing characters in the path will make it work.

So this rules out my theory of the path being some kind of key in a cache but it may be possible to reproduce on other machines.

**Comment by jpike88** [comment] 2019-08-27 05:31
Just ran into this issue. 

```"modifyObstructiveCode": false"``` fixes the issue. I encourage the cypress team to treat this issue as more of a priority, as it appears to be breaking core Angular code.

**Comment by Halt001** [comment] 2019-09-14 06:54
Everything that causes changes to the files being served can appear to solve this issue as it causes the Unicode characters not to be at a chunk boundary. So none of these solutions really solve anything except for a setting that causes the offending code to be skipped (which `"modifyObstructiveCode": false"` may do.

**Comment by CSchulz** [comment] 2019-09-26 12:16
We encountered the same issue on nearly all developer machines.

Generated javascript assets of Angular gets encoding issues with UTF-8 signs like ɵ sometimes.
https://puu.sh/DOFhM/1dd12f8b4a.png
(credits for the screenshot to @alfaproject)

Any ETA when #4984 will be merged?

**Closed** 2019-09-29 02:26 UTC
Labels: stage: needs review, type: bug
