### ISSUE TITLE
Auto-Scrolling goes disabled automatically when the execution is in-progress

### ISSUE THREAD

**Issue by vasanthiraman** [cypress-io/cypress#24015] opened 2022-09-28 10:56 UTC
### Current behavior

Auto-Scrolling goes disabled automatically when the execution is in-progress

### Desired behavior

Auto Scrolling should remain enabled once it is on in cinfiguration. It should not go disabled automatically until the user manually disable it.

### Test code to reproduce

N/A

### Cypress Version

10.6.0

### Node version

v14.16.0

### Operating System

Windows 10

**Comment by lucasdonato** [comment] 2022-09-28 12:09
I'm sad about this error too

**Comment by astone123** [comment] 2022-09-28 13:27
@vasanthiraman @lucasdonato This sounds like a similar issue to https://github.com/cypress-io/cypress/issues/16098. We released a fix for this in version 10.8.0. Could you try upgrading Cypress to 10.8.0 and see if the issue persists? Thanks

**Comment by lucasdonato** [comment] 2022-09-28 13:38
I'm on version 10.9 and I have the same problem

**Comment by astone123** [comment] 2022-09-28 15:24
@lucasdonato can you make it happen reliably, or does it only happen intermittently?

**Comment by lucasdonato** [comment] 2022-09-28 16:26
intermittently :(

**Comment by lucasdonato** [comment] 2022-09-29 11:46
it happen reliably :(

**Comment by astone123** [comment] 2022-09-29 14:57
@lucasdonato can you share more information? This bug has been difficult for us to pin down because we haven't been able to trigger it on demand. If you could share a project that reliably reproduces the issue, that would be extremely helpful. Thanks

**Comment by romankhomitskyi** [comment] 2022-09-29 19:16
This happens in open mode
Every time I rerurn my spec  Auto scrolling  is turned off

Cypress 10.9

**Comment by astone123** [comment] 2022-09-30 14:59
@romankhomitskyi could you provide an example project that can reproduce the issue reliably? That would allow me to take action on this. Thanks!

**Comment by romankhomitskyi** [comment] 2022-09-30 17:25
> @romankhomitskyi could you provide an example project that can reproduce the issue reliably? That would allow me to take action on this. Thanks!

Unfortunately, I could not

**Comment by marktnoonan** [comment] 2022-10-02 15:59
I wonder if we could act on this by adding some more guards around what is considered "user scrolling". The root cause of this seems to be that in certain situations, elements being added to the command log, and cypress autoscrolling, get interpreted as _user scrolling_. A user taking control by scrolling the command log to look at something while a test is running makes sense intuitively and I think it would be really disruptive (to a greater number of users) to change that behavior. 

To tighten this up though, after `user:scroll:detected` we could check if the pointer is over the scroll container in the command log. If it's not, the user most like was not intending to scroll the command log. Keyboard scrolling is unlikely since the Application Under Test almost always grabs keyboard focus. 

So we could skip `temporarilyDisableAutoScrolling` using that or some similar rubric, and only do it when we have extra signals that the user actually triggered the scroll event.

**Comment by astone123** [comment] 2022-10-07 17:41
I'm closing this ticket in favor or a more broad ticket that calls for investigating this issue further. #24171 Thanks to everyone who let us know that this is an issue

**Closed as completed by astone123** 2022-10-07 17:41 UTC
