### ISSUE TITLE
Cypress - New Window Opened and __ in url 

### ISSUE THREAD

**Issue by SevanAMPS** [cypress-io/cypress#7417] opened 2020-05-19 15:26 UTC
Hi there,

I have one issue with Cypress and doesn't understant very well what i need to do. 

My web application open a new window when we want print some data.  When we use Chrome, its a new tab, with Electron, its a new Window.

In this window appaer the PDF File. The URL Changed but I don't know I can test if this windows is correctlly appaear. Someone can help me plz ?

Technical points
The issue happened with Chrome 81 and Electron 80

- **Url should be** : _https://igg.iindustries.com/INSTANCE01Bin/XXXXX.dll/GetPrintReportFile?ID_MSG=693703_

**And Cypress try to open this URL** :  _https://igg.iindustries.com/__/GetPrintReportFile?ID_MSG=693703_

I Have no Idea where the bug is. 

**Other Example** : _Here, its not a new window or new tab its in the same iframe._
**Url should be** : _https://igg.iindustries.com/INSTANCE01Bin/XXXXX.dll/E39?ID1=1591060
https://igg.iindustries.com/__/E39?ID1=1591060_

**Comment by jennifer-shehane** [comment] 2020-05-20 08:00
This is likely due to this issue #3975 which will be fixed in our next release when passing a `experimentalSourceRewriting: true` configuration value. I suggest following  #3975 to see when this is released.

**Closed by jennifer-shehane** 2020-05-20 08:00 UTC

**Comment by jennifer-shehane** [comment] 2020-05-21 07:29
This fix is available starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments) which you can access by setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

The fix is experimental, so there may be some situations where the this is not fixed. 

If you're still this issue while setting the `experimentalSourceRewriting` to true in 4.6.0 - [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a reproducible example + screenshots, etc - filling out our issue template.
