### ISSUE TITLE
Asynchronous logging test results in 5.2.0 or other issue?

### ISSUE THREAD

**Issue by ammar01** [cypress-io/cypress#8607] opened 2020-09-17 17:40 UTC
### Current behavior: 

- We're using some plugin code to print debug messages to the screen when running in headless mode in a local terminal window and also to Jenkins build logs. 
- While evaluating Cypress 5.2.0 we're seeing that the order in which the logging messages appear in the output do not match up with the order they should appear in the code itself. 

- Here you can see the logout message is appearing BEFORE the final test in the output.
![image](https://user-images.githubusercontent.com/996294/93505765-30676a00-f913-11ea-84d9-df2501897f5f.png)

### Desired behavior:

- The output should look something like this where the logout message is appearing AFTER the final test. This is how our tests perform with Cypress 4.5.0 
![image](https://user-images.githubusercontent.com/996294/93505654-0ada6080-f913-11ea-9454-dfe5939bdf0c.png)

### Test code to reproduce

Here's the plugin code located in cypress/plugins/index.js: 
```
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('task', {
    log (message) {
      console.log(message)
      return null
    }
  })
}
```

- We call the plugin code in two separate files for logging in and out functions, that are included into the test spec file. We haven't modified any of our code/files between switching from 4.5.0 to 5.2.0

- In the login script we have this to output the message: 

`cy.task('log', `Logging in as ${role}`);`

- And here's the logging message in the logout script: 

`cy.task('log', `Logging out`);`

### Versions

Cypress 5.2.0, Mac OS Catalina, Chrome v85

Thanks for any light you can shed on this issue, whether it's user error or some thing else!

**Comment by bahmutov** [comment] 2020-09-17 17:43
I think because we are constantly fixing issues and upgrading Mocha engine we use internally that the new v5 messages are correct, right? You expect the "logging out" message to appear before the test finishes, since the message and `cy.task` is part of the test.

**Comment by ammar01** [comment] 2020-09-17 18:44
We're expecting it to look like the second screenshot where the "logging out" message appears after the last test completes.

We know the test is running fine as it passes but the way the logging appears in the output is confusing - it is suggesting we logged out of the app before we ran the last test - which would not be possible.

**Comment by bahmutov** [comment] 2020-09-17 18:56
I disagree - the v5 output makes more sense. Cypress waits for all its commands inside the test to finish before emitting "test finished" event (and then Mocha shows "✔ An insight cannot be created"). So the logging out tasks is _part_ of the test. What if it fails? You cannot have "✔ An insight cannot be created" followed by "oops, cy.task just blew up"

**Comment by ammar01** [comment] 2020-09-17 19:14
Yes I understand your point 👍 

I suppose the key is the logout action and the logging to terminal happens in the afterEach() function once the test itself completes. 

Sorry if I didn't make that clear before. Does that change things at all?

**Comment by bahmutov** [comment] 2020-09-17 19:35
Sure, here is my example using Mocha 

```js
it('works A', () => {
  console.log('in A')
})

it('works B', () => {
  console.log('in B')
})

afterEach(() => {
  console.log('Logging out')
})
```

When everything runs correctly

```
$ npx mocha mocha-test.js 


in A
  ✓ works A
Logging out
in B
  ✓ works B
Logging out

  2 passing (4ms)
```

Let's say test B fails in the callback function `it`

```js
it('works A', () => {
  console.log('in A')
})

it('works B', () => {
  console.log('in B')
  throw new Error('B fails')
})

afterEach(() => {
  console.log('Logging out')
})
```

The run result

```
$ npx mocha mocha-test.js 


in A
  ✓ works A
Logging out
in B
  1) works B
Logging out

  1 passing (5ms)
  1 failing

  1) works B:
     Error: B fails
```

Ok, at least it marked `works B` test as a failure. But now let's fail from the `afterEach` hook

```js
it('works A', () => {
  console.log('in A')
})

it('works B', () => {
  console.log('in B')
})

afterEach(() => {
  console.log('Logging out about to error')
  throw new Error('Logging out failed!')
})
```

Mocha in our opinion reports it incorrectly!

```
$ npx mocha mocha-test.js 


in A
  ✓ works A
Logging out about to error
  1) "after each" hook for "works A"

  1 passing (5ms)
  1 failing

  1) "after each" hook for "works A":
     Error: Logging out failed!
```

Weird right - what test is passing?! Mocha says "1 passing" and 1 "failing" - I assume "works A" is passing and "works B" has failed _even though it did not run at all_!

So we don't like this system at all. In our opinion, hooks like `beforeEach`, `afterEach` are just a way to organize reusable test code. Thus you should be able to move code from `afterEach` into the `it` and have it run its thing.

Here is where Cypress is different: we "know" and collect all hooks before and after the test, and run them and only mark test as passing when everything runs. Thus for us a failure to execute the `afterEach` hook is really a failure of the _test_, not some ambiguous failure down the line.

**Comment by bahmutov** [comment] 2020-09-18 14:57
@Bkucera do you have anything to add to this discussion? Or I can close this issue

**Comment by jennifer-shehane** [comment] 2021-02-22 14:34
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-02-22 14:34 UTC
Labels: stage: needs information, topic: hooks ↪
