### ISSUE TITLE
Alias in `before` block disappears after first test

### ISSUE THREAD

**Issue by ashleymercer** [cypress-io/cypress#18161] opened 2021-09-20 13:25 UTC
### Current behavior

If we alias a value in a `before()` block then it can only be retrieved (with `cy.get()`) in the first test in a suite; attempting to retrieve it in the second or subsequent tests results in

```
cy.get() could not find a registered alias for: @alias.
You have not aliased anything yet.
```

### Desired behavior

It is quite common to want to run a some initial query (e.g. a fetch from an API) at the start of a suite of tests, and alias with `cy.as()`. This alias should be available to all subsequent tests (within the current scope / context).

### Test code to reproduce

```ts
describe(`Test`, () => {
  
  function fetchUsers() {
    return new Promise<string[]>(resolve => resolve(['Alice', 'Bob']))
  }

  before(() => {
    cy.wrap(fetchUsers()).as('users')
  })

  // This test passes...
  it(`test 1`, () => {
    cy.get('@users').should('have.length', 2)
  })

  // ...but this one fails
  it(`test 2`, () => {
    cy.get('@users').should('have.length', 2)
  })
})
```

### Cypress Version

8.3.1

### Other

One workaround is to move the setup steps to `beforeEach` but this might be heavyweight (e.g. running a bunch of initial API requests on every single test, rather than once per suite)

**Comment by ashleymercer** [comment] 2021-09-20 13:27
I suspect this bug has the same root cause as https://github.com/cypress-io/cypress/issues/17467 but that issue was closed without being resolved, so this is still an issue in the latest versions.

**Comment by jennifer-shehane** [comment] 2021-09-20 15:28
Duplicate of https://github.com/cypress-io/cypress/issues/665 Aliases can't be used in before blocks.

**Closed by jennifer-shehane** 2021-09-20 15:28 UTC
