### ISSUE TITLE
type {enter} command to submit form failed if the form has reset button in front of submit button

### ISSUE THREAD

**Issue by Bigdragon13th** [cypress-io/cypress#4340] opened 2019-05-30 08:47 UTC
### Current behavior:

Given this form:
```html
<form id="myForm">
	<input type="text" id="myText">
	<button type="reset">Reset</button>
	<button type="submit">Submit</button>
</form>
```
And this test:
```javascript
cy.get('#myText').type('aaaa{enter}');
```

The test failed to submit the form correctly (submit with everything blank).
After my investigation, Cypress do both "Reset button click" and "Form Submit", console.log click event at reset button tells that Cypress really trigger a click event on it.

But if the form swap the buttons placement:
```html
<form id="myForm">
	<input type="text" id="myText">
	<button type="submit">Submit</button>
	<button type="reset">Reset</button>
</form>
```

Now the test will pass.

### Versions

Cypress: 3.3.1

**Comment by tuangillness** [comment] 2019-05-30 08:50
I found the same problem. I will be great if cypress fix it soon

**Comment by jennifer-shehane** [comment] 2019-05-30 14:20
Duplicate of https://github.com/cypress-io/cypress/issues/3909

**Closed by jennifer-shehane** 2019-05-30 14:20 UTC
