### ISSUE TITLE
Cypress reruns before hooks and skips tests when visiting multiple superdomains

### ISSUE THREAD

**Issue by c32hedge** [cypress-io/cypress#14179] opened 2020-12-14 21:51 UTC
### Current behavior

I have a test file that attempts to visit multiple superdomains in separate `describe` blocks. The behavior I'm seeing is that not only are the top-level `before` hooks getting rerun each time a new superdomain is visited, similar to what was described in #1987, but **the actual test contents are getting skipped**.

### Desired behavior

Before blocks shouldn't be rerun. Test contents should be run.

### Test code to reproduce

``` javascript
describe('page', () => {
  before('before 1', () => {
    cy.log('before 1');
  });

  before('before 2', () => {
    cy.log('before 2');
  });

  describe('inner describe 1', () => {
    it('runs describe 1 test 1', () => {
      cy.visit('www.google.com');
      cy.log('describe 1 test 1');
    });
  });

  describe('inner describe 2', () => {
    it('runs describe 2 test 1', () => {
      cy.visit('www.cypress.io');
      cy.log('describe 2 test 1');
    });
  });

  describe('inner describe 3', () => {
    it('runs describe 3 test 1', () => {
      cy.visit('www.github.com');
      cy.log('describe 3 test 1');
    });
  });
});
```

![image](https://user-images.githubusercontent.com/8810829/102139723-3692b700-3e2c-11eb-865b-6029c68c238d.png)

### Versions

Cypress: Reproduced on 5.5.0 and 6.1.0
Chrome Version 87.0.4280.66 (Official Build) (64-bit)
Ubuntu 20.04

**Comment by c32hedge** [comment] 2020-12-14 21:55
If I replace the second two `cy.visit` calls with the same superdomain as the first test, the tests behave as I would expect.

**Comment by jennifer-shehane** [comment] 2020-12-15 06:44
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/9026 - this issue was introduced in 4.8.0. I will add this example to the comments of the other issue. Thanks for opening!

**Closed by jennifer-shehane** 2020-12-15 06:44 UTC
