### ISSUE TITLE
Cypress 10.3.1 does not open interactive mode with node v18.7

### ISSUE THREAD

**Issue by alyaothman14** [cypress-io/cypress#23056] opened 2022-08-02 09:07 UTC
### Current behavior

1. Update the node version to 18.7
2. Run cypress locally in interactive mode
An error is thrown
If the node version is downgraded to 18.2 then no errors are thrown
![image](https://user-images.githubusercontent.com/87079479/182337132-9065ed7c-114d-408f-88c0-a26c935786bd.png)

### Desired behavior

Cypress interactive mode should work with v18.7 without throwing an error

### Test code to reproduce

Use node V18.7
run cypress open --e2e --browser chrome

### Cypress Version

10.3.1

**Comment by mjhenkes** [comment] 2022-08-02 18:58
Duplicate of https://github.com/cypress-io/cypress/issues/22795

**Closed by mjhenkes** 2022-08-02 18:58 UTC
