### ISSUE TITLE
Not able to run default test that come with test runner , chrome just hangs 

### ISSUE THREAD

**Issue by raj1girish** [cypress-io/cypress#8812] opened 2020-10-12 09:05 UTC
Not able to run the test on test runner , chrome just hangs 

### Current behavior
when cypress test runner opens and click on one of the test that come with cypress test runner I see that the chrome browser opens up but nothing happens after that it is just waiting. In the runner it says Opening Chrome 86 with a spinner
<img width="800" alt="Screenshot 2020-10-12 at 10 03 42" src="https://user-images.githubusercontent.com/5698720/95727584-40543e80-0c72-11eb-9875-c979fd08dafc.png">

### Desired behavior
Chrome browser should open and I should be able to see the test running

### Test code to reproduce
I am trying to run tests that come with cypress in the example folder.

I see nothing in debug console

**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">65320</span>.

Error details:

Error: connect ETIMEDOUT 92.242.132.24:65320
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m65320[39m.

Error details:

Error: connect ETIMEDOUT 92.242.132.24:65320
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)

    at get (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:968:15)
    at Object.throwErr [as throw] (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:986:9)
    at /Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:105:21
    at tryCatcher (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/girishpottigari/Library/Caches/Cypress/5.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

```

### Versions
MAC OS 10.15.6 (19G73)
chrome  86.0.4240.75 (Official Build) (x86_64)
Cypress 5.3.0
node JS: v12.19.0

**Comment by raj1girish** [comment] 2020-10-12 09:08
I could see nothing in the browser console or network tab
Nothing in debug console

**Comment by jennifer-shehane** [comment] 2020-12-16 05:36
Duplicate of https://github.com/cypress-io/cypress/issues/8986

**Closed by jennifer-shehane** 2020-12-16 05:36 UTC
Labels: topic: CDP connection
