### ISSUE TITLE
Invoke with as fails the assertion in version 12

### ISSUE THREAD

**Issue by Mandersen21** [cypress-io/cypress#25086] opened 2022-12-09 10:43 UTC
### Current behavior

If you do something like:

cy.get('div[data-e2e="someName"]').invoke('text').as('@someName')

and then tries to get the data saved 

cy.get('@someName').then((value) => 

Then value is empty from version 12, but works in version 11.2.0

### Desired behavior

There should be a value

### Test code to reproduce

Just try to do as you see in current behavior

### Cypress Version

11.2.0

### Node version

v14.17.0

### Operating System

Mac

**Comment by vergjor** [comment] 2022-12-09 12:11
Yes!! This is a major blocker for the migration to v12 since I also have a lot of tests and custom commands that depend on aliases! The strange thing is, it somehow worked in one instance:

```ts
cy.get('@LabelName').within(() => {
  cy.get('[data-testid="expand-button"]').click();
});
```

but when I try to chain it with other commands, even with `.then()`:

```ts
cy.get('@LabelName').then(($label) => {
  console.log($label);
});
```

the value of the alias could not be found :(

**Comment by BlueWinds** [comment] 2022-12-13 20:18
> cy.get('div[data-e2e="someName"]').invoke('text').as('@somename')

This code has a mistake - you retrieve aliases without `@`, but retrieve them with it.

I'm also having trouble reproducing the behavior you're showing.

```
it.only('works', {}, () => {
  cy.visit('https://wikipedia.org')
  cy.get('li').first().invoke('text').as('somename')

  cy.get('@somename').then(text => {
    expect(text).to.equal('Polski')
  })
  cy.get('@somename').then(text => {
    expect(text).to.equal('Polski')
  })
});
```

The behavior around aliases did change slightly in 12.0.0: The value is always requeried live. So if you want to alias a *static* value - eg, read the value once and store it as an alias - you'll need to put a non-query command (like .then() or .wrap()) in the chain. Eg:

```
cy.get('div[data-e2e="someName"]').invoke('text').then(text => cy.wrap(text).as('@somename'))
```

If someone wants to provide a reproducible example where you're running into issues not explained above, I'm happy to take a further look.

**Comment by samtsai** [comment] 2022-12-13 20:42
It'd be great to document that change if not already. I was caught off guard by the re-querying as well and some of my tests relied on static values, but maybe it was never designed this way?

At any rate, I appreciate all of the hard work you've done for us 😄 @BlueWinds

**Comment by rkrisztian** [comment] 2022-12-14 10:27
I have the same issue with:

```javascript
		cy.get('#search-results tbody tr').as('items in table')
			.should('have.length', 0);
```

It does not fail if:

* I expect non-zero items
* I remove the `.as(...)` call

**Comment by BlueWinds** [comment] 2022-12-14 17:55
> I have the same issue with:
> 
> ```js
> 		cy.get('#search-results tbody tr').as('items in table')
> 			.should('have.length', 0);
> ```
> 
> It does not fail if:
> 
>     * I expect non-zero items
> 
>     * I remove the `.as(...)` call

This is not the same issue - this one is about `.invoke()`, which you're not using at all. I'd suggest creating a new issue, and be sure to include a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/).

**Comment by BlueWinds** [comment] 2022-12-14 18:00
> I have the same issue with:
> 
> ```js
> 		cy.get('#search-results tbody tr').as('items in table')
> 			.should('have.length', 0);
> ```
> 
> It does not fail if:
> 
>     * I expect non-zero items
> 
>     * I remove the `.as(...)` call

Sorry, I replied too quickly previously - have a lot of issue coming in, lost track of which one I was commenting in. This comment does belong here, my mistake. :)

**Comment by BlueWinds** [comment] 2022-12-14 20:41
> It does not fail if:

>    I expect non-zero items
>    I remove the .as(...) call

This is completely expected behavior. Remember that every command has implicit assertions, such as "the element you're querying exists".

Adding `.should('have.length', 0)` overrides the default existence assertion *for the command it's attached to*.

So if you attach the assertion to `.get()`, then you'll override its existence assertion. If you attach the assertion to `.as()`, then you'll override *it's* existence assertion.

In Cypress 12, `.as()` is a first-class citizen - it works the same as any other query, and follows the same rules. :woman_shrugging:

**Comment by BlueWinds** [comment] 2022-12-14 20:43
> It'd be great to document that change if not already. I was caught off guard by the re-querying as well and some of my tests relied on static values, but maybe it was never designed this way?
> 
> At any rate, I appreciate all of the hard work you've done for us smile @BlueWinds

Improving the documentation around how aliases retry would be a good idea, as would adding these changes to the 12.x changelog. :+1:

**Comment by rkrisztian** [comment] 2022-12-14 20:54
My bad then, I used "as" as some kind of documentation to the element I was querying, which is wrong on its own. => You were right, my problem is irrelevant to the ticket.

**Comment by BlueWinds** [comment] 2022-12-21 17:08
Going to close this as duplicate of https://github.com/cypress-io/cypress/issues/25173, which has a bit more activity discussing the same problems in Cy 12. See there for ongoing updates.

**Closed as completed by BlueWinds** 2022-12-21 17:08 UTC
Labels: E2E
