### ISSUE TITLE
Cypress clears cookies before JavaScript is terminated

### ISSUE THREAD

**Issue by mzedeler** [cypress-io/cypress#15247] opened 2021-02-26 13:31 UTC
### Current behavior
When Cypress starts executing a new test, it will clear all cookies even if the JavaScript code in the old test is still executing.
This can be the source of confusing errors reporting 401 responses from the backend where Cypress wrongly reports them as having been triggered by `beforeEach`.

### Desired behavior
Make sure that the JavaScript code from the previous test has stopped or block all network traffic between tests before clearing all cookies.

### Versions

6.4.0

**Comment by jennifer-shehane** [comment] 2021-02-26 21:12
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by cbruge** [comment] 2021-02-27 09:55
I had a similar situation but was able to work around it using preserveOnce and also wait for the respective backend call via intercept/wait...maybe that helps?

**Comment by geigerzaehler** [comment] 2021-05-31 16:25
Here’s a minimal example to reproduce the issue.
```html
<!DOCTYPE html>
<script>
  document.cookie = "foo=bar"
  let interval = setInterval(() => {
    if (document.cookie !== "foo=bar") {
      clearInterval(interval)
      throw new Error(`Invalid cookie ${document.cookie}. Hash: ${document.location.hash}`)
    }
  }, 10)
</script>
```

```js
it("first", () => {
  cy.visit("./index.html#first")
  cy.wait(1000)
})

it("second", () => {
  cy.visit("./index.html#second")
  cy.wait(1000)
})
```

The first test case always passes. The second always errors because the first instance of the app (as witnessed by the `#first` location) crashes.

**Comment by emilyrohrbough** [comment] 2022-11-16 21:55
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation) to prevent cases like this. There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests.

Closing this issue as done and tagging for the v12.0.0 release.

**Closed by emilyrohrbough** 2022-11-16 21:55 UTC
Labels: stage: needs information, v12.0 Release
