### ISSUE TITLE
A page does not load

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#215] opened 2016-09-08 11:56 UTC
Very weird test failures with 0.17.2

I have a website deployed to Zeit.co cloud that works fine in a browser

https://express-sessions-tutorial-germflsgid.now.sh/

It has a form page that also works fine

https://express-sessions-tutorial-germflsgid.now.sh/form

I have 4 e2e tests in the repo https://github.com/bahmutov/express-sessions-tutorial

These tests work fine against local website, but 2 tests fail when running against the deployed website. I am attaching the screenshots. During tests it 404s the `/form` page.

I can recreate the failures using by setting the host url when opening cypress

```sh
CYPRESS_HOST=https://express-sessions-tutorial-germflsgid.now.sh/ cypress open
```

Page works in the browser
<img width="1440" alt="screen shot 2016-09-08 at 7 50 35 am" src="https://cloud.githubusercontent.com/assets/2212006/18348509/b6a3627e-7599-11e6-96b3-9d780f395db1.png">

Fails to load in Cypress
<img width="1360" alt="screen shot 2016-09-08 at 7 49 27 am" src="https://cloud.githubusercontent.com/assets/2212006/18348523/c71e14c8-7599-11e6-97c1-638f5c581b4a.png">

**Comment by bahmutov** [comment] 2016-09-08 11:57
Zeit deploys do use HTTP/2 but that would not explain why subpage does not load.

**Comment by bahmutov** [comment] 2016-09-08 12:47
The full log is available at https://travis-ci.org/bahmutov/express-sessions-tutorial/builds/158356408
- first it runs e2e tests against local server (all good)
- then it deploys the server and runs the cy tests against the deployed url, and two tests fail

**Comment by bahmutov** [comment] 2016-09-08 16:50
Another project with similar problem - the `/app.css` does not load when running inside the test
https://todomvc-express-mrsrokqrdw.now.sh/ is working by itself, but not from the e2e tests
https://github.com/bahmutov/todomvc-express to run
```
CYPRESS_HOST=https://todomvc-express-mrsrokqrdw.now.sh/ cypress open
```
<img width="1273" alt="screen shot 2016-09-08 at 12 48 09 pm" src="https://cloud.githubusercontent.com/assets/2212006/18358400/d1e310ba-75c2-11e6-91a0-4138164704ca.png">

**Comment by bahmutov** [comment] 2016-09-08 17:22
Seems to work in Cypress 0.16.5
<img width="1165" alt="screen shot 2016-09-08 at 1 21 38 pm" src="https://cloud.githubusercontent.com/assets/2212006/18359284/3d5b083a-75c7-11e6-862d-df205e7318ed.png">

**Comment by brian-mann** [comment] 2016-09-08 17:24
This is most definitely a proxy issue with `17`. I'll look at it tonight and let you know. Likely will be straightforward to reproduce and fix.

**Comment by bahmutov** [comment] 2016-09-09 15:02
I got more permanent domain for this to avoid changing urls https://todomvc-express.bahmutov.com/

**Comment by brian-mann** [comment] 2016-09-11 23:52
Both of the issues discussed here are due to #222.

Closing in favor of that issue.

**Closed by brian-mann** 2016-09-11 23:52 UTC
Labels: bug

**Comment by brian-mann** [comment] 2016-09-11 23:58
Also I would probably open an issue with `zeit.co` as well because their reverse proxy should probably take this into account.

This will be fixed in `cypress` but there over `16 million` downloads of the `request` module per month and requesting anything.

Additionally - it seems to only happen if you *include* the port in the url.

This will fail:

```
request("https://todomvc-express.bahmutov.com:443/app.css")
```

But this will pass:

```
request("https://todomvc-express.bahmutov.com/app.css")
```
