### ISSUE TITLE
Cypress + headless Electron: CoreText warning

### ISSUE THREAD

**Issue by jeff00seattle** [cypress-io/cypress#16762] opened 2021-06-01 16:04 UTC
I have recently migrated to **macOS version Catalina**, test running using **Cypress version 7.4.0**, and browser **Electron v13.0.1** installed.

If a headless test runner using browser Electron is started as follows in the command line, the tests do run properly but the Cypress Helper initiates with the following warning:

    cypress run --browser electron --headless

    Cypress Helper (Renderer)[28020:1581833] CoreText note:  
        Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
    Cypress Helper (Renderer)[28020:1581833] CoreText note: 
        Client requested name ".AppleSymbolsFB", it will get  
        Times-Roman rather than the intended font. All system UI  
        font access should be through proper APIs such as  
        CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

This warning is not generated if a headless browser is Chrome.

    cypress run --browser chrome --headless

Suggestions for resolving this warning issue?

**Comment by jennifer-shehane** [comment] 2021-06-01 16:27
Duplicate of https://github.com/cypress-io/cypress/issues/7245

**Closed by jennifer-shehane** 2021-06-01 16:27 UTC

**Comment by jeff00seattle** [comment] 2021-06-01 19:20
@jennifer-shehane After reading #7245, it is not clear what I am expected to perform to resolve this issue. Thank you

**Comment by jennifer-shehane** [comment] 2021-06-16 15:28
@jeff00seattle It's just a warning, so it can be safely ignored. There's nothing to do on your side - that issue is open because Cypress needs to fix the issue.
