### ISSUE TITLE
blacklistHosts configuration not working with chrome

### ISSUE THREAD

**Issue by sravan-s** [cypress-io/cypress#1154] opened 2018-01-05 17:14 UTC
- Operating System: mac os 10.13.2
- Cypress Version: 1.4.1
- Browser Version: Chrome 63

### Is this a Feature or Bug?
Bug

### Current behaviour:
https://docs.cypress.io/guides/references/configuration.html#blacklistHosts
blacklistHosts works well with Electron but isn't working with chrome.
i.e. - wouldn't block desired websites if we are using chrome for testing

### Desired behavior:
blacklistHosts should  work well with all browsers

### How to reproduce:

- Clone example recipes- https://github.com/cypress-io/cypress-example-recipes
- Run `npm run cypress:open` and select `stubbing-spying__google-analytics`
- Set browser as chrome 
- Run tests
- Tests should fail

#### Test code:

```js

```

### Additional Info (images, stack traces, etc)
![screen recording](https://user-images.githubusercontent.com/11382805/34619890-08eddfee-f287-11e7-916b-87a492383b7a.gif)

**Comment by brian-mann** [comment] 2018-01-05 17:34
This is a known issue that we just haven't had time to fix yet. I wrote these tests and they could be better. However, this has nothing to do with `blacklistHosts` - they work just fine. We have a boat load of tests around them. This is failing due to a different issue.

**Comment by brian-mann** [comment] 2018-01-07 00:32
Closing because this is an issue with the recipes, not Cypress itself.

https://github.com/cypress-io/cypress/issues/1154

**Comment by brian-mann** [comment] 2018-02-12 19:30
After investigating it does appear that `blacklistHosts` are not working under specific conditions that need investigation. I can see via the logs that when running locally it is applying, but under 3 different CI providers it is not. It could be an issue with Cypress itself.

**Comment by sravan-s** [comment] 2018-02-13 06:51
One more pointer, blacklist hosts work with chrome on cypress 1.2.0(we found it out recently)

**Comment by brian-mann** [comment] 2018-02-13 23:59
I figured out the root cause and will post back here with more information shortly.

**Comment by brian-mann** [comment] 2018-02-14 04:52
The root cause of this has to do with browser caching to disk.

What's happening in the Recipes is that because we utilize the same Cypress profile in between runs - that a previous test was first causing a request to `https://www.google-analytics.com/analytics.js`.

Then the browser would then cache the response to disk.

In subsequent runs of the browser, the Cache had not expired yet - so instead of making a real HTTP request to the server (which would have been blacklisted), the browser serves the file immediately from the disk cache.

We're going to be updating Cypress to automatically clear the disk cache whenever the browser is first spawned.

The related issue is here: https://github.com/cypress-io/cypress/issues/1124

**Comment by bahmutov** [comment] 2018-02-14 05:33
Unbelievable find, great work!

**Comment by brian-mann** [comment] 2018-02-14 20:08
Fixed by https://github.com/cypress-io/cypress/pull/1310

**Closed by brian-mann** 2018-02-14 20:08 UTC
Labels: type: unexpected behavior

**Comment by brian-mann** [comment] 2018-02-16 06:16
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
