### ISSUE TITLE
Missing request.body in cy.wait(@alias).then() after stubbing cy.route2

### ISSUE THREAD

**Issue by ChrisSargent** [cypress-io/cypress#8939] opened 2020-10-22 19:11 UTC
### Current behavior
`body` is not available on `request` in `cy.wait('@alias').then(({request}) => ...)` when proving a mock to `cy.route2`

### Desired behavior
`body` should still be available on `request` in `cy.wait('@alias').then(({request}) => ...)`

### Test code to reproduce
See: https://github.com/ChrisSargent/cypress-test-tiny
```js
describe("page", () => {
  it("with mocked cy.route2 respone, there is no request body in cy.wait", () => {
    const intercept = {
      method: "POST",
      pathname: "/graphql",
    };
    const response = {
      body: {
        data: {
          hello: "world",
        },
      },
      headers: {
        "Access-Control-Allow-Origin": "*",
      },
    };

    cy.route2(intercept, response).as("gql");
    cy.visit(
      "https://map.tacklehunger.org/donate?site=recOJoeAptDHrjhOC"
    );
    cy.wait("@gql").then((request) => console.log(request));
  });
  it("with NON-mocked cy.route2 respone, there is a request body in cy.wait", () => {
    const intercept = {
      method: "POST",
      pathname: "/graphql",
    };
    cy.route2(intercept).as("gql");
    cy.visit(
      "https://map.tacklehunger.org/donate?site=recOJoeAptDHrjhOC"
    );
    cy.wait("@gql").then((request) => console.log(request));
  });
});

```

### Versions
Cypress 5.4.0

Maybe I'm mis-understanding the functionality but I feel like this is how it worked with `cy.route` at least?

**Comment by jennifer-shehane** [comment] 2020-10-23 05:19
This is a duplicate of https://github.com/cypress-io/cypress/issues/8695, it will be fixed in the next release.

**Closed by jennifer-shehane** 2020-10-23 05:19 UTC
