### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by calwayne** [cypress-io/cypress#6887] opened 2020-03-31 06:15 UTC
### Current behavior:
I am using fixture data in my test suite, with `command.j` and also the pageObject model with following code. However, the test runner hits below error with passed (means it has nothing wrong with my code) while crashed immediately with window prompt "Cypress quit unexpectedly Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple":

```
  Running:  test-suite/searchBangkokProject.js                                              (1 of 1)


  As reader, I wish to go to project landing page
    ✓ should show me project landing page (7315ms)


  1 passing (7s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     7 seconds                                                                        │
  │ Spec Ran:     test-suite/searchBangkokProject.js                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (19.2.0)
Cypress Version: 4.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```js
import SearchResultPage from '../pageObjects/SearchResultPage';

describe('As reader, I wish to go to project landing page', function(){
    before(function(){
        cy.fixture('SearchData').then(function(data){
            this.data=data
        })
    })
    it('should show me project landing page', function(){

        const searchResultPage=new SearchResultPage();

        searchResultPage.getHomePage();

        searchResultPage.getSearchBox().click({force:true})

        //Type value into the search box based on fixture file
        searchResultPage.typeIntoSearchBox().type(this.data.project).type('{enter}');

        //When search result page shown, it should display pattaya projects and URL should be correct
        searchResultPage.getURLverified().should('eq',this.data.bangkokUrl)

        //SRP should show result "BANGKOK SKY" and "The Bangkok Sukhumvit 38" and "THE BANGKOK ทองหล่อ"
        searchResultPage.getCardWrapperVerified().contains(this.data.cardTitle1).should('have.text',this.data.cardTitle1);

        searchResultPage.getCardWrapperVerified().contains(this.data.cardTitle2).should('have.text',this.data.cardTitle2);

        searchResultPage.getCardWrapperVerified().contains(this.data.cardTitle3).should('have.text',this.data.cardTitle3);

        cy.VerifySearchedResult();
    });

});
```

### Desired behavior:
I realised that when I commented out 

```js
searchResultPage.getCardWrapperVerified().contains(this.data.cardTitle1).should('have.text',this.data.cardTitle1);
    searchResultPage.getCardWrapperVerified().contains(this.data.cardTitle2).should('have.text',this.data.cardTitle2);
    searchResultPage.getCardWrapperVerified().contains(this.data.cardTitle3).should('have.text',this.data.cardTitle3);
```

everything gets back to normal without error.

**Comment by jennifer-shehane** [comment] 2020-04-01 10:14
I'm not able to reproduce this on my side with the information given.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-04-01 10:14 UTC
