### ISSUE TITLE
ERR_OSSL_PEM_NO_START_LINE when running tests

### ISSUE THREAD

**Issue by leevigraham** [cypress-io/cypress#15953] opened 2021-04-13 00:57 UTC
### Current behavior

* Running Cypress 7.1.0 on OSX High Sierra (`LibreSSL 2.2.7`)
* Testing local site https://thephn.test with a self signed (mkcert) certificate on nginx
* Navigating within site triggers error: `ERR_OSSL_PEM_NO_START_LINE`

Same test suite passes on OSX Big Sur and Catalina with `LibreSSL 2.8.3`

The error seems to be triggered when using `cy.visit()` (same domain)

Console Output:

```
GVA info: Successfully connected to the Intel plugin, offline Gen7 
GET /__/ 200 5.365 ms - -
GET /__cypress/runner/cypress_runner.css 200 5.131 ms - -
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 255.466 ms - -
GET /chrome-variations/seed?osname=mac&channel=stable&milestone=89 304 323.098 ms - -
GET /__cypress/runner/cypress_runner.js 200 4.363 ms - -
GET /__cypress/iframes/integration/contact.spec.js 200 4.517 ms - 936
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 1.172 ms - 76120
GET /v1/pages/ChRDaHJvbWUvODkuMC40Mzg5LjExNBIQCZvSnKReDrmYEgUNkWGVThIXCYBpI15f7V1OEgUNL4g-ghIFDZFhlU4=?alt=proto 200 283.028 ms - -
GET /__cypress/tests?p=cypress/integration/contact.spec.js 200 1092.107 ms - -
GET /__cypress/tests?p=cypress/support/index.js 200 1101.821 ms - -
GET /contact-us 200 18.076 ms - -
GET /build/css/app_tailwind_css.css 200 19.759 ms - -
GET /build/css/vendor_css.css 200 37.504 ms - -
GET /cpresources/b8a83730/freeform.js?v=1617855932 200 32.406 ms - -
GET /v3/polyfill.min.js?flags=gated&features=Promise%2CPromise.prototype.finally%2CObject.assign%2CArray.from 200 50.335 ms - -
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
  at Object.createSecureContext (_tls_common.js:129:17)
  at Server.addContext (_tls_wrap.js:1420:32)
  at /Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:222:23
  at tryCatcher (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:512:31)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:582:21)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at Promise._resolveCallback (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:432:57)
  at Promise._settlePromiseFromHandler (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:524:17)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at PromiseArray._resolve (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
  at PromiseArray._promiseFulfilled (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
  at PromiseArray._iterate (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:114:31)
  at PromiseArray.init [as _init] (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:78:10)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:566:21)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at PromiseArray._resolve (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
  at PromiseArray._promiseFulfilled (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:574:26)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at _drainQueueStep (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:138:12)
  at _drainQueue (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:131:9)
  at Async._drainQueues (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:147:5)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:17:14)
  at processImmediate (internal/timers.js:461:21)
 {
 library: ‘PEM routines’,
 function: ‘OPENSSL_internal’,
 reason: ‘NO_START_LINE’,
 code: ‘ERR_OSSL_PEM_NO_START_LINE’
}
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
  at Object.createSecureContext (_tls_common.js:129:17)
  at Server.addContext (_tls_wrap.js:1420:32)
  at /Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:222:23
  at tryCatcher (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:512:31)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:582:21)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at Promise._resolveCallback (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:432:57)
  at Promise._settlePromiseFromHandler (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:524:17)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at PromiseArray._resolve (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
  at PromiseArray._promiseFulfilled (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
  at PromiseArray._iterate (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:114:31)
  at PromiseArray.init [as _init] (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:78:10)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:566:21)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at Promise._fulfill (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
  at PromiseArray._resolve (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
  at PromiseArray._promiseFulfilled (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
  at Promise._settlePromise (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:574:26)
  at Promise._settlePromise0 (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
  at _drainQueueStep (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:138:12)
  at _drainQueue (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:131:9)
  at Async._drainQueues (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:147:5)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:17:14)
  at processImmediate (internal/timers.js:461:21)

TypeError [ERR_UNKNOWN_SIGNAL] [ERR_UNKNOWN_SIGNAL]: Unknown signal: true
  at convertToValidSignal (internal/util.js:251:9)
  at ChildProcess.kill (internal/child_process.js:472:5)
  at Object.<anonymous> (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/chrome.js:442:43)
  at Generator.next (<anonymous>:null:null)
  at fulfilled (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/chrome.js:24:58)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
 {
 code: ‘ERR_UNKNOWN_SIGNAL’
}
TypeError [ERR_UNKNOWN_SIGNAL] [ERR_UNKNOWN_SIGNAL]: Unknown signal: true
  at convertToValidSignal (internal/util.js:251:9)
  at ChildProcess.kill (internal/child_process.js:472:5)
  at Object.<anonymous> (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/chrome.js:442:43)
  at Generator.next (<anonymous>:null:null)
  at fulfilled (/Users/iainhenderson/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/chrome.js:24:58)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)```
```

### Desired behavior

Error not thrown.

### Versions

Cypress 7.1.0
OSX High Sierra 
LibreSSL 2.2.7

**Comment by szy54** [comment] 2021-07-23 10:47
A possible duplicate of https://github.com/cypress-io/cypress/issues/8705. Check out the community proposed workaround there.

**Comment by flotwig** [comment] 2021-08-06 02:15
Definitely sounds like a dupe of #8705. #17628 should resolve it. Let's move future communication to #8705.

**Closed by flotwig** 2021-08-06 02:15 UTC
