### ISSUE TITLE
Problem with running multiple tests in Firefox

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#6767] opened 2020-03-18 08:21 UTC
### Current behavior:

After running correctly a first test file it crashes at the beginning of the second file.
Problem is only with Firefox browser. It's running normally on Chrome.
I'm pasting my terminal log:
![obraz](https://user-images.githubusercontent.com/34089686/76939969-ae619e80-68f9-11ea-8d51-93643498f825.png)

### Desired behavior:
Tests should run on Firefox either

### Versions
Cypress 4.2.0
Firefox 62.0.0.6816
Windows 10.0.17134.1365

**Comment by jennifer-shehane** [comment] 2020-03-18 08:57
Hey @zbigniewkalinowski, we have lots of tests that run through Firefox, so likely this is something specific to your config or tests that we will need to isolate. 

Saw mention of a similar error here: https://github.com/cypress-io/cypress/issues/6392#issuecomment-585099681

Can you provide the simplest example of test code that you are running in spec 1 and spec 2 that we can run? And any configuration around the tests - otherwise we will have to close this issue as we have no path forward to investigate.

**Comment by zbigniewkalinowski** [comment] 2020-03-18 09:35
Anything I'm trying to test is crashing after first file.
Example:

File 01.js
describe('Test 1', () => {
  it('Test 1', () => {
    expect(true).to.equal(true)
  })
})

File 02.js
describe('Test 2', () => {
  it('Test 2', () => {
    expect(false).to.equal(false)
  })
})

I'm attaching screenshot and log file
[2020-03-18T09_28_38_012Z-debug.log](https://github.com/cypress-io/cypress/files/4348128/2020-03-18T09_28_38_012Z-debug.log)

![bug](https://user-images.githubusercontent.com/34089686/76946189-f1287400-6903-11ea-827e-6c621e4696bc.jpg)

**Comment by jennifer-shehane** [comment] 2020-03-18 09:45
Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

Also, I see you have mocha-awesome reports set up, could you turn those off and see if that makes a difference?

**Comment by zbigniewkalinowski** [comment] 2020-03-18 10:24
[debug_log_mocha.txt](https://github.com/cypress-io/cypress/files/4348396/debug_log_mocha.txt)

I pasted debug_log with mocha turned on. Now I have to figure out how to turn it off :)

**Comment by zbigniewkalinowski** [comment] 2020-03-18 10:41
[debug_log_nomocha.txt](https://github.com/cypress-io/cypress/files/4348460/debug_log_nomocha.txt)

Log with mocha off

**Comment by jennifer-shehane** [comment] 2020-04-10 09:30
I just can't recreate this as provided. Do you have any other configuration involved? Like `plugins/index.js` / `support` files? Any cypress plugins? 

It's likely something specific to your environment or setup since we have a lot of tests around Firefox testing.

**Comment by zettadam** [comment] 2020-04-10 17:30
I can confirm this behavior (on Windows 10, Cypress@4.3.0 without any plugins stalled) though I get a slightly different error.

When running this command:

```
cypress run --browser firefox --headless
```

I see this error in the console (after I close popup window sayinh that Firefox is already running, but is not responding)

```
Running:  xyz.spec.js
                   (2 of 2)
Cypress could not connect to Firefox.

An unexpected error was received from Marionette connection:

Error: cannot open socket

To avoid this error, ensure that there are no other instances of Firefox
launched by Cypress running.
```

When I see all my processes running in Task Manager, I don't see any Firefox processes during tests though the first test is run and passes.

**Comment by jennifer-shehane** [comment] 2020-04-29 06:42
Duplicate of #6392. Trying to consolidate all these issues with the same error message.

**Closed by jennifer-shehane** 2020-04-29 06:42 UTC
Labels: OS: windows, browser: firefox, stage: needs information
