### ISSUE TITLE
Regression: confusing error message when first run smoke test fails

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#22399] opened 2022-06-20 09:25 UTC
### Current behavior

When the first run smoke test of Cypress 10.1.0 fails, the error message complains about "running the Cypress binary directly", and asks to install the NPM package, even though I _did_ install the NPM package and I am running Cypress using `npx cypress open` as per the documentation.
![image](https://user-images.githubusercontent.com/36038882/174559118-1802e89e-2717-4c13-9021-3ee79bd5228e.png)

### Desired behavior

In 9.7.0, the error message does not include the confusing part:
![image](https://user-images.githubusercontent.com/36038882/174568937-30df62d8-a2ce-4886-b79b-bd33fa25c450.png)
I seem to remember that some earlier version of Cypress would suggest a way to increase the verification timeout? At any rate, instructions on how to do that might be helpful in case 30 seconds consistently proves to be too short

### Test code to reproduce

Install and run Cypress per the documentation on a slow machine, or set `CYPRESS_VERIFY_TIMEOUT` to a low value to ensure the first run smoke test times out

### Cypress Version

10.1.0

**Comment by tbiethman** [comment] 2022-06-30 15:47
@JessefSpecialisterren thank you for the report, and apologies for the late response. I've looked into this a bit, and I can't seem to reproduce the output you're seeing. I tried on both macOS and Windows.

<details>
<summary>Log</summary>

```
PS C:\Users\Administrator\Documents\GitHub\cypress-component-testing-apps\react-cra5-ts> npx cypress open
It looks like this is your first time using Cypress: 10.3.0


Cypress verification timed out.

This command failed with the following output:

C:\Users\Administrator\AppData\Local\Cypress\Cache\10.3.0\Cypress\Cypress.exe --smoke-test --ping=433

----------

Command timed out after 1000 milliseconds: C:\Users\Administrator\AppData\Local\Cypress\Cache\10.3.0\Cypress\Cypress.exe --smoke-test --ping=433
Timed out

----------

Platform: win32-x64 (10.0.20348)
Cypress Version: 10.3.0
```

</details>

Are you seeing the incorrect output (with "It looks like you are running the binary directly...") every time the verification times out, or is it intermittent? In either case, could you try [removing your local Cypress installations](https://docs.cypress.io/guides/references/troubleshooting#Clear-Cypress-cache) by running `cypress cache clear`, installing cypress again, and seeing if further verification timeouts exhibit this issue?

**Comment by JessefSpecialisterren** [comment] 2022-07-01 09:12
Spent some time trying to reproduce this issue today with Cypress 10.3.0. Initially, all my attempts looked like the log you posted, no confusing error message to be seen. I finally got the confusing error message again by triggering the first run smoke test on a very slow Windows 10 VM and with `CYPRESS_VERIFY_TIMEOUT` unset (setting `CYPRESS_VERIFY_TIMEOUT` to a low value actually seems to _prevent_ the confusing error message, but maybe that's just flake). My guess is that it's somehow tied to a race condition.

At any rate, I wouldn't blame you for not assigning a high priority to this issue unless more people report experiencing it. Thank you for investigating and responding 🙂!

**Comment by tbiethman** [comment] 2022-07-01 21:10
That's good info to have, thanks @JessefSpecialisterren! We'll try to repro under those conditions as well.

**Comment by tbiethman** [comment] 2022-07-11 21:40
@JessefSpecialisterren after a few more attempts to reproduce this on a resource-constrained device, I'm still unable to recreate the output you saw. I'm going to close this issue, as it will be hard to move forward with a fix without a consistent reproduction. Thank you for the report and the time spent on your own investigation; if this issue surfaces again with more consistency/regularity, please log another issue so we can take another look.

**Closed by tbiethman** 2022-07-11 21:40 UTC
Labels: stage: awaiting response
