### ISSUE TITLE
Component tests occasionally fail with error "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by marcelwgn** [cypress-io/cypress#27101] opened 2023-06-21 14:09 UTC
### Current behavior

Our component tests occasionally fail with the following two stacktraces:

```
An uncaught error was detected outside of a test:
     TypeError: Cannot read properties of undefined (reading 'prevAttempts')
      at replacePreviousAttemptWith (http://localhost:3002/__cypress/runner/cypress_runner.js:170126:40)
      at Object.onRunnableRun (http://localhost:3002/__cypress/runner/cypress_runner.js:170265:11)
      at $Cypress.action (http://localhost:3002/__cypress/runner/cypress_runner.js:159665:28)
      at Runnable.run (http://localhost:3002/__cypress/runner/cypress_runner.js:168425:13)
      at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3002/__cypress/runner/cypress_runner.js:117650:10)
      at http://localhost:3002/__cypress/runner/cypress_runner.js:117776:12
      at next (http://localhost:3002/__cypress/runner/cypress_runner.js:117559:14)
      at http://localhost:3002/__cypress/runner/cypress_runner.js:117569:7
      at next (http://localhost:3002/__cypress/runner/cypress_runner.js:117471:14)
      at http://localhost:3002/__cypress/runner/cypress_runner.js:117537:5
      at timeslice (http://localhost:3002/__cypress/runner/cypress_runner.js:111463:27)
```

and 

```
Cannot read properties of undefined (reading 'get')
at isElement (http://localhost:3002/__cypress/runner/cypress_runner.js:164045:38) at validateType (http://localhost:3002/__cypress/runner/cypress_runner.js:163889:14) at Object.isType (http://localhost:3002/__cypress/runner/cypress_runner.js:163920:7) at $Cy.pushSubject (http://localhost:3002/__cypress/runner/cypress_runner.js:163628:22) at wrapped (http://localhost:3002/__cypress/runner/cypress_runner.js:163214:19) at <unknown> (http://localhost:3002/__cypress/runner/cypress_runner.js:162041:15) at tryCatcher (http://localhost:3002/__cypress/runner/cypress_runner.js:20941:23) at Promise._settlePromiseFromHandler (http://localhost:3002/__cypress/runner/cypress_runner.js:18876:31) at Promise._settlePromise (http://localhost:3002/__cypress/runner/cypress_runner.js:18933:18) at Promise._settlePromiseCtx (http://localhost:3002/__cypress/runner/cypress_runner.js:18970:10) at _drainQueueStep (http://localhost:3002/__cypress/runner/cypress_runner.js:15652:12) at _drainQueue (http://localhost:3002/__cypress/runner/cypress_runner.js:15641:9) at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3002/__cypress/runner/cypress_runner.js:15657:5) at Async.drainQueues (http://localhost:3002/__cypress/runner/cypress_runner.js:15527:14)
```

### Desired behavior

Tests should not occasionally crash due to outside of tests that doen't seem to originate from our code (at least looking at the stacktrace).

### Test code to reproduce

So far we haven't found a reliable way to reproduce this, locally test runs are mostly fine. Running in GitHub Actions, error rate seems to be around 50%.

### Cypress Version

12.15.0

### Node version

20.2.0 locally, v16.16.0 in GitHub Actions

### Operating System

10.0.22621.1848 locally, 22.04.2 in GitHub Actions

### Other

This issue seemed to be fixed by downgrading our vite version from 4.3.9 to 4.1.1 seemed to have fixed this issue for us.

**Comment by mike-plummer** [comment] 2023-06-23 17:54
Hi @chingucoding , sorry to hear you're having issues. Are you able to provide us with [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) of a failing run so we can try to diagnose what's going on?

**Comment by mike-plummer** [comment] 2023-06-30 13:18
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by marcelwgn** [comment] 2023-10-04 12:42
Sorry for the completely late reply. It seems our issue somehow didn't occur anymore, however I am able to reproduce this with upgrading `cypress` to any version after `13.0`. The issue only occurs on first runs, the second, third ... run work just fine. The `vite` version does not seem to matter. I would be able to provide you debug logs, however we would prefer not sharing that publicly depending on the loggers you want to see.

**Comment by muratkeremozcan** [comment] 2023-10-14 13:54
We can consistently reproduce this in our CI.
Locally, all is well. 
We are working with the Cy team towards a resolution so Vite works well in CI.

**Comment by jennifer-shehane** [comment] 2023-12-19 23:31
@muratkeremozcan This has the same stack trace in v13? Can someone provide a way to reproduce?

**Comment by jennifer-shehane** [comment] 2024-05-15 18:45
We'll have to close this issue since there's no information to reproduce this.

**Closed as not planned by jennifer-shehane** 2024-05-15 18:45 UTC

**Comment by resdust** [comment] 2025-05-13 05:18
Hi I resolved my problem by commenting out 'react' from 'externals' in `webpack.config.js`. My Cypress version is 13.6.1, and webpack version 5.99.7. If anyone still having issue can give it a try.
