### ISSUE TITLE
`cy.origin` not working with Auth0 login

### ISSUE THREAD

**Issue by wongk** [cypress-io/cypress#25551] opened 2023-01-24 15:41 UTC
### Current behavior

We are using Cypress to test a SPA (Angular) that integrates with Auth0 for login. I have added a login command to our cypress suite that is a copy & paste of the command from the real world app. The command fails when `cy.origin` is called.

![Screen Shot 2023-01-24 at 9 30 08 AM](https://user-images.githubusercontent.com/599085/214337475-b45cba5a-4764-4b02-aa10-448671b477bc.png)

Our app redirects to our Auth0 login page when "/" is visited, but Cypress does not detect this. This login command succeeds without the call to `cy.origin`, but the session is then restored for the wrong domain.

### Test code to reproduce

```js
Cypress.Commands.add("login", (username: string, password: string) => {
  const log = Cypress.log({
    displayName: "AUTH0 LOGIN",
    message: [`🔐 Authenticating | ${username}`],
    autoEnd: false,
  });
  log.snapshot("before");

  const args = { username, password };
  cy.session(
    args,
    () => {
      cy.visit("/");

      cy.origin("auth.our.domain.com", { args }, ({ username, password }) => {
        cy.get(loginPageLocators.emailInput).type(username);
        cy.get(loginPageLocators.passwordInput).type(password);
        cy.get(loginPageLocators.continueButton).click();
      });
      cy.url().should("contain", Cypress.config().baseUrl);
    },
    {
      cacheAcrossSpecs: true,
    }
  );
  cy.visit("/");

  log.snapshot("after");
  log.end();
});
```

### Cypress Version

12.3.0

### Node version

v16.15.0

### Operating System

macOS 12.5

**Comment by AtofStryker** [comment] 2023-01-25 14:48
Hi @wongk. Thank you for opening an issue. I am having some trouble reproducing the issue. Are you able to show the error or the replay on the session? I could be possible that the session is saving too early before the auth flow is fully completely, which you might be able to determine with some type of timeout before the validation 

```
  cy.origin("auth.our.domain.com", { args }, ({ username, password }) => {
        cy.get(loginPageLocators.emailInput).type(username);
        cy.get(loginPageLocators.passwordInput).type(password);
        cy.get(loginPageLocators.continueButton).click();
      });
      // does this change anything?
      cy.wait(5000)
      cy.url().should("contain", Cypress.config().baseUrl);
```

**Comment by wongk** [comment] 2023-01-25 17:59
It turns out you can't use locator variables in `cy.origin`, even if they're global. This was causing the issue, but for some reason, yesterday Cypress was not showing me the full error.

Now I am having an issue with `cy.session`. When the session is restored and the command visits "/", the Auth0 guard is still redirecting to the login page. It works fine the first time, when the session is created.

**Comment by AtofStryker** [comment] 2023-01-25 20:18
> It turns out you can't use locator variables in `cy.origin`, even if they're global. This was causing the issue, but for some reason, yesterday Cypress was not showing me the full error.

What do you mean by locator variables? Can you share a sample selector?

> Now I am having an issue with `cy.session`. When the session is restored and the command visits "/", the Auth0 guard is still redirecting to the login page. It works fine the first time, when the session is created.

would you be able to share your session code? We might be able to help you get unblocked here. My guess is there may be issues with rehydrating or saving the initial state too early.

**Comment by wongk** [comment] 2023-01-26 14:05
Both of those pieces of code are included in the Test Code I submitted on this issue.

**Comment by AtofStryker** [comment] 2023-01-26 15:06
Apologies I wasn't sure if the session code changed or not. I wasn't sure what you meant by locator variables but looking at the sample I can tell now. For those, they cannot be referenced directly like imports in the file since `cy.origin()` has it's own execution context. You might be able to `require` them though.

For issues with session, I think you are running into saving the session state before hydration has fully taken place. I created a reproduction [here](https://github.com/AtofStryker/cypress-issue-25551/blob/main/cypress/e2e/auth0-username.cy.js) that should be pretty similar to your test. When I run it I get similar behavior you describe which is my app thinking I am not logged in. My guess is the session is saving before the state is actually saved from the login round trip (setting cookies, localStorage, etc)

https://user-images.githubusercontent.com/3980464/214869055-2cfc7289-023f-4d8d-803a-961ca485a36b.mp4

If I add some [additional logic](https://github.com/AtofStryker/cypress-issue-25551/compare/verify-session-before-cache?expand=1) to verify the session naively before caching, the session looks to work as expected:

https://user-images.githubusercontent.com/3980464/214870201-c5795242-b3f9-42e0-a833-0f176d1b51c5.mp4

@wongk are you able to try something similar and see if this fixes your issue? I'd recommend something more exact than what I provided but something similar could get you over the hump.

**Comment by wongk** [comment] 2023-01-26 15:19
I started by adding a naive `cy.wait` to the session block, just to confirm your suspicion, and you are correct. Waiting does cause the session to be saved correctly. Now I just need to figure out what implicit wait I need to replace it with. Thank you for your help.

**Comment by AtofStryker** [comment] 2023-01-26 15:40
@wongk that is great to hear! I am going to close this issue then, but if you run into any other trouble pertaining to this just drop a comment here and we can re open.

**Closed as completed by AtofStryker** 2023-01-26 15:40 UTC
