### ISSUE TITLE
interception of jsonp loading doesn't work 

### ISSUE THREAD

**Issue by alexeedaria** [cypress-io/cypress#8777] opened 2020-10-07 20:49 UTC
Hi! It looks like jsonp (js instead xhr) can't be intercepted by cypress tools. 

### Current behavior
I get the error below when this row is executing 

```js
cy.wait(['@homeFetch', '@handlerOne', '@handlerTwo'])
```

`Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: search. No request ever occurred` 

By the way, I see all jsonp requests at network and at my terminal where cypress launched, but I don't see them at left browser panel.

### How I tried to fix this issue

1) changed default filtering by removing `jsx?` from `return xhr.method` at `server()` options 

```js
cy.server({
            ignore: (xhr) => {
                return xhr.method === 'GET' && /\.(coffee|html|less|s?css|svg)(\?.*)?$/.test(xhr.url)
            }
        })
```
2) set `"experimentalNetworkStubbing": true` at `cypress/support/index.js`

### Test code to reproduce
```js
describe('some_test', () => {
    it('opens some website, checks handlers', () => {
        cy.server({
            ignore: (xhr) => {
                return xhr.method === 'GET' && /\.(coffee|html|less|s?css|svg)(\?.*)?$/.test(xhr.url)
            }
        })
        cy.route2('GET', '/api/home/**').as('homeFetch') // xhr
        cy.route2('GET', '/api/handlerone/**').as('handlerOne') // js
        cy.route2('GET', '/api/handlertwo/**').as('handlerTwo') // js

        cy.visit('https://websitewithjshandler.com')
        cy.wait(['@homeFetch', '@handlerOne', '@handlerTwo'])  //here I get an error

        })
```

### Desired behavior
jsonp can by intercepted by cypress tools

### Versions

cypress: 5.3.0, macOS Catalina 10.15.4, Chrome 81.0.4044.138 (64-bit)

**Comment by jennifer-shehane** [comment] 2020-10-08 05:45
cy.server() has no effect on cy.route2(). However, the ignore option will control what requests are shown to the Command Log. 

There’s currently a bug with cy.route2() not reading the 2 arguments signature correctly https://github.com/cypress-io/cypress/issues/8729

Can you try removing the method arg or passing a third empty arg. If either of these works, I believe this is a duplicate of that issue. 

```js
// try without method arg
cy.route2(‘/api/home/**’)

// or try passing third arg
cy.route2(‘GET’, ‘/api/home/**’), {})
```

**Comment by alexeedaria** [comment] 2020-10-08 06:34
@jennifer-shehane thanks for advice! 
I tried to use `route2` without method arg and also passed the third arg as you recommended  - unfortunately, still can't intercept jsonp in both cases.

**Comment by jennifer-shehane** [comment] 2020-10-08 07:33
Can you provide an application to test this against? Create a repo with jsonp requests where the route2 is not working?

**Comment by jennifer-shehane** [comment] 2021-02-22 16:15
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-22 16:15 UTC
Labels: pkg/net-stubbing, stage: needs information

**Comment by bahmutov** [comment] 2021-02-22 17:46
@alexeedaria I have added an example of spying and stubbing JSONP requests, see https://github.com/cypress-io/cypress-example-recipes/pull/647
