### ISSUE TITLE
unexpected yielded value with .each()

### ISSUE THREAD

**Issue by cichelero** [cypress-io/cypress#6791] opened 2020-03-19 17:53 UTC
# Unexpected yielded value with each

We use Cypress extensively at and love it, but recently came to an unexpected behaviour concerning the `.each()`.

## Description

Consider:
- an element with text `Chai` inside `.connectors-each-ul>li'`
- an element with text `Lara Williams` inside `.connectors-its-ul>li'`

``` javascript
// This fails but shouldn't
 cy.get('.connectors-each-ul>li').each(() => {})
 cy.contains('Chai')

// This passes
cy.get('.connectors-each-ul>li').each(() => {})
cy.contains('Lara Williams')

// Adding an assertion passes too
cy.get('.connectors-each-ul>li').each(() => {}).should('exist')
cy.contains('Chai')
```

## Reproducible example

I've forked the kitchen sync example and added a failing test:
https://github.com/cichelero/cypress-each-bug

**Comment by vkhalikov** [comment] 2020-03-20 10:55
I have the same issue. 
```javascript
cy.contains(byDataCy('import-table-column'), 'Основной')
  .find('.ImportColumn-cell').each(($el) => {
    expect($el).to.have.css('background-color', 'rgba(30, 136, 229, 0.1)');
  });
cy.contains('Телефон');
```

<details>
  <summary>Unexpected Run Output</summary>

![bug](https://user-images.githubusercontent.com/37489000/77157227-fd523400-6ab1-11ea-9131-b51ae8ecc724.PNG)

</details>
If you add a minimum delay like:

```javascript
cy.contains(byDataCy('import-table-column'), 'Основной')
  .find('.ImportColumn-cell').each(($el) => {
    expect($el).to.have.css('background-color', 'rgba(30, 136, 229, 0.1)');
  });
cy.wait(20);
cy.contains('Телефон');
```

<details>
  <summary>Desired Run Output</summary>

![nobug](https://user-images.githubusercontent.com/37489000/77157309-22df3d80-6ab2-11ea-8ef8-0136852c67cf.PNG)

</details>

**Comment by jennifer-shehane** [comment] 2020-03-23 11:16
Duplicate of #4921

**Closed by jennifer-shehane** 2020-03-23 11:16 UTC
