### ISSUE TITLE
Cypress failed to make a connection to the Chrome DevTools Protocol: ECONNREFUSED at TCPConnectWrap.afterConnect

### ISSUE THREAD

**Issue by rnikkels** [cypress-io/cypress#16620] opened 2021-05-21 10:50 UTC
### Current behavior
I started experiencing the exact same behavior as described in https://github.com/cypress-io/cypress/issues/8986#issue-730383482
It all started when chrome updated itself to version 90 (90.0.4430.212 to be exact), only happens on chrome, chromium works (but that's still on 75), edge 90, electron and firefox 88 all work like a charm. 
So, I can start cypress normally and when running a test on chrome it logs the infamous: 
`Failed to connect to Chrome, retrying in 1 second (attempt 18/62)`
up to
`Failed to connect to Chrome, retrying in 1 second (attempt 62/62)`
And in the cypress window:

**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">53023</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:53023
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m53023[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:53023
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

    at get (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:966:15)
    at Object.throwErr [as throw] (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:984:9)
    at /Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:105:21
    at tryCatcher (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rnikkels/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

```
### Desired behavior

Well, a browser opens and executes my tests 😉 

### Test code to reproduce

Just the sample from the getting started guide in the cypress documentation gives me this behavior.
this one:
```javascript
describe('My First Test', () => {
  it('Does not do much!', () => {
    expect(true).to.equal(true)
  })
})
```

### Versions
Cypress version: 7.2.0 (update to 7.3.0 did not fix the issue) even had a repo left that was still on 6.4.0. also the issue occurs
Chrome version: 90.0.4430.212
OS: macOs BigSur 11.3.1

**Comment by jennifer-shehane** [comment] 2021-06-11 16:47
Duplicate of https://github.com/cypress-io/cypress/issues/15650

**Closed by jennifer-shehane** 2021-06-11 16:47 UTC
