### ISSUE TITLE
cy.type() failed because it targeted a disabled element when using `.type` after `.clear`

### ISSUE THREAD

**Issue by rockerest** [cypress-io/cypress#23955] opened 2022-09-23 01:46 UTC
### Current behavior

Cypress reports the following error when a input is `.clear`ed and then `.type`d into.

```
CypressError: `cy.type()` failed because it targeted a disabled element.

The element typed into was:

  > <input id="email" type="email" value="not-an-email" class="invalid" placeholder="email@example.com" required="" aria-invalid="">

Ensure the element does not have an attribute named `disabled` before typing into it.
    at <unknown> (http://localhost:9876/__cypress/runner/cypress_runner.js:137741:86)
From previous event:
    at onReady (http://localhost:9876/__cypress/runner/cypress_runner.js:137733:14)
    at runAllChecks (http://localhost:9876/__cypress/runner/cypress_runner.js:133306:14)
    at retryActionability (http://localhost:9876/__cypress/runner/cypress_runner.js:133315:16)
From previous event:
    at whenStable (http://localhost:9876/__cypress/runner/cypress_runner.js:152495:65)
    at <unknown> (http://localhost:9876/__cypress/runner/cypress_runner.js:151949:14)
From previous event:
    at $Cy.retry (http://localhost:9876/__cypress/runner/cypress_runner.js:151929:76)
    at retryActionability (http://localhost:9876/__cypress/runner/cypress_runner.js:133318:19)
    at <unknown> (http://localhost:9876/__cypress/runner/cypress_runner.js:133322:12)
From previous event:
    at Object.verify (http://localhost:9876/__cypress/runner/cypress_runner.js:133227:61)
    at handleFocused (http://localhost:9876/__cypress/runner/cypress_runner.js:137704:77)
    at $Cy.type (http://localhost:9876/__cypress/runner/cypress_runner.js:137764:12)
    at $Cy.now (http://localhost:9876/__cypress/runner/cypress_runner.js:157272:90)
    at callTypeCmd (http://localhost:9876/__cypress/runner/cypress_runner.js:137817:19)
    at clear (http://localhost:9876/__cypress/runner/cypress_runner.js:137877:14)
From previous event:
    at Context.clear (http://localhost:9876/__cypress/runner/cypress_runner.js:137880:87)
    at wrapped (http://localhost:9876/__cypress/runner/cypress_runner.js:157189:19)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/001-authentication/login.cy.js:40:7)
```

### Desired behavior

`.type( "{selectall}{backspace}" )` (and thus `.clear()`) should work correctly.

Please note that running either `.clear` OR `.type( "{selectall}{backspace}" )` both fail this way, but ADDING `"{selectall}{backspace}"` in front of more text WORKS.

Unfortunately, this means it's not possible to clear a field and then later type into it.

### Test code to reproduce

https://github.com/rockerest/cypress-ce-clear-disabled

### Cypress Version

10.8.0

### Node version

v18.9.0

### Operating System

Ubuntu 20.04.5 LTS running on Windows Subsystem for Linux 2 within Windows 11 Pro 22H2 Build 22622.590 (Experience Pack 1000.22634.1000.0)

### Other

This information is likely to be very important:

1. The input under test is within a Shadow DOM
1. Cypress' config includes `e2e: { "includeShadowDom": true }`
1. **The tests in the reproduction repo BOTH pass when I run it against Firefox 104**
    - I don't have a Chrome/Chromium install, but Electron fails.

**Comment by rockerest** [comment] 2022-09-23 01:48
The logs were too long to write directly in the issue, so I'm attaching them here.

[cypress.log](https://github.com/cypress-io/cypress/files/9630309/cypress.log)

**Comment by rockerest** [comment] 2022-09-23 02:34
It seems like any special character sequence causes this to happen.

I tried to work around not being able to `clear` by doing `.type( "{moveToStart}{del}{del}{del}" }` (with a long list of `"{del}"`s), and that fails the same way. It seems like the way that special character sequences are implemented bombs out in Shadow DOM.

**Comment by ZachJW34** [comment] 2022-09-26 16:19
Appreciate the info and the reproduction @rockerest, I was able to reproduce the issue you are seeing.

I also found https://github.com/cypress-io/cypress/issues/21433. I'm going to close this issue as being a duplicate. You can subscribe to that issue to get updates on how the issue is progressing.

**Closed as completed by ZachJW34** 2022-09-26 16:19 UTC
