### ISSUE TITLE
Error 504 Gateway timeout

### ISSUE THREAD

**Issue by mart834d** [cypress-io/cypress#6689] opened 2020-03-10 08:10 UTC
### Current behavior:

When I run my test, I need to auth with NTML. When I do so, it seems like I get authenticated, but I get an error. Error 504 Gateway timeout.
https://gyazo.com/41987db5ceba627491f4d165079d45e2

### Desired behavior:

What I want to happen is, being authenticated, and not getting this error. And being sent into the webpage which I ask for.

### Versions
Im using Cypress version 4.1.0

**Comment by jennifer-shehane** [comment] 2020-03-10 08:27
Cypress does not fully support NTML verification as noted in this issue: https://github.com/cypress-io/cypress/issues/850

Although there is a plugin provided by a third party to use NTML auth within Cypress here: https://github.com/bjowes/cypress-ntlm-auth

Duplicate of #850

**Closed by jennifer-shehane** 2020-03-10 08:27 UTC
