### ISSUE TITLE
Wrongly Rendering Angular app in Cypress Runner

### ISSUE THREAD

**Issue by OzLeviAkamai** [cypress-io/cypress#26229] opened 2023-03-27 10:33 UTC
### Current behavior

Have been working with Cypress (ts) to test the Dashboard web application written in Angular15.
When running tests in Cypress Runner, the page is loaded very wrongly,
Elements are misplaced,
Some of the are not displayed correctly,
And some even is not shown at all.
This happens also when opening the web app using Cypress-Automated-Chrome browser.
While opening the page with a regular Chrome browser, things are working fine (also in all other browsers).

Screenshots:

Original app:
![original-page1](https://user-images.githubusercontent.com/107463555/227914406-69d3e876-0ead-4e05-ae2d-b3fb18afb01e.jpg)
![original-page2](https://user-images.githubusercontent.com/107463555/227914397-29ad08aa-f817-4b0c-b44a-0baa4b9b5c59.jpg)

How it looks in Cypress:
![cypress-page1](https://user-images.githubusercontent.com/107463555/227914404-e6aa335a-e279-48f9-8293-197b9969512d.jpg)
![cypress-page2](https://user-images.githubusercontent.com/107463555/227914413-31d31f6e-4e4b-467f-b4c2-01a0c2767e73.jpg)![cypress-page3](https://user-images.githubusercontent.com/107463555/227914389-9e69b93b-8edc-4cf3-8f85-9226f42ffb60.jpg)

### Desired behavior

Be glad if the page can be rendered the same as looks in a regular browser.

### Test code to reproduce

Some tests are failing due to selecting not existing elements (not in place / not shown, while existing outside Cypress).
Most of the functionality is working although the corrupted rendering of elements.

Can share test code, but not the app code,
As the issue is while loading the app, the test code won't be helpful.

### Cypress Version

11.2.0

### Node version

16.18.0

### Operating System

macOS 13.2.1

**Comment by lmiller1990** [comment] 2023-03-28 02:10
Hi!

It looks like some stylesheets and/or JS is not loading. Is there any errors/failed requests in the network tab or console?

Another thing you can do to help debug is run with `DEBUG=cypress:* npx cypress ...` and copy+paste all the logs from the terminal here (there will be a lot).

**Comment by OzLeviAkamai** [comment] 2023-03-28 06:03
Thanks for the fast response,
So yes, there are related errors in the console:

`localhost/:1 Refused to apply style from 'http://localhost:4200/bpr-dashboard/bpr-dashboard/akamai-core/akamai-core.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

`index.js:551 [webpack-dev-server] Live Reloading enabled.`

`core.mjs:140 Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming`
`_checkThemeIsPresent @ core.mjs:140`
`Promise.then (async)`
`nativeScheduleMicroTask @ zone.js:561`
`scheduleMicroTask @ zone.js:572`
`scheduleTask @ zone.js:396`
`scheduleTask @ zone.js:221`
`scheduleMicroTask @ zone.js:241`
`scheduleResolveOrReject @ zone.js:1265`
`then @ zone.js:1461`
`bootstrapModule @ core.mjs:26300`
`46414 @ main.ts:11`
`__webpack_require__ @ bootstrap:19`
`__webpack_exec__ @ (index):292`
`(anonymous) @ (index):292`
`__webpack_require__.O @ chunk loaded:23`
`(anonymous) @ (index):292`
`webpackJsonpCallback @ jsonp chunk loading:71`
`(anonymous) @ main.js:1`
`sc.service.ts:67 SC is unavailable`

`localhost/:1 Refused to apply style from 'http://localhost:4200/bpr-dashboard/bpr-dashboard/akamai-core/akamai-core.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Additionally, attaching a full log of simple test loading the mentioned

[cypress-wrong-angular-page-load.log](https://github.com/cypress-io/cypress/files/11085910/cypress-wrong-angular-page-load.log)

**Comment by lmiller1990** [comment] 2023-03-29 00:05
@astone123 will be looking into this, but I see a few interesting things here...

- where/how do you import `akamai-core/akamai-core.css`?
-  SC is unavailable - this sounds like an issue relating to `styled-components`, which I think material-core uses.

Any chance you can reproduce this ins a minimal app (new Angular App + Material UI + akamai-core)?

**Comment by OzLeviAkamai** [comment] 2023-03-29 10:09
1. this is how akamai-core.css is used: 
`<head><link rel="stylesheet" href="bpr-dashboard/akamai-core/akamai-core.css"></head>`
inside `src/index.html`
3. SC not available isn't related to the issue.
4. App can't be loaded with those minimal dependencies.

After collaborating with our Dev team, he figured that:
When the page opens in Cypress browser, it tries to reach the akamai-core.ccs through a wrong path
* Path used in Cypress browser: `http://localhost:4200/bpr-dashboard/bpr-dashboard/akamai-core/akamai-core.css`
* Right path used in regular browser: `http://localhost:4200/bpr-dashboard/akamai-core/akamai-core.css`

Any idea how this discrepancy can happen?

BTW, if is not clear from the above details,
When modifying the `src/index.html` issue is fixed in the Cypress browser, but the issue is reproduced when loading the local website server from a regular browser.

**Comment by jordanpowell88** [comment] 2023-03-29 13:43
@OzLeviAkamai Have you tried adding the script in the `cypress/support/component-index.html` file directly? Also is there an alternative approach where you can add that stylesheet as part of your `angular.json` `styles` array?

**Comment by OzLeviAkamai** [comment] 2023-03-29 20:06
Hi @jordanpowell88 , my test is e2e, not a component.
Does `component-index.html` is relevant for e2e testing?
About the second, in check.

**Comment by jordanpowell88** [comment] 2023-03-29 21:35
@OzLeviAkamai Sorry about that, I was under the impression this was Component Testing issue

**Comment by lmiller1990** [comment] 2023-03-30 00:48
Can you share your `cypress.config.js`? I wonder if `baseUrl` is somehow getting confused.

Looking at your logs again, there is the incorrect URL with the duplicated base. Another silly question - what if you do `<head><link rel="stylesheet" href="/bpr-dashboard/akamai-core/akamai-core.css"></head>`? (note the leading `/`)

![image](https://user-images.githubusercontent.com/19196536/228699473-b2afbf80-959f-447b-9933-e81ef45089dd.png)

**Comment by OzLeviAkamai** [comment] 2023-03-30 10:06
Hi @lmiller1990 , Here is my `cypress.config.ts`

`import { defineConfig } from 'cypress'

export default defineConfig({
  projectId: 'bpr-config-qa-cypress',
  watchForFileChanges: false,
  viewportWidth: 1440,
  viewportHeight: 900,
  reporter: 'mochawesome',
  reporterOptions: {
    useInlineDiffs: true,
    embeddedScreenshots: true,
    reportDir: 'cypress/reports',
    reportFilename: '[name].html',
    overwrite: true,
    html: true,
    json: true,
  },
  e2e: {
    baseUrl: 'http://localhost:4200/bpr-dashboard',
    specPattern: 'cypress/ct/**/*.cy.{js,jsx,ts,tsx}',
    excludeSpecPattern: '',
    experimentalSessionAndOrigin: true,
    testIsolation: 'off'
  },
  env: {},
});
`

Adding the leading slash fixed the problem!
Now it works in both the regular browser and the Cypress browser.
Thanks a lot!

**Comment by lmiller1990** [comment] 2023-03-30 23:22
Great, glad you got it working. I'll close this one off.

**Closed as completed by lmiller1990** 2023-03-30 23:22 UTC
