### ISSUE TITLE
Tests randomly fails on timeout to find an element by attribute on v4.5.0

### ISSUE THREAD

**Issue by bernardodomingues-hotmart** [cypress-io/cypress#7183] opened 2020-04-29 21:28 UTC
### Current behavior:

On running our test suite in Cypress v4.5.0, we get random fails whenever the test suite runs in our CI environment (Drone - custom Node v12 docker image - running electron headless).

Examples of two independent runs failing in different tests:
![image](https://user-images.githubusercontent.com/45567521/80648516-ac394680-8a46-11ea-8bde-cd00fef58ec8.png)
![image](https://user-images.githubusercontent.com/45567521/80648568-c2df9d80-8a46-11ea-95c7-691f599be4be.png)

All tests pass when running locally either on chrome and in headless electron. Downgrading to `v4.4.1` fixes the issue in our CI.

### Desired behavior:

All tests pass independent of version and environment.

### Versions

* Cypress: `v4.5.0`
* OS: Linux Docker - Node 12 custom image
* Browser - Headless Electron

**Comment by jennifer-shehane** [comment] 2020-04-30 07:33
The 4.5.0 product release should have had zero effect on how your tests run in this case. We did not touch any of the code of the driver that would effect element visibility. 

Can you isolate any other changes that may have occured in the change? Maybe the image or any other dependencies upgraded?

Can you also follow our recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

**Comment by zetoke** [comment] 2020-04-30 20:05
@bernardodomingues-hotmart @jennifer-shehane  I have pretty the same problem!
My tests started to randomly fail with some errors like 
```
"before each" hook for "<something>":

[2020-04-30T19:07:02.949Z]      AssertionError: Timed out retrying: Expected to find element: `[data-test-id="<some_id>"]`, but never found it.

```
And the videos are pretty weird.
I have `cy.get([data-test-id]="example1").type('test')` in a spec.
So the video shows that it got example1, then tried to type `test` verryyy slow. But the input has the text.
<img width="216" alt="Screen Shot 2020-04-30 at 23 02 11" src="https://user-images.githubusercontent.com/301917/80753974-e8e46b00-8b36-11ea-98c6-7ea9c66c5e7f.png">
But it fails anyway for the whole chain showing that GET element timeout. 
<img width="220" alt="Screen Shot 2020-04-30 at 23 02 43" src="https://user-images.githubusercontent.com/301917/80753984-ec77f200-8b36-11ea-8ad9-4e5d7ddb8691.png">

And the most interesting part that it fails on CI pretty often in a docker container but it works 100% locally.

**Comment by allyraza** [comment] 2020-05-04 14:22
Hello, Also had the same problem downgrading to last version used 4.2.0 resolved the problem for me.

**Comment by RDNINO** [comment] 2020-05-09 11:38
I had the same problem. Downgrade cypress from 4.5.0 to 4.2.0. Problem is gone.

**Comment by yuriMalakhov** [comment] 2020-05-15 07:42
Same issue between `4.4.1` and `4.5.0`, `"cypress-iframe": "1.0.1"` and `"cypress-file-upload": "4.0.6"` plugins stopped working. Fail by a timeout while waiting for an element. Downgrading cypress fixes it.

**Comment by yuriMalakhov** [comment] 2020-05-20 19:21
Found out that this problem happens only when a test suite is run from `componentFolder` with `experimentalComponentTesting` set to `true`.
```
"experimentalComponentTesting": true,
"componentFolder": "src/components",
```

**Comment by stoplion** [comment] 2020-08-17 21:41
Same issue, I've changed `"pageLoadTimeout": 100000`
But the timeout error message says `30000ms`

**Comment by jennifer-shehane** [comment] 2020-08-19 09:08
@stoplion @allyraza @zetoke @bernardodomingues-hotmart Does anyone else also have `experimentalComponentTesting` set to `true`? That would be helpful to know. 

We'll really need a fully reproducible example to look into this though.

**Comment by lukeapage** [comment] 2020-08-30 06:00
If these issues are the result of cypress running slower and started happening in 4.5.0 (and only happen on ci as it seems is reported) then it could be solved by #8351

**Comment by bernardodomingues-hotmart** [comment] 2020-09-03 19:52
> @stoplion @allyraza @zetoke @bernardodomingues-hotmart Does anyone else also have `experimentalComponentTesting` set to `true`? That would be helpful to know.


@jennifer-shehane Not in my case.

**Comment by bahmutov** [comment] 2020-09-23 14:28
Is there a reproducible example? Like a public repo anywhere for this?

**Comment by jennifer-shehane** [comment] 2020-10-20 10:59
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-10-20 10:59 UTC
Labels: stage: needs information

**Comment by burzum** [comment] 2020-10-30 16:22
Please open the issue, we have the same problem. It fails randomly on CI and locally, at least for me, it fails randomly in Chrome and Firefox but works in Edge. 😮 What I've also noticed is, that each test alone works, if I run many I get random fails.

**Comment by teymurbabayev** [comment] 2020-10-30 16:54
Same here. Running tests locally is always a success. However, running them in docker on CI sometimes ends up in the `AssertionError: Timed out retrying: Expected to find element: `[data-cy=loginForm]`, but never found it.`

**Comment by jennifer-shehane** [comment] 2020-11-16 08:38
We'll be happy to reopen this issue if someone can comment providing a reproducible example. Without that we do not have a path to move forward in investigating.

**Comment by seankanderson** [comment] 2021-01-05 17:57
In my case I had to increase the defaultCommandTimeout significantly in order to solve for very poor container performance. I was getting many failures at the default 4 seconds, and consistent success at 10 seconds.

**Comment by enyangxxx** [comment] 2021-04-14 18:58
it's reproducible in a way, that the tests relying on cy.route() and cy.wait() fails randomly in CI (for me the tests are running successfully locally)

**Comment by danlynkew** [comment] 2021-05-24 16:24
Also having this issue and eagerly await a solution.

**Comment by jennifer-shehane** [comment] 2021-05-24 19:40
This issue is closed as no one has provided a way to reproduce it, so there is no solution avaialable. If you can provide a way to reproduce, we'll take a look at it.

**Comment by giancarlo88** [comment] 2021-06-21 12:27
We're also having the same issue. I think the problem is it's difficult to come up with a reproducible example to share with you as our codebase is internal and we can't easily spin up something and run it on a Drone CI pipeline (which we'd also have to spin up on our own). I'm going to see if I can try to create an example for you but it might not be entirely possible.

**Comment by waldemarennsaed** [comment] 2021-12-20 09:50
@giancarlo88 could you reproduce the issue and provide an example for us?

**Comment by darshna09** [comment] 2022-01-28 04:37
Facing the same issue. While running the specs from the local machine there is no error but on Jenkins Pipeline the specs fail with the error `AssertionError: Timed out retrying: Expected to find element.` We can provide a sample UI and specs we are using but a pipeline job to run and show might be difficult.

**Comment by waldemarennsaed** [comment] 2022-01-28 09:04
@darshna09 @giancarlo88 so what I noticed was that the issue happens always in combination with network requests (simple **fetch** or **axios**). We were able to fix some of the issues of this kind by _waiting_ for the network request to resolve, **bevore** making the assertions. What we noticed is that sometimes our CI-runners just didn't provide the performance so some requests took a long time to resolve.

So before, we had something like this:

```
// mocking network response
cy.intercept()

// asserting/finding/getting elements that are being rendered conditionally, depending on the network response
// on our pipeline, this failed sometimes
cy.get()
```

Now, we are doing:

```
// mocking network response
// naming the request
cy.intercept().as('getUserInfo')

// WAIT for the response
cy.wait('@getUserInfo')

// then asserting/finding/getting the conditionally rendered elements, based on the network response
// no fail on pipeline anymore
cy.get()
```

So take a closer look at the time your cy instance needs to run all the tests on the pipeline and compare it to your local time. If the times are **very far apart** - then you might try out what we did.

**Comment by khanh-le-otsv** [comment] 2022-10-26 10:24
Still facing this with even cypress 10 and it fails randomly so I cannot create a reproduction for this, but it fails on both local and CI

**Comment by bruno333** [comment] 2022-11-18 10:19
Still facing the same issues even on cypress 10 and it fails randomly. Should we change framework?

**Comment by pecamardelli** [comment] 2023-05-17 17:20
@jennifer-shehane still facing this random behavior in CI pipelines.
My tests always pass on my local machine but it throws random assertion errors during Github Actions. And, generally, if I re-run all jobs the tests passes. Sometimes another tests throws assertion errors.
Maybe it has something to do with Electron, since in the CI pipeline we only run headless tests.

**Comment by nagash77** [comment] 2023-05-17 17:49
@pecamardelli troubleshooting other people's Ci is very difficult because of how many potential setup issues independent of Cypress there are.  I would suggest you open a new issue with a reproducible example in a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  

Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by AnushaAshokReddy** [comment] 2023-12-02 23:19
@jennifer-shehane , is there a possibility to have call and we can show you our tests and Jenkins setup? 
we have the issue from several months, can you please help??
