### ISSUE TITLE
Run all tests button

### ISSUE THREAD

**Issue by gepardoj** [cypress-io/cypress#24256] opened 2022-10-14 11:22 UTC
### What would you like?

Button in browser mode. Before v10 there were the button to run all tests, but in v10 I don't see such button

### Why is this needed?

I have about 30 tests in different folders and I need to start all them one by one, it's too long

**Comment by nagash77** [comment] 2022-10-14 13:06
Closing as a dupe of https://github.com/cypress-io/cypress/issues/23471

**Closed as not planned by nagash77** 2022-10-14 13:06 UTC
