### ISSUE TITLE
Store screenshots in common paths between open and run modes

### ISSUE THREAD

**Issue by io-sar** [cypress-io/cypress#24090] opened 2022-10-03 11:57 UTC
### Current behavior

I try to take a screenshot and then use the screenshot from the screenshots folder for a test. However when I run cypress open it is stored here:
<img width="154" alt="Screenshot 2022-10-03 at 13 39 06" src="https://user-images.githubusercontent.com/22503601/193569642-93fd289a-460c-492c-a93b-ad0d5966247a.png">
But when I run with cypress run it is stored here:
<img width="216" alt="Screenshot 2022-10-03 at 13 46 31" src="https://user-images.githubusercontent.com/22503601/193569783-de9244ec-f626-4476-8ee6-ea7d31ecae5d.png">

P.S. From my understanding this was solved before v10 as one could define the specAll, but with the new version the specAll is deprecated, thus the regression issue

### Desired behavior

To have a common way to store screenshots

### Test code to reproduce

		cy.get('[data-testid=overlay]').within(($overlay) => {
			cy.get('svg')
				.screenshot('qrcode', { overwrite: true })
				// Location where the screenshot is saved
				// Cypress 10 regression Bug, it changes folders when it is run headless vs open
				.readFile('cypress/screenshots/user.spec.cy.js/qrcode.png', 'base64')
				.then((base64) => {
					// @TODO Fix the promise into promise cypress warning
					cy.readQRCode(base64).as('svgURL')
				})
		})

### Cypress Version

10.0.0+

### Node version

v14.17.0

### Operating System

macOS 12.5.1

**Comment by astone123** [comment] 2022-10-03 16:08
@io-sar I think that this is considered expected behavior for v10. See https://github.com/cypress-io/cypress/issues/22753. We can leave this open as a feature request

**Comment by marcrecor** [comment] 2023-05-18 08:26
Any updates with this? @astone123 

It is still happening with Cypress version 12

**Comment by GoushiRam** [comment] 2023-05-19 06:55
Adding a workaround here until this is fixed:

1. Use cy.exec and find the location of the screenshot in the cypress/screenshots/ folder:
            `cy.exec("find " + "cypress/screenshots/" + " -name " + <screenshot name> + " -type f -print"`
            the result of this will output the screenshot location to access the image. 
            
            `describe("dss", ()=> {

                     it("test", ()=> {
                                cy.visit("https://goqr.me/qr-codes/type-qr-url.html"); 
                                cy.get('img').first()
                                          .screenshot('qrcode', { overwrite: true });
                                cy.exec("find " + "cypress/screenshots/" + " -name " + "qrcode.png"+ " -type f -print").then(result => {
                                   cy.readFile(result.stdout, 'base64').should('exist')
                                })
                     })       
            })`
            
Verified with Cypress 12.5.1 both head on and headless

**Comment by emilyrohrbough** [comment] 2023-05-31 13:40
@astone123  is correct, It was an intentional v10.0.0 change, however, we recognizing this behavior is unexpected.

This is a duplicate of https://github.com/cypress-io/cypress/issues/24052#issuecomment-1470766686. I am closing as a duplicate in favor of #24052.

@GoushiRam Thank you for the workaround! I will link on #24052 for others as well.

**Closed as not planned by emilyrohrbough** 2023-05-31 13:40 UTC
Labels: existing workaround, E2E, Triaged

**Comment by pedrosvk** [comment] 2023-07-20 17:47
Problem with cy.exec is that it fails if try to use it with ${PATH} variable when passing it to read file command.
I used cy.task instead with a help from chat gpt to generate similar logic (find file and output its path).
