### ISSUE TITLE
Have a way to visit a local HTML file without prepending the `baseUrl`

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#4450] opened 2019-06-13 02:42 UTC
### Current behavior:

If I want to open a local file for test, like:
`cy.visit('file:///Users/jasonzhang/Desktop/test.html')`

I got an error:

CypressError: cy.visit() failed trying to load:
file:///Users/jasonzhang/Desktop/test.html
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: Invalid URI "file:///Users/jasonzhang/Desktop/test.html"
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

### Desired behavior:

Support it.

### Versions

3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-13 05:58
You can visit a file by specifying the relative path to `cy.visit()` - relative to the projectRoot.

```js
cy.visit('./test.html')
```

**Comment by nolimitsdude** [comment] 2019-11-04 19:54
When I run cy.visit('./cypress/screenshots/screenshot.html')
the baseurl is being added and I am not on file://
https://fleetlocate-stage.spireon.com/./cypress/screenshots/screenshot.html

I was expecting file://./cypress/screenshots/screenshot.html

**Comment by averri** [comment] 2020-03-13 12:17
What's the status of this request? A response has been given that does not answer the original question. Other users have commented about the same issue:

> When I run cy.visit('./cypress/screenshots/screenshot.html')
> the baseurl is being added and I am not on file://
> https://fleetlocate-stage.spireon.com/./cypress/screenshots/screenshot.html
> 
> I was expecting file://./cypress/screenshots/screenshot.html

**Comment by jennifer-shehane** [comment] 2020-03-16 09:34
This issue is still in the 'proposal' stage, which means no work has been done on this issue as of today, so we do not have an estimate on when this will be delivered.

**Comment by levenleven** [comment] 2020-07-14 14:07
@jennifer-shehane could you clarify if visiting file relative to project root is possible or not?
According to docs https://docs.cypress.io/api/commands/visit.html#Web-Server it should be, but it still appends base url

**Comment by jennifer-shehane** [comment] 2020-07-15 07:07
@levenleven It is possible and does work if you do not have a `baseUrl` defined.

**Comment by jennifer-shehane** [comment] 2020-07-15 07:08
Reopening as this is still an existing issue that needs addressing.

**Comment by jennifer-shehane** [comment] 2020-07-15 07:10
Sorry, this is actually a duplicate of #2918 😝 Forgive my comment spamming.

**Closed by jennifer-shehane** 2020-07-15 07:10 UTC

**Comment by wmadden** [comment] 2021-02-12 10:25
The Cypress [`visit()` documentation](https://docs.cypress.io/api/commands/visit.html#Syntax) states:

>Cypress will prefix the URL with the baseUrl configured in your network options if you’ve set one.
>
>You may also specify the relative path of an html file. The path is relative to the root
directory of the Cypress installation. Note that the file:// prefix is not needed.

However, what it means is: if `baseUrl` is set, Cypress will prepend the `baseUrl` to _any URL string that doesn't begin with `http`_. There is no way to disable this behavior if `baseUrl` is set.

When it says "you may also specify the relative path of an html file" it means: _If `baseUrl` is NOT set_, you may specify a relative path to an HTML file relative to the Cypress project root.

This documentation is extremely unclear and leads easily to frustration if you assume that Cypress would give you _some_ way to prevent having the `baseUrl` prepended to a given URL string. Considering how much the documentation stresses that using the `baseUrl` configuration option is a "best practice", you'd think that the options to `visit()` would allow you some control over what exact URL you're visiting.

It'd be an even "better" practice to _never_ set `baseUrl` in the global configuration, since you can always prepend the `baseUrl` yourself but you can't ask Cypress _not_ to prepend it once it's set.

And of course, as other users have pointed out, you can't unset the `baseUrl` while the test is running to get the `visit()` command to do what you'd expect it to do to begin with.

**Comment by bahmutov** [comment] 2021-02-12 13:40
@wmadden the way you visit a local file when `baseUrl` is set in `cypress.json` is by removing it using per-test configuration https://on.cypress.io/configuration#Test-Configuration

```js
it('visits base url', () => {
  cy.visit('/')
  cy.contains('h1', 'Kitchen Sink')
})

it('visits local file', {baseUrl: null}, () => {
  cy.visit('index.html')
  cy.contains('local file')
})
```

PS: I would put tests that use different `baseUrl` into separate spec files to avoid spec file reload when the different origin is hit.

**Comment by GrayedFox** [comment] 2022-10-14 01:52
This makes using a local file pretty tedious if using `baseUrl` since Cypress also expects a fully qualified domain name, i.e. setting the baseUrl to `./src/index.html` will prevent tests from being run.

You can work around it by doing something like this:

```ts
// cypress.config.ts
import { defineConfig } from 'cypress';

export default defineConfig({
  env: {
    indexUrl: './src/pages/index-dev.html',
  },
  e2e: {
    // due to some quirky behaviour in how Cypress handles the baseUrl environment variable
    // we use a work around, check the base-page.ts file
    baseUrl: null,
  },
});
```

Then, instead of calling `cy.visit('/')` you can pass in a specific environment variable as required. Here's an example using an abstract class that all other page objects inherit:

```ts
abstract class BasePage {
  open() {
    cy.visit(Cypress.env('indexUrl'));
    return this;
  }
}

export { BasePage };
```

A little janky but captures the essence of what baseUrl is supposed to do if working with local files and I can specify it on the command line to differentiate environments/CI/etc:

`cypress run --env indexUrl=./src/pages/index-dev.html`

**Comment by stepanroznik** [comment] 2025-04-15 15:16
I had a hard time getting this to work with `cy.visit()`, but managed to make it work by directly setting `window.location.href`. Maybe it helps your use case too:

```js
// only encode the filename but not the path
const filename = latestEmailPath.split('/').pop();
const path = latestEmailPath.replace(filename, '');
const encodedFilename = encodeURIComponent(filename);
const filepathWithEncodedFilename = `file://${path}${encodedFilename}`;

cy.window().then((win) => {
  // Navigate to the local file
  win.location.href = filepathWithEncodedFilename;

  // Continue with assertions or interactions
  cy.findByText(...);
});
