### ISSUE TITLE
Cypress Electron headless URL data:text/html,chromewebdata

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress#3566] opened 2019-02-22 15:39 UTC
### Current behavior:

Random one, this spec fails today which normally passed with:

`CypressError: Timed out retrying: expected 'data:text/html,chromewebdata' to include '/account/login'`

Then next spec in the suite then failed with:

`Error: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.`

Here's a screenshot:

![image](https://user-images.githubusercontent.com/677167/53252863-ceec0480-36b7-11e9-938c-ab8f211be7aa.png)

### Desired behavior:

This should not occur

### Steps to reproduce: (app code and test code)

I can't really help as in about 2000 specs this is the first occurance. It seems to be a new random error.

### Versions

Cypress: 3.1.5
Node 10 LTS + Electron headless 59 inside Docker inside Docker For Mac on an iMac Pro.

**Comment by jennifer-shehane** [comment] 2019-02-25 22:00
Hey @philjones88, we haven't seen this error before. Could you provide the test code you are running? What changed in between the tests passing and failing. Did you update any packages?

**Comment by philjones88** [comment] 2019-02-26 08:51
@jennifer-shehane unfortunatly it's internal product tests so can't provide the code but this test has passed many times, the error happened inside the beforeEach login code which is run for each spec. No packages were changed. Nothing has changed since and it's not been seen again.

**Comment by corentin59** [comment] 2019-04-15 19:33
I have similar problem, it's ok with Chrome, but not ok with Electron headless 59

**Comment by jennifer-shehane** [comment] 2019-04-24 16:03
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Closed** 2019-05-30 09:00 UTC
Labels: stage: needs information

**Comment by crazydude552** [comment] 2019-06-20 12:58
Hi I am Ram,

I am getting exact error, when I try to reach the payment page. which is working with other test frameworks.

Here is my scenario: I am doing a purchase in the test environment where I will redirect to the page of the payment portal to update the card details. Here the payment page is a third party page, which is similar to the any other online retailer sites.
Cypress not able to redirect and show the payment page link, and giving this error.

Can any one help me how this can be fixed.

//Ram.

**Comment by crazydude552** [comment] 2019-06-21 11:56
> Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

can you please help me in this issue i can see this issue already closed but i dont see any solution for this yet...

**Comment by jennifer-shehane** [comment] 2019-07-23 10:37
@crazydude552 	We can't offer a solution when there is not enough information to reproduce the problem. Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by janmarcin** [comment] 2019-10-17 08:11
Did anybody resolved this behavior somehow?

**Comment by rlyttle** [comment] 2022-10-29 15:42
Hi all, I can repeatedly trigger this error, but it's even stranger than it may seem: **the same laptop will experience the issue on one wifi network, but NOT on another.**

### My test scenario:
An angular webapp running on `https://localhost/route?params=123` redirects the user to `https://subdomain.localhost/route?params=123` by way of a javascript call (i.e. this is not a 302 redirect, it is initiated completely by the webapp.

### Visible result upon failure:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/19949843/198840053-35aaf3f0-d63f-4fec-bac3-f2900c7378a9.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/19949843/198840121-8f95eb9a-cfb9-448d-8353-433d7dedcd43.png">

The above is triggered by `cy.url().should('include', expectedSubdomain);` following the redirect. 

### Different results on different networks:
The tests pass as normal every time when I'm at Location A on wifi.
The tests pass as normal when I'm at Location A, tethering to my phone.

The tests FAIL every time when I'm at Location B on wifi.
The tests FAIL every time when I'm at Location B, tethering to my phone.

The tests pass as normal every time when I'm at Location C on wifi.
The tests FAIL every time when I'm at Location C, tethering to my phone.

Location B and C are in close proximity, so presumably there's no change to the network being used to tether on my mobile.
Location A and B use exactly the same router, but experience different results.
All locations have home wifi routers and broadband connections.
All tethering was done with the same phone, on the same network.

**I can literally run the tests in location A, close the laptop lid, move to location B, re-run the tests and they will fail with electron showing `'chrome-error://chromewebdata/'`**

### My Setup
NodeJS server running on localhost, with nginx being used to serve the compiled angular webapp.

```
Displaying Cypress info...

Detected 2 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 106.0.5249.119
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile: /Users/user/Library/Application Support/Cypress/cy/production/browsers/chrome-stable

2. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 105.0.2
  - Executable: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile: /Users/user/Library/Application Support/Cypress/cy/production/browsers/firefox-stable

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox
- cypress run --browser chrome

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /Users/user/Library/Application Support/cypress/cy/development
Browser Profiles: /Users/user/Library/Application Support/cypress/cy/development/browsers
Binary Caches: /Users/user/Library/Caches/Cypress

Cypress Version: 9.6.1 (stable)
System Platform: darwin (19.6.0)
System Memory: 34.4 GB free 1.34 GB
```


## Please help!
So, I have absolutely no idea what the cause could be here. Especially considering location B and C which are very close together have different results while tethering (i.e. the same network). Are there any diagnostic tools I can use to analyse this? Could DNS be playing a factor or some other network level change? Is there a way to get detailed error data out of cypress/electron?

@jennifer-shehane please advise how I can provide support on this as it's a major issue for me currently.
