### ISSUE TITLE
.intercept() never occured

### ISSUE THREAD

**Issue by slumbering** [cypress-io/cypress#9336] opened 2020-11-25 17:55 UTC
### Current behavior

The request below using .intercept() never occured while it's working with .server().route()

❌ 
```js
cy.fixture('search_results')
      .then((result) => {
        result.datas = _.fill(Array(2), this.datas)
        result.totalResults = 2
        cy.intercept( 
          'GET',
          `${SEARCH_BASEPATH_API}?${SEARCH_FACET}&page=1&size=25&fq=scope=data;collection=10.34847/e4fa4vqq;license=AFL-2.0&q=charles`,
          result,
        )
      })
      .as('getSearchResultFiltered')
```
![Capture d’écran 2020-11-25 à 18 45 53](https://user-images.githubusercontent.com/1186424/100264114-aceb7a00-2f4e-11eb-9277-d5da612720a3.png)

✅ 
```js

cy.fixture('search_results')
      .then((result) => {
        result.datas = _.fill(Array(2), this.datas)
        result.totalResults = 2
        cy.server().route( 
          'GET',
          `${SEARCH_BASEPATH_API}?${SEARCH_FACET}&page=1&size=25&fq=scope=data;collection=10.34847/e4fa4vqq;license=AFL-2.0&q=charles`,
          result,
        )
      })
      .as('getSearchResultFiltered')
```

![Capture d’écran 2020-11-25 à 18 51 28](https://user-images.githubusercontent.com/1186424/100264542-41ee7300-2f4f-11eb-8a54-bec8fd47453a.png)

### Desired behavior

.intercept() should have the same behaviour (in this particular case) than .server().route().

Thanks for your time :)

### Versions
6.0.0

**Comment by bahmutov** [comment] 2020-11-25 18:13
Please when opening an issue provide a fully reproducible example. Right now without code to run, we can run we have no idea how to go about debugging this problem. Maybe you could make a bug demo using https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept as a starting example?

**Comment by polga** [comment] 2020-11-25 18:51
@slumbering do either of the variables used to build the URL have a `*` in them? Might be the same problem as here: https://github.com/cypress-io/cypress/issues/9337

**Comment by slumbering** [comment] 2020-11-25 19:07
> Please when opening an issue provide a fully reproducible example. Right now without code to run, we can run we have no idea how to go about debugging this problem. Maybe you could make a bug demo using https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept as a starting example?

thanks @bahmutov for your quick answer. Yes I know it would be preferable to have a example to run but I was wondering maybe I'm missing something in the way I use .intercept(). I'll post a demo thought 

@polga : nop, no ```*``` in both variables but thanks anyway :)

**Comment by jennifer-shehane** [comment] 2020-11-30 06:02
Can you provide what the `search_results` fixture data looks like? But yah, the change in behavior could be dependent on some other things. We'll need a reproducible example in order to look at it. My example trying to replicate doesn't fail. 

```js
it('test cy.intercept()', () => {
  cy.fixture('example').then((example) => {
    cy.intercept(
      'GET',
      'url?search&page=1&size=25&fq=scope=data;collection=10.34847/e4fa4vqq;license=AFL-2.0&q=charles',
      example
    ).as('getUrl')
  })
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/url?search&page=1&size=25&fq=scope=data;collection=10.34847/e4fa4vqq;license=AFL-2.0&q=charles')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

<img width="557" alt="Screen Shot 2020-11-30 at 12 30 41 PM" src="https://user-images.githubusercontent.com/1271364/100574208-e255e600-3307-11eb-99f5-07dcf095e544.png">

**Comment by slumbering** [comment] 2020-12-08 08:21
@jennifer-shehane : sorry for the late answer. This is what search_results looks like : 

```json
{
  "totalResults": 14,
  "datas": [],
  "aggs": {
    "license": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "AFL-2.0",
          "doc_count": 1
        }
      ]
    },
    "year": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 10,
      "buckets": [
        {
          "key": "2018",
          "doc_count": 2
        },
        {
          "key": "2016",
          "doc_count": 1
        },
        {
          "key": "2014",
          "doc_count": 1
        },
        {
          "key": "2011",
          "doc_count": 1
        },
        {
          "key": "2010",
          "doc_count": 1
        },
        {
          "key": "2005",
          "doc_count": 1
        },
        {
          "key": "2002",
          "doc_count": 1
        },
        {
          "key": "1993",
          "doc_count": 1
        },
        {
          "key": "1981",
          "doc_count": 1
        },
        {
          "key": "1980",
          "doc_count": 1
        },
        {
          "key": "1977",
          "doc_count": 2
        },
        {
          "key": "1974",
          "doc_count": 1
        }
      ]
    },
    "type": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "http://purl.org/coar/resource_type/c_6670",
          "doc_count": 4
        },
        {
          "key": "http://purl.org/coar/resource_type/c_5ce6",
          "doc_count": 3
        },
        {
          "key": "http://purl.org/coar/resource_type/c_12ce",
          "doc_count": 2
        },
        {
          "key": "http://purl.org/coar/resource_type/c_e059",
          "doc_count": 2
        },
        {
          "key": "http://purl.org/coar/resource_type/c_18cc",
          "doc_count": 1
        },
        {
          "key": "http://purl.org/coar/resource_type/c_c94f",
          "doc_count": 1
        },
        {
          "key": "http://purl.org/coar/resource_type/c_ddb1",
          "doc_count": 1
        }
      ]
    }
  }
}
```

Many thanks

**Comment by jennifer-shehane** [comment] 2020-12-08 10:10
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-12-08 10:10 UTC
Labels: pkg/net-stubbing, stage: needs information

**Comment by csimpi** [comment] 2021-01-07 13:36
I'm having the same issue. Sometimes cypress misses catching API calls, for example exactly the same works with California, but not with Alabama:

https://i.imgur.com/mxGxyJP.png
![image](https://user-images.githubusercontent.com/6192067/103898616-7da35d80-50f5-11eb-8c13-dd1687c80a46.png)


```
    //Home Location - Alabama (assign US automatically)
    cy.get('#country').focus().clear().type('Alabama').should('have.value', 'Alabama');
    //Check API response
    cy.intercept({
      path: '/api/locations/find?query=Alabama'
    }).as('CountryLocationAutocompleteResponse');
    cy.wait('@CountryLocationAutocompleteResponse')
      .its('response.statusCode').should('eq', 200);
```

Obviously, I can't put this public so can't provide a reproducible case

**Comment by jennifer-shehane** [comment] 2021-01-08 08:51
@csimpi You'll want to define your `cy.intercept()` before you type into the input. It's essentially a listener - set up before the action happens, then you can define the `wait` to not continue until the request completes. 

```js
    cy.intercept({
      path: '/api/locations/find?query=Alabama'
    }).as('CountryLocationAutocompleteResponse');

    //Home Location - Alabama (assign US automatically)
    cy.get('#country').focus().clear().type('Alabama').should('have.value', 'Alabama');
    
    //Check API response
    cy.wait('@CountryLocationAutocompleteResponse')
      .its('response.statusCode').should('eq', 200);
```

**Comment by csimpi** [comment] 2021-01-08 16:29
@jennifer-shehane 
Thank you! Strange, because I remember when I tried the first time, I treated it like a listener (so put it before the request) but didn't work, then I moved after the request and it worked but only when the tester Chrome preview was in the foreground and failed when it was in the background. 

Now, it works. I don't know what I missed last time. Probably I put the `wait` part before the request too :) 
Thx again. I love it so far, makes the frontend testing less painful <3 I love that it's super communicative and tells me what's the exact problem. For example, when an element is hidden/covered by another element it throws an error. That's my favorite function, it forecasted an error on production right after the first use of my first tester script.

**Comment by csimpi** [comment] 2021-01-09 16:26
@jennifer-shehane I've found some inconsistency with intercept. I don't know why but sometimes I need to setup only one intercept and re-use wait a couple of times for the same request pattern. Sometimes works, sometimes doesn't. If it a listener it should be declared only one time and catch the matching requests/responses with `wait`. What do you think, why this is happening? Or how it should work in real? The documentation is not too detailed about this.

**Comment by jennifer-shehane** [comment] 2021-01-11 05:11
@csimpi I'm not sure exactly without an example. 

There is some unexpected behavior when overwriting intercept which is documented here: https://github.com/cypress-io/cypress/issues/9302
