### ISSUE TITLE
Spec List should persist state

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#22296] opened 2022-06-14 02:49 UTC
### What would you like?

When you open the Cypress app, the first page shows all your specs. You can filter and collapse the table. When you click a spec, you go to the run page. If you then return to the original page, your filtering is reset.

I'd like to keep the filtering, and also have a "reset" button to open all the collapsed rows, and remove the filter. 

This is based on user feedback: https://github.com/cypress-io/cypress/issues/22152#issuecomment-1152895415

### Why is this needed?

No need to redo your filters over and over.

**Comment by lmiller1990** [comment] 2022-06-14 02:51
Example demonstrating the current behaviour: 

https://user-images.githubusercontent.com/19196536/173483207-6ad26ed3-97db-4943-aa88-9c2c37f44079.mov

**Comment by mjhenkes** [comment] 2022-06-14 18:02
Closing as a duplicate of #21837

**Closed by mjhenkes** 2022-06-14 18:02 UTC
Labels: type: enhancement, type: user experience
