### ISSUE TITLE
Cypress is not capturing app XHR its only capturing 3rd party XHR calls

### ISSUE THREAD

**Issue by arun290636** [cypress-io/cypress#1619] opened 2018-04-19 16:18 UTC
### Current behavior: 
Request(XHR) going to 3rd party is captured
![image](https://user-images.githubusercontent.com/1212793/39004496-5fff701c-43f5-11e8-8a9a-a9ac58d603d7.png)
Request going to our own api is not captured:
![image](https://user-images.githubusercontent.com/1212793/39004534-7e72adac-43f5-11e8-99f7-289b9f64b8e2.png)

### Desired behavior:
Every XHR request on page load should be captured.

### Steps to reproduce:

```js
cy.visit('/');
          cy.get('select#users').select('ShootCoordinator')
          cy.get('input').click();
          cy.wait(2000)
          cy.get('.filter-callout.medium-text').contains('Filters')
          cy.visit('/asosstudio/');
```

### Versions  

Latest version of Cypress, latest version of Chrome and on Windows 7 OS

**Comment by arun290636** [comment] 2018-04-19 18:17
@brian-mann please help on above

**Comment by ValerieThoma** [comment] 2018-04-19 18:18
@arun290636  Can you provide a minimal reproducible example?

**Comment by jennifer-shehane** [comment] 2018-04-20 00:01
Have you tried setting up a `cy.route()` to listen for the request and `cy.wait()` to ensure it is captured?

Also, am I correct in seeing that you are visiting `localhost:3000` and also doing a `POST` request to a `localhost:3000` endpoint? 

Sorry, it is a bit difficult as @ValerieThoma said to track down the issue just from screenshots. If there is any way you could get us closer to reproducing it ourselves, that would help.

**Comment by arun290636** [comment] 2018-04-20 08:48
@jennifer-shehane  you are right i am visiting localhost:3000 and making request to local host.
Page URL - http://localhost:3000/abc/

XHR calls
http://localhost:3000/abc/api/User/GetUserInformation
Request Method:GET
https://dam-dev-web.xyz.com/abc/Tasks?group=shoots
Request Method:OPTIONS
http://localhost:3000/abc/api/TaskData/GetTasks/Shoot
Request Method:POST

**Comment by arun290636** [comment] 2018-04-20 12:51
@jennifer-shehane I have tried in our test environment as well . Its not capturing XHR requests.

**Comment by arun290636** [comment] 2018-04-20 13:01
@jennifer-shehane @ValerieThoma let me know if you want me to share my screen etc.

**Comment by jennifer-shehane** [comment] 2018-04-20 18:44
Ok, I see the code you posted in your example. You are writing: 
`cy.wait('@testing', { timeout: 600000 }`.

Where did you originally define the `testing` [alias](https://docs.cypress.io/api/commands/as.html? I'm not seeing that included in the code. Since that is the xhr you are concerned about, I'd like to see the route where you defined the `testing` alias. Thanks.

**Comment by darina-techery** [comment] 2018-04-23 14:06
I guess I know the answer. For some reason Cypress is not intercepting requests, when application uses Fetch API instead of XHR API. 
Our application under test contains a lib which checks if browser knows about 'fetch' function. If not, it fallbacks to XHR-based requests. So, our solution was to "disable" fetch feature to cause this fallback. Our tests do the following:

```Cypress.on('window:before:load', (win) => {
    win.fetch = null;
});```

But in your case it might not work. Check with your developers if they use Fetch API, and if yes, ask if they can provide fallback to XHR API.

I can't swear that your problem is of the same origin, but it looks exactly like ours to me.

**Comment by ahmehri** [comment] 2018-04-25 09:52
Does this means that cypress doesn't support Fetch API?

**Comment by darina-techery** [comment] 2018-04-25 10:53
It doesn't. There is an open issue for that: https://github.com/cypress-io/cypress/issues/687

**Comment by jennifer-shehane** [comment] 2019-04-25 06:26
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 06:26 UTC
Labels: stage: needs information, type: unexpected behavior

**Comment by manphannvg** [comment] 2019-05-22 04:16
hi @jennifer-shehane,

I have similar issue when Cypress cannot catch 3rd party XHR call. Can you please help?

![image](https://user-images.githubusercontent.com/40622958/58147053-fafd2e80-7c82-11e9-82a0-0e24cf4f9d81.png)

Thanks

**Comment by jennifer-shehane** [comment] 2019-05-22 06:43
@manphannvg Since there is content `?s=`&t...` after the end of your glob pattern, you'll need to add another `*` to make sure it matches correctly. Can you try?

```
**/properties/searchmetadata*
```

**Comment by manphannvg** [comment] 2019-05-22 06:58
@jennifer-shehane, Thanks for quick response. Unfortunately, it still does not work 

![image](https://user-images.githubusercontent.com/40622958/58153598-a5804c00-7c99-11e9-98b0-ee11d3019074.png)

**Comment by jennifer-shehane** [comment] 2019-06-24 09:35
@manphannvg Can you use the `Cypress.minimatch` method to confirm the glob is matching the entire url. https://on.cypress.io/minimatch#Examples

**Comment by manphannvg** [comment] 2019-06-27 08:07
> @manphannvg Can you use the `Cypress.minimatch` method to confirm the glob is matching the entire url. https://on.cypress.io/minimatch#Examples

It's a true. But it cannot be catched @jennifer-shehane 
![image](https://user-images.githubusercontent.com/40622958/60248611-35df2b80-98ed-11e9-850c-f7a3114f32df.png)

**Comment by iamdaniyalz** [comment] 2020-02-09 10:17
Hi, did you get a solution to this? I'm facing the same problem, cypress is not catching the xhr requests in Left Hand Pane (LHP) but they are there in the network tab of dev tools.
The problem is, i can see the requests in LHP when i run the code in one single describe, it() block but using multiple blocks, i don't see the requests.

**Comment by jennifer-shehane** [comment] 2020-05-05 09:04
Note that routes using the Fetch API will not be intercepted using cy.route: https://on.cypress.io/route currently. https://github.com/cypress-io/cypress/issues/95
