### ISSUE TITLE
Auto scroll is turned off sometimes 

### ISSUE THREAD

**Issue by bukharov** [cypress-io/cypress#16098] opened 2021-04-20 16:50 UTC
### Current behavior
As you can see in the video below, auto scroll turns off at 27s mark and then stays off for the rest of the spec: 

https://user-images.githubusercontent.com/49371/115434222-74d32500-a1d6-11eb-9f63-6b0037c46cff.mp4

It's not consistent, it happened locally more often than in CI, but the recording above is from CI.

### Desired behavior

I'd like it to stay on, as there's no way to see the commands without it.

### Versions

Cypress `7.1.0`

**Comment by jennifer-shehane** [comment] 2021-04-21 18:11
That's pretty weird. I don't see where this code would have been updated at all recently, so I don't think this would be a regression. Also it seems like in the code that this should only toggle if you click on it? 

Providing a way to reproduce this reliably would be helpful, without that this will be pretty difficult to track down.

**Comment by bukharov** [comment] 2021-04-21 19:22
It's in CI so no one clicked on it :trollface:

**Comment by jpourdanis** [comment] 2022-01-28 12:19
I have seen the same behavior on our CI also and we use cypress 8.7.0 on Gitlab. It's not happening to all tests runs but this is an example and I cannot reproduce it locally :


https://user-images.githubusercontent.com/15849558/151545305-a6a41337-70ff-468a-b8e5-fa021ebc6769.mov

This is the reason that we add this plugin to see what's going on when a test fails: https://github.com/bahmutov/cypress-failed-log

Can we ensure somehow this scrollbar tries always to go to the bottom? Is there any test for that?

**Comment by BlueWinds** [comment] 2022-02-17 17:14
We do indeed have extensive tests around the scrolling behavior, and as noted, this isn't something we've seen in cypress' own tests. Which isn't to say that your issue isn't real, just that without a publicly visible case demonstrating it, we're pretty limited in our ability to figure out what's going on.

If you can reproduce the behavior in a public repo, I'm definitely willing to spend some time looking into it.

**Comment by bukharov** [comment] 2022-03-31 12:46
I agree with @dlabrecque-uzinakod. How useful is this feature? Perhaps the fix to this issue is to remove the feature completely?

**Comment by JessicaSachs** [comment] 2022-04-04 20:23
The reason we have this feature is for users reviewing video artifacts in CI to debug what happened in a failing test. It makes a lot of sense for those workflows. I have a 100% reproduction with this repository https://github.com/JessicaSachs/rune-scrape

Video here: https://www.loom.com/share/61ff11e54ae6457c93b8d2191aa31b65

**Comment by bukharov** [comment] 2022-04-05 00:33
@JessicaSachs I understand, but what would be the use case for disabling auto scroll? I suppose my comment is a bit ambiguous. The suggestion was to remove the toggle and keep in always on.

**Comment by marktnoonan** [comment] 2022-04-28 20:53
A starting point for the implementation of this might be, when in headless mode, to not do [this scroll handling](https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/runnables/runnables.tsx#L139), since any scrollbar movement was definitely not caused by the user wanting to pause autoscrolling to look at something - they can't see the browser.

**Comment by astone123** [comment] 2022-07-14 20:45
Marking https://github.com/cypress-io/cypress/issues/22772 as a duplicate of this issue. Seems related to auto-scroll stopping mid-spec

**Comment by steve78GA** [comment] 2022-07-22 06:28
After upgrading to v10 we are now encountering this issue as well. It happens both in the runner and in CI which makes it particularly irritating.

https://user-images.githubusercontent.com/79444261/180376746-43547634-e463-46d0-bd56-b98bde2a1974.mov

.

**Comment by marktnoonan** [comment] 2022-08-03 14:24
Hi @ngandymovpr as mentioned in [in my comment yesterday](https://github.com/cypress-io/cypress/issues/16098#issuecomment-1202570914), there are some [builds that you can install](https://github.com/cypress-io/cypress/pull/23053#commitcomment-80006665) that attempt to fix this problem. Installation instructions for mac and linux are there, let me know if you need Windows and I'll make a fresh build.

I cannot actually reproduce this issue with the examples provided so far, so I need somebody who experiences it to validate that it is fixed in those builds (at least, for `run` mode). Would you be up for trying that? Or, can you provide a reproducible example repo I could try this preview build against?
 
I'm reluctant to merge a PR that we haven't confirmed fixes the problem. But I want to fix it because I agree it's a problem.

**Comment by DannyBunny** [comment] 2022-08-03 22:37
@marktnoonan, I have this problem on Windows. Please make a Windows build.
I can validate it pretty quickly, it happens to me every day in CI.
I don't have a reproducible example myself. It happens randomly.

**Comment by Tom5om** [comment] 2022-08-04 01:36
Hi @marktnoonan we were experiencing this issue in our team as well and raised it with cypress support as well.

I have tried your custom build and so far in my pipelines it seems to **HAVE FIXED** the problem.

I say it seems to have fixed it, because it wasn't always a problem so I will hopefully be able to confirm that it definitely fixed it later today.

Thanks for picking this up!

**Comment by marktnoonan** [comment] 2022-08-04 13:41
Thanks @Tom5om that's promising!

@DannyBunny here is the Windows version for you to check: https://github.com/cypress-io/cypress/pull/23053#commitcomment-80290518

**Comment by DannyBunny** [comment] 2022-08-05 15:15
@marktnoonan, unable to run. Getting an error:
`Timed out waiting for the browser to connect. Retrying...
EPERM: operation not permitted, unlink 'C:\Users\danny.z\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-23320\CypressCache\Cache_Data\data_1'
Error: EPERM: operation not permitted, unlink 'C:\Users\danny.z\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-23320\CypressCache\Cache_Data\data_1'`

**Comment by marktnoonan** [comment] 2022-08-05 21:37
Thanks @DannyBunny, and shoot it looks like I started my branch during the hot second that `develop` wasn't working on Windows, branch is updated and the Windows build should appear in the comments for this commit: https://github.com/cypress-io/cypress/pull/23053/commits/a28d6f80e953126cd3144dc756a4df26633227e0

Will check back on Monday.

**Comment by cposada23** [comment] 2022-08-16 13:59
Any news about this, It's happening to me even when I run the test in my local machine. The auto scroll stops working after some time. This is really annoying when it happens on CI because it leaves me with NO LOGS to see what cypress is doing. THis makes IMPOSIBLE to review the failures.... I have cypress version 10.4.0

**Comment by marktnoonan** [comment] 2022-08-16 14:06
@cposada23 since you can reproduce, can you verify one of these builds fixes the problem (using `cypress run`, no change expected in `cypress open`)

I've tried a bunch to reproduce it and had several others trying as well but we have not at any luck.

Linux: `npm install https://cdn.cypress.io/beta/npm/10.4.0/linux-x64/marktnoonan/16098-a28d6f80e953126cd3144dc756a4df26633227e0/cypress.tgz`

Windows: `npm install https://cdn.cypress.io/beta/npm/10.4.0/win32-x64/marktnoonan/16098-a28d6f80e953126cd3144dc756a4df26633227e0/cypress.tgz`

Mac: `npm install https://cdn.cypress.io/beta/npm/10.4.0/darwin-x64/marktnoonan/16098-2eb2f82b23cc0fc086254e64a61cd91ea04488d7/cypress.tgz`

Mac (ARM): `npm install https://cdn.cypress.io/beta/npm/10.4.0/darwin-arm64/marktnoonan/16098-2eb2f82b23cc0fc086254e64a61cd91ea04488d7/cypress.tgz`

@Tom5om are you able to confirm if the problem was truly fixed for you? @ngandymovpr would you be able to try one of these builds?

**Comment by Tom5om** [comment] 2022-08-16 22:32
Yes @marktnoonan I have implemented this build in my pipelines and have not seen the issue since

**Comment by leonard2901** [comment] 2022-08-17 12:40
I had the same issue for one of my specs with Cypress 10.3.0. There it occurred in about 50% of the times. Since I installed your Build, I have done 15 more runs and have not seen this behavior again.

**Comment by kevingorry** [comment] 2022-08-18 13:28
@marktnoonan can we get it merged, it's impacting us too. Thank you

**Comment by marktnoonan** [comment] 2022-08-18 13:56
Thanks @leonard2901 and @Tom5om, that seems like plenty validation that this was the issue.

@kevingorry this thread should automatically update when the PR is merged, it will need a test as well, which @viniciuspietscher has offered to pick up to get the PR over the finish line. This will likely make it into the next Cypress release at the end of the month.

**Comment by romankhomitskyi** [comment] 2022-08-31 06:11
@marktnoonan hello, any updates on this? This is really critical issue

**Comment by cposada23** [comment] 2022-09-08 17:55
I update to cypress version 10.7.0.... Still happening.... am I really the only one that's getting this annoying behavior ?  It's really impossible to see what is happening on the video when I run the test on CI. Guess we just need to change the testing framework

**Comment by romankhomitskyi** [comment] 2022-09-08 18:04
> 

😄😄  yeah

**Comment by marktnoonan** [comment] 2022-09-10 02:17
Hi folks, this just missed the cut for 10.7.0 due to a conflict with some of the changes made to bring Studio back. PR is updated now, hoping to merge in the next few days.

**Closed** 2022-09-13 13:17 UTC
Labels: type: unexpected behavior, pkg/reporter, stage: internal
