### ISSUE TITLE
Unable to login with browser controlled by Cypress

### ISSUE THREAD

**Issue by katQA** [cypress-io/cypress#29010] opened 2024-02-26 13:12 UTC
### Current behavior

I enter password and username click on login button and same page is reloaded. I don't get an error I'm just on the password page. In reality I cannot reproduce the issue neither on Chrome nor on Firefox. I can replicate the issue only in browser which is beign controlled by Cypress.

### Desired behavior

To be able to login as in other browsers.

### Test code to reproduce
 login button selector: 
```js
logInBtn: "[data-testid='login-button']",`
   ....

    register.loginBtn.scrollIntoView().should("exist");
    register.clickLogInBtn();
});
```

### Cypress Version

 "cypress": "^13.6.1"

### Node version

Node.js v18.15.0.

### Operating System

macOS 14.2.1

### Other

I noticed that one of the requests on login has status code: 204 but in other browsers it serves 200.

**Comment by fubha** [comment] 2024-02-27 14:48
I'm facing the same issue.

**Comment by jennifer-shehane** [comment] 2024-02-27 15:42
Maybe a duplicate of https://github.com/cypress-io/cypress/issues/28798 We're unsure what's causing these types of issues.

**Closed as not planned by jennifer-shehane** 2024-02-27 15:42 UTC
Labels: type: duplicate
