### ISSUE TITLE
Video error in dashboard when "videoUploadOnPasses": false given

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#778] opened 2017-10-20 01:10 UTC
- Operating System: Linux Debian - 8.8
- Cypress Version: 1.0.2
- Browser Version: Electron 53.0.2785.143
- CI service: Buildkite

### Is this a Feature or Bug?

Bug

### Current behavior:

When test passes and option `videoUploadOnPasses` is `false`, cypress dashboard in runs still displays that video as available but it can't load it like here:

<img width="900" alt="screen shot 2017-10-20 at 9 46 07 am" src="https://user-images.githubusercontent.com/829242/31800839-725176a6-b58f-11e7-97f7-3198518be0ac.png">

### Desired behavior:

When option `videoUploadOnPasses` is `false` video should not appear in video tab.

**Comment by jennifer-shehane** [comment] 2018-12-19 18:10
Duplicate of https://github.com/cypress-io/cypress/issues/2939

**Closed by jennifer-shehane** 2018-12-19 18:10 UTC
Labels: type: duplicate
