### ISSUE TITLE
Stdout is set to null which craches the cli on open

### ISSUE THREAD

**Issue by doshisid** [cypress-io/cypress#718] opened 2017-10-10 11:49 UTC
*Details*

- Operating System: Ubuntu 16.04
- Cypress Version: 1.0.0
- Browser Version: 60

### Is this a Feature or Bug?
Bug

### Current behavior:
When starting cypress with `cypress open`, it crashes the cli with the following error message:-
![image](https://user-images.githubusercontent.com/23718874/31384686-944cd7a0-addd-11e7-90bb-7112f44a7bd9.png)

It is because `stdout` and `stderr`  are null for some reason [here](https://github.com/cypress-io/cypress/blob/develop/cli/lib/exec/spawn.js#L30-L31).

As mentioned in this [answer](https://stackoverflow.com/a/29024376/7213112) it is because we are setting `stdio` to `inherit` [here](https://github.com/cypress-io/cypress/blob/develop/cli/lib/exec/open.js#L37)
After removing that line, cli works as expected. It still passes the output from the desktop app to the terminal.

### Desired behavior:
Cli runs without crashing

### How to reproduce:
Run cypress open on Linux ubuntu 16.04

> Note: It still opens the desktop app and runs but the cli stops with exit code 1.

**Comment by brian-mann** [comment] 2017-10-10 12:01
Duplicate of #717. We're doing some funkiness there due to Windows. Windows *literally* refuses to run with a normal set of stdio configuration. 

We have a branch running in CI now and when it passes we'll release `1.0.1`.

https://github.com/cypress-io/cypress/tree/issue-717

**Closed by brian-mann** 2017-10-10 12:01 UTC
