### ISSUE TITLE
Upgrading to 3.6.1 causes HTTP 431 errors on POST requests

### ISSUE THREAD

**Issue by SRocha147** [cypress-io/cypress#5751] opened 2019-11-20 12:53 UTC
**Current behavior:**

After upgrading from Cypress 3.4.1 to 3.6.1, we've been getting an HTTP 431 error. Here are the headers in my failing POST request:

```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
authorization: <...>
Content-Length: 171
content-type: application/json
Cookie: ai_user=y/J6x|2019-11-19T19:49:43.565Z; ai_session=DbTFk|1574192984304|1574192998997.615
Host: localhost:444
Origin: http://localhost:444
Proxy-Connection: keep-alive
Referer: http://localhost:444/test
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
X-Cypress-Delay: 0
X-Cypress-Headers: %7B%7D
X-Cypress-Id: xhr77
X-Cypress-Matched: **/MyClass/**
X-Cypress-Response: %7B%7D
X-Cypress-Status: 200
```

**Desired behavior**:

Should not fail.

**Steps to reproduce: (app code and test code)**:

Make a POST request with the above header in Cypress.

```
    cy.server();
    cy.route({
      method: 'POST',
      url: '**/MyClass/**',
      status: 200,
      response: {},
    });
```

**Versions**:

Chrome 78
Cypress 3.6.1

We run the tests via `npm run test:cypress`.

For now we have reverted to 3.4.0 until this issue is resolved in later versions. I saw that in 3.6.0, Cypress fixed an issue related to the 431 issue:

> We fixed a regression in 3.5.0 where the maximum size of an HTTP header or body in a stubbed cy.route() was limited to 8kb causing requests to fail with a 431 HTTP error. Fixes #5431.

It's possible this code was revisited and caused another regression in 3.6.1

> Cypress now sends the expected headers or request body in a cy.visit() to an HTTPS URL using the default port, 443. Fixes #5367

**Comment by flotwig** [comment] 2019-11-20 22:20
@SRocha147 thanks for reporting this, I believe this is a duplicate of #5561, so closing this for now. If this is a mistake please reopen.

**Closed** 2019-11-21 15:24 UTC
Labels: type: duplicate
