### ISSUE TITLE
Visibility errors when window is hidden during headed mode test execution

### ISSUE THREAD

**Issue by agualis** [cypress-io/cypress#4039] opened 2019-04-26 16:51 UTC
### Current behavior:

Cypress tests fail when the browser is not focused in "run headed" mode. 

This kind of problem is always related with components with animations and overlays like modals, popups or sticky headers. (this example shows the problem with sweet alert library). 

### Desired behavior:

The tests should be deterministic no matter the execution mode and the browser focus state. 

### Steps to reproduce: (app code and test code)

Repository to reproduce the problem (check readme to follow instructions)
https://github.com/agualis/flaky-swal-cypress

Video showing the error:  
https://github.com/agualis/flaky-swal-cypress/blob/master/flaky-cypress-test.mov

### Versions

Cypress:    3.2.0                                                                              │
Browser:    Chrome 73 
OS: macOS Mojave

**Comment by Bkucera** [comment] 2019-04-26 17:33
Hi @agualis, I believe this will be fixed in #2982

**Closed** 2019-06-11 15:06 UTC
Labels: stage: needs review, topic window focus

**Comment by jennifer-shehane** [comment] 2019-06-19 08:04
I'm actually unable to reproduce this from the repo provided as is so I can't confirm if 3.3.2 release fixes this. @Bkucera did you reproduce?

**Comment by johnknoop** [comment] 2019-09-27 13:07
I still have problems of this nature in 3.4.1.

**Comment by Bkucera** [comment] 2019-09-27 14:50
@johnknoop please provide a reproducible test example, either in this issue or a new one. Thanks

**Comment by johnknoop** [comment] 2019-09-27 14:53
> @johnknoop please provide a reproducible test example, either in this issue or a new one. Thanks!

That might take me some time, since I don't want to share the codebase as-is. I understand you need something reproducable to work with though. I'll try to get around to it!

**Comment by Bkucera** [comment] 2019-09-27 14:55
@johnknoop feel free to point us to a public-facing url if you need. We don't need access to anything but the test code.

**Comment by johnknoop** [comment] 2019-09-27 20:18
I think the problem may not be with Cypress, but with the fact that my application should do certain things when an input field has focus. When the Cypress window doesn't have focus, the browser doesn't recognize that the field is focused, and thus the application behaves differently.

It would be nice if cy.get('#myElement').focus() would trigger the field to be focused, but I can see how that might be out of your control.

**Comment by Bkucera** [comment] 2019-09-27 21:30
@johnknoop we should be properly "tricking" your app into thinking the browser is focused. We force document.hasFocus() to `true` and even polyfill focus events when browser is not in focus- even when your appcode calls input.focus(). It's possible there are still edge cases, so reproducible examples are key here.

**Comment by johnknoop** [comment] 2019-10-12 22:00
@Bkucera 

I've just spent a few hours trying to create a simple example that reproduces the issue, but to no success.

It reproduces 100% of the times in my real test though.

I can record you guys a video and send, but I'm not sure if you would get any good information from that.

Is there some instrumentation log or something that I can enable?

**Comment by Bkucera** [comment] 2019-10-15 14:50
@johnknoop usually we can't get much from video, and we don't have very robust debug logs in the driver. Usually these types of issues are related to some lib or ui framework so that type of information helps

**Comment by johnknoop** [comment] 2019-10-15 17:12
@Bkucera 

For what it's worth.. it's an AngularJS 1.6 app. The app is quite interactive, so a lot of stuff is displayed/hidden based on mouse interaction. And 98% (ish) of these seem to work when the Cypress window is hidden behind another window. There's only very few cases that don't work.

The one that I tried to reproduce in a codepen.io sample, but failed, uses elements that are repeated, and within each element is an input field. When that input field has focus, a property on the angular scope is set to true, which makes a fly-out visible (it's not part of the DOM when it's hidden). The thing that fails is that the input field never gets focused if the cypress window lacks focus. This much I have gathered using logging.

**Comment by mankybansal** [comment] 2019-10-16 06:59
I have noticed this in our Next.js app as well. All the tests pass when the window is in focus and I'm looking at it. The minute I switch workspaces on the mac (even after a few tests have passed), the next test fails.

**Comment by jennifer-shehane** [comment] 2019-12-24 09:23
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
