### ISSUE TITLE
Scroll Bar not scrolling across the logs

### ISSUE THREAD

**Issue by vambcool** [cypress-io/cypress#17938] opened 2021-08-30 16:28 UTC
### Current behavior

When running tests, we are seeing issue with the screen shot not capturing the logs displayed on the left panel. The scroll is not scrolling across the logs.

In the below screen shot we have tests failed and we are unable to see the logs on left panel to know what happened before the test step failed 

![CypressLogsNotScrollingDown](https://user-images.githubusercontent.com/30079509/131372108-69c51d79-c2d3-4905-a04d-0575be39f3c7.png)

### Test code to reproduce

Not Applicable

### Cypress Version

8.1.0

**Comment by jennifer-shehane** [comment] 2021-08-30 20:33
I see that the spec file ran for 20 minutes. Is this a typical runtime for your specfile? Because we'd recommend reducing the specfile so that it runs in ~1 min. My complete guess is that this is in some way related to the rendering of the amount of items that would be run in a specfile and Cypress not being optimized to render that many logs in a scrollable list. I'd have to test this theory though. 

Looks like a duplicate of this issue though, where autoscroll is turned off (and they didn't not have a long specfile): https://github.com/cypress-io/cypress/issues/16098

**Closed by jennifer-shehane** 2021-08-30 20:33 UTC

**Comment by camiloesub** [comment] 2022-10-28 14:11
I'm seeing this in the latest version of cypress
