### ISSUE TITLE
Heap OOM error does not fail subsequent specs 

### ISSUE THREAD

**Issue by JoA-MoS** [cypress-io/cypress#5869] opened 2019-12-04 06:10 UTC
I have two different repos using typescript both fail on the 23rd spec with an OOM error. In 3.4.1 the spec summary returns all specs after the OOM error as failed in 3.6.x and 3.7.0 report all specs passed even though specs after the 23rd spec should have failed.

@jennifer-shehane - I was able to repro this in a demo repo (https://github.com/JoA-MoS/nx-example/tree/cypress-js-heap-oom).  I think the issue is that once the TypeScript Preprocessor hits the out of memory it no longer processes the tests written in typescript.  I believe 3.4.1 failed after finishing all the tests where 3.6.1 states all specs passed.

Here are the results of the demo repo

![image](https://user-images.githubusercontent.com/5566979/69746345-ea79b500-10f8-11ea-8f84-b4006130d5e9.png)

specs 23 and 24 contain the following

```TypeScript
describe('demo-ui', () => {
  beforeEach(() => cy.visit('/'));

  it('I SHOULD NOT PASS', () => {
    // Function helper example, see `../support/app.po.ts` file
    cy.contains('THIS TEXT DOES NOT EXITS');
    expect(false).to.be.true;
  });
});
```

Spec 23 had the following logged to console.

```
 Running:  23.spec.ts                                                                    (24 of 25)
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF679F407BF uv_open_osfhandle+479
 2: 00007FF678CB9786 node::Abort+22
 3: 00007FF678CB9DA3 node::Abort+1587
 4: 00007FF6772864F8 v8::RetainedObjectInfo::GetElementCount+808
 5: 00007FF677286493 v8::RetainedObjectInfo::GetElementCount+707
 6: 00007FF6772FF133 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+255075
 7: 00007FF6772FE05B std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+250763
 8: 00007FF6772FB6BF std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+240111
 9: 00007FF677305409 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+280377
10: 00007FF677305A8E std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+282046
11: 00007FF6776CF067 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+4252567
12: 00007FF6778B20A9 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+6231001
13: 00007FF677C0AFAF v8::WasmStreaming::Unpack+2677935


  0 passing (6ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     23.spec.ts                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.
```

Running the demo repo:
```
git clone https://github.com/JoA-MoS/nx-example.git
git checkout cypress-js-heap-oom
npm install
ng e2e demo-ui-e2e --headless --prod
```

Related to: https://github.com/nrwl/nx/issues/2103

_Originally posted by @JoA-MoS in https://github.com/cypress-io/cypress/issues/2316#issuecomment-559188733_

**Comment by jennifer-shehane** [comment] 2020-01-02 07:10
@JoA-MoS I was not able to reproduce this error as you laid our in the instructions for the demo repo. 

There is a single specfile with a single spec that is passing. What is the behavior I'm supposed to be seeing that is wrong in this example?

<img width="986" alt="Screen Shot 2020-01-02 at 1 37 50 PM" src="https://user-images.githubusercontent.com/1271364/71655466-39081800-2d65-11ea-8c88-f8707e41859a.png">

**Comment by JoA-MoS** [comment] 2020-01-04 21:58
@jennifer-shehane, did you checkout the cypress-js-heap-oom branch?

**Comment by JoA-MoS** [comment] 2020-01-28 04:55
Any, movement on this?

**Comment by anilkoithara** [comment] 2020-04-22 16:28
I am also having the same problem after my 100th test, I am getting `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` and after that error occurred test keep on running and  test reports showing 0 test run for remaing test, showing the status as passed

**Comment by reaktivo** [comment] 2020-07-28 11:29
Is there any update on this? We just started experiencing the same issue

**Comment by jennifer-shehane** [comment] 2020-12-15 08:19
I was able to recreate this with the provided repo in the cypress-js-heap-oom branch in Cypress 3.6.1. I was not able to reproduce this in the current Cypress 6.1.0 however. 

Closing as resolved, especially since there have been no comments in this issue in 6 months as well. 

Please open a new issue if you encounter a similar error with a reproducible example.

```
  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     22.spec.ts                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  23.spec.ts                                                                    (24 of 25)

<--- Last few GCs --->
tart of marking 1267 ms) (average mu = 0.188, current mu = 0.037) a[77045:0x7f8d3be17000]    70445 ms: Mark-sweep 2042.7 (2058.1) -> 2037.2 (2054.1) MB, 1868.2 / 0.0 ms  (+ 0.1 ms in 45 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1896 ms) (average mu = 0.097, current mu = 0.015) all[77045:0x7f8d3be17000]    71772 ms: Mark-sweep 2038.2 (2054.1) -> 2037.2 (2054.1) MB, 1313.7 / 0.0 ms  (average mu = 0.060, current mu = 0.010) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x111a73fcb]
    1: StubFrame [pc: 0x1119d2dc6]
    2: StubFrame [pc: 0x111a3be0c]
    3: StubFrame [pc: 0x111a3f6b9]
Security context: 0x2ba696f1dfe1 <JSObject>
    4: replace [0x2ba696f07d41](this=0x2ba6e6502f41 <String[81]: /Users/jennifer/Dev/nx-example-cypress-js-heap-oom/apps/node_modules/@types/tslib>,0x2ba6faf7cc49 <JSRegExp <String[#2]: \\>>,0x2ba626508979 <String[#1]: />)
    5: combinePaths [0x2ba6e38c5119...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1153124c5 node::Abort() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x115312a64 node::Abort() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x11102cd77 v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x11102cd10 v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1110b2125 v8::internal::Heap::CreateFillerObjectAt(unsigned long, int, v8::internal::ClearRecordedSlots, v8::internal::ClearFreedMemoryMode) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x1110b3063 v8::internal::Heap::CreateFillerObjectAt(unsigned long, int, v8::internal::ClearRecordedSlots, v8::internal::ClearFreedMemoryMode) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x1110b0874 v8::internal::Heap::CreateFillerObjectAt(unsigned long, int, v8::internal::ClearRecordedSlots, v8::internal::ClearFreedMemoryMode) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x1110ae3a6 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x1110b8af5 v8::internal::Heap::ProtectUnprotectedMemoryChunks() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x1110b90ff v8::internal::Heap::ProtectUnprotectedMemoryChunks() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x1114fefa7 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x1110def3c v8::internal::Smi::SmiPrint(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x1111028a3 v8::internal::SlicedString::SlicedStringGet(int) [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x111751e1e v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x111a73fcb v8::internal::trap_handler::RemoveTrapHandler() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x1119d2dc6 v8::internal::trap_handler::RemoveTrapHandler() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x111a3be0c v8::internal::trap_handler::RemoveTrapHandler() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x111a3f6b9 v8::internal::trap_handler::RemoveTrapHandler() [/Users/jennifer/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
```

**Closed by jennifer-shehane** 2020-12-15 08:19 UTC
Labels: stage: needs information

**Comment by jbarriojim** [comment] 2021-07-13 09:33
Hi,

I'm using the cypress 7.7.0 version with typescript and it is working one by one test. If I try to execute the 34 features...I have the same error...It doesn't happen before with fewer features.

There is any solution to this?

Thank you.
