### ISSUE TITLE
Edge Renderer Crash

### ISSUE THREAD

**Issue by ltvn14** [cypress-io/cypress#29113] opened 2024-03-12 13:37 UTC
### Current behavior

Edge crashes website during process execution, rendering Cypress unresponsive and preventing restart even in terminal. Same process executes without issues in Electron.

Here is the message from the terminal: 
```
We detected that the Edge Renderer process just crashed.

We have failed the current spec but will continue running the next spec.

This can happen for a number of different reasons.

If you're running lots of tests on a memory intense application.
  - Try increasing the CPU/memory on the machine you're running on.
  - Try enabling experimentalMemoryManagement in your config file.
  - Try lowering numTestsKeptInMemory in your config file during 'cypress open'.

You can learn more here:

https://on.cypress.io/renderer-process-crashed
GET /autofillservice/core/page/-7239681148803205933/-8598696600276319732?variations_header=CLUICIcQCLMQCL/tygE= 200 2038.284 ms - -
```

### Test code to reproduce

Since the issue occurs upon clicking, there is no specific code to provide. The problem arises during user interaction with the application interface.

### Cypress Version

13.6.4

### Node version

18.15.0

### Operating System

Microsoft Windows 10 Pro 10.0.19045 Build 19045

**Comment by jennifer-shehane** [comment] 2024-03-12 14:12
@nltv14 Have you tried the suggestions in the error message? Essentially the browser is running out of memory. We've seen issues with the use of the cucumber plugin with this situation. Outside of that, we'd need a way to reproduce it to investigate.

**Comment by ltvn14** [comment] 2024-03-12 14:34
> @nltv14 Have you tried the suggestions in the error message? Essentially the browser is running out of memory. We've seen issues with the use of the cucumber plugin with this situation. Outside of that, we'd need a way to reproduce it to investigate.

Yes, I've followed the suggestions in the error message. I added experimentalOriginDependencies: true and experimentalMemoryManagement: true to the configuration file, and now everything works fine. Thank you for the guidance!

**Comment by ltvn14** [comment] 2024-03-13 13:54
@jennifer-shehane The issue recurred even after adding the numTestsKeptInMemory: 10 to the configuration file. Unfortunately, I'm still unable to address the problem.

**Comment by jennifer-shehane** [comment] 2024-03-18 17:31
@nltv14 We would need a reproducible way for us to see the issue, otherwise we'll have to close this since there's no way for us to investigate.

**Closed as not planned** 2024-09-04 15:06 UTC
