### ISSUE TITLE
expecting an array or an iterable object but got [object Null]

### ISSUE THREAD

**Issue by agoodall77** [cypress-io/cypress#23992] opened 2022-09-27 11:29 UTC
### Current behavior

I have a suite of tests that use a before each statement. 
On running the tests using the webkit plugin the before each runs then the first test runs. 
When the before each runs again it fails before it can get to the second test. 

Producing a "expecting an array or an iterable object but got [object Null" error. 

The stack trace produced is:
```
TypeError: expecting an array or an iterable object but got [object Null]

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `CDS Pages`
    automation@https://website/__cypress/runner/cypress_runner.js:153782:63
    automate@https://website/__cypress/runner/cypress_runner.js:139528:32
From previous event:
    getAndClear@https://website/__cypress/runner/cypress_runner.js:139554:70
From previous event:
    @https://website/__cypress/runner/cypress_runner.js:160956:36
From previous event:
    onRunnableRun@https://website/__cypress/runner/cypress_runner.js:164671:50
    @https://website/__cypress/runner/cypress_runner.js:162351:19
    next@https://website/__cypress/runner/cypress_runner.js:108383:13
    @https://website/__cypress/runner/cypress_runner.js:108427:9
    timeslice@https://website/__cypress/runner/cypress_runner.js:102353:27
```
    
It should be noted that this issue only occurs when running against webkit not against chrome, edge or safari
    

### Desired behavior

Cypress runs the tests as per the other browsers without erroring. 

### Test code to reproduce

```js
describe('CDS Pages', () => {

  beforeEach(() => {
    cdsLoginPage.navigatecds(webpage)
    cdsLoginPage.addUsercredentials(user credentials)
    cdsLoginPage.signIn()
    cdsAccountPage.accountcds(an account)
    cdsAccountPage.switchincds(an account, text)
  })
})
```

### Cypress Version

10.8.0

### Node version

v14.18.0

### Operating System

11.6

**Comment by ZachJW34** [comment] 2022-09-27 15:17
Do you have `experimentalSessionAndOrigin` enabled? Try removing this flag and running again, `experimentalWebkitSupport` does not support `experimentalSessionAndOrigin` yet.

Going to close as duplicate of https://github.com/cypress-io/cypress/issues/23832

**Comment by agoodall77** [comment] 2022-09-27 15:37
Hi, I don’t have that set as far as I can tell.


From: Zachary Williams ***@***.***>
Date: Tuesday, 27 September 2022 at 16:17
To: cypress-io/cypress ***@***.***>
Cc: Al Goodall ***@***.***>, Author ***@***.***>
Subject: Re: [cypress-io/cypress] expecting an array or an iterable object but got [object Null] (Issue #23992)
EXTERNAL SENDER

Do you have experimentalSessionAndOrigin enabled? Try removing this flag and running again, experimentalWebkitSupport does not support experimentalSessionAndOrigin yet.

Going to close as duplicate of #23832<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcypress-io%2Fcypress%2Fissues%2F23832&data=05%7C01%7Cagoodall%40workforcesoftware.com%7Cb458e7f8ef0a4fcb467d08daa09b6a68%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637998886658029251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NAFpo%2BCDvv93kqjz9R2DqwYu8794YcKxjAYK37IUtbo%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcypress-io%2Fcypress%2Fissues%2F23992%23issuecomment-1259659977&data=05%7C01%7Cagoodall%40workforcesoftware.com%7Cb458e7f8ef0a4fcb467d08daa09b6a68%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637998886658029251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=usl2SOyvqv0j1giIkTCbyMq9uVim3iqUIMUFUKx4mtc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARN3TGRKDTYXDLUAOERV3LLWAMFYLANCNFSM6AAAAAAQWV7DOM&data=05%7C01%7Cagoodall%40workforcesoftware.com%7Cb458e7f8ef0a4fcb467d08daa09b6a68%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637998886658029251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6ENAl13fqrWjmxk0lZzrTyWh6CPVJHPnbQAHCUtVM9I%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



This message is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged, confidential or otherwise legally exempt from disclosure. If you are not the named addressee, or have been inadvertently and erroneously referenced in the address line, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately by e-mail and delete all copies of the message. (ID m031214)

**Comment by ZachJW34** [comment] 2022-09-27 16:17
Could you provide a reproducible example? I won't be able to investigate further without one as there isn't enough information for me to go on.

**Comment by agoodall77** [comment] 2022-09-27 16:47
Unfortunately,  that's going to be hard as it would give access to our intellectual property.
Happy to do a call and show the issue, you might spot the culprit easier?
We use page objects etc to make accessing certain functions easy for the team.
Hope that helps.

**Comment by astone123** [comment] 2022-09-28 13:21
@agoodall77 We understand that you wouldn't want to share any IP with us, but if you could create a sort of trimmed-down example of the project (preferably in a repository) that triggers this error so that we can re-produce the issue on our machines, that would be extremely helpful. Thanks!

**Comment by agoodall77** [comment] 2022-09-28 13:33
We’re using another source control system.
To have a stripped-down version looking at something less sensitive, might not still reproduce the issue (wouldn’t that be interesting!) and at least for me wouldn’t be a trivial undertaking to set this up in something else.
Would a call suffice?


From: Adam Stone ***@***.***>
Date: Wednesday, 28 September 2022 at 14:21
To: cypress-io/cypress ***@***.***>
Cc: Al Goodall ***@***.***>, Mention ***@***.***>
Subject: Re: [cypress-io/cypress] expecting an array or an iterable object but got [object Null] (Issue #23992)
EXTERNAL SENDER

@agoodall77<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagoodall77&data=05%7C01%7Cagoodall%40workforcesoftware.com%7C806c10eb64844ac6c57208daa1546736%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637999681183287592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u0G8cdv1DKpRvP9rrqANIeApB9S8W0%2FaiHAdq7XEQj0%3D&reserved=0> We understand that you wouldn't want to share any IP with us, but if you could create a sort of trimmed-down example of the project (preferably in a repository) that triggers this error so that we can re-produce the issue on our machines, that would be extremely helpful. Thanks!

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcypress-io%2Fcypress%2Fissues%2F23992%23issuecomment-1260906843&data=05%7C01%7Cagoodall%40workforcesoftware.com%7C806c10eb64844ac6c57208daa1546736%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637999681183287592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iS6dMn9PdzDO9ndbAf9gqJlHkUIx2wUk9itsmNnNykA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARN3TGQJOGN4RUORK64E5TLWARA6BANCNFSM6AAAAAAQWV7DOM&data=05%7C01%7Cagoodall%40workforcesoftware.com%7C806c10eb64844ac6c57208daa1546736%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637999681183287592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2s2mznjzWnEOiTqWqusIlQKDXdMH%2FTyZWTPK0RjhzKM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



This message is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged, confidential or otherwise legally exempt from disclosure. If you are not the named addressee, or have been inadvertently and erroneously referenced in the address line, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately by e-mail and delete all copies of the message. (ID m031214)

**Comment by astone123** [comment] 2022-09-28 13:56
@agoodall77 unfortunately we don't offer that level of support at this time. Please let us know if you are able to provide a reproducible example

**Comment by agoodall77** [comment] 2022-09-28 14:19
@astone123  This gives the same issues as I originally reported. 

Cypress.on('uncaught:exception', (err, runnable) => {
  return false;
});

describe('Pages', () => {

  beforeEach(() => {
    cy.visit('https://www.bbc.co.uk')
  })

  it('Test a thing', () => {
    cy.get('.ssrcss-13tejcu-NavItemHoverState').click()
  })

  it('Test another thing ', () => {
    cy.get('.ssrcss-154a395-NavItemHoverState').click()
  })
})

here's the stack trace 
<img width="1238" alt="Screenshot 2022-09-28 at 15 17 54" src="https://user-images.githubusercontent.com/73120154/192812999-05aba877-c89e-4dbb-aec0-08631d1082ff.png">
Many thanks,
Al

From: Adam Stone ***@***.***>
Date: Wednesday, 28 September 2022 at 14:57
To: cypress-io/cypress ***@***.***>
Cc: Al Goodall ***@***.***>, Mention ***@***.***>
Subject: Re: [cypress-io/cypress] expecting an array or an iterable object but got [object Null] (Issue #23992)
EXTERNAL SENDER

@agoodall77<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagoodall77&data=05%7C01%7Cagoodall%40workforcesoftware.com%7Cb4d2879b2476433db12e08daa1594c5a%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637999702227815860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f55U7E942mzu9e8zsAnAZ2BWwGHiiYQiC4a%2BUdFtS5U%3D&reserved=0> unfortunately we don't offer that level of support at this time. Please let us know if you are able to provide a reproducible example

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcypress-io%2Fcypress%2Fissues%2F23992%23issuecomment-1260955540&data=05%7C01%7Cagoodall%40workforcesoftware.com%7Cb4d2879b2476433db12e08daa1594c5a%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637999702227815860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gv4oma2q8tfxGbSMjhpMNwJdGATdlEtI8RJi6LdlzV8%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARN3TGUHPFCUCWPKNUZCZ3DWARFBTANCNFSM6AAAAAAQWV7DOM&data=05%7C01%7Cagoodall%40workforcesoftware.com%7Cb4d2879b2476433db12e08daa1594c5a%7Cc61157e903cb47589165ee7845cb0ca3%7C0%7C0%7C637999702227815860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M%2FwoukLFQhqQ36HUYbmc1lO6H4lp%2FYKqwS7L2P7LWiQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



This message is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged, confidential or otherwise legally exempt from disclosure. If you are not the named addressee, or have been inadvertently and erroneously referenced in the address line, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately by e-mail and delete all copies of the message. (ID m031214)

**Comment by flotwig** [comment] 2022-09-28 15:04
This looks like #23832. Thanks for the repro @agoodall77, I'm going to close this issue since it is a duplicate. You can watch #23832 for updates on this.

**Closed as completed by flotwig** 2022-09-28 15:04 UTC
