### ISSUE TITLE
add support for es7 async/await

### ISSUE THREAD

**Issue by jhanink** [cypress-io/cypress#487] opened 2017-04-20 23:07 UTC
* Operating System:
* Cypress Version:

### Are you requesting a feature or reporting a bug?

FEATURE

#### Test code:

```js

```

### Additional Info (images, notes, stack traces, etc)
can you add this babel plugin?

https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-to-generator

**Comment by brian-mann** [comment] 2017-04-20 23:15
Duplicate of #343

**Closed by brian-mann** 2017-04-20 23:15 UTC

**Comment by SaltyDH** [comment] 2018-02-19 23:24
Does anyone have an example of this working now that the new plugin system is available?
