### ISSUE TITLE
Do not create new cypress configuration each time in the root of monorepo

### ISSUE THREAD

**Issue by dmtrKovalenko** [cypress-io/cypress#4961] opened 2019-08-09 13:20 UTC
### Current behavior:
Right now when you are typing `yarn cypress open` in the root of the monorepo instead of the particular project it will create a lot of example and configuration files. 

![image](https://user-images.githubusercontent.com/16926049/62781746-4fb18800-bac1-11e9-877b-9130a72b905b.png)

### Desired behavior:
It will be nice to make something like `yarn workspaces` do. Just send a note to the output
```
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
```

### Steps to reproduce: (app code and test code)
Run `yarn cypress open` in the root of any monorepo

### Versions

Cypress: 3.4.0

**Comment by mpahuja** [comment] 2019-08-30 09:13
might wanna consider adding a `cypress` script in your package.json file which passes in the `--project path\to\your\cypress\folder` and then use `yarn run cypress` to run your tests.

> package.json
```
{
  "name": "my-package",
  "scripts": {
    "build": "babel src -d lib",
    "test": "jest",
    "cypress":"cypress run --project path\to\your\cypress\folder"
  }
}
```

**Comment by jennifer-shehane** [comment] 2019-09-26 17:51
This PR will allow you to turn off the autogeneration of the configuration file alone. https://github.com/cypress-io/cypress/pull/3246

**Comment by jennifer-shehane** [comment] 2019-09-26 17:53
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/619 essentially though since that would enable you to turn off the auto scaffolding of files.

**Closed by jennifer-shehane** 2019-09-26 17:53 UTC
