### ISSUE TITLE
cy.visit can't render https://teams.microsoft.com

### ISSUE THREAD

**Issue by JemmyWong** [cypress-io/cypress#8942] opened 2020-10-23 08:17 UTC
### Current behavior

I saw many cy.visit issues are about proxy, we don't use any proxy.

Chrome, Firefox, Electron can reproduce this issue.

`cy.visit('https://teams.microsoft.com')`, the request got a 200 response code with page data, but the page didn't render. I save the page data to a separate HTML file and open it by Chrome/Firefox/Safari, all browser can render it correctly.

Messages printed on chrome console:
```
DevTools failed to load SourceMap: Could not load content for http://localhost:51492/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://teams.microsoft.com/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cypress_runner.js:200351 
```

<details>
<summary>The page can't be rendered:</summary>

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/18246211/96972500-299ec900-1549-11eb-8bee-d8b1bd22256f.png">
</details>

<details>
<summary>Response of `teams.microsoft.com` is 200:</summary>

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/18246211/96972626-4dfaa580-1549-11eb-9d3d-7c07e41952a6.png">
</details>

<details>
<summary>Save response data to a HTML file, Chrom/Safari/Firefox can render it:</summary>

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/18246211/96972795-8b5f3300-1549-11eb-905e-9b274cb2b266.png">
</details>

### Desired behavior

<details>
<summary>The URL should redirect to `https://login.microsoftonline.com` to log in.</summary>

<img width="745" alt="image" src="https://user-images.githubusercontent.com/18246211/96972058-9796c080-1548-11eb-96f5-2eb3917ea0ce.png">
</details>

### Test code to reproduce

```
it('Login MSFT Teams', () => {
  cy.visit('https://teams.microsoft.com');
  cy.url().should("include", "https://login.microsoftonline.com");
})
```

### Versions
macOS: 10.15.7
Cypress: 5.4.0 (5.4.0.481307)
Chrome: 86.0.4240.111 (Official Build) (x86_64)
Firefox: 82.0 (64-bit)

**Comment by jennifer-shehane** [comment] 2020-10-23 09:20
Duplicate of https://github.com/cypress-io/cypress/issues/3459

**Closed by jennifer-shehane** 2020-10-23 09:20 UTC
