### ISSUE TITLE
Not able to run sample test on Windows 10....Chrome window opens..but is blank

### ISSUE THREAD

**Issue by mathewsk** [cypress-io/cypress#2104] opened 2018-07-06 04:10 UTC
Tried several times to get Cypress to work on Windows 10 but am unsuccessful

Installed cypress and ran `npx cypress open` and clicked on the 1st test to run.

Browser window opens but there is nothing on the page...does not show anything on the page.
Screen shots and debug logs are attached.

Any workarounds or ideas to get this to work ?

### Steps to reproduce:

- create new directory `4`
- `cd 4`
- `npm init`
- `npm install --save-dev cypress`
- `set DEBUG=cypress:* cypress open`
- `npx cypress open`
- Cypress app opens..show sample tests
- Clicked the first test 
- Chrome browser opens..
- I can see the Cypress logo on the top right (screen shot attached)
- But the page is blank..
- There are no errors seen on Developer tools - console

log file `cypress.log` attached.
also attached is screenshot of browser window

### Versions

Windows 10 64 bit
Chrome browser version  67.0.3396.99 (Official Build) (64-bit)

[cypress.log](https://github.com/cypress-io/cypress/files/2168980/cypress.log)
![screen1](https://user-images.githubusercontent.com/4730582/42359439-90b44eb4-80a7-11e8-96c2-e055a002414e.JPG)

**Comment by Bkucera** [comment] 2018-07-06 11:56
Hi @mathewsk, do you get the same behavior when selecting the electron browser? What happens with `cypress run` ?

**Comment by mathewsk** [comment] 2018-07-06 12:19
Yes same behavior even if I choose Electron..(Electron 59)

**Comment by Bkucera** [comment] 2018-07-06 14:04
@mathewsk have you tried `cypress run`?

**Comment by mathewsk** [comment] 2018-07-07 22:39
here is output of cypress run

![image](https://user-images.githubusercontent.com/4730582/42415212-c0776684-820c-11e8-80ee-8b94c4262ec9.png)

**Comment by slope-taylor** [comment] 2018-09-04 19:48
FWIW, I'm getting the same behavior on macOS High Sierra, Version 10.13.6.  Version of Cypress doesn't seem to matter (I've tried older versions), but mine is 3.1.0.  Same behavior in Chrome and Electron, and I'm also getting 500 errors in the terminal where it's logging GET and HEAD requests.  3 HEAD requests are 500s (see image from terminal which happens after clicking on any of the test files to run it).
![screen shot 2018-09-04 at 3 45 57 pm](https://user-images.githubusercontent.com/36546925/45054002-a87ad400-b059-11e8-9b2a-309ab2ebfb56.png)

Cypress is working fine on my old Macbook, which is running El Capitan.

**Comment by Bkucera** [comment] 2018-09-10 16:29
@slope-taylor  Did you try increasing `pageLoadTimeout` ?

**Comment by oswaldofreitas** [comment] 2018-10-15 14:56
same as @slope-taylor here

**Comment by spideynr** [comment] 2018-10-19 14:21
Same issue in MacOS High Sierra. Any fixes? I can't seem to be able to run anything

**Comment by Bkucera** [comment] 2018-10-19 20:49
@spideynr can you give more details? Can you try setting `baseUrl` in `cypress.json` ?

**Comment by spideynr** [comment] 2018-10-22 07:55
Hi @Bkucera,

i followed [https://docs.cypress.io/guides/getting-started/installing-cypress.html#Environment-variables](the instructions) to install cypress. It opened up the window appropriately, generated the `cypress` folder and then trying to run the example tests or even creating my own will display an empty browser window. Both Chrome and Electron show nothing, with the console printing out 500s 

```
GET /__/ 200 8.184 ms - -
GET /__cypress/runner/cypress_runner.css 200 42.969 ms - -
GET /__cypress/runner/cypress_runner.js 200 349.127 ms - -
HEAD / 500 186.119 ms - -
HEAD / 500 189.158 ms - -
HEAD / 500 187.618 ms - -
```

**Comment by Bkucera** [comment] 2018-10-23 15:11
@spideynr is there anything in the browser console?

**Comment by spideynr** [comment] 2018-10-25 09:01
@Bkucera update, the macbook i am using is running Mojave after all. Not High Sierra.

**Comment by spideynr** [comment] 2018-10-25 20:59
@Bkucera I don't know the cause either. I tried multiple times to delete the ~/Library/Caches/Cypress folder and reinstall but to no avail. After many retries I even uninstalled purely chrome and it's settings ( I highly doubt that this was the error) and then restarted the Mac and it now works 🎉 

So I guess another case of turning it off and on again? 

It's pretty stupid that after removing/reinstalling the package I didn't think of restarting the machine just in case, but I am leaving this here to help some other poor soul like me

**Comment by slope-taylor** [comment] 2018-11-27 15:59
I thought I'd report back here as well.  Rebooting my laptop also fixed the issue for me, so it appears there might be an issue just with the initial install.  Didn't matter how many times I installed a fresh copy of Cypress until I rebooted the laptop.  Thanks for the help everyone!

**Comment by spideynr** [comment] 2018-11-27 16:08
I did a clean install on my macosx from scratch to solve this one and for all. Not a great fix but a fix nevertheless

**Comment by slope-taylor** [comment] 2018-12-11 20:43
FYI, this started happening again for me and doing a cache refresh and rebooting is no longer fixing the issue, so I'm dead in the water on this machine again.  Any further suggestions would be greatly appreciated!

**Comment by jarrodldavis** [comment] 2018-12-12 08:09
@slope-taylor Are you by chance using Chromium or Chrome Dev/Canary? I've found some interesting changes in how newer releases are handling `localhost` and `127.0.0.1` URLs – in short, Chrome and Chromium are now bypassing configured proxies (which is what Cypress uses to provide the test runner on the `/__/` path of `baseUrl`) for those local URLs. I detailed my findings [in this other issue][1].

My recommendation is to try using a different URL:
- configure your `/etc/hosts` file with a custom domain mapping to `127.0.0.1` and use it as `baseUrl`
- if your web server is attaching to all network interfaces/IP addresses, find your computer's network IP address and use that as `baseUrl`

[1]: https://github.com/cypress-io/cypress/issues/1872#issuecomment-445581050

**Comment by slope-taylor** [comment] 2018-12-12 14:07
@jarrodldavis Thanks for your reply!  However, I'm just using a standard stable chrome install, currently Version 71.0.3578.80

**Comment by jennifer-shehane** [comment] 2019-04-25 06:57
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by mathewsk** [comment] 2019-04-25 12:25
Yes, I can still reproduce this ..even almost a year after I originally reported it.
The repro steps are the same as I originally reported it.
Cypress does not run on Windows

**Steps to reproduce:**
npm init
npm install --save-dev cypress
npx cypress open
Cypress app opens..show sample tests
Clicked the first test
Chrome browser opens..
But the page is blank..

Versions
**Windows 10 64 bit**
Chrome browser - latest version (64-bit)

**Comment by slope-taylor** [comment] 2019-04-25 14:14
Still an issue for me on macOS as well.  My workaround has been to install Cypress on my Windows 10 VM and run it in there, but that's obviously not ideal.

My steps to reproduce are exactly the same as @mathewsk , except on macOS Mojave 10.14.3.

Sometimes doing a full reinstall and a reboot fixes it on mac, but other times not.  So I eventually gave up and installed it on Windows 10, and that seems to work OK.

**Comment by alxjnk** [comment] 2019-05-15 11:11
Still an issus. Windows 10 64 bit, Chrome 74, Canary 76. "cypress": "^3.2.0",

**Comment by Bkucera** [comment] 2019-05-15 14:49
@mathewsk can you open the browser console and see if there are any errors?

**Comment by mathewsk** [comment] 2019-05-16 13:37
> @mathewsk can you open the browser console and see if there are any errors?

tried this again..and have the same issues...no console errors.
I created a brand new directory, npm init, npm install cypress --save-dev, ./node_modules/.bin/cypress open, added the sample files, clicked on one of the test files to run, browser window opens,but then nothing ...
There are no errors in the console in developer tools ..but see 500 status in the powershell window
![image](https://user-images.githubusercontent.com/4730582/57858001-dbaf5e80-77b5-11e9-82cc-8c7a34bb2e90.png)

I also refreshed the page on the browser...and I see the websocket call in Pending state ..screenshot attached below
![image](https://user-images.githubusercontent.com/4730582/57857812-7fe4d580-77b5-11e9-9704-4f3544c318fa.png)

**Comment by Bkucera** [comment] 2019-05-16 17:48
@mathewsk does window.Runner exist in the console?

**Comment by mathewsk** [comment] 2019-05-16 18:08
yes it does exist
![image](https://user-images.githubusercontent.com/4730582/57876745-ba616900-77db-11e9-8694-276d255b9624.png)

**Comment by Bkucera** [comment] 2019-05-17 17:23
@mathewsk hmm, then maybe somehow Runner.start is not getting called. The html should have a call to `Runner.start(..)` in a script tag. Possibly try calling 

```
Runner.start(document.getElementById('app'), {})
```
in the console and see what happens

**Comment by mathewsk** [comment] 2019-05-18 05:15
Not sure what Runner.start was supposed to do...but here is a screenshot.. anyway the test is still not running.. Could these issues be related to websocket requests?
![image](https://user-images.githubusercontent.com/4730582/57964892-0c041380-7902-11e9-92dd-cd8f2f4fea7f.png)

**Comment by mikhailkopev** [comment] 2019-06-11 18:35
Hello. Any news on this issue?
I am getting the same error on Windows.

**Comment by planetbk9** [comment] 2019-07-10 07:31
Try to add map for localhost to 127.0.0.1 in /etc/hosts.

**Comment by jennifer-shehane** [comment] 2021-01-05 02:01
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-01-05 02:01 UTC
Labels: stage: needs information
