### ISSUE TITLE
No way to use check key combinations with cy.type() on date inputs

### ISSUE THREAD

**Issue by Abelhawk** [cypress-io/cypress#8254] opened 2020-08-11 18:48 UTC
### Current behavior:

As written on [Cypress documentation](https://docs.cypress.io/api/commands/type.html#Date-Inputs), "Special characters ( `{leftarrow}`, `{selectall}`, etc.) are not permitted" on date inputs using the `cy.type()` command. Attempting to check keypresses throws an error because dates need to have the format `yyyy-MM-dd.`

![image](https://user-images.githubusercontent.com/35573290/89929876-1aa1af00-dbc7-11ea-83ad-f2ec8039eff4.png)

### Desired behavior:

I want to be able to create a Cypress test to check a function related to pressing a key combination (in this case, CTRL+C) on a date input. Rather than the date input immediately assuming I'm trying to type `{ctrl}C`, I want it to check the key presses and be able to use special characters. 

### Test code to reproduce

`cy.get('[data-test=date-input]').first().type('{ctrl}C');`

### Versions

Cypress 4.5.0

**Comment by jennifer-shehane** [comment] 2020-08-12 06:39
Yah, seems like we do a naive RegExp against the string passed into `.type()` here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/keyboard.ts#L401:L401 Likely this is an issue with other input types as well. 

I'm not sure what we would do to get around this exactly though.

The workaround for this would be to manually trigger the events on the input using [`.trigger()`](https://on.cypress.io/trigger) using the corresponding event and charCodes, etc.

**Comment by sainthkh** [comment] 2020-12-29 06:34
FYI, `cy.type('{ctrl}c')` doesn't trigger copy event. I won't do until native events are supported.

**Comment by jennifer-shehane** [comment] 2021-07-14 19:18
Closing as duplicate of https://github.com/cypress-io/cypress/issues/17337 since that seems to  be a more plausible usecase.

**Closed by jennifer-shehane** 2021-07-14 19:18 UTC
Labels: pkg/driver, stage: ready for work, topic: cy.type ⌨️, type: unexpected behavior
