### ISSUE TITLE
Cypress fails when use `should('be.visible')` on a visible element - overflow hidden with position absolute outside

### ISSUE THREAD

**Issue by freewind** [cypress-io/cypress#4395] opened 2019-06-05 17:56 UTC
I found `should('be.visible')` gives wrong result sometimes (even in latest version). I finally made a simple demo to reproduce it:

**index.html**

```html
<html>
<head>
    <style>
        #main {
            border: 3px solid red;
            width: 200px;
            height: 200px;
            overflow: hidden;
        }

        #outside {
            position: absolute;
            left: 300px;
            border: 3px solid blue;
            width: 100px;
            height: 100px;
        }

        #hello {
            border: 3px solid green;
        }

    </style>
</head>
<body>
<div id="main">
    Main (overflow:hidden)
    <div id="outside">
        Outside (position:absolute)
        <span id="hello">Hello</span>
    </div>
</div>
</body>
</html>
```

**hello_spec.ts**

```ts
describe('cypress', () => {

  it('test visible correctly', () => {
    cy.visit('index.html');
    cy.get('#hello').should('be.visible');
  });

})

```

![image](https://user-images.githubusercontent.com/333781/58978191-eaf65a80-87fd-11e9-9b6d-1d1a43834c7a.png)

A complete small demo: https://github.com/freewind-demos/typescript-cypress-check-visibility-issue-demo

The problem is on this line of code:

![image](https://user-images.githubusercontent.com/333781/58978318-2b55d880-87fe-11e9-943c-aac7ad1cffad.png)

(In function `elIsOutOfBoundsOfAncestorsOverflow`)

**Comment by jennifer-shehane** [comment] 2019-06-07 16:34
This is actually a duplicate of https://github.com/cypress-io/cypress/issues/755, but I will leave this issue open since the repro is so simple and comparable to our other tests. 

Here is the line of code you are referring to: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/visibility.js#L203

Here are the tests for this logic, which I think are fairly self explanatory: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/dom/visibility_spec.coffee#L3

We run our `packages/driver` tests within Cypress itself - To run the tests:

- within `cypress` root, run `npm i`
- cd to `cypress/packages/runner` and run `npm watch`
- cd to `cypress/packages/driver` and run `cypress open`
- click on the `visibility_spec` to run it within Cypress

**Comment by jennifer-shehane** [comment] 2019-06-10 08:21
@freewind This failing test case is now a part of https://github.com/cypress-io/cypress/pull/4421

**Comment by freewind** [comment] 2019-06-11 05:23
@jennifer-shehane Thanks so much for the quick work

**Closed** 2019-06-19 08:21 UTC
Labels: first-timers-only, pkg/driver, stage: needs review, topic: visibility 👁, type: bug

**Comment by Pieras2** [comment] 2022-02-06 13:33
What was the cypress ver. for this bug?
I have such an issue on version 7.5.0.
Cypress states that parent object has overflow:hidden and relative size i 0 
My element is a button, but it was not the only item for which 'be.visible' failed.
