### ISSUE TITLE
Show number of retries in logs / dashboard per file

### ISSUE THREAD

**Issue by ismail-codinglab** [cypress-io/cypress#8426] opened 2020-08-27 01:13 UTC
### Current behavior:

![image](https://user-images.githubusercontent.com/48755937/91372039-e3600e80-e812-11ea-8997-119cef368b1f.png)

### Desired behavior:

Number of retries per test file described

The reason for this is:

1. It's cool, I like seeing the retries and how much it helps :)
2. It gives you insight on how often it fails
3. you can use it to check if it has become less stable or more stable 
4. Potentially nice valuable graph feature for the cypress dashboard ? :slightly_smiling_face:. It not only helps retries but tells your stability!

### Versions

Cypress v5

p.s. i'm loving the retries :sunglasses:

**Comment by ismail-codinglab** [comment] 2020-08-27 01:20
Oops.. I just noticed there's already an issue #8372 
Mods can choose which one to close

**Comment by jennifer-shehane** [comment] 2020-08-27 06:32
Duplicate of #8372 

The Dashboard now displays the screenshots and errors from each attempt of a test that retried. The test results are also filterable by whether they retried.

**Filter by whether test retried**

<img width="1470" alt="test-retries-filter copy" src="https://user-images.githubusercontent.com/1271364/91129249-afc89b80-e6cf-11ea-8618-6876e4b40d16.png">

**See screenshot and error for each attempt when clicking on test**

<img width="1470" alt="test-results-attempts" src="https://user-images.githubusercontent.com/1271364/91129281-c1aa3e80-e6cf-11ea-91d9-e5253b278d7a.png">

**Closed by jennifer-shehane** 2020-08-27 06:32 UTC
