### ISSUE TITLE
 GLib-GIO-ERROR: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

### ISSUE THREAD

**Issue by SarahNaiane1** [cypress-io/cypress#30176] opened 2024-09-03 19:33 UTC
### Current behavior

Hi Cypress Team,

I am experiencing an issue with Cypress on Ubuntu 24.04. When trying to open Cypress using the command npx cypress open, I encounter the following error:

```
**![Captura de tela de 2024-09-03 16-30-09](https://github.com/user-attachments/assets/4c4c6f82-3c7b-4f60-bf22-d852f3747720)**
Details:

Platform: Ubuntu 24.04
Cypress Version: 13.14.1
Steps to Reproduce:

Run npx cypress open in a terminal.
Observe the error message and the unexpected exit of the Test Runner.
What I Have Tried:

Reinstalled Cypress and cleared the cache.
Verified and reinstalled necessary GNOME packages and dependencies.
Executed Cypress with xvfb-run.
Tried running Cypress in both Xorg and Wayland sessions.
Updated the system and drivers.
Attempted various troubleshooting steps as suggested in the Cypress documentation and community forums.
Additional Information:

The issue persists across different versions of Cypress and after system updates.
I have consulted the [Cypress documentation](https://on.cypress.io/) and the [GitHub issues page](https://github.com/cypress-io/cypress/issues) but have not found a solution to this specific problem.
Request:

Could you please provide guidance or a possible workaround for this issue? If this is a known issue, is there an estimated timeline for a fix?

Thank you for your assistance.

### Desired behavior

_No response_

### Test code to reproduce

I just installed cypress with the command npm install cypress --save-dev
 and rode npx open cypress

### Cypress Version

13.14.1

### Node version

cypress": "^13.14.1",

### Operating System

Ubuntu 24.04

### Debug Logs

```shell
(Cypress:30356): GLib-GIO-ERROR **: 16:31:34.124: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 24.04)
Cypress Version: 13.14.1
```

### Other

![Captura de tela de 2024-09-03 16-30-09](https://github.com/user-attachments/assets/13b3dcb7-85b4-4c1e-8098-0f0f794584fc)

**Comment by jennifer-shehane** [comment] 2024-09-03 20:05
Duplicate of https://github.com/cypress-io/cypress/issues/30160

**Closed as not planned by jennifer-shehane** 2024-09-03 20:05 UTC
Labels: type: duplicate
