### ISSUE TITLE
Chrome does not close when I kill cypress

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#18132] opened 2021-09-16 20:01 UTC
### Current behavior

When I run `cypress open-ct` and want to close it, I am used to closing the cypress app.
It then closes both the cypress app and the spawned browser.

From 8.3.0 and on closing the cypress app leaves the chrome instance hanging.

See video below

https://user-images.githubusercontent.com/5592465/133678153-a13ea31c-99e8-4f69-9153-9b59224d2fce.mov

### Desired behavior

When I close cypress, the spawned browser will fail all requests. It is now driven by nothing. It should probably close automatically.

### Test code to reproduce

```sh
git checkout https://github.com/elevatebart/calc-vite
cd calc-vite
yarn
yarn cypress open-ct
```

Then close the cypress app that appears

### Cypress Version

8.3.0

### Other

It might very well be connected to the electron upgrade sending different signals and leaving the Chrome instance running

**Comment by emilyrohrbough** [comment] 2022-11-17 14:19
@elevatebart Are you still experiencing this issue?

**Comment by emilyrohrbough** [comment] 2022-11-17 14:37
duplicate of https://github.com/cypress-io/cypress/issues/18827 . Look like this should have been fixed in https://github.com/cypress-io/cypress/pull/19322

**Closed by emilyrohrbough** 2022-11-17 14:37 UTC
Labels: pkg/electron, pkg/launcher, stage: ready for work
