### ISSUE TITLE
Flaky test: CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23326] opened 2022-08-13 00:49 UTC
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/41821/workflows/3a631187-bd7e-4234-a5c5-64fb97984e5c/jobs/1733761/steps

### Link to failing test in GitHub

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/blogs__iframes/cypress/e2e/xhr-spec.cy.js#L10

### Analysis

Some hints:
The following error in the logs. Keep in mind that it happens at the start of the suite, so it's followed by several successful tests. [Looks like playwright is currently triaging the same error ](https://github.com/microsoft/playwright-python/issues/1277)
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[6037:0812/181450.054272:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by brianwawok** [comment] 2022-08-18 14:03
Seeing this a lot, and my server is crashing. Not 100% if this is related.

**Comment by aj-sdet** [comment] 2022-09-08 14:44
seeing this:

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[29310:0908/142840.488087:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[29310:0908/142840.493355:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported

**Comment by aj-sdet** [comment] 2022-09-08 17:30
the issue in my case was with electron browser, thus switched to chromium and ran fine.

**Comment by MikeMcC399** [comment] 2023-01-03 14:27
@rachelruderman 

- I can reproduce the errors

```text
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```
on GitHub [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) & [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md)
with `electron` & `chrome` browsers
running in container: [cypress/included:12.2.0](https://github.com/cypress-io/cypress-docker-images/tree/master/included/12.2.0) (with Node.js 16.16.0).

I have cloned the test https://github.com/cypress-io/github-action/tree/master/examples/v10/basic and modified it to run under Cypress 12.2.0.

The test runs successfully, so the errors are just a distraction.

Would it be helpful for me to open a separate new issue regarding the `libva` and `dri3` errors?

- https://github.com/cypress-io/cypress/issues/23343 also mentions the error message, however this issue is closed

- The issue https://github.com/microsoft/playwright-python/issues/1277 you mentioned is also closed.

**Comment by MikeMcC399** [comment] 2023-08-01 06:14
[Flaky tests](https://cloud.cypress.io/projects/6p53jw/analytics/flaky-tests) from [cypress-io/cypress-example-recipes](https://github.com/cypress-io/cypress-example-recipes/) are recorded into [Cypress Cloud](https://cloud.cypress.io/projects/6p53jw/). 

I don't see the test from this issue appearing in the [Flaky tests](https://cloud.cypress.io/projects/6p53jw/analytics/flaky-tests) list, so I suggest to close this issue.

- https://github.com/cypress-io/cypress/issues/25357 is separately logged.

**Comment by jennifer-shehane** [comment] 2023-10-04 21:23
Closing since this is likely stale

**Closed by jennifer-shehane** 2023-10-04 21:23 UTC
Labels: OS: linux, stage: backlog, process: flaky test, topic: flake ❄️
