### ISSUE TITLE
cy.get fails once in a while with "expected undefined to be enabled"

### ISSUE THREAD

**Issue by bukharov** [cypress-io/cypress#9404] opened 2020-12-01 23:45 UTC
After upgrading to `6.0.1` tests that weren't flaky became flaky and I believe it's not an issue with our code.

### Current behavior

<img width="636" alt="Screen Shot 2020-12-01 at 6 33 46 PM" src="https://user-images.githubusercontent.com/49371/100809692-aeacb600-3404-11eb-9cfb-1818b74b12b5.png">

### Desired behavior

If an element is not found I expect Cypress to fail as it normally does when it cannot find an element. 
("Timed out retrying: Expected to find element: input[name=email], but never found it.")
And if an element is found it expect it not to fail 8)

### Versions

Cypress `6.x` (`6.0.0` exhibited the same issue)

**Comment by bukharov** [comment] 2020-12-02 00:05
Another incarnation of this issue, could it be because it happens after `visit`?

<img width="675" alt="Screen Shot 2020-12-01 at 7 03 26 PM" src="https://user-images.githubusercontent.com/49371/100811175-000a7480-3408-11eb-89b6-7960887eacd0.png">

**Comment by OdedSoluto** [comment] 2020-12-03 07:39
I also experience this issue randomally accross my tests, happened in previous cypress versions when I've enabled route2, now this is enabled by default and I cannot use cypress (v6)

**Comment by jennifer-shehane** [comment] 2020-12-04 08:40
What's the last version you used where this was working correctly? It likely has something to do with the timing of the app where the input disappears after it's queried. We'd need a reproducible example to investigate it fully though. 

Can either of you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by bukharov** [comment] 2020-12-07 22:46
I checked with `4.7.0` and then with `5.6.0` it's fine with both. The main issue is that it doesn’t fail consistently, it works fine roughly 6 out of 10 runs.

**Comment by antonyfuentes** [comment] 2020-12-28 18:03
I'm experiencing exactly the same issue: 

<img width="827" alt="Screen Shot 2020-12-28 at 12 00 48" src="https://user-images.githubusercontent.com/16458076/103234099-677eeb80-4904-11eb-9d07-7664131ea5bb.png">

For some reason, cypress doesn't retry finding the element. Instead, it fails with the issue seen above.
I'm currently on Cypress 6.0.1

**Comment by bukharov** [comment] 2021-03-02 16:25
I can no longer reproduce this with `6.6.0`.

**Comment by bukharov** [comment] 2021-04-08 20:24
This's comeback in Cypress 7x ( I checked on `7.0.0` and `7.0.1`:

<img width="665" alt="Screen Shot 2021-04-08 at 4 23 34 PM" src="https://user-images.githubusercontent.com/49371/114091523-cbf80200-9886-11eb-95c9-b165e86e4358.png">

It marks test as flaky, because it passes the second time.

**Comment by erwindetesters** [comment] 2021-08-23 11:41
I see this with version 8.3.0.

`expected undefined to exist`
`expected undefined to be visible`

This happens when the initial pageload (first paint) is slow

**Comment by erwindetesters** [comment] 2021-08-25 07:06
Does anyone have some pointers on how I can provide the required information that you need in order to look into this?

**Comment by jrchongo** [comment] 2021-11-30 15:48
Is there anything worth enabling in the debug logs?  We're seeing it regularly in our CI pipeline, but I cannot reproduce it locally - even when running the test in a loop 50 times.

**Comment by erwindetesters** [comment] 2021-12-09 10:04
@jrchongo what you are describing is exactly what I was thinking and is also the scenario we see.

In our case
```
cy.visit()
// some actions
// some assertion(s)
cy.visit()
// some action which fails with the error
```

**Comment by maxime-helen** [comment] 2021-12-29 03:32
I am also experiencing this problem. Is there a workaround by any chance?

**Comment by meeranharish** [comment] 2021-12-30 14:36
Any update on this issue or work around. This is a pain!!

**Comment by BlaiseBocz** [comment] 2022-04-23 16:31
I also saw this issue happens randomly in 9.5.0 
```
expected undefined to be true
AssertionError
expected undefined to be true
  59 |         cy.wait('@reqest').then((xhr) => {
  60 |         expect(xhr?.request?.body?.variables?.settings?.reviewQueue).to.be
> 61 |           .true;
     |            ^
```
as a quick fix I used Test Retries functionality

**Comment by SealviewTW** [comment] 2022-04-26 08:38
This issue still happens to me in 9.6.0.

I have a loading spinner on page, that appears and disappears as stuff loads on screen, so I wait for the spinner to appear and then disappear, and when waiting for it to disappear the 'undefined' problem occurs.

`cy.get('.mat-progress-spinner',{timeout: 10000}).filter(':visible',{timeout: 30000}).should('have.length.at.least',1)` - works
`cy.get('.mat-progress-spinner',{timeout: 10000}).filter(':visible',{timeout: 30000}).should('have.length',0)` - does not work, and the cy log in test runner says `expected undefined to have a length of 0`

Interesting enough, it does NOT reach the 'undefined' straight away, but waits a bit before reaching the 'undefined' log message

Waiting for the element to be visible, working 100% correct all the time

<img width="588" alt="image" src="https://user-images.githubusercontent.com/11609472/165258583-af8dacf9-aa21-482a-8e92-ee875bee8a3b.png">

Waiting for the element to disappear, it processes for 1-2 seconds 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/11609472/165258476-032d4c62-9ed6-4cc6-8d47-8a7248d60eb5.png">

And then this is the result while waiting for the element to disappear

<img width="605" alt="image" src="https://user-images.githubusercontent.com/11609472/165258847-b7726127-6f18-497c-a654-017875868910.png">

**Comment by dmaicher** [comment] 2022-04-26 08:48
This also happened a lot to us recently after we added some global `cy.intercept('*').as('request');` inside a `beforeEach` hook.

We now removed this intercept and since then no fails anymore :thinking: :man_shrugging:

**Comment by rlyttle** [comment] 2022-05-21 11:54
This has been happening intermittently for me for quite a while, always very early in my tests. Forcing a `cy.wait(10 * 1000)` after loading the webapp doesn't help (I thought it might be related to the webapp taking too long to load).

I don't believe it's related to `cy.intercept` - though I recently added this, it was happening long before this addition to my tests.

Currently on Cypress v9.6.1.

**Comment by AurelienKun** [comment] 2022-08-16 13:35
We have the same kind of issues here. We tried all Cypress 10.2, 10.4 & 10.5
It randomly fails on headless run especially on electron/firefox using the  cypress-included docker image while chaining commands like : 
``` cy.get(SELECTOR).should("exist").and("be.visible") ```
It seems to appear less when using chrome though.

**Comment by olitomas** [comment] 2022-09-13 17:33
This keeps happening to me after updating to 10.X from 8.X and its driving me absolutely nuts!

This:
`cy.url().should('eq', 'http://localhost:8000/');`

Returns this:
`expected undefined to equal 'http://localhost:8000/'`

**Comment by sir-dunxalot** [comment] 2022-11-16 20:36
I get this error message, occasionally, when a previous step or command in the test failed. For me, the solution is not to solve the failing step. Instead, the solution is to identify any other steps failing prior to the one throwing this error message `expected undefined to be enabled`.

For example, look for the **_first_** step highlighted in red in the spec:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/4495352/202288646-eb48cfc7-8363-4234-8c20-f5cd05e1c5b9.png">

That might be the culprit.

**Comment by BlueWinds** [comment] 2022-11-17 19:53
This should be resolved in Cypress 12 - see https://github.com/cypress-io/cypress/pull/24628 for the big refactor of how subjects are determined and commands chain together / retry.

Sorry it took us so long to get to this - this is pretty fundamental to how Cypress executes commands, retries things, and chains subjects together. #7306 has a ton of discussion around the subject (and around how Cy12 is going to solve it), so I'm going to refer people there and close this one, just to keep things a bit more centralized.

**Closed by BlueWinds** 2022-11-17 19:53 UTC
Labels: stage: backlog
