### ISSUE TITLE
Whoops, there is no test to run after a login on www.eyeem.com

### ISSUE THREAD

**Issue by straris** [cypress-io/cypress#7337] opened 2020-05-13 17:35 UTC
### Current behavior:
_Whoops, there is no test to run_ after a login on www.eyeem.com
Similar issues that I investigated:

- `target="_top"`, not present on the form, also tried the following workaround:

```js
Object.defineProperty(win, 'self', {
    get: () => {
      return window.top
    }
  })
```
- `"blacklistHosts": ["www.googletagmanager.com"]`

- salesforce workaround from https://github.com/cypress-io/cypress/issues/2367, the page is neither an iframe nor pointing to a separate domain

### Desired behavior:

Not crash.

### Test code to reproduce

```js
describe('login test', () => {
  it('logins', function() {
    return cy
      .visit('www.eyeem.com/login')
      .get('input[name="email"]')
      .type('cypress+eyeem@gmail.com')
      .get('input[name="password"]')
      .type('cypressEyeEm')
      .get('*[data-test-id="TEST_LOGIN_BUTTON"]')
      .click();
  });
});
```

### Versions
Cypress 4.5.0, 
Mac OS Catalina 10.15.4, 
Chrome 81, Firefox 76, Electron 80

**Comment by jennifer-shehane** [comment] 2020-05-14 06:46
I can recreate this issue from the test code provided. Here are all the [similar issues](https://github.com/cypress-io/cypress/labels/topic%3A%20%20%F0%9F%98%B3whoops%20there%20is%20no%20test%20to%20run). 

Duplicate of #3077

**Closed by jennifer-shehane** 2020-05-14 06:46 UTC
Labels: topic:  😳whoops there is no test to run
