### ISSUE TITLE
Strange requests on unresolvable domains

### ISSUE THREAD

**Issue by slawiko** [cypress-io/cypress#2209] opened 2018-07-25 10:14 UTC
Among with our requests, cypress's proxy tried to proxy another strange requests:

`proxiedUrl: 'http://bmwfhjixhmtsajt/'`
`proxiedUrl: 'http://vcgegxngiaz/'`
`proxiedUrl: 'http://oxrkldtk/'`

```sh
cypress:server:proxy handling proxied request { url: '/runtime.a66f828dca56eeb90e02.js', proxiedUrl: 'http://ourOrigin/runtime.a66f828dca56eeb90e02.js', headers: { host: 'ourOrigin', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', accept: '*/*', referer: 'http://ourOrigin/?e2e', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US,en;q=0.9', cookie: 'ourCookie' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +0ms
cypress:server:timers queuing timer id 2083 after 30000 ms +5ms
cypress:server:timers child received timer id 2083 +44ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +15ms
cypress:server:proxy handling proxied request { url: '/polyfills.0cba0d8640cf481ad710.js', proxiedUrl: 'http://ourOrigin/polyfills.0cba0d8640cf481ad710.js', headers: { host: 'ourOrigin', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', accept: '*/*', referer: 'http://ourOrigin/?e2e', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US,en;q=0.9', cookie: 'ourCookie' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +0ms
cypress:server:timers queuing timer id 2084 after 30000 ms +2ms
cypress:server:timers child received timer id 2084 +14ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +3ms
cypress:server:proxy handling proxied request { url: '/main.fefede1e40e5b31fe2f5.js', proxiedUrl: 'http://ourOrigin/main.fefede1e40e5b31fe2f5.js', headers: { host: 'ourOrigin', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', accept: '*/*', referer: 'http://ourOrigin/?e2e', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US,en;q=0.9', cookie: 'ourCookie' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +1ms
cypress:server:timers queuing timer id 2085 after 30000 ms +8ms
cypress:server:timers child received timer id 2085 +11ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +32ms
cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://bmwfhjixhmtsajt/', headers: { host: 'bmwfhjixhmtsajt', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-us,en' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +0ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +3ms
cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://oxrkldtk/', headers: { host: 'oxrkldtk', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-us,en' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +1ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +2ms
cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://vcgegxngiaz/', headers: { host: 'vcgegxngiaz', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-us,en' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +6ms
cypress:server:timers queuing timer id 2086 after 30000 ms +21ms
cypress:server:timers child received timer id 2086 +66ms
cypress:server:proxy received response for { url: 'http://ourOrigin/styles.27bb40488940a3d69ad7.css', headers: { date: 'Tue, 24 Jul 2018 14:03:34 GMT', 'content-type': 'text/css; charset=UTF-8', 'transfer-encoding': 'chunked', connection: 'close', vary: 'Accept-Encoding', 'x-powered-by': 'Express', 'cache-control': 'public, max-age=0', 'last-modified': 'Mon, 23 Jul 2018 10:27:43 GMT', etag: 'W/"21d7e-164c6ae3518"', 'content-encoding': 'gzip' }, statusCode: 200, isGzipped: true, wantsInjection: false, wantsSecurityRemoved: false } +3ms
cypress:server:timers queuing timer id 2087 after 30000 ms +10ms
cypress:server:timers child received timer id 2087 +12ms
cypress:server:timers clearing timer id 2086 from queue { '2074': { args: [], ms: 85000, cb: [Function] }, '2080': { args: [], ms: 85000, cb: [Function] }, '2083': { args: [], ms: 30000, cb: [Function] }, '2084': { args: [], ms: 30000, cb: [Function] }, '2085': { args: [], ms: 30000, cb: [Function] }, '2086': { args: [], ms: 30000, cb: [Function] }, '2087': { args: [], ms: 30000, cb: [Function] } } +8ms
cypress:server:cors Parsed URL { port: '80', tld: 'bmwfhjixhmtsajt', domain: '' } +6ms
cypress:server:proxy received response for { url: 'http://bmwfhjixhmtsajt/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +0ms
cypress:server:proxy request failed { url: 'http://bmwfhjixhmtsajt/', status: 500, error: 'Error: getaddrinfo ENOTFOUND bmwfhjixhmtsajt bmwfhjixhmtsajt:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +0ms
cypress:server:timers queuing timer id 2088 after 30000 ms +5ms
cypress:server:timers child received timer id 2088 +19ms
cypress:server:timers clearing timer id 2087 from queue { '2074': { args: [], ms: 85000, cb: [Function] }, '2080': { args: [], ms: 85000, cb: [Function] }, '2083': { args: [], ms: 30000, cb: [Function] }, '2084': { args: [], ms: 30000, cb: [Function] }, '2085': { args: [], ms: 30000, cb: [Function] }, '2087': { args: [], ms: 30000, cb: [Function] }, '2088': { args: [], ms: 30000, cb: [Function] } } +1ms
cypress:server:cors Parsed URL { port: '80', tld: 'oxrkldtk', domain: '' } +1ms
cypress:server:proxy received response for { url: 'http://oxrkldtk/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +1ms
cypress:server:proxy request failed { url: 'http://oxrkldtk/', status: 500, error: 'Error: getaddrinfo ENOTFOUND oxrkldtk oxrkldtk:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +0ms
cypress:server:timers clearing timer id 2083 from queue { '2074': { args: [], ms: 85000, cb: [Function] }, '2080': { args: [], ms: 85000, cb: [Function] }, '2083': { args: [], ms: 30000, cb: [Function] }, '2084': { args: [], ms: 30000, cb: [Function] }, '2085': { args: [], ms: 30000, cb: [Function] }, '2088': { args: [], ms: 30000, cb: [Function] } } +32ms
cypress:server:timers clearing timer id 2088 from queue { '2074': { args: [], ms: 85000, cb: [Function] }, '2080': { args: [], ms: 85000, cb: [Function] }, '2084': { args: [], ms: 30000, cb: [Function] }, '2085': { args: [], ms: 30000, cb: [Function] }, '2088': { args: [], ms: 30000, cb: [Function] } } +1ms
cypress:server:cors Parsed URL { port: '80', tld: 'vcgegxngiaz', domain: '' } +4ms
cypress:server:proxy received response for { url: 'http://vcgegxngiaz/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +1ms
cypress:server:proxy request failed { url: 'http://vcgegxngiaz/', status: 500, error: 'Error: getaddrinfo ENOTFOUND vcgegxngiaz vcgegxngiaz:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +2ms
cypress:server:timers clearing timer id 2085 from queue { '2074': { args: [], ms: 85000, cb: [Function] }, '2080': { args: [], ms: 85000, cb: [Function] }, '2084': { args: [], ms: 30000, cb: [Function] }, '2085': { args: [], ms: 30000, cb: [Function] } } +28ms
cypress:server:timers clearing timer id 2084 from queue { '2074': { args: [], ms: 85000, cb: [Function] }, '2080': { args: [], ms: 85000, cb: [Function] }, '2084': { args: [], ms: 30000, cb: [Function] } } +0ms
cypress:server:proxy received response for { url: 'http://ourOrigin/runtime.a66f828dca56eeb90e02.js', headers: { date: 'Tue, 24 Jul 2018 14:03:35 GMT', 'content-type': 'application/javascript; charset=UTF-8', 'transfer-encoding': 'chunked', connection: 'close', vary: 'Accept-Encoding', 'x-powered-by': 'Express', 'cache-control': 'public, max-age=0', 'last-modified': 'Mon, 23 Jul 2018 10:27:43 GMT', etag: 'W/"461-164c6ae3518"', 'content-encoding': 'gzip' }, statusCode: 200, isGzipped: true, wantsInjection: false, wantsSecurityRemoved: true } +116ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +3ms
cypress:server:proxy handling proxied request { url: '/styles.27bb40488940a3d69ad7.css.map', proxiedUrl: 'http://ourOrigin/styles.27bb40488940a3d69ad7.css.map', headers: { host: 'ourOrigin', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US,en;q=0.9', cookie: 'ourCookie' }, remoteState: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } } +1ms
cypress:server:timers queuing timer id 2089 after 30000 ms +12ms
cypress:server:timers child received timer id 2089 +203ms
cypress:server:proxy received response for { url: 'http://ourOrigin/polyfills.0cba0d8640cf481ad710.js', headers: { date: 'Tue, 24 Jul 2018 14:03:35 GMT', 'content-type': 'application/javascript; charset=UTF-8', 'transfer-encoding': 'chunked', connection: 'close', vary: 'Accept-Encoding', 'x-powered-by': 'Express', 'cache-control': 'public, max-age=0', 'last-modified': 'Mon, 23 Jul 2018 10:27:43 GMT', etag: 'W/"e99c-164c6ae3518"', 'content-encoding': 'gzip' }, statusCode: 200, isGzipped: true, wantsInjection: false, wantsSecurityRemoved: true } +83ms
cypress:server:server Getting remote state: { auth: null, props: { port: '80', tld: 'ourTld', domain: 'ourDomain' }, origin: 'http://ourOrigin', strategy: 'http', visiting: false, domainName: 'ourDomain', fileServer: null } +38ms
```

Our application doesn't make such requests

### Current behavior:

Cypress proxies some strange requests

### Desired behavior:

Looks like It shouldn't happen

### Steps to reproduce:

Don't really know what's the steps

### Versions

Cypress: 3.0.2
OS: macOS 10.13.4
browser: Chrome 67

**Comment by IgorNikityuk** [comment] 2018-10-09 08:05
We have the same issue
`cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://wjvffdl/', headers: { host: 'wjvffdl', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: null, props: { port: '443', tld: 'com', domain: '...' }, origin: `

**Comment by flotwig** [comment] 2019-06-13 17:05
This is from running with Google Chrome, it makes these request to try to figure out if DNS is being hijacked so it can adjust behavior. We can't change this without also adversely affecting Cypress because of the command line options exposed, but since it doesn't affect operation, it's not an issue.

Closing as duplicate of #3151

**Closed by flotwig** 2019-06-13 17:05 UTC
Labels: stage: needs investigating
