### ISSUE TITLE
[v10] Clicking on the URL doesn't open the page in a new tab anymore

### ISSUE THREAD

**Issue by damien-monni** [cypress-io/cypress#22036] opened 2022-06-02 08:14 UTC
### Current behavior

Before v10, when clicking the URL in the Chrome tester it opened the same page in a new tab.
This was especially helpful to fastly test a bug fix without losing the last test context.

From v10, nothing happens when we click on the URL.

### Desired behavior

Clicking on the URL should open the page in a new page, as before v10.

### Test code to reproduce

Open any test and click on the Chrome URL.

### Cypress Version

10.0.1

**Comment by jennifer-shehane** [comment] 2022-06-02 12:53
@damien-monni Thanks for reporting. Closing as duplicate of https://github.com/cypress-io/cypress/issues/21823

**Closed by jennifer-shehane** 2022-06-02 12:53 UTC
