### ISSUE TITLE
Using `cy.log` within a promise causes the promise to `resolve(null)`

### ISSUE THREAD

**Issue by zakhenry** [cypress-io/cypress#5365] opened 2019-10-14 10:59 UTC
### Current behavior:

Calling a simple cypress command (log) from within a wrapped promise causes the promise to return `null` with no errors or warnings.

### Desired behavior:

Either
  * the promised value should be returned (ideal)
  * exception should be thrown from cypress command that would have caused this behavior

### Steps to reproduce: (app code and test code)

```js
describe('test', () => {
  it('should work', () => {
    cyTest('value').then(res => {
      cy.log(`value is ${res}`);
      expect(res).to.be.a('string');
      expect(res).to.contain('value | resolved');
    });
  });
});

function cyTest(value) {
  return cy.wrap(value).then(wrappedValue => {
    return cy.wrap(
      new Promise((resolve, reject) => {
        // cy.log('uncomment me to break the test');
        resolve(wrappedValue + ' | resolved');
      }),
    );
  });
}

```

### Versions

$ cypress --version
Cypress package version: 3.4.1
Cypress binary version: 3.4.1

Chrome 77

MacOS

**Comment by gabbersepp** [comment] 2019-10-22 08:05
Had the same issue here: https://github.com/cypress-io/cypress/issues/3536
Would be nice, if an exception is thrown to show that something is going wrong

**Comment by jennifer-shehane** [comment] 2019-11-06 15:26
Closing as duplicate of https://github.com/cypress-io/cypress/issues/3536

**Closed by jennifer-shehane** 2019-11-06 15:26 UTC
