### ISSUE TITLE
Have error Cannot add property index.html

### ISSUE THREAD

**Issue by afferenslucem** [cypress-io/cypress#24143] opened 2022-10-06 05:19 UTC
### Current behavior

When I start component tests I always receive error: Cannot add property index.html, object is not extensible

![image](https://user-images.githubusercontent.com/18226034/194220601-841f963e-57c2-4151-ac4e-8668b1ddabfd.png)

### Test code to reproduce

there is nothing to paste

### Cypress Version

10.9.0

### Node version

14.17.5

### Operating System

Windows 10

### Debug Logs

```shell
TypeError: Cannot add property index.html, object is not extensible
    at C:\Users\a.shakirov\silvertests\src\front\silvertests-ui-kit\node_modules\html-webpack-plugin\index.js:286:49
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Other

I've just updated cypress from 9th version

**Comment by nagash77** [comment] 2022-10-06 18:41
@afferenslucem I'm sorry to hear you are having problems!  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-10-13 13:43
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-10-13 13:43 UTC
