### ISSUE TITLE
cy.trigger command cannot simulate real mouse events 

### ISSUE THREAD

**Issue by chuandeng** [cypress-io/cypress#8137] opened 2020-07-31 05:40 UTC
### Current behavior:
when we use trigger like below code the event object in page is "Event"
```js
cy.get('.target').trigger('mousedown', { button: 0 })
```
use "ev instanceof MouseEvent" in mousedown event got result of false

### Desired behavior:

When we use "ev instanceof MouseEvent" in the mousedown event callback function should get result of true

### Test code to reproduce
our coed is on below 
```js
$('div').on('mousedown', function(ev){
  if (ev instanceof MouseEvent) {
     ...
  }else {
    ...
  }
})
```

### Versions
Cypress Version 4.9
System: Mac, Catalina 10.15.5
Browser: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by mingyixu** [comment] 2020-07-31 06:53
I had the same question.

**Comment by jennifer-shehane** [comment] 2020-08-03 09:24
Duplicate of #5650

**Closed by jennifer-shehane** 2020-08-03 09:24 UTC
