### ISSUE TITLE
Special characters in URL 

### ISSUE THREAD

**Issue by Caerglad** [cypress-io/cypress#9745] opened 2020-12-13 02:26 UTC
### Current behavior
I have following url addres (using prestashop): `https://localhost/appname/zamówienie`
It's converted to `https://localhost/appname/zam%C3%B3wienie`
This address is used in product order form, each time I'm moving to next step address is replacing avery `%` sing, so final url looks like this : `https://localhost/appname/zam%C3%83%C2%B3wienie`, and is not recognized by web site.

### Desired behavior
Adress should not change, or should allow URL to contains special characters

### Versions
6.1.0

**Comment by jennifer-shehane** [comment] 2020-12-14 06:36
Uri endoding of this character should not be a problem, as all characters outside of ASCII 2 can be uri encoded and still valid. https://www.w3.org/Addressing/URL/4_URI_Recommentations.html

>each time I'm moving to next step address is replacing avery % sing, so final url looks like this : https://localhost/appname/zam%C3%83%C2%B3wienie, and is not recognized by web site.

This 'double encoding' sounds like it may be an issue though. 

- What do you mean by "I'm moving to net step"?
- What is this `https://localhost/appname/zam%C3%83%C2%B3wienie` full address supposed to be? 

Can you provide a reproducible example?

**Comment by jennifer-shehane** [comment] 2021-02-27 00:11
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-27 00:11 UTC
Labels: stage: needs information
