### ISSUE TITLE
Cypress recognizes disabled element as enabled

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#24562] opened 2022-11-07 12:03 UTC
### Current behavior

My element looks like this:
![obraz](https://user-images.githubusercontent.com/34089686/200304694-d9c18655-a76c-4bcc-a3ff-2995f103ad0e.png)

I'm checking it with this code:
![obraz](https://user-images.githubusercontent.com/34089686/200304844-5446ad14-f094-4cb7-8e57-26b136fa1ca9.png)

Response from cypress:
![obraz](https://user-images.githubusercontent.com/34089686/200305177-e38a6a5c-3d7f-4cf3-859f-c89287141f58.png)

### Test code to reproduce

`cy.get('[data-test-id="Elements.0.PersonalizeVertical"]').should('be.disabled')`

### Cypress Version

10.11.0

### Node version

14.15.1

### Operating System

Windows 11

**Comment by nagash77** [comment] 2022-11-08 19:26
Hi @zbigniewkalinowski I noticed your error message references input.jss153 where as your screenshot of your html shows class=jss128.  Is that perhaps related?

**Comment by marktnoonan** [comment] 2022-11-09 01:02
Just a note, @zbigniewkalinowski - first thanks for this report! 

I was able to assert `should('be.disabled')` with correct results on an `input` with type `checkbox` in an isolated test.  Could you created an isolated example that you can share where we can reproduce this on our end?

**Comment by marktnoonan** [comment] 2022-11-16 15:58
I'm going to close this for now since we could not reproduce with the information provided, happy to reopen if there is an example of this happening that we can test.

**Closed as completed by marktnoonan** 2022-11-16 15:58 UTC
