### ISSUE TITLE
Cypress gives "libgconf-2.so.4: cannot open shared object file" error on debian stable

### ISSUE THREAD

**Issue by oupala** [cypress-io/cypress#4568] opened 2019-06-25 22:14 UTC
```bash
>node_modules/.bin/cypress open
It looks like this is your first time using Cypress: 3.3.1

 ✖  Verifying Cypress can run /home/user/.cache/Cypress/3.3.1/Cypress
   → Cypress Version: 3.3.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/home/user/.cache/Cypress/3.3.1/Cypress/Cypress: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

----------

Platform: linux (Debian - 9.9)
Cypress Version: 3.3.1
```

The same happens with the static asset downloaded as a zip file:

```bash
>./Cypress 
./Cypress: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

There is no libgconf in cypress cache directory:

```bash
>ls /home/user/.cache/Cypress/3.3.1/Cypress/
blink_image_resources_200_percent.pak  locales
content_resources_200_percent.pak      natives_blob.bin
content_shell.pak                      pdf_viewer_resources.pak
Cypress                                resources
icudtl.dat                             snapshot_blob.bin
libffmpeg.so                           ui_resources_200_percent.pak
libnode.so                             version
LICENSE                                views_resources_200_percent.pak
LICENSES.chromium.html
```

### Desired behavior:

To run successfully!

### Versions

Platform: linux (Debian - 9.9) on a laptop with full UI installed and launched (Gnome Shell)
Cypress Version: 3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-26 08:29
Closing as duplicate of https://github.com/cypress-io/cypress/issues/1526

**Closed by jennifer-shehane** 2019-06-26 08:29 UTC
