### ISSUE TITLE
Cypress open dont show up window

### ISSUE THREAD

**Issue by aldarund** [cypress-io/cypress#2667] opened 2018-10-26 21:32 UTC
### Current behavior:
`cypress open` dont show up cypress window. It load for sometime and nothing.

`cypress run` work fine.

I did clean cache ( `c:\Users\shape\AppData\Roaming\Cypress\` & `c:\Users\shape\AppData\Local\Cypress\` ), i did reinstall cypress. No luck.

here is cypress log from `cypress open`
https://gist.github.com/aldarund/7261313ecf1a729608f4d34008914c81

There is like 4-5 Cypress.exe running after open.
And when i stop it i see shortly a blinking window ( like milliseconds)

### Desired behavior:

Cypress opens a runner and window show up

### Steps to reproduce:

just `cypress open `

### Versions
Cypress 3.1
Node 11
Windows 10 x64 
Chrome Version 71.0.3578.20 (Official Build) beta (64-bit)

**Comment by Konstruktour** [comment] 2018-10-29 09:56
are u sure that it is not opened at all? sometime i have the issue that the dashboard/runner is shown outside of the screen.

**Comment by aldarund** [comment] 2018-10-29 10:01
@Konstruktour Yes, it dont opened. There no window in task panel and as i remember there should be. The only thing that i can notice is that when i stop some window ( console window ??) blinking and thats all.

**Comment by jennifer-shehane** [comment] 2018-10-30 17:19
Hey @aldarund, can you run `cypress open` with another project, like our [`cypress-example-kitchensink`](https://github.com/cypress-io/cypress-example-kitchensink)? 

I would like to know if it is related to your project's test code or not.

**Comment by aldarund** [comment] 2018-10-30 17:41
@jennifer-shehane it is not related to project code, it was working before on same code. I tried on your linked repo and its same behaviour.
Let me know what else i can provide to help debug it :)

**Comment by zerdos** [comment] 2018-10-31 14:41
The problem is node 11, on windows environment. Works fine with node 10.3

**Comment by zerdos** [comment] 2018-10-31 15:56
maybe related:
https://github.com/nodejs/node/pull/21316

**Comment by zerdos** [comment] 2018-10-31 17:47
Yes, adding windowsHide in the spawn options (cypress/cli/lib/exec/spawn.js, line 90), solves the problem in windows with node 11.

I will send a PR later;)

**Comment by ryanwmarsh** [comment] 2018-11-05 07:18
Having the same issue here. Node 11 + Windows 10 + Cypress 3.1.1

Running `node_modules\.bin\cypress open` doesn't show the browser. `cypress run` works fine.

**Comment by zerdos** [comment] 2018-11-07 14:01
PR added.

**Comment by Liverpudlian** [comment] 2018-11-07 14:07
Awesome, just experiencing this issue now 👍

**Comment by chrisbreiding** [comment] 2018-11-13 17:59
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://docs.cypress.io/guides/references/changelog.html) when it's released.

**Comment by brian-mann** [comment] 2018-11-19 10:23
Released in [`3.1.2`](https://docs.cypress.io/guides/references/changelog.html#3-1-2).

**Comment by aldarund** [comment] 2018-11-20 10:38
@brian-mann @chrisbreiding 3.1.2 dont fix the issue. Your latest refactoring to that PR broken it again.. After them you are setting windowsHide to getEnvOverrides which ends up into env vars and it dont work.

**Comment by xiaoxu12** [comment] 2018-11-21 07:10
Why not show up windows?When do you want to solve it. It also can not open chrome in window 10

**Comment by Bkucera** [comment] 2018-11-28 20:51
the problem is we set `windowsHide` as a prop of `options.env`, when it should be a prop of `options`
nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

I'll open up a PR to fix this

**Closed** 2018-12-03 02:03 UTC
Labels: OS: windows

**Comment by brian-mann** [comment] 2018-12-03 17:42
Released in [`3.1.3`](https://docs.cypress.io/guides/references/changelog.html#3-1-3).

**Comment by Pascalmh** [comment] 2019-09-19 11:05
In case this still happens you can Shift + Right Click on the Icon in the Toolbar an then click Maximize - that should bring the Window into the foreground and your are able to use it.

**Comment by grzegorz-jazurek** [comment] 2019-10-04 16:17
> In case this still happens you can Shift + Right Click on the Icon in the Toolbar an then click Maximize - that should bring the Window into the foreground and your are able to use it.

@Pascalmh thanks man!

**Comment by PawelEpicode** [comment] 2020-04-20 10:08
@grzegorz-jazurek you saved my life :)

**Comment by randomcoggles** [comment] 2021-03-01 13:51
In my case I had to uninstall Cypress and kill cypress folder in AppData folder(Kill all caches)

**Comment by vibes121** [comment] 2021-09-27 16:22
@grzegorz-jazurek you save my life too:-)

**Comment by slappinlappin** [comment] 2021-11-16 13:41
> In case this still happens you can Shift + Right Click on the Icon in the Toolbar an then click Maximize - that should bring the Window into the foreground and your are able to use it.

This has saved me so many times. Thank you

**Comment by sanjshrestha** [comment] 2022-01-06 07:21
how to fix this one i faced this issue

**Comment by sanjshrestha** [comment] 2022-01-06 07:22
> how to fix this one i faced this issue

how to fix this one i faced this issue

**Comment by Harsh-Personal** [comment] 2022-02-14 16:08
Any resolution for mac on this?

**Comment by Shw07** [comment] 2022-06-06 16:58
I am also facing same issue. Cypress window is blinking for a sec then closed

**Comment by abdullahsl2** [comment] 2022-06-10 06:45
> @Konstruktour Yes, it dont open. There no window in task panel and as i remember there should be. The only thing that i can notice is that when i stop some window ( console window ??) blinking and thats all.

i have also face this issue have you solved it

**Comment by Dark212302** [comment] 2022-06-17 07:41
I am also facing the same issue 
I have use the npx cypress open but it open and close after some time.
But if we change the version it will support the same command.

**Comment by rajendran-k** [comment] 2022-07-01 05:28
After upgrading to cypress 10.3.0 am seeing this issue in Windows. It does open but window is laying somewhere else and cant focus to it. Current hack am using is Shift+ Right click and then maximize.

**Comment by saimahanif38** [comment] 2022-09-01 07:08
having the same issues resolved by this "Current hack am using is Shift+ Right click and then maximize."

**Comment by alexcatanet** [comment] 2022-09-27 09:38
@Pascalmh, thx for the workaround, it's working but I'm still wondering why it was working before (I'm using the same machine as before) and now, after a while, it's failing to work properly when running '`npm run cypress:open`' in bash 

I'm using Cypress vers. 9.7.0

**Comment by gtugwell** [comment] 2022-09-30 14:26
Yeah, also experiencing this same issue on Windows 11, running cypress version 10.7.0, 10.8.0, and 10.9.0. Was able to get it back into focus by doing the Shift + Right click and selecting maximize as well.

**Comment by tripathi040** [comment] 2022-10-17 08:11
Facing the same issue on 17 october 2022. Was able to get it back into focus by doing the Shift + Right click and selecting maximize as well. 

====update====
After few runs it is fixed on its own

**Comment by sherryysj** [comment] 2022-10-27 23:22
> Facing the same issue on 17 october 2022. Was able to get it back into focus by doing the Shift + Right click and selecting maximize as well.
> 
> ====update==== After few runs it is fixed on its own

Thanks! This is really helpful!!

**Comment by AishwaryaRavindra** [comment] 2023-01-13 10:30
when i Give this _npx cypress open_   command, In a Visual studio code editor terminal, the cypress test runner window is opening, but it is not visible[not able to open] i can see the Cypress window icon only in Taskbar.

**Comment by kamiljjaworski** [comment] 2023-01-31 13:26
Hover over the cypress icon on your task bar and you'll see the mini-window of cypress UI. Right-click on that mini-window and click "maximize"

**Comment by AishwaryaRavindra** [comment] 2023-02-02 12:22
> Hover over the cypress icon on your task bar and you'll see the mini-window of cypress UI. Right-click on that mini-window and click "maximize"

yes, i got it ..Thanks for the Solution......

**Comment by gracewang129** [comment] 2023-02-07 20:52
Ok, turned out it was on my laptop screen, I I turned that off but it reset itself after I reconnected the monitor, and my laptop was closed so I can't see it.

**Comment by AishwaryaRavindra** [comment] 2023-03-01 10:08
how to write the code for Capturing the error message in cypress.

**Comment by madmacc** [comment] 2023-11-13 18:36
> Facing the same issue on 17 october 2022. Was able to get it back into focus by doing the Shift + Right click and selecting maximize as well.
> 
> ====update==== After few runs it is fixed on its own

Great answer, worked for me with Cypress 13.
