### ISSUE TITLE
Cypress test not getting triggered automatically after updating the file apart from spec file

### ISSUE THREAD

**Issue by nitish-Datman** [cypress-io/cypress#23137] opened 2022-08-05 12:56 UTC
### Current behavior

Cypress test not getting triggered automatically after updating the file apart from spec file, 
its only only running instantly for any of the .spec file for not for any other .js class file

### Desired behavior

its should be running instantly for any file update 

### Test code to reproduce

describe("test file save", function () {
 
  it("test", function () {
}
})

### Cypress Version

10.3.1

### Other

running in chrome

**Comment by rockindahizzy** [comment] 2022-08-08 17:21
Hey @nitish-Datman,

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-15 18:28
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-15 18:28 UTC
Labels: stage: awaiting response, Needs Reproduction
