### ISSUE TITLE
callCount is incorrect when using cy.stub().callsFake() for React component testing

### ISSUE THREAD

**Issue by 787681277** [cypress-io/cypress#26549] opened 2023-04-20 05:28 UTC
### Current behavior

callCount is 2 when click to trigger cy.stub().callsFake()
<img width="535" alt="Screen Shot 2023-04-20 at 13 27 13" src="https://user-images.githubusercontent.com/26969223/233266506-27b1c051-8d8b-4aad-acdd-4407f896fb93.png">
<img width="536" alt="Screen Shot 2023-04-20 at 13 27 37" src="https://user-images.githubusercontent.com/26969223/233266570-8140e5cd-85fe-48c0-b1c6-786ab680ad08.png">

### Desired behavior

callCount should be 1 when click to trigger cy.stub().callsFake()
stub-2 should not be displayed

### Test code to reproduce

    const SwitchButtonSample = () => {
      const [checked, setChecked] = React.useState<boolean>(false);
      const changeValue = (checked: boolean) => {setChecked(checked);console.log('123456');}
      const onChange = cy.stub().as('birthday').callsFake(changeValue);

      return (
        <Switch onChange={onChange} checked={checked} >Label</Switch>
      );

    }
  
    cy.mount(<SwitchButtonSample />); 
    cy.get(SwitchBtn).click();
    cy.get('@birthday').should('have.been.calledOnce');

### Cypress Version

12.9.0

### Node version

v14.20.0

### Operating System

macOS 12.6

**Comment by mike-plummer** [comment] 2023-04-20 14:54
@787681277 In your example, you're calling `cy.stub` in `SwitchButtonSample`'s render function, so it will get regenerated on every component render. Generally you would use Cypress APIs in your spec file, not within your components - you would pass a stub in as a prop to `SwitchButtonSample` from your spec

In your example it seems like you aren't actually using the stub for anything other than tracking a state change, but you can just as easily assert against the rendered output to validate your change handler was called

**Comment by 787681277** [comment] 2023-04-24 12:56
@mike-plummer  Thanks for your suggestion that Pass a stub in as a prop to SwitchButtonSample from my spec. In the meantime, setValue in my component 
const SwitchButtonSample = (props) => {

  const [checked, setChecked] = React.useState<boolean>(false);
  const changeValue = (checked: boolean) => {
       props.onChange(checked);
      setChecked(checked);
      }

  return (

    <Switch onChange={changeValue}  checked={checked} > Label </Switch>

  );

}

const onChange = cy.stub().as('birthday');
cy.mount(<SwitchButtonSample onChange={onChange} />); 

cy.get(SwitchBtn).click();
cy.get('@birthday').should('have.been.calledOnce');

**Comment by mike-plummer** [comment] 2023-04-24 14:06
@787681277 Your state is internal to the component itself, typically you would pass in an `onUpdate` prop which could utilize a stub as a state update callback:

```ts
// SwitchWrapper.tsx
type SwitchWrapperProps = {
  onUpdate?: (value: boolean) => void
}
const SwitchWrapper: React.FC<SwitchWrapperProps> = (props) => {
  const [checked, setChecked] = React.useState<boolean>(false);
  const onChange = React.useCallback((checked: boolean) => {
    props.onUpdate?.(checked)
    setChecked(checked)
  }, [props.onUpdate])

  return (
    <Switch onChange={onChange} checked={checked}>Label</Switch>
  );
}
```

```ts
// SwitchWrapper.spec.tsx
const onUpdateStub = cy.stub().as('switch-updated');
cy.mount(<SwitchWrapper onUpdate={onUpdateStub} />);

cy.get(SwitchBtn).click();
cy.get('@switch-updated').should('have.been.calledOnce');
```

Since this is not a bug in Cypress I am going to close this issue. If you need help using Cypress I recommend referencing our [Documentation](https://docs.cypress.io/) (there are some [good examples specific to React](https://docs.cypress.io/guides/component-testing/react/examples)), or utilize our [Discord community](https://on.cypress.io/chat) if you have a question not addressed by the documentation.

**Closed as not planned by mike-plummer** 2023-04-24 14:06 UTC
