### ISSUE TITLE
click does not work if an element has zero width / height element inside of it

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7012] opened 2020-04-14 17:12 UTC
Cypress 4.4.0

HTML

```html
<a href='#' className='learn-more' onClick={openProjectIdHelp}>
   <i className='fas fa-info-circle'></i>{' '}
   Learn more
</a>
```

Test code

```js
cy.contains('a', 'Learn more').click()
```

The click command happens BUT it does not reach the `onClick` handler in the `a` element. 

<img width="873" alt="Screen Shot 2020-04-14 at 1 01 02 PM" src="https://user-images.githubusercontent.com/2212006/79252710-0d122d80-7e50-11ea-94b4-4408986d1138.png">

Seems the mouse click happens on the edge of the found element, not inside of it

<img width="850" alt="Screen Shot 2020-04-14 at 1 01 58 PM" src="https://user-images.githubusercontent.com/2212006/79252768-21562a80-7e50-11ea-9f39-8f4625e4ec49.png">

and thus the click event goes into parent "div"

<img width="1102" alt="Screen Shot 2020-04-14 at 1 02 23 PM" src="https://user-images.githubusercontent.com/2212006/79252793-303cdd00-7e50-11ea-9963-abd75d97da1e.png">

After digging into the mouse click handlers got to `coordinates.js`

```js
const getElementPositioning = ($el) => {
  ...
  const rect = el.getClientRects()[0] || el.getBoundingClientRect()
```

For our element, `el.getClientRects()` returns _two rectangles_.

<img width="996" alt="Screen Shot 2020-04-14 at 1 06 09 PM" src="https://user-images.githubusercontent.com/2212006/79253192-ca048a00-7e50-11ea-9261-82a7398091a6.png">

The first rectangle is from `<i>` element with no width, the second from the text inside the `a` element.

<img width="780" alt="Screen Shot 2020-04-14 at 1 07 45 PM" src="https://user-images.githubusercontent.com/2212006/79253321-fe784600-7e50-11ea-9a3f-2d796e17dd9c.png">

We can recreate the behavior by putting an empty span

```html
<a href='#' className='learn-more' onClick={openProjectIdHelp}>
  <span></span>
  Learn more
</a>
```

<img width="890" alt="Screen Shot 2020-04-14 at 1 09 13 PM" src="https://user-images.githubusercontent.com/2212006/79253464-4008f100-7e51-11ea-9761-fd957fce9ae8.png">

## Proposal

- look at the list of returned client rectangles, not just at the first one. A simple check would be to skip the rectangles with `width:0` or `height:0`. A more robust check would be to get the coordinates and then check which element at those coordinates would receive the event. In our case, it would be parent `div`, because the first element has zero dimension.

**Comment by jennifer-shehane** [comment] 2020-05-18 08:00
I can't recreate this from the example provided. Can you give a fully reproducible example outside of React? I'd like to exclude this being an issue with the component test trying to track the event listeners.

My example:

`index.html`

```html
<html lang="en">
<body>
<a id='link'>
  <span></span>
  Learn more
</a>
<p id='demo'></p>
</body>
<script>
  document.getElementById('link').onclick = function changeContent() {
    document.getElementById('demo').innerHTML = "Click happened!"
  }
</script>
</html>
```

`spec.js`

```js
  it('test', () => {
    cy.get('#demo').should('not.contain', 'Click happened')
    cy.visit('index.html')
    cy.get('#link').click()
    cy.get('#demo').should('contain', 'Click happened')
  })
```

<img width="706" alt="Screen Shot 2020-05-18 at 2 30 04 PM" src="https://user-images.githubusercontent.com/1271364/82188579-15a8c880-9914-11ea-8abb-21b85f7a30f5.png">

**Comment by bahmutov** [comment] 2020-05-20 15:08
ughh, trying to recreate this without luck. The click still happens on `<i>` with width 0, but does propagate to the top `<a>` element

**Comment by bahmutov** [comment] 2020-05-20 15:18
The original issue was in file packages/desktop-gui/src/settings/project-id_spec.jsx There is a test that if you disable styles would have empty `<i>`

```
  it.only('calls load more', () => {
    cy.stub(ipc, 'externalOpen').as('externalOpen')
    mount(<ProjectId project={project} />, {
      // stylesheets: '/__root/dist/app.css',
    })

    cy.contains('a', 'Learn more')
    .click()

    cy.get('@externalOpen').should('have.been.called')
  })
```

But now I see it passing, so something has changed in how the event click propagates

<img width="1138" alt="Screen Shot 2020-05-20 at 11 16 46 AM" src="https://user-images.githubusercontent.com/2212006/82464053-9b9b4f80-9a8b-11ea-8515-324b84de1fb6.png">

<img width="1139" alt="Screen Shot 2020-05-20 at 11 17 05 AM" src="https://user-images.githubusercontent.com/2212006/82464066-a0600380-9a8b-11ea-90da-d8e7f012f036.png">

So for now - it still uses wrong coordinates (first zero-width span), but I don't see the impact of it

**Comment by panzarino** [comment] 2020-05-20 21:54
@jennifer-shehane so it took me quite a while to reproduce this issue but I discovered that the 0 width child element must not have `display: inline`. In this case the child element is not returned by `getClientRects()`. In my PR I show an example with `display: inline-block`, which does accurately reproduce the issue.

**Comment by jennifer-shehane** [comment] 2020-05-21 06:08
@panzarino I still don't see this recreating the issue here of not *clicking*. There is a warning on click that shows without the PR, which was not the original issue. 

```js
it('click 0 rect', () => {
  cy.visit('index.html')
  cy.get('#overflow-link-width').click()
  cy.get('#demo').should('contain', 'Click happened!')
})
```

```html
<html>
<body>
  <div style="width: 30px; line-height: 2;">
    <a href="#" id="overflow-link-width">
      <i style="display: inline-block;"></i>
      foofoofoofoofoo bar
    </a>
  </div>
  <div id="demo"></div>
</body>
<script>
  document.getElementById('overflow-link-width').onclick = () => {
    document.getElementById('demo').innerHTML = "Click happened!"
  }
</script>
</html>
```

<img width="609" alt="Screen Shot 2020-05-21 at 12 37 37 PM" src="https://user-images.githubusercontent.com/1271364/82528935-dec6f280-9b5f-11ea-93f0-3c151e758f60.png">

I'm in favor of closing this issue as not reproducible and opening your other issue - which your PR is fixing. It should click instead of showing the warning.

**Comment by Bkucera** [comment] 2020-06-01 16:13
accidentally closed in #7344, but that may address this issue as well. Reopening for now, however we will have to close if we cannot get a reproducible

**Comment by jennifer-shehane** [comment] 2020-06-02 08:08
I'm just gonna close this since we don't have a repro. Reopen is an repro is provided.

**Closed by jennifer-shehane** 2020-06-02 08:08 UTC
Labels: pkg/driver, stage: pending release, topic: cy.click 🖱, type: bug

**Comment by brian-mann** [comment] 2020-06-08 08:29
This issue is fixed by the PR. I could reproduce by forcing the `<a>` to break across multiple lines. This can be achieved by wrapping it with a parent element that has a set `width` smaller than the width that the `<a>` displaces.

**Comment by jennifer-shehane** [comment] 2020-06-08 08:33
So I'm able to recreate this by forcing the click in the [example I gave above](https://github.com/cypress-io/cypress/issues/7012#issuecomment-631901822) which shows the click is not happening in the center of the element. 

<img width="751" alt="Screen Shot 2020-06-08 at 3 00 29 PM" src="https://user-images.githubusercontent.com/1271364/84009309-15db3780-a999-11ea-9557-d4fa2fd361a7.png">

**Comment by jennifer-shehane** [comment] 2020-06-08 08:34
The code for this is done in [cypress-io/cypress#7344](https://github.com/cypress-io/cypress/pull/7344), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
