### ISSUE TITLE
--spec order is not respected. Defaults to alphabetical execution.

### ISSUE THREAD

**Issue by diggabyte** [cypress-io/cypress#15510] opened 2021-03-16 03:11 UTC
Ordering of the `--spec` argument is not respected. This is critical for our use case as it pertains to optimization / balancing of our suites to distribute evenly across workers. This should be a simple fix... just don't sort the spec arguments by alpha.

### Current behavior
Does not respect the order of `--spec`, always runs specs in alphabetized order

```
 $ yarn cypress run --spec \
   cypress/integration/defect/c.ts,cypress/integration/defect/b.ts,cypress/integration/defect/a.ts
```
Input specs are a specific order:
![image](https://user-images.githubusercontent.com/857573/111249837-f7623680-85d1-11eb-81b8-be627f80ec34.png)

Actual spec execution is alphabetized:
![image](https://user-images.githubusercontent.com/857573/111249879-0517bc00-85d2-11eb-8f7b-d2023c81420f.png)

`

### Desired behavior
Respect the order passed via `--spec` and do not alphabetize the run order

### Test code to reproduce
Just rename some tests, easy to reproduce

### Versions
6.5.x, 6.6.x, possibly much, much older

**Comment by diggabyte** [comment] 2021-03-16 03:19
Verification the actual run order is alphabetized.. so it's not just presentation of the test results:

![image](https://user-images.githubusercontent.com/857573/111250969-f3cfaf00-85d3-11eb-9db0-795acf6cdd8d.png)

![image](https://user-images.githubusercontent.com/857573/111250989-fc27ea00-85d3-11eb-8d07-f9cb36c6a5d4.png)

![image](https://user-images.githubusercontent.com/857573/111251003-02b66180-85d4-11eb-98d6-246635145b9e.png)

**Comment by jennifer-shehane** [comment] 2021-03-16 13:01
This is by design. Duplicate of https://github.com/cypress-io/cypress/issues/390

**Closed by jennifer-shehane** 2021-03-16 13:01 UTC

**Comment by diggabyte** [comment] 2021-03-16 14:51
Additional context added to comment on original issue: https://github.com/cypress-io/cypress/issues/390#issuecomment-800325661

**Comment by diggabyte** [comment] 2021-03-16 14:54
@jennifer-shehane we should be able to place failing tests first to save developers time. CI can be painfully slow waiting for results if you have a failing test that happens to be alphabetically last. Additional context provided on the original issue here: https://github.com/cypress-io/cypress/issues/390#issuecomment-800325661

**Comment by jennifer-shehane** [comment] 2021-05-05 18:19
@diggabyte As part of Cypress’s [new pricing](https://www.cypress.io/blog/2021/03/16/new-pricing-that-scales-seamlessly/), we’ve included the ability to [cancel test runs when a test fails](https://on.cypress.io/smart-orchestration#Cancel-test-run-when-a-test-fails). This setting is accessible from the Dashboard for organizations starting at the [Business Plan](https://www.cypress.io/pricing/).

This offers a solution for those running tests using the Cypress Dashboard - and also ensures a parallelized run is cancelled so that all parallel running specs will also be cancelled to save time on the run.

**To get this feature, you will need to update to Cypress 6.8.0 and also be a member of an organization subscribed to a [Business Plan](https://www.cypress.io/pricing/).**

---

This feature was implemented with parallelized runs in the Dashboard in mind since this was the hardest use case to address. We had to build this feature specifically to continue to receive all of the tests in a cancelled run to ensure proper reporting. Now that we have a mechanism to cancel runs across these channels of communication, we can now consider a way to initiate cancelling test runs when a test fails from the Test Runner when not recording to the Dashboard. (Likely this would be implemented by some CLI flag or config specifying `cancelOnFailures: true)

**See this issue https://github.com/cypress-io/cypress/issues/518 on addressing the use case of cancelling test runs when a test fails from the Test Runner when not recording to the Dashboard.**
