### ISSUE TITLE
Cypress can't access different ports on same domain

### ISSUE THREAD

**Issue by mankinchi** [cypress-io/cypress#6475] opened 2020-02-16 23:36 UTC
### Current behavior:
What I have is 2 tests (initially 1) looks like this

Application port (1):
<img width="340" alt="Screen Shot 2020-02-17 at 10 14 28 am" src="https://user-images.githubusercontent.com/8164063/74614704-5145c200-516e-11ea-8ba1-f8cf9b88060a.png">

Authentication port (2) (previously is going straight to the website and fill it in, but I switch to use `cy.request` instead):
<img width="376" alt="Screen Shot 2020-02-17 at 10 14 31 am" src="https://user-images.githubusercontent.com/8164063/74626924-625df580-51a5-11ea-8aae-663426a6e494.png">

Additional code:
<img width="390" alt="Screen Shot 2020-02-17 at 10 15 41 am" src="https://user-images.githubusercontent.com/8164063/74614903-0fb61680-5170-11ea-9b37-5b7cb3dd9dbc.png">

So if I put (1) before (2), this error shows up:
```
CypressError: cy.request() failed trying to load:

http://localhost:8888/login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:8888

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8888/login

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

RequestError: Error: connect ECONNREFUSED 127.0.0.1:8888
    at new RequestError (/Users/tringuyen/Library/Caches/Cypress/4.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/tringuyen/Library/Caches/Cypress/4.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/tringuyen/Library/Caches/Cypress/4.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/tringuyen/Library/Caches/Cypress/4.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.onRequestError (/Users/tringuyen/Library/Caches/Cypress/4.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:208:15)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

And if I put (2) before (1), this error shows up:
```
    CypressError: cy.visit() failed trying to load:

http://localhost:8000/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED ::1:8000

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ECONNREFUSED ::1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
```

### Desired behavior:
Accessing both ports doesn't end up with error

### Test code to reproduce
- Create 2 different ports using PHP (8000, 8888)
- Have cypress try to access both of them

### Versions
Cypress: 4.0.2
Mac: 10.15.2

### Additional 
I found a similar issue here: https://stackoverflow.com/questions/60031340/cypress-login-command-with-cy-request-causes-subsequent-cy-visit-to-fail

**Comment by jennifer-shehane** [comment] 2020-02-18 06:13
I'm not able to recreate this. I have 2 local servers running and there are no errors accessing them. I even added the extra config options although I think it's unnecessary. Tried `cypress run` and `cypress open`. 

Can you access the domain normally, via curl within your environment? What is the result of running `curl yourdomain.com`? Can you access the domain via a normal [Node http.request](https://nodejs.dev/making-http-requests-with-nodejs) within the environment? Knowing the results of these will help narrow down if this is a network issue inside or outside of Cypress.

---

Code I ran:


```js
it('visit', () => {
  cy.visit('http://localhost:2222', {
    failOnStatusCode: false
  }) 
})

it('request', () => {
  cy.request({
    method: 'POST',
    url: 'http://localhost:8080',
    form: true,
    followRedirect: false,
    body: {
      username: '',
      password: ''
    }
  })
})
```

<img width="497" alt="Screen Shot 2020-02-18 at 12 42 15 PM" src="https://user-images.githubusercontent.com/1271364/74708873-1f0a9200-524c-11ea-8d5b-a094f45806f8.png">

**Comment by mankinchi** [comment] 2020-02-18 06:59
hi @jennifer-shehane , thanks for your reply.

1. I'm not using Node to build this application so I can't try http.request
2. This is the result of `curl localhost:8000`
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='../login?returnURL=%2F'" />

        <title>Redirecting to ../login?returnURL=%2F</title>
    </head>
    <body>
        Redirecting to <a href="../login?returnURL=%2F">../login?returnURL=%2F</a>.
    </body>
</html>%    
```
And this is of `curl localhost:8888`
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='/login?returnURL=%2F'" />

        <title>Redirecting to /login?returnURL=%2F</title>
    </head>
    <body>
        Redirecting to <a href="/login?returnURL=%2F">/login?returnURL=%2F</a>.
    </body>
</html>%                                                                                                                     
```

They might look similar but they are different.

3. When I run the test, I have tried to open a new tab in the browser controlled by Cypress and put the url in. It resulted in the same error. Doing this with my normal Chrome browser yield no error

**Comment by Sumedh-k** [comment] 2020-02-18 11:29
Do you see anything different in the server logs when Cypress is running the tests?

also try http://127.0.0.1:8888

**Comment by mankinchi** [comment] 2020-02-19 00:16
@Sumedh-k the request never reaches my server :( so nothing is shown on the error server. `127.0.0.1:8888` actually works, but since `127.0.0.1` and `localhost` are being treated as 2 separated domain, cookies are not being set correctly

**Comment by jennifer-shehane** [comment] 2020-02-20 10:22
@mankinchi Are you behind a corporate proxy? Do you have any proxy configuration set up? https://on.cypress.io/proxy-configuration

**Comment by mankinchi** [comment] 2020-02-21 05:20
@jennifer-shehane I am not using any proxy nor connecting to any proxy in my company

**Comment by mankinchi** [comment] 2020-03-16 01:20
Is there any update on this?

**Comment by jennifer-shehane** [comment] 2022-04-08 18:45
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 18:45 UTC
Labels: stage: needs investigating

**Comment by VenatusSimpleX** [comment] 2022-07-26 20:17
Hi, I can confirm that it still doesn't work...

Port 8080 is running, viewable in normal browser/postman:
![image](https://user-images.githubusercontent.com/31540342/181103848-1375c0e2-1136-4671-af5d-9917ad685db9.png)

Not viewable in cypress browser (chrome):
![image](https://user-images.githubusercontent.com/31540342/181103974-920a5251-d9be-4692-8181-597257d82a73.png)

Says that connection refused, even though it can be accessed elsewhere that isn't cypress:
![image](https://user-images.githubusercontent.com/31540342/181104056-da9c3a32-8e72-4f23-8c52-bc0158fd3634.png)

**Comment by Sergiobop** [comment] 2022-08-31 13:41
Happens to me too 

It there any workaround?

@jennifer-shehane

**Comment by lmiller1990** [comment] 2023-03-23 03:45
I am trying to help another use debug it here: https://github.com/cypress-io/cypress/issues/26154#issuecomment-1480546653. I couldn't make a minimal reproduction, but the user there suggested a work around when they encountered this issue. I wonder if it's windows specific?

**Comment by josephkabba** [comment] 2023-03-24 14:51
I am using fedora 35 and am also have the same issue

**Comment by lmiller1990** [comment] 2023-03-26 21:57
Take a look at #26154 @josephkabba. Can you provide a minimal reproduction? You could share it there.

**Comment by josephkabba** [comment] 2023-03-27 07:24
Thanks @lmiller1990 #26154 helped solve the issue
