### ISSUE TITLE
Scrollbar and mouseover issues

### ISSUE THREAD

**Issue by jaimefps** [cypress-io/cypress#22851] opened 2022-07-19 18:42 UTC
### Current behavior

I need to very carefully place the mouse pointer to the left hand side of the scroll bar to actually use it. 
When hovering over the scrollbar itself, it turns into the "increase-decrease" mouse drag thing.

### Desired behavior

I wish the mouse would work normally on TOP of the scrollbar, and that the increase-decrease size mouse thing would be the one that requires carefully placing the mouse to the right-hand side of the scrollbar. 

### Test code to reproduce

See loom for example: https://www.loom.com/share/9699e9402fc54fd2821be9c111882d64

### Cypress Version

10

**Comment by mjhenkes** [comment] 2022-07-19 19:18
Duplicate of https://github.com/cypress-io/cypress/issues/22608

**Closed by mjhenkes** 2022-07-19 19:18 UTC
