### ISSUE TITLE
Cypress cannot interpret multiple arguments on the command line to change viewports, when there are already viewports configured by default

### ISSUE THREAD

**Issue by raulpacheco2k** [cypress-io/cypress#29007] opened 2024-02-25 04:34 UTC
### Current behavior

At the moment, the `cypress.config.js` file looks like this:

```
module.exports = defineConfig({
    viewportWidth: 1920,
    viewportHeight: 1080,
    e2e: {
        setupNodeEvents(on, config) {
            // implement node event listeners here
        },
    },
});
```

And I'm trying to change the vieport through the command line, using `cypress open --config viewportWidth=1280,viewportHeight=720`. However, the following message is displayed:

![image](https://github.com/cypress-io/cypress/assets/61039190/fdf5d207-b27f-4ca7-84b3-76714788dbc3)

Interestingly, if I change the dotcom file to this form:

```
module.exports = defineConfig({
    e2e: {
        viewportWidth: 1920,
        viewportHeight: 1080,
        setupNodeEvents(on, config) {
            // implement node event listeners here
        },
    },
});
```

Cypress does not display an error message, but it also does not change the viewport as determined by the command line.

### Desired behavior

I understand that when defining a value for the viewport via the command line, this value should over write the defining values ​​by default in the `cypress.config.js` file.

### Test code to reproduce

https://github.com/raulpacheco2k/Curso-TAT-Cypress-Basico

### Cypress Version

13.6.3

### Node version

21.4.0

### Operating System

Windows 11 Home Single Language 22631.3155

### Debug Logs

```shell
PS C:\Users\eu\Documents\Curso-TAT-Cypress-Basico> cypress open --config viewportWidth=1280,viewportHeight=720


DevTools listening on ws://127.0.0.1:49737/devtools/browser/aeea8c28-001b-4fdc-98ce-2584c80b52b2


> Annotation: No error message in the console
```

**Comment by MikeMcC399** [comment] 2024-02-25 13:23
@raulpacheco2k 

I can't reproduce your issue. 

What happens if you execute the following using `npx`?

```shell
npx cypress open --config viewportWidth=1280,viewportHeight=720
```

It looks like you may have Cypress installed globally in addition. It's [recommended to install](https://docs.cypress.io/guides/getting-started/installing-cypress#Installing) locally only:

```shell
npm install cypress --save-dev
```

**Comment by raulpacheco2k** [comment] 2024-02-25 14:54
@MikeMcC399 , thanks for your response.

Excellent, that's how it works. I was following the [Cypress documentation](https://docs.cypress.io/guides/references/configuration#:~:text=cypress%20run%20%2D%2Dbrowser%20firefox%20%2D%2Dconfig%20viewportWidth%3D1280%2CviewportHeight%3D720), it does not specify the npx parameter in the command. Maybe it's because you don't need npx to run the script in headless mode...

I'm new to Cypress, so I might end up saying nonsense. 

I believe there may be an error in the documentation, the npx parameter must be added to the command line. When running the command requested in the documentation an error is thrown, but when adding npx it works successfully.

```
PS C:\Users\eu\Documents\Curso-TAT-Cypress-Basico> cypress run --browser chrome --config viewportWidth=1280,viewportHeight=720


DevTools listening on ws://127.0.0.1:54550/devtools/browser/5a0e387b-d3ee-46e0-ba08-a56ec59283eb
An invalid configuration value was set.

Expected viewportWidth to be a number.

Instead the value was: "1280 viewportHeight=720"
PS C:\Users\eu\Documents\Curso-TAT-Cypress-Basico> npx cypress run --browser chrome --config viewportWidth=1280,viewportHeight=720


DevTools listening on ws://127.0.0.1:54560/devtools/browser/ce29aa2a-d939-4081-b77c-c02976aebd5f

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.6.3                                                                         │
  │ Browser:        Chrome 121 (headless)                                                          │
  │ Node Version:   v21.4.0 (C:\Program Files\nodejs\node.exe)                                     │
  │ Specs:          1 found (CAC-TAT.cy.js)                                                        │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


```

**Comment by MikeMcC399** [comment] 2024-02-25 15:19
@raulpacheco2k 

It's good to hear that your problem is solved!

The command you need to run depends on which package manager you are using, so all the commands are listed without `npx`, `yarn` or `pnpm`. This is explained in the documentation.

---
See [Getting Started > Opening the App](https://docs.cypress.io/guides/getting-started/opening-the-app#cypress-open). If you are using npm, then you use `npx`:

## `cypress open`

You can open Cypress from your **project root** one of the following ways:

**Using `npx`**

```shell
npx cypress open
```

**Or by using `yarn`**

```shell
yarn run cypress open
```

After a moment, the Cypress Launchpad will open.

---
See also [Guides > Command Line > How to run commands](https://docs.cypress.io/guides/guides/command-line#How-to-run-commands):

## How to run commands

For brevity we've omitted the full path to the cypress executable in each command's documentation.

To run a command, you'll need to prefix each command in order to properly locate the cypress executable.

```
npx cypress run
```

...or by using Yarn...

```
yarn cypress run
```

**Comment by MikeMcC399** [comment] 2024-02-25 16:04
@raulpacheco2k 

Since this is not a Cypress bug, you should close this issue now.

The Cypress technical community on Discord welcomes new users

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

You can share your problems and get advice from other users there.

**Closed as completed** 2024-02-25 16:05 UTC
