### ISSUE TITLE
Cypress timesout setting cookie

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#931] opened 2017-11-18 21:08 UTC
- Operating System: win10
- Cypress Version: 1.0.3
- Browser Version: 62

### Is this a Feature or Bug?

Bug

### Current behavior:

When running tests headlessly they run very slow. Failed once like this so far
![image](https://user-images.githubusercontent.com/2848185/32984767-c71f708c-cc7a-11e7-845e-cd47d3b190f8.png)

#### Test code:

```js

```

**Comment by jennifer-shehane** [comment] 2017-11-20 15:04
Would it be possible for you to provide any more about the situation in which this failed? I understand this shouldn't really time out, but we aren't going to be able to do much without a reproducible example. Thanks!

**Comment by egucciar** [comment] 2017-11-21 14:56
@jennifer-shehane  It was a headless run. I'm not sure what other information you would need, it is a large test suite and one test failed for this reason. I can run the tests again but besides reproducing the error how else can I get information you need to diagnose ?

**Comment by brian-mann** [comment] 2017-11-27 01:08
There should never be a situation where this happens unless someone the internals of Cypress are being modified from test code. Assuming that's not the case, the only other situation would be a websocket connection timeout.

I suppose if the CPU is max'd to the max and there isn't enough resources then even tasks like these could time out.

Cypress clears cookies the same way that `setCookie` works before every single test. Millions of Cypress tests run without a problem, so if there's a problem with the underlying implementation then it has to be a perfect storm of edge cases. Without being able to reproduce this or having incredibly detailed logs there's nothing we could possibly do to look into this.

I'll keep this issue open because we're trying to improve the debuggability of these issues by generating debug logs of CLI runs.

**Comment by egucciar** [comment] 2017-11-27 03:26
I agree it's probably a maxed out cpu could explain it. Thanks !

**Comment by egucciar** [comment] 2017-12-12 23:29
@brian-mann  I experienced this issue again on my build machine (got the tests running on the CI and this is the first time running since introducing new changes) so if you have the ability to capture better logs now let me know.

**Comment by Saibamen** [comment] 2019-02-22 21:45
Please retest and add some steps to reproduce

**Comment by egucciar** [comment] 2019-02-22 21:57
You can close this, as I no longer work for the company where I had this issue.

**Comment by Saibamen** [comment] 2019-02-22 22:03
@egucciar I can't - don't have permissions. Please close it - this is your issue

**Closed** 2019-02-22 23:06 UTC
Labels: OS: windows, stage: needs information, type: bug
