### ISSUE TITLE
Initiating Typescript - Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'

### ISSUE THREAD

**Issue by MaaikeFox** [cypress-io/cypress#8758] opened 2020-10-06 13:33 UTC
### Current behavior
On `open cypress` and then starting a test, the browser opens and starts loading the test, but before the test actually starts, Cypress crashes and shows this error:

```
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (/Users/maaike/Projects/cypress/cypress/plugins/index.ts)

Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
```

### Desired behavior
With our current configurations we expect Cypress with Typescript added to work. 
We followed the instructions, then cleared cache, reinstalled cypress, but nothing helps.
We searched on the shown error but can't find anything useful

### Test code to reproduce
tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es6", "dom"],
    "types": ["cypress", "node"],
    "esModuleInterop": true,
    "allowJs": true
  },
  "include": ["**/*.ts"]
}
```

cypress/plugins/index.ts:
```
// promisified fs module
import fs from 'fs-extra'
import path from 'path'
import webpack from '@cypress/webpack-preprocessor'

function getConfigurationByFile(file) {
    const pathToConfigFile = path.resolve('cypress', 'config', `${file}.json`)

    return fs.readJson(pathToConfigFile)
}

// plugins file
module.exports = (on, config) => {
    require('cypress-terminal-report/src/installLogsPrinter')(on)
    require('cypress-log-to-output').install(on, (type, event) => {
        return (event.level === 'error' || event.type === 'error') && islogableError(event)
    })
    const options = {
        // send in the options from your webpack.config.js, so it works the same
        // as your app's code
        webpackOptions: require('../../webpack.config'),
        watchOptions: {},
    }
    on('file:preprocessor', webpack(options))

    const environment = process.env.ENVIRONMENT || config.env.ENVIRONMENT || 'acceptance'
    console.log(`plugins/index.ts: Loading local config from cypress/config/${environment}.json...`)
    return getConfigurationByFile(environment)
}
```

webpack.config.js
```
const path = require('path')

module.exports = {
    entry: './src/index.ts',
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
        ],
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
}
```

### Versions
Cypress 5.3.0

**Comment by jennifer-shehane** [comment] 2020-10-07 06:06
Duplicate of https://github.com/cypress-io/cypress/issues/8759

**Closed by jennifer-shehane** 2020-10-07 06:06 UTC
