### ISSUE TITLE
Add option to leave `cy.server` and requests running between tests in a spec

### ISSUE THREAD

**Issue by Svish** [cypress-io/cypress#6363] opened 2020-02-07 14:31 UTC
I'm testing a single page application that fetches data via a library that uses `stale-while-revalidating`. In short, related to flaky tests:

* When different components try loading the same data within a timespan, only 1 request will happen.
* When a compontent _later_ tries loading data that has _already_ been loaded, it will use the already loaded result, but it _might_ trigger a new request to revalidate.

### Current behavior:

As described in the `cy.server` documentation:

>####  Server persists until the next test runs
>
>Cypress automatically continues to persist the server and routing configuration even after a test ends. This means you can continue to use your application and still benefit from stubbing or other server configuration.
>
>**However between tests, when a new test runs, the previous configuration is restored to a clean state.** No configuration leaks between tests.
>
>#### Outstanding requests are automatically aborted between tests
>
>**When a new test runs, any outstanding requests still in flight are automatically aborted.** In fact this happens by default whether or not you’ve even started a cy.server().

This means, to test single page applications, instead of being able to setup all the `cy.server` route stubbing `before` I `cy.visit`, I currently need to re-apply the same exact setup `beforeEach`. Additionally, ongoing requests, if there are any, will be cut off between tests, which is not good.

```ts
describe('Spec X', () => {
  before(() => {
    cy.visit(application);
  });

  beforeEach(() => {
    cy.server();

    cy.route(route0);
    cy.route(route1);
    cy.route(route2);
  });

  it('Test feature A', () => {
    //
  });

  it('Test feature B', () => {
    //
});
```

### Desired behavior:

The current behavior is a good default, but I really wish there was an option to make the server stay active for the rest of the spec file.

I could then set up my routes `before` I `cy.visit`, and any background requests will be caught and completed as they should, even between tests.

```ts
describe('Spec X', () => {
  before(() => {
    cy.server({ persist: true }); // Or something like that

    cy.route(route0);
    cy.route(route1);
    cy.route(route2);

    cy.visit(application);
  });

  it('Test feature A', () => {
    //
  });

  it('Test feature B', () => {
    //
});
```

_**NOTE:** The main point here is _not_ that I want use only `before` instead of both `before` and `beforeEach`. The main point is that background requests currently gets killed between tests, and _might_ be revalidated in a later test, even though the request completed the first time in the first test._

### Versions

**Cypress:** 3.8.3, **Windows:** 10, **Chrome:** 79

**Comment by jennifer-shehane** [comment] 2020-02-10 07:26
We used to not abort requests in between tests - and it caused a lot of confusing behavior. The vast majority of our users issue a `cy.visit()` in between each test and ensure that there is zero state from the previous test carried over [as we advise](https://on.cypress.io/best-practices#Having-tests-rely-on-the-state-of-previous-tests). Our product kind of expects you to test in this way, which is why the other behavior you want does not really work. 

If you need requests to finish before moving on to the next test, then you need to explicitly wait for those requests using `cy.wait()`. 

How would Cypress know when to ever stop listening to requests and move on, say if you had polling requests that overlap? The next test would never run if we waited for all open requests to always finish.  

Overall this is related to the larger topic of lifecycle events and allowing users more control over what state to carry over in between tests. Duplicate of #686

**Closed by jennifer-shehane** 2020-02-10 07:26 UTC

**Comment by Svish** [comment] 2020-02-10 08:39
> We used to not abort requests in between tests - and it caused a lot of confusing behavior.

That's why it should be opt-in, not default.

> The vast majority of our users issue a cy.visit() in between each test ...

The problem with that is that the tests become super slow. The tests are _so_ much faster when I can set things up in `before`, and then just run various client-side scenarios and assertions in `describe`, `context`, and `it`.

> If you need requests to finish before moving on to the next test, ...

I wouldn't need that, if requests weren't killed off. Because of the very nice retry feature of Cypress, as long as my assertions are good, the tests will run fine.

> How would Cypress know when to ever stop listening to requests and move on, say if you had polling requests that overlap?

Cypress shouldn't stop listening, and from what I've understood, it doesn't stop listening after the very last test either.

> The next test would never run if we waited for all open requests to always finish.

A test shouldn't wait for open requests, it should move on after the last assertion has completed successfully, regardless of open requests.

> Overall this is related to the larger topic of lifecycle events and allowing users more control over what state to carry over in between tests. Duplicate of #686

I read that issue now, and as long as "resets routes you've defined" is one of the options one can turn off, then I think that would indeed solve my issue. But, that issue having existed since September 23, 2017, with high priority, with no visible progress, doesn't make me super hopeful though... 😕
