### ISSUE TITLE
ERR_SSL_VERSIONOR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by SOMIASHARMA26** [cypress-io/cypress#5087] opened 2019-09-05 04:34 UTC
This site can't provide a secure connection
xxx uses an unsupported protocol
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Chrome version -76
Cypress version- 3.4.1

Code run
![15676579554944666226416890358443](https://user-images.githubusercontent.com/54882830/64312115-5948e580-cfc4-11e9-8859-142c75898e95.jpg)

Error on screen
![15676580195088851658052493986991](https://user-images.githubusercontent.com/54882830/64312145-754c8700-cfc4-11e9-9fff-ffd8e8cbd99d.jpg)

**Comment by SOMIASHARMA26** [comment] 2019-09-05 05:09
@jennifer-shehane please share some feedback..I have already implement all approach u have mentioned in #771

**Comment by SOMIASHARMA26** [comment] 2019-09-05 08:22
I mapped DNS now I am getting
Error getaddrinfo enotfound

**Comment by jennifer-shehane** [comment] 2019-09-05 20:48
Please don't open new issues for existing issues. Closing as duplicate of https://github.com/cypress-io/cypress/issues/771

**Closed by jennifer-shehane** 2019-09-05 20:48 UTC
