### ISSUE TITLE
Does not read from jsconfig.json

### ISSUE THREAD

**Issue by OleksiiKachan** [cypress-io/cypress#25943] opened 2023-02-24 16:57 UTC
### Current behavior

Unable to use alias from `jsconfig.json` after updating next to 13.2.1

cypress.config.js
```js
const { defineConfig } = require(`cypress`);

module.exports = defineConfig({
  component: {
    devServer: {
      framework: `next`,
      bundler: `webpack`,
    },
  },
});
```

support/component.js
```js
import '@testing-library/cypress/add-commands';

import { mount } from 'cypress/react18';
import GlobalStyle from 'styles/globalstyles';

Cypress.Commands.add(`mount`, (children) =>
  mount(
    <>
      <GlobalStyle />
      {children}
    </>
  )
);
```

jsconfig.json
```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["src/*"]
    }
  }
}

```

Terminal output:
<img width="832" alt="Screenshot 2023-02-24 at 11 25 17 AM" src="https://user-images.githubusercontent.com/14169061/221232473-ceed26c4-8e8e-4d9b-a4de-a5b2b4e7f66d.png">

all works if I rollback to next@13.1.6

### Desired behavior

Should use path from jsconfig and import files

### Test code to reproduce

https://github.com/OleksiiKachan/cypress-import

### Cypress Version

v12.6.0

### Node version

v18.12.1

### Operating System

macOS 13.2.1

### Other

I'm not sure where the problem is. I think it is related to babel updated on next side

**Comment by jamesopti** [comment] 2023-02-25 17:21
@OleksiiKachan thanks for filing a more thorough bug with reproducibility than I did! I'm encountering the same issue. 

Possibly related NextJS issue: https://github.com/cypress-io/cypress/issues/25943

**Comment by HoncharenkoZhenya** [comment] 2023-02-27 12:13
The same problem

**Comment by marktnoonan** [comment] 2023-02-27 16:48
Hi folks, going to consolidate this with https://github.com/cypress-io/cypress/issues/25951 so we can discuss in the same place, seems to be same underlying issue, so I'll close this one as a duplicate.

**Closed as not planned by marktnoonan** 2023-02-27 16:48 UTC
