### ISSUE TITLE
Component testing / DX: filter failed tests with one action

### ISSUE THREAD

**Issue by edimitchel** [cypress-io/cypress#17803] opened 2021-08-19 12:36 UTC
### What would you like?

Filter out all succeed error from a test suite for keeping all previous failed tests.
Filter should be simply made : a simple button click.

As long tests are fixed, auto refresh should rerun only previously failed tests.
Clicking on the button should filter again for keeping failed rest tests.
If all tests are alright, rerun all tests again for checking no one as being failed as side effects.

I have a name for that feature: "RED Focus".
_May be, we can have like a TDD lifecycle for getting a different behavior on tests failure._

### Why is this needed?

When I want to update a test because spec had changed, I would like to run the specific test that failed (or might fail).
_On the basis that my test suite is complex and have a lot of tests._
On the first run, I see several tests are failing. They are located at the end of the test suites. When I would like to fix them, today I have two choices: 
- wait first tests are passing before the specific test I want to fix or 
- comment out first tests.

This is not a good thing IMHO. I guess, if tests are well made (isolated and specific), fix filtered failed tests should not break hidden succeed tests.

### Other

I didn't time for working on it, but I will glad to help on specification and design :)

**Comment by jennifer-shehane** [comment] 2021-08-19 12:56
Duplicate of https://github.com/cypress-io/cypress/issues/4886

**Closed by jennifer-shehane** 2021-08-19 12:56 UTC
