### ISSUE TITLE
Cypress doesn't watch changes for files with square brackets in the name

### ISSUE THREAD

**Issue by amannn** [cypress-io/cypress#7980] opened 2020-07-14 13:42 UTC
### Current behavior:

If you use `"watchForFileChanges": true` and have a file named like `[slug].e2e.tsx` that contains your tests, it won't re-run the tests when the file changes.

### Desired behavior:

When the file `[slug].e2e.tsx` changes, I expect Cypress to re-run the test suite.

### Test code to reproduce

1. Clone https://github.com/amannn/cypress-test-tiny
2. Run `npm install && npm run cypress:open`
3. Run the test suite within `[test].spec.js`
4. Change the file `[test].spec.js`
5. Nothing happens – the tests aren't re-run.

### Versions

cypress@^4.10.0
macOS 10.15.4 (19E287)

**Comment by jennifer-shehane** [comment] 2020-07-15 06:03
Duplicate of #5426

**Closed by jennifer-shehane** 2020-07-15 06:03 UTC
