### ISSUE TITLE
Unable to complete a test Paypal payment from a commercial website 

### ISSUE THREAD

**Issue by obajaddi** [cypress-io/cypress#22186] opened 2022-06-08 11:40 UTC
### Current behavior

Hello ! 

I'm using the new "cy.origin()" feature in order to make a payment with Paypal.
After beeing redirected, I type the credentials and after cliking for login... the runner "crash" or "disapear"
=> it's like the page is "reloading" or open a new page in the same windows, since Cypress don't manage multi windows, maybe it's a the root cause ?
Potentially this problem occurs on other websites of course.

Ok there is a point with an extrenal provider front-testing : we chose to get throught the front.
=> that's why "cy.origin()" is cool !

**Context :** 

- OS : ubuntu 20.04.4 lts
- Browsers tested : Chrome 102, FF 100
- chromewebsecurity not implemented

Thx ^^
![cypressPPbug2](https://user-images.githubusercontent.com/51787457/172564744-1d200f5c-5141-46ab-ac1d-32a60865c4bf.gif)

### Desired behavior

Make a payment with Paypal from a website whitout the test runner to "disapear" 

### Test code to reproduce

# You need a commercial website with a checkout redirecting to sandbox.paypal.com

### Cypress Version

9.7.0

**Comment by AtofStryker** [comment] 2022-06-10 15:35
Related to #14986 and #16905

**Comment by mjhenkes** [comment] 2022-06-10 20:53
Closing as a duplicate of #21602

**Closed by mjhenkes** 2022-06-10 20:53 UTC
Labels: stage: investigating

**Comment by obajaddi** [comment] 2022-06-13 09:28
Hello @AtofStryker 

Great thanks ! I'm gonna follow this stuff, see you next time

Othmane

**Comment by AtofStryker** [comment] 2022-07-25 18:29
@obajaddi #22568 should fix the issue with logging into PayPal, but you will unlikely be able to engage in payment fields directly as they are cross origin iframes. Once #22568 releases, would you be able to confirm that this fix works for logging into PayPal for you with the flag introduced in #22568?

**Comment by serhatgemici** [comment] 2022-08-23 15:00
This is now working fine when experimentalModifyObstructiveThirdPartyCode is set to true.

**Comment by AtofStryker** [comment] 2022-08-25 14:19
@serhatgemici interesting that it is working for at least a payment. Are you able to provide a reproduction so we can see the issue?

**Comment by minopica** [comment] 2022-08-31 15:54
Hi all, any news on this ?
I am using latest version of cypress 10.7.0 and if I add the parameter "experimentalModifyObstructiveThirdPartyCode: true" into the cypress.config.js file then as soos as the cy.visit("...") command is invoked I got an unexpected exception "(uncaught exception)SyntaxError: Invalid left-hand side in assignment", see attached screenshot.

![image](https://user-images.githubusercontent.com/47905045/187723087-424c009b-2128-4010-9811-dcdcad5c956b.png)

I am blocked with tests on paypal payment, cyress runner disappear when there is a redirect to sandbox....

**Comment by leonid-sviderskii-mtl** [comment] 2022-09-09 17:12
I was able to handle the Paypal sandbox payment (separate page, not a pop-up) using Cypress 10.7 and these things:

Config:
```
experimentalModifyObstructiveThirdPartyCode: true,
chromeWebSecurity: false,
```

Steps when on the PayPal side:
```     
cy.origin('https://paypal.com', () => {
    cy.get('#password')
        .type('myPassword')

    cy.get('#btnLogin')
        .should('be.enabled')
        .click()

    cy.get('[data-testid="submit-button-initial"]')
        .should('be.enabled')
        .click()
})
```

**Comment by minopica** [comment] 2022-09-09 23:14
When I use     experimentalModifyObstructiveThirdPartyCode: true all the tests fail with the error
"SyntaxError
The following error originated from your application code, not from Cypress.

> Invalid left-hand side in assignment
"


following an example of js test that is failing:

// <reference types="Cypress" />

describe('Cypress Studio Demo', () => {

    it('create new transaction', () => {

      /* ==== Generated with Cypress Studio ==== */
      cy.visit('https://ac.windtre.it');
      /* ==== End Cypress Studio ==== */
      /* ==== Generated with Cypress Studio ==== */
      cy.get('#login_entra').click();
      cy.get('.mat-form-field-infix').click();
      cy.get('#firstInput').clear();
      cy.get('#firstInput').type('minopica@gmail.com');
      cy.get('#login_continua').click();
      cy.get('form.ng-untouched > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
      cy.get('#mat-input-1').clear();
      cy.get('#mat-input-1').type('a12345678B');
      cy.get('#accedi').click();
      cy.get('#Tariffe\\ estero > .w3-link').click();
      cy.get('#roaming_ue > .details-card > .row > .col-9 > .sub-title').click();
      cy.get('#Tariffe\\ estero > .w3-link').click();
      cy.get('#quando_sei_all_estero > .details-card > .row > .col-9 > .title').click();
      /* ==== End Cypress Studio ==== */
      /* ==== Generated with Cypress Studio ==== */
      cy.get('#login_entra').click();
      cy.get('.mat-form-field-infix').click();
      cy.get('#firstInput').clear();
      cy.get('#firstInput').type('minopica@gmail.com');
      cy.get('#login_continua').click();
      cy.get('form.ng-untouched > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
      cy.get('#mat-input-1').clear();
      cy.get('#mat-input-1').type('a12345678B');
      cy.get('#accedi').click();
      cy.get('#Tariffe\\ estero > .w3-link').click();
      cy.get('#roaming_ue > .details-card > .row > .col-9 > .sub-title').click();
      cy.get('#Tariffe\\ estero > .w3-link').click();
      cy.get('#quando_sei_all_estero > .details-card > .row > .col-9 > .title').click();
      /* ==== End Cypress Studio ==== */
    })
  })
  

following the cypress.config.js:

const { defineConfig } = require("cypress");

module.exports = defineConfig({
  chromeWebSecurity: false,
  projectId: "rwdmnz",
  defaultCommandTimeout: 20000,
  pageLoadTimeout: 60000,
  watchForFileChanges: false,

  env: {
    url_bs: 'https://priv:P3rz0nal!@pwa.bs.windtre.it/oa/auth/login',
    url_test: "http://pwa.dev.windtre.it/oa/auth/login"
  },

  e2e: {
    experimentalStudio: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    experimentalSessionAndOrigin: true,
    setupNodeEvents(on, config) {
      // implement node event listeners here
      const store = {}
      on('task',{
        saveToken(jwt) {
          console.log('token saveToken jwt:' + jwt)
          store['token'] = jwt
          return null
        },
        loadToken() {
          return store['token']
        },
        saveChallengeToken(jwt) {
          console.log('token saveChallengeToken jwt:' + jwt)
          store['challengeToken'] = jwt
          return null
        },
        loadChallengeToken() {
          return store['challengeToken']
        },
        saveCodiceCliente(code) {
          console.log('codice cliente salvato:' + code)
          store['codice_cliente'] = code
          return null
        },
        loadCodiceCliente() {
          return store['codice_cliente']
        },
        saveLineId(linea) {
          console.log('lineId salvato:' + linea)
          store['lineId'] = linea
          return null
        },
        loadLineId() {
          return store['lineId']
        },
        saveContractId(contratto) {
          console.log('contractId salvato:' + contratto)
          store['contractId'] = contratto
          return null
        },
        loadContractId() {
          return store['contractId']
        },
        saveArrayContracts(contratti) {
          console.log('array contratti salvato:' + contratti)
          store['arrayContracts'] = contratti
          return null
        },
        loadArrayContracts() {
          return store['arrayContracts']
        },

      })
    },
    specPattern: 'cypress/e2e/pwa/*.js'
  },
});

**Comment by leonid-sviderskii-mtl** [comment] 2022-09-12 15:42
@minopica I guess you need to provide a fully working test to the team which means a dummy user with the password. Otherwise, it doesn't work.

**Comment by minopica** [comment] 2022-09-12 15:51
Done, see here: https://github.com/cypress-io/cypress/issues/23647#issuecomment-1243840853

**Comment by lchhieu** [comment] 2022-11-01 09:49
@obajaddi what is your solution to solve this issue ? I'm using cypress v9.x so cannot use experimentalModifyObstructiveThirdPartyCode in version 10.x

**Comment by Ravikumar0212** [comment] 2024-12-16 17:22
Getting below error while automating PayPal sandbox in cypress

ReferenceError
cov_1doum82pp1 is not defined

Variables must either be defined within the cy.origin() command or passed in using the args option.
