### ISSUE TITLE
Watch a given folder or file mask(s) to rerun tests on changes

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3442] opened 2019-02-12 20:17 UTC
Currently in Cypress v3 we automatically rerun tests if one of the _spec_ files changes. But often the TDD workflow requires changing the source files to fix the test. Users have come up with ingenious workarounds to rerun the tests on application file changes - see https://github.com/TheBrainFamily/cypress-app-watcher-preprocessor

I think since we already set up watching on spec files, we could add extra file mask to watch too. Something like this to `cypress.json` to watch "src" folder

```json
{
  "watchExtraFiles": "src"
}
```

Or could watch several folders

```json
{
  "watchExtraFiles": ["src", "styles"]
}
```

We already have option `watchForFileChanges`. Maybe we can expand it? Right now it is a boolean, and we could make it into:

- boolean - watch or not just the specs, like current behavior in 3.1.5
- string or strings - watches specs (just like `watchForFileChanges: true` does right now), plus watches these extra folders or wildcards

**Comment by jennifer-shehane** [comment] 2019-02-13 04:47
Duplicate of https://github.com/cypress-io/cypress/issues/456

**Closed by jennifer-shehane** 2019-02-13 04:47 UTC
Labels: type: duplicate
