### ISSUE TITLE
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed.

### ISSUE THREAD

**Issue by Imcypressuser** [cypress-io/cypress#14831] opened 2021-01-30 14:28 UTC
### Current behavior
My tests were working fine earlier but now getting the following error "The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (C:\SK\My Projects\CypressAutomation\cypress\plugins\index.js)"
```
TypeError: err.replace is not a function
    at cleanseError (C:\SK\My Projects\CypressAutomation\node_modules\@cypress\webpack-preprocessor\dist\index.js:272:16)
    at Array.map (<anonymous>)
    at Watching.handle [as handler] (C:\SK\My Projects\CypressAutomation\node_modules\@cypress\webpack-preprocessor\dist\index.js:175:22)
    at C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Watching.js:185:9
    at Hook.eval [as callAsync] (eval at create (C:\SK\My Projects\CypressAutomation\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\SK\My Projects\CypressAutomation\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Watching.js:182:28)
    at C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Watching.js:107:21
    at Compiler.emitRecords (C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Compiler.js:820:39)
    at C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Watching.js:85:22
    at C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Compiler.js:802:14
    at Hook.eval [as callAsync] (eval at create (C:\SK\My Projects\CypressAutomation\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\SK\My Projects\CypressAutomation\node_modules\tapable\lib\Hook.js:18:14)
    at C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Compiler.js:799:27
    at C:\SK\My Projects\CypressAutomation\node_modules\neo-async\async.js:2818:7
    at done (C:\SK\My Projects\CypressAutomation\node_modules\neo-async\async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (C:\SK\My Projects\CypressAutomation\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\SK\My Projects\CypressAutomation\node_modules\tapable\lib\Hook.js:18:14)
    at C:\SK\My Projects\CypressAutomation\node_modules\webpack\lib\Compiler.js:667:33
    at C:\SK\My Projects\CypressAutomation\node_modules\graceful-fs\graceful-fs.js:144:16
    at C:\Users\shubhamk\AppData\Local\Cypress\Cache\6.3.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\SK\My Projects\CypressAutomation\node_modules\graceful-fs\graceful-fs.js:61:14
Stack trace
```

### Desired behavior
Tests may not failed

### Versions
Cypress package version: 6.3.0
Cypress binary version: 6.3.0
Electron version: 11.2.0
Bundled Node version:
12.18.3

**Comment by jennifer-shehane** [comment] 2021-02-02 05:50
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the plugins file and any code from the preprocessors you have set up. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-02 05:50 UTC

**Comment by myyellowshoe** [comment] 2021-02-03 22:30
@jennifer-shehane 

I'm running into the exact same issue. Just confirm i'm not doing anything crazy wrong I tried using one of the provided examples to see what I did wrong. I isolated the following folder from cypress examples:
https://github.com/cypress-io/cypress/tree/master/npm/react/examples/sass-and-ts

My version
https://github.com/myyellowshoe/sass-ts-testing

**To Reproduce:**
$ Cypress test

```
 Running:  cy-spec.js                                                                      (1 of 2)
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`{your local filepath}/sass-and-ts/cypress/plugins/index.js`)
```

What could be up here?

**Comment by jennifer-shehane** [comment] 2021-02-04 05:09
Duplicate of https://github.com/cypress-io/cypress/issues/8948

**Comment by prashantsaraogi** [comment] 2021-07-23 14:05
I am still getting error with following dependnies. Please suggest

  "devDependencies": {
    "cypress": "^8.0.0",
    "cypress-cucumber-preprocessor": "^4.1.4",
    "cypress-webpack-preprocessor-v5": "^5.0.0-alpha.1"
  },

**Comment by IPrasadMCA** [comment] 2022-01-25 05:32
I too came across this error, 
So I found that my system had nodejs 17 version so tried to uninstall 17 and installed nodejs 16 version..
Then Problem has been resolved..and now its working fine

**Comment by Honeyx03** [comment] 2023-03-07 01:45
My cypress isn't working. I am getting this message:

cypress run

objc[16221]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4ae58ec8) and /Users/n/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10e2919c8). One of the two will be used. Which one is undefined.
Nothing to watch. Set the "cypress-watch-and-reload" object in the Cypress configuration
see https://github.com/bahmutov/cypress-watch-and-reload#use
We stopped running your tests because a plugin crashed.

Your pluginsFile threw an error from: /Users/n/CodingProjects/html_intro/CSS_Intro/lab-intro-to-css/cypress/plugins/index.js
