### ISSUE TITLE
cy.clear() throws Type Error: Illegal Invocation

### ISSUE THREAD

**Issue by aeendale** [cypress-io/cypress#4194] opened 2019-05-14 23:45 UTC
### Current behavior:

`cy.clear()` method intermittently throws the following error message shown below 
![image](https://user-images.githubusercontent.com/23197906/57739032-fe3f5b80-767f-11e9-83d7-3c605d39ab77.png)

Additional error details below when running from the commandline

![image](https://user-images.githubusercontent.com/23197906/57739299-0c41ac00-7681-11e9-9b3f-a36053bcc94b.png)

 
### Desired behavior:

`cy.clear()` should always clear the text area.

### Steps to reproduce: (app code and test code)

Run the below code on the following open-source website: 

```js
cy.visit("http://pie-website.surge.sh/examples/pie-multiple-choice.html");
cy.get('.Component-prompt-8 > .EditorAndToolbar-root-70 > .EditorAndToolbar-editorHolder-72 > .EditorAndToolbar-children-71 > .Editor-slateEditor-69 > div').as('question');
cy.get('@question').clear().type("Test Question");
```

### Versions

Cypress: 3.2.0
Operating System: macOS Mojave 10.4.3
Browser: Electron 59

**Comment by jennifer-shehane** [comment] 2019-05-15 09:10
This is definitely a bug. In this situation you should technically get this error:

```
cy.clear() failed because it requires a valid clearable element.

      The element cleared was:

        > div

      Cypress considers a 'textarea', any 'element' with a 'contenteditable' attribute, or any 'input' with a 'type' attribute of 'text', 'password', 'email', 'number', 'date', 'week', 'month', 'time', 'datetime', 'datetime-local', 'search', 'url', or 'tel' to be valid clearable elements.
```

We will need to fix this situation.

The element with the `contenteditable="true"` should be the element targeted for the `.clear()`.

**But** even when targeting that element, the input is not properly cleared. What happens when calling `.clear()` is that the first character of the `contenteditable` is cleared and then the test on the page is selected. This kind of makes sense since `.clear()` is calling a `selectall` then `delete`, but why is it not focusing properly on the input first before calling the `selectall`

![Screen Shot 2019-05-15 at 3 32 40 PM](https://user-images.githubusercontent.com/1271364/57763143-d5be6c80-7726-11e9-8306-0c1f179336f3.png)

The native events support may improve this experience https://github.com/cypress-io/cypress/issues/311 @Bkucera Can you see if this behavior changes at all with native events support?

**Comment by jennifer-shehane** [comment] 2019-05-15 09:28
This issue only occurs when the browser has focus. If you focus on another window or are focused within the devtools console, this test will pass.

Reproducible code.

```js
it('clear illegal invocation"', function () {
  cy.visit('http://pie-website.surge.sh/examples/pie-multiple-choice.html')
  cy.get('.root').should('not.have.class', 'loading')

  cy.get('.Editor-slateEditor-69 > div').clear()
})
```

**Comment by jennifer-shehane** [comment] 2019-05-15 12:18
Because this element is not an `input`, `textarea`, `select`, or `button` - we wrongly assume that it must be an `option` element.

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/elements.js#L59

We then try to call the native `value()` prop of the 'option' element which throws the illegal invocation because it's not an option element.

Illegal invocation can be reproduced by running the code below in the console.

```js
Object.getOwnPropertyDescriptor(window.HTMLOptionElement.prototype, 'value').get.call($('.Editor-slateEditor-69>div'), 'value')
```

I updated this call to only happen after checking that the element is an `option` element. https://github.com/cypress-io/cypress/pull/4196

The real issue though is how does this element qualify as a `contenteditable` element initially (and does not throw the incorrect element error), but then later does not qualify as a `contenteditable` element when going to get its value. 

<img width="230" alt="Screen Shot 2019-05-15 at 5 58 47 PM" src="https://user-images.githubusercontent.com/1271364/57772318-1f18b700-773b-11e9-8c29-66892b28b00a.png">

Also, when I focus out of the window, the element always qualifies as a `contenteditable` element. 😕 

<img width="188" alt="Screen Shot 2019-05-15 at 6 04 33 PM" src="https://user-images.githubusercontent.com/1271364/57772663-0361e080-773c-11e9-8c3b-e746b14c5a4d.png">

<img width="846" alt="Screen Shot 2019-05-15 at 6 18 50 PM" src="https://user-images.githubusercontent.com/1271364/57773403-f514c400-773d-11e9-9327-21093d1a608c.png">

Anyways, it seems to switch to not qualifying as `contenteditable` upon focus of the element. @Bkucera you have some insight into this?

**Comment by aeendale** [comment] 2019-05-16 14:14
@Bkucera @jennifer-shehane any updates on this issue? 

At the very least, can you think of any workaround to clearing that text area in the meantime?

Really appreciate the ongoing effort.

**Comment by Bkucera** [comment] 2019-05-17 18:54
@aeendale I looked at this issue for a little while, it looks like an issue caused by us not firing the `selectionchange` event on `click`, which then causes the selection to be wrong, which causes the error.

However I will need a better reproducible. I know that's using the `slate` editor, but can't find a demo that cypress fails with.

If you'd be able to reproduce a minimal reproducible example (like in a codepin), I would be willing to investigate further. But right now, this looks like a very specific problem not worth being prioritized right now.

**Comment by aeendale** [comment] 2019-05-20 15:23
@Bkucera thanks for the feedback, the issue can be reproduced by running the three lines of code below. 

```
cy.visit("http://pie-website.surge.sh/examples/pie-multiple-choice.html");
cy.get('.Component-prompt-8 > .EditorAndToolbar-root-70 > .EditorAndToolbar-editorHolder-72 > .EditorAndToolbar-children-71 > .Editor-slateEditor-69 > div').as('question');
cy.get('@question').clear().type("Test Question");
```

**Comment by Bkucera** [comment] 2019-05-20 16:22
@aeendale, I was asking for a minimal reproducible example that can be locally cloned and built, so that we can actually write a failing test.

**Comment by aeendale** [comment] 2019-05-21 01:51
@Bkucera apologies. Below is the requested info. 

Repo: [Cypress-Sample](https://github.com/aeendale/cypress-sample.git)

`npx cypress run`

There is only one visible test within the integration folder called "brokenTest.spec.js"

Hope that helps.

**Comment by jennifer-shehane** [comment] 2019-05-21 05:54
Hey @aeendale, sorry for the confusion. 😥 

We want to write a test that does not visit your `http://pie-website-next.surge.sh/examples/pie-multiple-choice.html` page, but still reproduces the error. Since this website external and not under our control, any changes made to the pie-website will break our tests in the future. 

We need some html + js that reproduces the problem - just a local index.html and script.js file (or codepen) that we can place inside our own test suite. We tried making a few examples, but were unable to isolate the exact html + css + js that is causing it. We think maybe it's related to the slate editor component? Thanks again for your time.

**Comment by jennifer-shehane** [comment] 2019-07-11 08:21
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-11 08:21 UTC
Labels: pkg/driver, stage: needs information, type: bug
