### ISSUE TITLE
$element.text is not a function

### ISSUE THREAD

**Issue by VictorCapitole** [cypress-io/cypress#9435] opened 2020-12-03 08:33 UTC
I have this code:

```js
cy.get(#element).should(($element) => {
        cy.log($element.text())
})
```

When running this code I have the following error: $element.text is not a function
But the log is printing the text properly.

![image](https://user-images.githubusercontent.com/55388756/100984031-6e575000-354a-11eb-8c7b-f600be9a9635.png)

**Comment by jennifer-shehane** [comment] 2020-12-03 08:52
So, for some reason the `cy.log()` is running twice here. 

Duplicate of https://github.com/cypress-io/cypress/issues/8346

**Closed by jennifer-shehane** 2020-12-03 08:52 UTC

**Comment by VictorCapitole** [comment] 2020-12-03 08:58
It's not that.
I've changed the code to cy.get(loginForm.ddLanguage).text() and still have the same error.

![image](https://user-images.githubusercontent.com/55388756/100986917-1c182e00-354e-11eb-88c0-890ab3e8f8a4.png)

**Comment by jennifer-shehane** [comment] 2020-12-03 09:01
@VictorCapitole This is because `.text()` is not a Cypress command, so it is not a function that can be chained off of Cypress. 

See our FAQ for multiple ways to get the text of an element: https://on.cypress.io/using-cypress-faq#How-do-I-get-an-element%E2%80%99s-text-contents

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

**Comment by DMazona** [comment] 2021-12-27 20:46
I don't get it, the same page you reference mentions using .text() multiple times.
