### ISSUE TITLE
Cypress 4.4.1 (4.2.0 and above) opens with blank GUI on Linux

### ISSUE THREAD

**Issue by danatemple** [cypress-io/cypress#7140] opened 2020-04-26 20:49 UTC
### Current behavior:

Following upgrade from 4.1.0 to 4.4.1 (or any version above 4.2.0), "npx cypress open" results in a blank grey window with no content. No particular error messages are printed to the terminal.

Older versions 4.1.0 and below still work fine, as do all other X programs such as browsers etc from the same terminal.

### Test code to reproduce

This is seen running a Linux desktop via a VNC session. Ubuntu 16.04.

**Comment by jennifer-shehane** [comment] 2020-04-27 07:43
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

Could you provide a screenshot of what you mean by 'grey window of no content'. Thanks!

**Comment by danatemple** [comment] 2020-04-27 08:27
Here goes. Note that you can ignore the following lines, it always says this even if everything is working:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
```

```
dan@test1:data-dynamo> DEBUG=cypress:* ~/.cache/Cypress/4.2.0/Cypress/Cypress open
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
  cypress:ts Running without ts-node hook in environment "production" +0ms
  cypress:server:appdata path: /home/dan/.config/Cypress/cy/production/browsers +0ms
  cypress:server:cypress starting cypress with argv [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ] +0ms
  cypress:server:args argv array: [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ] +0ms
  cypress:server:args argv parsed: { _: [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ], invokedFromCli: false, cwd: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server' } +3ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ], invokedFromCli: false, cwd: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server', config: {} } +1ms
  cypress:server:args argv options: { _: [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ], invokedFromCli: false, cwd: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server', config: {} } +0ms
  cypress:server:cypress from argv [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ] got options { _: [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ], invokedFromCli: false, cwd: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server', config: {} } +7ms
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
  cypress:server:appdata path: /home/dan/.config/Cypress/cy/production +261ms
  cypress:server:cypress starting in mode interactive with options { _: [ '/home/dan/.cache/Cypress/4.2.0/Cypress/Cypress', 'open' ], invokedFromCli: false, cwd: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server', config: {} } +82ms
It looks like you are running the Cypress binary directly.

This is not the recommended approach, and Cypress may not work correctly.

Please install the 'cypress' NPM package and follow the instructions here:

https://on.cypress.io/installing-cypress
  cypress:server:cypress running Electron currently +4ms
  cypress:server:appdata path: /home/dan/.config/Cypress/cy/production +100ms
  cypress:server:appdata path: /home/dan/.config/Cypress/cy/production/cache +368ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler âââââââââââ¬ââââââââââââââââââââ¬âââââââââââââââ¬âââââââââââââââ¬âââââââââââââ¬âââââââââââââââââ¬âââââââââââ¬âââââââââââââââ¬ââââââââââââââcypress:server:util:process_profiler â (index) â       group       â processCount â     pids     â cpuPercent â meanCpuPercent â memRssMb â meanMemRssMb â maxMemRssMb â
  cypress:server:util:process_profiler âââââââââââ¼ââââââââââââââââââââ¼âââââââââââââââ¼âââââââââââââââ¼âââââââââââââ¼âââââââââââââââââ¼âââââââââââ¼âââââââââââââââ¼ââââââââââââââ¤
  cypress:server:util:process_profiler â    0    â     'cypress'     â      1       â    '4952'    â     0      â       0        â  139.33  â    139.33    â   139.33    â
  cypress:server:util:process_profiler â    1    â 'electron-shared' â      2       â '4956, 4958' â     0      â       0        â  48.92   â    48.92     â    48.92    â
  cypress:server:util:process_profiler â    2    â      'other'      â      2       â '5096, 5097' â     0      â       0        â   3.49   â     3.49     â    3.49     â
  cypress:server:util:process_profiler â    3    â      'TOTAL'      â      5       â     '-'      â     0      â       0        â  191.73  â    191.73    â   191.73    â
  cypress:server:util:process_profiler âââââââââââ´ââââââââââââââââââââ´âââââââââââââââ´âââââââââââââââ´âââââââââââââ´âââââââââââââââââ´âââââââââââ´âââââââââââââââ´ââââââââââââââ+0ms
  cypress:server:saved_state making saved state from /home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +1ms
  cypress:server:appdata path: /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +2s
  cypress:server:saved_state full state path /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:saved_state making new state file around /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file get values from /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file attempt to get lock on /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file gettin lock succeeded or failed for /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +2ms
  cypress:server:file read /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file read succeeded or failed for /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +2ms
  cypress:server:file attempt to unlock /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +1ms
  cypress:server:file unlock succeeded or failed for /home/dan/.config/Cypress/cy/production/projects/__global__/state.json +0ms
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
  cypress:server:windows creating electron window with options { backgroundColor: '#dfe2e4', width: 800, height: 550, minWidth: 458, minHeight: 400, x: null, y: null, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, icon: NativeImage {}, webPreferences: { preload: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/lib/ipc/ipc.js', partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false, backgroundColor: '#dfe2e4', transparent: false }, url: 'file:///home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/desktop-gui/dist/index.html', contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
  cypress:server:events got request for event: on:menu:clicked, undefined +0ms
  cypress:server:events got request for event: get:options, undefined +0ms
  cypress:server:events got request for event: get:current:user, undefined +1ms
  cypress:server:file get values from /home/dan/.config/Cypress/cy/production/cache +404ms
  cypress:server:file attempt to get lock on /home/dan/.config/Cypress/cy/production/cache +0ms
  cypress:server:events sending ipc data { type: 'get:options', data: { id: 0.8876190483223598, data: { _: [Array], invokedFromCli: false, cwd: '/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server', config: {}, onFocusTests: [Function: onFocusTests], os: 'linux', version: '4.2.0' } } } +4ms
(node:4952) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:4952) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
  cypress:server:file gettin lock succeeded or failed for /home/dan/.config/Cypress/cy/production/cache +11ms
  cypress:server:file read /home/dan/.config/Cypress/cy/production/cache +0ms
  cypress:server:file read succeeded or failed for /home/dan/.config/Cypress/cy/production/cache +1ms
  cypress:server:file attempt to unlock /home/dan/.config/Cypress/cy/production/cache +0ms
  cypress:server:file unlock succeeded or failed for /home/dan/.config/Cypress/cy/production/cache +1ms
  cypress:server:events sending ipc data { type: 'get:current:user', data: { id: 0.4127987322187505, data: {} } } +11ms
  cypress:server:events got request for event: get:projects, undefined +7ms
  cypress:server:file transaction for /home/dan/.config/Cypress/cy/production/cache +8ms
  cypress:server:file attempt to get lock on /home/dan/.config/Cypress/cy/production/cache +2ms
  cypress:server:events got request for event: updater:check, undefined +3ms
  cypress:server:updater checking for new version of Cypress. current version is 4.2.0 +0ms
  cypress:server:file gettin lock succeeded or failed for /home/dan/.config/Cypress/cy/production/cache +17ms
  cypress:server:file write /home/dan/.config/Cypress/cy/production/cache +0ms
  cypress:server:file write succeeded or failed for /home/dan/.config/Cypress/cy/production/cache +2ms
  cypress:server:file attempt to unlock /home/dan/.config/Cypress/cy/production/cache +1ms
  cypress:server:file unlock succeeded or failed for /home/dan/.config/Cypress/cy/production/cache +0ms
  cypress:server:events sending ipc data { type: 'get:projects', data: { id: 0.515467648110361, data: [] } } +21ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://download.cypress.io/desktop.json' } +0ms
  cypress:network:connect beginning getAddress { hostname: 'download.cypress.io', port: 443 } +0ms
  cypress:server:events got request for event: get:project:statuses, [] +17ms
  cypress:server:project get project statuses for 0 projects +0ms
  cypress:server:file get values from /home/dan/.config/Cypress/cy/production/cache +18ms
  cypress:network:connect got addresses { hostname: 'download.cypress.io', port: 443, addresses: [ { address: '104.26.6.176', family: 4 }, { address: '104.26.7.176', family: 4 }, { address: '2606:4700:20::681a:6b0', family: 6 }, { address: '2606:4700:20::681a:7b0', family: 6 } ] } +5ms
  cypress:server:events send error: Error: You're not logged in. Run `cypress open` to open the Desktop App and log in. at Object.get (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/lib/errors.js:348:11) at /home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/lib/user.js:63:26 at tryCatcher (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at _drainQueueStep (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)     at processImmediate (internal/timers.js:439:21) { isCypressErr: true, type: 'NOT_LOGGED_IN', details: undefined, isApiError: true } +6ms
  cypress:server:events sending ipc data { type: 'get:project:statuses', data: { id: 0.44617514297200067, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' + '    at Object.get (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/lib/errors.js:348:11)\n' + '    at /home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/lib/user.js:63:26\n' + '    at tryCatcher (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n' + '    at Promise._settlePromiseFromHandler (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)\n' + '    at Promise._settlePromise (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)\n' + '    at Promise._settlePromise0 (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)\n' + '    at Promise._settlePromises (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)\n' + '    at _drainQueueStep (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)\n' + '    at _drainQueue (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)\n' + '    at Async._drainQueues (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)\n' + '    at Immediate.Async.drainQueues [as _onImmediate] (/home/dan/.cache/Cypress/4.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)\n' + '    at processImmediate (internal/timers.js:439:21)\n', message: "You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } } } +2ms
  cypress:network:agent got family { family: 4, href: 'https://download.cypress.io/desktop.json' } +15ms
  cypress:server:updater latest version of Cypress is: 4.4.1 +291ms
  cypress:server:updater new version of Cypress exists: 4.4.1 +0ms
  cypress:server:events sending ipc data { type: 'updater:check', data: { id: 0.6811526139370934, data: '4.4.1' } } +246ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler âââââââââââ¬ââââââââââââââââââââ¬âââââââââââââââ¬âââââââââââââââââââââââââââââââââ¬âââââââââââââ¬âââââââââââââââââ¬âââââââââââ¬âââââââââââââââ¬ââââââââââââââcypress:server:util:process_profiler â (index) â       group       â processCount â              pids              â cpuPercent â meanCpuPercent â memRssMb â meanMemRssMb â maxMemRssMb â
  cypress:server:util:process_profiler âââââââââââ¼ââââââââââââââââââââ¼âââââââââââââââ¼âââââââââââââââââââââââââââââââââ¼âââââââââââââ¼âââââââââââââââââ¼âââââââââââ¼âââââââââââââââ¼ââââââââââââââ¤
  cypress:server:util:process_profiler â    0    â     'cypress'     â      1       â             '4952'             â    9.78    â      4.89      â  228.53  â    183.93    â   228.53    â
  cypress:server:util:process_profiler â    1    â 'electron-shared' â      5       â '4956, 4958, 5106, 5122, 5297' â     0      â       0        â  166.93  â    107.92    â   166.93    â
  cypress:server:util:process_profiler â    2    â   'desktop-gui'   â      1       â             '5305'             â     0      â       0        â  109.67  â    109.67    â   109.67    â
  cypress:server:util:process_profiler â    3    â      'other'      â      2       â          '5322, 5323'          â     0      â       0        â   3.54   â     3.51     â    3.54     â
  cypress:server:util:process_profiler â    4    â      'TOTAL'      â      9       â              '-'               â    9.78    â      4.89      â  508.67  â    350.2     â   508.67    â
  cypress:server:util:process_profiler âââââââââââ´ââââââââââââââââââââ´âââââââââââââââ´âââââââââââââââââââââââââââââââââ´âââââââââââââ´âââââââââââââââââ´âââââââââââ´âââââââââââââââ´ââââââââââââââ+10s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler âââââââââââ¬ââââââââââââââââââââ¬âââââââââââââââ¬âââââââââââââââââââââââââââââââââ¬âââââââââââââ¬âââââââââââââââââ¬âââââââââââ¬âââââââââââââââ¬ââââââââââââââcypress:server:util:process_profiler â (index) â       group       â processCount â              pids              â cpuPercent â meanCpuPercent â memRssMb â meanMemRssMb â maxMemRssMb â
  cypress:server:util:process_profiler âââââââââââ¼ââââââââââââââââââââ¼âââââââââââââââ¼âââââââââââââââââââââââââââââââââ¼âââââââââââââ¼âââââââââââââââââ¼âââââââââââ¼âââââââââââââââ¼ââââââââââââââ¤
  cypress:server:util:process_profiler â    0    â     'cypress'     â      1       â             '4952'             â    2.46    â      4.08      â  191.46  â    186.44    â   228.53    â
  cypress:server:util:process_profiler â    1    â 'electron-shared' â      5       â '4956, 4958, 5106, 5122, 5297' â    0.14    â      0.05      â  166.93  â    127.59    â   166.93    â
  cypress:server:util:process_profiler â    2    â   'desktop-gui'   â      1       â             '5305'             â     0      â       0        â  109.67  â    109.67    â   109.67    â
  cypress:server:util:process_profiler â    3    â      'other'      â      2       â          '5524, 5525'          â     0      â       0        â   3.57   â     3.53     â    3.57     â
  cypress:server:util:process_profiler â    4    â      'TOTAL'      â      9       â              '-'               â    2.6     â      4.13      â  471.64  â    390.68    â   508.67    â
  cypress:server:util:process_profiler âââââââââââ´ââââââââââââââââââââ´âââââââââââââââ´âââââââââââââââââââââââââââââââââ´âââââââââââââ´âââââââââââââââââ´âââââââââââ´âââââââââââââââ´ââââââââââââââ+10s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler âââââââââââ¬ââââââââââââââââââââ¬âââââââââââââââ¬âââââââââââââââââââââââââââââââââ¬âââââââââââââ¬âââââââââââââââââ¬âââââââââââ¬âââââââââââââââ¬ââââââââââââââcypress:server:util:process_profiler â (index) â       group       â processCount â              pids              â cpuPercent â meanCpuPercent â memRssMb â meanMemRssMb â maxMemRssMb â
  cypress:server:util:process_profiler âââââââââââ¼ââââââââââââââââââââ¼âââââââââââââââ¼âââââââââââââââââââââââââââââââââ¼âââââââââââââ¼âââââââââââââââââ¼âââââââââââ¼âââââââââââââââ¼ââââââââââââââ¤
  cypress:server:util:process_profiler â    0    â     'cypress'     â      1       â             '4952'             â    0.93    â      3.29      â  192.52  â    187.96    â   228.53    â
  cypress:server:util:process_profiler â    1    â 'electron-shared' â      5       â '4956, 4958, 5106, 5122, 5297' â    0.15    â      0.07      â  166.93  â    137.43    â   166.93    â
  cypress:server:util:process_profiler â    2    â   'desktop-gui'   â      1       â             '5305'             â     0      â       0        â  109.67  â    109.67    â   109.67    â
  cypress:server:util:process_profiler â    3    â      'other'      â      2       â          '5710, 5711'          â     0      â       0        â   3.46   â     3.52     â    3.57     â
  cypress:server:util:process_profiler â    4    â      'TOTAL'      â      9       â              '-'               â    1.07    â      3.36      â  472.59  â    411.16    â   508.67    â
  cypress:server:util:process_profiler âââââââââââ´ââââââââââââââââââââ´âââââââââââââââ´âââââââââââââââââââââââââââââââââ´âââââââââââââ´âââââââââââââââââ´âââââââââââ´âââââââââââââââ´ââââââââââââââ+10s
dan@test1:data-dynamo> 
```

**Comment by danatemple** [comment] 2020-04-27 08:27
Screenshot:

![image](https://user-images.githubusercontent.com/11148387/80350877-a63e3c80-8871-11ea-9144-745c62957246.png)

**Comment by jennifer-shehane** [comment] 2020-04-27 09:27
Well, these DEBUG logs look identical to my DEBUG logs of opening the cypress gui successfully from a cache location, aside from the logs below:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
Xlib:  extension "XInputExtension" missing on display "localhost:10.0".
```

Are you sure you ran from a freshly installed version of Cypress in 4.4.1? We fixed an issue that presented the same as this in Ubuntu with the new snap installations of Chromium in 4.4.1. https://github.com/cypress-io/cypress/issues/7020

**Comment by danatemple** [comment] 2020-04-27 09:41
Yes. I first noticed it as I jumped from 3.8.0 to 4.4.1. Found problem started in 4.2.0 by tracing back.

"cypress run" works fine, it seems to be more a rendering thing. Could it be affected by the version of chrome installed? Recent google-chrome releases have stopped working on systems without GPUs available, and the symptoms are very similar, window appears but does not render anything. Anything to try?

**Comment by danatemple** [comment] 2020-04-27 15:24
Here is another debug trace (attached) this time with 4.4.1, as I notice it behaves quite different on startup to 4.2.0.

```
DEBUG=cypress:* npx cypress open --env server_url=http://localhost:3011 2> cypress441.stderr.txt
```

When it hangs (with the blank screen) the last 4 lines are repeated ever 10s or so.
[cypress441.stderr.txt](https://github.com/cypress-io/cypress/files/4540524/cypress441.stderr.txt)

**Comment by danatemple** [comment] 2020-04-29 10:19
Did the debug trace in the previous comment give any clues?

Have just reproduced on newly installed Ubuntu 18.04 server, opening terminal on it with ssh -X, same result.

**Comment by jennifer-shehane** [comment] 2020-05-04 09:02
Do you have anything in your `plugins` or `support` files? Have you tried removing this / reducing the tests run to a single test? Does that make a difference - are you able to run the `cypress-example-kitchensink` for example? https://github.com/cypress-io/cypress-example-kitchensink

**Comment by danatemple** [comment] 2020-05-04 11:09
Same result with kitchensink. This is kind of expected, as the blank screen is just on opening the app - this is before trying to run any tests or anything project-specific.

I'm guessing it should be reproducible by:
- spinning up an Ubuntu server (I've tried both 16.04 or 18.04) in your cloud of choice (I'm using AWS)
- ssh -X to the server
- clone the kitchensink app, npm install
- npm run cy:open

Blank GUI is seen.

**Comment by edodusi** [comment] 2020-05-04 12:49
Same issue here (Ubuntu 18.04 - cypress open via docker) and I just want to add that I solved the `Gtk-Message: Failed to load module "canberra-gtk-module"`

**Comment by gianiaz** [comment] 2020-10-28 09:13
Any news about this? Same problem just tested till 5.5.0 wrong behaviour still present.

**Comment by flotwig** [comment] 2022-03-30 19:54
Closing this since it is lacking info to be reproduced.

To anyone who is still experiencing this issue on the latest stable version of Cypress - please open a new issue referencing this one, and include your distribution, distribution version, desktop environment, desktop environment version, and whether you are using X or Wayland.

@edodusi Please open a new issue if you're still having trouble with this in Docker - although `cypress open` in Docker isn't *explicitly* supported, I can't see why it wouldn't work if everything is configured correctly.

**Closed by flotwig** 2022-03-30 19:54 UTC
Labels: OS: linux, stage: needs information, blocking
