### ISSUE TITLE
The Cypress App could not be downloaded. `Error: Corrupted download`

### ISSUE THREAD

**Issue by Joel-Raju** [cypress-io/cypress#6789] opened 2020-03-19 14:38 UTC
### Current behavior:

The Cypress App could not be downloaded. I'm not under a proxy network.

```bash
[19:54:19]  Downloading Cypress      85% 57s [title changed]
[19:54:22]  Downloading Cypress      86% 53s [title changed]
[19:54:25]  Downloading Cypress      87% 49s [title changed]
[19:54:29]  Downloading Cypress      88% 45s [title changed]
[19:54:31]  Downloading Cypress      89% 41s [title changed]
[19:54:33]  Downloading Cypress      90% 37s [title changed]
[19:54:35]  Downloading Cypress      91% 33s [title changed]
[19:54:37]  Downloading Cypress      92% 29s [title changed]
[19:54:38]  Downloading Cypress      92% 30s [title changed]
[19:54:40]  Downloading Cypress      93% 26s [title changed]
[19:54:48]  Downloading Cypress      94% 22s [title changed]
[19:55:09]  Downloading Cypress      94% 24s [title changed]
[19:55:16]  Downloading Cypress      95% 20s [title changed]
[19:55:18]  Downloading Cypress      96% 16s [title changed]
[19:55:24]  Downloading Cypress      97% 12s [title changed]
[19:55:29]  Downloading Cypress      98% 8s [title changed]
[19:55:34]  Downloading Cypress      99% 4s [title changed]
[19:55:38]  Downloading Cypress      100% 0s [title changed]
[19:55:41]  Downloading Cypress      100% 0s [failed]
[19:55:41] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.2.0?platform=darwin&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 66ae5ac2fb9e10f0d055928a12cb3fb1a25493a4d39699f0c638e9c2f1f9b02d2c5eb24a8ed0555ac9bb31512ea65d45cddf7a728c26807a97698e20fb23ab53
Computed checksum: 6474dd287f8416cbf2f146352cf4b7fc0fbd806d049fe6fb8497cbfbcd6c95e21374539074308f713ac6c8d9d81ccb7281aede4c9fb70b7ea56081d2d9d756f3

Expected downloaded file to have size: 172922629
Computed size: 172922629

----------

Platform: darwin (19.3.0)
Cypress Version: 4.2.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.2.0?platform=darwin&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 66ae5ac2fb9e10f0d055928a12cb3fb1a25493a4d39699f0c638e9c2f1f9b02d2c5eb24a8ed0555ac9bb31512ea65d45cddf7a728c26807a97698e20fb23ab53
Computed checksum: 6474dd287f8416cbf2f146352cf4b7fc0fbd806d049fe6fb8497cbfbcd6c95e21374539074308f713ac6c8d9d81ccb7281aede4c9fb70b7ea56081d2d9d756f3

Expected downloaded file to have size: 172922629
Computed size: 172922629

----------

```

### Desired behavior:

Installation should be successful.

### Test code to reproduce

Clone repo: https://github.com/Joel-Raju/webiny-js
Run `yarn install`

### Versions
- Cypress - 4.2.0
- OS: Mac OS 10.15.3 (19D76)
- Browser: Firefox 74.0 (64-bit)
- Node: v12.14.1
- Yarn: 1.21.1

**Comment by Joel-Raju** [comment] 2020-03-19 14:46
https://github.com/webiny/webiny-js/issues/763

**Comment by POD666** [comment] 2020-03-21 20:55
+1

**Comment by jennifer-shehane** [comment] 2020-03-23 09:36
Can you try downloading a previous version of Cypress like 4.1.0? I'd like to narrow down if this is a newly introduced issue.

**Comment by GuillaumeAmat** [comment] 2020-03-27 00:41
On my side it fails with both 4.1.0 and 4.2.0, in an Alpine docker image (`node:12-alpine`).

**Comment by jennifer-shehane** [comment] 2020-03-27 09:22
This may be another expression of this issue: https://github.com/cypress-io/cypress/issues/4595 Where you can have multiple versions of Cypress downloaded at the same time - causing a corrupt download? This can happen in Yarn workspaces sometimes.

**Comment by GuillaumeAmat** [comment] 2020-03-29 12:33
Yep, that was my issue... Several modules depend on Cypress in my project:

* `cypress` itself
* `@types/cypress`
* `@types/testing-library__cypress`

I obviously can't remove the typings so I ended using [the CHILD_CONCURRENCY trick](https://github.com/cypress-io/cypress/issues/4595#issuecomment-514033689) in my CI (I don't know why but I don't have any issue locally).

Really looking forward to a proper fix on the Cypress side, as you proposed in #4595 👌

Thanks for your help @jennifer-shehane!

**Comment by davidfm** [comment] 2020-06-01 15:02
Same issue with `3.4.1`

`Output:

[14:20:41]  Downloading Cypress     [started]

[14:20:56]  Downloading Cypress     [failed]

The Cypress App could not be downloaded.


Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration


Otherwise, please check network connectivity and try again:


----------


URL: https://download.cypress.io/desktop/3.4.1?platform=linux&arch=x64

Error: Corrupted download


Expected downloaded file to have checksum: 1d83944c77bc9628909ea095ea15e85dd2c2e728a3440330c42eb49cc4f3260a9276ee9f176db7f462cf8031c42744bdd3f459927f2f4c00828b969b5cb8df7a

Computed checksum: 12c982973bd9cf3a563653b5746b89a0c397b22b5f79e6ae7651fa1783cb7c892547325b7af5cbba6e3a73885aff2a5dcba4ff6e12d33bda13122318c3042651


Expected downloaded file to have size: 138660520

Computed size: 138660520


----------


Platform: linux (Debian - 10)

Cypress Version: 3.4.1
`

**Comment by jennifer-shehane** [comment] 2020-06-02 08:15
@davidfm Are you using yarn workspaces? See this comment: https://github.com/cypress-io/cypress/issues/6789#issuecomment-604899385

Closing as duplicate of #6789

**Closed by jennifer-shehane** 2020-06-02 08:15 UTC
Labels: stage: needs investigating

**Comment by kschiffer** [comment] 2020-06-17 09:38
> Closing as duplicate of [#6789](https://github.com/cypress-io/cypress/issues/6789)

That's this issue. Where is the actual original issue? Having the same problem when running in Github Actions.

**Comment by jennifer-shehane** [comment] 2020-06-29 07:49
@kschiffer Sorry, duplicate of #4595

**Comment by thecreazy** [comment] 2020-12-03 10:32
same problem today


```
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: /var/www/hs-goldenrod/wls/wl-hotelscan/node_modules/cypress
Output:
Installing Cypress (version: 4.12.1)

[10:27:44]  Downloading Cypress     [started]
[10:27:45]  Downloading Cypress      0% 0s [title changed]
[10:27:46]  Downloading Cypress      1% 70s [title changed]
[10:27:46]  Downloading Cypress      1% 80s [title changed]
[10:27:46]  Downloading Cypress      2% 45s [title changed]
[10:27:46]  Downloading Cypress      3% 33s [title changed]
[10:27:46]  Downloading Cypress      4% 27s [title changed]
[10:27:46]  Downloading Cypress      4% 29s [title changed]
[10:27:47]  Downloading Cypress      5% 25s [title changed]
[10:27:47]  Downloading Cypress      6% 22s [title changed]
[10:27:47]  Downloading Cypress      7% 20s [title changed]
[10:27:47]  Downloading Cypress      8% 19s [title changed]
[10:27:47]  Downloading Cypress      9% 17s [title changed]
[10:27:47]  Downloading Cypress      10% 16s [title changed]
[10:27:47]  Downloading Cypress      10% 17s [title changed]
[10:27:47]  Downloading Cypress      11% 16s [title changed]
[10:27:47]  Downloading Cypress      12% 15s [title changed]
[10:27:47]  Downloading Cypress      13% 15s [title changed]
[10:27:48]  Downloading Cypress      14% 14s [title changed]
[10:27:48]  Downloading Cypress      15% 14s [title changed]
[10:27:48]  Downloading Cypress      16% 13s [title changed]
[10:27:48]  Downloading Cypress      16% 14s [title changed]
[10:27:48]  Downloading Cypress      17% 13s [title changed]
[10:27:48]  Downloading Cypress      18% 13s [title changed]
[10:27:48]  Downloading Cypress      19% 12s [title changed]
[10:27:48]  Downloading Cypress      20% 12s [title changed]
[10:27:48]  Downloading Cypress      21% 12s [title changed]
[10:27:48]  Downloading Cypress      22% 11s [title changed]
[10:27:49]  Downloading Cypress      22% 12s [title changed]
[10:27:49]  Downloading Cypress      23% 11s [title changed]
[10:27:49]  Downloading Cypress      24% 11s [title changed]
[10:27:49]  Downloading Cypress      25% 11s [title changed]
[10:27:49]  Downloading Cypress      26% 11s [title changed]
[10:27:49]  Downloading Cypress      27% 10s [title changed]
[10:27:49]  Downloading Cypress      27% 11s [title changed]
[10:27:49]  Downloading Cypress      28% 10s [title changed]
[10:27:49]  Downloading Cypress      29% 10s [title changed]
[10:27:49]  Downloading Cypress      30% 10s [title changed]
[10:27:50]  Downloading Cypress      31% 10s [title changed]
[10:27:50]  Downloading Cypress      32% 9s [title changed]
[10:27:50]  Downloading Cypress      33% 9s [title changed]
[10:27:50]  Downloading Cypress      34% 9s [title changed]
[10:27:50]  Downloading Cypress      35% 9s [title changed]
[10:27:50]  Downloading Cypress      36% 9s [title changed]
[10:27:50]  Downloading Cypress      37% 9s [title changed]
[10:27:50]  Downloading Cypress      38% 8s [title changed]
[10:27:50]  Downloading Cypress      39% 8s [title changed]
[10:27:51]  Downloading Cypress      40% 8s [title changed]
[10:27:51]  Downloading Cypress      41% 8s [title changed]
[10:27:51]  Downloading Cypress      42% 8s [title changed]
[10:27:51]  Downloading Cypress      43% 8s [title changed]
[10:27:51]  Downloading Cypress      44% 7s [title changed]
[10:27:51]  Downloading Cypress      45% 7s [title changed]
[10:27:51]  Downloading Cypress      46% 7s [title changed]
[10:27:51]  Downloading Cypress      47% 7s [title changed]
[10:27:52]  Downloading Cypress      48% 7s [title changed]
[10:27:52]  Downloading Cypress      49% 7s [title changed]
[10:27:52]  Downloading Cypress      50% 7s [title changed]
[10:27:52]  Downloading Cypress      51% 6s [title changed]
[10:27:52]  Downloading Cypress      52% 6s [title changed]
[10:27:52]  Downloading Cypress      53% 6s [title changed]
[10:27:52]  Downloading Cypress      54% 6s [title changed]
[10:27:52]  Downloading Cypress      55% 6s [title changed]
[10:27:52]  Downloading Cypress      56% 6s [title changed]
[10:27:53]  Downloading Cypress      57% 6s [title changed]
[10:27:53]  Downloading Cypress      58% 5s [title changed]
[10:27:53]  Downloading Cypress      59% 5s [title changed]
[10:27:53]  Downloading Cypress      60% 5s [title changed]
[10:27:53]  Downloading Cypress      61% 5s [title changed]
[10:27:53]  Downloading Cypress      62% 5s [title changed]
[10:27:53]  Downloading Cypress      63% 5s [title changed]
[10:27:53]  Downloading Cypress      64% 5s [title changed]
[10:27:54]  Downloading Cypress      65% 4s [title changed]
[10:27:54]  Downloading Cypress      66% 4s [title changed]
[10:27:54]  Downloading Cypress      67% 4s [title changed]
[10:27:54]  Downloading Cypress      68% 4s [title changed]
[10:27:54]  Downloading Cypress      69% 4s [title changed]
[10:27:54]  Downloading Cypress      70% 4s [title changed]
[10:27:54]  Downloading Cypress      71% 4s [title changed]
[10:27:54]  Downloading Cypress      72% 4s [title changed]
[10:27:54]  Downloading Cypress      73% 3s [title changed]
[10:27:55]  Downloading Cypress      74% 3s [title changed]
[10:27:55]  Downloading Cypress      75% 3s [title changed]
[10:27:55]  Downloading Cypress      76% 3s [title changed]
[10:27:55]  Downloading Cypress      77% 3s [title changed]
[10:27:55]  Downloading Cypress      78% 3s [title changed]
[10:27:55]  Downloading Cypress      79% 3s [title changed]
[10:27:55]  Downloading Cypress      80% 3s [title changed]
[10:27:55]  Downloading Cypress      81% 2s [title changed]
[10:27:55]  Downloading Cypress      82% 2s [title changed]
[10:27:56]  Downloading Cypress      83% 2s [title changed]
[10:27:56]  Downloading Cypress      84% 2s [title changed]
[10:27:56]  Downloading Cypress      85% 2s [title changed]
[10:27:56]  Downloading Cypress      86% 2s [title changed]
[10:27:56]  Downloading Cypress      87% 2s [title changed]
[10:27:56]  Downloading Cypress      88% 2s [title changed]
[10:27:56]  Downloading Cypress      89% 1s [title changed]
[10:27:56]  Downloading Cypress      90% 1s [title changed]
[10:27:57]  Downloading Cypress      91% 1s [title changed]
[10:27:57]  Downloading Cypress      92% 1s [title changed]
[10:27:57]  Downloading Cypress      93% 1s [title changed]
[10:27:57]  Downloading Cypress      94% 1s [title changed]
[10:27:57]  Downloading Cypress      95% 1s [title changed]
[10:27:57]  Downloading Cypress      96% 0s [title changed]
[10:27:57]  Downloading Cypress      96% 1s [title changed]
[10:27:57]  Downloading Cypress      97% 0s [title changed]
[10:27:57]  Downloading Cypress      98% 0s [title changed]
[10:27:58]  Downloading Cypress      99% 0s [title changed]
[10:27:58]  Downloading Cypress      100% 0s [title changed]
[10:27:59]  Downloading Cypress      100% 0s [failed]
[10:27:59] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.12.1?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 07fbc78fe7cc0d5418bf6c112411a8c8f2ab35691e8630a5090b87ce50d7b4971d9340aff8cafc7b619b92efab993748240ed84a8628fe1d15d8b4f4348612e7
Computed checksum: 2eeee00fc0256cb1d32309782494db4e27c2820fed2f79c18844085a59225987d344371b5f3d49b8a15d47c46af9fdee0bce43463f8060a957d0537521555059

Expected downloaded file to have size: 188839557
Computed size: 188839557

----------

Platform: linux (CentOS - 7.7.1908)
Cypress Version: 4.12.1
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.12.1?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 07fbc78fe7cc0d5418bf6c112411a8c8f2ab35691e8630a5090b87ce50d7b4971d9340aff8cafc7b619b92efab993748240ed84a8628fe1d15d8b4f4348612e7
Computed checksum: 2eeee00fc0256cb1d32309782494db4e27c2820fed2f79c18844085a59225987d344371b5f3d49b8a15d47c46af9fdee0bce43463f8060a957d0537521555059

Expected downloaded file to have size: 188839557
Computed size: 188839557

----------

```

**Comment by Imaver** [comment] 2020-12-07 17:02
Same issue today on my side too:
I```
nstalling Cypress (version: 4.12.1)

[17:00:49]  Downloading Cypress     [started]
[17:00:49]  Downloading Cypress      0% 0s [title changed]
[17:00:49]  Downloading Cypress      3% 3s [title changed]
[17:00:49]  Downloading Cypress      8% 2s [title changed]
[17:00:50]  Downloading Cypress      11% 2s [title changed]
[17:00:50]  Downloading Cypress      16% 2s [title changed]
[17:00:50]  Downloading Cypress      21% 2s [title changed]
[17:00:50]  Downloading Cypress      23% 2s [title changed]
[17:00:50]  Downloading Cypress      26% 2s [title changed]
[17:00:50]  Downloading Cypress      29% 2s [title changed]
[17:00:50]  Downloading Cypress      31% 2s [title changed]
[17:00:50]  Downloading Cypress      35% 2s [title changed]
[17:00:50]  Downloading Cypress      38% 2s [title changed]
[17:00:50]  Downloading Cypress      43% 2s [title changed]
[17:00:51]  Downloading Cypress      47% 1s [title changed]
[17:00:51]  Downloading Cypress      51% 1s [title changed]
[17:00:51]  Downloading Cypress      54% 1s [title changed]
[17:00:51]  Downloading Cypress      58% 1s [title changed]
[17:00:51]  Downloading Cypress      61% 1s [title changed]
[17:00:51]  Downloading Cypress      65% 1s [title changed]
[17:00:51]  Downloading Cypress      69% 1s [title changed]
[17:00:51]  Downloading Cypress      72% 1s [title changed]
[17:00:51]  Downloading Cypress      75% 1s [title changed]
[17:00:51]  Downloading Cypress      79% 1s [title changed]
[17:00:52]  Downloading Cypress      82% 1s [title changed]
[17:00:52]  Downloading Cypress      85% 0s [title changed]
[17:00:52]  Downloading Cypress      87% 0s [title changed]
[17:00:52]  Downloading Cypress      90% 0s [title changed]
[17:00:52]  Downloading Cypress      93% 0s [title changed]
[17:00:52]  Downloading Cypress      94% 0s [title changed]
[17:00:52]  Downloading Cypress      95% 0s [title changed]
[17:00:52]  Downloading Cypress      97% 0s [title changed]
[17:00:52]  Downloading Cypress      99% 0s [title changed]
[17:00:53]  Downloading Cypress      99% 0s [failed]
[17:00:53] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.12.1?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 07fbc78fe7cc0d5418bf6c112411a8c8f2ab35691e8630a5090b87ce50d7b4971d9340aff8cafc7b619b92efab993748240ed84a8628fe1d15d8b4f4348612e7
Computed checksum: ff8421ae030656ab24dda85cdfc3c93db3c7628ee66b59fb0fb10c9fa202ed341712e94869de1bf492ba850b00886132b62a7f6e8c81429c0f5fa25cbdb0cb72

Expected downloaded file to have size: 188839557
Computed size: 188839557
```

**Comment by jennifer-shehane** [comment] 2020-12-08 05:06
Closing as duplicate of #4595
