### ISSUE TITLE
"Experimental Fetch Polyfill" in v5.x results in 2nd "cy.visit" doing nothing forever

### ISSUE THREAD

**Issue by jverhoelen** [cypress-io/cypress#8845] opened 2020-10-14 14:42 UTC
### Current behavior
When starting with Cypress at ~4.11.0 we polyfilled Fetch API on our own (the `win.eval('<unfetch.js source code>'); win.fetch = win.unfetch;` hack). It worked nicely. We need to polyfill fetch in order to mock HTTP requests that AWS Cognito/AWS Amplify do.

After upgrading to Cypress 5.3.0 we tried to replace our fetch polyfill by the toggling `experimentalFetchPolyfill` to `true`. **Basically it works for all test suites (files) that use `cy.visit` exactly and only once**. Unfortunately we experienced that all test suites with **more than one cy.visit** failed. To be more precise: they run forever without timing out. In each of these tests the second call of `cy.visit` causes the test to "go into an infinite loop". It just does nothing for a very long time and does not proceed:

<img width="535" alt="Screenshot 2020-10-14 at 15 07 20" src="https://user-images.githubusercontent.com/6791360/95998592-4e9e8800-0e35-11eb-89d5-99a3b6938de0.png">

This leads us to the conclusion that using `experimentalFetchPolyfill` could, under some circumstances, make `cy.visit` doing nothing anymore.

### Desired behavior
`cy.visit` should visit the passed URL and the test should proceed.

### Test code to reproduce
We can reproduce the behaviour with our closed-source application. This application is deployed to the internet publicly. Also a minimal Cypress test against this application can verify the bug. The only problem: my customer does not allow me to associate the URL of the page with a test code for reproduction here.
It would be possible for me to provide the test scenario via DM on twitter for example: twitter.com/jverhoelen

I setup a test application that just demonstrates the setup itself: web app with AWS Amplify/Cognito, tested by Cypress 5.3.0 with experimental fetch polyfill enabled. Unfortunately it's not possible to reproduce the problem with this - it could just help to illustrate how one of our problematic tests look like:
https://github.com/jverhoelen/cypress-experimental-fetch-polyfill-failure

### Versions
Tried with Cypress 5.2.0, 5.3.0, 5.4.0 on Mac OS 10.15.6 with Node 12.15.0

**Comment by pschaub** [comment] 2020-10-14 17:48
idea for a workaround:
did you try to use the new `route2`? see https://docs.cypress.io/api/commands/route2.html

**Comment by pschaub** [comment] 2020-10-15 12:21
Are you able to reproduce this with Cypress 5.2.0?

**Comment by jverhoelen** [comment] 2020-10-15 14:11
Yes, same behaviour with 5.2, 5.3 and 5.4.

**Comment by pschaub** [comment] 2020-10-22 21:09
I suggest to use the debug output to check if you see any reason why this happens. See https://docs.cypress.io/guides/references/troubleshooting.html#Print-DEBUG-logs

I also suggest checking which browser is being used. Does the problem occur in both Electron and Chrome?

**Comment by pschaub** [comment] 2020-11-30 13:09
@jverhoelen do you still have this issue in Cypress 6.0?

**Comment by Marcelinna** [comment] 2020-12-29 14:50
I have the same problem, @jverhoelen you resoled it?

**Comment by bahmutov** [comment] 2020-12-29 20:07
Since we have deprecated this experimental temporary fix in favor of `cy.intercept`, I am closing this issue.

**Closed by bahmutov** 2020-12-29 20:07 UTC
Labels: experiment: fetch polyfill
