### ISSUE TITLE
cypress failed to make connection to devTools

### ISSUE THREAD

**Issue by cullsin** [cypress-io/cypress#5634] opened 2019-11-07 17:05 UTC
I am a newbie. I was able to run the test suit once. but after that It throws error ( as attached ) 

### Current behavior:

![image](https://user-images.githubusercontent.com/5137598/68410357-98efa180-01ae-11ea-9280-6be472c29160.png)

### Steps to reproduce: (app code and test code)

Install cypress and run it once in mac machine.

### Versions

Cypress 3.6.0
mac machine
chrome 57

**Comment by jennifer-shehane** [comment] 2019-11-07 20:33
Duplicate of https://github.com/cypress-io/cypress/issues/5445

If you are using `cypress-log-to-output`, updating that plugin to the latest version will fix your issue.

**Closed by jennifer-shehane** 2019-11-07 20:33 UTC

**Comment by cullsin** [comment] 2019-11-08 14:51
Hello, I never use anything other than cypress. how and where do I need to update cypress-log-to-output plugin ?

**Comment by cullsin** [comment] 2019-11-08 15:01
BTW, Test cases are running "Electron 73" . Only chrome it is not connecting

**Comment by flotwig** [comment] 2019-11-08 15:25
@cullsin If you don't know what `cypress-log-to-output` is, you don't need to worry about it. Do you still have the Chrome from the first time you ran Cypress open? Close that Chrome before restarting Cypress.

**Comment by cullsin** [comment] 2019-11-08 16:30
Ok. I have restarted the machine fresh today. I am sorry to say it is failing to connect with chrome.

**Comment by ray1618** [comment] 2019-12-11 13:09
Same issue for me, I am not using cypres-log-to-output
