### ISSUE TITLE
Selector TypeError: Cannot read property 'length' of undefined on salesforce page

### ISSUE THREAD

**Issue by tfajks** [cypress-io/cypress#9206] opened 2020-11-16 13:24 UTC
### Current behavior

- login to any salesforce application
- click on cypress selector tool (arrow) and click on any element to see selector
- selector displayed
### Desired behavior

 selector is always the same: "body"
 error in console:
```
cypress_runner.js:49413 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@40]' TypeError: Cannot read property 'length' of undefined
    at superMatcher (cypress_runner.js:88491)
    at Sizzle.select (cypress_runner.js:88687)
    at Function.Sizzle [as find] (cypress_runner.js:86855)
    at jQuery.fn.init.find (cypress_runner.js:88886)
    at getOrCreateSelectorHelperDom (cypress_runner.js:199120)
    at Object.addOrUpdateSelectorPlaygroundHighlight (cypress_runner.js:199152)
    at AutIframe._clearHighlight (cypress_runner.js:197891)
    at AutIframe.toggleSelectorHighlight (cypress_runner.js:198058)
    at cypress_runner.js:198629
    at i (cypress_runner.js:49413)
    at trackDerivedFunction (cypress_runner.js:49413)
    at e.track (cypress_runner.js:49413)
    at e.onInvalidate (cypress_runner.js:49413)
    at e.runReaction (cypress_runner.js:49413)
    at runReactionsHelper (cypress_runner.js:49413)
    at reactionScheduler (cypress_runner.js:49413)
```
### Test code to reproduce

```js
     cy.request('{yout_salesforce_login_link}.salesforce.com/?un=_login_&pw={password}')
    .then(() => {
     cy.visit('{your_salesforce_app_welcome_page}' );
     })
```
### Versions
5.6.0

<img width="942" alt="cypress_slesforce_bug" src="https://user-images.githubusercontent.com/11328178/99258009-334de080-2818-11eb-99e0-1d42cd839fad.png">

**Comment by sainthkh** [comment] 2021-01-12 05:55
Sorry for the late reply. It seems that it's a duplicate of #6058. In [a comment of that issue](https://github.com/cypress-io/cypress/issues/6058#issuecomment-641077068), it could be solved by using [shadow DOM support](https://docs.cypress.io/api/commands/shadow.html). It's now official since 5.3.0.

**Comment by sainthkh** [comment] 2021-01-12 05:59
Confirmed that the bug is still happening in 6.2.1 with the code below:

```js
it('selector playground error', () => {
  cy.visit('https://help.doterra.com/')
})
```

**Comment by tfajks** [comment] 2021-01-12 08:02
Yes it's the same issue and it's still happening.

**Comment by tit** [comment] 2021-02-23 14:24
Confirmed that the bug is still happening in 6.5.0 with the salesforce.

**Comment by uniqbit-julian** [comment] 2021-04-02 18:22
Any updates on this issue so far? Issue is still occuring with the cypress version 6.6.0. It seems to be only occuring once shadow dom is enabled within cypress. But this is necessary as salesforce works a lot with shadow dom components.

The issue is also going deeper as we're currently not able to set up an e2e testing suite on SF as we're not able to access shadow dom elements within a running salesforce instance. It seems to be related to this comment: https://github.com/cypress-io/cypress/issues/6058#issuecomment-570646327

**Comment by tit** [comment] 2021-05-05 20:32
@jennifer-shehane 
Any updates on this issue so far? Very often, when testing Salesforce, this error appears...

**Comment by L0wry** [comment] 2021-11-02 16:56
I've spent quite a bit of time on this today. I'm using 8.7.0.

in `openMode` It appears to only replicate for me after doing a re-run of a specific test. 
Once replicated the issue will persist on each re-run until I close the browser.
At this point starting a test from scratch the test will then pass which makes me feel like cypress is bleeding state across test executions. 

Reading through the source code it looks like `elems` is undefined which suggests this line sometimes isn't working as expected with with the shadow dom.

`elems = seed || byElement && Expr.find['TAG']('*', outermost)`

I'll try and keep this post updated if I find out anything more

**Comment by AtofStryker** [comment] 2023-01-09 20:26
Is this issue still happening @tfajks @tit ?

**Comment by AtofStryker** [comment] 2023-02-07 22:46
Going to close this issue due to inactivity but if this continues to be a problem please open another issue!

**Closed by AtofStryker** 2023-02-07 22:46 UTC
Labels: type: bug, stage: ready for work, topic: selector playground 🚸
