### ISSUE TITLE
Iframe issue - postmessage events are going to the wrong window

### ISSUE THREAD

**Issue by rakeshsukla53** [cypress-io/cypress#14367] opened 2020-12-31 01:11 UTC
We are having an issue with nested frames where flinks ( third party payment service ) postmessage events are going to the wrong window. We were wondering if your support had ever encountered this issue before and if there was any simple resolution, ideally a configuration change that would send the messages to the relative parent (window.parent) rather than the absolute parent (window.top)

**Window arrangement**

```
top

     - spec file ( iframe )

     - application under test ( iframe )

          - flinks (iframe)
```

When we hit the final continue button in flinks, there is a postmessage event triggered in the application but you don't see that call when browser is controlled by cypress. It seems like the event is getting dropped for some reason and we believe it's going to the wrong window. 

Our Cypress code will not be helpful here but here is a sample snippet 

   ```js
    cy.getIframeBody(flinkPage.flinksIframe).as("iframe");
    cy.get("@iframe").find(flinkPage.flinksListItem).should("be.exist").click();
    cy.get("@iframe").find(flinkPage.flinksUsername).type("Greatday");
    cy.get("@iframe").find(flinkPage.flinksPassword).type("Everyday");
    cy.get("@iframe").find(flinkPage.flinksTermsCheckbox).click();
    cy.get("@iframe").find(flinkPage.flinksSubmitButton).click();
    cy.get("@iframe")
      .xpath("//li/text()")
      .then(($item) => {
        let answer = $item.text();
        cy.get("@iframe")
          .find(flinkPage.flinksQuestion)
          .should("be.exist")
          .clear()
          .type(answer);
      });
    cy.pause();
    cy.get("@iframe").findByText("Continue").click();
    cy.get("@iframe").find(flinkPage.flinksAccountsList).eq(1).click();
    cy.get("@iframe").findByText("Continue").click();
```

**Comment by flotwig** [comment] 2022-02-03 21:44
Cypress has code to try and intercept references to `window.top` to reference the application-under-test's iframe (AUT iframe). A workaround could be to wait for `postMessage`s on `window.top`, and then re-emit them to the AUT iframe as they are received.

Closing since it is covered by #7297

**Closed by flotwig** 2022-02-03 21:44 UTC

**Comment by rgcunha** [comment] 2023-02-10 00:18
I am having the same issue. Tried Cypress 8.0.0 and more recently version 12.5.1 but the issue is still there unfortunately.

**Comment by rgcunha** [comment] 2023-02-11 23:50
Based on @flotwig suggestion I tried to implement the following code in our cypress spec and it fixed the issue:

```
    // listen for events bubbling up to the top window: cypress specs
    // then re-emits those events down to the application under test (AUT)
    cy.window().then((win) => {
      win.top.addEventListener("message", (e) => {
        win.postMessage({...e.data}, '*');
      })
    })
```

**Comment by thijsnado** [comment] 2024-11-13 20:03
Is it possible to fake the event origin for this? I tried the solution at https://github.com/cypress-io/cypress/issues/14367#issuecomment-1426900925 and it works but the event origin wouldn't match up to what it would be if it was rendered outside of cypress.
