### ISSUE TITLE
Cypress cy.visit redirects to HTML and is unable to load main.js  / Cypress UI lost

### ISSUE THREAD

**Issue by ethernal** [cypress-io/cypress#3124] opened 2019-01-13 14:40 UTC
### Is this a Feature or Bug?

Bug. Possibly in my configuration. I did post a question on gitter and was without answer. Also it seems that more context will be beneficial so using GitHub for it.

### Current behavior:

When running `npm run server` and then `npm run cypress` from https://github.com/ethernal/react-boilerplate and selecting `smoketest_homepage_spec.js` Cypress runs and redirects to the page with 'Hello World'. No JS is loaded so the App and styles are not loaded.

Also there is no Cypress UI/console (framebusting?).

Video (MP4) file in ZIP as MP4 are not supported.

[cypress-react-app-redirect-and-ui-lost-video.zip](https://github.com/cypress-io/cypress/files/2753165/cypress-react-app-redirect-and-ui-lost-video.zip)

When running localhost manually it loads OK (console tab)..
![cypress-browser-manually-run-localhost-console-tab png](https://user-images.githubusercontent.com/714658/51086554-76d0f280-1748-11e9-92e2-508da1737221.png)

..and Network tab:
![cypress-browser-manually-run-localhost-network-tab](https://user-images.githubusercontent.com/714658/51086555-76d0f280-1748-11e9-95f5-f79c25179d96.png)

When run by Cypress it cannot find the main.js served by WDS from memory:
![cypress-chrome-unable-to-find-main-js](https://user-images.githubusercontent.com/714658/51086556-76d0f280-1748-11e9-9305-da9611a69edc.png)

This is URL copied to Firefox:
![localhost-server-accessed-from-firefox](https://user-images.githubusercontent.com/714658/51086557-77698900-1748-11e9-9ce9-3ae40884648c.png)

Running Cypress in debug/log (localStorage.debug='cypress/*' in console) mode shows:

```
GET http://localhost:8080/__/main.js net::ERR_ABORTED
Navigated to http://localhost:61036/__/
VM47 cypress_runner.js:153927 Download the React DevTools for a better development experience: https://fb.me/react-devtools
VM47 cypress_runner.js:114815 Download the React DevTools for a better development experience: https://fb.me/react-devtools
VM47 cypress_runner.js:68763 Slow network is detected. Fallback font will be used while loading: http://localhost:61036/__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.6.3
VM47 cypress_runner.js:163613 console.clear() was prevented due to 'Preserve log'
localhost/:13 GET http://localhost:8080/__/main.js net::ERR_ABORTED
Navigated to http://localhost:8080/__/
Navigated to http://localhost:61036/__/
VM57 cypress_runner.js:153927 Download the React DevTools for a better development experience: https://fb.me/react-devtools
VM57 cypress_runner.js:114815 Download the React DevTools for a better development experience: https://fb.me/react-devtools
VM57 cypress_runner.js:68763 Slow network is detected. Fallback font will be used while loading: http://localhost:61036/__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.6.3
VM57 cypress_runner.js:163613 console.clear() was prevented due to 'Preserve log'
```

### Desired behavior:

Run a test and return fail/pass, see the Cypress UI. Tell me what I am doing wrong.

### Steps to reproduce: (app code and test code)

Clone latest commit from: https://github.com/ethernal/react-boilerplate

run:
`yarn install`
`npm run server`
`npm run cypress`

Select `smoketest_homepage_spec.js` test. It will show the HTML file without JS loaded.

### Versions

Cypress package version: 3.1.4
Cypress binary version: 3.1.4
Windows 10 1803 Enterprise
Browser: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by ethernal** [comment] 2019-01-14 07:33
When running tests from first examples (testing true to be true and true to be false), this is my OS browser:
![cypress-test-false-is-true-same-browser](https://user-images.githubusercontent.com/714658/51100558-f1485380-17d6-11e9-9e05-1eec46329876.png)

Cypress Task Runner UI shows Chrome 64 as well:
![cypress-runner-version](https://user-images.githubusercontent.com/714658/51100559-f1e0ea00-17d6-11e9-943b-a6cb6e6a8e11.png)

**Comment by ethernal** [comment] 2019-01-15 12:10
I have also checked with Chrome 71 - same behavior with enterprise version. No if there was a way to revert that change it would be great. @jennifer-shehane are you able to provide chrome enterprise installers for version that works for you so I can check if this is configuration issue or Chrome issue?

**Comment by ethernal** [comment] 2019-01-22 17:03
When testing with Electron (builtin setup) then everything works. I still think this might be an issue with my configuration of webpack/babel. Are there some settings that look incorrect from Cypress perspective that would make the code work with Electron but not Chrome?

**Comment by ethernal** [comment] 2019-01-22 17:44
When testing with Electron (builtin setup) then everything works. I just now tested with Chrome 71 on my desktop PC and it seems there are settings in Chrome managed via GPO that make Cypress fail.

So this is an issue with my configuration of Chrome as Electron will use engine that is not managed by admins. Is there a way to check which setting(s) is/are affecting Cypress or is there a way to use some custom installation of Chrome (portable?) and point Cypress to it ex. npm/yarn dependency?

**Comment by flotwig** [comment] 2019-01-22 17:48
@ethernal I'm glad you commented with an update, I was having trouble reproducing this behavior under Chrome 71. If it's localized to your group policy then I can press pause on that.

Re: installing other versions of Chrome - You can install Chromium (the open source side of Chrome), and we support that. You can also install Chrome Canary, which is the nightly build of Chrome. Both of these will be auto-detected next time you run Cypress.

Here's some docs about that: https://docs.cypress.io/guides/core-concepts/launching-browsers.html#Browsers

**Comment by ethernal** [comment] 2019-01-24 18:02
Yes it does. I did check earlier and that config changed nothing as you said. Although first change made the internal browser use Electron so that was misleading. I think we can close the issue. PS is there a way to check what settings make Chrome act so strange? It would be useful for troubleshooting I believe.

**Comment by flotwig** [comment] 2019-01-24 18:10
@ethernal You can visit `chrome://policy` in Chrome and click "export to JSON", then share that file with us here. Thanks for offering, that will be helpful for us to debug issues for enterprise users down the road.

**Comment by ethernal** [comment] 2019-01-26 20:50
I removed the domain names and internal addresses but it is all. No real data/options are removed::

```
{
   "chromePolicies": {
      "BackgroundModeEnabled": {
         "level": "mandatory",
         "scope": "machine",
         "source": "sourcePlatform",
         "value": false
      },
      "HomepageLocation": {
         "level": "mandatory",
         "scope": "machine",
         "source": "sourcePlatform",
         "value": "https://internalNetwork.domain.com/"
      },
      "JavaScriptAllowedForUrls": {
         "level": "mandatory",
         "scope": "machine",
         "source": "sourcePlatform",
         "value": [ "*.domain.com ", "*.internalDomain.internal " ]
      },
      "ProxySettings": {
         "level": "mandatory",
         "scope": "machine",
         "source": "sourcePlatform",
         "value": {
            "ProxyMode": "system"
         }
      },
      "SyncDisabled": {
         "level": "mandatory",
         "scope": "machine",
         "source": "sourcePlatform",
         "value": true
      }
   },
   "extensionPolicies": {
      "ghbmnnjooekpmoecnnnilnnbdlolhkhi": {

      }
   }
}
```

**Comment by flotwig** [comment] 2019-02-20 20:30
Been looking in to the proxy problems, and it looks your `ProxyMode` is set to `system` by an administrator. This forces Chrome to use the system proxy for all requests instead of using Cypress's special testing proxy, which is what is causing the behavior described in this issue. It's hard to fix this issue from our end without resorting to hacky workarounds that feed Chrome fake registry data. Closing for now as a duplicate of #1253

**Closed by flotwig** 2019-02-20 20:30 UTC
Labels: browser: chrome, stage: needs investigating, type: bug
