### ISSUE TITLE
Cypress failed to render HTML response on I-Frame 

### ISSUE THREAD

**Issue by Dan5123** [cypress-io/cypress#26442] opened 2023-04-06 09:09 UTC
### Current behavior

I have been trying to automate user journey which includes making a payment and receiving confirmation on the page to say payment has been done, after submitting the payment calls are being made to payment gateway and in return payment gateway send html response which needs to render on I-Frame, Cypress is failing in process and ending the test before it can receive confirmation on the page, upon debugging in one of the response received from payment gateway there is a default message from Cypress ("Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.").

This message has been generated by Cypress in one of the response, I can share the complete code upon request

 
![error1](https://user-images.githubusercontent.com/106591615/230327229-e41adf3f-27fe-4f1c-ade9-b2307a953d86.png)
![error2](https://user-images.githubusercontent.com/106591615/230327330-fbc927ee-e2e6-485e-8904-15ee57ef78a8.png)
![error-3](https://user-images.githubusercontent.com/106591615/230327337-f67fbf8d-fe1a-4120-b019-3a4de2a6a2ce.png)

### Desired behavior

Cypress should render the response on I-Frame and the payment should be processed 

![payment](https://user-images.githubusercontent.com/106591615/230328048-91c81886-1cb0-4911-b812-2f5a71fd6ca4.png)

### Test code to reproduce
```js
describe('physical order', () => {

    it('B2B physical order', () => {

      
      cy.visit('https://www.highstreetvouchers.com/')
      cy.get('#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll').click()
      cy.get('.user-login-link > [href="login"]').click()
      cy.get('p > input').click()
      cy.get('#login-email').type('******@***')
      cy.get('#login-password').type('*******')
      cy.get('.button-content-flex').click()
      cy.get('[data-dropdown="d3"] > .local-nav-system__link').click()
      cy.get('[data-category-url="gifts/love2shop-holiday-gift-cards"] > figure > .product-link > picture > .product-image').click()
      cy.get('#_parkcatalogueform_WAR_shoppingsuiteportlet_submit').click()
      cy.get('.basket > .local-nav-system__link').click()
      cy.get('#continueB > .button').click()
      cy.get('#arrange-delivery').click()
      cy.get('.btn--pink').click()
      cy.wait(5000)
      cy.get('#card-number').type('*******')
      cy.get("[name='_order_WAR_shoppingsuiteportlet_paymentCard.expiryMonth']").select('04','04')
      cy.get("[name='_order_WAR_shoppingsuiteportlet_paymentCard.expiryYear']").select(2)
      cy.get('#security-card-number').type('123')
      cy.get("button[type='submit']").click()
      
      })

    })
```
### Cypress Version

12.7.0

### Node version

18.15.0

### Operating System

Windows

**Comment by nagash77** [comment] 2023-04-06 17:49
@Dan5123  Have you read through our [cy.origin](https://docs.cypress.io/guides/guides/cross-origin-testing) guide? Depending on the setup you may need to make use of cy.origin to accomplish what you want.

You may also want to turn [chromeWebSecurity](https://docs.cypress.io/guides/references/configuration#Browser) to false in your Cypress config if the iframe is on the same domain.

**Comment by Dan5123** [comment] 2023-04-11 07:38
@nagash77  Hello, this error has prompt me to start file this bug from one of the API calls

Error("Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.");

 And I am using chromeWebSecurity : false.
 
 I have tried cy.orign() as well but nothing seems to be working
 
 The code I have mentioned above can easily be replicated

**Comment by Dan5123** [comment] 2023-04-11 07:41
After submitting payment, there are 6 API calls being made by the payment gateway, Cypress is failing on them and upon close debugging/comparing with real browser, I can see Cypress is changing some of the request headers in API calls

Are you suggesting to make payment gateway API calls by using cy.orign() ?
Please bare in mind those calls are triggered by payment gateway and my code has nothing to do with it 

I tried intercepting those payment gateway API calls to correct headers in request, but there are simply too many changes Cypress is making in headers (please mention if this is the expected behaviour by Cypress)

**Comment by mjhenkes** [comment] 2023-04-21 13:36
It seems like you may be running afoul of our limited iframes support: https://github.com/cypress-io/cypress/issues/136

I'm guessing that the cypress instance injected into the rendered iframe is unable to find the parent cypress instance because it is rendered in the iframe AUT.

**Comment by Dan5123** [comment] 2023-05-02 08:23
what is the solution

**Comment by mschile** [comment] 2023-05-03 21:34
@Dan5123, do you have a project I could run to investigate? You may also want to try turning on [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments#Configuration) to see if that helps.

**Comment by chrisbreiding** [comment] 2023-05-10 14:58
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please post a reproducible example and we will re-open this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) is a good starting place for creating a reproducible example.

**Closed as not planned by chrisbreiding** 2023-05-10 14:58 UTC
