### ISSUE TITLE
Enable snapshots during "npx cypress run --headed --no-exit"

### ISSUE THREAD

**Issue by nani554** [cypress-io/cypress#7242] opened 2020-05-06 17:12 UTC
## Current behavior:
hovering effect and console.logs are not working but it works when i run below command
`npx cypress open`

### Desired behavior:
Both in normal browser(`npx cypress open`) and in headed (`npx cypress run --headed`) user view is same, flow is same, having hovering effect and console.logs would be a great feature.

looking for a flag if there or a work around.
note: iam using `--no-exit` flag when running in headed mode(eg: `npx cypress run --headed --no-exit`)

### Versions

"cypress": "^4.5.0"

**Comment by jennifer-shehane** [comment] 2020-05-07 09:28
If you are referring to the snapshots taken when commands run, these are automatically disabled during `cypress run` mode to save memory since it's interactive work is not necessary. 

It seems like passing the `numTestsKeptInMemory` flag doesn't work when passed as CLI args either. `npx cypress run --headed --no-exit --config numTestsKeptInMemory=50`

Why do you need to have interactivity when running `cypress run --headed`, why not just use `cypress open`?

**Comment by nani554** [comment] 2020-05-07 17:07
In `npx cypress open`, we need to click on spec file then test execution starts, i just need to skip this step and directly move to test execution mode.
my question is like, is this possible in "npx cypress open".

As in `npx cypress run --headed --spec "some.spec.js" --no-exit `, seems to do that, but it lacks interactive work.

How can i add interactive functionality to `npx cypress run --headed` or How can i skip spec file clicking in `npx cypress open`

**Comment by todd-williams** [comment] 2020-05-13 15:57
I've just now noticed the same "issue", although I now understand the reasoning behind it.

For context, I've been giving devs a single command—which includes the spec, the environment, and the browser flags—so that they can see the exact same things I'm seeing, which is a real boon, but of course they want to be able to debug afterwards.

**Comment by jennifer-shehane** [comment] 2021-02-03 08:31
After reviewing the reason for wanting this. I think the feature request for a --spec command during `cypress open` would resolve the requests. 

Duplicate of https://github.com/cypress-io/cypress/issues/1925

**Closed by jennifer-shehane** 2021-02-03 08:31 UTC
Labels: stage: awaiting response
