### ISSUE TITLE
Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by averri** [cypress-io/cypress#6923] opened 2020-04-02 14:36 UTC
### Current behavior:
Clicking on a chart element causes the retry to fail.

This is the error:

![image](https://user-images.githubusercontent.com/1898447/78260134-87a88800-74f5-11ea-8bdc-cf719a4bff12.png)

### Desired behavior:
The click action should work as expected. The click should select the chart in the following point:

![image](https://user-images.githubusercontent.com/1898447/78355713-1379ed00-75a6-11ea-8744-9301cc27a56a.png)

### Test code to reproduce

```javascript
context('Actions', () => {

  beforeEach(() => {
    cy.visit('https://demo.spotfire.cloud.tibco.com/spotfire/wp/analysis?file=/Public/Airbnb%20Boston%20Listings')
  })

  it('select chart value', () => {
    cy.wait(6000) // Give time for the chart to render. Ideally, this should wait on the specific HTML element.
    cy.get('div[title="Property Type Distribution"]').parent().parent().parent().click(150, 60) // This click will fail.
  })

})
```

Second version of code to reproduce that does not rely on `cy.wait()`:

```javascript
context('Actions', () => {

  beforeEach(() => {
    cy.visit('https://demo.spotfire.cloud.tibco.com/spotfire/wp/analysis?file=/Public/Airbnb%20Boston%20Listings')
  })

  it('select chart value', () => {
    cy.get('div[title="Property Type Distribution"]').as('chartTitle').parent().parent().parent()
      .within(el => {
        cy.get('div.sf-element-canvas-image').invoke('attr', 'sf-busy').should('eq', 'false')
        cy.wrap(el).as('chart').click(150, 60) // This click will fail.
      })
  })

})
```

### Versions
Windows 10, Chrome or Electron, any version.
```json
  "devDependencies": {
    "cypress": "^4.3.0"
  },
```

**Comment by averri** [comment] 2020-04-02 16:34
A better test code that does not rely on timeout:

```javascript
context('Actions', () => {

  beforeEach(() => {
    cy.visit('https://demo.spotfire.cloud.tibco.com/spotfire/wp/analysis?file=/Public/Airbnb%20Boston%20Listings')
  })

  it('select chart value', () => {
    cy.get('div[title="Property Type Distribution"]').as('chartTitle')
      .parent().parent().parent()
      .within(el => {
        cy.get('div.sf-element-canvas-image')
          .invoke('attr', 'sf-busy').should('eq', 'false')
        cy.wrap(el).as('chart').click()  // This click will fail.
      })
  })

})

```

**Comment by jennifer-shehane** [comment] 2020-04-06 09:13
I can recreate this. 

<img width="466" alt="Screen Shot 2020-04-06 at 2 06 22 PM" src="https://user-images.githubusercontent.com/1271364/78541509-bdae7a80-781b-11ea-82bf-6fe98922761b.png">

This is throwing from here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/document.ts#L34:L34

If you track the stack trace up further - this method is resolving to `null`, which is being passed along to the other commands. 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/mouse.js#L548:L548

<img width="1045" alt="Screen Shot 2020-04-06 at 3 34 44 PM" src="https://user-images.githubusercontent.com/1271364/78542428-26e2bd80-781d-11ea-84c3-79a8e57c7250.png">


The `getFirstCommonAncestor` basically does not find the current element within their common ancestors - looping through until it gets to `curEl.parentNode` that is `null`. 

<img width="328" alt="Screen Shot 2020-04-06 at 3 40 21 PM" src="https://user-images.githubusercontent.com/1271364/78542394-1fbbaf80-781d-11ea-88b2-c8427babf7e1.png">

Probably a similar situation to https://github.com/cypress-io/cypress/pull/6787 and/or https://github.com/cypress-io/cypress/issues/6707 cc @sainthkh

**Comment by sainthkh** [comment] 2020-04-06 09:16
I'll check this out.

**Comment by jennifer-shehane** [comment] 2020-04-06 09:17
@sainthkh You *may* want to VPN into east coast US because this site loads *incredibly* slow in Asia.

**Comment by sainthkh** [comment] 2020-04-07 09:07
Thankfully, the site wasn't slow in South Korea. It might be because of the world's fastest Internet South Korea has.

Anyway, I researched the problem and found the cause. 

`cy.click()`  command doesn't issue native mouse event, but it only simulates it (#311). 

To run that simulation, we check `mouseUpPhase` and `mouseDownPhase`:

https://github.com/cypress-io/cypress/blob/069b22b0d55e42ecfcddfc8f1cabf539dac0266d/packages/driver/src/cy/mouse.js#L530-L534

And then, check if the target element of `mouseDownPhase` exists:

https://github.com/cypress-io/cypress/blob/069b22b0d55e42ecfcddfc8f1cabf539dac0266d/packages/driver/src/cy/mouse.js#L542-L545

This code doesn't consider this case: what if the target element of `mouseUpPhase` doesn't exist?

That's the cause of the problem in this issue. 

When you click an item in the chart, the app tries to make a drag area, `div.sf-canvas-drag-cursor`. That's the target element of `mouseUpPhase` because it's right below the mouse pointer. 

![Screenshot from 2020-04-07 17-39-18](https://user-images.githubusercontent.com/8130013/78650871-7b0f9f80-78fa-11ea-8e9e-e5983f2e7bb7.png)

But it doesn't exist any more when `getFirstCommonAncestor()` starts. That's why `getFirstCommonAncestor()` loops up to the `<html>` tag and `null`. 

The solution might be just returning the `mouseDownPhase` element. 

Implementation isn't hard, but I'm asking this just in case to avoid breaking change:

When this code was written, was there a specific case that `mouseUpPhase` always exists?

**Closed** 2020-04-20 07:34 UTC
Labels: stage: needs review, type: bug
