### ISSUE TITLE
cy.origin throws CORS error when using Microsoft b2c credentials

### ISSUE THREAD

**Issue by conversaShawn** [cypress-io/cypress#23661] opened 2022-09-01 16:28 UTC
### Current behavior

![Screen Shot 2022-09-01 at 9 22 27 AM](https://user-images.githubusercontent.com/48733734/187964377-23845db9-520d-4b3f-8eb5-27a191683978.png)

### Desired behavior

Possibly related to [#22874](https://github.com/cypress-io/cypress/issues/22874)

### Test code to reproduce

https://github.com/conversaShawn/origin-error

### Cypress Version

10.7.0

### Node version

v14.17.5

### Operating System

mac OS 12.0.1

**Comment by emilyrohrbough** [comment] 2022-09-06 19:29
@conversaShawn Thanks for opening this issue with a reproducible example!

**Comment by AtofStryker** [comment] 2022-11-09 14:34
@conversaShawn I think this issue was fixed with #24243. I think we just missed this issue for tagging for release in the change log, but should be resolved in [10.11.0](https://docs.cypress.io/guides/references/changelog#10-11-0). I'm going to close this since I strongly believe it is fixed but if you still see something on your end we should reopen it.

https://user-images.githubusercontent.com/3980464/200857583-2d268f5d-aa6c-4259-8e71-f49f8b2698fd.mp4

**Closed by AtofStryker** 2022-11-09 14:34 UTC
Labels: type: bug, cy.origin, routed-to-e2e
