### ISSUE TITLE
Execute a subset of specs by subfolders in UI

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#759] opened 2017-10-18 10:07 UTC
### Is this a Feature or Bug?
Feature

### Current behavior:
In the Cypress UI there is only the option to run either one file or all files altogether.

### Desired behavior:
Provide a run button on subfolder level that only executes tests in spec files below that level (recursively).

**Comment by brian-mann** [comment] 2017-10-18 15:59
Duplicate of https://github.com/cypress-io/cypress/issues/681

**Closed by brian-mann** 2017-10-18 15:59 UTC
Labels: type: duplicate
