### ISSUE TITLE
Cypress crashes on running sample tests

### ISSUE THREAD

**Issue by noelrappin** [cypress-io/cypress#15200] opened 2021-02-23 23:04 UTC
### Current behavior

Ruby on Rails project, installed Cypress via `cypress-rails`, but before I can even get to the Rails specific stuff or the my-app, just the Cypress sample tests.

Running any sample test crashes the Cypress test runner with the following in the logs:

```
(node:47175) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:47319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
Error: kill EPERM
    at ChildProcess.kill (internal/child_process.js:492:26)
    at /Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:34:14
    at Promise.cancellationExecute [as _execute] (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9)
    at Promise._resolveFromExecutor (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
    at Object.kill [as close] (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:21:10)
    at Object.onError (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/project-e2e.js:58:36)
    at EventEmitter.handleError (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:174:17)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
 {
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'kill'
}
Error: kill EPERM
    at ChildProcess.kill (internal/child_process.js:492:26)
    at /Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:34:14
    at Promise.cancellationExecute [as _execute] (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9)
    at Promise._resolveFromExecutor (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
    at Object.kill [as close] (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:21:10)
    at Object.onError (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/project-e2e.js:58:36)
    at EventEmitter.handleError (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:174:17)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/noelrappin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

GET /__cypress/tests?p=cypress/integration/examples/actions.spec.js - - ms - -
GET /__cypress/tests?p=cypress/support/index.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/aliasing.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/assertions.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/connectors.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/cookies.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/cypress_api.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/files.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/local_storage.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/location.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/misc.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/navigation.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/network_requests.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/querying.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/spies_stubs_clocks.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/traversal.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/utilities.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/viewport.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/waiting.spec.js - - ms - -
GET /__cypress/tests?p=cypress/integration/examples/window.spec.js - - ms - -
````

### Desired behavior
Cypress sample tests should run

### Test code to reproduce
Happens running any or all of the Cypress sample tests

### Versions

Cypress 6.5.0, it did work in 4.12 several months ago. MacOS 11.2.1. Any browser (though sometimes it won't even connect to chrome)

**Comment by jennifer-shehane** [comment] 2021-02-24 15:57
EPERM is a permissions error. Opening Cypress will require write permissions, you'll need to verify the correct permissions are set and rerun.

Duplicate of #7640

**Closed by jennifer-shehane** 2021-02-24 15:57 UTC

**Comment by noelrappin** [comment] 2021-02-24 17:06
Pretty sure I have write permission on the on the cache directory, so what directory do I need to set?
