### ISSUE TITLE
Assertion during a Promise during a Cypress.on event does not cause a test to fail

### ISSUE THREAD

**Issue by dave-newson** [cypress-io/cypress#6917] opened 2020-04-02 07:28 UTC
### Current behavior:

A `Cypress.on` event, which returns a `Promise`, which makes an `assert` call is unable to fail a test.

Cypress correctly recognises the failure assertion, but the test case is not failed, continues, and passes.

The console shows:
```
Uncaught (in promise) AssertionError {message: "I failed!: expected true to be false",
```

Similar to https://github.com/cypress-io/cypress/issues/3497

### Desired behavior:

A failing assertion should always terminate the test case as a failure.

The use-case for this is a Plugin which performs a check on every loaded page, and happens to use a Promise as part of that check.
The check works correctly and the assertion passes/fails as desired, however that doesn't register correctly with Cypress.

### Test code to reproduce

```js
// support.js
Cypress.on('window:load', () => {
  return new Promise((resolve, reject) => {
    assert.isFalse(true, "I failed!");
  });
});
```

```js
// test-case.js
describe('I am a test', () => {
    it('Hello world', () => {
        cy.visit("/");
    });
});
```

### Versions

Cypress 4.2.0 / Chrome 75 / Debian Linux

**Comment by jennifer-shehane** [comment] 2020-04-02 10:17
Cypress commands and assertions need to be written within the context of a test in order to register properly. It doesn't have a proper reference to the currently running test to handle this from within an event listener. Duplicate of https://github.com/cypress-io/cypress/issues/6316

<img width="452" alt="Screen Shot 2020-04-02 at 4 40 39 PM" src="https://user-images.githubusercontent.com/1271364/78237397-45854380-7501-11ea-8829-9230d2b2caac.png">


You'll probably want to throw an error in the `window:load` listener, since Cypress fails the currently running test whenever an error is thrown and you can construct your own error here.

```js
Cypress.on('window:load', () => {
  throw(new Error('err'))
});

describe('I am a test', () => {
  it('Hello world', () => {
    cy.visit("index.html");
  });
});
```

<img width="452" alt="Screen Shot 2020-04-02 at 4 44 14 PM" src="https://user-images.githubusercontent.com/1271364/78237365-369e9100-7501-11ea-9a26-5707a7e813a4.png">

**Closed by jennifer-shehane** 2020-04-02 10:17 UTC

**Comment by dave-newson** [comment] 2020-04-03 00:39
Thanks for the speedy reply @jennifer-shehane, I just want to make sure you're aware of the _twist_ this has over #6316, which is the Promise.

```
Cypress.on('window:load', () => {
    return new Promise((resolve, reject) => {
        throw(new Error('err'));
    });
});

describe('I am a test', () => {
    it('Hello world', () => {
        cy.visit("/");
    });
});
```

This gives only a console error: `Uncaught (in promise) Error: err`.

The Assert at least logs as a failure under the test run, but doesn't fail the test.

So neither works for a Promise. Any ideas, or is this simply not supported?

**Comment by msaktor** [comment] 2021-05-14 12:19
I face a similar issue:
```
const authenticatedRequest = ({ url, method, body, ...other }: RequestOptions): Promise<Cypress.Response> => {
    return new Promise(resolve => {
        cy.get('@jwtToken').then(jwtToken => {
            cy.request({
                url,
                method,
                auth: {
                    bearer: jwtToken,
                },
                body,
                ...other,
            }).then(resolve);
        })
    });
};
```

then if I have a assertion in the promise handler it won't fail the scenario
```
authenticatedRequest({
    url: '/api/token',
    method: 'POST',
    failOnStatusCode: false,
}).then(response => {
    expect(response.status).to.equal(401);
});
```

I understand
> Cypress commands and assertions need to be written within the context of a test in order to register properly

How can I pass the cypress context to my promise or what other workaround can you suggest please?
