### ISSUE TITLE
After closing Cypress always Error: Unsuspected Closure

### ISSUE THREAD

**Issue by JasperSlokker** [cypress-io/cypress#23938] opened 2022-09-22 13:14 UTC
### Current behavior

When i close with the close button (top left, Mac) Cypress i always get this error: Unsuspected Closure

### Desired behavior

No error when i close Cypress

### Test code to reproduce

Start Cypress 
Close Cypress

### Cypress Version

10.8.0

### Node version

16.13.0

### Operating System

Mac OS 12.6

**Comment by idanElitzur** [comment] 2022-09-22 13:32
I've this issue as well, it's k ind of legacy issue I still experienced since v9

**Comment by JasperSlokker** [comment] 2022-09-22 13:34
> 

OK, that is not good. But I have this issue since v10.

**Comment by mjhenkes** [comment] 2022-09-29 14:53
This happens to me too 😒 

It's a dupe of https://github.com/cypress-io/cypress/issues/22132

**Closed as not planned** 2022-09-29 14:53 UTC
