### ISSUE TITLE
Cypress verification fails while trying to run it on a CI/CD pipeline on TeamCity

### ISSUE THREAD

**Issue by jaspreet1878singh** [cypress-io/cypress#26607] opened 2023-04-27 07:41 UTC
### Current behavior

While trying to run cypress tests in a CI/CD build pipeline setup on TeamCity, the verification step times out without any useful debug logs. I've tried increasing the timeout using the environment variable, but the verification step is still timing out.

### Desired behavior

The verification step should pass or display the exact root cause of failure in the debug logs.

### Test code to reproduce

Issue not dependent on code.

### Cypress Version

9.4.1

### Node version

14.16.1

### Operating System

Windows Server 2016, version 10.0

### Debug Logs

```shell
[Step 6/6] 2023-04-14T09:57:22.126Z cypress:cli CYPRESS_RUN_BINARY is executable? : true
[10:57:22][Step 6/6] 2023-04-14T09:57:22.133Z cypress:cli CYPRESS_RUN_BINARY has realpath: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe
[10:57:22][Step 6/6] 2023-04-14T09:57:22.133Z cypress:cli CYPRESS_RUN_BINARY has binaryDir: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary
[10:57:22][Step 6/6] 2023-04-14T09:57:22.134Z cypress:cli checking if executable exists D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe
[10:57:22][Step 6/6] 2023-04-14T09:57:22.134Z cypress:cli Binary is executable? : true
[10:57:22][Step 6/6] 2023-04-14T09:57:22.134Z cypress:cli binaryDir is  D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary
[10:57:22][Step 6/6] 2023-04-14T09:57:22.134Z cypress:cli Reading binary package.json from: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\resources\app\package.json
[10:57:22][Step 6/6] 2023-04-14T09:57:22.137Z cypress:cli Found binary version 9.4.1 installed in: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary
[10:57:22][Step 6/6] 2023-04-14T09:57:22.138Z cypress:cli could not read binary_state.json file at "D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\binary_state.json"
[10:57:22][Step 6/6] It looks like this is your first time using Cypress: 9.4.1
[10:57:22][Step 6/6] 2023-04-14T09:57:22.138Z cypress:cli {}
[10:57:22][Step 6/6] 
[10:57:22][Step 6/6] 2023-04-14T09:57:22.139Z cypress:cli is Verified ? undefined
[10:57:22][Step 6/6] 2023-04-14T09:57:22.139Z cypress:cli running binary verification check 9.4.1
[10:57:22][Step 6/6] 2023-04-14T09:57:22.144Z cypress:cli clearing out the verified version
[10:57:22][Step 6/6] [STARTED] Task without title.
[10:57:22][Step 6/6] 2023-04-14T09:57:22.145Z cypress:cli needs Xvfb? false
[10:57:22][Step 6/6] 2023-04-14T09:57:22.145Z cypress:cli spawning, should retry on display problem? false
[10:57:22][Step 6/6] 2023-04-14T09:57:22.145Z cypress:cli running smoke test
[10:57:22][Step 6/6] 2023-04-14T09:57:22.145Z cypress:cli using Cypress executable D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe
[10:57:22][Step 6/6] 2023-04-14T09:57:22.146Z cypress:cli smoke test command: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:57:22][Step 6/6] 2023-04-14T09:57:22.146Z cypress:cli smoke test timeout 100000 ms
[10:59:03][Step 6/6] 2023-04-14T09:59:03.929Z cypress:cli Smoke test failed: Error: Command timed out after 100000 milliseconds: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:59:03][Step 6/6] Timed out
[10:59:03][Step 6/6]     at timeoutKill (D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\node_modules\cypress\node_modules\execa\lib\kill.js:65:23)
[10:59:03][Step 6/6]     at Timeout._onTimeout (D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\node_modules\cypress\node_modules\execa\lib\kill.js:81:4)
[10:59:03][Step 6/6]     at listOnTimeout (internal/timers.js:554:17)
[10:59:03][Step 6/6]     at processTimers (internal/timers.js:497:7) {
[10:59:03][Step 6/6]   timedOut: true,
[10:59:03][Step 6/6]   signal: 'SIGTERM',
[10:59:03][Step 6/6]   originalMessage: 'Timed out',
[10:59:03][Step 6/6]   shortMessage: 'Command timed out after 100000 milliseconds: D:\\Dev\\devtools\\apps\\buildagent\\work\\8521916b12622d00\\cypress-binary\\Cypress.exe --smoke-test --ping=760\n' +
[10:59:03][Step 6/6]     'Timed out',
[10:59:03][Step 6/6]   command: 'D:\\Dev\\devtools\\apps\\buildagent\\work\\8521916b12622d00\\cypress-binary\\Cypress.exe --smoke-test --ping=760',
[10:59:03][Step 6/6]   exitCode: undefined,
[10:59:03][Step 6/6]   signalDescription: 'Termination',
[10:59:03][Step 6/6]   stdout: '',
[10:59:03][Step 6/6]   stderr: '',
[10:59:03][Step 6/6]   failed: true,
[10:59:03][Step 6/6]   isCanceled: false,
[10:59:03][Step 6/6]   killed: false
[10:59:03][Step 6/6] }
[10:59:03][Step 6/6] 2023-04-14T09:59:03.930Z cypress:cli error message: Command timed out after 100000 milliseconds: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:59:03][Step 6/6] Timed out
[10:59:03][Step 6/6] 2023-04-14T09:59:03.930Z cypress:cli error timedOut is true
[10:59:03][Step 6/6] Cypress verification timed out.
[10:59:03][Step 6/6] [FAILED] Cypress verification timed out.
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] [FAILED] 
[10:59:03][Step 6/6] [FAILED] This command failed with the following output:
[10:59:03][Step 6/6] This command failed with the following output:
[10:59:03][Step 6/6] [FAILED] 
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] [FAILED] D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:59:03][Step 6/6] D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:59:03][Step 6/6] [FAILED] 
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] [FAILED] ----------
[10:59:03][Step 6/6] ----------
[10:59:03][Step 6/6] [FAILED] 
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] [FAILED] Command timed out after 100000 milliseconds: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:59:03][Step 6/6] Command timed out after 100000 milliseconds: D:\Dev\devtools\apps\buildagent\work\8521916b12622d00\cypress-binary\Cypress.exe --smoke-test --ping=760
[10:59:03][Step 6/6] [FAILED] Timed out
[10:59:03][Step 6/6] Timed out
[10:59:03][Step 6/6] [FAILED] 
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] [FAILED] ----------
[10:59:03][Step 6/6] ----------
[10:59:03][Step 6/6] [FAILED] 
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] [FAILED] Platform: win32-x64 (10.0.14393)
[10:59:03][Step 6/6] Platform: win32-x64 (10.0.14393)
[10:59:03][Step 6/6] [FAILED] Cypress Version: 9.4.1
[10:59:03][Step 6/6] Cypress Version: 9.4.1
[10:59:03][Step 6/6] npm ERR! code ELIFECYCLE
[10:59:03][Step 6/6] npm ERR! errno 1
[10:59:03][Step 6/6] npm ERR! cradle-ui@6.2.0-SNAPSHOT cy:run:edge:pre-prod3: `cypress run --browser edge --env envName=preprod3 `
[10:59:03][Step 6/6] npm ERR! Exit status 1
[10:59:03][Step 6/6] npm ERR! 
[10:59:03][Step 6/6] npm ERR! Failed at the cradle-ui@6.2.0-SNAPSHOT cy:run:edge:pre-prod3 script.
[10:59:03][Step 6/6] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[10:59:03][Step 6/6] 
[10:59:03][Step 6/6] npm ERR! A complete log of this run can be found in:
[10:59:03][Step 6/6] npm ERR!     D:\Dev\devtools\cache\npm\_logs\2023-04-14T09_59_03_974Z-debug.log
[10:59:04][Step 6/6] Process exited with code 1
```

**Comment by nagash77** [comment] 2023-04-27 14:20
Hi @jaspreet1878singh , Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nagash77** [comment] 2023-05-03 18:56
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-05-03 18:56 UTC
