### ISSUE TITLE
Cypress JSON Test Results are trimming the line error when running in an ecs container

### ISSUE THREAD

**Issue by kkavasik** [cypress-io/cypress#26987] opened 2023-06-09 15:15 UTC
### Current behavior

When we are running some cypress tests through an ecs container and we are getting the error we noticed that in the  json file with the results in the part where you provide the code frame object then for  some reason the value seems to be trimmed .

 "codeFrame": {
                  "line": 29,
                  "column": 6,
                  "originalFile": "ypresssteps/overloop-steps.js",
                  "relativeFile": "ypresssteps/overloop-steps.js",
                  "absoluteFile": "/ypresssteps/overloop-steps.js",
                  "frame": "  27 |   cy.get('input[name=\"fname\"]').type(\"testName\");\n  28 |   cy.get('input[name=\"lname\"]').type(\"testLastName\");\n> 29 |   cy.get('input[name=\"email\"]').type(\"this_is_a_test@overloop.io\");\n     |      ^\n  30 |   cy.contains(\"Submit\").click();\n  31 | });\n  32 | ",
                  "language": "js"
                }

### Desired behavior

We should have the path 

### Test code to reproduce

Run cypress in an ecs container

### Cypress Version

12.11.0

### Node version

16.18.1

### Operating System

Linux debian

**Comment by nagash77** [comment] 2023-06-12 12:16
Hi @kkavasik Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by kkavasik** [comment] 2023-06-23 13:23
The issue is that when i check the stack in results.json the relative fie and the absolute file are not correct, it seems that cypress is trimming some characters check here "originalFile": "ypresssteps/overloop-steps.js",
"relativeFile": "ypresssteps/overloop-steps.js",
"absoluteFile": "/ypresssteps/overloop-steps.js", it should say cypresssteps 

let me know what else you want from me so as to reproduce

**Comment by mike-plummer** [comment] 2023-06-27 17:27
@kkavasik Can you provide a simple reproduction case for us? Ideally in the form of a `git` repository we can clone and run ourselves. My initial attempt to reproduce your issue did not exhibit the described problem. This sort of problem could be caused by anything from the code bundler your project uses to special characters in your project's filenames. Before looking into this further we would need an example project that's known to exhibit the behavior.

**Comment by nagash77** [comment] 2023-07-07 12:14
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-07-07 12:14 UTC
