### ISSUE TITLE
Can't access CKeditor inside Iframe

### ISSUE THREAD

**Issue by nitingupta220** [cypress-io/cypress#2272] opened 2018-08-04 11:48 UTC
I won't be able to access the Ckeditor inside Iframe.

I have tried many things but none of them worked. 

This is my from which I'm trying to access it: - 

```js
cy.get(".cke_wysiwyg_frame").then(function($iframe) {
      const $body = $iframe.contents().find("body");
      console.log($body);
      cy.wrap($body[0]).type("<p>HTML body</p>");
```
![screenshot from 2018-08-04 17-16-56](https://user-images.githubusercontent.com/25584421/43676210-5475645e-980a-11e8-85c2-b747e03a2947.png)

This is above error message that I'm getting. 

Please look into it
@jennifer-shehane

**Comment by brian-mann** [comment] 2018-08-04 19:12
that means that the body was not ready by the time you tapped into it. If wrap received `undefined` then the body was undefined. I don't believe it is an error in Cypress. Logging out the $body will likely show you that its `length` is `0`. If you log out $body[0] it will likely also be undefined. You will have to wait until the body is ready.

**Comment by nitingupta220** [comment] 2018-08-06 06:42
Adding wait for the DOM elements to be ready.

` cy.wait(7000);
    cy.get("iframe.cke_wysiwyg_frame").then(function($iframe) {
      const $body = $iframe.contents().find("body");
      console.log($body);
      cy.wrap($body[0]).type("<p>HTML body</p>");
    });`

This time it does the find the element and says it is typed but nothing is shown in the editor.

So, I tried this: - 
`cy.window().then(win => {
      win.CKEDITOR.instances["iframe.cke_wysiwyg_frame"].setData("<p>HTML body</p>", {
        callback: function() {
          this.checkDirty();
        }
      });
    });`

But getting that error: - 
![screenshot from 2018-08-06 12-11-23](https://user-images.githubusercontent.com/25584421/43700900-f2bb8b9e-9971-11e8-8729-b26ed81a2a4b.png)

Please tell me what is wrong with my code.
@brian-mann @jennifer-shehane

**Comment by nitingupta220** [comment] 2018-08-06 06:53
Used your code as well but got this error: - 
![screenshot from 2018-08-06 12-22-43](https://user-images.githubusercontent.com/25584421/43701345-822cf24e-9973-11e8-888c-d6296ef206ee.png)
And I'm on the 3.0.2 version of Cypress.

**Comment by brian-mann** [comment] 2018-08-06 07:26
Then you need to increase the timeout since 4 seconds is not enough time for your iframe to be loaded. That's why it's timing out.

- https://docs.cypress.io/guides/getting-started/installing-cypress.html
- https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Timeouts

**Comment by nitingupta220** [comment] 2018-08-06 07:30
Added the timeout as well. But still won't be able to find the body. Getting the same above error message.

**Comment by nitingupta220** [comment] 2018-08-06 08:03
But in the console the body is logging fine.
See: - 
![screenshot from 2018-08-06 13-32-18](https://user-images.githubusercontent.com/25584421/43704413-36f1a9d2-997d-11e8-8b48-e722ef788e9d.png)

**Comment by nitingupta220** [comment] 2018-08-13 09:28
@brian-mann

**Comment by jennifer-shehane** [comment] 2018-08-13 20:14
We are a small team and have many considerations on what issues we work on and when. Core contributors being tagged in the issue is not one of our considerations. 

We have a community of users who are also available to help in https://gitter.im/cypress-io/cypress

Were you able to update to 3.0.3 to try the editor in that version?

**Comment by nitingupta220** [comment] 2018-08-14 07:13
@jennifer-shehane I have already updated version 3.0.3 and tried the editor but getting the same error again and again.
I know you're a small team but giving priority to every issue is a must for a good product because these issues will tell you what are the problems with your product so that you can make it stronger. 
I have heard lots of good things about cypress that's why using it.
Also, I have asked the same thing on Gitter as well.

**Comment by nitingupta220** [comment] 2018-08-22 08:15
@frazboyz Can you help me in this?

**Comment by jennifer-shehane** [comment] 2019-03-08 04:44
Closing in favor of https://github.com/cypress-io/cypress/issues/136

**Closed by jennifer-shehane** 2019-03-08 04:44 UTC
Labels: type: question

**Comment by smart625** [comment] 2019-06-17 07:06
@jennifer-shehane @brian-mann Hi, I met issue using the method you suggestion in comment. Can you take a look at this issue. Thanks in advance. https://github.com/cypress-io/cypress/issues/2272#issuecomment-410471328.
```
       cy.get('.op--ckeditor').within(()=>{
            cy.get('.bx--label').should('have.text','RTF Field')
            cy.get('.cke_wysiwyg_frame').should(function($iframe) {
              alert($iframe)
              const body = $iframe.contents().find('body').get(0);
              expect(body).to.be.ok  
            cy.wrap(body).type('<p>Testing field - RTF Field.</p>')
            })
        })
```
The error show as below
![image](https://user-images.githubusercontent.com/24734147/59584731-6666de80-9111-11e9-8eae-a1d94a88a52b.png)

**Comment by DavidEspinosa42** [comment] 2020-04-28 03:34
For CKEditor4 this works:

`cy.get('iframe').then(($iframe) => {
	const $body = $iframe.contents().find('body')
	cy.wrap($body).type('sample content.')
})`
