### ISSUE TITLE
Iframe 0.contentDocument.body cannot be loaded in Firefox

### ISSUE THREAD

**Issue by milan-easykad** [cypress-io/cypress#14853] opened 2021-02-01 22:24 UTC
### Current behavior

Running a test in a Firefox browser on iframed application cause tests to start failing due to 0.contentDocument.body.  
The same test is successfully executed on Chrome and Edge.   

![image](https://user-images.githubusercontent.com/68648172/106525511-608b6000-64e4-11eb-988e-e442afa13929.png)

### Desired behavior

To be able to execute tests on the Firefox browser for iframe applications. 

### Test code to reproduce

I have been using https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/ to set up testing iframe application, and it is not working only for Firefox.

### Versions

Cypress: 6.4.0
Firefox: 86.0b4

**Comment by jennifer-shehane** [comment] 2021-02-03 07:56
What is the error that is printed that is cut off in the screenshot you pasted? Thanks!

**Comment by milan-easykad** [comment] 2021-02-05 00:48
Hi @jennifer-shehane, 
Error bellow is just timeout after waiting for 0.contentDocument.body. Uploading new screenshot  

![Screenshot_4](https://user-images.githubusercontent.com/68648172/106973970-2f18cb80-6754-11eb-84b1-b1184a38aeb3.png)

**Comment by jennifer-shehane** [comment] 2021-02-05 05:01
Yah, it looks like our tests for these iframe recipes are all skipped on Firefox. I think because currently it requires setting `chromeWebSecurity: false`. So I'm guessing this workaround does not work in Firefox. https://github.com/cypress-io/cypress-example-recipes/blob/develop/examples/blogs__iframes/cypress/integration/button-spec.js#L29:L29

All of these are kind of hacky workarounds today. So I'd suggest following the main iframe support issue https://github.com/cypress-io/cypress/issues/136, which we're making progress on. Maybe the https://www.npmjs.com/package/cypress-iframe plugin has better support for Firefox, I'm not sure.

Duplicate of https://github.com/cypress-io/cypress/issues/136

**Closed by jennifer-shehane** 2021-02-05 05:01 UTC
Labels: stage: needs information
