### ISSUE TITLE
[4.0.2] cy.within().contains() regression, element no longer found

### ISSUE THREAD

**Issue by you1anna** [cypress-io/cypress#6519] opened 2020-02-20 15:41 UTC
### Current behavior:

Command Contains times out looking for element

### Desired behavior:

Working in Cypress 3.8.3, locate text inside a dropdown menu item

Text to find: 'Push the boundaries' 

### Test code to reproduce

```javascript
cy.get(AWARD_TYPES)
  .children()
  .eq(1)
  .within(() => {
    cy
      .contains('Push  the  boundaries')
      .click()
  });
```
Applied to:

```html
<li class="select2-results__option" id="select2-sAwardType-result-7s52-14" 
role="option" aria-selected="false" data-select2-id="select2-sAwardType-result-7s52-14">
  Push  the  boundaries
</li>
```

### Versions
Cypress 4.0.2
MacOS Mojave
Chrome 80.0.3987.106

**Comment by jennifer-shehane** [comment] 2020-02-24 04:22
Duplicate of #6405

**Closed by jennifer-shehane** 2020-02-24 04:22 UTC
