### ISSUE TITLE
Bug: Suite / test configuration overrides do not take effect in 4.9.0

### ISSUE THREAD

**Issue by kamranayub** [cypress-io/cypress#7823] opened 2020-06-26 01:07 UTC
### Current behavior:

According to the [documentation](https://docs.cypress.io/guides/references/configuration.html#Test-Configuration), we should be able to override configuration per-suite or per-test but it doesn't look like 4.9.0 is taking those into effect.

This test is configured to run at 1024x768 yet it's still the default 1000x660.

![2020-06-25](https://user-images.githubusercontent.com/563819/85809955-26243e00-b71f-11ea-9a83-9c8932773a52.png)

### Test code to reproduce

https://github.com/kamranayub/cypress-bug-test-config

```js
/// <reference types="cypress" />

describe("page", { viewportWidth: 1024, viewportHeight: 768 }, () => {
  it("works", () => {
    cy.visit("https://example.cypress.io");
  });
});
```

### Workarounds

You can still use `cy.viewport` in every test but even that I've discovered has regressed in 4.9.0 as there's a very quick shift to 1000x660 between each `it` execution that messes with styles and will affect tests.

For this split-second viewport issue, this seems to alleviate most of my issues:

```js
Cypress.Commands.overwrite("viewport", (originalFn, ...args) => {
  // Delegate to original fn
  originalFn(...args);

  // Seems to be needed in 4.9.0 for a split second
  cy.wait(500);
});
```

### Versions

- Cypress 4.9.0
- Windows 10
- Chrome 83

**Comment by shirotech** [comment] 2020-06-29 01:03
+1 also facing this issue

**Comment by jennifer-shehane** [comment] 2020-06-29 10:35
Duplicate of #7631

**Closed by jennifer-shehane** 2020-06-29 10:35 UTC

**Comment by kamranayub** [comment] 2020-06-29 13:39
Wow, GitHub search failed me, I literally searched for `viewportWidth` before opening this 😢
