### ISSUE TITLE
`pause()` should not be ignored with `cypress run --headed --no-exit`

### ISSUE THREAD

**Issue by Tobbe** [cypress-io/cypress#4044] opened 2019-04-28 17:37 UTC
### Current behavior:

`cy.pause()` is ignored when specs are run with `cypress run` 

![image](https://user-images.githubusercontent.com/30793/56867929-bdb5c180-69a0-11e9-99de-433b6d657483.png)

Notice that I have `cy.pause()` in the code to the left, but the test on the run hasn't paused

### Desired behavior:

I'd want the test to actually pause. Or make it really clear in the documentation that `pause()` is only working when you use `cypress open`

This is what it looks like when I use `cypress open`. I want the same behavior when I run with `cypress run`

![image](https://user-images.githubusercontent.com/30793/56867971-2c931a80-69a1-11e9-97fe-92da7e543ef1.png)

### Steps to reproduce: (app code and test code)

Add `cy.pause()` to any test, run it with `cypress run`, observe that the test is not paused.

### Versions

Win 10
Electron (included with cypress)
Cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-04-29 04:46
Hey, what is it you are trying to accomplish by adding `cy.pause()` during `cypress run`? Are you running with the `--headed` flag? What is your goal?

But yes, the `.pause` command does nothing when run during `cypress run` - code here. https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/debugging.coffee#L43

**Comment by Tobbe** [comment] 2019-04-29 04:51
Yeah, I was running it like this: `npx cypress run --spec cypress/integration/mySpec.js --headed --no-exit`

I didn't know `open` existed... So I wasted a bunch of time trying to get `pause()` working, to debug my test case...

**Comment by jennifer-shehane** [comment] 2019-04-29 04:58
Yeah, this does seem like a valid use case though, I believe the `cy.pause()` should work as normal when running with `--headed --no-exit` flags.

**Comment by JohnnyChiang** [comment] 2019-10-08 03:12
Because of this issue #1669. I cannot use `cypress open` to run my case. So I need `cy.pause()` to work on `cypress run`

**Comment by Bkucera** [comment] 2019-10-08 19:08
@JohnnyChiang can you post in that issue a detailed description of your problem?

**Comment by JohnnyChiang** [comment] 2019-10-09 08:07
@Bkucera I ran into the same problem as https://github.com/cypress-io/cypress/issues/1669#issuecomment-500675785 did. 
So I have to use `cypress run` to run my case

**Comment by yglin** [comment] 2019-11-06 09:18
+1, in [nrwl/nx](https://github.com/nrwl/nx) environment, "cypress run" is the default command

**Comment by DidacHerrera** [comment] 2019-11-06 19:21
I am in to the same problem, i am running cypress run, need to do this as i run with cli args. Do you know if this is going to be fix soon?

**Comment by jdillworth** [comment] 2019-11-22 00:19
I'm also having this issue. My use case is running cypress for end to end tests with a Vue-based SPA and a Django back end. I want to write my fixture and test setup code in Django (where I already have tooling) and then trigger Cypress tests. I'd like to use pause to experiment and diagnose issues.

**Comment by DidacHerrera** [comment] 2019-11-25 11:37
Why cypress is putting in the reports and even launching the UI for those tests that are excluded by tag filters? (Using cucumber plugin)

**Comment by Bkucera** [comment] 2019-12-02 18:29
@jdillworth Why can't you use `cypress open`? 
@DidacHerrera what do you mean by `cli args`? 
We want to make sure everyone can use cypress open mode.

**Comment by jdillworth** [comment] 2019-12-02 22:50
@Bkucera I can now, but I had to make endpoints on my backend to load and reset fixtures. The norm in Django is for the Django CLI to drive the tests.

**Comment by Bkucera** [comment] 2019-12-02 22:57
@jdillworth I see, that is a more advanced use case. It would be nice to have a recipe for django (I'm assuming Django rest framework?) so other users have more guidance

**Comment by amirrustam** [comment] 2019-12-06 18:22
@jdillworth I obviously don't know how your frontend and backend code is organized, but you can use the [`cy.exec`](http://on.cypress.io/exec) to call the Django CLI. For example, if you need to load data fixtures you can do:

```js
cy.exec('django-admin loaddata path/to/mydata.json')
```

**Comment by jdillworth** [comment] 2019-12-06 19:29
@Bkucera interesting, it'll probably be a month or so but I'll post something and refer to it here

**Comment by jdillworth** [comment] 2019-12-06 19:31
@amirrustam thanks for the suggestion. In my case I'm generating data sets using parameters and also need to wipe out my app-specific models at times. I think endpoints seems to fit with Cypress' thinking... keep tests as fast as possible, shave off every second. Calling an endpoint is probably faster than calling the command and incurring another python instance's startup time

**Comment by amirrustam** [comment] 2019-12-06 21:27
If your data seeding is very context-specific, then specialized endpoints would be more optimal. However, performance is purely dependent on your implementation.

To call you endpoints you can make requests via [tasks with `cy.task`](http://on.cypress.io/task).

**Comment by Bkucera** [comment] 2019-12-06 22:10
this is intended behavior, since we don't want Cypress run mode to hang forever due to left-in debugging code, which is what `cy.pause` is intended for.

https://github.com/cypress-io/cypress/blob/decaf-firefox/packages/driver/src/cy/commands/debugging.coffee#L43

Do continue to discuss below if you have other reasons for wanting to change this behavior.

**Comment by amfarrell** [comment] 2020-06-10 01:29
My use-case for this is to be able to tell someone:

> You can reproduce the issue by doing
> git fetch origin my-debugging-branch
> git checkout my-debugging-branch
> bundle exec rails server -p 3000 # Then in a separate terminal
> yarn cypress run --no-exit --headed --spec=cypress/integration/reproduce_the_bug.spec.js

If I can have a single test pause at meaningful points with comments,
then I can use cypress as a walkthrough of a problem.
If I can specify the test path on the command line, then someone who isn't yet sold on cypress does not have to hunt around the interface for the test that I point to, but can instead just run that command and see the value of cypress by watching actions in a browser.

This turns cypress into a tool for 
 * Communicating about bugs
 * Getting myself or someone else set up to debug a problem on either client and server
Allowing Cypress to demonstrate its value to new people.

**Comment by jennifer-shehane** [comment] 2020-06-10 07:05
Support for `--spec` during `cypress open` is another requested feature. @amfarrell Your use case makes a lot of sense. Thanks for explaining in detail.

**Comment by vitaliy4us** [comment] 2020-06-21 09:31
I need one of two possible ways to run a test containing pause() command:
1. Use cypress run --spec "cypress\integration\mytest.js" --headed --no-exit which should not ignore pause() command
2. Use cypress open --spec "cypress\integration\mytest.js" which starts the test containing pause() command automatically.

The reason is that I want to call the test from a script which automaticaly starts selected Cypress example. The test contains pause() to give user a chance to study example in details instead of "watching a movie" flickering in front of him for fo a couple of seconds

**Comment by amfarrell** [comment] 2020-06-25 12:02
> The test contains pause() to give user a chance to study example in details instead of "watching a movie" flickering in front of him for a couple of seconds

This fits my use-case exactly.

Two other things:
 * `cypress open --spec` should probably default to only starting its run after it detects that the server is up.
 * Ideally, it could also take a `--quiet` option. That way, I could say something like

> To reproduce this, `git checkout my-branch` and then run
> `cypress open --spec "cypress\integration\mytest.js" --detached --quiet && bundle exec rails s`.
>
> It will open chrome window that walks through the user actions to just before the issue.
> Hit the "▶" button to the left of the URL.
> It will continue the user actions that trigger the bug and pop rails into `binding.pry` where you can inspect the value of....
> 

Django users can say an equivalent thing for `runserver` and `ipdb`.

**Comment by LazaroOnline** [comment] 2020-11-08 18:29
Can you guys at cypress update the documentation to reflect that ".pause()" will not work in "run" mode?
I ran into the same issue and took some time to figure out.
https://docs.cypress.io/api/commands/pause.html

In my case I use "pause" to manually enter a captcha during a semi-automatic test.

Thanks!

**Comment by Konstruktour** [comment] 2020-12-11 08:37
as a workaround: set the config parameter `Cypress.config('isInteractive',` true);` , then `pause` works like in the headed mode.

**Comment by diminutivesloop** [comment] 2021-03-04 14:13
My use case is that I need to debug why a test is failing only in `cypress run` and not `cypress open`. I tried the solution offered by @Konstruktour but `cypress run` apparently doesn't take that config option anymore.

**Comment by Aleksandr-codefresh** [comment] 2021-03-12 13:36
> +1, in [nrwl/nx](https://github.com/nrwl/nx) environment, "cypress run" is the default command

For this specific use case solution would be to add `--watch` flag. Then it will run cypress in the interactive mode (see [details](https://github.com/nrwl/nx/blob/8088f20df75f2b61da4dcd0b31caf9e777595295/packages/cypress/src/executors/cypress/cypress.impl.ts#L178)).

**Comment by tristan-mastrodicasa** [comment] 2021-05-20 20:55
> My use case is that I need to debug why a test is failing only in `cypress run` and not `cypress open`. I tried the solution offered by @Konstruktour but `cypress run` apparently doesn't take that config option anymore.

In typescript and on the command line it complains that the 'isInteractive' option doesn't exist, but when you use plain js and put the line `Cypress.config('isInteractive', true);` in it worked as expected for me (v7.3.0) and the pause functionality was available.
 
This looks like another bug. It would be nice if this was properly fixed since I want to introduce to my company a new way to automate PR testing where the test is agnostic of the project.

**Comment by omgitsedwin** [comment] 2021-08-06 20:20
My workaround was to overwrite `cy.pause()` when using the CLI:

**cypress/support/commands.js**
```
Cypress.Commands.overwrite('pause', (originalFn, subject, options) => {
  if (Cypress.config('isInteractive')) {
    return originalFn(options)
  } else {
    cy.task('pause')
  }
});
```
**cypress/plugins/index.js**
```
const readline = require("readline");
module.exports = (on) => {
  on('task', {
    pause() {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });
      return new Promise((resolve) => {
        rl.question("Press [Enter] to continue", (answer) => {
          console.log(answer)
          rl.close()
          return resolve(answer);
        })
      });
    }
  });
}
```

**Comment by vlad0337187** [comment] 2021-09-15 22:40
It just doesn't work.
It should be fixed.

`yarn cypress:run --config video=false,isInteractive=true --headed --no-exit --spec <my_test.spec.ts>`

**Closed** 2021-10-08 21:17 UTC
Labels: type: unexpected behavior, first-timers-only, stage: needs review
