### ISSUE TITLE
ERROR TypeError: Cannot read property 'getRequestInfo' of null

### ISSUE THREAD

**Issue by amoore70** [cypress-io/cypress#5417] opened 2019-10-23 08:36 UTC
### Current behavior:

I am getting this error after doing a click() and the page does not load

### Desired behavior:

Page should load

### Steps to reproduce: (app code and test code)

```js
    const username = Cypress.env("username")
    const password = Cypress.env("password")
       
    cy.viewport(1280, 720)
    cy.visit("https://login.microsoftonline.com/te/genistarb2ctest.onmicrosoft.com/b2c_1_test_susi/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Fgenistarb2ctest.onmicrosoft.com%2Ftest-api%2Faccess.read%20openid%20profile&client_id=cd671d40-71b3-45e8-9895-80592da40203&redirect_uri=https%3A%2F%2Fgenistar-sirius-client-test.azurewebsites.net&state=5cbf535b-9a23-4114-bd14-a919f1a4d507&nonce=e5a696dd-2b92-4034-b8ef-d6d8b06d202f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.4&client-request-id=827954eb-3d74-4bfa-b46c-5e88774139ac&response_mode=fragment")

    cy.get('#logonIdentifier').type(username)
    cy.get('#password').type(password)
    cy.get('#next').click().debug()
    cy.wait(3000)
    cy.url().should('include', "https://genistar-sirius-client-test.azurewebsites.net")
```

### Versions

3.4.1 chrome

**Comment by jennifer-shehane** [comment] 2019-10-23 18:35
Since the username and password here is not provided, we have no way of running this code to reproduce this error. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by jennifer-shehane** [comment] 2019-10-24 14:16
Reopening, as I have a reproducible example with username and password. @amoore70 **Do NOT post your username and password publicly in this issue.**

**Comment by jennifer-shehane** [comment] 2019-10-24 14:20
@amoore70 When I run the code above with the username and password provided in the other issue and click the `#next` button, I see an error in the UI saying 'Your password is incorrect'

<img width="806" alt="Screen Shot 2019-10-24 at 10 19 20 AM" src="https://user-images.githubusercontent.com/1271364/67494772-c7666c00-f647-11e9-9a86-6bf2d496e1b6.png">

Are you also seeing this error?

**Comment by amoore70** [comment] 2019-10-25 12:03
The password is definitely correct. Are you using a 0 at the end and not an o? I think the issue is because we are using Azure B2C. Is there a way around this?

**Comment by jennifer-shehane** [comment] 2019-10-25 13:36
@amoore70 I copied and pasted the password as you previously wrote it exactly. Updating the last character to a `0` still results in a message within the application saying `Your password is incorrect`. Can you please verify that you do not see this message also within your test - that would prevent the page from moving forward. 

Unfortunately, I haven't been able to even determine there is a bug in Cypress from what's been provided as there is a password incorrect error, so I can't recommend a way around this.

**Comment by amoore70** [comment] 2019-10-25 14:37
I have just emailed you again incase I made a typo

**Comment by jennifer-shehane** [comment] 2022-04-08 13:56
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 13:56 UTC
Labels: stage: needs investigating

**Comment by spsiva24** [comment] 2025-01-24 08:57
I'm experiencing the same issue. Could someone assist me in resolving it?

![Image](https://github.com/user-attachments/assets/00478382-1060-4dcb-8404-a173b354e3fc)
