### ISSUE TITLE
cypress open does not work any more if internet connection breaks

### ISSUE THREAD

**Issue by geyuqiu** [cypress-io/cypress#14438] opened 2021-01-06 22:04 UTC
### Current behavior
`cypress open` does not work any more if internet connection breaks, hangs at first command and does not indicate anything: e.g. please check internet connection

### Desired behavior
obvious

### current steps to reproduce / resolve the problem
- run cypress open
- internet connection breaks
- test hangs
- internet comes back again
- must ctrl + C and restart terminal (iterm)
- open terminal and run cypress open again

### Versions
both latest (6.2.1) and 5.6

**Comment by jennifer-shehane** [comment] 2021-01-07 04:14
Can you provide an example of the test you're writing (you can exclude private url info if necessary)? Just want to see what type of test it's hanging on. Also if you could provide a screenshot or text of the error message, that would be helpful. 

The Test Runner shouldn't hang, requiring a hard exit, obviously. It's probably something in the timing of when the internet connection was lost - because I can't recreate outright with a lack of internet. Can you reproduce this? Or was it just that one time?

**Comment by jennifer-shehane** [comment] 2021-02-27 00:15
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-27 00:15 UTC
Labels: stage: needs information
