### ISSUE TITLE
Cypress erase localstorage between tests (Randomly)

### ISSUE THREAD

**Issue by mmonteiroc** [cypress-io/cypress#16166] opened 2021-04-23 14:44 UTC
### Current behavior
While executing tests with cypress open ( also we have that issue in cypress run in the CI )(only executing **all** tests)
Randomly and in different scenarios, cypress erases all localstorage from the page where executes the tests.

That can generate (depending of the structure of the app) redirects unexpected to the login page....

### Desired behavior
So that local storage is not erased except if forcedly using cy.clearLocalStorage

### Test code to reproduce
Cannot provide tests to make this fail, but willing to test anything you want me to try and give you the feedback :/

### Versions
Using cypress 6.8.0 - Also found in 7.1.0 (we rolled back because other issues open with this version, but we still had that issue in that version)

Env: Windows and CI Azure

**Comment by mmonteiroc** [comment] 2021-04-23 14:54
I saw this which explains that it's expected to clear the state.... the thing is that sometimes it does, sometimes it does not... that makes the tests flaky https://github.com/cypress-io/cypress/issues/686

Is there anyway we can disable this lifecycle with a flag or something and avoid this issue ?

**Comment by mmonteiroc** [comment] 2021-04-23 15:05
Also happens during a long test, so in the middle of the test we get a redirection to the login with localstorage empty

**Comment by mmonteiroc** [comment] 2021-04-23 15:06
Remark, not only between tests, but we also encountered this issue during a test.

**Comment by mmonteiroc** [comment] 2021-04-23 15:09
We have this code in the support file, so that executes before ANY TEST and so we are sure that we have localsotrage with our tokens and stuff during the test, but still the test redirects the login cause the localstorage gets cleared.

```
beforeEach(() => {
  // - This file returns a JSON OBJECT WHICH IS THE LOCALSTORAGE DIRECTLY
  cy.readFile(filePath).then((storage: Storage) => {
    Object.entries(storage).forEach(([key, value]: [string, string]) => {
      localStorage.setItem(key, value);
    });
  });
});
```

I did add logs, view in live the state of the localstorage.... this code works and adds the localstorage stuff, but then instantly starts the test, it gets erased it ... :/

**Comment by mmonteiroc** [comment] 2021-04-23 15:17
Is there any way to disable this of deleting the localstorage between tests ? otherwise apps which have a login like ours we will have this issue always

**Comment by MuckT** [comment] 2021-04-25 22:37
@mmonteiroc try [these custom commands](https://github.com/cypress-io/cypress/issues/944) in your `commands.js`
```JavaScript
// -- Save localStorage between tests
let LOCAL_STORAGE_MEMORY = {};

Cypress.Commands.add('saveLocalStorage', () => {
  Object.keys(localStorage).forEach(key => {
    LOCAL_STORAGE_MEMORY[key] = localStorage[key];
  });
});

Cypress.Commands.add('restoreLocalStorage', () => {
  Object.keys(LOCAL_STORAGE_MEMORY).forEach(key => {
    localStorage.setItem(key, LOCAL_STORAGE_MEMORY[key]);
  });
});
```

In your describe blocks for a spec
```JavaScript
afterEach(() => {
  cy.saveLocalStorage();
});

beforeEach(() => {
  cy.restoreLocalStorage();
});
```

**Comment by mmonteiroc** [comment] 2021-04-26 06:16
Hey ! @MuckT  Thanks for your reply but I still have the issue, I found the following commands in a post and I tried.... I have the following:

```
let LOCAL_STORAGE_MEMORY = {};

Cypress.Commands.add('saveLocalStorageCache', () => {
  Object.keys(localStorage).forEach(key => {
    LOCAL_STORAGE_MEMORY[key] = localStorage[key];
  });
});

Cypress.Commands.add('restoreLocalStorageCache', () => {
  Object.keys(LOCAL_STORAGE_MEMORY).forEach(key => {
    localStorage.setItem(key, LOCAL_STORAGE_MEMORY[key]);
  });
});

Cypress.Commands.add('clearLocalStorageCache', () => {
  localStorage.clear();
  LOCAL_STORAGE_MEMORY = {};
});

```


And then in the suport file, I have in the before each and after each the following (meaning that will be applied to all it() of all files...

```
beforeEach(() => {
  cy.restoreLocalStorageCache();
});

afterEach(() => {
  cy.saveLocalStorageCache();
});

```

**Comment by mmonteiroc** [comment] 2021-04-26 06:40
I don't know if would be hard to implement, a FLAG in the config of cypress which if true, then the localstorage is not erased between tests :/ but Im sure way more people appart of me, would enjoy this small feature

**Comment by jennifer-shehane** [comment] 2021-04-26 14:09
LocalStorage is cleared between tests by design. There's a feature request to allow certain localstorage entries to persist between tests: Duplicate of https://github.com/cypress-io/cypress/issues/461

Also related: https://github.com/cypress-io/cypress/issues/686

But our work on Sessions is likely what will resolve your issue in the end. https://github.com/cypress-io/cypress/issues/8301

There are several workarounds to this currently in the localstorage thread, one of which is https://github.com/cypress-io/cypress/issues/461#issuecomment-325402086

**Closed by jennifer-shehane** 2021-04-26 14:09 UTC
