### ISSUE TITLE
Capture stack traces on uncaught exception from application

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5212] opened 2019-09-26 12:23 UTC
### Current behavior:

If there is any issue in the application code you just get an information there was an uncaught exception with the exception message f.e. "Invalid or unexpected token" (see #1746 and #1396) without any context.

### Desired behavior:

Show a clear message with the error and a stack trace.

I have debugged into the cypress runner and noticed the onError method gets more attributes like file, line number and row number.
So it is just missing the transport to the cypress ui or similar.

### Steps to reproduce: (app code and test code)

Add some syntax error in your app code and run a test.

### Versions

3.4.1 + Chrome 76

**Comment by renatoruk** [comment] 2019-12-04 20:04
This would help a lot! Currently, I can not replicate the error manually so I'm not sure how to fix it. 

Do you have a workaround maybe?

**Comment by jennifer-shehane** [comment] 2020-01-03 06:58
@CSchulz This is part of the work within this issue https://github.com/cypress-io/cypress/issues/3762 which is being currently worked on. 

Closing as duplicate of https://github.com/cypress-io/cypress/issues/3762

**Closed by jennifer-shehane** 2020-01-03 06:58 UTC
