### ISSUE TITLE
cy.clearCookies() th in Webkit - cypress@10.8.0

### ISSUE THREAD

**Issue by lirajmaharjan-houzz** [cypress-io/cypress#23834] opened 2022-09-15 05:25 UTC
### Current behavior

Most of the time it throws an error

clearCookies

!CypressError
`cy.clearCookies() `had an unexpected error clearing cookies in Webkit.

After multiple re-run/refresh it does manage to by pass the clearCookie but it will again throw an error for chromeWebSecurity. 

I tried with adding `chromeWebSecurity: false` in cypress.config file, but didn't make any differences in cypress open.

### Desired behavior

To clear the cookies without any error. 

### Test code to reproduce

beforeEach(() => {
  cy.clearCookies()
})

### Cypress Version

10.8.0

### Node version

18.9.0

### Operating System

macOS 12.5

### Debug Logs

```shell
GET /__/assets/Runner.d2b9b65e.css 200 1.832 ms - -
GET /__/assets/Switch.eb249c19.js 200 1.521 ms - -
GET /__/assets/refresh_x16.62dd791e.js 200 1.365 ms - -
GET /__/assets/Runner.c5f68827.js 200 1.615 ms - -
GET /__/assets/Runner.c5f68827.js 200 2.305 ms - -
GET /__/assets/Switch.eb249c19.js 200 1.202 ms - -
GET /__/assets/refresh_x16.62dd791e.js 200 1.124 ms - -
GET /__cypress/iframes/cypress%2Fintegration%2FGoldenSanity_Prod%2Fimperial%2Fgroup%2Ffav-group%2Findex.spec.js 200 0.986 ms - -
GET /__cypress/tests?p=cypress/integration/GoldenSanity_Prod/imperial/group/fav-group/index.spec.js 200 420.542 ms - -
GET /__cypress/tests?p=cypress/support/e2e.js 200 934.029 ms - -
GET /socket.io/?token=c57f90c5b90a742c8102aa1ae9733b06e58ddf2de756bd1186e40d8b33abd426a79bd6f66a537a69958b451dd2b306c35d0e5ef307019e4dd6abc649d12ed0cd&EIO=3&transport=polling&t=OC_EDqD 200 11.385 ms - -
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 1.186 ms - 126828
GET /__/assets/FiraCode-VariableFont_wght.16865a4d.ttf 200 1.168 ms - -
GET /__cypress/runner/fonts/fa-regular-400.woff2 200 0.595 ms - 23900
GET /socket.io/?token=c57f90c5b90a742c8102aa1ae9733b06e58ddf2de756bd1186e40d8b33abd426a79bd6f66a537a69958b451dd2b306c35d0e5ef307019e4dd6abc649d12ed0cd&EIO=3&transport=polling&t=OC_EDqW&sid=4xSTWCbtXtKIICaPAAAA 200 111.270 ms - -
```

**Comment by chrisbreiding** [comment] 2022-09-16 15:58
I'm not able to reproduce this issue with the provided code. Can you post the full error message that's displayed and any stack trace?

Can you also post the stdout when you run `DEBUG=cypress* cypress run`?

**Comment by lirajmaharjan-houzz** [comment] 2022-09-20 10:32
Hi @chrisbreiding Sorry for the late response. 

Please find the error logs within the attachment. 
[logs.txt](https://github.com/cypress-io/cypress/files/9606583/logs.txt)
[stdout.txt](https://github.com/cypress-io/cypress/files/9606584/stdout.txt)

**Comment by chrisbreiding** [comment] 2022-09-20 20:45
I'm still not able to reproduce this, but it's likely related to https://github.com/cypress-io/cypress/issues/23865. I'm going to route this to an appropriate team to look into it.

**Comment by flotwig** [comment] 2022-09-21 14:04
From the logs, this does look like a duplicate of #23832, please follow that issue for more info. For now you can disable `experimentalSessionAndOrigin` to bypass this.

**Closed as completed by flotwig** 2022-09-21 14:04 UTC
Labels: topic: cookies :cookie:, browser: webkit, experiment: webkit
