### ISSUE TITLE
Typescript types issues

### ISSUE THREAD

**Issue by alindesign** [cypress-io/cypress#1627] opened 2018-04-20 17:01 UTC
### Current behavior:
![image](https://user-images.githubusercontent.com/12038126/39063703-93e6f316-44d4-11e8-938e-9cf7044487cd.png)

I have got some types error usign cypress with typescript, after some investigations and alot of tries to add these types on my tsconfig.json, nothing worked :cry: i have decided to change references from `cypress/types/index.d.ts` so:
```typescript
// These references
/// <reference types="blob-util" />
/// <reference types="bluebird" />
/// <reference types="minimatch" />

// Transformed into
/// <reference path="./blob-util.d.ts" />
/// <reference path="./bluebird.d.ts" />
/// <reference path="./minimatch.d.ts" />
```
After this changes, everything worked normally :disappointed: 
There is the PR: #1622 

Thanks in advance and sorry for my english :/

**Comment by bahmutov** [comment] 2018-04-20 17:04
Great, can you make a small repo reproducing the problem? Like a fork of https://github.com/cypress-io/cypress-test-tiny for example? I just want to see the problem myself

**Comment by bahmutov** [comment] 2018-04-20 17:04
also, @NicholasBoll what do you think?

**Comment by NicholasBoll** [comment] 2018-04-21 05:43
The errors you're seeing makes sense - `blob-util`, `bluebird` and `minimatch` are the three dependencies that aren't namespaced (global definition). I can reproduce and your suggested solution fixes the issue. I'm pretty sure it worked at one point. Maybe the existing code used to work, but wasn't supposed to and a TypeScript change fixed that loophole.

```ts
// as it is right now
Cypress.Promise // any

// with the suggested change
Cypress.Promise // typeof Bluebird
```

I don't think I noticed when this started breaking because I've had `skipLibCheck` enabled (I've had issues with other namespaces colliding).

**Comment by NicholasBoll** [comment] 2018-06-26 15:40
#1622 has been merged, but didn't have a reference to this issue so it didn't automatically get closed. Can this issue be closed now?

**Comment by bahmutov** [comment] 2018-06-26 15:53
good catch @NicholasBoll closing this

**Closed by bahmutov** 2018-06-26 15:53 UTC
Labels: stage: needs review, topic: typescript
