### ISSUE TITLE
Setting up Cypress using webpack 5 and react-scripts

### ISSUE THREAD

**Issue by wschenkel** [cypress-io/cypress#18992] opened 2021-11-18 21:28 UTC
### Current behavior

I am facing an issue with setting up Cypress with webpack 5. When I run the test end-to-end It works properly, but when I run the component test (`cypress run-ct`) I got an error. Follow the errro below:

<img width="1440" alt="Captura de Tela 2021-11-18 às 15 52 33" src="https://user-images.githubusercontent.com/5265969/142497659-a2c433d9-6778-416b-b5b3-77b930a2f37c.png">

<img width="1440" alt="Captura de Tela 2021-11-18 às 15 52 53" src="https://user-images.githubusercontent.com/5265969/142497723-fb691249-9f45-464b-aa35-b1562e4eadcf.png">

What I could notice is I'm using the `react-scripts` library and it is using webpack 4 under the hood. I tried to use `webpack-5-react-scripts` but it didn't work as well.

Anyone has already faced this before?

[My package.json](https://gist.github.com/wschenkel/741ba3c51bbc1e12d3e9ada8af49231c)
[My webpack config](https://gist.github.com/wschenkel/113ebeb8f3ad541af2bf5e1a4a7320e9)
[My Cypress plugin](https://gist.github.com/wschenkel/da0537e4dd924fc9dd4f5058eb25a4b0)

### Cypress Version

9.0.0

### Package Manager

yarn

### Operating system

Mac

### Other

Node version: 14.18.1
Thanks in advance!

**Comment by chrisbreiding** [comment] 2021-11-24 14:49
I was able to reproduce with the following:

package.json

```json
{
  "scripts": {
    "cy:open:ct": "cypress open-ct"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@cypress/react": "^5.10.3",
    "@cypress/webpack-dev-server": "^1.7.0",
    "babel-loader": "^8.2.3",
    "cypress": "^9.0.0",
    "react-scripts": "^4.0.3",
    "webpack": "^5.64.1"
  }
}
```

webpack.config.js

```js
const path = require('path')

module.exports = {
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'index.bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        }
      },
    ]
  },
}
```

cypress/plugins/index.js

```js
const injectDevServer = require('@cypress/react/plugins/react-scripts')

module.exports = (on, config) => {
  injectDevServer(on, config)
  return config
}
```

Then running `npm run cy:open:ct`.

If I change the webpack dependency to `^4`, it runs fine.

**Comment by FelipeLahti** [comment] 2021-12-16 18:27
Having the same issue but with react-scripts v5 which uses webpack 5 under. Any workarounds?

**Comment by FelipeLahti** [comment] 2021-12-18 03:13
Looks like `@cypress/webpack-dev-server` doesn't support webpack v5 just yet. See https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/webpackDevServerFacts.ts

**Comment by ZachJW34** [comment] 2021-12-20 15:52
@FelipeLahti the latest version of [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server/v/4.6.0) is 4.6.0 which supports Webpack v5 so we should be able to support v5. Looks like `react-scripts@5` is stable, so if there are any issues when running Cypress it's most likely coming from `@cypress/react` since we haven't added any tweaks to support the new version. Could you post the errors you are seeing and possibly a repo reproducing your issue? I was able to get cypress working with `create-react-app@5.0.0` but I would like to see what's happening on your end.

You can check out a (somewhat) working version of Cypress and react-scripts@5 [here](https://github.com/cypress-io/cypress-component-testing-examples/tree/react-scripts-5). You can clone the repo, check out the `react-scripts-5` branc, `cd ./react-scripts-5` and run `npx cypress open-ct`

**Comment by FelipeLahti** [comment] 2022-01-10 23:16
Getting this @ZachJW34 which is better than what I have today:
<img width="1502" alt="Screen Shot 2022-01-10 at 20 13 27" src="https://user-images.githubusercontent.com/1033702/148853472-7ae2fd15-a1f1-4468-bf9a-880f6bb4a57d.png">

This cypress-io/cypress#19434 looks promising. Any ETA on the release?

**Comment by ZachJW34** [comment] 2022-01-11 03:29
@FelipeLahti that PR was merged and released in @cypress/react@5.12.0. Have your tried it with the latest?

**Comment by FelipeLahti** [comment] 2022-01-11 23:09
@ZachJW34 Looks like the release for @cypress/react@5.12.1 didn't include that change. 
https://github.com/cypress-io/cypress/compare/@cypress/react-v5.11.0...@cypress/react-v5.12.0 didn't seem to include the change either. I also did check the node module installed and I could find the change...

**Comment by ZachJW34** [comment] 2022-01-12 21:38
@FelipeLahti the compare shows the commit for cra-5 support "feat: support create-react-app v5 (#19434)", it's down at the bottom. The changes were indeed released as part of `5.12.0`, you can check out [this branch](https://github.com/cypress-io/cypress-component-testing-examples/tree/cra-5) for a working example (the project called "my-app").

**Comment by FelipeLahti** [comment] 2022-01-12 23:43
Ok. Getting this now on a fresh installation https://github.com/cypress-io/cypress/issues/19674

**Comment by antonio-rodrigues** [comment] 2022-01-13 11:38
That is my use case also, it started today.

Old installation/yarn.lock works just fine.

In a fresh project, or deleting `yarn.lock` then `yarn install`, it fails with the error:
`TypeError: Cannot read properties of undefined (reading 'uid') at Object.statSync (/foo/bar/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:303:17)`

**Comment by robcaldecott** [comment] 2022-01-14 07:55
I can only make this work by reverting to `react-scripts@4.0.3`

**Comment by alecmerdler** [comment] 2022-01-18 21:59
This is broken for me as well. Simply followed the [official docs for React component testing](https://docs.cypress.io/guides/component-testing/introduction#Install).

**Comment by FelipeLahti** [comment] 2022-01-28 22:57
I create this repo here with a reproducible example with the same dependencies I have in my project.
https://github.com/FelipeLahti/error-create-react-app-v5
It's using the latest depencies for cypress.
```
"@cypress/react": "^5.12.1",
"@cypress/webpack-dev-server": "^1.8.0",
"cypress": "^9.3.1",
node version is v16.13
```
Steps to reproduce in the repo
```
nvm install v16.13
npm i
npm run test:ct
```
This is the error I get 
<img width="1233" alt="Screen Shot 2022-01-28 at 19 54 43" src="https://user-images.githubusercontent.com/1033702/151632781-d06c0723-5a1e-4c52-91d8-3140048d00a8.png">

**Comment by GideonShils** [comment] 2022-02-10 23:26
Hey @FelipeLahti, I was hitting the same error as you, and was able to get around it by installing webpack 5 as a top level dependency in my project via:

`npm install webpack --save-dev`

Cypress's `webpack-dev-server` is still dependent on webpack 4, which is likely causing it to get installed as a top level dependency in your project. This can be confirmed by running `npm install` in your sample repo, and checking the webpack version in `node_modules/webpack/package.json` (it's `4.44`). Since your project has webpack 4 installed, cypress's webpack-dev-server is running that version, but is trying to read the webpack 5 compatible `webpack.config.js` file that ships with CRA5. The specific errors you're seeing are all related to `config.js` options that exist in webpack 5 but not in 4.

By installing webpack5 at the top level, the dev server will use that version instead, which will hopefully hold you over until cypress ships with native support.

**Comment by FelipeLahti** [comment] 2022-02-11 13:02
Hey @GideonShils 
It worked! I had the dependency html-webpack-plugin missing in this repo too.

Updated https://github.com/FelipeLahti/error-create-react-app-v5 and it's working now. Thanks!

**Comment by rockhold** [comment] 2022-05-23 19:22
Closing this issue, as it was addressed in https://github.com/cypress-io/cypress/pull/19434

**Closed by rockhold** 2022-05-23 19:22 UTC
Labels: stage: backlog, component testing, topic: installation
