### ISSUE TITLE
Blank video recording

### ISSUE THREAD

**Issue by rgavinc** [cypress-io/cypress#1304] opened 2018-02-13 16:59 UTC
### Current behavior:
Recorded video is returned blank.

### Desired behavior:
Video to record normally.

### How to reproduce:
When I run cypress I get both a video and snapshot returned to me but they are both blank. When I run cypress in headed mode I get a correct snapshot back but no video (since video recording isn't supported in headed mode).

### Additional Info (images, stack traces, etc)
In headless mode:
![image](https://user-images.githubusercontent.com/16596981/36162111-c652f216-10a2-11e8-8a21-3ec934957bb0.png)
![image](https://user-images.githubusercontent.com/16596981/36162128-ce52b80c-10a2-11e8-83f9-197a96fce314.png)
In headed mode:
![image](https://user-images.githubusercontent.com/16596981/36162329-5fb65358-10a3-11e8-9f71-0c3fc6032fa8.png)

- Operating System: Windows 10
- Cypress Version: 1.4.2
- Browser Version:  Electron 53.0.2785.143

**Comment by ValerieThoma** [comment] 2018-04-13 02:13
@rgavinc, I cannot reproduce this bug with 1.4.2
nor @fdaryaee, can I reproduce with 2.1.0 
Can either of you provide a little more information about your tests? 

* Do you experience this behavior when running all of your test suites or projects? 
* Can you provide the steps and/or commands you issued to run your tests? 
* Are either of you behind a corporate proxy?

**Comment by fdaryaee** [comment] 2018-04-23 15:13
I am using following command to run the tests in a headless mode. I see this issue in both cases i.e. if I run a single test or all the tests in a suite.

To run all the tests I use following command
npx cypress run --env configFile=test

To run a single test I use following command
npx cypress run --env configFile=test --spec cypress\integration\matchmaker_spec.js

In both the cases, video is recorded but its bank (See screenshots attached)
Also, we are not behind a corporate proxy.

![all_tests](https://user-images.githubusercontent.com/37311281/39135551-3490f3ac-46e7-11e8-801a-3cbc3b946919.png)
![single_test](https://user-images.githubusercontent.com/37311281/39135554-36e39dbc-46e7-11e8-8fba-9400c2702ed0.png)

**Comment by jennifer-shehane** [comment] 2018-04-23 17:50
Unfortunately, we will have to have a reproducible repo that we can run to reproduce this. We have tried running some of our example repos - also in Windows, but have been unable to reproduce it.

Can someone provide a repo/code to reproduce?

**Comment by fdaryaee** [comment] 2018-04-24 15:09
The repo is private and something which I cannot share unfortunately. I can help with any other information that can help you reproduce this. Please let me know what all you need. Thanks!

**Comment by GAO8A** [comment] 2018-04-25 20:47
@ValerieThoma Can replicate this problem with my project. and yes we are behind a company proxy where https://api.cypress.io/is blocked.

In headed mode, screenshots work per expected, they issue arises in headless mode where they are blank.

A simple test like this will produce a blank screenshot in headless:

`describe('Sanity', function() {
    it('True is true', function() {
      cy.visit('https://news.ycombinator.com/'); // or any url
      cy.screenshot('HN')
      expect(true).to.equal(true)
    })
  })`

Operating System: Windows 7
Cypress Version: 2.0.3
Electron Version: 59

BTW, Thank you guys for a slick product and great support!

**Comment by jennifer-shehane** [comment] 2018-04-26 17:32
Can you try to set `HTTP_PROXY` and/or `HTTPS_PROXY` to your corporate proxy as environment variables? I detailed some of this fix here: https://github.com/cypress-io/cypress/issues/1469#issue-305961859

But for Windows, it should be something like
```shell
setx HTTP_PROXY "http://my-corporate-proxy-address"
```

**Comment by JoaoPachecoSmartMed** [comment] 2018-05-22 15:56
I'm having the same issue. I tried the same project I'm working on Ubuntu VM and it worked, I got video and images, but in Windows 10 the video is blank and the images black. 

Perhaps a Xvfb library is missing for Windows or something like that?

**Comment by dbourse** [comment] 2018-06-05 15:45
I have the same issue

**Comment by sj4nes** [comment] 2018-06-15 14:55
I'm seeing blank videos as well. This is with:

* Cypress 3.0.1
* Electron 59 (headless)
* Windows 8.1

Screenshots are also blank.

**Comment by brian-mann** [comment] 2018-06-15 16:58
Xvfb is not used or needed in Windows. It's linux only.

**Comment by brian-mann** [comment] 2018-06-15 16:58
Can you all try Chrome instead of Electron to see if the screenshots aren't blank?

**Comment by sj4nes** [comment] 2018-06-15 17:47
Screenshots are working when I use `-b chrome`, will check this with video capture next.

**Comment by brian-mann** [comment] 2018-07-01 00:40
Can you update to `3.0.2` and see if this issue is resolved?

We updated `ffmpeg` to `4.x.x` there and added many more debugging logs.

Also please be sure that you use `DEBUG=cypress:* cypress run` when running so that we can get the debug logs to understand what is happening.

**Comment by JoaoPachecoSmartMed** [comment] 2018-07-02 09:23
For me is working now with version `3.0.1`

**Comment by 4z5lz** [comment] 2018-07-04 15:07
I am facing the same issue with video recording.  In the headless mode the video is blank.
Cypress version: 3.0.1 (btw, can't upgrade to 3.0.2 - https://github.com/cypress-io/cypress/issues/2097)
OS: Win7 Professional (x64)

**Comment by SanderMeester** [comment] 2018-07-11 11:48
We had the same problem, but it went away after two changes; we went from running the TFS-agent as an app to running it as a service and we changed the user. So it might a permission-issue. It might not be related to both of the changes, but this might give you something to try.

**Comment by kvillega** [comment] 2018-10-18 23:29
Hi, I encountered this issue yesterday and managed to resolve it. 
What I did was install cypress as an administrator. (I was running it on my local machine as non admin since I didn't have any issues with it before). 

Once I installed node, angular, & cypress using an admin profile and ran it using the same admin profile it was able to render both videos and screenshots in headless mode. 

Hopefully this helps debugging! 

Version: Cypress 3.1
System: Windows 7

**Comment by timelights** [comment] 2019-03-03 01:20
> Hi, I encountered this issue yesterday and managed to resolve it.
> What I did was install cypress as an administrator. (I was running it on my local machine as non admin since I didn't have any issues with it before).
> 
> Once I installed node, angular, & cypress using an admin profile and ran it using the same admin profile it was able to render both videos and screenshots in headless mode.
> 
> Hopefully this helps debugging!
> 
> Version: Cypress 3.1
> System: Windows 7

@kvillega how to run or install cypress in admin mode?

This is my first time using cypress and encountering the same issue.
```cypress run --spec "cypress/integration/sample_spec.js"```

The content is to go to google.com and just search any keyword then click on images.
The code includes ```cy.screenshot("Step n")```

**When running via cypress desktop** the snapshots/screenshots are good! (but no video)
**On cypress run** the screenshots are all black while video is just white but have duration.

**Comment by h01d3r** [comment] 2019-03-06 11:48
I have the same issue. Test running on TeamCity build agent. Only -b chrome solve this issue

**Comment by jennifer-shehane** [comment] 2019-03-06 18:00
Can you try to add this code to the `pluginsFile` at `cypress/plugins/index.js`? Let us know if it changes anything.

Try `--disable-d3d11` and `--disable-gpu` flags independently also. Some combination of this may help things. 

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'electron') {
      args['disable-gpu']
      args['disable-d3d11']

      return args
    }
  })
}
```

**Comment by h01d3r** [comment] 2019-03-07 08:33
No, nothing has changed:( Video and screenshots is empty
And one more. when I run cypress with `-b chrome` option on build agent from TeamCity UI it's say that "A video will not be recorded when using this browser." , but when I run it from build agent from cmd video record is fine

**Comment by jaterlwj** [comment] 2019-03-28 06:28
Hi team,

Is there any update to this issue? I am running into the exact same problem as @rgavinc where screenshots and video in headless electron returns blank but screenshot works in headed electron. 

- I am experiencing this on all test suites and projects. Even the simplest of test - opening a page and taking a screenshot) would result in the same error. 

- Commands issued in the test are cy.visit('www.google.com') and cy.screenshot()

I am behind a corporate proxy and have tried the following to no avail:
1. Setting HTTP_PROXY and HTTPS_PROXY.
2. Disabling the disable-d3d11 and disable-gpu as per recommended by @jennifer-shehane 

My logs from DEBUG=cypress:* are uploaded [here](https://gist.github.com/jaterlwj/f6d519bf7757597247a0ca1feed4abac).

**Comment by jeceldx** [comment] 2019-03-28 06:31
Also have this issue with :
Cypress 3.1.5
Electron 59 (headless)
Windows 7(x64)

**Comment by glitchperfect** [comment] 2019-04-02 15:27
Is this issue also resolved with PR #3531?

**Comment by jennifer-shehane** [comment] 2019-04-24 06:47
@glitchperfect Oh, I really hope so! Can anyone run Cypress against the `develop` branch that is experiencing this issue to verify if this fixes the issue?

@flotwig Thoughts on this issue being resolved for proxy support? Would you be able to replicate this issue and verify?

**Comment by flotwig** [comment] 2019-04-24 14:25
@jennifer-shehane Is this a network-related issue? I tried running Cypress with `api.cypress.io` blocked, but it still successfully takes screenshots and videos in run mode on the latest `develop` branch (even with no Internet access at all).

[This comment](https://github.com/cypress-io/cypress/issues/1304#issuecomment-383611349) says they are experiencing the issue but are not behind a corporate proxy, so it might not be related.

**Comment by jennifer-shehane** [comment] 2019-04-24 14:29
@flotwig We've never been able to reproduce this, so we're unsure of the core issue. I just know some people mentioned proxy, so was hoping this may have been the issue.

**Comment by divslinger** [comment] 2020-02-25 10:18
Just to close this old issue. The bug has been resolved for me.

**Comment by jennifer-shehane** [comment] 2020-02-26 09:39
Yes, I am considering this to be resolved since there have not been really any mentions of this in nearly a year. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-02-26 09:39 UTC
Labels: OS: windows, stage: needs information, topic: video 📹, type: bug
