### ISSUE TITLE
Cy.request parse BigInt lost precision 

### ISSUE THREAD

**Issue by dinhvinhloc** [cypress-io/cypress#8154] opened 2020-08-01 06:15 UTC
### Current behavior:

I'm using `cy.request()` to test our API. There are cases where I create an entity on my back-end and expect an ID to return in JSON.

The ID is in number and 28-digits long and cypress automatically parse it to format of e+28 and some last digits lost which make the ID is no longer the original ID I expected.

### Desired behavior:

cypress to parse bigint precisely

### Test code to reproduce
Example of my JSON response.

```js
{
  "id":29178781077420375453911589234,
  "name":"test_attr",
  "description":"test attr description",
  "merchantId":0
}
```

### Versions

4.11.0

**Comment by rally25rs** [comment] 2020-08-02 12:11
I don't know if this is really a Cypress issue; Your number is larger than `Number.MAX_SAFE_INTEGER` so JS may not be able to represent it with the standard `Number` type. You can use `BigInt` but `BigInt` does not serialize to JSON, so you can't actually transmit it without implementing your own JSON serialization of BigInt.

In other words, if you remove Cypress from the picture and just paste your example JSON `{"id":29178781077420375453911589234}` into the browser console, JS will lose the precision on your ID.

```
JSON.stringify({"id":29178781077420375453911589234})
// returns "{\"id\":2.9178781077420378e+28}"
```

If you attempt this with a BigInt
```
JSON.stringify({"id":BigInt(29178781077420375453911589234)})
// TypeError: BigInt value can't be serialized in JSON
```

The [MDN docs for BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) suggsest overriding the JSON serialization for `BigInt` and transmit it as a string. On your backend you will have to also convert the string back to an Integer.

```
BigInt.prototype.toJSON = function() { return this.toString()  }
```
However BigInt's `toString()` also seems to not be able to handle your number:
```
BigInt(29178781077420375453911589234).toString();
// returns "29178781077420377578781278208"
```

IMO your best bet would be to convert your ID to a String on the backend. Always use it as a string in JS not as a Number. Since it is a record ID you probably don't need to do any mathematical operations on it, so using a string would likely suit your needs without any of the headaches of dealing with JS's Number types.

**Comment by dinhvinhloc** [comment] 2020-08-02 14:43
Thanks for your response. I understand that this is not Cypress issue. However, is there any chance that we can use other libraries to parse JSON in Cypress that return true BigInt (i.e.: https://www.npmjs.com/package/json-bigint)? Or at least Cypress includes the raw text string of the JSON in the response so that I can parse it again?

I was able to use axios to send the request then parse the raw text returned using json-bigint. However, the work need to display the result back to Cypress is so much pain.

Lastly, I have no control on the backend so have to live with it.

**Comment by jennifer-shehane** [comment] 2020-08-03 09:58
@dinhvinhloc There is a request to avoid the automatic parsing of JSON files in Cypress here: https://github.com/cypress-io/cypress/issues/5395

The basic workaround to get around our JSON parsing would be to remove the extension from the JSON file. So `cypress/fixtures/respone.json` to `cypress/fixtures/response`. 

Duplicate of #5395

**Closed by jennifer-shehane** 2020-08-03 09:58 UTC

**Comment by dinhvinhloc** [comment] 2020-08-03 12:51
@jennifer-shehane Thank you. Since this is direct response, Can I turn off automatic parsing through an option in cy.request()?

**Comment by jennifer-shehane** [comment] 2020-08-18 10:32
You can pass an `encoding` option which will be used when serializing the response body. https://on.cypress.io/request#Arguments Not sure if that fixes the issue.

**Comment by dinhvinhloc** [comment] 2020-08-18 15:07
Thank you very much for the advice. The work-around using encoding option works for me.
I can use hex encoding then use hex2ascii library to convert the body to text and use json-bigint to parse the id.

**Comment by Mxolotl** [comment] 2022-01-06 12:22
@skpriyatham58 Not sure if you still need it, but I achieved it like this :) 

`const app_url = Cypress.env("app_url")
const api_key = Cypress.env("api_key")
const hex2ascii = require('hex2ascii')
var JSONbig = require('json-bigint')

it('Deletes all documents in the database', () => {

    cy.request({
      url: app_url + '/odata/Published_OData_service/v1/Documents',
      method: 'GET',
      headers: {
        authorization: api_key
      },
      encoding: 'hex'
    }).then((response) => {
     var jsonBigResponse = JSONbig.parse(hex2ascii(response.body))
     console.log(jsonBigResponse.value[1].ID.toString());
    })`
