### ISSUE TITLE
selectFile errors on large files

### ISSUE THREAD

**Issue by mmestas** [cypress-io/cypress#29564] opened 2024-05-23 20:12 UTC
### Current behavior

I receive the error: 
```
 failed while trying to read the file at the following path:
 ... /PATH/
The following error occurred:

> "File size (2281403699) is greater than 2 GiB"
```

I then tried installing and using the cypress-file-upload library, and got a similar response.  
How are we supposed to test uploading large files?

### Desired behavior

Allow Cypress to test uploading large files.

### Test code to reproduce

`cy.get(".custom_file_drop").selectFile(filePath);`

### Cypress Version

13.9.0

### Node version

v18.15.0

### Operating System

macOS 14.3.1

**Comment by jennifer-shehane** [comment] 2024-05-24 18:38
Duplicate of https://github.com/cypress-io/cypress/issues/20244

**Closed as not planned by jennifer-shehane** 2024-05-24 18:38 UTC
Labels: type: duplicate
