### ISSUE TITLE
Can not open cypress due to this error "Circular symlink detected: "C:\Users\lmmki\AppData\Local\Application Data" points to "C:\Users\lmmki\AppData\Local" Error: Circular symlink detected: "C:\Users\lmmki\AppData\Local\Application Data" points to "C:\Users\lmmki\AppData\Local"     at E._getEntryType (<embedded>:3864:7466)     at async E._read (<embedded>:3864:6206)"

### ISSUE THREAD

**Issue by susanliuFourth** [cypress-io/cypress#29238] opened 2024-04-01 02:41 UTC
### Current behavior

input npx cypress open

### Desired behavior

open cypress

### Test code to reproduce
```
C:\Users\lmmki>npx cypress open


DevTools listening on ws://127.0.0.1:49904/devtools/browser/e65ef8e8-6229-46ed-a291-3dc172c60a97
Circular symlink detected: "C:\Users\lmmki\AppData\Local\Application Data" points to "C:\Users\lmmki\AppData\Local"
Error: Circular symlink detected: "C:\Users\lmmki\AppData\Local\Application Data" points to "C:\Users\lmmki\AppData\Local"
    at E._getEntryType (<embedded>:3864:7466)
    at async E._read (<embedded>:3864:6206)
```
### Cypress Version

13.7.1

### Node version

18.17.0

### Operating System

win11

**Comment by jennifer-shehane** [comment] 2024-04-01 13:50
Duplicate of https://github.com/cypress-io/cypress/issues/22052 There's a workaround provided here: https://github.com/cypress-io/cypress/issues/22052#issuecomment-1145551550

**Closed as not planned by jennifer-shehane** 2024-04-01 13:50 UTC
Labels: type: duplicate
