### ISSUE TITLE
`Cypress.on('uncaught:exception')` No Longer Preventing Tests From Failing after Upgrade to `10.0.2`

### ISSUE THREAD

**Issue by danfooks** [cypress-io/cypress#22129] opened 2022-06-06 16:40 UTC
### Current behavior

Cypress is not ignoring the following error:
![uncaughtexception](https://user-images.githubusercontent.com/46224768/172205437-2a8ae863-cae0-4689-ac2d-de39114679dd.png)

My `cypress/support/e2e.js` file is configured so that Cypress should return `false` on an `uncaught:exception` in order to prevent the test from failing. This is no longer working as expected after upgrading to the latest version, `10.0.2`, as the test is failing.

### Desired behavior

In this situation, Cypress should pass the `it` statement while ignoring the error and throwing any specified logging.

### Test code to reproduce

```
Cypress.on('uncaught:exception', (err) => {
  // returning false here prevents Cypress from
  // failing the test
  console.log('Cypress detected uncaught exception: ', err);
  return false;
});
```

### Cypress Version

10.0.2

**Comment by ZachJW34** [comment] 2022-06-06 23:12
@danfooks I'm not able to reproduce this issue on Cypress v10.0.2. Is this error specific to `ResizeObserver`? Have you checked out the issue @mjhenkes linked to see if it is an issue with how you are matching the resize observer error text?

If it is a more general issue and you `Cypress.on('uncaught:exception', (err) => {})` is not working for you, can you provide a minimal reproduction?

**Comment by willoliveira-air** [comment] 2022-06-07 08:16
@ZachJW34 I'm seeing the same problem from @danfooks within the `ResizeObserver ` and the pattern seems to be fine because it is working for most part of the scenarios. 

```
const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/;
Cypress.on('uncaught:exception', (err) => {
  /* returning false here prevents Cypress from failing the test */
  if (resizeObserverLoopErrRe.test(err.message)) {
    return false;
  }
});
```

It is not reproduced all the time in Electron or Chrome (I didn't check in Mozilla yet). It is happening every few test runs (the same test but not all the runs). 

```
The following error originated from your test code, not from Cypress.

  > ResizeObserver loop limit exceeded

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.


View stack trace
at <unknown> (http://localhost:3000/__/#/specs/runner?file=cypress/e2e/error-states.spec.ts:0:0)
```

Please let me know if you need more details. 
Thanks.

**Comment by danfooks** [comment] 2022-06-07 12:26
@ZachJW34 For myself, it is occurring consistently for every test run. I did check [the ResizeObserver bug ticket](https://github.com/cypress-io/cypress/issues/22113), which seems to be the root cause of my issue. Also, If I am correct I should not have to check for a regex expression to be present in the error as @willoliveira-air is doing, as I want to catch _all_ errors, rather than just this specific one. If it helps you to reproduce, below is the code that is triggering the issue in my test. The code uses an href from a button and `cy.origin` to navigate to an external page using the `baseUrl` and the `path` of the external page:

```
const baseUrl = 'https://www.sampleUrl.com/';

function testLoginPageLink(selector, pageDetails) {
  cy.get(selector)
    .should('have.attr', 'href').and('include', `${baseUrl}${pageDetails.path}`)
    .then((href) => {
      cy.origin(baseUrl,
        { args: { hrefPath: href.substring(26), title: pageDetails.title }}, ({ hrefPath, title }) => {
          cy.visit(hrefPath);
          cy.contains(title);
        });
    });
}
```

**Comment by AtofStryker** [comment] 2022-06-08 19:53
One thing I did notice that I found interesting is that it looks like the `ResizeObserver` failures in from @willoliveria-air 's case come from the test itself, which will not work with `uncaught:exception`, similar to #22113. What happens if you try the `fail` handler out of curiosity?

**Comment by AtofStryker** [comment] 2022-06-08 19:56
@danfooks since your error comes from the application itself, the problem is likely a bit different. I noticed you are using `cy.origin`, in which case you likely need a separate `uncaught:exception` handler in `cy.origin` to [catch that error and not throw it](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/e2e/origin/uncaught_errors.cy.ts#L88) in your main test, something like:

```js
const baseUrl = 'https://www.sampleUrl.com/';

function testLoginPageLink(selector, pageDetails) {
  cy.get(selector)
    .should('have.attr', 'href').and('include', `${baseUrl}${pageDetails.path}`)
    .then((href) => {
      cy.origin(baseUrl,
        { args: { hrefPath: href.substring(26), title: pageDetails.title }}, ({ hrefPath, title }) => {
          Cypress.on('uncaught:exception', () => false)
          cy.visit(hrefPath);
          cy.contains(title);
        });
    });
}
```

**Comment by willoliveira-air** [comment] 2022-06-09 11:35
@AtofStryker thanks for taking this one. 

Well, thanks for adding this note about the debug approach. When I'm adding your suggestion `on error` instead of the `uncaught:exception`. Sometimes I'm able to see the error from my environment itself and sometimes I can't because it is running fine. 

So, on the same way from the `resizeObserver` error, it is intermittent. 
![Screenshot 2022-06-09 at 13 21 29](https://user-images.githubusercontent.com/97463799/172837072-3cca2c1e-44a3-4660-9c99-6e8cdec8c1dc.png)

Another point is regarding the browser. I was not able to reproduce in Chrome or Firefox. 
Only in Electron v100 if that helps. 

Please let me know if you need more details and I can provide them. 
Thanks.

**Comment by danfooks** [comment] 2022-06-09 12:12
> 

@AtofStryker Thank you for this recommendation. This solution seems to work! This is actually my first time using `cy.origin`, so I was unaware that we had to catch exceptions separately rather than rely on the exception handler in `e2e.js`.

**Comment by AtofStryker** [comment] 2022-06-09 14:30
> handler in `e2e.js`. After bumping to `10.0.2`, this is the only place in our tests where this `ResizeObserver` error was

@danfooks I'm glad that solution is working for you! I was looking through the `cy.origin` docs myself and couldn't find a clear area where this kind of event behavior is described, so I am following up with our developer experience team to verify a location for this type of thing. Are you running into any additional issues or do you feel this issue might be ready to close?

**Comment by danfooks** [comment] 2022-06-09 15:42
> 

I think we are good to close this one out! And to respond to your other message, yes, the `ResizeObserver` error was being thrown in the Cypress test runner itself, rather than in the browser, as far as I know.

**Comment by AtofStryker** [comment] 2022-06-10 13:43
@danfooks Perfect. I am going to close this out.

**Comment by AtofStryker** [comment] 2022-06-10 13:45
@willoliveira-air I am going to continue our conversation on issue #22113 as I think you and @mlberkow are having the same, if not a very similar issue, i.e. a resize observer failure that is being generated from the test itself, not the application.

**Comment by rogoit** [comment] 2022-09-27 19:49
> @danfooks since your error comes from the application itself, the problem is likely a bit different. I noticed you are using `cy.origin`, in which case you likely need a separate `uncaught:exception` handler in `cy.origin` to [catch that error and not throw it](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/e2e/origin/uncaught_errors.cy.ts#L88) in your main test, something like:
> 
> ```js
> const baseUrl = 'https://www.sampleUrl.com/';
> 
> function testLoginPageLink(selector, pageDetails) {
>   cy.get(selector)
>     .should('have.attr', 'href').and('include', `${baseUrl}${pageDetails.path}`)
>     .then((href) => {
>       cy.origin(baseUrl,
>         { args: { hrefPath: href.substring(26), title: pageDetails.title }}, ({ hrefPath, title }) => {
>           Cypress.on('uncaught:exception', () => false)
>           cy.visit(hrefPath);
>           cy.contains(title);
>         });
>     });
> }
> ```

Works fine for me thx for your passion

**Comment by ryanborhoo** [comment] 2023-03-25 02:46
> One thing I did notice that I found interesting is that it looks like the `ResizeObserver` failures in from @willoliveria-air 's case come from the test itself, which will not work with `uncaught:exception`, similar to #22113. What happens if you try the `fail` handler out of curiosity? Something like
> 
> ```js
>     Cypress.on("fail", () => {
>       return false;
>     });
> ```

This will ignore the failing test, which is not what we want to have.

**Comment by AtofStryker** [comment] 2023-03-28 03:55
@ryanborhoo this was recommended to be diagnostic to verify if the error was coming from the test runner or the application. This is not as a solution to this issue. If you are running into an issue where the app is throwing this, you should be able to ignore it through the `uncaught:exception` handler. But if the test runner is throwing this for you, can you open a new issue with a reproduction?

**Comment by agugut-nexgen** [comment] 2023-06-23 15:09
Hello Team I'm having the same issue with cypress `12.15.0`
I have this config ```// Add this uncaught to avoid chrome error on pre prod
Cypress.on('uncaught:exception', (err) => {
    const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/;
    if (
        err.message.includes("Cannot set property 'status' of undefined") ||
        err.message.includes("Cannot read property 'method' of undefined") ||
        err.message.includes('Cannot set properties of undefined') ||
        err.message.includes('Cannot read properties of undefined') ||
        err.message.includes('timeLeftSeconds') ||
        resizeObserverLoopErrRe.test(err.message)
    ) {
        // returning false here prevents Cypress from
        // failing the test
        return false;
    }
    return true;
});```
And the test is failing i n the after each with `timeLeftSeconds`

**Comment by mike-plummer** [comment] 2023-06-29 16:48
@agugut This issue has been closed for some time and was specifically against an older version of Cypress. If you're experiencing this issue against the latest version of Cypress you should open a new issue and provide all the information requested in the template including Debug Logs and a compete, reproducible example that we can run locally to troubleshoot your problem.

**Comment by Jai-Gogineni** [comment] 2023-07-09 23:55
Hi All,  I can confirm this issue is still happening with current version of cypress using cypress-BDD.

My `/e2e.ts`

`Cypress.on("uncaught:exception", (err, runnable) => {
  return false;
});`

I can definitely say its erroring dev code, but the config to say ignore the error is not doing anything just fails the test.

<img width="598" alt="image" src="https://github.com/cypress-io/cypress/assets/6741795/4bfb046a-fd39-4b03-8e4b-21d7de374a85">

**Comment by lmiller1990** [comment] 2023-07-10 23:44
Please provide a minimal reproduction. I tried to reproduce, works fine for me. I will reopen if you can provide a reproduction and take a look.

Repro: https://github.com/lmiller1990/cypress-test-tiny/compare/master...lmiller1990:cypress-test-tiny:issue-22129?expand=1

![image](https://github.com/cypress-io/cypress/assets/19196536/93558a17-e09c-4ad4-ab0b-8bc86a1bd357)

**Closed** 2023-07-10 23:54 UTC

**Comment by ferdinandsousa** [comment] 2023-12-12 22:30
I'm getting this error in a cy.origin block. The Cypress version I'm running is 12.17.4

      const baseUrl = 'https://www.sampleUrl.com/';

      cy.origin(baseUrl, () => {
          Cypress.on('uncaught:exception', () => false);
          // any application JS errors here cause the test to fail. The uncaught:exception does not trap it!
          cy.get('h1').contains('some text');
        });

**Comment by trainoasis** [comment] 2024-02-29 09:52
Also started happening to us recently (we re on v13.6.6), 

```
- click
(uncaught exception)Error: ResizeObserver loop completed with undelivered notifications.
```

even though we have this in since forever and it worked before:

```
// Handle exceptions
// https://docs.cypress.io/api/events/catalog-of-events#To-conditionally-turn-off-uncaught-exception-handling-for-a-certain-error
Cypress.on("uncaught:exception", (err, runnable, promise) => {
  // do not stop test execution when the bellow error is encountered
  if (
    err.message.includes(
      "Cannot read properties of null (reading 'message')"
    ) ||
    err.message.includes("ResizeObserver loop limit exceeded")
  ) {
    return false;
  }
  // we still want to ensure there are no other unexpected
  // errors, so we let them fail the test
});
```

any ideas?

PS: I noticed that the message changed lol, so easy fix. I'm just checking for "ResizeObserver loop" now instead. I just simplified to 

```
const ignoreErrorMessagePartial = [
    "ResizeObserver loop",
    "Cannot read properties of null (reading 'message')",
  ];

  if (ignoreErrorMessagePartial.some((msg) => err.message.includes(msg))) {
    return false;
  }
```

**Comment by TenPotatoes** [comment] 2024-04-22 17:35
I was seeing this on Cypress 9 when I upgraded webpack. Issue was due to webpack showing the dev server error overlay, which can be turned off. https://stackoverflow.com/questions/75774800/how-to-stop-resizeobserver-loop-limit-exceeded-error-from-appearing-in-react-a
