### ISSUE TITLE
.clear() on an input at maxlength doesn’t work 

### ISSUE THREAD

**Issue by HugoGiraudel** [cypress-io/cypress#1002] opened 2017-12-04 10:26 UTC
- Operating System: 10.12.6
- Cypress Version: 1.1.3
- Browser Version: n/A

### Is this a Feature or Bug?

A bug.

### Current behavior:

Calling `.clear()` on an input with a value as long as its `maxlength` attribute value leaves the value untouched.

### Desired behavior:

Calling `.clear()` on an input with a value as long as its `maxlength` attribute value empties the field.

### How to reproduce:

1. Create an input.
2. Set its `maxlength` to `n`.
3. Set its `value` to a string of `n` characters.
4. Call `.clear()` on it.

#### Test code:

```js
cy.get('input[maxlength]').clear()
```

### Additional Info (images, stack traces, etc)

I suspect the problem to be here:

https://github.com/cypress-io/cypress/blob/324d549497345246ca76dbfb6d9ede26bb142048/packages/driver/src/cypress/keyboard.coffee#L541-L548

There is a max length, but the value is already at its max length, so it results on a no-op, when it really should clear the field.

**Comment by brian-mann** [comment] 2017-12-04 17:03
Yes this is a known problem.

It was first discussed here: https://github.com/cypress-io/cypress/issues/940#issuecomment-347267659

I started working on a solution for this and the text-mask problems but have not finished.

**Comment by JPHamlett1993** [comment] 2018-02-23 17:26
Any update one this?

**Comment by verheyenkoen** [comment] 2018-02-28 08:48
Here's a test (I put this in [keyboard_spec.coffee](https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/e2e/keyboard_spec.coffee)) to prove this bug. I didn't commit this since I didn't know if this is the right place (no other tests found for `.clear()`) and couldn't fix the bug so I just drop it here:

    it "can clear a field with maxlength", ->
      Cypress.$('input')
        .attr('maxlength', 5)
        .val('abcde')

      cy.get('input')
        .clear()
        .should('have.value', '')

**Comment by jennifer-shehane** [comment] 2018-02-28 15:21
@verheyenkoen there are tests in the [type_spec.coffee](https://github.com/corneliutusnea/cypress/blob/issue-1335/packages/driver/test/cypress/integration/commands/actions/type_spec.coffee#L2440). If you can, put these tests in there and open a WIP pull request.

**Comment by verheyenkoen** [comment] 2018-02-28 15:37
I found there appears to be a lot more bugs related to fields with maxlength, all with the same cause. Special keystrokes like backspace, del, leftarrow, rightarrow,... all seem to be ignored. Don't know about downarrow and uparrow as those only make sense in textareas and don't know if maxlength is a thing there.

**Comment by brian-mann** [comment] 2018-02-28 17:17
Yup these have been noted / documented before in an issue somewhere. I'll dig and find them. We've been experimenting with moving to native events to bypass all of these issues - although we'll likely still give you a simulated `.type()` for performance reasons, so it's still important to fix.

**Comment by kapalkat** [comment] 2018-06-29 12:38
Seems I have a similar problem. I have reported it under https://github.com/cypress-io/cypress/issues/2056

**Comment by Bkucera** [comment] 2018-06-29 12:57
I'm actively working on this issue and more related to cy.type(). Fixes should be in a patch release coming up

**Comment by vedmant** [comment] 2018-07-04 20:17
Is there a workaround how to actually clear a field with maxlength?

**Comment by kapalkat** [comment] 2018-07-04 20:37
So the problem (for me at least) is when the input filled in filled in with the maximum allowed characters. So what I do, I use jQuery to increase the maxlength parameter like so:
    cy.get('#coalTypeDescr')
        .as('coalTypeDescr')
        .then(($coalTypeDescr) => {
      Cypress.$($coalTypeDescr).attr('maxlength', 26)
    })
   cy.get('@coalTypeDescr')
      .clear()
      .type()
This works fine for me.

**Comment by ednailson** [comment] 2018-07-13 14:11
I have the same problem!

**Closed** 2018-07-23 08:43 UTC
Labels: pkg/driver, type: bug

**Comment by c32hedge** [comment] 2019-12-23 23:57
I've been having some flaky tests where `cy.clear()` sometimes fails, and the original value of the input field was the max length of the field. Looks like a recent regression? I've at least seen it in 3.7.0.

**Comment by Bkucera** [comment] 2019-12-24 02:19
@c32hedge can you give an example of a failure, with html and test code?

**Comment by jennifer-shehane** [comment] 2019-12-24 03:22
@c32hedge Please open a new issue with a reproducible example (HTML + test code). This original issue has been addressed and we have tests around it. Likely you have another case that is very similar with a slight different.
