### ISSUE TITLE
Screenshots taken during 'cypress run' do not respect the viewport size set

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#2102] opened 2018-07-05 17:48 UTC
### Current behavior:

Observe these two images:

Headless / Electron: 
![e2e spec -- goes through profile flow -- 01 - select old home size](https://user-images.githubusercontent.com/2848185/42338970-93c830d2-8059-11e8-85f2-e8b4a7823568.png)

Headed / Chrome:
![e2e spec -- goes through profile flow -- 01 - select old home size](https://user-images.githubusercontent.com/2848185/42338985-a0babc06-8059-11e8-8139-2195598027d8.png)

Notice the spacing to the Left of our Logo is much different than the spacing to left of the Logo in headed and headless, indicating that our 1500px viewport setting was not respected in headless.

### Desired behavior:

Ideally, the Viewport width should be the same for both browsers, headless and headed.

### Steps to reproduce:

Try using a Website with a viewport of 1500 pixels wide and confirm if the viewport taken in headless vs headed is the same

### Versions

Cypress 3.0.2 and MacOS

### Motivation

I am working towards pegging down the Visual Diffing workflow for our company. Truth is, having comparable screenshots in headless vs headed runs is a desirable feature. When it comes to scaling and cropping, there is no issue on my side to do some POC work to scale/crop images and set thresholds such that differences in the CI / Headless enviroment can be accounted for and ignored. However I cannot ignore the fact that headless screenshots do not honor the viewport width I explicitly set in the Cypress.json. Ideally, if the viewport is 1500px wide headed, the headless screenshots should reflect the same.

**Comment by Bkucera** [comment] 2018-07-05 18:19
Possibly related to #1857

**Comment by egucciar** [comment] 2018-07-05 18:55
@Bkucera I agree that this needs more information. I tried to output the "innerWidth" of window in both scenarios and Headless also said 1500px. Maybe it's just a difference between how High DPI screens render UIs verses the headlesS? maybe this is not a bug then, it just is confusing to me why there would be such different margins in one vs the other.

**Comment by brian-mann** [comment] 2018-07-06 01:50
I believe the reason this is happening is because in headless mode we set XVFB to render at 1280x720.

Normally Cypress scales the screen so that running tests makes no difference to the screen size. However when taking screenshots, we no longer scale the image, which forces it to display in full width + height.

Think of the 1280x720 as the literal screen size. If you've set your viewportWidth to be 1500px then it physically cannot fit inside of 1280. Your application is responsive so that it all "works" without a scrollbar, but its not the same image anymore.

We'd need to support setting xvfb viewport via the command-line, or we'd perhaps need to issue a warning or even error if you're trying to take a `cy.screenshot()` at a viewport that the screen cannot actually display.

**Comment by egucciar** [comment] 2018-07-06 02:00
Wow! Awesome that's solved for me, there's a Max width so that's good. The 1500 wasn't super necessary I'll set to 1280. 

It would be nice if full length screens could be taken by sizing up the viewport rather than scrolling due to fixed header content. I wonder if there has to be some kind of boundary on the width / height in general of the view box for taking shots or why it can't be any size?

**Comment by egucciar** [comment] 2018-07-09 13:53
@brian-mann Seeing unreliable/undesirable results with the `fullPage` screenshot capture. It would be awesome if the xvfb could respect the same viewport set in the Cypress.json, or an option to force it to do so.

**Comment by YevheniiKravchenko** [comment] 2018-12-06 14:54
Hey, 

I was able to make screenshots with headless electron with setting resolution as: 

```javascript
module.exports = on => {
  on('before:browser:launch', browser => {
    if (browser.name === 'electron') {
      return {
        width: 1600,
        height: 900,
      };
    }
  });
};
```

But question is how to get the same effect for Chrome? Trying to get it working on CI in headless mode.

**Comment by YevheniiKravchenko** [comment] 2018-12-10 11:49
Hey @brian-mann 
> We'd need to support setting xvfb viewport via the command-line

Is there any possibility to do that?

**Comment by jennifer-shehane** [comment] 2018-12-19 03:44
You can pass a `-screen` option to `xvfb-run` specifying the resolution. See [XVFB docs](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml)

Code where Cypress passes `1280x1024x8` option: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/scripts/run.js#L55

>−screen screennum WxHxD
>This option creates screen screennum and sets its width, height, and depth to W, H, and D respectively. By default, only screen 0 exists and has the dimensions 1280x1024x8.

**Comment by YevheniiKravchenko** [comment] 2018-12-21 14:07
Thanks @jennifer-shehane 

I'm trying to get it working with docker image `cypress/browsers:chrome67-ff57`, in my docker file I have the following lines: 

```
RUN Xvfb :1 -screen 0 '1600x1024x16' -ac &> /dev/null &
RUN export DISPLAY=:1
```

Is that enough for cypress to pick up the display or am I missing something?

**Comment by jennifer-shehane** [comment] 2019-01-08 10:52
@YevheniiKravchenko Sorry, I was addressing the core changes needed for cypress to fix this issue. 

To pass the options to chrome, you will have to pass the args slightly differently. Example of plugins file:

```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--cast-initial-screen-width=1600')
      args.push('--cast-initial-screen-height=900')

      return args
    }

    if (browser.name === 'electron') {
      args.width = 1600
      args.height = 900

      return args
    }
  })
}
```

I didn't try this locally, so let me know if this works! Be sure to check our [browser launch api docs](https://on.cypress.io/browser-launch-api).

**Comment by mgrybyk** [comment] 2019-01-21 10:44
any updates on how to set screen size to desired value instead of hardcoded  1280x720 ?

**Comment by AndreVirtimo** [comment] 2019-03-06 08:35
I had the same problem. Our CI server didn't made the screenshots in the right resolution.

I fixed it by changed the https://github.com/cypress-io/cypress/blob/develop/cli/lib/exec/xvfb.js and added xvfb_args. Here is the result: https://gist.github.com/AndreVirtimo/7bd2892478af2ea06ea7445319fbfef1#file-xvfb-js-L12-L16

I'm using hard coded FullHD resolution, but there should be used the viewPort configuration from cypress. I don't know how to get access to the configuration at this point.

The result are screenshots with the resolution 1919x1080. I don't now why the is a pixel missing. But for me this is ok at this point.

**Comment by lukeapage** [comment] 2019-03-14 08:09
On windows I've had some success running this in headless mode before cypress:

https://gallery.technet.microsoft.com/scriptcenter/2a631d72-206d-4036-a3f2-2e150f297515

**Comment by infctr** [comment] 2019-03-29 16:28
@jennifer-shehane Setting width and height for headless electron in docker container produces screenshots with correct size (`1919x1080` actually), however I seem to get a video recording error. 

```ts
// config
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'electron') {
      args.width = 1920;
      args.height = 1080;

      return args;
    }
  })
}
```

```sh
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Is the screen size too big?

**Comment by timmydoza** [comment] 2019-04-23 16:37
@infctr What docker image are you using?  I can't get the `args.width = 1400` trick to work.   Also where are you changing the settings for xvfb?  Is it in the dockerfile, or is the script run somewhere else?

**Comment by infctr** [comment] 2019-04-24 09:00
@timmydoza I've extended the image from the official repo https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/chrome69/Dockerfile, added latest yarn and dependencies needed for my project. 

The script above runs on CI as a job, sets xvfb display settings and starts the tests. You can run it as an entrypoint for you docker container. Nothing really fancy here

**Comment by timmydoza** [comment] 2019-04-24 15:48
Perfect - got it working.  Thanks!   Couldn't get it working with chrome, but it works with electron and the base:10 image.

**Comment by jennifer-shehane** [comment] 2019-07-16 08:42
Related issue: https://github.com/cypress-io/cypress/issues/3324

**Comment by sebinsua** [comment] 2019-08-14 15:39
What I've noticed is that `require('electron').screen.getPrimaryDisplay()` returns completely different `width`, `height` and `scaleFactor` depending on whether `cypress run` is run with the command line argument `--headed` or not.

When it is headless, it picks up the resolution of my monitor (`2560 x 1440`) and a scale factor of `1`. When it is headed, it seems to have a scale factor of `1.2999999523162842` and has resolutions (`1969 x 1107`) that don't match the `viewport` I selected at all (`1280 x 720`).

**Comment by rwwagner90** [comment] 2019-09-17 14:12
I'm not sure if the issues here are the same as the issues I am experiencing or not, but I have some tests where I need to check specific pixel values for `translateX` etc. Locally they all pass, but when running in CI, they are off by a few pixels. I was hoping to find a way to ensure all environments, both local and CI had the same dimensions and pixel density. Has anyone had success with this?

**Comment by ispal** [comment] 2019-10-15 10:35
Hi,

With all these messages, I'm not fully sure that are you going to make xfvb args as public properties without the need to update them manually? In CI environment where node_modules folder is cleared before every build, it's not really usable currently.

**Comment by ispal** [comment] 2019-10-17 13:27
Our CI is on a Windows machine and the screenshots taken are **1024x768** which are way too small. I checked the code and there's a check for Windows and those arguments are not passed on in Windows environment. It must behave differently in Windows? Anyway to override that 1024x768?

> You can pass a `-screen` option to `xvfb-run` specifying the resolution. See [XVFB docs](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml)
> 
> Code where Cypress passes `1280x1024x8` option: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/scripts/run.js#L55
> 
> > −screen screennum WxHxD
> > This option creates screen screennum and sets its width, height, and depth to W, H, and D respectively. By default, only screen 0 exists and has the dimensions 1280x1024x8.

**Comment by jennifer-shehane** [comment] 2019-10-17 14:35
I made some comments on how screenshots sizes work some and how we will improve the documentation around it here: https://github.com/cypress-io/cypress/issues/3324#issuecomment-542414532 May be relevant.

**Comment by ispal** [comment] 2019-10-18 08:13
Hmm..I think my issues is not related to that. The problem for us is that we get different screenshot sizes by running module version of Cypress headlessly so there's no `cypress run` vs `cypress open`

Here's the interesting part. If I remotely connect to a computer where our CI is, open `cmd` and run `node cypress-runner` manually, I will get the correct screenshot **1600x1000px**, but If I run that command as part of build step, I will get a screenshot with size **1024x768px**. So it's the same machine and script is run similarly, but results differ.

We have added the following to the plugins section and I have confirmed that in both circumstances it will go where those args are set.

```on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'electron') {
      args.width = 1600;
      args.height = 1000;

      return args;
    }
  });
```

Do you have any pointers why that would happen? Could it be that if I RDP to that machine, it will get the screen of my client machine and that's why it works?

**Comment by rwwagner90** [comment] 2019-10-18 14:51
I think in my case, since the px were only off by a few, it is likely differences in scrollbar sizes in CI. Is there a way to account for that to test transform values with Cypress?

**Comment by lukeapage** [comment] 2019-10-18 17:51
@ispal in headless ci in Windows you need to change the screen resolution. I do this : https://github.com/cypress-io/cypress/issues/2102#issuecomment-472745419

**Comment by tonilopezmr** [comment] 2019-10-21 08:10
I'm not able to make screenshot testing with cypress working on **CI**, because, `Image size (1280x1024) different than saved snapshot size 1279x1023.`. I'm using Github Actions for that and I can't execute `Xvfb` command. Also, cypress runs an `Xvfb` immediately before to run the cypress.  

Cypress config
```javascript 
{
"viewportWidth": 1280,
"viewportHeight": 1024
}
```

Cypress plugin setting width and height viewport.

```javascript
const {
  addMatchImageSnapshotPlugin
} = require('cypress-image-snapshot/plugin');

module.exports = (on, config) => {
  addMatchImageSnapshotPlugin(on, config);
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'electron') {
      args.width = 1280;
      args.height = 1024;

      return args;
    }
  });
};

```

**Comment by AndreVirtimo** [comment] 2019-10-21 08:41
@tonilopezmr I'm change my "node_modules/cypress/lib/exec/xvfb.js" File directly and add xvfb args to set my needed screen size. Here is my script from our CI workflow:

`sed -i "24 a xvfb_args: ['-screen','0','1920x1080x8']," node_modules/cypress/lib/exec/xvfb.js`

**Comment by tonilopezmr** [comment] 2019-10-21 08:45
@AndreVirtimo Sorry I don't understand your lines, I'm in the `xvfb.js` but which changes are you talking about? I'm don't see any xvfb args.

**Comment by AndreVirtimo** [comment] 2019-10-21 08:51
@tonilopezmr "sed" inserts a new line in this file. The result snipped is this:

> (...)
> module.exports = {
>   _debugXvfb: debugXvfb, // expose for testing
> xvfb_args: ['-screen','0','1920x1080x8'],
> 
>   _xvfb: xvfb, // expose for testing
> 
>   start: function start() {
>     debug('Starting XVFB');
> (...)

It seems that cypress does not set the xvfb screen size.

**Comment by tonilopezmr** [comment] 2019-10-21 11:42
@AndreVirtimo And how did you run that on the CI?

I have tried to add these arguments but it still failing: https://github.com/Karumi/LitElementPlayground/runs/268134245

I'm copying `xvfb.js` [file](https://github.com/Karumi/LitElementPlayground/blob/add-cypress/cypress/scripts/xvfb.js) with the arguments into the `node_modules xvfb.js` running this script https://github.com/Karumi/LitElementPlayground/blob/add-cypress/cypress/scripts/xvfbargs.js.

And this is the cypress dashboard: https://dashboard.cypress.io/#/projects/144fs5/runs

**Comment by ispal** [comment] 2019-10-21 18:54
> @ispal in headless ci in Windows you need to change the screen resolution. I do this : [#2102 (comment)](https://github.com/cypress-io/cypress/issues/2102#issuecomment-472745419)

Yeah, maybe that or I might give this a go: https://docs.microsoft.com/en-us/powershell/module/servercore/set-displayresolution?view=win10-ps

**Comment by sebinsua** [comment] 2019-11-11 17:18
Since posting my last comment, I upgraded to Cypress 3.6 and using Chrome within Docker.

After doing this the maximum width of the browser in headless mode ends up being 1050px. That is despite the `viewportWidth` being set to 1280px. It appears to be clipped to this value, however I'm not sure why.

For now, the quick fix seems to be setting the `viewportWidth` to 1280px, since this is obeyed by both headless mode and headed mode.

**Comment by WolfgangFellger** [comment] 2019-12-11 15:38
@sebinsua We experienced the same issue. Passing --window-size seems to do the trick (at least in cypress 3.7) without the other shenanigans mentioned in this thread:

```js
on('before:browser:launch', (browser = {}, args) => {
	if (browser.name === 'chrome') {
		args.push('--window-size=1920,1080')
		return args
	}
})
```

**Comment by memee** [comment] 2019-12-31 13:12
> You can pass a `-screen` option to `xvfb-run` specifying the resolution. See [XVFB docs](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml)
> 
> Code where Cypress passes `1280x1024x8` option: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/scripts/run.js#L55
> 
> > −screen screennum WxHxD
> > This option creates screen screennum and sets its width, height, and depth to W, H, and D respectively. By default, only screen 0 exists and has the dimensions 1280x1024x8.
@jennifer-shehane I would rather not modify cypress code. Is there a recommended way to pass custom resolution to Xvfb with cypress? In plugins maybe. Besides, I'm using `image: cypress/browsers:chrome69` in `gitlab-ci` and `cypress-plugin-snapshot`. I found the similar issue there: https://github.com/meinaart/cypress-plugin-snapshots/issues/71

**Comment by warpech** [comment] 2020-02-06 10:10
I got lucky with resolution 2560x1440 in headless Chrome in Docker, without messing with `xvfb`.

I used the Docker image  `cypress/included` version 3.8.3. My config:

1. In `cypress.json`, set: 
   ```json
   "viewportWidth": 2560, 
   "viewportHeight": 1024
   ```
2. In `cypress/plugins/index.js`, set:
   ```js
   on('before:browser:launch', (browser = {}, args) => {
     if (browser.name === 'chrome') {
       args.push('--window-size=2560,1440');
       return args;
     }
   });
   ```
3. In the tests, set `cy.viewport(2560, 1440);`
4. My Docker-compose YML file that I use for running Cypress:
   ```yml
   version: '3.5'
   services:
     cypress:
       image: "cypress/included:3.8.3"
       environment:
         - CYPRESS_baseUrl=http://host.docker.internal:8080
         - CYPRESS_cmd
       working_dir: /app
       volumes:
         - ../:/app
       command: --browser chrome --headless ${CYPRESS_cmd}
   ```

${CYPRESS_cmd}` is used to pass any additional command options, such as the name of the test file to run.

----

As mentioned in the beginning, this works with the resolution 2560x1440. I tried 3840x2160 to no availl. `cypress run` froze at executing the first test. I did not investigate further.

**Comment by RichieRunner** [comment] 2020-02-07 01:34
> @sebinsua We experienced the same issue. Passing --window-size seems to do the trick (at least in cypress 3.7) without the other shenanigans mentioned in this thread:
> 
> ```js
> on('before:browser:launch', (browser = {}, args) => {
> 	if (browser.name === 'chrome') {
> 		args.push('--window-size=1920,1080')
> 		return args
> 	}
> })
> ```

which file does this go in?

**Comment by RichieRunner** [comment] 2020-02-07 01:43
> ```json
> 1080
> ```

Still doesn't work for me. There are still differences with just running `run` and `open` locally. This is just silly.

**Comment by RichieRunner** [comment] 2020-02-07 01:44
> I got lucky with resolution 1980x1080 in headless Chrome in Docker, without messing with `xvfb`.
> 
> I used the Docker image `cypress/included` version 3.8.3. My config:
> 
> 1. In `cypress.json`, set:
>    ```json
>    "viewportWidth": 1920, 
>    "viewportHeight": 1080
>    ```
> 2. In `cypress/plugins/index.js`, set:
>    ```js
>    on('before:browser:launch', (browser = {}, args) => {
>      if (browser.name === 'chrome') {
>        args.push('--window-size=1920,1080');
>        return args;
>      }
>    });
>    ```
> 3. In the tests, set `cy.viewport(1920, 1080);`
> 4. My Docker-compose YML file that I use for running Cypress:
>    ```yaml
>    version: '3.5'
>    services:
>      cypress:
>        image: "cypress/included:3.8.3"
>        environment:
>          - CYPRESS_baseUrl=http://host.docker.internal:8080
>          - CYPRESS_cmd
>        working_dir: /app
>        volumes:
>          - ../:/app
>        command: --browser chrome --headless ${CYPRESS_cmd}
>    ```
> 
> ${CYPRESS_cmd}` is used to pass any additional command options, such as the name of the test file to run.
> 
> As mentioned in the beginning, this works with the resolution 1920x1080. At first, I tried 3840x2160 but `cypress run` froze at executing the first test. Later, I tried 2560x1440, but `cypress run` was still freezing at some tests 50% of the time. I settled on 1920x1080 and did not investigate further.
------------------
Still doesn't work for me. There are still differences with just running run and open locally. This is just silly.

**Comment by warpech** [comment] 2020-02-07 10:39
> Still doesn't work for me. There are still differences with just running run and open locally. This is just silly.

Yes, there are differences and there will be. When you open locally, the browser engine is Chromium on Mac/Windows/etc. When you run in Docker, the browser engine is Chromium on Linux inside Docker. It is just too different platforms to ever render the same screenshot.

For that reason, I never use `cypress run`, because it runs Chromium locally. I only use `cypress gui` locally for debugging without screenshots, or `docker-compose` to run Cypress in Docker with screenshots. That setup gives me the same screenshots in Windows, Mac, Linux and CI (GitHub Actions).

**Comment by RichieRunner** [comment] 2020-02-07 19:26
> 
> Yeah, for that reason I never create screenshots locally. I only use `cypress gui` locally for debugging without screenshots, or `docker-compose` to run Cypress in Docker with screenshots. That setup gives me the same screenshots in Windows, Mac, Linux and CI (GitHub Actions).

oh, so do you mean create the baseline images FIRST through your CI build pipeline?

**Comment by warpech** [comment] 2020-02-08 12:29
> oh, so do you mean create the baseline images FIRST through your CI build pipeline? Interesting. Then where/how would you find it to commit into into your source control?

No, I create the images on my developer machine using Chrome in Docker and commit them into the source control. The CI pipeline runs the tests and compares the screenshots in the source control with the current app using the plugin https://github.com/palmerhq/cypress-image-snapshot

**Comment by laurogripa** [comment] 2020-04-08 21:29
Possibly related: [electron#21379: Screen dimensions are off by one pixel in offscreen mode](https://github.com/electron/electron/issues/21379)

**Comment by lunaboona** [comment] 2020-04-13 12:14
> 
> 
> > Yeah, for that reason I never create screenshots locally. I only use `cypress gui` locally for debugging without screenshots, or `docker-compose` to run Cypress in Docker with screenshots. That setup gives me the same screenshots in Windows, Mac, Linux and CI (GitHub Actions).
> 
> oh, so do you mean create the baseline images FIRST through your CI build pipeline? Interesting. Then where/how would you find it to commit into into your source control?

Not necessarily take the screenshots in the CI pipeline, but rather use the same docker image in CI and locally to generate the base screenshots.

**Comment by iamjoncannon** [comment] 2020-07-09 16:39
Wanted to update the @RichieRunner solution above for headless Chrome. I spent some time on this yesterday.

Set up is Cypress 4.5 with cypress-image-snapshot in Docker (not using a cypress pre-build image). 

I am running VRTs across viewports, and ran into this bug-- the tests were all coming out at 1280px and below, even with the viewport set at higher widths. 

The following works at viewports above 1920-- 

cypress.json

```js
{
    "viewportWidth": 2560, 
    "viewportHeight": 1080
}
```

cypress/plugins/index.js

```js
on('before:browser:launch', (browser = {}, launchOptions) => {

    if (browser.name === 'chrome') {
      launchOptions.args.push('--disable-dev-shm-usage')
      launchOptions.args.push('--window-size=2560,1080')
      return launchOptions
    }
  })
```

When I tried @RichieRunner solution initially the suite froze after taking the 1920 shot, but "disable-dev-shm-usage ended up resolving the issue-- the suite loads at 2560 and reduces the screensize correctly for each it block.  (Lower viewports are less memory intensive, which is why running at default 1280 works even without that other flag)

@jennifer-shehane It might make sense to add this information here-- https://docs.cypress.io/api/plugins/browser-launch-api.html#Set-screen-size-when-running-headless-Chrome-- and/or here-- https://docs.cypress.io/guides/guides/continuous-integration.html#In-Docker -- and make it a bit more explicit that this is the solution to this issue.  

The basic idea is-- headless Chrome in CI needs to load at the max viewport width the test will require, and from there it will resize properly during the run.

**Comment by FDiskas** [comment] 2020-09-15 09:16
Got it working by following the docs https://docs.cypress.io/api/plugins/browser-launch-api.html#Set-screen-size-when-running-headless

**Comment by jennifer-shehane** [comment] 2021-01-07 04:51
I'm going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/587 "Make screenshot/video size configurable" because overall, I think this entire thread demonstrates a lack of a straightforward way to explicitly set the size you want screenshots (and videos) to be taken at.

I've noted all of the feedback within this thread for reference when we move forward with implementing a solution to this. Thanks everyone. This issue will be left open for comments so that workarounds can continue to be discussed openly.

**Closed by jennifer-shehane** 2021-01-07 04:51 UTC
Labels: stage: ready for work, topic: screenshots 📸, type: unexpected behavior

**Comment by Pieras2** [comment] 2021-04-13 07:58
What is the current status?
Should I pass some params to configure it the way it worked always the same time?
I installed 7.1.0 but still I encounter case where I run tests and I see image differences between 1st and 2nd run of the comparision test :(

**Comment by andrewalc** [comment] 2021-09-28 15:12
> Got it working by following the docs https://docs.cypress.io/api/plugins/browser-launch-api.html#Set-screen-size-when-running-headless
> 
> ```js
>     if (browser.name === 'electron') {
>       // fullPage screenshot size is 768x1024
>       launchOptions.preferences.width = 768;
>       launchOptions.preferences.height = 1024;
>       launchOptions.preferences.frame = false;
>       launchOptions.preferences.useContentSize = true;
>     }
> ```

The documentation link solved my issue.  I went down a rabbit hole of issues in this repo to find this. Just want to leave some notes on how i got here and give some thoughts / suggest some documentation edits.

My initial issue was my headless screenshots were being scaled to a smaller resolution. This caused the charts i was screenshotting to be cut in half, which would not do for my image-regression tests. My first assumption was `cy.screenshot`'s `scale` option had something to do with it. When i gave up on that I assumed `viewportWidth` and `viewportHeight` in `cypress.json` would affect the headless width and height, which lead me to try and use `cy.viewport` to change this to no avail.

It would be incredibly helpful if [this section](https://docs.cypress.io/api/plugins/browser-launch-api.html#Set-screen-size-when-running-headless) was linked on the cy.viewport or cy.screenshot docs page. clarifying that scaling issues with screenshots in headless mode is solved by this specific plugin config where you set your desired resolution, or a mention of how cy.viewport in headless mode doesn't behave correctly and to get your screenshots to look the way you want you need to edit the plugin config. I basically just replaced the resolution values with the values i had defined in `viewportWidth` and `viewportHeight` already.

The fact that `viewportWidth` and `viewportHeight` does not affect headless viewport height and width despite the docs saying it is global seems incredibly misleading to me. The mention that these [two variables are Global](https://docs.cypress.io/api/commands/viewport#Syntax) at the top of the page leads me to expect this should affect the viewport everywhere, including headless mode. There is no mention that these two variables do not affect headless mode [here either](https://docs.cypress.io/guides/references/configuration#Viewport). If the intent is to not affect headless mode and explicit define it through a plugin, then perhaps `runnerViewportWidth` and `runnerViewportHeight` would describe this better. Otherwise I would really hope this would set the default viewport resolution everywhere, whether its in the runner or headless.

**Comment by jennifer-shehane** [comment] 2021-11-02 22:35
Yes, headed Chrome has a strange way of setting the screen size. We definitely recommend using the same headed/headless value when comparing snapshots. Hopefully we can standardize the Chrome headed size in the future.
