### ISSUE TITLE
DOM Snapshots are blank in ionic app

### ISSUE THREAD

**Issue by pszalanski** [cypress-io/cypress#5776] opened 2019-11-22 10:09 UTC
### Current behavior:

Our ionic app is tested using cypress and everything works fine so far. But if we hover over a test step in the history, the app preview is blank. Normally, it displays a snapshot of the DOM at that time.

### Desired behavior:

The app view should show the rendered DOM at the hovered or pinned point in time.

### Screencap of issue:

![cypress](https://user-images.githubusercontent.com/4761826/69417184-71edaf80-0d18-11ea-94e4-a658c8892b07.gif)

### Versions

Windows 10
Cypress 3.6.1
Ionic 4.11.5
capacitor 1.3.0
Angular 8.1.2

**Comment by devinshoemaker** [comment] 2019-12-15 16:34
I have noticed the same behavior with both Ionic Angular and Ionic React.

**Comment by jennifer-shehane** [comment] 2019-12-16 05:01
I believe this is due to [Ionic using Shadow DOM](https://ionicframework.com/blog/shadow-dom-in-ionic-and-why-its-awesome/), which is not fully supported in Cypress. Duplicate of https://github.com/cypress-io/cypress/issues/144

**Closed by jennifer-shehane** 2019-12-16 05:01 UTC

**Comment by jennifer-shehane** [comment] 2020-06-09 09:04
We've added experimental shadow DOM support through the `experimentalShadowDomSupport` configuration option.

To use it, update to Cypress 4.8.0 and pass the following to your configuration file or however you pass in configuration. 

```json
{
  "experimentalShadowDomSupport": true
}
```

See the [Experiments](https://on.cypress.io/experiments#Cross-boundary-selectors) for more information including how to use the new `.shadow()` command and `includeShadowDom` option.

This is still experimental, so we'd like your help working through any bugs or unexpected behavior before releasing into the main product. If you encounter any issues using the new experimental shadow DOM feature, please **[open a new issue](https://github.com/cypress-io/cypress/issues/new)**, filling in the issue template and providing a reproducible example.
