### ISSUE TITLE
Form is submitted even with invalid password input

### ISSUE THREAD

**Issue by andrecasal** [cypress-io/cypress#26643] opened 2023-05-02 19:10 UTC
### Current behavior

Form is submitted even with invalid password input. Minimal reproduction:

https://user-images.githubusercontent.com/22457463/235953418-74b4bf4d-84d7-4af1-a3e5-e171410aa5e5.mov

### Desired behavior

I would expect the form to **not** be submitted because the [ValidityState](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) object should have `tooShort` set to `true`.

### Test code to reproduce

[Here](https://github.com/andrecasal/cypress-form-submittion-with-invalid-inputs-bug)'s a minimal reproduction:
- `npm i`
- `npm run start`
- `npm run cypress`

Notice the test fails because the form is submitted, even though it shouldn't be because the password field has a `minlength="8"` and the password has 7 characters.

### Cypress Version

12.8.1

### Node version

18.2.0

### Operating System

macOS Ventura 13.2.1

**Comment by nagash77** [comment] 2023-05-03 12:36
Hi @andrecasal Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by andrecasal** [comment] 2023-05-03 14:53
Alright, I created a [minimal reproduction repo](https://github.com/andrecasal/cypress-form-submittion-with-invalid-inputs-bug). Please reopen :)

**Comment by nagash77** [comment] 2023-05-03 18:44
@andrecasal Thank you for providing this example.  I will assign out to one of our engineers for investigation.

**Comment by andrecasal** [comment] 2023-05-05 09:32
Hey @mschile 👋 Thank you for taking the time to help out 🙏

Please let me know if there's any problem with the minimal reproduction and I'll try to fix it as soon as possible.

**Comment by mschile** [comment] 2023-05-05 22:39
Hi @andrecasal 👋, thanks for logging this issue. It appears to be duplicate of https://github.com/cypress-io/cypress/issues/6678. If you are testing in Chromium-based browsers, you can use [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events) to type into the password field so validation is correctly triggered.

![Image](https://user-images.githubusercontent.com/2002044/236580453-af295f19-e9c0-410e-8f4a-1722b276b79c.png)

**Closed as not planned by mschile** 2023-05-05 22:39 UTC
