### ISSUE TITLE
Component testing viteConfig override gets ignored

### ISSUE THREAD

**Issue by palasjir** [cypress-io/cypress#23487] opened 2022-08-22 08:53 UTC
### Current behavior

Defining custom vite config get's ignored despite being set as variable for `devServer`. It still loads `vite.config.ts` instead.

### Desired behavior

When `viteConfig` is specified on the `devServer` manually it should take precedence over other files.

### Test code to reproduce

```
import { defineConfig } from 'cypress';
import { defineConfig as defineViteConfig} from 'vite';

const customViteConfig = defineViteConfig({
        plugins: [react()],
});

export default defineConfig({
  component: {
    devServer: {
      framework: 'react',
      bundler: 'vite',
      viteConfig: customViteConfig // ignored
    },
  },
});
```

### Cypress Version

10.6.0

### Node version

16.13.0

### Operating System

macOS 12.4

**Comment by mike-plummer** [comment] 2022-08-22 20:35
Hi @palasjir , thanks for opening an issue!

The `viteConfig` field is intended as a set of overrides that get merged into your base `vite.config.js` to allow small tweaks to your config, rather than serving as a standalone Vite config itself. The idea is that most users will want to use a similar, if not identical, config to ensure their tests are validating their components as closely as possible to their production behavior. For reference, you can see the logic for how the Vite config is being [generated here](https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/src/resolveConfig.ts#L93), it uses [Vite's mergeConfig function](https://vitejs.dev/guide/api-javascript.html#mergeconfig) to deeply merge the two configs.

If this is not behaving the way I've described it would really help to have a small reproducible example so we can debug and figure out what's wrong. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-30 18:07
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-30 18:07 UTC
Labels: type: bug, CT, Needs Reproduction
