### ISSUE TITLE
Pass custom headers when clicking

### ISSUE THREAD

**Issue by pmelab** [cypress-io/cypress#4455] opened 2019-06-13 08:52 UTC
### Current behavior:

When custom `headers` are added to `cy.visit` they are properly added to the request. When executing a `cy.click` operation, the headers are not added to the result request.

### Desired behavior:

The `cy.click` sends the same request `headers` as `cy.visit` does.

### Versions

3.3.1

**Comment by jennifer-shehane** [comment] 2019-06-13 09:56
Can you please explain what happens in your application when you `click` - is there an XHR request? A form submission? We need to know what you are expecting headers on here.

**Comment by pmelab** [comment] 2019-06-13 10:41
Just standard browser click events. E.g. following a link or submitting a form. There are not click handlers involved.

I managed to achieve the current behaviour by:

* Overriding `visit` and `request` and injecting headers there
* Add custom headers to all XHR requests as illustrated in https://docs.cypress.io/api/commands/server.html#Set-a-custom-request-header-for-all-requests

**Comment by pmelab** [comment] 2019-06-13 15:22
Another observation: If cypress is following a redirect (301), the headers set on the initial `cy.visit` command are also passed to the redirect request.

**Comment by flotwig** [comment] 2019-06-13 15:25
@pmelab `cy.visit` headers are only for the initial request and any redirects that immediately follow it, they will not be reused on subsequent requests. 

Are you trying to send basic auth with every request? If so, `cy.visit`'s `auth` parameter is what you're looking for - it will be sent with every request if supplied.

`cy.route` and `cy.server` can be used to add headers to every request, but currently, these only work with XHRs. #687 will change that so that all network traffic can be intercepted.

**Comment by pmelab** [comment] 2019-06-13 15:56
Thanks, @flotwig! Yes this issue seems to be resolved with #678. Is there a status update on this?

Unfortunately, it's not basic auth, but other custom headers.

**Comment by jennifer-shehane** [comment] 2019-06-21 09:44
Will close as duplicate of #687 then - this is an issue @flotwig is actively working on when not busy fixing recently released regressions.

**Closed by jennifer-shehane** 2019-06-21 09:44 UTC

**Comment by ataylorme** [comment] 2020-03-03 20:31
> Overriding visit and request and injecting headers there

@pmelab I need to add a header to all requests as well. Can you share an example of how you did this?
