### ISSUE TITLE
More Emphasis on Typescript

### ISSUE THREAD

**Issue by craig-dae** [cypress-io/cypress#6847] opened 2020-03-25 17:42 UTC
Suggestion. Lower the barrier of entry to developers that prefer to use TypeScript over Javascript when writing tests.

### Current behavior:

Typescript was very difficult to set up. The initial cypress project is created in JS, and it took several hours to properly convert the project to use TypeScript.

### Desired behavior:

Create a project in TypeScript, without having to put effort into converting it. 

Also come up with some way of writing new Commands without having to update index.d.ts.

Also provide examples on how to break up `command.ts` into multiple files more easily, since this is not also obvious how to do even for a dev experienced in TypeScript. 

### Test code to reproduce

N/A

### Versions

4.1.0

**Comment by CypressJoseph** [comment] 2020-03-25 18:45
#5906 is all about this!

**Comment by jennifer-shehane** [comment] 2020-03-26 10:10
Duplicate of #1859

**Closed by jennifer-shehane** 2020-03-26 10:10 UTC
