### ISSUE TITLE
Cypress v8.5.0. fails with exit code 2147483651

### ISSUE THREAD

**Issue by far11ven** [cypress-io/cypress#18426] opened 2021-10-09 06:13 UTC
### Current behavior
```
> npx cypress open --env configFile=stg

It looks like this is your first time using Cypress: 8.5.0


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with exit code 2147483651: C:\Users\QCuser\AppData\Local\Cypress\Cache\8.5.0\Cypress\Cypress.exe --smoke-test --ping=177

----------

Platform: win32 (10.0.19043)
Cypress Version: 8.5.0
```

### Cypress Version

8.5.0

### Package Manager

npm

### Operating system

Windows

**Comment by jennifer-shehane** [comment] 2021-10-11 18:00
Duplicate of https://github.com/cypress-io/cypress/issues/17928

**Closed by jennifer-shehane** 2021-10-11 18:00 UTC
Labels: topic: installation
