### ISSUE TITLE
Customized assersion message not shown when using 'Cypress run'

### ISSUE THREAD

**Issue by iyangdidi** [cypress-io/cypress#14484] opened 2021-01-11 16:16 UTC
### Current behavior

I use following code to customize the assersion message
`
dossierPage.filerPanel.getCapsuleItems(filerName1).should(($lis) => {
            expect($lis, 'Filter "'+filerName1+'"should have 4 items').to.have.length(5)
        })
`
The customized message can be shown when using 'cypress open'
![image](https://user-images.githubusercontent.com/16665034/104206323-5ef6dc80-53fd-11eb-9f88-67fcad63607f.png)

But 
1. can't shown when using 'cypress run'
![image](https://user-images.githubusercontent.com/16665034/104206405-7df56e80-53fd-11eb-9c6b-8b735241cba2.png)
2. the line number throw the error is not right

### Desired behavior

1. customized message should also be shown when using 'cypress run'
2. the line number throw the error should be the right line number
Here is an example of protractor as an reference
![image](https://user-images.githubusercontent.com/16665034/104206812-fc521080-53fd-11eb-9fad-4c71853de236.png)

### Test code to reproduce

1. any test scripts, add customized message to 'expect', 
2. fail the assersion
3. run with 'cypress open'
4. run with 'cypress run'
5. check the failure information

### Versions
"cypress": "^5.5.0",

**Comment by bahmutov** [comment] 2021-01-11 16:26
Can you try the latest Cypress v6 version?

**Comment by jennifer-shehane** [comment] 2021-01-12 01:16
In this case, the actual error thrown does not contain the custom assertion error message and is instead overwritten by the Cypress error thrown. This is true in both `cypress open` and `cypress run`. 

Cypress does show the custom error message in the Command Log in `cypress open` though, which is not visible during `cypress run`.

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('div').should(($divs) => {
    expect($divs, 'Filter should have 1 items').to.have.length(1)
  })
})
```

```html
<html>
<body>
<div></div>
<div></div>
</body>
</html>
```

<img width="622" alt="Screen Shot 2021-01-12 at 7 41 10 AM" src="https://user-images.githubusercontent.com/1271364/104256612-ec900600-54a9-11eb-94ab-e3f6171290ff.png">

The second issue about the stack trace line is a duplicate of this issue: https://github.com/cypress-io/cypress/issues/7715

**Comment by iyangdidi** [comment] 2021-01-12 21:57
@jennifer-shehane 
Thanks for the prompt reply. 
So are you plan to fix this? and how about the time plan?

**Closed** 2021-03-10 16:59 UTC
Labels: stage: work in progress, type: error message, type: unexpected behavior
