### ISSUE TITLE
Symbol not found: _napi_acquire_threadsafe_function

### ISSUE THREAD

**Issue by vjpr** [cypress-io/cypress#4919] opened 2019-08-02 23:08 UTC
<details> 
<summary>Stack trace</summary>

```
Error: dlopen(/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/node_modules/fsevents/fsevents.node, 1): Symbol not found: _napi_acquire_threadsafe_function
  Referenced from: /xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/node_modules/fsevents/fsevents.node
  Expected in: flat namespace
 in /xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/node_modules/fsevents/fsevents.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/node_modules/fsevents/fsevents.js:13:16)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/node_modules/fsevents/fsevents.js:64:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/lib/fsevents-handler.js:8:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/lib/fsevents-handler.js:489:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/index.js:14:25)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/chokidar/index.js:903:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/watchers.js:6:14)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/watchers.js:94:4)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/watchers.js:96:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:47:14)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:680:4)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:682:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/gui/events.js:32:13)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/gui/events.js:276:4)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/gui/events.js:278:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/interactive.js:28:12)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/interactive.js:139:4)
    at Object.<anonymous> (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/interactive.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at module.exports (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/index.js:9:16)
    at /xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js:52:38
    at tryCatcher (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.runElectron (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js:46:28)
    at Object.startInMode (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js:159:23)
    at /xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js:115:24
    at tryCatcher (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at /xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/nodeback.js:42:21
    at xfs.stat (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at callback (/xxx/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqWrap.oncomplete (fs.js:153:5)
```
</details>

**Comment by jennifer-shehane** [comment] 2019-08-05 10:24
Hi, can you detail what you did when this error message displayed? Were you installing Cypress? Clearing cache? Running Cypress? It's best if we can reproduce the error message. Thanks!

**Comment by vjpr** [comment] 2019-08-05 10:45
I upgraded to latest cypress and then ran it. 'Cypress open'

**Comment by jennifer-shehane** [comment] 2019-08-05 13:10
Could you run `cypress open` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the logs here?

**Comment by vjpr** [comment] 2019-08-05 14:25
Everything seems to work fine, its just this large stack trace in the console.

It seems the file watching lib (fsevents) and the Electron Node.js version.

What version of Electron are you using?

**Comment by jennifer-shehane** [comment] 2020-10-20 08:14
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-10-20 08:14 UTC
Labels: stage: needs information
