### ISSUE TITLE
Cypress actionability validation does check the `aria-disabled` attribute

### ISSUE THREAD

**Issue by tbiethman** [cypress-io/cypress#22578] opened 2022-06-28 23:00 UTC
### Current behavior

Cypress performs some [actionability](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Actionability) validation prior to interacting with elements. Part of this validation includes determining whether an element is [disabled](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Disability) or not, by checking for the presence and value of the `disabled` attribute on that element.

However, we do not check for the presence of the [`aria-disabled`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled) attribute, which can be used more broadly to indicate to assistive technologies that an element is not interactive while keeping it accessible.

### Desired behavior

We should additionally check for the presence of the `aria-disabled` attribute as part of our standard actionability logic.

https://github.com/cypress-io/cypress/blob/d7218aab7ed7064ba2c28ba898934e88978d0888/packages/driver/src/cy/ensures.ts#L130

### Test code to reproduce

This issue was raised during a PR review where we ran into this ourselves: https://github.com/cypress-io/cypress/pull/22569#discussion_r908844548

Easiest way to test/validate would be to enhance an existing actionability test to use `aria-disabled` rather than `disabled`: https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/actions/click.cy.js#L1575-L1594

### Cypress Version

10.3.0

**Comment by marktnoonan** [comment] 2023-01-18 14:54
Followed a link to this from Discord, I think this one is actually tricky. I'm not sure we should implement this as an actionability check, but maybe we could warn about it.

`aria-disabled` doesn't mean the application has prevented users from interacting with the element (based on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled). Clicks etc _do work_ unless actively prevented by further steps taken with JS/CSS. It tells screen reader users that the element is not meant be usable, but if the element actually is still useable according to our existing actionability checks, this is a problem in the application itself imo.

It's incorrect to describe such elements as "not actionable", since their true actionability depends on how the application is implemented. It's certainly often wrong and incoherent for a test to pass by clicking on elements that have the `aria-disabled` attribute (but actually work), so a warning might be good.

That said, it's not even always wrong. Elements semantically disabled this way might still be actually clickable but not have the usual side effect, for example, and that seems valid. And it would be valid for a test to click that element and verify it didn't have the effect.

(Side note: To implement this, we would need to check for `.closest('[aria-disabled]')` in ancestors as well since focusable descendants of an `aria-disabled` element are also semantically disabled, which adds just a little extra complexity & maybe subtle perf cost if we are doing it for every interaction?)

**Comment by JMKJR** [comment] 2023-01-18 16:20
@marktnoonan agree with your thoughts here. Some kind of warning could be useful, otherwise it could be a pain for you guys to have to attend to this thread getting frequently bumped and/or duplicate issues created.

**Comment by todd-m-kemp** [comment] 2023-07-24 14:03
This discussion is still relevant and should not be considered stale IMO.

**Comment by scttdavs** [comment] 2023-08-10 13:54
I'll just say in our use case, our design system team has a Button component that uses `aria-disabled` + prevents clicks manually vs just using the disabled field. While this is a little controversial in its own right, they do it so that they can still have mouse events on a disabled button (to trigger a tooltip for example).

Now we must explicitly check for `aria-disabled` everywhere because Cypress still considers it actionable if set to true.

It would be good for an app to opt into this behavior via the Cypress config. By doing that, you're saying "yes, I'm preventing clicks for aria-disabled and I want Cypress to consider `aria-disabled="true"` not actionable".

This way it can keep to HTML standards but be flexible enough for teams to use Cypress to its full intended capability

**Comment by marktnoonan** [comment] 2023-08-10 14:02
> Now we must explicitly check for aria-disabled everywhere because Cypress doesn't consider it actionable if set to true.

I'm confused, are you saying that Cypress _does_ check for `aria-disabled`? This issue is reporting that Cypress ignores `aria-disabled`, which sounds like the opposite of what you are saying. Expected behavior currently is only that we check the [actual `disabled` property](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Disability).

Can you provide a reproduction of what you are seeing?

**Comment by scttdavs** [comment] 2023-08-10 14:04
typo, corrected in the original post

**Comment by marktnoonan** [comment] 2023-08-10 14:18
Ah I see, thanks @scttdavs. 

> This way it can keep to HTML standards but be flexible enough for teams to use Cypress to its full intended capability

I think Cypress currently provides a good way to do this, through defining a custom command. If you can share some examples of where you are having to check for `aria-disabled` in your test code I can suggest a custom command that you could implement. Right now I don't understand your actual goal - do you want Cypress to fail the test if the test attempts to click on a button that is `aria-disabled`? But still allow mouse events/focusing?

I would suggest something that ends up looking like this: `cy.get('.button-that-should-be-clickable').customClick()` and have your custom click command inspect the button to make sure it's not in a bad state.

I'm not saying we should close the door on a the conversation about this kind of actionability check, just that you can solve the problem with your need for a custom actionability check right now, without a change in behavior from Cypress.

**Comment by jennifer-shehane** [comment] 2024-06-10 21:01
Closing given the reasons that @marktnoonan outlined. Checking for aria-disabled in the actionability check does not gaurantee whether you can or cannot interact with it. 

We don’t have a mechanism for ‘warning’ here in the App, so will close.

**Closed by jennifer-shehane** 2024-06-10 21:01 UTC
Labels: type: bug, E2E
