### ISSUE TITLE
CypressError: `cy.screenshot()` timed out waiting '30000ms' to complete.

### ISSUE THREAD

**Issue by kodriscollics** [cypress-io/cypress#18778] opened 2021-11-03 16:42 UTC
### Current behavior

I run my tests headless. After upgrading to Cypress 8.7.0, whenever a test fails for whatever reason, I get the following:

     CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

That is all I get on the console. No other messages. I have to rerun the test(s) in the GUI environment to see what really happened and to get the real error. 

The above error is masking what is happening on test failure.

The problem goes away when I back-rev Cypress to version 8.5.0.

Another aspect that makes this an even worse problem is that once the error is thrown, the session never exits so the test never really finishes.

### Desired behavior

Show the real error instead of masking it with this faux error.

### Test code to reproduce

Not sure this is practical, as I have tons of tests and any failure on any test results in the problem.

### Cypress Version

8.6.0
8.7.0
9.0.0

**Comment by pawelgielda** [comment] 2021-11-04 08:23
Hey, could it be connected with the last changes introduced with: https://github.com/cypress-io/cypress/commit/c0d781d28fad4a8100d47d34a703ec6fb205eaae ?? The default timeout also changed for example in cy.request() method.

**Comment by kodriscollics** [comment] 2021-11-04 16:35
The problem goes away when I back-rev Cypress to version 8.5.0.

Another aspect that makes this an even worse problem is that once the error is thrown, the session never exits so the test never really finishes.

**Comment by szamanr** [comment] 2021-11-05 12:26
do you also experience slower runtime or video playback issues, like in #18740 or #18564?

**Comment by Arunk28** [comment] 2021-11-05 12:48
am facing the issue after updating the 8.6.0.
I will also revert and check to 8.5.0. 

but please fix this because of this all test are failed 
@jennifer-shehane

**Comment by kodriscollics** [comment] 2021-11-11 05:38
Same issue with Cypress version 9.0.0:

CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

**Comment by jennifer-shehane** [comment] 2021-11-19 20:18
Duplicate of https://github.com/cypress-io/cypress/issues/5016

**Closed by jennifer-shehane** 2021-11-19 20:18 UTC

**Comment by theTestingApproach** [comment] 2023-07-04 07:02
Hello, i am facing this same issue in 12.16.0..Any resolution so far please?

**Comment by wongk** [comment] 2023-07-06 16:02
+1

**Comment by fzampori-sumo** [comment] 2023-07-07 09:56
+1

**Comment by hannamarkevich** [comment] 2023-07-07 18:48
+ v12.9

**Comment by nagash77** [comment] 2023-07-10 13:16
As @jennifer-shehane mentioned in [this comment](https://github.com/cypress-io/cypress/issues/18778#issuecomment-974410343) this ticket is a duplicate of #5016 .  Please follow that ticket for any updates on this issue.
