### ISSUE TITLE
Cypress opens several Chrome tabs

### ISSUE THREAD

**Issue by warpdesign** [cypress-io/cypress#8913] opened 2020-10-21 16:53 UTC
### Current behavior

Whenever I start some tests by clicking on a file name in the Cypress window, a new Chrome window is opened, but several tabs are opened (which seem to be related to the previous tests I opened).

Now if I close the Chrome window by clicking on the `x Stop` button in the Cypress window, if I try to run the same tests by clicking on the spec file, it will open Chrome, with another extra tab. And so on...

### Desired behavior

Chrome should open a single tab.

I tried to disable the option to re-open tabs when starting the browser but it doesn't seem to be available since the browser is controlled by Cypress.

### Test code to reproduce

I was able to reproduce it with the test repo of cypress.

In the video below, a lot of tabs are already opened, and as you can see, everytime I start the tests, a new tab is added.

![chrome-tabs](https://user-images.githubusercontent.com/199648/96752241-7c07aa80-13ce-11eb-91cd-253d6a0b410d.gif)

I tried to run `cypress cache clear` but it doesn't appear to fix the problem.

### Versions
- Cypress: 5.4.0 (happened with 5.3.0 too)
- Chrome 86
- macOS 10.15.6

**Comment by jennifer-shehane** [comment] 2020-10-22 07:27
Could you try following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data?

Does this occur everytime you open Cypress - like, freshly run `cypress open`? Or does the issue go away after killing Cypress and rerunning `cypress open`?

**Comment by warpdesign** [comment] 2020-10-22 08:47
I followed the instructions and after closing/restarting Cypress, the problem is gone: only one tab is opened.

But I now know how to reproduce it:

1. click on a spec file (a new Chrome window with a single tab is opened)
2. close the Chrome window by clicking on the up left close button
3. click on `x Stop` in the Cypress window
4. click on a spec file: **two tabs** will be opened (one with the preview spec file, one with the new spec file I clicked on)

From this point, clicking on `x Stop` and clicking on a spec file will open Chrome with an additional tab every time a spec file is clicked on.

**Comment by warpdesign** [comment] 2020-10-22 08:50
Hmm.. Actually, there is no need to close the Chrome Window. Here is what I did:

1. clear the app data as suggested
2. open cypress
3. click on a spec file (a Chrome window with a **single** tab is opened)
4. click on `x Stop` in the Cypress window
5. click on another spec file: a Chrome window with *two tabs** is opened

**Comment by jennifer-shehane** [comment] 2021-02-22 16:15
I'm just not able to reproduce this with the instructions provided. It may be specific to the test code you are running somehow. 

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-22 16:15 UTC
Labels: stage: needs information, type: unexpected behavior

**Comment by iepoch** [comment] 2021-08-24 12:45
While I know this is closed it may need to also be looked at again. Also could be because of Sessions that has newly showed as experimental. I have the same issue with multiple browsers being opened after you click on a tab in the Cypress window. If you create a New Tab and then go back to the Cypress runner and click on a Feature or Spec file it will run in a new tab there after. And no matter how many times you click on that Spec or Feature file it will always create a new tab. 
At least that was my setup and seems to be on My Mac. I haven't tried it on a Windows Computer. But there is something there just not 100% sure what it causing it. But I also noticed a issue where the Cypress window itself becomes like a new rendered Tab. And because of this it fails my test because of a Session Storage issue. But I realized that some how Cypress on every run seems to be a new Tab. But the other tabs aren't showing until you do the click on a new tab and then each run after becomes its own tab.

Again Mac only so far not seeing the same issue in windows but I haven't tried this Scenario.

**Comment by nattius1983** [comment] 2021-09-02 19:04
I'm having the exact same issue on a mac OS Catalina 10.15.7 - same steps as @warpdesign posted last year. Please investigate 🙏

**Comment by nattius1983** [comment] 2021-09-06 12:27
> I'm just not able to reproduce this with the instructions provided. It may be specific to the test code you are running somehow.
> 
> Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Hi! What further info do you need to reopen this please? I've completed the steps you mentioned and this only temporarily resolves the issue until I run the next test? Are you on a Mac trying to recreate this at all? Should I open a new issue please?

**Comment by markl-canva** [comment] 2022-09-23 15:42
I'm also experiencing this infuriating problem. In order to avoid multiple tabs opening, I have to ⌘-w each tab in the Cypress-controlled Chrome, and then click "Stop" in the spec explorer window, otherwise the next time I run the tests those tabs will be restored and the tests will start running in all of the tabs.

I wonder if the people who can't reproduce this problem using [these steps](https://github.com/cypress-io/cypress/issues/8913#issuecomment-714336508), could post what the "On start-up" preferences of the Cypress-controlled Chrome is set to? For comparison, for me, who does have this problem, that looks like:

<img width="788" alt="Screenshot 2022-09-23 at 16 32 50" src="https://user-images.githubusercontent.com/89554036/191998281-f2da54d9-ca6d-4d36-aabd-c3487d8e5187.png">

I'm seeing this behaviour with
* both Cypress 9.7.0 and 10.5.0, 
* Chrome 105.0.5195.125 (Official Build) (x86_64)
* macOS 12.6
