### ISSUE TITLE
Test hangs forever on retry

### ISSUE THREAD

**Issue by julianmendonca** [cypress-io/cypress#9393] opened 2020-12-01 15:38 UTC
### Current behavior

When a test fails the retry hangs and never continues.
I read in this issue https://github.com/cypress-io/cypress/issues/8363 that "what reproduces the bug is having a test that fails and retries with an existent DOM node as the subject of an assertion" but it was supposed to be fixed in v 5.2.0.
The error doesent happen in any specific moment, just happens sometimes when a test failes (Almost every time i do cypress run --browser chrome this appear in some test). I tried with cypress run and cypress run --browser chrome and its the same in both.

![image](https://user-images.githubusercontent.com/31936866/100772584-8ca03d00-33de-11eb-8d3f-227432f6d0d8.png)
Sometimes shows this and sometimes the retry passes and its green but hangs either way.

### Desired behavior

Be able to use retries without hanging forever

### Test code to reproduce

https://github.com/julianmendonca/cypressError
run: **npm run scripts**
In my tests i dont run anything locally, just test already existent web pages. (I work with a lot of iframes).

### Versions

windows 10 and cypress 6.0.1

Thank you in advance for your support :)

**Comment by bahmutov** [comment] 2020-12-02 14:07
Running locally, with `cypress open` have noticed a bunch of errors in the DevTools

<img width="1277" alt="Screen Shot 2020-12-02 at 8 46 41 AM" src="https://user-images.githubusercontent.com/2212006/100882905-b492ad80-347d-11eb-83d5-035ee5a29a64.png">

also see that ServiceWorker is trying to load

**Comment by bahmutov** [comment] 2020-12-02 14:21
Errors in the site happen in any browser

<img width="1440" alt="Screen Shot 2020-12-02 at 9 20 30 AM" src="https://user-images.githubusercontent.com/2212006/100884702-c7a67d00-347f-11eb-94f5-f5803ac3f73e.png">

**Comment by bahmutov** [comment] 2020-12-02 14:33
I have added https://github.com/bahmutov/cypress-repeat to try to get this error to appear - but the `cypress/integration/testArredoUy.js` still fails in this test (but not hanging)

```js
it("Aparece caja de registro", () => {
  cy.visit("https://www.arredo.com.uy/");
  cy.wait(10000);
  cy.get("#braindw_register");
});
```

<img width="1279" alt="Screen Shot 2020-12-02 at 9 25 10 AM" src="https://user-images.githubusercontent.com/2212006/100885885-26202b00-3481-11eb-9ac9-8266afcad4c4.png">

I am not sure when the popup is supposed to be shown. Very rarely it is present and the test passes

<img width="1281" alt="Screen Shot 2020-12-02 at 9 23 25 AM" src="https://user-images.githubusercontent.com/2212006/100885928-30dac000-3481-11eb-9ce1-fd092c87d95c.png">

## Notes and advice

- Instead of hardcoding the URL in every test, put it as the base URL in the suite (since every spec tests its own)
- instead if using `cy.wait` just increase the timeout on the `cy.get` command

```js
context("Arredo Uy", { baseUrl: "https://www.arredo.com.uy/" }, () => {
  it("Aparece caja de registro", () => {
    cy.visit("/");
    cy.get("#braindw_register", {timeout: 10000});
  });
})
```

**Comment by bahmutov** [comment] 2020-12-02 14:54
What I think is really suspicious here is the "No commands were issues in this test" message on "Attempt 2". It almost seems like something went wrong and the test did not load or run in retry, and thus got into hanging phase and could never finish.

**Comment by bahmutov** [comment] 2020-12-02 15:49
I have been stress-testing retries and the entire run with much simpler tests in https://github.com/cypress-io/cypress-repeat-retry and could not recreate a hanging test. Seems there is something about either the test commands or the support file not loading causing "No commands found ..." message and the test hanging.

**Comment by julianmendonca** [comment] 2020-12-04 12:13
> I have added https://github.com/bahmutov/cypress-repeat to try to get this error to appear - but the `cypress/integration/testArredoUy.js` still fails in this test (but not hanging)
> 
> ```js
> it("Aparece caja de registro", () => {
>   cy.visit("https://www.arredo.com.uy/");
>   cy.wait(10000);
>   cy.get("#braindw_register");
> });
> ```
> 
> <img alt="Screen Shot 2020-12-02 at 9 25 10 AM" width="1279" src="https://user-images.githubusercontent.com/2212006/100885885-26202b00-3481-11eb-9ac9-8266afcad4c4.png">
> 
> I am not sure when the popup is supposed to be shown. Very rarely it is present and the test passes
> 
> <img alt="Screen Shot 2020-12-02 at 9 23 25 AM" width="1281" src="https://user-images.githubusercontent.com/2212006/100885928-30dac000-3481-11eb-9ce1-fd092c87d95c.png">
> 
> ## Notes and advice
> * Instead of hardcoding the URL in every test, put it as the base URL in the suite (since every spec tests its own)
> * instead if using `cy.wait` just increase the timeout on the `cy.get` command
> 
> ```js
> context("Arredo Uy", { baseUrl: "https://www.arredo.com.uy/" }, () => {
>   it("Aparece caja de registro", () => {
>     cy.visit("/");
>     cy.get("#braindw_register", {timeout: 10000});
>   });
> })
> ```
> 
> Since we see service worker errors, and the service workers can disrupt normal Cypress visits, I suggest you try [disabling ServiceWorker in Cypress test](https://glebbahmutov.com/blog/cypress-tips-and-tricks/#disable-serviceworker)
> 
> ```js
> cy.visit("/", {
>   onBeforeLoad (win) {
>     delete win.navigator.__proto__.serviceWorker
>   }
> });
> cy.get("#braindw_register", {timeout: 10000});
> ```
> 
> Do not forget to clean the application's data
> 
> <img alt="Screen Shot 2020-12-02 at 9 37 05 AM" width="1280" src="https://user-images.githubusercontent.com/2212006/100886566-fe7d9280-3481-11eb-8c4d-90fe9af38baa.png">
> 
> I have noticed that the popup appears after clicking "Clean application's data" and running the test for the first time. After that it no longer appears - so I suspect it is controlled by something preserved. @julianmendonca do you know how this popup is controlled?

@bahmutov  Sorry for the late response, thank you for all the advice!!
We inject code in already existent website so they all have errors that i can't fix, and a lot of content that i test have to do with cookies and local storage. The register box not appearing is really not a problem, but what was driving me crazy was that every time i do cypress run at least one test hangs forever. either with "No commands found" or beause the previous attempt failed and the current hangs forever  even if it passes.
When you do cypres run or npm run scripts you dont get the test hanging?

**Comment by julianmendonca** [comment] 2020-12-04 17:23
I actually downgraded to version 4 and use the cypress-retry-plugin from npm and it never hangs. But i dont get why in version 6.0.1 it hangs in some tests.
The 2 situation that i see is the no commands found and the other one is the test fails, it retries and it passes (meaning it is in green) but never continue to next test...
When you ran all the test it never got hanging?

**Comment by bahmutov** [comment] 2020-12-04 17:40
I have never seen in hanging, but I do see it failing a lot. Do you ever have it hanging during `cypress open`?

**Comment by julianmendonca** [comment] 2020-12-04 17:42
@bahmutov mmm not  with cypress open, but i have the test in a cron job running 24/7 and it hangs every 1 or 2 runs, did you try using "npm run scripts"?

**Comment by bahmutov** [comment] 2020-12-04 18:10
So to run you did `npm test` and Chrome pops up and you see it hanging and then you took the screenshot and saw "No commands ..."?

I have set it up to run multiple times on GitHub Actions https://github.com/bahmutov/cypressError/actions so let's see. I will also run it on repeat locally, maybe then it starts hanging

**Comment by julianmendonca** [comment] 2020-12-04 18:33
@bahmutov I dont see it in a screenshot (i have it disabled), i have the test running in an aws computer running 24/7 so i enter there and i see the chrome tab opened hanged in the test.
Sorry for not providing you the full code with the crone job but it have sensitive information, thank you for building it and running it!! :)

**Comment by bahmutov** [comment] 2020-12-04 19:55
Hmm, I have ran the thing 15 times in a row, the tests are failing, the retries are applied, but no luck getting it to hang using `cypress open` locally. Plus it finished on CI too without hanging https://github.com/bahmutov/cypressError/actions Very hard to reproduce this issue.

**Comment by julianmendonca** [comment] 2020-12-04 19:58
@bahmutov ohh ok, well i will work on another repo and test it on another computer too, so i make sure it reproduces the test so you can have a better look at it.
Thank you so much for the help! :)

**Comment by bahmutov** [comment] 2020-12-04 20:06
yeah, also I had a question for you - why do you have waits there. I have modified the tests a little bit to get rid of them here https://github.com/bahmutov/cypressError/blob/master/cypress/integration/testArredoUy.js

**Comment by julianmendonca** [comment] 2020-12-04 21:11
@bahmutov oh thank you! I use waits cause the things  I want to test are html appended after a a request to an API, so i add the wait to give some time for the request to load. I tried to used Intercept for wait to the request but i couldn't make it work, i dont know how to wait for an api only including the first part.
Something like:

cy.intercept({
  pathname: 'https://a.myapi.com/api/script/*',
  query: {
    q: 'some terms'
  }
}).as('searchForTerms')
// this 'cy.wait' will only resolve once a request is made to '/search'
// with the query paramater 'q=some+terms'
cy.wait('@searchForTerms')

Is this code right? Or how is it  supposed to be?

**Comment by jennifer-shehane** [comment] 2020-12-16 05:39
I thought this may be a duplicate of https://github.com/cypress-io/cypress/issues/9040, although it's kind of difficult to be sure since the example is very large.

After removing the abitrary cy.waits and the reporter so that retries are shown in stdout, I haven't been able to reproduce a hanging during `cypress run`. The tests take a long time to run, but it is the same amount of time as `cypress open`.

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-12-16 05:39 UTC
Labels: stage: investigating

**Comment by trprincebautista** [comment] 2022-04-21 03:19
I'm having the same problem... test hangs and won't continue to the next step.
![image](https://user-images.githubusercontent.com/93892014/164365201-f9a794ac-1849-4517-9176-0538abe313c6.png)
