### ISSUE TITLE
Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x.

### ISSUE THREAD

**Issue by webestet** [cypress-io/cypress#6804] opened 2020-03-22 18:07 UTC
I try to install cypress next command from documentation:
`yarn add cypress --dev`

I see error:
```
cypress > extract-zip > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```
But I don't have mkdirp in my dependency

Node: v10.19.0
Npm: v6.13.4
Yarn: 1.21.1

**Comment by jennifer-shehane** [comment] 2020-03-23 10:00
This is one of our deps. Basically a duplicate of https://github.com/cypress-io/cypress/issues/6730

**Closed by jennifer-shehane** 2020-03-23 10:00 UTC
Labels: process: dependencies
