### ISSUE TITLE
Cypress programmatically generate template structure

### ISSUE THREAD

**Issue by grantspeelman** [cypress-io/cypress#1929] opened 2018-06-11 23:33 UTC
### Current behaviour:
Currently, cypress only generates the initial folder structure and files on running cypress open for the first time. 

<img width="548" alt="screen shot 2018-06-12 at 9 12 00 am" src="https://user-images.githubusercontent.com/98919/41261888-2c99fce6-6e21-11e8-94d9-42f5e42a9c61.png">

### Desired behaviour:
Be able to generate the initial folder structure programmatically with something like:
```
cypress init -P test
```

### Motivation
This will allow other projects and libraries to wrap the initial setup process with additional setup steps and files as required.

### Versions
Future Cypress versions

**Comment by brian-mann** [comment] 2018-06-11 23:43
Did @bahmutov tell you to open this issue :P

He's been lobbying for this for a year now

**Comment by grantspeelman** [comment] 2018-06-11 23:53
No he has not 😄 
I am building a ruby gem (library) called [cypress_dev](https://github.com/grantspeelman/cypress_dev) that integrates with ruby on rails.
Part of what it does it attempt to get you setup easily with an initial cypress setup.
Currently I have a copy of the cypress 2.1 initial template copied into the gem but it would be great if this can easily be kept inline with the Cypress.

**Comment by bahmutov** [comment] 2018-06-12 00:10
:) thank you Grant for keeping our secret ! I was thinking of doing my own utility for scaffolding cypresss projects I. Different ways but including them (really just exposing) in Cypress would be so much better

**Comment by jennifer-shehane** [comment] 2021-03-31 17:55
Duplicate of https://github.com/cypress-io/cypress/issues/619

**Closed by jennifer-shehane** 2021-03-31 17:55 UTC
Labels: cli, type: feature
