### ISSUE TITLE
Feature Request - Support directly testing Electron apps

### ISSUE THREAD

**Issue by timfish** [cypress-io/cypress#2072] opened 2018-06-30 22:18 UTC
It would be great to be able to use Cypress to do full e2e testing of Electron apps. 

We currently use [Spectron](http://electronjs.org/spectron) but it uses webdriver so it is obviously rather unreliable and also requires updated Chromedriver for every new version of Electron.

**Comment by hunterlong** [comment] 2018-07-02 17:24
+1

**Comment by jennifer-shehane** [comment] 2018-07-12 20:23
@timfish Hey, just wanted to make sure you saw this FAQ. I know it's not, "testing an Electron app out of the box", but wanted to mention it here. https://on.cypress.io/using-cypress-faq#Can-I-test-my-Electron-app

**Comment by burtonator** [comment] 2018-09-05 15:07
Would be great if there was more documentation for this or an example app.  Spectron is definitely lacking and not very fun to work with.

**Comment by timfish** [comment] 2018-09-05 19:49
I have looked at the Cypress desktop app that uses Cypress to test the app UI in a browser, but we currently use Spectron to do a lot more than just UI interactions. 

As well as testing the UI, our integration test suite runs against packaged productions builds and checks interactions with the OS which just wouldn't work in a browser. We check that various state is persisted correctly between app restarts, file watching works as expected and a load of other things like that.

These tests drastically reduce the risk when upgrading Electron or other dependencies so moving to UI only tests would feel like a big step down.

**Comment by squiles** [comment] 2019-07-07 10:11
Any news on this?

**Comment by gtamas** [comment] 2019-07-09 14:59
@jennifer-shehane  
This would actually an important feature. There are many electron apps out there. 
Would it be possible to publish at least a tutorial on how to do this? Some info / help would be appreciated.

**Comment by jennifer-shehane** [comment] 2019-08-14 08:36
Hi everyone, we've begun work on supporting running tests directly in an Electron application. 

We often create new issues to track the progress of the more technical work involved while implementing, so if you want to follow the details of that - you can follow the issue here: https://github.com/cypress-io/cypress/issues/4964

Otherwise, just continue to follow this issue. It will be closed and updated whenever the feature is ready for release.

**Comment by eoinom** [comment] 2020-02-20 00:27
> Hi everyone, we've begun work on supporting running tests directly in an Electron application.
> 
> We often create new issues to track the progress of the more technical work involved while implementing, so if you want to follow the details of that - you can follow the issue here: #4964
> 
> Otherwise, just continue to follow this issue. It will be closed and updated whenever the feature is ready for release.

Hi @jennifer-shehane, 

Will this also work for CEF applications or is there a separate issue / plans for that integration?

Thanks,
Eoin.

**Comment by jennifer-shehane** [comment] 2020-12-09 08:42
I'm going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/4964. We've noted all of the comments from this issue. It won't be lost. 

This issue will be closed to further comment. Please refer to https://github.com/cypress-io/cypress/issues/4964 for any comments on wanting Electron app testing support.

**Closed by jennifer-shehane** 2020-12-09 08:42 UTC
Labels: browser: electron, stage: proposal 💡, type: feature
