### ISSUE TITLE
stuck when installing cypress

### ISSUE THREAD

**Issue by geraldos** [cypress-io/cypress#25657] opened 2023-02-01 10:04 UTC
### Current behavior

<img width="322" alt="image" src="https://user-images.githubusercontent.com/22190480/216011592-7323bb59-28ce-4bb5-8590-9a94ba8ea1bb.png">

when I'm install a cypress, stuck in installing untill many hours, I'll try many to fix them but always fail, maybe I'm have wrong config in my mac m1, please help to fix this problem

### Cypress Version

12.5.0

### Node version

14.20.0

### Package Manager

npm

### Package Manager Version

6.14.17

### Operating system

Mac

### Operating System Version

Ventura 13.2

**Comment by nagash77** [comment] 2023-02-01 18:10
Hi @geraldos I'm sorry you are having issues installing Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to install and use Cypress.  Discord will likely be your fastest way to find help so I urge you to check there.

**Closed as completed** 2023-02-01 18:47 UTC
Labels: topic: installation

**Comment by kartiktvv** [comment] 2023-02-06 23:36
I'm seeing exact same issue on an M1 chip Mac too. I haven't seen this happen on Intel Mac

**Comment by geraldos** [comment] 2023-02-07 02:10
> I'm seeing exact same issue on an M1 chip Mac too. I haven't seen this happen on Intel Mac

any solution for issue on a M1 chip??

**Comment by kartiktvv** [comment] 2023-02-07 03:09
I probably will have to go back to the older version as mentioned here: https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/
let me know if you find a resolution for the latest Cypress versions.

**Comment by kartiktvv** [comment] 2023-02-07 22:20
@nagash77 Could you please reopen and investigate this issue? Below is the max info I can provide you regarding reproducibility:
1. M1 chip with Monterey macOS
2. Node version v16.17.1
3. Run npm install cypress --save-dev
4. Run npx cypress install (pretty stops executing at this step, just like the screeshot @geraldos mentioned)
TIA

**Comment by mschile** [comment] 2023-02-07 23:05
@kartiktvv and @geraldos, I was unable to reproduce your issue. I am able to successfully download/install Cypress on my M1 mac.

1. macOS Monterey 12.6, Apple M1 Max chip
2. Node version 16.17.1
3. Ran `npm install cypress --save-dev`
4. Ran `npx cypress open` successfully

You could try clearing your Cypress cache. `npx cypress cache clear`.

Do the debug logs show anything? `DEBUG=cypress:* npx cypress install`?

Are you able to download the [binary directly](https://docs.cypress.io/guides/getting-started/installing-cypress#Direct-download)?

**Comment by mschile** [comment] 2023-02-07 23:11
If you are behind a corporate proxy, you will also need to configure that: https://docs.cypress.io/guides/references/proxy-configuration

**Comment by kartiktvv** [comment] 2023-02-07 23:51
> @kartiktvv and @geraldos, I was unable to reproduce your issue. I am able to successfully download/install Cypress on my M1 mac.
> 
> 1. macOS Monterey 12.6, Apple M1 Max chip
> 2. Node version 16.17.1
> 3. Ran `npm install cypress --save-dev`
> 4. Ran `npx cypress open` successfully
> 
> You could try clearing your Cypress cache. `npx cypress cache clear`.
> 
> Do the debug logs show anything? `DEBUG=cypress:* npx cypress install`?
> 
> Are you able to download the [binary directly](https://docs.cypress.io/guides/getting-started/installing-cypress#Direct-download)?

@mschile Debug logs show nothing. I was able to download the binary directly. going the npm route is being weird. I haven't setup the proxy. Let me try that and get back.
