### ISSUE TITLE
Improve failure accounting

### ISSUE THREAD

**Issue by nickpalmer** [cypress-io/cypress#14895] opened 2021-02-03 18:35 UTC
### What would you like?
If a "before" block fails cypress correctly cancels the tests associated with that before. However, it does not account for those failures properly. It shows a single failure in the dashboard and shows all the dependent tests as "pending" even though they were canceled.

### Why is this needed?
It would be nice if the canceled tests showed as failures instead of being accounted as "pending". This could be by adding a "Canceled" bucket to indicate they were canceled, or adding them to failures, but they are clearly not "pending".

This is an example run, which is finished, and had a failure in a `before` block which caused a cancel of the 25 tests associated with the before block:

![Screen Shot 2021-02-03 at 12 42 07 PM](https://user-images.githubusercontent.com/224670/106793572-3d180080-661d-11eb-8f3f-28bbe7c93526.png)

**Comment by nickpalmer** [comment] 2021-02-03 19:05
Related to https://github.com/cypress-io/cypress/issues/3092

**Comment by jennifer-shehane** [comment] 2021-02-04 05:13
Duplicate of #3092 

Please feel free to put your input in that issue which encompasses the 'skipping' of tests when hooks fail.

**Closed by jennifer-shehane** 2021-02-04 05:13 UTC
