### ISSUE TITLE
getting leave site pop up while using realClick() method from cypress-real-events plugin

### ISSUE THREAD

**Issue by satya081** [cypress-io/cypress#29462] opened 2024-05-02 13:27 UTC
### Current behavior

leave site pop up is showing(screenshot below) when i am using realClick() method from cypress-real-events plugin

![image](https://github.com/cypress-io/cypress/assets/32022027/306bccea-ecd1-45b6-b3b7-db1af58c17ac)

### Desired behavior

leave site pop up should not displayed

### Test code to reproduce

cy.get('#id').realClick();

### Cypress Version

13.7.2

### Node version

20.12.0

### Operating System

Windows

**Comment by jennifer-shehane** [comment] 2024-05-02 17:16
Duplicate of https://github.com/cypress-io/cypress/issues/28553

**Closed as not planned by jennifer-shehane** 2024-05-02 17:16 UTC
Labels: type: duplicate
