### ISSUE TITLE
cy.stub and cy.spy called withArgs creates two stubs/spies

### ISSUE THREAD

**Issue by meestergao** [cypress-io/cypress#8056] opened 2020-07-21 17:59 UTC
### Current behavior:
When calling `cy.stub` or `cy.spy` with `withArgs` defined, two stubs or spies are created. One of them will disregard `withArgs` and catches everything. 

I'm trying to stub fetch requests with "experimentalFetchPolyfill" and when trying to specify a certain request to stub, this bugged stub is catching all of my fetch requests.
![Screen Shot 2020-07-20 at 11 54 21 AM](https://user-images.githubusercontent.com/38012019/88089392-c021af80-cb40-11ea-800f-4a064849fc2e.png)

### Desired behavior:
When defining a stub/spy `withArgs` I would expect it to catch only the request with the arguments

### Test code to reproduce
https://github.com/meestergao/cypress-test-tiny/blob/master/cypress/integration/spec.js

You can see that 2 stubs are created 1 and 1.1

### Versions
4.11.0

**Comment by jennifer-shehane** [comment] 2020-07-22 07:31
I can recreate this with the following, without the `experimentalFetchPolyfill`:

`spec.js`

```js
it('stubs 2 calls', () => {
  cy.window().then((win) => {
    cy.stub(win, 'fetch')
      .withArgs('test')
  })
})
```

<img width="566" alt="Screen Shot 2020-07-22 at 1 45 42 PM" src="https://user-images.githubusercontent.com/1271364/88146323-b91e9e00-cc21-11ea-88ae-a4d6d4fe9b41.png">


This seems to be the expected behavior. The `1.1` is intentional - to indicate it's part of the first stub. https://on.cypress.io/stubs-spies-and-clocks#Integration-and-Extensions

>When stubs are created by calling the method .withArgs(...) we also visually link these together.

Here's an example of stubbing an object (outside of the `fetch`). There are 2 stubs - 1 withArgs and 1 without created when you use stub `withArgs`.

```js
it('stubs plain obj', () => {
  const obj = {
    foo (arg) { 
      return arg || 'bar'
    }
  }

  const stubAnyArgs = cy.stub(obj, 'foo')
  const stubWithArgs = stubAnyArgs.withArgs('test')

  obj.foo()
  expect(stubAnyArgs).to.be.called
  expect(stubWithArgs).to.not.be.called

  obj.foo('test')
  expect(stubAnyArgs).to.be.called
  expect(stubWithArgs).to.be.called
})
```

<img width="566" alt="Screen Shot 2020-07-22 at 1 58 28 PM" src="https://user-images.githubusercontent.com/1271364/88147593-71991180-cc23-11ea-8ae6-2e198fa07661.png">

You can then match the calls, based on if you want to check that the stub was called `withArgs` or not. The example above correctly shows the `withArgs` called when the proper args are passed. 

---

We would need a fuller example to demonstrate that there is a situation where `win.fetch` is called with the args you're hoping to stub on - and Cypress not matching that stubbed call when it has those exact args. Can you provide a full failing example?

**Comment by jennifer-shehane** [comment] 2021-02-26 23:55
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-26 23:55 UTC
Labels: stage: needs information

**Comment by monktana** [comment] 2024-07-16 16:30
Hello, i have come across this issue on my google search to solve an issue i currently have with stubbing the matchMedia function.

I'm have a test case to ensure that my color mode toggle works the way i expect it to. Therefore, i want to (pre)set the dark mode in the test following this blogpost: [https://www.cypress.io/blog/2019/12/13/test-your-web-app-in-dark-mode](https://www.cypress.io/blog/2019/12/13/test-your-web-app-in-dark-mode)

```typescript
cy.visit('/', {
  onBeforeLoad(win: Cypress.AUTWindow) {
    cy.stub(win, 'matchMedia')
      .withArgs('(prefers-color-scheme: dark)')
      .returns({
        matches: true,
        addListener: () => {},
      });
  },
});
```

When executing the test, i get this error message:

![image](https://github.com/user-attachments/assets/a117c6c1-5752-4f28-9598-9c6d2015713f)

Can someone tell me why this fails? Do i need to manually create another stub for no arguments (or the 'prefers-reduced-motion')?

What is the return of the automatically created stub?

Thanks in advance :)
