### ISSUE TITLE
In cypress 10.11 I can't visit my web page

### ISSUE THREAD

**Issue by NikitaSheff** [cypress-io/cypress#24269] opened 2022-10-15 15:57 UTC
### Current behavior
Browser - electron
https://ant.bc-servers.me/ this is my site
On version 10.9 I'm able to visit this site => cy.visit('https://ant.bc-servers.me/')
On version 10.10 I'm not able to visit it - just empty screen and no error occurs

### Desired behavior

I want to continue testing my web application on the newest version of cypress

### Test code to reproduce

`cy.visit('https://ant.bc-servers.me/')`

### Cypress Version

10.10

### Node version

18.10

### Operating System

Win11x64

### Debug Logs

```shell
empty
```

**Comment by reify-yirgu-bira** [comment] 2022-10-15 16:31
Same here

**Comment by baubie** [comment] 2022-10-15 21:01
Same issue here.

**Comment by ezekel** [comment] 2022-10-16 12:35
Same issue I'm using image cypress/included:10.10.0

cannot see my virtual domain http://myapp.local

```
We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

```

**Comment by tit** [comment] 2022-10-17 09:11
Hm... I have Cypress 10.10 and does not have same problem.
![image](https://user-images.githubusercontent.com/278604/196137863-1533fa42-a67b-47e5-883d-7d00195ddc47.png)

But, you page has JS exception.
See DevTools => Console.

**Comment by NikitaSheff** [comment] 2022-10-17 09:18
@tit I use electron browser

JS exception is known, thanks

**Comment by tit** [comment] 2022-10-17 09:25
@NikitaSheff In Electron browser I have not this problem too (except some errors in console).

![image](https://user-images.githubusercontent.com/278604/196141204-fb2f3f8b-1222-4169-b911-a6bd68587bae.png)

**Comment by NikitaSheff** [comment] 2022-10-17 12:07
![image](https://user-images.githubusercontent.com/99482593/196173066-985c308f-7586-420b-8293-5d84379a3a3f.png)

**Comment by tit** [comment] 2022-10-17 13:44
@NikitaSheff The screenshot shows that the command .visit has not finished its work yet. After the expiration of the timeout, it should end in any case with some error. Try to wait for the team to finish working. Also, make sure that the site you are opening opens simply in the next tab manually. That there are no problems with the network.

**Comment by NikitaSheff** [comment] 2022-10-17 13:55
![image](https://user-images.githubusercontent.com/99482593/196195257-31c1acb9-dc08-42c4-8762-191342996f10.png)
This is what I see after the test is over

The site opens fine in any browser.

**Comment by vivshaw** [comment] 2022-10-17 18:09
[This same failure](https://github.com/cypress-io/cypress/issues/24269#issuecomment-1280902466) randomly started happening to us too last Friday. I don't have a minimal repro. But I do know it appeared to start happening around the time that CircleCI bumped the Chrome version in CI, and we made no changes to Cypress tests nor any version bumps at the time it happened.

**Comment by AtofStryker** [comment] 2022-10-18 17:09
Hi @NikitaSheff . Thank you for opening an issue. I put your test case inside this [reproduction repository](https://github.com/AtofStryker/cypress-issue-24269) and ran with both MacOS and Windows 10 with Chrome 106 and Node 18.11.0. Unfortunately I wasn't able to reproduce the issue. Are you on a corporate managed device or have you tried running the process as administrator?

**Comment by mschile** [comment] 2022-10-26 17:47
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by NikitaSheff** [comment] 2022-10-27 07:53
Some new information, on cypress 10.11 in electron browser I still can't visit my site page, but in chrome browser I'm able to do it.

**Comment by nagash77** [comment] 2022-10-27 18:22
@NikitaSheff Can you help us reproduce this by folloing @AtofStryker 's instructions [here](https://github.com/cypress-io/cypress/issues/24269#issuecomment-1282739551)

**Comment by NikitaSheff** [comment] 2022-10-27 19:32
@nagash77 Hi! I work on my own PC and I have tried to run cypress as administrator - but the issue is still reproduceable
 
![image](https://user-images.githubusercontent.com/99482593/198381716-dbebb43a-f7c2-413a-81d2-bfbfc01763ec.png)
Thanks!

**Comment by mschile** [comment] 2022-10-27 23:05
@NikitaSheff, could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

If you run @AtofStryker's [reproduction repository](https://github.com/AtofStryker/cypress-issue-24269) does it also fail for you? He was running MacOS and Windows 10 with Chrome 106 and Node 18.11.0.

**Comment by NikitaSheff** [comment] 2022-10-28 07:48
Here is my logs :

[logs.txt](https://github.com/cypress-io/cypress/files/9886366/logs.txt)

@mschile Yes, I run @AtofStryker repository on win11

**Comment by ezekel** [comment] 2022-10-29 10:23
still same  cypress/included:10.11.0

cannot visit to virtual domain

```
Running:  spec.cy.js                                                                      (1 of 1)


  1) loads page

  0 passing (8s)
  1 failing

  1) loads page:
     CypressError: `cy.visit()` failed trying to load:

http://myapp.local/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:80

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
      at <unknown> (http://web/__cypress/runner/cypress_runner.js:142341:82)
      at visitFailedByErr (http://web/__cypress/runner/cypress_runner.js:141629:12)
      at <unknown> (http://web/__cypress/runner/cypress_runner.js:142340:11)
      at tryCatcher (http://web/__cypress/runner/cypress_runner.js:11318:23)
      at Promise._settlePromiseFromHandler (http://web/__cypress/runner/cypress_runner.js:9253:31)
      at Promise._settlePromise (http://web/__cypress/runner/cypress_runner.js:9310:18)
      at Promise._settlePromise0 (http://web/__cypress/runner/cypress_runner.js:9355:10)
      at Promise._settlePromises (http://web/__cypress/runner/cypress_runner.js:9431:18)
      at _drainQueueStep (http://web/__cypress/runner/cypress_runner.js:6025:12)
      at _drainQueue (http://web/__cypress/runner/cypress_runner.js:6018:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://web/__cypress/runner/cypress_runner.js:6034:5)
      at Async.drainQueues (http://web/__cypress/runner/cypress_runner.js:5904:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/spec.cy.js:2:7)
  
  From Node.js Internals:
    Error: connect ECONNREFUSED 127.0.0.1:80
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

**Comment by ezekel** [comment] 2022-10-29 10:50
But using host machine IP , it works fine
```
it('loads page', () => {
    cy.visit('http://192.168.1.2')

})
```

![image](https://user-images.githubusercontent.com/6830057/198827803-5b5f0331-7c92-4662-9c49-7e54a0a0248f.png)

**Comment by mschile** [comment] 2022-11-01 05:22
@NikitaSheff, thanks for the debug logs. Unfortunately, I didn't notice anything in the logs as being incorrect. You could try running the test with the [`cypress/included`](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) docker image.

`docker run -it -v ${PWD}:/test -w /test cypress/included:10.11.0`

**Comment by NikitaSheff** [comment] 2022-11-01 10:43
Interestingly, I'm not the only one having difficulty logging into the site..

**Comment by NikitaSheff** [comment] 2022-11-01 11:01
![image](https://user-images.githubusercontent.com/99482593/199219088-328aa1ba-fcd6-40a5-bb99-08fdabe059b4.png)

@mschile

**Comment by mschile** [comment] 2022-11-01 14:30
@NikitaSheff, are you running the command from the folder with your `cypress.config.js` file?

**Comment by NikitaSheff** [comment] 2022-11-01 18:27
@mschile Well, with this way it works!
![image](https://user-images.githubusercontent.com/99482593/199310045-dfbd21e2-965c-47a2-8170-6cb962162bcf.png)

**Comment by NikitaSheff** [comment] 2022-11-01 18:31
```
[28768:1101/212836.685:ERROR:CONSOLE(1)] "TypeError: Failed to fetch", source: devtools://devtools/bundled/entrypoints/main/main.js (1)
GET /__/ 200 8.667 ms - -
GET /__/assets/polyfills.f25d072f.js 200 7.009 ms - -
GET /__/assets/index.a470eacb.css 200 4.298 ms - -
GET /__/assets/index.60313f74.js 200 4.130 ms - -
GET /__cypress/runner/cypress_runner.css 200 4.614 ms - -
GET /__/assets/Specs.5d27fda4.js 200 12.368 ms - 485
GET /__/assets/Index.0c282094.css 200 10.667 ms - -
GET /__/assets/CreateSpecModal.685918fa.css 200 12.835 ms - 368
GET /__/assets/Index.51d6a0fc.js 200 11.506 ms - -
GET /__/assets/ResultCounts.120f706a.js 200 10.126 ms - -
GET /__/assets/CreateSpecModal.1b0c3f1c.js 200 13.182 ms - -
GET /__/assets/SpecPatterns.4e352bb0.js 200 15.325 ms - -
GET /__/assets/user-outline_x16.6f6586bc.js 200 13.410 ms - -
GET /__/assets/settings_x16.fd1371b1.js 200 10.673 ms - -
GET /__/assets/cypress_s.29af549a.png 200 5.253 ms - 4425
GET /__cypress/runner/cypress_runner.js 200 5.282 ms - -
GET /__/assets/chrome.98045c79.svg 200 9.521 ms - -
GET /__/assets/edge.e54a3dc2.svg 200 8.692 ms - -
GET /__/assets/electron.fb07f5cc.svg 200 11.703 ms - -
GET /__/assets/firefox.9be61e66.svg 200 11.005 ms - -
GET /__cypress/runner/popper.js.map 404 1.196 ms - 136
GET /avatar/c90262d95497c6845bc49070ed02762c?size=48&default=mm 200 452.621 ms - -
GET /__/assets/Runner.56cb4131.css 200 12.274 ms - -
GET /__/assets/Switch.8968e053.js 200 10.074 ms - -
GET /__/assets/refresh_x16.a27af9b6.js 200 8.991 ms - -
GET /__/assets/Runner.c0923bb9.js 200 22.335 ms - -
GET /__cypress/iframes/cypress%5Ce2e%5Cspec.cy.js 200 10.355 ms - 926
GET /__cypress/runner/popper.js.map 404 0.615 ms - 136
GET /__cypress/tests?p=cypress%5Ce2e%5Cspec.cy.js 200 1568.474 ms - -
GET /__cypress/tests?p=cypress%5Csupport%5Ce2e.js 200 1656.772 ms - -
GET /__/ 200 1.285 ms - -
GET /__/assets/polyfills.f25d072f.js 200 1.386 ms - -
GET /__/assets/index.a470eacb.css 200 1.597 ms - -
GET /__/assets/index.60313f74.js 200 1.911 ms - -
GET /__cypress/runner/cypress_runner.css 200 1.618 ms - -
GET /__/assets/Specs.5d27fda4.js 200 6.337 ms - 485
GET /__/assets/Runner.56cb4131.css 200 5.674 ms - -
GET /__/assets/CreateSpecModal.685918fa.css 200 9.373 ms - 368
GET /__/assets/Runner.c0923bb9.js 200 6.367 ms - -
GET /__/assets/CreateSpecModal.1b0c3f1c.js 200 4.556 ms - -
GET /__/assets/SpecPatterns.4e352bb0.js 200 7.875 ms - -
GET /__/assets/Switch.8968e053.js 200 8.043 ms - -
GET /__/assets/refresh_x16.a27af9b6.js 200 6.869 ms - -
GET /__cypress/runner/cypress_runner.js 200 3.406 ms - -
GET /__/assets/cypress_s.29af549a.png 200 1.821 ms - 4425
GET /__cypress/runner/popper.js.map 404 0.676 ms - 136
GET /__/assets/electron.fb07f5cc.svg 200 4.429 ms - -
GET /__/assets/chrome.98045c79.svg 200 4.028 ms - -
GET /__/assets/edge.e54a3dc2.svg 200 4.173 ms - -
GET /__/assets/firefox.9be61e66.svg 200 4.917 ms - -
GET /__cypress/iframes/cypress%5Ce2e%5Cspec.cy.js 200 1.664 ms - 930
GET /__cypress/runner/popper.js.map 404 0.932 ms - 136
GET /__cypress/tests?p=cypress%5Csupport%5Ce2e.js 200 4.186 ms - -
GET /__cypress/tests?p=cypress%5Ce2e%5Cspec.cy.js 200 4.473 ms - -
GET / 200 46.941 ms - -
GET /__/assets/cypress_s.29af549a.png 304 3.319 ms - -
GET /__/assets/electron.fb07f5cc.svg 304 3.873 ms - -
GET /__/assets/chrome.98045c79.svg 304 4.302 ms - -
GET /__/assets/edge.e54a3dc2.svg 304 4.505 ms - -
GET /__/assets/firefox.9be61e66.svg 304 4.922 ms - -
GET /avatar/c90262d95497c6845bc49070ed02762c?size=48&default=mm 200 629.780 ms - -
```

Nevertheless, this is what I see when I'm trying to visit my site in terminal

**Comment by mschile** [comment] 2022-11-02 20:57
@nikolalsvk, since you're able to successfully run the test using the docker image, there appears to be a difference with your specific system setup. Here are some details about the [docker image](https://github.com/cypress-io/cypress-docker-images/blob/master/included/10.11.0/Dockerfile#L8) that you used.

Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by ezekel** [comment] 2022-11-07 06:24
I tried, 

```
PS C:\web\myproject> docker run -it -v ${PWD}:/cypress -w /cypress cypress/included:10.11.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[204:1107/064926.066297:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

====================================================================================================
                                                                                                    
  (Run Starting)                                                                                    

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.11.0                                                                        │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v16.16.0 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (spec.cy.js)                                                           │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  spec.cy.js                                                                      (1 of 1)


  1) loads page

  0 passing (6s)
  1 failing

  1) loads page:
     CypressError: `cy.visit()` failed trying to load:

http://myapp.local

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:80

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
      at <unknown> (http://localhost:36067/__cypress/runner/cypress_runner.js:142341:82)
      at visitFailedByErr (http://localhost:36067/__cypress/runner/cypress_runner.js:141629:12)
      at <unknown> (http://localhost:36067/__cypress/runner/cypress_runner.js:142340:11)
      at tryCatcher (http://localhost:36067/__cypress/runner/cypress_runner.js:11318:23)
      at Promise._settlePromiseFromHandler (http://localhost:36067/__cypress/runner/cypress_runner.js:9253:31)
      at Promise._settlePromise (http://localhost:36067/__cypress/runner/cypress_runner.js:9310:18)
      at Promise._settlePromise0 (http://localhost:36067/__cypress/runner/cypress_runner.js:9355:10)
      at Promise._settlePromises (http://localhost:36067/__cypress/runner/cypress_runner.js:9431:18)
      at _drainQueueStep (http://localhost:36067/__cypress/runner/cypress_runner.js:6025:12)
      at _drainQueue (http://localhost:36067/__cypress/runner/cypress_runner.js:6018:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:36067/__cypress/runner/cypress_runner.js:6034:5)
      at Async.drainQueues (http://localhost:36067/__cypress/runner/cypress_runner.js:5904:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/spec.cy.js:2:7)

  From Node.js Internals:
    Error: connect ECONNREFUSED 127.0.0.1:80
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     spec.cy.js                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /cypress/cypress/screenshots/spec.cy.js/loads page (failed).png                      (1280x720)


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /cypress/cypress/videos/spec.cy.js.mp4                         (0 seconds)

====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  spec.cy.js                               00:06        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:06        1        -        1        -        -

```


```
it('loads page', () => {
    cy.visit('http://myapp.local')
    
})


```

**Comment by nagash77** [comment] 2022-11-07 13:26
@ezekel Unfortunately this does not provide us with any further information to help us track down this issue.  If you can provide a reproducible example please do share it here.  Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by NikitaSheff** [comment] 2022-11-08 13:49
ERR_FAILED (-2) loading 'https://ant.bc-servers.me/advertiser/'
Error: ERR_FAILED (-2) loading 'https://ant.bc-servers.me/advertiser/'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)


 I've also can see these logs in console

**Comment by mjhenkes** [comment] 2022-11-28 16:18
Closing this issue as not reproducible

**Closed as not planned** 2022-11-28 16:19 UTC
Labels: topic: visit
