### ISSUE TITLE
cy.wait timeouts on aborted xhr requests

### ISSUE THREAD

**Issue by mac2000** [cypress-io/cypress#9549] opened 2020-12-07 12:33 UTC
### Current behavior

Whenever there is something like this in app (pseudo code):

```js
var xhr = new XHR()
xhr.send()
xhr.abort() // <- POI
xhr = new XHR()
xhr.send()
```

and this in test:

```js
cy.intercept('...').as('xhr')
cy.visit('/')
cy.wait('@xhr')
```

cypress timeouts with  an error `Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: xhr. No response ever occurred.`

![image](https://user-images.githubusercontent.com/88868/101350868-68d66e80-3898-11eb-8e92-cc3229df5f5e.png)

As you can see on screenshot:

- in network tab there is aborted and follow up requests
- app renders response
- on a sidebar we can see that interception recognized the query (yellow marks)
- but somehow second requests still have spinning icon on left side

### Desired behavior

Page with app loads and works as expected, cypress should handle such cases as well

### Test code to reproduce

**index.html** - aka our app

```html
<!DOCTYPE html>
<html>
  <head>
    <title>demo</title>
  </head>
  <body>
    <button onclick="good()">good</button>
    <button onclick="bad()">bad</button>
    <script>
      function good() {
        const xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.responseType = "json";
        xhr.send();
        xhr.onload = () => {
          document.body.innerHTML += "<pre>" + JSON.stringify(xhr.response) + "</pre>";
        };
      }
      function bad() {
        let xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.responseType = "json";
        xhr.send();
        xhr.abort();
        xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.responseType = "json";
        xhr.send();
        xhr.onload = () => {
          document.body.innerHTML += "<pre>" + JSON.stringify(xhr.response) + "</pre>";
        };
      }
    </script>
  </body>
</html>
```

**demo.spec.js**

```js
describe("demo", () => {
  it("should handle aborted requests", () => {
    cy.intercept("https://jsonplaceholder.typicode.com/todos/1").as("xhr");
    cy.visit("http://localhost:3000");
    cy.get("button").contains("bad").click();
    cy.wait("@xhr");
  });
});
```

### Versions

cypress - 6.0.1
node - 12.8.3
chrome - 87.0.4280.88
os - macos 11.0.1 (20B29)
ci provider - undefined

PS: not sure but it might be related to this [PR](https://github.com/cypress-io/cypress/pull/2969) which was made by @brian-mann

**Comment by jennifer-shehane** [comment] 2020-12-08 04:49
I'm not able to reproduce the error with the provided code. It looks like in your screenshot you have a server running with some browser-sync requests - can you provide a full repo of the example? Something else may be involved outside of the example you gave.

**Test passes with only code provided above**

<img width="1107" alt="Screen Shot 2020-12-08 at 11 16 33 AM" src="https://user-images.githubusercontent.com/1271364/101441256-199b4700-3947-11eb-9d67-b6cfd5c5f6bc.png">

**Comment by mac2000** [comment] 2020-12-08 06:47
@jennifer-shehane indeed you are right, I'm also confirming the same behavior

So whenever you are doing something like: `php -S 0.0.0.0:3000` everything **works** as expected

But when we use something like: `npx lite-server` which indeed use some socket connections to reload pages on changes **issue is reproducible**

Unfortunately, 6.1.0 still has this issue

As about repo, I bed that it will be reproduced with `npx lite-server` but if it will help please let me know I will create one

**Comment by guilhermebruzzi** [comment] 2020-12-10 13:50
Running tests with Cypress 6.1.0 and having the same problem with `cy.intercept`.
When my axios request is aborted (appears (canceled) on Chrome network tab), `cy.intercept` keeps waiting for it, instead of getting the new request that is active:

![Screen Shot 2020-12-10 at 10 46 04](https://user-images.githubusercontent.com/1321766/101780159-eedef900-3ad4-11eb-91f9-b16326230117.png)

![image](https://user-images.githubusercontent.com/1321766/101780112-dc64bf80-3ad4-11eb-9a5c-ab1d3c7c5a91.png)

With cy.server and cy.route works fine

**Comment by guilhermebruzzi** [comment] 2020-12-10 17:04
And not directly related to this issue, but cy.state('requests') is not having the requests intercepting by cy.intercept just like cy.route? There is another issue talking about it?

**Comment by jennifer-shehane** [comment] 2021-01-12 03:16
@guilhermebruzzi Can you provide an example of the `cy.state('requests')` being different with `cy.intercept()`? The test below works and our tests in Cypress ensure if is defined the same. 

```js
  it('test cy.intercept()', () => {
    cy.intercept('/users').as('getUrl')
    cy.visit('https://example.com')
    cy.window().then((win) => {
      const xhr = new win.XMLHttpRequest()
      xhr.open('GET', '/users')
      xhr.send()
    })
    cy.wait('@getUrl').then(() => {
      expect(cy.state('requests')).to.have.length(1)
    })
  })
```

Also, we'll need a reproducible example for the issue in this thread. Without that, the issue will need to be closed as we can't move forward with investigating.

**Comment by jennifer-shehane** [comment] 2021-01-20 06:05
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mac2000** [comment] 2021-01-20 07:34
hm, here you go:

```bash
git clone https://github.com/mac2000/cypress-9549
cd cypress-9549
npm i
npm start
npm test
```


https://user-images.githubusercontent.com/88868/105141947-9141c180-5b02-11eb-9e42-df04c343a931.mp4

**Comment by jennifer-shehane** [comment] 2021-01-20 09:47
@mac2000 Nice. Thanks for this. 

Sometimes the first time I run this it passes, but on rerun it definitely fails. 

`index.html`

```html
<html>
<body>
  <button onclick="bad()">bad</button>
  <script>
    function bad() {
      let xhr = new XMLHttpRequest();
      xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
      xhr.responseType = "json";
      xhr.send();
      xhr.abort();
      
      xhr = new XMLHttpRequest();
      xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
      xhr.responseType = "json";
      xhr.send();
      xhr.onload = () => {
        document.body.innerHTML += "<pre>" + JSON.stringify(xhr.response) + "</pre>";
      };
    }
  </script>
</body>
</html>
```

```js
it('should handle non-aborted requests', () => {
  cy.intercept('https://jsonplaceholder.typicode.com/todos/1').as('xhr')
  cy.visit('index.html')
  cy.get('button').contains('good').click()
  cy.get('pre').contains('delectus') // response body renders to page
  // ✅ passes
  cy.wait('@xhr')
})

it('cy.route should handle aborted requests', () => {
  cy.server()
  cy.route('https://jsonplaceholder.typicode.com/todos/1').as('xhr')
  cy.visit('index.html')
  cy.get('button').contains('good').click()
  cy.get('pre').contains('delectus') // response body renders to page
  // ✅ passes
  cy.wait('@xhr')
})

it('cy.intercept should handle aborted requests', () => {
  cy.intercept('https://jsonplaceholder.typicode.com/todos/1').as('xhr')
  cy.visit('index.html')
  cy.get('button').contains('bad').click()
  cy.get('pre').contains('delectus')  // response body renders to page
  // ❗️ times out sometimes
  cy.wait('@xhr')
})

```

**Comment by mac2000** [comment] 2021-01-20 11:36
@jennifer-shehane indeed and it seems that root cause here is this socket connection being involved, so whenever on page we have some socket activity it somehow brakes everything, probably can test it even without lite-server by just adding socket connection to a page, but still need some server for this

**Comment by sainthkh** [comment] 2021-02-03 07:19
There are minor errors in the reproducible example above:

1. index.html doesn't contain `good` button.
2. Test 2 should click `bad` button, not `good`.

The corrected example is below:

**index.html**

```html
<!DOCTYPE html>
<html>
  <head>
    <title>demo</title>
  </head>
  <body>
    <button onclick="good()">good</button>
    <button onclick="bad()">bad</button>
    <script>
      function good() {
        const xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.responseType = "json";
        xhr.send();
        xhr.onload = () => {
          document.body.innerHTML += "<pre>" + JSON.stringify(xhr.response) + "</pre>";
        };
      }
      function bad() {
        let xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.responseType = "json";
        xhr.send();
        xhr.abort();
        xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.responseType = "json";
        xhr.send();
        xhr.onload = () => {
          document.body.innerHTML += "<pre>" + JSON.stringify(xhr.response) + "</pre>";
        };
      }
    </script>
  </body>
</html>
```

**test.js***

```js
it('should handle non-aborted requests', () => {
  cy.intercept('https://jsonplaceholder.typicode.com/todos/1').as('xhr')
  cy.visit('index.html')
  cy.get('button').contains('good').click()
  cy.get('pre').contains('delectus') // response body renders to page
  // ✅ passes
  cy.wait('@xhr')
})

it('cy.route should handle aborted requests', () => {
  cy.server()
  cy.route('https://jsonplaceholder.typicode.com/todos/1').as('xhr')
  cy.visit('index.html')
  cy.get('button').contains('bad').click()
  cy.get('pre').contains('delectus') // response body renders to page
  // ✅ passes
  cy.wait('@xhr')
})

it('cy.intercept should handle aborted requests', () => {
  cy.intercept('https://jsonplaceholder.typicode.com/todos/1').as('xhr')
  cy.visit('index.html')
  cy.get('button').contains('bad').click()
  cy.get('pre').contains('delectus')  // response body renders to page
  // ❗️ times out sometimes
  cy.wait('@xhr')
})
```

**Comment by JasonFairchild** [comment] 2021-02-16 22:39
I can also reproduce this. Though it is flaky in my case since canceled requests don't always happen. But every time the canceled request does happen, cy.wait('@alias') definitely fails. I'm running 6.4.0

![image](https://user-images.githubusercontent.com/56280950/108130562-18844580-706d-11eb-905b-ac138eef4154.png)

**Comment by everton-nasc** [comment] 2021-02-16 22:44
I had the same issue on my CI environment (failure ratio up to 25% - GitActions) and the workaround (a good one so far) that I did was:
1. Get rid from `cy.intercept` for lazy endpoints ---> replace it to `cy.server` and `cy.route`
2. Increased the `defaultCommandTimeout` from 3s to 6s (we have a really heavy/lazy endopint)

Or
Downgrade your Cypress version prior to `cy.intercept` feature. - I had no issues with Cypress 4.8.1.

**Comment by bahmutov** [comment] 2021-02-17 00:31
I added a failing reproducible test in https://github.com/cypress-io/cypress-example-recipes/tree/aborted-request-example

https://github.com/cypress-io/cypress-example-recipes/blob/aborted-request-example/examples/stubbing-spying__intercept/cypress/integration/spy-on-fetch-spec.js#L78-L87

```js
// https://github.com/cypress-io/cypress/issues/9549
it('handles aborted requests', () => {
  cy.intercept('https://jsonplaceholder.typicode.com/todos/1').as('aborted')
  cy.get('#aborted-request').click()
  cy.wait('@aborted', { timeout: 2000 })

  cy.wait(1000)
  cy.get('#aborted-request').click()
  cy.wait('@aborted', { timeout: 2000 })
})
```
<img width="1131" alt="Screen Shot 2021-02-16 at 7 28 41 PM" src="https://user-images.githubusercontent.com/2212006/108139192-89d3f080-708d-11eb-8dc1-8f8d579b6f3c.png">

**Comment by JasonFairchild** [comment] 2021-02-17 18:08
Does the PR from saintkhk fix the issue for Cypress, or is it just a PR to fix some tests that also demonstrate this behavior?

**Comment by bahmutov** [comment] 2021-02-17 18:21
Well it was meant to fix the issue, but I can still see the issue with it

**Closed** 2021-02-22 15:08 UTC
Labels: pkg/net-stubbing, stage: work in progress, type: bug
