### ISSUE TITLE
undefined after click

### ISSUE THREAD

**Issue by qkreltms** [cypress-io/cypress#6636] opened 2020-03-04 05:12 UTC
### Current behavior:
![bug](https://user-images.githubusercontent.com/25196026/75847119-a4cc3700-5e21-11ea-9e6e-188be3734cea.png)
I've tried testing todolist. what I have done is when I click span tag then style "text-decoration: line-through" is disappears to it and if I do it again style "text-decoration: line-through" is added.

### Desired behavior:

I expect click() after should() will be work but it's not.

### Test code to reproduce

```js
    cy.get("[data-testid=todoItem-span]").each((span, index) =>
      cy
        .wrap(span)
        .then(span => {
          cy.wrap(span)
          .click()
          .should("not.have.css", "text-decoration: line-through")
          .click()
          .should("have.css", "text-decoration: line-through")
        })
    );
```
### Versions

```
"cypress": "^4.0.2",
```

**Comment by jennifer-shehane** [comment] 2020-03-04 11:30
Duplicate of #4062

**Closed by jennifer-shehane** 2020-03-04 11:30 UTC
