### ISSUE TITLE
component testing: top of iframe sometimes hidden

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#16788] opened 2021-06-03 02:36 UTC
### Current behavior

Sometimes the top of the iframe cannot be seen:

![image](https://user-images.githubusercontent.com/19196536/120577708-071e4800-c468-11eb-9f73-14525ef375a0.png)

### Desired behavior

Can see entire iframe.

### Test code to reproduce

This branch does it: https://github.com/cypress-io/cypress/pull/16747

Go to packages/springboard and run yarn cypress:open:ct

**Comment by AnanaMJ** [comment] 2021-07-22 13:54
If you find the component with `class="size-container"` and add 
```
position: fixed
right: -300px (ajust to whatever looks good for you)
```
to the element style, does it fix your issue?

I'm seeing something similar locally but this is the only issue that is close enough to what's happening to me

**Comment by lmiller1990** [comment] 2021-07-28 01:22
Thanks for the suggestion - I'm more looking for a solution that solves it for everyone out of the box, but it's likely to be something similar to what you are suggesting (some kind of minor CSS adjustment).

**Comment by joshwooding** [comment] 2021-12-16 14:51
Any update on a fix/workaround for this?

**Comment by elevatebart** [comment] 2021-12-16 15:37
I think @tgriesser made a fix for this that he only committed to `10.0-release`.

Tim, would you mind terribly merging your fix into 9.X?

https://github.com/cypress-io/cypress/pull/18649

**Comment by joshwooding** [comment] 2022-01-10 17:28
Any update on this? Happy to create a PR with the commit cherry-picked if it helps :)

**Comment by lmiller1990** [comment] 2022-01-11 00:51
If you want to make a PR cherry-picking https://github.com/cypress-io/cypress/pull/18649, I think that would be fine. It would be great if we could find out how to consistently reproduce this problem, so we can verify #18649 actually fixes it.

**Comment by joshwooding** [comment] 2022-01-11 01:07
I'll see if I'm able to reproduce this consistently.

**Comment by joshwooding** [comment] 2022-01-11 02:22
I was able to reproduce it @lmiller1990 I believe it's something to do with the scrolling of the command pane and setting the viewportHeight to above a certain value. My reproduction is here: https://github.com/joshwooding/cypress-react-template

**Comment by elevatebart** [comment] 2022-01-11 15:28
I believe the issue happens, on 9.X, under those conditions:
- the AUT needs to scale down because the viewport is too big for the browser window user has open
- the application in the AUT iframe is bigger than the iframe (because of the viewport settings)

In this case, the initial scroll pushes the content above the fold. It does not happen all the time since it is a rendering race condition. 
This scrolled content is then made inaccessible by blocking scroll using `overflow: hidden`.

I believe using `overflow: clip` instead of `overflow:hidden` would block this scroll up for good and fix it.

I will review

**Closed** 2022-01-11 15:34 UTC
Labels: stage: needs review, component testing
