### ISSUE TITLE
__/#/tests/... page errors 404 - page not found on Chrome 75

### ISSUE THREAD

**Issue by joszo** [cypress-io/cypress#4893] opened 2019-08-01 08:00 UTC
Hello,

I've problem with NotFound.

How my test look likes:
```js
describe('As a Admin I want to manage rfs part I', () => {
	it('I want to create residential for sale', () => {
		createFeatureListing(page.residentialElement, page.forSaleElement, 'Cold Brayfield');
	});
});

describe('As a Admin I want to manage rfs part II', () => {
	it('I want to check residential listing', () => {
		checkFeatureListing(residentialPropertySaleUrl());
	});
});

describe('As a Admin I want to manage rfs part III', () => {
	it('I want to unmark property as featured and delete slot', () => {
		deleteFeatureListing();
	});
```
In part I we visit url A setup item A
In part II we visit url B and verify added item A
In part III we visit url A and delete added item A

I had those test in one describe() but it also didn't worked.

My cypress version is 3.4.1. 

What is funny - I have same methods for another test, the difference is only that I visit url A, then url C, and then url A. Tests, passes correctly. 

![Screen Shot 2019-08-01 at 9 59 21 AM](https://user-images.githubusercontent.com/32454314/62275848-19ca2f00-b443-11e9-8e32-8a081c0063d2.png)

![Screen Shot 2019-08-01 at 9 59 31 AM](https://user-images.githubusercontent.com/32454314/62275850-19ca2f00-b443-11e9-80d4-0acc2e69beee.png)

What can be the problem? If you need more information please let me know. 

The only workaround which would solve my problem is to create 2 specs:
In 1 spec
Visit url A setup item A
Visit url B and verify added item A

In 2 spec
Visit url A and delete added item A

But it is so ugly :(

**Comment by sainthkh** [comment] 2020-11-13 06:36
Closing because there is no reproducible test. If it's still happening in 5.6.0+, please open a new issue with a reproducible example.

**Closed by sainthkh** 2020-11-13 06:36 UTC
