### ISSUE TITLE
Component tests break due to Cypress version 13 adding a 'specPath' query parameter to the URL

### ISSUE THREAD

**Issue by vidyanambiar** [cypress-io/cypress#28021] opened 2023-10-10 16:58 UTC
### Current behavior

We are attempting to upgrade Cypress on our React project from version 12.17.4 to version 13.3.0. 

After the upgrade to version 13 we observed that some of our existing component tests failed. The reason is that Cypress adds a new `specPath` query parameter in the `window.location` URL. As a result code that is dependent on the value of `location.search` now breaks because of this unexpected new parameter.

### Desired behavior

Cypress tests should not change the URL by adding new query parameters to it.

### Test code to reproduce

https://github.com/ansible/ansible-ui/pull/1007

This PR includes a workaround for removing the `specPath` parameter from the URL in our code. But this workaround is undesirable as we don't want to introduce conditions in the code only to support component tests.

![Screenshot 2023-10-10 at 11 21 11 AM](https://github.com/cypress-io/cypress/assets/43621546/ec82ea61-509a-4c29-a22a-755954b611ba)

### Cypress Version

13.3.0

### Node version

v18.10.0

### Operating System

macOS 13.6

**Comment by marktnoonan** [comment] 2023-10-11 02:29
Hi! Thanks for taking the time to report this. This looks like a consequence of a known breaking change in https://github.com/cypress-io/cypress/pull/27510, see [this comment](https://github.com/cypress-io/cypress/pull/27510/files#r1295264721). And just to connect the dots, that's really a duplicate of https://github.com/cypress-io/cypress/pull/26844. 

We've not generally expected that component specs will have much to do with the URL, and there are lots of expectations for using the `window.location` that aren't met in Component Testing - for example things like navigation. My baseline expectation is that in general in that in a React app you would be grabbing params from a router, and when testing components that depend on those params, you would mock the router. But of course not everybody will be doing this.

In the short term, I think you might be able to move the workaround out of your application's logic and run it before your mount command [here](https://github.com/ansible/ansible-ui/blob/main/cypress/support/component.tsx#L79):  - something like `window.history.pushState({}, document.title, window.location.pathname)`?. This should allow Cypress to work normally for you, and remove any unwelcome guest params before any of your own application code executes.

Longer term, I think we should bear this use case in mind and see if we can bake this cleanup into our provided mount adapters, or find some other way to preserve the bugfix that led to this change. There probably can be other side effects of unexpected params on the iframe, even if we don't expect or recommend folks to depend on that URL.

Let me know if that cleanup suggestion, or something like it, works out for you.

**Closed as not planned** 2024-05-15 18:35 UTC
Labels: type: enhancement, CT
