### ISSUE TITLE
Cypress Runner crashes when response takes too long

### ISSUE THREAD

**Issue by Nasicus** [cypress-io/cypress#16475] opened 2021-05-12 12:01 UTC
This happens with the current version (`7.3.0`) and started happening starting with ~`5.0` (not sure anymore).
Never reported it because I always hoped it will be fixed in the next version. But so far it hasn't.

Problem:

If I'm debugging my server side code (i.e. a request takes a very long time => more than ~30 seconds) the Cypress test runner just crashes (closes completely).

The requests I'm doing is something around that:

```
const response = cy.request({
    method: 'GET',
    url: "http://localhost/my-api,
    headers: {
      authorization: `Bearer ${token}`,
    },
    failOnStatusCode: false
  });
```

... and then I normally process the result like that:

```
response.its('status').should((s) => expect(s).to.eql(200));
```

The following is on the terminal:

```
RangeError: Maximum call stack size exceeded
    at isBinary (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:23:18)
    // the following line (hasBinary) is about ~15k times in the call stack! removed it for readability
    at hasBinary (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:46:9)
    //... 15'000 times the line from above
    at Object.hasBinary (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at Encoder.encode (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\index.js:38:29)
    at Client._packet (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\client.js:169:44)
    at Socket.packet (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:160:21)
    at C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:274:18
    at C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\lib\socket-base.js:325:28
    at tryCatcher (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\cypress.user\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

As mentioned: In older versions this didn't happen. The test simply timed out then and it executed the next one or if it ran all the tests it just stayed open.

**Comment by jennifer-shehane** [comment] 2021-05-12 15:44
Duplicate of https://github.com/cypress-io/cypress/issues/16476

**Closed by jennifer-shehane** 2021-05-12 15:44 UTC
