### ISSUE TITLE
Maximum call stack size exceeded (trying to reload test that had been working)

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#19831] opened 2022-01-21 23:04 UTC
### Current behavior

In the video below, I am trying to reload the cypress runner by hitting cmd+r (on a mac) but it keeps saying that an error is thrown in my app: 
https://user-images.githubusercontent.com/2730609/150610789-c0a8a4b8-5465-46fa-9144-bea482c364f6.mov

However, in the meantime I can load my app just fine. Here's the app in another chrome instance loading just fine: 
![image](https://user-images.githubusercontent.com/2730609/150610851-c1ebd032-97a1-4504-80c8-184710fcb231.png)

Now here's the semi strange part, the call stack printed to the console: 
![image](https://user-images.githubusercontent.com/2730609/150610908-90bd820c-bb8b-4a05-979d-d100358f7ac9.png)

```
cypress_runner.js:190988 RangeError: The following error originated from your test code, not from Cypress.

  > Maximum call stack size exceeded

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at String.match (<anonymous>)
    at Object.extractSourceMap (http://localhost:3000/__cypress/runner/cypress_runner.js:178062:28)
    at extractSourceMap (http://localhost:3000/__cypress/runner/cypress_runner.js:177145:87)
From previous event:
    at runScriptsFromUrls (http://localhost:3000/__cypress/runner/cypress_runner.js:177158:114)
    at Object.runScripts (http://localhost:3000/__cypress/runner/cypress_runner.js:177173:12)
    at $Cypress.onSpecWindow (http://localhost:3000/__cypress/runner/cypress_runner.js:166034:75)
```

### Desired behavior

Ideally Cypress would just run normally, not get caught in this weird state where it says a Maximum call stack size exceeded. If I close the test via the test runner and re-open it everything works fine. 

Also cypress seems to think that "The following error originated from your test code, not from Cypress." and then points directly to cypress runner code. So not quite sure what is going on here. 

### Test code to reproduce

I am not able to reproduce this consistently nor am I able to reproduce this on any of the open source repos I work on. It is very annoying however and seems to point to cypress runner code that I am not in control of. 

It also seems to happen mostly when I am developing my app with webpack, make a change to my app (which hot reloads the code) and then reload the cypress runner to rerun the test shortly after. 

Sometimes the runner is able to "correct itself" and start running the test again after a couple of reloads, and sometimes it gets truly stuck, like now which is why I was able to take the video above.

Happy to provide any more details people want. Any insights or guesses as to what's going on would be appreciated. Thanks!

### Cypress Version

8.5.0
(also seeing this on the latest cypress)

**Comment by tho-masn** [comment] 2022-06-29 07:40
I'm experiencing the exact same issue in Cypress v10.2.
In our case we are starting the tests with devTools open. 
When I close the devTools, the error doesn't appear.

**Comment by juliomrc** [comment] 2022-07-01 11:29
@tnrich It has been a while. Do you have any update on this?
We recently updated Cypress and we are facing the exact same issue.

**Comment by nemonemi** [comment] 2022-09-08 14:18
I am experiencing this as well on version 10.7.0.

**Comment by richardszanyi-kasa** [comment] 2022-11-17 09:16
Same on our end. 10.11

**Comment by poponuts** [comment] 2022-12-29 04:21
I suddenly got this on v12.2

**Comment by emilyrohrbough** [comment] 2022-12-29 12:24
@poponuts / @richardszanyi-kasa  are you seeing the same stack trace?
[This check](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/source_map_utils.ts#L45) to ignore this error when it occurs because this is thrown when parsing source maps which is used to providing the line number of errors in stack traces when errors occur -- but shouldn't prevent tests from running. This would have been released in 10.8.

**Comment by chrisbreiding** [comment] 2023-01-11 19:07
Right now there doesn't seem to be enough information to reproduce the problem on our end. I'm going to close this issue until we can reproduce it. This does not mean that this issue is not happening - it just means that we do not have a path to move forward.

Please post a comment with a reproducible example and we can re-open this issue.

**Closed by chrisbreiding** 2023-01-11 19:07 UTC
Labels: stage: awaiting response

**Comment by dudewad** [comment] 2023-01-19 01:01
I am also experiencing this issue and have been for quite some time now. I'm on 10.1.0. I have been unable to determine what causes this, but it happens once every ~20 test runs, gets stuck, and I have to close the entire runner and start it up again. It's highly inconvenient.
