### ISSUE TITLE
window:confirm event ignored by command line (but not UI)

### ISSUE THREAD

**Issue by benschenker** [cypress-io/cypress#1432] opened 2018-03-07 21:07 UTC
- Operating System: OSX 10.3.3
- Cypress Version: 2.1.0
- Browser Version: Chrome 64

### Current behavior:
When a page fires a confirm command, the UI runner correctly handles this (as noted in https://docs.cypress.io/api/events/catalog-of-events.html#App-Events) but when running `cypress run` from the command line it just times out waiting for the load event.

### Desired behavior:
As noted in https://docs.cypress.io/api/events/catalog-of-events.html#App-Events, when a window:confirm event is fired, the default action should be auto accept. This should work the same when run from the UI and from the command line. At minimum the `cy.on('window:confirm')` command should be used.

### How to reproduce:
* Run the test below using the UI `cypress open` and it will pass
* Run the test below using the command line `cypress run --spec path/to/test.spec.js` and it will fail

#### Test code:

Cypress file
```js
describe('Test window.confirm', () => {
  beforeEach(() => {
    cy.on('window:confirm', () => true); // this is unnecessary as it is the default behavior
  });

  it('should accept the confirm and successfully reload', function() {
    cy.visit(`path/to/test.html`);
    cy.reload();
  });
});
```

test.html
```html
<html>
  <body>
    hello world
  </body>
  <script>
    window.onbeforeunload = () => confirm("test");
  </script>
</html>
```

### Additional Info (images, stack traces, etc)

EDIT -  See example: https://github.com/cypress-io/cypress-test-tiny/pull/27

**Comment by benschenker** [comment] 2018-04-12 16:51
Update: if I run with `cypress run --browser chrome` this works correctly... looks like it is related to the electron browser

**Comment by bsmithEG** [comment] 2018-05-24 02:59
I also seem to be having this issue, but for a different event:

```typescript
    //tslint:disable
    Cypress.on("window:before:load", win => {
        console.log("called window before load")
        const script = win.document.createElement("script")
        const scripts = win.document.getElementsByTagName("script")[0] as HTMLScriptElement
        script.type = "text/javascript"
        script.src = `http://localhost:3030/beacon/${account}/${dataset}/evergage.min.js`
        if (scripts && scripts.parentNode) {
            scripts.parentNode.insertBefore(script, scripts)
        }
        cy
            .stub(win, "fetch")
            .withArgs("/evergage.min.js")
            .as("fetchBeacon")
            .returns("@beacon")
    })
```

**Comment by jennifer-shehane** [comment] 2018-11-10 00:28
duplicate of https://github.com/cypress-io/cypress/issues/2118

**Closed by jennifer-shehane** 2018-11-10 00:28 UTC
Labels: browser: electron, stage: needs investigating

**Comment by nikhilesh009** [comment] 2019-02-15 13:29
i want to see the alert message but i am getting this message in cypress log"There are unsaved changes to this booking. Are you sure you want to do this?" and it auto accept alert

**Comment by jennifer-shehane** [comment] 2019-02-15 18:28
@nikhilesh009 Check out [this doc on listening to `window:confirm` events](https://on.cypress.io/catalog-of-events#Window-Confirm).
