### ISSUE TITLE
Whoops, there is no test to run.

### ISSUE THREAD

**Issue by uc-any** [cypress-io/cypress#5938] opened 2019-12-12 11:20 UTC
### Current behavior: 

Cypress generate "Whoops, there is no test to run" when we submit a form.

### Desired behavior: 

It should run properly and submit the form.

### Steps to reproduce: 

This error comes only when we use `target="_parent"` when we changed it this will not come.

```html
<form method="post" target="_parent" action="admin/store_me.php">
    <input type="text" name="text_value" id="text_value"/>
    <button type="submit" name="submit_form" id="submit_form">Save</button>
</form>

```
```js
cy.get("#text_value")
    .type("My Text");
cy.get("#submit_form")
    .click();
```

### Versions
3.7

**Comment by jennifer-shehane** [comment] 2019-12-13 11:27
Thank you for the incredibly clear reproducible example. This is a duplicate of https://github.com/cypress-io/cypress/issues/3121, but I will add your example to that issue. Thanks. 

If you have control over the code, you can rewrite `target="_parent"` to `target="_self"` as explained here: https://github.com/cypress-io/cypress/issues/3121#issuecomment-453634949

**Closed by jennifer-shehane** 2019-12-13 11:27 UTC

**Comment by amitdhanke** [comment] 2020-02-20 07:21
i facing this issue while navigating to URL itself
