### ISSUE TITLE
Cypress won't open project

### ISSUE THREAD

**Issue by jakub-bao** [cypress-io/cypress#7044] opened 2020-04-16 19:11 UTC
### Current behavior:

Hi, daily Cypress user here. I started having this issue just suddenly.

Steps to reproduce:
1. cypress open
2. open a project
3. it will get stuck on loading:

![image](https://user-images.githubusercontent.com/47790868/79496308-ef7dc900-7ff3-11ea-9092-f0186916baee.png)

No errors in the console:

```
jake@jakepc:~/DEV/datim-user-management-ng$ cypress open

```

It can be stuck for several minutes.

### Desired behavior:

1. open the project and show my my test specs

### Versions
Ubuntu 19.10
node v12.16.1
cypress 4.4.0, 4.3.0, 3.8.3

### What I tried
uninstall cypress
remove ~/.config/Cypress
remove ~/.cache/Cypress
reinstall again
i use cypress installed globally, but tried local install with no help

**Comment by jakub-bao** [comment] 2020-04-16 19:37
Is it possible to run `cypress open` in verbose mode so I can help debug this?

**Comment by jakub-bao** [comment] 2020-04-16 19:48
Adding some logs after `DEBUG=cypress:*`. First run of `cypress open` after clean reinstall.
No user action taken

```
jake@jakepc:~$ sh debugCypress.sh 
  cypress:cli:cli cli starts with arguments ["/home/jake/SERVER/node12/bin/node","/home/jake/bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +51ms
  cypress:cli opening from options {} +0ms
  cypress:cli command line arguments [] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /home/jake/.cache/Cypress/4.4.0/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +4ms
  cypress:cli binaryDir is  /home/jake/.cache/Cypress/4.4.0/Cypress +0ms
  cypress:cli Reading binary package.json from: /home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 4.4.0 installed in: /home/jake/.cache/Cypress/4.4.0/Cypress +2ms
  cypress:cli could not read binary_state.json file at "/home/jake/.cache/Cypress/4.4.0/binary_state.json" +2ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli running binary verification check 4.4.0 +0ms
It looks like this is your first time using Cypress: 4.4.0

  cypress:cli clearing out the verified version +2ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +3ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/jake/.cache/Cypress/4.4.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/jake/.cache/Cypress/4.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=153 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  ⠦  Verifying Cypress can run /home/jake/.cache/Cypress/4.4.0/Cypress
  cypress:cli smoke test stdout "It looks like you are running the Cypress binary directly.

This is not the recommended approach, and Cypress may not work correctly.

Please install the 'cypress' NPM package and follow the instructions here:

https://on.cypress.io/installing-cypress
153" +2s
  cypress:cli write verified: true +0ms
  ✔  Verified Cypress! /home/jake/.cache/Cypress/4.4.0/Cypress

Opening Cypress...
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +2s
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli passing DISPLAY :0 +2ms
  cypress:cli spawning Cypress with executable: /home/jake/.cache/Cypress/4.4.0/Cypress/Cypress +0ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--cwd', '/home/jake' ] { detached: false, stdio: 'inherit' } +0ms
  cypress:ts Running without ts-node hook in environment "production" +0ms
  cypress:server:appdata path: /home/jake/.config/Cypress/cy/production/browsers +0ms
  cypress:server:util:node_options NODE_OPTIONS check passed, not forking { NODE_OPTIONS: '--max-http-header-size=1048576 --http-parser=legacy' } +0ms
  cypress:server:util:node_options restoring NODE_OPTIONS { NODE_OPTIONS: '--max-http-header-size=1048576 --http-parser=legacy', ORIGINAL_NODE_OPTIONS: undefined } +1ms
  cypress:server:cypress starting cypress with argv [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress', '--no-sandbox', '--', '--cwd', '/home/jake' ] +0ms
  cypress:server:args argv array: [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress', '--no-sandbox', '--cwd', '/home/jake' ] +0ms
  cypress:server:args argv parsed: { _: [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress' ], sandbox: false, cwd: '/home/jake', invokedFromCli: true } +2ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress' ], sandbox: false, cwd: '/home/jake', invokedFromCli: true, config: {} } +1ms
  cypress:server:args argv options: { _: [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress' ], sandbox: false, cwd: '/home/jake', invokedFromCli: true, config: {} } +0ms
  cypress:server:cypress from argv [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress', '--no-sandbox', '--cwd', '/home/jake' ] got options { _: [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress' ], sandbox: false, cwd: '/home/jake', invokedFromCli: true, config: {} } +4ms
  cypress:server:appdata path: /home/jake/.config/Cypress/cy/production +197ms
  cypress:server:cypress starting in mode interactive with options { _: [ '/home/jake/.cache/Cypress/4.4.0/Cypress/Cypress' ], sandbox: false, cwd: '/home/jake', invokedFromCli: true, config: {} } +79ms
  cypress:server:cypress running Electron currently +1ms
  cypress:server:appdata path: /home/jake/.config/Cypress/cy/production +122ms
  cypress:server:appdata path: /home/jake/.config/Cypress/cy/production/cache +284ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │    '19191'     │    0.02    │      0.02      │  143.83  │    143.83    │   143.83    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      1       │    '19193'     │     0      │       0        │  41.98   │    41.98     │    41.98    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '19334, 19335' │     0      │       0        │   3.66   │     3.66     │    3.66     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      4       │      '-'       │    0.02    │      0.02      │  189.48  │    189.48    │   189.48    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:server:saved_state making saved state from /home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +1ms
  cypress:server:saved_state state path for global mode +3ms
  cypress:server:appdata path: /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +2s
  cypress:server:saved_state full state path /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:saved_state making new state file around /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file get values from /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file attempt to get lock on /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +2ms
  cypress:server:file gettin lock succeeded or failed for /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +5ms
  cypress:server:file read /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:file read succeeded or failed for /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +7ms
  cypress:server:file attempt to unlock /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +1ms
  cypress:server:file unlock succeeded or failed for /home/jake/.config/Cypress/cy/production/projects/__global__/state.json +2ms
  cypress:server:windows creating electron window with options { backgroundColor: '#dfe2e4', width: 800, height: 550, minWidth: 458, minHeight: 400, x: null, y: null, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, icon: NativeImage {}, webPreferences: { preload: '/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/ipc/ipc.js', partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false, backgroundColor: '#dfe2e4', transparent: false }, url: 'file:///home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/desktop-gui/dist/index.html', contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
  cypress:server:events got request for event: on:menu:clicked, undefined +0ms
  cypress:server:events got request for event: get:options, undefined +0ms
  cypress:server:events got request for event: get:current:user, undefined +1ms
  cypress:server:file get values from /home/jake/.config/Cypress/cy/production/cache +461ms
  cypress:server:file attempt to get lock on /home/jake/.config/Cypress/cy/production/cache +0ms
  cypress:server:events sending ipc data { type: 'get:options', data: { id: 0.4828289091789846, data: { _: [Array], sandbox: false, cwd: '/home/jake', invokedFromCli: true, config: {}, onFocusTests: null, os: 'linux', version: '4.4.0' } }, originalData: { id: 0.4828289091789846, data: { _: [Array], sandbox: false, cwd: '/home/jake', invokedFromCli: true, config: {}, onFocusTests: [Function: onFocusTests], os: 'linux', version: '4.4.0' } } } +3ms
  cypress:server:file gettin lock succeeded or failed for /home/jake/.config/Cypress/cy/production/cache +5ms
  cypress:server:file read /home/jake/.config/Cypress/cy/production/cache +0ms
  cypress:server:file read succeeded or failed for /home/jake/.config/Cypress/cy/production/cache +1ms
  cypress:server:file attempt to unlock /home/jake/.config/Cypress/cy/production/cache +0ms
  cypress:server:file unlock succeeded or failed for /home/jake/.config/Cypress/cy/production/cache +0ms
  cypress:server:events sending ipc data { type: 'get:current:user', data: { id: 0.7795054532897139, data: {} }, originalData: { id: 0.7795054532897139, data: {} } } +5ms
  cypress:server:events got request for event: get:projects, undefined +28ms
  cypress:server:file transaction for /home/jake/.config/Cypress/cy/production/cache +30ms
  cypress:server:file attempt to get lock on /home/jake/.config/Cypress/cy/production/cache +2ms
  cypress:server:events got request for event: updater:check, undefined +3ms
  cypress:server:updater checking for new version of Cypress. current version is 4.4.0 +0ms
  cypress:server:file gettin lock succeeded or failed for /home/jake/.config/Cypress/cy/production/cache +12ms
  cypress:server:file write /home/jake/.config/Cypress/cy/production/cache +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://download.cypress.io/desktop.json' } +0ms
  cypress:network:connect beginning getAddress { hostname: 'download.cypress.io', port: 443 } +0ms
  cypress:network:connect got addresses { hostname: 'download.cypress.io', port: 443, addresses: [ { address: '104.26.6.176', family: 4 }, { address: '104.26.7.176', family: 4 }, { address: '2606:4700:20::681a:6b0', family: 6 }, { address: '2606:4700:20::681a:7b0', family: 6 } ] } +5ms
  cypress:server:file write succeeded or failed for /home/jake/.config/Cypress/cy/production/cache +15ms
  cypress:server:file attempt to unlock /home/jake/.config/Cypress/cy/production/cache +0ms
  cypress:server:file unlock succeeded or failed for /home/jake/.config/Cypress/cy/production/cache +1ms
  cypress:server:events sending ipc data { type: 'get:projects', data: { id: 0.7436865579609808, data: [] }, originalData: { id: 0.7436865579609808, data: [] } } +28ms
  cypress:network:agent got family { family: 4, href: 'https://download.cypress.io/desktop.json' } +36ms
  cypress:server:events got request for event: get:project:statuses, [] +78ms
  cypress:server:project get project statuses for 0 projects +0ms
  cypress:server:file get values from /home/jake/.config/Cypress/cy/production/cache +81ms
  cypress:server:events send error: Error: You're not logged in. Run `cypress open` to open the Desktop App and log in. at Object.get (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/errors.js:348:11) at /home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/user.js:63:26 at tryCatcher (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at _drainQueueStep (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)     at processImmediate (internal/timers.js:439:21) { isCypressErr: true, type: 'NOT_LOGGED_IN', details: undefined, isApiError: true } +10ms
  cypress:server:events sending ipc data { type: 'get:project:statuses', data: { id: 0.12097464076107456, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' + '    at Object.get (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/errors.js:348:11)\n' + '    at /home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/user.js:63:26\n' + '    at tryCatcher (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n' + '    at Promise._settlePromiseFromHandler (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)\n' + '    at Promise._settlePromise (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)\n' + '    at Promise._settlePromise0 (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)\n' + '    at Promise._settlePromises (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)\n' + '    at _drainQueueStep (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)\n' + '    at _drainQueue (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)\n' + '    at Async._drainQueues (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)\n' + '    at Immediate.Async.drainQueues [as _onImmediate] (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)\n' + '    at processImmediate (internal/timers.js:439:21)\n', message: "You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } }, originalData: { id: 0.12097464076107456, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' + '    at Object.get (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/errors.js:348:11)\n' + '    at /home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/lib/user.js:63:26\n' + '    at tryCatcher (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n' + '    at Promise._settlePromiseFromHandler (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)\n' + '    at Promise._settlePromise (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)\n' + '    at Promise._settlePromise0 (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)\n' + '    at Promise._settlePromises (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)\n' + '    at _drainQueueStep (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)\n' + '    at _drainQueue (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)\n' + '    at Async._drainQueues (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)\n' + '    at Immediate.Async.drainQueues [as _onImmediate] (/home/jake/.cache/Cypress/4.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)\n' + '    at processImmediate (internal/timers.js:439:21)\n', message: "You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } } } +4ms
  cypress:server:updater latest version of Cypress is: 4.4.0 +203ms
  cypress:server:updater new version of Cypress does not exist +0ms
  cypress:server:events sending ipc data { type: 'updater:check', data: { id: 0.46192944780099476, data: false }, originalData: { id: 0.46192944780099476, data: false } } +83ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬───────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │         pids          │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼───────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │        '19191'        │    0.86    │      0.44      │  234.82  │    189.33    │   234.82    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      3       │ '19193, 19349, 19611' │     0      │       0        │  178.27  │    110.13    │   178.27    │
  cypress:server:util:process_profiler │    2    │   'desktop-gui'   │      1       │        '19701'        │    0.01    │      0.01      │  126.9   │    126.9     │    126.9    │
  cypress:server:util:process_profiler │    3    │      'other'      │      2       │    '19727, 19728'     │     0      │       0        │   3.53   │     3.59     │    3.66     │
  cypress:server:util:process_profiler │    4    │      'TOTAL'      │      7       │          '-'          │    0.87    │      0.44      │  543.53  │    366.5     │   543.53    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴───────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
```

**Comment by jakub-bao** [comment] 2020-04-16 19:49
Oh, I think I know what was happening.
I got `Chromium` installed on my system. And I think Cypress coudln't find matching chromedriver for chromium and it would all freeze.

Uninstalling chromium fixed the problem...

**Comment by albertaouad** [comment] 2020-04-16 22:47
@jakub-bao close the issue if u no longer have a problem

**Comment by abzainuddin** [comment] 2020-04-17 08:14
I had a similar problem, where since yesterday suddenly Cypress would keep loading. I'm on Unbuntu 19.10, where chromium is installed using snap. After some debugging using ``DEBUG=cypress:* yarn cypress open``, my temporary solution is:

`snap remove chromium`

Instead of uninstalling chromium, it would be better let Cypress gracefully handle the issue, now it simply doesn't work if chromium is installed.

**Comment by jennifer-shehane** [comment] 2020-04-17 11:26
Duplicate of #7020

**Closed by jennifer-shehane** 2020-04-17 11:26 UTC
