### ISSUE TITLE
Cypress v10.3.1 cypress.config.js require/module not defined

### ISSUE THREAD

**Issue by bwfisher82** [cypress-io/cypress#23005] opened 2022-07-28 23:33 UTC
### Current behavior

1. Performed a fresh install of node/npm, vue, vitest, cypress, eslint, prettier, vue-router at latest versions.
2. Ran 'npm install' without error.
3. Ran 'npm lint' with errors in cypress.config.js.

The errors are:

C:\Users\...\project\cypress.config.js
  1:26  error  'require' is not defined  no-undef
  3:1   error  'module' is not defined   no-undef

I found that adding the eslint comment block at the top (/* eslint-env node */) solved this, but I am not sure if this is the best/correct solution here.

npm list output:

+-- @rushstack/eslint-patch@1.1.4
+-- @vitejs/plugin-vue@3.0.1
+-- @vue/eslint-config-prettier@7.0.0
+-- @vue/test-utils@2.0.2
+-- cypress@10.3.1
+-- eslint-plugin-cypress@2.12.1
+-- eslint-plugin-vue@9.3.0
+-- eslint@8.20.0
+-- jsdom@20.0.0
+-- prettier@2.7.1
+-- start-server-and-test@1.14.0
+-- vite@3.0.3
+-- vitest@0.18.1
+-- vue-router@4.1.3
`-- vue@3.2.37

### Desired behavior

No errors?

### Test code to reproduce

No code has been written yet.

### Cypress Version

10.3.1

**Comment by rockindahizzy** [comment] 2022-08-08 17:24
Hey @bwfisher82,

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-15 18:26
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-15 18:26 UTC
Labels: stage: awaiting response, Needs Reproduction

**Comment by gitKearney** [comment] 2023-02-07 15:31
Hi. I am encountering this issue. When I use `npm init vue@latest` (this is from a udememy course)

```
Vue.js - The Progressive JavaScript Framework

✔ Project name: … music
✔ Add TypeScript? … No / Yes
✔ Add JSX Support? … No / Yes
✔ Add Vue Router for Single Page Application development? … No / Yes
✔ Add Pinia for state management? … No / Yes
✔ Add Vitest for Unit Testing? … No / Yes
✔ Add an End-to-End Testing Solution? › Cypress
✔ Add ESLint for code quality? … No / Yes
✔ Add Prettier for code formatting? … No / Yes

Scaffolding project in /Users/kearney/-/music...

Done. Now run:

  cd music
  npm install
  npm run lint
  npm run dev
```

When I run the command `npm run lint` I get the following error:
```> music@0.0.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore


/Users/kearney/-/music/cypress.config.js
  1:26  error  'require' is not defined  no-undef
  3:1   error  'module' is not defined   no-undef

✖ 2 problems (2 errors, 0 warnings)

```

# MY SYSTEM
_node --version v18.12.1_
_npm --version: 9.3.1_
MacOS 13.2

**Comment by cabbachew** [comment] 2023-03-21 21:31
I had the same issue, but I addressed these errors by using `import . . . from . . . ` and `export default` syntax instead of `require()` and `module.exports`.

From:
```js
const { defineConfig } = require("cypress");

module.exports = . . .
```

To:
```js
import { defineConfig } from "cypress";

export default . . . 
```
