### ISSUE TITLE
Cypress 10.3.1: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by TommasoAmici** [cypress-io/cypress#23061] opened 2022-08-02 10:58 UTC
### Current behavior

Hello, I'm trying to run Cypress in GitLab CI using the `cypress/base:16` image.

I run my tests with the following command:

```sh
cypress run --headless --component --config watchForFileChanges=false
```

Additionally I have disabled file watching in `vite.config.js`, however I'm getting the following error on every run:

```
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.3.1                                                                         │
  │ Browser:        Electron 100 (headless)                                                        │
  │ Node Version:   v16.14.2 (/usr/local/bin/node)                                                 │
  │ Specs:          21 found (app-banner.cy.js, todo.cy.js, actions.cy.js, aliasing.cy.js, asserti │
  │                 ons.cy.js, connectors.cy.js, cookies.cy.js, cypress_api.cy.js, files.cy.js, lo │
  │                 cal_storage.cy.js, location.cy.js, misc.cy.js, navigation.cy.js, network_reque │
  │                 sts.cy.js, querying.cy....)                                                    │
  │ Searched:       **/*.cy.{js,jsx,ts,tsx}                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  app-banner.cy.js                                                               (1 of 21)
Your configFile threw an error from: cypress.config.js
We stopped running your tests because your config file crashed.
Error: ENOSPC: System limit for number of file watchers reached, watch '/builds/technical-design/ripe-app-webcomponents/cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/codegen/index.js'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2251:34)
    at createFsWatchInstance (file:///builds/technical-design/ripe-app-webcomponents/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:47466:17)
    at setFsWatchListener (file:///builds/technical-design/ripe-app-webcomponents/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:47513:15)
    at NodeFsHandler$1._watchWithNodeFs (file:///builds/technical-design/ripe-app-webcomponents/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:47668:14)
    at NodeFsHandler$1._handleFile (file:///builds/technical-design/ripe-app-webcomponents/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:47732:23)
    at NodeFsHandler$1._addToNodeFs (file:///builds/technical-design/ripe-app-webcomponents/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:47974:21)
```

This is similar to #22054 and #17173 for example

### Desired behavior

Not throw an error and disable file watching

### Test code to reproduce

I might get around to this later

### Cypress Version

10.3.1

**Comment by TommasoAmici** [comment] 2022-08-02 11:03
Following this suggestion https://github.com/cypress-io/cypress/issues/17173#issuecomment-887257762, I have added `CHOKIDAR_USEPOLLING=1` to my environment and it works

**Comment by AtofStryker** [comment] 2022-08-03 20:26
Hey @TommasoAmici. Thank you for opening an issue. Would you be able to put together a quick reproducible example on a github repo? It seems weird that `CHOKIDAR_USEPOLLING` would fix the issue, since this turns on watching. have you verified that `watchForFileChanges` is being propagated to the config?

**Comment by leschdom** [comment] 2022-08-04 07:07
It seems related to this issue https://github.com/cypress-io/cypress/issues/22959

**Comment by TommasoAmici** [comment] 2022-08-05 10:14
I have managed to create a minimal reproduction (https://github.com/TommasoAmici/cypress-repro-23061)

It fails on our self hosted GitLab running in a Docker runner (it's not a public instance so I cannot link to it). I added to the repository a directory with 8000 thousand files and that triggers the file watcher error. Attached here you can find the logs for this run. [job.log](https://github.com/cypress-io/cypress/files/9267723/job.log)

I have then set up a GitHub repository with the official [Cypress action](https://github.com/marketplace/actions/cypress-io), but it happily worked, so I've increased the files to 16000 ([no error](https://github.com/TommasoAmici/cypress-repro-23061/runs/7689280806)) and 24000 ([no error](https://github.com/TommasoAmici/cypress-repro-23061/runs/7689333510)).

I'm sure GitHub Actions are configured in a different way from a GitLab Docker runner, but this is the best I could do to show it

**Comment by AtofStryker** [comment] 2022-08-09 14:19
> I have managed to create a minimal reproduction (https://github.com/TommasoAmici/cypress-repro-23061)
> 
> It fails on our self hosted GitLab running in a Docker runner (it's not a public instance so I cannot link to it). I added to the repository a directory with 8000 thousand files and that triggers the file watcher error. Attached here you can find the logs for this run. [job.log](https://github.com/cypress-io/cypress/files/9267723/job.log)
> 
> I have then set up a GitHub repository with the official [Cypress action](https://github.com/marketplace/actions/cypress-io), but it happily worked, so I've increased the files to 16000 ([no error](https://github.com/TommasoAmici/cypress-repro-23061/runs/7689280806)) and 24000 ([no error](https://github.com/TommasoAmici/cypress-repro-23061/runs/7689333510)). I have now gone up to 48000 files with no errors ([run](https://github.com/TommasoAmici/cypress-repro-23061/runs/7689471733?check_suite_focus=true)).
> 
> I'm sure GitHub Actions are configured in a different way from a GitLab Docker runner, but this is the best I could do to show it.

> Maybe it really is a case of config not propagating properly. How could I confirm whether that's the case or not?

Since it fails on self hosted gitlab and you haven't had luck in github actions, have you tried running this in cloud gitlab CI and capturing the results? I see there is a `gitlab-ci.yaml` file in there but figured it might only be run on the on prem solution.

**Comment by TommasoAmici** [comment] 2022-08-10 07:23
The `.gitlab-ci.yaml` is generic. I've set up a public repo on GitLab to test it annd indeed it fails: https://gitlab.com/tommaso.amici/cypress-repro-23061/-/jobs/2836895815

**Comment by AtofStryker** [comment] 2022-08-10 14:04
As a workaround, have you tried increasing the `fs.inotify.max_user_watches` inside the CI run? You might need to give the docker image privileged/admin access

**Comment by TommasoAmici** [comment] 2022-08-10 14:21
Thanks for the tip, but as explained above, I already found a workaround

> Following this suggestion [#17173 (comment)](https://github.com/cypress-io/cypress/issues/17173#issuecomment-887257762), I have added `CHOKIDAR_USEPOLLING=1` to my environment and it works

However my understanding is that file watching should be disabled if I pass `--config watchForFileChanges=false` so this shouldn't be happening at all.

Is it possible that this option is not being picked up by Cypress?

**Comment by AtofStryker** [comment] 2022-08-10 14:49
> Thanks for the tip, but as explained above, I already found a workaround
> 
> > Following this suggestion [#17173 (comment)](https://github.com/cypress-io/cypress/issues/17173#issuecomment-887257762), I have added `CHOKIDAR_USEPOLLING=1` to my environment and it works

Oh yeah that's right 🤦🏻 . Sorry about that!

> However my understanding is that file watching should be disabled if I pass `--config watchForFileChanges=false` so this shouldn't be happening at all.
> 
> Is it possible that this option is not being picked up by Cypress?

Definitely possible. I'll give https://github.com/TommasoAmici/cypress-repro-23061 a clone and do some debugging to see what's going on.

**Comment by AtofStryker** [comment] 2022-08-11 20:55
The option is definitely getting set through the CLI, so it makes me wonder if it's not being propagated to the server. Either way, looks like a bug.

**Comment by ZachJW34** [comment] 2022-10-06 17:23
Closing as completed in https://github.com/cypress-io/cypress/issues/22959. CT should no longer be watching files in run mode.

**Closed by ZachJW34** 2022-10-06 17:23 UTC
Labels: type: bug, existing workaround, CT, stage: routed to ct
