### ISSUE TITLE
Couldn't upload file using cypress run tests execution (version 4.2.0)

### ISSUE THREAD

**Issue by oborodai** [cypress-io/cypress#6882] opened 2020-03-30 16:57 UTC
While running tests using `cypress open` everything is okay, but each time invoking `cypress run` with the same tests they fail. 

I know that this was fixed in Cypress 3.4.1 -- but this version has a bug with spec runs -- they stop in pending mode after one spec is executed. Could you please fix the Upload File problem for Cypress version 4.2.0.

For Uploading files, I'm using: 
```js
/**
 * Uploads a file to an input
 * @memberOf Cypress.Chainable#
 * @name uploadFile
 * @function
 * @param {String} selector - element to target
 * @param {String} fileUrl - The file url to upload
 * @param {String} mimeType - content type of the uploaded file
 */
Cypress.Commands.add("uploadFile", (selector, fileUrl, mimeType = "") => {
  return cy.get(selector).then(subject => {
    return cy.fixture(fileUrl, "base64").then(base64String => {
      Cypress.Blob.base64StringToBlob(base64String, mimeType).then(function(
        blob
      ) {
        const testfile = new File([blob], fileUrl, { type: mimeType });
        const dataTransfer = new DataTransfer();
        const fileInput = subject[0];
        dataTransfer.items.add(testfile);
        // This triggers the @change event on the input.
        fileInput.files = dataTransfer.files;
        cy.wrap(subject).trigger("change", { force: true });
      });
    });
  });
});
```

**Comment by jennifer-shehane** [comment] 2020-03-31 06:01
Duplicate of #6490 I believe. See if running in `cypress run` with the --browser chrome - if the test passes, because there is an issue with file upload in Electron starting in 3.5.0.

**Closed by jennifer-shehane** 2020-03-31 06:01 UTC

**Comment by oborodai** [comment] 2020-03-31 07:54
@jennifer-shehane I switched browser to Chrome - the same behavior for 3.4.1 and 4.0.2 versions.
