### ISSUE TITLE
Support mocha's this.retries() / retry test failures

### ISSUE THREAD

**Issue by cameronc56** [cypress-io/cypress#1313] opened 2018-02-14 20:27 UTC
### Is this a Feature or Bug?
Feature

### Current behavior:
With this.retries set, when a test fails:

```
TypeError: Cannot set property 'err' of undefined
    at Reporter.mergeErr (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:95:18)
    at Reporter.parseArgs (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:199:20)
    at Reporter.emit (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:190:23)
    at Object.server.startWebsockets.onMocha (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/project.js:287:22)
    at Socket.<anonymous> (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/socket.js:237:36)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at /home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

TypeError: Cannot set property 'err' of undefined
    at Reporter.mergeErr (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:95:18)
    at Reporter.parseArgs (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:199:20)
    at Reporter.emit (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:190:23)
    at Object.server.startWebsockets.onMocha (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/project.js:287:22)
    at Socket.<anonymous> (/home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/socket.js:237:36)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at /home/cameronc/switch/test/matcher/node_modules/cypress/dist/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Desired behavior:
this.retries is supported at the describe() and it() level

**Comment by brian-mann** [comment] 2018-02-15 05:57
We've internally talked about this before and we'll be doing something different from the way mocha implements retries.

It will work the same - but will be controlled by different API's than what mocha provides. I'll open a proposal later and link it to this issue.

**Comment by spatelNYT** [comment] 2018-03-23 19:27
+1 for this feature, along with this it would also be nice to allow global and override retries in mocha `it` block.

**Comment by khuezy** [comment] 2018-04-09 20:52
@brian-mann Hi, do you have any updates on this?

**Comment by hdjong1** [comment] 2018-05-23 11:14
@brian-mann Would also very much like an update about this.

**Comment by henrymunro** [comment] 2018-06-14 08:42
+1 for this feature. We've seen some occasional failures in our CI that this would really help with.

**Comment by EirikBirkeland** [comment] 2018-06-18 20:35
This would be incredibly beneficial. I have a couple of tests that fail at random, and I have not yet figured out how I can get around this. But, if I can simply specify 5 retries, we can have slower yet useful CI builds ...

**Comment by brian-mann** [comment] 2018-06-18 21:14
We discussed this today as a team. It may be the next feature @chrisbreiding works on after Firefox lands.

**Comment by MaaikeFox** [comment] 2018-07-17 16:13
Great feature! 
Can you already give some insight in when it will be available? :)

**Comment by pacop** [comment] 2018-07-23 10:31
Also waiting for this. @brian-mann any updates?

**Comment by mattvb91** [comment] 2018-07-31 11:53
+1

**Comment by Bkucera** [comment] 2018-07-31 19:39
You can launch Cypress using the Module API , and effectively collects failed spec files from the run and tells cypress to run just those files. Here's an example:
https://gist.github.com/Bkucera/4ffd05f67034176a00518df251e19f58

Then, instead of `cypress run`, you use `node cypress-retries.js`

**Comment by EirikBirkeland** [comment] 2018-07-31 19:44
@Bkucera That is a great and simple solution. Will give this a try. Thanks for sharing.

**Comment by germyjen** [comment] 2018-08-03 19:05
would love this feature to come out of the box for cypress: a global setting to retry failed tests x number of times to reduce timeout flakiness. 

@brian-mann any news on where this is with the team?

**Comment by bryantabaird** [comment] 2018-08-06 16:24
@Bkucera running v3.0.1, I had to change the `const specs = _(results.runs).filter("stats.failures").map("spec.relative").value()` to `const specs = _(results.runs).filter("stats.failures").map("spec.path").value()`, but it worked great for me.

I'm hoping for a way to rerun individual failed tests within a spec, but that didn't seem possible with the current setup, since Cypress parameters only included spec files. I'd love to hear any workarounds for that if you had any.

**Comment by pkruhlei** [comment] 2018-08-16 15:17
@bahmutov @brian-mann I think that with retries by workaround https://github.com/cypress-io/cypress/issues/1313#issuecomment-409342834  with Module API will not work with cypress 3.1.x with the parallel run.
The thing that scope of specs will not be same from original run to retry - because some tests will fail and some will pass. So run will fail with https://docs.cypress.io/guides/references/error-messages.html#Cannot-parallelize-tests-across-environments

**Comment by Bkucera** [comment] 2018-09-19 22:29
@nanoflat [I've updated the `cypress-retries` script to work with Parallelization](https://gist.github.com/Bkucera/4ffd05f67034176a00518df251e19f58#file-cypress-retries-js-L14). 

The script should be able to work with parallel runs and non parallel runs. Just pass your configuration to `DEFAULT_CONFIG`

**Comment by itaykotler-fundbox** [comment] 2018-09-26 19:04
@Bkucera, your solution works great and I implemented it in my script.
Small problem, Cypress Dashboard marks the run as `Failed` while the reties succeded.
Is there a way to mark the run as `Passed` when retries have been successful?

**Comment by EirikBirkeland** [comment] 2018-10-05 20:07
@Francis-Moreau-adsk Feel your pain, man!

Just my 2 cents:
(1) Are you sure the app being tested is robust? I've had flakiness issues too, and I could never pinpoint any exact issue. The back-end was a little slow when testing manually, but not inconsistent.
(2) Could it be that flakiness can be reduced by changing the way you write tests? E.g. avoiding await/async, or making tweaks according to Cypress Promise best practices.

Anyway, I am not using Cypress right now, but having excellent 'Retry' facilities will be important to me in the future.

**Comment by Francis-Moreau-adsk** [comment] 2018-10-05 22:08
@EirikBirkeland,  thanks 
The app we are trying to test is pretty solid but the way it's running there is one Cypress issue (https://github.com/cypress-io/cypress/issues/2552) that causes a lot headaches to write tests.  

For sure we need to rethink the way we write tests,  and we will get better as we continue trying Cypress.  From my short experience with it,  I don't see it as a good solution (for us anyways) for true end to end test scenarios.  It appears to be viable solution to isolate a small ui component and test it very lightly.  Even with the proper Promises in place,  we will have to sometimes rely on other mechanism to synchronise the tests (reloads, gets,  fixtures, waits...). 

For more complex scenarios, there are a lot of shortcuts and workaround involved that real users will never have to do and I'm afraid some bugs might fall in the cracks if Cypress is the only solution to test the UI.  Selenium webdriver will still show far more stable test results for us. 

As for retries,  they are dangerous to use and it's better to make the tests robust before even thinking of a retry mechanism.  But I don't see how to completely escape them in a continuous testing build environment. 

Still think Cypress is a beautiful beast.

**Comment by Bkucera** [comment] 2018-10-06 00:39
@itaykotler-fundbox yes, the Dashboard will mark build as failed, and CI will say pass. Once we implement retries for real, that problem should be solved :smile:

**Comment by fedxgibson** [comment] 2018-10-17 17:10
Looking forward to having this feature!

**Comment by monsteronfire** [comment] 2018-11-19 01:00
This feature will be so useful! +1

**Comment by filiphric** [comment] 2018-11-28 20:22
I’m kind of confused with Milestones here on github. Seems this is in a closed sprint but not yet released? Is this currently being worked on or is it done? What’s the estimate?

**Comment by chrisbreiding** [comment] 2018-12-03 17:16
Some initial work was completed on this, but there is still a good amount of work to be done. For the moment, the release of 4.0 and its features are being prioritized (it has some prerequisite work for this feature).

We recently started using milestones to track sprints (weekly work), which is why this is tagged with a closed milestone. I'm going to remove that milestone, since it's no longer relevant. When we start working on this again, we'll tag it with the latest sprint milestone. When this feature is complete, this issue will be closed and when it's released in a new version of Cypress, we'll post a message saying so.

**Comment by filiphric** [comment] 2018-12-03 20:04
@chrisbreiding thank you for the explanation 👍

**Comment by Phillipe-Bojorquez** [comment] 2018-12-04 14:38
I'm happy this will be worked on.  Currently, I'm using if-then blocks to collect failed tests to be re-run at the end of a spec-file completed run.

**Comment by matt212** [comment] 2018-12-06 13:44
@Phillipe-Bojorquez  do you have the re run structure script in handy in gist or something .

**Comment by daan-brixcrm** [comment] 2018-12-10 15:00
I am not an expert developer but i created a custom command which i use for retries. Maybe it is usefull and can be improved by someone. I use this for asynchronous actions where html elements will be updated without page refresh. In the example below i used it for checking a asynchronous save message after committing a form.

This custom command looks for an element within a wrapper. If it can not be found then it will wait 1 second and +1 the counter and retries itself. When the counter reaches 60 it will do a last lookup and will fail if the element is not present. If the element is present it will return true and continue to the next command.

```
Cypress.Commands.add("waitFor", (item, wrapper, counter) => {
	if(!counter){counter = 0;}
	var el = wrapper ? wrapper : 'body';
	cy.get(el).then(($body) => {
		if ($body.text().includes(item)) {
			return true;
		} else if (counter== 60){
			cy.get(el).find(item)
		} else {
			counter++;
			cy.wait(1000)
			cy.log("Wait for "+item + " in "+wrapper+ ". Counter: "+counter)
			cy.waitFor(item, wrapper, counter)
		}
	})
})
```

<img width="251" alt="sun-test-automation 2018-12-10 15-51-33" src="https://user-images.githubusercontent.com/38657927/49739981-7a79e100-fc93-11e8-836f-4f22066092d0.png">

**Comment by Phillipe-Bojorquez** [comment] 2018-12-11 23:33
@monsteronfire and @matt212 I mistyped I intended to write i'm going to have to use if-then blocks.  Still trying to figure out the best way to do it.  I assumed I could wrap up retry logic in an after each block.  Though I was wondering if it might be simpler to just use this module and require it at the spec level https://www.npmjs.com/package/mocha-retry

**Comment by NicholasBoll** [comment] 2018-12-14 06:04
One of the recent flaky failures we had was the `login` helper we use to auth pages through an API before visiting pages. Worked hundreds of times without failing, failing once caused the whole CI run to fail.

We'll look into the module API script for now. Still showing a test failing will help to know when/what is flaky. Sometimes it is a poorly written test, sometimes it is a complex system failing over something seemingly stable.

**Comment by debrisapron** [comment] 2018-12-21 17:59
For anyone still waiting for the lovely Cypress team to get around to this, we came up with a solution we really like. We were using @Bkucera's handy cypress-retries script, but it didn't work with our parallelized CI setup and we didn't like re-running the whole test file just to retry a single failed test, so we wrote this (somewhat hacky) little module:

```
if (Cypress.env('RETRIES')) {
  let skip = false;
  const _it = window.it;
  const _beforeEach = window.beforeEach;

  window.beforeEach = (...args) => {
    const beforeEachFn = args.pop();
    args.push(() => {
      if (!skip) beforeEachFn();
    });
    _beforeEach(...args);
  };

  window.it = (testName, testFn) => {
    if (!testFn) {
      _it(testName);
      return;
    }

    _it(`${testName} 🔄 1 of 3`, function() {
      skip = true;
      cy.on('fail', () => {
        skip = false;
        this.skip();
      });
      testFn();
    });

    _it(`${testName} 🔄 2 of 3`, function() {
      if (skip) this.skip();
      skip = true;
      cy.on('fail', () => {
        skip = false;
        this.skip();
      });
      testFn();
    });

    _it(`${testName} 🔄 3 of 3`, function() {
      const _skip = skip;
      skip = false;
      if (_skip) this.skip();
      testFn();
    });
  };

  window.it.skip = _it.skip;
  window.it.only = _it.only;
}
```

This simply monkeypatches `it` and `beforeEach` so that every test is tried three times. It obviously doesn't cover every use case but it works well for us. Just set the env variable `CYPRESS_RETRIES=true` & stick the code somewhere in your cypress support setup.

**Comment by Arnasnn** [comment] 2018-12-26 17:05
@debrisapron thanks for a hack, seems to work like a charm !

As for the feature this is necessary in our use cases !

**Comment by monsteronfire** [comment] 2019-01-02 05:38
@debrisapron Thank you! This appears to be working for me. 💟

**Comment by NicholasBoll** [comment] 2019-01-03 01:09
I created a module that will (hopefully) be able to go away once retries are officially supported. I took the code @Bkucera posted in a gist and made it a module.

Code: https://github.com/NicholasBoll/cypress-run 
npm: https://www.npmjs.com/package/cypress-run
Install: `npm install cypress-run -D`
Change `cypress run` to `cypress-run` in node scripts.

**Comment by bahmutov** [comment] 2019-01-03 01:45
Ha, @NicholasBoll I also wrote https://github.com/bahmutov/cypress-retry that retries failed spec but also modifies its source code to `it.only` the failed tests before rerunning. It is not polished, does not parse CLI arguments (all left as open issues for now), but could be useful as a starting point for PRs

**Comment by NicholasBoll** [comment] 2019-01-03 16:17
@bahmutov That's pretty interesting using file rewriting to only run the spec that failed (as opposed to the whole file). You could probably just remove the non-failing tests rather than skipping them to decrease the noise.

`cypress-run` is meant to be a simple drop-in replacement for doing `cypress run` - simply replace the space with a dash for CI (the module publishes `cypress-run` as a binary entry point).

```diff
-    cypress run --record --parallel --group ci --ci-build-id $BUILD_ID --key $CYPRESS_KEY
+    cypress-run --record --parallel --group ci --ci-build-id $BUILD_ID --key $CYPRESS_KEY
```

Do you think it is worth combining efforts?

**Comment by bahmutov** [comment] 2019-01-03 17:08
@NicholasBoll yeah, your script is really nice and just works. For my "retry" and for companion https://github.com/bahmutov/cypress-skip-and-only-ui I would justs keep them as novelties and things one can do completely in userspace. When actual built-in retries are added to the core of Cypress these modules would become unnecessary.

@NicholasBoll but we could definitely work on something useful, you know

**Comment by NicholasBoll** [comment] 2019-01-03 17:17
@bahmutov Cypress does not run any `it` blocks if a `beforeEach` fails. Cypress assumes that if a `beforeEach` fails, then `beforeEach` will fail for _all_ tests. Do you know if `cypress-retry` handles this case?

https://github.com/bahmutov/cypress-skip-and-only-ui is cool! I didn't think about using `support` to add UI elements. I might be able to implement Command Log Grouping in user-space to try out.

**Comment by jm2242** [comment] 2019-01-15 22:07
@debrisapron where did you put the script? I tried pasting into `support/index.js`, but I'm still getting my tests to fail after just 1 try. I also replaced `Cypress.env('RETRIES')` with `true` to make sure it wasn't my env setup that was messing with things.

Also does it work in development mode with `cypress open`?

**Comment by jm2242** [comment] 2019-01-16 01:45
Any success retrying a before() section?

**Comment by jiglesiasromero** [comment] 2019-01-18 10:55
> Ha, @NicholasBoll I also wrote https://github.com/bahmutov/cypress-retry that retries failed spec but also modifies its source code to `it.only` the failed tests before rerunning. It is not polished, does not parse CLI arguments (all left as open issues for now), but could be useful as a starting point for PRs

Hi @bahmutov how could run the code from your repo to check the retry?
Thanks!

**Comment by vcamposs** [comment] 2019-01-25 13:35
> For anyone still waiting for the lovely Cypress team to get around to this, we came up with a solution we really like. We were using @Bkucera's handy cypress-retries script, but it didn't work with our parallelized CI setup and we didn't like re-running the whole test file just to retry a single failed test, so we wrote this (somewhat hacky) little module:
> 
> ```js
> if (Cypress.env('RETRIES')) {
>   let skip = false;
>   const _it = window.it;
>   const _beforeEach = window.beforeEach;
> 
>   window.beforeEach = (...args) => {
>     const beforeEachFn = args.pop();
>     args.push(() => {
>       if (!skip) beforeEachFn();
>     });
>     _beforeEach(...args);
>   };
> 
>   window.it = (testName, testFn) => {
>     if (!testFn) {
>       _it(testName);
>       return;
>     }
> 
>     _it(`${testName} 🔄 1 of 3`, function() {
>       skip = true;
>       cy.on('fail', () => {
>         skip = false;
>         this.skip();
>       });
>       testFn();
>     });
> 
>     _it(`${testName} 🔄 2 of 3`, function() {
>       if (skip) this.skip();
>       skip = true;
>       cy.on('fail', () => {
>         skip = false;
>         this.skip();
>       });
>       testFn();
>     });
> 
>     _it(`${testName} 🔄 3 of 3`, function() {
>       const _skip = skip;
>       skip = false;
>       if (_skip) this.skip();
>       testFn();
>     });
>   };
> 
>   window.it.skip = _it.skip;
>   window.it.only = _it.only;
> }
> ```
> 
> This simply monkeypatches `it` and `beforeEach` so that every test is tried three times. It obviously doesn't cover every use case but it works well for us. Just set the env variable `CYPRESS_RETRIES=true` & stick the code somewhere in your cypress support setup.

Hello, @debrisapron . I'm sorry about a dumb question, but to use your script, i just need put in .js and run switch like "npm run e2e-test CYPRESS_RETRIES=true" ?

**Comment by jm2242** [comment] 2019-01-25 15:08
@vcamposs we are using the script and works great. We adding this to our `Cypress.json`:

```
{
...
  "env": {
    "RETRY_FAILED_TESTS": true
  },
"video": false,
...
}

```

then your script that you copy pasted into your `index.js` can start like this:
```
if (Cypress.env("RETRY_FAILED_TESTS")) {
...
```

**Comment by vcamposs** [comment] 2019-01-25 16:38
Great @jm2242 ! Run here! I Tks bro.

**Comment by jm2242** [comment] 2019-02-07 15:28
@Bkucera 	any chance your package retries failures in a `beforeAll()`?

**Comment by jm2242** [comment] 2019-02-07 15:36
@jennifer-shehane this would be such a great feature to help reduce flakiness. Is there an estimated timeline for this feature?

**Comment by Bkucera** [comment] 2019-02-07 15:40
@jm2242 not currently, I'll look into it.

**Comment by omullaev** [comment] 2019-02-07 20:16
> We're still working on this, but in the meantime I've made a hacky plugin you can try out [`cypress-plugin-retries`](https://github.com/Bkucera/cypress-plugin-retries):
> [![image](https://user-images.githubusercontent.com/14625260/52328975-716d6d80-29bf-11e9-86b7-6a013acfe1f1.png)](https://github.com/Bkucera/cypress-plugin-retries)
> 
> It's a similar to @debrisapron's solution but with a slightly cleaner UI, and it also retries failures in beforeEach hooks:
> ![image](https://user-images.githubusercontent.com/14625260/52328789-dd030b00-29be-11e9-8509-bdd8f410725c.png)
> 
> Let me know any bugs you notice in the issues of that repo.


Hello @Bkucera , 

Seems the feature does not mark broken tests as failed and mark them as pending and hence you always have successful report after tests even some of them failed.
<img width="351" alt="screen shot 2019-02-07 at 12 15 29 pm" src="https://user-images.githubusercontent.com/13217335/52440108-22642d00-2ad2-11e9-8159-44e9f1715207.png">

**Comment by Bkucera** [comment] 2019-02-07 21:17
@omullaev please open an issue in that repo, so we can leave this one for genuine updates on the feature

**Comment by amrwahdan3** [comment] 2019-05-23 19:43
thanks @Bkucera that plugin worked really well for us for beforeEach retries.
it also didnt create weird 'pending' result for the possible retries like another solution from above did.
so now i only have pass/fail. not pass/fail/skipped/pending which is much nicer.

**Comment by azaeng04** [comment] 2019-05-24 14:07
@Bkucera would it work for data driven tests as well?

**Comment by Bkucera** [comment] 2019-05-24 14:13
@azaeng04 yes

**Comment by OgnjenPetrovic** [comment] 2019-06-02 15:11
@Bkucera my retry setup just stoped to work, nothing has changed, just updated cypress to the last version, any ideas ?

**Comment by dwelle** [comment] 2019-06-03 13:48
@OgnjenPetrovic works fine for me

`cypress@^3.3.1`, `cypress-plugin-retries@^1.2.0`

```js
Cypress.env(
    `RETRIES`,
    Cypress.env(`RETRIES`) !== undefined
        ? Cypress.env(`RETRIES`)
        : (Cypress.browser.isHeaded ? 0 : 3)
);
```

**Comment by anujpin** [comment] 2019-11-19 12:52
@Bkucera, does it work with cypress cucumber as well? I added `env: { "retries": 2}` in `cypress.json` and `import 'cypress-plugin-retries';` in `/support/index.js`, but I don't see any retries happening. Any thoughts please?

**Comment by Bkucera** [comment] 2019-11-20 18:43
> rotating_light Do not comment on this issue about issues with the plugin rotating_light

@anujpin

**Comment by andersthorbeck** [comment] 2019-12-19 13:59
Is there any ETA on this feature, or estimate of roughly how much work remains?
This feature would make our continuous integration pipeline much more forgiving of random temporary network issues and other flakyness. 🙂

**Comment by mankybansal** [comment] 2020-01-09 20:06
Bump on this. What is the status of this feature? Eagerly waiting for reducing flakiness!

**Comment by luisasalas** [comment] 2020-01-11 00:04
^ I second that

**Comment by hilarykitz** [comment] 2020-01-13 16:43
Thirded 🙏

**Comment by germyjen** [comment] 2020-01-22 17:24
it's been roughly a year since the original feature request, any update on what's going on with this? Desperate for officially supported retries.

**Comment by dwelle** [comment] 2020-01-22 17:27
@germyjen don't think this is a top priority when there's a perfectly working workaround https://github.com/Bkucera/cypress-plugin-retries

**Comment by Algram** [comment] 2020-01-28 08:39
Hello there,
I just wanted to chime in and try to give you an understanding that this is currently a Number 1 issue and is actually costing you money:

We just had to switch from our 5000$ a year cypress plan to our own parallel implementation. This is due to the issues described above: You can't retry a cypress test reliably in a pipeline when using the `parallel` feature.

For us this even meant that once you retried a cypress test it always went "green", so we actually deployed failing stuff.

So this issue alone will cose you 5000$ a year now. I would be "SO" happy to pay you for your services, but as it is now, we cannot use your commercial product, even though we want to.

**Comment by Bkucera** [comment] 2020-01-31 17:31
not trying to minimize the importance of getting this in Cypress core. We hear you, it's up next to be worked on.

But since Github has started hiding comments didn't want the workaround above to get buried:

We're still working on this, but in the meantime I've made a plugin you can try out [`cypress-plugin-retries`](https://github.com/Bkucera/cypress-plugin-retries):
[![image](https://user-images.githubusercontent.com/14625260/52328975-716d6d80-29bf-11e9-86b7-6a013acfe1f1.png)](https://github.com/Bkucera/cypress-plugin-retries)


It supports mocha's `this.retries`, and it also retries failures in beforeEach 


### :rotating_light: Do not comment on this issue about issues with the plugin :rotating_light: 
**Let me know any bugs in the issues of the plugin repo.**

**Comment by Algram** [comment] 2020-02-01 10:10
@Bkucera this is not really a workaround, because one can still manually retry a test in e.g. GitLab und force it to pass, even if there are real errors that where introduced with this test.

Furthermore it only retries them automatically. Chances are high that the test failure was introduced by a third party system not being available. The plugin would not do anything for that kind of failure.

**Comment by lslee714** [comment] 2020-02-01 18:00
The plugin works well for us. @Algram if your tests are dependent on third party systems, you might re-think them... it's generally best practice to mock out external dependencies that you have no control over.

**Comment by tiennguyen-ftu-k52** [comment] 2020-02-21 03:57
I'm facing the same issue with @Algram. I'm trying to run cypress parallel on Bitbucket Pipelines and it's always green when you rerun failed step. I tried `cypress-plugin-retries` but it didn't help.

**Comment by sdwvit** [comment] 2020-08-06 14:48
any news on this?

**Comment by jm2242** [comment] 2020-08-06 15:24
It looks like the Cypress team is building out native support for retries, so stay tuned!

**Comment by msteward** [comment] 2020-08-07 20:44
Would recommend giving the feature an up vote on the Cypress roadmap: https://portal.productboard.com/cypress-io/1-cypress-dashboard/c/59-automatically-retry-failed-specs

**Closed** 2020-08-11 06:07 UTC
Labels: Epic, difficulty: 5️⃣, existing workaround, pkg/reporter, pkg/server, stage: pending release, type: feature

**Comment by jennifer-shehane** [comment] 2020-08-20 06:25
Test retries has been released in [`5.0.0`](https://on.cypress.io/changelog#5-0-0).

You can refer to our docs on [Test Retries](https://docs.cypress.io/guides/guides/test-retries.html) for instructions on how to turn on and configure test retries. 

We think this will be a valuable tool in helping identify flake and have more plans in the future to improve this feature and surface the test retries as well as analytics on flake into our Dashboard.

There are several options which we think are important to explore depending on your project including configuring globally, per `cypress open` and `cypress run` separately, or per test suite / single test.

If you encounter any errors using Test Retries, **please open a new issue with a fully reproducible example - do not comment in this thread as this issue is closed**.

**Comment by csvan** [comment] 2020-08-20 12:57
Awesome work @jennifer-shehane and team, you're the best <3

**Comment by Bkucera** [comment] 2020-08-20 15:32
for anyone coming from the retries plugin:
#### Migrating from cypress-plugin-retries to Cypress 5.0.0:

- remove cypress-plugin-retries from `devDependencies` and related code in support/plugin files
- remove usage of `Cypress.currentTest` in favor of test config overrides `it('test title', { retries: 2 }, () => {...})`
- remove usage of `this.retries(n)` (not supported)
- Set `retries` in `cypress.json` instead of using `Cypress.env('RETRIES')` (e.g. `{ "retries": { "openMode": 0, "runMode": 2 } }`)

**Comment by jennifer-shehane** [comment] 2020-08-25 06:08
The Dashboard now displays the screenshots and errors from each attempt of a test that retried. The test results are also filterable by whether they retried.

**Filter by whether test retried**

<img width="1470" alt="test-retries-filter copy" src="https://user-images.githubusercontent.com/1271364/91129249-afc89b80-e6cf-11ea-8618-6876e4b40d16.png">

**See screenshot and error for each attempt when clicking on test**

<img width="1470" alt="test-results-attempts" src="https://user-images.githubusercontent.com/1271364/91129281-c1aa3e80-e6cf-11ea-91d9-e5253b278d7a.png">

**Comment by bezba** [comment] 2020-09-23 23:19
> ```js
> retries: 2
> ```

```
How can I use that object in cucumber plugin ?
Given('the user is on accounts location page', () => {
    { retries: 3 }
    cy.get('#search').click().type('test').type('{enter}').wait(1000); --> if this fails I need to be able to retry this 3 times same step till the actual thing loads
    cy.get('table').contains('a', 'test').click().wait(3000); 
    
});
```
@jennifer-shehane  @Bkucera 
My current issue is that when I use cy.wait(3000) if the element  or request is not back by then it will fail the test. what I wanna achieve is to retry three times same steps if it failed at 3 seconds time out. is there anyway of doing this?
