### ISSUE TITLE
Issues with scrollIntoView and scrollTo in Chrome/Electron; No Issue in Firefox

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#8675] opened 2020-09-25 17:50 UTC
### Current behavior

When using Chrome/Electron, `.scrollIntoView()` and `.scrollTo('bottom')` are exhibiting some very flaky behaviour. These tests will pass on occasion but most often they fail as a result of scrolling that did not occur as expected.

### Desired behavior

`.scrollIntoView()` and `.scrollTo('bottom')` behave consistently and predictably.

### Test code to reproduce
```js
context('Cypress', function () {

  beforeEach(function () {

    // These are not real credentials.
    // Please sign up (for free) at www.vidyard.com, verify your email address, then update these accordingly.
    // You will also need to upload a video into your account before running this spec.

    const email = 'fake@qa.com'
    const password = 'Password123!'

    cy.visit('https://secure.vidyard.com/user/sign_in')
    cy.get('#username').type(email)
    cy.get('#password').type(password)
    cy.get('#sign-in').click()
    cy.get('.library-item').click()
    cy.wait(5000) // Just to make sure the page is fully loaded.
  })

  it('scrollIntoView', function () {
    cy.get('.access-settings')
      .scrollIntoView()
    cy.get('.access-settings > .vy-card__content')
      .find('.vy-button')
      .click();
  });

  it('scrollTo', function () {
    cy.scrollTo('bottom')
    cy.get('.access-settings > .vy-card__content')
      .find('.vy-button')
      .click();
  });
});
```

These tests will pass occasionally:

![image](https://user-images.githubusercontent.com/62152998/94296146-5d79d500-ff30-11ea-800c-b32b3e3e6ff2.png)

But most often you will find that the tests fail on the `.click()` action since it isn't visible onscreen as a result of the scroll action not taking place as expected.

![image](https://user-images.githubusercontent.com/62152998/94298112-8e0f3e00-ff33-11ea-91f8-21e5952c149b.png)

### Stack trace

```
CypressError: Timed out retrying: `cy.click()` failed because the center of this element is hidden from view:

`<button data-v-7312bdba="" data-v-e33a336a="" type="button" class="vy-button vy-button--default is-centred" aria-labelledby="access-setting-title" aria-describedby="access-setting-description">...</button>`

Fix this problem, or use `{force: true}` to disable error checking.
    at $Cy.ensureDescendents (https://www.vidyard.com/__cypress/runner/cypress_runner.js:161610:24)
    at ensureDescendents (https://www.vidyard.com/__cypress/runner/cypress_runner.js:150141:8)
    at ensureDescendentsAndScroll (https://www.vidyard.com/__cypress/runner/cypress_runner.js:150148:14)
    at ensureElIsNotCovered (https://www.vidyard.com/__cypress/runner/cypress_runner.js:150277:5)
    at runAllChecks (https://www.vidyard.com/__cypress/runner/cypress_runner.js:150414:52)
    at retryActionability (https://www.vidyard.com/__cypress/runner/cypress_runner.js:150429:16)
From previous event:
    at tryFn (https://www.vidyard.com/__cypress/runner/cypress_runner.js:165710:24)
    at whenStable (https://www.vidyard.com/__cypress/runner/cypress_runner.js:165751:12)
    at https://www.vidyard.com/__cypress/runner/cypress_runner.js:165269:16
From Your Spec Code:
    at Context.eval (https://www.vidyard.com/__cypress/tests?p=cypress/integration/cypress.spec.js:116:71)
```

### Versions

Cypress version 5.1.0 on macOS 10.15.6 with Chrome 85.

When using the same Cypress/macOS versions with Firefox 81, *the tests will consistently pass every time.*

**Comment by jennifer-shehane** [comment] 2020-09-29 05:13
With the code provided, after logging in, it does not find a 'library-item' element. Please provide all steps required to reproduce this from scratch. 

<img width="1471" alt="Screen Shot 2020-09-29 at 11 42 01 AM" src="https://user-images.githubusercontent.com/1271364/94515146-f23e4480-0248-11eb-8d1a-a14914ab015d.png">

**Comment by todd-m-kemp** [comment] 2020-09-29 12:30
Hi @jennifer-shehane; thanks for taking a look. It looks like you missed the necessary prerequisite step of uploading a video into your account before running the spec. I did mention this in the original description

> // You will also need to upload a video into your account before running this spec.

but perhaps I didn't highlight it enough. If you upload a video into your account and run the spec again, there should be no difficulty in locating the `library-item` element.

Thanks again.

**Comment by idanRiski** [comment] 2020-10-08 21:43
Happens to me as well in cy 5.2 + chrome 85.

**Comment by jennifer-shehane** [comment] 2020-10-09 10:03
Yah I did miss that step. Sorry.

I do see this tests provided pass in Firefox and fail in Chrome. 

This is a duplicate of #3200. It's actually not an issue with the 'scrollIntoView', you don't actually need to scroll to the element to click it. The issue is when you try to click it doesn't properly automatically scroll (which Cypress does for you) because you have `scroll-behavior:smooth` on the html. There are some workarounds in that issue where you can remove the style during tests.

**Closed by jennifer-shehane** 2020-10-09 10:03 UTC
Labels: stage: needs information, topic: scrolling ↕️

**Comment by todd-m-kemp** [comment] 2020-10-09 18:27
Hi @jennifer-shehane; no worries at all! Thanks for taking another look.

I will give the workaround suggested in #3200 a try. That said, I personally believe that  fix for this issue would be a worthwhile enhancement. The use of `smooth` for `scroll-behavior` is extremely commonplace and I would expect Cypress to be handle this out of the box with no workarounds required. 😄

**Comment by islami00** [comment] 2023-10-05 09:23
I experienced this clicking on a row of a table in a modal with a sticky header in Cypress `v12.17.4 `, only on Electron (which was on `v106`). 
Updating to cypress v13.3.0 (which has electron `v114`) fixed this for me, it seems to be a problem with the bundled version of browsers at times.

Similar issue as #4233
