### ISSUE TITLE
cy.fixture removes trailing zeroes from number values

### ISSUE THREAD

**Issue by jprealini** [cypress-io/cypress#8110] opened 2020-07-28 19:00 UTC
### Current behavior:

When using a json file with some properties that have values with decimals ( i.e. "price" : 890.90 ) for a fixture, cy.fixture() returns that value with trailing zeroes removed... 

After some research I found that this is something that comes from JSON.parse (which I understand is executed automatically inside cy.fixture() if the fixture file has a .json extension, as per https://github.com/cypress-io/cypress/issues/7412 )... 

JSON.parse will remove the trailing zeroes in decimal part of a number unless specified ( https://github.com/JamesNK/Newtonsoft.Json/issues/2162 )

### Desired behavior:

cy.fixture() should allow to pass an option to keep trailing zeroes when parsing json fixture files

### Test code to reproduce

fixture file "file.json":
```json
{
    "results": [
        {
            "currency": "STD",
            "amount": 174.40,
            "paymentMethod": "AMEX",
            "status": 2,
            "date": "2020-01-07T09:23:30.46311+00:00",
            "storeId": "Store3",
            "terminalId": "TER4",
            "merchantId": "Sony Store",
            "action": null,
            "cardNumber": "****-****-****-4377",
            "expirationDate": "2020-07-14T15:09:13.8991218+00:00",
            "customerEmail": "M59@gmail.com",
            "order": {
                "id": "d2f9e598-90e3-499e-b723-b81b833652e0",
                "description": "Generic Metal Chicken",
                "customerId": "4a1dbbe9-141b-4671-8b8c-d85bd4a20095",
                "customerName": "Miriam H",
                "shippingAddress": "792 N, Palestinian Territory",
                "shippingStatus": "Delivered"
            },
            "authorization": {
                "authorizationCode": null,
                "currency": "STD",
                "amount": 174.40,
                "authorizationResponse": null,
                "status": 2,
                "date": "2020-01-07T09:23:30.46311+00:00",
                "operationReference": "3db6a4f1-1c91-471f-8cf7-3d60c99b3e0e",
                "cardCountry": "Mozambique",
                "description": "Generic Metal Chicken"
            },
            "id": "5f202ac54885560001de7100",
            "createdAt": "0001-01-01T00:00:00+00:00"
        }
    ]
}
```

Picking up this json file in a fixture you will verify that the amount is shown as 174.4 instead of 174.40

As a workaround, I have to rename the file as "file" (without any extension) and then it gets parsed correctly

### Versions

Cypress 4.11
Windows 10
Testing against Chrome 84

**Comment by jennifer-shehane** [comment] 2020-07-29 08:59
Duplicate of https://github.com/cypress-io/cypress/issues/5395

If you'd like, it'd be helpful to explain how you are using the fixture in this issue's comments #5395 - where this is causing an issue in the testing of your application? 

Just my preliminary simple assertion below passes, even though the Number does not show trailing zeros. So, just want some further context on a situation where the assertion is unexpected/wrong. Using a non-JSON file, it's all a returned string. 

`spec.js`

```js
it('Fixture with trailing zeros', () => {
  cy.fixture('amount.json').then((fx) => {
    expect(fx.amount).to.eq(174.40)
  })
})
```

`amount.json`

```json
{
  "amount": 174.40
}
```

**Closed by jennifer-shehane** 2020-07-29 08:59 UTC
