### ISSUE TITLE
cy.route not matching edited network request

### ISSUE THREAD

**Issue by tophmey** [cypress-io/cypress#4659] opened 2019-07-05 16:59 UTC
### Current behavior:

When editing a request with axios interceptors, cypress routes match against the unedited request

### Desired behavior:
`cy.route` should match against the final request including any modifications made by axios or anything else

### Steps to reproduce: (app code and test code)

Making a request `/api/pathA` and use an axios interceptor to rewrite the url to `/api/pathA?value=true`. `cy.route` should match on `/api/pathA?value=true` but it is not, it is only matching `/api/pathA`

### Versions

3.3.2, Mac OS

**Comment by gabbersepp** [comment] 2019-07-08 09:12
Can you please provide a minimal runnable example? Would be nice. No idea how to use the interceptors

**Comment by jennifer-shehane** [comment] 2019-07-08 09:56
@tophmey Yes, provide reproducible example as @gabbersepp said and also provide the test code you are running.

**Comment by tophmey** [comment] 2019-07-12 20:56
Sure, here you go.

Example Code
```
axios.interceptors.request.use(function (config) {
  return {
    ...config,
    url: config.url + '?value=true',
  }
});

function getData() {
  axios.get('/api/pathA');
}
getData();
```

Test Code
```
describe('the app', () => {
  cy.server();
  cy.route({
    method: 'GET',
    url: `/api/pathA?value=true',
  }).as('getData');
  it('should get the data', () => {
    cy.wait('@getData').then((xhr) => {
      expect(xhr.request.url).to.equal('/api/pathA?value=test');
    })
  })
});
```

**Comment by gabbersepp** [comment] 2019-07-15 10:05
> Sure, here you go.
> 
> Example Code
> 
> ```
> axios.interceptors.request.use(function (config) {
>   return {
>     ...config,
>     url: config.url + '?value=true',
>   }
> });
> 
> function getData() {
>   axios.get('/api/pathA');
> }
> getData();
> ```
> 
> Test Code
> 
> ```
> describe('the app', () => {
>   cy.server();
>   cy.route({
>     method: 'GET',
>     url: `/api/pathA?value=true',
>   }).as('getData');
>   it('should call the correct endpoint', () => {
>     cy.wait('@getData').then((xhr) => {
>       expect(xhr.request.url).to.equal('/api/pathA?value=test');
>     })
>   })
> });
> ```

I tested your example here:
https://github.com/gabbersepp/cypress-test-tiny/tree/issue-4659-route-not-matching
Everything is green.

Things I had to change:

- move the cy.server() stuff into the it() callback, otherwise cypress is throwing an error
- use xhr.url instead of xhr.request.url. No idea why `request` is not a property in my case

**Comment by jennifer-shehane** [comment] 2020-10-20 08:13
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2020-10-20 08:13 UTC
Labels: stage: needs information
