### ISSUE TITLE
Cypress 4.3.0 "Error: Corrupted download" during install on Circle CI

### ISSUE THREAD

**Issue by saschwarz** [cypress-io/cypress#6953] opened 2020-04-07 03:39 UTC
### Current behavior:

This started happening in the last 4 hours when we try to install cypress 4.3.0 via yarn on CircleCI. 4.3.0 installs locally without error. We were also stable installing on CircleCI using cypress 4.2.

Output of docker image creation:

```
Step 7/9 : RUN yarn install
 ---> Running in b0d68d675fc5
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@vue/eslint-config-standard > eslint-import-resolver-webpack@0.12.1" has unmet peer dependency "webpack@>=1.11.0".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
error /app/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /app/node_modules/cypress
Output:
Installing Cypress (version: 4.3.0)

[03:27:29]  Downloading Cypress     [started]
[03:27:30]  Downloading Cypress      0% 0s [title changed]
[03:27:30]  Downloading Cypress      1% 10s [title changed]
[03:27:30]  Downloading Cypress      2% 10s [title changed]
[03:27:30]  Downloading Cypress      4% 8s [title changed]
[03:27:30]  Downloading Cypress      7% 6s [title changed]
[03:27:30]  Downloading Cypress      10% 5s [title changed]
[03:27:30]  Downloading Cypress      12% 5s [title changed]
[03:27:30]  Downloading Cypress      14% 4s [title changed]
[03:27:31]  Downloading Cypress      17% 4s [title changed]
[03:27:31]  Downloading Cypress      22% 3s [title changed]
[03:27:31]  Downloading Cypress      26% 3s [title changed]
[03:27:31]  Downloading Cypress      33% 3s [title changed]
[03:27:31]  Downloading Cypress      39% 2s [title changed]
[03:27:31]  Downloading Cypress      43% 2s [title changed]
[03:27:31]  Downloading Cypress      48% 2s [title changed]
[03:27:31]  Downloading Cypress      55% 1s [title changed]
[03:27:31]  Downloading Cypress      60% 1s [title changed]
[03:27:32]  Downloading Cypress      67% 1s [title changed]
[03:27:32]  Downloading Cypress      72% 1s [title changed]
[03:27:32]  Downloading Cypress      76% 1s [title changed]
[03:27:32]  Downloading Cypress      81% 1s [title changed]
[03:27:32]  Downloading Cypress      89% 0s [title changed]
[03:27:32]  Downloading Cypress      93% 0s [title changed]
[03:27:32]  Downloading Cypress      98% 0s [title changed]
[03:27:34]  Downloading Cypress      98% 0s [failed]
[03:27:34] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.3.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: c2ad1521a91cdec2228b0f855c3f3a7a96210edc2af467877fcf160d97fee87fdc68461a89d905c223f22c4f5638d4489113af703e8fe10dff4a1ac50a84c7e1
Computed checksum: 3a177c02c7d4f186102a833aaf952d17942d5c855a70c5e2e73a46ea5f5df6cc0e28ee31a584adb150c6762f181bd0ab3bf1295ed5af00d5b5eb19c429fcabc5

Expected downloaded file to have size: 170191434
Computed size: 170191434

----------

Platform: linux (Debian - 9.11)
Cypress Version: 4.3.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.3.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: c2ad1521a91cdec2228b0f855c3f3a7a96210edc2af467877fcf160d97fee87fdc68461a89d905c223f22c4f5638d4489113af703e8fe10dff4a1ac50a84c7e1
Computed checksum: 3a177c02c7d4f186102a833aaf952d17942d5c855a70c5e2e73a46ea5f5df6cc0e28ee31a584adb150c6762f181bd0ab3bf1295ed5af00d5b5eb19c429fcabc5

Expected downloaded file to have size: 170191434
Computed size: 170191434

----------

Platform: linux (Debian - 9.11)
Cypress Version: 4.3.0
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1

Exited with code exit status 1
CircleCI received exit code 1
```
### Desired behavior:

Installs without error

### Test code to reproduce

This occurs prior to running tests.

### Versions

Cypress 4.3.0 Debian 9.11

**Comment by jennifer-shehane** [comment] 2020-04-07 06:13
This is likely an expression of this issue: https://github.com/cypress-io/cypress/issues/4595 Where you can have multiple versions of Cypress downloaded at the same time - possibly causing a corrupt download. This can happen in Yarn workspaces sometimes. 

Duplicate of #6789

**Closed by jennifer-shehane** 2020-04-07 06:13 UTC
