### ISSUE TITLE
How can I upload picture?

### ISSUE THREAD

**Issue by Mrshenxh** [cypress-io/cypress#4291] opened 2019-05-23 09:41 UTC
I just want to upload picture in my program!

**Comment by jevors** [comment] 2019-05-24 07:02
Duplicate of https://github.com/cypress-io/cypress/issues/170 in that ticket are multiple work arounds that may work for you.

**Closed** 2019-05-24 07:11 UTC
Labels: type: duplicate

**Comment by Mrshenxh** [comment] 2019-07-24 05:29
Thanks
