### ISSUE TITLE
Not able to upload File Since 3.4.1 version

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#6577] opened 2020-02-27 09:52 UTC
### Current behavior:

Fileupload functionality was working fine till 3.4.1 but for all the later version till the latest version. It has stopped working. No error but file is not getting uploaded

### Desired behavior:

File should get uploaded and subsequent server call should trigger when the file is uploaded. 

### Test code to reproduce
Kindly host the given html in the local IIS and add any image with the name as "testingimage.jpg" under Fixture folder of cypress.
I have added the code which when upload the file add the Console.log as true. But in the given example when running with Cypress latest version i.e v4.0.2 (as of now). there isn't console.log as true. 

But, when you manually upload a file, there is console.log

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<input type="file" id="file">
	<input type="button" id="load" value="Load File">
	<script>
		function addListener(element, eventName, handler) {
		  if (element.addEventListener) {
		    element.addEventListener(eventName, handler, false);
		  }
		  else if (element.attachEvent) {
		    element.attachEvent('on' + eventName, handler);
		  }
		  else {
		    element['on' + eventName] = handler;
		  }
		}

		addListener(document.getElementById('file'), 'change', function() {
			console.log(this.files[0] instanceof File);
		});


		addListener(document.getElementById('load'), 'click', function() {
			var file = new File(['content'], 'sample1.txt', {type: "text/txt"});
        	var dataTransfer = new DataTransfer();
        	dataTransfer.items.add(file);

        	var fileInput = document.getElementById("file");
        	fileInput.files = dataTransfer.files;
        	console.log(fileInput.files[0] instanceof File);
    	});
	</script>
</body>
</html>
```
```ts
context('Tests', () => {
  
  it('cy.fixture() - load a fixture', () => {
    cy.server();
    cy.visit("http://localhost:8012/");
    const test = "0";
    const fixtureFileName = "testingimage.jpg";
    const fileType = "image";
    cy.fixture(fixtureFileName, "base64").then((image) => {
      cy.get("input[type=file]").then((subject: any) => {
        Cypress.Blob.base64StringToBlob(image, fileType)
          .then(blob => {
            const el = subject[0];
            const testFile = new File([blob], fixtureFileName, { type: fileType });
            const dataTransfer = new DataTransfer();
            dataTransfer.items.add(testFile);
            el.files = dataTransfer.files;
          });
      });
    });
  });
});
```

### Versions

Cypress:  4.0.2 or any version > 3.4.1
Browser: Chrome(79) and Electron (78)
Operating System: Windows 10

**Comment by artemisclyde** [comment] 2020-02-27 16:18
Same problem, would greatly appreciate if someone could help!

**Comment by jennifer-shehane** [comment] 2020-02-28 06:21
Duplicate of #6490 

Although we never did fully support file upload as noted in https://github.com/cypress-io/cypress/issues/170, so it's not something we test for on updates. It's technically not a bug since it was never supported. Tracking in #6490 nonetheless.

**Closed by jennifer-shehane** 2020-02-28 06:21 UTC
