### ISSUE TITLE
Kindly suggest any approach instead of pass url to each it() block in a spec file while using cy.session() to login

### ISSUE THREAD

**Issue by venkatch189** [cypress-io/cypress#28767] opened 2024-01-22 12:31 UTC
### What would you like?

using "cypress": "^13.6.0"

using cy.session() to store the session.
![Screenshot 2024-01-22 121802](https://github.com/cypress-io/cypress/assets/153659517/2428c3cb-51e0-48c2-898a-9c24a421588e)

calling Login command in the beforeEach() hook and visiting the url

How to avoid pass url to each it() block ?
because i need to continue on the same navigation in the second it() block without passing url again. is there any work around or config changes required ?
![Screenshot 2024-01-22 122442](https://github.com/cypress-io/cypress/assets/153659517/c284da7a-31eb-4baf-be8e-59dbfab91eb0)

### Why is this needed?

Recently migrated to Cypress V13.6.0 from old version V6.6.0 and i have around 100 specs and each spec has got 10 - 15 it() blocks. pass url each time consume more time to load page and i have to navigate again where i left in the each it() block.

**Comment by jennifer-shehane** [comment] 2024-01-22 14:23
@venkatch189 If you don't want to use test isolation, where you have to visit on every it block, you can set `testIsolation: false` in your Cypress config. We don't recommend testing in this way because tests state can bleed over into other tests and cause for flake, but it is an option. https://on.cypress.io/test-isolation

I'll close this issue since it's a question and is not a bug. You can ask further questions in [our discord](https://on.cypress.io/chat).

**Closed as completed by jennifer-shehane** 2024-01-22 14:23 UTC
Labels: type: question

**Comment by venkatch189** [comment] 2024-01-22 15:16
Thanks @jennifer-shehane
