### ISSUE TITLE
Tests keep failing in headless mode

### ISSUE THREAD

**Issue by munjal-patel** [cypress-io/cypress#5098] opened 2019-09-06 20:39 UTC
I have a very simple test which passes on local machine in browser (both Chrome and Electron).

```js
describe('unauthenticated user', () => {
  it('should get redirected to /signin when navigating to a non public page', () => {
    cy.visit('/')
    cy.wait(10000)
    cy.location('pathname').should('equal', '/signin')
  })
})

describe('authenticated user', () => {
  it('should get redirected to /verify-email if email is not verified', () => {
    cy.visit('/signin')
    cy.get('input[name="username"]').type(Cypress.env('UNVERIFIED_USER_EMAIL'))
    cy.get('input[name="password"]').type(Cypress.env('UNVERIFIED_USER_PASS'))
    cy.get('.signin').click()
    cy.location('pathname').should('equal', '/verify-email')
  })
})
```

However, when I run the same test using `./node_modules/.bin/vue-cli-service test:e2e --headless` I keep getting the following errors:

```
1) unauthenticated user should get redirected to /signin when navigating to a non public page:
     CypressError: Timed out retrying: expected '/' to equal '/signin'
      at Object.cypressErr (http://localhost:8081/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://localhost:8081/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://localhost:8081/__cypress/runner/cypress_runner.js:85335:17)
      at retry (http://localhost:8081/__cypress/runner/cypress_runner.js:77321:16)
      at onFailFn (http://localhost:8081/__cypress/runner/cypress_runner.js:68422:16)
      at tryCatcher (http://localhost:8081/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://localhost:8081/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://localhost:8081/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://localhost:8081/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://localhost:8081/__cypress/runner/cypress_runner.js:117075:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8081/__cypress/runner/cypress_runner.js:113687:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>

  2) authenticated user should get redirected to /verify-email if email is not verified:
     CypressError: Timed out retrying: Expected to find element: 'input[name="username"]', but never found it.
      at Object.cypressErr (http://localhost:8081/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://localhost:8081/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://localhost:8081/__cypress/runner/cypress_runner.js:85335:17)
      at retry (http://localhost:8081/__cypress/runner/cypress_runner.js:77321:16)
      at onFailFn (http://localhost:8081/__cypress/runner/cypress_runner.js:68422:16)
      at tryCatcher (http://localhost:8081/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://localhost:8081/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://localhost:8081/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://localhost:8081/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://localhost:8081/__cypress/runner/cypress_runner.js:117075:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8081/__cypress/runner/cypress_runner.js:113687:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>
```

Here are the screenshots:

![image](https://user-images.githubusercontent.com/51474446/64458720-ee260e80-d0aa-11e9-9697-3fc4b8aa473e.png)

![image](https://user-images.githubusercontent.com/51474446/64458741-fbdb9400-d0aa-11e9-9880-2268ff595f3c.png)

**Comment by jennifer-shehane** [comment] 2019-09-09 17:56
There are a lot of reasons tests could fail in CI and pass locally.

Some reasons this could happen:

1. There is a problem isolated to the Chrome version of our Electron browser. We're working on updating it every day. https://github.com/cypress-io/cypress/pull/4720 Installing a later Chrome version in Travis would highlight if this is your problem.
2. If there is a build process in between running tests locally and running in CI - sometimes Cypress test failures are highlighting a bug in the build process.
3. Variability in timings when running your application in CI. If you have a test that will only pass when a network request finishes in 10ms (which happens every time on your local machine) and then that request takes 20ms on your CI machine (for whatever reason from that machine - location, CPU, etc slows it down) - this can cause some unexpected failures. You'll want to make sure to write assertions around the important steps that need to be reached before moving on to the next action in your tests. for example - ensuring a network request has finished before looking for the DOM element that relies on the data from that network request. I would suggest reviewing the video of the test failures, looking at the timings of commands and actions in the Command Log, and comparing them to your local run's Command Log to highlight if this is the issue.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-09-09 17:56 UTC

**Comment by anveshpuli** [comment] 2020-03-24 21:30
Facing same issue has it been resolved ??? @jennifer-shehane

**Comment by anveshpuli** [comment] 2020-03-25 16:11
is this issue fixed ? @jennifer-shehane @munjal-patel

**Comment by jennifer-shehane** [comment] 2020-03-26 10:14
@anveshpuli This issue was closed because we cannot reproduce it. Please see https://github.com/cypress-io/cypress/issues/5098#issuecomment-529594760

If you're seeing tests fail in `cypress run` and not in `cypress open` - refer to our debugging guide. https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI
