### ISSUE TITLE
[7.0.0] Vue Component testing - Doesn't display list of specs in Cypress Component Test Runner

### ISSUE THREAD

**Issue by xanxuz** [cypress-io/cypress#15846] opened 2021-04-07 13:28 UTC
### Current behavior

Tried to test a component with the initial HelloWorld.vue component with a HelloWorld.spec.js file but the test runner doesn't display the test

### Desired behavior

Being able to test a Vue component with Cypress Component Test Runner

### Test code to reproduce
Here is a repo with a fresh vue-cli project with cypress@7.0.0, you just have to run
```bash
yarn cypress open-ct
```
[https://github.com/xanxuz/vue-cypress-ct](https://github.com/xanxuz/vue-cypress-ct)

### Versions
Cypress version - 7.0.0
Operating System - Windows 10
Node version - v15.14.0

**Comment by agg23** [comment] 2021-04-07 13:42
Thank you for your report. Are you receiving any errors in either the browser console or in the terminal that you ran `yarn cypress open-ct`? I expect your issue is a duplicate of #15842, but I want to make sure.

**Comment by xanxuz** [comment] 2021-04-07 14:02
Hi @agg23, I think it could be a duplicate because the console printed something similar

![image](https://user-images.githubusercontent.com/11968584/113878868-fdd66f00-9787-11eb-9d3e-12a48189ad89.png)
![image](https://user-images.githubusercontent.com/11968584/113878981-16df2000-9788-11eb-8b28-c63f349a2787.png)
![image](https://user-images.githubusercontent.com/11968584/113879055-28c0c300-9788-11eb-9748-599275c28b3f.png)
![image](https://user-images.githubusercontent.com/11968584/113879278-59086180-9788-11eb-8f54-01043326fcaa.png)

**Comment by agg23** [comment] 2021-04-07 14:04
Dupe of #15842

**Closed by agg23** 2021-04-07 14:04 UTC
Labels: component testing, type: duplicate
