### ISSUE TITLE
Cypress tests when run in the background (in interactive mode) become extremely flakey

### ISSUE THREAD

**Issue by TransmissionsDev** [cypress-io/cypress#6471] opened 2020-02-15 06:44 UTC
### Current behavior:

Cypress tests when run in the background (in interactive mode) become extremely flakey.

When I'm working on my tests and I have the Cypress test runner open behind VSCode (on macos), and I go back to the tests after they auto run on save, I get weird errors when asserting that text should be visible, saying that the text is in the document but is not visible.

However, this does not happen outside of interactive mode, or when I rerun the tests when the runner is the primary focus.

### Desired behavior:

Tests should perform the same when run in the background (in interactive mode), as they do when the test runner's window is the primary focus?

Cypress: 4.0.2, MacOS El Capitan, Chrome (Interactive Mode!)

**Comment by jennifer-shehane** [comment] 2020-02-18 05:39
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-02-18 05:39 UTC

**Comment by BirgitPohl** [comment] 2020-04-02 12:54
Can I re-open this one by providing more information?

Let me give you a website and some code to reproduce

I have a container ".**wl-modal__frame**" that slowly moves from bottom to top when you click on the heart icon at the top. It doen't matter if you have bookmarked items or not.

<img width="1187" alt="Screenshot 2020-04-02 at 13 56 32" src="https://user-images.githubusercontent.com/4340405/78246982-55455d80-74ea-11ea-8fa5-861ec7fd3d32.png">

Following is are the only dependencies and package.json configs:
```json
"devDependencies": {
    "cypress-cucumber-preprocessor": "^2.0.1",
    "cypress": "^4.2.0",
  }
```

- Chrome 80 in Cypress interactive mode
- MacOS Catalina 10.15.3 on a Mac Book Pro 15'' 2017
- 2,5GHz Quad Core intel Core i7

I use Cucumber as you can see. But I can provide snippets for Cypress only too.
Of course, implementing Cucumber as a plugin: plugins/index.js

```javascript
module.exports = (on, config) => {
  on("file:preprocessor", cucumber());
};
```
Code snippets you need:
```javascript
When(/^I visit Sonnenklar$/, () => {
  cy.visit("https://www.sonnenklar.tv/")
    .get("body").should("be.visible");
});

When(/^I click on the Wishlist Icon$/, () => {
  cy.scrollTo(0, 0)
    .get(".wl-main-button:visible")
    .first()
    .should("be.visible")
    .click()
    .wait(1000); //shouldn't be here, but just to be sure, that it is a timing issue
});

Then(/^I see the Wishlist$/, () => {
  cy.get(".wl-modal__frame").should("be.visible");
});
```

```gherkin
When I visit Sonnenklar
When I click on the Wishlist Icon
Then I see the Wishlist
```

**Comment by jennifer-shehane** [comment] 2020-04-23 07:04
@BirgitPohl I can recreate this issue. Your issue is a duplicate of #5023 - see that issue for updates.
