### ISSUE TITLE
Errors on execution on Azure Pipeline agent

### ISSUE THREAD

**Issue by conventim** [cypress-io/cypress#23641] opened 2022-08-31 12:57 UTC
### Current behavior

I run `cypress run --config-file cypress/cypress.json "--spec" "<feature>"` on  Azure Pipeline with ubuntu-20.04 and i get these errors multiple times during the execution

```
[2087:0829/183107.750912:ERROR:gl_utils.cc(319)] [.WebGL-0x12b206a24e00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
[1932:0829/183111.127994:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183111.128616:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183111.129073:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183121.910715:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183121.911309:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183121.911747:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183128.769939:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183128.773302:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183128.773874:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183209.188560:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183209.189283:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183209.189991:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183219.127901:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183219.129012:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183219.129786:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[2087:0829/183222.384877:ERROR:gl_utils.cc(319)] [.WebGL-0x12b20561d500]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
[1932:0829/183225.717271:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183225.718114:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183225.718822:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183234.561254:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183234.562087:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1932:0829/183234.565250:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
```

i get also certificate errors multiple times like these

`[1964:0831/124215.831417:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for <url> failed:
----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=<url>) -----
ERROR: No matching issuer found`

### Test code to reproduce

The errors are present even if i try to run a test on www.google.com and search something

### Cypress Version

9.7

### Node version

12.22.12

### Operating System

ubuntu 20.04.4

**Comment by alpenite-mconventi** [comment] 2022-08-31 13:49
I need to add also that I notice an execution time increase (i can't provide some data because i changed test steps) from cypress 6.5 to cypress 9.7

**Comment by lmiller1990** [comment] 2022-09-01 02:12
Hi - please give me some time to try and reproduce, will need to procure an Azure account and try replicate it. Do you have a Docker image or something potentially that might speed things up?

Since it might be faster for you to debug - can you try

1) Consider updating to the latest - Cypress 10 - possibly we fixed the bug already?
2) 6.5 -> 9.7 is a big jump - if you can try moving to 7.x -> 8.x -> 9.x, you might be able to isolate the point the bug was introduced (assuming Cypress bug)

Thanks!

**Comment by alpenite-mconventi** [comment] 2022-09-01 07:17
Hi,
I m trying to update to Cypress 10 but i m facing some problems. 
I don't have a Docker image, i m using Azure Pipeline cloud agent
You need to configure the yml file with this on top
`pool:
  vmImage: 'ubuntu-20.04'
`
I'll keep you updated if I complete the cypress 10 update

**Comment by alpenite-mconventi** [comment] 2022-09-01 15:24
I tried to update Cypress to version 10.7 but i m facing this problem
<img width="606" alt="Schermata 2022-09-01 alle 17 08 14" src="https://user-images.githubusercontent.com/45484365/187950091-b34400f7-89f7-4cc4-aec5-88769c738049.png">

this is the step definition structure
![image](https://user-images.githubusercontent.com/45484365/187950318-6e867978-2bf0-4c20-96ea-38382ebd4e29.png)

this is the feature test structure
<img width="529" alt="image" src="https://user-images.githubusercontent.com/45484365/187950824-b01342df-2f4d-4fc7-b674-97316b35ac85.png">

this is the package.json
<img width="742" alt="image" src="https://user-images.githubusercontent.com/45484365/187951516-a903298a-a050-4b80-84a7-21d0d2f387cb.png">

the `specPattern` parameter in `cypress.config.js` has this value `specPattern: 'cypress/e2e/**/*.feature'`
Can you help me even if the problem is on cucumber config?
Thanks a lot

**Comment by lmiller1990** [comment] 2022-09-02 00:35
It looks like v4 of the Cypress Cucumber library is not maintained, there's a maintained fork here: https://github.com/badeball/cypress-cucumber-preprocessor. You probably want to grab that one (check their release notes for how to update to Cypress 10).

**Comment by alpenite-mconventi** [comment] 2022-09-02 16:01
HI @lmiller1990, i created a simple project based on cypress `10.7.0` **WITHOUT** cucumber plugin and i created a test where i browse to www.wikipedia.org and search something.
There are no errors on Azure Pipeline run, so on Monday i'll try to repeat the test moving Cypress to `9.7.0`

**Comment by alpenite-mconventi** [comment] 2022-09-05 10:18
I tried to test cypress 10.7 without cucumber on the site i usually run the test and i still have these errors
`[1843:0905/101108.835981:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101108.836205:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101108.836386:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101143.719907:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101143.721723:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101143.722279:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101159.774535:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101159.774778:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1843:0905/101159.774970:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
`

I see that using cypress 10.7.0 without cucumber there are no certificate errors (this i mean `[1964:0831/124215.831417:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for <url> failed: ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=<url>) ----- ERROR: No matching issuer found`).
Did you find an account for testing Azure DevOps Pipeline?
Thanks

**Comment by lmiller1990** [comment] 2022-09-05 23:37
> org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files

I do not think these are crashing warnings - it's just warning you that it cannot connect to a display server, since you are running heedlessly.

As for the the crashing problem:

```
[1964:0831/124215.831417:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for <url> failed: ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=<url>) ----- ERROR: No matching issuer found).
```

Is this only in Cypress 9.7?

> I see that using cypress 10.7.0 without cucumber there are no certificate errors

So just to clarify: you ran with both 9.7 and 10.7 on Azure.

- 9.7 exhibits certificate errors
- 10.7 works fine?

Is this correct?

I don't have an Azure account, but I can make one - that said, if you've found the problem is in 9.7 but not 10.7, would it just make sense to update to 10.7?

Please correct me if I'm misunderstood something here - there's quite a bit of information in the post. I think the goal should be simply running Cypress on Azure - once you can run tests, we can deal with warnings about Dbus.

**Comment by alpenite-mconventi** [comment] 2022-09-06 07:58
I saw these errors and I thought they were the cause of the running time increase and the goal is speed up and improve and keep working the execution of the tests.
If you can help me to integrate cucumber on cypress 10.7.0 and then deal with warnings about Dbus, it would be great!
Thanks in advance

**Comment by conventim** [comment] 2022-09-07 07:25
HI @lmiller1990, yesterday I integrated Cucumber and now I m fixing some output little errors and then i ll try to run the tests on Azure DevOps Pipeline to check if the Dbus warning are still present.

**Comment by lmiller1990** [comment] 2022-09-08 04:18
Sure thing, let me know if you have any success!

**Comment by ZachJW34** [comment] 2022-09-15 15:10
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by ZachJW34** 2022-09-15 15:10 UTC

**Comment by liambutler** [comment] 2022-10-10 08:25
Hello folks! I'm also seeing one of the above errors on an Azure Pipeline (via GitHub Actions):

```
[2674:1010/081822.370187:ERROR:gl_utils.cc(319)] [.WebGL-0xbdc0032e300]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
```

Not seeing the other issues though. Given that there are a lot of different issues being mentioned in the above thread, would I be better off opening a new issue, or can this one be reopened?

Additional info:

Cypress 10.8.0
Running in GitHub Actions (not self-hosted)
Viewport resolution: 1400w x 1100h
Symptoms: choppy video, some elements taking longer to render than on local machine (M1 Pro MacBook Pro)

**Comment by conventim** [comment] 2022-10-10 08:40
Hi @liambutler, i think you should open a new issue because my errors are generated from Cypress 9.7 and only on Azure DevOps Pipeline agent (ubuntu-20.04)

**Comment by stychu** [comment] 2023-02-16 11:58
This issue is still a thing. Running Cypress 12.5.1. And I believe this has nothing to do with Azure pipelines but rather running Cypress from Docker containers. I also see those errors when I run Cypress from the Docker

```
[226:0216/115058.296273:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

[226:0216/115253.122291:ERROR:gl_utils.cc(319)] [.WebGL-0x3ae005ee0700]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels (this message will no longer repeat)

[226:0216/115218.704268:ERROR:gl_utils.cc(319)] [.WebGL-0x3ae000329400]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
```

```
FROM cypress/base:16

ARG TESTS_FOLDER=/opt/cypress-tests

ENV NODE_PATH=/opt:/usr/lib/node_modules:$TESTS_FOLDER/node_modules

WORKDIR $TESTS_FOLDER

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian10-x86_64-100.5.4.deb && \
    apt install ./mongodb-database-tools-*.deb && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f mongodb-database-tools-*.deb

COPY package.json ./package.json

RUN npm install && npm run cy:verify

COPY cypress.config.ts ./cypress.config.ts
COPY cypress ./cypress
```

**Comment by MikeMcC399** [comment] 2023-02-16 12:19
@stychu 

Since this issue is closed, it probably isn't going to get much developer attention. 
- I see you found my issue #25357 for the first error message.

For the second error message:

```text
ERROR:gl_utils.cc(319)
```

are you going to open a new issue? It would be good to know which browser you are using and at what point in the logs the error occurs. Also whether the error messages are preventing Cypress test execution or if they are just an annoyance.

**Comment by lmiller1990** [comment] 2023-02-16 23:50
Has anyone tried running with `DEBUG=cypress:*` and sharing the logs? This might give us more insight. I do not doubt there's an issue, but I am not sure that https://github.com/cypress-io/cypress/issues/25357 is the cause the tests are not running on Azure.

**Comment by MikeMcC399** [comment] 2023-03-13 11:52
If the following error message is to be investigated, then it would be helpful if somebody who is affected opens a new issue.

`[226:0216/115218.704268:ERROR:gl_utils.cc(319)] [.WebGL-0x3ae000329400]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels`

including debug logs (`DEBUG=cypress:*`).

**Comment by lmiller1990** [comment] 2023-03-13 22:19
That's new - I have never seen that one before.

**Comment by wtachau** [comment] 2023-04-03 23:46
Hello all, I am having these issues still. Here is a new issue, with a small subset of the debug logs: https://github.com/cypress-io/cypress/issues/26412
