### ISSUE TITLE
Cypress throwing "Problem Reports" when I close it via terminal

### ISSUE THREAD

**Issue by techwizzdom** [cypress-io/cypress#30443] opened 2024-10-23 09:07 UTC
### Current behavior

I don't know if this is a bug or feature, but I wanted to report it.

I always used to close Cypress via the terminal, with CTRL+C. But now, every time I do it, Cypress throws a problem that looks like it's crashed:
<img width="1022" alt="Screenshot 2024-10-23 at 10 59 01" src="https://github.com/user-attachments/assets/b5f3372a-dd72-4bed-b6fd-8e319bd499d9">

The problem doesn't appear if I close it with the UI button - but I'm used to doing everything with the CLI. Is this a wanted behaviour?

### Desired behavior

Cypress should just close itself without throwing any errors.

### Test code to reproduce

`cypress open`

Then CTRL+C in terminal

### Cypress Version

13.15.0

### Node version

18.17.1

### Operating System

Mac OS 14.6.1

**Comment by MikeMcC399** [comment] 2024-10-23 16:08
@techwizzdom 

- I suspect that this is a duplicate of issue https://github.com/cypress-io/cypress/issues/29232 although I can't say for sure, since I don't have a macOS system to reproduce the error message. 
- Check out the report from @ginna-baker https://github.com/cypress-io/cypress/issues/29232#issuecomment-2386720855 and see if it is the same as what you are seeing.

**Comment by jennifer-shehane** [comment] 2024-10-24 13:35
Closing as duplicate. This is also reproducible on Mac

**Closed as not planned by jennifer-shehane** 2024-10-24 13:35 UTC

**Comment by MikeMcC399** [comment] 2024-10-27 09:02
- Also duplicate of https://github.com/cypress-io/cypress/issues/29228
