### ISSUE TITLE
Webpage doesn't load in Cypress where as Page loads perfectly in chrome browser

### ISSUE THREAD

**Issue by sushobhanworld** [cypress-io/cypress#22684] opened 2022-07-05 17:19 UTC
### Current behavior

Below is the dev console in cypress

![Cypress-browser](https://user-images.githubusercontent.com/8205488/177374749-3a3b6cd4-7cd5-479f-971b-c606e668338f.JPG)

I have tried adding below config is Cypress.json

```json
{ "modifyObstructiveCode" : false }
```

but this causes Cypress runner to not find my test at all

This is my Cypress code :

````js
/// <reference types="Cypress" />

describe("Service Now TEST login", () => {
    it("Login TEST", () => {
        cy.visit("https://hptest.service-now.com/login.do")
        cy.wait(2000)
        cy.get(".form-control", {
            timeout: 10000
        }).should("be.visible").then(() => {
            cy.get("#user_name").type("");
            cy.get("#user_password").type("");
            cy.get("#sysverb_login").click();
        });
    })
})
````

### Desired behavior

Expected Output -
Normal chrome browser

![Cypress-Normal](https://user-images.githubusercontent.com/8205488/177381848-9f79f951-868a-4c68-a00d-de60037e2f86.JPG)

### Test code to reproduce

```js
/// <reference types="Cypress" />

describe('Service Now TEST login', () => {
    it('Login TEST', () => {
      cy.visit('https://hptest.service-now.com/login.do')
      //Catch Exception
      Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      })
      cy.wait(2000)
      cy.get('.form-control', {
        timeout: 10000,
      })
        .should('be.visible')
        .then(() => {
          cy.get('#user_name').type(')
          cy.get('#user_password').type('')
          cy.get('#sysverb_login').click()
        })
    })
  })
```

### Cypress Version

9.7.0

**Comment by sushobhanworld** [comment] 2022-07-06 05:28
@bahmutov - Can you please help me here?

**Comment by sushobhanworld** [comment] 2022-07-07 05:57
@jennifer-shehane - Could you please help me here ?

**Comment by chrisbreiding** [comment] 2022-07-13 14:09
Without the username and password, I cannot reproduce the issue with the given code. I understand not wanting to share that information, but without a reliable reproduction that we can recreate on our end, we do not have a path forward to debug this issue. 

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by sushobhanworld** [comment] 2022-07-15 05:43
@chrisbreiding - is there wa way I can share the credentials with you and not here?

**Comment by mjhenkes** [comment] 2022-07-25 17:24
Likely your site or some of its scripts are having issues being rendered in an iFrame. Because cypress conducts tests in the browser we render the application under test in an iFrame. Things like assuming to window.top is the app when in fact the app is in a frame under cypress, which is now top. `modifyObstructiveCode` attempts to modify the same origin code to help run the application under test in an iframe. With https://github.com/cypress-io/cypress/pull/22568, we've added an experimental flag to modify 3rd part scripts as well. This may or may not fix your issue but it would be worth trying. It will be released with the next version of cypress.

**Closed** 2022-08-03 13:30 UTC
Labels: stage: awaiting response
