### ISSUE TITLE
Cypress is using a very old version of Electron

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3239] opened 2019-01-28 18:39 UTC
### Current behavior:

I discovered that my tests are failing on Electron and passing on Chrome because my app code relies on `Promise.finally`, which was added in Chrome 63. Cypress uses Electron 59, which is very old (April 2017).

### Desired behavior:

Please upgrade to the latest Electron. Or, even better, let users decide which version to use.

### Versions

3.1.4

**Comment by brian-mann** [comment] 2019-01-28 18:46
Duplicate of https://github.com/cypress-io/cypress/issues/2559

It's specifically on our tracking issue for 4.0 here: https://github.com/cypress-io/cypress/issues/2840

**Closed by brian-mann** 2019-01-28 18:46 UTC
Labels: type: duplicate
