### ISSUE TITLE
Basic auth in baseUrl does not work in electron browser

### ISSUE THREAD

**Issue by Narretz** [cypress-io/cypress#1639] opened 2018-04-25 12:46 UTC
### Current behavior: 
If I have a `baseUrl` in `cypress.json`:
```json
{
  "baseUrl": "http://username:password@test.dev.mypage.com"
}
```

then a basic `cypress run` does not work. I get this error:

`Timed out waiting for the browser to connect. Retrying...`

This also happens if I run `--headed`.

It *does* work in latest Chrome (66).

### Desired behavior:

It should open the page with basic auth data.

### Steps to reproduce:
1. Add `baseUrl` to `cypress.json`:
```json
{
  "baseUrl": "http://username:password@test.dev.mypage.com"
}
```

2. Do `cypress run`

### Versions  
Cypress 2.1.0

**Comment by rgrigel** [comment] 2018-05-03 18:17
We ran into this issue in our project when updating Cypress from `1.4.2` to `2.1.0`. There is a workaround based on (https://github.com/cypress-io/cypress/issues/1115).
We extended Cypress's `visit` command with:
```
Cypress.Commands.overwrite('visit', (orig, url, options) => {
  options = options || {};
  options.auth = {
    username: Cypress.env('AUTH_USER'),
    password: Cypress.env('AUTH_PASS')
  };
  return orig(url, options)
});
```
and we are running it with:
```
CYPRESS_AUTH_USER=user CYPRESS_AUTH_PASS=pass CYPRESS_baseUrl=https://app.com cypress run
```

**Comment by montogeek** [comment] 2018-12-05 11:31
Hello Cypress team!
It is there any information about a roadmap to fix this bug or something?

**Comment by keskiju** [comment] 2018-12-30 21:47
Cypress 3.1.4 seems to work ok on my Mac. However, this problem occurs when running Cypress 3.1.4 on `cypress/base:10` Docker image (Debian + Node.js 10.13).

Basic auth seems to work ok, if you just don't set the baseUrl configuration parameter at all and you make the calls using a full url (e.g. `cy.visit('https://user:pass@domain.com)`. If you have set the baseUrl configuration parameter, Cypress probably gives that url to the browser even before the tests are run, and that time the timeout problem occurs. Even this dummy test fails to a connection timeout, if the baseUrl configuration parameter has been set:

```
describe('My First Test', function() {
  it('Does not do much!', function() {
    expect(true).to.equal(true)
  })
})
```

**Comment by jennifer-shehane** [comment] 2019-05-02 08:07
Duplicate of https://github.com/cypress-io/cypress/issues/1598

**Closed by jennifer-shehane** 2019-05-02 08:07 UTC
Labels: stage: ready for work, type: bug
