### ISSUE TITLE
CypressError: cy.visit() failed trying to load when trying to load pushstate webpack-dev-server URI

### ISSUE THREAD

**Issue by paulblyth** [cypress-io/cypress#309] opened 2016-11-23 12:07 UTC
Hi. I've tried searching for an answer to this and I'm not sure it's been covered. Apologies if it has or I'm raising this in the wrong place.

So I have an application that I'm running the tests against which is served by webpack-dev-server. The application itself is a Backbone application using pushstate to remove the # from routes.

The issue arises when using these nested routes e.g. `/my/pushstate/route`

Everything works fine and returns a `200` response for the application in the browser and when curl'ing the URI. `cy.visit()` however returns a `404` when trying to request the same URIs. As a side note `cy.visit()` works correctly when requesting the base URI.

Is there something obvious I'm missing?

I can't share the codebase I'm encountering this but if there's no obvious answers I'll build a mock repo to replicate the issue.

Thanks,
Paul

**Comment by brian-mann** [comment] 2016-11-23 18:39
A mock repo would be great because I cannot see how this could happen.

**Comment by thomas-huston-zocdoc** [comment] 2016-12-07 15:15
I've been encountering the exact same issue in a webpack-dev-server application using react-router pushstate.

If I do `cy.visit('/')` and click a link to `/foo`, everything works fine, but if I do `cy.visit('/foo')`, cypress reports a `404`. Loading `/foo` directly in my browser works fine, though.

**Comment by paulblyth** [comment] 2016-12-07 15:38
Apologies - I left the project that I was encountering this error and never got round to creating the mock repo.

I'll get on that ASAP so we can try and figure out what's going on.

**Comment by brian-mann** [comment] 2016-12-12 21:47
Okay the root cause of this is that we're omitting an `Accepts` request header. Some servers require an `Accepts` header (even if its set to `*/*`)

This will be fixed in `0.18.2`.

**Comment by brian-mann** [comment] 2016-12-15 15:09
Fixed in [`0.18.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0182-12152016).

**Closed by brian-mann** 2016-12-15 15:09 UTC
Labels: bug
