### ISSUE TITLE
Cypress 4.0.1 not able to generate html reports Unexpected token in JSON

### ISSUE THREAD

**Issue by MehranShafqat** [cypress-io/cypress#6410] opened 2020-02-11 07:22 UTC
### Current behavior: 

With cypress 4.0.1 not able to generate the html reports. Well as I follow Mocha now updated to v7.0.1 and with this still we have to generate and merge the html reports etc ? 

### Desired behavior:

`npx merge` giving error not able to generate the reports

```
 npx mochawesome-report-generator --reportDir cypress/reports/ --cdn true --charts true cypress/reports/mochawesome.json
npx: installed 50 in 3.247s

✘ Some files could not be processed:
cypress/reports/mochawesome.json
  Unexpected token � in JSON at position 0
```

### Versions

v 4.0.1

**Comment by Sumedh-k** [comment] 2020-02-22 23:49
This looks like an issue with your tests.

Do you get the same error if you run the command on the example cypress tests?

**Comment by jennifer-shehane** [comment] 2020-02-26 09:59
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example, providing the test your running - ideally a repo demonstrating the issue and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-02-26 09:59 UTC
