### ISSUE TITLE
Change whitelist/blacklist references to allowlist/denylist for racial sensitivity 

### ISSUE THREAD

**Issue by tstrohecker** [cypress-io/cypress#7920] opened 2020-07-08 14:15 UTC
### Current behavior:
Currently there is a flag in the server options of `whitelist` and there were some conversations about a potential `blacklist`

### Desired behavior:

The desired state would be something more like `allowlist` and `denylist`, so that we can do a small part in being more racially sensitive.

**Comment by jennifer-shehane** [comment] 2020-07-08 14:45
The work for this is already done in https://github.com/cypress-io/cypress/pull/7622 and https://github.com/cypress-io/cypress/pull/7782 and will be released with our [5.0 release](https://github.com/cypress-io/cypress/pull/7753). Just finishing up some other breaking issues to go in before that's released. 

Closing as duplicate of https://github.com/cypress-io/cypress/issues/6642 and https://github.com/cypress-io/cypress/pull/7622

**Closed by jennifer-shehane** 2020-07-08 14:45 UTC
