### ISSUE TITLE
Spying on XHR request fails on Travis, but runs on Mac fine

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1201] opened 2018-01-18 03:21 UTC
### Current behavior:

On Mac a test that sets up XHR spy (from test spec) can spy on it. On Travis it fails to get the response. See https://dashboard.cypress.io/#/projects/9fap2d/runs/20b0cf0a-828b-4992-b7cf-25dfd71625cf/screenshots

### Desired behavior:

Be able to run this test on Travis

### How to reproduce:

Take repo https://github.com/bahmutov/cypress-form-data-with-file-upload and look at spec.js https://github.com/bahmutov/cypress-form-data-with-file-upload/blob/777f6df8725985d2dfcb410b375f45ed59b55cd4/cypress/integration/spec.js#L38

#### Test code:

```js
   it('upload with spying', () => {
      // spy on XHR calls
      cy.server()
      cy.route('POST', '/upload').as('upload')

      // we can enter info into the form fields
      cy.get('input[name="userid"]').type('foo@bar.com')

      // files to upload for each input[type="file"] name
      // we are going to construct a single text file
      const files = {
        fileToUpload: new File(['foo bar'], 'test-file.txt', {
          type: 'text/plain'
        })
      }
      // get the form element and attach files to upload
      cy.get('form').then(attachFiles(files))

      // submit the form
      cy.get('input[type="submit"]').click()

      // check upload response
      cy
        .get('@upload')
        .its('response.body')
        .should('include', 'Uploaded test-file.txt')
        .and('include', 'for foo@bar.com')
    })
```

### Additional Info (images, stack traces, etc)

Fails on Travis

![failed-spy](https://user-images.githubusercontent.com/2212006/35079292-70235aa8-fbd4-11e7-931e-7a0cc350f1bd.png)

Runs fine on Mac (both in Electron and in Chrome)

<img width="1124" alt="screen shot 2018-01-17 at 10 20 05 pm" src="https://user-images.githubusercontent.com/2212006/35079331-ac36b60c-fbd4-11e7-90fa-d5af0501088b.png">

I did not have time to run local Docker image or try Chrome on Travis

- Operating System: Linux (TravisCI)
- Cypress Version: 1.4.1
- Browser Version: Electron

**Comment by lethot** [comment] 2018-03-05 09:47
I have similar problem on circleci, cypress 2.1.0,
I have 2 routes declared, called in several tests:

test 1 : 
  - call to route 1: ok
  - call to route 2: xhr sent but not detected by cypress, lead to timeout

test 2 and following:
  - call to route 1: xhr sent but not detected by cypress,  lead to timeout

Everything works well locally, tests pass 100%, even with cli --headed, but fail 100% in circleci
I tried with chrome too, same thing happens

Screenshots:

locally: (I can see xhr)
![image](https://user-images.githubusercontent.com/6998784/36968145-f0044096-2061-11e8-9d8b-fe801ce03b9a.png)

circleci: (xhr does not appear)
![image](https://user-images.githubusercontent.com/6998784/36968209-2e27ec10-2062-11e8-8e65-6c4fc91c9c58.png)

**Comment by OrganicCat** [comment] 2018-03-22 20:00
I have a possible related issue, where on response with a 200 status the XHR POST request shows as "aborted" and the XHR status property reads "readyState" 0. However, the request goes through as verified in the network tab AND the upper "Status:" output if you click on the call.

The post response has a body of "" (nothing in there) which I THINK might be the issue? This is still a valid 200 response and should not show as failed.

**Comment by phellipeandrade** [comment] 2018-04-08 01:12
@lethot I have the same problem on circleci, cypress 2.1.0

locally:
![screenshot from 2018-04-07 22-02-00](https://user-images.githubusercontent.com/12415350/38461789-8f8ae450-3aaf-11e8-9fda-e04740fbe1ee.png)

circleci (no XHR detection):
![screenshot from 2018-04-07 22-04-09](https://user-images.githubusercontent.com/12415350/38461792-a9830cde-3aaf-11e8-90c1-8da6075851ab.png)

Making the tests fail by timeout

Do you have any progress or even a workaround?

Thanks

**Comment by filiphric** [comment] 2018-05-28 12:16
I have been able to replicate this outside of CI. I ran a test in Chrome, received an empty response body, though a response code was 201. Request came through, so problem points to Cypress.

![screenshot-2](https://user-images.githubusercontent.com/23213553/40614130-b18805de-6281-11e8-8fb9-d887cea3c3bb.png)

**Comment by bsmithEG** [comment] 2018-06-12 20:30
I'm currently experiencing an issue where all of my wait for xhr's are failing on CircleCI with 3.0.1 and the chrome65-ff container.

I can't reproduce locally.  Is there any extra amount of logging I could configure when the test runs and capture the output into a build artifact that would be beneficial?  Perhaps like a network request/response log?

**Comment by Bkucera** [comment] 2018-06-13 14:30
@bsmithEG do they sometimes fail or always? when did this start happening?

**Comment by bsmithEG** [comment] 2018-06-14 20:58
@Bkucera:

So on #1716 I discovered even though I thought I was running Chrome on CircleCI, I was actually running electron, do to misusage of command line arguments.  It seems like passing in invalid parameters to the cypress command line simply runs the default ```cypress run``` without any options.

After fixing this issue, it looks like I'm back to other issues but XHRs are now being handled correctly, so I think this might be explicitly related to electron.

**Comment by jennifer-shehane** [comment] 2018-07-12 23:08
@bsmithEG What were the invalid parameters that you were sending to `cypress run`? The command should error if you send invalid parameters, so we'd like to catch anything we may have missed. Thanks.

**Comment by jennifer-shehane** [comment] 2020-06-29 07:01
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-06-29 07:01 UTC
Labels: CI: circle, CI: travis, browser: electron, stage: needs investigating
