### ISSUE TITLE
cy.visit() don't understand the URL ?? 

### ISSUE THREAD

**Issue by Brayandotexe** [cypress-io/cypress#6172] opened 2020-01-15 20:35 UTC
The current website [manager.people.com.ai ](url)was improved to run over tests and now it generates a new URI for each BOT. Then I have created a scenario to automate the acquisition for that link, which is visible on the screen. 

![image](https://user-images.githubusercontent.com/59480526/72467707-489e4c80-37ba-11ea-99d0-3f46b3d68329.png)

After some changes and log's, the variable that receives the url was returning right value but when run a cy.visit is show two new values in different places.

![2020-01-15_15-00](https://user-images.githubusercontent.com/59480526/72460222-2a7d2000-37ab-11ea-93d8-e68dbde2315a.png)

The search value: [https://chathml.people.com.ai/9a068b08-500e-4715-8ad7-44b780297ea4](url) and localhost.

### Version:
Cypress: 3.8.1

**Comment by jennifer-shehane** [comment] 2020-01-16 05:23
You cannot visit 2 domains of different origin wtithin a single test - `http://localhost:8080` and `https://hml.people.com.ai` are of 2 different origins and subdomains. 

Split the visiting 2 different origin urls into separate tests or rewrite your tests in a way that you are not navigating to 2 domains of different origin. 

Closing as duplicate of https://github.com/cypress-io/cypress/issues/944

**Closed by jennifer-shehane** 2020-01-16 05:23 UTC
