### ISSUE TITLE
Stylesheets not correctly reinstated in snapshot

### ISSUE THREAD

**Issue by dracos** [cypress-io/cypress#1499] opened 2018-03-26 14:03 UTC
### Current behavior:

I saw #525 which was closed, so wasn't sure if same or different issue.

We have a test that sets `cy.viewport(480,800)`; the site has a base CSS and desktop CSS that kicks in at 48em (768px) wide using a media query on the `<link>`. Whilst watching the test run, this test displays perfectly, but when hovering over/pinning the page afterwards in the GUI, the page is displayed at the correct width but with the desktop styling also applied.

### Desired behavior:

The snapshot should match how it looked whilst running the test.
My guess is that the media query on the `<link>` has been lost when performing whatever magic it is you do for the snapshots to work?

### Additional Info (images, stack traces, etc)

Screenshot taken during test run:
![image](https://user-images.githubusercontent.com/154364/37910612-ddb6d5b6-3105-11e8-8a55-b155f45db90d.png)

Screenshot taken after test run by hovering/pinning:
![image](https://user-images.githubusercontent.com/154364/37910630-e56b8766-3105-11e8-88ad-9c1cf172d4b4.png)

- Operating System: MacOS 10.12.6
- Cypress Version: 2.1.0
- Browser Version: Electron 59 or Chrome 65

**Comment by jennifer-shehane** [comment] 2018-03-26 17:31
Snapshots are actually not screenshots. Cypress is restoring the DOM to the state that it was in during the test run. Also:

> When we save a snapshot, we grab all the CSS styles as text, then when we restore the snapshot on hover, we put the styles back, inlining them on the page in a <style> tag. The reason we do that is to avoid extra http requests when the snapshot is restored, or else there would be too much latency when trying to scrub over snapshots.

So, there is probably some sort of bug where the path to the CSS file is not being found/inlined correctly. 

Is it possible to provide a reproducible repo? With css links? Or show how the css is linked? Otherwise this will be impossible for us to track down.

**Comment by dracos** [comment] 2018-03-26 17:54
Yes, I realise they're not screenshots - I assume the large-width CSS is being inlined in the iframe when it shouldn't be. When you grab the CSS, are you taking account of the media queries on the `<link>`? That's why I guessed it could be something to do with that.

It's not the path, because too much is being inlined, not too little :) You're including the contents of a CSS file that should not be included at the viewport specified.

The repo is https://github.com/mysociety/fixmystreet and it has a Vagrantfile, but I think the setup might be too awkward, sorry. The CSS template is https://github.com/mysociety/fixmystreet/blob/master/templates/web/base/header/css.html - it is two CS files, one always included, one included with `media="screen and (min-width:48em)"`.

The Cypress tests are at https://github.com/mysociety/fixmystreet/blob/master/.cypress/cypress/integration/regressions.js

Thanks for your reply :)

**Comment by dracos** [comment] 2018-03-26 17:56
"I think the setup might be too awkward, sorry" - especially as precise can no longer download from GitHub, so we need to get the Vagrantfile updated to trusty... Anyway, once someone did get it running, we have a `bin/browser-tests` script that sets up a test database (a new Pg cluster in fact) and then calls cypress, which might be of general interest: https://github.com/mysociety/fixmystreet/blob/master/bin/browser-tests - and can be run with Vagrant, running the test server inside Vagrant and cypress outside of it :)

**Comment by sirjackal** [comment] 2021-04-20 07:31
Hi, I reported the same issue https://github.com/cypress-io/cypress/issues/16066 I'm upset nothing has happened here for 3 years :(

**Comment by jennifer-shehane** [comment] 2021-04-21 20:22
Close as duplicate of https://github.com/cypress-io/cypress/issues/16066 since it has a repro.

**Closed by jennifer-shehane** 2021-04-21 20:22 UTC
Labels: stage: needs investigating, topic: snapshot
