### ISSUE TITLE
Strings end with '\n' cause Chrome only test failures

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress#3907] opened 2019-04-08 03:14 UTC
### Current behavior:

The following tests from `tests/integration/commands/actions/type_spec.coffee` fail on Chrome 73 but pass on Electron 59:

* `can wrap cursor to next line in [contenteditable] with {rightarrow}`
* `can wrap cursor to prev line in [contenteditable] with {leftarrow}failed`
* `can use {rightarrow} and nested elementsfailed`
* `enter and \n should act the same for [contenteditable]`
* `can type into [contenteditable] with existing <div>`
* `can type into [contenteditable] with existing <p>failed`
* `collapses selection to start on {leftarrow}`
* `collapses selection to end on {rightarrow}`
* `should move cursor to the start of each line in contenteditable`
* `should move cursor to the end of each line in contenteditable`
* `up and down arrow on contenteditablefailed`
* `downarrow ignores current selectionfailed`
* `inserts new line into [contenteditable]`
* `inserts new line into [contenteditable] from midline`

The test failures have a common pattern:  The expected result strings all end with `\n` but the actual result does not end with `\n`.

![Screen Shot 2019-04-07 at 11 07 03 PM](https://user-images.githubusercontent.com/1740517/55696211-ea6e4e80-5989-11e9-9b93-b4a65685c420.png)

### Desired behavior:

All tests from `type_spec.coffee` pass on both Chrome and Electron.

### Steps to reproduce: (app code and test code)

* Clone Cypress' `develop` branch.
* Install Chrome 73.
* Open 3 terminals running the following commands:

Terminal 1:
```shell
cd cypress/package/driver
npm start
```

Terminal 2:
```shell
cd cypress/package/runner
npm run watch
```

Terminal 3:
```shell
cd cypress/packages/driver
npm run cypress:open
```

* Select "Chrome 73" as the browser.
* Click `type_spec.coffee` under command > actions.
* Wait for the tests to finish. :)

### Versions
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Mac OS (latest released version)
Cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-04-08 05:55
Thank you so much for opening such a detailed issue.`

Verified this is failing in `develop` for Chromium versions 72, 73, 75 - passing in Electron 59.

Also verified this is failing in `master` for Chromium versions 72, 73, 75 - passing in Electron 59, so it is not a regression in the 3.3.0 pre-release.

@bahmutov Are we running our tests against Chrome 64? Because this is quite old now. This should stay up to date with latest Chrome release. https://github.com/cypress-io/cypress/blob/master/circle.yml#L26

**Comment by Bkucera** [comment] 2019-04-08 19:06
this commit fixes those failing tests https://github.com/cypress-io/cypress/pull/3891/commits/3f1d38862aa1456309167b5c7bfdd9c7544f08b2

will be merged in as part of https://github.com/cypress-io/cypress/pull/3891

**Comment by clarmso** [comment] 2020-06-24 04:03
@jennifer-shehane Could we close this issue? The tests have been run against Chrome in addition to Electron.

**Comment by jennifer-shehane** [comment] 2020-07-13 08:31
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-13 08:31 UTC
Labels: browser: chrome, pkg/driver, process: tests, stage: work in progress, type: bug
