### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by quany** [cypress-io/cypress#3181] opened 2019-01-22 08:43 UTC
Platform: darwin (18.2.0)
Cypress Version: 3.1.4
The Cypress App could not be unzipped.

**Comment by jennifer-shehane** [comment] 2019-01-22 10:32
This may be due to a temporary network or file disk hiccup. We will need a reproducible example in order to address the issue. Can you provide it? Thanks!

**Comment by jennifer-shehane** [comment] 2019-02-28 17:15
Duplicate of https://github.com/cypress-io/cypress/issues/3515

**Closed by jennifer-shehane** 2019-02-28 17:15 UTC
Labels: stage: needs information
