### ISSUE TITLE
RangeError when visually diffing: The value of "offset" is out of range.

### ISSUE THREAD

**Issue by david-boydell** [cypress-io/cypress#8415] opened 2020-08-26 13:06 UTC
Related issue: https://github.com/cypress-io/cypress/issues/5668. As per 5668 I'm raising a new issue in the hope that it is reproducible in this instance. 

### Current behavior:

When visually diffing an element with _Cypress Image Snapshot_ or _cypress-plugin-snapshots_ using Cypress v4.0.0, or greater, I receive the error "RangeError: The value of "offset" is out of range. It must be >= 0 and <= 22014716. Received -13440" when attempting to compare screenshots.

I do not get this error on version 3.8.3.

### Desired behavior:

The plugins work as expected on versions greater than v3.8.3

### Test code to reproduce

1. Install and check cypress version with npx cypress -v
```
Cypress package version: 4.0.0
Cypress binary version: 4.0.0
```
2. Add cypress-plugin-snapshot to your project as per https://github.com/meinaart/cypress-plugin-snapshots
3. Use the following test:
```js
describe('Signed out homepage', () => {
  it('displays the signed out banner', () => {
    cy.visit('https://www.bbc.co.uk/weatherwatchers').then(() => {
      cy.get('.banner--intro-signed-out').toMatchImageSnapshot({ imageConfig: { threshold: 0.01 } });
    });
  });
});
```
4. Run it once to establish the expected screenshot, then run the test again. You receive the error `RangeError: The value of "offset" is out of range. It must be >= 0 and <= 22014716. Received -13440` in the results window.
5. Rerunning the same steps with cypress v3.8.3 does not produce the error.

I can paste the full error from the console if necessary, was quite verbose though.

### Versions

>v.4.0.0, OS X 10.14.6, Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment] 2020-08-27 06:55
Duplicate of #2034

**Closed by jennifer-shehane** 2020-08-27 06:55 UTC
