### ISSUE TITLE
intercept reply is getting queued after the following command

### ISSUE THREAD

**Issue by mzedeler** [cypress-io/cypress#9205] opened 2020-11-16 11:19 UTC
Providing a response override to `route2` causes the response promise to be queued *after* the following command, causing a deadlock.

### Current behavior
With the following snippet:

```js
const resHandler = response => console.log('response: ', response) || response
const reqHandler = request => console.log('request', request) || request.reply(resHandler)
cy.route2({ pathname: /clipboard/ }, reqHandler).as('clipboard')
cy.findByTestId('folders-menu-item').click().then(() => console.log('found menu item'))
```
A shorter and similar way to reproduce:
```js
cy.route2({ pathname: /clipboard/ }, req => req.reply(res => res)).as('clipboard')
cy.findByTestId('folders-menu-item').click()
cy.wait('@clipboard')
```

This causes a deadlock where `findByTestId` never completes because I believe it is queued before the `resHandler` (and the test depends on the response - note that it *isn't* overriden or modified, just output to the log). The log only outputs `request {<request data here>}`, and never gets to output `response`. If I remove the subsequent `findByTestId`, everything works.

### Desired behavior
Make sure that `route2` only completes once `reply` has completed.

### Test code to reproduce
See above.

### Versions

5.6.0.

**Comment by mzedeler** [comment] 2020-11-16 11:46
I may have found the bug - `resHandler` should be set to `response => console.log('response', response) || response`. I was assuming that returning nothing would cause route2 to pass back the response itself.

**Comment by mzedeler** [comment] 2020-11-16 11:49
Sorry - even if I add the fix above, the deadlock still occurs.

**Comment by mzedeler** [comment] 2020-11-17 10:57
Is it possible that https://github.com/cypress-io/cypress/pull/9059 solves this?

**Comment by jennifer-shehane** [comment] 2020-11-17 12:24
@mzedeler That PR fix is already released in 5.6.0, so if you're using 5.6.0 then that PR doesn't fix your issue.

**Comment by mzedeler** [comment] 2020-11-17 12:24
Ok - then someone needs to triage this issue.

**Comment by mzedeler** [comment] 2020-11-18 08:25
I've taken more time to try to diagnose this, and afaik, it is the `wait` command that is being queued before the `reply` command.

**Comment by mzedeler** [comment] 2020-11-18 09:42
I've added a minimal example here:

https://github.com/mzedeler/cypress-route2-bug

To run it, follow these steps:

* Clone to local machine
* `npm install`
* `npm start`
* Run the deadlock test

**Comment by jennifer-shehane** [comment] 2021-01-20 06:22
This issue has been fixed since this issue was opened and is no longer present when using `cy.intercept()` in our latest Cypress version (6.3.0). 

Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-01-20 06:22 UTC
Labels: pkg/net-stubbing, stage: needs investigating
