### ISSUE TITLE
Cypress fails to find input elements, it finds the first but not the following 

### ISSUE THREAD

**Issue by chipomapondera** [cypress-io/cypress#5718] opened 2019-11-17 01:44 UTC
Hello,

I’m trying to test a Stripe form with 3 input fields in Cypress. I found an example that works to test  a single input that takes all the payment info (https://medium.com/@chipomapondera/hi-michael-98e432948028). 

My version passes on inputting the CC but fails on the next input(s). My code is below: 
it('checks user can support the Creator', () => {
        cy.get('button[class="buttons__FollowButton-sc-10ti9z2-0 huoUmA"]').click()
        cy.wait(4000)
        cy.get('body')
          .should('contain', 'Join this community')
        cy.get('button[class="styledComponents__SubscribeButton-g42pit-3 kUgWbq"]').click()
        cy.getWithinIframe('[name="cardnumber"]').type('4242424242424242')
          .getWithinIframe('[name="exp-date"]').type('1232)
          .getWithinIframe('[name="cvc"]').type('987')
    })

It doesn’t seem to like after it has typed the card number:
cy.getWithinIframe(‘[name=”exp-date”]’).type(‘1232’)
cy.getWithinIframe(‘[name=”cvc”]’).type(‘987’)

The error I receive is: 
<img width="1333" alt="Screenshot 2019-11-17 at 01 44 18" src="https://user-images.githubusercontent.com/35879037/69001748-cc7fa980-08db-11ea-9b86-0b664581d80e.png">

**Comment by sainthkh** [comment] 2021-01-05 06:44
Closing this issue because it's old and it doesn't have a reproducible example. I hope it works with the latest Cypress. If the problem is still happening, please open a new issue with a reproducible example.

**Closed by sainthkh** 2021-01-05 06:44 UTC
