### ISSUE TITLE
7.5.0 is 50% slower than 6.6.0 

### ISSUE THREAD

**Issue by dariuszteooh** [cypress-io/cypress#16944] opened 2021-06-15 13:33 UTC
I've been using 6.6.0 for a while, having upgraded in the past to 7.0.0 and being affected by [https://github.com/cypress-io/cypress/issues/15853](this bug) I've downgraded back. I saw that it's been fixed, so I updated to 7.5.0 and found that test execution takes 50% more time. 
On 6.6.0 my test suite ran for 20 minutes (which is still a very long time for tests to run). Updating to 7.5.0 extends this time even further, to 30 minutes. 
I'm not sure what kind of information I can give you to help debug this? I'm running the tests through Jenkins.

**Comment by jennifer-shehane** [comment] 2021-06-15 13:38
Duplicate of https://github.com/cypress-io/cypress/issues/16305

If you are running Cypress in a headless browser, the default screen size was increased to 1920x1080 which introduces extra time. Reduce the screen size to the default size prior to 7.0 (1280x720). [Instructions here.](https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless) This should help. 

Additionally, I would recommend looking at the resources on the machine you're running on. Run on a high resources machine (like a Mac) and measure how long the tests take. If the tests are taking longer on your CI machine - you need to increase the resources of the machine. Low resources machines are more affected by slight performance issues.

If you are still having performance increases after that change. Please provide a reproducible example in https://github.com/cypress-io/cypress/issues/16305 that we can run. We've run lots of performance tests and no one has provided us with an example where performance is an issue outside of the increased screen size.

**Closed by jennifer-shehane** 2021-06-15 13:38 UTC
