### ISSUE TITLE
Should show stack trace to step in the script on custom command error

### ISSUE THREAD

**Issue by s1n7ax** [cypress-io/cypress#7546] opened 2020-05-31 21:26 UTC
I'm creating set of really useful Cypress commands. I wan't to handle invalid arguments validations and more stuff within the custom command. Default Cypress `get()` command handles it as follows,

```javascript
get (selector, options = {}) {
  const userOptions = options
  const ctx = this

  if ((userOptions === null) || _.isArray(userOptions) || !_.isPlainObject(userOptions)) {
	return $errUtils.throwErrByPath('get.invalid_options', {
	  args: { options: userOptions },
	})
  }
```

Log will show following information.

![image](https://user-images.githubusercontent.com/18459807/83362473-2c88f980-a3af-11ea-8b64-2513319e0145.png)

Important thing here is, the failure from `get()` will show stack trace to the current step in the **test script** as well as in the code peek window.

### Current behavior:
With current capabilities, I could throw an error from the command

```js
Cypress.Commands.add('vDo', (...args) => {
    throw new Error('testing error');
});
```
but when an error is thrown from a custom command, log will shows the stack trace to the custom command implementation, not to the current step in the script just like `get()`.

![image](https://user-images.githubusercontent.com/18459807/83362871-5ee82600-a3b2-11ea-9e13-cbf07cf64aa4.png)

### Desired behavior:
My suggestion for handling errors would be following, since I can do it in the same format as other commands,

```js
Cypress.Commands.add('vDo', (sel, userOptions) => {
    return $errUtils.throwErrByPath('vDo.invalid_options', {
        args: {
            options: userOptions
        },
    })
});
```
In the log, on an error, stack trace & code peek should show the step in test script.

#### support/index.js
```js
Cypress.Commands.add('vDo', (...args) => {
    throw new Error('testing error');
});
```

#### integration/actions.spec.js
```js
/// <reference types="cypress" />

context('Actions', () => {
	it('should only get visible element', () => {
		cy.visit('https://www.google.com')
		cy.vDo()
	});
})
```

**Comment by dwelle** [comment] 2020-07-12 18:16
This doesn't just relate to throwing custom errors. If you enqueue a cypress command from within a custom command and it fails, it'll show the stack trace leading to the command inside your custom command instead of your spec.

**Comment by dovh-me** [comment] 2022-10-27 06:39
Any updates on this?

**Comment by jennifer-shehane** [comment] 2024-01-24 01:54
Duplicate of https://github.com/cypress-io/cypress/issues/15581

**Closed by jennifer-shehane** 2024-01-24 01:54 UTC
Labels: type: enhancement, stage: proposal 💡, v4.6.0 :bug:, topic: code frame
