### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split') cypress_runner.js 198481

### ISSUE THREAD

**Issue by saylestyler** [cypress-io/cypress#20900] opened 2022-04-04 19:23 UTC
### Current behavior

I have a test failing in CI that I want to run locally to debug. 

I cannot get cypress to run locally—which I've always been able to do until recently. 

I've deleted caches at `/user/Library/Caches/Cypress/*`, reinstalled countless times, tried on two different machines. I've also gotten my coworkers to run locally and they don't have issues. 

Whenever a test is run I get this error. It occurs regardless of the test. I verified this using the getting started test from the docs: 

```js
describe('My First Test', () => {
  it('Does not do much!', () => {
    expect(true).to.equal(true)
  })
})
```

![image](https://user-images.githubusercontent.com/20520284/161616371-e2994d3b-ede3-42a3-96f8-1d72eaef0615.png)

The top of the stack trace leads to this from cypress_runner

```
var splitStack = function splitStack(stack) {
  var lines = stack.split('\n');
  return _.reduce(lines, function (memo, line) {
    if (memo.messageEnded || stackLineRegex.test(line)) {
      memo.messageEnded = true;
      memo[1].push(line);
    } else {
      memo[0].push(line);
    }

    return memo;
  }, [[], []]);
};
```

It seems like [others have had similar issues](https://github.com/cypress-io/cypress/issues/14968#issuecomment-1068289228). I noticed that popper.js.map is 404ing in the terminal. 

![image](https://user-images.githubusercontent.com/20520284/161616848-de1109c9-fd17-49a6-8786-416fee03ebda.png)

### Desired behavior

Trying to get any test to run. It's failing before I can. 

### Test code to reproduce

Using this test as a sanity check from the docs: 

```js
describe('My First Test', () => {
  it('Does not do much!', () => {
    expect(true).to.equal(true)
  })
})
```

Use `cypress open` and click it! 

### Cypress Version

4.7.0

**Comment by davidmunechika** [comment] 2022-04-05 14:24
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by saylestyler** [comment] 2022-04-19 15:21
> I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

Upgrading to `v9.5.4` had no effect, sadly.

**Comment by davidmunechika** [comment] 2022-04-21 14:51
Can you try uninstalling Cypress entirely from the machine and then reinstalling with the [latest version](https://docs.cypress.io/guides/references/changelog)?

Unfortunately, if there is not enough information to reproduce this issue, we will have to close this ticket. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. Since you mention others not having issues with this, this is likely not an issue with Cypress itself.

**Closed** 2022-05-09 17:40 UTC
Labels: stage: backlog

**Comment by eugensunic** [comment] 2022-08-24 14:45
+1

**Comment by andrii-lundiak** [comment] 2022-11-14 15:29
OMG, if such simple test cause that weird issue, then my not-simple test caused it somehow also.
And I also installed/reinstalled, cleared cache, etc.
And I have Cypress v6.x. I don't even try to upgrade to 11 coz most probably it's some silly thing, not version related.

Maybe it's again related to this bug: https://github.com/entropitor/dotenv-cli/issues/71
I also suspect it may be related to `.env`

@saylestyler have u fixed it somehow? Workaround? 10-11 version maybe?

**Comment by NataMT** [comment] 2022-12-20 22:17
+1 Having the same issue, has anyone found the fix? 
thx
