### ISSUE TITLE
Route response mock failing for AWS Cognito

### ISSUE THREAD

**Issue by kleky** [cypress-io/cypress#6703] opened 2020-03-11 13:59 UTC
### Current behavior:

When mocking out the authentication process for a user login with AWS Cognito, the POST is not being captured.

### Desired behavior:

The POST is captured and mock response returned.

### Test code to reproduce

Create user pool in cognito
wire up an app and authenticate using node package `aws-sdk` and `amazon-cognito-identity-js`
```js
const user = new CognitoUser({...});
user.authenticateUser(new AuthenticationDetails({...}, callback...)
```

https://github.com/amazon-archives/amazon-cognito-identity-js/blob/6b87f1a30a998072b4d98facb49dcaf8780d15b0/lib/CognitoUser.js#L242

https://github.com/amazon-archives/amazon-cognito-identity-js/blob/6b87f1a30a998072b4d98facb49dcaf8780d15b0/lib/CognitoUserPool.js#L69

```js
cy.server();
    cy.route({
      method: "POST",
      url: "cognito-idp.eu-west-2.amazonaws.com/",
      response: {
        ChallengeName: "PASSWORD_VERIFIER",
        ChallengeParameters: {
          SALT: "...",
          SECRET_BLOCK: "...",
          SRP_B: "...",
          USERNAME: "i.Jones",
          USER_ID_FOR_SRP: "i.Jones"
        }
      }}).as("verifier");
```

### Versions

Cypress - 4.1.0, operating system mac od 10.15.3 (catalina), browser test running in chrome 80

**Comment by jennifer-shehane** [comment] 2020-03-11 16:26
@kleky Can you explain a bit more about what "the POST is not being captured" means?

Are you seeing an error in Cypress? Is something functionally not working from the mocked response? Is the route displaying in the Command Log in Cypress? Have you inspected the Network panel?

**Comment by jennifer-shehane** [comment] 2020-03-16 08:41
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example, answering the questions above and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-03-16 08:41 UTC
Labels: stage: needs information

**Comment by prrraveen** [comment] 2020-04-28 18:52
I am having the same issue. The post request is not logging in cypress left panel but it is getting tracked in the netwok tab in chrome developer tool.
Other http requests are getting recorded in the cypress left panel. Its the issue only with aws congnito api.

**Comment by kleky** [comment] 2020-04-28 19:47
> I am having the same issue. The post request is not logging in cypress left panel but it is getting tracked in the netwok tab in chrome developer tool.
> Other http requests are getting recorded in the cypress left panel. Its the issue only with aws congnito api.

Hi. I think they updated the docs recently stating that fetch requests are not supported. Cognition uses a fetch request I believe, which is why its not caught. I've not tried to use the workaround, but would love to hear about it if you try.

**Comment by boraita** [comment] 2020-04-29 08:33
I'm having the same issue, and I would like to know how to mock it, because I'm trying to log in and I tried can't mock it.
Even I tried delete the fetch as cypress give us here: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch
Or 
Use a library to intercept the call.

**Comment by kleky** [comment] 2020-04-29 08:43
Yeah me too, sadly I've had to resort to logging in for real. You could do the http POST of the login data, rather than using a UI form, which will speed things up.

**Comment by prrraveen** [comment] 2020-05-03 08:04
@kleky could you please share an example code for this

**Comment by prrraveen** [comment] 2020-05-03 14:51
I followed [this example](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__window-fetch/cypress/integration/polyfill-fetch-from-tests-spec.js) to pollyfill the fetch api with xhr request. 

I was able to log the amplify Auth.login post request using this code
```
describe('Test the login feature', () => {

  let polyfill

  // grab fetch polyfill from remote URL, could be also from a local package
  before(() => {
    const polyfillUrl = 'https://unpkg.com/unfetch/dist/unfetch.umd.js'

    cy.request(polyfillUrl)
      .then((response) => {
        polyfill = response.body
      })
  })

  // all calls will be done via XHR after we load polyfill
  // so we can spy on them using cy.route

  beforeEach(function () {

    cy.server()
    cy.route('POST','https://cognito-idp.us-east-2.amazonaws.com/').as('userLogin')

    // We use cy.visit({onBeforeLoad: ...}) to delete native fetch and load polyfill code instead
    cy.visit('/login', {
      onBeforeLoad(win) {
        delete win.fetch
        // since the application code does not ship with a polyfill
        // load a polyfilled "fetch" from the test
        win.eval(polyfill)
        win.fetch = win.unfetch
      },
    })
  })

  const userName = 'example'
  const pw = 'pass'

  it('try login', () => {
    cy
      .get('.user-name')
      .type(userName)
      .should('have.value', userName)

    cy
      .get('.password')
      .type(pw + '{enter}')

    cy.wait('@userLogin')
  })

})
```

**Comment by shadrech** [comment] 2020-08-01 23:52
Nice @prrraveen . You mention getting polyfill from local package. How would someone go about doing this? I've tried this and it doesn't seem to work

**Comment by emmafass** [comment] 2021-02-12 19:33
@prrraveen any ideas on the best way to do this since `cy.route` was [deprecated in Cypress 6.0.0](https://docs.cypress.io/api/commands/route.html#Syntax)?

I've been trying to get the AWS Cognito mock to work using `cy.intercept` with a fixture. [According to the Cypress docs](https://docs.cypress.io/api/commands/intercept.html#Comparison-to-cy-route):

```
If cy.intercept() provides a response object, or a fixture, or calls req.reply() then the request will NOT go to the server, and instead will be mocked from the test.
```

However, I'm still finding that when I run the tests, the request goes to AWS Cognito.

**Comment by zhiwang95** [comment] 2021-03-11 05:43
I had this same issue and was able to solve this by putting the `intercept` command at the very beginning of the test. Hope this helps.

**Comment by williamRR** [comment] 2022-01-18 14:11
@emmafass did you solve how to mock cognito's answers?

**Comment by AtofStryker** [comment] 2022-11-18 16:13
Hey all. If logging into federated Cognito is still an issue using username/password, you can now easily test this with `cy.origin` in `10.11.0` and up! This requires the `experimentalSessionAndOrigin` flag to be enabled and ill be generally available in Cypress 12. A sample test would look like this

```
describe('Cognito Federated sign in via Amplify', () => {
  it('logs in via amplify', () => {
    cy.visit('/');
    cy.get('[data-cy="login"]').click();

    cy.origin('https://YOUR_COGNITO_INSTANCE.auth.us-east-1.amazoncognito.com', () => {
      // cognito log in page has some elements of the same id but are off screen. we only want the visible elements to log in
      cy.get('input[name="username"]:visible').type(
        Cypress.env('AWS_AMPLIFY_USERNAME')
      );
      cy.get('input[name="password"]:visible').type(
        Cypress.env('AWS_AMPLIFY_PASSWORD'),
        {
          log: false
        }
      );
      cy.get('input[name="signInSubmitButton"]:visible').click();
    });

    cy.get('[data-cy="user-name"]')
      .invoke('text')
      .should('equal', `USERNAME`);
  });
});
```

Hopefully you all are able to try this and let us know what you think!
