### ISSUE TITLE
'Nested' assertions not working in 3.4.1

### ISSUE THREAD

**Issue by hannaofsweden** [cypress-io/cypress#5004] opened 2019-08-19 11:22 UTC
**Current behavior:**
According to the documentation this should work:

```js
expect({a: {b: ['x', 'y']}}).to.have.nested.property('a.b[1]')
```

(Or `cy.something().should('have.nested.property, 'a.b[1]')` )

However if you do that you will get:

```
TypeError: Cannot read property 'property' of undefined
```

**Desired behavior:**

Nested assertions should work as specified in the documentation.

**Versions**
Cypress: 3.4.1
Chrome: 74
Electron: 61

**Comment by jennifer-shehane** [comment] 2019-10-11 20:20
The `nested` was introduced in [Chai 4.0.0](https://github.com/chaijs/chai/releases/4.0.0). Cypress is currently using Chai 3.5.0. 

This will be fixed in our breaking Cypress v4 release - I will be closing this issue as 'pending release' since the code for this is done, but has yet to be released.

- Original issue for Chai update: https://github.com/cypress-io/cypress/issues/1153
- PR containing Chai update: https://github.com/cypress-io/cypress/issues/2529
- Cypress v4 release (this issue will be fixed when this issue is closed): https://github.com/cypress-io/cypress/issues/4270

**Closed by jennifer-shehane** 2019-10-11 20:20 UTC
Labels: stage: pending release

**Comment by jennifer-shehane** [comment] 2020-01-29 09:22
I've confirmed that this works in upcoming 4.0 release. The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

<img width="453" alt="Screen Shot 2020-01-29 at 3 47 50 PM" src="https://user-images.githubusercontent.com/1271364/73343302-c11f0600-42ae-11ea-9160-73ecf6c80fae.png">
