### ISSUE TITLE
Cypress Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by AntonioGargaro** [cypress-io/cypress#9042] opened 2020-10-30 13:30 UTC
### Current behavior
Cypress running in headless mode is causing our CI and local environments to error unexpectedly after all tests have passed successfully. We are using `Cypress 5.4.0` for E2E testing.

This is screenshot of local run failing with debug,
![Screenshot 2020-10-30 at 13 24 05](https://user-images.githubusercontent.com/38767071/97710087-307e8c00-1ab3-11eb-9dee-109aa340111d.png)

This issue appears linked to https://github.com/cypress-io/cypress/issues/7048

**Comment by jennifer-shehane** [comment] 2020-11-02 08:16
Duplicate of https://github.com/cypress-io/cypress/issues/7048

**Closed by jennifer-shehane** 2020-11-02 08:16 UTC
