### ISSUE TITLE
Auth0 redirect back to app fails without explicit revisit via cy.visit()

### ISSUE THREAD

**Issue by gabriellemadden** [cypress-io/cypress#25530] opened 2023-01-20 15:56 UTC
### Current behavior

We have set up our test suite to sign in to our app through the auth0 UI. 
1. Our app redirects a user to the auth0 log in page where they input credentials.
2. After authenticating, the user is redirected back to our app where they should be authenticated via browser cookies set by auth0. 
3. Our app behaves as if the user is still not authenticated, and redirects them back to the Auth0 login page
4. if we run cy.visit('our-app-url') in the same test immediately after the first auth0 manual login in steps 1-3, the app sees the user as authenticated and the test is granted access.

The above behaviour is not observed when logging in outside of the cypress test. It occurs in headless and headed mode, both chrome and electron.

### Desired behavior

We should not have to explicitly use cy.visit() to return to the app and be seen as authenticated. The test should be seen as authenticated at the first organic redirect back to the app from auth0.

### Test code to reproduce

cypress.config.json:
```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  chromeWebSecurity: false,
  defaultCommandTimeout: 90000,
  responseTimeout: 90000,
  recoverFromRendererCrashes: true,
  e2e: {
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config)
    },
  },
})
```

cypress.env.json:
```
{
  "FRONTEND_URL": "localhost:4200",
  "AUTH0_CLIENT_ID": redacted,
  "AUTH0_DOMAIN": "businessname.auth0.com",
  "AUTH0_USERNAME": redacted,
  "AUTH0_PASSWORD": redacted
}
```

failing test:
```
/// <reference types="cypress" />
describe('Check home screen', () => {
    it('Checks home screen', () =>{
        cy.login(Cypress.env('FRONTEND_URL'))
        cy.get('#mainMenuBtn').click() // fails on timeout because this is an app component, but the test sees the auth0 login page again
        cy.get('#home-navigation').click()
    })
})
```

login command:
```
Cypress.Commands.add('login', (frontendUrl) => {
    cy.visit(frontendUrl); // redirects to auth0 login page
    cy.get('input[type=text]').type(Cypress.env('AUTH0_USERNAME'));
    cy.get('input[type=password]').type(Cypress.env('AUTH0_PASSWORD'), {log: false});
    cy.get('form').first().submit();

    // redirects back to app, app sees attempt as not authenticated and redirects back to auth0
    // note that an extra  cy.visit(frontendUrl); here actually results in the test being seen as authenticated by our app

});
```

login command attempting to use cy.origin, but with same behaviour:
```
Cypress.Commands.add('login', (frontendUrl) => {
    cy.visit(frontendUrl); // redirects to auth0 login page

    cy.origin(Cypress.env('AUTH0_DOMAIN'), () => {
      cy.get('input[type=text]').type(Cypress.env('AUTH0_USERNAME'));
      cy.get('input[type=password]').type(Cypress.env('AUTH0_PASSWORD'), {log: false});
      cy.get('form').first().submit();
    })

    // redirects back to app, app sees attempt as not authenticated and redirects back to auth0
    // note that an extra  cy.visit(frontendUrl); here actually results in the test being seen as authenticated by our app

});
```

### Cypress Version

12.3.0

### Node version

16.15.0

### Operating System

macOS 12.6

### Other

- I have not been able to find evidence that the issue is on the side of our app. When logging into the app outside of cypress, there is no failed authentication after logging in to auth0 and being redirected. We have not changed any of our Auth0 callback settings
- This issue has cropped up when attempting to upgrade cypress from version 9.1.0 to version 12.3.0. The original login command works with auth0 and our app just fine, even without the cy.origin() functionality, in version 9.1.0. 
- Given that the debug logs expose sensitive information, I prefer not to share them.
- The browser cookies set by auth0 appear to be working, since revisiting the app domain after login/redirect works

I am going to add in the cy.visit() as a workaround for now but it would be nice to mimic the user's login flow exactly in our e2e tests.

**Comment by AtofStryker** [comment] 2023-01-25 18:58
Hi @gabriellemadden. Thank you for opening your first Cypress issue! I tried giving this a reproduction in this [repo](https://github.com/AtofStryker/cypress-issue-25530) with a different tenant but haven't been able to reproduce it. Would you be able to use the reproduction repo and see if you can reproduce the issue? I tried to mimic this to your description as much as possible.

I wonder if some time is needed to validate possible state on the return URL. Are you able to post a video of the test with redacted information?

**Comment by gabriellemadden** [comment] 2023-01-26 15:50
Hi, thanks for attempting to reproduce. I have the repo you provided set up, and our Auth0 tenant works with the Vite app you provided. However, the app we have integrated with Auth0 that we are trying to test is an Angular app which is using the [Auth0.checkSession()](https://auth0.com/docs/libraries/auth0js?_gl=1*o4ei8n*rollup_ga*MjA4NTE0NDY0Ni4xNjU1MDk0MDg2*rollup_ga_F1G3E656YZ*MTY3NDc0NDQ4Mi4zNi4xLjE2NzQ3NDYwMjkuNjAuMC4w&_ga=2.206512470.452647813.1674684706-2085144646.1655094086#using-checksession-to-acquire-new-tokens) call to verify that the user has logged in. It seems this is causing issues with Cypress.

Here's what happens:
1. Cypress visits angular app at baseURL
2. angular app calls `checkSession`
3. `checkSession` fails, redirecting cypress to the Auth0 log in page
4. Cypress logs in as described above, clicks submit button
5. Auth0 redirects cypress back to our angular app
6. Angular app calls `checkSession` to verify the log in
7. `checkSession` fails -> redirected back to Auth0 log in page
8. If we revisit the app at this point using cy.visit('/'), `checkSession` is called once more and succeeds, granting access to the app

For a typical user log in flow outside of cypress, the behaviour described in steps 1-6 is identical. However, the `checkSession` call on step 7 actually succeeds so no other redirect is necessary.

Perhaps some sort of delay as you suggest may be the solution to give the browser time to set cookies properly. Is it possible to add a delay in between when cypress submits the log in form and the browser is redirected automatically?

**Comment by gabriellemadden** [comment] 2023-01-26 15:55
I added a `cy.wait(5000)` right after the form submission command, but as expected, the wait occurred _after_ step 7 as described above.

**Comment by AtofStryker** [comment] 2023-01-26 16:02
@gabriellemadden what auth0 SDK are you using that has `Auth0.checkSession()`? I can see if I can get a reprod going

**Comment by gabriellemadden** [comment] 2023-01-26 16:14
We're using auth0-js 9.20.0, it should be `webAuth.checkSession()` as described in the docs (my bad, typo earlier)

**Comment by gabriellemadden** [comment] 2023-01-26 17:42
I was able to reproduce the behaviour in the angular auth0 app sample, please see my changes here: https://github.com/gabriellemadden/cypress-issue-25530-repro/commit/1e5a5cce2c64802a8c28dabdc36a8f0eaf1bd3a8 I left the login with redirect supplied in the app sample as is.
1. please rename `auth_config.json.example` to `auth_config.json` and supply the tenant information in there as well for the login command to proceed
2. See nav-bar-component.ts and supply the auth tenant information there in order for the check session command to work.

Note that interacting with the app manually in the browser works as expected without redirecting back to auth0, but interacting with the app in cypress results in a redirect back to the auth0 login page, and verification that the url equals the baseurl fails. Going back to the app with cy.visit() afterwards loads the app properly.

**Comment by gabriellemadden** [comment] 2023-01-26 17:49
We are opting not to use cy.origin() as the login process can find the elements in the Auth0 page without it (we are using custom domains). However, the redirecting issue persists with the following log in procedure whether we use cy.origin() or not, so I believe the issue is not related to cy.origin()
<details>
  <summary>Login without cy.origin()</summary>

```js
describe('Username/Password login via auth0', () => {
  it('logs in via Username/Password', () => {
    cy.visit('/');
    cy.get('input[type=text]').type(Cypress.env('AUTH0_USERNAME'));
    cy.get('input[type=password]').type(Cypress.env('AUTH0_PASSWORD'), {log: false});
    cy.get('form').first().submit();

    cy.url().should("contain", Cypress.config().baseUrl); // fails

    // cy.visit('/') 
  });
});
```
</details>

**Comment by AtofStryker** [comment] 2023-01-26 19:32
@gabriellemadden I forked the reproduction you posted but wasn't able to reproduce the issue. I did have to [tweak](https://github.com/gabriellemadden/cypress-issue-25530-repro/compare/main...AtofStryker:cypress-issue-25530-repro:issue-25530-tenant-tweaks?expand=1) a few things to get it working with my sample tenant. However, with or without Cypress I seem to run into this permanent reloading issue where it keeps reauthing and reloading the page. Seems to happen with the flow you posted with `chromeWebSecurity` set to `false`, which I believe is why you can interact with the auth0 content, as well as with `cy.origin()`

https://user-images.githubusercontent.com/3980464/214931514-835b0e42-9f6f-4bbb-a013-cd5f2f7e977c.mp4

https://user-images.githubusercontent.com/3980464/214931516-707e41e5-8927-476c-8439-ac45a5ad7522.mp4

What browser are you using and have you tried others to see if the behavior is the same? Any idea what may be different here?

**Comment by gabriellemadden** [comment] 2023-01-26 20:50
I have [updated my repo](https://github.com/gabriellemadden/cypress-issue-25530-repro/commit/da98c7e264fff7b010dc1aee97cba376e5178004#diff-034a3309485450d9c7f3626cbe33c0d9ccacf0a78f54a1e73f6581bd3d702fd8R21) with your changes (except for the port number) - The difference in behaviour seems to be coming from the auth domain config line. Please remove the `https://` and see if that stops the authorization loop. 

When using Chrome 109 to log in manually, I do not get redirected back to auth0 after the initial log in. 
When using Safari and Firefox to log in manually, it appears that I do actually get redirected back to auth0 in this small repro app, but not in our live app that we are trying to test. 🤔 It seems this isn't the most accurate repro. 
I am experiencing the cypress redirect on both Chrome 109 and Electron 106.

**Comment by AtofStryker** [comment] 2023-01-27 18:15
OK I pushed those changes up to the [issue-25530-tenant-tweaks](https://github.com/gabriellemadden/cypress-issue-25530-repro/compare/main...AtofStryker:cypress-issue-25530-repro:issue-25530-tenant-tweaks?expand=1) branch for reference and it seems to have stopped the redirect.

Is there anyway to get this reproduction to reproduce the issue? I wonder if there is a bug in state in the `auth0.js` library when running inside of an iframe that causes state issues. Are you able to possibly prove out using [@auth0/angular](https://www.npmjs.com/package/@auth0/auth0-angular) reproduces the same issue with Cypress so we might be able to narrow down the cause?

**Comment by peeyushohri04** [comment] 2023-02-09 15:54
@gabriellemadden Did you find any solution to this issue , even i am facing the same issue .

**Comment by mschile** [comment] 2023-02-13 16:44
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by mschile** 2023-02-13 16:44 UTC
Labels: topic: cy.origin

**Comment by gabriellemadden** [comment] 2023-02-17 22:54
Hi, some further progress: it seems that using the `WebAuth.checkSession()` function directly after navigating back to the app from the Auth0 log in page initiates a race with Auth0. For some reason, when using chrome directly, Auth0 would win this race and checkSession() would succeed. However, when using chrome through cypress or using firefox directly without cypress, I was able to observe Auth0 _losing_ the race, ie calling `WebAuth.checkSession()` upon return from the log in page would fail.

@peeyushohri04 To eliminate the race, I am now using the `WebAuth.parseHash()` method when being redirected to the app after log in to parse the credentials Auth0 is giving us directly in the callback url rather than asking Auth0 to check a session that may not have had the time to be properly created yet.

Apologies for thinking the Cypress upgrade was the culprit; it actually surfaced a race condition that we have had in our app for years! 🎉

**Comment by AtofStryker** [comment] 2023-02-20 15:00
@gabriellemadden glad you were able to find the cause and come up with a solution!
