### ISSUE TITLE
Resolving an alias obtained with a .contains() chained of cy will fail if the element needs to be requeried

### ISSUE THREAD

**Issue by Maw-Jung** [cypress-io/cypress#19562] opened 2022-01-05 12:49 UTC
### Current behavior

Hey folks,

i think i found a bug when aliasing elements straight up with **cy.contains().as()**. When the DOM refreshes and the querying for the alias happens, the type of the **.contains()** command is **child** which will try to find a **parent** type command. In the following example the previous command is an assertion, which will make cypress fail with an error. Simply inserting a line with **cy.get('body');** prior to the use of the alias is a work around one could use.

### Desired behavior

The requerying of the alias should stop at the definition of the alias in the **cy.contains()**. The previous command, whatever it might be, shall not blindly be executed in the case of assertions (i do not know which is the correct ruling here).

### Test code to reproduce

```js
  it('test requerying alias', () => {
    // use an accessable domain to reproduce
    cy.visit('https://www.cypress.io/');
    // accept cookies to prevent 403s
    cy.get('#onetrust-accept-btn-handler').click();
    // this command will be tested for prev command since the **.contains()** is treated as a **child** type and **getCommandsUntilFirstParentOrValidSubject(current)** tries to find a **parent** command
    cy.url().should('equal', 'https://www.cypress.io/features');
    // get an alias using **.contains()**
    cy.contains('Cypress is the new standard in front-end testing that every developer and QA engineer needs.').as('foo');
    // trigger reload for new element
    cy.get('header a[href="/features"]').click();
    // this will try to resolve the alias and crash the party
    cy.get('@foo').should('not.exist');
  });
```

### Cypress Version

8.7.0

### Other

Please feel free to contact/reach out for more information, tho i hope this is enough to reproduce.
Thanks,
Marcel

**Comment by Maw-Jung** [comment] 2022-01-05 12:59
Here is a screenshot of the error message:
![image](https://user-images.githubusercontent.com/27959981/148221420-79584078-73b9-4771-89f3-883f73f3e3b3.png)

**Comment by mjhenkes** [comment] 2022-01-06 21:10
@Maw-Jung I was unable to recreate this in 9.2.0 and it is functioning as i would expect. Here is my modified test case.

```js
it('test requerying alias', () => {
  // use an accessable domain to reproduce
  cy.visit('https://www.cypress.io');
  //find element and alias it
  cy.contains('Fast, easy and reliable testing for anything that runs in a browser.').as('foo');
  // verify element exists
  cy.get('@foo').should('exist');
  // visit the features page
  cy.visit('https://www.cypress.io/features/');
  // alias not found, replay cy.visit command is found.
  cy.get('@foo').should('exist');
});
```

**Comment by Maw-Jung** [comment] 2022-01-07 13:34
Thanks for your quick response, i made a mistake when pasting the code in the assertion: /features must be removed, like so:
`  it('test requerying alias', () => {
    // use an accessable domain to reproduce
    cy.visit('https://www.cypress.io/');
    // accept cookies to prevent 403s
    cy.get('#onetrust-accept-btn-handler').click();
    // this command will be tested for prev command since the **.contains()** is treated as a **child** type and **getCommandsUntilFirstParentOrValidSubject(current)** tries to find a **parent** command
    cy.url().should('equal', 'https://www.cypress.io/');
    // get an alias using **.contains()**
    cy.contains('Cypress is the new standard in front-end testing that every developer and QA engineer needs.').as('foo');
    // trigger reload for new element
    cy.get('header a[href="/features"]').click();
    // this will try to resolve the alias and crash the party
    cy.get('@foo').should('not.exist');
  });`
  
  I also updated to '9.2.0' and the behavior still persists. I am terribly sorry for the mistake!

**Comment by Maw-Jung** [comment] 2022-01-07 13:37
Can you take a second look @mjhenkes, please? Does this also crash for you or do i need to provide further informations?

**Comment by mjhenkes** [comment] 2022-01-14 19:25
This is a duplicate of #7413

**Closed by mjhenkes** 2022-01-14 19:25 UTC
Labels: type: bug, stage: ready for work
