### ISSUE TITLE
"Failed to connect to the bus: Address does not contain a colon" throws a SIGSEGV error

### ISSUE THREAD

**Issue by cubanx** [cypress-io/cypress#19299] opened 2021-12-07 20:36 UTC
### Current behavior

Our tests intermittently crash in our Docker runs with the error below. We get the `Failed to connect to the bus: Address does not contain a colon` error often, but it doesn't crash it.

But, when it *does* crash, that error is always the last one before the SIGSEGV.

I think we're going to downgrade to 8.5.0 to fix this as it wasn't happening back then. However, before we do, is there some kind of diagnostic log that will help you, help me, help you? :)

Thanks, and I know this is vague, not sure where to even start here.

```
[15:24:18]W:		 [Docker Run] [111:1207/202418.627106:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[15:24:19] :		 [Docker Run] The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Please search Cypress documentation for possible solutions:
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] https://on.cypress.io
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Check if there is a GitHub issue describing this crash:
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] https://github.com/cypress-io/cypress/issues
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Consider opening a new issue.
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] ----------
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Platform: linux-x64 (Debian - 10.10)
[15:24:19] :		 [Docker Run] Cypress Version: 9.1.1
[15:24:19] :		 [Docker Run] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[15:24:19]W:		 [Docker Run] error Command failed with exit code 1.
[15:24:19]W:		 [Docker Run] Error: Command failed with exit code 1: yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false
[15:24:19]W:		 [Docker Run]     at makeError (/workspace/Sites/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
[15:24:19]W:		 [Docker Run]     at handlePromise (/workspace/Sites/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
[15:24:19]W:		 [Docker Run]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[15:24:19]W:		 [Docker Run]   shortMessage: 'Command failed with exit code 1: yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false',
[15:24:19]W:		 [Docker Run]   command: 'yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false',
[15:24:19]W:		 [Docker Run]   escapedCommand: '"yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false"',
[15:24:19]W:		 [Docker Run]   exitCode: 1,
[15:24:19]W:		 [Docker Run]   signal: undefined,
[15:24:19]W:		 [Docker Run]   signalDescription: undefined,
[15:24:19]W:		 [Docker Run]   stdout: undefined,
[15:24:19]W:		 [Docker Run]   stderr: undefined,
[15:24:19]W:		 [Docker Run]   failed: true,
[15:24:19]W:		 [Docker Run]   timedOut: false,
[15:24:19]W:		 [Docker Run]   isCanceled: false,
[15:24:19]W:		 [Docker Run]   killed: false
[15:24:19]W:		 [Docker Run] }
[15:24:19]W:		 [Docker Run] error Command failed with exit code 1.
[15:24:19] :		 [Docker Run] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired behavior

Do not throw the SIGSEGV.

### Test code to reproduce

It can happen on any test, at any time, in our 850+ test test suite.

### Cypress Version

9.1.1

### Other

It doesn't seem to happen if we run on Windows, and we have a parallel set of Component tests (about 100) that have yet to show the issue and they're run exactly the same way in the same Docker container, just as component tests.

**Comment by Venkateshkumar1234** [comment] 2021-12-09 05:37
Facing the same issue

**Comment by VicenteRuizWefoxgroup** [comment] 2021-12-09 15:57
I have the same issue with cypress 9.1.1, randomly the execution unexpectedly exits with sigsev, rolling it back to 8.4.0 solved the problem, also I noticed that this message shows up between every spec file
`Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`
but it doesn't happen in version 8.4.0, we use cypress/base:12.16.0 image in github actions.

**Comment by cubanx** [comment] 2021-12-09 16:48
BTW, for others on here commenting, I *think* this issue and fix might help us:
https://github.com/cypress-io/cypress/issues/9220

It's committed but not yet released.

I know it's an old issue, but the fix way at the bottom is new.

Hopefully we'll get it "soon" :)

**Comment by cubanx** [comment] 2021-12-09 17:30
Also, I switched my headless runs from using headless `electron` to headless `chrome` and the issue seems to have abated.

YMMV :)

**Comment by vibaiher-qatium** [comment] 2021-12-27 12:20
I'm using 9.2.0 and I see these warnings:


```
[43:1227/121552.068477:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[43:1227/121552.072800:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon                                                      
[43:1227/121552.072876:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon                                                      
[215:1227/121552.088414:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is   
```

**Comment by joel-rw** [comment] 2021-12-29 20:47
I'm getting these when running as a github action:
```
[357:1229/202813.707201:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[357:1229/202813.707294:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[357:1229/202813.715586:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[518:1229/202813.750545:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
```
Using cypress 9.2.0, chrome 96, node version 12.22.8

**Comment by JoshuaKGoldberg** [comment] 2021-12-31 00:27
Here's a reproducing run on a public repo: https://github.com/typescript-eslint/typescript-eslint/runs/4670193488?check_suite_focus=true

```> nx run website:start 
$ docusaurus start
[2934:1230/222258.330171:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2934:1230/222258.330260:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3166:1230/222258.351104:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
Starting the development server...
Docusaurus website is running at "http://localhost:3000/".
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.

**Comment by JoshuaKGoldberg** [comment] 2021-12-31 00:30
Here's a reproducing run on a public repo on `cypress@9.2.0`: https://github.com/typescript-eslint/typescript-eslint/runs/4670193488?check_suite_focus=true

```> nx run website:start 
$ docusaurus start
[2934:1230/222258.330171:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2934:1230/222258.330260:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3166:1230/222258.351104:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
Starting the development server...
Docusaurus website is running at "http://localhost:3000/".
Cypress could not verify that this server is running:

  > http://localhost:3000

We are verifying this server because it has been configured as your `baseUrl`.
```

```
  From Node.js Internals:
    Error: ESOCKETTIMEDOUT
        at ClientRequest.<anonymous> (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/@cypress/request/request.js:808:19)
        at Object.onceWrapper (node:events:513:28)
```

[Raw logs.txt](https://github.com/cypress-io/cypress/files/7794973/Raw.logs.txt)

**Comment by cubanx** [comment] 2022-01-04 15:52
You can close this issue for my specific bug. I resolved it by switching to headless chrome.

I have not seen the `SIGSEGV` error since.

Thanks!

**Comment by fseee** [comment] 2022-01-04 17:50
> I'm getting these when running as a github action:
> 
> ```
> [357:1229/202813.707201:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
> [357:1229/202813.707294:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
> [357:1229/202813.715586:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
> [518:1229/202813.750545:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
> ```
> 
> Using cypress 9.2.0, chrome 96, node version 12.22.8

exactly same errors with below versions:
Cypress 9.1.1
Chrome 89 (headless) 
Node Version   v14.16.0

**Comment by SadiqRahim** [comment] 2022-01-07 11:43
Hi there, do we have an update on this yet? I just upgraded to the cypress image "cypress/included:9.2.0" and not able to run the tests on Jenkins anymore. This works fine when I downgraded to 8.4.0 as suggested by @VicenteRuizWefoxgroup. re: issue on #9220 appears to be closed. Does anyone know whats going on?

**Comment by cjonstrup** [comment] 2022-01-11 12:15
Cypress 9.2.1
[18:0111/121438.553429:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon

**Comment by darul75** [comment] 2022-01-11 12:39
Same issue in 8.6.0 ;)

**Comment by cjchenPG** [comment] 2022-01-12 18:46
I'm seeing the same issue in Cypress 9.1.1.

**Comment by balawej** [comment] 2022-01-12 18:50
Same issue in Cypress 9.1.1
`[STARTED] Task without title.`
`[SUCCESS] Task without title.`
`[853:0112/180551.155229:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket` `/run/dbus/system_bus_socket: No such file or directory`
`[853:0112/180551.157544:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon`
`[853:0112/180551.157587:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon`
`[1009:0112/180551.209964:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is`

**Comment by leonardofaria** [comment] 2022-01-12 20:51
Same happening here (docker) 

Cypress:        9.2.1 
Browser:        Electron 94 (headless) 
Node Version:   v16.5.0 (/usr/local/bin/node)

**Comment by patrickmichalina** [comment] 2022-01-13 06:20
I am seeing the same error all of a sudden

**Comment by JCraigWasTaken** [comment] 2022-01-14 15:58
Same happening here, I was following this: https://docs.cypress.io/guides/continuous-integration/gitlab-ci#Basic-Setup

Cypress: 9.3.0
Browser: chrome85-ff81
Node Version: 12.14.1

**Comment by bogem** [comment] 2022-01-17 08:18
The same we have in CI after update from 8.0.0 to 9.2.1.

Cypress: 9.2.1
Browser: Electron 94 (headless)
Node Version: v16.5.0 (/usr/local/bin/node)

**Comment by azoff** [comment] 2022-01-19 17:30
+1 SIGSEV
```
[1965:0119/144529.699618:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

Cypress: 9.2.1
Browser: Electron 94 (headless)
Node Version: v16.5.0

**Comment by wqsandoval** [comment] 2022-01-19 17:38
Had the same problem using ^8.3.0 on package.json. Fixed by downgrading to 8.3.0

**Comment by eLenoAr** [comment] 2022-01-20 11:55
same here in our ci :(

`[326:0120/114804.650072:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[326:0120/114804.654220:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 874: Permission denied (13)`

`Platform: linux-x64 (Debian - 10.11)
Cypress Version: 9.3.1`

**Comment by bogem** [comment] 2022-01-20 12:57
Please tap on 👍 reaction on first message in this issue to get attention of Cypress team :)

**Comment by giranm** [comment] 2022-01-22 23:15
I encountered the same issue with [GitHub Actions](https://github.com/giranm/pd-live-react/runs/4908172385?check_suite_focus=true) + Docker, but I was able to workaround (locally) using the [following post](https://github.com/cypress-io/cypress-docker-images/issues/149#issuecomment-993214455).
- Cypress: `9.2.1`
- Docker Container: `cypress/browsers:node16.13.0-chrome95-ff94`
- Node: `v16.13.0`
- Chrome Webdriver: `95.0.4638.69`

### Workaround Steps
Although the recommendation is that you run the container with `--user 1001`, I entered the container through an interactive shell and changed permissions (logged in as root). 
```
$ chmod 777 -R /root
$ chmod 777 -R node_modules/
```

Once done, I proceeded to run the Cypress tests using the following:
`$ Xvfb -screen 0 1920x1080x24 :99 & export DISPLAY=:99 && npx cypress run --browser chrome && pkill Xvfb`

To make sure that this wasn't a false positive, I edited my integration tests to assert a false statement, and confirmed the tests are working as intended.

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  app.spec.js                              00:06        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  Incidents/incidents.spec.js              00:22        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 2 failed (50%)                      00:28        2        1        1        -        -  
```

Going to do some more digging and see how I can utilise this within GitHub actions - would be great for the Cypress team to provide a proper solution / patch to this.

**Comment by jana-levesque** [comment] 2022-01-27 19:13
Same issue here (version 9.3.1) but in our CI pipeline, which also caused excessive run time (+5min) for the cypress tests. Reverted to version `8.3.1` and the issue is resolved. None of the issues above resolved it otherwise

**Comment by kasunalwis** [comment] 2022-02-03 08:49
The same issue happens when running through GitHub Actions with the below settings

Cypress:  9.4.1        
Browser:  Electron 94 (headless)    
Node Version:  v14.18.2 (/usr/local/bin/node)

**Comment by sylvaindubus** [comment] 2022-02-04 09:20
Same issue through our Gitlab pipeline on Cypress 9.3.1 / Node 16.13.1

**Comment by Jacek-fstack** [comment] 2022-02-07 07:37
I'm seeing the same with latest cypress + github actions. Tests don't crash, but they do seem to be hanging indefinitely - I'm not sure if THIS is the cause.

**Comment by redReno** [comment] 2022-02-08 08:23
I'm seeing the same error messages but the tests keep running as usual. It is polluting the output, though. I am running 9.3.1 with Electron.

**Comment by Venkateshkumar1234** [comment] 2022-02-10 04:10
Not able to use new Cypress features because of this issue.

**Comment by Venkateshkumar1234** [comment] 2022-02-10 04:14
Please add SIG to labels

**Comment by tnrich** [comment] 2022-02-18 23:39
I believe we're experiencing this issue on CI as well

**Comment by alexkhalevine** [comment] 2022-02-22 12:36
Also having problem with this issue in Gitlab CI

**Comment by msalahz** [comment] 2022-02-22 14:02
Same Here

**Comment by jonsalvas** [comment] 2022-03-01 08:10
+1 in Gitlab CI Pipeline with Image cypress/included:9.5.0

**Comment by attkeko1** [comment] 2022-03-02 01:33
Still the same error with latest versions in gitlab ci

is there a fix planned by Cypress team ?

**Comment by sachinsakpal** [comment] 2022-03-02 17:19
Most of the tests are failing on Jenkins because of this issue. Is there any workaround or solution for this?

**Comment by EugenRakhimov** [comment] 2022-03-03 00:38
Same issue here

**Comment by tnrich** [comment] 2022-03-03 02:10
Any word on the status of this from the cypress team :) ?

**Comment by Radmess** [comment] 2022-03-04 09:14
Same issue here on Jenkins pipeline. 

 "node": "v14.16.0"
 "npm": "8.5.1"
 Somehow issue persists even now that I tried to downgrade back to 8.4.1.

**Comment by fbele** [comment] 2022-03-04 16:53
I am having the same error as above but the tests are executing as expected. I am running my tests in a Pod on K8s and at first the tests were running indefinitely.
Then I've found out somwhere that headless tests are consuming a lot of resources. So after I configured my Pod template spec resources to request `cpu` to "1" and `memory` to "1Gi" and limit `cpu` to "2" and `memory` to "4Gi" my tests are running fine also with the error written above. Here is an example of my Pod template:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  containers:
  - name: cypress
    image: cypress/browsers:node16.13.2-chrome97-ff96
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
```

So to put in less words, if you have an option, try increasing the resources of whatever you are running your tests in.
Hope it helps!

**Comment by fbele** [comment] 2022-03-04 16:54
> I'm seeing the same error messages but the tests keep running as usual. It is polluting the output, though. I am running 9.3.1 with Electron, using a container derived from the official Cypress image, in Gitlab and Jenkins.

https://github.com/cypress-io/cypress/issues/19299#issuecomment-1059336091

**Comment by LarissaGuder** [comment] 2022-03-09 21:40
Same issue with v9.0.0 on CodePipeline.

**Comment by tnrich** [comment] 2022-03-09 22:10
@jennifer-shehane what's the status of this showstopper?

**Comment by nitzanashi** [comment] 2022-03-10 12:22
Same issue

**Comment by TylorMayfield** [comment] 2022-03-10 19:54
Also same :(

**Comment by kashban** [comment] 2022-03-14 08:29
Same with Cypress 9.5.1. Locally on Windows it runs fine, but in Docker Linux I get this message:

npm run cy:run:DEV
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/974a5c23-ecfa-420d-bfb0-7fb1abf9f0dc.sh

> web-pricing-dkv-pricing-e2e@1.0.0 cy:run:DEV /home/vsts/work/1/s
> cypress info && cypress run --env STAGE=DEV  --browser chrome -- --record --key recordKeyDEV

[1631:0311/151540.430654:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1631:0311/151540.430735:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1788:0311/151540.490931:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 

Displaying Cypress info...

Detected 3 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 98.0.4758.102
  - Executable: google-chrome

2. Chromium
  - Name: chromium
  - Channel: stable
  - Version: 98.0.4758.0
  - Executable: chromium-browser

3. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 97.0
  - Executable: firefox

  - Version: 97.0
  - Executable: firefox

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser chromium
- cypress run --browser chrome

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables:

Application Data: /home/vsts/.config/cypress/cy/development
Browser Profiles: /home/vsts/.config/cypress/cy/development/browsers
Binary Caches: /home/vsts/.cache/Cypress

Cypress Version: 9.5.1
System Platform: linux (Ubuntu - 20.04)
System Memory: 7.28 GB free 3.82 GB
It looks like this is your first time using Cypress: 9.5.1

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...
**[2046:0311/151557.317703:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2046:0311/151557.317775:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2202:0311/151557.390986:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is**

**Comment by JoshuaGoddard** [comment] 2022-03-21 20:26
Experiencing the same problem on 9.5.0

**Comment by nimo-juice** [comment] 2022-03-23 20:48
I've had to back track to 7.6.0, this is horrible.

**Comment by manv6** [comment] 2022-03-24 13:30
I'm getting `[10195:0324/092959.801981:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`  with 9.5.2

**Comment by anuboby** [comment] 2022-03-24 14:14
Experiencing the same problem on 9.5.0. When will this be fixed?

**Comment by Cpt-Falcon** [comment] 2022-03-24 21:25
STILL A PROBLEM!

**Comment by mobsean** [comment] 2022-03-25 09:36
Hi,

I´m running a CI with: cypress/included:9.5.2.
and get this error in the gitlab logs:
This happens with --browser chrome and with default electron browser.

```cypress run --browser chrome --reporter junit --reporter-options 'mochaFile=cypress_[hash].xml,toConsole=true'
[964:0325/101306.387739:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[964:0325/101306.389313:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[964:0325/101306.389336:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[1151:0325/101306.401999:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
tput: unknown terminal "xterm   npm_config_loglevel warn   npm_config_unsafe_perm true"
```


The run finishes successful and then still drops an error on exit:


```  (Run Finished)
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  myTest.spec.js                 00:06        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:06        1        1        -        -        -  
node:events:498
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
Uploading artifacts...
test/cypress/videos/**/*.mp4: found 1 matching files and directories 
WARNING: test/cypress/screenshots/**/*.png: no matching files 
Uploading artifacts as "archive" to coordinator... ok  id=231064 responseStatus=201 Created token=U-Aj24KV
Uploading artifacts...
cypress_*.xml: found 1 matching files and directories 
Uploading artifacts as "junit" to coordinator... ok  id=231064 responseStatus=201 Created token=U-Aj24KV
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

```

**Comment by mobsean** [comment] 2022-03-25 13:18
ok, I did some research and ran the container with debugging and exactly the same test spec.
**cypress/included:9.5.2**

```
====================================================================================================
  (Run Finished)
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  myTest.spec.js                 00:14        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:14        1        1        -        -        -  
  cypress:server:cypress about to exit with code 0 +29s
  cypress:server:browsers browsers.kill called with no active instance +2s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 40, proxyRequestsReceived: 37, immediatelyMatchedRequests: 32, eventuallyReceivedPreRequest: [ { url: 'http://localhost:8080/app/chunk-common.js', afterMs: 1 }, { url: 'http://localhost:8080/app/img/pxc_logo_transparent.png', afterMs: 4 }, { url: 'https://mpp.gocloud-dev.europe.phoenixcontact.com/graphql', afterMs: 2 } ], neverReceivedPreRequest: [ { url: 'https://redirector.gvt1.com/edgedl/chrome/dict/en-us-9-0.bdic' }, { url: '[https://r1---sn-4g5ednly.gvt1.com/edgedl/chrome/dict/en-us-9-0.bdic?cms_redirect=yes&mh=I2&mip=62.157.123.151&mm=28&mn=sn-4g5ednly&ms=nvh&mt=1648211845&mv=u&mvi=1&pl=26&rmhost=r2---sn-4g5ednly.gvt1.com&shardbypass=sd&smhost=r1---sn-4g5edn6r.gvt1.com'](https://r1---sn-4g5ednly.gvt1.com/edgedl/chrome/dict/en-us-9-0.bdic?cms_redirect=yes&mh=I2&mip=62.157.123.151&mm=28&mn=sn-4g5ednly&ms=nvh&mt=1648211845&mv=u&mvi=1&pl=26&rmhost=r2---sn-4g5ednly.gvt1.com&shardbypass=sd&smhost=r1---sn-4g5edn6r.gvt1.com%27) } ] } +0ms
2022-03-25T12:45:39.668Z cypress:cli child event fired { event: 'exit', code: 0, signal: null }
2022-03-25T12:45:39.668Z cypress:cli child event fired { event: 'close', code: 0, signal: null }
2022-03-25T12:45:39.668Z cypress:cli Stopping Xvfb
node:events:498
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
Uploading artifacts for failed job
00:01
Uploading artifacts...
test/cypress/videos/**/*.mp4: found 1 matching files and directories 
WARNING: test/cypress/screenshots/**/*.png: no matching files 
Uploading artifacts as "archive" to coordinator... ok  id=231505 responseStatus=201 Created token=zwkLyLwQ
Uploading artifacts...
cypress_*.xml: found 1 matching files and directories 
Uploading artifacts as "junit" to coordinator... ok  id=231505 responseStatus=201 Created token=zwkLyLwQ
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```


and then
**cypress/included:8.7.0**

```
====================================================================================================
  (Run Finished)
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  myTest.spec.js                 00:10        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:10        1        1        -        -        -  
  cypress:server:cypress about to exit with code 0 +25s
  cypress:server:browsers browsers.kill called with no active instance +1s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 40, proxyRequestsReceived: 37, immediatelyMatchedRequests: 32, eventuallyReceivedPreRequest: [ { url: 'http://localhost:8080/app/vendor.js', afterMs: 1 }, { url: 'http://localhost:8080/app/app.js', afterMs: 4 }, { url: 'http://localhost:8080/app/img/pxc_logo_transparent.png', afterMs: 3 } ], neverReceivedPreRequest: [ { url: 'https://redirector.gvt1.com/edgedl/chrome/dict/en-us-9-0.bdic' }, { url: '[https://r3---sn-4g5ednde.gvt1.com/edgedl/chrome/dict/en-us-9-0.bdic?cms_redirect=yes&mh=I2&mip=62.157.123.168&mm=28&mn=sn-4g5ednde&ms=nvh&mt=1648213220&mv=m&mvi=3&pl=26&rmhost=r5---sn-4g5ednde.gvt1.com&shardbypass=sd&smhost=r1---sn-4g5edn6r.gvt1.com'](https://r3---sn-4g5ednde.gvt1.com/edgedl/chrome/dict/en-us-9-0.bdic?cms_redirect=yes&mh=I2&mip=62.157.123.168&mm=28&mn=sn-4g5ednde&ms=nvh&mt=1648213220&mv=m&mvi=3&pl=26&rmhost=r5---sn-4g5ednde.gvt1.com&shardbypass=sd&smhost=r1---sn-4g5edn6r.gvt1.com%27) } ] } +0ms
2022-03-25T13:05:12.523Z cypress:cli child event fired { event: 'exit', code: 0, signal: null }
2022-03-25T13:05:12.523Z cypress:cli child event fired { event: 'close', code: 0, signal: null }
2022-03-25T13:05:12.523Z cypress:cli Stopping Xvfb
Saving cache for successful job
00:18
Creating cache someBranch...
node_modules/: found 79138 matching files and directories 
No URL provided, cache will be not uploaded to shared cache server. Cache will be stored only locally. 
Created cache
Uploading artifacts for successful job
00:01
Uploading artifacts...
test/cypress/videos/**/*.mp4: found 1 matching files and directories 
WARNING: test/cypress/screenshots/**/*.png: no matching files 
Uploading artifacts as "archive" to coordinator... ok  id=231527 responseStatus=201 Created token=vmxNBXBw
Uploading artifacts...
cypress_*.xml: found 1 matching files and directories 
Uploading artifacts as "junit" to coordinator... ok  id=231527 responseStatus=201 Created token=vmxNBXBw
Cleaning up project directory and file based variables
Job succeeded
```

The error raises when Xvfb is stopped.... maybe it´s not a cypress related issue, but at least the cypress/included:9.5.2 container is broken.

**I downgraded to cypress 8.7.0 again.**

**Comment by iammike** [comment] 2022-04-05 21:09
Also seeing this problem. Crops up for me at 8.6.0 so reverting to 8.5.0 is my answer.

**Comment by BlueWinds** [comment] 2022-04-06 16:36
So I spent a lot of time looking deep into the internals of Electron + Chromium to verify this, be extra 100% sure: these errors never cause problems, and are a red herring. There are sometimes issues where cypress fails to launch, where it fails to connect to electron of to browsers, but these errors aren't the cause.

That's why there hasn't been much motion on this issue - we were pretty sure this was the case, but didn't have time to verify it 100% until now. If you want the technical details of why these were being emitted, take a look at the PR for an explanation. They'll be silenced in the next cypress release, but this won't fix any existing issues people are running into.

**Comment by BlueWinds** [comment] 2022-04-06 20:18
As a note: "Me too" comments are not particularly useful. We look at reactions to issues when assessing seriousness - 132 thumbs up means it's very important to the community!

By all means hold conversation and discussion, and if something hasn't been updated in months, a bump may be appropriate. But "Me too" multiple times a day make it harder for everyone to find the meat of issues.

**Closed** 2022-04-07 17:46 UTC
Labels: stage: work in progress, stage: needs review

**Comment by BlueWinds** [comment] 2022-04-07 17:53
These dbus errors will be silenced in the next Cypress release. **This will not solve SIGSEGV errors**, since they were not caused by this message to begin with.

Sorry! There are quite a number of open issues discussing faults in CI / docker - I encourage people who've found this issue to search other github issues, where you're more likely to find solutions, or at least better able to provide more targeted debugging so we can tackle the real causes.

**Comment by anuboby** [comment] 2022-04-07 22:14
Switching to headless Chrome and errors are gone for us too.

**Comment by theslantedroom** [comment] 2022-04-08 19:11
> I want to reiterate for those that didn't see my comment after opening this issue.
> 
> I had all kinds of `SIGSEGV` issues with Cypress/Electron/Docker.
> 
> I switched to using headless Chrome and they all went away.
> 
> I get that may not be a solution for everyone, and if you think you can add value by helping the Cypress team with debug info, or reproducible test cases, definitely do that as I'm sure they're as frustrated with these `SIGSEGV` errors as you are.
> 
> For me and my team, running in Chrome is fine, and we have seen no downsides.
> 
> Good luck all!

Thank you in advance!  Do you have any direction as to how to switch to chrome headless for running in github ci via github action?
