### ISSUE TITLE
DOM elements not identified by the selector

### ISSUE THREAD

**Issue by MTO71** [cypress-io/cypress#4156] opened 2019-05-07 15:13 UTC
### Current behavior: 

I want to test my web application but cypress can not identify the different elements of the DOM. When I try with the selector playground, it finds me only the whole page without identifying the elements of the DOM like the login or the password in the authentication form.

After running the tests, I notice that the generated screenshots are blank. (see the screenshots added to this issue).

In this image, when I select the home page of my application, the selector finds only one page "admin-main" with `cy.get()`.

![mg_pl1](https://user-images.githubusercontent.com/50370874/57310451-206a3400-70ea-11e9-8908-4eefbc2cc56c.png)

In this image, at the end of the tests, when I select a line on the left, the screenshoot is blank.

![mg_pl2](https://user-images.githubusercontent.com/50370874/57308814-4215ec00-70e7-11e9-8c74-47b30ecf91ea.png)

### Desired behavior:

- All elements of the DOM must be identified
- The tests must not fail
- Understand why identification of DOM elements does not work in my case?
- We are using another test tool, and why this same DOM is identified with this tool ?

### Steps to reproduce: (app code and test code)

Just run the tests.

HTML
```html
<input autocapitalize="none" autocomplete="username" autocorrect="off" autofocus="" formcontrolname="username" name="username" spellcheck="false" type="text" ng-reflect-name="username" placeholder="Username" class="ng-pristine ng-invalid ng-touched">
```

Cypress
```js
describe('login feature', function() {
    beforeEach(function(){
        cy.visit('/')
    })
    it('should display nicely', function() {
        cy.url().should('contains', '/login')
        cy.get('input[name=username]').should('be.visible')
        cy.get('input[type=password]').should('be.visible')
    })
 })
```

### Versions

Cypress 3.2.0, Win 7 Pro 64bits, Chrome 74

**Comment by jennifer-shehane** [comment] 2019-05-08 08:44
Is you login form being rendered inside of an iframe? If so, we do not fully support getting elements within iframes by default - but there are many workarounds documented here. https://github.com/cypress-io/cypress/issues/136

**Comment by MTO71** [comment] 2019-05-09 08:45
jennifer-shehane 
Thank you for your help
no we do not use iframes. Do you have any other ideas or do you want me to send you other information?

**Comment by MTO71** [comment] 2019-05-13 07:52
no one to help me?
Thanks

**Comment by raphaklaus** [comment] 2019-05-13 09:13
I am going through the same problem. The website I am testing doesn't use `iframe`. Using version 3.2.0. The problem is triggered when I open a dialog with a high z-index.

I believe this is a bug since the same selector works when I am testing it outside of Cypress.

The unique iframe it uses is the one created by Cypress. A workaround I discover is to do this:

```
var iframe = document.querySelector(".size-container iframe").contentWindow.document
iframe.querySelector("YOUR QUERY HERE")
```
I would recommend downgrading the version and test it.

**Comment by MTO71** [comment] 2019-05-13 09:50
Hello,
I just tested the workaround but I have a runtime error.
Should I downgrade the Cypress version before testing this workaround?

I encounter this error : <pre>TypeError: Cannot read property 'contentWindow' of null</pre>

**Comment by raphaklaus** [comment] 2019-05-14 09:21
I have edited my last comment. I will test a new approach these next days and I will let you know.

**Comment by jennifer-shehane** [comment] 2019-05-29 08:41
Are either of you using Shadow DOM? https://github.com/cypress-io/cypress/issues/144 I haven't seen this before outside of these exceptions. 

Maybe the z-index is a clue? @MTO71 	Do you have a high z-index set on your login form?

**Comment by raphaklaus** [comment] 2019-05-29 12:51
@MTO71 have you tried: `cy.get("your-selection", {force: true}).click()` for example?

**Comment by jennifer-shehane** [comment] 2019-07-11 08:25
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. I ran the HTML and test provided, but it does not reproduce the issue. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run on our machine and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-11 08:25 UTC
Labels: stage: needs information
