### ISSUE TITLE
get and click an element from a span element with cypress

### ISSUE THREAD

**Issue by mohamedyoussefmaaref** [cypress-io/cypress#4616] opened 2019-06-30 18:51 UTC
hello 

I need to get and click on an element from a drop down list which is a span with cypress but i can,t it says that the element is hidden.
Could you plesase help me.

**Comment by jennifer-shehane** [comment] 2019-07-01 03:47
Closing as duplicate of https://github.com/cypress-io/cypress/issues/4617

**Closed by jennifer-shehane** 2019-07-01 03:47 UTC
