### ISSUE TITLE
Cypress environment variables and colons

### ISSUE THREAD

**Issue by sembel** [cypress-io/cypress#2248] opened 2018-07-31 10:48 UTC
### Current behavior:
When I start the cypress from node app:
```js
cypress.run({
    browser: 'chrome', 
    env: {
        url: 'http://10.130.58.163/app/f?p=537:3:1544354351946::NO:RP::'
    }
})
```

I receive error message: **Could not find Cypress test run results.** 
The problem is with colons in the value.

### Workaround:
```js
cypress.run({
    browser: 'chrome', 
    env: {
        url: encodeURIComponent('http://10.130.58.163/app/f?p=537:3:1544354351946::NO:RP::')
    }
})
```

and then:
```js
const url = decodeURIComponent(Cypress.env('url'));
```

### Versions

Cypress package version: 3.0.2
Cypress binary version: 3.0.2
Win10 Pro

**Comment by jennifer-shehane** [comment] 2019-01-28 05:54
Hey @sembel, I have been unable to reproduce this issue on Cypress 3.1.4 within macOS. 

- Can you verify this behavior is still happening with the newest version of Cypress?
- Can you verify if this is only an issue on Windows?

**Comment by sembel** [comment] 2019-02-03 09:37
Hi @jennifer-shehane, I don't have access to the project, where I had this issue. I have created a new test project and I cannot to reproduce this issue with the new version, also it works with 3.0.2. Not sure, why I had this issue. Maybe it was some specific Browser version, maybe some corporate firewall issues. Thanks.

**Comment by jennifer-shehane** [comment] 2019-02-04 09:44
Closing since unable to reproduce. Please comment in the future if this issue happens again and we can reopen.

**Closed by jennifer-shehane** 2019-02-04 09:44 UTC
