### ISSUE TITLE
EDDL events are not loading in cypress runner instead loading in second tab of cypress runner

### ISSUE THREAD

**Issue by ShreyaAsthana** [cypress-io/cypress#26807] opened 2023-05-19 12:10 UTC
### Current behavior

Hi Team,

When I am hitting window.appEventData in my application, without cypress it is showing three EDDL events just after website loads. And when I am running the same thing in cypress runner then it is only showing first EDDL event.
I tried to debug and I found that all three EDDLs are loading when I am opening one new tab in cypress runner window.
Unfortunately, I can not automate second tab of cypress window.
It there any solution to this problem?
Please refer below piece of code:
 cy.window().then(function (win) {
            //Validating "Page Load Started" attribute
            expect(win.appEventData[0].event).equal(event1) // Passing
            expect(win.appEventData[1].event).equal(event2) // Failing but passing in second tab of cypress runner

I am using "cypress": "12.7.0", Also I did tried the same in lower versions as well but it was not working.

### Desired behavior

If it is able to load all all EDDL events in second tabs then it should also loads EDDL events in first tab of cypress runner.

### Test code to reproduce

 cy.window().then(function (win) {
            //Validating "Page Load Started" attribute
            expect(win.appEventData[0].event).equal(event1) // Passing
            expect(win.appEventData[1].event).equal(event2) // Failing but passing in second tab of cypress runner

### Cypress Version

12.7.0

### Node version

10.24.0

### Operating System

Red Hat Enterprise Linux 8.6

**Comment by nagash77** [comment] 2023-05-19 12:42
@ShreyaAsthana Cypress does not support running in multiple tabs at this time.  I am going to close this issue at this time.  Issues in teh github repository are reserved for reproducible bugs and feature requests only.  Please check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by ShreyaAsthana** [comment] 2023-05-19 12:45
I know that cypress does not support multiple tabs. But it should show eddl events which are fired through script atleast.
It is a bug that second tab eddl events are showing but in the first tab it is not.

**Comment by nagash77** [comment] 2023-05-19 19:26
@ShreyaAsthana sorry for the confusion on my part.  Looking at the example you provided, I am unable to reproduce this behavior.  Can you please provide a reproducible example using [Cypress Test tiny](https://github.com/cypress-io/cypress-test-tiny)?  Once I have that, our engineers will be able to assist. Better.

**Comment by nagash77** [comment] 2023-05-31 12:48
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-05-31 12:48 UTC
