### ISSUE TITLE
Running cypress component tests using CSS module imports fails in nextjs based project

### ISSUE THREAD

**Issue by mvestola** [cypress-io/cypress#14200] opened 2020-12-16 14:20 UTC
### Current behavior

We have quite simple nextjs project where tried to use cypress to run [component tests](https://github.com/cypress-io/cypress/tree/master/npm/react) for our components. If using just plain JSX in our components without CSS imports, component tests work just fine. But when running cypress component tests for components which have CSS module imports, cypress fails to run the test and shows below error message in cypress window:

**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/home/user/git/my-project/cypress/plugins/index.js`)

**Details:** Error: Callback was already called.
    at throwError (/home/user/git/my-project/node_modules/neo-async/async.js:16:11)
    at /home/user/git/my-project/node_modules/neo-async/async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Stack trace:**
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/home/user/git/my-project/cypress/plugins/index.js`)
    at Object.get (/home/user/.cache/Cypress/6.1.0/Cypress/resources/app/packages/server/lib/errors.js:946:15)
    at EventEmitter.handleError (/home/user/.cache/Cypress/6.1.0/Cypress/resources/app/packages/server/lib/plugins/index.js:159:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/user/.cache/Cypress/6.1.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

```

Above error message is not that good, but when running in debug mode, from console I noticed this error:
```
error: "No module factory available for dependency type: CssDependency"
```

So the above error and the fact that without CSS imports all is ok, indicates that something is wrong with cypress handling CSS imports in these tests. Our components work just fine in development server and also in storybook, so components should be just fine. I tried with just default nextjs config in our project without any special webpack configs and same issue persists, so config should also be fine.

### Desired behavior

Should be able to run tests for components which import CSS without errors.

Also cypress example components for example nextjs project should have some components which import CSS/SCSS in here: https://github.com/cypress-io/cypress/tree/master/npm/react/examples/nextjs/components . Now they are super simple components which have just some inline styles. But could also add there CSS module imports like these to verify that cypress can run tests against these components: https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css .  CSS module imports are pretty basic stuff in nextjs and should work out of the box without any extra configurations.

### Test code to reproduce

I have these files:

MyComponentWithCss.tsx:
```
import React from "react"
import styles from "./MyComponent.module.css"

export interface MyComponentProps {
  value: string
}

export const MyComponentWithCss: React.FC<MyComponentProps> = ({ value }) => {
  return <p className={styles.myClass}>{value}</p>
}
```

MyComponent.module.css:
```
.my-class {
  background-color: red;
}
```

MyComponentWithCss.spec.js:
```
import { mount } from "@cypress/react"
import React from "react"
import { MyComponentWithCss } from "../../components/mycomponent/MyComponentWithCss"

describe("MyComponentWithCss", () => {
  it("should work", () => {
    mount(
      <div data-test-id="testing">
        <MyComponentWithCss value="testing this" />
      </div>
    )
    cy.get("[data-test-id=testing]").should(
      "have.text",
      "testing this"
    )
  })
})
```

### Versions

Our configuration was done using instructions from https://github.com/cypress-io/cypress/blob/master/npm/react/docs/recipes.md:
```
// cypress/plugins/index.js
module.exports = (on, config) => {
  require('@cypress/react/plugins/next')(on, config)
  // IMPORTANT to return the config object
  // with the any changed environment variables
  return config
}
```

Cypress etc. versions from package.json:
```
"cypress": "6.1.0",
"@cypress/react": "^4.16.0",
"next": "10.0.3",
"css-loader": "^5.0.0",
"@babel/core": "^7.12.3",
"react": "16.14.0",
"react-dom": "16.14.0",
"next-transpile-modules": "^4.1.0",
"classnames": "^2.2.6",
```

**Comment by lmiller1990** [comment] 2021-05-07 00:22
Duplicate of https://github.com/cypress-io/cypress/issues/16243

I fixed this, nextjs should work out of the box now. Here's an example: https://github.com/cypress-io/cypress-component-examples/tree/main/nextjs-webpack-4 (`yarn cypress open-ct`). I also wrote some [docs about next.js and cypress](https://docs.cypress.io/guides/component-testing/framework-configuration#Next-js-Webpack-4).

If you are still having issues with Next.js, please open a new issue. Thanks!

**Closed by lmiller1990** 2021-05-07 00:22 UTC
Labels: component testing, stage: in progress
