### ISSUE TITLE
Cypress 10.1.0 crashes after running npx cypress open with registry error

### ISSUE THREAD

**Issue by mgmacdougall** [cypress-io/cypress#22560] opened 2022-06-28 15:27 UTC
### Current behavior

After installing 10.1.0 and then issuing the npx cypress open command the UI allows me to navigate through the introduction but then crashes.  

In the crash stack trace it tells me I need admin privileges to run.

This is the exact same behaviour described in this issue:
https://github.com/cypress-io/cypress/issues/22110

There is no way for me to work around this issue if a registry change in required.  My work does not allow access to the registry.

### Desired behavior

Cypress does not crash when opening.

### Test code to reproduce

N/A as this is happening when I launch Cypress.

### Cypress Version

10.1.0

### Other

Stack trace appearing in cmd window:
```
Error: Error while obtaining machine id: Error: Command failed: %windir%\System32\REG.exe QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid
ERROR: Registry editing has been disabled by your administrator.

    at ChildProcess.exithandler (node:child_process:406:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

    at C:\Users\michael.macdougall\AppData\Local\Cypress\Cache\10.1.0\Cypress\resources\app\node_modules\node-machine-id\dist\index.js:1:7964
    at ChildProcess.exithandler (node:child_process:413:5)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by lmiller1990** [comment] 2022-06-28 23:03
Can you guide me into reproducing this? I'm not super familiar with windows - how can I configure my user so I can encounter this error? I tried a few things but I'm not able to reproduce.

**Comment by mjhenkes** [comment] 2022-07-11 20:24
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-07-11 20:24 UTC
Labels: stage: awaiting response
