### ISSUE TITLE
Cypress v4.8.0  :   Cypress fails to make connection to the Chrome DevTools Protocol 

### ISSUE THREAD

**Issue by NurmemetAbliz** [cypress-io/cypress#7873] opened 2020-07-02 16:44 UTC
Cypress fails to connect to Chrome browser  in the middle of the test execution in CI build . 

Details : 
Cypress version : 4.8.0
Browser : Chrome 81 (headless)
Build machine : Linux (ubuntu)
CI/CD tools : Microsoft Azure Pipeline
![cypress_chromeErr01](https://user-images.githubusercontent.com/67753326/86387863-cd462f80-bc61-11ea-86f8-6fdb15bac7d7.PNG)
![cypress_chromeErr02](https://user-images.githubusercontent.com/67753326/86387866-cd462f80-bc61-11ea-8d11-9c64ffa7f955.PNG)

**Comment by nani554** [comment] 2020-07-06 03:17
This is happening to me also.
Above said error is shown when when i run multiple specs in chrome.
In firefox or edge it is showing different error called "previous browser inistance is open cannot open new browser instance".

cypress: ^4.9.0
Os: windows 7
ram: 64 gb

**Comment by jennifer-shehane** [comment] 2020-07-06 05:31
Duplicate of #6540

**Closed by jennifer-shehane** 2020-07-06 05:31 UTC
