### ISSUE TITLE
Option to suppress Cypress console output when using the npm module?

### ISSUE THREAD

**Issue by YOU54F** [cypress-io/cypress#4282] opened 2019-05-22 20:55 UTC
Hey,

I'm testing an [adaptor](https://github.com/YOU54F/cypress-jest) to run Cypress with Jest, and I have got it working locally & CI utilising the Cypress npm module.

It's working after some initial testing, but I would like to suppress the console output, and just utilise the returned [RunResult](https://github.com/cypress-io/cypress/blob/4521cdcc87414def652fb622942d2ab0c2bc4db6/cli/types/cypress-npm-api.d.ts#L395)

I wondered if the PR might be of use - https://github.com/cypress-io/cypress/pull/2079 will test it in a fork :)

### Current behavior:

Can run cypress with Jest, but the cypress npm runner will write to the console.

```
> jest --env=node
It looks like this is your first time using Cypress: 3.3.0
[11:52:04]  Verifying Cypress can run /home/travis/.cache/Cypress/3.3.0/Cypress [started]
[11:52:06]  Verifying Cypress can run /home/travis/.cache/Cypress/3.3.0/Cypress [completed]
Opening Cypress...
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.3.0                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      1 found (integration/happy_spec.js)                                                │
  │ Searched:   cypress/integration/happy_spec.js                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: integration/happy_spec.js...                                                    (1 of 1) 
  ✓ visits a page (715ms)
  1 passing (3s)
  (Results)
  ┌─────────────────────────────────────────┐
  │ Tests:        1                         │
  │ Passing:      1                         │
  │ Failing:      0                         │
  │ Pending:      0                         │
  │ Skipped:      0                         │
  │ Screenshots:  0                         │
  │ Video:        true                      │
  │ Duration:     3 seconds                 │
  │ Spec Ran:     integration/happy_spec.js │
  └─────────────────────────────────────────┘
  (Video)
  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /home/travis/build/YOU54F/cypress-jest/cypress/videos/integration/happy_spec.js.mp4 (1 second)
====================================================================================================
  (Run Finished)
      Spec                                                Tests  Passing  Failing  Pending  Skipped 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔ integration/happy_spec.js                 00:03        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    All specs passed!                           00:03        1        1        -        -        -  
 PASS   cypress  cypress/integration/happy_spec.js
  ✓  (3095ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        16.135s
Ran all test suites.
```

### Desired behavior:

```
> jest --env=node
 PASS   cypress  cypress/integration/happy_spec.js
  ✓  (3095ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        16.135s
Ran all test suites.
```

### Versions

Cypress 3.3.0

**Comment by jennifer-shehane** [comment] 2019-05-30 07:23
Duplicate of https://github.com/cypress-io/cypress/issues/2071

**Closed by jennifer-shehane** 2019-05-30 07:23 UTC
Labels: stage: proposal 💡, type: feature
