### ISSUE TITLE
Slow Stubbing

### ISSUE THREAD

**Issue by OmriAharon** [cypress-io/cypress#2081] opened 2018-07-01 12:31 UTC
### Current behavior:
I'm stubbing all of my backend requests, though I'm not seeing much improvement in speed. 

According to the docs:

> Stubbing is extremely fast, most responses will be returned in less than 20ms.

However, my requests take very close to 1s, even ones that are blocked in `cypress.json` as blacklisted domains and are visible as red text lines. See screenshot below, covering a 2.5 seconds section:

![image](https://user-images.githubusercontent.com/12033595/42134472-0d0be3f2-7d45-11e8-880d-240ae26f3177.png)

### Desired behavior:
I expect the stubs to be blazing fast.

### Steps to reproduce:
I'm keeping hard coded data as mocks in their own respective files.
Example of how I stub: (shortened for brevity, but maybe I'm doing something wrong?)

```js
const userMock = require('../ui-fixtures/user.json');

Cypress.Commands.add('useMocks', () => {
  cy.server({ matchBase: false });
  cy.route(XHRPaths.USER, userMock);
  // about 10 other mocks
});
```

This is how I use it:

```js
// inside a describe block
beforeEach(function() {
  cy.useMocks();
  cy.visit('/');
});

it('...', function () {
   // some simple tests
});
```

### Versions
Cypress 3.0.1
MacOS High Sierra

**Comment by brian-mann** [comment] 2018-07-01 20:35
We'd need you to create a tiny reproducible repo that we can clone. You should be able to create a tiny page that makes a single blacklisted request and also a single XHR that you stub.

After you create this, take a picture of your dev tools network traffic and then export that data as HAR and add it to your source so we can inspect it. My hope is that you can get the same slow behavior on a small reproducible repo.

Likely this is something specific to your computer / environment that we'd need to better understand in order to figure out what's going on. What you're experiencing is certainly not normal, but it will take some digging to find out. We run thousands of tests inside of Cypress that use stubbing (and a ton of our users do this) and this is not the normal performance.

**Comment by brian-mann** [comment] 2018-07-01 20:36
You may also want to try to use `3.0.2` since we fixed some proxy related things in there - but I can't see how those things would fix what you're seeing.

**Comment by OmriAharon** [comment] 2018-07-02 09:58
Thanks for the quick response @brian-mann.
I'm trying to create to repo, although the stubs are working fine there. I'm trying to close the gaps between my app and this tiny repo (include react, react-hmr, babel, etc..) until I can find what's slowing this down, but no luck so far.

In the meantime, I've analyzed a test using the Performance tab in devtools and tried to drill down on the long XHR requests. I've noticed where a lot of time being spent in the test runner:

![image](https://user-images.githubusercontent.com/12033595/42156408-aa9800ac-7df3-11e8-8da9-ade2d3c0dd02.png)

A high level of the performance call tree:

![image](https://user-images.githubusercontent.com/12033595/42157595-ceb0aec8-7df6-11e8-8526-d6b537381860.png)

Not sure if it's any help or not. Anything else I can do in the meantime?

**Comment by OmriAharon** [comment] 2018-07-03 11:12
I created the repo, it shows slow mocks, but not as slow as the initial issue. I did strip down a lot of code/mocks which might affect it. At the moment the mocks take between 30ms and 90ms, with the average of about 50-60. This seems high enough to demonstrate the point I think.

https://github.com/OmriAharon/CypressSlowStub

**Comment by OmriAharon** [comment] 2018-07-05 11:09
@brian-mann repo is above, please let me know if you need anything else, I'd really like to figure this out as our current situation is having 30-40 tests take 4 minute and this is really not scalable 😞

**Comment by jennifer-shehane** [comment] 2018-07-12 19:24
Hey @OmriAharon, thanks for the repo. I was unable to get the server up and running in the repo however. 

There were a couple of dev deps missing that I did install such as `uglifyjs-webpack-plugin` and `opn` in order to get the `npm start` command running without error, but nothing displays at the opened web address now after `npm start`. Let me know what I'm missing. Maybe the node/npm version? I'm not sure.

**Comment by OmriAharon** [comment] 2018-07-12 20:02
Thanks @jennifer-shehane, my bad there - guess I cleaned a little to much there.
Pushed the changes and updated the readme, should be all good now 👍

**Comment by jennifer-shehane** [comment] 2018-07-12 21:56
Ok, I got it up and running now and it appears to be stubbing lightning fast for me. 😬 

![screen shot 2018-07-12 at 5 55 52 pm](https://user-images.githubusercontent.com/1271364/42661656-d9c0798e-85fc-11e8-8f5d-97c28879b02b.png)

![screen shot 2018-07-12 at 5 48 45 pm](https://user-images.githubusercontent.com/1271364/42661374-0187c748-85fc-11e8-96f5-74e93ca9b1d6.png)

- Could you send a screenshot of the [Command Log](https://on.cypress.io/test-runner#Command-Log) when it is running with the Network logs open? 
- Are you running this in Chrome? Version? 
- Could you try running `DEBUG=cypress* cypress open` and see if there are any unusual logs captured when you run the test?

**Comment by OmriAharon** [comment] 2018-07-13 09:41
Thanks for looking at this @jennifer-shehane.

- Chrome version: Version 66.0.3359.170 (Official Build) (64-bit)
- Screenshot of the command log:
![image](https://user-images.githubusercontent.com/12033595/42684651-66be5a3a-8699-11e8-84ab-3a7b846b0aab.png)

Just to make sure we're indeed getting different results, the `46ms` and the `35ms` XHR requests are what I consider slow here (and in the full project this bloats up to about a second or even more), that's too much, correct?

- Ran with the debug option, not sure if there's anything there I should consider unusual. There were a few `cors` lines that had `+1 ms` at the end. In any case, I copied the text and added to the repo under `Logs` folder. Hope it helps 🤞

**Comment by OmriAharon** [comment] 2018-07-13 09:49
And here is one from the performance tab (from a different test run though):
![image](https://user-images.githubusercontent.com/12033595/42685237-1bda61c4-869b-11e8-9d4a-787e8ffbe2d3.png)

**Comment by OmriAharon** [comment] 2018-07-13 09:52
Another note - this is the same case for a team of about 5 devs working on the same repo, making this something very specific to my machine.

**Comment by OmriAharon** [comment] 2018-07-22 14:19
@jennifer-shehane 
Update: I've found a developer who manages to run the mocks super fast as they should be on the same repo (both the original one and the tiny reproducible one). The tests still take a long time to run, but that's a topic for a different issue. 
I'm concluding:

- It's probably something in our machines, as most of us are still seeing insanely high mocking times. (3s+ worst case). Not sure if it's something we have installed or not and Chrome doesn't run extensions in incognito mode, maybe it's affected by other things though?
- It is probably not related to any of the 3rd party packages listed in the `package.json`.
- It's not related to the node version, as we worked on the same node version, and mocks were fast on 2 different ones as well.

Would be glad to test any lead you may have, I'm getting a little despaired here.

**Comment by OmriAharon** [comment] 2018-07-23 11:54
@brian-mann 😱 
Canary solves it! 
![image](https://user-images.githubusercontent.com/12033595/43064121-b541b4de-8e66-11e8-81ff-1e7155a978e7.png)

Unfortunately, like you said, this doesn't affect the runtime of our tests, which are still 2.5~ minutes for about ~30 tests, so I need to try and isolate that issue as well. Tests could have many (10-20) assertions, but still not something that should be taking that long. I'll try to focus on that and perhaps raise a new issue.

If that is sufficient for you we can close this issue, but if you're still interested in the root cause of the regular Chrome let me know. If you want me to run some more tests, I'd be happy to assist.

**Comment by tysonnero** [comment] 2018-12-03 16:14
@OmriAharon Are you still having issues, and if not, how did you remedy it?

I'm seeing a 300ms response time for a 5kb file. To make my tests not fail, I have to increase the request timeout to 10 secs: `"requestTimeout": 10000`.

**Comment by OmriAharon** [comment] 2018-12-05 07:37
@tysonnero I'm still experiencing this issue unfortunately.

**Comment by tysonnero** [comment] 2018-12-05 21:49
@OmriAharon I will try to put together a sample repo

**Comment by jennifer-shehane** [comment] 2019-06-06 06:40
Closing in favor of https://github.com/cypress-io/cypress/issues/2206

**Closed by jennifer-shehane** 2019-06-06 06:40 UTC
Labels: stage: needs investigating, type: performance 🏃‍♀️
