### ISSUE TITLE
Specs order during parallelization not being updated quickly enough when spec goes from short duration to long duration.

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#4401] opened 2019-06-06 04:55 UTC
### Current behavior:
I had a long-running spec that was having issues.  Because I wanted to trouble-shoot this spec without causing the entire run to fail, I added a skip to the tests in the file, but left the spec in our Cypress solution.  Thus the first few times the spec file was recorded, it was extremely short, making it the last spec to be kicked off.  However, the spec is now fixed, and is actually one of the longest specs we have, meaning that it instead should run first.  Since we are using parallelization, this nearly doubles our runtime.

Even after many runs where it took longer than any other spec, it remained in the last position.  As a workaround, I rename the file so that it got a fresh start according to the moving average.

I see that the Dashboard FAQ states: _[...] we can order specs by the moving average of the previously recorded durations_, however I don't see anywhere in the docs a detailed description about how this moving average and ordering are calculated and updated.

### Desired behavior:
These first two suggestions seem like responses that I would consider bugfixes, while the third is more of of a feature request.  I think I'm more interested in the first two options, but wanted to list the third option as well in case other people thought it was a good idea.
1) Increase the documentation around how the dashboard ordering process works today.
2) Possibly modify the moving average behavior to respond more quickly/dramatically to changes such as the one I described above.

3) Possibly add a feature that allows some kind of manual override of the spec ordering behavior.

### Steps to reproduce: (app code and test code)
0) Set up parallelization
1) Create a long running spec file, but add 'skip's to all the tests
2) Implement a series of recorded runs that hit your dashboard which include this long-running spec, such that the spec ends up at the bottom of the list and runs last
3) Remove the skips from the file
4) Continue doing more recorded runs on the dashboard

Notice that the file remains at the end.

### Versions
Current version of the Cypress Dashboard

**Comment by jennifer-shehane** [comment] 2019-06-06 09:01
cc @cypress-io/services

**Comment by trydionel** [comment] 2019-06-06 15:23
Hey calvinballing, thanks for the excellent report. We're still taking a look at what we could do about that situation. In the mean time, you could try renaming the spec file in question. The Dashboard should run it first since it's a "new" file, and then keep running it first since it would have a history of long runtimes only.

**Comment by calvinballing** [comment] 2019-06-06 15:30
@trydionel Good suggestion.  Yes, that workaround was successful for me as mentioned in the Current Behavior section above. 

With another spec I tried an alternate method of doing a rename once, then renaming it back to the original name to see if that would allow a permanent fix while retaining the originally desired filepath.  It was only treated as a new spec after the first renaming however, and not after renaming back to the original.  So this alternate version of the fix was not successful.

**Comment by jennifer-shehane** [comment] 2021-02-04 06:01
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-02-04 06:01 UTC
Labels: external: api, stage: needs investigating
