### ISSUE TITLE
unable to select element from autocomplete

### ISSUE THREAD

**Issue by SornaSundaram** [cypress-io/cypress#6721] opened 2020-03-13 18:16 UTC
Current behavior this is the code i use to search a vuetify autocomplete.

```js
cy.get('[data-testid="select-patient"]').click().focused().type(patientId+'{downarrow}{enter}',{force:true});
cy.get('[data-testid="select-patient"]').should('have.value',patientId);
```
expected behaviour is that after finding the element it should be selected in the autocomplete.

## Current behavior:

after finding the element id is not selected in the autocomplete.
but this code works properly as expected
```js
cy.get('[data-testid="select-patient"]').click().focused().type(patientId+'{downarrow}{enter}',{force:true});
cy.wait(3000);
cy.get('[data-testid="select-patient"]').should('have.value',patientId);
```

but adding arbitrary wait is a bad practice mentioned in your guidelines. so how can i overcome this delay issue?

Test code :
```js
cy.get('[data-testid="select-patient"]').click().focused().type(patientId+'{downarrow}{enter}',{force:true});
cy.get('[data-testid="select-patient"]').should('have.value',patientId);
```

**Comment by jennifer-shehane** [comment] 2020-03-16 08:30
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue provided the HTML or test site to run the above tests against and we will consider reopening the issue.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Closed by jennifer-shehane** 2020-03-16 08:30 UTC

**Comment by jennifer-shehane** [comment] 2020-03-16 09:35
Duplicate of https://github.com/cypress-io/cypress/issues/6721 - please do not open an issue when you already have one open, we revisit the issues and will reopen if necessary.

**Comment by joeldbirch** [comment] 2020-05-06 04:04
This is #6721. Which is the other issue, please?

**Comment by jennifer-shehane** [comment] 2020-05-06 05:19
Sorry yes. Duplicate of #6716

**Comment by Roberto-Stanley** [comment] 2024-08-03 18:35
I resolved the same issue, I dropped the code here is this another issue [#6716 here](https://github.com/cypress-io/cypress/issues/6716#issuecomment-2267096495)
