### ISSUE TITLE
Aw Snap Out Of Memory Issue

### ISSUE THREAD

**Issue by UsmanKarim08** [cypress-io/cypress#28662] opened 2024-01-08 20:26 UTC
### Test code to reproduce

we have 476 teste cases in our project so far when we execute them together browser crash and give us Aw Snap Out Of Memory
error it happen when we run bunch of test cases together. But when we run the individually they run good. can you please help us to resolove that issue

### Cypress Mode

cypress run

### Cypress Version

v12.17.2

### Browser Version

v120

### Node version

v20.5.1

### Operating System

windows 10

**Comment by Greegko** [comment] 2024-01-09 14:35
I have just had the same issue yesterday, as we do many combinations for exploration tests.

Even for a most simplified case it could be reproduced the memory leak:
```ts
import { range } from 'lodash-es';

describe('Find Memory Leak', () => {
  range(1, 500).forEach((i) => {
    it('Yeah - ' + i, () => {
      cy.visit('https://google.com');
      cy.get('body').click();
    });
  });
});
```

After 140 / 500 the memory is already 3 GB (`Cypress Helper (Renderer)` on mac resource monitor terminal). I set the config: `screenshotOnRunFailure: true` even to true to make sure it should be empty.
Tried with Chrome and Electron as well, with 13.2.0 and 13.6.2 versions as well.
It seems doesn't matter if the test fails or is success. I thought the similar issue raised again as https://github.com/cypress-io/cypress/issues/18549, but haven't seen any similarity yet.

Upd:

It even crashed with the following message
```
<--- Last few GCs --->

[46350:0x148008000]   432069 ms: Mark-Compact (reduce) 2709.6 (3276.9) -> 2708.1 (3243.0) MB, 2659.42 / 0.04 ms  (average mu = 0.107, current mu = 0.022) last resort; GC in old space requested
[46350:0x148008000]   434541 ms: Mark-Compact (reduce) 2708.1 (3243.0) -> 2707.8 (3226.3) MB, 2470.33 / 0.00 ms  (average mu = 0.058, current mu = 0.001) last resort; GC in old space requested


<--- JS stacktrace --->

[46350:0109/153626.318295:ERROR:v8_initializer.cc(753)] V8 javascript OOM (CALL_AND_RETRY_LAST).
We detected that the Electron Renderer process just crashed.

We have failed the current spec but will continue running the next spec.

This can happen for a number of different reasons.

If you're running lots of tests on a memory intense application.
  - Try increasing the CPU/memory on the machine you're running on.
  - Try enabling experimentalMemoryManagement in your config file.
  - Try lowering numTestsKeptInMemory in your config file during 'cypress open'.

You can learn more here:

https://on.cypress.io/renderer-process-crashed
```

Upd: I didn't mention but all those configs adjustment didn't help, settings keptInMemory to 5, and run in chrome with MemoryManagement resulted the same issue.

**Comment by banjahman** [comment] 2024-01-09 17:22
I've been experiencing the same thing with our suite, it's been a problem for over a year. I've been working on finding a workaround but haven't been able to yet. It's definitely an issue with Cypress.

**Comment by akshaygupta5233** [comment] 2024-01-10 19:39
I too agree with this, running many test cases at once is throwing this error!
I tried with below configs also, still the same error
  numTestsKeptInMemory: 0,
    experimentalMemoryManagement: true,

**Comment by ivanharalampiev** [comment] 2024-01-30 16:36
at this point imo the best solution is to migrate to playwright like the rest of the world. cypress is just shrugging issues under the rug and calling it a day. just search for all the OOM issues reported before and you'll have pretty good idea what will happen to this one.

**Comment by bensouth** [comment] 2024-02-09 16:07
Same for me. No fix.

**Comment by banjahman** [comment] 2024-02-09 16:28
> at this point imo the best solution is to migrate to playwright like the rest of the world. cypress is just shrugging issues under the rug and calling it a day. just search for all the OOM issues reported before and you'll have pretty good idea what will happen to this one.

I recently starting porting our codebase over to playwright. It's very similar in syntax, so the migration is pretty easy. Playwright runs faster, better, more reliably, has more features, and costs far less. At this point sticking with Cypress is shooting yourself in the foot. I tried to give them a chance to fix the show stopping issues but all that ever gets done are closed issues without any resolution.

**Comment by Jacek-fstack** [comment] 2024-03-19 12:05
Same thing for me - never was an issue with Electron, but here we are

**Comment by LukasLewandowski** [comment] 2024-03-25 12:04
Any update on this? Workaround? It is a blocker for executing more tests on CI as memory is not released between tests.

**Comment by Jacek-fstack** [comment] 2024-04-02 12:37
Any updates @jennifer-shehane ?

**Comment by Jacek-fstack** [comment] 2024-04-02 14:34
@banjahman how long did it take you to migrate to Playwright? How many tests did you have?

**Comment by stepanroznik** [comment] 2024-06-18 07:55
For me, changing the Cypress version from 3.11.0 to 3.6.0 helped. Might work as a workaround for some. I also have experimentalMemoryManagement enabled.

**Comment by jennifer-shehane** [comment] 2024-06-25 13:48
@stepanroznik It'd be great to have an example for us to reproduce this. We/d be very interested in tracking down a performance regression.

**Comment by maoyu-test** [comment] 2024-07-10 07:56
This problem has been bothering me for two years now

**Comment by Greegko** [comment] 2024-07-10 09:01
> @stepanroznik It'd be great to have an example for us to reproduce this. We/d be very interested in tracking down a performance regression.

Hey, as mentioned the second comment even the most basic tests crash: https://github.com/cypress-io/cypress/issues/28662#issuecomment-1883163363

**Comment by jennifer-shehane** [comment] 2024-07-30 17:07
Going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/27415#issuecomment-2258782755

**Closed as duplicate by jennifer-shehane** 2024-07-30 17:07 UTC
Labels: type: duplicate

**Comment by StanKarpenko1** [comment] 2025-02-12 21:13
I have an assumption that the crash of my testing suite is somehow connected to the use of recursion. The testing suites that crashed for me included functions where recursion was implemented. I had to either rewrite or skip the tests involving recursion, and this seemed to help

**Comment by banjahman** [comment] 2025-02-13 21:39
> [@banjahman](https://github.com/banjahman) how long did it take you to migrate to Playwright? How many tests did you have?

@Jacek-fstack 

sorry for the delay in replying, I didn't see this come through.

it took our team around a year to migrate ~800 tests over to playwright. Our cypress implementation abstracted a lot of the common functionality like clicks and visibility checks, so it made it a lot easier as the bulk of the tests didn't change much, and it was more so modeling our common layer to use the playwright API over cypress.

That said, the migration went very smoothly and we didn't run into many problems at all. Performance is great, and I find it easier to write tests as well.

It's unfortunate, and seeing this issue get closed without resolution is only going to continue to push people away from cypress. 

> I have an assumption that the crash of my testing suite is somehow connected to the use of recursion. The testing suites that crashed for me included functions where recursion was implemented. I had to either rewrite or skip the tests involving recursion, and this seemed to help

@StanKarpenko1 that's a good observation. I recall this problem showing up when we had implemented some pretty complex tests that did a lot of recursion to get through a module. Hopefully that helps someone else experiencing the same problem, or the devs to find the root cause of the bug.
