### ISSUE TITLE
Tests causing CI agents to run out of memory on cypress 10.3

### ISSUE THREAD

**Issue by Stanley9292** [cypress-io/cypress#23035] opened 2022-08-01 08:11 UTC
### Current behavior

The Jenkins Job that I'm running on a linux machine gives the following error after running end to end tests for about 40 minutes. Our tests should finish in about 2.5 hours. 
The same behavior happens also on local environment.

```
[2022-07-29T10:46:00.220Z] <--- JS stacktrace --->
[2022-07-29T10:46:00.220Z] 
[2022-07-29T10:46:00.220Z] ==== JS stack trace =========================================
[2022-07-29T10:46:00.220Z] 
[2022-07-29T10:46:00.220Z]     0: ExitFrame [pc: 0x1376259]
[2022-07-29T10:46:00.220Z] Security context: 0x1a7fa62408a1 <JSObject>
[2022-07-29T10:46:00.220Z]     1: setParentPointers(aka setParentPointers) [0x2db1979fa189] [/home/jenkins/agent/workspace/CMS-Setup_automation_vmware/node_modules/typescript/lib/typescript.js:~34636] [pc=0x22eef1dce32](this=0x253766d404a9 <undefined>,0x0b472aa86281 <NodeObject map = 0x365fd9d283e1>,0x0b472aa86619 <IdentifierObject map = 0x365fd9d27da1>)
[2022-07-29T10:46:00.220Z]     2: /* anonymous */(aka /* anony...
[2022-07-29T10:46:00.220Z] 
[2022-07-29T10:46:00.220Z] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[2022-07-29T10:46:00.220Z] 
[2022-07-29T10:46:00.220Z] Writing Node.js report to file: report.20220729.134611.5391.0.001.json
[2022-07-29T10:46:00.220Z] Node.js report completed
[2022-07-29T10:46:00.220Z]  1: 0x9dab70 node::Abort() [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  2: 0x9dbd26 node::OnFatalError(char const*, char const*) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  3: 0xb3b18e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  4: 0xb3b509 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  5: 0xce68a5  [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  6: 0xce6f36 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  7: 0xcf2dca v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  8: 0xcf3cd5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z]  9: 0xcf66e8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z] 10: 0xcbd017 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z] 11: 0xff307b v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [Cypress: Config Manager]
[2022-07-29T10:46:00.220Z] 12: 0x1376259  [Cypress: Config Manager]
Aborted by Alexandru-George Stan
[2022-08-01T07:38:21.497Z] Sending interrupt signal to process
[2022-08-01T07:38:31.243Z] [5375:0801/103837.696595:ERROR:connection.cc(66)] X connection error received.
[Pipeline] junit
```

Cypress:        10.3.0                                                                       
Browser:        Chrome 103 (headless)                                                         
Node Version:   v12.14.0

### Desired behavior

Tests should finish. 

### Test code to reproduce

1. Run all tests: cypress run --browser=chrome --headless --config-file=cypress.config.ts
2. Wait for the tests to fail with the error. 

### Cypress Version

10.3.0

### Other

Nope

**Comment by ezrag26** [comment] 2022-08-01 10:16
I also receive an Out of Memory error after running about 10 minutes of tests

![image](https://user-images.githubusercontent.com/36003744/182126424-3217da5d-c950-4d25-bbc6-20054e69323f.png)

**Comment by rockindahizzy** [comment] 2022-08-10 15:21
@Stanley9292 thanks for reporting this issue. I'm curious how much memory your jenkins job runner has access to. 

Are you able to provide a public repo that reproduces this error? It would help us track down the root cause.

**Comment by mjhenkes** [comment] 2022-08-17 18:11
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed** 2022-08-17 18:11 UTC
Labels: stage: awaiting response, Needs Reproduction
