### ISSUE TITLE
Cypress crashed with error: JavaScript heap out of memory

### ISSUE THREAD

**Issue by tit** [cypress-io/cypress#21280] opened 2022-04-30 20:06 UTC
### Current behavior

I have more than 800 tests running inside Docker/Jenkins.
Docker: cypress/included:9.6.0
A full run of the tests takes approximately 16 hours.
About 90% of the tests fail with an error.

```
16:46:29    C542557
16:47:37      ✓ last passed test (66055ms)
16:47:37  
16:47:37  
16:47:37    1 passing (1m)
16:47:37  
16:47:37  [mochawesome] Report JSON saved to /home/ubuntu/workspace/results/mochawesome_results/mochawesome_788.json
16:47:37  
16:47:42  
16:47:42  <--- Last few GCs --->
16:47:42  
16:47:42  [96:0x4dc001dc000] 57881350 ms: Mark-sweep 1963.1 (2067.1) -> 1962.4 (2065.1) MB, 1545.7 / 0.1 ms  (average mu = 0.934, current mu = 0.129) allocation failure scavenge might not succeed
16:47:42  [96:0x4dc001dc000] 57883793 ms: Mark-sweep 1970.1 (2065.1) -> 1969.9 (2081.1) MB, 2413.7 / 0.1 ms  (average mu = 0.843, current mu = 0.012) allocation failure scavenge might not succeed
16:47:42  
16:47:42  
16:47:42  <--- JS stacktrace --->
16:47:42  
16:47:42  [96:0430/134741.526166:ERROR:node_bindings.cc(143)] Fatal error in V8: Reached heap limit Allocation failed - JavaScript heap out of memory
16:47:42  [278:0100/000000.936143:ERROR:connection.cc(66)] X connection error received.
16:47:42  [278:0100/000000.936182:ERROR:connection.cc(66)] X connection error received.
16:47:42  jake aborted.
16:47:42  Error: The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
16:47:42  
16:47:42  Please search Cypress documentation for possible solutions:
16:47:42  
16:47:42  https://on.cypress.io/
16:47:42  
16:47:42  Check if there is a GitHub issue describing this crash:
16:47:42  
16:47:42  https://github.com/cypress-io/cypress/issues
16:47:42  
16:47:42  Consider opening a new issue.
16:47:42  
16:47:42  ----------
16:47:42  
16:47:42  Platform: linux-x64 (Debian - 11.3)
16:47:42  Cypress Version: 9.6.0
16:47:42      at /home/ubuntu/workspace/node_modules/cypress/lib/errors.js:265:17
16:47:42      at tryCatcher (/home/ubuntu/workspace/node_modules/bluebird/js/release/util.js:16:23)
16:47:42      at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:547:31)
16:47:42      at Promise._settlePromise (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:604:18)
16:47:42      at Promise._settlePromise0 (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:649:10)
16:47:42      at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:729:18)
16:47:42      at Promise._fulfill (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:673:18)
16:47:42      at Promise._resolveCallback (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:466:57)
16:47:42      at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:559:17)
16:47:42      at Promise._settlePromise (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:604:18)
16:47:42      at Promise._settlePromise0 (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:649:10)
16:47:42      at Promise._settlePromises (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:729:18)
16:47:42      at Promise._fulfill (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:673:18)
16:47:42      at Promise._resolveCallback (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:466:57)
16:47:42      at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:559:17)
16:47:42      at Promise._settlePromise (/home/ubuntu/workspace/node_modules/bluebird/js/release/promise.js:604:18)
```

Tests are run via the Cypress Module API inside the Jake.
I tried running tests with a flag for node: `node --max-old-space-size=8192 /usr/local/bin/npx jake cypress:run:ci`.
It didn't help.

### Desired behavior

Tests should not crashed

### Test code to reproduce

I can't provide a working repository with tests...

### Cypress Version

9.6.0

**Comment by davidmunechika** [comment] 2022-05-02 14:12
Duplicate of : https://github.com/cypress-io/cypress/issues/21124, https://github.com/cypress-io/cypress/issues/20846, https://github.com/cypress-io/cypress/issues/17853

**Comment by mjhenkes** [comment] 2022-05-02 17:48
@tit Thanks for reporting this, It looks like this is a duplicate of #17853, Please follow along with that thread for any resolutions.

**Closed by mjhenkes** 2022-05-02 17:48 UTC
Labels: type: duplicate

**Comment by insistedMarin** [comment] 2022-11-30 11:03
I get the same problem at version 11.2.0.
