### ISSUE TITLE
file download not working in electron

### ISSUE THREAD

**Issue by sharky910** [cypress-io/cypress#20911] opened 2022-04-05 10:04 UTC
### Current behavior

I am getting the same issue as #14747 but on 9.5.3, when using my cucumber test to download the file cypress is crashing (using Electron). 

This is the test I have written: 
![image](https://user-images.githubusercontent.com/87695585/161729940-11092e67-a48a-48f7-98fe-2c17e1c68b82.png)

and the error I am getting: 

![image](https://user-images.githubusercontent.com/87695585/161729979-2e180d3b-4d9f-43c0-9825-1b9f832b3229.png)

I have been removing the target so the second page does not open and it all opens on one page and this has worked for other fields but not this xlsx file.

### Desired behavior

Download the XLSX file to a Download Folder without crashing

### Test code to reproduce

```js
import {Then} from "cypress-cucumber-preprocessor/steps";

Then(`I click on button {string}`, (button) => {
    switch(button){
        case "Download Guide":
        cy.get('.fa-download').invoke('removeAttr', 'target').click();
        break;
```
-----

`'<p class="mb-20px"><a :href="propertyExcelGuideURL" target="_blank"><i class="fas fa-download"></i> Download guide/sample file</a>' +`

### Cypress Version

9.5.3

**Comment by archfz** [comment] 2022-11-01 22:41
I am getting this issue on cypress 10.10.0. I was before on 9.5.3 and it wasn't reproducing. The whole cypress process dies. Removing target blank only improves this by not crashing cypress, but download still doesn't work.

**Comment by AlenaHalotaAbsa** [comment] 2022-12-23 13:21
I'm having the same issue in Cypress 10.4.0.

Test:

cy.get('[class="ti-new-window"]').eq(0).click().then(() => {
                    cy.verifyDownload();
                })

Result:
Error: ERR_FAILED (-2) loading '------/download'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)

**Comment by flotwig** [comment] 2023-02-27 16:04
This is seemingly a duplicate of #18547, closing

**Closed by flotwig** 2023-02-27 16:04 UTC
Labels: browser: electron, stage: backlog, topic: downloads ⬇️
