### ISSUE TITLE
Missing source and CI name information from Zeit Now GitHub integration app

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2434] opened 2018-09-05 13:21 UTC
When recording tests from Zeit Now GitHub application on a pull request, the dashboard is missing all Git commit information and CI name

See https://dashboard.cypress.io/#/projects/6v6qq1/runs/4/specs and the blog post https://www.cypress.io/blog/2018/08/28/Record-Test-Artifacts-From-Any-CI/

<img width="1024" alt="screen shot 2018-09-05 at 9 19 00 am" src="https://user-images.githubusercontent.com/2212006/45095815-ff7db900-b0ec-11e8-96d4-f9db27abb78b.png">

**Comment by jennifer-shehane** [comment] 2019-10-24 19:50
@bahmutov Thinking this may already exist since this is from 2018. Not sure where to check for that though.

**Comment by jennifer-shehane** [comment] 2020-07-13 09:18
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-13 09:18 UTC
Labels: CI: Zeit, cli, process: dependencies, stage: awaiting external fix
