### ISSUE TITLE
CLI cypress test during download opens window

### ISSUE THREAD

**Issue by joszo** [cypress-io/cypress#4814] opened 2019-07-25 10:16 UTC
Hello, 

I'm struggling problem with running tests in CLI.

```js
cy.xpath(page.generatePdfButton).wait(500).eq(0).click().wait('@pdf').then((xhr) => {
  expect(xhr.status).to.eq(200);
});
```

Tests clicks download button in ```npx cypress open```, the windows is not opened, file is downloaded.

But in CLI runs cypress open that window:

<img width="343" alt="Screen Shot 2019-07-25 at 12 12 32 PM" src="https://user-images.githubusercontent.com/32454314/61866723-fb5db400-aed5-11e9-83f1-b357ac2b42c0.png">

How can I handle this?

**Comment by jennifer-shehane** [comment] 2019-07-25 10:31
We don't fully support downloading files yet. Closing as duplicate of this issue https://github.com/cypress-io/cypress/issues/949

**Closed by jennifer-shehane** 2019-07-25 10:31 UTC

**Comment by jennifer-shehane** [comment] 2021-01-20 04:36
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
