### ISSUE TITLE
Tests with a too long description leads to ENOENT error

### ISSUE THREAD

**Issue by Konstruktour** [cypress-io/cypress#2665] opened 2018-10-26 11:01 UTC
### Current behavior:

Tests with a too long description leads to an error message because cypress has problems saving screenshots (because filename of screenshot is based on the description).

```
1) describe 1 it has a looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong description:
     Error: ENOENT: no such file or directory, open 'C:\dev\cypress\reports\screenshots\playground\playground.ts\describe 1 -- it has a looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong description (failed).png'
  
```
### Desired behavior:
The filename of the screenshot should be shortened when the description is too long.
An option in the configs to turn off screenshots would also help.

### Steps to reproduce:
```
describe('describe', () => {
    it('it has a looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong description!', () => {
        expect(false).to.be.true;
    });
});

```
### Versions
Cypress 3.1.0
Windows 10
Jenkins

**Comment by jennifer-shehane** [comment] 2018-10-26 17:39
Duplicate of https://github.com/cypress-io/cypress/issues/2403

**Closed by jennifer-shehane** 2018-10-26 17:39 UTC
