### ISSUE TITLE
Cypress can't test an application running at https://127.0.0.1 in a Docker container

### ISSUE THREAD

**Issue by benjaminapetersen** [cypress-io/cypress#1371] opened 2018-02-23 19:09 UTC
- Operating System: MacOS
- Cypress Version: 2.0.3
- Browser Version: Chrome 64.0.3282.167, & whatever Electron is used by the above Cypress version.

### Is this a Feature or Bug?

Bug

### Current behavior:

Cypress is unable to load anything and simply shows the `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` error.

### Desired behavior:

Cypress would load the page at `https://127.0.0.1:8443` and run the tests.

### How to reproduce:

I'm using the `oc cluster up` command from [this guide for openshift](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac) to setup a local cluster.  This is similar to `minikube` or `minishift` or any number of the other kubernetes distros to run a local cluster in a VM on your local machine.

I'm attempting to test the [web console for OpenShift](https://github.com/openshift/origin-web-console).  The console can be run locally at `localhost:9000` for development, however I am trying to test the console that is already built into a container running on the platform, which is accessible at `https://127.0.0.1:8443/console`.  This is necessary to ensure that the console is packaged and configured properly for deployment (talks to the APIs, etc).

#### Test code:

Nothing fancy, this is just a `visit()` to kick off the test:

```js
const protocol = 'https://',
    host = '127.0.0.1',
    serverPort = 8443,
    baseUrl = protocol + host + ':' + serverPort,
    loginUrl = baseUrl + '/login',
    consoleUrl = baseUrl + '/console';
describe('and login', () => {
      it('should successfully login', () => {
        cy.visit(consoleUrl);
      });
});
```

### Additional Info (images, stack traces, etc)

Nothing to add here, we don't get far enough.

Thanks!

**Comment by brian-mann** [comment] 2018-02-25 07:22
This is actually a duplicate of: https://github.com/cypress-io/cypress/issues/771

You're running into a highly unusual situation where Cypress doesn't work on HTTPS. There is a reproducible example (in the other issue) but we haven't had time to look at it / and fix it. It's a bug in Cypress though and it will be fixed. 

The vast majority of https works fine. Closing as duplicate but will note when the underlying issue is fixed.

**Closed by brian-mann** 2018-02-25 07:22 UTC

**Comment by benjaminapetersen** [comment] 2018-02-26 14:23
Sounds good to me, thx!
