### ISSUE TITLE
Key Combinations not working for {shift} and {ctrl}

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#7105] opened 2020-04-22 07:24 UTC
## Current behavior:

We have a text copied in the clipboard, so now want to trigger `Ctrl + v` to paste the copied text. Its working manually, Unfortunately, its not working. Even tried to type UPPERCASE alphabet using `Shift + v`. thats also not working

For Windows:

- `shift + v` to add a uppercase V
- `ctrl + v` to paste the text 

And the commands I am using are respectively:

```js
cy.get("input").type('{shift}v); //capital V
cy.get("input").type('{ctrl}v'); //paste
I have tried
cy.get("input").scrollIntoView().type("{shift}",{ release: false, force: true}).type("v",{ release: true, force: true})
cy.get("input").scrollIntoView().type("{ctrl}",{ release: false, force: true}).type("v",{ release: true, force: true})
```

## Desired behavior:

Keyboard shortcut that contain a one or more modifiers should work. like `{shift} + v` to type capital V and {ctrl} + v for paste and other combinations

## Test code to reproduce

You can use the above code and reproduce. Else I will provide 

## Versions

Cypress 4.4.1
Operating system Windows 10
browser Chrome 81, Electron 80

**Comment by jennifer-shehane** [comment] 2020-04-22 09:13
Duplicate of #2386 

But also part of the larger story of implementing copy/paste in Cypress since we're unable to currently access the clipboard. #2752

**Closed by jennifer-shehane** 2020-04-22 09:13 UTC

**Comment by Prashant-Kan** [comment] 2020-04-22 09:35
I see the #2386 its for copy and paste. 
Understand that you are working on the access the clipboard.

But, {shift} + v does not require clipboard. If this gets working I am sure {ctrl} + v will also work. Because from our code we have the data to the clipboard. But, the only thing we need to implement is press {ctrl} + v. 

Trigger this combinations will put the copied text into the input. we have tested this manually.

So, if you can give the solution to trigger the combinations of keys that would be great.

thanks in advance

**Comment by darrelfrancis** [comment] 2022-04-02 23:44
@Prashant-Kan. I sympathise with your reasoning, that if we can send {shift}v, we should be able to send {ctrl}v, and it should cause a pasting to occur.
However the browser manufacturers make a specific point about this. They allow Cypress to send ordinary text into text boxes, but their browser code deliberately does not interpret {control}c and v as copy/paste.

That is why your manual testing works, but the Cypress version does not: it is specifically blocked at the browser level.

**Comment by kenankukic** [comment] 2022-04-25 11:33
Understood the issue with clipboard but why {shift} is not working? I have same issue, where shift is not firing up nor ctrl. 
Tried using these modifiers to select part of the text but unfortunately only cursor is moving without pressed shift and ctrl. 

`type('{shift}{ctrl}{leftArrow}{leftArrow}{backspace}');` 
With this i wanted to select part of the text but only cursor moved.

Also tried 
`type('{shift}hello');`
output is "hello". Am I missing something or it should be "HELLO"?
