### ISSUE TITLE
 Can't start server EEXIST: file already exists, mkdir 'C:\CP\node_modules\.bin\cypress'

### ISSUE THREAD

**Issue by padmarajnidagundi** [cypress-io/cypress#1125] opened 2017-12-23 14:22 UTC
- Operating System: win10
- Cypress Version: 1.4.0
- Browser Version:

### Is this a Feature or Bug?
When I start the cypress it show me  Can't start server EEXIST: file already exists, mkdir 'C:\CP\node_modules\.bin\cypress'

### Current behavior:
![image](https://user-images.githubusercontent.com/8341941/34320218-2bd9fac2-e7fd-11e7-82ef-4922e7ecafc8.png)

### Desired behavior:
It need to start the test environment 

### How to reproduce:
Launch the cypress on win 10 PC
User will notice the  Can't start server error

#### Test code:

```js

```

**Comment by aaronherman** [comment] 2017-12-25 16:39
Duplicate of https://github.com/cypress-io/cypress/issues/1099. I've had the same issue for a while.

**Comment by brian-mann** [comment] 2017-12-25 16:56
Closing in favor of the other issue.

**Closed by brian-mann** 2017-12-25 16:56 UTC
Labels: type: duplicate

**Comment by padmarajnidagundi** [comment] 2018-03-02 11:45
How to make run cypress.io on your win system.

![11](https://user-images.githubusercontent.com/8341941/36897573-d8d39b04-1e1f-11e8-8598-ebf7f0ce2200.jpg)

**Comment by berxtjkl** [comment] 2018-08-28 07:41
@nashoshinoda 
@nashoshinoda 
You are a genius, I deleted the cypress file and clicked Try Again button, the problem was solved, 
thanks brother~

**Comment by nashoshinoda** [comment] 2018-08-28 18:43
Awesome @berxtjkl ! I'm glad to know that I helped you!

Greetings!

**Comment by jagadish659** [comment] 2018-10-22 20:11
Super bro..Thanks a lot :+1

**Comment by just4santosh** [comment] 2018-10-30 14:13
Worked for me too. :) Thanks @nashoshinoda

**Comment by mikelumberjack** [comment] 2019-03-29 11:31
> I don't know you guys but I just deleted the cypress file generated after the first installation, hit the Try Again button and that's it hehehe.
Thanks man!

**Comment by TechnoCraftCons** [comment] 2019-04-04 16:36
@nashoshinoda Thanks Man it worked!

**Comment by Vinay4Test** [comment] 2019-04-23 09:49
@nashoshinoda Worked for me Thanks

**Comment by githubbalaji** [comment] 2019-07-15 06:03
@padmarajnidagundi  - Thank you - your solution worked like a charm :)

**Comment by peterkemenyas** [comment] 2020-02-15 16:23
well done!

**Comment by jimmytbc** [comment] 2020-03-12 05:28
Thanks, it works!

**Comment by sabbir-subhan** [comment] 2020-05-20 04:49
Great..This solution works. Kudos to  @nashoshinoda nashoshinoda

**Comment by nashoshinoda** [comment] 2020-05-20 14:57
> Great..This solution works. Kudos to @nashoshinoda nashoshinoda

Thanks for the kudos, @sabbir-subhan

**Comment by Fairouz05** [comment] 2020-06-08 15:12
> I don't know you guys but I just deleted the cypress file generated after the first installation, hit the Try Again button and that's it hehehe.

Thanks! Worked for me :)

**Comment by nashoshinoda** [comment] 2020-06-08 15:15
> > I don't know you guys but I just deleted the cypress file generated after the first installation, hit the Try Again button and that's it hehehe.
> 
> Thanks! Worked for me :)

Good to know, man!

**Comment by khushal-Gupta-94** [comment] 2020-10-08 15:21
We can also use --global as it force Cypress into global mode as if its globally installed.
So, the cmd will be "cypress open --global"
It works for me.

**Comment by ggonmar** [comment] 2021-01-17 11:50
My way of fixing it was even stuppidier: change / for \ on the call

**Comment by shivanipatwal90** [comment] 2021-05-01 18:23
deleting the cypress file from .bin folder, worked for me too :)

**Comment by AUnathilACR** [comment] 2021-06-08 06:09
> deleting the cypress file from .bin folder, worked for me too :)

It works for me too. Thanks @shivanipatwal90

**Comment by paulcastro2014** [comment] 2021-09-26 23:52
lol I spent 3 hours trying to fix this...
Thanks
