### ISSUE TITLE
Timeout error from cy.visit()

### ISSUE THREAD

**Issue by TatevArakelyan** [cypress-io/cypress#20389] opened 2022-02-28 09:41 UTC
### Current behavior

Cypress version: 9.5.0
browser: chrome 98

While running the cy.visit() in before method page doesn't load, no matter how long is timeout. This issue has never been seen manually. The error doesn't always shown up.

Error: 
Timed out after waiting 60000ms for your remote page to load. 

<img width="1179" alt="Снимок экрана 2022-02-28 в 12 34 36" src="https://user-images.githubusercontent.com/100565230/155959476-60bac2b5-67b3-464b-ae41-0add829c58b1.png">

<img width="1786" alt="Снимок экрана 2022-02-28 в 12 19 01" src="https://user-images.githubusercontent.com/100565230/155959563-248a9484-79c1-4462-8c26-0562fff57f16.png">

### Desired behavior

Load the page

### Test code to reproduce

Cypress.on('uncaught:exception', () => {
  return false;
});

before('Clearing staff', () => {
  cy.visit('https://sunlight.net/pages/test_test_1.html');
  cy.window().then((win) => {
    cy.clearCookies();
    cy.clearLocalStorage();
    win.sessionStorage.clear();
    cy.reload();
  });
});

beforeEach(() => {
  Cypress.Cookies.defaults({
    preserve() {
      return true;
    },
  });
});

### Cypress Version

9.5.0

**Comment by sainthkh** [comment] 2022-03-04 01:29
Sorry for the late reply.

Is the problem still happening with 9.5.1?

I tried to reproduce the problem with the code below, but failed to do so. 

```js
Cypress.on('uncaught:exception', () => {
  return false
})

before('Clearing staff', () => {
  cy.visit('https://sunlight.net/pages/test_test_1.html')
  cy.window().then((win) => {
    cy.clearCookies()
    cy.clearLocalStorage()
    win.sessionStorage.clear()
    cy.reload()
  })
})

beforeEach(() => {
  Cypress.Cookies.defaults({
    preserve () {
      return true
    },
  })
})

it('t', () => {

})
```

![Peek 2022-03-04 10-29](https://user-images.githubusercontent.com/8130013/156681707-d6f0e2e8-2bad-4fc0-a6ac-a3384c225d43.gif)

**Comment by TatevArakelyan** [comment] 2022-03-09 12:47
Yes, I reproduce this issue with 9.5.1 
The error doesn't always appear, but once or twice in 10 times

**Comment by Julyanajs** [comment] 2022-04-24 19:33
having the same problem on cypress 9.5.1 =(

**Comment by Kreeg** [comment] 2022-05-26 11:45
Same problem with 9.6.0 version

**Comment by nbrugger-tgm** [comment] 2023-05-24 18:01
I have had this issue, but for me, it always happens (in `cypress open`). In comparison, `cypress run --headed` does **not** produce this (wrong) behaviour.
![grafik](https://github.com/cypress-io/cypress/assets/34156963/37e56205-ea88-44a7-a7c0-82b7c6bdb287)
The error is `"Your page did not fire its load event within 60000ms."`
But it works if i use the Firefox runner or if i use `cypress run` (with chrome)

**Comment by nagash77** [comment] 2023-05-24 18:53
Hi @nbrugger-tgm , can you share a reproducible example that demonstrates the problem you are seeing?  Reading through the history on this ticket it looks as if no one has been able to reproduce this behavior reliably (or even semi consistently) internally.  If you can share that, I will pass this ticket along to an engineer for investigation.

**Comment by nbrugger-tgm** [comment] 2023-05-24 19:29
Hello, I was about to create a reproducible example, which it was - and suddenly it started working again and i am now unable to reproduce it myself. So it was 100% fail rate -> 0% fail rate. I did nothing between the change except running a test. Sorry for the letdown :/
As soon as it appears again, I will clone my production project state and reduce it to a minimal example. Sorry for that, but I am pretty sure this is frustrating for both of us.

**Comment by Kreeg** [comment] 2023-05-25 07:27
I would say that between 9.6.0 and 12.x.x version a great improvement was made. If failure rate used to be around 10%, now it's less then 0,1%.

**Comment by nagash77** [comment] 2023-05-26 16:22
@nbrugger-tgm and @Kreeg thanks for your responses!  I am glad you are at least in a better place with your tests.  I am going to close this issue for now.  If in the future you do see this problem creep back up please do comment back here and we can investigate further.

**Closed by nagash77** 2023-05-26 16:22 UTC
Labels: Needs Reproduction
