### ISSUE TITLE
Recorded video in CI is only one second long

### ISSUE THREAD

**Issue by vicusbass** [cypress-io/cypress#8140] opened 2020-07-31 08:43 UTC
Using Cypress 4.11.0, in GitlabCI, docker image `cypress/browsers:chrome67`. The recorded video is only one-second length. When running the test locally, the video has 35 seconds. 

I tried minimal compression, also no compression, the same result.

This is the command I use for running the tests `cypress run --spec cypress/integration/production.monitoring.spec.js --browser chrome --config '{"reporterOptions":{"configFile": "reporter-config-prod.json"}}' --record --key <my_key> `

**Comment by jennifer-shehane** [comment] 2020-08-03 09:36
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here? Particularly, you may want to see if you are maxing out the CPU or having some ffmpeg issues.

**Comment by vicusbass** [comment] 2020-08-03 10:40
Is this enough information (it's from the GitLab job logs)? Otherwise I will have to do a lot of cleaning in the logs, it contains sensitive information:
 ```
cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
   cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
   cypress:server:util:process_profiler │ (index) │       group       │ processCount │                      pids                       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
   cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
   cypress:server:util:process_profiler │    0    │     'Chrome'      │      8       │ '621, 626, 627, 629, 630, 667 ... 2 more items' │   20.18    │     16.81      │  695.36  │    672.59    │     754     │
   cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                      '378'                      │    0.85    │      5.67      │  299.55  │     264      │   299.55    │
   cypress:server:util:process_profiler │    2    │ 'electron-shared' │      3       │                 '382, 531, 542'                 │     0      │       0        │  129.39  │     111      │   129.39    │
   cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │                      '585'                      │     0      │       0        │  65.74   │    65.74     │    65.74    │
   cypress:server:util:process_profiler │    4    │     'ffmpeg'      │      1       │                      '620'                      │     0      │       0        │  10.25   │    10.25     │    10.25    │
   cypress:server:util:process_profiler │    5    │      'other'      │      2       │                   '801, 802'                    │     0      │       0        │   2.75   │     2.78     │    2.92     │
   cypress:server:util:process_profiler │    6    │      'TOTAL'      │      16      │                       '-'                       │   21.03    │     19.11      │ 1203.04  │    976.65    │   1261.29   │
   cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
   (Results)
   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
   │ Tests:        7                                                                                │
   │ Passing:      7                                                                                │
   │ Failing:      0                                                                                │
   │ Pending:      0                                                                                │
   │ Skipped:      0                                                                                │
   │ Screenshots:  0                                                                                │
   │ Video:        true                                                                             │
   │ Duration:     30 seconds                                                                       │
   │ Estimated:    28 seconds                                                                       │
   │ Spec Ran:     production.monitoring.spec.js                                                    │
   └────────────────────────────────────────────────────────────────────────────────────────────────┘
   cypress:server:video capture stderr log { message: "Input #0, image2pipe, from 'pipe:0':" } +35s
   cypress:server:video capture stderr log { message: '  Duration: N/A, start: 1596450748.000000, bitrate: N/A' } +0ms
   cypress:server:video capture stderr log { message: '    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1050x938 [SAR 1:1 DAR 75:67], 25 tbr, 25 tbn, 25 tbc' } +0ms
   cypress:server:video capture stderr log { message: 'Stream mapping:' } +1ms
   cypress:server:video capture codec data: { format: 'image2pipe', audio: '', video: 'mjpeg (Baseline)', duration: 'N/A', video_details: [ 'mjpeg (Baseline)', 'yuvj420p(pc', 'bt470bg/unknown/unknown)', '1050x938 [SAR 1:1 DAR 75:67]', '25 tbr', '25 tbn', '25 tbc' ] } +0ms
   cypress:server:video capture stderr log { message: '  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] using SAR=1/1' } +2ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512' } +3ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit' } +4ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] 264 - core 157 r2935 545de2f - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0' } +1ms
   cypress:server:video capture stderr log { message: "Output #0, mp4, to '/builds/screening/testing/platform-ui-automation/cypress/videos/production.monitoring.spec.js.mp4':" } +0ms
   cypress:server:video capture stderr log { message: '  Metadata:' } +0ms
   cypress:server:video capture stderr log { message: '    encoder         : Lavf58.24.100' } +0ms
   cypress:server:video capture stderr log { message: '    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuvj420p(pc), 1050x938 [SAR 1:1 DAR 75:67], q=-1--1, 25 fps, 12800 tbn, 25 tbc' } +0ms
   cypress:server:video capture stderr log { message: '    Metadata:' } +0ms
   cypress:server:video capture stderr log { message: '      encoder         : Lavc58.42.100 libx264' } +0ms
   cypress:server:video capture stderr log { message: '    Side data:' } +0ms
   cypress:server:video capture stderr log { message: '      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1' } +0ms
   cypress:server:video capture stderr log { message: 'frame=   33 fps=0.0 q=-1.0 Lsize=     108kB time=00:00:01.28 bitrate= 692.9kbits/s dup=31 drop=0 speed=14.3x    ' } +79ms
   cypress:server:video capture stderr log { message: 'video:107kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.878973%' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] frame I:1     Avg QP:20.00  size:  2950' } +1ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] frame P:32    Avg QP:12.66  size:  3324' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] mb I  I16..4: 100.0%  0.0%  0.0%' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] mb P  I16..4:  3.1%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:96.9%' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] coded y,uvDC,uvAC intra: 16.5% 0.2% 0.2% inter: 0.0% 0.0% 0.0%' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] i16 v,h,dc,p: 80%  5% 12%  3%' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] i8c dc,h,v,p: 100%  0%  0%  0%' } +0ms
   cypress:server:video capture stderr log { message: '[libx264 @ 0x6faf380] kb/s:662.44' } +0ms
   cypress:server:video capture stderr log { message: '' } +1ms
   cypress:server:video capture ended +1ms
   cypress:server:run attempting to close the browser +35s
   cypress:server:browsers killing browser process +36s
   cypress:server:browsers:chrome closing remote interface client +37s
   cypress:server:browsers:chrome closing chrome +2ms
```

**Comment by jennifer-shehane** [comment] 2020-08-18 08:21
We would need more logs than this - these are the logs after the video has been recorded and processed. You could try running `DEBUG=cypress:server:video cypress run` to narrow down the logs to just video logs and provide those here.

**Comment by randing89** [comment] 2020-11-20 22:21
I am getting the same issue with 3.x and 5.x. It just suddenly stopped working. The recordings are either 1 second long. or black screen.

Here is the log I removed most of the HTTP entries:
https://gist.github.com/randing89/e9af774be25546252a567d9b43cacaa1

**Comment by cjord01** [comment] 2020-11-24 15:51
I also see this issue. Only against Chrome when run locally. Firefox still works, and both Firefox and Chrome work when run in CI.

**Comment by ayang3** [comment] 2020-11-25 02:30
We encountered the same issue (video recordings are 1 second long) on Chrome. Taking the screenshot also timed out sometimes. We started having the issue early this week, and used the latest Google-Chrome-Stable (87). After we changed to use Chrome 86 in the docker image, the video recordings work expected.

**Comment by jennifer-shehane** [comment] 2020-11-25 03:57
Duplicate of https://github.com/cypress-io/cypress/issues/9265

**Closed by jennifer-shehane** 2020-11-25 03:57 UTC
Labels: stage: needs information
