### ISSUE TITLE
[Feature request]: Conditionally create **/example folders

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#8852] opened 2020-10-14 20:35 UTC
### Current behavior
I accidentally did `cypress open` in the wrong folder. And I am surprised by how many junks it auto generated in that folder which I have to clean up.

### Desired behavior
Can we bundle this behavior with the `cypress first time check`?
For example, if cypress detects the user is running cypress for the first time (which I believe we already do for new version integrity check), cypress and generate all the **/example folder. If we know this user already used cypress before, there is not reason to generate all those files.

### Test code to reproduce
See `Current behavior`

### Versions
No need

**Comment by jennifer-shehane** [comment] 2020-10-14 23:50
Duplicate of https://github.com/cypress-io/cypress/issues/3364

**Closed by jennifer-shehane** 2020-10-14 23:50 UTC
