### ISSUE TITLE
Cypress records incomplete useless videos after upgrade from 5.6.0 to 6.0.0

### ISSUE THREAD

**Issue by adolgoff** [cypress-io/cypress#9367] opened 2020-11-28 22:46 UTC
### Current behavior
Video is recorded for only about a second after failing test case starts running (which doesn't even reveal a test itself, only Cypress UI gets rendered).

### Desired behavior
Video of full test is recorded.

### Test code to reproduce
[https://github.com/adolgoff/cypress-e2e-testing-angular](https://github.com/adolgoff/cypress-e2e-testing-angular)

### STR: 
```
$ git clone git@github.com:adolgoff/cypress-e2e-testing-angular.git
$ cd cypress-e2e-testing-angular
$ npm i
$ npm run e2e:ci
```
Then check out the `cypress/videos/` folder

`npm i -D cypress@5.6.0` help to fix the behavior.

### Versions
Cypress package version: 6.0.0
Cypress binary version: 6.0.0
Electron version: 11.0.2
Bundled Node version: 12.18.3

OS: Ubuntu 20.04.1 LTS

**Comment by travis-w** [comment] 2020-11-28 23:37
Same thing is happening for me on macOS 10.15.6

**Comment by jennifer-shehane** [comment] 2020-11-30 02:12
Duplicate of https://github.com/cypress-io/cypress/issues/9265

**Closed by jennifer-shehane** 2020-11-30 02:12 UTC
