### ISSUE TITLE
Response is not being yielded after wait using with cy.intercept()

### ISSUE THREAD

**Issue by vrknetha** [cypress-io/cypress#9150] opened 2020-11-10 09:13 UTC
The route2 matches the query and yields only request but not response

```js
Cypress.Commands.add(`registerRoute`, function (queries: {queryName: string; type?: string}[]) {
	return cy.fixture(`variables.json`).then(({developBackEndUrl}) => {
		queries.forEach(query => {
			cy.intercept(`POST`, Cypress.env('BACKEND_URL') || developBackEndUrl, req => {
				if (query.type) {
					if (req.body.includes(query.type) && req.body.includes(query.queryName)) {
						req.alias = `${query.type}${query.queryName}`;
					}
				} else {
					if (req.body.includes(query.queryName)) {
						req.alias = query.queryName;
					}
				}
			});
		});
	});
});
```

![image](https://user-images.githubusercontent.com/20596261/98653393-fdfe4a00-2362-11eb-8f42-4235a0958608.png)

**Comment by jennifer-shehane** [comment] 2020-11-16 05:27
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you.

- What version of Cypress are you running?

**Comment by vrknetha** [comment] 2020-11-16 10:26
@jennifer-shehane  I will follow the template from now on. The version I am using is 5.6.0

**Comment by vrknetha** [comment] 2020-11-24 07:24
If you check the screenshots, For the XHR requests, I could see the response object but not for the alias using cy.intercept(). I have updated to 6.0.0 still the issue is not resolved

![image](https://user-images.githubusercontent.com/20596261/100061438-16d32900-2e54-11eb-9f59-7805e5090ea7.png)

![image](https://user-images.githubusercontent.com/20596261/100061462-1dfa3700-2e54-11eb-835a-542f9caa1438.png)

**Comment by desaiuditd** [comment] 2020-11-26 11:08
I'm also experiencing this with `cy.intercept` on 6.0.0.

**Comment by jennifer-shehane** [comment] 2020-12-29 09:15
I can't be totally sure without a fully reproducible example given, but I believe this is likely a duplicate of https://github.com/cypress-io/cypress/issues/14205

If someone can post a reproducible example that is different from that issue, I'll be happy to reopen.

**Closed by jennifer-shehane** 2020-12-29 09:15 UTC
Labels: internal-priority, pkg/net-stubbing, stage: needs investigating
