### ISSUE TITLE
Screenshot missing after the execution in test result

### ISSUE THREAD

**Issue by senthkum** [cypress-io/cypress#23974] opened 2022-09-26 02:36 UTC
### Current behavior

I am currently running 20+ scripts and for a couple of failed scripts, the screenshots are missing after the execution.
please find the ss below.

![IMG_7386](https://user-images.githubusercontent.com/46837197/192182482-b114b290-5c54-4b19-8cab-b183c2918a51.jpg)
![IMG_7387](https://user-images.githubusercontent.com/46837197/192182484-e0dcccb3-ded7-46da-852a-74af23644d79.jpg)
a

### Desired behavior

I am assuming that cypress will take SS for both GUI and API failed test cases, but in some scenarios, Cypress fails to load the SS.cases

### Test code to reproduce

Code can not be shared

### Cypress Version

10.7.0

### Node version

16.14.0

### Operating System

macOS 12.6

**Comment by idanElitzur** [comment] 2022-09-26 21:23
Look in the network response it returns 404 not found error and check out the screenshots path configuration.
also you can see the exact problem over there by using `DEBUG=cypress:*`

**Comment by senthkum** [comment] 2022-09-26 23:24
Hi idan, I am intercepting the 401 error code, also I am excepting an error page. But it does not display the error page but loads the welcome page. Due to this, the assertion (script) has failed, it has also captured the screenshot. I have attached them above, I had executed them twice and both the SS are in the respective folder. My ask here is why is it not loaded in the report. This happens in many of the scripts, for a few of the failed scripts I do see the SS in the report.

**Comment by mjhenkes** [comment] 2022-09-27 16:17
@senthkum, Since there are many ways to setup and configure cypress, could you provide a sample project re-creating the error? Since the issue is around screenshots not appearing in the report this is most likely a setup issue, or an issue around bad path assumptions when generating the report.

I usually start with the https://github.com/cypress-io/cypress-test-tiny project.

**Comment by mjhenkes** [comment] 2022-10-05 16:36
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by mjhenkes** 2022-10-05 16:36 UTC
