### ISSUE TITLE
GET request to API with % as part of query, URI malformed error is thrown

### ISSUE THREAD

**Issue by eugeneoei** [cypress-io/cypress#8356] opened 2020-08-20 04:23 UTC
### Current behavior:

When a `GET` request is made to API with `%` as part of query, `URI malformed` error is thrown. For eg, `GET` request to `/api/query?tag=10%`

Works on Chrome browser:
![](https://raw.githubusercontent.com/eugeneoei/cypress-issue/master/screenshots/success.png)

But not when Cypress test is run:
![](https://raw.githubusercontent.com/eugeneoei/cypress-issue/master/screenshots/error.png)

### Desired behavior:

API call with `%` should be decoded correctly and should behave as on Chrome.

I am not entirely sure if issues [2372](https://github.com/cypress-io/cypress/issues/2372) and [5274](https://github.com/cypress-io/cypress/issues/5274) are relevant to this.

### Test code to reproduce

I have created a repository [here](https://github.com/eugeneoei/cypress-issue) for the steps to be reproduced. `express` app to serve static `html` file and handle API request

### Versions

Cypress: ^5.0.0
Chrome: Version 84.0.4147.125 (Official Build) (64-bit)
OS: macOS Mojave Version 10.14.2

**Comment by jennifer-shehane** [comment] 2020-08-20 06:02
@eugeneoei Thanks for providing a reproducible example!

Cypress is calling JavaScript's [`decodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) on the url `http://localhost:8080/api/query?tag=10%`. This throws an error about the URI being malformed, which is what is surfacing here. 

Calling it here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/server.js#L488:L488

We should probably be catching this error and having some sort of fallback here instead of failing to handle the request at all.

### Repro

```js
it('test cy.route()', () => {
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/api/query?tag=10%')
    xhr.send()
  })
})
```

<img width="458" alt="Screen Shot 2020-08-20 at 12 31 23 PM" src="https://user-images.githubusercontent.com/1271364/90722569-153c1700-e2e1-11ea-90a4-1478b57d469a.png">

**Comment by eugeneoei** [comment] 2020-08-20 06:46
@jennifer-shehane thanks for getting back so quickly! For now, I'll skip the test cases that makes API calls with `%` as part of the query.

**Comment by harshitdxt3004** [comment] 2020-08-20 14:33
Hey @jennifer-shehane, I would like to work on this.
Can you guide me on this?

**Comment by jennifer-shehane** [comment] 2020-08-21 06:40
@harshitdxt3004 Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by nirajgeorgian** [comment] 2020-08-26 20:35
@harshitdxt3004 if you are not working on this I can take up this as my first contribution to this.

**Comment by harshitdxt3004** [comment] 2020-08-26 20:36
@nirajgeorgian please go ahead.

**Comment by nirajgeorgian** [comment] 2020-08-26 20:37
@harshitdxt3004 any feedback or any progress till now ?

**Comment by nimish-gupta** [comment] 2020-09-02 17:15
> We should probably be catching this error and having some sort of fallback here instead of failing to handle the request at all.

Should we just pass a flag around to skip `%` or just use regex for replacing `%` with `%25` (unicode for `%`) ? @jennifer-shehane

**Comment by pstephenwille** [comment] 2020-09-09 16:12
Why not allow the encoded URI?  
Chrome Network tab shows the encoded URI which is what our server requires.  In my test, I want to confirm the URI is properly encoded.  Re-encoding the test string does not confirm my code is handling the URL query params correctly.

**Comment by sinharaksh1t** [comment] 2020-09-17 09:18
@eugeneoei since we know that Cypress is calling JavaScript's `decodeURIComponent` on the URL, have you tried encoding the query parameters in the URL before making the call? Not sure if this will help, but in the codebase of where I work, we use JavaScript's `encodeURIComponent` before making the API calls.

Below is an example from your own [example repo](https://github.com/eugeneoei/cypress-issue/blob/master/index.html#L17) to demonstrate what I mean:

```javascript
axios.get(`/api/query?tag=${encodeURIComponent(10%)}`)
					.then(function (response) {
						...do something
					})
					.catch(function (error) {
						...do something else after catch
					})
```

**Comment by eugeneoei** [comment] 2020-09-18 02:31
@sinharaksh1t i made the changes according to your suggestion and ran the test case again. you are right!! `URI malformed` error is no longer thrown after encoding the query params.

And now it made me realised I actually should be using `encodeURIComponent` in all the API calls involving query params on the URL made from the front-end application I'm working on. Currently, the API I did "decodes" by running a regex which will no longer be needed if `encodeURIComponent` is used on the front-end application. Thanks for the tip!

I guess this is technically not a bug and can be closed? what do you think @jennifer-shehane ?

**Comment by bahmutov** [comment] 2020-09-18 02:49
You can close it, thank you for seeing it through

**Closed** 2020-09-18 02:51 UTC
Labels: first-timers-only, pkg/server, stage: ready for work, type: bug
