### ISSUE TITLE
Cypress example tests currently fail in Firefox when running cypress run --browser firefox 

### ISSUE THREAD

**Issue by dschuessler** [cypress-io/cypress#7902] opened 2020-07-07 08:28 UTC
### Current behavior:

The example tests currently fail in Firefox 78 when using `cypress run --browser firefox`. My results: https://gist.github.com/dschuessler/c34b41fda1c42c63ea09b13af3d71088

They run fine with `cypress open` though.

### Desired behavior:

The example tests succeed.

### Test code to reproduce

```
npm init
npm install cypress --save-dev
npx cypress run --browser firefox
```

### Versions

Cypress 4.9.0
macOS 14.0.6
Firefox 78.0.1

**Comment by jennifer-shehane** [comment] 2020-07-07 08:53
Duplicate of #6813

**Closed by jennifer-shehane** 2020-07-07 08:53 UTC
