### ISSUE TITLE
cypress hanging with longer test runs

### ISSUE THREAD

**Issue by cameronc56** [cypress-io/cypress#1479] opened 2018-03-19 23:09 UTC
### Current behavior:
my suite runs about 1200 cypress tests for about 2 hours. Most of the time it hangs indefinitely at some point. Then I am seeing the logs below, where it seems to get stuck in some infinite loop. 

#### Logs:

logs with "DEBUG=cypress:*" set:
https://gist.github.com/cameronc56/b94c64533526751c0950a9d66c8f73c0

- Operating System:
Docker, Using cypress/base:8. Options: -v /dev/shm:/dev/shm --ipc=host
- Cypress Version:
2.1
- Browser Version:
chrome 64 + xvfb

**Comment by jennifer-shehane** [comment] 2018-03-20 16:07
Is the indefinite hanging point in the same spot each time? Could you share the sequence of tests you're running for each visit/request in these 1200 tests?

**Comment by cameronc56** [comment] 2018-03-20 17:01
It is not the same spot each time. 

This is whats happening 1200+ times:
```
cases.forEach(testCase => {
        it('visits ' + testCase.href + testCase.path + ' and verifies matched inputs', () => {
            cy.visit(testCase.href + testCase.path);
            testCase.assert_rules.forEach(rule => {
                cy.get("[data-swch-rule*='" + rule + "']", {timeout: 5000});
            });
            testCase.assert_fieldTypes.forEach(fieldType => {
                cy.get("[data-swch-fieldtype*='" + fieldType + "']", {timeout: 5000});
            });
        });
    });
```

where the testCase.href+testCase.path leads to a static site hosted in s3 with various inputs and elements. No css, no javascript. Though some images are there. 

My numtestskeptinmemory is set to 5, viewport is set to 1920x1080,

**Comment by cameronc56** [comment] 2018-03-20 19:38
Heres the logs from another repro. You can see that the hanging started on a different test case than before. The first log i posted it started on some greenmountain snapshot, this time it was bhpphoto. 
https://gist.github.com/cameronc56/1d743481349a688a390489c25f09c9cf

**Comment by jennifer-shehane** [comment] 2018-03-20 20:52
So, in an attempt to narrow down the variables, I ran 2,000 tests executing a `cy.visit()` with multiple `cy.get()` commands in each test. These ran fine and finished locally in `cypress run`. 

<img width="261" alt="screen shot 2018-03-20 at 4 44 43 pm" src="https://user-images.githubusercontent.com/1271364/37681899-5f65508a-2c5e-11e8-9895-c291fa5793a8.png">

I did actually run into the `cypress:server:timers` locking up after the tests finished (looks like may be during video processing) - **this seems unrelated to your issue**, but do you have `videoRecording` set to `false`? You may want to try it off.

<img width="497" alt="screen shot 2018-03-20 at 4 49 00 pm" src="https://user-images.githubusercontent.com/1271364/37681994-a200145c-2c5e-11e8-90a0-57f5c2ec4a02.png">


Is there any way to expand on my simplified example to get them failing? We need a reproducible example to get to the root of the issue.

```js
const cases = [...Array(1200)]
const assert_rules = [...Array(10)]
const assert_fieldTypes = [...Array(10)]

cases.forEach(i => {
it('visits and verifies matched els', () => {
    cy.visit('https://example.cypress.io//commands/querying')
    assert_rules.forEach(j => {
      cy.get('.query-btn', { timeout: 5000 })
    });
    assert_fieldTypes.forEach(k => {
      cy.get('.query-list', { timeout: 5000 })
    })
  })
})
```

**Comment by cameronc56** [comment] 2018-03-20 21:24
Trying a run with videoRecording set to false now

**Comment by cameronc56** [comment] 2018-03-20 23:24
Was still able to repro

**Comment by cameronc56** [comment] 2018-03-22 19:38
So i tried running your example in my docker environment, and it looks(?) like I was able to repro it. 

https://gist.github.com/cameronc56/1a74f17fe65479b4b00a225b22bafec8

**Comment by cameronc56** [comment] 2018-03-23 23:02
Ok, I am able to get a repro without my extension. I have made the snapshot I repro'd it on public so you can access it. Repro was on test 283 out of 1000. Second repro hung on test 567/1000. Yes I am aware the tests will all fail, this is expected since the extension is not there. 

I have the cy.reload(true) in there to force reload, to simulate that I am navigating to a bunch of different snapshots in my real tests. 

Here is the code I used: 

```
let cases = []
for (let i = 1; i <= 1000; i++) {
    cases.push(i);
}
const assert_rules = ["login"]
const assert_fieldTypes = ["accounts.password", "accounts.username", "submit"]
cases.forEach(i => {
    it('visits and verifies matched element: ' + i, () => {
        cy.visit('https://s3-us-west-2.amazonaws.com/public-test-swch/myaccount_greenmountain_com-1514499557386.html');
        cy.reload(true);
        assert_rules.forEach(rule => {
            cy.get("[data-swch-rule*='" + rule + "']", {timeout: 5000});
        });
        assert_fieldTypes.forEach(fieldType => {
            cy.get("[data-swch-fieldtype*='" + fieldType + "']", {timeout: 5000});
        });
    });
});
```

Plugins file:
Default i.e: 
```
module.exports = (on, config) => {

  // bind to the event we care about
  on('<event>', (arg1, arg2) => {
    // plugin stuff here
  })
}
```

Dockerfile:

```
FROM cypress/base:8
RUN apt-get update && \
  apt-get install -y \
    apt-transport-https
RUN \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y dbus-x11 google-chrome-stable && \
  rm -rf /var/lib/apt/lists/*
# "fake" dbus address to prevent errors
# https://github.com/SeleniumHQ/docker-selenium/issues/87
ENV DBUS_SESSION_BUS_ADDRESS=/dev/null
# allow installing when the main user is root
ENV npm_config_unsafe_perm true
WORKDIR /code
ADD . /code
RUN npm install --quiet
RUN npm install gulp -g --quiet
ENV PATH="${PATH}:/code/node_modules/.bin"
CMD /bin/bash
```

Then I ran it by doing: 
`docker run -it -e "DEBUG=cypress:*"  -v /dev/shm:/dev/shm --ipc=host --security-opt seccomp:unconfined   --rm switch/my-image:latest /bin/bash`

`./node_modules/.bin/cypress run --browser chrome --reporter mocha-multi-reporters --reporter-options configFile=config_for_reporters.json --env configFile=" + environment + ",cases_file=../cypress/fixtures/" + file`
Though you can just remove the --reporter, --reporter-options, and --env

**Comment by cameronc56** [comment] 2018-03-23 23:27
I'll try and throw these files in a public repro

**Comment by cameronc56** [comment] 2018-03-26 19:54
https://github.com/cameronc56/cypress-hanging-repro/tree/master

**Comment by cameronc56** [comment] 2018-03-27 21:35
I've removed a bunch of files/code from that repository and still am able to repro it, narrowing the search down a little more

**Comment by brian-mann** [comment] 2018-03-27 21:48
This is good - keep going.

Does it hang outside of Docker? Does it hang in electron too and not just chrome?

**Comment by cameronc56** [comment] 2018-03-28 04:13
So I ran it outside of docker, using chrome, and it hanged. This is a screenshot of what chrome looked like when it was hanging:

![screenshot from 2018-03-27 21-11-32](https://user-images.githubusercontent.com/5643864/38008432-80120f26-3203-11e8-8e1b-54a20c6691e9.png)

**Comment by cameronc56** [comment] 2018-03-28 18:34
Could't repro with electron, gonna try a couple more times just to be sure. 

that narrows it down to just three parameters then: The spec file, the site snapshot, and chrome.

**Comment by shcallaway** [comment] 2018-03-29 01:29
We are seeing this behavior in Docker w/ the default browser — which is Electron for `cypress run`, correct? I have never been able to repro in "headed mode".

**Comment by cameronc56** [comment] 2018-03-29 17:17
I tried a few more times and wasn't able to reproduce it with electron.

**Comment by cameronc56** [comment] 2018-03-30 17:04
I have re-snapshotted my tests and removed all script tags (some were lingering) and haven't been able to repro the hanging issue. 

So i'm pretty sure its CSS or Javascript on that snapshot site (https://s3-us-west-2.amazonaws.com/public-test-swch/myaccount_greenmountain_com-1514499557386.html) that is causing it to hang when using chrome.

**Comment by astraljames** [comment] 2019-04-04 16:12
I am still running into this issue in 2019, never the same test, always during long runs.

**Comment by jennifer-shehane** [comment] 2019-04-24 06:57
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Closed** 2019-05-30 08:53 UTC
Labels: pkg/server, stage: needs information, type: performance 🏃‍♀️
