### ISSUE TITLE
For the same spec, Screenshots are generated in different folders when run all specs or run specific spec using command --spec 

### ISSUE THREAD

**Issue by 787681277** [cypress-io/cypress#24176] opened 2022-10-08 06:40 UTC
### Current behavior

If do Angular component testing:
For the same spec, Screenshots are generated in different folders with below 2 commands 
npx cypress run --component --browser chromium
npx cypress run --component --browser chromium --spec

This issue does not occur if do React component testing

### Desired behavior

If do Angular component testing:
For the same spec, Screenshots should be generated in **SAME** folders with below 2 commands 
npx cypress run --component --browser chromium
npx cypress run --component --browser chromium --spec

### Test code to reproduce

Angular component testing
npx cypress run --component --browser chromium
npx cypress run --component --browser chromium --spec "XX"

### Cypress Version

10.9

### Node version

v12.20.0

### Operating System

12.6

**Comment by ll-vvolodko** [comment] 2022-10-31 14:33
We experience same issue with Cypress 10.7. and Node 16.17

When running tests using --spec parameter the screenshots are being generated like this -> `screenshots-folder/spec-file-name/screenshot-name`

When running tests without --spec parameter then the folder structure reflects the folder structure for tests themself -> `screenshots-folder/sub-folder-1/sub-folder-2/spec-file-name/screenshot-name`

**Comment by tassin-gauthier** [comment] 2023-05-31 08:58
I would like to reopen this issue which is very problematic for include screenshots to a mochawesome report.

Btw, the problem is not due to Angular / React as the author suggests but it depends on the spec folder hierarchy, and how much spec you are testing with npm run.

- npm run cypress
- npm run cypress --spec folder1/*
- npm run cypress -- spec folder1/folder1-1/*
will lead to 3 differents path for the same screenshots

**Comment by emilyrohrbough** [comment] 2023-05-31 13:39
This is a duplicate of https://github.com/cypress-io/cypress/issues/24052#issuecomment-1470766686. It was an intentional v10.0.0 change, however, we recognizing this behavior is unexpected.

I am closing as a duplicate in favor of #24052.

**Closed as not planned by emilyrohrbough** 2023-05-31 13:39 UTC
Labels: CT
