### ISSUE TITLE
Add minimum width to the Command Log

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6897] opened 2020-04-01 02:57 UTC
Cypress v4.3.0

You can drag the command log right side all the way to the windows left edge, and then it is tricky to grab it again to make it visible.

![border](https://user-images.githubusercontent.com/2212006/78094623-fc1ee200-73a2-11ea-9ea3-511ab20d9012.gif)

**Comment by jennifer-shehane** [comment] 2020-04-01 05:04
Duplicate of #2132

**Closed by jennifer-shehane** 2020-04-01 05:04 UTC
