### ISSUE TITLE
Cypress.Cookies.debug(true); doesn't print out cookie get/set logs

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#9099] opened 2020-11-04 22:23 UTC
### Current behavior

With Cypress.Cookies.debug(true), I use `cy.setCookie` and `cy.getCookie` in test method, but not seeing any output in the browser's console

### Test code to reproduce

```js
 describe.only('testing', function() {
    Cypress.Cookies.debug(true);
    it('request', function() {
       cy.getCookie('auth');
    }
```

**Comment by jennifer-shehane** [comment] 2020-11-05 11:09
Per the docs: 

>By turning on debugging, Cypress will automatically generate logs to the console when it sets or clears cookie values. 

So it will not log when getting any cookies via `cy.getCookie()`. It should log if calling `cy.setCookie()` or `cy.clearCookie()`. 

Can you provide a reproducible example of the command not logging when using either `cy.setCookie()` or `cy.clearCookie()`?

<img width="808" alt="Screen Shot 2020-11-05 at 5 39 06 PM" src="https://user-images.githubusercontent.com/1271364/98233708-d2a7e380-1f8d-11eb-97ce-aa7bb808a301.png">

**Comment by quad5** [comment] 2020-11-05 19:41
Please specify what other information you need besides codes. This is the simplest I can do.

> describe('debug', function() {
    Cypress.Cookies.debug(true);
    it('debug', function() {
        cy.setCookie("testingSet", "setThis");
    })
})


<img width="1680" alt="Untitled4" src="https://user-images.githubusercontent.com/2043287/98288385-9f4c6100-1f5b-11eb-8f3d-52e038ae0bf7.png">

**Comment by jennifer-shehane** [comment] 2021-02-27 14:15
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-27 14:15 UTC
Labels: stage: needs information

**Comment by fishgills** [comment] 2021-03-02 21:54
I've been having the same problem. For the life of me, I can not get `Cypress.Cookies.debug(true);` to do anything.

I tried running the same example @quad5 has and it doesn't work for me either.

Is there an example that shows it working?

**Comment by jennifer-shehane** [comment] 2021-03-02 21:57
@fishgills You may be experiencing this issue which was recently introduced in 6.3.0. https://github.com/cypress-io/cypress/issues/15032

But this original issue was opened before that, so I'm not sure what the original issue was.
