### ISSUE TITLE
Cypress 10 attempting version check behind company firewall and crashes.

### ISSUE THREAD

**Issue by kc2112** [cypress-io/cypress#22348] opened 2022-06-15 22:22 UTC
### Current behavior

 Cypress 10 does a version check when it starts a testing mode. My company is behind a firewall and will not allow the call to be completed. As a result Cy 10 crashes. How can we disable that check so we can still use the library?? Line 125 is failing due to invalid json response body when trying to parse https://download.cypress.io/desktop.json (which we cannot download)...

I was able to bypass the check by adding a return statement on line 121 of the following file:
```bash
C:\Users\XXXXX\AppData\Local\Cypress\Cache\10.0.0\Cypress\resources\app\packages\data-context\src\sources\VersionDataSource.js
return pkg.version; //on line 121
```

Can we get this check made optional, or at least configured to where it doesn't fail when the check cannot be made?? Or possibly validate the response object before operations are attempted on it. Something to fix, please!!

### Debug logs
```bash
invalid json response body at https://download.cypress.io/desktop.jsod token < in JSON at position 0
FetchError: invalid json response body at https://download.cypress.ion: Unexpected token < in JSON at position 0
    at C:\Users\PLQ6915\AppData\Local\Cypress\Cache\10.0.0\Cypress\redules\node-fetch\lib\index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:9
    at VersionsDataSource.getLatestVersion (C:\Users\PLQ6915\AppData\\10.0.0\Cypress\resources\app\packages\data-context\src\sources\Versi5:26)
```

### Cypress Version

10.0.0

### Package Manager

npm

### Operating system

Windows

**Comment by AtofStryker** [comment] 2022-06-17 19:59
Hey @kc2112. Thank you for opening an issue. Version handling, if unreachable, is supposed to be handled gracefully, which we try to account for in this [test](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/test/unit/sources/VersionsDataSource.spec.ts#L126). It almost looks like the request on your end is succeeding, but is returning malformed. Would you be able to share some more details about the request/response of `https://download.cypress.io/desktop.json`, such as the returned body and what the status code / other pertinent response information?

**Comment by mjhenkes** [comment] 2022-06-21 19:30
@kc2112, could you try this with a later version of cypress?

**Comment by emilyrohrbough** [comment] 2022-06-23 04:21
@kc2112 This appears to be a duplicate of #22081 which has been addressed in Cypress `v10.0.3` which was released on 6/3/2022. Please use a later Cypress version.

**Closed by emilyrohrbough** 2022-06-23 04:21 UTC
Labels: stage: awaiting response, topic: installation

**Comment by kc2112** [comment] 2022-06-24 22:44
It's not a straight forward thing.  Our company does not trust anything we have not verified, so to just 'try' a later version takes a lot more time than me doing it on my own.  I submitted a download request through my company and we will get it.  I'm trying to increase adoption of Cypress, but little things like this will make it take a lot longer.

"Patriotism is supporting your country all of the time, and your government when it deserves it." - Mark Twain
________________________________

**Comment by kc2112** [comment] 2022-06-24 22:45
I do appreciate the fast response to this item.....

"Patriotism is supporting your country all of the time, and your government when it deserves it." - Mark Twain
________________________________
