### ISSUE TITLE
Headers change from original case to all lowercase during cy.request()

### ISSUE THREAD

**Issue by Robpizza** [cypress-io/cypress#2879] opened 2018-12-03 16:01 UTC
### Current behavior:
I use the "Authorization" header to authenticate a request but when I post a html form in cypress it changes all the HTTP headers to lowercase, so "Authorization" becomes "authorization" which is refused at backend.

so this is my browser
![Image of browser](https://i.imgur.com/ROHXbFT.png)
this is cypress
![Image of cypress](https://i.imgur.com/X4HLNhA.png)
### Desired behavior:
I'd like the request headers to keep their capital letter because it causes issues😋 

### Steps to reproduce:
Make a small php file with a html form, and when submit ```print_r(getallheaders());```

### Versions
Cypress V3.1.2
NodeJS v8.11.4
Npm v6.4.1

I use Chrome v70.0.3538.110 on MacOS Mojave v10.14.1

**Comment by Robpizza** [comment] 2018-12-03 17:15
I tried it in NodeJS + Express and the headers are all converted to lowercase but when I request rawHeaders they are normal.

**Comment by Robpizza** [comment] 2018-12-04 10:44
Does Cypress use HTTP in NodeJS to send requests? 
if so that could cause this problem, according to this [Github issue](https://github.com/nodejs/node-v0.x-archive/issues/1954).

**Comment by Robpizza** [comment] 2018-12-11 14:11
bump

**Comment by Robpizza** [comment] 2018-12-12 15:38
We changed our back-end 👍

**Comment by jennifer-shehane** [comment] 2018-12-13 08:01
Hey @Robpizza, the HTTP spec does define header fields as case insensitive - so servers should be case insensitive as well. 

> Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

But, I understand that not all servers may choose to behave in this way. I don't think it would be unreasonable to pass along the Header fields with the casings as they were originally requested, but as you said, I'm not sure how this is implemented.

**Comment by nhhockeyplayer** [comment] 2019-01-30 08:51
koa 2 is flattening case on all headers

and I do not know what to code now

so whats the safe option... expect our serves to break anytime

have they made up their mind yet?

which case should we be operating?

**Comment by jennifer-shehane** [comment] 2019-01-30 08:53
Cypress currently transforms all headers to be lowercase when testing using `cy.request()`, so if you are willing to update your server, ensure it does not care about casing of headers.

**Comment by nhhockeyplayer** [comment] 2019-01-30 08:54
Ok since Im a programmer I will have to code logic because someone enjoying being lead of something is spending too much time enjoying being lead of something
const authHeader = ctx.req.headers['Authorization']
if ( typeof authHeader === 'undefined' ) 
authHeader = ctx.req.headers['authorization']
if ( typeof authHeader === 'undefined' )

**Comment by nhhockeyplayer** [comment] 2019-01-30 08:54
wow your up late jen babe whats doin?

**Comment by nhhockeyplayer** [comment] 2019-01-30 08:58
Well Im using koa2, no cypress here

and its turning into a case sensitive coding mess wrecking my code

I think its an http thing... im on http2 SSL

**Comment by nhhockeyplayer** [comment] 2019-01-30 08:59
I dont even know what cypress is... the npm module docs dont say

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:01
My apologies, its part of the project I inherited.
Are there docs for cypress as to why we want cypress with typescript?

Thank you

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:02
Why would I want to integrate cypress with all my typescript

**Comment by jennifer-shehane** [comment] 2019-01-30 09:02
Hey @nhhockeyplayer, please see our main documentation here: https://docs.cypress.io

Cypress is a front end testing tool built for the modern web. We address the key pain points developers and QA engineers face when testing modern applications.

TypeScript doc: https://on.cypress.io/typescript-support

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:05
well since its a test tool, I hadn't expected it to alter the landscape to make cypress happy

it should be leaving the headers alone

i will check my project to see if its turned on or something

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:06
Im just debuggin my back end... koa2

and all my server headers case flattened

so is this done for the sake of cypress?
its
unexpected

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:07
How can I shut cypress off... I will dig thru docs

if you know how I can shut this off that would be kind

thanks

**Comment by jennifer-shehane** [comment] 2019-01-30 09:11
@nhhockeyplayer I'm sorry, I don't understand completely. What is happening that you want to stop happening? Where are you seeing behavior from Cypress exactly?

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:14
```
            .use(async (ctx, next) => {                  // Jwt Token Handling
                try {
                    const authHeaderUpper = ctx.req.headers['Authorization']
                    const authHeaderLower = ctx.req.headers['authorization']
                    // const authHeader = ctx.get('authorization')
                    if ( typeof authHeaderUpper === 'undefined' && ) {                // check if bearer is not undefined (exists)
                        ctx.throw(HttpStatus.FORBIDDEN, 'Your Access is forbidden')
                    } else {    // split header string into an array
                        const headerContentArray = (ctx.req.headers.authorization as string).split(' ')// extract
                        const access_token = headerContentArray[1]
                        ctx.body.jwt = <IJWTToken> { access_token: access_token }   // token
                    }
                    await next()
                } catch (err) {
                }
            })
```

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:16
thats my middleware in my koa

server.ts

I can put middlewares everywhere

by app.use() like express

and Im being taken out here to try and resolve a case EXPECTATION issue because something altered the landscape

all the headers on the http request are flattened to lower case

i followed the issues people are having with this and it led me to this thread

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:17
cypress is part of the package.json for my angular app

but my code for this problem is separate in my server sub folder

so im confused if thsi is http standard

or if koa is doing it

of cypress

or even what the standard calls for and why its currently an issue for developers

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:20
"cypress": "3.1.4",

        "prettier": "prettier {src,e2e,cypress}/**/*.{ts,json,md,scss} --write",
        "prettier:ci": "prettier {src,e2e,cypress}/**/*.{ts,json,md,scss} --list-different",

        "cy:open": "cypress open",
        "cy:run": "cypress run",

        "@bahmutov/add-typescript-to-cypress": "^2.0.0",

these are part of my package.json

i apologize for not having checked all this prior

im unsure if this is even a cypress issue

it seems the originator of the project I inherited wants granular detail deep within his code which I find dangerous altering code written after tis written

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:22
ok so according to http speceverythign should be lowercase

I will go with that

thank you Jen

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:24
you must be coding 7x24

like me :1st_place_medal:

**Comment by nhhockeyplayer** [comment] 2019-01-30 09:25
track me down if you want to go corporate with typescript
Im a free agent now

**Comment by jeffj6123** [comment] 2020-09-18 19:13
Hello,

I am also experiencing this issue but with cy.route where the response headers are being transformed to lowercase and modifying them. The following is the same semantics they use; casing and hyphens. This format is odd but I do not have control over changing the server that provides the response. Would there be any work around here?

```
        headers: {
            'TEST-HeaderName': 'some value',
        }
```
is changed to

```
"test-header-name" 
```

**Comment by renanpupin** [comment] 2021-08-04 17:18
I can confirm it's happening with the Authorization header.

**Comment by ReactQQ** [comment] 2021-12-23 11:41
Any chances to make this headers converting a setting in cypress options?

**Comment by mjhenkes** [comment] 2022-01-14 20:34
The http spec specifies that headers should be case insensitive, as such we're closing this issue.

>Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

**Closed by mjhenkes** 2022-01-14 20:34 UTC
Labels: type: unexpected behavior, stage: ready for work
