### ISSUE TITLE
Add ability to initialize cypress directory programmatically

### ISSUE THREAD

**Issue by drewbrend** [cypress-io/cypress#2668] opened 2018-10-26 21:37 UTC
### Current behavior:

To populate the `/cypress/` directory you must open cypress GUI after it is installed

### Desired behavior:

Be able to run a command from the CLI to populate the `/cypress/` directory, something like `cypress init`.

Reasoning for this:

My company has an internal npm package we have created that contains additional commands, plugins, fixtures, etc for our application.  `npm install` finishes with a postinstall  script will "plug" this into files in the `/cypress/` directory.  Example:  adding an import statement to the `support/index.js` file, and adding a call to our shared package's `plugins/index.js` file from the application's `plugins/index.js` file.

In a new project, the setup workflow for us is:

1) `npm install --save-dev cypress`
2) `./node_module/.bin/cypress open` <= solely to populate the `/cypress/` directory
3) `npm install --save-dev @ourcompany/shared-cypress`

If the user has not opened cypress and does not have the `/cypress/` directory, we spew out a bunch of errors and tell them they need to open cypress and reinstall our package

If cypress has a command like `cypress init`, we could run that in a preinstall script and not have to worry about this case.

### Versions

Cypress 3.1.0

**Comment by jennifer-shehane** [comment] 2018-10-31 16:03
Duplicate of https://github.com/cypress-io/cypress/issues/619 Thanks for detailing your use case!

**Closed by jennifer-shehane** 2018-10-31 16:04 UTC

**Comment by allnulled** [comment] 2018-11-05 05:47
Or maybe it is possible to inject a new parameter that can be used as general path for the other paths, or something, idk. For now, we can modify all the routes at cypress.json, and get the same effect.
