### ISSUE TITLE
Mismatched Chai version

### ISSUE THREAD

**Issue by songty** [cypress-io/cypress#3080] opened 2019-01-07 23:19 UTC
### Current behavior:
The `chai` version in launched browser does not match the example given in Cypress [docs](https://docs.cypress.io/guides/references/assertions.html#Chai).
I tried using `.nested` and it is throwing `undefined` type error.

![image](https://user-images.githubusercontent.com/6962322/50795243-6de0ac80-1282-11e9-8588-38a52b7e17bf.png)

A version bump should fix this issue
### Desired behavior:

Update `chai` version to the latest to match current docs

### Steps to reproduce: (app code and test code)
Run `expect({a: {b: ['x', 'y']}}).to.have.nested.property('a.b[1]')` in a browser test
### Versions
`3.1.4`

**Comment by jennifer-shehane** [comment] 2019-01-08 06:18
Duplicate of https://github.com/cypress-io/cypress/issues/2529 - will be released in 4.0 of Cypress

**Closed by jennifer-shehane** 2019-01-08 06:18 UTC

**Comment by jennifer-shehane** [comment] 2020-01-29 09:18
I've confirmed that this works in upcoming 4.0 release. The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

<img width="453" alt="Screen Shot 2020-01-29 at 3 47 50 PM" src="https://user-images.githubusercontent.com/1271364/73343302-c11f0600-42ae-11ea-9160-73ecf6c80fae.png">
