### ISSUE TITLE
Cannot find NODE_DEBUG variable in component testing

### ISSUE THREAD

**Issue by Arian94** [cypress-io/cypress#25204] opened 2022-12-18 06:07 UTC
### Current behavior

run component testing and got  this error:
```Cannot read properties of undefined (reading 'REACT_APP_SC_ATTR')```

seached internet, found a fix in ```vite.config.ts```:
```js
import replace from '@rollup/plugin-replace';

export default defineConfig({
  plugins: [
    react(),
    eslint(),
    replace({
      values: {
        'process.env': '(process.env || {})',           //!HERE
      },
    })
  ],
...
});
```

Reruning component testing, I got this error:
```
1) An uncaught error was detected outside of a test

  0 passing (678ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read properties of undefined (reading 'NODE_DEBUG')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at <unknown> (http://localhost:5173/__cypress/src/node_modules/.vite/deps/cypress_react18.js?v=f70bc591:190:79)
```

### Desired behavior

No error should occur.

### Test code to reproduce

```npx cypress run --browser chrome --component```

### Cypress Version

^12.1.0

### Node version

v18.7.0

### Operating System

Lubuntu

### Other

```"react": "^18.2.0"```

cypress.config.ts:

```js
export default defineConfig({
  component: {
    devServer: {
      framework: "react",
      bundler: "vite",
    },
  },
});
```

**Comment by mike-plummer** [comment] 2022-12-20 17:50
Hi @Arian94 . I believe the second error you're seeing is caused by how you're using `@rollup/plugin-replace` - it's not a "smart" plugin, it just does a find/replace on the exact string you've configured. The error you're seeing is actually coming out of `react` not `cypress` because your Vite config is changing the following line:

```
typeof process === "object" && process.env && process.env.NODE_DEBUG
```
into this
```
typeof process === "object" && (process.env || {}) && process.env.NODE_DEBUG
```

The original (first) line is doing a safe traversal into `process.env` only if it's defined. With your replacement (secondl line) `process.env` can be nil but this line will still attempt to access `process.env.NODE_DEBUG`

Your original error has been [reported before](https://github.com/cypress-io/cypress/issues/21434) and appears to be related to `styled-components` - there is a workaround identified in the comments there that may be useful to you.

I'm going to close this as a duplicate of #21434. If you feel that this is incorrect go ahead and comment and we can reopen.

**Closed as not planned by mike-plummer** 2022-12-20 17:50 UTC
