### ISSUE TITLE
Build hangs on CI (Traivs)

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1333] opened 2018-02-17 15:05 UTC
Seeing this error for Cypress 2.0.0 and 2.0.1 on Travis CI. The build has finished successfully, but keeps hanging.

```
  6 passing (25s)
  (Tests Finished)
  - Tests:           6
  - Passes:          6
  - Failures:        0
  - Pending:         0
  - Duration:        24 seconds
  - Screenshots:     0
  - Video Recorded:  true
  - Cypress Version: 2.0.1
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Example https://travis-ci.org/cypress-io/cypress-example-recipes/jobs/342663254

**Comment by brian-mann** [comment] 2018-02-18 01:54
Doesn't really make sense because there are lots of other travis builds / runs / etc that do complete correctly. Not seeing this in any other CI provider either :/

**Comment by brian-mann** [comment] 2018-02-18 01:55
Travis doesn't offer a way to SSH in, so it's impossible to iterate in their environment.

**Comment by kartikupreti** [comment] 2018-02-18 02:22
@brian-mann Seeing this error on jenkins 2.105 also. 
#1235 
It looked like my error might be due to #674 but after seeing this - this is exactly what I see on jenkins - everything completes fine but after that it just prints the 
cypress:server:timers sending, clearing and receiving messages
on and on.

**Comment by brian-mann** [comment] 2018-02-18 03:45
I can look through the server code and likely guess where this is failing. After it displays the `Tests Finished` banner - if there was a video recording, it will then post process it.

Before doing that, it will end the video capture stream on ffmpeg. If this promise does not resolve... it will hang indefinitely. Likely the root issue is something with the `ffmpeg` capture stream, which unless we can reproduce reliably... really sucks.

@kartikupreti does this happen every time for you? Nothing has actually changed related to this behavior in `2.x.x`.

**Comment by brian-mann** [comment] 2018-02-18 03:47
Reading through the code some more... it's actually possible that its hanging on closing the browser. It actually does that **first** before attempting to end the `ffmpeg` stream. Perhaps there's something not resolving there.

What we can do is add better debug logs for both of these tasks so we can definitely see where it's hanging.

**Comment by brian-mann** [comment] 2018-02-18 06:58
@kartikupreti After investigated #674, this error is completely and totally unrelated to it. In this error, the tests **are** completing... Cypress just isn't completing the processes that come **after** all of that.

**Comment by kartikupreti** [comment] 2018-02-18 07:34
@brian-mann Yes, apologies I just re-read #674, this is not related. 
No it doesn't happen all the time - yes it might be related to video capture stream. I am trying to run it a few times with videoRecording as `false` . Will update here.

**Comment by kartikupreti** [comment] 2018-02-19 07:16
@brian-mann It doesn't seem to be related to me setting the videoRecording option. However, I upgraded to cypress 2.0.2 and ran a few times and have pasted the debug log below if it helps.  
For a successful quit. 
```
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers clearing timer id 375 from queue { '375': { args: [], ms: 85000, cb: [Function] } }
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers queuing timer id 376 after 85000 ms
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:project onMocha end
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers child received timer id 376

  6 passing (29s)


  (Tests Finished)

  - Tests:           6
  - Passes:          6
  - Failures:        0
  - Pending:         0
  - Duration:        28 seconds
  - Screenshots:     0
  - Video Recorded:  true
  - Cypress Version: 2.0.2
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:headless attempting to close the browser
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:browsers killing browser process
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:proxy received response for { url: 'http://localhost:38888/arc/sqlrun/jsonselect_parallel', headers: { vary: 'Cookie', 'content-type': 'text/plain', 'transfer-encoding': 'chunked', connection: 'close', date: 'Mon, 19 Feb 2018 06:58:59 GMT', server: 'localhost' }, statusCode: 200 }
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:browsers:electron closed event fired
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:browsers browser process killed
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:headless ending the video recording: /home/jenkins/test/workspace/ui_tests/cypress/cypress/videos/zvw51.mp4
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers queuing timer id 377 after 30000 ms
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers child received timer id 377
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers clearing timer id 377 from queue { '376': { args: [], ms: 85000, cb: [Function] }, '377': { args: [], ms: 30000, cb: [Function: bound cleanupWebsocketResources] } }
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers clearing timer id 376 from queue { '376': { args: [], ms: 85000, cb: [Function] } }
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:timers clearing timer id 376 from queue {}
Mon, 19 Feb 2018 06:58:59 GMT cypress:server:video ffmpeg ended


  (Video)

  - Started processing:   Compressing to 32 CRF
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 22
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 23
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 24
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 25
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 26
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 27
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 28
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 29
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 30
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 31
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 32
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 33
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 34
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 39
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 40
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:timers child sending timer id 41
  - Finished processing:  /home/jenkins/test/workspace/ui_tests/cypress/cypress/videos/zvw51.mp4 (2 seconds)
Mon, 19 Feb 2018 06:59:01 GMT cypress:server:headless Should copy Circle Artifacts? false


  (All Done)

Mon, 19 Feb 2018 06:59:01 GMT cypress:server about to exit with code 0
2018-02-19T06:59:01.704Z cypress:cli Stopping XVFB
```
and a 'hung' run
```
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:timers queuing timer id 404 after 85000 ms
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:project onMocha end
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:timers child received timer id 404

  6 passing (29s)


  (Tests Finished)

  - Tests:           6
  - Passes:          6
  - Failures:        0
  - Pending:         0
  - Duration:        29 seconds
  - Screenshots:     0
  - Video Recorded:  true
  - Cypress Version: 2.0.2
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:headless attempting to close the browser
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:browsers killing browser process
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:proxy received response for { url: 'http://localhost:38888/arc/sqlrun/jsonselect_parallel', headers: { vary: 'Cookie', 'content-type': 'text/plain', 'transfer-encoding': 'chunked', connection: 'close', date: 'Mon, 19 Feb 2018 07:03:16 GMT', server: 'localhost' }, statusCode: 200 }
Mon, 19 Feb 2018 07:03:16 GMT cypress:server:proxy received response for { url: 'http://localhost:38888/arc/reports/savedashboard', headers: { vary: 'Cookie', 'content-type': 'application/json', 'transfer-encoding': 'chunked', connection: 'close', date: 'Mon, 19 Feb 2018 07:03:16 GMT', server: 'localhost' }, statusCode: 200 }
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 22
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 23
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 24
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 25
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 26
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 27
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 28
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 29
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 30
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 31
Mon, 19 Feb 2018 07:03:17 GMT cypress:server:timers child sending timer id 32
```

**Comment by brian-mann** [comment] 2018-07-01 00:40
Can you update to 3.0.2 and see if this issue is resolved?

We updated ffmpeg to 4.x.x there and added many more debugging logs.

Also please be sure that you use DEBUG=cypress:* cypress run when running so that we can get the debug logs to understand what is happening.

**Comment by crosscompile** [comment] 2018-07-11 21:17
@brian-mann I'm seeing tests hang occasionally on 3.0.2, running with `DEBUG=cypress:*` outputs (scrubbed):
```
================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:  3.0.2                                                            │
  │ Browser:  Electron 59 (headless)                                           │
  │ Specs:    10 found (                                                       │
  │ Run URL:                                                                   │
  └────────────────────────────────────────────────────────────────────────────┘

Wed, 11 Jul 2018 20:21:04 GMT cypress:server:run before spec run { name: '', relative: '', absolute: '' }
Wed, 11 Jul 2018 20:21:04 GMT cypress:server:timers queuing timer id 4 after 10000 ms
Wed, 11 Jul 2018 20:21:04 GMT cypress:server:timers child received timer id 4
Wed, 11 Jul 2018 20:21:04 GMT cypress:server:timers clearing timer id 4 from queue { '4': { args: [], ms: 10000, cb: [Function] } }

────────────────────────────────────────────────────────────────────────────────
                                                                                
  Running: ...                                      (1 of 10) 
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:run about to run spec { spec: { name: '', relative: '', absolute: '' }, isHeadless: true, browserName: 'electron' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture started { command: 'ffmpeg -n 20 /home/jenkins/.cache/Cypress/3.0.2/Cypress/resources/app/packages/server/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -f image2pipe -use_wallclock_as_timestamps 1 -i pipe:0 -y -vcodec libx264 -preset ultrafast /var/lib/jenkins/workspace/mp4' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:openproject resetting project state, preparing to launch browser
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:project resetting project instance
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:server Setting remoteAuth undefined
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:cors Parsed URL { port: '443', tld: '', domain: '' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:server Setting remoteOrigin 
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:server Setting remoteHostAndPort { port: '443', tld: '', domain: '' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:server Setting remoteDocDomain 
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:server Getting remote state: { auth: undefined, props: { port: '443', tld: '', domain: '' }, origin: '', strategy: 'http', visiting: undefined, domainName: '', fileServer: null }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:timers queuing timer id 5 after 30000 ms
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:openproject launching browser: electron, spec: 
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:timers child received timer id 5
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:browsers opening browser electron
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:saved_state noop saved state
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: 'ffmpeg version N-45896-g19c3df0cd-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libavutil      56. 17.100 / 56. 17.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libavcodec     58. 19.100 / 58. 19.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libavformat    58. 13.100 / 58. 13.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libavdevice    58.  4.100 / 58.  4.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libavfilter     7. 20.100 /  7. 20.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libswscale      5.  2.100 /  5.  2.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libswresample   3.  2.100 /  3.  2.100' }
Wed, 11 Jul 2018 20:21:05 GMT cypress:server:video capture stderr log { message: '  libpostproc    55.  2.100 / 55.  2.100' }
Wed, 11 Jul 2018 20:21:14 GMT cypress:server:timers child sending timer id 3
Wed, 11 Jul 2018 20:21:14 GMT cypress:server:timers child sending timer id 4
Wed, 11 Jul 2018 20:21:35 GMT cypress:server:timers child sending timer id 5
```
After that it hangs indefinitely.  Let me know if any other logs would be helpful.

**Comment by brian-mann** [comment] 2018-07-11 21:45
Yup everyone is having the same issue. We've added more debug logs in `3.0.3` and came up with a workaround that'll likely release after.

It honestly makes no sense because it appears to be hanging on **synchronous** code randomly. With additional debug logs we should have a clearer picture but regardless we'll figure it out.

### To solve this today

Just switch to using Chrome + our Docker containers (or install them yourself). I believe Chrome is already installed by default in Travis. That will "just work" as this is an Electron only problem.

**Comment by jaredpalmer** [comment] 2018-07-11 22:16
@brian-mann This works. Thank you. However, now our team must decide either to lose confidence in our tests (occasionally they hang) or we don't test our Stripe payment flows. Please please please fix soon!

**Comment by brian-mann** [comment] 2018-07-11 22:24
We have spent a considerable amount of time tracking this down and looking into it. The problem is that it fails randomly (and not in every CI provider). Because of that, it's extremely difficult to understand the root cause.

It's a high up item on our list and we'll get it fixed soon. We prioritize problems in CI.

**Comment by scottcrowesai** [comment] 2018-07-12 14:46
@brian-mann I'm seeing similar behavior with Chrome inside the Docker container. 

I'm on version `3.0.2` and using the `cypress/browsers:chrome67` docker image for my base. 

After about half a dozen feature files the test freeze up while switching from one test to another. The `DEBUG=cypress:*` output show a few hundred `cypress:server:timers child sending timer id` messages and then stop.

Should this be a separate issue or likely the same cause?

**Comment by scottcrowesai** [comment] 2018-07-12 14:52
Mine might be more fitting under #1912

**Comment by sjones6** [comment] 2018-07-17 19:06
I experience this issue today on CI (specs below). I tried running with Chrome (also inside Docker container) but experienced the same issue as using electron.

I'm on Cypress 3.0.2 and running on CircleCI.

As a workaround, I wrapped the Cypress runtime in a Node script and that allowed my test process to finish. Sharing the approach here in case it helps anyone else.

(uses the [death](https://www.npmjs.com/package/death) package for process cleanup)
```javascript
const ON_DEATH = require('death')
const { spawn } = require('child_process');

const cy = spawn('node', ['./node_modules/.bin/cypress', 'run', '--record'], {
  cwd: __dirname,
  env: process.env
});

let out = ''
const end = () => {
  process.kill(cy.pid);

  // looks for X of Y failed in the test summary, if finds, exits with 1
  // otherwise exits with 0.
  process.exit(/\d+\s+of\s+\d+\s+failed/.test(out) ? 1 : 0)
}

cy.stdout.on('data', (data) => {
  const str = data.toString();
  out = out + str;

  // a simple test to listen for the end of the run
  // wait 20secs to exit on its own
  if (/Run Finished/i.test(str)) {
    setTimeout(end, 20 * 1000);
  }
  console.log(str)
});

cy.stderr.on('data', (data) => {
  console.error(data.toString());
});

cy.on('close', (code) => {
  process.exit(code);
});

ON_DEATH(() => {
  process.kill(cy.pid);
});
```
Then, in my bash script, I call `node ./run_cypress.js` rather than calling `node ./node_modules/.bin/cypress run` directly.

Thanks for the debugging/fixes from the Cypress team. Look forward to getting this one solved!

**Comment by sjones6** [comment] 2018-07-21 14:35
@jennifer-shehane : Thanks for pointer. That does look like a cleaner way to implement that. I'd just need to confirm that the module API doesn't have the same problem hanging that the CLI has on CI. I'll give it a try next week and report back if so.

**Comment by georgesequeira** [comment] 2018-08-22 16:13
@sjones6 did you end up leveraging the module-api to accomplish the same thing. Our team is having the same issue and updating to chrome + docker did not help us out.

**Comment by georgesequeira** [comment] 2018-08-23 13:11
We were facing this issue with CircleCI. It is part of our CI/CD workflow and so manual intervention is not how we wanted to manage this, borrowing from @sjones6, we are making use of the following script. It's not foolproof but it is reducing the amount of manual intervention necessary. I will file a separate ticket with my debug logs but for context we are running over 100 tests across 16 containers and this happens about 1/4 times on the same 2 containers. 

```
#!/usr/bin/env node

/* eslint-env node */
const ON_DEATH = require('death')
const {spawn} = require('child_process')
const path = require('path');
const cypress = require('cypress');
const parseArgs = require('minimist');
const fs = require('fs-extra');
const console = require('console');

const getSpecs = () => {
  const argv = parseArgs(process.argv.slice(2));
  if (argv && argv._ && argv._.length > 0) {
    return argv._.join(',') ;
  }
  throw new Error('--specs are required');
};


const specs = getSpecs();
var lastMessage = new Date();
var pids = [];

var spawnCy = () => {
  var localCy = spawn('node', [
    './node_modules/.bin/cypress',
    'run',
    '--spec', specs,
    '--record'], {
    env: process.env
  });

  localCy.stdout.on('data', (data) => {
    lastMessage =  new Date();
    process.stdout.write(data.toString())
  });

  localCy.stderr.on('data', (data) => {
    lastMessage =  new Date();
    process.stderr.write(data.toString());
  });

  localCy.on('close', (code) => {
    process.exit(code);
  });
  return localCy;
}

var cy = spawnCy(specs);

pids.push(cy.pid);

var numRetries = 0;


const end = () => {
  let pid = cy.pid
  process.kill(pid, 'SIGKILL');
  console.error(`Killed pid ${pid}`)

  // looks for X of Y failed in the test summary, if finds, exits with 1
  // otherwise exits with 0.
  // process.exit(/\d+\s+of\s+\d+\s+failed/.test(out) ? 1 : 0)
}

const TIMEOUT_FROM_LAST_MESSAGE_IN_SEC = 3 * 60;
const INTERVAL_OF_CHECKS_IN_MS = 30 * 1000;

var checkLastMessage = () => {
  var diffInSeconds = (new Date() - lastMessage)/1000;
  console.log(`Last time we saw a message was ${diffInSeconds} seconds ago`)
  if (diffInSeconds > TIMEOUT_FROM_LAST_MESSAGE_IN_SEC) {
    console.log("The last time we saw a message was greater than 3 minutes ago, killing");
    end(cy.pid);
    console.info(`Retries: ${numRetries}`)
    if (numRetries < 4)
    {
      cy = spawnCy(specs);
      pids.push(cy.pid);
      numRetries++;
    }
    else
    {
      console.error("Retried 4 times to re-run cypress and still couldnt get it to not get stuck");
      process.exit(1);
    }

  }
  setTimeout(checkLastMessage, 30000);
}

setTimeout(checkLastMessage, 30000);



ON_DEATH(() => {
  pids.forEach(pid => {
    try {
      console.info(`On death cleaning up if we got stuck along the way. ${pid}`)
      process.kill(pid);
    } catch (err) {
      console.error(`Caught error with killing pid ${pid}. Probably already killed.`)
    }

  });
});

```

**Comment by brian-mann** [comment] 2018-08-23 16:08
@sjones6 switch to Cypress `3.1.0` as we believe we've fixed the issues with it hanging in between running specs.

**Comment by brian-mann** [comment] 2018-08-23 16:11
I'm going to close this issue as I believe it's been resolved by the primary cause of the specs hanging in [`3.1.0`](https://docs.cypress.io/guides/references/changelog.html#3-1-0). If there are separate issues those should be opened as new issues.

**Closed by brian-mann** 2018-08-23 16:11 UTC
Labels: CI: travis, process: build, stage: ready for work
