### ISSUE TITLE
Cypress test runner crashed/getting Aw,snap error in vs code even if i added     "numTestsKeptInMemory": 0, in cypress.json file

### ISSUE THREAD

**Issue by vijay-peruri53** [cypress-io/cypress#23193] opened 2022-08-08 13:25 UTC
### Current behavior

Cypress test runner crashed/getting Aw,snap error in vs code even if i added     "numTestsKeptInMemory": 0, in cypress.json file

### Test code to reproduce

if i execute the scripts for sometime i am getting this Aw, snap errror and failing 

### Cypress Version

5.6.0

**Comment by kolorfilm** [comment] 2022-08-08 18:47
same problem here

**Comment by rockindahizzy** [comment] 2022-08-09 13:57
Hey @vijay-peruri53 thanks for submitting the issue!

- Are you able to upgrade to a newer version of Cypress? It's possible that the issue you are experiencing has been resolved in a more recent version of Cypess.
- Is it possible for you to provide a reproduction of this issue? 

@kolorfilm, are you experiencing this issue on `5.6.0` or a different version of Cypress?

**Comment by kolorfilm** [comment] 2022-08-09 17:12
> @kolorfilm, are you experiencing this issue on `5.6.0` or a different version of Cypress?

On the latest version of Cypress

**Comment by vijay-peruri53** [comment] 2022-08-10 07:22
@rockindahizzy I am facing the issue in 5.6.0 version previously i am not facing this issue but since few days i am seeing this issue.

**Comment by Georgi0304** [comment] 2022-08-10 13:03
I am facing the issue last few days with the latest version of cypress. My test was running fine for 23 mins last week and this week it crashes at about 8 mins.

**Comment by yellowee** [comment] 2022-08-11 11:41
It keeps crashing for me too - Cypress 10

**Comment by rockindahizzy** [comment] 2022-08-15 16:53
Hey @vijay-peruri53, are you able to upgrade to a more recent version of Cypress? You may see performance improvements.

**Comment by vijay-peruri53** [comment] 2022-08-15 17:01
@rockindahizzy  I will try to upgrade to recent version. can You let me what are the changes from  version 5.6.0 to the newer version..?

and can you guide me what are the framework level changes i have to do.

**Comment by rockindahizzy** [comment] 2022-08-15 17:21
@vijay-peruri53, there have been quite a few changes during that timespan. You can find all of the changes [in this change log](https://docs.cypress.io/guides/references/changelog).

In the Major version markers of the change log ([for example 10.0.0](https://docs.cypress.io/guides/references/changelog#10-0-0)), we highlight breaking changes. Also, you will find a migration guide to help migrate to a new version. You may need to look through the migration guides starting at [v6.0.0](https://docs.cypress.io/guides/references/changelog#6-0-0) and decide the best approach for your specific project.

**Comment by vijay-peruri53** [comment] 2022-08-18 13:30
@mike-plummer and @rockindahizzy  in the above comments i see that for the latest version of cypress also having this issue. is there any complete solution for this issue.

**Comment by tpodolskiy** [comment] 2022-08-23 23:34
same with 10.6 its awkward, consistently after running 5 -6 tests

**Comment by nagash77** [comment] 2022-08-25 18:15
Unfortunately we have to close this issue due to inactivity. If anyone following along with this ticket can provide us with a reproducible example/repo please do comment and we can reopen.

**Closed by nagash77** 2022-08-25 18:15 UTC
Labels: stage: awaiting response, topic: aw snap :slightly_frowning_face:, Needs Reproduction

**Comment by samelawrence** [comment] 2023-07-18 19:19
I still experience this issue in Cypress 12+. I have never been able to use the replay feature of Cypress because of this. It happens across multiple machines I run Cypress on. It has never worked for me (MacOS, latest version, 16GB of RAM+, etc.)

**Comment by nagash77** [comment] 2023-07-19 13:17
@samelawrence please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
