### ISSUE TITLE
Small delete tags are not shown in DOM though exists in elements

### ISSUE THREAD

**Issue by RohithQualiT** [cypress-io/cypress#25229] opened 2022-12-20 15:33 UTC
### Current behavior

During the automation in cypress, we are unable to find the delete-icon tags in the whole application

### Desired behavior

![image](https://user-images.githubusercontent.com/102667436/208704796-2a3c1050-399c-4c6a-8aab-a71f96d61f88.png)

### Test code to reproduce

We are using a simple scenario like cy.get(element).click()
Where element = .delete-icon

### Cypress Version

10.10.1

### Node version

8.19.2

### Operating System

Windows 7

### Other

This is the automtion evidence that represents the test case is not passing
![Screenshot (350)](https://user-images.githubusercontent.com/102667436/208702739-821cc0e1-4143-49c1-b079-4b77b6729228.png)

Here in the DOM, though the element is existed, cypress fails to display
![image](https://user-images.githubusercontent.com/102667436/208702973-12f115cf-8b69-487e-882d-df49963dd6f8.png)

Expected element: 
![Cypress_DOM_Issue](https://user-images.githubusercontent.com/102667436/208704442-382fd9ed-cad7-4c1f-a762-ba2f2b1206a1.png)

**Comment by mike-plummer** [comment] 2022-12-20 18:05
Hi @RohithYarramsetty , sorry to hear you're having trouble. Without a reproduction all I can do is guess that there is a failure to bundle/access some assets (SVGs, etc) for the close buttons. Can you review the browser dev tools when running a Cypress test and see if there are console errors or Network failures?

In order to help diagnose your problem we'll need a reproducible example of the issue you're encountering to help us. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. If that can't be provided we will at least need DEBUG logs - instructions are available in the Troubleshooting guide.

Also, please note that we do not support the version of Node you have reported (8.19.2) - our support baseline is [documented here](https://docs.cypress.io/guides/getting-started/installing-cypress#Node-js). Maybe that was a typo?

**Comment by RohithQualiT** [comment] 2022-12-21 04:47
As per @mike-plummer  suggestions, I have updated the node version to 18.12.1.
Here are the network logs recoreded: https://www.loom.com/share/3a586c6f7c4a4575840241392eb92284

Here are the logs documented: 
[Debug_Logs_Cypress.log](https://github.com/cypress-io/cypress/files/10274538/Debug_Logs_Cypress.log)

@mike-plummer Please let me know if you need anything more from myside. I need this bug to be resolved ASAP.
We were very much dependent on the tests. Atleast provide me a workaround mean while.

We have the similar kind of issue in all over the application.

FYI, we  tried testing the same test case in puppeteer(another web automation tool) wherein the tool is working very fine.

Thanks!

**Comment by lmiller1990** [comment] 2022-12-22 01:54
It looks like the icon isn't visible. Is the image (or ico file, or what the asset is) loaded in the Network Tab? It looks like, for whatever reason, the network request that loads your icons isn't succeeding. How/where is your icons loaded?

A potential work-around would be to do `click({ force: true })` which will perform a click, even if the element isn't visible/rendered correctly.

**Comment by astone123** [comment] 2023-01-06 17:02
@RohithYarramsetty have you tried forcing the click with `.click({ force: true })`? Cypress does some checks before clicking to make sure that the element is visible. If the element is being covered some how, Cypress won't click the element unless you force it.

**Comment by RohithQualiT** [comment] 2023-01-06 17:47
Hey @astone123 I knews it. I'm already using it from the initial stages and still no use. So, I believe that this is a drawback of cypress.
![image](https://user-images.githubusercontent.com/102667436/211069583-7523ecb6-6922-47b1-92fe-e52e3600e4ac.png)

cc: @lmiller1990

**Comment by astone123** [comment] 2023-01-06 18:29
@RohithYarramsetty can you share the error message that you get when the click fails? I can see in your video that the `.delete-icon` element is in the DOM, but I don't see the test fail. 

I'd like to understand what error Cypress actually throws when the click action fails. Thanks!

**Comment by RohithQualiT** [comment] 2023-01-07 04:44
@astone123 
> Timed out retrying after 60000ms: Expected to find element: //span[contains(text(),"File")]//parent::div//*[@class="delete-icon"]//*[@id="SMALL-REMOVE"], but never found it.

Here is the error caused: https://www.loom.com/share/15bf1c9045e24220aa9d4ae5418a6456

**Comment by astone123** [comment] 2023-01-10 18:51
@RohithYarramsetty thanks for the video. It looks like you're querying for an element with an `id` of `SMALL-REMOVE`. Does that element exist as a child of the `.delete-icon` element? It wasn't clear in the element inspector in your video. Thanks

**Comment by lmiller1990** [comment] 2023-01-17 01:27
@RohithYarramsetty 

> It looks like the icon isn't visible. Is the image (or ico file, or what the asset is) loaded in the Network Tab?

Cypress thinks the icon isn't  visible - it looks like something is happening and it's failing to load. Is there an error in the network tab for the icon request (maybe a 40x, like 401, 404, etc)?

**Comment by ZachJW34** [comment] 2023-01-24 17:12
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as completed by ZachJW34** 2023-01-24 17:12 UTC
