### ISSUE TITLE
click with multiple option doesn't trigger with correct counts

### ISSUE THREAD

**Issue by eldyvoon** [cypress-io/cypress#4687] opened 2019-07-10 04:45 UTC
This will click 3 times on a button
```js
    cy.get('btn').click()
    cy.get('btn').click()
    cy.get('btn').click()
```

This will click 3 times too
```js
    cy.get('btn').click({multiple: true})
    cy.get('btn').click()
```

But why this will click only 2 times, I expect 4 times
```js
    cy.get('btn').click({ multiple: true })
    cy.get('btn').click({ multiple: true })
```

**Comment by nikhilesh009** [comment] 2019-07-10 06:38
Are you trying to click the same button(element)? if you have multiple buttons with the same element then  guess you don't have to use multiple clicks if you use once {multiple: true}, it will click all button which has the same element

**Comment by eldyvoon** [comment] 2019-07-10 07:01
I'm trying to click an element for many times.

**Comment by nikhilesh009** [comment] 2019-07-10 07:20
i have some use case where i click an element and it works until an element is disabled(or disapper), and it not depends on how many elements available

**Comment by jennifer-shehane** [comment] 2019-07-10 10:02
Please provide the html example you are running these tests against, there's no way to tell how this should run without the HTML. Thanks!

**Comment by nikhilesh009** [comment] 2019-07-18 15:59
sorry for late response, 
here is HTML
`   cy.get('[name="delete"]', { timeout: 4500 }).click({ multiple: true }); `
![Screenshot 2019-07-18 at 17 53 17](https://user-images.githubusercontent.com/40767850/61472855-9231ea00-a985-11e9-9ba8-e0fc1e65c19d.png)


` <div class="result-container" seats-loader="false">
          <train-item-selected ng-repeat="selected in $ctrl.selectedList" count="$index + 1" item="selected" reserve-seat="$ctrl.search.reserve_seat" on-remove="$ctrl.onRemoveHandler($event)" class="ng-scope ng-isolate-scope" style=""><md-card flex="" class="train-item _md flex">
  <div flex="" layout="" style="background-color: #c1c1c1" class="layout-row flex">
    <strong layout-padding="" class="layout-padding ng-binding">Offer #1</strong>
    <div flex="" style="text-align: right;" class="flex">
      <cmtr-icon-button name="delete" tooltip="'Remove train item'" ng-click="$ctrl.onRemoveHandler()" class="ng-isolate-scope" role="button" tabindex="0"><button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" aria-label="'Remove train item'" md-labeled-by-tooltip="md-tooltip-364"><md-icon class="material-icons md-18" role="img" aria-label="{{$ctrl.name}}">delete</md-icon><div class="md-ripple-container"></div></button></cmtr-icon-button>
    </div>
  </div>
  <div class="slice-header">Outbound</div>
  <train-item-header flex="" item="$ctrl.item.train_item.slices[0]" class="ng-isolate-scope flex"><div flex="" layout="" layout-padding="" style="border-bottom: 1px dashed #ddd;" layout-align="start start" class="layout-padding layout-align-start-start layout-row flex">
  <div>Class: <strong class="ng-binding">2nd</strong></div>
  <div>Fare type: <strong class="ng-binding">Flexpreis</strong></div>
  <div>Total duration: <strong class="ng-binding">4h 30m</strong></div>
  <div flex="" layout="column" layout-align="start end" class="layout-align-start-end layout-column flex">
    <div>price: <strong class="ng-binding">167.00 EUR</strong></div>
    <ng-transclude>
    
    
  </ng-transclude>
  </div>
</div>
</train-item-header>
  <train-item-content segments="$ctrl.item.train_item.slices[0].segments" class="ng-isolate-scope"><div layout="" layout-padding="" layout-align="none center" ng-repeat-start="segment in ::$ctrl.segments" class="layout-padding ng-scope layout-align-start-center layout-row">
  <div flex="35" layout="column" class="layout-column flex-35">
    <strong><span ng-bind="::segment.departure_location_name" class="ng-binding">Berlin Hbf (tief)</span></strong>
    <span class="train-item-label ng-binding">2019-07-21 06:30</span>
  </div>
  <div flex="35" layout="column" class="layout-column flex-35">
    <strong><span ng-bind="::segment.arrival_location_name" class="ng-binding">München Hbf</span></strong>
    <span class="train-item-label ng-binding">2019-07-21 11:00</span>
  </div>
  <div flex="15" class="flex-15">
    <span class="train-item-label ng-binding" ng-bind="::segment.durationText">4h 30m</span>
  </div>
  <div flex="" style="text-align: right; color: #2196f3; font-weight: 500" ng-bind="::segment.train_number" class="ng-binding flex">ICE  503</div>
</div>

</train-item-content>

  
  <div flex="" layout-padding="" style="text-align: right; border-top: 1px solid #e0e0e0;" class="layout-padding flex">
    Total price: <strong style="font-size: 16px" class="ng-binding"> 167.00 EUR</strong>
  </div>
</md-card>
</train-item-selected><train-item-selected ng-repeat="selected in $ctrl.selectedList" count="$index + 1" item="selected" reserve-seat="$ctrl.search.reserve_seat" on-remove="$ctrl.onRemoveHandler($event)" class="ng-scope ng-isolate-scope"><md-card flex="" class="train-item _md flex">
  <div flex="" layout="" style="background-color: #c1c1c1" class="layout-row flex">
    <strong layout-padding="" class="layout-padding ng-binding">Offer #2</strong>
    <div flex="" style="text-align: right;" class="flex">
      <cmtr-icon-button name="delete" tooltip="'Remove train item'" ng-click="$ctrl.onRemoveHandler()" class="ng-isolate-scope" role="button" tabindex="0"><button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" aria-label="'Remove train item'" md-labeled-by-tooltip="md-tooltip-365"><md-icon class="material-icons md-18" role="img" aria-label="{{$ctrl.name}}">delete</md-icon></button></cmtr-icon-button>
    </div>
  </div>
  <div class="slice-header">Outbound</div>
  <train-item-header flex="" item="$ctrl.item.train_item.slices[0]" class="ng-isolate-scope flex"><div flex="" layout="" layout-padding="" style="border-bottom: 1px dashed #ddd;" layout-align="start start" class="layout-padding layout-align-start-start layout-row flex">
  <div>Class: <strong class="ng-binding">2nd</strong></div>
  <div>Fare type: <strong class="ng-binding">Flexpreis</strong></div>
  <div>Total duration: <strong class="ng-binding">5h 07m</strong></div>
  <div flex="" layout="column" layout-align="start end" class="layout-align-start-end layout-column flex">
    <div>price: <strong class="ng-binding">167.00 EUR</strong></div>
    <ng-transclude>
    
    
  </ng-transclude>
  </div>
</div>
</train-item-header>
  <train-item-content segments="$ctrl.item.train_item.slices[0].segments" class="ng-isolate-scope"><div layout="" layout-padding="" layout-align="none center" ng-repeat-start="segment in ::$ctrl.segments" class="layout-padding ng-scope layout-align-start-center layout-row">
  <div flex="35" layout="column" class="layout-column flex-35">
    <strong><span ng-bind="::segment.departure_location_name" class="ng-binding">Berlin Hbf (tief)</span></strong>
    <span class="train-item-label ng-binding">2019-07-21 07:37</span>
  </div>
  <div flex="35" layout="column" class="layout-column flex-35">
    <strong><span ng-bind="::segment.arrival_location_name" class="ng-binding">München Hbf</span></strong>
    <span class="train-item-label ng-binding">2019-07-21 12:44</span>
  </div>
  <div flex="15" class="flex-15">
    <span class="train-item-label ng-binding" ng-bind="::segment.durationText">5h 07m</span>
  </div>
  <div flex="" style="text-align: right; color: #2196f3; font-weight: 500" ng-bind="::segment.train_number" class="ng-binding flex">ICE  701</div>
</div>

</train-item-content>

  
  <div flex="" layout-padding="" style="text-align: right; border-top: 1px solid #e0e0e0;" class="layout-padding flex">
    Total price: <strong style="font-size: 16px" class="ng-binding"> 167.00 EUR</strong>
  </div>
</md-card>
</train-item-selected><train-item-selected ng-repeat="selected in $ctrl.selectedList" count="$index + 1" item="selected" reserve-seat="$ctrl.search.reserve_seat" on-remove="$ctrl.onRemoveHandler($event)" class="ng-scope ng-isolate-scope"><md-card flex="" class="train-item _md flex">
  <div flex="" layout="" style="background-color: #c1c1c1" class="layout-row flex">
    <strong layout-padding="" class="layout-padding ng-binding">Offer #3</strong>
    <div flex="" style="text-align: right;" class="flex">
      <cmtr-icon-button name="delete" tooltip="'Remove train item'" ng-click="$ctrl.onRemoveHandler()" class="ng-isolate-scope" role="button" tabindex="0"><button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" aria-label="'Remove train item'" md-labeled-by-tooltip="md-tooltip-366"><md-icon class="material-icons md-18" role="img" aria-label="{{$ctrl.name}}">delete</md-icon></button></cmtr-icon-button>
    </div>
  </div>
  <div class="slice-header">Outbound</div>
  <train-item-header flex="" item="$ctrl.item.train_item.slices[0]" class="ng-isolate-scope flex"><div flex="" layout="" layout-padding="" style="border-bottom: 1px dashed #ddd;" layout-align="start start" class="layout-padding layout-align-start-start layout-row flex">
  <div>Class: <strong class="ng-binding">2nd</strong></div>
  <div>Fare type: <strong class="ng-binding">Flexpreis</strong></div>
  <div>Total duration: <strong class="ng-binding">3h 58m</strong></div>
  <div flex="" layout="column" layout-align="start end" class="layout-align-start-end layout-column flex">
    <div>price: <strong class="ng-binding">167.00 EUR</strong></div>
    <ng-transclude>
    
    
  </ng-transclude>
  </div>
</div>
</train-item-header>
  <train-item-content segments="$ctrl.item.train_item.slices[0].segments" class="ng-isolate-scope"><div layout="" layout-padding="" layout-align="none center" ng-repeat-start="segment in ::$ctrl.segments" class="layout-padding ng-scope layout-align-start-center layout-row">
  <div flex="35" layout="column" class="layout-column flex-35">
    <strong><span ng-bind="::segment.departure_location_name" class="ng-binding">Berlin Hbf (tief)</span></strong>
    <span class="train-item-label ng-binding">2019-07-21 08:05</span>
  </div>
  <div flex="35" layout="column" class="layout-column flex-35">
    <strong><span ng-bind="::segment.arrival_location_name" class="ng-binding">München Hbf</span></strong>
    <span class="train-item-label ng-binding">2019-07-21 12:03</span>
  </div>
  <div flex="15" class="flex-15">
    <span class="train-item-label ng-binding" ng-bind="::segment.durationText">3h 58m</span>
  </div>
  <div flex="" style="text-align: right; color: #2196f3; font-weight: 500" ng-bind="::segment.train_number" class="ng-binding flex">ICE 1003</div>
</div>

</train-item-content>

  
  <div flex="" layout-padding="" style="text-align: right; border-top: 1px solid #e0e0e0;" class="layout-padding flex">
    Total price: <strong style="font-size: 16px" class="ng-binding"> 167.00 EUR</strong>
  </div>
</md-card>
</train-item-selected>
        </div> `

**Comment by jennifer-shehane** [comment] 2021-02-22 14:42
I'm not able to reproduce the described behavior from the repro provided. It clicks all buttons every time the click with multiple value is true in Cypress 6.5.0. 

<img width="1560" alt="Screen Shot 2021-02-22 at 9 41 29 AM" src="https://user-images.githubusercontent.com/1271364/108723452-44cb1680-74f2-11eb-9a87-979b22ea4fd3.png">

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-22 14:42 UTC
Labels: stage: needs information
