### ISSUE TITLE
Reference is  not working even after adding enabling but working after adding space

### ISSUE THREAD

**Issue by Atabic** [cypress-io/cypress#21938] opened 2022-05-31 11:06 UTC
### Current behavior

As per the documentation, you need to enable `/// <reference types="cypress" /> ` on top of the file or in the plugin folder, I did the exact same thing but It was not working so accidentally I added a space after the closing tag and it all of a sudden started working(The eslint and intellisense ). here are my eslint configurations. 
```
{
  "root": true,
  "plugins": ["eslint-plugin-cypress"],
  "extends": [
    "plugin:cypress/recommended"
  ],
  "env": {
    "cypress/globals": true
  }
}
```
and here are the plugin folder index file
```
/// <reference types="cypress" />
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line no-unused-vars
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}
```

### Desired behavior

It should be working without adding space after the reference tag. 

### Test code to reproduce

You can reproduce it in any CRA project after adding cypress and eslint configurations

### Cypress Version

9.6.1

**Comment by mjhenkes** [comment] 2022-05-31 17:16
@Atabic Could you describe what is not working? At first glance this doesn't seem to be a cypress issue. If you believe this to be a cypress issue could you provide a reproducible repo that we could look into?

**Comment by Atabic** [comment] 2022-06-01 07:44
The eslint and IntelliSense don't work, also I figured out another thing, that is whenever I close the plugin file in vscode, the eslint and IntelliSense stop working.

**Comment by mschile** [comment] 2022-06-02 21:43
@Atabic, I created a new CRA and added `cypress` and `eslint-plugin-cypress` but was unable to reproduce the issue. Both `eslint` and `IntelliSense` functioned as expected within VSCode. Do you have a reproducible example you could provide?

https://github.com/mschile/create-react-app-issue-21938

**Comment by mjhenkes** [comment] 2022-06-09 20:43
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-06-09 20:43 UTC
Labels: stage: awaiting response
