### ISSUE TITLE
 Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

### ISSUE THREAD

**Issue by splincode** [cypress-io/cypress#28988] opened 2024-02-21 16:00 UTC
### Current behavior

 Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
 
 https://github.com/taiga-family/taiga-ui/actions/runs/7990568727/job/21819665841?pr=6848

### Desired behavior

<img width="1285" alt="image" src="https://github.com/cypress-io/cypress/assets/12021443/6841dca5-34c1-4511-a344-8a2b9a58dc8b">

### Test code to reproduce

https://github.com/taiga-family/taiga-ui/pull/6848

### Cypress Version

13.6.5

### Node version

18

### Operating System

Ubuntu latest

**Comment by jennifer-shehane** [comment] 2024-02-21 16:27
Duplicate of https://github.com/cypress-io/cypress/issues/28982 - not sure if these bus errors are related at this point. We have an example and are working on diagnosing the issue. The issue has to do with use of NX with Cypress.

**Closed as not planned by jennifer-shehane** 2024-02-21 16:27 UTC
