### ISSUE TITLE
Cypress_cy.visit-->Unable to open URL: https://www.binance.com/en/markets

### ISSUE THREAD

**Issue by Sourajeet01** [cypress-io/cypress#6050] opened 2019-12-26 16:36 UTC
```
CypressError: cy.visit() failed trying to load:

https://www.binance.com/en/markets/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: Parse Error: Header overflow

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: Parse Error: Header overflow
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by jennifer-shehane** [comment] 2019-12-30 09:46
I can recreate this issue with the test code below. 

```js
it('fails to visit', () => {
  cy.visit('https://www.binance.com/en/markets')
})
```

This is a regression introduced in Cypress 3.5.0

## 3.4.1

![Screen Shot 2019-12-30 at 4 15 56 PM](https://user-images.githubusercontent.com/1271364/71576651-b3dff180-2b1f-11ea-9ebc-44f804f8cd79.png)


## 3.5.0

![Screen Shot 2019-12-30 at 4 14 21 PM](https://user-images.githubusercontent.com/1271364/71576586-7713fa80-2b1f-11ea-9ba0-69a357c7cd62.png)

# Workaround

Please downgrade to Cypress version 3.4.1 to avoid this error until there is a patch fix released.

**Comment by flotwig** [comment] 2019-12-30 17:38
Duplicate of #5602

**Closed by flotwig** 2019-12-30 17:38 UTC
Labels: stage: needs investigating, type: regression, v3.5.0 :bug:
