### ISSUE TITLE
Allowing Pinning Of Tests In Search Runner

### ISSUE THREAD

**Issue by daftspaniel** [cypress-io/cypress#17261] opened 2021-07-09 09:28 UTC
### What would you like?
Allowing pinning Of Tests In Search Runner so I can quickly build an adhoc list of tests to run.

### Why is this needed?

Currently I can use the existing search feature to identify a useful subset of tests to run during development. However not all relevant tests can be selected with a single search on the filename. It would be useful to perform a search, pin some or all test tests, perform another search, pin more tests and build up a focusses list which would then persist until cleared.

There would then be a 'run pinned tests' button to execute all the pinned items.

Thanks and I hope that is clear :)

**Comment by jennifer-shehane** [comment] 2021-07-09 14:03
Duplicate of https://github.com/cypress-io/cypress/issues/3607

**Closed by jennifer-shehane** 2021-07-09 14:03 UTC
