### ISSUE TITLE
Can't start server message in case try to run Firefox on cypress 4.0.1

### ISSUE THREAD

**Issue by aman-mcmb** [cypress-io/cypress#6381] opened 2020-02-08 09:03 UTC
### Current behavior:

Firefox still does not open on Mac.   No Firefox window was open. Even i restarted the system and try to run firefox through cypress

**Error message**

It shows Can't start server. 

An unexpected error was received from Marionette connection:

Error: cannot open socket

To avoid this error, ensure sure that there are no other instances of Firefox launched by Cypress running.

### Desired behavior:

Firefox Browser should open with cypress.

### Test code to reproduce

install cypress 4.0.1
Try to Run the Scripts over FireFox.

### Versions
Cypress : 4.0.1

OS - iMac 10.14.6 , macOS Mojave
3.4 GHz Intel Core i5

![cypress ](https://user-images.githubusercontent.com/54840531/74082423-d4388f80-4a7f-11ea-9847-8f8cc8a33bf0.png)
![Screenshot 2020-02-08 at 2 32 39 PM](https://user-images.githubusercontent.com/54840531/74082435-ef0b0400-4a7f-11ea-8075-7a4050fa7a9c.png)
![Screenshot 2020-02-08 at 2 33 01 PM](https://user-images.githubusercontent.com/54840531/74082436-f03c3100-4a7f-11ea-8255-a5e0bf46f7c2.png)

**Comment by YOU54F** [comment] 2020-02-08 09:22
Have you got Firefox already open, prior to starting cypress? If so it won’t work, as per the message.

If you expect Firefox w/ cypress to work, with Firefox open beforehand then this ticket is a dupe of https://github.com/cypress-io/cypress/issues/6380

**Comment by aman-mcmb** [comment] 2020-02-08 10:13
> Have you got Firefox already open, prior to starting cypress? If so it won’t work, as per the message. ( messages states ff launched by cypress but it could be ff launched by user prior to running cypress )
> 
> If you expect Firefox w/ cypress to work, with Firefox open beforehand then this ticket is a dupe of #6380

No firefox window was open. i check that already twice. Even i have restarted the system and then start cypress. Still not working.

**Comment by YOU54F** [comment] 2020-02-08 10:16
Hmm.  Does it also fail to load in 4.0.0?

**Comment by aman-mcmb** [comment] 2020-02-10 08:10
> Hmm. Does it also fail to load in 4.0.0?

no, 4.0.1

**Comment by jennifer-shehane** [comment] 2020-02-10 08:27
Duplicate of #6387

**Closed by jennifer-shehane** 2020-02-10 08:27 UTC
