### ISSUE TITLE
Before and After images for iframes are not available in the test result due to <iframe> placeholder for about:blank

### ISSUE THREAD

**Issue by CusHoria** [cypress-io/cypress#6067] opened 2019-12-31 09:47 UTC
### Current behavior:

Before and after images are unavailable while checking iframes actions

https://imgur.com/a/8MDJphh

### Desired behavior:

The user is able to see before/after screenshot on an iframe at the end of a test run

After the user performs a visit and action on an iframe, if the user checks the before/after images on it, it would be noticed that <iframe> placeholder for about:blank is displayed

### Steps to reproduce: (app code and test code)

Visit a page that uses iframe
Perform small actions
Check  before/after

### Versions
Cypress, 3.8.0, OS Win8, Chrome 79.0.3945.88

**Comment by jennifer-shehane** [comment] 2020-01-02 06:13
Closing as duplicate of https://github.com/cypress-io/cypress/issues/1433

**Closed by jennifer-shehane** 2020-01-02 06:13 UTC
