### ISSUE TITLE
Class WebSwapCGLLayer is implemented in both... error

### ISSUE THREAD

**Issue by tit** [cypress-io/cypress#21615] opened 2022-05-24 12:03 UTC
### Current behavior

`npx cypress run`
↓
```
objc[29971]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb503e3948) and /Users/tit/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x111fa89c8). One of the two will be used. Which one is undefined.
```

```
node --version
# v18.1.0

npm --version
# 8.8.0

cypress --version
# Cypress package version: 9.7.0
# Cypress binary version: 9.7.0
# Electron version: 18.0.4
# Bundled Node version: 16.13.2

Chrome: Version 101.0.4951.64 (Official Build) (arm64)
```

### Desired behavior

No warning :)

### Test code to reproduce

Install last Cypress version
npx cypress run

### Cypress Version

9.7.0

**Comment by mschile** [comment] 2022-05-24 21:30
I was able to reproduce the warning on Cypress 9.7.0. Downgrading to Cypress 9.6.1 did not reproduce the warning. I believe it's related to the [electron upgrade](https://github.com/cypress-io/cypress/commit/8311cf15ff84086f0357c812bfa9d68162e02756#diff-f2f892654ff3b0ae74472e3606a75f32817c5a029dbafd3112c1be0e8ab5f90bR26) and this issue https://github.com/electron/electron/issues/33685

**Comment by mjhenkes** [comment] 2022-05-25 16:40
@tit, Is this warning causing any issues in cypress that you can see?

**Comment by CyrilKrylatov** [comment] 2022-06-15 09:05
Hello everyone,

I might have the same issue with a very new just freshly install of Cypress, the "migration helper" seems to be stuck:

![ss_ 5461](https://user-images.githubusercontent.com/1059657/173788682-6f3ba94b-5948-4aa2-b612-e1e05d8bb501.jpg)

And I have the following message in my terminal:

```bash
❯ yarn cy:gui
yarn run v1.22.5
$ node_modules/.bin/cypress open --config-file "assets/frontend/tests/cypress/cypress-config.json"
It looks like this is your first time using Cypress: 10.1.0

✔  Verified Cypress! /Users/cyrilkrylatov/Library/Caches/Cypress/10.1.0/Cypress.app

Opening Cypress...
objc[16715]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb41da6948) and /Users/cyrilkrylatov/Library/Caches/Cypress/10.1.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10a69f9c8). One of the two will be used. Which one is undefined.
```

with :

```❯ node --version
v18.3.0```

```❯ yarn --version
1.22.5```

```❯ ./node_modules/.bin/cypress --version
Cypress package version: 10.1.0
Cypress binary version: 10.1.0
Electron version: 18.0.4
Bundled Node version: 16.13.2```

Please do tell me if I can provide you further informations.

Thank you for your time!

**Comment by chynamyerz** [comment] 2022-06-17 05:54
Experiencing the same issue as defined by @CyrilKrylatov, is there anyone who has figured out how to resolve the issue?

**Comment by darcyadams** [comment] 2022-06-27 17:10
I started seeing this warning after upgrading from 8.x to 10.1. Have not found a solution.

**Comment by splincode** [comment] 2022-06-27 22:20
fixed by 10.2

**Comment by sheecegardezi** [comment] 2022-06-28 05:48
Hello,

I encountered same isssue will followign this tetorial https://medium.com/nerd-for-tech/setting-up-cypress-193166f85b33. Freshly install of Cypress version 10.2.0 on Mac:

```
npx cypress open

objc[XYZ]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (XYZ) and /Users/sasuperdev/Library/Caches/Cypress/10.2.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (XYZ). One of the two will be used. Which one is undefined.

```

Please do tell me if I can provide you further informations.

Thank you for your time!

**Comment by id-dan** [comment] 2022-06-28 05:55
I got the same issue on macOS with cypress v10.2
<img width="1400" alt="Screenshot 2022-06-28 at 08 54 00" src="https://user-images.githubusercontent.com/52101871/176103676-752d3f02-13b0-44dd-a73b-6427061563a2.png">

**Comment by liuyafei0228** [comment] 2022-06-29 15:11
<img width="821" alt="image" src="https://user-images.githubusercontent.com/59075395/176471620-a5b86a35-79b6-4962-8c42-558604cc4273.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/59075395/176471852-51ba872b-5ed7-41c9-b429-878c634dd6fa.png">

**Closed** 2022-06-30 23:37 UTC
Labels: type: bug, OS: mac, pkg/electron, E2E-core, fast-follows-1, priority: low, stage: review
