### ISSUE TITLE
Customize chrome icon for easy switching

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#2900] opened 2018-12-05 02:54 UTC
Hey there, I was wondering if cypress could make the cypress-launched chrome app icon look slightly different from the default chrome icon. 

Here's an image showing what it looks like now trying to change apps on a mac: 

![image](https://user-images.githubusercontent.com/2730609/49487051-a6a9e380-f7f5-11e8-9d9c-7689699f2b91.png)

I'm never sure which browser is normal chrome and which is cypress. Maybe the cypress-chrome could have a little cypress logo in it
![image](https://user-images.githubusercontent.com/2730609/49487139-07392080-f7f6-11e8-96b1-e19e8be696c4.png)

Kind of nitpicky I know but it is a constant hassle currently. Thanks!

**Comment by egucciar** [comment] 2018-12-05 03:37
@tnrich i also installed canary for such a use case!

**Comment by jennifer-shehane** [comment] 2018-12-05 04:50
Duplicate of https://github.com/cypress-io/cypress/issues/714

We have a section in the docs with the recommended workarounds above: https://on.cypress.io/launching-browsers#Browser-Icon

**Closed by jennifer-shehane** 2018-12-05 04:50 UTC
Labels: type: duplicate

**Comment by tnrich** [comment] 2020-02-18 18:31
@jennifer-shehane I have been using electron for a while but have recently been having some little usability issues with it. The losing the Devtools issue is still happening for me https://github.com/cypress-io/cypress/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+loses+devtools and clicking Cmd+shift+C in electron doesn't open the Element Inspector 
![image](https://user-images.githubusercontent.com/2730609/74766039-73f0dd00-5239-11ea-890f-4c22796f28ca.png)


I'd love to use chrome but am still blocked from doing so by this issue. Is there no way to slightly customize the icon of the chrome browser launched? 

I'd like this issue to be re-opened if that is at all possible because this is definitely still an issue.

**Comment by jennifer-shehane** [comment] 2020-02-19 08:59
@tnrich No, there is no way for us to edit Chrome's icon since we are simply launching the application on your computer.
