### ISSUE TITLE
TypeError: Class constructor OTLPTraceExporter cannot be invoked without 'new'

### ISSUE THREAD

**Issue by wmputnam** [cypress-io/cypress#27630] opened 2023-08-22 21:23 UTC
### Current behavior

npx cypress open fails with 
TypeError: Class constructor OTLPTraceExporter cannot be invoked without 'new'12.17.4

### Debug logs

```Text
see attached
```

### Cypress Version

12.17.4

### Node version

18.16.0

### Package Manager

npm

### Package Manager Version

8.6.9

### Operating system

Linux

### Operating System Version

macOS Ventura v 13.4.1

### Other

[cypress-OLTPTraceExporter-err.zip](https://github.com/cypress-io/cypress/files/12413129/cypress-OLTPTraceExporter-err.zip)

**Comment by nagash77** [comment] 2023-08-23 13:21
In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by roryschadler** [comment] 2023-08-25 15:56
I'm seeing the same error, and I think it might also be the one mentioned in https://github.com/cypress-io/cypress/issues/26742. My minimal reproduction is here: https://github.com/roryschadler/cypress-debug-allowjs, I reproduce it when using TypeScript specs (and config), and when I have the combination of `"type": "module"` in my `package.json`, and `"allowJs": true"` in my `tsconfig.json` (https://www.typescriptlang.org/tsconfig#allowJs)

For my personal case, I can remove `allowJs` which resolves the issue.

**Comment by HenrikJohnson** [comment] 2023-09-06 21:09
Just FYI I had this issue. But only on MacOS and it seemed to be caused by having a tsconfig.json file with a target of "es5". When switching the target to "es6", the issue went away. The bug report here seems a bit confused since it says Linux, but the OS version is MacOS :).

**Comment by nagash77** [comment] 2023-09-08 20:44
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed as not planned by nagash77** 2023-09-08 20:44 UTC
Labels: topic: installation

**Comment by ocho-cesar** [comment] 2023-09-11 20:44
I got the same error, had to remove the `type: module` from package.json in macOS with cypress 13.1.0

**Comment by TazmanianDI** [comment] 2023-10-11 15:51
FYI, I hit this as well. It seems it was introduced some time in Cypress 12. I was on 10 and upgraded to 13 and hit this. I went backwards by major version and 11 was fine.
