### ISSUE TITLE
I'm trying to run multiple scripts headless in electron ,if the script fails it is not proceeding to next suite and is hanging in electron browser, ./node_modules/.bin/cypress run --spec '/Users/username/git/atlas/cypress/integration/templates//smoke*.js'

### ISSUE THREAD

**Issue by minams2** [cypress-io/cypress#3691] opened 2019-03-12 02:57 UTC
I'm trying to run multiple scripts headless in electron browser, if the script fails it is not proceeding to next suite and is hanging `./node_modules/.bin/cypress run --spec '/Users/username/git/atlas/cypress/integration/templates//smoke*.js'`

**Comment by jennifer-shehane** [comment] 2019-03-13 16:25
Hey @minams2, can you provide the code for the "scripts" and explain what they're doing. Feel free to remove sensitive code or provide psuedo code. We won't be able to figure out why it's hanging without being able to reproduce the hanging also. Thanks!

**Comment by minams2** [comment] 2019-03-18 12:00
Thanks. Let me get back to you with a scenario

**Comment by minams2** [comment] 2019-03-20 14:38
Hi,

Here is snippet of code where it runs fine in chrome and in electron if one of them fails it is not proceeding to next test and quits, this becomes problem for us when we run through jenkins ci/cd since there is no headless browser support for chrome..I really appreciate if you can get back to me
describe(' create', () => {
  beforeEach(() => {
    helper.login();
    template.visitEditForm();
  });

  afterEach(() => {
    helper.visitContentIndex();
  });

  after(() => {
    helper.logout();
  });

  it('should be able to save with no data', () => {
    assertionHelper.assertSaveNoData(template);
  });

  it('should not be able to submit with no data', () => {
    assertionHelper.assertSubmitNoData(template);
  });

  it('should be able to submit with Only Required fields filled', () => {
    template.addDataToRequiredFields();
    template.bottomBar.clickPublish();
  });

  it('should be able to submit with all fields filled', () => {
    template.addDataToAllFields();
    template.bottomBar.clickPublish();
  });
});

**Comment by jennifer-shehane** [comment] 2019-03-27 07:46
Hey @minams2, we're unable to run this code locally since this is all custom helpers we don't have access to. Unfortunately, we will have to close this issue if a reproducible example is not provided.

**Closed** 2019-05-30 09:00 UTC
Labels: stage: needs information
