### ISSUE TITLE
Cypress hangs 

### ISSUE THREAD

**Issue by wbolduc** [cypress-io/cypress#22562] opened 2022-06-28 16:32 UTC
### Current behavior

cypress hangs after trying to configure E2E tests

![image](https://user-images.githubusercontent.com/16736623/176232617-f9a2bfda-df09-4acd-a535-f55c15b5d0f3.png)
Spins forever

(Terminal copy paste start)
npx cypress open

[29600:0628/122937.711:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\<My name>'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1276:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:483:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:77:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
(Terminal copy paste end, don't know why code block formatting isn't working here)

### Desired behavior

Cypress initializes itself

### Test code to reproduce

run `npx cypress open`
Click configure E2E testing
Click continue
Cypress hangs

### Cypress Version

10.2.0

**Comment by lmiller1990** [comment] 2022-06-28 23:06
I think this issue should be solved by https://github.com/cypress-io/cypress/pull/22550 which was released in Cypress 10.3.0. It's caused by certain configurations on windows where the username has white space. 

Can you give Cypress 10.3.0 a try?

**Comment by wbolduc** [comment] 2022-06-29 16:14
My username does in fact have whitespace

I didn't think for that because I actually have 2 users, one with and without my last name.

I'll take a look and report back

**Comment by mjhenkes** [comment] 2022-07-11 20:28
10.3 should fix this issue.

**Closed by mjhenkes** 2022-07-11 20:28 UTC
Labels: stage: awaiting response
