### ISSUE TITLE
Browser crash only with using 9.7.0 version

### ISSUE THREAD

**Issue by pad0n** [cypress-io/cypress#21657] opened 2022-05-27 13:12 UTC
### Current behavior

I have migrated to cypress **9.7.0** from 9.6.1 version and noticed, that some of my tests now fails with browser crash or even possible memory leaks. My tests are running everynight for regression using Jenkins and allure reports. So that was a result of a headless run.
![run](https://user-images.githubusercontent.com/2554597/170701415-945637f1-9b60-4fa5-a353-c9c515515fad.png)

I've also tried to open those tests locally and after 300 seconds of run window with cypress turns completely blank. I've tried to change browser from electron to chrome, but no luck, same issue.
![open](https://user-images.githubusercontent.com/2554597/170701836-a5781a44-7350-46d5-b332-d4354d0da6f1.png)

Yes, that is a big end to end test, but it's perfectly working using older versions of cypress, for example **9.6.1**.
![openOld](https://user-images.githubusercontent.com/2554597/170702087-d9dc8d4c-eed4-4f13-9133-adb1568c9f31.png)

This test was written on cypress 4 and works fine until version 9.6.1

I've also tried to add _numTestsKeptInMemory_ parameter and set it to 1 or 0 - no effect.
I've also tried to add _disable-dev-shm-usage_ parameter - no effect, tests are still finished on 'blank' crashed window.

So now I've downgraded to 9.6.1 but will be glad to have this issue fixed. 

### Desired behavior

I expect cypress to handle that code, that was perfectly working previously.

### Test code to reproduce

This particular test fails at this moment (after clicking Yes button). Interesting, that this code also used in other tests - and those tests are fine. This test also works fine with older cypress, so problem is probably not in code.

<details>
  <summary>Code here</summary>

```
cy.get("layout-modal").then(($detLow) => {
    if ($detLow.find("product-card-review span.module:contains('Packaging model')").length) {
        cy.xpath(locators.packModelLink,).should("exist").should("be.visible").click();
        cy.WaitProgressBar();
        cy.xpath(locators.confirmModuleBtn,).should("exist").should("be.visible").click({ force: true });

        cy.intercept('GET', '/data/hierarchies*').as('wait1');
        cy.intercept('GET', '/data/products/common/*').as('wait2');

        cy.xpath(locators.confirmModuleYesBtn).should("exist").should("be.visible").click();
       
        cy.WaitProgressBar();
        cy.get("recipient-root",).then(($main) => {
            if ($main.find("layout-modal").length) {
                if ($main.find("product-card-review div.infobox-error").length) {
                    //if  some modules still not confirmed - skip for now
                }
                else {
                    cy.wait(['@wait1', '@wait2']);
                    cy.get(locators.reqDetWaiter,).should("exist").should("be.visible");
                    cy.get("div.infobox-success button",).should("exist").should("be.visible");
                }
            }
            else if ($main.find("request-list").length) {
                cy.get("table.table-list thead",).should("exist").should("be.visible");
            }
        });
    }
});
```
</details>

### Cypress Version

9.7.0

### Other

Maybe this is not cypress issue, but browser, but this issue is presented in both: electron and chrome browsers which I needed to use.

**Comment by jennifer-shehane** [comment] 2022-05-27 16:41
If you're using the default Electron browser, the Chromium version updated to Chrome 100 in 9.7.0. Maybe it's related to a memory issue in Chrome 100: https://github.com/cypress-io/cypress/issues/21135 I would probably suggest trying to not run such a long running test in general within Cypress though.

**Comment by mjhenkes** [comment] 2022-05-27 17:46
Closing as a duplicate of #21135

**Closed by mjhenkes** 2022-05-27 17:46 UTC
