### ISSUE TITLE
Error: Webpack Compilation Error, Module not found: Error: Can't resolve 'xxx' in ...

### ISSUE THREAD

**Issue by dclowd9901** [cypress-io/cypress#29767] opened 2024-06-27 19:49 UTC
### Current behavior

We have been attempting for months to upgrade our local cypress version to 13, but have been stymied by an issue that occurs when trying to run tests. 

In effect, there seems to be an issue with Webpack being able to resolve npm dependencies within a yarn pnp/workspaces environment. You are able to open the Cypress binary and get as far as selecting a test, but when you select a test, you're greeted with this error: 

```
Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'cypress-axe' in '/Users/dclowd9901/Code/cypress-13-yarn-pnp-workspace-bug-minimum-reproducible-example/e2e/cypress/support'
```

<img width="2032" alt="343930494-e1122656-0300-44f9-a70e-2a4ca56f2721" src="https://github.com/cypress-io/cypress/assets/1314066/64e5bf8f-2b7e-4c42-a0f8-a9bd9ea3c18d">

Note: I've redacted the stack trace because my actual name is in it. I know Github already exposes your real name if you provide it, but safe practices are a habit.

### Desired behavior

I would expect Cypress's Webpack preprocessor to handle Yarn PNP and Workspaces correctly and resolve the dependencies without erroring.

### Test code to reproduce

I've created a minimum reproducible example in this repo: https://github.com/dclowd9901/cypress-13-yarn-pnp-workspace-bug-minimum-reproducible-example/tree/main

### Cypress Version

13.12.0

### Node version

20.11.1

### Operating System

MacOS 14.5

**Comment by jennifer-shehane** [comment] 2024-06-27 19:58
This is a duplicate of this issue: https://github.com/cypress-io/cypress/issues/27947 Thanks for reporting. We're hoping to work on this as we'd like to fix these regressions that prevent a 13.x upgrade.

**Closed as not planned by jennifer-shehane** 2024-06-27 19:58 UTC
Labels: type: duplicate
