### ISSUE TITLE
Cypress NPM module is silent on permission error when accessing the test binary

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6014] opened 2019-12-19 20:49 UTC
Cypress v3.8.0

Using `cypress/included:3.8.0` to try to run Cypress as another user (an edge case, for sure). Noticed that `cypress --version` launches NPM module, yet returns nothing

<img width="1084" alt="Screen Shot 2019-12-19 at 3 46 29 PM" src="https://user-images.githubusercontent.com/2212006/71208490-14954180-2277-11ea-80b9-bef753f58406.png">

The error is silently swallowed too

```
node@61278ba3b513:/test$ DEBUG=cypress:cli cypress --version
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli Reading binary package.json from: /home/node/.cache/Cypress/3.8.0/Cypress/resources/app/package.json +0ms
node@61278ba3b513:/test$ echo $?
0
```

**Comment by flotwig** [comment] 2022-05-24 17:36
Can no longer reproduce this in Cypress 9.7.0: 
![image](https://user-images.githubusercontent.com/1151760/170097726-a5362a62-7788-4e9a-9c8d-d33af22edba9.png)

Closing since this appears to have been fixed.

**Closed by flotwig** 2022-05-24 17:36 UTC
Labels: type: unexpected behavior, cli, stage: ready for work
