### ISSUE TITLE
EEXIST: file already exists, mkdir 'C:\Users\.....\test\node_modules.bin\cypress'

### ISSUE THREAD

**Issue by AmitaTest** [cypress-io/cypress#15728] opened 2021-03-31 20:28 UTC
I am not able to fix this issue.

**Comment by jennifer-shehane** [comment] 2021-04-01 17:29
Duplicate of https://github.com/cypress-io/cypress/issues/1099

Follow this workaround: https://github.com/cypress-io/cypress/issues/1099#issuecomment-365868891

**Closed by jennifer-shehane** 2021-04-01 17:29 UTC
