### ISSUE TITLE
Using cy.route2, unable to find alias when running in CI (Github actions)

### ISSUE THREAD

**Issue by ChrisSargent** [cypress-io/cypress#8984] opened 2020-10-27 11:15 UTC
### Current behavior
I have some tests that are passing using `open` and when using `run` on my local machine, but which are failing in a Github action. Error is `CypressError: cy.wait() could not find a registered alias for: ...`.

<img width="1314" alt="Screenshot 2020-10-27 at 10 59 06" src="https://user-images.githubusercontent.com/12176122/97293836-7e925600-184d-11eb-939e-56f24c9ba4f3.png">

### Desired behavior
The aliased routes in the `beforeEach` should be available (note they are correctly available in previous and later tests)

### Test code to reproduce
Minimal setup is here: https://github.com/ChrisSargent/cypress-test-tiny.

### Versions
Cypress 5.5.0

**Comment by ChrisSargent** [comment] 2020-10-27 11:32
Actually, I now have this happening in my local machine so at least I can start troubleshooting a little bit easier. Moving the `route2` call to a test specific `beforeEach` instead of a `beforeEach` in the `commands.js` file seemed to get passed this error, but then I started getting undefined for the request - I have a feeling this is something to do with network requests being cancelled from the previous test...

**Comment by ChrisSargent** [comment] 2020-10-27 12:18
<img width="560" alt="Screenshot 2020-10-27 at 13 15 17" src="https://user-images.githubusercontent.com/12176122/97300262-81de0f80-1856-11eb-836d-8e582a4ccde4.png">

Okay, now running locally in Electron but with the `--headed` option, I can see I get a Cypress error as above: 

`> Cannot access 'continueSent' before initialization`

Seems that it would be related to this: https://github.com/cypress-io/cypress/issues/8926, just strange that it works fine when using `cypress open` vs `run`

**Comment by ChrisSargent** [comment] 2020-10-27 12:39
Sorry for the running commentary, but... okay, I moved all my route2 setup out of the `beforeEach` in to a `setupRoutes` function that I call at the beginning of each test, before `cy.visit`. I still get the same error which results in the request being undefined in the subsequent wait. Seems rather flaky because sometimes it's working, sometimes it's not. Works less often when the tests are running headlessly.

**Comment by ChrisSargent** [comment] 2020-10-27 13:24
Waiting for this fix before investigating further: https://github.com/cypress-io/cypress/pull/8978

**Comment by jennifer-shehane** [comment] 2020-10-28 08:19
I think you're running into [this issue](https://github.com/cypress-io/cypress/issues/8926) - which is a timing issue, so it makes sense that it may only happen during `cypress run` - since there could be some variability in the way it runs in Electron versus Chrome or on your GitHub action versus locally. 

Duplicate of https://github.com/cypress-io/cypress/issues/8926

**Closed by jennifer-shehane** 2020-10-28 08:19 UTC
