### ISSUE TITLE
Unable to log into Salesforce

### ISSUE THREAD

**Issue by mharrell** [cypress-io/cypress#4273] opened 2019-05-21 15:55 UTC
There was a comment about this same issue in December of 2018, but I don't know if they opened a bug or not. 

### Current behavior:

When I attempt to log into Salesforce, I am directed to the "Whoops" page.

### Desired behavior:

When I attempt to log into Salesforce, I am logged in correctly and directed to the landing page as though I were a user

### Steps to reproduce: (app code and test code)

```js
describe("Salesforce", function() {
          it("opens the login page", function() {
                cy.visit("https://login.salesforce.com/");
           });
           it("Log in to Salesforce", function() { 
                cy.get("#username").type("xxxx@xxxx.com.xxxxxx")
                cy.get("#password").type("xxxxxxxxx")
                cy.get("#Login").click()
           })
 });
```

### Versions

Cypress: 3.3.0

**Comment by jennifer-shehane** [comment] 2019-05-24 07:47
Duplicate of https://github.com/cypress-io/cypress/issues/2367

**Closed by jennifer-shehane** 2019-05-24 07:47 UTC
Labels: topic: whoops 😳
