### ISSUE TITLE
React.lazy component test errors

### ISSUE THREAD

**Issue by reintroducing** [cypress-io/cypress#15116] opened 2021-02-16 17:09 UTC
### Current behavior
I have a simple spec that lazy loads a component (followed the example outlined in the [lazy-load advanced examples](https://github.com/cypress-io/cypress/tree/master/npm/react/cypress/component/advanced/lazy-loaded)) which fails to compile correctly with the following error:
```
The following error originated from your test code, not from Cypress.

  > Automatic publicPath is not supported in this browser
```
I've tried to re-set up the whole environment to mirror, as closely as possible, the example link from above. Of note is that I'm using `cypress-webpack-preprocessor-v5` instead of what is provided in the example as, subsequently, thats what my project is using as well.

If I comment out the `Bar` lazy load on line 3 of `src/Foo.js` and the usage of `<Bar />` on line 8, the test compiles correctly. I've attached a zip file mirroring the whole setup. After downloading, run the following:
* `npm i`
* `npm test`

### Desired behavior
The test should pass.

### Test code to reproduce
See attached zip file.

[cypress-i18n.zip](https://github.com/cypress-io/cypress/files/5990293/cypress-i18n.zip)

### Versions
"cypress": "^6.5.0",
"@cypress/react": "^5.0.0",
"cypress-webpack-preprocessor-v5": "^5.0.0-alpha.1",
"webpack": "^5.22.0",

**Comment by jennifer-shehane** [comment] 2021-02-23 07:43
I can recreate this from the repo provided. https://github.com/cypress-io/cypress/files/5990293/cypress-i18n.zip

This likely is related to webpack 5, since I see this error is somewhat common in there when googling. 

<img width="745" alt="Screen Shot 2021-02-23 at 2 41 20 AM" src="https://user-images.githubusercontent.com/1271364/108814477-db461900-7580-11eb-8cb8-10bfbf7f0857.png">

**Comment by reintroducing** [comment] 2021-02-23 14:37
@jennifer-shehane i believe you are correct, i have seen some other issues mention this as well.

**Comment by Kocal** [comment] 2021-03-01 14:50
Hi :wave: 

After many hours of pain trying to setup `@cypress/vue` 2.0.1 (it seems that event `dev-server:start` is not called), everything is correct but I'm now facing the same issue on some `.css files`:

![image](https://user-images.githubusercontent.com/2103975/109512531-7c166600-7aa4-11eb-995f-9921c4a08127.png)

The error seems to come from [webpack's `AutoPublicPathRuntimeModule`](https://github.com/webpack/webpack/blob/master/lib/runtime/AutoPublicPathRuntimeModule.js#L57). It seems that webpack is not able to guess the publicPath, surely because how Cypress works. 

Maybe #8929 will help. 

Note that I am using Webpack Encore 1.1.1, Webpack 5.19.0 and Cypress 6.5.0.

Thanks!

**Comment by sethomas** [comment] 2021-04-27 19:24
This is no longer an issue with the below deps on webpack 5:
```
"@cypress/code-coverage": "3.9.5",
"@cypress/react": "5.4.0",
"@cypress/webpack-dev-server": "1.1.5",
"cypress": "7.2.0",
```

**Comment by jennifer-shehane** [comment] 2021-04-27 19:36
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-04-27 19:36 UTC
Labels: stage: ready for work, topic: preprocessors :wrench:, type: bug
