### ISSUE TITLE
Cypress returns Parse Error on POST login method in 3.7.0

### ISSUE THREAD

**Issue by uxi187** [cypress-io/cypress#5847] opened 2019-12-02 13:51 UTC
### Current behavior:

After switching to Cypress 3.7.0 making a POST request to a login API endpoint intermittently fails with an unknown "Parse" error and it's impossible to determine why. 

Login request HAR:
[singletest.frankfurt.testcase.cz.zip](https://github.com/cypress-io/cypress/files/3911549/singletest.frankfurt.testcase.cz.zip)

Cypress 3.7.0 when logging in:
![image](https://user-images.githubusercontent.com/20183440/69964273-58b3e280-1512-11ea-942d-0675abe36e1d.png)

### Desired behavior:
It should be working the same as in Cypress 3.4.1 where it is working flawlessly. 

Cypress 3.4.1 when logging in:
![image](https://user-images.githubusercontent.com/20183440/69965058-bac11780-1513-11ea-903f-e68cb18540f1.png)

### Versions

Operating System: Windows 10
Cypress Version: 3.7.0
Browser Version: Google Chrome 78

**Comment by jennifer-shehane** [comment] 2019-12-03 07:19
Hey @uxi187, thanks for opening this issue. I believe this to be a duplicate of https://github.com/cypress-io/cypress/issues/5688, seeing from the har file that there are multiple `Set-Cookie` headers and the same `Parse Error` as mentioned in that issue. I will be closing this as a duplicate.

This was a regression introduced in Cypress 3.6.1. As a workaround today, I suggest downgrading to Cypress 3.4.1.

**Closed by jennifer-shehane** 2019-12-03 07:19 UTC
