### ISSUE TITLE
Max out CPU (100%) after upgrade to v10.0.0

### ISSUE THREAD

**Issue by ignatiusreza** [cypress-io/cypress#22082] opened 2022-06-03 08:27 UTC
### Current behavior

Cypress open max out CPU usage, from htop, we can identify that 2 commands are running multiple processes, each taking 0-3% of CPU.. Below are screenshot for the `bash -c IFS=$' '; for file in` command, the other one are `git log --max-count=1`..

![bash-c](https://user-images.githubusercontent.com/667726/171815862-a80aa9a7-c595-4b92-88a0-7d16bac0e981.png)

### Test code to reproduce

Since it's happening on a private repo, I can't share the link to it.. but, I'll try to see if it can be reproduced on a dummy project..

### Cypress Version

10.0.2

**Comment by lmiller1990** [comment] 2022-06-03 10:41
These commands are how we get the "git status" which is shown on the app landing page, the relevant [code is here](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/GitDataSource.ts) for anyone looking into this.

If you could provide the following, it'd be really useful:

1. `cypress.config` file
2. number of specs perhaps? `ls cypress/e2e | wc -l` or something like this
3. OS?

**Comment by tgriesser** [comment] 2022-06-06 18:51
The root cause of this should be mostly mitigated by https://github.com/cypress-io/cypress/pull/22067, the excessive file watching was causing the command to run `loadBulkGitInfo` too frequently. 

We should also add a guard here to ensure it's only being called once, if any files that are being watched are being changed frequently, we don't want it spawning excessive processes.

**Comment by ignatiusreza** [comment] 2022-06-07 07:14
Thanks for addressing this.. CPU profile is much better on v10.0.3, so I think this issue can be closed.. but, there's still a `to do` label?

**Comment by lmiller1990** [comment] 2022-06-08 06:41
Glad to hear it's better in 10.0.3. I think we can close this one @rockhold?

**Comment by tgriesser** [comment] 2022-06-08 14:18
Glad to hear that it's much better in 10.0.3. The todo is:

> We should also add a guard here to ensure it's only being called once, if any files that are being watched are being changed frequently, we don't want it spawning excessive processes.

We can create a separate issue to track this work if we'd like to close out this issue though

**Comment by lmiller1990** [comment] 2022-06-09 11:01
When you say "only called once", what exactly are you meaning? You mean once per *file change*? If someone is continually editing a file, we want to show that it's been changed N minutes ago, so we'd re-grab the git history every time they save. 

Isn't this what we we are already doing? I looked through the code but I don't see anything that should be double triggering - sorry if I'm completely missing something here? I thought the merged PR was enough to solve the problem - we were watching way too many files, but now we aren't it, should be all good.

**Comment by rockhold** [comment] 2022-06-14 20:22
@tgriesser, I'm going to close this issue out. Can you create a separate issue for the remaining TODO you called out above? The team isn't quite sure what that TODO is, so we thought we'd send it over to you :)

**Closed by rockhold** 2022-06-14 20:22 UTC
Labels: type: bug, type: performance 🏃‍♀️, E2E-core, fast-follows-1, v10.0.0 :bug:, stage: open, pkg/data-context, priority: medium
