### ISSUE TITLE
Cypress ntlm

### ISSUE THREAD

**Issue by Rashminair88** [cypress-io/cypress#20422] opened 2022-03-01 15:07 UTC
### What would you like?

Getting below error:

cy.visit() failed trying to load:

https://<internal site ur>

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: socket hang up

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

### Why is this needed?

Getting error while accessing an internal site

**Comment by davidmunechika** [comment] 2022-03-01 16:31
Cypress does not fully support NTML verification as noted in this issue: https://github.com/cypress-io/cypress/issues/850

Although there is a plugin provided by a third party to use NTML auth within Cypress here: [bjowes/cypress-ntlm-auth](https://github.com/bjowes/cypress-ntlm-auth)

Duplicate of https://github.com/cypress-io/cypress/issues/850

**Closed by davidmunechika** 2022-03-01 16:31 UTC
Labels: type: duplicate, topic: visit

**Comment by Rashminair88** [comment] 2022-03-01 17:17
Yeah I am using [cypress-ntlm-auth](https://github.com/bjowes/cypress-ntlm-auth). 
![image](https://user-images.githubusercontent.com/96204241/156216571-033c57a9-78db-477a-bbdb-aeb59a93ac69.png)
