### ISSUE TITLE
100% performance drop on Github Actions after upgrading 6.8.0 => 7.1.0

### ISSUE THREAD

**Issue by mleszcz** [cypress-io/cypress#16133] opened 2021-04-22 06:48 UTC
Our e2e tests configured on GH Actions noticed 100% performance drop after the upgrade.

I can provide anything you need to fix that. We don't use any features listed in 7.0.0 major release (https://docs.cypress.io/guides/references/migration-guide)

As for now we had to switch back to 6.8.0.

**Comment by jennifer-shehane** [comment] 2021-04-22 12:53
We are aware of a performance regression and are actively working on addressing it. Duplicate of https://github.com/cypress-io/cypress/issues/15853

**Closed by jennifer-shehane** 2021-04-22 12:53 UTC
