### ISSUE TITLE
Display errors from Electron when we run `cypress run`

### ISSUE THREAD

**Issue by dhoko** [cypress-io/cypress#3986] opened 2019-04-17 16:40 UTC
I found this issue while updating my lib, if there is a JS error it fails but without any logs.
I was able to find it via the flag `--headed` + devtools.

![Screenshot from 2019-04-17 18-19-07](https://user-images.githubusercontent.com/713283/56305127-e8518000-613f-11e9-9245-d46d87930c38.png)

It would be great to log this error inside the report we can see inside the output from `$ cypress run`. Maybe there is a flag, but I didn't find one :/

### Current behavior:

≃ it doesn't work cf https://circleci.com/gh/ProtonMail/pt-formgenerator/47?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### Desired behavior:

It doesn't work, look we found a JS error inside your tests:
ex:
``` 
AbortController is undefined
``` 
### Steps to reproduce: (app code and test code)

Add a test with ex Fetch + AbortController, it won't work because Electron 59 doesn't support it.

### Versions

Cypress 3.2.0

**Comment by jennifer-shehane** [comment] 2019-04-18 05:53
Duplicate of https://github.com/cypress-io/cypress/issues/700

**Closed by jennifer-shehane** 2019-04-18 05:53 UTC
