### ISSUE TITLE
Basic auth not working in Chrome 64

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1288] opened 2018-02-09 17:17 UTC
It looks like our favorite friend https://github.com/cypress-io/cypress/issues/573 is back again and is no longer working.

Appears that chrome disabled disabling the blink feature that prevents this from working.

It's about time we permanently fixed this by adding a `cy.visit(url, options)` which will support an `auth` object with username + password.

When applied we'll need to automatically add the Authorization header to requests made to this origin at the network proxy layer.

**Comment by brian-mann** [comment] 2018-02-16 06:16
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).

**Comment by Alexintosh** [comment] 2018-04-04 09:06
This is not working for me on Chrome 64 and 65 with `cypress: 2.1.0`.
Neither this one:

`cy.visit('https://wile:coyote@www.acme.com')`

nor this:

```
cy.visit('https://www.acme.com/', {
  auth: {
    username: 'wile',
    password: 'coyote'
  }
})
```

**Comment by nickshatilo** [comment] 2018-04-20 12:36
@Alexintosh Same for me. 
@brian-mann Could you please provide a link for the documentation regarding the feature?

**Comment by khushboothakkar** [comment] 2018-04-25 06:50
Can anyone please suggest how to bypass or automate an HTTP authentication form for login using cypress?

**Comment by kelly-tock** [comment] 2018-05-31 13:07
this is working for me in `^3.0.0', and following the visit command docs. 

https://docs.cypress.io/api/commands/visit.html#Options

**Comment by saschahauke** [comment] 2018-07-23 09:07
I could not get it to work using a baseUrl so i tried using an env variable and override visit instead wich seems to work fine on chrome and electron.

index.js:
```
switch (configuration) {
  case 'development': {
    config.env.baseURL = 'localhost:4200';
  }
  case 'test': {
    config.env.baseURL = 'https://example.com';
  }
}
```
commands.js:
```
Cypress.Commands.overwrite('visit', (orig, url, options) => {
  orig(Cypress.env('baseURL') + url, {
    auth: {
      username: 'user',
      password: 'pass'
    }
  })
})
```

**Comment by brian-mann** [comment] 2018-07-23 09:09
@saschahauke you need to return `orig` else Cypress will not await the `cy.visit` command to complete.

**Comment by brian-mann** [comment] 2018-07-23 09:10
@jennifer-shehane why did you reopen this issue in April... shouldn't it be closed?

**Comment by jennifer-shehane** [comment] 2018-07-27 22:54
@brian-mann Because there were 3 comments saying they still encountered this issue. Did not want it to be abandoned if there was an issue.

**Comment by RichCrook** [comment] 2018-11-15 03:16
@jennifer-shehane 
This is not working for me on Chrome 70 with cypress: 3.1.1.
I tried on a couple of our sites and no dice :( Unfortunately this is blocking further adoption across older projects.
Are there any work arounds? Thank you!

**Comment by jennifer-shehane** [comment] 2021-01-05 08:35
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2021-01-05 08:35 UTC
Labels: stage: needs investigating, type: bug
