### ISSUE TITLE
appending to a file upon Cypress.on('fail') - 

### ISSUE THREAD

**Issue by shprung** [cypress-io/cypress#9093] opened 2020-11-04 16:42 UTC
my goal is to append to a local log file upon fail. 
my code is
```js
Cypress.on('fail', (error, runnable) => {
  const D=new Date()
  cy.writeFile('fail.log', D.toLocaleDateString()+"|"+error.message+"\n", { flag: 'a+' })
  throw error
})
```

it fails with, the following error in the console:

cypress_runner.js:199686 CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.type()`

The cy command you invoked inside the promise was:

  > `cy.writeFile()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.`

**Comment by jennifer-shehane** [comment] 2020-11-05 11:25
You can't currently call Cypress commands within the Cypress event listeners - since it's outside of the tests. 

You'll have to use something else to write to the files in your projects in this case. 

Duplicate of https://github.com/cypress-io/cypress/issues/6316

**Closed by jennifer-shehane** 2020-11-05 11:25 UTC

**Comment by shprung** [comment] 2020-11-05 16:47
before we just close it and hint me with "You'll have to use something else to write to the files in your projects in this case"; I did look at #6316 but I am getting no where. I know that a spec file is running in the browser so I can not use node fs with `cost fs=require('fs')` so I did add this block of code to cypress/index.js (inside the module.export block)
```
on('task', {
    appendToFailLog(message) {
      const log = fs.createWriteStream('fail.log', {flags: 'a'});
      log.end(message+"\n");
      return null
    }
  })
```
then in my spec file I tried to use it like this:
```
Cypress.on('fail', (error, runnable) => {
  const dt = new Date()
  cy.task('appendToFailLog', dt.toLocaleDateString()+"|"+error.message)
   throw error
})
```
but again, I am calling cy command and it fail with the same error. 
Next, I tried to simple create a function in the index.js :
```
const fs = require('fs')
function appendToFailLog(message) {
  const log = fs.createWriteStream('fail.log', {flags: 'a'});
  log.end(message+"\n");
  return null
}
```
And to simple call it from the on-fail event like that
```
Cypress.on('fail', (error, runnable) => {
  const dt = new Date()
  appendToFailLog(dt.toLocaleDateString()+"|"+error.message)
   throw error
})
```
Again, it didn't work; the referenceError shows `appendToFailLog is not defined`
So, how do I do that? how to i append to an error/fail file upon a 'fail'?

**Comment by jennifer-shehane** [comment] 2020-11-16 08:35
You may want to try asking for advice on how to test this situation from our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team, we have to focus our time on bugs and features in the product.

**Comment by anilpujaraofficial** [comment] 2023-06-21 02:05
!CypressError
 cy.writeFile() must only be invoked from the spec file or support file.

this version => cypress@12.15.0
