### ISSUE TITLE
Disable logging (xhr) and (fetch) requests

### ISSUE THREAD

**Issue by herecydev** [cypress-io/cypress#17815] opened 2021-08-19 20:06 UTC
### What would you like?

Ideally it would be possible to define a global configuration to remove all network logs in the test body, potentially the following option might be helpful:

- Disabled, absolutely no network calls are logged
- Error, if the network calls do not complete successfully they are logged (aborted?)
- All, current behavior

### Why is this needed?

#1184 was the correct solution for cy.server() but this is deprecated and as I understand is not relevant when using intercept.

For the majority of my time with cypress the network logs have not been helpful in testing. As my application increases in complexity the number of these logs are starting to pollute the test body, making it harder to understand what's happening within the test.

The routes however are clearly defined in a separate section, providing clear & concise information that is pertinent to the test in question.

**Comment by phillipoertel** [comment] 2021-08-20 11:03
I'd like to do the same.

**Comment by jennifer-shehane** [comment] 2021-08-20 17:13
Duplicate of https://github.com/cypress-io/cypress/issues/9358

We’ve discussed this a lot, how we want to expose a way to hide/show XHR requests. Right now Webkit support is being prioritized over this work, but we do plan to do it.

**Closed by jennifer-shehane** 2021-08-20 17:13 UTC

**Comment by herecydev** [comment] 2021-08-20 20:06
Apologies @jennifer-shehane didn't come across that one when searching. I'm happy to lend some effort on this one.

**Comment by melsyvolfram** [comment] 2023-12-13 10:16
What works now - in cypress/support/e2e.js add this code:  

```
before(() => {
  cy.intercept({ resourceType: /xhr|fetch/ }, { log: false });
});
```
