### ISSUE TITLE
Cypress does not trigger click event to execute on enter key using vuetify framework

### ISSUE THREAD

**Issue by TadasMil** [cypress-io/cypress#14628] opened 2021-01-19 10:24 UTC
Cypress version:  "cypress": "^6.2.1",

**Current behavior**
Button `onClick` event is not triggered

**Desired behavior**
Button `onClick` event is triggered

Hello, I am testing my application and I'm trying to invoke button click with enter keyword:
```js
<v-btn
    class="submit-button"
    block
    color="primary"
    @click="login"
  >
    Log In
</v-btn>

login() {
  console.log("clicked")
}

it('Trigger button click on enter keyword pressed', () => {
   cy.get('.submit-button').focus().type('{enter}');
});
```

Right now the button is being CLICKED with enter key, but the actual `onClick` event is not firing.

I haven't found any issues related to vuetify and cypress with invoking button click event on enter key.

Any suggestions?

I'm using vuetify framework and v-btn component.

**Comment by jennifer-shehane** [comment] 2021-01-20 08:30
Duplicate of https://github.com/cypress-io/cypress/issues/8267

**Closed by jennifer-shehane** 2021-01-20 08:30 UTC
