### ISSUE TITLE
Process Profiler Doesn't Work With cypress run

### ISSUE THREAD

**Issue by lots0logs** [cypress-io/cypress#6453] opened 2020-02-13 21:45 UTC
### Current behavior:

Enabling the new process profiler doesn't work with `cypress run`. The profiler is not shown. It works fine with `cypress open`

### Desired behavior:

There should be a way to use the process profiler (or at least access its data) while using `cypress run`

### Test code to reproduce

N/A

### Versions

4.8.0

**Comment by flotwig** [comment] 2020-02-13 21:58
@lots0logs The process profiler is supposed to log out process information to stderr at an interval when `DEBUG` is set to `cypress:server:util:process_profiler`. Is this not working for you?

**Comment by lots0logs** [comment] 2020-02-14 02:50
It does not work for `cypress run` however it does work for `cypress open`. Another user confirmed the issue on Gitter earlier today.

**Comment by jennifer-shehane** [comment] 2020-02-14 09:09
@lots0logs Are you able to see any other specific DEBUG logs within Cypress? Like if you do `DEBUG=cypress:server*` does that log anything? May be duplicate of https://github.com/cypress-io/cypress/issues/5051

**Comment by lots0logs** [comment] 2020-02-14 17:59
No, no debug requests are logged for `cypress run` when the spec reporter is enabled.

**Comment by jennifer-shehane** [comment] 2020-02-18 04:16
@lots0logs Can you explain what you mean by 

>when the spec reporter is enabled

What spec reporter do you have enabled? How did you enable it?

**Comment by lots0logs** [comment] 2020-02-18 22:53
Its just the default reporter that mocha has I think. Maybe I am confusing it with something else. Here's the config I am using:

```
 "reporter":                   "cypress-multi-reporters",
    "reporterOptions":            {
        "mochaJunitReporterReporterOptions": {
            "mochaFile": "tests/cypress/results/junit/[hash].xml",
            "overwrite": false
        },
        "mochawesomeReporterOptions":        {
            "html":      false,
            "json":      true,
            "overwrite": false,
            "reportDir": "tests/cypress/results/mochawesome"
        },
        "reportDir":                         "tests/cypress/results",
        "reporterEnabled":                   "mocha-junit-reporter, mochawesome"
```

**Comment by lots0logs** [comment] 2020-02-25 21:38
@jennifer-shehane *bump*

**Comment by lots0logs** [comment] 2020-06-11 01:29
@jennifer-shehane @flotwig 

![bump](https://user-images.githubusercontent.com/4675662/84334876-10c4e680-ab59-11ea-80e4-7234c586607d.gif)

**Comment by flotwig** [comment] 2020-07-07 14:44
It sounds like somehow the reporter configuration is causing the debug `stderr` to be discarded.

**Comment by lots0logs** [comment] 2020-07-07 18:06
@jennifer-shehane I'm running it locally on Linux.

**Comment by jennifer-shehane** [comment] 2020-07-08 14:57
I ran with the given reporter configuration, unless there's more configuration outside of that I'm not aware of.

**Comment by tsubik** [comment] 2020-07-14 11:03
I have the same problem, only `DEBUG=cypress:cli:*` seems to filter properly. I cannot filter anything else except displaying all `cypress:*` logs. I'm on 5.4.44-1-MANJARO Linux.

**Comment by jennifer-shehane** [comment] 2020-10-20 10:50
Can any of y'all verify that you are able to set environment variables on the system? Sometimes there are permissions issues apparently where this is not allowed, but I think we've only seen this in Windows. 

[Instructions on setting and viewing env vars](https://on.cypress.io/proxy-configuration#View-unset-and-set-environment-variables)

**Comment by jennifer-shehane** [comment] 2021-02-22 16:11
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-02-22 16:11 UTC
Labels: cli, stage: needs information

**Comment by kanteankit** [comment] 2021-07-15 09:22
I am running Cypress v7.7 on a Ubuntu 20.04 system and running the following command
```
DEBUG=cypress:server:util:process_profiler ./node_modules/.bin/cypress run
```

No logs are printed. 

![Screenshot from 2021-07-15 14-46-09](https://user-images.githubusercontent.com/34302506/125763728-06ac417e-62a7-4e66-aeec-1aa879361d98.png)

Here's an image showing that DEBUG env variable is set in the terminal.
![Screenshot from 2021-07-15 14-51-48](https://user-images.githubusercontent.com/34302506/125764060-528d16da-62ea-476e-a9c4-e5839c6da67b.png)

**Comment by lephuongbg** [comment] 2022-02-03 09:25
@jennifer-shehane Still same with 9.4. `DEBUG=cypress:server:util:process_profiler` does not work. `DEBUG=cypress:server:*` does not work. But `DEBUG=cypress:*` does print everything, including `cypress:server:...` lines.

**Comment by gedkirkham** [comment] 2022-03-01 09:14
I resolved this issue by running the below command.

`export DEBUG=cypress*` rather than `DEBUG=cypress*`
