### ISSUE TITLE
Parallel runs seem to be disabled when you reach the test run limit

### ISSUE THREAD

**Issue by beaugunderson** [cypress-io/cypress#5086] opened 2019-09-05 03:47 UTC
Super disappointed at this decision, we're at the biggest plan and trying to meet a deadline and suddenly our test runs take 8x longer with ZERO path to fix it without going through support to upgrade to a "custom" plan, whatever that is.

**Comment by jennifer-shehane** [comment] 2019-09-05 15:15
Hey @beaugunderson, currently the action to be taken is to click the "Upgrade" through your Billing and Usage page then click 'Contact Us' under the Custom Plan.

<img width="895" alt="Screen Shot 2019-09-05 at 10 26 34 AM copy" src="https://user-images.githubusercontent.com/1271364/64354976-6539a500-cfce-11e9-9ab0-f10eea901515.png">

Filling out this form will send a message directly to our billing team. 

<img width="609" alt="Screen Shot 2019-09-05 at 10 26 49 AM" src="https://user-images.githubusercontent.com/1271364/64354991-6a96ef80-cfce-11e9-9510-dc496797f622.png">


I understand this isn't ideal since it does require our team's response. I've noted your feedback on our Dashboard's product board. I'll be closing this issue since this is not a bug or feature request for our main Cypress test runner. 

Thanks for your feedback.

**Closed by jennifer-shehane** 2019-09-05 15:15 UTC
