### ISSUE TITLE
blank page during visit

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6191] opened 2020-01-17 21:38 UTC
Cypress v3.8.2 on MAc

Spec

```js
describe('QA Admin', () => {
	it('Loads the auth page, not an empty frame', () => {
		cy.visit('https://redacted.alumniq.com/admin/index.cfm/login');
		cy.get('input');
	});
});
```

Page is blank

Notice the iframed document only has `<head>...</head>` element, no `<body>` at all.

See the following in the terminal (I have added a few line breaks to break the single string)

```
[11854:0117/162940.246364:ERROR:CONSOLE(0)] "Blocked script execution in 'data:text/html;charset=UTF-8,%3Chead%3E%20%3Cscript%20type='text/javascript'%3E%20document.domain%20=%20'alumniq.com';%20var%20Cypress%20=%20window.Cypress%20=%20parent.Cypress;
%20if%20
(!Cypress)%20%7B%20throw%20new%20Error('Something%20went%20terribly%20wrong%20and%20we%20cannot%20proceed.%20We%20expected%20to%20find%20the%20global%20Cypress
%20in%20the%20parent%20window%20but%20it%20is%20missing!.%20This%20should
%20never%20happen%20and%20likely%20is%20a%20bug.%20Please%20open%20an%20issue!');%20%7D;%20Cypress.action('app:window:before:load',%20window);
%20%3C/script%3E%20%3C/head%3E' because the document's frame is sandboxed 
and the 'allow-scripts' permission is not set.", source: data:text/html;charset=UTF-8,%3Chead%3E%20%3Cscript%20type='text/javascript'%3E%20document.domain%20=%20'
alumniq.com';%20var%20Cypress%20=%20window.Cypress%20=%20parent.Cypress;
%20if%20(!Cypress)%20%7B%20throw%20new%20Error('Something%20went%20terribly%20wrong%20and%20we%20cannot%20proceed.%20We%20expected%20to%20find%20the%20
global%20Cypress%20in%20the%20parent%20window%20but%20it%20is%20missing!.
%20This%20should%20never%20happen%20and%20likely%20is%20a%20bug.%20Please%
20open%20an%20issue!');%20%7D;%20Cypress.action('app:window:before:load',
%20window);%20%3C/script%3E%20%3C/head%3E (0)
```

Relevant error from the above text

```
Blocked script execution in 'data:text/html... '
because the document's frame is sandboxed  and the 'allow-scripts' permission 
is not set.", source: data:text/html;charset=UTF-...
```

**Comment by bahmutov** [comment] 2020-01-17 22:00
After playing some more, see this error in the DevTools console

<img width="1199" alt="Screen Shot 2020-01-17 at 4 55 54 PM" src="https://user-images.githubusercontent.com/2212006/72649141-d4df7980-394a-11ea-89e1-67d688cec5e2.png">

**Comment by bahmutov** [comment] 2020-01-17 22:09
<img width="868" alt="Screen Shot 2020-01-17 at 5 06 31 PM" src="https://user-images.githubusercontent.com/2212006/72649577-10c70e80-394c-11ea-912a-8eb2064e013f.png">

**Comment by flotwig** [comment] 2020-01-17 22:17
do they embed an iframe with the `sandbox` attribute? if so this sounds like another thing that #5273 could help with

**Comment by atuttle** [comment] 2020-01-17 22:26
This ticket originated with my request for help on twitter/in gitter... @flotwig can you clarify your question? I don't follow. The page that we're attempting to load doesn't include any iframes (some parts of our application do, but we haven't gotten to writing tests for any of those screens yet.)

**Comment by bahmutov** [comment] 2020-01-18 02:55
no, @flotwig I could not any iframes there - I think this message comes from aut iframe

**Comment by atuttle** [comment] 2020-01-22 13:39
Is there anything I can do to assist in debugging?

**Comment by atuttle** [comment] 2020-01-24 20:50
I'll be offline for a week, starting tonight. If you need any more information or if you think making some changes could help, please contact my colleagues at helpdesk@alumniq.com

**Comment by villelahdenvuo** [comment] 2020-08-11 12:53
This also happens to me randomly and I have to close Electron and restart the suite.

**Comment by jennifer-shehane** [comment] 2020-08-12 07:59
I'm not able to recreate this issue with the code provided anymore. 

<img width="523" alt="Screen Shot 2020-08-12 at 2 28 33 PM" src="https://user-images.githubusercontent.com/1271364/89990287-24e7aa00-dca8-11ea-92c4-ef60599cf84b.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-12 07:59 UTC
Labels: stage: needs investigating

**Comment by villelahdenvuo** [comment] 2020-08-12 09:16
In case anyone finds this issue, in my case the issue was caused by the experimentalFetchPolyfill setting. It worked fine in the beginning and I replaced my custom polyfill solution, however it started failing in a way that the first cy.visit command would work, but after that I would just get a blank screen and if I tried to retry it would get stuck on loading tests.

After I disabled that and installed a third party polyfill plugin: https://github.com/rckeller/cypress-unfetch it started working again.
