### ISSUE TITLE
localStorage is not being resolved sometimes

### ISSUE THREAD

**Issue by TrejGun** [cypress-io/cypress#3905] opened 2019-04-07 09:08 UTC
when i'm using `localStorage.getItem` in `before` function to get some user data from storage sometimes (randomly) it is not being resolved by test engine so it spews error ```Uncaught TypeError: Cannot read property 'getItem' of null```

to fix this use `window.localStorage.getItem`

i can't provide steps to reproduce or other useful info so i believe this bug will be closed soon but i'm posting this workaround for guys who has the same issue so they can google for answer

**Comment by jennifer-shehane** [comment] 2019-04-10 06:15
Can you provide the exact test code that you write within your `before` and `it` that sometimes fails?

**Comment by TrejGun** [comment] 2019-04-10 10:38
I dont think it is usefull to copy paste here half of our react app
long story short we have <UserProvider> which wraps whole app, and it calls 
```
const user = window.localStorage.getItem("user");
```
in componentDidMount

**Comment by TrejGun** [comment] 2019-04-10 10:44
oh yes i forgot to mention this is only happens in headless run

**Comment by jennifer-shehane** [comment] 2019-04-11 08:17
Hey @TrejGun, we do not need your application code - just wanted to see the code from your test file, the file that contains the cypress commands. Thanks!

**Comment by TrejGun** [comment] 2019-04-12 15:10
test
``` js
  beforeEach(() => {
    cy.loginMocked();
  });
```

command
```js
Cypress.Commands.add('loginMocked', (type = 'admin') => {
  localStorage.setItem(AUTH_KEY, JSON.stringify(auths[type])); // this is working each time
  cy.visit('/locations');
});
```
and as ia said whocle application is wrapped in reacts Provider

**Comment by jennifer-shehane** [comment] 2019-04-24 13:07
And where is the `localStorage.getItem` being called that you said is throwing the error in the context of the tests above?

**Comment by TrejGun** [comment] 2019-04-25 07:09
```js
import React, {useState, useEffect} from "react";
import ReactDOM from "react-dom";
import {Switch, Route} from "react-router";

export default App => {
  ReactDOM.hydrate(
     <UserProvider>
       <Switch>
         <Route path="/" component={Landing} exact />
      </Switch>
    </UserProvider>,
    document.getElementById("app"),
  );
};

function UserProvider({children}) {
  const [user, setUser] = useState(defaultUser);

  useEffect(() => {
    const auth = localStorage.getItem(AUTH_KEY); // <- this one fails sometimes
    setUser(auth ? JSON.parse(auth) : null);
  }, []);

  return children;
}
```

**Comment by jennifer-shehane** [comment] 2019-04-25 07:36
Unfortunately this is impossible to look into without a reproducible example provided.

I do think it's a bit strange that you are calling to set the local storage before event calling `cy.visit()` however - maybe you are visiting the website somewhere before? 

Either way, we'll have to close the issue if we cannot reproduce the error. 

You may also want to ask around for help in our [community chat](https://gitter.im/cypress-io/cypress).

**Comment by jennifer-shehane** [comment] 2019-05-30 09:04
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-05-30 09:04 UTC
Labels: stage: needs information, topic: localStorage

**Comment by Uzlopak** [comment] 2019-08-15 16:34
@TrejGun 
See #2722

**Comment by TrejGun** [comment] 2019-09-10 13:16
@Uzlopak the problem is i'm doing this in app, not in tests. 
App knows nothing about `cy.window()` and it should not
Probably I should mock my global object aka `window` to use `cy.window()`. but when i use `window.localStorage` it works, so i dont need to mock it
