### ISSUE TITLE
WebGL Context Loss

### ISSUE THREAD

**Issue by ashtonsix** [cypress-io/cypress#20165] opened 2022-02-12 22:28 UTC
### Current behavior

This issue pertains to a WebGL2 library I am developing, it is a browser-only library.

When creating 7 or more webgl buffers within Chrome 90, Chrome 96, Chrome 98 or Edge 98 a webgl context loss occurs if the browser is being controlled by Cypress. The context loss does not occur in Firefox 96 or any of the previously mentioned browsers when they're launched normally (ie, not via Cypress).

### Desired behavior

Cypress runs the provided code without a context loss occuring.

### Test code to reproduce

```js
describe('webgl', () => {
  it('works', async () => {
    let canvas = document.createElement('canvas')
    let gl = canvas.getContext('webgl2')

    function createBuffer() {
      let buf = gl.createBuffer()
      let byteLength = 16
      gl.bindBuffer(gl.ARRAY_BUFFER, buf)
      gl.bufferData(gl.ARRAY_BUFFER, byteLength, gl.DYNAMIC_COPY)
      gl.bufferSubData(gl.ARRAY_BUFFER, 0, new Uint32Array([0, 1, 2, 3]))
      gl.bindBuffer(gl.ARRAY_BUFFER, null)
      return buf
    }

    async function waitForIdle() {
      let sync = gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE, 0)
      gl.flush()
      await new Promise((resolve) => {
        function test() {
          if (gl.clientWaitSync(sync, 0, 0) === gl.TIMEOUT_EXPIRED) setTimeout(test, 10)
          else resolve()
        }
        test()
      })
      gl.deleteSync(sync)
    }

    async function main() {
      for (let i = 0; i < 10; i++) {
        createBuffer()
        await waitForIdle()
        console.log(i, gl.isContextLost())
      }
    }

    await main()
  })
})
```

`console.log` output:

```txt
0 false
1 false
2 false
3 false
4 false
5 false
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
6 true
```

The context loss always occurs on my computer, and always in the same place. However it should be noted that different driver software, graphics cards, OS combinations, etc, may cause differences in behaviour.

### Cypress Version

9.4.1 (on Pop!_OS 21.10)

### Other

MDN provides these reasons why a WebGL context loss may occur (https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/isContextLost):

- Two or more pages are using the GPU, but together place too high a demand on the GPU, so the browser tells the two contexts that they've lost the connection, then selects one of the two to restore access for.
- The user's computer has multiple graphics processors (such as a laptop with both mobile and desktop class GPUs, the former used primarily when on battery power), and the user or system decides to switch GPUs. In this case, all contexts are lost, then restored after switching GPUs.
- Another page running in the user's browser performs an operation using the GPU that takes too long, causing the browser to decide to reset the GPU in order to break the stall. This would cause every WebGL context to be lost throughout the entire browser.
- The user updates their graphics driver on an operating system that allows graphics drivers to be updated without restarting the system.

Please note that when a context loss occurs it may not appear in the console for quite some time, leading one to try debugging the wrong parts of their code, or into believing bad code is working properly. Use the `waitForIdle` function from my test code to force context loss messages to appear.

My "unmasked renderer" (as reported by https://webglreport.com/?v=2) is:

ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (WHL GT2), OpenGL 4.6 (Core Profile) Mesa 21.2.2)

**Comment by BlueWinds** [comment] 2022-02-16 19:53
Very interesting. I'm able to reproduce the issue on Chrome 98, but not Chromium 98, which is the first time I've ever seen these diverge in behavior in Cypress. The example also fails to run in Chrome-beta 99 - `canvas.getContext('webgl2')` returns null.

With that said, I have no idea where to even start debugging this. Since this occurs in open mode, it's not related to our video recorder code, and as far as I can tell, we don't have code anywhere in cypress dealing with WebGL at all.

> Two or more pages are using the GPU, but together place too high a demand on the GPU, so the browser tells the two contexts that they've lost the connection, then selects one of the two to restore access for.

seems the most likely culprit. Cypress uses several iframes for running tests - it might be worth investigating if you run into similar issues with your code when running it in nested iframes.

**Comment by sainthkh** [comment] 2022-03-28 08:05
Sorry for the late reply. 

Is it still happening with 9.5.2 with Chrome 99? 

I failed to reproduce the problem with them on Ubuntu 20.04.

**Comment by ashtonsix** [comment] 2022-03-28 15:23
@sainthkh No worries! This issue isn't an issue for me anymore, since I'm no longer using Cypress in my project (switched to Karma). Thanks for taking a look at this regardless.

I haven't made an attempt to reproduce the issue with v9.5.2 and Chrome 99, but it's probably fine to close this issue if you've given it a test and found everything to be trouble-free with the latest software?

**Comment by sainthkh** [comment] 2022-03-29 06:56
Thank you for the quick response. Then, I'll close this issue for now.

**Closed by sainthkh** 2022-03-29 06:56 UTC
Labels: stage: awaiting response
