### ISSUE TITLE
cy.screenshot fails (after first time) with "e.indexOf is not a function" message

### ISSUE THREAD

**Issue by bethschrag** [cypress-io/cypress#8918] opened 2020-10-21 20:47 UTC
I have a simple Cypress test that logs into a website, asserts the header of the first page, takes a screenshot (works), logs out of that website, asserts the button text, and takes another screenshot (fails).
This was working previously on a different machine in April 2020.
I just got it back out to run again and can't get past this error.
```js
import { loginWithUI } from '../support'
import { logoutWithUI } from '../support'

Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from failing the test when the app
  // has an uncaught exception
  return false;
});

describe('The Login and Out Process', function() {
  it('successfully logs a user in and out using the UI', function() {
    // ======== LOG IN ========
    loginWithUI();
    // confirm url and page are as expected
    cy.url().should('include', '/home');
    cy.get('#block-gettingstarted').within(() => {
      cy.get('h2').should('contain', 'Getting Started');
    });
    cy.screenshot('getting_started_screen');    // <===THIS WORKS

    // ======== LOG OUT ========
    logoutWithUI();
    // confirm url and page are as expected
    cy.url().should('eq', Cypress.config().baseUrl);
    cy.get('#edit-submit').should('contain', 'Log in');
    cy.screenshot('login_screen_after_logout');   //  <===THIS FAILS
  });
});
```
In the Cypress window I get a green line for the assertion:
```expected <input#edit-submit.button.js-form-submit.form-submit> to contain Log in```
Then a light blue line with a spinning circle of dots that never stops:
```  -screenshot login_screen_after_logout```
Then a red line that says (NOTE that the screenshot file is saved in the screenshots directory):
```  -screenshot login_screen_after_logout```
Then in red:
``` 
   TypeError
   e.indexOf is not a function
```
Then the stack trace:
```
   at S.fn.init.S.fn.load (https://qa-portal-therapyed.breaktech.org/sites/default/files/js/optimized/js_dxIVcwvQ00owLGoUGPTfRYXU-T5rnj8Xi0cXfb3Kn58.9_aliU8dGd2tb6OSsuzixeV4y_faTqgFtohetphbbj0.js?v=3.5.1:2:84832)
    at Object.attach (https://qa-portal-therapyed.breaktech.org/sites/default/files/js/optimized/js_JD63hhl4-0283yRr3jJhw3fpsDci5Qrb6dPhT4ZR88o.ESB2kks586oQeqDZp9yGOJoSm5jyEZtUf5f5shf0XCk.js?v=8.9.2:1:102)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/sites/default/files/js/optimized/js_V1oRQ-kJlXBZaEklOtPUe_1t8-l0RS94HJ3gsqxKikc.gHquyVj1l68z94PPTo-qAcjHiCACliHXCfsrM3TyWWk.js?v=8.9.2:1:280)
        at Array.forEach (<anonymous>)
    at Object.t.attachBehaviors (https://qa-portal-therapyed.breaktech.org/sites/default/files/js/optimized/js_V1oRQ-kJlXBZaEklOtPUe_1t8-l0RS94HJ3gsqxKikc.gHquyVj1l68z94PPTo-qAcjHiCACliHXCfsrM3TyWWk.js?v=8.9.2:1:215)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/sites/default/files/js/optimized/js_KRjtvzl6UujB23-j_sF6dqOcbqg2z8ej98A8RU9bGsg.4NOli19MseNXEuWy8zlCmRBdiKdHghRfJUu9gqP_dSQ.js?v=8.9.2:2:147)
    at HTMLDocument.t (https://qa-portal-therapyed.breaktech.org/sites/default/files/js/optimized/js_KRjtvzl6UujB23-j_sF6dqOcbqg2z8ej98A8RU9bGsg.4NOli19MseNXEuWy8zlCmRBdiKdHghRfJUu9gqP_dSQ.js?v=8.9.2:2:26)
From previous event:
    at takeScreenshot (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:160133:14)
    at Context.screenshot (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:160225:15)
    at Context.<anonymous> (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170550:22)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:169974:16)
From previous event:
    at runCommand (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:169953:9)
    at next (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170099:15)
    at next (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170077:17)
From previous event:
    at next (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170099:35)
From previous event:
    at Promise.catch.err.name (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170140:38)
From previous event:
    at run (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170133:22)
    at $Cy.cy.<computed> [as visit] (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170590:12)
    at Context.runnable.fn (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:170814:22)
    at callFn (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:104982:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:104969:8)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:176413:29)
From previous event:
    at Object.onRunnableRun (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:176401:18)
    at $Cypress.action (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:166950:29)
    at Test.Runnable.run (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:174787:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:105641:11)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:105767:13)
    at next (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:105550:15)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:105560:8)
    at next (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:105462:15)
    at <unknown> (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:105528:6)
    at timeslice (https://qa-portal-therapyed.breaktech.org/__cypress/runner/cypress_runner.js:99454:28)
```

I am using:
Cypress: 5.4.0.481307 
MacOS: 10.15.7

This happens in UI and headless mode on Chrome (86.0.4240.80) and Firefox(81.0.1).

Everything I have read about indexOf messages says that it is a string error but I still get the same error when I leave the filename out of the screenshot call. 

I see other similar issues out there but not exactly the same and most are from a while ago.
Does anyone have a solution?

**Comment by jennifer-shehane** [comment] 2020-10-22 07:25
This error looks like it's being thrown from within your application - looking at the locations listed in the stacktrace. Have you tried clicking into the stacktrace locations to see where this is being thrown in that code?

Outside of this, we'd need a reproducible example that we can run on our machines. The example provided can't be run since it's missing a url + some custom commands. Without this we won't be able to track it down from our side.

**Comment by jennifer-shehane** [comment] 2021-06-11 17:11
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-06-11 17:11 UTC
Labels: stage: awaiting response
