### ISSUE TITLE
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)

### ISSUE THREAD

**Issue by ederperez09** [cypress-io/cypress#8108] opened 2020-07-28 14:57 UTC
### Current behavior:

I tried to open Cypress to run test cases but in the terminal, it says `Failed to connect to Chrome, retrying in 1 second (attempt 18/62)` and I cannot see preview in the chrome.

### Desired behavior:

I expect the Cypress runs successfully.

### Test code to reproduce

- Cypress.json
```
{
  "baseUrl": "http://localhost:8051",
  "video": false
}
```

### Versions

Cypress: 4.11.0
Chrome: 84
OS X: Mojave
Node version: v10.21.0

### Additional information

I also tried [this approach](https://github.com/cypress-io/cypress/issues/6540#issuecomment-641087834) but it doesn't work for me.

**Comment by liyuindeed** [comment] 2020-07-28 23:38
Intermittently facing this issue as well:

- For me, It is always happening start from the 2nd test Cucumber BDD feature file.
- Chrome: Version 81.0.4044.129 (Official Build) (64-bit)
- Dependencies:

"cypress": "^4.11.0",
"cypress-cucumber-preprocessor": "^2.5.4",
"cypress-image-snapshot": "^3.1.1",
"cypress-wait-until": "^1.7.1",
"multiple-cucumber-html-reporter": "^1.17.0"
`Timed out waiting for the browser to connect. Retrying...
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
Failed to connect to Chrome, retrying in 1 second (attempt 20/62)
Failed to connect to Chrome, retrying in 1 second (attempt 21/62)
Failed to connect to Chrome, retrying in 1 second (attempt 22/62)
Failed to connect to Chrome, retrying in 1 second (attempt 23/62)
Failed to connect to Chrome, retrying in 1 second (attempt 24/62)
Failed to connect to Chrome, retrying in 1 second (attempt 25/62)
Failed to connect to Chrome, retrying in 1 second (attempt 26/62)
Failed to connect to Chrome, retrying in 1 second (attempt 27/62)
Failed to connect to Chrome, retrying in 1 second (attempt 28/62)
Failed to connect to Chrome, retrying in 1 second (attempt 29/62)
Failed to connect to Chrome, retrying in 1 second (attempt 30/62)
Failed to connect to Chrome, retrying in 1 second (attempt 31/62)
Failed to connect to Chrome, retrying in 1 second (attempt 32/62)
Failed to connect to Chrome, retrying in 1 second (attempt 33/62)
Failed to connect to Chrome, retrying in 1 second (attempt 34/62)
Failed to connect to Chrome, retrying in 1 second (attempt 35/62)
Failed to connect to Chrome, retrying in 1 second (attempt 36/62)
Failed to connect to Chrome, retrying in 1 second (attempt 37/62)
Failed to connect to Chrome, retrying in 1 second (attempt 38/62)
Failed to connect to Chrome, retrying in 1 second (attempt 39/62)
Failed to connect to Chrome, retrying in 1 second (attempt 40/62)
Failed to connect to Chrome, retrying in 1 second (attempt 41/62)
Failed to connect to Chrome, retrying in 1 second (attempt 42/62)
Failed to connect to Chrome, retrying in 1 second (attempt 43/62)
Failed to connect to Chrome, retrying in 1 second (attempt 44/62)
Failed to connect to Chrome, retrying in 1 second (attempt 45/62)
Failed to connect to Chrome, retrying in 1 second (attempt 46/62)
Failed to connect to Chrome, retrying in 1 second (attempt 47/62)
Failed to connect to Chrome, retrying in 1 second (attempt 48/62)
Failed to connect to Chrome, retrying in 1 second (attempt 49/62)
Failed to connect to Chrome, retrying in 1 second (attempt 50/62)
Failed to connect to Chrome, retrying in 1 second (attempt 51/62)
Failed to connect to Chrome, retrying in 1 second (attempt 52/62)
Failed to connect to Chrome, retrying in 1 second (attempt 53/62)
Failed to connect to Chrome, retrying in 1 second (attempt 54/62)
Failed to connect to Chrome, retrying in 1 second (attempt 55/62)
Failed to connect to Chrome, retrying in 1 second (attempt 56/62)
Failed to connect to Chrome, retrying in 1 second (attempt 57/62)
Failed to connect to Chrome, retrying in 1 second (attempt 58/62)
Failed to connect to Chrome, retrying in 1 second (attempt 59/62)
Failed to connect to Chrome, retrying in 1 second (attempt 60/62)
Failed to connect to Chrome, retrying in 1 second (attempt 61/62)
Failed to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 49379.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:49379
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)`

**Comment by jennifer-shehane** [comment] 2020-07-29 11:15
Duplicate of #6540

**Closed by jennifer-shehane** 2020-07-29 11:15 UTC

**Comment by wnbupt** [comment] 2020-08-12 15:44
> ### Current behavior:
> I tried to open Cypress to run test cases but in the terminal, it says `Failed to connect to Chrome, retrying in 1 second (attempt 18/62)` and I cannot see preview in the chrome.
> 
> ### Desired behavior:
> I expect the Cypress runs successfully.
> 
> ### Test code to reproduce
> * Cypress.json
> 
> ```
> {
>   "baseUrl": "http://localhost:8051",
>   "video": false
> }
> ```
> 
> ### Versions
> Cypress: 4.11.0
> Chrome: 84
> OS X: Mojave
> Node version: v10.21.0

Me too.

### Versions
Cypress: 4.12.1
Chrome: 84.0.4147.105(latest)
OS X: 10.14.6 Mojave
Node version: v8.14.0

I also tried [issue  #6540 ](https://github.com/cypress-io/cypress/issues/6540#issuecomment-641087834) but it doesn't work for me.

**Comment by suchitrachavan** [comment] 2020-12-16 23:28
Hi I am also facing same issue with cypress

**Comment by phileinSophos** [comment] 2021-02-27 04:02
I was facing this same issue on Windows machine, wherein I was getting 

> Failed to connect to Chrome, retrying in 1 second (attempt 18/62)

I was able to resolve it by editing the package.json file, and modifying the "script" field to have following value 
```
"scripts": {
    "test": "node_modules\\.bin\\cypress run --headed --browser chrome",
    "runtests": "npm run test -- "
  }
```

**Comment by UtsavAnchanto** [comment] 2021-10-06 10:00
I modified the hosts file in /private/etc and specified:
127.0.0.1 localhost

This and nothing else seemed to work for me

**Comment by aharveysu** [comment] 2022-07-25 21:52
I am also having the same issue. I went from 10.3.0 cypress to 10.3.1 because I could not do a simple login test. Now I can't even connect to Chrome and the test runner took longer to load. The below are the tests I wrote and I have tried 20 different ways to login. I am also using this test site to learn cyprses with. https://opensource-demo.orangehrmlive.com/index.php/auth/login 


describe('Nav to My Store Page', () => {
  it('passes', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/index.php/auth/login')
  })
})

describe('Enter Username', () => {
  it('passes', () => {
    cy.get('[id="txtUsername"]').click({force: true}).type("Admin")
  })
})

describe('Enter Password', () => {
  it('passes', () => {
    cy.get('[id="txtPassword"]').type("admin123")
  })
})

describe('Hit login btn and login', () => {
  it('passes', () => {
    cy.get('#btnLogin').click().debug()
    debugger
  })
})

describe('Landed on the Home page after Login', () => {
  it('passes', () => {
    cy.url().contains('/dashboard')
  })
})
