### ISSUE TITLE
Headed tests stop running if I focus on another window on my computer

### ISSUE THREAD

**Issue by camseda** [cypress-io/cypress#28772] opened 2024-01-22 18:39 UTC
### Current behavior

On the newer versions of Cypress ( 13.6.0 ) I'm currently unable to run tests headed in the background locally. If I open another window to work on something else while I'm letting some tests run, the tests stop running. I thought it could be related to this release: https://github.com/cypress-io/cypress/pull/28334

### Desired behavior

Tests should be continuing to run even if I have another window open.

### Test code to reproduce

I believe any test that is running locally while on ^13.6.1 will stop running if you focus on another window. Not specific to a test. I found that downgrading to Cypress 13.5.0 resolved this issue for me.

### Cypress Version

13.6.1

### Node version

16.15.1

### Operating System

Mac OS 14.2.1

**Comment by jennifer-shehane** [comment] 2024-01-22 18:57
Duplicate of https://github.com/cypress-io/cypress/issues/28392

**Closed as completed by jennifer-shehane** 2024-01-22 18:57 UTC
