### ISSUE TITLE
log browser errors to console

### ISSUE THREAD

**Issue by Pomax** [cypress-io/cypress#4169] opened 2019-05-09 15:55 UTC
Running Cypress in CI context, we just spent an entire day figuring out why a single test kept refusing to pass only to discover that after adding in code that breaks CI but lets us debug what's going on shows that one test case had a CORS error in the browser.

That error should be logged to the console. _Any_ error should be logged to the console (since people will be using cypress for continuous integration testing: the GUI is super nice for local dev work, but does not exist during CI/CD, and should _not_ be relied on existing).

A tool that only works when nothing is wrong is not a good tool =)

**Comment by flotwig** [comment] 2019-05-09 19:15
Related issue (for logging `console.X` output to console): #700 

I made a plugin in the meantime that will log all browser messages and `console.log`s to stdout. It only works for Chrome, not Electron currently: https://github.com/flotwig/cypress-log-to-output

**Comment by Pomax** [comment] 2019-05-10 15:48
Does that include CORS, CSP, and Network errors? (because as far as I know, those use a very different error reporting system even though it might look like standard console logging)

**Comment by flotwig** [comment] 2019-05-10 15:52
@Pomax Yes, it hooks into both error reporting systems.

The CORS, CSP, etc. errors use the [`Log` interface](https://chromedevtools.github.io/devtools-protocol/tot/Log) of the Chrome Debugger Protocol, and errors from user code emit the [`Runtime.consoleAPICalled` event](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#event-consoleAPICalled). 

I also included an interface to filter logs based on, among other things, the origin of the log message.

**Comment by jennifer-shehane** [comment] 2019-05-22 06:52
Duplicate of https://github.com/cypress-io/cypress/issues/700

**Closed by jennifer-shehane** 2019-05-22 06:52 UTC
