### ISSUE TITLE
Inconsistent behaviour of cy.visit

### ISSUE THREAD

**Issue by MadMatt25** [cypress-io/cypress#1687] opened 2018-05-08 13:15 UTC
### Current behavior: 
I stumbled upon this while writing some tests. In some of my tests, I use cy.visit to the same page that is already loaded. I know about cy.reload, however, as my tests are being generated by my preprocessor and I'm lazy, I haven't implemented cy.reload. 

The behaviour of cy.visit is different depending on whether there is a hash present or not. I'm not sure what the desired behaviour would be. However, if there is **no** hash present, cy.visit works like cy.reload and my tests (even using the preprocessor) are fine. If there is a hash present, it stops working, and cy.visit times out for some reason. 

### Desired behavior:
I'm unsure about the desired behaviour. I personally would like cy.visit to reload the page even if it is currently loaded. However, there may be reasons to not do this and throw an error? I'm not sure. Currently, the behaviour is inconsistent, and I'm not sure what the intended behaviour should be.

### Steps to reproduce:
It is easy to reproduce. Just write two tests:
```js
it("Multiple visits without hash", function() {
	cy.visit("https://www.google.com");
	cy.visit("https://www.google.com");
	cy.visit("https://www.google.com");
});
it("Multiple visits with hash", function() {
	cy.visit("https://www.google.com#x");
	cy.visit("https://www.google.com#x");
	cy.visit("https://www.google.com#x");
});
```
The first test will work fine, and Google will be loaded three times. The second test will fail with a time-out after 60 seconds. 

### Versions  
Cypress 2.1.0
Windows 10 x64 up-to-date
Built-in Electron browser from Cypress

**Comment by jennifer-shehane** [comment] 2018-05-08 15:01
Will have to look into this. I don't completely understand why you can't use `cy.reload()`, could you elaborate?

>  I know about cy.reload, however, as my tests are being generated by my preprocessor and I'm lazy, I haven't implemented cy.reload.

**Comment by MadMatt25** [comment] 2018-05-09 07:31
Sure. I have built a language on top of Cypress (using Xtext). This results in an Eclipse IDE in which I can easily write tests. From the sources of this new language, I generate a JavaScript file containing the Cypress tests. It is not always certain (in translation phase) that I am already on the correct URL, so I can not be sure whether to use cy.reload instead of cy.visit. However, I thought that didn't matter, because cy.visit worked just fine. I now discovered that cy.visit for some reason does not work fine when there is a hash in the URL. 

Even when ignoring all the "new language" and translation stuff, this is inconsistent behaviour. I would like to know which of the two behaviours is the intended one, such that I can adapt my language (and JS generator) to the desired behaviour.

**Comment by Bkucera** [comment] 2018-05-10 14:28
@MadMatt25 That's a good point you brought up. If we are reloading the page on `cy.visit()` with the already visited URL, we should probably be doing the same for hashes.

**Comment by masonmark** [comment] 2018-06-06 07:05
Oh I think this might relate to an issue I am debugging where our tests using `cy.visit()` more than once are timing out in that call after the default 60 seconds. In our case, the app is an old-style AngularJS app and there is a hash in every URL in the app.

**Comment by pacop** [comment] 2018-08-03 12:14
@masonmark same problem here, did you solve it?

**Comment by jennifer-shehane** [comment] 2018-08-06 22:17
I think this issue actually may be a duplicate of this - `onLoad` is not called on visit to current url. https://github.com/cypress-io/cypress/issues/1311

**Comment by marcelo-rebello** [comment] 2018-11-27 04:02
I have been trying in last days to just write some tests ina Vue app that uses lots of hash URL
visit more than one page is completely inconsistent
This doesn't look like a new issue based and make tests fail in unpredictable and randon.
Why cy.visit() can not simply visit the url always, no matter if it was already visited or if it has a hash?

now just spend several hours to hack Cypress to just work simple. maybe will be better just get other tool and rewrite all my tests...

**Closed** 2018-12-18 15:49 UTC
Labels: type: duplicate
