### ISSUE TITLE
Screenshot "scroll and stitch together" repeats element with CSS "position: fixed"

### ISSUE THREAD

**Issue by WalterMoar** [cypress-io/cypress#19700] opened 2022-01-13 21:31 UTC
### Current behavior

The "Feedback" section in my application is always visible to the user - it is in a fixed position as the user scrolls down the page. When I do a cy.screenshot(), the content of the fixed div is repeated. It appears that one screenshot isn't being taken, but rather multiple shots are done and stitched together. This appears to be another form of problems reported elsewhere with the way that the screenshot is being done (#2681, etc).

![bug -- page loaded](https://user-images.githubusercontent.com/35532993/149410768-11f99ec2-0cdd-48d2-8af6-d21e925f0bc2.png)

### Desired behavior

The "feedback" text / div should only appear once in the screenshot above. A screenshot should look like what would be seen in a browser if its window was large enough to fit the entire page.

If possible, a workaround would be helpful in the meantime.

### Test code to reproduce

Page:
```
<html>
  <body>
    <div style="display: inline-block; line-height: 500%; width: 500px;">
      body 00<br>body 01<br>body 02<br>body 03<br>body 04<br>
      body 05<br>body 06<br>body 07<br>body 08<br>body 09<br>
      body 10<br>body 11<br>body 12<br>body 13<br>body 14<br>
      body 15<br>body 16<br>body 17<br>body 18<br>body 19<br>
    </div>
    <div style="display: inline-block; position: fixed; top: 20%;">
      feedback
    </div>
  </body>
</html>
```

Test:
```
describe('bug', () => {
  it('page loaded', () => {
    cy.visit('/')
      .screenshot()
  })
})
```

### Cypress Version

Cypress package version: 9.2.0 Cypress binary version: 9.2.0 Electron version: 15.2.0 Bundled Node version: 16.5.0

**Comment by mjhenkes** [comment] 2022-01-14 14:58
@WalterMoar, Thanks for logging this issue!. This is indeed a duplicate of #2681 so I'm going to close this issue for now and It would be best to watch #2681 for a fix. Thanks!

**Closed by mjhenkes** 2022-01-14 14:58 UTC
