### ISSUE TITLE
Run all specs in folder in UI

### ISSUE THREAD

**Issue by pburkindine** [cypress-io/cypress#4316] opened 2019-05-27 17:15 UTC
### Current behavior:

UI does not have a way to run all specs in a certain folder (similar to `cypress run --spec "cypress/integration/some/group/*"`

### Desired behavior:

UI should offer this option

### Versions

OSX High Sierra
Cypress 3.3.1

**Comment by jennifer-shehane** [comment] 2019-05-28 04:48
Duplicate of #3607

**Closed by jennifer-shehane** 2019-05-28 04:48 UTC
