### ISSUE TITLE
Long opening time for e2e tests using Electron

### ISSUE THREAD

**Issue by anchelotti** [cypress-io/cypress#24795] opened 2022-11-23 09:58 UTC
### Current behavior

After selecting Electron for e2e tests, loading takes about 5 minutes. No such issue with Chrome and Firefox. Persistent on 11.0 - 11.2.

![Screenshot_20221123_114758](https://user-images.githubusercontent.com/46111941/203516176-79ab7073-2659-4c72-b1f1-efcb3e7bade6.png)

### Desired behavior

Loading e2e tests with Electron happens faster.

### Test code to reproduce

Any e2e test.

### Cypress Version

11.2

### Node version

16.13.2

### Operating System

Kubuntu 20.4

**Comment by nagash77** [comment] 2022-11-23 19:16
Hi @anchelotti .  I am sorry to hear you are having issues running Cypress.

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.  Can you replicate the issue on other OSes or is it specific to Kubuntu?

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by anchelotti** [comment] 2022-11-25 07:25
Hi, unfortunately I don't have possibility to reproduce on different OS at the moment. Maybe providing my package.json and package-lock.json might be useful?

**Comment by simondrabble** [comment] 2022-11-25 14:38
I see this same behaviour on Mac OS 12.1 (host) using the cypress/included:11.2.0 docker container. However it only occurs on the first run after `cypress open`.

**Comment by nagash77** [comment] 2022-11-28 20:48
@anchelotti can you try forking this repo [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) and creating an example in there and linking to it for ease of debugging on our end?  This will help narrow down configuration issues.

**Comment by nagash77** [comment] 2022-12-05 18:36
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-12-05 18:36 UTC
