### ISSUE TITLE
cy.clock() is broken after cypress update to 3.4.0

### ISSUE THREAD

**Issue by TheRusskiy** [cypress-io/cypress#4832] opened 2019-07-26 11:00 UTC
After upgrading cypress from 3.2.0 to 3.4.0 started getting this error.
It happens on 2 different projects.
It happens in 50% of the time.

There's nothing in our code that calls `clearInterval` or `clearTimeout`.

The spec itself contains `cy.clock()` and `cy.tick(500)`, so looks like this is caused by cypress, not by application code. Specs without it seem to work just fine.

### Current behavior:
```
Uncaught Error: Cannot clear timer: timer created with setTimeout() but cleared with clearInterval()

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
at clearTimer (http://localhost:21000/__cypress/runner/cypress_runner.js:46314:23)
at Object.clearInterval (http://localhost:21000/__cypress/runner/cypress_runner.js:46558:20)
at target.(anonymous function) (http://localhost:21000/__cypress/runner/cypress_runner.js:46373:38)
```

### Desired behavior:

Don't randomly error out :-)

### Versions

Docker, cypress  3.4.0, headless electron.

**Comment by jennifer-shehane** [comment] 2019-07-30 04:30
Hey, can you provide the test code you are running? We have many tests around this, so for us, calling a simple cy.clock() and cy.tick() is not going to recreate the error - there's likely something specific in the way you wrote your tests or the way your application runs that causes this. 

If we cannot reproduce, we'll have to close this issue unfortunately since there's no path forward for us.

**Comment by ignatiusreza** [comment] 2020-07-02 07:24
we were having this issue too.. the key issue was, we had some call to `setInterval` before `cy.clock`.. such that when the respective `clearInterval`, it was trying to clear the wrong timer..

rule of thumb to avoid this issue, call `cy.clock` before `cy.visit`..

**Comment by jennifer-shehane** [comment] 2020-07-02 07:47
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by jennifer-shehane** 2020-07-02 07:47 UTC
Labels: stage: needs information
