### ISSUE TITLE
Waiting for network request automatically retries after 2 minutes and fails after 4 minutes

### ISSUE THREAD

**Issue by mactishp** [cypress-io/cypress#14781] opened 2021-01-27 14:06 UTC
Note: This seems the same issue that has been reported here: https://github.com/cypress-io/cypress/issues/2055

### Current behavior

WHEN  I'm waiting for a network request that takes over 2 minutes
AND I have a long enough timeout specified on cy.wait
THEN the request automatically retries after **exactly 2 minutes**
AND the initial request fails after **exactly 4 minutes**
AND the wait for the initial request times out

![image](https://user-images.githubusercontent.com/35067774/106001248-02a7e400-60b0-11eb-99d2-938d9fa70268.png)

Console:

- Note: the second request does not show up in the console

![image](https://user-images.githubusercontent.com/35067774/106000325-fcfdce80-60ae-11eb-98ff-17c5d5d6bba9.png)

### Desired behavior

WHEN I'm waiting for a network request that takes over 2 minutes
AND I have a long enough timeout specified on cy.wait()
THEN the request should not retry
AND the request should wait for the custom defined timeout

### Test code to reproduce

Repro: Send request that takes more than two minutes to get response and wait for it.

![image](https://user-images.githubusercontent.com/35067774/106001851-bd37e680-60b0-11eb-887c-abca6dea1d0a.png)

### Versions

Cypress 6.1.0
Microsoft Edge 88.0.705.50
Windows 10

**Comment by flotwig** [comment] 2022-02-03 21:46
Duplicate of #9219, please watch that issue for updates

**Closed by flotwig** 2022-02-03 21:46 UTC
