### ISSUE TITLE
spam git ENOENT

### ISSUE THREAD

**Issue by errohitrana2013** [cypress-io/cypress#6861] opened 2020-03-26 16:33 UTC
### Current behavior: 
>npm install cypress --save-dev
npm error code ENOENT
npm error syscall spawn git
npm error path git
npm error errno ENOENT
npm error enoent Error while executing:
npm error enoent undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm error enoent
npm error enoent
npm error enoent spawn git ENOENT
npm  error enoent This is related to npm not being able to find a file.
npm  error   C:\Users\Happy_PC\AppData\Roaming\npm-cache\_logs\2020-03-26T10_12_06_926Z-debug.log

### logs:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cypress',
1 verbose cli   '--save-dev'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session cbe6e812dc2577b7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/cypress 4407ms (from cache)
8 silly pacote tag manifest for cypress@latest fetched in 4479ms
9 timing stage:loadCurrentTree Completed in 4590ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule cypress@4.2.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@cypress%2flistr-verbose-renderer 3340ms (from cache)
18 silly pacote version manifest for @cypress/listr-verbose-renderer@0.4.1 fetched in 3349ms
19 silly resolveWithNewModule @cypress/listr-verbose-renderer@0.4.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/common-tags 2394ms (from cache)
21 silly pacote version manifest for common-tags@1.8.0 fetched in 2402ms
22 silly resolveWithNewModule common-tags@1.8.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/arch 6021ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/cli-table3 5974ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/chalk 6012ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/commander 5987ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/@types%2fsizzle 6046ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/check-more-types 6003ms (from cache)
29 silly pacote version manifest for arch@2.1.1 fetched in 6049ms
30 silly resolveWithNewModule arch@2.1.1 checking installable status
31 silly pacote version manifest for cli-table3@0.5.1 fetched in 6017ms
32 silly resolveWithNewModule cli-table3@0.5.1 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/cachedir 6055ms (from cache)
34 silly pacote version manifest for chalk@2.4.2 fetched in 6057ms
35 silly resolveWithNewModule chalk@2.4.2 checking installable status
36 http fetch GET 304 https://registry.npmjs.org/bluebird 6073ms (from cache)
37 silly pacote version manifest for @types/sizzle@2.3.2 fetched in 6102ms
38 silly resolveWithNewModule @types/sizzle@2.3.2 checking installable status
39 silly pacote version manifest for commander@4.1.0 fetched in 6049ms
40 silly resolveWithNewModule commander@4.1.0 checking installable status
41 silly pacote version manifest for check-more-types@2.24.0 fetched in 6083ms
42 silly resolveWithNewModule check-more-types@2.24.0 checking installable status
43 silly pacote version manifest for cachedir@2.3.0 fetched in 6129ms
44 silly resolveWithNewModule cachedir@2.3.0 checking installable status
45 silly pacote version manifest for bluebird@3.7.2 fetched in 6161ms
46 silly resolveWithNewModule bluebird@3.7.2 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/@cypress%2fxvfb 6253ms (from cache)
48 silly pacote version manifest for @cypress/xvfb@1.2.4 fetched in 6265ms
49 silly resolveWithNewModule @cypress/xvfb@1.2.4 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/debug 597ms (from cache)
51 silly pacote version manifest for debug@4.1.1 fetched in 602ms
52 silly resolveWithNewModule debug@4.1.1 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/eventemitter2 1465ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/executable 1444ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/execa 1458ms (from cache)
56 http fetch GET 304 https://registry.npmjs.org/extract-zip 1420ms (from cache)
57 silly pacote version manifest for eventemitter2@4.1.2 fetched in 1488ms
58 silly resolveWithNewModule eventemitter2@4.1.2 checking installable status
59 silly pacote version manifest for executable@4.1.1 fetched in 1470ms
60 silly resolveWithNewModule executable@4.1.1 checking installable status
61 silly pacote version manifest for extract-zip@1.6.7 fetched in 1446ms
62 silly resolveWithNewModule extract-zip@1.6.7 checking installable status
63 silly pacote version manifest for execa@1.0.0 fetched in 1492ms
64 silly resolveWithNewModule execa@1.0.0 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/getos 1637ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/fs-extra 1640ms (from cache)
67 http fetch GET 304 https://registry.npmjs.org/is-ci 1609ms (from cache)
68 http fetch GET 304 https://registry.npmjs.org/is-installed-globally 1591ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/lazy-ass 1501ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/listr 1428ms (from cache)
71 silly pacote version manifest for getos@3.1.4 fetched in 1657ms
72 silly resolveWithNewModule getos@3.1.4 checking installable status
73 silly pacote version manifest for fs-extra@8.1.0 fetched in 1664ms
74 silly resolveWithNewModule fs-extra@8.1.0 checking installable status
75 silly pacote version manifest for is-ci@2.0.0 fetched in 1631ms
76 silly resolveWithNewModule is-ci@2.0.0 checking installable status
77 silly pacote version manifest for is-installed-globally@0.1.0 fetched in 1613ms
78 silly resolveWithNewModule is-installed-globally@0.1.0 checking installable status
79 silly pacote version manifest for lazy-ass@1.6.0 fetched in 1681ms
80 silly resolveWithNewModule lazy-ass@1.6.0 checking installable status
81 silly pacote version manifest for listr@0.14.3 fetched in 1610ms
82 silly resolveWithNewModule listr@0.14.3 checking installable status
83 silly fetchPackageMetaData error for request@github:cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16 Error while executing:
83 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
83 silly fetchPackageMetaData
83 silly fetchPackageMetaData
83 silly fetchPackageMetaData spawn git ENOENT
84 http fetch GET 304 https://registry.npmjs.org/lodash 1035ms (from cache)
85 http fetch GET 304 https://registry.npmjs.org/minimist 1019ms (from cache)
86 http fetch GET 304 https://registry.npmjs.org/log-symbols 1044ms (from cache)
87 silly pacote version manifest for lodash@4.17.15 fetched in 1056ms
88 silly resolveWithNewModule lodash@4.17.15 checking installable status
89 silly pacote version manifest for minimist@1.2.2 fetched in 1043ms
90 silly resolveWithNewModule minimist@1.2.2 checking installable status
91 http fetch GET 304 https://registry.npmjs.org/moment 1044ms (from cache)
92 silly pacote version manifest for log-symbols@3.0.0 fetched in 1066ms
93 silly resolveWithNewModule log-symbols@3.0.0 checking installable status
94 silly pacote version manifest for moment@2.24.0 fetched in 1067ms
95 silly resolveWithNewModule moment@2.24.0 checking installable status
96 http fetch GET 304 https://registry.npmjs.org/ramda 1082ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/pretty-bytes 1092ms (from cache)
98 silly pacote version manifest for ramda@0.26.1 fetched in 1099ms
99 silly resolveWithNewModule ramda@0.26.1 checking installable status
100 silly pacote version manifest for pretty-bytes@5.3.0 fetched in 1103ms
101 silly resolveWithNewModule pretty-bytes@5.3.0 checking installable status
102 http fetch GET 304 https://registry.npmjs.org/request-progress 947ms (from cache)
103 http fetch GET 304 https://registry.npmjs.org/supports-color 944ms (from cache)
104 http fetch GET 304 https://registry.npmjs.org/tmp 893ms (from cache)
105 silly pacote version manifest for request-progress@3.0.0 fetched in 957ms
106 silly resolveWithNewModule request-progress@3.0.0 checking installable status
107 silly pacote version manifest for supports-color@7.1.0 fetched in 953ms
108 silly resolveWithNewModule supports-color@7.1.0 checking installable status
109 silly pacote version manifest for tmp@0.1.0 fetched in 906ms
110 silly resolveWithNewModule tmp@0.1.0 checking installable status
111 http fetch GET 304 https://registry.npmjs.org/untildify 831ms (from cache)
112 http fetch GET 304 https://registry.npmjs.org/url 825ms (from cache)
113 http fetch GET 304 https://registry.npmjs.org/yauzl 824ms (from cache)
114 silly pacote version manifest for untildify@4.0.0 fetched in 849ms
115 silly resolveWithNewModule untildify@4.0.0 checking installable status
116 silly pacote version manifest for url@0.11.0 fetched in 843ms
117 silly resolveWithNewModule url@0.11.0 checking installable status
118 silly pacote version manifest for yauzl@2.10.0 fetched in 837ms
119 silly resolveWithNewModule yauzl@2.10.0 checking installable status
120 http fetch GET 304 https://registry.npmjs.org/ospath 1745ms (from cache)
121 silly pacote version manifest for ospath@1.2.2 fetched in 1748ms
122 silly resolveWithNewModule ospath@1.2.2 checking installable status
123 timing stage:rollbackFailedOptional Completed in 1ms
124 timing stage:runTopLevelLifecycles Completed in 14214ms
125 silly saveTree hello@4.2.0
125 silly saveTree `-- cypress@4.2.0
125 silly saveTree   +-- @cypress/listr-verbose-renderer@0.4.1
125 silly saveTree   +-- @cypress/xvfb@1.2.4
125 silly saveTree   +-- @types/sizzle@2.3.2
125 silly saveTree   +-- arch@2.1.1
125 silly saveTree   +-- bluebird@3.7.2
125 silly saveTree   +-- cachedir@2.3.0
125 silly saveTree   +-- chalk@2.4.2
125 silly saveTree   +-- check-more-types@2.24.0
125 silly saveTree   +-- cli-table3@0.5.1
125 silly saveTree   +-- commander@4.1.0
125 silly saveTree   +-- common-tags@1.8.0
125 silly saveTree   +-- debug@4.1.1
125 silly saveTree   +-- eventemitter2@4.1.2
125 silly saveTree   +-- execa@1.0.0
125 silly saveTree   +-- executable@4.1.1
125 silly saveTree   +-- extract-zip@1.6.7
125 silly saveTree   +-- fs-extra@8.1.0
125 silly saveTree   +-- getos@3.1.4
125 silly saveTree   +-- is-ci@2.0.0
125 silly saveTree   +-- is-installed-globally@0.1.0
125 silly saveTree   +-- lazy-ass@1.6.0
125 silly saveTree   +-- listr@0.14.3
125 silly saveTree   +-- lodash@4.17.15
125 silly saveTree   +-- log-symbols@3.0.0
125 silly saveTree   +-- minimist@1.2.2
125 silly saveTree   +-- moment@2.24.0
125 silly saveTree   +-- ospath@1.2.2
125 silly saveTree   +-- pretty-bytes@5.3.0
125 silly saveTree   +-- ramda@0.26.1
125 silly saveTree   +-- request-progress@3.0.0
125 silly saveTree   +-- supports-color@7.1.0

### Desired behavior:
>npm install cypress --save-dev

Installing Cypress (version)

Downloaded Cypress
Unzipped Cypress
Finishded Installion C:\Users\Happy_PC\AppData\Local\Cache\3.6.1

### Test code to reproduce

npm init
npm install cypress --save-dev

### Versions
cypress version : "4.2.0",
Operation System :- Windows 8.1
System type:- 64 bit
Google Chrome :- Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by cfurst** [comment] 2020-03-26 21:57
I'm having the same issue, when running this, especially in a docker container:
```
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by macpham** [comment] 2020-03-27 00:36
I'm seeing:

```
npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cypress/request@github:cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16" as it does not contain a package.json file.
```

When trying to install 4.2.0

**Comment by jennifer-shehane** [comment] 2020-03-27 08:27
Duplicate of #6752 

This will be fixed in our next release on Monday. Downgrade to 4.1.0 in the meantime to get around this errro.

**Closed by jennifer-shehane** 2020-03-27 08:27 UTC

**Comment by errohitrana2013** [comment] 2020-03-27 08:31
i have check with 4.1.0 also same error.
