### ISSUE TITLE
Test runner disappear after screen resize

### ISSUE THREAD

**Issue by eppisapia** [cypress-io/cypress#7814] opened 2020-06-25 13:06 UTC
### Current behavior:

While doing a Test resize the browser screen and the Left Panel disappear and cannot open again

<img width="1440" alt="Captura de Pantalla 2020-06-25 a la(s) 9 01 27 a  m" src="https://user-images.githubusercontent.com/20419303/85725133-d6178e00-b6c2-11ea-899a-8224cb26867f.png">

### Desired behavior:

Should be like this
<img width="869" alt="Captura de Pantalla 2020-06-25 a la(s) 9 05 10 a  m" src="https://user-images.githubusercontent.com/20419303/85725402-12e38500-b6c3-11ea-9d34-faef93b98bb4.png">

**Comment by jennifer-shehane** [comment] 2020-06-26 11:02
Duplicate of https://github.com/cypress-io/cypress/issues/2132 

To get it back follow these instructions https://github.com/cypress-io/cypress/issues/2132#issuecomment-404561427

**Closed by jennifer-shehane** 2020-06-26 11:02 UTC
