### ISSUE TITLE
Why we need to call visit in every it test cases as first statement when cross origin used

### ISSUE THREAD

**Issue by BeBestOf** [cypress-io/cypress#22704] opened 2022-07-07 06:47 UTC
### What would you like?

When we used cross origin we have to call visit every time at the beginning of it block statement due to which we have to re-write our code to continuous flow. Also we're not able to test continuous flow of module. For an example, let's say in before we used origin and logged in via SSO, now we're at home screen in next it we have added one user from app and clicked on user link and redirected to user detail screen, now if calling visit at the beginning I have to again click on user link.

`let testData = require('../cross-origin-scenarios.json')
describe("Verify cross origin test", ()=>{

    before(()=>{
        // visit circleci login page
        cy.visit("https://circleci.com/vcs-authorize/");

        //click on sign in link
        cy.contains("Log In with GitHub").click({ force: true });

        //click on 'login with Github' button
        cy.origin("https://github.com", () => {
            cy.get("#login_field").type("************");
            cy.get("#password").type("********");
            cy.get("input").contains("Sign in").click();
        });

        // should load circleci app with logged in user
        cy.url().should("contain", "https://app.circleci.com/");
    });

    //Add new user and click on added user link
    it("Continue with Dashboard of app.cricle.ci.com without calling 'visit'", ()=>{
        //without calling visit would like to continue test flow without refreshing the page
        cy.get("#addButton").click();
        cy.get("#firstname").click().type("test_first");
        cy.get("#lastname").click().type("test_last");
        cy.contains("button", "Add").click()
        cy.contains("a", "test_first").click()
        //redirected to user details screen
    })

    //here would like to test negative and positive scenario on user detail screen
    testData.forEach((scenario:any)=>{
        it(scenario.scenarioName, ()=>{
             //here will continue to test different scenarios without calling of visit
            
            //note : If called visit at first statement which redirects again to home screen
        });
    });

});`

### Why is this needed?

Just to avoid calling of visit in every it block if we have used cross origin in test case so that w can save many lines of code not calling visit in every it block.

**Comment by chrisbreiding** [comment] 2022-07-12 13:05
I'd recommend using a `beforeEach` instead of a `before` hook, then you don't have to repeat the code in each `it` block. I'd also recommend utilizing [cy.session()](https://docs.cypress.io/api/commands/session) for your login flow, since it will effectively memoize it and subsequent tests won't need to go through the steps to log the user in.

**Comment by mjhenkes** [comment] 2022-07-19 20:14
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-07-19 20:15 UTC
Labels: stage: awaiting response
