### ISSUE TITLE
cy.visit() failed trying to load https://example.cypress.io/，but I can open it with my browser

### ISSUE THREAD

**Issue by debbyzang** [cypress-io/cypress#7100] opened 2020-04-22 03:40 UTC
### Current behavior:

```
CypressError: `cy.visit()` failed trying to load:

https://example.cypress.io/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ETIMEDOUT 104.26.6.176:443

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ETIMEDOUT 104.26.6.176:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)

    (No stack trace)
From previous event:
    at go (http://localhost:57342/__cypress/runner/cypress_runner.js:134555:17)
    at http://localhost:57342/__cypress/runner/cypress_runner.js:134609:20
From previous event:
    at visit (http://localhost:57342/__cypress/runner/cypress_runner.js:134607:34)
    at Context.visit (http://localhost:57342/__cypress/runner/cypress_runner.js:134615:14)
    at http://localhost:57342/__cypress/runner/cypress_runner.js:144167:33
From previous event:
    at runCommand (http://localhost:57342/__cypress/runner/cypress_runner.js:144146:14)
    at next (http://localhost:57342/__cypress/runner/cypress_runner.js:144289:14)
From previous event:
    at http://localhost:57342/__cypress/runner/cypress_runner.js:144330:37
From previous event:
    at run (http://localhost:57342/__cypress/runner/cypress_runner.js:144323:19)
    at Object.cy.<computed> [as visit] (http://localhost:57342/__cypress/runner/cypress_runner.js:144735:11)
    at Context.runnable.fn (http://localhost:57342/__cypress/runner/cypress_runner.js:144967:24)
    at callFn (http://localhost:57342/__cypress/runner/cypress_runner.js:88160:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:57342/__cypress/runner/cypress_runner.js:88147:7)
    at http://localhost:57342/__cypress/runner/cypress_runner.js:148972:28
From previous event:
    at Object.onRunnableRun (http://localhost:57342/__cypress/runner/cypress_runner.js:148960:20)
    at $Cypress.action (http://localhost:57342/__cypress/runner/cypress_runner.js:141238:61)
    at Test.Runnable.run (http://localhost:57342/__cypress/runner/cypress_runner.js:147768:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:57342/__cypress/runner/cypress_runner.js:88819:10)
    at http://localhost:57342/__cypress/runner/cypress_runner.js:88945:12
    at next (http://localhost:57342/__cypress/runner/cypress_runner.js:88728:14)
    at http://localhost:57342/__cypress/runner/cypress_runner.js:88738:7
    at next (http://localhost:57342/__cypress/runner/cypress_runner.js:88640:14)
    at http://localhost:57342/__cypress/runner/cypress_runner.js:88706:5
    at timeslice (http://localhost:57342/__cypress/runner/cypress_runner.js:82632:27)
```

### Desired behavior:

just open it. Because I and open it  with my chrome

### Versions

windows10 64 cypress version maybe 4.4.1, since I have no idea how to check the version

**Comment by jennifer-shehane** [comment] 2020-04-22 07:03
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by eternalmatt** [comment] 2020-09-04 19:09
I'm not OP, but I get this in my logs:

cypress:network:connect received error on connect, retrying { iteration: 0, delay: 0, err: Error: connect ETIMEDOUT {{redacted}}:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) { errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect', address: '{{redacted}}', port: 443 } }

redacted IP because it is my company's public IP address

This occurs 30 seconds after my last successful network log, and it causes cypress to wait 30 seconds at the start of the test run.

**Comment by jennifer-shehane** [comment] 2020-10-20 10:56
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2020-10-20 10:56 UTC
Labels: stage: needs information

**Comment by vpvikash** [comment] 2021-06-25 14:57
I am getting - From Node.js Internals:
    Error: connect ETIMEDOUT 3.6.24.244:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
