### ISSUE TITLE
visit local file fails because it always prepends the baseUrl

### ISSUE THREAD

**Issue by stuartbrussell-intuit** [cypress-io/cypress#7972] opened 2020-07-14 06:21 UTC
### Current behavior:

The cy.visit() command does not work trying to access a local file. This has been mentioned in several issues but it doesn't work for me. It always prepends the baseUrl.

### Desired behavior:
Everything I've tried always prepends the baseUrl.

```
myProject
    cypress.json  (in here, set a baseUrl)
    localFiles/
        index.html

cy.visit('./localFiles/index.html')
cy.visit('./localFiles/')
cy.visit('/localFiles/index.html')
cy.visit('/localFiles/')

```
### Versions

Cypress 4.8.0
macOS 10.15.5

**Comment by jennifer-shehane** [comment] 2020-07-14 06:27
Duplicate of #2918

**Closed by jennifer-shehane** 2020-07-14 06:27 UTC
