### ISSUE TITLE
Code in afterEach fails if test didn't pass

### ISSUE THREAD

**Issue by akapitoha** [cypress-io/cypress#3487] opened 2019-02-15 16:44 UTC
### Current behavior:
I added logout to some tests (we face some specific issues if not to do that) and logout works fine if the test itself passes.
In case test fails, then logout also fails.
Attached screenshot

### Desired behavior:
Logout from afterEach hook is executed successfully

### Steps to reproduce: (app code and test code)
error: `click() failed because it requires a DOM element`

![screenshot 2019-02-15 at 23 23 34](https://user-images.githubusercontent.com/3147449/52870951-96aa6a80-317b-11e9-8b06-b1047e4c5257.png)
`
afterEach:
```
afterEach(function() {
    functions.logout()
  })
```

logout code:
```
logout: function() {
    cy.get('[data-testid="profile-settings-button"]')
      .click()
    cy.get('[data-testid="menu-log-out"]')
      .click()
    cy.get('[data-testid="login-emailphone-input"]')
      .should('be.visible')
  },
```
sometimes code from afterEach hook fails on second click()

### Versions

3.1.5, Chromium 74, Mac OS

**Comment by jennifer-shehane** [comment] 2019-02-15 17:36
Duplicate of https://github.com/cypress-io/cypress/issues/2831

**Closed by jennifer-shehane** 2019-02-15 17:36 UTC
Labels: stage: needs information
