### ISSUE TITLE
An error inside the intercept callback hangs Cypress

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14632] opened 2021-01-19 13:47 UTC
Cypress v6.2.1
Reproducible example in https://github.com/bahmutov/todo-graphql-example/tree/crash-and-hang

- Clone the repo
- `git checkout crash-and-hang` branch
- `npm install`
- `npm run dev`
- click on the `spec.js`
- after running, try to click 'rerun' tests or interact - is it frozen

This spec runs
```js
it('completes the first todo', () => {
  cy.intercept(
    {
      method: 'POST',
      url: '/',
    },
    (req) => {
      console.log('inside the intercept')
      throw new Error('nope')
    },
  )
  cy.visit('/')
})
```

It throws an error inside the intercept - this error is never shown to the user, the test passes, but the Cypress is frozen after that as this video shows. I cannot restart the tests or even really close the browser until some time later

https://user-images.githubusercontent.com/2212006/105042919-d72f5480-5a32-11eb-8716-ff6f8b5ac501.mp4

**Comment by jennifer-shehane** [comment] 2021-01-20 03:35
This issue has been present since `route2()` was introduced in 5.1.0, so is not a regression. 

I can't get this error to happen with just plain XHR request, so it's something more specific to this application.

**Comment by flotwig** [comment] 2021-01-22 18:34
Potentially related: #9118

**Comment by sainthkh** [comment] 2021-03-09 02:44
It's interesting. When I run the test as-is, it failed. 

But I tested with the code below in the development environment, nothing went wrong.

```js
it('t', (done) => {
  cy.intercept('/dump-method', function (req) {
    expect(req.method).to.eq('POST')

    req.method = 'PATCH'

    throw new Error('x')
  }).then(function () {
    Cypress.$.post('/dump-method').done((responseText) => {
      expect(responseText).to.contain('request method: PATCH')

      done()
    })
  })
})
```

And I changed the backend Cypress to dev version by `yarn link cypress` and test it again. It worked fine.

**Comment by flotwig** [comment] 2021-04-08 18:48
The OP is confusing, the intercept is set up for a POST, but a GET is sent in the `.visit`? It never even calls the `cy.intercept` callback.

Of course, when I run this code in 7.0.1, nothing happens, the cy.visit continues as normal.

If I modify the `cy.visit` to use `method: POST` so it hits the `cy.intercept`, the test also fails as expected in 7.0.1:
![image](https://user-images.githubusercontent.com/1151760/114080478-fa7fd800-989a-11eb-9116-ca1d3b57007f.png)

Closing since it appears to have been resolved, if there was an issue as described.

**Closed by flotwig** 2021-04-08 18:48 UTC
Labels: pkg/net-stubbing, stage: ready for work, type: bug
