### ISSUE TITLE
Command Log improvements for calls made from a within callback

### ISSUE THREAD

**Issue by CoryDanielson** [cypress-io/cypress#17640] opened 2021-08-06 16:04 UTC
### What would you like?

When a `cy.get()` is made from a `within` callback, it would be nice if the `get` was displayed differently in the command log. I assume the `withinSubject` is going to be set in this scenario, so that seems like displaying that would be a great improvement.

Currently a get called from within will look something like this in the command log
```
get     #SomeElement
```

It would be great if it was displayed like this
```
get     #SomeElement (withinSubject #AnotherElementSelector)
```

Additionally, the error messaging could be better. At a minimum it should indicate that a call was made from a within callback, but it may also be beneficial to suggest that a failed selector may not be working due to being nested in a `within`... perhaps Cypress could run the same selector with `{withinSubject: null}` and report if an element was found elsewhere in the DOM. I think if the error messaging was more helpful and suggestive from `within` callbacks it could really help move people along when they bump into these kinds of issues. It certainly would have saved me a couple of hours yesterday and today.

### Why is this needed?

This would greatly improve the developers ability to debug a failed DOM lookup, especially when the developer is unknowingly inside of a within callback. This can happen often if you're editing functions in PageObjects/UI helpers that are called from multiple test files.

### Other

Here is an example of this same issue that a user was having. (https://github.com/cypress-io/cypress/issues/14566) The github issue was open for 10 days before someone suggested using `cy.get(selector, {withinSubject:null});` with no explanation. Four months later someone else explained why the suggested fix worked. I suspect that these subtle issues from `within` callbacks are causing developers a lot of pain.

 From the screenshot provided, you can see on line 17 that there is a `- within` but it was easily missed or not suspected to be the root cause. The test code was also provided, which included a within block that had 7 nested `get` calls.

https://user-images.githubusercontent.com/59794856/104608655-27f82380-56a8-11eb-8437-bd235b64118c.png

**Comment by jennifer-shehane** [comment] 2021-09-14 16:12
Duplicate of https://github.com/cypress-io/cypress/issues/7673

**Closed by jennifer-shehane** 2021-09-14 16:12 UTC
Labels: type: enhancement, stage: proposal 💡, pkg/reporter
