### ISSUE TITLE
cy.clock doesn't work in headless electron

### ISSUE THREAD

**Issue by esetnik** [cypress-io/cypress#25689] opened 2023-02-02 17:44 UTC
### Current behavior

Exclusively when using headless electron (the default for `cypress run`) with the following code:

```js
cy.clock(Date.UTC(2023,0,16));
```

The date is not changed in the client javascript. Calling `new Date()` returns the current date and not Jauary 16th, 2023.
This behavior does not happen in headed electron or in headless chrome / firefox which both work correctly.

### Desired behavior

cy.clock(Date.UTC(2023,0,16));

should exhibit the same behavior in headed and headless electron

### Test code to reproduce

```
     // works in chrome or if passing `--headed` (tests have correct current date set to Jan 16th, 2023)
      cypress run 
        --record 
        --key xxx
        --parallel
        --group circleci-chrome
        --browser chrome
```

```
     // does not work in electron (tests have current date set to today's date)
      cypress run 
        --record 
        --key xxx
        --parallel
        --group circleci-chrome
```

```ts
// page_spec.ts

describe(`The Page`, () => {
  beforeEach(function () {
    cy.clock(Date.UTC(2023,0,16), ['Date']);
    cy.visit('/');
  });
});
```

### Cypress Version

v12.5.0

### Node version

v16.18.0

### Operating System

FROM cypress/included:12.5.0@sha256:8e13566035b9e96404a865ca0294937437136312aa693cee91fc12cd2b1019df

### Other

I also tested in v12.3 and v12.4 and they both exhibit the same behavior.

**Comment by warrensplayer** [comment] 2023-02-10 16:46
@esetnik  I am not able to reproduce the problem. I wrote a test like yours above and my app displayed the time set by `cy.clock` as expected. 

Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marktnoonan** [comment] 2023-02-17 19:41
Hi @esetnik, unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as completed by marktnoonan** 2023-02-17 19:41 UTC
