### ISSUE TITLE
after/before hooks are rerun on domain navigation

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#7021] opened 2020-04-16 02:29 UTC
### Current behavior:
on domain navigation, before/after hooks will be rerun erroneously.

### Desired behavior:
before/after hooks should only be run once regardless of domain navigation

### Test code to reproduce

this spec will infinitely navigate between 2 domains since the before and after hooks are rerun
```js
describe('suite', () => {
  before(() => {
    // will cause infinite top navigation
    cy.visit('/fixtures/generic.html')
  })

  beforeEach(() => {
  })

  it('test', () => {
  })

  afterEach(() => {
  })

  after(() => {
    // will cause infinite top navigation
    cy.visit('/fixtures/generic.html')
  })
})

describe('cause top navigation', () => {
  it('test', () => {
    cy.visit('http://localhost:3501/fixtures/generic.html')
  })
})

```

### Versions
all

**Comment by jennifer-shehane** [comment] 2020-04-16 10:17
Duplicate of #1987

**Closed by jennifer-shehane** 2020-04-16 10:17 UTC
