### ISSUE TITLE
Cypress extension is not installed

### ISSUE THREAD

**Issue by sacegenko** [cypress-io/cypress#28806] opened 2024-01-26 14:48 UTC
### Current behavior

I upgraded my test project from cypress 13.5.1 to 13.6.3 and now when I unfocus cypress window the cypress execution gets frozen. I see that Cypress extension is not installed when the execution starts.

![image](https://github.com/cypress-io/cypress/assets/148965749/fa6e151c-9539-419d-b6cb-e23fe6ae205a)

My browser policy is managed by my corporation, and they set "ExtensionInstallBlocklist" to * and the extension ID (caljajdfkjjjdehjdoimjkkakekklcck)  is added to the "ExtensionInstallAllowlist" but cypress extension is not installed.

Edge version: 121

I can use chrome and electron but the corporative browser is Edge.

### Desired behavior

I want to focus on another window and let the cypress execution on another window

### Test code to reproduce

cy.visit("/")

### Cypress Version

13.6.3

### Node version

18.15.0

### Operating System

win10

**Comment by jennifer-shehane** [comment] 2024-01-26 14:52
Duplicate of https://github.com/cypress-io/cypress/issues/28392

Can you ensure the extension is enabled following [these instructions](https://github.com/cypress-io/cypress/issues/28392#issuecomment-1852735772)? For some people the extension has become disabled with newer Chrome versions.

**Closed as not planned by jennifer-shehane** 2024-01-26 14:52 UTC
Labels: type: duplicate

**Comment by sacegenko** [comment] 2024-01-26 15:18
Thank you @jennifer-shehane , yes I do. In my case I don't see any extension and we think it's due to the way of the cypress extension it's installed if the browser have the policy ExtensionInstallBlocklist set to "*". I think it's the same issue as #28392 

Thank you.

**Comment by jennifer-shehane** [comment] 2024-01-26 21:39
@sacegenko A blocklist value of '*' means all extensions are blocked unless they are explicitly listed in the allowlist. You would need to allow the Cypress extension Id in the allowlist as explained here: https://docs.cypress.io/guides/references/troubleshooting#Allow-the-Cypress-Chrome-extension

**Comment by sacegenko** [comment] 2024-01-29 08:50
we did it, but the extension is not installed in edge when the executions starts

![edgepolicy](https://github.com/cypress-io/cypress/assets/148965749/40908dd3-0fc7-41b1-9511-56e27992d639)


In chrome we do not have policy and the extension is installed, we are using chrome as workarround
