### ISSUE TITLE
AngularStrap aside not closing in Electron

### ISSUE THREAD

**Issue by oscar-b** [cypress-io/cypress#4439] opened 2019-06-12 09:46 UTC
### Current behavior:

The following test fails consistently for me. It seems like a browser problem, it works without problems in Chrome.  Toggling the aside manually works fine in Electron, after the test has failed. Using the tricks from other tickets to `wait` or `clickUntil` doesn't work either.

![Kapture 2019-06-12 at 11 43 48](https://user-images.githubusercontent.com/85102/59341058-6fb60c80-8d07-11e9-8f94-e19f25f48bb7.gif)

### Desired behavior:

The aside to open and close properly, and Cypress to assert that properly.

### Steps to reproduce: (app code and test code)

```js
describe('AngularStrap aside', function() {
	beforeEach(function() {
		cy.visit('https://mgcrea.github.io/angular-strap/');
	});

	it('opens and closes correctly', function() {
		cy.get('[href="#asides"]').click();

		cy.get(
			':nth-child(2) > .bs-docs-section > .bs-example > .btn-primary'
		).click();
		cy.get('.aside').should('be.visible');
		cy.get('.aside-backdrop').should('be.visible');

		// Doesn't help..
		//cy.wait(1000);

		// Doesn't work in Electron
		cy.get('.close').click();

		// https://github.com/cypress-io/cypress/issues/2402#issuecomment-465732748
		// cy.get('.close').clickUntil('not.exist');

		cy.get('.aside').should('not.exist');
		cy.get('.aside-backdrop').should('not.exist');
	});
});
```

### Versions

Cypress 3.3.1 with Electron 61, macOS 10.14.4

**Comment by jennifer-shehane** [comment] 2019-06-17 09:34
This code works for me when I run it in Electron 61, Cypress 3.3.1 😬 	

Do you have any extra settings in your `cypress.json` perhaps? Like overriding `animationDistanceThreshold`?

![](http://g.recordit.co/DJgFXiMe67.gif)

**Comment by oscar-b** [comment] 2019-06-18 08:01
Very strange.. The only thing in my `cypress.json` is:

```
{
	"baseUrl": "http://localhost",
	"viewportWidth": 1280,
	"viewportHeight": 900,
	"env": {...}
}
```

Does it also pass for you in headless mode? Mine fails there as well..

```

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.3.1                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      1 found (aside.js)                                                                 │
  │ Searched:   cypress/integration/aside.js                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: aside.js...                                                                     (1 of 1) 


  AngularStrap aside
    1) opens and closes correctly


  0 passing (8s)
  1 failing

  1) AngularStrap aside opens and closes correctly:
     CypressError: Timed out retrying: Expected <div.aside.right.am-fade-and-slide-right.ng-animate.ng-leave.ng-leave-active> not to exist in the DOM, but it was continuously found.
      at Object.cypressErr (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:83220:11)
      at Object.throwErr (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:83185:18)
      at Object.throwErrByPath (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:83212:17)
      at retry (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:76640:16)
      at https://mgcrea.github.io/__cypress/runner/cypress_runner.js:68612:18
      at tryCatcher (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:132142:23)
      at Promise._settlePromiseFromHandler (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:130160:31)
      at Promise._settlePromise (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:130217:18)
      at Promise._settlePromise0 (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:130262:10)
      at Promise._settlePromises (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:130337:18)
      at Async._drainQueue (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:127066:16)
      at Async._drainQueues (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:127076:10)
      at Async.drainQueues (https://mgcrea.github.io/__cypress/runner/cypress_runner.js:126950:14)
      at <anonymous>
```

**Comment by jennifer-shehane** [comment] 2019-07-11 08:37
Yes, this does pass for me in `cypress run` also. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-07-11 08:37 UTC
Labels: stage: needs information
