### ISSUE TITLE
Whoops, there is no test to run.

### ISSUE THREAD

**Issue by mylearning1005** [cypress-io/cypress#8354] opened 2020-08-19 23:56 UTC
## Issue

When i try to save the Create a property alert by clicking save search  

![image](https://user-images.githubusercontent.com/62883525/90701154-9b277600-e27f-11ea-872b-0e9c69ff1746.png)

I am getting the below error

![image](https://user-images.githubusercontent.com/62883525/90701425-4b957a00-e280-11ea-9f46-72a6514be4bd.png)

### Test code to reproduce

test.js
```js

context('Email Updates', () => {
  let testdata

  beforeEach(() => {
    cy.fixture("test_data").then((data) => { testdata = data })
    cy.visitZooplaHome()
  })

  describe('Register for daily email updates on rental property', () => {
    let rentTab = '#search-tabs-to-rent > span'
    let searchInput = '.search-input-location-placeholder-1'
    let rentMinPriceSelector = '#rent_price_min_per_month'
    let rentMaxPriceSelector = '#rent_price_max_per_month'
    let noOfBedrooms = '#beds_min'
    let searchButton = '#search-submit'
    let createEmailAlertButton = '#alert-btn-create'

    it('Register for daily email updates on rental property in London for  bed properties between £800 and £1000 per month', () => {
      cy.login(testdata.userid, testdata.password)
      cy.get(rentTab).click()
      cy.get(searchInput).type('London')
      cy.get('.search-home-reskin__title').click()
      cy.get(rentMinPriceSelector).select('£800 pcm')
      cy.get(rentMaxPriceSelector).select('£1,000 pcm')
      cy.get(noOfBedrooms).select('1+')
      cy.get(searchButton).click()
      cy.get('h1').contains('Property to rent in London')

      cy.get('#alert-btn-create').click()
      cy.get('#form_alert_search').submit()
    })
  })
})
```

test_data.json
```json
{
  "userid": "uitestcypress@gmail.com",
  "password": "Uitest1234"
}
```

command.js

```js
let acceptallcookiesbutton = '.ui-cookie-consent-choose__buttons > .ui-button-primary'
let signinbutton = '.css-1mjljx5 > .css-79elbk > [data-testid=header-profile] > :nth-child(4) > [data-testid=header-profile-sign-in]'
let signinemail = '#signin_email'
let signinpassword = '#signin_password'
let signinsubmit = '#signin_submit'


Cypress.Commands.add('visitZooplaHome' ,()  => {
    cy.visit('https://www.zoopla.co.uk/')
    cy.get(acceptallcookiesbutton).click()
  })
  
Cypress.Commands.add('login', (username, password) => {
    cy.get(signinbutton).click({force: true})
    cy.get(signinemail).type(username)
    cy.get(signinpassword).type(password)
    cy.get(signinsubmit).click({force: true})
  })
```

**Comment by jennifer-shehane** [comment] 2020-08-20 08:52
I can recreate this issue - this is caused when clicking the 'Save' button inside of the alert step where this button is.

<img width="802" alt="Screen Shot 2020-08-20 at 3 02 58 PM" src="https://user-images.githubusercontent.com/1271364/90745847-5db1ff80-e2f6-11ea-9f95-547c5d6baf2f.png">

Within this call is a call to set `top.location.href` to a url. This will call the topmost frame (Cypress's window) instead of the application under test. 

Duplicate of #8063

**Closed by jennifer-shehane** 2020-08-20 08:52 UTC
Labels: topic:  😳 whoops there is no test to run

**Comment by mylearning1005** [comment] 2020-08-20 11:30
@jennifer-shehane  is there a work around until this is fixed
