### ISSUE TITLE
'ERR_INVALID_ARG_TYPE' Cypress suddenly crashes 

### ISSUE THREAD

**Issue by srotak5** [cypress-io/cypress#16274] opened 2021-04-29 18:16 UTC
I had a test that worked since version 3.4 in the last few version this test started throwing   code: 'ERR_INVALID_ARG_TYPE'
if i used app it just crashed.

I tracked the problem. In some update this code stopped working 

```
 cy.get('[data-cy=form-text-area-comment]')
            .first()
            .type('Comment, test123, !"£$%^&*()')
            .should('have.value', 'Comment, test123, !"£$%^&*()');
```

The problem is the " in this part !"£$%^&*()
In some version Cypress started to take it as a string starter :D 

Console"
`TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (123)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:1496:27)
    at C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:545:23)
    at Immediate._onImmediate (C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (123)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:1496:27)
    at C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:545:23)
    at Immediate._onImmediate (C:\Users\Velky Modry\AppData\Local\Cypress\Cache\7.2.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
`

I can't really tell if it's a bug but this test string was working well in the past and i will miss my dear " . The sudden crash of the application is not ok.

Versions
Present version 7.2.0
Last working version was around 6 can't remember.

**Comment by jennifer-shehane** [comment] 2021-04-29 18:57
Duplicate of https://github.com/cypress-io/cypress/issues/16223

**Closed by jennifer-shehane** 2021-04-29 18:57 UTC
