### ISSUE TITLE
Unable to successfully request localhost within Cypress browser

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#1197] opened 2018-01-16 20:12 UTC
- Operating System: Windows 7
- Cypress Version: 1.4.1
- Browser Version: Chrome 60.0.3112.78

### Is this a Feature or Bug?
Bug

### Current behavior:
When making a cy.request() to localhost within the Cypress browser, the request consistently fails (404). Copying and pasting the localhost address directly in a new tab within the Cypress browser causes a redirect to a new IP which will also fail (500), with an ESOCKETTIMEDOUT error. This behavior only occurs within the Cypress browser, whereas localhost returns a successful response when inside of a normal Chrome browser window.

After reviewing similar issues, and inspecting the proxy settings for both the Cypress browser and the Chrome browser, there is a difference observed between the two.

### Desired behavior:
Making a cy.request() to localhost should return a successful response, if a successful request can be observed outside of the Cypress test suite.

### How to reproduce:

1. Note that making cy.request() of localhost in Cypress browser results in failure
2. Note that navigating directly to localhost in Cypress browser results in failure
3. Note that navigating directly to localhost in Chrome browser results in success

### Additional Info (images, stack traces, etc)

Cypress testing error
![cypress_dashboard](https://user-images.githubusercontent.com/2848185/35009607-14eba0f2-face-11e7-9b20-2229ee3e9e6e.PNG)

Cypress browser localhost response
![cypress_localhost](https://user-images.githubusercontent.com/2848185/35009629-25ee96f2-face-11e7-9eb7-d495df3d925b.PNG)

Cypress browser proxy info
![cypress_proxy](https://user-images.githubusercontent.com/2848185/35009644-34fcefea-face-11e7-87f9-2d2431693dea.PNG)

Chrome browser proxy info
![chrome_proxy](https://user-images.githubusercontent.com/2848185/35009649-3bde1708-face-11e7-9589-3563e308e10f.PNG)

Cypress settings
![cypress_settings](https://user-images.githubusercontent.com/2848185/35009656-4016c8ce-face-11e7-9138-c38a652ebb37.PNG)

**Comment by steveperrycreative** [comment] 2018-01-19 16:54
I'm not sure if this is the same issue but I get this grey screen with no test sidebar when using a local development URL.

URL being used is: http://cypress.localhost

I'm using MAMP Pro and can access the site in a standard browser (i.e. Chrome) but when I run Cypress I don't see the site.

Also see this Twitter thread:

https://twitter.com/stevemarkperry/status/954284397464899584

![dt5mixtwkaa22mg png-large](https://user-images.githubusercontent.com/2418930/35161856-5c55fb46-fd39-11e7-8181-667bf2ecf5bb.png)

**Comment by egucciar** [comment] 2018-01-19 17:17
I do have a different issue. Test runner loads et all. I think mines to do with Corporate proxy settings. I.e. test runner loaded just fine, but unable to access local host. I recommend opening seperate issue for yours, with the details of ur specs.

@steveperrycreative

**Comment by ndf** [comment] 2018-01-20 08:29
@steveperrycreative I think your issue is #451

**Comment by steveperrycreative** [comment] 2018-01-22 07:52
Thanks @egucciar.

Well spotted @ndf, thank you.

**Comment by bahmutov** [comment] 2018-01-22 14:12
marking as duplicate of #451

**Closed by bahmutov** 2018-01-22 14:12 UTC
Labels: stage: needs investigating

**Comment by egucciar** [comment] 2018-01-25 04:09
@bahmutov 

this is NOT a duplicate, there is NO domain name in my url browser ending in .localhost. See the error message / screenshots are completely different. Infact, the issue is with navigation to ANY website within the chrome browser, not just Localhost, but also Google Chrome etc.

This issue has been blocking all of my team members one by one for the past few months and im getting tired of asking them to re-image their machine when it happens (seems to be the only fix right now) Such an annoying waste of time

**Comment by ndf** [comment] 2018-01-25 08:17
Yes could be different @egucciar 
I pointed @steveperrycreative to #451 because his comment was exactly like that one.

@egucciar 
You seem to use "http://localhost:9006/auth/login" in one of your examples.
Is that the url that doesn't work in your cypress test suite?
In #451 we saw that urls that contain "local" and "localhost" specifically gave errors. And your url does contain "localhost".

Can you please specify exactly the url's that don't work?

Can you also play a bit with the configuration? Can you at least try a fully qualified url (http://my-test-suite.localhost:9006/auth/login) and a variation without local/localhost (http://my-test-suite.my-local-domain:9006/auth/login)?

If you still have this error without any reference of "local" or "localhost" in your url than please reopen this issue!

**Comment by egucciar** [comment] 2018-01-25 12:21
@ndf my cypress suite is working perfectly fine on my machine and others. Also as noted it's unable to go to any website even kitchen sink 

All urls are unavailable

**Comment by egucciar** [comment] 2018-01-25 13:55
I won't have the ability to debug this further today and the team I'm working with has a holiday tomorrow , but I'll check with more things once I have the time. I'd like to get resolved before Monday as this is blocking one of the primary devs in the project and testing is critical at this stage . Thanks for the insights and help .

**Comment by egucciar** [comment] 2018-01-29 17:16
@bahmutov 


![image](https://user-images.githubusercontent.com/2848185/35524021-3bfb0c12-04ee-11e8-9ce4-56901eff5fe6.png)

**Comment by helaaura** [comment] 2018-06-08 15:48
@egucciar Did you find a solution? I got the same error here:
![fullsizeoutput_673](https://user-images.githubusercontent.com/7725639/41167719-ad03fe2e-6b3b-11e8-844a-02c154ffdd31.jpeg)

**Comment by brian-mann** [comment] 2018-06-08 15:57
@helaaura that's not the same error, its a completely different error :P

@egucciar is that her server is returning a 503 response (which is on her end, not Cypress). Your problem is that your server is starting to respond but does not finish the response and thus we get ETIMEDOUT due to the response never finishing.

Do you have some sort of corporate proxy at work? Are you connecting over a VPN? Likely you have some non-standard networking in place between you and the server. We'd need a lot more details.

**Comment by san-ouadghiri** [comment] 2019-10-02 12:01
Just for future users ; I got this exact error @helaaura got (which is not the main topic of this thread I know). In case users ends up here for ETIMEDOUT here's a complementary feedback.

Produced ETIMEDOUT for me :
- I launched my tests (cypress open)
- I switched from my company network to a VPN one (as the test windows was open on 1 test with the previous execution results)
- I re-executed the test (using the "run all tests" top icon)
=> Got the error.

Does not produce ETIMEDOUT for me : 
- Close the test execution and the cypress open windows
- Switch from 1 network to another
- Re-execute cypress open
- Launch a test
Then the execution works just fine (no error).

So I'm guessing the cypress executed browser keeps some information that prevents us from network-switching between 2 executions with a proper relevant result. Hopefully this will help someone :).

**Comment by EmreCihanbeyoglu** [comment] 2021-07-05 10:19
I have the same issue. When I try to launch an internal application web side, I am getting 503 error. 

I am suspecting proxy settings. As far as I see, cypress is retrieving proxy bypass list automatically. My question is that: 
From where is it taking this bypass settings? 
Because in the test runner I cannot see all bypass addresses in the list. It might not have gotten the whole list. How can I import it manually?

![bpass-proxy-lis-cypress](https://user-images.githubusercontent.com/66699885/124454598-f58ecf80-dd88-11eb-924f-7e3329eb78ac.PNG)

**Comment by EmreCihanbeyoglu** [comment] 2021-07-05 10:20
I have solved this issue by adding my own bypass list into .nprmc file which Cypress is using while getting proxy settings.
