### ISSUE TITLE
Make caching Cypress binary in node_modules easier

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2634] opened 2018-10-22 10:51 UTC
Sometimes using a separate cache folder in the `$HOME` is not possible. Some CI's like Heroku CI only cache `node_modules` and that's it. So it would be nice to be able to download the binary into the local `node_modules` folder. 

I got this to work in https://github.com/cypress-io/cypress-example-kitchensink/pull/143 but it was non-obvious.

1. During the install I had to set environment variable `CYPRESS_CACHE_FOLDER=cache/Cypress`
2. During use I had to set environment variable `CYPRESS_CACHE_FOLDER=./node_modules/cypress/cache/Cypress npx cypress open`

I think it would be very nice

1. Remember where the binary was installed. Could be another JSON file in `node_modules/cypress` or right inside the `node_modules/cypress/package.json`
2. at least normalize how it finds the binary so we could use the same `CYPRESS_CACHE_FOLDER` during install and run. I think `CYPRESS_CACHE_FOLDER=node_modules/cypress/cache/Cypress` would be great

PS: we need documentation page for caching to cover more cases than https://github.com/cypress-io/cypress-documentation/pull/596/files covers (like GitLab CI example https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.gitlab-ci.yml) and also we need a redirect `https://on.cypress.io/caching`

**Comment by Bkucera** [comment] 2018-10-23 15:08
@bahmutov I see, so a problem is during install time, `CYPRESS_CACHE_FOLDER` is relative to `./node_modules/cypress/`, but during run-time, `CYPRESS_CACHE_FOLDER` is relative to project root?

**Comment by bahmutov** [comment] 2018-10-23 15:28
Yup

**Comment by turulb** [comment] 2019-02-19 17:26
I have the same problem.  Using the cypress/base:10 image as base, installed the cypress to it and tagged and pushed to my local repository.  I don't wanna install cypress during every test run, however, I cannot run it. I tried to add an alias to the /node_modules/.bin/cypress but still have the same error.
I tried to set  CYPRESS_CACHE_FOLDER to ~/.cache/Cypress, but still the same error using jenkins. 

This is a  blocker to me :(  so I would be very happy if you can help to solve this.

**Comment by Bkucera** [comment] 2019-07-12 20:09
> so a problem is during install time, CYPRESS_CACHE_FOLDER is relative to ./node_modules/cypress/, but during run-time, CYPRESS_CACHE_FOLDER is relative to project root?

Since this bug no longer exists I'm closing this issue

**Comment by eiswind** [comment] 2019-07-28 13:04
I still see this issue with 3.4.0

**Comment by Bkucera** [comment] 2019-07-28 14:22
@eiswind Interesting, I cant reproduce this is docker, but it may be some issue with Gitlab specifically, thanks for letting us know

**Comment by danielcaldas** [comment] 2019-09-05 19:51
Hey there. I updated to `cypress@3.4.1` and since then my travis CI is failing with something similar.
You can consult the pipeline full log here https://travis-ci.org/danielcaldas/react-d3-graph/jobs/580469437.

```
> export CYPRESS_SANDBOX_URL=http://127.0.0.1:8888 && cypress run
The cypress npm package is installed, but the Cypress binary is missing.
We expected the binary to be installed here: /home/travis/.cache/Cypress/3.4.1/Cypress/Cypress
Reasons it may be missing:
- You're caching 'node_modules' but are not caching this path: /home/travis/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/travis/.cache/Cypress
Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
Alternatively, you can run 'cypress install' to download the binary again.
https://on.cypress.io/not-installed-ci-error
----------
Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 3.4.1
```

**Comment by AshMcConnell** [comment] 2019-10-15 11:02
> I still see this issue with 3.4.0. It seems to work (on gitlab) with
> 
> ```
>   cache:
>      paths:
>         - cache/Cypress
>   script:
>     - 'export CYPRESS_CACHE_FOLDER=../../cache/Cypress'
>     - 'npm ci'
>     - 'export CYPRESS_CACHE_FOLDER=cache/Cypress'
>     - 'npm run ci'
> ```

Thanks, this worked for us.  (we are using `yarn` then `npx cypress run`).  I don't fully understand why it needs to be done though?

**Comment by Bkucera** [comment] 2019-10-15 15:09
I'll look into this

**Comment by AshMcConnell** [comment] 2019-10-21 10:29
Just to add, this seems to work between stages, but the caching doesn't work between pipelines for us.  I'm not sure why it's not picking up the binary

**Comment by bahmutov** [comment] 2019-10-21 19:40
I created an example project in https://gitlab.com/bahmutov/test-cypress-cache-in-node-modules

I think the best solution that matches the user's intuition would be:
- while running `postinstall` hook and installing binary detect if we are installing inside `node_modules/cypress` - this means we are installing Cypress binary as a dependency. In that case IF `CYPRESS_CACHE_FOLDER` is relative path, then use absolute path as `../..` + `CYPRESS_CACHE_FOLDER` to match human intution

**Closed** 2019-10-22 15:56 UTC
Labels: cli, stage: needs review
