### ISSUE TITLE
Inconsistent behaviour when the page has `window.onbeforeload` handler

### ISSUE THREAD

**Issue by buremba** [cypress-io/cypress#2674] opened 2018-10-30 00:43 UTC
### Current behavior:
When we run Cypress application on Mac and try running tests on a page that has `window.onbeforeload` handler, it works without an error but the console throws an error and the page doesn't show the confirmation prompt:
```
[Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808
```
However; when we run the test in CI, it fails to complete the tests and in Cypress UI it shows the runs as `Timed out` after 1 hour even though we have the following code before the tests:
```js
cy.on('window:confirm', (str) => {
        return true
 });
```
### Desired behavior:

If there a solution to make the behavior consistent, it should be implemented. If not, it should be documented. Also `window:confirm` doesn't seem to be working with `window.onbeforeload` so we failed to write tests for this particular page.

### Steps to reproduce:

Create a page that registers an handler to `window.onbeforeload` and try visiting an url after you're on this page.

### Versions

We use Cypress UI 3.1.0 on Mac and our CI tool is Wercker.

**Comment by jennifer-shehane** [comment] 2018-10-30 17:00
Related issue: https://github.com/cypress-io/cypress/issues/2482#issuecomment-423851175

**Comment by buremba** [comment] 2018-10-30 18:41
@jennifer-shehane  Unfortunately, the workaround on #2482 doesn't work for us because we also want to test the `onbeforeload` handler.

**Comment by smit9234** [comment] 2019-06-18 18:04
@jennifer-shehane 
Also running into the same issue when using the Electron Browser

Here is an example test case that enters data into a form then, when the second test tries to run Cypress just hangs, in the console output you can see the "blocked" beforeunload event.

I have tried all the workarounds but none of them seem to work.

```
describe('Generic Test', function() {
  context('Run some generic test', function() {
    it('should do something', () => {
      cy.visit('https://jsfiddle.net/sogata/Lx82optd/');
      cy.get('iframe[name="result"]').then(function($iframe) {
        const $body = $iframe.contents().find('body');
        cy.wrap($body)
          .find('input:eq(1)')
          .type('1222');
      });
    });

    it('should do something', () => {
      cy.visit('https://jsfiddle.net/sogata/Lx82optd/');
      cy.get('iframe[name="result"]').then(function($iframe) {
        const $body = $iframe.contents().find('body');
        cy.wrap($body)
          .find('input:eq(2)')
          .type('1222');
      });
    });
  });
});
```
![image](https://user-images.githubusercontent.com/7388782/59708020-c49acc80-91b8-11e9-8ae1-6fce048e08c6.png)

**Comment by archfz** [comment] 2020-01-18 17:07
I am also facing this issue with React Admin. I have a test spec with three it`s that first creates an entity then edits it and finally deletes it. It is failing at the last step, at delete test. In the console the error from the issue description appears. The only workaround seems to be a good amount of wait which is actually quite bothering.

**Comment by archfz** [comment] 2020-01-21 18:39
I had managed to resolve the problem by awaiting the call with cy.route for which the onbeforunload was registered.

**Comment by jennifer-shehane** [comment] 2020-01-30 05:45
Duplicate of https://github.com/cypress-io/cypress/issues/2118

**Closed by jennifer-shehane** 2020-01-30 05:45 UTC
Labels: stage: ready for work, type: bug
