### ISSUE TITLE
Ace editor (cloud 9) fails cy.type() with element is covered

### ISSUE THREAD

**Issue by harshithmullapudi** [cypress-io/cypress#1818] opened 2018-05-30 09:17 UTC
### Is this a Feature or Bug?

Cannot type in textarea using Cypress.

### Current behavior:

As it has cover of div elements cypress gives an error.

### Desired behavior:

Cypress should be able to type in the ace editor

![screenshot_20180530_145628](https://user-images.githubusercontent.com/17528887/40711800-c0ebdb06-6419-11e8-9e8e-ac11151ca14a.png)
This is the error that occurs if we use textarea with cypress type

**Comment by harshithmullapudi** [comment] 2018-05-30 09:27
![screenshot_20180530_145628](https://user-images.githubusercontent.com/17528887/40711800-c0ebdb06-6419-11e8-9e8e-ac11151ca14a.png)
This is the error that occurs if we use textarea with cypress type

**Comment by jennifer-shehane** [comment] 2018-05-30 09:48
You are using https://ace.c9.io/? Could you reproduce this issue, maybe trying to type on their example site, so that we have a reproducible example?

**Comment by harshithmullapudi** [comment] 2018-05-30 09:58
Yeah I have tried the same in website ( https://ace.c9.io/ ) and encountered the same problem 
Tried to type in textarea using the class of text area which is '.ace_text-input'
cy.get(".ace_text-input").first().type("#include")
And the cypress error is 
![screenshot_20180530_152637](https://user-images.githubusercontent.com/17528887/40713681-28472b9e-641e-11e8-9bac-83741e437eec.png)

**Comment by kartikupreti** [comment] 2018-06-05 01:04
yeah even I faced the same issue, but since I have it only in one text box I worked around as below- 
```
cy
      .window()
      .its('myjs.path.expressionEditor' as any)
      .invoke('value', 'text to be entered');
```

Hope it helps you

**Comment by Bkucera** [comment] 2018-06-29 14:29
this seems like a visibility bug, so I'm removing this from the `cy.type() improvements` epic.

**Comment by ronlawrence3** [comment] 2018-07-11 18:10
I had the thought to use cy.focused() to work around this issue...

Clicking on the ace editor, while this focuses the input in the real browser, seems to have no impact in cypress. 

So, I tried having my application expose a button to programatically bring up the editor's search dialog. Then I made cypress close it, which left the editor focused. then I used cy.focused() to type. 
This worked great, but only in chrome or electron, not in headless. 
Unfortunately, this will cause a failure in our CI system, so will not work.
 
Any other ideas for a workaround? I'm not sure how to use the window workaround above...

**Comment by jhoobergs** [comment] 2018-07-18 09:23
It works find by using {force: true} on the `type` command.

**Comment by Bkucera** [comment] 2018-07-18 12:01
@ronlawrence3 I'll look into the failure in headless, it's probably a window focus issue

**Comment by jennifer-shehane** [comment] 2019-06-11 11:02
This one is tricky. It actually is being covered by the other element, 

```
it('should type in input', function () {
  cy.visit('https://ace.c9.io/build/kitchen-sink.html')
  cy.get(".ace_text-input").first().focus().type("foo bar")
})

```

ace editor also has some fun focus logic of their own

```
    var focusEditor = function(e) {
        var windowBlurred = !document.hasFocus || !document.hasFocus()
            || !editor.isFocused() && document.activeElement == (editor.textInput && editor.textInput.getElement());
        if (windowBlurred)
            window.focus();
        editor.focus();
    };
```

**Comment by debel27** [comment] 2019-08-21 14:39
> This one is tricky. It actually is being covered by the other element,
> 
> ```js
> it('should type in input', function () {
>   cy.visit('https://ace.c9.io/build/kitchen-sink.html')
>   cy.get(".ace_text-input").first().focus().type("foo bar")
> })
> ```

It works perfectly for me! Thanks, I was banging my head against the wall with this

**Comment by Bkucera** [comment] 2019-08-29 17:56
closing this since it's not a visibility bug, and has a workaround.

**Closed by Bkucera** 2019-08-29 17:56 UTC
Labels: stage: needs investigating, topic: visibility 👁
