### ISSUE TITLE
Cypress.Cookies.debug(true) and setCookie doesn't work

### ISSUE THREAD

**Issue by scrat98** [cypress-io/cypress#1714] opened 2018-05-13 19:38 UTC
### Current behavior: 
When I enable cookies debug in support/index.js or in any test it doesn't log out into my console. And when setCookie - nothing happen
```js
Cypress.Cookies.debug(true)
```
```js
describe('Test', () => {
    Cypress.Cookies.debug(true);
    beforeEach(() => {
        cy.visit('http://localhost:8080');
        cy.clearCookies();
        cy.getCookies().should('be.empty');
        const value = 'test_value';
        const options = {
            path: '/',
        };
        cy.setCookie('token', value, options);
        cy.getCookie('token').should('have.property', 'name', 'token');

        cy.setCookie('refresh_token', value, options);
        cy.getCookie('refresh_token').should('have.property', 'name', 'refresh_token');

        cy.setCookie('expires', value, options);
        cy.getCookie('expires').should('have.property', 'name', 'expires');
        cy.clearCookies();
    });

    it('Test', () => {
        cy.log('Nothing log out');
    });
});
```
![image](https://user-images.githubusercontent.com/20593108/39987396-5a73d15c-576d-11e8-8629-da5ccb929361.png)
### Versions  
Cypress: 2.1.0
OS: Windows 10
Browser: Chrome 66/Electron

**Comment by scrat98** [comment] 2018-05-14 21:13
Here https://github.com/cypress-io/cypress/blob/2b2b6d99a9f1bf232d9c7396b25390913d5f2b18/packages/driver/src/cy/commands/cookies.coffee you use _.default - "This method mutates object.". So options was be mutate

**Comment by jennifer-shehane** [comment] 2019-07-23 11:30
Closing this as a duplicate of https://github.com/cypress-io/cypress/issues/2701

**Closed by jennifer-shehane** 2019-07-23 11:30 UTC
Labels: stage: needs investigating
