### ISSUE TITLE
Component tests not executing when clicking Run All on Cypress UI

### ISSUE THREAD

**Issue by azaeng04** [cypress-io/cypress#8839] opened 2020-10-14 08:53 UTC
### Current behavior
Cypress does not execute Component Tests as part of integration tests when clicking "Run All"

### Desired behavior
Cypress should Run All tests whether it is integration/component tests

### Test code to reproduce
Clone this repo: https://github.com/bahmutov/cypress-angular-unit-test/tree/master/examples/ng9
Start up cypress: `npm run cy:open`
Filter on a Component Test
Click "Run All"

The following error is shown:
![Screenshot from 2020-10-14 10-47-21](https://user-images.githubusercontent.com/13921692/95966057-f94d8100-0e0a-11eb-9ad7-f534716d5db7.png)

### Versions

Package.json dependencies at the time:
```
"dependencies": {
    "@angular/animations": "9.1.11",
    "@angular/cdk": "9.2.4",
    "@angular/common": "9.1.11",
    "@angular/compiler": "9.1.11",
    "@angular/core": "9.1.11",
    "@angular/forms": "9.1.11",
    "@angular/material": "9.2.4",
    "@angular/platform-browser": "9.1.11",
    "@angular/platform-browser-dynamic": "9.1.11",
    "@angular/router": "9.1.11",
    "core-js": "3.6.5",
    "primeng": "10.0.3",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.10",
    "@angular/cli": "9.1.10",
    "@angular/compiler-cli": "9.1.11",
    "@angular/language-service": "9.1.11",
    "@cypress/webpack-preprocessor": "^5.4.1",
    "@types/node": "~8.9.4",
    "angular2-template-loader": "0.6.2",
    "codelyzer": "^5.0.0",
    "cypress": "5.3.0",
    "cypress-angular-unit-test": "file:../..",
    "cypress-image-snapshot": "3.1.1",
    "html-loader": "1.1.0",
    "to-string-loader": "1.1.6",
    "ts-loader": "7.0.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
```

Chrome browser version: 86.0.4240.75 (Official Build) (64-bit)
OS: Ubuntu 20.04

**Comment by jennifer-shehane** [comment] 2020-10-14 23:53
Duplicate of https://github.com/cypress-io/cypress/issues/8203

**Closed by jennifer-shehane** 2020-10-14 23:53 UTC
