### ISSUE TITLE
Cypress reporting wrong "last-updated" duration in the UI

### ISSUE THREAD

**Issue by ns-abiramir** [cypress-io/cypress#26094] opened 2023-03-14 07:44 UTC
### Current behavior

Issue:

Cypress UI is reporting the wrong "last updated" time for the recently uploaded files.

I added a file recently. But the UI is displaying the last-updated time/duration of that file is "53 years ago".

### Desired behavior

It should display the proper time when the file added/updated.

### Test code to reproduce

Just update/add any files and see the last updated time.
![image](https://user-images.githubusercontent.com/118243773/224928113-514a5f62-4ec3-40ff-8e67-c9d83bdecff1.png)

### Cypress Version

12.4.1

### Node version

v14.17.0

### Operating System

Windows 10

**Comment by emilyrohrbough** [comment] 2023-03-14 18:48
Duplicate of https://github.com/cypress-io/cypress/issues/22188.

Closing in favor of https://github.com/cypress-io/cypress/issues/22188.

**Closed as not planned by emilyrohrbough** 2023-03-14 18:48 UTC
