### ISSUE TITLE
cy.wait(alias) for route can't get last one.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#7999] opened 2020-07-16 03:40 UTC
### Current behavior:

In some case, I only need check a route with first call and last call. And between the first and the last, maybe will call several times.

``` js
cy.server();

cy.route('/foobar**').as('foobar');

// app called "/foobar?page=1", check first one
cy.wait("@foobar").then(xhr->{
    // I got the first one xhr
})

... 
// with some code
// app called '/foobar**'  again with different param, "/foobar?page=2", bug I doesn't need check the second one
// with some code
...

// app called "/foobar?page=10", I want check last one, 
cy.wait("@foobar").then(xhr->{
    // **bug I got the second one's xhr: "/foobar?page=2"
})
```

### Desired behavior:

It looks like, cy.wait(alias) for route get 'alias' one by one. In my case, the workaround is wait all routes, or declare again.

Is it a function bug? And I feel it should wait the last.

### Versions

Cypress 4.10.0

**Comment by jennifer-shehane** [comment] 2020-07-16 09:22
There's not really a way to know what 'all' routes means here without explicitly defining how many times the XHR should go out and respond to Cypress. Essentially you may be interested in this feature: https://github.com/cypress-io/cypress/issues/4389

You can get the responses from all requests matching a route at any moment in time using `cy.get('@alias.all')` or get a specific request with `cy.get('@alias.num')`. So, if you want to say set the clock forward 5 minutes and then ensure that 5 XHR requests went out, you could do that. 

**This is undocumented and subject to change in a future release**

```js
cy.server();

cy.route('/foobar**').as('foobar');


cy.wait("@foobar").then(xhr->{
   // assert that it's the first request "/foobar?page=1"
})

// do all the other things to get to page 10

// 10 requests have gone out
cy.get("@foobar.all").should('have.length', 10)

cy.get("@foobar.9").then(xhr->{
  // assert on the 10th matching request: "/foobar?page=10"
})
```

Duplicate of #4389

**Closed by jennifer-shehane** 2020-07-16 09:22 UTC

**Comment by PengZhang2018** [comment] 2023-09-28 02:41
Hi @jennifer-shehane , is this cy.get('@alias.all') automatically wait for all requests get their responses? Or there is any additional configuration option I'm missing? In my case, after my app sent out the same request twice, cy.get('@alias.all') did return the information of 2 requests. But the 2nd one is without the response property as shown below.
![image](https://github.com/cypress-io/cypress/assets/40973678/38a6dcca-70f1-4b51-b041-9dbbe5886ab2)
