### ISSUE TITLE
Released in [`10.0.2`](https://on.cypress.io/changelog#10-0-2).

### ISSUE THREAD

**Issue by TahirMehmood8082** [cypress-io/cypress#26886] opened 2023-05-31 04:44 UTC
Released in [`10.0.2`](https://on.cypress.io/changelog#10-0-2).
This comment thread has been locked. If you are still experiencing this issue after upgrading to
Cypress v10.0.2, please open a new issue.
_Originally posted by @cypress-bot[bot] in https://github.com/cypress-io/cypress/issues/22034#issuecomment-1145433779_
----------------------------
![cypress-issue-01](https://user-images.githubusercontent.com/113116567/242160887-e79a9cfa-adbe-4151-98a6-cf4f3f78d980.png)

![cypress-issue-02](https://user-images.githubusercontent.com/113116567/242160931-3fdc843e-470f-4319-a39e-7a0fccec2703.png)
------------------------------------------------
still getting this issue in "12.13.0"

**Comment by nagash77** [comment] 2023-05-31 12:44
Hi @TahirMehmood8082 , Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by nagash77** [comment] 2023-06-07 13:47
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2023-06-07 13:47 UTC
