### ISSUE TITLE
could not find CRI target - Headless Chrome

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [cypress-io/cypress#6091] opened 2020-01-05 16:54 UTC
### Current behavior:
Trying to run my test specs using command **NODE_PATH=cypress cypress run --env configFile=staging --spec 'cypress/integration/stable/**/*' --headless --browser chrome**
without --headless everything works correctly

getting this kind of error: 
![image](https://user-images.githubusercontent.com/50987561/71783185-519a5b80-300d-11ea-9777-a738d2f1250f.png)
 I tried to resolve using **yarn cache clean**  & deleting node_modules folder - didn't help me
### Desired behavior:
continue my test run on headless mode

### Steps to reproduce: (app code and test code)
I guess this case doesn't need steps to reproduce (the problem not inside app code)

### Versions

Cypress 3.8.1
Mac OS Mojave
Chrome 79

**Comment by stefee** [comment] 2020-01-05 23:29
Possible duplicate of #6053

**Comment by jennifer-shehane** [comment] 2020-01-06 06:33
Closing as duplicate of https://github.com/cypress-io/cypress/issues/6053

**Closed by jennifer-shehane** 2020-01-06 06:33 UTC
