### ISSUE TITLE
 CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete. (gitlab headless)

### ISSUE THREAD

**Issue by sorind2010** [cypress-io/cypress#28051] opened 2023-10-13 08:35 UTC
### Current behavior

I run my tests headless in a gitlab CI/CD. After upgrading to Cypress from 12.14.0 to newer Cypress version, some tests started to fail with the error:

 CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

That is all I get on the console. No other messages. I have to rerun the test(s) in the GUI environment to see what really happened and to get the real error.

The above error is masking what is happening on test failure.

This error happens when during the test we click a button that would open a new tab in the browser. Most probably, Cypress switch focus on the new tab and it doesn't know to continue the test on the initial tab.

The problem goes away when I back-rev Cypress to version 12.14.0.

The issue doesn't happen when the test is run locally in GUI mode.

### Test code to reproduce

This error happens when during the test we click a button that would open a new tab in the browser. Most probably, Cypress switch focus on the new tab and it doesn't know to continue the test on the initial tab.

npx cypress run --config 'numTestsKeptInMemory=0' --browser chrome --headless --reporter mochawesome

### Cypress Version

all versions above 12.14.0

### Node version

20.6.1

### Operating System

Debian - 11.7

**Comment by jennifer-shehane** [comment] 2023-10-13 12:17
Hey @sorind2010, can you explain how this button is opening a new tab? Is it just a regular anchor link with target=_blank? What was the behavior in version 12? How was this test passing before? If you can send a reproduction or a snippet of test code that would help. 

We’ve had multiple reports of this bug happening more frequently in version 13 and I’m very interested in tracking it down. So far we haven’t been able to reproduce it.

**Comment by sorind2010** [comment] 2023-10-14 11:52
Hey Jennifer. This button opens a new tab and request an internal api call to the backend. The problem comes when the backend is not responding in 30seconds (I can see that the new tab has loading state). In that case cypress is failing do to a request timeout and the screenshot automatically fails. Just try to reproduce this scenario in headless mode

cy.get("button[title='Execute Endpoint']").click();

**Comment by bilarallen** [comment] 2023-10-16 01:35
Hi @sorind2010 are you using Cypress Cloud's test replay for this? If yes then we're encountering the same problem, you should try to disable the test replay in your project and re-run the test, if it passes there's some problem I guess with the test replay.

https://github.com/cypress-io/cypress/issues/5016#issuecomment-1758823882

**Comment by bilarallen** [comment] 2023-10-16 03:21
Hi, @jennifer-shehane I extracted the debug logs for my run where I also experienced this issue. I can't produce any reproducible code since I'm working with a private repository, here's the [link ](https://drive.google.com/file/d/1-KAdfwKBIW0J7LffqHg7cfqFBtOveA7a/view?usp=sharing) to the debug logs it's too long and huge to upload here so I just provided the link you can download. Thanks!

**Comment by bilarallen** [comment] 2023-10-18 09:13
any update on this?

**Comment by AlexSdet** [comment] 2023-11-02 16:29
any update on this?

**Comment by jennifer-shehane** [comment] 2023-11-02 18:54
@bilarallen @AlexSdet We'll need a reproducible example provided in order to investigate. Closing as duplicate of https://github.com/cypress-io/cypress/issues/5016

**Closed as completed by jennifer-shehane** 2023-11-02 18:54 UTC
Labels: type: duplicate
