### ISSUE TITLE
After update from 3.7.0 to 3.8.1, Cypress is having troubles finding elements that are visible on the UI

### ISSUE THREAD

**Issue by rickydidaravong** [cypress-io/cypress#6083] opened 2020-01-02 19:05 UTC
### Current behavior:  

Elements (e.g. buttons after page load) that appear visible are showing not visible by Cypress during a `cy.get()`.Prior to update Cypress 3.7.0 clicked on buttons just fine after page load. But a `{force: true}` does work but would rather verify that the button is visible first before clicking on the element. Clear Cypress cache made no different unless installing back 3.7.0 .

### Desired behavior: 

After page loads, buttons and all elements should be found with `cy.get` or `cy.find`.

### Steps to reproduce: (app code and test code)

Issue only started happening after upgrading from 3.7.0 to 3.8.1.

### Versions
Cypress 3.8.1

**Comment by scottcrowesai** [comment] 2020-01-02 22:39
Potentially duplicate of #5974 

@rickydidaravong TL;DR for that issues is that if the element or one of the parent's of the element includes `transform: translate(0, 0); height: 0;` in the style the overflow state isn't taken correctly into account for visibility.

**Comment by jennifer-shehane** [comment] 2020-01-06 07:02
This could be a duplicate, but there is zero chance of knowing without a reproducible example given. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Closed by jennifer-shehane** 2020-01-06 07:02 UTC
