### ISSUE TITLE
Unable to use Cypress.require within cy.origin

### ISSUE THREAD

**Issue by FlorianTopf** [cypress-io/cypress#25885] opened 2023-02-20 18:33 UTC
### Current behavior

I am trying to use `Cypress.require` which was released with 12.6.0 to be able to import external dependencies within a `cy.origin` callback. I am using cypress within an angular project using typescript 4.7.4.

According to the documentation this should work with any typescript module: 
https://docs.cypress.io/api/cypress-api/require

As soon as I start the test suite including a `Cypress.require` it immediately fails with: 
`Error: Cannot find module 'typescript'`

### Desired behavior

Absence of current behavior. `Cypress.require` should work as documented.

### Test code to reproduce

```typescript
// test.js
module.exports = {
    foo: 'bar',
};

// test.cy.ts
describe('Some test', (): void => {
   it('should work', (): void => {
      cy.origin('https://example.com', (): void => {
         const test = Cypress.require('./test.js');
         cy.log('test', test);
      });
   });
});

// cypress config
export default defineConfig({
    e2e: {
        baseUrl: 'http://0.0.0.0:4200',
        supportFile: 'cypress/support/e2e.ts',
        defaultCommandTimeout: 10000,
        video: false,
        experimentalOriginDependencies: true,
    },
});
```

### Cypress Version

12.6.0

### Node version

16.18.0

### Operating System

macOS 12.6.1

### Debug Logs

```shell
CypressError
cy.origin() failed to run the callback function due to the following error:



Processing the origin callback errored:



Error: Cannot find module 'typescript'

Require stack:

- /Users/floriantopf/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/cross-origin/process-callback.ts

    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)

    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)

    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)

    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)

    at PackherdModuleLoader.tryResolve (evalmachine.<anonymous>:1:727083)

    at resolve (evalmachine.<anonymous>:1:741891)

    at Function.resolve (evalmachine.<anonymous>:1:752340)

    at customRequire.resolve (<embedded>:5225:1350439)

    at _ (<embedded>:5166:22380)

    at <embedded>:5205:68107

    at a.handle_request (<embedded>:3012:1038)

    at i (<embedded>:3027:1285)

    at <embedded>:2627:2101

    at n (<embedded>:2608:1794)

    at p (<embedded>:2608:1813)

    at IncomingMessage.f (<embedded>:2608:2273)

    at IncomingMessage.emit (node:events:539:35)

    at endReadableNT (node:internal/streams/readable:1345:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)Learn more
```

**Comment by chrisbreiding** [comment] 2023-02-20 20:58
Sorry to see you're encountering an issue using `Cypress.require()`. I was able to reproduce the issue with the provided code. I'll route this to my team to investigate further.

**Comment by FlorianTopf** [comment] 2023-02-20 21:10
Thank you for the fast reply and for forwarding the issue to the team. I am glad to be able to contribute with a bug report on this recent version as I have a few use cases for this particular feature.

**Comment by mykhailosheptun** [comment] 2023-02-22 16:00
Have the same situation.Could be great to have answer for this)

**Comment by GabrielNastase** [comment] 2023-02-24 12:39
I'm seeing the same problem in the 12.6.0

**Comment by FranciscoKnebel** [comment] 2023-02-24 18:51
Getting this error since updating Cypress to 12.6.0, previously using require inside cy.origin was working, but now it forces an error, because Cypress.require got reinstated in 12.6.0.

Reverting back to 12.5.* should be the only solution for now.

**Comment by jokonimo** [comment] 2023-02-27 08:43
Is there an estimate when this will be fixed? Custom commands are unusable for us right now.

**Comment by kesirog** [comment] 2023-02-27 09:25
Just encountered this as well. 12.7

**Comment by HesterdeTester** [comment] 2023-02-27 13:15
I have this bug as well, both in 12.6 and in 12.7 unfortunately. Exactly the same situation as  described

**Comment by v7feng** [comment] 2023-02-28 03:04
I'm meeting the same issue with cypress 12.7.0

**Comment by luke-sensei** [comment] 2023-03-02 14:25
same issue with cypress 12.7.0, (adding experimentalOriginDependencies: true is enough)
sorry I spend more time on cypress itself than on my application tests, anyway...

**Comment by digitalgopnik** [comment] 2023-03-03 09:03
:+1: for @chrisbreiding with https://github.com/cypress-io/cypress/pull/25931

**Comment by chrisbreiding** [comment] 2023-03-03 16:05
This should be fixed by #25931 and out with the next release. Thanks for bearing with us as we work out the kinks in this experimental feature.

**Comment by simon-chen-1** [comment] 2023-03-07 16:09
Thanks @chrisbreiding! Any idea on when the next release is?

**Comment by chrisbreiding** [comment] 2023-03-07 16:48
Barring any unforeseen circumstances, the next release should be on March 14th.

**Closed as completed** 2023-03-08 21:25 UTC
Labels: type: bug, topic: cy.origin
