### ISSUE TITLE
cy.type() on time input does not fire change event in 3.5.0

### ISSUE THREAD

**Issue by pszalanski** [cypress-io/cypress#5488] opened 2019-10-28 10:01 UTC
### Current behavior:

`cy.type()` on an input with `type=time` manages to update the value of the input correctly. However, no `change` or `input` events are fired. Since our update to 3.5.0 from 3.4.

### Desired behavior:

A `change` eventhandler should be called.

### Steps to reproduce: (app code and test code)

Checkout my fork of cypress-test-tiny: https://github.com/pszalanski/cypress-test-tiny/tree/timepicker-change

### Versions

Cypress 3.5.0
Windows 10 x64

**Comment by dvic** [comment] 2019-10-28 13:28
Same for `type=date`, reported in #5476 with a reproducible test case

**Comment by dvic** [comment] 2019-10-28 13:29
@pszalanski by the way, you forgot to commit `timepicker.html` 🙂

**Comment by pszalanski** [comment] 2019-10-28 13:41
In some way I didn't 😉 You can navigate the site yourself and look at the source.

But I can put it here, as a comment:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Timepicker test</title>
</head>
<body>
    <input type="time" onChange="timeChanged(event);">
    <p>Time changed to <span id="target"></span></p>

    <script>
    function timeChanged(e) {
        document.getElementById("target").innerText = e.target.value;
    }
    </script>
</body>
</html>
```

**Comment by jennifer-shehane** [comment] 2019-10-28 14:13
The test you provided fails for me in both 3.4.1 and 3.5.0 on my osMac Mohave in Chrome 78. 

```js
it('fires change event on timepicker', () => {
  cy.visit('https://pszalanski.github.io/timepicker.html');
  cy.get('input').type('12:12');
  cy.get('#target').should('contain', '12:12'); // fails in both
})
```

<img width="687" alt="Screen Shot 2019-10-28 at 10 10 23 AM" src="https://user-images.githubusercontent.com/1271364/67685433-75855500-f96b-11e9-9fe9-f396246029a3.png">


Please provide an example of the exact bug introduced between the versions.

**Comment by Bkucera** [comment] 2019-10-28 19:55
duplicate of #5476

**Closed by Bkucera** 2019-10-28 19:55 UTC
Labels: stage: needs information
