### ISSUE TITLE
After upgrade 4.0.0 -> 4.1.0: cy.request broken

### ISSUE THREAD

**Issue by mduft** [cypress-io/cypress#6688] opened 2020-03-10 07:27 UTC
### Current behavior:

After updating from 4.0.0 to 4.1.0 a 'simple' cy.request no longer works:

```js
cy.request('POST', Cypress.env('backendBaseUrl') + '/auth', { user: user.user, password: user.pass })
```

It falsely performs a request to the URL '/POST', which was not the case if I rework the call to:

```js
cy.request({ method: 'POST', url: Cypress.env('backendBaseUrl') + '/auth', body: { user: user.user, password: user.pass }})
```

### Desired behavior:

*Both* versions should work, according to the signatures.

### Test code to reproduce

See example above.

### Versions

Cypress 4.1.0, Windows 10, NodeJS v12.16.1

**Comment by jennifer-shehane** [comment] 2020-03-10 08:25
I'm not able to reproduce what you are describing. This is a valid signature and issues a POST with a response in the example given below.

I tried with a `Cypress.env()` variable as well - also working.

```js
it('makes request', () => {
  cy.request('POST', 'https://jsonplaceholder.cypress.io/posts', {
    userId: 1,
    title: 'Cypress Test Runner',
    body: 'Fast, easy and reliable testing for anything that runs in a browser.',
  }).then((response) => {
    expect(response).property('status').to.equal(201) // new entity created
    expect(response).property('body').to.contain({
      title: 'Cypress Test Runner',
    })
  })
})
```

<img width="519" alt="Screen Shot 2020-03-10 at 2 52 03 PM" src="https://user-images.githubusercontent.com/1271364/76293045-bb213980-62de-11ea-937e-060492765992.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-03-10 08:25 UTC
