### ISSUE TITLE
Order of running global after block seem to be wrong

### ISSUE THREAD

**Issue by nagkumar** [cypress-io/cypress#19190] opened 2021-12-02 12:09 UTC
### Current behavior

[raja.pdf](https://github.com/cypress-io/cypress/files/7641639/raja.pdf)

support index code is this

![image](https://user-images.githubusercontent.com/332234/144418592-e8168de5-d61e-4f03-b1b6-cf635919b052.png)

Integration spec.ts is this

`import "cypress-audit/commands";

before(function ()
       {
	   cy.log('spec the before function')
       })

beforeEach(function ()
	   {
	       cy.log('spec the beforeEach function')
	   })

describe('My First Test', () =>
{
    before(function ()
	   {
	       cy.log('describe the before function')
	   })

    beforeEach(function ()
	       {
		   cy.log('describe the beforeEach function')
	       })

    it('it1', () =>
    {
	cy.visit('/')
    })

    it('it2', () =>
    {
	cy.visit('/owner')
    })

    it('it3', () =>
    {
	cy.visit('/')
    })

    afterEach(function ()
	      {
		  cy.log('describe the afterEach function')
	      })

    after(function ()
	  {
	      cy.log('describe the after function')
	  })
})

afterEach(function ()
	  {
	      cy.log('spec the afterEach function')
	  })

after(function ()
      {
	  cy.log('spec the after function')
      })`

When I run I see 

`AFTER EACH (1)
1
log
describe the afterEach function
AFTER EACH (2)
1
log
Index the afterEach function
AFTER EACH (3)
log
spec the afterEach function
`

I expect spec afterEach first and then global one i.e. Index afterEach..

The same order is lost even for after

![image](https://user-images.githubusercontent.com/332234/144418982-f4428194-80a1-4d1d-a875-5b133a91d7f4.png)

Is my understanding wrong i.e. I expect global **after** block to be executed **spec file global after**  similar block!!

### Desired behavior

Expect global after  in support index to be executed after spec file after

### Test code to reproduce

nil

### Cypress Version

9.1.0

### Other

Cypress version used is

![image](https://user-images.githubusercontent.com/332234/144419314-e9ba1c3c-c149-4be4-a05e-baa93bcdef7e.png)

**Comment by flotwig** [comment] 2022-02-03 21:56
Hooks like `afterEach` are run in the order of definition, so the global hook should indeed run first. This is designed this way so inner hooks can override the behavior of outer hooks by running last.

Closing because working as intended.

**Closed by flotwig** 2022-02-03 21:56 UTC
