### ISSUE TITLE
Detect Edge browser when using other install methods outside of Program Files. 

### ISSUE THREAD

**Issue by MehranShafqat** [cypress-io/cypress#6361] opened 2020-02-07 10:50 UTC
I just install cypress v4.0.0  cross browsers test run like Edge and Firefox. But in cypress dashboard im not able to see any other browser. Only chrome and electron browsers. 

How can I setup other browser? cypress will not detect other browsers automatically ? 

Edge and firefox browsers already installed. 

FireFiox installed path: `C:\Program Files\Mozilla Firefox`
Edge installed path:  `C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe`

![Screenshot_4](https://user-images.githubusercontent.com/50338287/74023020-7ee97900-49c0-11ea-825a-b393dfbcad3a.png)

Cypress version 4.0.0
OS : Windows 10

**Comment by natkrish** [comment] 2020-02-07 14:23
@MehranShafqat - You need to install FF 32 bit version and not 64 bit. ATM cypress 4 supports only 32bit. Please download 32 bit and cypress will definitely pick up. Also, try to install the latest edge version and it will also work fine. 
![image](https://user-images.githubusercontent.com/12541984/74037025-5a3bd400-49b5-11ea-891e-1763c7509d1d.png)

**Comment by wo-ist-henry** [comment] 2020-02-07 14:30
I had the same Issue, after I moved the Firefox installation to C:\Program Files (x86) it showed up in the Cypress Window.
But it won't run any Test, it fails with `Uncaught SyntaxError: invalid regexp group`.
Maybe this is a useful tip.

The Hint from @natkrish didn't worked for me, either.

**Comment by ghiscoding** [comment] 2020-02-07 16:18
@wo-ist-henry 
Just to point out that Firefox doesn't support Regex Lookbehind, there's an open [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665) for the Firefox browser while Lookbehind are supported in Chrome since version 62 and you can also see this [SO](https://stackoverflow.com/a/50011952/1212166) question for more info. You can also see in the [EcmaScript Kangax](https://kangax.github.io/compat-table/es2016plus/) table that Firefox still doesn't support it even though Chrome supports it since 2018 I think.

So you might want to check your code base (or Cypress tests) for any possible Regex Lookbehind, I had these kind of issues in a library that I made which is why your error is similar to what I had to debug myself.. 

Also from [TC39 Proposal](https://github.com/tc39/proposal-regexp-lookbehind)
> Positive lookbehind assertions are denoted as `(?<=...)` ... Negative lookbehind assertions are denoted as `(?<!...)`

So perhaps do a solution search in your code base..

**Comment by flotwig** [comment] 2020-02-07 17:22
Closing this since it appears to be a duplicate of #6355.

**Comment by MehranShafqat** [comment] 2020-02-09 12:21
@natkrish  well Edge is already installed by default in windows 10 but why cypress not able to detect it ?  we have to install it again from exe ?

**Comment by flotwig** [comment] 2020-02-09 14:50
@MehranShafqat currently Edge is only detected if installed in Program Files. I'll reopen this so we can add detection for other install methods.

**Comment by jennifer-shehane** [comment] 2020-02-10 06:41
Make sure to update to 4.0.1 to see what browsers are detected now as we improved some of the detection.

**Comment by jennifer-shehane** [comment] 2020-07-09 08:11
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-09 08:11 UTC
Labels: OS: windows, browser: edge, browser: firefox, stage: needs investigating, v4.0.0 :bug:
