### ISSUE TITLE
Error when opening Cypress

### ISSUE THREAD

**Issue by dackjaniels2001** [cypress-io/cypress#15304] opened 2021-03-03 16:14 UTC
Hi,

I have installed cypress on my Win 10 PC by using npm install inside a project directory.
If I run the command `npx cypress open` I get the following error:

```
It looks like this is your first time using Cypress: 6.6.0

  ×  Verifying Cypress can run C:\Users\Stephen.Edwards\AppData\Local\Cypress\Cache\6.6.0\Cypress
    → Cypress Version: 6.6.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed with UNKNOWN: C:\Users\Stephen.Edwards\AppData\Local\Cypress\Cache\6.6.0\Cypress\Cypress.exe --smoke-test --ping=392     
spawn UNKNOWN

----------

Platform: win32 (10.0.19042)
Cypress Version: 6.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hermes@0.0.0 cypress:open: `npx cypress open`
npm ERR! Exit status 1
```

I get the same error if I run the cypress executable in AppData\Local\Cypress (run as admin).

Any idea  what is going wrong here?
I am running 64bit Win 10, I wondered if the reference to Win32 in the error above might mean something?

Thanks

**Comment by jennifer-shehane** [comment] 2021-03-04 14:00
Can you follow this suggestion and let us know if it's resolved afterward? https://github.com/cypress-io/cypress/issues/5457#issuecomment-660775737

**Comment by dackjaniels2001** [comment] 2021-03-04 14:11
Hi,

Thanks for the suggestion but I already tried that and it made no difference.
I get the error if I execute the cypress .exe directly in windows too

**Comment by jennifer-shehane** [comment] 2021-05-27 15:25
Duplicate of https://github.com/cypress-io/cypress/issues/16647

**Closed by jennifer-shehane** 2021-05-27 15:25 UTC
Labels: stage: awaiting response
