### ISSUE TITLE
Allow visiting `about:blank` during test / before each / after each

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5510] opened 2019-10-29 09:35 UTC
### Current behavior:

`cy.visit('about:blank')` navigates to `http://url/base/about:blank`

### Desired behavior:

`cy.visit('about:blank')` navigates to `about:blank`

### Versions

3.4.1

### Background

In our application we register some listener on storage events. During before each cypress cleans the storage. This results into failing in our application, because our application is still running from the previous test case.
It should be possible to leave our application for example in after each by visiting `about:blank`.

I think the easiest way would be adding another option parameter to the visit command to skip adding base url to the target url:
https://github.com/cypress-io/cypress/blob/49f5b3e80c56e382b3cbd37c6deedda7389c32b7/packages/driver/src/cy/commands/navigation.coffee#L555-L563

Our current workaround is patching the register event listener method on `window:load`.

**Comment by jennifer-shehane** [comment] 2019-10-29 15:59
@CSchulz This is currently not possible. The only way to do this would be to have your webserver would need to serve an empty page that you could then visit. 

But we've discussed having Cypress serve a blank page so that you can reset things like this, something like `cy.reset()`

You *can* try using the test code below, but this may not perform the way you think it should exactly since there is still some persistence of state when visiting `about:blank` manually in this way.

```js
  cy.window().then((win) => {
    win.location.href = 'about:blank'
  })
```

**Comment by dbstraight** [comment] 2020-10-08 18:46
I just spent quite a while debugging a similar issue. It's very unexpected that the page from a previous test is still open causing things to happen and can fail the current test. Hugely in favor of a `cy.reset()`.

**Comment by c32hedge** [comment] 2020-12-30 18:33
A couple of other observations:

* The behavior the OP described seems consistent with what I've seen attempting to visit `about:blank` when the `baseUrl` configuration option is set--Cypress attempts to append `about:blank` onto the end of `baseUrl`.
* If I try `cy.visit('about:blank')` with `baseUrl` _not_ set, the error message is:
  ```
  cy.visit() failed trying to load:

  about:blank

  We attempted to make an http request to this URL but the request failed without a response.

  We received this error at the network level:

    > Error: Invalid protocol: about:

  Common situations why this would fail:
    - you don't have internet access
    - you forgot to run / boot your web server
    - your web server isn't accessible
    - you have weird network configuration settings on your computer
  ```
* If I try to visit a nonblank page (e.g. `www.cypress.io`) and then `about:blank`, Cypress thinks I'm trying to visit a different superdomain:
   ```
  cy.visit() failed because you are attempting to visit a URL that is of a different origin.

  The new URL is considered a different origin because the following parts of the URL are different:

    > protocol, superdomain

  You may only cy.visit() same-origin URLs within a single test.

  The previous URL you visited was:

    > 'https://www.cypress.io'

  You're attempting to visit this URL:

    > 'null'

  You may need to restructure some of your test code to avoid this problem.
  ```

And minimal reproducible example:

```
describe('about:blank', () => {
  it('just attempts to visit a blank page', () => {
    cy.visit('about:blank');
  });

  it('attempts to visit a blank page after visiting another page', () => {
    cy.visit('https://www.cypress.io');
    cy.visit('about:blank');
  });

  it('attempts to visit a blank page with baseUrl set', () => {
    Cypress.config('baseUrl', "https://www.cypress.io");
    cy.visit('about:blank');
  });
});
```

I'm curious how hard it would be for Cypress to just treat `about:blank` as a special case and not attempt to treat it as a network request?

**Comment by dbstraight** [comment] 2021-06-30 20:05
I'm still in favor of `cy.reset()`.

Because of https://github.com/cypress-io/cypress/issues/8679 combined with this issue, Cypress was making so many requests for an image that it actually got in between two immediately consecutive `setCookie` calls and put my application in an invalid state, failing the test.

So I finally made a route on my app that returns a totally blank page, but this is still a lurking footgun waiting to catch people unaware.

**Comment by jennifer-shehane** [comment] 2021-06-30 20:09
Our new cy.session feature will enforce visiting about:blank in between tests. https://github.com/cypress-io/cypress/issues/8301

**Comment by dbstraight** [comment] 2021-06-30 20:14
I only regret that I have but one heart emoji to react with.

🙇 🙇 🙇 🙇 🙇

**Comment by emilyrohrbough** [comment] 2022-11-16 21:34
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation). There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

Closing this issue as done and tagging for the v12.0.0 release.

**Closed by emilyrohrbough** 2022-11-16 21:34 UTC
Labels: type: feature, pkg/driver, stage: proposal 💡, v12.0 Release
