### ISSUE TITLE
cypress hangs when use cypress run command with network error

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress#7950] opened 2020-07-10 17:45 UTC
When I try to run my testing in jenkins, I found that the cypress hangs for very long time.   I used the jenkins pipeline with `cypress/included:4.9.0` image

```
cypress:network:connect received error on connect, retrying { 
  iteration: , 
  delay: 00, 
  err: Error: connect ETIMEDOUT 172.217.160.77:443     
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) { 
      errno: 'ETIMEDOUT', 
      code: 'ETIMEDOUT', 
      syscall: 'connect', 
      address: '172.217.160.77', 
      port: 443 
    } 
  } +33s
cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
cypress:server:util:process_profiler 
```

**Comment by ycwdaaaa** [comment] 2020-07-10 18:04
the command I use:
cypress run --record --key=281554e5-9eee-41bf-9f4c-e9cb405ed5a3 --ci-build-id jenkins-cess-ui-72 --parallel --spec cypress/integration/cases/test1.js --browser chrome

**Comment by ycwdaaaa** [comment] 2020-07-10 18:07
hangs and will not stop itself

![image](https://user-images.githubusercontent.com/18463029/87184739-21fd4080-c31b-11ea-960d-5eeb9782db5f.png)

**Comment by ycwdaaaa** [comment] 2020-07-10 18:20
more info:

defaultCommandTimeout: [33m10000[39m, chromeWebSecurity: [33mfalse[39m, baseUrl: [32m'http://172.27.65.237'[39m, env: { db: [36m[Object][39m, user: [36m[Object][39m, businessId: [33m1[39m, CACHE_FOLDER: [32m'/root/.cache/Cypress'[39m }, projectRoot: [32m'/home/jenkins/agent/workspace/cess-ui'[39m, projectName: [32m'cess-ui'[39m, morgan: [33mfalse[39m, isTextTerminal: [33mtrue[39m, socketId: [32m'rinmj'[39m, report: [33mtrue[39m, browsers: [ [36m[Object][39m, [36m[Object][39m, [36m[Object][39m ], port: [1mnull[22m, hosts: [1mnull[22m, userAgent: [1mnull[22m, reporter: [32m'spec'[39m, reporterOptions: [1mnull[22m, blacklistHosts: [1mnull[22m, clientRoute: [32m'/__/'[39m, xhrRoute: [32m'/xhrs/'[39m, socketIoRoute: [32m'/__socket.io'[39m, socketIoCookie: [32m'__socket.io'[39m, reporterRoute: [32m'/__cypress/reporter'[39m, ignoreTestFiles: [32m'*.hot-update.js'[39m, testFiles: [32m'**/*.*'[39m, requestTimeout: [33m5000[39m, responseTimeout: [33m30000[39m, pageLoadTimeout: [33m60000[39m, execTimeout: [33m60000[39m, taskTimeout: [33m60000[39m, video: [33mtrue[39m, videoCompression: [33m32[39m, videoUploadOnPasses: [33mtrue[39m, modifyObstructiveCode: [33mtrue[39m, waitForAnimations: [33mtrue[39m, animationDistanceThreshold: [33m5[39m, numTestsKeptInMemory: [33m0[39m, watchForFileChanges: [33mfalse[39m, trashAssetsBeforeRuns: [33mtrue[39m, autoOpen: [33mfalse[39m, viewportWidth: [33m1000[39m, viewportHeight: [33m660[39m, fileServerFolder: [32m'/home/jenkins/agent/workspace/cess-ui'[39m, videosFolder:

**Comment by jennifer-shehane** [comment] 2020-07-13 06:11
Can you access the domain normally, via curl within your environment? What is the result of running `curl yourdomain.com`? Can you access the domain via a normal [Node http.request](https://nodejs.dev/making-http-requests-with-nodejs) within the environment? Knowing the results of these will help narrow down if this is a network issue inside or outside of Cypress.

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

If you want these ANSCII characters removes from the logs, you can pass NO_COLOR as explained here btw https://on.cypress.io/continuous-integration#Colors

You should not share your record key in a public place. There are reasons why this key should be kept secret as explained here: https://on.cypress.io/projects#Record-key

**We strongly advise that you regenerate a new key since you have exposed your private record key.** Instructions here: https://on.cypress.io/projects#Create-new-record-key

**Comment by ycwdaaaa** [comment] 2020-07-14 08:30
yes, I can ping it and the curl and request can get the correct result.  even I can run the cypress on my mac or other server. But only in the docker container, it does not work.    and if I change the domain to google or other websit, it can work in docker container.  So I guess my website has some setting that the docker image cannot deal it. maybe the settings of browser?

**Comment by ycwdaaaa** [comment] 2020-07-15 09:13
it hangs and the log always output this:

**Comment by ycwdaaaa** [comment] 2020-07-15 09:13
2020-07-15T09:07:26.045Z cypress:server:server Got CONNECT request from accounts.google.com:443
2020-07-15T09:07:26.045Z cypress:https-proxy Writing browserSocket connection headers { url: 'accounts.google.com:443', headLength: 0, headers: { host: 'accounts.google.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' } }
2020-07-15T09:07:26.046Z cypress:https-proxy Got first head bytes { url: 'accounts.google.com:443', head: '\u0016\u0003\u0001\u0002\u0000\u0001\u0000\u0001�\u0003\u0003o�\u0000Ե�\u0011(,�\u0000�ͪ�P�\u0002~�\b����Z1�\u0001n� G�\b|�ȈX���\u0002�\tT㔵�?�PU9�' }
2020-07-15T09:07:26.046Z cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' }
2020-07-15T09:07:26.047Z cypress:server:server HTTPS request does not match URL: https://accounts.google.com:443 with props: { port: '80', tld: '172.27.65.237', domain: '' }
2020-07-15T09:07:26.047Z cypress:https-proxy Making connection to accounts.google.com:443
2020-07-15T09:07:26.047Z cypress:https-proxy getting proxy URL { port: 443, serverPort: 39818, sniPort: 33892, url: 'https://accounts.google.com:443' }
2020-07-15T09:07:27.484Z cypress:network:connect received error on connect, retrying { iteration: 0, delay: 0, err: Error: connect ETIMEDOUT 172.217.24.13:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) { errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect', address: '172.217.24.13', port: 443 } }
2020-07-15T09:07:35.862Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:

**Comment by andrew-leonard** [comment] 2020-07-20 22:39
Had similar issue 

cypress debug logs here https://github.com/andrew-leonard/cypress-log/blob/master/cypress-debug.log

**Comment by ycwdaaaa** [comment] 2020-07-21 05:01
@jennifer-shehane Is there any update?

**Comment by jennifer-shehane** [comment] 2021-02-26 23:56
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by jennifer-shehane** 2021-02-26 23:56 UTC
Labels: stage: needs information
