### ISSUE TITLE
Cypress support for iFrame [Logs preview & Debugging]

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress#16621] opened 2021-05-21 12:17 UTC
### What would you like?
As a end user, I want Cypress to handle iFrame, as it handles for sections outside iFrame (Specifically logs).

**Description:**

1. In general when we run our test cases using test runner we see the logs on left and its preview on right window.
2. After execution is complete. We can hover over the logs and see the execution preview one by one.
3. There is also a feature, If I pin a particular step in the log, I can debug using console (As it shows request and response for that particular step).

Now take any application that is entirely under an iFrame. And try to use the default Cypress feature of hovering over logs. You won't be able to see the preview. Debugging is also difficult.

Cypress by default supports iFrame to its full capacity.
No need for plugins to handle iFrames.
Cypress supports iFrames for logs preview & debugging (Just as it does for a web app without iFrame).

### Why is this needed?
All modern webapps are using iFrames extensively. At some point you will have to bring it to support your existing features.

**Comment by jennifer-shehane** [comment] 2021-05-21 14:28
Duplicate of https://github.com/cypress-io/cypress/issues/136

We're currently working on this feature as shown in our roadmap: https://on.cypress.io/roadmap

**Closed by jennifer-shehane** 2021-05-21 14:28 UTC
