### ISSUE TITLE
Unexpectedly exiting with signal SIGSEGV since 8.6.0 version

### ISSUE THREAD

**Issue by SantiagoSM** [cypress-io/cypress#18681] opened 2021-10-28 13:21 UTC
### Current behavior

Since cypress 8.6.0 upgrade, I'm experiencing aleatory errors in my pipelines, sometimes works fine until the end, and sometimes not. The error is the next:

`The Test Runner unexpectedly exited via a exit event with signal SIGSEGV`

I also started to see this  error at the logs, but seems to work ok sometimes, so I'm no prety sure is the route cause of this:

`[6606:1028/125808.622484:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`

The only pissible solution for those issues is downgrading to cypress 8.5.0, and in this version everything works fine for me.

### Desired behavior

I don't know how I can upgrade cypress and maintain the 8.5.0 behaviour.

### Test code to reproduce

**cypress.json:**
{
  "viewportWidth": 1920,
  "viewportHeight": 1080,
  "video": false,
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "cypress/results/test-results.[hash].xml",
    "toConsole": true
  },
  "pageLoadTimeout": 120000,
  "retries": {
    "runMode": 2,
    "openMode": 2
  },
 }

**package.json**
    "@cypress/skip-test": "^2.6.1",
    "cypress": "8.7.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-grep": "^2.5.1",
    "cypress-wait-until": "^1.7.1",

### Cypress Version

8.6.0 and 8.7.0

**Comment by smasala** [comment] 2021-11-01 14:47
Getting this too

**Comment by sampadaz** [comment] 2021-11-01 17:33
I was getting this with 8.7.0, so downgraded to 8.6.0. It worked for a day or two with downgrade and again started failing today with same error. With not much information on console, its hard to know what the real issue is. Has anyone been able to figure out what is the root cause and able to continue with one specific version of cypress?

**Comment by slumbering** [comment] 2021-11-18 13:06
Same issue with Cypress 9.0.0

**Comment by tihmatsumoto** [comment] 2021-11-18 13:22
Happening while using GH actions and sometimes, a run hangs for +6 hours, even though all tests were complete. Not sure how to solve it except for downgrading to 8.5

**Comment by korgon** [comment] 2021-11-19 21:45
I also am forced to use 8.5.0 due to this issue after having tried 9.0.0, 8.7.0 and 8.6.0. Only happens in GH actions - no problems locally.

**Comment by edenhermelin** [comment] 2021-11-24 10:22
happens also on the latest version..

**Comment by chuckstock** [comment] 2021-12-06 15:45
Confirming that this is still happening on latest issue.

**Comment by cubanx** [comment] 2021-12-07 20:23
Happens inside our docker runs as well. Mine always seems to have the error:
`Failed to connect to the bus: Address does not contain a colon`

Right before it fails. And it doesn't always fail on the same spec.

**Comment by Develliot** [comment] 2021-12-09 18:08
I'm getting the same as @cubanx I'm downgrading to 8.5

**Comment by mellis481** [comment] 2021-12-10 20:39
Also experiencing this with version 8.7.0. I will mention that I'm also using `cypress-wait-until` same as the author.

**Comment by marlonmarcello** [comment] 2021-12-13 18:52
Can confirm, same issue on `v9.1.1`

**Comment by barbaracassani** [comment] 2021-12-15 19:40
Same with `v8.7.0` .

**Comment by emilyrohrbough** [comment] 2021-12-15 22:22
`SIGSEGV ` means a signal for memory access violation, trying to read or write from/to a memory area that your process does not have access to. This error message alone doesn't provide enough information to investigate the issue.

For those of you who have experienced this issue, can you:
- provide a link to build failure?
- provide slimmed reproducible example? 
- define what CI system(s) & OS you are using

**Comment by emilyrohrbough** [comment] 2021-12-15 22:32
Duplicate of #18464. Closing in favor #18464 which has provided more information thus far. Please add additional information that PR to help us pin-point the issue.

**Closed by emilyrohrbough** 2021-12-15 22:32 UTC
Labels: stage: needs information

**Comment by saadidrees711** [comment] 2021-12-28 12:59
@emilyrohrbough you can find the failed github actions here with a public repo.

[https://github.com/AltaPay/plugin-magento2-community/runs/4531990642?check_suite_focus=true](https://github.com/AltaPay/plugin-magento2-community/runs/4531990642?check_suite_focus=true)
