### ISSUE TITLE
Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for Sandboxed iFrames

### ISSUE THREAD

**Issue by nileshpandey3** [cypress-io/cypress#16262] opened 2021-04-29 01:35 UTC
Similar issue: https://github.com/cypress-io/cypress/issues/5722

I see that you are using an older version of Cypress. Can you update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you?

Probably the structure of the URL is important here. Can you give an example of what it looks like? Like... https://test.app.domain.uk ?

_Originally posted by @jennifer-shehane in https://github.com/cypress-io/cypress/issues/8883#issuecomment-712242503_

**Comment by nileshpandey3** [comment] 2021-04-29 01:38
I am referencing the above open issue and posting something similar which I am facing when trying to create a test which logs-in to a public website using cypress. I am able to manually loginto the website but during autoamted test it fails with an error message `Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for Sandboxed iFrames`

```
Cypress package version: 7.2.0
Cypress binary version: 7.2.0
Electron version: 12.0.0-beta.14
```

**Comment by jennifer-shehane** [comment] 2021-04-29 15:43
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Could you provide a screenshot of the full error and where it is being displayed?

We'll have to close this issue without that as there's no path forward to investigate.

**Comment by nileshpandey3** [comment] 2021-04-29 23:06
@jennifer-shehane  Yes sure. Please find the issue details below

### Test code

```
describe('Airtable Onboarding test', () => {
    it('Visits home page', () => {
      cy.visit('https://airtable.com')
    })
```

### Issue:

- The page loads but I see an error in the devtools as attached below
- I can automate actions on this website but when I try to go cross origin e.g. Sign-up/sign-in then this error doesnt allow me to test the functionality, which I am guessing is due to the same origin policy limitation.
- I have already tried disabling security check for chrome but it doesn't work
```
Cypress package version: 7.2.0
Cypress binary version: 7.2.0
Electron version: 12.0.0-beta.14
```

### Screenshots

![image](https://user-images.githubusercontent.com/15132522/116628667-77372c80-a904-11eb-8562-6a22c775708e.png)

**Comment by nileshpandey3** [comment] 2021-04-30 23:37
@jennifer-shehane  Any suggestions please? 🙏

**Comment by jennifer-shehane** [comment] 2021-05-05 16:42
I see the application under test is setting `document.domain`. This is deprecated - you can see an explanation as to why under the Deprecation heading: https://developer.mozilla.org/en-US/docs/Web/API/Document/domain

This error throws within Cypress because it's within a sandboxed iframe. Is this functionally causing your application to not be testable? Outside of seeing the error in the console, can you provide a failing test case?

**Comment by flotwig** [comment] 2022-02-03 21:24
Closing due to lack of response. Please open a new issue if this is still happening.

**Closed by flotwig** 2022-02-03 21:24 UTC
Labels: stage: needs information

**Comment by aruns05** [comment] 2022-11-02 11:41
I am getting this even having the cypress 10.2. The browser is chrome. Can @jennifer-shehane please help

**Comment by devanshitrivedi** [comment] 2022-11-16 22:26
Facing the same issue

**Comment by pvogel2** [comment] 2023-02-03 10:41
Hi there, 
experienced the same issue with a sandboxed iframe, but after a while I found this experimental config flag for cypress (Version 12.5.1): 

experimentalSkipDomainInjection (see https://docs.cypress.io/guides/references/experiments)

Using this config (available for e2e tests only) cypress skips the document.domain manipulation and no error occurs.
