### ISSUE TITLE
Can't test Social Authentication with Google

### ISSUE THREAD

**Issue by PavelRybalko** [cypress-io/cypress#26192] opened 2023-03-23 08:51 UTC
### Current behavior

After entering email I get the error "This browser or app may not be secure."
![image](https://user-images.githubusercontent.com/60709039/227149099-ce9bc5e0-851f-4c84-b2fc-bf2cc8b60314.png)

### Desired behavior

After entering email I can enter the password and pass Social Authentication

### Test code to reproduce
```js
import { domain as Auth0Domain } from '../../src/auth_config.json'

function logIntoGoogle(username: string, password: string, name: string) {
  Cypress.on(
    'uncaught:exception',
    (err) =>
      !err.message.includes('ResizeObserver loop') &&
      !err.message.includes('Error in protected function')
  )
  cy.visit('http://localhost:3000')
  cy.get('#qsLoginBtn').click()

  cy.origin(Auth0Domain, () => {
    cy.scrollTo('bottom')
    cy.get('form[data-provider="google"]').submit()
  })

  cy.origin(
    'https://accounts.google.com',
    {
      args: {
        username,
        password,
      },
    },
    ({ username, password }) => {
      Cypress.on(
        'uncaught:exception',
        (err) =>
          !err.message.includes('ResizeObserver loop') &&
          !err.message.includes('Error in protected function')
      )

      cy.get('input[type="email"]').type(username, {
        log: false,
      })
      cy.contains('Next').click().wait(4000)
      cy.get('[type="password"]').type(password, {
        log: false,
      })
      cy.contains('Next').click().wait(4000)
    }
  )

  cy.get('h6.dropdown-header').should('contain', name)
}
```
### Cypress Version

12.8.1

### Node version

18.14.0

### Operating System

Windows 10 19044.2364

### Other

i use code for testing Google auth from cypress documentation (https://docs.cypress.io/guides/end-to-end-testing/social-authentication#docusaurus_skipToContent_fallback)

**Comment by AtofStryker** [comment] 2023-03-23 13:31
Closing as a duplicate of #24139

**Closed as completed by AtofStryker** 2023-03-23 13:31 UTC
