### ISSUE TITLE
cy.screenshot chained from an element within shadowDom throws maximum call stack exceeded error

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#1832] opened 2018-05-30 18:20 UTC
### Is this a Feature or Bug?

Bug

### Current behavior:

![image](https://user-images.githubusercontent.com/2848185/40739485-5b56df34-6414-11e8-9e21-ea91195fc0ee.png)

### Desired behavior:

It should work...please :)

### Steps to reproduce:

* Create a custom command or `.then` to grab an element from shadowDom since cypress commands do not natively work with shadowDom
* Chain `.screenshot` from the yielded subject.

### Versions

3.0.0

**Comment by chrisbreiding** [comment] 2018-05-30 19:04
Unfortunately, Cypress doesn't have any support for shadow DOM yet, so this will happen with commands outside of `.screenshot()` as well. 

I'm going to close this as it's essentially a duplicate of https://github.com/cypress-io/cypress/issues/144.

**Closed by chrisbreiding** 2018-05-30 19:04 UTC

**Comment by chrisbreiding** [comment] 2018-05-30 19:10
A workaround for the time being: take a fullPage capture (or a viewport capture if the element fits in the viewport), determine the position and size of the element, and use the `clip` option of `.screenshot()` to crop out the element.

**Comment by jennifer-shehane** [comment] 2020-06-09 08:58
We've added experimental shadow DOM support through the `experimentalShadowDomSupport` configuration option. (Big thanks to @43081j!)

To use it, update to Cypress 4.8.0 and pass the following to your configuration file or however you pass in configuration. 

```json
{
  "experimentalShadowDomSupport": true
}
```

See the [Experiments](https://on.cypress.io/experiments#Cross-boundary-selectors) for more information including how to use the new `.shadow()` command and `includeShadowDom` option.

This is still experimental, so we'd like your help working through any bugs or unexpected behavior before releasing into the main product. If you encounter any issues using the new experimental shadow DOM feature, please **[open a new issue](https://github.com/cypress-io/cypress/issues/new)**, filling in the issue template and providing a reproducible example.
