### ISSUE TITLE
Issue unit testing with nextjs and absolute imports

### ISSUE THREAD

**Issue by bscaspar** [cypress-io/cypress#20487] opened 2022-03-04 18:53 UTC
### Current behavior

We use a simple `tsconfig` with `baseUrl: "."` so all our imports are relative to the root of the project, like `import Button from "components/Button"`. No issues with integration tests. However, when running a unit test and importing a simple function from a file that has other relative imports (like `import {anotherUtil} from 'utils/someOtherUtils'`, Cypress does not understand this relative import. 

The error message looks like: 
```
Error: Webpack Compilation Error
./utils/someMath.ts
Module not found: Error: Can't resolve 'utils/addTwoNumbers' in '/Users/bradycaspar/code/test/cypress-next/utils'
resolve 'utils/addTwoNumbers' in '/Users/bradycaspar/code/test/cypress-next/utils'
  Parsed request is a module
  using description file: /Users/bradycaspar/code/test/cypress-next/package.json (relative path: ./utils)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
[/Users/bradycaspar/code/test/cypress-next/utils/node_modules]
[/Users/bradycaspar/code/test/node_modules]
[/Users/bradycaspar/code/node_modules]
[/Users/node_modules]...
```
The error message makes it sound like it is searching for this import in `node_modules` and nowhere else.

This works if the import is removed from the file or the import format changes to `import Button from './Button'`. However if possible I'd prefer to not change the imports across the whole app 😄 

### Desired behavior

The imports with the format we use are found as expected.

### Test code to reproduce

I created a minimal repro here: https://github.com/bscaspar/cypress-next-import-error-example.

### Cypress Version

^9.5.1

### Other

 Am I missing a simple config? Any help is appreciated!

**Comment by lmiller1990** [comment] 2022-03-15 19:49
Interesting, will need to dig into this one - I'll try and spend some time before the end of the month. I'm wondering if this is something we need to do in our nextjs dev server implementation.

Thanks for the repro!

**Comment by feRpicoral** [comment] 2022-04-15 05:17
Same here. I've tried to use `babel-plugin-tsconfig-paths` through `babelify` but it didn't work:

```ts
// cypress/puglins/index.ts
const browserify = require('@cypress/browserify-preprocessor');

module.exports = (
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
) => {
  require('@cypress/code-coverage/task')(on, config);

  const options = {
    ...browserify.defaultOptions,
    typescript: require.resolve('typescript')
  };

  const babelify = options.browserifyOptions.transform[1][1];

  const plugins = [
    require.resolve('babel-plugin-istanbul'),
    [
      require.resolve('babel-plugin-tsconfig-paths'),
      {
        rootDir: config.projectRoot
      }
    ]
  ];

  babelify.plugins.unshift(...plugins);

  on('file:preprocessor', browserify(options));

  return config;
};
```
If I remove the file preprocessor completely I can run the tests with no problems, but I'm trying to add code coverage reports to my unit tests and it turned out way more difficult than it was supposed to be.

Do we have any updates on this @lmiller1990?

**Comment by bscaspar** [comment] 2022-04-15 15:55
Turns out I made a mistake with my `tsconfig` which @leosuncin helped spot - I simply had to change `baseUrl` in the `tsconfig` to the root of the project, which in this case meant updating it from `"baseUrl": "."` to  `"baseUrl": ".."` since my `tsconfig` was located in the `/cypress` dir. Not sure if this will solve your issue @feRpicoral, possibly something different!

**Comment by feRpicoral** [comment] 2022-04-15 18:01
> Turns out I made a mistake with my `tsconfig` which @leosuncin helped spot - I simply had to change `baseUrl` in the `tsconfig` to the root of the project, which in this case meant updating it from `"baseUrl": "."` to `"baseUrl": ".."` since my `tsconfig` was located in the `/cypress` dir. Not sure if this will solve your issue @feRpicoral, possibly something different!

Unfortunately, that did not solve my problem, but thanks for sharing what worked for you!

After some experimentation, I found out that if I change line 29 on `node_modules/@cypress/browserify-preprocessor/lib/simple_tsify.js` from
```js
const text = chunks.join('')
```
to
```js
const text = chunks
    .join('')
    .replaceAll('@helpers', path.join(process.cwd(), 'src', 'helpers'))
    // in my case I'm trying to import from @helpers which is a tsconfig path for src/helpers
```
it works as expected.

What I think I will do is write a custom plugin based on `simple_tsfy,js` and use it to transpile the typescript code instead of using this one that comes with cypress.

**Comment by lmiller1990** [comment] 2022-04-20 01:15
Sorry, I've not been tracking this issue. We are in the process of updating our Next.js plugin to work with v11 and v12 with more thorough code around the various edge cases. This should be released w/ Cypress 10 (next few weeks).

In the meantime: it seems you found a workaround? Also, any particular reason to use the browserify plugin when Next.js is using webpack?

**Comment by feRpicoral** [comment] 2022-04-20 03:23
> Sorry, I've not been tracking this issue. We are in the process of updating our Next.js plugin to work with v11 and v12 with more thorough code around the various edge cases. This should be released w/ Cypress 10 (next few weeks).
> 
> 
> 
> In the meantime: it seems you found a workaround? Also, any particular reason to use the browserify plugin when Next.js is using webpack?

Looking forward for this next release with better support for Next 12!

Yes, I did found a workaround - I ended up writing a custom transformer for browserify. Regarding why I'm using it, I have no particular reason - I was following the official docs on how to have coverage reports for both my unit & integration tests.

**Comment by lmiller1990** [comment] 2023-02-22 05:12
Cypress 10 introduced a lot of changes and fixed many issues with dev servers. 

The current version is Cypress 12 - I'm not sure if this is still an issue or not, but the reproduction is far enough behind at this point that I think it makes sense to close this one off. If someone finds a similar issue, please make a new issue demonstrating with the latest Cypress (Cypress 12) and we can triage it. Also, I think Next 13 (and 14) has come out since this issue was filed, so it's possible something was fixed on their end, too.

We've got a better process around issue triage now, so it should be fairly prompt.

**Closed by lmiller1990** 2023-02-22 05:12 UTC
Labels: stage: backlog, CT
