### ISSUE TITLE
cypress runner stuck while executing the test 

### ISSUE THREAD

**Issue by shubham-lagshetti** [cypress-io/cypress#22709] opened 2022-07-07 11:55 UTC
### Current behavior

current behaving becasue of test script in which i used three for loops to some validation so it not working ,cypress runner stuck while executing the test and entire runner i have to restart again but i tried it not working event after restarting the runner and vs code also.

### Desired behavior

i  am expecting it should execute the test event with having three for loops inside the test script but it is not working i dont know what is the issue with the code or loops i dont know .

### Test code to reproduce

 for(let i=5;i<9;i++)
        {
            cy.get('#mat-slide-toggle-'+i+'-input').should('be.disabled')
        }
        for(let j=1;j<=4;j++)
        {
            cy.get('#mat-input-'+j).should('be.disabled')
        }
-------------here it is faling once i add this for loop with variable k then its is behaving like that if i comment this block then it is working fine so i am not able to find the issue 
        for(let k=13;k<=25;(k+4))
        {
            //cy.get('#mat-input-1').should('be.disabled')
            cy.get('#mat-select-value-'+ k).should('be.disabled')    
        }

### Cypress Version

10.0.3

**Comment by SondreElg** [comment] 2022-07-07 14:42
You're missing an '=' sign when updating the k variable in the last loop, leading to an infinite loop.
Working code would be:
```
for(let k=13;k<=25;(k+=4))
{
//cy.get('#mat-input-1').should('be.disabled')
cy.get('#mat-select-value-'+ k).should('be.disabled')
}
```

I would advice against how you're testing your application though, as your tests will break quickly if you make changes to the website. If possible, getting the parent objects of the different objects you're checking and checking if their children are disabled would be more robust to change.

**Comment by shubham-lagshetti** [comment] 2022-07-08 05:08
thanks for response @SondreElg  i found the other solution by getting its all child element and did the assertion so it is working now.

**Comment by hthetiot** [comment] 2022-07-11 00:27
Close the issue pls @shubham-lagshetti, your issue was not a bug, your code was the issue. You can help maintainers by closing your issue, so that they can focus on real tasks. Thank.you.

**Closed** 2022-07-13 05:00 UTC
Labels: stage: investigating
