### ISSUE TITLE
[Bug] Simple tests fail randomly

### ISSUE THREAD

**Issue by pgroot91** [cypress-io/cypress#1849] opened 2018-06-01 11:07 UTC
### Current behavior:

- Tests passes
or
- Tests fail randomly clicking on menu items due elements not visible?

![image](https://user-images.githubusercontent.com/6934501/40838082-ead35b2c-659c-11e8-9670-0cfaa9df2131.png)

How the test(s) look like:

```js
it('Audiences > Source audiences', function () {
	cy.get('li[id="mainMenu:Audiences"]').should('be.visible').click()
	cy.get('li[id="mainMenu:SourceAudiences"]').should('be.visible').click()
        cy.url().should('eq', 'https://domain.com/audiences')
	cy.get('h1[id="screen-title"]').should('have.text', 'Your audiences')
	cy.get('h4[id="screen-subtitle"]').should('have.text', 'Manage & create your source audiences')
})
```
or even when i run the test like this the same bevavior

```js
it('Audiences > Source audiences', function () {
	cy.get('li[id="mainMenu:Audiences"]').click()
	cy.get('li[id="mainMenu:SourceAudiences"]').click()
        cy.url().should('eq', 'https://domain.com/audiences')
	cy.get('h1[id="screen-title"]').should('have.text', 'Your audiences')
	cy.get('h4[id="screen-subtitle"]').should('have.text', 'Manage & create your source audiences')
})
```
Also happening when running headless mode.

### Desired behavior:

Tests should always pass since the snapshots are showing the elements just fine? 
Sometimes the elements seems not to be recognized as visible in cypress GUI.

### Versions

Cypress: 3.0.0 / Windows 10

**Comment by pgroot91** [comment] 2018-06-07 10:38
Like to comeback to this issue. 

I applied now simply a cy.wait between the menu items and than it works flawlessly. 

I'm scratching my head on this one i thought cypress would wait for elements to be there? Now i'm asking myself does Cypress not wait for elements to be visible and speed the test up to make the test fail?

**Comment by pgroot91** [comment] 2018-06-08 07:17
I solved this by adding cy.wait() between the navigation. It takes around +/- 3 times longer for the full test to run, but at-least the tests are all passing now! The cause of the test randomly failing seems to be the loading time of iframe(s) on those pages. When the iframe is not completely loaded test(s) fails.

**Comment by tonykaram1993** [comment] 2018-06-29 23:15
Same thing happens to me however not sure if we have the same issue. I have a test that if ran 10 times, would fail 2 out of those 10 times. The test always fails at the same place, if cy.wait() is added those fails are greatly reduced.

**Comment by jennifer-shehane** [comment] 2018-12-26 07:42
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?

**Comment by TobiContinued** [comment] 2019-02-11 08:10
I also have random errors in the test. The problem is, its random, so reproducing is hard :)
But i reduced the rate of fails with a timeout set to 30 sec, but i still have some issues, randomly.

**Comment by pgroot91** [comment] 2019-02-11 10:22
Sorry for not coming back to this issue. Didn't dived into it yet! 

But in one of the recent release/changelog this issue seems to be resolved.

**Comment by jennifer-shehane** [comment] 2019-04-25 08:28
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 08:28 UTC
Labels: stage: needs information, topic: visibility 👁, type: bug

**Comment by TheDutchCoder** [comment] 2020-06-29 21:41
I keep on having the same issues.

The great thing is my tests pass just fine locally, but on Buildkite is suddenly pretends to not be able to detect a `.should('not.be.visible')` (while the element literally is not visible) and complains about an "overlaying element", which doesn't exist.

It only fails in 1 test, yet I do the same test twice (it only ever fails the second time).

I'm starting to get the feeling it's somehow caching DOM fragments or something, because I'm all out of explanations.

And because the error is incorrect (it's doesn't seem to reflect the real state of the DOM), it's impossible to debug.
