### ISSUE TITLE
Can't save the cypress screenshots in higher resolution in jenkins pipelines

### ISSUE THREAD

**Issue by KWorke** [cypress-io/cypress#5201] opened 2019-09-25 14:00 UTC
Is there a way to enlarge failure screenshot image ? the default is width="1050" and height="932" (I mean the output image, not viewport).
as you can see the screenshot isn't spread on the entire page
<img width="1674" alt="Screen Shot 2019-09-25 at 16 17 25" src="https://user-images.githubusercontent.com/44168974/65607854-e4ab0a80-dfb5-11e9-8132-9bc47747eea5.png">

**Comment by jennifer-shehane** [comment] 2019-10-07 20:36
The screenshot is taken at the width of your browser window - which is also potentially restricted by the size of the screen the machine you are running within. We can only take a screenshot of the actual pixels on the screen - upscaling it to a higher resolution would just be manipulating the original screenshot. 

Also, the size of the Command Log on the left size will be whatever you had the Command Log width set to if you ran `cypress open` locally on that machine before. 

Closing this as a duplicate of https://github.com/cypress-io/cypress/issues/2102

**Closed by jennifer-shehane** 2019-10-07 20:36 UTC
