### ISSUE TITLE
cy.visit and non-idempotent event and task handlers

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#26613] opened 2023-04-27 20:56 UTC
### Current behavior

Given that `baseUrl` undefined and a test that visits a domain, any domain, the `before:spec` event is emitted twice. Furthermore, any test that subsequently visits another domain will further ensure that `before:spec` is emitted, despite this all happening in a single spec. Additionally, every task executed previous to a call to `cy.visit`, will be invoked again. Or in other words, the whole test is re-run for all practical purposes.

### Desired behavior

Event and task handlers aren't necessarily idempotent and there doesn't seem to be a way of detecting that a test is being ran again, aside from tracking state among event handlers.

### Test code to reproduce

https://github.com/badeball/reproducible-issues/tree/master/cypress/origin-behavior

### Cypress Version

12.11.0

### Node version

v18.8.0

### Operating System

Arch Linux

**Comment by mschile** [comment] 2023-04-28 20:38
Hi @badeball 👋, thanks for logging this issue! This is definitely unexpected behavior. I am going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/26300.

**Closed as not planned by mschile** 2023-04-28 20:38 UTC
