### ISSUE TITLE
cy.route merge response with stubbed response

### ISSUE THREAD

**Issue by plehnen** [cypress-io/cypress#3932] opened 2019-04-10 12:06 UTC
### Current behavior:

Currently we can choose between stubbing (inline or by fixture) or getting the original response.

### Desired behavior:

Sometimes it is desired just to change on specific aspect of the response.
e.g. change a value, add a value, or remove a value.

For this, currently we have to re-build ALL whats in the response. If this response will be changed later, the fixtures have to be changed as well, or will include outdated stuff.
And the fixtures will be very verbose, even if it is just one changed entry out of hundreds.

It would be nice to have a way to modify the response within `cy.route`.

```js
      cy.server();
      cy.route({
        method: 'GET',
        url: '**/api/init**/**',
        onResponse: (xhr) => {
          xhr.response.body.authenticated = false;
          xhr.response.body.messages.de.internalstock.optional_override_label_for_xyz = 'custom value xyz';
          return xhr; // RETURN MODIFIED RESPONSE
        }
      }).as('init');
```

### Versions
3.2.0, Windows 10, Chrome

**Comment by jennifer-shehane** [comment] 2019-04-11 08:21
Duplicate of https://github.com/cypress-io/cypress/issues/521

**Closed by jennifer-shehane** 2019-04-11 08:21 UTC
