### ISSUE TITLE
intellisense not woking in VS Code 

### ISSUE THREAD

**Issue by inamdararvind11** [cypress-io/cypress#16200] opened 2021-04-26 08:25 UTC
I have followed all the steps mentioned in docs(https://docs.cypress.io/guides/tooling/IDE-integration#Writing-Tests) but still autocomplete/intellisense is not working.

VS code details: 
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

Also similar ticket is already logged and its still in open state.
https://github.com/cypress-io/cypress-documentation/issues/3075

**Comment by jennifer-shehane** [comment] 2021-04-26 14:25
Duplicate of https://github.com/cypress-io/cypress-documentation/issues/3075 as mentioned this is outside of the product itself: https://github.com/cypress-io/cypress-documentation/issues/3075#issuecomment-674709748

**Closed by jennifer-shehane** 2021-04-26 14:25 UTC
