### ISSUE TITLE
Sync vs Async

### ISSUE THREAD

**Issue by margusp2heathmont** [cypress-io/cypress#6736] opened 2020-03-16 11:02 UTC
Hello!

This report is related to how Cypress handles Promises. It think the approach is old-school "make things sync", but it introduces a lot of non-intuitive issues.

As a developer, who can write JavaScript and understands async/await/Promises/generators - I feel, that Cypress makes things more complex than they should be.

I make an example:

```javascript
makeDeposit = async ({ userId: userId, amount: amount }) => {
  const result = await http.post({ userId: userId, amount: amount });
  cy.log("result was", result);
  return result;
}
```

```
cy.log
``` 
will error with "argument needs to be promise".

Yes, I understand, I should use 
```cy.request```
, but this means, that I can not use existing libaries from within my helper functions.

So, it would be totally awesome, if standard JS and Cypress would look alike.

**Comment by bahmutov** [comment] 2020-03-16 13:58
If you have a Promise-returning helper function, just wrap it so Cypress waits for it, see here https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/logging-in__using-app-code

**Comment by jennifer-shehane** [comment] 2020-03-16 15:17
Duplicate of #1417

**Closed by jennifer-shehane** 2020-03-16 15:17 UTC
