### ISSUE TITLE
Chrome hangs when copying text to clipboard

### ISSUE THREAD

**Issue by ncjones** [cypress-io/cypress#2739] opened 2018-11-08 00:30 UTC
### Current behavior:

Clipboard does not work in Chrome launched by Cypress:

 * clipboard copy shortcut (`⌘+C`) causes Chrome to hang
 * edit->cut/copy and debugger "copy as cURL" menu options do not modify system clipboard contents

### Desired behavior:

Clipboard should work as normal when interacting with Cypress Chrome instance.

### Steps to reproduce:

Select any text anywhere in a Chrome instance launched by Cypress (text on a page, console/debugger output, location bar, chrome preferences etc) then hit `⌘+C`.

### Versions

 * Cypress 3.1.1
 * macOS 10.13.6
 * Chrome 70.0.3538.77 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment] 2019-01-28 09:04
I'm not able to reproduce this at all. 

You are doing this copy/paste manually right? Not writing tests for cypress to do this? Could you record a video/gif of what you mean? Perhaps I'm not doing exactly what you're doing.

**Comment by ncjones** [comment] 2019-02-12 20:49
Yes you have understood the issue correctly. I don't think adding a video is going to add any value here. None of my team mates can reproduce this error either (all on Mac).

**Comment by bohendo** [comment] 2019-03-12 03:30
This might be related, I'm getting stuck after clicking a button that's supposed to copy to the clipboard. I know issue #311 is tracking copy/paste support and I'm fine if the copy function is a no-op for now but I'd still like to be able to click this button w/out needing any human interaction to move on to the next part of the test afterwards.
<img width="860" alt="Screen Shot 2019-03-12 at 8 57 39 AM" src="https://user-images.githubusercontent.com/8527067/54172712-01ae3f00-44a5-11e9-9117-1a2346bce2ae.png">

**Comment by jennifer-shehane** [comment] 2019-04-25 09:00
All I can suggest is to ensure you have all extensions disabled when trying the keyboard shortcut - it may be localized somehow to your machine since no one else is experiencing this exact behavior.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 09:00 UTC
Labels: stage: needs information

**Comment by tzimmermann** [comment] 2019-06-04 07:45
@bohendo Are you using [copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard), by chance?
I stumbled upon the same behaviour in my app, and found that copy-to-clipboard has a fallback mechanism that will display exactly this alert box if it finds that `execCommand` does not work (as appears to be the case within cypress).

So I guess we need to wait until https://github.com/cypress-io/cypress/issues/2851 is fixed.

**Comment by bohendo** [comment] 2019-06-06 08:19
@tzimmermann Good call, I'm actually using `react-copy-to-clipboard` but it uses `copy-to-clipboard` under the hood. I'll keep an eye on #2851 👍

**Comment by mxrguspxrt** [comment] 2019-06-20 11:50
+1

**Comment by CoryDanielson** [comment] 2019-10-08 13:30
If the copy-to-clipboard functionality is not important to what you are testing, you can stub out window.prompt so that your test will run without interruption.

https://docs.cypress.io/api/commands/stub.html#Replace-built-in-window-methods-like-prompt
```
	// Disable window prompt which is used in link creation by copy-to-clipboard library
	// This prompt pauses test execution during `cypress open`
	cy.window().then(win => {
		cy.stub(win, 'prompt').returns('DISABLED WINDOW PROMPT');
	});
```

You could probably also store the value passed to the prompt in a `clipboard` variable and read from it later on in your test.

**Comment by cesarlima-hotmart** [comment] 2019-12-04 20:15
It worked for me. Hope it helps.
https://github.com/sudodoki/copy-to-clipboard/issues/88

**Comment by ivanmjartan** [comment] 2022-05-10 08:28
I have solution, copy-to-clipboard library do document.execCommand("copy") and this has to be in callback.  

For my solution help use https://github.com/dmtrKovalenko/cypress-real-events#readme library and invoke button that do copy like ... 


cy.get(selector).realClick();

**Comment by Yangfan2016** [comment] 2022-08-10 12:14
Chrome version 87 with Cypress default Electron is OK

But there is a problem with the selection of Chrome 104. It seems that the new version limits the ability to copy scripts to the clipboard.

**Comment by jenishgandhi7** [comment] 2022-08-10 16:20
> I have solution, copy-to-clipboard library do document.execCommand("copy") and this has to be in callback.
> 
> For my solution help use https://github.com/dmtrKovalenko/cypress-real-events#readme library and invoke button that do copy like ...
> 
> cy.get(selector).realClick();

@ivanmjartan Thank you, your solution help me and working for me

**Comment by romanesss** [comment] 2024-03-21 22:01
> I have solution, copy-to-clipboard library do document.execCommand("copy") and this has to be in callback.
> 
> For my solution help use https://github.com/dmtrKovalenko/cypress-real-events#readme library and invoke button that do copy like ...
> 
> cy.get(selector).realClick();

Thanks!
