### ISSUE TITLE
Cypress 3.1.0 syntax errors

### ISSUE THREAD

**Issue by maamounapprise** [cypress-io/cypress#2357] opened 2018-08-16 13:59 UTC
### Current behavior:

I keep getting SyntaxError in all the files since I upgraded to 3.1.0 when I downgrade everything works fine. 

E.g: 
```
export const color: { [string]: string } = {
```

### Versions

cypress 3.1.0

**Comment by bahmutov** [comment] 2018-08-16 14:00
We need a repo to reproduce this error

**Comment by jennifer-shehane** [comment] 2018-08-16 14:02
Looks like duplicate of this issue: https://github.com/cypress-io/cypress/issues/2350

But yes, more information on your set up will help us track this down.

**Closed by jennifer-shehane** 2018-08-16 14:02 UTC
Labels: type: duplicate
