### ISSUE TITLE
flaky page load timeouts

### ISSUE THREAD

**Issue by tracykm** [cypress-io/cypress#6612] opened 2020-03-02 16:46 UTC
### Current behavior:
```
CypressError: Timed out after waiting '60000ms' for your remote page to load.

Your page did not fire its 'load' event within '60000ms'
```
I've been having a lot of issues with flaky tests, especially when run headlessly. The app I'm testing is very complex firing a lot of ajax calls and re-rendering tons of times, so it has been hard to isolate. But here I've found one example of a reliable fail. Running a simple stubbed example fails after a slightly more complex test.
<img width="670" alt="Screen Shot 2020-03-02 at 10 24 52 AM" src="https://user-images.githubusercontent.com/2788860/75695693-1b293780-5c70-11ea-975c-011be1be6c47.png">
<img width="439" alt="Screen Shot 2020-03-02 at 10 54 43 AM" src="https://user-images.githubusercontent.com/2788860/75698446-59285a80-5c74-11ea-8794-a48da70f6b6c.png">

### Desired behavior:
identical tests should all pass, the page load event should fire

### Test code to reproduce
`npm run cypress:run` in this repo:
https://github.com/tracykm/cypress-test-tiny

### Versions
Cypress 4.1.0, macOS Catalina, Chrome

**Comment by jennifer-shehane** [comment] 2020-03-03 08:56
This is actually only happening in the Electron browser, not Chrome. You can see this by calling `cypress open` and selecting 'Electron' or running `cypress run` (which defaults to Electron). 

If you open the DevTools while running `cypress open` and selecting Electron, you can see an error in the console warning that the `beforeunload` confirmation panel has been blocked.

<img width="1405" alt="Screen Shot 2020-03-03 at 3 23 58 PM" src="https://user-images.githubusercontent.com/1271364/75758874-0aa5b980-5d63-11ea-9ad7-1b82a0bc88fc.png">

>[Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808

Duplicate of #2118 

See this comment for existing workarounds: https://github.com/cypress-io/cypress/issues/2118#issuecomment-580095512

**Closed by jennifer-shehane** 2020-03-03 08:56 UTC
