### ISSUE TITLE
response to XHR request ignored by cypress

### ISSUE THREAD

**Issue by fmezas** [cypress-io/cypress#5000] opened 2019-08-18 22:18 UTC
### Current behavior:

XHR GET request reaches server and browser reports response (http code 200) in developer console but Cypress continues waiting for a response (see spinner next to `(XHR)` step in test and timeout message for `cy.wait` command)

![image](https://user-images.githubusercontent.com/540110/63231058-d1449c80-c1ca-11e9-9fe8-4b53aa7c6cc4.png)

### Desired behavior:

Cypress should recognize that a response to the request was received and continue with the test.

### Steps to reproduce: (app code and test code)

You can use https://github.com/fmezas/cypress-xhr-issue to reproduce the issue. It contains a toy server, client and cypress test, and instructions on how to run

### Versions

Cypress: `3.4.1`
operating system: `OS-X 10.14.6`
browser: `Chrome Version 76.0.3809.100 (Official Build) (64-bit)`

**Comment by Pieras2** [comment] 2019-08-19 10:10
In my case I don't even see the XHR request in developer console while using chrome inspector I see it on my tested page :(

**Comment by fmezas** [comment] 2019-08-21 04:53
hi @jennifer-shehane . Apologies for pinging you directly but desperate times call for desperate measures :)

any chance this issue could get some attention? it looks like a very basic use case to me. All code needed to reproduce it is in the accompanying github repo

any advise appreciated

best

Francisco

**Comment by mpahuja** [comment] 2019-08-30 08:53
it looks like `@hello` has been setup to wait for `hello` route but that route does not exist on the page being loaded. If this was an actual route `cy.visit('http://localhost:8000/hello');` and page to visit then cypress would have worked fine. 

This code right now does not seem to be doing anything.
```
  cy.server();
  cy.route({
    method: 'GET',
    url: 'http://localhost:3000/hello'
  }).as('hello');
```
And also this line: `  cy.wait('@hello');`

Removing those lines should work

**Comment by fmezas** [comment] 2019-09-02 15:28
@mpahuja `@hello` is an alias for the route defined in the excerpt you quote. The url point to this: https://github.com/fmezas/cypress-xhr-issue/blob/1091f04be61c59a6237c4d1df48b6758a4ca5d58/server/server.js#L22

`cy.wait('@hello')` just makes the issue more explicit. without it the code fails in exactly the same way

**Comment by fmezas** [comment] 2019-09-02 15:30
anybody else around here trying to use cypress with a cycle.js app?

**Comment by fmezas** [comment] 2019-09-02 20:29
hi @bahmutov 

apologies for pinging you directly. any chance this issue could get some attention? looks like a straightforward use case to me. All code needed to replicate the issue is in the accompanying repo. I guess the most important thing at this point for me is to figure out whether the combination cypress + cycle.js is viable or not yet

any advise highly appreciated

best regards

Francisco

**Comment by jennifer-shehane** [comment] 2020-07-10 05:14
I am able to reproduce this - even in our latest version of Cypress from the provided repo: https://github.com/fmezas/cypress-xhr-issue

**Comment by jennifer-shehane** [comment] 2020-12-28 07:38
This is fixed with our new [`cy.intercept()`](https://on.cypress.io/intercept) command - which is intended to replace `cy.route()` in a future version. We suggest updating your `cy.route()` code to use `cy.intercept()` instead. 

### cy.route()

```js
it('works', () => {
  cy.server();
  cy.route({
    method: 'GET',
    url: 'http://localhost:3000/hello'
  }).as('hello');

  cy.visit('http://localhost:8000/');
  cy.get('#button1').click();
  cy.wait('@hello', { timeout: 10000 });
  cy.contains('"ok":true');
});

```

<img width="667" alt="Screen Shot 2020-12-28 at 2 07 33 PM" src="https://user-images.githubusercontent.com/1271364/103198167-1546c600-4916-11eb-96cb-46d684a9e03d.png">

### cy.intercept()

```js
it('works', () => {
  cy.intercept({
    method: 'GET',
    url: 'http://localhost:3000/hello'
  }).as('hello');

  cy.visit('http://localhost:8000/');
  cy.get('#button1').click();
  cy.wait('@hello');
  cy.contains('"ok":true');
});
```

<img width="681" alt="Screen Shot 2020-12-28 at 2 05 52 PM" src="https://user-images.githubusercontent.com/1271364/103198120-f3e5da00-4915-11eb-9c13-d3816a7a4e88.png">

**Closed by jennifer-shehane** 2020-12-28 07:38 UTC
Labels: stage: needs investigating, type: bug
