### ISSUE TITLE
browser reopens after user clicks the close button

### ISSUE THREAD

**Issue by ionutiug4** [cypress-io/cypress#28969] opened 2024-02-19 13:26 UTC
### Current behavior

when you open a browser from the cypress debug window, and you click on the close button in the cypress runner, the browser automatically reopens

### Desired behavior

in this situation, in previous Cypress builds, the browser remained closed

### Test code to reproduce

run > npx cypress open in the Cli, select E2E testing, select a browser to open(i selected Chrome browser), wait for the browser to open, click on the close button in the cypress runner 

### Cypress Version

13.6.4

### Node version

20.9.0

### Operating System

Windows 11 23H2, OS build 22631.3155

**Comment by jennifer-shehane** [comment] 2024-02-19 16:24
Duplicate of https://github.com/cypress-io/cypress/issues/28852 This will be fixed in our next release.

**Closed as not planned by jennifer-shehane** 2024-02-19 16:24 UTC
Labels: type: duplicate
