### ISSUE TITLE
react-select v2 dropdown issues

### ISSUE THREAD

**Issue by cjlitch** [cypress-io/cypress#1486] opened 2018-03-22 00:39 UTC
- Operating System: Local: Mac OS High Sierra 10.13.3, CI: Travis (Open source -- https://travis-ci.org)
- Cypress Version: 2.1.0
- Browser Version: Local: Chrome 65.0.3325.181 

### Is this a Feature or Bug?
I think it's a bug, but it may be my mistake.

### Current behavior:
The test that fails is clicking a dropdown and then trying to select an element in that dropdown. It is using a third party open source dropdown component, [react select](https://github.com/JedWatson/react-select). Running this test locally, it passes over and over. I have not witnessed the test failing locally. Running the test through CI, it has failed every time. The video recordings on my Cypress dashboard suggest that the dropdown is never opening as a result of clicking on the element. I have two other tests in my test suite which both pass reliably on CI.

### Desired behavior:
I would like the test pass on CI just as it does locally.

### How to reproduce:
I have an open source repository where I am trying to add cypress. Here is the pull request: 
* https://github.com/cjlitch/screenshot-test-app/pull/15.

Here is the latest commit where you should be able to clone and reproduce the issue:
* https://github.com/cjlitch/screenshot-test-app/tree/20fdd95168b3febd76863251a697b544bf299e5c. 

Here is the relevant Cypress test: 
* https://github.com/cjlitch/screenshot-test-app/blob/20fdd95168b3febd76863251a697b544bf299e5c/cypress/integration/e2e-cypress.js#L17

#### Failing on CI
![image](https://user-images.githubusercontent.com/4774423/37744837-c6f67b54-2d47-11e8-9f7b-8b72e8eeaf04.png)

#### Passing Locally
![image](https://user-images.githubusercontent.com/4774423/37744848-d5b30b8a-2d47-11e8-99bb-8a0c0c89762f.png)

**Comment by jennifer-shehane** [comment] 2018-03-22 15:16
I notice that the `XHR` in the log is responding at a different time when running in CI. Probably unrelated. 

Can you try running `cypress run --browser chrome` and see if it passes? Would narrow down is Electron is the issue.

**Comment by cjlitch** [comment] 2018-03-22 15:51
Thanks for looking @jennifer-shehane 

Running that command locally, the tests do pass, and they pass in CI! 🎉 Screenshots and links to Travis run below.

Any advice on using electron so I can keep the recordings is welcome.

### Local
![image](https://user-images.githubusercontent.com/4774423/37779761-91832e96-2dc3-11e8-9dfa-f47a59e822db.png)

### CI
https://travis-ci.org/cjlitch/screenshot-test-app/builds/356933260?utm_source=github_status&utm_medium=notification
![image](https://user-images.githubusercontent.com/4774423/37780227-b1816950-2dc4-11e8-8d99-07867283e9a7.png)

**Comment by jennifer-shehane** [comment] 2018-03-22 16:16
Yeah, so I would try running the tests from the GUI, locally and selecting to run them in Electron. See if there are any console errors or anything that is obvious in there as to why it is failing. Electron is technically using Chrome 59 - and you are likely running Chrome 65 when in Chrome, so there may be some differences.

**Comment by Tarig0** [comment] 2018-03-26 15:08
+1

**Comment by sharks12** [comment] 2018-05-23 13:07
I have faced this issue recently where click & select works locally but not through CI - We use CircleCI. In my case, the temporary solution is to use ```{ force: true }``` option.

**Comment by willcodeforfoo** [comment] 2018-06-15 14:32
I'm also experiencing a similar issue with Cypress 3.0.1: an element is not being clicked using built-in Electron 59. What's weirder... the test _was_ passing for awhile but at some point during my development it started failing and now only passes in Chrome.

Happy to help gather information to help debug, but not sure what since I'm new to using Cypress (which is pretty great, BTW!)

**Comment by Bkucera** [comment] 2018-06-15 14:39
@willcodeforfoo can you try the following:
Use `cypress open` and run the test, just as it starts click to a different window on your computer to make the Test Runner lose focus. We see some cases where this causes the test to fail

**Comment by willcodeforfoo** [comment] 2018-06-15 15:10
@Bkucera I tried playing with focusing/blurring the test runner window but it didn't seem to make a difference: the test still fails.

**Comment by mpetrovich** [comment] 2018-08-09 03:49
I'm experiencing the same issue with a native `<select>` element on [Semaphore CI](https://semaphoreci.com/). I even tried as @jennifer-shehane suggested and ran the tests locally using Electron 59, but no dice: it always works locally but never works in CI. I'm also on the latest Cypress version as of this post, 3.0.3.

**Comment by Bkucera** [comment] 2018-08-21 18:32
this issue may be fixed in the most recent version of Cypress, after fixing some focus related bugs

**Comment by diarmuidoconnor** [comment] 2018-11-22 17:34
I seem to have a problem with similar characteristics to above - using cypress 3.1.2,. 

I have test specs that run smoothly (and pass) on my own computer but __one__ fails when run on the Travis CI service. 
The error is a standard TIMEOUT error, however, setting an extended timeout period does not seem to resolve it. 
The app is built with the VUE framework, communicating with a web API hosted on Heroku. The source code of the Vue app 
(and Cypress specs) is at: https://github.com/diarmuidoconnor/donationsSPA

The failing spec is line 41 of `cypress/integration/donations.spec.js`:

        cy.get('div.vue-message', {timeout: 5000}).should('contain', 'The message is [ Hope this helps')

The Travis build report is at: https://travis-ci.org/diarmuidoconnor/donationsSPA/builds/458498810

Thanks for your assistence,
Diarmuid

**Comment by bahmutov** [comment] 2018-11-22 18:18
And there is no way to see the video from Travis CI, is there? Could you use cypress dashboard and send the test results there?

**Comment by diarmuidoconnor** [comment] 2018-11-22 21:38
I've just created an account on the dashboard. A recording can be accessed [here]( https://dashboard.cypress.io/#/projects/bu5wca/runs/2/specs).

Not sure if this URL is accessible to you?

Thanks for prompt reply.

**Comment by tnrich** [comment] 2018-11-30 23:41
I'm also seeing a similar issue with the react-select dropdown in particular. It doesn't show up on the page after certain clicks:

![image](https://user-images.githubusercontent.com/2730609/49320279-9b814b80-f4b5-11e8-9028-636c215de677.png)

Interestingly this error occurs some of the time while running the tests locally via `cypress open`, but ONLY when I am not actually watching the test take place.

I've never had it fail yet while I actually watched it run, only when the test ran in the background. I tried using the `{force: true}` trick to see if that stops failures but it doesn't seem to 
![image](https://user-images.githubusercontent.com/2730609/49320357-0894e100-f4b6-11e8-956a-e9d0a5073ab7.png)

**Comment by diarmuidoconnor** [comment] 2018-12-03 19:57
Yes @tnrich our issues are similar in that they only arise when running Cypress in headless mode (cypress run), as opposed to interactive mode (cypress open). However, their is an extra layer of inconsistency in my case because both interactive and headless work locally, its headless mode on  the CI server (Travis) that a problem arises. And it is only one Cypress command line that causes the test fail - when I comment it out, everything passes. Nevertheless, we still both have a barrier to progress!

**Comment by diarmuidoconnor** [comment] 2018-12-18 11:23
Thanks @Bkucera, the tests now run locally and on Travis CI. Great.So the simple lesson is make selectors as specific and targeted as possible. Why my original, less targeted selector worked locally but failed on Travis is unclear, but that's for another day.

**Comment by Bkucera** [comment] 2018-12-27 13:33
In cypress, React-select v2 will currently not work if the browser is out of focus due to the browser priming focus/blur events while out of focus.

This is fixed in #2982 since we will polyfill focus/blur events if the browser is out of focus.

**Closed** 2019-06-11 15:06 UTC
Labels: pkg/driver, stage: needs review, topic window focus

**Comment by ThekhoN** [comment] 2019-12-12 19:00
I am still able to reproduce this. Is there any way to overcome this?

**Comment by Bkucera** [comment] 2019-12-15 18:40
@ThekhoN please describe the exact issue you're having with a reproducible example. Otherwise we won't be able to look into it. Thanks!
