### ISSUE TITLE
Cannot submit value to 'react-tagsinput' when rendered input type is 'time'

### ISSUE THREAD

**Issue by KudelAndrei** [cypress-io/cypress#4325] opened 2019-05-28 17:32 UTC
### Current behavior:

Right now I'm trying to test 'react-tagsinput' with a rendered input of a 'time' type. To submit value I have to press enter inside of the input, but when I do that with `input.type('01:11{enter}')` cypress throws and error:

> CypressError: Typing into a time input with cy.type() requires a valid time with the format 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS', where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999. You passed: 01:11{enter}. 

It works fine with other types of inputs.

Also tried: 

* Triggering the `keyDown`, `keyUp`, `change` and `input` events with jquery and pure js 
* Typing `{enter}` separately with the force option

### Desired behavior:

When I type some value into the 'time' input and add `{enter}` at the end of the value string it triggers event of pressed Enter key 

### Steps to reproduce:

Serve this file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <input data-cy="input" type="time">
  </body>
</html>
```
Then execute test.

Test code:

```js
describe("Enter", () => {
    beforeEach(() => {
        cy.visit("http://127.0.0.1:8080/");
    });

    it("misbehaves", () => {
        cy
            .get('[data-cy="input"]').type("01:11{enter}")
    });
});
```

`Operating System: Ubuntu 18.04.2 LTS`
`Cypress Version: ^3.2.0`
`Browser Version: Chrome 74.0.3729.108`
`For an actual app I use ReactJS with Material UI`

**Comment by jennifer-shehane** [comment] 2019-05-29 04:31
Yeah, this is a bug. Cypress should not attempt to validate when sent special characters to the input - or ignore the special characters as part of the validation.

I believe this line of code should be updated to strip any special characters before moving forward with the validation.

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/type.coffee#L119

**Comment by Bkucera** [comment] 2019-10-22 23:17
Could not reproduce in Cypress 3.4.1, closing as fixed. Feel free to comment here if you still believe somethings broken

**Closed by Bkucera** 2019-10-22 23:17 UTC
Labels: pkg/driver, stage: work in progress, topic: cy.type ⌨️, type: bug
