### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by Chili82** [cypress-io/cypress#22419] opened 2022-06-21 13:01 UTC
### Current behavior

Hi, I have about 200 scenarios in 15 feature files and in headless mode (electron) every time I get a memory issue error (approx after 90 min from the start of tests). 

![image](https://user-images.githubusercontent.com/17723593/174804221-5dd3d282-bef0-4698-941a-6a5204fad6c4.png)

I've set env variable in cypress.env.json but this setup is not resolved this problem.
![image](https://user-images.githubusercontent.com/17723593/174804748-21966a49-66a3-402c-b2b8-6b443f836973.png)

![image](https://user-images.githubusercontent.com/17723593/174806507-fb431bf0-8f73-4723-aec7-af448291cab8.png)

My company is interested in buying a cypress license but this is our blocker. We also went through the whole code and did the optimization, each test is completed in about 30 - 50 seconds but we still have a problem. Please who can help with this serious issue

### Test code to reproduce

{
    "NODE_OPTIONS": "--max_old_space_size=8192",
    "ELECTRON_EXTRA_LAUNCH_ARGS":"--js-flags=--expose_gc"
}

### Cypress Version

9.4.1

**Comment by mjhenkes** [comment] 2022-06-22 22:07
This may be fixed by #22460

**Comment by Chili82** [comment] 2022-06-23 14:46
Thanks, is this fix available in 10.2.0?

**Comment by Chili82** [comment] 2022-06-23 22:24
Thank You!

**Comment by mjhenkes** [comment] 2022-06-24 21:33
this might be next week.... sorry 😓

**Comment by mjhenkes** [comment] 2022-06-28 20:55
Could you try the 10.3.0 release? We fixed a memory leak that might be causing this issue.

**Comment by Chili82** [comment] 2022-06-29 05:57
Yes, I will try today and let you know more inforamtion.

**Comment by Chili82** [comment] 2022-06-29 08:14
I've run all tests with 10.3.0 version, and also I've migrated the solution but after each test, the application instance is killed and the next test has a problem with the state of the application. This is not case with previous versions 9 and 8.

**Comment by Chili82** [comment] 2022-06-29 21:29
Additional information: - seems that the test clears some flags from local storage during executing steps (usually the first step for login to application).

**Comment by lmiller1990** [comment] 2022-06-30 01:37
90 minutes is one heck of a long run. Over that time, I'm guessing there's a memory leak somewhere that's eventually causing this issue, and it must have been introduced in Cypress 10.

Just to clarify; you run all tests specs, sequentially, on your local machine (as opposed to a CI machine)?

> This wasn't the case with previous versions 9 and 8.

Your post says you are on 9.4.1 - can you confirm this issue is happening on 9.4.1, or only since migrating to 10? My understanding is this was not happening with older versions of Cypress 9, but is now happening on Cypress 9.4.1?

Since moving to Cypress 10, is it the same, or a different problem? You mention "but after each test, the application instance is killed and the next test has a problem with the state of the application" - which seems like, since moving to Cypress 10, there's a different issue?

So, please clarify:

1. original issue - Cypress 8 and 9.x is okay, but as of 9.4.1, you get the memory error.
2. new issue - since moving to Cypress 10, you have a different problem, where the "application instance is killed". What exactly does this mean - are you saying the *Cypress application* is killed?

**Comment by Chili82** [comment] 2022-06-30 05:17
Yes sorry, on 9.4.1 I get an error without memory. After that, I installed version 10.3.0 and ran all the tests, but after a few tests my tests started to crash and I can't fully test if we still have out of memory.
The application we are testing works on the following principle:
- when the user logs in, we place the appropriate settings in localStorage. After each user action, we refresh the localStorage and sequentially every 5 seconds pull the state from the localStorage and send the request to the database.
We have a cypress test that simulates the user's login, the user then changes the state of the form and checks the appropriate parameters.
The problem is that in the step after logging the user I see that the localStorage is initially loaded but when the next step starts eg the user enters some value in the input field, the values ​​in localStorage are deleted and the logic that every 5 seconds should take the state from localStorage does not work because the parameter in localStorage = null and the state of the application is not valid.
It seems to me that cypress affects localStorage during the execution of steps in one scenario, which was not the case in earlier versions 9 and 8.

**Comment by lmiller1990** [comment] 2022-07-01 00:23
Thanks for the reply. Let's start with the latter issue, around localStorage in Cypress 10. We generally don't patch older versions, like 9.4.1, so I think it's best to focus on the 10.x issue first, and go from there.

> The problem is that in the step after logging the user I see that the localStorage is initially loaded but when the next step starts eg the user enters some value in the input field, the values ​​in localStorage are deleted and the logic that every 5 seconds 
> It seems to me that cypress affects localStorage during the execution of steps 

So to clarify, when you say a step you are referring to a command, eg `cy.get`, `cy.click` etc (functions on the `cy` object)? We do [clear local storage](https://docs.cypress.io/api/commands/clearlocalstorage) before each test (so each `it` block) but this has not changed between v9 and v10.

> we refresh the localStorage and sequentially every 5 seconds pull the state from the localStorage

Is there any chance of a minimal reproduction? What do you mean by "refresh" here?

Sorry for all the questions - I'm trying to understand what I need to do to actually reproduce this. Happy to go back and forth, but it might be quicker if you can share a minimal reproduction - it sounds like the issue doesn't need a server/backend application at all - instead of logging in, you could just create a project that sets the local storage in a `before` hook, or something to that meaning.

**Comment by Chili82** [comment] 2022-07-01 05:02
Yes, I know that cypress clear localStorage aftet each test but if I have one test with few steps (login, open custom form, customize form - add new inupt or checkbox on form, set some values on form and save for example) This is one gherkin scenario.
 When I say "refresh" localStorage, I mean update localStorage with new applicationState. After login, we get state from DB and save this data in localStorage. If user add new element on form, we update localStorage with new applicationState

**Comment by GeorgeousPRO** [comment] 2022-07-11 13:12
Hi, I also get Heap out of memory when running tests on CI. 
In process_profiler table I see group called 'plugin' is growing in size with each test and eventually it breaks
![image](https://user-images.githubusercontent.com/32683645/178271312-7c87cbfe-1d46-4396-9838-798adb96eee1.png)
@lmiller1990 any ideas why 'plugin' group is taking up so much resources? 
I tried updating all plugins to last versions, but it didn't help

**Comment by lmiller1990** [comment] 2022-07-12 00:25
Oh nice debugging! This is useful. The `cypress.config.js` runs in a different process, so if you are modifying it and break it, your entire Cypress app won't crash - once you fix it, we re-execute it for you (on save, for example).

What plugins are you using? Either

1. one of them is leaking resources
2. something in our logic is leaking resources

If it's the latter, we can definitely fix it, need to figure out what's going on. If I was debugging, I'd incrementally remove plugins and try to isolate which one(s) might be causing this.

**Comment by GeorgeousPRO** [comment] 2022-07-15 10:33
in our case the issue turned out the 'ts-loader' version "5.3.3". Once updated to "8.1.0" the memory leak got fixed.

**Comment by lmiller1990** [comment] 2022-07-19 00:31
Nice - always good to update dependencies, glad that fixed it for you. I wonder if it can help the OP.

**Comment by mjhenkes** [comment] 2022-07-19 20:18
@Chili82, Could you check your version of `ts-loader` to see if it needs to be updated?

**Comment by Chili82** [comment] 2022-07-20 03:59
Yes, I will check as soon as possible. Currently I'm on vacation, but I will let you know next week. Thank you

**Closed** 2022-08-03 13:30 UTC
Labels: type: bug, stage: awaiting response
