### ISSUE TITLE
Automatically re-run failed cypress tests for a predefined number of times

### ISSUE THREAD

**Issue by cypressProj** [cypress-io/cypress#2163] opened 2018-07-17 13:00 UTC
### Current behavior:
As frontend test automation is a tricky business, there is no way to ensure 100% flakiness free tests. Sometimes even the response from the server can be slighlty slower than expected so a test will fail but re-running the same test without any remedial changes will end in success.

### Desired behavior:
Cypress has an option of something like cypress run '-rft 5' (or --repeatFailedTests 5) which will repeat the failed tests 5 times i.e. it will repeat until the tests until the test passes or fails for a maximum 5 times. 

In case the test passes when repeating the tests should be considered a success which can be really important when using CI like bamboo

The default value '-rft' should repeat the tests once.

**Comment by jennifer-shehane** [comment] 2018-07-17 15:00
Hi, you'll be happy to hear that this is already a requested feature that we have put some discussion into. Thanks for the input! Duplicate of https://github.com/cypress-io/cypress/issues/1313

**Closed by jennifer-shehane** 2018-07-17 15:00 UTC
Labels: type: duplicate
