### ISSUE TITLE
Not able to type text using index, incase if application does not have any id's or name attribute

### ISSUE THREAD

**Issue by mohammedroni4** [cypress-io/cypress#4350] opened 2019-05-30 21:15 UTC
I'm not able to type text in `search` textfield using the index, and I do not have `name` or `id` attribute, so I click on the dropdown and I have many `options`, and if I'm willing to click one, I'm not able to click on the elements because those hidden. 

And I have another option where I can type text there, but for that I do not have `id`'s or `name` attribute so I thought of using index as . `cy.get('example').eq(0).type('Hello');`

It seems like it says its not a valid attribute so if its not valid attribute its not letting my type.

I guess it would be big help if you guys can fix this issue..

**Comment by jennifer-shehane** [comment] 2019-05-31 06:45
Please provide an example of the `html` you are trying to type into. Please also provide a screenshot or the actual text of the error you are seeing.

Unfortunately we'll have to close this issue if more information is not provided. We need a way to reproduce the bug completely.

**Comment by mohammedroni4** [comment] 2019-05-31 17:20
Hey, so i'm attaching snapshot as you can see in the picture, that my dropdown category is open and also in the console log. So I want to be able to type text instead of selecting an option, since there is no select option. So as you can see there are two class which I can use to type text, so whenever I try to find element, it always finds two elements which I dont want, so I want it to type text using index so it can only type text in the first input field. so I wrote the code like this: cy.get('example').eq(0).type('Hello');  so I thought it would do is, grab the first input and type there but its not happening.  let me know if its make sense to you.

<img width="1888" alt="Screen Shot 2019-05-31 at 9 59 08 AM" src="https://user-images.githubusercontent.com/13221629/58721859-c9731a00-838a-11e9-9e03-0285a1084ce9.png">




<img width="1868" alt="Screen Shot 2019-05-31 at 10 20 15 AM" src="https://user-images.githubusercontent.com/13221629/58722982-b6157e00-838d-11e9-8b3b-65c788dad2a4.png">

**Comment by jennifer-shehane** [comment] 2019-06-03 05:13
The element you're typing into is not considered a typeable element as the error indicates - it lists all elements we consider typeable. 

We plan to expand some of these rules here: https://github.com/cypress-io/cypress/issues/3661

As for help for querying within Cypress, We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).
 
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

**Closed by jennifer-shehane** 2019-06-03 05:13 UTC
Labels: stage: needs information
