### ISSUE TITLE
Login Cookies are removed if test is too fast

### ISSUE THREAD

**Issue by tzachs** [cypress-io/cypress#2741] opened 2018-11-08 13:32 UTC
### Current behavior:
In case the 1st test is too fast (empty for example), the 2n test fails in the `beforeEach` on login since cookie is removed after the login has finished and before the 2nd test started to run.

From my developer console:
```
cypress_runner.js:58321 Cookie Removed: 'PLAY_SESSION'
Calling loginByForm
Calling cy.goToAccount
loginByForm start
loginByForm end
Cookie Set: 'PLAY_SESSION'
test1 started

Calling loginByForm
Calling cy.goToAccount
loginByForm start
Cookie Set: 'PLAY_SESSION'
loginByForm end
cypress_runner.js:58321 Cookie Removed: 'PLAY_SESSION'
```

### Desired behavior:
`cypress_runner.js` should first finish removing the cookies and only then call the `beforeEach()`

### Steps to reproduce:
* Create command in `commands.js` to login
* Create spec with `beforeEach` calling that login
* Create 2 tests, 1st test is empty, 2nd test takes a 30 seconds.

### Versions
3.1.1
Mac OS
Chrome 70 / Electron 59

### Workaround
Add `cy.wait(10000)` to first test solved it

**Comment by jennifer-shehane** [comment] 2019-01-28 09:05
Hey, could you provide the test code you are running exactly and remove sensitive information?

**Comment by tzachs** [comment] 2019-01-28 15:25
@jennifer-shehane No, I'm sorry, I can't.

**Comment by jennifer-shehane** [comment] 2019-01-29 07:36
We really won't be able to look into the issue if we cannot reproduce the behavior locally. Could you provide any screenshots or videos of the error occurring? 

You could also contact our support team in a non-public forum by emailing us at support@cypress.io

**Comment by jennifer-shehane** [comment] 2019-04-25 07:56
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 07:56 UTC
Labels: stage: needs information, topic: cookies :cookie:

**Comment by alimzadeh** [comment] 2022-05-13 15:36
I have the same issue too.
