### ISSUE TITLE
"cypress open" opens a window with a loading indicator that never goes away

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#7269] opened 2020-05-07 22:47 UTC
### Current behavior:

Running `cypress open` opens the test runner, but the loading indicator never goes away.

![image](https://user-images.githubusercontent.com/10719780/81351546-6fd69d80-9079-11ea-8636-693615674fff.png)

Here's my cypress config:

```json
{
  "chromeWebSecurity": false,
  "integrationFolder": "cypress/integration",
  "nodeVersion": "system",
  "numTestsKeptInMemory": 0,
  "testFiles": "**/*.spec.js",
  "trashAssetsBeforeRuns": false,
  "viewportHeight": 900,
  "viewportWidth": 1600
}
```

Adding debug logs isn't very illuminating:

```
cypress:server:scaffold determine if new project by globbing files in { integrationFolder: '...\\cypress\\integration' } +245ms
cypress:server:scaffold found 57 files in folder ...\cypress\integration +87ms
cypress:server:scaffold determine if we should scaffold: +0ms
cypress:server:scaffold - empty? false +2ms
cypress:server:scaffold - different number of files? true +3ms
cypress:server:scaffold - same sizes? false +0ms
cypress:server:scaffold untouched scaffold false modal closed false +0ms
cypress:server:project scaffolding with plugins file ...\cypress\plugins\index.js +110ms
cypress:server:scaffold plugins folder ...\cypress\plugins +5ms
cypress:server:scaffold verify scaffolding in ...\cypress\plugins +4ms
cypress:server:scaffold folder ...\cypress\plugins already exists +1ms
cypress:server:project typescript path: ...\node_modules\typescript\lib\typescript.js+10ms
cypress:server:plugins plugins.init ...\cypress\plugins\index.js +0ms
cypress:server:plugins launching using custom node version { resolvedNodePath: 'C:\\Users\\KYLEGE~1\\AppData\\Local\\Temp\\yarn--1588891464922-0.8051231763595283\\node.CMD', resolvedNodeVersion: '12.16.1' } +1ms
cypress:server:plugins forking to run C:\Users\Kyle Getz\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\plugins\child\index.js +1ms
```

### Versions

OS: Windows 10
Cypress: 4.5.0

**Comment by jennifer-shehane** [comment] 2020-05-08 05:01
- Can you try removing the `nodeVersion` from your config? Does this change anything?
- Do you have anything in your `plugins/index.js` file? 
- Does it run normally from a standard project like forking and running [`cypress-example-kitchensink`](https://github.com/cypress-io/cypress-example-kitchensink)?

**Comment by kaiyoma** [comment] 2020-05-08 17:12
Ah, it's the `nodeVersion` that's causing the problem. We recently changed this to `"system"` as per the comments in this thread: https://github.com/cypress-io/cypress/issues/5943

Making that switch has helped with performance issues for the macOS users, but it breaks the Cypress test runner entirely for Windows 10. 😢

**Comment by crfrolik** [comment] 2020-05-11 17:52
Duplicate of https://github.com/cypress-io/cypress/issues/6792

**Comment by jennifer-shehane** [comment] 2020-05-12 05:53
Duplicate of #6775

**Closed by jennifer-shehane** 2020-05-12 05:53 UTC
Labels: stage: awaiting response
