### ISSUE TITLE
Cypress never get past loading screen on Windows

### ISSUE THREAD

**Issue by hvaandres** [cypress-io/cypress#14393] opened 2021-01-04 18:53 UTC
I have created a new project

```
npm init -y
```

I have installed cypress

```
npm install cypress --save-dev
```

I have run the project

```
npx cypress open
```

The problem is that I'm seeing that cypress will open, but it will never load the files or it will never finish loading the dashboard window to be able to select one of your files. It's just spinning now for a long time. What can need to do to resolve this issue?

**Comment by jennifer-shehane** [comment] 2021-01-05 02:08
Likely a duplicate of https://github.com/cypress-io/cypress/issues/9572 which I haven't been able to track down why this issue occurs.

**Closed by jennifer-shehane** 2021-01-05 02:08 UTC
