### ISSUE TITLE
Please fix video recording for Firefox 

### ISSUE THREAD

**Issue by romankhomitskyi** [cypress-io/cypress#26090] opened 2023-03-13 12:43 UTC
### Current behavior

Currently video recording for firefox is not working

Firefox  version 110

### Desired behavior

Should record video

### Test code to reproduce

None

### Cypress Version

12.5.0

### Node version

18.13.0

### Operating System

Ventura 13.12.1

**Comment by mike-plummer** [comment] 2023-03-13 14:03
Duplicate of #18415

**Closed as not planned by mike-plummer** 2023-03-13 14:03 UTC
