### ISSUE TITLE
cypress removes origin on fetch post requests

### ISSUE THREAD

**Issue by mcgoooo** [cypress-io/cypress#4979] opened 2019-08-13 15:14 UTC
Currently cypress seems to remove the origin from fetch post requests, this does not happen in firefox, default chrome or safari, in normal mode or incognito mode

### Current behavior:
strips the origin from fetch post requests

code example to illustrate behaviour
https://github.com/mcgoooo/cypress-fetch-origin-example

the results are shown in these screenshots

![Screenshot 2019-08-13 at 15 58 26](https://user-images.githubusercontent.com/248888/62953070-c1047a00-bde4-11e9-8662-d394a319d923.png)

this is different than chrome, sfari and firefox which returns

![Screenshot 2019-08-13 at 15 42 50](https://user-images.githubusercontent.com/248888/62953103-cc57a580-bde4-11e9-9584-497701c870e6.png)

 

### Desired behavior:

dont strip origin on fetch post requests

### Steps to reproduce: (app code and test code)

can be seen by opening a tab in cypress and hitting the following url 
https://murmuring-sands-77169.herokuapp.com/

https://github.com/mcgoooo/cypress-fetch-origin-example

### Versions
CYPRESS 3.4.1

**Comment by abasille** [comment] 2019-08-19 13:29
- Origin removed with Chromium and Chrome 76
- Origin present with Electron 61

**Comment by TLadd** [comment] 2019-08-22 02:25
I'm pretty sure I'm running into this.

One of our tests that adds a payment method using Zuora started failing. When we run the test, this authentication alert pops up. This was not the case the last time we ran it manually, where it would normally just 200. In CI it still passes, which led me to believe it had something to do with the chrome version, since the image we're using in CI is not updated to the latest version of Chrome. Using https://chromium.cypress.io, I was able to confirm that the test passes as it did before in versions before 76 but fail in the 76 range.

Electron 61 - passes
74.0.3729.169 - passes
75.0.3770.100 - passes
75.0.3770.142 - passes
76.0.3809.87 - fail 
76.0.3809.100 - fail

(note the CC info entered here is fake using one of Stripe's test cards)
<img width="1199" alt="Screen Shot 2019-08-21 at 8 52 22 PM" src="https://user-images.githubusercontent.com/5084492/63480983-973cfa00-c459-11e9-9780-1ca0289e48d7.png">

The failing call:
<img width="556" alt="Screen Shot 2019-08-21 at 8 53 13 PM" src="https://user-images.githubusercontent.com/5084492/63480809-edf60400-c458-11e9-9703-269d807f4e3e.png">

Zuora's API is pretty finicky, so I think the origin header being stripped off would probably do it.

**Comment by tibdex** [comment] 2019-10-04 14:30
This is related to #2568 but the weird thing is that the issue happens when using `cypress run` but not `cypress open`. Someone knows the Chrome-related differences between these two modes?

**Comment by AnnaBankovskaiaTR** [comment] 2020-03-02 10:53
I have the same issue. It was present in 3.2.0, fixed it by upgrading to 3.4.1. Then decided to go up to 4.1.0... and, "Hi, missing origin, there you are". Only reproducible in Chrome, Electron always works fine

**Comment by jennifer-shehane** [comment] 2020-07-14 09:42
I'm not able to reproduce this in Cypress 4.10.0, so believe this has been fixed since this was opened. 

### Outside Cypress

<img width="1036" alt="Screen Shot 2020-07-14 at 4 07 47 PM" src="https://user-images.githubusercontent.com/1271364/87410415-493e6100-c5ec-11ea-85b9-24740b9bd872.png">


### Within Cypress

<img width="1251" alt="Screen Shot 2020-07-14 at 4 08 28 PM" src="https://user-images.githubusercontent.com/1271364/87410434-4f344200-c5ec-11ea-9de5-53f38293bdda.png">

Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-07-14 09:42 UTC

**Comment by sonphnt** [comment] 2022-03-01 13:27
I am using Cypress version 9.5, I have a call to Grahql and the origin is removed in the request. Is the bug coming back?

**Comment by Aishwarya-U-R** [comment] 2022-12-21 18:34
@jennifer-shehane - We are using Cypress 9.7 & origin removed in POST request too!

**Comment by Amy-B-Tradition** [comment] 2023-12-05 15:24
Is there any movement on this ticket? I was correcting for this with an intercept, but it seems like this no longer works.
