### ISSUE TITLE
Cannot use cy.readFile or cy.task inside cy.intercept even if promises are supported

### ISSUE THREAD

**Issue by XavierLeTohic** [cypress-io/cypress#15270] opened 2021-03-01 10:29 UTC
### Current behavior
Using  both `cy.readFile` or `cy.task` inside `cy.intercept` will occur the following error:

![Screenshot 2021-03-01 at 11 22 28](https://user-images.githubusercontent.com/6340490/109487460-87599980-7a84-11eb-87a4-3d00e66521e7.png)

### Desired behavior
We generate fixtures files before running Cypress containing multiple possible responses for each query. We would like to read the generated files in order to match the good mock according to the query's variables but we are unable to use `cy.readFile` or `cy.task` (that would use `fs`) inside `cy.intercept`.

### Test code to reproduce
```js
    cy.intercept('POST', 'http://graphql.test/graphql', (req) => {

      req.alias = operationName;

      const operationName = req.body.operationName;
      const [specName] = Cypress.spec.name.split('.');

      cy.readFile(`mocks/generated/${specName}_${req.body.operationName}.json`, (err, data) => {
        console.log(data)
        console.log(err)
      })
      .then((content) => {
        // we want here to find the good response from `content` according to req.body.variables
        req.reply(content);
      });
    });
```

### Versions

Mac OS 11.2.1
Cypress 6.5.0
Node 14.15.3

**Comment by jennifer-shehane** [comment] 2021-03-01 15:16
I can recreate this behavior. I'm not sure what the intended behavior is, but this does seem unexpected. 

```js
it('test cy.intercept()', () => {
  cy.intercept('POST', '/users', (req) => {
    cy.readFile('./fixtures/example.json').then((data) => {
      req.reply(data)
    })
  }).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/users')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

**Comment by flotwig** [comment] 2021-03-04 20:02
I think this is a duplicate of #7667 - cy commands are incidentally not supported, but it could use a better error either way

**Closed** 2021-03-26 19:40 UTC
Labels: pkg/net-stubbing, stage: needs investigating, type: unexpected behavior
