### ISSUE TITLE
cy.get('[data-some-input]').type('breaking') breaks in chrome 68

### ISSUE THREAD

**Issue by lm185074** [cypress-io/cypress#2223] opened 2018-07-27 14:03 UTC
Cypress typing functionality no longer working when updated to chrome 68.

### Current behavior:
```
CypressError: Timed out retrying: cy.type() failed because this element:

<input id="visiblenumber" focus-if="" type="number" maxlength="4" ng-model="$ctrl.number" tabindex="1" class="ng-pristine ng-valid ng-empty ng-valid-maxlength ng-touched" aria-invalid="false">

is being covered by another element:

<html lang="en" xmlns:ng="http://angularjs.org" ng-app="app" class="ng-scope">...</html>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Test'
```

### Desired behavior:

Type functionality should work as it did in chrome 67 and in electron browser.

### Steps to reproduce:

Download chrome 68. Try to run any test that using type function on a component. AngularJS application.

### Versions

Chrome 68, Mac OS Sierra, Cypress version 3.0.2, AngularJS

**Comment by millarm** [comment] 2018-07-27 14:35
I'm hitting this with a react app too - comparing developer's machines that it works on and others it doesn't looks like 67.0.3396.99 is good and 68.0.3440.75  is bad.

**Comment by jennifer-shehane** [comment] 2018-07-27 15:40
Duplicate of https://github.com/cypress-io/cypress/issues/2037

There is a workaround here: https://github.com/cypress-io/cypress/issues/2037#issuecomment-407898194

**Closed by jennifer-shehane** 2018-07-27 15:40 UTC
Labels: type: duplicate

**Comment by vivmehra-gl** [comment] 2020-05-21 08:38
Hi @jennifer-shehane,
I am still facing the same issue.  Tried all the suggestions in all the comments.
Cypress Version: 3.6
Chrome Version: 81
These issues have been marked as closed, but still facing the issue.
Request you to please help.

**Comment by jennifer-shehane** [comment] 2020-07-14 09:03
@vivmehra-gl If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
