### ISSUE TITLE
Cypress console suddenly crashed 

### ISSUE THREAD

**Issue by alessandrostassalpitour** [cypress-io/cypress#24791] opened 2022-11-23 08:24 UTC
### Current behavior

During the execution of Cypress test, after almost 2 minute, the test crashed suddenly. 

### Desired behavior

The test should complete the code until the end of the test (only one it block)

### Test code to reproduce

Console log errror:

This is the equivalent to seeing the 'sad face' when chrome dies

This can happen for a number of different reasons:

-You wrote an endless loop and you must fix your own code 
-You are running Docker (there is a an easy fix for this: see like below)
ecc. ecc.

### Cypress Version

11.0.1

### Node version

16.17.0

### Operating System

Windows 10

**Comment by nagash77** [comment] 2022-11-23 19:14
Hi @alessandrostassalpitour I am sorry to hear you are having issues running Cypress.  

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-12-05 18:36
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as not planned by nagash77** 2022-12-05 18:36 UTC
