### ISSUE TITLE
Code coverage instrumentation with cy.intercept()

### ISSUE THREAD

**Issue by slikts** [cypress-io/cypress#8831] opened 2020-10-14 06:59 UTC
It's mentioned in [this official webcast](https://youtu.be/C8g5X4vCZJA) that automated code coverage instrumentation would be enabled by full network request stubbing or `cy.route2()` (#687). There is, however, no documentation or examples for this, and no discussion that I could find, so it'd be helpful to either have docs or a confirmation that this feature is planned or dropped.

**Comment by jennifer-shehane** [comment] 2020-10-16 09:08
This is not a planned for the initial release of `cy.route2()`. Could you describe the features you'd like to see involving code coverage and `cy.route2()` for us to consider as a future feature?

**Comment by slikts** [comment] 2020-10-23 15:19
The use case would essentially be to add instrumentation to code on the fly to test apps using a production build instead of a development build. The reason to want to do it is somewhat complicated to explain, but I also don't think it's that uncommon.

**Comment by bahmutov** [comment] 2020-10-23 15:30
Yes this would be a very good use case, similar to this code coverage instrumentation proxy I wrote a while ago https://glebbahmutov.com/blog/code-coverage-proxy/. We could put some effort to make it work (the problem is bundling and going back via source maps)

**Comment by jennifer-shehane** [comment] 2024-01-24 01:13
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.

**Closed by jennifer-shehane** 2024-01-24 01:13 UTC
Labels: type: feature, stage: proposal 💡, topic: cy.intercept()
