### ISSUE TITLE
[@cypress/react] React 17 support for support configuration

### ISSUE THREAD

**Issue by AndrewLeedham** [cypress-io/cypress#15609] opened 2021-03-22 12:37 UTC
### Current behavior
I am adding `cypress` and `@cypress/react` to an existing project which uses React 17. It works as expected when using the [using-babel-typescript template](https://github.com/cypress-io/cypress/tree/develop/npm/react/examples/using-babel-typescript) and changing `'@babel/preset-react'` so be `['@babel/preset-react': {runtime: 'automatic'}]` to make use of React 17's `_jsx` automatic import fanciness, which the project uses for all its components already. However, when I try and create a centralised `cy.mount` helper along the lines of:
```js
import { mount } from '@cypress/react';
import { ReactElement } from 'react';
import Wrapper from '/path/to/Wrapper';

Cypress.Commands.add('mount', (component) => {
  return mount(<Wrapper>{component}</Wrapper>);
});
```
I get the following error in Cypress:
```
The following error originated from your application code, not from Cypress.

  > Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
After playing with various different scenarios this seems to be because support files are bundled separately without the custom plugin for bundling components, so it is referencing the usual "classic" react import instead of the new `_jsx` version.

### Desired behavior
"@cypress/react" has a peerDependency on React 16, so I guess the ideal scenario is 1st class React 17 support and the ability to use `runtime: 'automatic'` for support bundling.

### Test code to reproduce
Repro configs provided in the [Current behavior](#current-behaviour) section.

### Versions

`@cypress/react`: 4.16.4
`cypress`: 6.8.0
`@cypress/webpack-dev-server`: 1.1.0
`react`: 17.0.1
`react-dom`: 17.0.1

**Comment by dmtrKovalenko** [comment] 2021-03-22 16:33
Current workaround: manually import ReactDom and pass it as an argument

```js
import * as ReactDom from 'react-dom';

mount(<MyComponent />, { ReactDom });
```

**Comment by AndrewLeedham** [comment] 2021-03-22 20:56
@dmtrKovalenko I am not sure that would solve the issue. https://reactjs.org/link/invalid-hook-call seems to say the issue is with 2 instances of `react` not `react-dom`.

I am wanting to create a custom command in my support file which renders a wrapper component, then use said custom command in my test files to render children within the wrapper.

**Comment by lmiller1990** [comment] 2021-03-23 03:29
@AndrewLeedham I had a similar problem at the work around fixed it. Let us know if it works for you - you could be correct in your assertion, but good to validate the existing work-around won't work. If you try it and it does not work, we can dive deeper!

**Comment by AndrewLeedham** [comment] 2021-03-23 09:29
@lmiller1990 Sorry I meant to say I tried it and it didn't work. I tried passing react dom to the custom command and then to mount, but no luck.

**Comment by dmtrKovalenko** [comment] 2021-03-23 09:33
Please create a full example -- separate repository that verifies this issue

**Comment by AndrewLeedham** [comment] 2021-03-23 11:29
Sure, I created 2 repros, one with and one without the preposed fix. I am seeing the aforementioned error in both:
https://github.com/AndrewLeedham/cypress-test-tiny/tree/react-hook-warning
https://github.com/AndrewLeedham/cypress-test-tiny/tree/react-hook-warning-pass-react-dom

**Comment by lmiller1990** [comment] 2021-03-29 02:04
Yep, reproduction works. I am digging into this... I suspect your suspicions around the support file are correct.

**Comment by dmtrKovalenko** [comment] 2021-04-02 11:59
Sorry for long answer. It happens because of weird preprocessor architecture, 7.0 with dev-server architecture will be released very soon (maybe today) but preprocessor won't work because support file and test file is compiled by different cold call to webpack, so it will anyway have different version of react 

You can fix it now using `import` instead cypress command 

```diff
diff --git a/src/Component.test.jsx b/src/Component.test.jsx
index 8f09fc9..73d26da 100644
--- a/src/Component.test.jsx
+++ b/src/Component.test.jsx
@@ -1,8 +1,11 @@
 /// <reference types="cypress" />
-const Component = require('./Component');
+import React from 'react'
+import { mount } from '@cypress/react'
+import { mountWithWrapper } from './test_helpers';
+const Component  = require('./Component');
 
 describe('page', () => {
   it('works', () => {
-    cy.mount(<Component/>)
+    mountWithWrapper(<Component/>)
   })
 })
diff --git a/src/test_helpers.js b/src/test_helpers.js
new file mode 100644
index 0000000..9765eca
--- /dev/null
+++ b/src/test_helpers.js
@@ -0,0 +1,12 @@
+import * as React from 'react'
+import mount from "@cypress/react";
+
+const Wrapper = ({children}) => {
+  const [state, setState] = React.useState();
+  return <p>{children}</p>
+}
+
+
+export const mountWithWrapper = (el) => {
+  mount(<Wrapper>{el}</Wrapper>)
+}
\ No newline at end of file
```

**Closed** 2021-04-02 11:59 UTC
Labels: npm: @cypress/react

**Comment by AndrewLeedham** [comment] 2021-04-06 08:03
@dmtrKovalenko Thanks 👍 . Is there any plans to combine the 2 webpack's in the future, or will they always be separate by design?

**Comment by dmtrKovalenko** [comment] 2021-04-06 08:06
We already released new component testing using webpack devserer where it should work out of the box. 

Check cypress docs for v7 component test runner.

**Comment by lmiller1990** [comment] 2021-04-07 02:01
More details: https://github.com/cypress-io/cypress/issues/15569#issuecomment-813813742

**Comment by AndrewLeedham** [comment] 2021-04-12 17:02
Nice got `cy.mount` working with v7. Thanks for the help!
