### ISSUE TITLE
Cypress truncates and splits long run URLs

### ISSUE THREAD

**Issue by pitthecat** [cypress-io/cypress#20362] opened 2022-02-25 07:33 UTC
### Current behavior

Cypress splits and truncates long run URLs. Cypress splits the link over two lines here. That way the link is not usable directly and you have to do some grep, sed and awk magic to extract the whole link

![image](https://user-images.githubusercontent.com/28391645/155672372-13d8f3f2-1ed9-40a1-8ad7-290779fb3b22.png)

At the end of the run the link is posted again, but its completely unusable because Cypress truncates the URL and part of the run id is cut of. It's cut off after the 82th character.

![image](https://user-images.githubusercontent.com/28391645/155672678-bcf7e965-2a71-4614-a80d-80745eb1c4ff.png)

### Desired behavior

Cypress should output the run URL at least one time completely untouched

### Test code to reproduce

Use a cypress dashboard with a long DNS name and a longer run id.

### Cypress Version

9.2.0

**Comment by jennifer-shehane** [comment] 2022-04-08 20:08
Duplicate of https://github.com/cypress-io/cypress/issues/7533

**Closed by jennifer-shehane** 2022-04-08 20:08 UTC
Labels: external: dashboard
