### ISSUE TITLE
Returning from inside within block fails in the latest version of cypress after 5.3.0

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#15273] opened 2021-03-01 15:03 UTC
Returning from inside within block fails in the latest version of cypress after 5.3.0

Reproducible sample code, we have various other similar scenario in our application where return is required to use to target within block and need the same element in another function to move ahead

### Current behavior
Button click didn't trigger

### Desired behavior
Button click should be trigger

### Test code to reproduce

```
	<body>
		<div>
			<div test-id="myheader">
				This is just a demo
				<button class="mybuttons">Close</button>
			</div>
			<div test-id="mybody">
				First Name: <input type="text" id="fname" />
				First Name: <input type="text" id="lname" />
				<button class="mybuttons">Save</button>
			</div>
			<div test-id="myfooter">
				<button class="mybuttons">Ok</button>
				<button class="mybuttons">Cancel</button>
				<button class="mybuttons">Go To Home</button>
			</div>
		</div>

	</body>
```

```
function GetFooterbutton(index: number): Cypress.Chainable<Subject> {
    return cy.get("[test-id='myfooter']").within(() => {
		return cy.get(".mybuttons").eq(index - 1);
	});
}
```
Now calling the above function from the script

```
	cy.GetFooterbutton(1).click();
```

The same above code is working fine till Cypress 5.3.0 but its fails to click the button on all subsequent version after 5.3.0.
The reason :- It returns the [test-id='myfooter'] element and it clicks on "myfooter" element so, it neither throws any error nor it performs the tasks and hence the script gets stuck because button event is not triggered.

If we remove the return from the first line then the compiler will complain that the not all code return a value and on the other hand but we have to target the mybuttons within the myfooter component. even if we give data-test-id instead of class then also we have target within footer and then return and perform further action in the caller script

Let me know if you require further details
### Versions

Cypress v5.3.0 (working fine)
Cypress @latest version (all version after 5.3.0) has a problem

**Comment by jennifer-shehane** [comment] 2021-03-01 17:46
Duplicate of https://github.com/cypress-io/cypress/issues/8873

**Closed by jennifer-shehane** 2021-03-01 17:46 UTC
