### ISSUE TITLE
File watching is broken when integrationFolder is not the default

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#438] opened 2017-02-21 20:42 UTC
If the `integrationFolder` is configured to be something other than the default of `integration`, any changes to spec files will not cause a `watched:file:changed` event to be emitted through the web socket.

I think this has to do with the runner still using the default `integration` for the path of the file.

Note that the URL says `tests/integration/smoke_spec.js` even though the `integrationFolder has been set to `e2e`.

![screen shot 2017-02-21 at 3 39 45 pm](https://cloud.githubusercontent.com/assets/1157043/23184063/3b9f3d9c-f84c-11e6-8efa-677a5467a2c3.png)

**Comment by brian-mann** [comment] 2017-02-21 20:46
The `URL` will always denote `integration`, which is correct and is not related to changing the `integrationFolder`. 

The `integration` in the URL causes Cypress to internally lookup the `integrationFolder` path when serving the files (else it would have no ability to know where to look for them). When we start serving `unit` tests the URL will be changed and that's how it will know to lookup `unitFolder` as well.

**Comment by chrisbreiding** [comment] 2017-02-21 20:52
Okay, I thought that might be the case. But it is the root cause. Somewhere, we're missing a translation of `integration` to its configured value, which is causing the file change notification disconnect.

**Comment by chrisbreiding** [comment] 2017-02-21 20:53
Related to the root cause, I should say. It's not the precise root cause.

**Comment by brian-mann** [comment] 2017-03-09 21:32
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).

**Closed by brian-mann** 2017-03-09 21:32 UTC
Labels: bug

**Comment by Geary270592** [comment] 2019-08-20 10:49
I'm seeing this currently. Lots of different instances of file watching not working on Windows, here are my findings:

Setting the application up as in https://docs.cypress.io/guides/getting-started/writing-your-first-test.html#Write-a-simple-test doesn't work, even with configuring the integrationPath to another location.

Using the .exe can work, as long as you don't change the integrationPath, however due to the way that the project seems to require setting up to work with Jenkins, the code all needs to be within nodemodules/.bin/cypress in order for Jenkins to find it. This is because to run in Jenkins the steps are as follows:

npm install cypress --save-dev;
./node_modules/.bin/cypress run;

trying to run in Jenkins and point at the "correct" project code as follows:

npm install cypress --save-dev;
./node_modules/.bin/cypress run --project  ./cypress/integration;

yields the error that no tests are found. This is presumably due to the lack of cypress configuration in that module of the repository. As a result, if I want to both be able to develop with reruns, and also run the tests in Jenkins, then I need them in two different areas in the same repo. If just one of the rerouting overrides worked (ideally the jenkins override so I didn't need the whole cypress module in my git checked out code) then I'd be able to have them all in one place.

I accept that I'm probably doing a lot of things wrong in the above steps, but it's the best I could do given conflicting expected an actual results given from the documentation. I'm assuming these are Windows-specific issues.

**Comment by jennifer-shehane** [comment] 2020-01-06 10:44
This issue will be closed to further comment as the exact issue here was resolved and tested in Cypress 0.19.1 over 2 years ago.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
