### ISSUE TITLE
Cannot register multiple "after:spec" callbacks

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#24410] opened 2022-10-26 18:50 UTC
### Current behavior

```js
setupNodeEvents(on, config) {
  on('after:spec', (spec, results) => {
    console.log('after spec 1')
  })

  on('after:spec', (spec, results) => {
    console.log('after spec 2')
  })
}
```

Only shows `after spec 2` message

### Desired behavior

Every attached callback should be called

### Test code to reproduce

See above

### Cypress Version

9.7.0, 10.11.0

### Node version

v16

### Operating System

Mac

### Other

I wonder if the plugin data context is correct and keeps multiple callbacks in the list to call... https://github.com/cypress-io/cypress/blob/9ceb95d3c0c680a680d21d2ed765462e0b526436/packages/server/lib/plugins/run_events.js#L10

**Comment by bahmutov** [comment] 2022-10-26 18:53
Running with `DEBUG=cypress:server:run npx cypress run`

```
  cypress:server:run received project end { stats: { suites: 0, tests: 1, passes: 1, pending: 0, skipped: 0, failures: 0, wallClockStartedAt: 2022-10-26T18:51:34.537Z, wallClockEndedAt: 2022-10-26T18:51:34.597Z, wallClockDuration: 60 }, reporter: 'spec', reporterStats: { suites: 0, tests: 1, passes: 1, pending: 0, failures: 0, start: 2022-10-26T18:51:34.540Z, end: 2022-10-26T18:51:34.606Z, duration: 66 }, hooks: [], tests: [ { testId: 'r2', title: [Array], state: 'passed', body: "() => {\n  cy.log('test a');\n}", displayError: null, attempts: [Array] } ] } +750ms
  cypress:server:run received videoController { videoController: undefined } +1ms
after spec 2
  cypress:server:run executed after:spec +2ms
  cypress:server:run No video found after spec ran - skipping processing. Video path: undefined +0ms
```

Running with `DEBUG=cypress:data-context npx cypress run`

```
  cypress:data-context browser found to set electron +0ms
```

and nothing else

**Comment by emilyrohrbough** [comment] 2022-12-28 20:45
This is a duplicate of https://github.com/cypress-io/cypress/issues/5240.

**Closed as completed** 2022-12-28 20:46 UTC
Labels: type: duplicate, type: feature, E2E
