### ISSUE TITLE
Can there be a more detailed visual schema in the docs of how cypress works(cypress architecture))

### ISSUE THREAD

**Issue by kazeens** [cypress-io/cypress#4548] opened 2019-06-24 10:13 UTC
Hi, I want to start using Cypress and want to comprehend its architecture design.
Your doc says 
> Cypress is executed in the same run loop(is it event loop?) as your application

Could you follow up on this? Does it mean than Cypress tests and my application share the same process(inside a browser)?

>  Behind Cypress is a Node.js server process. Cypress and the Node.js process constantly communicate, synchronize, and perform tasks on behalf of each other.

Could you also follow-up on that? What are the concrete responsibilities on that Node.js process? What does it do?
Do I get it right that browser runtime is itself a standalone process in which Cypress hooks and runs tests?
Thanks

**Comment by jennifer-shehane** [comment] 2019-06-24 17:54
Closing as duplicate of https://github.com/cypress-io/cypress-documentation/issues/872

**Closed by jennifer-shehane** 2019-06-24 17:54 UTC
