### ISSUE TITLE
Cypress Tests getting stuck up when run as  a  batch of 30-40 Scripts.

### ISSUE THREAD

**Issue by AspireSytemsINC** [cypress-io/cypress#21549] opened 2022-05-18 18:04 UTC
### Current behavior

Cypress Tests getting stuck up when run as  a  batch of 30-40 Scripts.

### Desired behavior

Automation scripts in Batch should not get Stuck up.

### Test code to reproduce

Not  script level issue, script run fine locally when run individually. But it get stuck up when run in batch.

### Cypress Version

9.6.0

### Other

Automation Script run individually but when run as  batch it get stuck up randomly. 

Docker Image version -- FROM cypress/included:9.6.0

I tried increasing the shared memory of the container to 4 to 8gb but still the same (docker run -it --shm-size=4gb), also tried decreasing the count of this flag in cypress.json - numTestsKeptInMemory but still the same.

Note - This is also observed when running cypress without Docker and on Windows hosts directly.

Attached the snapshot of the container logs when run from docker with debug logs.

However after switching to docker image - FROM cypress/included:9.5.1 but cypress version is same 9.6.0 I could not see this issue.

Error Snapshot --
![image](https://user-images.githubusercontent.com/96147472/169112309-11139578-8894-4ccf-9ab2-e0c10041ad58.png)
![image](https://user-images.githubusercontent.com/96147472/169112451-ce39f2f8-58ec-40bd-9cbf-3d2df3807ca8.png)

**Comment by BlueWinds** [comment] 2022-05-18 23:41
Are you running these tests with Electron or Chrome? I ask because the different images have different browser versions - it's possible

One potential workaround would be to switch browsers  (`--browser electron/chrome/firefox`) and see if you're getting the same crashes - even if you don't want to change browsers permanently, it would at least help us figure out if that's the cause, since those two docker images are fairly similar other than their browser versions.

**Comment by BlueWinds** [comment] 2022-05-20 02:24
As best I can tell, this is a Chrome issue, introduced in the updated version in the 9.6.0 docker container. I haven't reproduced it myself, but I'm going to forward this to the e2e team for consideration.

Unfortunately I suspect that the only answer will be to keep using the older version of chrome until 10.0.0 comes out (and we update chrome again to the latest version, hopefully with a fix) or use a different browser.

**Comment by rockhold** [comment] 2022-06-21 20:59
@AspireSytemsINC, are you able to still reproduce this issue with a release >= 10.0?

**Comment by emilyrohrbough** [comment] 2022-06-30 18:38
Duplicate of #20846 and #22419

**Comment by AspireSytemsINC** [comment] 2022-06-30 19:22
> @AspireSytemsINC, are you able to still reproduce this issue with a release >= 10.0?

We are yet to migrate the scripts to Cypress 10. But, with docker  image FROM cypress/included:9.5.1 execution is fine for 2-3 hours batch in headless chrome.

**Comment by rockhold** [comment] 2022-08-18 21:02
@AspireSytemsINC, I'm going to close this out as a duplicate. If you're still experiencing a problem here, feel free to log a new issue. Thanks for reporting.

**Closed by rockhold** 2022-08-18 21:02 UTC
Labels: stage: routed to e2e-core, stage: fire watch
