### ISSUE TITLE
Cypress return 'Whoops, there is no test to run' after submiting an iframe

### ISSUE THREAD

**Issue by manphannvg** [cypress-io/cypress#3051] opened 2019-01-02 10:24 UTC
### Current behavior:

[See video here](https://youtu.be/PWEvMyUl2es)

![image](https://user-images.githubusercontent.com/40622958/50588083-140f6980-0eb3-11e9-947b-d1331643faba.png)

### Desired behavior:

It should works properly

### Steps to reproduce: (app code and test code)

```js
cy.get("#datatransPaymentFrame").then(($iframe) => {
       const $body = $iframe.contents().find('body')
       let stripe = cy.wrap($body[0])
       stripe.find('li.payment-list--item').eq(0).click()
       stripe = cy.wrap($body[0])
       stripe.find('#cardNumber').eq(0).type("5200000000000007", { force: true })
       stripe = cy.wrap($body[0])
       stripe.find('#expiry').eq(0).type("122019", { force: true })
       stripe = cy.wrap($body[0])
       stripe.find('#cvv').eq(0).type("133", { force: true })
       stripe = cy.wrap($body[0])
       stripe.find('.form--submit').click({ force: true })
       cy.wait(5000)
      })
```
'Whoops, there is no test to run' screen returned after click '.form--submit' element
### Versions

3.1.4 both electron 59 and chrome 71

**Comment by jennifer-shehane** [comment] 2019-01-03 11:35
Hey @manphannvg, this definitely shouldn't be happening. Unfortunately, we'll be unable to look at the issue without being able to reproduce this locally. 

Can you provide some test code that we can run exactly on our machine to experience this issue?

**Comment by manphannvg** [comment] 2019-01-04 04:37
Hi @jennifer-shehane ,

Can you try to reproduce this this test code?

```
  it.only("iframe - test", function () {
    cy.visit('https://www.immoscout24.ch/private/login')
    cy.get("[id='LoginDataModel_LoginName']").type('cypress_test@gmail.com')
    cy.get("[id='LoginDataModel_Password']").type('Aa123456')
    cy.get(".button.submit").first().click()
    cy.get(".hub-object-management")
    cy.visit("https://www.immoscout24.ch/private/insertion/final/5302048")
    cy.get('.credit-card').click()
    cy.get('.button.step-continue').click()
    cy.wait(9000)
    cy.get("#datatransPaymentFrame").then(($iframe) => {
      const $body = $iframe.contents().find('body')
      let stripe = cy.wrap($body[0])
      stripe.find('li.payment-list--item').eq(0).click()
      stripe = cy.wrap($body[0])
      stripe.find('#cardNumber').eq(0).type("5200000000000007", { force: true })
      stripe = cy.wrap($body[0])
      stripe.find('#expiry').eq(0).type("122019", { force: true })
      stripe = cy.wrap($body[0])
      stripe.find('#cvv').eq(0).type("133", { force: true })
      stripe = cy.wrap($body[0])
      stripe.find('.form--submit').click({ force: true })
    })
    cy.wait(5000)
  })
```

Thanks,
Man Phan

**Comment by manphannvg** [comment] 2019-01-30 03:41
Hi @jennifer-shehane,
CC @brian-mann 

Do you have any update for this issue?

Thanks,
Man Phan

**Comment by jennifer-shehane** [comment] 2019-01-30 05:39
Hey @manphannvg, could you please double check the tests you provided? I am getting a timeout when running these tests locally in Electron & Chrome. 

Also, you may want to look through our workarounds when behind corporate proxy is you are behind a corporate proxy: https://github.com/cypress-io/cypress/issues/1469

**My failure**

<img width="556" alt="screen shot 2019-01-30 at 12 09 12 pm" src="https://user-images.githubusercontent.com/1271364/51960562-e274c880-2487-11e9-9f13-3cf3a55f7004.png">

**Comment by tcoldmf** [comment] 2019-04-23 08:21
I have the same problem with a simple login form (not iframe). The login is static, no a javascript form.

**Comment by jennifer-shehane** [comment] 2019-04-24 15:42
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-24 15:42 UTC
Labels: stage: needs information, topic: whoops 😳

**Comment by tcoldmf** [comment] 2019-04-25 06:50
I have fixed my problem: I had an attribute `target="_ top"` in the `form` tag.

**Comment by magicspon** [comment] 2019-07-04 15:37
@manphannvg did you manage to get a fix for this?

**Comment by lpleo** [comment] 2019-11-06 09:30
I had the same problem, target '_top' attribute without any iframe. I removed the attribute and now works fine.

**Comment by jennifer-shehane** [comment] 2020-01-03 07:50
Essentially a duplicate of https://github.com/cypress-io/cypress/issues/3121
