### ISSUE TITLE
cy.fixture() uses encoding from the first use when used multiple times with different encodings

### ISSUE THREAD

**Issue by TomaszG** [cypress-io/cypress#6300] opened 2020-02-03 11:52 UTC
### Current behavior:

If `cy.fixture()` is used multiple times with different encodings within a single run then encoding from the first usage is preserved in the following usages.

### Desired behavior:

`cy.fixture()` should use provided encoding.

### Test code to reproduce

1. Prepare Excel .xlsx file and save it fixtures directory as `some.xlsx` (may work with text files too, not sure).
2. Run the following code, check the logged output from 2nd test - the correct binary string is logged:
```js
describe('encoding test', () => {
  it.skip('prints base64', () => {
    cy.fixture('some.xlsx', 'base64').then(out => cy.log(out));
  });

  it('prints binary', () => {
    cy.fixture('some.xlsx', 'binary').then(out => cy.log(out));
  });
});
```
3. Remove `.skip` from the first test, run the spec again.
4. Check the logged output from 2nd test - the base64 encoded string is logged even if the provided encoding is `binary`.

### Versions

Cypress 3.8.3
Chromium 79
macOS Catalina

**Comment by jennifer-shehane** [comment] 2020-02-04 05:00
I confirmed this is a bug. Duplicate of #4716

You can get around this by using `cy.readFile()` instead of `cy.fixture()`.

### Test with one fixture definition

```js
describe('encoding test', () => {
  it('prints binary', () => {
    cy.fixture('testing.xlsx', 'binary').then(out => cy.log(out));
  });
});
```

<img width="428" alt="Screen Shot 2020-02-04 at 11 17 56 AM" src="https://user-images.githubusercontent.com/1271364/73714706-1c824580-4740-11ea-9771-5c944cd44fae.png">

### Test with two fixture definitions with different encoding

<img width="423" alt="Screen Shot 2020-02-04 at 11 18 08 AM" src="https://user-images.githubusercontent.com/1271364/73714742-36238d00-4740-11ea-9e30-a8bbe411fa46.png">

### Test with 2 separate files read in works

```js
describe('encoding test', () => {
  it('prints base64', () => {
    cy.fixture('testing.xlsx', 'base64').then(out => cy.log(out));
  });

  it('prints binary', () => {
    cy.fixture('testing-2.xlsx', 'binary').then(out => cy.log(out));
  });
});
```

**Closed by jennifer-shehane** 2020-02-04 05:00 UTC
