### ISSUE TITLE
Basic authentication does not work for internal tools that requires windows credential. 

### ISSUE THREAD

**Issue by jlhuo** [cypress-io/cypress#2780] opened 2018-11-14 18:14 UTC
### Is this a Feature or Bug?
bug

### Current behavior:
The basic authentication does not work for internal tools which requires windows credential. I tried the HttpAuth for testcafe and selenium, both of them work.

### Steps to reproduce:
Refer to this link for the details about this bug.
https://stackoverflow.com/questions/53270912/basic-authentication-does-not-work-for-local-testing-with-cypress

**Comment by jennifer-shehane** [comment] 2018-11-14 22:02
Duplicate of https://github.com/cypress-io/cypress/issues/908

**Closed by jennifer-shehane** 2018-11-14 22:02 UTC
