### ISSUE TITLE
Sometimes previous passed cases are failed again when launch cypress through "npx cypress open --component"

### ISSUE THREAD

**Issue by 787681277** [cypress-io/cypress#24177] opened 2022-10-08 08:46 UTC
### Current behavior

1）launch cypress through "npx cypress open --component"
2） Add new test case in that spec

Precondition:source code are not changed and test case are not changed
Sometimes previous passed test cases(cy.get(activeTab2).click();) are failed again, which would Increase debugging difficulty in Cypress GUI mode.

In other word, sometime get "focus" UI screenshot when use .click() command.
Sometime get "click" UI screenshot when use .click() command.
This would bring inconsistency.

Comments:
This issue does not occur when run test case through "npx cypress run --component" in Cypress NON-GUI mode

### Desired behavior

1）launch cypress through "npx cypress open --component"
2）Add/remove/modify new test case in that spec

Previous passed cases/Never changed test case should always pass

### Test code to reproduce

1）launch cypress through "npx cypress open --component"
2）Add/remove/modify new test case in that spec

Sometimes previous passed test cases are failed again, 

### Cypress Version

10.9

### Node version

12.20

### Operating System

12.6

**Comment by warrensplayer** [comment] 2022-10-18 12:49
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by 787681277** [comment] 2022-10-20 02:15
Reproduced code:
  it('button-click', () => {
    cy.mount(`<button type="button">Click Me!</button>`, {
      declarations: [],
      imports:[]
    });

    const buttonClick = '#root0 > button';
    cy.get(buttonClick).click();
    cy.matchImageSnapshot('buttonClick');
  })

Screenshots:
<img width="1301" alt="Screen Shot 2022-10-20 at 10 11 23" src="https://user-images.githubusercontent.com/26969223/196840375-ad07211d-dab0-4619-ac64-5259c16b4cfa.png">


Comments:
If use cypress cy.click() , launch cypress in GUI mode WITH command : npx cypress open --component 
Actual result: sometimes get accessibility blue border, seem like user type TAB key; sometime there is no blue border

Expected Result: In fact, there is no blue border If don't use cypress cy.click()  and then user directly click button in real webpage

**Comment by amehta265** [comment] 2022-10-27 22:40
@787681277 Thank you for providing the code snippet above. I have been able to replicate the test.

As you mentioned, the button that is mounted does not contain an accessibility border in its styles.
Cypress ensures that certain styles such as `ring-color` (which is responsible for the border around the button) are common across specific components irrespective of the browser the component is mounted upon. This is to ensure deterministic behavior so that every time we dispatch a  `click()` event to a button within your test you always receive the same result. As a design choice cypress has configured a ring color to be `rgba(59,130,246,0.5)` when a component is clicked. This is the reason for the blue accessibility color you notice around the button.

I have ran the test provided several times and the test has yielded the same deterministic result every time showing the blue outline and the test passes every time.

With regards to your comment about the blue border color not being applied in the real webpage, I agree that when the button in question is displayed on a webpage, it does not yield the same blue border color `onClick`. This is because certain css changes  are applied to the button by Cypress as explained above.

Overall, one of the premier functionalities of the `click()` event is to assert that the button mounted is registering and applying the event. This is true for the button mounted in this test. Therefore Cypress is being deterministic by clicking the button every time the test is run yielding to the same passed test.

**Comment by amehta265** [comment] 2022-10-27 22:42
Using the test block you provided above, the tests pass on every instance on my end. If this is not the case on your end and  If the test on your end is still [flaky](https://docs.cypress.io/guides/dashboard/flaky-test-management) kindly provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by 787681277** [comment] 2022-10-29 09:28
I cannot share the project's code, so choose simple code snippet above.When testing is running and there is no app cover the tested browser at the same time, the issue cannot be reproduced.

When testing is running and put an app cover the tested browser at the same time, the issue can be reproduced.
<img width="1309" alt="1" src="https://user-images.githubusercontent.com/26969223/198824229-4a0c5aca-7cf6-4972-909c-3c189f085790.png">
<img width="1245" alt="2" src="https://user-images.githubusercontent.com/26969223/198824238-6520ca0f-226d-4a5a-83a3-4b832481c0ab.png">
<img width="1303" alt="3" src="https://user-images.githubusercontent.com/26969223/198824251-764799e0-55d1-4173-8fc8-aaf1c96141e3.png">

**Comment by amehta265** [comment] 2022-10-31 17:08
@787681277 Could you help me by explaining what you mean by "app cover"?
I am unfortunately not able to understand the issue here. Is the same test file [flaky](https://docs.cypress.io/guides/dashboard/flaky-test-management) i.e. it passes sometimes and fails sometimes? If this is the case, I have not been able to reproduce this on my end. Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. If you can provide the tests that are passing and failing inconsistently I can better debug and help you.

Furthermore, what is the desired behavior here? If you do not want the ring color to show around the button, I explained in my previous comment why this happens. I have not been able to reproduce two instances where the outcome for the ring-color is different.

A reproduction of this issue in a github repo will be much more helpful!

**Comment by 787681277** [comment] 2022-11-02 12:41
How to understand "app cover"? I am sorry to make you confused. 
For original baseline image,When testing is running in targeted browser Chrome, I don't do anything until testing is over ====>There is border border when executing cy.click()
For current image,When testing is running in targeted browser Chrome, I am doing something else: use mouse to click another app A, that means another app A is becoming target object.====>There is NO border border when executing cy.click().

Compare current image to baseline image, the composite image will highlight the difference.

When testing is running in targeted browser Chrome, if I use mouse to click another target  element, which will get inconsistent result,this is my concern

**Comment by amehta265** [comment] 2022-11-07 15:25
@787681277 I believe I understand the issue you have raised. The blue border exists on `cy.click()`. However, when focus in removed from the button and set to another target (e.g. another app "A"), there is no border on the button.

My explanation would be that this is not inconsistent behavior rather, it speaks to the defaults exercised by the chrome browser. Browsers often have defaults for specified events. In this case `onClick` the chrome browser shows a blue border which is what you are seeing on click. When you click away from to another app 'A' you are shifting the focus from the button to the other application. And therefore the button loses the blue outline because it is no longer in focus. This is the default browser style. 

I don't believe this points to any inconsistency rather it mimics how components would be rendered in the actual browser.

Furthermore, the test suite provided has always passed on my machine. I do not see any previous passed cases failing. If this is not the case on your end and if tests are [flaky](https://docs.cypress.io/guides/dashboard/flaky-test-management), please provide a reproducible example

**Comment by 787681277** [comment] 2022-11-08 02:24
1) Not just **chrome**, the border also exists when using cy.click() on **Electron**.
2) Is there any way/config setting to remove the redundant border when using cy.click()?Because we need to test keyboard function accessibility.The blue border should be displayed when using keyboard operation. But the The blue border is also displayed when using cy.click(),this is incorrect UI,which will make us confused during automation debug
3) If choose to using plugin:  import "cypress-real-events/support";
  it('button-click-github issue', () => {
    cy.mount(`<button type="button">Click Me!</button>`, {
      declarations: [],
      imports:[]
    });

    const buttonClick = '#root0 > button';
    cy.get(buttonClick).click();
    cy.matchImageSnapshot('buttonClick-github-issue');
  })

In this case, there is no blue border when using cy.get(buttonClick).click(); this is expected behavior.

**Comment by marktnoonan** [comment] 2022-11-09 20:45
Hi, I am a late joiner to this issue. It sounds like:

- this is only a problem when using Cypress in open mode
- based on the default behavior of a browser when the tab has focus or not when a button click or focus event happens
- the failures you mention happen when screenshots no longer match due to the border not being applied if you have focused an app other than cypress

You could find a css solution like `button:not(:focus-visible) { outline: none }` and put that in a style block in your `component-index.html`, which might produce consistent results for this issue. I'm also curious if there is any global CSS in your application that's not making it to your component tests and is needed.

But I have a different suggestion, more general - you could not run visual regression checks from `open` mode. This focus issue is just one of many potential gotchas that would introduce noise into your image diffs. You can make a custom command (or add to one if you already have) and check the value of `Cypress.config().isInteractive` - if it's true, Cypress is in `open` mode and you could skip taking the image for diffing. What matters is the images taken using `cypress run`, where more things are controlled, like the size of cypress and the focus state of the browser tab. Then there is no interference from you focusing other apps and doing other work. Cypress controls for a lot of that, but still, it's an open browser in your OS.

Curious what you think of this - if the diffs from open mode are useful to you, that would be interesting info as well.

**Comment by marktnoonan** [comment] 2022-11-18 14:59
@787681277 I'm going to close this for now since we've had more than a week of inactivity.

**Closed as completed by marktnoonan** 2022-11-18 14:59 UTC
