### ISSUE TITLE
browserslist extends not working with cypress

### ISSUE THREAD

**Issue by coderica** [cypress-io/cypress#5252] opened 2019-09-30 21:50 UTC
### Current behavior:

Cypress tests break when extending a browserslist configuration. (https://github.com/cypress-io/cypress/issues/2983).

### Desired behavior:

There is currently a workaround by installing another 3rd party library, but Cypress should recognize & parse extended browserslists by default.

### Steps to reproduce: (app code and test code)

My project uses browser compatibility linting and extends an internal browserslist like so:

```
"browserslist": [
    "extends @mycompany/browserslist-config-frontend"
],
```

When running `cypress run` the following error occurs on all tests:

```
Error: [BABEL] .../cypress/integration/variants.spec.js: Cannot find module '@mycompany/browserslist-config-frontend' (While processing: "/home/jenkins/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/@babel/preset-env/lib/index.js") while parsing file: .../cypress/integration/variants.spec.js
```

### Versions

Cypress: 3.4.1
Mac OS: 10.14.5
Node: 18.16.1

**Comment by bjankord** [comment] 2020-01-02 17:14
I've been able to work around this some by using ENV variable for browserslist when calling cypress.

In my package.json, I've set up the following:
```
  "browserslist": {
    "production": [
      "extends @company/browserslist-config"
    ],
    "test": [
      "last 2 Chrome versions"
    ]
  },
```
Then when I run cypress, I set the browserlists env variable like so:
```
"cypress:run": "BROWSERSLIST_ENV=test cypress run",
```
More info on BROWSERSLIST_ENV: https://github.com/browserslist/browserslist#configuring-for-different-environments

It would be nice if cypress resolved the extended browserslists config though.

**Comment by jennifer-shehane** [comment] 2020-01-02 17:34
Closing as duplicate of https://github.com/cypress-io/cypress/issues/2983 Please do not open new issues for existing ones. We are more than willing to reopen closed issues based on the comments. Opening 2 issues creates confusion in the places people go to find help for their issue.

**Closed by jennifer-shehane** 2020-01-02 17:34 UTC
