### ISSUE TITLE
Some CSS styles are lost when attempting to view DOM snapshots

### ISSUE THREAD

**Issue by mattmazzola** [cypress-io/cypress#1807] opened 2018-05-29 22:31 UTC
### Current behavior:
When I run my tests the UI/website looks correct; however, after the tests are done and I click on one of the test commands/steps to view the DOM snapshot it seems to lose a subset of the styles causing the page to change.  It's odd that only a portion of the styles are lost, but it is still dramatically as paddings, borders, and fonts / icons go to the browser defaults.

I'm suspecting that somehow the DOM snapshot is missing a certain inline `<style>` node so maybe when I hover over that step it's removed and causing re-render of UI?

I'm displaying the site using CRA (create-react-app) which I believe tries to change CSS on the fly by writing inline nodes so maybe this is related, but given that when I load the side outside of Cypress it displays fine and displays fine during tests I'm assuming it is something with Cypress.

### Desired behavior:
Since cypress is able to load my UI in a good state when tests are running it should be able to preserve this while I view DOM snapshots.

### Steps to reproduce:
Not sure why it happens but there is video here:
https://1drv.ms/v/s!AlIBzruyxcE4m75Lvngt-Jf4JAtPbA

See that the tests run and pass. Then see the cursor open the test and click on a step.  The website loses styles and looks different.

### Versions
```
"cypress": "2.1.0",
```
Chrome Version 66.0.3359.181 (Official Build) (64-bit)
Windows Version	10.0.17134 Build 17134

**Comment by jennifer-shehane** [comment] 2018-05-29 23:49
Yeah - your suspicions about the inlining may be correct - they are not being restored properly when time traveling to the snapshot. Could you create a reproducible example? That would be the best way for us to determine the cause and address it. 

Also - this might fix your UI shaking 🙈https://github.com/cypress-io/cypress/issues/1620#issuecomment-383201503

**Comment by sbruggmann** [comment] 2018-07-11 14:13
sounds like #1499

**Comment by jennifer-shehane** [comment] 2019-04-24 16:28
Closing as duplicate of https://github.com/cypress-io/cypress/issues/2469

**Closed by jennifer-shehane** 2019-04-24 16:28 UTC
Labels: stage: needs information, topic: snapshot

**Comment by mattmazzola** [comment] 2019-04-24 16:39
Hmm, I'm not understanding how #2469 is a duplicate.  Maybe it's the wrong issue number?

This seemed related to the snapshots not saving the inline styles and that issue seemed related to configuring a CI environment which are unrelated.

Either way, this issue may have been resolved by some other fix because it seems to not occur on the 3.x cypress we are using now.

**Comment by jennifer-shehane** [comment] 2019-04-25 04:18
Sorry yah, duplicate of https://github.com/cypress-io/cypress/issues/1499
