### ISSUE TITLE
Page doesn't load after I changed the origin or different url

### ISSUE THREAD

**Issue by adnanerlansyah403** [cypress-io/cypress#28449] opened 2023-12-03 00:27 UTC
### Current behavior

I can't access the page to interact with element because of the page doesn't want to load, I know this is the same issue as this one 
[https://github.com/cypress-io/cypress/issues/2938](https://github.com/cypress-io/cypress/issues/2938) but unfortunately I still can't fixed yet although already following the workaround or solutions that already gave on that thread. 

- Process Page Loading: 
![image](https://github.com/cypress-io/cypress/assets/88386921/bdf77d96-fd4a-4ccc-aa82-07fe730ec40f)
- Error Page Doesn't Load:
![image](https://github.com/cypress-io/cypress/assets/88386921/6829cc2c-465c-4d50-aa21-54b59893071f)

### Desired behavior

I want to access the other page or authentication page to interact with the element on it.

### Test code to reproduce

This is my code reproducable : https://github.com/adnanerlansyah403/cypress-test-tiny

### Cypress Version

^13.6.0

### Node version

16.0.1

### Operating System

Windows 10 Pro

### Other

Oh yeah this error is only happening on chrome & edge browser, but for the firefox it's working well

**Comment by adnanerlansyah403** [comment] 2023-12-04 10:07
Please help me out with this issue

**Comment by adnanerlansyah403** [comment] 2023-12-06 13:22
Please Keep it up for this threaad

**Comment by jennifer-shehane** [comment] 2023-12-13 15:55
Duplicate of https://github.com/cypress-io/cypress/issues/2118

**Closed as completed by jennifer-shehane** 2023-12-13 15:55 UTC
Labels: type: duplicate
