### ISSUE TITLE
Allow configuration for log expansion in test runner

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress#6446] opened 2020-02-13 16:22 UTC
### Current behavior:

Currently, there is no way to configure the behavior for expanding or opening the logs when running the test. This results in videos where the logs may not be visible if the test runs before they expand.

### Desired behavior:

Allow for configuration of the timeout or behavior of how the logs expand when running the tests.

### Test code to reproduce

Should be reproducible by running any test and viewing the video to see behavior of logs. Logs will only expand if the test exceeds the current timeout value for the log expansion.

### Versions

All

**Comment by jennifer-shehane** [comment] 2020-02-14 09:30
Duplicate of #6270

**Closed by jennifer-shehane** 2020-02-14 09:30 UTC
Labels: topic: video 📹, type: enhancement
