### ISSUE TITLE
Unable to fully download cypress on windows 10 using npm

### ISSUE THREAD

**Issue by codu6860** [cypress-io/cypress#17358] opened 2021-07-15 23:55 UTC
### Current behavior

I have just gotten an internship and my boss wants me to write cypress code for testing their website. I love this application and hope to use it back in school but whenever I try to install via npm, I run into issues with cypress not fully installing.

I first create the package.JSON file via `npm init`. I don't change any of the settings. When I input `npm install cypress --save-dev` into my console, I get the following message:
<img width="464" alt="cypress-intall_1" src="https://user-images.githubusercontent.com/59852820/125871450-03980f64-6dd0-4c0a-9347-a869a056dabe.PNG">
This only seems to install the node_modules folder as well as package-lock.JSON. I then attempt to run cypress via `npx cypress run` and get the following result
<img width="463" alt="cypress-install_2" src="https://user-images.githubusercontent.com/59852820/125871643-24303cc6-f590-4efe-a522-44f02ef58ca6.PNG">

I have tried to other alternatives such as `npx cypress install force` but with this method it doesn't seem to allow me to make modifications to the original package.JSON file as I am planning on using both mailslurp and typescript to be used with cypress. 

### Cypress Version

7.7.0

### Package Manager

npm

### Operating system

Windows

**Comment by JohnnyFun** [comment] 2021-07-21 14:03
Looks like it installed, but it simply didn't find your `cypress.json` file when it went to run tests in the directory you're in.

**Comment by flotwig** [comment] 2021-11-19 22:00
Yeah, as @JohnnyFun mentioned, this does not seem like a bug, but intended behavior. Closing.

**Closed by flotwig** 2021-11-19 22:00 UTC
Labels: topic: installation
