### ISSUE TITLE
How to solve iframe nesting in iframe

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#7437] opened 2020-05-21 08:07 UTC
### Current behavior:

Alicloud login page web, iframe nested iframe， how to solve iframe test。

- iframe `login-iframe-2019`
- sub-iframe `alibaba-login-box`

script:
```js
cy.get('iframe[id="alibaba-login-box"]').then(($iframe) => {
        const $body = $iframe.contents().find('body')
        cy.wrap($body).find('input#fm-login-id').type("44444")
    })
```
fail:
AssertionError
```
Timed out retrying: Expected to find element: iframe[id="alibaba-login-box"], but never found it.
```

### Versions

cypress： 4.1.0
system： linux
browser: chrome 31

**Comment by jennifer-shehane** [comment] 2020-05-21 11:38
Cypress does not natively support access to iframes within the application under test. See #136 for existing workarounds. 

Duplicate of #136 

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Closed by jennifer-shehane** 2020-05-21 11:38 UTC
