### ISSUE TITLE
Adding "pass/fail" on video recording filename

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#8131] opened 2020-07-30 18:01 UTC
### Current behavior:

For now, the video recording filename is locked to `videos/**/*.mp4`

### Desired behavior:

It would be nice to do something similar with the screenshot `screenshots/**/*(failed).png`

Such as `videos/**/*(fail 2/5).mp4`

So we can do targeted uploading to save some CI time.

**Comment by jennifer-shehane** [comment] 2020-08-03 09:10
Duplicate of #6998

**Closed by jennifer-shehane** 2020-08-03 09:10 UTC
