### ISSUE TITLE
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

### ISSUE THREAD

**Issue by TheDutchCoder** [cypress-io/cypress#7913] opened 2020-07-08 00:57 UTC
### Current behavior:
In Buildkite, I randomly get these errors. Not sure why, normally my tests seem to work okay, but sometimes this happens for no real reason.

### Desired behavior:
Not to fail making a connection to devtools

### Test code to reproduce
This happens on Buildkite, just running a regular suite of tests, so I can't reproduce this in a standalone repo.

### Versions
Cypress 4.9.0
Alpine Linux
Chrome headless

**Comment by jennifer-shehane** [comment] 2020-07-08 04:51
Duplicate of #7450

**Closed by jennifer-shehane** 2020-07-08 04:51 UTC

**Comment by Praveentrp** [comment] 2022-02-06 09:41
Hi @jennifer-shehane   - Our team is facing the same issue in Windows 10 locally while trying to run through chrome browser either in headless or headed. Could you please provide a solution to this?

**Comment by sbal5488** [comment] 2023-01-25 17:42
I have the same problem 
Environment = AWS Lambda + Docker + Cypress 12.4.0 + Node JS 16
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds
