### ISSUE TITLE
cy.visit() fails to load domains staples.com and bestbuy.com

### ISSUE THREAD

**Issue by eyalgutf** [cypress-io/cypress#2778] opened 2018-11-14 15:34 UTC
Current behavior:
cy.visit() fails to load domains ww.stapels.com and www.bestbuy.com
 
Steps to reproduce:
```js
cy.visit("https://www.staples.com")
```

Desired behavior:
cy.visit() does not fail on domains www.stapels.com and www.bestbuy.com

**Comment by jennifer-shehane** [comment] 2018-11-14 19:45
Hey @eyalgutf, I just want to confirm that we test the correct urls. 

Did you mean `www.staples.com`? `www.stapels.com` does not resolve to any website in or out of Cypress. Also, ensure you have the 3 w's, because you wrote `ww.stapels.com`.

**Comment by eyalgutf** [comment] 2018-11-14 21:40
You are correct. The correct url is www.staples.com
B.T.W -- this issue also happens on www.bestbuy.com.

**Comment by eyalgutf** [comment] 2018-11-27 13:12
Adding GAP.com to the list of domains cypress visit fails on

**Comment by jennifer-shehane** [comment] 2018-11-27 16:09
Hey @eyalgutf, could you confirm the error that is being printed when trying to visit each site? Is it the same error? Perhaps take a screenshot of the errors?

**Comment by eyalgutf** [comment] 2018-11-29 15:13
The Error for  on www.staples.com and www.bestbuy.com is the same and slightly different for ww.gap.com.

These are the only domains cy.visit fails on. The rest of the domains I tried are working.
The errors and settings are given below.

Staples/bestbuy error:
![image](https://user-images.githubusercontent.com/36811393/49231062-ca39ec00-f3f9-11e8-863e-034489c821cf.png)

Gap error:
![image](https://user-images.githubusercontent.com/36811393/49231101-dde55280-f3f9-11e8-87ce-32af29c57bdc.png)


### Steps to reproduce:
var url_list =
    [
            {testname:'gap',url:"https://www.gap.com"},
            {testname:'staples',url:"https://www.staples.com"},
            {testname:'bestbuy',url:"https://www.bestbuy.com"},
    ];
describe('batchname', () => {
    beforeEach(() => {
    });
    afterEach(() => {
    });
    for (const element of url_list) {
        it(element.testname, () => {
            cy.on('uncaught:exception', (err, runnable) => {
                return false
            })
            cy.visit(element.url);
        });
    }
});
### Versions
Cypress Version: 3.1.2, , OS: Windows 10, browser : Chrome

Tnx a bunch :)

**Comment by jennifer-shehane** [comment] 2019-07-24 05:52
Ran in 3.4.0 - still an issue. 

Tests

```js
it('yoox', function () {
  cy.visit('www.yoox.com/it/donna/shoponline')
})

it('bestbuy', function () {
  cy.visit('https://www.bestbuy.com')
})

it('staples', function () {
  cy.visit('https://www.staples.com')
})
```

DEBUG logs

[domains.log](https://github.com/cypress-io/cypress/files/3425215/domains.log)

**Comment by flotwig** [comment] 2019-07-29 14:16
When I try loading bestbuy.com manually using `request-promise`, I get the same ESOCKETTIMEDOUT error:

```js
const rp = require('request-promise')
rp({
  "url": "https://www.bestbuy.com/",
  "agent": false,
  "timeout: 30000
}).then(console.log).catch(console.error)
```

...leading me to think it's a bug in the `request` library, or maybe in Node's HTTP library. Still happens with Node 12. Gonna keep looking in to it.

**Comment by jennifer-shehane** [comment] 2019-12-12 04:16
@flotwig Found this issue explaining why this happens for bestbuy in the `request` library: https://github.com/request/request/issues/2738#issuecomment-369324868

**Comment by flotwig** [comment] 2019-12-12 15:29
@jennifer-shehane interesting, i wonder if we are mistakenly filtering out a header or something from the request, causing them to reject our request

**Comment by jennifer-shehane** [comment] 2020-07-28 04:54
Going to close this as a duplicate of #7062 which shows more examples.

**Closed by jennifer-shehane** 2020-07-28 04:54 UTC
Labels: stage: needs investigating, type: bug

**Comment by marinatedpork** [comment] 2021-04-17 22:35
Websites like these my be reached by adding the following headers:

spec:
```
cy.visit(url, {
  headers: {
    "Accept": "application/json, text/plain, */*",
    "User-Agent": "axios/0.18.0"
  }
})
```

package.json:
```
"dependencies": {
  "cypress": "^3.8.3"
}
```

**Comment by SethJimenez** [comment] 2021-06-24 13:54
> cy.visit(url, {
>   headers: {
>     "Accept": "application/json, text/plain, */*",
>     "User-Agent": "axios/0.18.0"
>   }
> })
I got the same issue and this worked for me. 
Thanks, @marinatedpork !!
