### ISSUE TITLE
dblclick events chain is missing mouseout

### ISSUE THREAD

**Issue by drumslave-git** [cypress-io/cypress#5533] opened 2019-10-30 10:36 UTC
### Current behavior:
`dblclick` does not trigger `mouseout`

### Desired behavior:
`dblclick` does trigger `mouseout`

### Steps to reproduce: (app code and test code)

I have such react code (simplified)

```jsx
<div
  onMouseEnter={this.onMouseEnter}
  onMouseLeave={this.onMouseLeave}
>
  Div A
</div>
<div
  onMouseEnter={this.onMouseEnter}
  onMouseLeave={this.onMouseLeave}
>
  Div B
</div>
```

`onMouseEnter` - start timeout of 300ms, show tooltip after 300ms
`onMouseLeave` - clear timeout

Cypress code (simplified)

```js
cy.get('div').then($divs => {
  $divs.each((idx, $div) => {
     cy.wrap($div).scrollIntoView().dblclick()
     cy.wait(300);
     cy.focused().blur();
  })
})
```

Problem is that when it comes to second div - tooltip is shown for first one.
My guess is that `dblclick` triggers `mouseover`, but not `mouseout`, because adding
`cy.wrap($div).scrollIntoView().dblclick().trigger('mouseout', {force: true})`
fixes this issue

### Versions
Cypress: 3.5.0
OS: Windows 10
Browser: Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by Bkucera** [comment] 2019-10-31 18:07
Hi @drumslave-git, I'm closing this as a duplicate of #5500 - please checkout that issue for a lengthy discussion about this.

I've opened an issue to add a new option to click commands that would send `mouseleave`/`mouseout` immediately after the click. #5552

**Closed by Bkucera** 2019-10-31 18:07 UTC
Labels: stage: needs information
