### ISSUE TITLE
CLI (env) options not correctly parsed

### ISSUE THREAD

**Issue by jdvegmond** [cypress-io/cypress#27176] opened 2023-06-30 13:28 UTC
### Current behavior

When running the following command
`npx cypress open --env cyuser=dummyUser,cypassword=dummyPassword`
When I open the project settings I see the following:  `cyuser: 'dummyUser cypassword=dummyPassword'`, and is highlighted in yellow instead of pink/red. The property 'cypassword' does not exist.

![afbeelding](https://github.com/cypress-io/cypress/assets/32638636/1c16b047-e4b2-4587-b862-4bd40f670d7f)

![afbeelding](https://github.com/cypress-io/cypress/assets/32638636/e39c5a7d-dad9-42e0-84b2-8b8bfa1dd826)

### Desired behavior

I would expect that when I open the Project Settings I would see two properties under 'env', one `cyuser: 'dummyUser'` and one `cypassword: 'dummyPassword'`.

### Test code to reproduce

This is the failing test code:

`npx cypress open --env cyuser=dummyUser,cypassword=dummyPassword`

### Cypress Version

12.16.0 (but found it in 12.14.0)

### Node version

v16.18.1

### Operating System

Windows 11

**Comment by mike-plummer** [comment] 2023-06-30 13:46
@jdvegmond Sorry to hear you're having issues. I just tried you example on a Unix system using the latest version of Cypress but cannot reproduce - the environment variables are being parsed correctly. This makes me wonder if you've hit a unique behavior of the command prompt you're using, possibly caused by special processing of the comma or equal symbols. I assume you're using the built-in Windows Command Prompt? Have you tried enclosing the argument value in quotes like this?

`npx cypress open --env "cyuser=dummyUser,cypassword=dummyPassword"`

**Comment by jdvegmond** [comment] 2023-06-30 13:52
I was actually using PowerShell (latest version, 7.3.5)
But using the quotes did help actually. Thanks for the suggestion.

Maybe https://docs.cypress.io/guides/guides/environment-variables#From-the-command-line-or-CI should get a remark that it might be useful to put the complete string in quotes?

**Comment by lmiller1990** [comment] 2023-07-06 01:52
Great - sounds like you solved the issue - I'll close this since we don't have any work to do in this repo.

Always good to update docs, please review @jdvegmond https://github.com/cypress-io/cypress-documentation/pull/5361

**Closed as completed by lmiller1990** 2023-07-06 01:52 UTC
