### ISSUE TITLE
doc.createTreeWalker is not a function

### ISSUE THREAD

**Issue by afreix-bricks** [cypress-io/cypress#20813] opened 2022-03-28 22:40 UTC
### Current behavior

When running a Cypress test via the Test Runner:

`node ./cypress/cypress.js -- open` 

I'm seeing this error thrown from cypress:

```
cypress_runner.js:175886 TypeError: doc.createTreeWalker is not a function
    at findShadowRoots (https://localhost:8080/__cypress/runner/cypress_runner.js:166508:22)
    at collectRoots (https://localhost:8080/__cypress/runner/cypress_runner.js:166488:24)
    at Object.findAllShadowRoots (https://localhost:8080/__cypress/runner/cypress_runner.js:166498:10)
    at getElements (https://localhost:8080/__cypress/runner/cypress_runner.js:143851:45)
From previous event:
    at resolveElements (https://localhost:8080/__cypress/runner/cypress_runner.js:143905:27)
    at $Cy.get (https://localhost:8080/__cypress/runner/cypress_runner.js:143916:14)
    at $Cy.now (https://localhost:8080/__cypress/runner/cypress_runner.js:156327:47)
    at resolveElements (https://localhost:8080/__cypress/runner/cypress_runner.js:144084:19)
From previous event:
    at tryFn (https://localhost:8080/__cypress/runner/cypress_runner.js:151739:21)
    at whenStable (https://localhost:8080/__cypress/runner/cypress_runner.js:151777:12)
    at https://localhost:8080/__cypress/runner/cypress_runner.js:151269:16
From previous event:
    at $Cy.retry (https://localhost:8080/__cypress/runner/cypress_runner.js:151249:38)
    at onFailFn (https://localhost:8080/__cypress/runner/cypress_runner.js:135999:19)
From previous event:
    at $Cy.verifyUpcomingAssertions (https://localhost:8080/__cypress/runner/cypress_runner.js:136006:63)
    at https://localhost:8080/__cypress/runner/cypress_runner.js:144090:21
From previous event:
    at resolveElements (https://localhost:8080/__cypress/runner/cypress_runner.js:144084:52)
    at tryFn (https://localhost:8080/__cypress/runner/cypress_runner.js:151739:21)
    at whenStable (https://localhost:8080/__cypress/runner/cypress_runner.js:151777:12)
    at https://localhost:8080/__cypress/runner/cypress_runner.js:151269:16
```

### Desired behavior

No error is thrown

### Test code to reproduce

I can't share the full source code due to my company's policies. Maybe a simpler repro could be made once I have some idea of where this issue is coming from.

The line of code where this is failing is 
`cy.findByRole('tabpanel', { hidden: false }).findByTestId('RichCommandFooter').contains('runtime');`

### Cypress Version

8.1.0

### Other

Happy to provide more details. Our `cypress.js` file has a good amount going on it, but I'm not sure what would be most relevant to help debug.

`@testing-library/cypress` is on version 8.0.1

<img width="597" alt="Screen Shot 2022-03-28 at 6 40 44 PM" src="https://user-images.githubusercontent.com/76451129/160498769-4371c1e9-efaa-41c9-bcab-42cae34bb57f.png">

**Comment by davidmunechika** [comment] 2022-03-29 13:31
Thanks for opening an issue! I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by elaides** [comment] 2022-04-25 20:30
I upgraded Cypress to v.9.5.4 but keep receiveing this "TypeError: doc.createTreeWalker is not a function".  
From what i see possible rootcause may be :    when i try to loop over array of page elements and check that one of them .contains("some value")

**Comment by davidmunechika** [comment] 2022-04-26 18:59
Hmm...looks like it is an unhandled case where querying the shadow dom doesn't work correctly. Do you think you might be able to create a simple test failure repro based on that possible root cause? That would help out a lot, thanks!

**Comment by jesperancinha** [comment] 2022-09-17 14:13
Hi there, I can reproduce this issue consistently on my project. Please find an example here: https://gitlab.com/jesperancinha/moving-objects-service-root/-/jobs/3043475557. I'm not sure if this has anything to do with cypress. I can only reproduce it consistently with Edge and this happens while upgrading an okta library. It seems pretty random, but it would be great if cypress could handle this in any way.

This is what I'm getting:

```shell
moving-objects-service-root-e2e-edge-1  |      TypeError: doc.createTreeWalker is not a function
moving-objects-service-root-e2e-edge-1  |       at findShadowRoots (http://192.168.0.15:8080/__cypress/runner/cypress_runner.js:169004:22)
moving-objects-service-root-e2e-edge-1  |       at collectRoots (http://192.168.0.15:8080/__cypress/runner/cypress_runner.js:168984:24)
moving-objects-service-root-e2e-edge-1  |       at Object.findAllShadowRoots (http://192.168.0.15:8080/__cypress/runner/cypress_runner.js:168994:10)
moving-objects-service-root-e2e-edge-1  |       at getElements (http://192.168.0.15:8080/__cypress/runner/cypress_runner.js:143111:93)
moving-objects-service-root-e2e-edge-1  |       at tryCatcher (http://192.168.0.15:8080/__cypress/runner/cypress_runner.js:11318:23)
moving-objects-service-root-e2e-edge-1  |       at Function.Promise.attempt.Promise.try (http://192.168.0.15:8080/__cypress/runner/cypress_runner.js:8592:29)
```

**Comment by steve-schreiner** [comment] 2022-10-20 13:54
Any news on this?  It's blocking our tests, and we run into it often.  Any workaround?  We have paid support.  Thanks

**Comment by AtofStryker** [comment] 2022-10-24 21:11
Hi @steve-schreiner. I am starting to take a look into this issue. I am trying to run @jesperancinha 's repository but I am having trouble getting it going this time (was able to start it before for a different issue). Are either of you able to help me provide a small reproduction to consistently reproduce the issue? 

My guess is the `includeShadowDom` option is set to true, and when looking up the shadow root within cypress in the case stability may/may not be achieved, the root returns null and causes a `createTreeWalker is not a function` error. I could be wrong, but I can likely confirm this suspicion with a reproduction.

**Comment by steve-schreiner** [comment] 2022-10-24 21:25
Hi Bill,

I'm adding 3 people from my QA team that can assist you.

Thanks,
Steve

**Comment by laradiaz** [comment] 2022-10-25 22:04
> createTreeWalker is not a function

Hi Bill, how are you? As Steve mentioned, we have been encountering this **_doc.createTreeWalker_** error in the tests since August. We didn't have the **includeShadowDom** option set to true at the time, when we ran into this error we tried setting it to true and for a while it worked and the error disappeared although with flakiness. 
Currently the error **_createTreeWalker is not a function_** persists in our tests. Making it difficult for us to continue with the normal workflow. 
Thank you!

**Comment by laradiaz** [comment] 2022-10-27 18:51
Hi Bill and Matt, how are you? As Steve mentioned, we have been encountering this `doc.createTreeWalker` error in the tests since August. We didn’t have the `includeShadowDom` option set to true at the time, when we ran into this error we tried setting it to true and for a while it worked and the error disappeared although with flakiness.
Currently the error `createTreeWalker is not a function` persists in our tests. Making it difficult for us to continue with the normal workflow.
In the last two days, I disabled the `includeShadowDom` option again, and many components (such as checkbox, dropdowns, etc) started to crash. So disabling this flag is not an option for our app. Hopefully we can resolve this error soon
Thank you!

**Comment by mschile** [comment] 2022-10-28 14:19
Thanks @laradiaz, unfortunately, I haven't been able to recreate the issue. If anyone has a project I can look at and debug or if you are able to create the issue using the [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) project that would be great.

**Comment by aquanow-rtran** [comment] 2022-10-31 16:58
Hi everyone, would just like to leave my two cents on this issue as I am also experiencing it. I have noticed in my tests that the `createTreeWalker is not a function` error occurs when the tests are trying to `get` an element that is currently being loaded in. Have seen two different instances where it has happened. Once when I'm performing a `cy.get().contains()` and another where my table hasn't fully loaded in yet. 
My workaround was to change `cy.get().contains()` to `cy.contains(selector, content)` and to input a `{timeout: 10000}`
Hope my solution is able to at least get your tests running until a proper fix could be applied

**Comment by yarmakR** [comment] 2022-10-31 18:00
@mschile @aquanow-rtran we have it repeated in this and the following runs as well https://dashboard.cypress.io/projects/zz1ryi/runs/3684/overview/411c1463-3742-46aa-9ff7-1c200c3a9363
any thoughts?

**Comment by mschile** [comment] 2022-11-02 21:00
@yarmakR, unfortunately, I don't have access to view your project. Do you have a link to your project code that I could debug?

**Comment by ryanthemanuel** [comment] 2022-11-14 17:28
@laradiaz, were you able to potentially get a publicly sharable reproduction of this issue as @mschile suggested?

**Comment by laradiaz** [comment] 2022-11-14 17:44
> @laradiaz, were you able to potentially get a publicly sharable reproduction of this issue as @mschile suggested?

No, I'm sorry. But this approach https://github.com/cypress-io/cypress/issues/20813#issuecomment-1297390114 help us to resolve the issue for now. 

Thank you!

**Comment by bahmutov** [comment] 2022-11-21 17:11
@AtofStryker in your comment to https://github.com/cypress-io/cypress/issues/944#issuecomment-1322276443 you are using `cy.origin` incorrectly, but I cannot even post that the site is refusing to load since that issue has been closed
<img width="1140" alt="Screen Shot 2022-11-21 at 12 08 17" src="https://user-images.githubusercontent.com/2212006/203117907-d6420119-250c-445c-aa11-059354537e5c.png">

**Comment by AtofStryker** [comment] 2022-11-21 17:37
@bahmutov I created #24756 to track that issue, which is open and you should be able to comment. On the issue, could you elaborate what is wrong with the usage of `cy.origin`? It's a very contrived example but should work the same. Going to move over to that thread.

**Comment by BlueWinds** [comment] 2022-11-28 16:58
This looks suspiciously like another manifestation of the same underlaying bug as https://github.com/cypress-io/cypress/issues/7306. We've spent a lot of work looking into that for Cypress 12.0.0 - my hope is that this issue will be resolved in Cy12, which should come out next week.

Going to assign myself so I remember to follow up here after release.

**Comment by jesperancinha** [comment] 2022-12-04 14:09
Hi there, I'm not sure if this is helpful at the moment since you are going to release version 12 at some point, I'm looking forward to that, but just wanted to share a build where this is now almost always happening:

https://github.com/jesperancinha/moving-objects-service-root/actions/runs/3613540356/jobs/6089355201

This is part of a dependabot PR:

https://github.com/jesperancinha/moving-objects-service-root/pull/9

**Comment by tkrabel-db** [comment] 2023-01-03 14:42
Does anyone know how I could [work with iframes in cypress](https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/) without calling the `find()` method separately from `get()`? IIUC, the whole idea of working with iframes leverages that paradigm (`.get().<...>.find()`).

**Comment by GrayedFox** [comment] 2023-01-19 01:02
Thanks to @aquanow-rtran for the hint:

> I have noticed in my tests that the createTreeWalker is not a function error occurs when the tests are trying to get an element that is currently being loaded in. 

Rather than target the element you want to work with directly a decent work around is to target the nearest parent you know to be already loaded (or unaffected by dynamic JavaScript) and do a preliminary loading check first. Here is an example that relies on the [waitForStableDom plugin](https://www.npmjs.com/package/cypress-wait-for-stable-dom) in TypeScript using the PageObject pattern (I know I know, POs are now an anti pattern, don't @ me)

```ts
abstract class BasePage {
  get finishedLoading(): Cypress.Chainable {
    return cy.get('[loading="true"]').should('have.length', 0);
  }

  waitForDomReady(): Cypress.Chainable {
    return this.finishedLoading.waitForStableDOM();
  }
```

You might want to check for disabled too depending on your use case. My problem was updating an item inside a shopping cart which involved updating the image and other product details, hence the item would become disabled and still be loading after the the requests we're waited on:

```ts
// ... derived class ...
  saveEdits() {
    cy.intercept('POST', BasePage.urls.api).as('graphql');
    this.saveEditsButton.click();
    cy.wait(['@graphql', '@graphql']);
    this.waitForDomReady(); // ensures items finish loading and DOM has settled
    return this;
  }
```

**Comment by jennifer-shehane** [comment] 2023-12-17 18:55
Closing. Hopefully this is resolved in v12, but there wasn’t a reproducible example provided here to investigate.

**Closed by jennifer-shehane** 2023-12-17 18:55 UTC
