### ISSUE TITLE
"Cypress verification timed out" occurs sporadically in CI

### ISSUE THREAD

**Issue by justinpincar** [cypress-io/cypress#4613] opened 2019-06-29 20:44 UTC
This occurs only in our gitlab CI environment, failing about half the time. I've compared the successful and unsuccessful log output but it looks identical up until the line where it fails. I'm not sure how to debug any further from here. I have cypress caching configured for these examples but it happens without anything cached also.

Verification failure output below:
```
DEBUG=cypress:* npx cypress install
2019-06-29T20:25:29.144Z cypress:cli cli starts with arguments ["/usr/local/bin/node","/builds/usurp-power/engine/packages/usurp-web/node_modules/.bin/cypress","install"]
2019-06-29T20:25:29.146Z cypress:cli NODE_OPTIONS is not set
2019-06-29T20:25:29.146Z cypress:cli program parsing arguments
2019-06-29T20:25:34.050Z cypress:cli parsed cli options {}
2019-06-29T20:25:34.051Z cypress:cli installing with options {}
2019-06-29T20:25:34.052Z cypress:cli version in package.json is 3.3.1
2019-06-29T20:25:34.052Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.052Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.053Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.053Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.054Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T20:25:34.054Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.054Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.054Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T20:25:34.054Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.054Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.055Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T20:25:34.058Z cypress:cli Reading binary package.json from: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/package.json
2019-06-29T20:25:34.087Z cypress:cli installed version is 3.3.1 version needed is 3.3.1
2019-06-29T20:25:34.088Z cypress:cli Not downloading or installing binary
$ DEBUG=cypress:* npx cypress verify
2019-06-29T20:25:34.537Z cypress:cli cli starts with arguments ["/usr/local/bin/node","/builds/usurp-power/engine/packages/usurp-web/node_modules/.bin/cypress","verify"]
2019-06-29T20:25:34.539Z cypress:cli NODE_OPTIONS is not set
2019-06-29T20:25:34.539Z cypress:cli program parsing arguments
2019-06-29T20:25:34.541Z cypress:cli parsed cli options {}
2019-06-29T20:25:34.706Z cypress:cli verifying Cypress app
2019-06-29T20:25:34.707Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.707Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T20:25:34.707Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T20:25:34.708Z cypress:cli checking environment variables
2019-06-29T20:25:34.711Z cypress:cli checking if executable exists /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress
2019-06-29T20:25:34.712Z cypress:cli Binary is executable? : true
2019-06-29T20:25:34.713Z cypress:cli binaryDir is  /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress
2019-06-29T20:25:34.713Z cypress:cli Reading binary package.json from: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/package.json
2019-06-29T20:25:34.716Z cypress:cli Found binary version 3.3.1 installed in: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress
2019-06-29T20:25:34.730Z cypress:cli { verified: true }
2019-06-29T20:25:34.730Z cypress:cli is Verified ? true
2019-06-29T20:25:34.731Z cypress:cli force verify
2019-06-29T20:25:34.731Z cypress:cli running binary verification check 3.3.1
[20:25:34]  Verifying Cypress can run /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress [started]
2019-06-29T20:25:34.737Z cypress:cli clearing out the verified version
2019-06-29T20:25:34.739Z cypress:cli undefined DISPLAY environment variable
2019-06-29T20:25:34.739Z cypress:cli Cypress will spawn its own Xvfb
2019-06-29T20:25:34.739Z cypress:cli needs Xvfb? true
2019-06-29T20:25:34.740Z cypress:cli Starting Xvfb
2019-06-29T20:25:35.725Z cypress:cli running smoke test
2019-06-29T20:25:35.725Z cypress:cli using Cypress executable /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress
2019-06-29T20:25:35.726Z cypress:cli smoke test command: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=890
2019-06-29T20:25:45.853Z cypress:cli Smoke test failed: { Error: Command failed: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=890
2019-06-29T20:25:42.995Z cypress:ts Running without ts-node hook in environment "production"
2019-06-29T20:25:43.631Z cypress:server:cypress starting cypress with argv [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress', '--smoke-test', '--ping=890' ]
2019-06-29T20:25:45.338Z cypress:server:args argv array: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress', '--smoke-test', '--ping=890' ]
2019-06-29T20:25:45.344Z cypress:server:args argv parsed: { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server' }
2019-06-29T20:25:45.345Z cypress:server:args options { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server', config: {} }
2019-06-29T20:25:45.346Z cypress:server:args argv options: { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server', config: {}, pong: 890 }


    at makeError (/builds/usurp-power/engine/packages/usurp-web/node_modules/cypress/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/builds/usurp-power/engine/packages/usurp-web/node_modules/cypress/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: null,
  stdout: '',
  stderr:
   '2019-06-29T20:25:42.995Z cypress:ts Running without ts-node hook in environment "production"\n2019-06-29T20:25:43.631Z cypress:server:cypress starting cypress with argv [ \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress\', \'--smoke-test\', \'--ping=890\' ]\n2019-06-29T20:25:45.338Z cypress:server:args argv array: [ \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress\', \'--smoke-test\', \'--ping=890\' ]\n2019-06-29T20:25:45.344Z cypress:server:args argv parsed: { _: [ \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress\' ], smokeTest: true, ping: 890, cwd: \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server\' }\n2019-06-29T20:25:45.345Z cypress:server:args options { _: [ \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress\' ], smokeTest: true, ping: 890, cwd: \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server\', config: {} }\n2019-06-29T20:25:45.346Z cypress:server:args argv options: { _: [ \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress\' ], smokeTest: true, ping: 890, cwd: \'/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server\', config: {}, pong: 890 }\n',
  failed: true,
  signal: 'SIGTERM',
  cmd:
   '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=890',
  timedOut: true,
  killed: true }
2019-06-29T20:25:45.855Z cypress:cli error message: 2019-06-29T20:25:42.995Z cypress:ts Running without ts-node hook in environment "production"
2019-06-29T20:25:43.631Z cypress:server:cypress starting cypress with argv [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress', '--smoke-test', '--ping=890' ]
2019-06-29T20:25:45.338Z cypress:server:args argv array: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress', '--smoke-test', '--ping=890' ]
2019-06-29T20:25:45.344Z cypress:server:args argv parsed: { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server' }
2019-06-29T20:25:45.345Z cypress:server:args options { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server', config: {} }
2019-06-29T20:25:45.346Z cypress:server:args argv options: { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server', config: {}, pong: 890 }

2019-06-29T20:25:45.856Z cypress:cli error timedOut is true
2019-06-29T20:25:47.406Z cypress:cli Stopping Xvfb
[20:25:47]  Verifying Cypress can run /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress [failed]
Cypress verification timed out.

This command failed with the following output:

/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=890

----------

2019-06-29T20:25:42.995Z cypress:ts Running without ts-node hook in environment "production"
2019-06-29T20:25:43.631Z cypress:server:cypress starting cypress with argv [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress', '--smoke-test', '--ping=890' ]
2019-06-29T20:25:45.338Z cypress:server:args argv array: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress', '--smoke-test', '--ping=890' ]
2019-06-29T20:25:45.344Z cypress:server:args argv parsed: { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server' }
2019-06-29T20:25:45.345Z cypress:server:args options { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server', config: {} }
2019-06-29T20:25:45.346Z cypress:server:args argv options: { _: [ '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress' ], smokeTest: true, ping: 890, cwd: '/builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/packages/server', config: {}, pong: 890 }

----------

Platform: linux (Debian - 8.11)
Cypress Version: 3.3.1
```

Verification success output below:
```
$ DEBUG=cypress:* npx cypress install
2019-06-29T19:47:14.959Z cypress:cli cli starts with arguments ["/usr/local/bin/node","/builds/usurp-power/engine/packages/usurp-web/node_modules/.bin/cypress","install"]
2019-06-29T19:47:14.961Z cypress:cli NODE_OPTIONS is not set
2019-06-29T19:47:14.961Z cypress:cli program parsing arguments
2019-06-29T19:47:19.725Z cypress:cli parsed cli options {}
2019-06-29T19:47:19.726Z cypress:cli installing with options {}
2019-06-29T19:47:19.727Z cypress:cli version in package.json is 3.3.1
2019-06-29T19:47:19.727Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.727Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.728Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.728Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.728Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T19:47:19.729Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.729Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.729Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T19:47:19.729Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.729Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:19.729Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T19:47:19.732Z cypress:cli Reading binary package.json from: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/package.json
2019-06-29T19:47:19.783Z cypress:cli installed version is 3.3.1 version needed is 3.3.1
2019-06-29T19:47:19.784Z cypress:cli Not downloading or installing binary
$ DEBUG=cypress:* npx cypress verify
2019-06-29T19:47:20.289Z cypress:cli cli starts with arguments ["/usr/local/bin/node","/builds/usurp-power/engine/packages/usurp-web/node_modules/.bin/cypress","verify"]
2019-06-29T19:47:20.291Z cypress:cli NODE_OPTIONS is not set
2019-06-29T19:47:20.292Z cypress:cli program parsing arguments
2019-06-29T19:47:20.294Z cypress:cli parsed cli options {}
2019-06-29T19:47:20.428Z cypress:cli verifying Cypress app
2019-06-29T19:47:20.429Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:20.429Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2019-06-29T19:47:20.429Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/usurp-power/engine/cache/Cypress
2019-06-29T19:47:20.430Z cypress:cli checking environment variables
2019-06-29T19:47:20.433Z cypress:cli checking if executable exists /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress
2019-06-29T19:47:20.434Z cypress:cli Binary is executable? : true
2019-06-29T19:47:20.435Z cypress:cli binaryDir is  /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress
2019-06-29T19:47:20.435Z cypress:cli Reading binary package.json from: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/resources/app/package.json
2019-06-29T19:47:20.438Z cypress:cli Found binary version 3.3.1 installed in: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress
2019-06-29T19:47:20.449Z cypress:cli { verified: true }
2019-06-29T19:47:20.449Z cypress:cli is Verified ? true
2019-06-29T19:47:20.449Z cypress:cli force verify
2019-06-29T19:47:20.450Z cypress:cli running binary verification check 3.3.1
[19:47:20]  Verifying Cypress can run /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress [started]
2019-06-29T19:47:20.458Z cypress:cli clearing out the verified version
2019-06-29T19:47:20.460Z cypress:cli undefined DISPLAY environment variable
2019-06-29T19:47:20.460Z cypress:cli Cypress will spawn its own Xvfb
2019-06-29T19:47:20.460Z cypress:cli needs Xvfb? true
2019-06-29T19:47:20.460Z cypress:cli Starting Xvfb
2019-06-29T19:47:21.456Z cypress:cli running smoke test
2019-06-29T19:47:21.456Z cypress:cli using Cypress executable /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress
2019-06-29T19:47:21.456Z cypress:cli smoke test command: /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress/Cypress --smoke-test --ping=224
2019-06-29T19:47:31.328Z cypress:cli smoke test stdout "224"
2019-06-29T19:47:31.329Z cypress:cli Stopping Xvfb
2019-06-29T19:47:31.424Z cypress:cli write verified: true
2019-06-29T19:47:31.425Z cypress:cli could not read binary_state.json file
[19:47:31]  Verifying Cypress can run /builds/usurp-power/engine/cache/Cypress/3.3.1/Cypress [completed]```

**Comment by jennifer-shehane** [comment] 2019-07-01 07:47
This looks to be a duplicate of https://github.com/cypress-io/cypress/issues/3116 - we **really** need a reproducible error and the exact details of this failure in order to address it though.

**Closed by jennifer-shehane** 2019-07-01 07:47 UTC
Labels: cli, type: bug

**Comment by jennifer-shehane** [comment] 2019-07-01 08:47
In order to direct better focus on the overall problem that is being described in several issues - we opened one issue to track this behavior https://github.com/cypress-io/cypress/issues/4624 Please add any information about how we can reproduce this bug there. 🙏
