### ISSUE TITLE
cy.wait() does not see call when initial intercept registration is overwritten with intercept with mocked data

### ISSUE THREAD

**Issue by Kapoetski3** [cypress-io/cypress#16109] opened 2021-04-21 09:59 UTC
We are trying to migrate our cy.route functionality to cy.intercept.

And while doing so we came across an issue with cy.wait. 

When we register an intercept without mocked data, and then overwrite that registration with an identical intercept, only with mocked data the cy.wait no longer sees the call.
This will cause the wait to fail on timeout.

The same functionality does work with cy.route.

### Current behavior
We see that cypress correctly intercepts the call, and gives back the mocked data. 
cy.wait does not see the call and fails after timing out. 
![afbeelding](https://user-images.githubusercontent.com/35066969/115535017-a8768380-a298-11eb-9905-5e713fd8b941.png)

### Desired behavior
cy.wait sees the mocked call and correctly awaits it.

### Test code to reproduce
https://github.com/Kapoetski3/cypress-test-tiny

### Versions
7.1

**Comment by jennifer-shehane** [comment] 2021-04-21 17:07
I can recreate this behavior with the example below - the `cy.wait()` never resolves with the intercept example. Going to have to check on whether there's an existing issue. This seems unexpected to me. 

```js

it('test cy.intercept()', () => {
  cy.intercept('/users').as('getUsers')
  cy.intercept('/users', { body: { data: 'fake data' }, statusCode: 200 }).as('getUsers')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  cy.wait('@getUsers')
})

it('test cy.route()', () => {
  cy.server()
  cy.route('/users').as('getUsers')
  cy.route('/users', { body: { data: 'fake data' }}).as('getUsers')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  cy.wait('@getUsers')
})
```

<img width="570" alt="Screen Shot 2021-04-21 at 12 06 49 PM" src="https://user-images.githubusercontent.com/1271364/115593450-20917900-a29a-11eb-8fa7-05a14f45b8b4.png">

**Comment by jennifer-shehane** [comment] 2021-04-21 17:13
So it looks like this is a duplicate of https://github.com/cypress-io/cypress/issues/15823

Closing as duplicate.

**Closed by jennifer-shehane** 2021-04-21 17:13 UTC
