### ISSUE TITLE
TypeScript: Make use of sourcemaps when displaying code snippet in Test Runner

### ISSUE THREAD

**Issue by xumepadismal** [cypress-io/cypress#9332] opened 2020-11-25 16:39 UTC
### What would you like?

it would be very useful to take into account sourcemaps generated by TypeScript. Here is an screenshot for demonstration. As you can see the line numbers are mismatch and Cypress displays transpiled JS instead of authored TS.

![image](https://user-images.githubusercontent.com/7963211/100256432-72cda880-2f4d-11eb-8268-3316f335e776.png)

### Minimal reproduction repo

https://github.com/xumepadismal/cypress

**Comment by bahmutov** [comment] 2020-11-25 17:40
Can you please provide the repo with a reproducible example? We worked hard to take source maps into account, and for most cases it should just work.

**Comment by xumepadismal** [comment] 2020-11-25 18:25
@bahmutov sure. I've added the link to the issue description

**Comment by jennifer-shehane** [comment] 2020-11-30 06:10
I can reproduce this with the provided code. The line numbers don't add up to what's in the original file. Not sure if this is expected or not.

When you click on the line number to go in IDE, it also jumps to line 8 which is the incorrect line.

```js
describe('TypeScript Spec', () => {
  it('should do something', () => {
    // Some comments and blank lines
    cy.wrap(5)

    // Some comments and blank lines
    cy.wrap(5)

    // Some comments and blank lines
    cy.wrap(5).then(v => expect(v).to.equal(10));
  });
});
```

<img width="690" alt="Screen Shot 2020-11-30 at 12 39 47 PM" src="https://user-images.githubusercontent.com/1271364/100574793-285f7980-3309-11eb-8b51-ac9d0fcdbe5d.png">


<img width="548" alt="Screen Shot 2020-11-30 at 12 39 13 PM" src="https://user-images.githubusercontent.com/1271364/100574773-1f6ea800-3309-11eb-9eda-2f6a48754478.png">

**Comment by xumepadismal** [comment] 2021-07-27 13:07
Hey guys! Apparently it seems this issue was fixed somehow. Maybe some transitive dependency update? I'm using Cypress 8.0.0 and just realized that line numbers are matched just fine, My IDE opens in the right place, fantastic :)

@jennifer-shehane as you were able to reproduce the issue in the past could you try it now and confirm it's fixed please?

**Comment by BlueWinds** [comment] 2022-05-20 02:28
I'm going to close this issue as duplicate of https://github.com/cypress-io/cypress/issues/21562 - that one contains a reproducible example, and the author here says the issue is fixed for them.

It looks like at least some users are still encountering this.

**Closed by BlueWinds** 2022-05-20 02:28 UTC
Labels: type: unexpected behavior, pkg/reporter, stage: needs investigating, topic: typescript, topic: code frame
