### ISSUE TITLE
cy.exec fails when Cypress is started from some terminals

### ISSUE THREAD

**Issue by sandra-ouadghiri** [cypress-io/cypress#15538] opened 2021-03-17 15:08 UTC
### Current behavior
On a **Windows** machine (not tested on a linux system)

OK scenario
- Launch cypress (npx cypress open) from a **cmd** terminal or a **powershell** terminal
- Execute _cy.exec('whoami')_ (or any other simple OS command)
- Cypress manage to run the cy.exec code successfully

KO scenario
- Launch cypress (npx cypress open) from a **bash** terminal, for example **git-bash**
- Execute the same code
- Cypress raise an error including the bash terminal path

I discovered this when trying to change my terminal in IntelliJ (Ctrl-Alt-S, Tool > Terminal). I reproduced it outside of my IDE with terminals I launched manually. This only occurs when cypress is in the loop : all terminal replies correctly to my command (whoami) when asked directly.

### Results
-> Manual run of _whoami_ -> **OK in git bash**, cmd & powershell
-> Cypress execution when cypress launched from cmd or powershell -> OK
![image](https://user-images.githubusercontent.com/77396345/111488903-f77d4600-8739-11eb-8942-a52553c55fa8.png)

-> Cypress execution when cypress launched from git bash -> KO
![image](https://user-images.githubusercontent.com/77396345/111491555-3e6c3b00-873c-11eb-8abf-c0c2e34e8beb.png)

Please note that my windows path is ok ; my windows computer resolves git bash correctly.
Could it be because the windows path to git bash has a space (Program Files) ? Both the "Program:" and the  \ and / that are not cohesive in the error message make me think this is the part cypress does not handle well. Maybe a lead.

### Desired behavior
I want my code to work the same way (=to compile) agnosticly from what terminal Cypress was launched from.
Today, some dev may not be able to execute my valid test code solely because of their terminal preference. That's an issue to me.

### Test code to reproduce
This produce. Other commands too. As long as the command inside cy.exec is valid, you can produce with it.
  ```
  cy.exec('whoami')
```

### Versions
Produced in 6.5.0

**Comment by jennifer-shehane** [comment] 2021-03-17 18:33
I think this is a duplicate of https://github.com/cypress-io/cypress/issues/789 - some Windows users experience this in other terminals. But if you can shed some light on the issue that would be 👍

**Closed by jennifer-shehane** 2021-03-17 18:33 UTC

**Comment by sandra-ouadghiri** [comment] 2021-03-18 08:28
Thanks @jennifer-shehane for the triage. You are absolutly right.
