### ISSUE TITLE
cypress verify fails on windows

### ISSUE THREAD

**Issue by SeriousM** [cypress-io/cypress#1959] opened 2018-06-15 13:03 UTC
### Current behavior:

I'm trying to create a windows-docker image for cypress.
This is required as I want to run my product docker-images (windows) with cypress in a docker-compose execution.

```
C:\> docker run -it --rm stefanscherer/node-windows:8-nanoserver cmd
# switches into container
C:\> mkdir work
C:\> cd work
C:\work> npm i -y
C:\work> npm i --save-dev cypress@3.0.1
# till now everything works well
C:\work> set DEBUG=*
C:\work> node_modules\.bin\cypress verify
```

```
  cypress:cli cli starts with arguments ["C:\\nodejs\\node.exe","C:\\work\\node_modules\\cypress\\bin\\cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +0ms
  cypress:cli parsed cli options {} +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe +0ms
  cypress:cli binaryDir is  C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress +32ms
  cypress:cli Found binary version 3.0.1 installed in: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress +0ms
  cypress:cli could not read binary_state.json file +0ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +0ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 3.0.1 +0ms
It looks like this is your first time using Cypress: 3.0.1

  cypress:cli clearing out the verified version +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe +0ms
  cypress:cli needs XVFB? false +0ms
  cypress:cli smoke test command: C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress\Cypress.exe --smoke-test --ping=247 +15ms
 ?  Verifying Cypress can run C:\Users\ContainerAdministrator\AppData\Local\Cypress\Cache\3.0.1\Cypress
   ? Cypress Version: 3.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------
----------

Platform: win32 (10.0.17134)
Cypress Version: 3.0.1
```

I don't know what dependency is missing.
I tried to [trace the error](https://github.com/cypress-io/cypress/blob/master/cli/lib/tasks/verify.js#L84) but wasn't able to be successful.
The dependencies from the official [cypress/base:8 image](https://github.com/cypress-io/cypress-docker-images/blob/master/base/8/Dockerfile#L4) don't help me either as I don't know what's the windows counterpart and which is missing.

Running the same on my windows dev machine works like a charm.

### Desired behavior:

The installation verification works or at least tells which dependency is missing.

### Versions

Cypress: 3.0.1

```
>yarn -v
1.6.0
>node -v
v8.11.3
>npm -v
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.11.3
npm info ok
5.6.0
```

**Comment by Bkucera** [comment] 2018-06-15 16:15
duplicate of https://github.com/cypress-io/cypress/issues/1866

**Closed** 2018-06-15 16:39 UTC
Labels: OS: windows, type: duplicate
