### ISSUE TITLE
Cypress + Azure pipeline + "hover" breakpoint = hover breakpoint always reached/active

### ISSUE THREAD

**Issue by AlexandreQ-LeBreton** [cypress-io/cypress#7096] opened 2020-04-21 15:14 UTC
### Current behavior:

We are working on Cypress solution to test criticals functionals paths of a Website. We are using Azure DevOps to launch Cypress (Azure pipelines).

The website is responsive with 2 breakpoints. The first one is a resolution screen breakpoint and the second one detect if propertie "hover" is active or not. Thanks to the last one, we can detect if the device is a touch screen.

The problem is that Cypress launched by Azure test each time (no matter resolution configure in Cypress & no matter browser used) the website in tablet mode.

NB : Cypress launched in a local machine works fine

### Desired behavior:

We wish that Cypress in Azure test website in desktop mode.
Something to configure in Azure to allow Cypress to work fine ?

### Versions
Azure + Cypress 3.8.3 (with cucumber & NTLM)

**Comment by jennifer-shehane** [comment] 2020-04-22 07:57
Cypress tests run within the browser will be restricted by the actual physical size of the screen.

Likely this irregularity is due to the actual screensize of the machine you are running within Azure being smaller than expected. You'll need to see if there is a way to configure the literal screen size to be larger. 

You could also run via Chrome headless and manually set the screen size as described here: https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless-Chrome

I'm not completely sure why this should matter though if you are setting `cy.viewport()` of your actual application under test. We would need an example of your test in order to verify. 

Also, I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog). Your issue may have already been fixed.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-04-22 07:57 UTC

**Comment by AlexandreQ-LeBreton** [comment] 2020-05-11 09:46
Hello Jennifer, 

For now, this is the list of things we've already done to try to resolve our problem :

### Tests perform
To launch Cypress + Chrome/Electron in headless/headed mod
To launch Cypress with specific viewport (cy.viewport) and specific User agent
To launch Cypress in console mod
To specify a resolution for the virtual screen's pipeline => pipeline doesn't need any screen to work so it's not possible to specify any resolution screen...

Have you got some other ideas ?

Thanks anyway for your supply ! ;)
