### ISSUE TITLE
I can't execute tests in Chrome headless mode

### ISSUE THREAD

**Issue by kagannikita** [cypress-io/cypress#29428] opened 2024-04-29 06:56 UTC
### Current behavior

Hi, everyone! I try execute tests in headless mode in Chrome, but I can't. I don't use Docker. I use Chrome v124.

### Test code to reproduce
```
Still waiting to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.
This usually indicates there was a problem opening the Chrome browser.
The CDP port requested was 61063.
Error: connect ECONNREFUSED 127.0.0.1:61063
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
```

### Cypress Version

13.7.2

### Node version

21.1.0

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment] 2024-08-27 14:29
Closing as duplicate of https://github.com/cypress-io/cypress/issues/27830

**Closed as not planned by jennifer-shehane** 2024-08-27 14:29 UTC
Labels: type: duplicate
