### ISSUE TITLE
Cypress retries do not work when including reporter options

### ISSUE THREAD

**Issue by deane187** [cypress-io/cypress#8988] opened 2020-10-27 15:31 UTC
### Current behavior
When including reporter options in the `cypress.json`

```json
"reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporterOpts.json"
  }
```
there are no retry logs shown when a test is run with `cypress run`
<img width="633" alt="Screenshot 2020-10-27 at 17 01 41" src="https://user-images.githubusercontent.com/27348820/97320065-20c63400-1876-11eb-8571-6798a0953a8d.png">

### Desired behavior
When removing the reporter options:
```json
"reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporterOpts.json"
  }
```
The test shows the desired output in the terminal.
<img width="551" alt="Screenshot 2020-10-27 at 17 04 14" src="https://user-images.githubusercontent.com/27348820/97320451-7b5f9000-1876-11eb-8e95-56419a6ad06f.png">

`cypress open` is not affected when the reporter options are included.
<img width="636" alt="Screenshot 2020-10-27 at 17 28 29" src="https://user-images.githubusercontent.com/27348820/97407924-13578b00-1904-11eb-95e9-b748b8ab8aec.png">

### Test code to reproduce
Created a repo with 1 small spec file that should fail -> https://github.com/deane187/cypress-retry-test.git

### Versions

Cypress:    5.5.0                                                                              
Browser:    Electron 85 (headless)                                                             
Specs:      1 found (examples/actions.spec.js)    
OS: Mac OS Catilina

**Comment by jennifer-shehane** [comment] 2020-10-28 07:58
The retry attempts are occuring during `cypress run` with the provided repo. You can see this from the recorded video and the fact that there are 4 screenshots taken (1 on each attempt). 

<img width="861" alt="Screen Shot 2020-10-28 at 2 27 36 PM" src="https://user-images.githubusercontent.com/1271364/97407957-d1d9d680-1929-11eb-9d38-5046dfd2024c.png">

The issue is that it's just not reporting the retries to the stdout. Duplicate of https://github.com/cypress-io/cypress/issues/8474

**Closed by jennifer-shehane** 2020-10-28 07:58 UTC
