### ISSUE TITLE
Getting Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'getRequestInfo') at n.handleWindowCallback

### ISSUE THREAD

**Issue by sonajoseph96** [cypress-io/cypress#26418] opened 2023-04-04 06:37 UTC
### Current behavior

When I try to Sign in to my application it gives error as below. Anyway to be able to fix this issue?

1) Launch website
2) Click on Sign In
3) Enter username and click on Next
4) Enter password and click on Sign In
5) Click on Yes button on popup asking to remain signed in /// at this stage the error is thrown instead of taking user to the home page of the application
```
Unhandled Exception: Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'getRequestInfo') TypeError: Cannot read properties of null (reading 'getRequestInfo') at n.handleWindowCallback (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:1404594) at e.handleCallback (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:826004) at e.canActivate (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:546320) at t.project (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:385923) at t._next (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:1377291) at t.next (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:89143) at t._subscribe (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:275508) at e._trySubscribe (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:66374) at e.subscribe (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:66203) at e.call (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:1377064)
```

### Test code to reproduce
```js
it('jjsLogin', () => {
  cy.visit('https://videoportaluat.azurewebsites.net/home',)

  cy.contains('Sign In').click()   //Sign In button

  cy.origin('https://login.microsoftonline.com', () => {
    cy.get('#i0116')
    .invoke('val', 'myusername')   //enter actual username  xxx@jjswaste.com.au
    .trigger('input')

    cy.get('#idSIButton9').click()    //Next button
  })
 
  cy.origin('https://login.microsoftonline.com', () => {
    cy.get('#i0118')
    .invoke('val', 'mypassword')   //enter actual password
    .trigger('input')

    cy.get('#idSIButton9').click()   // Sign in button

    cy.wait(1000)npx
    cy.get('#idSIButton9').click()  // Yes button
  })
})

```
### Cypress Version

12.8.1

### Node version

16.16.0

### Operating System

Windows 11

### Debug Logs

```shell
Unhandled Exception: Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'getRequestInfo') TypeError: Cannot read properties of null (reading 'getRequestInfo') at n.handleWindowCallback (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:1404594) at e.handleCallback (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:826004) at e.canActivate (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:546320) at t.project (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:385923) at t._next (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:1377291) at t.next (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:89143) at t._subscribe (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:275508) at e._trySubscribe (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:66374) at e.subscribe (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:66203) at e.call (https://videoportaluat.azurewebsites.net/main.7f65065004dccc833631.bundle.js:1:1377064)
```

### Other

Unable to share real username and password as it is sensitive info

**Comment by emilyrohrbough** [comment] 2023-04-04 13:56
Progression of https://github.com/cypress-io/cypress/issues/26223

**Comment by emilyrohrbough** [comment] 2023-04-04 14:00
@sonajoseph96 This error appears to be coming from your Application's bundle per the stack trace. Cypress does not parse for `.getRequestInfo()` at any point. Please take a look at your application to see what is expected vs what is received.

At this point without additional information, we cannot pin-point if this is an actual issue caused by Cypress or an issue being surface when running Cypress.

**Comment by sonajoseph96** [comment] 2023-04-05 04:14
Logging into the application (outside Cypress) works correctly and user is able to land on the home page. 
It is only when the application is launched via Cypress that the issue occurs. 

Is there any workaround atleast even if it is temporary or not best practice?  

Also, not sure if it has anything to do with iFrames on the home page

**Comment by mjhenkes** [comment] 2023-04-14 17:44
You may need to track down where `getRequestInfo` is getting called. With cypress tests are run in the browser, that means your page is loaded in an iframe an which can make references like 'window.top' mean other thing.

You could try enabling `experimentalModifyObstructiveThirdPartyCode` which will attempt to fix such issues on third party scripts.

**Comment by sonajoseph96** [comment] 2023-04-17 23:54
Thanks @mjhenkes , however the experimentalModifyObstructiveThirdPartyCode is already true. Yes, not sure why and how a getRequestInfo is getting called. 

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    
    
    //Network and Security
    experimentalSessionAndOrigin: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    modifyObstructiveCode: false,
    testIsolation: false,
    chromeWebSecurity: false,
    experimentalNetworkStubbing: true,
    experimentalInteractiveRunEvents: true,

   //Timeout and Logging in
    defaultCommandTimeout: 30000,
    requestTimeout: 30000,
    responseTimeout: 30000,
    pageLoadTimeout: 60000,
    viewportHeight: 1080,
    viewportWidth: 1920,

  //Base URL and environment variables
    baseUrl: 'https://videoportaluat.azurewebsites.net/home',
    maxUrlLength: 7000,

    
    setupNodeEvents(on, config) {

    },
  },
```

**Comment by chrisbreiding** [comment] 2023-05-10 20:41
> Is there any workaround atleast even if it is temporary or not best practice?

You could try ignoring the error. It might allow the tests to continue, but your site may not be functioning correctly if that error is being thrown.

```js
it('jjsLogin', () => {
  cy.on('uncaught:exception', (err) => {
	  if (err.message.includes('getRequestInfo')) return false
  })

  // ... rest of test ...
})
```

We'll need a way to reproduce this issue in order to have a way forward debugging it. Otherwise, we'll have to close this issue.

**Comment by sonajoseph96** [comment] 2023-05-10 22:33
Hi
Many thanks for your input. will try it out. Please feel free to close the issue. They have decided to change some things on the website from the developers end in order to be able to resolve this issue. Thank you again for all your time.

**Closed as not planned** 2023-05-11 11:51 UTC
Labels: stage: needs information
