### ISSUE TITLE
test not rerunning when file changed

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#865] opened 2017-11-02 03:06 UTC
- Operating System: Windows 10
- Cypress Version: 1.0.3
- Browser Version: 60.3

### Is this a Feature or Bug?
Bug

### Current behavior:

Change file -> test doesnt refresh

### Desired behavior:

It should refresh
### How to reproduce:

N/A

#### Test code:

N/A
```js

```

**Comment by brian-mann** [comment] 2017-11-02 03:38
Duplicate of https://github.com/cypress-io/cypress/issues/712

**Closed by brian-mann** 2017-11-02 03:38 UTC

**Comment by Imlus** [comment] 2017-11-23 11:28
Is there a temporary workaround for this? As it gets annoying pretty fast :)

**Comment by egucciar** [comment] 2017-11-23 15:30
This issue seems resolved 1.1.1
