### ISSUE TITLE
Adding feature to have folders open collapsed

### ISSUE THREAD

**Issue by Alex-passiv** [cypress-io/cypress#14529] opened 2021-01-13 14:13 UTC
Hi, 

Love the tool and have no issues with it this is just a minor request. I have a lot of different tests and folders for each (around 40 tests or so) my request is that it would be nice to have a feature which allows the user to select how the "cypress-open" applications opens. It would be nice if it opened with just the folders for each, right now it feels like it's screaming at me with all my files open and exposed. 
Again, not a huge deal but just wanted to bring this up. 
Best,

Alex

**Comment by bahmutov** [comment] 2021-01-13 15:35
duplicate of #14528

**Closed by bahmutov** 2021-01-13 15:35 UTC
