### ISSUE TITLE
Promises and chainables behave differently

### ISSUE THREAD

**Issue by phistuck** [cypress-io/cypress#24523] opened 2022-11-03 14:44 UTC
### Current behavior

```js
cy.wrap('/').then(
  () => cy.wrap('/login').then(() => {})
).then(o => console.log('cy what?', o));

// cy what? /login

Promise.resolve('/').then(
  () => Promise.resolve('/login').then(() => {})
).then(o => console.log('promise what?', o));

// promise what? undefined
```

### Desired behavior

`// cy what? undefined`

### Test code to reproduce

^

### Cypress Version

9.5.3

### Node version

16.15.1

### Operating System

macOS 11.3.1

### Other

Might not be a bug, but using `.then` makes it look like a `Promise`, so you expect it to behave the same way.

**Comment by Narretz** [comment] 2022-11-04 10:26
I mean the introduction to Cypress tells us that cypress commands don't return promises: https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#The-Cypress-Command-Queue

**Comment by lmiller1990** [comment] 2022-11-07 05:39
I think this is probably a duplicate of https://github.com/cypress-io/cypress/issues/1417.

Once you know about the command queue, it makes sense. Admittedly, I used Cypress for about 2-3 years before I read that page, maybe it needs more emphasis in the docs.

Other than #1417 (actually reworking things to support `async/await` which is very difficult, since lots of Cypress feature like retry-ability relies on the command queue architecture), I'm not sure what action to take, other than perhaps improving the docs around this? Would that be useful @phistuck?

**Comment by jennifer-shehane** [comment] 2023-02-09 16:05
Closing as duplicate of #1417

**Closed as completed by jennifer-shehane** 2023-02-09 16:05 UTC
