### ISSUE TITLE
I saw this issue and noticed OP is using zsh as their shell (which is the new default on macOS catalina). I'm also using zsh on ubuntu and had the same issue. I don't have the issue when switching my default shell back to bash with `chsh -s /bin/bash`.

### ISSUE THREAD

**Issue by deedee990** [cypress-io/cypress#6164] opened 2020-01-14 20:51 UTC
I saw this issue and noticed OP is using zsh as their shell (which is the new default on macOS catalina). I'm also using zsh on ubuntu and had the same issue. I don't have the issue when switching my default shell back to bash with `chsh -s /bin/bash`.

_Originally posted by @amkoehler in https://github.com/cypress-io/cypress/issues/6081#issuecomment-574367676_

**Comment by jennifer-shehane** [comment] 2020-01-15 07:33
Closing as duplicate of https://github.com/cypress-io/cypress/issues/6081 Please comment in the existing issue instead of opening new issues that are already open. Thanks.

**Closed by jennifer-shehane** 2020-01-15 07:33 UTC
