### ISSUE TITLE
contains(0) does not show zero in the command log

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1119] opened 2017-12-21 16:30 UTC
## small bug in Cypress 1.4.0

Repo with reproducible test https://github.com/bahmutov/test-cy-contains-zero 

The following test

```js
it('contains string zero', () => {
  cy.visit('index.html')
  cy.get('#zero').contains('0')
})

it('contains number zero', () => {
  cy.visit('index.html')
  cy.get('#zero').contains(0)
})
```

Shows "0" in the first test, but shows nothing in the second test. 

<img width="723" alt="contains-zero" src="https://user-images.githubusercontent.com/2212006/34264846-27277048-e642-11e7-9f5d-25b007f69097.png">

Should show "CONTAINS 0" in the second test

**Comment by jennifer-shehane** [comment] 2017-12-21 19:16
I had opened this a long time ago. It appears it is still in our private repo and was never opened when we went open source. Going to check over to see if there are any other leftover issues left private. https://github.com/cypress-io/cypress-monorepo/issues/334

**Comment by jennifer-shehane** [comment] 2019-07-11 09:08
This issue is still happening in 3.4.0

**Comment by dario-piotrowicz** [comment] 2021-06-17 22:11
@jennifer-shehane as of 7.5.0  the issue is still happening so I created a PR to fix it

I just noticed you were assigned to this issue, I hope you don't mind me opening the PR for it :cry: 
(it didn't look like you were actively looking into it anyhow)

**Closed** 2021-06-30 17:17 UTC
Labels: first-timers-only, pkg/reporter, stage: needs review, type: bug, type: user experience

**Comment by jennifer-shehane** [comment] 2021-07-06 14:01
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
