### ISSUE TITLE
GET 401 issue when trying to login in cypress

### ISSUE THREAD

**Issue by bulacsobilly** [cypress-io/cypress#5819] opened 2019-11-29 00:51 UTC
I'am getting a 401 error when trying to login using cypress. The error is not showing when trying to login manually. It seems to be a problem in cypress. here is my code. a simple login

```js
it("Smoke test in Strata Admin", () => {
  cy.visit("url");   
  // insert Username
  cy.get('.login-credentials-container .input-group:first-of-type .form-control')
  .type('email').should('have.value', 'email')
  // insert Password
  cy.get('.login-credentials-container .input-group:last-of-type .form-control')
  .type('pw').should('have.value', 'pw')
  // click Login
  cy.get('.btn-primary').click()
});
```

![Screen Shot 2019-11-29 at 8 46 48 AM](https://user-images.githubusercontent.com/58247746/69836665-4ec97f80-1285-11ea-936c-128743f935d4.png)

**Comment by jennifer-shehane** [comment] 2019-11-29 04:53
Hey @bulacsobilly, we would need more information in order to reproduce the issue and figure out what the problem is. Likely there is something involving cookies or localStorage with logging in - perhaps they need to be sent to a 3rd party more specifically. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-11-29 04:53 UTC

**Comment by bulacsobilly** [comment] 2019-11-29 05:40
Hi @jennifer-shehane we are using ID token when logging in. in my investigation, it is not getting the token before logging in
