### ISSUE TITLE
Refused to display

### ISSUE THREAD

**Issue by 2RajShaikh** [cypress-io/cypress#4125] opened 2019-05-05 00:31 UTC
I am facing below problem when I try to do SSO login using google auth form,

Refused to display 'https://accounts.google.com/o/oauth2/v2/auth?.....' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### Current behavior:

![image](https://user-images.githubusercontent.com/43998403/57186288-9718ee80-6eaa-11e9-806b-5ec1c9e58c00.png)

### Desired behavior:

Should show the google authentication login form.
It should not require any code changes in order to fix this problem, page should be rendered out of the box just like other frameworks (puppeteer, protractor, etc...) supports.

### Versions

Cypress: 3.1.0
Browser: Electron

**Comment by jennifer-shehane** [comment] 2019-05-06 05:15
Duplicate of https://github.com/cypress-io/cypress/issues/3459

**Closed by jennifer-shehane** 2019-05-06 05:15 UTC
