### ISSUE TITLE
Right side data cleared after test case failed

### ISSUE THREAD

**Issue by mohanbabu-zumen** [cypress-io/cypress#25220] opened 2022-12-20 07:21 UTC
### Current behavior

1. Run the test case
2. Once it is failed, right side (running side) data was cleared and shows Default blank page
3. **It was very tough to fix the test case in same browser.**

**Please consider this as a High priority** 

### Desired behavior

Right-side data shouldn't be cleared

### Test code to reproduce

https://user-images.githubusercontent.com/102032328/208606941-52903b88-3caa-48db-b90a-782c2e4c4be3.mp4

### Cypress Version

12.1.0

### Node version

16.17.0

### Operating System

Windows 11

**Comment by mohanbabu-zumen** [comment] 2022-12-20 08:28
cc: @cypress-app-bot @CypressAdam

**Comment by mike-plummer** [comment] 2022-12-20 18:58
Hi @mohanbabu-zumen , sorry to hear you're having issues. There were some changes made in recent versions of Cypress to add new [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation) behavior which will clear the runner _**before**_ each test, but it shouldn't have the behavior you're seeing. It appears that you are using some libraries on top of Cypress; Cucumber perhaps? It's possible that library isn't handling errors quite right or isn't working nicely with this new isolation feature.

I am not able to reproduce the behavior you're seeing in a pure Cypress test, so it would be helpful to have a basic reproduction of the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mohanbabu-zumen** [comment] 2022-12-21 05:04
Hi @mike-plummer, Thanks for the reply. 

@mike-plummer / @lmiller1990 - We are using the cucumber framework in cypress. Might it be the cause?

**Comment by mike-plummer** [comment] 2022-12-21 19:04
@mohanbabu-zumen It's impossible to know without a reproduction, but my best guess from the video is that it's due to the skipped test in your suite (it appears you're using Tags?). Cypress sees that there is another test in the execution context so the [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation) behavior clears the browser context but the decision to run the test is made by Mocha which skips the execution after we've prepared for it. I'm going to ask the team whether we can tweak Test Isolation to ignore skipped tests (there may be some edge cases that make that impractical), but in the meantime I can suggest two workarounds:

1. Disable Test Isolation (I do not recommend this)
In your `cypress.config.*` file, add a `testIsolation: false` entry under your [`e2e` config](https://docs.cypress.io/guides/references/configuration#e2e). This can allow tests to leak state so it is recommended to leave it enabled, but this should disable the "clear the page" behavior
2. Update your Cucumber config to provide the [`omitFiltered` flag](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#omit-filtered-tests) (this is probably a better option)
Add the following to your `package.json` so that Cucumber doesn't send skipped tests to the Cypress test runner
```
"cypress-cucumber-preprocessor": {
    "filterSpecs": true,
    "omitFiltered": true
  }
```

**Comment by lmiller1990** [comment] 2022-12-22 00:31
What version of the Cypress cucumber plugin are you using?

If you can create a minimal reproduction, that would help a lot - without code and versions, it's difficult to do much other than guess what the problem might be.

**Comment by mohanbabu-zumen** [comment] 2022-12-22 05:21
> What version of the Cypress cucumber plugin are you using?
> 
> If you can create a minimal reproduction, that would help a lot - without code and versions, it's difficult to do much other than guess what the problem might be.

Below are the cucumber and other devDependencies that we are using

```
"@shelex/cypress-allure-plugin": "^2.34.0",
    "cucumber-html-reporter": "^5.2.0",
    "cypress": "^11.2.0",
    "cypress-browser-permissions": "^1.0.5",
    "cypress-cucumber-preprocessor": "^4.0.0",
    "cypress-dark": "^1.7.14",
    "cypress-file-upload": "^5.0.8",
    "cypress-mailosaur": "^2.0.1",
    "cypress-multi-reporters": "^1.6.2",
    "cypress-nhover": "^1.0.1",
    "cypress-recurse": "^1.24.0",
    "cypress-wait-until": "^1.7.1",
    "cypress-xpath": "^2.0.1",
    "gmail-tester": "^1.3.8",
    "mocha": "^10.2.0",
    "mocha-junit-reporter": "^2.0.0",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.2",
    "mochawesome-report-generator": "^6.2.0",
    "multiple-cucumber-html-reporter": "^3.0.1",
    "npm-run-all": "^4.1.5",
    "parallelshell": "^3.0.1"
```

Please let me know If you need any other details or code from my end!

**Comment by lmiller1990** [comment] 2022-12-22 23:44
It looks like `cypress-cucumber-preprocessor@4` has not has a release in years: https://github.com/TheBrainFamily/cypress-cucumber-example

This looks like the most up to date one that works with Cypress 10+ https://github.com/badeball/cypress-cucumber-preprocessor. The README references the other repo 

> information_source The repositor has recently moved from github.com/TheBrainFamily to github.com/badeball. Read more about the transfer of ownership https://github.com/badeball/cypress-cucumber-preprocessor/issues/689.

I think you need to update to that version. They have an [upgrade guide here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

**Comment by mohanbabu-zumen** [comment] 2022-12-23 04:58
> It looks like `cypress-cucumber-preprocessor@4` has not has a release in years: https://github.com/TheBrainFamily/cypress-cucumber-example
> 
> This looks like the most up to date one that works with Cypress 10+ https://github.com/badeball/cypress-cucumber-preprocessor. The README references the other repo
> 
> > information_source The repositor has recently moved from github.com/TheBrainFamily to github.com/badeball. Read more about the transfer of ownership [badeball/cypress-cucumber-preprocessor#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).
> 
> I think you need to update to that version. They have an [upgrade guide here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

That makes sense @lmiller1990. Very much thanks for the detailed explanation! We will try the same and let you know ASAP

**Comment by lmiller1990** [comment] 2022-12-29 00:18
I think this is likely an issue regarding dependencies. Let me know if you need more assistance. I don't think we need to fix anything in this repo, so I'm going to close this. Happy to reopen if it turns out we've got a bug in Cypress we need to address.

**Closed as completed by lmiller1990** 2022-12-29 00:18 UTC
