### ISSUE TITLE
Request object of cy.intercept() is ArrayBuffer.

### ISSUE THREAD

**Issue by baeharam** [cypress-io/cypress#16917] opened 2021-06-14 04:52 UTC
### Current behavior

I'm using graphql and intercepting all the requests through `cy.intercept('/graphql')` to use below function which is waiting for network idle.

```ts
// reference: https://glebbahmutov.com/blog/cypress-tips-and-tricks/#wait-for-network-idle
const waitRequestsAfterCallback = (
  cyFunc: () => void,
  timeout = 1000,
): void => {
  const getCurrentTime = (): number => new Date().getTime();
  let lastNetworkTime: number | undefined = undefined;

  cy.intercept('/graphql', (req) => {
    console.dir(req);
    lastNetworkTime = getCurrentTime();
  });

  cyFunc();

  const started = getCurrentTime();
  cy.wrap(`wait graphql request during ${timeout/1000} second`).should(() => {
    const requestedTime = lastNetworkTime ?? started;
    const elapsed = getCurrentTime() - requestedTime;
    if (elapsed < timeout) {
      throw new Error('Network is busy');
    }
  });
};
```

There were no problems at all, but suddenly a specific request causes error.

![스크린샷 2021-06-14 오후 1 51 31](https://user-images.githubusercontent.com/35518072/121840646-a7e9ee80-cd17-11eb-9880-68787f3411e3.png)

This error is caused from request object which is ArrayBuffer. But, why? my request object was very normal at network tab in chrome. Also, other requests were succeeded.

↓ My current request object...which causes error

![스크린샷 2021-06-14 오후 1 44 48](https://user-images.githubusercontent.com/35518072/121840194-b84d9980-cd16-11eb-88e6-aa112590ae7f.png)

But, it works well under two conditions.

(1) Request object has `input` variable which contains several fields and `reason` field is nullable. So, I can skip that field but it causes error... however, it works well when I didn't skip that field....why??

```
input: {
  field1: some value,
  field2: some value,
  ...
  reason: null // nullable
}
```

(2) If I remove `cy.intercept`, it works well... why??

\+ Strange thing is that request works well in application not cypress.

### Desired behavior

Request is succeeded even if I use `cy.intercept`.

### Test code to reproduce

It could be server problem and dependent on specific request, so I cannot make reproduce. How do you think, does it could be `cy.intercept` problem?

### Versions

Cypress: 7.3.0

**Comment by jennifer-shehane** [comment] 2021-06-14 16:37
@baeharam Could you try updating to the latest version of Cypress and let us know if this is still happening for you.

If possible, could you provide a way to reproduce this if that doesn't resolve the issue? Thanks.

**Comment by jk4235** [comment] 2021-06-16 03:21
maybe same issue https://github.com/cypress-io/cypress/issues/16292

**Comment by flotwig** [comment] 2021-06-21 15:26
Looks like a duplicate of #16292 - closing, if this recurs after 7.6.0 please reopen.

**Closed by flotwig** 2021-06-21 15:26 UTC
Labels: stage: needs information
