### ISSUE TITLE
With `"grepFilterSpecs": true`, video output paths are not deterministic 

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#28976] opened 2024-02-20 17:29 UTC
### Current behavior

When I run `npx cypress run` and all those tests selected
<img width="1006" alt="image" src="https://github.com/cypress-io/cypress/assets/36670132/df8a5fe3-a872-433e-b603-7b0fa3d3efe1">
This is the video output path for `todo.cy.js`
`xxxxxxxxxxx/cypress/videos/1-getting-started/todo.cy.js.mp4`

When I run `npx cypress run --env grep="example to-do app"` and only one test is selected
<img width="1006" alt="image" src="https://github.com/cypress-io/cypress/assets/36670132/b9663f69-9220-483e-b81a-7a4a34b1f71b">

The video output path is `xxxxxxxxx/cypress/videos/todo.cy.js.mp4` (Note: `1-getting-started` is not included)

If I run `npx cypress run --env grep="an"` and multiple tests are selected
`xxxxxxxxxxx/cypress/videos/1-getting-started/todo.cy.js.mp4` is in use again

### Desired behavior

`xxxxxxxxxxx/cypress/videos/1-getting-started/todo.cy.js.mp4` should be used regardless of test suite

### Test code to reproduce

Using default cypress starter project `1-getting-started` and `2-advanced-examples`

Config file 
```javascript
module.exports = defineConfig({
  video: true,
   env: {
    "grepFilterSpecs": true
  },
  e2e: {
    setupNodeEvents(on, config) {
      require('@cypress/grep/src/plugin')(config);
      return config;
    },
  },
});

```

with  support file 
```javascript
const registerCypressGrep = require('@cypress/grep')
registerCypressGrep()
```

### Cypress Version

13.6.4

### Node version

20.11.0 

### Operating System

14.2.1 Mac

### Debug Logs

```shell
N/A
```

### Other

Please do not tell me to filter and lookup video paths using glob pattern, that is not the point.

**Comment by jennifer-shehane** [comment] 2024-02-20 17:50
Duplicate of https://github.com/cypress-io/cypress/issues/24052

**Closed as not planned by jennifer-shehane** 2024-02-20 17:50 UTC
Labels: type: duplicate
