### ISSUE TITLE
Chrome 91 causes redirection error

### ISSUE THREAD

**Issue by Jacek-fstack** [cypress-io/cypress#16769] opened 2021-06-02 09:26 UTC
Just like in the title: 
Chrome 91 throws "xxxxx redirected you too many times." error when app does a standard 2-3 redirects, while chrome 90 and electron do not.
I changed redirection limit to 30, no change.
I don't have a reliable way to reproduce it for you - I can't give you access to my repo/project, but maybe somone has an example and the same issue.
<img width="1194" alt="Screen Shot 2021-06-02 at 10 22 40 AM" src="https://user-images.githubusercontent.com/29603168/120459310-5dbc5100-c398-11eb-9d6f-a5446475e793.png">

**Comment by jennifer-shehane** [comment] 2021-06-02 15:39
Duplicate of https://github.com/cypress-io/cypress/issues/4220

**Closed by jennifer-shehane** 2021-06-02 15:39 UTC

**Comment by Jacek-fstack** [comment] 2021-06-03 10:58
But this is not the same error... It is working on chrome 90.

**Comment by jennifer-shehane** [comment] 2021-06-08 19:30
The application under test in the screenshot you posted is indicating it went to chrome-error://chromewebdata/ which is what the other issue is concerning. 

If you can provide a way to reproduce, where it passes in Chrome 90 and not in Chrome 91, we can reopen it as a new issue outside of the previous one.

**Comment by davetran5** [comment] 2021-06-09 16:00
I'm also receiving this issue after updating to Chrome 91. I get the redirect loop after logging through an Auth0 login page and having it redirect to my app.

**Comment by matthewbordas** [comment] 2021-09-08 19:24
@davetran5 same here

**Comment by karlhorky** [comment] 2021-09-08 19:45
I'm also experiencing this with Auth0 and the latest version of Chrome (93).

**Comment by muneebrana23** [comment] 2022-02-15 11:59
I'm using this code to handle new tab and getting this error. It's displaying chrome-error //chromewebdata/ in url.
*Also Saying Redirects too many times*

cy.get(".store-list-item__action").contains("a","Log in").eq(0).invoke("removeAttr", 'target').then(newUrl=>{
        cy.wrap(newUrl).click()
    })

Tried for few other example site and it's working fine. I think mine url is redirecting two times that why facing this issue "redirected too many time". How I can handle it?

**Comment by azhukovskygit** [comment] 2022-12-19 20:33
Have same issue with test case where after successful login I just want to logout user and I am unable to do it because of too many redirects.

**Comment by azhukovskygit** [comment] 2022-12-19 21:08
SOLVED! I was able to solve issue with too many redirects by using cy.visit() command where I supply logout URL to end user session, so I can run second test where I test negative login scenario.
describe('Login using username and password', () => {
    it('POSITIVE: Should be able to authenticate with valid credentials', () => {
        //Navigate to Log in to ZeroBank URL
        cy.visit('https://automationteststore.com/index.php?rt=account/login')

        //Verify Account Login page URL
        cy.url().should('include', 'account/login')

        //Verify Account Login page is displaying
        cy.get('h1.heading1 span.maintext:first-of-type').contains('Account Login')

        //Enter login name
        cy.get('input#loginFrm_loginname').clear()
        cy.get('input#loginFrm_loginname').type('jsmith123', { delay: 50 })

        //Enter password
        cy.get('input#loginFrm_password').clear()
        cy.get('input#loginFrm_password').type('Password123!', { delay: 50 })

        //Click on Login button
        cy.get('button[title="Login"]').click()

        //Verify My Account page URL
        cy.url().should('include', 'account/account')

        //Verify that My Account page is displaying
        cy.get('h1.heading1 span.maintext:first-of-type').contains('My Account')

        //Logoff user (Note: navigating to logout page due to redirect error)
        cy.visit('https://automationteststore.com/index.php?rt=account/logout')
    });
    

    it('NEGATIVE: Should not be able to authenticate with invalid credentials', () => {
        //Navigate to account login URL
        cy.visit('https://automationteststore.com/index.php?rt=account/login')

        //Verify Account Login page URL
        cy.url().should('include', 'account/login')

        //Verify Account Login page is displaying
        cy.get('h1.heading1 span.maintext:first-of-type').contains('Account Login')

        //Enter valid login name
        cy.get('input#loginFrm_loginname').clear()
        cy.get('input#loginFrm_loginname').type('jsmith123', { delay: 50 })

        //Enter invalid password
        cy.get('input#loginFrm_password').clear()
        cy.get('input#loginFrm_password').type('password', { delay: 50 })

        //Click on Login button
        cy.get('button[title="Login"]').click()

        //Verify that error message is displaying
        cy.get('div[class="alert alert-error alert-danger"]').should('contain.text', 'Error: Incorrect login or password provided.')
    });
});
