### ISSUE TITLE
Unable to open "Runs" tab in the Desktop GUI

### ISSUE THREAD

**Issue by krishvv** [cypress-io/cypress#3655] opened 2019-03-06 11:11 UTC
Hi,

I am trying to open the "Runs" for viewing the Dashboard from the TestRunner . I am unable to do the same . 

```
Cannot connect to API server
Viewing runs requires connecting to an external API server.
We tried but failed to connect to the API server at https://api.cypress.io/
 Try again
The following error was encountered:
connect ETIMEDOUT 104.25.215.23:443
```

**Comment by jennifer-shehane** [comment] 2019-03-06 16:00
Hey @krishvv, this can happen due to general connectivity issues. 

If you are behind a corporate proxy, you may also want to try the workarounds [suggested here](https://github.com/cypress-io/cypress/issues/1469)

**Comment by krishvv** [comment] 2019-03-07 11:09
Hello @jennifer-shehane .
I have tried the workarounds but still not able to open the "Runs" tab :(

**Comment by jennifer-shehane** [comment] 2019-03-08 09:12
@krishvv Are you behind a corporate proxy?

**Comment by krishvv** [comment] 2019-03-10 13:28
@jennifer. Yes . I have followed the workarounds and they dont seem to work.
Is there anything else that i need to look at? 
Thanks

**Comment by jennifer-shehane** [comment] 2019-03-14 04:35
Look at this issue. It is a duplicate of this, we are currently working on Proxy fixes, but until then, this may not work for now. https://github.com/cypress-io/cypress/issues/1470

**Closed by jennifer-shehane** 2019-03-14 04:35 UTC
Labels: stage: awaiting response

**Comment by krishvv** [comment] 2019-03-15 04:03
Hi Jennifer . Thanks . I am trying to locate server/lib/events file and unable to find it.
I have installed cypress using the command npm install cypress --save-dev
