### ISSUE TITLE
Cannot open any browser on Mac

### ISSUE THREAD

**Issue by sunpietro** [cypress-io/cypress#22866] opened 2022-07-20 09:47 UTC
### Current behavior

I've just set up a fresh Cypress project in a new NPM project.

### package.json content
```json
{
  "type": "module",
  "name": "project-e2e",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "test": "cypress open"
  },
  "devDependencies": {
    "cypress": "^10.3.1",
    "typescript": "^4.7.4"
  }
}
```

### cypress.config.js content
```
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

### Steps to reproduce
1. Run `yarn test`
2. It opens the Cypress app
3. Start basic configuration through the wizard
![Screen Shot 2022-07-20 at 11 43 35](https://user-images.githubusercontent.com/1736658/179951781-9a15d7b7-240e-4ab5-81de-00fffd89df6b.jpg)
4. On browsers screen pick any browser:
5. Try to run tests in the browser.

### Actual result
![Screen Shot 2022-07-20 at 11 45 00](https://user-images.githubusercontent.com/1736658/179952125-9d476489-a85b-4a7e-a530-80b05a4c917a.jpg)

This happens with any browser.

### Desired behavior

It should open the browser and run tests.

### Test code to reproduce

Run `yarn test` in the CLI.

### Cypress Version

10.3.1

### Other

Node: v16.13.1
OS: MacOS Monterrey 12.4

**Comment by tbiethman** [comment] 2022-07-20 20:21
@sunpietro thank you for the report. We have similar environments, but I'm unable to reproduce this. Do you by chance have MDM/admin software that could be preventing the browser app execution? Another thing to try would be to run with the DEBUG env enabled to see if there are any other browser errors being thrown:

`DEBUG=cypress:* cypress open`

**Comment by sunpietro** [comment] 2022-07-21 18:38
I can see something like this:
```
cypress:network:connect received error on connect, retrying { iteration: 5, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51715     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51715 } } +102ms
```
When the crash occurs.

**Comment by sunpietro** [comment] 2022-07-22 07:02
In addition to that. I switched back to Cypress 10.2.0 and there everything is working. The browser is running and I can do the testing.

**Comment by tbiethman** [comment] 2022-07-22 15:14
@sunpietro is it possible to post a full log, from start to crash? Feel free to redact paths/strings you're unable to share. Also, if you select 'Report...' from the browser crash dialog, do you get a stack trace? It might be helpful to see that, too.

Also, thank you for confirming that you're not seeing the issue on 10.2.0 and are seeing the issue in 10.3.1. Do you see the problem in 10.3.0? Confirming this would help use narrow down the affecting change set.

**Comment by tbiethman** [comment] 2022-08-01 19:36
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by tbiethman** 2022-08-01 19:36 UTC
Labels: stage: awaiting response

**Comment by sunpietro** [comment] 2022-08-01 20:19
From my end all I can say that moving to previous version, then upgrading to the latest version resolved that issue. It looks like if someone used the 9.x version and have never installed 10.3.x version then the issue might occur. After downgrading it to 10.2.x and upgrading it back to 10.3.x the issue is gone.
