### ISSUE TITLE
Not able to run the tests on Cypress Cloud viaGithub actions

### ISSUE THREAD

**Issue by janavi-p** [cypress-io/cypress#29722] opened 2024-06-21 11:00 UTC
### Current behavior

I am currently able to run the tests manually via cypress cloud. But if I trigger via github actions it does not. I tried reaching out to [support@cypress.io](mailto:support@cypress.io), but did not get prompt help.
![image](https://github.com/cypress-io/cypress/assets/132589418/fc9ecf0a-ca64-4d15-81a1-95ab61aafcfc)
![image](https://github.com/cypress-io/cypress/assets/132589418/c35dd5c7-1003-4994-b2c5-0b342b1bfe25)

### Desired behavior

Whenever the PR push happens to staging my repo should be triggered via Github actions in the Cypress cloud. 
Even scheduled cron job do not run via cypress cloud

### Test code to reproduce

Whenever the PR push happens to staging my repo should be triggered via Github actions in the Cypress cloud. 
Even scheduled cron job do not run via cypress cloud
In addition to this, in my local runs I cannot use chrome browser. 
![image](https://github.com/cypress-io/cypress/assets/132589418/a4dff486-afc6-4f8f-a81b-05ee04141244)

### Cypress Version

13.12.0

### Node version

9.5.1

### Operating System

macOS 14.5

**Comment by jennifer-shehane** [comment] 2024-06-21 14:29
I would recommend updating to the latest Cypress version, we may have resolved the Chrome opening issue since then. 

What is the output you're seeing when running Cypress? It's not clear to me the exact error you're encountering.

**Comment by MikeMcC399** [comment] 2024-06-21 15:06
@janavi-p 

You write that you are using Node.js version `9.5.1`. Perhaps that was a typo? Check with

```
node --version
```
and make sure that you are using a minimum version of `18.x` and preferably the `20.x` LTS version.

Please post also your GitHub Actions workflow.

**Comment by janavi-p** [comment] 2024-07-08 13:44
v20.13.1. this is the node version. 
![image](https://github.com/cypress-io/cypress/assets/132589418/9f55fa89-37be-45c1-87ab-9792557369c3)
GitHub Actions ( Cypress Runs) || Getting "Run finished" immediately when "Run Starts" @MikeMcC399 

Workflow:
jobs:
cypress-run:
name: 'Cypress Test on Ubuntu'
runs-on: ubuntu-latest
timeout-minutes: 25
strategy:
fail-fast: false # https://github.com/cypress-io/github-action/issues/48
matrix:
containers: [1] # Uses 1 parallel instance

steps:
  - name: 'Checkout the repository'
    uses: actions/checkout@v4
    with:
      ref: main
      
  - name: 'git branch info'
    run: | 
      git branch

  - name: 'Building web application to be tested'
    run: yarn
    
  - name: Cypress run
    uses: cypress-io/github-action@v6
    with:
      browser: electron
      config-file: cypress.config.js
      spec: "cypress/e2e/specs/regression-specs/staging/**/*.cy.js"
      group: 'UI-Electron'
      record: true
      parallel: true
    
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

**Comment by MikeMcC399** [comment] 2024-07-08 14:15
@janavi-p 

You may be able to get more information about why your workflow is failing if you enable debugging

```yml
  env:
    DEBUG: '@cypress/github-action'
```

You do not need the line
```yml
run: yarn
```
if your repo has a `yarn.lock` in it. `cypress-io/github-action` takes care of installing dependencies.

Please edit the posting of your workflow and use backticks, otherwise your code is displayed as `markdown` instead of as `yaml`, for example:

````
```yml
name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
and so on
```
````

This issue could also be transferred to https://github.com/cypress-io/github-action, although at this time there has not been any root cause identified.

**Comment by MikeMcC399** [comment] 2024-07-08 15:34
The workflow is missing

```yml
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by janavi-p** [comment] 2024-07-09 09:08
@MikeMcC399 Added the Debug line suggested by you. After which the specs are running. 
In addition, I see Bad credential error whenever I add the following code. With this code, even manual triggers fail with bad credential error.  I have set the right token. 
 env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
Attaching the logs for your reference. Please guide. 
[5_Cypress run.txt](https://github.com/user-attachments/files/16140969/5_Cypress.run.txt)

**Comment by MikeMcC399** [comment] 2024-07-09 09:36
@janavi-p 

You write that you have added

```yml
env:
GITHUB_TOKEN: ${{ secrets.TOKEN }}
```

This is not the same as:

```yml
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See
- [Automatic token authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) for an explanation of the `GITHUB_TOKEN` secret
- Cypress GitHub Action documentation [Record test results on Cypress Cloud](https://github.com/cypress-io/github-action/blob/master/README.md#record-test-results-on-cypress-cloud)

I suggest again for you to follow the documentation to avoid your errors.

**Comment by janavi-p** [comment] 2024-07-09 13:09
As per your suggestion, I made the necessary changes. @MikeMcC399 

Any particular reason why the run time has increased ( 25 mins to run 2 specs ) which leads to cancellation of operation ( triggered via scheduled job and via ci/cd)
![image](https://github.com/cypress-io/cypress/assets/132589418/28e79179-53ee-4fa6-aee5-3c53195f486a)

However, it runs 18 specs in 25 mins via triggered manually.

**Comment by jennifer-shehane** [comment] 2024-07-09 18:54
@janavi-p If you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here, that might reveal where the test is sitting for so long.

**Comment by MikeMcC399** [comment] 2024-08-09 16:45
This issue is stale since there has been no reply for one month.

**Closed as completed** 2024-08-12 14:58 UTC
Labels: stage: awaiting response
