### ISSUE TITLE
cypress run gives error with node v12.11.0

### ISSUE THREAD

**Issue by idxrx** [cypress-io/cypress#5292] opened 2019-10-04 14:07 UTC
Issue

### Current behavior:
Cypress version 3.4.1
Node version v12.11.0 and also v12.11.1

npm run cypress:run with nodejs version 12.11.0 gives error below after all specs passed and with node version 12.10.0 or lower there is no error. 
(easy fix is uninstalling node and install v12.10.0)

The error is:

   All specs passed!                           00:06        8        8        -        -        -

C:\..\node_modules\cypress\lib\exec\spawn.js:175
          throw err;
          ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:409:25)
    at callFinal (_stream_writable.js:627:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'shutdown'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ..Roaming\npm-cache\_logs\2019-10-04T13_27_29_516Z-debug.log
Error: Command failed with exit code 2 (ENOENT): npm run cypress:run
spawn npm run cypress:run ENOENT
    at notFoundError (..\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (..\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (..\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  errno: 'ENOENT',
  syscall: 'spawn npm run cypress:run',
  path: 'npm run cypress:run',
  spawnargs: [],
  command: 'npm run cypress:run',
  exitCode: 2,
  exitCodeName: 'ENOENT',
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ..\Roaming\npm-cache\_logs\2019-10-04T13_27_29_776Z-debug.log

### Desired behavior:

Cypress v3.4.1 with
npm run cypress:run should also run with node v12.11.0 or higher.

### Steps to reproduce: (app code and test code)
Install nodejs v12.11.0 and run a test with cypress run.

### Versions
Cypress 3.4.1 Chrome v76 Windows server 2019 Node v12.11.0 or v12.11.1

**Comment by flotwig** [comment] 2019-10-04 14:21
Duplicate of #5241, closing.

**Closed by flotwig** 2019-10-04 14:21 UTC
