### ISSUE TITLE
Can't pass more than 1 env variable to the command line. Reads several variables as one. Yarn Only. Npm works as expected.

### ISSUE THREAD

**Issue by valeria-chernikova** [cypress-io/cypress#26777] opened 2023-05-17 15:12 UTC
### Current behavior

STR: 
1. Open cypress using yarn and pass several env variables
`yarn run cypress open --env a=1,b=2`
2. Navigate to the Project settings in the runner 
3. You should see the following in the env object: 
![image](https://github.com/cypress-io/cypress/assets/81378319/02416bbc-d9a0-403c-a800-f39fbe062cd4)

### Desired behavior

Same as when working with npm. 
1. Open cypress using yarn and pass several env variables
`yarn run cypress open --env a=1,b=2`
2. Navigate to the Project settings in the runner 
3. You should see the following in the env object: 
![image](https://github.com/cypress-io/cypress/assets/81378319/4a0a4b95-e275-47a7-90d4-cccbf54f169a)

### Test code to reproduce

Can't fork the repo, it's private, But we saw this issue consistently on multiple machines and 2 different projects (cypress versions 12.7.0 and 12.12.0). 

### Cypress Version

12.7.0

### Node version

16.20.0

### Operating System

Windows 10 Pro Version 22H2

**Comment by chrisbreiding** [comment] 2023-05-18 14:13
I wasn't able to reproduce this with yarn 1. 

- Which version of yarn are you using? 
- Is it still an issue if you put quotes around the env values (` yarn run cypress open --env "a=1,b=2"`)

**Comment by valeria-chernikova** [comment] 2023-05-18 15:31
1. I figured that it happens only if you're using yarn with pwsh (yarn version doesn't matter, I'm on 1.22.19, but I tried 1.19.0, 1.10.0, 1.0.0, and it's the same) 
npx + pwsh, npx + cmd, yarn + cmd work as expected 
my PSVersion is 5.1.19041.2364

2. Yes, we're working around this issue using quotes, it's working.

**Comment by chrisbreiding** [comment] 2023-05-18 15:50
Thanks for the information! 

I was able to reproduce it in Powershell. Looks like when running `yarn run cypress open --env a=1,b=2`, it replaces the comma with a space, changing it to `yarn run cypress open --env a=1 b=2` and that's how Cypress receives it. I'm not sure there's anything we can do about that within Cypress, since we expect values to be comma-separated. 

I'd say putting quotes around the value is the solution, so I'm going to close this issue. 

I [opened an issue](https://github.com/cypress-io/cypress-documentation/issues/5256) in the docs repo to recommend using quotes around the value .

**Closed as completed by chrisbreiding** 2023-05-18 15:50 UTC
