### ISSUE TITLE
Chance of race condition when using screenshot()

### ISSUE THREAD

**Issue by renelux** [cypress-io/cypress#3276] opened 2019-02-01 07:26 UTC
### Current behavior:

When using `screenshot` command, when taking a screenshot the frame running the app get resized, this can trigger some re-render on the page. This can cause a race condition, if between the time that the element position is retrieved and the actual screenshot is taken the element is being moved.

The result is that certain part of the element we are trying to capture are actually missing, this is especially troublesome when you consider we use plugins like `cypress-plugins-snapshots` for image diffing.

### Desired behavior:

If the position moves between getting the position and taking the screenshot we should retry to ensure the element is properly captured. 

### Steps to reproduce: (app code and test code)
```js
describe('Flaky Screenshot', () => {
    it('Flaky Example', () => {
        cy.get('.container').then($container => {
            const container = $container[0];
            let i = 0;
            setInterval(() => {
                container.style.marginTop = `${i}px`;
                i += 10;
            }, 0.5);
        });

        cy.get('.container').screenshot();
    });
});
```
When executing this code (hacky) the screenshot almost always is missing a part of the element we are trying to capture.

### Versions

Cypress: 3.1.5
Chrome: 72

### Screenshots (consecutive runs on the same machine)
![flaky screenshot -- flaky example 4](https://user-images.githubusercontent.com/1439270/52108660-a8492980-2635-11e9-9417-e1a57ff872da.png)
![flaky screenshot -- flaky example 5](https://user-images.githubusercontent.com/1439270/52108661-a8e1c000-2635-11e9-931e-f3cea303cdb1.png)
![flaky screenshot -- flaky example 6](https://user-images.githubusercontent.com/1439270/52108662-a8e1c000-2635-11e9-9b82-2df540a8c52e.png)
![flaky screenshot -- flaky example 7](https://user-images.githubusercontent.com/1439270/52108664-a97a5680-2635-11e9-8d4f-694d79337c32.png)

**Comment by renelux** [comment] 2019-02-18 07:46
@jennifer-shehane I would like to see if I can resolve this issue myself.

From your perspective would it be ok if we verify the element coordinates after the screenshot is taken and retake if they changed? If it fails a second time then we throw an error explaining what happens to the user?

**Comment by chrisbreiding** [comment] 2019-03-14 15:05
Cypress tries to make efforts to prevent race conditions, but it can only really know about and control its own DOM (the reporter and app iframe). The app-under-test changing during a screenshot is nearly impossible to account for. Therefore, it's best to leave it up to the test code itself to get the app-under-test into a known, predictable state before a screenshot.

In the example above, there's an element of randomness introduced by `setInterval` since, due to how browser timers work, the number of times it will run before the screenshot is taken is not determinate. The best way to solve for that example would be to disable timers before the screenshot via `cy.clock`.

Now I know that's just an example for reproduction's sake and not what's likely happening in a real app that may re-render if the window size changes. But the same concept applies. There may be actions you can take ahead of the screenshot to ensure that the app doesn't change as a result of the app iframe resizing. 

Another solution, which _would_ require some work in Cypress, would be to allow you to run Cypress commands from the `onBeforeScreenshot` so that you can run guard assertions to ensure your app is in a known state after the iframe is resized but before the screenshot is taken.

**Comment by renelux** [comment] 2019-03-14 15:41
I agree that the above example is actually incorrect and a poor attempt of making this reproducible. After we attempted the fix we actually realized that the result and our investigation was incorrect.

When we are running our test suite (which heavily relies on image-diffing) on the CI, we can actually see that the runner sometimes is still visible, even though it should be made hidden by Cypress. So to us that makes it seem that there is a race-condition happening here where the screenshot taking can be more performant then the iframe being resized to full screen. So what we are attempting to achieve is that we are properly awaiting the iframe to be resized and awaiting the hiding of the scrollbars.

**Comment by renelux** [comment] 2019-03-20 01:03
The below screenshots show the issue we are seeing, at the moment we are unable to find the root cause, we will track the failures and see if there is a certain pattern so we can try to make it easier reproducible.

![race-condition-current](https://user-images.githubusercontent.com/1439270/54651693-ef5c8280-4aee-11e9-9ebb-3db98288596c.png)
![race-condition-original](https://user-images.githubusercontent.com/1439270/54651695-f08daf80-4aee-11e9-8fe1-4a2932198c44.png)
![race-condition-fullscreen](https://user-images.githubusercontent.com/1439270/54651694-eff51900-4aee-11e9-919f-4dbe06058c75.png)

**Comment by jennifer-shehane** [comment] 2020-07-14 06:06
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-07-14 06:06 UTC
Labels: topic: screenshots 📸, type: bug
