### ISSUE TITLE
The Cypress App could not be downloaded (Can't install via NPM I on WINDOWS 2012)

### ISSUE THREAD

**Issue by tyomasson** [cypress-io/cypress#6315] opened 2020-02-04 14:24 UTC
### Current behavior:

Can't install any Cypress version.

I do not use a proxy, I can also download the required version via the browser and console.
___
STR:
When I make:

```
npm install cypress --save-dev
```

I get:

```
URL: https://download.cypress.io/desktop/3.7.0?platform=win32&arch=x64
Error: read ECONNRESET
```

### Desired behavior:
The installation of the module should be successful.

### Test code to reproduce
Log:

```
> cypress@3.7.0 postinstall C:\projects\xxx\develop\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 3.7.0)

[09:45:47]  Downloading Cypress     [started]
[09:45:48]  Downloading Cypress     [failed]
[09:45:48] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, y               ou must configure the HTTP_PROXY environment variable before downloading Cypres               s. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.7.0?platform=win32&arch=x64
Error: read ECONNRESET

----------

Platform: win32 (6.3.9600)
Cypress Version: 3.7.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, y               ou must configure the HTTP_PROXY environment variable before downloading Cypres               s. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.7.0?platform=win32&arch=x64
Error: read ECONNRESET

----------

Platform: win32 (6.3.9600)
Cypress Version: 3.7.0
npm WARN rollback Rolling back node-pre-gyp@0.14.0 failed (this is probably har               mless): EPERM: operation not permitted, scandir 'C:\projects\xxx\develop\nod               e_modules\fsevents\node_modules'
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint@^4.19.1 || ^5.3.               0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.1.2 requires a peer of eslint@>=1.6.0 <6.0.0 but none                is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 ||                ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\f               sevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents               @1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x6               4"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.7.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional lo               gging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-02-04T               07_45_59_543Z-debug.log
```

### Versions

Cypress 3.7.0

Operating System: Windows Server 2012 R2 Standard 64-bit (6.3, Build 9600) (9600.winblue_ltsb_escrow.191014-1700)

**Comment by jennifer-shehane** [comment] 2020-02-04 14:51
Does your workplace require a proxy to be used to access the Internet? Or are you behind a firewall that may prohibit your network? Please follow the guidelines in [Proxy Configuration](https://on.cypress.io/proxy-configuration#Set-a-proxy-on-Linux-or-macOS) if so. 

Also I see an `EPERM: operation not permitted` error in here. Make sure you have the proper permissions where you are installing Cypress.

**Comment by tyomasson** [comment] 2020-02-04 15:03
My workplace doesn't require proxy and I can download cypress.zip via console.
I'm turned off firewall now and I have no result.

I know about warning EPERM it's not related to cypress, this is regular behaviour for rudiment dependencies.

**Comment by maacaro** [comment] 2020-02-20 13:22
I got the same error on the azure pipeline with but with yarn:
log:
```
yarn install v1.21.1
warning package.json: No license field
warning compriquote@1.0.0: No license field
[1/4] Resolving packages...
warning " > @storybook/react@5.3.13" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @babel/preset-flow@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core@5.3.13" has unmet peer dependency "@babel/core@*".
warning "@storybook/react > @storybook/core@5.3.13" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
[4/4] Building fresh packages...
error /home/vsts/work/1/s/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /home/vsts/work/1/s/node_modules/cypress
Output:
Installing Cypress (version: 3.7.0)

25l[12:56:22]  Downloading Cypress     [started]
[12:56:25]  Downloading Cypress     [failed]
25hThe Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.7.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 426bc17a99e0d7fb9e254f055b7f4c81ba6f1315731248706e2c4748bd10346670d09186cfc76ce452b7f287c8c92789b30a25788d11a1bfa9313b3b944be6bf
Computed checksum: 91f12188e5c6074928f8fa659668d5e1bbd13ab353d0a6b8405310836694f02b08c8431119e45a59d2f4ff814fe243d74a5d256b6f009fa7f12b4ac1412fa640

Expected downloaded file to have size: 161801618
Computed size: 161801618

----------

Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 3.7.0
25h
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```


I remove from my package.json `@testing-library/cypress`.
I refactored my tests.
I delete the node_modules folder `rm -rf node_modules`
I run `yarn install`
**and It works!!!**

**Comment by kylemh** [comment] 2020-03-23 06:32
Getting the same thing for Zeit, Netlify, and CircleCI: https://github.com/OperationCode/front-end/pull/1076

Can install locally no problem.

**Comment by kylemh** [comment] 2020-05-21 18:24
Getting this again today. It seems like binaries get corrupted on some sort of random, self-resolving basis.

**Comment by denahardian** [comment] 2020-05-21 22:42
same issue, i can't downloading via npm or yarn stuck on 6% and im tried download for spesific version still same hmm, then im trying download another depedency working fine. and my network is good hmm.

![image](https://user-images.githubusercontent.com/32255042/82613166-d8cc2280-9bee-11ea-8e74-eae3f9e850d1.png)

**Comment by AskMarvinV** [comment] 2020-05-24 23:10
Got same issue when downloading the v4.6.

**Comment by lgandecki** [comment] 2020-05-26 14:23
not windows, but 
Happening to me now with 4.6.0 and 4.4.1 on github actions :(
https://github.com/xolvio/webpack-federation-storybook-design-systems-demo/runs/709635556?check_suite_focus=true
https://github.com/xolvio/webpack-federation-storybook-design-systems-demo/runs/709620205?check_suite_focus=true
```
URL: https://download.cypress.io/desktop/4.6.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: f7c7fcf0cd721a077d40ded1bff3d0e237eff9062ba755b532e2b856fad335d1384331cebf0d0f7926721c86682ffaff064edf8281b81257338881f36a991e88
Computed checksum: bcdd289d4f120420223a8d7f69f5ab88d925516fc560894dea3a876980e363367b5473d9cc1775814655f754e4514f10b112fbae5a0472681306cb5467ae9e5a

Expected downloaded file to have size: 172463186
Computed size: 172463186
```

```

URL: https://download.cypress.io/desktop/4.4.1?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 96726a09c3023254f0fa0b37458187a8792cbb03567100f029c2edde6bb51d6ca307cb658fecedbecb9ab376dc7fb294394c13ff655b0ed6b9f489a71192cde0
Computed checksum: c3a5a37e1b3020c612badb9f38be1facc8c0d5074f172a6669135f5dc5d60a1d1a8029f12b3dbae1ecdc2877b6c9a09b3a92ff8b0e87a57fcc96b326772086ea

Expected downloaded file to have size: 171207794
Computed size: 171702596

----------

Platform: linux (Debian - 9.11)
Cypress Version: 4.4.1
```

**Comment by ZwapKillrath** [comment] 2020-05-29 14:19
v.4.6.0 also gives me the headache regarding the same error
Tried deleting node_modules, clear cache etc.
still the same

**Comment by hmmaros** [comment] 2020-06-02 06:28
Im getting the same error for 4.7.0 version even though the proxy is configured.

**Comment by jakedowns** [comment] 2020-06-19 20:31
I have the same "corruption" issue where the checksum fails, but the filesize matches. https://github.com/cypress-io/cypress/issues/7761

For no reason at all, after trying to go back to 3.8.3, and then re-downloading 4.8.0, it worked. amazing.

**Comment by Lavaei** [comment] 2020-07-28 10:33
I get this error always when 99% of packaged download successfully! 
The only thing I've changed recently is npm.

**Comment by jennifer-shehane** [comment] 2020-07-28 10:41
If you're using yarn workspaces and getting some corrupt downloads, it may be this issue https://github.com/cypress-io/cypress/issues/6789. See this comment: https://github.com/cypress-io/cypress/issues/6789#issuecomment-604899385

The original issue opened did not involve a corrupted download however, but it seems like most of the comments are referencing corrupted download issues.

**Comment by kylemh** [comment] 2020-07-28 15:16
I always come back to this issue and find that it's always the fact there are two instances in the lockfile. I fix it by matching the resolutions field.

**Comment by moezzie** [comment] 2020-08-19 06:53
Thanks @kylemh 
This fixed the issue for me.
In my case i had @vue/cli-plugin-e2e-cypress (which has Cypress as a dependency) and a separate entry for Cypress in my package.json.

I would have guessed that npm/yarn would figure a out a good way to satisfy the requirements with just one version of Cypress, but i could see, like you said, there were two entries for different versions in the lockfile.

**Comment by tsaiDavid** [comment] 2020-08-24 22:56
> I always come back to this issue and find that it's always the fact there are two instances in the lockfile. I fix it by matching the resolutions field.

Thanks @kylemh - that worked for me as well.

**Comment by kylemh** [comment] 2020-08-24 23:23
If you see where the dependency is coming from, I urge y'all to go to those packages and open an issue asking that Cypress be listed as a _peerDependency_.

**Comment by kylemh** [comment] 2020-09-02 17:18
@jennifer-shehane based on emoji reacts and my own personal experience, I feel like this issue can be closed if there were a better error during installation. Something to indicate that the dev likely has multiple instances listed in their lockfile.

**Comment by chuksgpfr** [comment] 2020-11-16 11:32
This can be solved using `yarn upgrade cypress`

This issue should be closed.

PS: I'm on a Mac OS

**Comment by jennifer-shehane** [comment] 2021-01-22 07:14
Closing as duplicate of #4595

**Closed by jennifer-shehane** 2021-01-22 07:14 UTC
Labels: stage: needs information, topic: installation

**Comment by eysaif** [comment] 2022-12-05 16:40
I'm also getting the same issue 

The Cypress App could not be downloaded.

`The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress.`

**Comment by Teebo** [comment] 2022-12-29 15:04
> I'm also getting the same issue
> 
> The Cypress App could not be downloaded.
> 
> `The Cypress App could not be downloaded.
> 
> Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress.`

Hi, try the below.

[Solution](https://medium.com/motf-creations/nx-workspace-npm-err-the-cypress-app-could-not-be-downloaded-bd33c5cac1b)

**Comment by bipin-codes** [comment] 2024-04-26 04:34
It might be too late, but if you are on windows. 
Use git bash instead of windows cmd prompt

Download the specific binary using
https://download.cypress.io/desktop/12.17.4

`export CYPRESS_INSTALL_BINARY=path_to_downloaded_cypress_zip`
`npm install cypress@specific_version`

Should solve the issue, Thanks!

**Comment by eysaif** [comment] 2024-04-26 05:00
tried Both same error

**Comment by bipin-codes** [comment] 2024-04-26 14:51
Can you add bit more description and screen shots, of what exaclty you tried?

**Comment by gregauger** [comment] 2024-06-17 14:52
I had this issue too with 13.9.0 and npm. Upgrading to 13.11.0 didn't help.  Using a different internet connection (mobile data) didn't help. Switching from node 18 to node 16 didn't help. But after switching to node 20 (in my case via [`n`](https://github.com/tj/n)) then the issue went away.

**Comment by peterzhuamazon** [comment] 2025-08-06 17:03
Using node20 having this exact issue, not on others.
