### ISSUE TITLE
 An unexpected error when launching CYPRESS occurred  EEXIST: file already exists, mkdir 

### ISSUE THREAD

**Issue by Arello** [cypress-io/cypress#7771] opened 2020-06-21 21:01 UTC
When trying to launch Cypress for the first time from the command line an error is displayed

**Message:** EEXIST: file already exists, mkdir 'C:\Users\ariel\Cypress_Automation\node_modules\.bin\cypress'

**Stack trace:**
```
Error: EEXIST: file already exists, mkdir 'C:\Users\ariel\Cypress_Automation\node_modules\.bin\cypress'


```
![image](https://user-images.githubusercontent.com/9436143/85235156-ad656f00-b40a-11ea-8a2a-fad8d42f70fe.png)

**Comment by jennifer-shehane** [comment] 2020-06-22 09:12
Duplicate of #1099

**Closed by jennifer-shehane** 2020-06-22 09:12 UTC
