### ISSUE TITLE
Chrome69 open but no tests open (spec file)  from test Runner

### ISSUE THREAD

**Issue by ndhunagan** [cypress-io/cypress#2571] opened 2018-10-08 16:13 UTC
### Current behavior:
Chrome69 open when i select any spec file but no tests are open
tests opens properly on Electron 59.

### Steps to reproduce:
- `npx cypress open`
- Select Chrome69
- select spec file
- Chrome open but no spec file open

### Versions

Windows 10: Version 1703 (OS Build 15063.786)
Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
Cypress: 3.1.0

**Comment by ndhunagan** [comment] 2018-10-08 16:37
Also I don't cypress extension on Chrome. I am not able to figure how to install this or configure this. I am not able to figure out so far. Could this be the reason for tests not opening on Chrome?

**Comment by jennifer-shehane** [comment] 2018-10-09 18:31
@ndhunagan How did you originally install Cypress? 

You should not need to install Cypress as an extension by itself, it should just work.

**Comment by jennifer-shehane** [comment] 2018-10-09 18:32
Also, can you provide a screenshot of what your screen looks like that indicates 'no spec file open'? Could you also provide the test code you are running?

**Comment by lukeapage** [comment] 2018-10-09 19:10
no problems with chrome 69 on windows 8 for me

**Comment by Nate-Watts** [comment] 2018-10-16 15:45
I am having a similar problem I believe. Running a spec file initially will start, but no test runner will display. Stopping the spec file and running it again will fix the problem. Having to stop the spec file and run it again over every time becomes bothersome.

**Comment by jennifer-shehane** [comment] 2018-11-09 23:54
Unfortunately we'll need to close this issue if no reproducible example is provided.

**Comment by david-ellinger** [comment] 2018-11-12 17:46
I am also experiencing this, installed Cypress with npm. Opens chrome but does nothing.  Let me know if there is any information I can provide.

**Comment by jennifer-shehane** [comment] 2018-11-28 10:02
@david-ellinger We need a reproducible example - Cypress test code that we can run on our machine to see the issue.

**Comment by jennifer-shehane** [comment] 2019-04-24 16:21
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-24 16:21 UTC
Labels: stage: needs information
