### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by hansgpe2** [cypress-io/cypress#21459] opened 2022-05-12 22:48 UTC
### Current behavior

When run
`npm run cypress:headless`

Cypress end with
`The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Fedora - 36)
Cypress Version: 9.6.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! startp@3.2.0 cypress:headless: `cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the startp@3.2.0 cypress:headless script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

### Test code to reproduce

run command
`npm run cypress:headless`

this comand runs
`cypress run`

### Cypress Version

9.6.1

### Other

Platform: linux-x64 (Fedora - 36)
Cypress Version: 9.6.1

 Cypress:        9.6.1                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v14.16.1 (/home/hans/.nvm/versions/node/v14.16.1/bin/node)                     │
  │ Specs:          20 found (abandoned-cart/cancel_reservation.spec.js, abandoned-cart/change_pag │
  │                 e.spec.js, abandoned-cart/complement.spec.js, abandoned-cart/form-filled.spec. │
  │                 js, abandoned-cart/reservation_select.spec.js, members/login_hertz.spec.js, re │
  │                 servaciones/consulta/bo...)                                                    │
  │ Experiments:    experimentalStudio=true

**Comment by mjhenkes** [comment] 2022-05-16 20:33
@hansgpe2, I'm sorry that you're experiencing this crash, unfortunately we don't have a lot to go on. Are you able to recreate this issue? Can you provide a minimally reproducible example? This template can be a good place to start for reproducible examples: https://github.com/cypress-io/cypress-test-tiny

**Comment by jsnjack** [comment] 2022-05-23 17:00
I also had problem with running cypress tests after upgrading to fedora 36. I think the reason is nodejs 16 and openssl 3 combination. The first version to support openssl 3 is nodejs 18. To install it:
```
sudo dnf module install nodejs:18/common
```

This solved the issue for me

**Comment by mjhenkes** [comment] 2022-05-23 21:09
@jsnjack, thanks for the information! @hansgpe2 Is this something that you could try?

**Comment by mjhenkes** [comment] 2022-05-31 16:40
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Closed by mjhenkes** 2022-05-31 16:40 UTC
Labels: stage: awaiting response
