### ISSUE TITLE
define default offset for scrollIntoView

### ISSUE THREAD

**Issue by plehnen** [cypress-io/cypress#3623] opened 2019-03-01 11:37 UTC
### Current behavior:

I have the following code:
```js
cy.contains('#INTERNAL_CATALOGUE .subscription', '11100204')
  .within(() => {
    cy.contains('foo');
    cy.contains('bar');
  });
```

When I want to see in the DOM Snapshot which element is selected, the elements are always scrolled to the very top.

But my layout has a fixed navigation there, so those elements are always invisible.

### Desired behavior:

It would be great if I could define a default `offset`, so all element which are `scrolledIntoView` automatically will actually be visible (e.g. under the fixed sticky navigation on the top)

### Versions

3.1.5, Windows 10, Chrome

**Comment by jennifer-shehane** [comment] 2019-03-01 19:27
Duplicate of https://github.com/cypress-io/cypress/issues/871

**Closed by jennifer-shehane** 2019-03-01 19:27 UTC

**Comment by jennifer-shehane** [comment] 2020-12-08 05:21
In Cypress 6.1.0, there’s a new `scrollBehavior` configuration option that controls the viewport position when an element is scrolled prior to action commands. Possible values are `'top'`, `'bottom'`, `'center'`, `'nearest'`, and `false`, with `'top'` being the default. `scrollBehavior: false` disables scrolling altogether. `scrollBehavior` can be specified in [global configuration](https://on.cypress.io/configuration#Actionability), [test configuration](https://on.cypress.io/writing-and-organizing-tests#Test-Configuration) or individual [action commands](https://on.cypress.io/interacting-with-elements) via options.
