### ISSUE TITLE
cy.log not prints followed/preceded by a failed assertion through expect() command

### ISSUE THREAD

**Issue by pravynandas** [cypress-io/cypress#5375] opened 2019-10-15 21:13 UTC
### Current behavior: 

In below test for the positive assertion `cy.log` prints the message on the left panel (though the comment before is coming 'after' the assert), but for the failed assertion no log prints.

```js
describe('issue with cy.log when combined with expect()', () => {
    it('positive', () => {
        cy.log('comment before expect()')
        expect(true).to.eq(true)
        cy.log('comment after expect()')
    })
    it('negative', () => {
        cy.log('comment before expect()')
        expect(false).to.eq(true)
        cy.log('comment after expect()')
    })
})
```

### Desired behavior:

Irrespective of the result of assertion it is expected to see the `cy.log` commands on the left panel (!?)

### Steps to reproduce: (app code and test code)

run above test in Chrome or electron and validate the result on cypress test runner window.

### Versions

Cypress 3.4.1
Chrome 77/ Electron 61
Windows 10

**Comment by pravynandas** [comment] 2019-10-15 21:14
Snippet of the test result <br/><br/>


![cypress_issue_cy_log_with_expect](https://user-images.githubusercontent.com/4099637/66870318-2b65a200-ef6f-11e9-861b-ec7d701ded8f.png)

**Comment by jennifer-shehane** [comment] 2019-10-29 19:50
@pravynandas This is because you are mixing async and sync code. The expectation in this case is the first thing to run - while the logs are *queued* to run. You can read more explaining this here: https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous

The example below will work how you are wanting it to work. 

```js
describe('issue with cy.log when combined with expect()', () => {
  it('positive', () => {
    cy.log('comment before expect()')
    expect(true).to.eq(true)
    cy.log('comment after expect()')
  })
  it('negative', () => {
    cy.log('comment before expect()').then(() => {
      expect(false).to.eq(true)
    })
    cy.log('comment after expect()')
  })
})
```

Closing as this is the intended behavior of Cypress commands.

**Closed by jennifer-shehane** 2019-10-29 19:50 UTC

**Comment by pravynandas** [comment] 2019-10-30 00:46
Thanks for the explanation and providing example. Appreciated @jennifer-shehane !!
