### ISSUE TITLE
Aliases get deleted after one time use

### ISSUE THREAD

**Issue by vrknetha** [cypress-io/cypress#8171] opened 2020-08-04 09:59 UTC
### Current behavior:

After 'before' execution, the variable is available in 'before each' for only one-time use. Next time, when 'before each' is executed, the alias is not registered. for the first test case, It works properly. 

![image](https://user-images.githubusercontent.com/20596261/89281906-6228b800-d668-11ea-99ac-2253a63d8d42.png)

But for the second test case, 'session' alias is not registered.

![image](https://user-images.githubusercontent.com/20596261/89281097-30632180-d667-11ea-931a-5f23a68a5e40.png)

`before('login using facebook', () => {
		cy.task('ConvosightLogin', {user: 'xxxxxxxx', pass: 'xxxxxxxx'}).as(`session`);
	});

	beforeEach(function () {
		cy.get(`@session`)
			.then(session => {
				cy.RestoreSession(session);
			})
			.visit('group-admin/manage')
			.get(`.c-button`)
			.click();
		cy.server();
	});`

Windows 10, Cypress: 4.11

**Comment by vrknetha** [comment] 2020-08-04 10:45
Closing this as I have figured out using the preserve cookies

**Comment by jennifer-shehane** [comment] 2020-08-05 05:17
Aliases are not reusable when defined in a `before` hook. 

Duplicate of #665

**Closed by jennifer-shehane** 2020-08-05 05:17 UTC
