### ISSUE TITLE
cy.clearLocalStorage does not properly clear the storage

### ISSUE THREAD

**Issue by zeburek** [cypress-io/cypress#5515] opened 2019-10-29 14:55 UTC
### Current behavior:

I have a web-application written in next.js with react.js.
At start-up it loads data from localstorage, and sometimes it breaks (only if I run tests with Cypress, Selenium works OK)

![image](https://user-images.githubusercontent.com/20853475/67777515-e8c5be80-fa72-11e9-93e6-4a388c584b1e.png)

I took a look at localstorage and found that there is an null value in localstorage and only for one key that we used (one of four).

Because of this unexpected null value my WebUI crashes with error.

I've added this to `support/index.js`

```js
afterEach(() => {
  localStorage.clear()
})
```

And now everything is fine - localstorage clears correctly. If I add `cy.clearLocalStorage()` in `beforeEach` or `afterEach` hooks - problem still reproduces.

Also I tested re-writing `Cypress.localStorage.clear` hook with whitelist - this way also works, but I need to clear storage - it's not my way.

### Desired behavior:

LocalStorage should be cleared correctly

### Steps to reproduce: (app code and test code)

Actually I could not provide my WebUI sources, but I can debug my code with, maybe, re-writing `Cypress.localStorage.clear`

### Versions

Cypress: 3.4.1, 3.5.0
Chrome: 77, 78
OS: Ubuntu 18.04 x64

**Comment by jennifer-shehane** [comment] 2019-10-29 15:21
Closing as duplicate of https://github.com/cypress-io/cypress/issues/2573

**Closed by jennifer-shehane** 2019-10-29 15:21 UTC
