### ISSUE TITLE
After updated to cypress 10.4.0, screenshot and videos for failed test didn't capture at correct failed section

### ISSUE THREAD

**Issue by cupcakepanda89** [cypress-io/cypress#23258] opened 2022-08-10 18:45 UTC
### Current behavior

After updated to cypress 10.4.0
- screenshot for failed test didn't capture at correct lines to show which lines of code failed
- when view screenshot for failed test on cypress dashboard it keeps flashing
- the left side on cypress video should scroll as the test runs to show which lines of code failed

### Desired behavior

- screenshot for failed test should capture the failed scenario at correct lines
- the left side on cypress video should scroll as the test runs

### Test code to reproduce

It can be reproduced with any tests

### Cypress Version

10.4.0

### Other

This wasn't an issue at version 9.7

**Comment by rockindahizzy** [comment] 2022-08-11 14:06
Hey @cupcakepanda89,

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment] 2022-08-18 18:09
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by nagash77** 2022-08-18 18:09 UTC
Labels: stage: awaiting response, Needs Reproduction
