### ISSUE TITLE
timeouts with upgrade to >=13.6.3

### ISSUE THREAD

**Issue by jenkma02** [cypress-io/cypress#29126] opened 2024-03-12 21:01 UTC
### Current behavior

I uncovered this issue when I was attempting to upgrade from 13.1.0 to the latest 13.6.6, but i narrowed it down to something introduced in 13.6.3 - that's the version that my tests stopped working in. the issue i'm running into is that routes that im intercepting and then waiting on are taking much longer to load than previous versions and are causing timeouts. we have a really big project with intercepts/aliases everywhere - i know that i could add timeouts to all of them but it's not really feasible for me to do that, especially when it has been working as expected until this upgrade.

### Test code to reproduce

```
cy.intercept('POST', '**/jobs/search').as('postJobsSearch')
cy.wait('@postJobsSearch')
```

this is very basic - hopefully the debug logs are more helpful

### Cypress Version

>= 13.6.3

### Node version

18.16.0

### Operating System

macOS 14.3.1 (23D60)

### Debug Logs

```shell
here is the log for the test ran in 13.6.3, when it started failing. it also fails in higher versions: https://gist.github.com/jenkma02/55a574d39d8e273003fa404514889cb4

logs for the same test, but run in 13.6.2, passing https://gist.github.com/jenkma02/6391ee92d554c31f1b69e665bd6b62ac.js
```

### Other

![Screenshot 2024-03-12 at 3 16 14 PM](https://github.com/cypress-io/cypress/assets/8558372/8576c58d-c38c-49db-b408-a968662a1ca4)

**Comment by jennifer-shehane** [comment] 2024-03-12 22:05
You’re likely running into this issue. We have a fix for this that will be in our next release, hopefully in the next few days. https://github.com/cypress-io/cypress/issues/28868

**Comment by jenkma02** [comment] 2024-03-13 01:20
thanks for looking at this @jennifer-shehane! I will be on the lookout for that new version and will try it again then.

**Comment by jennifer-shehane** [comment] 2024-03-13 15:57
@jenkma02 The 13.7.0 version is out, can you try and verify if this is fixed?

**Comment by jenkma02** [comment] 2024-03-14 17:38
I have been testing the new version out. It is running a lot better than the previous one, but it is still hanging up in some tests waiting on intercepted routes.

**Comment by smartdrop85** [comment] 2024-03-18 13:53
hello. I am experiencing exactly the same issue. in v13.7.0 it's much better with local runs, but in Jenkins+cypress dashboard 30s timeout for requests is not enough to wait for the call to happen any more -> while in v.13.6.2 it works very well with 15s timeout.

**Comment by jenkma02** [comment] 2024-03-20 17:45
@jennifer-shehane i'm having to update pretty much all of my tests for this update after all. do you guys have any plans to make this work the same way it used to in earlier versions?

**Comment by jenkma02** [comment] 2024-03-20 17:49
something else i've noticed occasionally is that the css doesn't load properly on cypress cloud runs either. this doesn't happen in every test, but i run into it at least once during each run (~950 tests)

here is an example of that - https://d.pr/v/7Yu3NO
same test run locally - https://d.pr/v/KJ5gWu

**Comment by sajjad541** [comment] 2024-03-21 12:06
Hi, 
After updating to 13.7.0 version all of my existing tests with intercepts, alias are failing. Route matcher is completely failing for all the tests. Any idea when will this issue be fixed?

![image](https://github.com/cypress-io/cypress/assets/42992227/5fe1c214-7e32-4e24-90b8-3efb517b5aca)

Thanks

**Comment by mschile** [comment] 2024-03-25 17:56
@sajjad541, what version were you upgrading from? Is 13.7.0 the first version that is started failing? Do you have a project I could look at or are you be able to recreate the issue in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by other means?

**Comment by sajjad541** [comment] 2024-03-25 23:53
@mschile , I've upgraded cypress version from 13.0.0 to 13.7.0 with node version 16.15.1. Unfortunately I can't share the code due to security perspective but I will try to reproduce it in cypress-test-tiny repo. For me dynamic intercept calls were working fine earlier but later with version update route matching is completely failing for all existing case.

**Closed as completed** 2024-04-23 17:52 UTC
