### ISSUE TITLE
Cypress: when running in CI / Cypress dashboard does not respect the viewport size

### ISSUE THREAD

**Issue by vomc** [cypress-io/cypress#5794] opened 2019-11-26 09:29 UTC
### Current behavior:

I have a simple test script where I start by setting the viewport like this: 

`cy.viewport(1200, 1200)`

Then I proceed to do actions on the page and capture screenshots. However, when I then use a library to do visual diffing of those screenshots, it is showing me that the full screen ones generated by cypress (which are supposed to be 1200,1200 are actually not that size). 

```javascript

.... file read read as  { width: 1200,
295       height: 720,
296       depth: 8,
297       interlace: false,
298       palette: false,
299       color: true,
300       alpha: true,
301       bpp: 4,
302       colorType: 6,
303       data: ... 
```

Again this is something that works fine locally but not when I am running it inside of Gitlab CI and view the results in the Cypress dashboard.

### Desired behavior:

It would be nice if the viewport of the tests would actually be set as per what the user specifies. Otherwise, why even have that `cy.viewport` option available?

### Steps to reproduce: (app code and test code)

1. Create a script and set viewport to 1200,1200
2. Load the page, take a screenshot
3. See the generated screenshot in the cypress dashboard having dimensions other than what you specified.

### Versions

Cypress 3.61, Linux Debian - 9.6, Electron 73.0.3683.121

**Comment by jennifer-shehane** [comment] 2019-11-26 09:47
Closing as duplicate of #3324 with a larger explanation on why this is currently happening found here https://github.com/cypress-io/cypress/issues/3324#issuecomment-542414532

**Closed by jennifer-shehane** 2019-11-26 09:47 UTC
