### ISSUE TITLE
Whoops, we can't run your tests 

### ISSUE THREAD

**Issue by bhn123** [cypress-io/cypress#15342] opened 2021-03-05 16:18 UTC
### Current behavior
Getting below error while running sample Cypress test in Chrome for the first time:
![image](https://user-images.githubusercontent.com/79097674/110141980-b01ebd80-7dfb-11eb-87e7-17dfdde6cfb2.png)

Doesn't work with Electron either:
![image](https://user-images.githubusercontent.com/79097674/110143956-d04f7c00-7dfd-11eb-82e5-9312b73cd41e.png)

### Desired behavior
Need to able to run all Cypress default examples in chrome without any issues

### Test code to reproduce
Below commands are used to install Cypress
cd c:\Cypress
npm init
npm install cypress --save-dev
node_modules\.bin\cypress open

Ran actions.spec.js by selecting "Chrome 88"

(increased timeout "const VERIFY_TEST_RUNNER_TIMEOUT_MS = 100000" in C:\Cypress\node_modules\cypress\lib\tasks\verify.js as it was throwing time out error while opening cypress)

### Versions

node.js version : v12.13.1
npm version : 6.12.1
chrome version : Version 88.0.4324.190 (Official Build) (64-bit)
OS : Windows 10 Enterprise 64 bit
Cypress version : 6.6.0

**Comment by bhn123** [comment] 2021-03-05 16:26
Adding more details:

Doesn't work with Electron either:
![image](https://user-images.githubusercontent.com/79097674/110143709-88c8f000-7dfd-11eb-8e0c-c8b966b1e96b.png)

**Comment by jennifer-shehane** [comment] 2021-03-05 19:25
Duplicate of https://github.com/cypress-io/cypress/issues/6889 

Certain group policies (GPOs) on Windows may prevent Cypress from working as intended, which can cause tests to break. We do try to detect this and should warn when it is detected.

You may want to read here for more info and workarounds: https://on.cypress.io/error-messages#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues and see if any of those resolve your issue

**Closed by jennifer-shehane** 2021-03-05 19:25 UTC
Labels: topic: 😳 whoops we can't run your tests

**Comment by bhn123** [comment] 2021-03-08 14:31
The issue is not only with respect to Chrome... 
With Electron also it fails. I see for others this is working.
