### ISSUE TITLE
Cypress does not reproduce script.

### ISSUE THREAD

**Issue by yasminjulia** [cypress-io/cypress#7482] opened 2020-05-26 17:22 UTC
### Current behavior:
![image](https://user-images.githubusercontent.com/33433251/82929373-ee787980-9f59-11ea-91d0-6dc796d0f905.png)

When i run my script project the Electron version 80 open but the tests steps does not reproduce, on terminal they pass. 
![image](https://user-images.githubusercontent.com/33433251/82929659-65ae0d80-9f5a-11ea-82e8-4378de87e236.png)

### Desired behavior:

I already revised my code and it run in other PC, this issue ocurr for any script project, i reinstalled the cypress puglins but still happen.

### Test code to reproduce
My project: 
https://github.com/yasminjulia/Cypresse/tree/master/ProjetinhoBarriga/cypress

### Versions
Cypress 4.6.0
Google Chrome

I'm available to contact for any question on;
E-mail: yasminjullia@live.com
Phone: +55 71 993637574

**Comment by jennifer-shehane** [comment] 2020-05-29 11:34
This is because you've added a command with the name 'reset', which is a reserved word that Cypress uses as an internal command. This is not documented anywhere however.

The `before` is further swallowing up the error for some reason, but you can see some kind of error in the console, albeit wouldn't lead you to understand that `reset` is reserved for command names. 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress.js#L364:L364

```js
Cypress.Commands.add('reset', () => {})

describe('tests', () => {
  before(() => {})

  it('test', () => {
    expect(true).to.be.true
  })
})
```

## Workaround

Rename your custom command anything other than `reset`. 

```js
Cypress.Commands.add('resetApp', () => {}) // works now!
```

Closing this as a duplicate of https://github.com/cypress-io/cypress/issues/6146 which documents another reserved word for commands that someone else encountered.

**Closed by jennifer-shehane** 2020-05-29 11:34 UTC
