### ISSUE TITLE
Issues with Turn off uncaught exception handling unhandled promise rejections does not work from a beforeEach hooks

### ISSUE THREAD

**Issue by Bharath-Kumar-S** [cypress-io/cypress#16527] opened 2021-05-14 20:33 UTC
I am using cypress 7.3.0 and I tried to turn off unhandled promise rejections with the snippet from Migration guide

```js
Cypress.on('uncaught:exception', (err, runnable, promise) => {
  // when the exception originated from an unhandled promise
  // rejection, the promise is provided as a third argument
  // you can turn off failing the test in this case
  if (promise) {
    // returning false here prevents Cypress from
    // failing the test
    cy.log(err);
    return false
  }
})
```

```js 
beforeEach(() => {
        cy.visit('https://example.cypress.io/commands/actions')

        let a = () =>{
            return new Promise((resolve,reject)=>{
                return reject();
            })
        }

        a()
    })
```
Works fine from a test but fails in hooks beforeEach and other.

**Comment by jennifer-shehane** [comment] 2021-05-17 17:32
It would help to see the error, but likely this is because you cannot currently call `cy.` commands within the Cypress event listeners. 

Duplicate of https://github.com/cypress-io/cypress/issues/6316

**Closed by jennifer-shehane** 2021-05-17 17:32 UTC

**Comment by Bharath-Kumar-S** [comment] 2021-05-17 18:51
@jennifer-shehane it was just to demonstrate. In the actual code a helper function is called from before hooks and in that helper unhandled promise rejection happens

**Comment by jennifer-shehane** [comment] 2021-05-17 19:44
The `uncaught:exception` handler will catch unhandled rejections from the application under test. Since this error is being thrown from the test code, Cypress will always catch unhandled rejections in the test code, this can't be ignored. 

Can you provide a real example of the issue you're encountering, that we can run and reproduce and the error message. I think that would be more helpful in finding a solution than the example above.
