### ISSUE TITLE
Permission denied when accessing Iframes in firefox and cypress crashes when accessing in chrome

### ISSUE THREAD

**Issue by muralinaidud** [cypress-io/cypress#19327] opened 2021-12-10 07:54 UTC
### Current behavior

when I run test which included Iframes to load, I am getting **Permission denied to access property "toString" on cross-origin object** in Firefox Browser.

And then I figure out to make it work in chrome by chromeWebSecurity as false and it used to run the test but cypress is crashing before the test complete, 

As I cannot attach a video of my issue which is more than 10kb, please mail me murali08211@gmail.com if required more info on this

![cypress permission denied](https://user-images.githubusercontent.com/93142100/145537512-e93dc209-c798-47c2-a1a7-11e369f65220.PNG)

### Desired behavior

 The tests should run successfully
 
 

### Test code to reproduce
```js
import datas from "../../../fixtures/XXXX.json";

describe("customer registration journey", () => {
  context(
    `test:  ${datas[0].casinoName} country:  Finland viewport: ${datas[0].viewports} `,
    () => {
      beforeEach(() => {
        cy.viewport(1920, 1080);
        cy.setCookie("test_country", "FI");
        cy.setCookie("language", "en");
        cy.visit({
          url: datas[0].baseURL,
        });
      });

      it("should complete test pnp registration process for finland users", function () {
        cy.get('[href="/login"]').findByText("Account").click();
        cy.wait(2000);
        cy.get(".mt-3").get("h1").should("have.text", "Deposit");
        cy.get(".row.no-gutters").should("be.visible");
        cy.get(".btn.btn-primary").should("have.text", " Deposit ");
        cy.get(".btn.btn-primary").should("be.disabled");
        cy.get(".btn.btn-outline-secondary.btn-block.amount-btn").each(
          ($el) => {
            const a = $el.text();
            cy.log(a);
            if (a === " 200€ ") {
              cy.get($el).scrollIntoView().click({ force: true });
            }
          }
        );
        cy.get(".btn.btn-primary").should("have.text", " Deposit €200").click();
        cy.wait(6000);
        cy.pnpIframe(datas[0]);
        cy.url().should("include", datas[0].url + "trustly/confirm");
        cy.get("#terms").click();
        cy.get(".btn.btn-primary").click();
        cy.url().should("include", datas[0].url + "trustly/success");
        cy.get(".col-12.text-center").eq(0).should("have.text", "Welcome!");
        cy.get(".col-12.text-center")
          .eq(1)
          .should("have.text", "Your balance has been updated");
      });
    }
  );
});
```

**in command.js**
```js
Cypress.Commands.add("pnpIframe", (data) => {
  if (
    data.casinoName === "XXXX" ||
    data.casinoName === "XXXX" ||
    data.casinoName === "XXXX"
  ) {
    cy.frameLoaded("lib-trustly-frame > iframe");
    cy.iframe("lib-trustly-frame > iframe").as("iframe");
  }else if (data.casinoName === "XXXX") {
    cy.frameLoaded(".trustly-cont > iframe");
    cy.iframe(".trustly-cont > iframe").as("iframe");
  }
  else {
    cy.frameLoaded("#trustly-frame");
    cy.iframe("#trustly-frame").as("iframe");
  }
  //cy.iframe('#trustly-frame').find('.inner').should('have.text','Deposit amount: 250€')
  cy.get("@iframe").find(".core_method:first").click();
  cy.wait(4000);
  cy.get("@iframe").find("a.button.core_action_button.button_next").click({force: true});
  cy.wait(2000);
  cy.get("@iframe")
    .find('[name="loginid"]')
    .type("auto" + faker.random.number(10000));
  cy.get("@iframe")
    .find('[href="next:submit_userid"]')
    .eq(0)
    .click({ force: true });
  cy.wait(2000);
  cy.get("@iframe")
    .find("span.message_value:first")
    .invoke("text")
    .then((code) => {
      cy.get("@iframe").find('input[type="password"]').type(code);
    });
  cy.get("@iframe").find('[href="next:submit_challenge_response"]').click();
  cy.wait(15000);
  cy.get("@iframe").find(".accountname").eq(0).click();
  cy.get("@iframe").find('[href="next:submit_account"]').click({ force: true });
  cy.wait(10000);
  cy.get("@iframe")
    .find("span.message_value:first")
    .invoke("text")
    .then((code) => {
      cy.get("@iframe").find('input[type="password"]').type(code);
    });
  cy.get("@iframe")
    .find('[href="next:submit_challenge_response"]')
    .click({ force: true });
  cy.wait(20000);
});
```
**In fixtures**
```js
[
  {
    "casinoName": "XXXX",
    "name": "XXXX",
    "baseURL": "XXXXXX",
    "url": "https://XXXX.XXXX.com/",
    "gender": "Male",
    "country": [
      {
        "selectCountry": "UNITED KINGDOM",
        "code": "GB",
        "currency": "GBP",
        "dialingCode": "+44",
        "loqate": "yes"
      }
    ],
    "email": "automation.test",
    "viewports": ["1920,1080"]
  }
]

```

### Cypress Version

9.0.0

Logs

**Comment by marty30** [comment] 2022-03-23 14:02
@muralinaidud, did you get it to work in the end?

**Comment by muralinaidud** [comment] 2022-03-23 14:24
Hi @marty30  no in firefox it never worked.
and in chrome it worked but crashes in the middle of the test

**Comment by truefalse10** [comment] 2022-08-10 13:42
Hi, i am having the same issue with cypress 10.4.0 and firefox 102

**Comment by muralinaidud** [comment] 2022-08-10 14:16
for me chrome still crashed and there is no error logs cypress 10.4.0

**Comment by muralinaidud** [comment] 2023-05-15 14:24
This issue is still remains same, on latest versions also cypress studio just crashes without any logs

**Comment by marktnoonan** [comment] 2023-05-15 17:02
Thanks @muralinaidud. I've attempted to reproduce this but haven't been successful, I can install cypress-iframe and call `cy.iframe()`, then test parts of the iframe without a problem in Firefox.

So this doesn't seem to be an issue with all iframes in Firefox, there's likely something else going on that might be related to the specific details of your project.

Do you think you could try to create a reproduction that we could work with, you can use the template https://github.com/cypress-io/cypress-test-tiny 

Without a reproduction it's hard for us to debug the issue.

For the other item you mentioned:

> cypress studio just crashes without any logs

Could you tell me more about this? Are you attempting to record a test with Cypress Studio and it doesn't work?

**Comment by muralinaidud** [comment] 2023-05-15 19:34
HI @marktnoonan 
[2023-05-15-21-25-53.zip](https://github.com/cypress-io/cypress/files/11481280/2023-05-15-21-25-53.zip)

please check the attached zip file for video recording for the issue I raised

This video is regarding the crash which I am talking about

**Comment by muralinaidud** [comment] 2023-05-15 19:39
Hi @marktnoonan 

I still have permission denied issue when running iframe test in firefox

![image](https://github.com/cypress-io/cypress/assets/93142100/425f6af9-3065-4296-bcd4-90142fb610b0)

**Comment by marktnoonan** [comment] 2023-05-15 22:10
Thanks @muralinaidud. I didn't notice till now that this error is pointing to code that is part of the `cypress-iframe` plugin, which is not maintained by us. It seems like the right place for this issue is the repo for that project: https://gitlab.com/kgroat/cypress-iframe/-/issues - it looks similar to this one https://gitlab.com/kgroat/cypress-iframe/-/issues/13

Looking at the error itself, it seems like the content of the iframe you are testing is on a different origin than the parent page, so that might be the cause of the problem with the other plugin, you would need to follow up there. Here is what I found out about that error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied

I'm going to close this issue for now since it doesn't appear to be a problem with Cypress itself.

**Closed by marktnoonan** 2023-05-15 22:10 UTC
Labels: type: bug

**Comment by muralinaidud** [comment] 2023-05-16 05:06
Hi @marktnoonan I was talking about 2 issues here 
1. Crash 
2. Permission denied in firefox 
I can see your explanation regarding 2nd issue but al though it's not a solution anyway, Then what about the crash, if cypress can't handle such webpage it suppose to just fail the test case but it is crashing 
Studio crash is definitely a bug with cypress, please check the video I uploaded.
You can't close an issue without ressolving.
I am ready to have a call and share the code to help you debug

**Comment by marktnoonan** [comment] 2023-05-17 13:55
Hi @muralinaidud, ah I see, we should make a new GitHub issue to discuss the crash since it seems to be unrelated to the iFrame issue. I've made https://github.com/cypress-io/cypress/issues/26775 to discuss further. I'll tag you there.

We can leave this one closed in regards to the iframe issue. I agree it's not a solution but since the error is being thrown by a third party package which we don't control, you would need to engage the authors of that package to follow up.
