### ISSUE TITLE
Issue with File download - running Cypress  in headless mode, a "confirm download" popup is opened (no interaction should be needed), and test never ends -(PAGE LOAD) --waiting for new page to load-- error, 

### ISSUE THREAD

**Issue by ArthurMk** [cypress-io/cypress#5651] opened 2019-11-10 21:15 UTC
### Current behavior:
Dear community, 
I have faced the following issue, I will be grateful if somebody can help. 
The task is to do some actions with the files, and after check the downloadable file - name and size. 

I have implemented it using the direction mentioned in another issue - (In-browser file download support [#949](https://github.com/cypress-io/cypress/issues/949)). 
I am able to read the file, parse it, get the name and get the size. 
Unfortunately, the next steps aim to fail tests that contain download functionality. 
Current behavior - 
1. Get downloadable file binary(see code below), assert name and size.  (Auto download of file take place in this step.)
2. After it in Cypress test run I am getting (PAGE LOAD)
--waiting for new page to load--   after the timeout the tests fail. 
3. Running a single test in command line mode,  after assertions the Download dialog is shown, which makes tests fail. As I get after this, in first UI run mode, my tests failing by this reason. 
-----------------
Code for checking downloadable file size and name. 

```js
Cypress.Commands.add('download', (downloadSize,downloadVariation,downloadName) => {
        cy.log('The Download page is loaded.');
        cy.get('.downloader__btn.active').then((anchor) => {
            const url = anchor.attr('href');
            cy.log('The Download page is loaded.');

            cy.request(url).then((res => {
                cy.log(res.body.length);
                cy.log(downloadSize);
                cy.log(JSON.stringify(res));
                cy.wait(1000);
                cy.expect(JSON.stringify(res.headers["content-disposition"])).contains(downloadName)                 
                cy.expect(res.body.length).to.equal(downloadSize);
        }));
    });
})
```
Size and Name assertions working fine, only issue is after I am getting (PAGE LOAD)
--waiting for new page to load-- error, as I am thinking the reasson is running Cypress  in headless, a "confirm download" popup is opened (and no interaction should be needed), and test never ends. When I am running tests in Cypress UI, I am not getting the Pop Up(but tests are failing with same reasson.)
 

![image](https://user-images.githubusercontent.com/56301796/68551236-40293e80-0424-11ea-860d-3f7c780c79b4.png)

### Desired behavior:

I want to FORCE prevent Auto download and prevent (PAGE LOAD)
--waiting for a new page to load--  error. 

### Versions
Updated Cypress to version 3.6.0 (does not help, I am still can not interact with download event)
Chrome Version - 78.0.3904.87

**Comment by ashlincascade** [comment] 2019-11-11 17:59
We are seeing the same problem, except that the test which downloads a file passes in standard mode and fails in headless mode. And in our case, we don't `cy.request` the file specifically, just `cy.click` on the link to download it.

**Comment by jennifer-shehane** [comment] 2019-11-13 01:02
We don't directly support file download and will regard all issues related to file download to the original issue asking for support. Closing as duplicate of https://github.com/cypress-io/cypress/issues/949

**Closed by jennifer-shehane** 2019-11-13 01:02 UTC

**Comment by Gurgen** [comment] 2019-11-14 21:21
> We don't directly support file download and will regard all issues related to file download to the original issue asking for support. Closing as duplicate of #949

Dear Jennifer, issue discussed in #949 but not resolved, is there any way to cancel browser file download?

**Comment by jennifer-shehane** [comment] 2021-01-20 04:35
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
