### ISSUE TITLE
Test gets into runaway loop if cy.wrap is inside cy.should

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14656] opened 2021-01-20 17:44 UTC
Cypress v6.3.0
```js
it('gets into a loop', () => {
  cy.wrap('bar')
    .should(() => {
      cy.wrap('foo')
    })
})
```

Runs away, never finishes

https://user-images.githubusercontent.com/2212006/105213850-39648400-5b1d-11eb-92fe-0d04751496e6.mp4

Example in https://github.com/cypress-io/cypress-test-tiny/tree/runaway

**Comment by sainthkh** [comment] 2021-03-09 04:29
Problem solved. I'll upload the PR with why it happened tomorrow.

**Comment by sainthkh** [comment] 2021-03-10 04:29
The problem is related with the command stack. I explained why in #15386.

**Comment by sainthkh** [comment] 2021-03-16 03:36
I tried 2 approaches and learned that allowing cy commands inside `should` callback is impossible because of `Cypress detected that you returned a promise in a test, but also invoked one or more cy commands inside of that promise.` error. I tried to solve this problem by removing `Promise` inside `shouldFnWithCallback`, but it also failed. It might be because `should` command is called inside a `Promise`.

If you want to check that cy commands don't work inside `should` callback, test the code below:

```js
it('gets into a loop', () => {
  cy.wrap('bar')
    .should(() => {
      cy.wrap('foo')
      cy.wrap('test')
    })
})
```

All you can see is `wrap foo`. `wrap test` is never shown. Because the error is thrown. 

If you want to check the thrown error, wrap `fn` call with `try...catch` below.

https://github.com/cypress-io/cypress/blob/cb281d17e4e4cce3eff22f367dbb86837b299439/packages/driver/src/cy/commands/asserting.js#L11-L24

----

I also thought what's the best solution for this. Showing "cy commands are not allowed inside `should` command" might be a good idea.

What do you think, @bahmutov?

**Comment by jennifer-shehane** [comment] 2021-05-18 22:32
Oof, I feel like I've seen this behavior before. Ideally I would like this to just work as expected, but probably throwing an error would be better than an infinite loop. I"m not sure what the rest of the team thinks though.

**Comment by bahmutov** [comment] 2021-11-05 02:33
Just randomly hit this again, ughh, and aside from this I do see runaway tests sometimes, but larger ones, seems there might be edge cases in the internal logic

```js
it('never finishes', () => {
  cy.wrap(1).should(() => cy.log('here'))
})
```

https://user-images.githubusercontent.com/2212006/140448613-37acd0d6-3106-4977-8559-f9f2dc4ddbe9.mp4

**Comment by testingJava2** [comment] 2021-12-06 19:50
Hello @bahmutov, @jennifer-shehane,

Until this is fixed, are there any workarounds that you can recommend?

Thank you,

Alex

**Comment by theseion** [comment] 2022-10-21 06:18
I'm seeing the same thing with both `cy.wrap` and `cy.get` inside `should`. And I have a case where I need to check that the text from element A shows up in element B _after_ element A has been removed. I haven't found a way to make it work any other way, not even by cheating with a variable defined in the outer scope.

```
cy.get(panel.dropdownOptions)
      .first()
      .should(option => {
        const selectedTimezone = option.text();
        // Click the option to populate the autocomplete with the option value
        // The dropdown will be removed from the DOM.
        cy.wrap(option).click(); // <----------------- loops forever
        // Now check that the input has been populated with the option value.
        cy.get(panel.timezoneInput).should('have.value', selectedTimezone); // <---------- loops forever if `cy.wrap` is commented
      });
```

I feel this is a pretty big issue. Yes, it doesn't matter in the majority of cases but there are some things that aren't possible to do otherwise.

**Comment by theseion** [comment] 2022-10-21 06:39
For anybody else ending up here, I **did** figure out a solution, using aliasing and `then` instead of `should`:
```javascript
// aliasing is necessary here, because getting that same element inside `then`
// fails (the context is a different document at that time)
cy.get(panel.timezoneInput).as('input');
    cy.get(panel.dropdownOptions)
      .first()
      .then(option => {
        const selectedTimezone = option.text().trim();
        // `cy.wrap` magically works in `then`, even though it fails in `should`
        cy.wrap(option).click();
        cy.get('@input').should('have.value', selectedTimezone);
      });
```

**Comment by emilyrohrbough** [comment] 2022-11-17 16:20
https://github.com/cypress-io/cypress/pull/23734 made a breaking change to now throw an error if Cypress commands are invoked from inside a `.should()` callback since this resulted in unusual and undefined behavior.

Closing this issue since this is no longer relevant.

**Closed by emilyrohrbough** 2022-11-17 16:20 UTC
Labels: type: bug, pkg/driver, stage: backlog

**Comment by bahmutov** [comment] 2022-11-17 16:33
Super
