### ISSUE TITLE
Cypress is not running on windows 7- 32bit

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#1554] opened 2018-04-09 18:35 UTC
- Operating System: Windows 7
- Cypress Version: Latest(1.8.2)
- Browser Version: Chrome 65.0.3325.181 (Official Build) (32 bit) 

Hi all,
I downloaded cypress last update from;
https://download.cypress.io/desktop?platform=win32&arch=x86
but it says "this program is incompetible with your Windows. Please check program requirements whether x86 or x64"
what can I do?
Thanks

**Comment by TinaMohanty** [comment] 2018-06-26 21:46
I am also facing the same issue. Looking for some suggestion.

**Comment by Saibamen** [comment] 2019-02-22 21:18
Please check latest Cypress version from http://download.cypress.io/desktop

**Comment by jennifer-shehane** [comment] 2019-03-01 22:16
Closing. Please comment if you are still experiencing this issue.

**Comment by timelights** [comment] 2019-03-02 09:06
> Please check latest Cypress version from http://download.cypress.io/desktop

After the .zip file had been downloaded from the above site, I clicked on "Cypress.exe" and encountered the same issue.

I am running on Windows 7 
32-bit Operating system.

And whenever I try another workaround for npm, it just say:
```
Cypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
spawn UNKNOWN
----------
Platform: win32 (6.1.7600)
Cypress Version: 3.1.5
```

**Comment by Saibamen** [comment] 2019-03-06 08:26
What is your `npm --version` and `node --version`?

**Comment by jennifer-shehane** [comment] 2019-03-06 17:44
Where are you running the `cypress open`/`cypress run` command from? Is it in a plain terminal (cmd) window or from a terminal within your IDE program? I've read that running from the IDE terminal may cause this issue.

**Comment by jennifer-shehane** [comment] 2019-03-06 17:45
Closing as duplicate of https://github.com/cypress-io/cypress/issues/787

**Closed by jennifer-shehane** 2019-03-06 17:45 UTC
Labels: OS: windows, stage: needs information

**Comment by timelights** [comment] 2019-03-09 10:48
@Saibamen 
> What is your `npm --version` and `node --version`?

Node version: v11.10.1
npm version: 6.7.0

**Comment by jennifer-shehane** [comment] 2019-03-11 03:30
@timelights Please comment and follow this issue https://github.com/cypress-io/cypress/issues/787
