### ISSUE TITLE
Configuration to start a test with the command log collapsed

### ISSUE THREAD

**Issue by gtmath** [cypress-io/cypress#7820] opened 2020-06-25 22:29 UTC
### Current behavior:
When running tests via cypress run (or open) the command log (left pane) is expanded by default.  In both cases, with large end to end tests, performance seems to slow down over time within a single test scope.

When running via cypress open and immediately collapsing the command log on test execution, there is no slow down.  Information is retained and available upon expansion if needed.

### Desired behavior:
A CLI or configuration option to have the command log collapsed by default upon launching a test.

### Versions
4.9.0

**Comment by jennifer-shehane** [comment] 2020-06-26 11:52
Duplicate of #6270

**Closed by jennifer-shehane** 2020-06-26 11:52 UTC
