### ISSUE TITLE
Angular component test are not working @nrwl/nx

### ISSUE THREAD

**Issue by wolfmanfx** [cypress-io/cypress#23364] opened 2022-08-16 13:46 UTC
### Current behavior

When you try to configure cypress component tests the angularHandler.ts is failing in 'getAngularCliWebpackConfig' function. 
The root cause is that the NX is splitting up the angular.json into multiple project.json files to decrease the clutter of angular.json.
This angular.json has the 'version: 2' and contains the relative path per project within the json

`{
  "version": 2,
  "projects": {
    "demo": "apps/demo"
  },
  "defaultProject": "demo"
}`

At the current situation it is not possible to use that great feature when a nx mono repo is used.

### Desired behavior

It could check for version 2 and retrieve the project.json from the relative path which is declared within the angular.json. Other solution would not to crash and give us a way to manually configure the component tests - which would be suboptimal.

### Test code to reproduce

npx create-nx-workspace@latest

// Create a simple angular project (check the screenshot)

![image](https://user-images.githubusercontent.com/730199/184894157-4edc12b6-47ef-405a-ad95-a80f480da201.png)

cd demo-cypress-crash

// Update cypress

npm i cypress@10.5 --dev

npx cypress open

Now click on component testing

Angular is displayed - Click on  "Next Step"

Click on Continue

Now enjoy the error message

![image](https://user-images.githubusercontent.com/730199/184895048-2219c7b3-308d-4574-acd1-82466b4b1110.png)

Now you could add the default project to the angular.json
`
  "defaultProject": "demo-cypress"`

Than it will crash here

![image](https://user-images.githubusercontent.com/730199/184895302-eff1aa6b-3d9c-450b-abaf-bb9be8d6b516.png)

### Cypress Version

10.5.0

### Node version

v16.16.0

### Operating System

macOS 12.5

**Comment by ZachJW34** [comment] 2022-08-16 20:12
You can follow https://github.com/cypress-io/cypress/issues/23161, we are working with the Nx team to add first class support for Angular CT + Nx

**Comment by mjhenkes** [comment] 2022-08-17 18:19
Closing as a duplicate of #23161

**Closed by mjhenkes** 2022-08-17 18:19 UTC
Labels: stage: investigating
