### ISSUE TITLE
Unzipping of the binary takes to long time on netlify

### ISSUE THREAD

**Issue by davidsoderberg** [cypress-io/cypress#3419] opened 2019-02-10 05:42 UTC
### Current behavior:
The build fail.

### Desired behavior:
The build continues.

### Steps to reproduce:
Import an project with cypress into [netlify](https://www.netlify.com/).
Run your build so that cypress are installed with `npm install`.

### Versions
Cypress: 3.1.5

**Comment by jennifer-shehane** [comment] 2019-02-11 08:57
Hey, I was able to reproduce this. It's unzipping very very slowly. 😐

### To recreate:

1. [Sign up for an account on Netlify](https://app.netlify.com/signup)
2. Click **New site from Git**
3. Connect to GitHub
4. Pick the `cypress-example-kitchensink` repository
5. Select the `netlify` branch, add build command as `npm run build`, add publish directory as `app`
6. Click **Deploy site**
7. Under **Production deploys**, you should see Production `building` - click in here and you'll eventually see Cypress unzipping forever.

**Comment by bahmutov** [comment] 2019-02-11 14:32
So I believe the problems are:
- Netlify does not give you a powerful machine to execute your build commands. It is NOT a full continuous integration service like GitLab / Circle / ... so do not expect speed from them in this step
- Netlify build environment does not include zip utilities, thus forcing Cypress to unzip in software, which is much slower that using compiled Zip binaries.

I don't know if there is anything we can really do. Aside from unzipping, I don't believe we can cache the Cypress binary and npm modules on Netlify, is there? It was a while since I looked at Cypress + Netlify combination https://glebbahmutov.com/blog/gatsby-netlify-circle-and-cypress/

So I will close this issue for now, but feel free to reopen if there are actionable things we should do in your opinion.

**Closed by bahmutov** 2019-02-11 14:32 UTC
Labels: stage: ready for work, type: unexpected behavior

**Comment by rotexhawk** [comment] 2019-03-12 18:49
I followed your guide and copied the scripts to my project but I am still getting the terminal message which eventually times out the build.

**Comment by onetwothreebutter** [comment] 2019-04-08 20:03
@bahmutov My team is experiencing this issue with long unzipping of Cypress too.

**Comment by lukemelas** [comment] 2019-08-29 21:19
I'm also experiencing issues unzipping cypress.

**Comment by nickytonline** [comment] 2019-12-04 23:42
It does take a while, but in my case it still deploys.@swyx from Netlify chimed in about a way to cached Cypress for those interested, https://twitter.com/nickytonline/status/1160914001511026688

**Comment by rotexhawk** [comment] 2019-12-06 14:57
@lukemelas add this to your netlify.toml

```
[build.environment]
  CI="1"
```

**Comment by nickytonline** [comment] 2019-12-06 15:12
Yeah, I run CI=1 as well, just not in my netlify.toml

https://github.com/nickytonline/www.iamdeveloper.com/blob/master/package.json#L15

**Comment by rotexhawk** [comment] 2019-12-06 18:17
For some reason that doesn't work on netlify. I tried that as well, before going the `netlify.toml` route.

**Comment by nickytonline** [comment] 2019-12-06 19:25
Weird, CI in my package.json works for me and I deploy to Netlify. Thanks for suggesting the cache plugin. I'll definitely add that to my project.
