### ISSUE TITLE
Azure Pipeline commit sha incorrect for github status check

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [cypress-io/cypress#5769] opened 2019-11-21 22:33 UTC
### Current behavior:

A status check is generate for the merge commit of a PR instead of the commit from the head branch. (example: https://github.com/microsoft/BotFramework-Composer/commit/20df2712b096decaf92c22bfc69c5816170c354e)

### Desired behavior:

The status should be reported on the commit sha for the head branch. (https://github.com/microsoft/BotFramework-Composer/commit/90ff91086f4692524e8bfbf3e3a393e316a693e7)

### Steps to reproduce: (app code and test code)

1. Create an Azure Pipeline with a PR validation trigger that runs `cypress --record`.
2. Open a pull request that will trigger new az pipeline.
3. Notice the check does not appear on the pull request commit.

### Versions

Cypress package version: 3.6.1
Cypress binary version: 3.6.1

**Comment by jennifer-shehane** [comment] 2020-01-03 05:24
We pull in environment variables set from the CI provider in order to get the correct commit SHA. For Azure, we are pulling `BUILD_SOURCEVERSION`.

This comment in Azure mentions why this env variable is inaccurate during Pull requests. 

>On a pull request, Azure DevOps does not build the exact version of the code that you pushed, but rather a version merged with your target branch; I suspect that is the commit id that you are getting. When the PR is completed this is the same commit id you will see in your tree, assuming the target branch pointer has not advanced.
>https://github.com/microsoft/azure-pipelines-tasks/issues/9801

They then confirm that the environment variable `$(system.pullRequest.sourceCommitId)` would give the accurate commit SHA, even though this environment variable is [completely undocumented](https://github.com/MicrosoftDocs/vsts-docs/issues/4588). 

This may be fixed by updating our code in our `ci_provider.js` file to account for the alternative ID if it is present. Similar to this PR we did for Travis https://github.com/cypress-io/cypress/pull/5714 (which actually did not fix this similar issue in Travis unfortunately).

https://github.com/cypress-io/cypress/blob/issue-2869-config-changes/packages/server/lib/util/ci_provider.js#L360:L360

I would have to do some experiments to ensure this is even present and being pulled correctly though.

**Comment by jennifer-shehane** [comment] 2020-01-06 05:25
Looking through our Azure runs in our `example-kitchensink-project`

## Commit 'merge branch master into....'

So, since the main issue was about the status check not running on a merging of the head branch into the sub branch, I tried to reproduce that here. 

https://github.com/cypress-io/cypress-example-kitchensink/pull/123/commits/232185aa316d415f396cf1b63e61c20c074c38e5

This triggered 2 runs in Azure. 

![Screen Shot 2020-01-06 at 11 33 17 AM](https://user-images.githubusercontent.com/1271364/71796299-66f89f80-3078-11ea-9bde-80857dd13ff2.png)

## Commit `Merge 232185 into 7019b`

- **Commit:** https://github.com/cypress-io/cypress-example-kitchensink/commit/edc7ae472ed952e4245fd466364c335dd8634f5f
- **Dashboard run:** https://dashboard.cypress.io/projects/4b7344/runs/11547/specs

**Env vars:**
- `BUILD_SOURCEVERSION=edc7ae472ed952e4245fd466364c335dd8634f5f`
- `SYSTEM_PULLREQUEST_SOURCECOMMITID=232185aa316d415f396cf1b63e61c20c074c38e5`

You can see the GitHub status check ran for this commit. 

![Screen Shot 2020-01-06 at 11 42 56 AM](https://user-images.githubusercontent.com/1271364/71796762-b4c1d780-3079-11ea-9b5f-5908c8433070.png)


## Commit `Merge branch 'master' into cypress-4`

- **Commit:** https://github.com/cypress-io/cypress-example-kitchensink/commit/232185aa316d415f396cf1b63e61c20c074c38e5
- **Dashboard run:** https://dashboard.cypress.io/projects/4b7344/runs/11548/specs

**Env vars:**
- `BUILD_SOURCEVERSION=232185aa316d415f396cf1b63e61c20c074c38e5`
- There is no `SYSTEM_PULLREQUEST_SOURCECOMMITID` env var

You can see the GitHub status check ran for this commit. 

![Screen Shot 2020-01-06 at 11 43 38 AM](https://user-images.githubusercontent.com/1271364/71796782-d7ec8700-3079-11ea-9d27-8c4263adc0e3.png)

## `azure-ci.yml`

- Our `azure-ci.yml`: https://github.com/cypress-io/cypress-example-kitchensink/blob/master/azure-ci.yml
- Their `azure-pipelines.yml`: https://github.com/microsoft/BotFramework-Composer/blob/stable/azure-pipelines.yml

They do have a `trigger` setup to only trigger CI on `master`. I'm not sure this should make any different though. https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#branches

## Conclusion

Yet again, I cannot recreate the situation described where the status checks do not run during a build. 

@a-b-r-o-w-n Can you provide any more specifics about the runs that may be relevant? Maybe you have some extra settings that we do not have on our project?

**Comment by a-b-r-o-w-n** [comment] 2020-01-06 17:55
@jennifer-shehane The pull request you linked correctly has the Azure CI check, but the cypress check (https://dashboard.cypress.io/projects/4b7344/runs/11547/specs) was generated by the individual Azure pipeline run (https://cypress-io.visualstudio.com/cypress-example-kitchensink/_build/results?buildId=894&view=results). This is consistent with my testing, the PR check only reports on the merge commit, not the source commit.

That context for this is that I want the Cypress check to fail, not the azure pipeline.

**Comment by jennifer-shehane** [comment] 2020-02-24 05:41
We recently fixed the situation where GitHub status checks would not trigger for CI providers that utilize "Pull Requests builds". Pull request builds are generated by the CI provider (if configured) by merging the head branch with the base branch specified in the pull request. These are helpful in answering the question “What if this PR merged into target (base) branch”. You'll often see the commit message for the associated build look something like "Merge 2f5a7afe97740f99f5c4f5e40a3d7347bc058b30 into 1f40d78961e5d268ac072dca86176f9fb2aa7b13".
​
These types of builds will now trigger Cypress's GitHub status checks, designating these with a `(merge)` note on the status check message like shown below. The image below shows a typical status check on push and a 'Pull Request build' status check (showing the merge note).
​
​
<img width="678" alt="Screen Shot 2020-02-24 at 11 45 07 AM" src="https://user-images.githubusercontent.com/1271364/75130860-c8470180-56fe-11ea-84b8-3dd28a9ef8c5.png">

​
​Additionally, if you have both 'Push' and 'Pull Request' builds on for your PRs (aka your CI provider creates 2 builds on each commit), you will see 2 comments made to the PR (if enabled) since there are 2 runs associated with the PR. 
​
​Please comment within this issue if this is not resolved and we will consider reopening.

**Closed by jennifer-shehane** 2020-02-24 05:41 UTC
Labels: CI: azure, external: api, pkg/server, stage: needs information, type: bug

**Comment by a-b-r-o-w-n** [comment] 2020-02-26 00:30
@jennifer-shehane how do I get this change? Do I need to update anything?

**Comment by jennifer-shehane** [comment] 2020-02-27 09:59
@a-b-r-o-w-n It should just work. It does not require an update to the Cypress package.

Please let me know if you're issue is not resolved, so we can investigate further and reopen this issue.

**Comment by a-b-r-o-w-n** [comment] 2020-02-27 16:02
Great thanks!
