### ISSUE TITLE
Test Failing because of the Uncaught exception on cy.visit 

### ISSUE THREAD

**Issue by Tchougbe** [cypress-io/cypress#15906] opened 2021-04-09 14:51 UTC
### Current behavior
Hi,

My test fails because of the Uncaught type error when I execute cy.visit() on our website  https://rutabago.com/ . 
I have used
```
Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  })
```
### Desired behavior

I want to load homepage and go through the website. 

### Test code to reproduce
describe('My First Test', () => {  
      
    it('finds the content "je demarre"', () => {
      cy.on('uncaught:exception', (err, runnable) => {
              return false
      })
    
      cy.visit('https://rutabago.com');
        //  cy.contains('Je démarre');
    })
})

**Comment by bahmutov** [comment] 2021-04-09 16:07
Can I ask what is not working? Using your test and Cypress v7 I can see the page loads and the test passes - yes, there are uncaught exceptions from the app, but you are ignoring them. 

<img width="1279" alt="Screen Shot 2021-04-09 at 12 07 16 PM" src="https://user-images.githubusercontent.com/2212006/114208995-21d2b580-992c-11eb-8c62-e8729ee51c0e.png">

**Comment by Tchougbe** [comment] 2021-04-09 16:48
Thanks for your reply . It doesn't work from me , here it what i get :

<img width="918" alt="Capture d’écran 2021-04-09 184526" src="https://user-images.githubusercontent.com/32594454/114213969-02577f00-9964-11eb-8ae6-d8881a5c6d8c.png">

I try to find an element after cy.visit() , and i never get to this step . 
Maybe some cache to clear ?

**Comment by bahmutov** [comment] 2021-04-09 16:57
Hmm I cannot recreate the error - tried Chrome 89 browser, same result for me, the test passes. Are you sure this is your test code?

```js
it('finds the content "je demarre"', () => {
  cy.on('uncaught:exception', (err, runnable) => {
          return false
  })

  cy.visit('https://rutabago.com');
    //  cy.contains('Je démarre');
})

```

**Comment by Tchougbe** [comment] 2021-04-09 18:48
Yes , i just tried again . 
Here is the project https://github.com/Tchougbe/ruta-e2e.git , I will ask a colleague to test this on his side as well.

**Comment by kpittman-securus** [comment] 2021-04-09 20:34
I am experiencing a similar regression, we have an automated upgrade trying to bump from Cypress 6.5 to 7.0.1, and one of our tests is stopped in its tracks by an uncaught application error. The application error has existed this whole time, and it's not a bug. Test ran fine in v6.5, will not run in 7.0.1 without `Cypress.on('uncaught:exception', ...);`

**Comment by sainthkh** [comment] 2021-04-15 01:55
It might be happening because of the error on the site: "Uncaught TypeError: Cannot set property 'status' of undefined". Can you come back to this issue after solving that one?

**Comment by jennifer-shehane** [comment] 2021-06-11 17:32
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2021-06-11 17:32 UTC
Labels: stage: awaiting response
