### ISSUE TITLE
Axios not starting request since 3.3.0

### ISSUE THREAD

**Issue by skjnldsv** [cypress-io/cypress#4252] opened 2019-05-20 08:35 UTC
Has anything changed that can impact this on 3.3.0?
I checked the changelog, but cannot find anything related. I'm no expert though :)

Changing browser (chromium, electron...) does not fix this.

### Current behavior:
- On large files (it seems to be the pattern here), axios request does not even starts
![Capture d’écran_2019-05-20_10-28-39](https://user-images.githubusercontent.com/14975046/58007649-04539300-7aeb-11e9-833e-721ac8403caa.png)
![Capture d’écran_2019-05-20_10-29-01](https://user-images.githubusercontent.com/14975046/58007650-04539300-7aeb-11e9-8939-ffb25769a138.png)

### Desired behavior:
- axios request starts as it used ot be

### Steps to reproduce: (app code and test code)
Command is working fine on 3.2.0
All [tests are passing](https://cloud.drone.io/nextcloud/viewer/62) and upload properly.

```js
Cypress.Commands.add('uploadFile', (fileName, mimeType) => {
	cy.fixture(fileName, 'base64')
		.then(Cypress.Blob.base64StringToBlob)
		.then(blob => {
			const file = new File([blob], fileName, { type: mimeType })
			const url = `${Cypress.env('baseUrl')}/remote.php/webdav/${fileName}`
			return cy.window().then({ timeout: 10000 }, window => {
				return axios.put(url, file, {
					headers: {
						requesttoken: window.OC.requestToken,
						'Content-Type': mimeType
					}
				}).then(response => {
					expect(response.status).to.eq(201)
					cy.log(`Uploaded ${fileName}`, response.status)
				})
			})
		})
})
```

### Versions

3.2.0
Linux
CI: Drone.io

**Comment by jennifer-shehane** [comment] 2019-05-20 09:07
Thanks for opening! Will close as duplicate of https://github.com/cypress-io/cypress/issues/4253 to keep the discussion in one place.

**Closed by jennifer-shehane** 2019-05-20 09:07 UTC

**Comment by skjnldsv** [comment] 2019-05-20 09:08
Awesome thanks @jennifer-shehane :)

**Comment by skjnldsv** [comment] 2019-05-20 10:05
@jennifer-shehane 
To reproduce:
1. clone https://github.com/nextcloud/viewer/
2. checkout the 3.3.0 branch `dependabot/npm_and_yarn/cypress-3.3.0`
3. npm install
4. start the server `./cypress/start.sh
   (it just copy the app into the nextcloud container, set some default config and run in background on port 8000)
5. run test `cypress run --spec cypress/integration/video.mp4.spec.js`
