### ISSUE TITLE
Cypress verify does not work on ubuntu server 20.10 raspberry PI 3

### ISSUE THREAD

**Issue by betmakh** [cypress-io/cypress#9560] opened 2020-12-08 11:15 UTC
### Current behavior

Cypress is failing to start witht the following error during verify process:
```
  ✖  Verifying Cypress can run /home/ubuntu/.cache/Cypress/6.0.1/Cypress
    → Cypress Version: 6.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/home/ubuntu/.cache/Cypress/6.0.1/Cypress/Cypress: 1: Syntax error: ")" unexpected

----------

Platform: linux (Ubuntu - 20.10)
Cypress Version: 6.0.1
```

### Desired behavior
I would expect cypress to be able to start

### Test code to reproduce
`npx cypress install &&
npx cypress verify`

### Versions

node: v12.18.2
npm: 6.14.8
os: Ubutntu Server 20.10 (arm64)
cypress: 6.0.1
device: raspberry pi 3

**Comment by jennifer-shehane** [comment] 2020-12-08 12:56
What's your use case for needing to install Cypress on Raspberry Pi?

**Comment by betmakh** [comment] 2020-12-08 15:34
@jennifer-shehane it's just a little project of my own: I want to monitor the availability of some products, such as PS5. And cypress just seems a good way to do this. 
However, if cypress does not work with raspberry I can look for another tooling

**Comment by jennifer-shehane** [comment] 2020-12-09 07:31
Yah, I'm guessing it does not work on Raspberry Pi. Close as duplicate of #9317 which will become an issue for Raspberry Pi support.

**Closed by jennifer-shehane** 2020-12-09 07:31 UTC
