### ISSUE TITLE
Could not trigger opening file upload dialog box

### ISSUE THREAD

**Issue by diana-RC** [cypress-io/cypress#7333] opened 2020-05-13 16:18 UTC
### Current behavior:

When I click a Browse button , it is not opening the Chrome file upload dialog box.

```js
cy.visit('/application')
cy.get('button[type=button]').click()
```

![image](https://user-images.githubusercontent.com/55460938/81834537-f6d3bc00-9538-11ea-8253-646e4125c397.png)
     

### Desired behavior:

 When the browse button is clicked it should open the file upload dialog box but it is not happening
![image](https://user-images.githubusercontent.com/55460938/81834696-34384980-9539-11ea-8403-c05d6f9b99ac.png)

Hi,
I want to just open the file upload dialog box. Please advice. Thanks in advance

**Comment by jennifer-shehane** [comment] 2020-05-14 07:12
Cypress doesn't fully support file upload. See #170 for existing workarounds. 

Duplicate of #170

**Closed by jennifer-shehane** 2020-05-14 07:12 UTC
