### ISSUE TITLE
Upgrade to version 13.3.3 causes Cypress to crash in Angular

### ISSUE THREAD

**Issue by mattbodman** [cypress-io/cypress#28136] opened 2023-10-25 02:36 UTC
### Current behavior

Running previously working Angular component tests results in an error "Session with given id not found." and Cypress crashes.

Specifically, when clicking "Start component testing in Chrome", Cypress crashes.  Test with two different Angular applications.

`Session with given id not found.
Error: Session with given id not found.
    at <embedded>:2466:519827
    at _._handleMessage (<embedded>:2466:521860)
    at A.<anonymous> (<embedded>:2466:521673)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:506953)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:487328)
    at <embedded>:2466:486860
    at <embedded>:2466:478182
    at <embedded>:2466:479134
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.<anonymous> (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
`

### Desired behavior

Cypress shouldn't crash.

### Test code to reproduce

https://github.com/mattbodman/cypress-test.git

1. clone repo
2. run `cypress open`
3. choose component testing
4. choose "start component testing in Chrome"
5. observe command line

### Cypress Version

13.3.3

### Node version

18.18.0

### Operating System

Windows 10 Ent

**Comment by OleksiiKachan** [comment] 2023-10-25 15:11
not just angular. I have same thing with react after upgrading to 13.3.3. worked fine on 13.3.2

**Comment by atmullan** [comment] 2023-10-25 15:24
Same for me with E2E Tests on react using Chrome, works ok if Electron is selected

**Comment by asset-web** [comment] 2023-10-25 16:12
I am also seeing the same error inconsistently on E2E tests using Chrome and with Electron using the docker version of `cypress/included:13.3.3`.  So far I have not been able to trigger this using Firefox for the same the same test suite.

```Session with given id not found.
Error: Session with given id not found.
    at <embedded>:2466:519827
    at _._handleMessage (<embedded>:2466:521860)
    at A.<anonymous> (<embedded>:2466:521673)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:506953)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:487328)
    at <embedded>:2466:486860
    at <embedded>:2466:478182
    at <embedded>:2466:479134
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.<anonymous> (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)```

```
  Cypress:        13.3.3
  Browser:        Chrome 118 (headless)
  Node Version:   v20.9.0 (/usr/local/bin/node)
```

**Comment by OleksiiKachan** [comment] 2023-10-25 17:01
interesting thing it works in ci for me (we use circleci), but fails when I run locally 🤔

**Comment by joshmccall221** [comment] 2023-10-25 18:56
For me it looks like it is a chrome issue. Edge seems to work just fine.

**Comment by CaiqueCoelho** [comment] 2023-10-25 19:05
I'm having the same problem, with Electron everything works fine

**Comment by joshmccall221** [comment] 2023-10-25 20:46
Looks like it's a chrome issue for me, edge works fine.

**Comment by Michael-Ludgate** [comment] 2023-10-26 08:09
Same issue for me, OP's repo but with **e2e tests using Edge** (workaround rolling back from Cypress 13.3.3).

**Comment by jfarris587** [comment] 2023-10-26 18:33
I see this same error occurring as well. it randomly started the last day, however, we are on 12.6.0, so unsure if it is in fact related to v13 upgrades.

unlike @OleksiiKachan, we see it failing in github-actions, but passing locally

**Comment by MikeMcC399** [comment] 2023-10-27 14:38
- It looks like this issue is the same as https://github.com/cypress-io/cypress/issues/28148, in which case the [comment ](https://github.com/cypress-io/cypress/issues/28148#issuecomment-1782976765) from @ryanthemanuel would apply, that the issue is fixed in PR https://github.com/cypress-io/cypress/pull/28147.

**Comment by ZipingL** [comment] 2023-10-27 18:30
I can confirm through metrics show on my CD status badges, that I had this issue, and after downgrading to `cypress@13.3.2` I no longer had this issue.

<table>
 <thead>
   <tr>
    <td>
     <a   href="https://github.com/ZIPING-LIU-CORPORATION/react-adobe-embed-cd-canary/blob/main/cypress.config.ts">Canary Heartbeat CD Enabler</a>
    </td>
    <td>
     <a href="https://github.com/ZIPING-LIU-CORPORATION/react-adobe-embed/blob/slave/src/__tests__/base.test.tsx">Integrated Unit Test</a>
    </td>
    <td>
      <a href="http://www.wakatime.com/@aws">Development Coding Effort</a>
    </td>
   </tr>
 </thead>
  <tr>
   <td>
  <a href="https://cloud.cypress.io/projects/izghdg/runs">  <img title="Canary heartbeat status check for deployed latest component and adobe pdf api availability" src="https://img.shields.io/endpoint?url=https://cloud.cypress.io/badge/detailed/izghdg/main&style=flat-square&logo=cypress"/> </a>
   </td>
    <td>
     <img src="https://github.com/ZIPING-LIU-CORPORATION/react-adobe-embed/actions/workflows/main.yml/badge.svg"/>
    </td>
        <td>
     <a href="https://wakatime.com/badge/user/e012350f-8b4a-4ec4-ae89-56e558bfec5d/project/91c0617a-04ed-419d-9221-d5086d1bfbf6"> <img src="https://wakatime.com/badge/user/e012350f-8b4a-4ec4-ae89-56e558bfec5d/project/91c0617a-04ed-419d-9221-d5086d1bfbf6.svg"/> </a>
    </td>
  </tr>
</table>

I just would like to take this time to encourage the cypress team to utilize continuous deployment and best practices for 
code deployments, especially for code that functions as a framework intended  to facilitate continuous deployment/...

You should probably use another form of UI testing framework, such as [@AWS CloudWatch Synthetics](https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/Welcome.html) given the notable lack of a internal  ui testing framework  being used that isn't related to the product offered. [Thank you](https://github.com/ZIPING-LIU-CORPORATION/react-adobe-embed-cd-canary)

<blockquote>
<p>
 In light of such prevailing conditions, I find the forceful notifications and subsequent suspensions of Cypress account access, due to surpassing the complimentary quota in 'Cypress cloud usages,' to be an overly aggressive method of underscoring the requirement to transition to the paid versions of Cypress. This tactic is unpalatable, especially given the inherent instability of the service. Furthermore, I am compelled to express my disapproval and disappointment concerning the unprofessional and discourteous treatment of users, who are integral to the development process and serve as 'test users.' The sole motivation for my financial investment in a program or API is the convenience of not having to code it myself.For instance, in the realm of video games, I am willing to invest financially because they generally function seamlessly, sparing me the need to comprehend the intricate programming aspects.<br/>
</p> <br/>
<blockquote><br/>I  concur with your sentiment, @jfarris587, as this is undoubtedly an unfavorable statement that carries a negative connotation. However, I must inquire, is it justifiable to be confronted with a $75 monthly fee after surpassing the free quota in the @cypress-github-team-services-sa cloud, especially considering the current issues that question the stability of the product? I am merely playing the role of a devil's advocate in this scenario.
</blockquote>
<blockquote>

**Comment by ragi96** [comment] 2023-10-31 09:18
FYI: in my case its fixed with `13.4.0`, see [changelog](https://docs.cypress.io/guides/references/changelog#13-4-0)

**Comment by MikeMcC399** [comment] 2023-10-31 10:33
@mattbodman 

Could you try with [cypress@13.4.0](https://docs.cypress.io/guides/references/changelog#13-4-0)?

I wasn't able to reproduce from your repo and it seems that the issue can show up randomly. That is probably the reason also that various people thought it was linked to a certain browser - which was probably more coincidence than anything else.

It would be great anyway if you could check whether the latest release (`13.4.0`) resolves it for you.

**Comment by asset-web** [comment] 2023-10-31 11:28
Works for me @MikeMcC399

**Comment by OleksiiKachan** [comment] 2023-10-31 14:11
resolved in v13.4.0 for us

**Comment by mattbodman** [comment] 2023-10-31 23:05
@MikeMcC399 

Confirmed it is working on my test repo and production repo with 13.4.0.  Thanks team!

**Comment by MikeMcC399** [comment] 2023-11-01 16:19
@mattbodman 

It's great to hear that you are up-and-running again! 👍🏻 
Would you like to close this issue now in that case?
⬇️ for Close button.

**Closed as completed** 2023-11-01 21:34 UTC
