### ISSUE TITLE
EPROTO Error

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1459] opened 2018-03-14 16:53 UTC
- Operating System: Windows 10 64bits
- Cypress Version: 2.0.4
- Browser Version: Version 64.0.3282.167 (Official Build) (64-bit)

I would like to use  cypress.io with a corporate proxy. I don't know if something must be configured in Cypress.io (on the client)  in adding with a configuration on the corporate proxy.

When I use cy.visit(), I get this error:

> CypressError: cy.visit() failed trying to load:
> 
> https://----/gateway/mesure/
> 
> We attempted to make an http request to this URL but the request failed without a response.
> 
> We received this error at the network level:
> 
>   > Error: write EPROTO 101057795:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:1494:SSL alert number 40
> 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:659:
> 
> Common situations why this would fail:
>   - you don't have internet access
>   - you forgot to run / boot your web server
>   - your web server isn't accessible
>   - you have weird network configuration settings on your computer
> 
> The stack trace for this error is:
> 
> Error: write EPROTO 101057795:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:1494:SSL alert number 40
> 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:659:
> 
>     at exports._errnoException (util.js:1024:11)
>     at WriteWrap.afterWrite (net.js:851:14)

Thanks for your helping

**Comment by jennifer-shehane** [comment] 2018-03-16 16:19
We're aware of issues with visiting under a corporate proxy and have listed some workarounds here: https://github.com/cypress-io/cypress/issues/1469 But there is no permanent fix. Closing this issue as duplicate of: https://github.com/cypress-io/cypress/issues/672

**Closed by jennifer-shehane** 2018-03-16 16:19 UTC

**Comment by VinothArasu** [comment] 2020-06-16 06:45
HI, I'm too facing similar kind of issue, While i try to access my corporate application. 
![cypressIssue](https://user-images.githubusercontent.com/53971556/84740419-fb254600-afca-11ea-87ca-17b2bcc90848.png)

please help us to resolve this issue !!

**Comment by VinothArasu** [comment] 2020-06-16 06:49
i have set the proxy based on my corporate account.
![image](https://user-images.githubusercontent.com/53971556/84740789-a7ffc300-afcb-11ea-9964-7952afad2131.png)

**Comment by flotwig** [comment] 2020-06-16 13:34
@VinothArasu please open a new issue, this one is closed and is no longer being tracked
