### ISSUE TITLE
Can't acces run overview page

### ISSUE THREAD

**Issue by MailysC** [cypress-io/cypress#17505] opened 2021-07-28 16:46 UTC
### Current behavior

I have launched a run and wanted to overview it in the dashboard (https://dashboard.cypress.io/projects/pqi8ff/runs/2/overview).
However I have a glimpse for a few seconds of the page and then it goes blank.

I'm using :
Linux ubuntu
Firefox 68

https://user-images.githubusercontent.com/22365380/127363210-17b9dd9d-85ee-463d-9cec-8fcf62e10a26.mp4

Console error :
ReferenceError: "ResizeObserver is not defined"

### Desired behavior

I should be able to see the overview of my run

### Cypress Version

6.8.0

**Comment by MailysC** [comment] 2021-07-28 16:59
Update :

It works fine with Chrome however if there is a way to make it run with Firefox I'd prefer that

**Comment by jennifer-shehane** [comment] 2021-07-28 20:36
Is this still occurring for you? I can't seem to recreate it, so am wondering if it's something about this specific state in this specific browser is causing this. Can I ask what version of Firefox are you running?

**Comment by MailysC** [comment] 2021-07-29 07:40
Hi yes I still got this problem with Firefox (but not with google).

I'm using Firefox Quantum 68

**Comment by cy-veronica** [comment] 2021-09-15 17:44
Filed for services team.

**Comment by benpatterson** [comment] 2023-04-26 21:49
I'm reviewing some tickets and I'm unable to reproduce this issue across various browsers, including firefox. Closing this ticket, but feel free to let us know if it surfaces again.

**Closed by benpatterson** 2023-04-26 21:49 UTC
Labels: external: cloud, stage: investigating
