### ISSUE TITLE
Cypress: 3.0.2   failed to start on Windows

### ISSUE THREAD

**Issue by petertsu** [cypress-io/cypress#2086] opened 2018-07-02 16:45 UTC
C:\Users\Administrator>cypress run
It looks like this is your first time using Cypress: 3.0.2

 ×  Verifying Cypress can run C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress
   → Cypress Version: 3.0.2
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

Command failed: C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=924

Platform: win32 (10.0.14393)
Cypress Version: 3.0.2

**Comment by petertsu** [comment] 2018-07-02 16:52
C:\Users\Administrator>cypress verify
  cypress:cli cli starts with arguments ["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cypress\\bin\\cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +7ms
  cypress:cli parsed cli options {} +4ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +2ms
  cypress:cli checking if executable exists C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe +5ms
  cypress:cli Binary is executable? : true +4ms
  cypress:cli binaryDir is  C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress +0ms
  cypress:cli Reading binary package.json from: C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 3.0.2 installed in: C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress +5ms
  cypress:cli could not read binary_state.json file +6ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +3ms
  cypress:cli force verify +4ms
  cypress:cli running binary verification check 3.0.2 +0ms
It looks like this is your first time using Cypress: 3.0.2

  cypress:cli clearing out the verified version +7ms
  cypress:cli running smoke test +2ms
  cypress:cli using Cypress executable C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe +1ms
  cypress:cli needs XVFB? false +1ms
  cypress:cli smoke test command: C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=755 +0ms
 \  Verifying Cypress can run C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress
  cypress:cli Smoke test failed: { Error: Command failed: C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=755



    at makeError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cypress\node_modules\execa\index.js:172:9)
    at Promise.all.then.arr (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cypress\node_modules\execa\index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 3221225477,
  stdout: '\r\n',
  stderr: '',
  failed: true,
  signal: null,
  cmd:
   'C:\\Users\\Administrator\\AppData\\Local\\Cypress\\Cache\\3.0.2\\Cypress\\Cypress.exe --smoke-test --ping=755',
  timedOut: false,
 ×  Verifying Cypress can run C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress
   → Cypress Version: 3.0.2
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: C:\Users\Administrator\AppData\Local\Cypress\Cache\3.0.2\Cypress\Cypress.exe --smoke-test --ping=755
----------

Platform: win32 (10.0.14393)
Cypress Version: 3.0.2

C:\Users\Administrator>

**Comment by brian-mann** [comment] 2018-07-02 16:56
Duplicate of https://github.com/cypress-io/cypress/issues/1866#issuecomment-401725706

Will close, but please follow the other issue. Thank you for providing what you've written. It appears there is more information from Electron regarding this here: https://github.com/electron/electron/issues/3570

**Closed by brian-mann** 2018-07-02 16:56 UTC
