### ISSUE TITLE
Incorporate File Uploads

### ISSUE THREAD

**Issue by MuckT** [cypress-io/cypress#15236] opened 2021-02-25 23:24 UTC
### Incorporate File Uploads
File uploads should be supported out of the box in Cypress.

### Why is this needed?
Currently [cypress-file-upload](https://www.npmjs.com/package/cypress-file-upload) is averaging around .42 million downloads a week; this feature request is one that many in the Cypress community would benefit from. Based on what I am seeing from [npmjs.com](https://www.npmjs.com/) about 20% of Cypress users are using this plugin.

**Comment by jennifer-shehane** [comment] 2021-02-26 13:40
Duplicate of https://github.com/cypress-io/cypress/issues/170

**Closed by jennifer-shehane** 2021-02-26 13:40 UTC
