### ISSUE TITLE
I'm unable to run cypress after 3.0.0 update

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#1821] opened 2018-05-30 10:49 UTC
### Is this a Feature or Bug?

BUG

### Current behavior:

When i'm running cypress from terminal i'm getting error.

### Steps to reproduce:
cypress open

TypeError: tty.getWindowSize is not a function
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\base.js:120:13)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\base.js:489:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\index.js:3:31)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\index.js:21:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:13:17)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:504:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\index.js:3:5)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\index.js:5:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\reporter.js:11:11)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\reporter.js:402:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\reporter.js:404:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\project.js:49:14)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\project.js:654:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\project.js:656:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\gui\events.js:30:13)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\gui\events.js:247:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\gui\events.js:249:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\interactive.js:30:12)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\interactive.js:141:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\interactive.js:143:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\index.js:9:16)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:43:38
    at tryCatcher (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at Object.runElectron (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:40:28)
    at Object.startInMode (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:148:23)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:112:24
    at tryCatcher (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._settlePromise (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:580:21)
    at Promise._settlePromise0 (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:636:18)
    at PromiseArray._resolve (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:572:26)
    at Promise._settlePromise0 (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:636:18)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
    at xfs.stat (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)

TypeError: tty.getWindowSize is not a function
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\base.js:120:13)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\base.js:489:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\index.js:3:31)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\reporters\index.js:21:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:13:17)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:504:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\index.js:3:5)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\mocha\index.js:5:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\reporter.js:11:11)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\reporter.js:402:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\reporter.js:404:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\project.js:49:14)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\project.js:654:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\project.js:656:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\gui\events.js:30:13)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\gui\events.js:247:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\gui\events.js:249:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\interactive.js:30:12)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\interactive.js:141:4)
    at Object.<anonymous> (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\interactive.js:143:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\modes\index.js:9:16)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:43:38
    at tryCatcher (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at Object.runElectron (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:40:28)
    at Object.startInMode (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:148:23)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\lib\cypress.js:112:24
    at tryCatcher (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._settlePromise (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:580:21)
    at Promise._settlePromise0 (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:636:18)
    at PromiseArray._resolve (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:572:26)
    at Promise._settlePromise0 (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:636:18)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
    at xfs.stat (C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\Zbyszek\AppData\Local\Cypress\Cache\3.0.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)

### Versions

Windows 10. Cypress 3.0.0

**Comment by simonhaenisch** [comment] 2018-05-30 11:18
duplicate of #1815

**Closed** 2018-05-30 14:06 UTC
Labels: type: duplicate

**Comment by jennifer-shehane** [comment] 2018-05-31 14:54
Fixed in [`3.0.1`](https://docs.cypress.io/guides/references/changelog.html#3-0-1).
