### ISSUE TITLE
Electron Browser can't able to recognize XHR request  

### ISSUE THREAD

**Issue by Prashant62** [cypress-io/cypress#5008] opened 2019-08-20 10:48 UTC
### Current behavior:

There is a test scenario where i need to enter some character on search box and then related search suggestions will come from search API.
what i found if i run tests on electron then after entering character, Search API has been not hitting while on chrome its hitting.

### Desired behavior:

There are 2 way by which we can fix them -

1. Making changes on electron so that it can hit search api after typing.
or 
2. Support of chrome on CLI mode. (This is kinda workaround)

### Steps to reproduce: (app code and test code)

1. Login 
2. Enter something existing on search Bar

Versions: 3.4.1
Electron : 61
O.S : Windows 10

Real response in Browser (We can see Search API is getting hit)
![Screenshot (219)](https://user-images.githubusercontent.com/54312612/63341807-af345100-c367-11e9-8435-3a32153c4b1f.png)

Response in cypress (Electron)
![Screenshot (214)](https://user-images.githubusercontent.com/54312612/63341986-05a18f80-c368-11e9-8777-8726319410b5.png)

**Comment by mpahuja** [comment] 2019-08-30 08:40
you may have a larger throttle set for search to call the api for each character type. You can probably verify that by adding a cy.wait() after a character type and then run a test. Obviously better would be to be able to see in the application code if there is throttle for search queries. 

The other possibility is that you might be using a specific type of web component that may not work exactly same between chrome and electron.

**Comment by jennifer-shehane** [comment] 2020-01-07 08:41
Chrome is support by passing the `--browser chrome` during `cypress run`. Chrome headless is also supported. Electron has also been upgrading since this was opened to use Chromium 78. 

Overall we have to close this issue as there is not enough information to reproduce the problem though.

Try updating to the [current version of Cypress](https://on.cypress.io/changelog) and see if this is still happening for you.

**Closed by jennifer-shehane** 2020-01-07 08:41 UTC
