### ISSUE TITLE
Fails on fresh Laravel installation

### ISSUE THREAD

**Issue by damms005** [cypress-io/cypress#26819] opened 2023-05-21 21:48 UTC
### Current behavior

When you install a new version of Laravel
```
composer create-project laravel/laravel example-app
```

Then, install Cypress and run 
```
npx cypress open
```

Errors out-of-the-box
![image](https://github.com/cypress-io/cypress/assets/9839355/bb490c9d-80e9-41bf-bd2b-17a9016fcc94)

This is very likely to be related to #26729

### Desired behavior

On a fresh installation of Laravel, Cypress should work out of the box. To reiterate, it seems related to #26729

### Test code to reproduce

```
composer create-project laravel/laravel example-app
```

Install Cypress and run 
```
npx cypress open
```

![image](https://github.com/cypress-io/cypress/assets/9839355/bb490c9d-80e9-41bf-bd2b-17a9016fcc94)

### Cypress Version

12.12.0

### Node version

v18.9.0

### Operating System

Ubuntu 20.04

**Comment by mike-plummer** [comment] 2023-06-27 18:13
@damms005 I'm not able to reproduce your problem. Here's the procedure I followed, maybe I'm missing a step?

1. Installed composer (Mac) - `brew install composer`
2. `composer create-project laravel/laravel 26819`
3. `cd 26819`
4. `npm i -D cypress`
5. `npx cypress open`
6. Followed in-app prompts to initialize new project with E2E testing config
7. Successfully launches Cypress runner UI

I have seen the error you're showing before, but typically it's caused by using an old Cypress config in a modern project that enables ESM via the `"type": "module"` field in `package.json`. Are you perhaps copying a Cypress config file from elsewhere, or reusing an old one? We have [dedicated logic](https://github.com/cypress-io/cypress/blob/develop/packages/config/src/ast-utils/addToCypressConfig.ts#L160) that attempts to autogenerate a CommonJS- or ESM-compliant config file on first launch which makes me wonder how you ended up with a config file that references `require` when the `package.json` for a Laravel project is created with ESM enabled.

**Comment by damms005** [comment] 2023-06-27 18:39
@mike-plummer Please confirm you're using same version of packages and tools

**Comment by jennifer-shehane** [comment] 2023-12-17 18:39
Closing since we’ve been unable to reproduce.

**Closed as not planned by jennifer-shehane** 2023-12-17 18:39 UTC
