### ISSUE TITLE
Can't fake webcam video 

### ISSUE THREAD

**Issue by alecmestroni** [cypress-io/cypress#24182] opened 2022-10-10 09:55 UTC
### Current behavior

When the test is running I'm having this issue
![image](https://user-images.githubusercontent.com/62354989/194839373-9acf6e03-9af3-43a8-89f3-4d6db72312df.png)
but if I open a new tab in cypress with the same link it's working fine 
![image](https://user-images.githubusercontent.com/62354989/194840910-082936f5-c2e8-49ea-9a5d-77a37c58fdb4.png)

I tried adding this code:
			
			on('before:browser:launch', (browser, launchOptions) => {
				launchOptions.args.push('--use-fake-device-for-media-stream')
				launchOptions.args.push('--use-fake-ui-for-media-stream')
				return launchOptions
			})
Nothing changed

Note :
I have followed following issue
https://github.com/cypress-io/cypress/issues/16637
https://github.com/cypress-io/cypress/issues/2704
https://github.com/cypress-io/cypress/issues/9562

### Desired behavior

Cypress should work in both situations

### Test code to reproduce

Code:

	it('Visit MoCa', () => {
		cy.visit(
			'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=PN0OoeMkEz9ArQGb6L17',
			{ failOnStatusCode: false }
		)
	})

	it('Take Photos', () => {
		cy.get('ion-button[data-cy="take-photo"]').each(el => {
			cy.wrap(el).click()
			cy.pause()
		})
	})

### Cypress Version

v10.9

### Node version

v16.15.1

### Operating System

Win 10, 19044.1620

**Comment by warrensplayer** [comment] 2022-10-13 21:00
@alecmestroni I was able to run your tests a couple of days ago when the URL you reference was still working.  It is now down, so I am no longer able to run the tests.  When I ran the tests on a Mac, I was able to see the fake webcam video without having to add any additional parameters.  I was going to try against a Windows virtual machine to see if running on Windows was the issue.  

Are you able to stand that website back up or else create a [Short, Self Contained, Correct, Example](http://sscce.org/) for me to test against?

**Comment by alecmestroni** [comment] 2022-10-14 08:02
@warrensplayer here it is 
```
it('Visit MoCa', () => {
	cy.visit(
		'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=q3jGE4mr86P1Jv9RXagY',
		{ failOnStatusCode: false }
	)
})

it('Take Photos', () => {
	cy.get('ion-button[data-cy="take-photo"]').each(el => {
		cy.wrap(el).click()
		cy.pause()
	})
})
```

**Comment by alecmestroni** [comment] 2022-10-17 16:05
@warrensplayer Some news?

**Comment by warrensplayer** [comment] 2022-10-18 16:23
@alecmestroni Thanks for the update.  I will take another look at this today.

**Comment by warrensplayer** [comment] 2022-10-19 14:46
@alecmestroni I have not been able to reproduce your issue. For me, it is showing the fake video on both Mac and Windows. Attached is the video from my Windows run using the `npx cypress run --e2e -b chrome` command that Cypress outputs to the `.\cypress\videos` directory in your project.   Can you confirm what version of Chrome you are using and can you share your `cypress.config.js` file?

Here is my modified test to click all the buttons on the page:
```
describe('webcam spec', () => {
  it('Visit MoCa', () => {
    cy.visit(
      'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=q3jGE4mr86P1Jv9RXagY',
      { failOnStatusCode: false }
    )
  })
  
  it('Take Photos', () => {
    cy.get('ion-button[data-cy="take-photo"]').each(el => {
      cy.wrap(el).click()
      cy.wait(500)
      cy.get('pwa-camera-modal-instance.hydrated').shadow().find('pwa-camera.hydrated').shadow().find('div.close').click()
    })
  })
})
```

https://user-images.githubusercontent.com/1702361/196724250-d68945da-a8b3-49a0-a74f-e83c6de601c6.mp4

**Comment by alecmestroni** [comment] 2022-10-20 08:09
I found the problem.. That is my baseUrl

```
e2e: {
		baseUrl: 'https://iqp.eu-west-1.tsaws.infocert.it/',
},
```

If I remove the base URL or change it with anotherone (could be fake and not reachable):
reachable
`  e2e: {
		baseUrl: 'https://github.com/cypress-io/cypress/issues/24182',
	},
`
unreachable
`  e2e: {
		baseUrl: 'https://test',
	},
`
 the webcam simulation works fine.
I need the baseUrl to be confingured for other tests, so i can't remove it
How to deal with it?

https://user-images.githubusercontent.com/62354989/196886506-505e2675-22fd-49ef-9d2f-aa96a7e9bce9.mp4

**Comment by alecmestroni** [comment] 2022-10-25 08:29
Some news? @warrensplayer

**Comment by warrensplayer** [comment] 2022-10-25 17:17
@alecmestroni Thanks for the feedback about the `baseUrl`.  We are continuing to look into a solution.

**Comment by amehta265** [comment] 2022-10-26 17:10
@alecmestroni Thank you for the information you have provided. I think the issue may stem from the fact that the `baseUrl` provided in the config file is being prepended to the url in the `cy.visit()` within your test files. This may be causing an incorrect url to be accessed leading to the inability to access the webcam. This is why removing the `baseUrl` from the cypress config file prevents this from happening.

Given that you need the `baseUrl` provided in the config file for other tests, maybe you can configure the `baseUrl` for the tests on the webcam so that they override the provided `baseUrl` in the config file. Your test would look something like this:
```
describe('webcam spec', { baseUrl: null } ,() => 
  it('Visit MoCa', () => {
    cy.visit(
      'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=q3jGE4mr86P1Jv9RXagY',
      { failOnStatusCode: false }
    )
  })
  
  it('Take Photos', () => {
    cy.get('ion-button[data-cy="take-photo"]').each(el => {
      cy.wrap(el).click()
      cy.wait(500)
      cy.get('pwa-camera-modal-instance.hydrated').shadow().find('pwa-camera.hydrated').shadow().find('div.close').click()
    })
  })
})
```

You can get more information about how to do this here: https://docs.cypress.io/guides/references/configuration#Test-Configuration

**Comment by alecmestroni** [comment] 2022-10-27 07:47
Hello @amehta265 thanks for your answer.
I have tried your solution, but this doesn't solve my issue... 
I tried also running it with the command line:
`npx cypress run --config baseUrl='' --headed -s 'cypress/e2e/cypress-issue.cy.js' `
neither this solved my problem..

**Comment by amehta265** [comment] 2022-10-28 21:24
@alecmestroni I am unable to run the test anymore as I am running into an `httpErrorResponse` "The address of the requested web page does not contain the correct parameters. Use the link received via SMS to launch the required evidence submission process correctly."

Could you kindly provided updated tests so I can replicate this once again on my end?

**Comment by alecmestroni** [comment] 2022-10-31 09:00
```
/// <reference types="cypress" />

describe('webcam spec', () => {
	it('Visit MoCa', () => {
		cy.visit(
			'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=q3jGE4mr86P1Jv9RXagY',
			{ failOnStatusCode: false }
		)
	})

	it('Take Photos', () => {
		cy.get('ion-button[data-cy="take-photo"]').each(el => {
			cy.wrap(el).click()
			cy.wait(500)
			cy.get('pwa-camera-modal-instance.hydrated')
				.shadow()
				.find('pwa-camera.hydrated')
				.shadow()
				.find('div.close')
				.click()
		})
	})
})

```
For me this is still working.
retry one more time @amehta265

**Comment by amehta265** [comment] 2022-10-31 16:13
@alecmestroni thank you for providing the updated tests.

```
describe('webcam spec', {baseUrl: 'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=q3jGE4mr86P1Jv9RXagY' } ,() => {
	it('Visit MoCa', () => {
		cy.visit('/',
			{ failOnStatusCode: false }
		)
	})

	it('Take Photos', () => {
		cy.get('ion-button[data-cy="take-photo"]').each(el => {
			cy.wrap(el).click()
			cy.wait(500)
			cy.get('pwa-camera-modal-instance.hydrated')
				.shadow()
				.find('pwa-camera.hydrated')
				.shadow()
				.find('div.close')
				.click()
		})
	})
})
```

The code attached above has been able to successfully override the `baseUrl` specified in the `cypress.config` file on my system. By introducing the options object and specifying a separate baseUrl for this test suite `{baseUrl: 'https://mobilecapture-test.infocert.it/home?companyId=Demo&dossierId=q3jGE4mr86P1Jv9RXagY' }` we ignore the `baseUrl` set in the config file.

If this does not work on your end, there may be something else missing other than the `baseUrl`. A reproducible example would be very handy in debugging this further as I will be able to dig into other possible configurations that may be mishandling your tests. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by alecmestroni** [comment] 2022-11-02 10:02
Neither this solution is working..
Hope with the reliable reproduction the proposed solution will be better next time..
https://github.com/alecmestroni/cypress-webcam

**Comment by amehta265** [comment] 2022-11-02 15:14
@alecmestroni  Thank you for providing a reproduction
I had a couple questions:
When running `cypress open` do you also receive the following error message as I receive in the reproduction before you run the e2e tests? 

![Image](https://user-images.githubusercontent.com/65267668/199520383-7f2665fa-4a50-478b-b4db-6331491baccd.png)

If you do, Cypress is giving you that error because at the time that Cypress starts, your application (`https://iqp.eu-west-1.tsaws.infocert.it/`) is not ready to start responding to requests. What I reckon is happening is that you may not be running your local environment before running cypress. Cypress can therefore not `.visit()` the correct website (`https://iqp.eu-west-1.tsaws.infocert.it/`) because it is not up and running. This may be because:

1.  You are not running your application from your local environment before running Cypress. Lets say that you are building an application that you serve locally e.g. you run `npm start` to serve your application on `localhost:3000`. You must serve your application by running `npm start` before you run `npx cypress open` on a different terminal. This way when the Cypress test tries to access `https://iqp.eu-west-1.tsaws.infocert.it/` it is able to do that as you are serving it on a local ip address.

2. You may have an incorrect configuration in your `etc/hosts` file.  Ideally, your system has been configured such that the domain name  in `https://iqp.eu-west-1.tsaws.infocert.it/` maps to a specific local ip-address in a file `etc/hosts`. This tells your computer that whenever you visit  `https://iqp.eu-west-1.tsaws.infocert.it/` it should open this website up on some local ip-address instead of trying to search up the domain on the internet. You can access your `etc/hosts` file by reading [this](https://www.nublue.co.uk/guides/edit-hosts-file/#:~:text=In%20Windows%2010%20the%20hosts,%5CDrivers%5Cetc%5Chosts.). Cypress allows you to configure your hosts in your configuration file like [this](https://cypresstips.substack.com/p/cypress-hosts-configuration) instead of editing the `etc/hosts` file every time during testing.

A quick fix would be to ensure that you run your application locally e.g. `npm start` before you test Cypress. Ensuring that the DNS settings are not misconfigured on your local system would also be great (as explained above)

For further debugging it would be helpful if you shared your `etc/hosts` file contents.

**Comment by alecmestroni** [comment] 2022-11-02 16:15
As I told in a message 13 days ago, my baseUrl is the problem.. 
So i tried different baseUrl:
_If I remove the base URL or change it with another one (could be fake and not reachable):
reachable
e2e: { baseUrl: 'https://learn.cypress.io/', },
unreachable
e2e: { baseUrl: 'https://test', },
the webcam simulation works fine.
I need my baseUrl to be configured for other tests, so I can't remove it or change it
How to deal with it?_
So the fact that my company internal baseUrl isnt reachable for you (you need our internal VPN to visit it) is not the problem..
Of course I'm not having this error message because I always activate my VPN before running the tests..
But this **SHOULD NOT** be a problem with the fakewebcam simulation..
Also baseUrl: 'https://test', is not rechable but the webcam is working fine.
Ignore that error and got to the test..

**Comment by amehta265** [comment] 2022-11-02 22:45
@alecmestroni I am once again getting this error accessing the url:

![Image](https://user-images.githubusercontent.com/65267668/199614889-c4e76eb9-63a5-442a-893f-50ba1ad09617.png)

**Comment by alecmestroni** [comment] 2022-11-03 08:54
> @alecmestroni I am once again getting this error accessing the url:
> 
> ![Image](https://user-images.githubusercontent.com/65267668/199614889-c4e76eb9-63a5-442a-893f-50ba1ad09617.png)

@amehta265 I fixed the link in the repo now should be up 24/24h.
Try again please

**Comment by amehta265** [comment] 2022-11-04 16:39
After discussion and guidance from @emilyrohrbough we have a work around:
```
describe('webcam spec',
() => {
	it('Throwaway', () => {
		cy.visit('www.google.com')
	})

	it('Take Photos', () => {
		cy.visit(
			'https://mobilecapture-stage.infocert.it/home?companyId=Demo&dossierId=lGj1aw8XrNa4k6M74YDq',
			{ failOnStatusCode: false }
		)
		cy.get('ion-button[data-cy="take-photo"]').each(el => {
			cy.wrap(el).click()
			cy.wait(500)
			cy.get('pwa-camera-modal-instance.hydrated')
				.shadow()
				.find('pwa-camera.hydrated')
				.shadow()
				.find('div.close')
				.click()
		})
	})
})
```
Seems like the issue was occurring because the top URL in the Cypress app was not being updated to `'https://mobilecapture-stage.infocert.it/home?companyId=Demo&dossierId=lGj1aw8XrNa4k6M74YDq'` during the tests and was remaining at `https://iqp.eu-west-1.tsaws.infocert.it/` because Cypress does not update the topURL when the `cy.visit()`occurs to a website that shares the same "super domain" as the `baseUrl` in the Cypress config e.g. in this case `infocert.it`

With the work around provided, "visiting" google.com forces a browser re-render because `'www.google.com'` and `'https://iqp.eu-west-1.tsaws.infocert.it/'` do not share the same domain names therefore updating the top Url to `'www.google.com'`. In the "Take Photos" test when you visit the mobile capture website, since it also does not share the same domain as your current top Url ('www.google.com') it was force another re-render which would then help pass your tests.

As mentioned this is just a temporary solution.
Kindly let me know if this works on your end.

**Comment by alecmestroni** [comment] 2022-11-04 16:53
The solution is working, on monday I'll update my tests.
For now, thanks for the solution (to u both)
Hope cypress will fix this bug in the next update!

**Comment by amehta265** [comment] 2022-11-04 17:59
I'm glad this is working on your end!

Closing as resolved.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by alecmestroni** [comment] 2022-12-14 09:41
Hello, i'm still getting the same error with firefox (and the solition proposed is not working).
The repo updated is the same
https://github.com/alecmestroni/cypress-webcam

**Comment by alecmestroni** [comment] 2022-12-14 09:42
Hello, @amehta265 & @emilyrohrbough
I'm still getting the same error with Firefox (and the solution proposed is not working).
The repo updated is the same
https://github.com/alecmestroni/cypress-webcam

**Comment by alecmestroni** [comment] 2022-12-19 08:26
Hello there, some news?

**Comment by mike-plummer** [comment] 2022-12-19 21:08
Hi @alecmestroni , it appears there is an [existing issue](https://github.com/cypress-io/cypress/issues/8849) open dealing with faked media streams in newer versions of Firefox - there are some fairly restrictive security policies (and additional preferences) that need to be worked around. [Here is a link to a user comment](https://github.com/cypress-io/cypress/issues/8849#issuecomment-789072605) that appears to have a workaround, hopefully that addresses your issue

**Comment by alecmestroni** [comment] 2022-12-27 06:13
Hello @mike-plummer & @lmiller1990  the workaround suggested isn't working in my case. 
I have also updated the repository with the code suggested:
```
	beforeEach(() => {
		cy.on('window:load', win => {
			win.parent.document
				.querySelector('.aut-iframe') // this selector is rather empirical
				.setAttribute('allow', 'camera;microphone')
		})
	})
```
U can check by yourself..

**Comment by lmiller1990** [comment] 2022-12-27 22:52
The way you do this is like the other comment suggest, using `launchOptions.args.push('--use-file-for-fake-video-capture=cypress/temp.y4m')`. This seems unsupported in Firefox right now. Similar issue in Playwright: https://github.com/microsoft/playwright/issues/4532

I don't think this is something that we can fix in Cypress (or any test runner). It is an upstream issue. Firefox would need to support loading a custom image or video, which they current don't.

The test works in Chrome on my machine. I also tried Firefox. In Firefox, you can still _open_ the webcam, it says "No image selected". I'd recommend asserting that modal is correctly opened and displayed for now. There is no work around or fix for something that's not supported in Firefox at this point in time.

I don't see anything actionable on our end. If it turns out Firefox does support a custom mock image/video, happy to reopen and take another look.

**Closed as completed by lmiller1990** 2022-12-27 22:52 UTC

**Comment by alecmestroni** [comment] 2023-08-28 08:42
Resolved in newest firefox version with
`Cypress.on('window:load', (win) => {
	win.parent.document
		.querySelector('.aut-iframe') // this selector is rather empirical
		.setAttribute('allow', 'camera;microphone')
})`
