### ISSUE TITLE
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds : V6.8.0

### ISSUE THREAD

**Issue by anushaengu** [cypress-io/cypress#15763] opened 2021-04-02 11:23 UTC
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 49676.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:49676
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

Cypress version used : 

Cypress package version: 6.8.0
Cypress binary version: 6.8.0
Electron version: 11.3.0
Bundled Node version: 12.18.3

on Mac system.

**Comment by lukeapage** [comment] 2021-04-06 17:26
Webpack version?

**Comment by sainthkh** [comment] 2021-04-30 01:33
Duplicate of #7766.

**Closed by sainthkh** 2021-04-30 01:33 UTC
