### ISSUE TITLE
Viewport issue of Cypress new version 9.0.0

### ISSUE THREAD

**Issue by Furong-Huang** [cypress-io/cypress#18878] opened 2021-11-11 03:09 UTC
### Current behavior

After updating new version 9.0.0 of cypress, I can't use cy.viewport to define the size of window to sign in website. Pls have a look about this issue. Thanks. It's very urgent that all the test casses failed due to signin failed. 
![image](https://user-images.githubusercontent.com/9040308/141228891-a5f0a948-cda6-4705-91d8-e32bf000c29a.png)

### Desired behavior

In this situation, Cypress should recognize the veiwpoint I defined and show the sign-in page properly.
![image](https://user-images.githubusercontent.com/9040308/141229077-91b02497-cdc9-48d2-bdd4-2798a63aafa6.png)

### Test code to reproduce

describe("Expense Claim Integration Tests", () => {

    it("1.Add flight item to expense claim", () => {
        cy.visit("https://cloud.zambion.com")
    })
})

### Cypress Version

9.0.0

**Comment by jennifer-shehane** [comment] 2021-11-11 10:44
Can you provide a fully reproducible example including exactly where in the tests the `cy.viewport` is being set? 

It’s not immediately obvious  in the 9.0 upgrade where this behavior would have changed and we need a reproducible example. Thanks!

**Comment by Furong-Huang** [comment] 2021-11-11 20:27
```
export function SignIn(view_width = 1280, view_height = 720) {
    cy.viewport(view_width, view_height)
    cy.visit("https://cloud.zambion.com"))
    cy.url().should("contain", "https://cloud.zambion.com")
    ClickButtonByText("Sign In")
}
```
```
 import { SignIn, CheckContains } from "../integration/helpers/general"
    describe("", () => {
        it("Restore database", () => {
            SignIn()
        })
    })
```
I have made a helper function which use cy.viewport to set view_width and view_height, then in the test case, I am calling this function to sign in website. Even though if you use cy.visit for website, it still can't show the SignIn page of website.
In other cypress old version, it doesn't happen this issue.

**Comment by BlueWinds** [comment] 2021-11-16 20:10
It seems to be working for me:

```
function SignIn(view_width = 1280, view_height = 720) {
    cy.viewport(view_width, view_height)
    cy.visit("https://cloud.zambion.com")
    cy.url().should("contain", "https://cloud.zambion.com")
    cy.get('.btn-signin-register').last().click()
}

it("Small", () => {
    SignIn(500, 500)
})

it("Big", () => {
    SignIn()
})
```

The small size shows an error, "Please expand your browser window and reduce your browser zoom as we are unable to run in your current window.", while the big one shows a registration page. I tested on both 8.7.0 and 9.0.0, they behaved the same.

![image](https://user-images.githubusercontent.com/3003404/142058233-4385dbe1-33c2-4d21-8c15-5f0ed805db0e.png)

Note that cloud.zambion.com does seem to be fairly slow at the moment, both in cypress and when visited externally - those three tests take a combined 35 seconds to run.

This doesn't mean the issue isn't real, just that I haven't figured out how to trigger it yet.

**Comment by Furong-Huang** [comment] 2021-11-17 03:45
Yeah, you're right. I still face the same issue when using 9.0.0. Still figure out the reason why will trigger this issue. That's weired.

**Comment by BlueWinds** [comment] 2021-11-17 17:15
I'm going to go ahead and close this issue, since I haven't been able to reproduce what you're running into. My first suggestion is to try increasing the timeouts around your login - the appearance of the login screen was very slow on the production site. In any case, it seems unrelated to setting the viewport size, as that looks to be working in all my tests.

If you do manage to isolate your issue down to something wrong with cypress, please comment here and I'll look at reopening.

**Closed by BlueWinds** 2021-11-17 17:15 UTC
Labels: stage: needs information
