### ISSUE TITLE
Temporarily escape from a cy.within()

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress#6666] opened 2020-03-06 15:39 UTC
### Current behavior:

`cy.within()` correctly scopes inner `cy.get()` and `cy.root()` calls.

### Desired behavior:

However, I sometimes need to temporarily escape from the `cy.within()` scope.

This is especially true for commands. I need a command that searches the whole `<body>` even when it is called from inside a `cy.within()`.

**Comment by jerguslejko** [comment] 2020-03-08 20:52
I'm in the same situation as OP.

**Comment by dressuncoded** [comment] 2020-08-07 19:26
Would also like this enhancement––when working with Vue.js, v-select components the select modal that lists options appears outside the scope of the form that the component is in.

**Comment by jennifer-shehane** [comment] 2020-11-19 06:20
You can do this today by using [`cy.wrap()`](https://on.cypress.io/wrap) to wrap an element found using [`Cypress.$()`](https://on.cypress.io/$) which will traverse the entire document (outside of the scope of the within). 

`index.html`

```html
<html>
<body>
  <div id="modal">
    <p>My Modal</p>
    <button>close</button>
  </div>
  <a href="" class="my-link">This anchor outside the modal</a>
</body>
</html>
```

`spec.js`

```js
it('get element outside of within', () => {
  cy.visit('index.html')
  cy.get('#modal').within(() => {
    // get element within modal
    cy.get('p').should('contain', 'My Modal')

    // cy.get('a').should('have.class', 'my-link') // won't work!
    // this anchor is outside of the modal!
    cy.wrap(Cypress.$('a')).should('have.class', 'my-link')

    // get element within modal
    cy.get('button').should('contain', 'close')
  })
})
```

<img width="825" alt="Screen Shot 2020-11-19 at 12 48 29 PM" src="https://user-images.githubusercontent.com/1271364/99628956-92546500-2a65-11eb-92e2-bdd556cfc8b7.png">

Closing as resolved with the above workaround. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-11-19 06:20 UTC
Labels: pkg/driver, stage: proposal 💡, type: enhancement

**Comment by DamienCassou** [comment] 2020-12-11 10:21
@jennifer-shehane thank you for your workaround but it only works if the DOM contains the element at the moment the promises are created: as said in [its documentation](https://docs.cypress.io/api/utilities/$.html#Syntax), `Cypress.$` is a "way to **synchronously** query for elements".

My test looks more like:

`index.html`:

```html
<html>
<body>
  <div id="modal">
    <p>My Modal</p>
    <button>close</button>
  </div>
</body>
</html>
```

`spec.js`:

```js
it('get element outside of within', () => {
  cy.visit('index.html')
  cy.get('#modal').within(() => {
    cy.get('button').click(); // the click should make a <a> tag appears in the DOM

    // FAILS because the <a> tag is only there after the button's click() has been executed
    // not  at the time `Cypress.$('a')` is evaluated:
    cy.wrap(Cypress.$('a')).should('have.class', 'my-link')
  })
})
```

**Comment by samueloakley** [comment] 2021-01-05 14:50
@DamienCassou It's a little hacky, but I got around a similar situation like this:
```
cy.wrap({}).should(() => {
  expect(Cypress.$('a')).to('have.class', 'my-link'));
});
```

`.should` will retry as usual until the assertion passes.

**Comment by doits** [comment] 2021-02-03 18:26
I think you can also do this to escape to the `body`:

```js
cy.wrap(Cypress.$("body")).within(() => {
  cy.get("a").should('have.class', 'my-link')
})
```

**Comment by IlCallo** [comment] 2021-03-31 11:17
Found this solution on [StackOverflow](https://stackoverflow.com/a/65932605/7931540), which seems cleaner

```ts
cy.document()
  .its('body')
  .within(() => {
    // Stuff into body scope
  })
```

@jennifer-shehane is there any drawback compared to the one you proposed?

**Comment by bvandrc** [comment] 2023-01-26 05:21
`cy.document().its('body')` didn't work for me for some reason, maybe due to retryability

Cypress 12 solution:

`Cypress.Commands.addQuery('escapeWithin', () => () => cy.$$('body'))`

`cy.escapeWithin().find('selector').should('do.things')`
