### ISSUE TITLE
Cypress V10 App shows spinning cursor on launch

### ISSUE THREAD

**Issue by bobgager** [cypress-io/cypress#22392] opened 2022-06-18 23:59 UTC
### Current behavior

V9 worked just fine.
Upgrade to v10 and when I launch Cypress, the app launches, but just shows the spinning Cypress logo forever.

### Desired behavior

I'd like it to launch so I can use it.

### Test code to reproduce

Just trying to launch the app with NPM on a Mac

### Cypress Version

10.1.0

### Other

NPM writes out some errors:

@ cypress:open /Users/bob/Google Drive/Cobalt Cloud/Developement/VSCprojects/Cypress/cypress
> cypress open

objc[2372]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4b6ce948) and /Users/bob/Library/Caches/Cypress/10.1.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x107cbd9c8). One of the two will be used. Which one is undefined.
/Users/bob/Library/Caches/Cypress/10.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:40
  invoke = (eventId, args = []) => {
         ^

SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/bob/Library/Caches/Cypress/10.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by lmiller1990** [comment] 2022-06-22 02:27
Hi! I think this is a duplicate of https://github.com/cypress-io/cypress/issues/22332.

Most likely you have an older version of Node.js installed (probably v10). When you launch the app directly, it's using the internally bundled Node.js version, but via npm, it's using your system node. What if you do `node --version`?

If you can upgrade your system Node.js to v12 or v14, it should be fine. [Docs on Node.js versions](https://docs.cypress.io/guides/references/migration-guide#Node-js-12-support).

**Closed by lmiller1990** 2022-06-22 02:27 UTC
