### ISSUE TITLE
Unable to type in an element having `display: none` in version 3.3.2

### ISSUE THREAD

**Issue by priyankaghosh1989** [cypress-io/cypress#4623] opened 2019-07-01 07:40 UTC
### Description:
Unable to type in an element having property `display: none` in version 3.3.2

### Note:
1. The same test was working perfectly with the version 3.3.1
2. The have tried this with `{force: true}` but its not able to save the value.
`cy.get('.mapping-name-editor > input').type('{selectall}ItemName{enter}', {force: true});`

![image](https://user-images.githubusercontent.com/45175962/60399952-56b5b400-9b6d-11e9-84c7-36c8d722da3b.png)

![image](https://user-images.githubusercontent.com/45175962/60418915-6de3b880-9be4-11e9-9bd7-80b7544f030b.png)

### Desired behavior:
It should be able to type the name and save it properly.

### Versions
3.3.2

**Comment by jennifer-shehane** [comment] 2019-07-01 09:16
When we perform `.type()` in Cypress, we click on the element as a user would. Any element with `display: none` is not clickable by a user, so this typing should fail. 

However, the input is able to be focused in other ways (aka - tabbing to the element). 

We fixed the behavior in version 3.3.2 so that you can now call `.focus()` on elements that were previously not clickable in order to type into them and correctly do not allow clicking into the input. 

Can you try the test code:

```js
cy.get('.mapping-name-editor > input').focus().type('{selectall}ItemName{enter}');
```

That being said, the `{force: true}` option should have worked I believe.

**Comment by priyankaghosh1989** [comment] 2019-07-03 07:45
@jennifer-shehane I tried with both `.focus()` and `{force: true}` In both the cases, it is able to type. But,
- According to our application when we hit enter in the input field, it should update the field in the database, and return 200 with PUT function. 
- But if I use `.focus()` and `{force: true}` as shown in the below function, the endpoint is not being called at all. 
```
changeMappingName(name) {
    cy.server();
    cy.get('.mapping-name-editor > input').type('{selectall}ItemName{enter}', {force: true});
    cy.route('PUT', /\/api\/projects\/709\/mappings\/[0-9]+/).as('apiCheck');
    cy.wait('@apiCheck', {timeout: 60000}).then((xhr) => {
      expect(xhr.status).to.eq(200)
    });
  };
```

**Note:** 
1. It was perfectly working in the version 3.3.1 without `.focus()` and `{force: true}`
2. Our application is in angular JS.

**Comment by jennifer-shehane** [comment] 2019-07-03 11:00
So, can you confirm that the typing of the text is working, but the implicit submission upon `{enter}` is not working? Because that would be a completely different cause if that is the case. 

Can you split up the commands for `.type('{selectall}ItemName')` and `.type('{enter}')` and confirm which command the `display: none` warning is happening?

Also, this isn't related to the issue, but I'm just a bit curious why you have `display: none` on an input where you presumably expect someone to type into and hit enter. You know they cannot click on your input? Would like to understand the real world use case for this.

**Comment by priyankaghosh1989** [comment] 2019-07-03 14:58
You are right @jennifer-shehane I tried the below code, and it typed correctly in the input field but failed in the `{enter}`. Screenshot attached.
`cy.get('.mapping-name-editor > input').focus().type('{selectall}' + name).type('{enter}');`

![image](https://user-images.githubusercontent.com/45175962/60602272-c6b57b80-9db3-11e9-862e-a8d27c6c1991.png)

**Comment by priyankaghosh1989** [comment] 2019-07-04 14:57
@jennifer-shehane Is there any idea why `{enter}` is not working properly. Or any workaround?

**Comment by jennifer-shehane** [comment] 2019-07-11 07:01
Can you try:

```js
cy.get('.mapping-name-editor > input').focus().type('{selectall}' + name)
cy.focused().type('{enter}');
```

Our support of typing into inputs that are not visible attempts to click on the input, but we recently added the ability to type into focused elements (as if the user had tabbed into it). So, it's not POSSIBLE, but the API is not ideal in my opinion. 

Also, could you update to Cypress 3.4.0? We recently fixed another issue with 'enter' on inputs in that release. Let us know if this doesn't work.

**Comment by priyankaghosh1989** [comment] 2019-07-18 12:30
@jennifer-shehane same issue with the below code 
```
cy.get('.mapping-name-editor > input').focus().type('{selectall}' + name)
cy.focused().type('{enter}');
```

Also I tried with 3.4.0 version.. no Luck :(

**Comment by jennifer-shehane** [comment] 2020-02-04 07:43
Please try updating to the [current version of Cypress](https://on.cypress.io/changelog). We made a lot of improvements with typing since this issue was opened. Your issue may have already been fixed. Unfortunately I can't verify if it is resolved as we were never provided a reproducible example. 

Closing as resolved. Please open a new issue with a reproducible example if you are experiencing an issue similar to this thread.

**Closed by jennifer-shehane** 2020-02-04 07:43 UTC
Labels: stage: awaiting response, topic: cy.type ⌨️

**Comment by Nutcracker52** [comment] 2022-06-10 08:45
Hi Jennifer,

I am experiencing something similar in Vue buefy Tabs. 
Buefy tab items has style display:none; but this is invalid for active tab and cypress failing to identify that and fail the test. 

Over here I am trying to click a button inside active tab which does not have active display:none; property. This value is not valid for active tab but cypress cannot identify it. 

![image](https://user-images.githubusercontent.com/65933656/173027423-cc9f0918-e85d-4eea-88ab-0e7cb781f221.png)

![image](https://user-images.githubusercontent.com/65933656/173027495-8898453e-f766-4e23-8264-4be77add91d7.png)

**Comment by luisadesouzamiranda** [comment] 2023-05-22 05:17
Hi All,
I have V10.11.0 here, and the same issue is still happening.
`.focus()` & `.type()` is still not working for me, to click on a hidden input.
<img width="308" alt="image" src="https://github.com/cypress-io/cypress/assets/53588533/c0160b41-616a-497f-b787-5b83d6a751b6">

**Comment by nagash77** [comment] 2023-05-22 13:43
@luisadesouzamiranda please open a new issue with a reproducible example using [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) and we will be happy to investigate.

**Comment by GeorgeBeres** [comment] 2024-04-19 19:04
Hi I do have the same issue when I'm trying to use a loop to go through a list of product in a table view by table row, how can I solve this issue?  It adds the first product in the basket but when the loop iterates again then I get the same error as above saying that the locator I have provided CSS property: display: none.

This is my code: 
```js
cy.get('.productList-block').find('tbody tr').each(($el, index, $list) => {
           const productText = $el.find('.productName').text()
           if(productText.includes('Cookie')) {
              cy.wrap(productText).get('.list-buttons').contains('Add').click({ force: true })
             
           }
     })
```

Also if I use click({ force: true }) then still adds only one product to my basket but finds the rest of the products which meet my if condition... again this is not the solution.
