### ISSUE TITLE
cy. Screenshot capturing improper screenshot some times

### ISSUE THREAD

**Issue by prashant-kashid** [cypress-io/cypress#27291] opened 2023-07-13 11:52 UTC
### Current behavior

cy. Screenshot capturing improper screenshot some times

Hi Team,
Below is my Setup

Node 16
Cypress 11.2  and 12.17
cypress-cucumber-preprocessor": "4.3.1"
framework: Cypress-Cucumber 

In Step definition file, I am using After() function from "cypress-cucumber-preprocessor/steps" ,  in After() i have written cy.screenshot(); so that after test i can take last screenshot, 

now here its working fine as per expected and capturing screenshot, but one issue i observed in screenshot it sometime it takes screenshot improper (i mean it take two screenshots and merge into one image) like below

![image](https://github.com/cypress-io/cypress/assets/126550779/8e418fa0-7fbf-4e47-82d3-e53e62e91b35)

can you suggest me here what wrong is happening and what i can do to overcome it.

### Test code to reproduce

Node 16
Cypress 11.2  and 12.17
cypress-cucumber-preprocessor": "4.3.1"
framework: Cypress-Cucumber 

In Step definition file, I am using After() function from "cypress-cucumber-preprocessor/steps" ,  in After() i have written cy.screenshot(); so that after test i can take last screenshot.

### Cypress Version

12.17

### Node version

v16.16

### Operating System

windows 11

**Comment by nagash77** [comment] 2023-07-13 13:35
Hi @prashant-kashid , can you provide a reproducible example using a fork of [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny)?  This will give our engineers the best chance of reproducing what you are seeing and be able to offer insights.

**Comment by prashant-kashid** [comment] 2023-07-13 14:03
Ok Give me some time i will provide you reproducible example

**Comment by yktoo** [comment] 2023-07-17 14:04
We're facing this, too. Looks like Cypress is reusing a part of the previous screenshot and overlays a new one.

**Comment by prashant-kashid** [comment] 2023-07-18 10:04
hi @nagash77 

its easy to reproduce on https://prep.comptia.org/ site, 
i have simply created one spec file with only one it block for below site and i am able to reproduce issue.
```js
describe('template spec', () => {
   it('passes', () => {
    cy.visit('https://prep.comptia.org/')
    cy.screenshot();
  })
})
```
![image](https://github.com/cypress-io/cypress/assets/126550779/8827d55c-9bf6-4c34-a817-385b9f80713e)

![image](https://github.com/cypress-io/cypress/assets/126550779/ae987ee5-f91d-4bc8-8b32-8764df1f7731)

**Comment by prashant-kashid** [comment] 2023-07-27 06:24
Hi Team, any update on this ticket?

**Comment by prashant-kashid** [comment] 2023-08-07 12:32
Any Progress on this ticket?

**Comment by prashant-kashid** [comment] 2023-08-14 06:16
@nagash77 can you update us on this issue? any ETA on this? currently this issue becoming critical as and high severity.

**Comment by jennifer-shehane** [comment] 2023-12-17 19:17
This is likely a duplicate of https://github.com/cypress-io/cypress/issues/2681

**Closed as not planned by jennifer-shehane** 2023-12-17 19:17 UTC
Labels: type: duplicate
