### ISSUE TITLE
Redirect is resolved before final valid URL is generated with needed parameters in it to open a page

### ISSUE THREAD

**Issue by AlexanderTunick** [cypress-io/cypress#8396] opened 2020-08-24 19:21 UTC
### Current behavior:

We have a URL containing arguments from which we then build out a custom page. 
1) It starts from ```https://content.kk-dev.com/offer/511d4e10-e63d-11ea-8a0e-cfb6ebdd1686/nucaht33p7?promotions=5e7b4f0```
2) then transforms to ```https://checkout.kk-dev.com/?token=54e2ba80-e63d-11ea-8a0e-cfb6ebdd1686&replace=true```
3) and then to ```https://checkout.kk-dev.com/checkout/17e0faff-ce43-4f16-b3e9-5f547b4d4e2d/signUp?replace=true```

Cypress resolves the 2nd step and records this redirect 
```
["302: https://checkout.kk-dev.com/?token=54e2ba80-e63d-11ea-8a0e-cfb6ebdd1686&replace=true"]
```
Then the page is being stuck and never reaches the 3rd step.
In the console for visit I have this output:
```
Command:       visit
cypress_runner.js:174416 Original Url:  https://content.kk-dev.com/offer/511d4e10-e63d-11ea-8a0e-cfb6ebdd1686/nucaht33p7?promotions=5e7b4f0445778b00073c758d
cypress_runner.js:174416 Resolved Url:  https://checkout.kk-dev.com/?token=54e2ba80-e63d-11ea-8a0e-cfb6ebdd1686&replace=true
cypress_runner.js:174416 Redirects:     ["302: https://checkout.kk-dev.com/?token=54e2ba80-e63d-11ea-8a0e-cfb6ebdd1686&replace=true"]
cypress_runner.js:174416 Cookies Set:   [{…}]
```

### Desired behavior:

I want Cypress to wait until the final valid URL will be generated to open a test page rather than resolving the first redirect.

### Test code to reproduce

Just try to open this test url: ```https://content.klickly-dev.com/offer/511d4e10-e63d-11ea-8a0e-cfb6ebdd1686/nucaht33p7?promotions=5e7b4f0445778b00073c758d```

### Versions
3.4.0

**Comment by jennifer-shehane** [comment] 2020-08-25 07:18
I'm visiting the given URL and see it rerouting through 3 urls and ending up on a login page. I can see that it ends up on the same URL as the URL when visited outside of Cypress. This looks like expected behavior to me. Let me know if this is incorrect.

<img width="1677" alt="Screen Shot 2020-08-25 at 1 46 58 PM" src="https://user-images.githubusercontent.com/1271364/91144078-8280eb00-e6d9-11ea-818f-7920e577621e.png">

I also see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) to ensure you get the most recent bug fixes.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example - perhaps there's something in your `cypress.json` or support/plugins files that's affecting this that we need. Then we will consider reopening the issue.

**Closed by jennifer-shehane** 2020-08-25 07:18 UTC

**Comment by AlexanderTunick** [comment] 2020-09-06 14:24
As turned out it was a problem with session storage cleaning. 
This workaround helped out
`cy.window().then((win) => {
                win.sessionStorage.clear();
            });`
