### ISSUE TITLE
Cypress 10.0.0 crashes couple of times on MacOS after upgrade

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [cypress-io/cypress#22051] opened 2022-06-02 17:10 UTC
### Current behavior

After upgrading to latest version of cypress, it crashed couple of times.
```
Assertion failed: (napi_call_function(env, recv, callback, 3, args, &recv) == napi_ok), function fse_dispatch_event, file ../src/fsevents.c, line 151.
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-x64 (21.4.0)
Cypress Version: 10.0.1
```
Also, the following file was missing before the crash
```
GET /__/assets/fonts/FiraCode-VF.woff2 404 1.857 ms - 136
```

### Desired behavior

Should not crash after upgrade

### Test code to reproduce

Seems to be happening with this issue - https://github.com/cypress-io/cypress/issues/22050

### Cypress Version

10.0.0

**Comment by flotwig** [comment] 2022-06-02 18:43
Hi @IrfanSyed-PSC, thanks for reporting this. I think this looks like a duplicate of https://github.com/cypress-io/cypress/issues/21928 - if you agree, can you please comment on that issue with any information specific to your environment? OSX version, CPU  architecture, etc.

**Closed** 2022-06-03 15:40 UTC
Labels: OS: mac, stage: awaiting response, v10.0.0 :bug:
