### ISSUE TITLE
Using localproxy gives connection to upstream proxy couldn't be established. 

### ISSUE THREAD

**Issue by dipakspawar** [cypress-io/cypress#5179] opened 2019-09-22 21:34 UTC
### Current behavior:
We are trying to setup ci with end-to-end tests. To target specific servers in our infrastructure we pass headers in the web requests. Because of this [issue](https://github.com/cypress-io/cypress/issues/687), we are not able to pass the headers in all web-requests generated from browser.

This is what we tried so far:
1. Loaded an extension to add custom header using plugins/index.js on-broswer-launch event, but the requests originated from cypress tests doesn't seem to have that header.
2. As that didn't work, I was trying to setup local proxy using mitmproxy to intercept network traffic and add headers dynamically. That seems to be working fine, when I invoke the url using curl but I get an error while running tests using cypress. I have attached debug logs from a test 
run.

I saw that work [issue](https://github.com/cypress-io/cypress/issues/687) is in progress, but I am not sure about the timeline, and we have immediate need for solution/workaround to solve this.

[error.log](https://github.com/cypress-io/cypress/files/3640144/error.log)

### Desired behavior:
We need a way to add a custom header to every web request originated from browser.

### Steps to reproduce: (app code and test code)
This is what I am doing.
1. On mac run ubuntu docker image.
2. Install mitmproxy on it.
3. Create cypress test file which targets any https url (in my case it was https://airbnb.com)
4. Open terminal, set http_proxy and https_proxy env variable.
5. Run "npx cypress run"

### Versions
cypress@3.4.1
Ubuntu
Chromium headless browser

**Comment by ryan-snyder** [comment] 2019-09-23 13:17
Until that issue is done, right now you can only add custom headers to xhr requests. There is no workaround unless you could force your application to only send xhr requests

**Comment by flotwig** [comment] 2019-09-23 13:58
Hey @dipakspawar -

It looks like Cypress is attempting to use SSL to connect to your proxy:

```
  cypress:network:agent Creating proxied socket for https://www.airbnb.com/ through https://127.0.0.1:8080 +1ms
```

I noticed that you're setting HTTP_PROXY and HTTPS_PROXY like this: `HTTP_PROXY=127.0.0.1:8080` That may be confusing Cypress, since it expects a protocol as well.

Can you try adding the protocol to the front of the `HTTP_PROXY` url? Like this: `HTTP_PROXY=http://127.0.0.1:8080`. Don't forget to set `HTTPS_PROXY` as well. It should work.

**Comment by flotwig** [comment] 2019-09-23 14:16
> 1. Loaded an extension to add custom header using plugins/index.js on-broswer-launch event, but the requests originated from cypress tests doesn't seem to have that header.

For a `cy.visit()`, Cypress only uses the headers explicitly supplied to `cy.visit()` and the `user-agent` from the browser (`headers` below are cached from the first request made to Cypress):

https://github.com/cypress-io/cypress/blob/dafc61a6848fb3151f117e3c5aee3fb572d238e4/packages/server/lib/request.coffee#L581-L589

This could be an oversight, we may want to copy all headers or some headers minus a blacklist.

For non-`cy.visit()` and non-`cy.request()` requests, your browser extension should be able to send the headers and have them be proxied correctly through Cypress.

So if you set up `cy.visit()` to send the necessary headers AND use your browser extension, that should result in the desired header being added to all outgoing requests. The HTTP proxy solution works too of course.

**Comment by dipakspawar** [comment] 2019-09-23 21:43
Thanks @flotwig.

I tried prepending protocol to respective proxy. Now it's giving another error. I have attached the logs.

Let me know if you need anything. This is a major blocker us for us to move to Cypress.

This is the exception:  A connection to the upstream proxy could not be established: 139705003600384:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:827:

[error2.log](https://github.com/cypress-io/cypress/files/3644274/error2.log)
](url)

**Comment by flotwig** [comment] 2019-09-23 21:55
@dipakspawar You need to use `http://` on the proxy URL, since it is not SSL-encrypted. I can see that your HTTPS_PROXY is set to `https://127.0.0.1:8080`:

```
  cypress:server:util:proxy found proxy environment variables { http_proxy: 'http://127.0.0.1:8080', https_proxy: 'https://127.0.0.1:8080' } +0ms
```

HTTPS_PROXY should be set to `http://127.0.0.1:8080` instead. This will get rid of your error.

Also, are you really visiting `https://airbnb.com` in your tests, not a development server? If so, make sure your MITM proxy supports intercepting HTTPS traffic, since there are some extra steps vs. proxying insecure traffic.

**Comment by dipakspawar** [comment] 2019-09-24 17:51
Thanks @flotwig, that worked. Let me try to run it as part of CI, see how it goes.

**Comment by sainthkh** [comment] 2021-01-04 08:00
Closing this issue because it seems that the problem has been solved and the issue is old. If it's still happening, please open a new issue.

**Closed by sainthkh** 2021-01-04 08:00 UTC
