### ISSUE TITLE
Cypress.env prefers value from cypress.json rather than CYPRESS_* env variable

### ISSUE THREAD

**Issue by fnune** [cypress-io/cypress#15606] opened 2021-03-22 08:12 UTC
### Current behavior

`Cypress.env("BASE_URL")` returns `http://localhost:5001` (the value in an environment variable) when running inside tests, but `http://localhost:6666` (the value in `cypress.json`) when running from inside commands. 

### Desired behavior

`Cypress.env("BASE_URL")` returns `http://localhost:5001` (the environment variable value) both when called from commands as well as tests, instead of returning a different result depending on the runtime.

### Test code to reproduce
I have this command:
```typescript
// cypress/support/commands.ts
Cypress.Commands.add("unauthenticate", () => {
    cy.request("GET", `${Cypress.env("BASE_URL")}/auth/logout`);
});
```
This `cypress.json` file:
```
{
    "env": {
        "BASE_URL": "http://localhost:6666"
    }
}
```
And I'm calling Cypress like so:
```
CYPRESS_BASE_URL=http://localhost:5001 yarn cypress:ci
```
Where the scripts look like this:
```
        "cypress:ci": "yarn cypress:ci:wait && yarn cypress:run",
        "cypress:ci:wait": "echo \"Waiting for the app at $CYPRESS_BASE_URL...\" && wait-on -t 120000 $CYPRESS_BASE_URL && echo 'Found it!'",
        "cypress:run": "cypress run",
```

### Versions

```
Cypress package version: 6.8.0
Cypress binary version: 6.8.0
Electron version: 11.3.0
Bundled Node version: 12.18.3
```

**Comment by fnune** [comment] 2021-03-22 08:16
A workaround for now:

```typescript
// commands.ts
const BASE_URL = process.env.CYPRESS_BASE_URL || Cypress.env("BASE_URL");
```
Elsewhere:
```
Cypress.env("BASE_URL") // Can use Cypress.env elsewhere
```

**Comment by richardst89** [comment] 2021-04-12 18:01
I've encountered this issue too.
However, if you include "--env SomeOtherVar=AnyValue" when executing, it appears to re-prioritise BaseUrl from the environment variables.

Definitely something buggy going on!

**Comment by jennifer-shehane** [comment] 2021-05-06 18:59
Duplicate of https://github.com/cypress-io/cypress/issues/15606

**Closed by jennifer-shehane** 2021-05-06 18:59 UTC
