### ISSUE TITLE
Support lazy evaluation for routes

### ISSUE THREAD

**Issue by TerrenceLJones** [cypress-io/cypress#259] opened 2016-10-07 21:25 UTC
Instead of only using a glob or regexp, it be nice to also have the ability to do the following: 

```
 route('/myURL//:lazy_param', function () {})
```

**Comment by TerrenceLJones** [comment] 2016-10-07 21:27
@brian-mann I've opened this issue as per our conversation on Gitter. My understanding of what really needs to be implemented is lacking. If I missed something can you help me formulate a more in depth description of this issue?

**Comment by andersthorbeck** [comment] 2018-04-16 12:13
This seems to be a variant of the feature suggestion in https://github.com/cypress-io/cypress/issues/387

**Comment by jennifer-shehane** [comment] 2018-04-17 16:14
Closing as duplicate of https://github.com/cypress-io/cypress/issues/387

**Closed by jennifer-shehane** 2018-04-17 16:14 UTC
Labels: type: duplicate
