### ISSUE TITLE
allow "cy.accessFile" on cy.readFile

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#3027] opened 2018-12-28 15:52 UTC
Hi,

Is there a way to only check if a files exist without throwing an error ?
Using the cy.readFile() function or using the fs.access()

Regards.

**Comment by jennifer-shehane** [comment] 2019-01-02 09:10
Duplicate of https://github.com/cypress-io/cypress/issues/411

**Closed by jennifer-shehane** 2019-01-02 09:10 UTC

**Comment by jennifer-shehane** [comment] 2019-01-18 07:43
@mandriao84 There is an example of how to read a file that may or may not exist in our docs here: https://on.cypress.io/task#Read-a-file-that-might-not-exist
