### ISSUE TITLE
Adding a preprocessor for the Snowpack build tool

### ISSUE THREAD

**Issue by alejandroiglesias** [cypress-io/cypress#14282] opened 2020-12-23 01:18 UTC
### What would you like?
In the same way that are preprocessors for Webpack, Browserify, Parcel, Rollup, etc. it would be great to have a preprocessor for [Snowpack](https://www.snowpack.dev/). Alternatively, if the core team won't support it, can you please point to clear directions on how to implement it? I might try to sell the task to the team.

### Why is this needed?
We are using Snowpack in a project and would like to use cypress-svelte-unit-test, but the lack of a preprocessor for Snowpack makes it impossible unless I'm missing something.

**Comment by jennifer-shehane** [comment] 2020-12-29 06:49
Duplicate of https://github.com/cypress-io/cypress/issues/14285

**Closed by jennifer-shehane** 2020-12-29 06:49 UTC
