### ISSUE TITLE
Not possible for more than one plugin to listen to `before:browser:launch` event

### ISSUE THREAD

**Issue by kpturner** [cypress-io/cypress#23496] opened 2022-08-22 16:46 UTC
### Current behavior

We have two plugins that both perform functionality on the `before:browser:launch` event.

Previously both plugins worked as expected - I believe in version 9 at least.

We have now found that one of the plugins no longer works.  It seems that if two or more listeners are attached to the `before:browser:launch` event, only the last listener attached actually fires/does anything. 

### Desired behavior

It should be possible to add as many listeners as you like to this event.

### Test code to reproduce

https://github.com/kpturner/cypress-bug-repro

### Cypress Version

10.6.0

### Node version

16

### Operating System

Mac Big Sur

**Comment by emilyrohrbough** [comment] 2022-08-23 19:07
Duplicate of: https://github.com/cypress-io/cypress/issues/22428

**Closed by emilyrohrbough** 2022-08-23 19:07 UTC
Labels: type: bug, type: duplicate, E2E-core
