### ISSUE TITLE
v11.0 does not respect watchForFileChanges

### ISSUE THREAD

**Issue by ramicohen303** [cypress-io/cypress#24737] opened 2022-11-19 01:18 UTC
### Current behavior

When using the Cypress UI, change to a code file no longer triggers a rerun of active spec. This broke in v11.0.0. Once I revert to v10.x.x, the issue is resolved.
I don't have watchForFileChanges set, but the default is true, so it should trigger a rerun. I verified under project settings that the setting is true.

### Desired behavior

Trigger a rerun

### Test code to reproduce

You can reproduce this using a vanilla vue project:

npm init vue@latest
Run npm test:e2e:dev, run example test, make a change, see rerun.
Upgrade to Cypress 11.x, repeat above. No rerun.

### Cypress Version

11.0.0

### Node version

16.18.1

### Operating System

Ubuntu 22.04

**Comment by nagash77** [comment] 2022-11-21 16:20
@ramicohen303 can you please try using 11.1.  There was a fix to this problem in that release that I think will address your problem.  If not please comment here and I will reopen this issue.

**Comment by ramicohen303** [comment] 2022-11-21 23:41
It is still an issue in 11.1. I just tested it again according to the script above.

**Comment by mike-plummer** [comment] 2022-12-06 18:59
Sorry this is causing you issues @ramicohen303 . I've confirmed this is still a problem in v12.0.0 (just released today) - the file watcher seems to work and re-run the test the first time or two I change a spec file in a fresh project, but then it stops working. My guess is there's some caching/optimization introduced by the snapshotting performance improvements we added in 11.x that aren't "seeing" the changed file. We'll get this routed to the team to take a look at

**Comment by mike-plummer** [comment] 2022-12-07 14:49
@ramicohen303 To follow up on this, it appears that file watching is broken when a test mode is passed via CLI. If you go into the `package.json` file and update the `test:e2e:dev` script to not pass the `--e2e` flag when launching Cypress then file watching appears to work as expected. Obviously not ideal since you have to select E2E manually when Cypress opens, but at least provides a workaround until we can get a fix in.

This problem is more precisely captured in #24834 , so I am going to close this issue in favor of that one to avoid duplication in our issues

**Closed as not planned by mike-plummer** 2022-12-07 14:49 UTC

**Comment by ramicohen303** [comment] 2022-12-07 16:07
Thank you @mike-plummer
