### ISSUE TITLE
Running cypress with webpack-preprocessor created typescript error

### ISSUE THREAD

**Issue by Kombustor** [cypress-io/cypress#3136] opened 2019-01-15 15:36 UTC
### Current behavior:

I created my setup exactly like in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack .

My test file looks like this:
``` 
describe('TypeScript', () => {
    it('works', () => {
        const x: number = 42;

        expect(x).to.equal(42);
    })
});
``` 

The console output is:
```
Running: dummy.spec.ts...                                                                (1 of 1)
i ｢atl｣: Using typescript@3.1.6 from typescript
i ｢atl｣: Using tsconfig.json from [...]/tsconfig.json
i ｢atl｣: Checking started in a separate process...
× ｢atl｣: Checking finished with 1 errors
i ｢atl｣: Using typescript@3.1.6 from typescript
i ｢atl｣: Using tsconfig.json from [...]/tsconfig.json

Oops...we found an error preparing this test file:

  cypress\integration\dummy.spec.ts

The error was:

[at-loader] ./node_modules/cypress/types/index.d.ts:3937:50
    TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```

The mentioned line (and the line above) in cypress typings source code:
```
// TODO - remove this if possible. Seems a recent change to TypeScript broke this. Possibly https://github.com/Microsoft/TypeScript/pull/17912
  type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>> // tslint:disable-line
```

### Desired behavior:

The typescript source should be transpiled into plain javascript using the webpack preprocessor. The test should run.

### Versions

```
"@cypress/webpack-preprocessor": "^4.0.3"
"cypress": "^3.1.4"
"typescript": "^3.1.6"
"webpack": "^4.25.1"
```

Is there any newer/better way for my setup? I'm using webpack + babel to transpile & pack the typescript source.

**Comment by bahmutov** [comment] 2019-01-15 15:39
Duplicate of https://github.com/cypress-io/cypress/issues/3024 - this has been resolved, and the fix will be released in 3.1.5 Meanwhile I suggest compiling tests with `tsc --skipLibCheck` option (which is blunt of course)

**Closed by bahmutov** 2019-01-15 15:39 UTC
