### ISSUE TITLE
Alias created in before() only works on first test (but it's only used in the second test)

### ISSUE THREAD

**Issue by dsesami** [cypress-io/cypress#5351] opened 2019-10-11 14:56 UTC
### ------------------------------------------
This appears to be really similar to https://github.com/cypress-io/cypress/issues/2766 (and https://github.com/cypress-io/cypress/issues/665 in turn), but it seems like it's a bit different. The alias definition exists, like `user` as an object exists, and `user.id` exists, but the value of `user.id` is null.

Note that an alias created _within_ the second test doesn't appear to work -- 

```js
it('does something', function () {
  cy.createUser('xyz').as('user') // createUser is an exec() outside of the application
  this.user.something... 
    // expected this to be available, 
    // as this works if I stuck it into a beforeEach 
    // on any test, or a before on the first test
})
```

### Current behavior:
The before() hook contains an alias. I would expect `this` to have `this.user` available as an object. If it is in the first test (I copy and move the test to the top), the test works. However, after the first test, `this.user` exists, but its value is empty and undefined.
### Desired behavior:
I would expect `this.user` to remain a consistent object available throughout each test in the spec file. I can currently get around this with `cy.createUser().then((user) => )`, but that's why I wanted to use aliases in the first place. Alternatively, I'd expect an alias to be create-able within a test.

### Steps to reproduce:

Test setup:
```js
before(function() {
  cy.createUser('foo').as('user') // returns an object that has a value called user.id
})

it('is the first test') {
 // nothing happens here
}

it('is a second test') {
  cy.visit(`/users/${this.user.id}`)
}
```
### Versions
Latest cypress (Oct 11 2019), chrome, fedora.

If you need more info, please feel free to ask.

**Comment by jennifer-shehane** [comment] 2019-10-11 19:59
@dsesami Can you provide an example of this behavior that we can run completely on our machines? We do not know what is happening within your custom `createUser` for example so cannot run this code to prove your theory. Please provide the complete code we can run to look into your issue - which tests are failing that should not fail. Thanks!

**Comment by dsesami** [comment] 2019-10-16 16:15
@jennifer-shehane here's a simpler example with the example tests that are generated with cypress initialization. `npx cypress open` on an empty directory will generate tests, and then you can substitute this following code in `window.spec.js`.

```
 /// <reference types="Cypress" />
 
 context('Window', () => {
   before(() => {
     cy.visit('https://example.cypress.io/commands/window')
     cy.get('h1').as('obj')
   })  
   beforeEach(() => {
     cy.visit('https://example.cypress.io/commands/window')
   })  
 
   it('cy.window() - get the global window object', () => {
     // https://on.cypress.io/window
     cy.window().should('have.property', 'top')
     cy.log(cy.get('@obj').value) // works
   })  
 
   it('cy.document() - get the document object', () => {
     // https://on.cypress.io/document
     cy.document().should('have.property', 'charset').and('eq', 'UTF-8')
     cy.log(cy.get('@obj').value) // doesn't work
   })  
```

Here's a screenshot:
![Screenshot from 2019-10-16 12-11-08](https://user-images.githubusercontent.com/19942822/66937755-0e33e080-f00e-11e9-8a3b-e7c51f1f760f.png)

Note that the alias is cleared after the first test when using `before()`. It feels like it should remain persistent; the point of `before()` is to do some setup before the test suite begins. I do understand that we want test isolation, but it feels weird that triggering an alias in `before()` just works for the first test. It'd probably be better to either:

1. Throw an error and prohibit aliases in `before()`, and only allow them in `beforeEach()`
2. Allow aliases created in `before()` to persist across tests. I'm putting it in a `before()` block specifically to save on API calls (as it's not changing).

**Comment by dsesami** [comment] 2019-10-22 17:38
@jennifer-shehane this is just a light ping, wondering if you've had a chance to look this over. Thank you!

**Comment by ronaiza-cardoso** [comment] 2019-10-23 14:26
Hello, I'm having this issue too. I noticed that the alias inside the `before` hook just works if we have only one test.

```json
"cypress": "^3.4.1",

node: v10.13.0
npm: 6.4.1
```

**Comment by jennifer-shehane** [comment] 2019-10-25 15:49
`before` code is only run once, and between the tests Cypress removes all of the aliases. So in subsequent tests it is not available.

Moving this code into a `beforeEach` will work.

Closing as duplicate of https://github.com/cypress-io/cypress/issues/665

**Closed by jennifer-shehane** 2019-10-25 15:49 UTC

**Comment by dsesami** [comment] 2019-10-25 15:56
@jennifer-shehane as this is apparently a very regularly-duplicated issue, may I suggest that the docs be updated to specify this nuance? Many users get tripped up by it.

**Comment by jennifer-shehane** [comment] 2020-01-03 08:42
@dsesami We updated the scope of the original issue to issue a warning when defining an alias in a before, please direct all comments to the original issue. https://github.com/cypress-io/cypress/issues/665#issuecomment-552961024
