### ISSUE TITLE
Cypress failing after uncaught:exception thrown from 3rd party, even thought 'uncaught:exception' return false;

### ISSUE THREAD

**Issue by wesoledi** [cypress-io/cypress#6021] opened 2019-12-20 15:28 UTC
### Current behavior:
I keep get failing test because of 3rd party scripts on site, I am testing. 
Sample site: https://gloswielkopolski.pl/sto-najpopularniejszych-nazwisk-w-polsce-lista/ar/c1-13614652

Problem is with: `Uncaught Error: Uncaught TypeError:`. 
It appear randomly I guess, but it mostly come-up. 

### Reproduce:
I used this "uncaught:exception" tricks from other issues, like mentioned here: https://github.com/cypress-io/cypress/issues/987

And it didnt help at all. And use some others other, like "onerror" (see code below). 
I also added: 
```js
on('uncaught:exception', (err, runnable) => {
    console.log('hello?');
    return false;
  });
```
To `index.js` in plugins and support directory. These files is visible to cypress (when I made mistake there, cypress throw errors indicating something wrong is in this files). 

Sample test code:
```javascript
describe('Google GPT script test', () => {
  Pages.PAGES_TO_VISIT.forEach((pageUrlForTesting) => {
    beforeEach(() => {
      cy.on('uncaught:exception', (err) => {
        return false;
      });
    });

    it(`Exist on page: "${pageUrlForTesting}"?`, () => {

      // url is good for sure
      cy.visit(pageUrlForTesting, {
        onBeforeLoad: (win) => {
          win.onerror = (m) => {console.log('my on error: ', m); return true;}
        }
      });
      cy.window().then((window) => {
        expect(typeof window.googletag !== 'undefined').to.equal(true);
      });
      cy.on('uncaught:exception', (err, runnable) => {
        return false;
      });
    })

  });
});
```

What more:
- I use CLI: cypress run, and must use it
- I use **Electron** 61, with version 3.8.0 of Cypress, and must use it, cant use chrome. 
(also tested on 3.6.0, which was mentioned in issue 987 to solve similar problem). 

### Desired behavior:
I want to get rid off test fail because of "uncaught error".
Hide it, omit, etc. 

I know this error could appear, but it dont bother me, with things I want to test.

**Comment by roggerfe** [comment] 2019-12-21 12:35
I am having a similar issue, it is very frustrating and hard to choose an automated framework with these behaviors, in my case, my application is not failing, but appears iframe cypress error which blocks me from keep my tests:

![Seleção_284](https://user-images.githubusercontent.com/6186831/71307986-34427c00-23d5-11ea-8338-a4f733e1f52c.png)

I am definetely changing my mind about using cypress

**Comment by jennifer-shehane** [comment] 2019-12-23 07:12
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. I tried visiting the url specified and it throws 403. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example, application to visit and test code that we can run locally and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-12-23 07:12 UTC

**Comment by buremba** [comment] 2020-01-06 13:29
I'm having the same issue in `3.8.1`. While I also don't have a public URL to share, we're using Nuxt.js and building the app in dev mode as a workaround since Nuxt halts the app in case it runs into an exception.
