### ISSUE TITLE
Getting intermittent node error when going to URL getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by robert-smith135** [cypress-io/cypress#1755] opened 2018-05-22 08:16 UTC
Hi, we're running cypress to test the local news section of the BBC news site on out TEST environment https://www.test.bbc.co.uk/news/localnews/2653822-Cardiff/0. (This should be publicly accessible). We have a test that look at the radius buttons to see if they redirect correctly. However it looks like there is some flake (unless I'm doing something wrong) when clicking the button and running an assertion to see if the page has redirected. When running a click command on the button cypress sometimes throws a node networking error: getaddrinfo ENOTFOUND when the page is reloaded.

I'm running the tests in the CLI mode, and the cypress gives me the following screenshot on the failing test: 

![screen shot 2018-05-22 at 09 02 49](https://user-images.githubusercontent.com/28531577/40350028-5c9e5040-5da0-11e8-8e86-1065bc49cba4.png)

### Current behavior: 
The test below sometimes fails. 

### Desired behavior:
The below test works every time 

### Steps to reproduce:
Running the below test with the CLI using the cypress docker container https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/chrome65-ff57 sometimes fails. 

Im also using the "chromeWebSecurity": false option in cypress.config.

```js
        it('has radius buttons that redirect as expected', () => {
            cy.server();
            cy.route('https://www.int.bbc.co.uk/news/localnewsdata/2653822/0/50/50').as('getLocalNewsData');
            cy.route('https://www.int.bbc.co.uk/news/localnewsdata/promoted-content/2653822/0').as('getPromotedContentData');
            cy.visit(path + "/2653822-cardiff/0?component-env=int");

            cy.wait('@getLocalNewsData');
            cy.wait('@getPromotedContentData');

            cy.get('.local-news-radius__link').should('have.length', 5);
            cy.get('.local-news-radius__link').eq(4).click();

            cy.url().should('eq', path + '/2653822-cardiff/30');
            cy.get('.local-news-radius__link>a').eq(4).should('be.visible').and('have.class', 'selected');

            cy.get('.local-news-radius__link').eq(3).click();
            cy.url().should('eq', path + '/2653822-cardiff/20');
            cy.get('.local-news-radius__link>a').eq(3).should('be.visible').and('have.class', 'selected');

            cy.get('.local-news-radius__link').eq(2).click();
            cy.url().should('eq', path + '/2653822-cardiff/10');
            cy.get('.local-news-radius__link>a').eq(2).should('be.visible').and('have.class', 'selected');

            cy.get('.local-news-radius__link').eq(1).click();
            cy.url().should('eq', path + '/2653822-cardiff/5');
            cy.get('.local-news-radius__link>a').eq(1).should('be.visible').and('have.class', 'selected');

            cy.get('.local-news-radius__link').eq(0).click();
            cy.url().should('eq', path + '/2653822-cardiff/0');
            cy.get('.local-news-radius__link>a').eq(0).should('be.visible').and('have.class', 'selected');
        });
```

### Versions 
Cypress: 2.1.0
Browser: Election
Operating System: Debian

**Comment by Bkucera** [comment] 2018-05-22 17:14
Hi, I tried to reproduce your failure, but it seems I'm failing even earlier than you. I got redirected to a `data:` url... see here:
![image](https://user-images.githubusercontent.com/14625260/40378250-01ec3682-5dc1-11e8-979b-1f8daa7519bf.png)

Could you provide a fully reproducible example, using https://github.com/cypress-io/cypress-test-tiny ? For example, just a single spec file that fails.

**Comment by robert-smith135** [comment] 2018-05-23 12:44
Apologies, I should have mentioned that that page runs a script that redirects the page to an international version if you access it from a location outside the United Kingdom. I get around this by blacklisting the host that the script is requested from, so it never runs. 

We run the tests inside a docker container. We're using version 18.03.1-ce-mac65 (24312). I've created a sample repo here with the problem test. 
https://github.com/robert-smith135/test

When cloned run these commands:
npm install
docker build -t test:latest .
docker run --rm -v `pwd`:/usr/local/bbc -t cypress-test:latest bash -lc "cypress run -s cypress/integration/topicPage.spec.js"

Because this problem seems to be intermittent I wrote a simple bash script that keeps track of passes and failures that you can run by:

sh runonloop.sh.

**Comment by saikrishna321** [comment] 2019-05-09 10:11
@jennifer-shehane I'm seeing the same error with latest Cypress and the same tests work fine on my test env and fail on another env. Not sure how to debug on the issue

**Comment by flotwig** [comment] 2019-06-13 17:08
We removed this 500 error in 3.3.0, opting instead to propagate the network error directly to the browser. However, we should also retry on `ENOTFOUND` errors, which will be done in #4424

Closing since it's working as it should now and there is another issue to improve the experience.

**Closed by flotwig** 2019-06-13 17:08 UTC
Labels: stage: needs information

**Comment by jennifer-shehane** [comment] 2019-06-19 08:47
The code for this is done in #4424, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by YassineFathallah** [comment] 2019-06-24 13:59
Hi @jennifer-shehane, any updates on when this fix would be released? Thanks
