### ISSUE TITLE
Docker - Browser: 'chrome' was not found on your system or is not supported by Cypress

### ISSUE THREAD

**Issue by sabarishnarain** [cypress-io/cypress#8611] opened 2020-09-18 01:58 UTC
cypress version 4.11

### Current behavior:

cypress run --browser chrome --headless --spec \"**/pr/*.spec.ts\"",

Tests intermittently fails with the following. 

`Browser: 'chrome' was not found on your system or is not supported by Cypress - on docker`

This happens more frequently in azure CI services on using `cypress/browsers:node12.16.2-chrome81-ff75`. 
Workaround is to re-try the job several times.

[cypress.log](https://github.com/cypress-io/cypress/files/5242886/cypress.log)

### Desired behavior:

Tests should run on chrome. 

### Test code to reproduce

Not sure how to provide a test code. This problem is very common with the above docker image and in Azure CI. I can provide the link to the CI job if needed.

**Comment by gustawx** [comment] 2020-09-22 08:37
Today I had exactly same issue with version 5.2.0:
![image](https://user-images.githubusercontent.com/13650820/93860380-54ce9800-fcbf-11ea-9e73-8c8be60b4d6e.png)

I run tests in a docker image. This happened for the first time and when I ran tests again all was fine

**Comment by gustawx** [comment] 2020-09-23 16:04
@sabarishnarain it seems to work fine with version 5.1.0

**Comment by johrues** [comment] 2020-11-19 09:53
@gustawx and which docker image are you using? i had the issue reproducible even with 5.1.0 version

**Comment by gustawx** [comment] 2020-11-19 09:58
Currently I'm successful with latest version 5.6.0.
If you have the problem with 5.1.0 the problem might be more complex and occur under some specific circumstances. Did you try latest version?

**Comment by johrues** [comment] 2020-11-19 10:34
yep, im using latests cypress/browsers:node12.18.3-chrome83-ff77 and latest cypress version 5.6.0
```
$ npx cypress run --record --key 2e450dd7-96e5-4f88-af1a-f7c448149dd0 --config baseUrl="https://www.notino.$COUNTRY" --env _countryCode=$COUNTRY --browser $BROWSER --headless --group $COUNTRY-$BROWSER-Run --ci-build-id $CI_PIPELINE_ID
[08:02:34]  Verifying Cypress can run /root/.cache/Cypress/5.6.0/Cypress [started]
[08:02:53]  Verifying Cypress can run /root/.cache/Cypress/5.6.0/Cypress [completed]
Can't run because you've entered an invalid browser name.
Browser: 'chrome' was not found on your system or is not supported by Cypress.
Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox
You can also use a custom browser: https://on.cypress.io/customize-browsers
Available browsers found on your system are:
- firefox
- electron
```

**Comment by j2020v** [comment] 2020-11-25 08:59
What's on your dockerfile?

**Comment by johrues** [comment] 2020-11-25 09:07
@j2020v I was using the default image cypress/browsers:node12.18.3-chrome83-ff77 one thing I tried doing was to rehost this on our GitLab so just 
`FROM cypress/browsers:node12.18.3-chrome83-ff77`

recently I tried updating to the newest image `cypress/browsers:node14.15.0-chrome86-ff82` and cypress 6.0.0 and still running into the same issue

The worst thing is more time I spent debugging this more nonsensical it seems

```$ google-chrome --version
Google Chrome 86.0.4240.193 
$ npx cypress info
Displaying Cypress info...
Detected 2 browsers installed:
1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 86.0.4240.193
  - Executable: google-chrome
2. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 82.0.3
  - Executable: firefox
Note: to run these browsers, pass <name>:<channel> to the '--browser' field
Examples:
- cypress run --browser chrome
- cypress run --browser firefox
Learn More: https://on.cypress.io/launching-browsers
Proxy Settings: none detected
Environment Variables: none detected
Application Data: /root/.config/cypress/cy/development
Browser Profiles: /root/.config/cypress/cy/development/browsers
Binary Caches: /root/.cache/Cypress
Cypress Version: 6.0.0
System Platform: linux (Debian - 10.6)
System Memory: 63.2 GB free 33 GB
$ npx cypress run --record --key <my-key> --config baseUrl="https://www.notino.$COUNTRY" --env _countryCode=$COUNTRY --browser $BROWSER --headless --group $COUNTRY-$BROWSER-Run --ci-build-id $CI_PIPELINE_ID
[08:56:20]  Verifying Cypress can run /root/.cache/Cypress/6.0.0/Cypress [started]
[08:56:23]  Verifying Cypress can run /root/.cache/Cypress/6.0.0/Cypress [completed]
Can't run because you've entered an invalid browser name.
Browser: 'chrome' was not found on your system or is not supported by Cypress.
Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox
You can also use a custom browser: https://on.cypress.io/customize-browsers
Available browsers found on your system are:
- firefox
- electron
```

**Comment by johrues** [comment] 2020-11-25 16:02
here is also pastebin with debug enabled https://pastebin.com/TfDr5rYE

**Comment by denis-domanskii** [comment] 2020-12-01 16:58
I just faced the same issue: 

```
   Browser: 'chrome' was not found on your system or is not supported by Cypress.
   Cypress supports the following browsers:
   - chrome
   - chromium
   - edge
   - electron
   - firefox (Cypress support in beta)
   You can also use a custom browser: https://on.cypress.io/customize-browsers 
   Available browsers found on your system are:
   - firefox
   - electron
```

Cypress 5.2.0
Docker image: cypress/browsers:node12.19.0-chrome86-ff82

It looks like flickering issue, because previous and next builds with the same configuration executed without the issue.

**Comment by denis-domanskii** [comment] 2020-12-01 16:59
Also I see a similar issue here: #8736

**Comment by johrues** [comment] 2021-01-06 10:22
any news about this? this is still a problem for us

**Comment by madhav580** [comment] 2021-01-11 15:29
Cypress looks for chrome installation in this Path: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe". If chrome installed in "C:/Program Files/" then it will throw an error.

**Comment by Undistraction** [comment] 2021-01-12 17:46
Intermittent issue on our CI with cypress@6.2.1 Same error, approx 1/50th of the time. Restarting the job almost always results in a successful run. No clear pattern.

**Comment by kaiyoma** [comment] 2021-01-25 23:26
Same here. Problem happens randomly, maybe 1-2% of the time, even though nothing about our infra is changing. Also running Cypress 6.2.1.

**Comment by Undistraction** [comment] 2021-01-26 09:30
We've been closely monitoring this issue. Same image for all our runners. Same resources for all our runners. But we are seeing two Cypress-related errors intermittently. This one and Smoke test timeouts.

**Comment by pastelsky** [comment] 2021-02-09 04:02
We noticed this issue happening too in one of our longer cypress tests (rare), but another hello world test on google.com has had no such failure on any run in the last 30 days.

Could it depend on the nature of the test?

**Comment by macrozone** [comment] 2021-03-15 13:57
this happens for me as well when it try to run the tests with `--record  --parallel`

using `cypress/browsers:node12.18.3-chrome89-ff86`

**Comment by aninhalacerda** [comment] 2021-03-22 20:50
it only worked when I've tried with `cypress/included:6.3.0` and Cypress `version 6.8.0`

**Comment by MicmladenTo** [comment] 2021-03-29 17:36
> 
> 
> Cypress looks for chrome installation in this Path: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe". If chrome installed in "C:/Program Files/" then it will throw an error.

What madhav580 here said is what appears to have been the issue for a good deal of these cases, it seems.

**Comment by kaiyoma** [comment] 2021-03-29 21:57
I see this with Chrome installed on Debian 9.

**Comment by guyguy333** [comment] 2021-04-16 10:04
Having the same issue with `node14.7.0-chrome84` docker image.

**Comment by pgfisico** [comment] 2021-04-27 05:34
I believe this is an issue with the Cypress launcher and not Docker image related. The issue is caused by not fully reading the output of the browser's version command. In the `cypress:launcher` logs you will see `Could not extract version from stdout using regex: { stdout: '', versionRegex: <varies depending on browser> }`. Note that `stdout` is empty and this log message is different from what you see when the binary is not found (which results in `ENOENT` for example).

The issue is in `getOutput()`
https://github.com/cypress-io/cypress/blob/60b217cccedf28c56b0573665f0b3ee81813a4cc/packages/launcher/lib/utils.ts#L8-L40

When the `exit` event occurs it is not guaranteed that the stdio streams are closed.
- https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html#child_process_event_exit
- https://nodejs.org/dist/latest-v14.x/docs/api/stream.html#stream_event_close_1
- https://github.com/nodejs/node/pull/38181
- https://github.com/nodejs/node-v0.x-archive/pull/2944

According to the PR that introduced `getOutput()` (https://github.com/cypress-io/cypress/pull/7039)
> mysteriously, execa would hang on --version when used with the snap

To resolve the issue, Cypress could revert to using the `execa` package (assuming no breakage as mentioned in the PR) or update  `getOutput()` to ensure it fully reads the output.

---

As an example, for Chrome Cypress tries all of `google-chrome`, `chrome`, and `google-chrome-stable` by default.

https://github.com/cypress-io/cypress/blob/60b217cccedf28c56b0573665f0b3ee81813a4cc/packages/launcher/lib/browsers.ts#L7-L14

In the Cypress Docker images, only `google-chrome` and `google-chrome-stable` can be used to run Chrome; `chrome` does not work. This gives Cypress two tries to detect the browser. If running one binary fails to detect the browser because Cypress did not fully read the output, the opposite binary could still work. If the output is not read completely for both binaries then Cypress will conclude that Chrome is not installed. The issue is intermittent due to the timing related nature of the issue (sometimes stdout will have been fully read when the `exit` event occurs but sometimes it hasn't) and that Cypress may have to encounter the issue multiple times before detection of a single browser fails.

I have observed one of the two Chrome detections fail in the Docker container by running `cypress info` in an infinite loop.

---

I have observed the general issue when running Cypress intermittently with Cypress 6.x and Cypress 7.1.0.

You can see the issue with empty stdout in the provided logs
- https://github.com/cypress-io/cypress/issues/8611#issuecomment-733797690
- https://github.com/cypress-io/cypress/issues/15258#issuecomment-788029383

The earliest Cypress version I found this issue reported with is `4.12.0` (https://github.com/cypress-io/cypress/issues/9044). `getOutput()` was released in Cypress `4.4.1` (https://github.com/cypress-io/cypress/issues/7020#issuecomment-616743402)

---

Potential duplicate issues
- https://github.com/cypress-io/cypress/issues/9044
- https://github.com/cypress-io/cypress/issues/15258
- https://github.com/cypress-io/cypress/issues/15390

Potential obsolete issues
- https://github.com/cypress-io/cypress-docker-images/issues/451

**Comment by denis-domanskii** [comment] 2021-04-28 09:37
@pgfisico it's a great investigation, thank you!

@bahmutov @jennifer-shehane probably you can fix it? Seems now the fix is clear.

**Comment by bahmutov** [comment] 2021-05-03 20:02
ughh, @pgfisico I ran Chrome detection 1000 times in a row in a Docker container, did not see the empty output. Do you know how one could see the STDOUT still streaming after the `exit` event? I would love to recreate this behavior before changing the `getOutput()` function

**Comment by jennifer-shehane** [comment] 2021-05-05 16:31
We've merged a PR so that the verify process listens for the 'close' event instead of 'exit'. We're not sure if this solves this issue since we weren't able to recreate it. 

You can install the pre-release with the potential fix by following the [instructions here](https://github.com/cypress-io/cypress/commit/bdde38dbac64db654fe6677a56921293af5fd31f#commitcomment-50427256). Please let us know if this seems to fix the issue or not.

**Comment by jennifer-shehane** [comment] 2021-05-11 21:14
We released 7.3.0 with a change that we believe should fix this issue. This error should only display when Chrome is not installed on the system. 

Please comment in this issue if this error is still displaying in your Docker container with Chrome installed after updating to 7.3.0.

**Closed by jennifer-shehane** 2021-05-11 21:14 UTC
Labels: external: docker, pkg/launcher, stage: to do, type: bug

**Comment by mahdiMustapha** [comment] 2021-09-13 08:16
I had exactly same issue with version  : 8.3.0 .  any help please !

**Comment by AnnaKarinaNava** [comment] 2021-09-28 12:17
same problem here! Please any help or workaround would be appreciated.

This is random but very frequent it delay our pipelines a lot and probably would mean that in the end we'd stop using cypress

**Comment by AnnaKarinaNava** [comment] 2021-09-28 16:00
Please help! 

We are using cypress v7.6 and the situation is quite frequent for us still

**Comment by sabarishnarain** [comment] 2021-09-28 17:32
@AnnaKarinaNava The recommended workaround is to use the chrome/ff images and it appears it has worked out so far. I tried `cypress/browsers:node12.18.3-chrome89-ff86` now and it works fine. 

Thanks to the cypress team who appears to have addressed this issue. I'm not active over my personal projects now, but if anyone still sees this problem please feel free to re-open.

**Comment by kpturner** [comment] 2021-11-11 16:14
> @AnnaKarinaNava The recommended workaround is to use the chrome/ff images and it appears it has worked out so far. I tried `cypress/browsers:node12.18.3-chrome89-ff86` now and it works fine.
> 
> Thanks to the cypress team who appears to have addressed this issue. I'm not active over my personal projects now, but if anyone still sees this problem please feel free to re-open.

If I may say so that is not a very good description of how one is supposed to work around the problem.   I get this issue with 8.7.0 when using github-actions.  Where does one specify `cypress/browsers:node12.18.3-chrome89-ff86` ?

**Comment by derek-charles** [comment] 2021-11-30 23:17
Could a more uptodate image containing the most up to date version of chrome-stable be released so that the workaround can be utilized? The application that I have automation built for requires that the most recent version of chrome be used or else there is an error (This is for an internal application).  I am getting the " Browser: 'chrome' was not found on your system or is not supported by Cypress." error using cypress/base:16.5.0 docker image. 

The most recent chrome/ff image is for chrome version 94  (chrome94-ff93). I require chrome-stable 96 (my image retrieves the most recent chrome-stable version).

**Comment by joearinze** [comment] 2022-01-25 12:14
tried image: cypress/browsers:node14.15.0-chrome86-ff82 and it works fine now
