### ISSUE TITLE
Unable to open the Firefox browser 

### ISSUE THREAD

**Issue by Pradip6622** [cypress-io/cypress#22789] opened 2022-07-14 12:01 UTC
### Current behavior

![firefox consol](https://user-images.githubusercontent.com/100840712/178976123-6c1be241-b42a-4a2d-b59d-aa69713062c8.png)

### Desired behavior

I'm using the Windows system ( Windows 10.0.19044 )

Firefox browser version ( 102.0.1 (64-bit) )

### Test code to reproduce

N/A

### Cypress Version

10.1.0

### Other

After closing the Firefox choice again select any other browsers ( Chrome, Edge, electron ). it's doesn't work. must close the cypress to re-run in ( Chrome, Edge, electron ).
![cypre](https://user-images.githubusercontent.com/100840712/178977808-3feb6a2b-028d-4f0f-a9fe-edc7c3a3b948.png)

**Comment by iomedico-beyer** [comment] 2022-07-25 08:35
Same for Cypress 10.0.0.

With Cypress 9.7.0 I can at least run one test with Firefox before the same error message shows up.

**Comment by iomedico-beyer** [comment] 2022-07-25 09:13
I think this is a duplicate of [22086](https://github.com/cypress-io/cypress/issues/22086).

**Comment by tbiethman** [comment] 2022-07-26 20:34
@iomedico-beyer you are correct! I'm going to close this as a duplicate of https://github.com/cypress-io/cypress/issues/22086. For posterity, these connection issues with FF101/102 on Windows should be resolved with the FF103 release. Please log new issues for connection issues that persist in other environments.

**Closed by tbiethman** 2022-07-26 20:34 UTC
Labels: type: bug, E2E-core, stage: routed to e2e-core, stage: fire watch, priority: high
