### ISSUE TITLE
Report: MaxListenersExceededWarning is show if there are more then 10 tests

### ISSUE THREAD

**Issue by xlenz** [cypress-io/cypress#2566] opened 2018-10-05 14:31 UTC
### Current behavior:

(node:84837) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added. Use emitter.setMaxListeners() to increase limit

if using any custom reporter

### Desired behavior:

fix adding event listeners.
Most likely defect caused by amazing idea to run each test separately...

### Steps to reproduce:

1. Use mochawesome reporter (or any similar)
2. run 10 or more tests
3. see log

(node:84837) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added. Use emitter.setMaxListeners() to increase limit

You may use repo: https://github.com/xlenz/cypress-bugs
cypress run
and see logs

### Versions

Cypress 3.1.0

**Comment by lamkovod** [comment] 2018-10-05 14:53
Faced it too on Free version

**Comment by jennifer-shehane** [comment] 2018-10-09 19:49
Duplicate of https://github.com/cypress-io/cypress/issues/1305

I believe the warning may go away after following these instructions: https://github.com/cypress-io/cypress/issues/1305#issuecomment-425199598

**Closed by jennifer-shehane** 2018-10-09 19:49 UTC

**Comment by keeema** [comment] 2019-09-18 06:39
@jennifer-shehane 
Unfortunately all your suggestions about this problem, in all discussions, do not work and I have to disagree that warnings about memory leaks do not have any impact. The cypress team should seriously look on this problem because it is kind of "show-stopper" (...in using cypress for e2e testing).

**Solution (workaround)**
To successfully run all tests at once simply create one spec referencing all tests and run just this one _container_.

In my case, tests are written in typescript, so code example of _container_ file:
`
import "./someFolder/subFolder/loginTest.spec";
import "./someFolder/subFolder/otherTest.spec";
import "./someFolder/someOther.spec";
`

**Comment by jennifer-shehane** [comment] 2020-01-06 06:10
@keeema Please comment in the original issue in order to focus conversation in one place. Do not comment in duplicate issues, thanks. https://github.com/cypress-io/cypress/issues/1305
