### ISSUE TITLE
TS18002: The 'files' list in config file 'tsconfig.json' is empty with Cypress 10.0.0

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [cypress-io/cypress#22050] opened 2022-06-02 16:58 UTC
### Current behavior

We have an old cypress project running Cypress 9.5 version and uses support files that in typescript. The `tsconfig.js` looks like this 
```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": [
      "es5",
      "dom"
    ],
    "types": [
      "cypress",
      "cypress-wait-until"
    ]
  },
  "include": [
    "*/cypress/support/*.ts"
  ]
}
```

After upgrading to cypress 10.0.0, I am unable to run any of the tests and they fail with the following error.
```
Webpack Compilation Error
[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.
```

Any reason why that would happen and what should be added as part of the files property ? 

### Desired behavior

Upgrade to Cypress 10.0 should not cause any issues to the old projects

### Test code to reproduce

This is a setup/configuration problem not with the code.

### Cypress Version

10.0.0

**Comment by IrfanSyed-PSC** [comment] 2022-06-03 18:03
@flotwig  - It does not have tsconfig.json in the directory where cypress lives. Its only there in cypress/support where all the typescripts files are available

**Comment by IrfanSyed-PSC** [comment] 2022-06-03 18:36
This is my configuration 

<img width="206" alt="image" src="https://user-images.githubusercontent.com/4980960/171925794-dd39535e-a7e7-4be2-8a0e-ca518f6b3ad9.png">

**Comment by flotwig** [comment] 2022-06-06 14:28
@IrfanSyed-PSC this is indeed a duplicate of #18938 then, since you don't have a root tsconfig. Create a valid tsconfig.json at the root of your project and this should go away.

Closing as duplicate.

**Closed by flotwig** 2022-06-06 14:28 UTC
Labels: stage: awaiting response, v10.0.0 :bug:

**Comment by IrfanSyed-PSC** [comment] 2022-06-06 22:56
After doing the change, I see the following error. I am guessing it is because of this issue https://github.com/cypress-io/cypress-docker-images/issues/673. Please let me know if its not

![image](https://user-images.githubusercontent.com/4980960/172262456-85cf4184-cc6b-4b82-98b0-37f9bea72f65.png)

**Comment by RositaMunoz** [comment] 2023-01-26 14:43
Hi! I create the file `tsconfig.json` in the cypress folder with the content specified in this page https://docs.cypress.io/guides/tooling/typescript-support and worked fine

Hope it helps!

**Comment by kent** [comment] 2023-04-26 14:08
> Hi! I create the file `tsconfig.json` in the cypress folder with the content specified in this page https://docs.cypress.io/guides/tooling/typescript-support and worked fine
> 
> Hope it helps!

This worked for me. Looks like it was just looking for that file inside the directory.

**Comment by guilhermesimoes** [comment] 2023-07-24 10:18
> @IrfanSyed-PSC this is indeed a duplicate of #18938 then, since you don't have a root tsconfig. Create a valid tsconfig.json at the root of your project and this should go away.
> 
> Closing as duplicate.

This doesn't match [Cypress's documentation](https://docs.cypress.io/guides/tooling/typescript-support) which states:

> We recommend creating a [tsconfig.json](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) **inside** your [cypress folder](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-Structure)

**Comment by thevelvetsnow** [comment] 2023-11-29 15:49
I had the same problem, and I just did the same thing as @kent and it worked, thank you.

Create tsconfig.json within Cypress and follow the official doc https://docs.cypress.io/guides/tooling/typescript-support
