### ISSUE TITLE
Cypress Headless mode does not exit after crashed browser

### ISSUE THREAD

**Issue by EtienneBruines** [cypress-io/cypress#6974] opened 2020-04-09 09:38 UTC
### Current behavior:

Whenever the browser crashes (any reason), or is exited (any reason), the cypress process itself keeps alive. 

This is a general problem as described in #6501, #6695, and #4434. 
The focus of those issues has been figuring out *why* the browser crashed. 
I want this issue to solely be about Cypress' behavior when that occurs. 

The issue: the Cypress process keeps running, does not exit with a non-0 exit code. 

It does show that the automation browser has disconnected and that the test cannot continue, but that does keep my CI tests running indefinitely :wink: 

### Desired behavior:

Especially in CI environments, if the browser crashes, the test has failed and the Cypress-process should exit with a non-0 exit code. 

If the browser exists (in headed mode, by closing the window), a non-0 exit code might also be desirable. 

### Test code to reproduce

Crashing Firefox tutorial 101 :see_no_evil: 

`reproduce.html`
```html
<!doctype html>
<html lang="en">
<head></head>
<body>
<input type="file">
<script>
document.getElementsByTagName('input')[0].click()
document.getElementsByTagName('body')[0].innerText = 'Done'
</script>
</body>
</html>
```

`file_dialog_spec.js`
```js
describe('File Dialog', () => {
  it('does not crash the browser', () => {
    cy.visit('./cypress/fixtures/reproduce.html')
    cy.contains('Done')
  })
})
```

Now run this in headless Firefox. 

### Versions

Cypress: 4.3.0 (and earlier versions)
OS: Linux
Browser: Any browser

**Comment by jennifer-shehane** [comment] 2020-04-10 08:08
Duplicate of #6170 - there is an existing PR to address this that is WIP here https://github.com/cypress-io/cypress/pull/6189

**Closed by jennifer-shehane** 2020-04-10 08:08 UTC
