### ISSUE TITLE
webpack-preprocessor:  dependent on a pinned version of @babel/parser but not @babel/core

### ISSUE THREAD

**Issue by alaingiller** [cypress-io/cypress#24923] opened 2022-12-01 16:55 UTC
### Current behavior

Hi,

The webpack-preprocessor use a (very old) pinned version of @babel/parser, but not of @babel/core:
https://github.com/cypress-io/cypress/blob/develop/npm/webpack-preprocessor/package.json#L24

Both should use "^7.0.1" or at least to allow patch version.

This break our pipeline because the version 7.13.0 is considered too old and there is a lot of patches and minor version since then.

### Cypress Version

11.2.0

### Node version

14.20.1

### Package Manager

npm

### Package Manager Version

8.19.3

### Operating system

Linux

### Operating System Version

ubuntu 22.04

**Comment by alaingiller** [comment] 2022-12-05 13:31
The current solution for us is to add this in the package.json:
```
    "overrides": {
        "@cypress/webpack-preprocessor": {
            "@babel/parser": "~7.13.0"
        }
    },
```
This will simply add the missing ~ to the dependency inside @cypress/webpack-preprocessor. 
In fact the `^` works also

**Comment by nagash77** [comment] 2022-12-05 19:06
Closing as a duplicate of https://github.com/cypress-io/cypress/issues/24768. Please follow along on that issue for updates on status.

**Closed as not planned by nagash77** 2022-12-05 19:06 UTC
Labels: topic: installation
