### ISSUE TITLE
Test fails randomly

### ISSUE THREAD

**Issue by damms005** [cypress-io/cypress#27152] opened 2023-06-28 01:41 UTC
### Current behavior

My test fails randomly and unpredictably with a blank screen. When it fails, it is always at the same step: when submitting the registration form -- Cyrpess display window simply shows a blank screen instead of loading the registration confirmation page, as shown in screenshots below.

In an attempt to try to debug it, I opened Cypress, opened dev tools, and ran the test several times to reproduce the failure. When the failure happens, I checked the network tab in dev tools and noticed that the confirmation page response is not what my app returned, but some (Cypress?) injected code/response that includes:

> throw new Error("Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.");

The screenshot is also shown below.

![Registration -- user can register (failed)](https://github.com/cypress-io/cypress/assets/9839355/f99ebc25-ca17-4644-8577-23e45d012367)

![image](https://github.com/cypress-io/cypress/assets/9839355/4b8303e7-6b4b-4ca8-8f42-635096ffd5c5)

### Desired behavior

My test should not fail randomly with a response of JavaScript that contains:

> Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue

### Test code to reproduce

Failing test code:
```
import { faker } from '@faker-js/faker';

describe('Registration', () => {
	it('user can register', () => {
		// Login
		cy.visit('/register')
		cy.get("[name=firstname]").type(faker.name.lastName().substring(0, 3))
		cy.get("[name=middlename]").type(faker.name.firstName().substring(0, 3))
		cy.get("[name=lastname]").type(faker.name.lastName().substring(0, 3))
		cy.get("#email").type(faker.internet.email())
		cy.get("#contact_number").type('12345')
		cy.get("#password").type('Pass2020')
		cy.get("#password_confirmation").type('Pass2020')
		cy.get("[data-cy=specializations]").find('input[type=checkbox]').eq(1).click()
		cy.get("[data-cy=specializations]").find('input[type=checkbox]').eq(2).click()
		cy.get('button[type=submit]').click()
		cy.url().should('include', '/verify-email')
		cy.contains('Thanks for signing up').should('exist')
	});
});
```

> The app code is a standard Laravel auth scaffold ([Laravel Breeze](https://github.com/laravel/breeze))

### Cypress Version

12.16.0

### Node version

v20.3.0

### Operating System

Zorin OS 16.2

### Debug Logs

```shell
Pasting the whole debug log here made the issue payload more than GitHub limit. So, used gist instead: https://gist.github.com/damms005/86b05fa40aa51a891b1db6ddbaebfed0
```

**Comment by tester-at-bmi** [comment] 2023-06-28 07:55
You say it fails on random? So sometimes the test do succeed?

That means you probably need to increase your timeouts in your cypress config.

You can play with these yourself

```
defaultCommandTimeout: 15000, 
requestTimeout: 15000, 
responseTimeout: 60000, 
```

**Comment by damms005** [comment] 2023-06-28 09:18
Thanks for taking time to look into this, @tester-at-bmi. I've played with these timeouts but it still fails randomly. This is how much I have debugged this so far when it fails:

1. It is not a timeout issue (explained above)
2. Instead of my app's auth registration response from the endpoint, a JavaScript code is being returned as described above (with content: `Something went terribly wrong and we cannot proceed...Please open an issue`)
3. Since it is a Laravel app, I logged at some points in the app lifecycle (`AppServiceProvider` and in the controller) and noticed that my app did not log anything, meaning the request did not hit my app

**Comment by mike-plummer** [comment] 2023-06-28 14:25
@damms005 From what I see in your screenshots that error isn't actually getting thrown, it's just part of the logic that Cypress sends back to run in the browser. If that error _were_ thrown it would appear in the reporter column on the left.

Is there anything reported in the DevTools console that might indicate a client-side error? The fact that your form submission is returning the full Cypress response indicates it may be escaping the iframe we use to encapsulate the application under test. Is it possible you have any frame-busting code in your application that might be causing issues on the form submission? The fact that your expected service endpoint isn't being hit makes me wonder if you have an `intercept` that is behaving in unexpected ways

In order to troubleshoot this issue it would be much easier if you could share a full reproduction case - is this site hosted somewhere that would allow us to run the test ourselves?

**Comment by damms005** [comment] 2023-06-29 03:51
I understand that the error is not thrown. I thought it is noteworthy to mention that the response is just that script.

Per reproduction, it is a private GitHub repo, but I can send you an invite if that's okay.

**Comment by lmiller1990** [comment] 2023-07-06 01:40
Hi, sorry to see you running into a reliability issue. Let's debug it. I'll pick this up.

I'm going to pick this issue up, but I'm going to need a public reproduction. It's too difficult to debug and triage issues on our public tracker when a public reproduction is not available. In addition, more eyes is better, lots of other people know Laravel (I don't know PHP well), and Cypress well, they could also help out.

**Comment by damms005** [comment] 2023-07-06 07:40
@lmiller1990 what are my options, please?

While I've obviously gone past this issue (by removing the last assertion that's causing all these), I believe it'll be helpful to the community if the root cause is fixed.

I can invite as many persons as required to the repo though.

**Comment by lmiller1990** [comment] 2023-07-06 22:35
Sure, go ahead and invite me - v-lachlan@cypress.io.

It'd be far more ideal to make the repo public - is there some sensitive information? What's preventing a public reproduction? This is public issue tracker, after all. I don't want access to a production project with sensitive information. I don't have the bandwidth to debug a large, complex production project - is your reproduction a minimal project, or a larger one?

Ultimately, to fix this, we will need a minimal reproduction that we can add to our test suite here, so some public code is needed at some point. If you can make something public that contains a minimal reproduction without any sensitive material, **that would be far more ideal**.

Options:

1. invite me and I'll try to help - I left my email above - but be aware I'm only one person with so many hours in a day. I cannot guarantee I'll get to it in a timely fashion. If it's a complex project, I won't be able to debug it faster than you.
2. make a minimal public repo - anyone at Cypress, and beyond, can help debug it. **This is vastly preferred and likely the only way you will get a fix** - there are already other community members in this thread trying to help, but they can't because they do not have access to the reproduction.

**Comment by lmiller1990** [comment] 2023-07-12 04:46
I did not get an invite or see a public repro. I can reopen once we have more information. For now, there isn't anything we can do, so I'm going to close this - the goal is to only have issues open that we can actively triage and work on, and until there's a reproduction, this isn't one of them.

**Closed as completed by lmiller1990** 2023-07-12 04:46 UTC
