### ISSUE TITLE
failed to make a connection to the CDP after retrying for 20 seconds. 

### ISSUE THREAD

**Issue by ssravanthi86** [cypress-io/cypress#6418] opened 2020-02-11 14:55 UTC
Issue: 
Current behavior:

I recently upgraded to cypress 4.0.0 and when i try to run my test i see the below error
i tried with chrome, electron as well as firefox but no luck
<img width="803" alt="Screenshot 2020-02-11 at 14 46 41" src="https://user-images.githubusercontent.com/60931139/74247347-d1d37100-4cdd-11ea-8315-39d12ab7896c.png">

below is the debug log 

<img width="1069" alt="Screenshot 2020-02-11 at 14 53 07" src="https://user-images.githubusercontent.com/60931139/74247659-4dcdb900-4cde-11ea-8ea6-f209b184ab0d.png">

**Comment by jennifer-shehane** [comment] 2020-02-12 10:31
@ssravanthi86 Did you have 2 Cypress Apps running? Like, calling `cypress open` in one tab and `cypress open` in another tab?  If so, this is a duplicate of https://github.com/cypress-io/cypress/issues/5613

Do you have a plugin or extension that is using the CDP port? Something like `--remote-debugging-port=19222` flag passed to Chrome?

**Comment by jennifer-shehane** [comment] 2020-02-18 07:09
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed by jennifer-shehane** 2020-02-18 07:09 UTC
Labels: stage: needs information

**Comment by DrNio13** [comment] 2021-06-11 14:23
Is it possible to run cypress tests with "custom" Electron Browser? https://docs.cypress.io/guides/guides/launching-browsers#Electron-Browser

Basically [downloading and starting the Electron Starting Guide example](https://www.electronjs.org/), build the binaries for example /out/electron-quick-start-win32-x64/electron-quick-start.exe and link that Electron Browser to Cypress Browsers list to execute the tests.

I tried with latest Cypress and Electron starting guide and got the same connection issue.
