### ISSUE TITLE
Cypress doesn't load all button content on my Website during the test

### ISSUE THREAD

**Issue by m-aouainia** [cypress-io/cypress#25529] opened 2023-01-20 15:21 UTC
### Current behavior

Hi Everyone, 
I test a Website which have a dynamic Login button with type='button' after clicking on this button I should be 
forwarded to Login Page. BUT this is not the case, the Login button is displayed and clickable but without BE. Means will be not forward me to Login page. 
I checked the problem, I found that the Login button is loaded but without content. Now I tried to check if in Normal Browser without Cypress ui , if is it the same or not. The result isn't the same, the button is loaded in Cypress without  BE content BUT manully in Normal Browser is loaded as expected and after clicking of Login button is forward me to Login page.
Could someone please help ? Thanks
Info: Login Button is displayed on the Main page !

### Desired behavior

Login Button **content** should be loaded when the page is loaded.
![Screenshot 2023-01-20 161447](https://user-images.githubusercontent.com/113613762/213733212-15f7e14e-011c-4a73-8979-a91f4fa4eaf7.png)

### Test code to reproduce

the code was successfully running but as I described above after clicking I am not forwarded to other page (login page).

### Cypress Version

v12.3.0

### Node version

16.16.0

### Operating System

Windows 11

**Comment by nagash77** [comment] 2023-01-23 19:44
Hi @m-aouainia , I'm sorry to hear you are having issues using Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by ZachJW34** [comment] 2023-01-30 15:57
Closing due to inactivity. Feel free to respond with a reproduction and we can investigate this issue further.

**Comment by m-aouainia** [comment] 2023-02-01 08:31
@nagash77 I sent already the path and all infos per Email. please check . Thanks !

**Comment by nagash77** [comment] 2023-02-01 18:05
@m-aouainia my apologies for this getting lost in the shuffle.  I have reopened this issue and forwarded the information to the team to take a look.

**Comment by warrensplayer** [comment] 2023-02-01 20:39
@m-aouainia I looked over the email you sent.  Thanks for sharing a description of the scenario you are trying to test and the screenshot.  Are you able to share the actual test file you are using as well as your `cypress.config.js` file for your project?  You can add them to a message in this project or respond to the same email you sent.  That would help to accurately reproduce your issue.

**Comment by warrensplayer** [comment] 2023-02-03 17:45
@m-aouainia Thanks for sharing your `cypress.config.js` and your test code.  I had to add the following to my `cypress/support/e2e.js` file to get past all the errors happening on that page when run through Cypress:
```
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  })
```
Did you have to do the same?  

I am able to reproduce the issue, but not sure what is happening yet.  Can you share or just explain the code that drives the click handler for that Login button.  I can see when going to the page outside of Cypress that it forwards the browser to another website for Login.  My guess is that the code that powers this is not loading correctly when run via Cypress.  Is this code pulled in from a cross origin domain?

**Comment by marktnoonan** [comment] 2023-02-20 21:34
Hi @m-aouainia, I'd like to pick this up to investigate a little more, before I dive in could you respond to the question above?

>Can you share or just explain the code that drives the click handler for that Login button. I can see when going to the page outside of Cypress that it forwards the browser to another website for Login. My guess is that the code that powers this is not loading correctly when run via Cypress. Is this code pulled in from a cross origin domain?

Many thanks.

**Comment by m-aouainia** [comment] 2023-02-22 08:09
> @m-aouainia Thanks for sharing your `cypress.config.js` and your test code. I had to add the following to my `cypress/support/e2e.js` file to get past all the errors happening on that page when run through Cypress:
> 
> ```
> Cypress.on('uncaught:exception', (err, runnable) => {
>     // returning false here prevents Cypress from
>     // failing the test
>     return false
>   })
> ```
> 
> Did you have to do the same?
> 
> I am able to reproduce the issue, but not sure what is happening yet. Can you share or just explain the code that drives the click handler for that Login button. I can see when going to the page outside of Cypress that it forwards the browser to another website for Login. My guess is that the code that powers this is not loading correctly when run via Cypress. Is this code pulled in from a cross origin domain?

Thanks for answer. I think I sent you all what I have !

**Comment by marktnoonan** [comment] 2023-02-22 23:27
Ah I see, ok, I've taken a closer look at what you sent. Let's follow up on email so we can speak about the details of the private code.

**Comment by warrensplayer** [comment] 2023-05-09 16:49
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Closed as completed by warrensplayer** 2023-05-09 16:49 UTC
