### ISSUE TITLE
error in dashboard 

### ISSUE THREAD

**Issue by maximilianofni** [cypress-io/cypress#17217] opened 2021-07-06 21:29 UTC
![chrome_SkY8fLVyvs](https://user-images.githubusercontent.com/17895688/124668864-de82d700-de87-11eb-8d1b-2c3fb6c692b9.png)

![chrome_6okFuRXwc1](https://user-images.githubusercontent.com/17895688/124668960-fe19ff80-de87-11eb-8cde-e4a3c88c7e98.png)

**Comment by finnstech** [comment] 2021-09-14 14:18
Please add steps to reproduce, thank you!

**Comment by jennifer-shehane** [comment] 2022-04-08 20:03
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Closed by jennifer-shehane** 2022-04-08 20:03 UTC
Labels: external: dashboard
