### ISSUE TITLE
get() inside should() with callback applies default assertion

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#5963] opened 2019-12-15 09:22 UTC
### Current behavior:

Using `get().should(not.exist)` inside should with callback applies default `exist` assertion.

![image](https://user-images.githubusercontent.com/3234900/70860669-c7d30300-1f24-11ea-884a-1ba8e99d6133.png)

### Desired behavior:

`should` will skip the default 

### Steps to reproduce: (app code and test code)

Use this example:

```js
describe("ad", () => {
    it("test", () => {
        cy.visit("https://www.cypress.io/")
        cy.get("*[aria-label='pricing']")
            .invoke('text').should(someValue => { 
                cy.get("asdad", {timeout: 5000}).should("not.exist");
            })
    })
})
```

The element "asdad" does not exist  but even though cypress fails while applying the default asertion.

### Versions

Cypress 3.8.0

**Comment by jennifer-shehane** [comment] 2019-12-16 05:07
Confirmed this behavior.

## `.should()` chaining

```js
it('test', () => {
  cy.visit('https://www.cypress.io/')
  cy.get('h1').should(() => {
    cy.get('asdad').should('not.exist') // fails incorrectly
  })
})
```

<img width="448" alt="Screen Shot 2019-12-16 at 11 37 22 AM" src="https://user-images.githubusercontent.com/1271364/70880738-75fbad00-1ff8-11ea-93af-bee9d3b03e46.png">


## `.then()` chaining

```js
it('test', () => {
  cy.visit('https://www.cypress.io/')
  cy.get('h1').then(() => {
    cy.get('asdad').should('not.exist') // passes correctly
  })
})
```

<img width="449" alt="Screen Shot 2019-12-16 at 11 36 59 AM" src="https://user-images.githubusercontent.com/1271364/70880719-654b3700-1ff8-11ea-9a11-08dbeb59db52.png">

**Comment by gabbersepp** [comment] 2019-12-16 16:30
Hey,
T tried to dive deeper into the cypress internals to fix this bug. I found the line `isDefaultAssertionErr = cmds.length is 0` in `assertions.coffee` that seems to control wether the default assertions are applied. But I found no place in the `driver` package that makes use of this information. Maybe you can give me a little hint where I can find the correct place?

**Comment by emilyrohrbough** [comment] 2022-11-16 22:08
https://github.com/cypress-io/cypress/pull/23734 made a breaking change to now throw an error if Cypress commands are invoked from inside a `.should()` callback since this resulted in unusual and undefined behavior.

Closing this issue since this is no longer relevant.

**Closed by emilyrohrbough** 2022-11-16 22:08 UTC
Labels: type: bug, pkg/driver, stage: needs investigating
