### ISSUE TITLE
Failure to start Cypress from VS Code Editor terminal

### ISSUE THREAD

**Issue by hemssam** [cypress-io/cypress#5457] opened 2019-10-24 21:48 UTC
I am new to Cypress. I installed a newer version of node.js and installed cypress 3.4.1 version. Also installed Visual studio code editor and using the terminal tab on the code editor I am trying to open cypress using `.\node_modules\.bin\cypress open` i get the following error:

```
PS C:\Users\samh01\Cypress> .\node_modules\.bin\cypress open
It looks like this is your first time using Cypress: 3.4.1

 ×  Verifying Cypress can run C:\Users\samh01\AppData\Local\Cypress\Cache\3.4.1\Cypress
   → Cypress Version: 3.4.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

spawn UNKNOWN

----------

Platform: win32 (10.0.17134)
Cypress Version: 3.4.1
PS C:\Users\samh01\Cypress> set NODE_OPTIONS=
PS C:\Users\samh01\Cypress> cypress run
cypress : The term 'cypress' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cypress run
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cypress:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\samh01\Cypress> .\node_modules\.bin\cypress run
It looks like this is your first time using Cypress: 3.4.1

 ×  Verifying Cypress can run C:\Users\samh01\AppData\Local\Cypress\Cache\3.4.1\Cypress
   → Cypress Version: 3.4.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

spawn UNKNOWN

----------

Platform: win32 (10.0.17134)
Cypress Version: 3.4.1
```

I tried clearing the cache  and unsetting the `NODE_OPTIONS`. Nothing works.

**Comment by jennifer-shehane** [comment] 2019-10-25 15:08
Hey @hemssam, can you try:

1. Updating to our latest 3.5.0 release - see what happens when you run that.
2. Running `.\node_modules\.bin\cypress run` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here.

**Comment by hemssam** [comment] 2019-10-25 17:06
Hi Jennifer,

Tried the newer version and i still see the same error. Also tried option 2
and please see the output below:
[image: image.png]

Thanks
Hema

**Comment by suhasch12** [comment] 2019-12-04 14:07
Hi,
I'm facing the same error code when I try to run on VS
 CategoryInfo          : ObjectNotFound: (.\node_modules\.bin\cypress:String) [], CommandNotFoundException

can anyone help me on this issue
many thanks, Suhas

**Comment by maxime-aubry** [comment] 2020-06-16 07:58
I have the same bug

**Comment by jennifer-shehane** [comment] 2020-06-16 08:01
@hemssam It doesn't look like you attached any output. Can you provide the DEBUG output?

**Comment by RashmiKalpeshChauhan** [comment] 2020-06-23 15:22
I faced this problem many times. 
The easiest way to fix this problem is-
1. Delete Cache which u will get "AppData\Local\Cypress\Cache" of your machine.
2. Delete node_modules from the project folder.
3. Then again install cypress -npm install cypress

The problem is fixed now :)

**Comment by skumar31** [comment] 2020-07-08 16:46
Thanks Rashmi
It works fine.

**Comment by krishnasan99** [comment] 2020-07-20 03:06
I Tried This Working Fine.
==================
Open Windows PowerShell with Run as Administrator then run with below command.

Set-ExecutionPolicy RemoteSigned

Yes

Now go to VSCode. and run

> node_modules/.bin/cypress open

Cypress Runs. you can see as Verified Cypress!

**Comment by smithapatil14** [comment] 2020-09-29 22:46
Thanks Rashmi, your solution worked for me.

**Comment by jennifer-shehane** [comment] 2020-11-04 05:23
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Closed by jennifer-shehane** 2020-11-04 05:23 UTC
Labels: stage: awaiting response
