### ISSUE TITLE
Problem with dashboard reporting

### ISSUE THREAD

**Issue by haleagar** [cypress-io/cypress#2678] opened 2018-10-30 12:40 UTC
### Current behavior:
Recording test runs to the Dashboard has become problematic since adding paid dashboard service.
multiple seemingly random tests report this error.
https://dashboard.cypress.io/#/projects/cwb5ky/runs/39/specs

```
Warning: We encountered an error talking to our servers.
This run will not be recorded.
This error will not alter the exit code.
StatusCodeError: 400 - "Cannot complete same instance multiple times"
```

and towards the end of the run the dashboard just gives up and all further tests return an error like this  (per file)
```
Warning: We encountered an error talking to our servers.
This run will not be recorded.
This error will not alter the exit code.
StatusCodeError: 400
{
  "message": "Cannot find unclaimed instance for spec: cypress\\integration\\ci\\components\\ex\\step4-fieldValidation-securityAnswer.feature"
}
```

### Desired behavior:
Test results are recorded.

### Steps to reproduce:
command line test run
```
node_modules/.bin/cypress run --spec 'cypress/integration/ci/components/**/*' --record --key xxx
```

### Versions

CI: local run in GitBash shell
OS: Windows 10
Browser: Electron 59.0.3071.115
Cypress: v3.1.0

using plugin: cypress-cucumber-preprocessor 1.5.1

(similar issues found by my college using osx)

**Comment by jennifer-shehane** [comment] 2018-10-30 23:33
Spent some time investigating this as this should not happen.

It looks as if your CI process crashed or was killed at some point during the run - which does not excuse the unhandled error from happening.

The `spec` received by the API is `cypress\\integration\\ci\\components\\ex\\step4-fieldValidation-securityAnswer.feature` which is a messed up path format so the API cannot find the "unclaimed instance" because the `spec` is properly stored as `cypress\integration\ci\components\ex\step4-fieldValidation-securityAnswer.feature`. 

This is an issue in this repo, not the API. 

We feel pretty strongly that this is likely a Windows issue, but I know you mentioned another colleague having the same issue on OSX. Can you verify this is the exact error that your colleague is also getting when run on OSX?

**Is there anything else you could share about your setup to help us track this down?**

**Comment by haleagar** [comment] 2018-11-01 19:03
When you say "your CI process crashed" do you mean on the cypress dashboard or the node cypress task I'm running.  The local test run continues even with the error.

Trying again using a different command line.   The tests still encounter the same error but it stops the local cypress test run and I can then start it again and it picks up where it left off.

Command line 
node_modules/.bin/cypress run --spec "cypress/integration/ci/components/**/*" --record --key f3230691-58fd-4a68-9a0d-9ceb252be8e6 --group desktop --parallel --ci-build-id local-docker20181101

received error

 (Uploading Results)

We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --group flag you passed was: desktop
The --ciBuildId flag you passed was: local-docker20181101

The server's response was:

StatusCodeError: 400 - "Cannot complete same instance multiple times"


https://dashboard.cypress.io/#/projects/cwb5ky/runs/41/specs

**Comment by amirrustam** [comment] 2018-11-01 19:22
@haleagar are you reusing your `ci-build-id`: `local-docker20181101`?

**Comment by haleagar** [comment] 2018-11-01 19:44
It's never run simultaneously, only one instanced in one console.
I did re-use it to try and restart the run/recording after that error, and it did pick up at the next test.
However it also encountered the same error and the dashboard run timed out before I tried another restart.

Might this have anything to do with a long test run?  I expect the total run time would be 1.5hr if it were to be able to complete.

**Comment by amirrustam** [comment] 2018-11-02 00:09
The `ci-build-id` flag can *only be used once for a project*. It is a unique identifier that associates multiple machines together to manage parallelization and/or grouping.

When using one of the out-of-the-box support CI providers, this `ci-build-id` is auto-determined for you. However, when running tests locally the management of the `ci-build-id` is left up to you. While parallel tests can technically run on a single machine, we do not recommend it since this machine would require significant resources to run your tests efficiently.

The duration of your run shouldn't really be an issue, but it is atypical. There might be something about your local system. Some questions:

1. Are you able to run your tests fine locally without parallelization or grouping?

**Comment by haleagar** [comment] 2018-11-02 14:50
I understand ci-build-id, if you look at the original post I was NOT using it and get the same errors.
I have in the past run multiple consoles on my system using the same ci-build-id and it worked as expected with the dashboard handing out scenarios to each.

However now regardless of if if it's a single or multiple cypress test runners I get complaints from the dashboard.    The only difference is if I do not use --parallel the test continue to run just fine locally.
All test run, no problems or errors other than the dashboard complaints.

I also saw a note in the linked ticket that it could be related to path management in GitBash, so I tried a run on windows command prompt but got the same complaint from the dashboard

**Comment by amirrustam** [comment] 2018-11-02 17:38
I was unable to replicate the issue on Windows 10. I also tested with GitBash. I used our base kitchen-sink tests which we initialize empty projects with when running cypress for the first time.

Please try recording a new fresh project using our kitchen sink tests. The goal here is to try to see if your actual tests are contributing to the issue.

**Comment by haleagar** [comment] 2018-11-02 19:20
Same results OSX sienna.   
Different test with error each time.
https://dashboard.cypress.io/#/projects/cwb5ky/runs/43/specs

I'll try to create a new project and reproduce.

**Comment by jennifer-shehane** [comment] 2018-12-07 18:22
Going to close this as duplicate of https://github.com/cypress-io/cypress/issues/2469

**Closed by jennifer-shehane** 2018-12-07 18:22 UTC
Labels: type: duplicate
