### ISSUE TITLE
Angular Material 1.x issues

### ISSUE THREAD

**Issue by peio72** [cypress-io/cypress#2204] opened 2018-07-24 10:14 UTC
We have random errors using Angular Material 1.x  (https://material.angularjs.org/) and Cypress 3.0.2:

```
CypressError: Timed out retrying: Expected to find element
```

using `cy.get()`.

Sometimes elements are found sometimes they are not ...

Any idea how to fix or use Cypress successfully with Angular Material ?

**Comment by Bkucera** [comment] 2018-07-30 17:48
Hi @peio72 , 
I think a lot of these issues could be fixed by the `3.0.3` release, but I'll need more info about which components are unable to be tested.



Can you give some examples of breaking tests? for example: ```
  it('works', () => {
    cy.visit('https://material.angularjs.org/latest/demo/datepicker')
    
    cy.get('.md-datepicker-input').first()
    .parent()
    .find('button').first()
    .click()

    cy.get('[aria-label="Friday November 6 2009"]').click()

    cy.get('.md-datepicker-input').eq(0).should('have.value', '11/6/2009')
  })
```

**Comment by nikhilesh009** [comment] 2018-10-08 13:52
i am using Angular 1.5 , Angular Material 1.1.5
I am facing the same issues, getting random error "cypress test fails because elements covered" or time out unable to find element even though element visible , It doesn't make sense because sometime its work.
most of the time test pass but it fail sometime. mainly it fail on drop down (md-select),
(md-autocomplete)

**Comment by Bkucera** [comment] 2018-10-09 15:37
@nikhilesh009 does it always pass headlessly in cypress run mode?

**Comment by nikhilesh009** [comment] 2018-10-09 15:41
@Bkucera No, it doesn't 
in browser it pass most of the time but when i run headless it pass very few times.

**Comment by Bkucera** [comment] 2018-10-09 15:43
@nikolalsvk can you see if window focus affects the test? e.g. launch the test in open mode, right after the test starts focus on another window (clicking on your code editor, for example)

**Comment by cdorman** [comment] 2018-10-18 18:01
I don't want to dilute the issue currently being discussed, but I'm having a different issue.  When I have a `$mdDialog.confirm()` dialog set with `.multiple(true)` (because it's opening over a custom dialog, also set with `.multiple(true)`), clicking on either button (to cancel or confirm) closes both dialogs.

In the course of troubleshooting this, I have confirmed that:
- there is only one element in the DOM that matches the associated `cy.get()`
- the `cy.get()` returns only that single element
- if I stop the script prior to either button being clicked and click on either button manually in the viewport, the correct behavior is exhibited (only the top dialog is closed)
- I get similar failures regardless of whether I `open` or `run` cypress

If anyone has any suggestions on how to continue troubleshooting this, or can confirm whether this is a known issue, I would appreciate it.

**Comment by Bkucera** [comment] 2018-10-19 20:56
@cdorman it's possible that there's an internal handler on the dialog that gets triggered because Cypress is clicking very soon after the dialog is loaded. Try adding a `cy.wait` and see if that solves the issue

**Comment by cdorman** [comment] 2018-10-19 22:40
@Bkucera Good call; a `cy.wait()` did the trick.  Thanks!

**Comment by jennifer-shehane** [comment] 2019-04-25 06:37
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Closed by jennifer-shehane** 2019-04-25 06:37 UTC
Labels: pkg/driver, stage: needs information

**Comment by rpkinfomedia** [comment] 2022-05-19 23:38
Hoping to help anybody who come here. This SFO question looks very similar https://stackoverflow.com/questions/53854954/closing-an-angular-material-dialog-in-cypress. And this answer https://stackoverflow.com/a/53859372/5107365 - did really help me to work around the problem.
