### ISSUE TITLE
Unable to have larger videos and screenshots (Windows CI)

### ISSUE THREAD

**Issue by jvanoostveen** [cypress-io/cypress#14430] opened 2021-01-06 13:58 UTC
### Current behavior
The videos recorded and the screenshots taken are too small (1024x768) and do not provide readable text making it hard to give any useful info about the error.

I've tried all sorts of config and ended up with the 'official' config but nothing seems to effect.

Cypress is done on Windows build machines in Electron (default).

Below my complete `before:browser:launch` config, although only the `isHeadless` > `electron` part is being hit.
```js
/**
 * @param {Cypress.PluginEvents} on
 * @param {Cypress.PluginConfigOptions} config
 */
module.exports = (on, config) => {
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.family === 'chromium') {
      launchOptions.args.push('--force-prefers-reduced-motion');
    }

    if (browser.isHeadless) {
      let width = 1440;
      let height = 1200;

      if (browser.family === 'chromium') {
        launchOptions.args.push(`--window-size=${width},${height}`);
        launchOptions.args.push('--force-device-scale-factor=1');
      }

      if (browser.name === 'electron') {
        launchOptions.preferences.width = width;
        launchOptions.preferences.height = height;
      }

      if (browser.name === 'firefox') {
        launchOptions.args.push(`--width=${width}`);
        launchOptions.args.push(`--height=${height}`);
      }
    }

    return launchOptions;
  });
};
```
Any suggestions or ideas?

### Desired behavior
Larger size videos and screenshots! 😄 

### Versions
Cypress 6.2.1
Electron (embedded)
Windows 10
Azure DevOps

**Comment by jennifer-shehane** [comment] 2021-01-07 08:07
I think there may be a limitation for ffmpeg size, which some people have detailed workarounds to in this issue: https://github.com/cypress-io/cypress/issues/587

Closing as duplicate of https://github.com/cypress-io/cypress/issues/587 - Having this more easily configurable will help solve these complicated workarounds.

**Closed by jennifer-shehane** 2021-01-07 08:07 UTC
