### ISSUE TITLE
cypress studio doesn't support contenteditable input

### ISSUE THREAD

**Issue by ed-jinyoung-park** [cypress-io/cypress#27634] opened 2023-08-23 05:38 UTC
### Current behavior

click contenteditable area and typing text doesn't record input event ``type``

### Desired behavior

generate a call to .type() to enter text in ``contenteditable`` element, in the same way that <input type="text"> works

### Test code to reproduce

application:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
  </head>
  <body>
    <div contenteditable="true">
    </div>
  </body>
</html>
```

### Cypress Version

v12.2.0

### Node version

v16.16.0

### Operating System

macOS 13.3.1

### Other

same issue with https://github.com/cypress-io/cypress/issues/25941

**Comment by nagash77** [comment] 2023-08-23 13:35
Hi @ed-jinyoung-park as you indicated this is a duplicate of #25941.  I am going to close this issue as a duplicate.  Please follow the other issue for any updates.

**Closed as not planned by nagash77** 2023-08-23 13:35 UTC
