### ISSUE TITLE
Powerapps authentication problem

### ISSUE THREAD

**Issue by ieZaky** [cypress-io/cypress#23188] opened 2022-08-08 07:40 UTC
### Current behavior

Using v10.4.0, there was a new feature added which is: experimentalModifyObstructiveThirdPartyCode. Using this feature, I could authenticate the Microsoft login normally using username and password. However, after logging in and being redirected to powerapps, It shows a blank page where Powerapps does not sense that am an authenticated user at all. I even checked the application storage and it did contain my token and it showed that am an authenticated user so why powerapps behaving in such a way? (Also am new with Cypress and its first time to use Cypress with Powerapps so if there are missing data or info to be provided just let me know please) Thanks a lot!

### Desired behavior

To be redirected to my application home page with authenticated user.

### Test code to reproduce
```
describe('POC', () => {
  Cypress.on('uncaught:exception', (err, runnable) => {
    return false;
  });
  
  it('passes', () => {
    cy.origin('https://login.microsoftonline.com/', () => {
      cy.visit('https://organization_name.crm4.dynamics.com/main.aspx');
      cy.get('[name="loginfmt"]').should('be.visible').type("Email here").click();
      cy.get('[name="passwd"]').should('be.visible').type("Password here").click();
      cy.get('[type="submit"]').should('be.visible').click();
    });
  });
});
```
### Cypress Version

10.4.0

**Comment by janyangyuan** [comment] 2022-08-08 08:25
i am trying Cypress v10.4.0 with Azure AD and facing the same issue also, after login successfully, it just hang there.

![cypress](https://user-images.githubusercontent.com/45619112/183373533-366d8b62-fe9f-46e4-8e2d-443dbd635325.PNG)

**Comment by AtofStryker** [comment] 2022-08-09 21:34
Hi @ieZaky. Thank you for opening an issue and giving the new `experimentalModifyObstructiveThirdPartyCode` flag a try. And welcome to the Cypress community! 

Would you be able to provide more details on your microsoftonline configuration? I noticed you have `sso_reload=true`. Also, have you tried moving the `cy.visit('https://organization_name.crm4.dynamics.com/main.aspx');` to before the `origin` command?

**Comment by ieZaky** [comment] 2022-08-10 10:14
@AtofStryker Thanks for your reply.  I actually don't have any configuration for microsoftonline or you can explain further what are you looking for so I can provide it, it's a very simple script where it just goes to the powerapps application page and while doing that its redirected to login page for microsoft where it inputs the email, password and clicks on login then its redirected back to the homepage for selected application. My script runs perfectly until it clicks on sign in,  I was able to fix the blank screen by disabling the CORS for chrome and edge however, I get another error now related to authentication shall I log it here or shall I log a new issue with it? thanks a lot in advance.

**Comment by AtofStryker** [comment] 2022-08-10 14:38
@ieZaky you can just log it here. Did you try moving the `visit` outside and before the `origin` block? Also, would you be able to try this with version `10.3.1` and see if you get the same results? Are you able to run with `DEBUG=cypress-verbose:proxy:http` and post the logs here with omitted sensitive data?

**Comment by ieZaky** [comment] 2022-08-11 09:13
@AtofStryker  Let me answer your questions in bullet points:

1. I tried to use visit outside origin yes and the result was that page does not load at, it keeps loading until timeout.
2. I can not use with 10.3.1 because of the frame busting, where when I try to visit powerapps application page, it must redirect me to microsoft to authenticate me and in 10.3.1 it used to framebust and close the cypress test window.
3. I'm able to do so yes but the log is way too big (toooo big) to even take a snapchat from so do you have a suggestion? or maybe am doing it in a wrong way if you can provide a quick tutorial link to do so would appreciate it. We can also schedule a quick meeting (if that's applicable) to show you a fast demo? let me know your thoughts.
(As I said am new to cypress so excuse me if am not providing the details in a correct manner am trying)

**Comment by AtofStryker** [comment] 2022-08-11 14:52
> 1. I tried to use visit outside origin yes and the result was that page does not load at, it keeps loading until timeout.

OK sounds like we can rule this out

> 2. I can not use with 10.3.1 because of the frame busting, where when I try to visit powerapps application page, it must redirect me to microsoft to authenticate me and in 10.3.1 it used to framebust and close the cypress test window.

Makes perfect sense. Sounds the like `experimentalModifyObstructiveThirdPartyCode` flag got you further so that's good!

> 3. I'm able to do so yes but the log is way too big (toooo big) to even take a snapchat from so do you have a suggestion? or maybe am doing it in a wrong way if you can provide a quick tutorial link to do so would appreciate it. We can also schedule a quick meeting (if that's applicable) to show you a fast demo? let me know your thoughts.
>    (As I said am new to cypress so excuse me if am not providing the details in a correct manner am trying)

@ieZaky no worries at all you are doing just fine. Reproducing here might be tricky, but I think we can get you going on the thread here.

if you are on a unix based system/subsystem, you should be able to pipe the debug logs to a file, like

```
DEBUG=cypress:*,cypress-verbose:proxy:http,-cypress:server:util:process_profiler npx cypress run 2> testoutput.log
```

I'd give the above a try and send over the `testoutput.log` if you can. We have more details on [troubleshooting](https://docs.cypress.io/guides/references/troubleshooting) that also might help set this up. I hope that helps!

**Comment by ieZaky** [comment] 2022-08-14 10:32
@AtofStryker  Sorry for the delay, kindly find 
[testoutput.log](https://github.com/cypress-io/cypress/files/9333189/testoutput.log)

attached the log file with omitted data.

**Comment by AtofStryker** [comment] 2022-08-15 21:02
@ieZaky thank you for sending that over. Almost looks like the server is a bit confused. Any idea what `top` is set to? Looks like it is expecting to go back to `http://localhost:53654` but then does a new visit entirely which then sets top to `https://organization.crm4.dynamics.com/` and then does a 302 redirect. Where is it supposed to return to?

**Comment by ieZaky** [comment] 2022-08-16 07:54
@AtofStryker I was actually confused with that local host redirection too, my script was supposed to re-direct to a page in powerapps application but that does not happen where authentication problem occurs (After logging in microsoft).

**Comment by ieZaky** [comment] 2022-08-16 14:20
@AtofStryker I don't use baseUrl no, is it mandatory?

**Comment by ieZaky** [comment] 2022-08-21 08:02
I tried setting the baseURL but with no result, still the same issue

**Comment by rachelruderman** [comment] 2022-08-25 17:17
@ieZaky can you attach the logs with `baseUrl` set? 🙏

**Comment by emilyrohrbough** [comment] 2022-09-06 13:59
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Closed by emilyrohrbough** 2022-09-06 13:59 UTC
Labels: stage: awaiting response, Needs Reproduction
